### ISSUE TITLE
A bug like the follow picture

### ISSUE THREAD

**Issue by netmou** [atom/atom#10011]
![default](https://cloud.githubusercontent.com/assets/7068058/11736852/e2969fde-a00d-11e5-90e6-7f42e316bfc6.png)

made by:remove all project folder in tree-view,then close the pane to close all opened file 
i can't duplicate the bug
os win10x64 atom v1.3

**Comment by lee-dohm** [comment]
Please let us know if you can get any more information. Also please try to reproduce this using Safe Mode:

To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/10011#issuecomment-163856211. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
