### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by SuperPrower** [atom/atom#10019]
**What i did:**
Nothing, just runned Atom. Uninstall and reinstall didn't helped. Neither themes nor packages were installed. 
Only clue is i was doing some business in my Ubuntu, then i rebooted and after i started Atom, this happened. But i didn't did anything to my Windows drive cause it was unable to mount. Sorry for my bad english.
**What i got:**
![bug1](https://cloud.githubusercontent.com/assets/10908110/11747615/554923ae-a035-11e5-9729-ffb3c6e4fc5c.PNG)
![bug2](https://cloud.githubusercontent.com/assets/10908110/11747616/5549df24-a035-11e5-8665-6921d78c1b3a.PNG)
![bug3](https://cloud.githubusercontent.com/assets/10908110/11747617/554eaf72-a035-11e5-8aef-17095670eb67.PNG)

**Comment by albertosantini** [comment]
Very similar to https://github.com/atom/atom/issues/10015

Try the suggestion to remove ` ~/.atom/blob-store`.
https://github.com/atom/atom/issues/10015#issuecomment-163942237

**Comment by SuperPrower** [comment]
@albertosantini, thanks you, this helped. I need to close the issue now, right?

**Comment by albertosantini** [comment]
I think so. Thanks. You are welcome.
