### ISSUE TITLE
When copy/paste same named file, new folder is created above working dir, dangerous

### ISSUE THREAD

**Issue by freed00m** [atom/atom#10024]
Hi, I have a working directory, (project's directory openned with atom)

/home/frdm/gDrive/3.1__Tretak ZS/ZSUR/zsur-sp

And when I try copy+paste a file from sidebar, in my case file
```
/home/frdm/gDrive/3.1__Tretak ZS/ZSUR/zsur-sp/app/source/data.txt
```
to (note that it will not fail when no "data.txt" file is inside)
```
/home/frdm/gDrive/3.1__Tretak ZS/ZSUR/zsur-sp/tomas/Skripty/
```

What should happen?
Nothing or maybe warning or overwrite confirmation dialog. 

What happens instead.
A new directory tree is created outside working directory (note that data has no postfix ".txt")
```
/home/frdm/gDrive/30.1__Tretak ZS/ZSUR/zsur-sp/tomas/Skripty/data
```

From my point of view it is completely dangerous behavior.

---

Arch linux with a kernel 4.3.1 and I am using systemd 228

Atom version 1.3.1

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tree-view? Thanks!
