### ISSUE TITLE
tab switching with unsaved files

### ISSUE THREAD

**Issue by Giah** [atom/atom#10020]
CTRL+TAB do not take into considerations tabs for unsaved files

**Comment by mnquintana** [comment]
I'm not sure what you mean - could you elaborate on what behavior you were expecting vs what actually happened?

**Comment by Giah** [comment]
if you create a new file and this is still unsaved, hitting CTRL+TAB (I'm on windows) just skip that tab, like it doesn't exists at all.

**Comment by doodhwala** [comment]
I think this issue has been fixed.
Do close it after confirming.

**Comment by Giah** [comment]
@doodhwala solved
