### ISSUE TITLE
Atom freezes with split panes on OS X

### ISSUE THREAD

**Issue by evanlucas** [atom/atom#10026]
To reproduce:

```sh
$ mkdir -p atom_test/{lib,test}
$ cd atom_test
$ touch lib/transport.js test/transport.js
```

Add some content to the two files. Open one of the files and then split the pane vertically. After splitting the panes, atom freezes and requests to close. 

It only seems to happen if the filename is the same, but they are in different directories. (`test/transport.js` and `lib/transport.js`)

Atom version: v1.3.1
Darwin Mac-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64

What is really weird is that it just started doing it out of the blue. I have tried removing ~/.atom/storage and it still does not work.

**Comment by kwilcox** [comment]
This just started happening to me today as well... very strange!

**Comment by bwalsh** [comment]
I'm having a similar problem,  Atom freezing with  "Editor not responding".
I can't tie it down to any one particular action.   It has been stable for months, no new installs, etc.
Just started happening today

```
$ atom --version
1.3.1
```

**Comment by erikanderson** [comment]
Also seeing this when using https://atom.io/packages/pane-layout-plus

**Comment by chrishiestand** [comment]
Same here, didn't happen with v1.2.

**Comment by chrishiestand** [comment]
v1.4.0-beta0 doesn't seem to be effected :+1:

**Comment by glued** [comment]
+1 on 1.3.1 and wasnt happening on 1.2

**Comment by iclanzan** [comment]
Same here, can’t use Atom at all anymore. It freezes completely every 5 minutes.

**Comment by rustanacexd** [comment]
+1 mine crashes with split plane. The problem occured with the latest update.

**Comment by 50Wliu** [comment]
Based on what @chrishiestand said, could other people please try 1.4.0-beta0 and see if that fixes their issue?

**Comment by nehz** [comment]
+1 getting random freezes too, such as when using `ctrl-p` -> select file -> enter will crash on some files.

**Comment by bwalsh** [comment]
installed beta - all is well

```
$ atom-beta -version
1.4.0-beta0
```

**Comment by 50Wliu** [comment]
Ok, thanks for the update!

**Comment by erikanderson** [comment]
Is this closed because beta fixes it?

**Comment by 50Wliu** [comment]
Yes.  If we figure out exactly what changes causes it, the Atom team might consider releasing a patch fixing this in stable.

**Comment by evanlucas** [comment]
I can confirm that the beta version is not showing this same problem. I'll dig in and see if I can tell what's going on. Thanks!

**Comment by erikanderson** [comment]
I ran the dev console and had it crash on me but no errors popped up so I guess I will use beta till this is fixed in the main release. If anyone else is wondering, use `atom-beta` to open the beta from the command line.

**Comment by khrykin** [comment]
Still having frequent freezes on OS X 10.10.4 even in `atom-beta` and even in safe mode AND even without splitting panes. Happens on UI interactions or when window loses focus...
`atom --version : 1.3.1`
`atom-beta --version : 1.4.0-beta0`

**Comment by chrishiestand** [comment]
@khrykin I've had zero freezes with 1.4.0-beta0 under OS X 10.11.1 and heavy usage. I'm not saying that upgrading to El Cap will fix the problem, just giving a data point. Since this is a split pane issue specifically, maybe there is a more appropriate issue for this topic? Or maybe you can create one.

**Comment by khrykin** [comment]
@chrishiestand Thanks for your point. Yes, this is probably not related to this issue, but I thought it was, until I get last freeze in single pane mode, so maybe frequency of freezes depends on number of panes.

**Comment by nehz** [comment]
also freezes on Windows 7

**Comment by YoYuUm** [comment]
It's still happening in 1.3.2

**Comment by 50Wliu** [comment]
Please update to the 1.4 betas if you are experiencing this issue, and refrain from posting "me too" comments, as that doesn't help.  Thanks!

**Comment by 50Wliu** [comment]
1.3.3 has just been released which fixes this issue.  Sorry for the delay.
