### ISSUE TITLE
Scrollbars can't be styled without making them visible the whole time

### ISSUE THREAD

**Issue by leo** [atom/atom#10025]
It sounds funny, I know. But it looks like it's currently not possible to style the editor's scrollbars without making them visible the whole time. Just try it: Add some stylings to your theme's stylesheet and suddenly the scrollbars will be visible the whole time.

I've tried it, too. If you want to see an example, just clone [material-ui](https://github.com/leo/material-ui/blob/master/styles/atom.less) and comment out the last few lines. Usually, this should just change the look of the scrollbars. But what it really does is making the scrollbars visible the whole time (independed from your OS' settings).

I also haven't yet seen a theme that managed to style them without making them visible the whole time. Would be awesome if this could be fixed! :see_no_evil:

**Comment by simurai** [comment]
> But it looks like it's currently not possible to style the editor's scrollbars without making them visible the whole time.

It's the same behavior found in Chrome/Safari. Not sure what the exact reason is, but unpredictable custom styling of the "disappearing" scrollbars might impact scrolling performance. So they decided to keep them un-style-able.

Atom could implement their own scrollbars that disappear and that you could restyle, but would open up the risk of making scrolling less smooth.

**Comment by leo** [comment]
Interesting! I'd say that implementing custom scrollbars that disappear and that you could restyle shouldn't even be a possibility here (at least if you want to do it with HTML, CSS & JS), because it seems very messy to me.

So let's wait for the Webkit guys to fix it! (It's a Webkit-related bug, right? Because then I think reporting the bug would help - I can do it, if you want.)

**Comment by simurai** [comment]
> It's a Webkit-related bug, right?

Feel free to make an issue, but it might be intentional. To make sure scrolling performance doesn't suffer when it gets custom styled.

**Comment by leo** [comment]
@simurai I don't really understand why this should affect scrolling performance. I mean it's already possible to style those that are always shown. Therefore it could only affect the performance of the show/hide effect, if you ask me.

Because of this, I don't understand why this should be intentional... :v:

**Comment by simurai** [comment]
I don't know enough to be sure, but when the scrollbar is visible all the time, it occupies its own space with an opaque background. When the scrollbar disappears, it's on top of content with a transparent background. Custom styling might not play nice all the time.

But yeah, just some guessing. :innocent: To be sure, making a bug report should clarify it better.

**Comment by leo** [comment]
@simurai That's interesting! Haven't considered this. I'll create a bug report.

**Comment by leo** [comment]
@simurai Here it is: https://bugs.webkit.org/show_bug.cgi?id=152226

**Comment by simurai** [comment]
@leo The issue you opened will be for Safari.

Atom uses Electron, which uses Chrome/Chromium. So you might also wanna open an issue here: https://code.google.com/p/chromium/issues/list

**Comment by leo** [comment]
Whoops! :speak_no_evil: I honestly thought that Chrome still uses WebKit, but now I know that they're using their own fork since version 28. Bug [reported](https://code.google.com/p/chromium/issues/detail?id=569477) again.

**Comment by simurai** [comment]
Great. I :star:ed it. Let's see if there is a specific reason behind it.

**Comment by leo** [comment]
If you ask me, it's time to close the issue. I mean, it's not something that can be solved internally in Atom, but rather something that needs to be fixed by browser vendors. :innocent:

**Comment by simurai** [comment]
@leo thanks for creating that bug report. https://code.google.com/p/chromium/issues/detail?id=569477

There has been some activity but it doesn't sound like it's getting fixed soon. I'll keep it stared anyways.

**Comment by leo** [comment]
@simurai Yep. I'll keep an eye on them, too!
