### ISSUE TITLE
Color picker returns invalid HEX string.

### ISSUE THREAD

**Issue by silvestreh** [atom/atom#10033]
When using the color picker in a package's settings, the `.toHexString()` method sometimes returns invalid HEX values for dark colors (close to black).

I resorted to catching those invalid colors using `tinycolor`'s `isValid()` method…

```javascript
atom.config.onDidChange('atom-material-ui.colors.accentColor', (value) => {
    var accentColor = tinycolor(value.newValue.toHexString());

    if (!accentColor.isValid()) {
        return atom.notifications.addError(`The selected color <code>${value.newValue.toHexString()}</code> is not a valid HEX value. Try another!`, { dismissable: true });
    }
    amu.writeConfig()
});
```

**Comment by lee-dohm** [comment]
Is this on the correct repository? (I freely admit that I could have completely spaced the addition of a color picker to Atom :laughing:)

**Comment by silvestreh** [comment]
@lee-dohm I'm not exactly sure this is the right repository, but it was my best guess. Just to be clear, I'm not talking about the [color-picker](https://atom.io/packages/color-picker) package. I'm talking about the color picker Atom gives us developers for our package's settings:

```javascript
"baseColor": {
    "title": "Primary color",
    "description": "Changes the main theme color.",
    "type": "color", // <-- This one!
    "default": "#009688"
},
```

Looks like this on OS X:

![captura de pantalla 2015-12-13 a las 2 58 24](https://cloud.githubusercontent.com/assets/1133339/11765770/797a4238-a145-11e5-8ffc-f3f455048907.png)

When changed, the `value.newValue` property is a `Color` object:

![captura de pantalla 2015-12-13 a las 3 04 38](https://cloud.githubusercontent.com/assets/1133339/11765793/7ef4c02a-a146-11e5-96a3-7e04be8435d2.png)

And its `toHexString()` method *sometimes* produces invalid HEX color strings. It happens with dark colors mostly.

**Comment by lee-dohm** [comment]
Ah ok, this should probably go on the [settings-view repository](https://github.com/atom/settings-view) then.

**Comment by silvestreh** [comment]
Thanks… I'll repost there.
