### ISSUE TITLE
Atom 1.3.1 not responding when started with files/directories in the workspace

### ISSUE THREAD

**Issue by andradei** [atom/atom#10036]
After 1.3.1 update. Running `atom .` from the shell will result in the message seen below, which never recovers from. Even starting it by clicking on its app icon (OS X) will result in the same situation.

Only after several random attempts Atom will start with no files or directories on the workspace (only a blank, unnamed file) and will work normally.

<img width="423" alt="screen shot 2015-12-12 at 12 54 59" src="https://cloud.githubusercontent.com/assets/2653546/11763631/f0ec11b4-a0cf-11e5-8bc0-8d8f9c991f03.png">

**Comment by andradei** [comment]
How can I further troubleshoot this?

**Comment by 50Wliu** [comment]
@andradei Can you try installing Atom 1.4.0-beta0 and see if that resolves your issue?  Thanks!

**Comment by entr** [comment]
Same issue, worked well for a while but suddenly won't start. `$ atom --safe` doesn't have an effect however:
```
➜  ~  atom --version
1.3.1
```
```
/home/zlatev/.atom/packages (19)
├── docblockr@0.7.3
├── editorconfig@1.2.2
├── file-icons@1.6.13
├── file-type-icons@0.7.4
├── highlight-selected@0.11.1
├── linter@1.11.3
├── linter-jshint@1.2.1
├── linter-php@1.1.6
├── linter-phpcs@1.3.0
├── linter-scss-lint@2.4.0
├── minimap@4.18.0
├── minimap-highlight-selected@4.3.1
├── minimap-linter@1.0.0
├── minimap-selection@4.3.1
├── phpcbf@0.2.1
├── project-manager@2.6.5
├── tag@0.3.0
├── wordpress-api@1.2.1
└── wordpress-dictionary@4.4.0
```

```DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
/etc/lsb-release (END)
```

**Comment by entr** [comment]
Ok, I feel I must add that the last time I used atom before it went not responding I was trying to edit files on mounted FTP. My guess is it was trying to load files and folders from that session. However after system restart atom loads properly again.

**Comment by andradei** [comment]
@50Wliu This is the most weird thing I've ever seen on an app release. I installed the beta version as you suggested, ran it, it worked, than I ran the stable release and now it works too.

I restarted and removed Atom Beta. Everything is working fine.
