### ISSUE TITLE
Add Auto Indent shortcut

### ISSUE THREAD

**Issue by albertonaperijr** [atom/atom#10038]
Is it possible to add an Auto Indent shortcut just like in Netbeans IDE on windows (Alt + Shift + F)?

Thanks.

**Comment by maxbrunsfeld** [comment]
I think you should just need to add this to your `keymap.cson`:

```coffee
'atom-text-editor':
  'alt-shift-F': 'editor:auto-indent'
```

Let me know if this does not work for you.

**Comment by albertonaperijr** [comment]
@maxbrunsfeld Thanks. I'll try that.
