### ISSUE TITLE
Atom crashing my computer

### ISSUE THREAD

**Issue by joey192** [atom/atom#10039]
Atom crashing my computer

**Reproduction Steps:**
1. Go to the 'Settings menu'
2. Go to the 'Themes' tab
3. Change the theme by using any of the drop down menu

I was expecting it to change themes but then it shows an empty box with no themes indexed, no font visible, and then my computer freeze. I then have to manually restart it. It happens in safe mode too.

Atom version:   Atom 1.3.1
OS and version:   Ubuntu 14.04.3 with 'kernel 3.19.0-39'

**Installed packages:**

.deb from the main page of the atom website :  https://atom.io/

**Additional information:**
- Problem can be reproduced in safe mode: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by joey192** [comment]
`Failed to load config.cson
[stdin]:1:4: error: unexpected 
���[1;31m[0myE�� �v�����fk���+��tǺ�7㠩R�:r��:#��u��N#�I�V��)RՔ�ڪ�\�p���jdM�[M��Fo�ف;�tZ�$�] ���;:`��\mKo���
[1;31m   ^[0m`

By the way, I now have this pop-up when I start Atom.

**Comment by Zireael07** [comment]
O_o

Your config.cson file seems to be corrupted. Navigate to where you installed Atom and delete config.cson, thus forcing Atom to regenerate it.

**Comment by joey192** [comment]
[Enter steps to reproduce below:]

1. ...uh... clearing config.cson.
2. start atom

**Atom Version**: 1.3.1
**System**: Ubuntu 14.04.3
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.0


### Stack Trace

Uncaught TypeError: _statusBarItem2.default is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:85

TypeError: _statusBarItem2.default is not a function
    at Object.consumeStatusBar (/usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:85:23)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by joey192** [comment]
[Enter steps to reproduce below:]

1. restart atom...
2. use atom
3. close atom
?. ???
4. get the error again

**Atom Version**: 1.3.1
**System**: Ubuntu 14.04.3
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.0


### Stack Trace

Uncaught TypeError: _statusBarItem2.default is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:85

TypeError: _statusBarItem2.default is not a function
    at Object.consumeStatusBar (/usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:85:23)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "idiomatic-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.14
idiomatic-dark-syntax, v0.1.3
minimap, v4.18.0
pigments, v0.19.3

# Dev
No dev packages
```

**Comment by joey192** [comment]
Atom seems to be working now thanks @Zireael07. But the 2 last post are still prompts I get each time I launch Atom.

**Comment by 50Wliu** [comment]
@joey192 based on a very similar report over at atom/line-ending-selector#9, could you try deleting the `~/.atom/compile-cache` folder and see if that makes the errors go away?  Thanks!

**Comment by joey192** [comment]
@50Wliu => I just did that, but then I can't change my theme without my computer crashing again.

**Comment by 50Wliu** [comment]
Looks like we're in a pretty vicious cycle then :(.  Did your config.cson get corrupted again?

**Comment by joey192** [comment]
I doesn't happen when I use the kernel that comes with Ubuntu, must be my fault...

**Comment by 50Wliu** [comment]
This is still pretty weird though.  I'll cc @zcbenz just to be safe.

**Comment by joey192** [comment]
@50Wliu Thanks, appreciated.

**Comment by cchanna** [comment]
I've been getting the initial error reported here, and none of the suggested solutions have fixed it.

**Reproduction**
Open Atom, open settings, navigate to themes and attempt to change the theme. The dropdown list is empty, and the computer freezes completely, forcing a hard reset

- Ubuntu 14.04.3
- Occurs on Atom installed from the .deb on the front page, as well as when building it from the source and deleting ~/.atom 
- No packages installed

**Comment by komali2** [comment]
Having this issue as well, Ubuntu 15.04. Happy to provide any information if instructed how to do so. Opening theme drop downs causes full system hang and forces hard restart.

**Comment by lee-dohm** [comment]
Please include the exact version of Atom with any bug reports. You can copy it from the About screen or using `atom --version`.
