### ISSUE TITLE
Pipe symbol subscript in Markdown mathmode syntax highlighting wrong

### ISSUE THREAD

**Issue by liamdiprose** [atom/atom#10032]
Writing a pipe symbol followed by an underscore, `|_` (for subscript in math-mode) makes the syntax highlighter think any text after is emphasised. The highlighting can be escaped using two underscores, but I don't think this should happen in the first place (unless there is some reason I am not aware of yet).

![atom_markdown_highlighing_error](https://cloud.githubusercontent.com/assets/1769386/11759700/d6ea2b5a-a0e5-11e5-9292-15dfbcf850f3.png)

**Comment by lee-dohm** [comment]
I don't know that the [language-gfm package](https://github.com/atom/language-gfm) supports math-mode? If it does, this should be reopened on the language-gfm repository.

**Comment by liamdiprose** [comment]
Sweet, thank you.
