### ISSUE TITLE
Atom update procedure gets caught in F-Secure

### ISSUE THREAD

**Issue by csholmq** [atom/atom#10048]
![image](https://cloud.githubusercontent.com/assets/1297882/11774876/1bc5bb86-a23a-11e5-9c4c-21dc48775142.png)

Translated it says "New server program. A program is attempting to act as an Internet server."

This pops up every now an then. I'm guessing it has to do with `~\AppData\Local\atom\Update.exe --processStart atom.exe` being detected as a new program after update. 

Win 7
Atom 1.3.1

**Comment by damieng** [comment]
I don't think there is anything we can do about this - it's a limitation of the way F-Secure alerts for new programs.
