### ISSUE TITLE
Autocomplete box position glitch

### ISSUE THREAD

**Issue by socketubs** [atom/atom#10049]
Hi there,

I have tried to found if this bug has already been reported but it's not easy to search a glitch like that.
Every time I work with a split (like 2 columns), auto complete box is rendering at a bad position when I'm writing in the right column. Everything is fine when using left column.

![screenshot from 2015-12-14 10-08-33](https://cloud.githubusercontent.com/assets/293337/11777087/35e20a76-a24c-11e5-8094-eef078ac2ec5.png)

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/autocomplete-plus? Thanks!
