### ISSUE TITLE
Proposal: Add an "API Changes" section to change log information in Releases

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#10059]
With the huge glut of new information in the change log on Releases, it is unclear for package authors where they can go to get information specifically on API changes. We should create an "API Changes" section of all change logs to document any changes to APIs so that package authors can go one place to find such information without having to scour the entire change log.

**Comment by benogle** [comment]
I like this idea. Just chatted with lee and we talked about maybe adding an API label, then using that in the generation of the PR list.
