### ISSUE TITLE
ISO-encoded XML files open with wrong encoding

### ISSUE THREAD

**Issue by ujay68** [atom/atom#10052]
The attached XML file declares and uses ISO-8859-15 as its encoding, but it opens as UTF-8. The sample Euro character (U+20AC), coded as byte 0xA4 in that encoding, is not shown correctly. Atom 1.3.1 on OS X 10.11.2.

![iso-8859-15](https://cloud.githubusercontent.com/assets/3627476/11778519/1b1780fa-a255-11e5-87e1-e94dc1268326.png)

[ISO-8859-15.xml.zip](https://github.com/atom/atom/files/61041/ISO-8859-15.xml.zip)

**Comment by 50Wliu** [comment]
This is because the default encoding is UTF-8, and you have to manually auto-detect each file.
Please see atom/encoding-selector#24 (automatically auto-detect) and atom/encoding-selector#25 (auto-detect encoding in meta tags) for more details.

**Comment by ujay68** [comment]
IMO, this is a very unlucky design decision. The XML specification is very clear and also very explicit about how XML files are encoded and how that encoding should be detected by tools even in the absence of an explicit charset in the XML declaration. So if a tool like Atom does not follow the XML specification here, the risk of accidentally producing non-wellformed XML files when editing is very high. For me, forcing the user to manually select the encoding of an existing well-formed XML file is definitely a bug, not a lacking feature.
