### ISSUE TITLE
pixelPositionForScreenPosition randomly returns invalid x position

### ISSUE THREAD

**Issue by abe33** [atom/atom#10051]
As you can see in the gif below, some of my markers views get invalid x coordinates when I modify the buffer:

![screen-position-issue](https://cloud.githubusercontent.com/assets/247140/11777765/c08e151c-a250-11e5-9731-7027555b7257.gif)

In the gif above, the update of the views is scheduled on a new frame during the `did-change` event of the text editor. I have more or less the same result if I do the update immediately. And as far as I can tell it was still working properly last week.

**Comment by maxbrunsfeld** [comment]
Thanks for the report @abe33! Is this 1.3.0? Could you try to write up a minimal example that demonstrates the problem?

**Comment by abe33** [comment]
Hi @maxbrunsfeld, actually it's on master, I'll see if I can write a smaller example. But FWIW anyone with pigments installed on master should see that behavior.

**Comment by abe33** [comment]
Ok, so I still don't have a proper way to reproduce it in isolation, but I've somehow found a way for you to test it.

First I wrote this small snippet: 

```coffee
      e = atom.workspace.getActiveTextEditor()
      v = atom.views.getView(e)

      e.onDidChange ->
        markers = e.findMarkers(intersectsScreenRowRange: v.getVisibleRowRange())

        markers.forEach (marker) ->
          markerScreenRangeStart = marker.getScreenRange().start
          pos = e.pixelPositionForScreenPosition(markerScreenRangeStart)
          if pos.left is 0 and markerScreenRangeStart.column isnt 0
            console.log "failed at row #{markerScreenRangeStart.row}"
```
In my tests I put that code in a command in my init script.

Then take a file long enough to scroll (I don't seem to get that if the editor isn't scrolled) and that will have markers so that the snippet can iterate over them, like this one: https://github.com/abe33/atom-pigments/blob/master/CHANGELOG.md. 
It tried to run the snippet for every line, but as it was taking more time to perform I never got invalid results.

Scroll until you see the first spell-check decorations (around the v0.18.0 block), and start typing above these markers.

In my case I almost always get the following logs when adding a new line: 

```
failed at row 102
failed at row 102
```
Then if I remove the line I just added: 

```
failed at row 101
```

In the same time, I noticed that the decorations was moving around, jumping into random places: 

![screen-position-issue](https://cloud.githubusercontent.com/assets/247140/11815065/606aaac4-a34a-11e5-93c3-f7405d131743.gif)

Hope it helps.

**Comment by abe33** [comment]
Anyone who had tried this?
cc/ @atom/feedback

**Comment by JesseLeite** [comment]
Hey @maxbrunsfeld,

> Could you try to write up a minimal example that demonstrates the problem?

I explained a way to reproduce same issue at abe33/atom-pigments#124 (didn't realize this might be problem with atom core, and not atom-pigments).  Hope it helps!

**Comment by abe33** [comment]
I took some time to investigate, and I can give some more information. 

The reason we got 0 is because `lineNode` is `undefined` here: https://github.com/atom/atom/blob/master/src/lines-yardstick.coffee#L96.

It looks like it occurs when requesting the line node for a line that moved to a new tile. The call might be done before the `lines-tile-component` has updated its `lineNodesByLineId` map.

**Comment by nathansobo** [comment]
I'll take a look this week and we won't release until this is fixed.

**Comment by nathansobo** [comment]
Okay, I understand the problem now. This was caused by a change I made in #9947... The component currently relies on the model to determine if the DOM node in question needs to be rendered, but this doesn't always work because component updates asynchronously and so may not reflect the state of the model. Should have this fixed soon.
