### ISSUE TITLE
Document contract that can be depended upon for Promises returned from Atom APIs

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#10058]
API documentation that simply states "returns a Promise" is somewhat ambiguous. We need to document exactly what operations are valid for any Promise returned from an Atom API.

**Comment by maxbrunsfeld** [comment]
I think now that they're standard ES6 Promises, linking to the MDN docs for that class should be clear enough. What do you think @lee-dohm?

**Comment by lee-dohm** [comment]
I think that would be great. Can we make it so that all mentions of `{Promise}` link there?

**Comment by maxbrunsfeld** [comment]
Yeah, I think so. Looks like currently they're broken links...

**Comment by lee-dohm** [comment]
It looks like some documentation doesn't linkify the word "promise" so I'll go through and update those if someone can ensure that the documentation generator points the link to the right place.

**Comment by lee-dohm** [comment]
Looks like this should have been closed when the above pull request was merged. Closing now!
