### ISSUE TITLE
How to develop packages in ES6

### ISSUE THREAD

**Issue by gsklee** [atom/atom#10066]
I was unable to find this information inside the official documentation - how do I develop packages in ES6?

**Comment by paulcbetts** [comment]
You don't have to do anything special other than put `'use babel';` at the very top of all your JS files

**Comment by maxbrunsfeld** [comment]
Thanks @paulcbetts. @gsklee See the [line-ending-selector](https://github.com/atom/line-ending-selector) package for one example. Closing this out for now, but I can reopen if you run into any problems.

**Comment by gsklee** [comment]
@paulcbetts @maxbrunsfeld Cool! Thanks :smile:
