### ISSUE TITLE
Change an array configuration

### ISSUE THREAD

**Issue by joseramonc** [atom/atom#10064]
I have an array configuration in my package and gets retrieved fine. I'd like to change the default of that configuration through the settings view like a normal configuration.

My settings view with a config set as an array:
<img width="933" alt="screen shot 2015-12-14 at 7 43 28 pm" src="https://cloud.githubusercontent.com/assets/1993929/11799606/2db74c04-a29b-11e5-8aeb-7193935de96d.png">

Exepcted:
<img width="913" alt="screen shot 2015-12-14 at 7 47 54 pm" src="https://cloud.githubusercontent.com/assets/1993929/11799648/9bfd3c5a-a29b-11e5-9990-8818d806dc2a.png">

or something like that.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/settings-view? Thanks!
