### ISSUE TITLE
Add blank space at the bottom of code

### ISSUE THREAD

**Issue by miftahafina** [atom/atom#10069]
Is possible to make blank space at the bottom of code (like in sublime text), so I don't have to see the bottom of the screen when i'm writing.

**Comment by albertosantini** [comment]
See `Scroll Past End` setting in `Settings`.

It allows the editor to be scrolled  past the end of the last line.

**Comment by 50Wliu** [comment]
Thanks @albertosantini!

**Comment by miftahafina** [comment]
thank you :+1: @albertosantini

**Comment by Klerith** [comment]
Thx @albertosantini
