### ISSUE TITLE
1.3.1 doesn't save session on OSX 10.11.1

### ISSUE THREAD

**Issue by MaadMax** [atom/atom#10061]
I encounter an issue with project saving with Atom 1.3.1. Here's my config  :

```
"*":
  "exception-reporting":
    userId: "631146f8-69d1-b154-4734-012195c538f5"
  welcome:
    showOnStartup: false
  core:
    openEmptyEditorOnStart: false
  editor:
    invisibles: {}
    fontSize: 11
    backUpBeforeSaving: true
    showInvisibles: true
  pigments: {}
  "terminal-plus":
    core: {}
    style: {}
  "save-session":
    dataSaveFolder: "/Users/radev09/.atom/packages/save-session/projects"
```

Can't find any same issues. Does it comes from my config or is it an issue related to the OS or something else?

**Comment by 50Wliu** [comment]
Please try uninstalling the save-session package and trying again.

**Comment by MaadMax** [comment]
It works well, thanks 50Wliu! But I need to understand why it works when I remove this package. I guess more information are needed as mnquintana marked the issue. Thanks again, I will try to go deeper into this issue..

**Comment by 50Wliu** [comment]
> But I need to understand why it works when I remove this package.

Atom has offered this functionality since before 1.0.0, and so save-session has become mostly redundant (in fact, all of its features are now in Atom as in 1.4.0-beta0).  In addition, it seems to have stopped working entirely after Atom 1.2.0.

Glad you solved your issue!

**Comment by MaadMax** [comment]
Ok I now understand thanks a lot for all these explanations! Thank you!

**Comment by MaadMax** [comment]
Finally, I've again the same problem when I shut down the computer and when I restart it : I can't get my previous opened folders and files. Is there something else to do or is it a norma behavior of Atom?
