### ISSUE TITLE
Weird issue with backwardsScanInBufferRange on first buffer line

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#10075]
We've recently run into a weird issue with `TextEditor::backwardsScanInBufferRange` (see https://github.com/fcrespo82/atom-markdown-table-formatter/issues/23)

Consider this snippet:

```javascript
atom.workspace.getActiveTextEditor().backwardsScanInBufferRange(/./g, atom.workspace.getActiveTextEditor().getBuffer().getRange(), function(m) { console.log(m); m.replace(m.matchText+m.matchText); });
```

This should, as far as I can gather, duplicate every character in current editor's buffer.

On a buffer with empty first line, it evidently does, i.e. buffer text like this

```

abcdefg
hijklmn
opqrstu
vwzyz
```

becomes

```

aabbccddeeffgg
hhiijjkkllmmnn
ooppqqrrssttuu
vvwwzzyyzz
```

Note empty first line.
This is expected.

What is unexpected is if we take the same buffer without empty first line, e.g.

```
abcdefg
hijklmn
opqrstu
vwzyz
```

then it becomes

```
aabbccddeeffggdhhiijjkkllmmnnhooppqqrrssttuulvvwwzzyyzz
ooppqqrrssttuu
vvwwzzyyzz
```

Note how it gobbled up newlines and introduced duplication.

You can use code snippet mentioned above in dev.console to test this.

This is really strange. Hope that someone can shed some light on this behavior.
Looks like a bug if you ask me.

**Comment by lierdakil** [comment]
I believe https://github.com/atom/text-buffer/issues/111 might be related.

Also, this needs checking, but I bet that https://github.com/atom/text-buffer/commit/51782bdaa86540b226c615169a29287f26dac2d5 probably has something to do with this.

**Comment by lierdakil** [comment]
Yep, just tested. Reverting atom/text-buffer@51782bd fixes this issue.

@maxbrunsfeld, care to join this discussion?

**Comment by lierdakil** [comment]
A quick patch to `text-buffer`'s spec to test for this issue (this test is stupid, but it works -- use it to save some typing, not as the be-all and end-all)

```diff
diff --git a/spec/text-buffer-spec.coffee b/spec/text-buffer-spec.coffee
index e833b82..bc81738 100644
--- a/spec/text-buffer-spec.coffee
+++ b/spec/text-buffer-spec.coffee
@@ -2064,6 +2064,13 @@ describe "TextBuffer", ->
         expect(buffer.lineForRow(5)).toBe '      foo = items.shift();'
         expect(buffer.lineForRow(6)).toBe '      foo < pivot ? left.push(foo) : right.push(current);'
 
+      it "works well with backwardsScanInBuffer", ->
+        text = buffer.getText()
+
+        buffer.backwardsScanInRange /./g, buffer.getRange(), ({matchText, replace}) ->
+          replace(matchText+matchText)
+        expect(buffer.getText()).toBe text.replace /./g, (x) -> x+x
+
       it "allows the match to be replaced with the empty string", ->
         buffer.scanInRange /current/g, [[4,0], [6,59]], ({replace}) ->
           replace("")
```

**Comment by maxbrunsfeld** [comment]
Yeah, I think this is the same bug as https://github.com/atom/text-buffer/issues/111. I'm going to close this for now in favor of that issue. Thanks for the investigation @lierdakil! I'll look into it this week.
