### ISSUE TITLE
Do not handle package activation exceptions in test mode.

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#10079]
I've run into difficulty writing tests a few times when my package failed to activate but the test environment didn't have anything interesting in the console or test output indicating that's where it failed. In `package.coffee` we should just re-raise if we're in test mode rather than calling `::handleError`. I plan to do this today, just writing up this issue to remind myself when I switch contexts (or in case I never get to it!)

**Comment by maxbrunsfeld** [comment]
:+1: This will probably help a lot of people.

**Comment by kepta** [comment]
Hi, I am a new here. Can I work on this bug?

**Comment by maxbrunsfeld** [comment]
@kepta Absolutely! Thanks for taking an interest. Do you have the information you need?

**Comment by kepta** [comment]
@maxbrunsfeld I went through the docs and the source code specifically package.coffee.
In this file the ```@devMode``` is what seems relevant to me or is it? I am not able to get the complete idea, any pointers?

**Comment by b-lambert** [comment]
Is this still an open issue? If it's beginner-friendly I'd be happy to take it on.

**Comment by 50Wliu** [comment]
@b-lambert yes it is!

**Comment by SahilC** [comment]
Hi, I've made a PR #13119 for this bug. Could someone review it?
