### ISSUE TITLE
An issue with "Close Pane" option for a tab

### ISSUE THREAD

**Issue by varshit97** [atom/atom#10076]
[images.zip](https://github.com/atom/atom/files/63051/images.zip)
I opened 3 files.
I did not touch the first one but edited the 2nd and the 3rd files.
I then right clicked on the 1st tab and clicked on the close pane option.
Then dialog boxes popped saying that you did not save the other 2 files.
Close pane for each file should be separate right i.e close pane option for a tab should close only that tab.
The above attached folder has the sequence of 9 images showing the above explained behaviour.
This problem also came up in safe mode(i.e after creating an atom instance by running "atom --safe").

**Comment by maxbrunsfeld** [comment]
In Atom, a 'pane' is a container that can have multiple tabs. For example, by default you have one pane. If you split your editor vertically, you have 2 panes. Closing a pane closes all of its tabs. Maybe you meant to click `Close Tab`?
