### ISSUE TITLE
Editor crashes consistently with particular string

### ISSUE THREAD

**Issue by suzanne-stathatos** [atom/atom#10074]
The editor crashes when I hit the "r" in "n = nums.search...." 

I did this 4 times. After each crash, I quit the editor and reloaded a new instance. Each time, it crashed at the "r"

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by suzanne-stathatos** [comment]
Cool, updating from atom 1.0.19 to 1.3.1 seems to fix it. 

But, to provide more information, 
I am running MacOSX v10.10.4
I did not have Emmet installed
I updated before restarting using atom --safe, so didn't test out atom --safe.

**Comment by lee-dohm** [comment]
Great! Glad to hear it is fixed. I'm going to close this for now. Please let us know if it reoccurs.
