### ISSUE TITLE
Atom hangs when opening 2 files with same basename on different panes

### ISSUE THREAD

**Issue by fand** [atom/atom#10070]
Atom hangs when I open 2 files with same basename, such as `foo/index.js` and `bar/index.js`, on different panes.
It shows `Editor is not responding` dialog but `Keep Waiting` doesn't solve the problem.

**Reproduction Steps:**

1. Open `foo/xxx` file.
2. Move to other pane.
3. Open `bar/xxx` file.

It also hangs when creating new file from tree view.

**Expected behavior:**

Open `bar/xxx` file on the pane.

**Observed behavior:**

Hangs.

**Screenshots and GIFs**

![2015-12-15 17 05 50](https://cloud.githubusercontent.com/assets/1403842/11805328/2c280e1a-a34e-11e5-9366-b5f7ad8ccac7.png)

Here's a capture movie.
https://youtu.be/iuiGKC136OY

**Atom version:** 1.3.1
**OS and version:** OS X 10.10.5

**Installed packages:**

This is the result of `apm list`:
https://gist.github.com/fand/06d1780462609405b520

Anyway, the problem also happens on safe mode.

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

I'm not sure but issue #10067 seems similar to this problem.

**Comment by MethodGrab** [comment]
I was getting this in 1.3.1 as well. Try 1.4.0-beta0, that fixed it for me.
I'm on OS X 10.10.4.

**Comment by 50Wliu** [comment]
Yep, this has already been fixed in 1.4.0-beta0.
