### ISSUE TITLE
json parsing issues when default code page is changed (Windows 7)

### ISSUE THREAD

**Issue by JustEdro** [atom/atom#10082]
Registry key HKEY_CURRENT_USER\Software\Microsoft\Command Processor\Autorun on my machine is set to "chcp 1251".
Each network query (plugin searh, featured plugins list, etc..) causes an error:
Unexpected token �: ������� ������� ��������: 1251

Whenever I startup my CMD it writes: 
Microsoft Windows [Version 6.1.7601]
(c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.
Текущая кодовая страница: 1251

I think that the last line was unexpected somewhere in json porcessor.

You are welcome to ask me any additional info. 

UPD: deleting the key helped me to solve the problem, but it is just a workaround, I really need this key active. 

UPD2: I changed the key to "chcp 1251>NUL". It works fine now.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
* Can you replicate these issues using the command-line apm utility? (If you can, this really belongs on the https://github.com/atom/apm repository.)

**Comment by elartix** [comment]
+1

**Comment by damieng** [comment]
This looks like when we fire up a hidden command line to interact with apm is trying to read the output of the autorun commands. We can tell our instances of the command line to not run the autoruns.
