### ISSUE TITLE
Prompt before opening large files to avoid making the editor hang by mistake

### ISSUE THREAD

**Issue by zinkkrysty** [atom/atom#10086]
We know that atom hangs when opening big files (#979). Usually I don't intend to open big files, but sometimes I do because of using the CMD+T dialog too fast, so by mistake. Can we prevent this with a small action the user has to take before ? Given that the the user has to wait a while when the file is opened, I think that warning the user and prompting to open is a small request. Then your team can focus on improving performance without getting many users frustrated until then.

![atom_open_big_file](https://cloud.githubusercontent.com/assets/570771/11843199/7df7c7c0-a408-11e5-8a36-477638bbd884.png)

**Comment by Zireael07** [comment]
Good idea.

**Comment by alexandernst** [comment]
Or even better, just make it work with big files... once and for all.

**Comment by avdg** [comment]
If it's possible, it would be nice to include the file size so one could see the difference between a let's say 600kb, a 1.5mb file and for the extreme cases files bigger than let's say 50mb.

**Comment by samartioli** [comment]
This seems like a reasonable intermediate step until Atom supports large buffers. I was a very long time sublime user, and I am loving Atom the past couple weeks, but I'm starting to get very frustrated with clicking on build files and having atom hang and then have to force-quit.. 

As stated above, you could prompt before opening a file larger than 1mb. 

You could also show a unix head preview of the file even, and then have a button to open the rest, while showing the file size to the user. 

Again, 99% of my files are under 100 lines of code... but when I compile or bundle and then accidentally click on the file in the tree view... bad times.

**Comment by elijahmanor** [comment]
@mnquintana yeah, it'd be nice if the threshold could be customized in the main settings with a default value https://github.com/atom/atom/blob/1fac3cb4e2608402831600c5f63dae38329251b1/src/workspace.coffee#L515

**Comment by Krisa** [comment]
Also as temporary workaround, it could be great that when clicking on a large file (size configurable), atom opens the file in a basic editor (also configurable) which supports large file (e.g. notepad ++). We usually don't care of all the atom functionalities when opening very large file and a more primitive editor is just good enough.

**Comment by remexre** [comment]
Anyone working on a PR for @elijahmanor's idea? If not, would one be accepted?

**Comment by remexre** [comment]
Welp, made one and it passes CI.

**Comment by nathansobo** [comment]
@50Wliu can this be closed since we do prompt?

**Comment by 50Wliu** [comment]
Yup, since there is a prompt at 20MB I'm closing this.

**Comment by nrser** [comment]
@50Wliu is there a way to set that threshold?

i have a 3.1M js bundle and accidentally clicking on it locks Atom up for at least 20-30 seconds if it doesn't crash it entirely... with Atom 1.9.6 on a Mackbook pro with a 4 core 2.7GHz i7 and 16G RAM.

**Comment by 50Wliu** [comment]
Yep!  In newer Atom versions (either 1.10 or the upcoming 1.11, not sure which) there is a setting that controls when that prompt shows up.

**Comment by avdg** [comment]
I believed I saw this in the settings panel somewhere, but I'm not on the computer where I've tested this.

**Comment by remexre** [comment]
I wrote the setting; it's in 1.11.

**Comment by nrser** [comment]
awesome, thanks, looking forward to it
