### ISSUE TITLE
Stop  highlight text  after some characters 

### ISSUE THREAD

**Issue by burhandodhy** [atom/atom#10083]
After some number of character atom stop highlight the text .. currently im using one dark theme  but this problem in other themes as well .. 

![screenshot_13](https://cloud.githubusercontent.com/assets/7139602/11834495/d2f00ebe-a3ee-11e5-8bf0-7d1242f7f83d.png)

**Comment by Zireael07** [comment]
Duplicate of #1667

**Comment by 50Wliu** [comment]
Thanks @Zireael07!
