### ISSUE TITLE
OS X "Open With" Finder context menu points to previous version after an update

### ISSUE THREAD

**Issue by jokeyrhyme** [atom/atom#10081]
Just pressed the button to update Atom, which works great.

But noticed that if I right-click on a file in Finder and "Open With" -> "Atom", sometimes there will be multiple Atom entries, and sometimes the solitary entry will be for the old version.

Is there a way to thoroughly conceal old versions of Atom from OS X so the only default behaviour is to use the latest version of Atom (instead of old versions)?

**Comment by lee-dohm** [comment]
This is a [known issue with OS X](http://apple.stackexchange.com/questions/22661/problem-with-open-with-menu) that Atom doesn't have any direct control over. Essentially the service that populates that menu doesn't update constantly. See my link above for more information and solutions.

**Comment by jokeyrhyme** [comment]
The answer there refers to a command that can trigger a launcher service rebuild:
`/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user`

Could Atom not automatically run this itself after an update? Or offer to run it?

**Comment by lee-dohm** [comment]
Could Atom run that action? Yes. Should Atom take undocumented corrective action that could have unforeseen consequences for the user's other programs? No.
