### ISSUE TITLE
Atom Fails to Initialize

### ISSUE THREAD

**Issue by cooperpellaton** [atom/atom#10096]
I did not update Atom or run a brew update, and now, seemingly out of nowhere, Atom will not launch. This is what I see upon the application opening. 
![screen shot 2015-12-16 at 7 47 26 pm](https://cloud.githubusercontent.com/assets/5178017/11858254/f1e7bd32-a42d-11e5-886b-96591bae5da3.png)

I have tried uninstalling and then reinstalling (using appcleaner to remove dependencies) as well as installing through brew cask and all to no avail. I'm not sure what the error is here but even when I have the application open I cannot access any of the menus to even check for or run through an update flow.

![screen shot 2015-12-16 at 7 49 01 pm](https://cloud.githubusercontent.com/assets/5178017/11858300/52bf7104-a42e-11e5-91f7-f168f4a52f27.jpg)

**Comment by cooperpellaton** [comment]
It turned out to be a corrupted `config.cson` file. Not sure how this occurred.

**Comment by 50Wliu** [comment]
Nice to know that you got it fixed @cooperpellaton!

In the future, if this happens again, you can find out what the error is by pressing the red x button (with a `1` next to it) in the corner of the dev tools.
