### ISSUE TITLE
Atom 1.3.1 Hangs when opening files of the same name in similar folder names

### ISSUE THREAD

**Issue by kinseyost** [atom/atom#10092]
[crashTest.zip](https://github.com/atom/atom/files/64668/crashTest.zip)
Directions to reproduce:
1. Unzip file.
2. Open the root folder of the zip as a project
3. Open all of the index.js files
4. Upon opening the third index.js file, Atom will hang.

**Comment by itaylor** [comment]
Same issue is happening for me with Atom 1.3.2 on Mac 10.11.2, even in Atom safe mode.

`atom --safe crashTest`
use the file tree to `parent1/subfolder1/index.js`, then `parent2/subfolder1/index.js`, then `parent2/subfolder2/index.js`

It looks like it's probably related to the tab renaming code.

**Comment by kmcnellis** [comment]
I have the same issue

**Comment by 50Wliu** [comment]
This has already been fixed in the 1.4.0 betas.
