### ISSUE TITLE
Restore open files etc. from previous session

### ISSUE THREAD

**Issue by distantnative** [atom/atom#10090]
I am really missing that Atom doesn't restore the open files/tabs, expanded tree view structure etc. from the previous session once I re-open it. Would make my work much easier.

**Comment by 50Wliu** [comment]
@distantnative What Atom version are you using?

**Comment by distantnative** [comment]
Version 1.3.1

Packages:
├── autoclose-html@0.19.0
├── autocomplete-php@0.3.7
├── color-picker@2.0.14
├── dash@1.5.0
├── docblockr@0.7.3
├── emmet@2.3.17
├── file-icons@1.6.13
├── highlight-selected@0.11.1
├── javascript-snippets@1.0.0
├── jquery-snippets@11.0.0
├── language-htaccess@0.1.1
├── linter@1.11.3
├── linter-csslint@1.1.0
├── linter-htmlhint@0.2.1
├── linter-jshint@1.2.1
├── linter-php@1.1.6
├── linter-sass-lint@0.4.3
├── merge-conflicts@1.3.7
├── minimap@4.18.1
├── minimap-autohide@0.10.1
├── minimap-bookmarks@0.2.0
├── minimap-cursorline@0.1.0
├── minimap-find-and-replace@4.4.0
├── minimap-git-diff@4.1.8
├── minimap-hide@0.3.0
├── minimap-highlight-selected@4.3.1
├── minimap-linter@1.0.0
├── minimap-pigments@0.1.7
├── minimap-selection@4.3.1
├── pigments@0.19.3
├── project-manager@2.6.5
└── regex-railroad-diagram@0.10.4

**Comment by distantnative** [comment]
Ok sorry, my bad. Had also "save-session" installed when this occurred. Now I noticed it works after that one was uninstalled.
