### ISSUE TITLE
Crash when dragging already present file to a pane

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#10109]
1. Open a file.
2. `Cmd+K, right` to open it in a neighboring pane.
3. Drag the new view into the original pane.
4. Atom crashes.

This should have worked fine. There should be no problems with multiple tabs simultaneously editing one file.

**Comment by 50Wliu** [comment]
@alexchandel Can you try the 1.4.0 betas please?

**Comment by alexchandel** [comment]
@50Wliu Crash is gone, but I got Uncaught TypeError #9918 when I edited some text in one of the panes and undid it, so it may still need some work, or that may be unrelated.

**Comment by 50Wliu** [comment]
> that may be unrelated

Yeah, we've been getting a few reports of that exception.  I'm going to re-open that issue since it doesn't appear to be solved.
