### ISSUE TITLE
Add a git commit editor to Atom like in VS Code

### ISSUE THREAD

**Issue by NoNameProvided** [atom/atom#10106]
The "commit builder" is a really good feature of the VS Code, is there any plane to make something similar in Atom in the future? 

![screenshot 1](https://cloud.githubusercontent.com/assets/4706265/11870773/e4095ef8-a4ca-11e5-95e3-b02149c84ef1.png)

**Comment by alexchandel** [comment]
@NoNameProvided Maybe something like [git-control](https://atom.io/packages/git-control)?

**Comment by lee-dohm** [comment]
There are currently [no plans to add this functionality to Atom](https://discuss.atom.io/t/version-control-support/475/4?u=leedohm). However, there is a wide selection of Git packages for Atom available at https://atom.io/packages.
