### ISSUE TITLE
Cannot rename project folder

### ISSUE THREAD

**Issue by vrusinov** [atom/atom#10108]
I can't seem to be able to rename or otherwise change title of a folder in sidebar.

Steps to reporoduce:

1. Add new project folder. If that matters, this is huge directory on a filesystem mounted over not-so-fast fuse, some parts of it are read-only, I think parent folder of the project is read-only.
2. Notice that display name is not very useful (too generic in my case - I will likely end up with many folders with the same name); try to rename it.

Expected result:

- I can change display name of the folder.
- Or, at least, I get meaningful error message

Actual result:

- Nothing happens - no rename, no error.

Confusion:

- Does 'rename' means rename on filesystem or is it only changing display name?

Atom 1.3.1-3937312 (built from source if that matters)

**Comment by amytruong** [comment]
I think this issue is related to https://github.com/atom/atom/issues/3306 but not quite sure so I'll leave it open for now. @lee-dohm, feel free to confirm or clarify since we spoke about this one. Thanks!

**Comment by thetalloneweb** [comment]
I have the same end problem but different circumstances. 

Verison: Atom 1.4.0. 
OS: Windows 8.1

Not a huge project folder, not a networked folder. Same steps to reproduce.

**Comment by dody87** [comment]
Same problem, I can't rename project folder.

Version: 1.5.3
OS: OSX El Capitán.

**Comment by Turqueso** [comment]
same problem.
atom: 1.5.4
OS: OS X 10.9.5

**Comment by boneskull** [comment]
Confirmed in Atom 1.10.2 on Sierra.

Folder is on case-sensitive FS

**Comment by Ben3eeE** [comment]
Duplicate https://github.com/atom/tree-view/issues/179
