### ISSUE TITLE
Editor becomes unresponsive when switching windows

### ISSUE THREAD

**Issue by HybridFox** [atom/atom#10107]
Everytime i switch back to the editor, it freezes for around 5-20 seconds.
I'm on windows 10 with atom 1.3.2

**Comment by HybridFox** [comment]
This only seems to happen when i open a project folder that is also used with github

**Comment by maxbrunsfeld** [comment]
Could you record and share a CPU profile of what's going on after you change the window focus (`Profiles > Collect JavaScript CPU Profile` from the dev tools)?

**Comment by HybridFox** [comment]
Github seemed like it wouldnt want to accept a ZIP of it so i uploaded it to here:
https://mega.nz/#!5JwCHKbL!IflE76hVMnGnQDyAfrc7WX9RVaZGvH6c4WLxwnB27jU
Here is a screenshot with the most longest taking processes: http://prntscr.com/9fejz0

**Comment by HybridFox** [comment]
Any updates on this? It is really anoying to use my editor like this

**Comment by neumond** [comment]
Almost same issue on linux. On every focus gain atom spawns bunch of short living child processes. In any possible case this _is_ suboptimal and must be eleminated. Here is ```ps``` snapshot:

```
neumond  19134 19089  9 339214 249676 1 06:21 tty2     00:12:52 /usr/share/atom/atom --type=renderer --js-flags=--harmony --no-sandbox --lang=ru --node-integration=true --enable-delegated-renderer --num-raster-threads=1 --gpu-rasterization-msaa-sample-count=8 --content-image-texture-target=3553 --video-image-texture-target=3553 --disable-accelerated-video-decode --channel=19087.1.2018850289 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
neumond  23409 19134 60 223809 60760  1 08:34 tty2     00:00:00 /usr/share/atom/atom --eval require('/usr/share/atom/resources/app.asar/src/compile-cache.js').setCacheDirectory('/home/neumond/.atom/compile-cache'); require('/usr/share/atom/resources/app.asar/src/task-bootstrap.js');
neumond  23410 19134 56 223958 60180  0 08:34 tty2     00:00:00 /usr/share/atom/atom --eval require('/usr/share/atom/resources/app.asar/src/compile-cache.js').setCacheDirectory('/home/neumond/.atom/compile-cache'); require('/usr/share/atom/resources/app.asar/src/task-bootstrap.js');
neumond  23411 19134 53 222945 58856  0 08:34 tty2     00:00:00 /usr/share/atom/atom --eval require('/usr/share/atom/resources/app.asar/src/compile-cache.js').setCacheDirectory('/home/neumond/.atom/compile-cache'); require('/usr/share/atom/resources/app.asar/src/task-bootstrap.js');
neumond  23412 19134 48 222697 58104  1 08:34 tty2     00:00:00 /usr/share/atom/atom --eval require('/usr/share/atom/resources/app.asar/src/compile-cache.js').setCacheDirectory('/home/neumond/.atom/compile-cache'); require('/usr/share/atom/resources/app.asar/src/task-bootstrap.js');
```

**Comment by HybridFox** [comment]
Hey, I solved this issue by removing Git, not idea why it worked but it
solved The issue

**Comment by dthettich** [comment]
@HybridFox You mean by removing all of git's installation executables?

**Comment by HybridFox** [comment]
Yes, that's correct

**Comment by dthettich** [comment]
Oh boy, I thought so... That's a pretty impractical solution for most productive environments where code versioning is essential. I can't believe it is supposed to be an issue with too little RAM.

**Comment by HybridFox** [comment]
I have 8GB of RAM and it still happends to me

2016-04-06 13:43 GMT+02:00 Dirk Tassilo Hettich <notifications@github.com>:

**Comment by dthettich** [comment]
Same here. Usually, I consider 8 GB too little for heavy data analytics I do, but for sinple code editing this should suffice.

**Comment by anyssa** [comment]
I'm having the same issue. 

CPU profile points to `refreshStatus` too. This started few days ago. My repo has a few months, and it's a WordPress installation, I'm editing mostly PHP and SCSS files. 

I'm running Atom 1.8.0 in Windows 7 i7 4GB.

**Comment by anyssa** [comment]
Just found a workaround, maybe it could help someone else.
It seems it could be an anti-virus issue.

[https://discuss.atom.io/t/possible-temp-fix-windows-freeze-when-switching-back-to-atom/26563](https://discuss.atom.io/t/possible-temp-fix-windows-freeze-when-switching-back-to-atom/26563)

**Comment by HybridFox** [comment]
Would be weird, since i was only running Windows Defender when the issues started happening

**Comment by k00p** [comment]
Same issue here. Running Windows 7 (if you want more on my environment I will give it, but seems irrelevant given that the same issue is there in Mac/Windows/Linux).

![image](https://user-images.githubusercontent.com/6538605/29144571-43d2da0e-7d0e-11e7-9fc7-b4c9bbb54713.png)

When Atom gains focus, it spawns five processes, one at a time. It then kills each in reverse order. After the last one disappears, focus is given to the App window. The command line call for all five of the processes is:
```
C:\Users\notme\AppData\Local\atom\app-1.19.0\atom.exe C:\Users\notme\AppData\Local\atom\app-1.19.0\resources\app\src\task-bootstrap.js C:\Users\notme\.atom\compile-cache C:\Users\notme\AppData\Local\atom\app-1.19.0\resources\app\src\repository-status-handler.js
```
From that and from the @HybridFox Linux output, seems like the compile-cache.js calling behavior is worth looking into. 

Using Atom in a setting where you have to switch often between Apps is seriously annoying/problematic (5-10 seconds between clicking on Atom and getting a cursor) with this issue. I don't think this "fits" under the [PR #30](https://github.com/victor-torres/atom-hg/pull/30) as it is remains a problem on both the beta and v1.19.

**Comment by HybridFox** [comment]
Damn I forget I created this issue, weird that this is still not fixed.
