### ISSUE TITLE
Release Notes is outdated

### ISSUE THREAD

**Issue by yamsellem** [atom/atom#10103]
Displaying the releases notes (help > Release Note) displays releases until 1.1.0.
But the last Atom release is 1.3.2 (About Atom displays this proper release).

**Comment by 50Wliu** [comment]
This is a duplicate of atom/release-notes#39 - please subscribe there for updates.

**Comment by yamsellem** [comment]
@50Wliu Oups, sorry for the duplicate & thanks for the pointer ;-).
