### ISSUE TITLE
Detecting file language when using a template extension

### ISSUE THREAD

**Issue by warrenseine** [atom/atom#10105]
Hi,

Atom is able to detect the my file is a Shell script when the extension is `.sh`. Sometimes, however, the extension is hidden by a template format, such as `.sh.j2` for Jinja templates.

I don't know what the correct approach should be or if it's already possible, but I'd like to be able to ignore specific extensions, such as `.j2` and use the previous suffix instead.

Thanks,
Warren.

**Comment by maxbrunsfeld** [comment]
Thanks for asking! The current solution is to add handling for that specific file extension in your `config.cson`:

```coffee
'*':
  'core':
    'customFileTypes':
      'source.shell': ['sh.j2']
```

Let me know if this does not solve your problem.
