### ISSUE TITLE
Atom freezes when opening

### ISSUE THREAD

**Issue by mjohnsonengr** [atom/atom#10114]
I managed to get Atom into a state where I cannot open it until I run in safe mode once.  I copied my .atom/storage directory.  I notice several files that begin with "editor-" and then have some sort of hash in the name; there's only one that appears to be particularly recent.  Are there any parts of it I could post that might help with diagnosis?

**Comment by amytruong** [comment]
Do you mind zipping up your `~/.atom/storage` directory and posting it here?

Also, some extra additional information would be fantastic. Can you tell us: 
* Which version of Atom are you using?
* What OS and version are you running?

Thank you!

**Comment by geksilla** [comment]
Same issue on Linux Mint 17. After update to 1.3.4 atom freezes. Also freezes in safe mode. When I removed content in `~/.atom/storage` atom opening without any issues.

**Comment by mjohnsonengr** [comment]
Do you need the content in the "buffers" property of the files inside?  It contains quite a bit of code.  I'd be happy to upload it if I strip out that code.

**Comment by mrrej89** [comment]
This seems to be happening if you try to open directories where you have split panes activated. Trying to split a pane freezes atom as well.

**Comment by MaPePeR** [comment]
I'm also experiencing the problem, that very often after closing Atom with a few files opened it will not reopen properly. Even if executed with `--safe`.   `--clear-window-state` solves the problem but it feels like i have to execute it every time i want to launch atom. (Which is a very frustrating experience. )
