### ISSUE TITLE
Atom won't open anymore after a crash

### ISSUE THREAD

**Issue by fsnx** [atom/atom#10116]
After some time Atom "Stop responding", After i close the program 1-2 processes of atom still continue running (can't stop them in task manager) also i can't open Atom anymore (even in the safe mode) without rebooting the system.

* Atom version 1.3.2
* Windows 7

As far i remember the issue was present even without community packages.

**Comment by lee-dohm** [comment]
Can you try running Atom in Safe Mode? Disabling community packages isn't all that Safe Mode does.

To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by PombaM** [comment]
i have the same problem, it crashed and now it won't start. 
PS: i also tried 1.4.0-beta2

**Comment by fsnx** [comment]
@lee-dohm Happened again after ~8 minutes editing (in the safe mode).

OT: Packages were loaded in the safe mode, is that normal?

**Comment by MrKoijk** [comment]
It happened to me either. After doing some work program crashed and can't load properly. I tried a lot of different versions of it and safe mode - nothing helped... :/

**Comment by lee-dohm** [comment]
@fsnx How do you know packages were loaded? If you were checking in the Settings View, all of your Community Packages will still show there and will not show as disabled. This is normal in Safe Mode. If you had the little green box in the status bar, then Safe Mode is operating normally:

<img width="140" alt="screen shot 2015-12-18 at 8 06 12 am" src="https://cloud.githubusercontent.com/assets/1038121/11901038/412e61da-a55e-11e5-9809-f99368194ae9.png">

Can you give any more information? Like what you were doing when it crashed? What sort of file you were editing?

**Comment by fsnx** [comment]
@lee-dohm Oh, i was checking the settings (also i saw this green box), I was writing a .lua and a .html file, it's completely random as i said.

**Comment by snowyu** [comment]
I have the same problem with the specified folder opened on windows 10.

```bash
git clone https://github.com/snowyu/load-config-file.js
atom load-config-file.js --safe
```

Then the editor has crashed.

**Comment by MrKoijk** [comment]
Okay guys, I found the easiest way to fix this issue - you have to remove atom folders in: \AppData\Roaming, \AppData\Local and Temp folder in \AppData\Local. After all these steps reinstall the Atom :) It worked for me.

**Comment by snowyu** [comment]
No useful, It's still crashed on the specified folder only. Here are the crash log:

[atom-crashes.zip](https://github.com/atom/atom/files/67426/atom-crashes.zip)

**Comment by fsnx** [comment]
Thanks @MrKoijk, Seems like the issue has been solved :+1:

**Comment by lee-dohm** [comment]
@fsnx I'm glad to hear things are working for you. I'm going to close the Issue. Let us know if you run into any more problems!

@snowyu Please open a new Issue for your crash problem.

**Comment by ldeck** [comment]
I found killing all atom related processes enabled atom to start up again. (MacOS Sierra).

**Comment by DrSharky** [comment]
Just for reference, I only had to delete the Atom folder in C:\Users\<username>\AppData\Roaming (Windows 7) and it began working again for me.

**Comment by preetgujral** [comment]
have you tried atom --clear-window-state from command line?

**Comment by francescoboc** [comment]
@preetgujral Thanks! It solved the issue for me too!

**Comment by pati610** [comment]
Thanks a lot! the --clear-window-state flag solved the problem!

**Comment by TSMMark** [comment]
I had to open ActivityMonitor on mac and kill these 3 processes:

![screen shot 2018-08-15 at 10 24 42 am](https://user-images.githubusercontent.com/4197823/44153164-707be218-a075-11e8-88b3-2a9ac3f02ab3.png)

**Comment by SirFunset** [comment]
i clicked update.exe and it started working again ¯\_(ツ)_/¯
