### ISSUE TITLE
Editor becomes unresponsive when opening files

### ISSUE THREAD

**Issue by andrewlively** [atom/atom#10115]
I haven't been able to reproduce it consistently, but several times today I (as well as one of my co-workers) have had Atom lock up and become unresponsive. It seems to only happen though when I open a file in my project (but not every file and if I close the application and open that same file again it works fine).

Here is what I get after OS X closes the app: http://pastebin.com/Uve2600f

Here is my info:

Atom: 1.3.2
OS: OS X 10.11

**Comment by andrewlively** [comment]
I have been playing around and am able to reproduce a few times now successfully:

1. Open two JS files
2. Open a third JS file using Fuzzy Finder using `cmd-T`
3. Application locks up

**Comment by andrewlively** [comment]
I just disabled all my plugins and still get the same issue

**Comment by lee-dohm** [comment]
Can you reproduce the issue on the v1.4.x beta? This sounds a lot like the "same file name, different path" crashing bug that exists in v1.3.x. (Can't find the Issue right now, sorry :frowning:)

**Comment by siannopollo** [comment]
Yeah, I think @lee-dohm is correct. I was having the same issue but then I just saw his comment and that was indeed the problem locking up the editor (opening two files with the same name but different paths).

I'll try out 1.4.x to see if that helps.

**Comment by siannopollo** [comment]
The 1.4.0-beta2 version doesn't exhibit the filename problem. Thanks @lee-dohm!

**Comment by lee-dohm** [comment]
You're welcome! I'm glad it is fixed for both of you :grinning:

**Comment by lee-dohm** [comment]
Oops ... just realized different people replied. Sorry about prematurely closing :confounded:

**Comment by andrewlively** [comment]
I tried on the beta and am not getting the issue anymore! Thanks @lee-dohm

**Comment by 50Wliu** [comment]
> I tried on the beta and am not getting the issue anymore!

:rocket:
