### ISSUE TITLE
Atom is broken, when opening it shows a screen like Chrome would when you use Inspect element

### ISSUE THREAD

**Issue by alex1236** [atom/atom#10130]
This is the screen when I open atom: http://vgy.me/liQWlM.png I get the same screen even after I reinstall it. I haven't changed anything since it last worked on my computer so I'm really confused as to why it's doing this. Any help would be great as Atom is my go to code editor right now.

EDIT: Clearing my c/users/alex/.atom directory fixed the issue, it may have been Activate Power Mode package's newest update.

**Comment by george-cz** [comment]
You can toggle developer tools in Atom by **View -> Developer -> Toggle developer tools**, hovewer I'm not sure why it stays open for you even after restart. Are you running atom with any sort of parameters?

**Comment by alex1236** [comment]
The only modification I made was the addition of the Activate Power Mode package.

**Comment by 50Wliu** [comment]
@alex1236 Please press the red x button with a 1 next to it next time this happens and paste the error here.  Since it seems like it's a problem with activate-power-mode, I'm going to close this out.

**Comment by mustaqeem** [comment]
I am also getting this screen. Don't know what to do?
Here is the error:

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at FileSystemBlobStore.load (/usr/share/atom/resources/app.asar/src/file-system-blob-store.js:37:34)
    at Function.load (/usr/share/atom/resources/app.asar/src/file-system-blob-store.js:10:14)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:18:39)
```

**Comment by aphasingnirvana** [comment]
Try this:
`sudo rm -rf ~/.atom/blob-store`

If the above command does not change anything use the following command:
`sudo rm -rf ~/.atom/compile-cache`

**Comment by rayaneDZ** [comment]
Open it as sudo

**Comment by JullietProjects** [comment]
I had the same problem, but it was my fault >.<... (#noob)
 
Atom created a folder called ".atom" on my computer, and I changed the folder attributes to "hidden"... I know, I know, silly mistake :'( As soon as I changed it back to the way it was before, it started working normally... 

I know you probably didn't do anything as silly as I did, but I'll post it just in case.

**Comment by steffsamtoy** [comment]
I had the same problem,  how can I fix it?  I had this screen
![atom_problem](https://user-images.githubusercontent.com/31155127/35510592-bf74ca40-0509-11e8-9b6b-108064cdbcce.jpg)

**Comment by Ben3eeE** [comment]
@steffsamtoy Rename the `C:\Users\Steff\.atom\compile-cache` folder to `compile-cache-bak` and try to start Atom again. If all works you can delete the backup.

**Comment by steffsamtoy** [comment]
@Ben3eeE thanks,
It works, my compile-cache folder attributes was hidden ^ ^'

**Comment by agusbrand** [comment]
@steffsamtoy Thanks it works!

**Comment by Yashu-369** [comment]
thanks @Ben3eeE . Guys this works!!!

**Comment by surajhs97** [comment]
Thanks @JullietProjects , I don't know how my .atom directory was hidden. As soon as I unhid it, it worked perfectly fine.
