### ISSUE TITLE
Close all Tabs only works if first tab is focused

### ISSUE THREAD

**Issue by bsbodden** [atom/atom#10133]
## Steps
- Open a few tabs, select any of the but the first one 
- Select "Close All Tabs" from File menu
- Nothing happens
## Environment

Atom Version: 1.3.2
OS: OS X Yosemite 10.10.5

**Comment by AndreaGriffiths11** [comment]
Thank you for contributing!
This issue has been resolved in Atom v1.13.0 on Mac OS X 10.12.2.
