### ISSUE TITLE
ENOENT: no such file or directory...

### ISSUE THREAD

**Issue by ghost** [atom/atom#10138]
When I drag and drop a _file_ on to a _folder_ to overwrite an old file, I get the following error:

```
ENOENT: no such file or directory, rename '' -> /path/to/folder/
```

What should occur:

When I drop the new file onto the folder, if the file exists I should be prompted to ask if I want to overwrite the old one.

Atom 1.3.2 on Mint 17.2

**Comment by kevinsawicki** [comment]
Does this happen for all files you are dropping and overwriting or only certain ones?

This is what I see when I try to reproduce it:

<img width="472" alt="screen shot 2016-01-04 at 1 25 53 pm" src="https://cloud.githubusercontent.com/assets/671378/12100895/b4109d04-b2e6-11e5-9cba-541152ebe9a1.png">

**Comment by jersten** [comment]
I created a folder named `test` with an empty file named `test.json` in that folder. I set the project folder as `test`. Created an empty file named `test.json` on the desktop (outside of project), then dragged the desktop file on top of the `test` folder. Below is the error:

![selection_001](https://cloud.githubusercontent.com/assets/7646510/12122528/a276ec92-b3a9-11e5-9963-b6bc09582fb6.png)

**Comment by kevinsawicki** [comment]
@jersten thanks so much for the specific steps, will take a look :+1:

**Comment by jersten** [comment]
As an update; this bug is in 1.5 as well.
