### ISSUE TITLE
Atom freezes when opening a file

### ISSUE THREAD

**Issue by ile** [atom/atom#10136]
I can open one file, named `index.coffee`in a certain folder. When I try to open another file, also named `index.coffee` in another folder, I will get this:

![image](https://cloud.githubusercontent.com/assets/433707/11920016/75b8668a-a76b-11e5-88f8-a6967207361b.png)

Atom will not recover from this, so "Close" is the only option.

I can also switch the order of the files that I open -- it's always the second open that crashes it although the opening ordering can be switched.

Dev tools screenshot with pause pressed:

![image](https://cloud.githubusercontent.com/assets/433707/11920032/392bbe96-a76c-11e5-88cb-e97c602f1517.png)

Using Atom 1.3.2 with Win 7 64bit.

**Comment by 50Wliu** [comment]
This has already been fixed in the 1.4.0 betas, if you want to try that.

**Comment by ile** [comment]
ThanThanks.
