### ISSUE TITLE
Atom freezes after opening a new pane and trying to open a file in it

### ISSUE THREAD

**Issue by DanielaValero** [atom/atom#10141]
Hello,

I have just noticed that atom is freezing during the next steps:

1. Open atom
2. Open a new file by clicking it in the tree view
3. Split the view in two panes
4. Focus the new pane
5. Open a new file in the freshly created pane by clicking it in the tree view

Other info:
My atom version is: 1.3.2
I can also reproduce it when running atom with the --safe flag.
I don't get any crash report

**Comment by surtic86** [comment]
I have the can Reproduce it with my Installation.

OSX: 10.11.2
Atom: 1.3.2
Packages: 
atom-autocomplete-php@0.18.3
atom-beautify@0.28.19
autoclose-html@0.19.0
color-picker@2.0.14
docblockr@0.7.3
editorconfig@1.2.2
file-icons@1.6.13
highlight-selected@0.11.1
language-ejs@0.2.0
language-spacebars@0.2.2
linter@1.11.3
linter-jshint@1.2.1
linter-php@1.1.6
markdown-pdf@1.3.9
markdown-scroll-sync@2.0.3
meteor-api@2.20.0
meteor-helper@0.27.0
monokai@0.18.0
nucleus-dark-ui@0.7.2
project-manager@2.6.5
regex-railroad-diagram@0.10.4
remote-sync@3.5.0
split-diff@0.5.0

**Comment by neokore** [comment]
+1 on GNU/Linux using v1.3.0.
It always happen when opening a different file with the same name in other panel.
Steps to reproduce:
1. Open a file named 'app.js', for example.
2. Open a new pane (Ctrl+K right).
3. Open a *different* file with the same name (another 'app.js' file).
4. Atom is frozen

Cheers!

**Comment by leoasis** [comment]
Happening the same on Mac OSX 10.10.3, Atom 1.3.2

**Comment by Krekotun** [comment]
The same
OSX 10.11.2
Atom 1.3.2

**Comment by DanielaValero** [comment]
@neokore  Exactly! that was the missing piece I missed with my steps to reproduce, it need to be a file with the same name.

I am using atom during some time, and I would like to provide more information useful for the bug-fix, but I dont get crash report, or any log file (that at least I can find). Does anybody know how to debug this better? I already tried the developer tools, /tmp/Atom Crashes and ~/.atom/whatever-inside.

**Comment by 50Wliu** [comment]
This issue has already been fixed in the 1.4 betas.  Sorry for the freezes :(.

**Comment by neokore** [comment]
Confirmed, I couldn't make this issue happen again with the last beta. Thank you @50Wliu !
