### ISSUE TITLE
Atom freeze when trying to open some files almost randomly

### ISSUE THREAD

**Issue by asci** [atom/atom#10140]
### I have very strange problem

one of atom's processes using CPU for 100%
Developer tools - freezing as well, I'm not able to make profiling
AFAIK It is not depend on file content (I tried to comment out or even delete files content)
No logs output when run `atom --safe -l log.txt`
not depend on .atom settings folder - i tried to install it from scratch without plugins - still freezing 

### how to get crash logs?

windows 7, no admin rights, atom v1.3.1 and atom v1.3.2
project is using SVN

I know it looks like bullshit, but it depends on opened files, here are filenames:
`any other file`
`resources\trader\js\modules\dgOrder\directives\dgQuickOrderPopup\index.js`
`resources\trader\js\modules\dgOrder\controllers\dgQuickOrderPopup\index.js`

It is not depend on sequence.

**Comment by 50Wliu** [comment]
Hi @asci, this is a problem with very similar filenames that has already been fixed in the 1.4.0 betas.

**Comment by asci** [comment]
Oh, thanks! updating helped
