### ISSUE TITLE
[ Keyboard usability enhancement ] Dismiss find pane by hitting <Enter>

### ISSUE THREAD

**Issue by i90rr** [atom/atom#10144]
Hi,

Whenever I look for any text after the search is done the only way to dismiss the search window is to hit Esc; a really good usability enhancement would be to automatically close the search pane and position the cursor at the first occurrence of the search, just like the search function works in Emacs or Vim.

Cheers.

**Comment by lee-dohm** [comment]
I believe this has been implemented as an option. See https://github.com/atom/find-and-replace/pull/427. Please let us know if this is not the case.

**Comment by i90rr** [comment]
Hello @lee-dohm this is exactly what I was looking for. What I fail to see however is how to toggle the functionality, could you point to the right place?

**Comment by lee-dohm** [comment]
It is called "Scroll To Result On Live-Search" in the find-and-replace package:

<img width="474" alt="screen shot 2016-01-03 at 3 01 01 pm" src="https://cloud.githubusercontent.com/assets/1038121/12081334/e11382c4-b22a-11e5-8ccc-426076d5f483.png">

1. Launch Atom
1. Open the Settings View using <kbd>Cmd+,</kbd> on OS X or <kbd>Ctrl+,</kbd> on other platforms
1. Click the Packages tab
1. Search for "find-and-replace"
1. Click the Settings button for the find-and-replace package
1. Scroll down to "Scroll To Result On Live-Search"
1. Ensure the setting is checked

**Comment by i90rr** [comment]
Nice, thank you!!!
