### ISSUE TITLE
Editor freeze in 1.3.2 browsing chef cookbooks

### ISSUE THREAD

**Issue by runningman84** [atom/atom#10158]
I have been using atom 1.2.x for a while without any problems. Since I have been using 1.3.x (currently 1.3.2) the editor stops responding or freezes if I open a attributes/default.rb file. The cpu load goes up to 100%. Strace shows only output like this:

```
gettid()                                = 22558
gettid()                                = 22558
gettid()                                = 22558
gettid()                                = 22558
gettid()                                = 22558
gettid()                                = 22558
gettid()                                = 22558
gettid()                                = 22558
gettid()                                = 22558
gettid()                                = 22558
gettid()                                = 22558
gettid()                                = 22558
^CProcess 22558 detached
```

The process list looks like this:

```
jon  22558 43.9  3.4 1303900 279816 ?      Rl   14:28   2:39 /usr/share/atom/atom --type=renderer --js-flags=--harmony --no-sandbox --lang=de --node-integration=true --enable-delegated-renderer --num-raster-threads=1 --gpu-rasterization-msaa-sample-count=8 --content-image-texture-target=3553 --video-image-texture-target=3553 --disable-accelerated-video-decode --channel=22519.1.1582449023 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
```

The problem occurs after a few minutes, I cannot reproduce it immediately after the start of atom.

I am using a few community packages like
- language-chef
- linter-...
- minimap
- atom-beautify

My system is Xubuntu 14.04

**Comment by runningman84** [comment]
It looks like a segfault:
```
Dec 22 13:28:11 vagrant-base-trusty-amd64 kernel: [19383.648789] atom[22612]: segfault at 0 ip           (null) sp 00007ffd731b58e8 error 14 in atom[400000+3612000]
Dec 22 13:35:20 vagrant-base-trusty-amd64 kernel: [19813.051538] atom[23246]: segfault at 0 ip           (null) sp 00007ffe4d9f38c8 error 14 in atom[400000+3612000]
Dec 22 13:35:21 vagrant-base-trusty-amd64 kernel: [19813.832907] atom[23318]: segfault at 0 ip           (null) sp 00007ffe770ae5b8 error 14 in atom[400000+3612000]
````

**Comment by tgagor** [comment]
I have same issue, with chef recipes or editing ansible scripts. Atom hungs even in safe mode.

In my case it's mostly when I'm switching between files by selecting them on treeview panel.

**Comment by benogle** [comment]
Can you try the [atom beta](https://atom.io/beta) in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by tgagor** [comment]
I have few days off, I will check when I'll back.

**Comment by tgagor** [comment]
I was playing for a while with beta version and it didn't hang. It looks fixed in new version.

For now I'm returning to version 1.2.4 from webupd8team/atom ppa.

**Comment by Ben3eeE** [comment]
Looks like this was solved by updating Atom. Closing.
