### ISSUE TITLE
Blank line between html attributes

### ISSUE THREAD

**Issue by cguilhermef** [atom/atom#10155]
Sometimes, I need to do this:

    <a
      data-toggle="modal"
      data-target="#myModal"
      class="some-class"
      title="Click to open modal"
    >modal</a>

instead just in a single line.
BUT

When I press "enter" to do the line break, Atom put a blank line before each line!

    <a
    
      data-toggle="modal" 

      data-target="#myModal"
  
      class="some-class"

      title="Click to open modal"
    >modal</a>

How to avoid it?

**Comment by 50Wliu** [comment]
Does this still happen in safe mode (`atom --safe`)?

**Comment by cguilhermef** [comment]
Well.. in safe mode, run pretty. : /  
I know what you will to say: some package has generate this issue... Please, can you help me?

**Comment by cguilhermef** [comment]
Ok. I turn off Emmet package and it´s solve the problem. But.. oh Lord! I want to use them!

**Comment by cguilhermef** [comment]
Ohh wait! I have the answer: in Emmet setting, unchecking "Format line breakes" appear to solve this!!

**Comment by 50Wliu** [comment]
Ok, glad you found your issue @cguilhermef!
