### ISSUE TITLE
Atom asks to save changes when quitting (OS X)

### ISSUE THREAD

**Issue by nuno-agostinho** [atom/atom#10150]
When quitting Atom, unsaved documents ask to save changes which is unexpected behaviour on OS X.

Other apps that are able to restore windows such as Pages, Numbers, Keynote and Sublime Text 3 don't ask to save changes, they simply open the unsaved documents the next time the app is launched.

**Comment by 50Wliu** [comment]
Good news, @nuno-agostinho!  The functionality you're asking for has just been implemented in the 1.4 betas, so feel free to try those out and report back :smile:.

**Comment by nuno-agostinho** [comment]
@50Wliu Thanks! Works like a charm in the 1.4 beta 3! :)
