### ISSUE TITLE
Show invisibles only when selecting text

### ISSUE THREAD

**Issue by nuno-agostinho** [atom/atom#10151]
I really hate to always see invisibles but they are useful sometimes… Some apps like Sublime Text only show invisibles when text is selected and it'd be great if there was such an option in Atom.

**Comment by valtlait** [comment]
This is nice suggestion.

I have this on my keymap, so I can toggle invisibles quickly with ⌘ M.

```cson
'atom-workspace':
  'cmd-i': 'window:toggle-invisibles'
  'cmd-m': 'minimap:toggle'
```

**Comment by benogle** [comment]
Closing in favor of https://github.com/atom/atom/issues/6669
