### ISSUE TITLE
Multiline selection gets very slow when selection with alt+shift+cursor is done fast

### ISSUE THREAD

**Issue by simonCor** [atom/atom#10153]
The multiline selection+editing functin slows sown the editor when one selects more than ~10 lines with [alt+shift+cursor down]. One have to hold down the cursor keys so the selection happens very fast, if one does it line by line it does not happen.

**Reproduction Steps:**
1. Start editor
2. Open a file with at least 100 lines
3. select first line
4. hold down [alt+shift+cursor down]

**Expected behavior:**

Multiple lines are sleected without noticeable performace issues.

**Observed behavior:**

Multiple lines are sleected but the editor start to not respond for a noticable time (> 5 s)

**Atom version:** 1.3.2
**OS and version:** openSUSE 13.2 (Harlequin) (x86_64) 64-bit

**Installed packages:**

atom-beautify  
find-selection  
linter-clang  
sublime-default-syntax
atomerinal  
fold-comments  
linter-cpplint  
svn
autocomplete-clang  
highlight-line  
project-manager  
switch-header-source
autocomplete-cmake  
highlight-selected  
terminal-plus
block-comment  
language-cmake  
show-in-system  
todo

**Comment by anoe** [comment]
Bump! I have the same issue; quite annoying.

**Comment by avacore1337** [comment]
bump, It's still unusable for more than low double digit amount of lines

**Comment by lczech** [comment]
Bump. Still an issue in atom 1.23.1, to the point where I had to kill atom...
