### ISSUE TITLE
Atom hangs (CPU@100%) if the Project dir is not a git repository and the home dir is a git repository

### ISSUE THREAD

**Issue by mindrones** [atom/atom#10159]
After upgrading node to 5.1.1 Atom is very slow, and hangs very frequently, making editing simple text very slow. Atom Helper takes 100% of the CPU.

- pressing a character on the keyboard shows it after a seconds or two, if it shows up at all;
- trying to open the `node_modules/` dir in the Tree View freezes Atom (*): I suspect this is because npm 3 node modules installation is now flat: adding `node_modules` to `.gitignore` seems to be beneficial at least reducing the CPU load, but it still hangs frequently;
- searching for some text in a dir freezes Atom (*).

(*) and shows a `Editor is not responding: Keep waiting/Close` popup.

**Specs**
- Atom: 1.4.3
- OS: OSX Yosemite 10.10.5 (14F1509)
- Hard drive: SSD
- RAM: 16 GB
- Processor: 4 processors / 2,4 GHz Intel Core i7

**Comment by mindrones** [comment]
Is there a way to profile Atom to detect which package is taking all the CPU?

**Comment by mnquintana** [comment]
@mindrones What version of Atom are you using? What do you mean by "upgrading to Node 5.1.1"? The version of Electron in Atom's most recent release (1.3.2) is built on Node 4.

**Comment by mindrones** [comment]
Hi @mnquintana, I have Atom 1.3.2 and I thought to report about the Node 5version because this slowdown happened after upgrading Node.

**Comment by mindrones** [comment]
@mnquintana I know I'm not being very specific but that's because I don't understand what's triggering the CPU peaks. I'd like to help tracking this one, do you know how to profile Atom to detect which package is taking all the CPU? 

This happens very often when searching text in a long file or on a lot of files.
The only way to solve this is to kill the peaking Atom Helper and reload Atom.

See also:
- [similar bug reports](https://discuss.atom.io/t/atomhelper-high-cpu-usage/2553)
- [similar bug reports](6437)

**Comment by mindrones** [comment]
@mnquintana Here's the steps to reproduce this.

**Setup**
- `git clone https://github.com/rachel-carvalho/chaplin-browserify-gulp`
- `cd chaplin-browserify-gulp`
- `npm install` (make sure you have node 5.1.1 so that npm 3 will install all dependencies non-nested)

**Atom**

- add `chaplin-browserify-gulp` as a project 
- open Dev Tools;
- in the `Profiles` tab choose `Collect Javascript CPU Profile`;
- press the `Start` button;
- search for 'jquery' in the project;
- I got 3788 occurrences of `jquery` in 110 files;
- in the `Project Find Results` tab click on one of the results;
- it opens the correspondent file scrolled at the correct line;
- then Atom freezes.

In one lucky case, after a minute Atom came back to life and I've been able to see the profile Chart and save it. The long bands you see here in the middle of the test are when Atom is freezed at all:

![screen shot 2015-12-28 at 11 40 10](https://cloud.githubusercontent.com/assets/1309648/12018131/a021441a-ad5f-11e5-896f-e5e925b6b604.png)

The very moment I click again on a result in the `Project Find Results` it freezes again.

In most of the other cases, repeating this procedure, Atom remains frozen for at least 30 mins from the first time I click on a result: in the profiler, I'm able to press the Stop button but it won't stop profiling until after ~30mins Atom comes back; then the profiler show this:

![screen shot 2015-12-28 at 12 57 49](https://cloud.githubusercontent.com/assets/1309648/12018446/d2579800-ad62-11e5-9d64-da1637b4d518.png)

(after the long bands you won't see anything as I've pressed the Stop button in the profiler after some minute)

**Comment by mindrones** [comment]
I have to verify this with more testing, but after Atom recovers from a freeze, if I click again on a result in the `Project Find Results`:
- if the result points to a line within a file that is already open, it seems to not trigger the freeze again;
- if the result points to a line within a file that is NOT already open, it opens a new file tab in Atom at the correct line, but as soon as I scroll this file Atom freezes again.

**Comment by mindrones** [comment]
Hi @mnquintana any news about this one? It's getting really exhausting to use Atom like this.
Any hint about how to spot the package that is causing this?

**Comment by lee-dohm** [comment]
I am unable to reproduce the error you're describing on Atom v1.5.0-dev-de04395 on Mac OS X 10.11.2. I tried it using npm from both Node v5.1.1 *and* Node v4.0.0. I doubt that this issue has anything to do with the version of Node installed and has completely to do with something else going on.

Have you been able to reproduce this issue when running Atom in Safe Mode?

To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by mindrones** [comment]
@lee-dohm thanks for your reply. 

Yes I tried running `atom --safe` right now and after clicking on one of the search results Atom stalled, with one Atom Helper at 100.5% of the CPU.

![screen shot 2016-01-08 at 15 58 44](https://cloud.githubusercontent.com/assets/1309648/12200739/d9410efa-b620-11e5-8762-13df0cd26a5d.png)

**Comment by lee-dohm** [comment]
Sorry if I'm missing the answers to these in your posts above but could you answer:

* What OS and version are you running?
* Are you using an HDD or SSD?
* How much RAM do you have installed?
* What processor is in your machine?

**Comment by mindrones** [comment]
Here they are:

- OS: OSX Yosemite 10.10.5 (14F1509)
- Hard drive: SSD
- RAM: 16 GB
- Processor: 4 processors, 2,4 GHz Intel Core i7

**Comment by mindrones** [comment]
I suspect this is not even related to find: today Atom freezes or at least uses 100% of the CPU for a long time right at startup :/

**Comment by mindrones** [comment]
As per comments in the "Atom profiles" issues, I tried to run `Atom --safe` but I still have an Atom Helper at 100% of the CPU so this is something happening in a core package. Same goes by running Atom normally with all custom packages disabled (should I reinstall them completely?).
Meanwhile I'll try disabling core packages one by one and see if I can track the offending one.

**Comment by mindrones** [comment]
Another thing I've noticed these days is that the offending Atom Helper won't close after I quit Atom: I have to manually "force quit" it using the Activity Monitor.

**Comment by mindrones** [comment]
OK I've disabled all core packages excluding `settings-view` and `tabs` and Atom still hangs just moving the cursor around in the only buffer I have opened (165 lines of javascript), this time with 2 Atom Helpers steaming at 100% :/

![atom_bugs_all_packs_disabled_still_hangs](https://cloud.githubusercontent.com/assets/1309648/12882219/57872bf4-ce50-11e5-9cbd-30ddda2eb2d9.png)

Even in this case, after quitting Atom I still have a Atom Helper running at 75%CPU (if I don't close it manually, it dies by itself after a minute or so).

So this have to be something in Atom / Electron.

**Comment by mindrones** [comment]
After disabling all packages as described in the previous comment, I ran `atom --safe` and profiled it while doing simple operations on a short buffer, 165 lines of javascript (moving the cursor, duplicating lines, deleting lines). After a bit it peaked to 100%, here's the profile screenshot:

![atom_sloppy_safe_simple_editing_small_js_file](https://cloud.githubusercontent.com/assets/1309648/12883029/a5732aca-ce55-11e5-88fe-035d4b460e28.png)

After I've stopped editing and I was using another app I noticed Atom was peaking again at 100%CPU all by itself, hence I profiled it again (it still was the `safe` atom):

![atom_safe_sloppy_idle_still_peaks](https://cloud.githubusercontent.com/assets/1309648/12883063/d2bd7c56-ce55-11e5-84cc-97619e873573.png)

(detail)

![atom_safe_sloppy_idle_still_peaks_detail](https://cloud.githubusercontent.com/assets/1309648/12883065/d9096e4e-ce55-11e5-906b-ef3a519f651a.png)

Of course I can provide the .cpuprofile files.

**Comment by lee-dohm** [comment]
Does this have anything to do with "find-in-project" anymore? If not, you should probably update the title.

**Comment by benogle** [comment]
Based on the first 2 flame graphs, it looks like the time is spent in oniguruma which is pretty much only used by the grammars. It makes sense that this could happen when opening a file. Maybe the issue is with the js grammar? In addition to Lee's question, what specific file in your project is causing this?

**Comment by 50Wliu** [comment]
@mindrones mentioned that the freezes still happened even after language-javascript was disabled (so it should just be using Plain Text), though those flame graphs didn't have any mentions of OnigScanner.

**Comment by mindrones** [comment]
@lee-dohm updated with a title that describes honestly the current situation :)

@benogle true, at first, by inspecting the graphs I though it was caused by OnigScanner too but, as @mnquintana said and as described above, this happens with all packages disabled, including core ones, so I suspect this is something in Atom or Electron.
As a reminder, I have saved these `.cpuprofile` for inspection if you need them.

Or can this be a corrupted configuration file? Should I reinstall Atom completely? Thanks!

**Comment by mindrones** [comment]
Today I've got the usual slowdown using a project before `git init` it, but the slowdown disappeared editing a git repository, isn't it weird? 
It may be a stupid question but could this be caused by using a Project Folder not being a git repository?
There could be some watch function not finding git references and going on forever?

**Comment by 50Wliu** [comment]
@mindrones Is your home folder a Git repository by any chance?

**Comment by mindrones** [comment]
@50Wliu yes I'm tracking my dotfiles there

**Comment by 50Wliu** [comment]
Ooh, looks like we have a lead then.  Can you try Atom 1.5.0?  The performance issue with having a Git repository in your home folder should be fixed in that version.

**Comment by mindrones** [comment]
Aaah, that might be it: with Atom 1.5.0, using a simple dir as a Project seems to behave just fine!
Before closing this one, I'd like to test this a bit to make sure that was the problem, but thanks a lot!

**Comment by lee-dohm** [comment]
Great catch @50Wliu :grinning:

Thanks for following up @mindrones. Looking forward to the results of your tests!

**Comment by mindrones** [comment]
I've tested this a bit and it seems to be gone!
@mnquintana @lee-dohm @benogle @50Wliu thanks a lot for your help :)
Closing this one.. what a relief!!!!!

**Comment by lee-dohm** [comment]
That's great news @mindrones. I'm glad we could help :grinning:
