### ISSUE TITLE
Atom segfaults on Xubuntu 14.04 

### ISSUE THREAD

**Issue by danielvoicu** [atom/atom#10162]
The app window flickers a few times, it freezes for a very short time and goes black then everything goes back to normal. Sometimes I get an error message saying that Atom has crashed. It gives me the option to relaunch the app or keep it closed, although the app is still running this whole time. This seems to happen to all apps that are built with Electron.

I wanted to see if I can find out more about the error so I ran `dmesg`. I don't know if this helps with anything, but this is what I get when I run `dmesg`:

```
[   92.324884] atom[2129]: segfault at 0 ip           (null) sp 00007ffea1d6b8b8 error 14 in atom[400000+3612000]
[   92.848875] atom[2241]: segfault at 0 ip           (null) sp 00007ffcbf5401a8 error 14 in atom[400000+3612000]
[   93.129687] atom[2255]: segfault at 0 ip           (null) sp 00007ffd050cbf98 error 14 in atom[400000+3612000]
```

I'm using **Atom 1.3.2 on Xubuntu 14.04 64bit**, running in a VirtualBox VM. I've installed Atom using the official .deb package, and this issue has been happening since I installed it.

**Comment by shizi** [comment]
I have exactly the same issue on Xubuntu 15.10 64bit running in a VirtualBox VM (VirtualBox version 5.0.14).
