### ISSUE TITLE
Soft tab setting not respected

### ISSUE THREAD

**Issue by heoga** [atom/atom#10169]
Using Atom 1.3.2 on Windows.
- Install Atom
- Ctrl + ,
- Enable Soft Tabs
- Set Tab Length = 4
- Set Tab Type = soft
- File > New File
- File > Save As
  - test.py
- Enter the following and press Enter.
  - def myfunc():

On the new line, the auto-indentation applies a hard tab, not a soft tab.

**Comment by lee-dohm** [comment]
I can't reproduce this using Atom v1.3.2 on Mac OS X 10.11.2. Can you turn on the Show Invisibles setting to ensure that it is actually a hard tab and not just spaces that Atom treats like a tab for cursor movement?

**Comment by heoga** [comment]
I did try with invisibles on and it didn't have the dots for spaces. I
won't have access to it for a few weeks, Xmas and all, but when I do I'll
save a file and open in a different editor to confirm.

**Comment by lee-dohm** [comment]
Sounds good @heoga. Looking forward to your feedback. Happy holidays!

**Comment by alexchandel** [comment]
This happens to me all the time, but on OS X Atom 1.4.3.

**Comment by lee-dohm** [comment]
@heoga, did you get a chance to try this out?

**Comment by neomonkey** [comment]
I opened the atom with the safemode. It is repoducing at the safemode and normal mode. Also I have an example how this works. Tested with C and javascript.

After:
#include line 8 spaces
function() line 7 spaces
function(){ line 6 spaces
while(){ line 2 spaces
pressing enter, no soft tabs...

**SETUP**
Atom 1.4.3
Ubuntu 15.10 (installed from .deb)
Under Virtualbox
Packages installed: language-c

**Settings:**
```
"*":
  core:
    autoHideMenuBar: true
  editor:
    invisibles: {}
    softTabs: true
    softWrapHangingIndent: 8
    tabLength: 8
    tabType: "soft"
  welcome:
    showOnStartup: false
".text.todo":
  editor:
    softWrapHangingIndent: 8
``

**Comment by heoga** [comment]
Yea, I came back from vacation and it was working again. Haven't had a
chance to do any further digging as my real testing job took priority. Is
this information cached anywhere?

**Comment by neomonkey** [comment]
Okay, more information about this. So when pressing enter, the new intedent makes 16 spaces (dots). When you press tab, it makes the correct 8 spaces, but when pressing back it deletes all 8 spaces. Now ok this seems like a feature if they are not presented as hard tabs. But the rest of the indentation mistakes stand and the settings doesn't work.

#include line 8 spaces
function() line 7 spaces
function(){ line 6 spaces
while(){ line 2 spaces
