### ISSUE TITLE
Toggle terminology in menu items is counter-intuitive

### ISSUE THREAD

**Issue by nuno-agostinho** [atom/atom#10160]
Lots of menu items are like **Toggle (action)**: Toggle comments, toggle bookmark, toggle find in buffer, toggle find in project, etc.

![screen shot 2015-12-22 at 13 53 33](https://cloud.githubusercontent.com/assets/3199157/11956626/6d306942-a8b3-11e5-9a4b-67947def60d5.png)

This is awful since it doesn't inform about the current state of the item.
- **Toggle Soft Wrap**. Wait, will it turn soft wrap on or off? Maybe it'd be better to add a checkmark when it's active (_à la_ Sublime Text, like this: ![screen shot 2015-12-22 at 14 19 18](https://cloud.githubusercontent.com/assets/3199157/11957094/2b62bb06-a8b7-11e5-89f5-072999fcc18e.png)). Either that or rename the item depending on its state: _Enable Soft Wrap_ or _Disable Soft Wrap_. The same goes to **Toggle bookmark** and **Toggle comment**.
- **Toggle Tree View**: why not _Show Tree View_ and _Hide Tree View_ instead? The same goes to **Toggle Preview** (from the Markdown Preview package), **Toggle** (Keybinding Resolver package), **Toggle Find in Buffer**, **Toggle Find in Project** and **Toggle Developer Tools**.
- **Toggle Full Screen**: on OS X, the standard way to state this is with _Enter Full Screen_ and _Exit Full Screen_.
- **Toggle Command Palette** and **Toggle Diff List** are fine since they show a palette that goes away as soon as you do some action.

**Comment by valtlait** [comment]
+1 for renaming them.
