### ISSUE TITLE
Can't rearrange tabs

### ISSUE THREAD

**Issue by sbrl** [atom/atom#10168]
Rearranging tabs on the top bar of my installation of atom sometimes works, and sometimes doesn't. Here's a link to my settings:

https://gist.github.com/sbrl/85cf891cc52543567204

Here's an animated gif of what I mean:

![gif](http://i.imgur.com/Fow1yyo.gif)

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tabs? Thanks!

**Comment by sbrl** [comment]
Sure!
