### ISSUE TITLE
Indent guide break at empty lines

### ISSUE THREAD

**Issue by Bilexes** [atom/atom#10173]
Atom 1.4.0 beta 3
Font Family standart (Windows 10)
UI Theme - Atom Dark
Syntax Theme - Atom Dark
styles.less - empty

Font size 11, 14 - all ok
Font size 12, 13 - Indent guide break (see picture)
Line with break guide empty. If in this line put tabs or spaces - guide is ok

![img2](https://cloud.githubusercontent.com/assets/7031555/11994398/9aeaa0b8-aa4e-11e5-9bc1-21275f07ad01.png)

**Comment by 50Wliu** [comment]
This is a duplicate of #9369 - please subscribe there for updates.
