### ISSUE TITLE
Atom consumes a full core after start

### ISSUE THREAD

**Issue by flaschbier** [atom/atom#10175]
System is Ubuntu 14.04 on a Lenovo X230, i7 4 cores, 8 Gig, SSD. `atom` is updated to 1.3.2 from the `.deb` file downloaded from `atom.io` just now. 

Regardless whether I open with `atom` or with `atom --safe` mode, a second or so after the window opens, the fan of my computer goes up and the disk light turns on. The system monitoring shows that `atom` is using up 100% CPU, and also 1.4 Gig of memory. Luckily, `atom` 1.3.2 eats only one of my cores. The 1.0.2 release was eating all cores and all I could do was turning the computer off. But still the weird disk activity eats up the battery much too fast so that I is still unacceptable for any practical use. 

There are not many or huge files open, just one 150 lines python file from the last testing session. But my home dir holds 140k+ files, totalling in 130 Gig of storage. I sincerely hope that `atom` does not try to suck the complete directory tree into memory.

Any hints or fixes?

**Comment by 50Wliu** [comment]
@flaschbier is that python file by any chance directly under your home directory (eg `~/file.py`)?

**Comment by flaschbier** [comment]
Nope, it is in a subdirectory two levels deep from my home dir. The excessive (both CPU and memory) resource consumption is the same when I start `atom` right from that directory.

**Comment by flaschbier** [comment]
@50Wliu Seems that it really has something to do with my large home dir. After your comment I changed to the respective subdir and opened a file directly with `atom somescript.sh` (instead of `atom` alone before). Now the folder area on the left is limited to the subdir and CPU as well as memory consumption are moderate.

**Comment by 50Wliu** [comment]
Just specifying `atom` will start Atom up with a saved workspace state that contains the same files, folders, etc. that you had open last time, whereas `atom .` will start Atom with only the current folder selected.

So in this case, it looks like you're hitting #6437 - I would suggest that you subscribe there for updates.
