### ISSUE TITLE
Atom freezes when opening several tabs

### ISSUE THREAD

**Issue by smalllark** [atom/atom#10174]
Atom: 1.3.2
Os: Archlinux | MacOS 

Repro: 
0. Remove folder `~/.atom`
1. Run atom from command line: `atom ~/tmp/atom-bug`
2. Open files in subfolders
![1450963277519](https://cloud.githubusercontent.com/assets/498585/11995020/93684b86-aa5a-11e5-9939-9efb5d48be77.jpg)
3. Atom hangs ...

**Comment by 50Wliu** [comment]
Hi @smalllark, this has already been fixed in the 1.4 betas.
