### ISSUE TITLE
UTF-16 may not be properly detected

### ISSUE THREAD

**Issue by felixvd** [atom/atom#10177]
Steps to reproduce this: save an Excel file containing Japanese characters as "Unicode Text", open it in Atom, see garbled characters.

![atombug](https://cloud.githubusercontent.com/assets/4535737/11997431/79b0fe2c-aabe-11e5-8c7d-70aea02a2899.PNG)

Selecting UTF-16 LE as the encoding works, but Notepad and Notepad++ read the files just fine from the start. Notepad++ says the file is encoded as USC-2 LE BOM. Saving the file as UTF-8 and then opening it in Atom works fine, too.

I am using Windows 7 and Excel 2016. I don't know if this is a bug, but it was confusing so I'll report it.

**Comment by 50Wliu** [comment]
Hi @felixvd, currently Atom does not automatically auto-detect files when you open them; you have to manually select "auto-detect" for each file.  See atom/atom#4160 and atom/encoding-selector#8 for more information.
