### ISSUE TITLE
"Find And Replace: Select All" hangs 1.3.2 and results in unexpected selections/cursors

### ISSUE THREAD

**Issue by WalterGR** [atom/atom#10179]
Atom 1.3.2 on OS X 10.10.5.

I have a Clojure (.clj) file whose sections are marked with the text `Section:`  I want to select all section headings, copy them, and paste them at the top of the file.

I didn't get very far, though.  Selecting `^;; .*Section:.*` seemed to hang Atom and I had to forcefully terminate it.  This reproduced reliably.

While working towards a minimal test case, I searched for `section:` instead, and found that it's more likely that it's just taking a very long time, because the resulting selections are quite numerous.  They're also rather... unexpected.

![2015-12-24 at 20 11 05 - atom selecting unexpected text](https://cloud.githubusercontent.com/assets/380880/11999785/246c4432-aa7b-11e5-8ed7-cbc6532d4e58.png)

Notice that there are a ton of resulting selections - or perhaps cursors.  I'm not entirely sure what I'm looking at, but it doesn't seem to be all instances of `section:` having been selected.

Let me know if you'd like the original file.

**Comment by jeancroy** [comment]
There's 18 result found for section, so search is probably working well.
However there was [work](https://github.com/atom/atom/pull/9426) to change the data structure holding marker for search result. You possibly found a bug in that.

**Comment by mnquintana** [comment]
This issue was moved to atom/find-and-replace#627

**Comment by WalterGR** [comment]
@jeancroy Searching isn't the problem.  It's doing "Find And Replace: Select All" afterwards.
