### ISSUE TITLE
Reopen last item never works

### ISSUE THREAD

**Issue by deadrow** [atom/atom#10180]
**Reproduction Steps:**
1. [First Step] Open atom and add some project 
2. [Second Step] Open some files ,modify them and then save.
3. [Third Step] Quit atom.
4. [Forth Step] Now reopen again.

**Expected behavior:**
Should open last added project files.
[Describe expected behavior here]

**Observed behavior:**
Opens empty tab
[Describe observed behavior here]

*_Screenshots *_
![screen shot 2015-12-25 at 9 10 36 pm](https://cloud.githubusercontent.com/assets/7129053/12003608/10d3f8d0-ab4c-11e5-977c-c5404d0c8a32.png)
![screen shot 2015-12-25 at 9 10 24 pm](https://cloud.githubusercontent.com/assets/7129053/12003609/14a0def6-ab4c-11e5-949a-7d587ba6b763.png)

**Atom version:** 1.3.2
**OS and version:** OSX 10.11.2 

**Installed packages:**

[List of installed packages here]
Only one extra package besides default packages 
1) atom-ternjs

**Additional information:**
- Problem can be reproduced in safe mode: [Yes/No] Yes
- Problem started happening recently, didn't happen in an older version of Atom: [Yes/No] Yes
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] No
- Problem happens with all files and projects, not only some files or projects: [Yes/No] Yes

**Comment by dideler** [comment]
The workflow I use is to `cd` to the project's root directory, then open the current directory with `atom .`
This reopens any tabs I had open when I last used Atom for that project.

If I open Atom without passing any arguments, it opens with a blank slate.
Perhaps what you're experiencing is expected behaviour?

**Comment by deadrow** [comment]
Yes but why this is not integrated in atom itself?

**Comment by dideler** [comment]
Sometimes you may want to open Atom without any history or context of the current directory?

**Comment by lee-dohm** [comment]
If @dideler is correct about how you're launching Atom, this appears to be expected behavior. And you can also always launch the last project you had open by launching Atom from the Dock on OS X.

**Comment by deadrow** [comment]
@lee-dohm "And you can also always launch the last project you had open by launching Atom from the Dock on OS X" 

No its not working . And its very annoying.Its reproducible everytime.I guess other developer must be facing this issue. If you want  i can provide logs.Just tell me steps to capture logs.

**Comment by r-a-v-a-s** [comment]
If you simply open the program from the Dock, 
then 'Reopen Last Item' won't do anything.
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

Drag the project folder from Finder onto Atom's Dock icon.
Notice if you open a file from the sidebar and then close it, 'Reopen Last Item' will work.
