### ISSUE TITLE
Atom.io error: Unexpecten token at Object.parse

### ISSUE THREAD

**Issue by Bredo** [atom/atom#10189]
Hey,
I'm experiencing a tough problem with Atom right now. It won't let me open the editor.
I get the error;

    SyntaxError: Unexpected token 
        at Object.parse (native)
        at FileSystemBlobStore.load (C:\Users\Jonathan\AppData\Local\atom\app-1.3.1\resources\app.asar\src\file-system-blob-store.js:31:31)
        at Function.load (C:\Users\Jonathan\AppData\Local\atom\app-1.3.1\resources\app.asar\src\file-system-blob-store.js:10:14)
        at window.onload (file:///C:/Users/Jonathan/AppData/Local/atom/app-1.3.1/resources/app.asar/static/index.js:18:39)

I have none packages, themes or anything installed, and I have tried reinstalling Atom and restarting my computer (also, reinstalling after restart).

Stuck upon this screen;
![](https://i.gyazo.com/2c718c3b56ff4fa5ba6a1ae2292d7434.png)

System info;
![](https://i.gyazo.com/f04324c491878b494972a27308960fed.png)

**Comment by mnquintana** [comment]
Can you try updating to the latest version of Atom (1.3.2) and see if you can reproduce this in safe mode? (`atom --safe`)

**Comment by Bredo** [comment]
Leaves me the same;
![](https://i.gyazo.com/b280f37f4fef91e507585b4f349190f4.png)

**Comment by mnquintana** [comment]
Take a look at https://github.com/atom/atom/issues/10065#issuecomment-164631959:

> try deleting the C:\Users\MYNAME\.atom\blob-store folder.

**Comment by Bredo** [comment]
I worked - thanks @mnquintana !

**Comment by ivosantiago** [comment]
I had this problem also. 

If you are using Mac delete `/Users/YOUR_USER/.atom/blob-store`

**Comment by victorperin** [comment]
I just had the same issue today. (using atom 1.4.0)

**Comment by bhushangahire** [comment]
Didnt worked for me. Any Other changes I should do ? I am on 1.6.0

**Comment by 50Wliu** [comment]
@bhushangahire Can you try deleting `~/.atom/compile-cache` as well?

**Comment by bhushangahire** [comment]
No luck.

**Comment by 50Wliu** [comment]
And if you rename the entire `.atom` folder to something else?
