### ISSUE TITLE
Restore maximized window

### ISSUE THREAD

**Issue by GoodGuyNick** [atom/atom#10181]
Linux Mint 17.3 MATE x64
Atom 1.3.2
Why after opening and closing of the atom maximized window can not be restored?
Steps:
1. Open Atom
2. Click on Maximize Window
3. Close Atom
4. Open Atom and it will not restore the maximized state
Although if i resize window position from corner to corner it will remember.

**Comment by 50Wliu** [comment]
@FlashFMA Can you still reproduce this on Atom 1.7.3?

**Comment by FlashFMA** [comment]
I'm now using Ubuntu MATE 15.10 with mate 1.10.2 and yes i can reproduce this. Maybe it's mate fault?

**Comment by robeerob** [comment]
I am on Atom 1.12.7, using Ubuntu 16.10 with Unity, and I have had this issue for about 6 months (plus/minus). Two different laptops (both with same environment). Did comment in another issue earlier, but couldn't find that one now.

Sometimes the window is maximized, but moved to another workspace. Most times it either is impossible to locate, and sometimes it is just minimized to a small vertical line in one of the corners, that can then be dragged to resize. I am using the "Maximize Window" keyboard shortcut.
