### ISSUE TITLE
Installation - Make context menu registration optional and non-default

### ISSUE THREAD

**Issue by garfieldbanks** [atom/atom#10186]
If I have to use regedit to remove atom from my context menu, it should not be something installed by default.

**Comment by mnquintana** [comment]
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/5901 – feel free to subscribe there for updates.

In the future, please take a look at the [Reporting Bugs section of the Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) before reporting an issue.
