### ISSUE TITLE
Text rendered inconsistently

### ISSUE THREAD

**Issue by chrisvio** [atom/atom#10185]
A picture is worth a thousand words so I've attached two. In the screenshot below notice the difference in black text between the two lines. The second line almost looks grey.
![greynotblack](https://cloud.githubusercontent.com/assets/16415311/12006574/e337c754-aba9-11e5-893b-a7ee166e6f55.png)
Below is another example. Look at the difference between the first 4 lines and the last line.
![wtf](https://cloud.githubusercontent.com/assets/16415311/12006575/e3393440-aba9-11e5-9842-b966250e5e59.png)

I'm using Atom 1.3.2 on windows 8.1 with the default font. My screen res is 1366x768. Disabling direct write resolves this issue.

**Comment by musmo** [comment]
+1 This is incredibly irritating. How do you disable direct write?

**Comment by chrisvio** [comment]
For starters I no longer use Atom. Since Sublime Text seems to be in active development once again I bit the bullet and just paid the $70. To disable direct write you have to modify the Atom shortcut or launch it from the command line with --disable-direct-write passed as an argument.

**Comment by damieng** [comment]
Are you still seeing this issue on recent Atom builds? We have upgraded Electron which brings in newer versions of Chromium which control how Windows renders the text via DirectWrite.

**Comment by chrisvio** [comment]
Yes. I'm still seeing this issue. I just tried Atom v1.12.6 and it's still occurring.

**Comment by damieng** [comment]
There are big changes to the font rendering in the next version of Electron (1.4) which we are in the process of integrating.  I'll ping this thread when a beta is available if you're still interested.

**Comment by chrisvio** [comment]
I am still interested. I'll check out the beta when it becomes available.
