### ISSUE TITLE
Deleting multiple files using tree view

### ISSUE THREAD

**Issue by ivoadf** [atom/atom#10184]
Nothing better than to show what is happening, can only close the window that pops up with alt+f4

![output](https://cloud.githubusercontent.com/assets/9215666/12004853/daac9b30-ab74-11e5-8a42-abe4c5f38f11.gif)

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tree-view?

Also, please take a look at [the Reporting Bugs section of the Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) before you do. Thanks!
