### ISSUE TITLE
seti-monokai theme should be removed from Atom Packages

### ISSUE THREAD

**Issue by miguelarauj1o** [atom/atom#10182]
It can not install the seti-monokai theme because the author removed the repository. It's no longer available on github (see author's page @joaoafrmartins), but he is still available for download.

**Reproduction Steps:**

1. Go to preferences
2. Go to install section
3. Search for "monokai"
4. Try install seti-monokai theme
5. Go to themes section
6. Click in *show output* and see explanation

**Expected behavior:**

the theme be installed

**Observed behavior:**

Theme not installed, but still available for download. Error below:

```
Installing “seti-monokai@0.3.1” failed.Hide output…
Unable to download https://www.atom.io/api/packages/seti-monokai/versions/0.3.1/tarball: 
400 Bad Request Repository inaccessible
```

**Screenshots and GIFs**

![screenshot 2015-12-25 19 45 12](https://cloud.githubusercontent.com/assets/7546651/12004552/125df8d8-ab40-11e5-85c2-de1beae6dff1.png)

**Atom version:** 1.3.2
**OS and version:** 10.10.5 (Yosemite)

**Comment by dakotalightning** [comment]
Same problem here, I don't understand why the repository was removed.

**Comment by thedaniel** [comment]
This package has been unpublished.
