### ISSUE TITLE
when adding more files in the project folder, ATOM response more slowly

### ISSUE THREAD

**Issue by Tasarinan** [atom/atom#10190]
If I added more than 2 folders in one project, in the same time, if you open one file in these folders, Atom response very slowly(Windows OS)

**Comment by jeancroy** [comment]
Can you give more details ? How many files are in those folders ? Multiple sub folders ? Very large files ? Any of those folders a git repository ?

**Comment by Tasarinan** [comment]
yeah, I think we can close this issue firstly because I am not sure it is caused by ATOM application or my harddisk speed. but it's clear if we have more npm packages in the node_modules folder of this project folder, the response will be slow.
