### ISSUE TITLE
Choosing "Application: Install Update" from command palette crashes Atom

### ISSUE THREAD

**Issue by nvdv** [atom/atom#10193]
HI,
when I choose "Application: Install update" from Atom command palette Atom crashes.
I am using Atom 1.3.2.

**Comment by 50Wliu** [comment]
Hi @nvdv, can you paste the crash log from Console.app here?  Thanks!

**Comment by nvdv** [comment]
For some reason in this case Atom does not generate error logs in Console.app.

**Comment by nvdv** [comment]
Is there another way to collect necessary debug info?

**Comment by 50Wliu** [comment]
@nvdv are you sure it's crashing, and not just freezing?  In addition, can you please try reproducing this in safe mode (`atom --safe`)?

**Comment by nvdv** [comment]
It just quits when I choose "Application: Install update". 
I've tried  ``atom --safe``` and behavior is the same.

**Comment by nvdv** [comment]
I checked ```system.log``` in Console.app and found this record after crash:
```
May 24 21:01:46 nvmac launchservicesd[76]: SecTaskLoadEntitlements failed error=22
```

**Comment by giacgbj** [comment]
I just lost all my unsaved tabs due to this error!

**Comment by pantuts** [comment]
Same here.

Atom 1.13.0
macOS 10.11.6

I had an issue opened before when I still use on Linux but it was resolved on the way. Just switched to mac then this one came up again.

**Comment by msabramo** [comment]
Did this a few times. I had one crash with the following in `Console.app`:

```
1/25/17 2:44:22.450 PM Atom[20736]: Download completed to: file:///Users/abramowi/Library/Caches/com.github.atom.ShipIt/update.xf4OPVp/atom-mac.zip
1/25/17 2:46:27.745 PM ShipIt[20943]: Moved bundle from file:///Applications/Atom.app to file:///var/folders/vq/yxhgc35139sc9rw90497n5vr0000gn/T/com.github.atom.ShipIt.2BArlWNM/Atom.app
1/25/17 2:46:27.745 PM ShipIt[20943]: Moved bundle from file:///var/folders/vq/yxhgc35139sc9rw90497n5vr0000gn/T/com.github.atom.ShipIt.v4WcZZDK/Atom.app to file:///Applications/Atom.app
1/25/17 2:46:28.740 PM ShipIt[20943]: Couldn't remove owned bundle at location file:///var/folders/vq/yxhgc35139sc9rw90497n5vr0000gn/T/com.github.atom.ShipIt.v4WcZZDK/Atom.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Atom.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/vq/yxhgc35139sc9rw90497n5vr0000gn/T/com.github.atom.ShipIt.v4WcZZDK/Atom.app";
    NSUserStringVariant =     (
        Remove
    );
} }
1/25/17 2:46:29.448 PM ShipIt[20943]: Application launched at file:///Applications/Atom.app
```

Several other times, it closed all my Atom windows, but the Atom app was still running with no windows. And then if I clicked Atom in the Docker, it brought up a single window and single tab with `untitled` in it. But if I quit and relaunch Atom, I get back the tabs I had before.

**Comment by tabacco** [comment]
I'm experiencing this same behavior as @msabramo in 1.15.0, where the editor appears to crash then, when refocused, opens an empty editor.

I've also noticed crashpad_handler processes piling up when I reproduce this, but all the directories in ```/tmp/Atom Crashes``` are empty
