### ISSUE TITLE
atom doesn't save last session on Windows 10

### ISSUE THREAD

**Issue by cuteUser** [atom/atom#10191]
I installed save-session package
I checked autosave enabled
I checked save-session enabled 
But my atom doesn't save last session. Also, empty editor start setting doesn't work.
Atom always starts with clean status.

Anybody have this problem or fix it?

my atom version is 1.3.2

**Comment by 50Wliu** [comment]
Please remove the `save-session` package and try again.

`save-session`'s functionality has been superseded by code in Atom core and has been totally deprecated as of the Atom 1.4 betas.  Many people have also been reporting that it's been broken since Atom 1.2.0.
