### ISSUE TITLE
Existence of config folder, breaks package installation

### ISSUE THREAD

**Issue by asampal** [atom/atom#10194]
I was trying to install the [Ionide](http://ionide.io/) suite of packages and ran into a problem as documented in [this bug](https://github.com/ionide/ionide-paket/issues/20) I filed against ionide. At the end of that issue a reference to another [bug](https://github.com/ionide/ionide-fsharp/issues/178) pointed to the problem happening when Atom has the config folder, created when opening settings, showing in the left pane.

**Comment by lee-dohm** [comment]
Can you describe what the actual problem is with repro steps? I did my best to take a quick look through the two bugs you linked, but I'm not understanding what is going wrong.

**Comment by asampal** [comment]
If you go to edit settings, this creates a `config` project folder. As detailed in the second bug I linked, if this folder exists when you install some packages, you will get errors on certain file access, where some file or other can't be found. In my case, detailed in the first bug I linked, I was trying to install ionide, which has the first step of installing `ionide-installer` and then the associated packages. You will find in that bug that many people end up with errors. The solution is to install the package with the `config` folder removed. I did it by removing the folder, going to the command line to install with `apm install ionide-installer`, starting up Atom and letting it finish the installation without error.

With the folder present I could never install ionide without an error.

**Comment by lee-dohm** [comment]
> If you go to edit settings, this creates a config project folder.

Where does it create this project folder? I don't get this behavior, so I can't replicate the error.

**Comment by asampal** [comment]
It's created in the left panel by opening up the settings where manually created project folders would be created. Well, it was in previous versions of Atom - can't confirm that this still happens because Atom has been updated since then.

**Comment by asampal** [comment]
Oh, if you already have a project folder in the left panel, the `config` folder will not be created. The panel has to be empty.

**Comment by 50Wliu** [comment]
If I'm understanding this correctly, I think I can replicate this - I posted some repro steps in the Electron PR but forgot to create a dedicated issue for it.

>Opening Settings or any other file that uses a URI will cause a fake folder to appear in the Tree View (eg config, init-script) and Settings - atom://config or similar to show up in the titlebar. Reproduce by using a new window.

**Comment by asampal** [comment]
Yeah, that's the cause of the problem.

**Comment by Ben3eeE** [comment]
This has been fixed in https://github.com/atom/atom/pull/12694 and will be available in Atom 1.12.
