### ISSUE TITLE
[ Keyboard usability enhancement ] Tree View navigation

### ISSUE THREAD

**Issue by i90rr** [atom/atom#10201]
Hi,

When browsing the Tree View using PgUp/PgDwn the selection cursor won't follow the screen jumps - so when you find the file you were looking for and press the Up/Down arrow keys you need to move all the way back to that point.

Best

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tree-view? Thanks!

**Comment by i90rr** [comment]
Hi @mnquintana, apologies for the delay on answering you, something weird is happening here as I'm not receiving any alert from GitHub.

Please let me know if you still want me to go ahead with your request.
