### ISSUE TITLE
having issues downloading atom on windows 10

### ISSUE THREAD

**Issue by oceansgreen** [atom/atom#10206]
when i attempt to download atom text editor i get to the download screen with the rocket,then a pop-up that says, installation failed, error while installing application, check setup log for more information and contact the author. open setup log via button on popup gives me the squirrel setup file in notepad, which i am sure the staff or users are familiar with, as i cant upload in this post without exceeding limit
is there something i can fix on my end or do i have to wait for a fix on your end?

**Comment by 50Wliu** [comment]
Hey @oceansgreen, please upload the squirrel setup file as a [Gist](https://gist.github.com) and paste the link here.  Thanks!

**Comment by oceansgreen** [comment]
https://gist.github.com/oceansgreen/bd8c158f1f9b797deae1
there you are hopefully thatll work

**Comment by 50Wliu** [comment]
/cc @paulcbetts 

Error is:
```
2015-12-28 01:38:11> IEnableLogger: Failed to install package to app dir: System.IO.IOException: The process cannot access the file 'C:\Users\Devon\AppData\Local\atom\app-1.3.2\lib\net45\atom.exe' because it is being used by another process.
```

**Comment by oceansgreen** [comment]
So is that something that I have to change on my end to allow download?

**Comment by paulcbetts** [comment]
You're trying to install Atom when it's already running?

**Comment by oceansgreen** [comment]
No in trying to install on a new computer, doesn't have ayom on it yet

**Comment by paulcbetts** [comment]
@oceansgreen The log says otherwise :)

**Comment by oceansgreen** [comment]
Well I am far from an expert with computer navigation ( apologies for the newness) but I can't find any files on my computer to open atom with, all I can find is atom setup and when I launch that I get the failed installation notification, is there something in the setup log that  missing that would help me to locate the program?

**Comment by oceansgreen** [comment]
So here is what I have done tonight, I attempted to run atom setup as admin just in case it wasn't recognizing my admin privileges, same result
I do have 5 atom setups downloaded
I tried to troubleshoot compatibility witg the recommended settings, same result
I tried the custom route which gives four options: 1) ran in earlier version of Windows but won't run now
2) program opens but doesn't display correctly
3) program requires additional permissions
4) I didn't see my problem listed
I tried numbers 1 and 4 and with both it Led to a screen that allowed selection of Windows 7, 8 vista and xp as well as an idk option I've tried selecting Windows 7 ( my old computer had Windows 7 and I successfully ran it on that) and I've tried selecting idk which set the troubleshooter to xp
On both of these it would pop up user account control where it asks if I'll let program make changes to computer with a yes or no, evrytime I click yes I get a new pop-up until I close the troubleshooter with no apparent progress made
I tried number 2 just for kicks and testing brought me to installation screen which... WORKED!!! Lol sorry to open a thread without trying basic shit on my own computer, perhaps this thread will help someone else out in the future, if not please know that I appreciate everyone's time attempting to help me with a problem that's mine to fix
