### ISSUE TITLE
Noisy com.github.ShipIt logs in console

### ISSUE THREAD

**Issue by tarngerine** [atom/atom#10207]
![image](https://cloud.githubusercontent.com/assets/1629901/12026515/61883bfe-ad88-11e5-8af2-725042cad722.png)

As you can see, this logs like every two seconds, cluttering up my log — makes it hard for me to debug stuff when trying to find things in the log (filtering works, but eventually gets pushed out due to system log max length per log set).

**Comment by lee-dohm** [comment]
This is fixed in the Beta channel, I believe. Please install the Beta and let us know if that doesn't fix it.

**Comment by lee-dohm** [comment]
Since this was fixed in the Beta that is now released, I'm going to go ahead and close this. Let us know if there are any more issues :grinning:
