### ISSUE TITLE
Enhance Atom's Mac Services support to include text services (editor not NSText)

### ISSUE THREAD

**Issue by magp** [atom/atom#10213]
Atom's Service support includes non text services. However, as the Atom text editor is a custom component not identified as text, the text services aren't show.

Thank you for your help. Don't hesitate to ask for further details if necessary.

Issue raised from conversation at https://github.com/atom/atom/issues/3204#issuecomment-167715168

**Comment by danielbayley** [comment]
+1.

**Comment by linickx** [comment]
:+1:

**Comment by jayvarner** [comment]
+1

**Comment by mkhl** [comment]
:pray:

**Comment by mkhl** [comment]
To interoperate with [OS X System Services][apple-services], objects in the responder chain need to implement three methods:

*   The system calls `-validRequestorForSendType:returnType:` to check whether services of a certain type (services that receive `sendType` and return `returnType`) are applicable in the current state of the application.

*   When a service (that receives data) is activated, the system calls `-writeSelectionToPasteboard:types:` to let the application write input data to the service.

*   When a service (that returns data) is finished, the system calls `-readSelectionFromPasteboard:` to let the application read result data from the service.

## Chromium

The chromium infrastructure code implements all of these methods in the classes `RenderWidgetHostViewCocoa` and `BridgedContentView`:

*   For `validRequestorForSendType:returnType:`, both return `self` if:
    *   Both types are be either text or null. This filters services that produce or consume non-textual data.
    *   If the services consumes text, the view must have a selection:
        *   `RenderWidgetHostViewCocoa` checks `!renderWidgetHostView_->selected_text().empty()`
        *   `BridgedContentView` checks `[self selectedRange].length > 0`
    *   If the services produces text, the view must be textual:
        *   `RenderWidgetHostViewCocoa` checks `renderWidgetHostView_->text_input_type_ != ui::TEXT_INPUT_TYPE_NONE`
        *   `BridgedContentView` checks `textInputClient_`
*   For `-writeSelectionToPasteboard:types:`, both write the current selection:
    *   `RenderWidgetHostViewCocoa` uses `renderWidgetHostView_->selected_text()`
    *   `BridgedContentView` uses `textInputClient_->GetTextFromRange(selectionRange, &text)`
*   For `-readSelectionFromPasteboard:`, both insert the read text using `-insertText:`.

## Atom

Cursory inspection (using F-Script) reveals that the root view of Atom is a `RenderWidgetHostViewCocoa` which contains everything except the titlebar, so let's focus on that.

In order for Atom text editors to interoperate with system services, we need to inform that view of our editor's selection. The appropriate method to call for this seems to be `RenderWidgetHostViewMac::SelectionChanged`, which updates the selection stored in the contained `renderWidgetHostView_` property.

It seems that we'll need a way to call this method from Atom, but not having grasped how all the parts of Atom/Electron fit together I'm not sure where to start making this connection.

Electron already includes calls to the render widget host view in `electron/atom/browser/api/atom_api_web_contents.cc`, although I'm not sure whether that's relevant here.

## Multiple Selections

As an additional issue, Atom text editors may contain multiple selections. The system services architecture does not seem to accommodate this: The methods for exchanging data with services are called by the operating system and allow transmitting a single piece of data (per distinct pasteboard key).

There is a way to invoke services programmatically using `NSPerformService`, but calling this function requires the *name* of the service, which none of the other methods reveal, so repeating a given service invocation for each selection seems not to be possible.

It seems that this leaves us with the choice of

*   either only ever invoking services on the first selections
*   or disabling services altogether when there are multiple selections.

[apple-services]: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/SysServices/Articles/using.html

**Comment by ToniWonKanobi** [comment]
@mkhl, in response to this:

> It seems that this leaves us with the choice of
>
> * either only ever invoking services on the first selections
> * or disabling services altogether when there are multiple selections.

... I would vote for the former (and I think most people would agree given the choice).

Most OS X Services users are okay with modifying only one text selection at at time.

If we could just do that, all would be well.

**Comment by alexchandel** [comment]
The lack of this means text services that all OS X users expect, like the built-in dictionary's `Look Up "x"`, the built-in text-to-speech's `Start Speaking`/`Stop Speaking`, and various other things like `Add to Notes`, are unavailable.

**Comment by magp** [comment]
This issue is still current in Atom 1.25.1 on a Mac OSX 10.13.3

Steps to reproduce:
0. Create a new file
1. Type text 
2. Select text
3. Select "Services" in the Atom menu

When doing this you will see that the services for text are not available.

**Comment by chrisjshull** [comment]
This issue is still current in Atom 1.36.0 on a macOS 10.14.4.

please reopen

**Comment by lee-dohm** [comment]
Thanks very much.

From what we've seen other than Services, most macOS tools that manipulate text within a program, such as TextExpander, interoperate with Atom's `TextEditor` without problems. Because of these workarounds, adding support for macOS Services is not something that the Atom team is going to take on.

We would be willing to review a very professionally written pull request. But because of the complexity of integrating with Atom at such a low level, it would need to be very detailed in its design, implementation, and testing, so that we can verify it would not be disruptive to the experience of other users. Please keep that in mind if anyone decides to tackle this task.

I'm going to close this issue and mark it with the `help-wanted` label so that others may find it if they're interested.

**Comment by rpkrajewski** [comment]
Just a comment from a mere end-user of Slack who's been watching this issue for about a year, after asking for macOS Services (and just read-only text services would be sufficient) to be enabled from Slack. It's kind of sad that a near-unicorn software company like Slack (IPO coming soon!) just delegates what is a piece of expected platform functionality to an open-source project whose priorities are quite different. Really, I don't care about Slack's dependencies, I just want to work more efficiently on my computer.
