### ISSUE TITLE
Ways to sync settings across different devices

### ISSUE THREAD

**Issue by haochuan** [atom/atom#10217]
Is there any good suggestion for syncing `Atom` settings across different devices?

**Comment by haochuan** [comment]
I know a lot of people using `git` or `dropbox` for `sublime`, not sure what's the best way for `Atom`

**Comment by lee-dohm** [comment]
There are a [number of suggestions](https://discuss.atom.io/t/syncing-settings-packages-between-machines/1385) for how to do this on Discuss, the official Atom message board. Personally, I use Git and [rcm](https://github.com/thoughtbot/rcm) to sync [my environment between my machines, including my Atom configuration.](https://github.com/lee-dohm/dotfiles)
