### ISSUE TITLE
Atom Freezes on Tall File 110kb 

### ISSUE THREAD

**Issue by slopesidecreative** [atom/atom#10215]
I have a file that is concatenated scripts from my Angular application. Atom cannot open it without locking up every time. This file is 109kb on disc. I've seen this over the past few days working with Gulp and script concatenation. and Atom. Many lockups. (OpenOffice easily opens the file. Sublime2 takes 30 seconds. Atom times out.)

I deleted the ~/.atom/storage contents but that didn't help.

**Comment by 50Wliu** [comment]
@slopesidecreative by "concatenated scripts", do you mean that the file contains very long lines?

**Comment by slopesidecreative** [comment]
@50Wliu it has 1100 lines (not that tall), with the last line being very wide across the screen - i have to scroll and scroll horizontally on a MacBook Pro -- it is a base 64 encoding so there is no line break. This file is generated in a Gulp build process by Browserify using a recipe from the Gulp site. The files are concatenated, but not yet processed thru Uglify. (btw - Atom has been awesome, this is the first hiccup I've encountered.)

**Comment by 50Wliu** [comment]
Yeah, Atom currently has lots of trouble processing either very large (~5MB+) files, or very long ones.  Sorry about that.  For updates, you can try subscribing to #979.

Glad to see you're liking Atom, and sorry again for the trouble.
