### ISSUE TITLE
small bug for chinese user

### ISSUE THREAD

**Issue by jatlee** [atom/atom#10222]
press "shift“ to switch input method is the commonly used in chinese.
but in atom, when press "shift+cmd+..." is invited the input method switch,but is not mine intent

**Comment by mnquintana** [comment]
What do you mean by the "input method"? What keyboard layout are you using?

**Comment by 50Wliu** [comment]
@mnquintana By "input method", @jatlee means to switch from typing English to Chinese, and vice versa.  Google Pinyin Input and the builtin Microsoft Pinyin are just two examples that use the <kbd>shift</kbd> key to switch between writing English and Chinese.  I don't think keyboard layout is relevant here.

That being said I can't reproduce this by trying to press <kbd>Shift+Ctrl+L</kbd> or <kbd>Ctrl+Shift+L</kbd> to activate the grammar selector.
