### ISSUE TITLE
Atom freezes when opening two files with the same folder/name but different parent folders 

### ISSUE THREAD

**Issue by vinodpanicker** [atom/atom#10220]
*Atom freezes when opening two files with the same folder/name but different parent folders*

The folder structure is a below 

0 . Root-folder 

----1.parent-1
         (1.1.) child 
              (1.1.1.) childs-child.txt

----2. parent-2
        (2.1.) child
              (2.1.1.) childs-child.txt

Atom freezes when you try to open (2.1.1) childs-child.txt after editing (1.1.1) childs-child.txt

Only work around is to close the previous file with the same name before opening the next one with the same parent-child path.

**Comment by jeancornic** [comment]
+1
Happens a lot when dealing with ansible roles..

**Comment by mnquintana** [comment]
Thanks for the report! This has already been fixed in the 1.4 betas.

**Comment by vinodpanicker** [comment]
Thanks , checked this out on atom 1.4 beta3 , works fine now. 

Waiting for this to come to the stable versions.
