### ISSUE TITLE
[OS X][Performance] Atom consumes a lot of resources when non-git folder open

### ISSUE THREAD

**Issue by sadikovi** [atom/atom#10221]
Atom starts taking 100% CPU and a lot of memory when opened with project folder that is **not git** repository. Reproducible in safe mode too. If new window open without any project folder or project folder is git repository, everything works perfectly well.

#### System info
OS X El Capitan 10.11.2 (15C50)
Intel Core i5 2.4 GHz, 4 GB

Atom version: 1.3.2

#### Steps to reproduce:
1. Open atom in non-git project folder
```shell
$ cd developer
$ atom --safe .
```
2. Once editor is open, create new tab and start typing any text, e.g.
```
sdfljsdflj
sdfljsdflj
sdfljsdfljsdf
sdflj sdfljsdf sdfljsdf sdfljsdf
sflj sdfljsdflj sdfljdslf sdflj
sdfljsdf sdfljdsfljsdf sdfljsdf 
sdfljsdf sdflj sdfljsdf sdfljsadfj sdfljsdf sdfljl sdf
```
3. You will notice how atom starts responding with delays, cpu goes up to 100%, and memory consumption increases. Agree, it sounds a little bit random, but it does not seem to be related to whether it is simple plain text or syntax highlight selected. The same behaviour observed with editing **.py** file with python syntax highlighting on.

#### Reports
Developer console does not show any errors, I tried recording profile:
![cpu-profile](https://cloud.githubusercontent.com/assets/7788766/12047969/3ea345e0-af39-11e5-9e51-59b9effbab1c.jpg)

[CPU-20151230T204350.cpuprofile.zip](https://github.com/atom/atom/files/74680/CPU-20151230T204350.cpuprofile.zip)

I appreciate any help on this issue, any apologies if it is just me doing something wrong with atom.

**Comment by ChrisJefferson** [comment]
Could you try being a little more concrete in how we should reproduce this problem?

Does this happen if 'developer' is an empty directory? Do you save the new file, or just click on 'new file' and start typing?

I tried reproducing this with an empty directory, and a random project of mine, on the same Mac / Atom version as you, and don't get the same problem

**Comment by 50Wliu** [comment]
@sadikovi do you by any chance have your home folder as a git repository?

**Comment by sadikovi** [comment]
@ChrisJefferson No, it does not matter, whether it is empty directory or not, as long as it is not a git repository. Again, it does not seem to matter whether you open saved file or start new one under that folder. Once you open / start new file in that folder and start typing, atom seems to spend a lot of time on "keychange" event.

**Comment by sadikovi** [comment]
@50Wliu Yes, it appears I do have my home folder as a git repository.

**Comment by sadikovi** [comment]
Interesting, I removed `.git` folder from home directory and everything seems to work fine now. Again, I will test it later and report results. Thanks @50Wliu.

**Comment by joshaber** [comment]
Ah yeah, that's the same as https://github.com/atom/atom/issues/6437, fixed in https://github.com/atom/atom/pull/10249.

**Comment by sadikovi** [comment]
Yeah, thanks @joshaber.
