### ISSUE TITLE
The string "cursor={" causes lines to overlap.

### ISSUE THREAD

**Issue by OKNoah** [atom/atom#10237]
I have some code like this:

    render: () => {
      return (
        <div className="page">
          <div className="cli">
            <div className="hero">
              <Typist
                cursor=
                className="typist"
              >
                Hello
              </Typist>
            </div>

If I complete the line that says `cursor=` to `cursor={`, the line `className="typist"` will jump up one line and over lapp with the line above.

![screen shot 2015-12-30 at 2 47 39 pm](https://cloud.githubusercontent.com/assets/3739277/12058771/52c5b826-af04-11e5-922d-16fa337c7f5e.png)

**Comment by 50Wliu** [comment]
Hi @OKNoah, can you try to reproduce this in safe mode (`atom --safe`)?  Thanks!

**Comment by OKNoah** [comment]
Nope, and neither can I reproduce it after opening in safe mode, closing, and opening in non-safe mode. Despite restarting atom before and still being able to reproduce it.

**Comment by 50Wliu** [comment]
All right, glad to see that it isn't happening anymore.  If this pops up again, you can try using @mark-hahn's [package-cop](https://atom.io/packages/package-cop) package to bisect the issue.
