### ISSUE TITLE
About the Markdown function

### ISSUE THREAD

**Issue by willstudy** [atom/atom#10239]
A little awkward...  Can you help us to improve this function ??
I really like to write my blog in Markdown style..
But when writing a very long blog, I slide my blog constantly, however the preview stay there silently... It's a really trouble for me 

=_= || .  

Please make it better in your spare time...  Thank you Thank you !!

**Comment by lee-dohm** [comment]
I'm not sure what you're saying is wrong with the Markdown capabilities of Atom. Can you give a screenshot or a step-by-step description of what is happening?

**Comment by willstudy** [comment]
I am sorry for my poor english... I will illustrate it in a picture.
Thanks for your reply.
![Uploading 49BC7234-8421-45B6-8EF7-F55EDE148A19.png…]()

**Comment by willstudy** [comment]
I am sorry for my poor english . I will illust

**Comment by willstudy** [comment]
I am sorry for my poor english.. and I wan to illustrate it in a picture.. Thanks for your reply.
![49bc7234-8421-45b6-8ef7-f55ede148a19](https://cloud.githubusercontent.com/assets/12168193/12062551/93e388bc-afd9-11e5-821f-6bc41abd9bcd.png)

**Comment by mnquintana** [comment]
Ah, in that case it sounds like you're looking for https://github.com/atom/markdown-preview/issues/24 – feel free to subscribe there for updates.

**Comment by willstudy** [comment]
That's it !! Thank you very much !
