### ISSUE TITLE
atom --wait should open files in a tab instead of a new window

### ISSUE THREAD

**Issue by liudangyi** [atom/atom#10244]
When I use `atom .git/COMMIT_EDITMSG`, the file is opened in the current atom window, that's fine.

But when I use `atom --wait .git/COMMIT_EDITMSG`, the file is opened in a new window with working directory of ".git", which is quite slow and not what I want.

**Comment by damieng** [comment]
Unfortunately because of the way the command line has to wait for the atom process to finish it has to open a new copy of atom.

**Comment by ajb** [comment]
Dang, that's a shame. I was following this issue because this behavior makes it really hard to use Atom as `git`'s editor. Any recommendations on that front? Or any hope of this ever being fixed? (I'm assuming something would need to be changed upstream, in Electron?)

**Comment by damieng** [comment]
It's nothing specific to Electron - it's more the way command line tools
wait for other tools to complete by starting a process and waiting for it
to terminate.

Do you have examples of any other editors that can be the git editor
without firing up a new instance/window?

**Comment by liudangyi** [comment]
https://github.com/atom/atom/blob/7aab88c4f62eb671bdfb9c036d1f0733f913109d/src/browser/atom-application.coffee#L468

Is it possible to listen on a tab's close event?

**Comment by lee-dohm** [comment]
It's possible for things with access to Atom's API to listen for an editor's close event. There's no mechanism for something outside of Atom (like a command-line script) to listen for an editor's close event.

**Comment by liudangyi** [comment]
However, in this case, Atom sends SIGTERM to its parent process manually, not by SIGCHILD.

**Comment by ajb** [comment]
> It's nothing specific to Electron - it's more the way command line tools
wait for other tools to complete by starting a process and waiting for it
to terminate.

Ah, that makes sense. Sublime has some sort of workaround though:

![img](http://take.ms/nVyEC)

**Comment by ajb** [comment]
@lee-dohm: Given the above discussion, would the Atom team consider this as a valid feature request?

**Comment by damieng** [comment]
It could be cool to add and we don't actually wait for processes today, we actively terminate launch processes but track it by Window not by file.

Re-opening as a potential feature request.

**Comment by ajb** [comment]
Awesome. Thanks so much!

**Comment by moubi** [comment]
Is there any work being done on this issue, it has been almost year ago? 
Opening new window instead of tab when committing with git is still in place. 
More of a sublime behaviour is wanted :)

**Comment by 50Wliu** [comment]
You are free to help out by creating a PR.
