### ISSUE TITLE
Scolling does not work on a MS precision touchpad.

### ISSUE THREAD

**Issue by christakahashi** [atom/atom#10243]
### Background
Starting with win8 Microsoft has started supported something it calls [precision touchpads](http://windows.microsoft.com/en-us/windows-8/touchpad).  From what I understand this generates different events from the normal mouse scroll wheel.  

### Environment
I'm running windows 10 (on a surface book with precision touchpad) with atom 1.3.2.

### Issue
Scrolling using the two finger gesture on the precision touchpad doesn't work.

**Comment by opus1269** [comment]
I just got a new Dell Inspiron running Windows 10 with a precision touchpad. The two finger gesture does work for scrolling but it is a very slow in Atom editor windows (v 1.4.1). Much slower than Chrome, Android Studio, or native Windows apps. However the scroll speed is good in non-editor windows treeview, settings, etc.

**Comment by christakahashi** [comment]
Seems to be working now along with other similar issues i've had with some websites and the precision touchpad.  Not sure if it's a chrome(ium) fix, or a MS fix, or individual fixes to atom and chrome and individual websites.  In any case it's fixed.
