### ISSUE TITLE
Cannot install ATOM in windows 

### ISSUE THREAD

**Issue by sasitha** [atom/atom#10245]
I can't install ATOM in my windows laptop

IEnableLogger: Failed to install package to app dir: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters

[#damnitraathi](https://twitter.com/raathigeshan)

**Comment by 50Wliu** [comment]
Hi @sasitha, sorry for the inconvenience.  This has already been reported in #5109, and you can try some workarounds there.
