### ISSUE TITLE
Can't tell the difference between spaces and tabs

### ISSUE THREAD

**Issue by ericandrewlewis** [atom/atom#10240]
I can't tell the difference visually between spaces and tabs, namely at the beginning of an indented line.

Sublime Text has this feature [hidden behind a config flag](http://stackoverflow.com/questions/10153998/sublime-text-2-view-whitespace-characters), and looks like this:

<img width="316" alt="screen shot 2015-12-31 at 11 58 52 am" src="https://cloud.githubusercontent.com/assets/1087646/12066444/ff7e84b0-afb5-11e5-8c0b-a5167edd9d1b.png">

Can we do something similar in Atom?

**Comment by lee-dohm** [comment]
Atom has this feature built-in. You can see it by turning on "Show Invisibles" in the Atom Settings View:

<img width="580" alt="screen shot 2015-12-31 at 9 10 23 am" src="https://cloud.githubusercontent.com/assets/1038121/12066551/68cdd79e-af9e-11e5-80f3-2a57b1a83781.png">

**Comment by ericandrewlewis** [comment]
Ah, sorry and thank you! :smile:

**Comment by lee-dohm** [comment]
You're welcome, it's quite alright :grinning:

**Comment by private-ryan23** [comment]
where to enable it any way

**Comment by rsese** [comment]
@private-ryan23: the setting from Lee's screenshot is under `Settings > Editor`.
