### ISSUE TITLE
Find and replace using tokens/patterns (without regex)

### ISSUE THREAD

**Issue by nuno-agostinho** [atom/atom#10246]
A token is simply a common pattern of what we'd like to search (for example, instead of using a regex pattern representing a word, a number, a tab, a break, etc. we could insert a token that represents the same thing).

In OS X's built in find/replace (available in TextEdit and Notes, for example), although it's not possible to use regex we can use the following tokens to represent commons patterns:
![screen shot 2016-01-01 at 18 12 39](https://cloud.githubusercontent.com/assets/3199157/12071731/4a39ff04-b0b3-11e5-8a62-07659c21eae6.png)

Using tokens is easier than having to remember common used regex patterns for a simple find and replace. Also, a great common use case for this is to use the result of the pattern searched when replacing. For example, imagine you have a text like this:
```
you thank
diem carpe
python monty
```

And you'd like to find in the text WORD1 WORD2 and replace matches with WORD2 WORD1. The resulting text would be:
```
thank you
carpe diem
monty python
```

Simply inserting the same tokens in the Replace field would allow to find and replace WORD1 WORD2 with WORD2 WORD1. This is achievable in the aforementioned OS X's find/replace feature and is presented like this:
![screen shot 2016-01-01 at 18 09 31](https://cloud.githubusercontent.com/assets/3199157/12071733/714be76a-b0b3-11e5-8578-20f6138088f4.png)

**Comment by YemSalat** [comment]
You have a bad example. There is already a regex pattern for 'Word', which is `\w`
So you can do: `(\w+) (\w+) -> $2 $1` To get the same effect.

**Comment by Zireael07** [comment]
It's not that there is no regex pattern for words, it's that tokens are easier to use/remember than regex patterns.

**Comment by YemSalat** [comment]
Sorry, I updated my comment while you were writing yours, I addressed your point above.

**Comment by nuno-agostinho** [comment]
@YemSalat I didn't know you could replace terms using regex like that so I'd like to thank you for teaching me that!

> I suppose that TextEdit and Note are not designed for editing code (…). Atom is mainly a code editor, so some assumptions can be made about its userbase, for example that they are comfortable using regular expressions.

You're right those programs are not intended for code editing. However, I don't use regex enough to remember all the commands I need when I'm indeed using it. It'd be just easier if there was some way to include tokens: they could be simple shortcuts to the regex expressions, after all.

**Comment by mnquintana** [comment]
This issue was moved to atom/find-and-replace#629
