### ISSUE TITLE
Double-click in Project Find Results crashes Atom 1.3.2 (Win 8.1)

### ISSUE THREAD

**Issue by fedsol** [atom/atom#10241]
After searching a project, the results come up as expected in the Project Find Results tab. Single-clicking opens them in new tab, but double-clicking causes the new tab to open blank and hang until "Editor is not responding" dialog appears. No workaround found so far, only recourse is allowing Atom to close completely.

("Just don't do that!" - I've been using various Eclipse-based IDEs for a decade, double-clicking on search results.)

**Comment by 50Wliu** [comment]
I can't reproduce this on Atom 1.5.0-dev-dbf7bed.  @fedsol can you please try reproducing this in safe mode (`atom --safe`)?  Thanks!

**Comment by fedsol** [comment]
Still crashes on `atom --safe` on 1.3.2. However, since you said you couldn't repro on 1.5.0-dev, I installed 1.4.0-beta3, and it does not crash. Therefore apparently something in 1.4.0 fixes it, so I'll close this.

**Comment by 50Wliu** [comment]
Awesome, glad to know that it's fixed!
