### ISSUE TITLE
fallback encoding

### ISSUE THREAD

**Issue by risperdal** [atom/atom#10252]
I opened an issue to here https://github.com/atom/encoding-selector/issues/27

But I think atom core is the right place.

In sublime there is two encoding options

One is default_encoding, the other is fallback_encoding

This is useful specifically for mixed encoding projects.

**default_encoding**

>  // Encoding used when saving new files, and files opened with an undefined
>     // encoding (e.g., plain ascii files). If a file is opened with a specific
>     // encoding (either detected or given explicitly), this setting will be
>     // ignored, and the file will be saved with the encoding it was opened
>     // with.
>     "default_encoding": "UTF-8"

**fallback_encoding**

> // The encoding to use when the encoding can't be determined automatically.
>   // ASCII, UTF-8 and UTF-16 encodings will be automatically detected.

**Comment by lee-dohm** [comment]
Summarizing my thoughts on this from the original Issue:

1. I agree that in specific situations it could be useful
1. In various other cases, it could be confusing or detrimental
    * If `default_encoding` is UTF-8 and `fallback_encoding` is ISO-8859-9 but the file is UTF-16, this strategy would use ISO-8859-9 instead of the correctly detected UTF-16

Given the above, I feel this would be best as a package rather than a core Atom feature.
