### ISSUE TITLE
Sometimes the Whole Atom Got Frozen

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/atom#10258]
If a certain condition is met, every time the whole Atom will be frozen and have to be closed and restarted. I don't know if this bug lies in the core or in the `tree-view`.

Steps to reproduce:

First, create 2 directories with 3 subdirectories:

```bash
mkdir lib
mkdir lib/c-v0.1.0
mkdir lib/c-v0.2.0
mkdir test
mkdir test/c-v0.1.0
```

Then, in each subdirectory place an empty file `main.js`:

```bash
touch lib/c-v0.1.0/main.js
touch lib/c-v0.2.0/main.js
touch test/c-v0.1.0/main.js
```

Then type `atom .` to open Atom. Then click these 3 files to open them. When the third file is clicked, the whole Atom will be frozen.

This bug exists in v1.3.2. I haven't tested beta versions.

**Comment by lee-dohm** [comment]
This has been fixed in the beta channel. Thanks for reporting!
