### ISSUE TITLE
Indent guide is crazy in XML files

### ISSUE THREAD

**Issue by Yajo** [atom/atom#10251]
Reopening https://github.com/atom/language-xml/issues/42 in the right place.

See this pic and you will understand what I mean:

![captura de pantalla de 2015-12-31 10-55-16](https://cloud.githubusercontent.com/assets/973709/12063319/06513688-afad-11e5-8358-4b781dfea681.png)

Atom 1.3.2. Fedora 23. No Emmet plugin installed. Issue happens with `atom --safe`.

**Comment by 50Wliu** [comment]
I suspect that this is the same issue as #9369.  @Yajo can you please try increasing/decreasing the font size to see if the problem fixes itself at a certain font size?  If so then it's probably a duplicate of #9369.

**Comment by Yajo** [comment]
Thanks, I tried. No matter the zoom, the lines stay the same.
