### ISSUE TITLE
Atom Run Error From Ubuntu Terminal

### ISSUE THREAD

**Issue by udoyen** [atom/atom#10253]
Atom doesn't launch as expected from terminal on ubuntu

**Reproduction Steps:**
1. go to a directory from terminal
2. launch with `atom .` or `sudo atom .`

**Expected behavior:**

atom should open said directory

**Observed behavior:**

when using just `atom .` it says _"permission denied"_, but when run like this `sudo atom .` the images below is seen: 
![console](https://cloud.githubusercontent.com/assets/3130489/12074061/d415758c-b13f-11e5-8da2-b9ac11d9cb98.png)

![screenshot from 2016-01-02 09 56 09](https://cloud.githubusercontent.com/assets/3130489/12074063/041da830-b140-11e5-84bd-4aae6917fed3.png)

**Screenshots and GIFs**

**see above images**

**Atom version:** 1.3.2
**OS and version:** Ubuntu LTS 14.04

**Installed packages:**
script
emmet
atom-typescript
language-smarty-php
linter
linter-tslint

**Additional information:**
- Problem can be reproduced in safe mode: [Yes]
- Problem started happening recently, didn't happen in an older version of Atom: [Yes]
- Problem can be reliably reproduced, doesn't happen randomly: [Yes]
- Problem happens with all files and projects, not only some files or projects: [Yes]

**Comment by udoyen** [comment]
@simurai, hi would be nice if you could help me here. Thanks

**Comment by varshit97** [comment]
Hi Udoyen,did you build the application without any errors???

**Comment by udoyen** [comment]
Hi @varshit97 I installed it using the "deb" from atom site, didn't actually build it myself. Perhaps there is a better way to install it. A pointer would be nice. Love atom and would want it as my main editor.

**Comment by 50Wliu** [comment]
@udoyen try changing the permissions on the `~/.atom` folder (recursively) so that your user has rwx permissions.

**Comment by varshit97** [comment]
Hey Udoyen even I got the same error while testing on ubuntu 15.04 after installing it with the deb file.
As you like Atom Editor so much :p you can use the built version as it isn't posing any errors.So try doing that.
If you run into any problems while building I am ready to help.

**Comment by varshit97** [comment]
Hi @50Wliu even setting 777(permissions) did not work.Tried it :(

**Comment by 50Wliu** [comment]
Oops, misread the error.  How about setting the permissions so that the root user can also access them?

**Comment by udoyen** [comment]
@varshit97 things just getting stranger. I did a complete removal of *atom* and had to install twice *(as the first install didn't show the necessary files and folders)* with a reboot using __deb package__ and the editor shows no error any more. It now works smoothly, but I am re-installing my earlier installed third party packages and watching to see if that was the original cause.

**Comment by varshit97** [comment]
@udoyen Its nice to hear its working and let me know if you figure out what caused that problem :p.

**Comment by dwhitena** [comment]
Hey guys @udoyen @varshit97, I getting the same thing on Ubuntu 15.10.  Same observed behavior as in the screenshots above.  I have done the following:

```
 $ sudo add-apt-repository ppa:webupd8team/atom
 $ sudo apt-get update
 $ sudo apt-get install atom
```

Also, I have tried the `*.deb` from the website.  Both multiple times, and both resulting in the same behavior.  Suggestions?

**Comment by dwhitena** [comment]
Also, @50Wliu I have checked the permissions on `~/.atom`, and get the same behavior even with 777.
