### ISSUE TITLE
OS X - 10.11.2 (El Capitan) - Atom Crashes when Closing a Window with a Project Folder

### ISSUE THREAD

**Issue by mike3run** [atom/atom#10250]
It only happens when on full screen mode.

Happens every time all the time.

Steps to perform the bug.

1. Open a Project folder
2. Go Full Screen Mode
3. Close current window by clicking the red circle on top left corner

4. App crashes

**Comment by 50Wliu** [comment]
@mike3run This issue has already been fixed in the 1.4.0 betas.  See #9584 for the original bug report.
