### ISSUE TITLE
Wrong paired brackets highlight

### ISSUE THREAD

**Issue by Chimit** [atom/atom#10254]
Mac OS, Atom 1.3.2, UI and Syntax Themes: One Dark.

If a string has a closing bracket ")", it is highlighted as a pair with the closest opening bracket:

![2016-01-02 19 53 58](https://cloud.githubusercontent.com/assets/839349/12074372/ae17f742-b18a-11e5-8eda-55500b47c145.png)

**Comment by mnquintana** [comment]
Thanks for the report! This looks like a duplicate of https://github.com/atom/bracket-matcher/issues/23 – feel free to subscribe there for updates.
