### ISSUE TITLE
"getaddrinfo EAGAIN" when searching for a package

### ISSUE THREAD

**Issue by Oxyrus** [atom/atom#10262]
Today I downloaded the .zip version of Atom from the releases, however whenever I try to search for a package I get the error getaddrinfo EAGAIN

![http://i.imgur.com/XwM6PKO.png](http://i.imgur.com/XwM6PKO.png)

I don't know if it may be related, but I can't load the Atom page in any of my devices.

**Comment by 50Wliu** [comment]
Yeah, that means atom.io is probably experiencing some technical difficulties right now.  I would try again later in a few hours.  Sorry about that!
