### ISSUE TITLE
Vertical scrolling when dragging text too fast, no preference for it

### ISSUE THREAD

**Issue by ProjectDent** [atom/atom#10263]
There was previously complaints that scrolling was too fast, so an option was added to preferences. It's still the case that if you're scrolling and highlighting text, so moving your mouse off the bottom while clicking and dragging, scrolls about 2x the speed it should. Try this in Sublime Text, or Xcode, where it's a much slower speed.

**Comment by lee-dohm** [comment]
So you want the "Scroll Sensitivity" setting to apply to selection-based scrolling too?

**Comment by ProjectDent** [comment]
Perhaps. If one seems too fast and one too slow, that might just lead to a person setting it somewhere in the middle and having neither be right.

**Comment by lee-dohm** [comment]
When I just experimented with it, the selection-scroll speed was variable based on how far you drag it past the border of the element. It sounds like you want a separate setting to cap the max scroll speed lower?

**Comment by ProjectDent** [comment]
You're right. Perhaps increase the distance required for it to go so fast? I find myself having to pay close attention if i want to scroll slowly, because 2/3 pixels more and I've passed it.

**Comment by einsteinx2** [comment]
I run into this constantly. After reading your comment @ProjectDent, that does appear to be the issue. If I go to just the right place, the scrolling speed is fine. But if I go just a few pixels lower BAM I'm at the bottom of the file. Since the sensitivity is so different from literally every other editor I use, it constantly happens. If the sensitivity range were just increased, I think it would be perfect.

**Comment by garygreen** [comment]
@lee-dohm yes exactly, there needs to be a max cap on how fast it scrolls when selecting text, as at the moment you have to be ultra precise otherwise it'll just select the whole document almost instantly.

See the difference between sublime and atom... in sublime there's a max cap and you can't accidentally select text ultra fast (good imo).

![sublime scroll cap](https://cloud.githubusercontent.com/assets/1702638/17861932/febb009c-688a-11e6-879e-83f8f535592f.gif)

![atom scroll selection speed bug](https://cloud.githubusercontent.com/assets/1702638/17861939/045d0b30-688b-11e6-8aef-c44bb024dc49.gif)

**Comment by starInEcust** [comment]
+1

**Comment by Oblik-Design** [comment]
Select scroll is wayyyyy to fast, there is a slower mode if you go really slowly up top, but it is not easy to get it right, there has to be a middle ground... It is really frustrating. It is the only editor that does this. I've tried, brackets, vs.. sublime.. none of them has this issue.

**Comment by garygreen** [comment]
@nathansobo @50Wliu this is probably the most frustrating thing in Atom atm and should be fixed as priority imo. At the moment selecting text by mouse is pretty much impossibru without bashing your head into the screen.

**Comment by 50Wliu** [comment]
> At the moment selecting text by mouse is pretty much impossibru without bashing your head into the screen.

Personally, I've had no problems with the selection speed.  Based on the comments however this certainly seems up for debate.

**Comment by pear1** [comment]
Same here.
Very annoying after using Sublime Text.

**Comment by calculator** [comment]
+1

**Comment by stevgouws** [comment]
+1

**Comment by callmeaponte** [comment]
+1

This is pretty frustrating... Hopefully it's an easy fix. At the very least please give us a setting to control this behavior.

**Comment by matt-curtis** [comment]
+1. Absolutely necessary, I run into this issue several times a day

**Comment by holyboly** [comment]
+1
This is one of two no gos. The second one is opening compressed/large files => crash.

**Comment by Oblik-Design** [comment]
I'm so tired of this, this needs to be fixed ASAP,  else i'll have to move on to others.. It is way too sensible. I know I've said it before, but everything else is so great, it's now the way I scroll up 20 pages long on code to get back to the top , selecting up is faster than the keyboard shortcut... EVERY other ide those this better, if MS can do it right...

**Comment by matt-curtis** [comment]
I'm very new to the Atom ecosystem, but if someone would point me in the right direction as to get started I'd give it a go.

**Comment by 50Wliu** [comment]
This looks like it'll help: https://github.com/atom/atom/blob/2095015e8221ad1873d037efd7cbd49d7c013c5b/src/text-editor.coffee#L3452
Try using that method and see if you get any results.

**Comment by Oblik-Design** [comment]
It's text selected scrolling, wheel scroll is fine. The problem is well presented in the animated gif up there. Atom is asking it's users to be crazy precise, like no other software before and since...

**Comment by matt-curtis** [comment]
^ Exactly.

**Comment by Oblik-Design** [comment]
matt-curtis, you most likely, are not at the right place.

**Comment by 50Wliu** [comment]
Finally found the quadratic PR I was talking about previously: https://github.com/atom/atom/pull/8548
I'm not sure how relevant that still is or if it's still even in place, but at least it should give you an idea of how to modify the scrolling speed (and hopefully actually helps with this issue, unlike my last link).

**Comment by Oblik-Design** [comment]
Weird that this thread/discution was over a year ago, and still this issue is not resolved at all, where did this version go?

**Comment by Oblik-Design** [comment]
Wow THANK GOD FOR THE UPDATE THAT FIXES IT !!!!

**Comment by Oblik-Design** [comment]
Thought the update would fix this... , where to write to get that text scroll fixed. -sorry for any mistake, english is a third language to me.

**Comment by agersoncgps** [comment]
I would like to add my voice to the chorus asking for slower scroll speed when dragging with the mouse, or a setting to control it. The lack of this makes precision slecting of text of more than a few lines that may not be visible very dificult.

**Comment by matt-curtis** [comment]
Switched to VS Code. :/

**Comment by mb3152** [comment]
This is the worst part of Atom.
