### ISSUE TITLE
Keybindings are not selecting.

### ISSUE THREAD

**Issue by Qix-** [atom/atom#10264]
> I tried to search to see if there was a core package related to keybindings but _low and behold_ Github's repo search box is broken. Technology not on my side today.

Well, here are two scenarios where keybindings have been messed up.

First one was when I was attempting to set up custom keybindings for a package I was developing. I tried the same selector format as other plugins, to no avail. Keybinding-Resolver was showing it was there. The element was even focused. Nothing. Atom didn't seem to care.

The second scenario, now prompting this issue, is when an upgrade failed for `ex-mode` (vim) and things started acting weird, I decided to re-install both `vim-mode` and `ex-mode` (hilarious they are two separate packages, by the way).

Certain keybinds work. Others don't. For instance, `ci"` and `gg` do not work, but `G` does. Once again, keybind-resolver is showing correct bindings, but the selector system doesn't seem to think the current pane is worthy of having them trigger.

The selection system is dreadfully picky, and now I'm left with a half-broken Vim setup forcing me to go back to _ye olde vim_ until this is fixed. I have absolutely no idea how to go about fixing this because it's all incredibly ambiguous. The keybinding system is random at best.

And nope, no other packages are fighting for these bindings (I don't have very much installed). No errors in the console. Keybindings configuration is clean. Nothing in my init script. This is a pure example of the keybindings system being way too selective.

For instance, here is me trying to do `gg` after the re-install.

First `g`:

<img width="1680" alt="screen shot 2016-01-03 at 16 51 37" src="https://cloud.githubusercontent.com/assets/885648/12081559/62f0af2e-b23a-11e5-8d61-da5b2d2800cc.png">

and then on the second `g`:

<img width="1680" alt="screen shot 2016-01-03 at 16 51 35" src="https://cloud.githubusercontent.com/assets/885648/12081560/7a40eee6-b23a-11e5-9b37-82966fdf8749.png">

**Comment by Qix-** [comment]
It's not stale, nobody chose to address it...

It's behavior like this that makes me not want to choose atom.

**Comment by Ben3eeE** [comment]
@Qix- There has been quite a lot of changes to Atoms keymap system since you reported this issue. It might be that it got fixed and this issue was not closed.

The vim-mode package is also deprecated in favor of the much more capable [vim-mode-plus package](atom.io/packages/vim-mode-plus).

Are you still able to reproduce this issue when trying the latest stable version of Atom (Currently 1.20.0) and vim-mode-plus?
