### ISSUE TITLE
"Install Shell Commands" not working while using beta

### ISSUE THREAD

**Issue by jgebhardt** [atom/atom#10261]
Repro steps:

1) Download & run v1.4.0-beta3, then run "Install Shell Commands" ; "atom and apm are now installed" message will appear.
2) neither `atom` nor `apm` are actually available on the command line.

This works with v1.3.2.

**Comment by 50Wliu** [comment]
> neither atom nor apm are actually available on the command line.

The commands are actually `atom-beta` and `apm-beta` - the dialog hasn't been updated yet for the Beta channel.  Sorry about the inconvenience, and please subscribe to #9361 for updates.
