### ISSUE TITLE
Repeated Ctrl +w also closes atom application when no more files are left open in the editor

### ISSUE THREAD

**Issue by vinodpanicker** [atom/atom#10268]
In Atom 1.4 beta 3 , Ctrl + w on linux/ubuntu closes the open file in the editor window,  but if you have a few files open and you are a heavy user of  ctrl+w to close them ,repeated ctrl+w also closes the application. 

This was not the behavior in the 1.3 , would be nice if the previous behavior is restored with changes in to the default key-mapping.

**Comment by joshaber** [comment]
Indeed, that was changed in https://github.com/atom/atom/pull/9607. You should be able to restore the old behavior by setting `closeEmptyWindows` to `false`.

**Comment by vinodpanicker** [comment]
Thanks @joshaber  tried this out, Would be nice if the default behavior was set to false. 

For me this saved me the need to restart atom every time i accidentally close the application . 
Better if it throws up a popup saying that => All files are closed do you really want to close the application?.

**Comment by joshaber** [comment]
I believe the current behavior is more standard on OS X, at least, so I'd advocate for keeping it. But we'll keep that in mind!
