### ISSUE TITLE
Atom cannot replace white space

### ISSUE THREAD

**Issue by razouckt** [atom/atom#10274]
I am trying to replace multiple spaces by just one. Apparenlty, this cannot be done with the great **Atom**.

![captura de tela de 2016-01-04 13-42-50](https://cloud.githubusercontent.com/assets/14312156/12093282/39ff9c10-b2e9-11e5-82be-fa22364db001.png)

Obrigado.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace? Thanks!

Also please add:
- Your version of Atom
- Your OS
- Whether or not you can reproduce this in safe mode
- Precise steps for reproducing this behavior

**Comment by razouckt** [comment]
Yes, I would mind.
