### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by Lazar-T** [atom/atom#10276]
Is there any way to add this feature manually? I've searched packages but haven't found anything...

I want to have smooth scrolling like the one in sublime text.

**Comment by lee-dohm** [comment]
Can you be a little more descriptive so we can be sure we're understanding what you want? What does "smooth scrolling" mean to you?

**Comment by Lazar-T** [comment]
Rather than trying to explain what I meant here's a video:

[![ss](http://i.imgur.com/j2iKmbD.png)](https://youtu.be/bZ3UzU8xGo4)

I'm guessing sublime text integrated some short time delay when scrolling while atom uses no delay. Hope this cleared what I meant by smooth.

**Comment by lee-dohm** [comment]
What are you using to do the scrolling? What OS are you on? I get the smooth scrolling experience on OS X using a trackpad.

**Comment by Lazar-T** [comment]
Ubuntu, and on desktop so no trackpad.

**Comment by mnquintana** [comment]
@Lazar-T Does that mean you're using a mouse with a scroll wheel?

**Comment by Lazar-T** [comment]
Yes

**Comment by VoronaPavel** [comment]
Scrolling in sublime has some transition time so it looks more smooth. Whereas atom just makes all lines jump almost instant.
+1 for this feature

**Comment by NicolasParada** [comment]
Smooth scrolling has been in chrome since version 49 https://developers.google.com/web/updates/2016/02/smooth-scrolling-in-chrome-49?hl=en
Electron uses version 49 of chrome since 0.37.0, but atom editor, even in beta, still uses electron 0.36.0 so...

**Comment by 50Wliu** [comment]
Closing in favor of #5359.

**Comment by ConsoleTVs** [comment]
Atom 1.19:

```css
atom-text-editor > div > .scroll-view > div,
atom-text-editor > div > .gutter-container > div {
    transition: -webkit-transform .15s ease;
}
```
