### ISSUE TITLE
Could not search in UTF-16 files

### ISSUE THREAD

**Issue by Komosa** [atom/atom#10270]
Atom can properly display UTF-16 (LE, with BOM) files, but couldn't search within them.
Scenario: open [attached file](https://github.com/atom/atom/files/77172/can_you_grep_this.txt), and search for word `grep`.

One result is expected, but no one is found.

Atom version: 1.3.0

**Comment by lee-dohm** [comment]
This issue was moved to atom/find-and-replace#632
