### ISSUE TITLE
editor hangs for very long time with 7.5k file

### ISSUE THREAD

**Issue by speter** [atom/atom#10272]
I've found similar reports when using Atom with large files but my file is less than 300 lines with less than 150 characters each.

**Reproduction Steps:**

1. Download and open the file https://github.com/go-gcfg/gcfg/blob/083575c3955c85df16fe9590cceab64d03f5eb6e/set.go#L242
2. Go to the end of line 242 (btw I find it weird that in Windows the last character is not displayed in full so the cursor at the end is also not visible)
3. Press Enter

**Expected behavior:**

New line is started at L243

**Observed behavior:**

Atom editor window hangs for a very long time. (I thought it was indefinite but it came back after an hour or so.) After that, new line is started.

**Screenshots and GIFs**

![screenshot](https://cloud.githubusercontent.com/assets/450945/12091952/91203fdc-b33d-11e5-8a6f-8a288456d23a.png)

**Atom version:** 1.3.1 and 1.4.0beta3
**OS and version:** Win8.1 64bit, Debian8.2 64bit

**Installed packages:**

Just the core packages.

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: No

**Comment by davidvgalbraith** [comment]
I am able to reproduce this. Better yet, I am able to chase down its root cause and put together a fix: https://github.com/atom/language-go/pull/79.
