### ISSUE TITLE
Error when opened Atom from command line

### ISSUE THREAD

**Issue by dyf102** [atom/atom#10278]
<pre>
2016-01-04 17:11:53.644 Atom[69130:4515750] *** Assertion failure in +[SQRLDirectoryManager currentApplicationManager], /Users/joshaber/Documents/Development/GitHub/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30
2016-01-04 17:11:53.688 Atom[69130:4515750] An uncaught exception was raised
2016-01-04 17:11:53.688 Atom[69130:4515750] Could not automatically determine the current application's identifier
2016-01-04 17:11:53.689 Atom[69130:4515750] (
        0   CoreFoundation                      0x00007fff8b108ae2 __exceptionPreprocess + 178
        1   libobjc.A.dylib                     0x00007fff93e07f7e objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff8b1088ba +[NSException raise:format:arguments:] + 106
        3   Foundation                          0x00007fff9723988c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
        4   Squirrel                            0x000000010e849c5f __49+[SQRLDirectoryManager currentApplicationManager]_block_invoke + 435
        5   libdispatch.dylib                   0x00007fff98f3033f _dispatch_client_callout + 8
        6   libdispatch.dylib                   0x00007fff98f30237 dispatch_once_f + 67
        7   Squirrel                            0x000000010e849aaa +[SQRLDirectoryManager currentApplicationManager] + 106
        8   Squirrel                            0x000000010e84a813 +[SQRLShipItLauncher shipItJobLabel] + 35
        9   Squirrel                            0x000000010e850959 __37-[SQRLUpdater pruneUpdateDirectories]_block_invoke + 55
        10  ReactiveCocoa                       0x000000010e8894c6 __31+[RACSignal(Operations) defer:]_block_invoke + 37
        11  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        12  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        13  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        14  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        15  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        16  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        17  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        18  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        19  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        20  ReactiveCocoa                       0x000000010e880890 __31-[RACSignal(Operations) catch:]_block_invoke + 374
        21  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        22  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        23  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        24  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        25  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        26  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        27  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        28  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        29  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        30  ReactiveCocoa                       0x000000010e89c59a __31-[RACSignal(RACStream) concat:]_block_invoke + 346
        31  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        32  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        33  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        34  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        35  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        36  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        37  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        38  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        39  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        40  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        41  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        42  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        43  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        44  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        45  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        46  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        47  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        48  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        49  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        50  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        51  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        52  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        53  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        54  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        55  ReactiveCocoa                       0x000000010e87e3da __33-[RACSignal(Operations) doError:]_block_invoke + 266
        56  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        57  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        58  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        59  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        60  ReactiveCocoa                       0x000000010e87e88a __37-[RACSignal(Operations) doCompleted:]_block_invoke + 266
        61  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        62  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        63  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        64  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        65  ReactiveCocoa                       0x000000010e88a5ee __35-[RACSignal(Operations) deliverOn:]_block_invoke + 318
        66  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        67  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        68  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        69  ReactiveCocoa                       0x000000010e88ad1e __37-[RACSignal(Operations) subscribeOn:]_block_invoke_2 + 38
        70  ReactiveCocoa                       0x000000010e87d2f9 -[RACScheduler performAsCurrentScheduler:] + 356
        71  libdispatch.dylib                   0x00007fff98f3b871 _dispatch_call_block_and_release + 12
        72  libdispatch.dylib                   0x00007fff98f3033f _dispatch_client_callout + 8
        73  libdispatch.dylib                   0x00007fff98f34f6f _dispatch_queue_drain + 754
        74  libdispatch.dylib                   0x00007fff98f3b63b _dispatch_queue_invoke + 549
        75  libdispatch.dylib                   0x00007fff98f4372e _dispatch_main_queue_callback_4CF + 422
        76  CoreFoundation                      0x00007fff8b04ecd9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
        77  CoreFoundation                      0x00007fff8b009d3d __CFRunLoopRun + 1949
        78  CoreFoundation                      0x00007fff8b009338 CFRunLoopRunSpecific + 296
        79  HIToolbox                           0x00007fff8d49e935 RunCurrentEventLoopInMode + 235
        80  HIToolbox                           0x00007fff8d49e76f ReceiveNextEventCommon + 432
        81  HIToolbox                           0x00007fff8d49e5af _BlockUntilNextEventMatchingListInModeWithFilter + 71
        82  AppKit                              0x00007fff8ee590ee _DPSNextEvent + 1067
        83  AppKit                              0x00007fff8f225943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
        84  AppKit                              0x00007fff8ee4efc8 -[NSApplication run] + 682
        85  Electron Framework                  0x000000010ab90ac1 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 304081
        86  Electron Framework                  0x000000010ab900dc _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 301548
        87  Electron Framework                  0x000000010abc6c43 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 525651
        88  Electron Framework                  0x000000010b0862cb _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5503963
        89  Electron Framework                  0x000000010b086205 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5503765
        90  Electron Framework                  0x000000010b0886b2 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5513154
        91  Electron Framework                  0x000000010b08255f _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5488239
        92  Electron Framework                  0x000000010b00c45c _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5004652
        93  Electron Framework                  0x000000010b00bab6 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5002182
        94  Electron Framework                  0x000000010aa1728d AtomMain + 77
        95  Atom                                0x000000010aa09eea main + 58
        96  libdyld.dylib                       0x00007fff999bf5ad start + 1
        97  ???                                 0x0000000000000002 0x0 + 2
)
2016-01-04 17:11:53.698 Atom[69130:4515750] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not automatically determine the current application's identifier'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fff8b108ae2 __exceptionPreprocess + 178
        1   libobjc.A.dylib                     0x00007fff93e07f7e objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff8b1088ba +[NSException raise:format:arguments:] + 106
        3   Foundation                          0x00007fff9723988c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
        4   Squirrel                            0x000000010e849c5f __49+[SQRLDirectoryManager currentApplicationManager]_block_invoke + 435
        5   libdispatch.dylib                   0x00007fff98f3033f _dispatch_client_callout + 8
        6   libdispatch.dylib                   0x00007fff98f30237 dispatch_once_f + 67
        7   Squirrel                            0x000000010e849aaa +[SQRLDirectoryManager currentApplicationManager] + 106
        8   Squirrel                            0x000000010e84a813 +[SQRLShipItLauncher shipItJobLabel] + 35
        9   Squirrel                            0x000000010e850959 __37-[SQRLUpdater pruneUpdateDirectories]_block_invoke + 55
        10  ReactiveCocoa                       0x000000010e8894c6 __31+[RACSignal(Operations) defer:]_block_invoke + 37
        11  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        12  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        13  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        14  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        15  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        16  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        17  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        18  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        19  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        20  ReactiveCocoa                       0x000000010e880890 __31-[RACSignal(Operations) catch:]_block_invoke + 374
        21  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        22  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        23  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        24  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        25  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        26  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        27  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        28  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        29  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        30  ReactiveCocoa                       0x000000010e89c59a __31-[RACSignal(RACStream) concat:]_block_invoke + 346
        31  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        32  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        33  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        34  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        35  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        36  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        37  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        38  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        39  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        40  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        41  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        42  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        43  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        44  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        45  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        46  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        47  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        48  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        49  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        50  ReactiveCocoa                       0x000000010e89b91d __29-[RACSignal(RACStream) bind:]_block_invoke + 947
        51  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        52  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        53  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        54  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        55  ReactiveCocoa                       0x000000010e87e3da __33-[RACSignal(Operations) doError:]_block_invoke + 266
        56  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        57  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        58  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        59  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        60  ReactiveCocoa                       0x000000010e87e88a __37-[RACSignal(Operations) doCompleted:]_block_invoke + 266
        61  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        62  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        63  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        64  ReactiveCocoa                       0x000000010e89e05b -[RACSignal(Subscription) subscribeNext:error:completed:] + 721
        65  ReactiveCocoa                       0x000000010e88a5ee __35-[RACSignal(Operations) deliverOn:]_block_invoke + 318
        66  ReactiveCocoa                       0x000000010e8a9a1b __30-[RACDynamicSignal subscribe:]_block_invoke + 59
        67  ReactiveCocoa                       0x000000010e8a2507 -[RACSubscriptionScheduler schedule:] + 276
        68  ReactiveCocoa                       0x000000010e8a997e -[RACDynamicSignal subscribe:] + 491
        69  ReactiveCocoa                       0x000000010e88ad1e __37-[RACSignal(Operations) subscribeOn:]_block_invoke_2 + 38
        70  ReactiveCocoa                       0x000000010e87d2f9 -[RACScheduler performAsCurrentScheduler:] + 356
        71  libdispatch.dylib                   0x00007fff98f3b871 _dispatch_call_block_and_release + 12
        72  libdispatch.dylib                   0x00007fff98f3033f _dispatch_client_callout + 8
        73  libdispatch.dylib                   0x00007fff98f34f6f _dispatch_queue_drain + 754
        74  libdispatch.dylib                   0x00007fff98f3b63b _dispatch_queue_invoke + 549
        75  libdispatch.dylib                   0x00007fff98f4372e _dispatch_main_queue_callback_4CF + 422
        76  CoreFoundation                      0x00007fff8b04ecd9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
        77  CoreFoundation                      0x00007fff8b009d3d __CFRunLoopRun + 1949
        78  CoreFoundation                      0x00007fff8b009338 CFRunLoopRunSpecific + 296
        79  HIToolbox                           0x00007fff8d49e935 RunCurrentEventLoopInMode + 235
        80  HIToolbox                           0x00007fff8d49e76f ReceiveNextEventCommon + 432
        81  HIToolbox                           0x00007fff8d49e5af _BlockUntilNextEventMatchingListInModeWithFilter + 71
        82  AppKit                              0x00007fff8ee590ee _DPSNextEvent + 1067
        83  AppKit                              0x00007fff8f225943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
        84  AppKit                              0x00007fff8ee4efc8 -[NSApplication run] + 682
        85  Electron Framework                  0x000000010ab90ac1 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 304081
        86  Electron Framework                  0x000000010ab900dc _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 301548
        87  Electron Framework                  0x000000010abc6c43 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 525651
        88  Electron Framework                  0x000000010b0862cb _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5503963
        89  Electron Framework                  0x000000010b086205 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5503765
        90  Electron Framework                  0x000000010b0886b2 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5513154
        91  Electron Framework                  0x000000010b08255f _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5488239
        92  Electron Framework                  0x000000010b00c45c _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5004652
        93  Electron Framework                  0x000000010b00bab6 _ZN4base8internal30DstRangeRelationToSrcRangeImplIilLNS0_21IntegerRepresentationE1ELS2_1ELNS0_26NumericRangeRepresentationE0EE5CheckEl + 5002182
        94  Electron Framework                  0x000000010aa1728d AtomMain + 77
        95  Atom                                0x000000010aa09eea main + 58
        96  libdyld.dylib                       0x00007fff999bf5ad start + 1
        97  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
</pre>

**Comment by joshaber** [comment]
:laughing: 

@dyf102 That's quite odd. Is it possible the app has been corrupted somehow? Does this happen if you download a fresh copy from https://atom.io?

**Comment by dyf102** [comment]
@joshaber  fresh copy still has this issue, but there is no problem when I open it from dock.

**Comment by joshaber** [comment]
How are you launching it from the command line?

**Comment by dyf102** [comment]
create soft link
lrwxr-xr-x  1 root  admin  42 25 Dec 19:35 /opt/local/bin/Atom ->
/Applications/Atom.app/Contents/MacOS/Atom

**Comment by joshaber** [comment]
I can't reproduce that crash, but it does behave oddly when launched that way.

Instead of doing that, I'd recommend doing Atom -> Install Shell Commands. Then you can launch `atom` from the Terminal and it should be :sparkles:

**Comment by dyf102** [comment]
It is Ok, I think the reason my link is linked
to /Applications/Atom.app/Contents/MacOS/Atom instead
of /Applications/Atom.app/Contents/Resources/app/atom.sh

Thank you guys so much

**Comment by greenscreen** [comment]
Had similar issue. 
[Steps to Replicate]
1. Make sure Atom is closed 
2. In Terminal try opening a file using `atom` command 
3. Open Atom from /Applications 
4. In Terminal try opening a file using `atom` command 

[Actual Results]
2. Would get the following exception: 
`2018-04-19 08:23:36.946 atom[38898:3539238] *** Assertion failure in +[SQRLDirectoryManager currentApplicationManager], /Users/joshaber/Documents/Development/GitHub/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30
2018-04-19 08:23:36.948 atom[38898:3539238] An uncaught exception was raised
2018-04-19 08:23:36.948 atom[38898:3539238] Could not automatically determine the current application's identifier` 

4. The file would get opened without issues if Atom was already running 

[Solution]
Fixed symbolic link in `~/bin`
Before: 
`atom -> /Applications/Atom.app/Contents/MacOS/Atom`
After:
`atom -> /Applications/Atom.app/Contents/Resources/app/atom.sh`
