### ISSUE TITLE
Atom crashing on OS X after closing window

### ISSUE THREAD

**Issue by jpxd** [atom/atom#10289]
Lately, after I close an Atom window with a project (another window with another project is open on another screen) entire Atom crashes.

```
Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread
 
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
```
Entire OS X crashlog: http://pastebin.com/snrr14Am

**Comment by nathansobo** [comment]
Am I understanding you correctly that this only happens when there are Atom windows on 2 different screens?

**Comment by joshaber** [comment]
This looks like the fullscreen window crash which has happily been fixed in the 1.4 betas.

**Comment by jpxd** [comment]
Seems to be so, at least I can only replicate it then (both Atom windows in fullscreen)

**Comment by jpxd** [comment]
When you say "fixed", am I missing an update somewhere?

**Comment by joshaber** [comment]
@jpxd The beta (https://atom.io/beta) has the fix. It hasn't been released to stable yet.

**Comment by jpxd** [comment]
Thanks :)

**Comment by a7madgamal** [comment]
Hate to be this person, but I have the same error :D
http://pastebin.com/EfdTyyC8
v1.10.2
I can provide more info as needed

**Comment by Ben3eeE** [comment]
@a7madgamal I believe your crash is covered by https://github.com/atom/atom/issues/12153. If you want to help out you can try the build that @maxbrunsfeld posted in https://github.com/atom/atom/issues/12153#issuecomment-248742288 and see if it still happens there.
