### ISSUE TITLE
Listening to window.toggle-full-screen using atom.commands.onWillDispatch does not retain originalEvent

### ISSUE THREAD

**Issue by Tyriar** [atom/atom#10287]
*Atom 1.3.2, Ubuntu 12.04*

Run the following in the console:

```js
atom.commands.onWillDispatch(function (e) {console.log(e.originalEvent)})
```

When using the default <kbd>F11</kbd> to trigger `window.toggle-full-screen` the `originalEvent` property is not set like with other keybindings.

Output:

```
(left)
KeyboardEvent {}

(home)
KeyboardEvent {}

(F11)
undefined
```

**Comment by maxbrunsfeld** [comment]
@Tyriar Yeah, I believe this is true for any events which originate from the application menu, rather than from a regular keyboard event. What are you trying to use the `originalEvent` property for?

**Comment by Tyriar** [comment]
@maxbrunsfeld but I pressed <kbd>F11</kbd> to trigger, why would that come from the application menu? I'm looking at building an extension that needs to know whether commands that were dispatched were dispatched via keyboard or not (command palette, menu).

**Comment by maxbrunsfeld** [comment]
Because that command is in the application menu, and has a keyboard shortcut defined in the application menu, the command is triggered by a different mechanism: it doesn't start from a `KeyboardEvent`.

**Comment by Tyriar** [comment]
@maxbrunsfeld But this doesn't happen for <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>r</kbd> to reload for example which is defined in [the same menu section](https://github.com/atom/atom/blob/master/menus/linux.cson#L98) and the [keymap is in the same scope](https://github.com/atom/atom/blob/master/keymaps/linux.cson#L9)?

**Comment by Tyriar** [comment]
Log after <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>r</kbd>:

```
KeyboardEvent {}
  altKey: true
  bubbles: true
  cancelBubble: false
  cancelable: true
  charCode: 0
  ctrlKey: true
  currentTarget: null
  defaultPrevented: true
  detail: 0
  eventPhase: 0
  keyCode: 82
  keyIdentifier: "U+0052"
  keyLocation: 0
  location: 0
  metaKey: false
  path: Array[16]
  repeat: false
  returnValue: false
  shiftKey: false
  srcElement: atom-text-editor.editor
  target: atom-text-editor.editor
  timeStamp: 1452215929940
  type: "keydown"
  view: Window
  which: 82
  __proto__: KeyboardEvent
```

**Comment by maxbrunsfeld** [comment]
That's a good question. Do all of the `F` keys behave this way? If you're interested in figuring this out, you could put a breakpoint in [`CommandRegistry::dispatch`](https://github.com/atom/atom/blob/dd1eb750fe95e4ab9bfeef294d98d1e738620102/src/command-registry.coffee#L181).

**Comment by Tyriar** [comment]
<kbd>F3</kbd> sets the `originalEvent` correctly.

When I stick a breakpoint in `CommandRegistry::dispatch` it is hit when I press <kbd>F11</kbd>, but not <kbd>F3</kbd> or <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>r</kbd>.

**Comment by Tyriar** [comment]
In other words you seem to be right as <kbd>F11</kbd> goes via `dispatchApplicationMenuCommand`, I'm still not understanding what exactly that distinction means though.

**Comment by Tyriar** [comment]
Found the problem, keybindings featuring uppercase F's in function keys simply don't work. It gets skipped over and ends up emitting `'did-fail-to-match-binding'` in `KeymapManager::handleKeyboardEvent`. It must then fallback to check the application menu somewhere. The core issue here is captured in https://github.com/atom/atom/issues/9194 and https://github.com/atom/atom/issues/9917. In the long term `KeymapManager` should either be compatible with uppercase function keys or error out on them.
