### ISSUE TITLE
Atom freezes when dragging file to split where same file is already opened

### ISSUE THREAD

**Issue by giantatwork** [atom/atom#10288]
Atom freezes when dragging file to split where it is already opened

**Reproduction Steps:**

1. Open up atom and create a new file, i.e. test.txt
2. Save this file and open up a vertical split.
3. The same file 'test.txt' is now opened in the new split.
4. Now drag the file in the left split to the right split.
5. Atom freezes.

**Expected behavior:**

The tab that is moved to the other split should merge with the target tab.

**Observed behavior:**

Atom freezes.

**Screenshots and GIFs**

http://take.ms/MYOv7

**Atom version:** 1.3.2
**OS and version:** OSX 10.11.2

**Installed packages:**

atom-beautify@0.28.19
atom-handlebars@1.3.0
atom-solarized-dark-ui@0.25.0
git-plus@5.9.0
highlight-selected@0.11.1
jshint@1.8.3
language-python-django-templates@0.1.0
linter@1.11.3
linter-flake8@1.9.3
linter-jslint@10.0.0
linter-php@1.1.6
linter-pylint@1.2.0
linter-ruby@1.2.1
minimap@4.19.0
minimap-highlight-selected@4.3.1
project-manager@2.6.5
solarized-dark-ui@0.3.1
tomorrow@1.0.0
vim-mode@0.64.0

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: Unknown
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by nathansobo** [comment]
Thanks for the detailed report, but I'm having trouble reproducing the issue.

I notice you're not in Safe Mode in the video. You're 100% sure this still happens when completely quitting Atom and starting with `atom --safe`?

**Comment by 50Wliu** [comment]
I think this is actually the "same-filename" freeze that has been fixed in the 1.4 betas.  @giantatwork if you can reproduce this on the 1.4 betas please let us know and I'll reopen this.

**Comment by giantatwork** [comment]
@50Wliu Tried to reproduce this problem in Atom 1.4.0-beta3, but no freeze this time.

**Comment by nathansobo** [comment]
Thanks @50Wliu!
