### ISSUE TITLE
Reindexing stuck in loop when there are symlinks to project directories

### ISSUE THREAD

**Issue by piit79** [atom/atom#10286]
Symlinks in the project pointing to directories within the project cause atom to get stuck in a loop (case 1) or report duplicate search matches (case 2).
### Case 1

Say there are the following entries in the project:

```
dir1
dir1/dir2
dir1/dir2/file1
dir1/dir2/symlink1 -> ..
```

The `symlink1` points to the parent directory. This creates a loop in the project filesystem and causes several issues:
- Atom gets stuck in a loop when reindexing the project. The reindexing will never finish
- When searching for matches within the project atom will again get stuck in a loop and keep reporting matches in the same files over and over
### Case 2

Consider the following project entries:

```
dir1
dir1/dir2
dir1/dir2/test.txt
symlink1-> dir1/dir2
```

In this case the `symlink1` points to a project directory further down the three. As a result the file test.txt is encountered **twice** when traversing the filesystem tree and any search matches will be reported twice.
### Fix

I think this should be handled cleanly by checking the target of symlinks in the project. If they point to other directories within the project they should not be followed when traversing the tree during reindexing/searching.

**Comment by nathansobo** [comment]
@amytruong do you think you could investigate this and reproduce it when you get a chance?

**Comment by amytruong** [comment]
@nathansobo sure thing, I'll let you know if I can repro

**Comment by piit79** [comment]
@amytruong Thanks for looking into it. This issue forced me to delete the links temporarily from one project to be able to use atom - otherwise it uses 100% CPU as soon as I hit Ctrl+P / shows infinite number of matches when searching.
I'm on Linux by the way.

**Comment by amytruong** [comment]
@piit79 do you mind clarifying what indexing means? Do you mean when you're in the fuzzy finder and searching for the file? Thank you!

**Comment by piit79** [comment]
@amytruong Yes, it's the fuzzy finder (I didn't know it was called that :). When I open it (using Ctrl+P in Linux) "Reindexing project..." shows above the input box and with the "loop" symlink in the project it never disappears and atom keeps consuming 100% of CPU.

**Comment by amytruong** [comment]
@piit79 Ah, yes, I know what you're talking about. Definitely odd how it's not happening on mac or windows. Thank you for the clarification!

**Comment by piit79** [comment]
@amytruong I just re-tested the issue again. I was wrong in saying that the reindexing will never finish - it just takes a **very** long time in my project with over 6000 files.

If you create a simple directory structure with one file and a symlink loop the issue will be nearly the same on both Linux and Windows (I don't have a Mac to test there):

    a/
    a/b/
    a/b/test.txt
    a/b/l -> ..

(Link on windows created using mklink /d.)

When using fuzzy finder, the file test.txt will be shown 10 times in gradually longer file path (b/test.txt, b/l/test.txt, b/l/l/test.txt etc.) on both Linux and Windows.

When searching for a match in project files, atom will show repeated matches in the same file (again, in gradually longer file path as above). In this case, **Linux** shows 40 results while **Windows** show 63 results.

I still think the tree should be traversed with possible loops in mind and make sure the same paths are not traversed more than once.

**Comment by frenchbread** [comment]
Same happening to me when there are couple of projects added to atom.

**Comment by Zireael07** [comment]
@frenchbread: Are you using symlinks in your projects?

**Comment by frenchbread** [comment]
@Zireael07  No. I used `atom --add ~/<project_path>` to add additional project folders to atom. Indexing finishes fine there is only one project added but stuck when adding more than one.

**Comment by lee-dohm** [comment]
@frenchbread Please file a new Issue. Since the problem you're experiencing doesn't have to do with symlinks, it should be tracked separately.

**Comment by sagarpanchal** [comment]
@piit79 @frenchbread If you're not using fuzzy-finder package, disabling it will make atom usable with recursive symlinks. https://github.com/atom/fuzzy-finder/issues/216
