### ISSUE TITLE
love-ide error

### ISSUE THREAD

**Issue by LeshaInc** [atom/atom#10284]
# love-ide-error
1. I pressed the start button
2. I got error

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Stack Trace

Error running LOVE.

```
At "C:\Program" �� ����� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.


undefined
```

### Commands

```
  2x -1:09.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-solarized-dark-ui",
      "solarized-dark-syntax"
    ],
    "ignoredNames": [
      ".git"
    ],
    "disabledPackages": [
      "love-launcher",
      "love-atom"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 11,
    "tabType": "soft",
    "showInvisibles": true,
    "showIndentGuide": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
atom-solarized-dark-ui, v0.25.0
autocomplete-glsl, v0.2.3
autocomplete-love, v0.2.0
color-picker, v2.0.14
command-executor, v1.2.6
hyperclick, v0.0.35
hyperclick-love, v0.2.0
language-glsl, v2.0.1
language-lua, v0.9.4
linter, v1.11.3
linter-luaparse, v0.2.0
love-ide, v0.6.0
minimap, v4.19.0
status-bar-clock, v2.0.4
tool-bar, v0.1.10

# Dev
No dev packages
```

**Comment by batjko** [comment]
I would strongly recommend opening this issue on the [love-ide package repo](https://github.com/rameshvarun/love-ide/issues) instead.

I don't know that package, but from the report it looks like you have two love-related packages disabled:
![image](https://cloud.githubusercontent.com/assets/7287076/12118426/4441fe18-b3be-11e5-8d08-c5001e1b278b.png)

I assume the main package needs these?

**Comment by mnquintana** [comment]
This issue was moved to rameshvarun/love-ide#10
