### ISSUE TITLE
Atom crashed

### ISSUE THREAD

**Issue by stelek** [atom/atom#10295]
The editor had crashed window appeared. Attached MacOSX process sample.
[Sample of Atom.txt](https://github.com/atom/atom/files/79074/Sample.of.Atom.txt)
Probably very large project. Maybe related to ctags.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by stelek** [comment]
Atom version 1.3.2
OSX 10.11.1
It's not easily reproducible and happens after some time (I'll try to repro with --safe)

**Comment by damieng** [comment]
No more information provided and no reproduction. Closing.
