### ISSUE TITLE
Atom hangs when using tree view if similar filename tab already open

### ISSUE THREAD

**Issue by xiata** [atom/atom#10290]
When working with ansible projects, you end up with a lot of similar filenames nested in various folders with common file names. There appears to be a situation that causes Atom to hang.

### System

- Version: 1.3.2
- OS: OS X 10.11.2
- Occurs with community packages disabled?: YES
- Community packages: 

    - atom-beautify@0.28.19
    - language-actionscript3@0.3.0
    - linter@1.11.3
    - linter-jshint@1.2.2
    - linter-pylint@1.2.0
    - mac-fix-path@0.0.0
    - merge-conflicts@1.3.7
    - minimap@4.19.0
    - tab-control@0.6.8

### Preparation Steps

Make this ansible file/folder structure (each leaf is a filename):

- repos/category/repository/inventory/hosts
- repos/category/repository/roles/role-a/defaults/main.yml
- repos/category/repository/roles/role-a/tasks/main.yml
- repos/category/repository/roles/role-b/subrole-c/defaults/main.yml
- repos/category/repository/roles/role-b/subrole-c/tasks/main.yml

### Steps

1. Open Atom to the `repos` directory
2. Open: repos/category/repository/roles/role-b/subrole-c/tasks/main.yml
3. Open: repos/category/repository/roles/role-b/subrole-c/defaults/main.yml
4. Open: repos/category/repository/roles/role-a/defaults/main.yml

### Expected behavior

Open these files without hanging Atom.

**Comment by pcmaffey** [comment]
Experiencing the same problem.

**Comment by 50Wliu** [comment]
Sorry for the trouble.  This has already been fixed in the 1.4 betas, so if you experience this a lot, you might want to try installing the beta.
