### ISSUE TITLE
Problems with accented characters in syntax highlighting

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#10309]
It looks like we may have a problem with accented characters with syntax highlighting. We have [a report](https://discuss.atom.io/t/accents-breaks-syntax-highlighting/24263/6?u=leedohm) that describes this as being a problem in:
- JS
- HTML
- PHP
- CSS

If this can be verified, we should probably do an audit to ensure that all languages that allow UTF-8 encodings utilize regular expressions that recognize the proper character sets. This especially holds true for text or markup languages like HTML.

/cc @atom/languages

**Comment by 50Wliu** [comment]
I can't reproduce this in a simple HTML or JS document:
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>¡Español!</title>
	</head>
	<body>
		<a href="" class="list-group-item">Administración de clases</a>
	</body>
</html>
```

```js
function áéíóú()
{
	let x = threé;
	var ú = mañana + 3;
}
```

Atom 1.5.0-dev-d855613, non-safe mode, Fizzy syntax.

**Comment by mpepito13** [comment]
I got the same problem with the basic One UI and syntax theme.

[Screenshot](https://www.dropbox.com/s/1upixdj34qtj491/Capture%20d%27%C3%A9cran%202016-02-18%2008.50.32.png?dl=0)

**Comment by simurai** [comment]
I can reproduce @mpepito13's JS example:

```js
class Ecriture {};
class Écriture {};
const très_bien;
```

![screen shot 2016-02-18 at 5 09 24 pm](https://cloud.githubusercontent.com/assets/378023/13137147/67848fe6-d662-11e5-859a-8d27a9e9154a.png)

Looks like accented characters don't get tokenized:

![screen shot 2016-02-18 at 5 12 32 pm](https://cloud.githubusercontent.com/assets/378023/13137258/13e7b466-d663-11e5-949b-862ce2403d99.png)

**Comment by lee-dohm** [comment]
@simurai Could you open an Issue on the [language-javascript package](https://github.com/atom/language-javascript) for that?

**Comment by lee-dohm** [comment]
Basically, this is almost assuredly an issue with various language packages (so long as the languages in question actually support non-7-bit-ASCII characters in their identifiers). I don't think there's anything in the Atom engine itself that prevents syntax highlighting of international character sets.

**Comment by 50Wliu** [comment]
This is the same issue that I believe spell-check is hitting, where `\w`only matches `[A-Za-z0-9_]` and nothing else.

**Comment by simurai** [comment]
Yeah, probably most languages have this issue in some form.. here just a few more:

```css
/* CSS */
.Ecriture {};
.Écriture {};
.très_bien {};
```

![screen shot 2016-02-19 at 8 57 21 am](https://cloud.githubusercontent.com/assets/378023/13162416/2acd039a-d6e8-11e5-9531-106272483fcd.png)

```go
// go
func Ecriture() {}
func Écriture() {}
func très_bien() {}
```

![screen shot 2016-02-19 at 9 03 12 am](https://cloud.githubusercontent.com/assets/378023/13162411/2184bbb6-d6e8-11e5-885d-f9621ae917a9.png)

```c
// c
int Ecriture() {}
int Écriture() {}
int très_bien() {}
```

![screen shot 2016-02-19 at 9 04 37 am](https://cloud.githubusercontent.com/assets/378023/13162408/1bbe4058-d6e8-11e5-9aec-522208bcdd6f.png)

Even here on github.com highlighting breaks.

**Comment by chagara** [comment]
Looks writing the accents works and searching for it also.
