### ISSUE TITLE
Hang when overwriting open file with new file

### ISSUE THREAD

**Issue by Jmaa** [atom/atom#10307]
Atom hangs whenever I try to save to the same location as that of an open file.

**Reproduction Steps:**
1.	Open any file `F`.
2.	Create new file `G`.
3.	Write anything (or nothing) in `G`.
4.	Make sure `F` is one of the open tabs.
5.	Save `G` to same location as `F`.

**Expected Behavior:**

Writing `G` to `F` and closing `F`.

**Observed Behavior:**

Atom hangs indefinitely.

**Atom version:** 1.3.0
**OS and version:** Kubuntu 15.10

**Installed packages:**
├── autocomplete-glsl@0.2.3
├── character-table@0.4.3
├── git-plus@5.5.0
├── hex@0.6.2
├── language-fish-shell@1.0.2
├── language-glsl@2.0.1
├── language-latex@0.6.1
├── language-lua@0.9.4
├── language-x86-64-assembly@2.1.5
├── latex-completions@0.3.0
├── linter@1.11.3
├── linter-lua@1.0.1
├── markdown-format@2.5.1
├── markdown-wiki@0.0.0 **(Personal; issue still arises when disabled)**
├── minimap@4.16.0
├── minimap-git-diff@4.1.8
├── save-session@0.15.7
├── seti-syntax@0.4.1
├── seti-ui@0.8.1
└── sort-lines@0.12.0

**Additional information:**

*	**Problem happens in safe mode**
*	**Problem is consistent**
*	**Problem happens with all files**

**Comment by lee-dohm** [comment]
Pretty sure this is the "same file name in different tabs" bug (https://github.com/atom/atom/pull/9636). It's fixed in the Beta channel.

**Comment by lee-dohm** [comment]
Since the beta has been released as v1.4.0, let us know if this happens again.
