### ISSUE TITLE
high CPU usage with spell checker (Mac)

### ISSUE THREAD

**Issue by lucastan** [atom/atom#10306]
When I open several files with many non-dictionary words (e.g. codewords), the Apple spell checker sucks up a lot of CPU for a long time. This happened quite a number of times for me. I can't send you the files due to sensitivity. 

Is there a way to turn off spell checking? 

![screen shot 2016-01-06 at 11 41 13 pm](https://cloud.githubusercontent.com/assets/742503/12146573/485226ba-b4cf-11e5-9f2d-1babc69868b2.png)

**Comment by nathansobo** [comment]
@maxbrunsfeld is working on fixing this.

**Comment by maxbrunsfeld** [comment]
See https://github.com/atom/node-spellchecker/pull/27 for updates.

**Comment by rcprdf** [comment]
I'm seeing this also. Drained my battery on my brand new macbook pro in 2 hours flat on an airplane - normally I get > 6 hours - mac Activity Monitor said that AppleSpell process was running at > 50% Energy utilization continuously whenever atom is open. Workaround: disabled spell-check package and total Energy utilization dropped to < 10%, battery life went back up to normal. Try it.

**Comment by 50Wliu** [comment]
The referenced pull request has been merged, so I'm closing this.  Expect to see performance improvements in Atom 1.5.0.
