### ISSUE TITLE
Strips script tags from EJS files

### ISSUE THREAD

**Issue by umair321** [atom/atom#10316]
I am working on sails and using ejs template engine. I have home.ejs, style.css and main.js files in my project. In home.ejs I have added some script. 
Now Issue is when I save any file other than home.ejs then It remove all script tags from home,ejs. I am wonder why it is only removing script tags and this problem is only with ejs files.
I am using ubunto 14.2 and atom is up-to-dated on my system.

**Comment by mnquintana** [comment]
What version of Atom are you using? Can you reproduce this in safe mode? (`atom --safe`) Can you post a list of your installed packages? (`apm list --installed`) My guess is that some community package you have installed is stripping script tags from EJS files.

**Comment by umair321** [comment]
I am using latest atom version. same problem is with netbeans. I think this is not IDE problem. 
Sails (nodejs framework) is removing any thing between  and restore to its default tempate's js.

**Comment by mnquintana** [comment]
Ah okay, thanks for the update!
