### ISSUE TITLE
OSX: Crashes when closed as full screen app

### ISSUE THREAD

**Issue by jmeas** [atom/atom#10311]
https://github.com/atom/atom/issues/9584 is once again a problem in 1.3.2. I'm filing a new issue based on https://github.com/atom/atom/issues/9584#issuecomment-167817650

**Operating system**: OSX El Capitan v10.11.2 (15C50)
**Atom**: v1.3.2

**Steps to reproduce:**

1. Open Atom
2. Make it full screen
3. Close Atom by clicking the "x" button in the upper left hand corner of the app, or via cmd+Q
4. Atom should crash. If not, repeat steps 1 through 4 until it does (shouldn't take more than a few tries!)

Crash data [here](https://gist.github.com/jmeas/e52b40212d2b57dcd375)

**Comment by 50Wliu** [comment]
Hi @jmeas, like I said in that issue the fix will not take effect until 1.4, unless it's backported.

**Comment by jmeas** [comment]
Oh, oops. Silly me. For some reason I kept thinking of `1.4` as some past version, rather than the next one.

Sorry for the duplication – and thanks for the quick reply @50Wliu !
