### ISSUE TITLE
Windows: Backslash does not work with Swedish keyboard layout

### ISSUE THREAD

**Issue by LeoToivio** [atom/atom#10317]
I have a problem with the backslash key not working in Windows build 1.3.2 using a Swedish keyboard layout. 

The shortcut I'm using is "**Alt Gr** and **+**"

Cheers!

**Comment by 50Wliu** [comment]
Hi @LeoToivio, Atom currently has problems with international keyboard layouts: please see atom/atom-keymap#35 and atom/atom-keymap#37 for more details and workarounds.
