### ISSUE TITLE
Build issue npm ERR! network read ECONNRESET on Windows 10

### ISSUE THREAD

**Issue by AnAverageHuman** [atom/atom#10329]
I'm getting the following error message while trying to run the build script on Windows 10:

    PS D:\git\atom> .\script\build
    Node: v4.2.4
    npm: v2.13.3
    Python: v2.7.11
    Installing build modules...
    => Took 4388ms.
    
    Installing apm...
    
    
    npm ERR! Windows_NT 10.0.10240
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "D:\\git\\atom\\build\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=D:\\git\\atom\\build\\.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
    npm ERR! node v4.2.4
    npm ERR! npm  v2.13.3
    npm ERR! code ECONNRESET
    npm ERR! errno ECONNRESET
    npm ERR! syscall read
    npm ERR! network read ECONNRESET
    npm ERR! network This is most likely not a problem with npm itself
    npm ERR! network and is related to network connectivity.
    npm ERR! network In most cases you are behind a proxy or have bad network settings.
    npm ERR! network
    npm ERR! network If you are behind a proxy, please make sure that the
    npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

How can I fix this? I am not behind a proxy.

**Comment by joshaber** [comment]
atom.io's having some problems right now. Just try rebuilding.

**Comment by AnAverageHuman** [comment]
Running [`npm config set registry http://registry.npmjs.org/`](http://stackoverflow.com/questions/18419144/npm-not-working-read-econnreset#18428563) seems to have fixed it. The script is now getting further into the build process.

**Comment by lee-dohm** [comment]
Sounds like this has been fixed. If that is not the case, please let us know!
