### ISSUE TITLE
Atom crashes after closing almost every time

### ISSUE THREAD

**Issue by JasonTheAdams** [atom/atom#10323]
Using `Atom 1.3.2` on  `OS X 10.11.2`

Within the last couple months, Atom has started crashing almost every time I close the program. No problems while it's running, but when I close out it appears to close just fine, but then pops up the OS X crash dialog. Here's the output: [AtomCrash.txt](https://github.com/atom/atom/files/81351/AtomCrash.txt)

**Comment by joshaber** [comment]
This is fixed in the 1.4 betas. Sorry for the hassle!
