### ISSUE TITLE
Python formatting of numeric function parameters is inconsistent

### ISSUE THREAD

**Issue by skewty** [atom/atom#10322]
```
data = sock.recv(1024)
sock.recv(1024)
```
without the '=' the number is not colored

**Comment by skewty** [comment]
This bug actually extends to more than numerics.

```
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
x = sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
```

Notice that the SOL_SOCKET and SO_REUSEADDR lose their color when the 1 gets it.

**Comment by mnquintana** [comment]
This issue was moved to atom/language-python#127
