### ISSUE TITLE
Missing commas are not inserted between array or object members

### ISSUE THREAD

**Issue by willnwhite** [atom/atom#10320]
Here's the issue in the wrong package: https://github.com/atom/language-javascript/issues/299

**Comment by lee-dohm** [comment]
It's not clear what you're expecting from the previous Issue. Are you suggesting that Atom should detect and insert missing commas for you when you're just looking at the file? Are you suggesting that Atom should detect and insert missing commas for you while you're typing like some sort of programmatic autocorrect? Or ... ?

**Comment by lee-dohm** [comment]
See the [How Do I Write a (Good) Enhancement Suggestion](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion) section of the CONTRIBUTING guide for suggestions on what sorts of information to include.

**Comment by willnwhite** [comment]
All this has reminded me that there are linters, and now I've installed one. Sorry, I guess I'm still getting the hang of Atom's modularity. I'll raise the issue with the linter.

**Comment by lee-dohm** [comment]
@willnwhite It's quite alright. We're here to help :grinning:
