### ISSUE TITLE
Empty spaces when tab indenting with multiple selection

### ISSUE THREAD

**Issue by ronilaukkarinen** [atom/atom#10321]
I have been having a very annoying problem with Atom.

When I select either with mouse or ctrl+shift+up/down keys like this:

![Screenshot](https://dl.dropboxusercontent.com/u/18447700/Screenshot%202016-01-07%2017.23.46.png "Screenshot")

Then pressing tab to indent, getting broken code:

![Screenshot](https://dl.dropboxusercontent.com/u/18447700/Screenshot%202016-01-07%2017.23.38.png "Screenshot")

**Comment by mnquintana** [comment]
Can you share the file in question? Are you using soft or hard tabs? Can you reproduce this in safe mode? (`atom --safe`)

**Comment by ronilaukkarinen** [comment]
[Link to the file](https://dl.dropboxusercontent.com/u/18447700/webapp2.scss)

It happens in every file, but not all the time. Haven't figured out yet what makes it act like that. I only use tab key in Mac, so I guess soft tabs.

With `atom --safe` it always works.
So it's a package thing then?

**Comment by mnquintana** [comment]
If you aren't having any problems in safe mode, then it seems like it's a community package. (I didn't see anything weird in the file.)

Can you post your list of installed packages? (`apm list --installed`)

**Comment by ronilaukkarinen** [comment]
Here you go:

````
$ apm list --installed
/Users/rolle/.atom/packages (27)
├── activate-power-mode@0.4.1
├── block-cursor@0.13.1
├── cssfmt@1.2.1
├── dark-flat-ui@1.2.4
├── dracula-theme@1.2.0
├── emmet@2.3.17
├── flatland@0.16.0
├── flatland-dark@0.1.6
├── font-awesome-snippetset@0.0.6
├── incremental-search@5.0.1
├── itg-flat-dark@0.2.0
├── itg-flat-flatland-Monokai@0.16.0
├── jsfmt@1.1.2
├── json-colorer@0.3.0
├── language-tcl@0.1.2
├── linter@1.11.3
├── linter-scss-lint@2.5.0
├── minimap@4.19.0
├── minimap-pigments@0.1.7
├── open-recent@4.0.1
├── php-fmt@0.1.2
├── pigments@0.19.5
├── recent-projects@0.9.5
├── set-syntax@0.3.0
├── tasks@2.6.0
├── tree-view-open-files@0.3.0
└── wakatime@5.0.2
````

**Comment by ronilaukkarinen** [comment]
Still haven't figured out which package causes this... Any tips?

**Comment by ronilaukkarinen** [comment]
Cleaned up some useless plugins, it seems **emmet** is to blame. Deactivating it fixes the problem.

````
$ apm list --installed
/Users/rolle/.atom/packages (21)
├── block-cursor@0.13.1
├── cssfmt@1.2.1
├── dark-flat-ui@1.2.4
├── emmet@2.3.17
├── flatland@0.16.0
├── flatland-dark@0.1.6
├── font-awesome-snippetset@0.0.6
├── itg-flat-dark@0.2.0
├── itg-flat-flatland-Monokai@0.16.0
├── jsfmt@1.1.2
├── language-tcl@0.1.2
├── linter@1.11.3
├── linter-scss-lint@2.5.0
├── minimap@4.19.0
├── open-recent@4.0.1
├── pigments@0.19.5
├── recent-projects@0.9.5
├── set-syntax@0.3.0
├── tasks@2.6.0
├── tree-view-open-files@0.3.0
└── wakatime@5.0.2
````
