### ISSUE TITLE
Relocate or rename "Reload" menu item to prevent confusion

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#10331]
See: https://github.com/atom/text-buffer/issues/124

**Comment by joshaber** [comment]
This confused me Back In The Day too :+1: 

Stick it under View => Developer?

**Comment by mnquintana** [comment]
> Stick it under View => Developer?

Makes sense to me :+1: 

Also from https://github.com/atom/text-buffer/issues/124 – we should probably rename the command too, to something like "Reload Window".
