### ISSUE TITLE
No good at supporting Chinese encoded in ANSI

### ISSUE THREAD

**Issue by seajean** [atom/atom#10338]
My Chinese text file was save in ANSI-encoding,when I open it in the editor, it does not showed normally.

**Comment by lee-dohm** [comment]
ANSI-encoding can mean many different things depending on where you're using it. Can you give us more information on exactly what encoding is not working?

**Comment by seajean** [comment]
Here is the file I create with notepad in my Windows 7~
[testFile.txt](https://github.com/atom/atom/files/87239/testFile.txt)

**Comment by seajean** [comment]
This file displayed ok in  EditPlus but not Atom

**Comment by lee-dohm** [comment]
Just having the file doesn't help unless you can tell me what encoding is being used.

@50Wliu do you have any ideas what encoding is used by default on Chinese Windows 7?

**Comment by 50Wliu** [comment]
Unfortunately not, it just works™ for me and I never had to check.

I'll test with the file though and see if I can figure it out.

**Comment by lee-dohm** [comment]
Thank you very much @50Wliu :bow:

**Comment by 50Wliu** [comment]
Encoding Selector's auto-detect tells me that it's encoded as the deprecated `gb2312`.  Makes sense since it's one of China's official character sets.

@seajean Please open up the Encoding Selector (<kbd>Ctrl+Shift+U</kbd>) and choose the first option, `Auto Detect`.

**Comment by seajean** [comment]
It works fine now, thanks~ If  there is a encoding select menu in the toolbar -> view,it will be better.
