### ISSUE TITLE
Atom (still) always opens keymap.cson on startup

### ISSUE THREAD

**Issue by derelk** [atom/atom#10342]
I can consistently reproduce #9155 from scratch. I'm running Atom 1.3.2 on OS X 10.11.2. This happens when run entirely within safe mode as well.
1. Quit Atom
2. `rm -rf ~/.atom/storage/`
3. Launch Atom via `atom --safe`
4. `cmd-,` (does not work the same with Atom > Preferences menu, see below)
5. Click Keybindings in left rail of Settings
6. Click "your keymap file" link in the top help line of the Keybindings page
7. Close `keymap.cson` buffer
8. Quit
9. Relaunch via `atom --safe`.
10. `keymap.cson` is open, and there's no way to fix this without deleting storage or modifying `initialPaths` in `~/.atom/storage/application.json`.

There is also a variant if you use the Atom > Preferences menu in step 4 instead of `cmd-,`, in which the Settings pane is always open on startup instead of keybindings.

**Comment by derelk** [comment]
Reproducible in 1.3.3 as well.

**Comment by 50Wliu** [comment]
Confirmed on Windows 10 x64, Atom 1.5.0-dev-d855613.  Likely related to #10297.
