### ISSUE TITLE
Dragging Icon from the title bar leaves behind glitchy sprite

### ISSUE THREAD

**Issue by rm-code** [atom/atom#10346]
![glitch](https://cloud.githubusercontent.com/assets/11627131/12213034/f23750d0-b671-11e5-9211-793a41669791.gif)

Operating System: OSX 10.11.3
Atom Version: 1.6.0-beta0
Reproducable in safe-mode: Yes

**Comment by mnquintana** [comment]
I can't reproduce this with 1.5.0-dev-6d949d3 on OS X 10.11.2. I suspect that there might be a graphics driver issue here, but I'm not totally sure. Are you on a retina MacBook Pro with a discrete graphics card by any chance?

**Comment by rm-code** [comment]
It's a MacBook Pro (13" Mid 2010) so no retina display. Graphics card is the NVIDIA GeForce 320M 256 MB.

**Comment by rm-code** [comment]
Just a quick update: Still happens in OSX 10.11.3 and Atom 1.6.0 - beta0

**Comment by rm-code** [comment]
Closing this as I can't reproduce it in Atom 1.9.0-beta2 anymore 👍 

![fixed](https://cloud.githubusercontent.com/assets/11627131/17243203/ad79b92a-557b-11e6-8efb-e4af6717f06a.png)
