### ISSUE TITLE
Error parsing array of objects in package settings (config.cson)

### ISSUE THREAD

**Issue by derekderaps** [atom/atom#10345]
The `config.cson` parser seems unable to handle objects within an array. E.g,. take this package settings configuration:

``` coffee
module.exports = MyPackage =
  config:
    MyArrayOfObjects:
      type: 'array'
      default: []
      items:
        type: 'object'
        properties:
          myObjectProperty:
            type: 'string'
```

The following  `config.cson` values get removed on parse:

``` cson
"my-module":
  MyArrayOfObjects: [
    {
      myObjectProperty: "I am a setting value"
    }
    {
      myObjectProperty: "I am a another setting value"
    }
  ]
```

**Comment by asopin** [comment]
I faced the same problem when trying to configure php-debug remote. PathMaps part doesn't get saved.

Is there any workaround for this issue?
