### ISSUE TITLE
How to start a file from command line?

### ISSUE THREAD

**Issue by xDinomode** [atom/atom#10353]
Hey! I need to be able to open files from the command line instead of opening atom and selecting open folder because time. Obviously this sounds easy just run atom filename, but that doesn't work. For some strange reason neither apm or atom installed to to the command line. 

Okay so my option should be to add atom.exe to the global path variable right? So I currently have an atom.exe shortcut on the desktop. When I check where it's located in I get "C:\Users\xDinomode\AppData\Local\atom\app-1.3.2".

Inside of local/atom are three folders:
app-1.3.1
app-1.3.2
app-1.3.3

WHAT?! Which one do I choose.

**Comment by pedro93** [comment]
Im assuming this, somone correct me but each folder correspond to the Atom version. That being said try the folder app-1.3.3 it should be the latest atom version you have

**Comment by xDinomode** [comment]
@pedro93 Yup that was it. Works now thank you.
