### ISSUE TITLE
Can't get Atom pass through a firewall

### ISSUE THREAD

**Issue by turbodude** [atom/atom#10357]
Hi! I'm on Windows 7 x64 and I have Comodo Firewall installed. I tried everything: creating special rules for atom.exe, disabling the firewall completely, disable additional features such as IPv6 filtering and blocking of fragmented IP traffic, I'm still getting this error message in Atom regardless:
Request for package information failed: connect EACCES

**Comment by mnquintana** [comment]
> disabling the firewall completely

Hmmm that's strange that this didn't do anything. So you're getting this error when trying to load package information in Atom itself? Could you paste the full error?

**Comment by turbodude** [comment]
"Fetching outdated packages and themes failed. Request for package information failed: connect EACCES"
This is the message that appears in the "Updates" tab within the program.

The message "Fetching featured packages failed. connect EACCES" appears in the "Install" tab. I already installed a package or two from that tab before when I had another firewall installed. It was Tinywall by the way, and disabling it actually helped Atom access the Internet, although creating an exception still did not give any results, just like now with Comodo. Many other software gets whitelisted/exceptioned just fine for me, this is the first time when a program behaves like this; it's like Atom is using some unusual way to access the Internet or something.

**Comment by lee-dohm** [comment]
Atom doesn't do the installing of packages itself. It uses apm and npm to do the heavy lifting. So perhaps your firewalls need exceptions for them as well?

**Comment by turbodude** [comment]
Then it would be great to know which files exactly are being used by Atom for downloading. But it's still hard to understand why a firewall doesn't detect any connection attempts for something other than atom.exe. That is actually the reason why I switched to Comodo, because it pops up a dialog box each time something is trying to access the Internet and there are no rules previously set for that something.

**Comment by turbodude** [comment]
OK, I resolved the issue by adding node.exe (AppData\Local\atom\app-1.4.0\resources\app\apm\bin\node.exe) to the firewall exceptions. And actually that is the only file that requires the network access, not even atom.exe, despite the fact that it gets detected by a firewall trying to access the internet. Go figure...
