### ISSUE TITLE
PackageManager.disablePackage() does not check if a package is already disabled

### ISSUE THREAD

**Issue by burodepeper** [atom/atom#10358]
See https://github.com/burodepeper/language-markdown/issues/70

I assumed `atom.packages.disablePackage()` would do this for me, but it didn't, and now I've polluted a whole bunch of people's configs with duplicates... :oopsie:

**Comment by mnquintana** [comment]
Confirmed on Atom 1.5.0-dev-6d949d3

**Comment by burodepeper** [comment]
Thanks for picking this up so quickly!
Is there an easy way to remove all the duplicate entries (although I assume they're harmless) without enabling a package and then disabling it again...
