### ISSUE TITLE
I can't install or update any packages

### ISSUE THREAD

**Issue by Bantes** [atom/atom#10368]
My internet is working properly.
But when i install package or update it,atom will talk me 'Updating to XXX failed'.
It's output like this:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz
gyp WARN install got an error, rolling back install
gyp
```
```
C:\Users\Administrator>apm -v
apm  1.4.1
npm  2.13.3
node 0.10.40
python
git 2.6.4.windows.1
visual studio
```

So, i set my vpn link to Dallas,Tokyo and Melbourne,but it still can't work...
I can open 'https://atom.io/download/atom-shell/v0.34.3/node-v0.34.3.tar.gz' and download it,but atom can't open it,i don't konw what's wrong with atom.

**Comment by angel1a** [comment]
I have the same trouble.
It seems that vpn isn't valid in the terminal and I used the proxychains to fix it.
Maybe this is helpful: https://atom-china.org/t/atom/797

**Comment by lee-dohm** [comment]
It looks like it can't find the native compile tools and you're trying to update a package that uses a native compilation component. You may want to try installing the requirements listed here:

https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md

**Comment by puranjayjain** [comment]
The following tasks resolved my issue:
1. Close atom
2. Update [node](https://nodejs.org/en/) to the latest **stable** version
2. npm rebuild
3. Open atom and try again it will work had the same issue yesterday

**Comment by darkmorpher** [comment]
CC @damieng Tag `Windows` and close :dango:
