### ISSUE TITLE
"sudo atom" does nothing

### ISSUE THREAD

**Issue by TheSHEEEP** [atom/atom#10360]
I can launch atom normally without sudo, but as soon as I need root privileges, the program simply won't start, and no error is shown.
Adding the "-f" flag also shows no additional output.

I am using openSUSE 42.1.

**Comment by mnquintana** [comment]
What version of Atom are you using? Did you install it from one of the official release downloads on https://atom.io?

**Comment by TheSHEEEP** [comment]
The very latest from atom.io, yes.

**Comment by mnquintana** [comment]
What version number?

**Comment by TheSHEEEP** [comment]
It is from today, so 1.3.3 for sure (switched machines in the meantime, so I can't take a look right now).

**Comment by alexandernst** [comment]
I'm surprised this worked before. Using `sudo` (not `kdesu` or `gnome-su`, but `sudo`) shouldn't work on any graphical app as it won't use the X server session of your user.

**Comment by TheSHEEEP** [comment]
Well, to be honest, this is the first time I tried openSUSE with the KDE desktop, so maybe it never DID work (as it could not).

**Comment by alexandernst** [comment]
Go try with `kdesu` (or `kdesudo`, depending of the KDE version)

**Comment by flotzilla** [comment]
Well, I'm tried to run atom-beta(1.4.0-beta3) on openSUSE 42.1, i have this messages:
`sudo atom-beta-f`
`[17689:0110/224202:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[17689:0110/224202:ERROR:browser_main_loop.cc(237)] Gtk: cannot open display: `

**Comment by alexandernst** [comment]
`Gtk: cannot open display:`
That is exactly what I was meaning. You can't run a graphical app with `sudo` because it won't use your X server session. And I'd be really surprised that running `sudo atom` would have ever worked, not without your distro patching `sudo` in some way.

**Comment by flotzilla** [comment]
Don't know about `kdesu` command. Thanks.
But still does not display any errors.

**Comment by alexandernst** [comment]
What about `kdesudo`? Also, what do you mean by "still does not display any errors"? Is it working?

**Comment by TheSHEEEP** [comment]
Okay, I tried it with kdesu.

So `kdesu atom` shows exactly the same behavior: Nothing, not even an error message.
However this typo of mine `kdesu atom -f somefile` DOES launch atom with the last open files.
My typo here is that `-f .` is interpreted as a flag for kdesu, not atom.

A command that finally launches atom with the desired file is `kdesu -c "atom -f somefile"`.
Needless to say, this is bothersome as hell, but likely not fixable by atom.

I'm pretty sure I'll switch to another desktop that will work just fine with sudo only...

**Comment by alexandernst** [comment]
Sure. Atom can't fix that, it's not a bug either. It's how `sudo` works.

@mnquintana Please close this issue.

**Comment by othpiik** [comment]
Atom 1.6 not even work with supper user access via common line in terminal

 
`# atom`
to run atom atom editor with normal user in terminal common line it's work!

but it doesn't work with superuser (su) access
```
# su -
# atom
```
------- OR --------
`# sudo atom`

atom can be very powerful if it's work with SU in linux desktop

I'm ever trying atom in Fedora 23, OpenSUSE leap and Archlinux  got same result and confirm it doesn't work with SuperUser Access in Linux

**Comment by arlyoneel** [comment]
This works in previous version with kdesu and sudo, now both are not working, with sudo works at least in manjaro idk in other distros.

I know the behavior of sudo, but in manjaro behaves different.

e.g: sudo kate works perfect.

Manjaro up to date + Plasma

no error no nothing.

**Comment by pabloab** [comment]
Probably `sudo kate` [will stop working perfectly](https://blog.martin-graesslin.com/blog/2017/02/editing-files-as-root/):

> Today I pushed a change for Kate and KWrite which does no longer allow to be run as root. Instead it educates the user about how to do the same with **`sudoedit`**.
