### ISSUE TITLE
Atom editor is not working.

### ISSUE THREAD

**Issue by ejlocop** [atom/atom#10369]
hi guys. iv'e been wondering what the hell happened to my atom editor? :smiling_imp: 
i tried reinstalling the software but still the same. 
any atom user experienced this too ?
![image](https://cloud.githubusercontent.com/assets/12082880/12228713/52b14aec-b87a-11e5-8541-ee932d29756c.png)

![image](https://cloud.githubusercontent.com/assets/12082880/12228723/6c1d6c04-b87a-11e5-9737-c7a368c12ca9.png)

**Comment by ejlocop** [comment]
looks like my google chrome browser

**Comment by 50Wliu** [comment]
Hi @ejlocop, please click the red x with the `1` right next to it and paste the error here  Thanks!

**Comment by ejlocop** [comment]
![image](https://cloud.githubusercontent.com/assets/12082880/12256127/f03613fe-b935-11e5-86ba-ec342de8d02b.png)

heres the error. 
now i checked the file-system-blob.js but theres nothing in my directory.
seems like a virus or something deleted it. weird.
btw heres C:\Users\Ling\AppData\Local\atom\app-1.3.3\ contains
![image](https://cloud.githubusercontent.com/assets/12082880/12256302/333a61c2-b937-11e5-8890-3aeeab3aa33a.png)

**Comment by lee-dohm** [comment]
> seems like a virus or something deleted it. weird.

Nothing deleted it. Atom stores its application files in a file called `app.asar` that it virtualizes directories and flies out of.

What you need to do is:

1. Completely exit all instances of Atom
1. Delete the `C:\Users\Ling\.atom\blob-store` directory
1. Launch Atom again

**Comment by ejlocop** [comment]
oh my. thanks mate. :) its working now

**Comment by lee-dohm** [comment]
Glad to hear it! Thanks for the update :grinning:
