### ISSUE TITLE
How to run a shell command in atom without a package 

### ISSUE THREAD

**Issue by Huaraz2** [atom/atom#10376]
Hi,
I love atom and I use the package 'Script' to run my code normally, but I am currently writing a feature for a package and I need to run a shell command and I am not sure how to do this in atom without the 'Script' package.  Any help would be greatly appreciated.

Thanks :smiling_imp:

**Comment by mnquintana** [comment]
Atom packages are also standard node packages, so you can do anything you would normally do in Node in an Atom package (like [spawning a child process](http://devdocs.io/node_lts/child_process#child_process_child_process_spawn_command_args_options)). (You can also make use of Atom's built-in [BufferedProcess API](https://atom.io/docs/api/v1.3.3/BufferedProcess) instead.)

For future reference though, you'll have better luck asking this kind of question on [Discuss](discuss.atom.io) or Slack instead.
