### ISSUE TITLE
GitRepository::relativize() is broken for submodules

### ISSUE THREAD

**Issue by kankaristo** [atom/atom#10373]
`GitRepository::relativize()` returns the wrong relative path for submodules.

Let's say I have a project, where the root directory is a Git repository and there's a submodule at `<root>/subdir/`.

I get the submodule's `GitRepository` with something like:

``` coffee
# Get main repo (assume [0] is the correct one)
repo = atom.project.getRepositories()[0]

# Get repo for a file in the submodule
subRepo = repo.getRepo("<root>/subdir/file.txt")
```

And then I try to get the relative path to a file within the submodule:

``` coffee
# Run relativize() on the submodule's GitRepository
relativePath = subRepo.relativize("<root>/subdir/file.txt")
```

The above returns `subdir/file.txt` when it [should](https://atom.io/docs/api/v1.3.3/GitRepository#instance-relativize) return `file.txt`, because the working directory for `subRepo` is `<root>/subdir/`.

Is this by design? It breaks quite a few packages that use Git in some way (they work fine for the main repo, but break for files in submodules).

I noticed that `GitRepository::getRepo()` is private (although used in a few packages). Is there some other way to get a relative path to a file from the root of its Git repository (i.e. a submodule, if the file is in one)?

**Comment by joshaber** [comment]
That *sounds* like a bug to me too.

https://github.com/atom/atom/pull/9213 is close to landing and will be the recommended path forward for Git packages. I'd be curious to know if it has the same bug.

**Comment by kankaristo** [comment]
A couple of packages that are broken for submodules because of `relativize()`, and are fixed by using something else:
https://github.com/littlebee/git-time-machine/issues/3
https://github.com/jakesankey/line-diff-details/issues/12

So if this isn't a bug (and works this way by design), there should probably be something that gives a path relative to the submodule's root. There should also be a mention in the docs for `relativize()`, since it doesn't really work as advertised.
