### ISSUE TITLE
core:select-down can skip lines

### ISSUE THREAD

**Issue by WalterGR** [atom/atom#10386]
Atom 1.3.2 on OS X 10.10.5.

This behavior is asymmetric with core:select-up.

Repro:

1.  Enter text such as the following.  The numbers and pipes shouldn't be typed and simply indicate the line number and the edge of the editor.  Lines 1 and 4 are empty.

        1|
        2|;; The optional step argument determines how far `partition` moves down the ...
        3|;; next chunk.  If not specified, `step` defaults to `size`.
        4|
        5|(partition 2 1 [1 2 3 4 5])

2.  Position the cursor on line 2 somewhere to the right of the first column, say - between the "e" and "n" of "argument".

3.  Press Up Arrow.

4.  Press Shift + Down Arrow.  Text through "argum" in line 2 is selected.

5.  Press Shift + Down Arrow.  Text through "not spec" in line 3 is selected.

6.  Press Shift + Down Arrow.

7.  Press Shift + Down Arrow.

Expected:

Step 6 selects text "through line 4", meaning that it selects from where the cursor was on step 2, through all of the contents of line 3, and including the newline at the end of line 3.

Step 7 selects text through the end of line 5.

Actual:

Step 6 selects through the end of line 3.  The difference from "Expected" is that the newline at the end of line 3 isn't selected.

Step 7 completely skips like 4 and selects through the end of line 5.

This animated GIF shows the above repro steps and the result:

![2016-01-11-atom-shift-down-can-skip-lines](https://cloud.githubusercontent.com/assets/380880/12256636/9c2b1322-b8b3-11e5-880c-41b2bfb63e23.gif)

**Comment by lee-dohm** [comment]
> The difference from "Expected" is that the newline at the end of line 3 isn't selected.

I believe you mean the end of line 4? I would argue that this is the expected behavior. You'll note that it didn't select the newline at the end of line 3 either because you're selecting only part way through the line each time.

**Comment by WalterGR** [comment]
> > The difference from "Expected" is that the newline at the end of line 3 isn't selected.
> I believe you mean the end of line 4?

No.

> I would argue that this is the expected behavior. You'll note that it didn't select the newline at the end of line 3 either because you're selecting only part way through the line each time.

I think you're mis-counting.

Shift-Down in step 4 selects line 1, the endline, and part of the way through line 2.

Shift-Down in step 5 selects line 1, the endline, line 2, the endline, and part of the way through line 3.

Shift-Down in step 6  selects line 1, the endline, line 2, the endline, and all of line 3 but no endline.

That's inconsistent, yes?

**Comment by WalterGR** [comment]
Here it is in table form.  The cell contents indicate the contents of the selection.

Step | Actual result | Expected result 
----------- | ----------- | -------------
4 | line 1, the endline, and part of the way through line **2**. | line 1, the endline, and part of the way through line **2**.
5 | line 1, the endline, line 2, the endline, and part of the way through line **3**. | line 1, the endline, line 2, the endline, and part of the way through line **3**.
6 | line 1, the endline, line 2, the endline, and all of line **3** but no endline. | line 1, the endline, line 2, the endline, line 3, the endline, and line **4**
7 | line 1, the endline, line 2, the endline, line 3, the endline, line 4, the endline, and line **5** | line 1, the endline, line 2, the endline, line 3, the endline, line 4, the endline, and line **5**

The full extent of the selection is indicated by the bold line numbers.

It is expected that Shift-Down grows the selection by one line every time it is pressed.

The expected pattern is 2, 3, 4, 5.  The actual pattern is 2, 3, 3, 5.

**Comment by WalterGR** [comment]
Here is Sublime Text showing the expected behavior.  The selection is grown by one line every time Shift-Down is pressed.  Line 4 is not skipped.

![2016-01-12-sublime-text-demonstrating-proper-shift-down-behavior](https://cloud.githubusercontent.com/assets/380880/12279081/db4c295c-b939-11e5-8b2b-b5ff1cfb82c8.gif)

**Comment by lee-dohm** [comment]
The only difference I see here is that Sublime Text's cursor is visible while selecting showing specifically where the selection is. Can you copy-paste what is selected each time or use the JavaScript Console to prove that the end of the selection is misaligned?

**Comment by WalterGR** [comment]
> The only difference I see here is that Sublime Text's cursor is visible while selecting showing specifically where the selection is. 

The screenshot of Atom also shows specifically where the selection is.

> Can you copy-paste what is selected each time or use the JavaScript Console to prove that the end of the selection is misaligned?

I did that before I created this ticket.

Are you finding that it doesn't repro?

**Comment by WalterGR** [comment]
(Added Atom and OS X versions to description.)

**Comment by WalterGR** [comment]
Confirmed that this still repros in 1.3.3 in safe mode with a fresh profile.

**Comment by IshmaelYavitz** [comment]
No longer repros in 1.7.2.

**Comment by Zireael07** [comment]
@WalterGR: Can you update? Atom is at 1.7.x now!

**Comment by WalterGR** [comment]
I can no longer reproduce this issue.

(The UI still makes it _appear_ that the line is being skipped, which is bad.  But it's not skipped in actuality, which I tested by copying and pasting, as I did when I opened the ticket.)
