### ISSUE TITLE
Sometimes when starting ATOM, cpu usage spikes, clicking on the status icon (octocat spinner) shows its processing 2000+ editText requests

### ISSUE THREAD

**Issue by DanielJoyce** [atom/atom#10381]
Eventually if I let it sit, it will successfully process all 6000+ requests. But this takes several minutes.If I  exit atom before it finishes I see two node processes still running, both taking 100% cpu.

**Comment by DanielJoyce** [comment]
Apparently this relates to code highlighting. When I open a typescript file, the spinner appears and cpu usage spikes until the syntax coloring completes.

I have atom-typescript installed.

Atom 1.3.2
atom-typescript 7.16.1

**Comment by lee-dohm** [comment]
Can you reproduce this in Safe Mode?

To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by DanielJoyce** [comment]
Appears to be a problem with a plugin.
