### ISSUE TITLE
Double click in any line of the "Project Find Results", Atom stop responding

### ISSUE THREAD

**Issue by alenwesker** [atom/atom#10389]
Simple to recreate the bug environment: open a large lua project, Ctrl + Shift + F, found some keyword,  
then the "Project Find Results" appears, double click one result, then stop responding.

Atom Version: 1.3.2

Contact me: alenwesker@gmail.com

If you guys can't let the problem reappear, just send me some link about how to debug atom, and I will try to figure it out myself. 

It's really low grade a problem, and it's annoying

**Comment by 50Wliu** [comment]
Someone else reported this and I believe updating to the 1.4 betas fixed it.  You can also try updating to 1.3.3 which contains some important bugfixes.

If neither of those fix it, please comment here and I'll reopen this issue.
