### ISSUE TITLE
Atom's Documentation Does Not Tell the End User dpkg Requires Git to be Installed

### ISSUE THREAD

**Issue by Wasserschlange** [atom/atom#10388]
I recieved this error while installing atom via dpkg: 
```bash
$ sudo dpkg --install atom-amd64.deb
[sudo] password for mhiiva: 
Selecting previously unselected package atom.
(Reading database ... 160643 files and directories currently installed.)
Preparing to unpack atom-amd64.deb ...
Unpacking atom (1.3.3) ...
dpkg: dependency problems prevent configuration of atom:
 atom depends on git; however:
  Package git is not installed.

dpkg: error processing package atom (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Errors were encountered while processing:
 atom
```
I have looked over the [Atom on Linux](https://atom.io/docs/v0.194.0/getting-started-installing-atom#atom-on-linux) and the [README](https://github.com/atom/atom/blob/master/README.md), and I found no mention of git being a requirement for atom to be installed. Could this be mentioned in the [README](https://github.com/atom/atom/blob/master/README.md) and [Getting Started Docs](https://atom.io/docs/v0.194.0/getting-started-installing-atom)?

**Comment by knightzac19** [comment]
Honestly, with the debian route, someone just has to run apt-get install -f and it will install any missing dependencies for atom. Also, if someone opens the deb file up using a package manager tool, it'll handle all that automatically.

As far as the yum route goes, if someone uses yum localinstall atom-amd64.rpm, it'll also download any dependencies itself.

**Comment by RishiKulshreshtha** [comment]
After getting the same error, I've done the following steps:
- `sudo apt-get install -f`
- `sudo dpkg -i atom-amd64.deb`

I'm using `Ubuntu 14.04.3 LTS`
