### ISSUE TITLE
Theme not changing

### ISSUE THREAD

**Issue by mingzx** [atom/atom#10382]
OS: Manjaro Linux
Atom version:1.3.3

I use the  Source code (tar.gz) to install. In Atom Setting can't change ui theme and syntax theme. The default theme is one dark.if I change the ui theme or syntax theme,the theme will become atom-dark theme. At the moment, I cannot choose other theme.

**Comment by lee-dohm** [comment]
You may want to take a look at this topic on [Discuss, the official Atom discussion forum](https://discuss.atom.io):

https://discuss.atom.io/t/solved-atom-cannot-change-to-any-theme-other-than-one-dark/24360

**Comment by mingzx** [comment]
I solved this problem. Edit the config.cson , such as:

/*other setting*/
..........
core:
    themes: [
      "seti-ui"
      "seti-syntax"
    ]
......

/*other setting*/

**Comment by lee-dohm** [comment]
Is everything working for you now?

**Comment by mingzx** [comment]
Yes. Thanks you! @lee-dohm .

**Comment by lee-dohm** [comment]
Great! Thanks for getting back to me :grinning:
