### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by Eqistyre** [atom/atom#10387]
when I open my file with atom 1.3.3, it will appear the editor has crashed and give me three choose(keep it open, Reload, close window),but these buttons are not used.and then the choose open with atom 1.3.3 will disappear until i restart my computer, I can open my file with atom 1.3.2. My system is OS X EI Capitan 10.11.2.😃

**Comment by lee-dohm** [comment]
Can you share any information about the file? The size? The number of lines? Is it minified JS or CSS?

Without more information, I can't reproduce the issue.

**Comment by Eqistyre** [comment]
Thank you for your reply

It's a markdown file, just a very little file.

<img width="554" alt="2016-01-13 08 43 36" src="https://cloud.githubusercontent.com/assets/11780948/12281518/c53a7568-b9d1-11e5-9193-323406e1485e.png">

When I click Atom(1.3.3).it will appear

<img width="804" alt="2016-01-13 08 45 23" src="https://cloud.githubusercontent.com/assets/11780948/12281552/18e36b2a-b9d2-11e5-8b9d-00fc32c42711.png">

And the button sometimes are not used.

Sometimes After I use Command + Q quit Atom, it will change like it.

<img width="654" alt="2016-01-13 08 47 44" src="https://cloud.githubusercontent.com/assets/11780948/12281603/9c21bc3a-b9d2-11e5-90f8-08ba83a6a410.png">

The Atom(1.3.3) disappear , but it will appear again after I restart my computer.

**Comment by lee-dohm** [comment]
How did you install Atom?

**Comment by Eqistyre** [comment]
Receive from my friends, maybe there is a problem? maybe one month ago I download Atom from https://atom.io ,but the Atom can't install, so I ask my friend how to resolve it, and I keep screenshot that day.But it also can't install, Then I find the reason maybe is signature does not match.So I click the (?) button and solve this problem.

![cd muifuj6g_ ks626gvm1](https://cloud.githubusercontent.com/assets/11780948/12282136/b8b04d7c-b9d6-11e5-8f78-0cc04e83b169.jpg)

enum, the words means the file is broken, you should put them into the recycle bin.

**Comment by lee-dohm** [comment]
That's a very weird message. I'd recommend uninstalling all copies of Atom
and download from https://atom.io directly.

**Comment by Eqistyre** [comment]
Yeah, it's okay now,  everything just works, there is no warning recommend the file is broken. Thanks for your help

**Comment by mnquintana** [comment]
Thanks for the update @Eqistyre! Sorry to hear about your troubles there, but I'm glad everything's resolved now.
