### ISSUE TITLE
Package install error

### ISSUE THREAD

**Issue by Nageshwari-p** [atom/atom#10385]
Hi 

I am using atom editor on window 7., when I'm trying to install packages following error is showing .

please help me in this .

![atom](https://cloud.githubusercontent.com/assets/12082803/12255765/55f508ee-b91d-11e5-9042-58ed9e528a4e.png)

**Comment by lee-dohm** [comment]
How did you install Atom? Have you tried using Safe Mode?

To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by Nageshwari-p** [comment]
thanks for helping its working :)

**Comment by 50Wliu** [comment]
Awesome!
