### ISSUE TITLE
Atom crashes on startup

### ISSUE THREAD

**Issue by RohitKharsan** [atom/atom#10393]
I am using Atom on Windows 8.1. After reinstalling Windows a few days ago, I decided to install Atom again (This was also happening previously). It worked fine for a few days. But after starting Atom today, I got this:
![capture](https://cloud.githubusercontent.com/assets/12206982/12261569/dab093d0-b947-11e5-863f-5f696b423b08.PNG)

Renaming `.atom` fixes the issue.

**Comment by vadymshymko** [comment]
i have this problem too (windows 10)

**Comment by 50Wliu** [comment]
Please remove the `~/.atom/blob-store` folder and try again.  Thanks!
