### ISSUE TITLE
Atom crashes on startup, reinstalling and deleting user data doesn't help

### ISSUE THREAD

**Issue by beholdnec** [atom/atom#10397]
I am trying to use Atom 1.3.3 on Windows 10 Pro 64-bit. Previous versions of Atom worked until around version 1.3.2 when it started crashing.

I tried deleting all the user data I could find. I deleted these folders specifically: [user]\AppData\Local\atom, [user]\AppData\Roaming\Atom, and [user] \ .atom. (If there are any others, please let me know!)

I uninstall, delete all data, and reinstall the latest version. When I start Atom for the first time, it shows a window with three tabs: "untitled", "Welcome" and "Welcome Guide". The Welcome Guide is open and shows normal contents. Immediately, a crash dialog appears saying "The editor has crashed, Please report..." and no further details.

I have three options. "Close Window" quits. "Reload" makes Atom crash again. "Keep It Open" makes the window blank.

When the window is blank, most options are unresponsive. Trying to "Open in Dev Mode" makes Atom crash in the same way.

The Bug Reporting Guide says to attach a crash report with a stack trace, but I cannot for the life of me find it on my system. If Atom makes a crash report, where does it go? This is especially strange because atom/CONTRIBUTING gives instructions for Mac but no other platforms.

Opening in safe mode doesn't help.
Adding a firewall exception doesn't help.
Rebooting doesn't help. (issue #9985)
No blob-store folder is ever created. (issue #10015)

Atom is completely unusable.

**Comment by jhuvi** [comment]
Same thing with OS X 10.10.5 and Console.app does't show any Atom related log. Only thing I can find is: "Atom: App load time: 479ms", but nothing under User Diagnostic Reports.

**Comment by ijgithub** [comment]
Hi all,
Atom crashed for me yesterday at the end of working hours. This morning its still crashing. See screenshot below for details. I get that window every time I start atom.

![atomcrash](https://cloud.githubusercontent.com/assets/5399739/12288539/7b0a6a6c-b9d5-11e5-9917-d6170d7ceece.png)

I tried reinstalling, deleting AppData\Local\atom but none worked.

**Comment by 50Wliu** [comment]
@ijgithub Your issue is unrelated and is solved by deleting the `~/.atom/blob-store` folder as you discovered.

**Comment by ijgithub** [comment]
@50Wliu Thank you for the information. This will be helpful in the future if the same happens.

**Comment by hairyhenderson** [comment]
I'm seeing this too (OS X 10.11.2). It's giving me a crash report though. Here's part of it that _may_ be relevant:

```
...

Crashed Thread:        32  com.apple.NSURLConnectionLoader

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Global Trace Buffer (reverse chronological seconds):
0.360039     libsystem_trace.dylib     	0x00007fff9c46d0fa dyld_image_header_containing_address(0x700000ec01d0) failed
0.362816     CFNetwork                 	0x00007fff93d4c21a Creating default cookie storage with process/bundle identifier
0.362816     CFNetwork                 	0x00007fff93d4c1b2 Faulting in CFHTTPCookieStorage singleton
0.362820     CFNetwork                 	0x00007fff93d4c041 Faulting in NSHTTPCookieStorage singleton
...
```

I'm not sure if this is an appropriate place to paste the whole thing, or even if the crash report is useful...

**Comment by beholdnec** [comment]
As I said, the problem occurs on Windows (it is not exclusive to Mac) and there is no way to access the devtools.

I found crash dumps in "[user]\Local\Temp\Atom Crashes", perhaps this should be noted in contributing.md. There are no stack traces; when Atom crashes, it generates a .dmp file and a text file with the contents:
```_companyName:GitHub
_productName:Atom
_version:1.3.3
platform:win32
process_type:renderer
prod:Electron
ptime:2272
rept:electron-crash-service
ver:0.34.5```

Would it help if I uploaded one of these .dmp files somewhere? They are about 230 K in size.

**Comment by beholdnec** [comment]
This issue is fixed (for me, at least) in v1.4.0, thanks!

**Comment by gaurav21r** [comment]
I'm on Win10 Atom 1.5 and 1.6beta4 Both are crashing for me! Please reopen!

**Comment by MitsuGM** [comment]
Maybe I'm wrong, but, Atom doest not crashes until installed Power Mode. W7 64 bits.

**Comment by lukehsiao** [comment]
I'm getting this crashing behavior on Windows 10 as of this morning.

**Comment by 50Wliu** [comment]
@lukehsiao Please open a new issue.

**Comment by lukehsiao** [comment]
@50Wliu Resolved. It turns out there was a file someone added to my project overnight that ended in a period (e.g. `filename.`). This was causing one of the other packages I had installed to crash (though I didn't identify exactly which one). Won't open another issue as this seems like a specific case to me, but in case someone happens across this thread with the same issue, I'll leave it here. Simply fixing that file name solved my problem.

**Comment by ph-poppe** [comment]
same issue for me. windows 10; atom is not usable anymore, even after full reinstall.
looking forward to fix

**Comment by MaximilianLloyd** [comment]
same here. Can not use atom anymore.

**Comment by 50Wliu** [comment]
@MaximilianLloyd Please open a new issue.

**Comment by JuanSomniis** [comment]
+1

**Comment by pwolter** [comment]
I just found that when Box sync is running (it takes centuries to sync files and eats almost 70% of the resources) Atom fails to load. When box is done it starts without any problem. So this may be a resources issue or Atom needs to speak with someone over the network connection in order to start (failing when the connection is 100% busy as it is the case when box sync is running). Either way an ugly bug. More concerning the fact that it needs for network connection in order to boot.

**Comment by cemsbr** [comment]
It is happening to me with version 1.11.2. Deleting `~/.atom/blob-store` folder as said by @50Wliu didn't help. I had to delete `~/.atom` entirely and lose all plugins and settings. I have a backup of the broken folder in case there is a way to investigate it further.

**Comment by 50Wliu** [comment]
@cemsbr Please open a new issue.
