### ISSUE TITLE
Sudden onset of poor performance: profiler shows time spent in channel.onread

### ISSUE THREAD

**Issue by pwaller** [atom/atom#10394]
I've been using Atom for a while now and generally haven't had any problems. But today it just became unusable. I don't have any explanation for why it became unusable today, since I haven't upgraded anything.

Any keypress can freeze the editor for several seconds, though sometimes it's possible to get off a volley of code before it stops working again. But essentially it's impossible to use.

It pegs the CPU at 100%. As an aside, the internet performance has been bad today in general (high ping and dropped packets), but I don't have any evidence or reason to believe this is related.

Conditions reproduced in:

* Editing Go code, dockerfiles and plain text files
* The general editor with no files open (browsing the settings and the Ctrl-P menu)
* 1.1.0, Linux amd64 Ubuntu 15.10, Intel graphics.
* 1.3.3, same.
* 1.3.3 Safe mode, same.

A profile shows all of the time being spent in channel.onread (I couldn't find any reference to this in the issue tracker)

![screenshot from 2016-01-12 16-01-48](https://cloud.githubusercontent.com/assets/438648/12268723/d96d4470-b945-11e5-9a45-389f74d06dac.png)

![screenshot from 2016-01-12 16-04-10](https://cloud.githubusercontent.com/assets/438648/12268788/2431baa4-b946-11e5-91b2-0b4c956bbb2c.png)

**Comment by pwaller** [comment]
Today I cannot immediately reproduce this. The next thing I'll do if it does it again is move my `.atom` directory out of the way.

**Comment by pwaller** [comment]
Could this have been https://github.com/atom/atom/issues/6437 ? I suspect so, I just discovered my $HOME was accidentally a git repository.

Closing for now.

**Comment by joshaber** [comment]
Yup, definitely could be!
