### ISSUE TITLE
Shortcut to toggle developer tools inserts character ı in TextEditor.

### ISSUE THREAD

**Issue by hedefalk** [atom/atom#10391]
https://discuss.atom.io/t/toogle-dev-tools-shortcut-lately-inserts-i/23118/3

Discussion seems to indicate that this is fixed but I still have this issue in 1.3.3. on OS X with Swedish keyboard.

**Comment by 50Wliu** [comment]
@hedefalk Could you please try updating to the 1.4 betas?

**Comment by damieng** [comment]
No response, closing.

**Comment by hedefalk** [comment]
This has been fixed so closing is fine.
