### ISSUE TITLE
Why doesn't atom delete files?

### ISSUE THREAD

**Issue by xDinomode** [atom/atom#10402]
Every time I need to delete a file I have to use a terminal. I right click on a file > delete > "Are you sure you want to delete the selected item" > move to trash... nothing.

**Comment by 50Wliu** [comment]
@xDinomode what OS are you using, and what Atom version?

**Comment by xDinomode** [comment]
@50Wliu Windows7 and 1.3.3

**Comment by 50Wliu** [comment]
Ok.  In that case this is a duplicate of atom/tree-view#666.  I'm working on a fix for it.

**Comment by xDinomode** [comment]
Okay glad I'm not the only one with this problem. please fix soon
