### ISSUE TITLE
atom shell command broken when run from tmux

### ISSUE THREAD

**Issue by timothysu** [atom/atom#10401]
Using the 'atom' shell command:

In tmux: "The application /Applications/Atom.app cannot be opened because its executable is missing."
However, open /Applications/Atom.app works just fine.

Outside of tmux: it opens fine

**Comment by lee-dohm** [comment]
Thanks @timothysu :grinning:

**Comment by timothysu** [comment]
Closing issue -- unable to reproduce after I restarted my mac.  Should have done this common fix first...

**Comment by Rastopyr** [comment]
I reproduce this issue after install tmux, and then fixed after restart mac.
