### ISSUE TITLE
indentation being changed on paste despite auto indent on paste unchecked

### ISSUE THREAD

**Issue by pknowles** [atom/atom#10407]
I have both Editor Settings->Auto Indent and Editor Settings->Auto Indent On Paste unchecked and start with a new plain text file (using hard tabs):

```
one
    two
```

where `two` is indented with a tab. I place the cursor at the end of `two`, hold shift, press up and copy the selection. This _should_ copy a newline character, a tab character and the word `two`, i.e. `"\n\ttwo"`. Then I paste, and get this:

```
one
    two
        two
```

somehow an extra tab has been injected. Additional pasting increases the indentation even further! I expected this:

```
one
    two
    two
```

Interestingly, if `one` is also indented before copying, the correct behaviour is observed. It's as though atom is counting the difference in indentation between the lines selected when the text is copied. Personally I hate anything that tries to be too fancy and automatic, and it is _far_ more frustrating to me than the times when something could have predicted what I wanted and didn't.

**Comment by amytruong** [comment]
Was able to reproduce this. Thanks @pknowles!

**Comment by Bulat-Ziganshin** [comment]
seems this is a dup and can be closed: https://github.com/atom/language-clojure/issues/34

**Comment by pknowles** [comment]
Still experience this in 1.7.2. There's also another effect which seems to be related:

```
»   /**
»   ·* hello
»   ·* world
»   ·*/
»   void hello()
```

Selecting one line up from the end of `hello()` to include the newline, then pasting at the end of `hello()` gives the wrong indentation. In fact it gives spaces.

```
»   /**
»   ·* hello
»   ·* world
»   ·*/
»   void hello()
···void hello()
```
