### ISSUE TITLE
Add a keep-indentation on newline option rather than auto-indent

### ISSUE THREAD

**Issue by pknowles** [atom/atom#10408]
<strike>In some cases I've found the Editor Settings->Auto Indent to misbehave. Don't get me wrong, in many cases it works great. However,</strike> I think it would be great to have the option to indent newlines to exactly match the indentation of the above line, but then not do anything further.

<strike>In the worst case, I've had the auto indent increase indentation for every new line, which I've then had to remove (I think when working with mixed languages in the same file).</strike> It is more often the case I want the indentation the same on a newline and am happy to change it myself at the start and end of blocks.

**Comment by beaushinkle** [comment]
Can you provide a code example, or perhaps a gif of the exact behavior?

**Comment by pknowles** [comment]
@beaushinkle I was more after a way to turn off some automation rather than noticing recurring bugs. Apologies for my slanderous talk :P. It's quite possible I've mistaken what in my opinion were issues with Auto Indent On Paste (e.g. pasting multiple lines after an `if` without braces in javascript), but turning this off is fine. Anyway, if I do notice anything reproducible I'll start a new issue.
