### ISSUE TITLE
Color issue in 1.4.0

### ISSUE THREAD

**Issue by RoleplayDotNetwork** [atom/atom#10414]
After updating my atom editor all the colors in all my themes start looking very weird.

Before 1.4.0
![image](https://cloud.githubusercontent.com/assets/7228476/12326458/d641127a-bac8-11e5-8a92-04078b21c48d.png)

After 1.4.0
![image](https://cloud.githubusercontent.com/assets/7228476/12326406/8796fd7e-bac8-11e5-91ee-3ceb3470c188.png)

The theme in the images above is Seti both ui and syntax

Is this intended in the update or is there a bug?

**Comment by 50Wliu** [comment]
Hi @RoleplayDotNetwork, the Javascript language changed a lot between 1.3.0 -> 1.4.0, which added support for chained methods and properties.

Do you have any suggestions as to what the syntax highlighting should be like?

**Comment by RoleplayDotNetwork** [comment]
Ah that would explain it.
Thanks @50Wliu 
Guess it's just something to get use to.
Though there was an issue on another project where the bracket color matching was quite off. ![image](https://cloud.githubusercontent.com/assets/7228476/12327292/945fc496-bacd-11e5-8126-3da904b80d19.png)

**Comment by mnquintana** [comment]
@RoleplayDotNetwork Thanks for the update! In that case, would you mind opening another issue for that bracket syntax highlighting issue on https://github.com/atom/language-javascript? (Also take a look at the open issues in that repo – it might exist already.)

**Comment by arodic** [comment]
The highlighting changed for me so much that it is close to unusable. Is there any way to revert to 1.3 highlighting scheme?

**Comment by 50Wliu** [comment]
@arodic if you're using one-dark-syntax [this comment](https://github.com/atom/one-dark-syntax/issues/60#issuecomment-172628426) should help you.  Otherwise, a more general solution is available at https://github.com/atom/language-javascript/issues/308#issuecomment-173328656.

In addition, I would greatly appreciate it if you could give some suggestions as to what the highlighting should be like.

**Comment by arodic** [comment]
@50Wliu thanks I'll look that up. Personally, I prefer the way it was before. For example, in the before/after screenshots below you can see that both `this` and properties of `this` are the same color. That makes is harder to visually discern very important `this` keyword. However, properties are sometimes orange for reason I cannot understand.

![before](https://cloud.githubusercontent.com/assets/708984/12577142/ccd9ace8-c418-11e5-8028-9a54b0f26135.png)
![after](https://cloud.githubusercontent.com/assets/708984/12577141/ccbb1bde-c418-11e5-85a9-45c6def4b168.png)

**Comment by 50Wliu** [comment]
Ok, when `this` becomes orange, that's definitely a bug :P.  I *think* we've fixed that but I'll double-check later today just to be sure.

Also, you're in luck - `this` (and `super`) can be styled separately using `.variable.language.js` so that you can give it a unique color.
