### ISSUE TITLE
Atom crashes when git and hg are present in one project

### ISSUE THREAD

**Issue by qunaibit** [atom/atom#10411]
Atom crashes when trying to "Add Project Folder" of a project that has both hg and git.
I use hg-git to mirror two repositories (hg and git).

I wasn't been able to generate the log using `atom --safe`

**Comment by mnquintana** [comment]
Just to make sure we're reproducing this issue as accurately as possible, what's the (rough) folder structure of the project? Like:

```
project/
  .git/
  .hg/
```
?

**Comment by qunaibit** [comment]
Sure,

```sh
drwxr-xr-x  19 mmm  staff       646 Jan 14 21:51 .
drwxr-xr-x  10 mmm  staff       340 Jan 13 02:00 ..
drwxr-xr-x  11 mmm  staff       374 Jan 12 21:37 .git
drwxr-xr-x  20 mmm  staff       680 Jan 14 19:50 .hg
drwxr-xr-x   2 mmm  staff        68 Jan 14 18:30 .hgcheck
-rw-r--r--   1 mmm  staff      1112 Jan 11 22:51 .hgignore
-rw-r--r--   1 mmm  staff     21172 Jan 12 21:31 .hgtags
drwxr-xr-x   7 mmm  staff       238 Apr 21  2015 .idea
-rw-r--r--   1 mmm  staff       678 Jan 12 21:31 .travis.yml
-rw-r--r--   1 mmm  staff      1564 Apr 21  2015 LICENSE
-rw-r--r--   1 mmm  staff      1951 Jan 12 22:20 README.md
drwxr-xr-x  14 mmm  staff       476 Jan 11 23:44 lib
drwxr-xr-x   4 mmm  staff       136 Jan 11 23:49 mxbuild
-rw-r--r--   1 mmm  staff    685496 Jan 12 16:56 setuptools-19.2.zip

```

**Comment by lee-dohm** [comment]
I can't reproduce this on Atom v1.4.0 on Mac OS X 10.11.2. Do you have nuclide installed? Or something else that works with Mercurial?

**Comment by qunaibit** [comment]
nope, I experience this issue on a clean (no additional packages) Atom v1.4.0
I will try to reproduce it on another machine and see.
