### ISSUE TITLE
The 'find and replace' result screen should have more features

### ISSUE THREAD

**Issue by tofagerl** [atom/atom#10428]
After search when the result are shown, there should either be a checkbox for each result so you can pick which result you want to replace, or the user should be able to quickly replace each result so he doesn't have to go to each single result and manually replace the text. Either a right-click command on the result itself, or a little button next to the gutter for each result which replaces and lets you regret it.

It's really annoying when you have to replace something which occurs 99 times, but you want to replace only 75 of them.

**Comment by primalmotion** [comment]
:+1: 

Something like that would be a dream

![atom-find-replace](https://cloud.githubusercontent.com/assets/208711/13716239/b58a3366-e78e-11e5-8da7-c398d4f123d9.png)

**Comment by CyrilPeponnet** [comment]
:+1:

**Comment by Dogild** [comment]
+1

**Comment by CyrilPeponnet** [comment]
👎
