### ISSUE TITLE
package specific setting page become not accessible from v1.4.0

### ISSUE THREAD

**Issue by t9md** [atom/atom#10426]
After upgraded to v1.4.0, setting can not accessible for page which have `activationCommands`, I first noticed in my package, but confirmed this issue is also happen for symbols-view package.

I'm not sure this issue is for settings-view or Atom core.
But I believe all package which have `activationCommands` in `package.json` have affect this issue.

OS X 10.9.5
Atom v1.4.0

When I reverted to v1.3.3 the issue not happen, OR when I removed activationCommands section from package.json issue not happen(can access setting page via settings-view)

The setting page I'm saying is package specific setting page by clicking setting button of specific package panel.

Screen capture with `symbols-view` package.

<img width="760" alt="settings_ __users_tmaeda_github_symbols-view" src="https://cloud.githubusercontent.com/assets/155205/12346575/fc99a556-bb98-11e5-80d5-1700adc151f5.png">

<img width="816" alt="settings_ __users_tmaeda_github_symbols-view" src="https://cloud.githubusercontent.com/assets/155205/12346585/1c921316-bb99-11e5-9e87-986a0c372027.png">

When I removed `activationCommands` from `package.json`, setting page become accessible.

<img width="780" alt="settings_ __users_tmaeda_github_symbols-view" src="https://cloud.githubusercontent.com/assets/155205/12346614/59dac39e-bb99-11e5-8956-15c451290bb6.png">

<img width="949" alt="settings_ __users_tmaeda_github_symbols-view" src="https://cloud.githubusercontent.com/assets/155205/12346608/461bdbd6-bb99-11e5-8870-aee5780c11a0.png">

**Comment by kandros** [comment]
atom 1.4.0 
osx 10.11.02

working for me
![screen shot 2016-01-15 at 08 57 48](https://cloud.githubusercontent.com/assets/4562878/12348299/2efddb4e-bb66-11e5-814c-1c6d308a12e8.png)

**Comment by t9md** [comment]
@kandros What you want to say is **not working for me** right?

**Comment by kandros** [comment]
@t9md  typo 😁

**Comment by maxbrunsfeld** [comment]
:sparkles: Thanks for catching this and for the detailed report, @t9md!

**Comment by trois** [comment]
osx 10.11.2
atom 1.5.0-b1 => missing 
atom 1.4.1 => missing
atom 1.3.3 => work  (to avoid autoupdating, I made temporary change.  
chmod 555 ~/Library/Application\ Support/com.github.atom.ShipIt ）

**Comment by 50Wliu** [comment]
@trois the fix isn't in the betas (yet).  At the current rate it'll be in Atom 1.7.0, but it may be cherry-picked as a hotfix.

**Comment by lierdakil** [comment]
Damn it all to hell! This issue pretty much kills all atom-haskell projects, since I use deferred activation *extensively*, for performance reasons, and most packages need to be configured.

**Comment by 50Wliu** [comment]
Hey @lierdakil, the fix has been released in Atom 1.4.2 :smile:.

**Comment by lierdakil** [comment]
Thanks.
1 февр. 2016 г. 23:27 пользователь "Wliu" <notifications@github.com>
написал:

**Comment by jonobacon** [comment]
It looks like this issue may be back. See https://github.com/AtomLinter/linter-pylama/issues/33 for details.
