### ISSUE TITLE
repositoryProvider - new logic suggestion

### ISSUE THREAD

**Issue by viatsko** [atom/atom#10423]
Hi!

I'm currently working on custom git provider which will work exactly like mercurial's one for Nuclide.

The problem is that using current logic implemented in Atom, if we have .git repository, we might have it resolved to default GitRepository implemented in Atom because if we are adding provider for GitRepository, there will be two with conflicting names and current resolve mechanism is barely predictable because currently Atom is trying to Promise.resolve all providers at once.

What I suggest is to have replacement logic instead - if we have custom git-repo implementation in packages, let it override the default one (it's implementing the same interfaces anyway) or let's change Promise.all logic to step-by-step one - it will be slower to resolve repo provider for project, but we will ensure that we tried to use custom provider before GitRepository one. I'm ready to provide pull request for review for any solution you will choose of these two.

Otherwise, it will make implementing custom git repository impossible or we'll have to :ship: our own version of Atom if we need one.

**Comment by viatsko** [comment]
I'm currently developing this branch https://github.com/viatsko/nuclide (draft) + using custom Atom build with "replace" logic.

**Comment by joshaber** [comment]
`Promise.all` still preserves the order of the promises, regardless of how quickly they resolve.

Given https://github.com/atom/atom/pull/10296, won't custom providers always be towards the beginning of the list?

**Comment by viatsko** [comment]
I thought so, but that didn't work, I'll double check again on what's happening, coming back shortly

**Comment by viatsko** [comment]
<img src="http://i.imgur.com/D0XKHA6.png" />

Nope, the problem is there, digging :)

**Comment by viatsko** [comment]
Interesting stuff is if I'm reloading project in Atom's session - repository detection works correctly, but not for the first start ;)

**Comment by joshaber** [comment]
Possibly a race condition in asking for the provider vs. registering?

**Comment by viatsko** [comment]
Kinda, here's the problem:

```coffeescript
    repo = null
    console.log(@repositoryProviders) # = Array[3] = hg, git, default git
    for provider in @repositoryProviders
      console.log(@repositoryProviders) # = Array[3] = hg, git, default git
      console.log(@repositoryProviders[0]) # = default git provider
      console.log(@repositoryProviders[1]) # = undefined
      console.log(@repositoryProviders[2]) # = undefined
      console.log(provider)
      console.log(provider.repositoryForDirectorySync?(directory))
      break if repo = provider.repositoryForDirectorySync?(directory)
    @repositories.push(repo ? null)
```

**Comment by viatsko** [comment]
I'd suggest #10424 to fix this, shouldn't make any even medium impact to customers (most of them anyway are sticking to internal git only)
