### ISSUE TITLE
After opening several, tabs are not all displayed.

### ISSUE THREAD

**Issue by valix** [atom/atom#10429]
After opening several tabs (about 18), the tabs are not all displayed. Atom 1.5.0-beta0
![bugtab](https://cloud.githubusercontent.com/assets/296379/12351290/cfdf7f84-bb7c-11e5-85b9-5194fcc053b4.png)

**Comment by ChristianGrech** [comment]
+1

**Comment by amytruong** [comment]
Dupe of https://github.com/atom/tabs/issues/137

**Comment by amytruong** [comment]
You can also subscribe to thread :point_up: for updates :smile:
