### ISSUE TITLE
ctrl-alt-shift-a doesn't register as a hotkey

### ISSUE THREAD

**Issue by SlimeQ** [atom/atom#10422]
when i upgraded to 1.3.0 i somehow lost my custom ctrl-alt-shift-a hotkey. my keybinding resolver shows ctrl-alt-shift-<something_else> works, but when ctrl-alt-shift is pressed it does not detect A for some reason.

Ubuntu 14.04, Atom 1.3-1.4

**Comment by lee-dohm** [comment]
I think someone mentioned recently that <kbd>Ctrl+Shift</kbd> was reserved for certain functions on Linux and shouldn't be used? Is it possible that something else on your system is capturing it before it gets to Atom?

**Comment by demhydraz** [comment]
Happens here too, Arch x86_64, atom 1.5.0-beta0 w/ Cinnamon 2.8.6. <kbd>Ctrl+Alt+A</kbd> works fine but <kbd>Ctrl+Alt+Shift+A</kdb> doesn't get registered.

**Comment by SlimeQ** [comment]
xev shows all keys being pressed during this combo so i don't think it's a system problem. that being said, this hotkey was working before i re-installed ubuntu, but i also upgraded atom at that time.

**Comment by lee-dohm** [comment]
To my knowledge, if the Keybinding Resolver doesn't see the combination being pressed then the key combination isn't making it to Atom, something outside of Atom is intercepting it.
