### ISSUE TITLE
CPU pegged at 100% in due to .git directory in home directory

### ISSUE THREAD

**Issue by leejoramo** [atom/atom#10421]
Atom has always been a performance disaster on my MacBook. I give it a try with each major release and watch Atom use 100% CPU and keep eating over 2GB of RAM.

After a long exchange on [Hacker News](https://news.ycombinator.com/item?id=10901691) about the current version 1.4 release, I dug deeper and ended up finding a [solution buried](https://github.com/atom/atom/issues/3426#issuecomment-119780457) in several other issues posted here. 

I had long ago accidentally created a .git directory in my home directory. This caused Atom to process my entire 350GB home directory. Deleting ~/.git and restarting Atom solved the problem. 

I am sure what the underlining technical issue is here. Why should Atom process the entire home directory. 

* If this is a *bug*, it should be fixed. 
* If this is a *feature*, a warning should be provided to users that their home directory contains a .git folder, which will hinder performance. Perhaps with the ability to disable the feature. 
* This issue should be more easily found in documentation, FAQ, trouble shoting. It actually took me two hours today to track this down, and this is after nearly two years of not using Atom because it was a  resource hog. 

I am sure many people have accidentally (or intensionally) created a ~/.git directory at some.

**Comment by joshaber** [comment]
Happily this has been fixed and is out in the 1.5 beta!
