### ISSUE TITLE
Can't get electron due to bad credentials

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#10427]
I'm trying to build atom for the first time.  I've always just installed using the `.deb`.  So I may be doing something stupid.  Anyway, I'm getting this when building on Ubuntu 12.04.

```
Running "download-electron" task
>> Cannot find electron v0.34.5 from GitHub [Error: Bad credentials]
Warning: Task "download-electron" failed. Use --force to continue.

Aborted due to warnings.
```

Help please?

**Comment by joshaber** [comment]
Do you have an `ATOM_ACCESS_TOKEN` environment variable set? If so, is it possible it's wrong? See https://github.com/atom/atom/blob/8677ca3a1086d14621e401672ef7fc5723919a4a/build/Gruntfile.coffee#L259 for context.

**Comment by mark-hahn** [comment]
Thanks.  Maybe this should be in the build instructions at
https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md.

**Comment by joshaber** [comment]
Perhaps. A quick search didn't reveal any dupes. Since we provide a default value, you have to have set `ATOM_ACCESS_TOKEN` previous.

Did that resolve the problem for you?

**Comment by mark-hahn** [comment]
I think so.  It has gotten past the download-electron-chromedriver task.

> A quick search didn't reveal any dupes

I don't understand, not that it matters.  Dupes of what?

**Comment by joshaber** [comment]
Ah, sorry, I mean that I couldn't find any other issues with this problem.

I'll go ahead and close this.

**Comment by mark-hahn** [comment]
>  you have to have set ATOM_ACCESS_TOKEN previous.

Aha.  Now I understand.   So it isn't a doc problem.  I will try to find my
previous declaration.

Thanks mucho.
