### ISSUE TITLE
Build error on windows：OutOfMemoryException

### ISSUE THREAD

**Issue by yuanyinchun** [atom/atom#10425]
Hello
trying to build atom,  OutOfMemoryException occured during grunt task *create-windows-installer*, 
here are some logs from *SquirrelSetup.log*, which located in *build/node_modules/grunt-electron-installer/vendor/SquirrelSetup.log*
>2016-01-15 09:37:08> DeltaPackageBuilder: We couldn't create a delta for app.asar, attempting to create bsdiff
2016-01-15 09:37:09> DeltaPackageBuilder: We really couldn't create a delta for app.asar: System.OutOfMemoryException
   in Squirrel.Bsdiff.BinaryPatchUtility.Create(Byte[] oldData, Byte[] newData, Stream output)
   in Squirrel.DeltaPackageBuilder.createDeltaForSingleFile(FileInfo targetFile, DirectoryInfo workingDirectory, Dictionary`2 baseFileListing)

It seems that generating delta data for app.asar cost lots memory. 
*grunt-electron-installer* called *Update.exe*, in windows task manager, I noticed that  *Update.exe* 's memory usage up to 1G.  My computer has 8G RAM and at least 1G avaiable at that time, but OutOfMemoryException still occurs. Don't know why, pls help me out.

###### building environment
* system: windows 7 SP1 64bit
* RAM: 8G
* python: v2.7.10
* nodejs: v4.2.4

**Comment by yuanyinchun** [comment]
well, problem solved.
According to [this](http://www.codeproject.com/Articles/483475/Memory-Limits-in-a-NET-Process) post, 32 bit .Net Application start receiving OutOfMemory exception when reaching around 1.2G memory usage.
So my solution is expanding memory limition for Update.exe. Visual studio provide tool [EditBin.exe](https://msdn.microsoft.com/en-us/library/d25ddyfc.aspx) to modify exectuable file, all I need to do is set /LARGEADDRESSAWARE option to Update.exe.
```
editbin /LARGEADDRESSAWARE Update.exe
```
hope it helps.

**Comment by lee-dohm** [comment]
@yuanyinchun Thanks for the feedback. Ultimately, I feel like the right solution is to build 64-bit on Windows if we can ... I'm not sure how feasible that is or when we could make the switch. I've brought this up to the team's attention so that they're aware of it.

Thank you very much for the workaround!

**Comment by yuanyinchun** [comment]
@lee-dohm Agree with you, tried to build 64-bit version but failed. Workaround do the job for now, it will be great to have a 64-bit version as ultimate solution.

**Comment by damieng** [comment]
Have never seen this error in countless builds of Atom including on an 8GB 64-bit Windows 10 machine. Are you still seeing this in recent builds? We recently took an update to Squirrel - let us know if this still happens for you by reopening the issue.
