### ISSUE TITLE
'find whole word' fails to find some reasonable search strings

### ISSUE THREAD

**Issue by rcprdf** [atom/atom#10438]
with 'find whole word' on, search for 'loggedIn(user)' in buffer will NOT find it in: ' loggedIn(user);'

(regexp and other selective search options were off)

with 'find whole word' off, it will find it there, but also in ' addAgentThenLoggedIn(user);' of course

in general 'find whole word' seems to sometimes defeat searches for some strings that are not themselves single whole words - though it works as it should sometimes, for some of them

for example, searching for 'loggedIn(' with 'find whole word' on seems to work correctly: it finds the target in ' loggedIn(user);' but not in  ' addAgentThenLoggedIn(user);'

atom 1.4.0

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace? Thanks!
