### ISSUE TITLE
So the new update removed the atom icon from the .exe launcher

### ISSUE THREAD

**Issue by xDinomode** [atom/atom#10431]
The application is missing the atom icon.. It's just a default icon now like the one you get after compiling a c program on windows 7. How do I add it back? This happened yesterday so I'm assuming it's because of the auto update to 1.4?

**Comment by damieng** [comment]
Where are you seeing this incorrect icon? Can you post a screenshot?

**Comment by xDinomode** [comment]
Sorry for the late reply. Its not showing this on the desktop ![image](http://i.imgur.com/Qs3WaAK.png)

**Comment by damieng** [comment]
Icon updating has been fixed in the 1.7 release as part of bringing in the latest Squirrel.Windows updater via grunt-electron-update https://github.com/atom/atom/pull/10858
