### ISSUE TITLE
bad option: --harmony_collections

### ISSUE THREAD

**Issue by bil-elmoussaoui** [atom/atom#10440]
I'm having this issue since i upgraded Nodejs on my 
```bash
/usr/share/atom/resources/app/apm/bin/node: bad option: --harmony_collections
```
i'm using Fedora 23 
Atom version :1.4.0
Output of  : v5.4.1
```bash
/usr/share/atom/resources/app/apm/bin/node -v 
```

**Comment by 1dot75cm** [comment]
Please see https://github.com/atom/atom/issues/8894 , https://github.com/helber/fedora-specs/issues/2 and https://github.com/FZUG/repo/issues/64 .

**Comment by lee-dohm** [comment]
Did you change the version of Node installed within the `/usr/share/atom/resources/app/apm/bin` directory? If so, making that change is what broke apm. apm is only designed to work properly with the version of Node packaged with apm.

**Comment by bil-elmoussaoui** [comment]
This works fine now! Thanks :+1:
