### ISSUE TITLE
Windows SmartScreen Warning

### ISSUE THREAD

**Issue by trunneml** [atom/atom#10443]
Windows SmartScreen pops up when installing Atom. The last time I installed Atom on my other Windows 10 PC that didn't happen. Is something wrong with the signature or is my new Laptop misconfigured?

**Comment by chainsawbeaver** [comment]
I have the same issue.
Windows SmartScreen complains about an  unknown app.
The "More Info"-Button reveals unknown publisher

**Comment by trunneml** [comment]
Also my second PC has the problem. There are also other app that have this problem like Github Desktop. I reinstalled my system and the problem was shortly gone until I installed the januar security update for windows 10 151.

**Comment by root-ua** [comment]
Same error on Windows 7. SmartScreen says "Unknown publisher".

**Comment by paulcbetts** [comment]
Almost certainly a dupe of #10567

**Comment by 50Wliu** [comment]
Ok, closing in favor of #10567 and #10383.
