### ISSUE TITLE
Atom build freezes on linux

### ISSUE THREAD

**Issue by hultberg** [atom/atom#10453]
While installing modules during build it always freezes after a while, like this:

```
$ script/build
Node: v0.12.9
npm: v2.13.3
Installing build modules...
=> Took 7334ms.

Installing apm...
=> Took 1737ms.

Deleting old packages...
=> Took 861ms.

Installing modules ✓
Installing update-package-dependencies@0.10.0 ✓
Installing welcome@0.33.0 ✓
Installing whitespace@0.32.1 ✓
Installing wrap-guide@0.38.1 ✓
Installing language-c@0.51.1 ✓
Installing language-clojure@0.19.1
```

Is this related to the github api rate limits as I get when using other dependency managers that downloads from github?

Using Ubuntu 15.10 64-bit with gnome.

**Comment by facelessjim** [comment]
Can relate, 4 times on 5 i get stuck at a random module install and have to manually abort and try again.

**Comment by darkmorpher** [comment]
@hultberg Is this still reproducible?

CC @damieng to close

**Comment by facelessjim** [comment]
Haven't been able to actively reproduce it lately. Apart from some minor
hiccups the build process runs fine. Sometimes during the modules build
process it get stuck and i have to restart the installation again.
But from what i could see no module in particular could be held responsible.

That said, i haven't had issues in the last 3-4 updates
Il 05/mag/2016 22:53, "Hei Liebrecht" <notifications@github.com> ha scritto:

**Comment by TheAntheus** [comment]
I am also having this issue. It will get to a different module then freeze. I have yet to have a successful building out of the 20+ times I have tried.

**Comment by hultberg** [comment]
Closing, not been able to reproduce.
