### ISSUE TITLE
Save All save also not modified files

### ISSUE THREAD

**Issue by Polatouche** [atom/atom#10457]
When using the Save all command, all the opened files are touched when not modified. I'll be better to save only modified files to keep track of the last modification time.

**Comment by mnquintana** [comment]
What version of Atom are you using? Does this happen in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by Polatouche** [comment]
I'm using atom v 1.0.0  on ubuntu 14.04 64bits, and yes this happens also in safe mode.

**Comment by mnquintana** [comment]
You're using a very old version of Atom – this was fixed back in 1.2.0 (refs https://github.com/atom/atom/issues/2871). Please update to the latest version (1.4.0).
