### ISSUE TITLE
node version mismatch

### ISSUE THREAD

**Issue by facelessjim** [atom/atom#10456]
i get this:
WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} 
(current: {"node":"5.4.1","npm":"3.5.3"})

everytime i start the build script.

**Comment by mnquintana** [comment]
What commit are you trying to build?

**Comment by facelessjim** [comment]
I cloned directly from the github so i assume the lastest one. It still warned me but the installation went on fine.

**Comment by mnquintana** [comment]
Would you mind checking which commit you're on? Just want to make sure we have enough information to look into this further. :mag:

**Comment by facelessjim** [comment]
atom version: 1.6.0-dev-0893201

**Comment by facelessjim** [comment]
Out of curiosity i tried to replicate the issue but it seems it's no longer there... i'm not sure what I did. I probably mixed up different versions and i can't recall what other version i could have used.
I guess this report can be closed as it doesn't really provide any useful informations.
I'm terribly sorry...

**Comment by mnquintana** [comment]
No worries, thanks for the update @facelessjim!

**Comment by 50Wliu** [comment]
@maxbrunsfeld updated the prettyjson dependency maybe 2-3 months ago to prevent this...perhaps some node caching went wrong.
