### ISSUE TITLE
Update.exe eating CPU like edible paper

### ISSUE THREAD

**Issue by Ashedragon** [atom/atom#10459]
Whenever I start up atom, the update.exe launches and its CPU usage goes through the roof (until I force close it, but then it just launches again by itself later on). The CPU usage never goes down and it just sits there hogging it all. This happens constantly on my Windows 7 64-bit computer, but happens significantly less often on my Windows 10 32-bit laptop.

**Comment by lee-dohm** [comment]
@paulcbetts Am I remembering correctly that `update.exe` is part of the Squirrel.Windows infrastructure?

**Comment by paulcbetts** [comment]
Correct. Can you copy the SquirrelSetup.txt log that's in `%LocalAppData%\Atom`?

**Comment by Ashedragon** [comment]
I couldn't copy it, but https://dl.dropboxusercontent.com/u/10498962/lib/SquirrelSetup.log

**Comment by paulcbetts** [comment]
You're super far behind and you keep killing update.exe, so you keep getting farther behind. Uninstall and reinstall

**Comment by Ashedragon** [comment]
Ah, that makes a lot of sense. I wish it wouldn't eat so much CPU to update though, it's kind've annoying.

**Comment by paulcbetts** [comment]
@Ashedragon Agree, though now that Atom has moved to ASAR, this problem is _way_ less prevalent so you shouldn't end up this way again
