### ISSUE TITLE
Docs for Point don't state whether rows and columns are indexed from 0 or 1

### ISSUE THREAD

**Issue by WalterGR** [atom/atom#10462]
The docs for Point don't state whether rows and columns are indexed from 0 or 1.

https://atom.io/docs/api/v1.4.0/Point

```
Point [essential]

Represents a point in a buffer in row/column coordinates.

Every public method that takes a point also accepts a point-compatible Array.
This means a 2-element array containing Numbers representing the row and
column.  So the following are equivalent:

  new Point(1, 2)
  [1, 2] # Point compatible Array 
```

**Comment by mnquintana** [comment]
It actually does mention that rows and columns are zero-indexed:

https://atom.io/docs/api/v1.4.0/Point#instance-row
https://atom.io/docs/api/v1.4.0/Point#instance-column

> A zero-indexed Number representing the row of the Point.

Hope that helps!

**Comment by WalterGR** [comment]
Ah, I should have expanded.  Thanks.
