### ISSUE TITLE
Incorrect list of symbols in PHP

### ISSUE THREAD

**Issue by sebastien-gallet** [atom/atom#10461]
In PHP, if a function name first character is lowercased and the parameter is a strongly typed initialized array:
![screen shot 2016-01-17 at 10 59 52 am](https://cloud.githubusercontent.com/assets/968164/12375536/62d04934-bd0a-11e5-8be5-c0fafefcfaf4.png)

Then pressing the shortcut "Goto Symbol", the list of symbols shows the parameter name instead of the function name.
(As a side note, somehow it pick "name" in the comment as a symbol as well.) 
![screen shot 2016-01-17 at 11 00 00 am](https://cloud.githubusercontent.com/assets/968164/12375537/62d39d96-bd0a-11e5-8c15-6dc8ad518a15.png)

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/language-php? Thanks!
