### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by kaifyahuja** [atom/atom#10464]
Hello,
I have been using atom before too. I just bought a new laptop 2 days before and had windows 10 installed in it. After that i tried a lot of times to install atom but the system gives error.
Please help me as soon as possible because i have a lot of works pending on the way.

**Comment by 50Wliu** [comment]
What is the system error?

**Comment by kaifyahuja** [comment]
This is the error..

**Comment by 50Wliu** [comment]
@kaifyahuja Attachments via emails don't work, can you please view the actual Github issue and attach it through the comment editor?  Thanks!

**Comment by damieng** [comment]
No response from user, closing.
