### ISSUE TITLE
Control characters at the end of the line cause the cursor to disappear

### ISSUE THREAD

**Issue by WalterGR** [atom/atom#10463]
I discovered this after pasting lines that had been copied from a web page.[1]

(Notice that at the beginning of the video, the column number changes but the cursor doesn't move.  I'm pressing Right and Left to go forward and backward over the control character at the beginning of the line.  This may be #1839 - "Control characters are not shown".)

Then I press Right repeatedly to get to the end of the line.  The cursor vanishes.  I dance around with Right and Left a bit.  Then I press Right until I'm at the beginning of the next line.

![atom-control-characters-not-shown-and-cause-cursor-to-disappear](https://cloud.githubusercontent.com/assets/380880/12376473/f745e0f2-bcaa-11e5-8d47-f4f89cff11ea.gif)

The character sequence after the 2 close parens at the end of the last line of text is `e2 80 8b`, then `\n`.

[1] - If you have access to O'Reilly Safari: the text I used to repro this is on https://www.safaribooksonline.com/library/view/programming-clojure-2nd/9781941222836/f_0042.html .  It's the code sample immediately below the text "Clojurish in another way as well:"

**Comment by RayFoss** [comment]
I can confirm that the "Highlight bad chars" and "Troll stopper" are not remedies for this problem.
To replicate, copy this code to atom and move the cursor between the middle  `Here->­<-Here` .
