### ISSUE TITLE
project folder name, show the project in focus

### ISSUE THREAD

**Issue by ppKrauss** [atom/atom#10478]
When using the editor with more than 1 project folder added (ex. with "Add Project Folder" mouse menu button at left folder viewer), the first project name is showed at "status" (superior bar)... Even when you nou using any file of the project and with many files of other (ex. second) project files... This make confusion and is not util.

The ideal is to show (at superior status bar) **the project of the _in focus_ file**.

**Comment by ElmarNeudam** [comment]
I would like to have that to!
Especially because i can better track the git tab content (which is linked to the project in focus).
