### ISSUE TITLE
how to choose a promt word with the hot key "enter"?

### ISSUE THREAD

**Issue by OneNewLife** [atom/atom#10471]
+ i'm accustomed to Sublime Text.everytime i wanna choose a promt word with "enter" ,the cursor will jump to the next row?how can i  solve that?ths>_<

+ System: win10:1511, Atom:1.4.0

![default](https://cloud.githubusercontent.com/assets/10388933/12386211/a978e752-bdfe-11e5-8da6-19e0a13e3211.PNG)
![1](https://cloud.githubusercontent.com/assets/10388933/12386212/a9a67550-bdfe-11e5-8bdc-6989ec00d1c8.PNG)

**Comment by OneNewLife** [comment]
i thought i made it at first,but the issue suddenly occured again.why sometimes the "enter" didn't work?

**Comment by mnquintana** [comment]
Go to Settings > Packages > autocomplete-plus and make sure `Keymap For Confirming A Selection` is set to either `tab and enter` or `enter`.

<img width="981" alt="settings" src="https://cloud.githubusercontent.com/assets/823545/12400552/cd8f1e3c-bdee-11e5-8f5a-747b8d5f5ba6.png">

In the future, you'll have better luck with support questions on [Discuss](https://discuss.atom.io) (Atom's forum) or on Slack.

Also, please take a look at [the guidelines for opening issues here](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

:beers:
