### ISSUE TITLE
Syntax highlighting different colours after update to 1.4

### ISSUE THREAD

**Issue by kokono2** [atom/atom#10472]
Syntax highlighting has changed after I updated from 1.3.3 to 1.4 on Windows 10. I didn't see anything in the changelog so I'm assuming this is a bug.

Before the update (1.3.3):
![before update](https://cloud.githubusercontent.com/assets/10324265/12387094/54558a48-bdca-11e5-9c6a-c40c4a55d470.png)

After the update (1.4):
![after update](https://cloud.githubusercontent.com/assets/10324265/12387099/5b07782e-bdca-11e5-9797-13e3746769fe.png)

**Comment by jonathanprl** [comment]
I am also getting mixed up syntax colouring since the new update.

![Screenshot](http://i.imgur.com/Djcx9I8.png)

**Comment by antigirl** [comment]
My JSX is all white
<img width="250" alt="screen shot 2016-01-18 at 11 18 17" src="https://cloud.githubusercontent.com/assets/1423413/12390118/34f69c0e-bdd5-11e5-8219-84041e8a4c97.png">

**Comment by spypsy** [comment]
keywords also seem to get mixed colours:
![image](https://cloud.githubusercontent.com/assets/6403450/12393290/a46f6342-bdec-11e5-8796-09e1a11d83e7.png)
![image](https://cloud.githubusercontent.com/assets/6403450/12393298/ae6c0e4a-bdec-11e5-9c41-ff808cf118a5.png)
These are in the same file (JSX)

**Comment by 50Wliu** [comment]
> I didn't see anything in the changelog so I'm assuming this is a bug.

It is in fact in the changelog, just not very noticeable.  Highlighting changes generally aren't part of the main changelog.  The changes are as follows:
### [language-javascript](https://github.com/atom/language-javascript)

v0.100.0...v0.104.0

* [atom/language-javascript#242 - Support for properties, function/method calls](https://github.com/atom/language-javascript/pull/242)
* [atom/language-javascript#255 - Reword opening line of readme file](https://github.com/atom/language-javascript/pull/255)
* [atom/language-javascript#256 - Add support for OpenJsCad](https://github.com/atom/language-javascript/pull/256)
* [atom/language-javascript#257 - improve function snippet](https://github.com/atom/language-javascript/pull/257)
* [atom/language-javascript#260 - Revert argumetns matching](https://github.com/atom/language-javascript/pull/260)
* [atom/language-javascript#264 - Fix 'this', 'super'](https://github.com/atom/language-javascript/pull/264)
* [atom/language-javascript#265 - Fix not a constant properties](https://github.com/atom/language-javascript/pull/265)
* [atom/language-javascript#269 - Fix comments in 'import', 'export' statements](https://github.com/atom/language-javascript/pull/269)
* [atom/language-javascript#272 - Allow $dollar$ signs in identifiers](https://github.com/atom/language-javascript/pull/272)
* [atom/language-javascript#266 - Support JSON5 files](https://github.com/atom/language-javascript/pull/266)
* [atom/language-javascript#277 - Tokenize let and var as storage.type.var.js](https://github.com/atom/language-javascript/pull/277)

Please file any issues you have with the new syntax highlighting on the language-javascript repository (while also making sure that you aren't filing duplicates).  We're working hard on improving the language support, but are aware that new bugs were introduced and more work is needed.

@antigirl, @spypsy: I'm not aware of how the JSX highlighting works, but unless it imports language-javascript, you may want to file it on the JSX repository instead.
