### ISSUE TITLE
Path in Window title stays the same and is wrong

### ISSUE THREAD

**Issue by Nek80** [atom/atom#10473]
In the window title after the filename (that is being separated by a dash) there is the file path, but for some reason sometimes it doesn't get updated when you change tabs or open a new tab. This results in displaying an incorrect path which can lead to serious problems (I won't go there, it is obvious).

Example:

![atom-window-title-path-bug 1](https://cloud.githubusercontent.com/assets/5416165/12388742/78061346-bddd-11e5-888e-32d61555fdfd.PNG)

When opening atom and open a file it correctly displays the filename and then the correct path besides it.

![atom-window-title-path-bug 2](https://cloud.githubusercontent.com/assets/5416165/12388743/780981e8-bddd-11e5-8959-5bbb26b61ab5.PNG)

But if then you open or switch to a new tab the path remains the same and is therefore incorrect.

Atom 1.4.0
Windows 10 x64

**Comment by Haggus** [comment]
Is it supposed to change? Doesn't this path represent the current folder (project) you have opened?

**Comment by Nek80** [comment]
First of all it does not represent a folder, it clearly states a file path including the filename and secondly it makes no sense and has no point to have the "opened" folder path in the title that stucks there in the first place.
