### ISSUE TITLE
Atom tries to delete undefined file when no file is selected

### ISSUE THREAD

**Issue by jagill** [atom/atom#10488]
This is Atom 1.4.0 on OS X 10.10.5.

Reproduce/What does happen:
Select a file in the file tree.  Press Fn-Delete; atom will show a delete alert.  Click Move to Trash.  The once-selected file is deleted and no file is selected.  Press Fn-Delete again; atom will show a delete alert but with no file name.  Click either Cancel or Move to Trash and the alert will disappear with no effect.

What should happen:
Not completely sure, but probably the Fn-Delete press should be ignored.

<img width="1102" alt="atom-delete-bug" src="https://cloud.githubusercontent.com/assets/495664/12408228/6f4bbcb6-be2c-11e5-9d99-cf7a7856574b.png">

**Comment by mnquintana** [comment]
This issue was moved to atom/tree-view#704
