### ISSUE TITLE
Atom: can't delete folder from tree view

### ISSUE THREAD

**Issue by hermit8888** [atom/atom#10485]
I'm having trouble deleting a folder from the tree view sidebar. I can create a folder but I can't delete it once it's created. I get the "Are you sure...Move to Trash" pop-up but nothing happens when I select "Move to Trash" - Windows 7, Atom 1.4.0

**Comment by 50Wliu** [comment]
Thanks for the report!  This looks like a duplicate of atom/tree-view#666 though, so please subscribe there for updates.  Also keep an eye on #9627 for when this will be fixed.
