### ISSUE TITLE
Atom crashes when opening a file from a git repository which has entry contains a forbidden file name on Windows

### ISSUE THREAD

**Issue by ivellioscolin** [atom/atom#10490]
[Environment]
Windows 8.1 64bit

[Reproduction Steps]
1. Install and run latest atom 1.4.0, no extra package installed.
2. Make sure project folder closed in tree view.
3. Drag a file from network mapped driver or remote shared folder into atom.

[Expected Behavior]
File opened and new project folder created.

[Observed Behavior]
Atom crashed. (screen shot and crash log attached)
[Capture.zip](https://github.com/atom/atom/files/95271/Capture.zip)
[Atom Crashes.zip](https://github.com/atom/atom/files/95272/Atom.Crashes.zip)

[Installed packages]
No extra package, all built-in Atom packages.

[Additional information]
Issue can be reproduced in safe mode.
Issue has a fail rate to happen, but easy to see when directory depth is deep on network location. I suspect it's related to connection timeout or remote path info. cache not ready.

**Comment by ivellioscolin** [comment]
Attach the crash dump analysis, looks hit access violation in git.node module:
FAULTING_IP: 
git+5a14a
0f14a14a 8b07            mov     eax,dword ptr [edi]

I don't have symbol but from export table, it looks like in function git_pathspec_match_list_failed_entry.

*************************************
Primary Analysis::
Windows 8 Version 9600 MP (4 procs) Free x86 compatible
Product: WinNt, suite: SingleUserTS
kernel32.dll version: 6.3.9600.17415 (winblue_r4.141028-1500)
Machine Name:
Debug session time: Mon Jan 18 21:48:47.000 2016 (UTC - 5:00)
System Uptime: not available
Process Uptime: 0 days 0:00:09.000
  Kernel time: 0 days 0:00:00.000
  User time: 0 days 0:00:03.000
TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\oca.ini, error 2
TRIAGER: Could not open triage file : e:\dump_analysis\program\winxp\triage.ini, error 2
TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\user.ini, error 2
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\guids.ini, error 2
*** WARNING: Unable to verify timestamp for atom.exe
*** ERROR: Module load completed but symbols could not be loaded for atom.exe
*** WARNING: Unable to verify timestamp for node.dll
*** ERROR: Module load completed but symbols could not be loaded for node.dll
Unable to load image C:\Users\huanxu\AppData\Local\atom\app-1.4.0\resources\app.asar.unpacked\node_modules\pathwatcher\build\Release\pathwatcher.node, Win32 error 0n2
*** WARNING: Unable to verify timestamp for pathwatcher.node
*** ERROR: Module load completed but symbols could not be loaded for pathwatcher.node
TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\modclass.ini, error 2
*** The OS name list needs to be updated! Unknown Windows version: 6.3 ***

FAULTING_IP: 
git+5a14a
0f14a14a 8b07            mov     eax,dword ptr [edi]

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 0f14a14a (git+0x0005a14a)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 00000000
Attempt to read from address 00000000

DEFAULT_BUCKET_ID:  NULL_POINTER_READ

PROCESS_NAME:  atom.exe

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at "0x%08lx" referenced memory at "0x%08lx". The memory could not be "%s".

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at "0x%08lx" referenced memory at "0x%08lx". The memory could not be "%s".

EXCEPTION_PARAMETER1:  00000000

EXCEPTION_PARAMETER2:  00000000

READ_ADDRESS:  00000000 

FOLLOWUP_IP: 
git+5a14a
0f14a14a 8b07            mov     eax,dword ptr [edi]

NTGLOBALFLAG:  0

FAULTING_THREAD:  00007bd4

PRIMARY_PROBLEM_CLASS:  NULL_POINTER_READ

BUGCHECK_STR:  APPLICATION_FAULT_NULL_POINTER_READ

LAST_CONTROL_TRANSFER:  from 00000000 to 0f14a14a

STACK_TEXT:  
00000000 00000000 00000000 00000000 00000000 git+0x5a14a


STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  git+5a14a

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: git

IMAGE_NAME:  git.node

DEBUG_FLR_IMAGE_TIMESTAMP:  5696c223

FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_git.node!Unknown

BUCKET_ID:  APPLICATION_FAULT_NULL_POINTER_READ_git+5a14a

WATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/atom_exe/0_34_5_0/5656a3ba/git_node/0_0_0_0/5696c223/c0000005/0005a14a.htm?Retriage=1

Followup: MachineOwner
*************************************
Loaded Module List:
start    end        module name
00ce0000 03f3d000   atom     atom.exe    
09f60000 09f81000   keyboard_layout_observer keyboard-layout-observer.node
09fb0000 09fd7000   marker_index marker_index.node
0f0f0000 0f1c7000   git      git.node    
0f200000 0f2ee000   msvcr120 msvcr120.dll
0fae0000 0fb34000   onig_scanner onig_scanner.node
0fc20000 1052f000   node     node.dll    
50000000 50024000   pathwatcher pathwatcher.node
51fb0000 51fd0000   scrollbar_style_observer scrollbar-style-observer.node
58ea0000 58ebd000   cached_run_in_this_context cached-run-in-this-context.node
5a7e0000 5a7f6000   usp10    usp10.dll   
65ef0000 65f13000   WINMMBASE WINMMBASE.dll
65f20000 65f89000   dxgi     dxgi.dll    
660c0000 660e3000   winmm    winmm.dll   
66180000 66359000   d3d11    d3d11.dll   
66f80000 67101000   DWrite   DWrite.dll  
68c90000 68caa000   dwmapi   dwmapi.dll  
68ea0000 68f8d000   uxtheme  uxtheme.dll 
68fa0000 6903f000   winhttp  winhttp.dll 
69cb0000 69cf0000   powrprof powrprof.dll
6a1e0000 6a25d000   tiptsf   tiptsf.dll  
6b460000 6b666000   comctl32 comctl32.dll
6b890000 6b8a1000   wkscli   wkscli.dll  
6b8b0000 6b8cd000   srvcli   srvcli.dll  
6b8d0000 6b8e3000   netapi32 netapi32.dll
6b940000 6b94a000   netutils netutils.dll
6bc80000 6bc90000   wshbth   wshbth.dll  
6bc90000 6bc9a000   winrnr   winrnr.dll  
6bca0000 6bcb4000   nlaapi   nlaapi.dll  
6bcc0000 6bcd6000   pnrpnsp  pnrpnsp.dll 
6bce0000 6bcf1000   NapiNSP  NapiNSP.dll 
72990000 72a0e000   dnsapi   dnsapi.dll  
73180000 7318a000   secur32  secur32.dll 
73190000 73198000   version  version.dll 
731c0000 731cf000   wtsapi32 wtsapi32.dll
731f0000 73240000   oleacc   oleacc.dll  
73640000 736a5000   winspool winspool.drv
736b0000 736d1000   devobj   devobj.dll  
73860000 73873000   dhcpcsvc6 dhcpcsvc6.DLL
73880000 73888000   winnsi   winnsi.dll  
73890000 738b0000   IPHLPAPI IPHLPAPI.DLL
738b0000 738c4000   dhcpcsvc dhcpcsvc.dll
738d0000 73a1b000   urlmon   urlmon.dll  
73c00000 73c8b000   SHCore   SHCore.dll  
73c90000 73cae000   bcrypt   bcrypt.dll  
73cb0000 73ce0000   rsaenh   rsaenh.dll  
73ce0000 73cf9000   cryptsp  cryptsp.dll 
73d00000 73d4b000   mswsock  mswsock.dll 
73d60000 73ea1000   dbghelp  dbghelp.dll 
73eb0000 73ebf000   profapi  profapi.dll 
73ef0000 73f0b000   userenv  userenv.dll 
73f10000 74142000   iertutil iertutil.dll
741f0000 743e3000   wininet  wininet.dll 
747b0000 74804000   bcryptPrimitives bcryptPrimitives.dll
74810000 7481a000   CRYPTBASE CRYPTBASE.dll
74820000 7483e000   sspicli  sspicli.dll 
74840000 7487c000   cfgmgr32 cfgmgr32.dll
74880000 749a9000   ole32    ole32.dll   
749d0000 749d7000   nsi      nsi.dll     
749e0000 74a25000   shlwapi  shlwapi.dll 
74a30000 74aea000   rpcrt4   rpcrt4.dll  
74af0000 75dac000   shell32  shell32.dll 
75db0000 75f2d000   combase  combase.dll 
760b0000 760b6000   psapi    psapi.dll   
76120000 76232000   msctf    msctf.dll   
76240000 762d5000   oleaut32 oleaut32.dll
764a0000 765e0000   kernel32 kernel32.dll
765e0000 76630000   ws2_32   ws2_32.dll  
76630000 766f3000   msvcrt   msvcrt.dll  
76700000 76727000   imm32    imm32.dll   
76730000 767ac000   advapi32 advapi32.dll
76840000 7684e000   msasn1   msasn1.dll  
76850000 76927000   KERNELBASE KERNELBASE.dll
76930000 76a3f000   gdi32    gdi32.dll   
76a40000 76adb000   comdlg32 comdlg32.dll
76ae0000 76c33000   user32   user32.dll  
76cd0000 76d11000   sechost  sechost.dll 
76d80000 76f08000   crypt32  crypt32.dll 
77030000 7719e000   ntdll    ntdll.dll   
771f0000 77261000   msvcp120 msvcp120.dll

**Comment by ivellioscolin** [comment]
ok issue happens in libgit2/iterator.c. Will submit fix see if can be merged.

**Comment by ivellioscolin** [comment]
Can be fixed in libgit2.
https://github.com/libgit2/libgit2/pull/3585

**Comment by ivellioscolin** [comment]
Root cause addressed...

https://github.com/libgit2/libgit2/issues/3588

**Comment by ivellioscolin** [comment]
Re-title to describe the real issue..

**Comment by ivellioscolin** [comment]
Fixed in https://github.com/libgit2/libgit2/pull/3619

**Comment by ivellioscolin** [comment]
Issue has been fixed in libgit2 v0.24.0.
https://github.com/libgit2/libgit2/releases/tag/v0.24.0

**Comment by damieng** [comment]
Getting git-utils onto 0.24.0 is out for PR at https://github.com/atom/git-utils/pull/71
