### ISSUE TITLE
run python

### ISSUE THREAD

**Issue by kaktoos81** [atom/atom#10499]
hi 
i can not run python in atom
i install python-runner and script but it does not run again
anybody can help me?
i use windows 10 and last version of atom

**Comment by mnquintana** [comment]
Sorry you're running into trouble! For support questions like this (particularly with community packages like python-runner or script) you'll have better luck asking on Slack or [Discuss](https://discuss.atom.io). Since this repo is just for issues with Atom core, I'm going to close this out.
