### ISSUE TITLE
OSX multiple desktop change bug

### ISSUE THREAD

**Issue by munkacsimark** [atom/atom#10495]
After changing between desktops sometimes Atom freeze. I get "Atom not responding" message, but after rechanging desktops it works again.
- OSX 10.11.2
- Atom 1.4.0

I can't describe how to reproduce the issue, it happens randomly.

**Comment by jllodra** [comment]
Same issue here. Atom randomly freezes when going back to it when it's in another desktop. To unfreeze it, I have to 1) wait or 2) go to another desktop and then go back to atom.

* OSX 10.11.3
* Atom 1.4.3

Frustrating. Happens in all mac computers I have. Any help I could provide, just ask.

**Comment by latusaki** [comment]
Not sure if my issue is the same. When I change between desktops, occasionally Atom will stop receiving input (click/typing as no effect), until I minimize (using cmd+H) and maximize it again. This used to happen on older versions as well.

Atom 1.5.3
OSX 10.11.3

**Comment by chrisvfritz** [comment]
I can also confirm this bug on multiple (more than a dozen) OS X computers. The problem does not happen consistently, but something that's worth noting is that Atom _does_ still receive input. Both keyboard and mouse input can change Atom's internal state - those state changes simply don't result in updates to the UI.

For example, if I type a bunch of words while Atom appears frozen, then switch away to another Desktop/Space and back again to fix it, I can see that the words I typed are there. And If I click around the sidebar or tabs to switch files, I can see real-time changes to the window's title bar.

While it does happen inconsistently, it seems to occur about once per hour of use on any multi-Desktop/Space environment.

**Comment by latusaki** [comment]
+1 on above comment. Changes will appear either after minimizing and restoring window, or after changing to another desktop and back.
