### ISSUE TITLE
Main page Installer (Not Working

### ISSUE THREAD

**Issue by cgoss** [atom/atom#10498]
The download on the main page does not work.

**Comment by mnquintana** [comment]
Sorry to hear you're running into trouble – which OS were you downloading for?

**Comment by cgoss** [comment]
Windows 7 or 8.1 64 bit

**Comment by cgoss** [comment]
It is either for window 7 or 8.1 that the install is failing on.


On Wed, Jan 20, 2016 at 9:17 PM, Colin G <colin.goss@gmail.com> wrote:

> Windows 7 or 8.1 64 bit
> On Jan 19, 2016 10:33 AM, "Machisté N. Quintana" <notifications@github.com>
> wrote:
>
>> Sorry to hear you're running into trouble – which OS were you downloading
>> for?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/atom/atom/issues/10498#issuecomment-172943824>.
>>
>


-- 
Thanks

Colin Goss

**Comment by JedBartlett** [comment]
Is this, perchance, related to: https://github.com/atom/atom/issues/10383#issuecomment-184585696 ?

I'm getting the same error as was mentioned in that case when attempting to run the installer on the main page. (presently Version 1.5.3). 

**Disabling McAfee Real-Time Scanning seems to allow the installer to continue and launch Atom just fine**.

The stack trace produced by SquirrelSetup is attached.
[SquirrelSetup.txt](https://github.com/atom/atom/files/132136/SquirrelSetup.txt)

I'm running:
Windows 10 Home, Version 1511, OS build 10586.104, 16GB ram, 64bit.
McAfee Anti-Virus and Anti-Spyware Version 18 (Build 18.0.7058)

**Comment by aviadpines** [comment]
I have Windows 8.1, this is my work comp so I cannot disable McAfee. Is there no workaround for this?

**Comment by 50Wliu** [comment]
@cgoss can you upload `%localappdata%\atom\SquirrelSetup.log` here please?

@avladpines Currently there is no workaround other than downloading the `.zip` file, though the situation should improve in the future as more AV vendors recognize Squirrel as "safe".

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/10498#issuecomment-214871722. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
