### ISSUE TITLE
atom version 1.4.0: makedown syntax highlighting issues

### ISSUE THREAD

**Issue by 521xueweihan** [atom/atom#10493]
When the MakedownFile has '\' symbol,
the next row content has problem with syntax highlighting.
For example:
``` makedown
row1 ### output: \*.\*
row2 ### hello
```                  
Row2 has problem with syntax highlighting.

**Comment by linlingyu** [comment]
你是猴子派来的逗比吧？你写成中文的，老外能看得懂啊～

**Comment by havthgem** [comment]
I wanted to translate, but she did not express clearly.

I guess she meant is __"\" match had issue for edit markdown__.

**Comment by 521xueweihan** [comment]
@havthgem 谢谢你

**Comment by havthgem** [comment]
@521xueweihan 不客气，不过你在 example 中没有显示 `\` 啊，你为什么不使用代码块来表现你的例子呢？

**Comment by 521xueweihan** [comment]
@havthgem 你说的对，已改

**Comment by 50Wliu** [comment]
@521xueweihan Do you mean **Markdown**, and not Makedown?

是不是 **Markdown** 出了问题，不是 Makedown?
