### ISSUE TITLE
Cannot convert/re-encode file to UTF-8 from another encoding

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#10497]
Steps to repeat (Atom 1.4.0, OS X.11.2):

1. Open a non-UTF-8 file (e.g. UTF-16 LE) in Atom.
2. Try to save it as UTF-8.
3. Fail.

This is fundamental behavior for a text editor.

**Comment by alexchandel** [comment]
@50Wliu I should clarify that this is not "broken UTF8 to UTF-16 LE" behavior. The functionality simply does not exist at all.

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/atom/encoding-selector/issues/7. Please subscribe there for updates.

**Comment by alexchandel** [comment]
Wouldn't this require modifying Atom's Save As dialog, to implement this in the canonical OS X way?
