### ISSUE TITLE
Some situations are slow

### ISSUE THREAD

**Issue by magiclen** [atom/atom#10502]
I found some situations would make atom slow (er than other editors).

1. Open atom
2. Many characters in a single line
3. Many characters in Markdown file while previewing
4. Loading a file which has many lines

**Comment by mnquintana** [comment]
Thanks for the report! :smile: These have all been reported already, in #979, https://github.com/atom/markdown-preview/issues/197, and https://github.com/atom/atom/issues/8864, respectively.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) for a guide on reporting bugs, including searching for duplicates.
