### ISSUE TITLE
ES6 Files In Core Not Being Transpiled Prior To asar Creation

### ISSUE THREAD

**Issue by joefitzgerald** [atom/atom#10509]
The only reason this works is because `babel-require` is being used. This may have performance implications as more ES6 finds its way into core.

`linter-eslint` breaks on master as a side effect of this, which exposes potential `linter-eslint` or `BufferedNodeProcess` issues: why is `linter-eslint`  or `BufferedNodeProcess` loading `git-repository-async.js` in the first place?

/cc @arcanemagus @thedaniel @joshaber @paulcbetts

**Comment by Arcanemagus** [comment]
Ah ha, traced it down I see?

**Comment by Arcanemagus** [comment]
Just an FYI so it gets mentioned here too, I'm guessing the reason "linter-eslint" loads `git-repository-async.js` is due to linter itself calling [`GitRepository::isPathIgnored()`](https://atom.io/docs/api/v1.4.0/GitRepository#instance-isPathIgnored).

**Comment by joshaber** [comment]
Ah interesting, thanks for tracking that down @Arcanemagus!

**Comment by joefitzgerald** [comment]
This is not resolved @joshaber.
