### ISSUE TITLE
search and replace with positive lookahead won't replace

### ISSUE THREAD

**Issue by gleasonj** [atom/atom#10500]
I am having trouble getting the replace functionality to work when using positive lookaheads (I have not tried the same problem with negative lookaheads). An example:

`some text to test11293898`

Using regex, case insensitive find: `(some text)([^0-9]+)(?=[0-9]+)`

This will properly match "`some text to test`" but no matter what is placed in the replace bar even "`asdfasdfasdf`" hitting replace will not actually replace text.

**Comment by lucas-barros** [comment]
Same issue as in [atom/find-and-replace#299 ](https://github.com/atom/find-and-replace/issues/299).
