### ISSUE TITLE
Atom make a mess of the home folder.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#10508]
Atom seems to be saving full copies of my source files into /tmp/ and not only is it doing that but it's not cleaning them up when it's done, after a days worth of editing, I ended up with close to a thousand files in my tmp folder from this.

**Comment by amytruong** [comment]
Heya! That's def weird. :grimacing: 
What OS and version are you on? What version of Atom? 

Can I reproduce it by opening Atom, making a new file, saving it, then closing Atom and checking my /tmp/ folder?

If not, do you have more steps I can follow to reproduce? Thank you! :smile:

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/10508#issuecomment-174786394. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
