### ISSUE TITLE
Cannot run `npm install` on atom. 403 response on node-v5.3.0-headers.tar.gz

### ISSUE THREAD

**Issue by tastycode** [atom/atom#10505]
Running on 

MacOSX;: 10.11.2 (El Capitan)
Node: v5.3.0

[nodegit] Everything is ready to go, attempting compilation
{ [Error: Command failed: /bin/sh -c "/Users/tastycode/workspace/atom/node_modules/nodegit/node_modules/.bin/node-gyp" rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 403 response downloading https://atom.io/download/atom-shell/v5.3.0/node-v5.3.0-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/tastycode/workspace/atom/node_modules/nodegit/node_modules/node-gyp/lib/install.js:244:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/tastycode/workspace/atom/node_modules/nodegit/node_modules/request/request.js:951:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:421:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:311:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/Users/tastycode/.nvm/v5.3.0/bin/node" "/Users/tastycode/workspace/atom/node_modules/nodegit/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/tastycode/workspace/atom/node_modules/nodegit

**Comment by nfantone** [comment]
Similar thing happening to me, but with:

```
403 response downloading https://atom.io/download/atom-shell/v4.3.1/node-v4.3.1-headers.tar.gz
```

Can't build on Linux Mint 17.3, node 4.3.1.

**Comment by nfantone** [comment]
@joefitzgerald @thedaniel FTW, I deleted the project and cloned it again and it started working. So the problem was fixed for me.

**Comment by ggreer** [comment]
If you get this error, remove the line `disturl = https://atom.io/download/atom-shell` from `.npmrc` and retry. Be sure to put it back in after `npm install` is finished.
