### ISSUE TITLE
Unsaved untitled buffers don't survive an OS crash

### ISSUE THREAD

**Issue by ekantola** [atom/atom#10516]
Unsaved buffers in Atom 1.4.0 (Windows) don't seem to get restored in case of an OS hard reset or equivalent, even though they AFAIK should (ref: https://github.com/atom/atom/issues/942). Gracefully quitting the editor doesn't have the same problem.

How to reproduce:
- Have unsaved untitled buffers present and with some content
- Power cycle the computer (hard reset)
- Reopen Atom

**Comment by Ashkaan** [comment]
I can reproduce the same issue.

It would be great to knock this out along with [this](https://github.com/atom/atom/issues/10474).
