### ISSUE TITLE
Atom racer is not properly configured.

### ISSUE THREAD

**Issue by jamperry** [atom/atom#10510]
[Enter steps to reproduce below:]

1. Create new Rust file.
2. Save it.

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: Atom Core

### Stack Trace

Atom racer is not properly configured.

```
At undefined

undefined
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
build-cargo, v0.12.0
language-rust, v0.4.5
linter, v1.11.3
linter-rust, v0.3.0
racer, v0.17.2

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
This is a duplicate of https://github.com/edubkendo/atom-racer/issues/64 – feel free to subscribe there for updates.

**Comment by editree** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

khj4218@naver.com 님께 보내신 메일 <Re: [atom] Atom racer is not properly configured. (#10510)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------
