### ISSUE TITLE
An Update is ready to install. Atom is trying to add a new helper tool. / Error checking for Updates

### ISSUE THREAD

**Issue by JustusDeitert** [atom/atom#10515]
I installed Atom via Brew Cask (Version 1.3.2). I am Using OS X El Capitan Version 10.11.2
While I am using Atom this Alert is always popping up:

![update](https://cloud.githubusercontent.com/assets/6768651/12445812/d0e2ad5a-bf66-11e5-8c33-cdf62a03d1ca.png)
Even if i Type Username&Password and Click on "Add Helper" it keeps popping up.
## 

I tried updating Atom from within the Programm.
![screen shot 2016-01-20 at 11 10 58](https://cloud.githubusercontent.com/assets/6768651/12445908/676da784-bf67-11e5-8621-70b0ef87bd08.png)

But after a while this Error Message pops up.
![screen shot 2016-01-20 at 11 12 10](https://cloud.githubusercontent.com/assets/6768651/12445967/b0feeaca-bf67-11e5-9406-920a43fdb975.png)

**Comment by missioeric** [comment]
I get the same issue every time I open atom.

**Comment by cadejscroggins** [comment]
I'm on OSX 10.11.6 (15G31) and am getting the same thing.

**Comment by Alberto-Vega** [comment]
Hi, same here MacOS 10.12.2 atom 1.12.6 and get prompted to update every single time I open Atom. Thanks for your time :)

**Comment by imranismail** [comment]
how do i fix this?

**Comment by cs-miller** [comment]
installed from atom.io, having the same problem

**Comment by timgavin** [comment]
MacOS 10.12.3 and Atom 1.13.0. Same problem with "An update is ready to install..." message.

**Comment by SixCupsofCoffee** [comment]
Having same issue (macOS 10.12.3, Atom 1.14.3 x64, installed from atom.io). Some additional info:

Atom claims I have an update. I click on the squirrel, it says Downloading Update, which never finishes. Instead, the helper tool popup shows on the screen, and if I dismiss it by pressing Cancel, in the Atom update screen I get this: 
<img width="523" alt="screen shot 2017-02-28 at 10 14 48 pm" src="https://cloud.githubusercontent.com/assets/17645705/23444482/6848d10c-fe03-11e6-8de0-f3a09ea936e8.png"> 
If I then press "Check now" again, I get a popup telling me Atom is up to date.

**Comment by sharphosting** [comment]
I deleted Atom and reinstalled which seems to have fixed it. All my settings were kept.

**Comment by rostag** [comment]
It looks like the solution has been found here: https://github.com/atom/atom/issues/7058
