### ISSUE TITLE
encoding error than UTF-8 cahrset

### ISSUE THREAD

**Issue by webhacking** [atom/atom#10512]
does not working on my computer(Win10).  input Korean characters(e.g ??<?)
how can i fixed?

**Comment by lee-dohm** [comment]
Are you asking for some other character encoding to be supported other than UTF-8?

**Comment by Zireael07** [comment]
I think he's saying Korean characters aren't showing up in other encoding than UTF-8.

**Comment by webhacking** [comment]
fiexd.
`.editorconfig` 
```ini
charset = utf-8-bom
```
