### ISSUE TITLE
atom command from command line should open enclosing folder

### ISSUE THREAD

**Issue by codysherman** [atom/atom#10525]
The ability to do atom [files] from the command line is a really neat trick, however I find the most of the time, I'm inside of the folder already, such as for doing git commands, etc. Why not have the command 'atom' by itself open the folder I'm already inside of, instead either opening whatever last atom windows were left open or a blank file, as is the current functionality?

Example: I'm in ~/Projects/my-git-project inside the terminal. If I run the command 'atom' it should do the same command as if I were in ~/Projects and ran 'atom my-git-project'.

**Comment by benogle** [comment]
This used to be the case, but it was changed to allow `atom` to start the app in a similar fashion as the clicking the dock icon. We changed it so there was a way to restore all state from the command line.

**Comment by codysherman** [comment]
Is there a command that replaces the previous functionality?

**Comment by mnquintana** [comment]
@codysherman You can just run `atom .` to open the current folder in Atom (which is standard for all CLIs)

**Comment by codysherman** [comment]
Ah should have thought of that! Thanks so much!
