### ISSUE TITLE
Can't copy a file name from Project Find Results

### ISSUE THREAD

**Issue by apuchkov** [atom/atom#10521]
On a find results screen I can select a file name, but If I try to copy it with `ctrl + c` or `ctrl + insert` nothing gets copied into a clip buffer.

**Screenshots and GIFs**
![screenshot_1](https://cloud.githubusercontent.com/assets/150003/12459571/7cdd5f90-bf7d-11e5-9bf3-364244e4f27b.png)

**Atom version:** 1.4.0
**OS and version:** Windows 10

**Comment by benogle** [comment]
This issue was moved to atom/find-and-replace#652
