### ISSUE TITLE
Column Count differs between tab and space characters

### ISSUE THREAD

**Issue by Wlkrshrpe** [atom/atom#10522]
Working in a .jade template, the column position can be very important to keep track of. I had an indentation error come back from the compiler, so I had to go through the file line by line in order to compare the position of my line indents.

What I noticed, is that the column count can be different depending on if user uses a tab vs a space.

So for example, 
![screen shot 2016-01-20 at 4 25 59 pm](https://cloud.githubusercontent.com/assets/12034199/12463615/8839ad20-bf92-11e5-9048-f291c4c788b4.png)

you can see from this that line 9 begins at column 3

however if I backspace the tab character (which is the whitespace char leading line 9) -- and then replace this whitespace char with spaces (spacebar), then column position is 4, not three

![screen shot 2016-01-20 at 4 27 22 pm](https://cloud.githubusercontent.com/assets/12034199/12463641/b56ba67c-bf92-11e5-9bee-8af61aa01632.png)

so you can see i did the aforementioned on line 8, deleting tab character and replacing with spacebar spaces... 

col position is 4 under this use case

please address this so that column count is found uniformly, it would make it much easier to troubleshoot 
files where indentation and whitespace affect whether or not code is runnable

**Comment by Wlkrshrpe** [comment]
Or maybe there is some method to the madness here? Like maybe this is intentional to let user know when a tab vs spaces are used? Turning on invisible characters does help a lot my personal indent sorting issue, but i thought i would make an issue here anyway, as it seems counter-intuitive to have column position changes based on whitepsace char

**Comment by 50Wliu** [comment]
Closing in favor of atom/status-bar#170.
