### ISSUE TITLE
Auto indent not correct when moving lines up or down

### ISSUE THREAD

**Issue by bkentdev** [atom/atom#10524]
When you move a group of selected lines up or down, Atom auto indents them to where it thinks they should fit in the code and it is not always correct. It should have the option to disable this flavor of auto indent.

**Comment by amytruong** [comment]
If you go into Settings View and scroll down to Editor Settings, we do have an option to turn off Auto Indent and Auto Indent on Paste. Let us know if that solves your problem. :grimacing: *crosses fingers*

**Comment by benogle** [comment]
Also, can you be more specific about your atom version and what languages you're having problems with?

**Comment by brandonk3nt** [comment]
Hey Amy,

Thanks for responding, that was quick! So I tried those settings earlier
and they don't affect the auto indent reformatting when using the hotkeys
(Ctrl + Option + up/down). Even with those two options turned off it still
will reformat indentation and not always for the better. It's particularly
noticeable when you highlight a block of code that has specific indentation
and move it up or down. I love Atom and this is my only issue with it.
Thanks for your help!

Brandon Kent | Software Engineer
www.brandonk3nt.com
Email: brandonk3nt@gmail.com
Cell: 480.788.1301

"A journey of a thousand miles begins with a single step."

**Comment by brandonk3nt** [comment]
​Hey Ben,

Thanks for reaching out- I just responded to Amy but here's some more
details that will hopefully help to reproduce the bug. I am on a Mac
(running El Capitan) and running Atom v1.4.0. I am code in CoffeeScript,
which uses indentation vs punctuation to define blocks of code (like
Python). The bug occurs when using the hotkeys to move selections up or
down (Ctrl + Command + up/down-arrow). ​It is particularly noticeable when
you highlight a chunk of code >5 lines which has specific indentation, and
move it up or down through other sections of code. Hope this helps and
please let me know if I can do more to help, thanks!


*Brandon Kent* | Software Engineer
E: brandonk3nt@gmail.com <brandonkent@gmail.com>
T: 480.788.1301
brandonk3nt.com <http://www.brandonk3nt.com/>

*"If there's one attribute that everyone could adopt from the skateboarding
community, it's to have a desire to learn something new- to try, and fall,
and get up again- and repeat that process a thousand times until you
eventually get it right."*

**Comment by benogle** [comment]
Noted, yeah, it's really bad at auto indenting chunks for whitespace delimited languages.

**Comment by tomekwi** [comment]
Hi, I’m also having trouble with this feature when coding in [Elm](http://elm-lang.org) – another language with significant whitespace.

As @amytruong suggested:
* I tried switching off *Auto Indent*. That did the job, but it also turned off indenting every new line. The latter is a super useful feature – I can’t imagine coding without that.
* I tried switching off *Auto Indent on Paste*. Unfortunately, that didn’t work.

**Comment by maackle** [comment]
I just ran into this problem too. Here's a simple case:

```py
def foo():
    if True:
        print("fizz")
    print("buzz")
```

If I highlight lines 2-4 and move them up or down, `print("buzz")` gets indented to the same level as `print("fizz")`, totally changing the program.

**Comment by radiac** [comment]
I have also just had the same python issue. This really should be an option, and probably be off by default, at least for languages which have significant whitespace. There is further discussion of this issue on the original PR (#9104), with a custom command that solves it for me.

**Comment by code-tree** [comment]
I'm finding this feature addition is almost always actually a hindrance to me. When I move code, it is extremely important it stays as it is (especially in Python, where indentation affects everything). After moving blocks of code it takes me a while to check if anything has changed, and to correct the indentation, where as a simple tab (or shift tab) would normally fix things after a move.

But I do appreciate the effort in trying to add a new feature, and I think it could be useful, but only (in my personal opinion) if **_no indentation changes within the selected lines_**

i.e. If the selected (multi-line) code is auto-indented less/more, indent it all equally (not just some lines of it).

**Comment by mgruner** [comment]
+1

**Comment by RsD0p9BK** [comment]
Just used **Ctrl+Command+up/down** and **cmd + z**

![may-30-2016 10-31-01](https://cloud.githubusercontent.com/assets/2192809/15640468/bc3cedb4-2651-11e6-8874-5eae168696c6.gif)

**Comment by mxmlnkn** [comment]
@RsD0p9BK Doesn't work for me, also not very high usability.

**Comment by RsD0p9BK** [comment]
@mxmlnkn Try to add empty string at the end of file (Eight on my picture)

**Comment by adambuczynski** [comment]
Here's another way to reproduce weird indentation behaviour when moving lines of code up:

1) Create a block comment like so with two lines of code underneath it:

```js
/**
 * Dependencies
 */
let moment = require('moment');
let mongoose = require('mongoose');
```

2) Try to move the last line up. You will end up with:


```js
/**
 * Dependencies
 */
 let mongoose = require('mongoose');
let moment = require('moment');
```

Notice the one space added indentation, and what's even stranger, the added space actually gets selected.

Demo:

![ss](https://www.dropbox.com/s/dbz0j0tem1lwtb4/comment-error-3.gif?dl=1)

This is with Atom 1.10.0-dev-e5a3c9e, and this joins several other comment block/indentation related issues like:

https://github.com/atom/atom/issues/11995
https://github.com/atom/atom/issues/5362
https://github.com/atom/atom/issues/7256#issuecomment-224580507

**Comment by Zerim** [comment]
Also reproduces for me on Atom 1.9.7, especially noticeable while writing and moving around blocks of JSX.

**Comment by Benibur** [comment]
I have the same problem, 
Exemple on Atom 1.8.0 on ubuntu 16.04, plain text, utf8:
```
first list
    . line 1.1
    . line 1.2
second list
    . line 2.1
    . line 2.2

```
Ctrl + down on line 1.2
```
first list
    . line 1.1
second list
. line 1.2
    . line 2.1
    . line 2.2
```
This is really very boring, i am about to switch to ST3 just for that because it breaks all my indentation each time I move a line (dozens of times a day...). What a pity...
Ben

**Comment by code-tree** [comment]
@Benibur the hack mentioned in [this comment](https://github.com/atom/atom/pull/9104#issuecomment-166568480) works very well for the time being.

This issue is flagged as `more-information-needed`, but what exactly is needed more than already mentioned?

**Comment by chris-martin** [comment]
The relevant function is https://github.com/atom/atom/blob/1a039df6435ba0d3fc2eead8e1b6e7a0cf0ebf9b/src/text-editor.coffee#L1113

Could we work around this with a plugin to add alternative versions of those functions?

**Comment by adamreisnz** [comment]
If it were written in normal javascript/ES6+ I'd happily take a look, but alas, I'm allergic to Coffeescript ;)

**Comment by LydiaF** [comment]
Hi there,

I am using YAML and I have this problem. It works as I would like it when Auto Indent is false in Editor Setting, but I would much prefer to keep that setting turned on.

![moving lines](https://cloud.githubusercontent.com/assets/10000865/25437052/08e2241e-2a8d-11e7-9bf4-100034d598a6.gif)

It would make a huge difference to me if there was a setting to turn this behaviour off!

Thank you :)

**Comment by oneschilling** [comment]
I am having the same issue. An option to turn auto indentation off for moving lines up and down would be great.

**Comment by corysimmons** [comment]
Atom team: Why use auto-indent after the move? Auto-indent is always error prone in every editor.

- Just store all the selected characters (like whitespace) in tmp memory.
- If their is no selection, just store the entire line in tmp memory.

What's the technical hold up on this?

**Comment by Signum** [comment]
Well, any other editor I have seen so far (that supports moving of lines) handles that well. Only Atom tries to auto-indent during a move. So that's just unexpected behavior.

Moving that way makes it easier visible in my opinion. You move something until it fits perfectly. You do not have to trim or add empty lines before or after a block. It's WYSIWYG.

But if it's terribly hard to disable auto-indent while moving lines then perhaps it's really not worth fixing it.

**Comment by DiThi** [comment]
It's ironic that it's written in Coffee Script. It **destroys** the indentation on Coffee Script!!

I'm OK with it moving the whole block left or right. But moving individual lines of code makes it USELESS for most cases.

Extremely simple case:

```coffeescript
    if true
        1
    if false
        2
```

turns into

```coffeescript
    if true
        1
        if false
            2
```

And the worst part is that sometimes it happened to us without noticing, introducing bugs.

**Comment by gardwired** [comment]
please fix. autoindent shouldn't pertain to moves.

**Comment by critcha** [comment]
Dear developers: I believe you can fix this unexpected behavior deleting the following line from the definition of movelineup and movelinedown in TextEditor.js
`      if (this.shouldAutoIndent()) this.autoIndentSelectedRows()`

**Comment by lawrence-dol** [comment]
Yes, I can still reproduce in the latest version (1.16.0), and it's INCREDIBLY annoying. It also, badly auto-indents when I edit an existing line, behavior which drives me completely bonkers.

What I would really like is the option to auto-indent to current indentation level on insertion of a new line ONLY. Just that. Nothing else. Nothing fancy. Just maintain the current indentation upon line insertion. While I know I can turn off indentation altogether, the indentation on insertion of a new line is incredibly useful. Essentially, you've borked the most useful auto-indent behavior by trying to make it too fancy.
