### ISSUE TITLE
Opening directory with \..\ does not resolve path name

### ISSUE THREAD

**Issue by Xcodo** [atom/atom#10535]
I noticed today that launching Atom on Windows with a folder path including a folder above (`..\`) does not resolve the path name to remove the `..`s, for instance running the command

`atom.exe C:\Users\Mark\Desktop\ProjectFolder\SubFolder\..\SubFolder\File.txt`

Gives a window with the title `C:\Users\Mark\Desktop\ProjectFolder\SubFolder\..\SubFolder\File.txt`:
![atomrelativefolderfile](https://cloud.githubusercontent.com/assets/6715247/12476171/7905114a-c01f-11e5-8dcd-482994e39380.png)

That's not too much of a problem.

However, if you open a directory as a project from the command line with the last part of the path as a `..`, then it gets a bit messier. Running

`atom.exe C:\Users\Mark\Desktop\ProjectFolder\SubFolder\..\`

Opens the `ProjectFolder` as a project, but with the title "..", which isn't so nice.
![atomrelativefolder](https://cloud.githubusercontent.com/assets/6715247/12476255/f5f2d1c4-c01f-11e5-8d88-9f6dab44f624.png)

Could atom check for this and resolve the path/folder name?

A usage case for this is a software project where you want to launch Atom from another the IDE which makes the IDE project path (for instance in the source sub-directory) available as a parameter, but you want to launch the folder above (which contains the documentation directory and source directory) in Atom.

*Tested on Windows 7 64-bit with Atom 1.4.0*

**Comment by damieng** [comment]
This and https://github.com/atom/atom/issues/8221 could be solved by resolving or nomalizing the path name before opening.

**Comment by damieng** [comment]
Appears to now work in master although not sure which change resolved it.

**Comment by Xcodo** [comment]
Yes, confirmed that's now working.

IDE integration is much nicer for me now :+1:
