### ISSUE TITLE
Find and Replace in large buffer is very slow

### ISSUE THREAD

**Issue by ypresto** [atom/atom#10531]
It seems to rebuilding tokenized buffer on every operation in transaction.

![image](https://cloud.githubusercontent.com/assets/400558/12474497/019feaf4-c05f-11e5-94b9-1e07fd3b66fa.png)

It took 16 secs to replace 920 `\n`s to newline on 15-inch MacBook Pro Retina Late-2013.

**Comment by benogle** [comment]
This issue was moved to atom/find-and-replace#653
