### ISSUE TITLE
SyntaxError: Unexpected end of input 

### ISSUE THREAD

**Issue by maksymddd** [atom/atom#10532]
Hello. I haven't done any changes to atom (installing new packages etc) in a while. But today I've got some interesting bug when I opened it. win10
![atom-bug](https://cloud.githubusercontent.com/assets/6981941/12475467/6b4fc51e-c023-11e5-8355-de81dd702c3c.png)

**Comment by stevenaldinger** [comment]
I'm brand new to the community, so try to excuse the noob-spewing but can you post the code that the trace refers to?
I have limited experience but unexpected end of input almost always seems to mean an open parenthesis/curlybrace without its matching close.

**Comment by Zireael07** [comment]
Duplicate of #10015.

(Can someone rename the original issue so that people CAN find it when searching?)

**Comment by maksymddd** [comment]
This solution worked for me. Thank you.
https://github.com/atom/atom/issues/10015
