### ISSUE TITLE
"#" character causes issue with syntax coloring

### ISSUE THREAD

**Issue by JustinDFuller** [atom/atom#10538]
Atom version 1.4.0, windows 8 using vmware fusion 7

theme: all theme's I've tested so far include Atom Dark, Atom Material, and One Dark , I've also tested with the corresponding syntaxes. I've also tested with base16 tomorrow syntax. 

Basically what happens is that the color coding of any document (html, JS, ANYTHING) works fine until you include a "#" as part of a string. Once you include it as part of a string all the color coding afterwards is messed up. By messed up I mean that it no longer seems to be able to differentiate between the html element tag, the attribute names, the strings they contain. They are all the same color. 

Below is a screenshot, you can see where it gets messed up on the 10th line where there is a "#".

![screen shot 2016-01-21 at 07 47 07](https://cloud.githubusercontent.com/assets/11914897/12480842/37648204-c013-11e5-9009-882e724d7bcc.png)

I've attached another screenshot to show how removing the "#" will fix the issue.

![screen shot 2016-01-21 at 07 48 32](https://cloud.githubusercontent.com/assets/11914897/12480875/6c42c2a6-c013-11e5-969d-c0ae7a614f84.png)

my packages: 

C:\Users\Justin Fuller\.atom\packages (21)
├── angularjs@0.3.4
├── atom-beautify@0.28.21
├── atom-material-syntax@0.2.10
├── atom-material-ui@0.8.0
├── atom-minify@0.7.1
├── auto-detect-indentation@0.4.2
├── autoclose-html@0.19.0
├── autoprefixer@3.1.0
├── color-picker@2.0.14
├── csscomb@0.3.1
├── file-icons@1.6.14
├── fold-functions@0.4.3
├── highlight-selected@0.11.1
├── KeyCount@0.1.1
├── language-cfml@0.11.0
├── linter@1.11.3
├── linter-csslint@1.2.0
├── linter-htmlhint@1.0.0
├── linter-jshint@1.2.2
├── minimap@4.19.0
└── minimap-highlight-selected@4.3.1

**Additional information:**

* Problem can be reproduced in safe mode: [No because of no theme syntax in safe mode]
* Problem started happening recently, didn't happen in an older version of Atom: [Only version i've used]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* Problem happens with all files and projects, not only some files or projects: [Yes]

This is the first issue I've ever submitted so If I've missed something please just let me know! I put this in this repo since it is happening across all themes, not just a few of them.

**Comment by 50Wliu** [comment]
@JustinDFuller Are you sure this happens to *all* languages, not just HTML/JS?  Can I please see an example of it breaking in eg Python or C?  Thanks.

(Also, you should be able to reproduce the issue in safe mode - Atom Dark is loaded in that case).

**Comment by JustinDFuller** [comment]
@50Wliu So this doesn't happen in something like CSS, but it happens in HTML, JS, coldfusion so far. That's all I've tested. So yeah I shouldn't have said all languages. I couldn't get atom dark to work in safe mode, but I can try again. Should I have to do anything special to get it to work? All text was just showing up white.

**Comment by damieng** [comment]
Unable to reproduce this on master even after installing most of those plugins and switching to the material syntax theme. Do you still get this problem?

![image](https://cloud.githubusercontent.com/assets/118951/14756348/7513a760-089d-11e6-92dc-7df747333082.png)

**Comment by damieng** [comment]
No response, closing issue. Please re-open if persists.
