### ISSUE TITLE
Syntax highlighting for inline HTML

### ISSUE THREAD

**Issue by Groschenroman** [atom/atom#10536]
As it is to be seen in the screenshot, inlined HTML syntax in Angular components template blocks is not highlighted.
Is there some snippet/package or any existing way to fix this?

![screen shot 2016-01-21 at 10 51 42](https://cloud.githubusercontent.com/assets/7312890/12477028/69f5a3a0-c02d-11e5-84ed-50c729d13586.jpg)

**Comment by mnquintana** [comment]
Angular syntax is not supported by Atom out of the box – [you would need to install some community package](https://atom.io/packages/search?q=angular) to add full Angular syntax highlighting support.

In the future, you'll have better luck asking support questions like this on [Discuss](https://discuss.atom.io) or Slack – GitHub Issues is really just meant for bugs or feature requests. See [the Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute) for more info.

:beers:
