### ISSUE TITLE
Close all tabs without closing the window

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/atom#10534]
Previously, I often hold ⌘W to close all tabs. But in 1.4.0 it seems too clever. If you hold ⌘W then it will end up closing the window, which I guess is not many people want. Could Atom bring back the old behavior? (Or, am I missing some new shortcut key introduced in 1.4.0?)

**Comment by mnquintana** [comment]
Take a look at https://github.com/atom/atom/issues/10410#issuecomment-171663010
