### ISSUE TITLE
Git status is not directory-relative

### ISSUE THREAD

**Issue by perry-mitchell** [atom/atom#10542]
When working with a directory of git repositories, all git accessories in Atom (including that of plugins) do not find the repository of currently open files.

I would say that it's fair to expect that git tasks, operating on currently opened files etc., would know to search upwards in directories to find the relative git repo. Having a separate atom window for each of my many projects is cumbersome.

Given the layout:
```
/home/projects
    /git-project-1
    /git-project-2
```

Git-related tasks will not function when /home/projects is open in Atom. I would have to open both separately to work on them with the built-in functionality.

**Comment by mertzt89** [comment]
This may be related to #2203

**Comment by perry-mitchell** [comment]
That's correct - I wasn't able to locate it.

This is a duplicate.
