### ISSUE TITLE
Menu bar drop down shows up on secondary (left) monitor

### ISSUE THREAD

**Issue by minsis** [atom/atom#10546]
I have a two monitor setup. Left monitor 22" is the secondary monitor. Right monitor 27" is the primary monitor and where I mostly use Atom.

When the window is in a certain position on the right monitor the drop down menu will be slammed to the very right edge of the left monitor. If I move Atom further from the left monitor the drop down menu will work just fine. If Atom is on the left screen entirely the drop down menu works fine. It seems that about 4" from the very left of the primary monitor the drop down menu works fine. No other applications are doing this. Ran it in safe mode with same results.

The edge of the task bar is the cutoff between the left and right monitors. The drop down menu's are cut off half way at the bottom, I'm pretty sure this is just due to the pressing of the print/screen button; the full menu displays.

Drop down menu showing up on left screen.
![left](https://cloud.githubusercontent.com/assets/11248197/12502010/c2962b2c-c089-11e5-92ba-abd1cd4e5861.jpg)

Drop down menu showing as it should when Atom is moved further to the right on the right monitor.
![right](https://cloud.githubusercontent.com/assets/11248197/12502030/ee1a94b8-c089-11e5-83cc-cc34366cc77b.jpg)

OS: Ubuntu 15.10
Desktop: Mate 1.10.2 (Also was happening on KDE Plasma5 same setup)
GPU: nvidia GeForce GTX 550 Ti
Driver: 352.63

Atom: 1.3.1
├── MagicPython@0.5.7
├── kobalt@0.5.0
├── kobalt-ui@0.4.0
├── kobalt-ui-mod@0.4.0
├── language-cisco@1.4.0
└── latex@0.28.2

**Comment by 50Wliu** [comment]
Refs #8921, #3415.

**Comment by ValheruPL** [comment]
50Wliu It's not the same issue.

**Comment by ValheruPL** [comment]
I have found solution ! Lol.

You have to add two lines to the "screen" section of nvidia

    Option         "nvidiaXineramaInfo" "False"
    Option         "nvidiaXineramaInfoOverride" "False"

So, this is my screen section of nvidia:

`Section "Screen"
    Identifier     "nvidia"
    Device         "nvidia"
    Monitor        "Monitor0"
    DefaultDepth    24
    Option         "AllowEmptyInitialConfiguration"
    Option         "nvidiaXineramaInfo" "False"
    Option         "nvidiaXineramaInfoOverride" "False"
    Option         "eDP-1" "Monitor0"
    Option         "HDMI-0" "Monitor1"
    Option         "BaseMosaic" "True"
    Option         "MetaModes" "GPU-0.DFP-0: 1920x1200+0+0, GPU-0.DFP-0: 1920x1200+1920+0"
    Option         "ConstrainCursor" "0"
    Option         "nvidiaXineramaInfoOverride" "1920x1200+1920+0, 1920x1080+0+0+0+0"
    Option         "TwinView"
    Option         "Coolbits" "12"
    SubSection     "Display"
        Depth       24
        Modes      "nvidia-auto-select"
    EndSubSection
EndSection
`

**Comment by minsis** [comment]
Changing those nvida options didn't work for me.
