### ISSUE TITLE
After Clearing the Error in Visualforce Page Still showing In Errors list

### ISSUE THREAD

**Issue by naveenila1221** [atom/atom#10541]
Errors list is not cleared. Especially this is occurs with VF pages, but fine with Apex. how can I clear the errors plane

**Comment by damieng** [comment]
What is Visual Force and what is Apex? Can you provide more information and perhaps some screenshots?

**Comment by naveenila1221** [comment]
I have Integrated mavensmate with atom. Witch acts an interface between IDE and Salesforce. 
In salesforce we have Apex(Controller) and visualforce(View).

**Comment by lee-dohm** [comment]
@naveenila1221 From what I can tell, this behavior isn't anything to do with Atom itself and is provided by one or more community packages you have installed. You may want to determine which community package you have installed that isn't working the way you expect and contact the authors of that package. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the authors of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
