### ISSUE TITLE
Set Atom to have same number of columns when I reopen it

### ISSUE THREAD

**Issue by corysimmons** [atom/atom#10545]
When I close Atom and reopen it, I'm back to 1 column...

Is there any way to permanently set it to show the last columns I had when I closed it? Really annoying having to re-set these when I open it each time...

**Comment by corysimmons** [comment]
As a sidenote, when I split panes, it moves the current tab to that pane (okay) but leaves that tab open in the same pane it was in, so it basically duplicates the tab...

**Comment by amytruong** [comment]
Thanks for the feedback! I'm going to label this as an enhancement. 

Currently, we do have a setting in Settings View where if you unselect it, the editor won't open as empty. It will open up with your current set of panes but only with saved files (not just an empty set of panes). It  if won't totally solve your problem but thought I'd share. 
![screen shot 2016-01-25 at 6 56 35 pm](https://cloud.githubusercontent.com/assets/10725993/12572070/420f44aa-c39c-11e5-8410-89bbfc4c96eb.png)

Regarding you second point, I do believe we have an issue open about it here. https://github.com/atom/atom/issues/4738

**Comment by corysimmons** [comment]
Hm, alright, thanks. Hope that PR gets in soon. :1234:

**Comment by 50Wliu** [comment]
#4738 has been merged and at the current pace of development should be available in Atom 1.6.0.

**Comment by corysimmons** [comment]
Cool. I hate to sound ungrateful, but it doesn't really matter anymore.

I fell in love with Atom when I first fired it up. It looked beautiful and a lot of it was intuitive.

After really trying to use Atom for a couple weeks and using about 5-10 plugins (Emmet... a few linters... I can't think of anything else), I went back to Sublime and will check out VSCode before too long.

Atom's ui (specifically plugin management) is amazing, but it's the slowest editor I've ever used (by far). It would frequently crawl when making edits to moderately sized documents and straight up freeze/crash on large documents (even without plugins).

I'm not sure what you guys can do to fix it, but you should halt all other development and dump all your resources into making Atom usable with official basic tools (autocomplete, linting).

You should reopen https://github.com/atom/atom/issues/10188 as a place to gather stolen ideas until Atom is usable. If it's too hard to fix and will take an exceedingly long time (or more likely just never get done), perhaps put a warning, instead of an expensive ad (money that could've gone towards development), on the Atom homepage that it's not ready for production use?

Salty about all these non-functional tools lately.
