### ISSUE TITLE
Cursor Disapears after Alt-TAB

### ISSUE THREAD

**Issue by zoffixznet** [atom/atom#10554]
I'm on Atom 1.4.0 on Bodhi Linux 3.1.1 (fork of Ubuntu 14.04, trusty), running inside VirtualBox on Windows7. I'm having the exact problem described at the start of Issue #3622.

The [screenshot in the third comment](https://github.com/atom/atom/issues/3622#issuecomment-56760573) demonstrates my issue exactly. The [workaround described in a later comment](https://github.com/atom/atom/issues/3622#issuecomment-73421592) did not help (perhaps new Atom has different selectors?).

If I quickly alt-tab back and forth multiple times, I can see the cursor (and the current-line highlight) appears for a few milliseconds, and every about 8 switchings back and forth, the cursor does show correctly.

To note: the cursor just disappears only visibly, but I can still type and I can see the highlight of the line number of the line the cursor is on move when I press Up/Down as well as braces get underlined when I move it horizontally.

**Comment by piotrze** [comment]
I have noticed the same on OSX 10.10.5 and Atom 1.4.0

**Comment by demhydraz** [comment]
Doesn't happen here. Arch Linux x86_64, w/ Atom 1.5.0-beta1, using Cinnamon 2.8

**Comment by zoffixznet** [comment]
Tried 1.4.1 and the 1.5.0-beta1, the issue is still present in both versions :(

**Comment by zoffixznet** [comment]
Some progress: I installed package `neon-cursor` and the issue went away. If I disable it to get back to the default cursor, the issue re-appears.

Perhaps this would give some clue as to what the issue is.

**Comment by tcr3dr** [comment]
I am seeing this issue, 10.10.5 and Atom 1.4.0. I installed https://github.com/thiagopnts/dyslexia to know when to click the window to regain focus after alt+tabbing to a fullscreen Atom window again.

**Comment by 50Wliu** [comment]
I cannot reproduce this on Ubuntu 16.04, Atom 1.9.0-dev-9175194.

**Comment by demhydraz** [comment]
No longer happening in 1.8.0-beta2.

**Comment by 50Wliu** [comment]
Is anyone who could originally reproduce this still seeing this?

**Comment by lee-dohm** [comment]
Closing due to lack of response. Please let us know if this reoccurs for anyone :grinning:

**Comment by deeperx** [comment]
@lee-dohm still happens here with os x el capitan. What do I need to send to you for you to reproduce it?

**Comment by amitdubey90** [comment]
I can reproduce the issue on Ubuntu 12.04 and Atom  1.0.11

**Comment by pcnate** [comment]
I was having the issue but I have hidden the tree view and have not had any issue since.
