### ISSUE TITLE
Add project Folder is not working on Windows

### ISSUE THREAD

**Issue by adrianmak** [atom/atom#10551]
Version 1.40

I licked the ‘Add Project Folder' on the sidebar, and select a folder.
Nothing was imported in Atom

**Comment by amytruong** [comment]
Thanks for letting us know about your issue. I'd love to get more information to see what the problem is.

What version of Windows are you on? Has this problem happened again? 
Maybe try it in safe mode?

**Comment by aggieben** [comment]
I don't know quite what the OPs problem was, but this is not working for me as well.  If I add a project folder, it sometimes replaces the folder I picked with my home directory.  It will briefly flash the folder I picked in the folder view, but then it will shortly (as in, < 1s) become my home directory.

**Comment by aggieben** [comment]
Aha, this is an Omnisharp issue.  Output just to help any other poor soul to stumbles into this issue:

![image](https://cloud.githubusercontent.com/assets/1321/12932892/e69fb270-cf4a-11e5-8f13-3f87f5eeccf4.png)

**Comment by damieng** [comment]
Apparently issue in Omnisharp.  Regular Add Project Folder on Windows is fine.
