### ISSUE TITLE
Feature Request "TODO" - Line highlight & anycase match

### ISSUE THREAD

**Issue by BryanARivera** [atom/atom#10550]
Currently when we write a todo comment we must write "todo" in uppercase and only the "todo" is highlighted.

Proposed changes:

1. Accept any combination of case.  "todo", "Todo", "tOdO", etc.

2. Highlight the entire line for better visibility.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/language-todo? Thanks!

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) for a guide on where to post issues, including searching for duplicates.

**Comment by BryanARivera** [comment]
@mnquintana  https://github.com/atom/language-todo/issues/40
