### ISSUE TITLE
Atom changed my markdown file to fit GFM automatically, which is NOT I want to save,what should I do?

### ISSUE THREAD

**Issue by Danceiny** [atom/atom#10559]
I want write markdown files with Atom, but the standard of markdown I want to use is not GFM. Therefore, if Atom changed my text to what I don't want,-- which is a huge waste of time,actually-- I can't use these markdown files normally. And I wonder whether there is some way to turn on/off this AUTO function.I really do not need it! I can only tolerate that it tell me what it wanna to change!
Following is the text I want:
```
 |  | A   | B   | C   | D|
|---| ----|---|---|---|
|A | 0.0 | 0.2 | 0.8 | 0.7|
|B | 0.2 | 0.0 | 0.9 | 0.8|
|C | 0.8 | 0.9 | 0.0 | 0.1|

```
and following is the version changed by Atom:
```
  | A   | B   | C   | D
- | --- | --- | --- | ---
A | 0.0 | 0.2 | 0.8 | 0.7
B | 0.2 | 0.0 | 0.9 | 0.8
C | 0.8 | 0.9 | 0.0 | 0.1
```

**Comment by 50Wliu** [comment]
@Danceiny Does this still happen in safe mode (`atom --safe`)?

**Comment by lee-dohm** [comment]
I can't reproduce this using Atom v1.6.0-dev-62c1f6a on Mac OS X 10.11.2. Here's what I did:

1. Launch Atom
1. Open a new file and save as `test.md`
1. Paste in the text from the "text I want" section of the original post
1. Save the file using <kbd>Cmd+S</kbd>

Expected and Actual: The text did not change

**Comment by Danceiny** [comment]
***Sorry for reply too late.***
*I run Atom 1.4.1 on Win 7 ultimate sp1, 64bit. *
And the amazing thing happens that it doesn't change my text, I just re-open the file a few days later without any difference than before ----- 
I wonder if the change is caused by the crush of related markdown packages which I installed last time? 
I have installed:
1. Markdown Preview
2. tidy-markdown
3.markdown-toc
4.markdown-writer
And when the change happens last time, I try to DISABLE some of these packages, and make no difference at that time.So I didn't cared this problem.
Now I doubt that. 
**After that, I shifted to safe mode, nothing goes wrong.**

**Comment by lee-dohm** [comment]
Yeah, I strongly suspect it was one of the packages you had installed. You can use the [package-cop package](https://atom.io/packages/package-cop) to help you determine which one ... or just use the built-in Markdown support in Atom :grinning:

Let us know if you have any more issues.
