### ISSUE TITLE
The editor has crashed (using atom-beautify on large file)

### ISSUE THREAD

**Issue by jsejcksn** [atom/atom#10556]
Just following orders:
<img width="517" alt="error" src="https://cloud.githubusercontent.com/assets/868251/12531628/2f826f5c-c1c5-11e5-9eae-f726d0270e3b.png">

Was trying to use [atom-beautify](https://atom.io/packages/atom-beautify) on [the mongodb example dataset](https://raw.githubusercontent.com/mongodb/docs-assets/primer-dataset/dataset.json), an 11.9 MB JSON file.

**Comment by benogle** [comment]
This issue was moved to Glavin001/atom-beautify#769
