### ISSUE TITLE
Atom is not signed using SHA256 hashes

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom#10567]
http://textslashplain.com/2016/01/19/sha-1-certificates-blocked-by-authenticode/

This will cause Atom problems with antivirus vendors. I tried to fix this myself, but signtool is abstracted as a script hidden on the Janky box. You need to add `/fd sha256` to the `signtool.exe` invocation

**Comment by niik** [comment]
I believe we also need to switch over to a SHA2 certificate, just resigning with `/fd sha256` won't cut it. I believe we have a cert lying around though. We just went through this with Desktop.

**Comment by 50Wliu** [comment]
Looks like this has been fixed in 1.4.2.
