### ISSUE TITLE
Searching failed

### ISSUE THREAD

**Issue by ugogon** [atom/atom#10565]
Hey, need your Help!
I cant search Packages/Themes in Atom anymore. The Output is very short. I have no clue what to do:
```
Searching for “Terminal” failed.Hide output…
Searching packages failed: Application error
```

I tried to install Term2 but I got some errors (Something like "VCBuild.exe" not found and node-gyp rebuild error)
and then I tried to fix it with some config changes:
```
npm config set msvs_version 2012 --global
```
as said here: http://stackoverflow.com/questions/14278417/cannot-install-node-modules-that-require-compilation-on-windows-7-x64-vs2012
and
```
npm config set python C:\Python27\python.exe
```
as said here: http://stackoverflow.com/questions/21562038/node-gyp-build-error-windows-x64

and some other sh*t i didnt remember.

That didnt help, but now I cant search anymore. I can install Packages (the featured ones).

I already tried:

Reinstalling
atom --safe

I run WIN 7 x64 Atom 1.4.0

THX 
a noob

**Comment by gregtyler** [comment]
[Package search is down too.](https://atom.io/packages/search?q=eslint)

Presumably related.

**Comment by yakaas** [comment]
Looks intermittent

**Comment by 50Wliu** [comment]
https://atom.io is currently having some trouble, which might be due to the recent blizzard in the Northeast (not sure where the servers are located).  The Atom team is aware of it already, but thanks for reporting!
