### ISSUE TITLE
Atom Package / Theme Repo Search does not work (1/24/2016 3:22PM)

### ISSUE THREAD

**Issue by gyf304** [atom/atom#10564]
Gives error 500. Same in the editor.

https://atom.io/themes/search?utf8=%E2%9C%93&q=theme

**Comment by 50Wliu** [comment]
@gyf304 thanks for reporting - these kind of errors usually fix themselves in a few hours.  If it still persists, please re-open the issue on https://github/atom/atom.io.  Thanks!
