### ISSUE TITLE
Restart button

### ISSUE THREAD

**Issue by rugk** [atom/atom#10561]
It would be nice to have a restart button (which is probably also offered when the editor crash (not-repsonding) message appears), which allows to restart Atom and restores the previous state immediately. 
Especially when you work with multiple windows and one crashes this is useful as you can be sure the correct session is restored.

**Comment by mnquintana** [comment]
There actually already is a restart command – `Window: Reload` in the command palette or View > Developer > Reload Window in the app menu.

Hope that helps!

**Comment by rugk** [comment]
Yes thanks. Although you cannot use this if Atom freezes and you are only able to use the menu.
