### ISSUE TITLE
How to run Atom as root? - Linux

### ISSUE THREAD

**Issue by polarathene** [atom/atom#10566]
I'm aware that we should avoid `sudo atom` since it'll write to the users `./atom` in their home directory as root which'll cause problems when not running atom as root. Normally you'd use `gksu/kdesu` or the newer [polkit](http://www.freedesktop.org/software/polkit/docs/latest/pkexec.1.html)/policykit with `pkexec`. The former does nothing, I setup a policy file for polkit and everything seemed good, Atom opened like a fresh install with no packages or past working tabs open. However I was unable to save a file getting a `permission denied` error. This worked fine with Gedit using polkit I could run `pkexec gedit` and save a file in the same location as root, with `pkexec atom` no file was saved as myself or root, just running `atom` would allow me to write a file as myself.

I believe this might have something to do with how Atom launches via a shell script instead of a binary directly? Would anyone know a way to fix this so I can use Atom for editing root owned files too?

I've got a thread on reddit seeking help as well: https://www.reddit.com/r/Atom/comments/42doe4/linux_running_atom_as_root/

**Comment by polarathene** [comment]
`gksu atom` does nothing, `gksudo atom` will run Atom as root, but has the same problems as my `pkexec atom` approach with permission to save being denied.

**Comment by siteleas** [comment]
I am running atom.io on Linux Mint and am having the same problem. I run atom with gksu and find that atom does not use the elevated permissions granted to it. It continues to be refused write permissions on files that it should have full access to. How do we get around this issue?

**Comment by lee-dohm** [comment]
It sounds like https://github.com/atom/atom/issues/4115 is really what you're looking for? The feature isn't added yet, but if Atom automatically prompted for escalation and allowed you to save files, would that cover your use case?

**Comment by polarathene** [comment]
@lee-dohm that sounds more than what I'm looking for rather than needing to run Atom as a whole with elevated privileges via pkexec/polkit. Though in some cases with Linux certain files are not visible or writable to unless you're accessing the file system as that user or a user that belongs to a certain group. For example VMWare if running as root will not have it's log files available to my user, I have to open the file browser with root rights for the log files to be visible.

Most of the time though any files I need to edit with privileges  will not have that issue, normally a config file that'd be more pleasant to use Atom with :)

@siteleas  you're granting rights to the wrapper script that launches Atom far as I understand. You'd need to edit the shell script that your launcher/terminal runs to give rights to the actual Atom application that it launches. However without a bit more work, it'd always launch Atom with gksu or pkexec, etc...plus if a Atom update makes changes to that file you'd have to patch it again.

**Comment by Thaali** [comment]
i have able to use super user privilages using this command line you should try this to
`Sudo atom`

**Comment by polarathene** [comment]
@Thaall I don't know if anything has changed since, but if you read the description rather than just the title... you'll see that `atom` would call a shell script not a binary, the wrapper shell script then calls the actual binary.

Either `sudo atom` will also run the binary as root but potentially cause the problems writing root only files into your users atom configs (in which case your Atom instance probably doesn't have all the packages installed and being configured like it was withoout sudo) or it runs the wrapper as root but not Atom as I described with the proper methods to run GUI apps as root. Either or is bad.

**DO NOT RUN ATOM WITH SUDO**

**Comment by Thaali966** [comment]
Ahh now i see the problem LOL i just read the topic and answered  stupidly and thanks for heads-up

**Comment by lee-dohm** [comment]
There isn't a good way to run Atom as root and probably shouldn't be given that it has no protections against malicious code. Elevating in the moment to save individual files should resolve the use cases that we want to support.

**Comment by polarathene** [comment]
@lee-dohm Recently a well known dev in KDE community [wrote a blogpost](https://blog.martin-graesslin.com/blog/2017/02/editing-files-as-root/) about providing root for read/write of files only when needed while keeping the rest of the application non-privlidged. Perhaps sudoedit could work like described there? Or PolKit/pbexec?

**Comment by KudosAbhay** [comment]
Hi. I don't know if this will help anyone here, 

But my scenario is that I just wanted to develop and test files in Apache Server's /var/www/html folder. So, I just provided all read write access to my Atom using "chmod 777 atom" .It has started to compile and write code in the directory.

It solved my problem.

**Comment by nocturnalguru** [comment]
Kudos to KudosAbhay.  The chmod 777 atom worked.  One command that might help is 'whereis atom' which should list the location of your files so you can chmod the right files :)
