### ISSUE TITLE
When I save files, Atom makes duplicate copies of those files and folders arbitrarily on my hard drive.  

### ISSUE THREAD

**Issue by justyn-clark** [atom/atom#10560]
### Why is this happening and how do I prevent it?

This also occurs when I rename a folder. When I'm in a file in the newly renamed folder and save, the old folder re-creates itself in the same directory. 
<img width="590" alt="screen shot 2016-01-24 at 1 49 36 am" src="https://cloud.githubusercontent.com/assets/11221796/12535584/e0bba8c0-c23c-11e5-8607-22c962b572a6.png">

**Comment by mnquintana** [comment]
- What version of Atom are you using?
- What OS are you using?
- Can you reproduce this after quitting Atom completely in safe mode? (`atom --safe`)
- If you can, what are the exact steps you used to reproduce this behavior?

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) for a guide on reporting bugs.

**Comment by justyn-clark** [comment]
I'm using:
• Version 1.4.0 is the latest version
• OSX 10.8.5

But I think I just identified what's happening. I'm using the `Remote FTP` package and when I double click to open a file on the remote server, that file and folders get copied to my system User folder. However, I have not activated any settings to allow that sync or behavior. 

<img width="568" alt="screen shot 2016-01-25 at 11 18 44 am" src="https://cloud.githubusercontent.com/assets/11221796/12561625/fbde1182-c355-11e5-99af-0a9d4654c866.png">

**Comment by 50Wliu** [comment]
> I should address this with the Package developer I presume.

Yes please!
