### ISSUE TITLE
Build failing on archlinux

### ISSUE THREAD

**Issue by kreyep** [atom/atom#10569]
Currently using v5.5.0 of node and v3.5.3 of npm. I have also tried with v5.4 and v4.2.1 of node, both give the same error.

[error.txt](https://github.com/atom/atom/files/102820/error.txt)

**Comment by arcticicestudio** [comment]
Do you tried to clean your npm cache? Maybe there are conflicts with outdated package files.

**Comment by kreyep** [comment]
This error was generated as follows:
<code>
$ npm cache clean
$ script/clean
$ script/build
</code>

**Comment by arcticicestudio** [comment]
I've compiled atom `1.4.1` some minutes ago (AUR build) with `nodejs@5.4.1` and `npm@3.5.3` successful.

**Comment by mnquintana** [comment]
What commit SHA are you trying to build?

**Comment by kreyep** [comment]
The problem was, I was using python 2.6...
