### ISSUE TITLE
Atom is lossing contributions and users due to third-party Electron-based IDEs

### ISSUE THREAD

**Issue by crushedice2000** [atom/atom#10579]
I think that the existence of third-party IDEs based on Electron is killing Atom, because they are improving many things that later don't get implemented into Atom. Wouldn't be great to have a only IDE with all the improvements?

I think that doing rebrandings of Atom to add some functionality is not as great as some development teams (*cough* MS) can think. Maybe would be better to join all the efforts here?

The only doubt I have is: Is my issue on-topic? I post here because there isn't Gitter account on the Atom repository.

**Comment by lee-dohm** [comment]
This kind of feedback is probably best on [Discuss, the official Atom message board](https://discuss.atom.io). In my opinion, this is a discussion around "what is the meaning of open source"? And I'm not sure that can be answered in a concrete fashion. Issues is generally best for questions that can be *solved* or *answered* ... and I'm pretty sure a lot of these other efforts just aren't under Atom's control :grinning:

Let me know if I'm not understanding and thanks so much for caring about Atom! :green_heart:

**Comment by crushedice2000** [comment]
@lee-dohm: Sorry, I didn't knew the existence of Discuss. I'll use it.

You're right, really, this isn't a *just solve it* issue. Also, this has nothing (or so few) to do with atom. However would be great to hare dev feedback.

You understood very well. About caring about atom... Really I simply said what I think, I'm new to Atom and I haven't so much experience as developer nor as GitHub user.

Thank you!

*Message for all the paranoid users here*: I approve the closing of this issue.

**Comment by lee-dohm** [comment]
> I'm new to Atom and I haven't so much experience as developer nor as GitHub user.

Welcome to Atom and GitHub! Let me know if there is anything that I can do to help :grinning:

**Comment by crushedice2000** [comment]
@lee-dohm: Here nothing, among other things, because would turn this more off-topic yet. However I'm sure that we will meet again on Discuss.

Thank you very much! :smile:
