### ISSUE TITLE
Stop atom to start when windows starts (win 7/10)

### ISSUE THREAD

**Issue by fwd079** [atom/atom#10572]
Hi
Whenever windows starts my UAC prompts that atom.exe is trying to start. I hit cancel of course, as I never allowed it to start with windows. I'd like it to start when I click the button. There seems to be no checkbox saying "Start atom when windows starts" which I can uncheck.

Please can you tell me how I stop atom starting everytime windows starts? It happens on both Win7 / 10 etc.

Regards.

**Comment by 50Wliu** [comment]
@fwd079 Atom definitely isn't supposed to start automatically when Windows starts.  How did you install Atom?

**Comment by fwd079** [comment]
I went to:
https://atom.io/

And clicked "Download Windows Installer" and did *not* change any of the options, its just a regular/recommended/shipped install.

**Comment by 50Wliu** [comment]
Hmm.  The installer doesn't even come with any options (it's a direct install).  Can you try uninstalling and reinstalling to see if that helps?

**Comment by fwd079** [comment]
Sure, doing right now, be back in ten.

**Comment by fwd079** [comment]
Well there you go, reinstalling doesn't help! 

[githubatom](https://cloud.githubusercontent.com/assets/7912632/12576471/ccb48e16-c40b-11e5-827d-f8f426efb06e.png)

**Comment by paulcbetts** [comment]
My Psychic Debugger is saying that you somehow machine-wide installed the app, probably by right-clicking "Run as Administrator" then something went wrong

**Comment by fwd079** [comment]
Well you wouldn't be surprised to know that there is no such thing as psychic powers lol. But I do have a habit of running trusted apps as administrator but I wasnt sure I did that with Atom, so I uninstalled it, reinstalled in regular fashion, and see the screenshot.

Regards
 
![image](https://cloud.githubusercontent.com/assets/7912632/12609512/1a145b5e-c4da-11e5-9215-3fc917c86827.png)

**Comment by paulcbetts** [comment]
Yeah, so, just delete `C:\ProgramData\SquirrelMachineInstalls` and you should be fine

**Comment by fwd079** [comment]
Yes deleting that particular folder solved the issue, no more security warnings and startup objects of Atom. Just a request to please give an option/delete after install, so any updates dont mess it up again.

Thanks for your help. Appreciated it. :smile:   :+1: 

Regards.
