### ISSUE TITLE
Crashes every now and then!

### ISSUE THREAD

**Issue by slavidodo** [atom/atom#10578]
As title describes! It crashes while working ( no specific reason ) -- I am confused about it!

So is it a known bug or ..? - However I now moved to sublime because I lost something and I have to rewrite them again, I still want to know why it crashes.

Thanks.

**Comment by amytruong** [comment]
Hey there! Thanks for letting us know.
It'd be awesome if we could get more information from you, such as: 

* Atom version 
* OS and version 
* Installed packages



**Additional information:**

* Does this happen in safe mode?
* Did this started happening recently?  Did it happen in an older version of Atom? 
* Does the crash happen with all files and projects, not only some files or projects?

**Comment by slavidodo** [comment]
Thanks for replying, 
## Information :
 - Atom version : 1.4.1
 - OS : Windows 10 - ENT
 - Installed Packages ( atom-beautify, autoclose-html, file-icons, pinned-tabs ) 
 - No Themes installed.

## Additional information :
 - No, Not happened in Safe mode.
 - It happened in this version only, ( not reticently, always ).
 - As I said no specific reason ( crashes with different projects ).

**Comment by lee-dohm** [comment]
If it isn't happening in Safe Mode then probably what is happening is some community package you have installed is crashing Atom. You can use the [package-cop package](https://atom.io/packages/package-cop) to help narrow down which one.

**Comment by slavidodo** [comment]
Exactly! That's it : 
After Long research i found the package autoclose-html caused the crash.
Anyway, Thanks.
