### ISSUE TITLE
Switch Atom To Use electron-compile Instead Of Built-In compile-cache

### ISSUE THREAD

**Issue by joefitzgerald** [atom/atom#10575]
Babel 6.x has a new plugin architecture which breaks assumptions used to transpile + cache Babel in 3rd party packages. babel-core looks for the plugins and presets (specified below) in directories relative to the .js file being transpiled. Thus, because the plugins and presets are included in `${PATH_TO_ATOM}/node_modules` (and not `~/.atom/packages/some-random-package/node_modules`), they are not found. There is no way to give babel-core a root directory from which to search.

This leaves us with two paths forward:
1. Submit a PR to `babel-core` to add an [option](http://babeljs.io/docs/usage/options/) for specifying a `presetRoot` and a `pluginRoot`
2. Require 3rd party packages wishing to use `babel` to add the required packages to their package.json
## Migration Notes:
- [ ] Update `static/babelrc.json`:
  - [ ] Clear file
  - [ ] Add `"presets": ["es2015", "stage-0", "react"]`
  - [ ] Add `"plugins" : ["syntax-async-functions"]`
  - [ ] Add `"sourceMaps": "inline"`
- [ ] Add in babel-polyfill at needed locations:
  - [ ] `static/index.html`?
  - [ ] `src/browser/main.coffee`?
- [ ] Update `package.json` and `build/package.json`
- [ ] Update `build/Gruntfile.coffee`
### `package.json`

``` json
"babel-core": "^6.4.5",
"babel-plugin-syntax-async-functions": "^6.3.13",
"babel-polyfill": "^6.3.14",
"babel-preset-es2015": "^6.3.13",
"babel-preset-stage-0": "^6.3.13",
"babel-preset-react": "^6.3.13",
```
### `Gruntfile.coffee`

```
  babelConfig =
    options:
      extends: '../static/babelrc'
    dist:
      files: [
        expand: true
        src: [
          'src/**/*.js'
        ]
        dest: appDir
      ]
```

This is related to #10509.

**Comment by joefitzgerald** [comment]
Per @paulcbetts, we could look into using [`electron-compile`](https://github.com/electron/electron-compile) to externalize this responsibility from Atom itself.

**Comment by freebroccolo** [comment]
If I'm understanding the issue correctly, option 2 generally sounds better to me although it would sometimes be less convenient. Relying on Atom for here seems problematic because whatever plugins it provides will always have the potential to be out of date.

Does `electron-compile` address that concern? Would it actually be possible to use in the near term? I mean, does it work with the versions of electron Atom is shipping?

**Comment by joefitzgerald** [comment]
Yes I think electron-compile is the best path forward at this time.
