### ISSUE TITLE
repositoryForDirectory promise matching versus setPaths disposing

### ISSUE THREAD

**Issue by sorear** [atom/atom#10584]
It is possible for `atom.project.repositoryForDirectory` to return a disposed `GitRepository`, that is one with `@emitter === null`, because `atom.project.setPaths` calls `.destroy()` on all loaded repositories, but  references to the (now destroyed) repositories are kept in `@repositoryPromisesByPath`.  I see this with `project-ring` which calls `setPaths` on startup, leading to a number of errors of startup (with `project-ring`) of the form:

```
Uncaught (in promise) TypeError: Cannot read property 'on' of null
   module.exports.GitRepository.onDidChangeStatus @ /Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:127
   module.exports.TabView.subscribeToRepo @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:343
   (anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:328
   _tickCallback @ node.js:368
```

Let me know if more detailed reproduction steps are needed.

**Comment by lee-dohm** [comment]
If you could supply more detailed repro steps, this would be helpful. It sounds like what you're saying is that if one:

1. Has a project with directory X (that is a Git repository)
1. Calls `atom.project.setPaths` and passes it directory Y
1. Calls `atom.project.repositoryForDirectory` passing it X

Then you'll get a disposed `GitRepository` object back from the returned Promise?

**Comment by sorear** [comment]
Essentially, yes.

**Comment by sorear** [comment]
```
$$ (mkdir repo1; cd repo1; git init)
Initialized empty Git repository in /private/tmp/repo1/.git/
$$ (mkdir repo2; cd repo2; git init)
Initialized empty Git repository in /private/tmp/repo2/.git/
$$ >/tmp/repo1/TEST
$$ rm -rf atom-bug-demo/
$$ ATOM_HOME=/tmp/atom-bug-demo apm install project-ring
Installing project-ring to /tmp/atom-bug-demo/packages ✓
$$ cat > atom-bug-demo/config.cson
"*":
  core: {}
  editor:
    invisibles: {}
  "exception-reporting":
    userId: "d32fb9b9-9d97-33fa-dcc7-55ce6f41ab89"
  tabs:
    enableVcsColoring: true
  welcome:
    showOnStartup: false
$$$ cat > ~/.atom-project-ring/default_project_ring.cson
Repo1:
  key: "Repo1"
  isDefault: true
  rootDirectories: [
    "/private/tmp/repo1"
  ]
  files:
    open: [
      "/private/tmp/repo1/TEST"
    ]
    banned: []
  treeViewState: null
Repo2:
  key: "Repo2"
  isDefault: false
  rootDirectories: [
    "/private/tmp/repo2"
  ]
  files:
    open: []
    banned: []
  treeViewState: null
$$ ATOM_HOME=/tmp/atom-bug-demo atom
```

Then open devtools, break on exceptions, and switch between the tabs a couple times.  Interestingly the `tabs.enableVcsColoring` is required; it could be a bug there, or in `project-ring` which could be misusing `atom.project`.  This is an OSX system where `/tmp` is a symlink to `/private/tmp`; you may need to tweak the example paths.

**Comment by sorear** [comment]
P.S. it seems a little weird that `project-ring` keeps state outside of `ATOM_HOME` (see `~/.atom-project-ring/default_project_ring.cson` above).  Should I file that as a bug against `project-ring` ?

**Comment by lee-dohm** [comment]
> P.S. it seems a little weird that project-ring keeps state outside of `ATOM_HOME`

If you feel it is a bug, then sure. Personally, if packages have secret information (OAuth tokens, passwords, etc), I generally recommend that they store it somewhere other than `ATOM_HOME`. So I don't think it is that big of a deal.
