### ISSUE TITLE
@ character in latin american keyboard does not work correctly

### ISSUE THREAD

**Issue by jhuvier** [atom/atom#10589]
When I hit AltGr + Q(@) on a Latin American keyboard, atom does not put the "@" character, instead it format the code as shown in After.png image attached to this issue.
![before](https://cloud.githubusercontent.com/assets/16830249/12582861/ac08b4ec-c40d-11e5-9b3d-bd291781b05b.png)
![after](https://cloud.githubusercontent.com/assets/16830249/12582860/ac0109b8-c40d-11e5-98a8-17bcf1447276.png)

**Comment by mnquintana** [comment]
Sorry for the trouble here! It sounds like you're running into https://github.com/atom/atom-keymap/issues/35 and/or https://github.com/atom/atom-keymap/issues/37 – feel free to subscribe there for updates.
