### ISSUE TITLE
Unable to add keymap for sorting lines

### ISSUE THREAD

**Issue by newhoggy** [atom/atom#10588]
I added the following to my keymap:

```
'atom-text-editor':
  'f5': 'lines:sort'
```

But am still unable to sort with `f5`.

**Comment by mnquintana** [comment]
Looks like that's because [the command name is actually `sort-lines:sort`.](https://github.com/atom/sort-lines/blob/master/keymaps/sort-lines.cson#L2)

Hope that helps!

**Comment by newhoggy** [comment]
Unfortunately, that didn't work for me either.

**Comment by newhoggy** [comment]
Also, when I press cmd-shift-p to get the command palette, I don't see a sort command anywhere.

**Comment by mnquintana** [comment]
What keyboard layout are you using?

**Comment by newhoggy** [comment]
Just the normal keyboard layout.  Is there another way to trigger the sort lines apart from via they keymap?

**Comment by newhoggy** [comment]
atom version is `1.4.0`

**Comment by newhoggy** [comment]
OS X.

**Comment by demhydraz** [comment]
> Just the normal keyboard layout.

I think @mnquintana meant as in, US, UK.. The layout of the keys on your physical keyboard.

**Comment by newhoggy** [comment]
It was Australia, but I just tried US and same problem.

**Comment by newhoggy** [comment]
Also, that link you posted looks like a package, but, I can't install it.  It doesn't appear in the list of packages I can install.

**Comment by newhoggy** [comment]
<img width="765" alt="screen shot 2016-01-31 at 10 34 28 am" src="https://cloud.githubusercontent.com/assets/63014/12699168/4077359e-c806-11e5-9bbe-b502aab085ad.png">

**Comment by newhoggy** [comment]
Oops, sorry, it looks like that was the list of already installed packages.

**Comment by newhoggy** [comment]
I have it working.

**Comment by newhoggy** [comment]
But one more thing.  I can't bind it to `ctrl-f5`.  I get a little box typed in instead when I used that key combo.

**Comment by newhoggy** [comment]
Could be something wrong with my particular mac because it works on a different mac.

**Comment by newhoggy** [comment]
Happy to close since I can bind to something else.

Thanks for your help!
