### ISSUE TITLE
Updating atom is ridiculous slow

### ISSUE THREAD

**Issue by vendforce** [atom/atom#10586]
This is a great editor but poor implementation, Atom editor has a lot going for it and it also has a lot against it

1 ) its still not great at opening large files
2 ) crashes from time to time
3 ) updating is a chore
4 ) loading times are not great

Im updating from arch , I had atom editor installed before it got it's first stable version and I wasn't happy with the updating process , Rapid application development is all well and good, but when it takes 5 minutes  to update the program because of modules, it becomes a task not a process and I haven't time nor the patience to wait for the update everytime theres a new release or rev and there's a lot of them ... 

There has to be a better way of updating the modules in a faster or more convenient way !!! 

I thought after the stable version the updating process would be a lot faster , I was wrong as it's getting worse with more modules being adding eventually you will be left waiting for 10 minutes for this thing to upgrade thats ridiculous if the release's were kept back a little longer it wouldn't be so bad but the fact there's so many updates its painful and I've no time this, Uninstalling atom editor , Its the only program I actually wish there isn't an update for when I boot up my machine.

**Comment by lee-dohm** [comment]
Thanks for the feedback and we're sorry that you have had a bad experience with Atom. I suspect you're talking about updating [Atom packages](https://atom.io/packages)? If you're talking about the main Atom program, we don't have an update process for Atom itself on Linux. So if that is unsatisfactory, you may want to follow up with the package manager that you installed Atom through.

As far as Atom packages go, there's nothing requiring you to update them ... though I understand the urge to keep them up to date. Some people even use their `styles.less` to hide the squirrel icon that reminds them to update their packages and just remember to do it themselves on whatever schedule they find most convenient.

Still, if you decide to no longer use Atom, we're sorry to see you go and greatly appreciate you taking the time to give us feedback so we can improve Atom!
