### ISSUE TITLE
.gitignore not reflecting live

### ISSUE THREAD

**Issue by asotog** [atom/atom#10582]
Hi,

Steps to reproduce
1 - Open folder project
2 - Modify the .gitignore file, adding an entry: my_temp_folder
3 - my_temp_folder still visible

Expected:
Folder hidden because entry was added to .gitignore list

Currently:
This is reflecting now until editor window is reopened, so my question is there any way to handle this without closing and opening again the window ?

**Comment by germ13** [comment]
I have a similar problem that might be related.

When i remove an item (eg `dist`) from the `.gitignore` file.
It should show up on the tree view, because its not being ignored anymore.
But it does not show up on tree view.

I have to close and reopen my ide for changes to take effect.

I have also tried all combinations of `Hide Ignored Names` in the tree-view options, and `Exclude VCS Ignored Paths`.  None of these take effect until i close and reopen.

```
atom version: 1.5.3
os: windows 10
```

**Comment by lee-dohm** [comment]
@asotog Do you mean that the file is still showing in the Tree View? You could try collapsing and expanding the root folder. That should refresh it.

@damieng Can you reproduce what @germ13 is describing?

**Comment by damieng** [comment]
Unless we're monitoring .gitignore for changes I can see how this would happen.

**Comment by lee-dohm** [comment]
We should be. This works on OS X for me. The tree view updates as soon as I save the `.gitignore` file.

**Comment by asotog** [comment]
Yeah it works when you collapse and expand again the folder

**Comment by germ13** [comment]
I tried collapsing and expanding the folder and it solved the issue as well.

@damieng can you give me more info on where to look at in the atom code (or docs) to enable monitoring of the .gitignore file.  A more natural solution than collapsing and expanding the folders would be better.  

thanks.

**Comment by lee-dohm** [comment]
Are you editing the `.gitingore` in Atom? Or are you editing the `.gitignore` in some other manner?

**Comment by germ13** [comment]
I am updating the `.gitignore` within Atom. No other manner.

**Comment by lee-dohm** [comment]
Ok, then there shouldn't be anything else you need to do to enable monitoring. It should just work.

**Comment by germ13** [comment]
seems non-intuitive to have to collapse and expand tree to see effects of saving the `.gitignore` file.
seems like it should refresh/reflect immediately upon save.

**Comment by lee-dohm** [comment]
My statement about collapsing and expanding the root folder was specifically to address the question:

> is there any way to handle this without closing and opening again the window ?

It wasn't a suggestion that this is acceptable. If I thought it was acceptable or intended, I would have closed the issue after giving the explanation.

**Comment by johnmuhl** [comment]
Could the `linux` label be added as well? This is also reproducible on Ubuntu 15.10 with all versions of Atom up to and including 1.6.0-beta6.

**Comment by germ13** [comment]
@lee-dohm understood. was just making sure we were on same page.

**Comment by lordmat0** [comment]
This also happens on OSX.

**Comment by lee-dohm** [comment]
@lordmat0 Please give some more information. All indications are that this does not reproduce on OS X.

**Comment by lordmat0** [comment]
@lee-dohm I think when it upgraded to 1.6.0 it broke a lot of things, so I have now done a clean install of Atom. Unfortunately I forgot to test this so for now I'll take back my comment of it not working on OSX and report back on Tuesday if it's the case for OSX.
