### ISSUE TITLE
Possible data loss when editing files on Samba shares, from OS X, in Atom 1.4

### ISSUE THREAD

**Issue by WalterGR** [atom/atom#10596]
A few days ago, I opened #10558: "Temp files are created on Samba shares that aren't deleted on close, can't be deleted manually, and are only deleted upon unmounting the share".

I'm seeing similar behavior _but with edited files as well_ - not just temp files.

I've only seen this once - but I've only performed 2 editing sessions in Atom 1.4 in which I edited files on a Samba share, so those aren't great odds.

As I said in #10558, I didn't see this issue in 1.3.x.  I edited lots and lots of files on Samba shares in 1.3.x and had no problems at all.

A little bit more about the setup:

OS X 10.10.5 running a Windows 7 SP1 VM in VMWare Fusion 7.  Some directories are shared from the Windows 7 VM using Windows file sharing.

Steps:
1.  Using Finder in OS X, mount a Samba share from the Windows VM.
2.  Open Atom.
3.  Open a file on the Samba share in Atom.
4.  Edit the file, save, edit, save, etc.
5.  Close the file in Atom.
6.  Open another file, edit, save, edit, save, etc.
7.  Close Atom.

At this point, everything seemed good.  Later, I attempted to edit the file opened in step 2 from within the Windows VM.  Reading the file worked, but it was locked for writing.

I dismounted the Samba share to see if that closed the handle.

It did close the handle.  _It also entirely deleted the file I had been editing_.

Now, there are several moving parts in the above scenario: Atom, OS X, Fusion, a Windows VM.  I can't guarantee that Atom is the part causing the data loss.  But I haven't seen files get locked like this, and only unlocked _and deleted_ when the share is unmounted (as in #10558, which is specifically about temp files) except in Atom >= 1.4.0.

~~Let me know if I should merge this issue with #10558.~~  I merged that issue with this one - see comments below.

EDIT: #10598 - "Samba shares and Atom" - which was closed as a dupe of this one - notes

> The last problem is that changing words in a samba share can damage files. The word had to be changed is replaced with nothing.

I'm not positive what that means, but it reminds me that I missed a step 8 above: In the Windows VM, rename the file opened in step 3.

Maybe it does mean what I think it means, which also would seem to match my experience:

if you edit a file on a Samba share in Atom, and then rename the same file via the OS that the Samba share resides on, then when the Samba share is dismounted the file is deleted completely.  Sometimes.  At least on OS X.

**Comment by lee-dohm** [comment]
It sounds like these two are the same underlying problem. Unless you think there is some alternate mechanism behind the temp files? If they are the same underlying problem, one Issue is probably best ... it especially helps because then *all* the information is in the same place.

**Comment by WalterGR** [comment]
> Unless you think there is some alternate mechanism behind the temp files?

Dunno.  Haven't looked at the code.

> If they are the same underlying problem, one Issue is probably best ... it especially helps because then all the information is in the same place.

Sure.  I'll roll #10558 into this one, since the data loss is more pressing than temp files being scattered around.

**Comment by WalterGR** [comment]
As requested, I'm rolling #10558: "Temp files are created on Samba shares that aren't deleted on close, can't be deleted manually, and are only deleted upon unmounting the share" into this bug.

The bug's description above already highlights how the following is related:

> But I haven't seen files get locked like this, and only unlocked _and deleted_ when the share is unmounted (as in #10558, which is specifically about temp files) except in Atom >= 1.4.0.

Here's the relevant info:

Repro:

1.  Edit a plain text file on a Samba share.
2.  (Atom creates a `.tmp` file in the same directory.  Sometimes.  Not always.  I don't know the repro steps to force it to do so.  "Back Up Before Saving" is off, so this must be some kind of special temp file.)
3.  Close the tab for the plain text file.  Temp file isn't deleted.
4.  Close Atom.

Expected:

Atom deletes the temp file.

Actual:

Atom doesn't delete the temp file.  The file can't be deleted either via Finder in OS X or via Windows Explorer on the Windows box where the Samba share resides.

Finder gives the error "The operation can’t be completed because an unexpected error occurred (error code -8072)."

Windows Explorer says that the deletion can't complete without administrative rights and shows the elevation dialog.  Elevating doesn't help: another dialog is displayed saying that the file can't be deleted.  (I didn't capture the exact error text of the dialog.)  Attempting to take ownership of the file via `takeown` and modifying its ACLs via `icacls` fail:

    > takeown /s MYBOXNAME /u MYBOXNAME\MyUsername /f . /r
    
    WARNING: User credentials cannot be used for local connections.
    ERROR: The current logged on user does not have ownership privileges on
           the file (or folder) "E:\work\current".
    
    > icacls . /grant MYBOXNAME\MyUsername:f /t
    processed file: .
    processed file: .\notes.txt
    .\notes.txt~RF449e304.TMP: Access is denied.
    Successfully processed 2 files; Failed processing 1 files
    
    >

`handles.exe` v3.46 (a Sysinternals tool by Mark Russinovich) shows that System has open handles on the temp file.

The temp file only gets deleted when the Samba share is unmounted from OS X.

Multiple temp files may be created, so reference above to "the temp file" are also applicable to "the temp files".  Again, I'm not sure under what circumstances Atom creates them, but the end result is that heavy Atom work on a Samba share leaves un-deletable temp files scattered about which screw up directory diffs, syncing directories, moving things around, uploading directories to other places, deleting directories that are no longer needed, recursively adding directories to source control, etc. etc. etc., and force an unmount and remount to resolve.

**Comment by WalterGR** [comment]
Should this get the `data-loss` tag?
