### ISSUE TITLE
Search doesn't work when same search term is entered

### ISSUE THREAD

**Issue by bobber205** [atom/atom#10593]
I use the Quick Project switcher all the time.
If I search for say `myVariable` in Project A then switch to Project B and keep the search term the say, whether that's leaving that field alone or retyping it, nothing is searched.

I think it'd be a handy thing to have it *always* research when I press search, maybe as a setting?

**Comment by lee-dohm** [comment]
Would you mind reopening this on the [find-and-replace package](https://github.com/atom/find-and-replace)? That is where issues with find and replace belong.

Also, when you do could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

Please let us know if you have any additional questions!
