### ISSUE TITLE
Does Atom have "projects"?

### ISSUE THREAD

**Issue by danechitoaie** [atom/atom#10606]
I'm looking into developing a plugin for Atom but I will need to have/store some project specific info (like credentials to connect to a server, and some other project specific settings).

ST has something similar and you can save this info in this "project file" (.sublime-project file). Here you can have/save custom values, list of files/folders added to the current project, etc...

Is there something like this available for Atom?

**Comment by lee-dohm** [comment]
There isn't something like this built in to Atom at this time (see https://github.com/atom/atom/issues/10517). But there are packages that add some or all of what you're looking for. The [project-manager package](https://atom.io/packages/project-manager) is possibly the most popular.

**Comment by danechitoaie** [comment]
@lee-dohm Thank you. In the end it would be nice for something like this to be natively in Atom.

**Comment by lee-dohm** [comment]
Yes, it would. I opened the Issue I linked to start that discussion :grinning:
