### ISSUE TITLE
Program freezes when on windows 10 in split view

### ISSUE THREAD

**Issue by AnthonyMichaelc** [atom/atom#10602]
I love using Atom for the core features and packages it comes with off the start but recently two project files that are both over 30 mb have been experiencing freezing up when dragging the program to the side and split viewing it with a web browser. Once I split view atom with chrome, i cannot click the code and change or highlight it at all. Because of this issue I am left using Sublime Text 3 or Brackets when Atom does this. Is there any news on when this issue may be fixed, because I have a samsung evo 840 sdd, i7, and 16 gb ddr3 so hardware should not be an issue.

**Comment by 50Wliu** [comment]
Hi @AnthonyMichaelc, sorry to see that you're having difficulties.  This has already been reported, so please subscribe to #9901 for updates.
