### ISSUE TITLE
User's keymap not work at 1.4.1

### ISSUE THREAD

**Issue by kerryChen95** [atom/atom#10617]
After check for update, I click restart and install. Then Atom upgrade from 1.0.0 to 1.4.1, but my keymap not work.
I use `cmd-.` to open key binding resolver, but I cannot see a keymap from my keymap file.

Reproduce when I re-install 1.0.0 then upgrade to 1.4.1.

My OS is Max OS X 10.11.3.

**Comment by thomasjo** [comment]
Please share your custom keybindings with us. Then we can help you track down the problem.

**Comment by kerryChen95** [comment]
This is my `~/.atom/keymap.cson` file
```cson
# Your keymap
#
# Atom keymaps work similarly to style sheets. Just as style sheets use
# selectors to apply styles to elements, Atom keymaps use selectors to associate
# keystrokes with events in specific contexts. Unlike style sheets however,
# each selector can only be declared once.
#
# You can create a new keybinding in this file by typing "key" and then hitting
# tab.
#
# Here's an example taken from Atom's built-in keymap:
#
# 'atom-text-editor':
#   'enter': 'editor:newline'
#
# 'atom-workspace':
#   'ctrl-shift-p': 'core:move-up'
#   'ctrl-p': 'core:move-down'
#
# You can find more information about keymaps in these guides:
# * https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings
# * https://atom.io/docs/latest/behind-atom-keymaps-in-depth
#
# This file uses CoffeeScript Object Notation (CSON).
# If you are unfamiliar with CSON, you can read more about it in the
# Atom Flight Manual:
# https://atom.io/docs/latest/using-atom-basic-customization#cson

'body':
  'cmd-h': null
  'cmd-`': 'tree-view:toggle-focus'
  'cmd-1': 'window:focus-pane-on-left'
  'cmd-2': 'window:focus-pane-on-right'
  'cmd-!': 'move-panes:move-left'
  'cmd-@': 'move-panes:move-right'
  'ctrl-left': 'editor:move-to-previous-subword-boundary'
  'ctrl-right': 'editor:move-to-next-subword-boundary'
  'ctrl-shift-left': 'editor:select-to-previous-subword-boundary'
  'ctrl-shift-right': 'editor:select-to-next-subword-boundary'

'atom-workspace':
  'cmd-ctrl-shift-h': 'core:move-left'
  'cmd-ctrl-shift-j': 'core:move-down'
  'cmd-ctrl-shift-k': 'core:move-up'
  'cmd-ctrl-shift-l': 'core:move-right'

'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-[': 'editor:fold-current-row'
  'ctrl-alt-]': 'editor:unfold-current-row'
  'ctrl-alt-{': 'editor:fold-selection'

'atom-text-editor':
  'ctrl-down': 'keyboard-scroll:scrollDown'
  'ctrl-up': 'keyboard-scroll:scrollUp'
  'alt-down': null
  'alt-up': null

'atom-text-editor:not([mini])':
  'cmd-e': 'emmet:expand-abbreviation'
  'cmd-shift-k': 'editor:delete-line'

'.platform-darwin .find-and-replace':
  'cmd-shift-r': 'find-and-replace:toggle-regex-option'
  'cmd-shift-c': 'find-and-replace:toggle-case-option'
  'cmd-shift-s': 'find-and-replace:toggle-selection-option'
  'cmd-shift-w': 'find-and-replace:toggle-whole-word-option'

'.platform-darwin .project-find':
  'cmd-shift-r': 'project-find:toggle-regex-option'
  'cmd-shift-c': 'project-find:toggle-case-option'
  'cmd-shift-w': 'project-find:toggle-whole-word-option'
```

**Comment by mnquintana** [comment]
Just to clarify, do none of your custom keybindings work? Or is it a subset of them that don't work?

**Comment by kerryChen95** [comment]
None of my custom keybindings work.

**Comment by dhruvdutt** [comment]
Facing same issue on windows platform too.

**Comment by lee-dohm** [comment]
Have you tried using the Keybinding Resolver (<kbd>Cmd+.</kbd> on OS X and <kbd>Ctrl+.</kbd> on other platforms)? It will show you what key Atom saw you press and the command that was triggered because of it.

**Comment by lee-dohm** [comment]
Also, are you using a non-English-US keyboard layout?

**Comment by dhruvdutt** [comment]
@lee-dohm Ah! I got mine fixed with the help of Keybinding Resolver. Thank you!

```
'body':
  'alt-down': 'core:page-down'
  'alt-up': 'core:page-up'

'atom-workspace atom-text-editor:not([mini])':
  'ctrl-[': 'editor:fold-current-row'
  'ctrl-]': 'editor:unfold-current-row'
  'ctrl-backspace': 'editor:delete-line'
```

**Comment by lee-dohm** [comment]
I'm glad to hear it @dhruvdutt :grinning:

**Comment by kerryChen95** [comment]
To reproduce, I upgrade Atom to 1.4.2, then once re-start Atom, display an error as below, and my custom keymaps not work again.

---

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.2
**System**: Mac OS X 10.11.3
**Thrown From**: [AtomicChar](https://github.com/SaschaNaz/AtomicChar) package, v0.3.8


### Stack Trace

Failed to load the AtomicChar package

```
At Cannot find module 'src/tokenized-line'

Error: Cannot find module 'src/tokenized-line'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at AtomicWrapper (/Users/kerry95/.atom/packages/AtomicChar/lib/atomic-wrapper.js:5:25)
    at Object.<anonymous> (/Users/kerry95/.atom/packages/AtomicChar/lib/atomic-wrapper.js:106:3)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:393:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": false
  }
}
```

### Installed Packages

```coffee
# User
AtomicChar, v0.3.8
column-select, v0.2.0
docblockr, v0.7.3
emmet, v2.4.1
highlight-column, v0.5.0
highlight-selected, v0.11.1
keyboard-scroll, v0.4.0
language-babel, v2.15.2
language-vue, v0.8.0
project-manager, v2.7.5

# Dev
No dev packages
```

**Comment by kerryChen95** [comment]
The error was thrown from AtomicChar package, so I tried to re-install AtomicChar package, but got another error

---

Installing “AtomicChar@0.3.8” failed.Hide output…

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp http 404 https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: 404 response downloading https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1584:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.34.5" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/kerry95/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by kerryChen95** [comment]
After using `'unset!'` instead of `null` to disable default keymaps, my custom keymaps work! :astonished:

**Comment by Ben3eeE** [comment]
Closing this since it looks like an error in a community package and was fixed by changing `keymap.cson`.
