### ISSUE TITLE
Can't drag tab between two 'splits' when using the Awesome window manager

### ISSUE THREAD

**Issue by MattiasEkstrom** [atom/atom#10611]
I have one window with a vertical split. I'm trying to drag one tab from one side to the other, the tab doesn't ever get moved to the other side. 

This seems to only happen when using '[awesome](http://awesome.naquadah.org/)'. I have tried this with openbox on the the same machine without issue. 

I'm using version 1.4.0

**Comment by tbranyen** [comment]
This is a very common problem in general with Awesome WM and Chrome-like tabs, I've noticed in my experience.

**Comment by lee-dohm** [comment]
If things are working for all other window managers, I'm not sure there is a lot we can do on this ... especially if it affects Chrome/Chromium as well.

**Comment by MattiasEkstrom** [comment]
Sounds like this might be an issue with Awesome and not Atom then, feel free to close it.

**Comment by lee-dohm** [comment]
Sorry we couldn't be more help :frowning:
