### ISSUE TITLE
Atom fails to correctly read any files including its config and packages

### ISSUE THREAD

**Issue by Hugoch** [atom/atom#10618]
When I start atom, the editor complains that it can't read config.cson and packages (nothing new modified or installed). Opening any file in atom gives me rubbish characters whatever the encoding. Opening the same file in another editor works fine.
![image](https://cloud.githubusercontent.com/assets/733386/12673655/57e2c844-c67e-11e5-815a-9a43670cb39d.png)
![image](https://cloud.githubusercontent.com/assets/733386/12673659/5aeeeebe-c67e-11e5-9468-d6419326c08e.png)
I have to reboot the computer to get it right. After a few start/stop of atom (I can't figure which event breaks everything) the bug reapears.

Trying to start atom from the command line (cmd.exe), I get
![image](https://cloud.githubusercontent.com/assets/733386/12673666/6317bc24-c67e-11e5-85b1-3ec8e4497123.png)

Safe mode does not work either.

I upgraded from 1.4 to 1.4.1, same behavior. I tried to disable my packages, no success.

I'm running on W7. 

Any clues ?

**Comment by Zireael07** [comment]
Something definitely corrupted your config.cson (I think I saw an issue about that), but I think there's even more corruption going on.

**Comment by Hugoch** [comment]
This appears for every file including the config.cson. Reinstalling Atom, or deleting the whole .atom/ folder with config.cson does not solve the issue.

**Comment by lee-dohm** [comment]
You mentioned though that rebooting the computer "get(s) it right". Does that mean that after rebooting your computer the problem goes away temporarily? Are you saying Atom can sometimes read the files correctly and sometimes not read the files correctly?

**Comment by Hugoch** [comment]
@lee-dohm Exactly. After a fresh reboot, everything is fine. I'm trying to find the event that messes everything up but no success yet ..

**Comment by lee-dohm** [comment]
Let us know what you find! This is definitely an unique experience :worried:

**Comment by Hugoch** [comment]
Ok, I finally found the bug. This has nothing to do with Atom but this is a incompatibility between node.js and my enterprise disk encryption software. When trying to open a file, node fails to correctly get the de-encrypted file and opens the encrypted version which is garbage. So that's our specific disk-encryption driver which seem to be faulty.

**Comment by lee-dohm** [comment]
Thanks for following up @Hugoch!
