### ISSUE TITLE
Cannot scroll through tree view when dragging a file

### ISSUE THREAD

**Issue by ToadKing** [atom/atom#10613]
When dragging a file to move it in the tree view, trying to scroll up or down while dragging the file will first drop the file wherever your cursor currently is, then scroll. The file should remain in a dragging state until the left click is released.

Atom version: 1.4.1
OS: Windows 10 Pro x64

**Comment by amytruong** [comment]
I am on Windows 8.1 and I am able to scroll while also dragging a file albeit it's a little bit...sticky/difficult. I'll get my hands on a Windows 10 machine and try it again though! :grimacing:

**Comment by g4challenge** [comment]
Can confirm this as well. When dragging in Tree view, neither mouse scrolling or touchpad or using the bar is working.

Atom version: 1.5.0
OS: Mac OS X 10.11

**Comment by amytruong** [comment]
Def weird. I'm having this issue now on both windows and mac. Will confirm with the team but will label it as a weird bug for now.

**Comment by poyhsiao** [comment]
Sorry, but my tree view cannot scroll when I update to new atom version

Atom version: 1.6.0
OS: Mac OS X 10.11
