### ISSUE TITLE
Atom keep changes when I change branch.

### ISSUE THREAD

**Issue by dody87** [atom/atom#10620]
When I have a clean repo and change to another branch, then it conserves my changes from previous one and showing invalid code on it.

Atom 1.4.1 OSX version.

**Comment by cgonzalezvera** [comment]
Hello guys! The same case happen to me. It was in a Atom for Windows 10. 
I was thinking was the only with that problem. But I see don't.

**Comment by nmarchini** [comment]
I have the same issue, when i switch branches on the terminal Atom doesn't show the new files. This is making it impossible to use Atom as an editor for me.
