### ISSUE TITLE
Replacing text using Regex not working

### ISSUE THREAD

**Issue by Quaturn** [atom/atom#10622]
I edit xhtml and html which i am using in epub.
When I am changing tags on specific lines in notepad++ I am using there regex functions for it:
`<p>Chapter(.*?)</p>` which finds all lines starting and ending this way and replacing it by using
`<h2>Chapter\1</h2>` which switches all the previous tags for these new ones without erasing text in between.

This is not working in Atom , it will find the lines just fine but when replacing he will replace it with `<h2>Chapter\1</h2>` with erasing the text in between and not just replacin

**Comment by princejwesley** [comment]
@Quaturn  Use `<h2>Chapter$1</h2>` to replace the captured group. (note: `$`)

**Comment by Quaturn** [comment]
thank you very much it is working this way

**Comment by 50Wliu** [comment]
Glad to see you solved your issue @Quaturn!

**Comment by demhydraz** [comment]
I have a question: Why does the regex engine use $ for variables instead of sed-style escapes?

**Comment by princejwesley** [comment]
@demhydraz regex engine uses `\` for captured group. `$` is used in replacement context( as in java, javascript style).

e.g. `(.*)\s\1` matches  `test test`
