### ISSUE TITLE
Atom shows there are available updates but then Settings/Updates start fetching updates again

### ISSUE THREAD

**Issue by mindrones** [atom/atom#10637]
Atom says there are available updates, 

![screen shot 2016-02-01 at 16 51 56](https://cloud.githubusercontent.com/assets/1309648/12722218/24cf9ecc-c904-11e5-90db-0234de80408f.png)

but clicking on the blu link it opens the `Settings/Updates` tab and start fetching updates again.
Shouldn't it already know and show the available updates instead?

**Comment by 50Wliu** [comment]
Hi @mindrones, this is a duplicate of atom/settings-view#409 - please subscribe there for updates.

**Comment by mindrones** [comment]
ok thanks!
