### ISSUE TITLE
apm test/atom --dev --test displays wrong file names

### ISSUE THREAD

**Issue by deprint** [atom/atom#10631]
How to reproduce this bug:
1. Open a package or create a new one.
2. Run `apm test`. If you created a new package with package-generator, the specs will fail and display an error like `Expected 'life' to be 'easy'. (spec/testing-package-view-spec.coffee:5:20)`.
3. Rename `spec/testing-package-view-spec.coffee` (I renamed it to `testing-package-view2-spec.coffee`).
4. Run `apm test` again.

The specs fail (as expected), but instead of showing the new file path, it shows the old one.

I assume this is a caching issue, because clearing `~/.atom/compile-cache` fixes the bug for me.

```
$ apm test
...

TestingPackageView
  it has one valid test
    Expected 'life' to be 'easy'. (spec/testing-package-view-spec.coffee:5:20)


Finished in 0.306 seconds
3 tests, 9 assertions, 1 failure, 0 skipped

Tests failed
$ mv spec/testing-package-view-spec.coffee spec/testing-package-view2-spec.coffee 
$ apm test
...

TestingPackageView
  it has one valid test
    Expected 'life' to be 'easy'. (spec/testing-package-view-spec.coffee:5:20) <--Wrong path


Finished in 0.185 seconds
3 tests, 9 assertions, 1 failure, 0 skipped

Tests failed
$ rm ~/.atom/compile-cache -R
$ apm test
...

TestingPackageView
  it has one valid test
    Expected 'life' to be 'easy'. (spec/testing-package-view2-spec.coffee:5:20)


Finished in 0.316 seconds
3 tests, 9 assertions, 1 failure, 0 skipped

Tests failed
$ atom -v
1.4.1-2cf2ccb
$ apm -v
apm  1.5.0
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.6.4
```

**Comment by lee-dohm** [comment]
Would you mind reopening this on the https://github.com/atom/apm repository? That's where we track issues with the apm tool.

**Comment by deprint** [comment]
Is this really an issue with apm ?
AFAIK `apm test` is just an alias for `atom --dev --test spec` ([source](https://github.com/atom/apm/blob/master/src/test.coffee#L37)).

Using `atom --dev --test spec` instead of `apm test` shows the same issue, I only prefer `apm test` because it's shorter.

**Comment by lee-dohm** [comment]
Ah good point. Thanks for clarifying :grinning:
