### ISSUE TITLE
Cannot rename file from window titlebar on OS X

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#10633]
It is standard practice in OS X document editors to be able to rename a file by clicking the current filename in the titlebar of the window, at which point one is allowed to "type" in the title-bar to effortlessly rename the file. Try this in Pages/Numbers/Keynote/TextEdit. This should be possible in Atom.

**Comment by tangledhelix** [comment]
This isn't exactly "standard in OS X" - it's a common feature of Apple apps, such as the ones you noted. But it's not supported by Sublime Text, Microsoft Word, Atom, TextMate...

**Comment by alexchandel** [comment]
This is still an issue, stale-bot. It just hasn't been fixed.
