### ISSUE TITLE
div.container>div*5  not working in atom

### ISSUE THREAD

**Issue by longxianlin** [atom/atom#10636]
in sb, working,
in atom, not working.

**Comment by mnquintana** [comment]
You need to install [Emmet](https://atom.io/packages/emmet), a community package, to get this functionality in Atom, as this does not ship in Atom core.

If you've already installed Emmet, then feel free to open an issue on [Emmet's repo](https://github.com/emmetio/emmet-atom/issues)

Also, for future reference, please read [the Reporting Bugs section of the Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) before reporting an issue. Thanks!
