### ISSUE TITLE
Errors pop up VERY briefly, then disappear

### ISSUE THREAD

**Issue by kstenerud** [atom/atom#10630]
I have a ton of errors that pop up when I launch Atom, but I can't read what they are because they disappear so fast. Is there a way to see those errors without having to relaunch the app a whole bunch of times and try to screenshot them before they disappear?

**Comment by 50Wliu** [comment]
@kstenerud Try disabling the notifications package.  That'll make all the errors appear in the dev tools.  Alternatively, you can try opening the dev tools after the errors appear, but I forget if `notifications` will prevent them from showing up in the console.

**Comment by kstenerud** [comment]
Nope. Even when I disable the notifications package, the only thing that shows up in the console are a couple of deprecation warnings.

**Comment by benogle** [comment]
In the console you can run the following to get all the messages:

```js
n = atom.notifications.getNotifications()
n.map(function(notification){ return notification.getMessage() })
```

Each notification will have all the structured data used to display the error.

**Comment by lee-dohm** [comment]
Please let us know if @benogle's solution didn't answer your question!

**Comment by Tangled-tessellations** [comment]
Sorry to comment on a closed post, but a great package developed by @UziTech is [notifications-plus](https://atom.io/packages/notifications-plus). Adds an notifications log where you can review previous notifications. I was searching for awhile on this one before finally finding the package.

**Comment by 50Wliu** [comment]
@Tangled-tessellations you'll be glad to know that @UziTech is working on bringing at least some of those improvements back to the core notifications package :).  The notification log has already been implemented.

**Comment by Tangled-tessellations** [comment]
That is good to know! Thanks for both of your work on this
