### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by tommynsong** [atom/atom#10647]
I am receiving the following error upon startup of the application every time. The issue persist despite reinstall of the application and cleared the profile.

/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:358 Uncaught Error: Repository has been destroyed

<img width="556" alt="screen shot 2016-02-01 at 5 52 42 pm" src="https://cloud.githubusercontent.com/assets/577647/12735342/bb2b1aba-c90c-11e5-950b-1fc89b3554b0.png">

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/10647#issuecomment-178267281. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
