### ISSUE TITLE
Replace preview does not translates matching groups

### ISSUE THREAD

**Issue by roolo** [atom/atom#10642]
I found out, that when I use regex matching groups in both Find in project and Replace in project, the matching group is not translated in the preview (see picture). Anyway it looks like the actual replacement works fine.

![project_find_results](https://cloud.githubusercontent.com/assets/173141/12732116/4d8d5fb8-c934-11e5-8bbd-bb759c33deaa.png)

**Comment by 50Wliu** [comment]
@roolo Can you please move this over to the [atom/find-and-replace](https://github.com/atom/find-and-replace) repo?  Thanks!

**Comment by roolo** [comment]
kk, sry
