### ISSUE TITLE
native features in atom isn't complate

### ISSUE THREAD

**Issue by imasood** [atom/atom#10643]
i have problem with atom and It does not have enough native features.
i think if atom want to have good speed must be have native snippet, no packages.
check bottom review.
![atom](https://cloud.githubusercontent.com/assets/11756815/12732767/4959f88a-c94c-11e5-8d6d-5e2f0b52d9b0.png)

**Comment by 50Wliu** [comment]
We're aware that JavaScript support is lacking and are actively working on improving it.  Please see atom/language-javascript#137 for details (which is needed before JS-specific autocomplete can be added).

In addition, one of the main points of Atom is that it is meant to be extremely extensible...almost all of Atom's features are provided through packages (`tabs`, `tree-view`, `autocomplete-plus`, etc).

**Comment by imasood** [comment]
yes, packages is a good approach but atom isn't too light, when we install many package will be heavy surely for coding not so cool.
thanks for your response.
