### ISSUE TITLE
tracking tabs by events is a little mess

### ISSUE THREAD

**Issue by paulpflug** [atom/atom#10654]
for my package [foldername-tabs](https://atom.io/packages/foldername-tabs) I need to track the tabs to change their content. After long research this is the only way that works for me:

```coffee
# doesn't fire on reorder within or between panes, but tabs are getting repainted everywhere
atom.workspace.onDidAddPaneItem processAllTabs

atom.workspace.observePanes (pane) ->
 # doesn't fire on split called in tabs but fires on split called in tree-view
 # also doesn't fire on reorder between panes
 # pane.onDidAddItem processAllTabs 

 # fires on reorder between panes
 pane.onDidRemoveItem processAllTabs

 # fires on reorder within panes
 pane.onDidMoveItem processAllTabs 
```
In my eyes there are three issues:
- tabs shouldn't get repainted on move or reorder
- split called in tabs should work exactly as split called in tree-view
- how to get an event for reordering within a pane isn't obvious (`onDidRemoveItem`, but not `onDidAddItem`)

what do you think?

**Comment by lee-dohm** [comment]
What if there was an API in the tabs package for controlling the title text of the tabs themselves? You wouldn't need any of this tab tracking ... when a tab needed to know what text to put there, it could ask your package and you could give it the answer.

**Comment by paulpflug** [comment]
Of course, that would be more than awesome :smile:

**Comment by lee-dohm** [comment]
Would you mind opening an Issue on the tabs package requesting this then? Please @-mention me on the Issue if and when you create it.

**Comment by Ben3eeE** [comment]
Closing since the feedback got moved to an enhancement issue on the tabs package.
