### ISSUE TITLE
Line select move

### ISSUE THREAD

**Issue by joshuaneedham** [atom/atom#10664]
When I select an entire line by clicking on a line number and try to move the entire line or block of lines it doesn't grab the highlighted lines it just starts selecting other lines where your mouse pointer is.

An example is shown in the linked screencast.

http://screencast.com/t/c7c4dE16V

As you can see it simply doesn't allow locking in a line selection of any sort. So say I have a CSS file and I want to reorder properties by selecting a line and moving it down this isn't possible.

**Comment by lee-dohm** [comment]
I feel like this is a special case of https://github.com/atom/atom/issues/1909. If so, you can subscribe there for updates. Please let me know if you feel this isn't a duplicate.

**Comment by joshuaneedham** [comment]
You are correct. My apologies for not finding this other issue. Thanks for the link.

**Comment by lee-dohm** [comment]
It's quite alright ... I know what to search for :grinning: Thanks for the feedback! Please subscribe to the other issue for updates.
