### ISSUE TITLE
Make OS X CFBundleIdentifier distinct between stable and beta channels

### ISSUE THREAD

**Issue by int3h** [atom/atom#10672]
On OS X, Atom.app and Atom Beta.app should have different `CFBundleIdentifier`s set in their respective `Info.plist`. Doing so would allow both "Atom" and "Atom Beta" to appear in OS X's Launchpad, among other benefits.

**Current behavior**

The [beta download page](https://atom.io/beta) claims users can have stable channel releases and beta channel releases installed side-by-side. However, both have the same `CFBundleIdentifier` value set in their `Info.plist` file: `com.github.atom`. Because of this, even though the two releases have distinct file names (`Atom.app`, `Atom Beta.app`), parts of OS X can't differentiate between the two apps. 

In particular, only one of the two apps will ever show up in OS X's Launchpad (among other oddities relating to opening files from Finder, setting default file associations, and so on).

**Suggested behavior**

Beta channel releases should have a `CFBundleIdentifier` distinct from stable channel releases, e.g. `com.github.atom-beta`. (It might also be useful to change the identifiers of bundled apps, like `Atom Helper.app`, but I can't personally speak to this one way or another.)

When I manually made this change, I saw both "Atom" and "Atom Beta" appear in Launchpad simultaneously. Both apps seemed to function properly on my cursory checking.

**Atom Version:** stable 1.4.3, beta 1.5.0-beta3
**OS and Version:** Mac OS X 10.11.3, "El Capitan"

**Comment by revelt** [comment]
I came here looking how to set the default code editor as Atom Beta (instead of regular Atom), kind-of like [this](http://stackoverflow.com/a/22141204/3943954), but using Atom Beta as `Info.plist` value for `LSHandlerRoleAll`. Something like:

    defaults write com.apple.LaunchServices LSHandlers -array-add '{LSHandlerContentType=public.plain-text;LSHandlerRoleAll=com.ATOMBETA???;}'

I want that set so that when I open Hyper preferences, Atom Beta is opened, not regular Atom.

**Comment by chris-c-thomas** [comment]
Apologies, had opened an issue identical to this. Would love to be able to run these side by side correctly.
