### ISSUE TITLE
Could you guys stop expanding text?

### ISSUE THREAD

**Issue by corysimmons** [atom/atom#10688]
`input[tab]` in php html expands to `<input type="button" name="name" value="">`

You're just randomly guessing what I want and I end up having to delete it. Why not just expand to `<input>`?

**Comment by demhydraz** [comment]
That's because `input` is in your snippets, and tab is bound to `snipets:expand` by default.

**Comment by corysimmons** [comment]
Do you guys load a preset of snippets by default?

If so, why? And where do you even get them?

Who originally thought expanding `input` to `<input type="button" name="name" value="">` was a good idea at all?

**Comment by kaidesu** [comment]
Pretty trivial to customize based on your own needs. It's fully documented in the Atom Documentation:

https://atom.io/docs/v1.4.3/using-atom-snippets

**Comment by corysimmons** [comment]
>Pretty trivial to customize based on your own needs.

I'm here because it was developed based on one person's needs.

I'm asking you guys to modify your default snippets so they aren't full of junk.

Pretty valid issue imo.

**Comment by 50Wliu** [comment]
Please reopen this on [atom/language-html](https://github.com/atom/language-html), which handles HTML snippets.  Thanks!
