### ISSUE TITLE
installed packages don't list at "Packages" OSX

### ISSUE THREAD

**Issue by mamartins** [atom/atom#10681]
Hello guys,

I just noticed that I have lots of packages that are installed on my Atom that don't show up on the "Packages" Tab. They only appear at "Install" section after you search for them.

**Comment by 50Wliu** [comment]
Hi @mamartins, usually when this happens one of your packages is throwing an error and preventing the rest of the packages from displaying.  Please see atom/settings-view#591 for more information.  Thanks!
