### ISSUE TITLE
Show CPU usage for each package

### ISSUE THREAD

**Issue by mindrones** [atom/atom#10683]
I'm stuck with an Atom that [constantly hangs](https://github.com/atom/atom/issues/10159) (CPU at 100%) and I suspect the cause being an installed package.

I'd like to see the CPU usage of the each package's Atom Helper. 
My suggestion would be, in `Settings/Installed Packages`, for each installed and enabled package show the correspondent Atom Helper CPU usage.

It would be ok to have these numbers updated only when I first open Settings/Installed Packages, no need to have them update in real time.

Another viable option would be to assign names to Atom Helpers, so that I can see the offending package name by inspecting the Activity Monitor.
For example:

![screen shot 2016-02-04 at 13 20 39](https://cloud.githubusercontent.com/assets/1309648/12814811/313b4086-cb42-11e5-8415-bf3b045de00b.png)

-> what package is associated with the hanging Atom Helper?

**Comment by lee-dohm** [comment]
There is already a profiling tool built in to Atom:

https://atom.io/docs/latest/hacking-atom-debugging#diagnose-performance-problems-with-the-dev-tools-cpu-profiler

While it won't specifically finger individual packages or summarize based on package name, the stack traces it provides can give lots of clues.

As far as the stuck Atom Helper process goes, I have a few suggestions:

1. Clear out the `~/.atom/storage` directory
    1. Completely exit all instances of Atom
    1. Move or rename the `~/.atom/storage
    1. Launch Atom again
1. Disable the spell-check package (it sometimes gets into a weird state and causes the stuck Atom Helper thing you're seeing)

**Comment by mindrones** [comment]
Clearing out the `~/.atom/storage` directory seems to help: I've got an Atom Helper at 70% of the CPUO all the time, thanks for the advice! I'll keep testing and will report back on the issue mentioned above.

I still think being able to see CPU usage per package would be a killer feature to inspect this kind of problems, so please don't close this issue :)

**Comment by mindrones** [comment]
No, Atom still hanging at 100% of the CPU :/ 

(it could be something that corrupts the storage)

**Comment by benogle** [comment]
> I still think being able to see CPU usage per package would be a killer feature

At this time this is not possible because all packages are run on the main process.

**Comment by g13013** [comment]
I have multiple issues with CPU usage of Atom Helper, while i also suspect installed packages, I noticed the every action that involves using the network (ex: packages)  makes Atom Helper crazy !

**Comment by johnsonz** [comment]
I met this problem occasionally when I open many files and switch and edit them.

**Comment by lee-dohm** [comment]
We do occasionally revisit better ways to track down packages that consume too much CPU and visualize it in ways accessible to the typical Atom user. Since it isn't something that we're actively working on however, we're going to close this for now.
