### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by unluisco** [atom/atom#10685]
Whenever beginning Atom, does not respond

![atom](https://cloud.githubusercontent.com/assets/6332263/12816711/f9cda70e-cb1b-11e5-938c-63acf669b3ef.png)

Atom --version: 1.4.3
OS: OS X El Capitan 10.11.3
In the safe version this not happen

**Comment by lee-dohm** [comment]
If it doesn't happen when you start Atom with `--safe`, then it is almost certainly a package you have installed that is causing this to happen. Others have had good results with using the [package-cop package](https://atom.io/packages/package-cop) to narrow down which package is causing the problem.

Let us know what you find!

**Comment by unluisco** [comment]
@lee-dohm I tried each package and none causes the error, but I realize that is a problem of the RAM, it falls short.
Thanks.
