### ISSUE TITLE
Keep spaces vs tabs setting according to last used?

### ISSUE THREAD

**Issue by corysimmons** [atom/atom#10686]
When I toggle tabs/spaces in the editor, it works fine for the current file, but then I open a new file and it resets.

Is there a setting or way to keep the setting until I change it again?

The reason I ask is because I have to adhere to WPCS (tabs) during the workday, and in my free time I work on open source stuff and prefer 2 spaces. So it's just a pain having to go into config a few times every day instead of just being able to set this via the command palette.

**Comment by lee-dohm** [comment]
No, there isn't a setting that works the way you describe. This would probably be solved with https://github.com/atom/atom/issues/5168.

**Comment by corysimmons** [comment]
I don't see how this is related to project configuration.

When I do:

![image](https://cloud.githubusercontent.com/assets/224636/12835294/e7380146-cb7c-11e5-85e5-8fc521db36ba.png)

It should alter:

![image](https://cloud.githubusercontent.com/assets/224636/12835299/f4b19062-cb7c-11e5-82d9-4c80e1430c54.png)
