### ISSUE TITLE
Window load time spike when opening second instance

### ISSUE THREAD

**Issue by krainboltgreene** [atom/atom#10690]
![screen shot 2016-02-04 at 12 06 08 pm](https://cloud.githubusercontent.com/assets/334809/12828166/04545d50-cb38-11e5-9151-f2e3a5a950f6.png)

![screen shot 2016-02-04 at 12 08 44 pm](https://cloud.githubusercontent.com/assets/334809/12828179/18b4ae4e-cb38-11e5-849d-a05415444750.png)

![screen shot 2016-02-04 at 12 09 32 pm](https://cloud.githubusercontent.com/assets/334809/12828212/4c9c0676-cb38-11e5-8a1d-47efc2767835.png)

**Comment by benogle** [comment]
What does starting 2 atom windows via `atom --safe .` report?

**Comment by krainboltgreene** [comment]
Nothing specific but now its 500ms. Looks like it might be a plugin?

**Comment by benogle** [comment]
Yeah, if faster in safe mode, it's a package. That timecop view should show you which package is slowing things down.

**Comment by krainboltgreene** [comment]
Nothing accounts for a total of 9s :/

**Comment by krainboltgreene** [comment]
Okay, some more information:

  - It seems to only happen when I open from the command line `atom .`
  - It seems to only happen when I have a different project open `~/code/krainboltgreene/foo` and `~/code/krainboltgreene/bar`
  - It *waits* until I switch to the application to open the window.

I no longer think this is a package issue.
