### ISSUE TITLE
Atom does not open new window until it is has focus - when opening file/directory via command line

### ISSUE THREAD

**Issue by sgtsquiggs** [atom/atom#10709]
I am an avid user of the `atom` command line script on Mac OS X Yosemite. I have noticed that Atom does not create a new window for a file/folder until it has been give focus (usually by clicking the icon in the dock).

Steps to reproduce;
1. Launch atom, open any file/directory
2. Open Terminal/etc
3. Use `atom` command to open another file/directory

Expected results:
- Atom opens new window, becomes focus(maybe?)

Actual results:
- Nothing happens until Atom has been given focus

Deets:
Atom 1.4.1
Mac OS X 10.11.2
/usr/local/bin/atom (no version but md5 is 00048d82f98c087e579f24ed32f8c7b2)

**Comment by dcalhoun** [comment]
I am also experiencing this consistently. When using the CLI (e.g. – `atom path/to/dir/`), Atom does not gain focus or open the directory until I manually give Atom focus by app switching or clicking the dock icon.

###### Environment
- Atom 1.5.3
- Mac OS X 10.11.3 (15D21)

**Comment by natew** [comment]
Also get this actually very often on Atom 1.5.3 Mac 10.11.
