### ISSUE TITLE
Switching tabs restarts nodemon

### ISSUE THREAD

**Issue by OKNoah** [atom/atom#10702]
Here is the corresponding issue on the Nodemon repo: https://github.com/remy/nodemon/issues/770

Basically whenever I switch tabs with `nodemon` running in the same project directory, it detects a file change and restarts the given process.

**Comment by lee-dohm** [comment]
This is probably because you have the [autosave package](https://atom.io/packages/autosave) enabled. It saves the file when its tab loses focus.

**Comment by OKNoah** [comment]
@lee-dohm I've disabled that package, but the problem still occurs.

**Comment by lee-dohm** [comment]
Have you restarted Atom? Can you reproduce the problem in Safe Mode?

To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by ex1machina** [comment]
I'm having a similar problem. I disabled the autosave package but I'm still having this issue. I've discovered two things:

1. The file that nodemon says it's restarting due to a change in is the file I'm tabbing _to_, not _from_.
2. **It only triggers if that file has uncommited changes in git**

I've disabled all my community packages and it's still happening so it seems to be an issue with my core atom. Currently running 1.4.3

**Comment by lee-dohm** [comment]
@ex1machina Can you reproduce the issue in Safe Mode? Simply disabling community packages isn't all that Safe Mode does and some packages don't completely remove themselves when disabled. The process that I mention above covers both contingencies.

**Comment by ex1machina** [comment]
@lee-dohm yup, still doing it in safe mode

**Comment by ex1machina** [comment]
Just an update, I removed my .atom config and that still didn't fix the issue, but I reinstalled nodemon (was running 1.8.0 and installed 1.8.1) and I can't seem to replicate the issue now.

@OKNoah what version of nodemon do you have installed?

**Comment by OKNoah** [comment]
@ex1machina Thanks, updating nodemon fixed it.

**Comment by lee-dohm** [comment]
Thanks for following up! Glad to hear that this is fixed for both of you :grinning:

**Comment by mnquintana** [comment]
Unfortunately I can reproduce this with nodemon 1.9.2 and Atom 1.9.0-dev-e5e1226 in safe mode 😢

**Comment by Kaijun** [comment]
Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
nodemon: 1.9.2

still reduces this issue even running under --save mode. 
Only switching tabs won't make nodemon restart, but selecting files in TreeView will

**Comment by maciejmyslinski** [comment]
It occurs for me also even when switching tabs.
Atom: 1.8

**Comment by benbeadle** [comment]
Was having this exact issue. Updating nodemon fixed the issue:

```
npm uninstall -g nodemon && npm install -g nodemon
```

**Comment by markhealey** [comment]
Tried that (updating `nodemon`) and it's still happening.

**Comment by Ancinek** [comment]
Having the same issue. Also updated nodemon and still the same.

**Comment by sbr464** [comment]
I had had to add remove global nodemon and yarn remove/add  it in the local dev-dependencies of the project. Not sure which fixed it, but it resolved.

**Comment by lee-dohm** [comment]
Thanks everyone for your interest.

This isn't something that we have the resources to spend time investigating. It sounds like there's a workaround mentioned in the above-linked issue. If anyone feels there is an Atom bug here, please:

1. Show us logs (other than nodemon's) or other evidence that shows that Atom is **writing** to files outside of the `.git` directory in a project when switching tabs
1. Supply us with detailed steps to reproduce the behavior in item 1 in Safe Mode

Beyond this, all other data we have suggests that Atom is doing the right thing when switching between active files. If people can supply us with the information I've mentioned above, I'll reopen this issue and ask someone to take a look.

Thanks again.
