### ISSUE TITLE
Support more languages with new node-spellchecker

### ISSUE THREAD

**Issue by juh2** [atom/atom#10705]
For years users who write non-english texts are desperatey waiting for spell checking in more languages than only English.

[From the bugtracker of node-spellchecker](https://github.com/atom/node-spellchecker/issues/4) I guess that everything is ready to get into Atom.

So please make non-english speakers happy.

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/atom/spell-check/issues/11. Please subscribe there for updates.
