### ISSUE TITLE
UI behaves weird when scrolling / focusing

### ISSUE THREAD

**Issue by der-Daniel** [atom/atom#10715]
Hi,

I am using the latest stable release and when I am scrolling or focusing an element, the UI does things like this:

![](http://i.imgur.com/F25PwZ0.png)
![](http://i.imgur.com/5z3AQnM.png)
![](http://i.imgur.com/uBSp92e.png)

I found some similar issues, but none of them fix it for me.
This behavior also appear in safe mode. I do not have any packages installed yet.

I am using a DELL XPS 15 with a 3200x1800 resolution.
This high resolution made trouble before.

Does anyone have experienced this before?

Cheers

**Comment by der-Daniel** [comment]
DELL has a onboard INTEL graphic card.
If I am using atom with the dedicated Nvidia card, this does not happen..

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using? (Please give the full version number. You can copy it from the About view.)
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by der-Daniel** [comment]
Hi,

I am using Ubuntu 15.10 (64 Bit), my Atom version is 1.4.3.
I already tested it in safe mode, but that did not fix it.

There was an issue with the xorg/xserver driver packages in connection with applications in full screen. Apps in full screen were laggy.. This was discussed here https://github.com/Microsoft/vscode/issues/162 and here https://github.com/atom/atom/issues/9724. Using the Oibaf PPA solved the laggy behavior in full screen.

I the weird UI rendering thing may be still related to the Ubuntu xserver driver environment. The only thing that does not fit in, is that with earlier versions do no show this behavior.

**Comment by fmntf** [comment]
Same issue on 1.4.3 and 1.5.3.
The issue started when I switched to Ubuntu 16.04 (everything was fine on 15.10). I have a notebook with Intel+nVidia GPUs (using Intel only).

**Comment by halfstrik** [comment]
I also encounter this problem while scrolling and selecting with mouse.
Atom 1.5.0 and 1.5.3
Debian Stretch on laptop with GeForse GTX 960m, drivers xserver-xorg-video-nouveau 1:1.0.12-1+b1

**Comment by massimiliano-scifo** [comment]
Same for me issue for me:

Atom 1.5.3, Debian Jessie, Geforce gtx 860m using nouveau driver

**Comment by massimiliano-scifo** [comment]
updating to the latest driver fixed my error, so this issue is not related to atom itself

**Comment by der-Daniel** [comment]
@massimiliano-scifo, on my machine the latest update fixed it, too.
@others, please notice, that I am using the Oibaf PPA. You may try that..

**Comment by 50Wliu** [comment]
Thanks for the updates @der-Daniel and @massimiliano-scifo!
