### ISSUE TITLE
Directory path on titlebar is not following selected file

### ISSUE THREAD

**Issue by javadba** [atom/atom#10710]
The screenshot below shows the titlebar is pointing to ~/.atom/timeline.txt  This is especially troubling because the file path is actually /nok/timeline.txt    So the result is the user (myself..) panics thinking that the original file were lost or displaced.

In fact the only thing happening is that atom is handling the current directory separately from the current file/buffer. It then has a bug in the current directory - using the wrong one. Atom then combines the (incorrect) directory with the current buffer name and we end up with a non-existing path. 

This is annoying because what happens when we have multiple files with the same buffer name but in different directories ?  that is in fact my case here - i have two different timeline.txt files and I do not know to which one atom is referring.

If it helps I am on Yosemite.

The screenshot shows that Atom mixed up the path of the current file "timeline.txt" with the prior one "settings.xml".

![screen shot 2016-02-05 at 1 47 38 pm](https://cloud.githubusercontent.com/assets/410769/12860089/31100cb8-cc0f-11e5-99c2-3640fa9556fc.JPG)

**Comment by otolabqu** [comment]
I noticed the same thing.

**Comment by javadba** [comment]
Any action on this?  This behavior may make me completely dump Atom.
