### ISSUE TITLE
Atom icon on windows 10

### ISSUE THREAD

**Issue by 3nk** [atom/atom#10716]
Hi,

On windows 10,  after some time, the Atom icon disappear from task bar
(even if you reinstall)

![missing](https://cloud.githubusercontent.com/assets/5038522/12865921/fe9a9cdc-ccbb-11e5-8903-e399c86a9346.png)

**Comment by paulcbetts** [comment]
Unpin it and repin it, this is fixed in the very latest Squirrel but that hasn't hit Atom yet

**Comment by Sjaak1** [comment]
It happened to me after every update of Atom. I fixed it by changing the icon in the properties of the shortcut to 
%USERPROFILE%\AppData\Local\atom\app.ico

**Comment by damieng** [comment]
Latest Squirrel has hit master, should be fixed in the next release of Atom.
