### ISSUE TITLE
Adding icons for the interface

### ISSUE THREAD

**Issue by abdelouahabb** [atom/atom#10711]
Hi,

Is there a way to add icons like this: 
![sans titre](https://cloud.githubusercontent.com/assets/2527234/12861443/b01a68c4-cc63-11e5-9895-09e1533bf042.png)

So a user for example bind an icon to an operation.

**Comment by lee-dohm** [comment]
There is the [tool-bar package](https://atom.io/packages/tool-bar) (and probably others) that provide this kind of capability.

Let me know if I misunderstood :grinning:

**Comment by abdelouahabb** [comment]
wonderful :dancer: 
Thank you!

![sans titre](https://cloud.githubusercontent.com/assets/2527234/12861981/a0040aae-cc67-11e5-9c42-35029d35d2a9.png)
