### ISSUE TITLE
Graphical glitches that occur under Arch Linux

### ISSUE THREAD

**Issue by fusion809** [atom/atom#10714]
Hi,

I have noticed that Atom 1.4.3 (have not noticed this issue with earlier releases of Atom) keeps experiencing graphical glitches, wherein tab titles, the toolbar and file windows become invisible or otherwise visually obstructed. Now to be clear by "file windows" I mean the windows (under the tab handles) wherein the contents of the file being edited is shown and can be edited, if my terminology is incorrect please correct me so that in future I can use the correct terminology when reporting Atom issues. In case my explanation is unclear I have taken screenshots of these bugs. These bugs seem to be plugin-independent as running Atom in safe mode makes no difference to these bugs. 

In this first example, you can see the second tab is partially obstructed in its view from the glitch.

![](http://imgur.com/a9IO6Sn.png)

In this second example, you can see parts of the file window and the left and centre tabs obstructed in their view:

![](http://imgur.com/a31M6oZ.png)

I know that some things seem to trigger its appearance, like scrolling down on larger files, switching between presently-opened windows, _etc._ If you want to know how I installed Atom well I installed it from my own PKGBUILD (which builds the Atom package from source code not from a Debian or RPM binary) which you can find [here](https://github.com/fusion809/PKGBUILDs/blob/master/atom-editor/PKGBUILD). I have observed this bug under two different desktop environments: Cinnamon and KDE Plasma 5 and with several different GTK themes. 

Oh and yes these bugs seem to be limited to just Atom. All other programs seem to be devoid of this bug. 

Thanks for your time,
Brenton

**Comment by demhydraz** [comment]
It doesn't happen here with Arch Linux x86_64, Atom 1.5.0-beta3 and Cinnamon.

**Comment by tong** [comment]
Same glitches here since 1.4.3.
Debian 8, Linux x86_64 4.3.0, Openbox, ATI (fglrx)

**Comment by tong** [comment]
Also remains after downgrading to 1.4.2.

**Comment by fusion809** [comment]
I switched to Atom 1.5.0-beta3 to see if this bug occurs under it and it did. Is there any interest in fixing this bug or is this bug likely to be ignored due to how few people have come forward with this bug?

**Comment by 50Wliu** [comment]
@fusion809 The underlying issue is most likely a problem with Electron.  Can you try building #9627 and see if that helps?

**Comment by fusion809** [comment]
Could ya point me to the specific comment with the details of how to do the build as that issue is long and it's not obvious to me, at least, where the build instructions are.

**Comment by fusion809** [comment]
Bumping to electron 0.36.7 in package.json before building made no difference to this graphical bug... And yes, I closed all Atom windows and opened a new Atom instance, yet still the bug persists.

**Comment by michalkasprzak** [comment]
I'm experiencing the same problem unfortunately...

![](https://cloud.githubusercontent.com/assets/6242859/12958603/c0440778-d032-11e5-887b-560b4d6fa9c4.png)

I'm using Atom 1.5.0-beta3-6d56185 compiled from GitHub under Arch Linux with GNOME3. I hope that it will be fixed soon, because it makes writing anything difficult. I don't have a problem like this with Chrome or any other application, so I believe that it is related to Atom or Electron.

**Comment by fusion809** [comment]
I have since switched distros from Arch to openSUSE Tumbleweed and are no longer experiencing this bug as a result. So I'm going to let those that are still experiencing this bug to continue on the discussion here.

**Comment by markbaas** [comment]
Problem is related to electron, I experience the same in the official slack linux client.

**Comment by atd** [comment]
Same problem here with Debian testing and GNOME

I cannot find the electron issue

**Comment by markbaas** [comment]
I fear it has to do with the latest intel driver. I downgraded and problem was solved.

**Comment by michalkasprzak** [comment]
I've found solution to this problem. At least it works for me.

As I said, I'm using Arch Linux. The solution is to switch acceleration method to UXA (default is SNA), as described [here](https://wiki.archlinux.org/index.php/Intel_graphics#SNA_issues). At the same time I turned on DRI3, but I think the problem is rather related to acceleration method than DRI version. If I'm not wrong this method probably should work for other distributions too.

**Comment by atd** [comment]
Thank you so much @michalkasprzak You are awesome! It worked for me too! I can use Atom again!

In Debian, you need to place a file in `/etc/X11/xorg.conf.d/20-intel.conf` with

```
Section "Device"
 Identifier "Card0"
 Driver "Intel"
 Option "AccelMethod" "uxa"
EndSection
```

and restart the computer

**Comment by tong** [comment]
@michalkasprzak @atd Yeah, seems to work.
Note: your `xorg.conf.d` might be at `/usr/share/X11/xorg.conf.d/` if not at `/etc/X11/..`

**Comment by atd** [comment]
@tong both locations work in Debian testing

**Comment by tru** [comment]
This must be a Electron shell problem. I see the same in the slack desktop app and it's also using electron. I can change the AccelMethod to UXA and it fixes the problem - but it gives all other applications a huge performance penalty (Jetbrains stuff is really sluggish) - so that's not the right solution. All other apps works fine with SNA.

**Comment by synthead** [comment]
I'm also experiencing these issues on Arch Linux.

**Comment by bryanspears** [comment]
The title is a bit misleading as this is not exclusive to Arch. I have this issue on Ubuntu 17.04. The above posts are correct, it's `AccelMethod` being `sna` that causes this problem.

**Comment by aauren** [comment]
Just wanted to add my thanks to @michalkasprzak as well! I have been working around this issue for months now, and I finally sat down and tried to figure out a fix for this and after Googling for hours stumbled across this thread and it fixed everything for me. The performance penalty is worth it to not have the distortion across all of my Electron based apps.

**Comment by anhdle14** [comment]
Actually the ArchLinux wiki has already covered this at: https://wiki.archlinux.org/index.php/Intel_graphics#Troubleshooting. 

I think all the Electron based app are infected. In my case it was VSCode that caused the issue, just by drag and drop a file. The quick fix is changing AccelMethod, but it is unbearable for any other apps.

Hope this could be fix soon.
