### ISSUE TITLE
Disabled packages show no README

### ISSUE THREAD

**Issue by mindrones** [atom/atom#10727]
In the Settings/Packages, clicking on disabled packages, in the README section I get this:

![screen shot 2016-02-08 at 11 40 14](https://cloud.githubusercontent.com/assets/1309648/12883515/cbce9af8-ce58-11e5-983a-92231d3ea6fa.png)

while if they're enabled at Atom startup they show the README correctly.

*EDIT - Specs*
- Atom: 1.4.3
- OS: OSX Yosemite 10.10.5 (14F1509)

**Comment by amytruong** [comment]
Hi! 
What OS and version of Atom are you on? Thank you!

**Comment by mindrones** [comment]
Hi! I've added my specs to the first post so that others would find them easily, thanks!

**Comment by lee-dohm** [comment]
@mindrones I suspect this belongs on the [settings-view repository](https://github.com/atom/settings-view) unless there is a specific reason you believe this is an Issue with Atom Core?

**Comment by mindrones** [comment]
@lee-dohm ah right, should I there and close this issue?

**Comment by lee-dohm** [comment]
Yes, please @mindrones. Thank you :grinning:
