### ISSUE TITLE
Multi-select background isn't cleared after ESC

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#10722]
Selecting a few lines of code with `ctrl+d` and then hitting `esc` doesn't clear the highlight/background of the lines.

visual example:
![](http://ibin.co/2W9Wstnr806c)

**Comment by 50Wliu** [comment]
I use Ctrl+D a lot and haven't encountered this before...is your gif being recorded in safe mode?  And what Atom version/OS are you using?

**Comment by alexandernst** [comment]
I just realized this is a bug in "highlight-line" package, not in Atom itself. I'll close this and open a bug in that package.

**Comment by alexandernst** [comment]
Just in case somebody end up here after a Google search: https://github.com/richrace/highlight-line/issues/79
