### ISSUE TITLE
Change default keymap for Windows

### ISSUE THREAD

**Issue by doberkofler** [atom/atom#10728]
I did spend quite a while to figure out on how to get Atom working on Windows with a non-US keyboard. Especially the backslash did not work at all because the default key bindings overwrite some needed keys.

The problem can be simply reproduced by trying to enter a backslash (for example) on a German keyboard.

The simplest solution I found is to just disable some bindings:
```
'.platform-win32 .editor':
  'ctrl-alt-[': 'unset!'
  'ctrl-alt-q': 'unset!'
```
and I would recommend changing this as a the default.

**Atom Version:** 1.4.3
**OS and Version:** Windows 7 x64

**Comment by 50Wliu** [comment]
@doberkofler Please see atom/atom-keymap#35 for the core issue, and also some workarounds.  Those default keybindings are highly unlikely to be changed.
