### ISSUE TITLE
Atom freezes Spotlight

### ISSUE THREAD

**Issue by robertdolca** [atom/atom#10723]
When trying to search for Atom in Spotlight it freezes. How can I investigate the cause?

Reproduced with:
- 1.4.3
- 1.5.0 beta 3

![screen shot 2016-02-07 at 18 39 20](https://cloud.githubusercontent.com/assets/383543/12873628/3e99bc54-cdcb-11e5-9dfe-d369af33399e.png)

**Comment by 50Wliu** [comment]
@robertdolca Please try clearing your 10 most recent documents by opening 10 new files through Atom.  See https://github.com/atom/atom/issues/10071#issuecomment-178841669 for more details.
