### ISSUE TITLE
Atom Helper process not finished

### ISSUE THREAD

**Issue by kim612** [atom/atom#10734]
Hi,

I found Atom Helper (/opt/homebrew-cask/Caskroom/atom/1.4.1/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper in my case) process is not finished, so if I run and quit Atom 6 times, six Atom Helper processes are running even after quitting.

![screen shot 2016-02-09 at 10 41 43 am](https://cloud.githubusercontent.com/assets/861202/12905338/bd6b82b6-cf19-11e5-91aa-2e91a65ad4c9.png)

**Comment by lee-dohm** [comment]
I'm unable to reproduce this using Atom v1.6.0-dev-ed43eda or v1.4.3 on Mac OS X 10.11.3.

Can you reproduce this on the latest version of Atom? Also can you try installing the application from the website to reproduce this?

**Comment by kim612** [comment]
Hi,

I rebooted my mac, and it was solved. 
Sorry and thank you!

Best,

**Comment by lee-dohm** [comment]
I'm glad to hear that it is fixed for you! Thanks for following up :grinning:
