### ISSUE TITLE
Tabs to Spaces screws up middle indentation

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#10736]
Consider this line, in Atom 1.4.3 with a tabLength of 8:

``` lisp
(E100_C     (dP -0.1)   (dT 100))
```

Using the Tabs to Spaces command should produce 9 spaces for the two consecutive tabs. However, Atom produces 16 spaces, pretending the line isn't indented in the middle. The choice of 8 is unimportant: Atom incorrectly converts tabs to spaces for all tabLengths.

**Comment by lee-dohm** [comment]
I'm not sure I'm understanding what you're saying is the problem. If you tell Atom that the tabLength is 8 then when you press <kbd>Tab</kbd>, it will either insert a tab character or eight spaces. Otherwise, they would be tab stops, which isn't a feature that Atom provides.

**Comment by alexchandel** [comment]
Atom clearly does provide tab stops, because pressing `tab` indents to the next multiple of `tabLength`, and tab characters extend to multiples of `tabLength`. Atom's implementation may be broken, but it's still there. The problems is that even though they are indented correctly, they are not treated correctly when converting between tabs and spaces.
