### ISSUE TITLE
Atom Crash on file actions from networked location (UNC)

### ISSUE THREAD

**Issue by MadLittleMods** [atom/atom#10730]
Atom 1.4.3 and 1.5.3 with no packages installed on Windows 10.

I have [file sharing enabled on a OSX](https://support.apple.com/kb/PH18707?locale=en_US&viewlocale=en_US) and then opening a project on that networked drive in Atom on a Windows 10 machine.

Very consistently whenever I do a `npm install` on the OSX machine, Atom will crash. I can reproduce it most consistently with `npm install x` or `git checkout x` commands but also happens with file actions like trying to save a new file and mostly doesn't happen when making manual edit. This happens regardless if I have the file open or not. Also happens regardless if the tree view is toggled open.  I have also had it happen when saving a new file in the project on the Windows machine or on the OSX side.

When the project is open, it shows the UNC path `\\some-mac\Macintosh HD\some-project`

Nothing appears in the devtools even when looking remotely `--remote-debugging-port=9224` but I am totally open to debugging this further with some instructions.

**Comment by MadLittleMods** [comment]
Directly related to:

 - Windows - editor crashes when creating a file in remote directory: https://github.com/atom/atom/issues/10131
 - Atom on windows crashes a lot of it's attempting to do filesystem operations on a mounted network drive : https://github.com/atom/atom/issues/5298

Related issues:

 - Accessing files on network drives is slow: https://github.com/atom/atom/issues/1766

**Comment by Costava** [comment]
:+1: Can reproduce with Atom 1.5.4 on Windows 8.1 (accessing OS X file share).

**Comment by milosa** [comment]
I have the same problem. I have atom installed on windows 7, and work with files through a network share on a OSX machine. When I create a file, delete a file, move a file or rename a file in a folder on that network share using atom, it will crash immediately. Sometimes it will even crash when a file is created without atom.
