### ISSUE TITLE
All files in Tree marked as New(Green)

### ISSUE THREAD

**Issue by rybridge** [atom/atom#10746]
I just updated to Atom 1.5 and now when opening any folder within a local repo each file in the tree is marked as green (marked as a new file). If I click and open the file it un-marks it green and goes back to clean. Note: The files are marked as green but Git doesn't pick them up as new files so I can still work with the files per normal.

I ran in Safe mode and was still able to reproduce the bug. I also tried different UI and Syntax themes and it still occurs.

I did notice that if I open the project from the root of the repo it works as intended, and the issue only seems present when opening a folder deeper within the repo.

#### Tree in root Git project
![root](https://cloud.githubusercontent.com/assets/419370/12931270/81d1bd14-cf42-11e5-8bbf-a055d96a4cd1.png)

#### Tree in sub dir of same project (files in screenshot are **NOT** new)
![subdir](https://cloud.githubusercontent.com/assets/419370/12931298/aaf6f114-cf42-11e5-9592-641f13b8cbcd.png)

**Comment by rybridge** [comment]
Additional note. Happens on all projects and doesn't seem to be limited to that one project above.

**Comment by adambuczynski** [comment]
Yep, have the same thing since Atom 1.5.0. Only non github hosted repositories seem to be affected from what it seems;

![image](https://cloud.githubusercontent.com/assets/490562/12935138/a3b98900-cff8-11e5-9c89-d4b56fc2924a.png)

**Comment by silentsokolov** [comment]
+1

**Comment by AnimiVulpis** [comment]
I have the same problem, but *not* limited to non-github repositories.

* opening atom with `non-root` folder displays everything as added
* adding a `sub-folder` after opening the `root-folder` works (sub folder shows the repo-book-symbol )
* adding the `root-folder` after opening a `sub-folder` keeps everything in the subfolder as added

____
* MacOS 10.11.3
* atom 1.5.0

**Comment by oakio** [comment]
Related issue: https://github.com/atom/tree-view/issues/717

**Comment by MattiJarvinen-BA** [comment]
Can confirm @AnimiVulpis happens also on github repositories. Opening at project root ( containing .git folder instead of the part I'm working with ) fixed this for me.

**Comment by oakio** [comment]
I have found the reason for such behavior.
Atom v1.5 includes a pull request https://github.com/atom/atom/pull/10249 which updates the version git-utils up to 1.4.0 (see https://github.com/atom/atom/commit/a962bba3a1299a7e27955c3c63dd3a16af4418ce) which changed the original behavior: https://github.com/atom/git-utils/commit/d4b0127852ff0857ca3cdb7e61c094e1c8503d47

**Comment by rkrv** [comment]
Same issue here.

**Comment by sebastienpires** [comment]
Same here :hand:

**Comment by WolfieZero** [comment]
I've come across this issue today updating to 1.5.0, and it only affects opening Atom in a sub folder of a git project rather than the root.

The image below shows the root on the left with the sub-folder on the right.

![git-issues](https://cloud.githubusercontent.com/assets/648761/12952694/46807fd4-d00f-11e5-91f7-71a6bf349695.png)

Tried with different UIs and all the same.

**Comment by joshaber** [comment]
We just released 1.5.1 which fixes this. Thanks for all the reports and sorry for the hassle!

![](http://www.reactiongifs.com/r/swag.gif)

**Comment by rybridge** [comment]
Works great on 1.5.1, thanks!

**Comment by WolfieZero** [comment]
Smooth! It works perfectly, thanks!

**Comment by IvonneQ21** [comment]
Having this issue. The folders that are highlighted are not accessible.

**Comment by sweetspot-mgdepoo** [comment]
I'm having this issue. The issue is that I'm on a mercurial repo (using https://atom.io/packages/atom-hg) but git version control kicks in, it shows I'm in master and all files are new. If I issue a git init + git add . the files go back to white. ping @chrishiestand

**Comment by chrishiestand** [comment]
@sweetspot-mgdepoo I haven't had this issue recur for me (just with git). I recommend looking for an issue which covers this and if there isn't already one, file a new one.

**Comment by atakanaydin** [comment]
Hi, issue born again. Why my local folders are green ? :/ its sad.
<img width="887" alt="screen shot 2017-06-15 at 11 11 40" src="https://user-images.githubusercontent.com/21036623/27171806-7d55f8fc-51bb-11e7-955a-518aee6923ce.png">

**Comment by Leohige** [comment]
![image](https://user-images.githubusercontent.com/7697524/28990678-06cd1554-7956-11e7-9bc2-d9048514477a.png)
My folders are green too... I installed Atom just now

**Comment by luismiguells** [comment]
I have the same issue

**Comment by Smus** [comment]
Same issue 1.12.1 64x

**Comment by gabrielebisogno** [comment]
i have the same problem

**Comment by pyaephyoswe** [comment]
ok , Thank  You.

pyaephyoswe569@gmail.com

**Comment by Lananass** [comment]
I have the same issue and my nodes_modules folder is grey... I've tried deleting nodes_modules folder and running 'npm install' and 'react-native run-ios'. 
No luck :(. I'm extremely new to this so would appreciate any tips out there

**Comment by adamreisnz** [comment]
I haven't experienced this anymore for a very long time.

**Comment by daria2303** [comment]
Atom 1.25, the same, on Mac

**Comment by tcador** [comment]
I had the same issue on 1.24.0. I downloaded 1.25.0 manually (without going thru the update), then re-added my project folders and they are no longer green.

**Comment by daria2303** [comment]
Thanks, unfortunately doesnt work for me, any other ideas?

**Comment by Arcanemagus** [comment]
It looks like everyone commenting on this issue saying they are seeing it after this was fixed is on macOS. It's possible you may all be hitting https://github.com/atom/atom/issues/1890, but the symptoms reported do seem to be a bit different.

Would somebody that is able to reproduce this please file a **new** issue and completely fill out the template? Steps to reproduce, like an example repository to clone, would be immensely helpful in tracking down this new issue.

Thanks!

**Comment by jay3183** [comment]
I am still getting this issue I am on windows

**Comment by mylvoh0714** [comment]
Same issue (;~~~;)
