### ISSUE TITLE
Blue notifications "close all" button does not work 

### ISSUE THREAD

**Issue by AgentME** [atom/atom#10749]
I use a plug-in which displays blue notifications at the top right on occasion. The notifications have a "close all" button, but the button doesn't do anything. The "close all" button on red notifications works fine though. I hope this is enough information; I'm not sure if there's anything unique about the plugin's notifications.

Original issue: https://github.com/AtomLinter/linter-flow/issues/46

**Comment by mnquintana** [comment]
This issue was moved to atom/notifications#110
