### ISSUE TITLE
unable to fetch in submodule path

### ISSUE THREAD

**Issue by sheenaagrawal** [atom/atom#10741]
I'm trying to build the PX4 flight stack firmware using the info given in this link : http://dev.px4.io/starting-building.html

I'm getting this error
```

Submodule 'jMAVlib' (https://github.com/PX4/jMAVSim.git) registered for path 'jM
AVlib'
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=No error

```
Unable to fetch in submodule path 'mavlink/include/mavlink/v1.0'
Checked NuttX submodule, correct version found
Checked Tools/gencpp submodule, correct version found
Checked Tools/genmsg submodule, correct version found
Checked Tools/jMAVSim submodule, correct version found
Checked Tools/sitl_gazebo submodule, correct version found
Checked cmake/cmake_hexagon submodule, correct version found
Checked mavlink/include/mavlink/v1.0 submodule, correct version found
Checked src/lib/DriverFramework submodule, correct version found
Checked src/lib/dspal submodule, correct version found
Checked src/lib/ecl submodule, correct version found
Checked src/lib/matrix submodule, correct version found
Checked src/modules/uavcan/libuavcan submodule, correct version found
Checked unittests/googletest submodule, correct version found
make -C /c/px4/Firmware/build_px4fmu-v2_default -j4 --no-print-directory
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [px4fmu-v2_default] Error 2
```
```

**Comment by 50Wliu** [comment]
@sheenaagrawal I think you posted this on the wrong repository :wink:.
