### ISSUE TITLE
Everything is super slow in hud 4k

### ISSUE THREAD

**Issue by Oblik-Design** [atom/atom#10750]
![capture d ecran 2016-02-09 a 21 29 53](https://cloud.githubusercontent.com/assets/9968597/12937216/556211f2-cf74-11e5-8cce-8858379e6b84.png)
scrolling, typing . everything is slooow, I mean ridiculous. I've got a monster computer.

**Comment by ivanychev** [comment]
Confirm that. FPS drops to 15-20 when scrolling. ST3 runs at 60.

MacBook Pro 13' (OS X 10.11.3)
Atom 1.5.3

**Comment by Oblik-Design** [comment]
mine's way worst, 2fps... and i've got a 32 gig 2015 dual graphics card 15inch quad i7 macbook pro connected to an asus 32 inch pq321q screen (amazing screen btw). I've got no issues running anything else but atom, so I use brackets... but ...

**Comment by 50Wliu** [comment]
Can someone please try using the latest master version and see if that solves your performance problems?  Thanks.

**Comment by burabure** [comment]
happens to me on a 4k monster running the latest atom on Ubuntu 16.04

**Comment by lee-dohm** [comment]
@Oblik-Design Did you ever try a newer version of Atom to see if it cleared up your problems?

We need more information for this to be actionable. There are plenty of other people running Atom with high resolutions and no problems. We need to know what is unique about your situation before we can attempt solving it.

**Comment by burabure** [comment]
seems like 1.9.0 beta fixes this https://github.com/atom/atom/issues/10518

**Comment by PIXPOINT** [comment]
I found a solution. Atom was very slow on my Windows 10 PC... But if you run atom "as administrator" , boom. all is super fast.

I had problems with scrolling and masking text. Now it is noticeably faster.
Maybe that helps someone...
