### ISSUE TITLE
Using the Close Tab command on an 'empty' window will close the window itself.

### ISSUE THREAD

**Issue by karloluis** [atom/atom#10752]
When closing multiple tab using the CTRL+W command (Windows) I tend to hold down the button. Recently noticed that doing this no longer leaves and empty atom client/window open, the one where the tips cycle in the backdrop. I believe that it used to be so that if all the tabs where closed the command would not perform any action, which I prefer. If I'd wanted to close the whole window I'd use the proper command, in this case CTRL+SHIFT+W. 

This seems like a simple fix/hack for someone with insight of the source code. It also would help by preventing unwanted behavior for task specific commands such as this.

I'm using Atom 1.5 on Windows 7 if that helps.

**Comment by MattiJarvinen-BA** [comment]
At least add option to ask first before closing Atom.

+1

**Comment by benogle** [comment]
There is an option in the main settings pane: 

![screen shot 2016-02-10 at 1 06 29 pm](https://cloud.githubusercontent.com/assets/69169/12961805/247e7c3c-cff7-11e5-93fd-146bbe171e63.png)

I agree as I have this option unchecked!
