### ISSUE TITLE
Destroying atom by launching Setup again

### ISSUE THREAD

**Issue by inetphantom** [atom/atom#10756]
I successfully installed Atom a few weeks ago.

Today I accidently started the AtomSetup.exe (the installer) again. As expected, it failed. But after that nothing worked no more. I tried uninstalling, it just happend, but the uninstaller misses a lot (remove registry entries etc.).

Additionaly, the log shows stuff that is not right, I know which folders I deleted( `Install path C:\Users\inetphantom\AppData\Local\atom already exists, burning it to the ground` )

After that, Atom (out of `\AppData\Local\atom\app-1.4.0\lib\net45`) worked, but not the Update.exe from Squirrel. 

[SquirrelSetup.log](https://github.com/atom/atom/files/124944/SquirrelSetup.log.txt) (Uninstall)
[SquirrelSetup.log](https://github.com/atom/atom/files/124869/SquirrelSetup.log.txt)(AtomSetup.exe)
[SquirrelSetup.log](https://github.com/atom/atom/files/124863/SquirrelSetup.log.txt) (Update.exe)

I would wish me a Atom-remover beside the uninstaller, and that the installer should not break the working installation

**Comment by damieng** [comment]
Both the install and uninstall logs show access denied errors to the installation folder which is strange as it is a user folder chosen to ensure you always have rights to it.

Are you running any anti-virus product?

**Comment by damieng** [comment]
No response, closing issue. Please re-open if you are still experiencing this issue.
