### ISSUE TITLE
Files are opened on same tab instead creating a new one

### ISSUE THREAD

**Issue by rm-code** [atom/atom#10753]
Not sure if this is a new feature in 1.6.0 ...

![tabs](https://cloud.githubusercontent.com/assets/11627131/12946136/860468fe-cff2-11e5-8eaa-61b15ee7e645.gif)

When I click on a file atom opens the tab, but when I click on another file it will be opened on the same tab. It looks like I have to double-click to "lock in" a certain file.

OSX 10.11.3
Atom 1.6.0-beta0 (Didn't notice it in any of the previous versions)

**Comment by GijsGoudzwaard** [comment]
It was updated recently, you can see it here https://github.com/atom/atom/commit/7b69ed7b4fb52e8c3ffd9f702e061d5f5ba62724

Also the repo it leads to:
https://github.com/atom/tabs

**Comment by rm-code** [comment]
Thanks @GijsGoudzwaard.

**Comment by benogle** [comment]
We should probably add the pending styles to the original atom themes.

**Comment by ziyaddin** [comment]
Now it happens to my Atom. The version is `1.17.2 x64`.

**Comment by kingjr** [comment]
same here
