### ISSUE TITLE
Feature Request: Open project from within Windows Libraries view

### ISSUE THREAD

**Issue by lech** [atom/atom#10766]
I just noticed that when attempting to open a project that also shares a location within a Windows Libraries location (Windows 7 in this case) a context menu option to open with Atom is not present when selecting within the directory area (blank space in the right pane). I'm fairly certain this is either something overlooked or possibly due to the way Windows treats these directories as symbolic links. Right clicking for the context menu option for a directory within the tree view for a project presents the "Open with Atom" context option, just within the right pane it does not.

**Comment by damieng** [comment]
These parts of the shell are not a 1-to-1 mapping with the file system - see for example here my Pictures Library where it represents multiple folders - and there is no corresponding symbolic link etc. available in the file system.

![image](https://cloud.githubusercontent.com/assets/118951/15062837/3374c648-12f9-11e6-8372-d0d0c01304c2.png)

Given atom's entire file browsing/organizing system is a 1-to-1 mapping with the actual FS this is not feasible.
