### ISSUE TITLE
Add config option to disable the concept of "pending tabs"

### ISSUE THREAD

**Issue by bjmiller** [atom/atom#10762]
After updating to atom 1.6.0-beta0, I found that my usual habit of opening tabs through single clicking was disrupted by having the tabs replace each other instead of opening next to each other.

I had to dig in to the release notes to find the problem - I was automatically opted in to the feature of "pending tabs", with no way out.  I never want to see a tab in a "pending" state, ever.  There should be a way to turn this feature off, and return to the previous behavior, in which every tab is always "non-pending".  A checkbox in the settings should be sufficient for this.

**Comment by kuychaco** [comment]
Planning to add a config option and patch it into 1.6 beta. Stay tuned.

**Comment by bjmiller** [comment]
Thank you!

**Comment by bjmiller** [comment]
Excellent!  Thank you so much for fixing this.  If I'd realized it was that easy, I might have submitted a patch myself. :)

**Comment by kuychaco** [comment]
@bjmiller you're welcome. Thanks for your feedback! If you do decide to open a pull request in the future, we'd totally welcome it :)

**Comment by lorenzos** [comment]
I'm still unable to get the old behaviour in Atom 1.8.0.

By default, if I single click items in the tree view, panes replaces themselves. If I uncheck the new *Allow Pending Pane Items* in core settings, single clicking an item does nothing. What me and I guess @bjmiller want is that the single click always opens new non-pending pane.

**Comment by 50Wliu** [comment]
@lorenzos You might be looking for https://atom.io/packages/single-click-open.

**Comment by lorenzos** [comment]
@50Wliu Exactly! Thank you.

**Comment by sekmo** [comment]
We have it now! https://flight-manual.atom.io/using-atom/sections/pending-pane-items/#disabling-pending-pane-items
