### ISSUE TITLE
failed to parse json

### ISSUE THREAD

**Issue by cham26** [atom/atom#10761]
keeps on having trouble when building atom
yaourt -S atom-editor

npm ERR! Linux 4.4.1-2-ARCH
npm ERR! argv "/tmp/yaourt-tmp-denis/aur-atom-editor/src/atom-1.4.3/apm/node_modules/atom-package-manager/bin/node" "/tmp/yaourt-tmp-denis/aur-atom-editor/src/atom-1.4.3/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/denis/.atom/.apm/.apmrc" "--userconfig" "/home/denis/.atom/.apmrc" "install" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file /home/denis/.atom/.node-gyp/.atom/.npm/center-align/0.1.3/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/denis/.atom/.node-gyp/.atom/.npm/center-align/0.1.3/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/yaourt-tmp-denis/aur-atom-editor/src/atom-1.4.3/npm-debug.log
== ERROR: A failure occurred in build().
Aborting...
== ERROR: Makepkg was unable to build atom-editor.

atom-editor 1.5.0-1  (2016-02-09 22:00)

**Comment by hemedani** [comment]
I have this problem too
`
Installing modules ✗
> atom@1.7.0-dev preinstall /tmp/yaourt-tmp-amir/aur-atom-editor-git/src/atom
> node -e 'process.exit(0)'


npm ERR! Linux 4.4.1-2-ARCH
npm ERR! argv "/tmp/yaourt-tmp-amir/aur-atom-editor-git/src/atom/apm/node_modules/atom-package-manager/bin/node" "/tmp/yaourt-tmp-amir/aur-atom-editor-git/src/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/amir/.atom/.apm/.apmrc" "--userconfig" "/home/amir/.atom/.apmrc" "install" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file /home/amir/.atom/.node-gyp/.atom/.npm/git-utils/4.1.2/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/amir/.atom/.node-gyp/.atom/.npm/git-utils/4.1.2/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/yaourt-tmp-amir/aur-atom-editor-git/src/atom/npm-debug.log
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build atom-editor-git.
==> Restart building atom-editor-git ? [y/N]
==> ----------------------------------------
==> 
`

**Comment by omninonsense** [comment]
This happened to me, although I am not exactly sure what caused it. I assume a previous upgrade gone wrong, or `apm` messing something up. As a workaround, you can just `mv ~/.atom/ ~/.atom.backup/`. However, you will need to reinstall non-core packages. To do that, just run (should be a cross-shell friendly version):

~~~sh
$ \ls -1 ~/.atom.backup/packages/ | xargs apm install
~~~

If you want to restore previous configuration, the only relevant configuration files I could find in my case were `~/.atom.backup/{config,keymap}.cson`. This included some APM package configuration as well, so maybe they're all there, but check in each directory to make sure:

~~~sh
$ cp ~/.atom.backup/{config,keymap}.cson .atom/
~~~

If you want to restore old editor sessions/tabs, those are now located in `~/.atom.backup/storage`.

**Comment by lee-dohm** [comment]
Sorry that I wasn't able to get to this Issue before now. If you're having problems building or installing the atom-editor Arch Linux package, you should follow up with the author of that package. The Atom team doesn't maintain it.

I'm sorry that I can't be more help.

**Comment by Torniojaws** [comment]
You don't need to delete the entire .atom/ directory. For me, it was enough to remove the file:
```\.atom\.apm\is-utf8\0.2.1\package\package.json```

For me, it was just full of "NUL" control characters. After I deleted that that file and re-ran Linter install, it installed successfully.
