### ISSUE TITLE
Installer not connecting to internet behind corporate proxy

### ISSUE THREAD

**Issue by stebiger** [atom/atom#10788]
Hey,

I already have an older version of atom installed, anyhow I have issues with proxy with a running atom so I considered to install the new version with the installer.

I am sitting behind a corporate proxy on win7 x64 machine - I have my environment variables correct on windows, I have configured my .apmrc with http-proxy, https-proxy and proxy variable correct.
Besides atom is not able to communicate with the internet with this settings even the new installer is crashing upon starting it, see attached log telling me

> 2015-09-01 13:28:40> Program: Starting Squirrel Updater: --install .
> 2015-09-01 13:28:40> Program: Starting install, writing to C:\Users\foo\AppData\Local\SquirrelTemp
> 2015-09-01 13:28:40> Program: About to install to: C:\Users\foo\AppData\Local\atom
> 2015-09-01 13:28:40> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Ein Teil des Pfades "C:\Users\foo\AppData\Local\atom\packages\RELEASES" konnte nicht gefunden werden.
>    bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    bei Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
>    bei Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__3a.MoveNext()
> 2015-09-01 13:28:40> CheckForUpdateImpl: Reading RELEASES file from C:\Users\foo\AppData\Local\SquirrelTemp
> 2015-09-01 13:28:40> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
> 2015-09-01 13:28:40> ApplyReleasesImpl: Writing files to app directory: C:\Users\foo\AppData\Local\atom\app-1.0.9
> 2015-09-01 13:28:54> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\foo\AppData\Local\atom\app-1.0.9\atom.exe]
> 2015-09-01 13:28:56> ApplyReleasesImpl: Starting fixPinnedExecutables
> 2015-09-01 13:28:56> ApplyReleasesImpl: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
> 2015-09-01 13:28:56> ApplyReleasesImpl: cleanDeadVersions: for version 1.0.9
> 2015-09-01 13:28:56> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-1.0.9
> 2015-09-01 13:28:56> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (407) Proxyauthentifizierung erforderlich.
>    bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    bei System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
>    bei System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
>

**Comment by damieng** [comment]
This looks like it is a problem within Squirrel which we use for the installers. https://github.com/Squirrel/Squirrel.Windows/issues/537  

I'll continue to investigate.

**Comment by damieng** [comment]
Just tried the latest installer on Windows 7 with a machine that only has access to the Internet via a proxy server.  The proxy server was set as the system-default proxy server and it installed correctly.

Is your proxy set as the system default proxy?  (You should be able to see it from Internet Explorer's connection settings)

**Comment by damieng** [comment]
No response for more information so closing. Please re-open if still experiencing this issue.
