### ISSUE TITLE
PHP -Weird string syntax highlighting

### ISSUE THREAD

**Issue by xorinzor** [atom/atom#10794]
I have had a couple of occasions where the syntax highlighting will turn parts of a string blue (same color as a function) whenever a '/' is used.

I personally don't see any point to this, and even if there is, it should use a different, more subtle color rather then the same aqua-blue as functions use.

Examples:

![untitled](https://cloud.githubusercontent.com/assets/4212335/13015542/00f56e46-d1ba-11e5-8a81-3684830474fb.png)

![untitled](https://cloud.githubusercontent.com/assets/4212335/13015576/20c22548-d1ba-11e5-85a8-b2a0287dd0df.png)

**Comment by 50Wliu** [comment]
That's a regex, no?  Looks like whatever syntax theme you're using highlights regex matches as aqua-blue.  I would suggest you reopen this issue on the syntax theme that you're using (atom/one-dark-ui perhaps?).
