### ISSUE TITLE
Atom is not updating the open tabs when I checkout a different Git branch

### ISSUE THREAD

**Issue by flaviolivolsi** [atom/atom#10793]
Hello,

It often happens that when I switch between the branch with Git, Atom doesn't update the files that are different between branches and that are opened in the editor. If I close and reopen the tab, the file gets properly updated, but that is annoying anyway. Do you have the same issue?

My version is 1.4.0.

Cheers,
Flavio

**Comment by 50Wliu** [comment]
Hi @flaviolivolsi, this looks like a duplicate of #4982, so feel free to subscribe there for updates.  Thanks!
