### ISSUE TITLE
Atom does not mark files with uncommitted changes in the file system browser

### ISSUE THREAD

**Issue by nabeelomer** [atom/atom#10791]
`Atom v1.5.2`
![screenshot from 2016-02-12 16 21 07](https://cloud.githubusercontent.com/assets/11234616/13004956/ad355c36-d1a4-11e5-99d2-d9a2f350bdca.png)
You can see that the file has uncommitted changes (the yellow lines) in the screenshot above.
![screenshot from 2016-02-12 16 18 11](https://cloud.githubusercontent.com/assets/11234616/13004976/dade2d3e-d1a4-11e5-8335-4de02b851b1e.png)
Atom marks them after I press `ctrl + s` but after they go away when the window goes out of focus.

I lost code because of this.

**Comment by jltrv** [comment]
Same bug here since atom 1.5 (on Ubuntu if that helps)

**Comment by albertosantini** [comment]
Dup https://github.com/atom/tree-view/issues/725

Very annoying bug.

**Comment by benogle** [comment]
Closing as a dupe
