### ISSUE TITLE
github crashed

### ISSUE THREAD

**Issue by dzknj** [atom/atom#10798]
got a message saying atom has crashed and
Please report this issue to https://github.com/atom/atom.
i tried to start atom from the terminal and i had recently installed zsh shell and was trying to open the .zshrc file to change the theme of the terminal. how do i fix this?? i am using ubuntu linux and the version of atom is 1.3.3

**Comment by 50Wliu** [comment]
@dzknj Please try updating Atom to the latest version, currently 1.5.3.  If that doesn't help, try launching Atom in safe mode: `atom --safe`.  And if that doesn't work, please comment here and I'll reopen this issue.  Thanks!
