### ISSUE TITLE
Hangs UI when opening large file

### ISSUE THREAD

**Issue by Jishaxe** [atom/atom#10800]
When opening a large (say, a binary) file, the UI hangs while it is being read.

**Comment by miftahafina** [comment]
me too

**Comment by mnquintana** [comment]
This sounds like a duplicate of either https://github.com/atom/atom/issues/8864 or #979 – feel free to subscribe there for updates.

Also, please take a look at the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) for a guide on reporting bugs, including searching for duplicates first.
