### ISSUE TITLE
Missing delete in edit menu

### ISSUE THREAD

**Issue by 0x1ad1b88** [atom/atom#10812]
Hi,

i an copy, paste, copy path from edit dialog. But if i am viewing a file i cant delete it via that menu... please add an delete option which closes the current tab and deletes the file.

**Comment by GijsGoudzwaard** [comment]
Why don't you just right click the file in the file tree and click on delete?

**Comment by 0x1ad1b88** [comment]
Well then we can delete the menu. :) You don't improve mistakes with a workaround. it's that simple.
