### ISSUE TITLE
Please get Atom added on steam

### ISSUE THREAD

**Issue by aoighost** [atom/atom#10810]
It would be nice to be able to grab Atom off of Steam. It would probably have to go through Steam Greenlight, but it would make it easier to get it downloaded and kept up to date for those of us who use Steam anyway.

https://steamcommunity.com/greenlight/

**Comment by aksiksi** [comment]
Sorry, but this is one of the weirdest requests I've ever seen. You want Atom to go through the Greenlight process just to make it more convenient for Steam users?

**Comment by aoighost** [comment]
Yep

**Comment by lee-dohm** [comment]
We're pretty happy with our current distribution methods. Atom updates itself on Windows and OS X. And we're looking into traditional package managers for Linux and other Unix flavors.

Thanks for the suggestion!

**Comment by paulcbetts** [comment]
I'm kind of into this idea actually, wonder how much of a pain in the ass it is
