### ISSUE TITLE
[1.5.3] Markdown editing lags after some time

### ISSUE THREAD

**Issue by NicoHood** [atom/atom#10824]
If you open a simple readme.md file and press `ctrl + shift + m` it opens a markdown preview on the right. After editing forth and back **some time** the atom editor gets slower. Moving the windows separator between the preview and the editor gets laggy. Opening folded paragraphs (via # headlines) freezes atom for some time.

I have not tested if not opening the preview does not cause this error.
This was in 1.4.1 already I think. No idea about previous versions.

Edit: has nothing to do with the markdown preview. It just gets slower after editing the file.

**Comment by kosson** [comment]
Same problem here. The issue started to manifest a few versions back. Editing md files with preview becomes a real pain after a short while. Closing the preview doesn't solve the issue. I usually close the editor and started again.

**Comment by arcticicestudio** [comment]
I think it's related to the auto completion feature, it starts to lagg/freeze everytime it opens the suggestions drop-down.

**Comment by kosson** [comment]
It seems Atom has an issue with editing large text files. Large JSON files are a freezing the editor... seems a limits for the size of the files edited.

**Comment by arcticicestudio** [comment]
Large File Support is still a part of the roadmap, there are several blog posts nad [discussions](https://discuss.atom.io).
I think this issue here is another problem, because I've edited javascript files with ~4000 lines of code and almost everything works fine.

**Comment by rsanchezsaez** [comment]
I have been experiencing a variant of this issue in which editing markdown files with the preview open is unbearably slow, wth the cursor freezing in place every few seconds.

However, my issue goes away when I close the *Markdown Preview* window, and reoccurs as soon as I open it.

I think that, in my case, this is related to the preview window being updated on real time (which is a nice feature). I guess the updates on the preview windows should occur in a background thread as to not interfere with the main editing window.

**Comment by arcticicestudio** [comment]
The Markdown Preview a awesome feature indeed, but sadly it is useless if you have to wait like 40-60 seconds to open it (editor freezes due this time). I have experienced it today again while editing my large README.md and CHANGELOG.md file of one of my projects, I had to wait ~80 seconds to use the editor again and there was no other way than switching to the npm app `[github-markdown-preview](github-markdown-preview)`

**Comment by arthurattwell** [comment]
This may be related to #6303
