### ISSUE TITLE
Attempt to fetch package list gives 'bad option: --harmony_collections'

### ISSUE THREAD

**Issue by dingxiangfei2009** [atom/atom#10821]
Fetching packages fails on Atom 1.5.3 gives:

/usr/share/atom/resources/app/apm/bin/node: bad option: --harmony_collections

Executing /usr/share/atom/resources/app/apm/bin/node -v produces "v5.6.0".
/usr/share/atom/resources/app/apm/bin/node is a symlink from /usr/bin/node, the Node.js from the distro's repository.

**Comment by 50Wliu** [comment]
We no longer use --harmony.
