### ISSUE TITLE
Graphical issues have been occuring ever since 1.2.0

### ISSUE THREAD

**Issue by ChrisTrenkamp** [atom/atom#10829]
![screenshot from 2016-02-15 22-25-50](https://cloud.githubusercontent.com/assets/3903329/13066392/556e9e5e-d433-11e5-8331-aa39be52b3ea.png)

I'm on Gentoo Linux, running Gnome 3.18 with the Nvidia binary driver v361.28.  

Ever since Atom 1.2.0, I have been experiencing these graphical issues as shown above and it happens all over the window, not just in the text editor.  I have tried compiling Atom from source, but it has the same issues.  I suspect it might have something to do with the version of Webkit Atom is using because I noticed Spotify 1.0.19 has the same kind of graphical glitches.

Atom 1.1.0 is the latest version I can run without these issues occurring.

**Comment by 50Wliu** [comment]
@ChrisTrenkamp This bug looks similar to #10714 - can you check that out and see if these two are the same?  Thanks.

**Comment by ChrisTrenkamp** [comment]
Indeed, I'm using an Intel GPU with a Nvidia Prime GPU (I keep forgetting that).  After switching over to UXA, I can't reproduce the problem anymore.
