### ISSUE TITLE
Atom tree-view git highlighting isn't always being refreshed in realtime on OSX

### ISSUE THREAD

**Issue by avatsaev** [atom/atom#10831]
Green (added) and orange (modified) colors sometimes remain until I exit from full screen mode, switch desktops or click on the items  in the tree-view. This is pretty annoying and misleading.

```
Atom Version: 1.5.3
OS X version: 10.11.3
```

**Comment by avatsaev** [comment]
here is a video demo of the bug (link expires in 7 days) http://cloud.vatsaev.com/data/public/atom-treeview-bug

**Comment by cyberhicham** [comment]
I got that 'bug' when upgrading to 1.9 (1.9.1 and 1.9.2) with a slightly different behaviour,
I have absolutely no orange or green in the tree-view, but if I chose one 'modified or added' file it gains its supposed color, and loses it after sometime (very short time)
