### ISSUE TITLE
Recent documents menu grows without end

### ISSUE THREAD

**Issue by jdforrester** [atom/atom#10845]
The new "Recent documents menu" in the dock provided by #9606 seems to grow without end, some of them multiple times, ignoring my system setting to never show these menus at all. This is troublesome for me as I normally have forty or more files open at once across a half dozen projects or so:

![screen shot 2016-02-16 at 14 15 55](https://cloud.githubusercontent.com/assets/881572/13092981/9bdcdbb0-d4b7-11e5-9fab-347c31f3b28d.png)

(Running Atom 1.5.3 on Mac OS X 10.11.)

**Comment by brentshermana** [comment]
This looks like an interesting bug. I don't see that menu in 1.6.0-dev though.... could you update and see if this issue persists?

**Comment by thomasjo** [comment]
@jdforrester I'm unable to reproduce this. If you are still seeing this, what is your *Recent items* setting set to? Mine is at the default value of 10;

<img width="668" alt="general" src="https://cloud.githubusercontent.com/assets/3622/13953603/0f56ae90-f03d-11e5-82d4-6fc2ae2e071f.png">

**Comment by jdforrester** [comment]
Hey there. 

@thomasjo It's set to "none".
@brentshermana I've switched to 1.7.0-beta0 and it seems to have gone now.

Thanks to whomever fixed it. :-)
