### ISSUE TITLE
Command-tilde no longer cycles through open windows

### ISSUE THREAD

**Issue by joshaber** [atom/atom#10852]
On `master` (41161dd462a1be9073752a34b4809612f933da6e).

This is a regression, presumably introduced by https://github.com/atom/atom/pull/9627.

/cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
@joshaber I can't reproduce this; command-tilde works for me. I *was* seeing some strange behavior when I first built Atom after the upgrade. Atom was actually failing to show up in the app switcher and in the dock. This problem persisted for me until I rebooted. I thought maybe something about the electron upgrade put OSX into a weird state with regard to Atom.

Is this happening consistently even after `script/clean && script/build`, and maybe rebooting your machine?

**Comment by abe33** [comment]
I built Atom freshly this morning (1.7.0-dev-41161dd) and I have the same issue with cmd-backtick.

Someone seems to have reported the same kind of issue in atom/electron#4512

**Comment by joshaber** [comment]
I can still reproduce this after a clean, rebuild, and restart.

**Comment by bdielman** [comment]
Still seeing this issue intermittently on U.S. keyboard. Reloading Atom will fix it sometimes, but it's not consistent.
