### ISSUE TITLE
community packages not showing

### ISSUE THREAD

**Issue by cloxure** [atom/atom#10853]
First, take a look at this:

![screen shot 2016-02-16 at 11 14 22 pm](https://cloud.githubusercontent.com/assets/2006175/13098876/0d081bb0-d503-11e5-86f0-6717bfe59a6b.png)

It states that I have 29 community packages installed but I can see only 1.

Atom version : 1.5.3
Mac OS X El Capitan

**Comment by 50Wliu** [comment]
@cloxure You're probably running into the same issue as atom/settings-view#591 - that issue should help you identify the misbehaving package.

**Comment by cloxure** [comment]
thanks @50Wliu.
