### ISSUE TITLE
Atom hangs for ~30s when pasting a large text block into a new tab.

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#10855]
Steps to repeat:
1. Copy a 161606-line XML document fully indented with spaces (and replete with CDATA) into the clipboard (<1s on **OS X Atom 1.5.3**)
2. Open a new tab in Atom
3. Paste
4. Atom hangs for 30 seconds.

I'm pretty sure 90% of the bugs I experience daily stem from work being done on GUI threads.

**Comment by hultberg** [comment]
Have you tried while running atom in safe mode? As I don't know what OS you are using, but on linux you just run: `atom --safe`

**Comment by alexchandel** [comment]
It's `atom --safe` on OS X too (after you install the optional CLTs).

And yeah, same result. Atom hangs ~30s upon Paste.

**Comment by alexchandel** [comment]
@hultberg Even worse: the damn editor freezes when you try to save the file. Even in safe mode. What garbage code is running *in between* my choosing a save filename and it actually writing the file? Atom is using **100%** CPU to execute this stupidity.

**Comment by rbottema** [comment]
I reproduced this on 1.5.3 and 1.6.0-beta5. Steps taken:
- Open Atom in safe mode
- Open new file
- Paste ~160k lines of XML

I've profiled it and it seems we can identify three main parts:
![profile](https://cloud.githubusercontent.com/assets/963169/13360258/a9347972-dcb8-11e5-8c66-a2f141d988b7.jpg)

* `buildTokenizedLinesForRows` in `handleBufferChange`. Typical view at the bottom:
![profilerleft](https://cloud.githubusercontent.com/assets/963169/13360443/a42afd10-dcb9-11e5-9695-89301cdb1ab7.jpg)
* `updateFoldableStatus` in `handleBufferChange`. Typical view at the bottom:
![profilerleft2](https://cloud.githubusercontent.com/assets/963169/13360445/a42be3d8-dcb9-11e5-866f-3813a87143ce.jpg)
* `addTokensInBufferRange`. Typical view at the bottom:
![profilerright](https://cloud.githubusercontent.com/assets/963169/13360444/a42b9f40-dcb9-11e5-9558-b5804fab1a34.jpg)

`addTokensInBufferRange` takes the longest with lots of calls to `SymbolStore.addToken`. This method contains the following comment:
`# This could be made async...`

 It seems like most of the time is taken by the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package in adding the newly pasted tokens to the 'auto-completion memory'. This should not cause the editor to be unresponsive.

What are the good steps to take? Open an issue on the autocomplete-plus package and try to make adding tokens asynchronously?

**Comment by benogle** [comment]
> What are the good steps to take? Open an issue on the autocomplete-plus package and try to make adding tokens asynchronously?

This has been fixed in autocomplete-plus with https://github.com/atom/autocomplete-plus/pull/672. The fix is in master, and will be in 1.7 beta.
