### ISSUE TITLE
Atom crashes when loading a large .json file

### ISSUE THREAD

**Issue by chromafunk** [atom/atom#10854]
When I load a dumped json it freezes instantly and I have to terminate it. With some json files I will have more luck and will be able to load them after a crash and keep on working, but with others it just won't and will crash inmediately after opening. I am on a Debian machine with plenty of hardware resources.

**Comment by Kreozot** [comment]
I confirm the problem with large files. My Atom crashes when opening any file larger than ~600KB. (Windows 10 x64)

**Comment by denqxotl** [comment]
Same thing Mac OS X 10.11

**Comment by gabrielclima** [comment]
Also to me =( 

Windows 10 x64

**Comment by ajbdev** [comment]
Same problem, OS X 10.10.5

**Comment by lee-dohm** [comment]
This is a duplicate of #9825. You may want to subscribe there for updates.
