### ISSUE TITLE
New file in project folder is not searchable

### ISSUE THREAD

**Issue by dinusubba** [atom/atom#10859]
When a new file is created in a project folder either by copy paste or using save as option. It is not searchable immediately using Command+T on Mac.
After a brief moment (couple of minutes) it started appearing in the search results.
<img width="928" alt="screen shot 2016-02-17 at 6 35 50 pm" src="https://cloud.githubusercontent.com/assets/5587801/13110343/7355255a-d5a5-11e5-9df5-250ceb42fb36.png">

**Comment by 50Wliu** [comment]
@dinusubba Can you please move this over to the [atom/fuzzy-finder](https://github.com/atom/fuzzy-finder) repository?  Thanks!

**Comment by dinusubba** [comment]
Sure I will move this

**Comment by dinusubba** [comment]
This issue was moved to atom/fuzzy-finder#175
