### ISSUE TITLE
Atom deems regexes with atomic groups or possessive quantifiers invalid

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#10869]
Atomic grouping and possessive quantifiers are *extremely* useful in regular expression. Supporting them can **only** speed up regex evaluation, especially for grammars that use them, as well as reduce the number of Find and Replace hangs that kill an Atom window.

Consider the regex `\b(integer|integral|integrity|insert|int|in)\b`matched against `integers`. The engine will match the first alternative, fail at the `\b`, then backtrack into the group and repeatedly match, fail, and backtrack through every single alternative, even matching the group in the last two cases only to fail at the `\b` again. This is quite a lot of work just to figure out `integers` isn't in our list of words. On the other hand, the atomic group `\b(?>integer|integral|integrity|insert|int|in)\b` will immediately give up matching the group at the second `\b` and never backtrack.

Consider also the regexes `"[^"]*"` and `"[^"]*+"` matched against `"aaaaaaaaaaaaaaaa`. Both fail, but the former backtracks through the *entire* string, while the second fails immediately thanks to possessive quantifiers. When such behavior is desired (often for order-dependent parameters), this makes a huge difference for performance.

Both of these are simplistic examples, but it's easy to imagine more realistic cases where the patterns getting backtracked through contain multiple alternatives, subgroups, character classes, lookaheads, or all of these.

In particular, I remember that switching to possessive quantifiers when writing a parser for Foxboro's ICC format reduced the parse time for a complete CP280 program from ~10min to a few seconds, merely by eliminating backtracking. Unfortunately I can't publish this as an Atom grammar, because Atom doesn't support atomics or possessives (or [string anchors](9146)).

If this issue is due to Atom's reliance on the crippled javascript regex spec, then it's time to junk it for one suited to the 21st century (or even the 20th).

**Comment by 50Wliu** [comment]
@alexchandel I'm fairly certain Atom grammars support both the use of atomics and possessives, as I've used them myself in a number of grammar rules.

Like I said in your other issue, grammars and find-and-replace use different regex engines.  Feel free to create an issue on [atom/find-and-replace](https://github.com/atom/find-and-replace) to suggest switching to Oniguruma.
