### ISSUE TITLE
Update CI To Node 5.x

### ISSUE THREAD

**Issue by joefitzgerald** [atom/atom#10860]
#9627 introduces Chrome 47 and Node 5.1.1. It would be nice to have CI match the node version bundled with Electron.

Given that:

* Electron bundles node
* Electron doesn't only use stable node, it tries to track v8
* Atom is comprised of Electron, core code, bundled packages, and npm modules
* apm is really just a wrapper around `npm`

Then I think we should formulate a strategy to:

* Try to lock in the same version of node in CI for core, bundled packages, and npm packages
* Try to use the same npm version bundled with the aforementioned version of node in apm
* When specifying node versions in CI, try to lock to the major / minor, but allow later patch versions (e.g. `~5.1.1`, as opposed to `5` or `^5.1.1`)

The goal of this would be to try to be somewhat deterministic in the builds, but this is somewhat dependent on the core Atom build servers being upgradeable, as releases are still generated there.

Doing this consistently would also have the side effect of allowing us to establish an `atom` babel preset, that can be used to slowly dial back the transforms required during transpilation as the version of node continues to progress and more ES6 functionality is bundled in.

**Comment by darkmorpher** [comment]
CC @lee-dohm
