### ISSUE TITLE
ENH: Find in find results output

### ISSUE THREAD

**Issue by dbarboza** [atom/atom#10867]
In Sublime, you can search in the search results output. This searches the filenames of the results as well as the match text. This is very useful when you have a vague search with many results. I use this a lot for searching for function definitions.

The steps in Sublime are:
ctrl+shift+F > search for stringA > Shows normal search output
ctrl+F > search for stringB > Searches in the search output only

Currently searching Atom search output does not seem to happen, but the "No results for <searchTerm>" is updated.

**Comment by 50Wliu** [comment]
@dbarboza This is a duplicate of atom/find-and-replace#133 - feel free to subscribe there for updates.
