### ISSUE TITLE
Create `atom` Babel Preset

### ISSUE THREAD

**Issue by joefitzgerald** [atom/atom#10864]
By creating an `atom` babel preset that core and packages can use, we introduce the possibility for slowly dialing back the number of transforms required during transpilation as the version of node bundled in Electron progresses.

It also provides a vector for possible optimizations to be introduced across all atom packages using babel, by writing new transforms focused on performance.

Related to #10860.

**Comment by hax** [comment]
You could consider https://github.com/ariporad/babel-preset-features , which detect transformers automatically.

**Comment by steelbrain** [comment]
I would also recommend that we make the version of the preset match the version of Atom, so it lets people target a minimum supported Atom version

**Comment by thedaniel** [comment]
There's all sorts of es6 and beyond stuff getting released in chrome lately, and I love using async/await, (the babelized version of which is not optimized well) so this gets more timely with each chromium release!

**Comment by thedaniel** [comment]
Are there babel presets for specific versions of chromium? That would be generally useful to the JS community, and won't need to be tied to atom. The atom preset, if we wanted to version it with the editor, could just import the numbered chromium preset.

**Comment by joefitzgerald** [comment]
I haven't found someone consistently creating chrome presets for the various chrome versions. Ideally, there would be one for each version such that we could update it as part of an electron upgrade @thomasjo @50Wliu .
