### ISSUE TITLE
Atom leaves image of itself imprinted on other windows when losing focus in Windows 7

### ISSUE THREAD

**Issue by nwduncan** [atom/atom#10876]
When changing focus from the active atom window to another application's window there is an image/imprint of atom stuck on the screen. Some notes:

- If a certain part of the newly active window is refreshed in some way (mouseover a button, panning a map, scrolling, etc.) that section of the window will show through. 
- Moving the newly active window only removes the atom imprint on sections that leave the view of the screen. 
- Changing focus via the taskbar does not create this issue. 
- Minimising atom does not create this issue. 
- This does not affect all types of windows (ie. Chrome is not affected, but ArcGIS is - seems to only affect Windows GUI based applications). 
- This issue is also present in safe mode.
- Using the most up-to-date version (1.5.3)
- This has been present since I installed atom several months ago.

Refer to the attached image.

![image](https://cloud.githubusercontent.com/assets/10606760/13130603/6207d07e-d639-11e5-8fdd-eebd2a07f3bc.png)

**Comment by benogle** [comment]
Gnar. cc @damieng

**Comment by Zireael07** [comment]
I have no such problem in Win7. What is your GFX card?

**Comment by nwduncan** [comment]
It's an NVIDIA Quadro 4000.

**Comment by damieng** [comment]
Are there any other apps this happens with besides ArcGIS?

**Comment by nwduncan** [comment]
Just tested it on a few more windows. Paint, IE, calculator, excel, word.. were all affected. Command prompt and notepad were not. The titlebar and window frame do not seem to ever be affected, but the menu bars and main window area often are.

**Comment by 50Wliu** [comment]
@nwduncan Does this also happen in Aero mode, or only Classic?

**Comment by damieng** [comment]
Not been able to reproduce this in my Windows 7 VMs. 

Given this has been seen for months on this machine but nobody else has reported it I wonder if the much less common Quadro is a factor here. 

@nwduncan have you made sure the Nvidia driver is up to date? Latest Quadro one is dated only a few days ago.

**Comment by nwduncan** [comment]
@damieng I'm starting to think that may be the issue. Unfortunately this is on my work machine and getting IT to update my drivers is proving to be more of a hassle than this bug is. I will report back when I can confirm or deny the graphics card is to blame.

**Comment by nwduncan** [comment]
Unfortunately a gfx driver update has not resolved the issue.

**Comment by paulcbetts** [comment]
This is https://github.com/atom/electron/issues/1821, subscribe there for updates but this is most likely not going to be fixed by Chromium. Workarounds are:

1. Use an Aero theme
1. Upgrade to Windows 8/8.1/10
