### ISSUE TITLE
Tooltips do not appear/disappear correctly.

### ISSUE THREAD

**Issue by jordwalke** [atom/atom#10882]
If you (on Mac) command+tab to Atom, and your cursor just happens to land on a tab, the blue hover dialog pops up. This is distracting and hovers should only ever be triggered if the mouse _stopped_ on a hover target.

**Comment by amytruong** [comment]
@jordwalke I _think_ I was able to reproduce this. When you mean hover (or tooltips), it shows the location of the file yes?

**Comment by jordwalke** [comment]
@amytruong yes those tooltips.

**Comment by amytruong** [comment]
Yea, it's happening for me when I strategically place the cursor where the tab is. :+1: Thanks for the clarification!

**Comment by benogle** [comment]
This may be a quirk in chrome where it is firing the mouse events even when the mouse doesnt move. I get this all the time with gmail--I basically cant have the mouse over any of the interface when arrowing through my mail.

**Comment by jordwalke** [comment]
An easy(ish) fix would be to put a threshold on the amount of movement (mouseMove) that would trigger a tooltip. You'd make it so that you cannot merely receive an `onmouseenter`, you'd need to experience some movement in order for a tooltip to become triggered (which in real cases would certainly occur).

**Comment by jordwalke** [comment]
Also, one other thing that makes the tooltips feel poorly implemented:
When you hover over a tab, and a tooltip rightfully shows, clicking on the tab itself should (as always) jump to that tab, but it should *also* close the tooltip. The paradigm for tooltips require that clicking anywhere outside of the tooltip should cause the tooltip to close. (That's consistent with tooltips on Chrome's browser tabs fwiw)

**Comment by jordwalke** [comment]
Also, try hovering on the tab, and then waiting for the tooltip. Then close/open the file tree. It should close the tooltip because it's as if you have moved the mouse.
