### ISSUE TITLE
Windows 7 shell integration gone

### ISSUE THREAD

**Issue by ihabovich** [atom/atom#10887]
I used to work with atom on Windows 10 which had shell integration in context menu "Open in atom".
Now I have atom installed on Windows 7 on which I see no shell integration any more. How come?

**Comment by lee-dohm** [comment]
Which version of Atom are you running? This functionality was also recently updated by @damieng, I'm not sure when that change will make it into Stable though.

**Comment by damieng** [comment]
The "Open with Atom" should be available in the context menu for all files and directories.

There were recent changes to ensure it would also be available via the "Open With..." option.

Can you check your registry using regedit to make sure you have the following path:

HKEY_CURRENT_USER\SOFTWARE\Classes\*\shell\Atom\command

If that keys is there can you check that the default data for it is a path that points to your installed atom.exe.

**Comment by ihabovich** [comment]
@lee-dohm I am using Windows version 1.5.3.
@damieng I checked my registry and found nothing about the path you mentioned.

**Comment by damieng** [comment]
Hi, can you make the contents of your squirrelsetup.log file available?  It is in %userprofile%\appdata\local\atom
