### ISSUE TITLE
Language grammar cson is completely undocumented

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#10889]
The latest official [documentation](https://atom.io/docs/latest/) makes no mention whatsoever of what a language grammar's cson should look like. Not which keys should go in it (`fileTypes`? `name`? `patterns`? `repository`?), not what those keys should contain, not which scope selectors should exist, **nothing**.

**Comment by lee-dohm** [comment]
Thanks for the feedback. We are aware that there are plenty of things that need to be documented. In response to your [other post](https://github.com/atom/atom/issues/8430#issuecomment-185842744), I've pinged on https://github.com/atom/docs/pull/114 to see if that can be merged.

Thanks again!
