### ISSUE TITLE
Does atom-amd64.deb need a screenshot?

### ISSUE THREAD

**Issue by HansMuller** [atom/atom#10890]
I installed atom-amd64.deb using the Ubuntu Software Center. Completely painless. Maybe the deb needs to include a screenshot for the installer's sake?

![install](https://cloud.githubusercontent.com/assets/1377460/13154056/e73d664a-d62b-11e5-8d06-89fb334af0ac.png)

**Comment by mnquintana** [comment]
Nice catch @HansMuller! It would definitely be nice to add. :smile:

**Comment by savimat** [comment]
Unfortunately only official packages have screenshots in the software center. PPAs or downloaded .deb files aren't supported.

**Comment by thomasjo** [comment]
Confirmed @savimat's observation.

---
_See http://screenshots.ubuntu.com/about_
