### ISSUE TITLE
Make non-standard line-endings more visible (stylable)

### ISSUE THREAD

**Issue by GuillaumeLegendre** [atom/atom#10905]
Could it be possible to make more visible lines ending who aren't the line ending by default?
In the status bar, on the left of the LF/CRLF/Mixed, I could see a warning icon or the text in red . (yes Mixed would be always with a warning)
And make in color: red; (or whatever easily seen) and always visible in the file each EOL who aren't the line ending by default.

I often receive file with which I have to work from many source. And they aren't always well formed. If Atom could warn me when it happen and where, I could more easily correct it or ask for the sender to correct it by pointing the error.

You can see https://github.com/atom/line-ending-selector/issues/23 my first issue on this matter. With an answer from Lee dohm who is a good start.

But that means having all invisible, visible. Not only the one who are an issue.

**Comment by lee-dohm** [comment]
What @GuillaumeLegendre is asking for is a way to make non-standard (CRLF on Unix/Mac or LF on Windows) line-endings visible as errors no matter what the invisibles settings are.
