### ISSUE TITLE
Add more diagnostics information for better bug reports

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#10909]
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [X] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Create a "diagnostics API" that will allow `atom --version` and the about-view to display valuable diagnostics information, similar to what is collected by the notifications package for uncaught exceptions.
### Steps to Reproduce
1. Open a terminal
2. Type `atom --version`

**Expected behavior:** Diagnostic information including all relevant version numbers, environment variables, etc

**Actual behavior:** See below
### Versions

```
Atom    : 1.7.0-dev-b311707
Electron: 0.36.7
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by damieng** [comment]
OS: Windows 10 Pro 10326 x64
GPU: Nvidia GTX 980 (v361.91)
Atom path: c:\users\damieng\appdata\local\atom\app-1.7.1

**Comment by lee-dohm** [comment]
Good idea that I'm pursuing as part of a separate package.
