### ISSUE TITLE
Workspace.scan returned values' structures are different

### ISSUE THREAD

**Issue by faceair** [atom/atom#10900]
https://github.com/atom/atom/blob/master/src/workspace.coffee#L995

When file is modified, Atom use [TextBuffer.scan](https://atom.io/docs/api/v1.5.3/TextBuffer#instance-scan) replace `directoriesForSearcher`, but `TextBuffer.scan`'s returned value is different with `directoriesForSearcher`.

What should I do when I used [Workspace.scan](https://atom.io/docs/api/v1.5.3/Workspace#instance-scan) and the returned values' structures are different ?

**Comment by faceair** [comment]
Such as: `range` in `directoriesForSearcher`'s returned value is `Array`, but in `TextBuffer.scan`'s returned value is `Object`

**Comment by lee-dohm** [comment]
I'm not sure I understand. Is this a question? A documentation bug? Pointing out a code bug?

**Comment by faceair** [comment]
If it is a feature, should pointing out on documentation. If not, `Workspace.scan` returned values' structures should be same.

**Comment by lee-dohm** [comment]
According to the documentation, `Workspace.scan` returns a Promise with a `cancel()` method. There is no mention of `directoriesForSearcher` in the API documentation. I'm not sure what any of this has to do with `TextBuffer.scan` ... that's a different API.

**Comment by faceair** [comment]
Yes, that's a different API. 

Let's look at [Workspace.scan](https://github.com/atom/atom/blob/master/src/workspace.coffee#L940) how to work.

...
[if file not modified](https://github.com/atom/atom/blob/master/src/workspace.coffee#L987), use [searcher.search](https://github.com/atom/atom/blob/master/src/workspace.coffee#L991) scan files, and call `iterator` to deal returned values.
...
[if file modified](https://github.com/atom/atom/blob/master/src/workspace.coffee#L995), use [TextBuffer.scan](https://github.com/atom/atom/blob/master/src/workspace.coffee#L999) scan files, and call `iterator` to deal returned values. But the returned values is different with `searcher.search` returned values.
...

That's my question, `searcher.search` and `TextBuffer.scan` returned values is different, but both in `Workspace.scan`.

**Comment by DFreds** [comment]
I just ran into this issue in my Code Peek package. My hack fix is below. This really doesn't make sense though. The return types should be the same in both cases.


    atom.workspace.scan(regExp, {paths: ["*.#{fileType}"]}, (matchingFile) =>
      initialLine = 0

      # HACK I literally have no idea why this is happening. If the file has
      # unsaved changes, we get a range object. If it does not, we get an array
      # for the range.
      if matchingFile.matches[0].range? and
        matchingFile.matches[0].range.start? and
        matchingFile.matches[0].range.start.row?
          initialLine = matchingFile.matches[0].range.start.row
      else
        initialLine = matchingFile.matches[0].range[0][0]

      console.log "initial line is #{initialLine}"
      @matchingFiles.push(new FileInfo(matchingFile.filePath,
        initialLine))
    ).then =>
      if @matchingFiles.length is 0
        atom.notifications.addWarning("Could not find function \
          #{functionName} in project")
        return

      @openFile(@matchingFiles[0])

**Comment by DFreds** [comment]
Recommend this is reopened.
