### ISSUE TITLE
syntax themes: rendering issues with fontsizes > 100%

### ISSUE THREAD

**Issue by nylki** [atom/atom#10904]
![ppc_lineissue2](https://cloud.githubusercontent.com/assets/1710598/13176596/c362319a-d713-11e5-9896-a94048b5106b.png)

Defining a fontsize of more than `100%` for a certain css scope, such as `.heading-1` results in several rendering issues:
- Displaced lines, resulting in overlaps.
- gutters and cursor height does not match the actual line size / font height
- Bigger fontsized lines don't _soft wrap_ properly

This is no new issue and it's possibly difficult to prevent, as a lot depends on measuring lines heights etc. and having different sized characters certainly won't make it easier.
Some issues, such as a displaced cursor have been fixed previously eg. via https://github.com/atom/atom/pull/8811, but the above ones still exist, that's why I decided opening this issue to collect thoughts and to link connected issues here.
If those issues were nonexistant, some interesting/useful things would be possible in syntax themes.

Some discussion has happened here: https://github.com/nylki/pen-paper-coffee-syntax/issues/20

**Comment by simurai** [comment]
Mixing different font sizes isn't really supported. Well, a theme can do it, but as described above, it doesn't work well.

Not sure if there is a plan of adding support. Probably not that easy with all the measuring that needs to happen. /cc @as-cii

Would certainly be interesting for languages like MarkDown.

**Comment by cnHeider** [comment]
This feature would be nice :pray:
