### ISSUE TITLE
beta warning missing :/

### ISSUE THREAD

**Issue by jan-glx** [atom/atom#10907]
Sry, but I lost quite an amount of work in recent days. Could you add a "not for production" or "beta" warning. What is an editor worth that repeatedly crashes and does not auto-save unsaved changes?
Possibly related: #10516 and #10717

**Comment by lee-dohm** [comment]
Thanks for the feedback!

**Comment by jan-glx** [comment]
you'r welcome ;-) I'll see if I can as well contribute something constructive later today ...
