### ISSUE TITLE
Atom.exe command-line output cannot be redirected to a file/pipe

### ISSUE THREAD

**Issue by FeodorFitsner** [atom/atom#10912]
### Description

On Windows atom.exe command-line does not respect redirecting output to a file (or pipe).

### Steps to Reproduce

1. Open command-line.
2. Type `atom.exe -v -w >out.txt`
3. Check contents of `out.txt`

**Expected behavior:** `out.txt` contains Atom version.

**Actual behavior:** `out.txt` is empty and Atom version is printed to the console.

### Versions

1.5.3

**Comment by joefitzgerald** [comment]
This is due to Electron directly attaching to the console. The behavior can be suppressed by setting `OS=cygwin` (< Electron 0.36.x) or `ELECTRON_NO_ATTACH_CONSOLE=true` (> Electron 0.36.x).

**Comment by FeodorFitsner** [comment]
Thanks for sharing the solution!
