### ISSUE TITLE
apm and atom commands not installed by default

### ISSUE THREAD

**Issue by Nikitaw99** [atom/atom#10910]
### Windows Version:

Windows 7 32bit.

### Atom Version:

Latest (AKA 1.5.3).

### Description of the Issue:

`apm` and `atom commands` aren't installed by default. The installer I used was **EXACTLY** taken from [atom.io](Https://www.atom.io).

Both the `where apm` and `where atom` commands found nothing.

I reinstalled `Atom` a couple of times, and still got the same issue.

**Comment by damieng** [comment]
It looks like the installer is unable to connect to the download server because of permissions.  Are you running a 3rd party antivirus or firewall?

**Comment by damieng** [comment]
Appears to be system specific issue, can not repro.

**Comment by Nikitaw99** [comment]
@damieng I just found the problem. I just made the `atom` and `apm` commands work, because I didn't find them in PATH. Could you tell the devs to fix the installer so that it adds `[installPath]\resources\cli` to the path enviroment variable?

**Comment by damieng** [comment]
It does actually add that to the path normally. Not sure why it didn't for
you.
