### ISSUE TITLE
Make setting Atom as Default Editor for filetypes easier

### ISSUE THREAD

**Issue by jbeck111** [atom/atom#10913]
This is issue  #4893, which has been closed and  locked.  All I wish to say is that in my experience the problem is not fixed.  So it should be re-opened.

### Description
On Windows 10, I uninstalled Atom, downloaded the latest version from https://atom.io/, and installed it (Atom 1.5.3), expecting that its installer would bring the new functionality to my PC.

### Steps to Reproduce
I went to a code file, right-clicked on it, and went to the "Open With..." submenu. Atom was not in the mini list. Clicked "Choose another App".  

Sadly, there is no Atom-with-nice-green-icon in the list.  Options are:
- Keep using this app: atom.cmd (blank white icon; old, undesirable method of accessing Atom)
- Other options: Sublime, Vim, etc
- More apps (with down-arrow).

Clicking More apps brings up a bigger list of editors, and various unrelated applications.  Atom is not there.  Finally there is "Look for another app on this PC", which brings up the file explorer.

And so nothing has changed.

### Desired Behavior
Right click, Open With, "Choose Another App", check "Always use this app to open .xyz files", choose Atom-with-nice-green-icon which should be there, and it becomes the default editor. All .xyz files immediately receive the Atom file icon to show that they will be opened by Atom in future.

### Versions
atom version 1.5.3
apm version 1.6.0

**Comment by 50Wliu** [comment]
The fix has not yet been released.  You should start seeing improved "Open with" behavior in Atom 1.7.0.
