### ISSUE TITLE
Atom hangs and uses 100% when saving a large file for the first time

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#10917]
### Description

After pasting a large block of text (160000 very short lines of XML in this case) into a new tab in Atom and trying to save, Atom hangs and uses 100% CPU.

### Steps to Reproduce

1. Copy a large block of text into the clipboard.
2. Open a new tab in Atom.
3. Paste the text. Per #10855 Atom freezes for ~30s while pasting.
4. Choose the Save menu option.
5. Pick filename `foo.xml` and Save.

**Expected behavior:** Atom writes the file immediately.

**Actual behavior:** Atom freezes forever and uses 100% CPU

### Versions

Atom 1.5.3 safe mode on OS X.11 x86_64

**Comment by tomByrer** [comment]
Atom 1.6.0-b7 OSX crashes when pasting in large data as plain text also.  (New File, so no code highlighting.)
Example file I was attempting to paste: https://raw.githubusercontent.com/Fyrd/caniuse/master/data.json

**Comment by trusktr** [comment]
Tracking all these large-file issues in #12065.

**Comment by lee-dohm** [comment]
The Atom team is tracking all of these in https://github.com/atom/atom/issues/8864. You may want to subscribe there for updates.

**Comment by kb2l** [comment]
Still same issue with latest version. So blocking and so frustrating.
