### ISSUE TITLE
Incorrect font rendering in the Editor view in recent versions (OS X)

### ISSUE THREAD

**Issue by legoadk** [atom/atom#10923]
### Description

On recent versions of Atom (including 1.5.3, 1.7.0 (master)), I have noticed that there seem to be some issues with rendering text in the Editor view.

However, I discovered that this does not affect _every_ view. The autocomplete pop-over seems to have correct rendering.

As an example, see the attached images:
![atom_170_fontrenderingosx](https://cloud.githubusercontent.com/assets/7536168/13206824/187300b4-d8c3-11e5-90da-f7bb80ac4c4f.png)

Enlarged, with some more noticeable differences called out:
![atom_170_fontrenderingosxenlarged](https://cloud.githubusercontent.com/assets/7536168/13206835/41ca7870-d8c3-11e5-8c1b-da7a9fd44d2e.png)
_on the Issue page this ends up being resized due to its width; I recommend clicking on the image for the fullsize view which will prevent any resampling)_

(disclaimer: this scenario was captured while I had `-webkit-font-smoothing: antialiased` applied on `.editor`, but this scenario also occurs in the absence of such setting)

This issue is not present in older versions of Atom; the only alternate version I currently have installed is 1.0.19. In that version, all rendering looks the same as the popover in the above images (aka, correct).
### Prerequisites

When attempting to reproduce this issue, it may help to use a font that is designed to fit nicely into pixel space when rendered at certain sizes. The one I am using is a variation of ProFontWindows, at 11px.
### Steps to Reproduce
1. Open the editor
2. Begin typing so that the auto-complete popover shows
3. Compare rendering of the Editor view with the popover.

**Expected behavior:** Correct rendering.

**Actual behavior:** Incorrect rendering. The rendered shapes appear to be horizontally shifted or squished to the left.
### Versions

`atom --version`

```
Atom    : 1.7.0-dev-e39d200
Electron: 0.36.7
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

`apm --version`

```
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 1.8.4
```

**Comment by damieng** [comment]
Can you try adding this to your CSS?  .line-number .icon-right::before { width: 9px !important }

**Comment by legoadk** [comment]
@damieng, This does not correct the issue.

**Comment by legoadk** [comment]
Adding the following to my styles.less solves this issue _in my particular situation_:

```css
atom-text-editor::shadow .line-number {
   padding-left: 0.556em;
}
```

The original value for padding-left is 0.5em, which does not land on an exact pixel boundary once computed, apparently. This fix I provide is likely not going to work on every system due to varying DPI settings. 

Is there an alternate way to solve this?

**Comment by damieng** [comment]
Setting a whole pixel width to the gutter container should address it
effectively but we need to figure out how to make that stick.

**Comment by legoadk** [comment]
I did try that suggestion and found that it only fixed the editor view, and not the line numbers. Not sure why.

**Comment by damieng** [comment]
That is correct - it will force the editor to start on a whole pixel
boundary.  The line numbers are within the gutter and will need their own
tweak to land on a pixel within the gutter. It is likely the padding-left
inside there causing that.

**Comment by simurai** [comment]
Probably the reason for using `em`s for `padding-left` is so that the padding stays proportional to the font size. Some options to fix it might be:

1. We could change it to a fixed `px` value, but then the padding might feel too wide or narrow, if you change the default font size.
2. We could inline the padding based on the font size in the settings and round it to a whole pixel value.
3. Not sure if there is a trick to round `em`s in Less/CSS.
