### ISSUE TITLE
UNKNOWN error when saving files

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#10931]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When saving a file after the first time, Atom throws an UNKNOWN error:
```
Unable to save file 'C:\Users\username\Documents\GitHub\markdown-preview\lib\markdown-preview-view.coffee'
UNKNOWN: unknown error, open 'C:\Users\username\Documents\GitHub\markdown-preview\lib\markdown-preview-view.coffee'
```

### Steps to Reproduce

1. Open file
2. Save for the first time
3. Save for the second time

**Expected behavior:** File to save successfully each time

**Actual behavior:** The file saves on the first time but on subsequent tries throws the above UNKNOWN error until the computer is restarted.  The backups of the original file get successfully created.

Additional info: After the initial save, it seems like Atom locks the file, and any other programs are unable to save either.  Notepad++ will error on attempting to save *until Atom is closed*, at which point it will be able to save the file.  This started happening Saturday.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.
```
'ELSE' is not recognized as an internal or external command,
operable program or batch file.

Atom    : 1.7.0-dev-e39d200
Electron: 0.36.7
Chrome  : 47.0.2526.110
Node    : 5.1.1
```
(Also note the ELSE error, which I'll be reporting separately shortly after this)

**Comment by 50Wliu** [comment]
This only appears to occur when editing a file that's directly linked to Atom.  I'll be able to confirm this when I get back from dinner.

**Comment by 50Wliu** [comment]
Ignore the above comment.  I was able to reproduce this on a `.travis.yml` file that was totally unrelated to Atom.  Interestingly the filepath was logged as `FF2.travis.yml` instead of `FF2\.travis.yml` (same with `markdown-preview.travis.yml`).

To be honest I have no idea what triggers this.  Some files will work while others won't.  The issue seems a lot more prevalent in Atom repos though.

**Comment by 50Wliu** [comment]
**Only happens with files that have CRLF line endings**.  Since the first save always works, if you use that save to switch from CRLF to LF, all future saves will also work.  However, if you already used the first save, then attempting to switch line endings will not fix the error (and neither will changing the endings using a different program).

**Comment by 50Wliu** [comment]
And...of course that's not actually the cause.  Switching to LF seems to delay it by a bit, but the errors will still occur.  I'll keep investigating.

**Comment by 50Wliu** [comment]
I've narrowed this down to the following PR: #10843.  I'll experiment with mix-and-matching the package updates tomorrow.

/cc @joshaber

**Comment by joshaber** [comment]
Huh, off the top of my head I'm not sure why any of those packages would affect saving. Thanks for digging into this @50Wliu! I'll be really curious to see what you find out.

**Comment by 50Wliu** [comment]
@joshaber I've identified the culprit as `status-bar`.  Any tips on debugging this further?  I'm not sure where to go from here.

**Comment by joshaber** [comment]
I reviewed my PR again (https://github.com/atom/status-bar/pull/114) and I still don't see anything that would obviously effect saving.

Do we have reproduction steps?

**Comment by 50Wliu** [comment]
Yeah, I'm not sure either why that would cause saving to fail.  As far as I know I'm the only one that can reproduce this so far but it happens consistently on every attempt to save for affected files.  I still haven't figured out what causes some files to work but others not to though.

**Comment by joshaber** [comment]
Can you get the full backtrace? Anything in the console?

**Comment by 50Wliu** [comment]
Nothing at all.  That gives me an idea though - I'll try disabling the custom error handling and see if I can get a stacktrace.

**Comment by 50Wliu** [comment]
Here it is.  It's very underwhelming though and doesn't go into why status bar might be causing this.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.0-dev-1aa0cec
**System**: Microsoft Windows 10 Home
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: UNKNOWN: unknown error, open 'C:\Users\username\Documents\GitHub\atom\src\pane.coffee'

```
At /C:/Users/username/Documents/GitHub/atom/src/pane.coffee:557

Error: UNKNOWN: unknown error, open 'C:\Users\username\Documents\GitHub\atom\src\pane.coffee'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at Object.fsPlus.writeFileSync (C:\Users\username\Documents\GitHub\atom\node_modules\fs-plus\lib\fs-plus.js:279:17)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\username\Documents\GitHub\atom\node_modules\text-buffer\lib\text-buffer.js:1076:14)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\username\Documents\GitHub\atom\node_modules\text-buffer\lib\text-buffer.js:1053:19)
    at TextEditor.module.exports.TextEditor.save (file:///C:/Users/username/Documents/GitHub/atom/src/text-editor.coffee:685:20)
    at Pane.module.exports.Pane.saveItem (file:///C:/Users/username/Documents/GitHub/atom/src/pane.coffee:514:14)
    at Pane.module.exports.Pane.saveActiveItem (file:///C:/Users/username/Documents/GitHub/atom/src/pane.coffee:491:6)
    at Workspace.module.exports.Workspace.saveActivePaneItem (file:///C:/Users/username/Documents/GitHub/atom/src/workspace.coffee:646:22)
    at atom-workspace.commandRegistry.add.core:save (file:///C:/Users/username/Documents/GitHub/atom/src/register-default-commands.coffee:67:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (file:///C:/Users/username/Documents/GitHub/atom/src/command-registry.coffee:253:27)
    at file:///C:/Users/username/Documents/GitHub/atom/src/command-registry.coffee:1:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\username\Documents\GitHub\atom\node_modules\atom-keymap\lib\keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\username\Documents\GitHub\atom\node_modules\atom-keymap\lib\keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (file:///C:/Users/username/Documents/GitHub/atom/src/window-event-handler.coffee:71:30)
    at HTMLDocument.<anonymous> (file:///C:/Users/username/Documents/GitHub/atom/src/window-event-handler.coffee:1:1)
```

### Commands

```
     -4:32.9.0 core:save (atom-text-editor.editor.is-focused)
     -4:14.3.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -4:13.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:10.4.0 window:toggle-dev-tools (atom-text-editor.editor.is-focused)
  3x -3:43.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "archive-view",
      "autoflow",
      "background-tips",
      "image-view",
      "open-on-github",
      "release-notes",
      "spell-check",
      "styleguide",
      "welcome",
      "feedback",
      "autosave",
      "incompatible-packages",
      "wrap-guide"
    ],
    "projectHome": "C:\\Users\\username\\Documents\\Github",
    "themes": [
      "one-light-ui",
      "fizzy"
    ]
  },
  "editor": {
    "backUpBeforeSaving": true,
    "fontFamily": "Consolas",
    "fontSize": 13,
    "invisibles": {},
    "showIndentGuide": true,
    "softTabs": false,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.15
fizzy, v0.16.0
language-c, v0.51.1
language-coffee-script, v0.46.1
language-csharp, v0.11.0
language-gfm, v0.84.0
language-git, v0.11.1
language-html, v0.44.1
language-java, v0.17.0
language-javascript, v0.110.0
language-latex, v0.6.1
language-make, v0.21.0
language-objective-c, v0.15.1
language-php, v0.37.0
language-python, v0.43.0
language-ruby, v0.68.1
language-sass, v0.42.1
language-shellscript, v0.20.0
language-sourcepawn, v0.6.0
language-sql, v0.19.0
language-toml, v0.17.0
language-xml, v0.34.3
language-yaml, v0.25.1
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-csslint, v1.3.1
linter-eslint, v7.0.0
linter-javac, v1.7.0
markdown-preview, v0.157.3
notifications, v0.62.2
pdf-view, v0.39.0
travis-ci-status, v1.0.0
tree-view, v0.201.2

# Dev
No dev packages
```

**Comment by joshaber** [comment]
Huh, thanks for doing that @50Wliu. I wonder if nodegit is keeping some lock on the file. That'd actually make sense with https://github.com/nodegit/nodegit/issues/877 ...

I [just](https://github.com/atom/atom/pull/10975) updated nodegit which includes a fix for that nodegit issue. So :pray: maybe that'll do the trick.

**Comment by joshaber** [comment]
(I'm hoping to do a beta release today to get that fix out.)

**Comment by joshaber** [comment]
@50Wliu I just release 1.6.0-beta6. Could you check if that changed anything?

**Comment by 50Wliu** [comment]
Updating to latest master (1.7.0-dev-ff0942d) did not fix the issue.  Do I need to script\clean for nodegit or is the script smart enough to upgrade it by itself?

Another thing I noticed: when saving with status-bar v1 and above, the status bar diff count will show +/- the amount of lines in the file, like it's trying to convert line endings or something.  This does not happen with the old Git.

**Comment by joshaber** [comment]
Thanks @50Wliu. I'm digging into this now.

**Comment by joshaber** [comment]
I've verified that https://github.com/nodegit/nodegit/pull/930 fixes this. Once a new release is out with that fix we _should_ be good.

**Comment by joshaber** [comment]
Thanks for doing all the legwork on this @50Wliu!

**Comment by tailorsira** [comment]
This error occurs in vision1.15.0, pls reopen this issue, thx
