### ISSUE TITLE
Settings keeps appearing every startup.

### ISSUE THREAD

**Issue by badboybruno547** [atom/atom#10935]
Everytime the application is opened, it starts with a new document. However once you open the settings menu once, close the tab and close Atom, you reopen it and settings keeps appearing back as a main tab in focus. Atom v1.5.3.0

**Comment by amytruong** [comment]
Hi! What OS are you on? 
I'm wondering if this is possibly a regression. :thought_balloon:

**Comment by 50Wliu** [comment]
This is most likely a duplicate of #10297, so feel free to subscribe there for updates.
