### ISSUE TITLE
Darwin: "kernel: file: table is full" / ENFILE: file table overflow

### ISSUE THREAD

**Issue by wmertens** [atom/atom#10947]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

When opening a few projects, Darwin or Atom run out of file descriptors.
### Steps to Reproduce
1. Open atom in safe mode (or not in safe mode), and Console.app to keep an eye on things
2. Open a few Node projects, containing node_modules folders so there are lots of files in the repos
3. Either you get `kernel: file: table is full` in Console.app or `ENFILE` errors in Atom

**Expected behavior:** Atom should only open the files that it needs, hard to imagine it needs so many that the kernel stutters.

**Actual behavior:** System becomes unstable, needed to reboot
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

```
$ atom --version
1.5.3
$ apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.0
```

**Comment by wmertens** [comment]
As a workaround, I ran

```
$ sudo sysctl kern.maxfiles=30000
Password:
kern.maxfiles: 12288 -> 30000
```

A project that I could not load now loads.

**Comment by benogle** [comment]
[pathwatcher](https://github.com/atom/node-pathwatcher) isnt amazing. This is a common error on [linux][linux], so much that sometimes we have [nice messages][error-nerf] when this happens. I wonder if something like https://github.com/Axosoft/nsfw is more efficient with the watch resources. Thanks for the heads up.

[linux]:https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path
[error-nerf]:https://github.com/atom/atom/blob/0896142ea2adf85d90fa1c97e6b19e90b304f0c2/src/keymap-extensions.coffee#L37-L46

**Comment by wmertens** [comment]
I had a look at nsfw and I honestly don't know :-) only one way to find out I suppose…
