### ISSUE TITLE
How to build an Atom package with the Fedora 21 Dockerfile?

### ISSUE THREAD

**Issue by fusion809** [atom/atom#10945]
Hi,

I am just wondering how one uses the Dockerfile in this repo's top-level repository to build an rpm package. I have tried running:

``` bash
docker build .
```

and (the output of the following command is [here](http://paste2.org/pe2Z096K)):

``` bash
docker build -t atom .
```

in the beta branch of this repo and neither managed to create an rpm package in the Atom source directory, or in its parent directory, or in my /tmp directory, or in the Atom directory of the Docker container. Despite this neither command returned any errors. Is the RPM package somewhere else? 

Thanks for your time,
Brenton

**Comment by paulcarroty** [comment]
https://copr.fedorainfracloud.org/ ?
