### ISSUE TITLE
Atom, freezes, hangs, when large 1 line of code (minified) file is opened.

### ISSUE THREAD

**Issue by nashokin** [atom/atom#10944]
### Prerequisites

* [yes] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [yes] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [no] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [no] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [yes] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [yes] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom, freezes, hangs, when large 1 line of code (minified) file is opened. Could be similar to #10769.

### Steps to Reproduce

1. Just open any large 1 line minified file (js, css, json etc.). Using Mac, all latest updates and the latest version of Atom. This issue was reproducible for many versions in the past and till now. PC has the same issue.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

**Comment by 50Wliu** [comment]
Hi @nashokin, thanks for reporting!  This is already being tracked in #979, so feel free to subscribe there for updates.  Thanks for taking the time to look for similar issues, but don't worry that you didn't find #979 - there's so many issues that you sometimes get swamped :sweat_smile:.

(Also, instead of writing [yes] or [no], you can instead place an `x` in the brackets to make it render as a checkbox like so: `[x]`)
* [x] Checked!
* [ ] Not checked (no x)

**Comment by AlexNodex** [comment]
#979 is closed - just saying...

**Comment by Zireael07** [comment]
@AlexNodex that's because it was recently fixed and the issue is from a year ago!

**Comment by AlexNodex** [comment]
But it's. It fixed. A minified JavaScript file of 100k still breaks my latest atom, by breaks I mean freezes it

**Comment by Zireael07** [comment]
@AlexNodex: The fix was merged, but there was no update to Atom containing it yet.

**Comment by AlexNodex** [comment]
Ah ok sorry, I assumed as it's a 1 year old bug that it was merged upstream and included in recent updates !

Guess I'll just have to wait then !!
