### ISSUE TITLE
New line at EOF

### ISSUE THREAD

**Issue by alexgrpopa** [atom/atom#10946]
When saving something, Atom adds a new line at the end of each file. How can I disable/overwrite this 'feature'?

**Comment by albertosantini** [comment]
Settings / Packages / whitespace / Settings / Ensure Single Trailing Newline.

(Please, this is not issue, read https://github.com/atom/atom/blob/master/CONTRIBUTING.md)

**Comment by alexgrpopa** [comment]
I know it's not an issue, but I've searched on the internets and wasn't able to find a solution. 
Thank you !
