### ISSUE TITLE
ASCII code not recognizable   

### ISSUE THREAD

**Issue by DrMajkrosoft** [atom/atom#10948]
While pressing " Ctrl + Alt + Q " with "Serbian" keyboard, the editor doesn't show the "backslash character", instead I have to switch keyboards in other to get the "backslash character".

**Comment by 50Wliu** [comment]
This is a duplicate of atom/atom-keymap#35 - please subscribe there for updates.  You can also try the [keyboard-localization](https://atom.io/packages/keyboard-localization) package as a workaround.

**Comment by DrMajkrosoft** [comment]
Ok, thank you.
