### ISSUE TITLE
Can't install packages in terminal or in preferences!

### ISSUE THREAD

**Issue by IanHank2** [atom/atom#10940]
When i go to the preferences the package installer comes up with this and i cant fine anything online to fix it! I'm new to atom and programming and i am trying to install the script runner program for java!

`Fetching featured packages failed.Hide output…
tunneling socket could not be established, cause=139987550533504:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:`

In the terminal it shows up as this.

`user@hsubt108451:~/.atom$ apm install script
Installing script to /home/user/.atom/packages ✗
Request for package information failed: tunneling socket could not be established, cause=140089072781184:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:
 (5 attempts) (ECONNRESET)`

Thanks for the help i tried the export option and that also does absolutely nothing!

**Comment by Focus** [comment]
Are you using a proxy or a firewall? This might be relevant: https://github.com/atom/apm#behind-a-firewall
