### ISSUE TITLE
Atom launcher shortcut does not work after install on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by christopher-hopper** [atom/atom#10958]
### Description

After installing Atom for the first time on Ubuntu 14.04 LTS the Launcher (Unity Launcher) shows the Atom application but the application will not launch when clicked. 

Atom can be executed from a terminal command.
### Steps to Reproduce
1. From Ubuntu 14.04 LTS download the official [Debian package for Atom](https://atom.io/download/deb) from the [Atom website](https://atom.io/).
2. Install the Atom application from the Debian package downloaded by double-clicking on it from a file browser, or by entering the following command in a terminal:
   
   ```
   sudo dpkg --install ./atom-amd64.deb
   ```
3. Once install completes, open the Unity Launcher. 
4. Find the newly installed Atom application and click on it to launch.
#### Actual behavior
- Clicking on the Atom application in the Launcher does nothing. No application opens.
- Right-clicking on the Atom application in the Launcher shows the Application name _Atom_ and a different File icon, but with no buttons to Launch the application and no application description.
#### Expected behavior
- Clicking on the Atom application in the Launcher opens the Atom editor.
- Right-clicking on the Atom application in the Launcher shows the Application name _Atom_, the description _A hackable text editor for the 21st Century._ and a button named _Launch_ that will launch the Atom application.
### Versions

Here are the relevant version strings for Atom and my Operating System.
#### Atom version

```
# atom --version
1.5.3
```
#### Atom Package Manager version

```
# apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1
```
#### Ubuntu version

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:    14.04
Codename:   trusty
```

**Comment by christopher-hopper** [comment]
Looked at issue #7201 but it is not the same.

**Comment by mfrederickson** [comment]
Same problem with Ubuntu 16.04, atom 1.8.0. I can launch atom from the terminal, lock it to the launcher, but it never launches from the launcher when I click on it like it used to.

```
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11+
git 2.7.4
```

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
```

**Comment by chroda** [comment]
Dude, I have this problem in windows and I using the beta version https://atom.io/beta with solved my problem.

**Comment by jamesaduke** [comment]
Am having the same problem too

**Comment by zgoda** [comment]
Unity search does not find Atom at all in my case. I can launch it from terminal.

**Comment by PrieureDeSion** [comment]
I am having the same issues on Ubuntu 14.04. Unable to pin it, and find it in the `Open With` list.
Can only launch from the terminal.
