### ISSUE TITLE
bug: Atom's interface gets messed up when using Live HTML preview

### ISSUE THREAD

**Issue by andreixk** [atom/atom#10954]
Interface gets messed up when using live preview in html.

## Repro Steps

1. Create a new HTML document template (type html, hit tab)
2. Open live preview (ctrl-shift-M)
3. In the HTML document's <head> section create new style as following:
```html
  <style media="screen">
    div{
      font-size:100px;
    }
  </style>
```
4. Watch the world burn:

Before applying style:
<img src="http://apps.utype.ca/upp/before.png" alt="before"/>

After applying style:
<img src="http://apps.utype.ca/upp/after.png" alt="after"/>

**Expected:** The preview pane to change only
**Actual:** Every element on the Atom interface changes font size

## Versions

* **Atom:**       1.5.3
* **OS:**         Mac OS X 10.10.5

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by 50Wliu** [comment]
So the "live preview" isn't actually that - it's more meant as a Markdown preview that has additional capabilities to render HTML (as the Markdown spec allows that).  This has already been reported though at atom/markdown-preview#276, so please subscribe there for updates.
