### ISSUE TITLE
Set Chromium log_level To Suppress Chromium Logs

### ISSUE THREAD

**Issue by joefitzgerald** [atom/atom#10952]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Currently, the chromium `log_level` is not explicitly set. This means that the `log_level` is implicitly `0`, which is the most verbose setting. We should set [1] the `log_level` to a level [2] that suppresses INFO and WARNING messages, at a minimum.

[1] `app.commandLine.appendSwitch 'log-level', '<SOME VALUE HERE>'`
[2] https://chromium.googlesource.com/chromium/src/+/master/base/logging.h#292
### Steps to Reproduce
1. Launch atom from the terminal / command line
2. Observe messages like `[852:0224/093645:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command` and `[2804:0224/093645:ERROR:renderer_main.cc(200)] Running without renderer sandbox`

**Expected behavior:** Show only meaningful log messages when atom is launched from the terminal or command line

**Actual behavior:** Spurious log messages are displayed when atom is launched from the terminal or command line.
### Versions

<= 1.7.0-dev
### See Also
- https://github.com/atom/electron/issues/1905
- https://github.com/atom/atom/pull/10950

**Comment by maxbrunsfeld** [comment]
:+1: Thanks for tracking this down. It'd be nice to :scissors: the verbosity.

**Comment by bolinfest** [comment]
I tried working around this by doing the following in a test:

```
require('fs').createWriteStream(
  /* path */ null,
  { fd: 1, autoClose: false, flags: 'a' }
).write('message!!!');
```

This seems to crash Atom. Any ideas why? Is there another workaround I can use?

**Comment by bolinfest** [comment]
Hmm, at least I was able to find this in the logs:

> Atom Helper: guarded fd exception: fd 1 code 0x1 guard 0x7fff89ad82a8

Not sure what's causing that, though.
