### ISSUE TITLE
A Command [native!] binds my [ctrl-shift-F] makes my Atom can't use [project-find:show]

### ISSUE THREAD

**Issue by catscarlet** [atom/atom#10960]
### Description
I reinstalled my system yesterday, and installed Atom 1.5.3. I found I couldn't use [ctrl-shift-F] to do a [project-find]. I checked the page [Keybindings], and found a command [native!] binds my [ctrl-shift-F].

![snap027](https://cloud.githubusercontent.com/assets/10594035/13309188/798e7636-dbb5-11e5-8051-a0f8e1f8a0c2.png)

Actually, what is [native!] ? How can I delete the keybinding? How to make [ctrl-shift-F] working for [project-find:show]

### Versions
```
System: Win7x64

C:\Users>atom --version

1.5.3

C:\Users>apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python
git 2.7.1.windows.2
visual studio
```

**Comment by catscarlet** [comment]
Sorry. I just found that it's my fault. 
I found [ctrl-f] is binded to [native!] too, and I can use [ctrl-f] to find. Now I know what does that mean.

I checked my computer and found hypersnap binded [ctrl-shift-F] to snapscreen. I exit hypersnap and the [ctrl-shift-F] on atom is working.

Please close this issue, sorry.

**Comment by 50Wliu** [comment]
Thanks for the update @catscarlet!
