### ISSUE TITLE
Crash in nodegit

### ISSUE THREAD

**Issue by viatsko** [atom/atom#10965]
Hello!

Thread 14 Crashed:

0   libsystem_kernel.dylib        	0x00007fff833f2002 __pthread_kill + 10

1   libsystem_pthread.dylib       	0x00007fff927685c5 pthread_kill + 90

2   libsystem_c.dylib             	0x00007fff9215a787 __abort + 145

3   libsystem_c.dylib             	0x00007fff9215b066 __stack_chk_fail + 200

4   nodegit.node                  	0x000000011567c61a diff_context_line__pattern_match + 249

5   nodegit.node                  	0x000000011567c4ee diff_context_find + 91

6   nodegit.node                  	0x00000001156dcf0f get_func_line + 152

7   nodegit.node                  	0x00000001156dcbb3 xdl_emit_diff + 696

8   nodegit.node                  	0x00000001156dc73d xdl_diff + 385

9   nodegit.node                  	0x000000011568308a git_xdiff + 290

10  nodegit.node                  	0x000000011567df13 diff_patch_generate + 406

11  nodegit.node                  	0x000000011567e803 git_patch_from_diff + 493

12  nodegit.node                  	0x00000001155a7315 GitPatch::FromDiffWorker::Execute() + 63

13  libnode.dylib                 	0x000000010f41448e 0x10f2d0000 + 1328270

14  libnode.dylib                 	0x000000010f41468b 0x10f2d0000 + 1328779

15  libnode.dylib                 	0x000000010f41f189 0x10f2d0000 + 1372553

16  libsystem_pthread.dylib       	0x00007fff92766c13 _pthread_body + 131

17  libsystem_pthread.dylib       	0x00007fff92766b90 _pthread_start + 168

18  libsystem_pthread.dylib       	0x00007fff92764375 thread_start + 13

Looks like we need to revisit https://github.com/atom/git-utils/pull/61 here as the source of the bug is exactly the same.
All the information is in that pull request and related issues.

**Comment by joshaber** [comment]
Thanks for opening https://github.com/nodegit/nodegit/pull/922!

**Comment by joshaber** [comment]
@atom/core FYI, this should block 1.6.

**Comment by johnhaley81** [comment]
Fixed in https://github.com/nodegit/nodegit/releases/tag/v0.11.5

**Comment by viatsko** [comment]
Yep, rebuilt Atom with new nodegit - works without crashes in all of the cases. :+1: 

GJ everybody :)
