### ISSUE TITLE
Disentangling `TextEditor` dependencies and reviving the use of the constructor

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#10979]
@joshaber and I were talking this morning about how unfortunate it is to require `TextEditor` instances to be constructed via the `atom.workspace.buildTextEditor` factory method instead of just via a normal constructor.

In https://github.com/atom/atom/pull/8968, we disentangled all the global references and moved to straight dependency injection. Because `TextEditor` had many dependencies, at that time we decided to deprecate the `TextEditor` export in the module returned by `require('atom')` and encourage people to use the factory so that these dependencies could be injected by the method without references to globals.

Now we're realizing that was probably a mistake. If you look at the dependencies of `TextEditor`, all but `clipboard` can actually be eliminated via various approaches. Some of them absolutely _should_ be eliminated, because we're using them to subscribe to global events such as `atom.grammars.onDidAddGrammar`. This creates a requirement that package authors call `destroy` on `TextEditor` instances they construct or otherwise they leak editor instances because these subscriptions are never disposed. Other dependencies _can_ be eliminated in various ways but aren't actually causing leaks.

Let's go through injected dependencies one at a time:
- [x] `notificationManager` This is for notifying the user of the cursor scope. We can add a `getCursorScope` method and implement this elsewhere as well.
- [x] `packageManager` This is just to emit grammar loaded hooks. Again, seems like we could emit events on individual editors and do this elsewhere.
- [x] `viewRegistry` We won't need this at all if people implement `getElement`.
- [x] `project` We set the project's path when the file is saved for the first time. Doesn't need to happen inside editor.
- [x] `assert` A method for sending stack traces of unexpected states to the exception tracker. We don't necessarily need this everywhere and could even maybe look the other way using a global.
- [x] `applicationDelegate` This is used to open prompts about file size. Could be moved and hopefully someday won't matter.
- [ ] `grammarRegistry` Again, when grammars are loaded, match them against editors from the outside.
- [ ] `config` Everything this controls can be managed from the outside (the workspace) and set options on the `TextEditor` directly. The only downside is that it would make it harder for package authors to match the settings of editors in panes.
- [ ] `clipboard` This one is needed or you can't copy and paste. But could we have a private global for it via the module system. Essentially a singleton you `require`?

Some of these cases are more clear than others. What's less clear for me is the config and grammar registry. What if the package author _wants_ a grammar to be automatically assigned based on the editor's path? What if they want to follow along with the user's settings for editors in panes?

I don't have perfect answers to these questions yet. It could be that the newly proposed editor registration API could also hook up your editor with certain services such as automatic grammar assignment and tracking certain user settings. Bottom line is, unless we want to bet on every editor user to calling _destroy_ when they're done with our instance at the risk of leaking editors, these dependencies have to go anyway.

Thoughts? Tweaks? /cc @atom/core @maxbrunsfeld @joshaber

**Comment by joshaber** [comment]
`TextEditor` is also accessing some globals directly:

- [ ] [`atom.textEditors`](https://github.com/atom/atom/blob/5ba701f112d6e2ec77eb0a4c91b6ab0276cc15ab/src/text-editor.coffee#L160)
- [ ] [`atom.workspace`](https://github.com/atom/atom/blob/5ba701f112d6e2ec77eb0a4c91b6ab0276cc15ab/src/text-editor.coffee#L618)
- [ ] [`atom.project`](https://github.com/atom/atom/blob/5ba701f112d6e2ec77eb0a4c91b6ab0276cc15ab/src/text-editor.coffee#L675)

**Comment by joshaber** [comment]
Not too surprisingly, pulling out `config` is a doozy.

>It could be that the newly proposed editor registration API could also hook up your editor with certain services such as automatic grammar assignment and tracking certain user settings.

I like this direction generally 👍 Just `observe` the appropriate config path and set values on the editor.

I'm not sure this works when a value is dependent on a scope though. For example, `Cursor` [grabs a config value scoped to the buffer position](https://github.com/atom/atom/blob/b4d09d580e43d807588580e5385cbca8ca3ae049/src/cursor.coffee#L163). I'm not sure how we'd switch that to the proposed model. But that said, I'm not terribly familiar with cursors _or_ the config system. Thoughts?

**Comment by lee-dohm** [comment]
> I'm not sure this works when a value is dependent on a scope though.

It seems like we need to figure out what settings will apply to the entire file (ex: line length or soft wrap) and what are scoped by localized grammar (ex: nonWordCharacters). We'll have to come up with a way to pass across the entire set of scoped configuration values in the case of the localized grammar settings and update it when any of those settings change?

**Comment by joshaber** [comment]
Yeah, at that point it sounds like we're just creating a more specific subset of `Config`. Which is maybe ok?
