### ISSUE TITLE
After Regular Expression, syntax highlighting and autocomplete gets thrown off

### ISSUE THREAD

**Issue by davidnagli** [atom/atom#10970]
![image](https://cloud.githubusercontent.com/assets/6759650/13323092/df1e21c8-dba5-11e5-8a7a-d2a5bb026dce.png)

The code after the Regular Expression has broken autocomplete and syntax highlighting. And comments have working autocomplete and syntax highlighting.

Please let me know anybody needs more information in order to resolve this issue.

This issue occurred on Ubuntu 15.10

**Comment by 50Wliu** [comment]
The root cause of this issue appears to be #1667 - feel free to subscribe there for updates.
