### ISSUE TITLE
Wrong auto-indent behavior

### ISSUE THREAD

**Issue by chbk** [atom/atom#10973]
I came across this bug when writing in python:

![19](https://cloud.githubusercontent.com/assets/7478535/13330905/540aeec6-dbfb-11e5-90cf-867a2e4d0705.gif)

``` python
with mutex:
    if condition: print(True)
    else: print(False)
```

Each time something is added after the `else` statement, the line is re-indented.

Similar to #8570

**Comment by Zireael07** [comment]
It's not limited to Python. I'm seeing the same in Lua. And I'm sure it was already reported but can't recall the issue number.
