### ISSUE TITLE
Paste should paste at cursor position, not at the mouse position

### ISSUE THREAD

**Issue by abate** [atom/atom#10971]
Hello,
I'm been using atom for a while now and this (together with the double paste problem) is really bugging me. The problem is simple. Whenever I paste something using the middle button, it get pasted wherever the mouse is pointing instead at the cursor position. I tend to use the mouse very little (I'm a vim user, and I'm also using the vim extension with atom), and I ended up with my text being pasted in the wrong spot (often twice, but this is another problem). Can I configure this behavior somewhere, or is this an atom feature that is missing ? Thank you for this great editor.

**Comment by lee-dohm** [comment]
I'm curious, is this a common expectation? Everything else to do with clicking a mouse button acts where the mouse pointer is ... not the cursor position. Why should middle mouse clicking be different?

**Comment by abate** [comment]
From a vim user prospective this is very my my habit. I'm not saying it should be the default, but I'm wondering if it is possible.

**Comment by lee-dohm** [comment]
Currently, it isn't as simple to redefine mouse functionality as it is to redefine key bindings. That said, I believe it may be possible for a package to override the built-in functionality. I'm not sure how that would be achieved though.

**Comment by nathansobo** [comment]
This isn't something you can really configure right now and not a sufficiently popular request to take the time to make it configurable. If you'd like to modify the behavior in your own copy of Atom, you could override `TextEditorComponent.prototype.onMouseDown` and opt out of changing the selection when the event's `button` property is `1`.
