### ISSUE TITLE
Memory leak at open home directory.

### ISSUE THREAD

**Issue by bindlock** [atom/atom#10985]
### Description

Memory leak at edit Golang source code (in safe mode too).
### Steps to Reproduce
1. Open .go file.
### Proof

![2016-02-27 08 11 21](https://cloud.githubusercontent.com/assets/4338636/13370981/42817072-dd2b-11e5-9290-ec02356c5407.png)
### Versions

Atom 1.5.3
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1

**Comment by lee-dohm** [comment]
Does this happen with any Go source code file? Can it be an empty file? Or are there specific source code files that it reproduces on and some that it doesn't?

**Comment by pyvim** [comment]
I open empty Go source file only.

**Comment by lee-dohm** [comment]
I was unable to reproduce this using Atom v1.5.3 on Mac OS X 10.11.3. I left it running for about four hours with nothing but a blank Go file open.

Before:

<img width="636" alt="screen shot 2016-02-27 at 5 03 26 pm" src="https://cloud.githubusercontent.com/assets/1038121/13377938/ab2af7ae-dda5-11e5-94d9-452dfa93d76c.png">

After:

<img width="594" alt="screen shot 2016-02-27 at 8 48 55 pm" src="https://cloud.githubusercontent.com/assets/1038121/13377939/b54813e8-dda5-11e5-9502-c13c362cf1a5.png">

As you can see, the memory use only went down.

Is there anything else you can tell us? What OS and version are you running? Were you using Atom at the time or just letting it run in the background?

**Comment by pyvim** [comment]
Used memory increases for 2 minutes to ~4GB (~20MB/s). My OS is Ubuntu 14.04.4. Problem repeated at the opening Atom in home directory (even without the opened file).

**Comment by lee-dohm** [comment]
Do you have symlinks that create loops? Either in the directory where the Go file was or underneath your home directory?

**Comment by pyvim** [comment]
No. `ls -la | grep "\->"` is empty.

**Comment by lee-dohm** [comment]
I'm not sure what's unique to your system that is causing this. Any additional information you can provide would be helpful.

**Comment by pyvim** [comment]
Symlinks have in subdirectories.
For example, `find -type l -ls`
./.virtualenvs/python-patterns/lib/python3.4/shutil.py -> /usr/lib/python3.4/shutil.py

**Comment by pyvim** [comment]
For `find -type l -ls | grep "\-> /home"`
./.virtualenvs/citylab-backend/local/include -> /home/pyvim/.virtualenvs/citylab-backend/include

**Comment by bdruth** [comment]
I'm having an issue on OS X (10.11.3) as well - Atom starts off OK, but after a while is consuming multiple GBs of memory. I have 16GB, so I usually notice it when the system slows to a crawl because it's short on memory and has maxed out swap. At that point, Atom is usually using 8GB+. Quitting Atom returns things to normal and I can restart Atom and work for a while again. Usually takes a few hours to get bad.

**Comment by lee-dohm** [comment]
@bdruth Unless your situation has specifically to do with editing Go files, I'd appreciate it if you could open a new Issue, fill in the template and include as much information as possible on the problem you're experiencing.

**Comment by pyvim** [comment]
@lee-dohm, we found problem. Problem not in Go source file. Problem in recursive open folders.

**Comment by 50Wliu** [comment]
@pyvim does the memory leak still show up if you disable the fuzzy-finder package?

**Comment by pyvim** [comment]
@50Wliu, if fuzzy-funder disable, memory not leaking.

**Comment by 50Wliu** [comment]
Awesome.  And what if you try Atom 1.6.0-beta7?

**Comment by pyvim** [comment]
@50Wliu, I install Atom 1.6.0-beta8. Problem not fixed.

**Comment by 50Wliu** [comment]
Looks like I was mistaken - the fuzzy-finder fix is only in Atom 1.7.0 and later.

**Comment by RomuloPBenedetti** [comment]
I am in 1.12.7 and the problem still exist, I'm facing Home directory memory leak too.
