### ISSUE TITLE
Very very slow with lots of imports when editing RAML

### ISSUE THREAD

**Issue by brennhill** [atom/atom#10981]
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [X] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

When editing a RAML file with lots (like 10) include directives, performance gets very slow.
### Steps to Reproduce
1. Create 10 RAML resource types in 10 files.
2. Include all 10 RAML libraries.
3. Try documenting an API.

**Expected behavior:** 
Editor performs quickly enough that typing appears instantaneously.   I'm  on a 2015 MBP with 8gb ram, SSD drive and 2.7ghz CPU on El Capitan.  We can reproduce this on other computers at our company as well, so it's not hardware dependent
**Actual behavior:** [What actually happened]
It can take a few seconds for typed characters to show.
### Versions

v1.5.3

You can get this information from executing `atom --version` and `apm --version` at the command line.

**Comment by lee-dohm** [comment]
Can you include an example RAML file that reproduces the issue and what language package you're using for it?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/10981#issuecomment-190439990. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
