### ISSUE TITLE
File changes lost when opened in two windows.

### ISSUE THREAD

**Issue by g-borgulya** [atom/atom#10993]
### Description

I use atom.io for a large project on two monitors with the same project open. Sometimes it happens (especially automatically after reloading atom) that the same file gets open in both the two windows. I worked in one window on one file for really long and put quite some effort into it. As soon as I clicked the same file's already open tab in the other window, the file's content got overwritten by the content version of the second window (~250 lines became 1 line, lost hours of work). No undo. Couldn't find a way to get it back.
### Steps to Reproduce
1. Open two atom windows. Use Add Project Folder... for the same folders in the two windows. Open a file in both windows.
2. Modify the file in one window.
3. Click the other window, the tab of the same file.
4. The file gets reverted and saved, no way to get your work back.

**Expected behavior:** The content in the second window should be updated. Or at least shouldn't overwrite the other file without question.

**Actual behavior:** As soon as you give focus to the other window it overwrites the file without question with the previous content. 
### Versions

1.5.3

**Comment by g-borgulya** [comment]
I see it's not coming stable as mentioned in the step-by-step above, but I managed to reproduce the problem.
Maybe it's related to switching branches in git. I can't tell this for sure but it seems there's something like if there are two windows with a same file open and one of then is not touched then the file's content can stuck in a state even if there's a git checkout to a newer state where the file's content should be changed. Clicking the file's tab overwrites the file's content. I managed to get to a file content state that doesn't even match the last checkout from git.
I hope this helps.

**Comment by mirestrepo** [comment]
I have the same problem and can reproduce:

Open Window A - add project folder 
Open Window B - add project folder

Navigate to same file on both windows
Modify file on B without saving
Modify file on A save

At this point file on B has not update

Save file on B (this operation should not be allowed) - editor should know that the file changed somewhere and should ask whether you want to discard changes or overwrite file on system

This now overwrites the contents on A

**Comment by caesarsol** [comment]
May be related to https://github.com/atom/atom/issues/9257?

**Comment by caesarsol** [comment]
I'm having a similar issue but with two different editors, do you think it's the same cause?

https://github.com/atom/atom/issues/9257#issuecomment-286686455
