### ISSUE TITLE
Official Package for Debian Linux / Ubuntu

### ISSUE THREAD

**Issue by 4Digits** [atom/atom#10998]
Is it possible to create an official package for Debian Linux / Ubuntu for the Advanced Packaging Tool?

**Comment by arcticicestudio** [comment]
You should take a look at [#2956](https://github.com/atom/atom/issues/2956).
Anyway, there is a `.deb` install package for every release listed in the [release section](https://github.com/atom/atom/releases), e.g. [`v1.5.3`](https://github.com/atom/atom/releases/download/v1.5.3/atom-amd64.deb).
If you're running ![](https://www.archlinux.org/favicon.ico) Arch Linux you can install the AUR package [atom-editor](https://aur.archlinux.org/packages/atom-editor/).
You should also check the [Instruction](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#instructions) section for building Atom on Linux systems where the fifth point describes how to build a `.deb` package on your own using the `script/grunt mkdeb` command parameter.

**Comment by 50Wliu** [comment]
Closing in favor of #2956.
