### ISSUE TITLE
Show tooltip immediately if the tooltip trigger is manual

### ISSUE THREAD

**Issue by oclbdk** [atom/atom#10996]
I think tooltips should display immediately for `trigger: 'manual'` (currently, setting that trigger type has no effect).

The Bootstrap tooltip has a `trigger` option that's `click | hover | focus | manual` http://getbootstrap.com/javascript/#tooltips-options For `'manual'` you need to call `show()` on the tooltip to get it to display, but the current Atom tooltip API doesn't expose that method. This makes it hard to get a tooltip to show immediately (e.g. you'd have to set `trigger: 'click'` and dispatch a click event on the target element).

**Comment by Ben3eeE** [comment]
Closed via https://github.com/atom/atom/pull/11063.
