### ISSUE TITLE
Can't open multiple non-text files in Atom 1.7.0-dev-a7e43fe

### ISSUE THREAD

**Issue by izuzak** [atom/atom#10995]
@BinaryMuse @kuychaco @nathansobo @lee-dohm Wondering if you could take a look at this one :pray: -- I _think_ it might be related to https://github.com/atom/atom/pull/10959.

Here's what the behavior was prior to  #10959 being merged (at 606dc0299c9e8f2a80a0321ef5cdcc89e933012c, in safe mode):

![problem1](https://cloud.githubusercontent.com/assets/38924/13378484/982fcb62-de08-11e5-901d-9362a3ee53fd.gif)

Notice that I click through several images, and every one of those opens in a separate tab. 

And here's the behavior on latest master (at a7e43fef7a2dd11ad90c691870aac517fd12ced7, in safe mode):

![problem2](https://cloud.githubusercontent.com/assets/38924/13378523/88569b98-de09-11e5-867d-3d6a4deca62d.gif)

Notice how each image is replaced and I can't have more than one open. This happens regardless of whether I opened the files with a single click or double click, and regardless of whether I double click the tab after opening a file. In other words, I can't seem to open multiple image files currently. This is also seems to be true for other non-text files (e.g. zip archives). For text files, I can get the expected behavior by opening them with a double click.

Reading [this comment](https://github.com/atom/atom/pull/10959#issuecomment-188920474) by @BinaryMuse, it seems that this behavior might partially be expected. However, I believe users will expect the same behavior for text and non-text files, especially non-text files handled by core packages (e.g. image-view and archive-view). If this isn't something that should be handled in Atom core, I think we should update our packages and possibly warn other package authors about this change and tell them how exactly they should update their packages.

**Comment by BinaryMuse** [comment]
Thanks for the detailed info, @izuzak. You're right, this is related to #10959. The behavior you (rightly) expect would come from atom/tree-view#741, which is blocked until atom/atom#10872 is shipped. I believe the tree-view PR could be modified to be backward compatible, allowing us to merge it earlier and fix this behavior. I'll look into this more.

**Comment by BinaryMuse** [comment]
There should probably also be a version of this to handle backward compatibility until atom/find-and-replace#668 and atom/tabs#268 can be fully shipped — I will also tackle those.

**Comment by izuzak** [comment]
Thanks so much for fixing this, @BinaryMuse -- opening files works great now :sparkles:. 

(Closing files seems to be partially-broken now, but due to some other changes, I think: https://github.com/atom/atom/issues/11002 :grimacing:)
