### ISSUE TITLE
Freezing on very long Lines

### ISSUE THREAD

**Issue by PinkiePieStyle** [atom/atom#11004]
Atom Version 1.5.3
Opened CSS File with inline Image, tryd to delete the Image part it hangs/freeze then in
PATH: atom\app-1.5.3\resources\app.asar\src\lines-yardstick.js
Line 59 : while (textIndex < text.length)

In SafeMode it is not freezing

Steps to reproduce:
Create CSS File
Add the Code below
Jump to the End of the Line `background: #fff ...`
Klick on the Text before `=') repeat; `

`body {
    background: #fff url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAgAElEQVR4Xm3ci3Lcxg6EYcmOE+fy/i+aOLGT2Hv4T/Rt9WF5q1TUknPBYIBGA0Pp9c8//3x8+/btpc+7d+9ePn78+PLXX3+9dO+HH354ef/+/cuHDx9ePn369PJ4PM7zrrXtWZ/a16Z7nz9/fvnxxx9P3/r0+eWXX17++eefc7++X758Odf6dL9+X79+Pd8bs3s//fTTaffvv/+e/pecL7/++usZs3Z///33+d61uWrXGMnXvcbpXuN0v3s9a2zXZHt9fT39G7/fa5uc5EoPxqCTniV/962rfn36nrzpoXlaQ+trjvokR9+bq5/k7F5rOveuDo++1LhPA1NIjbvfwhowxVOqTam9NrW3oV1bpE0liDlaDEU2H+U01s8//3yE++OPP47AKaLvXW1818bvU/sWnmwpguKSIflSQM/JVN/uNz8jat6+17d75Gl+607O5KhtPxlEuqlPP82/cjAgekk2m2DeNi8js4mvV6NHymlxrLPGqxSek0AUnJAWWP8EYrWETEAe1Nh9rx0PaVEUnkCNyfN4X3L1rIW0oOSiZAthTPX/7bffjpJYaDLbxMbilZSVTMnd+Na83sZAa9f4tevDyxgzZLCh6ckG8oDG4m3pwHyt+ek51yQP7ga2mjShmqwJ6tg1geyojaldH+7L+ii0iUEJK+XaCdJCzd9YFtH4LK72PLO2vNKCUvQaB/mTyWa14L5TDi9KkWCDITaeudu42oBTz8iZLDaJHsBobXg1j2NMyUUvjd96D2RdDx6E6ibldM+CuGRXFs26U0oC9OHyYKlFsWJxgmBgsDHBBS+wqawtmcAWqID5jctK4flCK1gUi6xlFdJYUCB521xQ1e+sX/ypb/eSq3ZgbOG8+3Qopol9DL37PN76Xi8B2pMjREILciy/zv0uZmiTcMFDOF8biu5+VgVqurax9RNoWY1xwUVjJQdCIDYwFP1dwRtL3OBrMxujz5IC0AmC68dKeWBzbiA+g0y88nw9JAW3JkGbTsQ/6+AZNhKanE0pqGMMgmgDwfx+h7FBDvjAilg4wbCU+oCj7qUYlgWqCMqNE1jg0z6LpRj4z3PzhD7BqNgElgR0cgrEXWuLAaXADIgxgFPsapW4RseA21QoQY+MtnViegtxyBKUadx+P20uQR4ppsVSeB3sMtfTZmnhUsjup5g+GARFNu56EYazwT8F8EpWbXMaz0/t0E4etIGy+UFC8+TFy+JWZqys/m18bZsTTV0INEd9eAFjJFPrNVZXhg3SwStjxRLFq+Z/bgjYSogWgtLZRZYmxgicAljfCfHEwzdG0mJTnoAonmAXWZsgyyN6tgs2NjirT21qj+UJ9snOuMSK7rHCjVs8oGetQf6Bytev9ktZM1KG2nWNVPwT6MkrzmFfOwbZDosrhlhsOwrrU7RNEnThKzc1KZazwSuFwPHGbPebsLFAGQZkMyyOhaPWKKzxl3wsFCUPqi2XQh7kJ2Lksp9kpSDrtzZebNMzAuvoHsPkwQuR4J7HS2p5KcNsDp73+vvvvz9YmwcybDib8O0iHt734Gkp3CZEhGdlsLcx6kNZMnGZ8VqPAFr72oHM2gieLZSsKRSECfY8BhzLR1pnY0pO0drmwJwaI/kZ5uYrSAFDBcn1Aac2apNNMVPMEIcY1YnVxZC12DoJut/DSK4N89HFNssCe2ZS+Mp6a4fbC4bo9CaWZ4C3eGRsViuBbbFgsN99LHBpKRzfco2g2/zpoPGVWHg49FAesjZ5iXjIG8Qw0E6HSkGgWD8wSnevV4eHXRV4CSMJJFTPYbaB8HABmWXh/9wSUUCjuy9jbx41nwQVQFMQz2PtLVjMAbFIBOOw6J6DKjERZe6ZDcV6QAuoRIsxJbL0nefwADU+BignsYHiZWutrwoC3WZYJ/Yeznt9on3oIxfWSdBKQQmbEAlQH9DCXbdMwAOwFhBAYShnY6YU+QDIg/PNn0xYi81VKvFMvnMy3rdSS3OCMrmUTZH/iCGMApQI3IqboJs8DDh92KxkZP3SBbpKjs3H6EViemLS1fnQXkwC1Ij8GlsMSNvgBS/Ve8QKsAZzEzwlyjHgeGOxJLJgbYxiq6RgADSJL+gk6xW7QJ2Aro6Ut1unTQXX5gWDKg7klEjSC3iFIpTd1TPJKQ/rGePpetAmllUHgRXNXcUsM9p8YC2AlaO8ML3v2JYKLTgTC7qysjarxaKusnnVUFDjPprJ60Bkc8bsKFBhsf6obZbbOluf5wu5W7dKPhuvJhdCqPNlVEhBbRmhoi3vbS7xBAzXFmyeoC5HEKhYLssHJS3gnjmzFJaw2LoV0hTTOCht/SiZpTSvckxXdSVBnfciIeijhaHFPAEBwQ55NwNIoY2lQgAq22znKgJ/fWwuGs/45G6MxSbXDrMT5ySOYqmYYkNPDEkRalPwlJuDBUGJ4pfR1FY2zCq7BxIIpu4Fclj3wh9ai1JTgtxD8CSfgLtZL2+zYeKa2CPJSznJBC72uEDsWaiUNy0U8kiF1L7bPDlQ92wAiBKLIU5jHnp/TfjANhJQ7sAbBDRWRfFbknc2IJFMiaxO4SwFC5YJQSDlC/CVDFs9FnfkSo19D5a1kcOACgbEM1kzNlj7lCTJ27yqNowEG1zmxwC3attzxxNyLd6RXpRk6A0bY2i8+vVS8DnC9WAXK/gJ7LwDNV1KKYHb40uby5obO8FT/h5GSbAoR0m6+2TDmuovBrBs7AteJ4tDLR7gQAqcbLETJKcDMQQdxZ4ko/IFHmwddxiFAslW3+SxHqjDg9fIzonh5h9r5XswI2imTHEENKwXsFBUmcujfoK9zBcEcdn6pSxKX5wW/FIqI+m5PEa9CIzA/6WXcJ4BWru1smTBF8SAqe6rMu8zlq/UArYEc54mLouR9Cp9OB5CsS1uOTvYsWDw0iJAybIunoCRYEsKkDi62MG6sB2W0ndsKAXwSHlMz7w4AacxQfWiZFFyISNjAEnuo92YDvixTmc79esHm9rYg3JjqQ61koE+bOpuLg96Unilk3vCklK2GLjVThjaglg4ZrYlc/CSosUPLAx/lyxtSVs/CZYyhI1pgXB5Sxhw2fk8KEMqUrjqAHalxC5gp/ytifFALGjP5Ru/+dMHoyNrz8RDxxLOm5JfIVVVWunmWcvC6zXksg1ss+x035Vb9q0JQmFGAuseVFmYMwDBTLWzObCzHWez2ebZhfOw2sgBQA8rRo0VGjdIg9fW1A8oEu96vswJa9OO58lbeCAjBMNr9HRpgxnhqfYKOBZpU1KI+NBVUG6xLAqL6Ttrs6gE4u42VqBneYp5giTXFxTJ0n1ztZh+3+Sw75TOg5Q+5COCd/cxJFfskRF13+ah+KrfFKzKi6UyPFC4+Yj1JAu43WMMAf+UTuCigMfSZaRNIIdoEFl0C1QOaJOMg+HsuQGBaiMmwVvKBRU2oQWlBDAoEIMeVoV2f49agwtJJWsXXDEgRGFf2khWwZrC1MEaD4Gxtq4br9If2N10oXsLceDqrPPq9OghqonPc0dZNPgQANddubPyCaGxojazcTcAS7za0H6HxRQnL/GsvjuewKicrgIsXvAirKi+lCWzlgh23yFb/TBDMqjcMgxzKDeRDTw2Z7Bb/z1TUhZanW7+csa/BnsQaHcKLmMUKOTioYMmiRx21ObxrrUE7Grp4hYCUVz4KohL5ha7waK8YQ0IZV4Lt4GUDV6wm55TFIbEI82/J38SS7EqWfdowWZvEXKNTkzkqc+YVgzBCCR+fYfJy44EYDiPc7PSpY1L+/YgqnG9k0sBmA85eKHjgNplcc2PQVFOsoA4cS6ZJard66e+oJE36btVCLgO2myYJLkxIIF6F9YkXtZXPGMwjds8PCL5UXPQfYzq+vLwCowHinkLF8od+D6BwRCWtCxlBa2/jfM7uEpQkNKmtJmbWFkgL0CZeaj8heKTSQDHlOrbOr0zxtC28mstII0CHcr1HM0XE8A9eW08y8cqW7M28iP65R2nbRsCNmClBIiSl6JyRdy7q35bVV0IML7azsINIiBGGW9LD8oY2oAdMYG8LB27wRC94oOYWAMoWqikQNVoBsJgBGkxh/GIWWIlRmrD1/shEbhTYThzdx6ifACC5CAsc/MPCpOLUAK8NwnG5uBHAgiXUWQ0syscVjnQhuK2lA1SxSWbs29SUhIDWA+9W7tE2FWMSCY5V4bBA8jbNYv3sh3jtMldxeY1gN1gcHaMsw3ZZLDNaPA+CYPrc7llVAlNwT0HIY2xXief4Q3gpPvOYrz40IIxLZZjc1lbc8FyL7epjYHDlVseknE0N1zvfvIzGgax+UrKRuPzNFQXvN8DtTrc5nRYZ/J7ca919l0+9gzyl+LOES6LgY0YygY+dZkUpFQCv+UWJnIuIk9xbXxn1yxuM1zJX+0kbYL8voTQ+PqlUIqw6dr67pwHrW8NW5SsHZrbvJLf1rPlGTBIT7xZxUJSqpqsEKm8nz4xV8iEuR7IvwZ+5iEYBTdEYzcpAhWs3mYSnJKUQOQ3CbJvFGI6kilYnKIIis2BDfWn5AGNPKN74EYM4Q0SNAGZ94DZ5lzD2+RPzNj8jA723YDGwOjIJyuHHuD5XjYSKg60VVxUSuj6vZcQsC67nXW2ALsNUrgpt2Z1XWXMTva4vAB3r7A2JmzlLaAMy2LFYBNrWfzeMgu4dWzKe7AzROSuONhfO7GKkpsL/SXX5lmSxdVF97BWb3TS2TkxFCtqxPXWVRtsgxUGoQSQRffcW4R7iIOlNK6FgUdxSlBEInouToAWWbKNooTmlpiSXbmDMkCkzBqsiBkofAbHa5q/OZunjQB5DMiccimb0X2e6HiBIYldyed9gZ6R8xhSiWEC9qEo2WXCSc6ayALEF/GDFSaIBE7A3sViGzYAXCnSobosGTnQD9vrvjI51kN5NpKiui8msPC7MsUq1q70ocDIc8TO1rR5Ve3V4dab9iQSwwPDexLZ+hjWgSzWu4IlHJZDYU3mHkblbNymghmxRawxtlihMOnIV+wAN2glmu2VGxa42bA+akWNBafN33e5BeOS0bcuSsYceTt4sVltauNgR95yZMSbrDbull8aSyySC6HFXQ+ElhgmDAYFhyl2AxIoOe50fXoGG9eq69vES4URBUearH/hTVzhVeRqbPSYV2E7kkbQaAwEpXYgtt/dF/iTX6YsfpKV1fIGm7ZvTKZYcREZwdaS6R74GRiay5ChxjMPEcgaVKMWz+UpksvthlkAxlNbcIani0MYhbIKqDQuPLUpDqu6r8QPxy2YNe/fgLBMNNy48pyTFb8F19aCdChgelOxNnIq7It3pEQGCSrFNkwOHGGFoLznWyJCjJ5/H8LtE1QAx6JYulLKJoQJtbnDVoklZI25b5nIwHtuY8WJFCA+dMVYQM96JxiB2zwTha2tpBeECawqDLXVfxNAnrfMrT5Bp2c2C0PaepbciA4Eb56sbVfwdfKQIAum1rhFsl5KAA+qnAtTYGtzGElT421g04YisY+8SIxwxsxieYW319cieW/jikEKd5TEWOQi2soZKFW+tDFi329W6uBhXXmIQzQyq+nRo0ox/aHOxnL0fNDkEvjB5VvU/kH9Ko5lphDuCIcTlhA2rzZxbMzE6Z5gLGmDpaBSLmMeihYgWTp56tfcoDFjSLleWuMtin6gr/4ydYZo89q0pb9klpWrFC+qND9jaTzVBVl+bf2QlZGs1548BHNSz29RLQQDWp7MwrqXUtFcC4SLjYn/YxAy7WVavKb+CdZ48ghB2DPxx6agkjxy3+cSCzDDhdXdROxvCYqzHExx20MNKQDrtuE8r3bgKXkFejq7QxVvPCeGKO4G3ITJytCyhNp3ngTdhTVw1zhbzU2w5d8KeilQ0sXiJZj+pKH7q1Qeh9H0HeykVEem4GLfRDm08q2oJ8ewmdibHEXyiGEpt/NGVo7280w6gBhtQGPSEyJhs3rOI08cvToWRp6BRdGQYII8L8K3WcRO1Dh950WsyIa0OBRzg60/FqofvGUQsBtkdVUX452wuHmcTiZfSuGVTiXht2AtscQotz2CAtIXfjb2QAJwTR6eZrMxsZ6DZnkVI33+wU47DPeyzr4vFNQRhnYFSfXB/dFdymYNhEcvJVOse+tnmwsoTzeXomVyFJtk6+itakFtlXRYefNot3QX1bdJcgrVCUaHssL67otNkkvGtNTbXFvOX0NG30H6YXnX7p7XgChT0NtNkZSlaOWRDYoCdAKwZBSRUrimONHV+2Ape4XGWhxqiWHgZ72lxTi/sWmMRHlfgpnCKYkxNDYlQQGsE70VyxQ5jYdwgHwGKMmWQIJKG2tD1dbEm+ORyu8JI9/ogfNu7rdZKNiA0zwHXvIe9R3xRnDMmuB9i+z3xhBEeWb35QstnhfbXPmDha1H85Lm2rOJ+jp02sx7/1EC9mjOfTsTpMp5GAEIBNvJ1vh7/GCdxpXPMdITQ2JZDbJJIOVwZdQU2wELdhamS4bub8dTPgvBrLqylmVWyEPPeSQoUCVFQMQAhrNlCzGAoSWnOLb9GAUIEQNXuYxPW96wNb37EQPkQHcRHRn/VhwY68lDxAcCtFNebkMHt3DHVbOAxW4u3XOWQxlgcakgro9I1GZZlvKCLJ7hOLZlyYgFLybz/ZQQNDUO2q4sgv4iM9ha7bQ1H09u3i278HxM0PrkVN870EJ8OMT5+5B7cEE5JYCsWJ1/F6x+ZTI0GbPwCo2JkYWFHXWylEJBW55YlsarbHrK8WpPcpnH5iraKXmIGco5y8w2JxJ/BFyQzmjBHVYpN9pYjMpjYc29p7Dpgo6xz9fLkk8eInCqsQhwShE93xig/VodvJa/YDYsR0xhjYIhOmgTW0i/sxoektclX8LLB1qUefud9SIg/gSA0dkwc1MwmRqXvEhA4zLSxnWCCjYZAsNCZFD31l0b0G9cTI0XnmuQxcW6shIJjjjRoHWQ7jfoZrTwkXs65rWR8BsDSkAlF8GPtXRFJ8khYMtLWCa4A1dyE4Yl7mFXsntERHK6NTM1sqXt3euzND9ZbAp44hXayeMgCUgUX2pvk4/hRXtBkKjPOlOKv9HDeAyIq1OeQKhk0Xd5TW3aIJguFqCTCbfWYwwUnBeiqnuKmUKTkXyN3cLEifrwJvDTuLyVYUgcxUo6QSwWfrCuhVWZee177i0b3tR4Kt6tp0/X2vHOYzRBFshYGJKUWaist0XBf4vtum+U6MOqeJ0CI7xtQ5atyCnuWbUKrFdpWH8y9QEBbfz+w4EtAgr8PMWLbXIdMrPsxpS9gyRKXDrLICleDkLZci3HFCm/sX32r6oOu610QkgJIOhaBaKVcgFBbgWozeYQ3NHmbl2HUDAdTIAecAgKJYWCuhKO+AKq0FNxqGtKSzFyh+75c4Hmb3NSvrqUMcUAsAuyl2KDYrkQGJYyJE+/o/zGRiqaW8zt9xNDmqCB+0lpm2comjWARTaJ8rbz5ayxiVk3tpU1C8bLMBrPmOizxWAjXJzSnOKlYN5lnA3ADEzllWVTqGLlWmryMi7PWzv6K3aB8PTU+OpcFJ1u6gfayYlFibG1V1j1TsMhVyAL3jtLwPW3CJjAgnnK38SuQeUcqKUqJ7hgRSCM5QrQNlz8wZ4cWvFc8QE8GZ9hwfDaKQGJLZK0ZGWAPcuwuvL89LHyrQeTTzogTxFH19N4KLbqZT5pQjLQ+TGk3u2F3d1AHSlc5rvvQS0J8C+auqekjfNjSBIqmTzs5/ryD9VU0LK5S4sVRNdDKAoRQGcpRVwUB2yI2APbl6qi1QwFYsj86yuHaFylJuugbLEZ5YYUjGFZXH0P7a10Il+Ah3aVBcpJWGLP11u4s9rScv1NnLq/1VFKUBvjWZS4LwY0jj+2F3BtUu299Q7+bBq6yaoVLrumVAQBQvhjItYuJ2GYlI4hLowrOZlr8wzjC+pLzxn7gb1L8Of/y2pAmTXcRefsNjfteZbghC8hYHCTC6KKbBgPJYKLFF1741Ok4G5DZd7gCs7bAPctfO9TLnYnt+qq+sCLWxfDIDtyAhnEvtrVhuzPbPvtb2asRRkJHV/D9kb9/5VOGpjVCXzcaq1SPElZKC2qySpwagpscgU4DKzJvV8r+NceXKqQtnDVWfHJxmJfPAAkmddYYoINbD4KZGyOfpexiSfW13gZnNjKMMFbfSHNxsT622DeuEkuCHWwdt5cZBVdd5cpTiJHQXa4+6xgy9IWzxv2nHw3jBJtcON68aC+NgtrAokwGgYnJ4ZmDRjQweW3n/W+DIqx8SAveDRGcoh1KVr8UohVk/N3LWIS1sfIUV5QmVx00LMt7RwvD7ISzgAsX5BZKtpkLMHO25S7O9ogGWvKVTgUY1BCkGAxLG2hDOOSrKHQhyq+/ZFP49mcrqrPvH4T2uRVyscGk0PcrG8KUxXg5WpdyZiOFA4Za3KSYw3Xc/lT3yWlSMzZkEonG9xOsnF9BN8G74MpbIkAj4elDajMwfoFbjFjEySbJJsFJ2hoc4OX5sLhWZmjYEaEVot/kjOyo888ztgbYwRxOZV4sQzQOpN3DdOGi008msFtDoLdITD0ft5+byFiSItTQrYZKVPwU0KxiRKhJktQONx3NSqbSxEgMsElWILxCujUkos3Tn0sBtVOPnDj1aVNHMGY8gbYERMonaegt+IUb2lMShZDeIOAr+ILTfZ5axPbJL+KtXKRQ3sF3jo3YJsCQzGTJlRKoYAm3XNiliZoCYACs8zZZi4V5fpd1axQTOWHIEZ+tCwPlWw8jEaWXbt+B3mYk8DL21IQY+Tx1mkM+UjtEJzkUZRFTLaS6/RTfrQlH3HI5hxvKzGEwWpNKdqRqUmaFCMgBEujOPdhM4jgypSt7JLyBFCxpu/moSDFRZvAYilK9YDx7GuobQTPBWHqZKg6VmcjuvIahojl3WE5vSzjBINLGKCL3AWDtU4pwkGQYgi4aDKlhu71XdLC3RqsgZ0n7CmiAEu5Ek31MMqRr9wF2tyi31HjpYltgoQLPFAgmBJYxSgxBEnoOxJCgbwW3huTR4FxMCuW9l0pX7LJYPQR69Su5C7gFYk5HlItSxa6LxIk0JaKeQPXZnU2BkRgNGBGHAInCd8HvFEubIXTzS2nYJ0sDN3lTebOELwsoX/ziAWbxOlL8cY0l/Uvg9M2j2Co4hjPsS7GpVySDOIcBrsxScw5Z+ooIFdHS8UIBypNYsEYkfoUvs36El45IwHguMBuY/IWpRnWqS6Fp2/WzxrRdFSZ9QUVPJ68Xc3Di8CTjeOFCIe4IBdRlbBBKX6T20NZ387MxWR5j7xJZTgZwCQygEI/aS9BZMJrQRTVQJgKXJe8gSeZs4IbQbXD5+UL3WcAqGbzqY85ZSRD4/EqXsoo+o6F7XrQ02QGY2IiqozCywkcI9gYitt6VXJQeuP2kSgGV85c6rOez4gwUvnSgaxroJOHtLtNwHK5P8EwLAkNmMNW6r/VWDCSUM7XF68d/LfBxnJAZpwUjNlwacml+HO0cH2wJX14hQROv6Xg1iKJbA31xwrru/UvMQvmy7XAMpgCaYzHZi/sW7NYXZvjvVenPs+DpRqwApgNg21Ogm85AdshaN8xmX7HREBi8y2eY2MOakCcZBKXN47aE+9LZmPj9SlPXKBwmya4i2VbGZBnyMsQFWyrvrURzK0DIxSDZOm1R/d3o7qP7PCY49XlIeAHx9/Jd1fr0IJZkEDG8tG5nrfIvEw+I+bAXdhtTrBFyaCK93r5QLCVB8B4JQ95lAC8b69QIuXJt3bDmj9Z/E8SyWP3lcy9S+xQCxxZKyhtnC2OotLgWzxF29PFefudVaVwAUii1sLsMDoHLrzx0VV8kVULzDJ29FFQZOW+116gTg6GgCqLKzZ5qS4L6x6LXtbjnjGTFX1Xx8MKJW4SOQQBjHY/I2AA5Ici+iUvb0NoBHMJIbl44zG+NgTkNMAe0KBwi+ndYxmgReCjSIoBV3CYtbAcFtrmYz1bcVVO2AMytTGeI+nsexYas/OPaVBTucPCRO1ZbGtKWRtkreF7LEx64FRSwD8W/lboJF9zK1AyHGGh6yaNB7IqvwuECQVqBFjn003Gqll9irToxWHBMoXfhWcNjeelbFgPm2G9EkWLworAI+uC1RjUwicvgfMp0N892gzWLuiLj7wJOQHH1om5pUSV5809jLPsMnl4Jna5BcmDEm1IA8JBLmxXYb+AlACyVJ4jE06IfmCtnAWTEpwlRoRrTNCQUClNyaY26DBK6Z5NwcQyEIwG1G2xT67C2JxKHrr5lgiLZTbxPw73XznHeuU01gWmeDlStISgZ5ugIlKNnRzKT2dDLBQFo0hWZzOaYC1m/9BG0JXd21iMqon9D63mQQ5QzZ433/24Ew6DT5tuc+U9MuGUlAwo6YGBofTdF4cwIEa2zGiPBECMzZFDgSpxlqxtCDjjCY3nuLbn8rZ+51nH0BUXLYLwsJo1cNF9PUjZJMFACpiofZN2ZQWSKAKvNdeO69swZKL28hnWbINwfTScZzEqz8UC3qg/dACP4NtGdgWl63VtKgNTmxMTyMgj6aArCCeXBJJ8Z0OUJrpJMNawJXCw0oTcEpdudwVhTA2FxYhAhBcpZNzNpdhn0eIUispzMDywx9oYjFO4vhuLdQq68L05mnchWCHQunjD/mMDgRuU+d6ckuDkS2ZQCAnA++ZQ6O/ZyEuAk4eAI4ymhwtdArjDIfx+3W+9Q/IlkAmGWw3YXEMSyoVtIrhguetxbZZ59vUiucSzPvSWyDZ2H6UKm80LeDD6jSmBPzphfCBeLiVxzeq3Gsx4rF1K0bzaPvMnQV2NiitnOU2IhdS5AQ0iu5Z3sGj5BK4Pl/d1F30a30vP9/9Sd688o4fwVmJIuU4yWSLlIRjJjZ7XxhGB/hjfWr041XWPGVqjGMCYkR/zg2OZe1foozyVjPTYvMdrKr/LJ+z04ifMbaJ7rQozE5mywwEAAAT+SURBVFide6vI1hcjwjAwppSjPwbSMxAppqipyX9qI6+pvw84oihnE+bru4Aux/CiM1QAX+tZG6vATesTHxlVY3oBItnBt4MqiScavAdyPPV4VRsCvymwTliS8+VlAqwtoVoUfKfYzRk2CVRAq3/jgwKb4Nr9+1sl3n4XKJs3mTZoiy+sTTYNkpofbIE1cWYV1rokmTb8XvJRtRbwHTtTLt1gXsbZAA/uuz5jTuch3VAWWeprITryhBbBG2yUe+hs90GcoqGxwQJsFdRsiHnAgeBrA5RsMD58XxySe8glkm1rXE7yNsBu6UYsSScMgAcK9vII3qb2JTEls7VhpPccRayESqe4mDAwEgbaJC4LIzcTJpz/qa40YdImkazJjMEiuJJwoattCuV1j5UjB+Ynl+oCSxc4lw43DgUlDxa4dSzGwLusofHFGcxtk+X9+45k2xK97B/Z4S3pGqGhh/ST4Z5a1uIZaltDm8MNG2RdU3wQuHjCshKxhweikaCsK4OwWYvPzp2XfuPuNsmCeZRNsRE936QUvRcrnPXIvTC3zdrviejW3CSGYpCkMqJQu01+bZLNEW+T5RjB9eBUex1RKiFnKavglGUCzICQkitFQtZrY1rwPTO1CFZKKSqjal7gErujpK4qCAttSzE3x6j9QlztwAmF3Y0EK1uGhAAxMGyPpbeO2oO99SZkpOfOb9IpSn/yEB6iSGhxNVLz6RkvkYFzu6XBcBZGq/E0ln4UitmouiIP+zKbAJhiQGrzrWEgEBRk83mNXEIcyTAkqJsT1Q4p4KnOvRngVhJAOjLQ+JjknWikaH3To9gs0NPl8ZBLiIdEB2NAOVkOJaXMdtl/edj4UltKqx3LEfyxEtZD2YIZS0pJCbYndj0DpVsIZblrlTafQSkAWkty9FGil7CC3TaL7N1TX0ObkRgEpXGRg6Bfgpr8KhKOBvxJnvfR6icnQUye/5V0gx4vkalz7SYxqVrOnT5qAxMpZK1EsN/SPUXyHAGUApRZxA1koO/aoN/dk6OIc9awMWzLGyzehiiHOPtJViyvMXmmDWluhEOOtWWo+iul7InrJpRnU3q3N8VLbOxYgtfRIi3MmxQtcA9X+q4kYLwUzyIJS9EyWfOAodqr3DY3T/I/ssQYFi+OwXsexvJ7Dm4PRl8WrWDKw0AiK+3qaBjeY5KNBYqXaIjDKsnYGohsbptoE1aHIO/5n60JIElUu2qQzSkEX6UVSaJET3KYItBXma38QkCVIHa1cPgrJohj9bWpcoYMIrlBi6DJaxhR8/U7NslrGYPYh4Sg6Gh9CkwfG3xR3K4gXaaeHGIXw0gX66UgledjtcdDpPeCWBsg+ZIXqHaKN/f4whKwEN4B3wne4tSpWP/Whdbt5TUU37U+4MiLzC1uWRvF1q7f1c4kpCgnWSm6+VjtQgmq2nj1Ud8zP+jbc3beQ67mbhxMjkxbezvrKDFkjfDfMSdGg59jIcoPPV/2IKvtyqIFP8pRBUULt2SBGYE+sWEz+sbTl5dugrp1NfBIHvKDjzYLVd/EsHa8zcmpWMkbsUY6cCbC4nkD47H5W3WgR/H1eP61mJOHgBfubTFLT0EA1lAbwR2d20kEYGOoyNoEHuA5CIH1AmZjs6gMwCuZxhc/lCEEbmf6gusyt9oK2K19oVbC6Ap+vRq7eRb4bGP2pQzGlI76XSBvHsQBPPP62vwP6nKBf943iD0AAAAASUVORK5CYII=') repeat;
}
`

**Comment by Zireael07** [comment]
If it's not freezing in safe mode, it means you have a problem with a package.

**Comment by 50Wliu** [comment]
You can try using the [package-cop](https://atom.io/packages/package-cop) package by @mark-hahn to find out which package is causing the freezing.

**Comment by DamirPecnik** [comment]
I had issues with this: https://atom.io/packages/open-recent when i disabled it the loading of files was fast again ... and no more freezing
