### ISSUE TITLE
Files opened from search results are treated as pending?

### ISSUE THREAD

**Issue by joshaber** [atom/atom#11007]
On 920d348014ac2ddf42e54e0bed6bb2cd71465146.

1. Find in Project.
2. Click on a result.
3. The result opens in a new tab. Note that the tab name isn't in italics, so it doesn't appear to be pending.
4. Find in Project again for a different thing.
5. The result replaces the tab opened in (3).

If I save or double-click the tab name, it seems to clear the pending state as I'd expect.

/cc @BinaryMuse @kuychaco

**Comment by BinaryMuse** [comment]
Thanks for the report @joshaber. @kuychaco and I are taking care of this today as part of the fix for #10995.

**Comment by BinaryMuse** [comment]
Closed by atom/find-and-replace#673

**Comment by ghs** [comment]
Still happen here.
When I search for specific string, the tab with "Project Find Results" returns all files, but when double click on any of them, it is open as pending/italic on a new tab.

OS: Mac OS X 10.11.4
Atom : 1.7.2
Electron: 0.36.8
Chrome : 47.0.2526.110
Node : 5.1.1
apm 1.9.2
npm 2.13.3
node 0.10.40
python 2.7.9
git 2.6.4

**Comment by jboler** [comment]
This is still a bug in 1.15.0 x64 on Ubuntu. There's no way to open a file from the Project find results without it being pending.

**Comment by danny-andrews** [comment]
Still have this issue as of
Atom: v1.14.3 on Mac
find-and-replace: v0.206.3

**Comment by matthiasdailey-ccri** [comment]
I've been able to work around it by making **Preferences > Core > Allow Pending Pane Items** unchecked.

**Comment by danny-andrews** [comment]
@matthiasdailey-ccri You're a gentleman and a scholar!
