### ISSUE TITLE
Indent-guide not aligned for some fonts

### ISSUE THREAD

**Issue by vdclouis** [atom/atom#11016]
### Description

For some fonts, the `indent-guide` is not aligned properly.

### Steps to Reproduce

1. Change font to, say Operator Mono
2. check code snippet

See:
![](https://cldup.com/u07R3KFIbh.png)

**Expected behavior:** correct alignment
**Actual behavior:** not aligned correctly

### Versions

Atom 1.5.3

**Comment by 50Wliu** [comment]
This is a duplicate of #9369 - feel free to subscribe there for updates.
