### ISSUE TITLE
Atom hangs when an opened file is written to

### ISSUE THREAD

**Issue by ChrisJefferson** [atom/atom#11012]
### Prerequisites
- [ X ] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [ X ] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [ X ] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [ X ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ X ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [ X ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Atom beta hangs when an open file is clobbered and continuously written to
### Steps to Reproduce

```
touch out.txt
atom-beta --safe out.txt
(for i in $(seq 100000); do echo "yyyyyyyyyy"; done) > out.txt
```

**Expected behavior:** [What you expected to happen]

atom changes to new file, and continues to work (atom stable does handle this fine)

**Actual behavior:** [What actually happened]

The two 'atom helper' processes hit > 260% CPU, and stay there. Eventually I am asked if I want to "keep waiting"
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

```
bash-4.3$ atom-beta --version
a1.6.0-beta6
bash-4.3$ apm-beta --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.2
```

**Comment by lee-dohm** [comment]
I was unable to reproduce this using Atom v1.6.0-beta6 on Mac OS X 10.11.3. What OS are you running?

**Comment by ChrisJefferson** [comment]
Exactly the same OS / Atom version. Weirdly, since rebooting my machine, the problem has gone away. I can still make atom hang if I run instead:

`for i in $(seq 20) ; do (for i in $(seq 100000); do echo "yyabcyyyyzy"; done) >! out.txt; done` (I gave atom at least 2 minutes to recover)

**Comment by lee-dohm** [comment]
@ChrisJefferson Thanks for giving a more reliable repro, I was able to reproduce this on my machine.

We agree that this is a bug and as such we would like to fix it eventually. On the flip side, the main use case we see that might encounter this problem (locking up when the file being viewed is created and deleted two million times in just a couple seconds) is when using Atom as a live log viewer. Using Atom in this way is a low priority for us.

We'll be leaving it open and if someone in the community wants to take a look and contribute PRs around it, that would be great.

Please feel free to clarify if I've misunderstood anything!
