### ISSUE TITLE
ctrl + backspace (expect similar feature like sublime)

### ISSUE THREAD

**Issue by zzz6519003** [atom/atom#11027]
### Prerequisites

- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

ctrl + backspace on mac should cut the word

### Steps to Reproduce

1. [First Step] ctrl + backspace to delete on a word like  "FancyWord"

**Expected behavior:** ["Fancy"]

**Actual behavior:** [""]

**Comment by sadovnychyi** [comment]
Actually `alt/option` + `backspace` should remove a word. Never seen `ctrl` to be used for this.

**Comment by zzz6519003** [comment]
thanks! it's sublime XD

**Comment by lee-dohm** [comment]
By default on OS X <kbd>Ctrl+Alt+Backspace</kbd> is mapped to `editor:delete-to-beginning-of-subword`. You can find this and other subword navigation keybindings in the Keybinding section of the Settings View.

<img width="777" alt="screen shot 2016-03-03 at 12 19 21 am" src="https://cloud.githubusercontent.com/assets/1038121/13488365/9d0086c0-e0d5-11e5-8e3a-ece1eb02243d.png">

If you would prefer the command to be mapped to a different key combination, you can find information on how to remap the command in the Atom Flight Manual:

https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings

**Comment by zzz6519003** [comment]
@lee-dohm  i mean ctrl+backspace   not + alt  XD

**Comment by groovenectar** [comment]
CTRL+Backspace deleting the previous word is not Sublime-specific.. It is every application in Windows...

CTRL+Backspace and CTRL+DEL in Atom seem redundant, they do the same thing, and CTRL+Backspace does the opposite of expected behavior (deletes the next word instead of previous).. I only just noticed it today.. Since I just installed the beta version, I'm wondering if that's what happened....
