### ISSUE TITLE
Support precise selection

### ISSUE THREAD

**Issue by jedesah** [atom/atom#11031]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Support precise selection like other applications on Mac OS X

As shown by [this](http://gfycat.com/AdventurousThankfulGermanpinscher) gif
### Versions

Is not present in version `1.5.3` of Atom.

**Comment by jeancroy** [comment]
There's block selection package that does some of this, althout it wont allow you to draw a target, negative, positive alternance.
