### ISSUE TITLE
Normalize The Environment And Allow Atom Windows To Have Different Environments

### ISSUE THREAD

**Issue by joefitzgerald** [atom/atom#11037]
### Prerequisites

* [x] ~~Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?~~
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] ~~Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?~~
* [x] ~~Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?~~
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

There are some issues with the way the user's environment is made available within Atom:

* On OS X, if a user launches `Atom.app` from `Finder`, `Spotlight`, `Dock`, `open`, or another `launchd` launched process, the user's environment is anaemic and potentially varies from the user's intended environment
* If a user launches `atom` from the command line multiple times, any changes in the environment for attempts `2...n` are not reflected in Atom's environment

I am conflating these two issues because I propose they should be solved by adding a ~~project-level API to `atom.project` (e.g. `atom.project.getEnv()` or `atom.project.env`)~~ functionality to Atom that:
* Is aware of the OS X "anaemic environment" issue and is capable of patching the environment for the implicit project that exists on first launch of Atom, if Atom was indeed launched from `Finder`, `Dock`, `Spotlight`, `open`, et a
* Allows projects to have a varying environment, so that multiple invocations of `atom` from the command line can result in some change in the environment, if changes were made

~~Note that this specifically does *not* endorse changing `process.env` nor does it seek to patch it. The actual environment for the running Atom process should be preserved, unpatched as it is still a valid environment for the original process. This also allows existing functionality to work as it always has, while providing a mechanism for package authors to opt-in to the new project-level API.~~

### Open Questions

* Is `atom.project` the right place for this?
* ~~What "marker" can be used to determine - on OS X - that the environment should be patched (see https://github.com/atom-community/environment/blob/3ccde732f213452e9b897482e1a3fba1f7a4a3e2/lib/environment.js#L113-L120 for prior art)~~ We are going to use the presence of ~~`TERM`~~ `PWD` as a marker on OSX that the environment does not need to be patched
* ~~Should `atom.project.getEnv()` return a promise to permit the patching, or should any patching be done synchronously (e.g. `atom.project.env`)?~~ process.env will be patched directly.
* ~~Should there be lifecycle events that are associated with changes in a project's environment (e.g. `onWillChangeEnv`, `onDidChangeEnv`, etc.)?~~ No.
* I'm certain there are a bunch of issues that this proposal would solve; I'd love help from @50Wliu and @lee-dohm to find them all

### Prior Art

* https;//atom.io/packages/environment
* https://www.npmjs.com/package/consistent-env

### Steps to Reproduce

1. Use OS X
1. Launch Atom from `Finder`, `Spotlight`, `Dock`, `open`
1. Open the Atom console, and type `process.env`
1. Observe the environment is anaemic
1. Quit Atom
1. Launch Atom from the terminal (`atom .`)
1. Open the Atom console, and type `process.env`
1. Observe the environment is as you would expect

**Expected behavior:** The environment is the same, regardless of how Atom is launched on OS X.

<img width="572" alt="untitled 2" src="https://cloud.githubusercontent.com/assets/744740/13480739/90a16e42-e0a5-11e5-8efc-5e6dded6ae44.png">

**Actual behavior:** The environment is different, depending on how Atom is launched.

<img width="572" alt="untitled" src="https://cloud.githubusercontent.com/assets/744740/13480724/7f9a0b2c-e0a5-11e5-975e-a564ce93b492.png">

### Versions

All, <= 1.7.x.

### Steps to Reproduce

* Atom does not update its environment when a project is opened twice
  1. Use any operating system
  1. Launch a terminal
  1. Make a directory (e.g. `directory-1`), and change your working directory to it
  1. Set an environment variable called `SOMEVAR` to `true` (e.g. `export SOMEVAR=true` on OS X / Linux; `SET SOMEVAR=true` on Windows)
  1. Launch `atom` from the terminal (e.g. `atom .`)
  1. Observe a new Window launches, with a new project in the tree view, for the `directory-1` directory
  1. Open the Atom console, and type `process.env`
  1. Observe the environment has the `SOMEVAR` key set with a value of `true`
  1. Go back to the terminal, and set the SOMEVAR environment variable to `false` (e.g. `export SOMEVAR=true` on OS X / Linux; `SET SOMEVAR=true` on Windows)
  1. Launch Atom from the terminal (`atom .`)
  1. Observe a new process launches temporarily, but then exits, and the original atom window focuses, with the `directory-1` project open
  1. Open the Atom console, and type `process.env`
  1. Observe the environment has the `SOMEVAR` key set with a value of `true` (although one would expect it to have a value of `false` now)
<img width="703" alt="screen shot 2016-03-02 at 5 58 47 pm" src="https://cloud.githubusercontent.com/assets/744740/13480030/b3b15c8a-e0a0-11e5-83ec-d6e86b771785.png">
* Atom does not allow different environments for different projects / windows
  1. (Continued from above)
  1. Change your working directory to the parent folder of `directory-1`
  1. Make a directory (e.g. `directory-2`) and change your working directory to it 
  1. Set an environment variable called `SOMEOTHERVAR` to `true` (e.g. `export SOMEOTHERVAR=true` on OS X / Linux; `SET SOMEOTHERVAR=true` on Windows)
  1. Launch `atom` from the terminal (e.g. `atom .`)
  1. Observe a new Window launches, with a new project in the tree view, for the `directory-2` directory
  1. Observe that the existing Window for `directory-1` is still open
  1. Open the Atom console, and type `process.env`
  1. Observe the environment has the `SOMEVAR` key still set to a value of `true`
  1. Observe the environment has the `SOMEOTHERVAR` key undefined
<img width="1206" alt="screen shot 2016-03-02 at 5 59 58 pm" src="https://cloud.githubusercontent.com/assets/744740/13480033/b5f08052-e0a0-11e5-8faf-6db16a9e8cdd.png">

**Expected behavior:** There is some way for a package author to get access to the state of the environment as it existed when `atom` was last invoked to launch a Window.

**Actual behavior:** Any changes in the environment for `atom` invocation `2...n` are not available to the package author.

### Versions

All, <= 1.7.x.

/cc @lee-dohm

**Comment by lee-dohm** [comment]
Thanks for documenting all of this @joefitzgerald!

Regarding the "marker", I think that we can determine if the `PATH` is equal to the concatenation of the contents of `/etc/paths` and all entries in `/etc/paths.d`. This way if some application changed their system environment, we should still be able to detect if they're using the "system default" `PATH`. For example, on my system, my "system default" `PATH` is `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`. The first entry in that list is new for OS X 10.11. The last one is because I installed XQuartz for something (that I'm probably not using anymore) and I'm afraid to remove it :laughing:

**Comment by joefitzgerald** [comment]
@lee-dohm just to summarize our conversation on Slack, we believe that the presence of `TERM` is the most appropriate marker that atom was launched from a terminal on OS X (e.g. iTerm2, Terminal.app); it is not present when Atom is launched from `Finder`, `Spotlight`, `Dock`, etc.

**Comment by joshaber** [comment]
I'm curious why we wouldn't patch `process.env` itself. Isn't the unreliability of `$PATH` a general problem/bug?

**Comment by joefitzgerald** [comment]
> I'm curious why we wouldn't patch process.env itself.

Quite simply, because process.env is simply reflecting the _actual_ state of the process's environment. We shouldn't mask that or patch that. While it is desirable to have a consistent environment (regardless of how atom was launched), that's different to mucking with the actual environment for the root atom process.

**Comment by joshaber** [comment]
I expect what package authors would like is for `child_process` to Just Work. For better or worse, VS Code directly patches the env: https://github.com/Microsoft/vscode/blob/80d53d89a341f8ba7caffebc39b7e4c8df73b613/src/vs/workbench/electron-main/main.ts#L251

**Comment by joefitzgerald** [comment]
@joshaber the thing is, I think we need a project level (or window level) api anyway, because we are also trying to solve for the scenario when you launch `atom` multiple times from the terminal, and each invocation has a different environment.

So I guess yes, we could also patch process.env. Would there be any valid use cases where people need access to the unpatched env?

**Comment by thedaniel** [comment]
> Would there be any valid use cases where people need access to the unpatched env?

If so, we could just make the original env available somewhere else for those rare cases. I tend to agree with @joshaber that package authors that want to use child_process probably don't want to think about getting different kinds of env. I do however share @joefitzgerald's view that we shouldn't throw away the original env - it might be useful for debugging user env issues at least.. we could patch it onto process as `_originalEnv` or something, or provide it in some other way.

**Comment by joefitzgerald** [comment]
@thedaniel @joshaber FYI we did end up doing what you requested in the PR.

**Comment by joshaber** [comment]
:sparkling_heart:
