### ISSUE TITLE
Problem with ampersand in folder name

### ISSUE THREAD

**Issue by maximvd** [atom/atom#11030]
### Description

- When a folder has an ampersand in the name and you right click and choose "Show in Explorer" it returns the following warning:

> Opening folder in Explorer failed
> 'Test' is not recognized as an internal or external command,
> operable program or batch file.

_("Test' is everything after the &)_

- If you choose a file within that folder Atom return the following warning:

> Opening file in Explorer failed
> The system can not find the path specified.

### Steps to Reproduce

1. Click a folder with an & in the name
2. Right click on the folder and choose "Show in Explorer".

**Expected behavior:** Atom opens the folder in explorer

**Actual behavior:** Atom opens the parent folder and returns an error

### Versions

**Atom version:** 1.5.3
**OS and version:** Windows 10

**Comment by zokker13** [comment]
Can't reproduce.

I've got Windows 10, too and Atom 1.5.3.
Opening a folder `& Test` works flawlessly.

Maybe you had an old version of Atom installed previously?
What does your regkey look like?
`HKEY_CLASSES_ROOT\Directory\Background\shell\Atom\command`
and
`HKEY_CLASSES_ROOT\Directory\shell\Atom\command`

**Comment by 50Wliu** [comment]
Reproduced on Windows 10 x64, Atom 1.7.0-dev-fa6905f.

**Comment by maximvd** [comment]
My atom has since updated to version 1.5.4 it seems.
"HKEY_CLASSES_ROOT\Directory\Background\shell\Atom\command" has the following value:
"C:\Users\Maxim\AppData\Local\atom\app-1.5.4\atom.exe" "%V"
and "HKEY_CLASSES_ROOT\Directory\shell\Atom\command" has the following value:
"C:\Users\Maxim\AppData\Local\atom\app-1.5.4\atom.exe" "%1"

**Comment by zokker13** [comment]
I totally misread the issue, please forgive me.
I can reproduce it as well on Win10 and atom 1.5.4 and 1.7.0-dev.

**Comment by maximvd** [comment]
I've copied this issue to the correct repo thanks.
