### ISSUE TITLE
Detecting Code Indentation

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#11049]
### Prerequisites

N/A

### Description

I saw this post on Medium and I thought you, Atom devs, might be interested in it: [Detecting Code Indentation](https://medium.com/firefox-developer-tools/detecting-code-indentation-eff3ed0fb56b)

### Steps to Reproduce

N/A

### Versions

N/A

**Comment by lee-dohm** [comment]
Looks like a great article! I've brought it up to the team. Thanks :grinning:

**Comment by nathansobo** [comment]
I read the article. We should definitely adopt the line comparison approach for auto-detection. If someone wants to open a PR, awesome. Otherwise we'll keep it in mind for when we circle back to indentation.

**Comment by alexandernst** [comment]
Maybe open an issue and link that post there? (Just as a reminder)

**Comment by lee-dohm** [comment]
Linked to the already open Issue.
