### ISSUE TITLE
Suggestion: Reopen Window in Dev Mode

### ISSUE THREAD

**Issue by Alhadis** [atom/atom#11055]
There's currently an _"Open in Dev Mode..."_ command under the _Developer_ submenu:

<img width="523" alt="figure-1" src="https://cloud.githubusercontent.com/assets/2346707/13522108/772aabc0-e241-11e5-9dab-1a4737e6e811.png">

I can't speak for other developers, but there've been numerous times when I've started working on something Atom-related, and I need to reopen the current project in dev mode. For instance, I'm working on a [language package](https://github.com/Alhadis/language-apl), so I need to see changes to pattern-matching expressions instantly... but stupid me keeps forgetting to open a project in dev-mode before I start working on it. Since I don't usually need to do that.
## What would be ace:

A shortcut under _"Open in Dev Mode..."_ called _"Reopen window in dev mode"_ (greyed out if already in dev-mode) that does exactly what that 25-byte sequence implies.

I understand this could be achieved with a package, but to be honest, this functionality feels too rudimentary to omit from Atom's core command-set.

**Comment by kachkaev** [comment]
@Alhadis have you found a solution? Also realised that _Reopen window in dev mode_ would be very useful, especially when having multiple linked projects open.

**Comment by Alhadis** [comment]
Haha, not really. :D I, uh, always start Atom in dev mode (owing to the number of forks I have dev-linked). I even have `atom --dev` aliased on command-line as just `@` (e.g., `@ file.js`) and it's the only way I launch it anymore...

Probably not the answer you were expecting...
