### ISSUE TITLE
Atom scss files autocomplete doesnt work

### ISSUE THREAD

**Issue by tslegaitis** [atom/atom#11056]
### Prerequisites

[What actually happened]

Autocomplete for scss files doesnt seem to work when using mixins. 

Basically when you are inside a mixin such as @include breakpoint(...){ .... } 

Autocompletion doesnt work. Any ideas on how to fix this? 

### Versions

Atom 1.5.4

**Comment by tslegaitis** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/17426331/13523460/80846494-e1ed-11e5-96c0-cee97996e751.jpg)

Here is a screenshot

**Comment by FernandoBoza** [comment]
Any update on this?
