### ISSUE TITLE
PHP syntax highlighting is broken when using "long comment type" within PHP-Tags

### ISSUE THREAD

**Issue by Terail** [atom/atom#11058]
### Description

Having a PHP code like below, does Atom let everything after the closing <?php */ ?> still interpret as "comment type" until the end of the file. This does not happen in other editors like UltraEdit, Brackets or Bbedit. Possible to get this changed? I am using mainly OSX.

### Steps to Reproduce
`<?php /* ?>
some non-php output here (JavaScript, HTML, whatever...)
<?php */ ?>
`

**Comment by 50Wliu** [comment]
@Terail please move this issue to the [language-php](https://github.com/atom/language-php) repository.
