### ISSUE TITLE
As soon as I Run atom , I can't do anything but just debugging atom and thinking of ways to make atom more awesome ,  Bug Or By Design? 

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#11064]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? 
Yes , both
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)? 
Latest Master and every other single version since birth of atom.
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)? 
Yes
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)? 
Yes
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? 
Yes
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
 Yes

### Description

As soon as I Run atom , I can't do anything but just find atom bugs and start thinking of ways to make atom more awesome ,  Bug Or By Design? 

### Steps to Reproduce

1. Run Atom
2. ????
3. Profit!

**Expected behavior:** [What you expected to happen]  
Start Coding  on my projects.

**Actual behavior:** [What actually happened] 
Start debugging for Atom.

**Comment by lee-dohm** [comment]
:laughing: I guess that depends on whether you mean this as a compliment or not :wink:

Thanks very much for wanting and helping Atom to be better!

**Comment by v3ss0n** [comment]
hahaha :D
