### ISSUE TITLE
Viewport doesn't scroll after expanding all

### ISSUE THREAD

**Issue by RodrigoEspinosa** [atom/atom#11066]
### Description

After unfolding, the viewport should scroll to the cursor, instead it stays on the previous (to fold) scroll position.

### Steps to Reproduce

1. Put the cursor in a line above the viewport first position.
2. Fold. _The cursor should stay in the same line or his parent if it was inside the block._
3. Unfold. _The cursor will appear stay in the correct position but the viewport didn't scroll._

**Expected behavior:** The viewport should scroll to the cursor position.

**Actual behavior:** The viewport stays on the position after _expanding_.

### Screenshot

![atom-viewpost-issue](https://cloud.githubusercontent.com/assets/1685621/13543261/3b3db466-e248-11e5-8722-9013aee08cfc.gif)

### Versions

Atom: `1.42`. _Tested on v1.5.4 as well_.
OS: `OS X 10.11 Beta`.

**Comment by lee-dohm** [comment]
* Can you reproduce this in Safe Mode?
* Can you reproduce this on the latest version? (Currently v1.5.4)

**Comment by RodrigoEspinosa** [comment]
Hey @lee-dohm, I just tried in v1.5.4 on Safe Mode and the issue is still there.

_I was looking for a way to scroll to the cursor in here: https://github.com/atom/atom/blob/master/src/fold.coffee#L77_

**Comment by RodrigoEspinosa** [comment]
@lee-dohm more information has been provided :smile:.
:arrow_right_hook: Also, there is an [open Pull Request](https://github.com/atom/atom/pull/11077) that solves this thing. _Tiny stuff._

**Comment by lee-dohm** [comment]
Thanks for the ping!
