### ISSUE TITLE
git bash cannot find atom

### ISSUE THREAD

**Issue by motonia** [atom/atom#11073]
I downloaded a latest version of atom, and rebooted my computer. Then, I ran git bash, wrote "atom .", and git bash said "bash: atom: command not found". What should I have to do?
p.s. I updated windows 7 to windows 10, and I cannot find like install shell commands menu.

**Comment by zokker13** [comment]
Is the path to the atom binary in your PATH variable?
(write set PATH in your git bash and look for the Atom folder in appdata)
The question implies that you could run other applications (like explorer or editor) from the git bash. Is that _really_ the case?

**Comment by damieng** [comment]
There were a number of problems with the bash and path integration in 1.5.4 (the latest non-beta version).  These issues have been fixed in master which will ship as part of 1.7.0.
