### ISSUE TITLE
Maxed CPU when updating packages

### ISSUE THREAD

**Issue by ElegantScripting** [atom/atom#11074]
### Prerequisites

* [N, but this is irrelevant, it's a bug in apm] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [Y] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [Y] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [Y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Updating an atom package takes 100% or more CPU.

### Steps to Reproduce

1. Be on Mac OS X El Capitan
2. Update a somewhat large package.
3. Close tab.

**Expected behavior:** It should have updated quietly.

**Actual behavior:** My fans turned on, my CPU was maxing out at 170% usage from apm.

### Versions
Latest version.

**Comment by lee-dohm** [comment]
If this is a problem with apm usage at the command line, this belongs on the https://github.com/atom/apm repo. If this is a problem with updating packages through the Settings View, this belongs in https://github.com/atom/settings-view. Would you mind reopening this on the correct repository?
