### ISSUE TITLE
Reindexing message should not cause jumpy list.

### ISSUE THREAD

**Issue by jordwalke** [atom/atom#11079]
(Latest Atom beta):
This is some design feedback on the command+t panel (in the `One Dark` theme). The fact that the "reindexing project" message appears is pretty cool - however, because of how the layout is designed, it causes the list itself to jump (which makes it distracting). The layout should preserve a place for messages to be shown in the dialog without causing the list rows to jump around when the "reindexing" message is shown/hidden).

I'm not sure if this is related only to the `One Dark` theme, because I saw it happen with multiple UI themes. Fixing this would make Atom feel more solid.

**Comment by 50Wliu** [comment]
@jordwalke can you please move this to the [fuzzy-finder](https://github.com/atom/fuzzy-finder) package?  Thanks!
