### ISSUE TITLE
apm install failed in HTTP 404 error when gyp is downloading node.js with a fresh install atom

### ISSUE THREAD

**Issue by skywind3000** [atom/atom#11080]
### Description

[Description of the bug or feature]
apm install failed in HTTP 404 error when gyp is downloading node.js with a fresh install gyp. This issue will stop new users from downloading any package.
### Steps to Reproduce
1. Mac Refresh install ATOM latest version: 1.54
2. goto command line
3. type: "apm install script"
4. 404 happen:

```
bogon:~ linwei$ apm install script
Installing script to C:\Users\linwei\.atom\packages
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp http 404 https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp WARN install got an error, rolling back install
gyp
bogon:~ linwei$ 
```

**Expected behavior:** [What you expected to happen]
package 'script' should be installed if I type "apm install script"

**Actual behavior:** [What actually happened]
gyp failed into 404, seems like gyp doesn't recognize http 302 redirection.
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

```
bogon:~ linwei$ atom --version
1.5.4
bogon:~ linwei$ apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.4
```

**Comment by gwind** [comment]
:+1: nice bug report!

I've got the same problem when exec `apm update`:

```
gwind@X201I $ atom --version
1.5.4
gwind@X201I $ apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1
gwind@X201I $ apm update
...
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp http 404 https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: 404 response downloading https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1584:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Linux 3.19.0-32-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/no
de-gyp.js" "install" "--target=0.34.5" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /data/home/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

I've wget the `https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz`:

```
$ wget https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
...
2016-03-08 13:20:54 (3.50 MB/s) - ‘node-v0.34.5.tar.gz’ saved [441298/441298]

gwind@X201I $ md5sum node-v0.34.5.tar.gz 
695ad0670ca7cda2a81c9c1b66918b10  node-v0.34.5.tar.gz
```

I've test http/sock5 proxy also:

Any help would be appreciated!
Thanks

**Comment by gwind** [comment]
Resolved at https://github.com/atom/apm/issues/322 !

btw, if you are in china, config your proxy at `~/.atom/.apmrc`:

```
strict-ssl = false
proxy=http://127.0.0.1:20090/
http_proxy=proxy
https_proxy=proxy
```

Thanks @TedThiCo

--------------------------

Seems that node-gyp isn't following the 302 Redirect sent by atom.io.

@fujisaks Thanks for pointing to the problem!

I've been able to workaround the issue by setting the ATOM_NODE_URL env variable to the new url (after redirect ). This should also be working after you update Atom. However, remove the entry when the bug gets fixed!

Windows temporary:
set ATOM_NODE_URL=http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist

Windows permanently:
setx ATOM_NODE_URL http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist /M

Linux
export ATOM_NODE_URL=http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist

**Comment by hedefalk** [comment]
+1

**Comment by wujunchuan** [comment]
I use shadowsocks proxy ,edit the file `~/.atom/.apmrc`:
```
strict-ssl = false
proxy=http://127.0.0.1:1080/
http_proxy=proxy
https_proxy=proxy
```
and then run `apm install --check`
if success you and see `Checking for native build tools done`
remember,shadowsocks mode choose `system agent mode`

**Comment by zhanfenghai** [comment]
when i install docblockr，i got this error underline

yp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v0.37.8/node-v0.37.8.tar.gz
gyp WARN install got an error, rolling back install

**Comment by dingshanliang** [comment]
I use shadowsocks proxy too, in china , and I do exactly what you describe, but It still dosn't  work.

`dingshanliang:.atom ericding$ apm install --check
Checking for native build tools ✗

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v1.3.15/iojs-v1.3.15.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: tunneling socket could not be established, cause=Parse Error
gyp ERR! stack     at ClientRequest.onError (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/tunnel-agent/index.js:177:17)
gyp ERR! stack     at ClientRequest.g (events.js:291:16)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:368:9)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:176:18)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:134:10)
gyp ERR! stack     at TCP.onread (net.js:548:20)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.3.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure" "--proxy=http://127.0.0.1:1080/"
gyp ERR! cwd /Users/ericding/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok`

**Comment by dingshanliang** [comment]
I use shadowsocks proxy too, in china , and I do exactly what you describe, but It still dosn't  work. @wujunchuan 

```
dingshanliang:.atom ericding$ apm install --check
Checking for native build tools ✗

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v1.3.15/iojs-v1.3.15.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: tunneling socket could not be established, cause=Parse Error
gyp ERR! stack     at ClientRequest.onError (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/tunnel-agent/index.js:177:17)
gyp ERR! stack     at ClientRequest.g (events.js:291:16)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:368:9)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:176:18)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:134:10)
gyp ERR! stack     at TCP.onread (net.js:548:20)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.3.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure" "--proxy=http://127.0.0.1:1080/"
gyp ERR! cwd /Users/ericding/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

```

**Comment by wujunchuan** [comment]
@dingshanliang 
I saw your apm logs,It show that `Error :tunneling socket could not be established`
Please check your shadowsocks proxy is work well or  **shadowsocks proxy port is setting right**.
Take me as an example, my shadowsocks proxy port is `1080`.
