### ISSUE TITLE
Feature Request: Tree View Groups & Custom Project Names

### ISSUE THREAD

**Issue by julmot** [atom/atom#11082]
The Atom Tree View should allow users to group projects and show/hide those groups. Also it should allow users to set custom project names (instead of showing the actual folder names).

**Current and suggested behavior**

Currently you will have to remove projects from Tree View when you don't need them anymore and don't want to inundate the UI. Also you will have to name your projects folder unique to know what you're inside.

This should be not necessary anymore.  
It should be possible to group projects, like:

```
organization A
-- project 1
-- project 2
organization B
-- project 1
-- project 2
```

Also it should be possible to adjust the name that is shown in Tree View for a project.

**Why would the enhancement be useful to most users**

When you are working for multiple organizations or you are using Atom for private and for business purposes, you would want to separate projects.

When working on projects where the source code is just a part of it, you will often name the source code folder "sandbox" or "repository". In Atom Tree View you will lose the overview when having multiple folders called the same.

Both things are possible in Eclipse. Eclipse stores the name of a project in `.project`. Groups are saved in internal files. 
In my opinion those things should be stored in internal files, that they can not be copied to a remote repository by mistake.

**Atom Version:** 1.5.3
**OS and Version:** Windows 10

**Comment by albertosantini** [comment]
If the issue https://github.com/atom/atom/issues/2203 was implemented, the layout of the folders might be implemented accordingly as you like.
