### ISSUE TITLE
MSI installer

### ISSUE THREAD

**Issue by duhow** [atom/atom#11087]
In order to deploy the installation / update of the software, it would be useful if the installer was in MSI format.

**Comment by julmot** [comment]
just for my interest: what exactly is your use case?

**Comment by 50Wliu** [comment]
@duhow have you tried `AtomSetup.exe --machine`?

**Comment by duhow** [comment]
@julmot The idea is to add the installer into Active Directory GPO on my Windows Server, and with it, all the machines will download the installer and execute it, also useful for updates.

**Comment by paulcbetts** [comment]
`AtomSetup --machine` is actually deprecated as of Squirrel.Windows 1.2.5, which also generates MSI packages automatically. This should be just a matter of Atom taking the file they're generating and publishing it somewhere, similar to what Slack does: https://get.slack.help/hc/en-us/articles/212475728-Deploying-Slack-via-Microsoft-Installer

**Comment by damieng** [comment]
Since we upgraded to the latest Squirrel scripts\build generates both an AtomSetup.exe and an AtomSetup.msi

People interested in the msi could checkout the source for that release and build or atom.io could consider distributing the .msi

**Comment by teknowledgist** [comment]
a) Would the .msi install once for all users (i.e. a multi-user install), or install to the current user profile like the .exe does?
b) If the latest build generates both an .exe and .msi, why wouldn't both be made available?

**Comment by damieng** [comment]
a. It is still a per-user install
b. We are considering making both available - I'll try and get an update on
this later today

**Comment by bittin** [comment]
Also interested in an .msi

**Comment by paulcbetts** [comment]
> Would the .msi install once for all users (i.e. a multi-user install), or install to the current user profile like the .exe does?

The MSI will ensure that all users on a machine get the app installed, without the admin having to install it for every user individually

**Comment by damieng** [comment]
Good news! We're going to go ahead with and include an .msi on the releases page once it's been tested and QA'ed by the team.

**Comment by swirly** [comment]
Good news. I will deploy atom in my college for the pupils now there is a MSI !

**Comment by bittin** [comment]
awesome <3 :)

**Comment by damieng** [comment]
Testing is complete. Getting the docs updated and the file added to the releases page.

**Comment by bittin** [comment]
Cool can you ping this thread when it can be downloaded ?

**Comment by damieng** [comment]
Will do.

**Comment by niemalsnever** [comment]
Sorry for sounding impatient, but any news on this topic? Did you find issues with the MSI last-minute preventing it from being published?

**Comment by damieng** [comment]
Testing is complete, getting somebody with access to the official build server to perform the steps necessary to publish it to releases as part of that process.  Will update this issue when that is done.

**Comment by bittin** [comment]
Download this MSI at work today

**Comment by damieng** [comment]
There is a delay on this right now because of the signing process. The current official signed build server we use can't be used to sign the MSI because of the way the Squirrel packaging system works.  I'm seeing what we can do about this.

**Comment by damieng** [comment]
The additional work is being tracked at:

https://github.com/atom/atom/pull/11791 and https://github.com/atom/atom/issues/11771

**Comment by damieng** [comment]
MSI's are now available from the releases page for both Atom 1.8 and Atom 1.9 beta!

**Comment by rriemann** [comment]
Why have MSIs been removed again?

**Comment by damieng** [comment]
Because they were not the kind of installer anyone was expecting. It was
not an msi alternative to the setup but rather an msi that simply added the
regular setup exe to everybody's auto run.
