### ISSUE TITLE
Conflicted file is not marked as modified

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#11092]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Files that have conflicts in them after a failed merge are not detected as modified in the Tree View or Status Bar, but Git Diff shows the changes correctly.
### Steps to Reproduce
1. Find a branch that has conflicts with another branch
2. Attempt to merge the two
3. Open a file that has conflicts
4. Observe that the Tree View does not color the file as modified, and the Status Bar also reports no changes

**Expected behavior:** Tree View and Status Bar to detect changes

**Actual behavior:** No changes are detected other than Git Diff
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

```
Atom    : 1.7.0-dev-8472f91
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

/cc @joshaber here's another one for you!

**Comment by arcticicestudio** [comment]
I think #10757 is related to this / the same, i've also posted [this](https://github.com/atom/atom/issues/10757#issuecomment-189835181) issue comment describing the same behaviour when doing a multi-edit using find-and-replace.

**Comment by 50Wliu** [comment]
@arcticicestudio It may be related but is not the same.  This scenario does not require other windows open, nor does it refresh upon switching focus.

**Comment by joshaber** [comment]
Ah good catch. It looks like 1.5.4 behaves the same way.

**Comment by 50Wliu** [comment]
Not stale.
