### ISSUE TITLE
Atom should warn on non-dev-mode launch when a default-installed package is overridden in ~/.atom/packages

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#11090]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? (duplicated packages aren't loaded in Safe Mode)
- [X] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Having an additional copy of a default-installed package in `~/.atom/packages` can cause hard-to-diagnose bugs:
- https://github.com/atom/git-diff/issues/85
- among others

Sometimes having an overridden version of a default-installed package is useful for Atom developers but it seems to be causing problems and frustration for unsuspecting regular users. The proposal here is to show an error notification on launch if Atom is not in Dev or Safe Mode. Something like:

<img width="465" alt="screen shot 2016-03-07 at 12 14 26 pm" src="https://cloud.githubusercontent.com/assets/1038121/13581933/2fe002d2-e45e-11e5-81fb-4b7798a050af.png">

### Steps to Reproduce

1. Install a duplicate Core package (ignore the warning) using `apm install git-diff`
2. Launch Atom

**Expected behavior:** A warning to appear

**Actual behavior:** No warning is shown

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

```
Atom    : 1.7.0-dev-f88051e
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by 50Wliu** [comment]
Will this affect packages that have been `apm link`'d?  Non-dev mode runs faster for me, and I have every default language package linked to `~/.atom/packages` :grimacing:.

**Comment by lee-dohm** [comment]
Potentially we could make it so that it only pays attention to packages that are actually installed there, not symlinked. I'm proposing this as a solution for the people that for whatever reason are installing packages that they already have installed :grinning:
