### ISSUE TITLE
^M artifacts upon editing with ATOM PHP files.

### ISSUE THREAD

**Issue by uhlhosting** [atom/atom#11094]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Here is what's happening. In my home directory, the WP config files are full of ^M artifacts. This is preventing the system understand the file, hence why it can't read what the php values are on the server.

This result upon editing all my config files with Atom. Anything you would suggest to never repeat this again?
### Steps to Reproduce
1. Used Transmit and Atom as editors
2. Open any wp-config.php file edit it save it and then issues are there.
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Just a working php file.
**Actual behavior:** [What actually happened]
Files contains ^M artifacts.
### Versions

1.5.4
You can get this information from executing `atom --version` and `apm --version` at the command line.

**Comment by ginkoms** [comment]
Could be unrelated but `^M` is usually a visual representation of a carriage return character (`0xD`). Windows uses `0xD0xA` (`\r\n`) for newlines while Unix like systems use `0xA` (`\n`).

**Comment by highacid** [comment]
@ginkoms I do not know, all I know is that while editing all my files in atom. And saved them, I got reports form Cpanel admins that my files are in windows format with the ^M on them.

**Comment by Ehekatl** [comment]
I can confirm this issue, it happens all the time on my windows machine, line ending convert does not work.
