### ISSUE TITLE
Can't install or build Atom on windows 7

### ISSUE THREAD

**Issue by MikailBag** [atom/atom#11102]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[logs](https://gist.github.com/MikailBag/c81ad9a28e46486ce41c)

When I tried to install Atom (SquirrelSetup.log) and build Atom (npm-debug.log; script/build), I got errors

### Versions
windows 7 (32bit)
node 5.7.1
npm 3.6.0

**Comment by 50Wliu** [comment]
@MikailBag please disable any antiviruses and try again.

**Comment by MikailBag** [comment]
Now Atom was successfully installed.
But build failt with the same error

**Comment by damieng** [comment]
What version of Visual Studio do you have installed?

**Comment by damieng** [comment]
No response for more information, closing. Please re-open if issue persists.
