### ISSUE TITLE
Mult-file multiple-line find (& replace)

### ISSUE THREAD

**Issue by ArekSredzki** [atom/atom#11107]
Enhance multiple-line find (& replace) to work for multiple files.

**Steps which explain the enhancement**
1. Press `meta-shift-f`
2. Enter your desired multiple-line find and replace values
3. Hit find (or replace/replace all) to complete the appropriate actions across all relevant files

**Current and suggested behavior**

Currently find (& replace) supports multiple-line entries in the currently open file, however no results will be returned if this is attempted for a multi-file search.

It would be very valuable to be able to do this... I find myself wishing this behavior was offered more than I would hope.

**Why would the enhancement be useful to most users**

Find & Replace is an invaluable tool in a multitude of scenarios, but one concrete example is when modifying multiple JSON files which contain the same, outdated schema.

If course this is only _one_ of _many_ possible use cases.

**Atom Version:** 1.5.4
**OS and Version:** All

**Comment by dphiffer** [comment]
I just encountered this issue and would find the enhancement described here useful.
