### ISSUE TITLE
View scroll issues with Atom 1.6.0-beta0+

### ISSUE THREAD

**Issue by ShMcK** [atom/atom#11104]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Functionality works in Atom 1.5 but not 1.6 beta.

Cannot scroll within a React based plugin inside of Atom as of Atom 1.6.0-beta0 through the current beta7.

<img width="1079" alt="screen shot 2016-03-08 at 11 04 12 am" src="https://cloud.githubusercontent.com/assets/4660659/13612788/3f72110c-e51e-11e5-9559-a352edee45d5.png">

Additionally, running ReactDOM on a target with `scrollIntoView()` results in strange behavior not found in Atom 1.5:

<img width="1277" alt="screen shot 2016-03-08 at 11 04 48 am" src="https://cloud.githubusercontent.com/assets/4660659/13612792/42ad51b0-e51e-11e5-84a9-f83a016132c3.png">

This leads me to believe that the view is handled significantly differently in 1.6, and may have an effect on other plugins as well.

### Steps to Reproduce

1. apm install atom-coderoad
2. follow basic install directions
3. Run the app and complete an initial task.

**Expected behavior:** Scrollable, no scroll target issues.

**Actual behavior:** Not scrollable, scroll target effects workspace as well.

### Versions

Issues occur with Atom 1.6-beta0 ~ 7. No problems in Atom 1.5.

**Comment by lee-dohm** [comment]
I've installed the package but I couldn't decipher the installation instructions to figure out how to download and/or install a tutorial to reproduce this issue. Can you supply a minimum repro?

**Comment by ShMcK** [comment]
- Create a new project with a file called `package.json` to your repo with these contents.
```json
{
  "name": "demo",
  "dependencies": {
    "coderoad-functional-school": "^0.1.9",
  }
}
```
- Run `npm install` from terminal inside of the folder.

- Toggle open *Atom-CodeRoad* from the packages menu

Thank you for your help.

**Comment by ShMcK** [comment]
A comparison:

As expected in 1.5.4:
* scroll works

![1 5 4-scroll-issue](https://cloud.githubusercontent.com/assets/4660659/13621111/df9284de-e549-11e5-811b-e98c9a46e3b1.gif)

Unexpected in 1.6.0-beta:
* scroll not working
* workspace effected by `scrollIntoView()` call in panel

![1 6 0-beta8-scroll-issue](https://cloud.githubusercontent.com/assets/4660659/13621121/ec4e483e-e549-11e5-8308-19c0e4a21f4c.gif)

**Comment by ShMcK** [comment]
I can get scroll to work when changing the height to a given number of pixels rather than a percentage. I'm not sure why this changed occurred between 1.5 & 1.6.

```json
  height: 100%; // scroll in 1.5, no scroll in 1.6
  height: 800px; // scroll in both 1.5 & 1.6
```

Additionally, scrollIntoView targeting can likely be handled with some clever math. 

With some workarounds, I'll consider the issue closed.
