### ISSUE TITLE
Identical folders are opened as separate projects on case-insensitive filesystems

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#11114]
### Description

On case-insensitive (but case-preserving) filesystems, opening a project by passing its folder to the `atom` command will not restore the project, if the path given has the wrong case.
### Steps to Reproduce
1. Create a project in Atom with 1 folder (e.g. `~/Foo`).
2. Open some tabs in that project.
3. Close the window.
4. Reopen the project using the `atom` command with a name differing only in case (e.g. `atom ~/FOo`).

**Expected behavior:** Atom restores the previously open tabs for that project.

**Actual behavior:** Atom creates a brand-new project with the wrongly-cased root folder `CApe`, and does not restore the tabs from the original project.
### Versions

OS X.11 x86_64, Atom 1.5.4.

**Comment by Ben3eeE** [comment]
No problems reproducing this on windows 7 atom 1.7.3 in safe mode, got nothing to add to the original steps they are very clear.
Maybe a fifth step can be added that if you reopen Foo with correct case the original state serialized in step 3 is restored.

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed on the latest version of atom `v1.51.0`. Consider upgrading to the latest atom version.
