### ISSUE TITLE
Using the middle mouse button to scroll the editor.

### ISSUE THREAD

**Issue by phoenixenero** [atom/atom#11113]
Allow the editor to scroll using the middle mouse button. It would be an nice feature to have.

Saw it in Visual Studio power tools:

https://visualstudiogallery.msdn.microsoft.com/d0d33361-18e2-46c0-8ff2-4adea1e34fef

Here's a demo image.

![](http://i3.visualstudiogallery.msdn.microsoft.com/d0d33361-18e2-46c0-8ff2-4adea1e34fef/image/file/46443/1/middleclickscrolling.png)

**Comment by 50Wliu** [comment]
Hi @phoenixenero, this looks like a duplicate of #6884, so feel free to subscribe there for updates.
