### ISSUE TITLE
Help>Roadmap menu option opens browser to a page that doesn't exists

### ISSUE THREAD

**Issue by davidnagli** [atom/atom#11119]
In the menu, if you navigate to Help>Roadmap it opens the browser to https://atom.io/roadmap?app which return a 404 page. 

I'm using Ubuntu but the issue is likely cross platform.

**Comment by 50Wliu** [comment]
@davidnagli Thanks for the report!  This has already been fixed and the offending menu item should be gone in Atom 1.7.0 (as the Roadmap has been removed).
