### ISSUE TITLE
Atom freezes frequently when a network/UNC file is open on Windows

### ISSUE THREAD

**Issue by mlalkaka** [atom/atom#11118]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
  * *Yes: Version 1.5.4 on Windows.*
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
  * *Yes, but I couldn't find how to profile Atom on startup. (I have a UNC/network file open in the project workspace, and every time I open Atom, it freezes before I can do anything.)*
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
  * *I skimmed it, but couldn't see anything relevant other than the debugging guide.*
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
  * *Probably not, but I didn't know which repository was most relevant.*
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
  * *Yes. I found some that sound similar, such as #2456 and #1766, but neither of them involve Atom completely freezing. They only report Atom performing poorly. In this case, Atom actually freezes/hangs. I've tried leaving it for multiple hours, only to find it still frozen.*

### Description

When I leave a network/UNC file (e.g. "\\host\share\folder\file") open, Atom eventually freezes. If I leave UNC file open in my project workspace, opening that project again results in Atom freezing as soon as I open it.

I am running Atom on Windows.

### Steps to Reproduce

1. Open a network/UNC file in Atom.
2. Edit it and save the file. (Possibly not necessary.)
3. Leave Atom open for some time.
4. Return to Atom. Atom will likely have frozen.
  * Alternatively, close Atom and try re-opening the same Atom project later.

**Expected behavior:** Atom is responsive to user input.

**Actual behavior:** Atom is not responsive to user input. It is frozen/hung.

Please let me know if I can help profile or investigate this in some way.

### Versions

```
> atom --version

1.5.4

> apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python
git 1.9.5.msysgit.0
visual studio 2013
```

**Comment by mlalkaka** [comment]
In trying to investigate and reproduce this more, I found that the freeze may actually be caused by the spell-check package checking the spelling of a large (2MB) text file in the work space upon starting Atom. I'll reopen this issue if it turns out I'm wrong.

**Comment by 50Wliu** [comment]
@mlalkaka If it is in fact spell-check causing the performance problems, you might want to try the 1.6.0 betas, which I believe massively improved spell-check performance.
