### ISSUE TITLE
Atom not Loading up, I get these errors, can't use at all. 

### ISSUE THREAD

**Issue by erinjerri** [atom/atom#11128]
![image](https://cloud.githubusercontent.com/assets/3184381/13690869/e548ad54-e6e8-11e5-87b7-9471e0c32123.png)

**Comment by 50Wliu** [comment]
Please update Atom to the latest version, currently Atom 1.5.4.

**Comment by erinjerri** [comment]
What's the easiest way to upgrade on Mac? Should I be using NPM/NVM? https://github.com/atom/atom/blob/master/docs/build-instructions/os-x.md

**Comment by 50Wliu** [comment]
If you're on Mac, it should auto-update.

**Comment by lee-dohm** [comment]
@erinjerri If you're having problems running Atom so that it doesn't auto-upgrade, you can also drag your current copy of Atom to the trash and then download the latest version from the website at https://atom.io.

**Comment by erinjerri** [comment]
I tried that and it still doesn't work, it freezes up and shows the editor is
not responding, the same exact thing with the previous version I had.




On Fri, Mar 11, 2016 at 1:30 PM, Lee Dohm < notifications@github.com > wrote:
@erinjerri If you're having problems running Atom so that it doesn't auto-upgrade, you can
also drag your current copy of Atom to the trash and then download the latest
version from the website at https://atom.io .

—
Reply to this email directly or view it on GitHub .




Erin Pangilinan erinjerri16@gmail.com

**Comment by lee-dohm** [comment]
Can you reproduce the problem in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`
