### ISSUE TITLE
Atom Crashes on Windows 10 (Every Time)

### ISSUE THREAD

**Issue by summitweb** [atom/atom#11134]
![atom-error](https://cloud.githubusercontent.com/assets/5718820/13702476/dcbf04f0-e786-11e5-9917-a351d9aafedd.jpg)
In the last week or so Atom has stopped working on my Windows 10 machine. I use the same packages/extensions as on my mac machine and that's working fine, so I don't think it's a package problem.

The Editor loads but appears blank. Once I resize the window the black editor screen appears along with the tabs of opened files from my last session/project. But nothing responds.

### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)
Yes it happens in Safe Mode. Here's the output:

[http://resource-centre.net/files/atom-error.jpg] (http://resource-centre.net/files/atom-error.jpg)

* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
Yes.
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
I can't load any of the config screens, but the menus appear.

* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?

* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
I think so.

* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
Yes, different people have different causes/solutions.

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
Load Atom in Windows. 10

2. [Second Step]
Nope that's it!

3. [and so on...]

**Expected behavior:** [What you expected to happen]
The last project opens and I can get on with work.

**Actual behavior:** [What actually happened]
The screen is blank until I resize it, then the tabs/editor appears but nothing's clickable and no menus work. They appear but clicking a menu item does nothing.

### Versions
1.5.4
You can get this information from executing `atom --version` and `apm --version` at the command line.

**Comment by summitweb** [comment]
Update: A clean reinstall (after a full install) still gave the same result. Thanks.

**Comment by neeraj07rathi** [comment]
+1

same is happening with my Atom on Windows 8.1 also.

**Comment by Sbonhom1** [comment]
I'm having the same exact issues on Windows 10. I even tried uninstalling and even installing the portable version of Atom and even that started crashing.

**Comment by damieng** [comment]
Definitely not experienced this problem on Windows 10 64-bit with latest code from master as that's my daily driver, will test 1.5.4.

**Comment by damieng** [comment]
Just tried this again on Windows 10 without a problem.

Can you try renaming the .atom folder in your home folder to something else and see if it launches then? I'm suspecting some corrupt/incompatible file in there and that folder is not removed as part of uninstall.

**Comment by summitweb** [comment]
I will give it a go but a clean install on Windows 10 64 Bit (which is what I have didn't work earlier). Happy to try again.

**Comment by damieng** [comment]
What do you mean by clean install? On a machine that's never had atom before?

If people experiencing this problem also let us know what graphics card they are using to help narrow down on the common factors.

**Comment by summitweb** [comment]
No I had to uninstall Atom and re-install it to try to fix this. That's what I meant by 'clean install' sorry.

**Comment by summitweb** [comment]
Nope I renamed the .atom file and this is the result. 
![atom-crash](https://cloud.githubusercontent.com/assets/5718820/13763363/7eb57a06-ea3d-11e5-8dde-787e28f82628.jpg)

It doesn't get past this stage.

**Comment by damieng** [comment]
What graphics card are you using?  It looks like the part of the screen that is rendered using DirectWrite is not rendering...

**Comment by summitweb** [comment]
NVIDIA GeForce GT 750M

I was working a couple of weeks ago and then just stopped (and I didn't upgrade my drivers in the interim). I hope to get this working, Atom is my preferred editor for work and personal projects now!

Thanks!

**Comment by damieng** [comment]
Using an Nvidia GTX 980 here without problem (using latest WHQL drivers from Nvidia). 

Are you using the drivers directly from Nvidia or the ones that come with Windows?  Either way can you let us know the version number.

The fact it suddenly broke one day for a bunch of people has me wondering if this maybe was a Windows Update that has cause it.

Everyone else please feel free to let us know what video card/driver you're using. We really want to get to the bottom of this.

**Comment by summit-web** [comment]
I'm using the drivers directly from NVIDIA. I tried doing an update yesterday but the driver manager fails to update to the latest drivers. I'm a bit reluctant to uninstall and reinstall as that causes massive display issues, but if that's what I have to do, I will. I'll grab the version number when I get home.

**Comment by summitweb** [comment]
I just updated to the latest drivers to make sure. 

NVIDIA GeForce Experience: Driver Version 364.51

And the same issue occurs. Not sure that helps but it rules out the old-driver issue as being the cause.

**Comment by morrisonbrett** [comment]
I'm running on a Surface Book.  I just tried the Beta Channel of Atom and it works now.

**Comment by summitweb** [comment]
How do you get onto the beta if the editor won't load, please?

**Comment by 50Wliu** [comment]
@summitweb https://atom.io/beta.

**Comment by summitweb** [comment]
Thanks! (Sorry for being unobservant!)

**Comment by morrisonbrett** [comment]
Both 1.6 release and 1.7-beta are now working for me.  No more all black/all white screen on my Surface Book.

**Comment by summit-web** [comment]
I'll run an update tonight and see if that fixes it then, thanks.

**Comment by summitweb** [comment]
The latest update to the beta version appears to fix this. Once I've reconfigured my lost extensions and re-added the projects (hoping to do that tomorrow or Monday) I'll close this ticket if it's all okay.

Thanks so much to those who chatted through this issue with me!

**Comment by summitweb** [comment]
This issue is definitely not happening now on Atom beta. I haven't tried the stable install but as I just need it to work I'll stay on the beta channel. Thanks!

**Comment by PyroSA** [comment]
I had a similar issue.
Interface loads as blank screen. (Windows 10 x64, Atom 1.6.1) I upgraded from an unknown previous version, and then again from 1.5.4. Neither worked.

As suggested by @guptadivyansh, clearing out the roaming folder solved it.
https://github.com/atom/atom/issues/4351#issuecomment-186504559

Log file:
[blankload.SquirrelSetup.log.txt](https://github.com/atom/atom/files/198718/blankload.SquirrelSetup.log.txt)

**Comment by app-sparkler** [comment]
+1

@50Wliu @morrisonbrett  Thanks for the suggestion and link for [atom beta](http://atom.io/beta).

I was working with Atom v1.7.4 and it was crashing a lot.  Downloaded and clean installed (wiped out `.atom` dir) the beta version and its going strong so far.

**Comment by damieng** [comment]
@reiallenramos The atom-html-preview package is a third party package and not maintained by the Atom team.  Issues with it can't be addressed here.

**Comment by grbd** [comment]
I've had this problem with Chrome and a few other things after the windows 10 creators update
in this case I think the atom-html-preview is pulling in something that's causing a similar crash

One way around it is to right click the shortcut / set it to run in compatibility mode under Windows
also disabling hardware acceleration might be another way to fix

**Comment by Jack-Kingdom** [comment]
Fresh installed and crashed every time on startup, safe mode and beta version crashed too.

**Comment by damieng** [comment]
@Jack-Kingdom this is an old issue which has been resolved. If you're having a problem now with a recent version can you please open an issue with the appropriate template filled in to help diagnose the issue.

**Comment by pasideepak** [comment]
Thanks, renaming .atom folder under user's profile directory c:\users fixed the problem for me.  Will monitor further.
