### ISSUE TITLE
gulp watch task will crash by atom, but ok with sublime text.

### ISSUE THREAD

**Issue by Pleasurazy** [atom/atom#11130]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
  Yes, start atom with $ `atom --safe`
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
  Yes, 1.5.4
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
  Yes, both of `(no links)`
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
  Yes, by keyword `gulp ENOENT`
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
  I think, Yes. I removed everything that in `~/.atom/packages` and quit application and re-start atom.
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
  Yes, https://github.com/atom/atom/issues/8610#issuecomment-194997415

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Run gulp default task, and open js file, hold cmd+s, crash with <kbd>atom</kbd>, but ok with <kbd>sublime text</kbd>.

demo: https://github.com/Pleasurazy/atom-issue-gulp-crash
### Steps to Reproduce
1. run gulp watch
2. open js file with atom
3. hold <kbd>cmd+s</kbd> with atom

**Expected behavior:**

``` sh
[12:06:52] Finished 'compile' after 3.38 ms
[12:06:52] Starting 'compile'...
[log] through /Users/pleasurazy/git/atom-issue-gulp-crash/app/assets/pages/welcome/index.js
[log] event finish sent
[12:06:52] Finished 'compile' after 3.37 ms
[12:06:52] Starting 'compile'...
[log] through /Users/pleasurazy/git/atom-issue-gulp-crash/app/assets/pages/welcome/index.js
[log] event finish sent
etc..
```

**Actual behavior:**

crash randomly..

``` sh
 pleasurazy@retina  ~/git/atom-issue-gulp-crash   master  gulp
[12:07:51] Using gulpfile ~/git/atom-issue-gulp-crash/gulpfile.js
[12:06:52] Finished 'compile' after 3.37 ms
[12:06:52] Starting 'compile'...
....a while
[12:07:51] Starting 'default'...
[12:07:51] Finished 'default' after 8.86 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat '/Users/pleasurazy/git/atom-issue-gulp-crash/app/assets/pages/welcome/index.js~'
    at Error (native)
```
### Versions

atom 1.5.4
gulp 3.9.1
mac os x 10.11.3
npm 3.8.1
node 4.2.6

**Comment by stewhouston** [comment]
Not sure where this stands. Gulp is not pitching errors for me as you've displayed above, but atom is crashing every 10 minutes or so.

**Comment by KeironLowe92** [comment]
I'm experiencing the same issue, I believe it's to do with the temporary files created by the "Back up before saving" option in Atom preferences. Disabling that option fixes the issue although it's not ideal. 

Not really sure who's problem this is, Atom or Gulp Watch. I've opened an issue on the [Gulp Watch repo](https://github.com/floatdrop/gulp-watch/issues/238).

**Comment by floppey** [comment]
I'm experiencing the same issue too. Every time gulp-watch is triggered, atom crashes.

**Comment by jxxcarlson** [comment]
I too am experiencing this error.  Backup before saving _is_ disabled.

**Comment by KeironLowe92** [comment]
I believe this is an issue with Gulp Watch rather than Atom. It seems gulp watch will crash on any/some temporary files, not just Atom backup files. 

I've had the error also occur on the temporary files created by OSX when a download is in progress (.crdownload files).
