### ISSUE TITLE
Remove Tooltips and Animations!

### ISSUE THREAD

**Issue by DHidee66** [atom/atom#11141]
Hi,

Is there a way to remove all the tooltips and animations?
- Blue tooltip showing under the tabs
- Animation of the tab close button
- Define a working set plus button
- Tooltip over strings etc.
Maybe an option in the settings to turn off all the animations would be helpful.

Thank You!

**Comment by arcticicestudio** [comment]
These elements are configured by the UI theme. Some UI themes provide additional settings (gear icon next to the theme name) providing options to disable animations.
Anyway, you can overwrite the theme rules via the `styles.less` file in your `.atom` folder or by open it via the command palette: *"Application: Open Your Stylesheet"*

**Disable tooltips**
You can set the `display`- and `visibility` property to prevent tooltip popups:
```css
.tooltip {
  display: none;
  visibility: hidden;
}
```

**Disable tab close-icon animation**
You can overwrite the `:hover` pseudo class of the `.close-icon` class for tabs with a empty selector:
```css
.tab-bar {
  .tab {
    .close-icon {
      &:hover {
        /* Empty selector block to prevent close-icon animation */
      }
    }
  }
}
```

> - Define a working set plus button
> - Tooltip over strings etc [...]

Sorry, I don't know what you mean for these two list items.

**Comment by jerone** [comment]
There's a forum to discuss non-issue related topics: https://discuss.atom.io/

**Comment by DHidee66** [comment]
@arcticicestudio Thank you for your help :)
