### ISSUE TITLE
Having issues on a QWERTY Spanish Keyboard

### ISSUE THREAD

**Issue by Jesusz0r** [atom/atom#11143]
### Description

I can't type colons (:) or closing brackets (]) when using a QWERTY Spanish Keyboard.

### Steps to Reproduce

1. Just use a QWERTY Spanish Keyboard

**Expected behavior:**
When I type the symbol shown in my keyboard, I expect it to apper in the text editor

**Actual behavior:**
When I try to type a colon (:) a greater than (>) symbol appears instead.
When I try to type a closing bracket (]) nothing happens.

### Versions

1.5.4

**Comment by 50Wliu** [comment]
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.
