### ISSUE TITLE
All views (pane?) and tabs are not really visible (very small width)

### ISSUE THREAD

**Issue by MoOx** [atom/atom#11148]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Currently, I have one project (folder) that open views with a very limited width, see screenshots below (taken in SAFE MODE).
### Steps to Reproduce
1. Open [my setup repo](https://github.com/MoOx/setup) (not sure if that's related to some local cache). **Note that this only happen in this folder** (from what I see), didn't find any other yet).
2. Open a new document (cmd+n) or about or settings page

**Expected behavior:** Normal (full) view width, with correct tab visibility

**Actual behavior:** View/tabs are not visible as they used to be

_Screenshots taken in safe mode_

![screen shot 2016-03-13 at 06 34 51](https://cloud.githubusercontent.com/assets/157534/13727146/fff9d3da-e8e6-11e5-8e4e-088105cffdf5.png)
![screen shot 2016-03-13 at 06 35 00](https://cloud.githubusercontent.com/assets/157534/13727148/0002249a-e8e7-11e5-9b6a-9253f1e60c00.png)
![screen shot 2016-03-13 at 06 35 12](https://cloud.githubusercontent.com/assets/157534/13727147/fffd3ec6-e8e6-11e5-8082-72c0951ce0c3.png)

Here is a detailed view. I don't see anything that might take some space here

![screen shot 2016-03-13 at 06 47 01](https://cloud.githubusercontent.com/assets/157534/13727163/7aeae02a-e8e7-11e5-931a-b29ef82121f3.png)

Is there a way I can find some local cache about the opened folder to see if that can fix the issue?
**I previously installed nuclide**, so maybe that is related ?
This bug did not happened when I installed nuclide, but some days after, after I changed some nuclide  config. I disabled nuclide and a lot of plugin, reverted my atom config (from the one versionned in setup repo) and still have the issue in safe mode.
### Versions

❯ atom --version
1.5.4

❯ apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.2

**Comment by MoOx** [comment]
Any idea for a workaround? I can't find a way to have this specific project to be opened correctly.
Can I remove a cache or something?

**Comment by MoOx** [comment]
FYI, same issue on Atom 1.6 beta.

**Comment by 50Wliu** [comment]
@MoOx You can try renaming your `~/.atom` folder to something like `~/.atom-backup`.

**Comment by MoOx** [comment]
Like I said in the description, only a specific project. Does not happen with a fresh .atom folder.

**Comment by 50Wliu** [comment]
Ok, then try removing the `~/.atom/storage` folder, as that contains the serialization state of each project.

**Comment by MoOx** [comment]
Nice, this worked. Do you want me to keep this folder? Maybe it can help you debug this somehow?

**Comment by 50Wliu** [comment]
Yeah, it would be great if you could upload it here as a .zip in case someone from the Atom team wants to take a look at it.

**Comment by MoOx** [comment]
[storage.zip](https://github.com/atom/atom/files/174078/storage.zip)
 Here it is, I tracked the culprit.
