### ISSUE TITLE
The Atom Env Path on Windows constantly breaks after updates.

### ISSUE THREAD

**Issue by lukewatts** [atom/atom#11150]
I'm currently on Atom 1.5.4. I've checked the atom.cmd file and it's pointing to the correct folder, and the path is pointing to `C:\Users\LukeWatts85\AppData\Local\atom\bin`

However, opening from cmd using "atom" no longer works. Instead it says "Cannot find path to specified file".

The "Open with Atom Editor" in the right-click menu also no longer works.

apm no longer runs.

This has happened numerous times before also. There must be a better way to update Atom than creating versioned folders and removing the old ones.

Other info:
Atom v 1.5.4
Windows 8.1

**Comment by 50Wliu** [comment]
@lukewatts sorry to hear that you've been having problems with the auto-updater.  Fortunately a lot of the issues with auto-updating on Windows should be fixed starting in Atom 1.7.0, so I'm going to close this out.

As for versioned folders that is a core feature of Squirrel.Windows, which the Atom team has decided to keep using as the Windows auto-updater framework.

**Comment by lukewatts** [comment]
That doesn't help me right though. How long until 1.7?

**Comment by lukewatts** [comment]
Any tips how I might fix this problem in the meantime?

**Comment by 50Wliu** [comment]
> How long until 1.7?

I can't give an estimate unfortunately - it all depends on when the core team feels that it's ready.  Though once 1.6.0 comes out (which will most likely be within the next two weeks), you should be able to install the 1.7.0 betas.

Can you paste the exact contents of the `atom.cmd` file here?

**Comment by lukewatts** [comment]
```
@echo off
"%~dp0\..\app-1.5.4\resources\cli\atom.cmd" %*
```

**Comment by 50Wliu** [comment]
Ok, and I'm guessing `where atom` also returns `C:\Users\LukeWatts85\AppData\Local\atom\bin\atom.cmd`?  If `...\bin\atom` appears before `atom.cmd`, can you also check the contents of that file?

**Comment by lukewatts** [comment]
It's ok now. 

I added the path to the **global** system env path variable and it all seems to work again now. Not sure why it stopped working with the local path variable though.

Thanks for your time though!
