### ISSUE TITLE
Tab bar is unable to scroll

### ISSUE THREAD

**Issue by Pyngon** [atom/atom#11157]
### Description

The tab bar is unable to scroll. 
After opening more than 20 files (depend on the window size). The newly opened file does not show on the tab.

### Steps to Reproduce

1. Open a folder with more than 20 files.
2. Keep selecting different file until you do not see your opened file being highlighted in the tab bar.

**Expected behavior:** The tab bar should always highlight the file that is being showed in the content.

### Versions

1.5.4

**Comment by amytruong** [comment]
Dupe here: https://github.com/atom/tabs/issues/137

**Comment by amytruong** [comment]
You can also subscribe to :point_up: for updates :smile:
