### ISSUE TITLE
Atom crashes on OS X after 4 key presses when using it for interactive git rebase

### ISSUE THREAD

**Issue by azerupi** [atom/atom#11155]
### Description

I am using `atom --wait` as editor for git. But when trying to do an interactive rebase the editor crashes after input or delete 4 letters (number of letters inputted can vary depending on cursor position). I can navigate fine with the arrow keys, so it's not keypresses that trigger this but rather modifying the displayed text.

Copy / Cut works fine, but pasting causes the crash. Sometimes I can paste 1 time and the crash happens, sometimes I can go up to 3 times. The number of times I can paste something stays consistent when I paste the same thing at the same position.

Tried rebasing another repository, I had to copy paste a line ±10 times to reproduce
### Steps to Reproduce
1. Set atom as git editor
2. Do an interactive rebase 
3. Type a couple of things
4. Watch atom crash

**Expected behavior:** Nothing, I would expect the text to be entered normally and no crash

**Actual behavior:**  Crash
### Versions

```
$ atom --version
1.5.4

$ apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.4
```

OS X El Capitan v10.11.3

**Comment by ChrisJefferson** [comment]
This isn't helpful (to you) but this works for me.

Could you try constructing a full guide, perhaps "from empty terminal", or suggest a git repository which causes this to happen?

Also, does it happen with `atom --wait --safe`?

**Comment by azerupi** [comment]
Sorry, I didn't get a notification :confused: 

>Also, does it happen with atom --wait --safe?

Yes, if I remember correctly, I tried with `--safe` and it didn't change anything.

>Could you try constructing a full guide

I will, but I am away from home until the end of the week.

**Comment by Valenchak** [comment]
azerupi, даже представления не имею что он писал
