### ISSUE TITLE
error with command atom

### ISSUE THREAD

**Issue by summer1988** [atom/atom#11156]
version: osx 1.6.0-beta8
When I use command atom in command line, it occurs error message below:

The application /Applications/Atom.app cannot be opened because its executable is missing.
How can I fix it ?

**Comment by mnquintana** [comment]
This sounds like a system-specific issue – maybe some cleaner app or antivirus accidentally swept up Atom's executable? At any rate, at this point the best thing to do is uninstall it and re-download it from https://atom.io/beta – sorry for the trouble!
