### ISSUE TITLE
Line height is too large by default

### ISSUE THREAD

**Issue by darkred** [atom/atom#11151]
_Using Atom 1.5.4 in win10 x64. Having 1920x1200 resolution in my monitor._

When opening any file in Atom, it shows only 49 lines at any time.
I feel that the current line height is too much.

_For reference:_
```
Sublime Text 3: 71 lines 
 Notepad++ 6.9: 65 lines
      gVim 7.4: 66 lines 
  UltraEdit 23: 67 lines
```

By default Atom has in its settings:
`Line Height` as 1.5 _(as a multiplier of font size)_ and 
`Font Size` as 14

If I set the former to **1.2** (and the latter to **13**),
then the visible lines area becomes on par with the other editors: 69 lines.
 
So, my suggestion is to change these settings default values to 1.2 (and 13) respectively.

**Comment by JoshWillik** [comment]
I just tried out the suggested font sizes, and I think they look uncomfortably cramped.

It's no large hassle to change a setting for something you don't like.

Not an atom developer, just my two cents.

**Comment by darkred** [comment]
My argument is not that it's a hassle to change a setting to your liking. 

But, for a new Atom user (like me) coming from Sublime Text and Notepad++,
my first reaction when opening a file in Atom 
and noticing that it displays such less lines by default (30%, that is 49 vs 71 of ST3),
was that it felt uncomfortable, way too large (even when taking into account that I use a high resolution such as 1920 x 1200), 
and to be frank, even discouraged me from using Atom as my main editor. 
Luckily I searched in Settings and found that the line height (and font size) are user-configurable.
(line height _cannot_ be configured via a keyboard shortcut -- like font size: Ctrl+ +/-/0 )

A user may of course configure the editor to his liking
but I think that the majority of users should be offered a default line height similar to every other text editor by default.


***

_Also, gVim shows 66 lines by default, 
and UltraEdit shows 67_

**Comment by thomasjo** [comment]
> but I think that the majority of users should be offered a default line height similar to every other text editor by default.

Well, as far as I can remember, you are (among) the first that have voiced a strong opinion on this. So my conjecture is that this is not something that is worth changing. I'm voting :-1: on this, but I'll let others chime in first.

/cc @atom/feedback

**Comment by lee-dohm** [comment]
I'm :-1: on changing the defaults because it would be disruptive to some percentage of the userbase (however many are using the default settings because they like them). There is also no clear win here since the font settings are in the main Editor Settings group that most people have no trouble finding.

**Comment by damieng** [comment]
One option we could consider is putting a line-height dropdown on the settings page next to the font size setting.  

Mac OS terminal lets you do something similar so you can trim the additional vertical space.

I'm pretty sure if we change the default line height however we'll see complaints where people want it set back having gone back and forth with the amount of space between lines on my own font.

**Comment by lee-dohm** [comment]
I'd be :+1: to moving the line height setting that's already there:

<img width="781" alt="move-line-height" src="https://cloud.githubusercontent.com/assets/1038121/13755100/d741cfc4-e9d6-11e5-87ac-a76b4a86cf73.png">

Not so big on the drop-down thing since it's a floating-point number and we've gone around on this with the drop-down for tab length. Even when we think restricting it is smart, someone has a use case for adding more values.

**Comment by thomasjo** [comment]
I agree with @lee-dohm; moving the line height setting to be below font size makes infinite sense, but switching to a drop-down is not something we can/should do. Adding support for combobox drop-down would require a fair about of work in the config schema department, etc.

**Comment by simurai** [comment]
We could put Font Size and Line Height into a group. Also, the Font Family. Then they appear together, like the [Invisibles](https://github.com/atom/atom/blob/912df0ae03a7661b40745b0e740aee68e0e56c45/src/config-schema.coffee#L231-L254). We probably could group even more related settings.

@darkred FYI: Here the discussion where the default Font Size and Line Height was changed last: https://github.com/atom/atom/pull/7281.

An argument is that if you could pick between too large or too small, what would cause less harm? With too large, you can still read it (although less lines), but with too small you couldn't.

**Comment by lee-dohm** [comment]
> We could put Font Size and Line Height into a group. Also, the Font Family.

I'll add Font Family to the Issue I just opened.

**Comment by damieng** [comment]
Agreed resolution is to make line height more visible by grouping it with font settings under #11168. Closing.
