### ISSUE TITLE
Move font settings into a single group so they are displayed together

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#11168]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

The "Line Height" setting has a significant visual separation from the "Font Size" and "Font Family" settings when people will often want to change them in concert with each other:

<img width="781" alt="move-line-height" src="https://cloud.githubusercontent.com/assets/1038121/13764377/dfd58a56-ea0b-11e5-9de8-48d1c439da2f.png">
### Steps to Reproduce
1. Launch Atom
2. Open Settings view with <kbd>Cmd+,</kbd> on OS X or <kbd>Ctrl+,</kbd> on other platforms
3. Scroll down so "Font Size" and "Line Height" both appear in the same screen

**Expected behavior:** "Line Height" to immediately follow "Font Size"

**Actual behavior:** Large visual separation (see picture above)
### Versions

```
Atom    : 1.7.0-dev-4798d6d
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```
### See Also
- #11151

**Comment by simurai** [comment]
Reposting my comment here too:

We could put Font Size and Line Height into a group. Also, the Font Family. Then they appear together, like the [Invisibles](https://github.com/atom/atom/blob/912df0ae03a7661b40745b0e740aee68e0e56c45/src/config-schema.coffee#L231-L254). We probably could group even more related settings.
