### ISSUE TITLE
openSUSE \ SLES 12 Package is missing

### ISSUE THREAD

**Issue by elico** [atom/atom#11165]
Hey,
I have seen that there is a RPM package and was wondering if it was tested on them?
Was the RPM built for usage on CentOS\RH\Fedora or also for openSUSE\SLES?

**Comment by daviddavo** [comment]
It works on openSUSE, but you can't download the package with zypper

**Comment by lee-dohm** [comment]
We don't regularly test every release on every flavor of Linux, there are too many of them to do that for the resources we have available.

Also, [we're trying to control the amount of Issues that we have to triage](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
