### ISSUE TITLE
Finding MarkerLayers after they are created

### ISSUE THREAD

**Issue by redbassett** [atom/atom#11175]
I'm looking to access the `MarkerLayer` created by another package in my own package. It appears that when `MarkerLayer`s are created, they are assigned an `id`, but there doesn't appear to be a way to find a specific `MarkerLayer` via its current `id` without knowing the `id`.

Can we get a way to access (non-default) `MarkerLayers` outside of our own packages once they are created?

**Comment by lee-dohm** [comment]
See discussion: https://discuss.atom.io/t/get-mispellings/26676
