### ISSUE TITLE
Legal still displays 2015

### ISSUE THREAD

**Issue by AppIns** [atom/atom#11177]
I am using Atom version 1.5.4 and for typing legal and using the auto-complete feature I get 
"Copyright (c) 201**5** Copyright Holder All Rights Reserved."
When it should be:
"Copyright (c) 201**6** Copyright Holder All Rights Reserved."

**Comment by thomasjo** [comment]
This was fixed in https://github.com/atom/atom/commit/a04c552fb710c3b147a55d824f260beac6cb3e34 and will be available in upcoming releases of Atom.

**Comment by AppIns** [comment]
Thanks
