### ISSUE TITLE
Can Atom build in environment of Windows 7 (sp1) & Visual Studio 2015?

### ISSUE THREAD

**Issue by chendeshen** [atom/atom#11170]
As shown below: cannot vs2015 with Win7???

<QUOTE>

Visual Studio

You can use either:

Visual Studio 2013 Update 5 (Express or better) on Windows 7, 8 or 10
Visual Studio 2015 (Community or better) with Windows 8 or 10

<QUOTE>

**Comment by damieng** [comment]
It might be possible - I just don't think anyone has tested that particular combination.

Try following the build instructions and remembering to set the VS2015 stuff correctly on Windows 7 and there's a reasonable chance it works. Let us know ;-)

**Comment by damieng** [comment]
No need to keep this open.
