### ISSUE TITLE
Incorrect css for JS contant objects or functions

### ISSUE THREAD

**Issue by Nokel81** [atom/atom#11185]
I have noticed that if a constant has sub items (in JS) that if you call of use them like
`const data = {
    "name":"Test"
};
console.log(data.name);
console.log(data);`

And look at the calling data (the one in the console log) in the developer tools then it has class "span.variable.other.object.js" but the declaration has "span.constant.other.js", the log of just the data also is "span.constant.other.js"

I believe that this is an error

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/language-javascript? Thanks!
