### ISSUE TITLE
issue in search text in specified files

### ISSUE THREAD

**Issue by praveendinesh6** [atom/atom#11197]
**steps to reproduce**
I have "folder a" with "file 1" and "folder b" with "file 2"
please refer the images 
1. search for  keyword "**simply**" in "**folder a**" (give the directory in file/directory pattern). The search result will show the result found for "**folder a**.
![screen shot 2016-03-18 at 3 21 38 pm](https://cloud.githubusercontent.com/assets/10971670/13874442/e8e832e6-ed1d-11e5-8dc5-c4364363b28f.png)
2. If the "**file2**" in "**folder b**" containing the same keyword "**simply**" is opened and closed. The search result is showing result in "**file2**" even though the file pattern in search is "**folder a**"
![screen shot 2016-03-18 at 3 27 39 pm](https://cloud.githubusercontent.com/assets/10971670/13874499/52c41d38-ed1e-11e5-8663-4f4f6fff1502.png)
![screen shot 2016-03-18 at 3 28 31 pm](https://cloud.githubusercontent.com/assets/10971670/13874527/8921a2ba-ed1e-11e5-871c-77b21f3318ae.png)

**Comment by amytruong** [comment]
What OS are you on? and version of Atom? 
I'm going to try and repro. Thanks!

**Comment by Zireael07** [comment]
I am on Win7 x64, Atom 1.5.3, consistently running into this one I search for something under "tome" folder while having files from another folder open. Since they are both for the same game engine, words I am looking for often occur in the open files.

**Comment by praveendinesh6** [comment]
I am on OS X 10.9.5, Atom 1.5.4 @amytruong

**Comment by mnquintana** [comment]
This issue was moved to atom/find-and-replace#688
