### ISSUE TITLE
Wrong icon for 1.6.0 for mac.

### ISSUE THREAD

**Issue by xpol** [atom/atom#11191]
Atom 1.6.0 stable package, [atom-mac.zip](https://github.com/atom/atom/releases/download/v1.6.0/atom-mac.zip), shipped with the yellow icon.
I think Yellow icon is for Beta version.

I can distinguish between stable/beta Atom app, since I install both.

**Comment by lee-dohm** [comment]
I just downloaded atom-mac.zip from the https://atom.io website and it shows with the green icon:

<img width="377" alt="screen shot 2016-03-17 at 10 26 30 pm" src="https://cloud.githubusercontent.com/assets/1038121/13869221/528fdd28-ec8f-11e5-9bde-9df312eb0c72.png">

Maybe someone fixed it already?

**Comment by xpol** [comment]
Maybe Is Mac's bug?
The info shows green. but the App Icon is yellow. I tried reboot Mac, but not fix it.

![image](https://cloud.githubusercontent.com/assets/20248/13870801/d92f8380-ed19-11e5-993d-fda0a359455b.png)

**Comment by xpol** [comment]
Yes It is an Mac icon cache issue.

Fixed by follow commands: 

```bash
touch /Applications/Atom.app
touch /Applications/Atom.app/Contents/Info.plist
sudo find /private/var/folders/ -name com.apple.dock.iconcache -exec rm {} \;
sudo find /private/var/folders -name com.apple.iconservices -exec rm -rf {} \;
killall Dock
killall Finder
```

I'm not sure if the 1,2 lines or 3,4 lines fix it.

**Comment by lee-dohm** [comment]
Thanks for following up @xpol and I'm glad it is working for you now!
