### ISSUE TITLE
Split pane from fuzzy finder no longer opens new file in a new pane.

### ISSUE THREAD

**Issue by joseramonc** [atom/atom#11192]
### Steps to Reproduce

1. Toggle fuzzy finder and find the file you need to open in a new pane.
2. <kbd>cmd</kbd>+<kbd>k</kbd> <kbd>right</kbd> (or any arrow)

**Expected behavior:** 
In previous versions of atom a new pane in the desired position with the selected file in fuzzy finder would open.

**Actual behavior:** 
It doesn't do anything.

### Versions
OSX capitan.

apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.4.3

**Comment by lee-dohm** [comment]
Some time between when this was reported and now, this was fixed. Thanks for reporting!
