### ISSUE TITLE
Pending pane doesn't work

### ISSUE THREAD

**Issue by nRewik** [atom/atom#11209]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? -- Safe mode doesn't have tree view.
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
Pending pane doesn't show up when click at a file in tree view. (`Allow Pending Pane Items` is checked. )

### Steps to Reproduce
1. Click at a file in tree view

**Expected behavior:**
Pending pane show up when click at a file in tree view.

**Actual behavior:** [What actually happened]
Nothing happen, just a file name is highlighted.

### Versions
1.6.0

**Comment by thomasjo** [comment]
Safe has the tree-view package, because it's bundled with Atom. Try launching Atom in safe and loading some directory as a project. E.g. `atom --safe .` or `atom --safe ~/foo/bar/awesome-project` or some such.

Alternatively, after launching Atom in safe mode with `atom --safe`, go to the *File* menu and use the *Add Project Folder...* option.

**Comment by nRewik** [comment]
Found it. 

I try to disable installed packages one by one. It causes from the outdated `nuclide` package. After I disable nuclide, Pending pane works fine.

However, after I update and enable the latest nuclide. When I single click at a file, it opens a new tab instead of pending pane. Is this the behaviour of nuclide ?

**Comment by thomasjo** [comment]
> However, after I update and enable the latest nuclide. When I single click at a file, it opens a new tab instead of pending pane. Is this the behaviour of nuclide ?

If it doesn't happen in safe mode, and with nuclide disabled, then yes, seems like an unfortunate side effect of nuclide. Check if there's an open issue for it on the nuclide repository, or open an issue there.
