### ISSUE TITLE
Atom sidebar can only open one file

### ISSUE THREAD

**Issue by ripter** [atom/atom#11202]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
Clicking a file on the sidebar will only open a new tab if you have never clicked on a file before. Additional clicks will 'reuse' the existing tab instead of leaving the existing files open.

### Steps to Reproduce

1. Click on a file in the sidebar
2. Click another file in the sidebar

Video of bug: https://youtu.be/Je1lO-lIajI

**Expected behavior:**
Both files open in separate tabs

**Actual behavior:**
Only the last file clicked is open. The tab used from the last click is 'reused'.

### Versions
1.6.0

**Comment by demhydraz** [comment]
Not a bug, a feature (a particularly stupid one). Double click on files instead.

**Comment by ripter** [comment]
This was not in the change log and a search did not reveal any info on this behavior. Is it documented somewhere? I'd like to add it to this ticket to help others who are hindered by this change.

**Comment by demhydraz** [comment]
Yeah - they're called _Pending panes_ now (used to be _Preview tabs_) - you can disable it from the Core Settings page:
![](http://i.imgur.com/amzvwa2.jpg)

**Comment by mnquintana** [comment]
For future reference, this was announced in the most recent blog post for Atom 1.6 and 1.7: http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html

**Comment by The-Penultimate-Defenestrator** [comment]
This *just* started happening for me about 10 minutes ago. Before a single click would open a file as expected, now even with disabling the preference I have to double click... very annoying.

**Comment by The-Penultimate-Defenestrator** [comment]
Wait, never mind, I just decided I like it since the tabs solidify if you start typing.
