### ISSUE TITLE
Folder duplication in tree view when saving file with hotkeys ctrl+s

### ISSUE THREAD

**Issue by ponyesteves** [atom/atom#11208]
1. Editing a *.coffee file
![image](https://cloud.githubusercontent.com/assets/4960589/13899374/59a9e062-edcb-11e5-9449-e724086c3bec.png)

2. Ctrl - S to save modifications
3. Some folder duplicate in the tree view. 
![image](https://cloud.githubusercontent.com/assets/4960589/13899379/69a7dba4-edcb-11e5-9a41-4dd6e34302f9.png)

**Expected behavior:**  Save the active file

**Actual behavior:** Save the active file and duplicate folders in tree view

atom-version: 1.5.4  (but i've seen this behavior on earlier releases)
I reproduce it also in latest beta version, in both cases with atom --safe the problem persisted

apm --version 
![image](https://cloud.githubusercontent.com/assets/4960589/13899404/1351401e-edcc-11e5-9a83-fc4478cf8cca.png)

I'm running on ubuntu 14.04 
![image](https://cloud.githubusercontent.com/assets/4960589/13899408/2b9f936e-edcc-11e5-9394-e4edae436433.png)

If you need any additional info I'll be glad on attaching it.

thanks,

**Comment by ponyesteves** [comment]
I' ve found what causes the duplication. But don't know how to fix it.  Duplication occurs when the inject function of Gulp is triggered.   Any help?

``` js
gulp.task('injects', function () {
  var bfiles = []
  bowerFiles().forEach(function(file){
    bfiles.push('dist/vendor/' + file.match(/\/([\w,\-,\_]+\.(min.)?(?:js|css|jquery.js))/)[1])
  });
  var target = gulp.src('app/index.jade'),
    sources = gulp.src(['./dist/**/*.js','!./dist/vendor/*.js','!./dist/node_modules/**/*.js','./dist/styles/**/*.css'], {read: false});
  return target.pipe(inject(sources, {ignorePath: 'dist'}))
    .pipe(inject(gulp.src(bfiles, {read: false}), {name: 'bower', ignorePath: 'dist'}))
    .pipe(gulp.dest('app/'));
});
```

**Comment by 50Wliu** [comment]
@ponyesteves This only happens when you have the "Collapse Directories" option enabled and the issue is being tracked at atom/tree-view#705, so please subscribe there for updates.

**Comment by ponyesteves** [comment]
Thank  @50Wliu for you're reply! 
It's already fixed  but not merged yet! 
I'll suscribe to [atom/tree-view#705](https://github.com/atom/tree-view/issues/705)
