### ISSUE TITLE
Hitting an unbound key sequence sharing a prefix with a bound sequence freezes atom

### ISSUE THREAD

**Issue by dpavlic** [atom/atom#11203]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?

I am not sure if this issue fits here or over at https://github.com/atom/atom-keymap, apologies.

* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom freezes or crashes when a non-bound key binding shares the same prefix as a bound key binding.

### Steps to Reproduce

1. Create an example keybinding in your keymap file; (this is a trivial example; while they make Atom effectively non-functional, these types of bindings are, I expect, not so uncommon for us vim mode folk):

```
    'atom-text-editor':
      'space b d': 'tabs:close-tab'
```
 
2. Hitting space, b, d will delete the tab as expected.
3. Now: instead, hit space b y (or any other unbound key).

**Expected behavior:** Nothing happens.

**Actual behavior:** Atom freezes for an extended time.  Attempting this in safe mode crashes, otherwise it freezes and eventually shows a stack trace referenced in #6102.  However, this does not appear to be the same issue from what is being discussed there.  Development console in addition shows:

```
    Uncaught exception
        module.exports.KeymapManager.simulateTextInput @ (program):446
    Uncaught RangeError: Maximum call stack size exceeded
        /usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:459
```

### Versions

Affects 1.6.0 and 1.5.4.  Downgrading to 1.5.3 solves the issue.

**Comment by BinaryMuse** [comment]
Thanks for the report! A similar issue came up in the #atom Slack channel as well, I'll take a look at this soon.

**Comment by dpavlic** [comment]
An additional note: it seems to me that I need to have a bound / unbound shortcut of >=3 characters to trigger this.  Almost all of my prefixes, as a result of vim mode, start with space (space being a pseudo leader key): for example: `space g s` for git status. However, if I press space, followed by the next letter which has no bindings (e.g., I have nothing that starts with `space y`), then there is no problem.

**Comment by jessejanderson** [comment]
Man, this bug is brutal—apparently I press a lot of incorrect shortcut keys.

Having to force quit Atom several times a day in it's current state.

**Comment by dragonxlwang** [comment]
Thanks @dpavlic for pointing me to the correct place.

Hope this issue to get fixed soon as I am a sloppy typing guy

**Comment by BinaryMuse** [comment]
I haven't had a chance to dive into this deeply yet, but anecdotally, the three or four times I've heard this reported, the leader key has been the space key.

**Comment by calebmeyer** [comment]
@BinaryMuse I can confirm that this only happens with the space key as the leader key. I added
`', r t': 'rspec:run-for-line'` to my keymap.cson, then hit `comma r f` and atom did not crash.

**Comment by dpavlic** [comment]
@BinaryMuse Changing the leader seems to stop the behaviour on this end as well.  I'm going to remap the leader for now and test it out some more.

**Comment by dpavlic** [comment]
I was too hasty, remapping all the keys to the comma brings the problem back...

**Comment by dragonxlwang** [comment]
@dpavlic In my case I was using "," for leader key in vim-mode and I got this problem all the time after updating.

**Comment by jackcasey** [comment]
Hi, I've managed to write a failing spec in atom-keymap. See the issue referenced above.

**Comment by demhydraz** [comment]
Happening in 1.7.0-beta0 (Arch Linux). I'll report for beta2 as soon as it's done compiling.

**Comment by nathansobo** [comment]
This was caused by an unforeseen corner of @benogle's changes to support keyup events, which is used in MRU tabs. I'm looking into a quick solution, but keystroke matching needs a rethink.

**Comment by nathansobo** [comment]
Okay, I fixed at least one issue in [1.7.0-beta4](https://github.com/atom/atom/releases/tag/v1.7.0-beta4). Can folks give it a try and comment here if there are other cases I missed? Keymap matching code is reaching critical crazy.

**Comment by dpavlic** [comment]
All looks good so far on the 1.7.0-beta4.  Thank you nathansobo and jackcasey.

**Comment by jackcasey** [comment]
Yay! Thanks for the fix. All works for me. Will save me 10 sighs a day at least :)

**Comment by demhydraz** [comment]
Fixed here, too.
