### ISSUE TITLE
Git --wait stalls after initiating a commit (does not respond after saving commit message)

### ISSUE THREAD

**Issue by sammcq** [atom/atom#11207]
### Description
Git does not recover or submit commit after initiating atom via "git commit" in bash.  I write commit msg, ctrl+save commit, and and ctrl+w, ctrl+w to exit atom. Git in bash appears to be waiting for a stop to --wait, does not send commit.

### Steps to Reproduce

1. Modify atom.cmd file to recent modified version: https://github.com/atom/atom/commit/4d9e2b865b1f136bd1400eb3c67cb98dfc7571f2
2. type git commit into the git bash terminal.
3. write commit, ctrl+s, ctrl+w, ctrl+w .

**Expected behavior:** A commit to be made from atom, after initiating the commit from git bash

**Actual behavior:** git bash stalls and behaves as if it is waiting for a stop signal to the --wait command. 

NOTE: I can successful commit in atom by ctrl+shift+h and then selecting commit; I cannot initiate this process from the bash. 

### Versions
git version 2.7.4; atom version1.60 with modified atom.cmd (version 1.60 won't launch atom per other issue), windows 10

**Comment by damieng** [comment]
You'll need both the atom.cmd and atom.sh from resources\win in master if you are using bash not just the cmd

**Comment by MirPresT** [comment]
@damieng I've been trying to figure out what files to replace and am not sure where to locate the atom.cmd file and the atom.sh. On my computer I was able to locate users/name/AppData/Local/atom/ but from there I'm not sure where to go. Where do I find the atom.cmd file and the atom.sh within the atom folder on my computer that needs to be updated for this to work. 

Using git bash and atom 1.6.2

**Comment by damieng** [comment]
They are in the resources/cli folder
