### ISSUE TITLE
Atom 1.7.0 beta0 not opening from command line in portable mode Windows 7

### ISSUE THREAD

**Issue by Zooce** [atom/atom#11206]
I always open Atom from the command line, and today I updated Atom to 1.7.0 beta0 and now when I open a directory from the command line I get the following errors:

```
atom -n .
/e/devtools/atom/bin/../app-1.7.0-beta0/resources/cli/atom.cmd: line 1: @echo: command not found
/e/devtools/atom/bin/../app-1.7.0-beta0/resources/cli/atom.cmd: line 3: SET: command not found
/e/devtools/atom/bin/../app-1.7.0-beta0/resources/cli/atom.cmd: line 4: SET: command not found
/e/devtools/atom/bin/../app-1.7.0-beta0/resources/cli/atom.cmd: line 6: syntax error near unexpected token `('
/e/devtools/atom/bin/../app-1.7.0-beta0/resources/cli/atom.cmd: line 6: `FOR %%a IN (%*) DO ('
```

I can successfully open Atom manually or through the Explorer context menus.

Windows 7 x64
Atom 1.7.0 beta0
apm  1.8.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 1.9.5.msysgit.0
visual studio 2012

**Comment by Ben3eeE** [comment]
Same error as https://github.com/atom/atom/issues/11164#issuecomment-199409185 ?

**Comment by Zooce** [comment]
@Ben3eeE Yea, same error. I'll close this as a duplicate. Thanks!
