### ISSUE TITLE
(updating Atom 1.5.4 --> 1.6.0) After pressing 'Help|Update and Restart' Atom didn't restart

### ISSUE THREAD

**Issue by darkred** [atom/atom#11210]
_Initially having Atom 1.5.4 stable in win10 6x4._
Today after launching Atom I noticed in Atom's statusbar that update 1.6.0 was available.
So, I pressed `Help|Update and Restart` but Atom didn't restart by itself: I had to manually launch it.

There was no relevant entry in windows Event Viewer (i.e. "Atom crashed" or something like that)

**Comment by 50Wliu** [comment]
@darkred there have been many improvements made to the auto-updating process in Atom 1.7.0, so I'm going to close this out.  If it still happens when updating from 1.7.0 to a new version, please comment here!

**Comment by darkred** [comment]
@50Wliu The same happened again just now, while updating Atom 1.8.0 --> 1.9.2

**Comment by pcnate** [comment]
Same thing happening going from 1.9.1 --> 1.9.2
