### ISSUE TITLE
Version not updating in bin

### ISSUE THREAD

**Issue by danieldevine** [atom/atom#11217]
Version: 1.6.0
OS: Windows 10
Try to run atom from command line, get following error:

```
/c/Users/XXX/AppData/Local/atom/bin/atom: line 2: /c/Users/XXX/AppData/Local/atom/bin/../app-1.5.3/resources/cli/atom.sh: No such file or directory
```

( temporarly ) fixed by manually updating version to 1.6.0 in line 2 of /c/Users/XXX/AppData/Local/atom/bin/atom

similar issue and fix for apm in the same directory.

Atom installed using Windows installer and updated in-app.

**Comment by damieng** [comment]
If you still have the squirrelsetup.log file available please post it here so we can see what happened.

**Comment by danieldevine** [comment]
@damieng Sure, log attached. 

[SquirrelSetup.txt](https://github.com/atom/atom/files/201004/SquirrelSetup.txt)

**Comment by damieng** [comment]
Hmm, there's no reference in there whatsoever to the resources\bin folder or its contents...

**Comment by paulcbetts** [comment]
I'm not 100% sure this is an installer / updater issue, is Cygwin supported in atom.sh?

**Comment by damieng** [comment]
atom.sh does work in cygwin - the problem here and in a number of other issue seems that the resources\bin folder is not always being installed/upgraded.

**Comment by damieng** [comment]
Just tried latest 1.6 installer from the site and it created the bin folder
with the contents correctly but also doesn't log that it created them in
the installer. Will need to further investigate.

**Comment by damieng** [comment]
Tracking this bug in https://github.com/atom/atom/issues/11450to combine multiple issues
