### ISSUE TITLE
preview tab should stay open

### ISSUE THREAD

**Issue by loganfreeman** [atom/atom#11223]
It is the current behavior that single click will open a preview tab, and double click will open a permanent tab. 

While this makes sense, it would be more appropriate if it is configurable. For example, I want the preview tab stay open while switching to a new one. I don't care opening a lot of tabs. switching between single click and double click is not intuitive to me. 

### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [ ] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

**Comment by lee-dohm** [comment]
It is configurable. Uncheck "Allow Pending Pane Items":

<img width="741" alt="screen shot 2016-03-20 at 10 32 45 pm" src="https://cloud.githubusercontent.com/assets/1038121/13911285/b8e6b8f4-eeeb-11e5-9305-2fb8e19dda0e.png">

**Comment by loganfreeman** [comment]
Thanks. Great
