### ISSUE TITLE
Rename filename from tab

### ISSUE THREAD

**Issue by grenzor** [atom/atom#11226]
Currently, atom cannot rename filenames via the filename tab - should be added. Very useful and quick way to do so.

**Comment by grenzor** [comment]
As far as I can see that merge was for renaming from treeview not the actual file tab, which is not able to renamed from.

**Comment by Ben3eeE** [comment]
That PR was for adding the `tree-view` rename file to the tabs context menu. If this is not what you were asking for then please open a new issue and completely fill out the provided template.

![image](https://cloud.githubusercontent.com/assets/1058982/19418136/3a591068-93be-11e6-9304-d3f55345b1a9.png)
