### ISSUE TITLE
Move line/block UP injects empty line unexpectedly

### ISSUE THREAD

**Issue by celloworld** [atom/atom#11233]
Atom 1.5.3

I press [cmd + L] to select an entire line, then I use [cmd + ctrl + up/down] to move that line relative to others. When moving a line upward, an empty line is _injected_ in place of the current line.

![move-block-bug](https://cloud.githubusercontent.com/assets/3270144/13933250/c7c9b78c-ef71-11e5-96d4-250fa58d8c09.gif)

**Comment by ZombieHippie** [comment]
@c43 Would you post exactly which command that keybinding evaluates to using the keybinding resolver? Thank you.

**Comment by c43** [comment]
![screen shot 2016-03-29 at 9 15 59 am](https://cloud.githubusercontent.com/assets/3270144/14113160/f738e4ac-f58e-11e5-8580-16296fec7cb9.png)

**Comment by ZombieHippie** [comment]
Thank you c43

**Comment by mnquintana** [comment]
I can't reproduce this in 1.8.0-dev-435dcc7 – can you try updating to the latest version of Atom? (1.6.0) If you still experience this issue, can you then try quitting Atom completely and restarting it in safe mode? (`atom --safe`)

**Comment by c43** [comment]
The bug persists after I updated atom (1.6.2) and launched in safe mode, BUT appears to be isolated to that specific document (the one shown in the gif above). When I created a new doc and copied everything over the misbehavior was corrected. Your call, guys. And thanks for the support.

**Comment by ZombieHippie** [comment]
I wonder if this is a Windows newline and carriage return glitch.

**Comment by mxmlnkn** [comment]
@ZombieHippie I tried

    printf "hi\r\nthere\r\n.\r\n" > dos.txt
    atom dos.txt

And then on the line with `.` pressing Ctrl+up which moves the line up, but doesn't inject any empty line for me (atom 1.8.0).
