### ISSUE TITLE
Atom 1.6.0 Autocomplete fails on El Capitan

### ISSUE THREAD

**Issue by t0dd** [atom/atom#11230]
I just installed Atom 1.6.0 on my iMac running OSX El Capitan (10.11.3). Autocomplete will pop-up with options as expected, however when I hit the 'tab' or 'enter' keys it does not complete the code, and the autocomplete window goes away with the cursor right where I left it. This is a clean install, I have not added any packages or changed any config settings. The same problem occurs in safe mode.  I've only tried this while working in HTML, CSS, and JavaScript.

**Comment by 50Wliu** [comment]
Hey @t0dd, sorry for the late response.  Can you please move this to the [autocomplete-plus](https://github.com/atom/autocomplete-plus) repository?  Thanks!
