### ISSUE TITLE
Install Packages does not work on Windows

### ISSUE THREAD

**Issue by gitcnd** [atom/atom#11235]
### Description

Install fails. You should test your stuff on a normal persons computer, not your dev workstation, to ensure your stuff isn't depending on whatever dev bloatware you've got installed.

### Steps to Reproduce

1. Install atom on windows
2. Install vim-mode
3. observe it fails

**Expected behavior:**

Should install, and activate (or tell me if I have to do something to use it)

**Actual behavior:** 

Installing “vim-mode@0.65.0” failed.Hide output…

npm ERR! tar.unpack error reading C:\Users\cnd\.atom\.apm\grim\0.12.0\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\cnd\\AppData\\Local\\atom\\app-1.6.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\cnd\\AppData\\Local\\atom\\app-1.6.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\cnd\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\cnd\\.atom\\.apmrc" "install" "C:\\Users\\cnd\\AppData\\Local\\Temp\\d-116222-1212-1uurtb5\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code EBADF
npm ERR! errno 9

npm ERR! EBADF, fstat
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

### Versions

1.6.0

**Comment by yangDL** [comment]
I can`t install the atom~. When I install AtomSetup.exe , it say : Does not support the 64 bit

**Comment by zhangnian** [comment]
the  lastest install package does n;t work on windows 10 x64. I download the package from the website:  http://atom.io。

**Comment by damieng** [comment]
@gitcnd: Are you getting this error with any other packages or just vim-mode? 

@yangDL and @zhangnian The download has been tested on Windows 10 64-bit and I just tried it again without error. Can you take a screenshot of the exact error?

**Comment by damieng** [comment]
No response. Please re-open if you are still getting this error.
