### ISSUE TITLE
Files opened from the file tree behave the same as #11007

### ISSUE THREAD

**Issue by bimsonz** [atom/atom#11237]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [Open blank or current project]
2. [Click any file in tree]
3. [It will open in italics as mentioned in #11007]
4. [click any other file and it will replace the previous file]

**Expected behavior:** [The new file to open as well as the previous file]

**Actual behavior:** [Files replaces]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

**Comment by Ben3eeE** [comment]
This is intended behavior with the pending tabs introduced in atom 1.6.0
- Single click will open the file as pending (in italics).
- Double click will open the file normally as pre 1.6.0 (non italics).

If you wish to revert to the old behavior there is a core setting: "Allow pending pane items" accessible from the settings view.

**Comment by bimsonz** [comment]
Thank you SO much for this! 

I was right in the middle of something really important when it updated and this was driving me crazzzzzy!

Sorry for the bug report but wasn't sure how else to fix.
