### ISSUE TITLE
Crashing when opening a file via OSXfuse mounted drive

### ISSUE THREAD

**Issue by bajere** [atom/atom#11238]
Tested in OSX 10.11.1 with;
- Atom Beta
- Atom 1.6.0

Any OSXfuse mounted drive holding a `.git` file will crash when opened. Removing/renaming `.git` will allow Atom to work as intended.

I have also tried to disable anything git related in the Atom Packages, still not working.

**Comment by tshazar** [comment]
I am also having the same trouble with OSX smb/cifs shares as well.

**Comment by dborsatto** [comment]
This is probably related to https://github.com/atom/atom/issues/11214 .

**Comment by damieng** [comment]
Believed to be fixed in 1.8 as part of https://github.com/atom/atom/issues/11214. Please re-open if not.
