### ISSUE TITLE
Softwrap unindents, drops the line

### ISSUE THREAD

**Issue by cameronmcefee** [atom/atom#1124]
Lines 6 and 7 are soft wrapped, which is forcing them down a line and lines them up with the left side, regardless of indent depth.

![screen shot 2013-11-18 at 5 03 40 pm](https://f.cloud.github.com/assets/72919/1568699/722fd790-50b6-11e3-9dc1-a0a8b69d5aa2.png)

**Comment by thomasjo** [comment]
Unless I'm mistaken, this is no longer an issue. Re-open if I'm wrong.
