### ISSUE TITLE
Error: Cannot find module 'undefined' on Updates screen

### ISSUE THREAD

**Issue by awayken** [atom/atom#11242]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When browsing the Updates section of the Settings tab, I get an error message. This error isn't 100% consistent, and it appears more consistently the first time I load the Updates section of the Settings tab. Sometimes, it also appears when I click the "Check for Updates" button.

Message: Fetching outdated packages and themes failed.
More output:
```bash
npm
module.js:340
    throw err;
          ^
Error: Cannot find module 'undefined'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at cb (C:\Users\mrausch\AppData\Local\atom\app-1.6.0\resources\app\apm\node_modules\npm\lib\npm.js:286:7)
    at C:\Users\mrausch\AppData\Local\atom\app-1.6.0\resources\app\apm\node_modules\npm\lib\npm.js:375:14
    at C:\Users\mrausch\AppData\Local\atom\app-1.6.0\resources\app\apm\node_modules\npm\lib\config\core.js:82:7
    at Array.forEach (native)
    at C:\Users\mrausch\AppData\Local\atom\app-1.6.0\resources\app\apm\node_modules\npm\lib\config\core.js:81:13
    at f (C:\Users\mrausch\AppData\Local\atom\app-1.6.0\resources\app\apm\node_modules\npm\node_modules\once\once.js:17:25)
```

### Steps to Reproduce

1. Open Settings tab
2. Click on "Updates"
3. It will do an initial "Check for Updates"

**Expected behavior:** Check for package and theme updates.

**Actual behavior:** Displays an error message.

### Versions

Atom 1.6.0

apm  1.6.0
npm  2.13.3 (This is not what I'm actually running. See below.)
node 0.10.40 (This is not what I'm actually running. See below.)
python 2.7.11
git 2.7.0.windows.1
visual studio

Node v4.4.0
npm 3.7.2

**Comment by ZombieHippie** [comment]
@awayken Thank you for the thorough report.

**Comment by awayken** [comment]
@ZombieHippie Any insight into what might be going on? Is there any additional info I can provide?

**Comment by ZombieHippie** [comment]
@awayken here is our first clue, which is the require which is undefined: https://github.com/npm/npm/blob/v2.13.3/lib/npm.js#L286

We can do more investigating where this onload script is.

**Comment by awayken** [comment]
I don't seem to be getting this error any longer. I'm going to close this issue unless I start to see the issue pop up again.
