### ISSUE TITLE
Sometimes opening a file, Atom does not open in a new tab

### ISSUE THREAD

**Issue by Kungfoowiz** [atom/atom#11243]
Sometimes when opening a file in Atom, it does not open the file in a new tab.
Instead, the file is opened over the current file that was opened. Please see screenshot with explanation.

![opening more than window sometimes does not open in a new tab](https://cloud.githubusercontent.com/assets/17824719/13960524/953a9d88-f050-11e5-8de8-5c25701c4372.jpg)

### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [ ] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)? Yes
* [ ] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Sometimes when opening a file in Atom, it does not open the file in a new tab.
Instead, the file is opened over the current file that was opened. Please see screenshot with explanation.

### Steps to Reproduce

1. Open a file in Atom.
2. Quickly close the file, I used Ctrl + W shortcut to close.
3. Very quickly, click another file.

OR

1. Open a file in Atom.
2. Quickly close the file, I used Ctrl + W shortcut to close.
3. I clicked away to another window.
4. Came back into Atom and opened the same file.
5. Then I clicked another file.

**Expected behavior:** [What you expected to happen]

Clicked files should always open in a new tab, this is the normal behaviour.

**Actual behavior:** [What actually happened]

The file clicked the second time, does not open in a new tab. Instead it opens in place of the current file which was opened.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

1.6.0

**Comment by mnquintana** [comment]
This feature is called Pending Pane Items (formerly known as Preview Tabs) – this allows you to quickly preview many files without committing to opening them. You can disable this setting by going to Settings > Core Settings > Allow Pending Pane Items and disabling it.

![image](https://cloud.githubusercontent.com/assets/823545/13963789/00bb8fcc-f024-11e5-8ab5-917dfe56743f.png)

Sorry for the confusion!

**Comment by Kungfoowiz** [comment]
Thank you for the update, I appreciate your reply =)

**Comment by jtkiley** [comment]
+1 for changing the default to disabled.

**Comment by wranvaud** [comment]
This feature is great and I will start to use it now but disabe by default please beacause in the heat of the action when you actually just want some code commited this looks like a nasty bug

**Comment by laszlof** [comment]
+1 for disable by default. I updated recently (was quite out of date) and was curious as to why all the sudden I could only open 1 tab. Its annoying when you expect one behaviour, and get something completely different.

**Comment by nikhilc89** [comment]
Was just finding this after I ran into the issue following an update.
Possible to have the previous config of opening files with just 1 click as well? Now it takes a double click to open files after disabling 'Allow Pending Pane Items'.
If 'Allow Pending Pane Items' is enabled, you can double click and keep the file open there as well.

**Comment by 50Wliu** [comment]
> Possible to have the previous config of opening files with just 1 click as well?

Check out the [single-click-open](https://atom.io/packages/single-click-open) package.

**Comment by nikhilc89** [comment]
> Check out the single-click-open package.
Perfect. Works like a charm.

**Comment by twoelevenjay** [comment]
@mnquintana, don't apologize for the confusion, the confusion was well worth it, this feature is AWESOME!!! Thanks to @Kungfoowiz, for having this pre-answered for me.

**Comment by siso** [comment]
this feature is pretty cool, at least once you are aware of it ;)

**Comment by sur** [comment]
thanks @mnquintana
really after knowing this as a feature, I am now able to use it and it's actually a beautiful feature.

**Comment by KingJavaJava** [comment]
Just noticed it too

**Comment by DonkeyAfterDark** [comment]
Who TF decided this was a good idea?

**Comment by dpanter** [comment]
+1 Pending Pane disabled by default because OMFG this "feature" was driving me insane on a new install. Having to add a plugin (single-click-open) to restore function is simply put madness.

**Comment by hackerwin7** [comment]
Is the difference between opened tab and pending tab is that pending tab's title is italics in a view? I think it's sometimes tricky, hard to find that ...

**Comment by kaumac** [comment]
`Who TF decided this was a good idea?`
My thoughts exactly... I also installed a plugin to disable this extremely annoying `feature`.

**Comment by ssbarnea** [comment]
I do really agree that this feature is in fact a bug. If so many people complain about this behavior, something must be wrong. Better to have such "too-smart" feature disabled by default instead of causing annoyance and confusion to users.

**Comment by hulkco** [comment]
Just Double Clic on each file

**Comment by jedwards1211** [comment]
Does anyone else find it annoying having to double-click?

**Comment by Babeetlebum** [comment]
Double clicking a file from the "Project Find Results" (ctrl+shift+F) would still open the file in preview mode, I have to pass on this feature because of this

Also ctrl-click would be more convenient than double-click imo

**Comment by DarrenZhang01** [comment]
It would be a plus if I disable "allow pending pane items" option, then single clicking rather than double clicking will open the user a new pane. At the same time, thanks for your hard work!

**Comment by syntaxErrorForbearer** [comment]
> [This feature is called Pending Pane Items (formerly known as Preview Tabs)](http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html) – this allows you to quickly preview many files without committing to opening them. You can disable this setting by going to Settings > Core Settings > Allow Pending Pane Items and disabling it.
> 
> ![image](https://cloud.githubusercontent.com/assets/823545/13963789/00bb8fcc-f024-11e5-8ab5-917dfe56743f.png)
> 
> You can also confirm a pending item by double-clicking on the tab, double-clicking on the file you want to open from the Tree View, right-clicking the tab you want to keep and clicking Keep Pending Tab, or selecting `Tabs: Keep Pending Tab` from the Command Palette.
> 
> Sorry for the confusion!



> [This feature is called Pending Pane Items (formerly known as Preview Tabs)](http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html) – this allows you to quickly preview many files without committing to opening them. You can disable this setting by going to Settings > Core Settings > Allow Pending Pane Items and disabling it.
> 
> ![image](https://cloud.githubusercontent.com/assets/823545/13963789/00bb8fcc-f024-11e5-8ab5-917dfe56743f.png)
> 
> You can also confirm a pending item by double-clicking on the tab, double-clicking on the file you want to open from the Tree View, right-clicking the tab you want to keep and clicking Keep Pending Tab, or selecting `Tabs: Keep Pending Tab` from the Command Palette.
> 
> Sorry for the confusion!

I was experiencing a similar problem, but in fact it was being caused by a popular package called 'zentabs'. Once I reached a limit of 5 tabs, every following tab would begin to close others unless they had been modified but not saved.

**Comment by syntaxErrorForbearer** [comment]
I was experiencing a similar problem, but in fact it was being caused by a popular package called 'zentabs'. Once I reached a limit of 5 tabs, every following tab would begin to close others unless they had been modified but not saved.

**Comment by colmsnowplow** [comment]
I really don't get the negative reaction to this - it's a very useful feature in navigating large or complex projects, especially wrt reading code from input -> output. 

My one suggestion is that it would be awesome to have a keyboard shortcut to keep pending tab for current tab. That combined w/the ability to pin a note to the tab would be super powerful (as in, a 'reminder' note for the current work session, eg. 'transformation function X is defined here'.

**Comment by jouellnyc** [comment]
> > Check out the single-click-open package.
> 
> Perfect. Works like a charm.

Indeed. Genius package!

For the newer Atom user  wondering...
"Open Atom, go to edit > preferences > install and search for the package you wish to install."

Took me a few minutes. I just got hooked on Atom a few weeks ago.

**Comment by rotemrevivo91** [comment]
just disable this crap already

**Comment by Coreusa** [comment]
The issue may also related to any package you might've recently installed. This was the matter in our case.

Thanks to stackoverflow: Have a look at your recently installed packages in ~/.atom/packages, sort by recently updated and disable anything you've installed recently.

**Comment by Gkiokan** [comment]
> > Possible to have the previous config of opening files with just 1 click as well?
> 
> Check out the [single-click-open](https://atom.io/packages/single-click-open) package.

This is what you need. Makes this whole feature more usable. Still a thing in 2022.
