### ISSUE TITLE
atom opens only two files

### ISSUE THREAD

**Issue by aleritty** [atom/atom#11244]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? yes
* [X] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)? yes
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

After latest update atom opens only two files at time.
I can have two files in two tabs, when I click on a third it will open replacing the last (rightmost) tab.
I can have three tabs open if one is settings tab.

### Steps to Reproduce

1. Click on a file (in the current working folder)
2. Click on a second file
3. click on a third one
4. the third file will open replacing the second one tab

**Expected behavior:** [What you expected to happen]

I used to open more than two tabs

**Actual behavior:** [What actually happened]

### Versions
atom 1.6.0

apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.0

**Comment by mnquintana** [comment]
See https://github.com/atom/atom/issues/11243#issuecomment-199959295
