### ISSUE TITLE
Hide atom-overlay when not visible

### ISSUE THREAD

**Issue by simurai** [atom/atom#11249]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

This issue came up [here](https://github.com/atom/one-dark-ui/pull/127).

Currently `atom-overlay`s overlap the rest of the UI. I think it's ok, but only as long as the current line is visible. If you scroll it "out of sight", it looks odd having the overlay still be shown.

A possible solution might be to try to detect when the current line is not visible and then hide the `atom-overlay`. I think autocomplete kinda already tries to do that by jumping to the top when scrolling down, but doesn't hide completely. And would be nice if it's part of the core behavior, so all packages would get it. Maybe with an option to opt-out if a package wants stay visible all the time.
### Steps to Reproduce
1. Open find + replace `cmd-f`
2. Have autocomplete enabled and type something to open the autocomplete overlay.
3. Scroll down until the current line is underneath the find + replace panel

**Expected behavior:**

The autocomplete overlay should disappear

![overlay](https://cloud.githubusercontent.com/assets/378023/13974127/810694a6-f0ec-11e5-897b-f80c7d7fbb52.gif)

**Actual behavior:**

It stays on top of the find + replace panel, even tough you can't see the current line anymore

![screen shot 2016-03-23 at 11 47 53 am](https://cloud.githubusercontent.com/assets/378023/13974215/2793be34-f0ed-11e5-8209-8bd9754f4e6a.png)
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

```
Atom    : 1.8.0-dev-64308bb
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.1
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.3
```

**Comment by steelbrain** [comment]
Related https://github.com/atom/atom/pull/11187

**Comment by ungb** [comment]
I can still repro this on

```
Atom    : 1.21.0-dev-5c41c665c
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

Adding help wanted as I don't think we'll be able to get to this any time soon.

**Comment by webdevdaemon** [comment]
I am looking to make this or another issue here @ atom/atom my first PR. I have contributed to eslint before, but it was for their docs... I am pretty capable though, new to open source, but not new to coding...

Should I give this one a try? Or is their another issue that comes to mind? 

I want to help Atom specifically because I use it so much that it just makes sense to give back. If this issue is a go for me to work on, ANY leads on where to begin would be appreciated. 

Thanks in advance,
- Charles
