### ISSUE TITLE
Power saving mode?

### ISSUE THREAD

**Issue by ZakariaRidouh** [atom/atom#11259]
I wanted to ask if a power saving mode for Atom is on the roadmap for future releases. 
Power saving mode would turn off many battery intensive feature like background update checks, package update checks, animations and more for the time while it is on.

This would be very helpful if you are running out of battery and really want to squeeze that last extra juice out of your battery and finish writing your code etc.

Thank you all so very much
Cheers!

**Comment by lee-dohm** [comment]
Most of our power-saving work has been around making Atom battery-friendly when not in the foreground. We generally assume that if Atom is in the foreground, then you want Atom to work like it always does. Also, what will typically save battery more than most things Atom could do are things like:

* Spin down hard drives (if still using platter technology)
* Turn off WiFi (which would solve the update checks)
* Turn down the backlight on your screen

With that said, if there is anything that you see that is anomalous or you have specific suggestions around ways that Atom can save battery, please file an Issue! We'd love to hear about it. (And I'd especially interested. I spent a few years working on power and thermal measurement for mobile devices, so it is a passion of mine.)

I hope that helps answer your question! Let me know if you have any others.
