### ISSUE TITLE
Atom does not use multiple tabs anymore

### ISSUE THREAD

**Issue by BlaM** [atom/atom#11253]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom just updated to v1.6.0 - and now it won't open multiple files in multiple tabs anymore.

### Steps to Reproduce

1. Start Atom and Open a folder with multiple files.
2. Open a File by clicking on it in the file browser.
3. Open another file by clicking on it in the file browser.

**Expected behavior:** The window should have two tabs with two open files.

**Actual behavior:** After the first click a tab is opened. The tab header is showing the filename in italics. When I click on another file the tab is replaced by the second file. It won't open a second tab anymore.

### Versions

1.6.0

**Comment by Ben3eeE** [comment]
This is intended behavior in atom 1.6.0 called pending pane items.
See https://github.com/atom/atom/issues/11243#issuecomment-199959295

**Comment by BlaM** [comment]
Okay, just found these "closed" issues #11202, #11243, #11237 - this seems to be an unexpected and rather annoying feature of the latest version.

**Comment by BlaM** [comment]
This should be disabled by default as it is a rather unexpected behaviour.
