### ISSUE TITLE
The context of the "Default encoding" should be "new files" with another setting for opening files.

### ISSUE THREAD

**Issue by fnurl** [atom/atom#11255]
There are several issues and comments regarding encoding behavior (atom: #4141, #4160, #10052, #10939, encoding-selector: https://github.com/atom/encoding-selector/issues/8, https://github.com/atom/encoding-selector/issues/24) in Atom, but they all seem to miss the mark.

I imagine that everybody would agree on the following use cases:
1. When the user opens a file, it is opened with the correct encoding.
2. When the user creates a new file and saves it, it is saved with the correct encoding.

These are two separate use cases. "auto-detect" encoding is not applicable to creating new files. I am not familiar with the dependencies and relation between core and encoding-selector (I don't know if encoding-selector can intercept an "open file"?), but here is a possible solution from a use case perspective:
- For opening files, **always** try to auto-detect encoding.
- The user sets his or her **preferred encoding**. The preferred encoding is used when creating **new files**.
- The user sets a **fallback encoding**. Fallback encoding is used when **Opening a file** and **auto-detect fails**.

Using the term _"default encoding"_ is bad in this case since it is ambiguous.

_Edit 2016-05-10_: Suggestions for more clear terms are:
- "default encoding for new files" (a bit long)
- "new file encoding"
- "encoding for new files"
- "default new file encoding"

**Comment by filippo-basso** [comment]
Well, I tried Atom, as there is a lot of publicity and "image" around it. 
It's a nice editor, and I like to be able to hack it.

But this morning, opening an UTF-16 file, I got quite disappointed. 
With **Sublime** or even the standard **TextEdit** from OSX I can read normally UTF-16 files, while in **Atom** I had to see strange characters �����, worry, compare with other editors (all working okay on this issue), surf in Google for 15 minutes, before understanding that I've to go to` Edit->SelectEncoding->AutoDetect` ... seems VERY ugly and annoying for 99% of the users.

Please try to find a way to solve this behavior.

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/10252 also mentions fallback encoding.
