### ISSUE TITLE
Could not connect to indexedDB

### ISSUE THREAD

**Issue by joefitzgerald** [atom/atom#11254]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

state-store doesn't work because IndexedDB can't open a connection.

### Steps to Reproduce

Unsure of reproduction steps.

**Expected behavior:** No errors

**Actual behavior:** Errors every few seconds while any editor is open.

![screen shot 2016-03-23 at 7 46 50 am](https://cloud.githubusercontent.com/assets/744740/13987168/e7a199de-f0cb-11e5-9698-54929d43d46c.png)

![screen shot 2016-03-23 at 7 47 35 am](https://cloud.githubusercontent.com/assets/744740/13987174/eb9e4eb0-f0cb-11e5-8e37-ec4d6c1ef2f6.png)

### Versions

1.7.0-beta0, master

**Comment by joefitzgerald** [comment]
The fix for me was: `rm -rf "/Users/jfitzgerald/Library/Application Support/Atom/IndexedDB"`.

**Comment by t9md** [comment]
@joefitzgerald Thanks, me too fixed by your instruction.

**Comment by Ben3eeE** [comment]
Ran in to this today after update to Atom 1.10.1
Seems I had stray `atom.exe` processes running in task manager, closing all those and starting Atom again restored state properly to what it was before the update.

**Comment by Fresheyeball** [comment]
@joefitzgerald would you mind pointing me to the location of that file on linux?

**Comment by comerc** [comment]
@Fresheyeball ~/.config/Atom/IndexedDB
