### ISSUE TITLE
Atom 1.6 opens wrong computer's windows

### ISSUE THREAD

**Issue by ksnyde** [atom/atom#11260]
I use Atom on my laptop and home computer and since installing 1.6 I now always have my laptop folders trying to load when I open Atom on my home computer. No other changes were made (to my knowledge).

### Prerequisites

* none

### Description

Starting Atom opens previous windows but with desktop this now the previous windows from my laptop (which has a completely separate paths to projects). 

### Steps to Reproduce

1. Start Atom on computer 1
2. Start Atom on computer 2

### Versions

     atom 1.6.0
     apm  1.6.0
     npm  2.13.3
     node 0.10.40
     python 2.7.11
     git 2.6.4

**Comment by mehcode** [comment]
@ksnyde What packages do you have? And do you use [sync settings](https://github.com/atom-community/sync-settings)? This sounds like that in combination with [open last project](https://atom.io/packages/open-last-project).

---

Does this problem occur when running atom via `atom --safe` ?

**Comment by ksnyde** [comment]
No it doesn't and after I ran it with safe turned on I tried it without and the problem appears to have gone away. Does that make sense?

**Comment by mehcode** [comment]
Are you perhaps syncing your `~/.atom` directory between the two computers? There is a file in there `~/.atom/storage/application.json` that remembers that paths that were open in the previous session. I assume that could cause a problem if `~/.atom` is shared between two computers.

---

As for `atom --safe` fixing it afterwords.. what I say above makes even more sense now. As your previous session is now the empty one with no folders.

**Comment by ksnyde** [comment]
Ahhh, yes. I have atom pointing to Dropbox and both computers work off that. Is that a bad idea?

**Comment by ksnyde** [comment]
Either way, sounds like I should close this issue.

**Comment by mehcode** [comment]
> Ahhh, yes. I have .atom pointing to Dropbox and both computers work off that. Is that a bad idea?

I'd say yes. As there is at least one thing that causes issues (the application.json file in `~/.atom/storage`). I'd recommend instead to use the https://github.com/atom-community/sync-settings package to synchronize configuration between computers.

**Comment by ksnyde** [comment]
ok, thanks
