### ISSUE TITLE
Error when installing packages

### ISSUE THREAD

**Issue by sharkoman** [atom/atom#11261]
I installed nodeJS 5 with npm 3.8.0
when i'm trying to install any package a red box with "installing faild" message appair
i tried reinstall atom and nothing happend 
this is the output when i tried to install emmet package:
-------------

`npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\SHERIF\\AppData\\Local\\atom\\app-1.6.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\SHERIF\\AppData\\Local\\atom\\app-1.6.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\SHERIF\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\SHERIF\\.atom\\.apmrc" "install" "C:\\Users\\SHERIF\\AppData\\Local\\Temp\\d-116224-3176-194om9u\\package.tgz" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Users\SHERIF\.atom\.apm\d\0.1.1\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\SHERIF\.atom\.apm\d\0.1.1\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse`

------

**Comment by sharkoman** [comment]
any help here ?

**Comment by jphillips05** [comment]
Having the same issue. The only way I could get around this is by copying the package.json from .atom/.npm/{whatever} to .atom/.apm/{whatever}. So I tried to install typescript and the first error was the module number-is-nan. I had to copy .atom\.npm\number-is-nan\1.0.0\package\package.json to .atom\.apm\number-is-nan\1.0.0\package\package.json and so on. It's tedious but ended up working for the in the end.
