### ISSUE TITLE
Cpp bracket folding problem with directive(s)

### ISSUE THREAD

**Issue by ardhipoetra** [atom/atom#11264]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](https://atom.io/docs/latest/hacking-atom-debugging#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Perhaps still related to #8724 or #11179. It seems the folding brackets in atom still not perfect yet. I have .cpp code : 

```c++
void send_request(int seq, char* a, int i)
{
	if (seq >= 0) a["seq"] = seq;
	int size = bencode(msg_buf, e);
#if defined DEBUG && IOSTREAM
	std::cerr << "sending: " <<  e << "\n";
#endif

	if (i == g_sent_packets.end())
	{
		TEST_ERROR("not responding");
		return;
	}

	g_sent_packets.erase(i);
}
```
Folding the if statement and #if directive is correct (or at least what I really expected). But folding the class is wrong.

Below is the screenshot of after-folding code
![screenshot from 2016-03-24 17 51 25](https://cloud.githubusercontent.com/assets/2739025/14024369/09e070a6-f1e9-11e5-96bb-02754032ebb7.png)

I'm not sure if this happened because I put the directive inside the function. Some other function without directives just fold fine.

### Steps to Reproduce

1. Open Atom (both in safe mode or not still produces same bug)
2. Open the file
3. Fold line 2
4. Bug happens

**Expected behavior:** [What you expected to happen]
The folding should cover line 2-16

**Actual behavior:** [What actually happened]
The folding only covers line 2-5

### Versions
1.6.0

**Comment by 50Wliu** [comment]
Folding is currently solely indentation-based, hence why your example is failing.  Please see #3442 for more details.
