### ISSUE TITLE
Atom crashes when attempting to step into Atom code without the Atom source repository available

### ISSUE THREAD

**Issue by International** [atom/atom#11269]
### Description

Atom crashes when setting breakpoints in my package.
### Steps to Reproduce
1. Set breakpoint in package code, wait for it to be hit
2. Step in or over the code
3. Atom crashes

**Expected behavior:** 
I expect atom to allow me to step through the code and be able to debug it.

**Actual behavior:**
Atom crashes every time.
### Versions

1.6.0
### Temporary fix

I've discussed the issue [here](https://discuss.atom.io/t/setting-breakpoints-crashes-atom/27060) , and @lee-dohm suggested I clone the atom repo in `~/github/atom`. After doing that, I'm able to use breakpoints without atom crashing.

**Comment by lee-dohm** [comment]
I updated the title to be more indicative of the problem we really saw. I also am not sure "Atom crashes every time" is accurate, but I decided to leave that alone for now.

@zcbenz, my theory is that this is a problem with the debugger not being able to read the source out of the `app.asar` and crashing. Is that reasonable? If so, is this an Electron issue?

**Comment by International** [comment]
Update: I actually needed to do some debugging today, and this time it went a bit different. Breakpoint hit, atom stopped, and then the window got darker ( as if blocked ), and then crashed. I've attached a screenshot of ubuntu's crash report, maybe it will help. 
![atom-crash](https://cloud.githubusercontent.com/assets/1022918/14041302/c4e7c076-f26f-11e5-9534-f3ba04458de4.png)

**Comment by International** [comment]
I've tried also to remove atom from ~/github and see if this fixes running the tests, but I get this:

```
Error: Cannot find module '/home/geo/github/atom/src/initialize-test-window.coffee'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:85:22)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)`
```

@lee-dohm do you know what to do enable running tests again?

**Comment by lee-dohm** [comment]
> do you know what to do enable running tests again?

I'd recommend putting the Atom source back in `~/github/atom` like before.

**Comment by International** [comment]
Having atom source in `~/github/atom` makes the package specs not run at all. The window that should open and run the tests, doesn't open at all.
