### ISSUE TITLE
JavaScript autocompletion breaking at accent

### ISSUE THREAD

**Issue by Bouzmine** [atom/atom#11272]
When I type in JavaScript there is always autocompletion for word that are not functions or variables. These are useful but as I am a French speaker, I frequently use accents in strings. What happens is the word is cut just before the letter with the accent (e.g. numéro -> num). Sorry if I'm not in the right place but didn't know in what package to put it.

**Comment by puranjayjain** [comment]
@Bouzmine can you open an issue [here](https://github.com/atom/language-javascript) as this would be a more appropriate place for it and close this issue here?

**Comment by Bouzmine** [comment]
Opened another issue in atom/language-javascript #340
