### ISSUE TITLE
[fedora] menus clip text on narrow monitors

### ISSUE THREAD

**Issue by andjd** [atom/atom#11279]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Menus are capped at an unusably narrow width making reading them impossible. See screenshots.
![atombug](https://cloud.githubusercontent.com/assets/13681211/14049833/2d81b876-f28e-11e5-9eba-dd5102a085d4.png)
![atombug2](https://cloud.githubusercontent.com/assets/13681211/14049837/33267f82-f28e-11e5-9c0d-9ec4d9cffd12.png)

This error occurs on a 1080 * 1920 monitor when set in a vertical orientation.  The problem does not manifest when the monitor is set in a horizontal orientation. 

### Steps to Reproduce

Open atom in vertically-oriented monitor. 

**Expected behavior:** Menus would resize to the appropriate width to fit all text.

**Actual behavior:** FILE, EDIT, VIEW, and SELECTION menus are all affected, and all render with the same width and in the same location.  PACKAGES and HELP menus display normally.

### Versions
Atom: 1.5.4

apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.5

Fedora release 23
GNOME Shell 3.18.4

**Comment by 50Wliu** [comment]
This seems either like a Gnome issue or an Electron issue: /cc @zcbenz.

**Comment by andjd** [comment]
I don't know what or if anything was changed, but the problem is gone now. :smile:

**Comment by 50Wliu** [comment]
Awesome, thanks for updating us!
It was probably the upgrade to Electron 0.37.0 that did it :).
