### ISSUE TITLE
Unable to scroll when mouse is over autocompletion bubble

### ISSUE THREAD

**Issue by Bouzmine** [atom/atom#11273]
When mouse is over autocompletion bubble it is impossible to scroll.

Version : 1.6.0
OS : OS X 10.11

**Comment by amytruong** [comment]
Do you mean that you cannot scroll in the autocompletion bubble to see the other options? 😬 
If the mouse is over the autocompletion bubble, that's where it's "focused" at but if you move the mouse elsewhere on the screen, you can still scroll.

**Comment by Bouzmine** [comment]
I mean when the bubble is open and I want to scroll the buffer. I'm unable to do so when my mouse is over the autocompletion bubble. I thought this behvior was a bug. In my case, there was only one element in the autocompletion bubble.
