### ISSUE TITLE
Autocomplete+ does not make it easy to select what you typed as correct

### ISSUE THREAD

**Issue by fields** [atom/atom#11276]
I am frequently frustrated by the corrections that autocomplete+ makes as I type, but it is very useful to have _suggestions_. It would help a lot to make the default correction be the string that was typed instead of having to press escape or several arrow keys every time to force autocmplete+ to not change it.

This frequently manifests when I'm typing a string that appears as a substring in other strings in the same project. (e.g.: I type 'us-west-1', and autocomplete wants to change it to 'us-west-1a' or 'us-west-1b' but 'us-west-1' is not an option easily selected in the suggestions menu).

I think what I'm asking for is an option to have autocomplete automatically pop up, but not automatically change anything unless I ask it to.

I am using Atom 1.4.3.

**Comment by Zireael07** [comment]
Autocomplete_plus is a package. Make this request on the package repository.

Unless you mean the bundled autocomplete, which has no plus.

**Comment by fields** [comment]
I'm not sure. I seem to have autocomplete-plus installed, but in the preferences it's listed as an atom core package.

**Comment by 50Wliu** [comment]
`autocomplete-plus` is the "new" core package for autocompletion, and it replaced the old `autocomplete` package at least a year ago.  There is no native autocompletion if you disable `autocomplete-plus`.
