### ISSUE TITLE
Click on package version number to go directly to CHANGELOG

### ISSUE THREAD

**Issue by brettz9** [atom/atom#11287]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When viewing packages (especially under "Updates" and "Packages", but I suppose also under "Install" or "Themes", I think it would be handy to be able to click the version number to go directly to the CHANGELOG without needing to first open the Settings and then click on CHANGELOG there. Given the frequency of updates of some packages and my curiosity about changes, it'd be nice to avoid the need for drill-down ever time I am viewing these available updates.

(Btw, not sure whether you actually wanted all of the boilerplate here on the issue report as most is irrelevant in my case, but I know some can be sticklers for procedure and didn't know if you had a tool to automatically parse this.)

### Steps to Reproduce

N/A

**Expected behavior:** [What you expected to happen]

N/A

**Actual behavior:** [What actually happened]

N/A

### Versions

1.6.0

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/settings-view? Thanks!
