### ISSUE TITLE
(happens a lot, hard to reproduce) Stray text edits

### ISSUE THREAD

**Issue by rogerbinns** [atom/atom#11281]
### Description

I keep experiencing "stray" changes to my files.  I'm mainly working on Python code, so I'll make some edits, and then run my code from the command line.  At that point Python complains about syntax errors.

What will have happened is atom will have applied a slightly mangled version of an edit I did make to some other places in the same or different file.  For example I just added the line 

    import pdb; pdb.set_trace()

to one file.  atom then also changed a different file (same project) so that a line that looked like this:

                                'org.freedesktop.DBus.ObjectManager')

ended up as:

      'org.    import pdb ; pdb.set_trace()s", v, subkey=dev)

The ````subkey``` bit is a fragment from a different nearby line of code.  Fortunately I can usually use gitg to revert these when they happen, but it is annoying.  Sometimes one other place is affected such as the example above, other times I've seen it happen in up to 7 other places.

### Correlations

This seems to happen mostly with Python code, but then I mostly edit Python code.  It has happened in other files such as css and javascript.

It seems like having Symbols-Tree-View turned on makes it *far* more likely to happen.

I have a multi-monitor setup and often have two atom windows each on a different monitor.  They are created by File > New Window or right clicking on a project folder and Open in New Window (ie I am not running two distinct copies of atom).  I am working on the same project folders in both and often the same files.  It is more likely to happen when I am doing this.

### Versions

This has been happening since I started using atom (November 2015) but was at a very low level then.  It seems to be happening a lot more now (about 3 times a day).  However I am working more intensely now.  I have been keeping up with the versions.

````
$ atom --version
1.6.0
$ apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.0
````

The system is stock Ubuntu 15.10 AMD64 with 32GB of RAM.  I get the deb packages from atom.io after the RSS feed tells me there is a new release.

**Comment by mnquintana** [comment]
Hmmm that's pretty weird. :confused: Can you reproduce this after quitting Atom completely and restarting it in safe mode? (`atom --safe`)

**Comment by rogerbinns** [comment]
Note I can't reproduce this on demand.  It just happens while working.  Unfortunately safe mode isn't usable enough for me to work in as a whole bunch of packages are not enabled in it.

My suspicion as to the underlying cause is some sort of race condition when you have the same file open in multiple windows, and I also sometimes use multiple panes too.  Something somewhere is hanging onto editor position information for too long and then typing gets inserted into wrong locations.  Unfortunately it could be the editor core, a package not handling the multiples correctly, the editor core and package interacting wrongly, or just a broken piece of caching somewhere.  Sadly determining that from the symptoms alone is very hard.  I do however have some suspicions that symbols tree view is involved, even if innocent and causing something else to lose the plot.

For the next week or so I'll add a comment to this ticket each time it happens to me, as well as any context.

**Comment by rogerbinns** [comment]
BTW it hasn't happened again since opening this ticket.

**Comment by rogerbinns** [comment]
It has now happened at least once today, and possibly a second time.  I'm using my laptop with only a single Atom window, but symbols-tree-view is on.  The change atom made is this:

     -        if len(p)==0:
     +        if len(p)==0:            if current==new_state:
     +                return accept()
     +

The two lines inserted at that random location were actually elsewhere in the same python file around 200 lines later and I had selected them, then pressed control down about five times to move them further down in an if statement.

**Comment by mnquintana** [comment]
Can you post a list of your installed packages? (`apm list --installed`)

**Comment by rogerbinns** [comment]
[apm-installed.txt](https://github.com/atom/atom/files/205270/apm-installed.txt)

**Comment by mnquintana** [comment]
Looks like that paste didn't quite go through – you can just paste it in a code block here.

**Comment by rogerbinns** [comment]
If I click on the link it downloads as an attachment just fine.  Anyway here it is again:

`[36m/home/rogerb/.atom/packages[39m (25)
├── aligner-python@1.0.1
├── atom-beautify@0.29.1
├── atom-jinja2@0.5.0
├── autocomplete-clang@0.8.9
├── autocomplete-python@1.7.2
├── clang-format@1.25.0
├── expose@0.11.1
├── hyperclick@0.0.35
├── language-diff@0.4.0
├── language-javascript-semantic@0.2.1
├── language-restructuredtext@0.13.0
├── linter@1.11.4
├── linter-clang@3.4.4
├── linter-csslint@1.3.2
├── linter-eslint@7.1.3
├── linter-flake8@1.13.0
├── linter-rst@0.0.3
├── merge-conflicts@1.4.0
├── nuclide-file-watcher@0.0.35
├── pigments@0.26.0
├── python-jedi@0.3.6
├── python-tools@0.6.7
├── quick-editor@0.4.3
├── slime@1.6.1
└── symbols-tree-view@0.11.0

`

**Comment by rogerbinns** [comment]
I've had the spurious edit happen again.

    -            "size": block["Size"],
    -            "drive": drive["Id"],
    -            "fsver": block["IdVersion"],
    -        }
    +            "size":int

The "int" most likely corresponds to a different file where I had `wait=int(wait)` and changed it to `wait=float(wait)`

**Comment by lygaret** [comment]
Double checking, but this happened to me: I had a minor short in my laptops trackpad that gave me spurious middle clicks: and seemingly random intervals, I ended up accidentally pasting the last selection wherever my cursor happened to be.

Just something to consider, it sounds crazy but it's happened.

**Comment by rogerbinns** [comment]
@lygaret you are right that unintended middle clicks must be ruled out.  I am absolutely certain that is not happening.

My suspicion is the cause is that Atom only has a portion of a file rendered as html, and that if you have multiple panes, multiple windows, the same file open more than once, and extensions like symbols tree view and linters that operate on whole files, something somewhere is getting confused having the wrong relative or absolute coordinates into a file (potentially even a race condition) during edits, which is how they end up being applied in the wrong place.

**Comment by rogerbinns** [comment]
Another occurence

````
-        us=not_useful[i][0]
-        them=not_useful[i+1][0]
-        if (them["filesystem"] and them["drive"]==us["drive"] and
-            them["_id"].startswith(us["_id"])):
+        us=not_useful[i][0"])):
             delrows.append(i)
-
-    if delrows:
-        for i in reversed(delrows):
-            del not_useful[i]
+info
````

**Comment by 50Wliu** [comment]
Something else that might need to be considered: Make sure you aren't accidentally Ctrl+clicking in your code, as that adds an extra cursor.

**Comment by rogerbinns** [comment]
I am reasonably certain I am not control clicking, but obviously can't prove it.  Note that I am using the same computers, mice, keyboards etc that I used emacs on for several years.

**Comment by rogerbinns** [comment]
Another two:

````
-        if not desired_source or not desired_dest:
+        if not desilogoselogosered_source or not desired_dest:
````

````
-                logging.exception("run_cr failed")
-            if not exit.is_set() and indev in audio_present:
-                logging.info("CR exited unexpectedly.  Restarting.")
-                time.sleep(0.3)
+                logose.sleep(0.3)
````

**Comment by Ben3eeE** [comment]
@rogerbinns As you said accidental middle mouse clicks must be ruled out and you say you did, but a few questions come to mind after reading this issue:

- How did you make sure it is not accidental middle clicks?
- Are you seeing the problem on multiple computers? Multiple computers of different models?
- Do you only use a laptop keyboard and have the touchpad enabled? Or an external keyboard/mouse?
- Did you try with another keyboard/mouse? Perhaps of a different model?
- Is it a paste event that is happening? Is the code being inserted on the cursor? It looks like it can be a paste event.

I believe some laptop models have middle click if you tap in a certain area on the touchpad and some have it while you tap with both fingers. I have had laptops where the touchpad suddenly got very sensitive in Ubuntu and I barely(Felt like I didn't) had to touch it for it to register a tap, which happened a fair amount while typing.
I worked around this by using http://linuxcommand.org/man_pages/syndaemon1.html to disable the touchpad while typing and never experienced a similar issue again.

**Comment by rogerbinns** [comment]
@Ben3eeE short of atom having some sort of black box recorder/audit log there isn't a way to prove this is not errant middle clicks.  I have many reasons for believing that it isn't middle clicks:

* This has been happening on my main workstation and my laptop, which are the two places I use atom.  I am not experiencing middle clicks in any other window such as terminals, although windows like browsers don't do anything with middle clicks so there I wouldn't notice.

* I switched from emacs last year, and emacs did respond to middle clicks.  (Note I do use middle clicks but mostly in terminals and have been doing so since 1989!)  However I never had any problems like this issue before using atom.

* I am not using the touchpad on the laptop and instead use an external bluetooth mouse.  I also have tapping on the touchpad for a click disabled.

* The errant changes are **not** happening in sections of code I am editing, and are hundreds of lines away.  I find out by going to run python code or javascript and getting syntax errors, or doing git commits and finding these kind of changes in less noticable places like css files.

* The changes themselves are not the result of a single click.  This is why I provided diffs above where you can see that a single middle click couldn't produce them.  At that very least they would require selecting some text, and then middle clicking to replace the selection.  Many would require even more clicks than that.

**Comment by Zireael07** [comment]
Do you work with branches? Switch branches, stash, etc.? Atom sometimes fails tor recognize changed stuff if you e.g. switch branches...

**Comment by Ben3eeE** [comment]
@rogerbinns Thank you for clearing this up. I can agree that this is not caused by middle mouse paste based on this information.
I tried to do a similar setup to try and reproduce the problem in a VM and what catches my eye is nuclide-file-watcher@0.0.35
According to https://libraries.io/atom/nuclide-file-watcher this package has been removed and is no longer updated and cannot be used any more, perhaps this is causing the problem?
It is not possible to install this package using apm so I don't know how I can install it and try to reproduce the problem with the same packages/setup. I also have no experience with deprecated/removed packages or anything perhaps someone else has more insight?

**Comment by Zireael07** [comment]
Looking at the package list, what does hyperclick package do?

**Comment by rogerbinns** [comment]
@Zireael07 I do branches and stashes, but they are rare (branches maybe once a month, stashes about twice a week).  I do do all my git activity outside of atom, using the command line or usually gitg.  @Ben3eeE I had installed that package because I wanted to make sure that the editor contents are fresh, and this is an issue with all editors.  In the preferences atom doesn't show it in the deprecated section, so it doesn't seem to have been properly withdrawn.  In any event I have now uninstalled the package and restarted atom.

**Comment by rogerbinns** [comment]
@Zireael07 hyperclick shows up in my config as disabled, so I have uninstalled it.  I don't know why it is installed, but presumably as part of some attempt to get IDE like functionality (show usages, go to definition kind of thing).  

I should also point out that I prefer "defaults" and "out of the box" configurations.  Consequently my philosophy is to have fewer additional packages, and then ones that are actually useful to my work.  Since most of my development is in Python, that is what ended up installing.  I also picked the packages during the atom 1.2 days with whatever the site seemed to be recommending/popular.

**Comment by 50Wliu** [comment]
@rogerbinns Can you try installing the [bug-report](https://atom.io/packages/bug-report) package, then  execute the `bug-report:open` command and paste the command history here when you encounter the accidental edits?  Still have no clue about what could be causing this :confused:.

As a side note, the command history functionality should really be viewable as a command through the default notifications package since it uses the same code...time to create a feature request over there :).

**Comment by rogerbinns** [comment]
@50Wliu I have bug-report installed now and am waiting for the problem to re-occur.

**Comment by rogerbinns** [comment]
It hasn't re-occurred in the last week.  That doesn't mean the issue is certainly gone, but there is a reasonable probability that it has.  Consequently I am closing the issue.

I am concerned that atom allowed a package (nuclide-file-watcher) to end up in zombie state.  They really should be at least completely disabled, if not uninstalled.

**Comment by 50Wliu** [comment]
> I am concerned that atom allowed a package (nuclide-file-watcher) to end up in zombie state. They really should be at least completely disabled, if not uninstalled.

Please feel free to file an issue on atom/settings-view for this.
