### ISSUE TITLE
Add ability to disable auto range clipping on mouse events

### ISSUE THREAD

**Issue by steelbrain** [atom/atom#11285]
### Description

Currently we have an API, [`TextEditorComponent::screenPositionForMouseEvent`](https://github.com/atom/atom/blob/98c8a08ac3837dc59c00e77a913af5f1358f6a14/src/text-editor-component.coffee#L910). The problem/limitation we're facing with that API is that there is no way to know if the cursor is actually on that position or it is being trimmed to that position.

As an explanation of the bug, imagine you have a file with 50 lines, and you have enabled the `Scroll Past End` config. If you place your cursor below the last line, it'll still return the last line as the position. It happens both vertically and horizontally, so if you had a line with 50 characters and you placed your mouse ahead of it, it'll return the position as 50.

### Proposed Change

I would like to propose an option to the `TextEditorComponent::screenPositionForMouseEvent` function which allows us to receive null instead of clipped ranges. That way we'll be able to determine if the user has put their cursor there or is it Atom API trying to make things easier for us.

Blocks https://github.com/steelbrain/linter-ui-default/issues/63

**Comment by lee-dohm** [comment]
`screenPositionForMouseEvent` is based on `screenPositionForPixelPosition` for which there is an inverse function `pixelPositionForScreenPosition`. If you wanted to determine if they clicked in the actual screen position, you could check against the reported pixel position for the given screen position ... within a reasonable delta.

**Comment by steelbrain** [comment]
@lee-dohm Thank you! It's a very good way of solving this, I'm using it for now

**Comment by lee-dohm** [comment]
Sounds good. I'm going to close this until my suggested solution proves to be inadequate.
