### ISSUE TITLE
right ALT is treated as CTRL-ALT on WIN

### ISSUE THREAD

**Issue by retepaskab** [atom/atom#11289]
Windows treats right-ALT as a special key, resulting in different character than it was pressed with. For example on a Hungarian layout, right-ALT-Q is \, left-ALT-Q is ALT-Q. Atom treats right-ALT as CTRL-ALT. This results in being unable to enter certain characters, and getting key-mapped commands instead of them.

**Reproduction Steps:**

1. Win10 Hungarian keyboard layout
2. open some file that can be reflowed
3. enter right-ALT-Q 

**Expected behavior:**

character \ inserted

**Observed behavior:**

reflow command

**Screenshots and GIFs**

-

**Atom version:** 1.6.0
**OS and version:** WIN10 Pro, Hungarian 101-key QWERTZ layout

**Installed packages:**

unrelevant

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: Don't know, first install
* Problem can be reliably reproduced, doesn't happen randomly: Yes, doesn't
* Problem happens with all files and projects, not only some files or projects: yes, any file

**Comment by mnquintana** [comment]
Sounds like you're running into https://github.com/atom/atom-keymap/issues/35 – feel free to subscribe there for updates. Sorry for the trouble!
