### ISSUE TITLE
[enhancement] syntax highlight for ZIMPL (package wanted) 

### ISSUE THREAD

**Issue by aovchinn** [atom/atom#11292]
I don't sure that I can post it here, but I was dissapointed when can't find any highlight for ZIMPL

here someone make tm file for sublime https://github.com/joneshf/sublime-zimpl 

but I can't find a way to use it within atom, or convert it to cson or something.

Sorry for dumb issue, which is not an issue, but where else could I get help.

**Comment by 50Wliu** [comment]
@aovchinn [Discuss](https://discuss.atom.io) is a great place to post feature requests like this one.  I hope that helps!

To more directly answer your question: can you try running `apm convert https://github.com/joneshf/sublime-zimpl` and see if that works?

**Comment by thorade** [comment]
https://discuss.atom.io/t/syntax-highlight-for-zimpl-package-wanted/27202
https://discuss.atom.io/t/convert-sublime-grammar-to-atom-grammar/14843/7
