### ISSUE TITLE
Changed my C:/ User Profile folder name, right clicking "Open with Atom" gives Explorer not found, and missing icon.

### ISSUE THREAD

**Issue by bamtan** [atom/atom#11298]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Title. I'm on Windows 7. I can still open it via my Start Menu, but not through right clicking.

### Steps to Reproduce

1. Install Atom.io
2. Change your C:/Users folder name using [this guide](http://www.sevenforums.com/tutorials/147545-user-profile-folder-change-user-account-folder-name.html).
3. Restart
4. Icon should be missing, as well as "Application not found"

![Right click](https://i.imgur.com/OgMw7hQ.png)
![Explorer](https://i.imgur.com/MLmHtay.png)

**Expected behavior:** [What you expected to happen]
Opens Atom.

**Actual behavior:** [What actually happened]
Doesn't find the location of Atom, cant open.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line.

Can't execute following commands in command line: **1.6.0**.

**Comment by thomasjo** [comment]
Atom get's installed into your profile's `AppData` directory (e.g. `C:\Users\bamtan\AppData\Local\atom`), so if you've changed the name of the profile folder, the Explorer shell integration will be broken. Just reinstall Atom and your problem will/should go away.

**Comment by damieng** [comment]
Yeah there is no way we could automatically recover from this.

**Comment by dhirschfeld** [comment]
How about an option in Atom configuration to install the shortcut so rather than having to reinstall from scratch you just click a button and it updates the registry itself?

**Comment by damieng** [comment]
Yeah the orphaned shortcut is a bit of a pain. We'll separate out the Atom Beta and non-Beta installers soon so this won't happen.  In the mean time you could manually delete the registry entry or try a clean-up tool - I suspect the CCleaner registry cleaner would spot the reference to a missing .exe and offer to remove it.

**Comment by damieng** [comment]
Here's a better way to clean up the registry. Run the following commands from the Command Prompt;

`
reg delete HKEY_CURRENT_USER\Software\Classes\Applications\Atom /f
reg delete HKEY_CURRENT_USER\Software\Classes\*\shell\Atom /f
reg delete HKEY_CURRENT_USER\Software\Classes\Directory\shell\Atom /f
reg delete HKEY_CURRENT_USER\Software\Classes\Directory\background\shell\Atom /f
`

Some of them may say unable to find depending on what version/options you had set but the four of them combined should clean up the context menu.

If you want to clean up after a beta just replace Atom with AtomBeta in those commands.  Sorry for the inconvenience.

**Comment by dhirschfeld** [comment]
Thanks, that's gotten rid of the orphaned icon.

**Comment by OliverRC** [comment]
This happens after updates to Atom because of the way Electron handles their updates. It makes new folders when the application is updated. I think that Electron really needs to consider how this affects the Windows Shell, because everytime it update all the Context Menus, and File Associates are broken. 

Gets kinda annoying.

**Comment by birksy89** [comment]
I followed instructions from @OliverRC but it still didn't work for me.

I then reinstalled Atom, but this didn't work for me either.

Finally when routing around in the settings for Atom, I when into the "System" part of the settings menu, and found that the two "context menu" settings were unchecked.

Checking these fixed the problem.

![capture](https://cloud.githubusercontent.com/assets/4971630/18345160/22f4e1a6-75b2-11e6-9474-f0ebe4bd43ab.PNG)

**Comment by jerone** [comment]
Some discussion happening here too: https://github.com/atom/settings-view/pull/811#issuecomment-236678606

**Comment by damieng** [comment]
@OliverRC The upgrade process should be taking care of the folder name differences.

**Comment by OliverRC** [comment]
@damieng it  didn't on my machine so I can only assume something prevented it making the necessary changes.

**Comment by damieng** [comment]
There was a bug in the update mechanism. The fix has been checked in and will be included in future updates :)

**Comment by rhernandog** [comment]
@birksy89 Thanks, never thought about checking the settings after an update. That solved the issue.
