### ISSUE TITLE
Mix of Arabic and Latin rendered incorrectly

### ISSUE THREAD

**Issue by emilbayes** [atom/atom#11290]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

I don't understand Arabic myself, and it's the first time working with a RTL language, but I'm experiencing some rendering issues with a specific text. I have the following SQL insert statement:

``` sql
INSERT INTO `dwp_terms` VALUES
  (19,'عين المدينة','3ayn-almadina',0);
```

Which renders incorrectly. It seems it might be a Webkit bug, but I'm not sure. It might also be that the text is ill formatted, but it seems to render correctly in Firefox and Apple Notes, albeit with the words in reverse. I've included a screenshot from Sublime Text 3 which seems to render as I expected.
### Steps to Reproduce
1. Use the following piece of text as a template `(19,'','3ayn-almadina',0),`
2. Paste `عين المدينة` into the empty quotes
3. Incorrect rendering

I do not know if this applies to more RTL scripts, but I've been working with about 40 terms that were "converted" to `INSERT` statements, and this was the only one causing trouble.

**Expected behavior:** here rendered with Sublime Text 3 (however, seems to not render arabic correctly)

<img width="406" alt="Sublime Text 3 Rendering" src="https://cloud.githubusercontent.com/assets/416524/14080299/6a4500c4-f504-11e5-95a2-db7c83200a0a.png">

**Actual behavior:** rendered with Atom 1.6.0

<img width="332" alt="Atom Rendering" src="https://cloud.githubusercontent.com/assets/416524/14080298/6a2dc788-f504-11e5-8067-d7f7badda11b.png">

The generated HTML, which looks correct:

``` html
<span class="source pgsql">
  <span class="meta statement pgsql">
    <span class="leading-whitespace indent-guide">  </span>
    (
    <span class="constant numeric pgsql">19</span>
    ,
    <span class="string quoted single pgsql">
      <span class="punctuation definition string begin pgsql">'</span>
      عين المدينة'
    </span>
    ,
    <span class="string quoted single pgsql">
      <span class="punctuation definition string begin pgsql">'</span>
      3ayn-almadina'
    </span>
    ,
    <span class="constant numeric pgsql">0</span>
    ),
  </span>
</span>
```
### Versions

``` sh
$ atom --version
1.6.0
$ apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.2
```

**Comment by Zireael07** [comment]
ST3 renders Arabic as LTR, therefore rendering it nonsensical.

**Comment by emilbayes** [comment]
I can confirm that the issue still persists in 1.19.1

**Comment by emilbayes** [comment]
Following the steps from the original report with the following versions, the issue still persists:

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G1314)
      Kernel Version: Darwin 16.7.0
      Boot Volume: 
      Boot Mode: 
      Computer Name: 
      User Name: 
      Secure Virtual Memory: 
      System Integrity Protection:
      Time since boot: 


$ uname -a
Darwin private 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
$ atom --version
Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.2
python 2.7.10
git 2.14.1
```

**Comment by Arcanemagus** [comment]
Note that the same bug happens in Chrome 70.0.3534.0:
![2018-08-29_13-56-44](https://user-images.githubusercontent.com/427137/44815106-7538d080-ab93-11e8-8120-26bfdff5b1ad.gif)

This is likely an Electron bug, that they will probably need to wait for it to get fixed in Chrome first.

**Comment by lee-dohm** [comment]
Reproduced this in a normal Chromium (v69.0.3497.100) `textarea` as well. (I was concerned that the GitHub comment field might have JS fiddly bits that would change the behavior.) It appears that this is a bug in Electron/Chromium.
