### ISSUE TITLE
atom startup: FATAL:nss_util.cc(211)] nss_error=-5925, os_error=0

### ISSUE THREAD

**Issue by sklages** [atom/atom#11299]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Without root access. Compiled NSS in current version (because initial built complained about old NSS version), set PATH and LD_LIBRARY_PATH accordingly, and compiled atom on custom (in-house built) 64bit linux, kernel 4.4.2, glibc 2.19.

```
$ /scratch/local2/de/atom/Atom/atom --safe
[8922:0329/124252:FATAL:nss_util.cc(211)] nss_error=-5925, os_error=0
#0 0x000001ae075e <unknown>
#1 0x000001af68eb <unknown>
#2 0x00000195a170 <unknown>
#3 0x00000070f44b <unknown>
#4 0x00000079254e <unknown>
#5 0x00000070ff34 <unknown>
#6 0x000002f3b097 atom::AtomCertVerifier::AtomCertVerifier()
#7 0x000002f2d940 atom::AtomBrowserContext::CreateCertVerifier()
#8 0x000002faffe2 brightray::URLRequestContextGetter::GetURLRequestContext()
#9 0x00000223fdcc <unknown>
#10 0x000002513a84 <unknown>
#11 0x000002513a09 <unknown>
#12 0x000001ae1683 <unknown>
#13 0x000001afcceb <unknown>
#14 0x000001afcff9 <unknown>
#15 0x000001afd1dd <unknown>
#16 0x000001ad71b9 <unknown>
#17 0x000001b103e0 <unknown>
#18 0x000001afc5da <unknown>
#19 0x0000022640c6 <unknown>
#20 0x0000022641f7 <unknown>
#21 0x000001b304e8 <unknown>
#22 0x000001b2cd0d <unknown>
#23 0x7fe520355191 start_thread
#24 0x7fe519e7c30d __clone

App load time: 493ms
Failed to get crash dump id.
Report Id: 
Aborted
```

### Steps to Reproduce

1. compile NSS from Mozilla Mercurial on custom linux 
2. compile atom from git or release
3. start atom

### Versions
```
Atom    : 1.8.0-dev-ea01981
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```
```
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.4.1
```

So I am not really sure where to start looking for the underlying problem ... hints are welcome.

thanks,
Sven

**Comment by adrian-stepien** [comment]
+1

**Comment by 50Wliu** [comment]
I'm probably just ignorant here as I generally don't use Linux, but can you elaborate on what "NSS" is @sklages?  As far as I'm aware that isn't one of the listed requirements for building Atom.

**Comment by brbsix** [comment]
[NSS](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/FAQ) is a crypto library used by chromium.

To OP, do you have the appropriate version of libgcrypt installed?

**Comment by sklages** [comment]
This has been slightly out of my focus for a while now :-) .. 

We have updated NSS[1] to 3.23 and NSPR[2] to 4.12. We were then able to compile atom.
It's just that the error message was not very helpful.
Sorry for not updating/closing the issue.

[1] = [Network Security Services] (https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS)
[2] = [Netscape Portable Runtime] (https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSPR)
