### ISSUE TITLE
[1.7.0] process.env keys on Windows are not case-insensitive anymore

### ISSUE THREAD

**Issue by maxnoel** [atom/atom#11302]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

On Windows, environment variable names are case-insensitive.

In Atom 1.7.0 for Windows, `process.env.PATH` is returning `undefined` if the path environment variable is defined as `Path` (it is then accessible as `process.env.Path` only).

In 1.6 the environment variable is accessible as both PATH and Path.

### Steps to Reproduce

1. On Windows, ensure your path environment variable (`%PATH%`) is defined as `Path` (not `PATH` as is customary on UNIX).
2. Launch Atom and open the dev console (ctrl+alt+I)
3. Evaluate `process.env.PATH`.

**Expected behavior:** `process.env.PATH` should return the contents of the Path environment variable, regardless of what case its name is spelled in (as in Atom 1.6).

**Actual behavior:** `process.env.PATH` evaluates to `undefined`. Only `process.env.Path` returns the proper contents of the environment variable.

### Versions

Atom    : 1.7.0-beta0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by damieng** [comment]
This isn't just .PATH. Previously anything off of env was case-insensitive but is now case sensitive.

**Comment by damieng** [comment]
Just tried with Node 5.0.0 which was case-sensitive and Node 4.4.1 which is insensitive.

**Comment by damieng** [comment]
Okay, tried this in Node 5.9.1 and it works there so not sure why it wouldn't be working in Atom.

**Comment by maxnoel** [comment]
While looking for more info on this issue (I'm not a JS developer so the intricacies of Node are unknown to me), I came across this thread: https://groups.google.com/forum/#!topic/nodejs/fFgZRRMaDRo

> * process.env does not in any way behave like a normal object. For example all values are coerced to string, and setting a value to "" (empty string) might actually delete the key. Also, on Windows, keys are case insensitive; changing that is going to break much more than it fixes. There's probably more weirdness that I am not even aware of, which is all caused by the fact that the environment *is* not a JS object. The "proper" way to do it would probably be to remove `process.env` and expose the functions `process.setenv()` and `process.getenv()`, but the way it works now is too damn convenient to remove. People should just accept the fact that process.env behaves a little different sometimes, and if you really need JS object semantics, make a copy of it.

It looks like in Node, `process.env` is not a Javascript Object but a magic stub that hooks into Node's C++ internals.

Does Atom (or Electron) by any chance somehow sanitize and/or replace `process.env` during its startup procedure?

**Comment by maxnoel** [comment]
Specifically, I'm noticing that https://github.com/atom/atom/blob/430a0e049a10f05227ef4460a4dd1668bfcf1087/src/atom-environment.coffee#L131 calls `environmentHelpers.normalize`, which is defined at https://github.com/atom/atom/blob/430a0e049a10f05227ef4460a4dd1668bfcf1087/src/environment-helpers.js#L70 and can replace `process.env` (although its initial purpose, I think, is to do so on OSX and only in certain cases).

Since `AtomEnvironment` is always instantiated with an `options.env` parameter (see https://github.com/atom/atom/blob/5e8752f7d8d1a3f751d293dfc92f869ce1611cef/src/initialize-application-window.coffee#L28), it seems to me that `normalize` will *always* replace `process.env`, thus breaking case insensitivity.

**Comment by damieng** [comment]
Hey @lee-dohm could this be caused by https://github.com/atom/atom/commit/8c53e25f802f7e5e6311a61087f78bbf4e246b20#diff-91bf726eeaaad75efb1705745a7af175 ?

**Comment by lee-dohm** [comment]
Yes, it is definitely possible. I didn't realize that there was a
"case-insensitive" object collection in JS.

**Comment by maxnoel** [comment]
There isn't one -- not in JS per se, at least. `process.env` is a "magic" object in Node internals that happens to be case-insensivite *on Windows only*.

**Comment by maxnoel** [comment]
I can't try this myself because I don't have the correct version of Visual Studio installed and can't build Atom, but it looks to me like replacing the `process.env = options.env` line in `normalize` (https://github.com/atom/atom/blob/430a0e049a10f05227ef4460a4dd1668bfcf1087/src/environment-helpers.js#L72) with a loop that copies keys/values from `options.env` to `process.env` (whatever the Javascript/Coffeescript equivalent of `dict.update` is) would solve the issue.

https://github.com/atom/atom/blob/430a0e049a10f05227ef4460a4dd1668bfcf1087/src/environment-helpers.js#L89 would probably need the same update for consistency's sake, but it's less important as it's only ever run on OSX, where environment variables are case-sensitive.

**Comment by damieng** [comment]
I'm wondering if we really want to fix this for path. It seems to be that if it's case-insensitive on Windows then Windows developers making atom plugins that use this will inadvertently create plugins that fail on Mac and Linux...

**Comment by maxnoel** [comment]
On the other hand, if we *don't* fix it Linux and OSX developers making Atom plugins will break on Windows.

The most common use case (and indeed the one that made me stumble across the issue: updating to Atom 1.7 beta broke atom-perforce for me) is the `PATH` environment variable. It's called `PATH` on UNIX and `Path` in a lot of (including mine), but definitely not all, Windows installations.

**Comment by ayan4m1** [comment]
PlatformIO is currently borked in Atom 1.7.0 on Windows as a result of this issue. If some upstream devs chime in with the fix they'd accept I can put some time toward it.

**Comment by maxnoel** [comment]
I suggested a fix earlier in the thread (one that I can't test because I don't have access to VS2013).

I'm somewhat worried that 1.7.0 final was released with that issue opened. I might not have been clear enough in my report, but *this issue breaks every package that interacts with `$PATH` on Windows 10*.

**Comment by ayan4m1** [comment]
@maxnoel Sorry, I did read what you described, just wanted to try and provoke any dicussion that was pending, but I agree that this seems like something that slipped under the radar.

I think that environment-helpers.js contains a few statements that would have unintended effects on the nature of the keys and values in the process.env and options.env object despite the code being focused on an OSX fix as you are saying. I will have time to test my hypotheses in the next day and will report back my findings.

**Comment by lee-dohm** [comment]
My apologies for letting this one slip through the cracks. This is the first thing on my todo list for tomorrow.
