### ISSUE TITLE
folder removed but files from the folder still opened

### ISSUE THREAD

**Issue by calidion** [atom/atom#11305]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
  Yes
- [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
  Yes.
- [ ] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
  No.
- [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
  No.
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
  Yes.
- [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
  No.

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

[Description of the bug or feature]
### Steps to Reproduce
1. open a file
2. delete the folder of the file opened
3. then the file still opened.

**Expected behavior:** [What you expected to happen]
the file will be closed. 
**Actual behavior:** [What actually happened]
file not closed
### Versions

1.5.4

**Comment by lee-dohm** [comment]
Assuming you're talking about OS X, this is fixed in v1.7-beta of Atom. See https://github.com/atom/tabs/issues/160.

**Comment by calidion** [comment]
no. i am talking about linux.

**Comment by calidion** [comment]
@lee-dohm 
did you ever know what i mean?
did you ever try to reproduce what I said?
if not, why you close this issue so arbitrarily?

what i said is not a file, but a folder, and inside linux os. having nothing to do with os x.

**Comment by lee-dohm** [comment]
@calidion No, I haven't yet tried to reproduce the issue on Linux. I closed the it because based on the information you gave me, it was an already solved issue. I didn't respond right away because I was sleeping.

In the future, please give as much information as you can. It will help prevent these kinds of misunderstandings.

**Comment by lee-dohm** [comment]
Also, please update to the latest version of Atom and let us know if the problem reproduces.

**Comment by amytruong** [comment]
I was able to reproduce this in ubuntu 15.10. 
Thank you for reporting @calidion

**Comment by calidion** [comment]
@amytruong 
yes, reproducable in ubutnu 14.04, atom rev 1.6.1.

**Comment by calidion** [comment]
How surprise it is to find that files inside the folder and the files editing inside pane views are not connected.
when the files inside the folder are changed, the files editing are ignorance of the these changes...

this may be the worst thing i ever encountered with atom.

**Comment by calidion** [comment]
when a file is changed inside a folder, 
and when you try to remove a folder,
there is no warning that the file inside the folder are opened and changed.
and if you press Ctrl+S, the removed folder will show again, and the files not saved will be created again.

I have to say that is the most strange logic i ever known.

**Comment by Taz8du29** [comment]
It's the normal behavior of 99% of text editors ...
Try with notepad on windows, sublime text, gedit, even microsoft word or libreoffice... it'll happen.
