### ISSUE TITLE
Text is distorted

### ISSUE THREAD

**Issue by pgrekovich** [atom/atom#11300]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Sometimes if i write code, i have some text distortion (see on attachment). I use Ubuntu 15.10, Atom version 1.6.0 I don't know how to reproduce this, but my friend has same problem on Windows 10, and atom 1.6.0.

![Distored text](http://i.imgur.com/Ke3G97t.png)
### Steps to Reproduce

No ideas.

**Expected behavior:** Text look like as on the old TV

**Actual behavior:** My text looks like text
### Versions

1.6.0

**Comment by bddenhartog** [comment]
@pgrekovich 

1. Looks like you accidentally misplaced the expected and actual behavior lines - might want to fix that to avoid confusion on anyone's part!

2. Do you experience this in Chrome/Chromium on the same machine?

**Comment by pgrekovich** [comment]
@bddenhartog 
> Do you experience this in Chrome/Chromium (or any other browser) on the same machine?

No, i have this problem only in Atom

**Comment by bddenhartog** [comment]
@pgrekovich Okay. I ask only because this looks like something that may be caused by your graphics card (GPU) and installed drivers, but maybe someone else has more accurate insight into the problem.

**Comment by pgrekovich** [comment]
@bddenhartog  yeah, i thought about it, but all test are ok. and i have this problem only in Atom.

**Comment by damieng** [comment]
Are you using an AMD graphics card?

**Comment by pgrekovich** [comment]
@damieng no, intel hd graphics.

**Comment by damieng** [comment]
This still an issue with 1.7 as well?

**Comment by pgrekovich** [comment]
Yes, reproduced on 1.7

**Comment by jodigiordano** [comment]
@pgrekovich: for me the issue was resolved by upgrading from 1.8 to 1.11.2.

**Comment by pgrekovich** [comment]
@jodigiordano yep! fixed, thank!
