### ISSUE TITLE
new feature - soft wrap at preferred line length not dependent on window width

### ISSUE THREAD

**Issue by svatem1** [atom/atom#11303]
1st post of this discussion says it all:
https://discuss.atom.io/t/truly-soft-wrap-at-preferred-line-length/10633

Point is to have wrapping at preferred line length that doesn't change into wrapping at window's width when window starts to be smaller than preferred line length.

**Suggested UI/logic change to maintain current behavior as well as the new one**
1. [What's now]
   There are 2 wrap related options in UI, "soft wrap" (sw) and "soft wrap at preferred line legth" (swpll), both are binary options, which gives 4 different states they can express, currently only 3 states are being used, "sw: on, swpll: off" & "sw: on, swpll: on" & 2 states with "sw: off" that do the same.
2. [Why can it be problematic]
   Imagine 2 buffers side by side, when you change the dimensions of the buffers, the smaller one (in case it's code) essentialy becomes unreadable, moreover wrapping changes the position of view into the buffer. Why not turn wrapping off then at all? Because it's usefull sometimes to allow very long lines in file yet to have the possibility to see all of it without scrolling.
3. [How to do it painlessly with maximum backwards compatibility & keeping most of current behavior]
   How about implementing "correct soft wrap at preferred line length" when "sw: off & swpll: on"? That way all currently working states would be preserved, everybody could pick her/his wrap style including the new one and only ppl who currently have "sw: off, swpll: on" would notice unwanted change - but then again, it would be a matter of changing the settings, their desired option would not be removed.

**Atom Version:** [1.6]
**OS and Version:** [Win 10]

**Comment by ADTC** [comment]
Re-open this please! I am shocked that the option "Soft Wrap at Preferred Line Length" **does NOT do exactly what it says on the tin:**

> Instead of wrapping lines to the window's width, wrap lines to the number of characters defined by the `Preferred Line Length` setting.

Well then, why does it wrap to the window width when the window's width is shorter than the width defined by the `Preferred Line Length` setting? That's not what the description says!

I expected it to work as per the description, where it would continue to wrap at my preferred length, and if the window is too narrow, I would scroll horizontally to see the rest of the lines (which are wrapped at my preferred line length).

**Comment by ADTC** [comment]
My suggestion would be to replace the two checkboxes from the Editor settings called "Soft Wrap" and "Soft Wrap at Preferred Line Length" to a 5-state drop-down box with the following options:

Soft Wrap  
_Wraps lines that exceed the selected criteria._
- Disabled
- Width of the window
- Preferred line length
- Window's width or preferred line length, whichever is shorter
- Window's width or preferred line length, whichever is longer

Also, this new drop-down should be placed just below or near the "Preferred Line Length" text box. For consistency, the "Soft Wrap Hanging Indent" text box should also be moved there.

I think the 5-state options are pretty self-explanatory, but feel free to ask any questions. I believe in giving the user all the possible options and letting them decide what they want.

**Comment by feakuru** [comment]
would someone please at least comment on this? @Ben3eeE?

**Comment by iolsen** [comment]
I agree this would be more sensible behavior, but it's unlikely the maintainer team will prioritize this work in the foreseeable future. We'd accept a well-written PR that implements it!

**Comment by feakuru** [comment]
@iolsen I am sorry, but is closing the issue really appropriate? Wouldn't a label for 'not-in-the-near-future' issues be more logical? I dunno, 'backlog'?

**Comment by ADTC** [comment]
I agree, this should at least be in the backlog.

**Comment by lee-dohm** [comment]
@feakuru Yes, closing issues that we don't have any plans to work on is appropriate and common practice for large open source projects. There are only so many things that we can keep track of and limiting the list of open issues to the things that we plan to prioritize gives people an easy way to understand the plans we have for the near future. The list of open issues is the maintainer team's backlog but when we close issues that we don't intend to work on in the near future, we do our best to be clear on whether we would accept a PR for the issue or not. Also, @50Wliu also added the `help-wanted` label. This makes these kinds of issues easily searchable.

I can understand your frustration at something you want addressed not being prioritized. We're just trying to be as transparent as possible on what we plan to work on and what we don't. i hope you can appreciate that.

**Comment by feakuru** [comment]
@lee-dohm no frustration intended, thank you for the verbose explanation :)

**Comment by 0tho** [comment]
I would like to work on this issue as I expected that turning on Soft Wrap at Preferred Line Length(swpll) would allow that the lines were wrapped at exactly the value of Preferred Line Length.

The thing is, for some this appears to be a feature and not a bug, so I would like to know what would be the best approach to keep both the old option and add a new one where swpll is respected independently of window size.

ps: Sorry for the duplicate issue, I thought creating a new one was actually the right thing to do

**Comment by rsese** [comment]
@0tho - the feedback I heard from the team is that they would consider a pull request that implements the setting as described in https://github.com/atom/atom/issues/11303#issuecomment-331634455.  When you open the pull request, please fill out the pull request template with as much detail as you can and see the [contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#pull-requests) if you haven't already.  Thanks again for your interest!

**Comment by michael-camilo** [comment]
Almost 5 years and Atom don't fix it? Don't even provide one developer to review a PR opened for the last 2 years ???

**Comment by pfgithub** [comment]
The current options for soft wrapping are broken for variable-width fonts and cause the text to wrap way before the edge of the screen, is there anything that can be done about this now that the PR is closed? Screenshot of the issue
![image](https://user-images.githubusercontent.com/6010774/120731278-2765fb00-c498-11eb-9d20-d81cb3113d5e.png)
Both "Soft Wrap and "Soft Wrap At Preferred Line Length" are off

**Comment by icecream17** [comment]
Wait, if Soft Wrap is off then why is the text wrapping?
