### ISSUE TITLE
Include version number in released .deb files

### ISSUE THREAD

**Issue by TheJosh** [atom/atom#11307]
### Description

It's difficult to determine the currently available version of the .deb files. It's also confusing if you download to a directory which already has an `atom-amd64.deb` file.

This change could also be applied to other releases; `atom-xx.yy.zz-mac.zip`, `atom-xx.yy.zz-windows.zip`, etc
### Steps to Reproduce
1. Download atom.
2. Wait a month or two.
3. Download atom again.
4. Get confused when looking in your downloads directory.

**Expected behavior:**
File is named `atom-1.6.1-amd64.deb`.

**Actual behavior:**
File is named `atom-amd64.deb`.
### Versions

All versions appear to be affected.

**Comment by Evpok** [comment]
That's probably because [it](https://github.com/atom/atom/blob/7929e261a0d6e78ff4ca5196c8b385946e64dbd9/script/lib/create-debian-package.js) provides no [changelog](http://unix.stackexchange.com/a/194574/19765) as far as I understand.

**Comment by TheJosh** [comment]
Lack of changelog seems to be a problem across the board...

**Comment by cjwelborn** [comment]
If putting it the deb file name is a problem, it would help to show it on the download page. Before I switched to the PPA I would have to download the deb package, view it's version, and then only install it if it was a newer version.

If the version number was shown on the home page or download button it would save a lot of time for people in the same position.

What is another way to check the latest version?

**Comment by thomasjo** [comment]
> What is another way to check the latest version?

@cjwelborn https://github.com/atom/atom/releases

**Comment by cjwelborn** [comment]
@thomasjo, thank you.

**Comment by TrueFurby** [comment]
@cjwelborn you can use https://github.com/atom/atom/releases/latest to get the latest stable version.

**Comment by cjwelborn** [comment]
@TrueFurby, thank you.
