### ISSUE TITLE
Why Atom installation requires .Net?

### ISSUE THREAD

**Issue by paulvi** [atom/atom#11308]
Why Atom installation on Windows requires .Net? Should not Atom/Electron be platform on its own?

**Comment by paulcbetts** [comment]
Because Squirrel.Windows requires .NET

**Comment by paulvi** [comment]
Do you mean https://github.com/Squirrel/Squirrel.Windows is used for Atom install and updates ?

**Comment by 50Wliu** [comment]
Yes.

**Comment by thomasjo** [comment]
I'm closing this since the question has been answered.
