### ISSUE TITLE
Manual checking for updates instead of automatic at startup

### ISSUE THREAD

**Issue by alok-mishra** [atom/atom#11318]
Please allow an option to not check for updates automatically whenever I open Atom.
This isn't the same as this issue: #1882 where you are still checking, but just not downloading.

I'm behind a corporate proxy which notices requests all the time from atom when I open it.
This isn't that great for people on mobile data plans either.

If we could instead just do the manual check for update when we choose to, that would be great. Thank you.

`Atom    : 1.7.0-beta2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
`

**Comment by entrptaher** [comment]
Hi, I got a nice workaround on my windows setup. 

I didn't want Atom to, 
- Update it everytime I start,
- Use net connections even when I didn't want to
- Add tcp connections when I didn't want to
- Disturb me when I was having coffee

So the workaround is do one of the following,
- Use cmd to open Atom, that won't trigger the updater. Just type atom and it'll open without anything to worry.
- Delete atom shortcuts from desktop and program files. Those shortcuts links to updater. We can add the shortcuts manually 
- Use the right click "Open with Atom", this also won't trigger the updater.
- Remove/Rename updater.exe from C:\Users\[user]AppData\Local\atom, we all can install atom manually by download and double=click Setup.exe :D

**Comment by alok-mishra** [comment]
Hmm.. I tried through the command line and checked, it still makes several connections to atom.io.  Right clicking and starting did the same number of connections.  In my case about 20 or so, probably based on plugins installed.   But I'm sure the renaming of update will work, thanks for the idea!

**Comment by alok-mishra** [comment]
Renaming Update doesn't work either.. Atom itself must be what checks.

**Comment by entrptaher** [comment]
TCP connection when everything is as is. Its downloading updates at full speed.
![before](http://i.imgur.com/nUaj5Lw.png)

When I flush the file, obviously the file won't run.
![Not Running](http://i.imgur.com/HzKdjNU.png)

So either I have to do this everytime to open Atom instead of clicking the shortcut,
![Opening Atom](http://i.imgur.com/kRVWSdZ.png)

Or, I can still use the shortcuts, but I have to find the shortcuts from desktop and start menu and just rewrite this part to **atom.exe**
![More Work](http://i.imgur.com/yfhcULD.png)

Then I open Atom anyway I like and voila,
![Atom CANNOT hog my net now](http://i.imgur.com/60RGOg4.png)

I hope you found that helpful.

**Comment by greencopper** [comment]
Why is this closed? The problem still exists, we need a clear disable feature.

**Comment by 50Wliu** [comment]
> Why is this closed?

The issue is still open?

**Comment by greencopper** [comment]
When I was here last the issue had been closed. Maybe by mistake?

**Comment by 50Wliu** [comment]
If it was closed and then reopened you would be able to see it in the issue history.  You must be thinking of a different issue.

**Comment by philliptmaddox** [comment]
1.18 is freezing for me repeatedly even in safe mode. After deleting Atom entirely and reinstalling 1.17 it works fine, so I feel confident that it's a bug with the new release.

However, the auto-update keeps jumping the install back up to 1.18 each day and halting my work.

**Comment by 50Wliu** [comment]
@philliptmaddox We're investigating slowdowns and crashes with the github package that was introduced in Atom 1.18.  To disable automatic updates, uncheck the "Automatically Update" option in the Settings View.
