### ISSUE TITLE
Mac OS GPU crash

### ISSUE THREAD

**Issue by Entwicklerpages** [atom/atom#11313]
### Description

On Mac OS X 10.9.5 Atom causes a crash of the GPU spontaneously. The crash happens in Mac Fullscreen mode and normal window mode. Happened three times at the same mac. The screen went gray and the mac didn't respond. Even keyboard shortcuts for killing Atom or shutting down didn't work. I must kill the mac with a long press on the power button. After the third time the mac had a hard drive failure and I need hours to revive him, so I'm afraid of using Atom or debugging it. But maybe others can solve the issue. 

If it helps, the crash happens always when I'm editing .less files. The first two times I tried to define a variable for a font-familiy, the third time I tired to set the font-familiy directly an it worked (even the autocomplete). But before or while I save the change Atom crashes.

Here are the kernel logs before the crash:

> 29.03.16 17:46:16,000 kernel[0]: [1:0:0] GPU HangState 0x00000000, HangFlags 0x00000006: IndividualEngineHang 0, NonEngineBlockHang 1, FenceNotRetired 1, PerEngineReset 0, FullAsicReset 1

Also there is a Atom Helper [Crash Report](https://gist.github.com/Entwicklerpages/fd89110d7c3c842eaae898238372afd1)

### Versions
I'm using Atom 1.6.0
I have installed the following packages:
* build@0.58.0
* build-npm-apm@0.10.0
* minimap@4.21.0
Mac OS X 10.9.5 - iMac Mid 2011
GPU: AMD Radeon HD 6970M 2048 MB

**Comment by lee-dohm** [comment]
Thanks for the crash report. I'll let the developers take a look at it.

I'm pretty skeptical that this has anything to do with Atom specifically. The stuff in Atom that works with the GPU is Chromium and I haven't heard of Chromium or Chrome crashing people's GPUs. Also, hard drives that fail often have days or weeks of intermittent problems preceding the failure ... so it could be that your hard drive was reading things incorrectly and the code damaged in the broken reads caused the GPU crashes.

If you have any information about this issue occurring on other machines than the one you mention, please let us know.

**Comment by Entwicklerpages** [comment]
Ok, I'm sorry that I waited so long. It was a fault in my graphic card (AMD Readon). The errors caused by that fault just happened when I used Atom. And the Atom Helper Log let me think it was an atom crash but it isn't. Sorry.

**Comment by lee-dohm** [comment]
Thanks for getting back to us. I'm sorry to hear that you had problems with your video card, it sucks. I hope everything is repaired now though :grinning:
