### ISSUE TITLE
Clicking on "Replace in selection" clears selection

### ISSUE THREAD

**Issue by bedge** [atom/atom#11321]
If I have a block of text selected and I want to replace something in that selection, if I click on the "replace in selection" button in the search controls, that clears the selection so that I have to re-highlight it.

**Comment by amytruong** [comment]
I have recalled this happening to me a number of times. Thanks for reporting as well!

**Comment by PhiLhoSoft** [comment]
Kind of +1. But, actually, I am not sure if this flag is useful. Most of the time, I just want to change unconditionally all occurrences in my selection, so a "Replace in selection" button, like the "Replace all" one, would be better.
For conditional replaces, I would rather use the regular replace and stop at the wanted bounds, anyway.
