### ISSUE TITLE
Find and replace in all project files

### ISSUE THREAD

**Issue by penafo** [atom/atom#11330]
This is not an issue but a feature request. Sorry if it already exists... I'm very new to Atom and still finding my way.

Is there a way to (or is planned to be added a) "Find and replace" in all project files **and/or ** "Find and replace in all opened documents" features like in Notepad++ ?

**Comment by Ben3eeE** [comment]
There is a way to find and replace in project, see the find and replace section http://flight-manual.atom.io/using-atom/sections/find-and-replace/ of the atom flight manual.

**Comment by 50Wliu** [comment]
Thanks @Ben3eeE.

**Comment by Ben3eeE** [comment]
Find and replace only in open tabs has an open issue: https://github.com/atom/find-and-replace/issues/241

Feel free to subscribe there for updates.
