### ISSUE TITLE
Reporting "incompatible native module" on non-existing transitive devDependency.

### ISSUE THREAD

**Issue by hedefalk** [atom/atom#11331]
I no longer can load my package on Atom beta 1.7.*

"Failed to require the main module of 'Ensime' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve."
- First of, this message doesn't tell me which module is problematic so I had to debug - wouldn't it be super easy to just report the failing module?
- apm rebuild doesn't help even when it succeeds.

Reported on my package https://github.com/ensime/ensime-atom/issues/221

I just went to hell and back replacing chokidar to a pre fsevent-using-node-pre-gyp failing apm rebuild in the thought that this was the issue.

The problem I have now it that Atom reports a transitive devDependency from grunt-ts on fsevents as incompatible. Debugging in package.js:

```
JSON.stringify(this.incompatibleModules)
"[{"path":"/Users/viktor/.atom/packages/Ensime/node_modules/ensime-client/node_modules/grunt-ts/node_modules/fsevents","name":"fsevents","version":"0.3.8","error":"Module version mismatch. Expected 47, got 46."}]"
```

This file doesn't even exist! grunt-ts is a devDependency to compile Typescript on ensime-client so it's not in there:

```
~/d/p/atom-ensime ❯❯❯ ll /Users/viktor/.atom/packages/Ensime/node_modules/ensime-client/node_modules/grunt-ts
ls: /Users/viktor/.atom/packages/Ensime/node_modules/ensime-client/node_modules/grunt-ts: No such file or directory
```

I see two issues:
- Atom is reporting issues on files that doesn't exist. Is it reading package.json including devDeps and constructing those paths just to confuse? Or is it cache? 
- Even if only failed on actual physical files in node_modules, my dev workflow with npm link (as described here http://flight-manual.atom.io/behind-atom/sections/developing-node-modules/) would be screwed since the transitive devDep would be there while developing.

**Comment by hedefalk** [comment]
Related: 
* https://github.com/ensime/ensime-atom/issues/220
* https://github.com/ensime/ensime-atom/issues/221
* https://github.com/strongloop/fsevents/issues/93#issuecomment-202830164
* https://github.com/mapbox/node-pre-gyp/issues/188

**Comment by hedefalk** [comment]
@lee-dohm because https://discuss.atom.io/t/failed-to-activate-because-native-module/27234/4

**Comment by lee-dohm** [comment]
Thanks @hedefalk ... I'll refer it to the dev team and see if I can get some :eyes: on it.
