### ISSUE TITLE
`script/build` fails while cloning nathansobo/node-plist due to “zero-padded file modes”

### ISSUE THREAD

**Issue by mkhl** [atom/atom#11335]
### Description

Trying to build Atom from a fresh clone fails, see [the error log][error-log].

While installing apm, cloning nathansobo/node-plist fails with the message: `error: object 3fa653483030560fd76ea99669255fa047882026: zeroPaddedFilemode: contains zero-padded file modes`.

[error-log]: https://gist.github.com/mkhl/3112bffc4d6562c1d369fe101b27abdf

### Steps to Reproduce

1. `git clone https://github.com/atom/atom.git`
2. `cd atom`
3. `./script/build` (I actually ran `env HOME=/Users/mkhl/.atom-dev  ./script/build --install-dir /Users/mkhl/Applications/Atom.app`)

**Expected behavior:** [What you expected to happen]
Atom builds

**Actual behavior:** [What actually happened]
While installing apm, cloning nathansobo/node-plist fails with the message: `error: object 3fa653483030560fd76ea99669255fa047882026: zeroPaddedFilemode: contains zero-padded file modes`
[See the full error log.][error-log]

### Versions

```
> git rev-parse HEAD
a058f3721f4ee888a643e2aff3af30a839056e4c
> atom --version
1.6.1
> apm --version
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.8.0
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65
```

This version of git is from Homebrew, the one provided by Apple behaves identically.
```
> /usr/bin/git --version
git version 2.6.4 (Apple Git-63)
```

**Comment by lee-dohm** [comment]
I was not able to reproduce this using Atom v1.8.0-dev-a058f37 on Mac OS X 10.11.4. I did a complete clean build using:

```shell
script/clean
script/build
```

My Git version is v2.7.3 from Homebrew.

**Comment by mkhl** [comment]
Even just cloning nathansobo/node-plist triggers the underlying problem for me…

```
> /usr/local/bin/git clone https://github.com/nathansobo/node-plist.git
Cloning into 'node-plist'...
remote: Counting objects: 289, done.
remote: Total 289 (delta 0), reused 0 (delta 0), pack-reused 289
error: object 3fa653483030560fd76ea99669255fa047882026: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
> /usr/bin/git clone https://github.com/nathansobo/node-plist.git
Cloning into 'node-plist'...
remote: Counting objects: 289, done.
remote: Total 289 (delta 0), reused 0 (delta 0), pack-reused 289
error: object 3fa653483030560fd76ea99669255fa047882026: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
```

@lee-dohm During `script/build`, are you cloning via HTTPS or SSH?

**Comment by lee-dohm** [comment]
@mkhl I'm cloning however `script/build` clones things during `script/build`. I ran only the two commands I mentioned above as you see them there.

**Comment by lee-dohm** [comment]
I also just tried it on its own:

```
$ git clone https://github.com/nathansobo/node-plist.git
Cloning into 'node-plist'...
remote: Counting objects: 289, done.
remote: Total 289 (delta 0), reused 0 (delta 0), pack-reused 289
Receiving objects: 100% (289/289), 916.98 KiB | 968.00 KiB/s, done.
Resolving deltas: 100% (116/116), done.
Checking connectivity... done.
$
```

No issues.

**Comment by mkhl** [comment]
Thanks for trying that.

I had previously globally enabled `transfer.fsckObjects`, disabling that lets me clone the repo.

I'll close this issue and open one over there.
