### ISSUE TITLE
High CPU usage when alt-tabbing on OSX

### ISSUE THREAD

**Issue by valerioformato** [atom/atom#11340]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Two Atom Helper processes get to high CPU usage after alt+tabbing in and out of Atom.
### Steps to Reproduce

For me it's not very clear how to safely reproduce this feature, but I'll try to give a description as complete as I can.

I have a large git project (~100k files) on my laptop SSD. The project is on a sparsedisk image (this was needed in order to have a case-sensitive filesystem) and is about 1.8G in size.

When I alt-tab to another application (e.g. iTerm2)  and then get back to atom for a few seconds the editor is unresponsive and these two Atom Helper processes go to 100% CPU. This behaviour was even worse before I deleted ~45G of data that was stored in the project folder (I can live leaving the data on a remote server, but it was nice to be able to test the code directly on my laptop...)

I'm including a startup CPU profile and two profiles during which I alt-tabbed to get the issue at least twice during the time spent profiling.

**Expected behavior:** [What you expected to happen]
Nothing

**Actual behavior:** [What actually happened]
The editor hangs for a couple of seconds
### Versions

Atom version 1.6.1

OSX Yosemite 10.10.5

[Archive.zip](https://github.com/atom/atom/files/199213/Archive.zip)

Hardware Overview:

  Model Name:   MacBook Pro
  Model Identifier: MacBookPro8,2
  Processor Name:   Intel Core i7
  Processor Speed:  2 GHz
  Number of Processors: 1
  Total Number of Cores:    4
  L2 Cache (per Core):  256 KB
  L3 Cache: 6 MB
  Memory:   16 GB

**Comment by methodbox** [comment]
[quote]
The project is on a sparsedisk image (this was needed in order to have a case-sensitive filesystem) and is about 1.8G in size.
[/quote]

You're using OS X, which means Mac, which means you can use the Disk Utility to set your file system *in OS X ** to be case-sensitive. Just FYI.
