### ISSUE TITLE
autosave package vs ctrl+s

### ISSUE THREAD

**Issue by Javacym** [atom/atom#11346]
on atom 1.6.0 or before, autosave only take a few second when lost focus to save a file, but why ctrl_s
take so long when save a file?

**Comment by lee-dohm** [comment]
From what I can see, they use the same mechanism for saving the files. So there shouldn't be a significant difference other than the natural variations in the time it takes to save files.

If you've got some measurements that show a problem that control for factors like:

1. First save in a session meaning that things like atom-beautify have to activate
1. Long-running format-on-save operations
1. Any other sort of on-save operation that takes noticeable amounts of time

then please open a new Issue and share the measurements. If you need help measuring things, you can see the [Debugging section of the Flight Manual](http://flight-manual.atom.io/hacking-atom/sections/debugging/).

I hope that helps answer your question!
