### ISSUE TITLE
Modified files remain marked in Atom after repo is commited

### ISSUE THREAD

**Issue by adambuczynski** [atom/atom#11358]
In Atom 1.8.0-dev-435dcc7, modified files remained marked as modified (e.g. coloured in the tabs and in tree view) even after a commit.

To reproduce: edit some files, commit the repository, go back to atom. The modified files remain coloured. Expected result is for them to lose their git status and revert back to unmodified.

This is on OS X 10.10.5

**Comment by adambuczynski** [comment]
Note that after doing another commit, the files that were previously marked become un-marked, and only the files from the last commit remain marked.

**Comment by ZombieHippie** [comment]
This issue is directly related to the [/atom/tree-view repository](/atom/tree-view), would you file this over there and close this?

**Comment by ZombieHippie** [comment]
This is interesting though:

> Note that after doing another commit, the files that were previously marked become un-marked, and only the files from the last commit remain marked.

**Comment by adambuczynski** [comment]
@ZombieHippie I wasn't sure if it was, because I don't know which Atom package is responsible for marking files with their git status. For example, it also affects the tabs, as they also color the files the same way. So it didn't seem like just tree view to me.

But if you still want me to post it there instead, I will.

**Comment by ZombieHippie** [comment]
@adambuczynski , oops, you're right! The tree-view uses the [provided from a core function.]( https://github.com/atom/tree-view/blob/492e344149bd42755d90765607743173bb9b7c0a/lib/helpers.coffee#L7)

**Comment by adambuczynski** [comment]
@ZombieHippie Seems to be fixed now since 1.9.0-dev-77dea79, so I'll close this

**Comment by adambuczynski** [comment]
This issue has returned in 1.9.0-dev-c4d4e0f

**Comment by kuldeepkumar123** [comment]
+1

**Comment by adambuczynski** [comment]
Haven't seen it happening anymore. Seems fixed in 1.10.0-dev-672cf6d

**Comment by adambuczynski** [comment]
This is a bit of a jojo issue. It has crept up again in 1.10.0-dev-748dbcd.

I won't close it anymore until it's properly looked at, because it might only be happening under certain circumstances that I'm not noticing.

**Comment by okdewit** [comment]
+1

Add files, commit, push -- files will just stay marked in the tree view, the tabs stay colored, and the line number / gutter area shows lines as edited. Both command line and ctrl-shift-B shows "nothing to commit, working directory clean". 

Restarting atom fixes the issue temporarily, until the next commit.

**Comment by okdewit** [comment]
in 1.10.0-dev-5533365, it seems that changing a *single* file in a repository marks ALL (non-ignored) files as modified. Committing the change clears everything (correctly).

**Comment by okdewit** [comment]
Tested again using 1.10.0-dev-0708140.
It seems the #12159 PR did indeed fix this, so I think this issue can be closed.

**Comment by adambuczynski** [comment]
Yes I haven't had it happen anymore, will close it again.
