### ISSUE TITLE
In Windows 10 when using "side" taskbar and snapping Atom window to the side it leaves some empty space at the bottom.

### ISSUE THREAD

**Issue by sftd** [atom/atom#11350]
Atom 1.6.2, Windows 10 (multiple screens).

In Windows 10 when using "side" taskbar and snapping Atom window to the side it leaves some empty space at the bottom.

![atom](https://cloud.githubusercontent.com/assets/3073859/14225869/8e2e7c78-f8d2-11e5-9560-a6f1ed3b410c.gif)

**Comment by 50Wliu** [comment]
Confirmed on Windows 10 x64, Atom 1.8.0-dev-4d52479.

**Comment by damieng** [comment]
Appears to now be fixed in master - quite likely as a result of Electron upgrades.
