### ISSUE TITLE
Atom Build and Install creates ~/.atom - Windows 10

### ISSUE THREAD

**Issue by ZombieHippie** [atom/atom#11359]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

After running the `script/build` process with specified install and build directories, atom still creates the `~/.atom` directory. I recommend this to be addressed, because **it inhibits the portability** of the application.

**It would be expected** that the `~/.atom` directory may be created when running the application, but not when installing, because it is necessary to change `$ATOM_HOME` environment variable to create portability, and in a portable environment, we cannot assume that the `~/.atom` has been created on first run.

### Steps to Reproduce

Atom is not installed, and your computer is in the state of never having Atom installed.

 1. Using Regshot take a snapshot of the files of the drives and the registry
 2. Run Atom's `"script/build" --install-dir ../atom-install --build-dir ../atom-build`
 3. Regshot after build and install to notice that the `~/.atom` directory has been created.

**Expected behavior:**

The only directories created are the build and install directories.

**Actual behavior:** [What actually happened]

The `%USERPROFILE%\.atom` / `~\.atom` folder is created with:
 * `~/.atom/.apm`
 * `~/.atom/compile-cache`
 * `~/.atom/.node-gyp`
 * `~/.atom/packages`

### Versions

master@f1cf66

#### ATOM
```
Atom    : 1.8.0-dev-f1cf66b
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

#### APM
```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.0.windows.1
visual studio 2015
```

#### OS
Windows 10 - Version 1511

**Comment by damieng** [comment]
How does creating the ~/.atom folder during a build affect running it as a portable application?

Do you have a scenario where you want to build and update your portable copy?  Or are you imagining that people would want an entire script\build'able version that is portable?

**Comment by ZombieHippie** [comment]
I want to have a fully scriptable portable install process, because I plan on building an educational editing environment as a series of packages on top of Atom. It would simplify the process of keeping each editor separated and we would not need to worry about whether the person installing Atom may already have had it installed or not.

In my situation, I view Atom very similarly to Electron, because you can build anything you want on top of Atom, and when it comes to that portability, I think it should strive to be "as portable as Electron is" (I understand this is a silly way to look at it) This way someone can have an entire Atom environment configured perfectly for TypeScript, but not have those plugins and keybindings interfere with a second installation dedicated to basic text editing.

**Comment by damieng** [comment]
In my opinion the build script should not install atom at all. Would that also work for you?

**Comment by ZombieHippie** [comment]
@damieng Would we be able to add a way to add build only in the cli script? Something like a `--build-only` flag, or separating the build and install tasks are initial thoughts.

This might have the side-effect of speeding up CI tests (even if only on the developers machine).

**Comment by damieng** [comment]
I'm tempted to just remove the install step entirely - it actually installs the atom.exe into c:\program files\Atom right now which is a holdover from days before it went into %appdata%.

**Comment by damieng** [comment]
Script\build now no longer installs by default.

If you specify build should install then it will create the ~/.atom folder as part of the installation process (setting up the shell integration etc) is performed by Atom itself.
