### ISSUE TITLE
atom freezes in windows 10 side-by-side if not resized

### ISSUE THREAD

**Issue by lukeapage** [atom/atom#11355]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

In windows 10, when starting a new atom that is already the right size to be in side-by-side and then dragging the window to one side, atom is frozen until the window is resized.

### Steps to Reproduce

1. Dock atom side by side
2. close atom
3. start atom - it remembers the size but is no longer docked
4. dock atom

Expected: Atom to continue working

Actual: Atom is frozen. clicks are registered and the titlebar updates but the ui is frozen.

I can consistently reproduce this all the time, every time if I follow the steps above. It is not 

### Versions

1.6.1

### Related Bugs

https://github.com/atom/atom/issues/9901 (no response to my request of re-opening)
https://github.com/atom/atom/issues/9616 - duplicate
https://github.com/atom/electron/issues/3501 - closed electron issue

**Comment by lukeapage** [comment]
I cannot reproduce the issue in chrome.

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.7.0 and not 1.6.0.  Apologies for not being clearer in #9901.

**Comment by lukeapage** [comment]
@50Wliu confirmed 1.7.0-beta4 works good.
