### ISSUE TITLE
Atom shortcut is removed from taskbar after update

### ISSUE THREAD

**Issue by Velesthau** [atom/atom#11364]
### Prerequisites

OS - Windows 8.1, shortcut to the Atom is added to task bar.

### Description

Periodically Atom shortcut disappears from the task bar. Looks like, this happens when the editor is updated. After every update I need manually add a shortcut to the taskbar.

### Steps to Reproduce

1. Install Atom editor
2. Wait for update

**Expected behavior:** 
No shortcuts are removed.

**Actual behavior:**
Shortcut is removed from the task bar.

### Versions

I do not remember version before update. Current is 1.6.2

**Comment by VesterDe** [comment]
It has been happening to me as well.

OS - Windows 10.

**Comment by damieng** [comment]
Some important changes were made in Squirrel (the updater) to handle this and they are included in 1.7.

**Comment by damieng** [comment]
To clarify the update from 1.6 to 1.7 should preserve the pinned task bar icons.
