### ISSUE TITLE
Atom is not maintaining the state

### ISSUE THREAD

**Issue by kamlekar** [atom/atom#11361]
This is a question actually.

I am opening some project folders through atom. When I restart the atom, the atom is being empty. Again, I am manually adding folders.

I even tried `reopen-last-item`, it doesn't do anything.

Please help.

**Comment by mnquintana** [comment]
When you restart, how are you opening Atom? (e.g. from the command line, from the Dock, from the Start Menu) What OS are you on? What version of Atom are you using? Can you reproduce this after quitting Atom completely and reopening it in safe mode? (`atom --safe`)

**Comment by kamlekar** [comment]
- I am opening from the Dock. 
- I am on Mac 10.11.1. 
- I was having version `1.5.2`. After this issue, I checked for updates and installed the latest update. 
- I also installed `remember-session` plugin, to manage sessions. (_now it seems to be working fine_)
- In future, if I found any issues related to it I will definitely post more info here.

Thanks.

**Comment by mnquintana** [comment]
You should uninstall `remember-session` – that package has been deprecated for awhile now, as its functionality is in Atom core. That probably was the root of your issues here. Glad things seem to be resolved! :smile:

**Comment by kamlekar** [comment]
I installed it because atom wasn't maintaining state. Tomorrow morning i
will uninstall remember-session and check again.

**Comment by kamlekar** [comment]
It happened again this Morning. I closed Atom editor on Friday evening and completely shut down my mac. After starting mac today(monday) morning, I opened atom, where I can't see the files which were kept open on Friday evening. (I am using the latest version of atom)

**Comment by arcticicestudio** [comment]
Have you checked if you disabled the **[ ] Open Empty Editor on Start** core setting?
![atom-ghi-11361-core-setting-empty-editor](https://cloud.githubusercontent.com/assets/7836623/14595845/ac47c2ec-0542-11e6-91c5-de2f330b0d6e.png)

**Comment by kamlekar** [comment]
Yeah it was selected :/ thanks. I think it was selected by default. 


![](http://i.imgur.com/IA6pjed.jpg)

**Comment by kamlekar** [comment]
Hey guys no mean bad just a joke image. I really like your contribution. :). I hope you guys will uncheck that setting by default.

**Comment by kamlekar** [comment]
This is happening again though the "open editor on start" checkbox is unchecked.

**Comment by Wouter33** [comment]
Happening here all the time. Really thinking of switching back to my old editor again, this is so frustrating. 

Happens here when i close the editor with the close button, close from the dock or force restart it and restart it just by clicking Atom in the applications folder.

Details:
- OS X 10.10.5
- Atom 1.7.3

**Comment by maxbrunsfeld** [comment]
@kamlekar @Wouter33 How are you closing Atom?

When you close a window with the close button, it is not supposed to appear the next time you load Atom. The expected behavior is that you should see the same windows that were open when you *quit the app*. So if you close a window with the `x` button, and then quit the app, Atom has no windows to restore the next time it is opened.

Please let me know if I'm misunderstanding what you're doing.

**Comment by kamlekar** [comment]
I might have closing the app and then quit, not sure. and I am not an owner
of Mac anymore.  Anyway, why such rule to just quit the app without closing
to maintain state?

**Comment by maxbrunsfeld** [comment]
> why such rule to just quit the app without closing to maintain state?

Basically, Atom remembers the state from when you last used the app. If the last time you used the app, you closed all of the windows, then Atom will remember that no windows were open.

**Comment by kamlekar** [comment]
@maxbrunsfeld  Thanks for explanation. I think closing the app shouldn't be handled like that. `Close` and `Quit` are two similar terminating states of an app in users' perspective, imo. It seems bug but not a feature to me.

**Comment by Wouter33** [comment]
It is still happening. I don't close individual window panes, after a hard reset of the computer, or sometimes a normal quit of the app all projects disappear from the projects pane and the windows are closed on the next start. Just an empty editor.

**Comment by mnquintana** [comment]
@kamlekar This is how window management and state restoration work on macOS – `Close` and `Quit` are not semantically similar on macOS, like they are on Windows and Linux. `Close` only closes the active window, while `Quit` is what actually quits the app. If you've encountered other Mac apps that quit on `Close`, then they're doing it wrong. 🙈 

If closing all windows, then quitting, didn't clear the saved windows, then the same window would open upon launching Atom forever. This is how all document-based native macOS apps that `Quit and Keep Windows` work.

It might take some getting used to, but it's more idiomatic to just `Quit` Mac apps instead of closing all their windows first.

Hope that helps!

**Comment by mnquintana** [comment]
@Wouter33 That sounds like a different issue – can you do a search for other existing issues that describe what you're running into? I think there might already be an open issue for that.

**Comment by Wouter33** [comment]
@mnquintana The issue which @kamiekar is describing in the opening post is that the projects disappear. The discussion about close vs quit on mac is irrelevant for the issue described in my opinion. 

Irrelevant of quit or close, projects should never disappear unless you remove them deliberately from the pane.

**Comment by kamlekar** [comment]
@mnquintana  thanks for explanation. It might take time for windows user to understand that concept on Mac. Anyway, I can't help you guys as I am not Mac user anymore. 

@Wouter33 according to their explanation. Mac counts closing the app also as state. So, if you want to maintain the state then you should always quit the app directly. That is how Mac works.
