### ISSUE TITLE
'Open with Atom' in Github Desktop conflicts with Update procedure

### ISSUE THREAD

**Issue by PascalPencil** [atom/atom#11360]
### Steps to reproduce

1. Run Atom
2. *Wait for an update for Atom becomes available while using the app*
3. Open Github for Desktop app
4. Right-click on a Repository in the sidebar of Github for Desktop
5. Click 'Open in Atom'

Command opens a second instance of the Atom app in the dock, which crashes and is completely unresponsive, right-clicking and selecting 'Options > Show in Finder' opens the folder of the repo you just commanded Github Desktop to open, there seem to be no files there (hidden or visible) that correspond with the second app.

Underneath the window of the second crashed instance, there is a screen suggesting to report the error, here is a screenshot of the whole situation:

<img width="1680" alt="screenshot 2016-04-04 13 32 11" src="https://cloud.githubusercontent.com/assets/3094044/14238257/bd2a0e78-fa69-11e5-831f-357b69645aac.png">

**Comment by joshaber** [comment]
Thanks @PascalPencil! This is one of the causes of https://github.com/atom/atom/issues/9559, so I'm gonna lump it in with that.
