### ISSUE TITLE
Delete dialog gets higher than screen height when deleting many files (multiple selection)

### ISSUE THREAD

**Issue by 0815fox** [atom/atom#11366]
... depending on how big your screen is. in my case 2560x1440.
I did a multi-selection with shift, to select like 100 files with long path names.
The Buttons were outside of visible screen area (Dialog higher than 1440).
-> Should introduce a scroll bar before the dialog exceeds screen size.
-> Should also increase horizontal size to avoid line breaks of files.

**Comment by Nokel81** [comment]
Agreed, only way to delete files is to hit enter. Which is a bother

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/atom/tree-view/issues/683. You may want to subscribe there for updates.
