### ISSUE TITLE
Column count to start at 0 rather than 1? Option to change

### ISSUE THREAD

**Issue by novice1985** [atom/atom#11371]
When analyzing certain files, it would be easier for me to read the first column as column zero as to stay consistent with what I'm doing. I understand this isn't beneficial to everyone, but perhaps a toggle option for where to start counting the columns (column 0 or column 1)?

**Comment by amytruong** [comment]
Hi! Do you mind opening this issue in the http://github.com/atom/status-bar repo? Thanks! 😄
