### ISSUE TITLE
Failed to load C:\Users\mohamads\.atom\keymap.cson

### ISSUE THREAD

**Issue by msaiyaff** [atom/atom#11378]
error message in atom - 
[stdin]:34:36: error: missing '
  'Ctrl-alt-l': 'editor:auto-indent'
                                   ^

keymap.cson file - 
# Your keymap
#
# Atom keymaps work similarly to style sheets. Just as style sheets use
# selectors to apply styles to elements, Atom keymaps use selectors to associate
# keystrokes with events in specific contexts. Unlike style sheets however,
# each selector can only be declared once.
#
# You can create a new keybinding in this file by typing "key" and then hitting
# tab.
#
# Here's an example taken from Atom's built-in keymap:
#
# 'atom-text-editor':
#   'enter': 'editor:newline'
#
# 'atom-workspace':
#   'ctrl-shift-p': 'core:move-up'
#   'ctrl-p': 'core:move-down'
#
# You can find more information about keymaps in these guides:
# * https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings
# * https://atom.io/docs/latest/behind-atom-keymaps-in-depth
#
# If you're having trouble with your keybindings not working, try the
# Keybinding Resolver: `Cmd+.` on OS X and `Ctrl+.` on other platforms. See the
# Debugging Guide for more information:
# * https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings
#
# This file uses CoffeeScript Object Notation (CSON).
# If you are unfamiliar with CSON, you can read more about it in the
# Atom Flight Manual:
# https://atom.io/docs/latest/using-atom-basic-customization#cson
atom-text-editor':
  'Ctrl-alt-l': 'editor:auto-indent'

**Comment by thomasjo** [comment]
@msaiyaff  If the last block
```cson
atom-text-editor':
'Ctrl-alt-l': 'editor:auto-indent'
```
is what you've got in your keymap file, then the first line is missing a `'`. The corrected version should look like this
```cson
'atom-text-editor':
  'ctrl-alt-l': 'editor:auto-indent'
```

I'm assuming this is your problem, so I'm closing this as a user error, not an issue with Atom itself.
