### ISSUE TITLE
CPU is being pegged by opening an empty file

### ISSUE THREAD

**Issue by stvn** [atom/atom#11379]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Posted tonight on Slack and spoke with @lee-dohm who directed me to create an issue here.  Lee asked me to try in safe mode and to try after closing the application and deleting `~/.atom/storage`

i've been seeing some strange behavior in atom (v1.6.2) the last 3 days on my mac(10.10.5) -- the editor starts overheating my laptop, cpu just gets overloaded.  Couldn't figure out what it was and today I long-clicked on the atom icon in my doc and I'm seeing this -- it shows that I have a bunch of buffers open, however, i do not have any buffers open at all.  Any idea how to reset this? I think this is causing the problem.

Here's a link to the image I posted on slack: https://files.slack.com/files-pri/T043R3J9D-F0YAGBL8Z/pasted_image_at_2016_04_05_08_44_pm.png

You'll see a list of files that it says I have open. I have no files open.  I believe there is a connection between references to those files and the CPU spike.  Any suggestion how to kill those pointers would be awesome.

I've also tried re-installing the application; this did not fix the issue.

### Steps to Reproduce

i have no steps to reproduce.  This is happening when I open the editor to any file, any project, or even an empty file.  Just leaving the editor open without doing anything will cause the cpu to spike and the editor will become unresponsive and a force quit is required.

**Comment by lee-dohm** [comment]
One thing I didn't think of last night because I was 🍳 ... depending on the Elixir package you're using, this could be because you have the path to your Elixir or Erlang binaries set wrong. Try opening the Developer Tools using <kbd>Shift+Cmd+I</kbd> and selecting the Console tab. Then when you let things sit, if I'm right, you'll see errors from the Elixir package.

**Comment by stvn** [comment]
@lee-dohm you're exactly right.  Something is in an external loop and throwing errors because of a path issue:  `CLOSED 126, Last Error: /usr/local/bin/elixir: line 109: exec: /usr/local/bin/erl/erl: cannot execute: Not a directory`.  Thanks a ton.  I'll find out where this is happening and fix it.  I appreciate the help!

**Comment by lee-dohm** [comment]
Thanks for following up! I'm glad I was able to help :grinning:
