### ISSUE TITLE
"Uncaught (in promise) GitRepositoryAsync.destroyed: Repository has been destroyed" on spec runs

### ISSUE THREAD

**Issue by t9md** [atom/atom#11373]
#When I run spec, spec passes, but it put error like blow.

![image](https://cloud.githubusercontent.com/assets/155205/14286799/4dbc8944-fb8b-11e5-998b-49cfc1c823e4.png)

AFAIR this error start from Atom v1.6.2.
This error is not by my code change.

When I re-run previous spec(which was not includes this error in logs of previous run) via Travis-CI, new result includes this `Repository has been destroyed` error.
This error is not my package specific, see [status-bar](https://travis-ci.org/atom/status-bar)

Minimum spec to reproduce error is below, spec passes but console.log put `Repository has been destroyed` error.
```
describe "git-repo-error", ->
  [editor] = []

  beforeEach ->
    waitsForPromise ->
      atom.workspace.open("sample").then (e) ->
        editor = e

  it "test", ->
    null
```

**Comment by 50Wliu** [comment]
/cc @joshaber 
This is also a problem with tree-view.

**Comment by joshaber** [comment]
@t9md I can't reproduce that on `master` with your minimum spec, though I do see it on `status-bar` and I'll fix it over there.

@50Wliu I don't see it on `master` with `tree-view`.

**Comment by joshaber** [comment]
Gonna leave this open to see if @t9md or @50Wliu can reproduce what they were seeing on `master`.

**Comment by t9md** [comment]
Thanks for checking this,
I can see error with the spec I put above in Atom v1.7.0-beta4 and v1.6.2, but can't check master immediately.
If you see error in Atom v1.7.0-beta4 and not see in master it would be OK.

**Comment by joshaber** [comment]
Confirmed I see it in v1.7.0-beta4 but not in `master` 👍

**Comment by t9md** [comment]
Nice! Thanks!

**Comment by 50Wliu** [comment]
I no longer see the tree-view error messages on master, either.
