### ISSUE TITLE
Characters were changed after saving file without modifying

### ISSUE THREAD

**Issue by skilliscode** [atom/atom#11372]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When open the following file and save it without any modifying, some unicode characters were changed.
https://raw.githubusercontent.com/skilliscode/is-thirteen/6ccd4d73758a7121108a32bcbca945699cffcf99/index.js
### Steps to Reproduce

1. Open the file.
2. Save the buffer.

**Expected behavior:** Should not change the file content.

**Actual behavior:** Lines 44, 83, 215 were changed.
### Versions

atom 1.6.2
apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.4
OS X EI Capitan 10.11.3 (15D21)

**Comment by baaltommysu** [comment]
I have the same issue. 

Every time I open a file with Atom, and save the buffer without modifying anything, it shows the file is modified. 

The Atom version is 1.6.2

**Comment by Ben3eeE** [comment]
The lines 44, 83 and 215 all end with whitespace. Is the change only the removal of this whitespace? Check the "Remove Trailing Whitespace" option in the Whitespace core package. With this option set these lines will be changed on save and the whitespace removed.

![trailing whitespace](https://cloud.githubusercontent.com/assets/1058982/14382164/11d33a06-fd8c-11e5-87df-d5bb114d5fb7.PNG)

**Comment by skilliscode** [comment]
@Ben3eeE it works after uncheck the Remove Trailing Whitespace option in Whitespace package's settings.
