### ISSUE TITLE
Atom deletes the files from disk 

### ISSUE THREAD

**Issue by dineshappavoo** [atom/atom#11375]
### Prerequisites

* [ N] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [Y ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [Y ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Y ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]
I am using atom in mac. It deletes all the opened files from disk. When I try to close the opened files, it asked me to save the file which i didn't change in the editor. And I saved it . Then it deleted all the other files which was not opened[active] in the editor from disk. Is there a way to recover the files. It is my one month project work. I desperately want those files.
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Should not delete files even in the worst case
**Actual behavior:** [What actually happened]
I am using atom in mac. It deletes all the opened files from disk. When I try to close the opened files, it asked me to save the file which i didn't change in the editor. And I saved it . Then it deleted all the other files which was not opened[active] in editor from disk. 
### Versions
1.6.0
You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by 50Wliu** [comment]
If your issue doesn't happen in safe mode, that means a package is causing the issue.  You can use the [package-cop](https://atom.io/packages/package-cop) package to try and identify which package is causing this.
