### ISSUE TITLE
Tab guides are not aligned

### ISSUE THREAD

**Issue by cjduncana** [atom/atom#11389]
### Description

![Failed Identation](https://cloud.githubusercontent.com/assets/1977082/14328659/477a704c-fbfd-11e5-8228-d572aad897b6.png)
Whenever there is an empty line between my indented code, the tab guides are not aligned. I have my tabs indented as for four spaces, but the tab guides in the empty lines show three spaces. I do not see where in the settings this can be removed, since it is visually unappealing and distracting.

This problem is reproducible, both in and out of safe mode. This is a bug I have noticed since I have been using this program. I have only used v1.6.2. 
### Steps to Reproduce

![Animated Failed Identation](https://cloud.githubusercontent.com/assets/1977082/14328607/0c01338e-fbfd-11e5-9682-869f49134b49.gif)
1. Open the terminal
2. Run `atom --safe`
3. Press the `Enter` button five times to create five empty lines
4. Go to line 2
5. Press the `Tab` button twice to indent the code by two levels
6. Go to line 4
7. Press the `Tab` button twice to indent the code by two levels

**Expected behavior:** I expect that the tab guides are all aligned.

**Actual behavior:** The tab guides show different spacing depending if there is code or not. If there is code, it will indent four spaces per tab, if not, it will indent as if three spaces per tab.
### Versions

Atom.io 1.6.2
Ubunto 15.10

**Comment by Ben3eeE** [comment]
Refs https://github.com/atom/atom/issues/9369

**Comment by cjduncana** [comment]
I did what was suggested in #9369 regarding changing font-size, and the maligned tab guides just scaled with the changing size.

**Comment by cjduncana** [comment]
I do not see this problem anymore.
