### ISSUE TITLE
Atom Crashing in Ubuntu 14.04

### ISSUE THREAD

**Issue by kartikjagdale** [atom/atom#11380]
Atom suddenly crashed and now I can't open any projects.
Tried re-installing atom, but still the problem persists. 
Any suggestions on how to fix this issue?
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by 50Wliu** [comment]
Please try removing the `~/.atom` folder and trying again.

(Also, in the future, please try to fill out the provided issue template.)

**Comment by kartikjagdale** [comment]
Thank You it worked! Also next time I will keep in mind  to fill out the provided issue template.

**Comment by MiguelSalas1987** [comment]
removing the ~/.atom folder worked for me also

**Comment by abhijitgujar86** [comment]
where can i find ~/.atom folder in ubuntu 14.04 (new to linux)

**Comment by abhijitgujar86** [comment]
never mind got it . its working now .

**Comment by MiguelSalas1987** [comment]
~ (tilde) represents the home directory of the user in linux, so this '~/' is the same as your 'home/'

**Comment by YuehChuan** [comment]
Thanks @50Wliu !!! sudo rm -r .atom  also works for me!
original issue
![atom_crash](https://cloud.githubusercontent.com/assets/7314531/22060670/adf20ec0-ddac-11e6-84ba-ff5299272ed0.png)

**Comment by cigotete** [comment]
a note about to remove ~/.atom folder. This way seems is deleted customizations made to the editor (plugins added, custom styles, changes at settings).

**Comment by msssingh0** [comment]
removing the ~/.atom folder worked for me also. Thank you
