### ISSUE TITLE
No Linux x86 deb package

### ISSUE THREAD

**Issue by tol182** [atom/atom#11382]
Cmon guys, really no deb package for 32 bit linux? Is that hard to do?

**Comment by Nikki1993** [comment]
x86 architecture has become obsolete. Even Google will drop support for 32bit packages for Ubuntu and Fedora. I don't think it's particularly hard to support 32bit, but I assume there is only a handful of users using that so no reason to support old infrastructure.

**Comment by vharsh** [comment]
@tol182 Do you have an x86 processor?

**Comment by tol182** [comment]
Well, i do
Anyway, i've found a replacement - Sublime Text + Komodo Edit
PS: i know that one can compile from source (what i actually did), its just convenient for end-users to have a single installation file

**Comment by franlu** [comment]
:+1:  deb package for 32 bit linux  :+1:

**Comment by mnquintana** [comment]
This looks like a duplicate of https://github.com/atom/atom/issues/6252 – feel free to subscribe there for updates!
