### ISSUE TITLE
Cannot install packages (ETIMEDOUT) tried various fixes and keep getting "atom command not found" in CL. Not in path either.

### ISSUE THREAD

**Issue by TheProjectMarch** [atom/atom#11387]
Hello, 

preface: I'm horribly new to this whole world of command lines, prompts and consoles... I've read other threads and some things just flew right over my head. I followed along and tried as much as I could but to no avail. 
[thread 1: Issue #4902 ](https://github.com/atom/atom/issues/4902)
[thread 2: Issue #11164 ](https://github.com/atom/atom/issues/11164)

### Description

cannot install packages nor themes. I try and it continuously times out and when I try various things (as far as I understand them) in the terminal, I get bupkis. 

I installed atom today. 

* version: 1.6.2
* OS: Win7 64bit
* terminals: Cygwin, Git Bash

**Expected behavior:** 

I expect packages to be installed, themes to be installed, and for my terminal to recognize that atom is a thing. 

**Actual behavior:** 

I tried installing both packages as well as a theme or two. Keep getting this error. 

```console
Installing “atom-monokai@0.10.1” failed.Hide output…
Unable to download https://www.atom.io/api/packages/atom-monokai/versions/0.10.1/tarball: connect ETIMEDOUT
```

output from console

```console
Installing theme atom-monokai failed Error: Installing “atom-monokai@0.10.1” failed.
    at C:\Users\Trading\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:457:21
    at exit (C:\Users\Trading\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Trading\AppData\Local\atom\app-1.6.2\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Trading\AppData\Local\atom\app-1.6.2\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) Unable to download https://www.atom.io/api/packages/atom-monokai/versions/0.10.1/tarball: connect ETIMEDOUT
```

upon reading those other threads I tried several things including 

* using apm directly
* checking the version
* just opening atom 
* which atom

Here are the results

```console
$ apm install atom-monokai
bash: apm: command not found

$ atom --version
bash: atom: command not found

$ atom.cmd --version
bash: atom.cmd: command not found

$ which atom.exe
which: no atom.exe in etc...etc...
```

### Versions

*"You can get this information from executing `atom --version` and `apm --version` at the command line. "*

No... I in fact cannot do such miraculous things. 

### Conclusion

HAAALP. 

My apologies in advance for being a problem child that doesn't know all about environment variables and bash and shells to the point y'all do. It seems I'm gonna need me some hand holding.

**Comment by damieng** [comment]
Do these commands work fine from a regular Windows shell such as Command Prompt or PowerShell?

**Comment by wasifhossain** [comment]
those commands seem to work if I set the environment variable with 2 explicit directories;
 - C:\Users\<username>\AppData\Local\atom\app-1.6.2
 - C:\Users\<username>\AppData\Local\atom\app-1.6.2\resources\cli

output:

```
$ atom --version
1.6.2

$ atom.cmd --version
1.6.2

$ which atom.exe
/c/Users/<username>/AppData/Local/atom/app-1.6.2/atom.exe
```

**Comment by damieng** [comment]
Do you have the folder C:\Users<username>\AppData\Local\atom\bin ? It should contain four files;

- atom
- atom.cmd
- apm
- apm.cmd

**Comment by wasifhossain** [comment]
No. I don't have any such folder `bin` under `atom` directory. Rather I have those files allocated in different folders:

```
C:\Users\AppData\Local\atom\app-1.6.2\resources\app\apm\bin
 - apm
 - apm.cmd

C:\Users\AppData\Local\atom\app-1.6.2\resources\cli
 - apm.cmd
 - apm.sh
 - atom.cmd
 - atom.js
 - atom.sh
```

**Comment by damieng** [comment]
The bin folder is normally the one added to the path and the commands in there just act as stubs for the ones in the app-1.x.y\resources\cli folder.

This isn't the first report we've seen about these bin files missing - going to investigate why they aren't there.

**Comment by wasifhossain** [comment]
@damieng I have just triggered a [pull request](https://github.com/atom/flight-manual.atom.io/pull/189) by updating the atom installation section in windows.

**Comment by damieng** [comment]
Grouping the various 'bin' folder, contents and path missing issues into https://github.com/atom/atom/issues/11450
