### ISSUE TITLE
New files opening within same tab

### ISSUE THREAD

**Issue by jamr-ron** [atom/atom#11386]
* [No - but the problem is intermittent, I cannot consistently reproduce the bug, and therefore I cannot determine if it wouldn't happen in safe mode as I have to work and can't spend too much time testing ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ yes] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [yes ] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [yes ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [I hope so] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [yes - no results ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

To open a file I click on it on the left hand tree view and a tab opens with the file (ex. test.js).
Then I select another file in the tree (new.js) on the left and click on it.
Sometimes the new.js opens and test.js closes (giving the appearance that new.js is opening in test.js), and sometimes new.js would open in a separate tab.
Eventually clicking multiple times on multiple files will have them open separately.
I tried disabling all of my community packages - but that did not solve the problem. 
I then spent a good amount of time disabling core packages, but got inconsistent results. This bug would happen with certain packages on or off, and I was not able to identify a particular package that was causing the bug.

### Steps to Reproduce

1. Open a file
2. open a separate file

**Expected behavior:** [What you expected to happen]
I expect a separate tab to open for the new file without closing the old one
**Actual behavior:** [What actually happened]
The old tab is closed and therefore I can't have more than 1 file open at a time
### Versions
1.6.2
You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by Nikki1993** [comment]
I think the "issue" you are having is actually a feature called file preview. When you open the file and do not make any changes in it, the name of the file is in italic letters, and then select another file, it will open the file in the same tab. You can lock the file by double clicking on its name/tab or by making changes to the file.

**Comment by jamr-ron** [comment]
Awesome thanks for resolving this for me! :)

**Comment by anseljh** [comment]
Hello! I have the same behavior, and this discussion helped me figure it out. Indeed, I have to double-click files in the tree to keep them. But I am pretty sure this "file preview" feature didn't happen before, and it's really counterintuitive behavior to me. Is there a setting that somehow got toggled on by mistake? How can I disable this?

**Comment by Nikki1993** [comment]
It's the default behaviour and I you can't disable it atm (not that I know anyway). You can submit a feature request.

**Comment by 50Wliu** [comment]
You can install the [single-click-open](https://atom.io/packages/single-click-open) package.
