### ISSUE TITLE
Splitting panes gives me an empty panel

### ISSUE THREAD

**Issue by vorillaz** [atom/atom#11381]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Open a file into Atom
2. Right click onto the editor.
3. Choose Split Right

**Comment by Ben3eeE** [comment]
Can confirm I have the same behavior in windows 7. Splitting from the tab bar duplicates the file and from the editor gives an empty pane.

**Comment by 50Wliu** [comment]
I assume this is because the pane split commands changed in 1.6.0 and weren't updated in some places.

@Ben3eeE please open a new issue on atom/tabs for that since one is coming from core, while the other one is from tabs.

**Comment by Ben3eeE** [comment]
@50Wliu I mean that the command in atom/tabs seems to work and splits the file in a new pane to the right. "Duplicates the file" was perhaps a poor choice of words. If the intended behavior is still to split the file or tab that the right click is on. The command in the editor opens a new empty pane on the right as this bug report suggests.

**Comment by warb12** [comment]
I am having the same problem. Windows 10 , atom 1.7.0. Any split produces a blank pane.

**Comment by stephenhandley** [comment]
Same problem on OSX 10.11.4 with Atom 1.7.1

**Comment by lee-dohm** [comment]
It seems that all of this may be the expected behavior of the commands updated in https://github.com/atom/atom/pull/7953.

**Comment by lee-dohm** [comment]
@vorillaz Can you specify what you expected to happen and what actually happens? Without that, this Issue isn't actionable.

**Comment by warb12** [comment]
So I expected the same behavior as before. i.e right mouse in the pane,
choose any pane split option. Get another pane view of the file I am
editing. If there is new options as in #7953 they should not change the
previous behavior. What good is a new empty pane? File new gives me that.

**Comment by stephenhandley** [comment]
I mean the split behavior before kinda sucked but I got accustomed to it and now I'm mad it's different.

**Comment by stephenhandley** [comment]
What's the best thing that could happen

**Comment by stephenhandley** [comment]
What's the worst thing that could happen

**Comment by stephenhandley** [comment]
Something involving rollerblades properly

**Comment by stephenhandley** [comment]
This is on you, dear dear maintainer

**Comment by stephenhandley** [comment]
Atom has failed me and I'm
Trying to file a formal complaint

**Comment by stephenhandley** [comment]
How do tabs work now

**Comment by stephenhandley** [comment]
I am so confused

**Comment by stephenhandley** [comment]
Please someone help send me a email with comprehensive warez

**Comment by stephenhandley** [comment]
No jk srsly trying here

**Comment by stephenhandley** [comment]
https://m.youtube.com/watch?v=ceOYYg4-YAI

**Comment by stephenhandley** [comment]
https://m.youtube.com/watch?v=KSC-8mxfXKI

**Comment by stephenhandley** [comment]
So maybe you should just split the existing pane into the new pane so as to limit user surprise

**Comment by stephenhandley** [comment]
Www.justkidding.guthub.gov

**Comment by warb12** [comment]
OK, I see #7953 <https://github.com/atom/atom/pull/7953>.  provides for new
behavior. The new way for old behavior iis " pane: split Right And Copy
Active Item"  mapped to (Ctrl+K Right). I have used the
command-toolbar  package
to produce buttons that do what I want. I still think the right mouse menus
should be mapped to the "copy" version.

Is there an easy way to remap the function of the right mouse menu?

**Comment by warb12** [comment]
add this to your init.coffee file in ~.atom directory to restore old
behavior.

atom.contextMenu.add {
    'atom-text-editor': [
        {label: 'Split Up',    command:
'pane:split-up-and-copy-active-item'},
        {label: 'Split Down',  command:
'pane:split-down-and-copy-active-item'},
        {label: 'Split Left',  command:
'pane:split-left-and-copy-active-item'},
        {label: 'Split Right', command:
'pane:split-right-and-copy-active-item'}
        ]
            }

**Comment by BinaryMuse** [comment]
My 2¢, if this behaved differently before the new commands were introduced, we should replicate that behavior. I'm also very 👍 for making it consistent between right-clicking on the editor and right-clicking on the tab.

**Comment by lee-dohm** [comment]
I agree @BinaryMuse. I think the old behavior should be restored. It isn't clear that is what the original author was asking for though, so I'm wondering if there is more than one issue here.

**Comment by BinaryMuse** [comment]
@lee-dohm Ah, I'm assuming based on the title, but could be wrong.

**Comment by BinaryMuse** [comment]
I'm assuming this is fixed by #11498 but please feel free to reopen if I'm wrong.

**Comment by ricardograca** [comment]
What's the correct package to report this same issue but when splitting by using the application menus: View > Panes > Split ?

**Comment by 50Wliu** [comment]
@ricardograca Here.  Just create a new issue.
