### ISSUE TITLE
Failed to spawn command atom.exe

### ISSUE THREAD

**Issue by TITAN-UZ** [atom/atom#11390]
Hello how to fix problem 

```
Failed to spawn command C:\Users\MNU\AppData\Local\atom\app-1.6.2\atom.exe. 
Make sure C:\Users\MNU\AppData\Local\atom\app-1.6.2\atom.exe is installed and on your PATH
```
Error: spawn C:\Windows\system32\cmd.exe ENOENT
```
Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```
<a href='http://postimg.org/image/njg51l2ez/' target='_blank'><img src='http://s9.postimg.org/njg51l2ez/error.jpg' border='0' alt="error" /></a>

**Comment by 50Wliu** [comment]
@TITAN-UZ What is your path?  Open up the command prompt and type `echo %PATH%`.  In addition, does `which atom.exe` fail with an error or point to a file location?

**Comment by daftpanda** [comment]
same issue(s) here. path is correct on my side...

**Comment by damieng** [comment]
What are the repro steps?

**Comment by damieng** [comment]
Can you also try `atom --version` from a command prompt?

**Comment by DamirPecnik** [comment]
Do you have this in Atom Pack: Error: linter-csslint disable it and see if it will work?

**Comment by daftpanda** [comment]
`atom --version` shows `1.6.2`

> Do you have this in Atom Pack: Error: linter-csslint disable it and see if it will work?

disabled and error is gone =)

**Comment by damieng** [comment]
Is it a problem with the package? If so we'll close this issue here.

**Comment by daftpanda** [comment]
it seems to...
