### ISSUE TITLE
crashed on windows 10

### ISSUE THREAD

**Issue by satdav** [atom/atom#11392]
https://gist.github.com/satdav/dce23cd5c048c681a8443fb5976aafbc

This is the logs for the crash I have windows defender

**Comment by 50Wliu** [comment]
Please try disabling Defender and try again.

**Comment by rinetd** [comment]
I have disabed Defender, but this bug is also exist ...

**Comment by damieng** [comment]
Can you show a screenshot of the crash or the error message? The log looks okay.

**Comment by rinetd** [comment]
only atom 1.0.11 is ok
another Atom version will be crashed when opening a folder  which contains a git repository 
such as 1.7.0  ,1.7.4 beta , 1.8.0 beta  &etc....

**Comment by navilinux** [comment]
![error](https://cloud.githubusercontent.com/assets/5529191/16018714/4cffa2fa-316b-11e6-8121-7df26234866f.png)
 help me.. windows 10 32bits

**Comment by damieng** [comment]
Your path is too long.  I would recommend downloading the portable version and extracting it to a short path such as c:\atom
