### ISSUE TITLE
Using the treefile "New file" in a keyboard shortcut, it's really powerful

### ISSUE THREAD

**Issue by martiuh** [atom/atom#11409]
Instead of using the cmd + n (to open new file) and cmd + s (to save for the first time). It'd be great to just have a shortcut to use the right click in treefile "New File", It even makes folders wich is awesome.

![](http://i.imgur.com/Go39q4a.gif?1)

Sorry for bad gif, but I'm totally new and yes it was intended to show the whole tree

hello/world/itsa/me/mario.me

**Comment by Ben3eeE** [comment]
This command is already bound to "a" when tree-view has focus, if you want to add it to another bind, for example ctrl-n when you have anything focused add the following or similar to your keymap (Open your keymap from the file menu).

```coffee
'*':
  'ctrl-n': 'tree-view:add-file'
```
I used the command palette (ctrl-shift-p in windows) to find the name of the command to add to the keymap, alternatively you can check in the package specific settings, it should be there along with the default keybinding information.

For more information I can recommend reading the atom flight manual: http://flight-manual.atom.io/

**Comment by martiuh** [comment]
Thank you for the answer, I will read the manual.

**Comment by lee-dohm** [comment]
There is a package that does this (and has some other features too) called [advanced-open-file](https://atom.io/packages/advanced-open-file).

Thanks very much for the  feedback!
