### ISSUE TITLE
Package serialize function gets called on click in editor - 1.7 beta

### ISSUE THREAD

**Issue by mupchrch** [atom/atom#11408]
### Description

In 1.7 beta, it seems like the serialize function for every active package gets called when a text editor is clicked.

### Steps to Reproduce

1. Have a package installed that has a serialize function.
2. Put a console.log in the serialize function
3. Notice that the console.log is called every time that an editor is clicked.

**Expected behavior:** I am not sure, but I would think that serialize would behave like 1.6.

**Actual behavior:** Serialize function is called way too often I believe.

### Versions

1.7 beta on both Windows 10 and Mac OSX Yosemite

**Comment by Ben3eeE** [comment]
I believe this is intended with the new IndexedDB crash recovery logic introduced in 1.7, see PR/Comment: https://github.com/atom/atom/pull/10605#issuecomment-183150474

**Comment by mupchrch** [comment]
I agree, @Ben3eeE, that looks like what is going on. Thanks!
