### ISSUE TITLE
Problem displaying Chinese

### ISSUE THREAD

**Issue by newjie** [atom/atom#11400]
### Description

Normally my Atom has no problem displaying Chinese. But when I open this file http://w.nycweb.io/luanma.txt all Chinese characters are messed up.
### Steps to Reproduce

The file is originally a .html file. I copy some contents from a [webpage](http://blog.sina.com.cn/s/blog_6175bf700102wbc1.html) and paste it to WORD, then save as this html file. Notepad++ and Notepad have no problem displaying Chinese characters in it.

**Expected behavior:** [What you expected to happen]
This is what Notepad++ displays:
![normal](https://cloud.githubusercontent.com/assets/12814040/14370253/7f5304ae-fcfa-11e5-9ad2-bc474dcf62d7.png)

**Actual behavior:** [What actually happened]
And this is what Atom displays:
![atom](https://cloud.githubusercontent.com/assets/12814040/14370267/aab7ed8a-fcfa-11e5-94fb-978a569aa3e8.png)
### Versions

1.6.2@windows 10

I think this has something to do with the redundant html codes generated by WORD, but why does the codes affect how atom displays UTF-8 characters?

**Comment by 50Wliu** [comment]
@newjie Can you try opening up the Encoding Selector (<kbd>Ctrl+Shift+U</kbd>) and selecting "Auto Detect"?

**Comment by newjie** [comment]
It works, thanks.

Originally it was "UTF-8", same as Notepad++. I wonder why Notepad++ works while atom didn't

**Comment by 50Wliu** [comment]
Issue with encoding-selector not allowing Auto-Detect to be the default.
