### ISSUE TITLE
Application shortcut removed each time installing Atom on Windows

### ISSUE THREAD

**Issue by doberkofler** [atom/atom#11416]
### Description

It's just a small issue but it seems, as if each time in Update Atom, any existing shortcuts to Atom get removed or are no longer valid.

### Steps to Reproduce

1. Install Atom
2. Create a shortcut based on the newly created Atom icon
3. Update Atom the the Shortcut is gone

### Versions

Windows 7 x64
All the way up to Atom 1.6.2

**Comment by anechol** [comment]
I've noticed this as well. It isn't a huge problem, but more of an annoyance that I have to remove and replace the shortcut whenever Atom updates.

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.7.0.  Sorry for the inconvenience.
