### ISSUE TITLE
Rendering freezes when snapping window in Windows 10

### ISSUE THREAD

**Issue by cormac-obrien** [atom/atom#11415]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

The editor view freezes when snapping the editor window to either side of the screen in Windows 10.

### Steps to Reproduce

0. Start Atom.
0. Snap Atom to one side of the screen by dragging its titlebar to the edge of the screen.

**Expected behavior:** Atom should snap to the side and continue to function as usual.

**Actual behavior:** The cursor disappears and the editor view is not updated until the window is maximized.

### Versions
Windows 10.0.10586
Atom 1.6.2
apm 1.6.0
npm 2.13.3
node 0.10.40
python 3.5.1

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.7.0.
