### ISSUE TITLE
Atom Startup: It rarely starts.

### ISSUE THREAD

**Issue by kumarharsh** [atom/atom#11411]
### Prerequisites

* [Y] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [Y] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [Y] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [Y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom keeps showing these two messages when I open my project. Even starting with --safe mode *at least* shows those errors once or twice.

![1](https://cloud.githubusercontent.com/assets/760112/14395989/a89987f4-fdf2-11e5-8845-150b6e83fede.png)
![2](https://cloud.githubusercontent.com/assets/760112/14395988/a8998204-fdf2-11e5-8aa8-66292e7de802.png)

This is happening with the latest version of atom also (I can remember it happening significant number of times since 1.6.0). My project is about 1100 files in the `src` folder. It also has `node_modules`, `webpack` temp files, etc, but they are already in the ignore list.

I suspect it's due to the tree-view plugin, which causes atom to lock up every now and then when I expand/collapse a folder, and generally makes atom very sluggish.

### Steps to Reproduce

1. Open a project with 1000+ files in atom
2. Wait forever to edit
3. ![2](https://cloud.githubusercontent.com/assets/760112/14395988/a8998204-fdf2-11e5-8aa8-66292e7de802.png)
4. Click **Close Window** and try again.

**Expected behavior:** Atom shouldn't freeze so much.

**Actual behavior:** Sublime works smoothly. Atom should atleast let me edit the files.

### Versions
Version: 1.6.2 (1.6.0+)
OS: Windows 10 x64

**Comment by ZombieHippie** [comment]
Thank you for reporting @kumarharsh, we are always looking for specifics when it comes to performance issues. Would you be able to capture some profiling details for your issue by following [the profiling section of the debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-startup-performance-problems-with-the-timecop-package-and-the-code-profile-startup-code-command-line-flag)?

**Comment by 50Wliu** [comment]
This looks very similar to #1847.

**Comment by damieng** [comment]
This is directly related to the number of files in the project - let's track it on #1847 as suggested.
