### ISSUE TITLE
dialog boxes

### ISSUE THREAD

**Issue by cmdpwnd** [atom/atom#11422]
to improve speed and efficiency and continuity, dialog boxes such as those in which a user is prompted to delete a file should have standard Yes or No options which are accessible via the keyboard. This reduces time as the user does not have to click nor alter hand placement nor use multiple keys to accomplish this task. It also improves continuity in that much of Atom is currently designed for ease and maneuverability via simple keys and key combinations. Lastly it is more efficient in that it requires less work to physically achieve this goal emphasized by the speed/work ratio.

**Comment by 50Wliu** [comment]
Closing in favor of #2928 - feel free to subscribe there for updates.
