### ISSUE TITLE
Atom Helper Daemons consuming too much RAM

### ISSUE THREAD

**Issue by varunagrawal** [atom/atom#11423]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom creates multiple Helper daemons on startup, each taking up 150+ MB of RAM, causing my system to slow down and sometimes even hang, despite having 6 GB. Of course, the expectation is that I run other applications on my laptop as well.

### Steps to Reproduce

1. Run Atom
2. Check the Activity Monitor for RAM usage of the Helpers.

**Expected behavior:** Atom runs smoothly.

**Actual behavior:** Atom eats up all my RAM and hangs.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Atom : 1.6.2
Mac OSX: 10.10.5

**Comment by 50Wliu** [comment]
@varunagrawal I'm going to close this in favor of #1827.  Can you please follow [these instructions](http://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-startup-performance-problems-with-the-timecop-package-and-the-code-profile-startup-code-command-line-flag) listed in the debugging guide and report your findings to #1827?  Thanks.

**Comment by varunagrawal** [comment]
@50Wliu thanks!
