### ISSUE TITLE
Add global configuration for package backend.

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#11434]
Right now, running all of Atom against a different package API (for local development on the API within the Atom core team, or for future users that want to run against some kind of API-compatible alternate package index or mirror inside their firewall) is not super straightforward. `apm` will do the right thing with an env var, but if you [search the org](https://github.com/search?utf8=%E2%9C%93&q=org%3Aatom+%22atom.io%2Fapi%22&type=Code&ref=searchresults) you'll see it's hardcoded in more than a few places.

We should add a core config setting, env var override, or something that can be set in the console to provide the api root URL, and then update all packages to use it.

@atom/feedback

**Comment by Fank** [comment]
I totally agree with it. :+1: 
If we would make it configurable, we could introduce something like this (https://github.com/nolanlawson/local-npm)[local-npm] for atom.io (It would reduce traffic and solves internal proxy issues in companies).

**Comment by BinaryMuse** [comment]
@thedaniel This sounds good; there is already a setting (`core.apmPath`) to configure which apm to use, so maybe it makes sense to do similar with this

**Comment by xavieryao** [comment]
I'm one of the administrators of [Tsinghua University open source mirrors (TUNA)](https://mirrors.tuna.tsinghua.edu.cn) and we'd be glad to provide a mirror for atom.io if there exists a practical way to do so. And I believe that such a mirror will benefit a myriad of users and developers in China.

**Comment by lee-dohm** [comment]
@xavieryao Thanks for the offer! I've put it on the agenda for the next strategy meeting and I'll reach out to you if/when we get our ducks in a row for such an effort. Thanks again :grinning:

**Comment by lee-dohm** [comment]
@xavieryao We don't have a way to set up a mirror in any pre-packaged way. We are planning on looking into better CDN performance for atom.io, including apm, but I don't have an ETA for when that work will commence. Thanks for the offer and keep an eye on the [Atom blog](https://blog.atom.io) for announcements :+1:
