### ISSUE TITLE
Fail to build the atom-editor on ArchLinux

### ISSUE THREAD

**Issue by procuteboy** [atom/atom#11431]
### Prerequisites

- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
Unable to build the atom-editor since the apm installing error

### Steps to Reproduce

1.Installing the essential packages for building atom-editor, such as npm,nodejs and python3
2. Set python as python 2.7 ``export PYTHON=/usr/bin/python2`` as have installed python3 in computer already
set npm using python2.7 ``npm config set python python2.7``
3. run ``script/build``

**Expected behavior:**  build atom-editor completely

**Actual behavior:**  eror for apm installing(it must be something i haven't done)
```
Node: v5.10.0
npm: v2.13.3
Installing build modules...
=> Took 4288ms.

Installing apm...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)
npm ERR! Linux 4.4.6-1-MANJARO
npm ERR! argv "/usr/bin/node" "/home/spring/download/atom-1.6.2/build/node_modules/.bin/npm" "--userconfig=/home/spring/download/atom-1.6.2/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v5.10.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! atom-package-manager@1.6.0 install: `node ./script/download-node.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.6.0 install script 'node ./script/download-node.js'.
npm ERR! This is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/download-node.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/spring/download/atom-1.6.2/apm/npm-debug.log
```

### Versions

- `atom --v1.6.2`
- `node -- v5.10.0`
- `npm -- v2.13.3`
- `Os -- Manjaro`

**Comment by 50Wliu** [comment]
@procuteboy Can you try running `script/build` again?  It looks like there was a connectivity issue while downloading Node.

**Comment by othpiik** [comment]
Step to build atom on arch linux : 
Downloads latest version https://github.com/atom/atom/releases/latest

Install package needed : 
`sudo pacman -S --needed gconf base-devel git nodejs npm libgnome-keyring python2`

Use python2
`export PYTHON=/usr/bin/python2`

Checking latest Electron version from http://electron.atom.io/

Edit file package.json
line :
"electronVersion": "0.36.8",

change to :
"electronVersion": "0.37.5",

Build Atom:
`script/build`

then install : 
`sudo script/grunt install`

then re-build atom again, it's work on my Arch Linux.

**Comment by 50Wliu** [comment]
> "electronVersion": "0.37.5",

This is highly unrecommended.  If you insist on switching Electron versions I would only use 0.36.9.

**Comment by othpiik** [comment]
atom 1.7.0 with electron 0.36.x your atom will be crashed.  I had try it out a few times.

**Comment by procuteboy** [comment]
network error (not setting error)
I thought it's better to close it. 
 @50Wliu

**Comment by vyasriday** [comment]
On running script/build on my arch linux i get following error.

 sudo script/build
Node: v5.10.1
npm: v3.8.6
Installing build modules...
make: error while loading shared libraries: libatomic_ops.so.1: cannot open shared object file: No such file or directory
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 127
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hridayesh/atom-1.7.2/build/node_modules/minidump
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 4.4.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--userconfig=/home/hridayesh/atom-1.7.2/build/.npmrc" "install" "--loglevel" "error"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs minidump
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hridayesh/atom-1.7.2/build/npm-debug.log

Both npm and and nodejs are latest,

**Comment by othpiik** [comment]
Just build atom with normal user not SU.. let try again

run this
```
sudo pacman -S --needed gconf base-devel git nodejs npm libgnome-keyring python2
export PYTHON=/usr/bin/python2
```
then 
`script/build`
then
`sudo script/grunt install`
