### ISSUE TITLE
Selecting a file when a tab is selected closes the file in that tab!

### ISSUE THREAD

**Issue by smohadjer** [atom/atom#11432]
In latest version of Atom I have noticed that opening a file when a tab is already selected, replaces the file in that tab with the selected file. I'm not sure if it's a bug or a feature, but I find it very annoying, as I often have a tab selected when browsing through files and when Atom closes my files I have to search for them and open them again. Is there a way to avoid this?

**Comment by Ben3eeE** [comment]
Are you describing pending pane items? See https://github.com/atom/atom/issues/11243#issuecomment-199959295

**Comment by 50Wliu** [comment]
This does sound like pending items behavior, so I'm closing this issue.  @smohadjer please correct me if I'm wrong.

**Comment by smohadjer** [comment]
You are right, Thanks for the tip.
