### ISSUE TITLE
Holding down the tab-switching shortcut key should show a list of open tabs

### ISSUE THREAD

**Issue by axefrog** [atom/atom#11439]
If I have many tabs open, often a lot of them will appear to have the same title because the tab size is not large enough to display anything useful. Unless I hover the mouse over a tab title and wait a moment so that the tooltip reveals the path, tab switching becomes a bit of a guessing game.

![image](https://cloud.githubusercontent.com/assets/298883/14483064/538fc1d2-0186-11e6-8df3-374176fe69ab.png)

![image](https://cloud.githubusercontent.com/assets/298883/14483078/81fd647a-0186-11e6-9115-6f295a9ebc14.png)

Other editors show you a proper list of open documents/tabs when holding down the tab switching shortcut (CTRL+TAB for me on Windows). I can then easily cycle through the list directly to the tab I want to focus. The order of the list is usually the same as the current tab cycling order, rather than the ordinal position in the UI. i.e. the current tab is first in the list, the previous tab is next, and so forth.

Another common addition that usually goes along with this is either having a list of the open tabs available from a dropdown button on the tab bar, or in one of the application menus.

Visual Studio provides a good experience for this:
![vs2015-tab-switching](https://cloud.githubusercontent.com/assets/298883/14482958/89a2fad8-0185-11e6-8de5-ab850a65f16c.gif)

VSCode is also similarly helpful:
![vscode-tab-switching](https://cloud.githubusercontent.com/assets/298883/14483022/f631cd32-0185-11e6-95de-127edec3d3b4.gif)

Sublime Text exposes the tab list as a dropdown, but not when holding down the shortcut. Even so, it's still better than having to cycle through tabs guessing, or having to wait for each tooltip to display:
![image](https://cloud.githubusercontent.com/assets/298883/14482895/e454cef8-0184-11e6-880d-717a4efc710a.png)

**Comment by arcticicestudio** [comment]
Have you tried the [`tab-switcher`](https://atom.io/packages/tab-switcher) or [`expose](https://atom.io/packages/expose) package?

**Comment by axefrog** [comment]
@arcticicestudio Yes of course. But the Atom folks rolled contextual tab-switching into core because it's such a fundamental feature. My feedback is on that implementation.

**Comment by Ben3eeE** [comment]
@axefrog does https://github.com/atom/tabs/pull/388#issuecomment-262638283 implement the feature you were requesting?

**Comment by axefrog** [comment]
@Ben3eeE Sorry, can't confirm; switched to vs code some time ago after losing patience with Atom's poor performance.

**Comment by 50Wliu** [comment]
Closing because no further feedback is possible.
