### ISSUE TITLE
syntax highlighting quote issue

### ISSUE THREAD

**Issue by nbolt** [atom/atom#11445]
Syntax highlighting messes up with single quote in html.

<img width="1245" alt="screen shot 2016-04-13 at 10 39 07 am" src="https://cloud.githubusercontent.com/assets/857940/14497207/0ca8d410-0164-11e6-92ec-dcadb05ee919.png">

**Comment by 50Wliu** [comment]
This is not an issue with Atom - language-javascript does not support React.  I suggest for you to install language-babel instead.

**Comment by nbolt** [comment]
installing `language-babel` doesn't change anything.
