### ISSUE TITLE
Combo select box out of place.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#11446]
This is reproduced using safemode and official one-dark theme. latest commit 

![combo_outofplace](https://cloud.githubusercontent.com/assets/419606/14499540/bae3c26e-01c4-11e6-98ff-4c54ad534a23.png)

When theme selection combo box or syntax switching combo is clicked , the select box is out of place.

**Comment by amytruong** [comment]
Yikes. Can you let us know what OS and version you're on?
If there's any steps to repro that, that'd be great. (maybe resizing the windows?)

**Comment by Ben3eeE** [comment]
Refs https://github.com/atom/atom/issues/9579

**Comment by v3ss0n** [comment]
@amytruong   Yeah , I am using Sabayon (Gentoo) Linux .  I am testing around with layouts and seeting to compact fixes the problem. i think it happens in auto/spacious layouts.
