### ISSUE TITLE
Menubar items blurry

### ISSUE THREAD

**Issue by kostadinnm** [atom/atom#11442]
![2016-04-13__10_01_13-about atom](https://cloud.githubusercontent.com/assets/18436405/14485320/03b34926-015f-11e6-8ae6-13c0af2bbef2.png)
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I think it's self-explanatory. Could it be because of the Chromium engine - Visual Studio Code is having the same issue?!
Two disclaimers:
-I don't think this requires safe mode or debugging
-first-time contributor in GitHub(Markdown's still not my strength)

### Steps to Reproduce

**Expected behavior:** The font of the menu should be crisp and clear.

**Actual behavior:** The font of the top menu(the triggering text only) appears blurry. The cascade items that open are OK.

### Versions
Atom is latest 1.6.2, the OS is latest Windows 10 64bit with all the updates.

**Comment by Nikki1993** [comment]
4k Resolution by any chance?

**Comment by kostadinnm** [comment]
No, it's 1080p.

**Comment by Nikki1993** [comment]
Alright, cause I am using same atom version and Win 10 64bit and do not have such blurry fonts as you describe. Have you made any modifications to the fonts within Atom or system wide?

**Comment by kostadinnm** [comment]
No, but I could try some things to narrow down the cause:
1) I think, but not so sure, some fonts were bugging me the same way when I had been trying out the Chrome browser on the same machine(I'm using mainly Firefox). So, I could try Installing Chrome back and look around.
2) I'm using Remote Desktop to access that machine, so I may try out Atom ont the notebook I am using to ininiate the RD session. This, although with less chance(I enabled all the enhancements of the session, one of which is 'Font smoothing'), won't hurt.

Btw, I'm not just describing it - it's clearly visible from the screenshot.

**Comment by Nikki1993** [comment]
it is visible, clearly. I am either losing my vision or I do not see the same issue with my atom. Here is my atom 
![atom](https://cloud.githubusercontent.com/assets/1446529/14502026/f0875812-01b1-11e6-9598-a60c7cd23d7b.png)

**Comment by Nikki1993** [comment]
what the, now that I posted the screenshot the quality of the menu degraded as well, in the screenshot that is o_O

**Comment by kostadinnm** [comment]
Sorry, but I couldn't get this - do you find any difference or not?!
If I zoom to 100% the two screenshots, I find the font of both menubars blurry - as if it is not getting anti-aliased. Yours even have blurry fonts on other places.

**Comment by Nikki1993** [comment]
I, personally, do not see the difference. Maybe I grew accustomed to the font that's why I do not "see" any blur

**Comment by kostadinnm** [comment]
You must've adapted. I think it's everywhere, which is pity :( Look at this new screenshot - the dot of the 'i'-symbols and the thickness of the 'l'-symbols are different:
![2016-04-13 20_26_50-settings atom___about atom](https://cloud.githubusercontent.com/assets/18436405/14502998/b1b31248-01b6-11e6-9cc5-4c9584ef186c.png)

Again, I am not 100% sure, but I think it must be some general issue, I was having with the Chrome browser back than.

**Comment by kostadinnm** [comment]
Unfortunatelly, here it is in Chrome settings as well:
![2016-04-13 21_00_35-settings](https://cloud.githubusercontent.com/assets/18436405/14503963/381e3b60-01bb-11e6-982d-dae65203dc65.png)

It is the same on non remote desktop session(the laptop is connected to the monitor via an HDMI cable). Fresh installation of Chrome(32-bit) on both machines.

I'll try contact Chrome support for that. In the meantime, I'll be using something else for editing source code. Even though people don't spent that much time in the settings, IT people spent a lot of time with these tools in general. Rendering HTML might be great job by Chromium, but these settings' fonts are just bugging me. I hope they take it seriously.

**Comment by damieng** [comment]
What you're seeing is text rendered using sub-pixel positioning. It's an option available in the low-level DirectWrite windows font renderer and Chrome's renderer Blink chose to use that mode.

They are continually going back and forth and tweaking it so it's possible it will improve again as they tweak it and Atom take newer Chromium builds with those tweaks but there is not something we have direct control over.

**Comment by kostadinnm** [comment]
Thanks for the input. Although I havn't used Chrome much, I can't remember these fonts looking OK on my two machines.

As a side note, just for people not getting biased, I'm having issue with directwrite on one of the machines with Firefox as well. IE's ok on both, but slower, choppier and uglier(personal opinion).

I guess I should close the issue as unrelated or sth?!

**Comment by damieng** [comment]
Also try adjusting the ClearType on your machine to see if you can find something a little better for your eyes. Start Menu > Adjust ClearType Text.

Yeah we should close for now. I've been keeping an eye on Blink to see what changes they've been making to DirectWrite but it takes a while for them to make it into Chromium, new builds of Chromium to make it into Electron and new Electrons to finally make it to Atom.

**Comment by kostadinnm** [comment]
Even in the adjusting dialog I detect the blurriness(the boldest options). Do you think downgrading to Windows 7 will make the things better(I have another blocker with Firefox html5 videos choppiness on the laptop)?! I also tried 125% dpi, but I really don't like it, although fonts are a little better.

Wow, that stack is amusing.

As to what I read on the Internet, the issue is a blocker for normal dpi monitors - MS are pushing to high density displays and most 32-bit user programs are suffering from that. They say the fonts should be better on OS X, so I think trying out a virtual machine. Later, I may buy a Mac, although Apple were also mentioned to pay more attention to the ultra high dpi displays(their Retina's, of course).

I don't know - I just got even more confused.

**Comment by damieng** [comment]
I doubt Windows 7 will make anything different. Presumably the drop-down menu in Chrome is also bad for you?

I don't know it's a blocker for normal dpi monitors - how bad it is depends very much on your monitor settings, your eyes and viewing environments. Microsoft have been tweaking font rendering for quite some time and the reality is there is no one-fits-all.  I agree tho that it's not sharp enough for me.

Fonts on Mac OS X are a whole other issue. Right now they are using ClearType sub-pixel rendering but at a higher resolution that the screen then scaling down on their retina displays which I find terrible. Thankfully you can turn off their version of ClearType and it gets a bit better.

**Comment by kostadinnm** [comment]
Cross link to the Visual Studio Code issue:
https://github.com/Microsoft/vscode/issues/5217

**Comment by kostadinnm** [comment]
Just an appeal found while discussing the issue on the VSCode thread:
[Bring sharp fonts back in Google Chrome (Disable DirectWrite)](https://www.change.org/p/google-inc-bring-sharp-fonts-back-in-google-chrome-disable-directwrite)
Anyone teased by this should support the petition. If reconsidered, that kind of functional rollback should improve the typographic performance of chromium-based software on a lot of hardware!

**Comment by damieng** [comment]
That petition is inaccurate. It states 

>DirectWrite is incapable of giving the same look and feel as GDI, as you don't need glasses to see this in the comparison above.

First off. The comparison at the top is blown-out to exaggerate the difference.  More importantly however DirectWrite has a number of options when rendering text and in fact it CAN look very similar to GDI.  You only need to check out Visual Studio 2015 to see what the DWRITE_RENDERING_MODE_CLEARTYPE_GDI_CLASSIC mode in action.

This isn't however the default in Chrome today as it's primary purpose is rendering a mix of fonts, styles and sizes.  In a text editor that is typically used with a monospaced font DWRITE_RENDERING_MODE_CLEARTYPE_GDI_CLASSIC can make all the difference.

The effort would be better off allowing Chromium to expose DirectWrite font flags to applications that use it so it can be fine-tuned as appropriate. 

It's also worth reminding people that font smoothing is very gamma dependent and ClearType is especially sensitive to LCD characteristics. Windows includes a ClearType tuner you can use to find what works best for you through a series of steps (and remember each display is different so you may need to do it on each monitor you have).  

If you find ClearType too blurry you can still fall back to greyscale anti-aliasing by running the tuner and turning it off. If that turns off all smoothing entirely then go into Windows performance settings and turn font smoothing on to get greyscale AA (I do this).

Font rendering is often tweaked and adjusted between different versions of Chrome and you will find different versions of Atom change how they look as we pick up newer builds via Electron (current beta is locked on grey-scale but the next Electron build enables ClearType again)

**Comment by kostadinnm** [comment]
I agree(already expressed my doubts this petition 'smells' in the VSCode thread). 10x again for the technical dive.
