### ISSUE TITLE
The editor has crashed 1.7.0 fresh install on archlinux

### ISSUE THREAD

**Issue by othpiik** [atom/atom#11457]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

**The editor has crashed 1.7.0 fresh install on archlinux**
Image link : http://i65.tinypic.com/jgntyc.png

```
Deduping modules ✓
=> Took 72602ms.

Running "download-electron" task


Running "download-electron-chromedriver" task


Running "build" task

Running "babel:dist" (babel) task

Running "coffee:glob_to_multiple" (coffee) task
>> 334 files created.

Running "prebuild-less:src" (prebuild-less) task
>> 1891 files compiled, 0 files reused

Running "cson:glob_to_multiple" (cson) task
>> 172 files compiled to JSON.

Running "peg:glob_to_multiple" (peg) task
Generating parser from "node_modules/snippets/lib/snippet-body.pegjs"...
Parser "/home/oh/Downloads/atom-1.7.0/out/Atom/resources/app/node_modules/snippets/lib/snippet-body.js" generated in 46ms.

Running "generate-license:save" (generate-license) task

Running "generate-module-cache" task

Running "compile-packages-slug" task

Running "set-version" task

Running "generate-asar" task

Done, without errors.


Execution Time (2016-04-14 03:56:21 UTC)
loading tasks                        14s  ▇ 3%
download-electron               5m 27.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 61%
download-electron-chromedriver     43.6s  ▇▇▇ 8%
build                              43.1s  ▇▇▇ 8%
coffee:glob_to_multiple            17.7s  ▇ 3%
prebuild-less:src                1m 0.6s  ▇▇▇▇ 11%
cson:glob_to_multiple                 7s  ▇ 1%
generate-asar                      13.3s  ▇ 2%
Total 8m 53.4s

[oh@Oh-Notebook atom-1.7.0]$ sudo script/grunt install
[sudo] password for oh: 
Running "install" task

Done, without errors.


Execution Time (2016-04-14 04:05:51 UTC)
loading tasks  14.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 69%
install         6.6s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 31%
Total 21s

[oh@Oh-Notebook atom-1.7.0]$ atom

```

### Versions  
Arch-linux.x86_64

```
[oh@Oh-Notebook atom-1.7.0]$ atom --version
Atom    : 1.7.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

```
[oh@Oh-Notebook atom-1.7.0]$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.0

```

**Comment by lee-dohm** [comment]
Please try to reproduce this in Safe Mode. To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by othpiik** [comment]
trying to launch Atom with the command `atom --safe`

I am got same result  

> The editor has crashed

**Comment by hoangan** [comment]
My editor also keeps crashing after upgrading to 1.7, but on a Mac.

**Comment by Nikki1993** [comment]
@lee-dohm these crashes are probably related to same issues fixed by electron update PR https://github.com/atom/atom/pull/11348

**Comment by sdellow** [comment]
Also having the same issue on OSX 10.11.3. It happens when saving a file for me.

**Comment by yriveiro** [comment]
I'm upgrade to 1.7 today, the editor crashed too before 3 hours of work.

**Comment by garrows** [comment]
Crashing for me when saving a file. It also completely empties out a file completely. Very frustrating with uncommitted work. 
On OSX `10.11.4` 
Atom `1.7.0`
I haven't be able to reproduce when using `--save`.

**Comment by MingcongBai** [comment]
Same here on AOSC OS.

```
jeffbai [ ~ ] $ node --version
v5.10.1
jeffbai [ ~ ] $ npm --version
3.8.7
```

**Comment by othpiik** [comment]
To fixed this issues , before you run build from source will need to edit file `package.json`

line : 
`"electronVersion": "0.36.8",`

change to : 
`"electronVersion": "0.37.5",`

then re-build atom again, it's work on my Arch Linux.
```
[oh@Oh-Notebook atom-1.7.0]$ atom --version
Atom    : 1.7.0
Electron: 0.37.5
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by Nikki1993** [comment]
@othpiik don't just update electron to latest version. Atom still uses 0.36.x branch so it's much safer to update to latest bug fixing release 0.36.12 and on top of that, you will need to make changes in other files in order to avoid potential issues in the future. 

Refer to this PR https://github.com/atom/atom/pull/11348 for full list of changes.

**Comment by lcdss** [comment]
I followed all the build instructions and `atom` crashed all the time it is opened. Was solved updating Electron to last version (0.37.7) in `package.json`, as othpiik said.

Before:
```bash
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

After:
```bash
Atom    : 1.7.2
Electron: 0.37.7
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by 50Wliu** [comment]
**Please** please please do not naively upgrade Electron.  If you insist on doing so, upgrade **only** to Electron 0.36.9, which is the most conservative fix.  Otherwise, refer to #11348.

**Comment by othpiik** [comment]
I have no idea, why stay with old version of software?
Atom build from Electron base for cross platform apps.  latest stable version come with bugs fixed and improved performance, why not upgradeed?
and why you have not upgrade Atom ?
new version of atom come with   bugs fixed , right?
that is common reasons to upgrade Electron too..

Electron 3.6.x is slow performance even on Electron 3.6.12 also
bugs fixed come with Electron latest version 3.7.x  ..

anyway guys, pick once fit your work.

PS: upgrade latest version of stable version only, do not use beta version it's only for testing!

**Comment by Nikki1993** [comment]
@othpiik because Atom is by far one of the largest electron apps built to-date. Simple upgrade of Electron can introduce 

- Regressions
- Unexpected behaviour due to API/ABI change
- New Bugs
- Etc

![electron](https://cloud.githubusercontent.com/assets/1446529/14786126/1ea1b848-0b06-11e6-9d54-f5f2469d705a.jpg)

While I share your frustration about how slow this process is, I also understand devs point of view. One little bug fixed, may introduce 100 more. Testing is not a recommendation, it is a requirement in building big, stable apps.

**Comment by 50Wliu** [comment]
We are working on updating Atom to the latest Electron versions, but we first need to make sure no regressions have been introduced.
