### ISSUE TITLE
Strange Problem

### ISSUE THREAD

**Issue by akshar-patel** [atom/atom#11458]
### Description

Adding just one line in file modifies other lines even when we don't touch other lines.

### Steps to Reproduce

1. Open this file in Atom : https://github.com/udacity/create-your-own-adventure/blob/master/language.md
2. Append newline at the end.
3. Save and run 'git diff'

**Expected behavior:** 
I expected only a new line to be added.

**Actual behavior:**
Other lines get modified.

### Versions
1.6.2

### How did I solve?
I added the line using Vim and it worked perfectly.

**Comment by Ben3eeE** [comment]
Some of the lines in this file end with a whitespace character. Is the changes in the other lines only the removal of this whitespace in the end of these lines?

Check the settings in the whitespace core package, specifically the "Remove Trailing Whitespace" option.

**Comment by akshar-patel** [comment]
@Ben3eeE Please, follow above steps. It will not take more than 2 mins if you have already installed Atom.

**Comment by Ben3eeE** [comment]
@akshar-patel I think it is best if you show what your output of `git diff` is because there are many settings that will cause different results.
Did you try in safe mode and see if you got the same diff?

**Comment by despairblue** [comment]
What I see is that atom removes the trailing whitespace (and the linked file contains a lot of those). If you don't need or want that feature try to disable it in the settings: 

![screen shot 2016-04-14 at 15 12 09](https://cloud.githubusercontent.com/assets/927609/14529114/4f991e02-0253-11e6-9790-9dcc876ddf35.png)

Are there any other issues after disabling theses settings?

**Comment by akshar-patel** [comment]
I disabled this package.
![selection_006](https://cloud.githubusercontent.com/assets/18311126/14529390/f7dc681c-0271-11e6-8efa-5fb15b93ff37.png)
Appended new line "testing"
![selection_007](https://cloud.githubusercontent.com/assets/18311126/14529411/16adb278-0272-11e6-94f5-756f2173e892.png)
Still the last line showing up as deleted and then added again although I have only added "testing"
![selection_005](https://cloud.githubusercontent.com/assets/18311126/14529428/2b62ac3c-0272-11e6-9629-b6a7548ede14.png)

**Comment by 50Wliu** [comment]
Please restart Atom after disabling the Whitespace package and try again.

**Comment by akshar-patel** [comment]
OK. working after restart. Thanks.
