### ISSUE TITLE
Command line `atom .` opens wrong directory

### ISSUE THREAD

**Issue by okonomiyaki3000** [atom/atom#11454]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Opening the current directory from the command line using `atom .` instead opens the root directory.  
This happens when using MSysGit or MSys2 but not from the native windows command line. 
I should also note that opening a directory other than `.` does work, for example: `atom $(pwd)` and 
`atom ~` both seem to work as expected.

### Steps to Reproduce

1. Use the command line (Bash, Zsh, whatever you like) in either MSysGit (Git for Windows) or MSys2.
2. Go to some directory.
3. Run `atom .` 

**Expected behavior:** Atom will open a new window with the current directory.

**Actual behavior:** Atom opened a new window with `D:\`.

### Versions

Only since 1.7.0 - was working as expected before.

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by damieng** [comment]
Just tried this in msys2 and it is working as expected. What version of the bash are you running? 

```bash
damien@desktop MSYS /d/src
$ atom .
```

![image](https://cloud.githubusercontent.com/assets/118951/14539168/1fa00c70-0234-11e6-8e3a-c9b31b56e374.png)

**Comment by okonomiyaki3000** [comment]
I'm mainly using zsh zsh 5.1.1 (x86_64-pc-msys) but I have the same trouble with bash 4.3.42(5)-release (x86_64-pc-msys). 

I've noticed a little bit more weirdness about it. If I run something like `atom wtf` (where `wtf` is not actually a file), it will open in `D:\` with a new empty file opened in the editor called `wtf`. Then, if I close the window and run `atom .`, it will open again with a blank file called `wtf`. It's like it's just remembering the last thing it did and doing it again. Sort of.

**Comment by damieng** [comment]
Available now in master - you can copy the atom.sh and atom.cmd from master to your %localappdata%\atom\app-1.7.1\resources\cli folder if you need them sooner.

**Comment by okonomiyaki3000** [comment]
Thanks! I'll check it out!

**Comment by okonomiyaki3000** [comment]
Actually, I'm using 1.7.2 now and I still have the same issue.

**Comment by 50Wliu** [comment]
@okonomiyaki3000 Atom 1.7.2 does not contain the `.cmd`/`.sh` fixes yet.  You'll still need to copy the files over manually.

**Comment by okonomiyaki3000** [comment]
Ah, I see. I'll get them then.

**Comment by okonomiyaki3000** [comment]
Doesn't seem to fix it. Is it the files in here: https://github.com/atom/atom/tree/master/resources/win ?

**Comment by damieng** [comment]
You'll need to copy atom.cmd and atom.sh from there into your
app-1.7.2/resources/cli folder in local app data.

**Comment by okonomiyaki3000** [comment]
Yes, I did that. doesn't seem to work.
