### ISSUE TITLE
Opening a file from treeview now requires a doubleclick

### ISSUE THREAD

**Issue by eddiemonge** [atom/atom#11455]
Atom 1.7.0

Allow Pending Pane Items - unchecked

Previous behavior: Clicking a file in the Treeview opened (or previewed it).
New behavior: Clicking a file in the Treeview only selects it. Opening requires a double click

**Comment by 50Wliu** [comment]
Please see atom/tree-view#803 for the PR that changed this behavior and atom/tree-view#804 for updates.

**Comment by eddiemonge** [comment]
Thanks

**Comment by devios1** [comment]
I clicked a file in my tree view today and stared at my computer for 30 seconds waiting for it to open, thinking "boy this must be a big file" before I realized I had to double-click it. 😡

And there's no way I'm enabling pending pane items; what a terrible annoyance that feature is.

**Comment by 50Wliu** [comment]
@devios1 then you may be interested in the [single-click-open](https://atom.io/packages/single-click-open) package.

**Comment by devios1** [comment]
@50Wliu The thing I'm confused about is that package requires pending pane items be enabled, but it will still open a permanent tab with a single click?

**Comment by 50Wliu** [comment]
Yes.
