### ISSUE TITLE
Long links line-breaking could be improved

### ISSUE THREAD

**Issue by LudwikJaniuk** [atom/atom#11466]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Long "words" (in this case links) break to a new line if they follow some text, even if they will anyways cover more than the editor are and therefore will need to be broken again. In the provided example, it is obvoius that it would be better to leave the link on the original line and break it in half. 

![Image describing the bad line breaking.](http://i.imgur.com/mjR0hI1.png)
### Steps to Reproduce
1. Enable "Soft Wrap at Prefereed Line Length"
2. Write some text that covers about 1/3 of the preferred line length
3. Paste a link that is longer than the preferred line length

**Expected behavior:** Link to follow after the written text, be broken at an appropriate place, and continue on the next line

**Actual behavior:** Link moves directly to the next line, is broken after `preferred line length` characters, and continues on the line below that, just as the image describes.
### Versions

Atom 1.7.0
Windows 10

**Comment by bit-generation** [comment]
So, just to clarify; what you want is long strings from the clipboard to split to fit, but not to be prepended with \n ?

**Comment by LudwikJaniuk** [comment]
Yes, if it saves a line, which it does in this case. If the long string were shorter than an editor width, prepending \n would be reasonable, but if it's longer, you're splitting it anyways; might as well split it earlier and skip the \n. Looks nicer.
