### ISSUE TITLE
Disable new tab switching behaviour (Atom 1.7.0)

### ISSUE THREAD

**Issue by BlaM** [atom/atom#11462]
Atom Updated to v1.7.0 today and has broken tab switching. It seems to go to the most recently used file - which is unpredictable. When I press CTRL+TAB I expect to go to the next tab - not to any random tab that I may have used last without any visual clue. 

How do I turn that off and go back to the old behaviour?

**Comment by BlaM** [comment]
I guess this is the opposite of https://github.com/atom/atom/issues/5344

**Comment by BlaM** [comment]
... and matches https://github.com/atom/atom/issues/11035

**Comment by BlaM** [comment]
The fix for this issue seems to be to insert this into the keymap

'body':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-tab ^ctrl': 'unset!'
  'ctrl-shift-tab': 'pane:show-previous-item'
  'ctrl-shift-tab ^ctrl': 'unset!'

**Comment by gee-forr** [comment]
OMG! Thank you. Really ill-advised move to make the change + make it default + not provide a UI-based setting to switch it back.

**Comment by tobinfekkes** [comment]
That is a lifesaver! Thank you for the keymap snippet, Atom is nearly unusable without it.

**Comment by jdforrester** [comment]
Is there a task for "Provide a UI control to disable MRU ordering of tabs"? If not, should I create one?

**Comment by 50Wliu** [comment]
@jdforrester: #11035

**Comment by developius** [comment]
Thanks @BlaM, really appreciate the snippet! I for one also hate the feature where it brings up this preview box thing - it's so distracting. Thankfully, your fix seems to remove that too!

![screen shot 2017-06-22 at 19 35 46](https://user-images.githubusercontent.com/5836587/27450047-53788e7e-5782-11e7-8547-72812442eff7.png)

**Comment by dschissler** [comment]
I just want to say that its crap like this that keeps "Switch from Atom to Visual Studio Code" on my top 10 things to do list.  Crap like this irritated enough with Atom that I can't say that I'm happy with it.  I've been on the edge for a while now.  That overlay is such a miserable thing.  Another thing is that I don't have an Atom-centric desktop environment (nor do I use Atom OS) and I lose track of which files have been accessed recently.  For some reason the Atom developers think that I should be guessing the tab order as I bumble through ten tabs until I finally skip to the correct one.

**Comment by 50Wliu** [comment]
@dschissler Atom 1.23 has an option to disable the overlay and has had an option to revert to left -> right tab switching for a while now.

**Comment by dschissler** [comment]
I'm on 1.21, which appears to be the latest stable.  When 1.23 is released I will disable the customizations and to use the vanilla options.

**Comment by 50Wliu** [comment]
Yep, sorry, I should have clarified that Atom 1.23 isn't released yet, but should be heading to the beta channel soon.  For others who are following this, the two options are located in Settings -> Packages -> Tabs.
![mru-options](https://user-images.githubusercontent.com/2766036/32098320-94d90c66-bb0c-11e7-9926-a69612a63c45.png)
(the different casing of mru is a bug that I'll go fix right now :smile:)

**Comment by dschissler** [comment]
This is great.  I hope that in the future Atom doesn't change its behavior to something completely different with no way to toggle it in the settings again.
