### ISSUE TITLE
Atom 1.7 win10 Crash and couldn't be started

### ISSUE THREAD

**Issue by ashevch** [atom/atom#11469]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Atom stopped responding and answering after I tried the search in directory of the project. Then it couldn't be started and returned an error during the start. Running of the installer on top that installation didn't help.

I managed to get rid of this error by starting the second instance of atom with `atom --safe`
while the one problematic was opened, then closed the problematic one first. Now Atom could be restarted without this crash, but I've lost all unsaved changes in files and project structure, so I think that the problem might be somewhere in user-session parameters
### Steps to Reproduce
1. Run search in the directory
2. Search hangs
3. Atom stop responding and show crash error after restart
### Versions

```
$ atom --version
Atom    : 1.7.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python
git 2.7.4.windows.1
visual studio
```

windows 10 home

**Comment by othpiik** [comment]
try this `https://github.com/atom/atom/issues/11457`
