### ISSUE TITLE
Syntax highlighting JavaScript not working when using block comments in a string

### ISSUE THREAD

**Issue by doberkofler** [atom/atom#11467]
### Description

The syntax highlighting of JavaScript does seem to have a problem when using block comments in a string as reproducible in the following simple example:

```javascript
/*
const files = glob.sync('src/**/*.+(gif|png|jpg|ico)');
*/
```

### Versions

1.7.0

**Comment by 50Wliu** [comment]
@doberkofler Please move this to the language-javascript repository.  Thanks!
