### ISSUE TITLE
Functions are inconsistently highlighted

### ISSUE THREAD

**Issue by bharadwaj-raju** [atom/atom#11465]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

**Functions in code are inconsistently highlighted:**

* Functions *not* in standard library:

![Functions not in standard library are not highlighted](http://i.imgur.com/LtGDezUl.png)

* Functions in standard library:

![Functions in standard library are highlighted blue](http://i.imgur.com/RrZxWEm.png)

* Functions *not* in standard library *being defined*:

![Functions not in standard library while defining are highlighted blue](http://i.imgur.com/iV5gGz0.png)

### Steps to Reproduce

1. Write functions
2. Call them
3. See how they are not highlighted at all

**Expected behavior:** 

All functions, during definition and calling, should be highlighted.

**Actual behavior:** 

Only standard library functions are highlighted.

### Versions

* OS: Ubuntu 14.04 64-bit
* Atom version: 1.7

**Comment by 50Wliu** [comment]
Please move this over to the language-python package (or whatever language that is).  Thanks!
