### ISSUE TITLE
Download for Mac is broken

### ISSUE THREAD

**Issue by aexmachina** [atom/atom#11477]
The file that is downloaded when I click "Download for Mac" on atom.io is corrupted. I've tried several times, but after the `.zip` is extracted and I try to run the `.app` a Mac OS dialog is shown with the message "You can’t open the application “Atom” because it may be damaged or incomplete."

Atom Beta seems to work just fine.

**Comment by shaungrady** [comment]
Seeing this as well.

**Comment by pizzaops** [comment]
Same here. Atom 1.7.0 works though.

**Comment by bloopletech** [comment]
Can confirm, 1.7.0 works, and I think the only change in 1.7.1 is a fix on Windows, so probably not needed for Mac users.

**Comment by pizzaops** [comment]
@bloopletech BUT 1.7.1 > 1.7.0 AND THEREFORE I MUST USE IT

**Comment by dustindowell22** [comment]
Same here. Where can I get 1.7.0? I cleaned up before installing 1.7.0 so I don't have my old version.

**Comment by javacoolme** [comment]
Same here, but the beta works fine.

**Comment by leighkendell** [comment]
1.7.0 works but throws a bunch of errors for me. I'm back on 1.6.2 for now...

**Comment by dustindowell22** [comment]
I don't get any errors on 1.7.0

**Comment by ricardozanini** [comment]
Same here. Using 1.7.0 pointed by @pizzaops

**Comment by lee-dohm** [comment]
A fixed version of v1.7.1 has been uploaded and is available via Releases here:

https://github.com/atom/atom/releases/tag/v1.7.1

Working to fix the one downloaded from the atom.io website now.

**Comment by jadlirakesh** [comment]
It is a pain :), I tried all browsers available to Mac, used almost all unarchiver tools available for Mac , still does not work. 

The new release works fine @lee-dohm

**Comment by lee-dohm** [comment]
Cleared the cache on the web host and the https://atom.io download link appears to work now. Thanks everyone for reporting the issue!
