### ISSUE TITLE
single clicking files in tree view no longer opens them after updating to 1.7

### ISSUE THREAD

**Issue by MilesRoberts** [atom/atom#11470]
### Prerequisites

* [ ✔️ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ ✔️ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ✔️ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ✔️ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ✔️ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ✔️ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

if "allow pending pane items" is disabled, single clicking a file in tree view no longer does anything after updating to 1.7

In 1.6 single clicking a file would open it permanently in a new pane if "allow pending pane items" was disabled.

### Steps to Reproduce

1. disable "allow pending pane items"
2. single-click a file in tree view

**Expected behavior:** [What you expected to happen]

Single-clicking a file in tree view should open the file in a new, permanent pane if "allow pending pane items" is disabled.

**Actual behavior:** [What actually happened]

Nothing. Files only open if double-clicked.

### Versions

Atom    : 1.7.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.4

**Comment by Ben3eeE** [comment]
This is intended, see the blog post http://blog.atom.io/#opening-and-managing-files-from-the-tree-view explaining the new features.
There is also this https://github.com/atom/tree-view/pull/804 PR discussing how it should be reverted so that you can open with single click without pending pane items.

**Comment by MilesRoberts** [comment]
great. will keep an eye on atom/tree-view#804
