### ISSUE TITLE
After auto-update, Atom reopens with multiple Untitled tabs

### ISSUE THREAD

**Issue by tobiasboyd** [atom/atom#11472]
### Description

On two different OSX versions (10.11.4 and 10.9.5), the upgrade to 1.7.0 relaunched Atom with my multiple open documents replaced with Untitled empty tabs. This did cause some loss of work (my fault, obviously, but still a nasty surprise).
### Steps to Reproduce
1. Restart Atom to install the 1.7.0 update with multiple files open

**Expected behavior:** 
Atom 1.7.0 would finish the install and re-open with the same files open in tabs

**Actual behavior:**
All open docs were replaced by empty Untitled tabs - for unsaved docs, this was fatal.
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Reporting this from my OSX 10.9.5 box:

```
[12:12:17] tnboyd:~ $ atom --version
Atom    : 1.7.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
[12:12:22] tnboyd:~ $ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.1
```

**Comment by mnquintana** [comment]
Confirmed on OS X 10.11.4

**Comment by kangw3n** [comment]
Same in Windows 10

**Comment by hrkisk** [comment]
also next day after update, opening atom and all the tabs are empty and "untitled"

**Comment by bfis** [comment]
Same issue occurs on Debian 8.

**Comment by PhiLhoSoft** [comment]
I had the same issue on Windows 7 Professional. But I closed the tabs, and re-opened the files without problem.
I wouldn't have tried to reload Atom with unsaved files. Is it supposed to keep them somewhere and restore them after reload?

**Comment by tobiasboyd** [comment]
I just (nervously) accepted the 1.7.1 upgrade - and Atom successfully launched with my open tabs intact! Looks fixed to me! (On OSX 10.9.5, I will confirm on 10.11.4 once I get home).

**Comment by adamrunner** [comment]
I definitely just ran into this issue, but after the 1.7.1 update it appears to be gone. 

Reported and fixed before I even knew I was having a problem! Great job!

**Comment by 50Wliu** [comment]
Glad to hear it everyone!
If someone is still experiencing this on 1.7.1 please comment here.

**Comment by duichwer** [comment]
Atom has already updated automaticly to 1.7.1, but there are always three untitled tabs. Only the project path is still there.
I am running Atom on Windows 8.1 .

**Comment by bwinton** [comment]
I just hit this on my upgrade to 1.7.1…

**Comment by PhiLhoSoft** [comment]
For the record, it happened when I upgraded Atom 1.6.2 to 1.7.2. Saw somewhere it was a change in session format and the upgrade code was bugged.
Again, I only lost the list of opened tabs, which isn't important, but I wanted to point out there was no improvement here, despite the closed 
I made a screenshot. :smile: 
![atom-upgrade-to-1 7](https://cloud.githubusercontent.com/assets/1087902/14672402/f325504c-06f7-11e6-90e7-bd3ee0c49bf8.png)
It also shows two other issues: 1.7 breaking extensions by reading PATH in a case-sensitive way (there is a PR for that), and the "Keep waiting" dialog never auto-closing... (I will open an issue for that).

**Comment by kevingimbel** [comment]
Can confirm this is happening on Ubuntu 15.10 with Atom 1.7.2 - sometimes Atom opens with 1 empty file sometimes with 3,4 or even 5+. I could not identify any pattern. 

Probably not relevant but I am launching atom from bash with `atom .`.

**Comment by duichwer** [comment]
It stilll happens with version 1.7.2 on windwos 8.1

**Comment by lee-dohm** [comment]
If you are experiencing this issue, please do the following:

1. Save all your work
1. Completely exit Atom
1. Launch Atom again using `atom --clear-window-state`

Please let us know if that does not fix the Issue.

**Comment by duichwer** [comment]
When i follow these steps, this problem is  gone. 
Now, when i open my first file during a session with a double-click and no other file has been open before, This file open two times. ( I am not sure, if i had this problem before, too.)

**Comment by lee-dohm** [comment]
@duichwer your newly reported symptoms are covered by https://github.com/atom/atom/issues/11391.

**Comment by jbasoo** [comment]
Had the same issue on 1.8.0 and `atom --clear-window-state` seemed to fix it.
``` bash
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1
```
