### ISSUE TITLE
CRTL+F4 should close tab

### ISSUE THREAD

**Issue by goeddea** [atom/atom#11486]
Atom partly follows browser tab handling (e.g. CRTL+SHIFT+T to re-open the last closed tab).

It should also implement the usual browser shortcut for closing a tab (CTRl+F4) (whether instead of CTRL+W as is presently the case or additionally I have no opinion).

This regularly trips me up, as I'm used to this shortcut from both any desktop browser I've ever used and quite a few applications which implement a multi-document interface.

**Comment by simon-thorpe** [comment]
Other editors currently follow Ctrl+W (like Visual Studio Code) so it should still be kept.

**Comment by jonyeezs** [comment]
Wouldn't this be simply adding your own custom keybinding?

**Comment by goeddea** [comment]
I was not aware of the custom keybindings, and it proved entirely trivial to add this myself. (I should have RTFM, really).

So: Solved for me personally. 

Since CTRL+F4 is not assigned to anything as a default my suggestion stands, since some users will expect this to close a tab (as it does e.g. in Sublime Text). I'm aware though that there may be good reasons not to want more than one keyboard shortcut for an action, so I won't argue with this issue being closed as a "won't fix".

**Comment by 50Wliu** [comment]
This actually works for me and the keybinding is defined in win32.cson: https://github.com/atom/atom/blob/42fef8c0145ecf27e2c08d7e3cb119ad79197a6f/keymaps/win32.cson#L35

Do any other F# shortcuts work?

**Comment by goeddea** [comment]
As I said, I should have RTFM - assigning this shortcut works fine (Atom 1.7.2 on Ubuntu), as do other function key shortcuts.

**Comment by goeddea** [comment]
Thanks - for the change and generally for the great work on Atom!
