### ISSUE TITLE
Reloading wipes undo history and scroll position

### ISSUE THREAD

**Issue by Alhadis** [atom/atom#11483]
Prior to v1.7.0, it was possible to undo changes to an opened document after reloading the window (as long as it'd been running in development mode). I always assumed this was a feature of dev mode... make changes to a package repo, reload window, see what's wrong, undo last change, repeat.

Since upgrading to v1.7.0, I'm no longer able to do this. I'm unsure if this is by design or just an honest bug (or even if the previous behaviour was a bug to begin with...)

Also, the scroll offset isn't preserved after reloading the window: it reverts back to the top of the document. This wasn't the case before.

For the record, I'm using the *Reload window* command from the *View -> Developer* menu (which I've assigned the keyboard shortcut of <kbd>⌘ + shift + R</kbd>).

**Comment by 50Wliu** [comment]
This isn't limited to dev mode.

**Comment by Alhadis** [comment]
D'oh. So it isn't. My bad.

**Comment by Alhadis** [comment]
@50Wliu This actually *does* appear to be related to the `text-buffer` repo. Specifically, a feature that [was recently added](https://github.com/atom/text-buffer/pull/150/files) to generate patches from buffer histories.

I'm only 60% sure, but something seems to be updating a cache somewhere, which is triggering a reload of the buffer on startup. Seems to be originating from [these events emitted on startup](http://pastebin.com/raw/8vHPTE4B).

**Comment by 50Wliu** [comment]
Oops...figuring out which repo to report issues on is kinda hard sometimes :sweat_smile:.

**Comment by Alhadis** [comment]
Should I post my findings there, or... what do we do with this issue? :D

**Comment by Alhadis** [comment]
I've noticed this only happens if I reload the window too quickly after saving a file. If I wait a few seconds, *then* reload, it seems fine.

Similarly, if I reload the window too quickly after saving a file, the original contents are visible for a split second in the refreshed editor window. After a slight delay, the buffer's text gets updated to the last-saved version... this delay is roughly the same as the delay between reloading the window and having the previous window's scroll offset changed.

So, the timeline strikes me as this:

<table>
<tr><td width="50%">User saves file</td><td width="50%"></td></tr>
<tr><td></td><td>Atom asynchronously updates cached buffers and datablobs on disk</td></tr>
<tr><td>User reloads window too fast</td><td></td></tr>
<tr><td>Window reloads</td><td></td></tr>
<tr><td></td><td>Atom finishes aforementioned task</td></tr>
<tr><td>Window detects change to underlying buffer</td><td></td></tr>
<tr><td>Editor isn't expecting a buffer change, and responds as though the entire file were replaced by an external process</td><td></td></tr>
</table>

**Comment by dwelle** [comment]
may also be related to to a bug we're having over at [AtomLinter/linter-eslint](https://github.com/AtomLinter/linter-eslint/issues/620)

**Comment by Alhadis** [comment]
Seems this was fixed in a recent release. =) 👍

**Comment by adamreisnz** [comment]
I don't think this is fixed. The issue experienced with linter-eslint is still present. About 40-50% of the time when the linter auto fixes a file, the buffer momentarily blanks out, then gets repopulated, causing the window to scroll to the top and losing your scroll position.

See: https://github.com/AtomLinter/linter-eslint/issues/620 https://github.com/AtomLinter/linter-eslint/issues/774

@Alhadis Should I open a new ticket for it or can we reopen this issue?

**Comment by Alhadis** [comment]
Probably better off opening a new one, to be honest. Whatever triggered the original issue is probably unrelated to whatever you're experiencing.

Haven't noticed any regressions, myself. Then again, I don't use a linter.

**Comment by adamreisnz** [comment]
The reason I wanted to reopen this one, is because the linter issue was mentioned here earlier (https://github.com/atom/atom/issues/11483#issuecomment-239614098) just prior to you closing this issue. But ok, I can open a new one.
