### ISSUE TITLE
Specify git location instead of looking in PATH

### ISSUE THREAD

**Issue by dminer78** [atom/atom#11490]
I am using a portable version of atom from a flash drive. I also have a version of Portable Git. It would be nice to give the path to that portable git. Although this would need to work when the Windows drive letter changes due to it being on a flash drive.

# atom.exe -v
```
Atom    : 1.7.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by damieng** [comment]
One thing you could do here is create a .cmd file that added the portable git location to the path using SET and then executed atom.exe.

This would still be 100% portable - the SET command only changes it for the current and child processes and does not affect the actual PATH on the machine for all other processes.

**Comment by darkmorpher** [comment]
Assuming `git.exe` location has been included in your `$path`, then type `which git` to find portable git location in future.

**Comment by damieng** [comment]
Given there is a simple workaround for this described above that also works for any number of dependencies I think we should go ahead and close this. If we were to special-case finding git.exe then we'd next be finding node.exe, python.exe...
