### ISSUE TITLE
Atom update doesn't reload unsaved file progress and chokes on manually opening editor JSON from ~/.atom/storage

### ISSUE THREAD

**Issue by dstack4273** [atom/atom#11497]
### Description

I noticed that I was still on Atom version 1.6, so I checked to see what version is current and tried to use the built-in updater. After the updater failed to work (still/again) I manually downloaded and installed Atom using this process:
- Download from atom.io
- unzip
- close Atom
- drag new Atom to Applications, replace existing Atom with new 
- relaunch Atom

When I relaunched Atom the unsaved files I was working on were gone replaced with two blank files, and the saved file I had open was replaced with a blank file. I tried to look in the editor cached files to recover what I had been working on. Unfortunately one of those files is a little more than 1.6 MB, which when I try to load it and scan through in Atom, it chokes. It doesn't seem to be able to handle the very file that it created -- making recovering from the failed update process all the more painful.
### Steps to Reproduce
1. Try to update
2. Manually update when first step fails
3. Open newly updated Atom
4. Try to review cache since previously opened files were blown away
5. Cry because one of the files is too big to deal with in Atom
6. File issue on Github

**Expected behavior:** [What you expected to happen]
One of two things...maybe three:
1. Atom actually updates itself like the menu option suggests is possible (despite it never working)
2. Atom would recover from cache files 
3. Atom could actually handle a file that it generates so a user can manually recover from problems

**Actual behavior:** [What actually happened]
1. Updater failed
2. Manual install blew away open files from previous session
3. Can't manually retrieve prior work because .atom/storage editor cache file is larger than what Atom can handle (my file is 1621797, not sure what the limit is for Atom stability).
### Versions

I am on OS X version 10.11.4. I started with Atom version 1.6, and updated to 1.7 (1.7.1 to be exact).

**Comment by dstack4273** [comment]
Not sure how typical or useful this is, but I used less to go through the file and it looked like a lot of it was the contents of the tree-view pane. I guess that is what caused that single editor backup file to be so massive. 

Maybe it would be a good idea to only have a limit on the levels of recursion cached in that file or something? Might help keep the file size more manageable.

**Comment by yuanwhy** [comment]
This PR fixed the bug https://github.com/atom/atom/pull/12486
