### ISSUE TITLE
Atom fails to launch from Bash when install dir contains space

### ISSUE THREAD

**Issue by kbrose** [atom/atom#11492]
### Description

Running `atom .` from Git Bash ([https://git-scm.com/downloads](https://git-scm.com/downloads)) no longer opens Atom, and instead errors out, printing

```
/c/Users/Kevin Rose/AppData/Local/atom/bin/../app-1.7.1/resources/cli/atom.sh: line 2: /c/Users/Kevin: No such file or directory
```

The code in [/resources/win/atom.sh](https://github.com/atom/atom/blob/master/resources/win/atom.sh) was recently shortened by @damieng, if I replace this newer code with the previous version, then it runs fine from Git Bash. 

### Steps to Reproduce

1. In Git Bash on Windows (10), navigate to any directory
2. Run `atom .`
3. Observe the error

**Expected behavior:** It should open Atom at the specified directory.

**Actual behavior:** It errors out.

### Versions

```
Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

Windows 10

**Comment by kbrose** [comment]
Could be due to the space in my username, i.e. the space in `/c/Users/Kevin Rose/...`?

**Comment by damieng** [comment]
While there are some compatibility issues with some older versions of Bash with this approach the error is different (and separate fix for that).

It is spaces in the path which is causing an issue here - typically you put quotes around them but when chaining scripts each one strips the spaces before passing on which messes things up.

You could temporarily use the old script from 1.6.2 for now - the problem with that one is the --wait functionality is broken (which this change was fixing)

**Comment by kbrose** [comment]
Thanks for the quick response! I never used/wanted to use the `--wait` option, so I'm fine just falling back to the older version as a workaround.

**Comment by damieng** [comment]
Available now in master - you can copy the atom.sh and atom.cmd from master to your %localappdata%\atom\app-1.7.1\resources\cli folder if you need them sooner.

**Comment by kbrose** [comment]
Thanks!
