### ISSUE TITLE
Separate file type icon for Windows

### ISSUE THREAD

**Issue by NJDEN** [atom/atom#11504]
In reference to #10818 I would like to see file associations in Windows taken a step further by differentiating Atom's associated files with distinct file type icons. As of 1.7 all associated files take Atom's default icon as its own. At the very least all associated files should have a generic file icon separate from Atom's stock icon.

Ideally all file type icons should be changeable depending on the file extension thus conveying a visual difference between for example a .txt and a .py by visual recognition; however, starting with a separate generic associated file type icon would be significantly better than what is in place as of 1.7.

An example of files associated with Atom 1.7 on Windows 10 desktop:
![2016-04-17](https://cloud.githubusercontent.com/assets/11142424/14588863/ae1dd722-0499-11e6-9cc1-e2a70c7fa6c2.png)

An example of the proposed generic file icon next to an Atom shortcut:
![2016-04-17 1](https://cloud.githubusercontent.com/assets/11142424/14588947/0566d16c-049c-11e6-8b75-60e7aa33cc1c.png)

**Comment by damieng** [comment]
@simurai can you make an icon like this for the Windows shell integration?
