### ISSUE TITLE
Fedora Dependency Problem for 1.7 Upgrade, nothing provides libffmpeg.so()(64bit) needed by atom-1.7.0-1.*.x86_64

### ISSUE THREAD

**Issue by johnthomas00** [atom/atom#11505]
### Prerequisites
None, 

### Description
Cannot install Atom 1.7 on Fedora 22 or 23, but can install 1.6.

### Steps to Reproduce
```
[root@dev02 ~]# dnf install atom-1.7.0-1.fc22.x86_64
Last metadata expiration check performed 0:52:20 ago on Sun Apr 17 07:09:52 2016.
Error: nothing provides libffmpeg.so()(64bit) needed by atom-1.7.0-1.fc22.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)

[root@dev02 ~]# dnf --allowerasing install atom-1.7.0-1.fc22.x86_64
Last metadata expiration check performed 0:52:36 ago on Sun Apr 17 07:09:52 2016.
Error: nothing provides libffmpeg.so()(64bit) needed by atom-1.7.0-1.fc22.x86_64

[root@dev02 ~]# dnf list ffmpeg
Last metadata expiration check performed 0:52:45 ago on Sun Apr 17 07:09:52 2016.
Available Packages
ffmpeg.x86_64                                               2.6.8-1.fc22                                               rpmfusion-free-updates
```

**Expected behavior:** [What you expected to happen]
Atom 1.7 to install
**Actual behavior:** [What actually happened]
Atom 1.7 install fails

### Versions
See above

# reference:
Mentioned the problem at the link below.  Problem was confirmed and @lee-dohm suggested I create this issue.  
https://discuss.atom.io/t/fedora-dependency-problem-for-1-7-upgrade-nothing-provides-libffmpeg-so-64bit-needed-by-atom-1-7-0-1-x86-64/27940

**Comment by allanlewis** [comment]
I also have this issue on Fedora 23, even after enabling `rpmfusion-free-updates-testing`, which contains `ffmpeg-2.8.6-1.fc23`, which provides:
```
ffmpeg = 2.8.6-1.fc23
ffmpeg(x86-64) = 2.8.6-1.fc23
```
So perhaps the dependency should be the second item above?

**Comment by 1dot75cm** [comment]
Hi @allanlewis,
I try to fix this issue. Please test this Copr repo. Thanks.
```
$ sudo dnf copr enable mosquito/atom
$ sudo dnf install atom
```
https://copr.fedorainfracloud.org/coprs/mosquito/atom

**Comment by allanlewis** [comment]
Thanks, @1dot75cm, that works. I've disabled @helber's COPR in favour of yours.

**Comment by johnthomas00** [comment]
Thanks, @1dot75cm, my problem was also the @helber's COPR.  This works.  I am not sure how to close this issue, but will try.
