### ISSUE TITLE
Atom Installation is Slow on Arch Linux with no verbosity

### ISSUE THREAD

**Issue by kamijoutouma** [atom/atom#11502]
This has gotten Really annoying for me that atom takes 10+ minutes to install even though it downloads in 1 second. 

Here is a gist of the installation using yaourt

https://gist.github.com/kamijoutouma/8f0bc47e4a1952cc96cedd5760ca50ff

As you can see from the Gist during installation:

Installing the BUILD modules alone takes 83 WHOOPING seconds.

Installing apm takes another WHOOPING 47 seconds

Installing modules takes another WHOOPING 286 seconds.

Deduping modules takes 26 seconds.

Actually Building atom takes 114.7 seconds

During this time there is NO OUTPUT to tell us its doing something aside from how long it took after its done each step.

I have a high endish gaming pc that has an i7 and 32GB of ram with a 1TB HDD that has plenty of space. 

I am so sick of just sitting there waiting for my console to tell me that atom's installation is actually doing something. 

You guys need to either add more verbosity to the output or figure out what is making it so slow.

Atom is not that big of a text editor and i've seen plenty of applications including but not limited to "Sublime Text" build and install faster and all of them actually show output of them doing something.

It gets annoying every time i go to update arch and atom has an update because of this.

I'm tempted to just uninstall atom and never install it again.

**Comment by Chronoes** [comment]
I see plenty of output during the build process. I don't see why that would ever be a valid reason of uninstalling Atom forever. It's not like there is a patch every day, unless you wish to use nightly builds.

I used to use the uncompiled package too when I wanted to make the most of my old laptop, having 32-bit CPU and no binaries for it meant that it had to rebuild for every update which took nearly an hour.

Nobody is forcing you to do this every time, glued to the screen waiting for an automated build process to produce intermediary results. The good people at AUR provide binaries as well (atom-editor-bin) which is a bigger download obviously but takes no time to upgrade.

**Comment by kamijoutouma** [comment]
If its downloading something else then it should say its doing that instead of acting like its "just installing". My problem is that im on arch and i have tons of packages that get updated everyday. Its annoying seeing atom taking 10+ minutes to install when i need the other stuff installed like 10 minutes ago so i can start my day. Its rediculous if its downloading the build modules and just saying its installing them. Due to how long it takes for Build modules and apm to install it should DEFINETLY say each thing its downloading and the progress AT THE VERY LEAST. Instead of just sitting there and then suddenly saying "Took 83618ms" or any other number. No sane person is going to like that its not showing any progress when it takes that long. In fact if anything its considered a nusance.

**Comment by lee-dohm** [comment]
@kamijoutouma Thanks very much for the feedback. Speeding up the build process is something that we would like to make happen and the timing metrics you're mentioning is part of that effort. Speeding up the build process will allow us faster turnaround times on CI builds, which means that we can iterate faster. Until we have time to make improvements in that area, if you want more output, you can use the `--verbose` flag that some of our build tasks respond to. 

But according to [The Rule of Silence](https://en.wikipedia.org/wiki/Unix_philosophy#Eric_Raymond.E2.80.99s_17_Unix_Rules), unnecessary output is generally a code smell. So we won't be making this the default behavior.

**Comment by lee-dohm** [comment]
@kamijoutouma Additionally, your tone in your posts is a violation of our [Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md), specifically personal attacks and insulting/derogatory comments. We all get upset but the people that work and volunteer their time here are not here for you to vent your frustrations upon. You may consider this an official warning.
