### ISSUE TITLE
script/test only works on OS X

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#11516]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

`script/test` only runs the tests (which is basically its whole purpose) on OS X.  Otherwise it's basically `script/build` with a few extra fancy features for publishing.  This is because of `ciTasks.push('test') if process.platform is 'darwin'` [here](https://github.com/atom/atom/blob/d25347d78f6a41dd79d14659f7c618c08515bf62/build/Gruntfile.coffee#L291).

### Steps to Reproduce

1. Run `script/test` on non-OSX platforms

**Expected behavior:** Specs to run

**Actual behavior:** No specs are run

**Comment by damieng** [comment]
Right now many of the specs fail. I've fixed a few so far (paths, window and font sizing etc) but still a bunch left to do before script/test would succeed.

**Comment by damieng** [comment]
Let's track this as part of https://github.com/atom/atom/issues/11543

**Comment by 50Wliu** [comment]
This actually doesn't apply anymore with the build system rewrite, as now main process tests are run.
