### ISSUE TITLE
Single click no longer opening files

### ISSUE THREAD

**Issue by smaili** [atom/atom#11514]
It appears that after updating to the latest version (1.7.1), single clicks on files no longer open them when the `Allow Pending Pane Items` configuration is disabled.  So essentially what this means is single clicks no longer have any value for those of us who do not want files to be previewed.

May not sound like much, but for many of us, double clicking to open files isn't desirable.

Running Atom 1.7.1 on Mac OS.

**Comment by 50Wliu** [comment]
The Atom team has decided that opening files via single-click when pending pane items are disabled will no longer be supported.  Please see https://github.com/atom/tree-view/pull/804#issuecomment-211542906 for the full comment.
