### ISSUE TITLE
Impossible to see package update progress without a progress bar

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#11513]
When updating packages, it's frustratingly impossible to see how far along a package is in its update. For example atom-beautify takes absolutely forever to update, and its update often hangs forever. But there's no way (at least in 1.7.1) to see whether it's hung.

Package updates need a progress bar.

**Comment by 50Wliu** [comment]
> atom-beautify takes absolutely forever to update, and its update often hangs forever

This is a bug in settings-view where the progress bar doesn't update after packages finish updating - please see atom/settings-view#532.

In addition, this belongs on the settings-view repo.
