### ISSUE TITLE
Single line breaks HTML syntax highlighting

### ISSUE THREAD

**Issue by zackhall** [atom/atom#11517]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The following lines break syntax highlighting in HTML files: 

```html
<html>
<head>
  <script>
    console.error.bind(console);
  </script>
</head>
<body>
  <div>Hi</div>
</body>
</html>
```

### Steps to Reproduce

1. Open atom
2. Create an HTML file
3. Paste the lines above.
4. NOTICE that if you delete the second "console" variable syntax higlighting goes back to normal.

![p57hz4fs4q 1](https://cloud.githubusercontent.com/assets/1725349/14620944/818c10c6-0574-11e6-8671-a1b6cd99d571.gif)

**Expected behavior:** Proper syntax highlighting

**Actual behavior:** Broken syntax highlighting

### Versions
```
> atom --version

Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

Windows 10

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by zackhall** [comment]
This also broke syntax highlighting above on Github too. :laughing:

**Comment by 50Wliu** [comment]
Huh, looks like this is more common than I thought :P.  We're in the process of fixing this - feel free to subscribe to atom/language-javascript#354 and atom/language-javascript#358 for updates!

**Comment by zackhall** [comment]
Thanks, @50Wliu!

**Comment by Hungry-Gnu** [comment]
I have the same bug.
