### ISSUE TITLE
Can't input characters any more.

### ISSUE THREAD

**Issue by despairblue** [atom/atom#11529]
![atom](https://cloud.githubusercontent.com/assets/927609/14649489/8f2182ea-0667-11e6-9163-4a0362ff3c04.gif)

## Repro Steps
No idea yet. Have to test it in w/o any packages (except vim-mode, since I think it might be the crux).
If anyone has any hand steps for debugging this behaviour I'd appreciate that.

**Expected:** characters appearing
**Actual:** no characters appearing

## Command History

```
     -3:17.0 core:copy (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:14.8 vim-mode:move-to-start-of-file (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:13.5 vim-mode:activate-characterwise-visual-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -2:12.7 vim-mode:move-to-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -2:10.8 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -2:10.2 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:08.5 core:close (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.9 application:new-file (atom-text-editor.editor.vim-mode.normal-mode)
     -0:07.0 linter:set-bubble-transparent (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.0 clipboard-plus:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.8 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:01.8 core:cancel (atom-text-editor.editor.mini)
     -0:01.4 core:close (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:01.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.0 bug-report:open (atom-text-editor.editor.vim-mode.normal-mode)
```

## Versions

* **Atom:**       1.8.0-beta2
* **Atom-Shell:** 
* **OS:**         Mac OS X 10.11.3
* **Misc**
    * Could not determine apm version information

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by despairblue** [comment]
Also, the gif shows jumpy at one point, just to show that shurtcuts are actually working, just not for the buffer. Reopening the buffers, oder opening new one has also no effect. The only solution is to reload atom.

**Comment by despairblue** [comment]
I deactivated all package but `vim-mode` and it still happens. I try w/o vim-mode now.

**Comment by lee-dohm** [comment]
Have you tried using the Keybinding Resolver (<kbd>Cmd+.</kbd> on OS X and <kbd>Ctrl+.</kbd> on other platforms)? It will show you what key Atom saw you press and the command that was triggered because of it. It also shows regular character keys too.

**Comment by despairblue** [comment]
@lee-dohm see the gif in the first post :wink:

**Comment by lee-dohm** [comment]
Ah, thanks, I missed that without zooming in :blush:

**Comment by lee-dohm** [comment]
I'm not sure I have any other debugging steps to suggest though. I'll keep 💭

**Comment by despairblue** [comment]
Hasn't happened in a long time. I'm going to close this for now.
