### ISSUE TITLE
keyboard shortcuts not showing in menus (Ubuntu 16.04)

### ISSUE THREAD

**Issue by ewot** [atom/atom#11522]
### Prerequisites

Ubuntu 16.04
Atom 1.7.2
### Description

Window drop down menues are not showing the keyboard shortcuts (ctr-f, etc.) after upgrade to Ubuntu 16.04.

This is probably a Chromium/Electron/GTK issue as they are not showing in Chrome as well. But it might be worth tracking this issues here if someone comes up with a workaround.

**Comment by lee-dohm** [comment]
@zcbenz Can you confirm this? Is it fixed in a newer version of Electron than we have packaged?

**Comment by ewot** [comment]
It has not been fixed in the latest Electron.

I just tried the quickstart tutorial project and got the same results (shortcuts not displayed) on Electron v 0.37.7.

When running on Windows 10 the shortcuts shows up in the menues.

**Comment by lee-dohm** [comment]
Thanks @ewot for the legwork. I agree with tracking this here.

**Comment by ip** [comment]
I experience this too on the same OS.
Any progress?

**Comment by linuxfreak003** [comment]
Same problem here using Ubuntu 16.04 and Atom 1.8.0 Would be wonderful to have those shortcuts.

**Comment by witoldsz** [comment]
This issue shows what a minority the Ubuntu users are. Almost 5 months and nothing. I bet it would take hours to fix the similar Mac issue and maybe days for Windows.
:-(

**Comment by 50Wliu** [comment]
Considering that Chrome does not display the shortcuts either, I would look for a Chrome bug instead.

**Comment by elentirmo** [comment]
I reported this issue in Chromium a few weeks ago:
https://bugs.chromium.org/p/chromium/issues/detail?id=636718

**Comment by ewot** [comment]
Good news at last! :smile: 

Just upgraded to Ubuntu 16.10 rc and the menu shortcuts are back. They are back in Atom, Chrome, Chromium, VSCode and all other Electron apps I have tried.

I have no idea how it got fixed, but I guess it has something to do with newer Gtk or Chromium versions.

**Comment by elentirmo** [comment]
I kind of suspected that it might have been a Unity issue, since I noticed recently that Firefox doesn't show shortcuts either.

@ewot: Does Firefox show shortcuts on your machine?

**Comment by ewot** [comment]
@elentirmo Yes they do on 16.10. And on my 16.04 in Virtual Box they don't. So it might be a Unity issue just as you say.

**Comment by stavnstrup** [comment]
Or maybe the error is something else.

Just discovered it works v1.12.0-beta3, but did not work on v1.12.0-beta1. And I am using Ubuntu 16.04.
