### ISSUE TITLE
At the building stage, Running "download-electron" task ends with an error

### ISSUE THREAD

**Issue by PsiReaver** [atom/atom#11525]
Atom v1.7.2
Node: v4.4.3
npm: v2.13.3
Linux Mint 17.3 Rosa (Linux version 3.13.0-24-generic)

At the building stage (script/build), the script ends at the following task with an error:

`Running "download-electron" task`
`Fatal error: Request path contains unescaped characters.`

`TypeError: Request path contains unescaped characters.`
 ` at new ClientRequest (_http_client.js:50:11)`
`  at TunnelingAgent.exports.request (http.js:31:10)`
`  at TunnelingAgent.createSocket (/home/usr/Downloads/atom/build/node_modules/request/node_modules/tunnel-agent/index.js:117:25)`
`  at TunnelingAgent.createSecureSocket [as createSocket] (/home/usr/Downloads/atom/build/node_modules/request/node_modules/tunnel-agent/index.js:184:41)`
 ` at TunnelingAgent.addRequest (/home/usr/Downloads/atom/build/node_modules/request/node_modules/tunnel-agent/index.js:80:8)`
`  at new ClientRequest (_http_client.js:131:16)`
`  at Object.exports.request (http.js:31:10)`
`  at Object.socket.once.exports.request (https.js:182:15)`
`  at Request.start (/home/usr/Downloads/atom/build/node_modules/request/request.js:585:30)`
`  at Request.end (/home/usr/Downloads/atom/build/node_modules/request/request.js:1213:28)`
`  at /home/usr/Downloads/atom/build/node_modules/request/request.js:417:12`
`  at nextTickCallbackWith0Args (node.js:420:9)`
`  at process._tickDomainCallback (node.js:390:13)`
`  at Function.Module.runMain (module.js:443:11)`
`  at startup (node.js:139:18)`
`  at node.js:968:3`

This error occurs only if I set environment variables `http_proxy` or `https_proxy`. If I unset this variables I get a following error because I am behind proxy:

` Cannot find electron v0.36.8 from GitHub { [Error: connect ECONNREFUSED 192.30.252.124:443]`
 `  code: 'ECONNREFUSED',`
 `  errno: 'ECONNREFUSED',`
 `  syscall: 'connect',`
 `  address: '192.30.252.124',`
 `  port: 443 }`
`Warning: Task "download-electron" failed. Use --force to continue.`

My `http_proxy` variable looks like this:

`http_proxy=http://192.168.22.9:3128/`

Evidently, there is no characters that should be escaped.

There is a comment in ClientRequest function,  in_http_client.js,  Node.js source code that says:

` // The actual regex is more like /[^A-Za-z0-9\-._~!$&'()*+,;=/:@]/`
  `  // with an additional rule for ignoring percentage-escaped characters`
 `   // but that's a) hard to capture in a regular expression that performs`
 `   // well, and b) possibly too restrictive for real-world usage. That's`
  `  // why it only scans for spaces because those are guaranteed to create`
 `   // an invalid request.`

So perhaps the problem is that some space characters are inserted in proxy url by mistake but I cannot find out where it may happens in Atom source code.

**Comment by suzetmk** [comment]
same problem with:
Atom: refs/tags/v1.8.0-beta2
Node: v5.3.0
npm: v2.13.3
Ubuntu 14.04 lts 3.13.0-77-generic

**Comment by 50Wliu** [comment]
Fixed by electron/grunt-download-electron#30.
