### ISSUE TITLE
Blinking scrollbars/soft wrap

### ISSUE THREAD

**Issue by kuba-orlik** [atom/atom#11523]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

When certain text is entered in the editor with "soft wrap" enabled, sometimes the editor cannot decide on which word to wrap and just alternates between the two options, which is extremely distracting.
### Steps to Reproduce
1. Enter some text
2. (after some time/luck) Observe blinking scrollbars

**Expected behavior:** Nothing moves unless I edit something

**Actual behavior:** See the video attachment
[blink.ogv.zip](https://github.com/atom/atom/files/225726/blink.ogv.zip)
### Versions

```
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.0
```

I'm running Ubuntu 15.10 with Gnome Shell 3.16

**Comment by bevacqua** [comment]
With this text and a specific sidebar width, you can reproduce consistently:

```asciidoc
[[javascript-modules]]
== JavaScript Modules

Over the years, we've seen multiple different ways in which to split code into more manageable units. For the longest time we've had the module pattern where you simply wrapped pieces of code in self-invoking function expressions. You had to be careful to sort your scripts so that each script came after all of its dependencies.

A while later, the RequireJS library was born. It provided a way of defining the dependencies of each module programmatically, so that a dependency graph is created and you wouldn't need to worry about sorting your scripts anymore. The way RequireJS worked demanded that you provided an array of strings used to identify your dependencies and also wrap modules in a function call, which would then receive those dependencies as parameters. Many other libraries provide similar functionality but offer an slightly different API.

Other complexity management mechanisms existed, such as the dependency injection mechanism in AngularJS, where you define named components using functions where you can, in turn, specify other named component dependencies. AngularJS carries the load of dependency injection on your behalf, so you only have to name components and specify dependencies.

CommonJS surfaced as an alternative to RequireJS, and it was swiftly popularized by Node.js soon afterwards. In this chapter we'll take a look at CommonJS, which is still heavily in use today. We'll then cover the module system introduced to native JavaScript in ES6, and lastly we'll explore interoperability between CommonJS and native JavaScript modules -- also known as "ES modules".
```

**Comment by ami** [comment]
reproduced this as well on atom v1.11.2 and mac osx v10.11.5
