### ISSUE TITLE
Files opened without content and with repetitive tabs for the same file.

### ISSUE THREAD

**Issue by ghs** [atom/atom#11524]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Files are opened empty for period of time and some of them are repetitive. It is happening since couple of versions, but can't say since which one exactly.

### Steps to Reproduce

1. Double click a file to open.
2. Fast another one

**Expected behavior:**
To open the file with content and to have only one tab per file, not double.

**Actual behavior:**
Files are opened without content. After some time, the file content is appearing and just after it, last file or randomly (can't say) is opened in separate tab.

### Versions
OS: Mac OS X 10.11.4
![captura de pantalla 2016-04-19 a las 12 43 47](https://cloud.githubusercontent.com/assets/94248/14636798/da5cfd0a-062d-11e6-994b-db2e0ff7b22e.png)
![captura de pantalla 2016-04-19 a las 12 43 51](https://cloud.githubusercontent.com/assets/94248/14636796/da5c02ec-062d-11e6-8b60-81b058854c65.png)
![captura de pantalla 2016-04-19 a las 12 47 25](https://cloud.githubusercontent.com/assets/94248/14636797/da5cb6ec-062d-11e6-9e2b-77b33d0bf6fc.png)

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.9
git 2.6.4

**Comment by Ben3eeE** [comment]
Duplicate tabs was reported over here https://github.com/atom/atom/issues/11391
This does however have an additional issue with the no content part, can't comment on that.

**Comment by lee-dohm** [comment]
If you are getting the same mystery tabs appearing without content, try this:

1. **Save your work**
1. Completely exit Atom
1. Launch Atom again with `atom --clear-window-state`

Feel free to reopen this if that doesn't fix it.

**Comment by gassius** [comment]
This is happening to me as well @lee-dohm 
Atom 1.7.2 running on Ubuntu 14.04 LTS
Installed via WebUpd8 PPA

I disabled any community package to discard any non-core problem, but result is the same. Tab opens with no content and then after a variable time it shows the content (sometimes the content don't appear at all after 2 min and then I close the tab and try again)
I should add that, very rarely, the content is shown as expected, but for me is less than 10% of the times I open a new file.

Should I create a new issue or you will reopen this? (of course already tried atom --clear-window-state and that did't solved the issue)

Please adivce

**Comment by lee-dohm** [comment]
Please open a new Issue.

**Comment by gassius** [comment]
Thanks @lee-dohm 
Reference https://github.com/atom/atom/issues/11632

**Comment by ghs** [comment]
sorry for the delay @lee-dohm, but --clear-window-state didn't work for me either

**Comment by lee-dohm** [comment]
Are the files you're opening on a network drive or in a VM?

**Comment by ghs** [comment]
No, same machine.

**Comment by lee-dohm** [comment]
Leaving off the duplicated tabs thing ... what exactly is the problem?

**Comment by ghs** [comment]
As @gassius also commented, the content from all of the "opened" files is empty and starts to appear after X time. For some files it takes about 2 seconds, which is normal I think, but for others could take up to 15 even with content of one line with about 50 characters.

**Comment by lee-dohm** [comment]
So it is slow to fill in the text when you open two files at pretty much the same moment?

**Comment by ghs** [comment]
Happens even with one file: double click to open it, the tab appears with no content and stays empty for X seconds. After that opens a copy of it in "preview" mode, then focus the preview tab, fills it with content and then if you click on the first tab, the content is there as well.

![captura de pantalla 2016-05-02 a las 15 04 06](https://cloud.githubusercontent.com/assets/94248/14955042/479d5cd6-1077-11e6-99bb-2d2d776febb4.png)

Now for that example, after 9 seconds:

![captura de pantalla 2016-05-02 a las 15 04 15](https://cloud.githubusercontent.com/assets/94248/14955050/4e05f84e-1077-11e6-9345-b09babc01b9d.png)

And if you start typing within the second file, changes are applied within the first one as well.

![captura de pantalla 2016-05-02 a las 15 04 22](https://cloud.githubusercontent.com/assets/94248/14955056/56364582-1077-11e6-93ed-6f63d0f469ed.png)

**Comment by lee-dohm** [comment]
Do you have a file or repository that reproduces this behavior @ghs? I can't reproduce this using Atom v1.9.0-dev-5a9bd28 on Mac OS X 10.11.4 (or other versions I've tried).

**Comment by ghs** [comment]
I see I've attached a screens from the same files all the time, but it happens with different ones and with different extensions. Sorry, all files and repos are private :(

If you want, lets leave it like that for the moment and will write back when update to Atom 1.8 or 1.9. I have no problem waiting some time till the file get opened and close the repetitive tabs. :)

**Comment by lee-dohm** [comment]
Ok, thanks ... let us know if you find anything more out! :grinning:

**Comment by ghs** [comment]
@lee-dohm only to inform you that just got 1.8 and it is not happening anymore :)
