### ISSUE TITLE
Atom Unusable on Windows - Heavy Lag

### ISSUE THREAD

**Issue by Charbrec** [atom/atom#11528]
### Description

Atom has begun to run at a snails pace, with ~5 latency between actions spaced out over a ~20 second interval. As in, it will run smoothly for ~ 20 seconds before locking up from an action for ~5 seconds. This happens consistently throughout any open document. The number of open tabs doesn't matter. Safe mode changed nothing, removing/disabling plugins changed nothing, attempting to completely uninstall & reinstall Atom changed nothing. 

Running out of troubleshooting options to try, as I think I've attempted everything to resolve the issue. I ran a CPU profile through dev tools, see attached .zip file. 

[CPU-Profile.zip](https://github.com/atom/atom/files/226490/CPU-Profile.zip)

In this state, the software is unusable, and has put a large fork in my workflow.
### Steps to Reproduce
1. Launch Atom
2. Observe Lag

**Expected behavior:**
No Lag

**Actual behavior:**
Insane Lag
### Versions

```
Atom     : 1.7.2
Electron : 0.36.8
Chrome   : 47.9.2526.110
Node     : 5.1.1

```

```
apm  1.9.2
npm  2.13.13
node 0.10.40
git 1.9.5.github.0
```

```
Windows 10 Pro
Version  : 1511
OS Build : 10586.218
```

**Comment by Zireael07** [comment]
What project are you working on? Is it a git repo? A remote disk/folder? Is it very large?

**Comment by Charbrec** [comment]
Working on basic HTML/CSS files. The files I was primarily working on where ~100 lines tops. Extremely small files compared to my usual work load. All on my local disc. Basically some copy/pasta for a Shopify build I'm working on, using Atom for staging before deployment to live.

**Comment by Zireael07** [comment]
Curious.

What is your CPU? GFX card? (I seem to recall some cards doing weird things with Chromium)

**Comment by Charbrec** [comment]
I'm running a i5 4570S, integrated graphics. 16GB of RAM, so that shouldn't be an issue.

**Comment by Zireael07** [comment]
Intel integra or NVidia integra?

**Comment by Charbrec** [comment]
Intel(R) HD Graphics 4600

**Comment by lee-dohm** [comment]
Are you opening a large directory where these files exist? Perhaps something that isn't under source control and is using node modules or some other deeply-nested directory structure?

**Comment by ivanpu** [comment]
I'm expiriencing the same lags on Windows 7, even after downgrading Atom to 1.6.2 (due to various crashes both on Windows and Linux).
Although at first I've attributed them to working over sshfs mount, but I'm curios now for the real reason after reading this issue.

In my current work case, I have project directory with few git managed directories (up to 5 levels), and few unmanaged directories (e.q. for building).
Do you need some more info, that might help?

Also, just a shot in the dark:
I'm familiar with similar behaviour in Java application, due to garbage collector.
So: does Electorn, or anything else that Atom uses, have garbage collector?

**Comment by lee-dohm** [comment]
@Charbrec Do you have answers to my questions?

**Comment by Charbrec** [comment]
I don't use directories in Atom, they've always bugged out for me after extended periods of time. And I don't have anything else running that would be using the same resources, or any software that might be causing issues.

On a side note, the lag issue seemed to subside for awhile, but has returned. Still haven't found a clear source of the issues yet.

**Comment by goigle** [comment]
I'm having the same issue on 1.9.9.
AMD FX 8350, Samsung SSD, AMD R9 390x.

I'm currently working in a folder with 244 subfolders and 483 files, but the lag is present before opening that folder.

**Comment by damieng** [comment]
Are you still getting this on the latest 1.12 update?  (There were fixes in Electron for slowdowns on systems with certain accessibility features enabled)

**Comment by goigle** [comment]
@damieng I am not, I found out the problem was a color addon

**Comment by damieng** [comment]
Great news, going to close this issue.
