### ISSUE TITLE
Not all snippets rendering

### ISSUE THREAD

**Issue by bretonics** [atom/atom#11532]
In `snippets.cson file`, some custom snips do not autofill when used accordingly. Interestingly enough, the editor suggests the prefix used for the new snips, though differently (without the green arrow on the left) and just enters the word prefix rather than the snip.

Started seeing this a couple of months back but only on 1 snip, now that I've added a couple more, the issue persists.

Atom Version: 1.7.2
OS: OS X El Capitan

**Comment by bretonics** [comment]
In `snippets.cson` file, some custom snips do not autofill when used accordingly. Interestingly enough, the editor suggests the prefix used for the new snips, though differently (without the green arrow on the left).

**Atom Version**: 1.7.2
**OS**: OS X El Capitan

**Comment by bretonics** [comment]
This fixed the issue: [second instance overwriting first] (http://stackoverflow.com/questions/26615818/atom-editor-multiple-snippets)

**Comment by 50Wliu** [comment]
Glad to hear you fixed it @bretonics!
