### ISSUE TITLE
Repeatedly collapsing/expanding folders in tree-view crashes the editor

### ISSUE THREAD

**Issue by Ingramz** [atom/atom#11538]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

![tree_view_crash](https://cloud.githubusercontent.com/assets/1017132/14666823/59fc31c8-06e4-11e6-8c6f-75b838c87fa1.gif)

### Steps to Reproduce

1. Open a project with at least two nested folders inside the project
2. Expand the two nested folders
3. Start rapidly and repeatedly collapsing/expanding the outer folder of the two

**Expected behavior:** Folders would expand/collapse

**Actual behavior:** Editor crashes

### Versions

Running Windows 10 with latest Atom beta

```
Atom    : 1.8.0-beta2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by Zireael07** [comment]
I think it's a duplicate. Look in tree view repo?

**Comment by 50Wliu** [comment]
This should be reported to atom/tree-view, but I'm not sure it's a duplicate (there is a related one though).  I may have been able to reproduce this accidentally before, but I'll double-check later today.
