### ISSUE TITLE
[Feature Request] When pressing Ctrl-Tab key, display a panel of tab list in MRU order for cycling

### ISSUE THREAD

**Issue by ugoa** [atom/atom#11535]
### Description

The MRU tab switching in 1.7 is great, however it would be even better to pop up a tabs list panel in MRU order when pressing `ctrl-tab`, so that I can choose which specific tab to go to by holding `ctrl` and pressing `tab` key. The current behaviour would just jump to the first tab in the MRU stack, which is fine but really doesn't cover the most of editing scenarios.

What I mean is something like this package does [enhanced-tabs](https://atom.io/packages/enhanced-tabs).

Thanks!

### Versions

OS X: 10.10
Atom: 1.7.2

**Comment by mehcode** [comment]
This sounds like it could be very awesome if paired with the rendering engine powering the minimap. Though I'd think we'd either need to make the minimap a bundled package or make the rendering API it's own shared package/library.

**Comment by lee-dohm** [comment]
I'm not sure I understand what is being requested here. The whole point of MRU tabs is that people remember the order that their tabs are in separate from how they are ordered in the tab bar. If you want a tab list ordered in MRU order, then couldn't a package reorder the tab bar every time you switched tabs?

**Comment by mehcode** [comment]
@lee-dohm From what I gather this is a request to add an centered modal overlay that that shows _only_ when switching tabs in MRU order. Exactly like `alt-tab` or `cmd-tab` in your OS but for tabs. I'm envisioning a truncated minimap rendering with a title under it.

This should probably end up in a package though. I don't think it belongs in core.

**Comment by ugoa** [comment]
@lee-dohm @mehcode What I mean is something like this package does [enhanced-tabs](https://atom.io/packages/enhanced-tabs), I might be asking too much since there is already a package to do this, but it would be so great to integrate it with MRU cause it would be native and much faster.

**Comment by mehcode** [comment]
Aside from cringing at the UI of enhanced-tabs; we're on the same page.

**Comment by PhiLhoSoft** [comment]
Looks more like Atom Tabs Exposé, perhaps.
https://atom.io/packages/expose

**Comment by lee-dohm** [comment]
Since this feature is already available in a couple of packages, I'm going to close it. With that said, if someone wanted to submit a PR for something like this and needed help landing it, please feel free to reach out to me here, on Discuss or Slack.

**Comment by ugoa** [comment]
@lee-dohm I still think this is the missing part for the MRU tab switching feature, and it should be supported by the editor instead of leveraging on a 3rd party package. Not to mention I'd tried all the the packages listed above and all of them have this and that problems: `enhanced-tabs` no longer works, `tab-switcher` and `expose` uses different key-bindings rather than `ctrl-tab`... I might be biased cause I've being using RubyMine for years and love it's tab switching so I want to see it also available in Atom. But having said that, I am fine if the core team decide it should not be build-in supported, and I am glad to see if someone developed such a package, before that I guess I have to live with it. 

Great editor though, thanks for all your hard work!

**Comment by Ben3eeE** [comment]
This sounds like the same issue as https://github.com/atom/atom/issues/11439

**Comment by 50Wliu** [comment]
I believe #11439 is more about "I can't tell which `index.js` is which" rather than "I don't know which tab I'm going to be switched to".

**Comment by Ajedi32** [comment]
FYI, this is being addressed by atom/tabs#388
