### ISSUE TITLE
cmd+` key binding appears to no longer work. OSx

### ISSUE THREAD

**Issue by mawint** [atom/atom#11531]
![screen shot 2016-04-19 at 2 28 56 pm](https://cloud.githubusercontent.com/assets/3912781/14653559/1d41c19e-063f-11e6-869f-92c10aaa4aa1.png)
![screen shot 2016-04-19 at 2 29 06 pm](https://cloud.githubusercontent.com/assets/3912781/14653558/1d4166f4-063f-11e6-9fb1-82b2a49b80e9.png)

Attempting cmd+` is not currently switching between open windows. App version and OSx version below.

If there is additional debug screens I can post for key binding, let me know, I am unaware of them. 
## Versions

Atom: 1.7.2
OS: Mac OS X 10.11.4
Packages: None
Themes : None

**Comment by klebba** [comment]
Same here -- Atom 1.7.2, OSX 10.11.4 -- restarting Atom sometimes alleviates the problem briefly

**Comment by mitchellnemitz** [comment]
Can't reproduce here. Atom 1.7.2, OSX 10.11.4.

**Comment by lee-dohm** [comment]
I can't reproduce this using Atom v1.7.2 on Mac OS X 10.11.4. Are you using a non-US-English keyboard?

**Comment by klebba** [comment]
MacBook Pro keyboard -- nothing about my hardware has changed lately, and I have been using this shortcut for a while in atom. Not sure what other info I can provide to help repro

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Can you reproduce the issue in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by mawint** [comment]
Is reproducible for me in safe mode. 

I am using a standard US English keyboard.

**Comment by lee-dohm** [comment]
Can you post your `keymap.cson` here?

**Comment by mawint** [comment]
Let me know if this works, it's not a valid extension for upload.

https://gist.github.com/mawint/a00c7780c8d5a5b8cf391c6fdfc6f1df

**Comment by lee-dohm** [comment]
Yes, that worked, thanks. Unfortunately, it doesn't get us any closer to what is going on with your system 😕

**Comment by mawint** [comment]
Hmmm. 

Can you think of any other debug that would help?

**Comment by lee-dohm** [comment]
Are you using an alternate keyboard layout in OS X? Meaning something like Dvorak, Colemak, or Dvorak-Cmd-Qwerty?

**Comment by mawint** [comment]
Nope. Just using the standard keyboard layout.

**Comment by mawint** [comment]
So to update this. 

The command works as long as I click focus off of the original window but gets stuck back at the original window. 

I have a video of this and also a keyboard display popping up on the side of the screen. Let me know if this link works.

https://drive.google.com/file/d/0B2-_A7kv-DdGNWVfanJxZVFPc2M/view?usp=sharing

**Comment by maaarghk** [comment]
I'm also getting this, UK english external Apple keyboard. Has always worked before, obviously I use it regularly.

**Comment by lee-dohm** [comment]
The only other thing I can think of to try is to create a guest account on your machine, install Atom and try to reproduce the problem there. It could be some piece of software you have installed intercepting things (hopefully not for all users or this won't work :grinning:).

**Comment by mawint** [comment]
It does work in a new user. 

I did not reinstall the program though. I was able to select it in Applications.

**Comment by mawint** [comment]
Is there a settings/cache file I can blow away to reset atom?

**Comment by 50Wliu** [comment]
`mv ~/.atom ~/.atom-backup`

**Comment by mawint** [comment]
Hmm. That didn't work. 

Still gets stuck on the first window opened for this user.

**Comment by lee-dohm** [comment]
So it isn't anything to do with Atom then that is causing the problem, but most likely some other piece of software running in your user profile.

**Comment by mawint** [comment]
I have brew installed and when I went to check the status of it, brew was having issues with Ruby. 

When I get back to my computer and can resolve the brew issues and check the packages, I'll see if it resolves the issue.

**Comment by maaarghk** [comment]
honestly? some other piece of software that happens to capture cmd + ` on atom's behalf since the 1.7  upgrade?

**Comment by lee-dohm** [comment]
@maaarghk What is causing the problem for @mawint may well be different than what is causing the problem in your case. Did you try creating a guest account and did you get the same results?

**Comment by mawint** [comment]
Fixing brew did not solve the problem. Since it's what I'm using as a package manager it was my first step at troubleshooting. 

I'll look for others.

**Comment by mawint** [comment]
I deleted a few programs but still can't find any that would be conflicting with it. I also attempted to remove the .atom folder and delete the program and reinstall but it doesn't seem to help.

**Comment by klebba** [comment]
How can I roll back my version of Atom?

**Comment by mawint** [comment]
I'm not sure.

Update though; If I leave the windows open and quit then reopen Atom with the windows auto opening the command works. If I close the windows before quitting atom and reopen the folders manually after opening Atom, the command doesn't work.

**Comment by lee-dohm** [comment]
@klebba For general questions, please use [Discuss, the official Atom discussion forum](https://discuss.atom.io).

**Comment by klebba** [comment]
@lee-dohm Not a general question; trying to verify that this issue arose in this version of Atom since the feature has worked for me in all prior versions. Don't believe it's an issue with my system

**Comment by lee-dohm** [comment]
You can delete the application from `/Applications` and download an older version from https://github.com/atom/atom/releases.

**Comment by djadomi** [comment]
I'm also getting the broken ***OS X standard*** Cmd-` behaviour, since 1.7 as far as I can tell.

I've tried using a Guest account, launching in safe mode, and there's no still response to Cmd-`.

I use this constantly between all other apps - the only other app that doesn't support it - deliberately - is Photoshop. I have used Cmd-` since I started using Atom (can't remember when exactly, but way before v1)

**Comment by mawint** [comment]
Not sure if anyone is still following this but updating to 1.7.3 has grabbed me intermittent success on getting the command to work. Still hangs on some windows for an unknown reason.

**Comment by djadomi** [comment]
@mawint Ooh, you gave me some hope there… false hope it turned out, but hope nonetheless ;)

I don't get the behaviour you're reporting, still no switching at all.

I'm assuming this is actually an Electron issue/feature? Going to look there…

**Comment by rcchen** [comment]
I'm on Atom 1.8.0, US keyboard layout, El Capitan 10.11.4. Here's the repro that I've figured out:

1. Open an Atom window.
2. Open a second Atom window. Hit cmd+`. Note that it does not rotate back around to the first window.
3. Go back to the original Atom window. Hit cmd+`. It _does_ rotate to the second window. However, hitting the combo again does not rotate to the first window.

Also managed to repro this on another Mac with Atom 1.8.0, US keyboard layout, El Capitan 10.11.5. Would appreciate any feedback on whether others manage to reproduce this issue in a similar manner.

**Comment by lee-dohm** [comment]
@rcchen I just tried this using Atom v1.8.0 on Mac OS X 10.11.5 and could not replicate your experience. Here's what I did:

1. Launch Atom from the command line using `atom .` in my Atom project repository
1. Open a new window using <kbd>Shift+Cmd+N</kbd>
1. Rotate back to the first window using <kbd>Cmd+`</kbd>
1. Rotate to the second window using <kbd>Cmd+`</kbd>
1. Rotate repeatedly between both using <kbd>Cmd+`</kbd>

I also tried:

1. Launch Atom from the command line using `atom .` from my Atom project repository
1. Launch a second Atom window from the command line using `atom .` in another project repository
1. Rotate back to the first window using <kbd>Cmd+`</kbd>
1. Rotate to the second window using <kbd>Cmd+`</kbd>
1. Rotate repeatedly between both using <kbd>Cmd+`</kbd>

Both worked exactly as expected.

**Comment by maaarghk** [comment]
I also still sporadically experience this issue. UK English external keyboard, MBP, latest OS X. However I also had it happen in Chrome once - happens far less often than in Stock, but still - making me think it is possible this is either a Chromium bug or perhaps even an OS bug. I wouldn't know where to start to help debug this next time it happens though.

**Comment by lee-dohm** [comment]
@maaarghk Could you include the actual version number of OS X? In the future nobody will know what the latest OS X was at this particular date :grinning:

**Comment by maaarghk** [comment]
Fair point! I was typing the comment on mobile and couldn't remember the number, but I've checked the version it's on now and updated the comment. Do you have any advice for how I can get some useful debugging info the next time this bug hits?

**Comment by djadomi** [comment]
> What follow may be moot now, but it might help someone Googling sometime in the future…

For me, this problem has been worked around by changing keyboard layouts. Let me explain: previously I was using OS X with a "British - PC" layout

![british-vs-british---pc](https://cloud.githubusercontent.com/assets/512513/16651703/0964b588-4446-11e6-8ab1-cae3ab812294.png)

(my muscle memory for \\"\~|\`@# and friends was built up over 25+ years so standard OS X British was tricky). The Cmd-` keystroke was therefore on the "top-left" key. This used to work on Atom, and still does on everything else. When it stopped working on Atom (around 1.7) I couldn't find a fix. So I bit the bullet and switched to standard OS X British to see if that fixed it. This now switches exactly as expected (in everything - even Photoshop likes it) although my old muscle memory sometimes kicks in and I end up quoting with @ signs…

**Comment by maaarghk** [comment]
![screen shot 2016-07-07 at 12 39 07](https://cloud.githubusercontent.com/assets/3168648/16652062/d724cad2-443f-11e6-84bb-1687958006d6.png)

Interestingly, despite the fact I have British selected and my keyboard has the backtick on the bottom left, the diagram matches "British PC" on your screenshot.

**Comment by djadomi** [comment]
Hm, not sure… maybe that's because it's physically an American-style keyboard? (Horizontal vs vertical Enter key.) The UK layout has an extra key (now my \` key) where your left-shift is.

**Comment by maaarghk** [comment]
No, it's definitely a UK stye keyboard. Frustratingly here, the model number A1243, is not useful as it seems to relate to any wired keyboard with a numeric pad. However, incase it is unique, the USB id is `05ac:0250` and here is a photo from the net of a keyboard with an identical layout: 
![image](https://cloud.githubusercontent.com/assets/3168648/16652559/54743056-4443-11e6-81b2-b974c7f51a09.png) - taken from [this ebay entry](http://www.ebay.co.uk/itm/Genuine-Apple-A1243-Wired-UK-QWERTY-Thin-Keyboard-with-Num-Pad-/291785483932?hash=item43efc5269c:g:ircAAOSwMNxXVsmd).

**Comment by djadomi** [comment]
I wonder if it's not been recognised as a British keyboard? I don't have one to see what it says on my system. Did you say you were using a MacBook? What's the keyboard on that?

**Comment by maaarghk** [comment]
It definitely recognised it as a UK keyboard, I didn't have to configure it to say British in the control panel there. The macbook itself also has a UK keyboard.

**Comment by lee-dohm** [comment]
@djadomi and @maaarghk We currently have a known bug around international keyboards atom/atom-keymap#35 that could be the cause of this problem for you. Some people have reported good results from using the [keyboard-localization package](https://atom.io/packages/keyboard-localization).

**Comment by adamreisnz** [comment]
I have tested out this issue on a Macbook Air with the native keyboard using US and International keyboard layouts, on OS X 10.11.5 with Atom 1.15.

No problem cycling through windows, whether in normal order or in reverse order with the shift key.

**Comment by 50Wliu** [comment]
No reports since July of 2016, and keyboard-localization is now deprecated.  I believe it's safe to close this issue now.  If someone is still experiencing this, please create a new issue.  Thanks!
