### ISSUE TITLE
apm tests fail on latest commit 9ff5fb2

### ISSUE THREAD

**Issue by BrainCrumbz** [atom/atom#11543]
### Description

After synching source repository to latest commit and building Atom from scratch, running tests on Atom core fails.
### Steps to Reproduce
1. Move to root directory in Atom source repository 
2. Sync local repo with atom remote one
3. Build Atom from scratch
4. Run `apm test` from repository root

**Expected behavior:** 
Tests should all pass: 
- console should show only dots (`.`), no `F`s, 
- should show the number of ran/passed tests and 
- show a final green _Tests passed_ message.

Further, in order to check installed version, `atom --version` should show version string.

**Actual behavior:** 
Not all tests pass, some fails (see also output pasted at the bottom): 
- console shows some `F`s, 
- it does not show number of ran/passed/failed tests and
- it shows a final red _Tests failed_ message.

Further, `atom --version` does not show anything, it just quits after being lunched.

**Actual output:**

> D:\atom>apm test
> ............................F.F......FFFFF.F........F.F...F..------...............................................................................................................................................................................................................................................................................................................................F......................F....................................F...............................................................................F.FFF.................................................................................FF....................................................................................................................................................................................................................................F..F............................................................................................................................................................................................F................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
> Tests failed
### Versions
- latest commit: _language-make@0.22.0_ [9ff5fb2](https://github.com/atom/atom/commit/9ff5fb21fb0cccea293e43a36d3c04edd989df6c) dated April 20th 2016
- `atom --version` shows no output
- Atom version from `Help\About` menu: 1.9.0-dev-9ff5fb2
- `apm --version` shows:

```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4.windows.1
visual studio 2013
```
- OS version: Windows 10 64-bit

**Comment by 50Wliu** [comment]
Specs currently only pass on Mac.  @damieng is working on getting them to pass on Windows though.

**Comment by damieng** [comment]
#11488 is the first batch of fixes. Feel free to jump in!

**Comment by BrainCrumbz** [comment]
Thanks for such a quick info! @damieng , the plan was to start from 0 failed, so that we could add ours :smile_cat: . BTW, the current clone we did (from commit 9ff5fb2) already includes the mentioned PR.

**Comment by BrainCrumbz** [comment]
Two questions: 
1. should we close this? (I vote for Yes)
1. are there any more info on Windows failing specs? I could not find any in that PR thread

**Comment by damieng** [comment]
I don't think we actually have an issue to track it so we could use this one.

There are a whole bunch of failing tests. I don't have a definitive list as at least one test kills the spec runner...

**Comment by BrainCrumbz** [comment]
If it can help, we'd like to share our very recent experience: 

while working on a local branch, splitting some class in smaller, more focused ones, we were running just one test scenario by means of `fdescribe`. While splitting files, I accidentally forgot to assign a local variable that another variable was depending on: 

```coffeescript
#system32Path = path.join(process.env.SystemRoot, 'System32') # forgot to add this one
regPath = path.join(system32Path, 'reg.exe')
```

That mistake was enough to have `apm test` showing absolutely no test progress indicators and only *Tests failed* message:

```bash
D:\atom>apm test
Tests failed
```

In the same context, when instead I forgot some *system* import, like `fs = require 'fs-plus'`, we could see proper error messages, complete with stack-trace.
