### ISSUE TITLE
Bring back single click to open a file

### ISSUE THREAD

**Issue by ebordeau** [atom/atom#11540]
I used to be able to single click a file in the file tree to open it. Now there's the "Allow Pending Pane Items" setting. When turned on, a single click opens the file in a preview tab. When turned off, a single click does nothing. I don't like using the preview feature, but I also don't like needing to double click a file to open it. Can you bring back the single click to open a file when the preview option is turned off?

Using Atom 1.7.2

**Comment by 50Wliu** [comment]
This was discussed in #804 - see [this comment](https://github.com/atom/tree-view/pull/804#issuecomment-211542906) for the reasoning behind not bringing back this functionality.
