### ISSUE TITLE
"The editor has crashed"

### ISSUE THREAD

**Issue by h4v0c74** [atom/atom#11545]
When closing an open folder in the treeview which has other open folders in it, the editor will frequently crash.

**Reproduction Steps:**
1. Open a folder in treeview that has other folders in it.
2. Open one or more of the folders within the first folder.
3. Close and reopen the first folder until the crash.

**Expected behavior:**
Just close the folder, no crash.

**Observed behavior:**
Crash when closing the folder.

**Atom:**
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**OS and version:**
Windows 10 Pro (version 1511, 64bit)

**Installed packages:**
atom-grails
language-groovy
sort-lines

* Problem can be reproduced in safe mode: **YES**
* Problem started happening recently, didn't happen in an older version of Atom: **YES**
* Problem can be reliably reproduced, doesn't happen randomly: **NO**
* Problem happens with all files and projects, not only some files or projects: **YES**

**Comment by albertosantini** [comment]
I can reproduce it. 

- Problem can be reliably reproduced, doesn't happen randomly: YES

Should it be reported in tree-view project (with a better title)?

**Comment by h4v0c74** [comment]
That is probably a much better idea, I guess I should have done that to begin with... I will try to when I get a few minutes (currently at work).

**Comment by h4v0c74** [comment]
Moved to the tree-view project.
