### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by backspaces** [atom/atom#11548]
### Description

Seeming random crashs preceded by the dropdown image below.  Occur frequently, once a day or so. Often on first use in a while (morning etc)
### Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
### Versions

Crash details here:
backspaces/Atom Helper_2016-04-20-100803_MBP13.crash

OSX  10.11.4 Has occurred on both MBP & iMac, both bought within the year. 

MBP13|~/Library/Logs/DiagnosticReports[569]
: atom --version
Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

MBP13|~/Library/Logs/DiagnosticReports[570]
: apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.4.5

<img width="513" alt="snap 04 20 16-10 09 30" src="https://cloud.githubusercontent.com/assets/124366/14690959/fad64e4a-070b-11e6-9ae6-879ed0e0307f.png">

**Comment by lee-dohm** [comment]
Can you add a link to the crash report?

**Comment by backspaces** [comment]
I thought I did .. it's a gist as you asked for.
https://gist.github.com/backspaces/307533cfe24361b71e0d3e02a2b007a2

For some reason I though a secret one was required.  It's public now. Sorry.

   -- Owen

**Comment by lee-dohm** [comment]
Thanks!

**Comment by tedyun** [comment]
Atom started to crash VERY frequently for me, almost every hour, when I'm regularly typing in the editor. It started to happen very recently, probably 1.7.2 or 1.7.1 version. I can upload the crash log if someone can tell me where to find the log file on Windows.

Using Windows 10 x64, Atom 1.7.2.

**Comment by 50Wliu** [comment]
@tedyun From memory (on Ubuntu right now and not Windows) they're located in `%TEMP%\Atom Crashes`.

**Comment by lee-dohm** [comment]
@tedyun Please open a new Issue.

@backspaces What are you doing when Atom crashes? What size project are you working in? What size file? Please include as much information as you can.

**Comment by backspaces** [comment]
OK, I'll do better on my next report.

Generally I have 4-5 projects open, which tend to be large due to
node_modules and .git typically quite large like 30M for node_modules and
10M for .git.

And one window looks at a directory with daily notes files, it is the one
that generally crashes.  Here are the top sizes, generally 5 tabs or so:
-rw-r--r--@  1 owen  staff   519K Apr 21 21:40 Scrap
-rw-r--r--@  1 owen  staff   507K Apr  6 15:28 Think
-rw-r--r--@  1 owen  staff   474K Feb 27  2013 todo0
-rw-r--r--@  1 owen  staff   444K Apr 23 11:46 todo
-rw-r--r--@  1 owen  staff   331K Nov 28 20:44 Log
-rw-r--r--@  1 owen  staff   283K Apr 21 16:30 Work
-rw-r--r--@  1 owen  staff   166K Apr  9 12:23 AS
-rw-r--r--@  1 owen  staff   161K Sep 23  2013 Scrap0
-rw-r--r--@  1 owen  staff   157K Oct 27 11:33 Travel
-rw-r--r--@  1 owen  staff   144K Sep  9  2015 Learning
-rw-r--r--@  1 owen  staff   136K Apr  6 16:12 MiniLog
-rw-r--r--@  1 owen  staff   100K Jan  8  2011 Complex

**Comment by lee-dohm** [comment]
Do you have `node_modules` in your `.gitignore` for the project (or globally)?

**Comment by lee-dohm** [comment]
How much RAM do you have in the machine that the crash log belongs to?

**Comment by backspaces** [comment]
[image: Inline image 1]

**Comment by tedyun** [comment]
@lee-dohm Created new issue for Windows 10 x64 - https://github.com/atom/atom/issues/11590

**Comment by lee-dohm** [comment]
@backspaces You can't attach an image via email, it has to be done through the website.

**Comment by backspaces** [comment]
Sorry:

<img width="587" alt="snap 04 23 16-15 48 45" src="https://cloud.githubusercontent.com/assets/124366/14764195/84644452-096c-11e6-98de-8d088b80e81e.png">

**Comment by backspaces** [comment]
Another crash:
backspaces/Atom Helper_2016-04-25-131336_MBP13.crash
https://gist.github.com/backspaces/2a2ae2788522637df514ff93b1c2ae85

The computer was un-attended, I found the crash when coming upstairs from my work system to my laptop. It looks as if Dropbox may be part of the problem: I use the technique of having my ~/.atom point to a dropbox file.

I think I need to re-do that setup, it looked like the links were incorrectly done.

**Comment by backspaces** [comment]
Nope, the Dropbox links are fine. I forgot that I don't link all files, just these six. This was recommended by a post warning about not linking all the .atom files.

    config.cson
    init.coffee
    keymap.cson
    packages
    snippets.cson
    styles.less

**Comment by tomByrer** [comment]
I get a predictable crash OSX 10.11.4 opening a 400Kb CSS file; not sure to piggyback one of these large-file-crash reports, or open a new one?

**Comment by lee-dohm** [comment]
@tomByrer Please just add on to one of the existing issues.

**Comment by jsouthern** [comment]
I am also experiencing this behavior. I'm running OSX El Capitan (10.11.6). The first editor crash occurred using Atom 1.13.0 on January 20, 2017. The editor typically crashes when I try to open a file (regardless of size) and sometimes when I try to save the file. I've experienced this behavior also on 1.14.0 and 1.14.1.

I've tried all of the relevant advice in the flight manual (http://flight-manual.atom.io/hacking-atom/sections/debugging/). Even with all packages disabled, the crash still occurs.

Here is the most recent crash report from a crash that occurred this morning (02/14/2017): https://gist.github.com/jsouthern/9be4d1c2ef1e9aa5cccb5d09f6499490

**Comment by jcortell** [comment]
Same issue here.
I just updated to 1.17.2, but still getting a crash every time I try to start Atom in OSX 10.12.5, with the same message as previously posted by "backspaces" in first message in this issue:
https://cloud.githubusercontent.com/assets/124366/14690959/fad64e4a-070b-11e6-9ae6-879ed0e0307f.png
