### ISSUE TITLE
Not able to set a modul tab length to default if main settings are different 

### ISSUE THREAD

**Issue by henri-hulski** [atom/atom#11546]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I'm not able to set the tab length to the default value (2) in a language modul if I set a value in the main settings tab length,
It immediately changes to the tab length from the main settings.

See also issues Lukasa/language-restructuredtext#37 and atom/language-gfm#134.

### Steps to Reproduce

1. Set tab length in main settings to 4.
2. Go to the settings of language-html package and set the tab length to 2.
3. It immediately changes to 4.
4. When you leave it empty it shows `Default: 2`. But then also changes to 4. 

It should possible to change the value to the default 2.
Now you can change it to every other value (1,3,5,etc) but not to 2.

### Versions
1.7.2 and 1.8.0-beta2

System: Debian Jessie

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by jessebye** [comment]
Can confirm.

**Comment by lee-dohm** [comment]
Confirmed though this belongs on the [settings-view package](https://github.com/atom/settings-view). Would you mind reopening the Issue there?
