### ISSUE TITLE
strange behavior by opening New File with TreeView

### ISSUE THREAD

**Issue by stephanfriedrich** [atom/atom#11556]
### Description

hi, 
supposed i will work on a existing file style.css (actual with no changes) and i press `STRG + N`, the new window replace my "style.css" tab-window. 
if i change something, and press STRG + N`, the new file appear on a new tab-window.

### Steps to Reproduce

1. [start atom in some project folder]
2. [open a file within Tree View (don't edit these file]
3. [press 'STRG + N']

**Expected behavior:**
But imho, a new file should open a new tab-window.

**Actual behavior:** 
 the new window replace my "style.css" tab-window. 

### Versions
Atom 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1

**Comment by abejfehr** [comment]
I think you're referring to _Pending Panes_, which are a [feature in Atom](http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html).

Try disabling them in Settings > Allow Pending Pane Items and see if that resolves your issue

**Comment by lee-dohm** [comment]
This is the expected behavior when you have the "Allow Pending Pane Items" setting enabled as @abejfehr pointed out.

I hope that helps!
