### ISSUE TITLE
"Keep Waiting" dialog blocks until closed

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#11551]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

The "keep waiting" dialog that appears when Atom becomes unresponsive blocks until it is closed, preventing Atom from ever becoming responsive again until "keep waiting" is selected.  This is because Atom is performing a synchronous call to `dialog.showMessageBox` instead of an async one.  In addition, there is no code in place to automatically close the dialog if/when Atom does regain responsiveness.
### Steps to Reproduce
1. Get Atom into an unresponsive state and have the "keep waiting" dialog appear
2. Wait for Atom to become responsive again
3. :zzz:

**Expected behavior:** Atom to regain responsiveness

**Actual behavior:** Atom hangs forever until an option is selected
### Versions

```
Atom    : 1.9.0-dev-8ece1ee
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.0.windows.1
visual studio 2015
```

Windows 10 x64.

**Comment by 50Wliu** [comment]
Working on creating a PR for this now.  Just need to verify that my changes work first.

**Comment by PhiLhoSoft** [comment]
Yeah!
I posted a message about this in Discuss: https://discuss.atom.io/t/refinements-to-the-not-responding-keep-waiting-dialog/24375
I never got any reaction... :disappointed: 
I planned to open an issue about this, but you did it before! Thanks for that.

**Comment by 50Wliu** [comment]
Awesome, it would be great if you could test it!  Just comment on the linked PR above your comment.

**Comment by PointedEars** [comment]
Any progress on this?
