### ISSUE TITLE
The feature about "find in project" is so weakly!

### ISSUE THREAD

**Issue by zhangbg** [atom/atom#11555]
Compared to Notepad++, the feature about "find in project" is so weakly! Can anyone support a package about this feature?

**Comment by albertosantini** [comment]
Following the guidelines in the recent post [Managing the Deluge of Atom Issues](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html), this question would be better addressed to https://discuss.atom.io/

Thanks.
