### ISSUE TITLE
Can not delete folder

### ISSUE THREAD

**Issue by seanmars** [atom/atom#11557]
### Description

Can not delete or move the folder, if the folder have sub-folder and the sub-folder is unfolded.

### Steps to Reproduce

1. Create the folder A;
2. Create the folder B under A;
3. Unfold the folder B in the Tree View;
4. Delete A;

**Expected behavior:** Delete the folder A and B;

**Actual behavior:** Get error;

### Versions
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
apm  1.9.2
npm  2.13.3
node 0.10.40
python
git 2.7.4.windows.1
visual studio

OS: Windows 7 SP 1

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by lee-dohm** [comment]
Please reopen this on the [tree-view repository](https://github.com/atom/tree-view).
