### ISSUE TITLE
Opening Atom triggers a screenshot (Gnome)

### ISSUE THREAD

**Issue by romgrk** [atom/atom#11553]
Hello,

I've had this problem since ever, but I never opened an issue because this is a somewhat obscure problem; if anyone has answers, awesome. If not, it's really a minor disagreement.

Upon launching Atom, the electron window starts, and triggers a desktop screenshot before loading any more of the UI.

This happens on Gnome desktop, no matter how Atom was launched: command-line, icon-click, keybinding shortcut, shell switcher.

Not including version, because this has been happening since pre 1.0 until now (1.8).

**Comment by lee-dohm** [comment]
Can you include the OS version you're experiencing this on? Can you replicate the problem in Safe Mode?

**Comment by romgrk** [comment]
Yes, yes, Arch-4.5, closing because of http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html, this is really a minor inconvenience. But if anyone happens to find an explanation, plese send.

**Comment by lee-dohm** [comment]
Thanks for helping out! If we find anything, I'll update the issue.
