### ISSUE TITLE
Installing “react@0.15.0” failed

### ISSUE THREAD

**Issue by neznayka82** [atom/atom#11558]
I'm trying to install a package but I have an error, it is overcome without changing the OS

Error log:

> npm ERR! git clone C:\Users\неведомыйруслан\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f C:\Users\6158~1\AppData\Local\Temp\npm-9840-c4015d9c\git-cache-a7941daf6eeb\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: Cloning into 'C:\Users\6158~1\AppData\Local\Temp\npm-9840-c4015d9c\git-cache-a7941daf6eeb\1bd5044df1d6c888a1bd1b511158fb34b011e9aa'...
> npm ERR! git clone C:\Users\неведомыйруслан\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f C:\Users\6158~1\AppData\Local\Temp\npm-9840-c4015d9c\git-cache-a7941daf6eeb\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: error: cannot spawn sh: No such file or directory
> npm ERR! git clone C:\Users\неведомыйруслан\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f C:\Users\6158~1\AppData\Local\Temp\npm-9840-c4015d9c\git-cache-a7941daf6eeb\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: fatal: unable to fork
> npm ERR! git clone C:\Users\неведомыйруслан\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f C:\Users\6158~1\AppData\Local\Temp\npm-9840-c4015d9c\git-cache-a7941daf6eeb\1bd5044df1d6c888a1bd1b511158fb34b011e9aa: 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Users\\неведомыйруслан\\AppData\\Local\\atom\\app-1.6.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\неведомыйруслан\\AppData\\Local\\atom\\app-1.6.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\неведомыйруслан\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\неведомыйруслан\\.atom\\.apmrc" "install" "C:\\Users\\6158~1\\AppData\\Local\\Temp\\d-116321-11052-1i576d1\\package.tgz" "--target=0.34.5" "--arch=ia32"
> npm ERR! node v0.10.40
> npm ERR! npm  v2.13.3
> npm ERR! code 128
> 
> npm ERR! Command failed: Cloning into 'C:\Users\6158~1\AppData\Local\Temp\npm-9840-c4015d9c\git-cache-a7941daf6eeb\1bd5044df1d6c888a1bd1b511158fb34b011e9aa'...
> npm ERR! error: cannot spawn sh: No such file or directory
> npm ERR! fatal: unable to fork
> npm ERR! 
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>

**Comment by abejfehr** [comment]
Which package are you trying to install? Should this error not be reported to the author of that package?

**Comment by lee-dohm** [comment]
@neznayka82 Please file a new Issue and fill in the information requested in the template.
