### ISSUE TITLE
Reverting ctrl-tab to `pane:show-next-item` won't tab in order if tabs are rearranged via drag-and-drop or when using `Add New Tabs At End`

### ISSUE THREAD

**Issue by mitchellnemitz** [atom/atom#11563]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

After updating to Atom 1.7.2 and reverting the `ctrl-tab` and `ctrl-shift-tab` behavior via the config in the release blog post:

```
'body':
  'ctrl-tab ^ctrl': 'unset!'
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab ^ctrl': 'unset!'
  'ctrl-shift-tab': 'pane:show-previous-item'
```

`ctrl-tab` and `ctrl-shift-tab` no longer tab through panes in order if they have been rearranged via drag-and-drop or if you are using the `Add New Tabs At End` config option from the `tabs` core package and open a file with an active tab somewhere in the middle of the list.

### Steps to Reproduce

1. Copy the config block from the MRU Tab Change blog post into your `keymap.cson` file.
1. Open 3-5 files from the tree / fuzzy open / however. Verify that you can `ctrl-tab` through them in order.
2. Drag-and-drop to rearrange them, or enable `Add New Tabs At End` in the `tabs` core package and select a tab other than the last, then open a file via the tree or the fuzzy finder.
3. Attempt to `ctrl-tab` and see that the order for selection is wrong.

**Expected behavior:** You can `ctrl-tab` through your open files in order as you could in Atom < 1.7.x releases.

**Actual behavior:** `ctrl-tab` does not progress through visual tab order and instead appears to follow the order of when the files were opened.

### Versions

```
$ atom --version
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by lee-dohm** [comment]
Part of this is resolved in https://github.com/atom/tabs/pull/302. Reordering tabs by drag-and-drop may require a similar fix. Please reopen this Issue on the [tabs repository](https://github.com/atom/tabs).
