### ISSUE TITLE
Project Folders are removed when window is closed

### ISSUE THREAD

**Issue by juilyoon** [atom/atom#11566]
### Description

When you close every window without quitting the program, all the project folders are removed the next time you open a window.

### Steps to Reproduce

1. Close all windows `Cmd + Shift + W`
2. Open Atom

**Expected behavior:** Project folders in the same state I left them.

**Actual behavior:** All project folders have been removed.

### Versions
```
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.8.0

OSX 10.10.5
```

**Comment by bj7** [comment]
I thought that was a feature for the longest time, but that would be really nice if all my files would reopen automatically. I'll poke around and see what's up. 

I also noticed that upon reopening the window, the dialogue: "File-->Reopen Last Item" does nothing. Is that expected? 

> Atom    :1.7.2
> OSX 10.11.4

**Comment by juilyoon** [comment]
I don't think I complete projects often enough to justify a clearing of all project folders simply by closing the window.

**Comment by amytruong** [comment]
I can reproduce this as well. Looks like a regression but I'll check with @lee-dohm

**Comment by lee-dohm** [comment]
This is the expected behavior. When you open a new window when Atom is already running, it behaves the same by opening an empty environment. This is the same as right-clicking the Dock and selecting New Window or pressing <kbd>Shift+Cmd+N</kbd>.

**Comment by juilyoon** [comment]
@lee-dohm I can understand if you close the window with `Cmd+Shift+W`, but it doesn't feel right if I'm closing tabs and press `Cmd+W` one too many times, to then lose all my project folders.

**Comment by lee-dohm** [comment]
@juilyoon If you uncheck the "Close Empty Windows" setting then <kbd>Cmd+W</kbd> can no longer close windows on its own, you'll have to use <kbd>Shift+Cmd+W</kbd> to close windows. This will prevent the accidental loss of project folders.

<img width="608" alt="screen shot 2016-04-27 at 1 45 26 pm" src="https://cloud.githubusercontent.com/assets/1038121/14867693/9484d63e-0c7e-11e6-8369-f5c0f6f0591d.png">
