### ISSUE TITLE
Text cursor blinking after stopping switch between windows using ALT + TAB

### ISSUE THREAD

**Issue by samuelyeshua** [atom/atom#11561]
**Description:**
text cursor just disappears when I switch between open windows on the desktop using the rotation buttons. Only happens after you have changed a few times, the number of times changes, time in the first hour after.

[ y] Can you reproduce the problem in safe mode?
[ y] Are you running the latest version of Atom?
[ y] Did you check the debugging guide?
[ y] Did you check the FAQs on Discuss?
[ y] Are you reporting to the correct repository?
[ y] Did you perform a cursory search to see if your bug or enhancement is already reported?

**Steps to Reproduce**

1. Open the editor
2. Open a file
3. Switch between the open windows using the ALT + TAB keys sometimes
4. **Don't click** in the editor window

**Expected behavior:**
Even after switching between open windows in the course desktop continues to flash, so I can find me in the code

**Actual behavior:**
text cursor blinking after stopping switch window sometimes using the ALT + TAB

**Versions:**
`atom --version `
0.210.0-17235e7

`apm --version`
apm  0.171.0
npm  2.5.1
node 0.10.35
python 2.7.10
git 2.5.0

**OS:**
Ubuntu 15.10

**Comment by lee-dohm** [comment]
Please update to the latest version of Atom. If the problem can be reproduced on the latest version, please update the information and reopen the bug.
