### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createObjectStore' of undefined

### ISSUE THREAD

**Issue by AjiHajir** [atom/atom#11577]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Cannot read property 'createObjectStore' of undefined

```
At C:\Users\A71\AppData\Local\atom\app-1.7.2\resources\app.asar\src\state-store.js:10

TypeError: Cannot read property 'createObjectStore' of undefined
    at IDBOpenDBRequest.dbOpenRequest.onupgradeneeded (C:\Users\A71\AppData\Local\atom\app-1.7.2\resources\app.asar\src\state-store.js:10:11)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by GeorgeWL** [comment]
Also got this.

Cleared itself up almost immediately after load.

**Comment by rsese** [comment]
Thanks for the reports 👍   Since this is an older issue that wasn't triaged, I'll close in favor of https://github.com/atom/atom/issues/16781 where someone else hit the error in the current latest stable release.
