### ISSUE TITLE
Menus open behind application window

### ISSUE THREAD

**Issue by AshlynBlack** [atom/atom#11574]
### Prerequisites

* [Y] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [Y] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [Y] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [Y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom menus (File, Edit etc) open behind the application window.

### Steps to Reproduce

1. Fullscreen the window
2. Open a menu

**Expected behavior:** See the displayed menu

**Actual behavior:** Menu gets obscured by the application window

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

Both Ubuntu and Atom are fresh installs using the latest builds.
![virtualbox_ashlyns dev box_22_04_2016_21_50_45](https://cloud.githubusercontent.com/assets/9297796/14744145/0ad29196-08d8-11e6-8967-b6413af8ae55.png)

**Comment by Flos** [comment]
I can confirm the bug on Ubuntu 14.04 LTS, makes it unusable for me!
The title bar is acting normal, the Atom content window stays always on top.
![virtualbox_default_1461574038447_9069_26_04_2016_16_20_42](https://cloud.githubusercontent.com/assets/1560705/14821409/f2166362-0bca-11e6-9c90-399530290887.png)
![virtualbox_default_1461574038447_9069_26_04_2016_16_19_57](https://cloud.githubusercontent.com/assets/1560705/14821410/f21959a0-0bca-11e6-98b1-871802f5f642.png)

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1

**Comment by 50Wliu** [comment]
Can not reproduce on Ubuntu 16.04, Atom 1.9.0-dev-9175194.

**Comment by lee-dohm** [comment]
@AshlynBlack or @Flos Can you reproduce this behavior using Chromium?

**Comment by Flos** [comment]
@lee-dohm 
google-chrome is not installed, only the chromium-browser. If its integrated in the Atom package, I have no clue how to change the browser. I see no cli option for that. 

But I just looked a bit deeper in it. I started the chromium-browser using the terminal and got a error and a messed up webview, looked a bit like many broken textures. The error pointed me to a recent, Virtualbox 3D acceleration issue: http://permalink.gmane.org/gmane.comp.emulators.virtualbox.user/6225 

Now I disabled 3D acceleration in my VM and the chromium-browser is working fine, and also Atom.

I think it's an Virtualbox 3D driver bug not a Atom bug at all.
Thanks for the support!

**Comment by lee-dohm** [comment]
Glad to hear it is working for you @Flos. Any updates from you @AshlynBlack?

**Comment by isapa1984** [comment]
Well, I was having this same issue on Debian Jessie using Virtual Box 5.0.20 with 3d Acceleration on. Disabling 3D did the trick.

**Comment by Nikki1993** [comment]
Confirming same behaviour in VBox as others. Getting rid of 3D acceleration or downgrading guest additions resolves issue with Atom editor.

**Comment by hoto** [comment]
For a Vagrant/VirtualBox powered GUI machine workaround is to write this to `Vagrantfile`  

```ruby
vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
```

**Comment by lee-dohm** [comment]
Since there is no response from @AshlynBlack and it seems everyone else is having luck with either using a different version of guest additions or turning off 3D acceleration, I'm going to close this as resolved. Thanks everyone!

**Comment by draeath** [comment]
That's... that's not really a fix, just a (bad) workaround.

Assuming the atom code is fine (*pretty sure it is*). Has anyone opened a bug with Oracle?

**Comment by darrenleeweber** [comment]
Reproduced this issue, see related comment in
- https://github.com/atom/atom/issues/1959#issuecomment-238635590

**Comment by jrial** [comment]
In case anyone's interested, the VirtualBox guys have a wiki page describing the current situation: https://www.virtualbox.org/wiki/X11Guest3D

Unfortunately, it appears they lack the manpower to tackle this, and are counting on the community to provide patches. Needless to say, that hasn't happened yet.

I can confirm I still get the black screen permanently on top with VirtualBox 5.1.8, regardless of whether I install the matching guest additions or the 5.0.16 ones.

**Comment by KUGA2** [comment]
The same issue occurs with qtcreator welcome screen. 5.0.16 fixes it, but also disables 3D hardware accelleration. You can see this, because the "Unity Start Menu" is loading a lot slower.

**Comment by ichiriac** [comment]
You can also disable GPU only on atom application by creating a shortcut on the desktop and adding `--disable-gpu` argument to the application. 

![image](https://user-images.githubusercontent.com/173203/30247717-5a0bc798-961a-11e7-80a9-bb96f4c5ba45.png)

It's fixing the problem on atom and I still use 3d acceleration on ubuntu (works with any electron based application)

**Comment by draeath** [comment]
That's much more convenient than defining `LIBGL_ALWAYS_SOFTWARE=1` in the environment. Good find!
