### ISSUE TITLE
`core:copy-selection` doesn't copy.

### ISSUE THREAD

**Issue by MichaelJCole** [atom/atom#11572]
### Description

As referenced in #11542, this keyman.cson should copy only when text is selected.

```
'atom-text-editor':
  'ctrl-c': 'core:copy-selection'    # linux and windows
```

### Steps to Reproduce

1. change cson
2. select new text
3. ctrl-c
4. Change cursor insertion point
5. Ctrl-v

**Expected behavior:** [What you expected to happen]

New text was copied to clipboard.

**Actual behavior:** [What actually happened]

Old text pasted.  New text was never copied to clipboard.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

1.5.3

**Comment by Ben3eeE** [comment]
I can't find the command `core:copy-selection` in the command palette, settings view or when searching the repositories. There is `editor:copy-selection` that works. But I am using a newer version of atom.

Perhaps @lee-dohm said the wrong command in his comment and meant `editor:copy-selection`?

**Comment by MichaelJCole** [comment]
That would be consistent with my experience.

**Comment by lee-dohm** [comment]
@MichaelJCole Can you reproduce this on the latest version of Atom?
