### ISSUE TITLE
Quadruple Atom taking up 1.2GB!

### ISSUE THREAD

**Issue by eugenesvk** [atom/atom#11586]
I just realized I have four Atoms on my system gobbling up more than a gigabyte!

Two of them are in the `\AppData\Local\atom`. These I was aware of — still see no good reason for Atom to do that, also almost no other apps do that, but oh well.
But then I've discovered another double-Atom buried in the `\AppData\Local\SquirrelTemp` in nondescript "tempb" and "tempe" folders.
That's just ridiculous. With such a bad installation/upgrade design I'd rather go back to clicking one UAC prompt per upgrade rather than having the silent "convenience" of quadruple app!

Is there an option somewhere that I could enable to get rid of all this unnecessary quadruplication and go back to having just one and only one app — the latest version I'm using?
Thank you

Windows 10 x64
Atom versions app-1.6.2 and app-1.5.3 (plus whatever versions are left in the Squirrel folder)

**Comment by albertosantini** [comment]
By design, Atom keeps the two latest installations. At the moment I cannot find the thread explaining that decision: I think it is due to Squirrel machinery.

It seems the devs are aware about Atom not cleaning up some temp files, for instance,  https://github.com/atom/atom/issues/5570 and other.

Generally speaking, you may read the recent post about [issue guidelines](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).
Finally, please, feel free to talk about it on the official Atom forum at https://discuss.atom.io.

**Comment by eugenesvk** [comment]
The issues you linked is different - it's about packages, while mine it's about quadruple atom folder. But now that you mention those, I'll  go check and clean up package temp :)
I've also read the guidelines and this issue definitely "can be fixed, added, resolved, have a stake driven through its  heart". It shouldn't be otherwise for something almost all other apps are already doing.
I'm also registered on the forums.

> it is to Squirrel machinery

Atom could still just override it and remove the extra folders itself post install even if squirrel is bad enough not to do it.

**Comment by 50Wliu** [comment]
The ones in `%localappdata%\atom` are there by design.  You should have the latest version as well as one backup version in case anything goes wrong.

As for the ones in `SquirrelTemp`, it sounds like those aren't being cleaned up properly.  Can you please upload your `SquirrelSetup.log` file here?

**Comment by eugenesvk** [comment]
I know the first duplication is by design, that's I meant by `These I was aware of` means. So I can only reiterate that it's still a bad design that should be fixed (at least provide an option to disable it) — that's too high a cost to pay for "if anything goes wrong". If that happens, I'll just download the app again, not a big deal vs. wasting **300MBs** of space. All the settings are conveniently separated and can be just plugged in to a freshly installed app.

Re. logs I'm sorry, but I've just removed all squirrel files in the `SquirrelTemp` folder :( I'll keep an eye during the next update and upload them if I see them not being cleaned up.
However, I can provide [`SquirrelSetup.log`](https://gist.github.com/eugenesvk/d02cdf526f0c0ae0f1f86d0be10d6ffb) in the `\AppData\Local\atom` folder if that is of any help

**Comment by 50Wliu** [comment]
Yup, that's the log I was talking about :).

And regarding the duplication...Chrome does the same thing (not that that means it's the correct thing to do, of course).  I personally think it's helpful, but maybe that's just me.

/cc @paulcbetts @damieng

**Comment by paulcbetts** [comment]
Just delete SquirrelTemp

**Comment by eugenesvk** [comment]
> Chrome does the same thing

Yep, Chrome is a notorious resource hog for disk space and memory. Don't mind if you find it helpful (though interested whether you've actually ever used this feature in any of the few apps that offer it), just for me there is no justification — I've never had a single case when I wished I had a duplicate app and can't even imagine such a case (I'd just download and reinstall the app or use my distributives backup on another drive). 

> Just delete SquirrelTemp

That's no solution, it's a bad design to require manual removal of temp install files (while at the same time keeping the user in the dark about it and placing them **outside the expected temp** folder to make it even harder to discover them)! The app is supposed to clean after itself. So don't understand why you closed it.

**Comment by paulcbetts** [comment]
> That's no solution, it's a bad design to require manual removal of temp install files

I agree! In fact, I agree so much that I designed it to clean up temp files - something weird happened on your machine, because these files are normally cleaned up. Sorry about that!

> keeping the user in the dark about it and placing them outside the expected temp folder to make it even harder to discover them

This isn't to keep the user in the dark, it's to protect against machines whose Temp folder is broken, permissioned incorrectly, or otherwise unusable - we have found *many* users whose computers are in this state. Creating our own folder protects us against this.

**Comment by paulcbetts** [comment]
Also, if you give me your full name and address, I will be glad to personally pay the $3 to send you a USB stick with enough disk space to run Atom, temp files and all.

**Comment by eugenesvk** [comment]
> designed it to clean up temp files

Sorry, from your comment I didn't understand that the leftovers were just a bug, I wrongly assumed there was no built-in facility to cleanup those files. In this case it's not such a big deal.

> to protect against machines whose Temp folder is broken

May I suggest that you at least rename it to TempSquirrel so it's physically right there with Temp? That would've helped me spot the issue much earlier.

I'd also kindly nudge you to enable the option of not leaving the old version either so I don't have to clean that up manually. Or at least add something unique to the folder name (e.g. `app-1.2.3-old` or something) so I can add this to my CCLeaner ini file and delete it automatically as part of regular system maintenance.
Thank you

**Comment by damieng** [comment]
@paulcbetts There are a couple of ways a failure could jump to failedExtract after starting the extraction and I don't see any cleanup of SquirrelTemp.

https://github.com/Squirrel/Squirrel.Windows/blob/9de260cb6b614234511d57723738f1be2ed25476/src/Setup/UpdateRunner.cpp#L260

**Comment by paulcbetts** [comment]
afaik it gets cleaned up in the C# side
