### ISSUE TITLE
tree-view fails to show git-status changes on OSX

### ISSUE THREAD

**Issue by Daemoen** [atom/atom#11582]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom 1.7.2 on OSX does not show tree-view git status changes

### Steps to Reproduce

1. Install Atom
2. Open Atom
3. Add project folder that includes git repositories

**Expected behavior:** [What you expected to happen]
4. Look at tree-view and see summarized git status  (orange for modified, green for added, etc)

**Actual behavior:** [What actually happened]
4. Look at tree-view and see no colors

### Versions
atom --version
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.1

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

OS Info:
     System Version: OS X 10.11.3 (15D21)
      Kernel Version: Darwin 15.3.0

Screenshot:
![screen shot 2016-04-22 at 4 29 33 pm](https://cloud.githubusercontent.com/assets/1039884/14757660/ca7f73ac-08aa-11e6-9e88-29ab95d667a5.png)

**Comment by Daemoen** [comment]
Hmmm, so apparently, tree-view does not update unless you have a file open from a given project Devs can decide if this is an actual bug or expected behavior)  This might be the same issue as https://github.com/atom/atom/issues/10831  (so possibly a persistent bug, based on their version and mine?).

I have verified that if I *open* a file from the project, then it updates the color scheme, but have not verified wether or not the auto-refresh issue is still present in my release.  I'll try to verify that later for more info.

**Comment by Daemoen** [comment]
Did a small bit of experimenting and found that the highlighting itself *does* work, provided you are not having it *recurse* a folder.  IE:  if you have all projects under $USER/projects/project{a..e}; you must have each of the projects opened separately for highlighting to work, it will not recurse through the projects and highlight.  If you have projecta, projectb etc opened individually, it works.

**Comment by albertosantini** [comment]
It seems Git integration doesn't work if .git/ is not in top level.

Dupe https://github.com/atom/atom/issues/2203?

Generally speaking, you may read the recent post about [issue guidelines](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

**Comment by classicemi** [comment]
I have the same problem after updating my atom from 1.8.0 to 1.9.0. Also found the the same problem in 1.10.0 beta. It works great in 1.8.0. Still not sure the reason.

**Comment by marszall87** [comment]
Same problem here.

atom --version
Atom    : 1.9.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.5.4

OS Info:
ProductName: Mac OS X
ProductVersion: 10.11.5
BuildVersion: 15F34

**Comment by smcouch** [comment]
I'm having this problem, too, after updating from 1.8.0 to 1.9.2...

**Comment by calvinbrewer** [comment]
Same problem here as well. Atom recognizes git status when I save a particular file, but when I change applications (Atom to Chrome for example) and then back to Atom, my changes are lost until I save the file again...Repeat. 

Works properly (Git status not lost) when I only have one repo opened in Atom.

Atom: 1.9.2

Saving file: 
<img width="137" alt="screen shot 2016-08-04 at 8 59 02 am" src="https://cloud.githubusercontent.com/assets/10352306/17406699/c64c7884-5a21-11e6-9976-15801acaa9da.png">

After switching applications and back to Atom: 
<img width="75" alt="screen shot 2016-08-04 at 9 00 08 am" src="https://cloud.githubusercontent.com/assets/10352306/17406717/df0c3576-5a21-11e6-8a7a-f3699edc7e6c.png">

**Comment by 50Wliu** [comment]
Everyone experiencing this issue on 1.9.x, please subscribe to atom/tree-view#906 instead.  Thanks.
