### ISSUE TITLE
Where are bundled APM packages installed on Linux and how to install extra packages there?

### ISSUE THREAD

**Issue by fusion809** [atom/atom#11584]
Hi,

I would like to create an AUR package to install Atom and the `package-sync` package of Lee Dohm, as it would simplify the process of installing the packages one wants, if one regularly switches between Arch Linux installations. It would pull in the `atom-editor` package as a required dependency and then, when building the package, run some command to install the `package-sync` package. AUR packages are usually better off installing packages to one's `/usr` directory than to one's home directory the way that apm does by default. For example, Node packages in the AUR use the `/usr` directory and packages are installed there using the command:

```bash
npm install --user root -g --prefix $pkgdir/usr $_npmname@$pkgver
```

so it would help me to know where the APM packages that come bundled with Atom are installed to, by default, on Linux platforms. I have tried searching the contents of Atom Linux binary packages for such a location but I can't find one, so I assume there is something I am missing. Plus, please tell me how I might specify the install location for APM packages, analogously to how the `--prefix` flag does for NPM packages. 

Thanks for your time,
Brenton

**Comment by 50Wliu** [comment]
They should be in `/usr/local/share/atom/resources/app.asar` (at least on Ubuntu).  I do not believe there is a way to specify where Atom packages should be installed.

In addition, in accordance with [Managing the Deluge of Atom Issues](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html), as this is not a bug or enhancement, it would be better suited to being on https://discuss.atom.io.  Just something for next time :).
