### ISSUE TITLE
Add native OS X Notifications

### ISSUE THREAD

**Issue by bretonics** [atom/atom#11585]
Several times a notifications pops up in Atom, I miss reading it in it's entirety, and I think adding the notifications to the native OS X notifications bar would be great and more streamlined.

**Comment by 50Wliu** [comment]
I believe Atom notifications should be contained within Atom itself (since some of them won't make sense without context) - atom/notifications#29 should be similar to what you're asking for.

**Comment by bretonics** [comment]
Well, can a 'Notifications Center' be added to see recent notifications?

**Comment by mnquintana** [comment]
@bretonics Yup! That should be covered by https://github.com/atom/notifications/issues/29. 😄
