### ISSUE TITLE
Atom doesn't open. Error: Module version mismatch. Expected 47, got 46.

### ISSUE THREAD

**Issue by creat89** [atom/atom#11598]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported??

### Description

I've updated Atom to the last version and it doesn't open. Instead of it, when I tried to open Atom it opens like the web console of Firefox where I can see all the HTML elements and use debugger. I believe it is the debugging tool of Atom.

I am using an Arch Linux distribution and I built myself Atom for the installation. In other words, I downloaded the git repository and built Atom.

Attached is the log.
[-1461595807126.txt](https://github.com/atom/atom/files/234816/-1461595807126.txt)

### Steps to Reproduce

1. Open Atom

**Expected behavior:**  Open Atom

**Actual behavior:**  Open Atom debugger?

### Versions

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.0g.

**Comment by lee-dohm** [comment]
* Did you try to build Atom from source at some point?
* What OS are you running into this on?

**Comment by creat89** [comment]
Sorry, I thought I indicated that:

I built myself Atom to install it because I have a Arch Linux distribution. So, I followed the instructions to do it by downloading the git repository. I will, update my question to add the OS.

**Comment by 50Wliu** [comment]
Can you try running `script/clean` and then `script/build` again?

**Comment by creat89** [comment]
No it didn't work. I have uninstalled everything and tried again. The problem still the same.

**Comment by lee-dohm** [comment]
You should be able to fix this by going to your local Atom repository and:

1. Delete the `node_modules` directory
1. `script/clean`
1. `script/build`

**Comment by creat89** [comment]
No, it didn't work either. I add the script/build output:
[install.txt](https://github.com/atom/atom/files/254495/install.txt)

**Comment by lee-dohm** [comment]
There is something hanging out somewhere that you didn't completely delete when you followed my steps. You need to perform a 100% clean build. My only recommendation at this point is to delete anywhere Atom is installed, delete any Atom packages you have installed, delete the Atom repository completely and start over from the beginning.

**Comment by creat89** [comment]
I deleted everything. Atom was unistalled and I builded atom from zero. I got installed Atom beta, but it crashes when it is open. The normal version of atom was not installed as expected.

**Comment by lee-dohm** [comment]
The reason that this error message shows up is because some native modules were compiled against an older version of Chromium than the one that is running. Deleting all that I mentioned in my last post would destroy all previous native modules and there wouldn't be a conflict anymore.

**Comment by creat89** [comment]
Well, I've uninstalled Atom again, following the same instructions posted [here](http://stackoverflow.com/questions/23621181/how-to-uninstall-atom-text-editor-on-linux)

I've downloaded the source code, not using the git command but the .tar.gz that it is found in Git. I've compiled everything. Now, I have the normal version of Atom 1.7.3 but it crashes when it is open. So, the error of Expected 47, got 46, has been solved. But a new problem has appeared.

**Comment by adambuczynski** [comment]
I have the same problem now when trying to build Atom from the latest master commit (ad24aae).

![image](https://cloud.githubusercontent.com/assets/490562/18104012/4087b6aa-6f4d-11e6-93c3-b3a39d8117e8.png)
(pardon the screenshot, I can't copy paste from the dev tools console)

**Comment by adambuczynski** [comment]
The above steps worked for me.
