### ISSUE TITLE
Pane resizer goes through other panes

### ISSUE THREAD

**Issue by JetLua** [atom/atom#11592]
### screenshots
---
**os: windows 7**
**version: 1.7.2**

![screenshots](https://lufei.so/t.gif)

**Comment by 50Wliu** [comment]
Reproduced on Atom 1.9.0-dev-9175194, Windows 10 x64.

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/atom/issues/10121?

**Comment by Ben3eeE** [comment]
Also maybe https://github.com/atom/atom/issues/7446?

**Comment by 50Wliu** [comment]
Closing as a duplicate of #7446 - thanks @Ben3eeE!
