### ISSUE TITLE
.git causes crash

### ISSUE THREAD

**Issue by luclu** [atom/atom#11594]
Reproducible on
OSX **10.11.4** - Atom **1.7.2**
Ubuntu **14.04** - Atom **1.7.2**

`.git`-folder of the Repository https://github.com/ethereum/mist causes a crash - also in `safe`-mode.

**Comment by Bigous** [comment]
Windows 10 too...

**Comment by lee-dohm** [comment]
Confirmed using Atom v1.7.3 on Mac OS X 10.11.4.

Crash log: https://gist.github.com/lee-dohm/572d6f40525a0998d2a2b4665e7bc67b

**Comment by luclu** [comment]
This also happens using the electron based http://gitkraken.com.

**Comment by luclu** [comment]
This problem seems to be resolved in atom `1.10.2`.
