### ISSUE TITLE
Atom crashes on opening a panel

### ISSUE THREAD

**Issue by SoonDead** [atom/atom#11599]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Everytime I try to open any panel, atom crashes with the "The editor has crashed" dialog.

Which crash report should I include here?

### Steps to Reproduce

1. Open atom
2. Open anything, a file, the settings, etc.
3. Recieve the crash dialog.

**Expected behavior:** To not crash

**Actual behavior:** Crash

### Versions

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.0.windows.1
visual studio 2013

Windows 10 Professional x64

**Comment by lee-dohm** [comment]
Can you try launching Atom with `atom --clear-window-state` and see if that fixes it?

**Comment by SoonDead** [comment]
Reinstalling atom fixed it, and now I can't reproduce the problem. Are there reports or logs of the crash i should share that would still be useful to determine the original cause?

**Comment by lee-dohm** [comment]
You may be able to find something in the Windows Event Log. Crashes are supposed to be reported there.

**Comment by lee-dohm** [comment]
Since this is fixed for you. I'm going to close it. Please let us know if the problem reoccurs!
