### ISSUE TITLE
Atom wants to connect to **keep.google.com** on port 443

### ISSUE THREAD

**Issue by jacobbuck** [atom/atom#11596]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When launching Atom, LittleSnitch reports that:

<img width="735" alt="Atom wants to connect to **keep.google.com** on port 443 (https)" src="https://cloud.githubusercontent.com/assets/830470/14771502/7f8d2612-0ae1-11e6-8357-47e6226582cd.png">

### Steps to Reproduce

1. Launch Atom
2. See LittleSnitch dialog

**Expected behavior:** [What you expected to happen]

Atom doesn't connect to keep.google.com, so there's no LittleSnitch dialog.

**Actual behavior:** [What actually happened]

Atom attempts connecting to keep.google.com, so LittleSnitch displays a dialog.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
$ atom --version
Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.4
```

OS X 10.11.4 (15E65)

**Comment by paulcbetts** [comment]
Little Snitch often gets confused when it attempts to reverse-lookup the IP address into a DNS name when an IP is serving >1 DNS name (this happens all the time in AWS). This is most likely Google Analytics.

**Comment by jacobbuck** [comment]
Ah, that would make sense thanks.

Also noticed Evernote attempting to connect to accounts.youtube.com, must be related 😏
