### ISSUE TITLE
memory leak when alt-tabbing (most likely only with .atom added to the tree view)

### ISSUE THREAD

**Issue by unic0rn** [atom/atom#11591]
windows 7, single - small - file opened.

when alt-tabbing, going back to atom causes a spike in cpu and memory usage - memory gets allocated, deallocated, it looks like something is going on, and sometimes there's a little bit less allocated after that, but more often than not - more. after a few moments of alt-tabbing, 150mb turns into 300mb, after a while - into over 1gb of ram, used for nothing.

heap profiling shows constant 42mb. safe mode - same thing. looks like a bug.

latest stable version, everything checked. and i'm just updating this issue, because i've found one little important detail - the problem occurs when one (of two in my case) folders added to the tree view is .atom - it doesn't matter if the tree view is hidden. after removing .atom from the tree view, memory leak doesn't happen. there's a small cpu spike but nothing that major, and there's no major memory allocation change. weird.

**Comment by unic0rn** [comment]
well, i'm not 100% certain about the lack of leak without .atom in the tree view - but the change is very small, 1mb per - more than ten? - alt-tab cycles, and often doesn't happen at all. so i would say that's some random and usual stuff. worth checking out, but it's borderline on nitpicking (unless it gets worse with more, bigger files - not sure).

chewing away hundreds of megabytes with .atom in the view though - that happens pretty fast.

**Comment by unic0rn** [comment]
no .atom in the tree view, single file opened, platformio terminal opened at the bottom - small but consistent (less than 1mb per alt-tab cycle) raise of memory usage. i know, it's a package, but still, there's a pattern here that i think needs investigating.

**Comment by 50Wliu** [comment]
@unic0rn So to clarify: does the increase in memory usage happen in safe mode (`atom --safe`) as well?

**Comment by unic0rn** [comment]
yes.

it is worst with .atom folder in the tree view though, without it the increase with time is much slower. noticeable with terminalio active for example.

i'm not sure what's at play here, it looks like some handler launched when the window gets focus, does something that has a potential to leak memory, and if it does and to what degree, depends on current window contents/active panels.

**Comment by lee-dohm** [comment]
Could you specify which version of Atom you're running?

**Comment by unic0rn** [comment]
1.7.2 - just noticed that 1.7.3 is out, will comment after update and further testing.

**Comment by unic0rn** [comment]
tested. exactly same thing.

**Comment by lee-dohm** [comment]
@unic0rn Can you replicate the problem in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by 50Wliu** [comment]
@lee-dohm I already asked above and he replied in the affirmative.

@unic0rn What is "terminalio"?  Is that an Atom package?

**Comment by lee-dohm** [comment]
Whoops ... sorry I missed that everyone :blush:

**Comment by unic0rn** [comment]
@50Wliu https://atom.io/packages/platformio-ide-terminal
doesn't matter though, because it's happening in safe mode as well. maybe it's related to some core package, but i lack deep understanding of atom's architecture so i've got no idea what's being called when the window gets focus, and why is it sometimes chewing memory.

**Comment by 50Wliu** [comment]
The Git status gets refreshed every time the window is focused, so that's definitely a possibility.  Is your .atom folder a git repository?

**Comment by unic0rn** [comment]
it sits inside a git repository.

.git/
.atom/
atom/

and so on.

so what you're saying is that if there's a git repo in the tree view, it will chew away memory on each alt-tab, and the amount depends on the size of the folder added to the tree view?

**Comment by 50Wliu** [comment]
Well, I wouldn't say "chew away memory"...but yes, it's supposed to make sure the Git statuses are updated whenever you focus the window.  The amount of memory it takes is also probably related to the size of the repository, as it would have to look through all the files and folders.

Going to tentatively cc @joshaber here.

**Comment by unic0rn** [comment]
if wasting forever hundreds of megabytes of ram (it doesn't free that memory later, so it's a leak) doesn't count as chewing, then i don't know what does.

**Comment by joshaber** [comment]
Yes, it's not surprising that it's using memory when activated. Certainly the less we use the better, but I don't see any bug here. It sounds like the memory gets freed so it's not a leak really.

**Comment by unic0rn** [comment]
it sounds like the memory gets freed?

that's the whole reason i'm reporting it. it is not being freed, unless you count a jump from 150mb to over 1gb of allocated memory over some hours of usage as "not a leak".

**Comment by unic0rn** [comment]
test case scenario:

create a folder (in my case it's a separate partition - an image file mounted using truecrypt actually), fill it with few gigabytes of files and dirs, create a git repo with 99% of that excluding some configs and logs put into .gitignore, then put into .gitignore:
.atom/.apm/
.atom/.node-gyp/
.atom/blob-store/
.atom/compile-cache/
atom/
put atom and .atom - as can be seen above - in that folder, launch atom, add some folder to the tree view, add .atom to the tree view, launch task manager, start alt-tabbing and watch the cookie monster in action. that's precisely my setup when it comes to .atom dirs i have in .gitignore, not sure if it really matters.

what i do know is that those cpu spikes and - especially - memory usage increases with each alt-tab in such scenario, are not normal.

**Comment by lee-dohm** [comment]
@unic0rn do you have a repo that you can share that reproduces this problem?

@damieng Can you reproduce this behavior?

**Comment by unic0rn** [comment]
@lee-dohm unfortunately, no.

but there's one more detail which i've just realized, it shouldn't make a difference, but hell knows. my git repositories are created and managed using cygwin build of git. files created by cygwin have a little bit different default permissions/ownership afair, but as i've said, it shouldn't make any difference.

**Comment by unic0rn** [comment]
if you can give me a full debug build of atom (so basically with debug-everything, from node to webkit - whole electron and stuff), i'll throw it at valgrind and see what sticks.

**Comment by unic0rn** [comment]
forget the last comment, i just woke up -.-

but hey, there's dr. memory for windows. so yeah, the part about debug build still holds.
