### ISSUE TITLE
tree view not working

### ISSUE THREAD

**Issue by haasDev** [atom/atom#11601]
### Prerequisites

* [Y ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ Y] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ Y] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [Y ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

tree view not toggling with ctrl-\ or ctrl-shift-p

### Steps to Reproduce

1. open atom in a directory
2. try to toggle tree view with ctrl-\
3. try to toggle tree view with ctrl-shift-p

**Expected behavior:** tree view to open and close

**Actual behavior:** unresponsive

### Versions

Windows version 7

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.4.windows.1
visual studio 2013

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by 50Wliu** [comment]
Please make sure the `tree-view` package is enabled (you can do this by going to Settings -> Packages and searching for Tree View).  Do you have Nuclide installed?

**Comment by haasDev** [comment]
That was it. I should've caught that. Sorry.

**Comment by 50Wliu** [comment]
No worries...Tree View sometimes gets into a bad state when other packages disable it and forget to re-enable it when they're disabled/uninstalled themselves.

**Comment by sethlivingston** [comment]
BAD Nuclide!
