### ISSUE TITLE
Uncaught DOMException: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned.

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#11608]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Periodically seeing the following error pop up in the console.  My session state doesn't seem to be saving as a result.

```
Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned.
    at Error (native)
    at dbPromise.then.db (C:\Program Files\Atom\resources\app.asar\src\state-store.js:33:12)
```
### Steps to Reproduce
1. Unsure, unfortunately.  Just started happening out of nowhere.  Perhaps it's because I haven't opened up this particular project since around the beginning of March, which I think is before the new state-store code was added?

**Expected behavior:** No errors, and session state to be saved properly after restarting Atom.

**Actual behavior:** See error above :(.
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.9.0-dev-9175194
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.0.windows.1
visual studio 2015
```

/cc @kuychaco maybe?

**Comment by 50Wliu** [comment]
I suspect something is broken with this project state - anything I can provide to help debug before I `--clear-window-state`?

**Comment by kuychaco** [comment]
Hmm nothing comes to mind for me. /cc @as-cii who may have some ideas

**Comment by as-cii** [comment]
It's possible that some package is trying to serialize something that [IndexedDB doesn't support](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#Things_that_don%27t_work_with_structured_clones).

If you can still reproduce, it'd be nice to open the DevTools and enable `Pause on exceptions` (the rightmost icon in the picture below), and make sure the `Async` checkbox is set:

![screen shot 2016-05-02 at 11 55 50](https://cloud.githubusercontent.com/assets/482957/14951954/db699ea4-105c-11e6-86c5-e4b0c62ee217.png)

With the DevTools open, whenever the error is triggered, the debugger should stop [somewhere around here](https://github.com/atom/atom/blob/master/src/state-store.js#L26-L40), and you can try to poke around in the console to get information about what went wrong in the request. In particular, it might be nice to get a dump of what's inside `key` and `value`, maybe looking out for stuff that IndexedDB doesn't support (e.g. `Error` objects, DOM nodes, etc.).

From there, you could try to backtrack and understand where that value comes from. It'd be awesome if you could post the dump here and, if you'd like to investigate, your findings too. Thanks, @50Wliu!

**Comment by 50Wliu** [comment]
And...can't reproduce anymore after switching to the Electron 0.37 branch.  Will reopen if it starts occurring again.

**Comment by willdawsonme** [comment]
I've had this happen a few times when saving the current project's state using `atom.serialize`. A restart seems to fix it, but doesn't prevent it from happening again. When pausing on the uncaught exception, I'm unable to `JSON.stringify(value)` because it contains circular references; maybe this is why the object can't be cloned? At any other time, I'm able to stringify the value.

Next time it happens I'll do some more digging to see which slice of the value is causing the issue!

**Comment by skandasoft** [comment]
I am getting it too

**Comment by abe33** [comment]
I think it should be reopened because it's still happening a lot for me (on Atom's reload). And as is it's really tough to find which package is causing the serialization to fail.

**Comment by 50Wliu** [comment]
Make sure you're not passing around DOM elements as parameters.
