### ISSUE TITLE
Atom TopMost on VirtualBox Ubuntu Machine

### ISSUE THREAD

**Issue by LeMerP** [atom/atom#11609]
### Description

If you run Atom on Ubuntu Trusty or Xenial within a VirtualBox environment under Windows 10, the Atom window has always a topmost state.

### Steps to Reproduce

1. Install Ubuntu 14.04 / 16.04 VirtualBox VM under Windows 10
2. Install Atom from deb-file.

**Expected behavior:** 
Atom window should not become top most. Other windows like the application switcher are not accessible. 

**Actual behavior:**
Atom window state is top most.

### Versions

1.7.2, 1.8.0-beta2

**Comment by paras20xx** [comment]
@LeMerP I see this same issue on a fresh installation of Ubuntu 16.04 (on VirtualBox v5.0.20 with extension pack and guestbox additions). Were you able to fix it?

**Comment by paras20xx** [comment]
Alright, found the solution in https://github.com/atom/atom/issues/11574 :-)

The issue is due to some bug in VirtualBox 3D acceleration. Solution which worked for me is mentioned in: https://github.com/atom/atom/issues/11574#issuecomment-216051670
