### ISSUE TITLE
git not interfacing with Atom correctly

### ISSUE THREAD

**Issue by boster99** [atom/atom#11605]
### Prerequisites

* [**Yes**] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [**Yes**] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [**Yes**] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [**Yes**] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [**I think so**] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [**Yes**] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

'm a new user of Atom and Git. I've configured git to use Atom as its core editor. Mostly Atom works for me; and mostly, git works for me. Together, they aren't happy.

Atom is configured as the editor in this manner: git config --global core.editor "'C:/users/[user]/appdata/local/atom/bin/atom.cmd' --new-window --wait"

I've also tried it without the "--new-window" flag, with no difference in result.

When I issue a "git commit" command, I get some form of the following, IF THERE'S NO CURRENT
INSTANCE OF ATOM:

```
App load time: 545ms
[1228:0424/183520:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[1228:0424/183520:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[1228:0424/183520:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[1228:0424/183520:WARNING:accelerator_util.cc(118)] Invalid accelerator token: command
[1228:0424/183522:INFO:CONSOLE(52)] "Window load time: 1483ms", source: file:///C:/Users/[user]/AppData/Local/atom/app-1.7.2/resources/app.asar/static/index.js (52)
[1228:0424/183525:INFO:CONSOLE(1282)] "Error refreshing repository status:", source: C:\Users[user]\AppData\Local\atom\app-1.7.2\resources\app.asar\src\git-repository-async.js (1282)
[1228:0424/183525:INFO:CONSOLE(1283)] "Error: Reference 'refs/heads/master' not found", source: C:\Users[user]\AppData\Local\atom\app-1.7.2\resources\app.asar\src\git-repository-async.js (1283)
[1228:0424/183525:INFO:CONSOLE(392)] "Uncaught (in promise) Error: Reference 'refs/heads/master' not found", source: node.js (392)
[1228:0424/183526:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source: (0)
error: There was a problem with the editor ''C:/users/[user]/appdata/local/atom/bin/atom.cmd' --new-window --wait'.
Please supply the message using either -m or -F option.
```

If there IS ALREADY a current instance of Atom, then instead I get this:

```
App load time: 815ms
error: There was a problem with the editor ''C:/users/[user]/appdata/local/atom/bin/atom.cmd' --new-window --wait'.
Please supply the message using either -m or -F option.
```

In neither case does the commit succeed.

I don't know whether the "-m" or "-F" option would solve the problem, but if it will I'm not sure how to supply one of those.

I've done very little configuration with git and Atom, so they're both very close to "out of the box" with regard to customization.

Can anyone help?

-boster

### Steps to Reproduce

1. Configure Atom as the default editor for git, in gitbash, with this line of code:
```
git config --global core.editor "'C:/users/[user]/appdata/local/atom/bin/atom.cmd' --new-window --wait"
```
2. Commit a change to a repository

**Expected behavior:** 
I expect an Atom window to open with git commit details, and a place for me to enter a commit message. Upon closing this Atom window, I expect the commit to be executed and succeed.

**Actual behavior:** 
The Atom window does open, and I edit my message and close the window. But instead of executing the commit, the commit fails.

### Versions

**From apm --version:**
apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.1.windows.1
visual studio

**From Windows command ver:**
Windows 10.0.10586

**From atom --version:**
Atom 1.7.2
Electron 0.36.8
Chrome 47.0.2526.110
Node 5.1.1

**Comment by 50Wliu** [comment]
Thanks for the detailed report @boster99!

/cc @damieng

**Comment by damieng** [comment]
Sorry, missed this condition when I switched over to start-process to handle quoted parameter names. 
Now fixed in master, if you need it in an older version you can just grab the atom.cmd referenced and drop it into your atom's resource/cli folder.
