### ISSUE TITLE
Starting half window with specific project

### ISSUE THREAD

**Issue by jsveron23** [atom/atom#11607]
- atom --version

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

- os version

osx 10.11.4

1. I tried to open specific named project but it never goes with full window but another project are fine when open.
2. I tried to launch on the safe(-safe) mode but nothing change.
3. I tried to delete .atom directory but still same problem (actually, _$ mv .atom atom_bak_ then re-launch)
4. I changed specific directory name then it works but I do not want to change directory name.
5. I couldn't find any specific settings for the project.

<img width="1280" alt="screenshot 2016-04-26 07 35 16" src="https://cloud.githubusercontent.com/assets/156895/14801259/f44ba536-0b82-11e6-8ae4-879129e7f770.png">

**Comment by jsveron23** [comment]
<img width="614" alt="screenshot 2016-04-26 08 00 56" src="https://cloud.githubusercontent.com/assets/156895/14801563/18b03584-0b85-11e6-8640-f71606d24102.png">

- flex-grow

**Comment by emileber** [comment]
I'm having a similar issue with a atom 1.7.2 and flex-grow at like 0.90

**Comment by emileber** [comment]
I disabled every community packages installed and the problem was still there. I tried `Reload window` and a complete close/reopen of atom and nothing worked.

I finally closed the project folder and restarted Atom and got the 10% missing (from the flex-grow) back. I reopened the same project folder and everything seems fine for now.

**Comment by emileber** [comment]
After accidentally typing the wrong command in the command palet, I discovered that there is `Pane: Decrease Size` which cuts of 10% of the pane space. So not a bug, just a well hidden feature.

**Comment by lee-dohm** [comment]
For future reference, state is no longer serialized in the `~/.atom`directory (in reference to step 3 in the list of things you tried @jsveron23). To wipe out any saved state now, you can launch Atom using `atom --clear-window-state`. I tested this approach and it fixed up the shrunken pane.
