### ISSUE TITLE
The editor has crashed error (fresh install)

### ISSUE THREAD

**Issue by Almoullim** [atom/atom#11612]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)? **yes**
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? **yes**
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? **yes**
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)? **yes**
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? **yes**
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported? **yes**
### Description

![screenshot_2016-04-26_18-45-25](https://cloud.githubusercontent.com/assets/8402210/14824811/f253e95c-0bdf-11e6-8896-59d09d4548eb.png)

**The editor has crashed**
Please report this issue to https://github.com/atom/atom
### Steps to Reproduce
1. Start Atom

**Expected behavior:** Atom to start
**Actual behavior:** Atom crashed
### Versions

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.0

**Comment by Almoullim** [comment]
### System:
           Host: Almoullim Kernel: 4.1.19-1-MANJARO x86_64 (64 bit gcc: 5.3.0)
           Desktop: Xfce 4.12.3 (Gtk 2.24.28)
           Distro: ManjaroLinux 15.12 Capella
### Machine:
           System: ASUSTeK (portable) product: K53SV v: 1.0
           Mobo: ASUSTeK model: K53SV v: 1.0
           Bios: American Megatrends v: K53SV.216 date: 04/27/2011
### CPU:
           Dual core Intel Core i5-2410M (-HT-MCP-) cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 9183
           clock speeds: max: 2900 MHz 1: 1058 MHz 2: 1044 MHz
           3: 1103 MHz 4: 1018 MHz
### Graphics: 
           Card-1: Intel 2nd Generation Core Processor Family Integrated Graphics Controller
           bus-ID: 00:02.0
           Card-2: NVIDIA GF108M [GeForce GT 540M] bus-ID: 01:00.0
           Display Server: X.Org 1.17.4 driver: intel
           Resolution: 1366x768@60.00hz, 1920x1080@60.00hz
           GLX Renderer: Mesa DRI Intel Sandybridge Mobile
           GLX Version: 3.0 Mesa 11.1.2 Direct Rendering: Yes
### Audio:
           Card Intel 6 Series/C200 Series Family High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: ALSA v: k4.1.19-1-MANJARO
### Network:  
           Card-1: Qualcomm Atheros AR9285 Wireless Network Adapter (PCI-Express)
           driver: ath9k bus-ID: 03:00.0
           IF: wlp3s0 state: up mac: e0:b9:a5:9c:f0:c9
           Card-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8168 port: a000 bus-ID: 04:00.0
           IF: enp4s0 state: down mac: f4:6d:04:11:70:67
### Drives: 
           HDD Total Size: 500.1GB (7.7% used)
           ID-1: /dev/sda model: ST9500325AS size: 500.1GB
           ID-1: swap-1 size: 8.92GB used: 0.01GB (0%) fs: swap dev: /dev/sda2
### Info:      
           Processes: 195 Uptime: 5:36 Memory: 2575.5/3867.0MB
           Init: systemd Gcc sys: 5.3.0
           Client: Shell (bash 4.3.421) inxi: 2.2.36

**Comment by djibi2** [comment]
I am having this issue today as well.  Atom will not start.  This was happening with an older version (which I can't remember) so I updated to 1.7.2 but it still would  not start.

I renamed  my ~/.atom directory to ~/.atom.back and it started fine.

**Comment by lee-dohm** [comment]
@djibi2 Please open a new Issue, unless you're using the exact same version of Linux that @Almoullim is?

**Comment by drewmnoel** [comment]
@Almoullim you're using an Arch derivative, what version of `freetype2` do you have? There's a known issue in `Electron 0.36.8` with `freetype2 >= 2.6.3`

**Comment by djibi2** [comment]
No, I wasn't running an Arch derivative (Ubuntu 14.04).  Since reporting the issue is no longer present and so I can not provide any additional useful information.

**Comment by DamnedScholar** [comment]
@Almoullim Try checking out the latest code and building. I have two Arch-derivative computers happily running Atom built from the 1.9.0 development code (the one on my machine next to me is 1.9.0-dev-b9dbb81) and haven't seen a single problem.

**Comment by pantuts** [comment]
Have this issue too before.
What i did was install `freetype2-infinality`, removed `freetype2` then changed package electron version to `0.36.9`.
All was set now.
