### ISSUE TITLE
rhino-python Atom Package Install Error

### ISSUE THREAD

**Issue by bmpietras** [atom/atom#11623]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I have a fresh install of the latest version of Atom on Mac OS X 10.11.4. I am attempting to install the package [rhino-python](https://atom.io/users/mcneel) (v.0.8.2, current), resulting in a failure and the appearance of an error message. See below.

### Steps to Reproduce

1. Download Atom from website.
2. Move Atom to /Applications.
3. Run Atom by double-clicking its icon.
4. Navigate to the Preferences pane --> Packages --> +Install
5. Search for "rhino."
6. Attempt to install "rhino-python," distributed by McNeel, by clicking the Install button.

**Expected behavior:** 

I would expect this to be successful, since the steps taken directly reflect the instructions by the package's developer.

**Actual behavior:** [What actually happened]

The install fails resulting in the appearance of this message:

```
npm WARN addRemoteGit git+https://git@github.com/vuejs/vue.git#b3c529992e322daa4c3a486137730078edd22ffd resetting remote /Users/bmpietras/.atom/.apm/_git-remotes/https-git-github-com-vuejs-vue-git-7c0a9863 because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/bmpietras/.atom/.apm/_git-remotes/_templates --mirror https://git@github.com/vuejs/vue.git /Users/bmpietras/.atom/.apm/_git-remotes/https-git-github-com-vuejs-vue-git-7c0a9863: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Darwin 15.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/bmpietras/.atom/.apm/.apmrc" "--userconfig" "/Users/bmpietras/.atom/.apmrc" "install" "/private/var/folders/wg/wt3x9xq91cv0dk35m7dwck0m0000gn/T/d-116325-2735-1sw8139/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 1
npm ERR! Command failed: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/wg/wt3x9xq91cv0dk35m7dwck0m0000gn/T/apm-install-dir-116325-2735-1rip9z8/npm-debug.log
```

The problem has been reported, as instructed at the NPM repository, to little attention.

### Versions

Atom v. 1.7.2
rhino-python v. 0.8.2

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by arbalhara** [comment]
Hi bmpietras,
I am having the same issue, but with version 0.8.4. Were you able to resolve the issue. Can you please share the solution with me.
