### ISSUE TITLE
File Open Behavior

### ISSUE THREAD

**Issue by winter-muted** [atom/atom#11625]
When opening an existing file for editing, sometimes the file replaces already open
tabs.  Other times, a new tab is created.  Began after updating to Atom 1.7.

## Repro Steps

1. Have a project tree open.
2. Open an existing file.
3. Open another existing file by selecting it from the tree, or using the fuzzy finder.

**Expected:** Consistent file open behavior.        
**Actual:** Seemingly random opening.

## Versions

* **Atom:**       1.7.1
* **OS:**         linux 4.5.0-1-ARCH
* **Misc**
    * apm  1.9.2
    * npm  2.13.3
    * node 0.10.40
    * python 3.5.1
    * git 2.8.0

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by CraZySacX** [comment]
That's a feature.   Pending Panes.

You can turn off Pending Pane in the settings.

**Comment by winter-muted** [comment]
Thanks!
