### ISSUE TITLE
Atom install failed on arch linux

### ISSUE THREAD

**Issue by vyasriday** [atom/atom#11624]
I am using arch linux with kernel 4.4.5-1 on a 64 bit machine
I am getting the following error while running 
script/build
 the atom editor in arch linux. I am following the following steps
https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

make: error while loading shared libraries: libatomic_ops.so.1: cannot open shared object file: No such file or directory
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 127
gyp ERR! stack     at ChildProcess.onExit (/home/hridayesh/atom/build/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/home/hridayesh/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hridayesh/atom/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
make: error while loading shared libraries: libatomic_ops.so.1: cannot open shared object file: No such file or directory
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 127
gyp ERR! stack     at ChildProcess.onExit (/home/hridayesh/atom/build/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/home/hridayesh/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hridayesh/atom/apm/node_modules/atom-package-manager/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
make: error while loading shared libraries: libatomic_ops.so.1: cannot open shared object file: No such file or directory
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 127
gyp ERR! stack     at ChildProcess.onExit (/home/hridayesh/atom/build/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/home/hridayesh/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hridayesh/atom/apm/node_modules/atom-package-manager/node_modules/git-utils
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.4.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/home/hridayesh/atom/build/node_modules/.bin/npm" "--userconfig=/home/hridayesh/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v5.10.1
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hridayesh/atom/apm/npm-debug.log

**Comment by Alexis-Martin** [comment]
If you want, you can install atom from the AUR: 
[https://aur.archlinux.org/packages/atom-editor/](url)

**Comment by vyasriday** [comment]
Well Alexis-Martin Thanks for reply but the link that you provided, it is not working.
I have already tried to install atom-editor package by yaourt but it shows -
"atom-editor not found in AUR"

**Comment by Alexis-Martin** [comment]
You right, if you copy-paste the link in a new tab it's work... I don't know why. :)

It's strange, for me the command `yaourt -a atom-editor` give me this : 
```
1 aur/atom-editor 1.7.2-1 [installed] (555) (63,29)
    Chrome-based text editor from Github
2 aur/atom-editor-beta 1.8.0.beta2-1 (5) (1,53)
    Chrome-based text editor from Github - Beta Channel
3 aur/atom-editor-beta-bin 1.8.0.beta2-1 (21) (3,22)
    Chrome-based text editor from Github - Beta Channel - Precompiled binary from official repository
4 aur/atom-editor-bin 1.6.2-1 (Out of Date) (242) (26,64)
    Chrome-based text editor from Github - Precompiled binary from official repository
5 aur/atom-editor-git 1.1.0.beta.0.r178.g575d79a-2 (40) (0,32)
```

**Comment by tinchoz49** [comment]
using the package from aur ```atom-editor``` or ```atom-editor-beta``` it happens the same error.

here is the log taked from yaourt
```
==> atom-editor-beta dependencies:
 - alsa-lib (already installed)
 - desktop-file-utils (already installed)
 - gconf (already installed)
 - gtk2 (already installed)
 - libgnome-keyring (already installed)
 - libnotify (already installed)
 - libxtst (already installed)
 - nodejs (already installed)
 - nss (already installed)
 - python2 (already installed)
 - git (already installed) [makedepend]
 - npm (already installed) [makedepend]

==> Building and installing package
==> Making package: atom-editor-beta 1.8.0.beta2-1 (Wed Apr 27 14:06:28 ART 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading v1.8.0-beta2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123    0   123    0     0    161      0 --:--:-- --:--:-- --:--:--   161
100  9.8M  100  9.8M    0     0  1368k      0  0:00:07  0:00:07 --:--:-- 2037k
  -> Found atom-beta.desktop
  -> Found package.patch
==> Validating source files with sha256sums...
    v1.8.0-beta2.tar.gz ... Passed
    atom-beta.desktop ... Passed
    package.patch ... Passed
==> Extracting sources...
  -> Extracting v1.8.0-beta2.tar.gz with bsdtar
==> Starting prepare()...
patching file package.json
patching file spec/atom-environment-spec.coffee
patching file spec/module-cache-spec.coffee
patching file spec/window-event-handler-spec.coffee
Hunk #1 succeeded at 75 with fuzz 2.
patching file src/module-cache.coffee
==> Starting build()...
Node: v5.6.0
npm: v3.6.0
Installing build modules...
=> Took 200776ms.

Installing apm...
../src/main.cc: In function ‘void {anonymous}::Init(v8::Handle<v8::Object>)’:
../src/main.cc:52:53: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [12], Nan::NAN_METHOD_RETURN_TYPE (&)(Nan::NAN_METHOD_ARGS_TYPE))’
   Nan::SetMethod(exports, "getPassword", GetPassword);
                                                     ^
In file included from ../src/main.cc:1:0:
../node_modules/nan/nan.h:1853:17: note: candidate: void Nan::SetMethod(v8::Local<v8::Object>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1853:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::Object>’
../node_modules/nan/nan.h:1865:17: note: candidate: void Nan::SetMethod(v8::Local<v8::FunctionTemplate>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1865:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::FunctionTemplate>’
../node_modules/nan/nan.h:1876:17: note: candidate: void Nan::SetMethod(v8::Local<v8::ObjectTemplate>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1876:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::ObjectTemplate>’
../src/main.cc:53:53: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [12], Nan::NAN_METHOD_RETURN_TYPE (&)(Nan::NAN_METHOD_ARGS_TYPE))’
   Nan::SetMethod(exports, "addPassword", AddPassword);
                                                     ^
In file included from ../src/main.cc:1:0:
../node_modules/nan/nan.h:1853:17: note: candidate: void Nan::SetMethod(v8::Local<v8::Object>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1853:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::Object>’
../node_modules/nan/nan.h:1865:17: note: candidate: void Nan::SetMethod(v8::Local<v8::FunctionTemplate>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1865:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::FunctionTemplate>’
../node_modules/nan/nan.h:1876:17: note: candidate: void Nan::SetMethod(v8::Local<v8::ObjectTemplate>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1876:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::ObjectTemplate>’
../src/main.cc:54:59: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [15], Nan::NAN_METHOD_RETURN_TYPE (&)(Nan::NAN_METHOD_ARGS_TYPE))’
   Nan::SetMethod(exports, "deletePassword", DeletePassword);
                                                           ^
In file included from ../src/main.cc:1:0:
../node_modules/nan/nan.h:1853:17: note: candidate: void Nan::SetMethod(v8::Local<v8::Object>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1853:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::Object>’
../node_modules/nan/nan.h:1865:17: note: candidate: void Nan::SetMethod(v8::Local<v8::FunctionTemplate>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1865:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::FunctionTemplate>’
../node_modules/nan/nan.h:1876:17: note: candidate: void Nan::SetMethod(v8::Local<v8::ObjectTemplate>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1876:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::ObjectTemplate>’
../src/main.cc:55:55: error: no matching function for call to ‘SetMethod(v8::Handle<v8::Object>&, const char [13], Nan::NAN_METHOD_RETURN_TYPE (&)(Nan::NAN_METHOD_ARGS_TYPE))’
   Nan::SetMethod(exports, "findPassword", FindPassword);
                                                       ^
In file included from ../src/main.cc:1:0:
../node_modules/nan/nan.h:1853:17: note: candidate: void Nan::SetMethod(v8::Local<v8::Object>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1853:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::Object>’
../node_modules/nan/nan.h:1865:17: note: candidate: void Nan::SetMethod(v8::Local<v8::FunctionTemplate>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1865:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::FunctionTemplate>’
../node_modules/nan/nan.h:1876:17: note: candidate: void Nan::SetMethod(v8::Local<v8::ObjectTemplate>, const char*, Nan::FunctionCallback)
 NAN_INLINE void SetMethod(
                 ^
../node_modules/nan/nan.h:1876:17: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Object>’ to ‘v8::Local<v8::ObjectTemplate>’
make: *** [Release/obj.target/keytar/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/yaourt-tmp-<user>/aur-atom-editor-beta/src/atom-1.8.0-beta2/build/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.8-1-MANJARO
gyp ERR! command "/home/<user>/.nvm/versions/node/v5.6.0/bin/node" "/tmp/yaourt-tmp-<user>/aur-atom-editor-beta/src/atom-1.8.0-beta2/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/yaourt-tmp-<user>/aur-atom-editor-beta/src/atom-1.8.0-beta2/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.4.8-1-MANJARO
npm ERR! argv "/home/<user>/.nvm/versions/node/v5.6.0/bin/node" "/tmp/yaourt-tmp-<user>/aur-atom-editor-beta/src/atom-1.8.0-beta2/build/node_modules/.bin/npm" "--userconfig=/tmp/yaourt-tmp-<user>/aur-atom-editor-beta/src/atom-1.8.0-beta2/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v5.6.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.
```

**Comment by tinchoz49** [comment]
@vyasriday updating the version of apm to 1.9.3 fix the problem, at least in my case. Please, try that.

Change the version in your atom repository <atom repo>/apm/package.json

**Comment by lee-dohm** [comment]
Since this seems to have moved on to a discussion around the yaourt package, I'm going to close this. 

Also, [we're trying to control the amount of Issues that we have to triage](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions or discussions, [the Atom message board](https://discuss.atom.io) is the best location.

**Comment by vyasriday** [comment]
Ok Thanks . well that is working now. Thanks tinchoz42 for that.
But got and issue again. 
When trying to run 
sudo scrip grunt/install i get the following error.

sudo script grunt/install          
Script started, file is grunt/install
script: cannot open grunt/install: No such file or directory
                                                            Script done, file is grunt/install
Segmentation fault

Can you help me with that. 
I think that might a small issue and i do not want to open a new issue just for that.

**Comment by 50Wliu** [comment]
@vyasriday It's `sudo script/grunt install`.

**Comment by vyasriday** [comment]
@50Wliu see the next output which i got by running sudo script grunt/install

**Comment by 50Wliu** [comment]
It is `sudo script/grunt install`, not `sudo script grunt/install`.  If you're still having trouble after this, please create a new topic on [Discuss](https://discuss.atom.io).

**Comment by Announcement** [comment]
What's wrong with installing from source? (as a Gentoo user I'd say you should ALWAYS install from source when possible ;) )

**Comment by vyasriday** [comment]
@50Wliu  I am really sorry ,I couldnot see that. 
But i am still having issues.
Thanks for your help
