### ISSUE TITLE
ERROR Spawn flake 8 ENOENT

### ISSUE THREAD

**Issue by muesuum** [atom/atom#11622]
Hello. Im a total noob and i just followed Pluralsight course that stated that i need a text editor with text highlighting for python. Thats how i got here: http://www.marinamele.com/install-and-configure-atom-editor-for-python

followed the steps more-or-less,
though i did not use

$ pip install flake8
$ pip install flake8-docstrings
$ apm install linter-flake8

because it did not seem to work, or i dont know how to make it work, so i just used Settings-» install

After the install did not preform 
![image](https://cloud.githubusercontent.com/assets/18697615/14848670/7798c9e2-0c77-11e6-91be-69ddb0f4108e.png)

because i have different error. and i dont know how to get to Atom - open yout init script

So linter-flake8 gives me this pesky error: 
![image](https://cloud.githubusercontent.com/assets/18697615/14848331/ca730b0c-0c75-11e6-96c9-dc1ca34633d2.png)

Note that i tried to reinstall the whole atom, run it in administrator mode etc. And its the only package that produces errors. I grabbed some other packages too and they seem fine.

...aand i have no idea how to solve it. I browsed some similar issues here, but i do not understand the answers given. I only suspect that it points to some unexisting file in temp, since i read something similar here and saw this: https://www.youtube.com/watch?v=1Vz2fbjIrU4    How should i fix that?

I have windows7,
Atom should be latest, installed it today. 
Tried the debugging manual, but i do not know how to do most of the stuff described there. Like running stuff from terminal. What terminal? cmd? 

So how do i get rid of this error? i do not want to disable the package, because it should catch errors that i am bound to make. 

Please bear with me if i am asking something stupid, or in the wrong place. Im doing my best.
### Prerequisites

* [ X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[After installing Linter-flake8 in Atom I get ENOENT error]

### Steps to Reproduce

1. [Install Atom]
2. [Install Linter-flake8]
3. [get enjoying your errors]

**Expected behavior:** [No errors]

**Actual behavior:** [gave error, even after reisntalling the whole thing]

**Comment by 50Wliu** [comment]
Please report this error to linter-flake8 instead.  Thanks!
