### ISSUE TITLE
alt-tab switch to Atom on Windows 10: ~ 5 secs

### ISSUE THREAD

**Issue by merl-dev** [atom/atom#11621]
this is a killer, if I have to count to 5 every time I switch back to Atom.  On Amazon EC2 c4.xlarge instance this goes down to 1-2 secs.  Clearly there is an optimization issue here.

Completely fresh install of latest version, no packages apart from the default installs. 

Now I try to uninstall and find the job half done, with at least 2 folders in AppData + .atom

And yes, I know these are already documented issues.  But they need to float up to top priority, because they are definitely app killers.

**Comment by 50Wliu** [comment]
As you mentioned that these are already documented issues, I will be closing this one in favor of those in order to keep discussion unified.
