### ISSUE TITLE
cursor in wrong column in soft wrapped line when using tabs

### ISSUE THREAD

**Issue by UziTech** [atom/atom#11630]
### Description

The cursor looks like it is in the (`x`-1)th column to the left of where it actually is. Where `x` is the tab width.
![animation](https://cloud.githubusercontent.com/assets/97994/14867272/5b2f4090-0c8d-11e6-919c-9b295cb31b9a.gif)

In the above GIF I am pressing the [Backspace] key and the character after the blinking cursor is being deleted then the cursor moves one character to the left
### Steps to Reproduce
1. Type a long string with tabs so the tabs are past the edge of the editor (make sure tabs are used not spaces)
2. Turn on Soft Wrap (`View -> Toggle Soft Wrap` if it isn't on)
3. Turn on Invisible Characters
4. Try to edit the wrapped part of the line

**Expected behavior:** [What you expected to happen]
Same as editing the non wrapped part of the line

**Actual behavior:** [What actually happened]
The cursor looks like it is the width of a tab - 1 characters to the left of where it actually is
### Versions

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

OS: Windows 10

**Comment by UziTech** [comment]
It looks like the wrapped line is actually moved to the right by (tabWidth - 1) characters and the cursor is in the correct position

**Comment by UziTech** [comment]
looks like it only happens when invisible characters are turned on

**Comment by Ben3eeE** [comment]
I have no problems reproducing this with the steps given, what I did:

1. Ensure I have tab type set to hard, soft wrap on and invisibles on.
2. Open a new tab and type a single a.
3. Tab until wrapping and a few more times, after wrap cursor is behind (tabWidth - 1) invisibles.
4. Add another a and it is the wrong position and this issue happens.

There is no way to select the incorrect (tabWidth - 1) characters. editor:select-to-end-of-line, editor:move-to-end-of-screen-line all ignore this character, and cursor is in the wrong position.

More things feel wrong with similar steps though:

If I disable invisibles and do the same steps the cursor stays in the first column on the second line.
1. Ensure you have tab type set to hard, soft wrap on and invisibles off.
2. Open a new tab and type a single a
3. Tab until wrapping to new line.
4. Tabbing again never moves cursor it is stuck in the first column, tabbing does however increase scrollbar size.

If I use soft tabs and do the same steps the cursor moves to the first column.
1. Ensure you have tab type set to soft, soft wrap on and invisibles on.
2. Open a new tab and type a single a
3. Tab until wrapping to new line and a few more times.
5. Type a single a, all invisibles disappear (No longer visible but they are there) and typed a moves to the first column of the second line.

Windows 7 atom 1.7.3 in safe mode.

// cc @lee-dohm reproduced and should I create separate issues for the other things or keep them here?

**Comment by lee-dohm** [comment]
@Ben3eeE They all seem related, so leave them here for now.

**Comment by lee-dohm** [comment]
This might be addressed by the new DisplayLayer changes on `master`. I'll have to test it out on Monday though.

**Comment by lee-dohm** [comment]
Things stacked up over the weekend. I'll have to get to this tomorrow unfortunately.

**Comment by lee-dohm** [comment]
I was able to reproduce the problem using @Ben3eeE's first set of repro steps.
