### ISSUE TITLE
tunneling socket could not be established, cause=Parse Error 

### ISSUE THREAD

**Issue by shikelong** [atom/atom#11637]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

hi.I use atom under the Great FireWall In China and under the proxy network in my company.

my proxy config look like next:

```bash
http-proxy = "http://user:psw@10.**.0.1:8080/"
https-proxy = "http://user:psw@10.**.0.1:8080/"
proxy = "http://user:psw@10.**.0.1:8080/"
strict-ssl = false
```

But It not work. when I use `apm install` or search packages or themes in atom.it show a error message:

```bash
 failed
Request for package information failed: tunneling socket could not be established, cause=Parse Error (5 attempts) (ECONNRESET)
```

thanks.

### Versions

atom 1.7.2
apm  1.9.2
npm  2.13.3
node 0.10.40
python
git 2.8.1.windows.1
visual studio 2010

**Comment by albertosantini** [comment]
You may give a look at https://github.com/atom/apm/issues/322.

The workaround it seems setting `ATOM_NODE_URL`.
Finally I suggest to add comments in that issue, if you have troubles.

Generally speaking, you may read the recent post about [issue guidelines](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

**Comment by 50Wliu** [comment]
Thanks @albertosantini!

**Comment by arvinthkumar** [comment]
@shikelong its worked for me.. Thanks !!

**Comment by amolnw2778** [comment]
## Steps to resolve this problem on Windows 7:

![image](https://cloud.githubusercontent.com/assets/3804871/24861848/ccd3d188-1e17-11e7-937c-00ed725024ba.png)

1. Open the location of **Atom installed folder**
2. Go to `Atom\resources\app\apm\node_modules\atom-package-manager\lib\`
3. Open `config.js`
4. Go to `getNodeUrl ()` function
5. Comment default returning url
6. Paste `return process.env.ATOM_NODE_URL;`

![image](https://cloud.githubusercontent.com/assets/3804871/24862001/76813f22-1e18-11e7-9daa-bc88eda1896f.png)

**Comment by navinprasadk** [comment]
for me atom-package-manager is mising @amolnw2778

**Comment by amolnw2778** [comment]
@navinprasadk Try installing [atom-package-manager](https://github.com/atom/apm) manually. If that doesn't work in your case, you should consider re-installing the latest [Atom](https://atom.io/)!

**Comment by navinprasadk** [comment]
how to manually install the atom-package-manager? @amolnw2778
