### ISSUE TITLE
Mouse buttons 8/9 cannot be listened to from Atom

### ISSUE THREAD

**Issue by capaj** [atom/atom#11638]
Most mouse devices today not made by Apple have more than two button.
To be precise, my mouse is this one: http://myego.cz/img/razer-logitech/mx518.jpg
I would love if I could use all of my buttons in Atom. Currently I tried:
```javascript
document.addEventListener('mousedown', (e) => console.log(e))
``` 

But that doesn't trigger when I use my mouse's back/forward button.
I did a quick search and came to:
https://github.com/jostrander/mouse-forward-back

I would be perfectly satisfied if I could at least listen to 5 buttons left click, right click, middle click and those forward/back buttons.

My versions:
Atom    : 1.7.1
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11+
git 2.7.4

**Comment by albertosantini** [comment]
It seems an enhancement request.

You may give a look at at https://discuss.atom.io/t/enhancement-support-for-all-available-mouse-buttons/16800.

Generally speaking, you may read the recent post about [issue guidelines](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

**Comment by 50Wliu** [comment]
@capaj So just to clarify: do mouse buttons 1-7 work?

**Comment by lee-dohm** [comment]
To my understanding, Atom supports left, right and middle click on all platforms. While it would be nice to have support for more mouse buttons, I don't think that this is something that the Atom team is going to have the bandwidth to work on any time soon. If someone wants to work on this and needs help creating a quality pull request, please do contact me here or on the [Atom Slack](http://atom-slack.herokuapp.com/).

**Comment by a7madgamal** [comment]
I really don't get the idea behind closing such issue?
sure, not having the time is completely understandable. but this doesn't mean the issue is not there!
it's like deleting a todo item that I don't have the time to do now!
closing it will just slowly kill it over time
However, it's 1000000 times better than locking issues. it should be illegal :D
