### ISSUE TITLE
Atom doesn't remember full-screen state if it's started without a project context

### ISSUE THREAD

**Issue by jbarnette** [atom/atom#1163]
1. Open Atom without context, via Spotlight or Applications
2. Full-screen Atom
3. Quit
4. Open Atom the same way

I expect Atom to still be full-screen, but it's not.

/cc #1144

**Comment by Unicyde** [comment]
Using System Preferences, I got Terminal opening in full screen, but I don't remember where I found that setting...

**Comment by stereobooster** [comment]
It should do so for `restorePreviousWindowsOnStart: true`. It doesn't as of now

**Comment by cardmist** [comment]
http//:www.tradessilver.com
