### ISSUE TITLE
Filenames display with normalized spaces in tabs

### ISSUE THREAD

**Issue by jodekirk** [atom/atom#11647]
Opening a file with multiple spaces in the filename displays as one space.
It appears to be normalizing whitespace in the display of the filename.
For example a filename with 2 or more spaces displays in the tab as one space:
"811347  1_por.xml"
displays as 
"811347 1_por.xml"

This screenshot shows two filenames where one has multiple spaces and one that has only one space. They look identical in the tabs title.
![image](https://cloud.githubusercontent.com/assets/1869259/14918625/993d12f0-0dea-11e6-887b-5dc2f45b54dd.png)

Atom 1.7.2 Windows 7 64bit

**Comment by lee-dohm** [comment]
This is a side-effect of displaying filenames using HTML :grinning:

You      can      see      the      same      effect      here,      each      word      in       this      sentence      has     six      spaces      in       between      them.

It should definitely be fixed though. Please reopen this on the [tabs repository](https://github.com/atom/tabs).

**Comment by damieng** [comment]
Fix here is to change the `whitespace: nowrap` on the .tab .title class to be `whitespace: pre-nowrap`

**Comment by damieng** [comment]
This actually also affects the tree-view as well.

**Comment by lee-dohm** [comment]
We could convert regular spaces to `&nbsp;` for display:

Testing&nbsp;&nbsp;&nbsp;&nbsp;Testing&nbsp;&nbsp;&nbsp;&nbsp;Testing&nbsp;&nbsp;&nbsp;&nbsp;Testing

With proportional fonts it is still hard to tell the difference between one space and two, but it is more accurate than what we're showing now.
