### ISSUE TITLE
ctrl-tab goes through tabs in a very confusing order

### ISSUE THREAD

**Issue by yourpalal** [atom/atom#11650]
### Description

I'm not sure what happened here, this was working fine until recently. Now, when I ctrl-tab or ctrl-shift-tab, I jump all over the place, from tab to tab in no apparent order. Sometimes it goes to the right, sometimes to the left, etc..

I think maybe it's using a recently-used order, but I don't think it used to do this. The problem persists in safe mode. I tried to fix it by overriding the commands in my keymap, but to no avail. The keybinding resolver seems to indicate that pane:show-next-item is being used correctly..

### keymap

'body':
  'ctrl-shift-W': 'pane:close-other-items'
  'ctrl-shift-tab': 'pane:show-previous-item'
  'ctrl-tab': 'pane:show-next-item'

### Steps to Reproduce

1. open some tabs
2. press ctrl-tab

**Expected behavior:** [What you expected to happen]
3. move to the next tab

**Actual behavior:** [What actually happened]
4. move to a tab, maybe the next one, maybe not

### Versions

Atom Version 1.7.3

**Comment by yourpalal** [comment]
I forgot to mention, ctrl-pgup / ctrl-pgdown, which are mapped to the same things, work correctly.. I think maybe the problem has to do with the bindings on ctrl-tab ^tab ^ctrl, which changes the recently-used order?

**Comment by 50Wliu** [comment]
Yes, Ctrl+Tab is now in most-recently-used order.  You can change your keybindings by following the instructions in [this post](https://github.com/atom/atom/issues/11035#issuecomment-209875101).

**Comment by yourpalal** [comment]
@50Wliu  thanks for the update. It's very unfortunate that I lost quite a bit of time to this nearly undocumented change. I wonder how many people across the atom user base have lost time to this, and how man hours it adds up to over all. Should I avoid updating my editor in the future?

**Comment by rpdobson123** [comment]
It snuck up on me after updating - rather frustrating.

If users would be expected to modify those keybindings to what they're used to, why would you change user's configurations in the first place instead of letting people do it themselves?

**Comment by ianlancaster** [comment]
To reset the ctrl-tab tabbing order, try dropping the following code into your keymap.cson
`'body':
  'ctrl-tab': 'unset!'
  'ctrl-tab ^ctrl': 'unset!'
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab': 'unset!'
  'ctrl-shift-tab ^ctrl': 'unset!'
  'ctrl-shift-tab': 'pane:show-previous-item'
`

**Comment by ahnbizcad** [comment]
why is this still not the default yet.

**Comment by jtheck** [comment]
I see all the "+1 MRU" comments in the other post, but this is backwards as hell for anyone who isn't clinging to 20 year old editor defaults. Making that crap the default for atom.. smfh. If they want that old style then they should be the ones editing their configs.

**Comment by HugoMcPhee** [comment]
in atom version 1.124 to avoid errors the keymap is shortened to
```
'body':
  'ctrl-tab ^ctrl': 'unset!'
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab ^ctrl': 'unset!'
  'ctrl-shift-tab': 'pane:show-previous-item'
```
(from ianlancasters comment)

**Comment by martinprot** [comment]
Alleluia.
MRU/LRU can be a standard for some people (definitely not me), but in this case editor MUST give feedback to user. Simple example : the windows Alt-Tab, or OSX Cmd-Tab iS LRU, and GIVES user feedback by showing the elements in the right order.
This Atom feature is currently broken due to user experience problem.

**Comment by Ben3eeE** [comment]
@martinprot Work is being done to enhance the MRU UX see https://github.com/atom/tabs/pull/388 and https://github.com/atom/atom/issues/11035 for example.

**Comment by martinprot** [comment]
that would be PERFECT. 👍

**Comment by inspectaTech** [comment]
@yourpalal thank you this is the answer.  why wouldn't everyone just lead with this. 
**Ctrl pgUp & Ctrl pgDn**
presumably with no added keybindings needed.

**Comment by gardner** [comment]
Remapping the keys appears to no longer work. After updating my `~/.atom/config.cson` and restarting the editor ctrl-tab still uses MRU.

```
$ cat ~/.atom/config.cson 
"*":
  "autocomplete-plus":
    confirmCompletion: "tab always, enter when suggestion explicitly selected"
  body:
    "ctrl-shift-tab": "pane:show-previous-item"
    "ctrl-shift-tab ^ctrl": "unset!"
    "ctrl-tab": "pane:show-next-item"
    "ctrl-tab ^ctrl": "unset!"
  core:
    telemetryConsent: "no"
  editor: {}
  "exception-reporting":
    userId: "d4f0b84c-a77f-4e36-9282-263c55243d3f"
  "spell-check":
    locales: [
      "en-UK"
    ]
```

Atom version: 1.26.1
```
$ atom --version
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```
