### ISSUE TITLE
Add an overlay to provide context when MRU tabbing

### ISSUE THREAD

**Issue by drewshaver** [atom/atom#11656]
### Problem

MRU tabbing is very confusing when unexpected. For new or unaware users, it appears ctrl-tab is broken and just jumping around randomly. Even for aware users, the lack of a pop-up list of tabs in MRU order makes quickly identifying the distance needed to arrive at desired tab impossible.

### Suggested Fix

Something like this: [Tab switcher plugin](https://atom.io/packages/tab-switcher)

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/atom/issues/11535?

**Comment by drewshaver** [comment]
derp
