### ISSUE TITLE
SOFT UNDO – Unable to "undo" cursor movement and selection (Like Cmd + U in Sublime)

### ISSUE THREAD

**Issue by dallanlee** [atom/atom#11652]
I've been searching quite a bit for a "soft undo" in Atom. I'm hoping I'm wrong but it doesn't look like there is one… Can anyone confirm one way or the other? Soft undo is essential to my workflow. I used it *a lot* in Sublime Text and I'm trying to make the move to Atom. Today is day one and there are a couple things I like more so far. But no soft undo really is a big deal and has me wondering if I can go without it… 🤔

**Comment by albertosantini** [comment]
I beg your pardon, but it seems to me an help request or a general question.

It might be better addressed in a `Discuss` topic: https://discuss.atom.io/

Generally speaking, you may read the recent post about [issue guidelines](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

**Comment by 50Wliu** [comment]
Closing in favor of creating a new topic on Discuss.

As far as I know there is no soft undo, but have you tried searching for a package that gives that functionality?

**Comment by dallanlee** [comment]
@50Wliu I have tried "searching quite a bit" (meaning an hour or so of searching high and low) as I explained in my original post. It's disappointing and surprising that a "hackable text editor for the 21st Century" doesn't have soft undo.

**Comment by dallanlee** [comment]
@albertosantini I beg your pardon but is this not clearly "an enhancement" as explained in the [issue guidelines]http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html)?

**Comment by 50Wliu** [comment]
> It's disappointing and surprising that a "hackable text editor for the 21st Century" doesn't have soft undo.

That's the reason that it is "hackable" - you can create your own package for that functionality.  It's just that no one has decided to yet.

**Comment by dallanlee** [comment]
@50Wliu I guess that's true! 🙂
