### ISSUE TITLE
Title bar color not updating

### ISSUE THREAD

**Issue by Ben3eeE** [atom/atom#11658]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The title bar color (Windows 7 classic theme) does not always update and is sometimes grey (non focused window) while the window is focused and should be blue (focused window).

//cc @damieng Windows only issue?

### Steps to Reproduce

1. Classic mode windows (I don't know if needed I only use classic mode)
2. Open atom in safe mode.
3. Ctrl-shift-o and move the dialog over the blue title bar, title bar gets colored grey where the dialog was moved over. Other operations such as making a new snap in the snipping tool also changes the color of the title bar.

See example of title bar of focused application where open dialog was moved around.
![atom title bar color](https://cloud.githubusercontent.com/assets/1058982/14931437/b8afb67a-0e6b-11e6-98a0-0082e3673450.png)

**Expected behavior:** Title bar color to update consistently as other windows applications and be completely blue when the application is focused.

**Actual behavior:** Title bar color is incorrect and depends on how some dialog was moved or other actions while having atom open.

### Versions

Windows 7 classic theme
Atom 1.7.3

**Comment by Ben3eeE** [comment]
I just tested and it seems to only happen with the "Windows Classic" theme.

**Comment by damieng** [comment]
Again Electron+Windows7+WDM composition disabled - being tracked at https://github.com/electron/electron/issues/1821
