### ISSUE TITLE
Atom window disappears

### ISSUE THREAD

**Issue by LinusNeuman** [atom/atom#11653]
Description

When launching the Atom editor, the window never appears. I can see it in my taskbar, and the preview looks fine. I have tried disconnecting extra monitors, and I have tried to open extra windows, but none of them appear, they are hidden in some magical way.

Steps to Reproduce

I have no idea.

Versions

Atom Version 1.7.3

**Comment by 50Wliu** [comment]
What OS is this on?  In the future, please fill out the entirety of the issue template.

**Comment by LinusNeuman** [comment]
Sorry.

I'm on Windows 10.

**Comment by 50Wliu** [comment]
If you shift-right click on Atom, you should be able to restore/maximize/move Atom.  Can you try doing that and see if you can get it to show up?

**Comment by damieng** [comment]
Also try pressing the Windows key and an arrow once you've pressed the icon in the task bar.  

Windows is very bad about positioning Windows off-screen if you have changed resolution/external monitors :(

**Comment by Ben3eeE** [comment]
Refs/Duplicates that I stumbled upon a few days ago and have been meaning to comment on: https://github.com/atom/atom/issues/8737 https://github.com/atom/atom/issues/6939 https://github.com/atom/atom/issues/9172  https://github.com/atom/atom/issues/9223

**Comment by lee-dohm** [comment]
Thanks @Ben3eeE. Closing this (and the others) as duplicate of #6939.
