### ISSUE TITLE
Window not redrawing when some dialogs are open

### ISSUE THREAD

**Issue by Ben3eeE** [atom/atom#11657]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The window does not redraw while the help menu->check for update dialog is opened and moved.

//cc @damieng Windows only?

### Steps to Reproduce

1. Check for update using the help menu.
2. Move around the dialog that appears stating atom is the latest version.

![window doesnt update with dialog open](https://cloud.githubusercontent.com/assets/1058982/14552189/00a32da4-02dc-11e6-88df-cf2edbc4862a.PNG)

**Expected behavior:** I expect atom to not look like I am winning in solitaire.

**Actual behavior:** Atom looks like I won solitaire.

### Versions
Windows 7
Atom 1.7.3 safe mode.

**Comment by 50Wliu** [comment]
Does this still happen when Aero mode is enabled?

**Comment by Ben3eeE** [comment]
I just tested and it seems to only happen with the "Windows Classic" theme.

**Comment by damieng** [comment]
This is a bug in Electron specifically on Windows 7 with DWM composition disabled (which is what Classic mode does) and is being tracked at https://github.com/electron/electron/issues/1821

**Comment by Ben3eeE** [comment]
@damieng Thanks.

**Comment by damieng** [comment]
Sorry I don't have better news - takes time to get upstream fixes in.
