### ISSUE TITLE
Feature Request: restore unsaved tabs upon restart

### ISSUE THREAD

**Issue by fbcom** [atom/atom#11655]
### Description

Atom does not restore text entered in new (unsaved) tabs.
This is a feature request.

Related issues ([#8327](https://github.com/atom/atom/issues/8327), [#942](https://github.com/atom/atom/issues/942)) were closed but this is still a thing in version 1.7.3

### Steps to Reproduce

1. Start Atom
2. Create a new tab
3. Type something in the tab
4. Close Atom
5. Reopen Atom
6. Text is gone

**Expected behavior:**

Unsaved tabs should be restored (sublimetext does this) even when they are not saved explicitly to a file to allow for quick jotting down of ideas or code snippets.

**Actual behavior:**

All entered text is gone.

### Versions

Atom 1.7.3
OSX 10.10.5

**Comment by 50Wliu** [comment]
In your first step, "Start Atom", is there a project that is opened?  In other words, does the tree view show up?

In addition, in step 4, "Close Atom", are you quitting Atom entirely and not just closing the window?

**Comment by fbcom** [comment]
Added Information:

There is nothing openend and the treeview is empty.
In step 4 I am quitting atom entirely.

**Comment by Ben3eeE** [comment]
I believe that makes this a duplicate of https://github.com/atom/atom/issues/10474

**Comment by fbcom** [comment]
indeed [closed]
