### ISSUE TITLE
Tooltips z-index bug

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#11661]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

The autocomplete tooltip overlaps other tabs

![](http://uploadpie.com/mJ8YM)

### Steps to Reproduce

1. Open a file
2. Create a second pane below the main pane
3. Invoke autocomplete
4. Scroll

**Expected behavior:** 

The tooltip should hide when outside of the visible are of it's pane

**Actual behavior:** 

The tooltip is visible, on top of another pane.

### Versions

Atom    : 1.7.2
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
Debian 8 + KDE 5

**Comment by lee-dohm** [comment]
Image is broken.

**Comment by lee-dohm** [comment]
I was able to replicate this using Atom v1.9.0-dev-5a9bd28 on Mac OS X 10.11.4. Would you mind reopening it on the atom/autocomplete-plus repository?

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/10192 https://github.com/atom/atom/issues/8596 Duplicates?

**Comment by alexandernst** [comment]
The first one, not sure, but the second one is a duplicate, indeed.

**Comment by lee-dohm** [comment]
Thanks for spotting the dupes for us!
