### ISSUE TITLE
Different comment styles

### ISSUE THREAD

**Issue by tommiehansen** [atom/atom#11666]
### Description

Add ability to style different types of comments. This is useful since different comments can have different purposes. Some comments can be of the 'section' type and some can be of the 'small comment type'. Being able to style these differently is often of great help when working with code.

### Steps to Reproduce

1. Add single-line comment ie // comment
2. Add multi-line comment ie /* multiline comment */
3. Add third type ie # php hash comment

**Expected behavior:** Being able to style these comments differently
**Actual behavior:** No difference between comment and _comment_

### Versions
1.7.2

**Comment by 50Wliu** [comment]
This is already possible in most language packages, which differentiate between each type of comment.  For example, in language-javascript, `//` is tokenized as `comment.line.double-slash.js`, while `/*` is `comment.block.js`.  You can style these comments differently in your `styles.less` (instructions [here](http://flight-manual.atom.io/using-atom/sections/basic-customization/#_style_tweaks)).

**Comment by tommiehansen** [comment]
I was talking about **multi line** vs **single line** though. Both `// text` and `/* text */` can be single line.
I haven't been able to find any style that acts differently depending on no. of lines in comment and depicts the style after that?

**Comment by 50Wliu** [comment]
No, currently none of the languages differentiate between the number of lines, only the type of comment.
