### ISSUE TITLE
Stuck indexing when adding more than one project folder

### ISSUE THREAD

**Issue by frenchbread** [atom/atom#11667]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Stuck indexing when adding more that one project folder to atom-beta

### Steps to Reproduce

1. `$ atom-beta ./<project>`
2. Atom opens - `Cmd+T`, Fuzzy window works fine
3. `$ atom-beta --add ~/<path>/<project>` - another project added to atom
4. In atom - `Cmd+T`, Fuzzy window shows:

![screen shot 2016-05-02 at 01 10 40](https://cloud.githubusercontent.com/assets/2122679/14944738/a15d928a-1005-11e6-8dc7-5162cd11b85a.png)

**Note!** This steps are reproducing the bug only in `atom-beta`. In `atom` this bug appears for some other reason sometimes.

**Expected behavior:** Both projects successfully indexed and possible to open file using Fuzzy window.

**Actual behavior:** Stuck while indexing

### Versions
Atom:
```
$ atom -version
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

Atom-beta:
```
$ atom-beta -version
Atom    : 1.8.0-beta3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by lee-dohm** [comment]
Can you reproduce the issue in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by frenchbread** [comment]
Yes, same issue in save mode. And since the issue seem to be for `atom-beta` only the command is `atom-beta --save` or `atom-beta --save --add ~/<path>`

**Comment by 50Wliu** [comment]
It is **safe** mode, not **save** mode.

**Comment by frenchbread** [comment]
@50Wliu Sorry for typos. Tested again, and same issue.

**Comment by lee-dohm** [comment]
@frenchbread Would you mind reopening this Issue on the https://github.com/atom/fuzzy-finder repository? It will make tracking some things easier.

**Comment by frenchbread** [comment]
Sure. 

For reference: https://github.com/atom/fuzzy-finder/issues/205

**Comment by lee-dohm** [comment]
Thanks very much @frenchbread :grinning:
