### ISSUE TITLE
Implement silent upgrade of Atom

### ISSUE THREAD

**Issue by ssbarnea** [atom/atom#11665]
I do not see any reason why Atom would not be able to update itself without requiring any user intervention. Once the application is not used (foreground) for a number of minutes it should just restart in order to install the newer version.

Our time is too precious to be wasted on manually upgrading applications, hide this boring task. Obviously that if someone wants to be in-control of that behaviour they could enable or disable this in the settings.

**Comment by 50Wliu** [comment]
> I do not see any reason why Atom would not be able to update itself without requiring any user intervention.

Atom already does this on Windows and OS X.  It checks for updates silently and applies them when Atom is closed.

> Once the application is not used (foreground) for a number of minutes it should just restart in order to install the newer version.

This is extremely dangerous since there are certain packages/processes that may be running in the background without user interaction.  In addition, there is no guarantee that just because Atom hasn't been used for a while, that also means no one will attempt to use it while it closed by itself to update ("where'd my Atom go?!").


> Our time is too precious to be wasted on manually upgrading applications, hide this boring task.

As I said before, Atom does not need to be manually upgraded except on Linux or the archive versions.

**Comment by ssbarnea** [comment]
Hmm, I guess that you are not an OS X user. OS X users do not close their applications for weeks if not months! So if Atom will upgrade itself when I manually quit it, it would be like not good enough solution.

Sorry to say but I would not call the current behaviour a `silent upgrade` as if I keep my computer running for one year, and atom happens to be running.

**silent and unattended** means not requiring any kind of user intervention in order to be updates.Having to quit and start the application is a manual task.

**Comment by 50Wliu** [comment]
> Hmm, I guess that you are not an OS X user.

Yep, I'm a Windows user on a laptop :).  However, I am still against silently (and unexpectedly) closing Atom for the reasons I listed above.

I'll see if I can get someone from the team who uses OS X to comment here.

**Comment by lee-dohm** [comment]
@ssbarnea I'm an OS X user and I generally leave my applications open for quite some time. I can see your point that a manual step is needed for Atom to upgrade the code that is running. @50Wliu is also right, that simply closing and restarting without the user's permission is also potentially jarring and worrisome to the user. If someday Atom is to the point where we can take a snapshot of the running system and restore it flawlessly in every case, then we'll come back and consider this. Until then, manually restarting in the least intrusive way possible will have to do.

**Comment by mnquintana** [comment]
Can you point to any other OS X app that has this silent upgrade flow you're proposing? Atom's update flow is more or less modeled after Chrome's which still requires its users to restart the app at some point, but is nonetheless constantly silently updated behind the scenes. 

Unfortunately, I suspect that restarting the app if it's been blurred for long enough would actually be even more obtrusive and disruptive than the current update behavior, and has high potential to frustrate a lot of users. I don't know of any app that restarts itself without user intervention, and it would be incredibly jarring for an app you expect to remain running to all of a sudden blink out and back into existence. It could also, I think, easily be perceived as a crash, and not a silent upgrade working its magic. I think we currently strike a good balance between silent updates and user free will. 😄 

We could, alternatively, open a notification for users informing them about an update if they haven't restarted in a *really* long time (like, on the order of weeks) and there's an update available.
