### ISSUE TITLE
Atom open in some sort of "debug mode" in every execution

### ISSUE THREAD

**Issue by danielbmeireles** [atom/atom#11676]
### Description

Atom open in some sort of "debug mode" in every execution

### Steps to Reproduce

Every time I tried to open the atom editor, the following screen shows instead of the regular editor window:

![image](https://cloud.githubusercontent.com/assets/16562270/14973114/5c55e588-10ba-11e6-800c-eb198c4b641c.png)

The same behavior is observed when atom is opened in safe mode.

My environment information:

```
C:\Users\Daniel>atom --version

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

C:\Users\Daniel>ver

Microsoft Windows [versão 10.0.10586]
```

**Comment by 50Wliu** [comment]
Please click the red "x" with a 1 next to it and paste the error here.  Thanks!

**Comment by danielbmeireles** [comment]
@50Wliu: first of all, thank you for you assistant.

I just realized that my home folder was some permissions missing (don't ask why) and the installer was unable to create the ".atom" folder there.

After correct this, I was able to install the Atom editor without problem.

Once more, thank you so much for your support.

Best Regards,

Daniel Meireles
