### ISSUE TITLE
Atom editor crashes on startup with dialog

### ISSUE THREAD

**Issue by zenwalker1985** [atom/atom#11672]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?yes
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?yes
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?yes
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?yes
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?yes
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?yes

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

[Description of the bug or feature]
Launching of the Atom editor 1.7.3 crashes with a dialog
### Steps to Reproduce
1. launch atom

**Expected behavior:** [What you expected to happen]Start normally

**Actual behavior:** [What actually happened]Crashed with a dialog
### Versions

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.2

OS Info:
Zenwalk Linux x64 bit. 

Atom package installed via source building.

**Comment by 50Wliu** [comment]
Is Zenwalk Linux based on Arch Linux?

**Comment by Nikki1993** [comment]
@50Wliu  It is based on Slackware.

**Comment by DamnedScholar** [comment]
[Zen Linux](http://distrowatch.com/table.php?distribution=zen) includes Freetype. Freetype 2.6.3 [conflicts with Electron 0.36.8](https://github.com/atom/atom/issues/11612#issuecomment-216696720). So, if your Freetype is updated, that's what's causing the problem (it's the same as on Arch).

The solution: check out the latest git repo and build. The issue has been fixed, it just hasn't been released yet. I have two Arch-derivative computers happily running Atom built from the 1.9.0 development code (the one on my machine next to me is 1.9.0-dev-b9dbb81) and haven't seen a single problem.

**Comment by 50Wliu** [comment]
Looks like this has been solved.
