### ISSUE TITLE
Visual Basic .NET syntax highlight

### ISSUE THREAD

**Issue by CuteLeon** [atom/atom#11674]
I need Visual Basic .NET syntax highlight! Please.

**Comment by lee-dohm** [comment]
You may want to search the [packages listing](https://atom.io/packages). Someone has probably already built a package for it.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
