### ISSUE TITLE
atom should recognize "vim:ft..." file type specifiers

### ISSUE THREAD

**Issue by bedge** [atom/atom#11670]
This is an encancement request.

Many files contain vim file-type commands, eg:
`# vim: ft=sh
`
If atom parsed vim file type specifiers, then many cases where the user had to manually change it to the appropriate file type, would go away as it would be automatically gleaned from the vim file type.

**Comment by bastilian** [comment]
This may be a nice addition to [atom/vim-mode](https://github.com/atom/vim-mode) rather then in Atom itself.

**Comment by bedge** [comment]
I thought about that, and decided that it's not really VIM specific because you want the file type ident to be as automated as possible, but not necessarily want to use the VIM mode.
It's more about automating the latter than extending the vim-mode emulation.

**Comment by bastilian** [comment]
I just found this: https://atom.io/packages/vim-modeline

**Comment by bedge** [comment]
perfect, even better. I should have looked harder... thanks!
