### ISSUE TITLE
Atom remembers session on "atom .", even after rm -rf ~/.atom/storage

### ISSUE THREAD

**Issue by vtimbuc** [atom/atom#11684]
Hey guys, so is there a way to start atom on a project without remembering the last session? Using "atom .", I looked on the project folder to see if it creates a config file but didnt find anything. Cheers

**Comment by 50Wliu** [comment]
@vtimbuc `atom --clear-window-storage`

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

**Comment by vtimbuc** [comment]
@50Wliu Thanks man. Cheers
