### ISSUE TITLE
Simple regular expression replace bug

### ISSUE THREAD

**Issue by zamb3zi** [atom/atom#11689]
### Description

When searching in regular expression mode, some expressions ending in a zero-length assertion, match but do not actually replace.

### Steps to Reproduce

1. Create a new file containing:
```js
//foo
//bar
```
2. Find in `.*` (regular expression) mode either `//\b` or `//(?=\S)` and replace with any text replacement.
3. Click Find, then Replace and Replace. Matches occur but replacements do not. 
4. Now search for `..\b` and observe correct matches for `//`, `oo` and `ar` but only the latter get replaced.

### Versions
```
> atom --version

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

> apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 1.9.5.msysgit.0
visual studio 2013
```

**Comment by albertosantini** [comment]
I think this issue should be filled in https://github.com/atom/find-and-replace project.

It seems there are other issues about replacing with regex (matching $, partial replacing and so on).

**Comment by 50Wliu** [comment]
Thanks @albertosantini.
