### ISSUE TITLE
Bookmark icons should stay visible when line numbers gutter is hidden

### ISSUE THREAD

**Issue by freemanoid** [atom/atom#11681]
### Description
When I hide the line numbers (cmd + P -> `Editor: Toggle Line Numbers`) all the bookmark icons disappear.
I believe they should stay visible. 

![bookmarks](https://cloud.githubusercontent.com/assets/180154/14991120/7e678452-1168-11e6-9f1e-3de93b93c6dd.gif)

### Version
Atom    : 1.7.3

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/bookmarks? Thanks!

**Comment by freemanoid** [comment]
Thanks! Didn't know about this plugin. Actually this is a dup of https://github.com/atom/bookmarks/issues/8

**Comment by mnquintana** [comment]
No worries! We have a ton of repos, so it can definitely be tricky to figure out what goes where. 😅
