### ISSUE TITLE
Switching branches does not properly reopen tabs for files in one branch but not the other

### ISSUE THREAD

**Issue by AaronM04** [atom/atom#11693]
If I am on branch A and I have a file open in a tab that is present in A but absent in branch B, switching to branch B causes the tab to close (which is fine). However, switching back to branch A does not reopen the tab. This would be very desirable behavior for people who switch between branches a lot with their version control system.

I am running Atom 1.7.3 on OS X.

**Comment by albertosantini** [comment]
Dupe https://github.com/atom/atom/issues/4982?

See also https://github.com/atom/atom/issues/9589.

There is also a Discuss topic `Why doesn’t the newly created tabs/files close when I switch the branch?`: https://discuss.atom.io/t/why-doesnt-the-newly-created-tabs-files-close-when-i-switch-the-branch/15885

Generally speaking, you may read the recent post about [issue guidelines](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

**Comment by AaronM04** [comment]
Thank you @albertosantini. It looks like all three issues (this one and the two you mentioned) describe the same problem.

**Comment by AaronM04** [comment]
At any rate, I really hope it gets fixed soon.

**Comment by brunogarcia** [comment]
@AaronM04 There is a plugin than watches open files for conflicts or changes:
https://atom.io/packages/file-watcher
