### ISSUE TITLE
atom crashes on projects with non standard git repos (git annex direct mode)

### ISSUE THREAD

**Issue by eskimor** [atom/atom#11697]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? (1.6.2)
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

atom crashes at startup for projects with a git-annex repo in direct mode.
### Steps to Reproduce
1. cd $project; git init; git annex init; git annex direct
2. atom .

atom should probably check whether the found git repo is a valid plain one, and inform the user otherwise that the found git repo is not supported.

**Expected behavior:** Open project

**Actual behavior:** Editor crashed with dialog (keep open, close, ..)

This really bit me, because my home directory is a git-annex repo, so atom crashed for me for any project I had not yet run `git init` for. It took me quite a while to figure that out. 
### Versions

atom-1.6.2 and earlier tested.

**Comment by internetimagery** [comment]
I also get this. I believe it is due to the config "core.bare=true", used as a locking mechanism in annex, but of course it's not actually a bare repo.

In the meantime, I copy the .git folder into a subfolder while working... 😕

**Comment by rsese** [comment]
> I also get this. I believe it is due to the config "core.bare=true", used as a locking mechanism in annex, but of course it's not actually a bare repo.

Thanks for spotting that, looks like a dupe of https://github.com/atom/atom/issues/12474 then?
