### ISSUE TITLE
Consistency within OS X

### ISSUE THREAD

**Issue by will1818** [atom/atom#11698]
Hi all, just wanted to raise this design flaw - although flaw is a strong word. 

On OS X all of the close tab "X's" are on the left hand side of the tab throughout the OS (Safari, Finder, Terminal..) however in Atom they're on the right! It would be great to have a setting allowing them to be repositioned to the left, allowing for more consistency within OS X.

Many thanks,

**Comment by will1818** [comment]
https://atom.io/packages/close-on-left

^^ I should have googled harder before posting!

**Comment by 50Wliu** [comment]
Glad you solved your issue @will1818 :).
