### ISSUE TITLE
Release key keybinding behaviour change proposal

### ISSUE THREAD

**Issue by chamini2** [atom/atom#11699]
I read #11035 and it seems obvious that the option is not received as expected, which made me think that the problem is not the default behaviour, but that it shouldn't be needed to `unset!` the keybindings.

If we have:

```
'body':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab': 'pane:show-previous-item'
```

The [_method_ called](https://github.com/atom/atom/blob/72721af3c63fd0d0bd0b0dd196ff28a3cab9ba11/src/pane.coffee#L347) when `ctrl` is released (`ctrl-tab ^ctrl`) seems to not affect the pane to show at all, it should just change the stack. Yet it changes behaviour of tab switching.

**Comment by Ben3eeE** [comment]
/cc: @iolsen some :eyes: here as part of the MRU UX.

**Comment by iolsen** [comment]
You're correct that `ctrl-tab ^ctrl` does nothing but change the stack. Unsetting it isn't strictly necessary to turn off the MRU behavior.

The keybinding change that actually affects the behavior is overriding this (the default):

```
'body':
  'ctrl-tab': 'pane:show-next-recently-used-item'
  'ctrl-shift-tab': 'pane:show-previous-recently-used-item'
```

with this:

```
'body':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab': 'pane:show-previous-item'
```

So I'm not sure there's any action to be taken from this feedback. That being said, the [change with the MRU list and option](https://github.com/atom/tabs/pull/388) is likely to ship in the next beta, so hopefully that addresses any outstanding concern.
