### ISSUE TITLE
Uncaught Error: ENOTSUP: operation not supported on socket, read

### ISSUE THREAD

**Issue by fabyc** [atom/atom#11702]
[Enter steps to reproduce below:]
1. Open a remote (ftp) project folder
2. Edit a file of that remote folder
3. Click on "Save" button for save changes of the file

**Atom Version**: 1.7.3
**System**: Ubuntu 14.04.4
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: ENOTSUP: operation not supported on socket, read

```
At fs.js:651

Error: ENOTSUP: operation not supported on socket, read
    at Error (native)
    at Object.fs.readSync (fs.js:651:19)
    at Object.fs.readFileSync (fs.js:467:24)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at File.module.exports.File.readSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:266:36)
    at File.module.exports.File.getDigestSync (/usr/share/atom/resources/app.asar/node_modules/text-buffer/node_modules/pathwatcher/lib/file.js:167:14)
    at TextBuffer.module.exports.TextBuffer.serialize (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:231:68)
    at /usr/share/atom/resources/app.asar/src/project.js:137:27
    at Array.map (native)
    at Project.module.exports.Project.serialize (/usr/share/atom/resources/app.asar/src/project.js:135:41)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:769:31)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27
```
### Commands

```
     -6:26.1.0 window:increase-font-size (atom-pane.pane.active)
     -6:26 settings-view:open (atom-pane.pane.active)
     -1:10.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:09.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:43.1.0 core:undo (atom-text-editor.editor.is-focused)
  9x -0:42 core:save (atom-text-editor.editor.is-focused)
     -0:27.6.0 core:select-all (atom-text-editor.editor.is-focused)
  2x -0:26.8.0 core:copy (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "fontSize": 15
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@fabyc What were you doing when this occurred?

**Comment by fabyc** [comment]
Hi @50Wliu 

I opened a remote (ftp) project folder and I edited a file. When I clicked on "Save" button for save changes of the file, I got the error message described.

**Comment by ledazinha** [comment]
This is happening to me too, and I didn't even tried to save the file. I'm just trying to open it.

**Comment by lee-dohm** [comment]
So it sounds like the file is stored on an FTP server somewhere and isn't really on the local filesystem? Since Atom doesn't support FTP, I'm not seeing how this could be a bug in Atom?

**Comment by ledettwy** [comment]
I'm experiencing this too. This kind of amazes me that this is even occurring at all. The fact that a filesystem is network mounted should be completely opaque to the open(), read(), and write() calls. atom shouldn't care. It's almost as if atom would have to go out of its way to check if the location it's writing to is network mounted, and then actively refuse to do so for some reason?

**Comment by lee-dohm** [comment]
@ledettwy Yes, you're correct. But Atom doesn't care. Atom wasn't designed to pay attention to how something is mounted ... it treats everything the same. It just uses the Node file system module to read and write files. So I would guess that the problem lies in whatever system is used to mount an FTP server to the file system.

**Comment by ledettwy** [comment]
@lee-dohm But I'm seeing the same behavior (operation not supported on socket) when I try to save an opened file. Sublime Text has no issues. nano has no issues. vim has no issues. _**ed**_ has no issues.  But Atom refuses to save the file. BUT it does create backup copies in the exact same location but with a different name. So it has no trouble writing files to network mounts. It just won't save the actual file.

**Comment by hws-md** [comment]
I also have this issue (Mac OS 10.11.6, Atom 1.9.9 with local node version 4.5.0), I can not save an opened file from a mounted smb drive (have this mounted into a local folder, so should be completely transparent). Although, a backup file is created!
Is this an issue with the Node.js FS?

**Comment by mathiassen1990** [comment]
Any news on this issue?

**Comment by ljmatkins** [comment]
I also have had the same problem (for a long time now). As others have stated above, backup copies are created and other editors have no issues saving.
