### ISSUE TITLE
Atom Continues to crash

### ISSUE THREAD

**Issue by Saul3d** [atom/atom#11719]
Everytime I launch Atom I get an alert message stating that the editor has crashed. I've tried running Atom in safe mode, uninstalling and reinstalling it and nothing seems to work.  I'm running version 1.7.3 of Atom on a windows 7 machine.  This just recently happened as it worked fine earlier this morning. 

**Atom version:1.7.3
**OS and version:Win 7

**Installed packages:**

[List of installed packages here]

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes
![atomcrash](https://cloud.githubusercontent.com/assets/1847649/15122850/8a23b3ce-15e6-11e6-9aea-726d5d375672.png)

**Comment by bkbartonDesign** [comment]
+1 Same problem.

**Comment by joshmanders** [comment]
Just started getting this also.

**Comment by joshmanders** [comment]
So doing some changes, I got it to stop crashing when I deleted all my installed packages. What packages do you guys have installed? Maybe we can cross reference and figure out what package is causing the issues.

**Comment by joshmanders** [comment]
`linter-js-standard@3.3.2` seems to be what is causing my crashes.

**Comment by joshmanders** [comment]
https://github.com/ricardofbarros/linter-js-standard/issues/112

**Comment by bkbartonDesign** [comment]
@joshmanders I also deleted installed packages. After I removed `linter-eslint@7.2.2`, I have been able to work with no issues.

Are there any stable linters for Atom? I don't remember having this same problem in Sublime.

**Comment by 50Wliu** [comment]
@Saul3d Can you try renaming the `%USERPROFILE%\.atom` folder to `%USERPROFILE%\.atom-backup` or something and see if that lets you start up Atom?

**Comment by Saul3d** [comment]
@50Wliu that did it.  Thank you!

-Saul

**Comment by 50Wliu** [comment]
Awesome, thanks for reporting back!  That usually means one of your installed packages is causing the crash.  You can remove them one-by-one in `.atom\packages` until your crashes go away.
