### ISSUE TITLE
Atom fails to open new windows from command line

### ISSUE THREAD

**Issue by bedge** [atom/atom#11712]
Atom Editor v1.7.3

I used to open new atom windows using:
`atom -n .`
A few months ago that quit working. Now, from the shell, atom only opens a window if atom is not already running.
I can still open a new window from inside the editor, but not from a shell.

Now, if I open the first atom instance in the foreground, with logging enables, ie, with
`atom -fnl`
I get a log of the error when I try to open another window from a different shell instance:
```
%> atom -fnl
[47311:0506/220409:WARNING:resource_bundle.cc(305)] locale_file_path.empty() for locale English
[47311:0506/220409:WARNING:dns_config_service_posix.cc(146)] dns_config has unhandled options!
2016-05-06 22:04:10.259 Atom[47311:6623754] App load time: 390ms
[47311:0506/220410:INFO:CONSOLE(52)] "Window load time: 330ms", source: file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js (52)
[47311:0506/220411:INFO:CONSOLE(29)] "(node) sys is deprecated. Use util instead.", source: internal/util.js (29)
[47311:0506/220411:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[47311:0506/220411:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[47311:0506/220412:INFO:CONSOLE(85755)] "WebSocket connection to 'ws://localhost:56166/a244ed92-2af0-4d9c-b2a7-79747864d2fe/browser' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED", source: /Users/bedge/src/proton/plugin/lib/proton.js (85755)
[47311:0506/220412:INFO:CONSOLE(85802)] "DEVTOOLS: disconnected!", source: /Users/bedge/src/proton/plugin/lib/proton.js (85802)
```
Attempted to open another window from shell here, log continues below:
```
2016-05-06 22:04:19.567 Atom[47311:6623754] Unexpected end of input
2016-05-06 22:04:19.575 Atom[47311:6623754] SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:232:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
2016-05-06 22:04:19.576 Atom[47311:6623754] Unexpected token ?
2016-05-06 22:04:19.577 Atom[47311:6623754] SyntaxError: Unexpected token ?
    at Object.parse (native)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:232:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```
Note. while I am using the proton plugin now, this was happening without proton originally.

Same behavior in --safe mode too.

**Comment by damieng** [comment]
Which shell/command prompt are you using?  (Command Prompt, PowerShell, MSYS1, GitHub Desktop Bash....)

**Comment by bedge** [comment]
osx, zsh 5.2 (x86_64-apple-darwin15.0.0)
Same thing with bash.

**Comment by albireox** [comment]
Also happening in OSX with fish shell.

**Comment by birkir** [comment]
Having the same issue, can see it's trying to start (get duplicate icon in dock), then it disappears.

**Comment by damieng** [comment]
It should do that and make the existing copy of atom open the file.

**Comment by Pierrounator** [comment]
Did you try `atom` or `atom --new-window` or `atom [name]` to create a new document and name it?

I'm using 1.7.3 on OS X 10.11.4 and it works fine with Terminal.

**Comment by bedge** [comment]
Both, with and without the `-n` arg each fail to open a new window, or, add the file to an existing window.

Also Osx 10.11.4 (15E65), atom 1.7.3

**Comment by chrisdhanaraj** [comment]
Just noting that when I try this with logging on (getting the same issue), the only error I get is

```
[94337:0520/155420:WARNING:resource_bundle.cc(305)] locale_file_path.empty() for locale English
```

**Comment by kafoso** [comment]
Having issues on Windows 7 SP1, too.

- Atom version 1.7.4
- Git Bash installed through Git-2.6.2-64-bit.exe.

`atom -n` works correctly using cmd.exe.

Also, files cannot be opened through e.g. `$ atom ~/.bashrc`. It cuts off the first letter of my username ("kafoso"):

```bash
$ atom ~/.bashrc
'afoso' blev ikke genkendt som en intern eller ekstern kommando,
et program eller en batchfil.
```

It's in danish, but corresponds to:

```bash
'afoso' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by lee-dohm** [comment]
I can't replicate this using Atom v1.7.4 on Mac OS X 10.11.5. Here's what I did:

1. Navigate to my local Atom repository at `~/Source/atom`
1. Launch Atom with `atom .`
1. Wait for Atom to start
1. Go back to the terminal window
1. Launch a second window with `atom -n .`

Expected and Actual: A second Atom window is opened

@bedge Can you include steps to reproduce the issue you're describing?

**Comment by bedge** [comment]
@lee-dohm - here's a with & without logging case set.

From shell:
```
%> atom .
%> atom .
```
End result - one atom window instance.
I waited for the first instance to start, then tabbed back to shell and started a second instance.
cd-ing into a different directory or using another shell instance does not change anything.

Note that after running atom for the second time, the system menu bar changes to an "atom" menu bar very briefly, for maybe 200mS.

Here's the same thing using -fl for log output:

> 
> %> atom -fl .
> [30555:0523/134924:WARNING:resource_bundle.cc(305)] locale_file_path.empty() for locale English
> [30555:0523/134924:WARNING:dns_config_service_posix.cc(146)] dns_config has unhandled options!
> 2016-05-23 13:49:24.849 Atom[30555:14632852] App load time: 470ms
> [30555:0523/134925:INFO:CONSOLE(52)] "Window load time: 488ms", source: file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js (52)
> [30555:0523/134926:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
> [30555:0523/134927:INFO:CONSOLE(139)] "Loading Emmet extensions from", source: /Users/bedge/.atom/packages/emmet/lib/emmet.coffee (139)
> [30555:0523/134927:INFO:CONSOLE(156)] "Emmet: no such extension folder:", source: /Users/bedge/.atom/packages/emmet/lib/emmet.coffee (156)
> [30555:0523/134928:INFO:CONSOLE(29)] "(node) sys is deprecated. Use util instead.", source: internal/util.js (29)
> [30555:0523/134928:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)

New instance started in another shell here

> 
> 2016-05-23 13:49:42.430 Atom[30555:14632852] Unexpected end of input
> 2016-05-23 13:49:42.443 Atom[30555:14632852] SyntaxError: Unexpected end of input
>     at Object.parse (native)
>     at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:232:28)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at Socket.Readable.push (_stream_readable.js:110:10)
>     at Pipe.onread (net.js:523:20)
> 2016-05-23 13:49:42.444 Atom[30555:14632852] Unexpected token H
> 2016-05-23 13:49:42.445 Atom[30555:14632852] SyntaxError: Unexpected token H
>     at Object.parse (native)
>     at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:232:28)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at Socket.Readable.push (_stream_readable.js:110:10)
>     at Pipe.onread (net.js:523:20)

**Comment by lee-dohm** [comment]
> From shell:
> 
> %> atom .
> %> atom .
> End result - one atom window instance.

This is the expected result. If you open the same directory twice the second call should simply bring the original window to the front.

**Comment by bedge** [comment]
ok, bad example that time - I was replicating @lee-dohm 's example.

My problem is using a different directory for each instance.

**Comment by lee-dohm** [comment]
Ok, so to be sure that I'm replicating what you're talking about. I have two local repositories: `~/Source/atom` and `~/Source/settings-view`. Here's what I tried this time:

1. Launch terminal window (it starts in my home directory `~`)
1. Launch Atom with `atom ~/Source/atom`
1. Wait for it to start
1. Switch back to the same terminal window (it is still in my home directory `~`)
1. Launch Atom with `atom ~/Source/settings-view`

Expected and Actual: Two separate windows are open ... one for `~/Source/atom` and one for `~/Source/settings-view`

Additionally, I tried:

1. Launch terminal window (it starts in my home directory `~`)
1. Launch Atom with `atom ~/Source/atom`
1. Wait for it to start
1. Switch back to the same terminal window (it is still in my home directory `~`)
1. Change directory to `atom ~/Source/atom`
1. Launch Atom with `atom .`

Expected and Actual: One Atom window open for `~/Source/atom`

Is there some scenario that I'm not taking into account?

**Comment by bedge** [comment]
Nope, that's it. The first case - running 2 instances of atom passing a different path as an argument to each instance.
The first one opens atom at the specified path, the second one does not open any new windows.

However, if the -fl args are specified for the initial atom instance, I get this error on the original console immediately after I try to instantiate the second instance:

> 2016-05-23 14:26:15.015 Atom[57910:14693057] Unexpected end of input
> 2016-05-23 14:26:15.020 Atom[57910:14693057] SyntaxError: Unexpected end of input
>     at Object.parse (native)
>     at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:232:28)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at Socket.Readable.push (_stream_readable.js:110:10)
>     at Pipe.onread (net.js:523:20)
> 2016-05-23 14:26:15.020 Atom[57910:14693057] Unexpected token d
> 2016-05-23 14:26:15.021 Atom[57910:14693057] SyntaxError: Unexpected token d
>     at Object.parse (native)
>     at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:232:28)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at Socket.Readable.push (_stream_readable.js:110:10)
>     at Pipe.onread (net.js:523:20)
>

**Comment by lee-dohm** [comment]
So is the error the part that you are reporting as a bug? Or is it that a second window is not opened?

**Comment by bedge** [comment]
My original complaint is that I can't open more than one atom window from a shell. I used to be able to, but not now. It broke maybe 3 months ago.
The error is just additional info that I noticed in the process of digging deeper.

What I resort to now is File -> New window, then File -> Add project folder, as it's the only way I can open multiple locations with Atom.

**Comment by lee-dohm** [comment]
@bedge Can you give some steps to reproduce the problem that this bug is intended to reveal? As it stands, I have no problem opening additional windows with the `-n` parameter. Here's what I did:

1. Launch a terminal window
1. Change directory to my local Atom repository at `~/Source/atom`
1. Launch Atom with `atom .`
1. Wait for Atom to start
1. Change back to the terminal window (still at `~/Source/atom`)
1. Launch Atom with `atom -n .`

Expected and Actual: Two separate Atom windows are open, both with `~/Source/atom`

**Comment by bedge** [comment]
Your steps do not yield the same result for me. I do not see 2 windows. Obviously there's some corner case in my atom config that is causing this. 
Although, I'm not the only one as others have confirmed this as well.

I could completely purge Atom & reinstall, but I expect that will fix it and the repeatability will be lost.
If you have some specific things you'd like me to try, I can do so. 
As it stands, I don't know what else to provide. 
I'll attempt the atom purge & reinstall later and see of that does fix it.

**Comment by muendelezaji** [comment]
Just to chime in on this, I'm having a similar problem, running 1.7.4 on OS X 10.11.4. Seems to have started a couple of weeks ago, but haven't been able to point out exactly when.

There aren't any obvious errors with `atom -fnl`, it just does not open a new window.
Here is output from the first window: `bash -x atom -fnl .`:
```
$ bash -x atom -fnl .
++ uname
+ '[' Darwin == Darwin ']'
+ OS=Mac
++ basename atom
+ '[' atom == atom-beta ']'
+ BETA_VERSION=
+ getopts :wtfvh-: opt
+ case "$opt" in
+ EXPECT_OUTPUT=1
+ getopts :wtfvh-: opt
+ case "$opt" in
+ getopts :wtfvh-: opt
+ case "$opt" in
+ getopts :wtfvh-: opt
+ '[' ']'
+ '[' 1 ']'
+ export ELECTRON_ENABLE_LOGGING=1
+ ELECTRON_ENABLE_LOGGING=1
+ '[' Mac == Mac ']'
+ '[' -n '' ']'
+ ATOM_APP_NAME=Atom.app
+ '[' -z '' ']'
+ '[' -x /Applications/Atom.app ']'
+ ATOM_PATH=/Applications
+ '[' 1 ']'
++ pwd
+ /Applications/Atom.app/Contents/MacOS/Atom --executed-from=/Users/user/first_dir --pid=1150 -fnl .
[1154:0523/225418:WARNING:resource_bundle.cc(305)] locale_file_path.empty() for locale English
2016-05-23 22:54:18.741 Atom[1154:5764617] App load time: 502ms
[1154:0523/225419:INFO:CONSOLE(52)] "Window load time: 382ms", source: file:///opt/homebrew-cask/Caskroom/atom/1.4.3/Atom.app/Contents/Resources/app.asar/static/index.js (52)
[1154:0523/225419:INFO:CONSOLE(52)] "Window load time: 384ms", source: file:///opt/homebrew-cask/Caskroom/atom/1.4.3/Atom.app/Contents/Resources/app.asar/static/index.js (52)
[1154:0523/225419:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[1154:0523/225420:INFO:CONSOLE(0)] "::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[1154:0523/225421:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
[1154:0523/225422:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
```

Then for subsequent windows:
```
$ bash -x atom -fnl .
++ uname
+ '[' Darwin == Darwin ']'
+ OS=Mac
++ basename atom
+ '[' atom == atom-beta ']'
+ BETA_VERSION=
+ getopts :wtfvh-: opt
+ case "$opt" in
+ EXPECT_OUTPUT=1
+ getopts :wtfvh-: opt
+ case "$opt" in
+ getopts :wtfvh-: opt
+ case "$opt" in
+ getopts :wtfvh-: opt
+ '[' ']'
+ '[' 1 ']'
+ export ELECTRON_ENABLE_LOGGING=1
+ ELECTRON_ENABLE_LOGGING=1
+ '[' Mac == Mac ']'
+ '[' -n '' ']'
+ ATOM_APP_NAME=Atom.app
+ '[' -z '' ']'
+ '[' -x /Applications/Atom.app ']'
+ ATOM_PATH=/Applications
+ '[' 1 ']'
++ pwd
+ /Applications/Atom.app/Contents/MacOS/Atom --executed-from=/Users/user/second_dir --pid=1231 -fnl .
[1235:0523/225507:WARNING:resource_bundle.cc(305)] locale_file_path.empty() for locale English
2016-05-23 22:55:07.591 Atom[1235:5766093] App load time: 288ms
+ exit 0
```

Note that the first instance stays open, while the subsequent ones close immediately after. On the dock, a new Atom icon appears, then quickly disappears.

**Comment by lee-dohm** [comment]
To be clear, are we talking about Atom windows? Or icons on the Dock? I see two Atom windows but only one icon on the Dock. (This is the expected behavior.)

**Comment by muendelezaji** [comment]
Atom windows. 
That information about the dock behaviour was just extra. If my understanding is correct, the dock behaviour is fine i.e. new icon appears momentarily, then gets "merged" into the window list of already open Atom.

**Comment by lee-dohm** [comment]
@bedge Assuming that it is a configuration thing, I backed up my Atom configuration and deleted my entire `~/.atom` directory and then ran my last set of repro steps again. I got the same results (two windows, one Dock icon) as before. Would you mind pasting your `~/.atom/config.cson` in a Gist?

**Comment by bedge** [comment]
Remembered to remove my userToken this time :-)

https://gist.github.com/bedge/4969cd67ae2d109efd97ae346dbc97f6

**Comment by bedge** [comment]
I just tried renaming ~/.atom, and restarting - I can still only open one atom window from the cmdline.
Will try deleting & reinstalling next

**Comment by muendelezaji** [comment]
I can confirm this to be the case as well. Renamed ~/.atom and started
afresh, but second window just will not open.

I just tried renaming ~/.atom, and restarting - I can still only open one
atom window from the cmdline.
Will try deleting & reinstalling next

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/atom/atom/issues/11712#issuecomment-221131442>

**Comment by lee-dohm** [comment]
Did both of you exit Atom before you renamed the `~/.atom` directory?

**Comment by bedge** [comment]
yes, I quit atom first.

**Comment by muendelezaji** [comment]
Exited and checked ps/activity monitor as well

**Comment by chrisdhanaraj** [comment]
Same issue here; I nuked Atom completely (removed .atom, cli stuff, Atom app itself), and then reinstalled - same issue.

**Comment by gmmeyer** [comment]
Same issue here, I can only open one window from the command line. I only see an error when I look in the OSX console:

```
5/24/16 11:57:38.893 AM Atom[86646]: SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:232:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

**Comment by 50Wliu** [comment]
Just curious: what terminals (eg bash, fish, csh, etc.) is everyone using?

**Comment by gmmeyer** [comment]
I'm on zsh.

**Comment by bedge** [comment]
zsh, but it's irrelevant, same on bash.

**Comment by jackcasey** [comment]
OSX Yosemite and bash here and I get the same issue:
```
~ $ cd project 1
~/project1 $ atom .
~/project1 $ cd ../project2
~/project2 $ atom .
~/project2 $ atom -n .
~/project2 $ atom -n
```
**Result**: Only one atom window open and it's for project1. project2 is nowhere to be seen. 
This used to work some weeks(months?) ago.

**Note** This also stops git commit messages from being opened in atom when `GIT_EDITOR=atom --wait` which is pretty annoying!

**Comment by msroest** [comment]
I'm getting the same issue with Git on windows.  Using core.editor as atom --wait from powershell it just launches cmd (no atom window) it was working fine with 1.7.3

**Comment by 50Wliu** [comment]
> I'm getting the same issue with Git on windows. Using core.editor as atom --wait from powershell it just launches cmd (no atom window) it was working fine with 1.7.3

This is a different bug that is specific to Windows (I believe it's already been fixed/a fix is in the works).

**Comment by richardtape** [comment]
Same issue here on OS X 10.10.5, Atom v 1.7.4 running zsh 5.1.1

Once one atom window is open, regardless of how that window was opened, no other atom window can be opened from the command line (even with `--new-window`). Opening another window via File > New Window still works fine.

**Comment by albireox** [comment]
Fish, although I think it happens with all shells.

**Comment by anrid** [comment]
I’ve had this issue for a good 3 months at least.
Cannot open more than one instance of Atom using command line `atom`.
Tried renaming the `~/.atom` folder etc.
I’m on OSX 10.11.4 El Capitan.

**Comment by albireox** [comment]
Not sure if this helps, but if I do

`bash -x atom-beta -fnl .`

In a terminal I get

```
++ uname
+ '[' Darwin == Darwin ']'
+ OS=Mac
++ basename atom-beta
+ '[' atom-beta == atom-beta ']'
+ BETA_VERSION=true
+ getopts :wtfvh-: opt
+ case "$opt" in
+ EXPECT_OUTPUT=1
+ getopts :wtfvh-: opt
+ case "$opt" in
+ getopts :wtfvh-: opt
+ case "$opt" in
+ getopts :wtfvh-: opt
+ '[' ']'
+ '[' 1 ']'
+ export ELECTRON_ENABLE_LOGGING=1
+ ELECTRON_ENABLE_LOGGING=1
+ '[' Mac == Mac ']'
+ '[' -n true ']'
+ ATOM_APP_NAME='Atom Beta.app'
+ '[' -z '' ']'
+ '[' -x '/Applications/Atom Beta.app' ']'
+ ATOM_PATH=/Applications
+ '[' 1 ']'
++ pwd
+ '/Applications/Atom Beta.app/Contents/MacOS/Atom' --executed-from=/Users/albireo/Documents/Repo/external/RO --pid=24900 -fnl .
[24904:0601/104106:WARNING:resource_bundle.cc(305)] locale_file_path.empty() for locale English
2016-06-01 10:41:06.689 Atom[24904:3944675] App load time: 511ms
[24904:0601/104107:INFO:CONSOLE(52)] "Window load time: 504ms", source: file:///Applications/Atom%20Beta.app/Contents/Resources/app.asar/static/index.js (52)
[24904:0601/104108:INFO:CONSOLE(47)] "No deserializer found for", source: /Applications/Atom Beta.app/Contents/Resources/app.asar/src/deserializer-manager.js (47)
[24904:0601/104108:INFO:CONSOLE(0)] "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.", source:  (0)
```

Now, if I go to a different terminal and do `atom-beta -fnl .`, in the stdout of the first terminal I get these additional lines

```
2016-06-01 10:41:18.582 Atom[24904:3944675] Unexpected end of input
2016-06-01 10:41:18.592 Atom[24904:3944675] SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Socket.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/browser/atom-application.js:244:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
2016-06-01 10:41:18.593 Atom[24904:3944675] Unexpected token b
2016-06-01 10:41:18.595 Atom[24904:3944675] SyntaxError: Unexpected token b
    at Object.parse (native)
    at Socket.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/browser/atom-application.js:244:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

**Comment by jackcasey** [comment]
I have no idea how or why, but this is now fixed for me. I can a now open new atom windows from the command line manually with `atom .` and with `git commit` for editing the commit message. Still 1.7.4 - it just started working randomly. :/

**Comment by bedge** [comment]
Still broken for me. I get the exact same error as @albireox, also with 1.7.4.

**Comment by albireox** [comment]
Are there any news about this? This is still happening in Atom 1.8.0 and 1.9.0-beta0.

**Comment by richardtape** [comment]
For me a complete reinstall of mac os x has solved this. I'm not suggesting that as a potential way forward for folk (I was forced into a reinstall, thanks macbook hd) but it seems to not be a native issue or a clash with an add-on - as I'm running the same version of Atom and the same add-ons, rather a mish-mash of problems which may be very difficult to debug.

**Comment by bedge** [comment]
Confirmed still broken on 1.8.0

OSX console reports this when it happens:

> 6/11/16 11:19:05.901 AM Atom[66936]: App load time: 275ms
> 6/11/16 11:19:05.912 AM Atom[64536]: Unexpected end of input
> 6/11/16 11:19:05.912 AM Atom[64536]: SyntaxError: Unexpected end of input
>     at Object.parse (native)
>     at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:244:28)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at Socket.Readable.push (_stream_readable.js:110:10)
>     at Pipe.onread (net.js:523:20)
> 6/11/16 11:19:05.912 AM Atom[64536]: Unexpected token G
> 6/11/16 11:19:05.913 AM Atom[64536]: SyntaxError: Unexpected token G
>     at Object.parse (native)
>     at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:244:28)
>     at emitOne (events.js:77:13)
>     at Socket.emit (events.js:169:7)
>     at readableAddChunk (_stream_readable.js:146:16)
>     at Socket.Readable.push (_stream_readable.js:110:10)
>     at Pipe.onread (net.js:523:20)

I don't understand how this is not diagnosable with so many provided stack traces.

Is there any additional information that I can provide to assist in resolving?

**Comment by 50Wliu** [comment]
It's hard to diagnose because the error is happening when it's reading JSON, and we don't have access to said JSON in the stack trace.

I suppose what could help is if you add a console.log statement when the data is being passed in, but that would require a rebuild of Atom.

**Comment by muendelezaji** [comment]
Following up on my experiences a couple of weeks ago, I've found as a workaround that it works when run with an empty environment i.e. `env -i /usr/local/bin/atom filename`. Does this work for anyone else?

**Comment by albireox** [comment]
That seems to work for me, and the behaviour is the expected. For now I have aliased atom-beta to `env -i /usr/local/bin/atom-beta`.

**Comment by bedge** [comment]
Confirmed, 
`env -i /usr/local/bin/atom <PATH>
`
works for me too, in that multiple invocations do result in multiple open windows.

**Comment by chrisdhanaraj** [comment]
Confirmed that the current atom-beta resolves my issue.

**Comment by jjwon0** [comment]
`atom-beta` works for me as well, thanks!

**Comment by jackcasey** [comment]
Can confirm the latest beta has fixed the issue for me. Thanks.

**Comment by 50Wliu** [comment]
From the recent comments, it appears that Atom 1.9.0-beta0 has resolved this issue, so I'm closing this.
