### ISSUE TITLE
File opened from UNC Patch results empty

### ISSUE THREAD

**Issue by eldblz** [atom/atom#11714]
Using Atom 1.7.3 on Windows 10 Version 1511 (Build 10586.218)

I cannot open files on mapped network letter (for example Z: mapped to \\server\folder\). The folder tree on the left pane correctly shows the files and folders available. But, when I open a file the tab is empty, as with new files. The content in the file does not appear. I have reproduced this behavior with different files and here a gif demostrating the problem:

http://recordit.co/PbyCXTYcsd

Seems a similar issue to this closed one:
https://github.com/atom/atom/issues/2885

**Comment by lee-dohm** [comment]
Have you tried reproducing the problem in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

In the future, please fill out the template. It saves time for both of us by helping us get to the bottom of the problem faster.

**Comment by eldblz** [comment]
Sorry for not following the template, the issue persists in safe mode

**Comment by lee-dohm** [comment]
If you can try out the [Beta](https://atom.io/beta) and let us know if it is fixed there, that would be helpful. According to https://github.com/atom/atom/issues/11481 it should be fixed.

**Comment by eldblz** [comment]
Seems fixed in the last beta! Thank you very much for your help!

**Comment by 50Wliu** [comment]
Awesome, thanks for reporting back @eldblz!

**Comment by brandonk3nt** [comment]
Hey how can I fix this on Mac? Atom keeps opening empty files and I've had to switch to using VSCode for the remainder of my work day...

**Comment by 50Wliu** [comment]
> Hey how can I fix this on Mac?

As described above, you can install Atom Beta or wait until Atom 1.8.0 is considered stable.
