### ISSUE TITLE
Bug! Can't remove folders in non-disk volume

### ISSUE THREAD

**Issue by CaledoniaProject** [atom/atom#11716]
I have a memory based disk created with `hdiutil attach -nomount ram://size`

When I delete files in that folder, atom says

![screen 2016-05-09 at 13 58 33](https://cloud.githubusercontent.com/assets/1357701/15104741/256b3bc0-15ee-11e6-81a1-b0d5583861f2.jpg)

It works in Finder, because Finder does not move it to trash if it's not applicable, it simply deletes them

**Comment by BlaM** [comment]
Same issue on Windows if I work on network drives on my NAS.

**Comment by 50Wliu** [comment]
Please move this to the [atom/tree-view](https://github.com/atom/tree-view) repository.  Thanks!
