### ISSUE TITLE
Integer configuration type does not allow the value 0

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#11715]
### Description

The `integer` configuration type does not allow the value `0` to be entered.

### Steps to Reproduce

1. Install a package that has an `integer` type configuration setting ([linter-phpcs](https://atom.io/packages/linter-phpcs) for example)
2. Open the settings for the package installed in step 1
3. Attempt to set the setting (eg. Warning Severity) to a value of `0`
4. Note how it instead sets the default value.

**Expected behavior:**

`0` is allowed to be set.

**Actual behavior:**

All integer values other than `0` are allowed, however attempting to set `0` just sets the default value.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

OS: Windows 10 Professional x64 (Technical Preview)
Atom: 1.8.0-beta3
apm:
```
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.4.windows.1
visual studio 2015
```

Also reported in https://github.com/AtomLinter/linter-phpcs/issues/154 by a user on Win10/Atom v1.7.3.

**Comment by 50Wliu** [comment]
Please move this to the settings-view repository.
