### ISSUE TITLE
Atom fails to build on Windows 10

### ISSUE THREAD

**Issue by DamnedScholar** [atom/atom#11710]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

I would like to manage my versions of Atom via building the executables from source, but I've been unable to successfully build anything with script/build.

### Steps to Reproduce

1. Follow the instructions [here](https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md).
2. Navigate to local Atom clone.
3. Check out any version (that I've tried so far).
4. Wait a few minutes for the errors to roll in.

**Expected behavior:** Given NodeJS 4.4, Python 2.7, and an installed Visual Studio 2015 with Visual C++ support, Atom should build as easily on Windows as it does on Linux.

**Actual behavior:** 

```
$ script/build
Node: v4.4.4
npm: v2.13.3
Python: v2.7.11
Installing build modules...
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading 32-bit node.lib
gyp ERR! stack     at Request.<anonymous> (D:\github\atom\atom\build\node_modules\npm\node_modules\node-gyp\lib\install.js:377:20)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (D:\github\atom\atom\build\node_modules\npm\node_modules\request\request.js:992:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:419:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:309:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\github\\atom\\atom\\build\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\github\atom\atom\build\node_modules\minidump
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "D:\\github\\atom\\atom\\build\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=D:\\github\\atom\\atom\\build\\.npmrc" "install" "--loglevel" "error"
npm ERR! node v4.4.4
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minidump@0.9.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\github\atom\atom\build\npm-debug.log
```

The error log is here: https://gist.github.com/DamnedScholar/99e4359cd3c8112b2327cc238545fedf

### Versions

```
Windows 10
Microsoft Visual Studio Community 2015
    Version 14.0.25123.00 Update 2
    Microsoft .NET Framework
    Version 4.6.01038
Node: v4.4.0
npm: v3.8.6
Python: v2.7.11
```

**Comment by damieng** [comment]
It definitely does build on Windows 10 - that's my daily driver. Do you have the 32-bit or 64-bit verison of node installed? Is your OS 32-bit?

My ouptut is

```
Node: v4.2.4
npm: v2.14.12
Python: v2.7.11
Installing build modules...
Installing build modules...
WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"4.2.4","npm":"2.14.12"})
=> Took 62676ms.

Installing apm...
=> Took 41181ms.

Deleting old packages...
=> Took 566ms.
```

etc. 

Running on Windows 10 Pro 64-bit retail through 160422-1940 insider builds no problem.

**Comment by DamnedScholar** [comment]
Everything's 64-bit (Node, OS, processor). I thought it was weird that the error mentioned a 32-bit node.lib. I actually installed 32-bit Node to test, and it threw the same error but citing a 64-bit node.lib. So either way, it's a 404 from some (to me) unknown location regarding a Node file that's apparently only important for Windows (because Linux builds it just fine).

**Comment by damieng** [comment]
I believe the problem is the fact you are using npm 3.  There are bugs on the node-gyp mailing list that indicate node-gyp requires either npm 2 or more specifically the npm that ships with node.js for Windows.  

https://github.com/nodejs/node-gyp/issues/724

**Comment by DamnedScholar** [comment]
What version of node-gyp do you have?

**Comment by DamnedScholar** [comment]
Nevermind, it seems I've fixed it. Here's the blow-by-blow for anybody who comes along and reads this:

1. The initial error was due to me having installed Visual Studio improperly. The web installer was giving me shit, so I [downloaded the ISO](https://www.visualstudio.com/downloads/download-visual-studio-vs) and installed it that way. I don't even remember what happened, but it errored at me and it was late, so I just ran the bare bones install. Then I went to bed. I fixed that problem last night, by installing the tools I needed.

2. I had messed around a bit, so I completely removed and reinstalled Node 4.4.4.

3. Then I ran into a new error.
```
λ script\build
Node: v4.4.4
npm: v2.13.3
Python: v2.7.11
Installing build modules...
gyp: C:\Users\stick\.node-gyp\4.4.4\common.gypi not found (cwd: D:\github\atom\atom\build\node_modules\minidump) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (D:\github\atom\atom\build\node_modules\npm\node_modules\node-gyp\lib\configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\github\\atom\\atom\\build\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
```
4. Did some research and found [this package](https://www.npmjs.com/package/node-gyp-install). I installed it, ran it, and voilà. Everything just works.

**Comment by damieng** [comment]
Glad you're up and running.

Node-gyp normally installs automatically however it's worth doing a
script/clean as some script/build operations that fail leave things in a
state where script/build can't recover.

**Comment by DamnedScholar** [comment]
I'm not sure how it would be that, since I didn't clean things tonight (I did refresh my local repo last night when I reinstalled everything), but I did a few failed `script\build` attempts following that. Running `node-gyp-install` gave node-gyp exactly what it was looking for.

A lot of people are having similar-but-different issues with this package.

**Comment by Sneha-Watharkar** [comment]
I am trying to run script/build and i get this error:

Installing apm
npm ERR! path W:\GitContributions\atom\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\ansicolors
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'W:\GitContributions\atom\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\ansicolors' -> 'W:\GitContributions\atom\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

I can see that in package.json, ansicolors module is present but its not getting installed.

Any leads appreciated!

**Comment by damieng** [comment]
Try `build\clean` first and let it complete.   Sometimes the node_modules folders either directly under Atom or under the scripts folder seem to get in a bad state and ansicolors just happens to be the first one it tries to process.
