### ISSUE TITLE
Default KeyBinding: Shift-Delete should be 'editor:delete-line', not 'core:cut'

### ISSUE THREAD

**Issue by lope** [atom/atom#11717]
Atom.oi 1.5.3 default keybindings on Linux

(only relevant keybindings shown)

```
'body':
  'ctrl-x': 'core:cut'
  'shift-delete': 'core:cut'
```

In my opinion this makes NO SENSE. It should be as follows

```
'body':
  'ctrl-x': 'core:cut'
  'shift-delete': 'editor:delete-line'
```

Cut is cut, and delete is delete.

There is no button bound to 'editor:delete-line' which is an extremely commonly needed action in programming.
core:cut is a very poor replacement for delete-line, because it overwrites the clipboard which may have something useful in it, with something that's useless and the user is trying to discard.

**Comment by mehcode** [comment]
1. `ctrl-shift-k` is bound to `editor:delete-line`

2. `shift-delete` is bound to cut because that's how it is on all other text editors in linux. `shift-delete`, `ctrl-insert`, and `shift-insert` are very common place in linux for right-handed cut/copy/paste commands.

**Comment by lope** [comment]
Oh, well I came from windows about 3 years ago, so the right handed cut/copy/paste are not native to me.
I only use insert for copy and paste in therminals, then left hand for GUI stuff that handles ctrl xcv.

It seems a bit silly having two sets of keys for cut/copy/paste for left hand and right hand. But I guess people can just customize to what they want.
It's harder (takes longer) to find the letter K on the keyboard without looking than the delete button.

**Comment by 50Wliu** [comment]
> Oh, well I came from windows about 3 years ago, so the right handed cut/copy/paste are not native to me.

Windows uses the exact same keybindings :wink:.

**Comment by lope** [comment]
Lol, I doubt it's the standard. It's certainly not what get's taught or recommended.

**Comment by 50Wliu** [comment]
They're legacy keybindings from I want to say the 1980s or 90s (IBM "standardized" them I think?) that have been kept so as to not annoy the 0.01% of people that still use them.

**Comment by lope** [comment]
The good old 0.01%

**Comment by mehcode** [comment]
https://github.com/atom/atom/blob/master/keymaps/base.cson#L16

@lope

**Comment by lope** [comment]
@mehcode Oh I see, it's in base.cson.

**Comment by mehcode** [comment]
I can answer for the reason behind two sets of copy/paste bindings. In traditional unix (so most text-based editors and terminal applications themselves) the ctrl/shift insert/delete keybindings refer to the PRIMARY buffer while the ctrl x/c/v bindings refer to the CLIPBOARD buffer.

I'd strongly be in favor of doing this in Atom for linux as long-time linux users grow accustomed to the two buffers.

The key difference is select-on-copy. Applications that support that dump the copied text to the PRIMARY buffer.

**Comment by damieng** [comment]
Also going to -1 this. shift-delete on windows is another shortcut for cut in every app I've used.  

If there is a compelling reason to change it on macOS or Linux I'd be up for reopening this issue.
