### ISSUE TITLE
Atom Doesn't install corerctly on Windows 10

### ISSUE THREAD

**Issue by Godeolo** [atom/atom#11722]
I have installed Atom several times, i even uninstalled the antivir and desactivated the firewall but those messages keeps apearing, pls help
![captura4](https://cloud.githubusercontent.com/assets/19273677/15128369/0cd1db9c-1601-11e6-822b-4dcb9eeea481.PNG)

**Comment by 50Wliu** [comment]
Please remove the `%USERPROFILE%\.atom` directory and try again.  If the problem persists please comment here and I'll reopen this issue.
