### ISSUE TITLE
Atom1.7.3 crashes every few minutes on Win10 x64

### ISSUE THREAD

**Issue by andrinheusser** [atom/atom#11736]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Windows 10 x64, Atom v1.7.3 (installed with the Windows installer)

Atom is crashing every 3-5 Minutes or so without any error message. The dev console doesn't show any information either.

Happens when editing a local file, while typing. 

Maybe this is related? #11590 talks about this happening while having lots of uncommited files. In my case just one is enough. Using atom in safe mode and editing a file that is not under version control works fine.

[operation_log.txt](https://gist.github.com/andrinheusser/7c753cf2552dc3c75f7dda96647d06f3)

### Steps to Reproduce

1. Use Atom v1.7.2 for a while on Windows 10 x64.
2. Editor crashes almost every hour when I'm regularly typing in the editor.

Expected behavior: Should not crash that often.

Actual behavior: Crashes frequently.

### Versions

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.3
git
visual studio

Win 10 x64
Intel i5-2500 @ 3.3 GHz
16 GB Ram

**Comment by damieng** [comment]
This is likely the same problem as https://github.com/atom/atom/issues/11590 as you summarized. We'll track it there.
