### ISSUE TITLE
New delay/duplication in opening file from sshfs mounted drive 

### ISSUE THREAD

**Issue by breschke** [atom/atom#11730]
Up until recently, I have been able to open and edit files in sshfs-mounted drives without problems. Now, when I try to open a file, Atom does the following:

1) Displays a blank tab for 15+ seconds; the name of the tab is the name of the file I'm trying to open
2) Opens the file in a new tab with all the expected content, but the title of the tab is in italics
3) If I close the tab in (2) or navigate to the tab in (1), I see that the formerly blank tab now displays the content expected.

This is very frustrating.

OS X 10.11.2
Atom 1.7.3

**Comment by breschke** [comment]
I didn't see the behavior I'm experiencing described in #2456, but I just tried the suggestion of @nolandg and found the issue does seem to be related to .git integration: I renamed my .git folder in my project to something else (effectively removing git integration) and problem goes away.

Again, I wasn't experiencing this until recently, though, and I haven't had the problems described in #2456. Could a recent update have broken sshfs for me?

**Comment by 50Wliu** [comment]
@breschke Users have reported that the Atom 1.8.0 betas have improved network handling - can you please try the beta and report back?  Thanks!

**Comment by breschke** [comment]
@50Wliu I've downloaded the beta, re-enabled git integration, and I'm pleased to report that I can no longer replicate the issue.

**Comment by 50Wliu** [comment]
:tada:
