### ISSUE TITLE
Atom helper occupies high CPU resource

### ISSUE THREAD

**Issue by Shikugawa** [atom/atom#11739]
When I use atom on mac(OS X 10.11.4), atom is very dull behavior, so I check Activity monitor, and I discovered that atom helper occupies high CPU resource. Please fix this symptom.

**Comment by 50Wliu** [comment]
Please open a new issue and follow the issue template so that we can further triage this issue.  Thanks!

**Comment by sagarpanchal** [comment]
@50Wliu Can you help me with this issue? -> https://github.com/atom/tree-view/issues/837
