### ISSUE TITLE
Lazy evaluation of search results may fail if the app window gets resized

### ISSUE THREAD

**Issue by fabiospampinato** [atom/atom#11735]
### Description

Lazy evaluation of search results gets triggered on scroll, that's way the initial showed results are a bit more than what can be displayed without scrolling. The problem is that I can search for something with a lot of results, than resize the app window to be double in size and now all the initial results fit comfortably within the panel, and since I cannot scroll them I can't see the other results.

### Steps to Reproduce

1. Resize Atom's window to be small enough 
2. Search for something with a lot of results
3. Double Atom's window size, or increase it enough
4. Try view all the results and fail 

**Expected behavior:** I guess a dirty and easy fix would be to recompute the initial results when a resize event happen (hopefully using debouncing) if not all of them are displayed.

**Actual behavior:** Only a fraction of the results are visible, in a now unscrollable list.

### Versions

1.8.0-beta3

**Comment by 50Wliu** [comment]
> Search for something with a lot of results

Can you elaborate on how you're searching?  Is it through find-and-replace?  Keybindings?  etc.

**Comment by fabiospampinato** [comment]
Sure, I'm just doing:

1. cmd + shift + f
2. keyword
3. enter

**Comment by 50Wliu** [comment]
Thanks!  In that case, can you please reopen this issue on the [atom/find-and-replace](https://github.com/atom/find-and-replace) repository?

**Comment by fabiospampinato** [comment]
Done.
