### ISSUE TITLE
Error in gitbash with atom shell command not handling directories with spaces in Windows 10

### ISSUE THREAD

**Issue by MirPresT** [atom/atom#11732]
### Description

Attempting to use the `atom .`  command was producing the following error in git bash. Running the atom command in the windows command prompt worked fine but gitbash gives the following error.

![Image](https://cloud.githubusercontent.com/assets/12580197/15162400/8ddc48c4-16b7-11e6-89f4-a030b70eb11f.PNG)

### Solution

I noticed that my user folder "Terrell Big T Vest" was being cut off at just "Terrell". I guess the shell command wasn't dealing with the space in the directory path. The solution that solved this issue just involved adding double quotes around a portion of the pushd command like so. 

#### Previous Code

[Link to specific line of code](https://github.com/atom/atom/blob/f00ac5ca0a4c64f4f1b05c394ec4ecfb70fa59ff/resources/win/atom.sh#L2
)

```sh
pushd $(dirname "$0") > /dev/null
```

#### Solution Code
```sh
pushd "$(dirname "$0")" > /dev/null
```

### Atom Version
1.7.3

### OS Version

Windows 10 version 1511 (OS build 10586.0)

**Expected behavior:** open folder in atom at directory of bash

**Actual behavior:** gave the error provided above via a screenshot and did not open atom.

### Additional Comments
Again, I tested the original code in the windows command prompt and everything works as expected. The original code also works on windows when the user folder does not contain any spaces.
Hopefully this change can be made to the atom.sh folder to prevent this issue with others who have a user folder that contains spaces.

**Comment by damieng** [comment]
What version/distribution of bash are you using?  (e.g. GitHub for Windows 1.9 bash)

The current solution works with spaces in the path on both MSYS2 (Bash 4) and MSYS from MINGW (Bash 3.1.0).

**Comment by damieng** [comment]
Okay, I see where it can fail - if the relative path from the current working folder to where the script is running contains a path.  Ugh, the test matrix for spaces in paths just goes on forever.  Fixing.

**Comment by MirPresT** [comment]
@damieng @50Wliu  thanks for looking into this so quickly. I'm glad the fix works.
