### ISSUE TITLE
Undesired HTML character encoding

### ISSUE THREAD

**Issue by djmtype** [atom/atom#11748]
It seems pretty coincidental if both packages I've tried ([html-entities](https://atom.io/packages/html-entities) and [escape-utils](https://atom.io/packages/escape-utils)) for encoding HTML entities produces the same unfavorable results. Is Atom responsible?

For example, encoding closed curly quotes returns `&CloseCurlyQuote;`. Preferably, `&rsquo;` is the desired result.

Is `&CloseCurlyQuote;` the preferred HTML5 method? Maybe I'm just too old?

-- 
Atom 1.7.3
Mac OS 10.11.4

**Comment by thomasjo** [comment]
This is indeed a HTML5 concept, and the behavior stems from the npm package [html-entities](https://www.npmjs.com/package/html-entities) (see [html5-entities.js](https://github.com/mdevils/node-html-entities/blob/1c195beafd4c013f2e07811eeae733f43ebfa137/lib/html5-entities.js)).

In other words this has nothing to do with Atom.

---
Also, for future reference, please consider asking these types of questions in our Slack channel, or on https://discuss.atom.io/.
