### ISSUE TITLE
Atom has crashed. OK, what to do next ?

### ISSUE THREAD

**Issue by mh-cbon** [atom/atom#11747]
My instance of atom editor has crashed after i forcibly closed it.

I tried to restart it, it kept saying "Atom has crashed, please report it".

I m not annoyed by it, its my first time in 6 months use.

But I m annoyed that i don t know what to do next.

I mean, i had to delete files randomly in my .atom folder until it restarts.

I would like to ask if you could provide some documentation about which steps to execute when such situation occurs.
- what metrics you d like to get and how to get them (free -m etc)
- how to get the crash dump if any
- and then, which files should probably be deleted first, then try restart, then which files, then restart etc
- maybe provide a template to report that issue

Maybe that could appear in http://flight-manual.atom.io/ ? With the keyword crash ?

**Comment by amytruong** [comment]
:cry: Sorry this is happening for you. 
Here's a link to report bugs - https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs
This might help the developers figure out what's going on.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/11747#issuecomment-221297876. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
