### ISSUE TITLE
Atom 1.7.3 crashes on startup (segmentation fault) on Ubuntu 14.04

### ISSUE THREAD

**Issue by SlimeQ** [atom/atom#11743]
Atom is suddenly crashing on startup. I did not recently add any packages, but I did recently attempt to open an 81K xml file which caused the initial crash. I can open atom in safe mode, but **cannot disable most of my packages**. i've also tried disabling packages via apm and it hasn't seemed to do anything. this is the only error message i've seen;

```
atom --de/usr/bin/atom: line 115:  8832 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 324ms
Failed to get crash dump id.
Report Id: 
Failed to get crash dump id.
Report Id:
```

**Comment by 50Wliu** [comment]
What OS are you on, and what Atom version?

In the future please fill out the provided issue template.

**Comment by 50Wliu** [comment]
What do you mean by "cannot disable most of my packages"?

**Comment by lee-dohm** [comment]
> i've also tried disabling packages via apm and it hasn't seemed to do anything. 

You have to restart Atom for any packages disabled at the command line to take effect.

> I can open atom in safe mode,

This most likely means that you have a package that is causing the Issue. Can you include the list of packages you have installed? (You can get the list easily with `apm list`.)

**Comment by erlopez** [comment]
I'm too having a core dump file created when I start atom. I'm running Linux Mint (Ubuntu 14).
Basically, atom runs and I can use it fine; it just creates a core file every time it starts.

I'm my case, the problem may be related to the VirtualBox GL display (see core info below). 
I have a similar Linux Mint (Ubuntu 14) installation on a real desktop and the problem does not occur there.


Atom Version:
-------------
1.7.3 (Installed today from URL https://atom.io/download/deb)


My System (running on Virtualbox 4.3.28 with Win7 as host OS):
-----------------------------------------
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17
DISTRIB_CODENAME=qiana
DISTRIB_DESCRIPTION="Linux Mint 17 Qiana"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04" 


Atom Packages List:
-------------------
Built-in Atom Packages (89)
├── about@1.4.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.29.1
├── autocomplete-snippets@1.10.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.38.2
├── bracket-matcher@0.81.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.199.0
├── fuzzy-finder@1.0.5
├── git-diff@1.0.1
├── go-to-line@0.30.0
├── grammar-selector@0.48.1
├── image-view@0.57.0
├── incompatible-packages@0.25.1
├── keybinding-resolver@0.35.0
├── language-c@0.51.1
├── language-clojure@0.20.0
├── language-coffee-script@0.46.1
├── language-csharp@0.12.0
├── language-css@0.36.0
├── language-gfm@0.85.0
├── language-git@0.12.1
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.110.0
├── language-json@0.17.6
├── language-less@0.29.0
├── language-make@0.21.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.32.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.43.0
├── language-ruby@0.68.3
├── language-ruby-on-rails@0.25.0
├── language-sass@0.46.0
├── language-shellscript@0.21.0
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.1
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.4
├── language-yaml@0.25.1
├── line-ending-selector@0.3.1
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.63.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.2.0
├── one-light-syntax@1.2.0
├── one-light-ui@1.2.0
├── open-on-github@1.0.1
├── package-generator@1.0.0
├── settings-view@0.235.1
├── snippets@1.0.1
├── solarized-dark-syntax@1.0.0
├── solarized-light-syntax@1.0.0
├── spell-check@0.67.0
├── status-bar@1.1.2
├── styleguide@0.45.2
├── symbols-view@0.112.0
├── tabs@0.92.0
├── timecop@0.33.1
├── tree-view@0.205.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (1)  
└── blue-gray-syntax@0.4.0


Core Info:
----------
$ gdb --core=core /usr/share/atom/atom

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/share/atom/atom...(no debugging symbols found)...done.
[New LWP 5414]
[New LWP 5409]
[New LWP 5405]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Core was generated by `/usr/share/atom/atom --type=gpu-process --channel=5386.0.1476908062 --no-sandbo'.
Program terminated with signal SIGSEGV, Segmentation fault.

#0  0x00007f1d1b7aa5ba in ?? () from /usr/lib/x86_64-linux-gnu/VBoxOGLpackspu.so
#1  0x00007f1d1bc8ce55 in ?? () from /usr/lib/x86_64-linux-gnu/dri/vboxvideo_dri.so
#2  0x00007f1d1bcae60c in ?? () from /usr/lib/x86_64-linux-gnu/dri/vboxvideo_dri.so
#3  0x00007f1d1bcb2a4c in ?? () from /usr/lib/x86_64-linux-gnu/dri/vboxvideo_dri.so
#4  0x00007f1d2a1e1182 in start_thread (arg=0x7f1d2b761700) at pthread_create.c:312
#5  0x00007f1d23d7b47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by SlimeQ** [comment]
> What do you mean by "cannot disable most of my packages"?

in safe mode, i went through to disable all of my packages, and found i could only disable ~5 of the dozens that i had enabled. for the rest of them, the disable button was completely unresponsive. 

> You have to restart Atom for any packages disabled at the command line to take effect.

i was running apm with atom closed (because it literally wouldn't start) and when it started i was greeted with a frozen app complete with all of the themes/packages i had disabled.

i've since fixed this problem by doing a complete reinstall (move ~/.atom, install with dpkg), but this is the remaining package list after trying to uninstall a bunch of things and then just deleting the package folders. there may have been more packages installed but atom would still not start with this list
![screenshot from 2016-05-19 13 00 22](https://cloud.githubusercontent.com/assets/3934698/15402351/c6edf610-1dc1-11e6-9593-b27719a91b2e.png)

i did not get a full core dump like erlopez, or at least i don't know where to find it. the message i posted was after running from command line.

**Comment by SumNeuron** [comment]
I just downloaded atom according to its install guide and got:


`
/usr/bin/atom: line 129: 110869 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
`

**Comment by BenTeoNeb** [comment]
Same here. With WSL.

**Comment by 3141bishwa** [comment]
I'm having the same problem. I installed Atom after a fresh install of Ubuntu 17.10 and it doesn't work for me normally. It only works when i try  `atom --safe`.

**Comment by JDx1994** [comment]
Same issue as those above me.

**Comment by joicetm** [comment]
I am also facing the same issue, :(
I am using ubuntu 16.04

**Comment by pldilley** [comment]
Likewise, Ubuntu 17.10.

**Comment by emorgado** [comment]
Same problem on Ubuntu 17.10. but after restart my machine, it works.

**Comment by SumNeuron** [comment]
@SlimeQ  can we get this re-opened? How was it closed in the first place. There is no current solution and the issue seems to have gotten worse as now if atom loads, then I see html.

**Comment by mindaslab** [comment]
I have this issue too :(

**Comment by Torbuntu** [comment]
Just downloaded the RPM from github and installed "successfully" but then the Segmentation fault when trying to launch:

`/usr/bin/atom: line 157: 11622 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
`

OS: Fedora 29 Gnome

**Comment by andyfr** [comment]
I'm running in to the same issue for a fresh installation on fedora 29 with xfce:

> /usr/bin/atom: line 157: 23284 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

**Comment by rsese** [comment]
@Torbuntu @andyfr - I think the issue you're hitting might be resolved by #18012, but that fix is only available in the latest beta (currently 1.32.0-beta3) right now . Can you try the beta and let us know if you still get the segfault?

**Comment by Torbuntu** [comment]
@rsese I quickly grabbed the beta package and installed. So far it works as normal! Thanks for the recommendation. All I did was grab the beta and install the RPM package like I normally would (using dnfdragora on Fedora 29). 

I've also found that using the Flatpak in the software center worked in the meantime. Just in case this fix doesn't work for the next person.

**Comment by andyfr** [comment]
@rsese 1.32.0-beta3 works like a charm, thx!
