### ISSUE TITLE
Suddenly typed characters was doubled automatically some lines below (incl. screencast)

### ISSUE THREAD

**Issue by itinance** [atom/atom#11754]
### Description

This funny issue isn't reproducable for me and i don't know if it is a feature or a bug ;)
However, at some point Atom began to double my typing input some lines below.

I recorded a screencast https://www.youtube.com/watch?v=TmNzQKavbQY&feature=youtu.be

It suddenly began and it stopped after switching from the IDE-Window to youtube for uploading the screencast and returning back to IDE.

![screen shot 2016-05-15 at 17 22 10](https://cloud.githubusercontent.com/assets/1758597/15275044/abda4a0c-1ac1-11e6-9e2d-9114938192bc.png)
bQY

### Steps to Reproduce

not possible. It suddenly began and it (possible) stops with a switch between IDE-Window and Chrome and back.

### Versions

```
$ atom --version
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

OS: OSX El Capitain.

```

**Comment by 50Wliu** [comment]
Are you sure you aren't `cmd`-clicking on other lines by accident?  That creates an extra cursor.

**Comment by itinance** [comment]
Argh... what a feature ;) i guess you're right
