### ISSUE TITLE
Auto indent on paste doesn't work

### ISSUE THREAD

**Issue by sandrodz** [atom/atom#11752]
### Description

I'm trying to move away from Sublime 3 to Atom. There are some things that irritate me, and I wonder if there is a fix or package for this:

I've "auto indent on paste" checked.

pasted content has tab indent, I expect 'auto indent on paste' option to align pasted html to file indentation rules...

thoughts?

![13221417_10156991829645613_3419166243758827520_o](https://cloud.githubusercontent.com/assets/8479569/15266849/664cbc36-19c2-11e6-95e4-120e098272dc.jpg)
### Steps to Reproduce
1. Open file with spaces indent
2. Make sure "auto indent on paste" is checked
3. Paste in content with tab indentation

**Expected behavior:** pasted content is auto indented to spaces

**Actual behavior:** pasted content remains tabbed.
### Versions

OSX 10.11.4

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4

**Comment by tjkohli** [comment]
This is still an issue.

**Comment by clayteller** [comment]
Auto indent on paste has never seemed to work for me. I have it turned on in my settings. It's a first-world problem I know, but it would be nice to paste a snippet of code into my file and have it automatically follow the indent pattern established in the file I'm pasting into. I always have to highlight the snippet after I've pasted it and command it to 'auto indent'…and then that usually works.  I can't find a plugin to fix the issue either.

**Comment by tjkohli** [comment]
The only way it works for me is if I create the new line manually, delete the existing indents, and then paste. Then it seems to work fine. How is this even an issue?

**Comment by clayteller** [comment]
It would be great to know if it works for some people or if it is the same for all.

**Comment by mryanb** [comment]
Agreed, this never seems to work correctly for me when I'm pasting in code from outside Atom.

Ex:
![image](https://user-images.githubusercontent.com/3656391/36063414-276d77be-0e42-11e8-8451-1076ce2526cb.png)

**Comment by oschade** [comment]
It's so annoying, that additional lines are not indented. Could you please fix this!

**Comment by clayteller** [comment]
@concAPPtLab thanks, I just installed "fix-indent-on-paste" package and so far so good.
