### ISSUE TITLE
Atom BSOD while trying to search a package/theme

### ISSUE THREAD

**Issue by omicronkappa** [atom/atom#11753]
### Description
I was searching for config-import-export package when suddenly after hitting enter I got a Blue Screen of Death, after restart , Atom opened in Chrome Developer Tools, so I didn't looked after this bug, here on issues...
After this what I did was to uninstall and re-install Atom. After that I tried to search again other package and got again a BSOD....

### Steps to Reproduce
1. Search a package/theme 
2. Enter
3. BSOD :)

### Versions
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
OS:  Windows 10 64 bits

![photo_2016-05-14_22-32-21](https://cloud.githubusercontent.com/assets/12105295/15270783/cd7ee0ee-1a23-11e6-81cb-4dca80072166.jpg)

![photo_2016-05-14_22-28-44](https://cloud.githubusercontent.com/assets/12105295/15270772/44489dba-1a23-11e6-9cc0-322a0dc6f1c3.jpg)

**Comment by paulcbetts** [comment]
This means your network card did something problematic, update your drivers. Atom is just the victim in this problem, not the culprit

**Comment by omicronkappa** [comment]
I didn't have this problem before while installing packages but today occurred... ~
Thanks for replying!

**Comment by bdjidi** [comment]
Same thing persistent NETIO.SYS BSOD when trying to access packages.
