### ISSUE TITLE
Force Touch support

### ISSUE THREAD

**Issue by Bouzmine** [atom/atom#11776]
[Link to Force Touch's Wikipedia article](https://en.wikipedia.org/wiki/Force_Touch)
### Description

I'd like to be able to use a Force Touch trackpad to perform some tasks. There could be default ones.

Default actions : 
- Force Click : Go to declaration
- Force Click : Rename in tree-view (would mimic Finder's behavior)
- Force Click : On the gutter to insert a bookmark
- Force Feedback : On end of scrolling (at bottom and top of a file)
- Force Feedback : When moving a tab in the tabs-bar (feedback when the placeholder line moves)

After, an API could be made available to package developers to allow things like : 
- Force Click :  On the minimap to open another split tab of the same file at that place
- etc.

**Expected behavior:** Have an immersive Force Touch experience

**Actual behavior:** No Force Touch support
### Versions

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by Nikki1993** [comment]
I think this issue should be filed against electron not atom, if electron doesn't have force touch API, I don't think atom editor can solve the issue. 

@50Wliu

**Comment by mnquintana** [comment]
This would be a cool touch (pun not intended! 😇 ), but it would definitely require a change in Electron, and that's going to be a ways off – not even Chrome supports Force Touch yet.

**Comment by ProLoser** [comment]
I would be interested in force touch selecting the entire word (and highlighting other instances) instead of just placing the cursor.

**Comment by DerZyklop** [comment]
What version of Atom you reproduced the issue on
atom @ 1.35

What OS and version you reproduced the issue on
osx @ 10.14

What steps you followed to reproduce the issue
Force-Click > Nothing happens.

;)
