### ISSUE TITLE
Crash and not able to run it anymore....

### ISSUE THREAD

**Issue by gabycperezdias** [atom/atom#11778]
![ss_atom](https://cloud.githubusercontent.com/assets/6580266/15329233/549fb452-1c2e-11e6-9641-4dbfbaed3f2c.png)

The editor crashed from nowhere, and now I can't open it anymore.... I don't want to re-install the basic packages and run for my gist to import everything, can I delete some file to be able to run the editor again? Yes, I need to run it on Windows, yes, I already tried to restart it. 

Thanks,

**Comment by gabycperezdias** [comment]
The "keep it open" option, keeps a whit screen, useless open

The "reload" option takes me to the same screen again in an endless loop

**Comment by Nikki1993** [comment]
@gabycperezdias have you tried running atom in safe mode see if it works? Launch terminal and paste 
`atom --safe`

**Comment by 50Wliu** [comment]
@gabycperezdias In the future, please follow the issue template when creating issues.

You may also want to try `atom --clear-window-state --safe` if @Nikki1993's command doesn't work for you, and that still doesn't help try renaming `%USERPROFILE%\.atom` to something like `%USERPROFILE%\.atom-backup`.

**Comment by gabycperezdias** [comment]
I can't run atom from terminal and I can't find the binary file to put in the PATH on windows to run it, I tried to rename the folder as suggested, the editor ran, but I would need to do all the config again... I tried to copy in parts, to see what I could get from the previous version, I put the packages and some config files and it seems to be working, I will need to reconfigure most part but... I can work at least

**Comment by gabycperezdias** [comment]
If I copy the "packages" folder... that has only one file with the initial paths (all of them exists, I already check), the application starts to crash again...

**Comment by 50Wliu** [comment]
Ok, that indicates that one of your installed packages is causing this issue.  Your best bet would be to move one package over at a time to figure which one it is, but that's the best advice I can give you :/.

**Comment by gabycperezdias** [comment]
Sorry, I sad it wrong, the folder that crashes is the "storage" one not the "packages", inside this folder there's only one file application.json and inside it only an array with 3 paths for the folder I have opened.

**Comment by gabycperezdias** [comment]
@50Wliu Do you think could still be a broken package?

**Comment by 50Wliu** [comment]
Then something went wrong with deserialization most likely.  If you want you can email the contents of the storage folder to atom@github.com so that they can take a look at it.

**Comment by gabycperezdias** [comment]
I was able to identify which project is broken, but its a big folder to send by email... There's a log file where I could see which file exactly is broken the program?

**Comment by 50Wliu** [comment]
Hmm, that's true.  Can you upload the most recent `.dmp` file from `%TEMP%\Atom Crashes` instead?  You'll have to compress it inside a `.zip` file in order for GitHub to accept it.

**Comment by gabycperezdias** [comment]
This is the most recent .dmp file as required, I had to change the .dmp to .txt because even compressing as zip github doesn't allow me to upload the file, but I think it will be easy to change to .dmp again... just changing the extension name...

[5164883f-bcee-408d-af0c-8078aa0bbbaa.txt](https://github.com/atom/atom/files/271692/5164883f-bcee-408d-af0c-8078aa0bbbaa.txt)

**Comment by gabycperezdias** [comment]
@50Wliu I (think) I found the problem... Through atom I was able to create a folder named "aux", but apparentely it's a reserved word in DOS, and when I closed the editor maybe the OS blocked and gives some errors...

**Comment by pepjo** [comment]
I had the same problem when creating a folder named "aux"! Spent the whole day on it :disappointed:
