### ISSUE TITLE
Module version mismatch when using apm or installing/fetching packages

### ISSUE THREAD

**Issue by tpoisot** [atom/atom#11775]
### Description

I am unable to update or install packages or themes using either `apm` or the atom interface.

Specifically, I get the following error:

~~~
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
~~~

### Steps to Reproduce

1. Open atom
2. Go to *Settings View: Install Packages and Themes*
3. Look on my works, ye Mighty, and despair!

![capture d ecran de 2016-05-17 11-01-17](https://cloud.githubusercontent.com/assets/579329/15327227/b361aa3c-1c1e-11e6-8bfe-33b4fec96e89.png)

### Versions

**OS**

Fedora 24 beta, `4.5.4-300.fc24.x86_64`

Output of `atom --version`

~~~
Atom    : 1.7.3
Electron: 0.37.7
Chrome  : 49.0.2623.75
Node    : 5.10.0
~~~

Output of `apm --version` give the same error.

I install atom from the `mosquito/atom` copr repo @ [https://copr.fedorainfracloud.org/coprs/mosquito/atom/]

**Comment by 50Wliu** [comment]
@tpoisot Does the same error occur if you install Atom manually using the `.rpm` package provided at https://github.com/atom/atom/releases/tag/v1.7.3?

**Comment by tpoisot** [comment]
@50Wliu no it doesn't. Seems to suggest that there is an issue with the bundled nodejs-* packages that installing from copr installs. Closing, sorry for the noise.

**Comment by fabiomontefuscolo** [comment]
I had this problem too, and after read this thread I updated nodejs and npm and problem solved.

**Comment by Sneha-Watharkar** [comment]
I  am facing the same issue. I am running on 
Node:   v8.9.4
Npm:    v5.6.0
Any solutions?
