### ISSUE TITLE
ctrl-alt-cmd-up shortcut not working

### ISSUE THREAD

**Issue by PierBover** [atom/atom#11777]
I'm setting up a new machine from scratch with OSX 10.11.5 and Atom 1.7.3. This happens in safe mode too.

For some reason using `ctrl-alt-cmd-up` doesn't work.

```
'atom-text-editor:not([mini])':
  'ctrl-alt-cmd-up': 'editor:delete-line'
```

I've tried using the shortcut with other functions and it doesn't work either.

```
'atom-workspace atom-text-editor:not([mini])': 
  'ctrl-alt-cmd-up': 'editor:duplicate-lines'
```

If I change to `ctrl-alt-cmd-down` it does work so it may seem like a problem with the key combination.

This used to work... Since this is a fresh machine I don't know whether it's an Atom problem or an OSX one or a combination.

**Comment by amytruong** [comment]
Hiya! I'm on 1.7.4 and it worked fine for me. Do you want to try upgrading?

**Comment by PierBover** [comment]
Hey @amytruong are you on 10.11.5 ?

I've updated to 1.7.4 and neither of these commands work now...

```
'atom-text-editor:not([mini])':
  'ctrl-alt-cmd-up': 'editor:delete-line'

'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-cmd-down': 'editor:duplicate-lines'
```

**Comment by amytruong** [comment]
@PierBover I'm actually on 10.10 still and was just going to wonder if that's the difference...hmm.

**Comment by PierBover** [comment]
This used to work before. Even on 10.11.3 or 10.11.2 (not sure).
