### ISSUE TITLE
Attach MSI installer during build

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#11771]
In https://github.com/atom/atom/pull/11734/files I added the .msi filename to the list of build assets for windows, but the draft release that was created when I ran CI didn't have any Windows assets. Does anyone else on @atom/core that has worked with the build more than I have know what's missing here?

cc @damieng

**Comment by thedaniel** [comment]
It looks like the .msi isn't actually getting built on appveyor on master.

**Comment by damieng** [comment]
https://github.com/atom/atom/pull/11791 addresses that.
