### ISSUE TITLE
Unable to paste text copied with xsel, when it contains over 4000 chars

### ISSUE THREAD

**Issue by marjakm** [atom/atom#11779]
### Description

xsel is a command-line tool to access X clipboard and selection buffers in linux. Things copied with it up to 4000 chars are pasted in atom fine (printf "%04000d" 0 | xsel -ib), but over that it freezes atom (but not sublime or mousepad ..).

xclip is another such terminal clipboard program. Atom can paste things copied with it without a size limit, these commands work:
```
 printf "%04001d" 0 | xclip -selection clipboard -i
 printf "%08001d" 0 | xclip -selection clipboard -i
 printf "%080001d" 0 | xclip -selection clipboard -i
```

### Steps to Reproduce

1. printf "%04001d" 0 | xsel -ib
2. atom --safe .
3. open new tab and paste
4. editor freezes for 30s, popup "Editor is not responding" opens
    1. select keep waiting -> editor unfreezes, no text pasted
    2. select close -> atom closes, output in terminal:
```
/usr/bin/atom: line 98: 29057 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
App load time: 372ms
Failed to get crash dump id.
Report Id: 
```

### Versions

`--> atom --version
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

`--> apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11+
git 2.7.4

`--> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

`--> uname -a
Linux . 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

`--> dpkg -l xsel
ii  xsel                         1.2.0-2             amd64               command-line tool to access X clipboard and selection buffers

`--> dpkg -l xclip
ii  xclip                        0.12+svn84-4  amd64               command line interface to X selections

**Comment by marjakm** [comment]
Actually the command
` printf "%080001d" 0 | xclip -selection clipboard -i`
does not work, but it freezes after the text has appeared

**Comment by drewmnoel** [comment]
Can confirm, it segfaults. [Here's the coredump](https://gist.github.com/drewmnoel/25820018d1a1c2a622849114c329df6f). Running on Arch.

```
$ atom --version
Atom    : 1.9.0-dev-7253514
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.2
```

From the coredump

**Comment by lee-dohm** [comment]
According to https://github.com/electron/electron/issues/3116 this is caused by a bug in the xsel program and is out of the control of Atom and Electron.
