### ISSUE TITLE
Atom needs to handle large files better.

### ISSUE THREAD

**Issue by vjancik** [atom/atom#11788]
When you open a large file in Atom, the whole editor freezes up while it loads the whole file.

This is neither desirable or acceptable. Can't it just load a portion of the file? Like the head or something.

And for 1 infinite line files (generated files), set a line length limit. Then as the user scrolls, read more data and display it.

**Comment by hultberg** [comment]
Do you see the same behaviour when running atom with safe mode? `atom --safe`

**Comment by lee-dohm** [comment]
There are Issues open already on handling large files better. You may want to search for them to subscribe to the relevant Issues.
