### ISSUE TITLE
Mixing Arabic characters and curly brackets confuses LTR/RTL and closing bracket position & direction

### ISSUE THREAD

**Issue by vkatsikaros** [atom/atom#11783]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When arabic characters are between curly brackets the left to right order is getting confused.

### Steps to Reproduce

1. Write the sample text or load a file with the sample text:
```
\textarabic{ مال \lala{ما ل}  }
```

2. Put cursor between `}  }`
3. Start writing arabic characters. For example I start writing `قا `

**Expected behavior:** 
I would expect to see
```
\textarabic{ مال \lala{ما ل}  قا }
```
or (gimp manipulated image)
![how_it_should_look_like](https://cloud.githubusercontent.com/assets/1138992/15367152/6f3614ac-1d30-11e6-8013-e00dc3d73ee1.png)

**Actual behavior:**

![animation](https://cloud.githubusercontent.com/assets/1138992/15367183/8ac1bc08-1d30-11e6-8f77-078b66ab1c10.gif)

### Versions

```
$ atom --version
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1

~/.atom/packages $ apm links
/home/vag/.atom/dev/packages (0)
└── (no links)
/home/vag/.atom/packages (0)
└── (no links)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

**Comment by Zireael07** [comment]
100% certain it's a duplicate.

**Comment by 50Wliu** [comment]
Thanks @Zireael07.
