### ISSUE TITLE
Wrong line and cursor position with block decoration

### ISSUE THREAD

**Issue by abe33** [atom/atom#11796]
While playing with block decorations I noticed that on master the cursor is wrongly positionned when on a line with a block decoration:

![block-decoration](https://cloud.githubusercontent.com/assets/247140/15425757/c8f10adc-1e8a-11e6-8b1b-f2b6316932f1.gif)

To reproduce you can use that snippet in your `init.coffee` file, it creates five block decorations randomly at the top of a file through the `editor:test-block-decorations` command:  

```coffee
blockDecorations = []

clearBlockDecorations = ->
  blockDecorations.forEach (d) -> d.destroy()
  blockDecorations.length = 0

atom.commands.add 'atom-workspace',
  'editor:clear-block-decorations': clearBlockDecorations
  'editor:test-block-decorations': ->
    e = atom.workspace.getActiveTextEditor()
    b = 0

    for i in [0..4]
      b += Math.round(Math.random() * 300)
      start = b
      b += Math.round(Math.random() * 300)
      end = b

      startPos = e.buffer.positionForCharacterIndex(start)
      endPos = e.buffer.positionForCharacterIndex(end)

      marker = e.markBufferRange([startPos, endPos], persistent: false,   invalidate: 'touch')

      props =
        type: 'block'
        item: document.createElement('div')

      props.item.textContent = "Decoration #{i}"
      props.item.style.cssText = 'background: red; width: 100%; height: 50px;'

      blockDecorations.push e.decorateMarker(marker, props)
```

```shell
$ atom --version
Atom    : 1.9.0-dev-8f1a691
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Comment by as-cii** [comment]
This seems to be a problem with not specifying `{position: 'before'}` or `{position: 'after'}`. I am working on a fix right now, but you can circumvent this issue by using an explicit `position` parameter.

Thanks for the report, @abe33! ✨
