### ISSUE TITLE
Can't install Script Pckage on Atom

### ISSUE THREAD

**Issue by janoop** [atom/atom#11798]
### Description
I had installed latest version of atom text editor but can't install Script Package in it.

### Steps to Reproduce

1. sudo apm install script

**Expected behavior:** Successfully Install

**Actual behavior:**
```
Installing script to /home/nobodyu/.atom/packages ✗

npm ERR! tar.unpack error reading /tmp/d-116420-6488-v8x98x/package.tgz
npm ERR! addLocal Could not install /tmp/d-116420-6488-v8x98x/package.tgz
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/nobodyu/.atom/.apm/.apmrc" "--userconfig" "/home/nobodyu/.atom/.apmrc" "install" "/tmp/d-116420-6488-v8x98x/package.tgz" "--target=0.36.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3

npm ERR! 0-byte tarball
npm ERR! Please run `npm cache clean`
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116420-6488-1ik6grb/npm-debug.log
```

### Versions

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by Nikki1993** [comment]
@janoop have you tried running `npm cache clean` as ERR message suggests and then trying to install the script?

**Comment by janoop** [comment]
yes but that makes no difference

**Comment by Nikki1993** [comment]
Why are you using root to install the script in the home directory btw? Have you tried running 

`apm install script` ?

**Comment by janoop** [comment]
yes but it gives same error

**Comment by Nikki1993** [comment]
Alright, since you tried installing apm package with sudo, try running `sudo npm cache clean ` Also, clean cache folders in your atom editor. `~/.atom/.apm (and ~/.atom/.npm)` are download cache folders. Based on [this info ](https://discuss.atom.io/t/apm-manually-having-to-clean-up-the-packages-folder/21359) it's safe to delete what's inside those folders since it's package caches. Try clearing out those and then try installing package through atom editor again. 

**make sure you quit atom editor before clearing folders.**

**Comment by janoop** [comment]
Cool it worked thanks. Nikki1993,
so what i did is `sudo npm cache clean`
and then deleted all folders from `~/.atom/.apm`
and there was no directory named `.npm` so i created it and the 
executed the command `sudo apm install script`
and this time output is `Installing script to /home/nobodyu/.atom/packages ✓
 `

Thanks Once Again

**Comment by lauyader** [comment]
Hay que reinstalar Atom
