### ISSUE TITLE
Unable to modify files owned by root in mac like it used to be able to

### ISSUE THREAD

**Issue by billgao0807** [atom/atom#11794]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When I want to modify any file owned by root, in my case an Apache conf file, atom says permission denied instead show a popup for credentials like it used to to before.

### Steps to Reproduce

1. Open a file owned by root
2. Try to modify
3. Try to save

**Expected behavior:** [What you expected to happen]
A popup asking for credential
**Actual behavior:** [What actually happened]
An alert saying permission denied
### Versions
Mac os 10.11.4-5
Atom mac 1.7.3
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.4
You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by lee-dohm** [comment]
Was able to reproduce using Atom v1.7.4 on Mac OS X 10.11.5. @kuychaco was this affected by your recent changes?

**Comment by kuychaco** [comment]
@lee-dohm The changes I made in https://github.com/atom/atom/pull/11478 are only on 1.9-dev. I tried to reproduce this bug on 1.9.0-dev-405f28f and got the expected behavior. So whatever the bug is, perhaps it's fixed on master?

**Comment by lee-dohm** [comment]
Thanks @kuychaco! I'll double-check on `master`.

**Comment by lee-dohm** [comment]
I was able to reproduce the problem using Atom v1.9.0-dev-2cfc4ee on Mac OS X 10.11.5. Here's what I did:

1. Launch Atom from the terminal using `atom /etc/profile`
1. Navigate to the end of the file using <kbd>Cmd+Down</kbd>
1. Add an extra newline at the end of the file with <kbd>Enter</kbd>
1. Save the file with <kbd>Cmd+S</kbd>

**Expected:** Dialog asking for permission elevation
**Actual:** Permission denied notification

**Comment by kuychaco** [comment]
@lee-dohm hmm interesting. I just built the same version of dev (2cfc4ee), followed your repro steps and got the expected dialog asking for my password...

**Comment by lee-dohm** [comment]
I found the bug. Here's what I found:

1. Launch Atom
1. Open Settings View with <kbd>Cmd+,</kbd>
1. Ensure "Back Up Before Saving" is **disabled**
1. Close Atom
1. Launch Atom with `atom --safe /etc/profile`
1. Type `# testtesttest` and press <kbd>Enter</kbd> on the first line of the file
1. Save the file with <kbd>Cmd+S</kbd>

**Expected and Actual:** Dialog comes up asking for elevation

But then if you:

1. Launch Atom
1. Open Settings View with <kbd>Cmd+,</kbd>
1. Ensure "Back Up Before Saving" is **enabled**
1. Close Atom
1. Launch Atom with `atom --safe /etc/profile`
1. Type `# testtesttest` and press <kbd>Enter</kbd> on the first line of the file
1. Save the file with <kbd>Cmd+S</kbd>

**Expected:** Dialog comes up asking for elevation
**Actual:** Permission denied notification

Confirmed using Atom v1.9.0-dev-2cfc4ee on Mac OS X 10.11.5.

**Comment by kuychaco** [comment]
Looked into this with @lee-dohm and @BinaryMuse. We've identified the problem but a thorough solution has yet to be fleshed out. 

When "Back Up Before Saving" is enabled an error is thrown while the backup file is being created, before the actual save takes place. See [`TextBuffer::backUpFileContentsBeforeWriting`](https://github.com/atom/text-buffer/blob/master/src/text-buffer.coffee#L1417-L1419)

A solution could involve wrapping the code in a try/catch similar to [`File::writeFileWithPrivilegeEscalationSync`](https://github.com/atom/node-pathwatcher/blob/master/src/file.coffee#L351-L362).

Thoughts @atom/core, and specifically @as-cii - this seems to be up your alley given the work you're doing with file system operations so perhaps it's something you can tackle as part of that?

**Comment by as-cii** [comment]
Thanks @kuychaco, @lee-dohm and @BinaryMuse for the investigation. Awesome work here! 👏 

This definitely seems to be a problem with backup files not handling privilege escalation correctly. It's tricky because I am not sure backup files are the right way of solving the data loss problem, and it feels like we could move away from them after/if #11828 lands. Still, it's probably sensible to make them work even if we'll end up deprecating them at some point.

I'll take care of it and submit a pull-request in [atom/text-buffer](https://github.com/atom/text-buffer) shortly. 👍

**Comment by jaychow** [comment]
This issue is appearing again, after updating to v 1.19.0 when I try to edit any file in /etc/ I get the permission error message. After downgrading to v 1.18.0 I was able to get the promot to enter password for elevated privileges

**Comment by lee-dohm** [comment]
@jaychow I've opened a new issue at #15267. You may want to subscribe there for updates.

**Comment by pablocrs** [comment]
Was using atom to manage my host file for many months, and past week started getting this error message 'Unable to save file: Permission denied '/private/etc/hosts'' instead of asking me for credentials.

**Comment by Ben3eeE** [comment]
@pablocrs There is a new issue open for this https://github.com/atom/atom/issues/15267. You may want to subscribe there for updates.
