### ISSUE TITLE
application:new-file does not work

### ISSUE THREAD

**Issue by cristian-sima** [atom/atom#11800]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I tries in different modes to hit CTRL + N or from the menu and it does not work.

It does not work for a few days.

### Steps to Reproduce

1. Open Atom
2. Hit CTRL + N

Or...

1. Open Atom
2. Hit ALT (to show the top menu)
3. Click File
4. Click `New File`

**Expected behavior:**  to create an empty tab/file

**Actual behavior:** nothing :))

### Versions

![image](https://cloud.githubusercontent.com/assets/12199042/15435617/092aff8c-1ec6-11e6-99ef-43badd530c3a.png)

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by cristian-sima** [comment]
It worsks now with 1.7.4
