### ISSUE TITLE
remote-edit issue

### ISSUE THREAD

**Issue by stemd** [atom/atom#11809]
Hi! There is an issue of remote-edit atom plugin which is described in detail here:
https://github.com/sveale/remote-edit/issues/169

(issue exist from atom v1.5 onwards, more users confirmed issue on more platforms).

As developer of plugin is unresponsive, I ask here for help, and humbly share my limited insight:

My CoffeeScript debugging skills suck, but I got following:

1. "Cannot read property 'alias' of undefined" is referencing following line (in file host.coffee):
`toReturn = "#{toReturn} #{@alias}" if searchKeySettings["alias"]`
which means that searchKeySettings object (probably hashtable) is undefined.

2. This object is initialized with this line:
```
atom.config.observe "remote-edit.filterHostsUsing", (settings) =>
@searchKey = @getSearchKey(settings) ? @searchKey
```
In JS notation:
```
atom.config.observe("remote-edit.filterHostsUsing", (function(_this) {
return function(settings) {
var ref;
return _this.searchKey = (ref = _this.getSearchKey(settings)) != null ? ref : _this.searchKey;
};
```
- Either atom.config.observe is broken or called to early or something similar.

Any idea what need to be fixed? TIA

**Comment by lee-dohm** [comment]
To be honest, I'm not sure what is going wrong with this package. To my understanding, we don't have any bug reports on `atom.config.observe`, so it is most likely that it is functioning properly.

[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For package development questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
