### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'transaction' of null

### ISSUE THREAD

**Issue by Trudko** [atom/atom#11806]
Hi everyone, I am getting this error in dev console for quite some time. Doesn't seem to cause other problem but it's bit annoying. I did tried it in safe mode on latest Atom.

```
Uncaught (in promise) TypeError: Cannot read property 'transaction' of null(…)dbPromise.then.db @ /opt/atom/resources/app.asar/src/state-store.js:31
```
### Steps to Reproduce
1. Open atom --safe and check console

**Expected behavior:** [What you expected to happen]
No error in console.

**Actual behavior:** [What actually happened]
Error in console.
### Versions

Did happen for longer time right now using 1.7.3
Elementary OS Freya (based on Ubuntu 14.04LTS)

**Comment by 50Wliu** [comment]
Ok, and does this happen with every project or just a specific one?

**Comment by Trudko** [comment]
Seems to happen to every project I tried so far. Also I've noticed an error  
```
Could not connect to indexedDB
 Eventbubbles: true
cancelBubble: false
cancelable: true
currentTarget: null
defaultPrevented: false
eventPhase: 0
isTrusted: true
isTrusted: true
path: Array[0]
returnValue: true
srcElement: IDBOpen
DBRequesttarget: IDBOpen
DBRequesttimeStamp: 1464072584123
type: "error"
__proto__: Event
dbOpenRequest.onerror @ /opt/atom/resources/app.asar/src/state-store.js:16
 ```

**Comment by as-cii** [comment]
Thanks for the report, @Trudko! 🙇 

We've seen this problem a couple of times now and it seems like, for some reason, the underlying database gets corrupted. Some other user experienced this after installing beta side by side to Atom stable, so I wonder if this is what's happening in this case too. @Trudko: have you (ever) installed beta alongside stable? If so, we need to address beta installation to prevent this issue from happening again (maybe by providing a different database path for the different kinds of installations).

As a workaround, does opening Atom with the `--clear-state-store` argument fix the issue? If it doesn't, can you try deleting the `/Users/<your user>/Library/Application Support/Atom/IndexedDB` folder and re-open Atom again? (this path might be different in case you're not using OS X)

Thanks again! ✨

**Comment by Trudko** [comment]
Hi @as-cii  :bow: 

--clear-state-store (with or without --safe) didn't work but deleting ~/.config/Atom/IndexedDB seem to fixed the issue although I still have an error Could not connect to indexedDB. Btw I did't installed beta ever.

Thank you for your time and support!

**Comment by capaj** [comment]
I enabled "Capture async stack traces" in the atom debug panel and got the whole stack trace:

```
/usr/share/atom/resources/app.asar/src/state-store.js:31 Uncaught (in promise) TypeError: Cannot read property 'transaction' of null(…)dbPromise.then.db @ /usr/share/atom/resources/app.asar/src/state-store.js:31Promise.resolve (async)Promise @ /usr/share/atom/resources/app.asar/src/state-store.js:28save @ /usr/share/atom/resources/app.asar/src/state-store.js:27(anonymous function) @ /usr/share/atom/resources/app.asar/src/atom-environment.js:990module.exports.AtomEnvironment.saveState @ /usr/share/atom/resources/app.asar/src/atom-environment.js:983(anonymous function) @ /usr/share/atom/resources/app.asar/src/atom-environment.js:309
```

For me this fires exactly 2 seconds after I click on something in editor(I have hyperclick with js-hyperclick). This is certainly not an issue with js-hyperclick or hyperclick, because these two plugins run fine on my other machine.

Will try deleting my indexedDB folder.

**Comment by viddo** [comment]
> We've seen this problem a couple of times now and it seems like, for some reason, the underlying database gets corrupted. Some other user experienced this after installing beta and stable side by side, so I wonder if this is what's happening in this case too.
> …Have you (ever) installed beta alongside stable? If so, we should probably start using a different database path for the different kinds of installations.

> As a workaround, does opening Atom with the --clear-state-store argument fix the issue?  If it doesn't, can you try deleting the /Users/<your user>/Library/Application Support/Atom/IndexedDB folder and re-open Atom again?

@as-cii, I'm using beta alongside with stable, I also started to experience this problem lately (currently using v1.9.9 and v10.10.0-beta7 on MacOSX 10.10.5 Yosemite).

Neither `--clear-state-store` nor deleting the IndexedDB folder works, it solves the problem for the first app restarted, but appears again in the second app (reproducible for both stable and beta started last).

Btw, the first exception thrown prior to the reported exception here is a _Could not connect to indexedDB_ error, which was also reported in #11254

**Comment by viddo** [comment]
I've found a workaround, by starting the Atom-beta app with it's own user-data dir:
`open 'Atom Beta.app' --args my/project/dir --user-data-dir ~/Library/Application\ Support/AtomBeta`
