### ISSUE TITLE
Atom command line opens up a Windows shell in Git Bash.

### ISSUE THREAD

**Issue by webspecnick** [atom/atom#11817]
### Description

The atom command line no longer opens files in the editor in Windows 10. Instead it opens up a type of shell and expects input. This happens in Git Bash but not `cmd`. It's happening on multiple Windows 10 machines around the office.

### Steps to Reproduce

1. Open up Git Bash on Windows
2. Cd to a folder you want to open in atom
3. Run `atom .` or `atom foldernamehere` to open up a folder

**Expected behavior:**
Atom will open up a new window with the folder added as a project folder

**Actual behavior:**
A type of shell opens up and expects input from the user. See screenshot.
![atom-command-line](https://cloud.githubusercontent.com/assets/6545164/15471686/dd6205c8-20bc-11e6-9aee-8c5e93775901.PNG)

### Versions
Atom 1.7.4
Windows 10
Git Bash 2.8.3 MINGW64

### Workarounds
These workarounds may or may not work depending on your bash versions.

**Running atom.cmd**
Running `atom.cmd .` will produce the expected behavior. (@mikew)

**Aliasing atom.cmd**
Add an alias in your .bashrc `alias atom='atom.cmd'` (@DGempler)

**Comment by mikew** [comment]
Just started happening here today too

Atom 1.7.4
Windows 10
Git Bash 2.8.2

**Comment by ethanclevenger91** [comment]
Can confirm as well

Atom 1.7.4
Windows 10
Git Bash 2.7.2

**Comment by uncleramsay** [comment]
Happening on Windows 7 too.

Atom 1.7.4
Windows 7
Git Bash 2.8.2

**Comment by sanori** [comment]
I have got same situation
Atom 1.7.4
Windows 8.1
Git bash 2.8.2, 2.8.3

I guess `atom .` works on atom 1.7.3 because I alway use the command.
`atom .` works on Git cmd, windows command line.

---

> Running `atom.cmd .` works as a workaround

Thanks @mikew . It works in my case.

**Comment by 50Wliu** [comment]
@damieng :scream:

**Comment by damieng** [comment]
Yeah, looks like more subtle differences between the various flavors and versions of Bash on Windows. Sigh.

**Comment by damieng** [comment]
So it seems MSYS variants want //C on line 11 and one backslash on line 3.

Cygwin wants /C on line 11, double-backslash on line 3...

**Comment by damieng** [comment]
I have a workaround for the path from cygpath ending or not ending with a backslash between different flavors.

Not seeing a single method that's going to handle the /C however.  Open to any suggestions that are better than hard-coding `uname -a` signature based logic.

**Comment by damieng** [comment]
Apparently MSYS helpfully 'detects' /C everywhere and maps it to the C: drive path. This is what is causing cmd.exe to open an Window and not actually run the command on Git Bash.

**Comment by DGempler** [comment]
Using @mikew 's suggestion, a temporary solution would be to add 
alias atom='atom.cmd'
to your .bashrc or aliases file.

**Comment by damieng** [comment]
Some of the older bash shells won't actually run atom.cnd directly without
going via cmd.exe

**Comment by jerrywardlow** [comment]
Thanks for the quick fix @DGempler! This bug was driving me nuts, it's hard to change such an ingrained habit.

**Comment by damieng** [comment]
Fix went out in 1.8 and 1.9 beta.

**Comment by prijindal** [comment]
Problem Still Persists
Atom: 1.8.0
Windows 10
Git bash 2.8.4

**Comment by damieng** [comment]
Yes, it looks like the fix didn't make the 1.8 branch.

Can you copy the contents of https://github.com/atom/atom/blob/dc6388323c55a577669eb92fcef5131477d34aad/resources/win/atom.sh into your atom.sh in resources/cli and see if that works for you?

**Comment by sanori** [comment]
It seems that `resources/cli/atom.sh` of `app-1.7.4` and `app-1.8.0` are the same.
After changing atom.sh as @damieng 's, `atom .` works in my case
Windows 8.1
Git bash 2.8.3

**Comment by prijindal** [comment]
Fix provided by @damieng works +1

**Comment by finalcut** [comment]
using windows 10, atom 1.8 and using the provided update works for me as well.

I was a little confused on what file to update at first because of the path of the file to update in git isn't the same as the installed path.

For others similarly confused update

**/c/users/{{YourAccount}}/AppData/Local/atom/app-1.8.0/resources/cli/atom.sh**

I then closed all instances of atom and git bash (had to use the task manager to kill a git for windows task as well) then started git bash and atom worked from the command line again.

**Comment by giresse19** [comment]
Am having a problem opening Atom from Git bash on windows 7.
Windows 7
Atom 1.8.0
Git bash 2.9.0

**Comment by giresse19** [comment]
@ ^ any help please!

**Comment by damieng** [comment]
@giresse19 The answer is right there above.  Copy the atom.sh from https://raw.githubusercontent.com/atom/atom/dc6388323c55a577669eb92fcef5131477d34aad/resources/win/atom.sh and replace the contents of /c/users/{{YourAccount}}/AppData/Local/atom/app-1.8.0/resources/cli/atom.sh with it.

**Comment by giresse19** [comment]
@damieng Thanks but am still having some probs and will be grateful if u help out:
After typing: cp dir Desktop/file1/filetocpy.txt(location of the item to copy,i.e the link u send to me )  dir  c:/users/kasutaja/AppData/Local/atom/app-1.8.0/resources/cli/atom.sh.
i get the RESULT: cp: target 'app-1.8.0/resources/cli/atom.sh' is not a directory.
QUESTION: did I type in a wrong command on the Git bash, if yes, what should use?
Thanks in advance!

**Comment by giresse19** [comment]
^what should I use**?

**Comment by damieng** [comment]
Try this from a PowerShell command line;

```invoke-webrequest https://raw.githubusercontent.com/atom/atom/master/resources/win/atom.sh -OutFile $env:LocalAppData\atom\app-1.8.0\resources\cli\atom.sh```

**Comment by damieng** [comment]
Can you paste the contents of your atom.sh here?
