### ISSUE TITLE
ctrl+shift+d does not duplicate the line

### ISSUE THREAD

**Issue by GradyD** [atom/atom#11818]
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)? Yes
- [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? Yes, 1.7.4 on windows 7
- [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? Yes, still having issues
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)? Yes
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? I believe so
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported? Yes, did not find anything

When I press `ctrl+shift+d` to try to duplicate a line it never duplicates. If I open the command pallet and run 'Editor: Duplicate Lines' it works. Next to the command it shows the shortcut as being `ctrl+shift+d`

![image](https://cloud.githubusercontent.com/assets/994964/15472912/6bea07b0-20cb-11e6-829d-3e144ec22f9c.png)

I also checked my keymap.cson to make sure nothing was in there and nothing has been added. 
### Steps to Reproduce
1. Open Atom (normal or safe mode)
2. Type anything on a tab
3. Press `Ctrl+Shift+D`, the line does not duplicate for me

**Expected behavior:** The line to duplicate

**Actual behavior:** Nothing happens
### Versions

Confirmed on 1.7.3 and 1.7.4. I don't recall if it was happening before 1.7.3.

**Comment by Ben3eeE** [comment]
Did you also check the keybinding resolver to make sure there isn't a conflicting keybinding somehwere? You can open the keybinding resolver with `ctrl+.`

**Comment by GradyD** [comment]
Hey,

I just tried that and when I would press `ctrl+shift+d` it would only show 'ctrl+shift', like it never captured the 'd' key being pressed. When I try `ctrl+shift+F` it works and properly shows the binding. 

I also tried 'ctrl+d' and 'shift+d' and both showed up in the resolver.

**Comment by GradyD** [comment]
I had another engineer on my team test on his computer, windows 7, as well and it did not work for him either.

**Comment by lee-dohm** [comment]
Are you using a non-US English keyboard layout?

**Comment by GradyD** [comment]
No sir. Both of us are using American qwerty keyboards. Different brands mine is Logitech wireless and his is a machanical usb wired keyboard.

**Comment by lee-dohm** [comment]
> I just tried that and when I would press ctrl+shift+d it would only show 'ctrl+shift', like it never captured the 'd' key being pressed.

This indicates that something external to Atom is intercepting the <kbd>Ctrl+Shift+D</kbd> and preventing Atom from receiving it.

@damieng Can you reproduce this behavior? Or do you know what might be intercepting this key combination?

**Comment by damieng** [comment]
Hmm,  <kbd>Ctrl+Shift+D</kbd> here is duplicating a line. Running Windows 10 with a UK keyboard.

**Comment by 50Wliu** [comment]
Also can't reproduce here on Windows 10.  Atom 1.9.0-dev-720ad9c.

**Comment by amytruong** [comment]
I'm on Windows 8.1 and can't reproduce it either.

**Comment by GradyD** [comment]
Hmm ok. I'll go talk with my IT department and see if something has been installed that would hijack the command.

**Comment by GradyD** [comment]
I talked with my IT department and they are not aware of anything that would do this. 

I looked for ways to test my key events and found this, http://unixpapa.com/js/testkey.html

![image](https://cloud.githubusercontent.com/assets/994964/15505457/a946bfb0-2191-11e6-8e9f-6259793d815e.png)

It looks like my key events are going through correctly. Could this be isolated to windows 7? Is there anything I can do on my end to test this further or provide more data?

**Comment by Ben3eeE** [comment]
> Could this be isolated to windows 7?

I was unable to reproduce it with Atom 1.7.4 Windows 7 Swedish keyboard.

**Comment by 50Wliu** [comment]
That's odd.  @GradyD if you bind the duplicate lines command to another keybinding does it work then?

**Comment by GradyD** [comment]
Hey @50Wliu,

I tested some bindings this morning and came up with this,

```
'.platform-win32, .platform-win32 .command-palette atom-text-editor':
    'ctrl-shift-d': 'command-palette:toggle'
'.editor':
  'ctrl-shift-g': 'editor:duplicate-lines'
```

Pressing `ctrl-shift-d` does not toggle the command pallet but pressing `ctrl-shift-g` does duplicate the line. I also tried this with a capital 'D' but it did not make a difference.

**Comment by damieng** [comment]
When a shortcut fails for somebody on Windows but works for others on the same OS and keyboard layout it is usually another program running which has registered a system-level shortcut that grabs it before atom ever sees it.

You can see this for yourself if you switch on Keybinding Resolver from the Packages menu and hit the desired shortcut but it never shows.

I'd check to see what other programs you have running - normally ones in the system tray are the culprits and narrow it down.

Some examples so far are;

- <kbd>ctrl</kbd><kbd>alt</kbd><kbd>\ </kbd> for `tree-view:toggle` is taken by 1Password
- <kbd>ctrl</kbd><kbd>alt</kbd><kbd>cursors</kbd> taken by Intel Graphics Control Panel
- <kbd>ctrl</kbd><kbd>alt</kbd><kbd>function keys</kbd> taken by Intel Graphics Control Panel
- <kbd>ctrl</kbd><kbd>alt</kbd><kbd>cursors</kbd> taken by Intel Graphics Control Panel

Other apps that setup global hotkeys include ATI Catalyst Control Center (graphics driver), WMPKeys (Media player controller), MediaKeys, WinAmp etc.  Basically video driver tools and media players.

There is a tool that can confirm if a global hotkey is configured for a specific combo called [ActiveHotkeys](http://www.tranglos.com/activehotkeys/) but it is unable to tell you which app registered the hotkey (apparently the Windows API doesn't report it)

**Comment by DylanJCain** [comment]
Ctrl+Shift+D  working on windows 7 32-bit atom v.1.11.1 & v.1.12.6
also working on windows 10 64-bit atom v.1.11.1
