### ISSUE TITLE
Make search results and preferences panes behave more like other panes

### ISSUE THREAD

**Issue by phptools** [atom/atom#11819]
It would be nice if one could change font size in search results and preferences panes, just like one does in the other panes, eg. by using ctrl+mouse wheel; also, the same panes can't be scrolled with the keyboard.

**Comment by lee-dohm** [comment]
Most people appreciate being able to control the text editor font size and the UI font size separately, so we won't be making the change to allow scaling all font sizes with the Ctrl+Mouse Wheel change. The settings view is scrollable via the keyboard. If there is keyboard support that you would like in other packages, please open Issues on those packages with specifics as to what you expect.

Thanks for the feedback!
