### ISSUE TITLE
Markdown syntax colour issue while using /* .. */

### ISSUE THREAD

**Issue by akshaybabloo** [atom/atom#11815]
### Description

I don't know if this is happening to everyone but when I write `/* .. */` in a code block, every thing after that turns to pink (See the screenshot).
![screen shot 2016-05-23 at 3 48 34 pm](https://cloud.githubusercontent.com/assets/7360286/15459907/39b40754-20fe-11e6-96d8-870774e41a12.png)

### Steps to Reproduce

1. Follow the content in the screenshot.

**Expected behavior:** No pink color

**Actual behavior:** Turns anything after `/* .. */` to pink.

### Versions

**Atom version**

Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

No amp installed.

OS - OSX 10.11.5

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/language-c](https://github.com/atom/language-c) repository.  Thanks!
