### ISSUE TITLE
cmd + ` does not swap Atom windows in same workspace OSX

### ISSUE THREAD

**Issue by cdbattags** [atom/atom#11816]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

cmd + ` doesn't swap Atom windows in same workspace on OSX

### Steps to Reproduce

1. open two Atom windows in same workspace
2. press cmd + `

**Expected behavior:** should swap windows

**Actual behavior:** nothing

### Versions

Atom version 1.7.3

OSX version 10.11.4

**Comment by hultberg** [comment]
@cdbattags Did you find a solution? I'm also unable to switch windows with cmd+`
