### ISSUE TITLE
Auto-indent in Atom thinks one space is sufficient indentation

### ISSUE THREAD

**Issue by phoenixenero** [atom/atom#11827]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Atom thinks one space is sufficient indentation and promptly indents my code one space when I copy and paste or move code.
### Steps to Reproduce
1. Get some code with comment docblocks:

``` php
/**
 * Lorem ipsum dolor.
 */
```
1. Copy some random code after a comment docblock:

``` php
while (true) {
    //
}
```

**Expected behavior:** Code is copied without being indented by once space.

**Actual behavior:** Code is copied and indented one space.
### GIF showing behavior

![anim](https://cloud.githubusercontent.com/assets/9031092/15494602/f5e58fc8-21bd-11e6-983d-a555a06b6e02.gif)
### Versions
- Windows 7 Ultimate x64 – Atom 1.7.4

```
> atom --version

Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

> apm --version

apm  1.9.2         
npm  2.13.3        
node 0.10.40       
python 3.5.1       
git 1.9.5.msysgit.1
visual studio 2012 
```

**Comment by brunnolou** [comment]
Same problem here!
Also when selecting all and applying **Auto Indent** it messes the indentation:
```js
  /**
  * Constructor.
  */
  
  constructor
```
😢 

Mac OSX El Capitan 10.11.5 – Atom: 1.8.0

```bash
> apm --version

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.8.1
```
