### ISSUE TITLE
Code folding based on grammar instead of indentation

### ISSUE THREAD

**Issue by fruggiero** [atom/atom#11838]
The actual folding mechanism is simply wrong and unreliable.
I often work with big files and use folding to speed up my work.

But, if the file has a wrong indentation (something not rare if the files are human edited) atom also fold the code in a wrong manner. 
This in some case can be extremely dangerous , because if you don't remember to check every time what is folded you take that as given and work on the other parts of the file in a wrong manner.

The actual code folding is based firstly on indentation then on grammar.

I think that the code folding should be based ONLY on grammar.
Because, actually, even when you have a correct grammar (with correct folding rules) you can't be sure that the editor fold the code in the right manner.

Here is some examples to show , editing an XML file (**i want to fold at line number 10**):

**Unfolded text (with wrong indentation at line 18 and 19)**:
![image](https://cloud.githubusercontent.com/assets/4760358/15536250/ce8dff60-2270-11e6-9307-8247d72f057e.png)

**Folded text (WRONG because of wrong indentation)**:

![image](https://cloud.githubusercontent.com/assets/4760358/15536276/ef14bfd0-2270-11e6-99be-cec427338a9d.png)

What the correct folding should be:

![image](https://cloud.githubusercontent.com/assets/4760358/15536312/19aa2244-2271-11e6-8548-e1a5aa3345bc.png)

But for achieve this we must fix the indentation (on line 18 and 19):

![image](https://cloud.githubusercontent.com/assets/4760358/15536453/8e0a602c-2271-11e6-91a7-0076bec79f33.png)

I think that correct indentation CAN'T be a requirement to correct code folding.

**Comment by timrosenblatt** [comment]
Bumping this. I love Atom, but haven't been able to find a solution for this. I notice it with HEREDOC syntax as well. 1000 internet points to whoever fixes this :)

**Comment by twainj** [comment]
Agreed. I'm a new Atom user, I am trying it because I picked up work on a Classic ASP project, and have to navigate poorly organized code in overlarge files. Atom actually having a contributed grammar for ASP has been a godsend.

However, being new to Atom, I never would have thought that the folding was based on indentation.
I discovered it today purely by accident, and I'm glad I did, as I was starting to wonder if the uncollapsible code I was finding was because of something strange in the code.  I was prepared to trust Atom instead of the devs that came before me on this project.

Folding based on indentation makes sense in a whitespace-sensitive language (python, etc), and I can see how this might have been a shortcut to get some functionality fast. But it really should be based on the grammar.

**Comment by cytsunny** [comment]
Having the same problem, but I am working on Laravel, an MVC framework of PHP. We are now trying to fix the coding standard but previously members have different indentation width. Wanted to use the folding function to tidy up the indentation but then hit this problem. This actually forced me to use other editor instead.

**Comment by AgamlaRage** [comment]
Here is a related post in the Atom discussion, there is a cool gif to illustrate the issue.
https://discuss.atom.io/t/how-does-code-folding-work-in-atom/23713

**Comment by threecleartones** [comment]
I think I'm running into this as well - in the attached screenshot, the `<section>` tag folds to the line just after the `<pre title="html"><code>`.

Before:

![screenshot_032417_123832_am](https://cloud.githubusercontent.com/assets/1541672/24280814/36b06c0c-102a-11e7-8e4d-d7e2b8d7b79a.jpg)

After:

![screenshot_032417_123947_am](https://cloud.githubusercontent.com/assets/1541672/24280836/6345893c-102a-11e7-95b1-ee02f0c89d12.jpg)

(it should fold the entire `<section>` tag)

**Comment by erdmenger** [comment]
+1 to @fruggiero original comment: Comming from Emacs the insufficient text folding in Atom hit me several time already, both when working on code as well as when writing with markup and other formats. Folding should work based on syntax. 
Ideally it would allow me to customize the folding if it doesn't fold as I like for some fancy format, e.g. using regular expressions.

**Comment by jchook** [comment]
+1, would also be fantastic for hierarchies that do not always have indentation, such as markdown.

**Comment by xanfus** [comment]
My suggestion considers control flow syntactic constructions for VHLLs. It would be very convenient to code fold Julia code by mere keyword set, because numerical models tend to accrete with mutually exclusive parameters of boolean type.
```
if boolean_type
   ...
end
```

**Comment by jchook** [comment]
If I could get some basic direction/strategy on making this change from @maxbrunsfeld or similar, I would be happy to contribute.

**Comment by fruggiero** [comment]
In the upcoming VS Code the issue is resolved by the creation of the "folding provider" extension for the language server protocol:

https://github.com/Microsoft/vscode/issues/3422

https://www.npmjs.com/package/vscode-languageserver-protocol-foldingprovider

I suggest to take a look at their implementation.

**Comment by maxbrunsfeld** [comment]
This is now supported in Atom for the languages mentioned in this PR: https://github.com/atom/atom/pull/16299. Because the feature is still in development, you have to opt into it via the `Use Tree-sitter Parsers` setting. It should be very easy to create a [tree-sitter](https://github.com/tree-sitter/tree-sitter) grammar for XML so that we can support that language as well.

**Comment by AgamlaRage** [comment]
Don't close! This is not implemented yet, and we need it!

Atom: 1.33.0
Windows 10 Pro: 1809 (17763.437)
Step to reproduce: Copy/Paste this code and try to fold the section.
(Same behavior in CSS, SCSS, JS, PHP)

```php
if (true) {
My inner expression...
}
```

**Comment by Aerijo** [comment]
@AgamlaRage Your example folds properly in JS, and the other languages don't have Tree-sitter parsers added yet.

**Comment by AgamlaRage** [comment]
@Aerijo, ok thx!
My bad, I had Babel enable. I can confirm that this example folds properly in JS with my environment.
