### ISSUE TITLE
how to config atom to use PAC file in ubuntu

### ISSUE THREAD

**Issue by halfer53** [atom/atom#11835]
### Description

I'm using the school network, and it has a set of complicated proxy rules such that the proxy can only work with this PAC file. Here is a glimpse [PAC](http://www.waikato.ac.nz/waikato.pac). 

Also, since I'm not allowed to install any software, I have to download the portable version (tar.gz). 

How do I set up auto-config-url in atom?
### Versions

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1
Ubuntu 14.04.4 LTS

**Comment by alexjurkiewicz** [comment]
Unfortunately, you can't use a pac file with Atom. You need to read the pac file, determine what your proxy URL is, and statically configure Atom to use that proxy. See #5725 for more info
