### ISSUE TITLE
Crash when opening large (27MB) file and switching encoding.

### ISSUE THREAD

**Issue by cosmix** [atom/atom#11831]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

(Issue might be related to #11742, but seems unique enough to merit its own issue. I posted it here as it crashes the editor -- might be relevant to [atom/encoding-selector](https://github.com/atom/encoding-selector) )

Atom 1.7.4 crashes (safe mode) when opening this large file: https://raw.githubusercontent.com/LibreOffice/dictionaries/master/el_GR/el_GR.dic and changing the encoding from UTF-8 to 'ISO-8859-7 (Greek)' via Shift - Control - U.

It is also significantly unresponsive both while opening the file (no feedback) and after choosing the new encoding for the file.

### Steps to Reproduce

0. Get https://raw.githubusercontent.com/LibreOffice/dictionaries/master/el_GR/el_GR.dic and save to disk
1. Open Atom (from terminal using `--safe`)
2. Open the saved file.
3. Wait for atom to become responsive.
4. Press Control - Shift - U to bring up the Encoding Selector.
5. Type 'Greek' and choose 'Greek (ISO 8859-7)' from the filtered list.
6. Wait for several seconds for atom to become responsive – it crashes instead.

**Expected behavior:**

I expected Atom to open the file promptly and without any UI freezes and not crash when switching encoding.

**Actual behavior:**

Atom crashes several seconds after user chooses to switch encoding from UTF-8 to Greek ISO 8859-7 using the built-in Encoding Selector.

### Versions

Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4

on OS X 10.11.5

**Comment by trusktr** [comment]
Tracking all these large-file issues in #12065.

**Comment by lee-dohm** [comment]
The Atom team is tracking them in https://github.com/atom/atom/issues/8864. You may want to subscribe there for updates.

**Comment by cosmix** [comment]
There are, indeed, numerous tickets about the same general 'class' of issue. But I think bundling what seems to be a bunch of different (possibly unrelated) issues under a few generic 'crashes with large file' tickets is not helpful. At least it wouldn't be to me if I was trying to track down the cause. I described a very specific set of circumstances that always cause a crash. If you feel that's the same as the dozens of other more 'generic' tickets, I'm cool with that. But I don't think #8864 or #12065 have anything to do with the issue reported here.
