### ISSUE TITLE
Whitespace without "Show Line Numbers"

### ISSUE THREAD

**Issue by TuomLarsen** [atom/atom#11836]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

When enabling the "Show Line Numbers" option, the editor has nice white space between the file pane and the editor because of the numbers, see the attached screenshot "loose.png". However, when disabling the option, the text appears at the very left of the editor pane, looking very cramped. ("tight.png")
### Steps to Reproduce
1. type some text into editor
2. enable "Show Line Numbers" option
3. enjoy the generous margins around text
4. disable the option
5. the text in editor has no gap on its left now

**Expected behavior:**

The margins should exhibit generous white space, regardless of the line numbers appearance.

**Actual behavior:**

The typography and the use of white space varies on the "Show Line Numbers" option.
### Versions

Atom 1.7.4
Xubuntu 16.04

"loose.png"
![loose](https://cloud.githubusercontent.com/assets/2552859/15524728/2a3186a8-2225-11e6-8090-c1c482c5bdf1.png)

"tight.png"
![tight](https://cloud.githubusercontent.com/assets/2552859/15524724/24d849b2-2225-11e6-81d0-42576fbcd112.png)

**Comment by slavat** [comment]
Adding this code to styles.less adds a padding:
```css
atom-text-editor {
  padding-left: 5px;
}
```
But I agree that there has to be some space by default.

**Comment by simurai** [comment]
Maybe instead of `display: none;`

```html
<div class="gutter" style="display: none;">
```

we could add an `is-hidden` class:

```html
<div class="gutter is-hidden">
```

and then add these styles:

```less
.gutter.is-hidden {
  padding-left: .5em; // add padding
  .line-numbers {
    display: none; // remove the numbers
  }
}
```

If this is a case of "changing the default that might upset some people", @slavat's `styles.less` tweak is a great stop gap. Then there is more control how big the gap should be. `.5em` would adjust based on the font-size:

```less
atom-text-editor {
  padding-left: .5em;
}
```

**Comment by eonist** [comment]
Is there a way to hide this empty space? Feels superfluous to have it if you don't want it. I like my Atom zen 😁
