### ISSUE TITLE
Window serialisation/state

### ISSUE THREAD

**Issue by danielbayley** [atom/atom#11834]
Window serialisation needs some improvements on macOS, to better match expected native app behaviour.
- [ ] Include _dev mode_ state in window serialisation
- [ ] Include minimised state in window serialisation
- [ ] Add `Window` > `Minimize All` alt <kbd>⌥</kbd><kbd>⌘</kbd><kbd>M</kbd> menu item
- [ ] Add `Window` > `Zoom All` alt menu item

**Comment by danielbayley** [comment]
These still haven't been resolved sly bot! 🤖

**Comment by 50Wliu** [comment]
Sorry about that @danielbayley!  probot's been having some issues where his warning comments get rate limited and don't show up.

**Comment by danielbayley** [comment]
@50Wliu I like how he gets anthropomorphised.
