### ISSUE TITLE
Atom doesn't refresh when switching virtual desktops under Xfwm

### ISSUE THREAD

**Issue by ggl** [atom/atom#11841]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Atom doesn't refresh when switching virtual desktops under Xfwm.
### Steps to Reproduce
1. Start Atom
2. Open a file
3. Switch desktops back and forth

**Expected behavior:** Refresh content.

**Actual behavior:** Content from the switched desktop along with pieces of deasktop background remain superimposed on thhe Atom window.

![screenshot - 05252016 - 10 24 45 pm](https://cloud.githubusercontent.com/assets/3610557/15553960/642a1ad2-22ca-11e6-86d9-11ca1d940272.png)
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

Linux 3.13.0-86-generic #131-Ubuntu SMP Thu May 12 23:33:13 UTC 2016 x86_64 x86_64 GNU/Linux

**Comment by tristanojbacon** [comment]
I'm running 16.04 inside VirtualBox 5.0.20 r106931, and I experienced the same symptoms. I am using the VirtualBox Guest graphics driver, shipped with VirtualBox.

I am also on the latest Atom (1.7.4)
Linux version 4.4.0-22-generic

Everything except the window decorations behave as though it's always on top. Also, it crashed while reloading a file as it was changed on disk, outside the editor.

**Comment by ChallahuAkbar** [comment]
On Ubuntu 16.04 in VirtualBox 5.0.24 r108355, same thing; I'm also using the guest graphics driver.
Whenever I need to do something in a window other than atom, I have to close atom and reopen it because it covers all other windows and becomes somewhat inoperable.


Atom: 1.8.0
Electron: 0.36.8
Chrome: 47.0.2526.110
Node: 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11+
git 2.7.4

Linux: 4.4.0-28-generic

**Comment by lee-dohm** [comment]
We have seen other issues when running under VirtualBox that seem to be VirtualBox and Chromium not playing well together. For example, https://github.com/atom/atom/issues/11574. Others have reported that using `atom --disable-gpu` or this addition to your `Vagrantfile` have been helpful: https://github.com/atom/atom/issues/11574#issuecomment-224878092

**Comment by ChallahuAkbar** [comment]
Yeah, from my searching on the VirtualBox bug tracker, it almost definitely has to do with changes made in the 5.0.18 guest additions when 3d acceleration is enabled.

**Comment by lee-dohm** [comment]
@ggl Can you reproduce the same issue using the Chromium browser v47?
