### ISSUE TITLE
the editor has crushed-what should I do?

### ISSUE THREAD

**Issue by elmarin** [atom/atom#11844]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by hultberg** [comment]
Please fill out the template regarding your issue, or else we cannot help you.

**Comment by 50Wliu** [comment]
Please create a new issue and completely fill out the provided issue template as @hultberg mentioned.  Thanks!

**Comment by elmarin** [comment]
Hi,

everything's fine now. I figured it out.

It was a problem with the settings of the autocomplete-elixir package I've
installed.

Thanks a lot though.


On Thu, May 26, 2016 at 5:02 PM, Wliu <notifications@github.com> wrote:

> Closed #11844 <https://github.com/atom/atom/issues/11844>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/11844#event-673202694>
>



-- 

[image: Stoiximan Logo]
Niki Marinaki
Junior Software Engineer
<https://www.facebook.com/stoiximan.gr> <http://twitter.com/stoiximan>
<https://www.instagram.com/stoiximan.gr/>
<https://www.youtube.com/user/StoiximanTV/>
<https://www.linkedin.com/company/stoiximan-gr>

E-mail: n.marinaki@stoiximan.gr
