### ISSUE TITLE
`atom` cli crashes

### ISSUE THREAD

**Issue by heyarne** [atom/atom#11843]
I am getting the following error when trying to use the `atom` command line tool:

```
$ atom --safe .
/usr/local/bin/atom: line 115:  8318 Trace/BPT trap: 5       open -a "$ATOM_PATH/$ATOM_APP_NAME" -n --args --executed-from="$(pwd)" --pid=$$ --path-environment="$PATH" "$@"
```

I installed atom via `brew cask install atom` yesterday, 1.7.3, and it immediately updated. I can use the atom app, it only occurs when trying to start from the command line.

Versions:

```
$ atom --version
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.8.2
```

Running on Mac OSX 10.11.5.  
**To clarify:** I am not sure wheither this is an issue of `atom` or one of `hombrew cask`. I have opened issues in either github repository.

**Comment by heyarne** [comment]
I uninstalled atom completely with `brew cask zap atom` and reinstalled a fresh version 1.7.4, the problem persists. If there is any additional information I can provide, I'll happily do that.

**Comment by damieng** [comment]
Can you try an official build from atom.io and let us know if that works on your system so we can determine if it's a configuration issue or a brew package issue? Thanks

**Comment by damieng** [comment]
No response. Closing.
