### ISSUE TITLE
Editor crashes intermittently on save

### ISSUE THREAD

**Issue by spryce** [atom/atom#11842]
I'm not sure why this has just started. I have not installed any new packages within the last week or two. I have been working all day without any problems. I had left over pizza for lunch and then things started to go bad after that. It was only one day old pizza though so I suspect something else is the problem.

Basically it will just crash every few saves. Im not doing anything special that I can offer to reproduce this problem. I have: 
- Run Atom in safe mode
- Checked I am on the latest version (1.7.4)
- Flicked through the debugging guide
- not changed any config files
- not edited any key bindings
- not getting any red pop ups etc

atom --version reveals:

> Atom    : 1.7.4
> Electron: 0.36.8
> Chrome  : 47.0.2526.110
> Node    : 5.1.1

npm --version reveals:

> apm  1.9.2
> npm  2.13.3
> node 0.10.40
> python 2.7.2
> git 1.8.1.msysgit.1
> visual studio 2012

*edit - Windows 7 if that matters

Error img:
![atom-crash](https://cloud.githubusercontent.com/assets/12742003/15564391/297665fe-2355-11e6-8225-d73d4fd00c77.jpg)

**Comment by 50Wliu** [comment]
@spryce Can you please upload the latest `.dmp` file from `%TEMP%\Atom Crashes` here?  You'll have to zip it or rename the extension in order for GitHub to accept it.

**Comment by adbenson** [comment]
I'm seeing virtually the same issue, same OS, same Atom versions: unpredictable crashes but no more than 10 minutes apart. Same in --safe mode.

I didn't find a `.dmp` file in the Atom Crashes folder, did find `operation_log.txt`
[operation_log.txt](https://github.com/atom/atom/files/285082/operation_log.txt)

But it didn't look too instructive at a glance. Any other information I can provide?

**Comment by stewhouston** [comment]
+1. Crashing every 5 minutes or so. Started a few days ago. Trying to figure out if I have a conflicting service running.

**Comment by spryce** [comment]
@50Wliu Dump file attached. Cheers.

[fa7c0dd6-5548-4b09-be71-85585125e833.zip](https://github.com/atom/atom/files/285642/fa7c0dd6-5548-4b09-be71-85585125e833.zip)

**Comment by 50Wliu** [comment]
Awesome, thanks!  /cc @damieng

@stewhouston Are you also on Windows and Atom 1.7.4?

**Comment by matisszilard** [comment]
Hi All, I have the same issue on Ubuntu 14.04 LTS. Yesterday I updated the atom, it worked until today. 
Right now it does not even start, only an error popup is shown. 
The /tmp/Atom Crashes folder is empty. 

```
➜  ~ atom --version
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
➜  ~ npm --version 
2.15.5
```

Error popup: 
![atom](https://cloud.githubusercontent.com/assets/17850589/15609804/cadefe12-242a-11e6-9f31-9d024db21740.png)

**Comment by stewhouston** [comment]
@50Wliu Yep, Win10/Atom 1.7.4. I am using the atom-typescript package which is excellent but quite heavy. I thought that may be the source of the issue however I get the same behavior in safe mode.

**Comment by jerone** [comment]
Can confirm this on - not yet mentioned - Windows 8.1 (64-bits). Atom 1.7.4.

**Comment by adi518** [comment]
I just ran into it today... crashes non-stop. Took the advice above and got rid of my .atom. Seems to have fixed the error for the time being. Before I did that, I exported my packages using: https://atom.io/packages/config-import-export and saved some hassle getting them back.
