### ISSUE TITLE
Failed to move entry .... already exists

### ISSUE THREAD

**Issue by jersten** [atom/atom#11854]
### Description

Unable to drag-n-drop overwrite a file.

### Steps to Reproduce

1. Pick a file (in my case from the desktop).
2. Drag the file onto the folder structure of an open project.
3. You'll get the following error:

![selection_002](https://cloud.githubusercontent.com/assets/7646510/15610038/41205740-23f1-11e6-9235-2873dd99dc9a.png)

**Expected behavior:** Either automatically overwrites or Atom prompts me to overwrite.

**Actual behavior:** Does nothing.

### Versions

Atom 1.7.3

**Comment by hultberg** [comment]
I can't reproduce the issue as described on Mac OSX. I think you are trying to move a file that is already there. What OS do you use?

**Comment by jersten** [comment]
This is on Xubuntu 16.04.

**Comment by jersten** [comment]
Correct; the file is already there. I want it to replace it; or prompt me to replace it.

**Comment by hultberg** [comment]
@jersten Indeed. I think this issue belongs in the [atom/tree-view](https://github.com/atom/tree-view) repo, not core.

**Comment by 50Wliu** [comment]
Thanks @hultberg!

**Comment by jersten** [comment]
Is this issue already open in atom/tree-view or do I need to create an issue there?

**Comment by 50Wliu** [comment]
@jersten Please create a new issue if one doesn't already exist (just do a cursory search for it).
