### ISSUE TITLE
Regex's in a grammar don't work over multiple lines

### ISSUE THREAD

**Issue by serialhex** [atom/atom#11856]
I'm making a syntax highlighter for Common Lisp, and one of the things I've noticed is that a regex will not work over multiple lines.  Example:

I'm using (effectively) this regex:
```regex
(?<=\()
(def[\S]*)\s+
([\S]*)\s+
  (\(\s*
    ((
      [^()\s]+[\n\s]*|
      \([^()\s]+\s+[^()\s]+\)[\n\s]*
     )*)
  \))
```
and I get this:
![bad-img](https://cloud.githubusercontent.com/assets/500833/15619645/7e81feb8-2423-11e6-8a60-3b273c72bf95.png)

The `meh` & `hex` should also be red.  Using the built-in `oniguruma` in dev-mode gives me this:

![good-regex](https://cloud.githubusercontent.com/assets/500833/15619814/a10dc38a-2424-11e6-9a12-7445afb9d99d.png)

and even trying it out in something like `regex101.com` says this should work just fine.  Ao there must be something else that is going on...

The actual implementation is [located here](https://github.com/serialhex/language-common-lisp/blob/master/grammars/lisp.cson#L345-L355).

BTW, this effects the Racket highlighting also:
![racket](https://cloud.githubusercontent.com/assets/500833/15620061/00568e2a-2426-11e6-84db-3d2e58830274.png)

Thanks for any help!

**Comment by 50Wliu** [comment]
This is a limitation in TextMate's grammar-matching spec, which is also present in [atom/first-mate](https://github.com/atom/first-mate) which Atom uses.  See atom/first-mate#57 for more information.

**Comment by serialhex** [comment]
Damn that was fast!!!  Thanks!  Here's a happy penguin: :penguin:

**Comment by 50Wliu** [comment]
Haha, just happened to be going through my unread notifications at the time :P.
