### ISSUE TITLE
Atom crashes on windows 7 after dragging folder into editor

### ISSUE THREAD

**Issue by RsD0p9BK** [atom/atom#11859]
Atom crashes on windows 7 after dragging folder into editor

**Comment by hultberg** [comment]
Please fill out the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) provided when you are facing the new issue screen as this issue needs more information.

**Comment by 50Wliu** [comment]
Not enough information to triage, so closing.  Feel free to open a new issue and fill out the issue template as @hultberg said.
