### ISSUE TITLE
Atom crashes opening file by command line, El Capitan 

### ISSUE THREAD

**Issue by kyle-sorensen** [atom/atom#11855]
1. The problem is not reproducible using safe mode. It works fine in safe mode. 

2. I am running the latest version, 1.7.4

I am opening some html files using the command line with the command 'atom .' After a few moments atom becomes unresponsive and then crashes. Here is a console trace during load time up to the crash. 

5/27/16 11:22:12.765 AM Atom[1441]: App load time: 265ms
5/27/16 11:22:14.959 AM launchservicesd[78]: SecTaskLoadEntitlements failed error=22
5/27/16 11:22:14.963 AM launchservicesd[78]: SecTaskLoadEntitlements failed error=22
5/27/16 11:22:14.979 AM launchservicesd[78]: SecTaskLoadEntitlements failed error=22
5/27/16 11:22:14.982 AM launchservicesd[78]: SecTaskLoadEntitlements failed error=22

There are no errors in the developer console in Atom, the application becomes unresponsive before anything is logged, I am assuming.

**Comment by 50Wliu** [comment]
If the crash isn't happening in safe mode that most likely means that one of your installed packages is causing the issue.  Your packages are installed at `~/.atom/packages`.
