### ISSUE TITLE
"Open" opens file in wrong window when multiple windows exist

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#11853]
### Description

When multiple windows are open, attempting to open a file with the "Open..." dialog in an empty window opens that file in the wrong window, if that file is in a folder that is open in another window.
### Steps to Reproduce
1. Create an Atom window.
2. Add a folder to it.
3. Create a second, empty Atom window, and select it.
4. "Open" from the file menu (e.g. Cmd+O)
5. Select a file that's the folder that you added to the first window.

**Expected behavior:**
Atom opens that file in this new second window.

**Actual behavior:**
Atom fronts the first window and opens the file there. Since Atom windows can freeze opening large files (e.g. #8154), I want to avoid this.
### Versions

Atom 1.7.4 in safe mode (and OS X 10.11.5).

**Comment by hultberg** [comment]
Confirmed, opening a file that is in a directory that is in an open atom window the file is not opened in my focused window. Using Atom 1.7.4 in safe mode on OS X El Captain.
