### ISSUE TITLE
HTML syntax highlighting breaking at non-word characters

### ISSUE THREAD

**Issue by coreybruyere** [atom/atom#11857]
I'm seeing this on all UI and syntax themes:

<img width="971" alt="screen shot 2016-05-27 at 2 02 57 pm" src="https://cloud.githubusercontent.com/assets/3430222/15621453/e2bf2e36-2415-11e6-8f5a-c856674e1f8c.png">

Here's the current packages I'm using:

<img width="1023" alt="screen shot 2016-05-27 at 2 24 49 pm" src="https://cloud.githubusercontent.com/assets/3430222/15621589/cd666486-2416-11e6-96ac-6def70141413.png">

- Running Atom 1.7.4
- Same thing occurred in safe mode

**Comment by 50Wliu** [comment]
@coreybruyere Please create a new issue on [atom/language-html](https://github.com/atom/language-html) instead and include an HTML snippet that can be copy/pasted into Atom to reproduce the issue.  Thanks!
