### ISSUE TITLE
Exclude temporary download of updates from Time Machine on OS X

### ISSUE THREAD

**Issue by caesar** [atom/atom#11867]
On OS X, Atom temporarily stores downloaded updates at `~/Library/Application Support/com.github.atom.ShipIt/`.

These files are included in Time Machine backups, causing a huge amount of backup churn (often several hundreds of megabytes in each hourly backup).

There are two possible solutions:

* Set the temporary download to be excluded from Time Machine backups. This can be done from the commandline using `tmutil addexclusion <path>`.

* A more 'correct' solution would be to store the temporary download in a subdirectory of `~/Library/Caches/`. This whole directory is automatically excluded from Time Machine backups.

Atom v 1.7.4.

(I am assuming this is an Atom bug rather than one in a third-party library. I haven't been able to find anything called 'shipit' so I assume it is part of Atom.)

**Comment by 50Wliu** [comment]
> (I am assuming this is an Atom bug rather than one in a third-party library. I haven't been able to find anything called 'shipit' so I assume it is part of Atom.)

The Mac auto-updater we use is called `Squirrel.Mac`, which contains many `shipit` references :shipit:.  @joshaber should this issue be moved to the Squirrel repository instead?

**Comment by caesar** [comment]
Thanks @50Wliu. Is `Squirrel.Mac` a GitHub product? I ask because the identifier used is `com.github.atom.ShipIt`.

**Comment by joshaber** [comment]
Yes, please open an issue on https://github.com/Squirrel/Squirrel.Mac.

>Is Squirrel.Mac a project by the Atom team?

It was originally started by a GitHub employee.

**Comment by caesar** [comment]
Thanks guys. Turns out there's already [an issue open for this with Squirrel](https://github.com/Squirrel/Squirrel.Mac/issues/108), though sadly it's been open for over two years with no progress.

In the meantime if anyone wants to work around this on their own computer the solution is
`tmutil addexclusion -p '~/Library/Application Support/com.github.atom.ShipIt'`
(The `-p` is necessary because the directory gets deleted after every update and recreated for the next one.)

**Comment by 50Wliu** [comment]
Closing in favor of the referenced issue.

**Comment by caesar** [comment]
@joshaber has [fixed this upstream](https://github.com/Squirrel/Squirrel.Mac/issues/169). Cool! 👍
