### ISSUE TITLE
Visual glitch after clicking on "update all"

### ISSUE THREAD

**Issue by ChristianSch** [atom/atom#11861]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)? **NB: will edit when next update is available**
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? **NB: no, but the changelog did not reference anything relevant, will update, as aforementioned**
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? **NB: not sure, it affects multiple fields in the reference image**
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Visual glitch when clicking on "update all" in the "update packages window.
![screen shot 2016-05-29 at 11 15 27](https://cloud.githubusercontent.com/assets/6138133/15632361/3d12adde-258f-11e6-9b40-3210b9813cb8.png)

NB: probably relevant: #732

### Steps to Reproduce

1. Have several tabs open
2. Open up settings
3. While this loads, click on the "updates available" in the bottom right
4. Click on "update all"
5. et voilá
6. NB: click on other tab resolves visual glitch

**Expected behavior:** No visual glitches

**Actual behavior:** Visual glitch

### Versions
```
atom --version
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

```
uname -a
Darwin *snip* 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
```

**Comment by Nikki1993** [comment]
That's what happens when you update the theme. I can see you have nucleus-dark-ui being updated, that probably caused the botched look. After theme is updated, atom will apply/use it again. Nothing out of the ordinary here :P

**Comment by ChristianSch** [comment]
I see, I did not know that, thanks. Is it something that should be addressed? Or is it expected behavior? (Read: let open or close this issue?)

**Comment by 50Wliu** [comment]
I think this is expected, since the theme has to be disabled while it is being updated.  Does it not fix itself after it finishes updating?

**Comment by Nikki1993** [comment]
@50Wliu as you said, it is to be expected. Theme gets unloaded, you get a "bare bone without CSS" atom, theme updated and reloads. The only bug present atm, is that theme settings are not loaded after the update. You need to restart atom for it to recognize any preferences set in the theme. Aka, I have material UI theme and a **custom blue color**, but it **defaults to teal after update** so **I need to restart** atom for it to pick up the right color.

**Comment by ChristianSch** [comment]
Well, the glitch has gone away only after I switched to an actual editor tab, so I can't really help with that, I guess. I am not sure if the update completed upon switching the tabs, or even if the reloading did happen in the exact same moment.

**Comment by Nikki1993** [comment]
@ChristianSch Switching tabs could be the same as reloading. Either way, it's perfectly normal for editor to looked botched during theme update :)

**Comment by 50Wliu** [comment]
Ok, since this issue seems to be resolved I'm closing this.
