### ISSUE TITLE
Important: Project folders disappear

### ISSUE THREAD

**Issue by whizkydee** [atom/atom#11869]
### Prerequisites
* [Y] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [Y] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [Y] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [Y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

OS: Windows 8, 10
Atom: v1.7.4

@mojombo @Caged @schacon @defunkt @benburkert 
### Description

Project folders disappear

Right from when I've been using v1.0, this has been consistent. When Atom is closed and I open a file with Atom from Windows File Explorer, I opens the file in Atom and replaces my Project Folders, making the file name a Project in the Tree View and then I have to add all my Project Folders again.

I've always wanted to report this issue but I thought it would be fixed sooner.

Some help would be appreciated. Thanks.

**Expected behavior:** Atom keeps my project folders

**Actual behavior:** Project folders disappear and filename becomes a folder

**Comment by Ben3eeE** [comment]
I believe you are talking about https://github.com/atom/atom/pull/10862 https://github.com/atom/tree-view/issues/471 which (finally) has a merged PR and according to latest comments should be available starting from Atom 1.8.

I don't know how this will affect the launch story however as I have not tested the PR, maybe there is some other issue that causes you to have to add all the project folders again.

**Comment by 50Wliu** [comment]
Yeah, you should be able to install the beta to resolve this issue.  Sorry for the inconvenience.
