### ISSUE TITLE
Checkboxes are clickable inside packages descriptions

### ISSUE THREAD

**Issue by FezVrasta** [atom/atom#11862]
### Description

If the README of any package contains a checklist, when you visit the package description from within Atom, you are able to check/uncheck the items.

It's not an important bug, it just feels weird, probably the checkboxes should be set to `disabled`.

### Steps to Reproduce

1. Open the Atom settings
2. Click on "Install"
3. Search the "Atom Tabs Exposé" package and open its description
4. Scroll down till you find the checkboxes
5. Click on any of the checkboxes

**Expected behavior:** The checkboxes should not change state
**Actual behavior:** The checkboxes get checked/unchecked on click

![checkboxes](https://cloud.githubusercontent.com/assets/5382443/15632864/fd2b206a-259e-11e6-9284-b0c7752e32a5.gif)

### Versions

```Shell
~$ atom --version
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
~$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.9
git 2.6.4
```

OS X Yosemite 10.11.5 (15F34)

**Comment by Ben3eeE** [comment]
https://github.com/atom/settings-view/issues/628?

**Comment by FezVrasta** [comment]
oh... sorry, I have searched in the wrong repository...
