### ISSUE TITLE
Atom Editor - Vertical Line UI Bug

### ISSUE THREAD

**Issue by andrewlumley** [atom/atom#11874]
### Description

I have found that upon launching _Atom_ on my Mac with the latest update, a UI glitch presents a vertical line through the main text editor at all times.

### Steps to Reproduce

The bug is presented under the following conditions:

1. Launched in OS X 10.11.6 (beta - 15G7a)
2. Using latest version of _Atom_ - V 1.7.4

### Screenshot

![screen shot 2016-05-31 at 9 33 58 pm](https://cloud.githubusercontent.com/assets/6331394/15696330/784b6144-277d-11e6-93e2-bc0df36ec4b6.png)

### Versions

OS: OS X 10.11.6 (beta - 15G7a)

Atom: 1.7.4
Electron: 0.36.8
Chrome: 47.0.2526.110
Node: 5.1.1

app: 1.9.2
nam: 2.13.3
node: 0.10.40
python: 2.7.10
git: 2.7.4

**Comment by mnquintana** [comment]
See https://discuss.atom.io/t/what-is-this-line-on-the-right-in-the-editor-view/18477
