### ISSUE TITLE
"The editor has crashed" after editing remote files with FileZilla

### ISSUE THREAD

**Issue by SK83RJOSH** [atom/atom#11871]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

When exiting Atom after editing and uploading a file through FileZilla the editor fails to exit cleanly.

This occurs regardless of whether or not all files have been closed out in Atom before exiting, but only if they've been deleted by FileZilla through the "Finish editing and delete local file." option. Upon opening atom the next time there may sometimes be a tab left over for the file you were last editing. After this occurs once the editor can sometimes crash on subsequent exits and start ups.

I'm wondering if this has anything to do with filelocks and whether or not this issue is with the treeview (as opposed to atom core).
### Steps to Reproduce
1. Open a remote file with FileZilla while ensuring Atom selected as the default editor
2. Save the file in Atom
3. When FileZilla prompts you to do so, select "Finish editing and delete local file."
4. Exit Atom

**Expected behavior:** The editor should exit successfully.

**Actual behavior:** The editor fails to exit cleanly.
### Versions

1.8.0-beta4 on Windows 10

**Comment by 50Wliu** [comment]
@SK83RJOSH Can you please zip the latest `.dmp` file from `%temp%\Atom Crashes` and upload it here?  Thanks.

**Comment by SK83RJOSH** [comment]
Yeah, no problem :smile: 
[40311a19-0dcb-41b4-95e0-9fcd353a4daf.zip](https://github.com/atom/atom/files/292266/40311a19-0dcb-41b4-95e0-9fcd353a4daf.zip)

**Comment by AGPDev** [comment]
+1
