### ISSUE TITLE
cmd+` doesn't switch between windows consistently

### ISSUE THREAD

**Issue by dawnerd** [atom/atom#11886]
Two different directories opened with `atom .` cmd+` only works on the first window that opens. Once the second window is shown it wont switch back. Can consistently switch to the second window from the first window.

Version: 1.7.4
OS: osx 10.11.5

Tried in safe mode, same issue. Other apps work correctly.

![image](https://cloud.githubusercontent.com/assets/24781/15766826/a7efbf32-28f7-11e6-9450-6615555a573a.png)

**Comment by 50Wliu** [comment]
This seems similar enough to #11531 that I'm going to close this issue in favor of that one - feel free to subscribe over there for updates.
