### ISSUE TITLE
Very slow indexing when using Cryptomator encrypted folder (Windows 10)

### ISSUE THREAD

**Issue by isuraed** [atom/atom#11880]
### Description
https://cryptomator.org/ is a client side encryption software. When atom opens a mounted cryptomator vault (which is mapped to a network drive locally) it tries to index the hidden folders (named "." and ".."). This indexing never stops since atom is trying to index the hidden folders that contain the cryptomator metadata. This occurs on Windows 10 Pro. The issue is not present on OSX.

### Steps to Reproduce

1. Clone any repo (e.g. https://github.com/twitter/heron)
2. Install cryptomator (https://cryptomator.org/downloads/#winDownload). Java client does not require installation.
3. Create a new vault in cryptomator for the heron repo
4. Mount the vault
5. Open the network drive (usually Z: drive) in atom
6. Try to find a file (Ctrl-P). Atom says "indexing" forever. Ctrl-P is broken and you can't find any files in the project.

I've also tried adding "." and ".." to the ignored folders list in settings (and enabled "hide hidden folders" in tree-view plugin). This doesn't make a difference and these folders are not hidden.

**Expected behavior:**
Atom should quickly index the repo. It takes ~2 seconds to index the non-encrypted heron repo. 

**Actual behavior:** [What actually happened]
Atom tries to index these hidden folders. Indexing goes on forever because it's trying to index a deep structure of hidden folders.

### Versions
1.7.4 (windows 10 pro x64 machine)

**Comment by 50Wliu** [comment]
Can you please reopen this issue on the [atom/fuzzy-finder](https://github.com/atom/fuzzy-finder) repo?  Thanks.

**Comment by isuraed** [comment]
Done.
