### ISSUE TITLE
sudo atom -a file open in new window (not in window already open)

### ISSUE THREAD

**Issue by wicope** [atom/atom#11888]
### Description

sudo atom -a file open in new window (not in window already open)

```
$ atom --help
  -a, --add  Open path as a new project in last used window.  [boolean]
```
### Steps to Reproduce

**Actual behavior:** [What actually happened]

atom -a file1 ( first time open in new window of atom )
atom -a file2 ( second time open in window already open of atom )
sudo atom -a file3  ( Third time open in new window of sudo atom )
sudo atom -a file4  ( Fourt time open in window already open of sudo atom )

**Expected behavior:** [What you expected to happen]

atom -a file1 ( first time open in new window of atom )
atom -a file2 ( second time open in window already open of atom )
sudo atom -a file3  ( Third time open in window already open of atom )
sudo atom -a file4  ( Fourth time open in window already open of atom )
### Versions

```
$ atom --version
Atom    : 1.7.3
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

```
usuario at wicope in ~
$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1
```

```
usuario at wicope in ~
$ uname -a
Linux wicope 3.13.0-76-lowlatency #120+7.0trisquel2 SMP PREEMPT Tue Jan 19 19:55:06 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Trisquel
Description:    Trisquel GNU/Linux 7.0, Belenos
Release:    7.0
Codename:   belenos
```

**Comment by InvisibleRedInk** [comment]
Could you clarify on a little thing here, why would you want to open it in the same window. That way you will not know which "Tabs" have superuser, and which do not?

I propose this though, a feature which asks you to open the file with sudo when you try to save it and it fails (due to user restrictions).

Kudos
