### ISSUE TITLE
Crashes Every every minute

### ISSUE THREAD

**Issue by tehzu9** [atom/atom#11883]
I was working on it around 4 months and now it crashes every minute while writing code.

**Comment by tehzu9** [comment]
Using windows 10. Using no plugin. Version 1.2.4

**Comment by hultberg** [comment]
Please fill out the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) provided when you are facing the new issue screen as this issue needs more information.

**Comment by youurayy** [comment]
Atom crashes on Windows 10 when the same file which is being edited is opened in two tabs (and/or panes) simultaneously. Pretty reproducible (happens inside of 5 minutes of editing such file).

I'll try to find time to submit a proper bug report later. It would be awesome if Atom could just send its current state aftera crash, like many other programs.

**Comment by hultberg** [comment]
@youurayy Atom saves crash dumps in `%LocalAppData%\Temp\Atom Crashes`[1] and in `/tmp/Atom Crashes` on OSX/Linux.

[1] https://discuss.atom.io/t/atom-keeps-crashing-when-opening-a-file-or-project-folder/23847/4

**Comment by youurayy** [comment]
thanks @hultberg!

however I don't know how to attach the .dmp file here (tried inside .zip too) -- is there a known method that works?

**Comment by hultberg** [comment]
You should be able to attach the `.zip` (at least) on an comment as [explained here](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by youurayy** [comment]
Something's wrong with Github. I tried both WinRar and Info-ZIP and neither (nor the .dmp) is attachable to this message (by drag&drop or open dialog).

![image](https://cloud.githubusercontent.com/assets/588573/15772566/7bb52aa0-297a-11e6-9e96-09e1c3b14a7d.png)

![image](https://cloud.githubusercontent.com/assets/588573/15772582/8c1f429a-297a-11e6-8236-b5e18ab7d470.png)

![image](https://cloud.githubusercontent.com/assets/588573/15772609/afb9aff6-297a-11e6-8448-d49c79e8c541.png)

works when renamed to `.dmp.txt`:

[e7e4d6a6-5346-45e1-ace4-5037024af8fe.dmp.txt](https://github.com/atom/atom/files/297164/e7e4d6a6-5346-45e1-ace4-5037024af8fe.dmp.txt)

**Comment by Ben3eeE** [comment]
@tehzu9 Atom 1.2.4 is an old version and there has been many improvements to the overall Windows experience in the more current versions, I think the first thing to try would be to update to a current version and see if the problem persists.

**Comment by lem8r** [comment]
My atom crashes every time I'm trying to run it. There is no dumps, it crashed in safe mode too
deleting ~/.atom didn't help
It was fine last week. I don't know what's wrong and how to debug it

Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

OpenSUSE leap 42
Gnome 3.18

**Comment by tehzu9** [comment]
I have installed 1.7 version and it also crashes while writing Javascript
code.

**Comment by 50Wliu** [comment]
@youurayy @lem8r please open new issues.

@tehzu9 does it still crash in safe mode (`atom --safe`)?

**Comment by lem8r** [comment]
@youurayy I've solved my issue downgrading libfreetype2

**Comment by youurayy** [comment]
just FYI my problem (Windows crashing in same-file multi-pane edit) got resolved in 1.8.0 - works like a clock now, thanks everyone!
