### ISSUE TITLE
Copy Paste not working when editing XML files

### ISSUE THREAD

**Issue by Kungfoowiz** [atom/atom#11881]
### Description

When copy pasting from an xml file, it pastes only the first letter of the copy operation.
For example, if you select copy text "Hello World" then it will paste only "H".
### Steps to Reproduce
1. Open the attached example xml file (See ZIP download).
2. Copy a piece of text.
3. Paste back into xml file or notepad window.
   [Example - Copy.zip](https://github.com/atom/atom/files/295162/Example.-.Copy.zip)

**Expected behavior:** 

The full text should be copied.

**Actual behavior:**

Only the first letter is copied.
### Versions

Atom 1.7.4

**Comment by hultberg** [comment]
Cannot reproduce with Atom 1.7.4 on OSX 10.11. @Kungfoowiz: Do you observe the same behaviour when running atom in safe mode? `atom --safe`

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/11881#issuecomment-223233767. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Kungfoowiz** [comment]
Sorry, I got busy and did not use Atom for some time, lol. Now that I am back using it again, I tried testing this in Atom --safe mode and noticed something else. It appears to happen only in Mixed mode (see screenshot below). Mixed mode regarding CR / LF characters, you can see this on the file details on the bottom right in the screenshot.  

You can also see when I copied the text from the Mixed mode XML file that it only copied the first character. I used the exact same example XML file as I originally attached to this issue. 

And then I used a sample XML file using CRLF mode (Download from here: https://www.w3schools.com/xml/simple.xml). I was able to copy the text fine with this example, but not with the above example. 

I wonder also, the encoding type set in the above XML is UTF-16, yet Atom reports it as UTF-8. Maybe it is having an issue reading the characters because of this? 
It could also be the Mixed mode? 

![atom safe mode test](https://cloud.githubusercontent.com/assets/17824719/23263589/979aef48-f9d6-11e6-9a45-9a3dc3d59b53.jpg)

**Comment by lee-dohm** [comment]
> I wonder also, the encoding type set in the above XML is UTF-16, yet Atom reports it as UTF-8. 

Does everything work properly if you set the encoding to match the encoding of the file?

**Comment by Kungfoowiz** [comment]
Nope, I tried setting it in N++ (USC 2 little endian and big endian which I think is UTF-16 roughly) and Atom still reports it as UTF-8. 

When copying from the opened file in Atom, it still only copies a single letter, rather than what was selected. 

As a test, and also to get familiar with packages in Atom, I quickly wrote something to check the file for NULLs. I think what may be happening is when Atom hits a NULL it stops copying from that point and ignores the other characters. 

![atom nulls in file](https://cloud.githubusercontent.com/assets/17824719/23303105/02361270-fa8a-11e6-9a66-7debea3a9977.jpg)

**Comment by lee-dohm** [comment]
> Nope, I tried setting it in N++ (USC 2 little endian and big endian which I think is UTF-16 roughly) and Atom still reports it as UTF-8.

Atom doesn't autodetect encoding well, this is a known issue that is being tracked elsewhere. What I was asking for you to do is if you know that the encoding is UTF-16LE, do things work properly when you tell Atom that the file is UTF-16LE?

**Comment by Kungfoowiz** [comment]
The xml file was originally exported from Windows Task Scheduler, so I suspect that the encoding is not quite correct anyway. 

I set the file to UTF-16LE in N++ but Atom still reports it as Mixed UTF-8 XML.
![encoding](https://cloud.githubusercontent.com/assets/17824719/23401406/7d064e94-fd9f-11e6-8dad-0e1f7cbf71b2.jpg)

However, reading the file back into N++ it reports it as UTF-16LE, yet Atom does not.

**Comment by 50Wliu** [comment]
Yes, like mentioned previously, Atom doesn't do well with detecting the encoding.  You need to set it manually using Ctrl+Shift+U.  After doing that, does copy/paste start working?

**Comment by Kungfoowiz** [comment]
Sure, I understand the encoding detection is not properly working at the moment. 

As you suggested, I set the encoding manually in Atom and copy/paste still only copies a single letter. 

![atom problem copying](https://cloud.githubusercontent.com/assets/17824719/23456486/95b218c0-fe6b-11e6-942f-550a4d38c408.jpg)

**Comment by Kungfoowiz** [comment]
I thought to try with another set of programs I am using, so it is tested with something completely different. 

It saves the file as utf-16 encoding and when I open in atom it only copies the first character from the selection, as if the null characters are interrupting it. The file is identified by atom as Mixed UTF-8 XML. 

![atom problem utf16](https://cloud.githubusercontent.com/assets/17824719/23603813/82be15c0-024e-11e7-8a4a-61816e8b3a61.jpg)

**Comment by lee-dohm** [comment]
Please lets limit reproduction steps to Atom doing things incorrectly when the encoding is set correctly in Atom. Atom doing weird things when the encoding is incorrect is almost guaranteed to be a `wontfix`.
