### ISSUE TITLE
Python raw string broken

### ISSUE THREAD

**Issue by Winseven4lyf** [atom/atom#11887]
### Description

The Python Language's raw string functionality is broken

### Steps to Reproduce

```Python
print(r"\")
```

**Expected behavior:** String stops there because of the `r`.

**Actual behavior:** Atom language thinks the string continues, regardless of the `r`.

### Versions

apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.1.windows.1
visual studio
windows 10

**Comment by hultberg** [comment]
Seems that this issue should be moved to the [atom/language-python](https://github.com/atom/language-python) repo.

**Comment by Winseven4lyf** [comment]
Oh
Will do.
