### ISSUE TITLE
Atom not displaying in ubuntu Xfce desktop environment

### ISSUE THREAD

**Issue by Rocks25** [atom/atom#11884]
### Description

When launching atom under Ubuntu Xfce desktop environment, atom window never shows up, and no errors are displayed.  Tried version 1.7.4 .deb package first, then tried cloning 1.8.0-beta4 from the repo and building. Both versions had the exact same problem.  After running the atom command it displays the app load time and then just sits there and the window never comes up.

I am using ubuntu server with the Xfce desktop manager over an x2go connection.

I have also tested it over tightvnc and with KDE4 (with both x2go and tightvnc) with the exact same results.

### Steps to Reproduce

1. Install latest .deb package or build from source
2. Run atom command
3. Atom editor window never displays

**Expected behavior:** Atom window shows up.

**Actual behavior:** Atom window never shows up.

### Versions
Atom: 1.7.4 and 1.8.0-beta4
Electron: 0.36.8
Chrome: 47.0.25.26.110
Node: 5.1.1
Ubuntu: server 14.04.4 LTS
Xfce: 4.10

**Comment by cskeen** [comment]
I've got the same problem with Atom 1.8.0 on Ubuntu 16.04 via x2go. Same behavior as in the original post.

Versions

Atom      : 1.8.0
Electron : 0.36.8
Chrome : 47.0.2526.110
Node     : 5.1.1
Ubuntu  : server 16.04 LTS
Xfce       : 4.12

**Comment by Rocks25** [comment]
@cskeen I'm also having the same problem with Visual Studio Code on the same machine, but Atom and Code are the only two programs I'm seeming to have the issue with.

Would you mind trying to run Visual Studio Code and see if you have the same problem?
Just grab the .deb package on their site and install it with dpkg.

**Comment by cskeen** [comment]
VSCode has the same problem.

This might be another example of an upstream Electron issue relating to NX. electron/electron#2256

**Comment by Rocks25** [comment]
@cskeen Seems plausible. What's odd to me is that it doesn't throw errors of any sort that I could see, unless there is a log somewhere that I am unaware of.

**Comment by cskeen** [comment]
To give some clarification of the behavior (and the problem...):

When you try starting Atom via x2go, it will start Atom on display :0, regardless of the DISPLAY environment variable or anything else. This is a problem for x2go users because it defaults to a new session on :50.

This behavior can be replicated with the following steps:

1: Find a Linux machine you have local access to.
2: Install x2goserver and x2goclient. Start x2goserver.
3: Use x2goclient to connect to localhost via x2go.
4: Try to launch Atom from the x2go session.
5: The Atom window will open on the local session, not the x2go session.

**Comment by misund** [comment]
I was experiencing the same issue in Gnome 3, but noticed that I was able to open atom as root or as a guest user. So I started deleting stuff in my home directory... Hopefully, this may narrow down the problem:

```
$ atom # window did not open
$ ls -lah
$ rm  .v8flags.4.6.85.32.misund.json
$ rm .Xauthority
$ rm .xsession-errors*
$ rm -r .gconf/
$ atom # window opened successfully
```

**Comment by 50Wliu** [comment]
Closing in favor of #4360 - feel free to subscribe there for updates.

**Comment by zxw454034941** [comment]
why is this issue been closed? Is the bug fixed?
i have the same problem, but cant find answer.

**Comment by mickeyil** [comment]
This comment from #4360, helps workaround this problem:
https://github.com/atom/atom/issues/4360#issuecomment-205122828

**Comment by zxw454034941** [comment]
@mickeyil according to the steps comment on #4360 ,  still not work.  I tried this method on another computer and worked.  so maybe not the same problem, I have no idea now.

**Comment by krtschmr** [comment]
still buggy. atom window loading, but not displaying anything. just black pixels.

**Ubuntu 16.04, XFCE 4.12**
in 16.04 unity it works perfect.
