### ISSUE TITLE
Multiple Navigation shortcuts do not work on Windows

### ISSUE THREAD

**Issue by Haacked** [atom/atom#11895]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I was going through the Atom Flight Manual's "[moving in Atom](http://flight-manual.atom.io/using-atom/sections/moving-in-atom/)" section and several of the shortcuts don't work on Windows. I'll list a couple examples, but it's probably worth going through the examples in the document on Windows.

For example, `ALT` + `Right` moves to the end of the word and that works great! But `CMD` + `Right` is supposed to move to the end of the line. In mapping that to Windows I assumed that would be `CTRL` + `Right` but that doesn't work. Neither does `CTRL` + `e`. I also tried `CTRL` + `ALT` + `Right` just in case but that just changed the orientation of my screen to sideways which really sucks. :stuck_out_tongue: 

### Steps to Reproduce

1. Open a text document in Atom on Windows
2. Move the cursor to the middle of a line.
3. Hit the key combo `CTRL` + `Right`

**Expected behavior:** Cursor moves to the end of the line.

**Actual behavior:** Cursor moves to the end of the word.

### Versions
You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

* Atom Version 1.7.4
* Windows 10

**Comment by Haacked** [comment]
BTW, some of the [selection shortcuts](http://flight-manual.atom.io/using-atom/sections/atom-selections/) don't work either.

`Ctrl`+`Shift`+`w` is supposed to select the current word.

On Windows, that key combo closes Atom. I tried `ALT+Shift+w` and `WINDOWS+Shift+w` and none of them did anything useful.

**Comment by 50Wliu** [comment]
The flight manual is currently geared towards OS X only, so all the shortcuts are OS X-specific (though it looks like ctrl-shift-w doesn't exist on OS X either?).  There is no cmd-left/right equivalent on Windows other than the <kbd>End</kbd> key, which is enabled for all platforms.

Closing in favor of atom/flight-manual.atom.io#16.

**Comment by Haacked** [comment]
@50Wliu sure. But these shortcuts should also exist in some form on Windows whether the documentation is correct or not, right?

The issue I'm opening is not to fix the Flight Manual. As you point out, there's already an issue open for that. This issue is to ensure that the corresponding Windows shortcuts exist and work for each of the ones mentioned in the Flight Manual.

**Comment by 50Wliu** [comment]
@Haacked While the shortcuts don't exist, the commands do, so you can bind (almost) whatever you want to them.

I don't think Windows/Linux will ever achieve full parity with the Mac shortcuts, purely because Mac has an extra modifier key available.  Wouldn't the better solution be to provide OS-specific information in the flight manual?

**Comment by Haacked** [comment]
> @Haacked While the shortcuts don't exist, the commands do, so you can bind (almost) whatever you want to them.

By that logic, why have any default key bindings at all? I assume it's because we don't want the first experience for new users to be setting up a bunch of key bindings for common operations. We want to ease the transition from other text editors.

> I don't think Windows/Linux will ever achieve full parity with the Mac shortcuts, purely because Mac has an extra modifier key available. 

That's not exactly true. There's a mapping of [Mac shortcut keys to Windows](https://support.apple.com/en-us/HT201236). Exact 1-1 mapping may not be possible because some shortcuts belong to the operating system, but we can find alternatives in those cases.

Even if that's true, I'm still talking about the default set of keyboard shortcuts. It's a small set and we haven't exhausted the set of potential key combinations yet.

> Wouldn't the better solution be to provide OS-specific information in the flight manual?

That's a false dichotomy. I think we should do both! :smile:

Here's a specific example. The flight manual says hit `CTRL+SHIFT+w` to select a word in the editor on OSX. Are you suggesting that we simply document this shortcut doesn't exist on Windows or  Linux?

Rather than do that, why don't we create a mapping specific to those operating systems. For example, in Visual Studio, `CTRL+w` selects the current word. We could map it to that.

Or better yet, in this specific case, is `CTRL+SHIFT+w` even necessary when `Command+d` (if you only invoke it once) accomplishes the same result? Could we just remove that binding?

**Comment by 50Wliu** [comment]
> There's a mapping of Mac shortcut keys to Windows

Does the Windows key really count, though?  I can only think of one Windows app that allows the Windows key to be bound to something, and even that is under Advanced Options.

> Even if that's true, I'm still talking about the default set of keyboard shortcuts. It's a small set and we haven't exhausted the set of potential key combinations yet.

Some packages rely on those keybindings on being unbound since then they implement those in their own packages.  Obviously we can implement them anyway and let the packages deal with the fallout, but then users will have to change their muscle memory.

> For example, in Visual Studio, `CTRL+w` selects the current word. We could map it to that.

`ctrl+w` closes the current tab on Windows :wink:.  `ctrl+d` sounds good, except that keybinding is from find-and-replace which can be disabled (not that it really matters though considering how integral find-and-replace is, and that I'm pretty sure the flight manual references package-specific keybindings elsewhere as well).

I'm suggesting that when the keybinding doesn't exist, we just don't mention it or replace it with the underlying command instead.

**Comment by Haacked** [comment]
Ok, documentation will work for now. As I think about it, I think I need to rephrase the issue.

Imagine you were building Atom from scratch, but your entire team consisted of Windows developers so you targeted Windows developers in the beginning and added on OSX shortcuts as an after thought.

Which keyboard shortcut set would you have by default? Is what Atom has today it?

Given that Atom is a cross-platform editor, it should (as much as possible) feel like it belongs to every platform. Perhaps a better solution is to have some sort of shortcut sets. Maybe this is in there already?

For example, if you install Atom on Mac you get the default OSX keybinding set. If you install it on Windows you get the Windows set. But folks coming from Visual Studio can install a VS keybinding for  Atom set.
