### ISSUE TITLE
apm command not working

### ISSUE THREAD

**Issue by zhuyingda** [atom/atom#11899]
Mac osx system version 10.11
I installed the atom from official website and use it for a week.
Today, I want to write a self-package to do sth,so I follow the guide of atom.io.
However, I found the apm command in my cli is not working, that means, when I typed
`apm`
in my command line, nothing happened.
So I typed `which apm` to see where is this script file, it is in `/usr/local/bin/apm`, okay,
I typed this  `ls -l /usr/local/bin/apm` to see what file did it link?
Then, I found this file was link to `/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm`, and that is an empty file!
Of course, I `ln` the `/usr/local/bin/apm` to the right file `/Applications/Atom.app/Contents/Resources/app/apm/bin/apm` and now, everything is right.

I want to know is there any problem could lead to the `apm` command link to the wrong file?

**Comment by eastwood** [comment]
Mine is linked to the former file path and works correctly. I'd see if you can `npm install` from within the former directory and or try and run `sh Applications/Atom.app/Contents/Resources/app/atom.sh`

**Comment by zhuyingda** [comment]
After update atom newest version, the problem was resolved.

**Comment by 50Wliu** [comment]
Thanks for the update @zhuyingda!

**Comment by eastwood** [comment]
Great news!
