### ISSUE TITLE
Key-to-character mapping gets stuck in AltGr-Mode

### ISSUE THREAD

**Issue by jdittrich** [atom/atom#11904]
### Description
After using AltGr characters, Atom gets stuck in AltGr-mode and  produces only AltGr characters of the pressed keys, e.g. if I press "E" I get "€"

### Steps to Reproduce

1. Press AltGr + any other character producing key. 
2. Press the character producing key without AltGr

**Expected behavior:** Get the keys normal character (e.g. "e")

**Actual behavior:** I get the AltGr modified character of the key (e.g. "€")

### Versions
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

(also tried the Beta, same problem there)

German Keyboard (QWERTZ)

Ubuntu 16.04

**Comment by Harsesis** [comment]
I had exactly the same issue using Ubuntu 14.04 LTS and my german keyboard.
Updating atom to the newest version 1.8.0 solved the problem for me.

**Comment by DSigmund** [comment]
I have the same problem and the newest Version of atom (1.8.0)

Im using Windows 10.

**Comment by jdittrich** [comment]
Do you use some sort of internationalization package or keyboard remapping package or does it happen to a (keyboard-wise) untouched Atom?

**Comment by DSigmund** [comment]
Just found out i was using [keyboard-localization](https://atom.io/packages/keyboard-localization).  
Now the problem is, without this package, the problem is solved.  
But (although this may be another issue) i did use it to be able to use the combination **alt-gr+q**  to add an **@** and not refold the code in some crazy way...

**Comment by anothergituser** [comment]
Same here, spanish keyboard

**Comment by lee-dohm** [comment]
If this is a bug with the [keyboard-localization package](https://atom.io/packages/keyboard-localization), it should be reported there. We are already aware of the Issue that makes the keyboard-localization package necessary in the first place: atom/atom-keymap#35.

So the question is, can this be reproduced in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by 50Wliu** [comment]
No response, so closing.  Feel free to comment here if you're still experiencing this issue **without** the keyboard-localization package.

**Comment by Overdrivr** [comment]
I've encountered this issue because the package was still installed, yet it is [deprecated](https://github.com/andischerer/atom-keyboard-localization). Are there any plans to notify users of package deprecation ?
