### ISSUE TITLE
Can't highlight terms ending in a period

### ISSUE THREAD

**Issue by ruscur** [atom/atom#11908]
### Prerequisites

* [ Y ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ Y ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ Y ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ Y ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ Y ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ Y ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Syntax highlighting does not occur for terms ending in a period ( `.` ).  This is necessary for use cases such as powerpc assembly, in which some opcodes behave differently when suffixed with a period, and in some cases only function with a period.

### Steps to Reproduce

1. Use a language highlighting package that looks for terms ending in '.', such as [language-powerpc-assembly](https://github.com/ruscur/language-powerpc-assembly)
2. Activate that language, type a term that should be highlighted (in my case, `addi`), and on a new line, a term that *should* be highlighted that ends in a '.' (in my case, `stdcx.`)

**Expected behavior:** [What you expected to happen]

Terms ending in a '.' should be highlighted just as terms that don't end in a '.' are.

**Actual behavior:** [What actually happened]

Terms ending in a '.' are not highlighted until numbers are added after, it seems that there is hardcoded checking for numbers after a '.'

![Example](http://imgur.com/gAPDMS7l.png)

### Versions

```
Atom    : 1.7.4
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.3

Arch Linux running kernel 4.5.4
```

**Comment by 50Wliu** [comment]
Please report this to langauge-powerpc-assembly instead.  Thanks!

**Comment by ruscur** [comment]
This has nothing to do with that package, though (of which I'm the author).  I'm saying that you can't highlight any term ending in a period, regardless of the specific language highlighting.  At the editor level, terms with a period behave as if they're invalid/unhighlighted until there's something written after the period.

I could fix it myself if I had any idea where to look in Atom's source.

**Comment by 50Wliu** [comment]
No, this is a problem (actually two) with your language package.

The first problem is that you're only using a single backslash to escape the period when you need to be using two.  The second is that you're ending the capture with a word boundary match `\b` which doesn't allow periods to end the line.  You might want to use `\s+` instead.

**Comment by ruscur** [comment]
I tried with all sorts of backslashes, which wasn't enough.  I didn't know about the boundary match.  Thanks!
