### ISSUE TITLE
Why does react package not rank first?

### ISSUE THREAD

**Issue by aitchnyu** [atom/atom#11909]
I use Atom 1.7.4. I tried searching for and installing react. I was surprised that the package react was ranked 10th at 218448 downloads while packages with 19 to 24487 downloads precede it. I guess other users will be forced to turn to Google to find the right packages when Atom itself could be sufficient for recommending packages.

**Comment by Ben3eeE** [comment]
https://github.com/atom/apm/issues/561

**Comment by 50Wliu** [comment]
Closing in favor of atom/apm#561.
