### ISSUE TITLE
Make CEF framework installer and move libcef outside of project

### ISSUE THREAD

**Issue by hazardland** [atom/atom#11903]
For god sake make a separate installer for CEF to make users to treat libcef as a separate framework which is needed to install before installing any app using CEF just like some other apps require to install Microsoft .NET framework.

When I build apps using CEF app size becomes strongly not acceptable and nobody has ever came up with an idea to standardise way we use this framework.

While you have authority at Atom to do it and you can make others follow you ! Just imagine how many apps will shrink and how will it boost CEF based app development if you host CEF installer somewhere by versions and make standard way for apps to locate and use libcef in Windows (Linux is not problem at all) system or make request to download and install it.

**Comment by 50Wliu** [comment]
Atom does not use CEF - it uses [Electron](http://electron.atom.io) which in turn utilizes [brightray and the Chromium content module](https://github.com/electron/electron/issues/1170#issuecomment-75639373).

If I'm misunderstanding something, please feel free to reply.
