### ISSUE TITLE
Option/flag to disable direct write

### ISSUE THREAD

**Issue by kaiser101** [atom/atom#11900]
There needs be an option/flag to disable direct write. Without it the fonts are not as crisp as I would like it. And while it may be the default option for chrome going forward, there should be an option to disable it.

**Comment by damieng** [comment]
The flag necessary to perform that in Chrome is experimental and likely to be removed so we will not be supporting it at this time.

There are various improvements to the DirectWrite settings in Chrome that we will pick up as we move to newer versions of Electron.

**Comment by damieng** [comment]
Improvement to font rendering are still being tracked at https://github.com/atom/atom/issues/7261 - there are a couple more things we can do to improve what we have already such as avoiding fractional positioning of elements.

**Comment by kaiser101** [comment]
I had to download close to 4GB if microsoft trash because you idiots would not provide an option for a feature which is supposedly going to be unsupported in the future. What do you suppose users should do in the interim?

**Comment by eladkarako** [comment]
pushing a Chrome/Chromium switch through atom - possible??

for example:
<h3><code>--disable-directwrite-for-ui</code> <sub><a href="http://icompile.eladkarako.com/disable-direct-write-alternative-for-chrome/" title="#disable-direct-write Alternative For Google Chrome"><em>source</em></a></sub></h3>

**Comment by damieng** [comment]
All command-line switches are indeed effectively passed through to Chrome and I can confirm that right now that switch does what you think it does.

Whenever we update the version of Electron Atom uses we get a new version of Chromium and any removed switches like this disappear at a whim. This is why we don't recommend them and we have zero ability to add them back if and when they are removed.

**Comment by Hamulus** [comment]
@damieng 
I understand that it is your policy to not add experimental features
but maybe you can give some hint how to disable direct write in code, so I would make the change and then assemble Atom myself?
generally Direct Write disabling is possible in all versions of Chrominum including the latest
for example Cent Browser
https://www.centbrowser.com/
always uses the last version of Chrominum but have option to disable direct write, so this is one of main reasons why people choose it: they keep their eyes:)

**Comment by damieng** [comment]
Atom is built on Electron which takes care of all our interop with Chromium.  If Electron supports it or can take a command line switch for it then Atom could do it - but we do not have any control outside of what Electron offers.
