### ISSUE TITLE
Toggle Comments partially comments sections of code if nested comment exists 

### ISSUE THREAD

**Issue by theaccordance** [atom/atom#11915]
### Description

When highlighting a section of markup code that already contains a commented-out line, Atom's Toggle Comments feature doesn't adequately update the selection, resulting in the selection being partially commented out.  

Markup text when selected, before applying Toggle Comments: 
![screen shot 2016-06-06 at 4 32 06 pm](https://cloud.githubusercontent.com/assets/1813001/15838979/78bf7e02-2c06-11e6-8694-3fc74878ba7f.png)

Markup text after applying Toggle Comments:
![screen shot 2016-06-06 at 4 32 57 pm](https://cloud.githubusercontent.com/assets/1813001/15838997/8e347206-2c06-11e6-97ad-5e2b676090a0.png)
### Steps to Reproduce
1. Highlight a selection of markup that already has a comment.
2. Edit -> Toggle Comments (or key combo if you prefer)

**Expected behavior:** The highlighted section in it's entirety should be commented out.  

**Actual behavior:**  The selection is partially commented out.  
### Versions

Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by theaccordance** [comment]
Additionally, here's how Toggle Comments works in Webstorm:

Highlighted text before Toggle Comments:
![screen shot 2016-06-06 at 4 56 58 pm](https://cloud.githubusercontent.com/assets/1813001/15839288/28f3bd96-2c08-11e6-9269-2220717723aa.png)

Text after ToggleComments: 
![screen shot 2016-06-06 at 4 57 21 pm](https://cloud.githubusercontent.com/assets/1813001/15839304/3fadee08-2c08-11e6-8259-eb4027fa0100.png)

**Comment by jonyeezs** [comment]
Hmm i have a feeling it is expected.
If you look at the actual command, it says "toggle-line-comments"
It may only work for single lines, instead of a block of codes.

**Comment by theaccordance** [comment]
One man's bug is another man's enhancement?

**Comment by theaccordance** [comment]
Okay, I just installed Sublime Text and Atom's toggle comment feature mirrors that of Sublime's.  I'm probably just spoiled with features from a mature, paid product, but I would still ask that the Atom team to consider this as an enhancement; it would only improve the intuitiveness of the application and the overall experience.

**Comment by 50Wliu** [comment]
This is extremely difficult to implement because Atom has no knowledge that HTML doesn't allow nested comments.  Even if it did, it would also need to know what to do with the nested comment.

I suppose this is possible with the addition of further scoped-grammar rules though.

**Comment by theaccordance** [comment]
The screenshots from Webstorm in the comments show how to address the nested comment situation.  From a on-paper perspective, it looks pretty straight forward:
- Parse each line of the selection block
  - If line contains a comment, escape the comment
- Wrap each line in a comment block

As far as implementation, extremely sounds a bit exaggerated; if Atom wasn't a mixture of JS & CS I would dive in myself

**Comment by 50Wliu** [comment]
Yeah, I realized as I was typing out my comment that it would be easier than I initially thought.  Forgot to remove it though :P.
