### ISSUE TITLE
atom rails partial click

### ISSUE THREAD

**Issue by saroar** [atom/atom#11914]
is anybody know about rails click partial like 
rails partials as link after click go to partial file path  atom
thanks

**Comment by 50Wliu** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
