### ISSUE TITLE
My . are replaced by >

### ISSUE THREAD

**Issue by marcqw** [atom/atom#11917]
Hello (pardon my french)

I use last Atom release for Linux on Ubuntu.

On HTML page when I press SHIFT + ;. (for dots) it prints >

Could you help me please ?

**Comment by Nikki1993** [comment]
Do you happen to have html-autoclose package installed?

**Comment by arcticicestudio** [comment]
May also be a problem with your system setup, you can check your current keymap with `localectl status`.
Also, if you're running Ubuntu on a MacBook/MacBook Pro, there's a problem with the ISO layout which results in switching some keys like `<>` with `|`.
