### ISSUE TITLE
Update and packaged install failed. version 1.8.0 Windows 7 64bit

### ISSUE THREAD

**Issue by QuantumBitsIT** [atom/atom#11928]
![capture](https://cloud.githubusercontent.com/assets/16469808/15877766/cd6d5824-2cca-11e6-99b3-d0499045eea0.JPG)
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

[Description of the bug or feature]
### Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by beachd80** [comment]
I tried many ways but could not update Atom or install packages that I need.

**Comment by damieng** [comment]
Can you click 'Show output' so we can get some detail on what's going wrong?

**Comment by beachd80** [comment]
Here is the output details:

Fetching outdated packages and themes failed.Hide output…
Request for package information failed: connect ETIMEDOUT
Fetching outdated packages and themes failed.Hide output…
Request for package information failed: connect ETIMEDOUT

**Comment by 50Wliu** [comment]
Are you behind a proxy @beachd80?

**Comment by beachd80** [comment]
I don't think so, I have tried with different connections and it appears the same.

**Comment by seanmars** [comment]
i got the some problem

Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
PS C:\Users\Mars> apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python
git 2.9.2.windows.1
visual studio

**Comment by damieng** [comment]
Are you on a corporate network?  Do you know if your machine normally uses a proxy server?

**Comment by dschmidthawk** [comment]
I've got the same issue using portable. Windows 10. Atom Portable version 1.9.9 (just downloaded from github so I could use without installing to my C: ssd)
I'm not behind a proxy and this is not a corporate server. Same error repeated twice as shown in @beachd80 's box above.

**Comment by dschmidthawk** [comment]
any word on this? Just checking.

**Comment by dschmidthawk** [comment]
This solved it for me:  Can't get Atom pass through a firewall #10357

**Comment by damieng** [comment]
@beachd80 Can you confirm if you still have the problem?  If so are you running a firewall? If so does permitting node.exe to access the network resolve the problem?

**Comment by damieng** [comment]
No response.
