### ISSUE TITLE
Developer Tools splits source files if space in user name on Windows

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#11923]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

It seems that the Developer Tools has major issues determining the proper paths to files on Windows when the logged in user account has a space in their folder name. See the Actual behavior section for details.

I'm sure this bug has to have been reported before, but I couldn't find it when searching.

### Steps to Reproduce

1. Log into a user with a space in their user folder name (`C:\Users\Landon Abney\`)
2. Open Developer Tools

**Expected behavior:**
All files are correctly identified to their proper location, meaning _all_ package files are identified and shown properly in the Source tree.

**Actual behavior:**

Files that are recognized as under the `file://` domain are split between `C:\Users\User Name\` and `C:\Users\User%20Name\`.

![image](https://cloud.githubusercontent.com/assets/427137/15867853/f6bb0b12-2c99-11e6-9b4b-01e6b20e9a5f.png)
![image](https://cloud.githubusercontent.com/assets/427137/15867871/108ab6c8-2c9a-11e6-8b66-316d1564aab7.png)

The files under `file://C:/Users/Landon%20Abney/` also exhibit the odd behavior that the path is duplicated, but a few package's path's aren't:

![image](https://cloud.githubusercontent.com/assets/427137/15868263/f29ca048-2c9b-11e6-87e6-27d11e8beff8.png)

While many files are only listed under the `(no domain)` categorization.

One group of these are shown as `/C:/Users/Landon%20Abney/.atom/packages/...`:
![image](https://cloud.githubusercontent.com/assets/427137/15867942/556b99f6-2c9a-11e6-814a-5b19323f585c.png)

The majority of files are shown as `C:\Users\Landon Abney\.atom\packages`:
![image](https://cloud.githubusercontent.com/assets/427137/15867998/92d16fe6-2c9a-11e6-9dca-b113a7f3e618.png)

I would expect _all_ of these files to be recognized as coming from the same folder, and shown properly in the Source tree. Often when working on a package the source file isn't listed under the `file://` domain, and I have to hunt through the huge list of `(no domain)` files, if it's even listed there.

### Versions

OS: Windows 10 x64 Enterprise

`atom --version`:

```text
Atom    : 1.9.0-beta0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

`apm --version`:

```text
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.4.windows.1
visual studio 2015
```

Note that I've seen this since before Atom hit 1.0 till current, so it's been a long standing issue.

**Comment by Arcanemagus** [comment]
It looks like, of the files in the `file://` section, the ones under `Landon%20Abney` are all "native" files (`.js`, `.html`, `.woff`), while the ones under `Landon Abney` are transpiled (`.coffee`).

**Comment by Arcanemagus** [comment]
Just a *bump* to say that this is still an (annoying) issue on v1.11.0-beta5:
![image](https://cloud.githubusercontent.com/assets/427137/18854327/6d06f4d6-83ff-11e6-95ce-adbc8377b859.png)

**Comment by damieng** [comment]
We now compile our coffeescript files with embedded source maps so this should be a lot better https://github.com/atom/atom/commit/fd1e0605926a471f7192b71a0ef12bbab0655405

**Comment by damieng** [comment]
Please feel free to comment if this issue still occurs in master or in 1.12 if you are reading this in the future.

**Comment by Arcanemagus** [comment]
I'm still seeing issues with this in Atom v12.0-beta5 btw.

![image](https://cloud.githubusercontent.com/assets/427137/19873773/295ee154-9f7e-11e6-930e-d125be949930.png)
As you can see, paths are all over the place, with files even being listed twice!

Issues shown here:

- Two different folders for my user: `Landon%20Abney` and `Landon Abney`
- `main.js` shows twice, this potentially deserves a separate issue as one (the "second" in the list) is the transpiled file, while the other (highlighted) is the source file. If you click on the transpiled file it does warn that a source map is detected, but leaves it up to the user to know where the source file is. Notw where it thinks this file is located here:
![image](https://cloud.githubusercontent.com/assets/427137/19873796/46e0cd0a-9f7e-11e6-8c1c-4a4c69749bb7.png)

Note that none of these are CoffeeScript files, but they _are_ transpiled.

**Comment by Arcanemagus** [comment]
It looks like this is at least partially a duplicate of #6553, with some unique information here.
