### ISSUE TITLE
Words are automatically being converted to lowercase

### ISSUE THREAD

**Issue by halhenke** [atom/atom#11924]
### Words are automatically being converted to lowercase

This first happened on Windows about a month ago - thought it was a Windows specific issue. Suddenly started happening on OS X this weekend.

It doesn't happen in Safe Mode. I uninstalled `atom-ctags` and it still happened. Disabled most of the autocomplete plugins and it still happened

### Steps to Reproduce

Think this GIF tells the story
- Basically I am trying to Capitalize a word
- As soon as I capitalize the word "Making" autocomplete seems to kick in and replace it with the lowercase version
- It seems I can make other characters uppercase - just not the first character

![](https://s3-ap-southeast-2.amazonaws.com/hal-henke/GitHub/lowercase.gif)

Sorry to put this here since i know its prob a problem with some sub-package but i've tried disabling all I could think of (uninstalled `atom-ctags` as mentioned) with no change.

### Versions

OS X 10.11.5

➜  atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
➜  apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.3

**Comment by 50Wliu** [comment]
You can try using the [package-cop](https://atom.io/packages/package-cop) package to determine which one of your packages is causing the issue.
