### ISSUE TITLE
Missing scrollbars in project search on OS X in fullscreen-mode

### ISSUE THREAD

**Issue by valnub** [atom/atom#11927]
When I use project search (Shift+CMD+F) and get a lot of results that can be scrolled through, I see no scrollbar on the right side which means I never know at which scroll position I am nor can I make a guess how long the result set is.

Is it just me or is this a bug?

---

**Update:** I just noticed that this problem only occurs when I go fullscreen with Atom. In windowed mode I see scroll bars.

Here is a video of the issue: https://youtu.be/0P3mpwp6v6w

Using Atom 1.8.0 on OS X El Capitan 10.11.5

**Comment by adamreisnz** [comment]
I've tried to reproduce this but am unable to. Have tested in full screen mode, using Atom 1.15.0-dev-8b36693 on OS X 10.11.5.

The scroll bar is not initially visible (as per my OS X settings), but once I scroll with the touchpad/mouse wheel, the scroll bar appears and show the correct scroll position.

@valnub have you tested this with modified OS X settings (under *General*)?

![image](https://cloud.githubusercontent.com/assets/490562/22400771/1ef472ec-e623-11e6-9043-b3c3c24a3454.png)

**Comment by valnub** [comment]
@adamreisnz Hi, yes it still occurs in current Atom version, however when I switch settings to "When scrolling" the problem disappears. So, it only occurs when set to auto.

**Comment by adamreisnz** [comment]
Is that with a mouse? I still can't reproduce it on Auto setting with a trackpad.

**Comment by valnub** [comment]
@adamreisnz I am using the Apple Magic Mouse. Also, I'm on a Macbook Pro in clamshell mode with 2 external displays attached to it.

Atom version is 1.13.1
MacOS version is 10.12.3

**Comment by valnub** [comment]
@adamreisnz Very weird, now using "When scrolling" setting won't do the trick anymore. Only if I set scroll setting to "always" it will show the scrollbar.

**Comment by adamreisnz** [comment]
I'll check when I'm back at work tomorrow using clamshell mode. That combination of that and full screen might be what's causing this.

**Comment by adamreisnz** [comment]
@valnub I've tried with clamshell mode now, but am afraid I still can't reproduce it. Is it possible you have some 3rd party applications installed that might be interfering with the scrollbars?

**Comment by valnub** [comment]
@adamreisnz Nope, I don't have anything installed related to scrolling. I noticed that you're using a more recent version of Atom and also an older version of macOS. Maybe the problem does not occur in this combination?

**Comment by valnub** [comment]
Ps. I also noticed that the problem currently also occurs when in windowed mode, so it's not fullscreen-only

**Comment by adamreisnz** [comment]
@valnub yep that's possible. I have a new version of OS X at home, but it's on my iMac so can't test that with clamshell mode. However, I'll have another look to see if I can reproduce with the latest Atom there.

**Comment by valnub** [comment]
@adamreisnz thanks a lot for your effort!!

**Comment by adamreisnz** [comment]
@valnub retested on OS X 10.12.2 with Atom 1.15.0-dev-623caaf, but scrollbars still appear correctly, regardless of scrollbar setting in OS X. Looks like the issue you're having might somehow be related to your specific setup :(

**Comment by valnub** [comment]
@adamreisnz Thanks for checking back! If noone else has this issue then yes, seems like this is the case although I wouldn't know what or why my setup differs from others.

I suggest to keep this ticket open for a while and see if anyone else reports the same issue. If not, it could be closed then.
