### ISSUE TITLE
Can't select or position single spaces, but only in tab size steps

### ISSUE THREAD

**Issue by mxmlnkn** [atom/atom#11920]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Can't select or position single spaces, but only in tab size steps

### Steps to Reproduce

1. Press tab [inserts 4 spaces]
2. Pres left arrow 2x or click with mouse after 2 spaces

**Expected behavior:** [What you expected to happen]
I want the cursor to be after the second space

**Actual behavior:** [What actually happened]
Cursor is either at position 1 or 5, but I can't go inbetween

I want to be able to insert 4 spaces with the tab key, but I don't want enforced tab grouping for navigation, I want a plain simple space-wise stepping, positioning, selecting if there are spaces. I couldn't find any option for that. I tried setting tab size to 1, but then inserting 4 tabs with tab doesn't work anymore.

### Versions

Atom 1.8.0 Debian sid

**Comment by 50Wliu** [comment]
You can disable the "grouped tabs" by disabling the "Atomic Soft Tabs" option in Atom's editor settings.

**Comment by mxmlnkn** [comment]
Edit->Preferences->Settings->Uncheck 'Soft Tabs'. I don't see any different behavior whether it is checked or unchecked, even with restarts inbetween in the follwing `spaces.txt`

       test
        test
    test  test
    test    test
    test

All except the second line works like I expect it to, only the second line, no matter whether `Soft Tabs` is checked or not, no matter whether Tab Type is auto,soft or hard, behaves like one single character, i.e. skipping 4 spaces at once when pressing left-arrow.

**Comment by 50Wliu** [comment]
I specified the "Atomic Soft Tabs" option, **not** the "Soft Tabs" option.
