### ISSUE TITLE
PHP comment code highlighting issue

### ISSUE THREAD

**Issue by naumz** [atom/atom#11931]
Hi,

First time posting here, please excuse any improper formatting.

I recently started using Atom for editing PHP code, and I ran into this potential issue almost immediately. When a PHP multi-line comment goes over a PHP environment tag, Atom appears to malfunction. It ignores the comment in the new PHP environment (and, in my instance, commented out all the javascript code subsequent to closing the comment as well). Additionally, all subsequent PHP code appears in italics.

I tried changing the grammar to HTML from PHP and it fixes the comment issue but, of course, the PHP code is not colored so it doesn't serve the purpose.

![atom-bug](https://cloud.githubusercontent.com/assets/4783847/15883286/a4f8d108-2cfb-11e6-8c63-4789917682ec.png)

**Comment by hultberg** [comment]
Hello, and welcome to the atom project! This issue is related to the PHP programming language, and should be filed in the [atom/language-php](https://github.com/atom/language-php) repository instead.

**Comment by 50Wliu** [comment]
Thanks @hultberg.
