### ISSUE TITLE
Windows 10 x64 can not move file to trash

### ISSUE THREAD

**Issue by yassersharaf** [atom/atom#11934]
Atom version 1.8 on Windows 10 x64 "The following file couldn't be moved to trash" while deleting a file from tree view

**Comment by tjgerot** [comment]
I have experienced that same issue on multiple computers running Windows 10

**Comment by Ben3eeE** [comment]
Are you deleting from a virtual or network drive or with the recycle bin disabled? Then this is a duplicate of https://github.com/atom/tree-view/issues/856

**Comment by 50Wliu** [comment]
Closing in favor of atom/tree-view#856.

**Comment by yassersharaf** [comment]
Recycle bin is enabled and i'm deleting project files from D:\XAMPP\htdocs folder
what is the correct answer please?
