### ISSUE TITLE
MSI installer starts and then disappears Windows 7

### ISSUE THREAD

**Issue by amaltson** [atom/atom#11938]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When I try installing using the MSI fir Atom 1.8 (which became available since #11087), I find that the installation starts and then disappears. No error message. See the GIF below.

![atom-msi-not-installing](https://cloud.githubusercontent.com/assets/167443/15906427/d540562a-2d86-11e6-932c-fef29fd72eaa.gif)

### Steps to Reproduce

1. Download 1.8 MSI
2. Double click to start installation.
3. Installation disappears.

**Expected behavior:** Expect the installation to start.

**Actual behavior:** Installation disappears and Atom is never installed.

### Versions

[Atom 1.8 MSI download](https://github.com/atom/atom/releases/download/v1.8.0/AtomSetup.msi) on Windows 7 Enterprise.

**Comment by paulcbetts** [comment]
Log off and log on again and it will ✨ Magically ✨ appear!

**Comment by amaltson** [comment]
@paulcbetts unfortunately that doesn't seem to be the case. I've logged off, also tried to restart the machine. No Atom for me 😞 .

**Comment by paulcbetts** [comment]
Does the normal installer work on your machine?

**Comment by amaltson** [comment]
@paulcbetts it does, but it installs into my profile and I'm trying to set this up globally on the box. It's a template that gets rolled out to lots of users.

**Comment by paulcbetts** [comment]
@amaltson You should read this article about Slack's MSI (which uses the same technology) - https://get.slack.help/hc/en-us/articles/212475728-Deploying-Slack-via-Microsoft-Installer; the app will still get installed into the profile, just on login.

Can you try the following:

1. Uninstall Atom
1. Delete `%LocalAppData%\Atom` completely
1. Install the MSI
1. Log out / log back in

**Comment by damieng** [comment]
Oh yes, step 2 is important. In order that it doesn't auto-install for users that have uninstalled it it won't reinstall if that folder is present (even if empty)

**Comment by amaltson** [comment]
@paulcbetts @damieng So I see something in `C:\Program Files (x86)\Atom Installer`... when I run it it creates an atom folder in `%LocalAppData%\Atom`. Is that the expected behaviour? That's not really a System install per say...

**Comment by paulcbetts** [comment]
@amaltson This is expected behavior. The MSI file's goal is to install the app for all users on the system, and it does it!

**Comment by damieng** [comment]
@amaltson You can't really have a 'system install' in the traditional sense as multiple people using the same install of atom would interfere with each other thanks to package installations and automated upgrades (plus sometimes those are incompatible)

**Comment by amaltson** [comment]
@paulcbetts @damieng as you both said, it does actually end up installing Atom, but it takes a few minutes after you log back into the system. I ended up removing all instances of Atom, running the MSI again and then waiting after logging back in. Sure enough, Atom got installed into my user profile after a few minutes.

Thanks again for your patience with me. This installation method by the Atom team makes perfect sense now. Thanks again.

**Comment by paulcbetts** [comment]
@amaltson No worries, the MSI is admittedly A Bit Weird but the reason it does all these backflips is so that background updates don't require UAC and can be Chrome-like

**Comment by m93a** [comment]
I've encountered this problem too -- I downloaded the latest `msi` installer on my Windows 10 and tried to "configure the Atom Machine-Wide installer". Then it crashed silently.
![obrazek](https://cloud.githubusercontent.com/assets/1671665/22654001/a529283a-ec8b-11e6-9ec1-e3741237d448.png)

I've done it multiple times, always the same. Checked `%LocalAppData%` and there was no `Atom` folder. Tried to run it in the console to see at least a log or something. The only difference was that it asked me for admin rights before "configuring the Atom Machine-Wide installer" and crashing.

**Comment by damieng** [comment]
Are you sure it crashed silently?  Because it is designed to succeed silently and I suspect you are expecting it to do something different to what it actually does.

You should run the installer once then log off. Any user logging in should now get an Atom icon on their desktop.  

The installer itself does not put a shared copy of atom anywhere, it just sets-up the regular single-user installer to automatically run when a user logs in for the first time.

**Comment by m93a** [comment]
Oh, I guess that's what happened. However are you sure this is a good design? Users tend to install software *when* they need it, so a silent requirement of relog is... well, from user's perspective a defect. If it was up to me, I'd either repair the `msi` so that it installs immediately, or NOTIFY THE USER IN BIG LETTERS, or remove the `msi` installer completely.

**Comment by damieng** [comment]
If users want to install the software they should use AtomSetup.exe

The MSI is for organizations which want to install the software for all users of a machine.  It is quite clear in the docs but I can imagine people perusing the releases page might get confused.
