### ISSUE TITLE
Opening a file fails if update is ready (Mac OS X)

### ISSUE THREAD

**Issue by palant** [atom/atom#11933]
### Description

If Atom is running and an update is downloaded and ready to be installed, opening a new file from an external application (like Finder) will fail - rather than opening that file in the existing application instance a new instance of the application starts up, without any files. Worse yet, after closing the second instance and restarting the initial one the update is not installed and has to be downloaded again.
### Steps to Reproduce
1. Install Atom 1.8.0-beta4
2. Run Atom
3. Go to Atom menu, click "Check for Update" if that menu item is present.
4. Wait for the update to be downloaded (Atom menu will show something like "Restart to install Atom 1.9.0-beta0") but don't restart Atom.
5. Run from command line: `open -a 'Atom Beta' ~/.atom/init.coffee`

**Expected behavior:** A new tab is opened in the running Atom instance, allowing to edit the Atom init script.

**Actual behavior:** A second Atom instance starts up, without any tabs. Closing that instance and restarting the initial instance won't install the update, the update has to be downloaded again instead.
### Versions

Atom 1.8.0-beta4 on Mac OS X 10.11.5. However, I've been seeing this issue at least since Atom 1.3, merely didn't realize what was causing it before now.

**Comment by leo** [comment]
Also happens for me sometimes! Sadly, I have no idea what actually causes this bug to appear...
