### ISSUE TITLE
atom -d command does not open text editing window

### ISSUE THREAD

**Issue by KiYugadgeter** [atom/atom#11936]
### Description

`atom -d` command does not open text editing window.

I attempted to execute `atom -d .` to develop package.
But Atom does not open editing window 
When executed it, There is a just atom application menu and Quit sub menu like attached picture.

![2016-06-08 20 11 21](https://cloud.githubusercontent.com/assets/7894040/15894760/a3ea1b38-2dc2-11e6-9ace-471fb4f239ca.png)
##### Expected behavior

Open Editing window with dev mode
### Versions

OS X 10.11.5
Atom 1.8.0

**Comment by stereobooster** [comment]
Try to update

Works for this setting
```
Atom    : 1.12.0-dev-ad7ce8f
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```
