### ISSUE TITLE
State Save : Reopen last file

### ISSUE THREAD

**Issue by gauravmak** [atom/atom#11947]
### Description

File's state before it was closed is not maintained when it is re-opened. Cursor is always at the beginning of the page no matter where you were last time.

### Steps to Reproduce

1. Open any file.
2. Do some work.
3. Close it
4. Reopen it with Ctrl + Shift + T

**Expected behavior:** It should take the cursor to the place where it was last when file was closed. Preferably, word.line selection, if any, should also be maintained.

**Actual behavior:** Keep the cursor at the beginning of the page

### Versions

Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by mehcode** [comment]
@gauravmak https://github.com/tmunro/remember-file-positions should do what you want

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/9437?

**Comment by thomasjo** [comment]
@Ben3eeE Good call!

Closing as duplicate of #9437.
