### ISSUE TITLE
Random highlighting

### ISSUE THREAD

**Issue by ryansmith94** [atom/atom#11945]
### Description

I don't really know how to describe the issue. As you can see in the screenshot below, Atom appears to be highlighting a lot of words, but I'm not sure how or why.

![screen shot 2016-06-09 at 08 16 59](https://cloud.githubusercontent.com/assets/3045513/15921676/df22eb64-2e1a-11e6-89b2-eb6416be3321.png)

### Steps to Reproduce

No idea, but if anyone has any suggestions for this I'm all ears.

**Expected behavior:**
No highlighting of words.

**Actual behavior:**
Lots of highlighted words.

### Versions

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3 (this seems really odd - but I doubt it contributes to this issue)
node 0.10.40
python 2.7.10
git 2.4.0

**Comment by Zireael07** [comment]
Any packages installed? What theme is it?

**Comment by ryansmith94** [comment]
Community packages are:
```
├── atom-ternjs@0.14.1
├── atom-typescript@8.10.2
├── autocomplete-haskell@0.6.5
├── docblockr@0.7.3
├── git-plus@5.14.0
├── haskell-ghc-mod@1.14.5
├── highlight-selected@0.11.2
├── ide-haskell@1.6.5
├── ide-haskell-cabal@1.4.0
├── ide-haskell-repl@0.0.23
├── js-refactor@0.6.0
├── language-dotenv@1.0.0
├── language-haskell@1.7.16
├── language-jade@0.7.1
├── linter@1.11.4
├── linter-eslint@7.2.2
├── linter-tslint@0.10.0
├── minimap-git-diff@4.3.1
├── npm-plus@0.4.0
├── project-plus@0.9.0
├── refactor@0.6.0
└── terminal-plus@0.14.5
```

UI theme and syntax theme are both "One Dark".

**Comment by ryansmith94** [comment]
Wow, just found the package that causes the problem, it's the "refactor" package. Not sure why it highlights stuff at all to be honest. Will post this issue over there at some point.
