### ISSUE TITLE
Refresh Project View

### ISSUE THREAD

**Issue by marvoh** [atom/atom#11948]
This is not a bug report but more of question on how to find my way around having just installed Atom for the first time.

I am working on a symfony project which on at the begining generates entity files when you define schema in yml files from the cli. However, I am unable to view the directory and generated files on my project view. I have tried to google, searched here and even tried to find packages that can achieve my requirement for a way to refresh the project tree view with no success. 

Can anyone point me to the right direction?

**Comment by Ben3eeE** [comment]
Questions like this are more suited for https://discuss.atom.io and will likely be answered faster if you post there instead.

**Comment by marvoh** [comment]
Thanks and sorry for not following protocol. I'll ask there.


Get Outlook for Android






On Thu, Jun 9, 2016 at 4:51 PM +0300, "Ben3eeE" <notifications@github.com> wrote:












Questions like this are more suited for https://discuss.atom.io and will likely be answered faster if you post there instead.
