### ISSUE TITLE
Cannot Uninstall Packages and Themes on Atom 1.7.4

### ISSUE THREAD

**Issue by bendacoder** [atom/atom#11940]
Hello, Atom Community and Developers!

I decided to remove a package from Atom. When I click on the "Uninstall" button in the preferences, I receive the following error . . . 

`Failed to delete <package name>: Does not exist`

This is also happening to other packages and themes that I have installed in the editor. I am using Ubuntu 16.04.

I am wondering whether or not other people are getting the same output, and how to fix it.

Thank you in advance.

**Comment by 50Wliu** [comment]
This has been fixed in the Atom 1.9.0 beta and does not actually affect package uninstallation.  In other words, it just doesn't look nice, but everything still works properly (and your package actually has been uninstalled).

**Comment by bendacoder** [comment]
Thank you!
