### ISSUE TITLE
Atom 1.9 beta 0: haskell-ide: popups never disappear

### ISSUE THREAD

**Issue by mpkh** [atom/atom#11946]
using haskell ghc-mod plugin

![capture](https://cloud.githubusercontent.com/assets/2656965/15922364/43850ed0-2e38-11e6-8cc0-b075db646551.JPG)

**Comment by joshvera** [comment]
Sounds like this was fixed in haskell-ide-1.6.6. 🎉

**Comment by mpkh** [comment]
yep
