### ISSUE TITLE
Tabs are too small

### ISSUE THREAD

**Issue by FezVrasta** [atom/atom#11954]
After the latest update the tabs act weird. The selected tab is about 20 pixels wide and I can't find any way to restore the default behavior...

```
$ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.9
git 2.6.4
```

![image](https://cloud.githubusercontent.com/assets/5382443/15957146/69c46266-2eed-11e6-9852-28b03e1251d8.png)

**Comment by nehalist** [comment]
Go to `Settings -> Themes -> Theme Settings (the wrench icon next to the UI Theme dropdown) -> Tab Sizing` and set it to "Even".

**Comment by FezVrasta** [comment]
thanks!

**Comment by WilliamIPark** [comment]
Thanks @nehalist, I was closing my tabs more often than opening them. Your solution did exactly what I was googling for.

**Comment by JeremyIglehart** [comment]
Thans @nehalist just like @WilliamIPark I was closing my tabs more often than selecting them - it was driving me nuts...

**Comment by johncadengo** [comment]
I ran into this problem too, but found that the tab size is responsive to the viewport. So leaving the setting at "Auto" and stretching out the atom editor to a larger width solved my problem in a better way than updating the setting to "Even". That way when the viewport is narrow, the tab sizes adjust accordingly.
