### ISSUE TITLE
Go To Declaration / Show In Tree View not working (Python)

### ISSUE THREAD

**Issue by muhammedabad** [atom/atom#11955]
### Description

Not sure where exactly to log this as I'm fairly new to Atom. The **Go To Declaration** feature used to work fine using the combination of `alt + cmd + g`. The only related keybindings I can see are as follows, but they don't seem to work either.

![image](https://cloud.githubusercontent.com/assets/1520135/15957236/fe26c67e-2eed-11e6-914e-3636a3d5fa24.png)

Nothing shows up in the developer tools when trying these keyboard combinations.

### Steps to Reproduce

1. Highlight /click any function or import that exists in another file in your project.
2. Press `alt + cmd + down`

### Expected behavior
The file where the function/import is located should be opened and the cursor should be placed on the line that contains the function/import.

### Actual behavior
Nothing.

### Versions

Atom: 1.8.0
OS X: 10.11.5

**Comment by muhammedabad** [comment]
Tested this in the beta version as well, same issue. Any updates ?

**Comment by lee-dohm** [comment]
@muhammedabad The functionality you're describing is part of the [symbols-view package](https://github.com/atom/symbols-view). For some functionality of symbols-view, a tags file is required. See the README on the package for a reference. Tags files are generated by [Exuberant Ctags](http://ctags.sourceforge.net/) or one of its derivatives.

I hope that helps!

**Comment by kenorb** [comment]
Related: #9034
