### ISSUE TITLE
Flag emoji is not support

### ISSUE THREAD

**Issue by bennettyuan18** [atom/atom#11964]
![screen shot 2016-06-12 at 16 09 03](https://cloud.githubusercontent.com/assets/11625453/15989914/48bd8512-30b8-11e6-95b1-f64a23e1f96a.png)

**As shown above.**
### Versions

Atom: 1.8.0
System: Mac OS X 10.11.5

**Comment by meeDamian** [comment]
Same in `Atom 1.10.2` && MacOS `10.12.1`

<img width="219" alt="screen shot 2016-10-08 at 13 29 21" src="https://cloud.githubusercontent.com/assets/526657/19211489/46fb2c02-8d5b-11e6-9537-105cdf1484e2.png">

**Comment by zanderzhng** [comment]
`Atom 1.12.8` not fixed.

**Comment by zanderzhng** [comment]
Solved, not sure which update.

**Comment by havthgem** [comment]
🎉
But, need tap delete key twice to delete it.
Or, tap delete key once, there will still has a character.
Because these emoji has two Unicode, such as flags, face with different skin color.
