### ISSUE TITLE
[idea] remap keys

### ISSUE THREAD

**Issue by trusktr** [atom/atom#11965]
What do you think of a feature like this? https://discuss.atom.io/t/is-there-a-way-to-map-keys-to-other-keys/29856

**Comment by clessg** [comment]
This would be a very useful feature. I have many uses for it.

**Comment by trusktr** [comment]
Yes, and it'd make it really easy to hack up certain shortcuts without having to know all the associated commands if you already know what the original shortcut is, similar to in vim scripting, mapping any sequence of keys to any other sequence of keys.

**Comment by lee-dohm** [comment]
Would you mind reopening this on the https://github.com/atom/atom-keymap repository? That's where this would get resolved.
