### ISSUE TITLE
[bug] Pressing spacebar inside package install search bar scrolls page.

### ISSUE THREAD

**Issue by trusktr** [atom/atom#11969]
In the install page of settings, in the search bar, typing a space causes the page to scroll which makes the search bar go out of view. I'm in 1.8.0

**Comment by 50Wliu** [comment]
This is a duplicate of atom/settings-view#767 - feel free to subscribe there for updates.

**Comment by leshniak** [comment]
[Temporary workaround](https://gist.github.com/leshniak/355780d482fb9512bfc746c4b7ca50e6) - add to your init.coffee script

**Comment by leshniak** [comment]
Ok, I started to doing sth in my init.coffee, but it doesn't work at all. However, maybe it will be useful for somebody. [[gist](https://gist.github.com/leshniak/355780d482fb9512bfc746c4b7ca50e6)]
