### ISSUE TITLE
Crash on Open - Linux 14.04, Atom 1.8.0

### ISSUE THREAD

**Issue by cfergus** [atom/atom#11977]
### Prerequisites

* [ Yes ] Can you reproduce the problem in safe mode?
* [ Yes ] Are you running the latest version of Atom?
* [ Yes ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ Yes ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ Yes ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ Yes ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

After updating a number of packages, Atom will not start. Not sure if they were due to a Chrome, Atom, or otherwise update.

There are no files in /tmp/Atom\ Crashes/

### Steps to Reproduce

1. Try to open atom

**Expected behavior:** [What you expected to happen]

Atom opens successfully, allows regular behavior.

**Actual behavior:** [What actually happened]

Window opens, showing "untitled - Atom" in the toolbar.
Alert popup says "The editor has crashed" "Please report this issue to https://github.com/atom/atom"
Option to close window, reload, keep it open.

Another variant, when trying to open:
$ atom --safe -f
App load time: 445ms
Failed to get crash dump id.
Report Id: 

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

$ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 2.9.0

$ uname -a
Linux blah-desktop 3.13.0-88-generic #135-Ubuntu SMP Wed Jun 8 21:10:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Nikki1993** [comment]
Most likely related to fontconfig update, can you install and try beta version of the atom? https://atom.io/beta it uses electron version 0.38.7 that fixes font config issue and if it works for you, most likely you will have to wait for 1.9.0 branch to become stable.

**Comment by cfergus** [comment]
Confirmed - I installed atom beta, and it opens properly.

For reference:

$ atom-beta --version
Atom    : 1.9.0-beta0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Please advise if I should update this issue in any other fashion.

**Comment by Nikki1993** [comment]
Since it's fixed with the electron update, I'd say just wait for 1.9.0 stable release.

@lee-dohm @50Wliu what do you think? (since I am not atom member not sure how to proceed from here xD)

**Comment by 50Wliu** [comment]
Since the issue has been resolved I'm closing this.
