### ISSUE TITLE
Curly bracket mismatch if string contains it

### ISSUE THREAD

**Issue by klaszlo** [atom/atom#11971]
Consider the following code in the text editor:

    var t = function() {
     var str = '{';
     if (true) {
       console.log('hmm');
     }
    };

The '}' highlighting do not find the correspondant opening bracket.

Recently I needed to find { in a string t.indexOf('{'), which is kind of rare usecase. 

atom 1.8, ubuntu linux.

**Comment by hultberg** [comment]
Assuming this is javascript, this should be reported to the [atom/language-js](https://github.com/atom/language-javascript) repo.

**Comment by 50Wliu** [comment]
This is a duplicate of atom/bracket-matcher#78 - feel free to subscribe there for updates.
