### ISSUE TITLE
Dragging a tab outside atom should open that tab in a new window.

### ISSUE THREAD

**Issue by delk0** [atom/atom#11987]
Shouldn't it? It's a cool feature i'm missing since I switched from sublime. I'm using Windows 10 btw.

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/tabs/issues/39?

**Comment by delk0** [comment]
Yep, but damn that one is old...

**Comment by 50Wliu** [comment]
Closing as a duplicate of atom/tabs#39 - feel free to subscribe there for updates.
