### ISSUE TITLE
the editor has crashed

### ISSUE THREAD

**Issue by zyl54586** [atom/atom#11992]
I opened a 100MB file, the editor display "atom will be unresponsive during the loading of very large files", then I clicked "proceed", the editor display "the editor has crashed"

**Comment by trusktr** [comment]
Tracking all these large-file issues in #12065.

**Comment by Zireael07** [comment]
"Large file" != "long line". And there's already an issue for large files.

**Comment by mnquintana** [comment]
This seems like a duplicate of https://github.com/atom/atom/issues/8864 – let's keep the discussion going there.

**Comment by krabbypattified** [comment]
Hello from issue #12065. Atom Beta should fix this for many people.
