### ISSUE TITLE
Pasting code with a comment block indents the pasted code too much

### ISSUE THREAD

**Issue by adamreisnz** [atom/atom#11995]
Pasting code which contains a comment block, e.g.:

``` js
  /**
   * Comment
   */
```

is no longer being indented properly after pasting. Observe:

![ss](https://www.dropbox.com/s/uu8x9ugikvbkwis/comment%20indentation%20on%20paste.gif?dl=1)

Without the comment block:

![ss](https://www.dropbox.com/s/jcdaco4vyzabq7g/comment%20indentation%20on%20paste%202.gif?dl=1)

So the code is being indented one level too much.

Probably related to: https://github.com/atom/atom/issues/5362
Possibly also related to https://github.com/atom/atom/issues/7256, see comments about indentation @ https://github.com/atom/atom/issues/7256#issuecomment-224580507

Can we scoop up all these comment-block related issues and fix them up for one of the next Atom releases?

Atom version is 1.10.0-dev-f6e87b1.
I don't recall this being a problem in 1.9.x.

**Comment by adambuczynski** [comment]
HTML also seems to be affected by a similar bug:

![ss](https://www.dropbox.com/s/m5a5y4nfj84ii7n/pasting%20html.gif?dl=1)

The second and subsequent lines of the HTML get indented one level too much.

**Comment by hultberg** [comment]
I have observed this in PHP too, thanks for creating this issue!

**Comment by michaelchadwick** [comment]
I swear this is something I've seen as a bug in lots of places where you paste text, but now we all have a chance to fix it!

**Comment by adamreisnz** [comment]
Don't get your hopes up... I've raised this issue more than a year ago, and similar ones as well. They don't have a high priority for fixing it seems.

**Comment by adamreisnz** [comment]
This seems to have gotten fixed now, closing this.
