### ISSUE TITLE
Can't type national characters in atom due to default keybindings

### ISSUE THREAD

**Issue by ikurek** [atom/atom#12005]
I really love atom, but I can't get past default keybindings on some keyboard combinations. 

For example:
```
"alt-o" should make "ó", but it opens folder menu
"alt-z" should make "ż", but it doesn't work

```
I tried to bypass this using keymap file:

```
'.workspace .editor':
  'ctrl-alt-o': 'unset!'
  'ctrl-alt-z': 'unset!'

```
But it doesn't work. How can I fix it?

**Comment by Ben3eeE** [comment]
Did your try the keyboard-localization package?
More information here https://discuss.atom.io/t/im-using-an-international-keyboard-and-keys-that-use-altgr-or-ctrl-alt-arent-working/21719

**Comment by ikurek** [comment]
Thanks, I didn't see that package before. Works like a charm.

**Comment by wholubowski81** [comment]
Because keyboard-localization is deprecated I suggest try this:
 'atom-text-editor':
  'ctrl-alt-o': 'native!'
in keymap.cson
