### ISSUE TITLE
Question: Every click starts a selection even though I'm not holding the left button

### ISSUE THREAD

**Issue by jcalfee** [atom/atom#12017]
Is this a feature of Atom?  I'm using Ubuntu and everything else appears fine.  Every time I left click (and release) it starts a new selection.  I have tried an alternate mouse, and restarting the editor.  It is really stuck.  I did want to write this incase it is a feature, in that case it needs a better way `out` ...

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/11691?

**Comment by jcalfee** [comment]
I did a reboot and at least the editor is usable again.  If you have any questions please let me know.  You can close the ticket I'll follow the other ticket...

**Comment by jcalfee** [comment]
thank you

**Comment by 50Wliu** [comment]
Closing in favor of #11691.
