### ISSUE TITLE
Typing enter before a closing bracket results in wrong indentation on new line

### ISSUE THREAD

**Issue by adambuczynski** [atom/atom#12013]
See example:

![ss](https://www.dropbox.com/s/ydrj3pjiofafwec/wrong%20indentation%20with%20closing%20bracket.gif?dl=1)

When you press `enter` with the cursor positioned just before the closing bracket, the indentation of the new line is one unit off.

This is on Atom 1.10.0-dev-e5a3c9e, OS X 10.11.5.

**Comment by InvisibleRedInk** [comment]
This is a bit obvious, but can you recheck if there is any opening bracket before, and also could you put some of the code (or a sample) which has this behavior?

**Comment by adambuczynski** [comment]
@InvisibleRedInk sorry, I thought it was obvious from the screen grab.

The simplest example with a closing bracket will work to reproduce this:

```js
    //)
    if (this.date) {
```

Place cursor between the comment slashes and the closing bracket and hit enter. It will move the closing bracket to this position:

```js
    //
  )
    if (this.date) {
```

There is no opening bracket on the line above or anything.

**Comment by 50Wliu** [comment]
Auto-indentation behavior is controlled by language packages, so please reopen this issue on whatever language you're having the issue on.

**Comment by adambuczynski** [comment]
@50Wliu it's happening in at least both javascript and typescript, possibly other languages are affected as well. Should I raise the issue for all affected languages?

**Comment by 50Wliu** [comment]
Yup.

**Comment by InvisibleRedInk** [comment]
Also happens in C++ (.cpp) but not in Java (.java) files.
