### ISSUE TITLE
indent on paste

### ISSUE THREAD

**Issue by Mencey0** [atom/atom#12015]
Code:
![atom1](https://cloud.githubusercontent.com/assets/4997735/16226729/7edc6d80-37b5-11e6-9e01-2672ac146d82.png)

Action 1:
![atom2](https://cloud.githubusercontent.com/assets/4997735/16226602/e740caca-37b4-11e6-812b-49458a2877af.png)

Action 2:
![atom3](https://cloud.githubusercontent.com/assets/4997735/16226609/edb5eca0-37b4-11e6-85aa-54b886d9786b.png)

Result:
![atom4](https://cloud.githubusercontent.com/assets/4997735/16226705/603a5338-37b5-11e6-8c02-28001e37dd82.png)

I want:
![atom5](https://cloud.githubusercontent.com/assets/4997735/16226668/30ce889e-37b5-11e6-80bc-840986a945c8.png)

**Comment by hultberg** [comment]
Might be related/duplicate to #11995

**Comment by unluisco** [comment]
Auto Indent is broke with the last update
see this:

![](https://j.gifs.com/n59ngW.gif)

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/atom/atom/issues/4461. You may want to subscribe there for updates.
