### ISSUE TITLE
"\%" as error in C code

### ISSUE THREAD

**Issue by dhbmarcos** [atom/atom#12011]
### Description

A `\%` string using in `format` of `printf`, `scanf`, etc, not show as special character. However, In code its is formatted as error (red backgroud using dark theme).

### Steps to Reproduce

1. Create new file;
2. select grammar for C
3. type `"\%"`

**Expected behavior:** I expected format as color of a special character, like `\0`

**Actual behavior:** The character is formatted as error, like when type `*/` without `/*`

### Versions

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11+
git 2.7.4
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

**Comment by 50Wliu** [comment]
Please create a new issue for this on the [atom/language-c](https://github.com/atom/language-c) repo.  Thanks!
