### ISSUE TITLE
Consider changing the TextEditor documentation

### ISSUE THREAD

**Issue by DamnedScholar** [atom/atom#12022]
[The documentation](https://atom.io/docs/api/v1.8.0/TextEditor) for the TextEditor class includes a very mischievous example that has the effect of writing in all open TextEditors at the same time. Since this is unlikely to be the first thing a user wants to do with this class, and possibly results in some very tedious cleanup, the example should probably be changed so that the example selects only the active editor.

**Comment by lee-dohm** [comment]
While I agree that the specific example isn't something that people would want in their `init.coffee`, the example is intended to illustrate the use of `atom.workspace.observeTextEditors` which is something that people often have a need for. And it illustrates it in a very obvious way :grinning:

If you have a suggestion for a better example for `atom.workspace.observeTextEditors`, please let us know. I'd be happy to update the docs or help you with the process.
