### ISSUE TITLE
JavaScript API documentation is missing (at least) the notification options for buttons.

### ISSUE THREAD

**Issue by kminehart** [atom/atom#12021]
### Description

JavaScript API documentation is missing (at least) the notification options for buttons.

I'm not sure what else it's missing.

I can write:

```JavaScript
let notification = atom.notifications.addError('Set up your docker variables!', { buttons: [
    {
       text: 'myButton',
       onDidClick: (e) => {
     }
   }
]});
```

yet that is nowhere to be found in the docs [here](https://atom.io/docs/api/v1.8.0/NotificationManager#instance-addError).

### Versions

"latest" according to the API doc page.

**Comment by 50Wliu** [comment]
Closing in favor of atom/notifications#126.  See #11942 for the PR documenting all the current Notification options.
