### ISSUE TITLE
Atom only opens one tab when clicking on files in tree view

### ISSUE THREAD

**Issue by rickgregory** [atom/atom#12026]
Ever since 1.0 Atom, when I open a file by clicking it in the project tree it opens a tab for that file. If I click a second file, it opens a new tab with the contents of the file (and thus I have two tabs, one for each file I've clicked on). 

In 1.80, this does not happen. If I click on a file it opens the contents of that file in a tab. If I click on a second file, the contents of that file appear in the same tab, closing the first file. 

Steps: 
1) Open a project with 2 or more editable files. 
2) click on a file to open it. It appears in a newly created tab. 
3) Click on another file. 

Actual - the contents of the second file  open in the very same tab, replacing the first file. The tab title changes too. 

Expected - A new, second, tab opens alongside the first tab and this continues whenever I click a file in the tree view. 

More info: Atom 1.80 on Mac OS X 10.11.5. I've already 1) replaced the .atom folder (renamed it and let Atom create a new one). Downloaded and replaces my copy of Atom. 

This is a pretty fundamental change in how I interact with files. For just two files I could create panes, but that's not feasible when I have a bunch of open files.

**Comment by rickgregory** [comment]
Closing this - it's working when I have panes up so I want to investigate more. Will reopen if needed.

**Comment by thomasjo** [comment]
This is the *pending pane items* feature. Check out http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html#pending-pane-items.

**Comment by jcalfee** [comment]
I disagree, I think this is a valid bug.  Pending Pane Items should be off.  It catches the user by surprise and interferes with their work flow by constantly loosing files.  it is not intuitive that you need to double click to keep your files now.  Consider that you have over a 1000 issues now making stuff like this hard to find.  Please make it non-intrusive.  Thank you.
