### ISSUE TITLE
*Atom 1.8.0* Still not able to use Atom as commit message editor.

### ISSUE THREAD

**Issue by eivinfu** [atom/atom#12027]
After adding atom as commit editor using: 

git config --global core.editor "'C:\Users\Eivind\AppData\Local\atom\app-1.8.0\atom' -n -w"

When trying to commit (with a running instance of atom) I get the message 
"Aborting commit due to empty commit message.".
Atom still opens a new window for me to write a commit message, but doesn't wait.
It does work properly when atom is not running. But it's a pain having to close it for every commit.

This is the same problem as issue: #3074
(I thought this was resolved?)

EDIT:
If I open atom from git bash using "atom &" it will not let me use the command line, even if I close atom, I have to use "CTRL+C" to interrupt the command line and make it available again. If i open atom without "&", and then close atom, the command line becomes available as expected.

Versions:
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python
git 2.9.0.windows.1
visual studio

OS: Win10 x64
*Using git bash

PS: I am brand new to git and github, and programming on Win OS, sorry if I'm wasting your time with this and I'm just being stupid somehow.

**Comment by 50Wliu** [comment]
If you copy over the `atom.cmd` and `atom.sh` files [here](https://github.com/atom/atom/tree/master/resources/win) into `%LOCALAPPDATA%\Atom\bin`, does that fix your issue?

**Comment by eivinfu** [comment]
I copied the files to the ~/AppData/Local/Atom/bin/

No change.

**Comment by awgregory** [comment]
I am having the very same issue.  On Windows 10  HP Laptop.   Also new and learned this when taking the Git Class.   I installed the GitHub Windows App and Git was installed with that.  Should we instead be using the Git for Windows?    https://git-scm.com/downloads

**Comment by damieng** [comment]
The configuration for git is wrong - it has to go through either atom.cmd (Command Prompt/PowerShell) or atom.sh (Cygwin) - if you set it directly to the .exe then the wait logic is bypassed.

Try
```
git config --global core.editor "'%localappdata%\atom\bin\atom' -n -w"
```

**Comment by eivinfu** [comment]
After trying both the solutions offered above, I got a new error message (from both):

'OMMIT_EDITMSG' is not recognized as an internal or external command,
operable program or batch file.

Aborting commit due to empty commit message.

Not sure what this means, but it seems to be missing 'C' in 'COMMIT_EDITMSG'?

**Comment by damieng** [comment]
Are you running this from a Bash shell?  If so, which one?

**Comment by awgregory** [comment]
That's the same error message I get 'OMMIT_EDITMSG' is not recognized as an
internal or external command      The command seems to be missing the C

When this happens it seems to just get hung up on a process
I'm running the bash shell that installed with the windows app  git version
2.8.1.windows.1

**Comment by damieng** [comment]
If you're using bash then you'll definitely want to copy atom.sh from https://github.com/atom/atom/blob/master/resources/win/atom.sh over the top of %localappdata%\atom\app-1.8.0\resources\cli

**Comment by awgregory** [comment]
@damieng I copied and pasted the code from the atom.sh file in the link you provided above and that seems to be working for me (hopefully it stays) so thanks.  Newbie questions if I may:

Can I install the more feature rich git for windows version [here](https://git-scm.com/download/win) without causing any more atom issues and if yes must I uninstall the current git I have first?

Is it possible to download individual file from repo, such as the atom.sh file you linked me too (as opposed to copy and paste into old file like I did)?  When I click on 'raw' in the file and right-click save as from the browser, windows saves it as a text file   atom.sh.txt   I just want to download as a regular shell file atom.sh

Thanks

**Comment by eivinfu** [comment]
I also copied 'atom.sh' to the 'cli' folder, and now it's working as expected!

Thanks alot!

**Comment by damieng** [comment]
I'll try and make sure it gets into 1.8.1

**Comment by awgregory** [comment]
sorry if my questions got off topic

**Comment by damieng** [comment]
Atom doesn't mind which git package you use - it just needs to be in the path.
