### ISSUE TITLE
Got "gyp ERR" When Install Plugins After Update Linux Kernel

### ISSUE THREAD

**Issue by EAimTY** [atom/atom#12023]
I got an error when I install plugins for atom after compile and install Linux Kernel4.6.2

![ERROR](https://cloud.githubusercontent.com/assets/13065214/16252950/106d203c-3865-11e6-8234-8bbecd90f329.png)

I am using Atom 1.8.0 on Debian8. 
The way of compile and install Linux Kernel is [here](http://www.cyberciti.biz/faq/debian-ubuntu-building-installing-a-custom-linux-kernel/)
How to solve it?
Thanks!

**Comment by andyrichardson** [comment]
Seems very similar to this issue - #12044

**Comment by lee-dohm** [comment]
According to the error message, it says that you're having problems with network settings. You may want to take a look at the proxy configuration information in the [apm README](https://github.com/atom/apm).

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
