### ISSUE TITLE
Duplicated file goes to wrong path

### ISSUE THREAD

**Issue by seoker** [atom/atom#12036]
### Description

Bad path when I paste a file under a path which contains a number.

### Steps to Reproduce

1. Assume I have a file located under `/users/myuser/blablabla/v1.0/some/path/file.txt`
2. Duplciate the file onto the same folder by copying/pasting.

**Expected behavior:**
The duplicated file should put right next to the original file, i.e. `/users/myuser/blablabla/v1.0/some/path/file0.txt`

**Actual behavior:**
The duplicated file goes to `/users/myuser/blablabla/v10.0/some/path/file.txt`

### Versions
Atom : `1.8.0`
Electron : `0.36.8`
Chrome : `47.0.2526.110`
Node : `5.1.1`

apm : `1.9.2`
npm : `2.13.3`
node : `0.10.40`
python : `2.7.11`
git : `2.7.4`

OS version: `OS X El Capitan 10.11.5`

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.9.0.
