### ISSUE TITLE
atom 1.8 stable symbol error

### ISSUE THREAD

**Issue by anothergituser** [atom/atom#12033]
With atom 1.8 on fedora 22 when i type the letter "e" i get the euro symbol "€" ..
This is not an issue with atom 1.6 which i'm currently using.

**Comment by 50Wliu** [comment]
Are you using a non-US keyboard layout?

**Comment by anothergituser** [comment]
Yes, it's spanish "es" layout

**Comment by 50Wliu** [comment]
And are you using the keyboard-localization package?

**Comment by anothergituser** [comment]
Yes i am, could that be the culprit? I don't remember updating it after installing 1.8

**Comment by 50Wliu** [comment]
Ok, then I'm closing this issue in favor of #11904 - feel free to subscribe there for updates.
