### ISSUE TITLE
Invisible characters break ruby code

### ISSUE THREAD

**Issue by h-salazaro** [atom/atom#12041]
### Description

I love Atom interface and functionality, but sometimes it creates an invisible character that breaks my code. Allow me to explain. When I write this, in my tests (for example):

``` ruby
subject(:square) { Square.new } 

# ... rest of my test
```

When running the test, I get this error: 

```
syntax error, unexpected tIDENTIFIER, expecting '}' (SyntaxError)
  subject(:square) { Square.new(7) }
                                    ^
```

What I do in this cases is to **delete and rewrite the line** without using autocomplete. Sometimes it works. If that does not solve the problem, I directly rewrite the line in **vim**.

However, that **does** happens with this specific character -> **}**.

Any ideas?
### Versions

OS X 10.11.5
Atom 1.8.0
ruby 2.3.1

**Comment by lee-dohm** [comment]
I've never run into this problem with Atom. Can you reproduce the problem in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

Also, do you use a non-US English keyboard layout?

**Comment by h-salazaro** [comment]
I'm sorry for this odd problem. Neither I have been able to reproduce at will; it happens about once a week. I'll be using atom in safe mode for the next two weeks in order to be able to detect any kind of anomalies.

I'm using a spanish keyboard layout, it is called "Spanish ISO" in my preferences panel.

**Comment by lee-dohm** [comment]
I suspect it might be something to do with your keyboard layout and atom/atom-keymap#35. But definitely let us know about the results on the Safe Mode tests. I'll leave this open for now and check back with you.

**Comment by lee-dohm** [comment]
@h-salazaro Any new information?

**Comment by elmatou** [comment]
Hi everybody,

I have also this kind if issue with invisible character.
it appear with I copy/paste, some colored text from a console, or from an atom tab which output some command runned in console (think every plugin for running tasks (grunt, rake, rspec, ...)

in console colors are rendered using some "unprintable" character. I have to edit the line in 'gedit' or any text editor ()  which support these characters.

I think Atom should handle them with a special rendering (often a square) allowing users to cop/paste/delete them. pretty much as number of texteditor are doing.
![image](https://cloud.githubusercontent.com/assets/292021/20037109/51069788-a41a-11e6-86e4-ba05c55cce7b.png)
![image](https://cloud.githubusercontent.com/assets/292021/20037111/5b15fcfa-a41a-11e6-9ca5-dd5111340039.png)

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12041#issuecomment-232403930. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
