### ISSUE TITLE
apm install failed

### ISSUE THREAD

**Issue by githubmann** [atom/atom#12044]
C:\WINDOWS\system32>apm install --check
Checking for native build tools failed

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp WARN install got an error, rolling back install

C:\WINDOWS\system32>apm -v
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.12rc1
git 2.9.0.windows.1
visual studio

**Comment by githubmann** [comment]
C:\WINDOWS\system32>apm config ls
; cli configs
globalconfig = "C:\\Users\\rhb\\.atom\\.apm\\.apmrc"
user-agent = "npm/2.13.3 node/v0.10.40 win32 ia32"
userconfig = "C:\\Users\\rhb\\.atom\\.apmrc"

; userconfig C:\Users\rhb\.atom\.apmrc
GYP_MSVS_VERSION = "2015"
https-proxy = "https://9.0.2.1:0/"
msvs_version = "2015"
strict-ssl = false

; globalconfig C:\Users\rhb\.atom\.apm\.apmrc
cache = "C:\\Users\\rhb\\.atom\\.apm"

; node bin location = C:\Users\rhb\AppData\Local\atom\app-1.8.0\resources\app\apm\bin\node.exe
; cwd = C:\WINDOWS\system32
; HOME = C:\Users\rhb
; 'npm config ls -l' to show all defaults.

**Comment by githubmann** [comment]
I install vs c++ build tools 2015
Can you help me?

**Comment by andyrichardson** [comment]
I'd advise you upgrade to a newer version of node and see if the issue persists.

**Comment by githubmann** [comment]
@andyrichardson thx .I used[ Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) to replace vs2015 community ,and then fixed it.
