### ISSUE TITLE
Atom consistently complains about missing package.json

### ISSUE THREAD

**Issue by DamnedScholar** [atom/atom#12042]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Whenever I'm using dev mode and working on a file in some general directory, Atom complains bitterly every time I save something because there's not a `package.json` file. Most of the things I'm working on are text files or personal bits of code that are never going to see a package manager or somebody else's computer and have no need for version or dependency information. While I appreciate Atom's ability to access and utilize the package information, I don't think it's appropriate that it assumes that I need a `package.json` file in every single directory. The dev tools console should only pop up when there's an _actual_ error.
### Versions

```
Windows 10
Atom 1.8.0
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.2.windows.1
visual studio 2015
```

**Comment by DamnedScholar** [comment]
More information:

http://puu.sh/pF3VU/8a490bed37.png

The file is in my user folder, which is the only project folder open. Sixteen of the errors in that screenshot are the same two, generated each time I save:

```
C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\exception-reporting\lib…:25
Error reporting uncaught exception Error: Cannot find module '../package.json'(…)
(anonymous function)	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\exception-reporting\lib…:25
module.exports.Emitter.simpleDispatch	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25
module.exports.Emitter.emit	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125
(anonymous function)	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:832
module.exports.KeymapManager.dispatchCommandEvent	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-…:580
module.exports.KeymapManager.handleKeyboardEvent	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-…:388
module.exports.WindowEventHandler.handleDocumentKeyEvent	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98
(anonymous function)
```
and
```
C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:1002
Uncaught Error: Cannot find module 'C:\Users\stick\package.json'
Module._resolveFilename	@	module.js:338
Module._resolveFilename	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383
Module._load	@	module.js:289
Module.require	@	module.js:366
require	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50
module.exports.reload	@	index.coffee:19
(anonymous function)	@	index.coffee:12
module.exports.Emitter.simpleDispatch	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25
module.exports.Emitter.emit	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125
module.exports.TextBuffer.saveAs	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-bu…:1113
module.exports.TextBuffer.save	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-bu…:1083
module.exports.TextEditor.save	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:660
module.exports.Pane.saveItem	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:718
module.exports.Pane.saveActiveItem	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:701
module.exports.Workspace.saveActivePaneItem	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:684
commandRegistry.add.core:save	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\register-default-commands.js:214
module.exports.CommandRegistry.handleCommandEvent	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260
(anonymous function)	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3
module.exports.KeymapManager.dispatchCommandEvent	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-…:580
module.exports.KeymapManager.handleKeyboardEvent	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-…:388
module.exports.WindowEventHandler.handleDocumentKeyEvent	@	C:\Users\stick\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98
(anonymous function)
```

**Comment by lee-dohm** [comment]
I've never seen this error before. Can you reproduce it if you temporarily move your `~/.atom` directory somewhere else?

**Comment by DamnedScholar** [comment]
No, I can't. And it only happens in dev mode, so that would suggest one of the packages in `.atom/dev`, but I just deleted all the symlinks and there's no change.

Thanks for the tip. When I have a moment, I'll set about undoing every part of my `.atom` folder and testing to see which bit fixes the errors, then report back.

**Comment by retepaskab** [comment]
Creating a package.json with contents: {} solves the problem.
Might it be some filesystem permission issue, the user having write access to the folder, but atom not?
