### ISSUE TITLE
can not work with chinese typewriting

### ISSUE THREAD

**Issue by lenxeon** [atom/atom#12067]
just see gif 

![bug](https://cloud.githubusercontent.com/assets/251825/16436493/de93e1ce-3dd0-11e6-8569-5baab6cdbabc.gif)

**Comment by lenxeon** [comment]
![image](https://cloud.githubusercontent.com/assets/251825/16436538/2d628274-3dd1-11e6-8980-ff0184f31478.png)

**Comment by lenxeon** [comment]
work good at 1.7.4

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/atom/issues/11988?

**Comment by lenxeon** [comment]
@Ben3eeE  yes
