### ISSUE TITLE
CONTRIBUTING.md Invalid Links

### ISSUE THREAD

**Issue by dakshshah96** [atom/atom#12066]
### Description

On line 235 and line 236 of the file CONTRIBUTING.md, the links to the JavaScript style guide as well as CSS style guide are invalid.

**Expected behavior:** Links "JavaScript" and "CSS" should point to their respective style guides.

**Actual behavior:** Links "JavaScript" and "CSS" encounter a 404 not found page.

**Comment by jerone** [comment]
Noticed a while back that those styleguides where removed, don't know what's replacing them:
* https://github.com/styleguide/css
* https://github.com/styleguide/javascript

**Comment by bastilian** [comment]
I would assume that these could be replaced with those mentioned on https://github.com/styleguide, which would be http://primercss.io/ for CSS and https://github.com/styleguide/ruby for Ruby.

**Comment by bastilian** [comment]
Ruby. what am i talking about. :D (me needs more coffee). Ok, no JS styleguide found yet.

**Comment by mltroutt** [comment]
The AirBnB styleguides seem to be held in high regard, what about linking those instead?

- https://github.com/airbnb/javascript
- https://github.com/airbnb/css
