### ISSUE TITLE
Split into lines not working

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [atom/atom#12076]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

On OS X, Selection > Split into lines does not work

### Steps to Reproduce

1. [First Step]
make a sentence with multiple words
2. [Second Step]
Select the sentence
3. [and so on...]
Click on the Selection menu, then split into lines.

**Expected behavior:** [What you expected to happen]
The lines should have split into multiple rows
**Actual behavior:** [What actually happened]
Does not have any effect. 
### Versions
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by benkahle** [comment]
Split into lines doesn't split a single line of text into multiple lines, it splits a multi-line selection into multiple, single-line selections with multiple cursors. To see this behavior write a few words on multiple lines, select them, then click "split into lines". Move the cursors by using the arrow keys and you will see one cursor per line.

**Comment by Karlheinzniebuhr** [comment]
ok thanks for the answer. There seems to be no inversion of "join" then, doing the opposite of the join command. I think this would we a useful feature.
