### ISSUE TITLE
The "x" (close) button on a tab becomes active too soon.

### ISSUE THREAD

**Issue by jersten** [atom/atom#12071]
### Description

The tabs `x` button becomes active too soon; when changing between tabs I have to make sure I go far left on short names so that I do not accidentally close the tab.

### Steps to Reproduce

1. Create a file with short name; in my example `geo.go`
2. Observe mouse pointer, and when the `x` becomes active.

**Expected behavior:** The area of the `x` is too large; should be smaller.

**Actual behavior:** Because the area of the `x` is so large; I regularly accidentally close tabs on short file names.

### Versions

Atom 1.8.0
Xubuntu 16.04

### Image
The red dot is about when the `x` becomes active. ![selection_001](https://cloud.githubusercontent.com/assets/7646510/16458199/4711a018-3dec-11e6-852c-aeea14f225db.png)

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/atom/issues/11448

**Comment by jersten** [comment]
Indeed, wasn't able to find in the search.
