### ISSUE TITLE
Issue changing focus to a fullscreen Atom instance on OSX

### ISSUE THREAD

**Issue by randomPoison** [atom/atom#12073]
### Description

I have an Atom instance running in fullscreen mode and a terminal in fullscreen mode. If I use the `atom` command to open a file from the terminal the file opens but the window does not come into focus.

Some additional information is available in [the original discussion post](https://discuss.atom.io/t/issue-changing-focus-to-a-fullscreen-atom-instance-on-osx/30458), though the relevant information is reproduced here.
### Steps to Reproduce
1. Open an Atom workspace and put the window in fullscreen mode using the green button in the upper-left corner.
2. Open an terminal window and make it fullscreen as well.
3. Run the command `atom foo.txt:7` in the terminal (where `foo.txt` is an actual file).

**Expected behavior:** The file should open in the existing window and the Atom window should be in focus.

**Actual behavior:** The file is opening as expected, but the _desktop_ is in focus.
### Versions

Running on OS X 10.10.5.

output of `atom --version`:

```
Atom    : 1.9.0-beta0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

output of `apm --version`:

```
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.0
```

**Comment by lee-dohm** [comment]
I was able to reproduce this using Atom v1.10.0-dev-5533365 on Mac OS X 10.11.5.

**Comment by mvoropaiev** [comment]
same issue on macOS 10.12.3

```
$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.12.0
```

**Comment by nckslvrmn** [comment]
bump on this as i am also experiencing the same behavior with the same apm and atom and osx versions as @mvoropaiev

**Comment by nckslvrmn** [comment]
+1 this still happens on atom 1.16.0 and apm 1.16.1 as well with the exact same behavior as described. Also happens in OSX split fullscreen with half terminal half Atom FWIW

**Comment by chriswatrous** [comment]
I may have found a workaround for this problem: `atom -f`.

The help for that option says `  -f, --foreground           Keep the main process in the foreground.  [boolean]`.

I'm not sure what that option is supposed to do but it seems to eliminate this problem at least on my machine. Without this option, it always flips to "Desktop 1" when opening a file from the command line.

I have an alias in my `.bashrc`:
`alias a='atom -f'`

macOS High Sierra
Version 10.13.3

ATOM 1.24.0
fresh install
