### ISSUE TITLE
Weird border from 620px left of the all panes.

### ISSUE THREAD

**Issue by BurakTokak** [atom/atom#12087]
### Description

Unexpected border is showing ~620px left relative to every pane. There is no additional plugins or themes, also the screenshot is using the default ui and syntax coloring.

Note that there is no problem in the welcome section that the shortcut tips are showing off and the setting pane. The problem seems to be appearing in only project files like HTML.

![screenshot_23](https://cloud.githubusercontent.com/assets/5216601/16542965/870b3a26-40c6-11e6-801d-b62e1a6eb96c.png)

Also in a smaller window;

![screenshot_24](https://cloud.githubusercontent.com/assets/5216601/16542979/1c02a650-40c7-11e6-9334-b9944f31114b.png)

### Steps to Reproduce

1. Open Atom

**Expected behavior:** For Border, not to show up.

**Actual behavior:** Unexpected border is showing 620px left relative to every pane.

### Versions

Windows 7, Atom v1.8.0 (Just downloaded and installed from atom.io)

**Comment by thomasjo** [comment]
That's the wrap-guide. See https://discuss.atom.io/t/what-is-this-line-on-the-right-in-the-editor-view/18477
