### ISSUE TITLE
Korean/Ansi encoding problem

### ISSUE THREAD

**Issue by xc4patryk** [atom/atom#12083]
Hello,

When i testing the latest version encountered one problem with Ansi/Korean encoding. When i wrote Korean words atom change text to "???? ???" I was looking for a solution for all sides and I couldn't find a panacea.

e.g
`수인족에게 강함`  to  `????? ??`

I used packages:
AnsiToUTF8
Auto-encoding
Keyboard-localization

**Comment by lee-dohm** [comment]
[There is no such thing as ANSI encoding.](http://stackoverflow.com/a/701920/1954) Or, more specifically, "ANSI encoding" is so vague as to be meaningless. Do you know what encoding your file is stored in? Or what the default encoding is for your system? It is possible that Atom doesn't support that encoding, but far more likely that the correct encoding wasn't selected.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12083#issuecomment-232213628. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
