### ISSUE TITLE
Uncaught Error: Invalid text decoration iterator position: (111, 139).Buffer row 111 has length ...

### ISSUE THREAD

**Issue by chaffeqa** [atom/atom#12085]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Invalid text decoration iterator position: (111, 139).
Buffer row 111 has length 177.

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1074

Error: Invalid text decoration iterator position: (111, 139).
Buffer row 111 has length 177.
    at DisplayLayer.module.exports.DisplayLayer.getScreenLines (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:1074:19)
    at TextEditorPresenter.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1355:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1362:12)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-presenter.js:121:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:205:12)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:221:9)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:3:61
```

### Commands

```
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "excludeVcsIgnoredPaths": true,
    "projectHome": "/Users/quinnchaffee/code/sti"
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {},
    "showIndentGuide": true,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
atom-jade, v0.3.0 (active)
atom-typescript, v8.11.0 (active)
language-babel, v2.29.2 (active)
language-docker, v1.1.6 (active)
language-gradle, v0.0.3 (active)
language-haml, v0.24.0 (active)
language-nginx, v0.6.1 (active)
language-patch, v1.2.0 (active)
linter, v1.11.14 (active)
linter-pep8, v1.3.0 (active)
python-indent, v0.4.3 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lee-dohm** [comment]
Any indication as to what you were doing when this exception happened?

/cc @as-cii

**Comment by flxsource** [comment]
@lee-dohm In my case with the same error, I just partially scrolled a PHP file. Once the error has occurred, scroll stops working in that pain until I switch to another tab. Other panes continue working as normal.

This problem appeared after a couple of hours of using the file/pane normally, but now occurs ever time the pane is scrolled until I close the file and reopen it.

**Comment by as-cii** [comment]
Thanks for your feedback, @flxsource! 🙇 Could you paste the content of that file here so that we can debug this? It seems like that file is causing the PHP grammar (along with our new `DisplayLayer` abstraction) to trigger the exception you are observing, and so having the exact grammar scopes causing the issue would be invaluable. ✨

In case you don't feel like sharing the file publicly, it would be awesome if you could send it to us via e-mail (you can find mine on https://github.com/as-cii) so that we are still able to reproduce and address the problem. ⚡

**Comment by flxsource** [comment]
I've sent the offending file to you, hope it helps!

**Comment by flxsource** [comment]
As requested, the output of `apm list`

<details>
<summary>Output of `apm list`</summary>
[36mBuilt-in Atom Packages[39m (89)
├── about@1.5.0
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.29.2
├── autocomplete-snippets@1.10.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.39.0
├── bracket-matcher@0.82.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.38.0
├── find-and-replace@0.199.0
├── fuzzy-finder@1.0.5
├── git-diff@1.0.1
├── go-to-line@0.30.0
├── grammar-selector@0.48.1
├── image-view@0.57.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.51.3
├── language-clojure@0.20.0
├── language-coffee-script@0.46.1
├── language-csharp@0.12.1
├── language-css@0.36.1
├── language-gfm@0.85.0
├── language-git@0.12.1
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.110.0
├── language-json@0.18.0
├── language-less@0.29.3
├── language-make@0.21.1
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.34.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.43.1
├── language-ruby@0.68.5
├── language-ruby-on-rails@0.25.0
├── language-sass@0.46.0
├── language-shellscript@0.21.1
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.1
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.4
├── language-yaml@0.25.2
├── line-ending-selector@0.4.1
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.63.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.3.1
├── one-light-syntax@1.2.0
├── one-light-ui@1.3.1
├── open-on-github@1.0.1
├── package-generator@1.0.0
├── settings-view@0.235.1
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.2.3
├── styleguide@0.45.2
├── symbols-view@0.112.0
├── tabs@0.96.0
├── timecop@0.33.1
├── tree-view@0.205.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

[36mCommunity Packages (5)[39m /Users/adam/.atom/packages
├── autocomplete-emojis@2.5.0
├── git-plus@5.16.2
├── linter@1.11.14
├── linter-scss-lint@3.0.4
└── project-plus@0.9.0

└── (empty)

</details>

**Comment by flxsource** [comment]
It's worth mentioning that most of the time it's fine - managed to work with that file for the rest of the day yesterday without a problem, although some days it occurs 3 or 4 times.

**Comment by as-cii** [comment]
Does it happen after you change the file? If so, can you help us tracking down which kind of edit triggers the exception? My sense is that, somehow, either the grammar or `DisplayLayer` get confused with a particular scope.

Also, do you remember if soft-wrapping was enabled when you noticed the exception? In the meantime, I'll try editing the file to get it into the inconsistent state.

Thanks, @flxsource! 🙇

**Comment by flxsource** [comment]
I haven't been noting it down, but anecdotally I'd say it occurs when I make a change to a _different_ file, and then switch back to that one I sent you. It does seem to be intermittent - reopening the file (presumably still with whatever issue it originally complained about) often clears the error, but not always.

Soft wrapping is enabled.

I'll try and keep a better track of exactly what happens just before the error - but as sometime entire days pass without a problem sods law says I'll not be paying attention next time it happens!

**Comment by Stromwerk** [comment]
Today after updating to 1.9.0 I also started seeing this error.

[Enter steps to reproduce below:]

1. Open [this header.php](/https://gist.github.com/Stromwerk/01075049dd30c11c52b726bbd7c727de) file.

2. Scroll past line 74

3. Additional information: after some fiddling around I found out that line 81 is the culprit
`$uri = $lang . ( $this->uri->segment(2) ? "/" . $this->uri->segment(2) : '' ) . ( $this->uri->segment(3) ? "/" . $this->uri->segment(3) : '') . ( $this->uri->segment(4) ? "/" . $this->uri->segment(4) : ''); ?>`
Also chaning it's length also changed the buffer length in the error accordingly (e.g. if I removed 10 characters the number would go down by 10)

**Atom Version**: 1.9.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Invalid text decoration iterator position: (80, 106).
Buffer row 80 has length 240.

```
At C:\Users\stromwerk\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\text-buffer\lib\display-layer.js:1074

Error: Invalid text decoration iterator position: (80, 106).
Buffer row 80 has length 240.
    at DisplayLayer.module.exports.DisplayLayer.getScreenLines (C:\Users\stromwerk\AppData\Local\atom\app-1.9.0\resources\app.asar\node_modules\text-buffer\lib\display-layer.js:1074:19)
    at TextEditorPresenter.<anonymous> (C:\Users\stromwerk\AppData\Local\atom\app-1.9.0\resources\app.asar\src\text-editor-presenter.js:1355:37)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateLines (C:\Users\stromwerk\AppData\Local\atom\app-1.9.0\resources\app.asar\src\text-editor-presenter.js:1362:12)
    at TextEditorPresenter.module.exports.TextEditorPresenter.getPreMeasurementState (C:\Users\stromwerk\AppData\Local\atom\app-1.9.0\resources\app.asar\src\text-editor-presenter.js:121:12)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSyncPreMeasurement (C:\Users\stromwerk\AppData\Local\atom\app-1.9.0\resources\app.asar\src\text-editor-component.js:265:60)
    at TextEditorComponent.module.exports.TextEditorComponent.updateSync (C:\Users\stromwerk\AppData\Local\atom\app-1.9.0\resources\app.asar\src\text-editor-component.js:205:12)
    at C:\Users\stromwerk\AppData\Local\atom\app-1.9.0\resources\app.asar\src\text-editor-component.js:324:28
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\stromwerk\AppData\Local\atom\app-1.9.0\resources\app.asar\src\view-registry.js:221:9)
    at C:\Users\stromwerk\AppData\Local\atom\app-1.9.0\resources\app.asar\src\view-registry.js:3:61
```

### Commands

```
     -4:39.6.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -4:06.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:39.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:39.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:38.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:18.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:17.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:17.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:delete (atom-text-editor.editor.is-focused)
     -0:12.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:06.3.0 core:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "disabledPackages": [
      "minimap"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "dark-flat-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 13,
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true,
    "softWrap": true,
    "tabLength": 4,
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.23.0 (active)
dark-flat-ui, v1.2.4 (active)
highlight-selected, v0.11.2 (active)
less-autocompile, v1.0.0 (active)
minimap, v4.24.7 (inactive)
monokai, v0.18.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
Can anyone confirm whether they're still seeing this on 1.9.1?

**Comment by Stromwerk** [comment]
I can confirm I am no longer getting this error after updating to 1.9.1

**Comment by ozo2003** [comment]
mine still occurs in 1.9.1
actually apparently that occurs for my friend as well, he's on stable version. and in the same file, same row
my error was #12070

**Comment by as-cii** [comment]
@ozo2003: I have been trying to reproduce the error with the file you posted and the configuration shared on #12070, but unfortunately I am unable to trigger an exception (I've tried on `master`, `v1.9.1` and `v1.9.2`). A couple of questions to try reproducing this locally:

* Does it happen when running atom via `atom --safe`? 
* Does it happen only when you scroll down to the line you mentioned in the issue or when you edit it?
* Does it happen when you have some folded regions in the file?
* Does it happen when soft-wrap is on?

Thanks so much for everyone's help on this! 🙇

**Comment by nathansobo** [comment]
We'll be collecting more metadata about the state of the DisplayLayer  when these exceptions occur in 1.9.3 and we will get to the bottom of this.

**Comment by nathansobo** [comment]
This will be fixed in 1.9.8

**Comment by ShaurmaLab** [comment]
Looks like issue again returned in 1.13.0

**Comment by lee-dohm** [comment]
@ShaurmaLab If so, please post a new issue with steps to reproduce the problem.
