### ISSUE TITLE
Can't run on Ubuntu 16.04

### ISSUE THREAD

**Issue by zavodnyrichard** [atom/atom#12090]
Hi, I have a problem. :(

Atom installed correctly on my computer with Ubuntu 16.04, but after Atom run, the system reports an error, Atom freezes and nothing happens.

How can i fix it?

Richard

**Comment by zavodnyrichard** [comment]
Yay! I forgot.. I have a 64-bit OS.

**Comment by zavodnyrichard** [comment]
Ouch.. Any ideas where can be a problem?

**Comment by lee-dohm** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

When you post there, please include the following information:

* Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)?
* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

I hope we can help you get this figured out.
