### ISSUE TITLE
How can I change statusbar to be displayed on right-panel?

### ISSUE THREAD

**Issue by pierreneter** [atom/atom#12092]
![capture](https://cloud.githubusercontent.com/assets/12815768/16547076/de5ab788-418a-11e6-90e1-35231abf4598.PNG)
Im using Atom version 1.8.0

**Comment by thomasjo** [comment]
Those status-bar elements are not provided by any of the core Atom packages. I'm guessing they are coming from linter or some such package. Please reopen this issue on the appropriate package's GitHub repository.
