### ISSUE TITLE
to many code blocks

### ISSUE THREAD

**Issue by ronaldpetty** [atom/atom#12091]
### Description

When using the markdown render feature, I am having issues that cause the entire IDE to collapse into three skinny columns (that can still be interacted with.)  I tried recreate that issue, but so far have only found what follows.  I suspect it has to due with parsing several code blocks in a row.

### Steps to Reproduce

1. [First Step]
&#96;&#96;&#96;
a
&#96;&#96;&#96;
&nbsp;&nbsp;&nbsp;&nbsp;b
&#96;&#96;&#96;
c
&#96;&#96;&#96;

2. [Second Step]

Try to render in editor.

3. [and so on...]

**Expected behavior:** [What you expected to happen]

b to not be in code block

**Actual behavior:** [What actually happened]

b is in code block

### Versions

1.8.0

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by eikooc** [comment]
I think this is intended behavior if the _b_ is indented 4 spaces because indentation like that also causes a code block

**Comment by lee-dohm** [comment]
@eikooc is correct. This is not an Atom bug but the way that Markdown is designed.
