### ISSUE TITLE
Cannot build atom on Win10, error: node.exe: bad option: --harmony_collections

### ISSUE THREAD

**Issue by tinymins** [atom/atom#12099]
I tried to compile atom on Windows 10 x64.
And I have got python 2.7.10(x86), node 4.4.5(x64) installed already.
But when I execute `script\build` command, I got this:
```
D:\Dev\GitHub\atom>script\build
Node: v4.4.5
npm: v2.13.3
Python: v2.7.10
Installing build modules...
=> Took 4582ms.

Installing apm...
=> Took 1535ms.

Deleting old packages...
node.exe: bad option: --harmony_collections

D:\Dev\GitHub\atom>node --version
v4.4.5

D:\Dev\GitHub\atom>npm --version
2.15.5

D:\Dev\GitHub\atom>apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.3.windows.1
visual studio
```
I tried search on existed issues and on google, but still not find any solution.
Here is the screenshot:
![image](https://cloud.githubusercontent.com/assets/1808990/16573281/a8ea80ae-42a4-11e6-9c47-3a1afc76c489.png)
I got confused and have no idea on what to do next.
Can anybody help me get out of this problem please?

**Comment by lee-dohm** [comment]
Do you have [a version of Visual Studio](https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md#visual-studio) installed? If that doesn't fix it, the message board is the right place for this.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For build questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
