### ISSUE TITLE
Unable to select text or move cursor with keyboard shortcuts CMD+Arrow/CMD+Shift+Arrow using keyboard

### ISSUE THREAD

**Issue by StephenOTT** [atom/atom#12102]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Unable to select entire field / unable to move cursor to start and end of field using keyboard shortcuts native to mac when in Save dialog

### Steps to Reproduce

1. open file
2. open save dialog window.  
3. in the file name text field attempt to move the cursor using the keyboard from start of field or end or vice versa (CMD+Arrow Left or CMD+Arrow Right)
4. Additionally select CMD+Shift+Arrow left or Arrow right to select full field and does not work

**Comment by lee-dohm** [comment]
I could not replicate this issue using Atom v1.8.0 on Mac OS X 10.11.5. Here's what I did:

1. Launch Atom
1. Create a new file using <kbd>Cmd+N</kbd>
1. Start saving the file using <kbd>Cmd+S</kbd>
1. Pressed <kbd>Right</kbd> to move the cursor to the end of the word "Untitled"
1. Pressed <kbd>Cmd+Left</kbd> to move the cursor to the beginning of the word "Untitled"
1. Pressed <kbd>Cmd+Right</kbd> to highlight the entire word "Untitled"

All of the above worked exactly as expected. I also tried other permutations of the above and couldn't replicate the problem.

Have you tried replicating the problem in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

Also, have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?

**Comment by lee-dohm** [comment]
Closing due to lack of response. If you can let us know the answers to the above questions, I'll be happy to reopen the issue.
