### ISSUE TITLE
Unicode Encoding Issue with Python 2.7 Atom 1.8.0

### ISSUE THREAD

**Issue by Ricardo-Zhang** [atom/atom#12115]
Running on Mac os X 10.11
Atom ver 1.8.0
The encoding comment is not working in files created by atom:
```
# -*- coding: utf-8 -*- 
print u'好'
```
It simply didn't recognise the encoding scheme declared and the python interpreter used ASCII by default.

The same content works when editing the file with nano.
Same issue found on another Mac
In atom:
`print u'好'.encode('utf-8') `worked well.

But the comment declaration method is quite important for python, please pay attention and fix.

**Comment by lee-dohm** [comment]
I'm not sure what you're saying the bug is here.

**Comment by Ricardo-Zhang** [comment]
I am also quite confused with this but the python interpreter simply could not recognise the 
`# -*- coding: utf-8 -*- ` part in the script written with atom. 
When I switched to other text editor(vim) and typing exactly the same words, this problem did disappear. So I consider it as an issue of atom.

**Comment by lee-dohm** [comment]
According to [this StackOverflow answer](http://stackoverflow.com/a/6289494/1954) you don't need to declare strings as Unicode when you include the encoding comment line. I changed your script to:

```python
# -*- coding: utf-8 -*-
print '好'
```

And it worked just fine. I suspect that the other editors weren't saving the text in UTF-8, which Atom does by default.
