### ISSUE TITLE
Project folders disappear

### ISSUE THREAD

**Issue by QiiSyhx** [atom/atom#12113]
i also have this problem:#11869,#471,#661

os:win7
version:1.8.0

the project folder disappear when atom is closed, and i open a new file with context menu.

**Comment by Ben3eeE** [comment]
This behavior is intended, see https://github.com/atom/tree-view/issues/852#issuecomment-222904528 for a recent explanation.
This issue is a duplicate of https://github.com/atom/atom/issues/9643?

**Comment by lee-dohm** [comment]
Closing as duplicate of #9643. You may want to subscribe there for updates.
