### ISSUE TITLE
Atom crashes on open preferences.

### ISSUE THREAD

**Issue by pyvim** [atom/atom#12110]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom crashes on open preferences.

### Steps to Reproduce

1. Start Atom.
2. Edit -> Preferences.

### Versions

$ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1

$ uname -a
Linux SEPHIROTH 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lee-dohm** [comment]
Which Linux variant is this?

**Comment by pyvim** [comment]
Ubuntu 14.04.4 LTS

**Comment by pyvim** [comment]
Atom crashes when I write code too, but less. I don't know why. It's happening random.

**Comment by lee-dohm** [comment]
We haven't been able to reproduce this given the information we have so far. Let us know if you have any more information you can share.

**Comment by pyvim** [comment]
Now works normally. I don't understand how it's happened.

**Comment by 50Wliu** [comment]
Glad to hear it @pyvim.  If it happens again please let us know.
