### ISSUE TITLE
Atom isn't working in macOS Sierra Beta 2.

### ISSUE THREAD

**Issue by Dfmarulanda** [atom/atom#12126]
**Expected behavior:** 
1. Open the app.

**Actual behavior:** [What actually happened]
1. "Atom" is damaged and can't be opened. You should move it to the trash

### Versions
1. Stable  (Lastest)
2. Beta (Lastest)

Pss. Sublime Text is not working either.
Pss2. Brackets is not working.
Pss3. LightTable is not working

**Comment by thomasjo** [comment]
Works fine here. Something is broken on your system since no other editor seems to work either.
I'm closing this as this is seemingly not a problem on our end.

**Comment by Dfmarulanda** [comment]
Are you using Public Beta or Dev Beta?
