### ISSUE TITLE
Open Project, Files Atom suddenly closed.....

### ISSUE THREAD

**Issue by Aakash30Sethiya** [atom/atom#12121]
I am using latest version of atom 1.8.0

when I open any file or project by shortcut key {crtl+o} for open file, {ctrl+shift+o} for open folder or {ctrl+alt+o} for add project.....

then my atom get closed.

Like (Same as) I press crtl+shift+w which is for close atom window

Please mail me if there is any solution for it.....

Thanks in advance. :)

**Comment by thomasjo** [comment]
Please fill in the [issue template](https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md) (this was *automatically* added when you opened this issue).

Right now there is not enough information provided in this issue, and it will be closed unless the required information is provided in a timely manner.

**Comment by thomasjo** [comment]
It's asking you for a bunch of important information.
See https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md.

The first thing it's asking you for, is whether you can reproduce your problems in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode).

**Comment by Aakash30Sethiya** [comment]
how to check your checkbox?

**Comment by thomasjo** [comment]
Replace the space between the square brackets with an `x`. In other words change `[ ]` to `[x]`.
That will result
 - [x] Some important question.

**Comment by Aakash30Sethiya** [comment]
ok thanks

**Comment by Aakash30Sethiya** [comment]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

when I open any file or project by shortcut key {crtl+o} for open file, {ctrl+shift+o} for open folder or {ctrl+alt+o} for add project.....

then my atom get closed.

Like (Same as) I press crtl+shift+w which is for close atom window

### Steps to Reproduce

1. Open Atom.exe
2. Press Crtl + O or Ctrl + Shift + O or Crtl + Alt + Shift + O.

**Expected behavior:** 
Open File window.

**Actual behavior:** 
Closed the Atom Window.

### Versions
1.8.0
You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Now I Run atom 1.4.3 

It run quite well as before but I think It is fake. Means It is not updating.
shows a squirrel icon at the bottom-right of the atom window.
But all that it runs well now.

**Comment by thomasjo** [comment]
There's a few questions you haven't answered. Please try to reproduce the problem in safe mode:
http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode

Also, what operating system are you running? Also can you please run `atom --version` from a command line and report the output. I'm a bit confused by your description of what version of Atom you are running.

The reason for asking about safe mode is that if the problem is **not** reproducible there, then the problem is caused by one of your packages. I suspect this is the problem, but cannot be certain until you test in safe mode.

**Comment by Aakash30Sethiya** [comment]
How to open safe mode? I don't know....?

I 'm running Windows 10 64-bit. (Home version).

I recently told you that when I was running version 1.4.3 it's OK, but
after update to 1.8.0 it stuck same problem occurred to me...

What can I do now???

**Comment by thomasjo** [comment]
I have linked to the [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode) documentation two times already. It's also linked to in the issue template that you filled out.

Here's a fourth time for good measure:
http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode

Just click the link above and **read it**. It tells you exactly what [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode) is, and how to use it.

**Comment by Aakash30Sethiya** [comment]
sorry for my mistake but I already told you about that I am not a developer so I don't know about your coding features you already send me the links 4 times I know but I want to know that what is the safe mode in short I am not ion mood to ready the whole jumbo article about safe mode. If I have time to read it I already google for it but I think to direct talk about my problem to an expert, who can understand my problem and direct give me suggestions on my problem action. But you pretend like I'm Expert here!!! who can understand your thoughts and what do you want to do....

But I'm sorry again I'm not a developer. So please told me direct answers, not to give me links to search my answers. You should answer me like previously you told me about the checkbox "checked" problem. & you simply said that just remove the space between brackets and type x between the bracket.

I just want to say that in short please help me not try to confuse me.....

**Comment by thomasjo** [comment]
You don't need to read more than a few lines of text and the documentation clearly tells you that you can launch Atom in safe mode by executing the following command from the command line
``` command-line
atom --safe
```

Just make sure you **completely** exit all instances of Atom first. If you have followed the steps correctly, you should see a little green icon in the Atom status bar;
![image](https://cloud.githubusercontent.com/assets/3622/16760846/02f1ed48-481e-11e6-8090-576aacaf9496.png)

Once you are running Atom in safe mode, try to reproduce the problem you have reported. I'm almost 100% sure you will not be able to reproduce, since the problem is almost surely caused by a community package you have installed. But we need to confirm that suspicion just to be absolutely certain.

**Comment by Aakash30Sethiya** [comment]
thanks for your precious and simple reply :)

I read the whole page thrice but I Don't understand what to do for safe mode.... :)

Please Be simple.

and as you says in atom safe mode it working well and I can open any thing in atom with open command and shortcuts too.

I want to know 1 more thing that, 
When I face this problem again at next time, should I apply this steps for next time anymore for this problem???

**Comment by 50Wliu** [comment]
1. Search for `cmd.exe` in Cortana or the start menu.
2. Start the application once Windows finds it.
3. Type `atom --safe` and press enter.

**Comment by Aakash30Sethiya** [comment]
yes I already enter in safe mode.
1. I press "CTRL+O" or open any thing in atom, the atom window is closed, as like I press close button.

**Comment by 50Wliu** [comment]
OK.  I missed the part where you said you were using safe mode in your last post.

Are you using a non-US keyboard layout (like something that has AltGr)?

**Comment by Aakash30Sethiya** [comment]
I enter in safe mode and the given symbol which represents that I am in safe mode 
![02f1ed48-481e-11e6-8090-576aacaf9496](https://cloud.githubusercontent.com/assets/17140149/16793325/c4fcd040-48ed-11e6-8e9e-a7dc2d6202f0.png)
what is the mean that line in this question that
"Are you using a non-US keyboard layout (like something that has AltGr)?"

I am using US keyboard layout.

**Comment by 50Wliu** [comment]
Thanks, that answers my question.

Does opening a file or folder from the File menu work, or does Atom also close?  Can you also try running Atom using `atom --foreground --safe`, opening a file using the shortcut, and then paste the output here?

**Comment by Aakash30Sethiya** [comment]
ok as you says 
1. I open atom --forground --safe in cmd prompt
2. I click on file menu
3. select open file.
4. atom get closed again.

after that I have a cmd prompt window which shows some codes which I don't understand I thought you will so attach a screen shot of the cmd prompt which is given below:-
![atom error](https://cloud.githubusercontent.com/assets/17140149/16801665/c0d481d0-4919-11e6-9021-c68605a16ee0.png)

**Comment by 50Wliu** [comment]
Looks like app.asar couldn't get loaded, which might be the cause of your crashes.

**Comment by Aakash30Sethiya** [comment]
so what should I do for solve this problem?

any suggestions???

**Comment by Aakash30Sethiya** [comment]
hello

**Comment by lee-dohm** [comment]
@Aakash30Sethiya If the `app.asar` can't be loaded, it is going to cause all kinds of crashes. Fixing the loading of the `app.asar` is going to be the thing that will have to be worked on first.

1. Uninstall Atom
1. Download a new copy of the installer from https://atom.io
1. Install Atom using the new installer

Let us know if that helps.

**Comment by Aakash30Sethiya** [comment]
I do that a lot of times but every time this problem stuck to me.
I also install the previous version. But after It get update to 1.8.0 version of atom then its problem is same.

So should I use the previous version of atom???

I never get use newest version of atom???  :.(

**Comment by lee-dohm** [comment]
@Aakash30Sethiya Which OS and version are you running Atom on?

**Comment by Aakash30Sethiya** [comment]
When You see my previous messages then you don't ask me such questions.....:)

this is not possible to tell all person who join this conversation.

I am using windows 10 (64-bit) OS

and When my atom version is 1.8.0 then this thing is happen.

Are you all there solve my problem or you there for just question answering....????

This conversation starts at 8 days ago but you all just asking me the basic questions I send you the screen sho0t of the problem you distinguished the problem but you have no answer about it. ???

then why are you asking every time same questions? If you have no any further solution for it please tell me I'll solve it by my side I'll arrange something by my side.

I thought my problem get solved but now I could solve it by my side.

Thanks for wasting my time 
and
 Yours Too 
Sorry....!.
