### ISSUE TITLE
"Atom installation on Windows 7 produced no shortcut or OS integration"

### ISSUE THREAD

**Issue by DingBEN** [atom/atom#12124]
UPDATE July 29th, 2016

---

**WIN 7 Pro  ... ALL APPS working great on this box EXCEPT ATOM!!!**
after all the steps stated in the many posts below, I am left disappointed...
- Sorry to inform that ATOM is simply a continuing annoying FAIL!
- One never knows when it will start and show the VISUAL interface(window)
- It starts **multiple instances** in the TaskManager with no corresponding visual/window!
- it raises the Processor usage to 100% and peters-out
- Starting it from different shortcuts including via the update.exe type eventually results in windows popping on the screen of which many are untitled and empty, totally bare! an 1 partially remembering the last status

**whateva!**  something is not right about the ATOM editor on WIN

---

**Original post**
**squirrelsetup.log** attached

**My scenario, ex:** WIN7, first install of 1.8.0 atom.exe...

**1. run after install**, luckily I checked it or I would never have even seen the tool.

**2. once I exited**, had no way to start atom!? - no shortcuts ANYWHERE
       - had to do a FileSystem search to find where installed

**3. clicking on atom.exe**
    does nothing
    O! yes it does! it starts it but does not show the visual interface, only shows as an entry in the Task-Manager.!?

**4. going to DOS**
    and using .cmd or atom FAIL (spews 1/2 screen of 'crash' lines on the DOS window and hangs)

**5. context menu(right-click)**
       - **NO (Open with Atom)** even after having manually associated extensions to be ATOM default and icon shows correctly on the file type, like .css, .js, ...
       ...AND THE BAD PART ABOUT THAT
       ...ASSOCIATING .htm/.aspx/.php/etc...simply a CLUMSY APPROACH - GETS IN THE WAY...
          these extensions need to be
         - DefaultBrowser-associated to **EXECUTE**,
         - and instead, **(Open with Atom)** in the context menu!

```
  - **Open with** - Choose default program - Browse to fetch Atom FAILs (as in 4 - above)
     ...2 to 4 clicks and delays - RIDICULOUS
```

**6. adding a registry key,**
      to place (Open with Atom) in the context menu(right-click)
      have not tried that yet, but have had problems with other editors...
      was able to get (Open with notepad2) and (Open with Wordpad) to appear in context menu
     ...but it was a struggle (with Wordpad definitely)
**Will post an update HERE if I succeed with that!  (any suggestions?!)**

**7. made a shortcut:**
   C:\Users\User\AppData\Local\atom\app-1.8.0\atom.exe (with same target)
- that seems to dig the atom from the depth of KLUDGEs...
- atom comes up and shows as was last exited
   and remembers the file displayed is an ASPX which was set as HTML manually or no syntax color would show!   **(wonder if that will stick... where is it stored in the config!?)**

**Thus atom works ok... if use the shortcut.**

[SquirrelSetupCopy01.log.txt](https://github.com/atom/atom/files/354800/SquirrelSetupCopy01.log.txt)

**Comment by damieng** [comment]
Do you have an antivirus package installed? It looks like some files we create were instantly getting locked which can happen with an on-access virus scanner.

**Comment by DingBEN** [comment]
Well... incidentally that was my next thought, to reinstall with MSEssentials OFF.
as I peeked in the log I did see the access failures...
thus if 2 of us see that then it may be the simple solution...
but why am I able to install a great variety of software with no issues... and this one fails!?
I would like to reinstall with no apps up... and with the MALWARE still running, and if that fails again then turn it OFF and reinstall again.

Is that ok to try ... or will it jam due to installing over and over!?
I also have to save some of my config files where I made changes to font, colors etc... I think I was in 3 files... or will it leave that alone!?

**Comment by damieng** [comment]
Atom should be fine once installed.

The installer creates some temporary files and removes them again once it's done. Sometimes this happens too quickly for an on-access scanner that is still busy looking at them.

**Comment by DingBEN** [comment]
hmmm! I thank you for all your willingness to help, but this is turning into a circus.
...yet do not think for one minute your help is not well appreciated.

Perhaps I am not precise enough in my wording, but this is the second post where I get blanket answers which do not address my points made directly. I am having to guess.
I am not sure how to interpret your answers.
**"...Atom should be fine once installed..."** well ok, that sounds good
I interpret that as install away it will know what to do to make sure all is tidy!

Thus I attempted the steps I listed in my previous post --- and the REinstall failed 3 times!

**hierarchy** "C:\Users\ThisUser\AppData\Local\atom\packages\RELEASES" I am sure was on disk before the REattempts... now it is GONE! ...packages hierarchy is gone, in fact Atom.exe is gone!
**ONLY THING LEFT!?** C:\Users\ThisUser\AppData\Local\atom\app-1.8.0\resources\app\apm\bin\node.exe

1. **ALL INSTALLs are under Administrator
Original install is 01 you have that log**

2. **see corresponding logs attached**
    REinstall 02 (ANTIVIRUS  ON - MSE) made no difference crash
    REinstall 03 (ANTIVIRUS  OFF - NOMSE) made no difference crash
    REinstall 04 (new AtomSetup.exe from https://atom.io/) crash

3. **Downloaded Atom-master from Github page instead** - https://github.com/atom/atom
    and unziped it in place to see what hierarchy it produced...
    nothing exactly similar to the AppData/local/Atom/...
   **is the github atom-master.zip download the one to install and HOW to install that?**

**So I am now stuck** as Atom is no longer executing even from the shortcut (duhhh it's gone!)
...and reinstalling fails repeatedly!

Although I have many questions... one seems to stand alone...
**_...how do I 'clean slate' this for a brand new clean install?_**

next... give up! and get Sublime, be done with this!
yeah I know, I read on both extensively and Atom may offer a few more features than Sublime
and Atom maybe more Open Source as well... but I simply do not have hours and hours to play with stuff!
I has resigned myself to use it from the shortcut and wait till your install got better...
but now it means clean slate... duno! waiting on your advice.

[SquirrelSetup03NOMSE.log.txt](https://github.com/atom/atom/files/355371/SquirrelSetup03NOMSE.log.txt)
[SquirrelSetup02withMSE.log.txt](https://github.com/atom/atom/files/355372/SquirrelSetup02withMSE.log.txt)
[SquirrelSetup04NEWatomsetup.exe.log.txt](https://github.com/atom/atom/files/355374/SquirrelSetup04NEWatomsetup.exe.log.txt)

**Comment by damieng** [comment]
Really not sure why you are getting so many IO errors but it's not typical - we have many many Windows users.

There is one more thing you could try - delete c:\users\thisuser\appdata\local\atom\app-1.8.0 entirely then download https://github.com/atom/atom/releases/download/v1.8.0/atom-windows.zip and unpack it to the same location.  

This bypasses the installer entirely so if you want to use from the command line you'll need to manually add the %localappdata%\atom\bin folder to your PATH.

**Comment by paulcbetts** [comment]
> This bypasses the installer entirely so if you want to use from the command line you'll need to manually add the %localappdata%\atom\bin folder to your PATH.

Or just run `atom.exe --squirrel-install 1.8.0` to fake it

**Comment by DingBEN** [comment]
ok... will rename the bad hierarchy instead, in case it is riding on a disk problem, though much of that hierarchy has been deleted by the install and is probably back in the OS IO free chain already!
Will let you know progress, in a bit!

- Should that work!, should I use the AtomSetup.exe on top to get it to create the OS integration!?
- or struggle manually to create the context menu and other integration?
- AND how do I stop the auto upgrade from clobbering it later!?

**Comment by DingBEN** [comment]
**ohhhh! the plot is gettin' thicker!** yet some good news!
I am running on Atom again, with 2 shortcuts that are not identical(see below)

It would not let me rename the **AppData/local/Atom/** folder
 - said was in use by some process or close WExplorer-folder
 - I closed everything ... nothing running but the startup TASKs in TaskManager... noGO... still locked!
 - so I logged out and reattempted - **all good, folder renamed** - atoxxxmxxx

...at that point, I assumed that the install had been crashing due to this issue, thus thought it was a good idea to use the AtomSetup.exe to install fresh... as I now know clean-slate =  zap **AppData/local/Atom/** folder (maybe not, may need to clear Browser data as well... next batch surely, as this is not over!)

Install was a bit faster, but seemed to hang (see log) - it should install much faster(I had never mentioned that because I was not sure of my intuition)

Log shows it crashes on the tmp/lockfile !!@#^*!^@#* repeatedly! duhhh! source of the hanging!
**KEY QUESTION**...please let me know what did not install due to the errors!
**- though it appears to have installed mostly well... what is it missing due to the log LOCK errors!!!**

**- Low&behold**... a shortcut appears on the Desktop... hmmm good news, never made it before!
- and Atom came up after install with ALL my settings/Folders(2 of them) in the left pane, and  appears to be installed... successfully!  hmmm!  let us investigate a bit:

**FIRST doubt ...**
- how did it remember the settings?
- and know to load my 2 folders in the left pane!?!?
...please give me a precise answer on this question!!! I assume it is getting that from the Browser cache... **give me clues, please... what where when!?!**

Once I killed it and used various ways to call it... it only sees one of the folders... and given the scenario may only show a generic Atom window, with nothing in it... but it is running! alelooooo!

- no shortcut in the **START MENU**
- **Open with** - Atom is now present in the list of potential Apps, **no need to BROWSE anymore**
- **context menu**(right-click) Open with Atom NOPE... no such luck
  ...though I have  'Open with notepad', 'Open with notepad2', and 'Open with Sublime' entries!

## **BUTTT!!!!!**  this one is a CLUE for you guys... very weird behavior!!!!
**EEEEEElectron confusion! must be the spooky effect at a distance!**
- if double-click a file **with Atom icon**, or use 'Open with' - opens it in the currently running Atom process
- if no currently running instance... it peters out to a sequence of hour/glass silent death! NOTHING!
  **that may be the cause of piled up atom instances in task manager with NO corresponding VISUAL interface!!!** ...and after checking indeed they show in task manager but not visually.
- if piled up orphan instances in task manager then the double click or Open with may work, but starts more than one window one or 2 being generic without any panes... but working!!!

**SHORTCUTS**  - one installed*(desktop), - the other, MINE!
- both seem to always work except if orphan atoms! LOL then they come up with multiple instances! and forget to load all folders and/or open generic versions of atom!

- **My old shortcut** manually created on original install still works, BRINGs Atom to screen!
    ...C:\Users\NIQ\AppData\Local\atom\app-1.8.0\atom.exe (same target)  - has worked on previous installs!?
- **the Desktop-installed shortcut**  **C:\Users\NIQ\AppData\Local\atom\Update.exe --processStart atom.exe** also works... and is the way to bypass the update to keep it from clobering working setup! **YES?NO!?**

**- I am assuming this is how to grab the current update!?** PLEASE CONFIRM/EXPLAIN!

Have not checked my config files yet to see if my customization was retained, I AM SURE THEY WERE NOT!  no biggie... I know them by heart...

**Hope this helps!**

[SquirrelSetup05.log.txt](https://github.com/atom/atom/files/355733/SquirrelSetup05.log.txt)

**Comment by JacquesvanWyk** [comment]
I have also a strange problem.I installed atom and worked on it for few days.I keep my computer on but then did a restart.When i wanted to start atom i could not find it.I looked around but nowhere i then went to the download folder to do another install and there the file has been deleted.

Now here is where it gets stranger.I at first did think it was because i did also do system restore in this time.So i download this atom installer 2nd time.I installed and worked again.Then after restart exactly the same happened.Atom is gone and the install file shows deleted in my list.
![2016-07-10 14_16_31-downloads](https://cloud.githubusercontent.com/assets/12008702/16713486/3627616e-46a9-11e6-8fe8-14f00a3b56a9.png)

**Comment by damieng** [comment]
@JacquesvanWyk There is nothing in Atom that would delete AtomSetup.exe at all.  A quick search did reveal a bunch of discussions about Chrome removing downloads.

**Comment by DingBEN** [comment]
@JacquesvanWyk 

I have gone thru the same loop (both just logging off, and restart) and not experiencing the problem any more, all files seem to remain in place... and I think it is due to this(**but not guaranteed**):

**cut & pasted from my previous post**
My old shortcut manually created on original install still works, BRINGs Atom to screen!
...C:\Users\NIQ\AppData\Local\atom\**app-1.8.0\atom.exe** (same target) - has worked on previous installs!?

the Desktop-installed shortcut C:\Users\NIQ\AppData\Local\**atom\Update.exe** --processStart atom.exe also works..

...thus I only use My old shortcut... **NOT** starting via Update.exe

One thing, when I first downloaded the AtomSetup.exe an update slid between as I was going thru my tribulations with it, and it appears it crashed me, but it is hard to tell if indeed that is the case.
I downloaded the latest AtomSetup.exe and noticed the recent update note on Github... but the file is the same byte count so hard to say.

I believe if no update is available, the Update.exe will not cause the problem,
but I cannot test that on this machine, so I am NOT running the Update.exe shortcut version... lest it clobbers me again!
I suppose I could duplicate the atom hierarchy and reinstate it if it does clobber it, but that means constantly backing it up as changes are made.

**My suggestion at this point**:  (see previous post for detail)

- zap(rename) the atom hierarchy (also keeps cache from being accessed)
- make sure you are on a clean reboot, nothing running(I am not sure if Chrome for example causes locks on the AppData hierarchy)
- reinstall (AtomSetup.exe) (see previous post for details)
- Create the shortcut that bypasses the Update.exe(never click on the Update.exe version shortcut the install places on the Desktop!)

**Comment by DingBEN** [comment]
..interesting that damien would also mention Chrome... LOL... i had my doubts about that as I mentioned in my previous reply(damien was typing at the same time as I was reacting the previous reply-lol)
...and thought it may get int he way BUT NOT actually delete! wow!

**Comment by damieng** [comment]
It is perfectly normal for the icon to point to update.exe  - it doesn't mean there is an update or it will update - it's just part of the checking process.

**Comment by nelson6e65** [comment]
Same problem of Atom integration on Windows 10. :pensive:

**Comment by DingBEN** [comment]
@neslon6e65 have you tried the steps I listed?  it should work!
make sure to login as admin just in case and do it on a fresh login... do not start Chrome or other!

**Comment by DingBEN** [comment]
**WIN 7 Pro  ... ALL APPS working great on this box EXCEPT ATOM!!!**
_**see Updated ORIGINAL post at top of thread**_

**Comment by Cerberus1985** [comment]
Same problem of Atom integration on Windows 7 ultimate x86

**Comment by luis2003** [comment]
I had a similar issue: Installer atom on windows 7 and no shortcut and only could find atomsetup.exe when performing search. that meant that I had to reinstall atom every time I wanted to use it!!! after several times of doing this, I enabled in control panel "show hidden folders" and "show file extensions" and after reinstalling one more time the shortcut was created and I could use to launch atom without reinstalling :) hope this helps.
