### ISSUE TITLE
Atom dissapears after windows restart

### ISSUE THREAD

**Issue by JacquesvanWyk** [atom/atom#12133]
I have strange problem where my atom program dissapears.I installed it and worked on it for few days while my computer stays on.I had to restart my pc and when i wanted to go start atom it was gone.I looked everywhere but it was gone.When i went to downloads folder it got even more stranger as my installer file was gone too.

My pc was asking my for a system restore so i figured it must have gone with this restore.So i downloaded the installer again and started working again.Today i restarted my computer and again Atom is gone and even the installer files is deleted.
![2016-07-10 14_16_31-downloads](https://cloud.githubusercontent.com/assets/12008702/16713556/6d2e8c44-46ab-11e6-8b77-c05a9c0a4ab6.png)

Here you can see the two files and you can see its deleted.Has anyone else experienced something like this?

I have never had any other software do this before.I am going to download atom again and try for 3rd time.

**Comment by lee-dohm** [comment]
We've never heard of anything like this before either. Do you have any more information you can give us as to what is unique about your system that it is deleting Atom?

**Comment by JacquesvanWyk** [comment]
I think it was not the program and my computer itself.Have send pc to be checked will give feedback after i get pc back.thank you

**Comment by lee-dohm** [comment]
Thanks for the update @JacquesvanWyk. I hope everything gets fixed up quickly!

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12133#issuecomment-231953654. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
