### ISSUE TITLE
Prevent command-w/ctrl-w closing windows

### ISSUE THREAD

**Issue by alexjurkiewicz** [atom/atom#12136]
### Description

In Atom, ctrl-w closes both tabs and windows. Sometimes I want to close all tabs in my window, but leave the window open for later. It's surprising (and annoying) when I hold down command-w and all my tabs close, follow by the window.

I would find the UI more consistent if you needed ctrl-shift-w to close an editor window. This is not the same behaviour as eg a web browser, but it is consistent with IDEs in particular.

### Steps to Reproduce

1. Open an Atom window
2. Open two tabs in the window
3. Press command-w / ctrl-w three times

**Expected behavior:** All tabs closed but editor window is open.

**Actual behavior:** Editor window is closed.

### Versions

Atom 1.8.0

**Comment by mnquintana** [comment]
Try this:
<img width="633" alt="settings screenshot" src="https://cloud.githubusercontent.com/assets/823545/16738300/fade9518-4749-11e6-842f-03e232e27c50.png">

**Comment by alexjurkiewicz** [comment]
Thanks!

**Comment by Rhywun** [comment]
Ditto & I would add the only reason this annoys me is because the app is so slow to launch :(
