### ISSUE TITLE
Error when installing any package

### ISSUE THREAD

**Issue by JustinHoman** [atom/atom#12135]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Every time I try to install a package, I get an error. I get this with every package i try to install. I've tried a lot of different ones.
![error](https://cloud.githubusercontent.com/assets/9911917/16715654/75b405ca-46e6-11e6-81e0-9279dcee752b.png)

### Steps to Reproduce

1. Search for package
2. Click on install
3. See error message

**Expected behavior:** Package to be installed

**Actual behavior:** Got an error

### Versions

Atom: 1.8.0
Electron: 0.36.8
Chrome: 47.2526.110
Node: 5.1.1
macOS:  10.11.4

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by lee-dohm** [comment]
Socket hang up is a networking problem. For some reason the connection is getting cut off mid stream. Can you replicate this on another computer or in another location?

**Comment by JustinHoman** [comment]
Unfortunately, I don't have any computers nearby to test this issue with right now. I'm not behind a proxy or anything like that.

Thanks for you response

**Comment by 50Wliu** [comment]
@JustinHoman And just to confirm - it happens consistently, even after waiting for a few hours?

**Comment by JustinHoman** [comment]
@50Wliu Yes, I've tried it multiple times. Waited a few minutes then a few hours, and even a day or 2 after that. Nothing fixed the issue.
