### ISSUE TITLE
Option for toggling undo history persistence over multiple sessions

### ISSUE THREAD

**Issue by sjuvonen** [atom/atom#12134]
Since around release 1.7.0 or 1.8.0 Atom has started storing undo history over reboots, which is frankly awful way to behave. I could not find any package that would cause this nor is there any way to configure the behavior in the GUI. Therefore I presume it to be hardcoded somewhere in core. I've lost good chunks of code for not realizing my undos are clearing lots of others things too than just my latest debug session.

Steps to reproduce:
1. Open a document
2. Type something (and save)
3. Close Atom
4. Open Atom
5. Open the same doc as in step 1
6. Ctrl-Z to undo -> it clears the edits from previous session

**Comment by thomasjo** [comment]
This is by design, and not likely to change. Additionally there is no justified reason for adding yet another option, simply to toggle this functionality.

You can trivially recover from this by undoing your undo — simply execute a *Redo* (`ctrl-y` / `cmd-y`).
