### ISSUE TITLE
.gitignore hidden files

### ISSUE THREAD

**Issue by QiiSyhx** [atom/atom#12147]
i have a file ".gitignore" in my project folder. the files in .gitignore not show in the tree view,
some file like config file, i would not commit to git,but sometime i want to edit it, like database config file,
i want connect to local db. other teamer want to connect their local db. some times, i want to check log files,but it's hidden, and so on.

**Comment by lee-dohm** [comment]
See the Tree View setting "Hide VCS Ignored Files":

<img width="844" alt="screen_shot_2016-07-11_at_11_37_50_pm" src="https://cloud.githubusercontent.com/assets/1038121/16757390/90dec972-47c0-11e6-884a-e3ecf6a1e750.png">

Uncheck it if you want the Tree View to display ignored files.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
