### ISSUE TITLE
Multiple Projects setup

### ISSUE THREAD

**Issue by DingBEN** [atom/atom#12140]
**_WIN 7 - Atom 1.8.0_**
Pardon me for seeming to be lazy, but I am winded just having had to fight the installation of Atom.
I need to speed up this issue, relying on someone who has already done such!
Have seen a note that such setup is available on unbuntu!?

How to setup Atom to remember a particular Project's last session?
It seems Atom wants to only reload what was last used...

- **Picture, say 8 projects, in a drop-down menu P1, P2, P3, ...**
- --- Each option Px points to a set of Psx(shortcuts) that pertain to the corresponding Px clicked.
- --- one shortcut may point to a set of Folders to bring up
- --- another shortcut may point to some HTM,  js, Node.js areas etc...

thus...
- **another shortcut** Ps1 points to starting Atom with the last set of files accessed left open upon quitting the Atom Editor 
so... if P1, Ps1 was just exited with its own last session image/status
then loading Atom again will remember that scenario

**Question 1**
**But if** last exited P1 and now clicking.... P2, Ps2 ... how to get it to remember the P2, Ps2 last scenario?
_...this is the better option, all automatic/dynamic_ CAN IT BE SETUP TO DO THAT?

**Question 2**
**Can settle for simply creating shortcuts** that call a set of default Folders/files in Atom for each specific Project!  IS THIS THE WAY to GO?!

Thank you!

**Comment by lee-dohm** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

Atom remembers your last session based on the list of project roots you have open when Atom is closed. So if you have 8 project roots, then you have to open the same set of 8 project roots when launching Atom to restore the same session.
