### ISSUE TITLE
lineTextForScreenRow returns invisibles

### ISSUE THREAD

**Issue by benogle** [atom/atom#12149]
### Description

I would expect `lineTextForScreenRow` to return whitespace rather than the associated invisibles. This behavior was changed ~1.9beta, likely with the layered rendering stuff.
### Steps to Reproduce
1. `atom.workspace.getActiveTextEditor().lineTextForScreenRow(2)` on a line with invisibles

**Expected behavior:** whitespace!

**Actual behavior:** invisibles :(
### Versions

Master @ 57faec

**Comment by lee-dohm** [comment]
Confirmed using Atom v1.10.0-dev-57faec3 on Mac OS X 10.11.5:

<img width="440" alt="screen shot 2016-07-11 at 11 34 32 pm" src="https://cloud.githubusercontent.com/assets/1038121/16757342/1b5ddaf8-47c0-11e6-9db3-a7811c980bf0.png">
