### ISSUE TITLE
Install Node.js modules to build directory

### ISSUE THREAD

**Issue by paulmenzel** [atom/atom#12151]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [ x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

Following the [Linux build instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#custom-build-directory), passing the [build directory](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#custom-build-directory), the Node.js modules are installed in the source directory.

```
$ /dev/shm/bee-root/atom/atom-1.8.0-0/source/script/build --build-dir /dev/shm/bee-root/atom/atom-1.8.0-0/build
Node: v6.2.1
npm: v3.9.3
Installing build modules...
=> Took 54004ms.
[…]
$ /dev/shm/bee-root/atom/atom-1.8.0-0/source/script/grunt install --build-dir /dev/shm/bee-root/atom/atom-1.8.0-0/build --install-dir /dev/shm/bee-root/atom/atom-1.8.0-0/image
Grunt command does not exist at: build/node_modules/.bin/grunt
Run script/bootstrap to install Grunt
$ cd /dev/shm/bee-root/atom/atom-1.8.0-0/
$ find . -name grunt
./source/node_modules/bootstrap/grunt
./source/script/grunt
./source/build/node_modules/.bin/grunt
./source/build/node_modules/grunt-cli/bin/grunt
./source/build/node_modules/grunt
./source/build/node_modules/grunt/lib/grunt
```

In my opinion, the `build` directory should have been put into `/dev/shm/bee-root/atom/atom-1.8.0-0/build`.

**Comment by lee-dohm** [comment]
I understand that you want the node modules only installed in the build directory and not the source directory. What's the reasoning behind this?

**Comment by paulmenzel** [comment]
The reason is, that in my case all commands are run from the build directory (pwd) – as seen in the output above – and the directory `node_modules` is not found.

The more generic reason is, that the source directory should be kept clean, as it’s for example not writable, or the build is supposed to be done on a dedicated disk/media.

**Comment by eastwood** [comment]
I tend to agree, unless ofcourse there is a functional reason to have dependencies in the source
