### ISSUE TITLE
samd21_xpro

### ISSUE THREAD

**Issue by alexptbg** [atom/atom#12162]
Hi,
I am running the latest versions of all software (win10 pro+Atom+platform+python2.7)
Everything work fine when using with arduino avr boards.
When i try to build for samd21 xpro board i have the this error:

platformio run --target upload
src\main.cpp:6:21: fatal error: Arduino.h: No such file or directory
#include "Arduino.h"
^
compilation terminated.
scons: *** [.pioenvs\samd21_xpro\src\main.o] Error 1
 [ ERROR ] Took 1.26 seconds
 
Can someone help me here?

Thanks in advance, 

Alex Soares

**Comment by 50Wliu** [comment]
I don't see how this is an Atom issue, as Atom by itself does not support compiling.  This appears to be a platformio or other issue instead.
