### ISSUE TITLE
Atom crashes after 5 minutes without any packages. 

### ISSUE THREAD

**Issue by lfaler** [atom/atom#12173]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]
After 10 minutes of atom being open all files are unsaved and atom crashes. This even happens without packages.

### Steps to Reproduce

1. [Open Atom]
2. [Wait 10 minutes]

**Expected behavior:** [What you expected to happen]
For Atom to continue running.

**Actual behavior:** [What actually happened]
![screen shot 2016-07-14 at 3 30 04 pm](https://cloud.githubusercontent.com/assets/14255968/16857905/e0e12636-49d7-11e6-9db1-afefc9346d4d.png)

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

MacBook-Pro:~ laynefaler$ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

MacBook-Pro:~ laynefaler$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4

** On Mac OSX El Capitan **

And here are the packages I want to use:

Built-in Atom Packages (89)
├── about@1.5.0
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.29.2
├── autocomplete-snippets@1.10.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.39.0
├── bracket-matcher@0.82.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.38.0
├── find-and-replace@0.199.0
├── fuzzy-finder@1.0.5
├── git-diff@1.0.1
├── go-to-line@0.30.0
├── grammar-selector@0.48.1
├── image-view@0.57.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.51.3
├── language-clojure@0.20.0
├── language-coffee-script@0.46.1
├── language-csharp@0.12.1
├── language-css@0.36.1
├── language-gfm@0.85.0
├── language-git@0.12.1
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.110.0
├── language-json@0.18.0
├── language-less@0.29.3
├── language-make@0.21.1
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.34.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.43.1
├── language-ruby@0.68.5
├── language-ruby-on-rails@0.25.0
├── language-sass@0.46.0
├── language-shellscript@0.21.1
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.1
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.4
├── language-yaml@0.25.2
├── line-ending-selector@0.4.1
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.63.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.3.1
├── one-light-syntax@1.2.0
├── one-light-ui@1.3.1
├── open-on-github@1.0.1
├── package-generator@1.0.0
├── settings-view@0.235.1
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.2.3
├── styleguide@0.45.2
├── symbols-view@0.112.0
├── tabs@0.96.0
├── timecop@0.33.1
├── tree-view@0.205.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (23) /Users/laynefaler/.atom/packages
├── atom-beautify@0.29.9
├── atom-bootstrap3@1.2.12
├── atom-html-preview@0.1.21
├── auto-detect-indentation@1.1.0
├── autoclose-html@0.23.0
├── color-picker@2.2.2
├── css-comb@2.4.3
├── emmet@2.4.3
├── file-header@1.9.0
├── file-icons@1.7.17
├── git-plus@5.16.2
├── highlight-selected@0.11.2
├── javascript-snippets@1.2.1
├── linter@1.11.14
├── minimap@4.24.7
├── minimap-highlight-selected@4.4.0
├── nuclide@0.155.0
├── open-recent@5.0.0
├── pigments@0.31.1
├── remote-edit@1.8.24
├── script@3.8.1
├── set-syntax@0.3.0
└── todo-show@1.6.0

**Comment by lfaler** [comment]
Any trace of preview-plus crashes the editor. I had to uninstall all packages and uninstall Atom then install them all over again (w/o preview-plus)

**Comment by 50Wliu** [comment]
So does Atom crash without preview-plus?  In other words, does Atom crash when running `atom --safe`?

**Comment by eastwood** [comment]
This doesn't appear to be an issue with Atom and moreso with the third-party packages. @lfaler did you localise the issue to https://github.com/skandasoft/pp?

**Comment by lfaler** [comment]
I tried to close this because I found out that it was a package not the editor, preview-plus was crashing the editor and it wasn't the editor itself. After uninstalling the package I still had to uninstall the editor and reinstall my packages without preview-plus. Just uninstalling the package wasn't the fix. I have the editor working and I haven't had a problem since.

**Comment by 50Wliu** [comment]
Thanks for the update @lfaler.

**Comment by eastwood** [comment]
Good to hear you're not having any more problems @lfaler.

**Comment by lfaler** [comment]
One thing that may be interesting to look at, is why was the editor still affected by the package after uninstalling the package with a restart.

**Comment by 50Wliu** [comment]
It shouldn't, though it may be that that package left some bad configuration in `~/.atom`.
