### ISSUE TITLE
Broken Link in Workspace documentation

### ISSUE THREAD

**Issue by zoo1** [atom/atom#12175]
In the documentation for the Workspace Class, the open method contains a broken link. The broken link is the "Promise" in the return values block. 
![capture 2016-06-04 at 11 15 01](https://cloud.githubusercontent.com/assets/4008169/16493560/f2d6e116-3eb3-11e6-861e-17bfe98aa192.png)

_Copied from original issue: atom/atom.io#80_

**Comment by lee-dohm** [comment]
This is fixed now. Thanks!
