### ISSUE TITLE
why no upgrade core frame  Electron to  V1.2.7!!!!

### ISSUE THREAD

**Issue by crperlin** [atom/atom#12177]
http://electron.atom.io/releases/
![image](https://cloud.githubusercontent.com/assets/8272877/16883079/d23c6d84-4af4-11e6-9c1c-20c2ba9d480e.png)

I found that the latest version of the eletron is still only 0.37, behind a lot of versions;
The general version of the update has a certain BUG repair, there are some performance improvement and function expansion;
The next version can be updated to the latest version of electron.. Thank you

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/11967#issuecomment-225974781

**Comment by 50Wliu** [comment]
See also https://github.com/atom/design-decisions/blob/master/electron-update-procedure.md.
