### ISSUE TITLE
blue dots in tabs for files changed are hard to read

### ISSUE THREAD

**Issue by masterkrang** [atom/atom#12184]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
yes
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
yes
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
yes
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
yes
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
yes
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
yes
For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The blue dot that symbolizes file changes that haven't been saved is overlapping the file name. This causes some very annoying problems:

- it's so easy to miss that I sometimes forget to save file changes
- makes it harder to read the file name

![image](https://cloud.githubusercontent.com/assets/452219/16897895/4a615ca8-4b76-11e6-9ee5-d7113052c26b.png)

### Steps to Reproduce

1. make a change to any file
2. try reading the text in the tab, you'll see a blue dot on top of the text

**Expected behavior:** Blue dot should have a margin so you can clearly see it and also be able to clearly read the file name.

**Actual behavior:** Blue dot is on top of the text, making it not obvious which files have changed, causing me to forget to save file changes.

### Versions
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

Mac OSX El Capitan

**Comment by lee-dohm** [comment]
Thanks very much for the bug report! (And especially taking the time to give the details.) Would you mind reopening it on the https://github.com/atom/one-dark-ui repository?

**Comment by lee-dohm** [comment]
Moved to https://github.com/atom/one-dark-ui/issues/153.

**Comment by masterkrang** [comment]
@lee-dohm damn you're fast
