### ISSUE TITLE
Linux installation packages on atom.io are broken

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#12182]
## Symptoms

You downloaded Atom from https://atom.io and are experiencing unhandled exceptions like the ones in these Issues:

* https://github.com/atom/git-diff/issues/106
* https://github.com/atom/status-bar/issues/157
* https://github.com/atom/tree-view/issues/888

## Workaround

1. Uninstall the version of Atom you have installed now
1. Download the appropriate package from https://github.com/atom/atom/releases/latest
1. Install the new package according to [the installation instructions](https://github.com/atom/atom#debian-linux-ubuntu)

## Root Cause

It appears that the CDN cache on https://atom.io of the Linux packages is some unreleased branch version rather than the packages from https://github.com/atom/atom/releases/latest. We're investigating the problem and will update this Issue with current status.

**Comment by justinseiter** [comment]
Thank you @lee-dohm ! This resolved my 'onDidChangeStatuses' issue.

**Comment by OriginalPenguin** [comment]
I'm still having the problem. :(

What should I do?

**Comment by Amet13** [comment]
+ to @OriginalPenguin 
Fresh installation from github under Linux Mint MATE 17.3. Can't open file/folder or create new project in new window.

**Comment by roccomuso** [comment]
@Amet13 me too on Ubuntu 16.04.

**Comment by 50Wliu** [comment]
@Amet13 @roccomuso Can one of you open a new issue and follow the provided issue template?

**Comment by Amet13** [comment]
@50Wliu I created this issue (https://github.com/atom/atom/issues/12191) with screenshots, hope it helps you.

**Comment by Yakoot** [comment]
not working for me


[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Linux Mint
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.0


### Stack Trace

Failed to activate the status-bar package

```
At Cannot read property 'onDidChangeStatuses' of undefined

TypeError: Cannot read property 'onDidChangeStatuses' of undefined
    at GitRepository.module.exports.GitRepository.onDidChangeStatuses (/usr/share/atom/resources/app.asar/src/git-repository.js:131:24)
    at status-bar-git.GitView.subscribeToRepositories (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:106:61)
    at status-bar-git.GitView.initialize (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/git-view.js:32:12)
    at Object.module.exports.activate (/usr/share/atom/resources/app.asar/node_modules/status-bar/lib/main.js:67:16)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by glaslos** [comment]
`sudo apt remove --purge atom` and reinstalling the deb package from github fixed the issue for me. Didn't worked without the `--purge`

**Comment by Nemikolh** [comment]
I'm on Ubuntu 14.04, and I tried to remove all files manually but as it didn't worked, I tried to do `sudo apt-get remove --purge atom` and it still doesn't work. :cry: 

I'll try the beta version to see if the problem is solved with that version.

**Comment by Yakoot** [comment]
Beta works for me too

**Comment by luisgagocasas** [comment]
**Español**
Parece que el problema es en la versión  v1.4.0 la solución es pasar a la versión BETA  v1.8.0

1) Primero hay que desinstalar atom v1.4.0
- sudo apt remove --purge atom

2) Luego instalar la versión v1.8.0
- sudo add-apt-repository ppa:webupd8team/atom
- sudo apt-get update
- sudo apt-get install atom

**English**
It seems the problem is in version v1.4.0 the solution is to move to the BETA version v1.8.0

1) You must first uninstall atom v1.4.0
- sudo apt remove --purge atom

2) Then install the version v1.8.0

- sudo add-apt-repository ppa:webupd8team/atom
- sudo apt-get update
- sudo apt-get install atom

**Comment by ryanbergsma** [comment]
I am on Ubuntu 16.04 and the [Beta](https://atom.io/beta) seems to be working for me. I had trouble with the stable release and the PPA

**Comment by adamwtow** [comment]
The workaround at the top of this page just worked for me on Ubuntu 14.04

**Comment by Guard13007** [comment]
What's the difference between the PPA and the version that is supposed to be linked to from the site? @ryanbergsma How do you get the PPA? Is it having the same issue as the release on the site?

**Comment by 50Wliu** [comment]
The PPA is maintained by a third-party that is not affiliated with Atom or GitHub.

**Comment by Guard13007** [comment]
@50Wliu Thank you. I prefer to get my packages from official sources usually, so I won't be using that.

**Comment by slash3b** [comment]
Beta works perfectly on Fedora 24.

**Comment by dinhxuanvu** [comment]
I followed the instruction but it didn't help on Fedora 23. Still experiencing the same issues.

**Comment by maxbrunsfeld** [comment]
I believe [atom.io](atom.io) is now serving the correct files.

**Comment by roccomuso** [comment]
@maxbrunsfeld confirmed?

**Comment by lee-dohm** [comment]
Yes, it is confirmed as fixed.
