### ISSUE TITLE
editor:move-to-beginning-of-screen-line moves cursor to the end of the previous line

### ISSUE THREAD

**Issue by kylesimmonds** [atom/atom#12187]
### Steps to Reproduce
1. Open file with at least one line of text
2. Turn Soft Wrap on, if it's not already
3. Indent line at least once
4. Resize window so line soft wraps
5. Fire `editor:move-to-beginning-of-screen-line` with cursor positioned anywhere on any screen line, except for the first screen line or any other screen line's first character

![Soft-wrapped lines with indentation](https://cloud.githubusercontent.com/assets/6350880/16905560/65cb0ce4-4c6d-11e6-9349-32f29b808eb3.png)

**Expected behavior:** Cursor moves to beginning of current line

**Actual behavior:** Cursor moves to the end of the previous line
### Versions

OS X 10.11.5
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

**Comment by WSlatton** [comment]
The issue appears to be caused by the function `DisplayLayer.translateScreenPosition()` in the text-buffer package, which handles soft wrapping when calculating the position of the cursor. I've opened a copy of this issue there as [#161](https://github.com/atom/text-buffer/issues/161).
