### ISSUE TITLE
Redoing changes that include a new line mixes up line endings on Windows

### ISSUE THREAD

**Issue by miqid** [atom/atom#12198]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

When editing a text file, any changes including new lines that are applied using the redo option appear to be coerced to LF endings instead of CRLF endings as one might expect on Windows. I've only noticed this recently while editing files with some linter packages, which immediately highlight inconsistencies with line endings.

See my screen capture below for an illustration of this problem.

![redoproblem](https://cloud.githubusercontent.com/assets/2031402/16984950/df07d2ce-4eaf-11e6-8c07-4e8b300ec2a9.gif)

I had a quick poke around the Atom code base but nothing stood out to me. It's probably something to do with the `text-buffer` dependency.
### Steps to Reproduce

Enabling invisible characters will help visualise this problem.
1. Open a new file in Atom and add some lines using the <kbd>ENTER</kbd> key.
2. Undo all the lines (i.e. <kbd>CTRL</kbd> + <kbd>Z</kbd>).
3. Redo all the lines (i.e. <kbd>CTRL</kbd> + <kbd>Y</kbd>).

**Expected behavior:** All the line endings inserted by the redo action should use CRLF endings instead of LF.

**Actual behavior:** Redo actions insert LF endings.
### Versions
- Atom 1.8.0
- apm 1.9.2
- Windows 10 Pro

**Comment by nelson6e65** [comment]
Yes, I'm having the same issue. Line ending are mixed in windows.

**Comment by johnsonz** [comment]
same issue.

win 10 x64
