### ISSUE TITLE
Upgrading to Electron v1+? Better ES6 Support

### ISSUE THREAD

**Issue by bigtimebuddy** [atom/atom#12192]
The current version of Atom (v1.8) is using Electron v0.36.8 internally (`process.versions.electron`). Is there a plan to upgrade to Electron v1 +so that many more native ES6 features can be used via NodeJS 6+?

**Comment by 50Wliu** [comment]
@bigtimebuddy Please see https://github.com/atom/design-decisions/blob/master/electron-update-procedure.md.
