### ISSUE TITLE
Can't open file/folder or create new project in new window

### ISSUE THREAD

**Issue by Amet13** [atom/atom#12191]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I can't open file/folder or create new project in new window

### Steps to Reproduce

1. Open atom (I created project earlier)
![1](https://cloud.githubusercontent.com/assets/5184847/16922450/3cf44eaa-4d1e-11e6-95c3-bf224ba5bab2.png)
In this window all OK, i can open any files/folder
2. I want to create new window and open folder at this window (**File - New Window**)
![image](https://cloud.githubusercontent.com/assets/5184847/16922542/9fa239ae-4d1e-11e6-97cd-5d223f6312f7.png)
All OK at this step
3. Next I try to open some folder (**File - Open File**)
![image](https://cloud.githubusercontent.com/assets/5184847/16922568/c685480e-4d1e-11e6-8482-2ec2876c2891.png)
4. After OK button clicking i get an error
![image](https://cloud.githubusercontent.com/assets/5184847/16922582/dbb55962-4d1e-11e6-86c1-ddc04cb856e7.png)

**Expected behavior:** My folder must be open in new window
**Actual behavior:** I got an error

### Versions
```
atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1

cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"

uname -a
Linux mint-17 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by 50Wliu** [comment]
Please see #12182.

**Comment by 50Wliu** [comment]
Whoops, didn't realize that this was the issue I asked you to create...

**Comment by Amet13** [comment]
@50Wliu now I'm downloaded latest version from github, and now all OK. Thanks
