### ISSUE TITLE
Atom Save As...broken on Sierra Public Beta

### ISSUE THREAD

**Issue by SpiraMira** [atom/atom#12194]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Atom 1.9.0-beta0 saves files to the wrong directory when using the dialog expanded mode.
### Steps to Reproduce
1. Save As...
2. Select a directory using the Save As.. Dialog expansion. Navigate to a chosen directory
3. Press Save
4. File is saved at the same level as the selected directory and NOT within it.

**Expected behavior:** Save to the proper directory selected within the Save As.. dialog
**Actual behavior:** Only seems to happen when the Save As.. Dialog is expanded to allow Finder like navigation.  Saves at the same level as the directory selected and not within the directory itself. 

Have gotten it to work by not expanding and using the default Finder toolbar directory pull down only. Tricky. Workaround is of course to move the file in Terminal or the Finder etc..
### Versions

macOS Sierra Public Beta 10.12 Beta (16A238m)

atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.8.4

**Comment by mkreder** [comment]
macOS Sierra user here. This is a general problem of the public beta of Sierra. I saw it in several apps not only Atom is affected. I would say it is not an issue.

**Comment by shreyasminocha** [comment]
On macOS Sierra Version 10.12.2 (16C68), this does not seem to be an issue. Save-as works as expected.

**Comment by 50Wliu** [comment]
We've had no more reports of this, so closing.
