### ISSUE TITLE
I want to keep symlinked path when file opened with ATOM

### ISSUE THREAD

**Issue by pavel-odintsov** [atom/atom#12190]
Hello!

I have symlink component in my project's path. Atom is expanding it to the original path. But I want to keep "symlink" components inside it.

I have following environment.

Folder with files:

```
mkdir ~/myapp_original_path
echo "hello world" > ~/myapp_original_path/index.txt
```

Folder which uses files from first folder and do not store anything actually:

```
mkdir ~/myapp_symlinked_path
ln -s  ~/myapp_original_path ~/myapp_symlinked_path/myproject
```

ls -la output looks as following:

```
ls -al ~/myapp_original_path
total 8
drwxr-xr-x   3 pavel  staff   102 18 Jul 16:57 .
drwxr-xr-x+ 41 pavel  staff  1394 18 Jul 16:52 ..
-rw-r--r--   1 pavel  staff    12 18 Jul 16:55 index.txt
```

And for fake folder:

```
ls -al ~/myapp_symlinked_path/
total 8
drwxr-xr-x   3 pavel  staff   102 18 Jul 16:57 .
drwxr-xr-x+ 41 pavel  staff  1394 18 Jul 16:52 ..
lrwxr-xr-x   1 pavel  staff    32 18 Jul 16:57 myproject -> /Users/pavel/myapp_original_path
```

So I could use both patches for accessing index.txt (original):
`~/myapp_original_path/index.txt`

Or I could use path with symlink jump inside it:
`~/myapp_symlinked_path/myproject/index.txt`

But when I'm trying to open second path (with symlink component) with atom:
`atom ~/myapp_symlinked_path/myproject/index.txt`

I'm still getting original path:

``` /Users/pavel/myapp_original_path/index.txt```

And it broke my hack for Go enabled project. 

How I could tune / change this behaviour? I could accept source code changes too ;)
```

**Comment by pavel-odintsov** [comment]
Hello!

As I could understand, this issue related with Chrome project itself and I've created ticket for it too: https://bugs.chromium.org/p/chromium/issues/detail?id=629437

**Comment by TigersWay** [comment]
Would also really love to see that solved. No way to use Atom without it :-(

**Comment by TigersWay** [comment]
Not totally sure now but it seems only the popup content is "wrong": the file is in the opened/"symlinked" folder, but the path shown in the popup is the original one.
Anyone could check?

**Comment by TigersWay** [comment]
Just did a little test with the beta 1.14 and it seems to be solved :-)

**Comment by 50Wliu** [comment]
Thanks @TigersWay!  @pavel-odintsov if you're still experiencing this on Atom 1.14, please comment here and I'll reopen the issue.
