### ISSUE TITLE
Uninstalling failes for any package.

### ISSUE THREAD

**Issue by ajaykools** [atom/atom#12204]
### Description

Uninstalling “xxxxxxx” failed.
Failed to delete xxxxxxx: Does not exist

### Steps to Reproduce

1. Go to "File -> Settings"
2. Click on "Package" and select any package.
3. Click "Uninstall"

**Expected behavior:** 
Package should uninstall with success message.

**Actual behavior:** 
Package uninstalls but with error message as mentioned in description.

**Note:**
- package will not be in list if I restart Atom application.
- I noticed in windows 8 system

### Versions
Atom version in 1.8.0,

**Comment by IshanGupta10** [comment]
Tried to reproduce this in Windows 7, Atom 1.8.0 . When I clicked on uninstall, the package got uninstall but wasn't showing the install icon but showed Uninstall and Disable icons, even when I tried clicking the Uninstall icon repeatedly. It showed the package has been removed when I restarted Atom.

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.9.0-beta0 and above.
