### ISSUE TITLE
Right clicking in window doesn't give that window focus

### ISSUE THREAD

**Issue by zyklus** [atom/atom#12201]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I often have two atom windows open side-by-side.  If I right click on one (e.g. to create a new file), I often end up typing the file name in the other.  It's rather annoying.

Note that this is a different issue than #2991, I'm referring to focusing the entire window, not an item.

OSX 10.11.5
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

This is possibly an issue with Electron; if I should move it there let me know :)

**Comment by mnquintana** [comment]
This is how window management in macOS works – try right-clicking in any native Mac app (iTunes, Photos, Notes) and you'll find that the window doesn't get focused.
