### ISSUE TITLE
Dock menu: multiple entries of the same file

### ISSUE THREAD

**Issue by oaleynik** [atom/atom#12206]
### Prerequisites
- [✓] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
- [✓] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [✓] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [✓] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [✓] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [✓] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Multiple entries of of the same file in the right click menu.

![Screenshot](https://www.dropbox.com/s/fgtxcanra0p3wxa/Screenshot%202016-07-20%2023.43.16.png?dl=1)
### Steps to Reproduce

Not found.

**Expected behavior:** [What you expected to happen]

One entry per file in menu.

**Actual behavior:** [What actually happened]

Multiple entries for the same file.
### Versions

OS X El Capitan 10.11.6 Beta (15G26a)

Atom      : 1.8.0
Electron : 0.36.8
Chrome  : 47.0.2526.110
Node      : 5.1.1

**Comment by eastwood** [comment]
Would you be able to provide a zip of a folder that displays the multiple files? I'm running the same system as you and would like to attempt reproduction.

**Comment by oaleynik** [comment]
@eastwood unfortunately, no. This is the private project. But I will try to reproduce it using something synthetic.

P.S. Each duplicate item from menu is pointing to the same file in the project.
P.S.2. After some usage Atom consumes a lot of RAM. Highest I noticed was 4.1GB. I lost the moment and just restarted it, so I didn't catch the memory profile. I think it can be related to the multiple entries in the menu. Hope this will help somehow.

**Comment by eastwood** [comment]
@oaleynik Yea something synthetic would be preferable :) Yea I haven't been able to replicate this scenario, is the 4.1GB the memory consumption for `Atom` or the sum of `Atom Helpers`?

**Comment by oaleynik** [comment]
@eastwood Atom itself has very small memory footprint - around 80MB. But one of the multiple Atom Helpers is growing. See screenshot of what I have at the moment.

![Atom Processes](https://www.dropbox.com/s/o5gvc937ilh88mv/Screenshot%202016-07-22%2018.51.36.png?dl=1)
