### ISSUE TITLE
Where is beta 1, I used to make package for it :S

### ISSUE THREAD

**Issue by mpkh** [atom/atom#12215]
And now my package is failing to build, should I move back to beta0 or create snapshot by myself?

**Comment by fusion809** [comment]
Same question here, I bumped the AUR package `atom-editor-beta` to 1.9.0-beta1 (https://aur.archlinux.org/packages/atom-editor-beta).

**Comment by thomasjo** [comment]
There is no proper 1.9.0-beta1 yet, only a draft release. Not sure what happened, but likely just a hiccup or someone testing something.
