### ISSUE TITLE
[OSX] How to clear recently opened files? Or set max value?

### ISSUE THREAD

**Issue by aleclarson** [atom/atom#12217]
![](http://i.imgur.com/PhJobFqh.png)

There are at least 100 "recently opened" files when I swipe down with four fingers. There are also duplicates of the same files.
1. Can I clear this list?
2. Or maybe I can set a limit on the cache?
3. Or maybe it would be easier to just disable this "feature"?

Using Atom v1.8.0

**Comment by oBlissing** [comment]
![screenshot 2016-08-17 15 41 20](https://cloud.githubusercontent.com/assets/3618525/17738388/598f4454-6491-11e6-8d76-0b63616f1cdf.png)

Same issue with the dock menu. It's even the same files over and over.

**Comment by kalyan0510** [comment]
can I know which version of OS X u r using? Because on my machine ( El Capitan 10.11.6 ), I did not find such a big "recently opened" list. It is limited to 10 on both of the menus.

**Comment by aleclarson** [comment]
@kalyan0510 I'm using El Capitan 10.11.3

I'll try updating when I get the chance.

**Comment by oBlissing** [comment]
@kalyan0510
OS X 10.11 (15A284)

**Comment by aleclarson** [comment]
Upgrading to El Capitan 10.11.6 has fixed the problem. Thanks @kalyan0510!

**Comment by aleclarson** [comment]
After a month, I just noticed this issue came back. So upgrading the OS is not a permanent solution.
