### ISSUE TITLE
Block decorators don't work if `Use Shadow DOM` is false

### ISSUE THREAD

**Issue by n-riesco** [atom/atom#12222]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

The package [Hydrogen](https://github.com/nteract/hydrogen) uses block decorators. We've received a report that Hydrogen's block decorators are invisible when the setting `Use Shadow DOM` is false. See [this comment](https://github.com/nteract/hydrogen/issues/326#issuecomment-234727594).
### Steps to Reproduce
1. Install Hydrogen
2. Disable `Use Shadow DOM` under `Settings > Editor`
3. Run hydrogen, e.g. `hydrogen:run` on a line of python file.

**Expected behavior:** [What you expected to happen]

a block decorator showing the result of running that python line

**Actual behavior:** [What actually happened]

nothing happens
### Versions

```
$ atom --version
Atom    : 1.10.0-dev-3a4e251
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.7.4
```

Also fails with Atom 1.8.0 and 1.9.0

**Comment by mnquintana** [comment]
@atom/feedback I'm surprised we still have this config option – maybe we should consider removing it? Quite a lot in Atom assumes that the Shadow DOM's in use.

**Comment by crazymykl** [comment]
I would like to see #12212 land before the shadow DOM toggle is removed.

**Comment by 50Wliu** [comment]
Shadow DOM is being removed, so this shouldn't be an issue anymore.
