### ISSUE TITLE
Copy-Paste-Paste messes up indentation

### ISSUE THREAD

**Issue by carlmanaster** [atom/atom#12221]
This is probably related to a number of other issues, but I think I've got a pretty clear example of exactly what doesn't work and consider it more appropriate to file as its own bug than as a comment to one of the others ( #4747, #5046, #9045, #10407, etc.).  Atom's behavior breaks what is for me a very basic, very common practice and I think I can provide test cases which spell out the problem pretty clearly.

I know that to duplicate a selection of lines I can type shift-cmd-D, and that's OK - I've learned to do it and I use it.  But I shouldn't need that command, because there is a technique I practice in every other text editor which does not require learning anything new.  That is Copy-Paste-Paste.  That is:
select entire lines of text (with triple-click-drag or cmd-left, shift-down, shift-down)

1. copy (do not change the selection at this point)
2. paste (pastes content in place, leaving selection at the start of the next line)
3. paste again (pastes a copy after the original, indented identically to the original)

Or, in shorthand, cmd-CVV.  In my experience, this is a universally successful way of accomplishing a frequently useful operation, except for atom.  Here's what goes wrong when I try it with atom.

In step 2, instead of pasting the content in place, it outdents the selection to the left margin.  In step 2, instead of pasting the second copy indented identically, it indents it by the indentation of the final line of the block.  That is, if the final line was indented 8 spaces more than the first line, it indents my second pasted block by 8 spaces.  If I paste again, it adds yet another level of indentation.

This is something I do under many circumstances, but probably the most common are to add a new "case" block to a switch statement or to duplicate a small function.

I'm sure this behavior is the result of enabling some other, desirable, behavior, but this is not behavior I would want or can imagine wanting under any circumstances.  When I copy-paste in place, I do not believe the pasted code should have changed in any way.

**Comment by thomasjo** [comment]
Closing this since it's a duplicate (of several of the referenced issues, plus others). Thanks for the detailed report though 🙇

**Comment by carlmanaster** [comment]
Should I add it as a comment somewhere, then?
