### ISSUE TITLE
HTML Preview error and crash after saving

### ISSUE THREAD

**Issue by cmahurin** [atom/atom#12236]
### Prerequisites
- [Yes ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [Yes ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [YES ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [YES ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [YES (Assumed, Not Know) ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [YES ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

[The HTML Preview window will go blank after saving, does not show saved changes properly and will intermittently close/crash the program. The debug file is open when launching the program after a crash.  The program crashes in safe mode when I open my folder with the project I am working on.

[0725/210501:ERROR:crash_report_database_win.cc(412)] unexpected header

]
### Steps to Reproduce
1. Launch Application
2. Open Folder
3. Open index.html file
4. Open Stylesheet.css file
5. Use Key Command ctrl + SHIFT + H
6. (Optional) Make a change to the file in Atom
7. Use Key Command ctrl +S

**Expected behavior:** [What you expected to happen]
The file saves and the changes made will update in the html preview.
**Actual behavior:** 
Preview Window is dark and blank
App will close the program
### Versions

Atom : 1.8.0
Electron: 0.36.8
Chrome: 47.0.2526.110
Node: 5.1.1

Windows 7
Version 6.1.7601 Service Pack 1 Build 7601

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by mnquintana** [comment]
Can you post a list of your installed packages? (`apm list --installed`)

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12236#issuecomment-235169021. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by plexabyte** [comment]
I'm also having this issue. Here's my installed packages.

C:\WINDOWS\system32>apm list --installed
Community Packages (3) C:\Users\zachm\.atom\packages
├── atom-html-preview@0.2.2
├── git-plus@7.10.0
└── language-sml@0.7.0
