### ISSUE TITLE
hitting space scrolls page while searching for packages to install

### ISSUE THREAD

**Issue by dalexj** [atom/atom#12239]
### Description

searching for packages to install, when you type space into the search bar, the page scrolls

### Steps to Reproduce

1. open settings
2. go to install tab
3. type a space into the search bar

**Expected behavior:**

page stays still while I type

**Actual behavior:**

both a space character is entered and the page scrolls

### Versions

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
on mac OSX

**Comment by 50Wliu** [comment]
This is a duplicate of atom/settings-view#767 - feel free to subscribe there for updates.
