### ISSUE TITLE
I Can't Open Atom in Archlinux

### ISSUE THREAD

**Issue by creativefull** [atom/atom#12244]
atom version 1.8.0

```
[mshodiqul@muzaki streamhd2]$ atom -v
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
[mshodiqul@muzaki streamhd2]$ 

```

![screenshot at 2016-07-27 14 04 42](https://cloud.githubusercontent.com/assets/13174684/17166799/5b985040-5403-11e6-9641-3b6f4e4c30e4.png)

help me

**Comment by 50Wliu** [comment]
Please open a new issue and fill out the entirety of the _provided_ issue template.
