### ISSUE TITLE
Atom Helper crashed

### ISSUE THREAD

**Issue by davidak** [atom/atom#12245]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

i normally used the editor, placed the cursor on another line with the mouse, than it hangs and finally crashed. the bad thing is that my unsaved documents are lost, but the saved ones are fine. i hope the crash report helps.

https://davidak.basecom.de/paste/?697ce85863f6f098#iP9oxwL1DMHNgVjipgp7EYIKiq3u9fqJbYcnkKY03ck=

from system log:

```
Jul 26 11:50:53 unibook-2.local Atom[10849]: XPC error messaging com.apple.IconServicesAgent: Connection interrupted
Jul 26 11:50:53 unibook-2.local Atom[10849]: XPC error messaging com.apple.IconServicesAgent: Connection invalid
Jul 26 15:29:26 unibook-2.local ReportCrash[30557]: Saved crash report for Atom Helper[10854] version 1.8.0 (1.8.0) to /Users/davidak/Library/Logs/DiagnosticReports/Atom Helper_2016-07-26-152926_unibook-2.crash
Jul 26 15:30:36 unibook-2.local Atom[30629]: App load time: 561ms
Jul 26 15:47:13 unibook-2.local Atom[30629]: Cannot read property 'length' of undefined
Jul 26 15:47:13 unibook-2.local Atom[30629]: TypeError: Cannot read property 'length' of undefined
        at AtomApplication.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:707:40)
        at AtomApplication.module.exports.AtomApplication.openPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:712:10)
        at /Applications/Atom.app/Contents/Resources/app.asar/src/browser/atom-application.js:1040:24
        at Function.wrappedCallback (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:78:14)
```
### Steps to Reproduce

happened only once

**Expected behavior:**

stable textedior

**Actual behavior:**

crash, data loss
### Versions

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.9
git 1.9.5

OS X 10.9.5

**Comment by SpiraMira** [comment]
Noticed the same behavior on 1.9 beta1 atom helper related crash! Unsaved documents unrecoverable. I love this editor, but losing data in a text editor is so 90s. This has to be fixed.

**Comment by freedom26** [comment]
Similar thing (I guess) happened to me yesterday. I saved multiple big .js files quickly one after another. Atom crashed, and after reloading one of the .js files was suddenly empty, and saved like that. I've completely lost all of the contents of the file, and couldn't get it back, even in Time Machine backup the file was empty. 

**Atom version:** 1.8.0
**OS and version:** OS X 10.11.5

**Installed packages:**

color-picker
minimap

**Additional information:**

Crash report: http://pastebin.com/cbLuDRPC

* Problem can be reproduced in safe mode: I don't really want to try to reproduce it.
* Problem started happening recently, didn't happen in an older version of Atom: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [No]
* Problem happens with all files and projects, not only some files or projects: Don't know

**Comment by davidak** [comment]
Happened again with `de.txt` (289659 lines).

steps to reproduce:

1. download und unpack [de-2011.zip](https://github.com/atom/atom/files/392595/de-2011.zip) (1,7 MB)
2. open **de.txt** in Atom
3. "Find in Buffer"
4. "Use Regex"
5. try to type "` [0-9]+`", it will crash
6. if that might work, hit "Replace All", it will crash!

crash report:
https://davidak.basecom.de/paste/?6d4487da3241e84b#FTzpkeXora1jJAoeHgsTeig+whGIfb2vSEKvDsxfp4g=

PS: Click "Keep It Open" to not loose data in other Atom windows!

PPS: Works in Sublimetext 2, also the file loads a lot faster and scrolling is very smooth.

**Comment by davidak** [comment]
a process crashed after high RAM usage for some hours, editor still works.

![bildschirmfoto 2016-08-08 um 00 22 22](https://cloud.githubusercontent.com/assets/91113/17465755/7a52f700-5d00-11e6-96a7-46d00dfbff77.png)


https://davidak.basecom.de/paste/?57a5547d8a4f0d86#toGHJvQ429+U8GRnhfRU4ALNFhbh3vnul1y9wqUvHBc=

**Comment by davidak** [comment]
and again one atom window crashed while scrolling through a 4.6 MB file.

https://davidak.basecom.de/paste/?0fcc4af950bd3518#kSkLy7SbQYC2JIbObxEI1NYJEtCPF9i1T3Da3dho3lw=

please do something, this is a serious problem. maybe rewrite it in rust or go :P

**Comment by philoSurfer** [comment]
you can always fork!   OpenSource++ BitchLess++
