### ISSUE TITLE
Atom settings being resetting randomly when memory is full and starts swapping .

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#12255]
This is 3rd time , after computer restart atom's settings (every single setting) being resetted to default including re-enabling disabled packages .

It is very annoying. Just launching atom from commandline (as usual) is causing this.
And reproducing it is unreliable. It happens sometimes after restarting Laptop.

Atom : 1.8.0
OS : Sabayon Linux KDE , Kernel 4.6.0

**Comment by scippio** [comment]
Me too.

Atom : 1.11.2
OS: Archlinux

It is very painful when I must set up all my settings again :-1:
I think It happens after restarting Laptop or sometimes when using just...

**Comment by MrWilhelm** [comment]
This happened to me 5 minutes ago for the god's sake 5th time in last 2 months. I'm sick of having this issue. Totally randomly resets everything from the ground up and deletes anything, any data, any setting. I don't understand why is this happening.

**Comment by scippio** [comment]
2 times today! :sob:

**Comment by v3ss0n** [comment]
@scippio Your observation is right. It is happening whenever swap is full.
@MrWilhelm I am also spending more time on VSCode because of this issue, quite sad.

**Comment by scippio** [comment]
:sob: I had to setup all my plugins and keybindings today... again.

**Comment by v3ss0n** [comment]
@50Wliu  would be nice if someone looking into it , that is causing me to shift away from atom for a while. All the new releases not fixing it.

**Comment by scippio** [comment]
Nevermind.. I changed IDE to VSCode

**Comment by v3ss0n** [comment]
me too , but i am coming back to atom coz i miss the customizability and want to know how fast it become with v8snaphots . now testing master build , hoping the problem is fixed now.

**Comment by scippio** [comment]
maybe... but now I have the trouble to run it at all:

```
/usr/bin/atom -v
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
/usr/bin/atom -f
[30200:0517/102226:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.


#
# Fatal error in ../../v8/src/api.cc, line 1027
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
#

==== C stack trace ===============================

 1: V8_Fatal
 2: 0x7f6d7103c79e
 3: Repository::Init(v8::Local<v8::Object>)
 4: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 6: 0x7f6d710a0bb7
 7: 0x7f6d710a2986
 8: 0x222e6a4083e7
Failed to get crash dump id.
Report Id: 
```

**Comment by v3ss0n** [comment]
build from master and try.
