### ISSUE TITLE
Version 1.9.0-beta1 hangs and crashes on files only a few megabytes or tens of megabytes in size.

### ISSUE THREAD

**Issue by chadwickboggs** [atom/atom#12250]
I would not call these files large.  Atom 1.9.0-beta1 (and earlier) can only do tiny files.  I think this issue should have the highest priority.

**Comment by 50Wliu** [comment]
Can you share some more information on these files?  Are they publicly available?  If not, do they contain very long lines?

**Comment by KrasusC** [comment]
Actually Atom crashes frequently with large files in any version.
(Now I'm using 1.9.5)

**Comment by 50Wliu** [comment]
No new information was provided so I'm going to close this in favor of #8864.
