### ISSUE TITLE
提交一个中文无法输入的问题

### ISSUE THREAD

**Issue by Witee** [atom/atom#12257]
正在使用的是1.8.0版本，发现中文无法输入，1.7.x版本没有此问题，
重现问题的办法就是安装个中文输入法，然后输入。

**Comment by Witee** [comment]
我的操作系统版本是 OS X Yosemite  10.10.5

**Comment by Witee** [comment]
尝试过重装，更换其它中文输入法，都不能解决，换到旧版本就没有问题。

**Comment by Ben3eeE** [comment]
Sogou Wubi? https://github.com/atom/atom/issues/11988

**Comment by 50Wliu** [comment]
@Witee 下次请用英文，谢谢。请您看 #11988, 谢谢。

**Comment by Witee** [comment]
感谢，确认是Sogou Wubi。
Thx , I'm using Sougou Wubi.
