### ISSUE TITLE
The size of editor's scrollbar can not change

### ISSUE THREAD

**Issue by farell** [atom/atom#12251]
I add the following snippet to styles.less,but not satisfy my need, 
::-webkit-scrollbar {
    width: 15px !important;
    height: 15px !important;
}

and the result :
![text](https://cloud.githubusercontent.com/assets/2083201/17208850/e1c1ce82-54ec-11e6-8cde-da278e3dc724.png)

the size  of scrollbar of treeview on the left side is changed,but the right side editor's scrollbar's size remains the same:small enough that you can't see it,what I really want is to change the size of editor's scrollbar.

**Comment by 50Wliu** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
