### ISSUE TITLE
Searching for "git" fails

### ISSUE THREAD

**Issue by turion** [atom/atom#12259]
Probably more of a package manager server problem, but who knows.

### Steps to Reproduce

1. Go to "Settings" -> "Install"
2. Enter "git"
3. Hit "Enter"

**Expected behavior:** Find all packages relevant to git, or at least an articulated "Too many results error".

**Actual behavior:** An error like this:
```Searching for “git” failed.
Unexpected end of input: [{...```
(thousands of lines of JSON follow, with package description data)

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

1.8.0 on Linux Gentoo.

**Comment by 50Wliu** [comment]
I cannot reproduce this.  The package listing appears as expected.

**Comment by skwerlman** [comment]
I was able to reproduce this today.

```
Atom    : 1.8.0
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1
apm  1.9.2
npm  2.13.3
python 2.7.10
git 2.10.0
```

Using Sabayon Linux (maybe its a gentoo thing? sabayon is gentoo...)

**Comment by 50Wliu** [comment]
> Atom    : 1.8.0

You're on a pretty outdated Atom version.  Can you still reproduce this with Atom 1.10.2?

**Comment by skwerlman** [comment]
Running 1.10.2 without installing it, I no longer see the issue.

1.8.0 is the newest version available for my distro. Guess I'll have to ask the maintainers for an update.
