### ISSUE TITLE
Atom 1.8:  opening python file results in a currently open worksheet (of a different pythong file) being overwritten rather than an automatic creation of a new worksheet

### ISSUE THREAD

**Issue by Dowwie** [atom/atom#12254]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

opening python file results in a currently open worksheet (of a different pythong file) being overwritten rather than an automatic creation of a new worksheet

see attached screenshot 

![untitled](https://cloud.githubusercontent.com/assets/2601236/17226473/aec9b392-54d7-11e6-835d-27d9ceec82b6.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by Ben3eeE** [comment]
Pending pane items? http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html

**Comment by Dowwie** [comment]
oh thank you -- I think my lack of terminology made it harder to
troubleshoot

I don't like pending panes , for the record.  I'm going to de-activate them.
