### ISSUE TITLE
Sidebar AutoResize![treeview]

### ISSUE THREAD

**Issue by crperlin** [atom/atom#12268]
I see the widget library which provides a very compact and practical plug .. what can be built inside the atom ...

[tree-view-autoresize](https://atom.io/packages/tree-view-autoresize)

![image](https://cloud.githubusercontent.com/assets/10590799/14082869/a6132a20-f4cf-11e5-8640-e067730f7098.gif)

**Comment by hultberg** [comment]
This should be reported to the [tree-view](https://github.com/atom/tree-view) repository instead of atom core. The very fact that there is a package for this tells me that no changes in Atom core is required.

**Comment by 50Wliu** [comment]
Thanks @hultberg.

[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions and feedback, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
