### ISSUE TITLE
Atom 1.8.0 Fails to start on RHEL 7.2

### ISSUE THREAD

**Issue by bungojungo** [atom/atom#12264]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Fresh installation of Atom 1.8.0 from RPM does not load when opned via x2go client.

### Steps to Reproduce

1. Fresh install of Atom 1.8.0 RPM from Releases on RHEL 7.2
2. Open an XFCE (or any other desktop) with x2go client
2b. Alternatively, try and load as a single app. It won't work
3. attempt to start via CLI or X from within that x2go session
4. Atom will not load

**However, it does work via X forwarding**

**Expected behavior:** [What you expected to happen]

Atom editor will load in a full X environment

**Actual behavior:** [What actually happened]

[jscalia@x2g1-dpmgmt-smq ~]$ atom -f
[4461:0729/141655:ERROR:browser_main_loop.cc(203)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 506ms
[4461:0729/141656:ERROR:browser_main_parts.cc(116)] X IO error received (X server probably went away)

or

[jscalia@x2g1-dpmgmt-smq ~]$ atom
[jscalia@x2g1-dpmgmt-smq ~]$ App load time: 462ms

nothing further happens

### Versions

[jscalia@x2g1-dpmgmt-smq ~]$ atom --version && apm --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.5
git 1.8.3.1

[jscalia@x2g1-dpmgmt-smq ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)

[jscalia@x2g1-dpmgmt-smq ~]$ rpm -q atom && rpm -qi atom
atom-1.8.0-0.1.fc21.x86_64
Name        : atom
Version     : 1.8.0
Release     : 0.1.fc21
Architecture: x86_64
Install Date: Fri 29 Jul 2016 01:40:07 PM EDT
Group       : Unspecified
Size        : 238730707
License     : MIT
Signature   : (none)
Source RPM  : atom-1.8.0-0.1.fc21.src.rpm
Build Date  : Mon 06 Jun 2016 05:42:16 PM EDT
Build Host  : d9f210119bf3
Relocations : /usr 
URL         : https://atom.io/
Summary     : A hackable text editor for the 21st Century.
Description :
A hackable text editor for the 21st Century.

Thanks!

**Comment by 50Wliu** [comment]
Closing in favor of #4360 - feel free to subscribe there for updates.

**Comment by northeastsquare** [comment]
Hack worked vscode works via xrdp in Ubuntu MATE 16.04:

make a backup first
sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /usr/lib/x86_64-linux-gnu/libxcb.so.1
https://github.com/Microsoft/vscode/issues/3451
