### ISSUE TITLE
Atom doesn't automatically refresh archive hosted in another machine

### ISSUE THREAD

**Issue by lgb3** [atom/atom#12263]
When editing files hosted in another machine, if the file changes (outside Atom), then it will not refresh them, not even signalize that they are out-date. There isn't also an option to force the refresh of the file (os is there?). This is very annoying when I can change the file outside atom (for instance by updating my repository).

Other editors detect when the file changes, signalize it and offer the user the ability to reload it, or to overwrite it.
- the autorefresh mechanism **works when working on files hosted on the same machine**.
- I'm on OS X El Capitan
- I'm using **samba** to mount the external files in my machine.
  
  atom --version
  Atom    : 1.8.0
  Electron: 0.36.8
  Chrome  : 47.0.2526.110
  Node    : 5.1.1

**Comment by clasimoes** [comment]
Noticed the same issue.
