### ISSUE TITLE
Crashes when a file contains more than 1000 lines

### ISSUE THREAD

**Issue by ikasyk** [atom/atom#12265]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When I open a big PHP file (for example, one of [Xsolla files](https://github.com/xsolla/xsolla-sdk-php/blob/master/src/API/Resources/xsolla-2015-07-23.php)) and press Enter (to create new line) on line number 1500+, Atom brakes and sometimes crashed when amount of text is bigger.
### Steps to Reproduce

1. Open a big PHP file
2. Scroll to a line 1500+
3. Focus on line and press Enter to create a new line.

**Expected behavior:** Atom don't brakes (for example, Sublime Text doesn't brake).

**Actual behavior:** Atom brakes

### Versions

OS X El Capitan
10.11.5

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4

**Comment by Innectic** [comment]
No issues on a fresh install. Do you have lots of plugins?

My versions, if it matters:

```
➜  ~ apm -v
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.7.4
```

**Comment by ikasyk** [comment]
I use Remote-FTP, color-picker and emmet.
When I turned all plugins off, it's nothing changed.

**Comment by Innectic** [comment]
Hmm, any crash logs? I'm not sure where atom stores them (if it does)

**Comment by ikasyk** [comment]
It crashes rarely, usually it brakes.
I've write it on video https://youtu.be/V99NAGmJecw.

**Comment by alexkaessner** [comment]
I'm experiencing the same problem. Over the last weeks I had to work with huge `JSON` files (~3MB big). Atom sometimes crashes and almost every time freezes if I opened them, especially if I searched in them. Okay to be honest this is a big task for this file size. 😁 But a powerful editor should handle this.

**Comment by jfredsilva** [comment]
I also have issues with big files. I was forced to install another text editor to work with big files

**Comment by kachkaev** [comment]
Is it still the case with 1.9.0 guys? Or has the problem got fixed? I'm about to upgrade from 1.8.

**Comment by jfredsilva** [comment]
I still have this issue with the 1.9.0 version on Windows

**Comment by mnquintana** [comment]
@ikasyk Just to check, did you try seeing if you could reproduce this in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? (Not just manually disabling all your packages.)

**Comment by ikasyk** [comment]
@mnquintana yes, it works quickly in safe mode, but why it can't work in normal mode?

**Comment by Zireael07** [comment]
@ikasyk Then something is wrong with your packages.

**Comment by mnquintana** [comment]
@ikasyk I recommend reading through the docs on [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) – it opens Atom without loading community packages or any custom scripts / styles you might have added. If you can't reproduce it in safe mode, then like @Zireael07 said, one of the community packages you have installed is the culprit.
