### ISSUE TITLE
Atom keep crashing! although I reinstall it in my Ubuntu16.04 machine

### ISSUE THREAD

**Issue by basselAlshK** [atom/atom#12260]
when I am using Atom, it keeps crashing, and this the message that I get from the system 
atom crashed with sigsegv in V8:string::newFromutf8()

**Comment by NotBad4U** [comment]
Same problem on ubuntu 14.04

**Comment by 50Wliu** [comment]
What version of Atom is this?

**Comment by NotBad4U** [comment]
Atom Editor v1.5.3
The problem doesn't happen in --safe mod.

**Comment by 50Wliu** [comment]
First of all, your Atom version is extremely outdated.  The current stable version is 1.8.0.

Second, if the crash does not happen in safe mode, that means one of your installed packages is causing the issue.  A list of all your packages is available at `~/.atom/packages/`.
