### ISSUE TITLE
Disable tab stops as the Sublime Text's option "use_tab_stops: false"

### ISSUE THREAD

**Issue by addonszz** [atom/atom#12275]
Where is this option over atom? 

    // Set to true to insert spaces when tab is pressed
    "translate_tabs_to_spaces": false,
   
    // If translate_tabs_to_spaces is true, use_tab_stops will make tab and
    // backspace insert/delete up to the next tabstop
    "use_tab_stops": false,

It is simple, it is horrible to this editor keep deleting all my dear 4 spaces every time I hit the delete button.

**Comment by 50Wliu** [comment]
This feature is now available in Atom 1.9.0-beta0 and above!  To enable, simply uncheck the "Atomic Soft Tabs" option in the Settings View.  Hope that helps!
