### ISSUE TITLE
New way of naming component or zipped package...

### ISSUE THREAD

**Issue by duytrung** [atom/atom#12270]
Hi all,

I have used Atom for a few weeks and really love it. I found that there is a portable version of Atom to use in the USB sticks (at Sourceforge). I copied the files in ~ .atom folder the respective folder in the USB so that all plugins are available to use for the portable version.

However I have encountered problems:

1. Plugins sometime have filename/path exceed 256 chars. Using explorer copy function doesn't work.
2. Update of plugins, for both of installed and portable version sometime took too long to complete.

My question are:

Is there any kind of **_"enhance proposal"_** or **standard** to make Atom more convenient in handling components/plugins? For example, all plugin are packed in a zip-based archives so that installation and update of these stuffs become more convenient and faster. It also make disk access faster someway because normally there are too many files in the plugin folder.

Thanks!

TN

**Comment by 50Wliu** [comment]
There is currently no way to "make Atom more convenient in handling [packages]", though the next Atom beta (1.10.0) will have an updated version of `npm` which should fix the path length issue.  That update of `npm` might also make package updating faster.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
