### ISSUE TITLE
Atom crash with low system memory message

### ISSUE THREAD

**Issue by knzudgt** [atom/atom#12271]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
  Not so far, although I am now using Atom in safe mode
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
  Atom 1.8.0
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Atom crashed twice in a week with multiple open tabs during editing of simple text file.
The cursor stops responding to commands, then stops blinking, then a warning message appears informing that 'The editor has crashed'. The second time a system warning message informed that there was not enough memory to analyse the problem and send a report.

At present I am trying Atom in safe mode and monitoring it.

![screenshot from 2016-07-31 14 41 15](https://cloud.githubusercontent.com/assets/15718033/17276747/7d1538d2-5732-11e6-9365-5ffcec0cea95.png)
### Steps to Reproduce

Before I did not experience any issue.
Moreover I did not change my usual configuration, and the editor started to crash during simple tasks, like editing a text file.

My installed packages are:

Core Packages (77)
Community packages: file-icons, linter, linter-ruby

Installed themes:

Core themes (12)
Community themes: dark-flat-ui, outlander-syntax

Along with Atom, other running applications are:

Firefox: two windows with about 12 tabs each
terminal (inactive)
Files (file manager)
Document viewer (pdf viewer)
SMPlayer
Audacious

Only Atom actually crashes

**Expected behavior:** normal functioning

**Actual behavior:** crash
### Versions

me@SATELLITE-L50-A-161:~ $ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

me@SATELLITE-L50-A-161:~ $ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 2.9.2

OS: Ubuntu 14.04.4 LTS
Memory: 5,7 GiB
hard disk: 16,4 GB used, 444,3 GB free

me@SATELLITE-L50-A-161:~ $ top
KiB Mem:   5983776 total,  4000268 used,  1983508 free,   302832 buffers
KiB Swap:  6163452 total,   202924 used,  5960528 free.   901984 cached Mem

Notebook: Toshiba satellite L50-A-161

**Comment by 50Wliu** [comment]
In the future, please **completely** fill out the provided issue template (it's there for a reason).

Now for a few questions:
1) Does this still happen in safe mode (`atom --safe`)?
2) How did you install Atom?
3) Did it crash while editing the same text file?  If so, can you share that file?

**Comment by knzudgt** [comment]
I added the missing part of the issue template to the original report message.

As for your questions:
1) I usually work in the weekend, but I started to use Atom in safe mode in my spare time.
    So far (I started yesterday, after the last crash) I could not reproduce the problem in safe mode, though I would not be able to tell how to reproduce it in normal mode.
2) I installed Atom following the [instructions](https://github.com/atom/atom#debian-linux-ubuntu) reported in this depository. I also made several updates following the same instructions.
3) Atom crashed editing the same file. It is a file with no extension, called 'RailsTutorialComplement' of about 1300 lines, with size of about 40 KB that I use to jot down a tutorial for my Rails project. The file mixes up simple text instructions with Ruby code, using the same approach of M. Hartl Rails tutorial, which my project is largely based on. I made a screenshot of part of this file below, and something is also visible in my first screenshot in my original message. As you can see, as I said, the files mixes up text and code. Let me know if it is enough or if you still need a copy of this file and if it is possible to share it with chosen github users.

![screenshot from 2016-08-01 15 48 02](https://cloud.githubusercontent.com/assets/15718033/17296280/b2f7608c-5800-11e6-966d-b1d0c676b355.png)

**Comment by 50Wliu** [comment]
Thanks for the info!

If you feel uncomfortable with publicly sharing the text file, you can email it to `atom@github.com` (and be sure to direct them to this issue for context).

**Comment by knzudgt** [comment]
email with attached file sent to `atom@github.com`.

**Comment by knzudgt** [comment]
Atom crashed today while it was running in safe mode

**Comment by 50Wliu** [comment]
:(

I'll try to take a look at that file later today.
