### ISSUE TITLE
atom 1.9 autocomplete position not correct ,just look at the picture as below

### ISSUE THREAD

**Issue by toplinuxsir** [atom/atom#12279]
![image](https://cloud.githubusercontent.com/assets/1111353/17312826/54d39cea-5888-11e6-842a-dd9e51578ebf.png)

### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by Chofoteddy** [comment]
The same problem, I use Ubuntu 16.04 LTS.

![screenshot from 2016-08-01 19-46-21](https://cloud.githubusercontent.com/assets/1615875/17313381/b68ede9e-5820-11e6-963b-bcfdbc70c643.png)

**Comment by toplinuxsir** [comment]
I think it is a critical bug , It should be fixed immediately !

**Comment by mnquintana** [comment]
Can you reproduce this in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by toplinuxsir** [comment]
In safe mode it works ok

**Comment by toplinuxsir** [comment]
I can not reproduce this in safe mode.
In safe mode It works ok.

**Comment by OctoNezd** [comment]
It`s bug in activate-power-mode add-on. If I disable it, bug don`t work, if enable, autocomplete position is wrong

**Comment by 50Wliu** [comment]
As safe mode works fine, people affected by this "bug" may want to use the [package-cop](https://atom.io/packages/package-cop) package to figure out which package is causing this issue.

**Comment by toplinuxsir** [comment]
Yes， It's active-power-mode bug！
