### ISSUE TITLE
Comment out JS line results in removal of first character.

### ISSUE THREAD

**Issue by drj-io** [atom/atom#12273]
Just here to report. 

 
![jul-31-2016 15-47-23](https://cloud.githubusercontent.com/assets/444485/17279630/3ab3bfe6-5736-11e6-8476-85aa0b1f34ab.gif)

Feel free to close if dupe, didn't have time to write a full report at the moment, but wanted to show it.

Using Javascript

**Comment by 50Wliu** [comment]
Does this happen in safe mode (`atom --safe`)?

**Comment by iamstarkov** [comment]
@drj-io can you re-try with `atom --safe`?

**Comment by drj-io** [comment]
Haven't seen the issue since in save mode or otherwise.
