### ISSUE TITLE
It can be very difficult to determine grammar names for config.cson

### ISSUE THREAD

**Issue by OJFord** [atom/atom#12288]
I've too many times spent far too long (and even given up) trying to find grammar names. Sometimes `.source` comes before the language; sometimes after. For some reason HTML has `.basic`.

There's no clear pattern to follow, and the status bar will only give what we probably already know - e.g. `YAML`.

Even hunting through the developer tools will only give you the attributes e.g. `source` and `yaml` - not an order.

This could be fixed just by documentation, but ideally I think it would be great to see something like a 'tooltip' on hover over the current grammar/button to open selector that's in the lower left. So it would still say "YAML", but if I hovered a small ".source.yaml" would appear.

**Comment by bastilian** [comment]
You can find the scopes with the "Log Cursor Scope" (alt-cmd-p). It will show the selector for the current position of the cursor.

It is not mentioned yet in the documentation but i've just opened an issue to add it. [#atom/flight-manual.atom.io/248](/atom/flight-manual.atom.io/issues/248)

**Comment by OJFord** [comment]
Sounds perfect, thanks @bastilian!
