### ISSUE TITLE
Tree sidebar no longer able to scroll horizontally

### ISSUE THREAD

**Issue by shannonjohnstone** [atom/atom#12298]
My Atom has updated to 1.9.0 and it seems that the tree sidebar view has lost the ability to scroll horizontally to view the entire file name if it's longer than the width of the tree view.

So with 1.8.0 i could scroll horizontally with either my trackpad or my mouse but now it seems this no longer works and i have to make my tree sidebar wider and this seem not right as i have been able to do this previously. 

Im on  Mackbook pro and using Atom 1.9.0

**Comment by 50Wliu** [comment]
@shannonjohnstone Can you please reopen this issue on [atom/tree-view](https://github.com/atom/tree-view)?  Thanks!
