### ISSUE TITLE
Question: Does atom have unit tests for its code base?

### ISSUE THREAD

**Issue by nitrocode** [atom/atom#12307]
Does atom have unit tests for its code base? If so, how may I run them?

Thanks

**Comment by 50Wliu** [comment]
Yes, it does: https://github.com/atom/atom/tree/219c92f6fb54eba7c75fb82bab667eca977f9fed/spec
Run them using `atom --test spec`.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
