### ISSUE TITLE
find in current directory does not work, always showing "no result"

### ISSUE THREAD

**Issue by wik3** [atom/atom#12305]
Hello everyone,

On Windows 7 and with Atom 1.10.0-beta0, I try to find text in the current directory of a file with Alt-a, project-find:show-in-current-directory. The file is not in any project. Regardless of what I try to find, Atom shows "no result". 

To reproduce, I did:

1. Create empty %userprofile%\.atom
2. Download and install Atom 1.10.0-beta0
3. Start it with 'atom --safe'
4. Open any text file
5. In the tree view, delete the project that was created when the file was opened (because I would like to search in the file's current directory, independent of any project)
6. Alt-a. The dialog pre-populates with the absolute path to the directory of the file
7. Enter search text and press 'enter'

Expected: list of occurrences
Actual: "no result"

**Comment by 50Wliu** [comment]
@wik3 In the future, please completely fill out the provided issue template.  If you had, you might have noticed that the correct repository to report this on is [atom/find-and-replace](https://github.com/atom/find-and-replace), so please reopen this issue over there.
