### ISSUE TITLE
c++ file class closing bracket semicolon in need

### ISSUE THREAD

**Issue by daubaris** [atom/atom#12302]
Hello, 
I've recently downloaded atom and started writing c++ code on it. It's amazing although one thing, when starting a class, closing brackets does not have a semicolon. It just looks like this
`#include <iostream>
class Something {
public: //something
private: //something
} //should have semicolon

int main {
  /*something*/
}`

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/language-c? Thanks!
