### ISSUE TITLE
Creating a new file takes a long time

### ISSUE THREAD

**Issue by joshaber** [atom/atom#1230]
I'm seeing anywhere from 2-5 seconds to create a new file when I hit command-N.

**Comment by benogle** [comment]
Is this still a problem? `cmd-n` It's near instant for me. For startup speed, we should refer to #3673

**Comment by joshaber** [comment]
I'm on a newer computer now so I can't give a direct comparison.

Window load time is now ~800ms. Better though still noticeably slow.

**Comment by benogle** [comment]
Closing as `cmd-n` isnt really the issue, it's startup speed.
