### ISSUE TITLE
Update page doesn't show newest release version and notes

### ISSUE THREAD

**Issue by JSn1nj4** [atom/atom#12311]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? _This only happens when there's a new release._
- [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? _This happens just before updating to the latest version._
- [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? _I didn't get the chance to before this happened._
- [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)? _Yes._
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? _I'm fairly certain this is the correct repository, since it has to do with the core updater (or maybe just the About/update tab)._
- [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported? _Yes._

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

The atom updater, when there's a new update, always shows the currently-installed vesion.
### Steps to Reproduce
1. Wait until there's a new release
2. Click the Squirrel icon in the lower-right

**Expected behavior:**

The Restart & Update section on the About tab should show the newest release version and link to its notes.

**Actual behavior:** [What actually happened]

The Restart & Update section shows the _currently-installed_ version number and links to the _currently-installed_ version's release notes.

![atom-updater-wrong_version_and_notes](https://cloud.githubusercontent.com/assets/5084820/17374133/2e1af480-5979-11e6-9e6f-222d19aecd17.png)
### Versions

Windows version

```
ver
Microsoft Windows [Version 10.0.10586]
```

Atom version

```
atom --version
Atom: 1.9.2
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0
```

Atom package manager version

```
apm --version
apm: 1.10.0
npm: 2.13.3
node: 0.10.40
python
git
Visual Studio
```

Since I'm on Windows, the `apm --version` colors may not be displaying correctly. I had a hard time reading the Node version output for that command.

Also, as far as I know, this has been happening at least since Atom 1.5 or 1.6. I just didn't think to report it until now.

**Comment by joegilley** [comment]
before updating to 1.9.9
```
. atom --version
Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

. apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.9.3

                 -/+:.         
                :++++.          OS: 64bit Mac OS X 10.11.6 15G31
               /+++/.           Kernel: x86_64 Darwin 15.6.0
       .:-::- .+/:-``.::-       Uptime: 19d 23h 56m
    .:/++++++/::::/++++++/:`    Packages: 192
  .:///////////////////////:`   Shell: bash 3.2.57
  ////////////////////////`     Resolution: 2880x1800
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue
 :ssssssssssssssssssssssss-     Font: Inconsolata-Regular 13
  osssssssssssssssssssssssso/`  CPU: Intel Core i7-4870HQ CPU @ 2.50GHz
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  GPU: Intel Iris Pro / NVIDIA GeForce GT 750M
   `ossssssssssssssssssssss/    RAM: 10382MiB / 16384MiB
     :ooooooooooooooooooo+.
      `:+oo+/:-..-:/+o+/-
```
![image](https://cloud.githubusercontent.com/assets/1476969/17834856/4ef1b1d4-6708-11e6-8338-eecbdb5fcb6f.png)

**Comment by JSn1nj4** [comment]
Still happening for me too. I just updated from 1.9.9 to 1.10.0. Nothing to see yet for 1.10.0, but it did it on 1.9.9.

**Comment by JSn1nj4** [comment]
Updated original comment. Meant to say that the squirrel icon was on the lower-right, not lower-left.

**Comment by Ruben9922** [comment]
Also noticed this when updating from 1.9.8 to 1.10.0, but have noticed this several times when upgrading previously.

![image](https://cloud.githubusercontent.com/assets/14931620/18233408/98987c00-72de-11e6-9ca0-3f71613f4d83.png)

**Comment by Kuuak** [comment]
Still buggy before update to 1.12.3 on MacOS.

```
$ atom --version 
Atom    : 1.12.2
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.8.3

$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2555
```

![atom-update](https://cloud.githubusercontent.com/assets/6989959/20343700/bc751c42-abef-11e6-9c08-a09130e9314e.jpg)

Thanks

**Comment by JSn1nj4** [comment]
Still the same for me as for @Kuuak, but on Windows 10.

**Comment by petewalker** [comment]
Same for me when updating to 1.12.4 on macOS

**Comment by petewalker** [comment]
I wrote about my findings on this issue here: https://github.com/atom/about/issues/44#issuecomment-261502634

**Comment by lee-dohm** [comment]
Closing this Issue since this should be on the atom/about repo. Thanks for creating the new Issue @petewalker :grinning:

**Comment by sbrl** [comment]
For people who find this issue when googling it, you want atom/about#44.

**Comment by Ruben9922** [comment]
Seems to be ok for me now. Running macOS 10.12.3 with Atom 1.13.0.

**Comment by sbrl** [comment]
@Ruben9922 Not for me on Windows 10!

**Comment by petewalker** [comment]
Can you please direct any comments to the (open) active issue on atom/about#44 - this issue is closed and not the correct forum.
