### ISSUE TITLE
Cursor keeps switching back to pointer instead of i beam

### ISSUE THREAD

**Issue by whaaaley** [atom/atom#12314]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

The cursor keeps switching back to a pointer instead of an i beam.

[![https://gyazo.com/86f19cdd229d3db894a327cfeb6eee80](https://i.gyazo.com/86f19cdd229d3db894a327cfeb6eee80.gif)](https://gyazo.com/86f19cdd229d3db894a327cfeb6eee80)
### Steps to Reproduce
1. Focus away from atom window
2. Bring atom window into focus
3. Click on a few lines of text
4. Watch the cursor revert to a pointer

**Expected behavior:** The cursor should remain an i beam

**Actual behavior:** The cursor reverted to a pointer
### Versions

1.9.2 | 1.9.3 | 1.9.4
### Additional Info

OS: OS X El Capitan: 10.11.6
Syntax and UI Theme: Atom One Dark

Moving the cursor to the sidebar and back to the editor temporarily fixes the problem.

**Comment by maxbrunsfeld** [comment]
Could you report your OS and your syntax and UI themes?

**Comment by dustindowell22** [comment]
OSX 10.11.6
syntax and ui are default

**Comment by dustindowell22** [comment]
more info:
moving the cursor to the sidebar and back to the editor temporarily fixes the problem

**Comment by dustindowell22** [comment]
Still happens in atom 1.10.1

**Comment by jimbonator** [comment]
I'm still seeing this in Atom 1.19.5.

**Comment by 50Wliu** [comment]
@jimbonator are you also on macOS?  What Atom version are you currently running?

**Comment by jimbonator** [comment]
As mentioned, Atom 1.19.5.  I'm on MacOS using Atom Dark theme.

**Comment by 50Wliu** [comment]
Oh whoops, I missed that by accident 😓.  Does adding the following to your `styles.less` file help?
```less
atom-text-editor.editor {
  cursor: text;
}
```

**Comment by jimbonator** [comment]
I still see this with the above change to styles.less, although it's not as easy as it once was to lose the I-beam.

Here's one way to reproduce the problem now:

* Select some text
* Right-click on the edit pane
* Dismiss the popup menu by left-clicking on the edit pane

The cursor will now be a standard arrow.  Moving it off the pane and back on (or switching windows) will reset it to an I-beam.

**Comment by 50Wliu** [comment]
By "edit pane", do you mean the active text editor where you selected the text?

**Comment by jimbonator** [comment]
Yes.

**Comment by 50Wliu** [comment]
Ok.  I'm tentatively tagging this as macOS-only because I can't reproduce it on Windows.

**Comment by rsese** [comment]
I can repro in safe mode with the steps in https://github.com/atom/atom/issues/12314#issuecomment-328176336, though step 1 wasn't necessary for me:

![pointer](https://user-images.githubusercontent.com/734194/30839111-661ab78e-a235-11e7-8cab-4e83d0d9776a.gif)

**Comment by mepatterson** [comment]
I'm seeing this same issue now, too. I wasn't having the problem on MacOS Sierra, but now can reproduce it reliably (with same steps as mentioned above) on High Sierra on a brand-new MBP with fresh install of Atom using Pristine theme.

**Comment by tadeusgregorian** [comment]
same problem here on Mac, El Capitan

**Comment by runfaj** [comment]
Also having the issue in Mojave, v1.32.2. It's not a huge deal though, especially because apple doesn't have any other consistent cursor behaviors (e.g. the dock and menu bar never get the pointer cursor).

**Comment by eduardonunesp** [comment]
It's happening to me too, using other editors too, tried VSCode, Intelij and sometimes when I navigate back to the editor the cursor stay as pointer instead of change to I-bean

**Comment by whaaaley** [comment]
I haven't seen this in a long time. Could still be an issue, but I'm using VSCode now since development on Atom is pretty slow now. Closing this issue since it's 4 years old now and I'm cleaning my issues. o/
