### ISSUE TITLE
Merge "Install" section with "Packages" section

### ISSUE THREAD

**Issue by adambuczynski** [atom/atom#12316]
I can't count anymore how many times I've wanted to install a new package, went to settings, clicked "Packages" and started to type the package name in the search box waiting and staring at the screen while nothing happened...

The two interfaces "Packages" and "Install" are so similar that it's really hard to keep the two apart. Why don't we merge them into one, called "Packages" to avoid confusion?

To me it seems intuitive that if you want to install "packages" you go and click on "packages" first, especially since that's the first item that you see when you're scanning the menu options from top to bottom.

Even adding a "install new packages" button in the "packages" section linking to the "install" section would help tremendously I think.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/settings-view? Thanks!

**Comment by adambuczynski** [comment]
Will do, cheers.
