### ISSUE TITLE
Windows 10 1607 Build 14393.10 - "Open with Atom" doesn't work

### ISSUE THREAD

**Issue by Lordmau5** [atom/atom#12315]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I updated to the Win10 Anniversary Build today and wanted to edit some files, but whenever I select the specific option in the context menu (right-click), Windows asks me which program I should use to open the specific file with.

I also reinstalled Atom already, just to be safe.

### Steps to Reproduce

1. Have Windows 10 1607 Build 14393.10 (Pretty much the anniversary build)
2. Try to rightclick any file and select "Open with Atom"

**Expected behavior:** Open the specific file in Atom

**Actual behavior:** Windows asks me with what program I want to open the file

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.10.0-beta1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Windows 10 1607 Build 14393.10

**Comment by 50Wliu** [comment]
I'll try reproducing this once I get Atom set up again.

**Comment by Lordmau5** [comment]
Thanks for the quick response! :)

It has to be some change in the anniversary build that is causing this, since it worked fine before.

Another thing, which is unrelated to Atom, is, that Start10 (a tool to replace the start menu so it looks like the Win7 one again) is not able to search for programs in the "Program Files (x86)" folder since the anniversary update.

**Comment by 50Wliu** [comment]
Cannot reproduce with in safe mode, Atom 1.11.0-dev-c381b93, Windows 10 x64 Anniversary Build.

**Comment by Lordmau5** [comment]
What do you mean, "in safe mode"?
How would the right-click option work with safe-mode O_o

Can you tell me how you got that working so I can try it as well, please?

**Comment by 50Wliu** [comment]
I meant Atom's safe mode (`atom --safe`), though that wouldn't really affect anything in this case.

**Comment by Lordmau5** [comment]
Ah. Well yea, that's why I didn't tick it in the first place - I thought it's useless to try it in safe-mode (wouldn't even know how that would affect anything anyway for the context menu).

Also another interesting thing that I just found out is, that if you are in a folder and rightclick the empty space and select "Open with Atom", it should bring up Atom within that folder (as in, show all the files and such).

However, it shows a message that, translated, says something along the lines of "Program not found.":
![.](https://i.lordmau5.com/1470264717-1796.png)

**Comment by 50Wliu** [comment]
Can you try unchecking and rechecking the new options in Settings -> System?

**Comment by Lordmau5** [comment]
Which options? As in, where can I find them?

**Comment by Lordmau5** [comment]
Ah!
I enabled "Show in file context menus" and "Show in folder context menus" now and it shows up "Open with Atom Beta" now.
![.](https://i.lordmau5.com/1470265091-1797.png)

Any idea how I can remove the "Open with Atom" one though?... :D

**Comment by damieng** [comment]
The installer for beta unfortunately overwrites/upgrades non-beta.  Will look into it.

**Comment by yaso9** [comment]
This issue happened to me to when I used to use windows 10 insiders preview but instead of saying program not found windows explorer would crash.

**Comment by damieng** [comment]
If you are installing 1.10 beta we recommend first uninstalling 1.9 rather than 'upgrading' for now. Long-term beta versions will install alongside non-beta but that's not yet ready for prime time.

**Comment by verlok** [comment]
Sorry for necroposting, I just want to report that I had the same problem on **Windows 8** with the following version.

```
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

The solution that worked for me was checking the new options in the Settings -> System pane, so:

* Register as file handler
* Show in file context menus
* Show in folder context menus

Thank you

**Comment by Ben3eeE** [comment]
There was a problem introduced with the new Systems tab causing the shell integration to not get updated when upgrading Atom, this has been fixed on master already. In the meantime the solution that @verlok posted is the correct one if you are facing this issue.
