### ISSUE TITLE
Opening a new window from the shortcut or file menu opens the dev tools window.

### ISSUE THREAD

**Issue by mikedoth** [atom/atom#12329]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The dev tools opens when a new window should in 1.9.3 on the PC. It works fine if I roll back to 1.9.2.

### Steps to Reproduce

1. Open Atom.
2. Click file, "New Window" or the key binding for it.
3. Watch it open the dev tools.

**Expected behavior:** Open a new window.

**Actual behavior:** Opens the dev tools window.

### Version: 1.9.3

**Comment by dvigne** [comment]
This is in regards to issue #12328, they're working on releasing a patch shortly for 1.9.4

**Comment by 50Wliu** [comment]
Thanks @dvigne.
