### ISSUE TITLE
Git status coloring in tree view disappears - 1.9 OSX

### ISSUE THREAD

**Issue by willdady** [atom/atom#12320]
Title is self explanatory. I can replicate by:

1. Open Atom in safe mode
2. Add a project which you know to have changes. Git status coloring usually appears fine at this point.
3. Switch focus to another app, then back to Atom and you can _see_ the colours disappear back to the normal default colours.

El Capitan 10.11.4

Atom    : 1.9.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by superlin** [comment]
+1

**Comment by BlackSkorpio** [comment]
Can be replicated under Win7 & Atom 1.9.2

**Comment by Stax** [comment]
+1
Atom : 1.9.2
OS X 10.11.5

**Comment by arcticicestudio** [comment]
Already reported at [atom/tree-view #906](https://github.com/atom/tree-view/issues/906).

**Comment by 50Wliu** [comment]
Closing in favor of the aforementioned atom/tree-view#906.
