### ISSUE TITLE
Cant Install ATOM

### ISSUE THREAD

**Issue by davidayers** [atom/atom#12324]
### Description

I am unable to install the latest version of ATOM. I tried download it directly from the website (the main download button on the front page). I have ran it as administrator. I have had atom on my PC since the beginning. I just realized though that its not in my list of installed programs. Github's windows client has a new ATOM button that doesn't appear (because atom i believe is not installed correctly) How can I install it correctly or fix my current installation. I do have the [SquirrelStetup.log](http://theaamgroup.com/hosting/SquirrelSetup.log)

I have removed all traces of ATOM.

### Steps to Reproduce

1. I downloaded ATOM
2. I run in Administrator Mode or Normal Mode
3. It starts (the atom rocket is being loaded)
4. It fails after about 5 seconds saying installation has failed and to check the log file.
5. I don't see a problem in the log file but I'm not sure what to look for.

**Expected behavior:** ATOM to be installed correctly

**Actual behavior:** It fails to install

### Versions

WINDOWS 10
[SquirrelSetup.txt](https://github.com/atom/atom/files/402257/SquirrelSetup.txt)

**Comment by davidayers** [comment]
UPDATE: I have now nuked every instance of ATOM, folder or file associated with ATOM from my pc. Same problem as above.

**Comment by mnquintana** [comment]
You need to run the installer as a regular user – it won't work if you try running it in Admin mode. Hope that helps!

**Comment by davidayers** [comment]
That made no difference to the outcome. Same result.

**Comment by davidayers** [comment]
It could be an antivirus issue but for our machines that can not be turned off.

**Comment by 50Wliu** [comment]
`IEnableLogger: Failed to install package to app dir: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.`

But in the end, the issue is that the antivirus is blocking the install (`'resources' is denied`).  As I commented in the other issue, you'll have to use the zipped version if you can't disable it.
