### ISSUE TITLE
[Mac OS X] Native Application Menu Defaults is disabled for native dialogs

### ISSUE THREAD

**Issue by fzzr-** [atom/atom#12338]
### Prerequisites
- The problem is reproducible in all versions in all modes on the any Mac OS X version;
- Are you running the latest version of Atom? **Yes, 1.9.4**;
### Description

Native Application Menu Defaults (`File` & `Edit` menus) is disabled for native dialogs.
### Steps to Reproduce
1. Open any native dialog. For example 'File/Open...' or  'File/Add Project Folder...';
2. Press `⌘+G` (standard Finder's hot-key, "command+shift+G") ;
3. Try to copy or/and paste anything. You can't.

**Expected behaviour:** Native menus should work.

**Actual behaviour:** Native menus not works, ~~stupidly~~ disabled.
### Versions

```
Atom    : 1.9.4
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4
OS X: 10.11.5 (15F34)
```

![atom menu issue mov opt](https://cloud.githubusercontent.com/assets/888526/17439252/4038e580-5b38-11e6-84b4-ddd994468d03.gif)

_Why & for what? It's really terrible!_

**Comment by spalger** [comment]
Could this be why the `⌘+D` shortcut no longer works for selecting "Don't Save" in the save alert?

**Comment by fzzr-** [comment]
@spalger In my case `⌘+D` was work fine in the versions `1.9.0` and older. In the latest versions it disabled too. But why?!

**Comment by houmark** [comment]
@fzzr- Same for me. Prior to 1.9.x `⌘+D` worked like any other app, but not anymore.

Maybe it's related to the changes to the open dialog that now opens the same directory as the current file (which is very nice and something I missed since I started using Atom).

**Comment by 50Wliu** [comment]
This is probably related to the Electron upgrade.  See also #12277.

**Comment by nicolaguidi** [comment]
Not sure if it's the same problem: when there are no active windows open, File > Open... doesn't work; if an untitled Atom windows is open it works. (Version 1.9.9/Mac)

**Comment by Vaguery** [comment]
I suspect this is also the reason 1.15.0 is unable to access the system clipboard in the Save dialog: I cannot paste or cut the filename (even programmatically with Alfred.app).

Is this possibly a reversion bug for #10446 ?

**Comment by zeis** [comment]
I too am unable to use hotkeys such as Cmd-v to paste into the text field in a Save dialog.
