### ISSUE TITLE
Cannot install 1.9.4 on windows 10

### ISSUE THREAD

**Issue by OneNewLife** [atom/atom#12332]
* Version: 1.9.4
* OS: windows 10 10.0.10586

when opening `AtomSetup.exe`, it threw an error:  **this version doesn't match your system**.

![error](https://cloud.githubusercontent.com/assets/10388933/17430810/0be43596-5b29-11e6-8a21-7d72b1d21c6b.png)

please fix this bug, ths :)

**Comment by damieng** [comment]
I just downloaded the latest atomsetup.exe from atom.io (which is now 1.9.5 for other reasons) and it installed on Windows 10 (64-bit English) without an issue.

Can you try with 1.9.5 from atom.io.

**Comment by OneNewLife** [comment]
ths god, 1.9.5 works now. @damieng
