### ISSUE TITLE
Add version numbers to installer files

### ISSUE THREAD

**Issue by airtonix** [atom/atom#12337]
Just a suggestion, becuase when downloading `AtomSetup.exe`, I end up with `AtomSetup.exe(1)` `AtomSetup.exe(2)`... which version is which?

If instead it was `AtomSetup-1.9.3.exe`
- It's now obvious what version this file is, and any links pointing at it.

**Comment by damieng** [comment]
I think the rationale was that it shouldn't matter as it will auto-upgrade to the latest one after the first launch.

Personally I would like to see the version numbers attached but it's probably quite tied up with the various publishing steps which make it non-trivial.

**Comment by pcnate** [comment]
This may cause issues with some users autoupdate scripts. Could potentially affect other packages such as: https://github.com/simonkberg/atom-check-updates

**Comment by damieng** [comment]
Do the autoupdater scripts grab from GH releases or from the web site?

**Comment by johnmuhl** [comment]
I was recently caught by this on Linux where manual install is the only option; #12303. Having the version number as part of the file name would have saved me a couple minutes of confusion.

**Comment by pcnate** [comment]
@damieng looks like in this case it is using the GH releases API so this shoud be fine. If people have custom developed script to do this are probably few or should be using something like this if they don't want to manually download it until the linux packages get some sort of automatic updating mechanism.

https://api.github.com/repos/atom/atom/releases

@johnmuhl I would recommend the atom-check-updates package I mentioned above.

**Comment by ricardograca** [comment]
For the record even on OSX it doesn't auto-update properly: #2860, #5160, so assuming that people only need to install it once is a bit too optimistic.

**Comment by airtonix** [comment]
Meh, using semver people can use more robust strategies to update.

**Comment by ricardograca** [comment]
This is still an issue. The only downloads with a version number on them are the `.nupkg` files.

**Comment by damieng** [comment]
We have no plans to do this - the time to change the distribution process throughout our release system outweighs the small inconveniences given our other workloads and priorities on Atom.
