### ISSUE TITLE
Upgrade electron to fix canvas bug

### ISSUE THREAD

**Issue by unixpickle** [atom/atom#12339]
### Description

When switching spaces on OS X, `<canvas>` elements in the editor view sometimes disappear (i.e. turn completely white). This is most likely related to this Chromium bug: [https://bugs.chromium.org/p/chromium/issues/detail?id=588434](https://bugs.chromium.org/p/chromium/issues/detail?id=588434). This bug is fixed in newer versions of Chromium. This could be fixed by upgrading electron.

### Steps to Reproduce

1. Use a plugin which places a canvas in the editor view.
2. Launch atom, switch spaces on OS X, switch back.
3. Try this a few times if the bug doesn't occur right away.

**Expected behavior:** the canvas should still be there when you switch spaces back.

**Actual behavior:** the canvas is rendered as a white element, no matter what `background-color` it is given, and no matter what CSS transformations are applied to it.

**EDIT:** it was white in my editor because I use a white theme. The canvas appears to become a solid color that matches the editor's background color (probably takes the pixel buffer from the thing behind it). I know it's not just transparent, because I can move the canvas above the text and the text is clearly covered by something of a solid color.

### Versions

```
Atom    : 1.9.4
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

Note how old that version of Chrome and Electron are. The [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=588434) I linked above was present in Chrome 49. Thus, electron should be upgraded.

**Comment by 50Wliu** [comment]
Please see https://github.com/atom/design-decisions/blob/master/electron-update-procedure.md for the Electron update procedure and #12300 for the ongoing PR.
