### ISSUE TITLE
Atom is freezing under windows when editing jade/pug links 

### ISSUE THREAD

**Issue by breytex** [atom/atom#12336]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

When I write link tags for a jade/pug file like this:
`a.hb-yt(href='https://www.youtube.com/', target="_blank",onmouseover="track('"+name+" LP all', 'hover', 'social: yt')", onclick="track('"+name+" LP all', 'click', 'social: yt')")`

The editor sometimes freezes for about 20 seconds and sometimes crashes.
### Steps to Reproduce
1. [First Step]
   create long pug / jade file.
   Use linter and pug / jade highlighting
2. [Second Step]
   create / edit a-href

**Expected behavior:** [What you expected to happen]
no lag

**Actual behavior:** [What actually happened]
lag
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by 50Wliu** [comment]
As per the first prerequisite, can you reproduce this behavior in safe mode (`atom --safe`)?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12133#issuecomment-231953654. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
