### ISSUE TITLE
grammar-used activation hook regression

### ISSUE THREAD

**Issue by nwolverson** [atom/atom#12333]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? **N/A**
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

My package has a `grammar-used` activation hook, as per #8313 it is triggered on opening a new file but not on opening a previous session.

I have observed this working correctly at some point in an earlier version, but can't say how long ago.

### Steps to Reproduce

(as per #8313)

1. Install language-purescript and ide-purescript
2. Open a file with `.purs` extension - observe package starts
3. Close atom
4. Re-open atom (so file is still open)

**Expected behavior:** [What you expected to happen]
*  Package is started

**Actual behavior:** [What actually happened]

*  Package does not start
*  Package can be observed to neither be started nor activated (via console.log on startup)
*  Opening a new file which was not already open will start the package as normal (but not switching to one of the existing files)

### Versions

apm 1.10.0
atom 1.9.4 (also verified on 1.10.0-beta1)

OSX 10.9.4

**Comment by yitzchak** [comment]
I think this is showing up in thomasjo/atom-latex#200

**Comment by mrdawn** [comment]
Same issue in latex, packages not work with remember tabs. I think it's atom error, not package error

**Comment by zertosh** [comment]
We hit this issue in Nuclide too- in a hastily move, I ended up removing all of the `grammar-used` activation hooks (facebook/nuclide@f413cbfc39341f7728767e8611d81fb960c16cd4) for Atom 1.9.0 compat.

I believe that what is going on is that activation hooks are only triggered when `atom.workspace.openTextFile` is [used](https://github.com/atom/atom/blob/v1.9.6/src/workspace.coffee#L554). When TextEditors are deserialized, they get created via a [different](https://github.com/atom/atom/blob/v1.9.6/src/text-editor.coffee#L114) code path that doesn't trigger the activation hooks.

**Comment by maxbrunsfeld** [comment]
I think this was introduced by https://github.com/atom/atom/pull/11603

**Comment by maxbrunsfeld** [comment]
This is fixed on master. The fix will be released in v1.9.8 and v1.10.0-beta5.
