### ISSUE TITLE
toggle-menu-bar modified hotkey not reflected in notification

### ISSUE THREAD

**Issue by pcnate** [atom/atom#12340]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Changing the hotkey for `window:toggle-menu-bar` to something like <kbd>alt</kbd>+<kbd>F1</kbd> is not reflected in notifications.
I cannot determine if this affects more than this notification as I am not yet aware of other similar notifications.

**Modified keybindings through `keymap.cson`:**

```
# disable the alt key
'.platform-win32, .platform-linux':
  'alt': 'abort!'
  'alt-f1': 'window:toggle-menu-bar'
```

**Keybindings are changed in settings:**
![image](https://cloud.githubusercontent.com/assets/621940/17441889/cd0d4ad6-5af8-11e6-8e5b-476df078eb45.png)

**Change is reflected in menus:**
![image](https://cloud.githubusercontent.com/assets/621940/17441972/3cc67514-5af9-11e6-80f0-425b29a954af.png)

**Change is NOT reflected in notification:**
![image](https://cloud.githubusercontent.com/assets/621940/17441853/9a28ec10-5af8-11e6-9be4-80d7310eaba8.png)
### Steps to Reproduce
1. Override the <kbd>alt</kbd> hotkey to show/hide the menu bar as example above shows
2. Use new combination to hide the menu-bar.
3. Observe the displayed notifications reference to using <kbd>alt</kbd>
4. Looking in settings --> keybindings we can see that the key combo has been changed

**Expected behavior:**
Notification should show the correct hotkey to `window:toggle-menu-bar`

**Actual behavior:**
Notification does not show the correct hotkey to `window:toggle-menu-bar`
### Versions

**apm**

```
apm  1.10.0
npm  2.13.3
node 0.10.40
python
git
visual studio 2010
```

**atom**

```
Atom    : 1.9.4
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**OS**

```
Microsoft Windows 7 [Version 6.1.7601]


Debian GNU/Linux 8.5 (jessie) ( fully patched ) ( gnome 3 )
```

**Comment by 50Wliu** [comment]
The `alt` key by itself isn't bound to any command - I think there's some Electron/OS-level behavior going on that allows Alt to toggle the menu bar.  After the menu bar is hidden, does pressing Alt just by itself toggle the menu bar?

**Comment by pcnate** [comment]
Once the alternative combination is added, <kbd>alt</kbd> no longer has any effect. This is of course the point.

The issue at hand here is the key combo that is displayed on the notification that appears.
