### ISSUE TITLE
Unobtrusive uncaught exceptions

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#12343]
Related https://github.com/atom/atom/issues/6945

Although it was incredibly helpful while Atom was still in beta, I think we should reconsider popping up big red notifications for every uncaught exception. 

Admittedly, doing this provides us with a vast pool of users catching our bugs, allowing us to hone in on code paths that might not be working the way we expect. However, I strongly suspect (from almost 2 years of issue triage experience) that it gives users the sense that Atom is wildly unstable.

This can be exacerbated by Atom's hackability – since a package can literally do anything, there is nothing preventing a community package from completely disrupting a user's workflow by throwing exceptions left and right (and this isn't hypothetical, either – there are definitely some packages well known for making Atom "feel" unstable). This also increases our issue triage burden, because we often get reports of issues that are ultimately caused by community packages.

Compare this with any other production desktop app – how many of them burden their users with taking action on mere uncaught exceptions? With the exception of hard crashes, there's no reason why any of these necessarily should require manual user action.

I think users on Atom's stable channel reasonably expect Atom to feel, err, stable 😆 , and we should do all that we can to make their lives simpler, more pleasant, and more productive. Beta users, on the other hand, have explicitly opted-in to testing a more experimental, potentially unstable Atom.
## Proposal 🎉

On the `stable` channel, just log uncaught exceptions silently instead of popping up a notification (and send to Bugsnag, if they've opted-in to telemetry). On `beta`, keep the current behavior, but in addition to this revamped logging.

Persist these logs to disk and provide a command to open issues with those logs attached.
## Considerations 💭
1. We would lose a large sample set for discovering uncaught exceptions – what if we miss some?
2. Uncaught exceptions and stack traces in themselves are rarely, if ever, enough information to properly diagnose a bug. This is why the notifications package currently attaches the most recent commands entered, the user's config, and their installed packages, and encourages users to describe reproduction steps. How would we get the information we need to debug uncaught exceptions without making users open issues on GitHub for them?
3. Packages might be explicitly using the `atom.notifications` API to pop open errors, even though it's still private. Should we prevent this in the stable channel (but only for error-type notifications)?
### Potential Solutions 🚀
1. This shouldn't matter – our beta channel exists for this exact purpose. We shouldn't treat users on stable like beta users.
2. We should set up robust logs for all registered Atom commands, and persist these logs to disk. (cf. https://github.com/winstonjs/winston).

What do you think? :eyes: @iolsen @lee-dohm @atom/feedback

**Comment by nathansobo** [comment]
My concern is that once an exception occurs, behavior can be unpredictable. This may lead to people reporting bugs caused by these secondary effects rather than the exception itself.

**Comment by alexrussell** [comment]
Just to add my preferences to this. First off I fully understand why having these exceptions display is a good idea. And Atom is hackable and made, in general, for devs, so it's not like they'd be overly confusing to see.

That said, they can pop up quite often if a given package is misbehaving. A recent example for my use-case are that the eslint linter had some issues sometimes when a given rule was hit (in my case, the rule was "too many blank lines" - there was some exception thrown for something like `editor.getScreenPositionForCursor()` or something), and another is the find-and-replace one where most times I did a find in project and then clicked on a result, thus switching the tab, there would be an exception thrown for the find-and-replace package. These were both reported in Github on the respective packages and were being looked at or worked on. There was nothing I could really do, but I was still constantly told about the issues.

My proposal for both stable and beta (or behind a configuration option ideally) is that the first time a given exception happens per editor/session it should be shown. And then if it happens again, there can be a checkbox or button to silence that exception for the rest of the session. Somewhat like the `alert`/`confirm` thing in Chrome (and probably other browsers): "Prevent page from creating additional dialogs".

This way, users are told about all exceptions and shouldn't (_shouldn't!_) be creating bug reports based on instabilities once they have accepted that a given exception is occurring but being silenced. Additionally, they are being reminded that the error still exists when they have a new session, but once or so a day is far more preferable to whenever the plugin happens to throw.

**Comment by nathansobo** [comment]
cc @iolsen for reactive prioritization.
