### ISSUE TITLE
Package request: Alpine Linux

### ISSUE THREAD

**Issue by greencopper** [atom/atom#12347]
I would be really nice if we could get a package for Alpine Linux too! :+1: 

http://alpinelinux.org/

**Comment by 50Wliu** [comment]
What file format does Alpine Linux support (eg `.deb`, `.rpm`)?

**Comment by mladengit** [comment]
[Alpine Package Format](https://wiki.alpinelinux.org/wiki/Alpine_package_format)

**Comment by greencopper** [comment]
Alpine Linux is an independent security oriented distribution with their own great package format.

I really miss Atom on Alpine Linux.

I would very much like to compile my own, but I do not know what packages to install that correspond to the build-essential from Debian.

**Comment by pwFoo** [comment]
[Alpine Linux is a security-oriented, lightweight Linux distribution based on musl libc and busybox](https://www.alpinelinux.org/about/).

If glibc is needed there is a [glibc compat package](https://github.com/sgerrand/alpine-pkg-glibc) which works fine to run docker-compose (needs glibc) and a wiki article about [Running glibc programs](https://wiki.alpinelinux.org/wiki/Running_glibc_programs).
