### ISSUE TITLE
Atom + git + macOS Sierra

### ISSUE THREAD

**Issue by thinklinux** [atom/atom#12344]
### Description

When I modify I file it doesn't always show it as modified on the file tree.

### Steps to Reproduce

1. Modify a file
2. Switch to another application
3. Go back to Atom

**Expected behavior:**

All the files that have been modified should be highlight on the file tree

**Actual behavior:**

There are no files that are highlighted as modified.

### Versions
macOS Sierra 10.12 Beta (16A270f)

`atom --version`
Atom    : 1.9.5
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

`apm --version`
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.7.1

**Comment by arcticicestudio** [comment]
Already reported here: [atom/tree-view #906](https://github.com/atom/tree-view/issues/906)
