### ISSUE TITLE
Terminate Atom from CLI

### ISSUE THREAD

**Issue by dominhhai** [atom/atom#12352]
How to close Atom App from CLI?

**Comment by pcnate** [comment]
Most applications don't support such a thing. Services tend to, but services and applications are two different things. If you are on Linux then use something like what [this from digital ocean](https://www.digitalocean.com/community/tutorials/how-to-use-ps-kill-and-nice-to-manage-processes-in-linux)

For windows see [this stackoverflow question](http://superuser.com/questions/727724/close-programs-from-the-command-line-windows)

**Comment by dominhhai** [comment]
Using `kill` command to kill Atom process, have to use `ps` to check the id of process, however. 
So, I want a Atom's command to do that.

**Comment by damieng** [comment]
We wouldn't add such a command - it is highly unusual and there are already tools to do it if you need to terminate it as described by pcnate above.

**Comment by pcnate** [comment]
@dominhhai just create a bash script to do this and drop it in your ```/usr/local/bin```
