### ISSUE TITLE
Command line 'atom' script does not work in new Ubuntu subsystem on Windows 10

### ISSUE THREAD

**Issue by jrajav** [atom/atom#12358]
### Description

Command line 'atom' script does not work in new Ubuntu subsystem on Windows 10

### Steps to Reproduce

1. Open the Ubuntu subsystem shell (bash.exe).
2. Add the `atom/bin` directory to your path (`export PATH=/mnt/c/Users/<MyUsername>/AppData/Local/atom/bin:$PATH`).
3. Try to use the 'atom' script on a file.

**Expected behavior:** The script to work correctly and the file to open in Atom

**Actual behavior:** The script fails with the error:

```
% atom file.txt
/mnt/c/Users/<MyUsername>/AppData/Local/atom/bin/../app-1.9.6/resources/cli/atom.sh: line 9: pwd: -W: invalid option
pwd: usage: pwd [-LP]
/mnt/c/Users/<MyUsername>/AppData/Local/atom/bin/../app-1.9.6/resources/cli/atom.sh: line 15: cmd.exe: command not found
```

### Versions

Atom 1.9.6
Windows 10 version 1607 build 14393.10 (Anniversary update), inside Ubuntu subsystem

**Comment by 50Wliu** [comment]
I'm _pretty_ sure the Windows version of `atom.sh` is meant to transfer control to `atom.cmd`, which is not possible within the Ubuntu subsystem.

/cc @damieng?

**Comment by damieng** [comment]
The Ubuntu/Linux Subsystem for Windows 10 does not allow calling back to any kind of Windows process.  It's a one-way street.

If you need interop you'd be better off using Cygwin or MSYS2.
