### ISSUE TITLE
README for the v1.12.3 tagged release appears incorrect

### ISSUE THREAD

**Issue by anomaly256** [atom/atom#12359]
These are the instructions for getting/using apm but not for building atom itself.  Also the build scripts appear to be missing from this tagged version.  ?

**Comment by anomaly256** [comment]
Ditto with the v1.11.0 tag

**Comment by mnquintana** [comment]
I think you may be looking at the [apm repo](https://github.com/atom/apm) – there is no v1.11.0 tag or v1.12.3 tag on this repo.

**Comment by anomaly256** [comment]
Then what is this:

https://github.com/atom/atom/tree/v1.12.3

I think someone pushed to the wrong place perhaps?

**Comment by 50Wliu** [comment]
@anomaly256 There was, I believe, an experiment to try to get all of apm's history included within the atom/atom repo and to merge the two together.  That didn't end up going through and that branch you're referencing is probably a side-effect of that effort.  If you notice, that branch isn't tagged.

/cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
😬  I knew that would have some unintended consequences. I had tried to delete the apm tags, but I missed two. They are now gone. Thanks so much for catching and diagnosing that @50Wliu 🙏 .

**Comment by anomaly256** [comment]
Ah right, thanks for the explanation.
