### ISSUE TITLE
install packages in window system，not work

### ISSUE THREAD

**Issue by dukegod** [atom/atom#12369]
in my window notebook。Everytime install package ，i must manually install，like ：

installed atom-jade for instance.

```
cd ~

cd .atom/packages

git clone https://github.com/merrihew/atom-jade.git

cd atom-jade

npm install

```

how to work it automatically ？

**Comment by 50Wliu** [comment]
`apm install`, not `npm install`.

Automatically: `apm install atom-jade`.  You can also install through Atom's Settings View.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
