### ISSUE TITLE
Someone pushed the apm repo to the atom repo - or maybe github is broke

### ISSUE THREAD

**Issue by anomaly256** [atom/atom#12362]
https://github.com/atom/atom/tree/v1.12.3

??

**Comment by anomaly256** [comment]
Or maybe Github broke

**Comment by anomaly256** [comment]
@mnquintana

**Comment by anomaly256** [comment]
![screen1](https://cloud.githubusercontent.com/assets/421854/17470148/5614ab40-5d7d-11e6-905e-3d3fee57a5f8.png)
![screen2](https://cloud.githubusercontent.com/assets/421854/17470159/6aa46c6c-5d7d-11e6-8164-e2ed32be3e35.png)

**Comment by 50Wliu** [comment]
See my comment in your other thread.
