### ISSUE TITLE
I hope 'ctrl-tab' is show-next-item

### ISSUE THREAD

**Issue by ykqmain** [atom/atom#12361]
**I changed my settings, but it is unavailable.**

![](http://ww4.sinaimg.cn/large/006tNc79gw1f6m8d9uzc5j312u0kyn18.jpg)

**Comment by 50Wliu** [comment]
@ykqmain Here's the keymaps you'll need:
```cson
'body':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-tab ^ctrl': 'unset!'
  'ctrl-shift-tab': 'pane:show-previous-item'
  'ctrl-shift-tab ^ctrl': 'unset!'
```

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
