### ISSUE TITLE
Maximizing window requires several attempts

### ISSUE THREAD

**Issue by MKindy** [atom/atom#12365]
Has anyone else encountered this situation?  I can't find any information about it.  Problem occurs on a fresh install or in safe mode.

### Description

Maximizing window requires several attempts.

### Steps to Reproduce

1) Open program, or switch to actively-running program.
1b) If program window is already maximized, reduce the window size below maximum.
2) Attempt to maximize window.
3) Attempt to maximize window.
4) Attempt to etc.

**Expected behavior:** Window is maximized after clicking "maximize window" button (or keyboard shortcut) once.

**Actual behavior:** Window requires multiple attempts at maximizing.  See gif of attempt(s) at [http://imgur.com/a/Ymzjo](http://imgur.com/a/Ymzjo)

### Versions
```C:\WINDOWS\system32>atom --version

Atom    : 1.9.6
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

C:\WINDOWS\system32>ver

Microsoft Windows [Version 10.0.14393]
```

**Comment by 50Wliu** [comment]
Hasn't ever happened to me before.

**Comment by MKindy** [comment]
After further testing, it appears to be in conflict with my window management software, Actual Window Manager.  This calls for more troubleshooting.  Anyone else running AWM?

**Comment by lee-dohm** [comment]
Since this appears to be a bug in the window manager as opposed to Atom, I'm going to close this. You may also want to leave a message on [Discuss, the official Atom and Electron message board,](https://discuss.atom.io) to see if anyone there can help replicate the issue.
