### ISSUE TITLE
Add shell commands to Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by irowebbn** [atom/atom#12379]
### Description

The Atom Shell commands are not available on Bash on Ubuntu on Windows 10

### Steps to Reproduce

1. Open [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) in Windows 10
2. Try the `atom` and `apm` commands and note the "command not found" message
3. Try these same commands in Command Prompt (cmd.exe) and observe intended result

**Expected behavior:** Expected `atom` command to launch editor GUI and `apm` command to return `apm - Atom Package Manager powered by https://atom.io...` or install package named in command.

**Actual behavior:** Bash gives: `atom: command not found` and `apm: command not found`

### Versions

Atom    : 1.9.7
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
Windows 10 Home, Version 1607, OS Build 14393.10

**Comment by 50Wliu** [comment]
This is not possible as Bash on Ubuntu is completely (well, almost completely) isolated from Windows.  Items in Windows' PATH are not added to Bash's path.  In addition, the bash files that Atom for Windows ships with are designed to call their respective `.cmd` versions, which also isn't possible in the Linux subsystem.

You would have better luck attempting to build Atom from source and then adding the resulting `apm.sh` to Bash's path.  Much more work would be involved in getting Atom to show up.
