### ISSUE TITLE
Cannot open Atom from Applications dir on OS X El Capitan

### ISSUE THREAD

**Issue by kalmecak** [atom/atom#12387]
### Description

I'm using a MAC with **El Capitan**

I can not open Atom if I move it to **Applications** directory but it perfectly works if I open atom in other directory, Downloads for example.

For now I'm launching Atom from downloads Dir.
### Steps to Reproduce
1. Go to [https://atom.io](https://atom.io) and download the latest version
2. Once downloaded, move Atom to Applications directory
3. Try to open it from Application directory
4. Enjoy the **“Atom” is broken and cannot be opened** message

**Expected behavior:**  Get Atom works from Applications directory

**Actual behavior:** Sends "Cannot open Atom" message 
### Versions

Atom version: **1,9,7**

**Comment by lee-dohm** [comment]
Is your user account an Administrator?

**Comment by kalmecak** [comment]
Yes, it is

**Comment by kalmecak** [comment]
Mi account is admin account, I've took some screen shots to illustrate te issue

1. [Download](https://drive.google.com/file/d/0B7xWu7Zc6ZZkbWp3c3psSEowNjQ/view?usp=sharing)
2. [Move to Applications directory](https://drive.google.com/file/d/0B7xWu7Zc6ZZkeTRTbEFSdGJHa3c/view?usp=sharing)
3. [I get broken alert when I try to open it](https://drive.google.com/file/d/0B7xWu7Zc6ZZkWnVjcl9DNjlfalE/view?usp=sharing)
4. [But Atom work's fine from downloads dir](https://drive.google.com/file/d/0B7xWu7Zc6ZZkU3RwNkdZVS1WSUk/view?usp=sharing)

**Comment by caseybaggz** [comment]
@kalmecak when Atom is in your Applications dir can you open it from the terminal with this:
`open /Applications/Atom.app` ?

**Comment by kalmecak** [comment]
Yep, from terminal it works

**Comment by stereobooster** [comment]
Try left button click -> Open -> Open anyway. This will make MacOs trust this. But strange why this  happens in first place. MacOS complains about safety. Are you sure it is not tempered file?
