### ISSUE TITLE
1.9.0: M+ font rendering

### ISSUE THREAD

**Issue by solbjorn** [atom/atom#12381]
Version 1.9.0 of Atom has introduced some nasty regression with font rendering:
![screenshot - 10 08 2016 - 12 10 21](https://cloud.githubusercontent.com/assets/12006295/17548522/f21a657a-5ef4-11e6-88d6-f46ea1814b4a.png)
![screenshot - 10 08 2016 - 12 06 36](https://cloud.githubusercontent.com/assets/12006295/17548527/f4ebe422-5ef4-11e6-9426-bca2a8f79d63.png)
Take a look at "offset": despite using monospace font (it's M+ 1mn, size 17), letters 'f' are sticked to each other and occupy 1 space instead of two.
I cannot reproduce it on Liberation Sans Mono or DejaVu Sans Mono, only M+ (https://mplus-fonts.osdn.jp). Downgrading to 1.8.0 solves this, thus running in Safe mode (or with erased configs) makes no sense. Atom 1.9.7 also contains this bug.

Xubuntu 14.04.5 64-bit.

**Comment by bernharduw** [comment]
I suspect this is a "problem" with the font you use. So-called ligatures can provide additional value even with monospaced fonts, and they are enabled by default in Atom 1.9+. If you use the free font [Fira Code](https://github.com/tonsky/FiraCode), for example, it uses ligatures a lot to improve legibility. You font seems to have ligatures enabled, but uses them incorrectly - ff is a common "traditional" ligature, such as ft and st, for example.

You can try to disabled ligatures in Atom (maybe [these instructions for enabling ligatures](https://github.com/tonsky/FiraCode/wiki/Atom-instructions) will help), or you use an updated version of the font, where this ligature has been disabled.

I hope this helps a bit.

**Comment by solbjorn** [comment]
@bernharduw, disabling ligatures solves this. So you're right, it's not Atom problem but M+ font feature. Thanks!

Issue is incorrect itself, closing.
