### ISSUE TITLE
jump with a comment

### ISSUE THREAD

**Issue by jumbycc** [atom/atom#12383]
### Steps to Reproduce
 [First Step]

open a php file

```php
<?php

namespace App\Jobs;

use Illuminate\Bus\Queueable;

abstract class Job
{
    /*
    |--------------------------------------------------------------------------
    | Queueable Jobs
    |--------------------------------------------------------------------------
    |
    | This job base class provides a central location to place any logic that
    | is shared across all of your jobs. The trait included with the class
    | provides access to the "onQueue" and "delay" queue helper methods.
    |
    */

    use Queueable;
}
```

[Second Step]
press Ctrl+R want  jump into a function
 [and so on...]
displayed content　is:
```php
/*-----------
/ Job
/ Line:7
/-----------
/ providers
/ Line:14
/-----------*/
```

**Expected behavior:** [What you expected to happen]
no data displayed or only class name displayed

**Actual behavior:** [What actually happened]
a comment displayed
```php
/*-----------
/  providers
/  Line:14
/-----------*/
```
### Versions
atom 1.9.7

**Comment by 50Wliu** [comment]
Are you using a non-US keyboard layout?  If not, please reopen this on the [atom/symbols-view](https://github.com/atom/symbols-view) repository.
