### ISSUE TITLE
Splitting panes using the menu gives me an empty panel

### ISSUE THREAD

**Issue by ricardograca** [atom/atom#12386]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When attempting to split panes by using the application's menu I end up with empty panes.

### Steps to Reproduce

1. Open a file 
2. Open the View > Panes menu and select one of the Split Left/Right/Up/Down options

**Expected behavior:**

A new pane is created containing a new view of the currently open file.

**Actual behavior:**

A new pane is created but it is empty.

### Versions

Atom 1.9.7, OSX 10.9.5 and Ubuntu 15.04.

**Comment by nirajk42** [comment]
Can I work on it?

**Comment by 50Wliu** [comment]
@nirajk42 Of course! :smile:  Just change the commands in [these three files](https://github.com/atom/atom/tree/master/menus) to use the correct pane-split command (`pane:split-up-and-copy-active-item` et. al).

**Comment by nirajk42** [comment]
Thanks @50Wliu. Can you assign this issue to me. 
I have gone through the https://github.com/atom/atom/blob/master/CONTRIBUTING.md. I will submit the pull request by tomorrow. Please let me know If anything else I need to know?

**Comment by 50Wliu** [comment]
I can't assign this issue to you, sorry.

**Comment by nirajk42** [comment]
No problem. I have done the changes. What should I do next?

**Comment by Ben3eeE** [comment]
If everything is working then you can probably submit a pull request to this repository for review and merge. Include a brief explanation and a reference back to this issue so the maintainers that review the PR know what you are trying to achieve.

For reference this issue was introduced by https://github.com/atom/atom/pull/7953.

**Comment by nirajk42** [comment]
I built the package on Ubuntu 14.04 and It is working properly.
I do not have permission to push.
So getting an error: 
```
remote: Permission to atom/atom.git denied to nirajk42.
fatal: unable to access 'https://github.com/atom/atom.git/': The requested URL returned error: 403
```

**Comment by Ben3eeE** [comment]
I have personally not submitted a PR but reading [this help article](https://help.github.com/articles/using-pull-requests/) it looks like you need to push the changes to your own fork and open a PR from there and you are trying to push it to atom/atom directly without using a PR.

**Comment by nirajk42** [comment]
Yeah right!
I missed this point. 
Thanks

**Comment by nirajk42** [comment]
Please review the pull request https://github.com/atom/atom/pull/12404.

**Comment by nirajk42** [comment]
The Mac OS build using circleci has failed due to timeout.
How can I restart it?

**Comment by 50Wliu** [comment]
Fixed by #12404.

**Comment by nirajk42** [comment]
Thanks @50Wliu and @Ben3eeE!
For helping me in my first open source contribution.
Looking forward to have more fun with atom. 
What should I do next? 😊

**Comment by 50Wliu** [comment]
@nirajk42 Take a look at some of the other beginner issues across the Atom org and see if any tickle your fancy :).  https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aatom+label%3Abeginner

If you need help I'm available on [Slack](https://discuss.atom.io/t/join-us-on-slack/16638?u=wliu) as `@wliu`.

**Comment by Ben3eeE** [comment]
I am also available in the slack channel if you need help with other PRs!
