### ISSUE TITLE
Typing 'e' creates euro symbol '€' on QWERTZ keyboard

### ISSUE THREAD

**Issue by KonradHoeffner** [atom/atom#12385]
### Description

The German QWERTZ keyboard creates the euro symbol '€' when pressing Alt Gr + e. In Atom, after 30-60 minutes, euro symbols are created when pressing the e key without holding down Alt Gr.

### Steps to Reproduce

The problem occurs sporadically without a known cause but once it starts it persists until restart. 

### Versions

Atom    : 1.9.6
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.9.2

**Comment by 50Wliu** [comment]
Assuming you have the keyboard-localization package installed, there seems to be a bug in that package where the AltGr key gets 'stuck' after a while.  If you're not, I would still suggest installing it to see if that helps what you're experiencing, and also to subscribe to atom/atom-keymap#35 if you haven't already.

**Comment by KonradHoeffner** [comment]
I indeed have the keyboard-localization package installed. I updated the package and hope that will fix the issue.
