### ISSUE TITLE
Takes very long when multiple atom windows are quitted and re-opened

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#12399]
When atom is restoring last session , it hits IO 99% about same amount of windows opned , very very slow to start (takes 10 mins) since every atom processes are trying to steal each other IO resources.

**Comment by 50Wliu** [comment]
Closing until the requested information is provided. Thanks @hultberg.

**Comment by v3ss0n** [comment]
- How would it possible to restore last session in --safe?
- Tested on atom 1.9.8
- Yes 
- Yes i am an old atom user and part of community since day one.
- Yes

- When atom is restoring last session ,. that is quitted with multiple windows open and many tabs on each windows , it hits IO 99% about same amount of windows , very very slow to start (takes 10 mins) since every atom processes are trying to steal each other IO resources.
