### ISSUE TITLE
Complete Uninstall/Reinstall/Portable Disaster

### ISSUE THREAD

**Issue by Crayder** [atom/atom#12392]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? (Why is that even relevant to most of the issues here?)
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported? (Well one of the red boxes mentioned below say that there is an issue reported already.)

### Description

Well, I ran AtomSetup.exe expecting to select how I wanted it installed and stuff, but no, everything was automatic. What I wanted was a portable install for my flashdrive to take to school. Instead I got a local install in AppData or whatever.

I decided to just play with it anyways and I started to install some JavaScript add-ons. While they were installing a breaker blew in my house (this may or may not be relevant). I started my computer back up and went to run Atom again with the icon (that happened to just be a plain icon, not the Atom logo, with the Atom label). Nothing happened, not even a process. So I went to start it manually and it worked, except there were some red boxes with errors saying it couldn't do stuff with the files in the ".atom" data folder.

I uninstalled, deleted the data folders (manually... -.-), and reinstalled. The red boxes were still there. Uninstalled again.

Then I Googled to see if there was even a portable version of Atom available. Apparently there is according to an issue and a PR here. I downloaded `atom-windows.zip` and extracted. When I ran the `atom.exe`, there the red boxes were once again. Everything also seemed to be in the same state as it was when I closed the last installation.

### Steps to Reproduce

(explained in description)

**Expected behavior:** I want a portable version of Atom on my flashdrive that doesn't have any connections to Windows (besides the usual requirements) and runs fine.

**Actual behavior:** Explained above.

### Versions

Latest stable, 1.9.8.
Windows 10 Pro 64 bit.

![image](https://cloud.githubusercontent.com/assets/9919010/17577791/dbc8e304-5f4f-11e6-95f6-1eb7a0c4d05f.png)

**Comment by 50Wliu** [comment]
Remove `%USERPROFILE%\.atom` and try again.  I'm not sure if that's what you meant by the "data" folder, but it seems to have gotten corrupted somehow.
