### ISSUE TITLE
Atom 1.9.8 crashes when trying to open 9.2MB XML file on OS X 10.11.6

### ISSUE THREAD

**Issue by baz8080** [atom/atom#12391]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

I am going to develop an English / Swedish diction for Android, so I downloaded 4 data files into a directory:
- http://folkets-lexikon.csc.kth.se/folkets/folkets_en_sv_public.xml
- http://folkets-lexikon.csc.kth.se/folkets/folkets_sv_en_public.xml
- http://folkets-lexikon.csc.kth.se/folkets/folkets_en_sv_public.xdxf
- http://folkets-lexikon.csc.kth.se/folkets/folkets_sv_en_public.xdxf

If I attempt to open `folkets_en_sv_public.xdxf`, atom will hang and crash.
### Steps to Reproduce
1. Download all of the files above
2. Start atom in safe mode
3. Open `folkets_en_sv_public.xdxf`

**Expected behavior:** 

Editor renders XML

**Actual behavior:** 

atom hangs, and then crashes
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

_atom versions_

```
Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**apm versions**

```
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.4
```

**os versions**

```
Darwin Barrys-MBP 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

**Comment by maxbrunsfeld** [comment]
Atom v1.8.0 seems to crash on this file too. Investigating...

**Comment by maxbrunsfeld** [comment]
I'm really sorry for this. Can you disable the `autocomplete-plus` package and try again? I believe that there is some code in that package that is particularly memory-intensive, and is causing Atom to run out of memory.

**Comment by baz8080** [comment]
@maxbrunsfeld thanks for the reply! I disabled `autocomplete-plus` and the first `xdxf` file opened without a crash. It did crash again when I tried to switch from that file to the other `xdxf` one.

I followed your lead and disabled more packages, however the crash still occurred. The packages I have enabled now are:

* about
* dev-live-reload
* exception-reporting
* settings-view
* tabs
* tree-view

**Comment by Zireael07** [comment]
9.2 MB sounds like you're running into one of the issues with large files.
