### ISSUE TITLE
Settings got resetted when opening multiple windows at once.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#12398]
When atom is quitted using Ctrl + Q and when new windows are opened all settings are resetting.
Including disabled plugins.

**Comment by hultberg** [comment]
Hello, and welcome to the atom core issues. Please fill out the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) that was provided in the content when you created the issue, as it gives us much more information to go on.

**Comment by 50Wliu** [comment]
Closing until the requested information is provided. Thanks @hultberg.
