### ISSUE TITLE
Use generic icon in linux .desktop file instead of hard coded path

### ISSUE THREAD

**Issue by Edenhofer** [atom/atom#12407]
Instead of hard coding the icon path in the `.desktop` file it is much more common to just state the appname and place the default logo at `/usr/share/icons/hicolor/`_`resolution`_`/apps/atom.png`. Chrome for example does so. However this is not simply a cosmetic change! It also allows for themes to replace certain icons while preserving the icons of apps with no altered icon.

The bug is still present in the master branch as of now.

**Comment by wassname** [comment]
It's no longer hard coded and it's put in `/usr/share/pixmaps` (at least for debian). So this issue can be closed

**Comment by 50Wliu** [comment]
@Edenhofer can you please confirm?

**Comment by Edenhofer** [comment]
I can confirm that the icon in the `.desktop` file is now properly configured. However the name of the variable `iconPath` is a bit misleading since it no longer contains a path but merely a name. Either way the bug is resolved.
Thanks for working on this!
