### ISSUE TITLE
Atom crashed when open a folder

### ISSUE THREAD

**Issue by nguyenbathanh** [atom/atom#12402]
### Description

Atom crashed when open a folder. Please see screenshot of all files in my "bug" folder.

http://image.prntscr.com/image/90c1244fca1e41b88cdc50cd3339ea5a.png

I don't know why but it's working with other folders.
### Steps to Reproduce
- Open folder in Atom with folder context menu
- Open folder in Atom from File -> Open Folder...

**Expected behavior:** Folder opened with Atom

**Actual behavior:** Please see this screenshot: http://image.prntscr.com/image/192d9121e71b4725a854ce07d138402c.png
### Versions

I'm using Atom 1.9.8 on Windows 7 64 bit.

**Comment by bgdxv** [comment]
Getting the same error on a PHP project folder. Can't even open some files from withing the folder, but others work fine. Tried safe-mode with the same result.

**Comment by 50Wliu** [comment]
Please upload the dump files from  `%TEMP%\Atom Crashes` here.

**Comment by nguyenbathanh** [comment]
@50Wliu 
I uploaded it in the link below:
https://drive.google.com/file/d/0B9lPIy1ftUvwT0FlbGdtdlA4RFE/view?usp=sharing
