### ISSUE TITLE
PATH env being changed randomly

### ISSUE THREAD

**Issue by pangqingyuan1991** [atom/atom#12401]
Gentoo Linux KDE5 desktop, atom v1.9.7.
I met a strange issue. atom sometimes reports that it cannot find some base comands.
for example,
Uncaught BufferedProcessError: Failed to spawn command `find`. Make sure `find` is installed and on your PATH
and basename,dirname,etc.
When restart atom,  the problem is gone. 
Is it the PATH env problem?

**Comment by hultberg** [comment]
Hello, and welcome to the atom core issues. Please fill out the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) that was provided in the content when you created the issue, as it gives us much more information to go on.

**Comment by 50Wliu** [comment]
Closing until the requested information is provided.  Thanks @hultberg.

**Comment by pangqingyuan1991** [comment]
Oh, sorry. This bug belongs to the package atom-gtags.
This package will change PATH env.
