### ISSUE TITLE
Atom reverted to base install, deleted all themes/packages 

### ISSUE THREAD

**Issue by yingw787** [atom/atom#12414]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

Not entirely sure about this.
- [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?

Yes. I have "install new updates on restart" enabled.
- [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?

I asked on Slack (atomio.slack.com) and one user mentioned how I should definitely file an issue for this. I've never seen or heard any application delete all packages and user settings based on application close. 
- [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?

Just performed cursory search, no issues like this open. 
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?

This happened to the Atom editor. 
- [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

Just did, this was not a crash (closed properly), but when it restarted all the packages were missing.

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Atom deleted all of my packages and themes upon application restart. Not really sure how else to elaborate on this, but pretty much reverted to base install (maybe more basic as file explorer is not present on left-hand-side as well).  
### Steps to Reproduce
1. Have a lot of tabs open (I had my React project open at the time and had my README.md, and many Javascript files)
2. Notable installed packages include those needed to run .eslintrc file (eslint-plugin-{react, lodash, etc.}, eslint)
3. Delete tabs by using shortcut Cmd + W really fast
4. Reopen Atom by typing in Terminal atom . in targeted directory
5. cry

**Expected behavior:** [What you expected to happen]

Atom closes and starts up again with all packages and themes present. File explorer present on left hand side. 

**Actual behavior:** [What actually happened]

Atom deleted all themes and packages. ~/.atom directory still exists, ~/.atom/packages does not. No green square on bottom-left-hand-side (not sure if I should be looking for this.)
Still present: all directory files (Atom did not touch any of my files, and since I had just pushed to devel branch there weren't any unsaved changes to any files so I don't know if those would have been lost or not).
### Versions

Atom 1.9.8 
apm 1.10.0
OS: OS X 10.11.5

**Comment by lee-dohm** [comment]
In Slack you said you used <kbd>Cmd+W</kbd>, but in these repro steps you say <kbd>Cmd+P</kbd>. Is that a typo?

**Comment by yingw787** [comment]
Yes, that is a type. It is Cmd+W, not Cmd+P. Corrected in the issue.
