### ISSUE TITLE
Crash on start with fresh install Arch Linux

### ISSUE THREAD

**Issue by remexre** [atom/atom#12413]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
 * And when I ran with `--clear-window-state`, I got another crash dialog...
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
 * Didn't know you could do a search query like that, cool.

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Starting Atom from its icon or the CLI (with or without `--safe`, with or without `-f`, before and after deleting `~/.atom` and `~/.config/Atom`), I'm getting a "The editor has crashed" box immediately on start, before any other window appears. This is accompanied by a core dump which includes

```
Core was generated by `/usr/lib/electron/electron --type=renderer --js-flags='.
Program terminated with signal SIGILL, Illegal instruction.
```

(I can paste the whole core dump if wanted)

This is a fresh install of Arch Linux, I've installed the `base` and `gnome` groups, plus `grub`, `vivaldi`, `vlc`, `atom`, `go`, and `git`.

### Steps to Reproduce

1. Install Arch Linux
2. `sudo pacman -S atom` (Install atom from the repos)
3. Run atom in any way.

**Expected behavior:** [What you expected to happen]

Atom to open successfully.

**Actual behavior:** [What actually happened]

"The editor has crashed" plus a core dump.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
$ atom --version
Atom    : 1.9.8
Electron: 1.3.3
Chrome  : 52.0.2743.82
Node    : 6.3.0

$ apm --version
apm  1.12.6
npm  3.10.6
node 6.3.1
python 3.5.2
git 2.9.2
```

Arch Linux is rolling release, so version doesn't really count... Fully updated as of `Sat Aug 13 10:30:47 CDT 2016`.

**Comment by 50Wliu** [comment]
> Electron: 1.3.3

Please see https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md.  We are unable to support unofficial distributions of Atom that modify core components.  Please install Atom directly from https://atom.io.
