### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by creativefull** [atom/atom#12416]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
i successfull install atom, after i open atom i get this notification

### Steps to Reproduce

![screenshot_21](https://cloud.githubusercontent.com/assets/13174684/17649654/98848158-6264-11e6-9935-9c5e71748c43.png)

![screenshot_1](https://cloud.githubusercontent.com/assets/13174684/17649661/affd9db0-6264-11e6-9413-5c9353bbe313.png)

### Versions
![screenshot_2](https://cloud.githubusercontent.com/assets/13174684/17649677/f6120408-6264-11e6-8921-0061fc60d27f.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/13174684/17649741/4bebfb80-6266-11e6-8b49-1a3044310109.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/13174684/17649689/0fd10f74-6265-11e6-99b8-e251a66120f9.png)

**Comment by 50Wliu** [comment]
Please update Atom to the latest version, currently 1.9.8.

And please don't blindly check off everything in the prerequisites if you haven't actually fulfilled them.
