### ISSUE TITLE
Have metrics disabled by default! Please!

### ISSUE THREAD

**Issue by greencopper** [atom/atom#12432]
Why is this still opt-out rather than opt-in?! It's very annoying and just plain wrong!

So the user can disable the metrics package, but this is AFTER he has already run Atom the first time having metrics send information the first time it is run.

Even if all the data is out in the open, this seriously needs to be opt-in, not opt-out!

Would you please take this issue serious and look at all the complaints about the issue.

We have discussed this issue again and again in https://github.com/atom/atom/issues/4966 and in https://github.com/atom/metrics/issues/16

It's spyware no matter what you call it as long as it is opt-out!

**Comment by mnquintana** [comment]
This is already happening – see https://github.com/atom/atom/pull/12281.

Please don't open new issues for duplicates of existing ones.

**Comment by greencopper** [comment]
Super! Because I tested a fresh install of Atom beta. Before the user can disable the metrics package, data is sent to Google upon the very first activation of Atom.

```
11	3.246164970	172.217.19.110	10.191.1.6	TCP	60	443 → 34620 [SYN, ACK] Seq=0 Ack=1 Win=42540 Len=0 MSS=1368 SACK_PERM=1 TSval=62156495 TSecr=369729 WS=128
```
