### ISSUE TITLE
"Open File..." uses gnome-open instead of kde-open in KDE

### ISSUE THREAD

**Issue by cfbaptista** [atom/atom#12437]
When I press **File > Open File...** or **File > Open Folder...** Atom launches gnome-open instead of kde-open in Kubuntu 14.04. Can this be configured by the user or changed by the developers?

**Comment by 50Wliu** [comment]
This is handled by Electron - please open an issue on [electron/electron](https://github.com/electron/electron) instead.  Thanks!
