### ISSUE TITLE
Indent guides don't show up on existing editors

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#12451]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Existing editors (ie those that are opened automatically upon opening an existing project) do not show indent guides.  New editors (ie those that are opened after Atom loads the existing project) do.  In addition, closing the existing editors and reopening them will cause them to start showing indent guides.  I believe this started after the TextEditor extraction PR, though I'm not completely sure.

### Steps to Reproduce

1. Open Atom and add a project folder (making sure the indent guides option is enabled)
2. Open some files
3. Close Atom
4. Open Atom again, making sure it restores the project folder and files added in step 1
5. Note that no indent guides are shown
6. Open a different file and note that indent guides are shown on that file only
7. Close one of the existing files and reopen it and notice that indent guides are now shown on that file as well

**Expected behavior:** Indent guides to always show if the option is enabled

**Actual behavior:** Indent guides do not show on existing editors until they are reopened

### Versions

```
Atom    : 1.11.0-dev-351bad4
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.2.windows.1
visual studio 2015
```

Windows 10 x64.

/cc @lee-dohm

**Comment by maxbrunsfeld** [comment]
Thanks for catching this @50Wliu!
