### ISSUE TITLE
Tree view does not correctly indicate changed files (OS X, Atom Beta 1.10.0-beta5)

### ISSUE THREAD

**Issue by tikiatua** [atom/atom#12456]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? no
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? Atom 1.10.0-beta 5 on OS X
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)? yes
* [x] Are you reporting to the [correct repository] (https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? yes
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported? yes

### Description
The tree view git indicator indicates the complete folder containing a changed files as changed. Not only the actual file.
![atom-beta 1 10 0-beta5](https://cloud.githubusercontent.com/assets/1379175/17770624/f4d96770-653e-11e6-9e22-9336a5a96579.png)

### Steps to Reproduce

1. Create git repository
2. Modify a file in directory
3. Inspect status in tree view

**Expected behavior:**
Only changed file and folder name should be indicated as modified (as working correctly in Atom 1.9.8)
![atom 1 9 8](https://cloud.githubusercontent.com/assets/1379175/17770609/e586cfc4-653e-11e6-8457-aedd785fd7c5.png)

**Actual behavior:** [What actually happened]
All files and folders in the directory containing the file are indicated as modified. The issue does not arise if Atom Beta is started in safe mode.
![atom-beta 1 10 0-beta5](https://cloud.githubusercontent.com/assets/1379175/17770624/f4d96770-653e-11e6-9e22-9336a5a96579.png)

### Versions
OS: OS X 10.11.6 (El Capitan)
Atom: 1.10.0-beta5
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0

**Comment by Ben3eeE** [comment]
> Can you reproduce the problem in safe mode? no

Since you can't reproduce this in safe mode this is a problem with one of your installed packages. https://github.com/atom/tree-view/issues/923 mentions problems with material ui theme having similar issues. If you are using the material ui theme perhaps https://github.com/atom-material/atom-material-ui/issues/317 applies to you.

**Comment by tikiatua** [comment]
Thank you for the very fast response. That does indeed seem to be the case.
