### ISSUE TITLE
Atom 1.9.8 freezes everytime when an opened large file gets updated under Windows 10

### ISSUE THREAD

**Issue by bailuding** [atom/atom#12450]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

I opened two files in Atom, one is 3MB large. The smaller file was active, and then the large file got updated (more exactly, rewritten) by another external process. After that, Atom did not respond and froze. It would not come back to life and I had to restart it.
### Steps to Reproduce
1. Open a large file, and switch to a window with a smaller file.
2. Update the large file with some external process.
3. Atom freezes.

**Expected behavior:** [What you expected to happen]
The large file can get reloaded (depending on your choice) just like what will happen in Notepad++

**Actual behavior:** [What actually happened]
Atom just freezes.
### Versions

1.9.8

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by MrBlaise** [comment]
I can reproduce this, it happens everytime I use browserify to generate a large file while it is open in Atom and it freezes and will stay "frozen" until it is restarted.

windows 10 x64
Atom 1.12.7

**Comment by jtauber** [comment]
I can reproduce this on Atom 1.14.3 on MacOS 10.12.3 too. Has no problem opening a large file, but if that file is open in Atom while another processes rewrites it, Atom freezes until restarted.

**Comment by PhillMcKraken** [comment]
I've either reproduced this, or a similar root cause.
Atom 1.14.3 / Win10 64bit

After a LOT of time, I managed to get a cpuprofile of the issue. If you give it enough time, it un-freezes. Unfortunately trying to save the profile off results in an empty file, I tried a few times. Heres a screenshot.

![profile](https://cloud.githubusercontent.com/assets/20247733/23336962/c23e4b1c-fba4-11e6-95f6-0e4d8ff292b5.png)

The slowdown starts when the file opens, until the styles are parsed visually. 

Safemode reproduces it.

**Comment by PhillMcKraken** [comment]
Fixed by https://github.com/atom/atom/pull/13820

This should be closed.

**Comment by Ben3eeE** [comment]
Thanks @PhillMcKraken

**Comment by 50Wliu** [comment]
The issue specifies a "large" file, not a minified file, and also talks about external reloading, so I don't think this has to do with #13820.  Reopening.

**Comment by 50Wliu** [comment]
@bailuding I noticed that you couldn't reproduce this in safe mode (`atom --safe`): does it not happen in safe mode, or did you not try?  If the latter, please try reproducing this in safe mode and tell us how it goes.  Thanks!

**Comment by PhillMcKraken** [comment]
Just to be clear, I did reproduce the root report and narrowed it to what I reported. While I cant speak for bailuding, I did try to do some due diligence.
