### ISSUE TITLE
Atom crash on Windows 10

### ISSUE THREAD

**Issue by PaulRps** [atom/atom#12465]
# Description

The editor crash when i try to run, it not open and present a error message in a little window: 
      "The editor has crashed
       please report this issue to http://github.com/atom/atom

```
   //options
   -> close the window
   -> reload
   -> keep it open"
```

If i choose the third option, the editor keep open but don't make nothing, don't respond to nothing. Already i tried to reload and reinstall but don't solve, 
### Steps to Reproduce
1. [First Step]

I downloaded from site: https://atom.io/ (Download Windows Installer)
1. [Second Step]

I used the installer to install.
1. [Third Step]

I run the Atom 

![image](https://cloud.githubusercontent.com/assets/12769247/17786786/ca385ed6-655c-11e6-8880-796960f90b26.png)

**Comment by 50Wliu** [comment]
If you remove `%USERPROFILE%\.atom`, does that solve the crashes?  If not, can you please upload the latest dump file from `%TEMP%\Atom Crashes` here?  Thanks.

**Comment by Ehekatl** [comment]
this happened frequently since I upgrade to 1.10
dump file is [here](http://obfjtv6fz.bkt.clouddn.com/Atom%20Crashes.zip)

**Comment by fedyvenom** [comment]
[91b9cb6b-7b5b-4caf-b5ab-770313cc044c.txt](https://github.com/atom/atom/files/495844/91b9cb6b-7b5b-4caf-b5ab-770313cc044c.txt)
[operation_log.txt](https://github.com/atom/atom/files/495846/operation_log.txt)
I also using Windows 10, last thing i remember is changing my system PATH variable sequence. But didn't remove atom's.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12465#issuecomment-240836950. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by patricorgi** [comment]
@50Wliu I downloaded a beta version of Atom and depressed the archiver file in Downloads folders. It doesn't give out crash error message when I opened Atom.exe. But if I move the folder into my Program Files (x86) folder, the crash error occurs. Could you get some hint of this problem?
