### ISSUE TITLE
Why so many Atom Helpers?

### ISSUE THREAD

**Issue by mikeerickson** [atom/atom#12460]
### Description

Trying to determine what is causing Atom to slow to a crawl, so I viewed Activity Monitor.  
At this point, it is shows 9 instances of Atom Helper (see screenshot)

![atom-helper](https://cloud.githubusercontent.com/assets/183153/17782379/101d8730-6528-11e6-82ac-0a5f57963639.png)

**Comment by 50Wliu** [comment]
Please open a new issue and **completely** fill out the provided issue template so that we can better assist you.

**Comment by mikeerickson** [comment]
@50Wliu will do
