### ISSUE TITLE
Open folder in three on file click

### ISSUE THREAD

**Issue by ansmonjol** [atom/atom#12477]
**Steps which explain the enhancement**

1. Double click on the file tab on the top of the IDE.
2. The file is automatically focus on the folder three and the file highlighted.

**Current and suggested behavior / Why would the enhancement be useful to most users**

I was wondering if it could be possible to open the three folder on the sidebar on clic or double click on file tab. 

If a file is open but the folder is hard to access or closed, far away or lost in all the opened folder and you want to access to a file near the one open, without having to search and navigate longer in the folder three.

[List some other text editors or applications where this enhancement exists]

This behaviour come from *visual code studio* and is pretty cool when you are lost in a big project and want to access faster to a folder. But visual have this behaviors on every file switch, which some time is not needed (that's why it could be cool to have this event oncli on click or double click on the file tab).

**Atom Version:** 1.9.9
**OS and Version:** OXS 10.11.6

**Comment by Ben3eeE** [comment]
Questions like this are more suited for asking on [discuss](https://discuss.atom.io) where you will get help faster from awesome community members. This is because the Atom team is trying to [manage the deluge of atom issues](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html).

**Comment by ansmonjol** [comment]
Hum Sorry for that, I'll post it on the blog for sure.

Thanks for your quick response.

**Comment by 50Wliu** [comment]
The "Auto Reveal" option in the Tree View settings seems to be basically what you're asking for.  Closing this out.

**Comment by Ben3eeE** [comment]
Also you can bind the reveal active file command or use the existing keybinding if you feel auto is too much.
If you want help with any of this i will be happy to answer on discuss.

**Comment by ansmonjol** [comment]
Thanks a lot @Ben3eeE 

I changed my keymap.cson to look like this :
```
'.platform-darwin atom-workspace atom-text-editor:not([mini])':
...
  'alt-cmd-r': 'tree-view:reveal-active-file'
```
This was exactly what I was looking for 😄
