### ISSUE TITLE
Atom is getting hanged . 

### ISSUE THREAD

**Issue by syedbaqarrizvi** [atom/atom#12475]
Atom is getting hanged in Ubuntu . if i search any file and click to open it it just hanged for minutes i dont know why .
![image](https://cloud.githubusercontent.com/assets/15075559/17808309/0398e6f6-6629-11e6-9468-c456fa2559c9.png)

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/atom/issues/979
