### ISSUE TITLE
 Code completion doesn’t work when I split (not always and only in one side)

### ISSUE THREAD

**Issue by n3ph7hy5** [atom/atom#12476]
Hello,
I'm in ubuntu 16.04, I just updated from the repo to version 1.9.8 of atom and now when I do: "open folder then split right" (same file to the left and right) the completion works only on the left but not on the right.
If I open directly a file and split it works fine in both sides (but not always).
What I did:
-atom --safe,
-deleted "~/.atom", 
-atom --clear-window-state.
Same results
I completely removed from synaptic and then install it again but nothing changed 
I updated to 1.9.9, repeated again but no changes.
$ atom --version
  Atom    : 1.9.9
  Electron: 0.37.8
  Chrome  : 49.0.2623.75
  Node    : 5.10.0
$ apm --version
  apm  1.10.0
  npm  2.13.3
  node 0.10.40
  python 2.7.12
  git 2.7.4
[HERE](https://discuss.atom.io/t/code-completion-doesnt-work-when-i-split-not-always-and-only-in-one-side/32312/1) you can see a gif of the problem!

**Comment by Ben3eeE** [comment]
Probably belongs in the autocomplete-plus repository. Possibly a duplicate. Would have been better to wait for @lee-dohm to reply on discuss than to rush and create this issue.

**Comment by 50Wliu** [comment]
This belongs on [atom/autocomplete-plus](https://github.com/atom/autocomplete-plus) - please create a new issue there if one does not already exist for it.
