### ISSUE TITLE
UNC paths are not supported. Defaulting to Windows directory.

### ISSUE THREAD

**Issue by nicholas-c** [atom/atom#12478]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Heyyy, so getting this error an awful lot when working with projects folders and files from a network drive, very annoying :\

`Error: '[network samba drive]' CMD.EXE was started with the above path as the current directory. UNC paths are not supported. Defaulting to Windows directory.
Error: '[network samba drive]'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
    at parameters.exit (C:\Users\Nicholas Carter\.atom\packages\linter-jshint\node_modules\atom-linter\lib\helpers.js:47:27)
    at triggerExitCallback (C:\Users\Nicholas Carter\AppData\Local\atom\app-1.9.8\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Nicholas Carter\AppData\Local\atom\app-1.9.8\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)`

**Comment by lorengordon** [comment]
I'm seeing this as well. My documents folder is a network drive, but I've mounted it as H: and am actually launching atom from the H: mount. Atom is somehow still resolving the cwd back to the UNC path.

**Comment by Ben3eeE** [comment]
@lorengordon https://github.com/atom/atom/issues/13104 covers what you describe.

@nicholas-c Closing this in favor of https://github.com/atom/atom/issues/13104 or https://github.com/nodejs/node/issues/5160 depending on if you have spaces in the path or not.

**Comment by lorengordon** [comment]
@Ben3eeE thanks, i subscribed to that issue to track the resolution or any suggested workarounds.
