### ISSUE TITLE
Command-a in Menubar/Help doesn't highlight search input. 

### ISSUE THREAD

**Issue by jaepage** [atom/atom#12471]
To reproduce: 
1) Press <kbd>command</kbd><kbd>shift</kbd><kbd>/</kbd> to trigger `Menubar / Help` search input. 
2) Type anything to populate the search input. 
3) Press <kbd>command</kbd><kbd>a</kbd>. 
- Expected behavior (convention for Mac OS native and major third-party apps): Typed search input should highlight entirely. 
- Observed behavior: Keyboard focus is lost from the search input, and the file's contents are highlighted entirely instead. 

Mac OS 10.11.6
Atom 1.9.9

**Comment by rahatarmanahmed** [comment]
Duplicate of #10735

**Comment by jaepage** [comment]
Closing in favor of previously reported https://github.com/atom/atom/issues/10735.
