### ISSUE TITLE
"Restart and Install" does not restart Atom after update on Windows

### ISSUE THREAD

**Issue by ValisVeckers** [atom/atom#12472]
### Prerequisites
- [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

When Squirrel notifies about new Atom release, after clicking "Restart and Install" button on about view, Atom exits, update completes with some errors logged to SquirrelSetup.log but Atom is not restarted.
This has been happening during every update since I installed Atom 1.8.0 or one version before that.

Here is the whole [SquirrelSetup.log](https://github.com/atom/atom/files/426153/SquirrelSetup.log.txt) containing every line since update to 1.8.0 on 2016-07-03.

Possible cause:

```
System.IO.IOException: The process cannot access the file 'C:\Users\User\AppData\Local\SquirrelTemp\tempe\lib\net45\atom.exe' because it is being used by another process.
```

Might be caused by security software locking the file druring scanning.
### Steps to Reproduce
1. Open about view when a new release is available
2. Wait for download to finish
3. Click "Restart and Install" button

**Expected behavior:**
Atom restarting after Squirrel completes updating to latest release

**Actual behavior:**
Atom is not restarting after updates have been applied
### Versions

Atom    : 1.9.7
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
Squirrel: 1.2.4.0

OS: Windows 10 Pro, version 1607, build 14393.51

**Comment by hochbrian** [comment]
I have the same behavior with Atom as well as other Electron apps.

**Comment by MorganMarshall** [comment]
Has never worked for me yet.

**Comment by amaslenn** [comment]
Update to 1.23. Still here.

**Comment by Schlammsuhler** [comment]
i had the same problem on Mac OS X 10.13.5
I was able to update after quitting and starting it 5 times in a row

**Comment by adammenges** [comment]
Yep, same on MacOS 10.14.2 (18C54)
