### ISSUE TITLE
Atom crashes on opening file, if bare git repo is in the same directory

### ISSUE THREAD

**Issue by plats1** [atom/atom#12474]
### Description

The editor crashes if I try to open a file (`readme.md` in the picture), which is in a directory which also contains a bare git repo:

![folders](http://i.imgur.com/tT1niJ6.png)
### Steps to Reproduce
1. Create bare git repository (`bare` property in `.git/config` set to `true`)
2. Add file to **containing** folder (e.g. a readme file)
3. Open that file

**On start:**
![crash](http://i.imgur.com/IoLVExz.png)
### Note

If the `bare` property in `.git/config` is changed to `false`, the editor starts as expected and vice versa.
### Versions

Windows: 10

Atom: 1.9.9
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0

**Comment by 50Wliu** [comment]
Confirmed on Atom 1.11.0-dev-080f1d3, Windows 10 x64.  In fact, I can't even open the containing folder itself.

Crash dump (at least, I think this is the correct one):
[642dd009-4c59-4136-9818-bdc044c28fdc.zip](https://github.com/atom/atom/files/427463/642dd009-4c59-4136-9818-bdc044c28fdc.zip)

**Comment by fedyvenom** [comment]
[6e6f4f22-6696-4349-8a0f-10db52b5a3b1.zip](https://github.com/atom/atom/files/496031/6e6f4f22-6696-4349-8a0f-10db52b5a3b1.zip)
Confirmed on Atom 1.10.2 in Windows 10 x64. Only crash with specific directory which its remote url has been changed before this problem occurs.

**Comment by fedyvenom** [comment]
@plats1 @50Wliu Have solved this issue with change all files line-break type to CR LF.
I use Git Bash to fix it, git add --all will convert all files to CR LF.
Commit then Push and try add your project dir in Atom again.
Hope this also solved your issue.

**Comment by vedharish** [comment]
I think the root cause for this is [this issue](https://github.com/libgit2/libgit2/issues/3901). 
As @plats1 mentioned, it happens if we change just "bare = false" in `.git/conf` without any other change. I think `push/pull` is not allowed on bare repositories, so not sure about line endings being the issue here.
