### ISSUE TITLE
Command-d fails to trigger "Don't save" in unsaved changes closing dialog (Mac).

### ISSUE THREAD

**Issue by jaepage** [atom/atom#12470]
Steps to reproduce: 
1) Press <kbd>command</kbd><kbd>n</kbd> to open a new file. 
2) Type any character.
3) Press <kbd>command</kbd><kbd>w</kbd> to close the new file.
4) The unsaved changes warning dialog appears:
- Pressing <kbd>return</kbd> will correctly trigger "Save".
- Pressing <kbd>esc</kbd> will correctly trigger "Cancel".
- Pressing <kbd>command</kbd><kbd>d</kbd> incorrectly attempts to trigger `Menubar / Find / Select Next`. Standard Mac OS behavior is to trigger "Don't Save". 

Mac OS 10.11.6
Atom 1.9.9

**Comment by 50Wliu** [comment]
This is a duplicate of #12277 - feel free to subscribe there for updates.

**Comment by jaepage** [comment]
Thank you.
