### ISSUE TITLE
Allow editor:indent-selected-rows to indent empty lines when only one line is selected

### ISSUE THREAD

**Issue by willlma** [atom/atom#12483]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Can't indent empty line
### Steps to Reproduce
1. Click into an empty line
2. Click _Edit > Lines > Indent_

**Expected behavior:** Indent

**Actual behavior:** Nothing
### Versions

Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.8.1
OSX 10.11.6

**Comment by andyrichardson** [comment]
Is there a reason you would want to indent an otherwise empty line?

**Comment by willlma** [comment]
In many IDEs, pressing tab indents the line irrespective of cursor location. I like the behavior (can't imagine why I'd want to insert a tab mid-line) so I've mapped tab to `'editor:indent-selected-rows'`.  Now when I'm on a blank line and press tab, nothing happens. 

Any workaround is welcome.

**Comment by andyrichardson** [comment]
I use _tab_ and _shift+tab_ to indent/unindent code respectively. It also has the added ability of being able to insert tabs into new lines.

**Comment by willlma** [comment]
By default, tab only indents a line if the caret is at the beginning of the line. If it's in the middle of the line, it inserts a tab mid-line, which is not the behavior I'm seeking. I'd like for it to indent the line irrespective of the location of the caret on the line.

**Comment by andyrichardson** [comment]
With all due respect, I'm still struggling to understand why you consider indentation of an empty line to be necessary. One could argue that allowing this would promote the production of unnecessary characters.

Are you able to provide a use case which justifies the inclusion of this feature?

**Comment by willlma** [comment]
Let's start from the beginning. What I would like to do is to be able to press the tab key while the caret is in the middle of the line like
```
This is text before the caret|This is text after the caret
```
and the result should be 
```
    This is text before the caret|This is text after the caret`
```
instead of 
```
This is text before the caret  |This is text after the caret
```

Note that the middle example is indented, whereas the last example added a space mid-line. Any idea how to achieve this?

**Comment by Ben3eeE** [comment]
Not adding whitespace to empty rows is good if you select multiple rows to indent. @willlma wants to use it for indenting a single row and because of using `editor:indent-selected-rows` in place of `editor:indent` wants it to be able to indent an empty line when only one line is selected.

![indent selected rows](https://cloud.githubusercontent.com/assets/1058982/19211412/acf48f46-8d3b-11e6-9bc2-85f708d284bd.gif)

**Comment by willlma** [comment]
Thank you for expressing it better than I could, @Ben3eeE. That's correct.
