### ISSUE TITLE
Atom creates redundant `/home/<user>/tmp` directory on start

### ISSUE THREAD

**Issue by zdroid** [atom/atom#12481]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom creates redundant `/home/<user>/tmp` directory whenever I start it. I am using Ubuntu 16.04 and I find it pretty annoying to see an empty `/tmp` directory while my `TEMP` variable is set to `/tmp`.

### Steps to Reproduce

1. Open the Atom
2. Check your home folder

**Expected behavior:** No creation of any additional directories in `/home/<user>`

**Actual behavior:** `/home/<user>/tmp` directory created yet again

I can reproduce the issue on any 1.6.0+ version of Atom.

### Versions

```sh
$ atom --version
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

I have no custom APM packages installed.

**Comment by isdampe** [comment]
Cannot reproduce on Ubuntu GNOME 16.04.1

**Comment by zdroid** [comment]
It seems like issue got fixed. I had to restart computer and it all works fine now.
