### ISSUE TITLE
Projects window session restored, last file open not restored

### ISSUE THREAD

**Issue by fiando** [atom/atom#12487]
### Update 
All is OK when open atom as super user ( root )

### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom project window session restored but anything last file open not restored ( included not saved file )

### Steps to Reproduce

1. Open Atom Editor
2. Unchecked Empty Editor On Start
    - then set atom core config restorePreviousWindowsOnStart: true
3. Try to open file tab from existing window project
4. Close Atom Editor
5. Open again, only window project opened ( empty editor )
6. Close Atom Editor
7. Try to 
  - delete atom compile cache
  - delete atom storage
8. Open Atom Editor
9. Add Project Folder and open file tab from project file
10. Close Atom Editor
11. Open Atom Editor ( empty editor )

**Expected behavior:** 

- Any last file should be opened, not only project window
- Any unsaved file should be restored when open

**Actual behavior:**  Only project window opened with empty editor on start

### Versions
Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
OS : Linux Mint Cinnamon 18 64-bit

**Comment by fiando** [comment]
The problem Uncaught (in promise) TypeError: Cannot read property 'transaction' display at chrome dev tools, fix this issues with delete _~/.config/Atom/IndexedDB_ 
https://github.com/atom/atom/issues/11806

**Comment by james-gamesparks** [comment]
+1

Mac OS X 10.11.6, Atom 1.9.9

1.  Open Atom.
2.  File -> New File.
3.  Enter some unsaved text.
4.  In the Mac OS toolbar at the top, select Atom -> Quit.
5.  Re-open Atom.
6.  New file with unsaved changes is gone.  An empty editor appears.
