### ISSUE TITLE
Editor crash on open

### ISSUE THREAD

**Issue by nlacombe42** [atom/atom#12485]
Atom crash when I try to open it.

The crash happens every time I try to open atom.

Clearing the window state and resetting to factory default does not fix the issue.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Running command "atom" or "atom -fnw --safe test.txt"

What I expect:
The atom editor opens (a window containing the editor pops up).

What happens:
Either there is no change in the GUI or a see a window that says "The editor has crashed. Please report this issue to [...]"

Also here is the logs of the "atom -fnw --safe test.txt" command:

[4656:0819/205932:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
App load time: 116ms
[4656:0819/205932:ERROR:browser_main_loop.cc(277)] gdkwindow-x11.c:5555 drawable is not a native X11 window (http://crbug.com/329991)
[4656:0819/205932:ERROR:browser_main_loop.cc(277)] gdkwindow-x11.c:5555 drawable is not a native X11 window (http://crbug.com/329991)
[4656:0819/205932:ERROR:browser_main_loop.cc(277)] gdkwindow-x11.c:5555 drawable is not a native X11 window (http://crbug.com/329991)

### Versions
OS: Manjaro 16.06.1
Atom    : 1.9.8
Electron: 1.3.3
Chrome  : 52.0.2743.82
Node    : 6.3.0
apm  1.12.6
npm  3.10.6
node 6.3.1
python 3.5.2
git 2.9.2

**Comment by nlacombe42** [comment]
Apparently it might be because of my version of freetype2 (2.6.5-2) according to this comment: https://github.com/atom/atom/issues/11612#issuecomment-216696720

Could someone confirm that and give me an URL for the issue that is already open?

**Comment by Smana** [comment]
I don't know if it is related but my atom crashes with the following trace in the logs ```systemd-coredump[2335]: Process 2311 (atom) of user 1000 dumped core.
                                                  
                                                  Stack trace of thread 2311:
                                                  #0  0x00007f8b9f1c6a8a _ZNK2v88internal18SerializedCodeData11SanityCheckEPNS0_7IsolateEPNS0_6StringE (libnode.so)
                                                  #1  0x00007f8b9f1c572e _ZN2v88internal14CodeSerializer11DeserializeEPNS0_7IsolateEPNS0_10ScriptDataENS0_6HandleINS0_6StringEEE (libnode.so)
                                                  #2  0x00007f8b9eea9cab _ZN2v88internal8Compiler13CompileScriptENS0_6HandleINS0_6StringEEENS2_INS0_6ObjectEEEiiNS_19ScriptOriginOptionsES6_NS2_INS0_7ContextEEEPNS
                                                  #3  0x00007f8b9ed169cf _ZN2v814ScriptCompiler22CompileUnboundInternalEPNS_7IsolateEPNS0_6SourceENS0_14CompileOptionsEb (libnode.so)
                                                  #4  0x00007f8b8a1ad7b8 _ZN22CustomRunInThisContextL22RunInThisContextCachedERKN2v820FunctionCallbackInfoINS0_5ValueEEE (cached-run-in-this-context.node)
                                                  #5  0x00007f8b9ed3e0a4 _ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE (libnode.so)
                                                  #6  0x00007f8b9ed7211f n/a (libnode.so)
                                                  #7  0x00007f8b9ed80504 n/a (libnode.so)
                                                  #8  0x00002a2f7550c1fb n/a (n/a```

I have the same freetype version as you @nlacombe42.

I'm on ArchLinux and i tested several versions of atom.

**Comment by Braden1996** [comment]
I am having the exact same issue. It still occurs on a fresh install of Manjaro KDE. If you'd like any information from me, please don't hesitate to ask!

**Comment by nlacombe42** [comment]
I tried uninstalling the official atom package for manjaro and installing aur/atom-editor.
The aur/atom-editor does not crash. I do not know if it is a fix from atom (since the version of atom is different) or from arch.

Here is the version information for aur/atom-editor :

Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.10.0
npm  2.13.3
node 0.10.40
python 3.5.2
git 2.9.2

**Comment by Smana** [comment]
ok so that's not the same issue as mine because i just installe from AUR and i still have the same error.
```
atom --version
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by Braden1996** [comment]
I uninstalled Atom, along with all its dependencies, and then installed the version from AUR. It seems to of fixed the problem. If these reported version numbers are correct, it could be worth to see if the AUR's does anything different - it did seem to take a while longer to install.

**Comment by Smana** [comment]
I tried the docker image but i have the same error, i guess it is probably due to my X environment....

**Comment by 50Wliu** [comment]
> Electron: 1.3.3

This is not a supported Electron version.  Please contact the maintainer of whichever software repository you downloaded Atom from for support instead.

https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md

**Comment by nlacombe42** [comment]
The initial package that cause trouble was on one of the manjaro mirror. I assume the repository was "Community" since that is the repository for the arch package. (the manjaro equivalent of https://www.archlinux.org/packages/community/x86_64/atom/)

The package that worked was on the AUR : https://aur.archlinux.org/packages/atom-editor/

Now the atom package of manjaro has been updated and the problem is no longer present with atom 1.9.9-2.
