### ISSUE TITLE
Tooltip with file path stay after closing pane

### ISSUE THREAD

**Issue by sebastien-gallet** [atom/atom#12490]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

A tooltip with a file path stay on the screen after closing a pane if the contextual menu is brought by clicking on a actual file tab.

![tooltip-bug-1](https://cloud.githubusercontent.com/assets/968164/17837224/edac6294-67e7-11e6-9f06-5f282d086740.png)
![tooltip-bug-2](https://cloud.githubusercontent.com/assets/968164/17837225/ee005818-67e7-11e6-84e5-6ed84f04c506.png)
![tooltip-bug-3](https://cloud.githubusercontent.com/assets/968164/17837228/ee0d1d82-67e7-11e6-877d-28374f174078.png)
![tooltip-bug-4](https://cloud.githubusercontent.com/assets/968164/17837226/ee062a86-67e7-11e6-9486-63e1b3413147.png)
![tooltip-bug-5](https://cloud.githubusercontent.com/assets/968164/17837227/ee0667ee-67e7-11e6-9387-33717a76d440.png)

### Steps to Reproduce

1. Open a file
2. Split the pane (any direction)
3. Close a pane with the cursor on a file tab

**Expected behavior:**

The pane is closed and no tooltip with the file path is shown

**Actual behavior:**

The pane is closed but an unremovable tooltip with the file path stays on screen.
The tooltip will finally disappear if the window is resized.

### Versions

Both versions: Atom 1.9.9 and Atom beta 1.10.0-beta6 on OS X 10.11.6

**Comment by Ben3eeE** [comment]
https://github.com/atom/tabs/issues/362

**Comment by 50Wliu** [comment]
Thanks.
