### ISSUE TITLE
Support HTML 4 attributes

### ISSUE THREAD

**Issue by weenzeel** [atom/atom#12506]
I would like to use Atom for html-email workflow. When writing html-email we often need to use html 4 attributes like cellpadding and cellspacing on table element. But atom only support autocompletion for html 5. Could HTML 4 etc please be made available by choice of the developer?

**Comment by arcticicestudio** [comment]
If you only need it for HTML email development you can try the awesome [MJML](https://mjml.io) language project. There is also a Atom package [`language-mjml`](https://atom.io/packages/language-mjml).
On the other hand the `cellpadding` and `cellspacing` attributes are deprecated and should be defined via CSS.

**Comment by jerone** [comment]
The [language-html](https://github.com/atom/language-html) package takes care of syntax highlighting and snippets to HTML files in Atom.
The [autocomplete-html](https://github.com/atom/autocomplete-html) package takes care of  HTML tag and attribute completions in Atom.

**Comment by 50Wliu** [comment]
I don't think autocomplete-html will be supporting deprecated tags or attributes.  If necessary you can create your own autocomplete package to provide those.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
