### ISSUE TITLE
On Mac clicking Atom icon in a Dock opens multiple windows

### ISSUE THREAD

**Issue by tomasx** [atom/atom#12516]
**Scenario**
- Open Atom
- Close Atom by pressing red X bubble at the top left corner. No you don't have any windows opened just an active Atom icon in the dock
- Click quickly several times on Atom icon in the doc

**Expected** 
- To open only one window despite the fact that I clicked several times

**Actual**
- Opens one window per click. [See screenshot](https://dl.dropboxusercontent.com/u/6417398/Screen%20Shot%202016-08-25%20at%2013.29.53.png)

**Info**
- Atom 1.9.9
- Mac OS 10.10.5

**Comment by pietbrauer** [comment]
I think this is related to #11937

**Comment by damieng** [comment]
Will track under the other issue.
