### ISSUE TITLE
Dueling tab length between editor default and languages

### ISSUE THREAD

**Issue by kmck** [atom/atom#12518]
### Description

When the Atom Editor Settings tab length is set, it is not possible to use a language-specific tab length that matches the language's default. It will assume the "default" value and use the editor tab length instead.

For example, the Atom editor default and LESS language both use a tab length of 2 spaces. If you override the default setting for the editor, it's not possible to force LESS to use 2 spaces, because the editor assumes that you want the default and then falls back to the global editor override.

### Steps to Reproduce

1. Set tab length to 4 spaces in Atom Editor Settings.
2. Set LESS language settings to 2-space tabs.
3. Observe that the language settings input resets itself and that the effective tab length when indenting in LESS files is 4 spaces, not 2.

**Expected behavior:** You can force the tab length to be the default value without it resetting.

**Actual behavior:** If the value matches the default, it will reset to the placeholder version of the setting (`Default: 2`) rather than appearing as an override.

### Versions

`atom --version`
apmAtom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

`apm --version`
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.7.4

OS X 10.11.6

**Comment by Ben3eeE** [comment]
https://github.com/atom/settings-view/issues/774?

**Comment by kmck** [comment]
Yup, same issue. Sorry!
