### ISSUE TITLE
Wrong C++ highlighting

### ISSUE THREAD

**Issue by slypiggies** [atom/atom#12510]
![atom](https://cloud.githubusercontent.com/assets/21236048/17961587/3b030594-6adf-11e6-940d-66d3410d5056.png)

**Comment by thomasjo** [comment]
Thanks for the report, but since this has been opened on the wrong repo, I'm closing this issue.
The issue should have been opened on the [language-c](https://github.com/atom/language-c) repo. Additionally this is potentially a duplicate (or at least related to) atom/language-c#146.
