### ISSUE TITLE
Feature: Windows Bash 'WLS' / 'WSL' atom support

### ISSUE THREAD

**Issue by bergerd1** [atom/atom#12519]
### Prerequisites

* [X ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom can be installed through Windows 10 Bash, but it does not run. 

### Steps to Reproduce

Support Atom for Windows Bash 'WSL' on Windows 10

- Turn Developer Mode on via Settings > Update & security > For developers.
- Click the Start button , click Control Panel, click Programs, and then click Turn Windows features on or off.
- Enable Windows Subsystem for Linux (Beta)
- To get Bash installed, open Command Prompt and type “bash”

1. Run `sudo apt-get update`
> $ sudo apt-get update

2. Add repository
> $ sudo add-apt-repository ppa:webupd8team/atom

3. Update repository
> $ sudo apt-get update

4. Install Atom
> $ sudo apt-get install atom

5. Run Atom
> $ atom .

- Or try `Atom --version` (or any Atom command. They all fail.)

> $ atom --version

**Expected behavior:**

- Atom to open in current directory. Or Atom to show version. Or do something.

**Actual behavior:** [What actually happened]

- The output from any Atom command is shown below:

```
david@DESKTOP-09AQL1Q:~$ atom --version
david@DESKTOP-09AQL1Q:~$ atom --safe
david@DESKTOP-09AQL1Q:~$ /usr/bin/atom: line 111: 27266 Aborted                 (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[27266:0825/103701:FATAL:render_sandbox_host_linux.cc(40)] Check failed: 0 == shutdown(renderer_socket_, SHUT_RD). shutdown: Invalid argument

#0 0x000001bfb0ae <unknown>
#1 0x000001c10f3b <unknown>
#2 0x000001c114fd <unknown>
#3 0x0000025e2ae2 <unknown>
#4 0x0000023cf2f2 <unknown>
#5 0x0000023d5fd4 <unknown>
#6 0x0000023ce946 <unknown>
#7 0x0000011375e1 <unknown>
#8 0x0000011362d0 <unknown>
#9 0x000003088b7c main
#10 0x7fa7abb81f45 __libc_start_main
#11 0x000000544249 <unknown>
```

### Versions

- The latest? Not sure of the version number.  As the command `$ atom --version` does not work.
Run `apt-get install atom` again to make sure it is the latest version?
```
david@DESKTOP-09AQL1Q:~$ sudo apt-get install atom
[sudo] password for david:
Reading package lists... Done
Building dependency tree
Reading state information... Done
atom is already the newest version.
```

## Additional Thoughts

- Maybe a GUI has to be enabled for Atom to run?
- I am able to Run Dolphin through Windows Bash 'XTerm'

```
david@DESKTOP-09AQL1Q:~$ sudo apt-get install lubuntu-desktop
...
david@DESKTOP-09AQL1Q:~$ sudo apt-get install dolphin [?]
david@DESKTOP-09AQL1Q:~$ echo $DISPLAY
david@DESKTOP-09AQL1Q:~$ export DISPLAY=localhost:0
david@DESKTOP-09AQL1Q:~$ xterm

(now in Xterm window)
david@DESKTOP-09AQL1Q:~$ dolphin .
```

- Open atom from within dolphin [?]
![atom-wsl-dolphin-1](https://cloud.githubusercontent.com/assets/11757552/17974719/2ab9b64e-6ab5-11e6-940b-0478bba92b1e.PNG)

- This error appears in Xterm (after trying to run Atom from within Dolphin)

```
QFileSystemWatcher: failed to add paths: /opt/atom
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: Invalid argument
QFileSystemWatcher: failed to add paths: /opt/atom
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: Invalid argument
QFileSystemWatcher: failed to add paths: /opt/atom/chromedriver
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: Invalid argument
QFileSystemWatcher: failed to add paths: /opt/atom/locales
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: Invalid argument
QFileSystemWatcher: failed to add paths: /opt/atom/resources
[27342:0825/111140:FATAL:render_sandbox_host_linux.cc(40)] Check failed: 0 == shutdown(renderer_socket_, SHUT_RD). shutdown: Invalid argument
#0 0x000001bfb0ae <unknown>
#1 0x000001c10f3b <unknown>
#2 0x000001c114fd <unknown>
#3 0x0000025e2ae2 <unknown>
#4 0x0000023cf2f2 <unknown>
#5 0x0000023d5fd4 <unknown>
#6 0x0000023ce946 <unknown>
#7 0x0000011375e1 <unknown>
#8 0x0000011362d0 <unknown>
#9 0x000003088b7c main
#10 0x7f399f981f45 __libc_start_main
#11 0x000000544249 <unknown>
```

**Comment by damieng** [comment]
Thank-you for your detailed report.

The top request right now on WSL is the ability to launch Windows applications from the Bash command line which would be our preferred way of using Atom from the WSL.  

The amount of effort to get the Linux version running in WSL would be non-trivial given the early state of WSL and isn't something the core team could commit to at this time.

**Comment by awkaiser** [comment]
I stumbled down a rabbit hole from [comments on this WSL Github issue about filesystem watchers not working](https://github.com/Microsoft/BashOnWindows/issues/216#issuecomment-242510345), hoping to be able to run Atom within the context of WSL and take advantage of the upcoming inotify patch, but no dice. Word on the street is that SublimeText is working, so I was feeling hopeful. Launching the Windows version of Atom from WSL is nice and all, but won't help work around this particular issue.

:+1: **Another vote for Atom on WSL!** :beers:

**Comment by mmshah2004** [comment]
I had the same problem. Did you find any way to fix it?

**Comment by damieng** [comment]
What benefit are you expecting running the Linux version of Atom on Windows when a native version already exists?

**Comment by mmshah2004** [comment]
I need the Ruby toolkit. Not all of it has native support.

**Comment by Sureiya** [comment]
> What benefit are you expecting running the Linux version of Atom on Windows when a native version already exists?

In my case at least, this is the entire point of WSL.

For a full stack web dev workflow running atom on windows isn't very useful, since I have no access to the environment and therefore none of the plugins work.

The ability to access this environment easily and natively is what makes this useful.

When using atom on windows, most of what I use just won't work, or requires vastly different configuration. Atom on windows also doesn't play well with WSL at all, and seems to cause filesystem corruption if you try to operate on any files or directories atom has open. Even if I could get the plugins I need running under windows, actually working on the code in windows would require a vastly different configuration than our staging or production environment. It's a constant fight against odd windows only behaviour. Obviously using WSL isn't going to negate that, but it's a start, and the difference between needing to use virtualbox or have a battery draining linux installation.

Unless you know of a way to give windows atom proper access to the WSL filesystem and installed programs. As it is, I don't think the windows version of atom knows how to communicate with the WSL at all.

I think figuring out why this is crashing on WSL might be easier than getting the windows build of atom WSL compatible.

As a starting point, I do know the WSL implementation of domain sockets is incomplete.
https://github.com/Microsoft/BashOnWindows/issues/376

**Comment by damieng** [comment]
>I think figuring out why this is crashing on WSL might be easier than getting the windows build of atom WSL compatible.

Atom is comprised of its own code and plugins, Node, Electron and Chromium.  The chance of all these components working well in WSL is slim. I'm quite confident that once this crash is solved there will be another, and another... 

Unfortunately we don't have the resources to to support what is effectively another platform at this time.

**Comment by mmshah2004** [comment]
I changed my OS to an Arch Linux install and it worked thanks for the help

**Comment by uuf6429** [comment]
My use-case: I'd like to test Electron on a Linux-ish system (my main desktop is Windows) without a VM or external CI SaS (mainly for rapid development). Not an essential feature, but a nice to have.

**Comment by sebdelvalle** [comment]
It's been a Long road from the day this post was opened, and WSL is now final and supports opening windows apps. Is there any ETA to have "atom <file>" command working on WSL?

**Comment by damieng** [comment]
The situation has not changed. We have a fully-featured Windows native version of Atom that works great but do not have the resources to create a WSL-compatible Linux-derived version.

**Comment by damieng** [comment]
It is also worth noting that;

1. Microsoft do not support GUI apps on WSL  (some may work but no guarantees, lots of issues, could get worse)
2. Chromium has a whole bunch of issues on WSL and therefore Electron
3. Atom is built on Electron

Right now with newer WSL builds you can launch the Windows version using `atom.exe somePath` - I will look into seeing if we can make the existing Windows atom.sh bash script we use for cygwin/msys/msys2 also work nicely to remove the '.exe' part but that will likely be the most WSL integration you can expect to see here.

**Comment by mmshah2004** [comment]
There is a way to get it working, I accomplished it after over 100 hours. 2
days later I switched to Linux cause Windows has too many privacy problems.

**Comment by niceKamrul** [comment]
It is strange that command for VSCode works just fine.

`code .`

Just works.

**Comment by damieng** [comment]
@niceKamrul they are almost certainly running the Windows version of code from the WSL.

Atom does that too as long as it is in your path.

**Comment by niceKamrul** [comment]
![hlp](https://user-images.githubusercontent.com/10681837/36556476-7b27c390-182f-11e8-904b-0f28f36f1c3f.png)

I think my paths are ok. Again, from gitbash those command works. idk :/

**Comment by damieng** [comment]
That's definitely not where we install atom, we put it in;

`%localappdata%\atom x64\app-1.24.0\` (where 1.24.0 is version number you have installed) with the atom.sh and atom.cmd files in a bin folder below that.

Can you see what your Atom path is in Windows?  I wonder if the spaces are causing problems with WSL.

**Comment by niceKamrul** [comment]
Sorry there is no such file called `atom x64`. It is only atom. I have changed the env var though. It is now `%localappdata%\atom\app-1.24.0\`

Now it says, 
`/mnt/c/Users/Kamrul/AppData/Local/atom/app-1.24.0/atom: line 1: !/bin/sh: No such file or directory`  
`/mnt/c/Users/Kamrul/AppData/Local/atom/app-1.24.0/atom: line 1: $'\r': command not found`

**Comment by niceKamrul** [comment]
Well, I have changed the app-1.24.0/atom from

`!/bin/sh "C:/Users/Kamrul/AppData/Local/atom/atom.exe" $1 &`

to

``` 
#!/bin/bash
"$(dirname "$0")/../app-1.24.0/atom.exe" $1 &
```

Now, it's working!

**Comment by damieng** [comment]
Yeah, it will say 'atom' instead of 'atom x64' if you have the 32-bit version installed.

I'm wondering how that file ended up like that. Mine is;

```shell
#!/bin/sh
"$(dirname "$0")/../app-dev/resources/cli/atom.sh" "$@"
```

**Comment by niceKamrul** [comment]
I've downloaded today from [atom.io](atom.io)

It is definitely x64. Maybe something is wrong with this - idk :/ 

![tdy](https://user-images.githubusercontent.com/10681837/36563267-c89b0592-1843-11e8-8c0c-858563d8383a.png)
