### ISSUE TITLE
Ignore next update

### ISSUE THREAD

**Issue by manulaiko** [atom/atom#12524]
Each time there's a new version available for Atom, a popup shows when you start the editor and offers two options:
- `Cancel`, closes the popup until you reopen the editor.
- `Go to the download page`, starts a browser with the releases section of the github repository.

With this enhancement a third button would be shown for ignoring the update, meaning that if you reopen the editor the message for the update will not appear until there's a new update.

Simple and effective if you don't need to have the latest version with bug fixes that aren't targeted to your operative system or new features that you won't need.

**Comment by andyrichardson** [comment]
Interesting idea although I think the devs at Atom would prefer people using the latest builds.

**Comment by MatteoRagni** [comment]
On linux it is upgraded with the repo. Personally I will find it annoying.

**Comment by pcnate** [comment]
It could be useful if we discover a version unstable or unusable on the current OS so we downgrade to the previous. Then you could ignore the "bad" version and get the one following that. Unfortunately, I think this would require additional UI elements to allow the functionality as well as storing these prefs. Any possibility a package would be able to hook into the update process and block by version number? This of coarse would be available only on OS's that have auto updates enabled.

**Comment by andyrichardson** [comment]
> It could be useful if we discover a version unstable or unusable on the current OS

Stable releases should be exactly that - stable.

@manulaiko #7339 mentions how to disable automatic updates. With this, you can then install updates when and if you find necessary.
