### ISSUE TITLE
Keyboard shortcut ctrl-shift-P not working

### ISSUE THREAD

**Issue by maxferrario-msf** [atom/atom#12527]
### Prerequisites
- [Y] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [Y] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [Y ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [Y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Keyboard shortcut ctrl-shift-P is not working
### Steps to Reproduce
1. Press ctrl-shift-P

**Expected behavior:** [What you expected to happen]

Pressing ctrl-shift-P should toggle the command palette

**Actual behavior:** [What actually happened]

Pressing ctrl-shift-P doesn't toggle the command palette
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Atom version:**
Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Apm version:**
apm  1.10.0
npm  2.13.3
node 0.10.40
python
git 2.5.3.windows.1
visual studio 2010

**OS and version:**
Windows 7

**Installed packages**

> apm list --installed
> Community Packages (0) C:\Users\m.ferrario.atom\packages
> └── (empty)

└── (empty)

**Comment by d-mg** [comment]
Try to check the keybinding resolver with Ctrl-. _(that's Ctrl and a dot, to be clear)_ so you can see what happens when entering Ctrl-Shift-P. Maybe adding a screenshot of it here?

**Comment by maxferrario-msf** [comment]
Hi d-mg,
what I see whan I open the keybinding resolver and press Ctrl-Shift-P:
![ctrl-shift-p](https://cloud.githubusercontent.com/assets/15982392/18045169/c6810784-6dd1-11e6-9be8-0eaef3122965.png)
It looks like ctrl and shift keys are "sensed", but not p ...

**Comment by rdlugosz** [comment]
FWIW, I just had this same problem on OS X and it turns out another app I had been running was globally swallowing the cmd-shift-p keystroke. I saw the same behavior in the key binding resolver, too... hope that helps!

**Comment by damieng** [comment]
Yeah this is most likely going to be another app taking the shortcut. Not sure which it would be but 1Password4 does this on Windows by taking ctrl-shift-\ which we normally use to toggle the tree-view.

**Comment by ljc101** [comment]
Thanks rdlugosz :) - You just saved me from walking out of the office for the afternoon!

**Comment by natterstefan** [comment]
@ljc101 How did you find out which app "blocked" the Shortcut or adjusted/modified it?

**Comment by ljc101** [comment]
An App called Viola - Used for screen casts. Now Called Capto - http://www.globaldelight.com/capto/ 
I'm not sure if the newer version / name does the same thing.

**Comment by neslob** [comment]
thanks ljc101

You gave me a hint. I disabled the hot key in Capto's preferences and Atom works fine, again.
![capto__prefs](https://user-images.githubusercontent.com/168862/35648313-9feb5400-06d5-11e8-8e08-f5e84ae8fe32.png)
