### ISSUE TITLE
[1.9.9] Cannot resize splitted windows with linux

### ISSUE THREAD

**Issue by NicoHood** [atom/atom#12534]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

On Linux you cannot resize the splitted window size.

### Steps to Reproduce

1. Open Atom
2. Open two files
3. Drag one file to the right
4. Try to resize the splitted windows and make the right smaller/larger
5. You do not see any "resize curser".

### Versions
Atom    : 1.9.9
Electron: 1.3.4
Chrome  : 52.0.2743.82
Node    : 6.3.0

Running archlinux:
atom 1.9.9-2
Linux arch 4.4.19-1-lts #1 SMP Sat Aug 20 21:58:36 CEST 2016 x86_64 GNU/Linux
xfce4

A side note: I can resize the directory panel on the left, so Its not a bug of my desktop environment. It happens vertically and horizontally. I've also tried this on windows lately and this works. This came with some version of 1.9.x, 1.8.x worked before.

-> https://github.com/atom/atom/pull/12300#issuecomment-242493527

**Comment by Ben3eeE** [comment]
Your Atom is packaged with an unsupported electron newer version. If your check out the electron upgrade PR you can get some clue on how to fix this.

**Comment by andyrichardson** [comment]
### Versions
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

I just tested this with my Fedora 24 installation and managed to resize the window with no issues.

**Comment by 50Wliu** [comment]
> Electron: 1.3.4

As @Ben3eeE said, that is an unsupported Electron version.  Please uninstall your version of Atom and reinstall from https://atom.io.

https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md

**Comment by tensor5** [comment]
The element `<atom-pane-resize-handle>` is misplaced by Chromium 52 (Electron 1.3) due to the change explained [here](https://developers.google.com/web/updates/2016/06/absolute-positioned-children). I fixed it with [this patch](https://github.com/tensor5/arch-atom/blob/master/atom/fix-pane-resize-handle.patch), but the fix is not compatible with Electron 0.37.
