### ISSUE TITLE
TokenizedBuffer's did-tokenize and did-invalidate-range don't fire on small buffer changes

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#12539]
It's more of a question than a bug report, so sorry in advance.

Looking at https://github.com/atom/atom/blob/master/src/tokenized-buffer.coffee (and also testing), it seems when buffer change is smaller than `chunkSize`, `did-tokenize` and `did-invalidate-range` are never fired.

I was wondering if it's a design decision, or a bug.

**Comment by Ben3eeE** [comment]
> It's more of a question than a bug report, so sorry in advance.

Questions are more suited for posting on discuss https://discuss.atom.io/ where you are likely to get an answer faster. This is because the Atom team is trying to manage to deluge of issues. http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html
