### ISSUE TITLE
Incorrect Python folding for indented block followed by triple quoted string

### ISSUE THREAD

**Issue by matthew-brett** [atom/atom#12533]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

With this Python file:

```
if True:
    pass

"""
Text
"""
```

folding the code gives this appearance:

![image](https://cloud.githubusercontent.com/assets/67612/18023323/dd296cf0-6bac-11e6-8e22-500c0cad7c1e.png)

If the first triple quote has text following on the same line, I get the correct folding:

```
if True:
    pass

""" t
Text
"""
```

![image](https://cloud.githubusercontent.com/assets/67612/18023354/415618b8-6bad-11e6-9e53-94e4018dfcf9.png)

I discovered this issue while executing code via Hydrogen - see https://github.com/nteract/hydrogen/issues/418

### Steps to Reproduce

1. Any Python file with block containing indentation followed by a bare triple quote on a line, at the same indentation level as the first statement of the block.
2. Fold the indented block.

**Expected behavior:**

The block containing indentation should fold, but not include the triple quotes.

**Actual behavior:**

The block folds along with the initial triple quotes.

### Versions

```
$ atom --version
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.11
git 2.7.4
```

**Comment by lgeiger** [comment]
I can confirm this happens on Atom `1.10.0` and `1.12.0-dev` as well.

**Comment by lgeiger** [comment]
I opened a [PR on the language-python](https://github.com/atom/language-python/pull/155) package to fix this.
