### ISSUE TITLE
Chrashed when i unknowingly opened a ".7z" file

### ISSUE THREAD

**Issue by Deephakkrishna** [atom/atom#12558]
### Prerequisites

* [Not Tried ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ Yes] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?Yes
* [No ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [No ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [Yes ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Yes ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Atom crashed when i unknowingly opened a "*.7z" file ]

### Steps to Reproduce

1. [Open Atom]
2. [Open the folder containing "*.7z" file]
3. [Click on the  "*.7z" file from left side navigation bar]

**Expected behavior:** [Should open the file or Should throw an alert message]

**Actual behavior:** [I get a pop up window stating "
Atom
The editor has crashed
Please report this issue to https://github.com/atom/atom

[Close Window] [Reload] [Keep It Open]"]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by marcoshtm** [comment]
I couldn't reproduce the problem.

What I did:
1) Created a 'test.txt' file.
2) Typed "test" as the text content in 'test.txt', and saved it.
3) Compressed in a test.7z file using 7zip.
4) Opened the file folder in Atom, and then clicked in the file on the left pane.

Result: Atom opened the file and displayed the content. Since it's a binary file, what I see are some unreadable characters. It's the expected behaviour.

My environment:
- Atom 1.10.0
- 7zip 16.02 [64bits]
- Windows 10

Can you upload the file that triggered the problem? I believe it's a more specific issue.

.

**Comment by Zireael07** [comment]
How big is the .7z file?

**Comment by Deephakkrishna** [comment]
I cannot upload it because, it is a project file of mine containing HTML, CSS and JS files . 
It is 19.8mb is size .

**Comment by Deephakkrishna** [comment]
It is a project file of mine with HTML, CSS, JS, image files in that .7z .
Sorry, i wont be able to share that file . The file is of 19.8mb in size .

**Comment by Zireael07** [comment]
The problem isn't the format, it's the size.
Probably #8864?

**Comment by Deephakkrishna** [comment]
Oh . Okay . Thanks 👍
