### ISSUE TITLE
Unabled to remove some records from Search results and use replace all 

### ISSUE THREAD

**Issue by seajean** [atom/atom#12561]
### Description

[Description of the bug or feature]
if I used search in dir menu and replace the results with with other words,
but not all, and I try to right click to find context menu like remove record from the results, 

### Steps to Reproduce

1. [First Step] click search in the directory
2. [Second Step] type keywords and hit find
3. [and so on...]  replace some records with replace all button.

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/find-and-replace](https://github.com/atom/find-and-replace) repository if an issue does not already exist.

In the future, please **completely** fill out the provided issue template.
