### ISSUE TITLE
Indention glitch

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [atom/atom#12568]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

So when you are formatting text or pasting formatted text, atom seems to have its own way of indenting. Sometimes when coding HTML and php it indents in ways it not supposed to. 
Example: 
```html
<html>
    <head>
        <title>My glitchy workspace</title>
    </head>
        <body>
            <h1> Hi</h1>
        </body
</html>
```
You can see how it thinks `<body>` is a child of `<head>`
### Steps to Reproduce

1. Code. Try and let atom do the indention

**Expected behavior:** For code to be formatted
**Actual behavior:** Code indents wrong

### Versions
All

**Comment by 50Wliu** [comment]
Cannot reproduce using Atom 1.11.0-dev-5c3c546.  Both the `editor:auto-indent` command and auto-indentation work correctly.
