### ISSUE TITLE
Type assit in commentes

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [atom/atom#12567]
### Prerequisites

* [✓] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [✓] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [✓] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [✓] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [✓] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [✓] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

While typing [this ](http://hastebin.com/ejijaverow.md) comment,
I had a lot of trouble. When i would type words 
like server and code then hit enter to start a new
line, it would put a code piece. So if i typed server
then hit enter to start a new line it would set server 
to SoapServer.

### Steps to Reproduce

1. Type a comment. Words like server and code trigger it

**Expected behavior:** Not auto type code pieces when i am commenting

**Actual behavior:** It tries to auto type code when im writing comments. This becomes annoying when you work as a team and you are commenting code for others.

### Versions
All

**Comment by 50Wliu** [comment]
You can disable this behavior by adding `.comment` to the Scope Blacklist setting in autocomplete-plus.
