### ISSUE TITLE
Wrong package name for beta .deb distribution

### ISSUE THREAD

**Issue by laubstein** [atom/atom#12579]
I have a script that perform the automatic update from both versions (release and beta). Yesterday they got crazy.

The problem is that the last beta release (1.11.0-beta0) commes with `Package: atom` in deb control file.

Previous beta (1.10.0-beta7 - 21f835142289c52a09e8322bdff4948917776065) deb control file:
```
Package: atom-beta
Version: 1.10.0-beta7
...
```

Current beta (1.11.0-beta0 - 538aa945a2fe680ebd39d4789d725421e6158453) deb control file:
```
Package: atom
Version: 1.11.0-beta0-538aa94
...
```

**Comment by laubstein** [comment]
Addendum: the "Release Notes" link are taking account the commit hash.(https://github.com/atom/atom/releases/tag/v1.11.0-beta0-538aa94)
![image](https://cloud.githubusercontent.com/assets/457100/18166430/89a42f88-7021-11e6-9a60-374c3d0903c8.png)

**Comment by 50Wliu** [comment]
This should be fixed now.

**Comment by laubstein** [comment]
:+1:
