### ISSUE TITLE
Atom does not load correctly with VirtualBox Guest Additions installed

### ISSUE THREAD

**Issue by RJ-Russell** [atom/atom#12574]
### Prerequisites

* [y] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [y] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [y] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description
Atom and VirtualBox Guest Additions are both installed in the /opt directory. If I remove guest additions, atom opens and loads just fine. However, if I install guest additions and then reboot, atom opens, but does not load/render correctly. It opens but only has a black/gray pixelated window and is unusable. As soon as I remove the guest additions directory, Atom opens and loads perfectly. I have tested this in safe mode as well.

Installing Atom from the Ubuntu repo (which installs version 1.0.11) works perfect with guest additions installed. In order to install the newest version of Atom, I have to remove the /opt directory to avoid the warnings that Atom couldn't install properly, then reinstall Atom, and then reinstall guest additions, in which case Atom no longer loads/renders correctly. I also tried to install Atom using the webupd8/atom ppa, and have the same issues. 

### Steps to Reproduce
1. Install Atom
2. Install Guest Additions
3. Reboot
4. Start Atom

### Versions
OS (Guest): Bodhi 3.2.1 (Ubuntu 14.04)
VirtualBox Guest Additions 5.1.4
Atom 1.9.9

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/12570
