### ISSUE TITLE
snippets not working for stylus files

### ISSUE THREAD

**Issue by peteringram0** [atom/atom#12588]
I have tried the following:

'.source.css, .source.sass, .source.styl, .source.stylus'

however snippets don't want to work for the format

**Comment by Ben3eeE** [comment]
Please fill out the provided issue template describing all the steps to reproduce the issue you are facing. If this is just a question about the general usage of snippets consider asking on discuss https://discuss.atom.io where you will get help faster or reading the flight manual http://flight-manual.atom.io/using-atom/sections/snippets/
