### ISSUE TITLE
Data loss on save over SSHFS. Also, NULLs appended.

### ISSUE THREAD

**Issue by bmhkim** [atom/atom#12582]
### Prerequisites
- [*] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [*] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [*] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [*] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [*] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [*] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

When I work on a project over a network share (SSHFS; I haven't tried other ways of doing network share mounts), saving files sometimes results in deletion of portions of the file I'm working on (deletions don't seem to care about position relative to newlines), and appends NULL characters to the end (before the trailing newline if there is one).
### Steps to Reproduce
1. Create an SSHFS mount to get at a project.
2. Start work on a project.
3. Make changes.
4. Save changes.

Note this probably happens with around 1/4-1/3 of my days when I start work.

**Expected behavior:**

Files should be saved reliably, without random deletions, and without random insertions of NULL characters.

**Actual behavior:**

See description
### Versions

$ atom --version
Atom : 1.10.0
Electron: 0.37.8
Chrome : 49.0.2623.75
Node : 5.10.0

I'm on OS X 10.11.6.

**Comment by andyrichardson** [comment]
SSHFS on Atom has been an issue for me for over a year and while I never experienced insertions of NULL characters, performance was negligible and often crashed when on unstable wifi connections.

If you can avoid SSHFS while using Atom I would strongly advise doing so as [it seems to be a persistent issue](https://github.com/atom/atom/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20sshfs). If your changes need to be run in server environment, I'd advise you try mounting your working directory inside a Docker container.

**Comment by bmhkim** [comment]
I neglected to include version information.

$ atom --version
Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

I'm on OS X 10.11.6.
