### ISSUE TITLE
Help > Documentation takes you to https://flight-manual.atom.io/, which returns a "Privacy error"

### ISSUE THREAD

**Issue by wluu** [atom/atom#12583]
### Description

Help > Documentation takes you to https://flight-manual.atom.io/, which returns a "Privacy error".

### Steps to Reproduce

1. In the menu bar, go to Help
2. Click on Documentation

**Expected behavior:** https://flight-manual.atom.io/ should open in your browser without any issues.

**Actual behavior:** "Privacy error", specifically **NET::ERR_CERT_COMMON_NAME_INVALID**, is returned.

![screen shot 2016-09-01 at 10 49 27 am](https://cloud.githubusercontent.com/assets/1141338/18178295/a1923002-7032-11e6-93e6-7a9b191e4276.png)

### Versions

Atom: 1.10.0
OS: Mac OS 10.11.6, Windows 10
Browser: Chrome (Version 52.0.2743.116 (64-bit)), Safari (Version 9.1.2 (11601.7.7))

**Comment by aqchin** [comment]
The flight manual page does not have a security certification. You can still access the unsecure page by changing the https in the link to http or removing 'https://' altogether. I put in a pull request to correct the link.
