### ISSUE TITLE
Atom IDE crashed when I try to open beats repository

### ISSUE THREAD

**Issue by raghzz** [atom/atom#12594]
Atom IDE v1.10.0 crashes everytime I try to open https://github.com/elastic/beats. Other repositories seems to open without any issues.

**Comment by 50Wliu** [comment]
Please create a new issue and **completely** fill out the provided issue template so that we can better assist you.  Thanks.

**Comment by Equinox** [comment]
@raghzz I can reproduce the crash fwiw, so it's worth opening a new issue with the template, as it's not only you, etc. :)
