### ISSUE TITLE
.<tab> python snippet will autocomplete to "self." even if not preceded by whitespace

### ISSUE THREAD

**Issue by talkaminker** [atom/atom#12596]
### Description

the` .<TAB>` snippet that changes this to `self.` should only be triggered if it is after whitespace
 Meaning,
writing:
`blah.<TAB>`  will turn into  `blahself.` which is undesired
instead the `.<TAB>` autocomplete should only be applied if it is preceded by whitespace or if it in the beginning of sentence

### Versions

vanilla latest 1.10

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/language-python](https://github.com/atom/language-python) repo.

In the future, please **completely** fill out the provided issue template.
