### ISSUE TITLE
Command not found after upgrade to 1.10

### ISSUE THREAD

**Issue by stevenxiao** [atom/atom#12597]
After upgrade to version 1.10,  while click "Install" in setting page, it shows below error: 
/Applications/Atom.app/Contents/Resources/app/apm/bin/apm: line 8: dirname: command not found
/Applications/Atom.app/Contents/Resources/app/apm/bin/apm: line 9: basename: command not found

My OS is OS X EI 10.11.6

**Comment by 50Wliu** [comment]
Please create a new issue and **completely** fill out the provided issue template.
