### ISSUE TITLE
Install Package section (Press intro to search)

### ISSUE THREAD

**Issue by Akumetsu-Dev** [atom/atom#12592]
### Prerequisites

* [Yes ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ 1.10.0] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ No] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ No] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ Yes] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ Yes] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

In the install package Section, when i press intro for do the search do nothing, i have to click package button to do the search.

### Steps to Reproduce

1. Open Atom
2. Go to "Settings"
3. Click Install Section
4. Search a package in the search box.
5. Press intro.
6. Nothing happend.

**Expected behavior:** When i press intro, the search box  have to do  the search.

**Actual behavior:** Nothing.

### Versions

1.10.0

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/settings-view](https://github.com/atom/settings-view) repo.
