### ISSUE TITLE
Chrome interferes with atom 1.10.0

### ISSUE THREAD

**Issue by anothergituser** [atom/atom#12599]
My os is fedora linux
I use chrome 50.0.2661.94 and atom 1.10.0
Sometimes atom's interface is behaving weird, i click the tabs and nothing changes, also i can't edit text until i close chrome. Are they sharing something?
Also i don't remember having these issues with say 1.6 or 1.7

**Comment by andyrichardson** [comment]
Fedora 24 here with no issues. 

I think Chrome and Atom interact in some way or another. Have you tried disabling Chrome extensions?

**System**
Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by 50Wliu** [comment]
@anothergituser Please open a new issue and **completely** fill out the provided issue template so that we can assist you better.  Thanks.
