### ISSUE TITLE
Incosistent Markdown styling in Atom 1.10.0

### ISSUE THREAD

**Issue by gitkrax** [atom/atom#12609]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom 1.10.0 inconsistently styles Markdown text. I noticed this behavior after upgrading to Atom 1.10.0. The problem is consistent between different themes, so it sounds like a problem in Atom and not in a specific theme.

### Steps to Reproduce

I am unable to consistently reproduce the behavior. I have a longer Markdown-document where the styling is consistently broken, but the manner in which it is broken varies when I open a new instance of Atom. I could not reproduce the behavior with a shorter Markdown document, so I am not sure what the trigger is.

**Expected behavior:** Markdown to be styled consistently.

**Actual behavior:** The broken styling looks like this:

![sieppaa](https://cloud.githubusercontent.com/assets/5079912/18264874/63af4a6c-741b-11e6-980f-ea8a2918d13f.PNG)

### Versions

`atom --version`:

Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

`apm --version`:

apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 1.7.11.msysgit.1
visual studio

OS:

Windows 7 Service Pack 1

**Comment by thomasjo** [comment]
Please re-open this on the [language-gfm repo](https://github.com/atom/language-gfm).

When you re-open the issue there, please provide a screenshot that shows this reproduced in safe mode (it should include the little green icon in the status bar). Also, if you can provide a reference to an example file that consistently reproduces the problem. If we're not able to reproduce the problem, we will not be able to track down and fix any potential bugs.

Thanks! 🙇
