### ISSUE TITLE
Special "light" mode for fast git start

### ISSUE THREAD

**Issue by rugk** [atom/atom#12607]
I would really like to use Atom for editing commit messages of git, however I have one big problem: With a lot of packages installed Atom is just _veery_ slow.

This is why I'd propose to add a special `git-start` mode of Atom. This is how it should work:
When Atom is already started it should just work as usual, opening a new tab and let the user type in the commit message.
However when Atom is not already started it should just load a "light" version of Atom, where it does only load Atom (& most core packages) and `language-git` (and possibly some packages the user can configure manually), but not anything else. The reason is simple: In 80% of these situation the user will close Atom anyway directly after finishing writing the commit message, so there is not need to load packages for Python, PHP or so...

Of course it would be awesome if a user could load the missing packages afterwards when they finished writing the commit message, so that they can even go on using Atom without having to restart it.

**Comment by thomasjo** [comment]
I don't see this happening anytime soon; this is a non-trivial enhancement that will likely be unused by most users, and is guaranteed to be a victim of Scope Creep™.

Why don't you simply setup your Git editor to be `atom --safe`? Doesn't get much more lightweight than that.

**Comment by rugk** [comment]
> Why don't you simply setup your Git editor to be atom --safe?

This might be an option. I'll look into it.

However I think once you advertise this feature correctly it will be used by many people.

**Comment by damieng** [comment]
Suggestion by @thomasjo is a good one.
