### ISSUE TITLE
apm.cmd breaks on the second closing parenthesis in Windows PATH variable

### ISSUE THREAD

**Issue by sompylasar** [atom/atom#12608]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The error is described here:
http://stackoverflow.com/questions/39282229/cant-install-packages-in-atom-in-app-or-cmd
>I'm trying to install linter for atom, however both in the app and in cmd I get:
> 
> INFO: Could not find files for the given pattern(s).
> 
> `\Java\jre7\bin";C:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Brackets\command;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\GtkSharp\2.12\bin;" was unexpected at this time.`
>
> And I honestly don't know what that means, but I've tried searching for an answer and I can't find it. "atom -v" returns the version (1.10.0), "apm -v" returns the above, as well as any apm command. "where apm" returns
> 
> C:\Users\JM\AppData\Local\atom\bin\apm
> 
> C:\Users\JM\AppData\Local\atom\bin\apm.cmd

Though I am hitting this error in the Atom Packages search.

Looks like `atom.cmd` breaks on the second occurrence of the closing parenthesis: `"C:\Program Files (x86)\Java\jdk1.8.0_60\bin"` or on the first after `Git\cmd`, don't know for sure. I've checked by removing both parentheses and just the closing one, it did run without the error both times.

Somehow related to Java installation or update.

### Steps to Reproduce

Windows 7, Atom 1.10.0.

The full `Path` variable contents:
```
C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Git\cmd;C:\Users\user\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\user\AppData\Local\Programs\Python\Python35-32\;C:\Users\user\AppData\Roaming\npm;D:\_babak\_programs\apache-ant-1.9.6\bin;"C:\Program Files (x86)\Java\jdk1.8.0_60\bin";D:\_babak\_programs\code_swarm\bin;C:\Program Files\TortoiseHg\;C:\Users\user\AppData\Local\atom\bin;D:\_babak\_programs\watchman;%NVM_HOME%;%NVM_SYMLINK%;"C:\Program Files\Java\jre1.8.0_74\bin";"C:\Program Files\Java\jdk1.8.0_74\bin"
```

`where git` gives:
```
C:\Program Files (x86)\Git\cmd\git.exe
```

`apm.cmd` contents:
```
@echo off
setlocal enabledelayedexpansion

:: Try to find git.exe in path
for /f "tokens=*" %%G in ('where git') do set "apm_git_path=%%~dpG"
if not defined apm_git_path (
  :: Try to find git.exe in GitHub Desktop, oldest first so we end with newest
  for /f "tokens=*" %%d in ('dir /b /s /a:d /od "%LOCALAPPDATA%\GitHub\PortableGit*"') do (
    if exist %%d\cmd\git.exe set apm_git_path=%%d\cmd
  )
  :: Found one, add it to the path
  if defined apm_git_path set "Path=!apm_git_path!;%PATH%"
)

set maybe_node_gyp_path=%~dp0\..\node_modules\node-gyp\bin\node-gyp.js
if exist %maybe_node_gyp_path% (
  set npm_config_node_gyp=%maybe_node_gyp_path%
)

if exist "%~dp0\node.exe" (
  "%~dp0\node.exe" "%~dp0/../lib/cli.js" %*
) else (
  node.exe "%~dp0/../lib/cli.js" %*
)
```

**Expected behavior:**

The Atom Package search works without errors.

**Actual behavior:**

`Searching for "..." failed.`

### Versions

`atom --version`

```
Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

`apm --version`

(an error about the "unexpected" until I fix the Path variable by removing the closing parenthesis)

```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 3.5.0
git 1.9.4.msysgit.1
visual studio
```

**Comment by sompylasar** [comment]
Looks related:
http://superuser.com/questions/119610/spaces-and-parenthesis-in-windows-path-variable-screws-up-batch-files

**Comment by sompylasar** [comment]
Looks like following [the advice on StackOverflow](http://superuser.com/a/119619/392704) and changing:
```
if defined apm_git_path set "Path=!apm_git_path!;%PATH%"
```
to 
```
if defined apm_git_path set "Path=!apm_git_path!;!PATH!"
```
fixes this issue. But I'm not sure if the `Path` variable is set to a proper value, so would be better if some of Atom developers tested this.

**Comment by damieng** [comment]
Really those paths should be quoted in the environment variable but it looks like a bunch of apps don't do the right thing. I'll see if I can make this a bit more bullet proof.

**Comment by sompylasar** [comment]
@damieng They **are** quoted, but the cmd script ignores that. See the aforementioned StackOverflow question.

**Comment by damieng** [comment]
I don't see the same error when I try and repo it here despite my PATH also containing some entries with parentheses.

Can you change the first line of this file on your system to be REM @echo off so we can see exactly which line is generating the `Searching for "..." failed.` message?

**Comment by sompylasar** [comment]
> Can you change the first line of this file on your system to be REM @echo off so we can see exactly which line is generating the Searching for "..." failed. message?

No need to change anything, it's this line:
https://github.com/atom/settings-view/blob/06a022c84f870ae685b6ce594829a5af491414f3/lib/package-manager.coffee#L229

I realized that the issue is not just with the parentheses, but with the double quotes, too.

I guess the `%PATH%` expansion results in the following, note the quotes (syntax-highlighted), the parenthesis gets out of the quotes and closes the `if` block opening paren, so the rest of the expanded `%PATH%` is interpreted as a piece of code:
```bash
if not defined apm_git_path (
  if defined apm_git_path set "Path=!apm_git_path!;C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Git\cmd;C:\Users\user\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\user\AppData\Local\Programs\Python\Python35-32\;C:\Users\user\AppData\Roaming\npm;D:\_babak\_programs\apache-ant-1.9.6\bin;"C:\Program Files (x86)\Java\jdk1.8.0_60\bin";D:\_babak\_programs\code_swarm\bin;C:\Program Files\TortoiseHg\;C:\Users\user\AppData\Local\atom\bin;D:\_babak\_programs\watchman;%NVM_HOME%;%NVM_SYMLINK%;"C:\Program Files\Java\jre1.8.0_74\bin";"C:\Program Files\Java\jdk1.8.0_74\bin""
)
```

Below I've added line breaks in the points of interest:
```bash
if not defined apm_git_path (
  if defined apm_git_path set "Path=!apm_git_path!;C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Git\cmd;C:\Users\user\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\user\AppData\Local\Programs\Python\Python35-32\;C:\Users\user\AppData\Roaming\npm;D:\_babak\_programs\apache-ant-1.9.6\bin;"
C:\Program Files (x86
)\Java\jdk1.8.0_60\bin";D:\_babak\_programs\code_swarm\bin;C:\Program Files\TortoiseHg\;C:\Users\user\AppData\Local\atom\bin;D:\_babak\_programs\watchman;%NVM_HOME%;%NVM_SYMLINK%;"C:\Program Files\Java\jre1.8.0_74\bin";"C:\Program Files\Java\jdk1.8.0_74\bin""
)
```

**Comment by damieng** [comment]
Ah, it's the combination of quotes containing a parenthesis. I see.  Can now repro.

**Comment by damieng** [comment]
The apm.cmd actually comes from the atom/apm repo so it's been fixed there https://github.com/atom/apm/commit/fa84f2693b22630e5125dcea10004300d00cdd75

Thanks for reporting and the detailed information!

**Comment by sompylasar** [comment]
@damieng When approximately could this be expected to be published?

**Comment by lee-dohm** [comment]
@sompylasar We haven't slated this for a specific release at this point. We don't have an ETA for when it will be published currently.
