### ISSUE TITLE
Add an option to disable smooth scrolling

### ISSUE THREAD

**Issue by esemeniuc** [atom/atom#12603]
I was using Atom 1.8.8 previously which did not include smooth scrolling. Today I updated to 1.10 which has smooth scrolling enabled by default, but I cannot figure out how to turn it off. There do not seem to any plugins or tutorials on how to disable it either. In Chrome, the user can open chrome://flags and manually disable it, but I could not figure out how. [This post](https://discuss.atom.io/t/how-to-access-chrome-flags-in-electron/16470/6) gives me a few hints, but not much else unfortunately.

**Comment by neonn** [comment]
Ideally, I think that the smooth-scrolling toggle should be under either `Core`, or in the `Editor` menu. And @cwaffles is right, unless Atom itself is modified, there are no flags to disable/enable smooth scrolling.

**Comment by leitec** [comment]
At least on Linux I was able to disable it by passing Atom the same command-line parameter as Chrome: `--disable-smooth-scrolling`. It makes a significant difference when working over VNC or similar systems.

**Comment by neonn** [comment]
That is exactly what I needed! I wish they would add it as a flag in `Settings` though, much like Chrome, or even as a config option. Awesome work though @leitec !

**Comment by chpio** [comment]
+1 please fix this, it's a show stopper for me.

**Comment by manuelbieh** [comment]
This option is so highly desirable!

**Comment by manuelbieh** [comment]
Looks like the `--disable-smooth-scrolling` option does no longer work when starting it with:
`%USERPROFILE%\AppData\Local\atom\atom.exe --disable-smooth-scrolling` 
instead of (before):
`%USERPROFILE%\AppData\Local\atom\Update.exe --disable-smooth-scrolling --processStart atom.exe --process-start-args "--disable-smooth-scrolling"`

at least not for the file tree and the settings view.

**Comment by ventr1x** [comment]
smooth scrolling not being able to deactivate made me instantly facepalm and deinstall again.
Why is this a thing? 
When does a programmer need such animations, delayed scrollings, spell checking in source codes, link highlights in source codes and all that total bs?
I'm fine with it being an option, but these things being default and not optional at all...

**Comment by chpio** [comment]
spell checking & link highlighting is pretty neat for markdown files.

**Comment by ventr1x** [comment]
Sadly there are tons of editors you get used to over the years that suddenly introduce such features as default for every file type without asking, wasting time and nerves until (if) you find the setting for it (looking at you notepad++)

**Comment by Mayurifag** [comment]
+1, we actually need that option in settings.

**Comment by 0tt** [comment]
Come on guys. I use a trackpad, and the only thing smooth scrolling does for me is add a horrible 1 second delay.

**Comment by NeoGriever** [comment]
"temp" fix for this "problem":

Put this in your css:

atom-text-editor.editor > div > .scroll-view > div,
atom-text-editor.editor > div > .gutter-container > div {
    transition: -webkit-transform 0s linear;
}

This disabled smooth-scroll-effect at win7 64bit :D hope, it helps.

(Based on example from here: https://github.com/atom/atom/issues/10276#issuecomment-323538272)

**Comment by Asday** [comment]
Any word on this?  Atom 1.22.0 on Mint 18, the editor doesn't smoothscroll, but settings and the treeview (!) do.

I would very much like it gone.

**Comment by louis925** [comment]
Any update on this issue? The scroll in Atom still behave differently from any other apps on both Mac and Windows. I can see a delay even when using the touchpad to scroll on Mac.

**Comment by Zylann** [comment]
Atom 1.33.1 on Windows 7 64 bits, the settings view has smooth scrolling but text editors don't, and I see no option to toggle this on or off... (I'd like to be able to enable it for text editors, though)

**Comment by tarkh** [comment]
> Atom 1.33.1 on Windows 7 64 bits, the settings view has smooth scrolling but text editors don't, and I see no option to toggle this on or off... (I'd like to be able to enable it for text editors, though).
> 
> I tried the [stylesheet addition](https://github.com/atom/atom/issues/10276#issuecomment-323538272) but it causes text loading to lag when scrolling because Atom does not take the actual scroll offset into account: ![image](https://user-images.githubusercontent.com/1311555/50482415-ac56ab80-09e6-11e9-9d68-66abba33d4cc.png)
> 
> Ah, I noticed it also breaks subpixel antialiasing for some reason.

Same issue here, Arch Linux on Xorg. Did you find any solution?
