### ISSUE TITLE
Atom cannot input Chinese in Ubuntu64 16.04

### ISSUE THREAD

**Issue by ScarletCirno** [atom/atom#12617]
**Environment:**
Ubuntu64 16.04
My language setting:
![image](https://cloud.githubusercontent.com/assets/15227557/18303300/0f6b041a-750f-11e6-85b1-5806f6f3f802.png)
My input setting :
![image](https://cloud.githubusercontent.com/assets/15227557/18303778/5deb24ec-7511-11e6-8903-cb503900b17e.png)

& perference:
![image](https://cloud.githubusercontent.com/assets/15227557/18303342/4bb66d24-750f-11e6-8ba2-488120ff902f.png)
atom source ver: 1.12.0-dev-44c0fe5

**Description:**
![image](https://cloud.githubusercontent.com/assets/15227557/18303690/efc303ae-7510-11e6-86f3-560a43e8c8fd.png)
I can input Chinese in other application, 
but atom can not.Although the Chinese can show.
When i wanna input some word(Chinese)
It is always the letter, rather than the Chinese candidate word!
I have tried to modify **font family** , but it doesn't work.
My English is poor..
Please, help me

**Comment by li-xinyang** [comment]
![screenshot from 2016-09-16 13-00-27](https://cloud.githubusercontent.com/assets/3349406/18575739/9b70e8d0-7c0d-11e6-9930-76c9f01c175c.png)

I do not have the issue to input Chinese character in Atom 1.9.8.
