### ISSUE TITLE
Scrolling Problem in Windows

### ISSUE THREAD

**Issue by hpt8592pro** [atom/atom#12618]
I love this editor. But scrolling issue is headache to me.
Can anyone solve Scrolling Issue in Windows?

Thank you.

**Comment by Ben3eeE** [comment]
Please elaborate what scrolling issue you are experiencing by completely filling out the provided issue template.

**Comment by 50Wliu** [comment]
As @Ben3eeE mentioned, please open a new issue and completely fill out the issue template.
