### ISSUE TITLE
not all selected text is highlighted when editor is scrolled horizontally

### ISSUE THREAD

**Issue by UziTech** [atom/atom#12612]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

![highlight-issue](https://cloud.githubusercontent.com/assets/97994/18292174/74c4b360-7451-11e6-8ec2-da2701d2dedd.gif)
### Steps to Reproduce
1. scroll editor to the right
2. select multiple lines of text
3. scroll editor to the left

**Expected behavior:** lines that are fully selected should be fully highlighted

**Actual behavior:** highlighting stops at left of editor when scrolled
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
atom --version
Atom    : 1.10.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.8.3.windows.1
visual studio 2015
```

**Comment by Ben3eeE** [comment]
I was able to reproduce this in Windows 7 Atom 1.10.1.
If you copy the selected text everything will get copied so it is just the highlighting that is wrong.

**Comment by vedharish** [comment]
I can reproduce this on Mac ElC. This happens only when we drag the horizontal scrollbar for scrolling. The wheel scroll events (when we scroll left/right using the trackpad) works just fine.

![ScreenCast](https://cloud.githubusercontent.com/assets/2497481/18375505/824009d4-7674-11e6-9d4c-1169ca928fb1.gif)
