### ISSUE TITLE
Git integration holds locks on pack files in .git directory

### ISSUE THREAD

**Issue by jholewinski** [atom/atom#12621]
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

When I open a project directory in Atom which is under git source control, the git integration in Atom holds file locks on various files in the .git directory of the project.  This breaks git commands that modify the pack files, like `git gc`. When running `git gc`, I see errors like the following:

```
Unlink of file '.git/objects/pack/pack-0cca48411464b8ef80a288f080d3d8eef5321ae3.pack' failed. Should I try again? (y/n)
```

Using [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/bb896653), I was able to track down the file lock to the atom.exe process.
### Steps to Reproduce
1. Open project directory in Atom that is under git source control
2. Perform enough commits to the git repo that a garbage collection will write new .pack and .idx files
3. Try running `git gc` with Atom open

OR
1. Open project directory in Atom that is under git source control
2. Observe atom.exe process holding open handles to .git files in Process Explorer

**Expected behavior:** Atom does not hold open handles on .git files

**Actual behavior:** Atom holds open handles on .git files
### Versions

```
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

OS is Win 10.0.10240

**Comment by MagicDuck** [comment]
Same problem here.... :(

**Comment by snwiem** [comment]
Same problem here:

`$ rm -rf sc-spo-service-datain-input-watcher/
rm: cannot remove 'sc-spo-service-datain-input-watcher/.git/objects/pack/pack-63d109eb1bca29a6ad8f2adaca6826d104606e9f.pack': Device or resource busy
`

**Comment by Standard8** [comment]
I frequently see this if I interact with Atom whilst also doing various commands like `git rebase` and `git commit --amend`. Rebase is the worst as it tends to mess up the rebase and I have to start again.

```
$ git rebase -i master
fatal: Unable to create '/Users/mark/dev/gecko/.git/index.lock': File exists.
```

Sometimes I have to quit Atom to avoid this getting in the way.
