### ISSUE TITLE
Spell check markers do not reposition when soft wrapped and closing a split pane

### ISSUE THREAD

**Issue by Ben3eeE** [atom/atom#12622]
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Closing a split pane when soft wrapped does not cause the spell check markers to get repositioned. Doing almost any action while in this state causes them to reposition correctly. Actions that cause them to reposition are: resize the Atom window, click in the `TextEditor`, scroll the `TextEditor`, switch to another tab and back, use the arrow keys to move the cursor.
I can reproduce this with all themes in safe mode on both Windows 10 and Windows 7.

Discovered and discussed over in https://github.com/atom/language-gfm/issues/167#issuecomment-244906162 where @nathansobo told me to open a new issue.
### Steps to Reproduce
1. Open Atom in safe mode.
2. Ensure you have `Soft Wrap` enabled.
3. Ensure you have `spell-check` enabled.
4. Copy [this file](https://gist.githubusercontent.com/Ben3eeE/6b9a8d5c3fbdd38bda3b70b63617b280/raw/77e0fc174f27160e82bd3c27f2d8182771770fb8/gistfile1.txt) into a new untitled `TextEditor` 
5. Split the pane right and resize the Atom window so there is soft wrapping.
6. Close the right pane that you just opened.

Gif of reproduction Windows 7 safe mode:
![split pane close](https://cloud.githubusercontent.com/assets/1058982/18268989/8712b448-7426-11e6-814c-adf8b998e353.gif)

Inspect markers in dev tools:
![markers in dev tools](https://cloud.githubusercontent.com/assets/1058982/18305056/0283dc00-74e6-11e6-82f9-70e28581873d.png)

**Expected behavior:** Spell check markers to be correctly positioned.

**Actual behavior:** Spell check markers are incorrectly positioned. Doing anything like moving the cursor, clicking in the pane causes them to reposition correctly.
###### atom --version

```
Atom    : 1.11.0-beta4
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```
###### apm --version

```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.8.1.windows.1
visual studio 2015
```
###### atom --version

```
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```
###### apm --version

```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.11
git 1.9.2.msysgit.0
visual studio
```

**Comment by 50Wliu** [comment]
Here's my gif from #12891:
![incorrect-selection-on-pane-resize](https://cloud.githubusercontent.com/assets/2766036/19156576/5ffa4bb8-8bb0-11e6-9dbc-1b7ab4ea60c6.gif)

**Comment by Ben3eeE** [comment]
Looks like this has since been fixed I can't reproduce
