### ISSUE TITLE
"Open with Atom" no longer appears

### ISSUE THREAD

**Issue by ErraticFox** [atom/atom#12620]
I manually uninstall Atom by accident (was trying to clear Atoms preferences). Once I did this, it did not uninstall the context menu item. I didn't think much of it as I thought it'd fix itself when I reinstalled Atom. Well, that didn't fix it, so I uninstalled properly (through Windows) and reinstalled. Still didn't fix it. I removed the context menu item via registry editor and reinstalled Atom and now it didn't even install the context menu. I've ran CClear after uninstalling aswell. On top of that, it's also broke the "Show in Explorer" feature in the tree-view. How can I get these functions back? I use them quite frequently.

**Comment by jerone** [comment]
There's now an extra settings tab in Atom specifically for the context-menu options:
![atom settings](https://cloud.githubusercontent.com/assets/55841/18313897/1a7c77f6-7511-11e6-8194-b4d9d2efda03.png)
