### ISSUE TITLE
Incorrect indentation when using multi-line snippets

### ISSUE THREAD

**Issue by ffxsam** [atom/atom#12627]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Snippet indentation is incorrect. I have the following snippet:

```
'.source.js':
  'React method':
    'prefix': 'rm',
    'body': """
    $1 = ($2) => {
      $3
    };
    """
```

I open a .js file and type "rm" then hit tab and fill it in.

**Expected behavior:** [What you expected to happen]

Expected result: (e.g.):

```js
  testMethod = () => {
    this.doSomething();
  };
```

**Actual behavior:** [What actually happened]

```js
  testMethod = () => {
     this.doSomething();
   };
```

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.9.3

Mac OS 10.11.6
```

**Comment by 50Wliu** [comment]
You already have an issue open for this at atom/snippets#213 - please don't create duplicate issues.

**Comment by ffxsam** [comment]
Ahhh, it was under a different repo - no wonder I couldn't find it here. Sorry about that.
