### ISSUE TITLE
File associations not working on Windows 10 rev. 1607

### ISSUE THREAD

**Issue by Marqin** [atom/atom#12628]
File associations from #10818 (fixing #4893) doesn't work on Windows 10 (rev. 1607).

Atom version is 1.10.2

### Steps to Reproduce

1. Have windows 10 rev. 1607 (**after anniversary update**)
2. Instal atom from atom's website (1.10.2)
3. Restart PC
4. Right click on any file (`.txt`, `.lua`, etc.) and "open with"
5. There is no Atom editor there 👎

**Comment by Marqin** [comment]
Also, there is no `HKEY_CURRENT_USER/SOFTWARE/Classes/Applications/atom.exe`. (desktop/start-menu shortcuts are ok).

**Comment by Marqin** [comment]
I've looked into [this](https://github.com/atom/atom/blob/master/src/main-process/win-shell.coffee) and registry keys there you register and I can say that there are no such path as:
```
\\Software\\Classes\\*\\shell\\
\\Software\\Classes\\Directory\\shell\\
\\Software\\Classes\\Directory\\background\\shell\\
```
(where * is any file extension).

But, there are two little different paths:
```
\\Software\\Classes\\Directory\\shellex\\
\\Software\\Classes\\Directory\\background\\shellex\\
```

**Comment by Ben3eeE** [comment]
Did you check the setting in the settings view system panel?
In the future please completely fill out the provided issue template.

**Comment by Marqin** [comment]
It's listed in Applications in system "applications & functions pane".

But, on "Default applications" no extension has Atom avaiable.

Which is consistent with what I wrote about registry keys.



2016-09-08 10:26 GMT+02:00 Ben3eeE <notifications@github.com>:

**Comment by 50Wliu** [comment]
What @Ben3eeE is trying to say is make sure the "Register as file handler" checkbox in Settings -> System are checked.

And yes, in the future please completely fill out the issue template or your issue runs the risk of being closed without triage.

**Comment by lemongrassnginger** [comment]
Adding a big obvious screenshot since I've spent the last half hour reading through issues trying to find the solution to this 🙃 The settings fix mentioned above worked for me 😊 

![image](https://user-images.githubusercontent.com/12435157/30495270-48e27962-9a43-11e7-9b3a-1753caab5c35.png)

**Comment by 50Wliu** [comment]
Thanks for the screenshot @lemongrassnginger :smile:.  I'm sure that will help a lot for anyone else who finds this issue!  Should have included one myself.
