### ISSUE TITLE
Open... or Open Project Folder does not start window when no atom window is present

### ISSUE THREAD

**Issue by Nokel81** [atom/atom#12633]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

In macOS you can have an application running without having any application window running. This is the case for Atom. However, if you do `File -> Open` or `File -> Open Project Folder` when Atom does not have a window open then no dialog window appears

### Steps to Reproduce

1. Launch Atom (on macOS)
2. Close window (so that the app is still running but has no windows open)
3. do the command `File -> Open`

**Expected behaviour:** A dialog window to appear to open a file which will also open a new window

**Actual behaviour:** Nothing

### Versions

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.7.4

**Comment by andersryanc** [comment]
+1

same thing is happening for me... and to add to this issue, I was just pressing the shortcut: `cmd+o`. I can see the file menu flash when I press the shortcut, but nothing happens.

Atom: 1.10.2 (was also happening before latest update 1.9.9? I forget the exact prev version)
OSX: 10.11.6

**Comment by andersryanc** [comment]
FYI - just found this duplicate issue: https://github.com/atom/atom/issues/12508

**Comment by 50Wliu** [comment]
Thanks @andersryanc!
