### ISSUE TITLE
Windows File Explorer context menu broken

### ISSUE THREAD

**Issue by blokeley** [atom/atom#12635]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? Not applicable
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? Not applicable
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?  It's not at all clear where the Windows context menu code would be.  Atom? Electron?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

The update to v1.10 seems to have broken the Atom action in the context menu in Windows Explorer. 

_This may be due to the Windows 10 Anniversary update which happened at the same time as the atom update._  However, uninstalling and reinstalling atom did not fix it so I suspect that the issue with with atom

### Steps to Reproduce

1. Install v1.10 or update to it
2. Open Windows Explorer
3. Right-click on a file

**Expected behavior:**

The context menu should have green Atom icon next to "Open with Atom"
Selecting "Open with Atom" should open the file in atom.

**Actual behavior:**

The context menu icon is a generic one, not atom's green icon.
Selecting "Open with Atom" opens a Windows dialog saying, "How do you want to open this file" with a list of potential programs, of which atom is somewhere down the list.

### Versions

atom 1.10.2
Windows 10 Anniversary update version 1607 build 14393.105

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by 50Wliu** [comment]
Go to Atom's Settings -> System and toggle the "Show in file context menus" option.
