### ISSUE TITLE
Setting the default syntax for new documents

### ISSUE THREAD

**Issue by ChrisChiera** [atom/atom#12639]
Each time I create a new document and paste in code (most typically HTML/CSS/PHP) it defaults to Plain Text. While of course you could save the document with a file extension and then will update the  syntax.

But for all the times where ones just pastes in the code to make a quick edit or check without the need or desire for saving the file, would be great to change the default file type.

There are several threads on here and the forum but they are in regards to changing the default file type for custom file extensions which isn't the issue I have. Does anyone know a config setting to adjust the default syntax for new documents (preferably without an extension if possible)?

**Comment by Ben3eeE** [comment]
https://discuss.atom.io/t/how-can-i-make-all-new-files-open-with-a-specific-grammar-or-syntax/20754

**Comment by thomasjo** [comment]
This is a perfect feature for a community package. Although since you don't seem to want to use a package, I propose you add something like this to your `~/.atom/init.coffee` file,

~~~ coffee
atom.workspace.observeTextEditors (editor) ->
  return if editor.getPath()?
  editor.setGrammar(atom.grammars.grammarForScopeName('source.cpp'))
~~~

**Comment by ChrisChiera** [comment]
As noted, I'm certainly fine using a community package if one exists, just that I would of course prefer being able to add a line or two, to my Atom Preferences than having to install a whole plugin if there is a Preference setting available instead. 

Opened ~/.atom/init.coffee pasted in your above code @thomasjo and saved that coffee file. Restarted atom. Then tried opening a new blank Atom file and it still defaults to Plain Text as noted in the bottom right of Atom rather than opening in whatever format "CPP" is. I also tried changing the code from "source.cpp" to "source.php" and saved and restarted, and when opening a new file is still does not default to PHP. 

I also tried the code provided by @Ben3eeE https://discuss.atom.io/t/how-can-i-make-all-new-files-open-with-a-specific-grammar-or-syntax/20754 which is similar but a little different than the other commenter. That also does not appear to work. Any thoughts on what either I'm doing wrong or what may be wrong with the code? It looks like this got abruptly closed before I was able to test the code so hopefully you will still be notified of this comment. Thank you!

**Comment by 50Wliu** [comment]
I cannot reproduce - the snippet that @thomasjo provided worked fine for me when opening a blank file using Ctrl+N.

**Comment by ChrisChiera** [comment]
Right this is in regards to only opening a blank file. Not opening a blank file than creating an additional new tab using Ctrl+N or File > New Tab where the functionality works. Choosing File > New Window also runs into the same issue.

Can you confirm that you are able to open atom from scratch (either from Dock, Alfred, Spotlight, etc, and the default window that appears opens in the new default syntax and not plain text? That is what this issue is about. Thanks!

**Comment by ChrisChiera** [comment]
Was confirmed that does appear to be an actual bug. Since this bug got closed opening again here and including additional information: https://github.com/atom/atom/issues/12732

**Comment by lee-dohm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [init.coffee running too late](https://trello.com/c/Ot2apUQO/71-init-coffee-running-too-late)
