### ISSUE TITLE
Sub-pixel rendering does not occur when unlocking Atom on Macbook external monitor

### ISSUE THREAD

**Issue by tyrsius** [atom/atom#12638]
### Description

When unlocking mac OS on a macbook when atom is on a second monitor, the color of syntax highlighting is muted. The color fixes when the pane is updated by changing tabs. The screenshot below shows the muted color on the left, and the correct color (by changing the tab) on the right.

This does not appear to happen when waking the computer if atom is on the laptop screen. Its hard to tell, but the color appears to be fine for a split second, and then muted once the window is force-resized. This may happen on a desktop, but I don't have one to test with.

![image](https://cloud.githubusercontent.com/assets/1187432/18359997/297866f2-75b1-11e6-898f-417644b42c35.png)
### Steps to Reproduce
1. Open Atom on a second, external monitor on a macbook
2. Allow Mac to lock from inactivity OR lock from the lock in the toolbar. The System "Sleep" command will not work.
3. Wake the mac, and unlock the screen

**Expected behavior:** Color should appear normally

**Actual behavior:** Color is <s>muted</s> not sub-pixel rendered. Thanks to @simurai  for noticing
### Versions

```
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by 50Wliu** [comment]
Does this occur in safe mode (`atom --safe`)?

**Comment by tyrsius** [comment]
Yes, it does

**Comment by simurai** [comment]
Based on the screenshot, it looks like the left side isn't **sub-pixel** rendered.

Left | Right
--- | ---
![screen shot 2016-09-09 at 8 55 55 am](https://cloud.githubusercontent.com/assets/378023/18370947/a703e190-766b-11e6-947f-38118d6c1271.png) | ![screen shot 2016-09-09 at 8 55 36 am](https://cloud.githubusercontent.com/assets/378023/18370948/ac9e9c58-766b-11e6-97d4-ce828b129e20.png)

/cc @as-cii

**Comment by tyrsius** [comment]
@simurai Wow, good catch. I never would have thought to check that =)

**Comment by tyrsius** [comment]
@50Wliu I have successfully reproduced this issue on 2 of my coworkers machines, if that helps.
