### ISSUE TITLE
Integrated terminal panel

### ISSUE THREAD

**Issue by lednhatkhanh** [atom/atom#12649]
The terminal-plus package doesn't work on Atom from 1.9 and this is a must-have package for me.
So I think it should be better if we can have a terminal built in instead of waiting for a package to be updated.

**Comment by lee-dohm** [comment]
We aren't going to be building a terminal emulator into Atom. We agree that it is something that is very useful for some workflows but it isn't something that we'll be investing our limited resources into building and maintaining. We would much rather concentrate on making a great editor and leave terminal emulators to others who have the interest and expertise for them.
