### ISSUE TITLE
crashReporter submitURL points to non-existant domain

### ISSUE THREAD

**Issue by alex** [atom/atom#12658]
Code is here: https://github.com/atom/atom/blob/master/src/crash-reporter-start.js#L6

```
~ $ host crashreport.atom.io
Host crashreport.atom.io not found: 3(NXDOMAIN)
```

I have no idea what the impact of this is, but I have to imagine it means that crash reporting doesn't work.

**Comment by damieng** [comment]
That is correct, crashreport.atom.io has never existed.  It's a placeholder for the future. 

Right now it has no effect as we configure the crash reporting service to not automatically submit.

Unfortunately the service requires a URL even if you don't submit or it fails to start (and if you don't start it you can't get local disk-only reports)
