### ISSUE TITLE
Does Atom have an opinion on the future of Coffeescript?

### ISSUE THREAD

**Issue by greghuc** [atom/atom#12656]
Hi guys,

A quick heads up that there's a pretty active discussion going on over at [coffeescript6/discuss](https://github.com/coffeescript6/discuss) about possible next steps for Coffeescript.

Thought you might want to comment, given Atom is a heavy Coffeescript user. Discussed issues are [here](https://github.com/coffeescript6/discuss/issues).

There's also a survey that's relevant to you: [Survey for devs/teams with maintained Coffescript codebases: happy with CS, or considering migrating?](https://github.com/coffeescript6/discuss/issues/32)

**Comment by 50Wliu** [comment]
I am not an official member of the Atom team.

However, the current strategy appears to be that when new files are checked into the codebase, those should be written in ES6.  No more Coffeescript files should be added.
Existing coffeescript files may be converted to ES6 when they undergo a major rewrite.

/cc @lee-dohm

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

**Comment by Alhadis** [comment]
Only suggestion I'll make is that you swap the freakin' `of` and `in` operators the other way around so devs won't keep confusing the two when flipping between CoffeeScript and ES6.

Ｐ Ｌ Ｅ Ａ Ｓ Ｅ

**Comment by Haggus** [comment]
@Alhadis You can use for...of in ES6: [for...of](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of)

**Comment by Alhadis** [comment]
@Haggus That's my point. `for...of` does something different in CoffeeScript, which is what `for...in` does in JavaScript. It drives me insane.

**Comment by lee-dohm** [comment]
What @50Wliu said was right on the nose. 👍
