### ISSUE TITLE
Complete loss of subpixel antialiasing

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#12652]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

After the Electron 1.3.5 upgrade, I've noticed a complete loss of subpixel antialiasing in Atom.  Code, tree-view, status-bar, you name it are all grayscale antialiased.  If there's any way I can help debug this please let me know because it's starting to hurt my eyes :(.
### Steps to Reproduce
1. `atom --safe`
2. Zoom in using Magnify

**Expected behavior:** Colorful subpixel antialiasing

**Actual behavior:** Grayscale :(
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.12.0-dev-4f1833a
Electron: 1.3.5
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.2.windows.1
visual studio 2015
```

Windows 10 x64.

**Comment by damieng** [comment]
Tested master on my system today with ClearType turned on...  I got ClearType on the editor and the menu drop-down and tooltips. But regular AA on tree-view, menu bar, tabs.

Are you running high DPI?  On my high DPI display (Surface Book) everything was regular AA not ClearType.

**Comment by 50Wliu** [comment]
Sorry, forgot to mention that.  Yes, I'm on a high-DPI display (150% scaling).
