### ISSUE TITLE
New feature or package google translate package possible?

### ISSUE THREAD

**Issue by designofhumanity** [atom/atom#12663]
Is it possible to make package for atom for translation like this
![atom-google-tranlate](https://cloud.githubusercontent.com/assets/2714036/18419913/a163c3b8-786e-11e6-96da-b6e94c351989.gif)

Something like this:
```
url = "https://translate.google.com/?en=en#en/ru/#{cased}"
        # Shell.openExternal url
      xmlHttp = new XMLHttpRequest()
      xmlHttp.open( "GET", url, false )
      xmlHttp.onreadystatechange = ->
          if this.readyState == 4
              parser = new DOMParser()
              doc = parser.parseFromString(xmlHttp.responseText, "text/html")
              resultbox = doc.getElementById("result_box")
              alert(resultbox.innerHTML)
      xmlHttp.send( null )
      console.log(xmlHttp.responseText)
```

**Comment by 50Wliu** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
