### ISSUE TITLE
atom helper crashed on exit

### ISSUE THREAD

**Issue by shoesforindustry** [atom/atom#12660]
Atom helper crashes on exit of Atom started from terminal in safe mode (also crashes if opened with icon). There are multiple Atom Helper processes started when I open the app this way?
Mac: OS X ElCapitain
10.11.6

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

[atom helper crash.crash.zip](https://github.com/atom/atom/files/465968/atom.helper.crash.crash.zip)

**Comment by VivaLosDoyers** [comment]
I have this problem too. FWIW it occurs on Sierra as well.

**Comment by gmdavenport** [comment]
Same here.  I had it in April. Deleted app, and reinstalled today.  Now I know why I deleted it.

**Comment by 50Wliu** [comment]
This crash should be fixed in Atom 1.11.0-beta or 1.12.0-dev - I'm not sure exactly which one.
