### ISSUE TITLE
"Reload Specs" button does nothing

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#12665]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

The interactive specs window does not close the first time you click the "x" button.  It only closes after the second time.

### Steps to Reproduce

1. `window:run-package-specs`
2. Hit the "Reload Specs" button
3. ...
4. Click it a few more times
5. ...

**Expected behavior:** Specs window to reload

**Actual behavior:** Specs window stares at you defiantly

### Versions

```
Atom    : 1.12.0-dev-5264fae
Electron: 1.3.5
Chrome  : 52.0.2743.82
Node    : 6.3.0
```
```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.2.windows.1
visual studio 2015
```

Windows 10 x64.

**Comment by thomasjo** [comment]
Looks like the [IPC call](https://github.com/atom/atom/blob/5264faedf03ebcd850ec84ea5cafe70904c28c3a/spec/atom-reporter.coffee#L176) either isn't being sent, or it's no longer being handled/targeted properly.
