### ISSUE TITLE
Cursor in unexpected position when moving it while selecting

### ISSUE THREAD

**Issue by Download** [atom/atom#12677]
Observed in Atom 1.10.2 on Windows 10 Home using Atom One UI Theme and Atom Light syntax theme.
1. Create a new file and enter some lines of text in it. Make sure there are around 40 characters per line.
2. Position your cursor somewhere halfway the second line (say, column 20)
3. Hold Shift and move the cursor up one line using the arrow Up key
4. Observe: The cursor is in the expected position, line 1 column 20, exactly one column above where it was before, and text from where the cursor is now up to where it was before is now selected
5. Release the Shift key
6. Press the Up key on the keyboard
7. Observe: The text is no longer selected (expected)
8. Observe: The cursor is now at the beginning of the line (column 1) (**not** expected)
9. Press the Down key on the keyboard
10. Observe: The cursor is now on line 2, column 1.

Expected behavior: Since we started on line 2 and are on line 1 at step 6, it's not possible to go up one more line so I would expect the cursor to remain where it is. I do expect to lose the selection when I attempt to move the cursor, but I don't expect it to move to the beginning of the line. 

The problem with the current behavior is that when you do Up, Down, you don't return to where you were before. This gives unexpected cursor 'jumps' when editing.

I compared with Microsoft Notepad and Notepad++

**MS Notepad:**
Behaves as I would expect. The cursor remains at it's position when we press Up on line 1, selection is lost

**Notepad++**
Has some mysterious behavior of itself. It also moves the cursor to column 1 when we press up (like Atom), but, crucially, when we press Down it moves the cursor back to where it was. This is actually also unexpected

I guess it's a minor issue. But I've found myself selecting the wrong stuff / deleting the wrong parts of a line etc when editing from muscle memory and I've traced it back to this quirk. I think it would improve the editing experience if it was fixed.

Also, note that if we don't hold Shift when moving Up and Down, Atom behaves as Notepad++:
When we press Up while the cursor is on line 1, it visually moves to the beginning of the line, however if we then press Down it actually moves back to where it was before, therefore maintaining command symmetry. This behavior changes (for the worse imho) when we hold Shift to select some text.

**Comment by Download** [comment]
Activity to prevent bot from removing my issue....

It won't solve itself. Maybe the'll make a bot for that once  :)

**Comment by 50Wliu** [comment]
:wave: @Download as previously mentioned, I tried to repro this issue.  It seems that Atom is now exhibiting the same behavior as Notepad++.  Here's a gif.
![cursor-up-down](https://user-images.githubusercontent.com/2766036/30695634-14f171b8-9ed9-11e7-896e-19820789c888.gif)

Would you consider that acceptable behavior?

**Comment by Download** [comment]
Yes it would seem acceptable indeed! The problem with the old behavior was that command symmetry was lost. 

So... it does seem like some issues do solve themselves! Thanks for your patience @50Wliu !

**Comment by 50Wliu** [comment]
Hurray!  In addition, we're looking into updating the stale comment based on your feedback :).
