### ISSUE TITLE
Syntax highlighting without file extension

### ISSUE THREAD

**Issue by LIyoai** [atom/atom#12678]
### Description

When I open a file without file extension I have no syntax highlighting at all.

### Steps to Reproduce

1. create a xml file without extension
2. open it
3. rename file to .xml
4. open it

**Expected behavior:**
If no file extension available atom could check the content of the file (maybe just the first line) to choose the correct syntax highlighting.

**Actual behavior:**
no file extension = no highlighting

### Versions
Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
Windows 7 64-Bit

**Comment by Ingramz** [comment]
It would be incredibly useful if you could provide the XML file you used to reproduce this.

**Comment by LIyoai** [comment]
You can use any files. XML, HTML...attached examples.
[xml.zip](https://github.com/atom/atom/files/469879/xml.zip)

**Comment by thomasjo** [comment]
This is possible via the `firstLineMatch` language grammar construct; see [shell-unix-bash.cson](https://github.com/atom/language-shellscript/blob/6d66ca58c030a9509b9e01ce57456511c529eb6a/grammars/shell-unix-bash.cson#L28).

I propose you open a [new issue](https://github.com/atom/language-xml/issues/new) on language-xml with a request that a reasonable `firstLineMatch` pattern be implemented that will detect XML (and XSL) files without extensions.
