### ISSUE TITLE
Antivirus flags "pathwatcher.node" as trojan malware

### ISSUE THREAD

**Issue by khalibloo** [atom/atom#12679]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode]?
Yes
* [x] Are you running the [latest version of Atom]?
Yes. Downloaded Atom a few minutes ago. Version 1.10.2
* [x] Did you check the [debugging guide]?
Yes
* [x] Did you check the [FAQs on Discuss]?
Yes
* [x] Are you reporting to the [correct repository]?
I think so.
* [x] Did you [perform a cursory search] to see if your bug or enhancement is already reported?
Yes.

### Description

On starting Atom and on performing certain actions like searching for new packages or even just opening the package manager, my antivirus (360 total security) reports that a trojan has been detected. 

After adding the patchwatcher.node file to my antivirus whitelist and restarting Atom, the problem went away. I think it might be worth looking into, though.

### Steps to Reproduce

1. If you have 360 total security installed, launch Atom
2. If you haven't already seen the alert, try to install a new package from the package manager

**Expected behavior:** [What you expected to happen]
When I search for a package, I expect to see results.

**Actual behavior:** [What actually happened]
A trojan alert is displayed by my antivirus and I do not see my search results afterwards.

### Versions
Atom 1.10.2
Windows 10 Pro x64

**Comment by thomasjo** [comment]
There is no such thing as `patchwatcher.node` — do you mean [`pathwatcher`](http://atom.github.io/node-pathwatcher/)? If that is the case, I would recommend switching to a better antivirus software. 

This is a ridiculous false positive most likely triggered based on filesystem activity. Since you are on Windows, why don't you simply rely on the built-in antivirus and malware protection? It's more than adequate.

/cc @atom/feedback

**Comment by 50Wliu** [comment]
> There is no such thing as patchwatcher.node

There actually is - it's created when running `npm install` at `%localappdata%\Atom\app-dev\resources\app.asar.unpacked\node_modules\pathwatcher\build\Release\pathwatcher.node`.

**Comment by khalibloo** [comment]
thomasjo, ah yes, that was a typo. I meant pathwatcher.node. Sorry for the confusion.

360 Total Security does a lot more than just protection for me, so I can't just revert to Windows Defender.

I've used Atom without any more of this issue for most of today, so I'm reasonably sure that the issue has been resolved in my case. I only reported this so you guys might have a look, in case it's something that can be fixed on Atom's part. Clearly, the offending file is doing something that the antivirus thinks is suspicious.

**Comment by thomasjo** [comment]
@khalibloo All it does is monitor files and directories. My only recommendation at this point is to open report this to 360 as a false positive; https://www.360totalsecurity.com/en/suspicion/

**Comment by khalibloo** [comment]
I've reported the file to 360 as a false positive. Thank you very much for your time.

**Comment by lee-dohm** [comment]
Since it appears to be a 360 Total Security issue, I'm closing.
