### ISSUE TITLE
Atom crashes opening a big text file

### ISSUE THREAD

**Issue by louisrubet** [atom/atom#12676]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom shows a popup saying "The editor has crashed. Please report this issue to https://github.com/atom/atom. Close window|Reload|Keep it open" when loading a 12.8MB text file. This file contains real values separated by semicolumns.

Reproduced in safe mode.

### Steps to Reproduce

Open a big text file !

**Expected behavior:**

**Actual behavior:** [What actually happened]

File not opened.

### Versions
louis>Tests> atom --version
Atom    : 1.10.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

louis>Tests> apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4

**Comment by Zireael07** [comment]
Sounds like #8864?

**Comment by louisrubet** [comment]
Maybe.
Fyi my big file contains about 800000 lines like
<real number>;<timestamp epoch format>\n

**Comment by louisrubet** [comment]
Nope. The problem is still there when I load the big file using the menu "File -> Open File ..." while atom shows any other directory.
-> nothing common with "Don't open the directory when I just want to open a single file." !
