### ISSUE TITLE
Unable to set keymap for core:save-all

### ISSUE THREAD

**Issue by xucaen** [atom/atom#12684]
The documentation for Atom is horrendous. It should not be this difficult to set a simply keymap. All I want is to set the save all to ctrl-alt-s. 

Here is what I did in keymap.cson:

'atom-text-editor':
  'ctrl-shift-s': 'core:save-all'
  'ctrl-alt-s': 'core:save-as'

Now, the save-as works (thought I had tried alt+shift+s which did NOT work) but the save-all will not work at all. 

Please document how to set up keymaps and please provide documentation for all the classes for all the menu commands. This should be easy, as it is with Brackets and VSCode - both let me set the key bindings is mere seconds and setting a key bind always overrides a default - not so with Atom apparently.

**Comment by Ben3eeE** [comment]
I believe the command name is `window:save-all` and not `core:save-all`. Try something like the following to see if it works:

```
'atom-text-editor:not([mini])':
  'ctrl-shift-S': 'window:save-all'
```

>Please document how to set up keymaps and please provide documentation for all the classes for all the menu commands.

What about the [keymaps in depth](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/) section of the flight manual?

**Comment by xucaen** [comment]
I've decided Atom is not a good fit for using in an Enterprise environment. I've moved on to another editor.
