### ISSUE TITLE
Unable to override alt-shift-s

### ISSUE THREAD

**Issue by xucaen** [atom/atom#12685]
Just installed Atom. First thing I am doing is changing the keymaps.
I did:

'body':
  'alt-shift-S': 'core:save-as'

but whenever I press alt-shift-s I get the snippets popup. So I did:

'.available-snippets atom-text-editor[mini]':
  'ctrl-alt-S': 'snippets:available'

and yet I still get the stupid snippets popup when I press alt-shift-s.

What do I have to do to override this keybind?? It should not be this difficult.  My custom keybind should automatically override any other default keybind..

**Comment by 50Wliu** [comment]
I cannot reproduce this with the following `keymap.cson`:
```cson
'atom-text-editor:not([mini])':
  'alt-shift-S': 'core:save-as'
```

Can you please try that and see if it works?  Thanks.

**Comment by xucaen** [comment]
Yes thank you. That worked.

**Comment by TrevorBurnham** [comment]
Ah, so the problem is [selector specificity](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#specificity-and-cascade-order), as documented.

I'll see myself out. 🚶

**Comment by xucaen** [comment]
I would love to see that document. But is it really the document that is at
fault or is the underlying process so complicated that even a seasoned
developer of 20 years can't understand it? (btw i had no trouble making the
same exact key binding in brackets and vscode,  just saying).  😉

**Comment by 50Wliu** [comment]
We agree that the process is overcomplicated - it was designed with the greatest flexibility possible (i.e. having the same key combo trigger different commands depending on where you executed it), but as can be seen in this issue it's not exactly intuitive.  I think we're planning on overhauling the system, but I don't have any details on that or whether or not it's even going to happen.
