### ISSUE TITLE
doctype crash on HTML or PHP

### ISSUE THREAD

**Issue by nicomf1982** [atom/atom#12688]
Hello guys, 
When i use this combination of doctype and PHP:

`<?PHP

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">`

And try to edit or change something in the first lines, ATOM crash ... i try to replicate this error on safe-mode but not happend there, 
I think the problem is the string on the DOCTYPE tag.

i use lastest version ATOM

thx

**Comment by 50Wliu** [comment]
> i try to replicate this error on safe-mode but not happend there,

This means that one of your installed packages is causing the issue.
