### ISSUE TITLE
Add auto indent keyboard shortcut

### ISSUE THREAD

**Issue by mattdipasquale** [atom/atom#12680]

**Comment by 50Wliu** [comment]
You can do this yourself: http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/.

In the future, please **completely** fill out the provided issue template.

**Comment by mattdipasquale** [comment]
OK. Thank you. But, I'm suggesting that Atom come installed with a "sensible default." See [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration). For example, in Xcode, it's <kbd>^I</kbd>, and in TextMate 2, it's <kbd>⌥⌘[</kbd>.

**Comment by 50Wliu** [comment]
If that is the case, please open a new issue and take care to fill out the issue template.  If you had included that information in this issue, I might not have closed it.

**Comment by mattdipasquale** [comment]
Why not just reopen this issue? What is it missing?
Keywords: re-indent, reindent, re-format, reformat

**Comment by 50Wliu** [comment]
> What is it missing?

The issue template.
