### ISSUE TITLE
The OS magnifier can't follow the text input cursor in editor

### ISSUE THREAD

**Issue by JiayangShen** [atom/atom#12709]
- Atom Editor Version: 1.10.2
- OS Version:windows 10

Steps to Reproduce:

1.  Press Win + R shortcut key to open the "Run Dialog", and input "magnify" to open the magnifier tool in the windows system. Then setting the magnifier to follow mouse pointer, follow keyboard focus, and follow text input cursor. 
2.  Open Atom, new a blank document, input some long text. You will find that the magnifier can't follow the text input cursor in editor.

**Thanks for this great code editor! But, utill now, modern code editors, like webstorm, sublime text, atom, and vscode, all of them have this accessibility issue. My eyesight is poor, magnifier is needed. I know the input cursor is just a simulated one using html+css+js, is there any way to make it can be followed by the OS magnifier when input in the editor? I like atom so much that I really hope this issue can be solved as quickly as possible. Thanks! **

**Comment by 50Wliu** [comment]
> Open vscode

I assume you meant Atom here?

**Comment by JiayangShen** [comment]
@50Wliu 
Sorry, I correct it. I compared some editors, and reported the same issue of them, included Atom.

**Comment by 50Wliu** [comment]
@JiayangShen Does it work in Chrome?

**Comment by JiayangShen** [comment]
@50Wliu doesn't work in chrome.

**Comment by 50Wliu** [comment]
As it doesn't work in Chrome, you would be best off filing a Chromium bug.  Then when they fix it, Electron will eventually pick up those changes, and then Atom (and also VS Code) will eventually update to the newer Electron.

**Comment by JiayangShen** [comment]
@50Wliu 
 OK, thanks!

**Comment by JiayangShen** [comment]
@50Wliu I noticed that Chrome 55 have solved this problem. And Atom?

**Comment by 50Wliu** [comment]
We'll need to wait for Electron to upgrade to Chrome 55.  Then Atom will eventually update to that Electron version.
