### ISSUE TITLE
How to get latest 32-BIT version?

### ISSUE THREAD

**Issue by Dan9er** [atom/atom#12706]
Hello, I'm looking for a way to update to or install the latest **32-bit** version of Atom, since there is a Python lintier that doesn't work with my current version: 1.0.11.

If I need to uninstall my current version, can someone please tell me how to do that as well?

System (`uname -a`): `Linux AcerNotebook 3.2.0-109-generic-pae #150-Ubuntu SMP Fri Aug 12 18:59:00 UTC 2016 i686 i686 i386 GNU/Linux`

Please don't mark this as closed when you post a solution in case that solution doesn't work for me.
Thank you in advance!

**Comment by 50Wliu** [comment]
Releases can either be downloaded from https://atom.io/ or https://github.com/atom/atom/releases.

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.  If you're still having issues after trying both of those methods, please create a new topic on Discuss instead.
