### ISSUE TITLE
Fail to Auto Detect ISO-8859 encoding

### ISSUE THREAD

**Issue by lpanebr** [atom/atom#12705]
### Description

Atom's Auto Detect is detecting the **ISO-8859** file below as a **Windows 1251** encoding resulting the word "Documenta**çã**o" to open as "Documenta**зг**o".

**Content of the [western-iso-8859-1.txt](https://github.com/atom/encoding-selector/files/477390/western-iso-8859-1.txt) file:**
```txt
<?php
$var = "Assistente Documentação e Pesquisa"
```

**Check the encoding:**
```bash
$ file western-iso-8859-1.txt
western-iso-8859-1.txt: PHP script, ISO-8859 text, with CRLF line terminators
```

**Detected encoding:**
![image](https://cloud.githubusercontent.com/assets/129185/18596194/55406e9c-7c1e-11e6-8180-af7cc0c836ae.png)

### Steps to Reproduce

1. Download and open this file: [western-iso-8859-1.txt](https://github.com/atom/encoding-selector/files/477390/western-iso-8859-1.txt)
2. Select Western ISO-8859 and confirm text is correct: "Documenta**çã**o"
3. Select Auto Detect and notice that encoding changes to **Windows 1251** and text is corrupt: "Documenta**зг**o"

**Expected behavior:** Encoding should be correctly detected thus resulting in correct text.

**Actual behavior:** Encoding is not detected correctly and thus corrupts the text.

### Versions

```bash
$ atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

$ apm --version
apm 1.12.5
npm 3.10.5
node 4.4.5
python 2.7.3
git 1.7.9.5
```

**Comment by damieng** [comment]
Thanks for reporting this.  We are currently tracking incorrect encoding detection at https://github.com/atom/encoding-selector/issues/8 so I'll close this one here.

**Comment by btrazzini** [comment]
@lpanebr estou com o mesmo problema. Sabe se foi resolvido?

**Comment by lpanebr** [comment]
@btrazzini eles estavam tratando disso no issue https://github.com/atom/encoding-selector/issues/8 que está fechado..

Eu não sei dizer pois desisti do Atom e voltei para o Sublime.

**Comment by btrazzini** [comment]
@lpanebr só para avisar, parece que o problema foi resolvido na versão 1.18.0-beta2.
Fiz uns testes por aqui e está tudo certo. 😉
