### ISSUE TITLE
Change default icon?

### ISSUE THREAD

**Issue by lednhatkhanh** [atom/atom#12707]
Hi, is there a way that I can change the default icon to this https://github.com/fv0/native-ui/raw/master/Atom.ico on Windows 10?

**Comment by thomasjo** [comment]
Sorry, but we are trying to manage [the deluge of issues](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html) and this is not the appropriate place for a general question such as this.

Try asking on [Discuss](https://discuss.atom.io/) or on [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638).
