### ISSUE TITLE
workspace.getActiveTextEditor() etc don't work if the text editor is not a PaneItem

### ISSUE THREAD

**Issue by pfitzseb** [atom/atom#12702]
The [docs](https://github.com/atom/atom/blob/v1.10.2/src/workspace.coffee#L646-L658) for `workspace.getTextEditors()` suggests that _all_ `TextEditors` anywhere will be returned, just as `workspace.getActiveTextEditor()` should seemingly return the currently active `TextEditor` no matter what.

This is obviously at odds with the implementation, which only considers `TextEditors` which are registered as `PaneItem`s. In the [ink package](https://github.com/JunoLab/atom-ink/), we have a `Console`-class, which extends `PaneItem` and can contain `TextEditor`s as input cells (those are properly registered, I think), but one can't access them via one of the commands above (also see [#75](https://github.com/JunoLab/atom-ink/issues/75) for why this is problematic).

So either the documentation should clarify that only certain `TextEditor`s will be considered or the implementation should be changed to searching the `TextEditorRegistry` or something like that. 

I can have a look at implementing this if you think that'd be a proper solution.

**Comment by iolsen** [comment]
@nathansobo do you have thoughts on whether this is an api or documentation bug? I lean toward documentation.

**Comment by nathansobo** [comment]
Yeah it's a documentation issue. The `atom.workspace` global really implies that we're talking about text editor *pane items*. For other editors, we could potentially add a method to the `atom.textEditors` global which is intended to deal with all editors. An approach that would work today would be to get the focused element via `document.activeElement`, but when the shadow DOM goes away the result will be the hidden input element embedded within the editor and won't be super convenient to resolve to an actual editor, hence my suggestion that we might add an API.

**Comment by pfitzseb** [comment]
Yeah, I was kinda unsure what `workspace` actually implied. Good to have that cleared up! Still don't quite understand the need for getting editor pane items as opposed to editors, but then again I haven't put much thought into this yet.

I think adding some a `getActiveTextEditor` method to `atom.textEditors` would be great, but I don't think we have any real need for that yet -- it's just surprising that some method of `workspace` (which is supposed to "Represent the state of the user interface for the entire window.") only works for certain parts of it.

Maybe it would make sense to deprecate `atom.workspace.getActiveTextEditor` etc in favor of that new API? I'd guess there are some packages out there which should probably work with text editors everywhere but don't right now (and I don't think to many packages contain non-PaneItem text editors anyways).

Sorry if I'm rambling (was never any good at designing APIs and stuff) and thanks for the feedback!

**Comment by nathansobo** [comment]
@pfitzseb Yeah, the workspace actually has a `paneContainer`, but it's not part of the public API. In retrospect it could probably be more clear. Workspace is the object that handles panes and panels, and since we never have a panel containing just an editor it felt natural to just have these methods imply pane items. At this point, this is probably too central of an API in the package ecosystem for this to be worth changing no matter what.

**Comment by pfitzseb** [comment]
Yeah, deprecating/changing that is probably more trouble than it's worth.

I'll try to figure out some way to improve the docs and maybe have a look at how to implement `atom.textEditors.getActiveTextEditor` or something similar.
