### ISSUE TITLE
 grunt: command not found

### ISSUE THREAD

**Issue by jiapei100** [atom/atom#12710]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
1. 
> jiapei:atom$ sudo script/grunt install
> sudo: script/grunt: command not found

2. 
> jiapei:atom$ sudo grunt install
> sudo: grunt: command not found
> jiapei:atom$ grunt --version
> grunt-cli v1.2.0

### Steps to Reproduce

1. Strictly follow http://stackoverflow.com/questions/24741996/how-to-upgrade-atom-editor-on-linux
and trying to upgrade atom to the newest git.
2. All good until 
`sudo script/grunt install`
3. grunt is installed already. But
`sudo grunt install` gives me the error message
`sudo: grunt: command not found`

**Expected behavior:** 
Just expect to successfully have atom upgraded, as described in:
http://stackoverflow.com/questions/24741996/how-to-upgrade-atom-editor-on-linux

**Actual behavior:** 
**grunt: command not found**

### Versions
```
jiapei:atom$ node -v
v6.6.0
jiapei:atom$ npm -v
3.10.8
```
```
jiapei:atom$ atom --version
Atom    : 1.9.0-dev-7253514
Electron: 0.36.12
Chrome  : 47.0.2526.110
Node    : 5.1.1
```
```
jiapei:atom$ apm --version
apm  1.10.0
npm  2.13.3
node 0.10.40
python 3.5.2
git 2.7.4
```
```
jiapei:atom$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

Looking forward to have atom upgraded....

Cheers
Pei

**Comment by arcticicestudio** [comment]
The`grunt` script has been removed in the `master` branch. Furthermore the StackOverflow question is outdated (2014).  
Anyway, you should use the `.deb` (e.g. [`v1.10.2`](https://github.com/atom/atom/releases/download/v1.10.2/atom-amd64.deb)) file to install the latest Atom version on distributions like Ubuntu.  
You can read the README [install section for Ubuntu] (https://github.com/atom/atom#debian-linux-ubuntu) for more information. Build instructions for Linux can be found [here](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md).
