### ISSUE TITLE
Atom Crashes on Ubuntu 16.04 LTS when init.coffee is open

### ISSUE THREAD

**Issue by codexetreme** [atom/atom#12716]
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

The Atom editor crashes when trying to close a previously opened init.coffee
### Steps to Reproduce
1. open init.coffee
2. Make sure Open empty editor in settings is not checked.
3. close atom, but don't close the init.coffee tab.
4. when you open atom again, try and close init.coffee script.
5. at this point atom crashes immediately. 
### Note

I did solve the issue by opening atom with the `--clear-window-state` flag this loaded an empty atom editor and everything works normally, but when I try to open init.coffee the same behaviour is back.
Also, i have nothing in my init.coffee script.
### Versions

atom : 1.10.2
Electron : 0.37.8
Chrome : 49.0.2623.75
Node : 5.10.0
apm : 1.12.5

**Comment by B3nac** [comment]
I'll see if I can reproduce this on my PC running the same version of Ubuntu.

**Comment by B3nac** [comment]
The very first time Atom crashed when I closed Atom with the init.coffee script open. After that it hasn't crashed with the exact steps mentioned. So it was reproducible but only once.

**Comment by olivbau** [comment]
Excatly same problem on Fedora 24.

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm : 1.12.5

**Comment by jdams051** [comment]
Same problem on kali linux, it happens also with the style.less file

**Comment by mako7c4** [comment]
Similar problem on windows 7.  Atom loads with the tab, init.coffee open and crashes when trying to close the file.

**Comment by ngr900** [comment]
Same problem on Windows 10.

**Comment by rubabuddin** [comment]
Problem still exists on Windows 7. Deleting it also doesn't cause it to regenerate from the .atom folder, as config.cson normally regenerates upon deletion.

**Comment by iron-cherep** [comment]
same problem when trying to close tab with init.coffee. Ubuntu 16.04 / Atom 1.12.6

**Comment by SamuelColacchia** [comment]
Same problem 

windows 10 

atom 1.12.7

To resolve: I uninstalled atom and then deleted .atom file under my user name

**Comment by aaltland** [comment]
Same behavior on OS X, Sierra, atom 1.12.9

**Comment by earnold** [comment]
Duplicated on OS X, Sierra, Atom 1.13.1 x64
