### ISSUE TITLE
[UX] Listing "Featured packages" below search results is confusing

### ISSUE THREAD

**Issue by chrisfilo** [atom/atom#12718]
Many applications these days perform search while you type. Since atom is listing featured packages under the search dialog (when you try to install a new package) it gives an initial impression that the the featured packages listing is the result of your search (if you just type your query without hitting enter). This is very confusing. I would suggest either:

a) implementing search while you type functionality
b) remove the featured packages from the search/install page

**Comment by arcticicestudio** [comment]
I think the featured packages are a pretty nice feature, but I agree with you. I'm using Atom a long time and already noticed that I forgot to hit enter.  
Here are some more ideas on how this may be solved:

  1. Add a option to disable featured packages
  2. Load all data on startup in the background
  3. Split the actual user search and the loading of the featured packages into two separate threads
  3. Implement some kind of loading bar/splash before the search form is displayed to load all the necessary data and show the user that Atom is busy, **but this is a really dirty solution**

**Comment by Ben3eeE** [comment]
This sounds very similar to the discussions in https://github.com/atom/settings-view/issues/825

**Comment by iolsen** [comment]
> This sounds very similar to the discussions in atom/settings-view#825

Agreed, and this discussion really belongs in the settings-view repo. I'm going to close this one. Feel free to subscribe to the settings-view one for further updates.
