### ISSUE TITLE
Lookbehinds not supported in Task instances

### ISSUE THREAD

**Issue by Alhadis** [atom/atom#12712]
Recent versions of Chromium include support for lookbehinds in regular expressions:

``` js
/(?<=a)b/.test("ab"); // -> true
```

This includes the one Atom v1.10 uses, which you can confirm by running the above snippet in your devtools.

However, [Task](https://atom.io/docs/api/v1.10.2/Task) instances seem to run using an older version of Node, because they throw TypeErrors if given regex with lookbehinds in them.
### Steps to reproduce
1. Save the following snippet to `~/Desktop/scan-test.js` (or something similar):
   
   ``` js
   module.exports = function(){
       let done = this.async();
       /(?<=a)b/.test("ab");
       done();
   };
   ```
2. Open the dev tools and run:
   
   ``` js
   require("atom").Task.once(`${process.env.HOME}/Desktop/scan-test.js`);
   ```
### Expectation

Nothing.
### Reality

```
/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52 Invalid regular expression:
/(?<=a)b/: Invalid group SyntaxError: Invalid regular expression: /(?<=a)b/: Invalid group
    at Object.module.exports (scan-test.js:3:2)
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:84:10)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
    (anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52
    (anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:126
    module.exports.Emitter.simpleDispatch @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25
    module.exports.Emitter.emit @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125
    (anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:78
    emitTwo @ events.js:100
    emit @ events.js:185
    handleMessage @ internal/child_process.js:718
    channel.onread @ internal/child_process.js:444
```

**Comment by Alhadis** [comment]
Still happening in Atom beta, 1.12.0-dev-f58d70a.

**Comment by Alhadis** [comment]
Alright, I suppose this isn't an issue now that the aforementioned expression actually throws an error in the main process, too:

~~~js
/(?<=A)B/.test("AB");
Uncaught SyntaxError: Invalid regular expression: /(?<=A)B/: Invalid group
    at <anonymous>:1:1
~~~

Not sure what happened since then, but the original issue is clearly not applicable anymore. Closing.

**Comment by 50Wliu** [comment]
Atom will pick up lookbehind support after Chrome releases it without a feature flag.

**Comment by Alhadis** [comment]
I assumed that, but what confused me is that I distinctly recalled lookbehinds being supported by any script that's executed by the main process. I didn't suspect Babel was involved because lookbehinds were supported by code executed by the dev-console, too...
