### ISSUE TITLE
Clicking Atom's dock icon isn't opening new windows

### ISSUE THREAD

**Issue by zertosh** [atom/atom#12728]
### Description

Clicking Atom's dock icon isn't opening new windows.

### Steps to Reproduce

1. Open Atom.app.
2. Close the Window from the red traffic light button (top left of window).
3. Click still running Atom.app icon from the Dock.

**Expected behavior:**

A new empty window to open.

**Actual behavior:**

Nothing happens.

### Versions

macOS 10.11.6.
Atom built from source at 2ed2121e4baed2643aabf6ec9da6e96b97c18762.

**Comment by Nikki1993** [comment]
I can confirm on latest macOS 10.12

**Comment by iolsen** [comment]
🙇 thanks for the report!

I see his too on master on macOS 10.11.6

**Comment by DavidIsrawi** [comment]
It opened a new empty window for me (Expected Behavior)

Using macOS Sierra 10.12
Atom 1.10.2
