### ISSUE TITLE
How do you navigate between several split panes? Are there any shortcuts / Key bindings?? 

### ISSUE THREAD

**Issue by rlam3** [atom/atom#12723]
How do you navigate between several split panes? Are there any shortcuts / Key bindings??

**Comment by 50Wliu** [comment]
https://github.com/atom/atom/blob/master/keymaps/darwin.cson#L92-L106
https://github.com/atom/atom/blob/master/keymaps/win32.cson#L79-L93
https://github.com/atom/atom/blob/master/keymaps/linux.cson#L74-L88

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
