### ISSUE TITLE
Keybinding shortcut with escape character

### ISSUE THREAD

**Issue by Bentipa** [atom/atom#12729]
The problem is, that when I try to override the Core-Shortcut 'alt-\' it won't work inside the keymap.cson file because \' is an escape character and I can't leave it like that. I can't write a backslash anymore because the key binding. I already tried:
'alt-\\' : 'unset!'
'alt-\ ' : 'unset!'
'alt-\'' : 'unset!:
nothing of these keybindings worked or disabled the core keybinding.

**Comment by 50Wliu** [comment]
`'alt-\\'`

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
