### ISSUE TITLE
Atom menus unreadable (both background and text are white) on Windows using high contrast theme

### ISSUE THREAD

**Issue by dev169** [atom/atom#12725]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

![2016-09-19 20_23_20-untitled atom](https://cloud.githubusercontent.com/assets/5874526/18641967/74aed9e0-7ea7-11e6-8301-c24b27e38639.png)

### Steps to Reproduce

1. Use Windows (tested on Windows 10)
2. Enable a High Contrast theme
3. Launch Atom

**Expected behavior:** Menus should be legible 

**Actual behavior:** Menus are illegible, making Atom unusable

### Versions

```
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 3.5.2
git 2.8.2.windows.1
visual studio 2015
```

This can be traced back to (see https://bugs.chromium.org/p/chromium/issues/detail?id=570698), please bump Chrome to resolve (verified fixed in `M49-49.0.2623.108`).

**Comment by 50Wliu** [comment]
> verified fixed in M49-49.0.2623.108

Good news: Atom 1.12.0 is on track to ship with Chrome 52!
