### ISSUE TITLE
Return the last active tab when close a tab

### ISSUE THREAD

**Issue by weijarz** [atom/atom#12735]
For example, open a project-wide search tab by `ctrl-shift-f` then close it, it should returns to the last _used_ tab in MRU order, but current version it returns to last tab in display order.

**Comment by vtambourine** [comment]
I suppose [atom/tabs](https://github.com/atom/tabs/) repository is more relevant to this issue.

**Comment by iolsen** [comment]
There are certainly people out there who prefer the current behavior, so this isn't something we could simply change. But perhaps when we add the option as described in https://github.com/atom/atom/issues/11035#issuecomment-254259897 we can base this behavior on it, too.

Also yes, this issue would be better off in [atom/tabs](https://github.com/atom/tabs). :)
