### ISSUE TITLE
Installing Atom on Raspberry PI 3

### ISSUE THREAD

**Issue by neilwilliams36** [atom/atom#12736]
I have used the following commands to try to install Atom on a Raspberry PI
git clone https://github.com/atom/atom.git
cd atom
Get npm setup 
sudo npm install node-gyp
sudo npm config set python /usr/bin/python2
Build and install Atom
sudo ./script/build  -–create-debian-package
cd out
sudo dpkg add-architecture arm
sudo dpkg –i atom-arm-deb
sudo apt-get –f install

I have had a number of errors in the process but finally got to the end without any errors.  I can see the installation but it does not run.  

When I try to run from the menu I get a spinning wheel and then no output.

Trying to run from the command line I get
nohup: failed to run command 'tmp/atom-build/Atom.atom': No such file or directory

I am assuming that Atom currently does not support running under a Raspberry PI architecture.

**Comment by gedeagas** [comment]
Bump, same problem

**Comment by Calinou** [comment]
You may be interested in [this issue](https://github.com/atom/atom/issues/7822) which tracks Electron-on-ARM support.

**Comment by damieng** [comment]
Atom isn't supported on the Raspberry Pi or indeed on ARM chipsets.  https://github.com/atom/atom/issues/7822 has much discussion about the steps people have taken so far.

**Comment by wgreybe** [comment]
Has anyone managed to get atom working on a Rasberry Pi3 since this listing?

**Comment by 50Wliu** [comment]
@wgreybe You might want to subscribe to #7822 for the latest updates regarding ARM.

**Comment by Luraktinus** [comment]
VScode works on my PI3
https://code.headmelted.com

**Comment by jonathanscottjames** [comment]
* heads up warning** this may clear your internet cache and rearrange your shortcuts in your start menu but it usually makes the whole system work i tried it on kazam and it worked like a charm
 sudo apt-get update
 sudo apt-get upgrade
(its the conventional method of installing anything in deb or raspbian)

**Comment by jonathanscottjames** [comment]
this did something. lol . i have no idea what but it took a minute
```
git clone https://github.com/atom/atom.git
cd atom
'then i was in this directory "pi@raspberrypi:~/atom $" and i typed the following
sudo apt-get  install package.json

```
