### ISSUE TITLE
atom can not auto detect .html and highlight by default

### ISSUE THREAD

**Issue by LeoWang1991** [atom/atom#12749]
![](http://ww1.sinaimg.cn/large/801b780agw1f81m39awrej213e0igacb.jpg)

when i new a html file, atom can not auto detect and highlight the file.it is detected as "Plain Text".
And i am confused why the html style in atom only "GO Rails Mustache Ruby-ERB" without Default Html Style .

the "GO Rails Mustache Ruby-ERB"  html style which i choose seems not highlight my html file.

my atom version is 1.9.9 on macOS10.12.

any solution or setting to solve the issue?Thx.

**Comment by 50Wliu** [comment]
The latest version of Atom is currently 1.10.2.  Can you try to reproduce this in safe mode (`atom --safe`)?

In the future, please **completely** fill out the provided issue template.

**Comment by LeoWang1991** [comment]
@50Wliu  it still has the issue when i launch atom by safe mode.i think the issue do not relative with the version of atom.

my colleague's atom which is normal that has the "HTML" style(format) in addition to "HTML(GO/Rails/Mustache/Ruby-ERB)".
i just try the different versions include the lastest in my macOS10.12. it miss the "HTML" style which cause the issue?
i try to re-install, but the issue still exist. 
what is the possible reasons?

**Comment by LeoWang1991** [comment]
i solve the issue that caused by "language-html" disabled.
but i am just confused why the setting do not be reseted after i re-install atom.
