### ISSUE TITLE
9|21|16 - The Installation Setup shows an Error! 

### ISSUE THREAD

**Issue by AbhigyanPal** [atom/atom#12741]
![untitled](https://cloud.githubusercontent.com/assets/22342966/18706679/9558b6c4-8010-11e6-80cf-0b0c4b4e9616.png)

Each time I run it.. it shows me this. I'm not able to figure out the Problem.
Please, help me with this! I really want it to work. :cry: 

[OS : Windows 7 (HB), 64-bit]

**Comment by Nikki1993** [comment]
I could be wrong here but I think Atom Editor is not available for 32bit Windows installation or any 32bit hence why it doesn't work.

**Comment by AbhigyanPal** [comment]
@Nikki1993 Heyy..! Thanks for Responding :smile: 
But I had used it Earlier and it worked fine then.
It got uninstalled, by mistake while I was uninstalling other apps.

**Comment by thomasjo** [comment]
@AbhigyanPal Please share the setup log with us. Right now we're unable to help you since we have basically zero information to work with.

**Comment by damieng** [comment]
As tomasjo says we'll need that setup log posted to be able to identify what went wrong.

If you are running a third-party anti-virus solution (McAffee) etc. you can try temporarily disabling it during installation.

@Nikki1993 Atom is only available on Windows as a 32-bit application today.  It should however run just fine on both 32-bit and 64-bit versions of Windows.

**Comment by AbhigyanPal** [comment]
Thank you very much for helping me with the problem. I did exactly what
 you said, and it worked. Now finally I can get back to Coding :computer: 

Thanks again! :) @damieng @thomasjo

**Comment by 50Wliu** [comment]
Closing as resolved.
