### ISSUE TITLE
Move Line breaks indentation in python

### ISSUE THREAD

**Issue by rogerfc** [atom/atom#12742]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

Moving lines or blocks of text around with Move Line Up/Down (CTRL+Up/Down) in python messes with the indentation. The code block gets indented to match the indentation of the block just above, assuming you want to nest it there. In general this results in code you have to re-indent back after moving. 

![optimised](https://cloud.githubusercontent.com/assets/1453692/18712371/6b316ce4-800e-11e6-9e52-aaeee5845d1f.gif)
### Steps to Reproduce
1. In a python script, select a line or block of text. 
2. Move it around with CTRL+Up/Down so it is below an indented line, e.g. a function. 

**Expected behavior:** The block of text is moved with its indentation preserved

**Actual behavior:** The indentation matches that of the line just above. 
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

❋ ~ ❯ atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
❋ ~ ❯ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.6
git 1.9.1
❋ ~ ❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:    14.04
Codename:   trusty

**Comment by ollpu** [comment]
This also causes any indentation structure in the code being moved to break.

From
```
if True:
    pass
if True:
    pass
```
to
```
if True:
    pass
    if True:
        pass
```

I feel like it is fine for the indentation to move with the surrounding area, but I don't like that it wrecks all relative indentation structure within the block that is moved.

**Comment by hugollm** [comment]
This "smart" reindenting thing causes me more problems than it solves.
Can't we just have a config to turn it off?
