### ISSUE TITLE
Exclude VCS Ignored Paths unchecked not showing node_modules

### ISSUE THREAD

**Issue by RonItelman** [atom/atom#12752]
I'm using Atom version 1.10.2 on a Mac.

When I click on Atom > Preferences > Core and uncheck 'Exclude VCS Ignored Paths' I am still unable to see my node_modules directory. I've tried restarting Atom as well. 

Here is an Atom Discuss post on the subject, but the solution is not working for me: https://discuss.atom.io/t/how-do-i-open-node-modules-dir/23708

Hoping someone has had luck on resolving this.

**Comment by zebapy** [comment]
@RonItelman did you look in the https://github.com/atom/tree-view package to make sure Hide VCS Ignored Files is not checked?
