### ISSUE TITLE
[Archlinux] Stop using atom ?

### ISSUE THREAD

**Issue by funilrys** [atom/atom#12751]
### Prerequisites
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
  `atom --version` don't work 
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
  I get same error than in normal mode
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
  `atom --version`  == I get nothing
  `atom --safe` 

```
/usr/bin/atom: line 56:  5170 Aborted                 (core dumped) nohup $ATOM_PATH --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
/usr/lib/electron/electron[5170]: ../../vendor/node/src/cares_wrap.cc:1327:void node::cares_wrap::Initialize(Local<v8::Object>, Local<v8::Value>, Local<v8::Context>): Assertion `(r) == (0)' failed.
 1: node::Abort() [/usr/lib/electron/libnode.so]
 2: 0x7ff05e67702d [/usr/lib/electron/libnode.so]
 3: 0x7ff05e66d242 [/usr/lib/electron/libnode.so]
 4: 0x7ff05e67ebcd [/usr/lib/electron/libnode.so]
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/lib/electron/libnode.so]
 6: 0x7ff05df85fda [/usr/lib/electron/libnode.so]
 7: 0x7ff05dfacf01 [/usr/lib/electron/libnode.so]
 8: 0x37dbe4706147
```

`atom --clear-window-state` 

```
/usr/bin/atom: line 56:  5219 Aborted                 (core dumped) nohup $ATOM_PATH --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
/usr/lib/electron/electron[5219]: ../../vendor/node/src/cares_wrap.cc:1327:void node::cares_wrap::Initialize(Local<v8::Object>, Local<v8::Value>, Local<v8::Context>): Assertion `(r) == (0)' failed.
 1: node::Abort() [/usr/lib/electron/libnode.so]
 2: 0x7f0ddc5ad02d [/usr/lib/electron/libnode.so]
 3: 0x7f0ddc5a3242 [/usr/lib/electron/libnode.so]
 4: 0x7f0ddc5b4bcd [/usr/lib/electron/libnode.so]
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/lib/electron/libnode.so]
 6: 0x7f0ddbebbfda [/usr/lib/electron/libnode.so]
 7: 0x7f0ddbee2f01 [/usr/lib/electron/libnode.so]
 8: 0x2c627e006147
```

`apm links`

```
/usr/bin/node[5264]: ../src/cares_wrap.cc:1328:void node::cares_wrap::Initialize(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>): Assertion `(r) == (0)' failed.
 1: node::Abort() [/usr/bin/node]
 2: node::Assert(char const* const (*) [4]) [/usr/bin/node]
 3: 0xd5bb7a [/usr/bin/node]
 4: 0xd6e715 [/usr/bin/node]
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/bin/node]
 6: 0x75046b [/usr/bin/node]
 7: 0x750b38 [/usr/bin/node]
 8: 0x750c9e [/usr/bin/node]
 9: 0x3880011092a7
Aborted (core dumped)
```
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

When I start `atom` in terminal I get 

```
/usr/bin/atom: line 56:  5640 Aborted                 (core dumped) nohup $ATOM_PATH --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
/usr/lib/electron/electron[5640]: ../../vendor/node/src/cares_wrap.cc:1327:void node::cares_wrap::Initialize(Local<v8::Object>, Local<v8::Value>, Local<v8::Context>): Assertion `(r) == (0)' failed.
 1: node::Abort() [/usr/lib/electron/libnode.so]
 2: 0x7f79e13ec02d [/usr/lib/electron/libnode.so]
 3: 0x7f79e13e2242 [/usr/lib/electron/libnode.so]
 4: 0x7f79e13f3bcd [/usr/lib/electron/libnode.so]
 5: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/lib/electron/libnode.so]
 6: 0x7f79e0cfafda [/usr/lib/electron/libnode.so]
 7: 0x7f79e0d21f01 [/usr/lib/electron/libnode.so]
 8: 0xf43d7106147
```

**But**
when i start `sudo atom` it's working.
### Steps to Reproduce

start atom

**Expected behavior:** [What you expected to happen]
I can code !
**Actual behavior:** [What actually happened]
I can't code ! 
### Versions

Installed via AUR : 1.10.2-1

**Comment by 50Wliu** [comment]
> Installed via pacman : 1.10.2-1

Please uninstall Atom and redownload from https://atom.io as you are using an unsupported version.

**Comment by ChevalierNumerique** [comment]
i'm an archlinux user too and i have atom-editor 1.10.2-1 100% working, installed by pacman :)

**Comment by funilrys** [comment]
solved by changing permission of resolv.conf to 644 !

**Comment by paulcbetts** [comment]
This would actually do the same thing on a released version - cc @zcbenz, this might be a clue for that Electron bug we saw with a similar call stack. @funilrys thanks for reporting back!

**Comment by funilrys** [comment]
Your welcome ! Long life to information sharing and open source softwares @paulcbetts ;)

**Comment by funilrys** [comment]
For reproduction change the permission of `resolv.conf` to 640 @mnquintana :)
