### ISSUE TITLE
Scrolling down document when no lines left

### ISSUE THREAD

**Issue by voytovichs** [atom/atom#12769]
### Prerequisites

* [Yes] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [Yes] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [No] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [Yes] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [Yes] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Yes] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]
I can scroll document down even if it has no lines left with data. There's a lower bound so I can't doing this continuously. The frame between last  line of data and actual 'lower bound' is about 25 lines. It feels like invisible 'something'.

I've never experienced that before updating to macOS Sierra, but not sure if it started right after updating thus I can't be sure that updating to Sierra causes that issue.

### Steps to Reproduce

1. [Open any file with any number of lines]
2. [Make sure you have n lines of code and (n + ~25) enables scrolling]
3. [See the issue]

**Expected behavior:** [What you expected to happen]
I want editor to show lines exactly document has and no more.
**Actual behavior:** [What actually happened]
I
### Versions
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
![atom_issue](https://cloud.githubusercontent.com/assets/6034290/18814543/fe8c6864-831e-11e6-9a84-f5761266a796.gif)
![screen shot 2016-09-25 at 12 30 30 pm](https://cloud.githubusercontent.com/assets/6034290/18814544/fe95b3b0-831e-11e6-970c-795a5c9a46aa.png)

**Comment by mnquintana** [comment]
Do you have `Scroll Past End` enabled? (under Settings > Editor)

**Comment by voytovichs** [comment]
Yes, didn't know about this.
Disabling it helps.
