### ISSUE TITLE
Feature request: Collapse functions/blocks

### ISSUE THREAD

**Issue by viktak** [atom/atom#12763]
Hi,

I extensively use the collapse function of the editor. When opening a source file, however, the editor expands all collapsed functions/blocks. Is there a way for the editor to remember what was collapsed the last time? Or failing that, could it open any file with all functions collapsed? Or provide a shortcut/button to do the same?

Every time I open a file I spend about a minute collapsing all functions that are of no interest to me at the time...

Thanks

viktak

**Comment by andyrichardson** [comment]
This functionality has already been added by the 'remember-folds' package.

**Installation**
`apm i remember-folds`

https://atom.io/packages/remember-folds

**Comment by viktak** [comment]
Sorry, I missed that. Closing this issue.
