### ISSUE TITLE
Bad Performance related to Coloration and Undo buffer

### ISSUE THREAD

**Issue by tenaciousRas** [atom/atom#12775]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Pasting a long line of minified JavaScript into an HTML doc causes slow performance.  This appears to be due to the coloration feature, and although it's barely acceptable I believe there are other bug reports related to that.

Once the long line is pasted poor performance is easy to encounter again.  Just highlight the newly pasted lines, and delete them.  I don't know for sure this is related to the architecture and/or implementation of the undo buffer, but that seems like a reasonable place to start.

### Steps to Reproduce

1. Open/create an HTML document.
2. Create an empty script tag for text/javascript in the HTML doc.
3. Paste the minified jquery JS into the script tag, the contents at https://code.jquery.com/jquery-3.1.1.slim.min.js
4.  Wait -- (repeatedly) clear any prompts that may appear due to system hanging.
5.  Highlight the newly pasted lines.
6.  Press backspace/delete.
7.  IDE hangs.

**Expected behavior:** [What you expected to happen]
Delete the highlighted lines and return control to the user.

**Actual behavior:** [What actually happened]
IDE hangs.

** Workaround **
Follow step 4 above.

### Versions
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.7.4

**Comment by Zireael07** [comment]
You say it's minified. Does that mean it has a veeery looong line?

**Comment by 50Wliu** [comment]
The description says "...a long line of minified JavaScript".  Therefore, I'm closing this in favor of #979.  Feel free to subscribe there for updates.
