### ISSUE TITLE
Variable scope color

### ISSUE THREAD

**Issue by dronzer92** [atom/atom#12774]
**Feature request**

### Description
Variable should have different  color in its scope
**example**
`
    
    function example() {
        var newVar = []; // white color

        newVar.push('a'); // white color
    }
    newVar.push('b'); // red color because variable cannot access OR show red underline
`

### Versions
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
OS    : Windows 10 (OS Build 14393.187)

**Comment by thomasjo** [comment]
Please read ["How Do I Submit A (Good) Enhancement Suggestion?"](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), then re-open this in the appropriate repo (which I'm guessing might be [language-javascript](https://github.com/atom/language-javascript)).

**Comment by 50Wliu** [comment]
Please don't open a new issue.  What you're asking for (contect-aware highlighting) isn't possible within Atom yet.
