### ISSUE TITLE
editor:auto-indent on a syntactically incorrect JS file consistently locks editor

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#12779]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

editor:auto-indent on a syntactically incorrect JS file consistently hard locks editor. Not sure if it's any malformed JS file or just this one but I have a file that i can reproduce with every time.
### Steps to Reproduce
1. create a file with these contents https://gist.github.com/thedaniel/0e95c39c4b1e5d688be17a5ba76dd80d
2. run editor:auto-indent
3. cry

**Expected behavior:** [What you expected to happen]

file would be indented, or the editor would try and fail to indent and i'd be able to continue editing

**Actual behavior:** [What actually happened]

<img width="611" alt="schermafbeelding 2016-09-26 om 13 26 23" src="https://cloud.githubusercontent.com/assets/1476/18832624/e2428002-83ec-11e6-8bac-0b5ef3309ebc.png">
### Versions

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by thedaniel** [comment]
Note the hundreds of lines of whitespace at the end of the file, maybe that has something to do with it? And yes I realize it is a garbage file with errors and whitespace and stuff but I did some mutations on it with find and replace in a sloppy fashion and tried to indent it - which I think is a pretty normal part of a developer's day.

**Comment by thedaniel** [comment]
(I don't actually know if the whitespace was there or created during the auto-indent crash, sorry)

**Comment by Ben3eeE** [comment]
For me the command takes a couple of seconds (5-10s) to complete. Which seems like much for the relatively small file but after waiting the command runs normally without any fails.
What I did was paste into a new texteditor, save it as `as.js`, select all text and run the `editor:auto-indent` command.

Did you try pressing the `Keep Waiting` button to see what happens if you wait? This dialog does block until you press the `Keep Waiting` button.

**Comment by thedaniel** [comment]
I did hit 'keep waiting' once, and waited about 5-10 s before giving up, force quitting, and returning to my work.

**Comment by 50Wliu** [comment]
Auto-indent does take its time with this file, but it does finish on a timescale comparable to what @Ben3eeE saw.
