### ISSUE TITLE
Bad Performance related to syntax coloring

### ISSUE THREAD

**Issue by tenaciousRas** [atom/atom#12784]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

When commenting long HTML lines, the editor hangs if the comment is authored in a natural way.  There is a workaround that can avoid the editor hang.
### Steps to Reproduce
1. Create an HTML document with multiple long lines of HTML code.  For example, create a script tag and place the contents of a large file into it.  Then create a second tag with the contents of another file.  NOTE:  you may need more HTML contents to reproduce this issue, if so simply create the code.
2. Preprend an HTML comment to the first script tag, i.e. "" to the closing script tag.  The editor will hang while re-coloring the syntax.

**Expected behavior:** [What you expected to happen]
Just use the previously known coloration when closing the comment.  Why re-process?

**Actual behavior:** [What actually happened]
Editor hangs while re-coloring.
### Workaround

When commenting long lines with an HTML comment, add the closing token first, then add the opening token.  No hanging occurs.
- NOTE:  there's no reason to think this doesn't happen with long JavaScript lines commented with /\* ... */.  Although unverified there's reason to suspect this could be a general problem for any programming language with multi-line comments in AtomIDE.
### Versions

Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.7.4

**Comment by 50Wliu** [comment]
> Create an HTML document with multiple long lines of HTML code.

Define "long" please?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12784#issuecomment-249675622. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by tenaciousRas** [comment]
Re-open this bug, please, dude.  In my humble opinion this kind of support is a disservice to the Atom project.  You already have a definition of "long" in the "steps to reproduce".  Did you read them?  Did you even spend any time trying to reproduce the bug?  The "steps to reproduce" says you can use the contents of a file inside a script tag -- so why not try a JavaScript file that's approx. 1MB?  You don't need me to provide a URL since Atom probably has such files inside itself.

**Comment by 50Wliu** [comment]
You never defined "long", only saying to "Create an HTML document with multiple long lines of HTML code".  How long is long?  100 characters?  1000?  Neither did you define "large".  Both of those can be extremely subjective.

No, I did not spend any time trying to reproduce this bug as I cannot without knowing how to.  Until you specify what you mean by "long" and "large", the Atom team will not be able to take action.

**Comment by tenaciousRas** [comment]
Do you need me to hold your hand to reproduce the bug after that thorough description and follow up?  Can you please re-open this bug and re-assign it to another community member that may take it more seriously?  When I reported the bug, I was embedding base64 data into HTML and/or CSS, and the Atom IDE was unusable without the workaround I provided.  You don't need to embed Base64 data to reproduce this bug.  I'm very disappointed you didn't even attempt to reproduce the bug because the effort you spent to close the bug is likely greater than that required to reproduce it.

**Comment by tenaciousRas** [comment]
I define long as a file > 500MB.  As stated in the description you may need to embed more than one (1) file.  Just give it a try!  I look forward to re-opening this bug, @50Wliu.

**Comment by tenaciousRas** [comment]
No need to re-open this bug report since it's been re-filed at #13521.
