### ISSUE TITLE
Opening file through default file association when Atom had been started manually opens second instance

### ISSUE THREAD

**Issue by boekhold** [atom/atom#12800]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

cannot use safe mode with this use case

* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?

cannot use these tips with this use case.

* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?

nothing applicable to be find here.

* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description
I have Atom set as the default program for files with extension ".sql". If I double-click a .sql file in Windows Explorer *while Atom is not yet running*, Atom opens correctly with the file. If I click another ".sql" file, that file is correctly opened in the same Atom window in a new tab. This works the same if I right-click and select "Open with Atom".

Now I shut down Atom, and manually open Atom (Windows key -> Atom). Atom opens with the last session state. If I now double-click an SQL file in Windows Explorer, _a second Atom instance_ opens with the file. If on the other hand I right-click->Open with Atom, the file opens in the existing Atom window in a new tab.

When double-clicking a file while an Atom instance was previously started manually (Windows key -> Atom), that file should open in the existing window, not open a new Atom instance.

Btw. the same issue happens when trying to open an SQL email attachment from Outlook. If Atom was previously started manually, this will open a new Atom instance with the file. It does not re-use the existing instance.

### Steps to Reproduce

1. Open Atom manually, eg Start menu->GitHub, Inc -> Atom
2. Open Windows Explorer
3. Locate a file who's extension has been associated with Atom
4. Double-click that file

**Expected behavior:** The file from (4) opens in the existing Atom window

**Actual behavior:** A new Atom instance opens with the file. Now there are 2 Atom windows/instances

### Versions
- Atom 1.10.2
- Electron 0.37.8
- Chrome 49.0.2623.75
- Node 5.10.0
- Windows 7 Professional SP1

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by Ben3eeE** [comment]
Try this:

1. Completely exit all instances of Atom.
2. Launch Atom from cmd.exe using `atom --safe`.
3. In the settings-view open the Systems tab and check all three options.
4. Close Atom and try to reproduce this issue.
5. In the settings-view systems tab check all options as you want.

**Comment by boekhold** [comment]
Done, no change, same behavior:

1. Shut down all Atom instances
2. Open atom from CMD prompt with `atom --safe`
3. Tick all 3 options in Settings->System
4. Shut down Atom
5. Open Atom manually from Start->GitHub Inc.->Atom
6. In Windows Explorer, double-click an SQL file
    - A new Atom instance is opened with the file I just double-clicked
    - Note that right-click->Open with Atom produces the expected behavior: the file is
       opened in the existing instance of Atom.

**Comment by Ben3eeE** [comment]
I can not reproduce this, I associated a markdown file with Atom and it opened in the current Atom instance when I double clicked it in the file explorer.

Maybe a duplicate https://github.com/atom/atom/issues/12606

**Comment by boekhold** [comment]
Yes, seems like a duplicate of #12606. Sorry I missed that one, I did search for "new window" but somehow I didn't see this one.

Do you want to close my duplicate case then as "duplicate"?

**Comment by boekhold** [comment]
I think I've discovered something. As you recall, opening a file through "right-click->Open with Atom" works correctly, even if I have Atom open already. But double-clicking opens a separate instance. Once that second instance opens and I double-click another file, it opens as a tab in the second instance.

I searched through my registry, and I noticed:

- `HKEY_CLASSES_ROOT\*\shell\Atom\command` = `C:\......\atom\app-.1.10.2\atom.exe`
- `HKEY_CLASSES_ROOT\Applications\atom.exe\shell\open\command` = `C:\....\atom\app-1.10.0\atom.exe`
-`HKEY_CURRENT_USER\Software\Classes\Applications\atom.exe\shell\open\command` = `C:\....\atom\app-1.10.0\atom.exe`

So that's actually 2 different applications that are registered, so it makes sense that they open in different windows. Indeed, if I close all Atom instances and double-click an SQL file, and then check Help->About, it tells me the Atom version is 1.10.0, not 1.10.2....

Is there something in the upgrade process that fails to change the "Applications\atom.exe" entries to point to the new version?

**Comment by Ben3eeE** [comment]
Thanks for the additional information this does indeed look incorrect. All my instances point to app-1.10.2 which is why I was unable to reproduce it.

@damieng Any ideas why these keys have not updated? Same thing as right click menu but not possible to work around with the `settings-view`?

**Comment by boekhold** [comment]
#12642, with commit https://github.com/atom/atom/commit/7c48b947d738e189c26ba342018b4e47b4cea3be ???

This was fixed 19 days ago, not sure when 1.10.2 was released?

**Comment by Ben3eeE** [comment]
Yea that one. This commit was after 1.10.2 so the fix will be available the next upgrade.

**Comment by mickejansson** [comment]
I have this problem with the latest release. Sure it's suposed to fixed?
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
Windows 10 Enterprise v 1511

**Comment by damieng** [comment]
It was definitely fixed almost a year ago - that's not to say something isn't regressed but it's worth also checking you are seeing the exact same behavior.

Are both versions of Atom that open the same?

**Comment by mickejansson** [comment]
If you're asking if the two windows that opens have the some tabs open, then no. The new one always has only the one with the new file.
However, just figured something out. If i open i file in the same directory, it will open in the same atom window. It makes the directory that i'm opening the file from a project in atom. Maybe that's by design and i'm just not getting how atom works?

**Comment by damieng** [comment]
So one of a few things might be happening - when I said version I meant version of Atom as found in Help > About Atom.  It's possible you can get in a state where you have multiple versions of Atom installed and they keep taking the association from each other.

If you have got into this state close all running copies of Atom and launch 1.21 from your Start Menu. Then go into Atom's Settings > System > and uncheck, wait a second then recheck "Register as a file handler" to ensure it takes over any stray associations.

**Comment by mickejansson** [comment]
Oh! You're rigth, i did have multiple versions installed. Thanx, that solved the problem it seems :)
