### ISSUE TITLE
Atom built-in apps are not using npm3 structure 

### ISSUE THREAD

**Issue by bmharsha** [atom/atom#12805]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Even though npm3 has been enforced on external apps, Atom built-in apps are not using this structure yet!  
I downloaded atom-windows.zip (Tried with both [Beta](https://github.com/atom/atom/releases/download/v1.11.0-beta5/atom-windows.zip)  and [stable](https://github.com/atom/atom/releases/download/v1.10.2/atom-windows.zip)), when I extracted this zip file, the packages inside “resources” folder had long chain of sub-directories, the path-size of these sub-directories range upto 206 characters, one example of such path is as follows

```
Atom\app-1.10.2\resources\app\apm\node_modules\npm\node_modules\request\node_modules\har-validator\node_modules\is-my-json-valid\node_modules\generate-object-property\node_modules\is-property\is-property.js
```

Since Windows MAX_PATH is restricted to 260 characters, we cannot extract Atom or relocate existing installation of Atom onto a location where the path size is more than 54 characters (260-206=54) 
### Versions

Aforementioned issue exists on both 1.10.2 (Current stable release) and 1.11.0-beta5 (Latest beta version)

**Comment by tkelman** [comment]
This wasn't fixed, was it? Should be reopened if not.
