### ISSUE TITLE
Atom package dependency add Unix utils

### ISSUE THREAD

**Issue by ethanjyx** [atom/atom#12815]
I am interested in writing an Atom package that may depend on and call a Unix util, specifically a2ps: https://www.gnu.org/software/a2ps/. Is this possible? Thanks.

**Comment by 50Wliu** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
