### ISSUE TITLE
window:focus-pane-on-right/left not working in large window

### ISSUE THREAD

**Issue by jacobmischka** [atom/atom#12830]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

`window:focus-pane-on-right` and `window:focus-pane-on-left` don't work when the window is greater than the breakpoint between the `minimum` and the largest `even` tab sizes when the setting is `auto`.

It seems to only be a problem with `-left` and `-right`, `focus-pane-above`, `focus-pane-below`, `focus-previous-pane`, and `focus-next-pane` work fine in all sizes.

Small window, minimum-style tabs, `window:focus-pane-on-left/right` works correctly:
![image](https://cloud.githubusercontent.com/assets/3939997/18998792/be070904-86ff-11e6-915e-b2e19926d400.png)

Wide and short window, medium-sized even-style tabs, `window:focus-pane-on-left/right` works correctly:
![image](https://cloud.githubusercontent.com/assets/3939997/18998893/27f6e53c-8700-11e6-849f-ea444014009c.png)

Large window, even-style tabs,  `window:focus-pane-on-left/right` does nothing:
![image](https://cloud.githubusercontent.com/assets/3939997/18998900/3397e594-8700-11e6-9e71-026228d1fdea.png)

Small behavior:
![focus pane works](https://cloud.githubusercontent.com/assets/3939997/18998964/92ba5a0c-8700-11e6-8dea-76a6cfb6a397.gif)

Large behavior:
![doesnt work](https://cloud.githubusercontent.com/assets/3939997/18998967/971e9bd0-8700-11e6-88b0-bac6bce95133.gif)

Apologies for the poor/weird recording in those gifs, screen recording works poorly on my work desktop for some reason.

### Steps to Reproduce

1. Fullscreen the window
2. Call `window:focus-pane-on-right`

**Expected behavior:** Pane on right is focused.

**Actual behavior:** Current pane is still focused.

### Versions

Platform: Arch Linux x64

`$ atom --version`
Atom    : 1.10.2
Electron: 1.4.1
Chrome  : 53.0.2785.113
Node    : 6.5.0

**Comment by 50Wliu** [comment]
> Electron: 1.4.1

You are using an unsupported version of Atom.  Please uninstall it and download it from https://atom.io instead.

https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md

**Comment by jacobmischka** [comment]
Okay, fair enough. I forgot Arch's package uses upstream electron, my mistake.

Can you please confirm for me that this is not an issue with the correct version of electron? The command works for you, right?

Thank you!

**Comment by 50Wliu** [comment]
As far as I can tell, the commands are working, though I do have the tabs to always be even.
