### ISSUE TITLE
keymap alt-\ error

### ISSUE THREAD

**Issue by MrVacless** [atom/atom#12844]
When I try to change the bind of alt-\ I get an error

I tried this:
'.platform-win32, .platform-linux':
  'alt-\': 'unset!'

and then I get that error
[stdin]:2:19: error: missing '
  'alt-\': 'unset!'

**Comment by 50Wliu** [comment]
`'alt-\\'`

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
