### ISSUE TITLE
Replace CoffeeScript with IcedCoffeeScript ?

### ISSUE THREAD

**Issue by lazytyper** [atom/atom#12849]
[IcedCoffeeScript](http://maxtaco.github.io/coffee-script/) could make developing atom app easier.
It adds the keywords `await` and `defer`:

An example with `CoffeeScript`:

``` coffee
serialSearch = (keywords, cb) ->
  result = []
  i = 0
  launch = () ->
    if i < keywords.length
       j = i++
       search keywords[j], cb_generator j
     else
       cb results
  cb_generator = (i) ->
    (json) ->
      results[i] = json
      launch()
  launch()
```

With `IcedCoffeeScript`:

``` coffee
serialSearch = (keywords, cb) ->
  out = []
  for k,i in keywords
    await search k, defer out[i]
  cb out
```

So simple ;)

**Comment by lazytyper** [comment]
You should use `iced-coffee-script-3`

**Comment by mnquintana** [comment]
Thanks for the suggestion! We're not planning on using (any dialect of) CoffeeScript going forward though – see https://github.com/atom/atom/issues/12656#issuecomment-246122469 for more info
