### ISSUE TITLE
Atom in not in Start Menu

### ISSUE THREAD

**Issue by AwesomeMinecrafter94** [atom/atom#12854]
### Prerequisites
- [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? 

I am not sure
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)? 

I just installed today
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? 

No
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)? 

No
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)? 

I believe I am.
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported? 

Bug has been reported back in 2014
### Description

I installed Atom about an hour ago and when it finished, I saw Atom did not show in the start menu by default. I had to search Atom.exe  and manually add to the Start Menu. I did some rearch and found this [Issue from 2014](https://github.com/atom/atom/issues/2321). It looked like it was getting fixed.
### Steps to Reproduce
1. Install Atom

**Expected behavior:** I expected Atom to be in the start menu

**Actual behavior:** Atom did not appear in the start menu
### Versions

1.10.2

**Comment by damieng** [comment]
We're going to need more information to find out why this isn't working on your system - it definitely appears for the majority of people.

Can you find the squirrelsetup.log file? It should be one folder up from where you found atom.exe and will provide some details.

Can you also let us know if you are on a corporate network or using a third-party antivirus package?

**Comment by AwesomeMinecrafter94** [comment]
It did for my laptop too. it actually added a desktop icon which my PC did not. I also have to manually add it to the start menu. I'll see if I can get the file for you.

**Comment by AwesomeMinecrafter94** [comment]
Here is [SquirrelSetup](http://pastebin.com/9dHskmSR)

**Comment by AwesomeMinecrafter94** [comment]
I don't use an anti-virus (Unless you count Windows Defender but, I almost never run it.) . What exactly is a corporate network? 

I use Windows 10 in case you need that information.

**Comment by TKONTOP** [comment]
THI IS THE BEST SOFTWARE I EVER COME ACROS I WILL GIVE IT 5 RATE STAR

**Comment by AwesomeMinecrafter94** [comment]
What?

**Comment by damieng** [comment]
Some companies when they have many Windows machines lock them down and that can intentionally stop things like shortcuts. That doesn't sound like your case.

The log indicates it created it:

`Creating shortcut for atom.exe => C:\Users\Joshua\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\Atom.lnk`

Can you see if it is in the start menu by clicking it and hunting for the GitHub, Inc. group.  I have noticed recent Windows 10 builds are often very slow at indexing all new programs and just pressing <kdb>Start</kbd> and typing **Atom** for example won't show it immediately.

**Comment by damieng** [comment]
It should appear like this; 
![image](https://cloud.githubusercontent.com/assets/118951/19094983/1f146c5a-8a48-11e6-9545-7acbf1da5f47.png)

**Comment by AwesomeMinecrafter94** [comment]
It is not in that folder.

**Comment by AwesomeMinecrafter94** [comment]
I searched it in the File Explorer and it is there. Just not showing in the start meny

**Comment by damieng** [comment]
So it is in `C:\Users\Joshua\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.` ?

Can you go up a level in Explorer and see if other files exist above GitHub, Inc?  It just sounds like the Windows Start Menu isn't updating itself. It should be completely automatic.

**Comment by AwesomeMinecrafter94** [comment]
Yes, I have GitHub (with Git Shell) installed and it works fine.

**Comment by damieng** [comment]
If the folder is there it is supposed to appear in the start menu. There are no extra steps an app needs to take (you can test this yourself by creating folders in that path and seeing them appear).

Would be interesting to know if it appears next time you reboot.

**Comment by AwesomeMinecrafter94** [comment]
Interesting... I made a new folder and it did not appear... It's like it is in a different folder path - which I remembered I put the Atom shortcut in and forgot what file path it is

**Comment by damieng** [comment]
Is it still not showing after a reboot?  Can you also try installing another program and see if that adds to the start menu?

**Comment by AwesomeMinecrafter94** [comment]
I installed VMWare yesterday and it shows in the start menu.

**Comment by andyrichardson** [comment]
Any update on the issue? Did you attempt to reinstall the Atom?

**Comment by damieng** [comment]
No response, closing.  Please continue the discussion if the problem still exists.
