### ISSUE TITLE
Feature: Open folder in current window

### ISSUE THREAD

**Issue by RichardJECooke** [atom/atom#12857]
### Description

Similar to this, but for folders: https://github.com/atom/atom/issues/1722
### Steps to Reproduce

Menu - File - Open folder - Select folder

**Expected behavior:** [What you expected to happen]
- Folder opens in current window 

OR
- Select this window or new window

**Actual behavior:** [What actually happened]
- Folder opens in a new window

**Comment by 50Wliu** [comment]
Does Add Project Folder work for your needs?

**Comment by RichardJECooke** [comment]
That's useful. But it's not the same as this issue, which when I google people were asking about on the forums.  In most applications when you open something new the current thing closes, or it asks you if you want to close it.  That new feature would be a better UX for Atom.

**Comment by andyrichardson** [comment]
I somewhat agree; I think the UX needs some work. While I'm far from an expert in this field, I think 'open folder' should have the functionality of 'add project folder' (obviously the latter would need to be removed). 

**Open folder**
File -> Open folder

**Open folder in new window**
File -> New window
File -> Open folder

Having 'open folder' and 'add project folder' options just doesn't seem very intuitive as both share the functionally of opening folders. Another alternative would be to have 'open folder' and 'open folder in new window' options.
