### ISSUE TITLE
Problem when trying to close curly braces and square brackets

### ISSUE THREAD

**Issue by DataTriny** [atom/atom#12853]
Hello,
On the latest Atom version, with French keyboard, it is impossible to write "}" and "]" on the editor.
When pressing Altgr + = to write "}", nothing happens, and when pressing Altgr + ) to write "]", sometimes it deletes the entire block of code (in languages such as PHP).
Thanks in advance.

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.12.0.  Beta releases should be available in the coming weeks.
