### ISSUE TITLE
--wait does not interact reasonably with the no-prompt-on-close behavior

### ISSUE THREAD

**Issue by boutell** [atom/atom#12860]
The `--wait` option is intended to allow the use of atom as a step in a command line process such as `git commit` in which the command line process does not proceed until the user closes the file.

This interacts poorly with atom's no-prompt-on-close behavior. When working with `--wait` the file is usually a temporary file, so there is no opportunity to restore the work later.

The `--wait` option should introduce prompt-for-save-on-close behavior. Otherwise the user must take a minimum of two steps in a certain order to avoid "stubbing their toe."

**Comment by stereobooster** [comment]
Kind of related #12607
