### ISSUE TITLE
Copy paste file/folder from Atom does not work with Windows Explorer

### ISSUE THREAD

**Issue by Kungfoowiz** [atom/atom#12867]
### Description

When copying a file/folder from Atom editor, it does not recognise the paste operation in Windows Explorer. Please see screenshots.
### Steps to Reproduce
1. Copy a file/folder in Atom.
2. Go to Windows explorer.
3. Try to paste the file/folder from Atom and it remains greyed out.

**Expected behavior:** 

It would be nice to be able to paste from Atom into Windows Explorer.

**Actual behavior:**

The Paste option is greyed out / disabled in Windows Explorer.
### Versions

Atom 1.10.2

![image](https://cloud.githubusercontent.com/assets/17824719/19069752/246f7514-8a20-11e6-910b-18ac6c9c8897.png)

![image](https://cloud.githubusercontent.com/assets/17824719/19069761/32ce3f82-8a20-11e6-9a79-97894f9a7bfc.png)

**Comment by marat-chardymov** [comment]
File copying doesn't work on Ubuntu 16.04 either

**Comment by moonjoungyoung** [comment]
verson: 1.23.3
os: windows10 1709

This issue is still working.
Windows Explorer -> Atom and Atom -> Windows Explorer
Copy/Paste is not working.
