### ISSUE TITLE
Differing results in specs and Atom itself

### ISSUE THREAD

**Issue by Gert-dev** [atom/atom#12874]
Hello

I'm encountering a strange problem whilst running package specs in Atom: the scope descriptors I get from the specs don't seem to be the same as those in the actual editor. I may very well be doing something wrong here, so feel free to stop me if I am.

I have the following simple PHP code:

```php
<?php

$test = \Test\CONST_TEST;
```

Putting this into an editor, the `\Test\` part of the scope descriptor has `.support.other.namespace.php` in its scope chain according to the developer tools. I can verify this via my package:

```coffeescript
editor.scopeDescriptorForBufferPosition([2, 10]).getScopeChain()
```

This yields `.text.html.php .meta.embedded.block.php .source.php .support.other.namespace.php`, which is correct. However, if I put this into my spec:

```coffeescript
describe "Test", ->
    editor = null
    grammar = null

    beforeEach ->
        waitsForPromise ->
            atom.workspace.open().then (result) ->
                editor = result

        waitsForPromise ->
            atom.packages.activatePackage('language-php')

        runs ->
            grammar = atom.grammars.selectGrammar('.text.html.php')

        waitsFor ->
            grammar and editor

        runs ->
            editor.setGrammar(grammar)

    it "gives different results from an actual Atom window?", ->
        source =
            """
            <?php

            $test = \Test\CONST_TEST;
            """

        editor.setText(source)

        lines = editor.getLineCount()

        for line in [0 .. lines - 1]
            text = editor.lineTextForBufferRow(line)

            continue if text.length == 0

            for i in [0 .. text.length - 1]
                chain = editor.scopeDescriptorForBufferPosition([line, i]).getScopeChain()

                console.log([line, i], chain)
```

The entire range `\Test\CONST_TEST` is marked as being a `.text.html.php .meta.embedded.block.php .source.php .constant.other.php`, which is something slightly different from what the editor says. What's strange is that it seems that actual syntax highlighting has occurred, as scope descriptors are present, but only _some_ of them are different from the actual results. Am I perhaps somehow using the wrong grammar?

My apologies if this is in the wrong place, the issue is somewhat tied to the `language-php` package, but since it involves difference in behavior between specs and the actual editors, I thought it might belong here instead.

I'm using Atom version 1.10.2.

Thanks in advance

**Comment by 50Wliu** [comment]
I believe you need to do `\\Test\\`.  Try that.

**Comment by Gert-dev** [comment]
Thanks, I can't believe I missed that. I had checked the example several times in the hope of finding something wrong with it as the different results just didn't seem to be possible. Another newbie mistake to add to my list :+1: .
