### ISSUE TITLE
change font 

### ISSUE THREAD

**Issue by tsouhaieb** [atom/atom#12872]
i can't find a way to change atom to use 'Meslo LG S Regular for Powerline' font osx, i already installed this font on this system but zhen i wright the name in font family field, i doesn't change

please any

**Comment by rodude123** [comment]
try to reinstall it if that doesn't work then maybe atom has its own fonts

**Comment by damieng** [comment]
I just downloaded this font from https://github.com/powerline/fonts/blob/master/Meslo/ and on installation noticed the style name isn't "Regular" but is instead "RegularForPowerline" as shown here 
![image](https://cloud.githubusercontent.com/assets/118951/19104150/cf69ca86-8a8f-11e6-89d4-52cfc8f53cfc.png)

This is very likely messing up the matching in Chrome.  

There is a workaround on the Mac; You can go into Font Properties from Font Book and lookup the PostScript name and use that which in this case is **MesloLGS-RegularForPowerline** which then works.
