### ISSUE TITLE
Accessibility: No Option To Change Text Size

### ISSUE THREAD

**Issue by koopdi** [atom/atom#12887]
There is an option to change editor text size but not for the rest of the UI.
Even after editing a custom stylesheet, many elements are still too small (for me) to read. It is unclear how to universally increase the size.
All sizes need to be relative to a global modifier.

**Comment by koopdi** [comment]
duplicate of
https://github.com/atom/atom/issues/4342

**Comment by thomasjo** [comment]
If you use either One Light or One Dark, the font size is trivially configurable via the theme settings;

<img width="848" alt="settings_ ___code_atom_latex" src="https://cloud.githubusercontent.com/assets/3622/19143391/e884e932-8ba3-11e6-9aa7-cbeb3dc50ec8.png">

**Comment by koopdi** [comment]
That works for most things, thanks. Popup errors are still small.

**Comment by Ben3eeE** [comment]
@koopdi Thanks for following up 🙇 We have created an issue for this at https://github.com/atom/one-dark-ui/issues/170. Feel free to subscribe there for updates.

**Comment by TKONTOP** [comment]
Thanks sir
