### ISSUE TITLE
script/build error "Cannot find module 'internal/fs' 

### ISSUE THREAD

**Issue by Aakash1312** [atom/atom#12880]
### Prerequisites

* [Y ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [Y ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ Y] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [Y ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Y ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

[script/build error "Cannot find module 'internal/fs' "]

### Steps to Reproduce
I cloned atom repo, installed all the mentioned repositories, then script/build gave this error:

```
Node:	v7.0.0-pre
Npm:	v3.10.8
Installing script dependencies
npm ERR! Linux 3.19.0-69-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--loglevel=error" "install"
npm ERR! node v7.0.0-pre
npm ERR! npm  v3.10.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aakash/packages/atomlatest/atom/script/npm-debug.log
child_process.js:511
    throw err;
    ^

Error: Command failed: npm --loglevel=error install
npm ERR! Linux 3.19.0-69-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--loglevel=error" "install"
npm ERR! node v7.0.0-pre
npm ERR! npm  v3.10.8
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'internal/fs'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aakash/packages/atomlatest/atom/script/npm-debug.log

    at checkExecSyncError (child_process.js:488:13)
    at Object.execFileSync (child_process.js:508:13)
    at module.exports (/home/aakash/packages/atomlatest/atom/script/lib/install-script-dependencies.js:10:16)
    at Object.<anonymous> (/home/aakash/packages/atomlatest/atom/script/bootstrap:26:1)
    at Module._compile (module.js:574:32)
    at Object.Module._extensions..js (module.js:583:10)
    at Module.load (module.js:491:32)
    at tryModuleLoad (module.js:450:12)
    at Function.Module._load (module.js:442:3)
    at Module.require (module.js:501:17)
```

### Versions
I am running ubuntu 15.04

**Comment by 50Wliu** [comment]
What happens if you `script/bootstrap && script/build`?

**Comment by Aakash1312** [comment]
I think I messed up my nodejs installation. I removed node completely and reinstalled. The build worked perfectly.
