### ISSUE TITLE
Exclude VCS Ignored Paths excludes the VCS-controlled files

### ISSUE THREAD

**Issue by amyodov** [atom/atom#12881]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

When the file matches the VCS ignore conditions but is still present in the repository (due to being forcefully added), it is still excluded from the view.
### Steps to Reproduce
1. Create a git repository, add it to Atom project.
2. In Atom, enable the Exclude VCS Ignored Paths.
3. Create a .gitignore file, add some condition.
4. Create a file matching the condition from previous step. Using `git add -f`, add it to the repository.

**Expected behavior:** [What you expected to happen]
The file is displayed in Atom.

The rationale is: all VCS-controlled files are definitely a part of the project; the .gitignore contains the rules what files should not bother me suggesting to add it to the commit; but if I've added it already, it is the part of the project since that moment. Since the moment I've added it via `git add -f`, Git now tracks the changes in that file; whenever the file is changed, its changes are now reflected in the `git status`; that is, from the Git viewpoint, using `git add -f` overrides the .gitignore rule. Atom should behave accordingly to Git.

**Actual behavior:** [What actually happened]
The file is not displayed in Atom.
### Versions

macOS 10.12

~:$ atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

~:$ apm --version 
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.8.4

**Comment by guillochon** [comment]
This is a pretty big issue, I'd love this to be fixed.
