### ISSUE TITLE
Disabling atomic soft tabs does not work on a whitespace-only line

### ISSUE THREAD

**Issue by fcntl** [atom/atom#12884]
### Prerequisites
- [Y] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [Y] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [Y] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [Y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [Y] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [Y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

The "Atomic Soft Tabs" setting cannot be disabled - or more clearly, the checkbox that is on by default can be unselected, but the effect of cursor skipping over soft tabs does not change.
### Steps to Reproduce
1. Ensure that "soft tabs" and "show invisibles" settings are on, and Tab Type is set to auto/soft.
2. Create a new file, and press the tab key to indent.
3. Observe that 4 "dots" appear to represent the tab as four spaces, i.e. a soft tab.
4. move the cursor using the keyboard, and observe if the cursor skips over the spaces as a whole, or allows the cursor to move over each space one by one. Also try and select a middle space using the mouse cursor.

**Expected behavior:** with the 'Atomic Soft Tabs' setting off, I would expect the cursor to be able to select spaces within a soft tab.

**Actual behavior:** the cursor skips over all the spaces, i.e. Atomic Soft Tab behaviour.
### Versions

RHEL7.2

$ atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.5
git 1.8.3.1

**Comment by 50Wliu** [comment]
I cannot reproduce this on Atom 1.12.0-dev-fcddf83, Windows 10 x64.

**Comment by fcntl** [comment]
@50Wliu I can confirm is still a problem with the latest Beta:

$ atom-beta --version
Atom    : 1.11.0-beta5
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

$ apm-beta --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.5
git 1.8.3.1

**Comment by fcntl** [comment]
@50Wliu also a problem for me on Win7x64 and version 1.10.2

**Comment by Ben3eeE** [comment]
Doing some early morning testing on stable it looks like the setting is not respected when the line only contains whitespace.

@fcntl can you confirm that this is the behavior you are seeing? See gif.

![atomic soft tabs](https://cloud.githubusercontent.com/assets/1058982/19141950/06475996-8b9a-11e6-87ba-a9ff2c656229.gif)

**Comment by fcntl** [comment]
@Ben3eeE yes if I follow it with non-space characters, the "atomic" behavior does not happen when the option is switched off.

**Comment by N0r1x** [comment]
I'd like to see if I can fix this (since I have been able to reproduce the bug on both stable and the latest build).
Is there some way I can run atom in debug mode/ a debugger? Not too familiar with any kind of Javascript and certainly not with all the related tools but this bug looks solvable.

**Comment by 50Wliu** [comment]
@N0r1x Set `ATOM_DEV_RESOURCE_PATH` to where you cloned Atom, and then start Atom using `atom --dev`.

**Comment by N0r1x** [comment]
@50Wliu I found out using the dev console that the metadata carried by the tokens that represent the tabs change from 70 to 36 when a non space characters gets inserted, but I haven't been able to find out where they get generated.

**Comment by 50Wliu** [comment]
I don't know, sorry.  Maybe https://github.com/atom/atom/blob/master/src/token-iterator.coffee or https://github.com/atom/atom/blob/master/src/token.coffee?  There's also a few `tokenized-` source files.

**Comment by N0r1x** [comment]
I think I fixed it.

https://github.com/atom/text-buffer/pull/176

**Comment by 50Wliu** [comment]
Looks like this has been fixed.
