### ISSUE TITLE
Using an apostrophe within a <script> tag while writing an HTML pattern breaks syntax highlighting

### ISSUE THREAD

**Issue by dep** [atom/atom#12896]
When using backbone/underscore, I oftentimes need to write HTML within a _script_ tag that will then be rendered as a pattern that underscore can use as a template to execute JS against.

Unfortunately, if my string contains an apostrophe, Atom thinks I'm trying to define a string and will trigger an open-ended syntax highlight event.

Here is a screenshot: http://dl.dpeck.net/1j3q6

Any tips to work around this are greatly appreciates.

**Comment by 50Wliu** [comment]
@dep Is the script type always `text/x-pattern`?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/12896#issuecomment-252071238
Thank you for your issue!

We haven't gotten a response to our questions in our comment [insert URL here]. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
