### ISSUE TITLE
Should warn on unsaved files if restorePreviousWindowsOnStart = true

### ISSUE THREAD

**Issue by fulldecent** [atom/atom#12904]
Test case:

1. Enable `restorePreviousWindowsOnStart` in your configuration (see #10623)
2. Open atom
3. Edit that blank file
4. Quit

Expected outcome

 > Would you like to save changes to this file?

Actual outcome

Atom quits without warning. You lose anything you were working on.

**Comment by stereobooster** [comment]
As of me it doesn't ask for save of new tab (unsaved) independently of `restorePreviousWindowsOnStart`. It should either ask if user want to save it or should show this tab again after window reopened.

**Comment by stereobooster** [comment]
Related https://github.com/atom/atom/pull/6075

**Comment by Ben3eeE** [comment]
@stereobooster that is a different issue https://github.com/atom/atom/issues/10474

**Comment by stereobooster** [comment]
This fixes this problem too https://github.com/atom/atom/pull/12922

**Comment by stereobooster** [comment]
Need to say `restorePreviousWindowsOnStart` feels incomplete without ability to restore sessions with unsaved buffers (but without project folders). I suppose this is not the case for coders, who always start editor from folder with intention to edit project. But people whose intention is taking notes will start application from Dock (so no folder for project is provided). But I see my PR as intermediate solution - it is better than nothing.

**Comment by fulldecent** [comment]
If I do not have a project open, unsaved buffers do not make sense to me.

As a comparison: in Mac OS X 10.7 let you quit Textedit.app without saving. Now in macOS 10.12 you must Save or Don't Save before quitting. I don't know exactly where the change was made. But it was a change Apple conscientiously made.

**Comment by 50Wliu** [comment]
Looks like this was fixed by #12922.
