### ISSUE TITLE
All icons disappeared after update

### ISSUE THREAD

**Issue by mschipperheyn** [atom/atom#12907]
Just updated Atom to 1.10.2 (includes Nuclide, added some other packages in the same update step). And all icons have disappeared. Not a showstopper. But annoying nonetheless.

<img width="580" alt="screen shot 2016-10-07 at 15 31 38" src="https://cloud.githubusercontent.com/assets/384959/19201219/2aee3e2c-8ca3-11e6-9f05-6205d74c654d.png">

**Comment by 50Wliu** [comment]
Please open a new issue and **completely** fill out the provided issue template.  Thanks.
