### ISSUE TITLE
Makefile Box in Markdown not highlighted.

### ISSUE THREAD

**Issue by NicoHood** [atom/atom#12915]
If you have a markdown file (.md) with this content:
```
```makefile
# Compiler flag, 4M flash chip, SS on PB7 (original MP)
C_FLAGS += -DFLASH_CHIP_4M
C_FLAGS += -DFLASH_BIT_SS=PB7 -DFLASH_PORT_SS=PORTB -DFLASH_DDR_SS=DDRB
```.
```

The content is not highlighted, its just green. For example a `cpp` instead of `makefile` highlights the code inside the editor. If you press `ctrl + m` the markdown preview is shown, where the code **is** highlighted. This means markdown is actually supported but for some reason not highlighted in the markdown editor.

Using atom 1.10.2 on archlinux.

**Comment by 50Wliu** [comment]
Please open this on the [language-gfm](https://github.com/atom/language-gfm) repository.  In addition, next time when filing an issue on atom/atom be sure to **completely** fill out the provided issue template or your issue may be closed without further triage.
