### ISSUE TITLE
script\clean twice fails (cannot find module 'fs-extra')

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#12913]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Originally reported to me by @Ben3eeE.  Running `script\clean` twice in a row will fail with `Error: Cannot find module 'fs-extra'` and the usual traceback that occurs with that.
### Steps to Reproduce
1. `script\clean` (make sure it succeeds...doesn't always happen on Windows)
2. `script\clean`
3. `Error: Cannot find module 'fs-extra'`

**Expected behavior:** Usual cleaning output to occur

**Actual behavior:** `Error: Cannot find module 'fs-extra'`
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

This really isn't relevant to this issue, but:

```
Atom    : 1.12.0-dev-9df5253
Electron: 1.4.2
Chrome  : 53.0.2785.113
Node    : 6.5.0
```

I can't log the apm version because of some module version mismatches that I'm trying to solve right now (by cleaning and rebuilding!).

Windows 10 x64.

/cc @nathansobo

**Comment by nathansobo** [comment]
Probably because we're deleting the modules in the first run of the `clean` script.

**Comment by jali** [comment]
I had a similar issue when running executable electron app. 
Worked fine for me when I moved fs-extra package from devDependencies to dependencies.
