### ISSUE TITLE
editor:duplicate-lines should only duplicate once per line with a cursor

### ISSUE THREAD

**Issue by adambutler** [atom/atom#12927]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

`editor:duplicate-lines` should only duplicate at most once per line when using multiple cursors. 

This would allow for easier duplication of many use cased such as duplicating and changing inputs, imports, markdown tables etc.
### Steps to Reproduce
1. Create an empty document
2. Add the following content -
   
   ```
   <input name="foo" id="foo"/>
   ```
3. Highlight either of `foo` texts
4. Press `shift-cmd-D` or whatever your associated keybindings for `editor:duplicate-lines` is.

**Expected behavior:** One new line should be created with both `foo` strings highlighted on the new line.

**Actual behavior:** Two new lines are created with the highlighted `foo` strings being one per line.
### Versions

Running  OS X El Capitan - 10.11.6 (15G31)

```
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.8.0
```

**Comment by Ben3eeE** [comment]
Can you reproduce the problem in safe mode `atom --safe`? In the future please completely fill out the provided issue template.

**Comment by adambutler** [comment]
> Can you reproduce the problem in safe mode atom --safe?

Yes

> In the future please completely fill out the provided issue template.

It's not very obvious that the prerequisites should be included in the issue itself. I figured it would be more of a case of don't open an issue unless you can check each item.

I've updated the description to include the prerequisites section.

**Comment by 50Wliu** [comment]
> It's not very obvious that the prerequisites should be included in the issue itself. I figured it would be more of a case of don't open an issue unless you can check each item.

Thanks for the feedback!  I'll pass it on to the community manager.

**Comment by Ben3eeE** [comment]
Ok, so this is what I can figure out.

When you have a single cursor and select the text, duplicate happens only once:
![duplicate lines 1 selection](https://cloud.githubusercontent.com/assets/1058982/19244276/e1fa4906-8f1b-11e6-9356-47ab1ada7591.gif)

When you select two things duplicate happens twice:
![duplicate lines 2 selections](https://cloud.githubusercontent.com/assets/1058982/19244277/e1fd2f22-8f1b-11e6-9e69-78dce2d61a15.gif)

**Comment by adambutler** [comment]
Correct. I am proposing that line duplication should happen once per line.

The reason for this is I often find myself duplicating a line and then changing it. If I need to change that line in two or more places then this change would increase productivity.

I used the following `<input>` example as a simple & common example of where you might have the same string in two places on one line. I can think of many other examples where typing out the line again would take much longer that duplicating the line and editing it. I think the cursor should be preserved in doing so.

For instance I've been doing a lot of react recently. At the top of most files I've found myself importing in such a way -

```js
import Alpha from 'path/to/some/file/Alpha';
import Bravo from 'path/to/some/file/Bravo';
```

If I want to add `Charlie` & `Delta` to this list I'd want to:

1. Highlight the first Bravo
2. Press Opt-D once to select both Bravos
3. Press Shift-Opt-D to duplicate the line
4. Type `Charlie`
5. Press Shift-Opt-D to duplicate the line
6. Highlight backwards (alt-shift-left)
7. Type `Delta`

Currently if I was to do that this I would end up with surplus lines:

![atom](https://cloud.githubusercontent.com/assets/1238468/19248020/947cab10-8f25-11e6-827b-4639edc00f2e.gif)

By changing duplicate line to be once per line this would give me the correct output.

The problem is only exacerbated when you have even more on the same line such as in this convoluted example where I might want to add back & accept button -

```ruby
<%= link_to "cancel", cancel_path, id: "cancel" class: "button--cancel %>
```

**Comment by Ben3eeE** [comment]
@adambutler Thank you for this report 🙇. Sorry for taking some time to get back with labels. I was unfamiliar with this command and had to ask around. After discussing this we agree that it is a bug.

**Comment by zoo1** [comment]
![multi highlight](https://cloud.githubusercontent.com/assets/4008169/19365307/293148ec-9160-11e6-8626-47fa01aa4f8b.gif)
This also occurs when highlighting multiple items on the same line. @Ben3eeE I'm not sure what the expected behavior is here.

**Comment by Ben3eeE** [comment]
The expected behavior in that case is to only duplicate the line once and have all 3 words selected on the duplicated line.

**Comment by seusher** [comment]
I haven't written CoffeeScript before, but I decided I needed a fix for this, and created a pull request: [](https://github.com/atom/atom/pull/13047 )

My scree capture software (Silentcast) cut off the line numbers, but this gives a demo of the new changes:
![anim](https://cloud.githubusercontent.com/assets/416212/19617148/c19131aa-97dd-11e6-94a9-a25657a7fcb5.gif)

**Comment by Ben3eeE** [comment]
Closed via https://github.com/atom/atom/pull/13602
