### ISSUE TITLE
Separate settings for tab length and indent length

### ISSUE THREAD

**Issue by josh-berry** [atom/atom#12931]
Please split the "Tab Length" setting into "Tab Length" and "Indent Length" settings, where the "Tab Length" setting specifies the visual length of a tab character, and the "Indent Length" specifies the visual length of an indentation (e.g. the number of spaces inserted when pressing the Tab key).

**Rationale**

As an Atom user working at a mid-size software company, I frequently interact with code written by users of other editors, such as Emacs and Vim. Both Emacs and Vim provide separate "Tab Length" and "Indent Length" settings. In Vim, those settings are `tabstop` and `shiftwidth`, respectively. In Emacs, those settings are `tab-width` and `standard-indent`, respectively.

It is standard practice in our codebase to set `tabstop` to 8, and `shiftwidth` to 4. From what I've seen, many open source codebases (especially C and C++ codebases) follow the same convention. In Atom, however, I'm limited to setting both of these values to either 8 or 4, since Atom only provides a single setting for both of these values: "Tab Length".

This is problematic, because when editing other code in Atom, I'm forced to choose between incorrect display of the code, or incorrect indenting behavior.

For example, suppose I set Atom's "Tab Length" setting to 4. Then I open a file which uses 4-space indent and 8-space tabs. I will see code indented like this (example mocked up from my `magic-reflow` Atom package):

``` js
    reflow_lines: function*(lines, state) {
    lines = Array.from(lines);

    if (debug) debug('reflowing:', state, lines);

    // Break the text into blocks, and reflow each block separately.
    for (let i = 0; i < lines.length; ) {
        // Blank lines always break blocks.  We must handle them specially
        // here since they will get swallowed by the rewrap logic otherwise.
        if (is_blank_line(lines[i])) {
        yield lines[i];
        ++i;
        continue;
        }

        let [ni, out_lines] = this.consume_block(lines, i, state);
        if (ni < i + 1) {
        throw `consume didn't advance (from ${i}) target ${ni}`;
        }
        i = ni;
        yield* out_lines;
    }

    if (debug) debug('done reflowing');
    },
```

Alternatively, I could set "Tab Length" to 8, which would cause the code to render correctly, but indentation would behave incorrectly, and I would have to constantly adjust it manually, which very quickly gets annoying.

**Proposal**

I propose the following changes:
- Limit the existing "Tab Length" setting to specify only the visual length (or number of columns) of physical tab characters.
- Add a new "Indent Length" setting, which specifies the visual length of an indentation. This setting is used any time code needs to be indented, to determine how many spaces (or combination of spaces and tabs, if Tab Type is “hard”) to insert.

This should accommodate users (like myself) who work in codebases where the “Tab Length” is different from the “Indent Length”.

**Comment by josh-berry** [comment]
Issue is still relevant -- the setting requested above has not yet been added to Atom.

**Comment by iangoegebuer** [comment]
This issue is still relevant. It is the first hit on Google when the issue is searched.

**Comment by n3ko** [comment]
Same here.

**Comment by tukusejssirs** [comment]
I’ve just found out that setting `indent_size` or `tab_width` to `3` (or any value really) makes the indent/width one more (4).
```bash
# .editorconfig:
# This file is for unifying the coding style for different editors and IDEs
# editorconfig.org
root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = false
indent_style = tab
indent_size = 3

# Show state of .editorconfig:

end_of_line | \n
-- | --
charset | utf8
indent_style | tab
indent_size/ tab_width | 3
insert_final_newline | false
trim_trailing_whitespace | true
max_line_length | auto
```

I use Atom 1.26.0 x64 on Xubuntu 17.10 AMD64.
