### ISSUE TITLE
Unable to install atom latest version in windows 10 pro

### ISSUE THREAD

**Issue by NishantSinghChandel** [atom/atom#12947]
When trying to install it show an error message as shown below
Version 1.11.1
![image](https://cloud.githubusercontent.com/assets/17858766/19291727/91efbbe8-9034-11e6-8cc9-f29be1079c0a.png)

**Comment by lee-dohm** [comment]
Please see the [Atom FAQ](https://discuss.atom.io/c/faq) for the standard Windows installation troubleshooting information:

https://discuss.atom.io/t/having-windows-installation-problems/26498/1
