### ISSUE TITLE
atom fails to open a window in debian 9-prerelease with lxdm/openbox/lxde

### ISSUE THREAD

**Issue by divinity76** [atom/atom#12945]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [?] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

atom fails to open a window in debian 9-prerelease with lxdm/openbox/lxde.
### Steps to Reproduce
1. install atom from the .deb using gdebi
2. try to start atom.

**Expected behavior:** [What you expected to happen]
atom starts up normally.
**Actual behavior:** [What actually happened]
atom never opens a window, hangs indefinitely, strace reveals it's doing an infinite loop of nanosleep({0, 2000001}, NULL); 
and no startup parameters change this (it's the same in --version --safe --profile-startup, it doesn't make any difference.)
### Versions

apm --version relevals:
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12+
git 2.9.3

contradictory to documentation, i can NOT check the atom version by invoking atom --version, because it enters the same nanosleep() loop as a normal invocation, but it should be the latest released version .deb of 2016-10-10 (ISO8601 format) from atom.io 

i'm running debian 9 testing, with lxdm / openbox / lxde, amd64, inside VMWare,

uname -a: 
Linux debian9clean 4.7.0-1-amd64 #1 SMP Debian 4.7.5-1 (2016-09-26) x86_64 GNU/Linux

**Comment by divinity76** [comment]
forgot the strace log, here
[strace.txt](https://github.com/atom/atom/files/522951/strace.txt)

**Comment by lee-dohm** [comment]
Can you reproduce the problem on a released version of Debian?

**Comment by divinity76** [comment]
sigh, yes i can. same problem on debian 8 stable, using lightdm/openbox/LXDE. 
apm --version: 
`apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.9
git 2.1.4
`
uname -a:
`Linux webdevdebian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux`

**Comment by divinity76** [comment]
does it warrant it's own issue? that it doesn't work on debian 8 stable too? in lxde?

**Comment by althaser** [comment]
It's now working fine with version 1.14.0 at least here with GNOME.

**Comment by althaser** [comment]
and now working fine with version 1.16.0 in Debian/stretch :-)

**Comment by divinity76** [comment]
@althaser just to satisfy my curiosity, could you give a little explanation of what the problem was?

**Comment by althaser** [comment]
@divinity76 the atom window opened but you couldn't use it.

I couldn't address the real culprit dependency/issue.

Could you run the atom 1.16.0 in openbox now ?

**Comment by tzot** [comment]
The exact same issue (no window opens, endless nanosleep calls) occurs on xubuntu 16.04 for all electron-based applications I could get my hands on.

**Comment by 50Wliu** [comment]
@tzot Thanks for testing on other Electron applications - based on your findings, it sounds like this is an Electron bug.  Would you mind reporting it upstream to https://github.com/electron/electron?

**Comment by tzot** [comment]
I managed to locate the issue: non-empty /etc/ld.so.preload and failure (inexplicable, but oh well) to load the shared library mentioned there. It's possible that the same issue might happen if LD_PRELOAD is set to some library.
