### ISSUE TITLE
Remember previous window state for multiple fullscreen windows

### ISSUE THREAD

**Issue by jamesstidard** [atom/atom#12956]
Hi,

I use Atom for developing multiple micro services so will have at least 3 projects open at a time - which I usually keep in fullscreen mode on macOS. When I cmd-q and quit Atom, then reopen Atom, all the previous windows will be opened but only one of them will be in full screen and the rest will be dumped onto the main desktop. Here's two images of before and after quitting and reopening Atom.

<img width="1280" alt="screen shot 2016-10-12 at 10 08 19 am" src="https://cloud.githubusercontent.com/assets/1797906/19304465/b263e860-9064-11e6-8909-19b76fa31b82.png">
<img width="1280" alt="screen shot 2016-10-12 at 10 08 51 am" src="https://cloud.githubusercontent.com/assets/1797906/19304468/b41b45ae-9064-11e6-8da3-fe970d674ade.png">

Is this something that is possible to implement? If I can be pointed in the right direction I would be happy to see if I can scratch my own itch and submit a pull request.

Bonus points: remembering the order of the windows - don't know if that's posible.

Thanks

**Comment by EmilVarona** [comment]
I'm seeing a different but (possibly) related issue. I have atom running on a large external monitor which is my second screen. When I restart atom, the window always returns to my primary screen (laptop display).

**Comment by shtirlic** [comment]
@EmilVarona same problem for me, I am also have Atom running on external monitor and always after Atom (packages) updates/restart all windows returns the my macbook primary screen

**Comment by emilyaviva** [comment]
Same problem here. Atom always starts on the primary display with the Dock, even though I always move it and use it on my secondary display, and close it from that display. I wonder if this is an Atom issue specifically, or some kind of larger Electron issue.

**Comment by emilyaviva** [comment]
This issue still persists. Atom 1.27.0, macOS High Sierra 10.13.4. When I open Atom, it always opens on my "primary" display, and does not remember the window state across multiple monitors. If, as in the video shown below, I open Atom and then move it to the big (secondary) display, and then I quit Atom and reopen, it reopens on the small (primary) display.

https://emilyaviva.com/files/AtomWindowScreenBehavior.m4v
