### ISSUE TITLE
Save open documents on crash

### ISSUE THREAD

**Issue by mschipperheyn** [atom/atom#12959]
Atom crashes a whole lot. Happens to me at least once every two days. A nice feature that LibreOffice and some other text editors have is that it saves any unsaved open documents either directly or as a temporary file to be reopened on restart. This might save people from losing info on a frequent basis.

One thing that I notice is that when Atom crashes, it's actually the open window that crashes not the entire program. So, this abstraction would be a nice place to put that functionality

**Comment by 50Wliu** [comment]
Check out the `~.atom/recovery` folder.  Atom also notified you about recovered files after it opens after a crash.

**Comment by mschipperheyn** [comment]
Ok, hmm this doesn't happen when a window crashes and you open a new window. I guess you have to restart atom to get this functionality? Not sure I saw that either. Maybe this is only available on a full Atom crash and not on a window crash?
