### ISSUE TITLE
Fullscreen window opens new window on top of parent

### ISSUE THREAD

**Issue by jamesstidard** [atom/atom#12957]
Atom: 1.12.0-beta0 & 1.11.1
OS: macOS Sierra

I'm not sure if this is an Electron or an Atom issue - I initially posted it on Electron and was ask to repost here and see if it could be reproduced with the latest Electron build.

Since upgrading to macOS Sierra, opening new windows while in fullscreen mode will open the new window on top of the current fullscreened window. This didn't use to happen and I assume was something to do with how macOS have changed their window management API to allow tabs in apps.

Here's a screenshot which will hopefully make more sense:
<img width="1280" alt="screen shot 2016-10-12 at 9 36 54 am" src="https://cloud.githubusercontent.com/assets/1797906/19304619/581ef9f2-9065-11e6-87b6-715b7b83eef4.png">

Steps to reproduce:
1: open Atom
2: fullscreen application with the green button on the menu bar
3: open new window with cmd-shift-n or File > New Window

**Comment by robbawebba** [comment]
Hi @JamesStidard 
Just to clarify, you are referring to the fact that the newly created window is also not full-screen?

**Comment by JamesStidard** [comment]
Hi @robbawebba 
Yeah it should also make a new space and become full screen. I think that's the normal behaviour you'd expect in macOS. Is that what you're after?

**Comment by robbawebba** [comment]
@JamesStidard Yeah! I cannot speak for OSX because I am using Windows 10, but the behavior you are looking for seems like it should be the correct way.
