### ISSUE TITLE
Enabling setting 'Use Custom Title Bar' prevents double click on title bar from maximizing window

### ISSUE THREAD

**Issue by zcdunn** [atom/atom#12968]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

When the 'Use Custom Title Bar' setting is enabled, double clicking on the title bar doesn't enlarge the window on OS X Yosemite
### Steps to Reproduce
1. Enable Settings->Core->'Use Custom Title Bar' setting
2. Restart Atom for setting to take effect
3. Double click the title bar

**Expected behavior:** [What you expected to happen]
The window should enlarge to fill the screen

**Actual behavior:** [What actually happened]
No effect.
### Versions

Atom: 1.11.1
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0
OS X Yosemite 10.10.5

**Comment by simurai** [comment]
Double-click support got added with https://github.com/atom/atom/pull/12327
