### ISSUE TITLE
Atom 1.12-Beta1 :atom.project.relativizePath behaviour changed.

### ISSUE THREAD

**Issue by gandm** [atom/atom#12965]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

In versions 1.11 and prior a call to atom.project.relativizePath would result in an array with array[0] being the project path and array[1] being the relative file path.

In version 1.12-beta1 the call returns array[0] null and array[1] the full path/filename. No project path

### Steps to Reproduce

Given a file that exists inside a project call `atom.projectRelativizePath(filename)`

![image](https://cloud.githubusercontent.com/assets/2313237/19344481/469e1456-9132-11e6-9ffc-c22a3aa096e1.png)

**Expected behavior:** [What you expected to happen]
![image](https://cloud.githubusercontent.com/assets/2313237/19344233/459e487e-9131-11e6-9d21-58a22fe2cee7.png)

**Actual behavior:** [What actually happened]
![image](https://cloud.githubusercontent.com/assets/2313237/19344129/ec6aea96-9130-11e6-8720-a67b6243a540.png)

### Versions

Windows 10
atom 1.12-Beta1

**Comment by thomasjo** [comment]
What's the output of `atom.project.getPaths()` in both those cases?

**Comment by gandm** [comment]
Interesting. Its a spec I'm running and I setPaths before testing and it appears it's setPaths at issue!
Atom 1.11.0
![image](https://cloud.githubusercontent.com/assets/2313237/19346050/546140fc-9139-11e6-9119-cab241e514ee.png)

Atom 1.12.1-beta1
![image](https://cloud.githubusercontent.com/assets/2313237/19346079/7b42d56e-9139-11e6-9e74-5d743c8b2502.png)

**Comment by gandm** [comment]
OK it's this commit https://github.com/atom/atom/commit/fe480d8fa4b5c980477c75598584d3a9de2f3309
I'll have to use temp fs and rework the specs!
