### ISSUE TITLE
Spacebar broken in beta

### ISSUE THREAD

**Issue by DavidLGoldberg** [atom/atom#12960]
### Prerequisites

Atom beta

### Description

The space bar is not resolving with key resolver for my package jumpy + vim-mode.

### Steps to Reproduce

1. Open editor with vim-mode on
2. press the space bar

**Expected behavior:**
The cursor should progress

**Actual behavior:** [What actually happened]
Key resolver says no key press being passed to the package / commands

### Versions
Atom 1.12.0-beta0
Mac OS 10.11.6

I have created an issue with vim-mode as well:
https://github.com/atom/vim-mode/issues/1071
But I believe this is more of an issue with atom core, as the key resolver doesn't show anything for vim-mode nor my package.  Did the key for the keymap change perhaps?

**Comment by t9md** [comment]
https://github.com/atom/atom/issues/12953

**Comment by lee-dohm** [comment]
Thanks @t9md for linking the duplicate Issue!

**Comment by DavidLGoldberg** [comment]
oops sorry guys.  I must have missed it :(
