### ISSUE TITLE
Replace  'native' menu with HTML5 version

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#12961]
Since Native top file menubar looks really ugly and quite most of us just hide it , why not remove it totally and re implement own one with html5 ?

Why not :)

**Comment by thomasjo** [comment]
This seems like a fairly big undertaking with little tangible benefit. I'm personally 👎 on this.

**Comment by damieng** [comment]
I'd much rather we work on getting the menu we have more Windows-native (via Electron) than start again trying to do it all in HTML5.

**Comment by v3ss0n** [comment]
No not windows native. Since atom is cross platform. why whould native `MSWidndows` stlying got to do with atom.

Why would HTML5 menu is so difficult either ?Would like to give a try but with so much negatives thumbdowns here.

Advantage is look and feel , can also be themed easily .

**Comment by damieng** [comment]
Users of each operating system have certain expectations of how an application behaves on their system.

While a few Windows apps do their own menu and theming this would be a complete non-starter on macOS where every application uses the standard OS menu.

**Comment by v3ss0n** [comment]
but whats the point if it look too different from the current chosen theme?

**Comment by damieng** [comment]
While some people might like it themed most users would find it incredibly jarring and then there is no way we can give them the native-like experience they want.

I can only think of one Windows application that even attempts to render it's own menu and that is Steam. The result is awful and it doesn't support keyboard accessibility.

**Comment by lee-dohm** [comment]
The idea behind Electron and Atom is not to deliver the web experience to the end user. They already have that in their browser. The inspiration of Atom and Electron is to take the technologies, the flexibility and the power of the web and allow people to write, as much as possible, native applications with those technologies. The Atom maintainers want Atom to work more like a native application, not less. This proposed change would take us in the wrong direction. After discussing with the team, we aren't interested in taking this on.

Thank you very much for your continuing interest in Atom and the flow of ideas you offer us :grinning:

**Comment by v3ss0n** [comment]
meh! But an addon that mirroring all the menu functions will be interesting. i am gonna look into it :laughing:
