### ISSUE TITLE
1.12.0-beta1 breaks palette on Fedora

### ISSUE THREAD

**Issue by quasipedia** [atom/atom#12969]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

Yes, it manifests itself in a different way, but the error - I believe - is the same.

* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?

This bug refers to version 1.12.0-beta1, I compared the bug to the latest (non-buggy) 1.11.1 version

* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Version 1.12.0-beta1 seems to have the command palette (CTRL-SHIFT-P) and the symbol palette (CTRL-P) broken for my system (Fedora 24 64bits)

### Steps to Reproduce

1. Install atom-beta
2. Run `atom-beta .`
3. Try to press CTRL-P or CTRL-SHIFT-P
4. **Nothing happens**
5. Run `atom-beta . --safe`
6. Try to press CTRL-P
7. **You get a `No symbols found` message**
8. Try to press CTRL-SHIFT-P
9. **You get a `Project has no tags file or it is empty`**
10. Try to perform the same tests with `atom .` and `atom . --safe` do not cause any issue (everything wors)

**Expected behavior:** [What you expected to happen]

See above: file or command palettes should be displayed.

**Actual behavior:** [What actually happened]

Nothing shows in regular mode, errors get displayed in safe mode

### Versions

Atom    : 1.12.0-beta1
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4
Fedora 24 64 bit, wokstation

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by quasipedia** [comment]
Other useful information (maybe):

  - The keybinding resolver display the correct binding
  - My keyboard layout is `colemak-UK-gb` (I'm mentioning this because I saw this pre-release had "Substitute U.S. layout equivalents for non-Latin characters in all cases, not just when combined with modifier keys. Fixes vim-style bindings on non-Latin keyboards."

**Comment by Ben3eeE** [comment]
When you say it shows an error do you mean the command palette opens but doesn't work? We are having trouble with the keymaps on Linux in the 1.12 beta see: https://github.com/atom/atom/issues/12951

**Comment by quasipedia** [comment]
Yes, the palette widget opens, but instead of having a list of files/commands it displays the error messages that I reported above.

**Comment by quasipedia** [comment]
Reading #12951 I would say - in fact - my symptom is a side effect of it.  Mark is as duplicate, maybe?
