### ISSUE TITLE
Remember syntax for opened files or improve auto detect

### ISSUE THREAD

**Issue by BramVanroy** [atom/atom#12966]
Perl and Prolog annoyingly share the `.pl` extension. This ambivalence throws Atom into a dilemma when auto-detecting the syntax of a file. I often use Prolog and Perl files at the same time or interchangeably and more often then not files get opened with the wrong syntax highlighting. When opening a file for the first time, that is not an issue: Atom tried to detect the correct syntax, and perhaps it failed - but I can always manually switch to the correct syntax. The problem is that this issue recurs every single time I open a `.pl` file. What I mean is, if for `file-a.pl` Atom guessed Prolog and I change the syntax to Perl, then close the file, and open it again, Atom will - again - guess Prolog. I guess you understand my frustration.

As I see it there are at least two ways to solve this issue:
### 1. Remember the syntax per file

As soon as you open `file-a.pl` Atom could write to a CFG file somewhere that `path/to/file-a.pl` is auto-detected as Prolog. If the user then changes the syntax to Perl, the changes would be made in the CFG file as well. When closing and re-opening the file, Atom would check the CFG file to see if an entry with that file name is present and use the given syntax.

The downside is that if you are working with a lot of files, this CFG file can grow significantly. Therefore it might be useful to have a check of the CFG at Atom start-up where entries older than e.g. a week are removed from the file, or that the oldest entries are removed when the CFG file reaches a size of > X KB.
### 2. Improve auto-detection

This might be the easiest to implement, though I cannot find it in the source after briefly glancing. (I don't have a lot of time, and when I couldn't find it I wrote this post.) In this particular case, it should be easy to distinguish Perl. Often it's right there in the first line:

`#!/usr/bin/perl`

But doing a regex check on the first line for this specific issue should only be a quick fix. I like the first idea more.

**Comment by PaulKlumpp** [comment]
+1
