### ISSUE TITLE
Unable to build Atom from source

### ISSUE THREAD

**Issue by vanarieleyen** [atom/atom#12976]
### Description

After failing to install Atom from an added repository I decided to follow the instructions on the Atom website to build a 32 bit version, but that also failed.

### Steps to Reproduce

1. Download the source from git:
        git clone https://github.com/atom/atom
2. cd atom
3. script/build

The build took about an hour with the following result:

aevl@aevl-1015PX:~/atom$ script/build
Node:	v4.2.6
Npm:	v3.5.2
Installing script dependencies
Installing apm
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:544:26)
/home/aevl/atom/apm/node_modules/atom-package-manager/bin/apm: line 35: /home/aevl/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory
child_process.js:487
    throw err;
    ^

Error: Command failed: /home/aevl/atom/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:464:13)
    at Object.execFileSync (child_process.js:484:13)
    at module.exports (/home/aevl/atom/script/lib/install-atom-dependencies.js:19:16)
    at Object.<anonymous> (/home/aevl/atom/script/bootstrap:28:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
 --------------------------------------------------------------------------------------------------------

I compile it on a fresh install of Ubuntu Xenial 16.04.1 which is running on an Asus notebook with 4GB memory, 32 bit processor

**Comment by seusher** [comment]
This doesn't repro on a fresh install of Ubuntu 16.04 64bit install, and doesn't look to be an architecture-specific error.

I used the recommended steps to set up my Ubuntu machine from: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md 

seusher@laptop:~/Documents/git/atom$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

seusher@laptop:~/Documents/git/atom$ script/build 
Node:	v4.4.7
Npm:	v3.10.9
Installing script dependencies
Installing apm
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:25:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
../src/onig-string.cc: In constructor ‘OnigString::OnigString(v8::Local<v8::String>)’:
../src/onig-string.cc:25:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   hasMultiByteChars = (value->Length() != utf8_length_);
                                        ^
Installing modules ✓
Installing atom-dark-syntax@0.28.0 ✓
Installing atom-dark-ui@0.53.0 ✓
......
......

**Comment by vanarieleyen** [comment]
But I am not compiling for a 64 bit system. My Ubuntu is 16.04.1 Xenial 32 bit, perhaps that causes the problems.

**Comment by Nikki1993** [comment]
Having same error as the original message on APM install. Running latest Node 7.0.0 macOS 10.12.1

**Comment by 50Wliu** [comment]
Use Node 6 for the time being.  The x64/x32 architecture issue has already been fixed.
