### ISSUE TITLE
Building Atom on 32bit Ubuntu 14.04 results in 64bit binary

### ISSUE THREAD

**Issue by hotice** [atom/atom#12972]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

Not applicable.

* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Trying to build the latest Atom 1.11.1 in Ubuntu 14.04 32bit results in a 64bit binary being created:
```
andrei@andrei-desktop:~/atom-1.11.1/out/atom-1.11.1-i386$ readelf -a -W atom | grep Class: | sort | uniq
  Class:                             ELF64
```
As you can see, even the atom executable path has "i386" in its name, but the executable is for 64bit. The machine is 32bit:
```
$ uname -a
Linux andrei-desktop 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:08:14 UTC 2014 i686 i686 i686 GNU/Linux
```
And:
```
$  node -e "console.log(process.arch)" 
ia32
```

The previous Atom version I was able to build properly on 32bit was 1.10.2 (I didn't try 1.11.0 or 1.12 beta).

Here is the build log: http://pastebin.com/raw/WgywYX72

### Steps to Reproduce

1. Using Ubuntu 14.04 32bit, install nodejs v6 from its [official Ubuntu/Debian repository](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions). I was also able to reproduce this with nodejs v4 from the its official repository and npm v3 installed manually (installing the nodejs v4 package provides npm v2, and Atom 1.11.1 refuses to build with npm older than v3; this was not the case for Atom 1.10.2).

2. Download Atom 1.11.1 and build it with ``script/build``

**Expected behavior:** Atom should be built for 32bit.
**Actual behavior:** Atom is built for 64bit.
### Versions

Tested on two Ubuntu 14.04 32bit machines. Atom version: 1.11.1 (latest stable).

I'm not sure if these are required in this case but anyway:
```
$ atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

```
$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.6
git 1.9.1
```

**Comment by 50Wliu** [comment]
@nathansobo Possibly a problem with the new build scripts?  1.10 was the last version that worked and also the last version with the old build scripts.

**Comment by nathansobo** [comment]
Possibly. I can't spend time on this right now but if someone wants to investigate I will look at a PR.

**Comment by i-svr** [comment]
[logs.txt](https://github.com/atom/atom/files/557060/logs.txt)
I can confirm the issue. It is impossible to build Atom 1.11.2 from sources on Slackware x32-bit.
Also, this error in Atom's installation scripts was present in Atom's 1.10.2 sources, but i didn't bother to report (decided to install 1.10.0 version using sbopkg instead).

During compilation from sources process, i noticed a string in console:
**Downloading electron-v0.37.8-linux-x64.zip**

But I'm using **x32-bit** operating system!
There is an error in installation scripts.

PS: logs attached.

**Comment by Ben3eeE** [comment]
@i-svr If you want you can test the PR that fixes this issue https://github.com/atom/atom/issues/13001

**Comment by hotice** [comment]
That fixes it for me on Ubuntu 32bit!
