### ISSUE TITLE
Unable to install Atom 32 bit in Ubuntu Xenial 16.04.1 LTS

### ISSUE THREAD

**Issue by vanarieleyen** [atom/atom#12975]
### Description

I want to install Atom on a 32 bit notebook but unfortunately it is not available.
I found a repository (sudo add-apt-repository ppa:webupd8team/atom) that should be able to install the 32 bit version of Atom but that failed.

### Steps to Reproduce

1.  add repository:
       sudo add-apt-repository ppa:webupd8team/atom
2. update:
       sudo apt-get update
3. install:
       sudo apt-get install atom

Result:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 atom : Depends: gvfs-bin but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

--------------------------------------------------------------------------------------------------

Ubuntu Xenial 16.04.1

**Comment by Ben3eeE** [comment]
[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll be able to find answers faster.
