### ISSUE TITLE
Recent files list in Mac dock icon is too long

### ISSUE THREAD

**Issue by motjuste** [atom/atom#12997]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

The recent files list displayed when the dock icon is right-clicked on Mac is too long and noisy to be useable, IMO. The files are often from unrelated projects, and if they have the same name, there is no hint which project they belong to.

![screen shot 2016-10-16 at 11 06 27](https://cloud.githubusercontent.com/assets/5238256/19416444/c7fbc43e-9390-11e6-83dd-f017760f1391.png)
### Steps to Reproduce
1. Use Atom with many files.
2. Have at least one Atom window open.
3. Right Click on the Mac dock icon

**Expected behavior:** 
- A sensibly long list. I am not qualified to suggest the appropriate length. 
- Or at least with some context, maybe grouped based on project name, or, sorted, or .... organized in some way.
- A way to clear the list

**Actual behavior:** 
- A very long list, from unrelated projects, with no easy way to clear it.
### Versions

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
apm  1.12.5
npm  3.10.5
node 4.4.5
python 3.4.5
git 2.7.4

**Comment by andyrichardson** [comment]
This seems like a valid issue. Can you find any examples of other apps that use a `right-click -> recents` functionality and, if so, what do they typically set their recent file limit to?

The implementation of the `right-click -> recents` is done through Electron ([see here](https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md#recent-documents-windows--macos)) and would require modifications in order to set a limit. We can go ahead and open an issue there, requesting the functionality, if limiting recents is a common practice in desktop applications.

**Comment by Ben3eeE** [comment]
Refs https://github.com/atom/atom/issues/10845

**Comment by motjuste** [comment]
Can confirm that the length of the list of recent files can be controlled from `System Preferences > General > Recent Items [dropdown]` (as shared in #10845, mine was set to 50). I guess the precedence set by the OS should be followed here, as far as the length of the list is concerned.

However, there is still no easy way I could find to clear the recents list in Atom. 

Preview, VLC, Quick Time, Audacity, Xcode, MacVim, etc. have `File > Open Recent > Clear Menu` in the menu bar. Clicking that clears the recents list in the dock menu as well.

I am guessing adding a similar option to Atom's menu bar would be possible without changes in Electron.

![screen shot 2016-10-16 at 20 31 03](https://cloud.githubusercontent.com/assets/5238256/19419862/87c501be-93e0-11e6-8438-9aa4588d411c.png)

**Comment by starriv** [comment]
My situation is like that, feel this bug still exists
the recent documents on the dock can not be cleared in any way( file -> open recent -> clear menu  this way is invalid) 
platform: macOS sierra 10.12.3
atom version: 1.15.0 x64
（ps: This problem has been a long time
<img width="159" alt="qq20170321-185306 2x" src="https://cloud.githubusercontent.com/assets/7098001/24144448/37ef0c18-0e68-11e7-9abb-5d7a1d72ba07.png">

**Comment by motjuste** [comment]
Closing because all my suggestions have one or other solution implemented now.
