### ISSUE TITLE
Icon looks bad on GNOME

### ISSUE THREAD

**Issue by johnmuhl** [atom/atom#12993]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

The Atom icon looks bad on GNOME. On KDE and Unity the icon looks as expected.

![atom-icon-switcher](https://cloud.githubusercontent.com/assets/7944/19411002/8fdcbb3a-92be-11e6-9b31-1a8233a9b92a.png)
![atom-icon-topbar](https://cloud.githubusercontent.com/assets/7944/19411004/8fe250ea-92be-11e6-91be-6a37a137d644.png)
![emacs-icon-topbar](https://cloud.githubusercontent.com/assets/7944/19411003/8fdddfec-92be-11e6-86d6-a9394033916e.png)

(Make sure to view images at 100% to see the problem)
### Versions

``` bash
$ atom-beta --version
Atom    : 1.12.0-beta1
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

$ apm-beta --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.1

$ gnome-shell --version
GNOME Shell 3.22.0
```

**Comment by arcticicestudio** [comment]
May be related to GNOME 3.22 which uses the Wayland session as default now. Have you tried to reproduce it in an X11 environment?

**Comment by johnmuhl** [comment]
It looks the same in an X11 session. The icon in the activities overview screen looks as expected.

![atom-icon-](https://cloud.githubusercontent.com/assets/7944/19412785/bb6a5400-92e2-11e6-969c-afb542a85d8c.png)

**Comment by minweidong** [comment]
-what
    well

**Comment by minweidong** [comment]
- what
   well

**Comment by minweidong** [comment]
- what  
well

**Comment by minweidong** [comment]
-whar  
fsdhfkjhdskjfdgdf

**Comment by minweidong** [comment]
- dsf  
dsjfljsdl

**Comment by MoritzKn** [comment]
This seams to be a scaling issue caused by the fact that the atom desktop file only includes one icon in the resolution of 1024x1024px.

**Comment by MoritzKn** [comment]
Ok, my above comment only applies if atom is build from source, is that the case?

**Comment by daviwil** [comment]
Just saw this issue while reviewing @MoritzKn's PR.  I don't see this issue with Atom icons in Gnome 3.26.2 after installing Atom from the official .rpm package (I'm on Fedora).  Here's a screenshot: 

![image](https://user-images.githubusercontent.com/79405/34748344-ea52976a-f550-11e7-9341-e5603e4f3f3d.png)

@johnmuhl can you verify whether you still see this problem?  Thanks!

**Comment by 50Wliu** [comment]
@daviwil I think @johnmuhl said that the icons in the overview screen work as expected?  His other screenshots show the issue.

**Comment by daviwil** [comment]
My bad, misunderstood.  Looks fine for me in the panel too:

![image](https://user-images.githubusercontent.com/79405/34749135-a5168c66-f554-11e7-974a-e6d19555a222.png)

**Comment by daviwil** [comment]
Caveat, I'm using a HIDPI display, dunno if maybe that has something to do with it.

**Comment by johnmuhl** [comment]
Yeah the latest beta still looks like garbage on my lofi monitor and GNOME 3.24.3.

**Comment by daviwil** [comment]
I'll reopen this because I think it's worth looking into.  We definitely don't want Atom's icons looking like crap on Linux :)
