### ISSUE TITLE
[proposal] Improve scrollbar behavior with infinite edges

### ISSUE THREAD

**Issue by tiborsaas** [atom/atom#12998]
### Prerequisites

* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

I've just installed Atom and the current scrollbar implementation is very frustrating. If I want to scroll with my touchpad, I have to target the scrollbar explicitly, instead of just dragging the cursor to the rightmost edge and drag the code down.

This is a human-computer interface antipattern.

Please read this: http://particletree.com/features/visualizing-fittss-law/ especially the section "Rule of the Infinite Edge"

I could just repeat everything that the article says. For a text editor where I can spend most of my time during the day, this should be a no brainier to implement.

**Comment by rumpelsepp** [comment]
Not directly related to your proposal, but a nice workaround may be the [minimap](https://atom.io/packages/minimap). I always scroll my code by moving the white window on the minimap. That feels good for me.

**Comment by 50Wliu** [comment]
> instead of just dragging the cursor to the rightmost edge and drag the code down.

Can you elaborate on this?  I'm not sure I'm following.  Can you show some pictures/gifs?

**Comment by tiborsaas** [comment]
Here you go:

![problem](https://cloud.githubusercontent.com/assets/342688/19445457/a1ca7008-9494-11e6-8bcb-1bae5ab327cf.gif)

Dragging the scrollbar shouldn't be a precise, well coordinated action.

**Comment by 50Wliu** [comment]
Gotcha, thanks.  That makes sense.  /cc @simurai

**Comment by Ben3eeE** [comment]
I don't have that empty space between the edge of the pane and the scrollbar. What theme are you using? Just to be sure can you check https://discuss.atom.io/t/where-did-this-empty-space-come-from-how-do-i-get-rid-of-it/30226 to see that this is not why you have that empty space? How does it work after this?

**Comment by tiborsaas** [comment]
I'm using the default one that comes with Atom, "One Dark".

I changed to "atom dark" and the scrollbar now appears to be 1px from the right border, but I still can't use it while my cursor dragged 100% to the right. 

![x](https://cloud.githubusercontent.com/assets/342688/19454369/2b7d8bf4-94b9-11e6-9da5-0d8a4ace79d1.gif)

That discussion looks like a different issue to me.

**Comment by Ben3eeE** [comment]
Ah, true there seems to be a 1px gap. I have the 1px gap with both `One dark` and `Atom dark`. Just making sure 😊

**Comment by tiborsaas** [comment]
Update: Atom dark theme's scrollbar works when I'm in the main code editor view.

**Comment by simurai** [comment]
For the One theme, you can remove the extra space around the editor by switching to `compact` mode in the [theme settings](https://github.com/atom/one-dark-ui#settings). But there is still a `1px` border. I'll look into it if it can be removed.

**Comment by simurai** [comment]
This should be fixed for the One themes in Atom `1.13`.
