### ISSUE TITLE
Package search doesn't work

### ISSUE THREAD

**Issue by tiborsaas** [atom/atom#12999]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [#] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

I wanted to search packages, but I got this strange error
![3a27c350-93b4-11e6-9748-c3f382cce0a9](https://cloud.githubusercontent.com/assets/342688/19417827/d9ac8ddc-93b6-11e6-9a67-6423cea8ea09.png)

### Steps to Reproduce

1. See the screenshot, it says all

**Expected behavior:** [What you expected to happen]
I wanted to search packages with a keyword

**Actual behavior:** [What actually happened]
I got an error :)

### Versions
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by tiborsaas** [comment]
Yeah, but I kinda like it. Why does it interfere with Atom at all?

**Comment by Ingramz** [comment]
@tiborsaas by any chance, are you using quotes in your system path? that could what's causing it.

Found from https://github.com/atom/settings-view/issues/847

**Comment by tiborsaas** [comment]
I removed ConEmu from the PATH and it seems to be solved, 

However...
![image](https://cloud.githubusercontent.com/assets/342688/19437785/32e8e3da-9477-11e6-9634-82c733978885.png)

The bug is with the `Program files (x86)\whatever` folder name.

**Comment by 50Wliu** [comment]
This has been fixed in apm (https://github.com/atom/apm/commit/fa84f2693b22630e5125dcea10004300d00cdd75) but hasn't made it in Atom yet.
