### ISSUE TITLE
How to disable font smoothing?

### ISSUE THREAD

**Issue by zii** [atom/atom#13000]
I feel that the font is a little blurry in Atom. Let's open a pure txt code file, and compare with Chrome. Set font-size=12px, font-family=monospace.
http://www.cs.dartmouth.edu/~doug/aqsort.c

In chrome:
![image](https://cloud.githubusercontent.com/assets/81924/19419815/0624fe48-9412-11e6-8985-37ebb0993839.png)

In Atom 1.12.0-beta2, with same font:
![image](https://cloud.githubusercontent.com/assets/81924/19419848/9cadb85a-9412-11e6-8223-b91315c23b26.png)

Zoom into:
![image](https://cloud.githubusercontent.com/assets/81924/19419922/cbba3d52-9413-11e6-908c-6cbc788104cc.png)

Help me to disable the Anti-Aliasing please!

**Comment by larsenwork** [comment]
Try this In your stylesheet (under "Atom" in the menu)
```
*, .comment {
  -webkit-font-smoothing: antialiased;
}
```

**Comment by dustindowell22** [comment]
@zii I believe @larsenwork meant to say `none` not `antialiased`.

Also, no reason to use the `*` selector here, `atom-workspace` will do fine.

```
atom-workspace {
  -webkit-font-smoothing: none;
}
```

**Comment by v3ss0n** [comment]
please use forum for this kind of questions :
https://discuss.atom.io
We had a thread with detail info about this on the forum.

**Comment by 50Wliu** [comment]
Thanks @v3ss0n.  Please use the issue tracker only for enhancements or bugs, not for questions.

**Comment by zii** [comment]
@dustindowell22 Thank you, but still no effect on my windows 7.
