### ISSUE TITLE
The tabs get resized when mouse hover.

### ISSUE THREAD

**Issue by alexis57** [atom/atom#13005]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
The problem is not present.
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

The tabs get resize when the mouse is over them. If I click, the length is changing more...

### Steps to Reproduce

1. Just open a folder with many files in tabs.
2. Go with your mouse on them.

**Expected behavior:** Tab's length does not change because the cross for closing tab moves too.

**Actual behavior:** Tab's length is moving.

### Versions

CentOS 7 
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Thank you.

**Comment by Ben3eeE** [comment]
Since the problem is not present in safe mode this indicates that there is a problem with one of your installed community packages. Try disabling packages until the problem disappears and report the issue to that packages repository.
