### ISSUE TITLE
Update takes too long: 30 minutes from 1.9.8 to 1.11.1

### ISSUE THREAD

**Issue by mrdc** [atom/atom#13013]
### Description

Update takes too long: 30 minutes from 1.9.8 to 1.11.1 and consumes more than 400mb of traffic.
### Steps to Reproduce
1. Start Atom 1.9.8
2. Go to About
3. Press Check now

**Expected behavior:** 
The latest version should be downloaded and it should happen once not in a circle.

**Actual behavior:** 
atom-1._._-delta.nupkg files were downloaded, then after delta updates were not successful atom-1.11.1-full.nupkg was downloaded.

Please, check attached log for details:
[atom-update.zip](https://github.com/atom/atom/files/534716/atom-update.zip)

**Comment by MarshallOfSound** [comment]
The one line that matters in the Squirrel log is this one

> 2016-10-17 23:56:55> Program: Failed to apply updates, falling back to full updates: System.IO.EndOfStreamException: BZip2 input stream end of compressed stream

Which is the same issue that was reported upstream at Squirrel/Squirrel.Windows/issues/832

Possibly an incomplete download, or something went wrong on the network somewhere that resulted in an incomplete delta package

**Comment by mrdc** [comment]
> Possibly an incomplete download, or something went wrong on the network somewhere that resulted in 
> an incomplete delta package
Several delta packages were downloaded (actually all from 1.9.9 to 1.11.1) and non of them worked - that's strange. 
Wouldn't even notice it, but for 30 mins my laptop was spinning it's fan like crazy, so I've decided to have a look :)

**Comment by damieng** [comment]
Given this looks like a network/download issue of some sort and there have been no other reports (yet) I'm going to close this issue.  If anyone runs into similar issues please comment here and we'll re-open.
