### ISSUE TITLE
atom startup issue

### ISSUE THREAD

**Issue by tommygebru** [atom/atom#13012]
**Expected behavior:** 
I open Atom app, it opens one window, Only.

**Actual behavior:** 
I am a mac user, when I click on Atom.app or double-click to open the application, it may take a while or lag, but I often double-click just "to-be-sure". Most often what happens next is that my computer freezes because the editor is forcing many windows to open and run at the same time. I understand it is a mistake, and that I only need one window.
However is there a way to make sure that only 1 window is forced open?

Atom version 1.11.1

**Comment by damieng** [comment]
Rather than treating the symptom here we are working on various improvements for start-up in general. You can keep an eye on https://github.com/atom/atom/issues/13253 for details of progress so far.
