### ISSUE TITLE
希望能支持像sublime一样的全项目跳转功能，我用的Python语言开发

### ISSUE THREAD

**Issue by Samoyedsun** [atom/atom#13027]

**Comment by 50Wliu** [comment]
下次，请用英文。这样子，别的人也可以帮助您。这个问题最好适合https://discuss.atom.io。谢谢！
***
Next time, please use English.  This way, others can help you as well.  This question is best suited for https://discuss.atom.io.  Thanks!

**Comment by Samoyedsun** [comment]
I hope to support the same project as sublime jump function, I use the Python language development
