### ISSUE TITLE
TextEditor.reloadGrammar() references non-existing TokenizedBuffer.reloadGrammar() method

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#13022]
Here's what I get in console:

```
Uncaught (in promise) TypeError: this.tokenizedBuffer.reloadGrammar is not a function(…)
module.exports.TextEditor.reloadGrammar @ text-editor.coffee:3024
(anonymous function) @ init.coffee:5
module.exports.Emitter.simpleDispatch @ .../resources/app.asar/node_modules/event-kit/lib/emitter.js:25
module.exports.Emitter.emit @ .../resources/app.asar/node_modules/event-kit/lib/emitter.js:129
(anonymous function) @ package-manager.coffee:457
```

**Comment by lierdakil** [comment]
Addenum:
`TokenizedBuffer.reloadGrammar()` was removed in 20b5450
However, it is still referenced by https://github.com/atom/atom/blob/1.11-releases/src/text-editor.coffee#L3022

`TextEditor.reloadGrammar()` doesn't seem to be used anywhere though. I was using it in the init script, hence the error.

**Comment by 50Wliu** [comment]
@maxbrunsfeld

**Comment by bradennapier** [comment]
Yes I am running into this issue now whenever i try to save a file in dev mode/

**Comment by lierdakil** [comment]
`TextEditor::reloadGrammar` apparently removed in 140a78301
