### ISSUE TITLE
Atom no longer option as default editor

### ISSUE THREAD

**Issue by rohitsodhia** [atom/atom#13026]
I upgraded to 1.11.2 yesterday, and when I went to go open a file directly today (not through Atom), Windows could no longer "find" Atom, since it was still looking in the old 1.10.0 folder. I went to change what app it opens with, and I have the option of atom.cmd, but when I run it, it opens up the ugly dialog box, but doesn't actually open the file in Atom. I can right click and see the option to open the file with Atom (though the icon has disappeared), but it just brings up the "Open file with" dialog.

Essentially, I can no longer directly open a file with Atom, short of binding it directly to the exe of the current version, which would mean having to update all my shortcuts every time I update Atom.

Interestingly, I have a start menu shortcut bound to C:\Users\Rohit\AppData\Local\atom\Update.exe --processStart "atom.exe" which still launches atom at least...

**Comment by damieng** [comment]
If you go into Settings > System and click the **Register as file handler** checkbox it should fix this. It was a problem in the upgrader that is fixed in future builds.

**Comment by rohitsodhia** [comment]
Thanks a ton damieng, that fixed it! Icons have changed to the default windows icon instead of the atom one, and while I'd love to get them to the atom ico, it's something I can live with.

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/12974 they will have a different icon in 1.12.

**Comment by rohitsodhia** [comment]
Heh, so I guess it's not worth cringing over anyway. Thanks for all the help.
