### ISSUE TITLE
How about a project manager that is NOT a directory listing?

### ISSUE THREAD

**Issue by BugZappr** [atom/atom#13038]
I am using Notepad++ currently, and I prefer the Workspace/Project management it uses (View|Workspace|Workspace Panel1).  In it you add files individually to a project.  More than occasionally, I have files in a project which are no longer in use, are alternate versions which I did not bother to make a branch for, might be notes I took or are example code.  Directory listing-based project managers generally have no easy way to exclude these files.  I'd rather use the model that I ADD the files which ARE in a project, instead of SUBTRACTING files which are not.  (It also has a new feature, "Folder as Workspace", thereby giving users the choice).  It is easy enough, after all, to multi-select files which are.  Ideally, one might be able to right-click on a file's tab, and choose "Add to project".  I imagine it might be a plug-in for those who prefer not to work that way (well, nearly all of Atom is plugins), but if there is a plug-in that comes close to this for me to post an issue on, I do not know what it is.

Of the usual features I first look for in evaluating a new text editor, this is the principle one which Atom does not seem to have.  (Spell-checking might ignore keywords; but this is not a stopper for me.  This is impressive for such a new editor, BTW.)

**Comment by 50Wliu** [comment]
As you said yourself this is probably best for a package.  Searching the package listing gives me some packages you might want to check out (but at a glance I didn't see any that explicitly stated that you could add files to projects): [project-plus](https://atom.io/packages/project-plus) and [project-manager](https://atom.io/packages/project-manager).  I would also suggest posting on [Discuss](https://discuss.atom.io), the Atom message board, as that would probably give you better results.

**Comment by BugZappr** [comment]
This is best for a package, but from looking at those two, NO PACKAGE THAT YET EXISTS YET!  I see no reason for you to close this instantly.

**Comment by 50Wliu** [comment]
I closed this because this was not an enhancement request or bug, but rather a question/package request.  As per [Managing the Deluge of Atom Issues](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html), Discuss is where questions should go, not the Atom issue tracker.

**Comment by BugZappr** [comment]
It's not a question.  It's an enhancement request.

**Comment by lee-dohm** [comment]
@BugZappr We're definitely looking at ways to improve Atom's concept of a project over time. However, this is a duplicate of https://github.com/atom/tree-view/issues/854. You may want to subscribe there for updates.

Additionally, being positive and respectful is an expectation listed in our [Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md). If you want to participate here, you'll be expected to comply with it.

**Comment by BugZappr** [comment]
I'm not sure I understand that, since every bug report is negative.
