### ISSUE TITLE
TokenizedLine.tokenStartColumnForBufferColumn always returns NaN

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#13035]
I believe `Token.bufferDelta` was removed in PR #11414, not too sure about that.

Anyway, there's still a lingering reference to `bufferDelta` in
https://github.com/atom/atom/blob/master/src/tokenized-line.coffee#L42

```coffee
  tokenStartColumnForBufferColumn: (bufferColumn) ->
    delta = 0
    for token in @tokens
      nextDelta = delta + token.bufferDelta
      break if nextDelta > bufferColumn
      delta = nextDelta
    delta
```

I believe that should read -- again, not too sure, not very familiar with Atom's guts:

```coffee
  tokenStartColumnForBufferColumn: (bufferColumn) ->
    delta = 0
    for token in @tokens
      nextDelta = delta + token.value.length
      break if nextDelta > bufferColumn
      delta = nextDelta
    delta
```

/cc @nathansobo -- I think you originally wrote `tokenStartColumnForBufferColumn`

**Comment by lee-dohm** [comment]
`TokenizedLine` is an [undocumented API](https://atom.io/docs/api/search/v1.11.2?utf8=%E2%9C%93&q=TokenizedLine) and isn't supported. You are right that we should probably go through and clean out some dead code though :grinning: I'll bring it up to the team.

Thanks for the feedback!
