### ISSUE TITLE
500 code on package installation

### ISSUE THREAD

**Issue by setni** [atom/atom#13044]
### Description

500 code on package installation

### Steps to Reproduce

1. Go on preference->package->install
2. Try to install atom-autocomplete-php@0.19.4 or php-twig@4.0.0

**Actual behavior:** Unable to download https://www.atom.io/api/packages/atom-autocomplete-php/versions/0.19.4/tarball: 500 Internal Server Error Application error

### Versions

You can get this information from executing `Atom 1.11.1`.

**Comment by OlegsHanins** [comment]
Same problem on Atom 1.11.2 for Mac.

apm install remote-edit
Unable to download https://www.atom.io/api/packages/remote-edit/versions/1.8.24/tarball: 500 Internal Server Error Application error

Also sometimes return 503
Unable to download https://www.atom.io/api/packages/remote-edit/versions/1.8.24/tarball: 503

**Comment by nathansobo** [comment]
Taking a look.

**Comment by AlexandruB** [comment]
Same problem on Atom on Windows 10.

**Comment by nathansobo** [comment]
Heroku is experiencing an [API outage](https://status.heroku.com/incidents/963) due to a DDOS which is the most likely culprit. It is preventing us from logging in to view logs, preventing further diagnosis. Let's give the Heroku engineers time to resolve the issue and see if Atom.io recovers. It may be intermittent in the meantime.

**Comment by sensiblemedia** [comment]
Seeing 500 error when attempting to install packages on new install of Atom on OSX 10.11.6
```
$atom --version
Atom    : 1.19.3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by nathansobo** [comment]
I think GitHub's tarball serving was having issues this morning. Is it working now @sensiblemedia?
