### ISSUE TITLE
Polish letters issue

### ISSUE THREAD

**Issue by Wirus-deleted-my-username** [atom/atom#13048]
That issue is still present on newest atom version (1.11.2).... I'm able to type most of the letters:
ą - alt+a
 ź - alt+x
 ł - alt+l 
ń - alt+n 
ę - alt+e
 ś - alt+s 
ć - alt+c
But these letters aren't possible to type:
ó - alt+o
ż - alt+z

Add support to these letters, it is really annoying issue 😕

**Comment by thomasjo** [comment]
This has been fixed in Atom v1.12.0, which is currently being tested on the [beta channel](https://atom.io/beta).
