### ISSUE TITLE
How can I set the path where the packages are installed for a specific instance of Atom ?

### ISSUE THREAD

**Issue by kevincaradant** [atom/atom#13041]
Hi

I have a setup with an atomPortable.exe found here: https://github.com/garethflowers/atom-portable
Have I to use your repository to have a atom portable ? I don't know how to do with yours if it's possible

Also, I have an atom installed with right admin in the user folder with a .atom and some plugins. 

I want to put the plugins in my special folder  with my portable Atom which is on the other location but when I write `apm install my_plugin`, it install it in my .atom folder under the user `C:\Users\Kevin\.atom\Data\packages` something like that and not where I have my portableAtom which is `C:\PortableAtom\Data\packages`. 

How can I tell it, OK I want that you install here every time with my commander line ? Or maybe there is an other way ? I don't know :/

Thank you

**Comment by S-ed** [comment]
Probably by running atow with predefined ATOM_HOME:
```batch
@echo off
pushd %~dp0
if not exist .atom mkdir .atom
if not exist .atom\AppData mkdir .atom\AppData
if not exist .atom\AppData\Roaming mkdir .atom\AppData\Roaming

:: Trick emmet or other plugin to think profile directory is in our data directory
set "USERPROFILE=%~dp0\.atom"

:: Set Atom base directory
set "ATOM_HOME=%~dp0\.atom"

:: Boot
start atom
```
(this is copypasta, edit for your needs, more info: https://github.com/atom/atom/issues/2939)

**Comment by lee-dohm** [comment]
@S-ed is correct, you can place the `.atom` directory wherever you want with the use of the `ATOM_HOME` environment variable. You can only move the entire `.atom` directory though, you can't put `.atom/packages` in one place and `.atom/config.cson` in another.

You can find information on other options for portable use in the [Atom Flight Manual under Installing Atom](http://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode-for-windows).
