### ISSUE TITLE
ctrl+R can't find method

### ISSUE THREAD

**Issue by QiiSyhx** [atom/atom#13057]
### Prerequisites

* [ok ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ok ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ok] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ok] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ok ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ok ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

This problem has always been there, all version. now my atom version is 1.10.2

![qq 20161024135334](https://cloud.githubusercontent.com/assets/2001704/19635002/9c79a742-99f1-11e6-9656-d5d7bf26f4f5.png)

**Comment by 50Wliu** [comment]
As specified in the [symbols-view](https://github.com/atom/symbols-view) README, you need to have a `.tags` file in order for symbol viewing to work.  You can generate one using [ctags](ctags.sourceforge.net).
