### ISSUE TITLE
Erratic behaviour of atom.workspace.open

### ISSUE THREAD

**Issue by idleberg** [atom/atom#13054]
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.
### Description

When executing `atom.workspace.open("myNewFile")` (e.g. in the console), Atom behaves differently on different platforms and whether in Developer Mode or not.
### Steps to Reproduce

The following has been tested Safe Mode (`atom --safe` and `atom --safe -dev`):
#### macOS 10.12 / Atom 1.11.2

In both, regular mode and Developer Mode, `atom.workspace.open("myNewFile")` opens new tab "untitled". However, when I'm outside of Safe Mode and in Developer Mode, it opens a new tab titled "myNewFile" (as expected!)
#### Windows 10.0.14393 / Atom 1.11.2

In both, regular mode and Developer Mode, `atom.workspace.open("myNewFile")` opens new tab titled "myNewFile".
#### Fedora 24 (GNOME 3.20.2) / Atom 1.11.2-0.1

Same as Windows

**Expected behavior:** All version to behave consistently like on Windows and Linux

**Actual behavior:** macOS behaves differently
### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.
#### macOS 10.12

``` bash
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.8.4
```
#### Windows 10.0.14393

``` cmd
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.3.windows.1
visual studio
```
#### Fedora 24

``` bash
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4
```

**Comment by iolsen** [comment]
Does this alter what happens when you try to save the file? Like setting the file name differently? Or is it purely cosmetic and just the tab name.

/cc @bungdonuts

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13054#issuecomment-258923445. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by idleberg** [comment]
> Does this alter what happens when you try to save the file? Like setting the file name differently? Or is it purely cosmetic and just the tab name.

(Sorry for the late reply) When I save the file, there's no value for the file name. Whereas when I save in Developer Mode, the proposed file name matches the tab-name.
