### ISSUE TITLE
Bad indentation in nested loops ( C )

### ISSUE THREAD

**Issue by Kornhe** [atom/atom#13058]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Indentation isn't working properly in nested loops. All the curly brackets are aligned on a single column rather than being aligned with "their loop".

### Steps to Reproduce

1. Create a while
2. Create another while/if inside
3. try to align the curly brackets

**Expected behavior:** [Expected](http://i.imgur.com/7vT7BKC.png)

**Actual behavior:** [Result](http://i.imgur.com/CV6JaQW.png)

### Versions

Atom : 1.11.2
OS : Blinux

**Comment by 50Wliu** [comment]
Please reopen this on the [language-c](https://github.com/atom/language-c) repository.
