### ISSUE TITLE
Cannot change font size of UI

### ISSUE THREAD

**Issue by vlad1777d** [atom/atom#13055]
### Prerequisites

* [no] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [yes] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [no] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [yes] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [yes] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [yes] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

In the setting there is a way to change the font size, but it only changes the font size of text from text files.
There is no way to increase\decrease font size of user interface.

**Expected behavior:** [What you expected to happen]
I expect that there would be entry, where I could change UI's font size. It may be near to the entry for changing font size of editor text:
![2016-10-24 04-38-50](https://cloud.githubusercontent.com/assets/12682937/19631354/f884f558-99a3-11e6-9179-8eb11ca21cf5.png)

**Actual behavior:** [What actually happened]
There is not entry to change font size of UI.

### Versions
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
OS: Debian x64 unstable Cinnamon

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by arcticicestudio** [comment]
As the description says:
> Height in pixels of **editor text**.

The UI font and size depends on the UI theme. Many UI themes include theme specific settings for users, e.g. [One Dark UI](https://github.com/atom/one-dark-ui) or [my theme](https://github.com/arcticicestudio/nord-atom-ui/issues/36).

![scrot-github-atom-atom-ghi-13055](https://cloud.githubusercontent.com/assets/7836623/19633568/6e7e0e16-99b3-11e6-8481-9bf638f87558.png)

**Comment by 50Wliu** [comment]
In addition, [this comment](https://github.com/atom/atom/issues/3636#issuecomment-75157082) might help if your UI theme does not allow for UI font size customization.

**Comment by vlad1777d** [comment]
Thank you, but I have not button to change theme.
![2016-10-24 19-13-07](https://cloud.githubusercontent.com/assets/12682937/19653662/0586a9ac-9a1e-11e6-95ce-a824739ba77b.png)
Maybe it would be better to create such entry in preferences (it's not rarely used)?

**Comment by arcticicestudio** [comment]
*Atom Dark* UI- and syntax themes have been replaced by the *One Dark* themes which includes settings as shown in the screenshot above.
To change the UI font size for *Atom Dark* you should follow the instructions from the post @50Wliu posted.

**Comment by w-barath** [comment]
There's a bug in that it only takes px sizes.  My screen size changes several times per day so I'd like to enter my font size as .7vmax instead of a pixel size.

**Comment by franciscop-invast** [comment]
Note that when changing the font everything will look broken; restart Atom and the interface will be adapted (at least in Windows).
