### ISSUE TITLE
Unable to connect to Atom in any fashion through the app in Windows 10. "Loading themes", etc.

### ISSUE THREAD

**Issue by emptyopen** [atom/atom#13059]
### Description

I installed Atom in the most basic way possible. Went to the website, clicked "Download Windows Installer". It did it's thing. Now I can open Atom, but I can't seem to download any packages, themes, anything. 

https://postimg.org/image/ooxogddat/
https://postimg.org/image/6nejikj9x/

I've googled this for a while, I've tried setting my environmental variables to every path in existence. Still nothing. I've run Atom in safe mode (i.e. I can run it from the command line). Not sure what else to try. Something extremely basic is missing in the install process. 

### Steps to Reproduce

1. Download Atom on Windows 10
2. You can't download anything from github or atom in general

**Expected behavior:** 

I would be able to download a snazzy theme (or APIs to use this as my Python IDE or whatever).

**Actual behavior:** 

I was not able to download any snazzy themes. 

### Versions
Running 'apm --version' gets me:

```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 3.5.2
git 2.10.1.windows.1
visual studio
```

**Comment by Ben3eeE** [comment]
Do you have any quotation marks in your path variable?

**Comment by emptyopen** [comment]
https://postimg.org/image/ffaa4802r/

**Comment by Ben3eeE** [comment]
There is another Path variable in the system variables section that you can check for quotation marks.

**Comment by emptyopen** [comment]
?????

**Comment by Ben3eeE** [comment]
![image](https://cloud.githubusercontent.com/assets/1058982/19647801/2578b64c-9a00-11e6-89df-b479d07ceadb.png)

**Comment by Ben3eeE** [comment]
> The edit button is greyed out

Try to echo the variable from the command line instead. In `cmd.exe` type `echo %path%`.

**Comment by emptyopen** [comment]
C:\Users\Takkeezi>echo %path%:
`C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Python\Scripts\;C:\Python\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;"C:\Program Files (x86)\Microsoft Office\DOCRECRYPT";C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Git\cmd;C:\Users\Takkeezi\AppData\Local\Microsoft\WindowsApps;C:\Users\Takkeezi\Documents\Atom\resources\cli\;C:\Users\Takkeezi\AppData\Local\atom\bin`

**Comment by 50Wliu** [comment]
This will be fixed in Atom 1.13.0.  There is a chance that this fix will be backported to 1.11 and 1.12 but that may or may not happen.

**Comment by emptyopen** [comment]
Thanks!
Is there a release date for this? Also, is there a workaround in the mean time?

**Comment by Ben3eeE** [comment]
Workaround is to edit the environment variable and remove the quotation marks. There is no release date set for Atom 1.13 yet.

This part `"C:\Program Files (x86)\Microsoft Office\DOCRECRYPT";` needs to be `C:\Program Files (x86)\Microsoft Office\DOCRECRYPT;`

**Comment by emptyopen** [comment]
Thanks for the help!
