### ISSUE TITLE
Comment Highlighting broken for "//**/" end of comments (Screencap linked)

### ISSUE THREAD

**Issue by actcontpr** [atom/atom#13066]
### Description

Comment Highlighting broken in PHP mode with flexible comments with "//**/", most likely broken in other languages too. [Link to screencap](https://goo.gl/photos/Y33bww8mkaMRoP3E9)

### Steps to Reproduce

1. Open comment with "/**"
2. Close comment a few lines down with "//**/"
3. The comment highlightings continues beyond the "//**/" although it shouldn't.

**Expected behavior:** The comment highlight should stop at comment close.

**Actual behavior:** Highlight continues beyond end of comment.

### Versions

1.11.2 and earlyer

**Comment by 50Wliu** [comment]
Please reopen this on the [language-php](https://github.com/atom/language-php) repository.
