### ISSUE TITLE
--harmony flag exposes bug in Chromium 53 currently in Atom Beta

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#13073]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

[Sample code](https://gist.github.com/zertosh/c8fd6482cde0292f363bf47dd81fb0f1)

**Expected behavior:** No exception is thrown

**Actual behavior:** Exception is thrown as stated in the Gist

### Versions

```
Atom    : 1.12.0-beta4
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

```
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.1
```

### Relevant Links

* https://bugs.chromium.org/p/v8/issues/detail?id=5322

### Possible Fix

Commenting out [this line](https://github.com/atom/atom/blob/v1.12.0-beta4/src/main-process/atom-application.coffee#L94) appears to solve the problem.

/cc @zertosh for tracking

**Comment by zertosh** [comment]
FYI: @jgebhardt @mostafaeweda @nmote

**Comment by nathansobo** [comment]
Yeah, we should definitely be able to drop `--harmony`. It's been around for a long time to enable `Map` and friends. Shouldn't be needed now.
