### ISSUE TITLE
Tree View Stuck on opening project folder

### ISSUE THREAD

**Issue by basith374** [atom/atom#13072]
![screen shot 2016-10-26 at 10 31 39 am](https://cloud.githubusercontent.com/assets/10130692/19713895/6e2e3980-9b67-11e6-867e-cb4d77efafe4.png)

as you can see the project folder shows this 'refresh' icon. but it just stays there forever. it doesn't open at all.  But i can open project files using `Command + P` shortcut.

**Comment by lee-dohm** [comment]
Thanks for reaching out!

That doesn't appear to be Atom's Tree View, which looks like this:

<img width="610" alt="screen shot 2016-10-25 at 10 09 09 pm" src="https://cloud.githubusercontent.com/assets/1038121/19714026/b3fc2282-9aff-11e6-83be-5b43e5a8f3cf.png">

Atom also doesn't have a "refresh" icon in the Tree View. I'm not sure what package that is. I couldn't find it with some quick searches. You should probably contact the maintainers of that package to see if they can help with what is going wrong. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by jgebhardt** [comment]
Looks like you have Nuclide installed, which ships a custom file tree. You probably want to file an issue over at https://github.com/facebook/nuclide/issues instead. Please also provide version & package info when you do so. Thanks!

**Comment by basith374** [comment]
okay i found out the problem by opening the developer tools. it seems that yesterday, i was trying to create a new file. and in the file name i included slashes to create this in a subdirectory. like `app/index.js` instead of `index.js`. so what happened is that atom automatically renamed it to `app:index.js`. now its showing this error
```
Uncaught (in promise)
message: Nuclide URIs must contain paths, null' found while parsing 'app:index.js'

**Comment by basith374** [comment]
okay. thanks for the help.
