### ISSUE TITLE
1.11.2 - language settings (tabType/indent_style) seemingly ignored on window:refresh, restart

### ISSUE THREAD

**Issue by working-name** [atom/atom#13070]
### Prerequisites
- ~~[ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?~~ Can **_you_**?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- ~~[ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?~~
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

Language-X packages can have their own editor settings, and snippets. However I found that tabType/indent_style is not respected when starting/restarting/window:reloading atom. 
### Steps to Reproduce
1. Set your global preference for tabs to auto, 2 spaces and check show invisibles. Inject a settings file in your favorite language-X package:

``` coffeescript
'.scope.Name':
  'editor':
    'tabType': 'hard' #this doesn't seem to do anything.
    'softWrap': true
    'indent_style': 'tab' #this actually makes it an \x09
```
1. do a window:reload, type a tab when back up. Should be a tab character, but it's two spaces.
2. Quit Atom and restart it, type a tab in the file after session is restored, it's again two spaces.
3. Change something in the `settings/language-X.cson` file and save it, do a window:reload. You might now get a tab character, or you might get two spaces. Can't see a pattern, seems random.

**Expected behavior:** settings/language-X.cson should **always** override global settings.

**Actual behavior:** ([screencast of bug in action](https://bugout.regex.cf/tabissues.mp4)) settings/language-X.cson seems to randomly be reloaded when modified, or only when switching to another language and then back to this one.
### Versions

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
OS: 10.10.5

**Comment by 50Wliu** [comment]
Since this problem cannot be reproduced in safe mode (at least that's what I'm interpreting from your strikethrough), I'm closing this issue.  Feel free to correct me if I'm wrong.

**Comment by working-name** [comment]
@50Wliu I get it, your time is limited, and probably almost as expensive as mine, but tell me I didn't just waste my time writing that up. How exactly is one supposed to test this bug if not by loading a settings file from a language stored in `~/.atom/packages`? That's the whole point here.

> This starts Atom, but does not load packages from `~/.atom/packages` or `~/.atom/dev/packages` and disables loading of your init script. If you can no longer reproduce the problem in safe mode, it's likely it was caused by one of the packages or the init script.

**Comment by 50Wliu** [comment]
There are bundled language packages that aren't located in `~/.atom/packages` that you should be able to test with.  For example, language-c, language-javascript, language-css, language-html...
Since some language packages like [language-yaml](https://github.com/atom/language-yaml) already specify a tabType within their settings that has been confirmed to work, I suspect that you are running into a conflict with one of your community packages.
In addition, `indent_style` doesn't even exist in Atom's default configuration.

**Comment by working-name** [comment]
Unpacking has no effect, Atom crashes if I rename app.asar. There's no easy way to do what you're saying, so I disabled all community packages. Then ran `apm develop language-html`, edited its settings file to 
```json
'.text.html':
  'editor':
    'tabType': 'hard'
    'commentStart': '<!-- '
...
```
and ran `atom --dev`. After a window:reload bug is there. I swap to CSS, then back to HTML, I get true `\t` characters. I quit atom and re-run `atom --dev` bug is automagically back.
