### ISSUE TITLE
IntlRo key on Brazilian Portuguese layout is not resolving to key bindings correctly

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#13076]
@escobera I thought I'd move this to its own issue so we can track it.

![](https://cloud.githubusercontent.com/assets/9344/19708902/d86164f6-9b00-11e6-98b1-d79a5c5b3f01.png)

**Comment by escobera** [comment]
@nathansobo ok by me. Is there any way I can help you here?

**Comment by nathansobo** [comment]
Thanks for the offer @escobera. It ended up being simple enough that I just took care of it. Should be fixed in 1.12.0-beta5.

**Comment by escobera** [comment]
@nathansobo thanks a lot. The main problem is solved. There's a side-effect tough. `ctrl-;` is still triggering `Toggle Comment`.  

Lemme try and show this a little better:

Correct behavior  `ctrl-/`
![selection_015](https://cloud.githubusercontent.com/assets/9344/19812009/919ad2fa-9d12-11e6-992a-30f913a73412.png)

Strange behavior `ctrl-;` (notice it doesn't show the command)
![selection_016](https://cloud.githubusercontent.com/assets/9344/19812037/b3fc9cac-9d12-11e6-816f-3718b68964f6.png)

**Comment by nathansobo** [comment]
So `ctrl-;` is commenting the line? Are you seeing the application menu flash? If so, it's possible that the keyboard shortcut associated with the application menu item is being triggered due to a bug in the operating system. If this is the case, there's not much we can do about it short of removing the menu item, which I don't really want to do.

**Comment by escobera** [comment]
Yeah, it's commenting the line.
What do you mean by application menu flashing? 
Nothing seems to be flashing here.

![menu_017](https://cloud.githubusercontent.com/assets/9344/19813820/1cb5ae8a-9d1a-11e6-8d68-507b1d362755.png)

This shows the correct shurtcut.

**Comment by nathansobo** [comment]
Not sure if the menu flashes when an item is selected on Linux Mint, but it seems very likely that the operating system is triggering that menu item on `ctrl-;`.

**Comment by escobera** [comment]
Is there a way to test that?

**Comment by nathansobo** [comment]
Not sure... maybe the OS allows you to override shortcuts for certain menus. That's something you can do on macOS but not sure on Linux.

**Comment by nathansobo** [comment]
@Ben3eeE Does this look like what you're seeing with `ctrl-'` on the Swedish layout?

**Comment by Ben3eeE** [comment]
Yeah it does look the same. I get this on  Windows 10 and Ubuntu 16.04 on Swedish layout. <kbd>Ctrl+'</kbd> either prints `undefined` in the `TextEditor` or comments out the line based on grammar and content of the line. Investigating.

**Comment by nathansobo** [comment]
@Ben3eeE When you get some more context it might be good to open a new issue.

**Comment by Ben3eeE** [comment]
There is an issue for this already: https://github.com/atom/atom/issues/10104
