### ISSUE TITLE
Alt-modified keystrokes are broken on macOS in 1.12.0-beta4

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#13085]
We're using the alt-modified character instead of the non-modified character when alt is used.

![](https://cloud.githubusercontent.com/assets/593118/19737143/f6cd2eec-9bba-11e6-9315-d45f1ad6ba83.png)

@AriaMinaei tracking your issue here instead of in that other issue. This should be fixed today in 1.12.0-beta5.

**Comment by AriaMinaei** [comment]
I can confirm that my keybindings seem to be working again with beta5. Thanks @nathansobo :)

**Comment by nathansobo** [comment]
Yeah, thanks for the report. Sorry about the hiccup. Had a wrong assumption about the `KeyboardEvent` API on macOS that found its way into the test helpers.
