### ISSUE TITLE
Too long a line of code

### ISSUE THREAD

**Issue by przemyslawnycz** [atom/atom#13089]
Some css files have too long a line of code.
Is there any way to divide it and to make the code more readable?
<img width="1265" alt="longline" src="https://cloud.githubusercontent.com/assets/23001436/19789163/b12e4bb6-9cad-11e6-9db6-ecdb00941680.png">

**Comment by udnaan** [comment]
Turn on soft wrap in Settings->Editor

**Comment by mnquintana** [comment]
Thanks @udnaan!

Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
