### ISSUE TITLE
Build Atom for 32 bit Linux

### ISSUE THREAD

**Issue by progkix** [atom/atom#13092]
I'm attempting to build the latest version (1.11.2 & 1.12.0b5) on Fedora 24 for 32 bit platform.

Upon starting the build script, I immediately get this erro:

/usr/local/src/atom-1.12.0-beta5/script/build:13
const yargs = require('yargs')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Am I just out of luck building 32 bit versions?

**Comment by thomasjo** [comment]
What version of Node.js are you using?

**Comment by progkix** [comment]
Oh sorry
node --version reports 0.12.5

**Comment by thomasjo** [comment]
If you look at the [build instructions](https://github.com/atom/atom/blob/a759e5f17dbf470183d1aa1795615a508da0e4ff/docs/build-instructions/linux.md#requirements), you'll see that Node.js v4.4.x or later is required.

Additionally, you might have to checkout PR #13001 in order for the build to actually produce a 32-bit binary.

**Comment by progkix** [comment]
I understand that. I installed Node 7.0.0 for Fedora 24.

Just ran this:

n stable

     install : node-v7.0.0
       mkdir : /usr/local/n/versions/node/7.0.0
       fetch : https://nodejs.org/dist/v7.0.0/node-v7.0.0-linux-x86.tar.gz
######################################################################## 100.0%
   installed : v0.12.5

**Comment by 50Wliu** [comment]
#13001 has been merged.
