### ISSUE TITLE
Proposal: Create multiple files over the file dialog

### ISSUE THREAD

**Issue by lenovouser** [atom/atom#13102]
I'd love to be able to use something similar to the UNIX `touch` or `mkdir` syntax in order to create multiple folders and / or files with the file create dialog. Something like this:

![](https://puu.sh/rZXNF/9c60770fd4.png)

**Comment by Ewwe** [comment]
Hell yeah.. would be great

**Comment by lenovouser** [comment]
Still relevant I suppose. "Reproducible" on all platforms and versions since it is a feature request.
