### ISSUE TITLE
Go to CSS class / ID from html code

### ISSUE THREAD

**Issue by PixelT** [atom/atom#13106]
Example:
https://github.com/rmaksim/Sublime-Text-2-Goto-CSS-Declaration

Possibility to go to the CSS class in open CSS files, when put cursor in HTML file on class / ID name + use shortcut / commend

**Comment by 50Wliu** [comment]
This is a great package idea - I would suggest that you bring it up on [Discuss](https://discuss.atom.io), the Atom forum, instead of here, so that you get better feedback.
