### ISSUE TITLE
White text on white background in menus in Windows high-contrast mode

### ISSUE THREAD

**Issue by rsomla** [atom/atom#13115]
Hi,

I downloaded Atom 1.11.2 for Windows from the official download
page . I am using the Windows high-contrast theme. After starting
Atom app all looks great except that menus have white background
and white text, which makes it basically impossible to use
the editor :/

Rafal

**Comment by Zandrae** [comment]
To give more information that might help the developers, I also am afflicted by this. I am using Windows 10 with high contrast mode with the inverted colors. Black bars, light text. This may be a problem for Windows 8.1 and Windows 10 users using these settings.

**Comment by DylanJCain** [comment]
I have just tested this with Atom v1.11.2 i wish the author of this post was a little bit more specific on which version of windows they are running. 

Reproduced in Windows 7 - author is correct, all the text in the drop downs are in white.
Reproduced in Windows 10 - Again, Author is correct all the text in the drop downs are white.

**Comment by rsomla** [comment]
Sorry that I forgot to mention Windows version. I was using Atom on Windows 10.

Rafal
