### ISSUE TITLE
Feature request: Provide an AppImage for Atom Stable and Atom Beta releases

### ISSUE THREAD

**Issue by fusion809** [atom/atom#13118]
Hi,

As @probonopd, the developer of the AppImage format, has requested I do this in [probonopd/AppImages#118](https://github.com/probonopd/AppImages/issues/118#issuecomment-257396828), I have decided to request that this provide provides official AppImage builds for Atom Stable and Atom Beta releases. AppImages are a cross-distribution (but very much Linux-specific, in case you're wondering whether they'd run on FreeBSD) package format that are essentially self-mounting disk images with all the required libraries and executables inside to run the app they provide (in the case of an Atom AppImage this would be Atom, of course). They are similar, in this regard, to `.dmg` (or disk image) files for macOS. I realize this project already provides tarball builds for Atom, but AppImages do not need to be extracted in order to be run, unlike tarball builds. AppImages are extremely easy to build, including from your Travis CI artefacts. 

And yes, I know that AppImages have been previously discussed in this bugtracker, see for example atom/atom#4980. But I would like to make a formal and specific request (as opposed to issue 4980, which merely requested a portable package format for Linux and did not specifically request an AppImage) for them to be provided. 

Thanks for your time,
Brenton

**Comment by Ben3eeE** [comment]
Refs: https://github.com/atom/atom/issues/2956#issuecomment-255622650

**Comment by probonopd** [comment]
See https://github.com/atom/atom/pull/15193

**Comment by damieng** [comment]
Closing - our reasons for not supporting additional distribution formats at this time are documented in #13921
