### ISSUE TITLE
Application Freeze When Searching CSV File with Regex

### ISSUE THREAD

**Issue by lachlan-eagling** [atom/atom#13122]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Trying to search with Regex option on in 843KB .csv file causes application to freeze after typing \n in search bar. 

![2016-11-01_1605](https://cloud.githubusercontent.com/assets/8456105/19880111/3f586c16-a04e-11e6-8d47-da3a829e5b20.png)

RAM utilisation exceeding 800MB after app freeze.

![taskmanager](https://cloud.githubusercontent.com/assets/8456105/19880118/68fa4ba2-a04e-11e6-8041-74804fe46217.png)

### Steps to Reproduce

1. Open csv file (Tested with file containint 9604 lines)
2. Enter regex [a-z]\n[a-z] and observe that application freezes when typing \n

### Versions

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Windows 10

**Comment by adsfgg** [comment]
I was able to reproduce this using a large csv file with 10,000 lines of random entries. The application does freeze and memory usage does increase.

However I couldn't repro this on a small file. This seems to be related to large files.

**Comment by lachlan-eagling** [comment]
Can confirm, no issue with small files only very large.
