### ISSUE TITLE
Feature Request: Support for VB.net

### ISSUE THREAD

**Issue by Accelyte** [atom/atom#13126]
I know VB.net is a bit lame compared to C++ and all that, but VB.net is quite popular. I use VB.net myself, so I'd love to see it implemented as one of the supported languages by default.

**Comment by thomasjo** [comment]
There's already a community package providing VB.NET support:
https://atom.io/packages/language-vb

Given the fact a package exists, and the fact we don't want to take on unnecessary maintenance burdens, we have no plans of creating a core package for VB.NET language support. Thanks for the suggestion though.

**Comment by Accelyte** [comment]
It's actually because I tried using the package and it wasn't syntaxing my code that I suggested making it native, I copypasted some of my code from visual studio to atom and all I got was dashed red error underlines.

**Comment by Accelyte** [comment]
Actually no, I take that back. I didn't know syntaxing only worked after you saved the file. My bad.
In that case, is it possible for Atom to actively try to identify the code type and apply syntax highlighting? Or maybe manual dropdown menu that sets the code type of the file.

**Comment by Ben3eeE** [comment]
You can change language using the language selector available in the status bar:
![select language](https://cloud.githubusercontent.com/assets/1058982/19947194/48624dfa-a147-11e6-8d0c-a8c8fd414ee7.gif)

**Comment by Accelyte** [comment]
I see, thanks :)

**Comment by Ben3eeE** [comment]
You're welcome 🙂
