### ISSUE TITLE
Can't open notepad++ ansi encoded files properly with atom

### ISSUE THREAD

**Issue by stebiger** [atom/atom#13136]
Hey,

I know this is a complicated and never ending story but I still try to understand, why atom is not able to operate with files from other editors in non-rare encodings.

I am working on a windows machine and produce a txt file with Notepad++ encoded with it's `ansi `encoding.
When I open that file with atom - I can not find any encoding that is able to show characters like german umlauts (ä ö ü ß )with its proper encoding. Not `ISO-88591, cp1252 `is able to encode it properly.

Cross-check that behaviour by doing it vice versa shows me the same.

I often have read that you claim to say that ANSI is wide-variety of "encoding" - yes that is true. But I also read that you claim that `windows1252 `aka `cp1252 `on windows machines ensures such an ANSI encoding.

From what I can reproduce this is wrong. CP1252 is not even ANSI certified and the encoding will differ.

A file with ANSI encoding from Notepad++ will produce the following charset:
`foo.sql: text/plain; charset=us-ascii`

While a file with cp1252 from atom will produce:
`foo.sql: text/plain; charset=iso-8859-1`

Whilst they seem to only differ in some characters this is a problem with database scripts or some other usage.

I would like to ask if there will ever be a timeline when atom editor is able to support proper ANSI encoding - if that will be achieved I can finally move from Notepad++ to atom editor.

**Comment by Ben3eeE** [comment]
Unable to reproduce, here is what I did:

1. Open Notepad++
1. Change encoding to ANSI by choosing `Encode in ANSI` from the `Encoding` menu
1. Enter the contents `ä ö ü ß` in a new empty file
1. Save the file as `ansi.txt` on the desktop
1. Open Atom and open `ansi.txt`
1. Expected and Actual: File opens with `UTF-8` encoding and looks incorrect
1. Open the encoding selector <kbd>Ctrl-Shift-U</kbd>
1. Change the encoding to `Western (Windows 1252)` or alternatively `Auto Detect`
1. Expected and Actual: File looks correct.

Please provide full steps to reproduce the issue.

**Comment by stebiger** [comment]
> Expected and Actual: File looks correct.

Look is not equals to **is**.
Save such a file with windows 1252 and check the encoding (like `file -i `on a cli) and see that it is not the same charset.

**Comment by damieng** [comment]
Try **DOS (CP 437)** from the drop-down list.

**Comment by stebiger** [comment]
Hello damieng,

thank you for a hint. Unfortunately the encoding differs for a file saved with DOS (CP 437).

![image](https://cloud.githubusercontent.com/assets/8200750/19998055/c70bb960-a26a-11e6-8117-849a8d1240a8.png)

Steps to reproduce:

1. Input #äüö+ü in new atom file with DOS (CP 437) selected encoding, save
2. Open with Notepad++
3. See result characters: #„”+
4. Check encoding with gnu tools: `file -i`

**Comment by damieng** [comment]
There is no "proper ANSI encoding". Choosing this option uses whatever default codepage the OS has to interpret the characters above 0x7F.

On Windows this is controlled by the **Region > Language for non-Unicode programs** in Control Panel. Normally this is Windows-1252 for US English but could be different depending on your locale.

On my system (US English) setting Atom to Windows-1252 works perfectly as show in this hex view;

![image](https://cloud.githubusercontent.com/assets/118951/20012232/adea1d54-a26b-11e6-859b-5afaa853fdb0.png)

You mention using this "encoding" for database scripts. I would not advise that. Files written this way have no metadata about what actual codepage they were written with and machines reading the file will use their own default code page to interpret these characters.

The upshot is a file written on your machine in "ANSI" and subsequently uploaded to a remote Linux server for example could easily result in the contents being interpreted differently. Likewise send the file to somebody in a different country and again they'll see something different by default.

**Comment by lee-dohm** [comment]
As @damieng noted, there is no single encoding named "ANSI". If you have steps that show that Atom is encoding something incorrectly using a hex editor, please let us know. As things stand now, the information here leads me to believe that this is just that Atom and Notepad++ are using different encodings.

Let us know if you have more information @stebiger and we'll be happy to reopen the issue.
