### ISSUE TITLE
Slow dependencies loading during startup

### ISSUE THREAD

**Issue by walles** [atom/atom#13133]
Will attach startup profile showing that loading the w3c-validator plugin takes 829ms.

I'd expect plugin loading to be a lot faster than that, but I'm not good enough to actually track this down to what's actually so hard about loading those requirements.

### Steps to Reproduce

1. Install the w3c-validator package
2. (Re)start Atom
3. Launch Timecop. Notice that w3c-validator package activation time is really bad
4. Close Atom and start with `--profile-startup`
5. Look at the profile as `Tree (Top Down)` and notice that loading the files from w3c-validator takes much too long

**Expected behavior:**
Loading the w3c-validator should be snappy, at least the dependency resolution / loading which is the part Atom / Electron provides.

**Actual behavior:** [What actually happened]
Loading the w3c-validator package is really slow, which the profile indicates is due to dependency resolution performance of the platform.

### Versions

```
~/s/w3c-validation (master|✔) $ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
~/s/w3c-validation (master|✔) $ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.1
~/s/w3c-validation (master|✔) $
```
This is on OS X El Capitan, 10.11.6.

My computer has a hard drive, not an SSD, but there's plenty of RAM left and I've done this several times so everything should be cached.

**Comment by walles** [comment]
Profile generated with `--profile-startup` showing slow dependency resolution for w3c-validator:
[slow-package-loading.cpuprofile.zip](https://github.com/atom/atom/files/567637/slow-package-loading.cpuprofile.zip)

**Comment by walles** [comment]
See also:
https://github.com/atom/metrics/issues/70
https://github.com/leny/atom-w3c-validation/issues/18

**Comment by thomasjo** [comment]
We have zero control over the referenced package. If they are doing something that is slow, then you need to get the package authors to resolve that. There's nothing we can do on our end as far as I can tell.

**Comment by thomasjo** [comment]
One thing you can suggest they do, is to defer package activation until necessary by using [`activationCommands`](http://flight-manual.atom.io/hacking-atom/sections/package-word-count/#packagejson).

**Comment by walles** [comment]
My impression from the attached profile was that it is the *loading* of those packages that is slow, and that *is* part of Atom.

Am I wrong?

As I said I'm not familiar enough with the environment to draw good conclusions from the profile, so I'm OK with being wrong.

**Comment by thomasjo** [comment]
If they do something, like loading dependencies that are huge (by virtue of having many dependencies themselves), that is slow, how are we supposed to fix that? There are good reasons for having the concept of deferred activation via `activationCommands` and `activationHooks`, this is one of them.

Dependency resolution is done by V8/Node.js, and out of our hands.

**Comment by walles** [comment]
I'll consider `activationCommands` / `activationHooks`, thanks for the pointers @thomasjo!
