### ISSUE TITLE
Feature Request: Save a regex for future usage

### ISSUE THREAD

**Issue by firattekin1** [atom/atom#13139]
I recently searched a module or extension like that but no luck.
How about adding a module like that?

> 1 - Write a regexp for your requirement.
> 2- Save it for future use.
> 3- When same regexp need, use it like syntax selector.

I really don't know is it really required/wanted by community or not. But, it's a requirement imho.

**Comment by andya9** [comment]
Belongs to [Discuss](https://discuss.atom.io/), not here

**Comment by 50Wliu** [comment]
Thanks @andya9.
