### ISSUE TITLE
Atom editor SQL text overlap bug

### ISSUE THREAD

**Issue by Dowwie** [atom/atom#13130]
Atom editor does not appropriately handle sql files containing lines that extend 80 characters.  Long lines appear to corrupt lines below as the width of the editor pane narrows.

I've created a short video clip illustrating the issue.  As I expand the tree navigator width, notice how two sections of code begin to overlap:  https://gfycat.com/SoftMistyAmericancrocodile

However, I've found that enabling soft-wrap resolves this issue.

### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by Ben3eeE** [comment]
Please completely fill out the provided issue template.

**Comment by 50Wliu** [comment]
To add on to what @Ben3eeE said, if you cannot reproduce this issue in safe mode, then it will be closed.

**Comment by Ben3eeE** [comment]
I assume that this doesn't reproduce in safe mode since no additional information was given. If you still experience this error in safe mode please open a new issue and completely fill out the provided issue template.
