### ISSUE TITLE
Uncaught Error: The element has already been freed!

### ISSUE THREAD

**Issue by DeanmvSG** [atom/atom#13137]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
No as it is thrown when switching projects using [this](https://github.com/danielbrodin/atom-project-manager) plugin that causes the issue, but Atom is reporting that it is an issue with Atom, so I cannot reproduce in safe mode as that plugin does not run.

* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When switching project using [this](https://github.com/danielbrodin/atom-project-manager) plugin, Atom reports this error, but states that it is a bug within Atom and not within this plugin.  Also sometimes happens when I close a file in an open project after switching using the project manager plugin.

![screen shot 2016-11-03 at 10 54 07](https://cloud.githubusercontent.com/assets/15265711/19963348/e112df12-a1b3-11e6-9592-4edb30cd7cfa.png)

### Steps to Reproduce

1. Open a project within Atom
2. Using the Project Manager Plugin, switch to another project with the original one still open

**Expected behavior:**
The project to switch but no errors be thrown

**Actual behavior:**
The project does switch successfully but this error is thrown at the same time.

### Versions

macOS: 10.12.1 (16B2657)
Atom: 1.12.0-beta6
Electron: 0.37.8
Chrome: 49.0.2623.75
Node: 5.10.0
apm:  1.12.5
npm:  3.10.5
node: 4.4.5
python: 2.7.10
git: 2.9.3

**Comment by 50Wliu** [comment]
The error is originating from Atom, but it is most likely *caused* by incorrect behavior from the Project Manager package.  I would suggest re-reporting this over there.  Sorry for the trouble!

**Comment by DeanmvSG** [comment]
@50Wliu I did wonder that!  Will do, thanks for the heads up 👍

**Comment by r3oath** [comment]
I don't have the project manager package installed and I am getting this error now. To such a degree that it's spamming message boxes down the side of atom that you cannot close as it spawns a new one every second or so.

<img width="603" alt="screen shot 2016-11-24 at 09 17 50 am" src="https://cloud.githubusercontent.com/assets/2805249/20581783/e8f96cd6-b226-11e6-8461-4c0558fb1115.png">

### Install packages
```
Stylus@3.1.0
Sublime-Style-Column-Selection@1.7.2
atom-beautify@0.29.13
atom-material-syntax@0.4.6
atom-material-ui@1.3.6
atom-pair@2.0.10
atom-slugify@1.0.0
atom-wrap-in-tag@0.6.0
autoclose-html@0.23.0
change-case@0.6.3
color-picker@2.2.3
cursor-blink-interval@0.3.1
docblockr@0.8.7
double-tag@0.4.0
emmet@2.4.3
escape-utils@0.5.3
file-icons@1.7.25
language-blade@0.26.2
language-rust@0.4.8
language-twig@1.6.3
language-vue@0.21.0
maybs-quit@1.3.0
merge-conflicts@1.4.4
pigments@0.37.0
sort-lines@0.14.0
todo-show@1.8.0
toggle-quotes@1.0.0
```

### Versions
```
macOS 10.11.5
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.6.4
```

**Comment by 50Wliu** [comment]
@r3oath if the issue still occurs in safe mode, then please open a new issue.  Thanks!
