### ISSUE TITLE
Error: Running without the SUID sandbox! 

### ISSUE THREAD

**Issue by Joshua-Anderson** [atom/atom#13149]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Atom mysteriously stopped working with `[30501:1104/210118:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.`

I've been using atom `1.11.2` for several weeks now, but today it stopped working. I installed using the official Debian package.

### Steps to Reproduce

1. `atom -f --safe`

**Expected behavior:** I expected atom to start

**Actual behavior:** Atom crashed with error message above

### Versions

```
OS      : Ubuntu 16.10
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by Joshua-Anderson** [comment]
Hmm. It looks like I had a stale atom socket in`/tmp` which caused the crash. Could possibly be better documented in the crash dialog or the console log.

**Comment by dominicbarnes** [comment]
I'm seeing this error on Ubuntu 16.04 after updating to Atom 1.12.0. I've tried deleting the aforementioned socket, but it isn't working for me.

**Comment by Joshua-Anderson** [comment]
I think this error is a red herring, as I believe atom on linux does not run in the suid sandbox. The actual error is likely elsewhere but not logged.

**Comment by dominicbarnes** [comment]
Gotcha, that sounds totally plausible, I wish I had something more that I could use to report this issue as it's a huge pain not being able to start Atom. :(
