### ISSUE TITLE
Atom Crashes when saving c++ files

### ISSUE THREAD

**Issue by jorge-sepulveda** [atom/atom#13146]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I am trying to edit c++ files on my network drive and atom just crashes when I try to save the file. I moved the folder to a local spot on my computer and it still crashes when attempting to save
### Steps to Reproduce

1. [First Step]: Open a file(I used a c++ file)
2. [Second Step]: hit CTRL+s or save
3. [and so on...]: Program crashes on me.

**Expected behavior:** the file to actually save

**Actual behavior:** Program crashes when saving. 

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.12.5
npm  3.10.5
node 4.4.5
python
git
visual studio

Running on a lately updated Windows 10 machine.

**Comment by 50Wliu** [comment]
Is this reproducible in safe mode (`atom --safe`)?

**Comment by jorge-sepulveda** [comment]
Yes, I just tried to save a file and same issue occured

**Comment by Ben3eeE** [comment]
Please completely fill out the issue template. Does this always happen with a specific file or with many files? Can you share the file?

**Comment by Ben3eeE** [comment]
Also share the latest dump file located in `%localappdata%\temp\Atom Crashes` from when this crash happens.

**Comment by Policy51** [comment]
I have just attempted to save a C++ using Atom and Atom in safemode, both files saved successfully and had no problems.

**Comment by pc23** [comment]
I have saved the C++ file using Atom application for that and the file was save successfully had no any problems.

**Comment by adsfgg** [comment]
I wrote a simple C++ file and saved it with CTRL+S with no issues. Saving also works in safe-mode.

As others have suggested; uploading the file you were trying to save, or the dump file, would be a huge help.

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13146#issuecomment-258577718 and https://github.com/atom/atom/issues/13146#issuecomment-258577414. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by jorge-sepulveda** [comment]
I'll give it a try on my end from here.

**Comment by pc23** [comment]
I have just attempted to save a C++ using Atom and the file  saved successfully and had no problems.
