### ISSUE TITLE
Syntax Highlight Error after "&"

### ISSUE THREAD

**Issue by MatPA1** [atom/atom#13142]
Beta Version: 1.12.0-beta7
File code type: HTML (Liquid),(Go),(Rails),(Mustache),(Ruby - ERB).
MacOs: 10.12.1

Syntax highlight color error occurs after the use of symbol "&" all text after becomes purple.

<img width="924" alt="screen shot 2016-11-03 at 23 56 37" src="https://cloud.githubusercontent.com/assets/22709328/19989847/35e31382-a221-11e6-9388-19e3156363de.png">

After removing symbol, text returns to normal until it hits another.

<img width="930" alt="screen shot 2016-11-03 at 23 57 30" src="https://cloud.githubusercontent.com/assets/22709328/19989866/505d7324-a221-11e6-8f3d-5c35114b7daf.png">

**Comment by 50Wliu** [comment]
This will be fixed in Atom 1.13.
