### ISSUE TITLE
Feature Request: Drag and drop files from the tree view into browser to open in browser (similar to how the open file tabs can be dragged in)

### ISSUE THREAD

**Issue by davidsanders** [atom/atom#13145]
### Feautre Breakdown

1. Drag file from the tree view.
2. Drop file into browser (omnibar)
3. File is opened and rendered

Presently you can drag an open file tab into the browser and it will open/render. Can we get the same functionality from the tree view?

**Comment by bmario** [comment]
I'm answering to get this out of stale because I'd love to get this feature. 
It is not implemented as of version 1.23.2 on Mac OS X.

**Comment by 50Wliu** [comment]
@bmario please create a new issue on [atom/tree-view](https://github.com/atom/tree-view) if it doesn't already exist.  Thanks!
