### ISSUE TITLE
Project has minified SVG file open -> eternal freeze loop

### ISSUE THREAD

**Issue by Bram-Zijp** [atom/atom#13144]
My Atom has an large SVG file of 2MB open in a project and now i can't open the project  folder in atom without freezing it.

**Comment by thomasjo** [comment]
Please provide more information — fill in the details we request in the default [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md).
Unless the requested information is provided in a timely manner, this issue will be closed.

---
For future reference, consider reading 
https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs.
