### ISSUE TITLE
Frame drops and sluggishness with gSync

### ISSUE THREAD

**Issue by eedahl** [atom/atom#13158]
### Description
Frame rate drops to 2-20 fps, slow to pick up when I start working again: feels sluggish and laggy. On gSync monitor. Similar to an issue in Visual Studio Code, except I don't have to fullscreen with Atom:
https://github.com/Microsoft/vscode/issues/5516
Like in VS Code, running atom --disable-gpu makes it work as expected.

### Steps to Reproduce
Have gSync enabled in windowed and full screen and open Atom.

**Expected behavior:** Fps to full refresh rate of monitor and high responsiveness.

**Actual behavior:** Frame rates as low as 2-20 fps when idle, slow to pick up when I start working again: feels sluggish and laggy.

### Versions

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by 50Wliu** [comment]
Is this reproducible in safe mode (`atom --safe`)?  Are you willing to try the 1.12 betas to see if that resolves the problem?

**Comment by eedahl** [comment]
It happens in safe mode as well, and the issue is not resolved in beta 1.12. According to https://github.com/Microsoft/vscode/issues/15074 it is an issue with Electron.

**Comment by 50Wliu** [comment]
Thanks for the update!  Marking this as blocked on Electron then.
