### ISSUE TITLE
Shake Screen effect of Active Power Mode Package in Gnome Classic is not working

### ISSUE THREAD

**Issue by nguyen47** [atom/atom#13155]
### Prerequisites

* [ yes] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [yes ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [yes ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [yes ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ no] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [yes ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Shake Screen at Active Power Mode in Gnome Classic is not working

### Steps to Reproduce

1. Launch Ubuntu at Gnome Classic mode
2. Launch Atom
3. Install Active Power Mode Package
4. Notice that shake screen effect is not working

**Expected behavior:** 
Shake Screen is work well

**Actual behavior:** 
Shake Screen is not working

### Versions

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

Packages installed
├── activate-power-mode@1.1.0
└── autoclose-html@0.23.0

**Comment by Ben3eeE** [comment]
The [activate-power-mode](https://github.com/JoelBesada/activate-power-mode/issues) package repository is where you want to report this issue. Please reopen this issue there.
