### ISSUE TITLE
Keymap copy-pase doesn't escape backslash

### ISSUE THREAD

**Issue by TravisDart** [atom/atom#13167]
I want to change the keybinding for "cmd-\\". The Settings say that I can override these keybindings by clicking on the copy button pasting them into your keymap file. When I do so for cmd-\\, this is what is pasted:

    '.platform-darwin':
      'cmd-\': 'tree-view:toggle'

However, when I go to save the file, it gives me an error: 

    Failed to load /Users/oscargarcia/.atom/keymap.cson
    [stdin]:38:29: error: missing '
      'cmd-\': 'tree-view:toggle'

The correct syntax is to escape the backslash like so:

    '.platform-darwin':
      'cmd-\\': 'tree-view:toggle'

This is a minor bug for an unusual use case, but I thought I would mention it.

Atom 1.11.2
OS X 10.11.6

**Comment by 50Wliu** [comment]
Can you please reopen this on the atom/settings-view repository?  Thanks.

**Comment by TravisDart** [comment]
Turns out this issue is a duplicate of https://github.com/atom/settings-view/issues/363.
