### ISSUE TITLE
Keymaps with same selector declared multiple times should produce an error popup

### ISSUE THREAD

**Issue by delackner** [atom/atom#13165]
### Prerequisites

* [ y] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [y ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ y] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ y] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [y ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ y] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Keymap.cson containing the same selector twice will silently fail to map all but the final one.  This is mentioned in a comment in the default version of the file, but having long ago replaced the entire contents of the file, it is easy to end up scratching your head wondering why your keymap is not working, and no error popup is generated.

At the very least a warning popup should appear when you save a keymap with the same selector twice, since there is no useful reason to have such a file.
 
### Steps to Reproduce

1. create a keymap with 

'.platform-darwin atom-workspace atom-text-editor':
  'shift-cmd-J': 'editor:move-line-up'

'.platform-darwin atom-workspace atom-text-editor':
  'shift-cmd-K': 'editor:move-line-down'

2. save

**Expected behavior:** [What you expected to happen]
Warning or error popup.

**Actual behavior:** [What actually happened]

Silent failure.

### Versions
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.12.0 and should produce an error notification.

**Comment by delackner** [comment]
Oh cool!  I checked for updates before posting, but it said I was current.

**Comment by 50Wliu** [comment]
Sorry, should have clarified: Atom 1.12 is currently in beta and should be stable sometime later this month.
