### ISSUE TITLE
Portable version for macOS

### ISSUE THREAD

**Issue by jaredreich** [atom/atom#13164]
I would LOVE to use two different portable version of Atom running at the same time, not sharing ANYTHING between them.

It seems this is available for Windows users with something like this:
https://github.com/garethflowers/atom-portable

But no love for macOS 😢

**Comment by bronson** [comment]
PortableApps claim you can use their stuff on MacOS using Wine.

It seems like lack of OSX support is a PortableApps issue, not an Atom issue...?

**Comment by jaredreich** [comment]
Thanks for that pointer, but the "PortableApps" usage was just an example. Ideally Atom would offer proprietary portable versions.

**Comment by damieng** [comment]
You can do this today by setting ATOM_HOME before you launch the second copy. You could even copy the existing atom shell script and put this in and call it atom2 or something.  `export ATOM_HOME=~/.atom2`
