### ISSUE TITLE
Unwanted diff when editing files created in other editor.

### ISSUE THREAD

**Issue by ankitrg** [atom/atom#13175]
I created a file in sublime sometime back, now I am trying to use atom to edit it. When I change even one line of code, there are unwanted diffs at several places. How can I solve this?

**Comment by Ben3eeE** [comment]
Check the settings of the whitespace package and ensure that Atom is using the correct encoding.

[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.
