### ISSUE TITLE
Build Linux 32bit Pulls 64bit Electron

### ISSUE THREAD

**Issue by progkix** [atom/atom#13179]
Finally managed to get the build to go all the through on Fedora 24 **32bit** architecture but it will will not run.

As the build was progressing, I noticed that it downloaded the **64bit** version of Electron 1.3.6.

Is there any way to specify the architecture to build for? I've got several 32bit Linux machines still humming along and I'd really like to get this to work on them.

Thanks in advance

**Comment by 50Wliu** [comment]
I was under the impression that this was recently fixed.  Can you try pulling from master, running `script/clean`, and trying again?

**Comment by progkix** [comment]
Building 1.13.0-beta0 right now

**Comment by progkix** [comment]
Didn't mean to close it yet.

Building 1.13.0-beta0 right now

**Comment by progkix** [comment]
I can now confirm that it does indeed download Electron 32bit 1.3.6 during the build process.

**Comment by Ben3eeE** [comment]
Check out the PR that fixed this https://github.com/atom/atom/pull/13001 if you want to build 1.12 32bit.

**Comment by progkix** [comment]
And the 32bit build on Fedora installed and started up as expected
