### ISSUE TITLE
Cant install packages because of Windows username

### ISSUE THREAD

**Issue by GeekMediaDK** [atom/atom#13178]
I cant install or manage any packages in Atom, because it cant hand that in my username there is a "&".

It gives me this error:
'C:\Users\C' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.

My username is C&C

Running versin 1.12 of atom

**Comment by ungb** [comment]
I was able to repro this issue.  

I created a new user on windows 10, Username as C&C.  Login as that user and installed atom 1.12.0.

I open atom and attempt to install a package, but get the same error as above.

![image](https://cloud.githubusercontent.com/assets/5624870/20196224/9a6bf5ee-a74e-11e6-9148-479d0904286d.png)

**Comment by aredfox** [comment]
+1 Have the same issue where my username contains the characters _".."_ and _"!"_. The username is _"..LeRenard!"_ and shows up correctly in atom's titlebar as "Welcome Guide - C:\Users\..LeRenard!\.atom - Atom", yet when opening the "Install a Package" or "Choose a Theme" it fails on the _"!"_ character as it omits that, like the C&C by @GeekMediaDK.

![nokatom](https://cloud.githubusercontent.com/assets/1333704/20298963/fb278556-ab18-11e6-92fc-ae0086bdb633.JPG)

**Comment by EGO7000** [comment]
Hi!
You forgot to add the brackets "&^|**()**"!

**Comment by damieng** [comment]
Brackets do not require quotes around them.  You can test the problematic ones that need quoting by doing this;

`cmd /c echo hi > test.txt` works fine
`cmd /c echo hi > test&.txt` fails - needs quoting
`cmd /c echo hi > test|.txt` fails - needs quoting
`cmd /c echo hi > test^.txt` fails - needs quoting
`cmd /c echo hi > test(1).txt` works fine

Can you explain what actual problem you are having? Ideally in a new issue.

**Comment by EGO7000** [comment]
I have already created issue #13346 and it was labeled as "dublicate" for this issue..
