### ISSUE TITLE
Viewing "Install / Atom Chrome" causes editor to crash

### ISSUE THREAD

**Issue by wolfgang42** [atom/atom#13183]
### Prerequisites
* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
No. I also can't reproduce it with `--foreground`. I'm looking for information on how to diagnose this.
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
Yes, 1.12.0.
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
Yes, it's the main editor that's crashing.
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
Yes, I don't see anything promising there.

### Description
When I look at the package description for `atomic-chrome` (not even trying to install it!), Atom crashes.
This is fairly reproducible under the specific conditions that:
* I start `atom` with no flags.
* I look at `atomic-chrome`.

It doesn't seem to happen with any other plugin about pages, and I can't find any logs (I looked in `~\.atom`, `~\atom`, my home folder, and Event Viewer under Windows Logs: Application). Also, `--log-file` doesn't actually seem to create a log file anywhere I can find.

### Steps to Reproduce
1. Open Settings.
2. Go to Install.
3. Click `atomic-chrome`.
4. Scroll up and down for a few seconds.

**Expected behavior:** It works normally.
**Actual behavior:** "Editor has crashed" dialog.

### Versions
Atom: 1.12.0
Windows 10 Pro 64-bit

**Comment by wolfgang42** [comment]
Updated description to actually have content. (Apparently <kbd>Shift</kbd><kbd>Enter</kbd> means "submit this form". Oops.)

**Comment by Ben3eeE** [comment]
Can reproduce on `Atom 1.13.0-beta0` Windows 10 64-bit.

**Comment by Ben3eeE** [comment]
![acrash 3](https://cloud.githubusercontent.com/assets/1058982/20189625/598ba738-a77e-11e6-93ae-23c1cdd6ee10.gif)

**Comment by Policy51** [comment]
Tried to reproduce using Atom 1.13.0-beta1
Windows 10 64bit

Didn't have any problems

**Comment by Policy51** [comment]
Tried to reproduce using Atom `1.13.0-beta1` Windows 10 64 Home.
Worked as intended.

**Comment by sabski** [comment]
I have the same issue on version 1.12.7 after opening the page to update a plug-in, the editor crashes and even reinstall doesn't work.

**Comment by wchrismontgomery** [comment]
Cannot reproduce on version 1.14.4, Windows 10 Home 64-bit.

**Comment by balderclaassen** [comment]
@wolfgang42 @Ben3eeE is this still an issue on the current version? I ask because it's been a while and 2 people have been unable to reproduce. Maybe this can be closed?

@sabski  This issue is about a specific plugin's page, if you have this problem with all/several plugins I think it's best to make a separate issue if you haven't already.

**Comment by Ben3eeE** [comment]
Unable to reproduce. Thanks @balderclaassen 🙇
