### ISSUE TITLE
"Editor not responding" message is misleading

### ISSUE THREAD

**Issue by alexrussell** [atom/atom#13191]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
    * Well, I tried, but there's a lot of noise around "not responding"

Admittedly, some of these steps seemed pointless to me (safe mode, etc.) so I have checked them without actually performing them. However, I'm pretty sure it's the correct repo, and I did try to search for a pre-existing issue.

### Description

The "not responding" messages clearly states that an editor is not responding. To most people that would mean the current tab. However, if you click "closed editor" the whole entire window is closed. This, in my experience, breaks user expectation.

See screenshot in #9185.

### Steps to Reproduce

1. Find a way to get a "not responding" message box up
2. Click on "Close"
3. Cry when it takes away everything you were working on

**Expected behavior:** Obviously it depends on what is actually unresponsive, but if, as it was in my case, it's because you decided to click on a minified JS file in the treeview (and after about 50ms you *knew* it was a bad idea), it'd be great to constrain the collateral damage to the currently open editor/tab/textbuffer (whatever it is) and only take that down (like Chrome does).

If it is a plugin that's running 'globally' or something similar, then of course, the window probably needs to burn.

But in the real world, I'm guessing it's not easy (if not impossible) to differentiate between the two (I bet syntax parsing/highlighting all happens in the big main thread as we're talking JS here right?). So, as a compromise, maybe just make the message say that the *window* will go bye-bye, not the "editor" (as it's not clear to normal users what "editor" means.

**Actual behavior:** The message says the *editor* is not responding, but the whole window goes if you click "close".

### Versions

```
❯ atom-beta --version
Atom    : 1.13.0-beta0
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

```
❯ apm-beta --version
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.3
```

OSX 10.11.6.

**Comment by Ben3eeE** [comment]
Hey, We currently have a PR open for improving the text and buttons on this dialog. Maybe you can post a comment there with your ideas https://github.com/atom/atom/pull/12750.

**Comment by alexrussell** [comment]
Cool, will close this in favour of #12750 then.
