### ISSUE TITLE
/usr/bin/atom: line 111: 13463 Segmentation fault  

### ISSUE THREAD

**Issue by chanble** [atom/atom#13190]
atom -f .
[13463:1111/131853:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[13463:1111/131853:ERROR:edid_parser.cc(181)] invalid EDID: human unreadable char in name

<--- Last few GCs --->

   33461 ms: Mark-sweep 1403.7 (1466.5) -> 1403.7 (1466.5) MB, 1546.6 / 0.1 ms [allocation failure] [GC in old space requested].
   35004 ms: Mark-sweep 1403.7 (1466.5) -> 1403.7 (1466.5) MB, 1543.3 / 0.1 ms [allocation failure] [GC in old space requested].
   36559 ms: Mark-sweep 1403.7 (1466.5) -> 1403.7 (1436.5) MB, 1554.7 / 4.2 ms [last resort gc].
   38134 ms: Mark-sweep 1403.7 (1436.5) -> 1403.7 (1436.5) MB, 1575.1 / 4.1 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3c16c6119579 <String[7]: file://>
    1: buildSpatialScreenLines [/opt/atom/resources/app.asar/node_modules/text-buffer/lib/display-layer.js:~508] [pc=0x14cf86bb1242](this=0x1ccfb09bbbe1 <a DisplayLayer with map 0x1da1b79d0871>,startBufferRow=0x22ec8404311 <undefined>,endBufferRow=456351)
    2: reset [/opt/atom/resources/app.asar/node_modules/text-buffer/lib/display-layer.js:223] [pc=0x14cf86af3ca9](this=0x1ccfb09bbbe...

[13491:1111/131932:ERROR:atom_bindings.cc(78)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Failed to get crash dump id.
Report Id: 
Failed to get crash dump id.
Report Id: 
/usr/bin/atom: line 111: 13463 Segmentation fault      (core dumped) "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@"

unbunt 16.04

**Comment by drewmnoel** [comment]
@chanble were you attempting to open a particularly large file? Can you also give your versions (the outputs from `atom --version` and `apm --version`)

**Comment by chanble** [comment]
> were you attempting to open a particularly large file?

yes

```shell
➜  ~ atom --version
Atom    : 1.12.0
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
➜  ~ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4
➜  ~ 
```
