### ISSUE TITLE
Atom don't run on Linux Mint system after update.

### ISSUE THREAD

**Issue by zloi-vasya** [atom/atom#13196]
I try atom --safe, try to reinstall, and try to install package from atom.io web-site. 
Several times I saw a message box:
![photo_2016-11-11_19-50-27](https://cloud.githubusercontent.com/assets/13254668/20218809/2141beb0-a848-11e6-8ba6-4fba031986d5.jpg)
 or message, if run as root: 
![image](https://cloud.githubusercontent.com/assets/13254668/20219519/a016596e-a84b-11e6-9a5d-a8e4d03ebcc4.png)

I read and make all from this instruction: http://flight-manual.atom.io/hacking-atom/sections/debugging/

~ $ ps -C atom 
  PID TTY          TIME CMD
 1526 pts/2    00:00:15 atom
 1557 pts/2    00:00:15 atom
 1602 pts/2    00:00:12 atom
 1642 pts/2    00:01:40 atom
 1714 pts/2    00:01:44 atom
 2954 pts/2    00:12:31 atom
 2956 pts/2    00:11:54 atom
 3006 pts/2    00:11:59 atom
 3880 pts/2    00:00:10 atom
11841 pts/2    00:11:52 atom
19801 pts/2    00:09:04 atom
19890 pts/2    00:09:08 atom
20106 pts/2    00:09:03 atom
22957 pts/2    00:02:17 atom
23254 pts/2    00:04:55 atom
25628 pts/2    00:03:44 atom
28313 pts/2    00:03:35 atom
31505 pts/2    00:01:51 atom

~$ atom --version
Atom    : 1.12.1
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

~$ apm --version 
apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.6
git 1.9.1

**UPD: Last beta work only one time from root!**

**Comment by vwugd97** [comment]
Same here on Debian (Linux xxxx 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux)

root@xxxx:/home/dmeiswinkel# atom --version
Atom    : 1.12.1
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

The editor won't open when started from commandline (bash) works fine when I'm starting it from the Icon.

**Comment by vwugd97** [comment]
btw. this looks like a dup of https://github.com/atom/atom/issues/13192

**Comment by zloi-vasya** [comment]
@vwugd97 But it worked fine before today. Start from icon with errors 
![image](https://cloud.githubusercontent.com/assets/13254668/20220784/aadee99c-a850-11e6-9db3-d4d9b8a2fd1b.png)
I changed the access rights to the folder ~/.atom, and the problem was solved, but I did not think that they may be wrong

**Comment by zloi-vasya** [comment]
I start atom from command line, and new bash process eat my cpu. I killed some bash process and saw atom window) Thx for link to #13192)
