### ISSUE TITLE
Github for windows show that the of all the lines below the changes, instead the lines that I actually changed

### ISSUE THREAD

**Issue by Guy-Markman** [atom/atom#13207]
When I change a file using atom, GitHub for windows will show that the whole file changed instead of the actually lines I changed.
For example:
I used python file for it. Couldn't produce it with text.
Original file
1234
5678

The change I made:
1234
7
5678.
When I edit the file using basic text editor (notepad in my test)
 1234
 +7
  5678
And it show that there was one addition to file.

When I do the same thing but with atom:
 -1234
 -5678 
 +1234
 +7
 +5678
And it shows there was 3 additions and 2 deletion.
How can I fix it? Is it problem with atom, GitHub for windows or just my settings?

**Comment by Guy-Markman** [comment]
Changed the title

**Comment by 50Wliu** [comment]
What are the line endings of the file before and after the change?

**Comment by Guy-Markman** [comment]
If I understood you corectly, Empty line

**Comment by Guy-Markman** [comment]
Windows 8.1
Atom    : 1.12.2
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

Do you need more information?

**Comment by Guy-Markman** [comment]
git diff and git gui (from gitshell) works ok

**Comment by 50Wliu** [comment]
What does the line ending selector in the status bar show before/after the change?
![line-ending-selector](https://cloud.githubusercontent.com/assets/2766036/20243372/c11eae5e-a922-11e6-80d0-2222c0dffa8d.png)

**Comment by Guy-Markman** [comment]
CRLF

**Comment by 50Wliu** [comment]
Ok.  Since that resolved the issue I'm closing this.

**Comment by Guy-Markman** [comment]
I think you should keep it open.
Atom should work with CRLF.

**Comment by 50Wliu** [comment]
It does - nearly all the files within the Atom repo have CRLF line endings, and GitHub Desktop works perfectly for them.
