### ISSUE TITLE
[v1.13-beta] When two pane exist and destroy one pane, remaining editor does not focused

### ISSUE THREAD

**Issue by t9md** [atom/atom#13206]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

When last paneItem(editor) was closed and pane was destroyed, remaining paneItem(editor) not correctly focused so I have to manually click by mouse.
It's very tedious, this issue is only happens in current beta(v1.13.0-beta2), no issue in stable(v1.12.1).

Maybe shadowDOM removal have some cause.

### Steps to Reproduce

- Confirm `Remove Empty Panes`(`core.destroyEmptyPanes`) is `true`(this is default value).
- Open some text-editor.
- Split editor into **two** by `cmd-k right`(or `cmd-k down` is OK), the point is **there are two panes in workspace**.
- Close pane item by `cmd-w`, then that pane is destroyed.
- The remaining editor on remaining pane don't get focused(expected: focus to remaining editor)

#### v1.12.1: OK no issue

- before: close editor

```
> atom.workspace.getPanes()
  [Pane, Pane]
> document.activeElement
  <atom-text-editor class=​"editor vim-mode-plus normal-mode" tabindex=​"-1" data-grammar=​"source coffee" data-encoding=​"utf8">​…​</atom-text-editor>​
```

- after: close editor and pane destroyed, remaining editor get focused.
```
> atom.workspace.getPanes()
  [Pane]
> document.activeElement
  <atom-text-editor class=​"editor vim-mode-plus normal-mode" tabindex=​"-1" data-grammar=​"source coffee" data-encoding=​"utf8">​…​</atom-text-editor>​
```

#### v1.13.0-beta2: NG remaining editor is not focused where it should.

- before: close editor
```
> atom.workspace.getPanes()
[Pane, Pane]
> document.activeElement
<input class=​"hidden-input" tabindex=​"-1" data-react-skip-selection-restoration=​"true" style=​"transform:​ translateZ(0px)​;​ top:​ 0px;​ left:​ 0px;​ width:​ 7px;​ height:​ 18px;​">​
```

- after: close editor and pane destroyed, remaining editor doesn't get focused.
```
> atom.workspace.getPanes()
[Pane]
> document.activeElement
<body tabindex=​"-1" class=​"platform-darwin is-blurred">​…​</body>​
```

- after: I mouse clicked editor, editor get focused.
```
> document.activeElement
<input class=​"hidden-input" tabindex=​"-1" data-react-skip-selection-restoration=​"true" style=​"transform:​ translateZ(0px)​;​ top:​ 0px;​ left:​ 0px;​ width:​ 2px;​ height:​ 18px;​">​
```

### Versions

```
Atom    : 1.13.0-beta2
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

**Comment by nathansobo** [comment]
cc @iolsen @ungb If this is truly a regression it needs to block the release.

**Comment by ungb** [comment]
@nathansobo @iolsen I am able to repro the issue on 1.13-beta6. it works fine on stable 1.12.5.

**Comment by damieng** [comment]
Confirmed broken as far back as 1.13-beta0
