### ISSUE TITLE
Display Issue (Bad Colour Choice) for Restart Notification

### ISSUE THREAD

**Issue by pingshunhuangalex** [atom/atom#13205]
With the latest Atom version 1.12.2, the following issue remains...

It happens when the below notification is triggered (after updating packages that require restart). It's just a bad choice of color which makes it almost impossible to see the restart text on the button both before and after the clicking.
![image](https://cloud.githubusercontent.com/assets/17170199/20234956/a6b806b2-a8d9-11e6-8765-e347948d9fe5.png)

Meanwhile, an associated issue is after I restart Atom by clicking the button, there will still be a squirrel icon showing at the bottom right corner, reminding me to restart Atom for the updated packages to take effect. I have to manually close and open Atom again to make it go away.

Not a big issue, but hopefully it'll be fixed later. Thanks.

**Comment by 50Wliu** [comment]
What UI theme are you using?  You'll want to report it to the author of that theme.

**Comment by pingshunhuangalex** [comment]
Still, the restart squirrel thing should belong to Atom team, right?

**Comment by 50Wliu** [comment]
The squirrel icon indicates that there is an Atom update available, not a package update.
