### ISSUE TITLE
Cycling through many tabs does not show tab title when Atom is not full width of screen

### ISSUE THREAD

**Issue by monolux** [atom/atom#13212]
Atom version: 1.11.2
OS: Windows 7 64 SP1

As per
[https://discuss.atom.io/t/keyboard-shortcut-for-cycling-through-tabs/698](https://discuss.atom.io/t/keyboard-shortcut-for-cycling-through-tabs/698)

I added
```
'body':
  'ctrl-tab': 'pane:show-next-item'
  'ctrl-shift-tab': 'pane:show-previous-item'
```
to the config file.

Now when I have 10+ tabs open but Atom occupies half the screen and I cycle to a tab that is further down the line the pane does open correctly, however it does not show the tab title in the menu bar.

1. Like this I have to guess what file I am working on.
2. Also the path to the file has to be guessed like this as I cannot hover of the tab title and see the path.
3. I can see the filename and extension in the bottom left corner, however hovering over that link does not show the path, I have to click to have the path displayed plus the path is then copied to the clipboard. What if I already have other data in the clipboard that I like to copy from one file to another file.

How can I get Atom to also actively display the tab title, including the show full path on hover functionality, in the menu bar please?

Thank you for your help.

**Comment by Ben3eeE** [comment]
In Atom 1.12 the tabs on the tab bar will be automatically scrolled in to view if not visible when activated.
