### ISSUE TITLE
Issues with autoformating

### ISSUE THREAD

**Issue by michaldybczak** [atom/atom#13214]
Version 1.11.2-1 on Manjaro.

When having various numbers for various paragraphs, atom overrides them with **1.** on save. My friend also noticed issue when using markdown within one word like for example "**pac**kage", atom is puting space on save so the word is split.

Is there any way to turn off such behaviour. It's very annoying. I didn't find anything in options.

**Comment by 50Wliu** [comment]
Please open a new issue and **completely** fill out the provided issue template.
