### ISSUE TITLE
Lost my html code on crash of Atom

### ISSUE THREAD

**Issue by OmKessarwani** [atom/atom#13215]
version 1.11.2

If there any way which anyone know pls help me on this, that was very important me

**Comment by 50Wliu** [comment]
The recovered files should be available in your `~/.atom/recovery` directory.

In the future, please **completely** fill out the provided issue template.  In addition, questions like these are better suited for [Discuss](https://discuss.atom.io), the official Atom forum.

**Comment by OmKessarwani** [comment]
Nothing is there..

**Comment by 50Wliu** [comment]
Like I said previously, please **completely** fill out the provided issue template if you would like for this issue to be reopened. In addition, questions like these are better suited for [Discuss](https://discuss.atom.io), the official Atom forum.
