### ISSUE TITLE
Screen goes blue after switching workspace in Linux

### ISSUE THREAD

**Issue by schvabodka-man** [atom/atom#13210]
### Description

Hello! 
I'm running manjaro linux with proprietary amd drivers and i3 windows manager. Sometimes, when i switch from atom to another workspace(browser for example) and switch back to workspace with atom, atom goes *blue* like that:

![alt tag](https://transfer.sh/YbAV8/screenshot-2016-11-13-10-08-37.png)

Sometimes atom become to look like normal, someties only closing editor and reopening it again helps

### Steps to Reproduce

1. Open atom
2. Change workspace
3. Change workspace again
4. Sometimes atom screen goes blue

### Versions

atom - 6.5.0
apm - 1.14.1
catalyst - 2016.09-1
compton - 0.1_beta 2.5.3
i3 - i3-gaps 4.12.1-1

**Comment by arcticicestudio** [comment]
Does this happen only with Atom or other applications that are based on Electron / Node?

> Versions
atom - 6.5.0

Also there is no version `6.5.0` of Atom, [`1.12.2`](https://github.com/atom/atom/releases/v1.12.2) is the latest stable release.
You can replace this with the output from the `atom --version` command.

**Comment by schvabodka-man** [comment]
Yes, it goes in every electron app. Here is screenshot of electron with exactly same trouble
![alt tag](https://transfer.sh/Wz8In/screenshot-2016-11-13-10-27-53.png)
![alt tag](https://https://transfer.sh/MQpJ2/screenshot-2016-11-13-10-28-23.png)
But in vivaldi(which has the same chromium engine) everything works fine and there are no blue screen
My versions of atom and electron are
Atom    : 1.11.2
Electron: 1.4.6
Chrome  : 53.0.2785.143
Node    : 6.5.0

**Comment by 50Wliu** [comment]
> Electron: 1.4.6

You are running an unsupported Atom distribution.  Please uninstall it and reinstall from https://atom.io.  In addition, since this appears to be an Electron-related issue, please create an issue on electron/electron instead.
