### ISSUE TITLE
XML Syntax does not work anymore

### ISSUE THREAD

**Issue by mcharron** [atom/atom#13229]
### Prerequisites

* [ ] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Since I updated to 1.12.2, my XML files with DOCTYPE aren't colorized. I tried every single color syntax which are builded with Atom, and no one works.

### Steps to Reproduce

1. Set your prefered syntax coloration
2. Open an XML file

**Expected behavior:** XML tags colorized

**Actual behavior:** XML is open without any colorization

### Versions

mcharron@mcharron ➜ ~ atom --version
Atom    : 1.12.2
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
mcharron@mcharron ➜ ~ apm --version  
apm  1.12.9  
npm  3.10.5  
node 4.4.5  
python 2.7.12  
git 2.7.4  
mcharron@mcharron ➜ ~ lsb_release -a  
No LSB modules are available.  
Distributor ID:	Ubuntu  
Description:	Ubuntu 16.04.1 LTS  
Release:	16.04  
Codename:	xenial

**Comment by xahon** [comment]
Is there at the right bottom corner any syntax selected?

**Comment by mcharron** [comment]
Yes, XML is selected.

**Comment by xahon** [comment]
Make a screenshot, please

**Comment by mcharron** [comment]
![atom-problem](https://cloud.githubusercontent.com/assets/6449337/20310769/7b0af238-ab4d-11e6-93e7-29753ddf57d8.png)
![atom-problem2](https://cloud.githubusercontent.com/assets/6449337/20310768/7b09fb12-ab4d-11e6-9464-fb4579c1990b.png)

I had to blur most of the XML because the data can be sensible on some points.

As you can see on first screenshot, no syntax colorization is done.
On the second, syntax colorization is done, and I don't know why on the first it won't colorize.

The first XML contains 33866 lines, the second 19798.

**Comment by 50Wliu** [comment]
What is the output of `apm list --installed`?

**Comment by mcharron** [comment]
Here is the output : 

Community Packages (15) /home/mcharron/.atom/packages
├── atom-beautify@0.29.13
├── atom-php-navigation@0.6.0
├── autoclose-html@0.23.0
├── editorconfig@2.0.5
├── file-watcher@0.4.0
├── language-apache@1.7.0
├── language-twig@1.6.3
├── linter@1.11.18
├── linter-phpcs@1.5.3
├── linter-phpmd@1.5.2
├── markdown-pdf@1.5.0
├── pigments@0.37.0
├── revert-buffer@0.5.0
├── selection-highlight@0.1.5
└── tasks@2.6.4

**Comment by damieng** [comment]
Syntax highlighting is disabled for files beyond a certain size for performance reasons.

**Comment by mcharron** [comment]
Ok, thank you !
