### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by hackereg35** [atom/atom#13225]
i get this error when installing or searching for any package
`(node:14995) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.`

os : arch linux i686
kernel : 4.8.6-1-ARCH

**Comment by 50Wliu** [comment]
Please open a new issue and **completely** fill out the provided issue template.  Thanks!

**Comment by hackereg35** [comment]
that is the issue, if i want to download a package from atom ui i get this error and then it exits, but installing from terminal give me the same error but it does not exit
