### ISSUE TITLE
Why atom is trying to create /usr/etc during make? Please don't do it

### ISSUE THREAD

**Issue by mpkh** [atom/atom#13221]
it breaks building inside sandbox

```
**Installing apm
 * ACCESS DENIED:  mkdir:        /usr/etc
```

Thank you

**Comment by thomasjo** [comment]
How are you building Atom? Neither Atom or apm touches `/usr/etc`. Judging from the referenced issue's repository, you are patching Atom source files... are you positive you aren't doing something wrong?

Try building from pristine, official [source code](https://github.com/atom/atom/releases/tag/v1.12.2) without _any_ patching.

**Comment by mpkh** [comment]
@thomasjo yes, that version is using few patches to clarify build environment, I can try running clean version to see if that could be related or not.

**Comment by 50Wliu** [comment]
@mpkh yes, it would be appreciated if you could do that.

**Comment by damieng** [comment]
Did you find out what was referencing /usr/etc ?

**Comment by mpkh** [comment]
@damieng not yet, I will close it for now and will reopen later than
