### ISSUE TITLE
`script/build` does not accept any options

### ISSUE THREAD

**Issue by paulmenzel** [atom/atom#13232]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Passing `help` or `--help` to `script/build` does not work.

### Steps to Reproduce

1. Download Atom 1.12.2.
2. Extract.
3. Run `script/build --help` or `script/build help`.

**Expected behavior:** [What you expected to happen]

The help/usage should be shown.

**Actual behavior:** [What actually happened]

The script starts building and installing Atom.

### Versions

1.12.2

**Comment by damieng** [comment]
`script/build --help` does actually output build options however it first has to check the various dependencies/versions of things. The very first time that might take several minutes as it downloads and builds various npm and apm packages.  Subsequent runs should only be a few seconds;

```
root@atom-deb:/home/damieng/Source/atom# script/build --help
Node:	v4.4.7
Npm:	v3.10.5
Installing script dependencies
Installing apm
Installing modules ✓
Wrote Dependencies Fingerprint: /home/damieng/Source/atom/node_modules/.dependencies-fingerprint 6dcf8451e00072b50676fd6878dfc9a7b02105f1
Usage: /usr/bin/nodejs script/build [options]

Options:
  --help                      Show help                                               [boolean]
  --code-sign                 Code-sign executables (macOS and Windows only)
  --create-windows-installer  Create installer (Windows only)
  --create-debian-package     Create .deb package (Linux only)
  --create-rpm-package        Create .rpm package (Linux only)
  --compress-artifacts        Compress Atom binaries (and symbols on macOS)
  --install                   Install Atom
```

**Comment by iolsen** [comment]
I think @damieng's response closes this. Feel free to reply if not.

**Comment by paulmenzel** [comment]
@damieng, thank you for the response. In my opinion, that is a bad behavior to install anything when the user just wants to run help, and I don’t understand why that is necessary.

Looking at the code, the usage section should just be moved to the top before requiring `bootstrap`, shouldn’t it?

```
const yargs = require('yargs')
const argv = yargs
  .usage('Usage: $0 [options]')
  .help('help')
  .describe('code-sign',  'Code-sign executables (macOS and Windows only)')
  .describe('create-windows-installer', 'Create installer (Windows only)')
  .describe('create-debian-package', 'Create .deb package (Linux only)')
  .describe('create-rpm-package', 'Create .rpm package (Linux only)')
  .describe('compress-artifacts', 'Compress Atom binaries (and symbols on macOS)')
  .describe('install', 'Install Atom')
  .wrap(yargs.terminalWidth())
  .argv
```

Should I open a new issue for that?

**Comment by Ben3eeE** [comment]
We have an issue for this already https://github.com/atom/atom/issues/12978

**Comment by paulmenzel** [comment]
@Ben3eeE, thank you. Good find.
