### ISSUE TITLE
False Positive Trojan Warning? : SONAR.AM.C!g9

### ISSUE THREAD

**Issue by jgiovanettiatventera** [atom/atom#13234]
### Description

Anyone else getting a Symantec virus warning when launching Atom? 

It’s saying: 
Update.exe

Threat name
SONAR.AM.C!g9

### Atom Version:
1.12.2

Thanks :-]

**Comment by hakobo** [comment]
I just got the same warning from Norton by Symantec on Atom version 1.12.2. Here is Norton's description of the threat. https://us.norton.com/security_response/writeup.jsp?docid=2016-110121-1504-99

**Comment by damieng** [comment]
That's going to be a false positive based on that description - they are doing heuristics analysis and I would imagine seeing that update.exe downloads files from the internet and installs them on your machine (the files being the next version of Atom).

These false positives normally resolve themselves in the next update to the AV software. If not you can report it to your AV vendor.
