### ISSUE TITLE
Atom is unresponsively slow, even in safe mode

### ISSUE THREAD

**Issue by dominicbarnes** [atom/atom#13238]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Since installing v1.12, Atom has become unresponsive on my Ubuntu machine. (not seeing the same issue on macOS) It hangs for a long time during startup, to the point where Ubuntu asks if it should be forcibly quit. If I wait long enough, the UI does start up, but it is painfully slow to interact with. (safe mode helps little, if any)

I've noticed that a command `/bin/bash -ilc command env` is pegging an entire CPU, and I know it starts from [within atom](https://github.com/atom/atom/blob/d89c3a18ad715514d587361bcf5e17449c243428/src/update-process-env.js#L67). I'm not sure if this _is_ the core problem, but it sure is suspicious.

![screenshot from 2016-11-16 01-24-30](https://cloud.githubusercontent.com/assets/160197/20341556/8971fa8a-ab9b-11e6-86d2-c13dfe23d392.png)

### Steps to Reproduce

For me, this happens any time I start up atom, I can't figure out any workaround to make it stop.

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

```
 $ atom --version
Atom    : 1.12.2
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4

$ lsb_release -irc
Distributor ID:	Ubuntu
Release:	16.04
Codename:	xenial

$ uname -or
4.4.0-47-generic GNU/Linux
```

**Comment by jorgerc85** [comment]
@dominicbarnes, I have the same issue. I've found that this only happens when running atom from the command line. If I open atom using the launcher it loads fine and the `/bin/bash -ilc command env` process is not started. I am running exactly the same setup.

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.12.3.

**Comment by ItsNickBarry** [comment]
This is still happening on 1.12.3.

**Comment by 50Wliu** [comment]
Are you by any chance using the Webupd8 PPA?

**Comment by ItsNickBarry** [comment]
Yes.

**Comment by dominicbarnes** [comment]
@jorgerc85 gotcha! Yeah, it seems I have the same issue. I typically launch from the terminal, but I tried launching via the launcher and it works a lot better. (and the `command env` isn't kicked off, as you described)

I'm afraid the issue hasn't gone away with v1.12.3. (in fact, it behaves identically) fwiw I am using the Webupd8 PPA as well.

**Comment by vwugd97** [comment]
+1 Atom 1.12.3 still has the bug

The only thing that changed for me is that the main window starts showing up:
![atom_crash](https://cloud.githubusercontent.com/assets/15200842/20357166/2e9bceb0-ac27-11e6-870e-a2a8da317b38.png)

$ uname -a
Linux xxxx 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

$ atom --version
Atom    : 1.12.3
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.9
git 2.1.4

**Comment by 50Wliu** [comment]
Please uninstall Atom if you are using the webupd8 version and reinstall Atom from https://atom.io.  The webupd8 distribution is unofficial and is messing with Atom's launch scripts, which is why you're still seeing this.

See https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md for more information.

**Comment by vwugd97** [comment]
@50Wliu 

Wow, I didn't see that coming. Installing the package from https://atom.io indeed fixes the problem.

**Comment by jorgerc85** [comment]
Cool, thanks! Goodbye automatic updates :(

**Comment by dominicbarnes** [comment]
I'll try installing the supported version (and removing the webupd8 version) when I get home tonight.

That's really unfortunate though, getting automatic updates is a pretty big deal to me, as I'm sure it is for most. Is there an official Ubuntu PPA? (or is that even on the roadmap?)

**Comment by dominicbarnes** [comment]
Just a heads-up, upgrading to v1.12.3 appears to have fixed this issue for me. Just wanted to point out that this doesn't appear to have anything to with webupd8's PPA after all. (so I won't lose automatic updates, thankfully)
