### ISSUE TITLE
Blurry inconistent font rendering on Windows

### ISSUE THREAD

**Issue by polydecay** [atom/atom#13244]
**I'm using Atom 1.12.3 on Windows 10, and my font is Consolas at 12px and 1.4 line height.**

### Description
When I comment out lines by inserting `//` at the beginning of a line all lines in that block gets blurry. From what I can tell it's related to italicized fonts, and I was able to temporarily fix the issue by disabling italicized comments.

Using the devtools experimental Layers tool I noticed the block of lines that were blurry had a different size `1601 x 96 (at -1,0)` instead of `1600 x 96 (at 0,0)`. However when using the normal inspector they're all `1600px` wide, I'm not sure what that means but hopefully it's useful.

Screenshot of blurry font rendering on line 7-12:
![text](https://cloud.githubusercontent.com/assets/18099734/20359625/feff1810-ac30-11e6-827e-2ad90659efdc.png)

### Steps to Reproduce
1. Write a few lines of code with JS syntax
2. Insert `//` at the beginning of a line

**Comment by chrisvio** [comment]
Heh. I reported a similar issue almost a year ago -> https://github.com/atom/atom/issues/10185
