### ISSUE TITLE
color code incorrect 

### ISSUE THREAD

**Issue by GioDgo** [atom/atom#13250]
### Prerequisites

* Hi , when i updated to .12.3 version my html and javascript code is color wrong , i can`t diference the code
![captura de pantalla 2016-11-16 a la s 17 03 19](https://cloud.githubusercontent.com/assets/4277848/20370965/d40d28a2-ac1e-11e6-85b9-bea1f1ddb46f.png)
![captura de pantalla 2016-11-16 a la s 17 06 04](https://cloud.githubusercontent.com/assets/4277848/20370977/ea6b08bc-ac1e-11e6-8239-8d5ec67af5ba.png)

**Comment by 50Wliu** [comment]
Please open a new issue and **completely** fill out the provided issue template.  Thanks!
