### ISSUE TITLE
Stopped working on my Macbook Pro

### ISSUE THREAD

**Issue by fman29** [atom/atom#13259]
I'm not sure what's going on but when I restarted my Macbook Pro Atom windows wouldn't open.  An error box popped up saying: The editor has crashed Please report this issue to https://github.com/atom/atom. I know it is up to date because I am very diligent about that sort of thing. I even went as far as downloading Atom again from the Atom website, deleted my current version and tried replacing it with the newly downloaded version. I got the same message. Any help would be GREATLY appreciated as I use ATOM daily! (I really like Atom and I don't want to have to switch to another text editor.)

**Comment by 50Wliu** [comment]
@fman29 Sorry to hear you're having trouble!  Can you try out the following things for me and see if they work?
1) `atom --safe`
2) `atom --clear-window-state` (note: this will irreversibly clear Atom's window state.  If you have any unsaved changes, those will be wiped out.  If you think that's not worth trying, then feel free not to.)

In addition, what is the output of `atom --version`?

Finally, in the future, it would be greatly appreciated if you could follow the default issue template that is provided to you when creating an issue.  It helps us provide faster and more directed feedback :).

**Comment by fman29** [comment]
Unfortunately, I can't get it to open ANY window. I've got the Atom menu bar and nothing else. Every attempt to open any window or search preferences or config files fails.

**Comment by thomasjo** [comment]
@fman29 Please follow the steps laid out by @50Wliu, and answer his questions.

Right now, we do not have enough information to help resolve your problem. Unless the requested information is not provided in a reasonable timeframe, this issue will be closed.

**Comment by aymericbouzy** [comment]
I had the same issue.

1) atom --safe does work once I've closed all windows. I can then open any project. My react package was not parsing jsx files as it usually does.
2)
```
$ atom --version
Atom    : 1.12.3
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

Now that I've opened atom in safe mode once, I cannot reproduce the issue, even when opening without safe mode, everything is fine. Issue is solved for me at least!

**Comment by iMasterAle** [comment]
I have the same problem but atom works only if I use `atom --safe` with atom themes.
```
Atom    : 1.12.4
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by fman29** [comment]
Thanks everyone! Your instructions seem to have worked like a charm! I appreciate your very quick responses and all of your help!!

**Comment by 50Wliu** [comment]
If Atom works in safe mode, try disabling community packages until it works in non-safe mode.

**Comment by shailenderacc** [comment]
Hi All,

I am unable to open Atom editor on my Mac.

Below are the details 

Shailenders-MacBook-Pro:Root shailenderkumar$ atom --version
Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
Shailenders-MacBook-Pro:Root shailenderkumar$ atom --clear-window-state
2017-09-02 20:39:57.749 atom[78436:9788664] *** Assertion failure in +[SQRLDirectoryManager currentApplicationManager], /Users/joshaber/Documents/Development/GitHub/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30
Illegal instruction: 4

Can someone please guide me how to work on Atom in Mac as I am using Atom editor for the very first time.

Regards,
Shailender

**Comment by shailenderacc** [comment]
Hi All,

I am now able to open Atom perfectly on my Mac, seems like the download got corrupted during the download.

Thanks,
Shailender
