### ISSUE TITLE
[FIXED] Atom appears to open past monitor. JRE 8u112 update

### ISSUE THREAD

**Issue by danielmarkavis** [atom/atom#13252]
### Prerequisites
Checked, nothing related.

### Description
I just updated to JRE 8u112, and Atom fails to open, the window looks to opening past my current screens, the atom window is visible as it expands to fill the screen, but carries on beyond the furthest right monitor.

Uninstalled and reinstalled, updated to latest atom.

System:
Windows 7 Pro
AMD FirePro W4300
2x Monitors

### Steps to Reproduce

1. Installed JRE 8u112
2. Open Atom
3. Looked confused

### Expected behavior
Opens to a current monitor

### Actual behavior
Opens beyond furthest right monitor

### Versions
Atom 1.11.2 - version that I was using
Atom 1.12.3 - version I am updated too after problem started.

JRE 8u102 - version that I was using
JRE 8u112 - update

**Comment by 50Wliu** [comment]
As Atom does not depend on Java in any way, shape, or form, this does not have to do with your Java update but rather something else.  I don't even have Java installed at the moment.  Did you by any chance have an external monitor connected sometime before you updated Java?

> Checked, nothing related.

What happened when you ran Atom in safe mode?

**Comment by danielmarkavis** [comment]
Still did the same thing. Moved off screen.

Just started atom, and it was still showing off screen. Hovered over the task bar icon, right clicked on the popup and choose Maximise, and it came back into view. 

So I will close this, and hope this will help someone in the future.
