### ISSUE TITLE
How to update Atom on Ubuntu Linux

### ISSUE THREAD

**Issue by vishu-46** [atom/atom#13261]
How i can update 32-bit Atom in ubuntu-12.04 LTS

**Comment by 50Wliu** [comment]
There is no auto-update mechanism built in for Linux distributions.  You'll have to manually re-download it from https://atom.io.

**Comment by raky291** [comment]
by the easy way :smile: [src](http://www.webupd8.org/2014/05/install-atom-text-editor-in-ubuntu-via-ppa.html)
```
sudo add-apt-repository ppa:webupd8team/atom
sudo apt-get update
sudo apt-get install atom
```

**Comment by 50Wliu** [comment]
That is an unofficial distribution, so if you run into any bugs using it, do not expect support from the Atom team.

**Comment by vishub** [comment]
@50Wliu  why you can not give 32 bit .deb package ?

**Comment by 50Wliu** [comment]
@vishub Travis, which builds our Linux releases, runs on x64 containers.

**Comment by vishub** [comment]
@50Wliu how to install atom.x86_64.rpm package in ubuntu 32bit ?

**Comment by 50Wliu** [comment]
I don't know.  These types of questions are better suited for [Discuss, the Atom forum](https://discuss.atom.io).

**Comment by vishub** [comment]
@50Wliu Thank's
