### ISSUE TITLE
Scrollbars move to the top of the file when splitting panes or closing split panes

### ISSUE THREAD

**Issue by skywind3000** [atom/atom#13265]
### Prerequisites

* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

- When I open a large file and move the cursor to the bottom, and then click View->Panes->Split Right.
I found the scroll bar position of previous pane rewind to the top but the cursor is still on the last line.

### Steps to Reproduce

1. Start Atom using `atom --safe` from `cmd.exe`
2. Open any file and resize the Atom window so you have a vertical scrollbar visible
3. Scroll to the middle of an opened file
4. Run `pane:split-right-and-copy-active-item`
5. Expected: The scrollbars to stay in the same position for both files. Actual: The scrollbars in both files moves to the top of the file
6. Close the right pane
7. Expected: The scrollbar position of the first file to not change. Actual: The scrollbar in the first file is displayed at the top of the file.

![scrollbar](https://cloud.githubusercontent.com/assets/1058982/20443729/5a67cab4-adce-11e6-821b-b1784f161afc.gif)

**Expected behavior:** [What you expected to happen]
scroll bar position should no change

**Actual behavior:** [What actually happened]
I found the scroll bar position of previous pane rewind to the top but the cursor is still on the last line.

### Versions
Atom    : 1.12.0
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

![atom-2](https://cloud.githubusercontent.com/assets/3035071/20433492/c8b1edc8-adde-11e6-9ede-f003873eaaf8.png)

**Comment by skywind3000** [comment]
https://github.com/atom/atom/issues/11484 has been closed
they are supposed to fixed in 1.12.0, but actually it wasn't or maybe new bug comes out

**Comment by lee-dohm** [comment]
@skywind3000 I understand that you are upset with the apparent quality of Atom. However, posting repetitive comments across so many separate Issues is [harassment under our Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md). This is an official warning. If you continue, you will be banned from participation in the Atom and Electron projects.

Additionally, comments like the following:

> I wonder do you have a QA Team ?

are insulting, which is also a violation of the Code of Conduct.

We want to work with you on these things. We closed #11484 because we could no longer reproduce the problem. There are some bugs that only reproduce on certain configurations or in certain instances. No team can find **all** bugs in a software product, some bugs will have to be reported by people outside of our team. If people run into bugs and don't tell us about them, then we don't know about them and can't fix them.

We're going to take a look at this and see if we can reproduce it. Please report any other bugs you find with as much information as you can. Please also do so in a respectful and cooperative manner.

**Comment by skywind3000** [comment]
Apologize for my inappropriate words.
All I want is atom becomes better.

**Comment by Ben3eeE** [comment]
Hey, this is a different bug than the one you referenced. I can reproduce this on `Atom 1.14.0-dev-9c73ae0 Electron 1.4 branch`, Windows 10 anniversary x64.

This is with an 84 line file and `one-dark-ui`. So it doesn't require large files and is not limited to `atom-light-ui`.

1. Start Atom using `atom --safe` from `cmd.exe`
1. Open any file and resize the Atom window so you have a vertical scrollbar visible
1. Scroll to the middle of an opened file
1. Run `pane:split-right-and-copy-active-item`
1. Expected: The scrollbars to stay in the same position for both files. Actual: The scrollbars in both files moves to the top of the file
1. Close the right pane
1. Expected: The scrollbar position of the first file to not change. Actual: The scrollbar in the first file is displayed at the top of the file.

![scrollbar](https://cloud.githubusercontent.com/assets/1058982/20443729/5a67cab4-adce-11e6-821b-b1784f161afc.gif)

**Comment by lee-dohm** [comment]
> Apologize for my inappropriate words.
> All I want is atom becomes better.

We want Atom to become better too. Thanks for helping us find this bug so we can fix it! 👍

**Comment by skywind3000** [comment]
What about the first bug ? Is it possible that it is caused by a float point calculation error ?

**Comment by lee-dohm** [comment]
@skywind3000 I can't reproduce Bug 1 using Atom v1.12.4 on Mac OS X 10.12.1. Additionally, you should report only one bug per Issue. If you can supply more detailed steps to reproduce the problem, please open a new Issue. I'll be editing this bug to only track the pane splitting bug that @Ben3eeE confirmed.

**Comment by skywind3000** [comment]
I can't reproduce it on Mac OS X either, It's only on windows.

**Comment by lee-dohm** [comment]
Please include that information when you open the new Issue.
