### ISSUE TITLE
Atom editor crashes on startup

### ISSUE THREAD

**Issue by LeanderK** [atom/atom#13271]
I am running MacOSX.
After starting i am greeted by: The editor has crashed.
This is the log from the Console-app: https://gist.github.com/LeanderK/767c8e1166bea86255f04dad8bbdda25.
Running in safe-mode works.
```
atom version:
Atom    : 1.12.4
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.2
```
I may be possible that an package caused this.

**Comment by kioshimafx** [comment]
I deleted my ~/.atom directory, and it worked fine (macOS Sierra).

**Comment by LeanderK** [comment]
lol, well it deleted all the packages and preferences. Should have  thought about it before running it.

**Comment by kioshimafx** [comment]
No, it's not deleted all the packages and preferences! 😃

**Comment by LeanderK** [comment]
i just started atom and was greeted with a blank installation.  :anguished:

**Comment by kioshimafx** [comment]
@LeanderK it's ok, check your packages in Preferances 😄

**Comment by aoc** [comment]
I experienced the same problem here on macOS Sierra.
I could narrow down the problem to api-blueprint-preview package. After manually deleting it from `.atom/packages`, I could start Atom and install the package again. Now Atom starts without problems.

**Comment by LeanderK** [comment]
@aoc that could be the culprit, i also installed that package!

**Comment by revelt** [comment]
Guys, as you identified the cause of the problem, would you like to close this issue and open one on `api-blueprint-preview` repo instead?

**Comment by LeanderK** [comment]
@revelt of course, i was on my mobile. Sorry for the delay!

**Comment by aoc** [comment]
@revelt I don't agree this an `api-blueprint-preview` issue. That package works fine with atom 1.12.4 if you install it in a fresh installation (or even if you install it in any of the past 5 releases. I couldn't track down the version I used to originally install it).

I've been using it daily without problems in all the latest atom versions. Why did it break in this minor release?

Even though there might be issues in the package, Atom should handle this more gracefully. No package should crash atom like that.

I'm still investigating this problem, I'll open another issue if I find anything else.

**Comment by revelt** [comment]
@aoc Definitely. Thanks for helping to investigate.

**Comment by chkania** [comment]
With my installation markdown-preview-kramdown was the problematical thing.
Even when I try to install it again it crashed during the installation process
Atom 1.12.5 with Sierra
