### ISSUE TITLE
Ability to *enforce* preferences for all users.

### ISSUE THREAD

**Issue by iainhallam** [atom/atom#13285]
### Description

#13284 is a request to be able to provide a default value for preferences at the machine level rather than user or application level. In some cases, we'd like to enforce settings even if users have them set to a non-default value. Particularly in the case of something like backing up before saving, this is something that should be turned on for all our managed machines, not just defaulted to on.

This request is for a way to mark certain machine-wide preferences as being enforced rather than optional so that Atom would ignore a user's setting of a preference.

### Versions

1.10 and all previous versions on all OSes

**Comment by damieng** [comment]
Given the hackability of Atom any such enforcement would be trivially bypassed.
