### ISSUE TITLE
Ability to set preferences for all users of machine

### ISSUE THREAD

**Issue by iainhallam** [atom/atom#13284]
### Description

It recently came up that a user lost work because of #9166 and I wanted to be able to roll out a preference to our machines that would default saving with back up to true. Apparently there's no way to read a system-wide configuration file in Atom, and it relies entirely on configuration in the user's home directory.

I'd like Atom to be able to have an extra layer of preferences, so that if something is not set by the user, it is read from a per-machine configuration, before using the application's default settings. On Linux this should be a file in /etc, but it could be registry entries on Windows or some other file in the application data area.

### Steps to Reproduce

1. Wish to set a preference across users
2. Not have the ability.

**Expected behavior:** Be able to default a preference for all users

**Actual behavior:** Only per-user configuration is taken into account

### Versions

1.10 and all previous, all OSes.

**Comment by clarcharr** [comment]
I would be very interested in this, at least on Linux.

Preferably, Atom would follow the XDG specification, replacing `~/.atom` with `~/.config/atom` and loading `/etc/xdg/atom` before `~/.config/atom`, if it exists.
