### ISSUE TITLE
Button "/" considered as "."  

### ISSUE THREAD

**Issue by vzhabonos** [atom/atom#13297]
I'm not sure is it bug with Atom, but I have this issue since i changed OS to ArchLinux and installed the Atom. 
So problem is when I push "Ctrl+/" it considers this as "Ctrl-.". I thought if I'll press "Ctrl+." it will be consider this as "Ctrl+/" but no! 
I think it probably something went wrong with my keyboard layout.

Can someone guide me to the right point?

**Comment by Ben3eeE** [comment]
* What is the language of your keyboard?
* Did you change layouts while Atom was running?
* What version of Atom are you using? `atom --version`

**Comment by vzhabonos** [comment]
Languages: ru, us, ua
Nope. I didn't changed layouts
Atom 1.12.5(just updated it)

Sooo... When i updated Atom problem gone by itself.
@Ben3eeE , thanks for your help :) Actually without your comment I doubt that I would had tried to update Atom
