### ISSUE TITLE
building i386 on debian

### ISSUE THREAD

**Issue by deepgray** [atom/atom#13302]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [ ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

while building on Debian 8 i386 platform i get the following error:

root@debian8-i386:~/atom# ./script/build

/root/atom/script/build:13
const yargs = require('yargs')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
root@debian8-i386:~/atom# which node
/usr/bin/node
root@debian8-i386:~/atom# ls -la /usr/bin/node
lrwxrwxrwx 1 root root 15 Nov 22 13:19 /usr/bin/node -> /usr/bin/nodejs
root@debian8-i386:~/atom# ls -al /usr/bin/nodejs
-rwxr-xr-x 1 root root 1265044 Apr 12  2015 /usr/bin/nodejs
root@debian8-i386:~/atom# /usr/bin/nodejs -v
v0.10.29
root@debian8-i386:~/atom# 

I have built it on Ubuntu 16 i386, but when trying to install the Debian package, it says that it's an unknown format.

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

**Comment by 50Wliu** [comment]
As the build instructions state, you must have at least Node v4 installed in order to build Atom.
> Node.js 4.4.x or later (we recommend installing it via nvm)
