### ISSUE TITLE
Open Terminal at Root: cmd inherits Atom environment variables

### ISSUE THREAD

**Issue by marvinroger** [atom/atom#13304]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I've been wondering why, when I open a windows CMD from Atom with the `Open Terminal at Root` feature, my `npm install` only installs dependencies and not devDependencies. It turns out the `NODE_ENV` environment variable is set to `production`, which is, I guess, inherited from the Atom process.

### Steps to Reproduce

1. Right click on your top folder
2. Click Open Terminal at Root
3. Type `echo %NODE_ENV%`

**Expected behavior:** `NODE_ENV` is not defined on my machine, so I should actually see `%NODE_ENV%`

**Actual behavior:** `production` is printed

### Versions

Windows 10 Home x64 (version 1607 build 14393.447)

>Atom    : 1.12.5
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

>apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.1.windows.1
visual studio 2015

**Comment by 50Wliu** [comment]
> Click Open Terminal at Root

Can you clarify this step?  Atom by itself does not contain any "Open Terminal at Root" function.  Are you sure you tested in safe mode?

**Comment by marvinroger** [comment]
I thought I did, maybe I made a typo typing `--safe`...
Anyway, my bad, the problem does not come from Atom but from an extension. Sorry for the noise.

**Comment by 50Wliu** [comment]
No problem!  We all make mistakes sometimes :).  Thanks for getting back to us!
