### ISSUE TITLE
Enhancement: Allow 'Reveal in Treeview' for not selected files

### ISSUE THREAD

**Issue by JoaoGFarias** [atom/atom#13303]
Sometimes, it's useful to check where a file different from the current on view is placed in the treeview.

This enhancement aims to add to the dropdown the 'Reveal in the Treeview' option when the user clicks with the right button.

- Menu in the current selected file:
<img width="357" alt="screen shot 2016-11-22 at 16 14 18" src="https://cloud.githubusercontent.com/assets/1585655/20538257/29557b3e-b0cf-11e6-9a1a-d3bb4a51c995.png">

- Menu in a not selected file:
<img width="347" alt="screen shot 2016-11-22 at 16 14 25" src="https://cloud.githubusercontent.com/assets/1585655/20538258/2ac89a5a-b0cf-11e6-88b1-037468c63914.png">

**Comment by 50Wliu** [comment]
@JoaoGFarias Can you please reopen this on the [tree-view](https://github.com/atom/tree-view) repository?  Thanks!
