### ISSUE TITLE
Autocomplete behaviour

### ISSUE THREAD

**Issue by Aggroblut** [atom/atom#13316]
### Description

![2016-11-23](https://cloud.githubusercontent.com/assets/5066584/20571418/a97e3b4c-b1a7-11e6-999f-b109e09a412d.GIF)

May my way to use autocomplete is retarded. I think not. 

### Versions

Ubuntu 16.04.1 and Windows 10 with the latest Version so 1.12.5

**Comment by 50Wliu** [comment]
What you are using is called "snippets".  The intended use for those is to directly invoke the snippet.
