### ISSUE TITLE
editor:split-selections-into-lines incorrect autocomplete

### ISSUE THREAD

**Issue by cag** [atom/atom#13313]
![imageedit_2_5318542759](https://cloud.githubusercontent.com/assets/298447/20568571/96603d02-b162-11e6-9b46-3f83ac695eae.png)

1. Go to edit your keymaps.cson
2. Start typing `'editor:split` as the value of a mapping

The autocomplete will give you the wrong value.

See also: https://github.com/atom/atom/issues/5765

**Comment by 50Wliu** [comment]
I can't reproduce this.  Atom's autocompletion takes into account text from other open files, so make sure you don't have `split-selection-into-lines` already open somewhere else.
