### ISSUE TITLE
symbol quick search

### ISSUE THREAD

**Issue by SirCameron** [atom/atom#13311]
### Symbol quick search scroll

Currently when using the symbol quick search (CMD + r on a mac) and the symbol is found, the window scrolls to some arbitrary position where the found symbol is near the bottom.
This is unhelpful when you need to glance through code to and are jumping from symbol/function to symbol/function. 
Improvement suggestion: scroll the window so the position of the found symbol is at the top. This allows the developer to quickly glance at the code if needed.

### Steps to Reproduce

1. open up some code
2. use CMD + r and enter some text to find a symbol
3. look at where the window has positioned the found symbol

**Expected behavior:** The symbol to be positioned at the top of the view pane, so the function below is visible.

**Actual behavior:** symbol is visible at the bottom of the pane

### Versions
1.12.2

## OS and version
Mac OS 10.12

**Comment by 50Wliu** [comment]
This belongs on the [symbols-view](https://github.com/atom/symbols-view) package - please open a new issue there instead (if one doesn't already exist).  Thanks!
