### ISSUE TITLE
Atom won't launch in Fedora 25 Workstation

### ISSUE THREAD

**Issue by uzantonomon** [atom/atom#13334]
Atom won't launch on a fresh Fedora 25 Workstation install. Launching it from a terminal shows the following error:

/usr/share/atom/atom: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

**Reproduction Steps:**

1. Click on Atom icon.

**Expected behavior:**

Atom launches.

**Observed behavior:**

Atom don't launch and don't throw any error (except when launching from a terminal)

**Atom version:** 1.12.5
**OS and version:** Fedora 25 Workstation

* Problem can be reproduced in safe mode: Yes
* Problem started happening recently, didn't happen in an older version of Atom: Don't know
* Problem can be reliably reproduced, doesn't happen randomly: Yes, every time on a fresh Fedora 25 install
* Problem happens with all files and projects, not only some files or projects: N/A

**Installing *libXScrnSaver* solves the issue. (libXScrnSaver-1.2.2-10.fc24.x86_64)**

**Comment by thomasjo** [comment]
This has been fixed in https://github.com/atom/atom/pull/13289. I'm not sure if we're going to release a patch to v1.12, or if you'll have to wait for v1.13.

Thanks for the report!
