### ISSUE TITLE
Unable to insert some diacritic characters due to shortcuts (just hear me out)

### ISSUE THREAD

**Issue by KamodaP** [atom/atom#13347]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

I'm using Polish (programmers) keyboard, and there we use right alt (or alt/gr), which has different key code then left alt (regular alt) to insert diacritic characters like ąężźćółńś. Unfortunately some shortcuts are defined with alt+ combinations, like alt+o (default) this doesn't cause problems in most applications, since they can differentiate left alt from right alt. I know I can just change shortcut, but it would be nice to be able to use alt+ shortcuts AND write special characters.

### Steps to Reproduce

1. Just press alt+o which should produce ó but produces some popup

**Expected behavior:** [What you expected to happen]

Insert ó

**Actual behavior:** [What actually happened]

opens popup

### Versions

Atom    : 1.12.5
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
OS: Windows 10 newest

Oh, I noticed that left alt + o does nothing :(
Maybe swap those as default?

**Comment by Ben3eeE** [comment]
This is the intended behavior. On Windows <kbd>AltGr</kbd> is the same thing as <kbd>Ctrl-Alt</kbd>. We have started to remove <kbd>AltGr</kbd> keybindings from core starting with Atom 1.12 and continued in Atom 1.13.

If you want to be able to write this character in Atom 1.12 using <kbd>AltGr-o</kbd> you will have to change the keybind yourself in your `keymap.cson` (`File menu -> Keymap`) and enter the following:

```json
'body':
  'ctrl-alt-o': 'unset!'
  'ctrl-shift-o': 'application:open-folder'
```

Sorry for the inconvenience.

**Comment by szyszak** [comment]
Your solution works for alt+o, but unsetting alt+z doesn't work and triggers Atom's built in Git API no matter what I try.
