### ISSUE TITLE
APM cmd

### ISSUE THREAD

**Issue by Akumetsu-Dev** [atom/atom#13352]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

When try use "Apm" on the cmd appear the next line: 
"INFO: Could not find any file for given patterns. The system can not find the specified archive.", and i dont know if for this warning or error i cant use some package like beautify in C#, where throw me "error permision".

*note: i re-install windows, and only install atom.

### Steps to Reproduce

1. CMD
2. Input "Apm"
3. throw error

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions
apm  1.12.9
npm  3.10.5
node 4.4.5
python
git
visual studio

**Comment by damieng** [comment]
This is just an informational message that should have no affect on using atom or apm.

The message has been removed in Atom 1.13 which is currently in beta.

**Comment by Akumetsu-Dev** [comment]
ok, thank you.
