### ISSUE TITLE
Text highlight problem on php files whit tag <script>

### ISSUE THREAD

**Issue by iJackBauer** [atom/atom#13356]
I have highlight problem when i put php code inside tag <script>.

This is how it looks:

![atom_bug_1](https://cloud.githubusercontent.com/assets/9990272/20704539/efe3350c-b61f-11e6-94a5-27787691f27a.png)

And this is how it should look (I had to add the quotes around <php>)

![atom_bug_2](https://cloud.githubusercontent.com/assets/9990272/20704632/4e552348-b620-11e6-81f9-92103884b1db.png)

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.13.0.
