### ISSUE TITLE
unresolvable dependency libXScrnSaver on openSUSE

### ISSUE THREAD

**Issue by cobexer** [atom/atom#13354]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [ ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description
On openSUSE Atom 1.12.6 can't be installed because the package libXScrnSaver is not available.
according to [build.opensuse.org project X11:XOrg package libXScrnSave for example for openSUSE_Leap_42.2](https://build.opensuse.org/package/binaries/X11:XOrg/libXScrnSaver?repository=openSUSE_Leap_42.2) the binary package is called **libXss1**, perhaps more compatible would be **libXss.so.1()(64bit)** as a requirement? Introduced by Pull #13289

### Steps to Reproduce

1. try to install Atom 1.12.6 on any version of openSUSE

**Expected behavior:** atom installs

**Actual behavior:**
```
LC_ALL=C zypper in atom.x86_64.rpm 
Problem: nothing provides libXScrnSaver needed by atom-1.12.6-0.1.x86_64
 Solution 1: do not install atom-1.12.6-0.1.x86_64
```

### Versions
```
# cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20161125"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="20161125"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20161125"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"

```

**Comment by Adobe-Android** [comment]
Do we really even need this dependency? Couldn't we at least make it optional? Make it a suggested package for those who use screen saver functionality.

**Comment by 50Wliu** [comment]
From what I know, `libXScrnSaver` is now a requirement in newer Electron versions (such as the one we use).

**Comment by Fisiu** [comment]
I think rpm should handle library dependencies, even when package is not mentioned by name.

**Comment by Adobe-Android** [comment]
Typing this: sudo zypper in -y atom.x86_64.rpm
Gives the above error.
Typing rpm -i *.rpm
Output:
error: Failed dependencies:
	libXScrnSaver is needed by atom-beta-1.13.0.beta6-0.1.x86_64

**Comment by Adobe-Android** [comment]
Does anyone know what version of electron Atom uses? I'd like to point out that I got VS Code working after installing libXss1 32-bit packages.

**Comment by 50Wliu** [comment]
1.3.9.

**Comment by Adobe-Android** [comment]
That's weird..still interesting. Seems to not be an upstream issue then. Guess it has to be solved by the editor more directly.

**Comment by dominuskernel** [comment]
If I have removed the dependence libXScrnSaver #13289 and it can do rpmbuild fine. I think the dependence for openSuse is libXss1 instead of libXScrnSaver.

**Comment by Adobe-Android** [comment]
@dominuskernel Ya, it is.

**Comment by kmare** [comment]
Installing the latest 1.12.7 rpm build, is giving me 
```
error: Failed dependencies:
	libXss.so.1 is needed by atom-1.12.7-0.1.x86_64
```
on Fedora 25. Of course libXScrnSaver is installed and libXss.so.1 exists.

**Comment by majidazimi** [comment]
On fedora 25 it tries to download 32bit version of libXScrnSaver while there is 64 bit version already available in the repository. Installing 32 bit version libXScrnSaver causes many other 32 bit dependencies like glibc. Is this necessary?

**Comment by Fisiu** [comment]
openSUSE Leap 42.2: Installation of atom 1.12.7 pulls extra 32 bit libs now:
`libX11-6-32bit libXau6-32bit libxcb1-32bit libXext6-32bit libXss1-32bit`

What about using `%{_libdir}/libXss.so.1` in Require? I'm not sure macro can be used in `.spec` preamble.

**Comment by ProgramFan** [comment]
On fedora 24, it also tries to download 32bit versions. This is too bad. Any solutions to this?

**Comment by 50Wliu** [comment]
Can someone open a new issue for the 32-bit problem?

**Comment by 50Wliu** [comment]
Actually, never mind.  It looks like this has already been fixed in the next hotfix release.

**Comment by ndc33** [comment]
have just tried today on opensuse - is this ever going to get fixed?

**Comment by Fisiu** [comment]
atom-1.13.0 and issue still occurs.

**Comment by ginus** [comment]
atom 1.13.0
openSuse Tumbleweed
sudo rpm -U --nodeps atom.x86_64.rpm
it works fine!

**Comment by ndc33** [comment]
thanks for the tip but --nodeps is not best practice and will most likely break in the long term.
