### ISSUE TITLE
Regressions in atom 1.12.6 - atom opened in wrong workspace + move several file

### ISSUE THREAD

**Issue by pelallemant** [atom/atom#13364]
### Description

Problem reproduced in safe mode.

I am using ubuntu 16.04 . I updated the system an now i'm experiencing 2 problems:

- If i open another atom in another workspace by typing 'atom .' in the shell in the desired folder, the atom window is opened in another workspace . I usually have 7 atom opened with a shell, in 7 distincts workspaces.
- When we select several files, and try to move them into a directory, the first file is selected so we have to move them each one

**Expected behavior:** 

- The window has to be opened as it was before: in the current workspace
- The multiple files move should work

### Versions

> Atom    : 1.12.6
> Electron: 1.3.9
> Chrome  : 52.0.2743.82
> Node    : 6.5.0

**Comment by Ben3eeE** [comment]
Multiple move of files from the `tree-view` has never worked. From where do you experience this behavior? Please include full steps to reproduce the problems.
