### ISSUE TITLE
Blurry font after tab switch

### ISSUE THREAD

**Issue by muchweb** [atom/atom#13361]
This started to happen after an upgrade. 

1. Start an editor and see good, crispy font:
![1](https://cloud.githubusercontent.com/assets/7157049/20756599/585ac33e-b724-11e6-8c30-ae357222074d.png)
2. Switch the tab, and see bad blurry font:
![2](https://cloud.githubusercontent.com/assets/7157049/20756620/64fac346-b724-11e6-9147-92b61c6febaa.png)

'Reload Window' helps to restore crispy font until another tab switch.

Atom 1.12.6 on GNU+Linux. Font: 'Proggy Clean' from [fonts](https://atom.io/packages/fonts) package, 'webkit font smoothing' is turned off.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the issue template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by muchweb** [comment]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

Blurry font after tab switch

### Steps to Reproduce

1. Start an editor and see good, crispy font:
![1](https://cloud.githubusercontent.com/assets/7157049/20756599/585ac33e-b724-11e6-8c30-ae357222074d.png)
2. Switch the tab, and see bad blurry font:
![2](https://cloud.githubusercontent.com/assets/7157049/20756620/64fac346-b724-11e6-9147-92b61c6febaa.png)

'Reload Window' helps to restore crispy font until another tab switch.

**Expected behavior:** Font does not go blurry after tab switch

**Actual behavior:** Font does go blurry after tab switch

### Versions

Atom 1.12.6 on GNU+Linux. Font: 'Proggy Clean' from [fonts](https://atom.io/packages/fonts) package, 'webkit font smoothing' is turned off.

**Comment by Ben3eeE** [comment]
What is the output of `atom --version` and `apm --version`?

**Comment by muchweb** [comment]
@Ben3eeE,
```
$ atom --version
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.1
```

**Comment by muchweb** [comment]
I  could not find any subpixel element positions that could affect the text

**Comment by muchweb** [comment]
Last version of Atom it works OK on is `1.11.2`. All later versions have this issue.

**Comment by muchweb** [comment]
Bug is still present in v1.15.0 ☹

**Comment by muchweb** [comment]
File opened for the first time (good crisp font):

![good](https://cloud.githubusercontent.com/assets/7157049/23901799/dbf49e3e-08cf-11e7-982a-84262d46d316.png)

Tab revisited (bad greenish font):

![bad](https://cloud.githubusercontent.com/assets/7157049/23901809/e905c92c-08cf-11e7-84d4-4c58ae1aab39.png)

**Comment by muchweb** [comment]
It seems to work correctly now. No idea what fixed it.

Atom version 1.18.0.
