### ISSUE TITLE
Possible internal python unicode issue 

### ISSUE THREAD

**Issue by MrYann** [atom/atom#13363]
### Prerequisites

* [no - but see below] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [yes ] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [yes ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [yes] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [not sure] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [yes] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Running python scripts with unicode characters through "script" package or "build + build-python" packages results in UnicodeEncodeError, whereas running the same python script in the terminal has no error.

So, the problem can obviously no be reproduced in safe mode. However, since two different packages fail in exactly the same way, I would tend to think that this is somehow inherent to atom itself: the unicode environment for python is somehow perturbed when launched through atom.

### Steps to Reproduce

1 Install "script" package, or "build" and "build-python" packages
2 Create new file and paste the following line: 
with open("test.txt", "w") as file: file.write("é")
3 execute the script (cmd-i with "script" package, or cmd-alt-b with "build" package (on Mac -- on linux it seems to be cmd-alt-b in both cases)

**Expected behavior:** [What you expected to happen]

No error + creation of file "test.txt" containing the single letter é

**Actual behavior:** [What actually happened]

UnicodeEncodeError + empty file "test.txt"

EDIT : the same problem happens with SublimeText. So there is something really strange happening
 when python scripts are executed from a program instead of in a terminal. But I have no clue auto what.

### Versions

Atom 1.12.6
MacOS Sierra
Python 3.5 (anaconda distribution)

**Comment by lee-dohm** [comment]
Thank you for contributing!

It appears that this is being caused by the various packages, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of one of the packages that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by MrYann** [comment]
In fact, it does not come from the packages at all.
It comes from a wide-reaching problem : 
On macOS, when Atom is started from the dock or mission control, it does not correctly get then locale settings. When started from the terminal, everything works just fine.
As it is, starting atom from dock or mission control is a real problem for many third party plugins, as they will not receive a correct system state.

**Comment by lee-dohm** [comment]
We've actually done a large amount of work to attempt to detect and import your shell environment when you launch Atom from somewhere other than the terminal. (See https://github.com/atom/atom/pull/12562 among others.) If you're using one of the standard shells, it should just work. If that isn't working, please open a new issue with steps to reproduce the problem in Safe Mode.

**Comment by MrYann** [comment]
The thing is that in safe mode, I have no idea whether the locale has been imported or not; since the main effect is that the extensions developed to run code do it in a wrong environment.

**Comment by lee-dohm** [comment]
@MrYann You can check the environment by using the Atom Developer Tools console. For example:

<img width="750" alt="screen shot 2016-12-30 at 9 26 40 pm" src="https://cloud.githubusercontent.com/assets/1038121/21576011/ad37b7da-ced6-11e6-818a-ed895e33ffbb.png">

`PGDATA` is an environment variable set by my shell environment that is imported into Atom.

**Comment by MrYann** [comment]
I guess the problem comes from elsewhere : I checked process.env.PGDATA and I get "undefined", whether I start atom from the console (where python finds the correct locale) or from the dock (where python does not find the correct locale)
