### ISSUE TITLE
project find results not allowing display of more than one match

### ISSUE THREAD

**Issue by TheNotary** [atom/atom#13369]
### Description

When using the `project find results` UI (via ctrl+shift+f for me), when searching for things that occur in multiple files, all attempts to open the next occurrence the tab for the prior occurrence.  

### Steps to Reproduce

1.  Use ctrl + shift + f to search for something string you know to exist in multiple places within the project
2. click on the first occurrence
3. go back to the project find results tab and click another occurrence in a separate file

**Expected behavior:** I expect to see three tabs, a tab housing `project find results`, a tab containing the file of the first match to my search, and a third tab containing the second match to my search.

**Actual behavior:**  I only see two tabs, a tab housing `project find results`, and a tab containing the second match to my search.  

### Versions
```
$ atom --version
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by Ben3eeE** [comment]
I believe you are describing pending pane items. You have to double click the results to open it and keep the tab. You can read more about it in the [Blog Post](http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html).

**Comment by TheNotary** [comment]
Yes, that seems to be the feature causing the issue, thanks.  I'm not able to double click any of the results in the find results pane though, a 'pending tab' is immediately switched to.  Maybe this should remain open if someone hasn't listed this as a bug yet?

**Comment by Ben3eeE** [comment]
I believe this is filed in https://github.com/atom/find-and-replace/issues/680
