### ISSUE TITLE
Toggle line comment prints "undefined" when language unknown

### ISSUE THREAD

**Issue by tjgerot** [atom/atom#13370]
### Prerequisites

* [X] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [X] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [X] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [X] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [X] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

__Proposed Solution:__ #847 

In a new file (untitled and unsaved) or in a file with an unrecognized file extensions, pressing the <kbd>Ctrl</kbd>+<kbd>/</kbd> shortcut to toggle the line comments (comment the line out) it prints out in the editor `undefined`. I am very confident this arises from the editor returning `undefined` because it cannot determine a comment identifier for an unknown language.

### Steps to Reproduce

1. Open Atom (with or without safe mode)
2. Press <kbd>Ctrl</kbd>+<kbd>N</kbd> to open a new file
3. Press <kbd>Ctrl</kbd>+<kbd>/</kbd> to toggle line comment

**Expected behavior:** [What you expected to happen]

I expected Atom to either ignore the command, or to issue a warning.

**Actual behavior:** [What actually happened]

The editor instead printed `undefined`

#### Application
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

#### Community Packages
* atom-clock
* autocomplete-python
* file-icons
* merge-conflicts
* wakatime

#### System Information

**OS:** Microsoft Windows 10 Home
**OS Version:** 10.0.14393 Build 14393
**Device:** Dell Inspiron 7559 x64 PC

**Comment by Ben3eeE** [comment]
Already fixed by https://github.com/atom/atom/pull/13098

**Comment by tjgerot** [comment]
Thanks for the quick response! I assume these changes won't be part of Atom until a new version is published?

**Comment by 50Wliu** [comment]
It's already in the 1.13 betas.
