### ISSUE TITLE
Proper usage of script/build for a user-level install?

### ISSUE THREAD

**Issue by CodeMan99** [atom/atom#13389]
Building from source was not a problem for me up to (and including) **v1.10.2**.

Since then I have been met with multiple problems and errors while trying to build. Today I attempted to build **v1.12.6** and received an error identical to #12549.

Reading through the documentation it seems the workflow is to install at the system level. This doesn't work for me as I always install to "$HOME/.local" so that I replicate my build on servers where I don't have admin (root) access.

Previously I would do the following.

1. `./script/build`
2. `./script/test`
3. `./script/grunt install --install-dir "$HOME/.local"`

Every version since v1.10.2 (v1.11.* and v1.12.*) have failed to build on my system (step 1). I am unsure how to continue since the documentation only includes directions for a system-level install.

**Comment by CodeMan99** [comment]
System info:

* OS: Ubuntu 15.10 (64 bit, Virtual Box VM)
* node: v6.9.1
* npm: v3.10.9
* gcc: v5.2.1

**Comment by Ben3eeE** [comment]
https://github.com/atom/atom/issues/13240?

**Comment by CodeMan99** [comment]
@Ben3eeE Related, but not the whole issue.

Just remembered about the **script/clean** script. Why is this not documented in "docs/build-inscructions/linux.md"?

**Comment by nathansobo** [comment]
Open a PR?

**Comment by CodeMan99** [comment]
Closing this issue because documenting `script/clean` and issue #13240 is what needs to be done.
