### ISSUE TITLE
Atom does not respect UTF-16 LE w/ BOM file

### ISSUE THREAD

**Issue by cheesecracker** [atom/atom#13399]
### Prerequisites

* The problem can be reproduced in safe mode
* Running Atom 1.12.6, the latest version

### Description

When I open a UTF-16 LE with BOM file in Atom, Atom thinks it is UTF8 file and additional lines are added.  There are also other problem linked to the misinterpretation UTF16 vs UTF8 by Atom.

I've seen some similar discussions on this, but they are talking about general case UTF8/16/32.  So I think a specific bug issue might be easier to manage.

### Steps to Reproduce

1. Open a UTF-16 LE with BOM file in Atom.  Such file can be generated with the following command in elevated DOS window:
secedit /export /cfg C:\temp\new.cfg

2. Observe the bottom right corner in Atom and it's written UTF-8

**Expected behavior:** Since BOM is inside the file, Atom should recognize it as UTF-16 LE

**Actual behavior:** Wrongly recognize the file as UTF-8

### Versions
1.12.6

**Comment by cheesecracker** [comment]
Sample file:
[utf-16-le-with-bom.txt](https://github.com/atom/atom/files/634520/utf-16-le-with-bom.txt)

Screen shot of Atom showing the error:
![atom-error](https://cloud.githubusercontent.com/assets/5957892/20935407/dc1c00ac-bbde-11e6-8773-3cc8d31e79e8.png)

**Comment by 50Wliu** [comment]
Atom does not auto-detect the encoding when a file is opened - you have to select it manually. See https://github.com/atom/encoding-selector/issues/24.

**Comment by petrasteri** [comment]
I give up on Atom.
Downloaded Visual Studio Code which works perfectly.
Bye Atom.
