### ISSUE TITLE
editor doesn't update file paths after renaming folder in Tree View.

### ISSUE THREAD

**Issue by hex13** [atom/atom#13402]
### Prerequisites
Version 1.12.16
### Description

editor doesn't update file paths after renaming folder in Tree View.

If I have such structure:
```
foo/
     index.js
```
and I rename `foo` folder to `bar` in Tree View, file in editor still has `foo/index.js` path.

Sometimes this makes confusion, because I have later two copies of files (changed `bar/index.js` and `foo/index.js` which is only in memory, not on disk, because it was moved). 

So, here I change:
![image](https://cloud.githubusercontent.com/assets/3883359/20952885/d5af4570-bc2f-11e6-89f7-ffe0842c970c.png)

And there is still old directory on the right side:
![image](https://cloud.githubusercontent.com/assets/3883359/20952927/2d1679b4-bc30-11e6-9152-d872ab1d5f94.png)
Notice that on the right is `gui/AppTopBar` even if it was renamed to `view/AppTopBar`
this is confusing, because this file is no longer stored on disk, so additionaly when I click [x] there is a message `AppTopBar.js' has changes, do you want to save them?`

**Comment by lee-dohm** [comment]
Thanks for contributing!

Since this is a bug on the [tabs package](https://github.com/atom/tabs), I've reopened the applicable issue there and referenced this one.

Thanks again for reporting this :grinning:
