### ISSUE TITLE
Check now button downloads updates instead of just checking for them

### ISSUE THREAD

**Issue by trych** [atom/atom#13405]
The `Check now` button in the `About` window starts to download an available update right away instead of just checking for it and letting the user know if an update is available or not.

While I often like to check if an update is available, I do not always want to download it right away (maybe it's just a minor version, maybe I'm on a slow/unreliable network).

So I think the `Check now` button should do what it claims to do: check if an update is available and if ask the user if he wants to download it or not. This is how it works in most other software packages.

**Comment by lee-dohm** [comment]
Thanks for reaching out!

Atom already has this feature. You can uncheck the "Automatically download updates" box and Check Now will only check for updates and not download any available update.

<img width="666" alt="screen_shot_2016-12-23_at_12_32_02_pm" src="https://cloud.githubusercontent.com/assets/1038121/21461997/ff045d0a-c90b-11e6-8e45-efbb6b840015.png">

Thanks again!

**Comment by trych** [comment]
@lee-dohm Well, this is _not_ how it works on my system, unfortunately. I have the "Automatically download updates" button unchecked (and always had) and it still downloads updates whenever I press the "Check now" button.

Could you please re-open the issue, as this seems to be a bug then? Thanks.

**Comment by lee-dohm** [comment]
@trych Please open a new issue on https://github.com/atom/about (since that is where the check and update code resides), @mention me on it and we'll take a look.
