### ISSUE TITLE
Locking up when... interacting with XTerm/pty.js?

### ISSUE THREAD

**Issue by ioquatix** [atom/atom#13423]
### Description

Atom locks up when resizing the panel.. or interacting with XTerm. Unsure how to debug as it's not obvious what's locked up.

### Steps to Reproduce

1. Install script-runner package
2. Go to ~/.atom/package/script-runner/examples
3. Execute `htop.sh` example.
4. In the panel that pops up, interact with htop rapidly, e.g. clicking on rows with the mouse, pressing up/down on the keyboard and resizing then panel rapidly.

Eventually Atom will completely lock up with no obvious error.

### Versions

% atom --version
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

% uname -a
Linux koyoko.local 4.8.12-3-ARCH #1 SMP PREEMPT Thu Dec 8 16:10:23 CET 2016 x86_64 GNU/Linux

**Comment by ioquatix** [comment]
Here is a video demo the problem https://drive.google.com/open?id=0B4svTYmRKR87UXcxNkp1NFZ1Y00

It is typical, I can reproduce every time. I'm not sure how to debug. Debugger seems unresponsive. Eventually I get a segfault in the terminal that started Atom.

**Comment by ioquatix** [comment]
I tried updating electron but same issue:

% atom --version
Atom    : 1.12.7
Electron: 1.4.12
Chrome  : 53.0.2785.143
Node    : 6.5.0

**Comment by 50Wliu** [comment]
Updating Electron is more likely to make things worse than to fix the issue...

Since this seems to be an issue with script-runner, please report it there instead.  Thanks.

**Comment by ioquatix** [comment]
@50Wliu, I'm the author of script-runner.

**Comment by 50Wliu** [comment]
Ok.  This seems to be an issue with script-runner, as Atom does not provide any built-in way to interact with a terminal.  So I'm not sure why you're creating an issue on atom/atom.

**Comment by ioquatix** [comment]
Because atom is segfaulting, and locking up during what seems to be normal operation. I don't know where the bug is, but if the debugger is locking up that's fairly bad right?

**Comment by ioquatix** [comment]
> Updating Electron is more likely to make things worse than to fix the issue...

Why is this?

**Comment by ioquatix** [comment]
One more question. Let's say my code did go into an infinite loop for some reason. Is it possible to debug this? Like, normally, you'd hit pause and you'd be stopped in the loop. When I press pause in the atom debugger, it just freezes.

**Comment by 50Wliu** [comment]
> Why is this?

The amount of issues we get due to mismatched Electron versions is actually a bit depressing.  Every change in Electron has the potential to break something in Atom, and more often than not, multiple things break.  That's the main reason why we're so conservative with upgrading Electron.

Is there possibly another terminal package you could install to test out this issue?  If that one also segfaults, then I'd consider re-opening this issue.

No, I don't really know how to debug that.
