### ISSUE TITLE
Incorrect ligature rendering

### ISSUE THREAD

**Issue by ElectricCoffee** [atom/atom#13424]
Atom seems to have trouble rendering some ligatures. Apparently it's to do with the way the syntax highlighter handles things.

Here's an example of what it looks like in Atom:
<img width="387" alt="screen shot 2016-12-11 at 11 45 37" src="https://cloud.githubusercontent.com/assets/1515791/21083200/9d6e5600-bfeb-11e6-92cb-7e665c68cbf8.png">

And here's what it looks like in the terminal with the same font enabled:
<img width="318" alt="screen shot 2016-12-11 at 11 46 06" src="https://cloud.githubusercontent.com/assets/1515791/21083202/aafefe5a-bfeb-11e6-8381-62177580ad4c.png">

This problem seems to affect things that involve the `>` character, such as `=>`, `->`, `|>`, and `$>`; which all render incorrectly most of the time.

The font I'm using to test this, is [_Fira Code_](https://github.com/tonsky/FiraCode).

**Comment by 50Wliu** [comment]
Please report this to the relevant language package that's highlighting the code.

**Comment by ElectricCoffee** [comment]
Oh, I thought it was a general thing...
It appears in C++, Go, and Rust, hardly specific to any particular language

**Comment by 50Wliu** [comment]
All those languages are tokenizing the operators incorrectly then 😉.
