### ISSUE TITLE
Linux 32bit Build

### ISSUE THREAD

**Issue by progkix** [atom/atom#13420]
Attempting to build Linux 32bit from source and it's downloading the 64bit of Electron.

Using the following:

Node:	v6.9.1
Npm:	v3.10.9

Here's the line from the build output:

Downloading electron-v1.3.13-linux-x64.zip

**Comment by 50Wliu** [comment]
Make sure you're trying to build Atom 1.13 and up.  Atom 1.11 and 1.12 had a bug in the build scripts where it would force x64 installation.
