### ISSUE TITLE
Search in Directory -> ENOENT: no such file or directory

### ISSUE THREAD

**Issue by bsh314** [atom/atom#13449]
Hello Atom/Github team & other humans!

Currently i'm having the next issue:
- When I try to search any value in directory, ENOENT error produces execution stop. 
- When I search value without specifing directory, it makes search in all folders correctly.

Here is the error trace:
`task.coffee:86 ENOENT: no such file or directory, lstat 'my/working/dir/�W@@�@8' Error: ENOENT: no such file or directory, lstat 'my/working/dir/�W@@�@8'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at PathScanner.module.exports.PathScanner.stat (/usr/share/atom/resources/app.asar/node_modules/scandal/lib/path-scanner.js:87:17)
    at PathScanner.module.exports.PathScanner.processFile (/usr/share/atom/resources/app.asar/node_modules/scandal/lib/path-scanner.js:74:19)
    at /usr/share/atom/resources/app.asar/node_modules/scandal/lib/path-scanner.js:51:19
    at FSReqWrap.oncomplete (fs.js:123:15)`

Seems like encoding error, coz Atom throws this to:
`spell-check:es-es Can't load es_ES: Cannot find dictionary for es_ES.`

Currently I'm working on ElementaryOs 0.4 Loki (Ubuntu 16.04) & I've installed Atom with ".deb" package. Any suggestion? 

@50Wliu sorry, here you have it:
atom --version:
`Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
`
atom --save throws the same error.

Thanks for help!

**Comment by 50Wliu** [comment]
What is the output of `atom --version`?  Is this reproducible in safe mode (`atom --safe`)?  Does this happen with one specific project or all folders?
In the future, please fill out the entirety of the provided issue template or your issue will be closed.

**Comment by matthew-dean** [comment]
I have the same issue. Atom version is 1.12.7. ENOENT errors should probably be swallowed if returned on search.

<img width="273" alt="screen shot 2016-12-14 at 11 55 41 am" src="https://cloud.githubusercontent.com/assets/414752/21199340/ffa7aa20-c1f7-11e6-8e18-06e691eb13f4.png">

**Comment by lee-dohm** [comment]
Thanks for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13449#issuecomment-267100171. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
