### ISSUE TITLE
Mark event handlers as passive where possible

### ISSUE THREAD

**Issue by Ryan1729** [atom/atom#13443]
Event listeners that don't call preventDefault can be [marked as passive to improve performance](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md).
So, unless there is a good reason to call `event.preventDefault`, event listeners should be marked passive, particularly in performance critical sections of the code, such as scrolling.

**Steps which explain the enhancement**

1. Current calls to `event.preventDefault` in performance critical code should be evaluated to see if they are necessary
2. If they are not necessary, they should be removed
3. the event listener should be marked as passive by passing an object with a property of passive set to true, i.e. `{passive: true}`, as the third parameter to `addEventListener`

**Current and suggested behavior**

Currently [searching for "passive" in the atom repo](https://github.com/atom/atom/search?utf8=%E2%9C%93&q=passive) doesn't show any event listeners marked as passive, and [searching issues for passive](https://github.com/atom/atom/issues?utf8=%E2%9C%93&q=passive) doesn't show this being suggested before.

I've been using this code in my init.js file for a little while with no obvious ill effects.

```js
(function () {
    //remove event.preventDefault() calls in TextEditorConponent's onMouseWheel listener
    atom.workspace.observeTextEditors(function (editor) {
        var component = editor.editorElement.component

        component.domNode.removeEventListener('mousewheel', component.onMouseWheel)
        
        component.domNode.addEventListener('mousewheel', (function(_this) {
            return function(event) {
                var previousScrollLeft, previousScrollTop, updatedScrollLeft, updatedScrollTop, wheelDeltaX, wheelDeltaY;
                wheelDeltaX = event.wheelDeltaX, wheelDeltaY = event.wheelDeltaY;
                if (Math.abs(wheelDeltaX) > Math.abs(wheelDeltaY)) {
                    previousScrollLeft = _this.presenter.getScrollLeft();
                    updatedScrollLeft = previousScrollLeft - Math.round(wheelDeltaX * _this.editor.getScrollSensitivity() / 100);

                    return _this.presenter.setScrollLeft(updatedScrollLeft);
                } else {
                    _this.presenter.setMouseWheelScreenRow(_this.screenRowForNode(event.target));
                    previousScrollTop = _this.presenter.getScrollTop();
                    updatedScrollTop = previousScrollTop - Math.round(wheelDeltaY * _this.editor.getScrollSensitivity() / 100);

                    return _this.presenter.setScrollTop(updatedScrollTop);
                }
            };
        })(component), {passive: true})
    })

}).call(this); 
```

It removes the `mousewheel` listener from the `TextEditorComponent` and adds another version which is almost the same except the conditional calls to `event.preventDefault` have been taken out, (and it has been converted from coffeescript to javascript), and marks it as passive. Since the calls to `event.preventDefault` don't seem to be doing anything important (at least on my system?) I think they should be removed and the event listener should be marked as passive.

**Why would the enhancement be useful to most users**

Giving the runtime more information with which to optimize could have performance improvements in many areas of the codebase. Focusing on scrolling performance alone, here are some previously opened issues related to scrolling: #10188 #10987 #13407

It's also easy to find people complaining about atom's scrolling speed elsewhere.

**Screenshots and GIFs**

One day scrolling in Atom lagged for a moment. So I opened up dev tools to see if I could collect enough info for a bug report, and the following errors were in the console. 

![passivelisteners](https://cloud.githubusercontent.com/assets/2133026/21173771/b15e948e-c196-11e6-86f9-ccdbdabce596.png)

The top two are familiar, and appear to be being worked on. The third one is what prompted me to research passive event listeners and to break on `mousewheel` listeners and investigate what happens when scrolling in the text editor component enough to write the code above. Also note you can make the third type of error message happen by setting a breakpoint an a non-passive `mousewheel` listener and trying to scroll the editor and then resuming execution.

**Atom Version:** 
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**OS and Version:** 
Ubuntu 16.04 LTS

**Comment by Ben3eeE** [comment]
Another performance related issue when scrolling: https://github.com/atom/atom/issues/12949

**Comment by 50Wliu** [comment]
Yes please.  This does make _perceived_ performance increase a lot since the UI still responds when scrolling.

**Comment by nathansobo** [comment]
I think that in Atom's case, this might not be helpful.

We don't actually use the browser's implementation of scrolling at all for the editor, because we only render the lines that are actually visible on screen to minimize layout costs when editing. Since the browser's scrolling is threaded and asynchronous, using the default browser scrolling implementation leads to situations where a region of the content div is scrolled into view before our scripts are notified via a `scroll` event. This can cause a visible delay between scrolling to an area and rendering its content, which people don't like.

To avoid this flicker, scrolling is implemented completely in JS. Each time you use the mouse wheel or drag a scrollbar or move the cursor, it is translated into an explicit update to our model that moves the scroll position. Passive event listeners are designed to avoid blocking the browser's native scrolling implementation with JavaScript, but we literally *implement* scrolling with JavaScript. That JavaScript just needs to run as fast as possible.

I'm open to further discussion if there's something I'm missing, though this issue has been around for a while so it may be too late.
