### ISSUE TITLE
[Feature request] - Make search non-blocking for the UI

### ISSUE THREAD

**Issue by matthew-dean** [atom/atom#13452]
When running a search for a large folder with lots of sub-folders/files, the UI drags quite a bit. It's possible that search is on a non-blocking thread, but is injecting markup at a rate that's causing thrashing. Is Atom managing inserts with a virtual DOM or is it just inserting markup whenever a result is returned?

When performing a large search, it's more valuable to have a smooth interface than to have an immediate result inserted for each match.

**Comment by 50Wliu** [comment]
Please report this on the [find-and-replace](https://github.com/atom/find-and-replace) package instead.  Thanks!
