### ISSUE TITLE
Editor is offset upon reaching line 10

### ISSUE THREAD

**Issue by mz103** [atom/atom#13455]
### Prerequisites

* [Yes] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [Yes] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [Yes] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [Yes] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [Yes] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [Yes] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Once the editor reaches line 10, there is a graphical glitch that offsets the text.

The assumption is that this is based on the length of the line number's textContent.

This is distracting when switching from tab to tab, or just programming in general.

### Steps to Reproduce

1. Create a new file (or just open a new editor tab)
2. Press enter until you hit line 10

**Expected behavior:** Editor shouldn't offset text

**Actual behavior:** Editor offsets text

### Example
(again, this is a confirmed behavior in safe mode)

![snap test artboard](https://cloud.githubusercontent.com/assets/24572473/21232510/e35cbe10-c2b9-11e6-8481-8f94a4d1416c.gif)

### Versions

Latest Atom version
Latest Mac OS X version

**Comment by 50Wliu** [comment]
Confirmed, but please define what you mean by the "latest" Atom version, as there's technically three "latest" ones: stable, beta, or dev.  You can do this by copying the output of `atom --version`.

**Comment by mz103** [comment]
@50Wliu 

```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
macOS   : 10.12.1
```

**Comment by lee-dohm** [comment]
Thanks for the feedback. This is intentional to minimize the amount of screen real-estate taken up by the line numbers for users with small screens. If you want to prevent this from happening, you can use the solution [described on the message board](https://discuss.atom.io/t/is-there-a-way-to-make-a-fixed-width-for-the-line-number-column/18971).

Thanks again for reaching out!
