### ISSUE TITLE
error opening files, and preferences, settings, etc.

### ISSUE THREAD

**Issue by otgo** [atom/atom#13465]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

You can get this information from executing `atom --version` and `apm --version` at the command line. Also, please include the OS and what version of the OS you're running.

If I open on my terminal:
atom

I can open the preferences, settings, etc, but if I open atom in the main, (utilities->atom) I cant open preferences and nothing =( just the files, how can I send a log?

Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.13rc1
git 2.10.2

OS: DEBIAN

Neither i cant open the files with atom

**Comment by ocoka** [comment]
same for me

**Comment by ocoka** [comment]
Ok, I found a solution, there is a problem with how Atom are invoked:
If it's invoked from menu, entry for which is defined in
`/usr/share/applications/atom.desktop`
line
>Exec=/usr/share/atom/atom %F
then above issue is in effect,
but if it's invoked from command line, `atom`, then all works as it should,
so i just changed to:
>Exec=/usr/bin/atom %F
in mentioned desktop file, probably something was changed in latest update about security

**Comment by jarriztg** [comment]
oh yeah @ocoka this is the fix! Thanks! but I keep this issue here, atom needs repair that

**Comment by 50Wliu** [comment]
May I ask how you two are installing Atom?  Is it through https://atom.io?

**Comment by jarriztg** [comment]
Obviously

**Comment by jarriztg** [comment]
Last version, Debian Stretch, Last versions of packages, test it in Debian Stable Jessie and also I have the bug
Package installed by dpkg, I edit /use/share/atom/atom to /usr/bin/atom and is working perfectly, sure is bad the .desktop access...

**Comment by 50Wliu** [comment]
And what about you @ocoka?

**Comment by ocoka** [comment]
Ммм.. to be honestly, i just use *webupd8team* atom launchpad repository, but... as I can see in official deb file from *atom.io*, they identical, and both contains same issue

**Comment by lee-dohm** [comment]
@ungb Can you reproduce this?

**Comment by AndreaGriffiths11** [comment]
@ungb did you manage to take a look at this?
