### ISSUE TITLE
Don't use ctrl-alt-letter keyboard shortcuts

### ISSUE THREAD

**Issue by vuki** [atom/atom#13479]
### Description

On Windows, ` ctrl-alt` , also known as AltGr, is a modifier used for entering national characters. If a keyboard shortcut using `ctrl-alt`  is assigned in Atom, it blocks the possibility to enter these characters. At lest two such shortcuts are assigned by the core module.

    'body':
      'ctrl-alt-o': 'application:add-project-folder'

    'atom-workspace atom-text-editor:not([mini])':
      'ctrl-alt-z': 'editor:checkout-head-revision'

Polish keyboard uses the following keys: a, c, e, l, n, o, s, x, z, also with ` shift`  modifier. Other languages may use other keys. As a general rule, programmers should not use ` ctrl-alt-letter`  keyboard shortcuts.

https://en.wikipedia.org/wiki/AltGr_key

### Steps to Reproduce

1. Set the keyboard layout to Polish (programmers).
2. In Atom editor, press ` ctrl-alt-o`  and ` ctrl-alt-z` 

**Expected behavior:** [What you expected to happen]
Characters `ó` and ` ż`  are entered

**Actual behavior:** [What actually happened]

Functions "Open project folder" and "Checkout HEAD revision" are activated.

### Versions

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.11
git 2.7.4.windows.1
visual studio 2015

Microsoft Windows [Version 10.0.14393]

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

As of Atom 1.13 we have removed <kbd>Ctrl-Alt</kbd> keybindings for atom core commands on Windows and Linux to avoid this conflict. The keybindings you mention have been remapped or removed in the latest beta. You can read the changelog for these changes [here](https://github.com/atom/atom/releases/tag/v1.13.0-beta4) and [here](https://github.com/atom/atom/releases/tag/v1.13.0-beta5).

In Atom 1.12 or earlier you will have to change these keybindings to avoid the conflict:

```cson
'body':
  'ctrl-alt-o': 'unset!'
  'ctrl-shift-a': 'application:add-project-folder'

'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-z': 'unset!'
```

Let us know if you find any default keybindings that we might have missed!
