### ISSUE TITLE
[OF-TOPIC] Atom like windows installer.

### ISSUE THREAD

**Issue by abuhenasobuj** [atom/atom#13474]
Does anyone here to help me integrate Atom like windows installer for my existing C# project.
I tried with Squirrel For Windows but can't get exact result what I want.

I'll be glad if anyone from here tech me to create an windows installer same as Atom installer for Windows with Auto Update.

_Please forgive me for posting this of-topic thread but seeking for help._

**Comment by 50Wliu** [comment]
@abuhenasobuj What you're looking for is [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows).  Try asking over there.

**Comment by abuhenasobuj** [comment]
Can I get **atom** nuspec file and other source that can I make installer like **Atom**?
