### ISSUE TITLE
Atom doesn't correctly identify the XML file type if it is not saved with the .xml extension

### ISSUE THREAD

**Issue by jp26jp** [atom/atom#13471]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ ] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

[Here is an example](https://www.dropbox.com/s/5nnbh1lu15jtt6u/page.mucow?dl=1). A .MuCow is a XML extension used for creating Adobe Muse widgets. Atom will always identify the file as an HTML file despite the opening tag being `<?xml version="1.0" encoding="UTF-8"?>`

### Steps to Reproduce

1. Open [this file](https://www.dropbox.com/s/5nnbh1lu15jtt6u/page.mucow?dl=1)
2. Check the file type in the bottom right corner. _Every once in awhile, it will correctly identify the file type when it's first opened. Close the file and reopen it and you'll see the file type is now HTML. If it isn't, then I'll go to the store, buy a hat, and then eat my hat._
3. Scream, "This shouldn't be identified as an HTML file!"
4. Work your magic

### Versions

1.12.7 and 1.13.0-beta8

**Comment by 50Wliu** [comment]
I'm not exactly sure why it's being matched as an HTML file, but there's two easy ways to alleviate this: by adding `mucow` as a recognized XML extension or by adding a first line match to language-xml.  Please create a new issue on [atom/language-xml](https://github.com/atom/language-xml) and we'll continue the discussion there.  Thanks!
