### ISSUE TITLE
GUI Pixelated, Distorted view on Load [ Ubuntu ] 

### ISSUE THREAD

**Issue by benyanke** [atom/atom#13472]
When I attempt to start Atom, both in normal and safemode, it just pixelates and distorts what was previously on the screen, and it stalls indefinitely. This only happens on one of my two computers running atom. 

## Screenshot
![image](https://cloud.githubusercontent.com/assets/4274911/21327039/d0d2bd08-c5f2-11e6-92b2-2d7c57f494a8.png)

## Atom Versions
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

## APM Versions 
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12+
git 2.9.3

**Comment by 50Wliu** [comment]
Yikes!  Does this happen when you try starting Atom without the GPU (`atom --disable-gpu`)?  And what version of Ubuntu are you using?

**Comment by benyanke** [comment]
OS is Ubuntu MATE 16.04.1 LTS. Will retest later.

**Comment by benyanke** [comment]
Of course as soon as I submit a bug request it stops happening. Will report back with more information if it starts again.

**Comment by lee-dohm** [comment]
Thanks @benyanke. I'm going to close this for now. Please let us know if it reoccurs and we will be happy to reopen the issue.
