### ISSUE TITLE
Extremely sluggish performance when dragging 'tabs' (splitting)

### ISSUE THREAD

**Issue by cosmix** [atom/atom#13481]
### Prerequisites

* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

Atom freezes when 'dragging' tabs from one pane another (within the same window or across windows) or when attempting to create a pane through dragging.

### Steps to Reproduce

1. Launch Atom
2. Open two files.
3. Drag one of the tabs so that part of the existing editor viewport gets highlighted (split zone indicator).

**Expected behavior:** [What you expected to happen]

Fast performance while dragging

**Actual behavior:** [What actually happened]

Sluggish performance, very slow visual update of tab movement.

### Versions

This issue is probably a regression. It started recently and manifests itself in 1.12.7 on macOS 10.12.2.

**Comment by 50Wliu** [comment]
This belongs on the [tabs](https://github.com/atom/tabs) repo - would you please move this issue there?  Thanks!
