### ISSUE TITLE
Use of coala-format binary is deprecated, use coala --format instead.

### ISSUE THREAD

**Issue by vanimesh76** [atom/atom#13480]
### Prerequisites

* [ NO] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* [ YES] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [YES ] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [ YES] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [YES ] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [ ]NO Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

For more information on how to write a good [bug report](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report) or [enhancement request](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-enhancement-suggestion), see the `CONTRIBUTING` guide.

### Description
Error in Coala package
[Description of the bug or feature]
Error: WARNING:root:Use of `coala-format` binary is deprecated, use `coala --format` instead.
    at ChildProcess.<anonymous> (C:\Users\jjj\.atom\packages\coala\node_modules\sb-exec\lib\index.js:36:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
### Steps to Reproduce
It is suuposed to auto run 
else
[1]. Step: Install coala package
[2].Step: Go to Packages
[3].Step: Whitespaces
[4].Step: Error will ShowUp

**Comment by thomasjo** [comment]
You need to re-open this issue on the [coala repo](https://github.com/coala/coala-atom).
