### ISSUE TITLE
dev/packages folder linked to SMB mount won't show up

### ISSUE THREAD

**Issue by ggreif** [atom/atom#13492]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I want to start developing a new derived package from a known one. I run `atom` on windows. When linking my package folder (which resides in my home dir in linux and is mounted on a SAMBA share in windows), the `.atom/dev/packages` hierarchy in the `atom` pane remains empty (also in developer mode).

### Steps to Reproduce

1. in windows `cmd` I go to my mounted folder: `C:\Users\ggreif>pushd Z:\ide-haskell-repl`

2. I link it to `atom`:
```
Z:\ide-haskell-repl>apm link --dev
INFO: Could not find files for the given pattern(s).
The system cannot find the file specified.
C:\Users\ggreif\.atom\dev\packages\ide-haskell-repl -> Z:\ide-haskell-repl
```
3. I start in dev mode: `Z:\ide-haskell-repl>atom -d`
4. I open up the "Settings" pane and hit the `Open Config Folder` button
5. I observe: the `dev/packages` hierarchy is empty.
6. I confirm that the folder is indeed linked:
```
Z:\ide-haskell-repl>popd
C:\Users\ggreif>dir .atom\dev
 Volume in drive C is System
 Volume Serial Number is XXXXXXX

 Directory of C:\Users\ggreif\.atom\dev

30.11.2016  17:04    <DIR>          .
30.11.2016  17:04    <DIR>          ..
22.12.2016  14:15    <DIR>          packages
               0 File(s)              0 bytes
               3 Dir(s)  231.205.515.264 bytes free

C:\Users\ggreif>dir .atom\dev\packages
 Volume in drive C is System
 Volume Serial Number is XXXXXXX

 Directory of C:\Users\ggreif\.atom\dev\packages

22.12.2016  14:15    <DIR>          .
22.12.2016  14:15    <DIR>          ..
22.12.2016  14:15    <JUNCTION>     ide-haskell-repl [Z:\ide-haskell-repl]
               0 File(s)              0 bytes
               3 Dir(s)  231.205.515.264 bytes free
```

**Expected behavior:** I'd expect that my linked package shows up under `dev/packages`
**Actual behavior:** It doesn't

**Reproduces how often:** Happens always I try it.

### Versions

OS: Windows 7 Professional

Z:\hyper-haskell>atom --version

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Z:\hyper-haskell>apm --version
INFO: Could not find files for the given pattern(s).
The system cannot find the file specified.
apm  1.12.9
npm  3.10.5
node 4.4.5
python
git
visual studio

**Comment by ggreif** [comment]
Just checked this and it is reproducible with `1.13.0 ia32`.

**Comment by lee-dohm** [comment]
@ungb Can you reproduce this?

**Comment by AndreaGriffiths11** [comment]
Thank you for your submission!

Unfortunately according to [Microsoft's documentation of junctions](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365006(v=vs.85).aspx) the type of junction you are attempting is not allowed. This appears to be an OS issue not an Atom issue, so we are going to close this. You might want to try linking from a directory that is on the local machine.

**Comment by ggreif** [comment]
@AndreaGriffiths11 so you are saying electron/atom cannot list the contents of those types of junctions the way `cmd` can? I am not a windows guy, so I am somewhat embarrassed wasting our time with an outright Microsoft bug, but why will `apm` allow me to make that link in first place? I would have expected an error or alt least a loud warning...

**Comment by AndreaGriffiths11** [comment]
@ggreif you are correct, I would expect a warning or loud error too. If you would like to file an issue on https://github.com/atom/apm, we can take a look at that. Thanks again.
