### ISSUE TITLE
Atom on Windows does not load when disconnected from Internet

### ISSUE THREAD

**Issue by MultiplyByZer01** [atom/atom#13496]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When my computer is disconnected from the Internet, Atom does not load.

### Steps to Reproduce

1. Disconnect from Internet.
2. Try to run Atom.

**Expected behavior:** Atom opens.

**Actual behavior:** Atom does not open.

**Reproduces how often:** Always

### Versions

```shell
PS C:\Users\Workstation> atom --version
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

PS C:\Users\Workstation> apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.1.windows.1
visual studio
```

### Additional Information

I am running Windows 10.

I have tried running Atom from the Start Menu, from its EXE, and from the command line.  None of these work.

Running `atom --safe` does not work. Even `atom --version` does not work when the Internet is disconnected.

I am on a laptop with WiFi.

There is nothing in `%TEMP%\Atom Crashes`.

**Comment by lee-dohm** [comment]
@ungb or @50Wliu can you reproduce this?

**Comment by 50Wliu** [comment]
Unable to confirm.  I've been without wifi a few times yet have been able to open Atom as usual.  Can't give an exact version number but it definitely works on 1.12+, Windows 10 x64.  I'll be able to supply more information in a week if needed.

**Comment by Ben3eeE** [comment]
Refs: https://github.com/atom/atom/issues/12586

**Comment by Equinox** [comment]
FWIW: I can't reproduce this or the above linked #12586. 

Windows 10, x64.

**Comment by MultiplyByZer01** [comment]
After restarting my PC, Atom seems to work again, even when offline.
