### ISSUE TITLE
Non-Keypad Number Key Keystrokes Ignored with htm/html files

### ISSUE THREAD

**Issue by emiscience** [atom/atom#13497]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When editing files with the extension .htm or .html the number keys (non keypad number keys) are not working however they do work when you press shift and the number key equivalent e.g. 

> !@£$%^&*()_+

I've confirmed this by copying an htm file as filename.htm and filename.txt

The above is not reproducible with the file with the .txt extension.
### Steps to Reproduce

1. Open atom (either via macOS UI Applications or via terminal)
2. In atom open any html file with extension .htm or .html
3. Whilst editing the html file press any number key (non keypad as I'm using a MacBook Pro)

**Expected behavior:** [What you expect to happen]

A number to appear at the cursor

**Actual behavior:** [What actually happens]

Keystroke ignored

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

1.12.7 production release
1.13.0-beta8 beta release

**Comment by Ben3eeE** [comment]
Thanks for reaching out! Your issue template is missing the prerequisites section. We need to know if this reproduces in safe mode. I also have some additional questions:

* Can you reproduce this in safe mode `atom --safe`?
* What do you see in the [keybinding resolver](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings) when pressing these keys?
* Can you post the results of typing the numeric keys after running the following devtools console script:
```
document.addEventListener('keydown', e => console.log(e), true)
```

**Comment by emiscience** [comment]
1) Sorry I did actually test it in safe mode but neglected to comment. Indeed it happens in safe mode too. This applies to both public and beta releases, the version info is below:

```
$ atom --version
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ atom-beta --version
Atom    : 1.13.0-beta8
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

2) The keybinding resolver logs the actual key e.g. 0, 1, 2, 3, 4 and just below it it comes up with another message e.g.

![screen shot 2016-12-24 at 02 47 57](https://cloud.githubusercontent.com/assets/5453349/21464909/5c58ef8e-c984-11e6-9354-e79b411b18a6.png)

Similar happens on all of the other numeric keys, the difference being the letter shown next to the X (in the image). In order the keys show up as:

`
0    o

1    p

2    e

3    n

4    -

5    h

6    t
7    m
8    l
9    -
`

**Comment by Ben3eeE** [comment]
Thanks for the additional information! I can reproduce this with the given information.

>Also the keycap.cson is default as I've never touched this. Currently it only has 32 commented out lines and

That's weird, the default keymap should only have the starting 32 lines of comments and nothing else. Maybe you don't remember adding this? Or maybe the `open-html-in-browser` package somehow added this? The following keymap is invalid because it only contains a command and not the keystroke and likely is the cause of the issue you are seeing:

```cson
'atom-text-editor[data-grammar~="html"]':
 'open-html-in-browser:open'
```

* Can you try to remove those lines and see if the problem persists?

**Comment by emiscience** [comment]
I've removed the lines and it solved the issue on both the public and beta releases!

Many thanks!
