### ISSUE TITLE
Atom gets stuck when searching for something common in a large project

### ISSUE THREAD

**Issue by SelaOAL** [atom/atom#13500]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom gets stuck when searching for something very common in a large project.

### Steps to Reproduce

Open a folder with a large project.
Press ctrl shift f to look in the whole project.
Search for something very common like 'console.log('
Atom window gets stuck, I see the number of matches slowly rise to thousands and then it stops.
There's no way to stop the search other than closing down the window.

**Expected behavior:**

To not get stuck and to be able to stop the search.

**Actual behavior:**

Window hangs.

**Reproduces how often:** 

Always.

### Versions

1.12.7 on Windows 10.

### Additional Information

With notepad++ I get about 2500 matches in the same folder.

**Comment by 50Wliu** [comment]
Please reopen this on the https://github.com/atom/find-and-replace repository.  Thanks!
