### ISSUE TITLE
Monospaced font NOT aligned in Windows

### ISSUE THREAD

**Issue by axolo** [atom/atom#13508]
![consolas](https://cloud.githubusercontent.com/assets/1021935/21511133/a8bf6852-ccd7-11e6-8242-efbcc2347cfe.png)

![microsoftyahei](https://cloud.githubusercontent.com/assets/1021935/21511134/a98ce25a-ccd7-11e6-87c2-13aaf2fe5c9f.png)

![simsun](https://cloud.githubusercontent.com/assets/1021935/21511136/aaee25d2-ccd7-11e6-9ab0-5186f91aa166.png)

**Comment by damieng** [comment]
Consolas doesn't have the Japanese characters and so it is substituting from another font. 

Can you try putting that block of text in a <pre> tag in a html page and opening it in Chrome?  I suspect the layout there will also be misaligned.

**Comment by axolo** [comment]
Thanks.
May be look for some CJK Monospaced Fonts.
I got it.
https://github.com/be5invis/Iosevka
![qq 20161230123358](https://cloud.githubusercontent.com/assets/1021935/21559735/8213e3c0-ce8c-11e6-9585-98f2961f63c2.png)


BTW: Sublime Text CJK Fonts Uniform Scale.
![qq 20161230091501](https://cloud.githubusercontent.com/assets/1021935/21559070/3332aab8-ce80-11e6-90c5-17ab0e7c3d6c.png)
