### ISSUE TITLE
No way to scope a grammar capture

### ISSUE THREAD

**Issue by isiahmeadows** [atom/atom#13515]
### Description

There is no way to scope a grammar capture for specific grammar rules, leading to very odd, buggy-looking syntax highlights.

### Steps to Reproduce

1. Set the language to any that has a rule that features both of the following. `language-gfm` and `language-javascript` both fulfill this requirement in their grammars.
  - A `begin` and `end` capture
  - A `pattern` that delegates to another language that also has a rule containing both a `begin` and `end` capture. (It doesn't have to delegate, though.)

2. Create something that matches that rule. For GFM, a code block tagged with `css` would suffice, and for JS, a tagged template starting with `html` would work.

3. Within that block, type something that would match the `begin` half of any rule in the other language that includes both a `begin` and `end`. Do not include the end. For GFM or JS, just start a comment in CSS or HTML, respectively.

4. Observe very odd syntax highlighting. It looks like a bug because it can't be contained, and repros 100% of the time.

If you followed the above repro, the code might look like this pre-syntax highlighting:

<ul>
<li><p>GFM -> CSS
<pre><code>```css<br>
/* This is an unterminated comment<br>
```<br>
<br>
Some more text...
</code></pre>
<li><p>JS -> HTML
<pre><code>html`<br>
&lt;!-- This is an unterminated comment<br>
`;<br>
<br>
someOtherCall();
</code></pre>
</ul>

Here's a few screenshots of other code.

`language-gfm` -> `language-javascript`:

![screenshot from 2016-10-24 23-47-59](https://cloud.githubusercontent.com/assets/4483844/19672425/57f076e8-9a44-11e6-8776-4ebaf959af1b.png)

`language-javascript` -> `language-html`

![screenshot from 2016-10-24 23-52-48](https://cloud.githubusercontent.com/assets/4483844/19672495/0a6b770a-9a45-11e6-85a4-4ec7ef657b93.png)

### Versions

OS: Ubuntu GNOME 14.04 (although it's been repro'd in Windows by others)
Atom: v1.12.5 (been going on for quite a while)

### Additional Information

Initially reported in atom/language-gfm#171, but I filed it here because it's language-agnostic.

**Comment by 50Wliu** [comment]
Yeah.  We need a way to handle this.  I've been looking at injections and injection selectors, but I'm not sure that's enough.

Also, this may be better suited at https://github.com/atom/first-mate, so I'm going to close this issue and ask you to file it there instead.

**Comment by isiahmeadows** [comment]
@50Wliu Thanks! (It was unclear which repo it belonged in.)
