### ISSUE TITLE
Bad performance editing a line after many blank lines

### ISSUE THREAD

**Issue by YaLTeR** [atom/atom#13512]
### Prerequisites

* [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [X] Tried disabling every package in safe mode on a clean install
* [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Text operations (inserting / deleting characters, pasting, etc.) on a line that is preceded by many blank lines take a really long time.

### Steps to Reproduce

1. Create a new file.
2. Paste about 2000 blank lines (the performance gradually decreases with the amount of lines, for me 2000 is where it's already very noticeable).
3. Try to type something.

**Expected behavior:** Characters are inserted instantly.

**Actual behavior:** Individual characters take about 2 seconds to insert, typing many characters at once makes the editor hang for about 10 seconds before inserting them all at once.

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Linux 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```

### Profiler log
Trying to save the profiler log produced an empty file for some reason, here's a screenshot:
![Profiler log](https://i.imgur.com/4gPdAH7.png)

**Comment by 50Wliu** [comment]
I can't reproduce this on Atom 1.14.0-dev-3e33aa1.  @YaLTeR can you please fill out the rest of the issue template, specifically the prerequisites section?

**Comment by YaLTeR** [comment]
Building latest git atom to check there.

**Comment by YaLTeR** [comment]
Seems to be fixed on latest git.

**Comment by 50Wliu** [comment]
Awesome!  Yeah, I had a suspicion that this would be fixed after the recent work done on improving large file support.
