### ISSUE TITLE
Build failing - "Could not determine Electron version"

### ISSUE THREAD

**Issue by 1nF0rmed** [atom/atom#13529]
### Prerequisites

    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I would like to manage my versions of Atom via building the executable's from source, but I've been unable to successfully build anything with script/build.

### Steps to Reproduce

1. Follow the instructions at [here](https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md)
2. Navigate to local Atom clone.
3. Open Administrator CMD in the script directory of the clone.
4. Execute the build script.
5. Wait for a few minutes after printing "Installing apm" on the screen.
6. The Error's will be displayed.

**Expected behavior:** [What you expect to happen]
Given NodeJS 6.9, Python 2.7, and an installed Visual Studio 2015 with Visual C++ support, Atom should build as easily on Windows as it does on Linux.

**Actual behavior:** [What actually happens]
*

> C:\Users\1nf0rmed\Documents\atom-master\script>build
Node:   v6.9.2
Npm:    v3.10.5
Python: v2.7.12
Installing script dependencies
Installing apm
C:\Users\1nf0rmed\Documents\atom-master\apm\node_modules\atom-package-manager\lib\command.js:147
            throw new Error('Could not determine Electron version');
            ^
Error: Could not determine Electron version
    at C:\Users\1nf0rmed\Documents\atom-master\apm\node_modules\atom-package-manager\lib\command.js:147:19
    at C:\Users\1nf0rmed\Documents\atom-master\apm\node_modules\atom-package-manager\lib\command.js:165:20
    at C:\Users\1nf0rmed\Documents\atom-master\apm\node_modules\atom-package-manager\lib\apm.js:40:18
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
 child_process.js:506
    throw err;
    ^
Error: Command failed: C:\Users\1nf0rmed\Documents\atom-master\apm\node_modules\atom-package-manager\bin\apm.cmd --loglevel=error install
    at checkExecSyncError (child_process.js:483:13)
    at Object.execFileSync (child_process.js:503:13)
    at module.exports (C:\Users\1nf0rmed\Documents\atom-master\script\lib\install-atom-dependencies.js:15:16)
    at Object.<anonymous> (C:\Users\1nf0rmed\Documents\atom-master\script\bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Reproduces how often:** [What percentage of the time does it reproduce?]
90% of the time I get this output.
The rest of the time I receive an error saying "EPERM operation not permitted, rename"

### Versions

Windows 10
Microsoft Visual Studio Community 2015
    Version 14 Update 3

Node: v6.9.2
npm: v3.10.5
Python: v2.7.12
Electron: v1.4.13

**Comment by 50Wliu** [comment]
Can you paste the contents of `atom-master/package.json` here?  And are you building Atom directly from master or have you changed some things locally/used a different branch?

**Comment by lee-dohm** [comment]
Thank you for contributing!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/13318. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
