### ISSUE TITLE
You can't zoom Project Find Results (or settings)

### ISSUE THREAD

**Issue by mark0978** [atom/atom#13530]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

All other windows in Atom (except for settings) respond to Ctrl+/- for zooming.  Both of these windows should already be web views, therefore I would expect them to zoom like all the other windows.  But for some reason they don't.  The fonts are too small for me to read if I can't zoom them.

### Steps to Reproduce

1. Use Find in Proejct to locate things in your project
2. Try to zoom results
3. squint, curse, cry

**Expected behavior:** Text gets bigger, text becomes readable

**Actual behavior:** Nothin

**Reproduces how often:** Always

### Versions

Atom 1.12.7 on  OSX 10.11.6

**Comment by 50Wliu** [comment]
If you're using the One Light or One Dark UI themes, those allow you to customize the UI font size.  Otherwise, you might want to check out https://github.com/atom/atom/issues/11905#issuecomment-224865625.
