### ISSUE TITLE
Error: nothing provides libXss1 needed by atom-1.12.8-0.1.x86_64

### ISSUE THREAD

**Issue by fusion809** [atom/atom#13535]
Hi,

It seems like you've patched one problem, only to expose yet another with the release of Atom 1.12.8. As while you may have fixed a CentOS dependency issue there's a new Fedora dependency issue. Trying to install Atom 1.12.8 with Fedora's DNF package manager (namely on Fedora 25) gave the error:

```bash
Last metadata expiration check: 1:00:11 ago on Wed Jan  4 07:13:30 2017.
Error: nothing provides libXss1 needed by atom-1.12.8-0.1.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)
```

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
[`libXScrnSaver`](https://apps.fedoraproject.org/packages/libXScrnSaver) is probably the Fedora package Atom is meant to depend on in place of libXss1.

**Comment by 50Wliu** [comment]
Oh noooo

Thanks for the report!

**Comment by colindensem** [comment]
Also hit this. 1.12.7 installs fine on fedora 25.

**Comment by nsoui** [comment]
as a workaround, you may do the following
`rpmrebuild -e -p atom.x86_64.rpm`

replace libXss1 by libXScrnSaver, save and then install the newly created RPM 
`sudo dnf install /home/USER/rpmbuild/RPMS/x86_64/atom-1.12.8-0.1.x86_64.rpm`

**Comment by fusion809** [comment]
@nsoui thanks but frankly what's the point? The only difference between 1.12.7 and 1.12.8, according to the release notes, is that the CentOS packaging issue is fixed. So why not stick to 1.12.7 until this issue is resolved.

**Comment by ashcrow** [comment]
Confirmed it's ``libXScrnSaver`` in Fedora (24).

```
$ sudo dnf whatprovides /usr/lib/libXss.so.1.0.0 
Last metadata expiration check: 1:58:17 ago on Wed Jan  4 08:50:39 2017.
libXScrnSaver-1.2.2-10.fc24.i686 : X.Org X11 libXss runtime library
Repo        : @System

libXScrnSaver-1.2.2-10.fc24.i686 : X.Org X11 libXss runtime library
Repo        : fedora
```

One can also get around this with ```sudo rpm -Uvh --nodeps atom.x86_64.rpm``` assuming ``libXScrnSaver`` is installed.

**Comment by ashcrow** [comment]
Relevant commit: https://github.com/atom/atom/commit/af4da948e9aed3d62de3a52992fab5f8c69e5f36

It looks like the rpm was built on a non rhel/fedora image (Build host was testing-docker-a184e49d-56cf-445e-ab72-c1ccdf1e0e32). My guess is that there will need to be two rpm builds: Red Hat-like, Other (SuSE-like? just a guess...).

**Comment by alflanagan** [comment]
Also seen with atom-beta-1.13.0.beta9-0.1.x86_64.

**Comment by ungb** [comment]
I have a PR open that should address this issue. https://github.com/atom/atom/pull/13536.  Works for Centos and Fedora so far. Testing on OpenSuse. Will patch today if things look good.

**Comment by FloodCode** [comment]
I have a same issue

**Comment by iolsen** [comment]
Sorry about this, folks. Until we have a proper fix we've rolled this change back for 1.12.9 and 1.13.0-beta10.

**Comment by fooishbar** [comment]
@iolsen Given that #13536 doesn't actually resolve the issue (unless you build separate SUSE vs. RHEL/Fedora RPMs), should this issue be reopened? It's still uninstallable on F25, unless you use `--nodeps`.

```error: Failed dependencies:
	libXss.so.1 is needed by atom-beta-1.14.0.beta3-0.1.x86_64```

**Comment by Ben3eeE** [comment]
@fooishbar Thank you for reporting this :sparkles: 

This issue was later fixed in https://github.com/atom/atom/pull/13573 but this unfortunately did not make it into the latest hotfix release. I have added this to our [regression tracking issue](https://github.com/atom/atom/issues/13628).

**Comment by ungb** [comment]
Hi @fooishbar, I've seen this also when you run `sudo rpm -i atom.x86_64.rpm`.  since you're on Fedora 25, can you try running `sudo yum install atom.x86_64.rpm`? (or `sudo dnf install ./atom.x86_64.rpm` see: https://github.com/atom/atom#fedora-22)

I don't think running `sudo rpm` would resolve the dependency and if you install it with nodeps, atom will install but will probably get a runtime error when you try starting atom.

**Comment by fooishbar** [comment]
@ungb I am on F25 indeed, and there are no runtime errors as libXScrnSaver is installed, providing libXss.so.1 for 64-bit. `dnf` will resolve it by installing 32-bit X11 libraries, which seems a bit of a waste. Hopefully when #13573 lands in packages (I'm currently trying 1.14.0-beta3), this will just go away.

**Comment by younes1945** [comment]
check the line to fixing the probelm https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux

**Comment by ungb** [comment]
@fooishbar let us know if the new changes to how to install on linux fix the issue for you ✌️.

**Comment by fooishbar** [comment]
@ungb Sorry, I no longer use Atom.

**Comment by fusion809** [comment]
Nor do I. I feel Vim and Visual Studio Code (VSCode) are superior to Atom now, partly because on Linux they are more devoid of these sorts of issues and also because until recently they were easier to keep up-to-date on Linux. That and because they tend to have better features, like VSCode's auto-complete for JavaScript is truly intelligent, following 'requires' so that function definitions are automatically loaded. 

Still grateful for Atom's developers and their efforts to maintain this fine piece of software.
