### ISSUE TITLE
With PHP Inside JS Script, Throws error

### ISSUE THREAD

**Issue by ahinkle** [atom/atom#13532]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When you write a php statement inside of a JavaScript statement on a .php page, it throws an error inside the IDE when there is actually no errors.

Stackoverflow:
[http://stackoverflow.com/questions/41433018/atom-editor-error-when-php-is-inside-javascript](url)

### Steps to Reproduce

1. Create new .PHP Page
2. Paste the following example code: (remove spaces.. code doesn't show up here)
```
< html>

< head>

  < ?php $testvar = "Test"; ?>

< script> 

var test = < ?php echo $testvar; ?>

< /script>

< /head>

< body>

< p> This is a test. </p>

< /body>

< /html>`

```
3. Page Displays Correctly but the Editor IDE highlights everything else on page as an error.

**Expected behavior:** Not show the red  highlighted text.

**Actual behavior:** Drops color on all code after the script, highlights everything in red.

**Reproduces how often:** 100%

### Versions

1.12.7 ATOM, Windows 10.

### Additional Information

Screenshot:
http://i.imgur.com/6kc2Yob.png
![jserror](https://cloud.githubusercontent.com/assets/17038330/21595104/dd232176-d0ef-11e6-8bc2-66b565da8514.png)

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.13, currently in beta.
