### ISSUE TITLE
Yaml code block doesn't end with ``` in editor in Markdown file

### ISSUE THREAD

**Issue by brookshelley** [atom/atom#13544]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When editing a markdown file and inserting a yaml code block (```yaml), ending the block with ``` doesn't appear to stop the Yaml parsing for the remainder of the document. Markdown preview/output is not effected, and shows correctly. Syntax highlighting for content below the closing ``` still shows Yaml formatting though.

### Steps to Reproduce

1. Create a markdown file
2. Write some content. Add a ```yaml <yaml goes here> ``` block. Write more text after the yaml, maybe even another code block for some other format.
3. View the content below the close of the yaml block.

**Expected behavior:** The yaml syntax highlighting for the yaml block will end with the ``` closing element.

**Actual behavior:** The yaml syntax highlighting continues below the code block closing ```.

**Reproduces how often:** 100%

### Versions

Mac OS 10.12.2
Atom 1.12.7

### Additional Information

Note that the Markdown preview correctly shows output that matches the expected behavior of the yaml block closing.

**Comment by brookshelley** [comment]
(Apologies if this should've been filed under https://github.com/atom/language-yaml)

**Comment by 50Wliu** [comment]
This is a wider issue that's covered in https://github.com/atom/first-mate/issues/83 - feel free to subscribe there for updates.
