### ISSUE TITLE
php and javascript mixed breaks the highlighting of the editor

### ISSUE THREAD

**Issue by jzilg** [atom/atom#13546]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If I have a php- or phtml-file with a script-tag, where I enter some php-code. The editor-highlighting becomes wrong after this php-Statement

### Steps to Reproduce

1. create a php-file
2. write some HTML
3. create a script-tag
4. write a php-tag inside of this script-tag
5. the HTML after this php-tag is all wrong highlighted

**Expected behavior:** The Code after the php-inside-the-script-tag is highlighted normal

![fine](https://cloud.githubusercontent.com/assets/15897388/21679278/7579efa4-d343-11e6-88a3-e69ce01c905a.png)

**Actual behavior:** The Code after the php-inside-the-script-tag is all black and red

![bug](https://cloud.githubusercontent.com/assets/15897388/21679279/78c96d4c-d343-11e6-969d-f3732e491a15.png)

**Reproduces how often:** 100%

### Versions

Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4

### Additional Information

Ubuntu Gnome
Distributor ID: Ubuntu
Description: Ubuntu 16.04.1 LTS
Release:	16.04
Codename: xenial
Kernel: 4.4.0-57-generic

**Comment by 50Wliu** [comment]
This has been fixed in Atom 1.13, currently in beta.
