### ISSUE TITLE
Cursor::getPixelRect calls deprecated TextEditor::pixelRectForScreenRange

### ISSUE THREAD

**Issue by benphelps** [atom/atom#13541]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`Cursor::getPixelRect` calls deprecated `TextEditor::pixelRectForScreenRange`. Causing a deprecation warning in latest Atom Beta 1.13.0-beta9.

`This is now a view method. Call TextEditorElement::pixelRectForScreenRange instead.`

### Steps to Reproduce

Use the color-picker plugin on latest beta, check deprecation warnings.  Throws this call stack in the warning:

```
TextEditor.pixelRectForScreenRange - /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:3559:12
Cursor.getPixelRect - /Applications/Atom Beta.app/Contents/Resources/app.asar/src/cursor.js:675:26
```

I'm sure this happens in other plugins, this just happens to be the one that shows it for me.

### Versions

Atom    : 1.13.0-beta9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS X El Capitan 10.11.6 (15G1212)

**Comment by 50Wliu** [comment]
getPixelRect is a private method and shouldn't be used in packages (hence why it's not documented anywhere).

Your issue is still valid though, we shouldn't be using pixelRectForScreenRange if it's deprecated.

**Comment by maxbrunsfeld** [comment]
I think we should simply remove that method. It doesn't look like it's used anywhere.

**Comment by thomaslindstrom** [comment]
Before you go ahead and do that, is there an alternative?

**Comment by maxbrunsfeld** [comment]
Yeah, `TextEditorElement::pixelPositionForScreenPosition`. To obtain a screen position for a cursor call, `Cursor::getScreenPosition`.

**Comment by thomaslindstrom** [comment]
Sweet, thanks! I'll push this in an update ASAP.

**Comment by thomaslindstrom** [comment]
@maxbrunsfeld I've pushed the update. Not using `Cursor.getPixelRect` in `color-picker` `v2.2.4`. :)
