### ISSUE TITLE
New to Atom. 1st install crash on launch.

### ISSUE THREAD

**Issue by GRRRillaNinja** [atom/atom#13550]
New Atom user here. Never installed before.

Installed today and immediately got this error on launch. Uninstalled and re-installed with the same result.
![untitled](https://cloud.githubusercontent.com/assets/14032888/21698650/918a8e3c-d35d-11e6-8366-4854bb841ea1.png)

**Comment by damieng** [comment]
Can you please file a new bug with the issue template completed - we are not going to be able to diagnose your issue without much more information.
