### ISSUE TITLE
"414 Request-URI Too Large" on Create issue

### ISSUE THREAD

**Issue by cbrunnkvist** [atom/atom#13552]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The create package bug report action can sometime include too much data (like a looong stacktrace) on the query parameter which results in the Github "New Issue" page failing with 414 error in the browser.

### Steps to Reproduce

1. Find an appropriate bug. For me, the current issue is with the `navigation-history` package, but it is not specific to one package, it is probably due to the user (me!) having many packages in "Disabled" mode perhaps.

The link in my case: 

https://github.com/Tyriar/navigation-history/issues/new?title=Failed%20to%20activate%20the%20navigation-history%20package&body=%5BEnter%20steps%20to%20reproduce%20below:%5D%0A%0A1.%20...%0A2.%20...%0A%0A**Atom%20Version**:%201.12.9%0A**Electron%20Version**:%201.3.13%0A**System**:%20Mac%20OS%20X%2010.12.2%0A**Thrown%20From**:%20%5Bnavigation-history%5D(https://github.com/Tyriar/navigation-history)%20package,%20v0.1.8%0A%0A%0A%23%23%23%20Stack%20Trace%0A%0AFailed%20to%20activate%20the%20navigation-history%20package%0A%0A%60%60%60%0AAt%20editor%20is%20not%20defined%0A%0AReferenceError:%20editor%20is%20not%20defined%0A%20%20%20%20at%20new%20CursorWatcher%20(/Users/conny/.atom/packages/navigation-history/lib/cursor-watcher.coffee:4:5)%0A%20%20%20%20at%20/Users/conny/.atom/packages/navigation-history/lib/main.coffee:22:27%0A%20%20%20%20at%20Workspace.module.exports.Workspace.observeTextEditors%20(/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:9)%0A%20%20%20%20at%20Object.activate%20(/Users/conny/.atom/packages/navigation-history/lib/main.coffee:21:20)%0A%20%20%20%20at%20Package.module.exports.Package.activateNow%20(/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)%0A%20%20%20%20at%20/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32%0A%20%20%20%20at%20Package.module.exports.Package.measure%20(/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)%0A%20%20%20%20at%20/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26%0A%20%20%20%20at%20Package.module.exports.Package.activate%20(/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)%0A%20%20%20%20at%20PackageManager.module.exports.PackageManager.activatePackage%20(/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)%0A%20%20%20%20at%20/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:531:29%0A%20%20%20%20at%20Config.module.exports.Config.transactAsync%20(/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)%0A%20%20%20%20at%20PackageManager.module.exports.PackageManager.activatePackages%20(/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:19)%0A%20%20%20%20at%20PackageManager.module.exports.PackageManager.activate%20(/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:508:46)%0A%20%20%20%20at%20/Users/conny/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:792:28%0A%60%60%60%0A%0A%23%23%23%20Commands%0A%0A%60%60%60%0A%60%60%60%0A%0A%23%23%23%20Config%0A%0A%60%60%60json%0A%7B%0A%20%20%22core%22:%20%7B%0A%20%20%20%20%22disabledPackages%22:%20%5B%0A%20%20%20%20%20%20%22node-resolver%22,%0A%20%20%20%20%20%20%22titanium-language-javascript%22,%0A%20%20%20%20%20%20%22titanium-build%22,%0A%20%20%20%20%20%20%22titanium-alloy%22,%0A%20%20%20%20%20%20%22ti-create%22,%0A%20%20%20%20%20%20%22npm-docs%22,%0A%20%20%20%20%20%20%22build%22,%0A%20%20%20%20%20%20%22cucumber%22,%0A%20%20%20%20%20%20%22atom-ternjs%22,%0A%20%20%20%20%20%20%22atom-php-navigation%22,%0A%20%20%20%20%20%20%22javascript-snippets%22,%0A%20%20%20%20%20%20%22language-java%22,%0A%20%20%20%20%20%20%22goto%22,%0A%20%20%20%20%20%20%22es-navigation%22%0A%20%20%20%20%5D,%0A%20%20%20%20%22ignoredNames%22:%20%5B%0A%20%20%20%20%20%20%22.git%22,%0A%20%20%20%20%20%20%22.hg%22,%0A%20%20%20%20%20%20%22.svn%22,%0A%20%20%20%20%20%20%22.DS_Store%22,%0A%20%20%20%20%20%20%22._*%22,%0A%20%20%20%20%20%20%22Thumbs.db%22,%0A%20%20%20%20%20%20%22node_modules%22%0A%20%20%20%20%5D,%0A%20%20%20%20%22telemetryConsent%22:%20%22limited%22%0A%20%20%7D%0A%7D%0A%60%60%60%0A%0A%23%23%23%20Installed%20Packages%0A%0A%60%60%60coffee%0A%23%20User%0Aansible-snippets,%20v0.2.0%20(inactive)%0Aapiary-highlighter,%20v0.4.0%20(inactive)%0Aatom-beautify,%20v0.29.14%20(inactive)%0Aatom-php-navigation,%20v0.6.0%20(inactive)%0Aatom-ternjs,%20v0.16.1%20(inactive)%0Aautocomplete-modules,%20v1.6.7%20(inactive)%0Abuild,%20v0.67.0%20(inactive)%0Aclipboard-history,%20v0.6.6%20(inactive)%0Acucumber,%20v0.5.0%20(inactive)%0Adockerletion,%20v0.2.0%20(inactive)%0Aes-navigation,%20v0.1.5%20(inactive)%0Aes6-javascript,%20v1.0.0%20(inactive)%0Agoto,%20v1.8.2%20(inactive)%0Ahyperclick,%20v0.0.39%20(inactive)%0Aindentation-indicator,%20v1.0.0%20(inactive)%0Ajavascript-snippets,%20v1.2.1%20(inactive)%0Ajs-hyperclick,%20v1.9.0%20(inactive)%0Alanguage-docker,%20v1.1.7%20(inactive)%0Alanguage-gherkin,%20v1.0.4%20(inactive)%0Alanguage-tss,%20v0.4.0%20(inactive)%0Alinter,%20v1.11.18%20(inactive)%0Alinter-eslint,%20v8.0.0%20(inactive)%0Alinter-php,%20v1.3.1%20(inactive)%0Amerge-conflicts,%20v1.4.4%20(inactive)%0Aminimap,%20v4.25.7%20(inactive)%0Anavigation-history,%20v0.1.8%20(inactive)%0Anode-resolver,%20v1.0.1%20(inactive)%0Anodejs-snippets,%20v2.0.2%20(inactive)%0Anpm-docs,%20v0.2.0%20(inactive)%0Aphp-twig,%20v4.0.0%20(inactive)%0Apipe,%20v0.4.0%20(inactive)%0Ati-create,%20v0.26.0%20(inactive)%0Atitanium-alloy,%20v0.13.4%20(inactive)%0Atitanium-build,%20v0.8.1%20(inactive)%0Atitanium-language-javascript,%20v0.48.0%20(inactive)%0Aatom-dark-syntax,%20v0.27.0%20(inactive)%0Aatom-dark-ui,%20v0.52.0%20(inactive)%0Aatom-light-syntax,%20v0.28.0%20(inactive)%0Aatom-light-ui,%20v0.45.0%20(inactive)%0Abase16-tomorrow-dark-theme,%20v1.3.0%20(inactive)%0Abase16-tomorrow-light-theme,%20v1.3.0%20(inactive)%0Aone-dark-ui,%20v1.6.2%20(inactive)%0Aone-light-ui,%20v1.6.2%20(inactive)%0Aone-dark-syntax,%20v1.5.0%20(inactive)%0Aone-light-syntax,%20v1.5.0%20(inactive)%0Asolarized-dark-syntax,%20v1.0.5%20(inactive)%0Asolarized-light-syntax,%20v1.0.5%20(inactive)%0Aabout,%20v1.7.0%20(inactive)%0Aarchive-view,%20v0.62.0%20(inactive)%0Aautocomplete-atom-api,%20v0.10.0%20(inactive)%0Aautocomplete-css,%20v0.13.1%20(inactive)%0Aautocomplete-html,%20v0.7.2%20(inactive)%0Aautocomplete-plus,%20v2.31.4%20(inactive)%0Aautocomplete-snippets,%20v1.11.0%20(inactive)%0Aautoflow,%20v0.27.0%20(inactive)%0Aautosave,%20v0.23.1%20(inactive)%0Abackground-tips,%20v0.26.1%20(inactive)%0Abookmarks,%20v0.42.0%20(inactive)%0Abracket-matcher,%20v0.82.2%20(inactive)%0Acommand-palette,%20v0.39.0%20(inactive)%0Adeprecation-cop,%20v0.54.1%20(inactive)%0Adev-live-reload,%20v0.47.0%20(inactive)%0Aencoding-selector,%20v0.22.0%20(inactive)%0Aexception-reporting,%20v0.40.0%20(inactive)%0Afind-and-replace,%20v0.202.2%20(inactive)%0Afuzzy-finder,%20v1.4.0%20(inactive)%0Agit-diff,%20v1.1.0%20(inactive)%0Ago-to-line,%20v0.31.0%20(inactive)%0Agrammar-selector,%20v0.48.2%20(inactive)%0Aimage-view,%20v0.60.0%20(inactive)%0Aincompatible-packages,%20v0.26.1%20(inactive)%0Akeybinding-resolver,%20v0.35.0%20(inactive)%0Aline-ending-selector,%20v0.5.0%20(inactive)%0Alink,%20v0.31.2%20(inactive)%0Amarkdown-preview,%20v0.158.8%20(inactive)%0Ametrics,%20v1.1.2%20(inactive)%0Anotifications,%20v0.65.1%20(inactive)%0Aopen-on-github,%20v1.2.1%20(inactive)%0Apackage-generator,%20v1.0.1%20(inactive)%0Asettings-view,%20v0.243.1%20(inactive)%0Asnippets,%20v1.0.4%20(inactive)%0Aspell-check,%20v0.68.4%20(inactive)%0Astatus-bar,%20v1.4.1%20(inactive)%0Astyleguide,%20v0.47.2%20(inactive)%0Asymbols-view,%20v0.113.1%20(inactive)%0Atabs,%20v0.103.0%20(inactive)%0Atimecop,%20v0.33.2%20(inactive)%0Atree-view,%20v0.210.0%20(inactive)%0Aupdate-package-dependencies,%20v0.10.0%20(inactive)%0Awelcome,%20v0.35.1%20(inactive)%0Awhitespace,%20v0.35.0%20(inactive)%0Awrap-guide,%20v0.38.2%20(inactive)%0Alanguage-c,%20v0.54.0%20(inactive)%0Alanguage-clojure,%20v0.22.1%20(inactive)%0Alanguage-coffee-script,%20v0.48.0%20(inactive)%0Alanguage-csharp,%20v0.13.0%20(inactive)%0Alanguage-css,%20v0.40.1%20(inactive)%0Alanguage-gfm,%20v0.88.0%20(inactive)%0Alanguage-git,%20v0.15.0%20(inactive)%0Alanguage-go,%20v0.43.0%20(inactive)%0Alanguage-html,%20v0.47.1%20(inactive)%0Alanguage-hyperlink,%20v0.16.1%20(inactive)%0Alanguage-java,%20v0.24.0%20(inactive)%0Alanguage-javascript,%20v0.122.0%20(inactive)%0Alanguage-json,%20v0.18.3%20(inactive)%0Alanguage-less,%20v0.29.6%20(inactive)%0Alanguage-make,%20v0.22.2%20(inactive)%0Alanguage-mustache,%20v0.13.0%20(inactive)%0Alanguage-objective-c,%20v0.15.1%20(inactive)%0Alanguage-perl,%20v0.37.0%20(inactive)%0Alanguage-php,%20v0.37.3%20(inactive)%0Alanguage-property-list,%20v0.8.0%20(inactive)%0Alanguage-python,%20v0.45.1%20(inactive)%0Alanguage-ruby,%20v0.70.2%20(inactive)%0Alanguage-ruby-on-rails,%20v0.25.1%20(inactive)%0Alanguage-sass,%20v0.57.0%20(inactive)%0Alanguage-shellscript,%20v0.23.0%20(inactive)%0Alanguage-source,%20v0.9.0%20(inactive)%0Alanguage-sql,%20v0.25.0%20(inactive)%0Alanguage-text,%20v0.7.1%20(inactive)%0Alanguage-todo,%20v0.29.1%20(inactive)%0Alanguage-toml,%20v0.18.1%20(inactive)%0Alanguage-xml,%20v0.34.12%20(inactive)%0Alanguage-yaml,%20v0.27.1%20(inactive)%0A%0A%23%20Dev%0ANo%20dev%20packages%0A%60%60%60%0A%0A

**Expected behavior:** 

You should see the Github "New issue" page for the package project. 

**Actual behavior:** [What actually happens]

Github reports an error: `414 Request-URI Too Large`.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time I click the button, with my current collection of packages :)

### Versions

Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

macOS: 10.12.2

**Comment by 50Wliu** [comment]
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/notifications/issues/129. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by cbrunnkvist** [comment]
Aha it's in a different repo. That would explain why I didn't find any existing ticket. Thank you for the update +1
