### ISSUE TITLE
Simple, test scrolling is WAY TO sensible and fast. 

### ISSUE THREAD

**Issue by Oblik-Design** [atom/atom#13557]
It is an horror show, to get portion to **copy / pace** . This is driving me mad, and there is not a single other software that works like this. Please fix it.

ATOM
![045d0b30-688b-11e6-8aef-c44bb024dc49](https://cloud.githubusercontent.com/assets/9968597/21723323/ff489450-d3fd-11e6-9db1-2dd0407ea907.gif)

OTHER ONES - SUBLIME
![febb009c-688a-11e6-879e-83f8f535592f](https://cloud.githubusercontent.com/assets/9968597/21723324/01354b32-d3fe-11e6-86f5-3f1fd996666a.gif)

**Comment by 50Wliu** [comment]
Please do not create duplicate issues.

**Comment by Oblik-Design** [comment]
please fix it ...
