### ISSUE TITLE
Incorrect File Path Displayed in Title Bar

### ISSUE THREAD

**Issue by sturadnidge** [atom/atom#13566]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Opening a file that does not belong to a project folder that has been added to the current session results in an incorrect file path being displayed on the title bar, making it look like the open file is actually part of the first project folder in the list.

### Steps to Reproduce

1. Open Atom on a macOS machine
2. Add some project folders if none exist
3. Using finder, open a file outside of any project folder currently added
4. Note that the file path displayed in the title bar points to the first project folder in the list, not the actual file location.

**Expected behavior:** Opening any file in Atom displays the correct path to the file, always.

**Actual behavior:** Opening a file that is not part of an 'added' project folder displays an incorrect path to the file in the title bar.

**Reproduces how often:** 100%

### Versions

Atom    : 1.12.7

Electron: 1.3.13

Chrome  : 52.0.2743.82

Node    : 6.5.0

### Additional Information

See screenshot - the  correct path to ISSUE_TEMPLATE.md is displayed in the status bar (\~/Desktop), but not in the title bar (\~/Projects/node-steam)
![image](https://cloud.githubusercontent.com/assets/901721/21746316/6b5e94f4-d594-11e6-98c1-1a4f319c84e0.png)

**Comment by 50Wliu** [comment]
This was fixed by https://github.com/atom/atom/pull/13475 and will be available in Atom 1.14.
