### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by reskwer** [atom/atom#13562]
God, how the Atom is extremely slow, constant mistakes with getting the pack list, I didn't know that github programmers hands of assholes grow...
![image](https://cloud.githubusercontent.com/assets/8849299/21737462/e584c8d6-d489-11e6-9c9d-ab5d5cb3d120.png)

**Comment by lee-dohm** [comment]
@reskwer I'm closing this for obvious reasons. It is also a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. Welcome to the ban list.
