### ISSUE TITLE
Duplicate search results when using Search in Directory

### ISSUE THREAD

**Issue by dominic-p** [atom/atom#13577]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is kind of an edge case. I have multiple projects added to the Tree View. A couple of them use the same final folder name (e.g. `C:\path\to\www` and `C:\another\path\www`). Furthermore, these are similar websites with similar directory structures. For example, I work on multiple WordPress sites that share some plugins in common.

When I use the "Search in Directory" function I get a path that looks like this: `www\public_html\wp-content\plugins\woocommerce`. However, since that path could be referring to multiple projects, I get duplicate search results.

### Steps to Reproduce

1. Add multiple projects to the Tree View with the same name for the final directory
2. Search inside one of the projects for a string that would occur in the same place in more than one project

**Expected behavior:** Return only the results from the project you selected to search within.

**Actual behavior:** Results from multiple projects are returned.

**Reproduces how often:** 100%

### Versions

Windows 10 1607
Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

I know it seems like kind of a corner case, but I can't tell you how frustrating it is to find a file, start editing it, and then try to understand why your changes aren't being reflected. Only later do you realize that you've been editing code for a completely different project. :)

Thanks for the great editor, btw.

**Comment by lee-dohm** [comment]
This issue was moved to atom/find-and-replace#846
