### ISSUE TITLE
Make a persistent shortcut to the atom executable

### ISSUE THREAD

**Issue by Busti** [atom/atom#13578]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Starting atom through an external program is not persistent since the install directory changes regularly.
Applications, such as WinSCP, that require an executable path to the text editor the user specifies, will only open the editor (atom.exe) until the next update.

### Steps to Reproduce

1. Link C:\Users\<username>\AppData\Local\atom\app-<version>\atom.exe in an external program.
![szjager 1](https://cloud.githubusercontent.com/assets/3575167/21787028/3a9d608c-d6c7-11e6-8a10-05be5ed10b0a.png)

2. Program starts atom as expected.
3. Update atom
4. Program won't start atom anymore.

**Expected behavior:** Atom should provide an executable file (link to such file) that can be refered to in other software.

**Actual behavior:** atom.exe folder changes regularly.

**Reproduces how often:** A couple times per month.

### Versions

All

### Additional Information

This error might be or might not be specific to Windows systems.

**Comment by damieng** [comment]
There is an atom proxy stub coming in the 1.14 release courtesy of the 1.51 version of Squirrel. 

We won't be using it just yet but it people want to link to the atom.exe proxy stub that is directly in the atom folder instead of in a version folder they certainly can do now.

**Comment by mickacz** [comment]
WinSCP 5.9.3 + Atom 1.14.0-beta0 x64

With this path, you can now edit and create new files. It works 100%

External editor:
C:\Users\ < user> \AppData\Local\atom\atom.exe --processStart !.!

![image](https://cloud.githubusercontent.com/assets/13012600/21905822/10bd272c-d909-11e6-80a5-621a56c81eac.png)

**Comment by damieng** [comment]
Good to know @mickacz - we're looking at moving all our shortcuts/OS integration to the new stub in a future update.
