### ISSUE TITLE
Sass illegal characters false-positive?

### ISSUE THREAD

**Issue by zslabs** [atom/atom#13582]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hi,
When writing a class in Sass like the following `.u-textRight\@medium` it's showing up as illegal within the inspector, causing the code highlighting to be a bit funky. I don't have any validation errors using this type of syntax and it works on the frontend well; for example you can write `<p class="u-textLeft@medium">Hello</p>`. Screen shot below:

<img width="1234" alt="screen shot 2017-01-10 at 11 05 52 am" src="https://cloud.githubusercontent.com/assets/1018402/21813715/24beba28-d725-11e6-9179-c9c3f4523782.png">

Here's some insight into the validity of classnames http://stackoverflow.com/a/6592488/1026742

### Steps to Reproduce

1. Within `.scss` file, write `.u-textRight\@medium`

**Expected behavior:** Same code highlighting

**Actual behavior:** Appears to have "illegal" class in Atom panel.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by arcticicestudio** [comment]
I think this should be moved to [atom/language-sass](https://github.com/atom/language-sass).
There are already the issues [#187](https://github.com/atom/language-sass/issues/187) and [#193](https://github.com/atom/language-sass/issues/193) which seem to be the same.

**Comment by 50Wliu** [comment]
Correct, this is atom/language-sass#187.

**Comment by zslabs** [comment]
@50Wliu thanks for mentioning that issue, subscribing there.
