### ISSUE TITLE
Upgrade from atom 1.12.9 to atom 1.13 , Atom can not open any project 

### ISSUE THREAD

**Issue by toplinuxsir** [atom/atom#13586]
Upgrade from atom 1.12.9 to atom 1.13, Atom can not open any project 
The Error Info :
   "<css input>:3:27: Unknown word"

CssSyntaxError
column
:
27
generated
:
(...)
input
:
Object
line
:
3
message
:
"<css input>:3:27: Unknown word"
name
:
"CssSyntaxError"
reason
:
"Unknown word"
source
:
"atom-text-editor {↵  font-size: 17px;↵  font-family: Input Mono;Fira Mono;Wenqunyi Bitmap Song;↵  line-height: 1.5;↵}"
stack
:
(...)
get stack
:
stack()
set stack
:
stack()
__proto__
:
Object

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by petrjaros** [comment]
Simple workaround: Delete/remame C:\Users\user\AppData\Roaming\Atom folder. (Your don't loose any settings doing this)

**Comment by toplinuxsir** [comment]
Thanks , It work !

**Comment by natady** [comment]
I deleted /Users/koyo120/Library/Application Support/Atom folder but it does not work for me. (macOS Sierra) What should I do anything else?

**Comment by 50Wliu** [comment]
@natady please open a new issue and completely fill out the issue template.  As this issue has been resolved, I'm closing it.

**Comment by shikelong** [comment]
#13631
