### ISSUE TITLE
Atom 1.13 indentation-guide width

### ISSUE THREAD

**Issue by idleberg** [atom/atom#13589]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

(I have previously submitted the [same issue](https://github.com/atom/base16-tomorrow-dark-theme) elsewhere, but since it seems to be independent from the theme in use, I'm posting it again) 

Since upgrading to 1.13, the indentation guides are displayed as a very thick line. For as far as I can remember, they were only 1px wide.

### Steps to Reproduce

1. Upgrade to 1.13
2. Activate `Show Invisibles`
3. Take a look

**Expected behavior:** Thin indentation guide

**Actual behavior:** Thick indentation guide

**Reproduces how often:** 100%

### Versions

```bash
$ atom --version
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.5
git 1.9.5
```

### Additional Information

**Atom 1.12.9:**

![atom-1 12 9](https://cloud.githubusercontent.com/assets/1504938/21847250/2a4d4be0-d7fb-11e6-8ffb-aeedd95a3ec4.jpg)

**Atom 1.13.0:**

![atom-1 13](https://cloud.githubusercontent.com/assets/1504938/21847260/3b119102-d7fb-11e6-8eab-255f4fbcfb3e.jpg)

Examining the indentation guide in the inspector, I noticed the following…

```css
.editor .indent-guide {
    display: inline-block;
    box-shadow: inset 10px 0;
}
```

…is overwriting this…

```css
atom-text-editor .indent-guide {
    display: inline-block;
    box-shadow: inset 1px 0;
}
```

**Comment by idleberg** [comment]
It turned out that I had the 10px box-shadow in my local `index.less`. I don't recall ever touching my style-sheet, but it clearly caused the issue.

**Comment by Ingramz** [comment]
@idleberg when using inspector, you can backtrack the source of certain style block by clicking on the `<style></style>` tags on the top right corner of the block. Where does the `.editor .indent-guide {` block point you?

**Comment by idleberg** [comment]
It turned out these were remainders in my `styles.less`. At first I wasn't sure where they came from, but now I'm sure I tried to reproduce a problem somebody posted on the Atom forum. All good, closing this!
