### ISSUE TITLE
OSX Sierra new tab bar

### ISSUE THREAD

**Issue by Sofianio** [atom/atom#13581]
This is a simple request, in OSX Sierra you can group windows in one window with multiple tabs.

I can drag an atom window to another atom window's tab-bar to have them both in one window
<img width="787" alt="screen shot 2017-01-10 at 14 58 37" src="https://cloud.githubusercontent.com/assets/14220889/21808835/56f986f6-d745-11e6-90ff-41ead221a64f.png">

But, it would be better if atom had an option that says like "open project in new tab" or "open new tab" or something like that

Thanks.

**Comment by blcarson** [comment]
It's also an issue when the "use custom title bar" option is checked under core settings.

**Comment by brentcas** [comment]
Wouldn't it also make sense for Sierra tabs to replace the current tabs implementation in Atom?

**Comment by blcarson** [comment]
Not really - the screenshot Sofianio posted is how I would expect it to work - multiple projects as primary "tabs" with open files as smaller subtabs within each project. The goal here being 1 atom window open but with multiple projects available.

**Comment by brentcas** [comment]
@blcarson That's definitely a reasonable approach. Something that might be worth considering is making it the job of the left-side panel to take care of navigating between projects in a single tab. This is how Sketch handles having multiple 'Pages' in a single file.

**Comment by blcarson** [comment]
Yep I'd be totally down with that.

**Comment by lee-dohm** [comment]
While this would definitely be useful for some workflows, it isn't something that we're going to have the time to get to anytime soon. Since we use the issues list as the maintainer team's backlog, I'm going to close this. We would, on the other hand, accept a well-written PR for this, so I'll label it `help-wanted` so that people who might be interested can take a stab at it.

Thanks for the suggestion!

**Comment by sn0wyfall** [comment]
@blcarson Is it a known issue that the custom title bar will mess with Sierra's tabs? Because they do for me.

**Comment by blcarson** [comment]
@sn0wyfall Yeah it's still an issue as of the last update.

**Comment by sn0wyfall** [comment]
@blcarson Is it a known issue? Do you know if it'll be fixed? Because that would be pretty cool

**Comment by blcarson** [comment]
@sn0wyfall Yes it's known, no idea if anyone will fix it I'm afraid.

**Comment by alekbarszczewski** [comment]
Guys, are you able to group atom windows in native mac os tabs? It was working for some time but since few days it does not group windows anymore for me :(.

**Comment by Sofianio** [comment]
It' still working for me.
also, now when i click new window it opens in a new tab! which is cool!
PS: your name needs more vowels ... just sayin'

**Comment by alekbarszczewski** [comment]
@Sofianio For me it works only when I click "File -> New window". However it does not work when I type `atom .` in terminal (to open atom in current directory) - it just opens separate window while before, if there was any atom window already opened it created new atom window in a tab. Any idea why this is happening?

**Comment by Sofianio** [comment]
i have no idea

**Comment by blcarson** [comment]
This works for me when I have the title bar preference set to "native" and the dock system preference for "prefer tabs when opening new documents" set to "always". Any other combination does not want to work, which sucks because the custom title bar is really slick 😞

**Comment by stratocode** [comment]
I just upgraded to 1.19.0 from 1.18.0.   On 1.18.0 when I launched atom from the terminal ("atom ."), it would open a new atom window in a tab.   Now (on 1.19.0), it just opens a whole new window.   Something must have changed between those two versions.   I much prefer it the old way.   Any idea how to change it back??

**Comment by jaredcwhite** [comment]
Yeah some kind of Atom update recently just killed my ability to use Sierra's window tabs. This *really* sucks. I don't think it's Atom's fault though...it looks like Electron disabled support at some point because of other issues they saw. But I never had any problem with Atom—worked great for me. If the Powers That Be working on Atom could nudge the Electron folks to bring back support, I'd definitely appreciate it. :)

**Comment by mifrej** [comment]
The Atom disobey global system preferences which is a bug. When I set "prefer tabs" to "Always" I expect app to obey the rule. It's not critical but it is a bug.
