### ISSUE TITLE
Curly bracket mismatch in JavaScript

### ISSUE THREAD

**Issue by josephrocca** [atom/atom#13590]
Sorry for the lack of extended testing. I figure it's better to post and see whether others get the same behaviour than to not post at all (but maybe I'm wrong!). In any case, I won't feel bad if this issue is closed immediately.

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Notice that the bracket matching is wrong:

![image](https://cloud.githubusercontent.com/assets/1167575/21850625/9dda6cd2-d85f-11e6-8dc4-f10e94c4d1d9.png)

It matches the last bracket with the bracket in the second last string. This is a general problem, and not specific to this particular code example.

### Steps to Reproduce

Paste this code in a `.js` file and look at put your cursor on the last curly bracket.
```javascript
  if(a === "{") {
    if(a === "{") {
      
    }
  }
```

**Reproduces how often:** 100%

### Versions

I have not added any extra packages or plugins. It's a clean install that I did one or two months ago.

Atom    : 1.12.5
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4

Ubuntu 16

**Comment by 50Wliu** [comment]
I believe this has been fixed in Atom 1.13.0.
