### ISSUE TITLE
Syntax Auto Detect changes behavior based on filename (not extension).

### ISSUE THREAD

**Issue by aniljava** [atom/atom#13594]
Atom fails to correctly auto detect the syntax if the script file without extension is named a certain way. Two files `mm`  and `t1` are detected with different syntax despite having same content, permissions and encoding.

The mm is opened with `Objective C++` mode whereas t1 is opened correctly with `python` syntax.

Tested with other names, the problem persists if the file is named `mm`. 

Expected behavior: Use `#!/usr/bin/env python` to map the syntax. 
Is there any special significance of `mm` like `.bashrc`  or `/etc/hosts` being special files.

    /root/Desktop/tests :: # file *
    mm: Python script, ASCII text executable
    t1: Python script, ASCII text executable

    /root/Desktop/tests :: # ls -l
    total 8
    -rwxr--r-- 1 root root 100 Jan 11 11:36 mm
    -rwxr--r-- 1 root root 100 Jan 11 11:36 t1

Content of both files:

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-
    
    import os
    import sys
    
    def main():
        pass
    
    
    
    main()

Environment

    Atom    : 1.12.8
    Electron: 1.3.13
    Chrome  : 52.0.2743.82
    Node    : 6.5.0

    Linux k32 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.1 LTS
    Release:	16.04
    Codename:	xenial

**Comment by 50Wliu** [comment]
Yes, `mm` is the extension for Objective-C++.
https://github.com/atom/language-objective-c/blob/master/grammars/objective-c%2B%2B.cson#L3

@Ingramz I would argue that the first line match should matter more than the filetype.  What do you think?

**Comment by Ingramz** [comment]
@50Wliu I believe the main issue here is that the whole filename is treated as a file type, however we probably want to only target something.mm files for objective-c++ (not sure about the case where a file is named `.mm`). Of course there are other cases where we are expecting the file type to be the whole filename itself, eg Makefile. There's an open issue for glob pattern support in one of the repositories to mend that.

I can probably live with first line matches being prioritized over file types if any grammar building on top of HTML gets the same first line match pattern included that HTML has (doctype), which should fix my main concern regarding this approach where a grammar such as HTML cripples the use of any grammar based on it. It would be wise to inspect other bundled first line matches for similar issues as well before transitioning back.

**Comment by Ingramz** [comment]
I put some thought into this. I don't think we are ready yet to swap first line match with file types.

The reasoning behind currently used model is simple, file types are all about conventional use of files. If file type is unknown (unsupported or unconventional use) or we have to choose between more than one competing file type, we can go "guessing". Some guesses are significantly better than others. If guessing does not work out for you, unconventional file type uses can always be manually added by the user to better improve the file type matching, yet unsupported ones can be added via a pull request.

We can however steadily work towards improving the current situation where some languages that could benefit from first line matches that don't have them (eg. XML), some which recognize poorly if first line match is considered before file type (supersets of HTML) and where some file types are detected too eagerly (like the case with `mm` we're having here). If we can raise the quality of those before flipping the priority in grammar scoring, we can have a much better end result compared to reverting to old behavior now and fixing all the issues later. In short I have a feeling that right now we break more than we fix by prioritizing first line matches.

**Comment by lee-dohm** [comment]
Thanks very much for the feedback! This has given us a lot of food for thought. I'll bring the information back to the maintainers and we'll use it to inform future decisions.
