### ISSUE TITLE
Atom 1.13 specifying font family weight breaks editor

### ISSUE THREAD

**Issue by maxpowa** [atom/atom#13593]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Specifying a weight in the "Font Family" editor setting breaks the editor, this is a regression from 1.12 as it worked fine there. This issue actually breaks all functionality of atom, trying to click any of the menu items will open the dev tools.

### Steps to Reproduce

1. Specify weight with font family option in config. `Source Code Pro:500`
2. Attempt to start atom

**Expected behavior:** Editor should use font family with specified weight

**Actual behavior:** Editor fails to load as it cannot parse the generated SCSS which cuts off the weight.

**Reproduces how often:** every time

### Versions

```
System Version: OS X 10.11.5 (15F34)
Kernel Version: Darwin 15.5.0

> atom --version
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
> apm --version
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.11.0
```

**Comment by damieng** [comment]
Specifying a weight in the font family box is not supported.  If you want to use a specific weight go into File > Settings and then add a block to your CSS like this;

```css
atom-text-editor {
  font-weight: 500;
}
```
