### ISSUE TITLE
Allow searching a string in installed packages information

### ISSUE THREAD

**Issue by mindrones** [atom/atom#13608]
*Problems*

- changing a setting/shortcut requires to find the installed package it's supposed to belong to (can be tricky at times, it's a bit time consuming), scroll down and find the term by eye;
- sometimes people [assume you know where to find a certain setting](https://github.com/richrace/highlight-selected/issues/73#issuecomment-104724559) and if not the case you have to search it on the web, which is time consuming;

*Proposal*

Allow searching terms in all of the installed packages by looking up:

- package settings' name and description (and maybe setting's allowed values?)
- package keybindings' command, selector and source 
- eventually, package name and description
- eventually, package READMEs

---
(on Atom 1.13.0 now)

**Comment by 50Wliu** [comment]
Please reopen this on the atom/settings-view repo.

**Comment by mindrones** [comment]
[Done](https://github.com/atom/settings-view/issues/899), sorry for the noise, thanks!
