### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by MandarSant** [atom/atom#13609]
after updating atom I getting following status on status bar what is it and what sould i do now
![capture1](https://cloud.githubusercontent.com/assets/20091634/21933533/cf3f17ce-d9cb-11e6-9f1e-c0a505301548.JPG)

**Comment by damieng** [comment]
This just means some plugins are using APIs that will be removed in a future update.

You will likely see some package updates over the next few days that as authors update their code and those will disappear.

**Comment by MandarSant** [comment]
@damieng  but do i have to perform manual operations to remove that status other than updating or it will be automaticaly removed?

**Comment by Ben3eeE** [comment]
@MandarSant If you click on that message you will open the deprecation-cop which will show you which packages are causing the deprecation. From here you can report issues about the deprecation to these packages. The message will automatically disappear once these deprecations have been fixed and the packages updated.
