### ISSUE TITLE
Missing libnode.dylib - OSX Sierra Crash on start

### ISSUE THREAD

**Issue by lfdmotta** [atom/atom#13619]
Hi,

Let me first thank you for the great job of making Atom, I was using it as my LaTeX editor, thus far the best.

Unfortunately, today Atom stopped working. It crashes on start. **Trying to run in Safe Mode results in the same crash.**

Here are the details:

The crash report indicates a dylib is missing. I was not able to find the libnode.dylib file inside the path indicated in the crash report and I could not locate it anywhere inside Atom.app. I don't understand the problem since I did not update macOS nor Atom after the last time I used Atom. Searching the web, it seems that this is a consistent issue for Atom in OSX for at least two years now, as users have being reporting this weird crash on start behavior caused by the missing lib for several OSX versions and Atom versions. In my case, Atom was working fine and I cannot identify what caused the app to stop working suddenly.

> Process:               Atom [23854]
> Path:                  /Applications/Atom.app/Contents/MacOS/Atom
> Identifier:            com.github.atom
> Version:               1.13.0 (1.13.0)
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           Atom [23854]
> User ID:               501
> 
> Date/Time:             2017-01-14 12:23:00.740 -0200
> OS Version:            Mac OS X 10.12.2 (16C67)
> Report Version:        12
> 
> [...]
>
> Crashed Thread:        0
> 
> Exception Type:        EXC_CRASH (SIGABRT)
> Exception Codes:       0x0000000000000000, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Termination Reason:    DYLD, [0x1] Library missing
>
> Application Specific Information:
> dyld: launch, loading dependent libraries
> 
> Dyld Error Message:
>   Library not loaded: @rpath/libnode.dylib
>   Referenced from: /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
>   Reason: image not found
>

**Comment by 50Wliu** [comment]
Does it crash every time, or occasionally?
Also, Atom updated recently, it perhaps could be a case of the auto-update process not finishing correctly.

**Comment by BohdanTkachenko** [comment]
I have the same issue - when running Atom, it just closes and not creating any logs. I tried to remove all Atom configs in my user's home directory, also tried to download and install latest Atom from the website.

**Comment by BohdanTkachenko** [comment]
Also tried 1.14.0-beta1 -- this one works

**Comment by lfdmotta** [comment]
@50Wliu It crashes every time.

I downloaded Atom 1.13.0, replaced the Atom.app and now it works fine.

**Comment by lee-dohm** [comment]
Thanks for the update @lfdmotta. Since this is now working for you, I'm going to close it. Let us know if you run into the problem again.
