### ISSUE TITLE
How can I set my environment variable in atom when executing commands

### ISSUE THREAD

**Issue by AhadCove** [atom/atom#13614]
I am trying to set my environment variables to

>     $env:DEBUG="*,-babel"

But I cant figure out where to use this setting in the Atom editor

**Comment by damieng** [comment]
There is no feature built-in or planned for Atom to do this although it should be trivially possible with a package.  An alternative option would be to open the dev tools, go into the console and enter;

```process.env.DEBUG="*,-babel"```
