### ISSUE TITLE
script/build cannot create windows installer [404 (Not Found)]

### ISSUE THREAD

**Issue by diegonc** [atom/atom#13622]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`script/build` cannot create windows installer because of a 404 HTTP error while downloading the RELEASES file for the x64 architecture.

### Steps to Reproduce

1. Run `script/build --create-windows-installer`
2. Wait

**Expected behavior:**

Installer is created successfuly.

**Actual behavior:**

The following messages are eventually printed:

```
Creating Windows Installer for D:\diego\PROGRAMACION\Src\atom\atom\out\Atom x64
Extracting signed executables failed:
Error: Failed with exit code: 4294967295
Output:
Attempting to sync URL as remote RELEASES folder
Trying to download RELEASES index from https://atom.io/api/updates-x64/RELEASES
Trying to download RELEASES index from https://atom.io/api/updates-x64/RELEASES
Trying to download RELEASES index from https://atom.io/api/updates-x64/RELEASES
Trying to download RELEASES index from https://atom.io/api/updates-x64/RELEASES
Failed to sync URL as GitHub repo: repos/api/updates-x64/releases was not found.
System.AggregateException: Se han producido uno o varios errores. ---> System.Net.Http.HttpRequestException: El c�digo de estado de la respuesta no indica un resultado correcto: 404 (Not Found).
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

**Reproduces how often:**
On every build

### Versions

Atom: master
Node:   v6.7.0
Npm:    v3.10.5
Python: v2.7.11
Microsoft Visual C++ Build Tools: Default install plus Windows 8.1 SDK
Windows 10 64-bits

### Additional Information

1. I'm adding the following pull requests:

    atom/atom#10881
    atom/first-mate#67

    But, I've successfully built Atom with those a few weeks ago.

2. The URL mentioned in the build output gives a 404 in the browser. ( https://atom.io/api/updates-x64/RELEASES )

**Comment by lee-dohm** [comment]
@ungb Can you reproduce this?

**Comment by diegonc** [comment]
> The URL mentioned in the build output gives a 404 in the browser. ( https://atom.io/api/updates-x64/RELEASES )

I tried again and the installer builds correctly. This URL is now returning a 200 status code; I don't know whether it's related but somehow it's fixed.

**Comment by lee-dohm** [comment]
Ok, I suspected this might be the case. Please let us know if the problem reoccurs and we'll be happy to reopen the issue.
