### ISSUE TITLE
n not build for 32 bit Linux  with node 7.2

### ISSUE THREAD

**Issue by lishoujun** [atom/atom#13623]
### Description

[Description of the issue]
I have this error:
Error: Atom does not build properly on node v7+. node v7.2.0 is installed.
### Steps to Reproduce

1. download ZIP from https://github.com/atom/atom
2. sudo apt install build-essential git libgnome-keyring-dev fakeroot rpm libx11-dev libxkbfile-dev
3. script/build

**Expected behavior:** [What you expect to happen]
build atom 
**Actual behavior:** [What actually happens]
Error: Atom does not build properly on node v7+. node v7.2.0 is installed.
**Reproduces how often:** [What percentage of the time does it reproduce?]
everytime
### Versions
debian sid 32 
nodejs v7.2.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
This is expected...please read the error message you get.
https://github.com/atom/atom/blob/96111f47e973dd737e68ecb0708f1a08f5711c0d/script/lib/verify-machine-requirements.js#L23

**Comment by lishoujun** [comment]
I built it with a  6.x nodejs from nvm
and I think this rule should be in https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md----Requirements
now :       Node.js 4.4.x or later (we recommend installing it via nvm)
suggest : Node.js 4.4.x - 6.x (we recommend installing it via nvm)

**Comment by 50Wliu** [comment]
I think the restriction can actually be removed now since apm has been updated.  I'll take a look tomorrow.

**Comment by lishoujun** [comment]
ok  thanks
