### ISSUE TITLE
Blurry text inside the editor on Windows with display scaling

### ISSUE THREAD

**Issue by DFelten** [atom/atom#13627]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The text inside the editor is blurry on my Thinkpad T440s with Windows 10. I'm using a display scaling of 125%. It's not blurry when starting Atom with "--force-device-scale-factor=1", but then of course the elements are too small. It seems there is a problem with the scaling from Windows and Atom.

On the attached file you can see a comparison. On the left there is the blurry font, on the right the correct without display scaling.
![compare](https://cloud.githubusercontent.com/assets/1169185/21962451/daae2760-db26-11e6-8a44-10a939418740.jpg)

### Steps to Reproduce

1. Change the display scaling of Windows (https://www.thurrott.com/windows/windows-10/4597/windows-10-feature-focus-display-scaling)
2. Start Atom
3. see the blurry font inside the text editor

**Expected behavior:** clear font

**Actual behavior:** blurry font

**Reproduces how often:** 100%

### Versions
1.13.0 and 1.14.0-beta0
Windows 10 Pro

**Comment by damieng** [comment]
Those screenshots both look incredibly blurry and pixelated to me :(

**Comment by DFelten** [comment]
Strange, maybe it's the image quality when uploading something here. On my screen it's only blurry when there is a display scaling. 

In the moment I'm working with atom with -force-device-scale-factor=1 and the Atom Material theme. With this theme it's possible to set up the size of the UI easily.

**Comment by 50Wliu** [comment]
This may improve when we upgrade to Electron 1.4.

**Comment by damieng** [comment]
Latest Windows 10 insider builds also have a brand new DPI scaling methodology we need to check out.

**Comment by DFelten** [comment]
With the latest beta (1.15.0-beta0) the scaling is better and not quite so blurred, but not as sharp as for example Sublime.
