### ISSUE TITLE
Atom does not run properly on the Ubuntu 16.10 (x86)

### ISSUE THREAD

**Issue by Petr-Lazecky** [atom/atom#13635]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Dear all,

I am trying to use Atom on 32 bit virtual machine running Ubuntu 16.10 as guest virtual machine OS (I am using latest version of VirtualBox 5.1.12 on Windows 10).

I have tried both options - using pre-compiled 32 bit binary package provided by webupd8.org and compiling binary within virtual machine myself. Both steps lead to the same result so I will describe symptoms for observed behavior when building 32-bit Atom locally as this may be more pristine state.

### Steps to Reproduce

1. I was able to successfully compile Atom on Ubuntu using `script/build --create-debian-package` command. DEB package is successfully created and build is clean with no errors. 
2. Installing Atom.deb - success, no issues
3. Atom --version
```
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Expected behavior:** I would expect editor to launch

**Actual behavior:** Atom editor is dark (black), nothing can be seen within text area. Title bar shows "Welcome Guide -- Atom" but whole text area is black and nothing can be seen. Moving mouse within the text area changes cursor pointer from time to time so it seems that pane boundaries within the text area are properly recognized but not properly rendered (everything is black as mentioned above). Attempt to close all tabs through menu option (File\Close Tab) does not solve the issue, while tabs are closed which can be observed by text changing within Atom's window Title bar, but whole text area continues to be black\dark.

**Reproduces how often:** Every time Atom is launched

## Versions

```
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

This is how Atom screen looks like:

![image](https://cloud.githubusercontent.com/assets/8009260/21987607/87f2e806-dc04-11e6-975e-8d956088c3c1.png)

**Comment by 50Wliu** [comment]
Can you try running `atom --disable-gpu` and see if that helps?

**Comment by Petr-Lazecky** [comment]
Hi Wliu,

thank you for tip and help. Yes, this switch helped, Atom starts correctly now.

Petr

**Comment by 50Wliu** [comment]
Ok.  Then I'm closing this as a problem with VirtualBox, specifically with Guest Additions.  If you want, you can take a look at https://github.com/atom/atom/issues/11574, which deals with different VirtualBox problems with the same solutions.
