### ISSUE TITLE
Atom uses cson very extensively, but there is no formal specification for cson

### ISSUE THREAD

**Issue by JonasT** [atom/atom#13630]
Atom appears to use the cson format very extensively. However, there appears to be no formal specification for cson available at all.

Given how prominently Atom uses this format, this is rather undesirable. Maybe the Atom develoeprs could convince the CSON maintainers that a formal specification would be important? (or maybe even help them out with it) This issue appears to have been brought up multiple times on the [CSON issues tracker](https://github.com/bevry/cson/issues) (most recently by myself), but so far there appears to be still no specification available or even any sort of publicly stated commitment to provide one in the near future.

**Comment by lee-dohm** [comment]
Thank you for your submission!

You are correct that Atom uses the CSON format extensively. But we use [our own implementation of the CSON format](https://github.com/atom/season), so whether or not there is a formal specification isn't of much importance to Atom itself. Additionally, if our implementation and the official formal one disagreed, I'm not sure that we would feel obligated to update our implementation unless it exposed a bug.

In any case, I'll mention it to the development team. Thanks again for reaching out.

**Comment by JonasT** [comment]
@lee-dohm so is there any chance your development team will produce a formal specification of the format Atom's implementation uses?

**Comment by lee-dohm** [comment]
It is quite unlikely that we will.
