### ISSUE TITLE
Update squirrel stays even though running latest version

### ISSUE THREAD

**Issue by Coysh** [atom/atom#13633]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The bottom-right 'squirrel' continues to show even when on the latest version.
"An update will be installed the next time Atom is relaunched" - I have relaunched

Not a major issue - but a bug nonetheless 

### Steps to Reproduce

N/A

### Versions

**OS: Windows 7**

**atom --version**
Atom    : 1.14.0-beta1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**apm --version**
apm  1.15.1
npm  3.10.5
node 4.4.5 ia32
python
git 2.8.2.windows.1
visual studio 2010

**Comment by dev169** [comment]
Yes, I'm seeing this too. Happens after dealing with https://github.com/atom/atom/issues/13607 and having to update to 1.14.0-beta1 with the .exe installer.

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/about](https://github.com/atom/about) repository if a bug doesn't already exist for it.  Thanks!

**Comment by Coysh** [comment]
atom/about#50
