### ISSUE TITLE
 Autocompletion eats return key presses while typing

### ISSUE THREAD

**Issue by JonasT** [atom/atom#13632]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Autocompletion sometimes eats return key presses for me while typing. This interferes with the typing of legitimate proper code in many languages. In C/C++ the impact is less serious because a line is *usually* terminated with a `;` (but midstatement line breaks are possible and sometimes used for formatting, so this could also lead to user frustrations). However, for languages where an identifier can regularly be at the end of the line, as for example in lua or when assigning one variable to another in Python, this is potentially very wrong and frustrating.

The autocompletion should be configured in a way that if the user doesn't actively interact (e.g. choose something out of the list with active key presses) it will never mess up what the user typed, unless it is most likely a proper useful macro (e.g. "pdb" in Python) which is intended to be expanded in special ways.
### Steps to Reproduce

1. Start typing some identifier/variable name you used before in the same file
2. The autocompletion should suggest it to you while you type the name. Don't press any cursor keys and don't actively interact with it in any way
3. Press return key to start a new line after typing the identifier

**Expected behavior:** Auto-complete popup closes, cursor ends up in new line

**Actual behavior:** Auto-complete popup closes, cursor does *not* end up in new line

**Reproduces how often:** 100% (every time)

### Versions

```
[jonas@falcon ~]$ atom --version
Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
[jonas@falcon ~]$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.3
[jonas@falcon ~]$ uname -a
Linux falcon 4.8.16-300.fc25.x86_64 #1 SMP Fri Jan 6 18:11:49 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[jonas@falcon ~]$
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
You're still on the wrong repo unfortunately @JonasT - this belongs on atom/autocomplete-plus.  Looks like it's already been raised in https://github.com/atom/autocomplete-plus/issues/490.
