### ISSUE TITLE
Window title is `untitled` when no files are open

### ISSUE THREAD

**Issue by adamreisnz** [atom/atom#13647]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The title of the window is `untitled` even when there is no new/untitled file open.

### Steps to Reproduce

1. Open a project folder
2. Ensure all file tabs are closed

**Expected behavior:**
The title of the window should show the location of the project folder, so that when you are viewing the window and the tree view happens to be scrolled down (moving the root folder out of view) you will still know what window you're looking at.

Are present, if you have multiple windows open, they will all say `untitled` which isn't very helpful. I'm pretty sure this has been introduced in one of the latest releases and that it didn't use to be like this.

**Actual behavior:**
The title of the window says `untitled`

**Reproduces how often:** 
100%

### Versions
Atom 1.14.0-dev-157e8e1
OS X 10.11.5

**Comment by lee-dohm** [comment]
I was able to reproduce the issue using Atom v1.14.0-beta3 on Mac OS X 10.12.3. Thanks for reporting this! (I had actually seen the bug before but hadn't gotten around to filing it :blush:)

**Comment by adamreisnz** [comment]
Cheers, I wasn't sure if it was a regression or just something that I only noticed recently!
