### ISSUE TITLE
computer crash after  editing wxpython GUI code on the Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by wzqxing** [atom/atom#13649]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

when I had installed wxpython in my computer,I try to edit a example program to check whether wxpython is correct installation.

So,I input the example program:

```
import wx
app = wx.App()
win = wx.Frame(None)
win.Show()
app.Mainloop

``` 

But,when I input the second line code `app = wx.`,Atom should display the function in wxpython.But my computer crash directly.The mouse keyboard and screen can not response. I can only cut off the power supply to restore the computer.

### Steps to Reproduce

1. install wxpython
2. create file,and input the code
3. the computer is crash

**Expected behavior:** normally work

**Actual behavior:** computer crash

**Reproduces how often:** every time

### Versions

```
apm --version

apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4
```

```
atom --version

Atom    : 1.10.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

```

**Comment by 50Wliu** [comment]
Two things:
1. This is most likely not caused by Atom as it does not have builtin functionality to work with wxpython.
2. The latest Atom version is currently 1.13.0.  Please update.
