### ISSUE TITLE
TextEditor's scrollPastEnd gets ignored

### ISSUE THREAD

**Issue by samu** [atom/atom#13660]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The `scrollPastEnd` option for a `TextEditor` is not respected.

### Steps to Reproduce

1. Install `git-diff-details` which makes use of this feature
2. Open a repo, create a diff that spans at least 5 lines
3. Place the cursor above the red area and scroll

**Expected behavior:**
Inline editor view does not scroll.

**Actual behavior:**
Inline editor view scrolls.

**Reproduces how often:**
100%

### Versions

1.14 Beta and lower

**Comment by lee-dohm** [comment]
Thanks for taking the time to contribute!

This appears to be an issue with the [git-diff-details package](https://atom.io/packages/git-diff-details) that you mention in your repro steps. You should follow up with the maintainers of that package. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
