### ISSUE TITLE
Error: Atom does not build properly on node v7+. node v7.4.0 is installed.

### ISSUE THREAD

**Issue by JPRuehmann** [atom/atom#13666]
if I try script/build
I get the following.
/home/ruehmann/atom/script/lib/verify-machine-requirements.js:23
    throw new Error(`Atom does not build properly on node v7+. node v${fullVersion} is installed.`)
    ^

Error: Atom does not build properly on node v7+. node v7.4.0 is installed.
    at verifyNode (/home/ruehmann/atom/script/lib/verify-machine-requirements.js:23:11)
    at module.exports (/home/ruehmann/atom/script/lib/verify-machine-requirements.js:10:3)
    at Object.<anonymous> (/home/ruehmann/atom/script/bootstrap:18:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Yes, that's because it doesn't build properly on Node 7+, as the error message states.

**Comment by JPRuehmann** [comment]
This is no answer.
How can I make it compile?
Thanks,

**Comment by 50Wliu** [comment]
Do not use Node 7+.

**Comment by JPRuehmann** [comment]
Am I here at an Windows Forum?
The only other jnode i can get to work is 4.* and that does the same
how can I make a workable jnode???
Thanks,

**Comment by 50Wliu** [comment]
The error message clearly states that you are using Node 7.4.0.  Make sure you are using Node 4, such as by looking at the output of `node --version`.

**Comment by JPRuehmann** [comment]
So I´ve found this sudo n 4.4.1
gets me a bit farther to the compilation.
Thanks for not pointing me in the directon ;-)

**Comment by adamreisnz** [comment]
@50Wliu not to beat a dead horse, but are there any plans for supporting builds on Node 7 (and future versions) in the near future, or are we going to have to keep a legacy node version installed just for building Atom?

**Comment by 50Wliu** [comment]
#13691

**Comment by adamreisnz** [comment]
Cheers thanks
