### ISSUE TITLE
Using the apm command when using Atom portable in a custom location

### ISSUE THREAD

**Issue by simonknittel** [atom/atom#13673]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It looks like it's currently not possible to use the `apm` command in while using Atom as portable version in a custom location (see step 2 and 3) (on Windows).

### Steps to Reproduce

1. Download `atom-windows.zip`
2. Create `.atom` in custom location like `C:\Users\username\portables\.atom`
3. Extract to custom location like `C:\Users\username\portables\Atom`
4. Enable the `apm` command via the environmental variables by adding `C:\Users\sknit\portables\Atom\resources\cli` to the users `Path` variable
5. Run `apm install` to install some package

**Expected behavior:** It installs to`C:\Users\username\portables\.atom\packages` (as defined in step 2)

**Actual behavior:** It tries to install to `C:\Users\username\.atom\packages`

**Reproduces how often:** 100%

### Versions

* **atom** 1.13.0
* **apm** 1.14.1

**Comment by lee-dohm** [comment]
This definitely sounds like a problem. We track Issues with apm in the https://github.com/atom/apm repository. Would you mind filing this again in that Issues list? Thanks for understanding :grinning:
