### ISSUE TITLE
Help > Search Issues menu item bugged

### ISSUE THREAD

**Issue by GiantCrocodile** [atom/atom#13677]
1. click on Help > Search Issues
2. link https://github.com/issues?q=+is%3Aissue+user%3Aatom is opened.

This link is not working for people who aren't logged in and thus should be replaced with link 
https://github.com/atom/atom/issues .

**Comment by 50Wliu** [comment]
The two links you have given are not equivalent.  The first searches through the entire Atom organization while the second only searches in atom/atom.

In addition, this is a duplicate of #7758 - feel free to subscribe there for updates.
