### ISSUE TITLE
Scope-aware expanding selection using Alt+Up (like in IntelliJ)

### ISSUE THREAD

**Issue by oyazik** [atom/atom#13674]
This would be a great feature to add to Atom. By pressing Alt+Up the selection expands gradually with each repeated Alt+Up. IntelliJ users will know what I'm talking about smile

For example:

```
function do(something) {
  var someVar = 'hi there';
  var someVar2 = 'hello';
}
```

Having the cursor blinking inside the word there and pressing Alt+Up repeatedly would select:

1. there
2. hi there
3. 'hi there'
4. var someVar = 'hi there';
5. everything inside the function block, i.e. the two rows declaring the vars
6. the function block including the { and }
7. the whole function declaration
8. ... you get the idea

Kind of hard to describe, but download the IntelliJ Community Edition and try it out. It is one of the single best features in IntelliJ, would love to see it in Atom.

I found this issue from another website and from another user who named joscarsson.

**Comment by perryprog** [comment]
Definitely would like to see this. Maybe a plugin?

**Comment by lee-dohm** [comment]
Hello @oyazik ... there is an Atom package that already provides this functionality, the [expand-selection package](https://atom.io/packages/expand-selection). You may want to check it out!
