### ISSUE TITLE
Can atom be used for commercial purpose

### ISSUE THREAD

**Issue by user-12345** [atom/atom#13689]
Hi there, My commercial activities may include things such as creating WordPress themes and plugins and creating software.

1) Can i use Atom for the commercial purpose stated above ?
2) Can i use Atom for the any commercial purpose ( i do not intend to sell Atom ) ?

Thank you.

**Comment by 50Wliu** [comment]
Hi there @user-12345, I noticed that you also created a Discuss topic on this (https://discuss.atom.io/t/can-atom-be-used-for-commercial-purpose/38593).  Since Discuss is better suited for these types of questions, and also so that we can unify discussion, I'm going to close this issue.
