### ISSUE TITLE
Beautify not installing

### ISSUE THREAD

**Issue by luisfellipe7** [atom/atom#13683]
When I try to install the beautify package it gives me this error, how to proceed so I can install it?

> atom-beautify@0.29.16 postinstall C:\Users\LUISFE~1\AppData\Local\Temp\apm-install-dir-117023-10192-96r0yb\node_modules\atom-beautify
> npm run build-options

C:\Users\LUISFE~1\AppData\Local\Temp\apm-install-dir-117023-10192-96r0yb
`-- (empty)

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
'C:\Users\Luis' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\LUISFE~1\AppData\Local\Temp\apm-install-dir-117023-10192-96r0yb\package.json'
npm WARN apm-install-dir-117023-10192-96r0yb No description
npm WARN apm-install-dir-117023-10192-96r0yb No repository field.
npm WARN apm-install-dir-117023-10192-96r0yb No README data
npm WARN apm-install-dir-117023-10192-96r0yb No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Luis Fellipe\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Luis Fellipe\\AppData\\Local\\atom\\app-1.13.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Luis Fellipe\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Luis Fellipe\\.atom\\.apmrc" "install" "C:\\Users\\LUISFE~1\\AppData\\Local\\Temp\\d-117023-10192-el7zcr\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.16 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.16 postinstall script 'npm run build-options'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\LUISFE~1\AppData\Local\Temp\apm-install-dir-117023-10192-96r0yb\npm-debug.log
npm ERR! code 1

**Comment by 50Wliu** [comment]
I believe this has been fixed in upcoming Atom versions.
