### ISSUE TITLE
Problem in syntax engine when `const` is function

### ISSUE THREAD

**Issue by tunnckoCore** [atom/atom#13690]
### Prerequisites

Using `atom -d` to have access to `Inspect element`.

### Description

There is a problem for styling the color of `const` when it is a function. It works when `var` or `let` are used.

### Steps to Reproduce

Will give you some code and screenshots to see the problem

```js
const foo = (options) => Promise.resolve(options))
let foo = (options) => Promise.resolve(options))
```

![2017-01-24-21 27 18_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/22263001/9dc7cfca-e27b-11e6-9680-4b891b318b87.png)
![2017-01-24-21 27 13_1280x1024_scrot](https://cloud.githubusercontent.com/assets/5038030/22263000/9dc1fcbc-e27b-11e6-9af6-f23f9328b8fa.png)

### Versions

running `atom --version`

```
Atom    : 1.13.0
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0
```

running `apm --version`

```
apm  1.15.2
npm  4.1.1
node 7.4.0 x64
python 3.6.0
git 2.11.0
```

Using ArchLinux as OS.

ref: https://github.com/atom-material/atom-material-syntax/pull/56#issuecomment-273538223

**Comment by 50Wliu** [comment]
Please uninstall your version of Atom and reinstall from https://atom.io.  You are running an unofficial distribution that uses mismatched components for which we offer no support.  For more information, you can read our unofficial distribution policy at https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md and subscribe to https://bugs.archlinux.org/task/50357 for updates.

Luckily for you, this is not a hard issue to diagnose - please reopen this on the [atom/language-javascript](https://github.com/atom/language-javascript) repository after you have installed an official version of Atom.  Thanks!
