### ISSUE TITLE
Odd behaviour as editor to a rebase

### ISSUE THREAD

**Issue by elliotcm** [atom/atom#13705]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Until recently[1], using `atom` as my `VISUAL` editor during an interactive rebase would open the `git-rebase-todo` temporary file in a new tab in Atom and allow me to perform changes before saving and closing.

Now, instead of waiting, it deletes each line in the file one by one, and closes it.  Performing commits this way are unchanged.

Using `atom --wait` resolves the issue but at the cost of startup time as it opens a new window rather than a new tab.

Using `atom --safe` has no effect.

`atom --clear-window-state` had no effect.

### Steps to Reproduce

1. Set `atom` as your `VISUAL`.
2. Perform a `git rebase -i` with or without `--root`.

**Expected behavior:**

A new tab opens in the same project as the directory I'm in containing `git-rebase-todo` and takes action only when I save and close the file.

**Actual behavior:**

`git rebase -i --root`
![rebase](https://cloud.githubusercontent.com/assets/109225/22371780/feadcb02-e490-11e6-83f0-b83adcc39a08.gif)

`git commit`
![commit](https://cloud.githubusercontent.com/assets/109225/22371894/dd6645ea-e491-11e6-8cd3-06f63d5b2ec2.gif)

**Reproduces how often:**

100% of time with an interactive rebase
0% of the time with a commit

### Versions
```
macOS Sierra 10.12.2 (16C67)
```

```
Atom    : 1.13.1 (most recent at time of writing)
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.11.0
```

### Additional Information

Using `atom --wait` as my `VISUAL` does not have the same problem, however it is less than ideal because opening a new window rather than a new tab is subject to atom's relatively slow startup time.

[1] I don't know how recently this started happening as it has been a while since I did an interactive rebase.

**Comment by lee-dohm** [comment]
The `--wait` option is necessary for things like the rebase command because that is what enables the synchronization of the Atom process with the terminal process. If you don't supply `--wait` then the terminal process will launch Atom and then continue on and not wait for you to edit and save the `git-rebase-todo` temporary file. This is the entire purpose of the `--wait` option.

As far as `--wait` opening a tab instead of a window, there is an open issue for that already https://github.com/atom/atom/issues/10244. Since the only actionable part of this is duplicated by that issue, I'm going to close this as duplicate. You may want to subscribe to that other issue for updates.

Thanks for contributing and for such a well-written bug report!

**Comment by elliotcm** [comment]
Hi @lee-dohm, do you have any thoughts on why it works fine for commits without --wait but not for rebases, and was working fine for rebases not long ago?

**Comment by peterbabic** [comment]
+1 I would love this feature as well

**Comment by lee-dohm** [comment]
@peterbabic Atom already has a `--wait` parameter. We aren't going to be enabling this scenario without `--wait`.
