### ISSUE TITLE
Autocomplete duplication

### ISSUE THREAD

**Issue by vsemozhetbyt** [atom/atom#13703]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I've just loaded the last beta portable version for the first Atom try. The autocompletion test causes unexpected behavior: the object name is doubled before the property (the same in the safe mode / with factory defaults). Sorry, if I get something wrong.

### Steps to Reproduce
![autocomplete](https://cloud.githubusercontent.com/assets/10393198/22356694/0679d81c-e43c-11e6-9e36-f71d5703816d.gif)

**Expected behavior:** [What you expect to happen]
```js
console.log();
```

**Actual behavior:** [What actually happens]
```js
console.console.log();
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
Persistently.

### Versions
Atom    : 1.14.0-beta3 (atom-x64-windows.zip)
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS: Windows 7 x64

**Comment by 50Wliu** [comment]
This is expected: you're using a feature called "snippets" (denoted by the green tab marker on the left).  Those expand when you autocomplete them, as opposed to normal autocompletion.

**Comment by vsemozhetbyt** [comment]
Well, it seems to be too confusing for a default behavior(

**Comment by 50Wliu** [comment]
Yeah, I agree it's pretty confusing to new users.  If you have any suggestions for how to improve the UX though, please create new issues on the atom/autocomplete-plus repo.  We'd be glad to hear about them :).

**Comment by vsemozhetbyt** [comment]
Unfortunately, I know very little about Atom UX. I've also tried VSC the same day, this autocompletion works fine there. Maybe atom/autocomplete-snippets should not be toggled on by default?

**Comment by vsemozhetbyt** [comment]
It seems atom/autocomplete-snippets even disables common autocompletion, what is even more confusing to new users. Compare

atom/autocomplete-snippets is off:

![off](https://cloud.githubusercontent.com/assets/10393198/22387199/282df8f6-e4e3-11e6-9d5e-7857006a1a62.gif)


atom/autocomplete-snippets is on:

![on](https://cloud.githubusercontent.com/assets/10393198/22387203/2d568866-e4e3-11e6-9cf9-97265c603bd1.gif)
