### ISSUE TITLE
atom do not reload file on sshfs when modified by external program

### ISSUE THREAD

**Issue by wiso** [atom/atom#13717]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

atom does not reload a file which is modified by an external program when the file is on a folder mounter by sshfs. This is very common with command like `svn up`, which means that you are overwriting all the changes made by other contributors.

I don't know if there are packages which does this, but I think this should be the default behaviour of any editor, at least atom should warn you.

### Steps to Reproduce

1. sshfs remote_host:remote_path localpath
2. atom localpath/myfile
3. cd localpath/myfile
4. svn up

**Expected behavior:** 

atom should reload the file after svn up

### Versions
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

emacs does

**Comment by cooniur** [comment]
+1

**Comment by dexter369** [comment]
Same issue, if I open a log file from server and then re-download and open that file from server using Filezilla, atom shows the contents of old file instead of updated file. Hard to imagine why it is this way or not fixed yet , if bug.

**Comment by Edmundod** [comment]
+1

**Comment by ourway** [comment]
You need to turn of cache on sshfs.

**Comment by erikedhagen** [comment]
Did anyone find a way to resolve this? Or an alternative way of working with an sshfs share?

**Comment by valkalon** [comment]
same issue here

**Comment by flaschbier** [comment]
still the case in Atom 1.40.1 x64 on Ubuntu 18.04 (installed from snap): files changed externally are not automatically reloaded by Atom. Dangerous behaviour. Should be fixed asap.

**Comment by allefeld** [comment]
Same here, sorted a file open in Atom from the bash prompt, expected Atom to alert me to the change and to offer to either save or reload.

**Comment by kovvalsky** [comment]
Atom 1.40.1 on Ubuntu 16.04, the same issue.
Other program edited the file but in Atom there is no indication that the file has changed and the old version is shown.
