### ISSUE TITLE
atom-environment.js is error when starting Atom via xrdp

### ISSUE THREAD

**Issue by boyoyon8** [atom/atom#13715]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I using atom on linux mint OS via xrdp.

atom-environment.js is error when atom starting:
```log
Uncaught TypeError: Cannot read property 'addWarning' of undefined
 /usr/share/atom/resources/app.asar/src/atom-environment.js:335 
```
but after, that I can use atom without problems.

### Steps to Reproduce

1. install atom
2. run it

**Actual behavior:** [What actually happens]
Developper Tool open in atom and show the error message.
![starting-error](https://cloud.githubusercontent.com/assets/2116356/22451320/f2e2cb24-e7b0-11e6-9f77-28523e0f51a2.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

```console
$ apm -v
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.12
$ atom --version
Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

OS : Linux Mint 18 MATE 64bit
xrdp : 0.6.1
vnc : TigerVNC 1.7.80

### Additional Information

Error does not occur with..

* do not use xrdp
* or super user command (via xrdp ok)
```console
$ su atom
```

**Comment by 50Wliu** [comment]
Can you give some information about `xrdp` and what it is please?  In addition, how did you install Atom?

**Comment by boyoyon8** [comment]
### xrdp info
xrdp is open source remote desktop protocol server.
here to detail -> http://www.xrdp.org/

### Atom install step 
1. download atom-amd64.deb from Atom.io -> https://atom.io/
2. ```sudo dpkg -i atom-amd64.deb```

**Comment by lee-dohm** [comment]
Thanks for reaching out!

While we understand that this is a valid and useful use case. This isn't something that we're going to have the resources to investigate and correct by ourselves anytime soon. Since the maintainer team isn't going to be able to work on it and we're trying to use the open issues list as our backlog, I'm going to close this. 

We would accept a well-written PR for this functionality, so I've labeled this as `help-wanted`. Hopefully someone from the community will be able to help with a solution.

**Comment by boyoyon8** [comment]
thank's for your action!
