### ISSUE TITLE
Some part of selected lines seen unselected if dragged vertically after selecting text

### ISSUE THREAD

**Issue by citrix123** [atom/atom#13711]
### Setup
OS : ubuntu 16.04
GPU : Intel Haswell
### Description

[Description of the issue]
Some section of the selected lines , seen unselected if scrolled Vertically back and forth.
### Steps to Reproduce

1. Open a big file [HTML File in my case]
2. Select some Lines [~10 Lines]
3. Using Track pad scroll it vertically.
4. Observe Some section won't seen selected. [Screenshot attached]

**Expected behavior:** [What you expect to happen]
All lines should be selected either scrolled back and forth vertically

**Actual behavior:** [What actually happens]
Some part of lines gets unslected.
**Reproduces how often:** [What percentage of the time does it reproduce?]
It reproduce 10 out of 9 time on vertically scrolling after selecting lines
### Versions

# apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4

# atom --version
Atom    : 1.12.1
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0

Please let me know if any other information needed.
Also i would feel great if i can be in some part of contribution. :)

![atomissue](https://cloud.githubusercontent.com/assets/8206658/22406707/d21f275e-e67d-11e6-881c-88ad214596a6.png)

**Comment by lee-dohm** [comment]
Thank you for contributing!

We require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests. You specifically omitted an important part of the issue template, namely the part about whether this reproduces in Safe Mode, followed all applicable steps in the debugging guide (which also suggests to update to the latest version), whether you've searched for similar issues, etc. These are common steps that resolve or shed light on a lot of problems and reduce the overhead of maintaining the issue tracker. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. Please open a new issue and fill out the template for us.

Thanks for understanding and meeting us half way :grinning:

**Comment by citrix123** [comment]
Thanks @lee-dohm for your quick reply .
Well i seen on windows this issue is not observed. I guess it is observed with Linux only . 
I will file a new issue by filling issue template .

**Comment by lee-dohm** [comment]
Thank you @citrix123 :bow:
