### ISSUE TITLE
Github markdown for the world

### ISSUE THREAD

**Issue by franciscop** [atom/atom#13726]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I expect the syntax highlighter either to ignore the text, to let the user choose a language or make a smart decision. Right now, if I try to edit a text in Spanish I get this (they are all valid words in Spanish):

![odd](https://cloud.githubusercontent.com/assets/2801252/22533843/a58fa20c-e8f0-11e6-8851-8b82bfda70de.png)

### Steps to Reproduce

1. Create a new document and use "Github Markdown" syntax highlighting.
2. Write some text in Spanish and see how Atom highlights valid words as wrong.
3. Doubt your skills in your native language. Start to doubt everything you believe is true. Conclude that it's probably not me and I should ask for help in Atom's Github.

**Expected behavior:** there are many options that would be better:
- No syntax highlighting. English is just one more language and it wouldn't be reasonable to expect that people around the world only write text in English.
- Make a smart choice. I am sure there are many evaluation techniques to find out the current language, and the language-checker could be based on this. [Example of package](https://github.com/FGRibreau/node-language-detect). However, this would have to be complemented with.
- Allow the user to choose a language. It could be a sub-menu in the bottom-right next to the syntax highlight, but that would probably require a big overhaul. I am **not** asking to remove UTF-8, please don't change that as it's the best from JS world (previous PHP developer here).

**Actual behavior:** forces you to write in English if you don't want to be overwhelmed with red warnings.

**Reproduces how often:** 100%

### Versions

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
OS: Ubuntu 16.04

## Notes

Japanese language is correctly(?) ignored:

![jap](https://cloud.githubusercontent.com/assets/2801252/22534228/e850ae9a-e8f2-11e6-8466-eb3a1f054dfd.png)

**Comment by 50Wliu** [comment]
Two things.
1. This should be on the atom/spell-check repo, not here.
2. You're running on a very outdated version of Atom - I believe the latest version, 1.13.1, supports multilingual spell-checking.
