### ISSUE TITLE
Atom goes black when moved to another monitor

### ISSUE THREAD

**Issue by ebrian** [atom/atom#13737]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Screen goes black when moved off monitor which Atom was opened on. Sometimes if "Open in New Window" causes the window to automatically appear on a different monitor, then it is fine. But moving a screen originating from one monitor always causes it to go black when moved to another.

![img_20170203_133837](https://cloud.githubusercontent.com/assets/4989650/22605678/927c1822-ea16-11e6-9645-05aa80981626.jpg)

### Steps to Reproduce

1. Open Atom
2. Right click file and go to "Open in New Window"
3. Drag screen to other monitor.

**Expected behavior:** Screen looks normal.

**Actual behavior:** Screen is black.

**Reproduces how often:** 100%

### Versions

Atom 1.13.1
Xubuntu 14.04.5 LTS kernel 4.4.0-57-generic nvidia drivers
8 monitors, 4 GeForce GTS 550 Ti

**Comment by 50Wliu** [comment]
> Atom 1.0.19

You are on a version of Atom that is more than a year and a half old.  Please update to the latest version of Atom, currently 1.13.1.  If this still occurs, then open a new issue.  Thanks!

**Comment by ebrian** [comment]
Upgraded to 1.13.1. Same issue.

**Comment by ebrian** [comment]
A workaround is moving the main window to the monitor that I want a new window on, opening a new file on that monitor, then moving the main window back to the original monitor.

**Comment by damieng** [comment]
Do you also get this if you do the same thing with Chrome?

**Comment by ebrian** [comment]
Actually, I did. To fix it, I turned off "Hardware Acceleration" in the Chrome settings. Does Atom have a "Hardware Acceleration" option like Chrome?

**Comment by ebrian** [comment]
Looks like `atom --disable-gpu` fixes it.

**Comment by 50Wliu** [comment]
Cool, thanks for the update @ebrian.

**Comment by ebrian** [comment]
@50Wliu Hopefully somebody finds it useful. I'm sure I'm not the only one with multiple GPUs around here. I've also experienced this issue (the Chrome issue) on a few systems, all different hardware. The only thing in common was > 1 GPUs running Linux using proprietary NVIDIA drivers.

Not really sure who is responsible for this bug then. I guess it's either the Chrome engine guys, Xorg guys, or NVIDIA driver guys.

**Comment by damieng** [comment]
Yeah if it happens in Chrome there's a good chance it happens in Atom - and
other Electron based apps as they use the Chromium fork of Chrome to render
the UI etc.

Are you able to run any 3D games across monitors like that? It's possible
it's a limitation in DirectX or the graphics drivers. I would imagine down
at that level this is a horrible problem to try and solve.
