### ISSUE TITLE
rpm installation of atom in centos7 causes errors for some packages

### ISSUE THREAD

**Issue by DanBuchan** [atom/atom#13733]
On centos 7 with Atom 1.13.0x64 the following warning is thrown when the autocomplete-python package first attempts to autocomplete.

```
/bin/sh: module: line 1: syntax error: unexpected end of file
/bin/sh: error importing function definition for `BASH_FUNC_module'
```

### Steps to Reproduce

1. Install Centos7
2. Install atom with the 1.13.0 rpm
1. Install autocomplete-python package
2. Close Atom
3. Open Atom
4. Open python file
5. Start typing something that might trigger autocomplete

**Expected behavior:**
autocomplete dialogue appears, no warnings are thrown

**Actual behavior:**
no dialogue appears the warning/error is thrown

As far as I can tell this is an issue with the atom rpm install for fedora/centos.

After running
```
rpm -Uvh atom.x84_64.rpm
```
I can now find 2 copies of the atom executable one at `/bin/atom` and one at `/usr/share/atom/atom`. I would typically expect one of those to be a symlink to the other but that is not the case here. The desktop icon that the rpm adds to Gnome is pointed at the executable `/usr/share/atom/atom `

If I run atom from the command line with `/usr/share/atom/atom` I get the following error
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```
and the `BASH_FUNC_module` error for autocomplete-python persists. So you obviously see this same behaviour with the desktop icon.

If I run atom with `/bin/atom` there are no errors and everything works as expected.

### Current Solutions

Either

1. Run atom from the commandline allowing it to resolve to `/bin/atom`
2. As I'm using gnome I changed the atom desktop icon to always call `/bin/atom` is called. I made the following edits to `/usr/share/applications/atom.desktop`
```
Exec=/bin/atom %F
Icon=/usr/share/atom/atom.png
```
and then log out and back in to Gnome

**Comment by shermdog** [comment]
Also seen on Fedora 25.  Some additional details on closed module ticket autocomplete-python/autocomplete-python#275

**Comment by AndreaGriffiths11** [comment]
@ungb is this due to dependencies?

**Comment by DanBuchan** [comment]
Strikes me that the runtime dependencies are satisfied given that `/bin/atom` runs without error. Some manner of relative path problem seems likely.

**Comment by ungb** [comment]
I do see the error

```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

come up but I am unable to repro the issue where autocomplete doesn't work.   Is there any thing else you can provide that might be different about your system?  where is atom mapped on your terminal if you run `which atom`.  

see gif of my repro on Centos 7.
![error](https://cloud.githubusercontent.com/assets/5624870/22910654/392485e6-f210-11e6-8169-16a41f69bac1.gif)

**Comment by DanBuchan** [comment]
`which atom`
returns
`bin/atom`

Here is the behaviour when launched from `/usr/share/atom/atom`
![atom_autocomplete_error](https://cloud.githubusercontent.com/assets/1756584/22924898/cb12031e-f29e-11e6-8f3e-e36ba6f80f7b.gif)

**Comment by ungb** [comment]
I am still unable to repro your issue on centos

This is what I see when I follow your steps(NOTE my Centos VM is completely new install of Centos 7.3 64-bit):
![python](https://cloud.githubusercontent.com/assets/5624870/23044893/16d89da8-f457-11e6-8957-8ba0c55fe915.gif)

**Comment by NatalieWolfe** [comment]
I get this error any time I try to install dependencies on Fedora 25 with Atom 1.15.0. [Here is a compressed webm screen capture](https://github.com/atom/atom/files/870525/screencast.zip) showing the error. To reproduce this error on Fedora:

1) Install a package that requires a dependency (e.g. linter)
2) Click install in the blue popup asking about dependencies.
3) See error.

After this has happened once, every time you start Atom again you will get the blue popup asking you to install dependencies again and the error will happen once more.

**Comment by haghighi-ahmad** [comment]
Check this:
#https://github.com/autocomplete-python/autocomplete-python/issues/275#issuecomment-310929013
