### ISSUE TITLE
adjacent .atom folder not recongnized with portable zip distribution.

### ISSUE THREAD

**Issue by cengizhan** [atom/atom#13730]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

new portable mode that was introduced with 1.14beta0 got broken with later betas

### Steps to Reproduce

1. download [https://github.com/atom/atom/releases/download/v1.14.0-beta3/atom-x64-windows.zip](https://github.com/atom/atom/releases/download/v1.14.0-beta3/atom-x64-windows.zip)
2. extract to a folder and create a .atom folder adjacent to **atom.exe** file
3. start and made some changes, install packages etc.

**Expected behavior:**
atom should user this adjacent **.atom** folder for packages

**Actual behavior:**
atom uses .atom folder from user profile folder not adjacent **.atom** folder.

**Reproduces how often:**
tried in two computers. same result

### Versions
1.14.0-beta3

### Additional Information
this new portable mode was working with 1.14.0-beta0

**Comment by damieng** [comment]
"extract to a folder and create a .atom folder adjacent to atom.exe file" is incorrect.

The .atom folder has to be one level above - adjacent to the *folder* that contains atom.exe.

I just tested this in 1.14-beta3 and it works fine.

**Comment by thebigmunch** [comment]
> "extract to a folder and create a .atom folder adjacent to atom.exe file" is incorrect.
> 
> The .atom folder has to be one level above - adjacent to the folder that contains atom.exe.
> 
> I just tested this in 1.14-beta3 and it works fine.

Sorry this is a bit late, but this seems to be counter-intuitive and inconsistent with the way other portable apps do this. Moreover, putting the .atom directory inside the atom directory (adjacent to atom.exe) worked up through beta2. Windows users get a packaged directory and expect everything to be contained within that directory, else you're just making the .atom directory a little closer to the atom directory, not making it self-contained.

**Comment by damieng** [comment]
If it was inside the Atom folder then the entire configuration would easily get lost when upgrading the version of Atom.

If you absolutely desire it goes in the same folder you can follow the instructions at https://github.com/atom/atom/pull/8442#issuecomment-210478131

**Comment by thebigmunch** [comment]
I was already aware of ways to work around this. But working around it is not the same as having Atom be portable. The way it is now is simply not portable as expected nor is the difference documented anywhere easily accessible to most users.

I understand there may be some limitations in the auto updater as currently implemented, but other apps behave in the way the OP and I suggest. Sublime Text, which I'm sure many Atom users used prior (or still), works this way as one example.

If this is something the Atom developers are interested in looking into or discussing further, I can open a separate issue. If not, I'll just have to be disappointed that there won't be a proper portable version of Atom.

**Comment by damieng** [comment]
I'm sorry you feel that somehow this makes it not a 'proper portable' install but in all ways it is.

There is nothing stopping you from creating an Atom folder that has the .atom config folder and a program folder containing Atom.exe in it. In that scenario you have to click one more time to launch atom.exe but then you don't need to create a batch file. 

Putting them together in the same folder is a fundamentally bad idea. It's not just the auto-updater anyone attempting to manually update would very easily wipe out their atom config if not careful. It will happen, that kind of layout is unusual and error-prone and we'll err on not losing a users data.

**Comment by JayXon** [comment]
I find it very weird that you have to put .atom folder one level up. It's common practice for portable apps to store their config files in the same directory as the main exe on Windows. I think it's very unlikely that someone will delete their atom config by accident, if they know nothing about portable apps they should be using the installer version anyway.
