### ISSUE TITLE
Classes and ids autocomplete

### ISSUE THREAD

**Issue by scooterman751** [atom/atom#13744]
Atom should include a feature in which it also includes classes and ids ( that are already named ) in autocomplete. This would be useful for me using CSS since I am a beginner to coding. Thanks! 

![image](https://cloud.githubusercontent.com/assets/22735586/22622878/ade46d44-eb15-11e6-8953-5f233015bd42.png)
![image](https://cloud.githubusercontent.com/assets/22735586/22622886/da197918-eb15-11e6-9697-d4938c2d560a.png)

**Comment by 50Wliu** [comment]
This belongs on the atom/autocomplete-css repo: please file it there instead, and completely fill out the issue template.
