### ISSUE TITLE
The Reopen Projects menu is empty when atom is opened without a project

### ISSUE THREAD

**Issue by ungb** [atom/atom#13758]
### Prerequisites

* [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x]  Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [x]  Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Unexpected restart causes Atom to lose project state

### Steps to Reproduce

1. Open Atom, go to settings -> core and unselect  `Reopen Previous Windows On Start`
2. Close Atom and open Atom from spotlight
3. Go to content menu and try to open recent projects.

**Expected behavior:** [What you expect to happen]
It has recent projects
**Actual behavior:** [What actually happens]
It's empty,  when you open a project, it gets populated. 

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

No Project loaded:
![image](https://cloud.githubusercontent.com/assets/5624870/22668453/a47be014-ec75-11e6-990e-e43baf81b55b.png)

After opening a project:
![image](https://cloud.githubusercontent.com/assets/5624870/22668474/b306971e-ec75-11e6-9e57-4eff8eef9ad9.png)

### Versions

```
atom --version
Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm --version
apm  1.14.1
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.10.1
```
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ungb** [comment]
@50Wliu Saw this issue in https://github.com/atom/atom/issues/13757

**Comment by ungb** [comment]
This list is now populated when Atom is open in empty state, but if I open when Atom is in empty state,  we run into data-loss issue: https://github.com/atom/atom/issues/13873.

**Comment by Ben3eeE** [comment]
@ungb That is a good point. If we release this without a fix for https://github.com/atom/atom/issues/13873 we have more ways to run into the data-loss issue.

**Comment by ungb** [comment]
@damieng, this is going out in beta and not stable, correct?

**Comment by damieng** [comment]
It's only on master right now. Can merge it to beta or stable branches for the next hotfix if you think it's required. Given nobody else reported it and there is a data loss scenario you mentioned I'd probably hold off on hotfixing.
