### ISSUE TITLE
Unable to save a CPU Profile

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#13767]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

A security error is produced when attempting to collect a CPU Profile through the developer tools in Atom.

### Steps to Reproduce

1. Launch Atom in your local atom repository
2. Press <kbd>Alt+Cmd+I</kbd> to open the Developer Tools
3. Click the Profiles tab in the Developer Tools
1. Ensure "Record JavaScript CPU Profile" is selected
1. Click Start
1. Do a couple random things in the editor
1. Click Stop
1. Observe that a SecurityError regarding temporary storage is displayed
1. Click the Save link next to the new profile record
1. Save to `~/Downloads`
1. Get info on the new `*.cpuprofile` file

**Expected behavior:** The `cpuprofile` file to be longer than zero bytes

**Actual behavior:** The `cpuprofile` file is always zero bytes

### Versions

```
Atom    : 1.15.0-dev-ae9d949ee
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

I also reproduced this using v1.13.1 and v1.14.0-beta4.

### Additional Information

<img width="1292" alt="screen shot 2017-02-07 at 10 28 03 am" src="https://cloud.githubusercontent.com/assets/1038121/22705953/6466eeee-ed22-11e6-8f08-d3e607e69a0b.png">

**Comment by lee-dohm** [comment]
@ungb Can you also reproduce this?

**Comment by ungb** [comment]
I was able to repro this issue on 1.13.1
I see the following error when clicking stop with repro steps above.
```
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError
```

**Comment by lee-dohm** [comment]
Thanks very much for the quick repro @ungb!

**Comment by BinaryMuse** [comment]
Reproable on 1.15.0-dev-7aa87d7 as well. The CPU profile works, but the saved file is zero bytes.

**Comment by Stanzilla** [comment]
Issue persists on 1.16beta0 and also includes not being able to save TimelineRawData.json

**Comment by Daniel15** [comment]
I'm still seeing this on 1.16.0
