### ISSUE TITLE
Opening a new window switches workspace and raises first window (Ubuntu)

### ISSUE THREAD

**Issue by schigum** [atom/atom#13766]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When opening a second (new) atom window on a different workspace, the first opened window gets focused for a short moment before the new window opens.
First of all this raises the first window (if e.g. minimized) but also switches the workspace to the workspace where the first window is positioned.
I have reproduced this with Ubuntu 14.04 and Ubuntu 16.10, opening a new window with e.g.
`atom --safe --clear-window-state -n .`

### Steps to Reproduce

1. Open the first window on a given workspace (workspace A) and minimize the atom window.
2. Switch workspace to an other workspace (workspace B).
3. Open a new atom window.

**Expected behavior:** 
A new atom window opening on the workspace B.
The first window on workspace A being still minimized.

**Actual behavior:**
The workspace switches to workspace A and the first window is no longer minimized.

**Reproduces how often:**
Every time so far.

### Versions
Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Linux  : 4.4.0-62-generic Ubuntu 14.04 with Unity 7.2.6
and
Linux  : 4.8.0-37-generic  Ubuntu 16.10 with Unity 7.5.0

### Additional Information

It is probably the issue mentioned in #13364, but since it is closed and mentions two seemingly unrelated issues I opted for opening this topic.

**Comment by AndreaGriffiths11** [comment]
@ungb Could you please reproduce this?

**Comment by ungb** [comment]
I can repro this issue.  We'll add this to the queue.  @schacon, thanks for the repro steps!  Do you know if this use to work?

**Comment by schigum** [comment]
Assuming that the question is directed at me, sorry, but this is the first version I've used.
So I don't know when this issue started.

**Comment by dhimmel** [comment]
@schigum, thanks for reporting this issue. It's been driving me crazy!

The behavior I expect is when opening a new window with `atom -n .`, the window should appear on the active workspace where you entered it into the terminal.

@ungb, I'm currently using Atom 1.12.7 on Ubuntu 16.10. In my prior version of Atom (I forget exactly what version that was), this problem did not exist. The new windows would open in the expected (active) workspace.

**Comment by dhimmel** [comment]
Just upgraded my atom and the issue persists :cry:

Here's the output when I run `atom --version`:

```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by ungb** [comment]
I've saw a few issues similar to this.  Looks related to https://github.com/atom/atom/issues/11610, which is also related to a electron bug.  see https://github.com/electron/electron/issues/5362.  I'm going to close this out as dup.    Please subscribe there for updates on this issue.
