### ISSUE TITLE
[Enhancement Requests] Package Sets/Lists

### ISSUE THREAD

**Issue by uchuugaka** [atom/atom#13763]
[Enhancement Requests] Package Sets/Lists

It strikes me as painful and tedious with ALL editors like Atom, VSCode, Sublime, etc... that it is so hard to produce and share curated, reproducible sets of packages or total configurations.

The ability to do this, and make it simple to export, share, save and sync would be a boon to users on multiple machines as well as organizations or teams all trying to create a common platform to work from. 

Bonus points if these can be saved to Github in some fashion :)

**Comment by AndreaGriffiths11** [comment]
Thanks for reaching out!

This has been a common request and there is [a large discussion of various strategies and community packages on the official Atom message board](https://discuss.atom.io/t/syncing-settings-packages-between-machines/1385). You may want to take a look at that discussion for options. Thanks for the feedback and your interest in Atom.
