### ISSUE TITLE
Atom keeps trying to wrap long lines on markdown file causing text to blink

### ISSUE THREAD

**Issue by diegor2** [atom/atom#13769]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I open an specific file (described below) with an specific windows size (see screencap) atom will try to accommodate the text by wrapping the long lines, then revert it and try again,resulting in the text alternating between this too states in a loop. The bottom half of the text will show and disappear while the top is being rearranged.

### Steps to Reproduce

1. Open this file on atom https://github.com/docker-library/wordpress/blob/d8e5577dcc7096d2b694dda433e2b5c7c4561a82/README.md
2. If the text is still, resize the window until it reproduces the bug.

**Expected behavior:** 
The text should be rendered and stay still until the window is resized.

**Actual behavior:** 
The text will "blink" between these three states.
![bug](https://cloud.githubusercontent.com/assets/921798/22718325/e6cf5998-ed86-11e6-864b-f93cbe79ad14.gif)

**Reproduces how often:** 
100%

### Versions

Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by AndreaGriffiths11** [comment]
I was able to reproduce this using Atom v1.14.0 on Mac OS X 10.12.3.

**Comment by diegor2** [comment]
Original report was on Mac OSX 10.12
Also reproducible on Windows 8 (Version 6.3.9600)

![bug](https://cloud.githubusercontent.com/assets/921798/22827917/0e3628ba-ef79-11e6-9c98-e5eaa6a584b6.gif)

**Comment by ianrosedev** [comment]
I just submitted [this](https://github.com/atom/atom/issues/13845) issue for the same problem with React/JSX. My pure JS and HTML work just fine. I thought that it was a React issue, so it's interesting that Markdown is causing the same effect.
