### ISSUE TITLE
Atom stops and cpu is 100% with some kind of file

### ISSUE THREAD

**Issue by thiagowiezbicki** [atom/atom#13772]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom stops running and the CPU is 100% opening javascript source: http://pastebin.com/dJ9Dsu4M

### Steps to Reproduce

1. Copy the source code from http://pastebin.com/dJ9Dsu4M and save as a js file
2. Open the downloaded file

**Expected behavior:** Opening and editing the file normally

**Actual behavior:** Atom editor breaks and CPU frequency is 100%

**Reproduces how often:** 100%

### Versions

1.12.6

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Confirmed on Atom 1.15.0-dev-ae6a7a0.

**Comment by tylerancell** [comment]
Having the same issue with 1.14.0

Trying to open a minified javascript file causes the editor to freeze.

![atom](https://cloud.githubusercontent.com/assets/3847779/22776882/a4d512d8-ee6e-11e6-9982-63f6fcc51fa5.jpg)

**Comment by GreenSunBear** [comment]
Same issue with 1.14.0

**Comment by 50Wliu** [comment]
Upon reinvestigating the file it appears that the root cause is #979 because of the extremely long line in the middle of the file.

**Comment by thiagowiezbicki** [comment]
This is a old bug since 2013.    I can't open minified JS, CSS, etc files with Atom.

Does anybody will correct this bug?

**Comment by tylerancell** [comment]
@50Wliu That issue was closed over a year ago.  Until recently (last month or so), Atom has been able to open files with long lines with no problems for me - I've sent the same JS files to others that also use Atom (1.14), and they can open them with no problems which is very confusing.

**Comment by 50Wliu** [comment]
#979 is not closed, just locked due to the amount of unhelpful comments we received.
The ability of Atom to open long files is dependent on each individual computer (more memory, etc).

I will look into whether the memory cost of tokenizing JavaScript files has increased in Atom 1.14.0, and if so, I'll file a different issue for that on the atom/language-javascript repository.

**Comment by tylerancell** [comment]
@50Wliu Definitely not trying to be unhelpful, just trying to figure out why it suddenly is unable to open the same files it was able to open previously.

I've added a quick screen of processor/memory, I feel like they shouldn't be the cause.

![perf](https://cloud.githubusercontent.com/assets/3847779/22800000/29828064-eec5-11e6-9780-f62daafa12cc.png)

**Comment by thiagowiezbicki** [comment]
@50Wliu @tylerancell 

I installed here the 1.14 and when trying to open  http://pastebin.com/dJ9Dsu4M   file    or jquery.min,js angular.min.js ,   bootstrap.css.min           the same problem occurs, therefore it isn't possible edit these kind of files on Atom editor.

Another editors as notepad++ and sublime text   this problem don't occurs.
