### ISSUE TITLE
[Beta 1.14.0] APM or github packages and Portable mode

### ISSUE THREAD

**Issue by TigersWay** [atom/atom#13770]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode => **Issue about APM**
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/ => **Issue about APM**
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages => **Issue about APM**

### Description
Trying to run APM in portable mode on Windows cannot be done, at least simply!

### Steps to Reproduce

1. Neither Atom nor APM are on the "PATH" and should be run on their respective folders
2. APM install <githubpackage> is able to install that github package but in the "classic" .atom folder: C:\Users\myself\.atom

**Expected behavior:** [What you expect to happen]
- Being able to run APM from Atom folder
- github package installed in the .atom folder alongside Atom.exe folder

**Actual behavior:** [What actually happens]
- Need to call resources\app\apm\bin\apm
- github package installed in %USERPROFILE%\.atom

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
atom --version
```
Atom    : 1.14.0-beta4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
apm --version
```
apm  1.15.3
npm  3.10.5
node 4.4.5 ia32
python 3.5.2
git 2.10.1.windows.1
visual studio
```

### Additional Information
None

**Comment by damieng** [comment]
Our portable mode is not intended to be used externally from atom itself using apm directly. If you wish to use the apm command line you will need to set ATOM_HOME first to point to where the .atom folder is.

https://github.com/atom/apm/issues/678 has the details.

**Comment by TigersWay** [comment]
Maybe a little word in your documentation page http://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode-for-windows would be good then :-)

Thanks
