### ISSUE TITLE
find-next-selected(Ctrl-F3) command work after initial calling find(Ctrl-f) command

### ISSUE THREAD

**Issue by Si7ius** [atom/atom#13775]
### Description of problem

I opened some file with Atom text editor. After that I tried to find word that cursor is standing in using `Ctrl-F3`. But it didn't work. I call find window (`Ctrl-f`) and closed it. After this operation I could use `Ctrl-F3` command freely.

* [ ] `find-next-selected` command should work at start although `find` command initially called

**Comment by 50Wliu** [comment]
@Si7ius Please reopen this on the atom/find-and-replace package and completely fill out the issue template.  Thanks!
