### ISSUE TITLE
 enhancement : msi installer should install system wide and not a system wide installer

### ISSUE THREAD

**Issue by swirly** [atom/atom#13789]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

A MSI installer as been created for Atom. But it's not an installer for Atom. It's an installer for the Installer ! After installation, you don't have Atom in c:\Programs but an Installer of Atom and atom.exe still lives in personnal directory

### Steps to Reproduce

install with msiexec 

**Expected behavior:** 

having atom.exe living in c:\Programs\atom\

**Actual behavior:** 

An atom installer lives in C:\Programs and atom.exe lives in user personnal directory. Why is it so crucial for us ?  We are a high shcool and we teach code to our students. We have 1200 students and are low on budget for server storage space. 

Every student has an allocation of approximately 300M for personnal space, and another 200M for sharing space. That's all we can do.

And... atom installation is more than 300M in size ! It's useless because those 300M could perfectly be stored in C:\Program\atom\ and shared for all the users of the computer.

**Reproduces how often:** 

100%

### Versions

1.14.1 on windows 7 64bits

### Additional Information

I've made some test so far, with copying brutally the content of a personnal atom setup in the system Programs directory, it seems to work for non priviledged users. The program files should live in system, and only customization should live in personnal data

**Comment by gluons** [comment]
I have similar issue. I've used Aomt 64 MSI installer but I did't see Atom icon everywhere after it finish.
No icon on desktop. No icon on start menu. No atom in `AppData`. No atom in `Program Files`.

I can't find it everywhere but Add/Remove programs. Can only uninstall it. 😕

**Comment by swirly** [comment]
gluons, it kinda works ... it justs install an atom installer in c:\Programs

Without any icon or shortcut.

**Comment by damieng** [comment]
This is intentional and by-design.  A shared copy of Atom is not supported.

**Comment by swirly** [comment]
damieng, shared copy is not necessary (computer in a school are not running multiple user at once).

But having a machine install is mandatory. In secure environment, pupils can not have an executable in their own personnal folder or any shared data folder for security reason. Plus, even if they should, the space overhead would be unusable

Here in France, we are begin to massively teach computer science. Atom would be perfect for an editor, but actually, it cannot be used because of the installation method.

A machine install is really mandatory. Plus, it works ! I've just put all the file from a personnal folder in the %PROGRAMS% folder, and there be it, for a single user, it works flawlessly !

The design intention is perfect for developpers having the keys of his desktop, but that's not the only use case.

**Comment by damieng** [comment]
If you want to deploy a single copy to machines I would suggest unpacking the zip file and adding an icon to atom.exe to the all users\Start menu location.

The packaging system we use today - Squirrel - does not support a machine-wide installation and we do not have the resources to develop one given our other priorities.
