### ISSUE TITLE
Linux 32bit Source Build Fails Installation

### ISSUE THREAD

**Issue by progkix** [atom/atom#13788]
I've just built 1.14.0 & 1.15.0-beta0 32bit Linux DEBs, RPMs and GZs on Fedora 25. Builds were all successful.

Trying to install both fails with the foloowing messages:

rpm -Uvh /strg/ftp/ibnd/Atom-LnxX32-1.15.0b0.rpm
error: Failed dependencies:
	libXss.so.1()(64bit) is needed by atom-beta-1.15.0.beta0-0.1.fc25.i686

rpm -Uvh /strg/ftp/ibnd/Atom-LnxX32-1.14.0.rpm
error: Failed dependencies:
	libXss.so.1()(64bit) is needed by atom-1.14.0-0.1.fc25.i686

**Comment by ungb** [comment]
Can you try to run the `script/build --install` should install Atom after building?   
(see https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#scriptbuild-options).  

We currently only have builds for 64 bit on linux for rpm builds.  We would happily accept a pr that makes the rpm package spec compatible on every architecture.

**Comment by progkix** [comment]
I'm sure it will fail as well.

About a month ago, between 1.14.0-beta3 and 1.14.0-beta4, the file "resources/linux/redhat/atom.spec.in" was changed to require the 64bit version of libXss.so.1.

This effectively prevents any 32bit RPMs from being built.

/cc @as-cii

**Comment by progkix** [comment]
I've looked over some of the code briefly and i think a possible solution is to provide both a 32bit and a 64bit version of the resources/linux/redhat/atom.spec.in" file. Say something like atom32.spec.in and atom64.spec.in.

The atom32.spec.in would have "Requires: lsb-core-noarch, libXss.so.1
The atom64.spec.in would have "Requires: lsb-core-noarch, libXss.so.1()(64bit)"

Then the create-rpm-package.js script could be modified to check process.arch for 32 vs 64 bit and set the value appropriately - see the line below that would need to be replicated and ajusted for the proper spec.in file.

const rpmPackageSpecsTemplate = fs.readFileSync(path.join(CONFIG.repositoryRootPath, 'resources', 'linux', 'redhat', 'atom.spec.in'))

This is right off the top of my head and with no knowledge at all of the inner working of the build scripts.

**Comment by progkix** [comment]
I just build and successfully installed the latest versions (1.14.2 and 1.15.0-beta2) on Fedora 25 32bit from the source archive.

I modified the resources/linux/redhat/atom.spec.in file as follows:

Replaced this line:

Requires: lsb-core-noarch, libXss.so.1()(64bit)

With this:

%ifarch i386 i486 i586 i686
Requires: lsb-core-noarch, libXss.so.1
%else
Requires: lsb-core-noarch, libXss.so.1()(64bit)
%endif

%cc @50Wliu @ungb @as-cii

**Comment by ungb** [comment]
Thanks @progkix!  We ran into a similar issue when trying to [fix compatibility for different distros](https://github.com/atom/atom/pull/13536) as this occurs during build time.  I do believe since we are building on a x64 bit machine for releases, this should be fine.  

Any chance you can create a PR for this change?   I want to test the builds that are generated from Travis to make sure nothing breaks here.  

Thanks,

Bryant Ung

**Comment by progkix** [comment]
I'll see if I can go through the procedure tomorrow and get a pull request in place

**Comment by progkix** [comment]
Well being a newbie at this, I'm not really sure how to go about putting the request together and sending it in. I'm going to need to do some research on how to do that.

**Comment by ungb** [comment]
I've created PR  https://github.com/atom/atom/pull/13835 with your change.  

I believe what you need to do is fork the project Atom.  Create a branch, make your changes and create a PR of your change back to the main repo from your forked repo.  I created the PR for this change, but if you ever would like to submit a PR in the future,  these steps should work.

**Comment by nelson6e65** [comment]
I'm having the same issue in 1.14.3:

```sh
sudo dnf install ./atom-1.14.3.i686.rpm 
Error: nothing provides libXss.so.1()(64bit) needed by atom-1.14.3-0.1.fc24.i686
```
:disappointed:

**Comment by ungb** [comment]
I was able to verify that this doesn't affect the builds on 64-bit, I merged the pr https://github.com/atom/atom/pull/13835.  it's currently in master.
