### ISSUE TITLE
Atom icon doesn't override pinned icon in Windows 10 taskbar

### ISSUE THREAD

**Issue by mbladel** [atom/atom#13784]
Windows 10, started happening in 1.14.1: if the atom launcher is pinned to the taskbar, when the program launches it creates another icon that doesn't override it. It's not that big a problem but when shortcutting with <kbd>Windows key</kbd> + <kbd>#</kbd> (number of the application on the taskbar), it will open a new window instead on focusing on the one you were working on.

**Comment by isherwood** [comment]
I'm on 1.4.0 ia32 (no opdate offered) and the problem occurs.

**Comment by MaherFa** [comment]
And the old pinned loses its icon and shows windows' default blank white icon.  

Im on windows 10 64

**Comment by isherwood** [comment]
I don't see that, MaherFa. The two icons are identical.

**Comment by MaherFa** [comment]
Strange.. I'll  try to reproduce later.

**Comment by Duncank** [comment]
Happens here as well, Windows 10 64. The old icon seems to lose its icon, but sometimes it suddenly returns. Opening Atom will open a new instance in the task bar as well. I usually unpin the old icon and pin the new instance to fix it.

**Comment by MaherFa** [comment]
@Duncank exactly what happened with me. But the icon part seems inconsistent for some reason.

**Comment by JulianBerger** [comment]
Same issue with 1.14.2 x64
![atomm_icon](https://cloud.githubusercontent.com/assets/3339615/22975954/e7dd736c-f388-11e6-8819-6f0f491b55a3.JPG)

**Comment by isherwood** [comment]
Just to clarify the behavior I see: 

When I open Atom from a pinned icon, a second identical icon appears at the bottom/end of the taskbar. Now if I unpin the original, it disappears, and if I then pin the second icon, a new pinned icon appears that's not related to the active Atom window. Clicking the pinned icon results in a new Atom instance. 

I've still seen no disappearance or variation in icon style.

**Comment by mbladel** [comment]
Still here on 1.14.3.

![image](https://cloud.githubusercontent.com/assets/25681369/23131648/11e323cc-f78b-11e6-9840-8b26ccc36f58.png)

**Comment by mbladel** [comment]
Problem solved as of version 1.14.4

**Comment by fmauNeko** [comment]
Still doing it for me : [Video](https://caracal.dissidence.ovh/SentimentalConventionalCoelacanth)

**Comment by isherwood** [comment]
Still a problem on 1.14.4.

**Comment by Nickman87** [comment]
Same here. Unpinning the old icon and pinning the new again instantly makes a new icon next to the active one.

**Comment by obrousseau** [comment]
Confirmed as happening on 1.16.0.

Double icons (one pinned, one for the active window). They would normally be merged into one icon only.

**Comment by DrynnBavis** [comment]
Has anyone found a fix to this yet?
