### ISSUE TITLE
macOS: Custom Title Bar makes native tabs look ugly

### ISSUE THREAD

**Issue by Alaneor** [atom/atom#13791]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When the "Use Custom Title Bar" option is enabled on macOS, the system tabs look ugly - they seem to be transparent and overlap with the window's contents (ie. Atom's tabs).

### Steps to Reproduce

1. Start Atom with "Use Custom Title Bar" option enabled (*Preferences -> Core -> Use Custom Title Bar*)
2. Show macOS native tabs if not already visible (View -> Show Tab Bar)
3. Despair

**Expected behavior:** The native tab bar should not overlap with the window's contents and should probably not be transparent. Ideally, the tab bar would match the title bar's colour.

**Actual behavior:** The tab bar is displayed **over** the window's contents and seems to be transparent

**Reproduces how often:** 100%, with any theme selected

### Versions

Atom 1.14
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.11.1

### Additional Information

An obligatory screenshot:

![macos - broken native tab bar](https://cloud.githubusercontent.com/assets/3058150/22838121/ed589344-efc3-11e6-87d5-5212a2915ffe.png)

**Comment by AndreaGriffiths11** [comment]
Thank you for your submission!

We're aware that some native functionality is either disabled or won't function properly with the
"Use Custom Title Bar" feature enabled. This is a decision that individuals will have to make for
themselves, whether the themable title bar is more important to them or these native features. To
my understanding the native features that do not work or don't work properly are the proxy icon and
the native tab bar.

This isn't something that we're going to investigate a fix for. If someone from the community wanted
to submit a well-crafted PR for it, we would definitely review it. So I'm going to label this
`help-wanted` and close it.

Thanks again!

**Comment by simurai** [comment]
The "Show Tab Bar" menu item got [removed](https://github.com/electron/electron/pull/7415) in Electron. So once Atom updates to a newer Electron version that menu item shouldn't show up anymore. Although there is still [talk](https://github.com/electron/electron/issues/6124) in adding that feature back. So we'll see.

Otherwise, yeah, choosing to "Use Custom Title Bar" removes some of the native features. I don't think it's possible to change the text and border color of the native tabs to match the theme. So it would become unusable for dark themes.
