### ISSUE TITLE
Installation requirements addition / Compilation on Raspberry Pi 3 / Raspbian Jessie

### ISSUE THREAD

**Issue by jrie** [atom/atom#13792]
Hello,

Im currently trying to compile Atom on an Raspberry / arm architecture.

Its working fine, using the installation instruction, just one more thing:
I noticed there is one more requirement to be added which was not installed previously -
libxkb*** - which does the include "X11/extensions/xkbrules.h"

Its inside keyboard-layout-manager.cc @ 5:37

Perhaps this should become added to the note of requirements.

If I encounter any other problem, I report it here. But for now, all seems to be compiling smoothly.

Kind regards on behalf of an arm user.

**Comment by jrie** [comment]
Actually doenst seem to work, I fixed some minor hickup, but in the end, Atom starts with the error:
"/usr/share/atom/atom %F" could not be executed (along those lines)

Compilation and installation worked, after adding "arm" to common.js in "electron-packager/common.js"

and following:
sudo mkdir /usr/share/applications
sudo chown pi SAME_FOLDER

and 

sudo mkdir /usr/local/share/atom
sudo chown SAME_FOLDER

in addtion it was required to chown:
/usr/local/bin
to "pi" user

As there alltogether where no writing permissions.

Compilation was fine so, just took a while.

**Comment by damieng** [comment]
Atom is not supported on ARM - some users are experimenting and reporting their results on https://github.com/atom/atom/issues/7822

**Comment by curiousercreative** [comment]
@jrie we've had some luck with with this fork. Give it a whirl, tested on a couple of ARM devices running Debian: https://github.com/hypersad/atom
