### ISSUE TITLE
apm outdated returning undefined when seti-syntax is installed

### ISSUE THREAD

**Issue by eswat2** [atom/atom#13790]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

apm outdated returns undefined

### Steps to Reproduce

1. run "apm outdated" on the commandline
2. returns undefined
3. run "apm list"
4. shows what appears to be a proper list of packages

**Expected behavior:** return JSON of outdated packages

**Actual behavior:** returns undefined

**Reproduces how often:** 100%

### Versions

$ atom --version; apm --version
Atom    : 1.14.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.2.1

### Additional Information

noticed that the Updates in Settings were failing and tracked it to the apm call

<img width="792" alt="screen shot 2017-02-10 at 9 51 52 am" src="https://cloud.githubusercontent.com/assets/334293/22837967/b81dd122-ef77-11e6-92ef-c8ea0d4baac6.png">

**Comment by eswat2** [comment]
this just started happening this morning after i updated 2 packages from Settings...

**Comment by eswat2** [comment]
Here are the packages i have installed

```
$ apm list
Built-in Atom Packages (89)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.4.0
├── base16-tomorrow-light-theme@1.4.0
├── one-dark-ui@1.9.1
├── one-light-ui@1.9.1
├── one-dark-syntax@1.6.0
├── one-light-syntax@1.6.0
├── solarized-dark-syntax@1.1.1
├── solarized-light-syntax@1.1.1
├── about@1.7.2
├── archive-view@0.62.2
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.14.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.34.2
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.0
├── background-tips@0.26.1
├── bookmarks@0.43.4
├── bracket-matcher@0.85.2
├── command-palette@0.39.2
├── deprecation-cop@0.56.2
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.40.2
├── find-and-replace@0.206.1
├── fuzzy-finder@1.4.1
├── git-diff@1.2.0
├── go-to-line@0.31.2
├── grammar-selector@0.48.2
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.1
├── link@0.31.2
├── markdown-preview@0.159.6
├── metrics@1.1.3
├── notifications@0.66.1
├── open-on-github@1.2.1
├── package-generator@1.0.2
├── settings-view@0.246.0
├── snippets@1.0.5
├── spell-check@0.70.2
├── status-bar@1.7.0
├── styleguide@0.48.0
├── symbols-view@0.114.0
├── tabs@0.104.1
├── timecop@0.33.2
├── tree-view@0.213.1
├── update-package-dependencies@0.10.0
├── welcome@0.36.0
├── whitespace@0.36.1
├── wrap-guide@0.39.0
├── language-c@0.54.1
├── language-clojure@0.22.1
├── language-coffee-script@0.48.2
├── language-csharp@0.14.0
├── language-css@0.41.0
├── language-gfm@0.88.0
├── language-git@0.19.0
├── language-go@0.43.1
├── language-html@0.47.1
├── language-hyperlink@0.16.1
├── language-java@0.25.0
├── language-javascript@0.125.1
├── language-json@0.18.3
├── language-less@0.30.0
├── language-make@0.22.3
├── language-mustache@0.13.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.3
├── language-property-list@0.9.0
├── language-python@0.45.1
├── language-ruby@0.70.4
├── language-ruby-on-rails@0.25.1
├── language-sass@0.57.1
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.2
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.15
└── language-yaml@0.27.2

Community Packages (32) /Users/rhess/.atom/packages
├── angularjs@0.4.0
├── atom-material-syntax@1.0.2
├── atom-material-syntax-dark@0.2.7
├── atom-material-ui@1.3.9
├── atom-typescript@10.1.13
├── autocomplete-js-import@1.4.0
├── brogrammer-syntax@1.0.0
├── color-gutter@0.4.1
├── editorconfig@2.2.0
├── file-icons@2.0.15
├── fonts@2.0.0
├── gotham-syntax@0.2.0
├── highlight-column@0.5.2
├── highlight-line@0.12.0
├── language-ejs@0.4.0
├── language-sweetjs@0.2.0
├── lines@0.13.1
├── linter@1.11.21
├── linter-eslint@8.1.0
├── merge-conflicts@1.4.4
├── minimap@4.26.8
├── minimap-pigments@0.2.2
├── pep-ui@0.0.5
├── pigments@0.39.0
├── react@0.16.2
├── seti-icons@1.3.4
├── seti-ui@1.6.1
├── tabs-to-spaces@1.0.3
├── tree-ignore@0.6.2
├── tron-legacy@0.5.0
├── tron-theme@0.3.2
└── zentabs@0.8.8

Git Packages (1) /Users/rhess/.atom/packages
└── seti-syntax@1.1.2 (jesseweed/seti-syntax#fe9b3566)


```

**Comment by eswat2** [comment]
RESOLVED:  i removed the seti-syntax package and it's now checking for updates properly...

**Comment by eswat2** [comment]
```
$ apm outdated
Package Updates Available (0)
└── (empty)

```

**Comment by eswat2** [comment]
i'll leave this open for a bit just in case someone else sees this issue.  Feel free to close it if that's not the right approach...

**Comment by sirschuyler** [comment]
thank you @eswat2 … had the same issue and this solved it for me as well
for others… command to uninstall
run "apm uninstall seti-syntax"

**Comment by bdjurkan** [comment]
Thank you @eswat2 !
I had the same issue and this solved it for me!

**Comment by hleinders** [comment]
Same here (mac OS sierra) and same solution also. I've blamed the 1.14.1 update for this at first, but luckily I've found this issue, thx!

**Comment by AndreaGriffiths11** [comment]
Thanks for contributing!

We are going to wait and see what the author of the seti-syntax package says.

**Comment by MatrixV01** [comment]
Thanks for figuring this one out so quickly. Hopefully this gets resolved. I need my Seti.

**Comment by 50Wliu** [comment]
This issue should technically belong on atom/apm, but given the amount of traction it's gathered, I think moving it at this point would be unwise.

I wonder why one package has the potential to completely cripple the upgrade process for _all_ packages.

**Comment by joaufi** [comment]
[atom/apm #620](https://github.com/atom/apm/issues/620) is the issue thread on apm for this same problem.

**Comment by 50Wliu** [comment]
No, atom/apm#620 was opened long before this happened and unfortunately got hijacked.

**Comment by TheMushrr00m** [comment]
The same issue on Arch Linux and Atom 1.16.0-dev-02a1010a7 x64 builded from source and i solved from the same way. Thanks.

**Comment by 6stringbeliever** [comment]
I had this same issue without seti-syntax installed. I did have clean-dark-blue-syntax (also a git package) installed and removing that fixed the problem.

**Comment by jacobmischka** [comment]
@50Wliu It sure seems to be the same bug, so I wouldn't really say it was hijacked.

**Comment by 50Wliu** [comment]
@jacobmischka Nope, it was open long before this seti-syntax issue occurred 🙂.  The only similarity is that the error message is the same (which does _not_ mean it has the same underlying cause).

At any rate, the next version of seti-syntax should fix this (https://github.com/jesseweed/seti-syntax/pull/146).  We should still however investigate why package updates failed, and fix the `undefined` error message.

**Comment by david-wieczorek** [comment]
Same issue, removing seti-syntax work for me 👍

**Comment by Krysisx** [comment]
Hi, it does not work for me. I removed only `seti-ui` because it's the only packaged I had. My system is Linux Mint x64. Any help please?

**Comment by TheMushrr00m** [comment]
@Krysisx You can check the packages folder if the uninstallation was correctly. Did you install atom from source code or directly from binary?

**Comment by Krysisx** [comment]
@TheMushrr00m I have installed atom from .deb package. I have also deleted a related folder in `~/.atom/.apm/` but same problem.

**Comment by TheMushrr00m** [comment]
@Krysisx What version do you have? Maybe .deb package was corrupted. I have no idea, this is so weird.

**Comment by Krysisx** [comment]
@TheMushrr00m My Atom version is v1.15.0

**Comment by a1exlism** [comment]
works well for me in latest atom version, thx!

**Comment by TheMushrr00m** [comment]
@Krysisx What plugins do you have installed?

**Comment by Krysisx** [comment]
@TheMushrr00m thanks for your help. I have solved the problem by uninstalling and reinstalling Atom.

**Comment by TheMushrr00m** [comment]
@Krysisx You had to do it the "dirty" way, that's what I was trying to avoid, well, enjoy this wonderful editor.
