### ISSUE TITLE
Can't launch Atom: "Could not create an input method."

### ISSUE THREAD

**Issue by Huluti** [atom/atom#13807]
When I try to launch Atom, I get this error in the console:

> index.js:61 Error: Could not create an input method.
>     at Error (native)
>     at Object.<anonymous> (/usr/lib/atom/node_modules/keyboard-layout/lib/keyboard-layout.js:9:17)
>     at Module._compile (/usr/lib/atom/src/native-compile-cache.js:109:30)
>     at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:216:21)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (/usr/lib/atom/src/native-compile-cache.js:50:27)
>     at Object.<anonymous> (/usr/lib/atom/node_modules/atom-keymap/lib/helpers.js:6:20)
>     at Object.<anonymous> (/usr/lib/atom/node_modules/atom-keymap/lib/helpers.js:372:4)
>     at Module._compile (/usr/lib/atom/src/native-compile-cache.js:109:30)
>     at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:216:21)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (/usr/lib/atom/src/native-compile-cache.js:50:27)
>     at Object.<anonymous> (/usr/lib/atom/node_modules/atom-keymap/lib/key-binding.js:4:10)
>     at Object.<anonymous> (/usr/lib/atom/node_modules/atom-keymap/lib/key-binding.js:129:4)
>     at Module._compile (/usr/lib/atom/src/native-compile-cache.js:109:30)
>     at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:216:21)
>     at Module.load (module.js:473:32)
>     at tryModuleLoad (module.js:432:12)
>     at Function.Module._load (module.js:424:3)
>     at Module.require (module.js:483:17)
>     at require (/usr/lib/atom/src/native-compile-cache.js:50:27)
>     at Object.<anonymous> (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:17:11)
>     at Object.<anonymous> (/usr/lib/atom/node_modules/atom-keymap/lib/keymap-manager.js:639:4)
>     at Module._compile (/usr/lib/atom/src/native-compile-cache.js:109:30)

Any idea?

**Comment by 50Wliu** [comment]
This will be fixed in Atom 1.14.2 (not yet released, but keep an eye out for it).

**Comment by Huluti** [comment]
Thank's!
