### ISSUE TITLE
Atom unexpectly crashes when I didn't save my work

### ISSUE THREAD

**Issue by amayarora** [atom/atom#13801]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashed when I didn't save my work.

### Steps to Reproduce

1. Recover my work I did not save, of course!

**Expected behavior:** Have my work to be saved!

**Actual behavior:** It did not save! GAHHHHHHHHHHHH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Reproduces how often:** Huh?

### Versions

Input: `atom --version`
Output: 
```
Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

Nothing, just help me bro!

**Comment by ozo2003** [comment]
without logs or steps to reproduce, this is just a rant and nobody can actually help you to do anything

**Comment by 50Wliu** [comment]
Thanks for contributing!

All new issues now require steps to reproduce (also called "repro steps") the problem or the behavior you wish to see in Atom. We do this so we can be certain that we are understanding what it is you're describing and don't prematurely close the issue or implement the wrong feature. If you need help writing detailed repro steps, please see the [How Can I Contribute? section of the Atom CONTRTIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
