### ISSUE TITLE
Atom had unexpectedly crashed when I didn't want it to.

### ISSUE THREAD

**Issue by amayarora** [atom/atom#13815]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashed when I didn't save my work.

### Steps to Reproduce

1. Find my work at [**@amayarora**](https://github.com/amayarora).
2. Go to files GitHub > pkb > Academics > School > Intermediate > Grade V > History > Chapter XII.md.
3. Recover Section II: *Who Were the Loyalists and Patriots?*, along with part of Section III: *Loyalists and Patriots*. Atom had crashed during this time, and didn't save my work. You should be able to find this work in one of the previous commits, which I really didn't commit, since it didn't save, but hopefully you know what I mean.

**Expected behavior:** Have my work to be saved!

**Actual behavior:** It did not save! GAHHHHHHHHHHHH!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Reproduces how often:** Once, please.

### Versions

Input: `atom --version`
Output: 
```
Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

Nothing, just help me bro!

**Comment by 50Wliu** [comment]
Are you saying that you were editing the md file when Atom crashed, or that opening the file causes Atom to crash?  What OS are you using?

If the former, is there anything in your `~/.atom/recovery` folder (or `%USERPROFILE%\.atom\recovery` if on Windows)?

**Comment by rsese** [comment]
Thank you for your issue!

We haven't received a response to our questions in our comment https://github.com/atom/atom/issues/13815#issuecomment-279754216. With only the information that's currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
