### ISSUE TITLE
Atom stops responding

### ISSUE THREAD

**Issue by ronag** [atom/atom#13827]
OSX. Was running 14.1 and Atom started to stop responding (think it was trying to auto update to 14.2?). I deleted the application, download 14.2 manually and not Atom consistently stops responding after ~30 seconds and have to be forced quit...

**Comment by ronag** [comment]
Back with 14.0. Runs fine now.

**Comment by ToSeven** [comment]
I have the same issue with you and how to back 14.0.  uninstall 14.1 then install 14.0?
