### ISSUE TITLE
After adjusting the tree view, the mouse does not drop the resize bar.

### ISSUE THREAD

**Issue by Xurma2** [atom/atom#13828]
In safe mode I cannot see Tree-View (try cmd + / doesnt work)
Yes
Yes

I click on the partition between the tree-view and other content.
I try to drag (reduced tree-view)
After dragging, release the mouse button.
atom considers that the mouse pressed.
Solution - Only restart

Expected behavior: If I release mouse button drug event stop

Actual behavior: If I release mouse button drug event doesnt work

Versions:
Atom    : 1.12.9
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.0
MacOS Sierra 10.12.1

![resize](https://cloud.githubusercontent.com/assets/5157416/23000862/0459a0c4-f415-11e6-897d-1e45eeb99f72.gif)

**Comment by Xurma2** [comment]
Same behaviour with `console`

**Comment by ungb** [comment]
Hi @Xurma2, Do you see this behavior when running chrome when trying to resize?  I am unable to repro on my machine.

**Comment by Xurma2** [comment]
Hi 
No. Chrome does not have a relation to the problem with the atom (I think)

**Comment by 50Wliu** [comment]
> In safe mode I cannot see Tree-View (try cmd + / doesnt work)

This implies that one of your installed community packages is overriding the tree view.  Make sure the Tree View (in Settings -> Packages) is enabled.

**Comment by Xurma2** [comment]
@50Wliu
You're right!
I activated it
But still hotkeys does not work, and it does not appear in the safe-mode
