### ISSUE TITLE
Soft wrap settings reset when saving new file

### ISSUE THREAD

**Issue by arkadiyt** [atom/atom#13829]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If soft wrap is enabled on a new, unsaved file and you save that file, then soft wrap is disabled on that file.

### Steps to Reproduce

1. Open a new, untitled window.
2. Put in enough text so as to require horizontal scrolling, and enable the soft wrapping under "View" -> "Toggle Soft Wrap"
3. Save the file

**Expected behavior:**

I expect the file to save and retain the soft wrap settings.

**Actual behavior:** 

The file saves but soft wrap is reset, and you get a single long line of text.

**Reproduces how often:**

100% reproducible. Only happens when saving a *new* file - if you enable soft wrap again, make some changes in the file and save it again, then the soft wrap settings are retained.

### Versions

Atom:
```
Atom    : 1.14.2
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
Apm:
```
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.11.1
```
OS: OSX Sierra 10.12.3
```
$ uname -mprsv
Darwin 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64 i386
```

**Comment by 50Wliu** [comment]
I can't reproduce this using Atom 1.16.0-dev-4422354, Windows 10 x64.

/cc @ungb

**Comment by ungb** [comment]
I tried this on atom 1.14.4, I didn't see this behavior either, that's really strange since softswrap is a setting in config.cson.
![image](https://cloud.githubusercontent.com/assets/5624870/23682472/c94bddce-0348-11e7-9022-da5b72327fa6.png)


![softwarp](https://cloud.githubusercontent.com/assets/5624870/23682630/b381c458-0349-11e7-8a2e-8c2ec253e870.gif)

**Comment by arkadiyt** [comment]
Still getting the same behavior in 1.14.4 - here's my repro:

![hitbox](https://cloud.githubusercontent.com/assets/2279289/23684395/72d6609e-0353-11e7-8af0-5620853b545e.gif)

**Comment by arkadiyt** [comment]
I put in enough horizontal text to require scrolling again, then enabled soft wrapping.

Then I set a conditional breakpoint on this line:
https://github.com/atom/atom/blob/4a165e239388058bf9c77cfb432dd734211a7997/src/text-editor.coffee#L225

with the condition:
`params['softWrapped'] === false`

Then I saved the file and the breakpoint triggered - here's the resulting callstack and local variables:
<img width="1331" alt="screen shot 2017-03-07 at 4 46 35 pm" src="https://cloud.githubusercontent.com/assets/2279289/23684782/a8fef030-0355-11e7-95a4-2a22949f169d.png">

If I go up one stack frame to `text-editor-registry.js:327`, it seems that `textEditorParamsForScope` is returning params with `softWrapped: false`, and going to the definition of that function, it seems that `this.config.get('softWrapped', configOptions)` on this line:
https://github.com/atom/atom/blob/4a165e239388058bf9c77cfb432dd734211a7997/src/text-editor-registry.js#L366

is returning false even though I have enabled soft wrap from the menu.

**Comment by ungb** [comment]
I am able to repro this on latest on master.  

The following repro steps is what I followed(similar to what you provided)
1. Open a `untitled` window on atom
2. Paste in the text:
```
This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test This is a test

```
3. in Context menu, go to view -> Toggle Soft Wrap
4.  Save the file as `softwarpTest.txt`

Noticed that softwrap is gone.  Weird thing is if you save it without the `.txt` the softwrap persist.

**Comment by daviwil** [comment]
It turns out this issue is due to how the TextBuffer's assigned grammar changes from when it's an untitled buffer (NullGrammar with scope `text.plain.null-grammar` to Grammar with scope `text-plain`).  We've got some [logic in TextEditorRegistry](https://github.com/atom/atom/blob/master/src/text-editor-registry.js#L223) that overwrites the settings of a TextEditor when its underlying TextBuffer's language mode changes.

I'm aiming to fix this by making this code more aware of how the buffer settings change due to language mode changes so that we only overwrite the settings that would change between the two language modes.

Many thanks to @maxbrunsfeld for his help investigating this!

**Comment by daviwil** [comment]
This issue actually did get fixed earlier this year (Jan 12) but I forgot to close it!
