### ISSUE TITLE
update atom 14.1 and can not work

### ISSUE THREAD

**Issue by ToSeven** [atom/atom#13837]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It can not work after updating atom .Now atom version is 14.1 .
 
### Steps to Reproduce

 1. startup atom . 
2.the atom show below. It does not respond and show nothing.
![1](https://cloud.githubusercontent.com/assets/14891443/23054179/3f4f6e98-f519-11e6-9f04-c9767c9e6cf1.PNG)

### Versions
computer system :windows 10
atom :14.1

**Comment by 50Wliu** [comment]
Can you reproduce the problem in safe mode (`atom --safe`)?

**Comment by ToSeven** [comment]
the same issue in safe mode

**Comment by ToSeven** [comment]
Now atom version is 14.2.

**Comment by TuKun33** [comment]
i just install 1.14.4，my cpu(i3 6100) is boom。
![d611b0525310124f8f80f8a18d644e81](https://cloud.githubusercontent.com/assets/22310931/23603235/2c0f32f4-028f-11e7-8ac0-b059206a65b9.jpg)

**Comment by 50Wliu** [comment]
@ToSeven what about `atom --disable-gpu`?

**Comment by ToSeven** [comment]
I have updated atom with 14.3 then it is OK
