### ISSUE TITLE
[UX] The Welcome Guide option should probably apply only to new windows, not windows with content.

### ISSUE THREAD

**Issue by bdsexton** [atom/atom#13830]
### Prerequisites

This section is mostly not applicable because the issue is one of default user experience.

* [X] Put an X between the brackets on this line if you have done all of the following:
    * N/A: Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * N/A: Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * N/A: Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * ✓ (I don't see it.): Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * N/A: Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The "Show Welcome Guide when opening Atom" option should probably apply only to new windows, not to windows that already contain other content.

A possible exception: it may be desirable to show the Welcome Guide after an update, although a prompt would be preferable to automatically showing it in a window that already contains other content.

### Steps to Reproduce

1. Start Atom.

**Expected behavior:** [What you expect to happen]

If I DID have content open, I expect to see that regardless of the Welcome Guide display setting.

If I did NOT have content open and the Welcome Guide display setting is OFF, I expect to see a new window with a fresh, focused editor tab ready for immediate use.

If I did NOT have content open and the Welcome Guide display setting is ON, I expect to see a new window with the Welcome Guide.

**Actual behavior:** [What actually happens]

If the Welcome Guide display setting is ON, it is displayed whether or not I had other content open.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time (100%) except once immediately after the 1.14.2 upgrade, when the first window was blank and never rendered any content or the Welcome Guide.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

1.14.2 x64 for macOS*

\* That is on the computer I am presently using, but the issue is not actually platform-specific.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

N/A

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is an issue for the [Welcome package](https://github.com/atom/welcome), can you  file this issue in that repository?
