### ISSUE TITLE
Global search/replace (with regex) not working

### ISSUE THREAD

**Issue by ffxsam** [atom/atom#13844]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When doing a global regex search/replace, matches are found and replacements are confirmed visually, but the actual replace function does nothing.

### Steps to Reproduce

(in my particular case)
1. Open Find in Project.
2. Enable regex.
3. Search for: ^export default (.*)\)$
4. Find all.
5. Replace with: export default $1);
6. Hit "Replace All"

**Expected behavior:** [What you expect to happen]

I expected all the shown instances of code to be replaced.

**Actual behavior:** [What actually happens]

I was told "Nothing replaced" and my git status confirmed that.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time.

### Versions

Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.11.1
Mac OS 10.12.3

### Additional Information

See screen capture: 

[ScreenFlow.zip](https://github.com/atom/atom/files/784543/ScreenFlow.zip)

**Comment by rsese** [comment]
Thanks for contributing!

I think this is an issue for the [find-and-replace](https://github.com/atom/find-and-replace) package, can you file this issue in that repository?
