### ISSUE TITLE
atom freeze when open compress file

### ISSUE THREAD

**Issue by reimax** [atom/atom#13847]
Hi

atom 1.14.2x64. ubuntu 16.04. 
disable all installed modules. open compress js file:
[compress.txt](https://github.com/atom/atom/files/785115/compress.txt)

in attache txt file, change to js

editor not responding and freeze.

if open txt file as plane text, atom work normal. if change to JavaScript - atom freeze.

**Comment by clabnet** [comment]
+1

**Comment by 50Wliu** [comment]
Should be fixed in Atom 1.15.0-beta3 and later.
