### ISSUE TITLE
Atom is great... until you give it an addon

### ISSUE THREAD

**Issue by angelxaces** [atom/atom#13849]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    [x]* Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
   [x] (none) * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    [x]* Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
[x]* Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom seems fine on it's own but the second I put anything on it the thing acts like I kicked it's puppy. 

### Steps to Reproduce

step one: install Atom
step two: install a package
step three: wait for atom to crash. it will, just give it a couple seconds. 

**Expected behavior:** [What you expect to happen]
function. allow me to use it. work. 

**Actual behavior:** [What actually happens]
freezes 
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Can you share the `Versions` details asked for in the template?

Also, can you share specific packages that you installed that caused Atom to crash?

**Comment by angelxaces** [comment]
that's just it, I could, but it doesn't say anything useful. As far as I can tell it tears through it allocated ramm like jack the ripper. 

I'm sorry, I thought I finished sent this. That said I'll upload it when I get home. I would SSH but its difficult when the computer/acting home server is off :)

**Comment by angelxaces** [comment]
ok, I've gathered the info but it 's quite extensive. I haven't gone through it all and it will take forever to get through. I ran a memory leak test against atom which is how I tested my memory issue theory. Atom went down almost immediately.

Instead of posting all of this publicly I would prefer to share it with one person at first. If someone would be willing to do that they can post the relevant data. Right now it's just pretty much a log dump.

**Comment by rsese** [comment]
It would be easiest for someone to take a look if you can post the data publicly so many people have a chance to take a look - if you'd like, instead of just pasting all the data in a comment, you can post the data in a gist and share the link.

Can you also share the information I asked about [above](https://github.com/atom/atom/issues/13849#issuecomment-281164663)?

> Can you share the Versions details asked for in the template?

> Also, can you share specific packages that you installed that caused Atom to crash?

**Comment by angelxaces** [comment]
Obviously that would be easier for everyone else, including the would-be hacker who breaks in after I share something I didn't intend to. Didn't think of a gist though.

**Comment by rsese** [comment]
If you're not comfortable sharing log files publicly that's fine - before moving forward though, can you share the information I asked for above?

> Can you share the Versions details asked for in the template?
> Also, can you share specific packages that you installed that caused Atom to crash?

**Comment by Vylcas** [comment]
Are you still having issues? If so, I'd be happy to help. New to GitHub and wanting to help in any way I can.

**Comment by angelxaces** [comment]
No @Vylcas, I'm not but thank you for reminding be to say something. I was so wrapped up in what I was doing that when I stumbled across the answer I spaced. It's well-complained about as it is but here's the comment that helped me figure it out.

#11590
