### ISSUE TITLE
Raster text cursor doesn't scale and doesn't look native

### ISSUE THREAD

**Issue by marcoms** [atom/atom#13852]
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

By default, Atom uses a base64 encoded image as the text cursor in the atom-text-editor component. There are some problems with this:

- It's not the native text cursror - looks out of place
- It doesn't scale well - the first image below is the default cursor, with macOS cursor scaling enabled. The second shows the native OS text cursor (pixellated..). The native cursror was scaled correctly as a vector but the screenshot tool for some reason renders it at the normal 1x size (just imagine it scaled properly :))

![cursor-img](https://cloud.githubusercontent.com/assets/4211302/23124134/4f4b3998-f763-11e6-9534-90431208c23e.png)

![cursor-reg](https://cloud.githubusercontent.com/assets/4211302/23124137/55d5812e-f763-11e6-9f83-e5fcbe1fa98d.png)

Fix is to use something similar to this: 

```css
atom-text-editor.editor .scroll-view {
    cursor: text;
}
```

### Steps to Reproduce

1. Hover over a text field

**Expected behavior:** Cursor should be native text cursor, should scale with accessibility settings

**Actual behavior:** Cursor is a custom raster image - therefore becomes pixellated when scaled

**Reproduces how often:** 100%

### Versions

```fish
> atom-beta --version
Atom    : 1.15.0-beta3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.
```

macOS sierra 10.12.3

**Comment by simurai** [comment]
> Atom uses a base64 encoded image as the text cursor in the atom-text-editor component

The reason for using an image is so that the color changes to white if a dark theme is used. We might can use an SVG version instead and see if it stays sharp when scaled up.

btw. here the settings to change the cursor size:

![screen shot 2017-02-21 at 11 38 08 am](https://cloud.githubusercontent.com/assets/378023/23148677/87f12c4a-f82a-11e6-9cab-2926a30ad03b.png)

**Comment by marcoms** [comment]
@simurai Yeah I did use that scaling setting - and the native cursor does stay sharp scaled up. It's just the macOS screenshot doesn't show the larger cursor for some reason.
Here is a picture I've taken manually of the cursor scaled up - as you can see it scales well and also has a white stroke for visibility on a dark background (not as contrasting as 100% white but seems easy enough to see).

![img_20170221_103510487_hdr](https://cloud.githubusercontent.com/assets/4211302/23161404/f2a6e0a6-f821-11e6-8611-fed0c6414d14.jpg)
