### ISSUE TITLE
Atom crashes when opening a folder containing a git sparse checkout

### ISSUE THREAD

**Issue by wadefagen** [atom/atom#13859]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashes when opening a folder containing a git sparse checkout.

### Steps to Reproduce

1. Create a sparse checkout of a git repo.
  - `mkdir thisWillCrashAtom`
  - `cd thisWillCrashAtom`
  - `git init`
  - `git config core.sparseCheckout true`
  - `git remote add -f origin git://...`
  - `echo someRepoPath/* > .git/info/sparse-checkout`
  - `git checkout master`
2. Open the `thisWillCrashAtom` directory with atom

**Expected behavior:** Atom opens without crashing.

**Actual behavior:** Atom crashes.

**Reproduces how often:** Always.

### Versions

Windows 64-bit (Windows 7 and Windows 10)

Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 ia32
python 3.5.2
git 1.9.4.msysgit.1
visual studio 2012

**Comment by carb0nknight** [comment]
I'm experiencing a similar issue with Atom after the Windows Github app failed to sync with one of my repo's properly. I've tried reinstalling Atom, and removing the local repo that caused the issue, but still can't get Atom to open without crashing immediately.

**Comment by rsese** [comment]
I just tried on 1.14.4 on Windows 10 but was unable to reproduce - after doing a sparse checkout I ran `atom .` and Atom opened without crashing.  I also tried starting Atom and then adding the project directory and that worked ok too.

**Comment by rsese** [comment]
@wadefagen - I'm assuming the answer is yes, but just to confirm, have you hit this problem no matter what repository you use?  I tested with https://github.com/atom/markdown-preview.

**Comment by CyanChoi** [comment]
@rsese my repository is [https://github.com/gaearon/redux-devtools.git](https://github.com/gaearon/redux-devtools.git),
same case

**Comment by rsese** [comment]
Going to re-tag this as `needs-reproduction`.
