### ISSUE TITLE
find in current buffer

### ISSUE THREAD

**Issue by verglas** [atom/atom#13857]
Use regular expression to find, modify the search string, when the search string is empty, The program stops responding, can not cancel the regular expression search.

When the search string is empty, the query should be triggered by the user

1.13.0 win10 x64

**Comment by rsese** [comment]
Thanks for contributing!

This looks like an issue for the [find-and-replace](https://github.com/atom/find-and-replace) package, can you file the issue in that repository?  When you do, please fill out the issue template fully.
