### ISSUE TITLE
Don't let run atom as root

### ISSUE THREAD

**Issue by pabloab** [atom/atom#13851]
In particular for experienced users is [pretty known](https://github.com/atom/atom/issues/10566#issuecomment-278616243) they shouldn't run atom as root, not only for problems this make on .atom folder but also because of security issues. [In this post Martin Gräßlin](https://blog.martin-graesslin.com/blog/2017/02/editing-files-as-root/) (Kate and Kwrite developer) say:

> Today I pushed a change for Kate and KWrite which does no longer allow to be run as root. Instead it educates the user about how to do the same with sudoedit.

Probably Atom should do the same.

**Comment by polarathene** [comment]
PolKit/pbexec might be a better way to go about it, that is more commonplace/flexible than sudoedit?

**Comment by pabloab** [comment]
Probably, I'm not an expert. Even if the editor might use polkit to save the file, atom shouldn't run as root. This will also avoid people to screw their `.atom` folder and then need to ``sudo chown -R `whoami`:`whoami` ~/.atom``.

**Comment by polarathene** [comment]
PolKit doesn't cause Atom to run as root, from my understanding you create a policy file to state what root permissions it needs, then when those are needed the user is presented with a dialog to enter a password. So if you tried to open or save a file that needs root rights, you define the need for root read/write of files and when requested the user must authorize. Everything else not defined in the policy is non-root.

Someone created a web based package manager for pacman recently, when it needs root permissions it uses polkit I've heard, might be worth looking at for reference?

**Comment by pabloab** [comment]
> Someone created a web based package manager...

Do you remember something else? So I could research and help Atom's developers.

**Comment by polarathene** [comment]
@pabloab good thing I could find it on reddit post from a month ago, didn't have luck with google. [Here] it is](https://github.com/flipflop97/WebMan)

**Comment by jlbrewster** [comment]
Is there a temp fix to EACCESS denied errors?
