### ISSUE TITLE
Using customFileTypes for xtend

### ISSUE THREAD

**Issue by bredmich** [atom/atom#13855]
### Description

I want  to use the customFileTypes feature to highlight .rules files as xtend

I tried to add the following to my config.cson:
`customFileTypes:
'source.xtend': ['rules','sitemap']`

I added xtend via `apm install language-xtend`

I´m pretty sure the `source.xtend` is wrong.
But what´s the correct one?

Thanks!

**Comment by 50Wliu** [comment]
See https://discuss.atom.io/t/how-do-i-make-atom-recognize-a-file-with-extension-x-as-language-y/26539.

**Comment by bredmich** [comment]
I already did that, but the link within this post isn´t working.
http://flight-manual.atom.io/#finding-a-language-s-scope-name

**Comment by BinaryMuse** [comment]
@bredmich That link should now lead here: http://flight-manual.atom.io/using-atom/sections/basic-customization/#finding-a-languages-scope-name

I think the link was broken when the Flight Manual was updated a while back.

**Comment by bredmich** [comment]
@BinaryMuse: Thanks for that!
Now i know that `source.xtend` is correct.
But Atom still doesn´t highlight files with '.rules' as xtend.
I´m able to manually set the language to xtend with 'CTRL + Shift + l' but this only works for one file and not after restarts.

Also there is some misunderstanding in the manual.
http://flight-manual.atom.io/using-atom/sections/basic-customization/#finding-a-languages-scope-name
`'*':
  core:
    customFileTypes:
      'source.coffee': [
        'foo'
      ]
`

While my config.cson starts mit '"*":'
