### ISSUE TITLE
When using "duplicate" on a file, mode (+x) is not preserved

### ISSUE THREAD

**Issue by alberto56** [atom/atom#13868]
To reproduce, right-click any file with mode +x, duplicate it, and the mode (+x) is not preserved. I am expecting it to be preserved, see enclosed image.

<img width="498" alt="screen shot 2017-02-23 at 8 25 04 am" src="https://cloud.githubusercontent.com/assets/808265/23260831/b478ecb2-f9a1-11e6-8514-73a2b04730a7.png">

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Please reopen this on the atom/tree-view repository and completely fill out the issue template.  Thanks!
