### ISSUE TITLE
Atom don't work, show a message "The editor has crashed".

### ISSUE THREAD

**Issue by jedidas** [atom/atom#13862]
Hello, I always use atom in my work, but now don't wants work, when I open atom it show me that message.

**Please report this issue to https://github.com/atom/atomPlease report this issue to https://github.com/atom/atom**

Here there is a image.
[Error image](https://image.ibb.co/n5hTGF/Captura_de_pantalla_2017_02_21_a_las_20_46_19.png)

I uninstalled Atom and downloaded it again but it does not work. How could I fix atom?

Thanks.

**Comment by 50Wliu** [comment]
Move `~/.atom` to `~/.atom-backup`.
