### ISSUE TITLE
Unsaved Files Deleted Randomly

### ISSUE THREAD

**Issue by JHNUXER** [atom/atom#13879]
I just had 4 source files that I was working on completely erased. They were all untitled files because I hadn't saved yet. I switched to a file I HAD saved to change something, and when I went back, I looked in the first untitled tab, only to find it empty. I quickly discovered the other untitled tabs were empty as well. Long-story short, I just lost four source files and thought you may want to look into the cause of this/see if anyone else has this issue.

**Comment by lee-dohm** [comment]
Thanks for the submission.

We haven't received any other reports of untitled files being wiped of their contents while Atom is running. We do have https://github.com/atom/atom/issues/13318 which describes how untitled files aren't silently saved when Atom exits without a project folder, though you are now prompted to save them on exit.

While losing work is somewhere between annoying and catastrophic, without the information that was requested in the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md), we don't have enough information to do any real investigation here. We would be happy (and highly motivated) to look into what went wrong if you open a new issue and fill in the details requested in the issue template.

Thanks for understanding and meeting us halfway.
