### ISSUE TITLE
Can't Write Numbers on HTML files

### ISSUE THREAD

**Issue by Akumetsu-Dev** [atom/atom#13872]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I try to enter numbers using the keyboard in an html file, atom does not allow input, but if it is any other file: css, js, text, I can enter numbers

### Steps to Reproduce

1. Open atom.
2. create .html file
3. try input number.

**Expected behavior:** Write Numbers

**Actual behavior:** Numbers not appear

**Reproduces how often:** Always

### Versions

Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.10.2

**Comment by Ben3eeE** [comment]
What are the contents of your `keymap.cson` file?

**Comment by lee-dohm** [comment]
Do you have Emmet installed? And were you able to reproduce this in Safe Mode? To launch Safe Mode:

1. Completely exit all instances of Atom
1. Launch Atom with the command `atom --safe`

**Comment by HerrWagner1680** [comment]
I also had this problem on the HTML setting in Atom. But it was an easy fix. Opened the atom `keymap.cson` file. Deleted code that I recently added. Relaunched with the `atom --safe` command.

If you're curious, the bug-producing code came from the keymap section of this page: https://atom.io/packages/open-html-in-browser

**Comment by Akumetsu-Dev** [comment]
Thank to HerrWagner1680 this 
`'atom-text-editor[data-grammar~="html"]':
    'open-html-in-browser:open'`

code in the keymap.cson create the conflict with the `atom-text-editor[data-grammar~="html"] `part, so i have to report this on the addons issue side

Close issue.
Thank you for the fast respond
