### ISSUE TITLE
Copy Paste not working when editing XML files (Atom 1.14.3)

### ISSUE THREAD

**Issue by Kungfoowiz** [atom/atom#13871]
This is to continue from a previous issue but was closed (https://github.com/atom/atom/issues/11881). 

I am now using Atom 1.14.3. 

Sorry, I got busy and did not use Atom for some time, lol. Now that I am back using it again, I tried testing this in Atom --safe mode and noticed something else. It appears to happen only in Mixed mode (see screenshot below). Mixed mode regarding CR / LF characters, you can see this on the file details on the bottom right in the screenshot.

You can also see when I copied the text from the Mixed mode XML file that it only copied the first character. I used the exact same example XML file as I originally attached to this issue.

And then I used a sample XML file using CRLF mode (Download from here: https://www.w3schools.com/xml/simple.xml). I was able to copy the text fine with this example, but not with the above example.

I wonder also, the encoding type set in the above XML is UTF-16, yet Atom reports it as UTF-8. Maybe it is having an issue reading the characters because of this?
It could also be the Mixed mode?

![atom safe mode test](https://cloud.githubusercontent.com/assets/17824719/23263757/1d27f80e-f9d7-11e6-91cf-51377690f7cf.jpg)

**Comment by Ben3eeE** [comment]
Closing in favor of https://github.com/atom/atom/issues/11881
