### ISSUE TITLE
Data loss scenarios with opening project with atom in empty state  

### ISSUE THREAD

**Issue by ungb** [atom/atom#13873]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom 
        * There's a lot of issues filed for this already :) this is a issue to consolidate the root issues.  
    * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is to capture a few data loss scenarios with opening your project.  

There are 3 bugs that we can see so far that will cause data loss

### **Opening a Empty Document and try to `Open` the folder from context menu.**

  Repro:

  1. Open Atom, go to settings, check `Open Empty Editor On Start` and uncheck `Restore Previous Windows on Start` 
  2. Open a folder, add a few untitled documents or make changes to file and don't save anything.
  3. Close Atom
  4. Open Atom, you should get a blank editor
  5. Go to context menu and click `Open` (or cmd+o on mac) and open the folder from step 2.  

Expected: Restores Session
Actual: Unsaved session is lost.

### **Opening a Empty Document and trying to `Add a Project Folder` from context menu**

  Repro:

  1. Open Atom, go to settings, check `Open Empty Editor On Start` and uncheck `Restore Previous Windows on Start` 
  2. Open a folder, add a few untitled documents or make changes to file and don't save anything.
  3. Close Atom
  4. Open Atom, you should get a blank editor
  5. Go to context menu and click `Add a Project Folder...` (or cmd+shift+o on mac) and open the folder from step 2.  

Expected: Since there isn't any folder added yet, Atom should restore the session of that folder.
Actual: Unsaved session is lost. 

    
### **Open `atom .` when there is a empty atom editor open.**
Repro:
  1. Open Atom, go to settings, check `Open Empty Editor On Start` and uncheck `Restore Previous Windows on Start` 
  2. Open a folder, add a few untitled documents or make changes to file and don't save anything.
  3. Close Atom
  4. Open Atom, you should get a blank editor
  5. Go to terminal/powershell and go to the folder in step 2 and run `atom .` 

Expected: Restores Session
Actual: Unsaved session is lost. If no atom instance is running this works.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100% of the time.  

### Versions
Atom 1.14.3

### Additional Information

This is causing a lot of various reports, but I think this is the underlying cause for most of them.  

/cc @lee-dohm @iolsen @ben3eee

**Comment by ungb** [comment]
Related issues so far:

https://github.com/atom/atom/issues/13861
https://github.com/atom/atom/issues/11293
https://github.com/atom/atom/issues/10044

**Comment by 50Wliu** [comment]
Does checking the Restore Previous Windows on Start option mean that no state should ever be restored, or that you should be able to recover project state by explicitly opening the previous project you had open?

**Comment by Ben3eeE** [comment]
I believe the setting only affects restoring state when launching Atom without any arguments.
