### ISSUE TITLE
Hard Crash on Win10-64 at Toggle Full Screen (F11)

### ISSUE THREAD

**Issue by KlugB** [atom/atom#13870]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hard Crash on Win10-64 at toggle full screen (F11)

### Steps to Reproduce

1. Clean install recent AtomSetup-x64.exe
2. Start Atom
3. Press F11

**Expected behavior:** Well, full screen mode, I guess.

**Actual behavior:** Hard crash of Windows (blue screen with something like "A problem occured. Windows must be restarted. Collecting information...")

**Reproduces how often:** 100%

### Versions

System: DELL Latitude E6430
Windows 10 Pro Version 1607 Build 14393.693
Graphics (both up-to-date):
Intel(R) HD Graphics 4000, driver version 10.18.10.4425
NVIDIA NVS 5200M, driver version 21.21.13.6909
Atom Version 1.14.2

**Comment by MaherFa** [comment]
I couldn't reproduce the issue. I have latest atom installed on Windows 10 x64 and also tested a fresh install on a VM Win 10 x64.

**Comment by KlugB** [comment]
My guess is that this is a graphics card issue. Remembers me of a [Chrome bug](https://productforums.google.com/forum/#!topic/chrome/fQuPiV8YOlc) where I had to turn off "Use hardware acceleration when available". So it would be interesting to hear from people who also have a laptop with two graphics adapters (especially with Intel HD graphics 4000). Maybe atom uses some display component which uses hardware acceleration?

**Comment by MaherFa** [comment]
since atom is built on top of electron I thought maybe `app.disableHardwareAcceleration()` would help, but running in console:
`require('electron').remote.app.disableHardwareAcceleration()`
I got the following error:
> app.disableHardwareAcceleration() can only be called before app is ready

so I'm guessing it can only work in main process which is packed in asar and too much work to edit.

anyway I'd try running atom with the commandline `--disable-gpu` and see if it helps at all.

**Comment by 50Wliu** [comment]
Yes, definitely try `atom --disable-gpu`.

**Comment by KlugB** [comment]
`-- disable-gpu` worked :thumbsup:
