### ISSUE TITLE
Possible Issue With Right Click Menu

### ISSUE THREAD

**Issue by c0fe** [atom/atom#13881]
When you right click on a particular file, in Windows 7 you have an immediate option to have that file open in Atom but in Windows 10 that option is not there. Although in both versions Atom is an option in "Open With" menu. I am not sure if this is a bug, intentional design or a result of a restriction in Windows 10.

**Windows 10:**
http://i.imgur.com/S9AKpUh.png

**Windows 7:**
http://i.imgur.com/yBIwJDC.png

**Comment by 50Wliu** [comment]
Open Atom: Settings -> System -> check "Show in file context menus".
