### ISSUE TITLE
macOS Sierra Atom-beta dock icon never stops bouncing when launched from shell

### ISSUE THREAD

**Issue by DanFreed** [atom/atom#13886]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
**--- There isn't a dock icon in safe mode.**
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On macOS Sierra 10.12.3, when launching atom from the command line, the dock icon never stops bouncing.  When launching from Finder, spotlight, or Alfred this does not happen.

I'm using Atom 1.15.0-beta3 x64

### Steps to Reproduce

1. open a Terminal application
2. close Atom if it is running (the entire application Atom-Beta menu... Quit)
3. use the atom shell script to launch atom: atom-beta

Expected behavior: The dock icon should stop bouncing after the application is launched

Actual behavior: The icon bounces forever.

Reproduces how often: every time.

### Versions
$ atom-beta -version
Atom    : 1.15.0-beta3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm -version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.9.3

**Comment by rsese** [comment]
Hmmm, I just installed the beta on 10.12.3 but couldn't reproduce - after I launch with `atom-beta`, the dock icon bounces, Atom gets focused, and the bouncing stops.

**Comment by DanFreed** [comment]
Is it possible it has something to do with the in place upgrade from the previous beta?  That would be the only thing I can think would be different from what you described.

**Comment by rsese** [comment]
I'm not sure but I can double check at the next upgrade in case no one else has a chance to try and reproduce in the meantime.  Just to double check, if you focus Atom, you can still use it and the dock icon stops bouncing?

Also you said:

> --- There isn't a dock icon in safe mode.

I was able to run the beta in safe mode and I have a dock icon - to confirm, is the lack of a dock icon also 100% reproducible (not sure if it's related, mostly curious)?

**Comment by DanFreed** [comment]
I re-attempted the safe-mode start, and I did get a dock icon.  I'm not sure what I did last time when it didn't show up.  Sorry for the red herring.   Unfortunately, it still bounced forever.

When I launch it from the shell script, I can interact with it and use it just fine, but the icon bounces away until I quit completely out of Atom.  If I launch atom by double clicking the icon in finder (or use Alfred or spotlight) it bounces once or twice then stops.  I can then open new Atom windows from the shel, and a new Atom icon shows up for a second in the dock(I'm assuming it is some kind of helper) before the window opens.  The second icon disappears pretty quickly.

**Comment by rsese** [comment]
I updated to 1.15.0-beta4 and tried again but didn't see the continuous bouncing dock icon.

> When in safe mode it doesn't bounce forever.
>
> It must be a package I have installed I guess.

Thanks for confirming :+1:  That does seem to point to a package as the issue but it may be that there is still a bug in Atom.  If so and you're able to pinpoint which package is causing the problem, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
