### ISSUE TITLE
Editor becomes unresponsive and may crash when opening large/minified files

### ISSUE THREAD

**Issue by danielbonnell** [atom/atom#13889]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I recently noticed that Atom freezes and becomes unresponsive whenever I open a large file with say, more than 300 lines, or any kind of minified JS file. I'm running `v1.14.3` on `OS 10.11.6`. I can reproduce the issue consistently even in safe mode.

I've tried disabling all of my added packages and reverting to the stock themes, but that made no difference.

When opening a large non-minified file, Atom seems to recover from the freeze in a few seconds but continued running sluggishly. When opening any minified file, Atom freezes and I am forced to force quit the process.

### Steps to Reproduce

1. Open Atom
2. Open a large file with more than 300 lines of code OR:
3. Open any minified JS file

**Expected behavior:** Should open the file and continue to be responsive.

**Actual behavior:** Freezes and usually must be force quit

**Reproduces how often:** Reproducible 100% of the time

### Versions

OS X : 10.11.6 (Mid 2009 13" MacBook Pro / 2.26GHz Core 2 Duo 8GB RAM / 256GB SSD)
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

See attachment for latest crash report.
[Atom_2017-02-27-155309_GALACTICA.txt](https://github.com/atom/atom/files/805165/Atom_2017-02-27-155309_GALACTICA.txt)

Community Packages Installed:
1. autoclose-html v0.23.0
2. color-picker v2.2.5
3. file-icons v2.0.16
4. fold-functions v0.5.0

Community Themes Installed:
1. seti-ui v1.6.1

**Comment by 50Wliu** [comment]
This will be fixed in the Atom 1.15.0.
