### ISSUE TITLE
How to force particular syntax type?

### ISSUE THREAD

**Issue by adi518** [atom/atom#13893]
I have a project with es5 and another with es6, react etc'. The issue is with Atom packages like Beautify. It acts differently between syntax type `JavaScript` and `JavaScript with JSX`. Is there config file I can place in project root to force the desired syntax type?

Thanks.

**Comment by 50Wliu** [comment]
https://discuss.atom.io/t/how-do-i-make-atom-recognize-a-file-with-extension-x-as-language-y/26539

**Comment by adi518** [comment]
Thanks. I arrived at that entry too, but I'm looking for a per project config to override Atom's `config.cson`. Looking around some more reveals there's no such feature in Atom as of yet, right?

**Comment by 50Wliu** [comment]
Yeah, there is no per-project support yet.  For that, you may want to subscribe to #5168.
