### ISSUE TITLE
Atom crashes when opening file (11KB minimized javascript)

### ISSUE THREAD

**Issue by Aloso** [atom/atom#13907]
Atom crashes when I open one 11KB minified javascript file. Then the whole editor freezes. However, the menu bar still works. This also happens when I use `atom --safe` to start Atom without packages. The error even appears after a **factory reset**.
[prism.js.txt](https://github.com/atom/atom/files/811506/prism.js.txt)

The following error is displayed when **_starting_** Atom:

> Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

When the editor freezes, no error is displayed. I noticed that CPU profiling in the developer tools is not possible while the editor is frozen

 (it can't be stopped).

### Steps to Reproduce

The file that repeatedly caused the error is called **`prism.js`**. Since no javascript files can be uploaded here, I renamed it to **`prism.js.txt`**.

To reproduce the error, download the file in the appendix, rename it to `pism.js` and open it. If you don't rename it, the error won't occur.

### Versions

`Atom: 1.14.4
Electron: 1.3.13
Chrome: 52.0.2743.82
Node: 6.5.0`

**Comment by damieng** [comment]
Hi, we have fixed this in Atom 1.15.0-beta3 (currently in beta).  You can find more details at https://github.com/atom/atom/issues/979
