### ISSUE TITLE
[Enhancement] "Automatically Check for Update" Atom option

### ISSUE THREAD

**Issue by eduncan911** [atom/atom#13905]
### Description

Atom 1.14.4 has an automatic "Automatically download updates" option.  

This eats up bandwidth on Mobile devices if this is checked, as it has no mercy of what type of connection it has when checking and downloading.  

But, i want to be automatically notified when updates are available - so after my long commute when I arrive in the office, I can just download it!  Therefore, a simple "curl json" request is acceptable on a Mobile connection - instead of downloading 100MB!!!

### Proposal

Change Atom to have a drop down/selection of:

* Do not check for updates (existing functionality when Unchecked)
* **Notify only when updates are available but don't download (new functionality)**
* Automatically download updates (existing functionality when Checked)

### Versions

```
macOS 10.12.3

$ atom --version
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.12.0

```

**Comment by 50Wliu** [comment]
This is currently not possible.  You may want to subscribe to https://github.com/electron/electron/issues/4587 for updates.
