### ISSUE TITLE
Editor pane renders without font styling

### ISSUE THREAD

**Issue by aidan-fitz** [atom/atom#13908]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The editor pane doesn't render the font chosen in settings.

### Steps to Reproduce

1. Open **Settings** (Ctrl+,) > **Editor Settings**.
2. Type a font name into the "Font Family" field, e.g. Courier 10 Pitch.
3. Restart Atom.

**Expected behavior:** Text should render in the specified font.

**Actual behavior:** Text renders in the default system font, Liberation Serif.

**Reproduces how often:** Always.

### Screenshots

![no fonts 2](https://cloud.githubusercontent.com/assets/2768977/23477444/f3988a26-fe8b-11e6-8748-f2413358b941.png)

![no fonts](https://cloud.githubusercontent.com/assets/2768977/23477461/fea36b66-fe8b-11e6-9ce8-18dfb0f5392c.png)

### Versions

Atom 1.14.4 (Electron 1.3.13, Chrome 52.0.2743.82, Node 6.5.0) on Ubuntu 16.04 LTS

**Comment by 50Wliu** [comment]
Is Courier installed and available on your system?

**Comment by aidan-fitz** [comment]
Yes it is.

**Comment by damieng** [comment]
Are you sure it's not `Courier New` ?   The font selection is definitely working here and I'm sure if it was totally broken we'd have issues open everywhere.

**Comment by 50Wliu** [comment]
Note that Atom is running on Ubuntu in this case, and Courier New is a Windows font.  That's why I asked.

**Comment by aidan-fitz** [comment]
I have both plain old Courier by IBM and [Courier 10 Pitch](https://en.wikipedia.org/wiki/Courier_(typeface)#Courier_10_Pitch_BT) by Bitstream.

**Comment by aidan-fitz** [comment]
I'm back. I'm now using version 1.20.1 and this is still not working. :slightly_frowning_face:

**Comment by damieng** [comment]
Just tried Atom 1.20 on Ubuntu 16.

Was easily able to set a bunch of the fonts and it applied fine.

Looked at using Courier 10 Pitch Regular - turns out that's a Postscript type-1 font. Such fonts aren't supported by Google Chrome and subsequently by Electron or Chrome.

System appears to come with a Courier clone called "Tlwg Mono" that worked just fine.

**Comment by aidan-fitz** [comment]
I'm trying it with a TrueType font now and it's still not working.
![still doesn't work](https://user-images.githubusercontent.com/2768977/30871206-04749fac-a2b4-11e7-8a63-67b2b87f771b.png)
