### ISSUE TITLE
Grey text in editor should be black

### ISSUE THREAD

**Issue by ad8e** [atom/atom#13913]
https://discuss.atom.io/t/grey-text-in-editor-should-be-black/40099
> The default white editor themes (One Light, Atom Light, Base16 Tomorrow Light, Solarized Light) have grey text, but research papers on typography stress the importance of high contrast for readability. That is, if the text is intended to be black on white, then it should be pure black and pure white. This is a good survey: [Hall Hanna 04](http://tecfa.unige.ch/tecfa/maltt/cosys-2/textes/hall04.pdf), Section 1.1. It states, "There is a large body of research... that indicates that high levels of contrast lead to better readability." And it gives a lot of citations.

I think all four default white-background themes should have black text. Short of that, at least one of the four should have black text, since an inferior choice should not be a hard-to-override default.

**Comment by lee-dohm** [comment]
Per my post on the linked topic, since this is intended as a discussion and not a task to be performed, I'm closing this unless and until there is some work to be done.
