### ISSUE TITLE
Atom wont fetch package updates -- Always shows error

### ISSUE THREAD

**Issue by mikeerickson** [atom/atom#13928]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When selecting Preferences ->  Updates    

Atom always fails, throws 

### Steps to Reproduce

1. `$ atom --safe`
2. Preferences -> Updates

**Expected behavior:** 

Show list of updated packages...

**Actual behavior:** [What actually happens]

Always throws error (see screenshot below)

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

![image](https://cloud.githubusercontent.com/assets/183153/23574883/f466c8ce-0038-11e7-974f-16713a29d888.png)

### Additional Information

![image](https://cloud.githubusercontent.com/assets/183153/23574870/c713dbdc-0038-11e7-8e80-37cdbbbf234f.png)

**Comment by 50Wliu** [comment]
Please uninstall seti-syntax and/or seti-ui.  The package author has fixed the issue but not yet published a new version for it yet.

**Comment by mikeerickson** [comment]
@50Wliu Awesome, thx a ton!  I am not even using Seti so removing was not impactful :-)
