### ISSUE TITLE
Lots of file tabs will squeeze the main window narrower

### ISSUE THREAD

**Issue by huozhi** [atom/atom#13931]
### Description

The file tabs squeeze the main window becoming smaller after opening too many files.

### Steps to Reproduce

1. Open a folder or project with sidebar opened.
2. Open a lot of files to let each tab became narrow. You' ll see the following.

**Expected behavior:**

![image](https://cloud.githubusercontent.com/assets/4800338/23584288/dae48d9a-0197-11e7-8a7d-0b61caa5c69a.png)

**Actual behavior:**

![image](https://cloud.githubusercontent.com/assets/4800338/23584273/90b83384-0197-11e7-8e1e-f59af7195195.png)

**Reproduces how often:**

Everytime

### Versions

```
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
```

**Comment by 50Wliu** [comment]
This is an issue with whatever UI theme you are using.

**Comment by spohlenz** [comment]
For those of you like me using a UI theme that hasn't been updated, I was able to solve this by adding the following to my user stylesheet:

```css
.tab-bar {
  overflow-x: auto;
  overflow-y: hidden;

  &::-webkit-scrollbar {
    display: none;
  }
}
```
