### ISSUE TITLE
When deleting first line in file diff shows that second line is deleted

### ISSUE THREAD

**Issue by bjubes** [atom/atom#13938]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After editing a file inside a git repo and deleting the top line of a file, the deletion icon in between the line numbers is in between lines 1 and 2 instead of at the top. I assuming this is an oversight, not an intentional design decision.

![capture](https://cloud.githubusercontent.com/assets/7608114/23593959/a0ad250a-01e3-11e7-8122-1e0150f7ce07.PNG)

### Steps to Reproduce

1. Open a git repo in atom
2. delete the top line

**Expected behavior:** 
to see the the indicator before the first line

**Actual behavior:**
the indicator is  between first and second line 

**Reproduces how often:** 100%

### Versions
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Windows 10 v1607

**Comment by 50Wliu** [comment]
what does `git diff` show?  I'm pretty sure we get our information from that.

**Comment by bjubes** [comment]
git diff shows
```
index 7c43f5c..7509ebf 100644
--- a/main.js
+++ b/main.js
@@ -1,4 +1,3 @@
-//app.js
 var express = require('express');
 var app = express();
 var serv = require('http').Server(app);
```
which is correctly showing line one (`//app.js`) deleted before lines 2 and 3

**Comment by 50Wliu** [comment]
Ok, then can you please move this to the [atom/git-diff](https://github.com/atom/git-diff) package?  Thanks!
