### ISSUE TITLE
Opening large project results in excessive network traffic

### ISSUE THREAD

**Issue by Uninen** [atom/atom#13946]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I work with a fairly large (in megabytes) software project that has a git repository of 1.9 Gb and 1,7 Gb working files, totalling 3,6 Gb. I work with VMware Fusion virtual machine that is connected via sshfs to the host running macOS Sierra 10.12.3. When I open this project with Atom, it starts to generate very heavy network traffic, downloading something at times over 50 Mbps. I work on other similar but lighter projects on the same virtual machine but have never seen this but with this one large project.

I have absolutely no experience in analysing or monitoring network traffic and all profiling I managed to do per instructions above didn't give me much clues on what's happening here. Anyways, the traffic seems to be downloaded/streamed by Atom from the vm to the host.

I attached some screenshots from the profiler (because the resulted files were so huge, I can upload them too, of course if needed) and one from tcptrack that tracked network traffic on the virtual machine.

<img width="977" alt="screenshot 2017-03-07 02 39 44" src="https://cloud.githubusercontent.com/assets/43100/23636724/c2b56886-02df-11e7-8bec-200f71ecf0b9.png">

<img width="976" alt="screenshot 2017-03-07 02 39 55" src="https://cloud.githubusercontent.com/assets/43100/23636729/c8e61606-02df-11e7-92c6-9acefa051855.png">

<img width="1137" alt="screenshot 2017-03-07 01 46 41" src="https://cloud.githubusercontent.com/assets/43100/23636737/d60c5af2-02df-11e7-8d7e-4ea4168769a6.png">

( 192.168.1.155 is the vms ip in above)

There may also be some related issues here as the project tree view acts a bit weird, sometimes closing itself when saving, and the git-plus package is so slow with every operation (> 30s) that it's unusable.

This problem reproduces every time I open the project.

### Steps to Reproduce

1. Mount filesystem over sshfs
2. Open large git project folder with atom

### Versions

macOS 10.12.3

Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
OSXFUSE 3.5.5
FUSE library version: 2.9.7

**Comment by lee-dohm** [comment]
I'm not sure I understand what the problem you're reporting is. You say that you're opening a positively gigantic Git repository over a network. (Even if the virtual machine is running on your host OS, because it is connected via SSHFS it is treated as "network traffic".) It sounds like Atom using a lot of network resources in this situation is to be expected? What is it you expect to happen in your described situation?

-----

For comparison, a cloned Linux kernel repository takes 2.6GB of disk space, 1.8GB of which is just in the `.git` directory.

**Comment by Uninen** [comment]
I'm not expecting Atom to actually download the whole project when opening, or is it supposed to?

The problem is that there seems to be this quite heavy network traffic all the time, constantly. It never ends. I'm assuming that the normal thing to happen when opening a folder (project) in Atom is that the file structure is read so the tree view etc works, but surely not the content of every file? I obviously don't have them all open, only a few files at a time :)

And to be clear, I don't know what it actually is "downloading". I have absolutely no idea what is being transferred and why, that's the problem. Atom still opens very quickly and its usable (except the previously mentioned stuff) right off the bat, so I'm baffled what is constantly being transferred and why. The only thing I'm sure about it that it's Atom that is making the traffic.

And for the content of the repo, the weight comes from binaries, mostly images, so there's actually even not so many source files in the repo.

**Comment by lee-dohm** [comment]
Atom does a number of things to provide the features that it does, mostly monitoring all of the files within the Git repository for state changes. It's pretty common that running a file system over a network is not the most efficient use of bandwidth, so I'm not surprised that file operations that don't seem that big of a deal on a local file system might seem like a much larger deal when viewed with a "network bandwidth" lens ... especially when compounded by the fact that you're running a larger than normal Git repository and that it is mostly binary files like images (that Git is known to be inefficient at handling as well). So it may well be that Atom isn't "downloading" the entire contents of your repository ... or maybe the file system is and Atom is just requesting a stat on individual files. Atom literally doesn't know that you're using it across a network, so it is doing the same thing it always does, nothing special.

In any case, I'm not seeing any indication that there is a task to be completed here. If you're wondering what it is that Atom is doing, I would recommend using the `lsof` command (or other utilities) to monitor file access in your repository directory.

**Comment by Uninen** [comment]
Ok, makes sense. This just felt very wrong as I've used the same exact setup for years now, and while the sshfs has had its problems, it nowadays works very well with absolutely no lag nor any other problems in all of my several other (albeit much lighter) projects.

I'll try to do partial clone of the repo or some other voodoo to manage the project. Thanks for your swift replies! :)
