### ISSUE TITLE
packages can't disabled

### ISSUE THREAD

**Issue by WLyKan** [atom/atom#13958]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom packages disable button is not good

### Steps to Reproduce

1. I download packages from github use `git clone`
2. then install use `apm install`
3. install success
4. but when i click disable button in `Setting` - `Packages`, it didn't toggle it's appearance

### Versions

```
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.10.1
Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/settings-view](https://github.com/atom/settings-view) repository.  Thanks!
