### ISSUE TITLE
Atom crashes after working for a few days on a Git repo

### ISSUE THREAD

**Issue by craigfanman** [atom/atom#13959]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm having really weird and frustrating crashes with atom, and I think its do with git. my only fix so far is if I delete the .git folder from the folder, it will then start opening properly in atom. any ideas why this might be?

### Steps to Reproduce

clone a git repo
work on it for a bit
push pull merge etc
after a few days, this folder wont open just crashes

**Expected behavior:** 
the folder should just open like normal

**Actual behavior:** 
this error popup:
[Window Title]
Atom

[Main Instruction]
The editor has crashed

[Content]
Please report this issue to https://github.com/atom/atom

[Close Window] [Reload] [Keep It Open]

**Reproduces how often:**
with a new git repo it will be fine, but after a few days this randomly starts, and then will always happen. 

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

C:\Users\User>atom --version

Atom    : 1.14.4
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Windows 10 64 bit

### Additional Information

Git version 2.12 64 bit

attached DMP file
[7442e06c-1d5a-4524-bc3e-e479d6435fd4.txt](https://github.com/atom/atom/files/827292/7442e06c-1d5a-4524-bc3e-e479d6435fd4.txt)

**Comment by Zireael07** [comment]
Is your git repo a standard repo or are you using git annex, git lfs or other such things?

**Comment by craigfanman** [comment]
hi thanks for replying, its a pretty standard repo as far as I know, not using any of those things, I use bitbucket to host it. the repo isnt that big its 21mb. my git config file looks like this:

[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true

**Comment by 50Wliu** [comment]
Next time the crash happens (and if you have no unsaved changes), can you try opening Atom using `atom --clear-window-state`?  I wonder if that will help.

**Comment by craigfanman** [comment]
Hi, yeah it doesnt completely kill atom, say i have 5 folders, only one of them will crash it, the other 4 work fine. These are all git repos from bitbucket so I'm not sure what the difference is that affects one of them.

**Comment by dustinpoissant** [comment]
My editor crashes each time i try and open a minified JS file.

**Comment by rsese** [comment]
@dustinpoissant that issue with minified JS is https://github.com/atom/atom/issues/979 and is resolved as of 1.15.0-beta3.

**Comment by felipesabino** [comment]
Is it possible to be a corrupted plugin?

My editor was crashing every single time I opened it regardless of folders or anything else. I couldn't even see my configurations or plugins to change something as it just crashes with the message bellow.

![screenshot 2017-03-09 14 37 15](https://cloud.githubusercontent.com/assets/700480/23762885/493e4ae2-04d6-11e7-8927-9d5fc37571bb.png)

I am using version `1.14.4` and tried `atom --clear-window-state` but same thing happens all the time. I uninstalled and installed once but after a few days the same error came back.

I couldn't open any file, preference or settings window. Also, the `Find` and `Packages` menu were not opening, they just highlighted but didn't show any option.

I went to `~/.atom/packages` folder and started removing one by one and opening Atom again, it turns out that when I removed [api-blueprint-preview](https://atom.io/packages/api-blueprint-preview) plugin, it fixed the issue.

**Comment by 50Wliu** [comment]
Hey guys, please don't use this issue for your own crashes.  This issue is specific to the crash that @craigfanman is reporting; namely that Atom is crashing when working on Git projects.  If you'd like to report a crash, please [open a new issue](https://github.com/atom/atom/issues/new).  Thanks!

**Comment by ungb** [comment]
@craigfanman, are you still seeing this issue?  

when running `atom --safe` mode do you still see this issue?  Also can you provide a list of community packages you have installed? 
run: `apm list`, it could help us investigate the issue more or could be related to a community package.
