### ISSUE TITLE
Atom on Windows can't install any packages

### ISSUE THREAD

**Issue by bazzilic** [atom/atom#13971]
### Description

Atom (v1.15.0 ia32) does not install _any_ packages on Windows, saying that native build tools are not available. This happens with packages that do not seem to require any compiling. Moreover, all the required build tools _are_ installed:

```
bazzilic@BAZZILIC $ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 ia32
python 2.7.13
git 2.12.0.windows.1
visual studio 2015
```

However, `apm install --check` fails without stating exactly why.

### Steps to Reproduce

1. Open Atom (v1.15.0 ia32) on Windows 10 x64
2. Try installing or updating any package. E.g., `atom-clock`, which (I checked) is pure JS and CSS, so doesn't need build tools.

**Expected behavior:** The package installs nicely.

**Actual behavior:**
![image](https://cloud.githubusercontent.com/assets/1805832/23786861/3a6fa6e4-05aa-11e7-8b05-475bf8b69362.png)

**Reproduces how often:** Always, since about a month ago

### Versions
```
bazzilic@BAZZILIC $ atom --version

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
```
bazzilic@BAZZILIC $ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 ia32
python 2.7.13
git 2.12.0.windows.1
visual studio 2015
```
Running on Windows 10 Pro x64 (updated to Anniversary Edition). Visual Studio 2015 _with_ C/C++ compilers, with all latest updates. Reproduces on two different machines; both, however, are very similar software-wise.

### Additional Information
I have tried backing up the `~/.atom/` folder and reinstalling Atom from scratch, but it didn't help. One more detail: `~/.atom/` is a symlink to a different location; if that's important.

**Comment by rsese** [comment]
Since you're having trouble installing packages with apm, can you please open this in https://github.com/atom/apm?
