### ISSUE TITLE
Save dialog can appear multiple times

### ISSUE THREAD

**Issue by mjaggard** [atom/atom#13972]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Frequently I middle click on all my open tabs to close them.
When I close a tab that has changes I'm prompted to save but if I try to close it again I'm prompted again.

### Steps to Reproduce

1. Open a document (can be new or existing)
2. Enter some text to change it
3. Close the tab - the save confirmation box appears
4. Close the tab again

**Expected behavior:** [What you expect to happen]
I expect the save dialog to take the focus - like an application modal dialog

**Actual behavior:** [What actually happens]
A second save confirmation box appears on top of the existing one

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
1.5.3

apm  1.6.0
npm  2.13.3
node 0.10.40
python 2.7.12+
git 2.9.3

**Comment by 50Wliu** [comment]
Your Atom version is extremely outdated - please update to the latest version, currently Atom 1.15.0, and try again.  I cannot reproduce this behavior on the latest version.
