### ISSUE TITLE
'Save as' opens a save dialog in a semi-random dir with 'Untitled' as the file name

### ISSUE THREAD

**Issue by benogle** [atom/atom#13978]
### Prerequisites

* In safe mode
* Was unable to find an existing issue
* Seems like it started happening a couple weeks ago. Electron upgrade?

### Description

Save as used to open a save dialog in the directory of the focused file with the file's name as the filename in the dialog. 

Now it opens in the root of the project (most of the time), with the filename as `Untitled`. Also the dialog is much larger than before.

<img width="1108" alt="screen shot 2017-03-10 at 10 52 42 am" src="https://cloud.githubusercontent.com/assets/69169/23808956/9d337cf8-0580-11e7-86e2-756aaaa4aafe.png">

### Steps to Reproduce

1. Open atom in safe mode
2. open a file
3. cmd-shift-s to save as
4. Get kind of useless dialog

**Expected behavior:** Open a dialog in the current directory of the active file, with the name being that of the active file

**Actual behavior:** The above dialog

**Reproduces how often:** 100%

### Versions

On master HEAD as of today: e35a00

**Comment by Ben3eeE** [comment]
On Windows the dialog opens in the root of the project directory with nothing in the file name dialog.
Thanks for the report @benogle. Adding it to the list of potential regressions ⚡️

**Comment by jbt** [comment]
Just chiming in to say that on Ubuntu the dialog has recently been opening in a background(!) window, with no directory or filename set (so it chooses "Recently Used"), so it looks like this affects all platforms similarly.

**Comment by 50Wliu** [comment]
This seems to be a regression in 1.15 that didn't occur in 1.14.

**Comment by umpirsky** [comment]
@50Wliu I can confirm that.

**Comment by ungb** [comment]
I am able to repro as well.

**Comment by theurge14** [comment]
May be related, but this behavior seems to not allow copy and pasting into the filename in this dialog box starting in 1.15.0, had to revert to 1.14.4 to get this back.

**Comment by markaduffy** [comment]
Just noticed this myself. Also noticed dragging a file on to atom, automatically add that files containing folder to project pane.

**Comment by DLaicH** [comment]
I'm also having this issue on Arch Linux, not in safe mode. The file chooser dialog always goes straight to my home directory with a blank filename, and for some reason it always opens on my primary monitor even though the editor is on my second monitor.

**Comment by mbdmbd** [comment]
Confirming what theurge14 said - When saving a new text file on a Mac, it won't let you paste in a filename. Tested atom 1.15.0 in safe mode and 1.16.0-beta0 as well.  Works fine in 1.14.4

**Comment by AlexisJackson** [comment]
This has also been happening to me.
Thanks, @50Wliu for pointing me to this issue.

**Comment by hex007** [comment]
@jbt The save opens in background on Fedora 25 too

**Comment by ryan-p-randall** [comment]
Also cannot paste in a filename on Mac. I'm using Atom 1.15.0 and had no issues with this before the new version.

**Comment by rbu** [comment]
If you are touching the path, could you please make the default Save directory the one that also comes up for Open by default? I had opened issue #6088 about this long ago and it's still not fixed.

**Comment by alexrussell** [comment]
I can tell you that in my experience the "random" directory is not random at all - it is the last one you used for "save as". At least for OSX anyway. It seems that other platforms have other "random" directories, so at a guess Atom is not sending a directory in and the OS is using its best guess at a sensible one for you (OSX = last used, Ubuntu = "Recently Used").

As for the inability to paste form @theurge14, I noticed this too, but even before this came along there were certain common keyboard shortcuts (cmd+a to select all) that simply didn't work. At a guess that's because Electron (or Atom) intercepts keystrokes even if they are the standard OS-provided ones like copy, paste, select all, etc. Not sure how easy it is to tell Electron/Atom to not intercept keystrokes when using the open/save dialogs, and either way should probably be in a separate issue entirely.

**Comment by umpirsky** [comment]
Is this bug in Atom or Electron?

**Comment by cs150bf** [comment]
I suspect this has something to do with the `showSaveDialog` getting broken in version 1.15.0. I reported the problem in issue https://github.com/atom/atom/issues/14109 and wrote some of my findings there.

**Comment by alexrussell** [comment]
Great job @cs150bf for taking the time to look into and fix this issue 👍

**Comment by hex007** [comment]
@cs150bf The save dialog is not focused once open.
