### ISSUE TITLE
Current version shown when update is available

### ISSUE THREAD

**Issue by pbregener** [atom/atom#13988]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When an update is available, this is shown in the "About" view. However, the version number next to the update button lists the currently installed version, and the link to the release notes also points to the old release notes. This does not make sense.  
When clicking the update button, I actually don't even know whether I'm about to install a minor or major update.

### Steps to Reproduce

1. Wait for a new Atom release
2. Go to "About"

**Expected behavior:**
The current version is shown at the top, the latest available version is shown in the "New update" box. The "Restart and install" button will actually install the version that is about to be installed.

**Actual behavior:**
![atomupdate](https://cloud.githubusercontent.com/assets/6407709/23831990/68ddf0e8-072c-11e7-91ff-6966c82f922b.png)

**Reproduces how often:**
100%

### Versions
At least 1.14.x and previous ones. Possibly also master, can't check when on the latest version.
Using Windows 7 and macOS Sierra.

**Comment by 50Wliu** [comment]
This has been fixed starting with Atom 1.16.0-beta0.
