### ISSUE TITLE
src/config.coffee should use _.deepClone from underscore-plus

### ISSUE THREAD

**Issue by anatoli26** [atom/atom#13980]
Subj, just a reminder (following @50Wliu's request) to make a code cleanup. Line 999 in `src/config.coffee` implements its own deep clone function, but `underscore-plus` already has it (accessible as `_.deepClone`), so that one should be used instead of own implementation.

**Comment by adityaYashwanth** [comment]
Hi, I am new here. Here is the pull request for this issue. I hope this is what is expected from this issue.
Please review these changes.
#13987

**Comment by Asutosh989** [comment]
Hi, I am new to open source, and wanted to contribute to same. Since there is a beginner label on this issue, so I wanted to ask, can I start with this issue?

**Comment by 50Wliu** [comment]
Hi @Asutosh989, of course you can!  I would suggest reading the conversation in #13987 and working on the requested changes (specifically, https://github.com/atom/atom/pull/13987#issuecomment-286110823).

**Comment by rohanBagchi** [comment]
@50Wliu 
Just out of curiosity, why are we using `_.deepCopy`? 
We could simply use es6 object destructuring.
```
original = { "foo": "bar" }
copied = {...original}
```
Let me know if I am missing something. Thanks in advance.
btw, I am also new in here.

**Comment by 50Wliu** [comment]
@rohanBagchi I assume that we're deep cloning because the copy's values can be modified and we don't want that to reflect on the original object.

**Comment by cbrit** [comment]
Is this still something that can be worked on?

**Comment by 50Wliu** [comment]
@cbrit Yes, this is still actionable.

**Comment by AryanJ-NYC** [comment]
@50Wliu What actions can a new contributor take since we can't simple replace the local `deepClone()` function with `_.deepClone()?`

**Comment by 50Wliu** [comment]
@AryanJ-NYC Like I said [above](https://github.com/atom/atom/issues/13980#issuecomment-314315439), it would probably help to read [this comment](https://github.com/atom/atom/pull/13987#issuecomment-286110823) in a similar PR.

**Comment by AryanJ-NYC** [comment]
@50Wliu Thank you. I had read the comment but it doesn't go into specifics of the functionality wanted from `color.js`'s color setters. As I understand it, the setter should parse the color prior to setting it while letting a developer use the `this.red = "someHex"` syntax. This can be done by using a leading underscore for the class variables. However, this would break the test (as the tests test for `this.red` and not `this._red`.  Is it OK to change the tests to account for the change in class variable naming convention?

**Comment by 50Wliu** [comment]
@AryanJ-NYC I believe that should be fine.  Do you know how to run tests locally, or would you like me to give you a quick tutorial?

**Comment by AryanJ-NYC** [comment]
@50Wliu I'd greatly appreciate that. I've been trying to run `atom --test path/to/config-spec.coffee`  (as described in [`CONTRIBUTING.md`](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)) but it doesn't work at all.

**Comment by 50Wliu** [comment]
Try: `atom --test spec`.  Then, to only test a subset of the specs (rather than the whole suite!) add an `f` in front of the tests you're interested in, so that they become `fdescribe` or `fit`.

**Comment by AryanJ-NYC** [comment]
Thanks. I tried that and got:

```
➜  atom git:(master) ✗ atom --test spec
Error Downloading Update: Could not get code signature for running application
```
