### ISSUE TITLE
Super slow performance when I enable Linter ( with cow power ) latest version 

### ISSUE THREAD

**Issue by Oblik-Design** [atom/atom#13999]
Linter is at 1.11.23, this issue has been plaguing my works for months, each return on a 500 lines HTML takes 4 seconds to respond, all is good as soon has I disable the Linter, is there a config I'm missing ?? It's now in default mode all the way through , it 's the most downloaded package here !

**Comment by lee-dohm** [comment]
This is something that you'll have to report to the [linter package](https://atom.io/packages/linter). The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
