### ISSUE TITLE
Linux Atom.desktop and unusual behavior.

### ISSUE THREAD

**Issue by Xembie** [atom/atom#13992]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This seems similar to #13733 but for the DEB version.

Unusual behavior if not launched using the bash script installed to /usr/bin/atom.  When launching the binary directly /usr/share/atom/atom, I get the following error below and Atom seems to access contexts from other open windows.  Atom's File->New File would not function.  If it does succeed, touchpad input is killed for some reason.

```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

### Steps to Reproduce

1. With Lubuntu, start Atom through panel.

**Expected behavior:** Client to start and function normally.

**Actual behavior:** Unusual behavior and manipulation of other windows.

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

Lubuntu 16.10
To fix, just edit /usr/share/applications/Atom.desktop and set it to exec /usr/bin/atom

**Comment by rsese** [comment]
> Unusual behavior if not launched using the bash script installed to /usr/bin/atom. When launching the binary directly /usr/share/atom/atom, I get the following error below and Atom seems to access contexts from other open windows. Atom's File->New File would not function. If it does succeed, touchpad input is killed for some reason.
> 
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

I see this error as well on my Lubuntu VM if I try to run `/usr/share/atom/atom` directly from the command line but I didn't have any trouble creating a new file, saving it, etc.  

> With Lubuntu, start Atom through panel.

Just to confirm your steps to reproduce, you're starting Atom from the main panel menu?  And if you do this, you see the same behavior you described above when running `/usr/share/atom/atom` directly (e.g. creating a new file not working, touchpad input problem)?

**Comment by Xembie** [comment]
@rsese Yes, it happens when ran from terminal or panel.

**Comment by rsese** [comment]
Thanks for confirming - I tried again and I'm still unable to reproduce.  I'm able to create new files and save them when running Atom from panel.  I'll go ahead and label as `needs reproduction` in case someone else can give it a try.

**Comment by Xembie** [comment]
#13465 is related.  I think that these problems show up if a previous installation was not uninstalled prior to installing a newer version.

**Comment by Xembie** [comment]
It turns out that these issues show up because syndaemon(touchpad delay) is faulty and interferes with Atom's functionality.  However, the Atom.desktop configuration maybe should use the script at /usr/bin/atom.

**Comment by rsese** [comment]
> I think that these problems show up if a previous installation was not uninstalled prior to installing a newer version.

I had a chance to try it out by installing a new version over a previous version but still couldn't reproduce.

> It turns out that these issues show up because syndaemon(touchpad delay) is faulty and interferes with Atom's functionality.

Glad you figured out what was going on but just to confirm, did this cause the problem with creating new files as well?

**Comment by Xembie** [comment]
@rsese Yes, it did.

**Comment by ravihara** [comment]
The issue occurs even with 1.18.0 version of Atom, when I try to run it on Debian-8 VM using Cinnamon desktop.

**Comment by zspine** [comment]
I am having the same issue:

OS: ubuntu 16.04
Atom: 1.23.3

I have downloaded the tar 'atom-amd64.deb' from release page and extracted and ran it from my home folder '/home/user/atom'. I see this error on terminal every time I exit atom.

btw: I haven't installed these dependencies
`sudo apt install git gconf2 gconf-service libgtk2.0-0 libudev1 libgcrypt20 libnotify4 libxtst6 libnss3 python gvfs-bin xdg-utils libcap2`
