### ISSUE TITLE
After opening file with 16000 lines Atom hangs and there's no way to do smth about it

### ISSUE THREAD

**Issue by beramaks** [atom/atom#14009]
### Description

After opening file with 16000 lines Atom hanged and there is no way to close this file. Even restard and re-install didn't help. It just keeps asking whether to close or keep waiting from time to time. I left it "waiting" for all night and of cource nothing happened.
This bug makes imposible to use this text editor.

### Steps to Reproduce

1. Open file with at least 16000 lines and here you go

### Versions

Latest. Can't get V number, because Atom is unresponsive.

**Comment by lee-dohm** [comment]
Have you taken a look at the [Debugging section of the Atom Flight Manual](http://flight-manual.atom.io/hacking-atom/sections/debugging/)? The section on [clearing saved state](http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state) will allow you to get out of this situation.

Additionally, you can always get the version information by running `atom --version` from the command line as it says in the template.

If you can give us an example of a file that causes Atom to hang, we'd like to take a look. On the latest versions, Atom shouldn't be running into this problem anymore.

**Comment by 50Wliu** [comment]
> I left it "waiting" for all night and of cource nothing happened.

This won't work.  Last I checked, the dialog is blocking and so nothing will run while it's open.

**Comment by Pearyman** [comment]
i have the same problem

**Comment by lee-dohm** [comment]
Thanks for taking the time to contribute!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/14009#issuecomment-286763106. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by lee-dohm** [comment]
@Pearyman please open a new issue and fill out the template with the required information and we'll be happy to take a look at it :+1:
