### ISSUE TITLE
<option> tag is bugged

### ISSUE THREAD

**Issue by ExillustX** [atom/atom#14018]
### Description

If i pick the tag `<option>` from the autocomplete list its going to look like this `<<option value=""></option>`

**Expected behavior:** expected the result gonna be `<option value=""></option>`

**Actual behavior:** `<<option value=""></option>`

**Reproduces how often:** 100%

### Versions

1.15.0 x64, Windows 10 pro - x64: V1607

**Comment by lee-dohm** [comment]
What you're picking isn't an autocompletion suggestion for the option tag, but the [`option` snippet in language-html](https://github.com/atom/language-html/blob/master/snippets/language-html.cson#L248-L250). So when you type `<opt` the [autocomplete-snippets package](https://github.com/atom/autocomplete-snippets) is suggesting the `option` snippet for the `opt` in your text. When you select that expansion, it replaces just the `opt`. If you type `opt` by itself and use the snippet, things will work the way you want.
