### ISSUE TITLE
CSS Auto indentation not working

### ISSUE THREAD

**Issue by DijitulLiam** [atom/atom#14015]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Indentation with: {}, [], () do not work using the CSS syntax.

### Steps to Reproduce

1. Create a new blank file
2. Change the langauge to Atom's default 'CSS' syntax.
3. Create a simple CSS rule

*Where '|' is the I-cursor in Atom, and the indentation setting is set to 'Tabs (4 wide)'...*

**Expected behavior:**

.cssrule'{
'''|
}

**Actual behavior:**

.cssrule'{
|
}

**Reproduces how often:**

This happens for me 100% of the time, in my normal work environment and in safe mode.

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Auto indentation is enabled in the settings, and works for all other langauges I use.

I for some reason, have two 'CSS' languages when changing, although neither work.

![two 'CSS' languages](https://cloud.githubusercontent.com/assets/22833343/23998475/287e44ac-0a4d-11e7-928f-f811d91aa62c.png)

**Comment by rsese** [comment]
Thanks for the report!  Auto-indent issues should be opened in the language specific repository - can you please reopen this issue in https://github.com/atom/language-css?
