### ISSUE TITLE
Uncaught TypeError: Cannot read property 'matches' of undefined

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#14017]
Steps to reproduce:
1. Perform a project-wide search for something that isn't found.
2. Arrow down with the view focused.

/cc @Ben3eeE  @maxbrunsfeld 

**Atom**: 1.17.0-dev-ad6a5ac3b x64
**Electron**: 1.3.14
**OS**: Mac OS X 10.12.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'matches' of undefined

```
At <embedded>:85213

TypeError: Cannot read property 'matches' of undefined
    at ResultsView.moveDown (<embedded>:85213:55)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (<embedded>:18101:35)
    at <embedded>:17845:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (<embedded>:64225:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (<embedded>:64016:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (<embedded>:14953:42)
    at HTMLDocument.<anonymous> (<embedded>:14861:65)
```

### Commands

```
     -4:27.5.0 project-find:show (atom-pane.pane.active)
     -4:25.6.0 core:confirm (input.hidden-input)
  2x -4:24.7.0 project-find:show (div.results-view.focusable-panel)
     -4:20.7.0 core:backspace (input.hidden-input)
     -4:20.1.0 core:confirm (input.hidden-input)
     -4:00.3.0 settings-view:open (div.results-view.focusable-panel)
     -3:51.9.0 find-and-replace:show (div.panels-item)
     -3:51.1.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -3:45.4.0 editor:move-to-end-of-line (input.hidden-input)
     -0:16.6.0 core:move-down (div.results-view.focusable-panel)
```

### Non-Core Packages

```
atom-ternjs 0.16.1 
autocomplete-clang 0.10.0 
autocomplete-cmake 0.3.1 
change-case 0.6.3 
clang-format 1.25.0 
color-picker 2.2.3 
git-pear 1.2.1 
github 0.0.0 
journal 0.0.0 
language-cmake 0.2.0 
language-javascript-jsx 0.3.7 
linter 1.11.21 
linter-clang 3.4.4 
linter-js-standard-jsx 4.1.2 
nuclide 0.207.0 
nvatom 0.11.0 
sort-lines 0.14.0 
switch-header-source 0.22.0 
toggle-quotes 1.0.0 
Zen 0.16.4 
```

**Comment by Ben3eeE** [comment]
Can reproduce on beta but not on stable so it's a regression from the jQuery removal.

**Comment by nathansobo** [comment]
@Ben3eeE In a hurry and just blindly created the issue without realizing it was on `atom/atom` due to the snapshotting code. Should we move this?

**Comment by Ben3eeE** [comment]
@nathansobo Nah I think it's ok. We have the regression tracking to keep track of it and being a regression it's gonna be closed soon anyway 🤞😀  
Just curious about the new snapshot code throwing from core instead of the package ⚡️

**Comment by nathansobo** [comment]
> Just curious about the new snapshot code throwing from core instead of the package

Yeah, I think we're going to need to generate some source maps or something to make production stack traces sane.

**Comment by maxbrunsfeld** [comment]
Closed via https://github.com/atom/find-and-replace/commit/6a3b4ab645846a23865ceb63c68acb699a09774d
