### ISSUE TITLE
Package no loading no responding 

### ISSUE THREAD

**Issue by edrem07** [atom/atom#14025]
installed the editor ....but in the settings-packages install , I can't install any of the packages because is not loading any ...is taking forever to loading .I'm doing something wrong or what ? 
![screenshot 8](https://cloud.githubusercontent.com/assets/18537596/24059555/86849d64-0b1d-11e7-9d25-523430a875ed.png)
This is what I'm dealing with ...ridiculous  about 20 mins now

**Comment by 50Wliu** [comment]
See atom/settings-view#916.  There is a code bug where errors will not be shown.  Please open the developer tools (ctrl-alt-i) and create a new issue on the settings-view repo with the error.
