### ISSUE TITLE
Atom crashes on launch and/or when opening files

### ISSUE THREAD

**Issue by mdtdev** [atom/atom#14033]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom, running on Windows 10, crashes on launch revealing an error message popup:

![image](https://cloud.githubusercontent.com/assets/9751401/24083518/a2bec058-0cae-11e7-9b8f-626fb2565fb3.png)

This happens for command line launches, launches from the Atom icon on the start menu, and from the command line in safe mode. Additionally, if I select reload and the program comes up (it usually does when I select the reload option from the pop-up) then it fails to open files, see this GIF (pop image to a new tab to see full-sized):

![animated_fail](https://cloud.githubusercontent.com/assets/9751401/24083535/f3f08862-0cae-11e7-8d1f-832ba2a99be8.gif)

However, if I change to a new folder at this point Atom, and try to open various files, sometimes a file will open **and at this point Atom's file open behavior will return to normal**, at least until I kill it and restart. Sometimes changing to a different directory makes Atom briefly start normally, but this behavior stops over time; I cannot determine a rule for why some directories work/files open and other do not.

### Steps to Reproduce

I do not expect this to reproduce as it is currently only happening on one of my windows systems, and not on the other. This started with my previously installed Atom, which was working as of about a month or so ago, and failed upon my running it today (this follows the update to 1.15). However, I did a clean install and deleted ~/.atom, so:

1. Do a clean install of Atom, including deleting `~/.atom`
2. Launch Atom
3. That would be it, except you're probably launched!

**Expected behavior:** Expect Atom to open normally without error pop-up and to open files normally.

**Actual behavior:** Error pop-up occurs on launch or on opening files.

**Reproduces how often:** Error message appears almost all of the time, except as noted above.

### Versions

atom --version
>Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm --version
>apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.11
git 2.11.0.windows.3
visual studio

OS/System Info:
>OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
System Manufacturer:       HP
System Model:              750-150
System Type:               x64-based PC

### Additional Information

This is happening on a Windows 10 (home) PC. I have access to a Windows 10 (pro) tablet and the problem does not occur there, at least not so far. **UPDATE: this other computer is running Atom 1.14, not 1.15.** I cannot afford to break this one so I cannot check if this is the cause!

I am willing to help diagnose, but I am not an Atom expert or developer so please spell out what you want me to do. 😄

**Comment by mdtdev** [comment]
Similar to, but not the same as:

https://github.com/file-icons/atom/issues/529
https://github.com/atom/atom/issues/10397 
https://github.com/atom/atom/issues/10717 (requested new issue, hence this!)
https://github.com/atom/atom/issues/13959

**Comment by mdtdev** [comment]
I can now confirm that rolling back to release 1.14.4 does not resolve the issue.

**Comment by rsese** [comment]
> I can now confirm that rolling back to release 1.14.4 does not resolve the issue.

Thanks for confirming :+1:

Can you try [clearing saved state](http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state) and see if that helps?  Run `atom --clear-window-state` from the command line.

Also, are there any crash files in `%LocalAppData%\Temp\Atom Crashes`?

**Comment by mdtdev** [comment]
Well, this is embarrassing, but after the multiple uninstalls and reinstalls the bug has gone back into hiding. 

I also want to note, for the future as this error seems to come up again and again(!), that when the problem was happening, I did try exactly that command: `atom --clear-window-state` and inspection (just now) has revealed no relevant crash files that remained after the multiple uninstall and reinstall processes.

After discovering that 1.14.4 did not resolve the issue on Sunday, I uninstalled that version, deleted the `.atom` directory, rebooted, and basically used other tools since then. My system got shut down yesterday and then today I reinstalled the current version from a fresh download. No error this last time! 

So both happy and sad.

Before I close this bug report, I would like to note that before I posted it in the first place, I did uninstall, delete `~/.atom`, and reboot before reinstalling, so I have no idea why this last power cycle and reinstall fixed things. But I can no longer reproduce the bug. 

Glad I had a .GIF to show above or I might not have believed it happened now. 😑

Thanks for the help!

**Comment by rhengles** [comment]
I am having this problem now 😕

**Comment by rsese** [comment]
@rhengles - can you open a new issue and completely fill out the issue template so we can take a look?

**Comment by rhengles** [comment]
@rsese Thank you. Eventually, I found out that the culprit is not Atom core, but the `github` package. When I disabled it, now I can run Atom again 🎉 

I don't know how to get more details about this crash, and if there is already an issue open on https://github.com/atom/github or not. 😕

**Comment by krizajb** [comment]
Same issue here on linux. It crashed once (after using it for few minutes in total) and wasn't able to get it running ever since. It spawns the 4 processes on each attempt and does nothing.

**Comment by patriksam182** [comment]
I in my case, i was have  delete the files .tags1
