### ISSUE TITLE
atom package list problem.

### ISSUE THREAD

**Issue by GhostChild** [atom/atom#14039]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
![20170321165642](https://cloud.githubusercontent.com/assets/22742106/24140666/d77ef368-0e5b-11e7-8984-5f015abcf363.png)

### Steps to Reproduce

I use widnows 10
and set environment variables "ComSpec" change cmd.exe to powershell
then atom package list can't show anything
always "loading packages ..."
![20170321172958](https://cloud.githubusercontent.com/assets/22742106/24140747/159e80e6-0e5c-11e7-8407-89132473d917.png)

so I change back to cmd.exe
atom everything is going well.

I think the amp.cmd can't run in powershell

In the future, the next windows versions. 
microsoft will set powershell to default cmd
atom need update cmd script to support powershell

thank you.

### Versions
ATOM Versions: 1.15.0 x64
OS:windows 10 1607

**Comment by 50Wliu** [comment]
> In the future, the next windows versions.
> microsoft will set powershell to default cmd

When that happens, we will take appropriate steps to make sure our Windows scripts continue working as intended.  For now though, please keep using cmd.exe.

(Also, the actual error should be hidden in the devtools console: Ctrl+Shift+I to bring it up)

/cc @damieng

**Comment by damieng** [comment]
It is my understanding that Microsoft's change to the default will in fact be at the UI level not by changing comspec as that would break a great many number of packages.

https://blogs.windows.com/windowsexperience/2016/11/17/announcing-windows-10-insider-preview-build-14971-for-pc/#MGoCJCuU0cZLk5DL.97
