### ISSUE TITLE
Deprecated calls - Atom core : Autocomplete provider

### ISSUE THREAD

**Issue by jy95** [atom/atom#14036]
### Description

[Description of the issue]

I use https://atom.io/packages/api-workbench and I often see this message

![bugatom](https://cloud.githubusercontent.com/assets/9306961/24093275/55667ea4-0d53-11e7-9c39-3c7bd4ac6ffd.png)

**Expected behavior:** [What you expect to happen]

I expect this issue to be solved by update but it is not the case.

**Actual behavior:** [What actually happens]

Not solved:

```
atom core (1 deprecation)
Autocomplete provider 'Object(undefined)' returns suggestions with a prefix attribute. 
The prefix attribute is now replacementPrefix and is optional. 
See https://github.com/atom/autocomplete-plus/wiki/Provider-API
AutocompleteManager.deprecateForSuggestion - C:\Users\Jacques\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:484:14
<unknown> - C:\Users\Jacques\AppData\Local\atom\app-1.15.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:341:38
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Each time that Atom seems to check for update

### Versions
Atom : 1.15.0
Electron: 1.3.13
Chrome : 52.
OS : Windows 10 64 bit Education

### Additional Information

Not

**Comment by 50Wliu** [comment]
Please report this to api-workbench instead.  Thanks!

**Comment by jy95** [comment]
I reported here because it is written `atom core ` , not only related to api workbench

**Comment by 50Wliu** [comment]
The detection is not always accurate.

**Comment by jy95** [comment]
No problem, no the first time error lied to me XD
