### ISSUE TITLE
Inconsistent syntax highlighting of transition properties

### ISSUE THREAD

**Issue by johanneskrtek** [atom/atom#14044]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using different keywords as `transition-property` results in different syntax highlighting.

### Steps to Reproduce

1. Use the syntax theme 'One Light'.
2. Create a CSS file.
3. Add the following Code:
```
div {
  transition-property: width;
}

div {
  transition-property: color;
}

div {
  transition-property: background;
}
```
**Expected behavior:** [What you expect to happen]

The keywords `width`, `color` and `background` should have the same syntax highlighting.

**Actual behavior:** [What actually happens]

![bildschirmfoto 2017-03-22 um 10 54 50](https://cloud.githubusercontent.com/assets/419747/24192104/328b0250-0eee-11e7-87fc-ab910d26446b.png)

![bildschirmfoto 2017-03-22 um 10 55 19](https://cloud.githubusercontent.com/assets/419747/24192105/33db41c4-0eee-11e7-9088-693e69534d91.png)

![bildschirmfoto 2017-03-22 um 10 55 36](https://cloud.githubusercontent.com/assets/419747/24192118/3bfe44b4-0eee-11e7-912b-afe3a6ef99c3.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.10.1

### Additional Information

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties) lists `background` as an animated property, it also works in all browsers I have tested so far. Therefore I think it should not be highlighted as invalid. At least `width` and `color` I would suspect to have the same syntax highlighting.

**Comment by 50Wliu** [comment]
Please reopen this on the [language-css](https://github.com/atom/language-css) repository.  Thanks!

**Comment by johanneskrtek** [comment]
Thanks for pointing me to the right place.
