### ISSUE TITLE
suggest the tree-view plugin can user-defined alias name

### ISSUE THREAD

**Issue by gooking** [atom/atom#14043]
hi :

in the version 1.15.0 , just like this screenshot bellow:

![image](https://cloud.githubusercontent.com/assets/7286469/24190092/79bb66f4-0f22-11e7-845d-882c49694ef4.png)

when  i add two different fold where has the same name，in the tree-view ,it is difficulty to specification witch fold is witch.

so , is i can user-defined alias name for the "view" name, it is very easy to difficulty them.

**Comment by 50Wliu** [comment]
Please create a new issue on the [tree-view](https://github.com/atom/tree-view) repository (if one doesn't already exist for your issue) and completely fill out the issue template.  Thanks!
