### ISSUE TITLE
HiDPI Scaling

### ISSUE THREAD

**Issue by ghost** [atom/atom#14046]
I use Atom (1.15) on two 4K displays (15.6 inch laptop and 27 inch desktop) on Linux (Solus OS). While I have changed the window and font scaling in Gnome tweak tools, Atom does not seems to respect that.

Installing 'hidpi' package scales everything within the window but the menu text is still tiny. 

![screenshot from 2017-03-23 11-21-19](https://cloud.githubusercontent.com/assets/18163728/24229957/cbc71658-0fbf-11e7-9f60-882b690d6d2d.png)

I was wondering if there is anything that can be done about it? Window title text is also too small to read. Perhaps integrating a scaling function for both text as well as window contents would be a good idea given that more and more people have high res screens.

**Comment by ghisvail** [comment]
Record the font scaling factor set on GNOME Tweak tool and put in the `Operating System Scale Factor` field in the setting of the `hidpi` package. Restart Atom and it should scale appropriately.
