### ISSUE TITLE
<script> tag in html does not fold

### ISSUE THREAD

**Issue by stibinator** [atom/atom#14042]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`<script>` Tags in html do not fold the same way as other html page elements (`<head>`, `<div>`, etc.) and indeed javascript code blocks ( `function(){}`, `if(){}`, etc… ) do, meaning that long blocks of script can't be folded away.

### Steps to Reproduce

1. open html document containing `<script>` tags
2. hover mouse next to the line numbers where the > symbols allow you to fold your code
3. …
4. dismay!

**Expected behavior:** [What you expect to happen]
**`>`** appears to allow script block to be folded
**Actual behavior:** [What actually happens]
nothing
**Reproduces how often:** [What percentage of the time does it reproduce?]
all the time
### Versions
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3........] - :
npm  3.10.5
node 4.4.5 ia32
python 2.7.11
git 2.10.0.windows.1
visual studio 2015

Windows 7 64
<img width="277" alt="2017-03-22 16_42_45-index html c__users_sdixon_creative cloud files_development_html atom" src="https://cloud.githubusercontent.com/assets/422938/24183922/4cee751a-0f1f-11e7-8259-bf8bc7211f28.png">

**Comment by 50Wliu** [comment]
This is because folding is entirely indentation-based at the moment.  Since you placed the JavaScript at the same indentation level as the `<script>` tag, Atom doesn't recognize it as foldable.
