### ISSUE TITLE
Opening a New Window Looks Weird

### ISSUE THREAD

**Issue by jalenconner** [atom/atom#14045]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When opening a New Window, it opens "inside" the old window. It seems to open a tab instead even though it doesn't look like a normal tab - fonts and colors are weird. Dragging the "tab" out of the old window actually restores normal/expected behavior. I've tried running Atom in Safe Mode and using different UI and Syntax theme. Seems to be something wrong with Core and not a theme or package.

### Steps to Reproduce

EDIT: MORE/UPDATED INFO IN [COMMENT](https://github.com/atom/atom/issues/14045#issuecomment-288519047) BELOW...

Click `File > New Window`

**Expected behavior:**
![screen shot 2017-03-22 at 3 10 45 pm](https://cloud.githubusercontent.com/assets/6537823/24216220/cab455b8-0f11-11e7-8b4a-36d9cb4e261f.png)

**Actual behavior:**
![screen shot 2017-03-22 at 3 09 36 pm](https://cloud.githubusercontent.com/assets/6537823/24216162/949521d8-0f11-11e7-901f-0163036542ab.png)

**Reproduces how often:**
Every time

### Versions
atom --version:
```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
apm --version:
```
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.12.0
```
MacOS version:
`10.12.3`

### Additional Information
Config File:
```
"*":
  "atom-beautify":
    css:
      beautify_on_save: true
      configPath: "~/.csscomb.json"
      default_beautifier: "CSScomb"
    general:
      _analyticsUserId: "d27ee7d6-68e7-428b-8914-7471776d7198"
    html:
      beautify_on_save: true
      default_beautifier: "Pretty Diff"
      indent_size: 2
      wrap_line_length: 0
    markdown:
      beautify_on_save: true
    sass:
      beautify_on_save: true
    scss:
      beautify_on_save: true
      configPath: "~/.csscomb.json"
      default_beautifier: "CSScomb"
      indent_size: 2
    twig:
      beautify_on_save: true
      indent_size: 2
      wrap_line_length: 0
  autoprefixer:
    runOnSave: true
  "color-picker":
    preferredFormat: "HEX"
    uppercaseColorValues: true
  core:
    automaticallyUpdate: false
    closeDeletedFileTabs: true
    customFileTypes:
      "text.html.twig": [
        "html"
      ]
    openEmptyEditorOnStart: false
    projectHome: "/Users/jalenconner/Projects"
    telemetryConsent: "limited"
    themes: [
      "nucleus-dark-ui"
      "duotone-dark-sea-syntax"
    ]
    useCustomTitleBar: true
  "double-tag": {}
  editor:
    autoIndentOnPaste: false
    fontFamily: "Hasklig"
    invisibles:
      eol: " "
    scrollPastEnd: true
    showInvisibles: true
    softWrap: true
    tabType: "soft"
  emmet: {}
  "exception-reporting":
    userId: "971b39b3-f542-abab-e5b7-1a51b6eab907"
  "file-icons": {}
  "genesis-ui":
    distractionFree: {}
  "gist-it":
    newGistsDefaultToPrivate: true
    userToken: "2da3c7eccc51f0a494ad19f688fdcc4407050cdd"
  "git-diff":
    showIconsInEditorGutter: true
  "grammar-selector": {}
  "highlight-selected":
    hideHighlightOnSelectedWord: true
    ignoreCase: true
  "isotope-ui":
    backgroundGradient: true
    fontFamily: "Source Sans Pro"
    lowContrastTooltip: true
    minimalMode: true
  "less-than-slash": {}
  "markdown-preview":
    breakOnSingleNewline: true
    useGitHubStyle: true
  minimap:
    charHeight: 4
    charWidth: 2
    displayPluginsControls: false
    ignoreWhitespacesInTokens: true
    scrollAnimation: true
    textOpacity: 0.3
  "one-dark-ui": {}
  pigments:
    autocompleteSuggestionsFromValue: true
    extendAutocompleteToColorValue: true
    extendAutocompleteToVariables: true
    markerType: "native-dot"
  "predawn-ui":
    colourlessIcons: false
  "project-manager":
    includeGitRepositories: true
    savePathsRelativeToHome: true
    sortBy: "last modified"
  "seti-ui":
    displayIgnored: false
    fileIcons: false
    themeColor: "Green"
  "status-bar":
    fullWidth: false
  tabs:
    enableVcsColoring: true
  "toggle-quotes": {}
  "tree-view":
    alwaysOpenExisting: true
    hideIgnoredNames: true
    hideVcsIgnoredFiles: true
    sortFoldersBeforeFiles: false
  welcome:
    showOnStartup: false
```

**Comment by rsese** [comment]
Do you have Atom in full-screen mode?  If so, do things work normally for you when not in full screen mode?

**Comment by jalenconner** [comment]
@rsese No I do not have atom in full-screen mode.

**Comment by jalenconner** [comment]
So I've figured out what is causing the bug described above. It is this setting under `System Preferences > Dock`

![screen shot 2017-03-22 at 3 49 19 pm](https://cloud.githubusercontent.com/assets/6537823/24217742/40d86f72-0f17-11e7-9766-f38e0aed9455.png)

If it is set to `Manually` or `Full-Screen Only`, everything works like normal. If it is set to `Always`, what I described above will happen.

**Comment by rsese** [comment]
Ohhh interesting - looks like it was set to "In Full Screen Only" for me which is why I could reproduce only in full screen mode.

I poked around a bit more and it looks like there's already an issue for this /cc https://github.com/atom/atom/issues/12690 so feel free to subscribe there for updates.

**Comment by jalenconner** [comment]
@rsese my issue isn't quite the same. He's talking about running Atom in Full-Screen mode, and it turning windows into tabs. I'm not running Atom in Full-Screen mode, and my "tabs" look nothing like his.

**Comment by rsese** [comment]
Hmmm, though they mention full screen mode, it seems to me that the general issue reported is that a new window opens in a tab rather than a new window?  E.g. this issue was closed as a dupe as well /cc https://github.com/atom/atom/issues/13169 which based on the description, matches your issue a bit more closely since there's no mention of full screen mode.

About the tabs appearance, looking at your screenshot and the one in that issue, a difference I see is that it looks like you have the `Use Custom Title Bar` setting enabled but they don't.   If you disable that setting, do you see basically the same thing as reported in https://github.com/atom/atom/issues/12690 and https://github.com/atom/atom/issues/13169?

Let me know if I'm mis-understanding anything.
