### ISSUE TITLE
Add "Copy Path" to file name tab contextual menu

### ISSUE THREAD

**Issue by CoralineAda** [atom/atom#14040]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The options in the contextual menu when control- or right-clicking on a file name tab do not include the ability to copy the file path. The use case for this is when I have a spec file open and I want to paste its path in Terminal. The only workaround is to show the item in the Finder and drag the file into Terminal to get its path.

### Steps to Reproduce

1. Open a file
2. Control- or right-click on the file name in the tab bar
3. View options

**Expected behavior:** [What you expect to happen]

I expect there to be a "Copy path" under "Show in Finder"

**Actual behavior:** [What actually happens]

No such option exists.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0```

**Comment by rsese** [comment]
Hey @CoralineAda :wave:!  This would go in https://github.com/atom/tabs and I checked and see that there's an existing request for this if you want to subscribe there /cc https://github.com/atom/tabs/issues/270.

**Comment by CoralineAda** [comment]
Sorry about that, thanks!
