### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 147.204.6.136:...

### ISSUE THREAD

**Issue by ururekina** [atom/atom#14056]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 147.204.6.136:8080

```
At stream.js:74

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 147.204.6.136:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:176:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
  2x -3:47.3.0 core:copy (input.hidden-input)
     -3:42.9.0 project-find:show (input.hidden-input)
  2x -3:30.5.0 core:backspace (input.hidden-input)
     -3:28.6.0 core:confirm (input.hidden-input)
     -1:58.6.0 key-binding-resolver:toggle (input.hidden-input)
     -1:54.4.0 settings-view:open (input.hidden-input)
     -1:11.6.0 core:backspace (input.hidden-input)
     -0:24.9.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-formatter-jsbeautify 1.1.2 
atom-typescript 11.0.1 
atom-ui5-features 0.2.2 
csslint 1.1.5 
fast-eslint 3.9.0 
jslint 1.5.1 
linter 1.11.21 
linter-eslint 8.1.0 
linter-tslint 0.15.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
* are you behind a proxy?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/14056#issuecomment-289087755. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
