### ISSUE TITLE
update the .zip version

### ISSUE THREAD

**Issue by Jan9th** [atom/atom#14054]
The Docs read "The .zip version will not automatically update".How can I update the version to the latest. 
I have clicked the Check for Updates button , but it does not work. The latest version is 1.15.0 ,but it is 1.13.1 ia32 version on my windows. Must I  [down it](https://github.com/atom/atom/releases/tag/v1.15.0) ?

**Comment by thomasjo** [comment]
Download either the `.exe` or the `.msi` file from https://atom.io/.

**Comment by Jan9th** [comment]
Does it means there is nothing I can do for the .zip version?I means I want to update the .zip ,neither the .exe or the .msi. Just for I have some plugins in it. Thank you for your answer.
