### ISSUE TITLE
how to fix or disable markdown text formatting in editor

### ISSUE THREAD

**Issue by knzudgt** [atom/atom#14058]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In the editor of a markdown document, Atom starts rendering in italics and in pink colour a text following an underline as soon as that text is typed, not considering that it should instead wait for the closing underline, and not considering that the closing underline could never be, since the user could have other intentions.

### Steps to Reproduce

1. Open attached file and change its extension from `txt` to `md`
2. See how text is rendered in the editor following markdown rules from start to line 35
3. See what happens at line 36: the test suddenly turns pink and stays pink until the end of the document, because of the first underline in  `_search_form.html.erb `

**Expected behavior:** [What you expect to happen]

1.   _search_form.html.erb should not be treated as a block of text in italics because it starts with underline, unless until a new underline is inserted at the end of the sentence. It does not happen here, in this post, so it should not happen in Atom.

2. As long as Atoms behaviour differs from markdown editors common behaviour, there should be the opportunity to turn off how Atom render markdown formatting in the editor, like a common markdown editor would do, and let the editor behave as a simple text editor

**Actual behavior:** [What actually happens]
Atom is conceived to give the user the best experience possible rendering markdown formatting with different colours etc in the editor and this is good. However it should not anticipate the user's intentions rendering text in italics when the user instead wanted to start some block of text with an underscore for other purposes.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Often

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS: Ubuntu 14.04 LTS

### Additional Information

_Markdown preview does not experience the same issue, because italics, to be rendered as such, expects a closing underline_
This is also GitHub behaviour as you can notice by the way is rendered here _search_form.html.erb. A punctuation, moreover, would break the rule of `underline` = `start of italics test`. See below:

_search_form.html.erb. _search_form.html.erb. _search_form.html.erb
[extract.txt](https://github.com/atom/atom/files/868124/extract.txt)

**Comment by 50Wliu** [comment]
Disable the language-gfm package.
