### ISSUE TITLE
Atom closes randomly

### ISSUE THREAD

**Issue by Zanndorin** [atom/atom#14066]
I'm using the newest atom and have had this issue since the moment I started using atom. I am using atom with: go-plus, linter, intentions, hyperclick, go-signature-statusbar, busy-signal and go-debug. I have used these tools since I started using atom.

### Description
I write in it. While writing, saving or any interaction really, it randomly closes, but only when I'm doing something i.e. it never crashes when I don't touch it but only have it on in the background. I have tried to look for a crash log etc. but there is nothing. When I open atom again it remembers perfectly which the last letter I typed was and where i typed it.

I'm sitting on Windows 10.

I have no idea what to do about it and have stopped using atom except for special occurrences.

**Comment by arcticicestudio** [comment]
It's easier to analyze your problem if you'd fill out the issue template. There are missing information like your version of Atom, your installed packaged and if you'd tried to run Atom in `--safe` mode to see if it also happens when all third-party packages are disabled.

**Comment by Zanndorin** [comment]
The safe mode gives me no real usage scenarios. I was just fishing for information if there was a log about what is happening / why it is closing.

1.15 x64 Windows 10 is the version, I think.

**Comment by arcticicestudio** [comment]
Well, the `--safe` mode exists to see if problems are related to Atom Core or any community package.
If it is a community package there will probably no logs anyway.
> When I open atom again it remembers perfectly which the last letter I typed was and where i typed it.

This may indicate that Atom works fine, but there is a package which causes a fatal exception so Atom's *recover* feature jumps in and saves the current state.

You should provide the output from `apm --list` and `atom --version` so a Atom team member may help to track the origin of the crash.

**Comment by Zanndorin** [comment]
`apm list`
```Built-in Atom Packages (89)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.9.1
├── one-light-ui@1.9.1
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.2
├── archive-view@0.62.2
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.15.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.34.2
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.0
├── background-tips@0.26.1
├── bookmarks@0.44.1
├── bracket-matcher@0.85.2
├── command-palette@0.40.1
├── deprecation-cop@0.56.2
├── dev-live-reload@0.47.0
├── encoding-selector@0.23.1
├── exception-reporting@0.41.0
├── find-and-replace@0.206.3
├── fuzzy-finder@1.4.1
├── git-diff@1.3.1
├── go-to-line@0.32.0
├── grammar-selector@0.49.1
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.36.1
├── line-ending-selector@0.6.1
├── link@0.31.2
├── markdown-preview@0.159.6
├── metrics@1.1.3
├── notifications@0.66.2
├── open-on-github@1.2.1
├── package-generator@1.1.0
├── settings-view@0.247.0
├── snippets@1.0.5
├── spell-check@0.70.2
├── status-bar@1.8.1
├── styleguide@0.49.2
├── symbols-view@0.114.0
├── tabs@0.104.1
├── timecop@0.34.0
├── tree-view@0.214.1
├── update-package-dependencies@0.10.0
├── welcome@0.36.0
├── whitespace@0.36.2
├── wrap-guide@0.39.0
├── language-c@0.56.0
├── language-clojure@0.22.2
├── language-coffee-script@0.48.5
├── language-csharp@0.14.2
├── language-css@0.42.0
├── language-gfm@0.88.1
├── language-git@0.19.0
├── language-go@0.43.1
├── language-html@0.47.2
├── language-hyperlink@0.16.1
├── language-java@0.26.0
├── language-javascript@0.126.1
├── language-json@0.18.3
├── language-less@0.30.1
├── language-make@0.22.3
├── language-mustache@0.13.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.4
├── language-property-list@0.9.0
├── language-python@0.45.2
├── language-ruby@0.70.5
├── language-ruby-on-rails@0.25.2
├── language-sass@0.57.1
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.3
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.16
└── language-yaml@0.28.0

Community Packages (10) C:\Users\max\.atom\packages
├── busy-signal@1.3.0
├── go-debug@1.2.0
├── go-plus@5.3.4
├── go-signature-statusbar@1.2.0
├── hyperclick@0.0.40
├── intentions@1.1.2
├── linter@2.1.2
├── linter-govet@0.1.5
├── linter-ui-default@1.2.1
└── platformio-ide-terminal@2.5.0
```
`atom` 
 ```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
I'll check if I can find any use from it in safe-mode

**Comment by 50Wliu** [comment]
We'll need to know if the issue happens in safe mode in order to further triage this.

**Comment by zer09** [comment]
I got same issue, also installed go-plus and its dependencies using the proton-mode config.
It will just suddenly close while editing without a warning or something.

I also posted this issue at here [discuss.atom.io](https://discuss.atom.io/t/atom-will-suddenly-close-randomly/41282) but didn't get any reply.

**Comment by zer09** [comment]
Hello,

I opened two instance of atom today with the --safe. but both of them suddenly closed at the same time, even I am not editing on the second one.

BTW where i can find the atom logs?

**Comment by djsell** [comment]
I experience similar issues, and I'm also using go-plus.  Perhaps.

**Comment by rsese** [comment]
> BTW where i can find the atom logs?

You can get crash logs in `%TEMP%\Atom Crashes` on Windows or through Console.app on macOS:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs

**Comment by cryptologica** [comment]
Having the same problem. Atom just randomly closes. I don't ever lose work but it's super annoying!
I also have go-plus installed. 
There's no crash log, only an operation_log.txt?

**Comment by hyacinthus** [comment]
[operation_log.txt](https://github.com/atom/atom/files/978024/operation_log.txt)

+1 , and the log here.

**Comment by pushc6** [comment]
Did anyone get this resolved? I too have go-plus and it crashes regularly on my windows 10 machine, but the OS X version seems fine.

**Comment by djsell** [comment]
I "fixed" it by installing Visual Studio Code with the vscode-go extension.  Not a single crash since; works like a dream!

**Comment by hyacinthus** [comment]
Aha, I also switch to VS Code last month , and feel more smooth and easy to use!

**Comment by karbe** [comment]
I have the same issue and might have additional info: For me, is also crashes when I use go-plus, but in my last project there was NO crash, whereas in my other projects it crashed frequently. The only difference that I can think of: I didn't write tests in my last project. Could that be related somehow?

**Comment by rover886** [comment]
Shifted to Visual Studio Code with the vscode-go extension. atom crashed in `--safe` mode also

**Comment by rover886** [comment]
@djsell and @hyacinthus what other useful extensions do you installed with it?

**Comment by hyacinthus** [comment]
@rover886  SETTINGS SYNC    and it's report:
beautify - Version :1.1.1
code-settings-sync - Version :2.8.2
EditorConfig - Version :0.9.4
githistory - Version :0.2.2
gitlens - Version :4.3.2
Go - Version :0.6.62
JavaScriptSnippets - Version :1.4.1
Material-theme - Version :2.9.8
sass-indented - Version :1.4.1
vetur - Version :0.9.3
vim - Version :0.9.0
vscode-apielements - Version :0.6.7
vscode-docker - Version :0.0.16
vscode-eslint - Version :1.2.11
vscode-icons - Version :7.10.1
vscode-markdownlint - Version :0.10.0
vscode-todo-highlight - Version :0.5.8


All these are for golang or js.

**Comment by TomerHeber** [comment]
Occurs on Windows 7 as well - with go-plus.
I worked with 4 different machines some are Windows 7 some are Windows 10. All use go-plus, all crash.
