### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by pleabargain** [atom/atom#14060]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
segmentation fault: 
atom: line 130: 27885 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
Failed to get crash dump id.
Report Id: 

[Description of the issue]
seg fault
### Steps to Reproduce

1. [First Step]
2K lines
2K single words
wrapping commas and " using regex
2. [Second Step]
find regex $
add ,"
crash
3. [and so on...]

**Expected behavior:** [What you expect to happen]
wrap the end of the words with ,"
**Actual behavior:** [What actually happens]
crash
**Reproduces how often:** [What percentage of the time does it reproduce?]
every time
### Versions
atom --version
Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information
crashed once
used xkill
started again
tried to use regex on 2K words
crashed again

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report @pleabargain!  Just to confirm, this is a problem with regex find and replace?

**Comment by pleabargain** [comment]
yes, it's a problem with regex find and replace

**Comment by rsese** [comment]
Thanks for confirming :bow:  If you don't mind, can you re-open this in https://github.com/atom/find-and-replace?  That's the repository for issues about find and replace.
