### ISSUE TITLE
Option to sort Command Palette by Most Recently / Frequently Used commands

### ISSUE THREAD

**Issue by jm3** [atom/atom#14067]
### feature request

option to sort the **Command Palette** by most frequently used commands in decreasing order.

**Comment by toddmc1** [comment]
👍

**Comment by rsese** [comment]
Thanks for contributing @jm3!  It looks like there's an existing request for sorting by most recently used commands in the [command palette repository](https://github.com/atom/command-palette), you can subscribe there for updates /cc https://github.com/atom/command-palette/issues/18.  Sorting by most frequent commands could be another separate request though, you can open an issue for that in the command palette repository as well.

Thanks again :bow:
