### ISSUE TITLE
[1493:0324/153213:WARNING:archive.cc(144)] Opening /home/travis/atom/usr/share/atom-beta/resources/electron.asar/browser/api/exports/babel-plugin-/home/travis/atom/usr/share/atom-beta/resources/app.asar: FILE_ERROR_NOT_A_DIRECTORY - Error output ATOM_CHANNEL=beta builds on Travis CI

### ISSUE THREAD

**Issue by viddo** [atom/atom#14061]
* [x] Put an X between the brackets on this line if you have done all of the following:
    [x] ~~Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode~~ only happens on Travis CI
    [x] ~~Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/~~ only happens on Travis CI
    [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Builds with `ATOM_CHANNEL=beta` outputs tons of warnings on Travis CI, which in some causes the build to break/abort.

### Steps to Reproduce

1. Create a new package, e.g. `apm init -p your-pkg-name` and push to Github account
2. Setup Travis according to the official atom/ci docs: https://github.com/atom/ci#travis-ci
3. Push a change to master to trigger Travis

**Expected behavior:**
Same output on `ATOM_CHANNEL=beta` as on `ATOM_CHANNEL=stable`, e.g. https://travis-ci.org/viddo/atom-test-travis/builds/214687988 (top 2 builds): https://s3.amazonaws.com/archive.travis-ci.org/jobs/214687990/log.txt

**Actual behavior:**
The build output is almost the same, with the difference that there's an error repeated ~1k times (for an project with a single spec case) on `ATOM_CHANNEL=beta` e.g. https://s3.amazonaws.com/archive.travis-ci.org/jobs/214687992/log.txt (3rd build of https://travis-ci.org/viddo/atom-test-travis/builds/214687988):
```bash
...
[1493:0324/153213:WARNING:archive.cc(144)] Opening /home/travis/atom/usr/share/atom-beta/resources/electron.asar/browser/api/exports/babel-plugin-/home/travis/atom/usr/share/atom-beta/resources/app.asar: FILE_ERROR_NOT_A_DIRECTORY
[1493:0324/153213:WARNING:archive.cc(144)] Opening /home/travis/atom/usr/share/atom-beta/resources/electron.asar/browser/api/exports/babel-plugin-/home/travis/atom/usr/share/atom-beta/resources/app.asar: FILE_ERROR_NOT_A_DIRECTORY
[1493:0324/153213:WARNING:archive.cc(144)] Opening /home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/babel-plugin-/home/travis/atom/usr/share/atom-beta/resources/app.asar: FILE_ERROR_NOT_A_DIRECTORY
[1493:0324/153213:WARNING:archive.cc(144)] Opening /home/travis/atom/usr/share/atom-beta/resources/app.asar/node_modules/babel-plugin-/home/travis/atom/usr/share/atom-beta/resources/app.asar: FILE_ERROR_NOT_A_DIRECTORY
...
```

Even if the spec passed the error output is always there, and it seems that if there is more code in a project more error output like above are printed to the console, which in some Travis builds causes the build to err due to too much output:

```
...
[1634:0326/154808:WARNING:archive.cc(144)] Opening /home/travis/atom/usr/share/atom-beta/resources/electron.asar/renderer/api/exports/babel-plugin-/home/travis/atom/usr/share/atom-beta/resources/app.asar: FILE_ERROR_NOT_A_DIRECTORY


The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

This happened on my project where I first noticed this, https://travis-ci.org/viddo/atom-textual-velocity/builds/214512510

**Reproduces how often:**
100% on `ATOM_CHANNEL=beta` (both Linux and OSX)

### Versions

(from build output):
```
Downloading latest Atom release...
Using Atom version:
Atom    : 1.16.0-beta0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Using APM version:
```

### Additional Information
- The empty package to reproduce the error: https://travis-ci.org/viddo/atom-test-travis
- The original build where I noticed this: https://travis-ci.org/viddo/atom-textual-velocity/builds/214512510
- Other packages where I've also found this error:
  - https://travis-ci.org/DavidLGoldberg/qolor/jobs/214331591
  - https://travis-ci.org/AtomLinter/linter-swiftlint/jobs/212210237
  - https://travis-ci.org/AtomLinter/linter-golinter/jobs/212627124
  - https://travis-ci.org/subesokun/atom-tree-view-git-status/jobs/214424086
  - https://travis-ci.org/OmniSharp/omnisharp-atom/jobs/212228757
  - _any project which have `ATOM_CHANNEL=beta` set really, found them by searching for recently updated projects https://github.com/search?p=3&q=ATOM_CHANNEL%3Dbeta&type=Commits&utf8=%E2%9C%93_

**Comment by viddo** [comment]
This can be reproduced following https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image 

I'm using MacOSX Sierra (10.12.3, if that matters):

```bash
docker run --name travis-debug -dit quay.io/travisci/travis-ruby /sbin/init
docker exec -it travis-debug bash -l
su - travis

git clone https://github.com/viddo/atom-textual-velocity.git
cd atom-textual/velocity
export TRAVIS_OS_NAME=linux
export APM_TEST_PACKAGES=""
export ATOM_LINT_WITH_BUNDLED_NODE="true"
export ATOM_CHANNEL=beta
curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh -x
```

The output is the same as already reported above, and can be seen in the referenced logs.

**Comment by viddo** [comment]
Warning message seems to origin from https://github.com/electron/electron/blob/79346f1ac56c4cb7837947ce1025db47d6550036/atom/common/asar/archive.cc#L144-L145

**Comment by viddo** [comment]
Another observation: looking through build history of the mentioned repos above, this started happening for builds using Atom v1.16.0-beta0, which indicates that it should be something that was released in https://github.com/atom/atom/releases/tag/v1.16.0-beta0

**Comment by 50Wliu** [comment]
/cc @joefitzgerald I believe you were seeing this as well?
It's also happening on some Appveyor builds.

**Comment by joefitzgerald** [comment]
@50Wliu yup, all my builds are failing exclusively on the beta channel on linux: https://travis-ci.org/joefitzgerald/go-plus/builds

**Comment by josteinbf** [comment]
I have seen a similar error message on Win7 with 1.15 and 1.16.0-beta0:

```
C:\Users\josteinf>atom --safe -f

[6456:0323/100818:WARNING:archive.cc(144)] Opening file:\C:\Users\josteinf\AppDa
ta\Local\atom\app-1.15.0\resources\app.asar: FILE_ERROR_FAILED
```

It has been reported previously: #14049 . Is this related?

**Comment by viddo** [comment]
It seems like this was finally fixed as of https://github.com/atom/ci/pull/73 🎉 
E.g. working builds: https://travis-ci.org/viddo/atom-textual-velocity/builds/245251426
