### ISSUE TITLE
Markdown Preview + HTML can manipulate Atom itself

### ISSUE THREAD

**Issue by yellowblood** [atom/atom#14071]
![image](https://cloud.githubusercontent.com/assets/1921800/24353176/1b531f36-12f5-11e7-9d18-6b1c1e8d993c.png)

Woo hoo!

**Comment by rsese** [comment]
Thanks for the report!  Since this issue is related to Markdown preview, can you re-open in https://github.com/atom/markdown-preview and completely fill out the issue template in the new issue?

**Comment by 50Wliu** [comment]
Already filed at https://github.com/atom/markdown-preview/issues/276.
