### ISSUE TITLE
Cannot find and jump to the JavaScript methods in some cases

### ISSUE THREAD

**Issue by neiloox** [atom/atom#14087]
### Prerequisites

* [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In the cases below, Atom cannot find and jump to the correct JavaScript methods by Command+R:
1. Cannot find and jump to the methods used "allman" style and defined in a JavaScript class.
2. Cannot find and jump to the methods defined by arrow function.
3. Cannot find and jump to the methods defined by "const", but identify the "const" keyword as a method.
4. Can find and jump to the methods defined by "let", but identify the "let" keyword as a method either.

### Steps to Reproduce

Save the code below as a *.js file, and use Command+R.
```
class Test{
    haha() {
        console.log('haha');
    }

    case1()
    {
        console.log('Case 3: used "allman" style and defined in a class');
    }
}

var fn = function() {
    console.log('fn1');
};

var case2 = () => {
    console.log('Case 2: defined by arrow function');
};

const case3 = function() {
    console.log('Case 3: defined by "const"');
};

let case4 = function() {
    console.log('Case 4: defined by "let"');
};

```

**Expected behavior:**

All the cases in description can be found and jumped to the correct methods.

**Actual behavior:**

Case 1 to 4 are not found or not correct by Command+R.
![Actual Cases](http://i.imgur.com/ZjSI3ZX.png)

**Reproduces how often:**
Always.

### Versions

```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.10.1
```

### Additional Information
Nothing.

**Comment by rsese** [comment]
Thanks for the report @neiloox - can you re-open this issue in the https://github.com/atom/symbols-view repository?  There may already be existing issues for some of the cases you mention however e.g. https://github.com/atom/symbols-view/issues/174.

**Comment by neiloox** [comment]
OK, I reopened it. Thank you.
