### ISSUE TITLE
The thickness of font is not consistent.

### ISSUE THREAD

**Issue by zkostree** [atom/atom#14082]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Sometimes, when I type some variables or keywords (e.g. const, extern), I found that the thickness of font is not consistent.

### Steps to Reproduce

I don't know how to reproduce this issue by specific steps. I just write the code and then it happens sometimes.  I have changed it to several different font type. But it didn't work. 

![Thickness Problem](http://i.imgur.com/YCPfNjP.png)

**Reproduces how often:** 60%

### Versions

OS : Windows 7 (64-bit)
Version : 1.15.0
UI Theme : One Dark
Syntax Theme : Monokai (by kevinsawicki)
The fonts I have already tried : 
1. Droid Sans Mono
2. DejaVu Mono
3. Code New Roman
4. Source Code Pro
5. CamingoCode

### Additional Information

No

I appreciate any help. Thanks.

**Comment by 50Wliu** [comment]
Can you zoom in on the different parts of the code using Magnifier and share the screenshots here?  You can access Magnifier using the <kbd>Windows</kbd>+<kbd>=</kbd> shortcut.

**Comment by chrisvio** [comment]
#10185

**Comment by zkostree** [comment]
Hi 50Wliu,

Thanks for your comment! I have tried to use the Windows Magnifier. But when I used the PrintScreen, the part where I zoomed in was not able to be captured. I don't know why, sorry. However, after the zoom in, I could still obviously see that the thickness of code were different .


Hi Chrisvio,

Thanks for the information, I will keep following these issues.

**Comment by 50Wliu** [comment]
Hmm, that's odd, it worked for me:
![example-zoom-in](https://cloud.githubusercontent.com/assets/2766036/24658881/0dc9ea0a-1919-11e7-8a4e-f51a2b750f49.png)

Anyway, even if it isn't for you, does the inconsistent font look like the above picture, or with less variation in color, like the one below?
![image](https://cloud.githubusercontent.com/assets/2766036/24658961/4d6060f4-1919-11e7-8e71-1f9ab764ee05.png)

**Comment by zkostree** [comment]
Hi 50Wliu,

I captured the screen successfully after the zoom in. You can check it on below image.
It looks like the second one which you post.
![](http://imgur.com/a/MP8uy)

**Comment by 50Wliu** [comment]
Ok, thanks for the response.  This is due to Chromium not applying subpixel antialiasing on the text and instead falling back to grayscale antialiasing.  There's not much we can do about this other than upgrade to newer Chromium/Electron versions and seeing if their antialiasing strategy has improved.

We're in the progress of updating to Electron 1.6 right now, which at least for me has provided significant improvements in the crispness of the text.
