### ISSUE TITLE
Skipped tests in Jasmine spec runner

### ISSUE THREAD

**Issue by diesire** [atom/atom#14089]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Show skipped tests (`xit`) in Jasmine spec runner

---

Running a test with `fit`
```coffeescript
fit "pass", ->
    expect(true).toEqual true
```
shows how many tests were performed and were skipped

![image](https://cloud.githubusercontent.com/assets/1185591/24452446/907109b0-1483-11e7-88dc-1d14eff17c5f.png)

But skipping some tests using `xit`
```coffeescript
xit "pass", ->
    expect(true).toEqual false
```
does not show how many tests were skipped

![image](https://cloud.githubusercontent.com/assets/1185591/24452543/13a71982-1484-11e7-8a96-c834f3bd5dd6.png)

### Steps to Reproduce

1. Skip a test in a package spec
2. Run package spec

**Expected behavior:** Show number of skipped tests using `xit`

**Actual behavior:** Does not show number of skipped tests using `xit`

**Reproduces how often:** 100%

### Versions

Windows7 x64, atom v1.16.0-beta0, apm v1.16.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by diesire** [comment]
I have found another related issue. If title contains a hash `#` sometimes the test is skipped depending the position

```coffee
describe "In atom spec runner", ->
  it "pass", ->
    expect(true).toEqual true

  it "fails", ->
    expect(true).toEqual false

  xit "skipped1 but not shown", ->
    expect(1).toEqual 2

  it "#skipped2 because hash", ->
    expect(2).toEqual 3

  it "# skipped3 because hash", ->
    expect(3).toEqual 4

  it "#", ->
    #skipped
    expect(4).toEqual 5

  it "skipped5 because hash# ", ->
    expect(5).toEqual 6

  it "skipped6 because hash#", ->
    expect(6).toEqual 7

  it "skipped7 because hash #", ->
    expect(7).toEqual 8

```

![image](https://cloud.githubusercontent.com/assets/1185591/24503389/2ebe1b52-1552-11e7-8ad2-72dcf6ffc447.png)

**Comment by 50Wliu** [comment]
The hash behavior is intended, though honestly I think it's unnecessary because of the `xit` support.

**Comment by diesire** [comment]
Is there any documentation or rule about hash behaviour? Is not working all the times and there is nothing in [Writing specs documentation](http://flight-manual.atom.io/hacking-atom/sections/writing-specs/)

About `xit`, there is no visual feedback, no `(4 skipped)` message, silent. The problem is to forget some test skipped (just an additional `x`)

**Comment by 50Wliu** [comment]
> Is there any documentation or rule about hash behaviour?

I don't think so.  I discovered it by accident as well.

**Comment by kevinsawicki** [comment]
> Is there any documentation or rule about hash behaviour?

https://github.com/atom/jasmine-tagged
