### ISSUE TITLE
APM fails to build certain node modules under windows

### ISSUE THREAD

**Issue by Sorunome** [atom/atom#14105]
It seems like APM fails to build certain node modules underwindows, I have unfortunatelly only one example but it seems to be effecting gyp / node-pre-gyp.

More information / debug output: https://github.com/Sorunome/arduino-upload/issues/8

**Comment by rsese** [comment]
Thanks for the report @Sorunome - can you re-open this issue (if there's isn't an existing issue for the problem) in https://github.com/atom/apm and fully fill out the issue template?  Thanks!
