### ISSUE TITLE
Blurred screen when Windows dialog is moved around

### ISSUE THREAD

**Issue by neildocs** [atom/atom#14114]
# ATOM Test

## Environment

- Version:  ATOM 1.15 X64
- OS: Win 7

## Issue

When saving a file, if the `Save As...` dialog is moved, the blured screen is frustrating.
![1](https://cloud.githubusercontent.com/assets/14267903/24583414/c3561088-1716-11e7-8e5d-e82f7480ae12.jpg)

**Comment by damieng** [comment]
Not able to reproduce here on atom-dev/Windows 10/x64.  Possibly Windows 7 specific or a driver issue.

**Comment by neildocs** [comment]
Hi Damien,

Thanks for quick response.  I tried on another Win-7 laptop and getting the
same issue.  Seems not an issur with driver.  Maybe Win-7 specific.

Thanks!

**Comment by Ben3eeE** [comment]
@damieng I believe this is https://github.com/electron/electron/issues/1821. I have the same issue on Windows 7 with the classic and basic themes.

**Comment by damieng** [comment]
@neildocs you can probably solve this by switching to the Aero theme which will enable the DWM composition engine that is required by Atom (and other Electron applications)

**Comment by neildocs** [comment]
@Damien, will give it a shot. Thanks for the tip.
