### ISSUE TITLE
Atom menu bar sometimes disappear

### ISSUE THREAD

**Issue by AnthonyWC** [atom/atom#14112]
### Description

Atom menu bar sometimes disappear; requiring restarting atom to fix.

### Steps to Reproduce
Hover mouse over menu bar.

### Versions
```
antho@alto  ~  lsb_release -a                                                       
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

antho@alto  ~  atom -v                                                           
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

antho@alto  ~  apm -v                                                               
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.7.4

```

**Comment by rsese** [comment]
Thanks for the report!  In the future, please fill out the issue template completely - is this behavior reproducible in safe mode (`atom --safe`)?  Also just to confirm, you're referring to the menu with the `File`, `Edit`, `View`, etc. menu items?

**Comment by AnthonyWC** [comment]
Didn't try with atom --safe because it is fairly intermittent and may have to do w/ files open with sshfs.  I will try to run atom with debug console to see if any error comes up if it happens again.

And yes the menu with File/Edi (I am using Unity/Ubuntu)

**Comment by rsese** [comment]
> Didn't try with atom --safe because it is fairly intermittent and may have to do w/ files open with sshfs.

Gotcha :+1:  If you find out more details please let us know.

I noted a few issues about the menu bar in Ubuntu but they weren't intermittent e.g. https://github.com/atom/atom/issues/3114 so your issue seems different.

**Comment by johnramsden** [comment]
I'm not sure if I'm talking about the same thing, but I i'm unable to get my menu bar to show up. Using the `window: toggle-menu-bar` command shows a pop up telling me to press alt to toggle the menu bar, but alt doesn't do anything. I even tried remapping the toggle menu bar command to another key map and running it but that just shows the pop-up as well. 

I tried checking the auto hide menu bar button, and tried unchecking it but it doesn't make any difference.

I tried running it in safe mode and the same problem occurs. I'm running KDE Plasma 5 on Arch Linux.

I also noticed a `nohup.out` file in my `~/.atom/` directory full of 

```
(electron:14635): LIBDBUSMENU-GLIB-WARNING **: About to Show called on an item wihtout submenus.  We're ignoring it.
```
I'm running the [official arch package](https://www.archlinux.org/packages/community/x86_64/atom/).

**Comment by 50Wliu** [comment]
> I'm running the official arch package.

That might be the "official" arch package, but it is in fact an unofficial distribution of Atom that has been known to cause many hard-to-diagnose bugs, mostly because of its insistence in using mismatched components.  I would highly recommend that you uninstall it and reinstall from https://atom.io.

**Comment by johnramsden** [comment]
I tested with the current github release, same problem.

**Comment by AnthonyWC** [comment]
Going to revisit this issue since it is still happening intermittently and it doesn't have anything to do w/ sshfs remote mount (which causes a separate issue; mainly it hangs).

**Comment by ChALkeR** [comment]
@johnramsden Atom dbusmenu malfunction under KDE is is an Electron bug, reported here: https://github.com/electron/electron/issues/8455.

Try to:
 * Reproduce the same issue with just `electron` instead of `atom`
 * Use `ELECTRON_FORCE_WINDOW_MENU_BAR=1` work-around do disable electron dbusmenu.

**Comment by mojoaxel** [comment]
This is propably an electron issue: https://github.com/electron/electron/issues/10297
