### ISSUE TITLE
Cant update/ install packages or theme

### ISSUE THREAD

**Issue by nakulbende** [atom/atom#14111]
![image](https://cloud.githubusercontent.com/assets/8712050/24580519/551ea5c4-16d7-11e7-8700-a5eb3f109b31.png)

I tried safe mode, and it works fine. I do not know what the issue is. I do not have seti UI installed, which was the common fix for this problem. 

Console says: 

C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\settings-view\lib\installed-packages-panel.js:328 Fetching local packages failed. Error: Fetching local packages failed.
    at C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:97:19
    at exit (C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:69:16)
    at triggerExitCallback (C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\src\buffered-process.js:303:11)
    at C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\src\buffered-process.js:324:11
    at Socket.<anonymous> (C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\src\buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)(anonymous function) @ C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\settings-view\lib\installed-packages-panel.js:328
C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\settings-view\lib\installed-packages-panel.js:329 Uncaught (in promise) TypeError: Cannot read property 'hide' of undefined(…)
C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:176 Uncaught (in promise) Error: Fetching outdated packages and themes failed.(…)
C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:176 Uncaught (in promise) Error: Fetching outdated packages and themes failed.(…)
C:\Users\Nakul Bende\AppData\Local\atom\app-1.14.1\resources\app.asar\node_modules\settings-view\lib\themes-panel.js:393 Uncaught (in promise) TypeError: Cannot read property 'hide' of undefined(…)

**Comment by rsese** [comment]
> I tried safe mode, and it works fine. I do not know what the issue is. I do not have seti UI installed, which was the common fix for this problem.

Have you tried disabling all your community packages one by one to see which one is causing the problem?

**Comment by crucialfelix** [comment]
Same problem, same stack trace.

I don't have "The system cannot find the path specified" though.

Fetch is attempted twice:

```
Fetching outdated packages and themes failed.Hide output…
undefined

Fetching outdated packages and themes failed.Hide output…
undefined
```

I _can_ upgrade individual packages on the command line:

```sh
(mattermind)mattermind ❯ apm upgrade prettier-atom                                               ⏎
Package Updates Available (1)
└── prettier-atom 0.23.1 -> 0.29.0

Would you like to install these updates? (yes) yes
```

but cannot update all packages with `apm upgrade`

```sh
(mattermind)mattermind ❯ apm upgrade
undefined
```

Note the undefined.

There are no non-core packages in the stack trace. It is BufferedProcess that is throwing the error, and this is a call to apm. So maybe this should be filed with apm.

**Comment by crucialfelix** [comment]
See https://github.com/atom/apm/issues/620

**Comment by rsese** [comment]
Thanks again for your issue @nakulbende!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/14111#issuecomment-291221144. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.  About the problem specifically, you also might want to check for something similar as described in https://github.com/atom/apm/issues/620#issuecomment-302456284.  

(It looks like you found that you were hitting that issue with seti-syntax @crucialfelix, glad you have that sorted out.)
