### ISSUE TITLE
windows crashes consistantly with netio.sys bsod when accessing package repositories through atom settings menu with windows proxy enabled and running through charles

### ISSUE THREAD

**Issue by noahholley** [atom/atom#14121]
Defect Description:

When the user is accessing the atom package repositories through the atom settings menu and as a prerequisite has a browser session running through a windows proxy through Charles windows crashes with a bsod and a netio.sys error 

Steps to Reproduce:

1. install charles proxy
2. install google chrome
3. setup windows proxy
4. create recording settings in charles with ssl enabled on a arbitrary test server
5. open the install packages menu in atom
6. search for and install a package
7. note windows crashes with bsod netio.sys error

Expected behavior:

windows does not crash when accessing package repository in atom while simultaneously recording proxy traffic

Actual behavior:

windows does not crash when accessing package repository in atom while simultaneously recording proxy traffic

Reproducible:  

100%

**Comment by damieng** [comment]
I would recommend reaching out to the authors of Charles given that this error doesn't occur when going through other proxy servers (e.g. Fiddler)

**Comment by noahholley** [comment]
ah i see thanks for looking into it.

**Comment by damieng** [comment]
In general a blue screen of death happens at kernel level - applications should never be able to cause them (security risk).  In this case it's the network driver which I can only assume Charles is intercepting/filtering in some way that interferes with it.
