### ISSUE TITLE
Atom shows .gitignore'd files in ctrl-p

### ISSUE THREAD

**Issue by brigand** [atom/atom#14128]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom shows files in my 'lib' directory in ctrl-p despite them being in .gitignore. It doesn't
show files in node_modules (also in .gitignore).

Image taken in `--safe` mode:

![image of .gitignore and atom editor](https://i.imgur.com/xHAKcrr.png)

### Steps to Reproduce

I'm not able to reproduce it in a test case so far. Hopefully you can point me in the right
direction.

**Expected behavior:**

It shouldn't show files in the lib directory in ctrl-p.

**Actual behavior:** [What actually happens]

It shows files in the lib directory in ctrl-p.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always in this project.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Latest OSX version.

```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

Let me know if you need more information, but it happens in `--safe` mode.

**Comment by rsese** [comment]
@brigand can you share your .gitignore file and confirm where the .gitignore file is located in your directory tree? 

> I'm not able to reproduce it in a test case so far. Hopefully you can point me in the right
> direction.

Just to confirm, you mean that you can reproduce it in this particular project only?

**Comment by rsese** [comment]
Oh sorry - if you don't mind, can you re-create this issue in https://github.com/atom/fuzzy-finder @brigand so we have it in the right place?  There are a few open issues about .gitgnore behavior that you can check out too e.g. https://github.com/atom/fuzzy-finder/issues/120.

**Comment by brigand** [comment]
Thanks exactly the situation (opened in a sub directory), thanks!
