### ISSUE TITLE
Error Installing eslint-config-airbnb/legacy

### ISSUE THREAD

**Issue by kevinhylant** [atom/atom#14122]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

* Failure to install the package `eslint-config-airbnb/legacy`

### Steps to Reproduce

1. Go to install packages
2. Search for & attempt to install eslint-config-airbnb/legacy

**Expected behavior:** Install package

**Actual behavior:**
I get the following error message
```
Installing “eslint-config-airbnb/legacy” failed.Hide output…
Couldn't clone https://github.com/eslint-config-airbnb/legacy.git or git+ssh://git@github.com/eslint-config-airbnb/legacy.git
```

**Reproduces how often:**  Always

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.10
git 2.11.0

MacOS Sierra 10.12.2

Brand new installs of each OS & of Atom

**Comment by 50Wliu** [comment]
That is because 1) eslint-config-airbnb/legacy is not a valid package name (so it does not and cannot exist as an Atom package), and 2) it is not an existing Git repository.
