### ISSUE TITLE
Find in buffer with only in selection option doesn't work correctly

### ISSUE THREAD

**Issue by kolbma** [atom/atom#14129]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The selection in the buffer is sometimes not recognized.
So it can happen that the text is not found at all because it is used some old selection before.
Or it can happen that no selection is recognized and text gets replaced in the whole buffer.

### Steps to Reproduce

1. Select some text in the buffer
2. Press Ctrl + F to open the Find in buffer dialog.
3. Switch on the "Only in selection" option
4. Enter some text in the find line
5. See that the counter of found indexes is not correct.
6. If it is correct, play around with selections in the buffer, soon you'll see the problem.

**Expected behavior:** 

That it recognizes the changed selection in buffer without editing the find field.

**Actual behavior:** 

You have to disable the "Only in selection" option, do the selection in buffer and enable the option again. Or you have to change the find text field.

**Reproduces how often:** 

Every time.

### Versions

Windows 10 / also on Linux

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.15.3
npm  3.10.5
node 4.4.5 ia32
python 3.6.0
git 2.9.2.windows.1
visual studio 2015

**Comment by 50Wliu** [comment]
Please reopen this on the find-and-replace repository if an issue does not already exist.
