### ISSUE TITLE
No text in the UI

### ISSUE THREAD

**Issue by Leva7** [atom/atom#14127]
### Prerequisites

* [x] Done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

One day I launched Atom only to find out that all UI text is gone. By that I mean that the code editor is fine, but anywhere else (including preferences) there's no text.
![image](https://cloud.githubusercontent.com/assets/15035286/24643135/4ff76b26-1925-11e7-9fdb-d39d1a990e11.png)
I haven't done any changes to Atom since the last time I launched it and it everything was fine back then.

### Steps to Reproduce

1. Launch Atom

**Expected behavior:** Text in the UI should render as usual

**Actual behavior:** It doesn't (see the screenshot for details)

**Reproduces how often:** Always occurs

### Versions

Running Ubuntu 16.04, issue seen in Atom 1.14.6 and still persists after an upgrade to the latest 1.15.0
```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

It's not any packages that cause this issue, because I've tried moving the `~/.atom` folder away

**Comment by 50Wliu** [comment]
What about starting Atom with `atom --disable-gpu`?

**Comment by Leva7** [comment]
@50Wliu Same issue

**Comment by ungb** [comment]
@Leva7 are you running atom on a vm?

**Comment by Leva7** [comment]
@ungb Nope, just regular Ubuntu

**Comment by ungb** [comment]
@Leva7 are you still seeing this issue?  One thing to check if chrome and other programs behave the same or differently.  I am unable to repro this on my vm or physical ubuntu machine.

**Comment by Leva7** [comment]
@ungb Yes, the issue persists to this day. Currently, I have:
```
Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by 50Wliu** [comment]
Hmm, so this issue survived the Electron upgrade.  @Leva7 would you mind temporarily installing Chromium to check if the issue reproduces in Chromium?  That way we can rule out whether it's an upstream Chromium issue or not.

**Comment by Leva7** [comment]
@50Wliu Did that. The browser seems fine, there's text in the UI and in the webview

**Comment by Leva7** [comment]
I finally realized what the issue was. I had a Segoe UI font on my Ubuntu machine which had only 7 glyphs. Don't remember where I've acquired it. But removing it from the CSS temporarily allowed the text to render. I'll just delete this broken font from my machine and it should work fine
