### ISSUE TITLE
Scala code not being highlighted

### ISSUE THREAD

**Issue by kaustubhhiware** [atom/atom#14120]
Opening files with extension `.scala` has no highlighting.

Output of `atom --version` is as follows : 

```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by 50Wliu** [comment]
You will need to install a package that provides syntax highlighting for Scala files.  https://atom.io/packages/language-scala appears to be popular.

**Comment by kaustubhhiware** [comment]
Shouldn't this be supported in the default atom editor ?

**Comment by 50Wliu** [comment]
See https://github.com/atom/atom/issues/13932#issuecomment-284562845.
