### ISSUE TITLE
Got error when installing packages

### ISSUE THREAD

**Issue by wyujie** [atom/atom#14132]
I download atom from the official website, and install it on my new machine. But I cannot install any packages. The following are the error message:

> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.4.0
> gyp info using node@4.4.5 | darwin | x64
> gyp http GET https://atom.io/download/electron/v1.3.13/iojs-v1.3.13.tar.gz
> gyp WARN install got an error, rolling back install
> gyp ERR! install error 
> gyp ERR! stack Error: connect ETIMEDOUT 52.216.82.152:443
> gyp ERR! stack     at Object.exports._errnoException (util.js:870:11)
> gyp ERR! stack     at exports._exceptionWithHostPort (util.js:893:20)
> gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
> gyp ERR! System Darwin 16.1.0
> gyp ERR! command "/private/var/folders/9t/q9qfv2gx1rg3y5grwd1wzq_h0000gn/T/AppTranslocation/76BA49A4-BB19-47E6-9F9F-79AF191E933D/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/9t/q9qfv2gx1rg3y5grwd1wzq_h0000gn/T/AppTranslocation/76BA49A4-BB19-47E6-9F9F-79AF191E933D/d/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.3.13" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
> gyp ERR! cwd /Users/yujie/.atom
> gyp ERR! node -v v4.4.5
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok 

Does it look like server errors?  I visit 52.216.82.152:443, and it directs to amazon website.

Thx very much for your attention.

**Comment by rsese** [comment]
Thanks for the report!  Can you re-open this issue and fill out the issue template completely in https://github.com/atom/apm/issues so we have it in the right repository?
