### ISSUE TITLE
Support for grammar scopeName based activation hooks

### ISSUE THREAD

**Issue by MoritzKn** [atom/atom#14148]
At the moment Atom supports `activationHooks` like `${packageName}:grammar-used`, but these only work on package level and not on the level of the actual grammar. This has two downsides:
1. If a package defines multiple grammars, the `activationHooks` will be triggered for any grammar. An example for this is the `language-java` package.
2. if multiple packages define the same grammar, a package that should be activated if this grammar is used has to add `activationHooks` for every package and update the `activationHooks` if a new package implements that grammar. An example for this is the `language-javascript` and `language-babel` package.

I think it wound be best to have another activation hook that works on the `scopeName` of a grammar. Something like: `${scopeName}:grammar-scope-used`.

**Comment by MoritzKn** [comment]
If this is a desired extension of the API, I would try to implement it myself. I just have a few questions upfront:
* Is my proposed solution a suitable way?
* I suppose the hook has to be triggered in the phase where new text is tokenized. In which part of the code base does this happen? Could someone point me in the right direction, please?

**Comment by iolsen** [comment]
@damieng this is related to your recent work. What are your thoughts?

**Comment by damieng** [comment]
This isn't specifically tied to enhancedScopes although we could re-use the package.json field definition to potentially facilitate this.

**Comment by MoritzKn** [comment]
@damieng Could you explain what the `enhancedScopes` property is about (or point me in the right direction)? I saw about that in the language-server packages...

**Comment by damieng** [comment]
It is a declaration on the packages.json that will in the future be used to recommend packages for people based on the scopes they are editing (that part does not yet exist)

**Comment by MoritzKn** [comment]
Sounds interesting! But i think using this rather then an actual activation hock for my proposed use case, would be confusing. 
Apart from that, what do you think of the idea in general? And where would be the best place to trigger such a hook?

**Comment by Aerijo** [comment]
I may be missing something, but wouldn't it be easy just to add the emitter to the same place as the existing grammar name emitter?

E.g., in `atom/src/workspace.js` line 1269
```
  handleGrammarUsed (grammar) {
    if (grammar == null) { return }
    this.packageManager.triggerActivationHook(`${grammar.scopeName}:root-scope-used`); // <- add this
    return this.packageManager.triggerActivationHook(`${grammar.packageName}:grammar-used`);
  }
```
As far as I can tell, the return value isn't used for anything (it's `undefined`, unless the hook is empty in which case it returns an error. And the hook is never empty). I tested the above change just now, and it seems to work fine.

This addition would really help packages that want to use grammar hooks. It also makes it more in line with the services API, which is also package-agnostic. It shouldn't matter who is providing the grammar, just what the root scope is.

**Comment by MoritzKn** [comment]
@Aerijo This looks exactly like what I imaged. Are you going to create a pull request for this? If you don't want to, I am happy to do it as well.

**Comment by Aerijo** [comment]
I'll make the PR now
