### ISSUE TITLE
Atom constantly crashes when it starts on 16.04

### ISSUE THREAD

**Issue by patmcd** [atom/atom#14144]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Ever since updating to 1.15 I have not been able to start atom. I window does not even appear. it's a fairly instant crash. I have removed the package. purged the package. mv ~/atom to ~/atom-backup. Re-Install/Installed dozens of times

### Steps to Reproduce

1. start atom
( or start atom in safe mode)

**Expected behavior:** atom to start

**Actual behavior:** atom does not start and crashes. A window never even appears.

**Reproduces how often:**  everytime

### Versions
atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm -v
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.7.4

(uname 4.4.0-72-generic)
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Trudko** [comment]
By any chance does multiple instances of Atom opens for you? This  is what has been happening to me lately. The solution was to remove .atom folder(which ofc removes your packages too).

**Comment by patmcd** [comment]
After several hours of frustration I finally got this fixed.

I `rm -rf .atom`
I then also` rm -rf .atom-backup` (for the first time -- the most odd thing is that this operation took > ~ 3 minutes on a modern machine.)
removed 'atom' via apt

Fresh install, and it finally opened.

The most odd thing to point out is the time it took to remove the backup. I think maybe Atom was still trying to launch from there in someway in an odd link, but, it was obviously trying to load something huge at launch (I also have like 15MB .crash files from atom)

**Comment by thomasjo** [comment]
Closing the issue since it has been resolved.

**Comment by dmbiel** [comment]
Tnx! Helps!
