### ISSUE TITLE
 Stops responding if an open (large) file gets edited by other program (ex. GitHub or notepad)

### ISSUE THREAD

**Issue by dennorske** [atom/atom#14140]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom doesn't want to cooperate with me in the following case: 
I have a large file open, about 41.000 lines with averagely 130 characters on each.
I go into git, I  commit my stuff, and checks out to a different branch.
The file is changed by git. When Atom detects that, it freezes.
Was easily re-createable in safe mode, by opening the file, entering notepad opening the same file, do changes and save.
_I couldn't find any related issues, sorry if I have missed any_

### Steps to Reproduce

1. Open Atom, load a rather large file. (_Mine was 41k lines, 1920 kb in size_)
2. Open a second text editor, open the same file, and add one character (or just do any change to it). Save the file
3. Switch back to Atom, and see that the editor hangs for quite a long time. I am haven't been able to return to my work without closing the editor first (unresponsive).

**Expected behavior:** I expected the file to be re-buffered such as in other text editors. (_at least get prompted about it_)

**Actual behavior:** The program freezes and goes unresponsive. 

**Reproduces how often:** 95-100%

### Versions
```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

I have deleted the storage folder, reinstalled Atom, attempted safe mode. Reproduces every time, no matter wich OS. _(Ubuntu 16.04 64-bit and Windows 10 Education 64-bit)_

**Comment by rsese** [comment]
There's an issue about the behavior when switching branches with Git /cc https://github.com/atom/atom/issues/4982 but I don't think there's any specifically about freezing/hanging on as a result of switching branches or editing the same large file in another editor simultaneously.

Out of curiosity, do you see the same behavior if you copy the large file outside of a git repository and then edit the copy in Notepad?

**Comment by dennorske** [comment]
Issue you referenced is not the same as I'm having (it seems) as I'm able to freeze the application for several minutes. 
I am able to reproduce the issue by both safe mode and normal startup, and I even tested a clean install again to make sure it's possible to reproduce.

The file I used this time was located under My Documents (Windows), and under ~/home (Ubuntu).
Screenshot attached below.

![image](https://cloud.githubusercontent.com/assets/3287543/24731518/f552690e-1a6a-11e7-8b1a-00e1606740d2.png)

**Comment by rsese** [comment]
Yeah I don't think it's the same issue either, was just noting another issue related to switching git branches :+1:

Is the repository private or would you be able to share it so we can try to reproduce?  Or the file itself?  If not, I can try to create a test file based on your description ("a large file open, about 41.000 lines with averagely 130 characters on each.").

Oh also, what kind of file is it, a log file?

**Comment by dennorske** [comment]
Unfortunately it's a private repository. It's a Pawn language file (Server Game-mode for GTA San Andreas Multiplayer Mod), so basically a script.

Encoding is UTF-8. Besides that I don't think I have any other information available. I'll happily check up things if you need.

**Comment by Martez-Conner** [comment]
My issue is similar but it happens when I open large files in general without the use of another program being involved.

**Comment by rsese** [comment]
@dennorske - I had a chance to test things out a bit but couldn't reproduce on my Windows 10 machine with a test file.  I used this script to create a file with 50,000 lines with a line length 130 characters:

https://gist.github.com/rsese/b8bc0131566f2ed9acadd462df28be6e

Then:

1. open the file in Atom
2. open the file in Notepad and change a few characters towards the middle of the file
3. went back to the file open in Atom

At this point, I didn't notice any lag and I could see the edit in Atom ok.

Would you be able to generate the same test file and let me know if you see the same freezing behavior?

Lastly, I was reminded about a performance issue on Windows with spell-check /cc https://github.com/atom/spell-check/issues/190.  Though you do mention that you see the freezing on Ubuntu as well, can you try disabling spell-check and see if notice any difference?

**Comment by dennorske** [comment]
I also tried to check encoding for both files, so I tried with sublime. Opened in windows 1252 in both editors, commented something like 

>//sadfasfgfgsfgsdfgdsfgsd

on one random line, and spellchecking is off, I am in safe mode - this happens in windows. Unable to test Linux as my installation is gone nuts after some bad changes by me on it, so have to reinstall linux to test that. @rsese
