### ISSUE TITLE
Propsal: `atom.whenShellEnvironmentLoaded()`

### ISSUE THREAD

**Issue by matthewwithanm** [atom/atom#14155]
### Description of the Change

Currently, there's no way for a package to know if the shell environment has been loaded other than delaying its activation. You can use `atom.packages.onDidTriggerActivationHook()` to listen for `"'core:loaded-shell-environment"`, but it may have already been triggered. In Nuclide, we currently have [a package][1] whose entire point is to resolve a promise when it's activated by the hook 😝

The proposal is to add a new AtomEnvironment method that allows you to register a callback to be invoked immediately if the shell environment is already loaded or, otherwise, once it loads:

`atom.whenShellEnvironmentLoaded(cb: () => void): Disposable`

### Alternate Designs

There are currently three precedents for this kind of event handling in Atom:

1. `onDidBlah()` functions which only invoke their callbacks on events subsequent to registration (of which there are implied to be multiple)
2. `observeBlah()` functions which provide the semantics we're after but (currently, at least) imply multiple events
3. `getBlahPromise()` provides similar semantics. (This isn't a strong precedent though—the only example I'm aware of is `atom.views.getNextUpdatePromise()`). Looking ahead, though, if more promise-returning methods are added, we'll almost certainly require cancelability at some point. That would probably mean adding cancelation tokens which would fragment the APIs between cancelation tokens and disposables.

The proposed version fits with the established API patterns (callback-accepting, disposable-returning functions) but establishes a new prefix ("when") that has the same semantics as `observeBlah()` functions but is used when the callback will only be called once.

cc @maxbrunsfeld @nathansobo 

[1]: https://github.com/facebook/nuclide/tree/v0.216.0/pkg/nuclide-loaded-shell-hook

**Comment by maxbrunsfeld** [comment]
This seems reasonable to me. @nathansobo has the strongest vision for how this sort of thing should be named and such. Let's discuss Monday morning!

**Comment by matthewwithanm** [comment]
Another naming convention possibility is `onBlahReady()` 😊

**Comment by nathansobo** [comment]
We've concluded that the `atom.whenShellEnvironmentLoaded` approach is a go.
