### ISSUE TITLE
AutoSave doesn't work

### ISSUE THREAD

**Issue by srseven** [atom/atom#14154]
[X]

AutoSave doesn't work even though I have check marked 'enabled' check button.

**Expected behavior:**AutoSave should work.

**Actual behavior:** AutoSave doesn't work.

**Reproduces how often:**100%

Atom Version: 1.15.0
`apm` Version: 1.15.3

**Comment by lee-dohm** [comment]
@srseven As @50Wliu pointed out in https://github.com/atom/atom/issues/14153, we require the issue template to be filled out. One of the requirements is a list of steps to reproduce the problem, which you haven't included. From the meager information that you have included, we cannot reproduce the problem. If you want us to help you with the problem you're having, you'll have to give us more information.

We consider repeatedly opening issues with a lack of information like this to be a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it is considered harassment. You may consider this an official warning.
