### ISSUE TITLE
Duplicate tabs can be opened

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#14184]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When opening files (eg from the Tree View, which is where I experienced this), it is possible to open the same file multiple times.

### Steps to Reproduce

1. Rapidly double-click on the same file in the Tree View

**Expected behavior:** The file to open once, become permanent (if applicable), and further double-clicks on the file to refocus the editor.

**Actual behavior:** The file opens multiple times.

**Reproduces how often:** Almost 100%.  @nathansobo mentioned that it's more likely to occur the faster you click, probably because of the new async methods.

### Versions

```
Atom    : 1.18.0-dev-e8ae30217
Electron: 1.6.5
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.12.0.windows.1
visual studio 2015
```

### Additional Information

![multiple-files](https://cloud.githubusercontent.com/assets/2766036/24919739/a16fc5ba-1eb2-11e7-846d-eeeed3a46472.gif)

/cc: @nathansobo @maxbrunsfeld @matthewwithanm

**Comment by ungb** [comment]
Able to repro this too.  

This occurs even if you click away and then double click the file again.  

![clicking](https://cloud.githubusercontent.com/assets/5624870/24968973/fb9cbbf4-1f63-11e7-8f10-fafae4be85e3.gif)
