### ISSUE TITLE
Renaming an open file and then saving it recreates the file with the original filename

### ISSUE THREAD

**Issue by rpiotaix** [atom/atom#14187]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When you rename a file opened in atom using tree view or right click on the tab, the file is renamed but the file name of the opened file is not updated.
At the end:
- if you continue editing and save, you edited the wrong file and re-created a file with the original name
- if you close the tab without editing, atom if you want to save your work

### Steps to Reproduce
1. Create a file named "file1"
2. Add some text and save
3. Rename by right-clicking on the tab > rename to "file2"
4a. close the tab -> atom asks to save the file. choosing yes will create a file named "file1"
4b. add some text and press Ctrl+S -> will create a file named "file1" with the updated content. "file2" will be the old state of "file1"

**Expected behavior:** Rename action shoud be picked up by the editor and the open file should be the "new" one

**Actual behavior:** Only moves the file but atom ignores it

**Reproduces how often:** 100%

### Versions

Debian Stretch
Atom 1.15 x64
Blank atom state (.atom directory removed before testing)

**Comment by BinaryMuse** [comment]
I *believe* this should be fixed by https://github.com/atom/tree-view/pull/1049

**Comment by rpiotaix** [comment]
Yes!
Fixed in atom-beta and tree-view 0.217.
Thanks and sorry for the noise.
