### ISSUE TITLE
I'm getting a periodic "this editor is not responding" dialog while I'm reading the most recent

### ISSUE THREAD

**Issue by jbarnette** [atom/atom#1418]
I'm getting a periodic "this editor is not responding" dialog while I'm reading the most recent release notes.

Atom Version: 0.44.0
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Atom/0.44.0 Atom-Shell/0.7.6 Safari/537.36
Debug Info:
```json
{}
```

**Comment by benogle** [comment]
I never see this anymore. If anyone still has this issue, please comment.

**Comment by markgarrigan** [comment]
This happens to me basically every 10 minutes. It's really fun. No packages are installed. No custom anything. Fresh install of atom. The only thing i've done is install shell commands. OS X 10.11.2

**Comment by benogle** [comment]
@markgarrigan on any dir? Or only on some directories? Can you try the [atom beta](https://atom.io/beta)?

**Comment by markgarrigan** [comment]
Any directory. I reinstalled and it worked for a few days but now it's doing it again.

I'll try the Beta.

**Comment by benogle** [comment]
Also, make sure to try safe mode.

**Comment by markgarrigan** [comment]
Just started happening on Beta version.

I'll try safe mode now.

Typical work flow...

Edit... Save... Click on Chrome to test something... Command + Tab and select Atom from OS X app selector... Click on Atom and it's frozen. Then I just wait until it says not responding. Then I quit Atom.

![screen shot 2016-01-05 at 4 25 22 pm](https://cloud.githubusercontent.com/assets/422391/12129404/06863ebc-b3c9-11e5-88d6-90b3844f953e.png)

**Comment by markgarrigan** [comment]
Just happened again in safe mode.

This time, and it could be completely unrelated, but I had JUST hit play on the Spotify app. Switched back to the desktop where Atom Beta was running and Atom was frozen.

**Comment by Subhash-Balla** [comment]
Yep! It used to happen whenever I tried to open atom. If you're running atom from the shortcut created by the installer then here's my solution that worked for me. If the shortcut's target was to "C:\Users\YOUR-USERNAME\AppData\Local\atom\Update.exe --processStart atom.exe" then change it to "C:\Users\YOUR-USERNAME\AppData\Local\atom\app-1.9.9\atom.exe" and also tick the "Run as administrator" option in shortcut properties. I was using Windows 10 32-bit.
