### ISSUE TITLE
Updates check is broken, gives error

### ISSUE THREAD

**Issue by JonasT** [atom/atom#14182]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The "Updates" tab gives me this error:

```
Fetching outdated packages and themes failed.Hide output…

undefined
```
![atom_package_update_failure](https://cloud.githubusercontent.com/assets/1573352/24962808/3a88f524-1f9d-11e7-9e2c-cf5e9f1f21ba.png)

### Steps to Reproduce

1. Open "Preferences"
2. Click "Updates"

**Expected behavior:** list of updates and not an error

**Actual behavior:** error

**Reproduces how often:** always

### Versions

```
$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
$ uname -a
Linux cyberman 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
```

**Comment by 50Wliu** [comment]
Please uninstall seti-ui and seti-syntax.  If you do not have one of those two packages installed, just say so and I'll reopen the issue.

**Comment by JonasT** [comment]
@50Wliu I don't understand, isn't testing in safe mode supposed to make the installed packages irrelevant?

Nevertheless, I checked and I don't have any seti-* packages installed on my laptop where I'm also seeing this (I get this update error both on my desktop with Fedora 24 and Laptop with Ubuntu 17.04 beta).

**Comment by JonasT** [comment]
Actually, I did and I just missed them in the list. After removal, this is indeed fixed.

Is this some sort of limitation of safe mode that it was still broken in it? I always assumed the point of safe mode was not to load up any packages to avoid such problems when testing

**Comment by 50Wliu** [comment]
Well, `apm update` has to...check installed packages for updates, right?  `apm` is separate from `atom`.  And seti-ui/seti-syntax break the update mechanism due to an unexpected entry in their package.json.

**Comment by JonasT** [comment]
Ah that makes sense. Sorry for my confusion then :smile: and thanks for the quick and helpful responses!
