### ISSUE TITLE
KDE Activities and Atom

### ISSUE THREAD

**Issue by nmartignoni** [atom/atom#14196]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am using Atom on a Kubuntu 16.04, unfortunetly Atom can seem to be able to be open in several activities on KDE.

### Steps to Reproduce

1. Open Atom in one activty
2. Create a new activity
3. Open Atom in the new activity

**Expected behavior:**

Atom should open in the new activity.

**Actual behavior:**

Atom open in the first activity.

**Reproduces how often:**

100%

### Versions

`atom --version`:
```
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
`apm --version` :
```
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.7.4
```

I am using a kubuntu 16.04.

**Comment by rsese** [comment]
It seems like activities are basically like Ubuntu workspaces with more functionality?  If so, I think this is the same/super similar to https://github.com/atom/atom/issues/11610?

**Comment by nmartignoni** [comment]
Indeed, it seems to be the same problems.

**Comment by rsese** [comment]
👍 - I'll go ahead and close this one as a duplicate.
