### ISSUE TITLE
Issue building Atom on Ubuntu 16.04 - cannot find scrollbar-style-observer

### ISSUE THREAD

**Issue by shanept** [atom/atom#14192]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am trying to build atom from source on Ubuntu 16.04 and it builds without issue, however upon running the atom binary, I am presented with a grey screen and the following error:

    Uncaught Error: Cannot find module '../build/Release/scrollbar-style-observer.node'

I have:
 - Tried cleaning the build: `script/clean`
 - Tried cleaning the NPM cache: `rm -rf ~/.npm && npm cache clear`
 - Deleted my local git repo and started again
 - Tried safe mode

### Steps to Reproduce

1. script/clean
2. script/build

**Expected behavior:** Atom opens as per usual

**Actual behavior:** Atom presents me with a completely grey screen. Developer console gives me the above error.

**Reproduces how often:** Every time I open atom, even after a new build.

### Versions
    atom --version
    Atom    : 1.18.0-dev-f4fceb0
    Electron: 1.3.14
    Chrome  : 52.0.2743.82
    Node    : 6.5.0
    
    apm --version
    apm  1.17.0
    npm  3.10.5
    node 6.9.5 x64
    python 2.7.12
    git 2.7.4
    
    uname -a
    Linux ProgrammerWS 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    
    cat /etc/issue
    Ubuntu 16.04 LTS \n \l

**Comment by ungb** [comment]
@shanept are you building this with `script/build --create-debian-package` and then installing it? Or running the binary in out directory?  I tried building it and running it my ubuntu vm and didn't see any issues starting up. 

I'm running Ubuntu 16.04.1

**uname -a**:
```
Linux ubuntu 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by shanept** [comment]
@ungb I am using the following command:

    script/build --install=~/Documents/atom-build/

Then I execute bin/atom in that directory.

**Comment by ungb** [comment]
I tried to repro this with same exact steps and atom came up and was working.  

Where is the repo checked out to?  any chance you can provide info on the path?  I'm not sure if this matters or not.  

Also, wondering why `uname` returns a different version.  

Are you able to install atom from the official deb build?

**Comment by shanept** [comment]
Hmm...

I've installed OS updates, pulled the latest version (the commits since I opened the issue) and now it compiles and runs fine.

Very weird.

Thanks for your help guys
