### ISSUE TITLE
when closing files with keyboard dock panes close instead.

### ISSUE THREAD

**Issue by chrisdrackett** [atom/atom#14198]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When closing files with the keyboard sometimes dock items are closed.

### Steps to Reproduce

1. open an editor and make sure the tree view is in the left dock.
2. open more than one file.
3. close the file with the keyboard shortcut for close file (<kbd>cmd</kbd>-<kbd>W</kbd> on a mac)
4. do the command again.

**Expected behavior:** [What you expect to happen]

The next open file in the center pane will close

**Actual behavior:** [What actually happens]

The tree view itself closes.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

1.17.0
10.12.4

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ungb** [comment]
For items that are in docks that are permanent items, we should no-op when `cmd+w` is triggered as this leads to bad behavior and experience.

**Comment by ungb** [comment]
gif from linked issue of the problem (thanks @steelbrain):

![kapture](https://cloud.githubusercontent.com/assets/4278113/25021927/6414f3f0-20ad-11e7-9dc0-659c953561dc.gif)

**Comment by iolsen** [comment]
Fixed in https://github.com/atom/atom/pull/14221
