### ISSUE TITLE
Treeview is unusable with Atom 1.16.0

### ISSUE THREAD

**Issue by feketegy** [atom/atom#14195]
### Description

The tree view became unresponsive in Atom 1.16.0.
Can't expand/collapse folders, can't open files.
It does nothing when trying to click on files to open it.

See example video: https://streamable.com/56mqp

### Steps to Reproduce

1. Open Atom 1.16.0
2. Open folder / files using the tree view.

### Versions

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Mac OS X El Capitan: 10.11.6

**Comment by rsese** [comment]
Thanks for the report @feketegy - can you edit the issue body and fully fill out the issue template?  In particular, it's always helpful to know if you tried everything in the `Prerequisites` section, trying in safe mode in particular.

**Comment by nalston** [comment]
@feketegy I had the same issue, determined it was caused by addon "double-click-tree-view" .

**Comment by feketegy** [comment]
@nalston That was it. Thanks!!
