### ISSUE TITLE
On open, tree-view opens half shown and expands only when mouse action occurs in Atom

### ISSUE THREAD

**Issue by ungb** [atom/atom#14209]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

tree-view opens half shown and expands only when mouse action occurs in Atom
### Steps to Reproduce

1. Open a project in atom with `atom .`

**Expected behavior:** [What you expect to happen]
![image](https://cloud.githubusercontent.com/assets/5624870/25054622/17cde16c-2113-11e7-9b6a-ef53a8b361ce.png)

**Actual behavior:** [What actually happens]
![image](https://cloud.githubusercontent.com/assets/5624870/25054617/11a4b50e-2113-11e7-91f4-b8a74d3d2fb9.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
Atom    : 1.18.0-dev-83efa4b91
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

BETA:
Atom    : 1.17.0-beta1
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
gif:
![cropped](https://cloud.githubusercontent.com/assets/5624870/25054681/76d42bee-2113-11e7-8c8f-6b9f7bd70ae9.gif)

/cc @nathansobo @matthewwithanm @maxbrunsfeld

**Comment by matthewwithanm** [comment]
afk but I bet this is 83efa4b91889e4cbcb297d859475b3e1cd82547f  😩

**Comment by 50Wliu** [comment]
I can confirm this.
