### ISSUE TITLE
After collapsing a dock, unable to expand dock again

### ISSUE THREAD

**Issue by ungb** [atom/atom#14202]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After collapsing a dock, unable to expand dock again

### Steps to Reproduce

1. Open Atom (atom-beta) with a project
2. collapse the tree view by clicking on the arrow.
![image](https://cloud.githubusercontent.com/assets/5624870/25025269/6117cae4-2056-11e7-8e13-15a8e30e7f82.png)

3. hover over where the arrow should be to expand the dock

**Expected behavior:** [What you expect to happen]
arrow should pop up and let you expand the dock

**Actual behavior:** [What actually happens]
no arrow appears which makes it so you can't expand the dock.  The only way around this is if you drag something and put something in the dock.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Atom    : 1.17.0-beta1
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

/cc @matthewwithanm

**Comment by ryancole** [comment]
Came here to also bring this up. Happening for me, too. I'm on Windows 10 64-bit.
