### ISSUE TITLE
Cannot pitch zoom under the edit area without scrolling

### ISSUE THREAD

**Issue by ooJerryLeeoo** [atom/atom#14206]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I cannot pinch zoom under the `edit` area without scrolling

### Steps to Reproduce

1. Open a file
2. Type some code
3. And than try pinch zoom under `edit` area

**Expected behavior:** It should be zoom in(or out) without scrolling the whole edit area.

**Actual behavior:** 

![zoom](https://cloud.githubusercontent.com/assets/20783502/25043660/270e8a6e-2154-11e7-8731-61f16f5ab388.gif)

### Versions

`Atom`: `1.17.0-beta1`
`OS`: `macOS sierra`

**Comment by rsese** [comment]
Hmmm, for some reason I can't get pinch-zoom to work at all in Atom on Sierra.  It works in other apps like Chrome and Safari though 😕   Tagging as needs reproduction for now.

**Comment by ungb** [comment]
@rsese I'm testing this out now.  under settings I think you need to enable zoom with ctrl scroll.

![image](https://cloud.githubusercontent.com/assets/5624870/25054235/d04d153a-2110-11e7-9fb1-9926a73ad7a2.png)

**Comment by ungb** [comment]
@ooJerryLeeoo it seems in beta you can scroll without having this setting enable which leads to the behavior you are seeing.   Can you try to zoom which pinch zoom with this setting enabled? 
screenshot ⬆️

**Comment by rsese** [comment]
Ohhh I was wondering if I missed a setting somewhere, thanks for the pointer @ungb :v:

**Comment by ooJerryLeeoo** [comment]
@ungb @rsese Ctrl scrolling zoom is not what I mean, you can add this config to your init script to enable pinch zoom.

``` coffee
webFrame = require("electron").webFrame
webFrame.setZoomLevelLimits(1, 10)
```

**Comment by 50Wliu** [comment]
I'm pretty sure we disabled that by default exactly because of this...I'm inclined to mark this as a wontfix.

**Comment by ooJerryLeeoo** [comment]
@50Wliu Pinch zoom is not disable by default, in version `1.17` beta.

**Comment by ungb** [comment]
@ooJerryLeeoo, are you able to do this in stable?  I can only repro this behavior in stable once I enable the `ctrl + scrolling zoom`

**Comment by ooJerryLeeoo** [comment]
@ungb, in stable, you can add this script into init script to enable the pinch zoom :ok_hand::

```
webFrame = require("electron").webFrame
webFrame.setZoomLevelLimits(1, 10)
```

**Comment by 50Wliu** [comment]
That's why I think this should be closed as wontfix - because you can't do it unless you enter code into your init script that overrides the [built-in disable](https://github.com/atom/atom/blob/03be10414189b195ce4cbb9f11936cf575b15042/src/main-process/atom-window.coffee#L317).

**Comment by ooJerryLeeoo** [comment]
@50Wliu so should I close this ??

**Comment by ooJerryLeeoo** [comment]
But like what I say before, this is not disable by default under `Atom1.17.0-beta2` 😕

**Comment by 50Wliu** [comment]
In which case the disable probably broke (it's happened before).  It definitely isn't intentional though that you can pinch to zoom, as evidenced by that code snippet. #13949 looks suspicious because that's the commit that changed how the zoom disabling works, and it was added in 1.17.0.

**Comment by ooJerryLeeoo** [comment]
Ok, I got it :ok_hand:

**Comment by 50Wliu** [comment]
@ooJerryLeeoo If you want to create a new issue asking for the _addition_ of pinch to zoom such that it works correctly on macOS, I think that's totally fine :).

**Comment by ooJerryLeeoo** [comment]
#14241

**Comment by ungb** [comment]
So after further investigation.. the editor and text isn't getting zoomed in but the entire atom is getting zoomed in.  This is a bug in beta.  I created https://github.com/atom/atom/issues/14252 as it's more obvious when you have the tree view open or other dock items.
