### ISSUE TITLE
apm is missing

### ISSUE THREAD

**Issue by plexigras** [atom/atom#14207]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

i accidentally uninstalled apm and so i reinstalled atom while i moved all my globaly insalled packages to a local user folder and changed the npm prefix `npm config set prefix .local/share/npm`.

so i simply did `pacman -S atom` to reinstall atom but apm is still nowhere to be found

### Versions

1.16.0

**ps.: is this the right place for this issue?**

**Comment by rsese** [comment]
> ps.: is this the right place for this issue?

There's https://github.com/atom/apm/ for apm related issues - go ahead and re-open there and make sure to fully fill out the issue template.
