### ISSUE TITLE
Atom Crashes (Angular2 project / macOS)

### ISSUE THREAD

**Issue by krisUneon** [atom/atom#14220]
Hi folks,

I have found many posts about Atom freezing/hanging/failing/crashing, but none really helped me since I am not very good in troubleshooting. I am on mac, thus I have gone through the logs in console, there seems to be a lot, even regarding the Atom itself, but I have no idea how to analyse that. I am using just a few plugins (mostly TypeScript related), which I would not consider demanding (but who am I to judge ....). I deal with TypeScript files mostly. My machine is MacBook Pro 2015 / 2,7 GHz Intel Core i5 / 8 GB 1867 MHz DDR3 / Intel Iris Graphics 6100 1536 MB . All I can say is that it seems to me that Atom crashes always when new linter warning appears exactly at the time when the project bundle is being compiled automatically after saving some file (automatisation is not related to Atom itself, I mostly use Angular CLI in my projects). There seems to be several different occurrences of crashing. Sometimes Atom just freezes, other times it quits and just recently, it crashed down my entire OS forcing it to restart. I am using many other tools on the very same machine (even CPU/GPU highly demanding such as VR/3D editing software) and it crashes only when Atom is on. I am sorry I am not more specific (I have decided to create this issue to be able to be more specific). I welcome any suggestion -> "How To" troubleshoot Atom crash? / What detail info to share to receive best advice? / What posts regarding Atom crashes are best to read? / What docs related to Atom crash are best to study? ... anything.

Thanks!

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
