### ISSUE TITLE
Live reload in dev mode fails when multiple files are symlinks to the same path.

### ISSUE THREAD

**Issue by p0lm** [atom/atom#14226]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When multiple files within the same project are symlinks to an identical path, dev live no longer works.

### Steps to Reproduce

1. Create a new project.
2. Create a new file. 
3. Create 2 symlinks to the original file.
4. Open Atom in developer mode.

**Expected behavior:** Live reload on edit of either the original file, or when opened via the symlink.

**Actual behavior:** No live reload. Trace below:

```
The handle(20) returned by watching /path/to/second-symlink is the same with an already watched path(/path/to/first-symlink)

HandleWatcher.start	@	main.js:91
HandleWatcher	@	main.js:20
PathWatcher	@	main.js:140
exports.watch	@	main.js:234
module.exports.File.subscribeToNativeChangeEvents	@	file.js:598
module.exports.File.willAddSubscription	@	file.js:107
(anonymous function)	@	file.js:3
module.exports.File.onDidChange	@	file.js:86
module.exports.TextBuffer.subscribeToFile	@	text-buffer.js:1272
module.exports.TextBuffer.setPath	@	text-buffer.js:317
TextBuffer	@	text-buffer.js:122
module.exports.Project.buildBuffer	@	project.coffee:385
module.exports.Project.bufferForPath	@	project.coffee:364
openTextFile	@	workspace.js:719
openURIInPane	@	workspace.js:624
open	@	workspace.js:556
module.exports.TreeView.openAfterPromise	@	tree-view.coffee:246
module.exports.TreeView.fileViewEntryClicked	@	tree-view.coffee:240
module.exports.TreeView.entryClicked	@	tree-view.coffee:228
(anonymous function)	@	tree-view.coffee:100
```

**Reproduces how often:** 100%

### Versions
Linux Mint 18.1 Cinnamon - Atom 1.16.0 development mode.

**Comment by 50Wliu** [comment]
Please reopen this on the [dev-live-reload](https://github.com/atom/dev-live-reload) package.  Thanks!

**Comment by p0lm** [comment]
Reopened: https://github.com/atom/dev-live-reload/issues/25
