### ISSUE TITLE
Opening new project from context menu opens atom with tree view collapsed 

### ISSUE THREAD

**Issue by ungb** [atom/atom#14236]
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Opening new project opens atom with tree view collapsed 

### Steps to Reproduce

1. create a new folder 
2. Open empty window of Atom
3. Go to context menu and open the new folder from step 1.

**Expected behavior:** [What you expect to happen]
Opens in current atom window with tree view open

**Actual behavior:** [What actually happens]
Tree view is collapse, you can open it with the arrow, but it's not obvious anything happened.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% for new projects

### Versions
Atom    : 1.18.0-dev-b664e1ad8
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

BETA:
Atom    : 1.17.0-beta2
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

/cc @nathansobo @maxbrunsfeld @matthewwithanm as this might be related to the changes that came in with docks.

**Comment by 50Wliu** [comment]
Fixed by above commit.
