### ISSUE TITLE
Scroll does not work in tree-view

### ISSUE THREAD

**Issue by carrodher** [atom/atom#14230]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I can not scroll in the side view of directories/files

### Steps to Reproduce

1. Open Atom
2. Put your mouse on top tree view
3. Scroll doesn't work

**Expected behavior:** I expect to move between files/directories

**Actual behavior:** List of files/directories doesn't change

**Reproduces how often:** 100% after the update

### Versions
```
[~]$ atom-beta --version
Atom    : 1.17.0-beta2
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

[~]$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.13
git 2.12.2
```
### Additional Information

macOS Sierra v10.12.4

**Comment by rsese** [comment]
Are you using the Atom Material UI theme by any chance? /cc https://discuss.atom.io/t/tree-view-does-not-scroll-in-1-17-0-beta0-and-1-17-0-beta1/41733/2

**Comment by carrodher** [comment]
Yes, I am using it. I try to change the theme and using another theme the problem disappear.
Thanks for your answer.

**Comment by davidcp90** [comment]
You can add css to make it work again 
`.tool-panel {
  overflow: scroll;
}`

**Comment by Sarvesh-D** [comment]
Issue is fixed after updating material-ui theme to 2.0.4

**Comment by amackintosh** [comment]
Confirmed, had issue and now fixed by updating to material-ui 2.0.4.

I had to restart Atom a second time to get it to work.

**Comment by owendall** [comment]
thanks for that.

**Comment by Liqiankun** [comment]
Add `.tool-panel { overflow: scroll; }` to stylesheet works for me!

**Comment by cortical-iv** [comment]
The tool-panel overflow trick makes it show, but also makes the editor look ugly in general in a global sense. I just toggle the tree view back and forth a couple of times (`ctrl-\`) and that makes it work.

**Comment by thekyriarchy** [comment]
@Liqiankun Shouldn't the default behavior be to scroll? 

I got here from google, but only using nuclide and no community packgase so I wanted to link to my bug report on that in case anyone else with the same issue ends up here: https://github.com/facebook/nuclide/issues/1532
