### ISSUE TITLE
api reference issue on function arguments

### ISSUE THREAD

**Issue by simpzan** [atom/atom#14233]
for instance `Workspace.observeTextEditors` api, the code is `observeTextEditors (callback)`, while the doc is `observeTextEditors(callback, editor)`. 

It's a common issue throughout all reference docs.

https://atom.io/docs/api/v1.16.0/Workspace#instance-observeTextEditors
https://github.com/atom/atom/blob/v1.16.0/src/workspace.js#L304

**Comment by 50Wliu** [comment]
This is caused by https://github.com/atom/joanna/issues/4.

**Comment by Arcanemagus** [comment]
As explained in https://github.com/atom/joanna/issues/4, this has been fixed since Atom v1.21.0 🎉.
