### ISSUE TITLE
Text gets blurry when scrolled to some position with dpi scaled

### ISSUE THREAD

**Issue by noe132** [atom/atom#14237]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Text gets blurry when System dpi scaled.

### Steps to Reproduce

1. set your system dpi scale to 150% (not an integer multiple of 100%)
2. open atom
3. new file and enter a lot of text more than a page that u can scroll
4. scroll (i'm using touchpad on laptop)
5. scroll on some position text gets blurry

**Expected behavior:** text is sharp

**Actual behavior:** text gets blurry sometimes

**Reproduces how often:** 100%

### Versions

λ atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

λ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 3.6.1
git 2.12.0.windows.1
visual studio

gpu :Intel graphics hd 620 on Intel i5-7200U

OS: win10 x64 enterprise 14393

### Additional Information
screenshots(left is blurry, right is sharp):
![1](https://cloud.githubusercontent.com/assets/2271900/25095951/8224dbfa-23d0-11e7-8fad-b3e2dc174c09.png)
![2](https://cloud.githubusercontent.com/assets/2271900/25095952/822ac560-23d0-11e7-9b6b-326dc1d7532d.png)

#### something i discovered:
only when i scroll to a specific position the text gets blurry, otherwise text is sharp, the chance is about 50%

I open dev tools found that how text is scroll is by css transform translate property, and it is scrolled pixel by pixel, the css pixel was equivalent to 1.5 physical pixel, so when i scroll a  pixel, it translate a pixel, a css pixel was between 2 physical pixels, then the text gets blurry like pic above.

![q](https://cloud.githubusercontent.com/assets/2271900/25096424/b5cbe1c2-23d2-11e7-8d1a-1239d00cf04a.png)

As soon as i found that i set my system dpi scaling to 200%, 1 css pixel = 2 physical pixel, there is no factional physical pixel value, and the blurry text issue no longer occurred.

Similarly, 100% dpi scale or 300% dpi scale won't occur this problem.

I guess this was due to hardware acceleration relating issue, so I have tried that opem atom by `atom --disable-gpu`, and the blurry problem wasn't occurred. So `--disable-gpu` was a walk around by now

I have tried that apply a style `body{transform:translate3D(0, 1px, 0)}` on my chrome browser, the text on web page gets blurry too. Maybe it's the problem how blink render transformed element.

**Comment by noe132** [comment]
I can reproduce this issue on my another computer which has around same OS, Atom version but with nvidia graphics card gtx 1080, by setting dpi scaling to 150% and scroll.

But if I set dpi scale to 200% or 100% the text looks sharp no matter how i scroll the editor.

I guess it's not related to graphics driver or something.

**Comment by rsese** [comment]
Cross referencing some other issues mentioning blurry text on Windows with display scaling /cc https://github.com/atom/atom/issues/13627 and https://github.com/atom/atom/issues/2833.  Seems like basically the same issue?  The only difference though is you mention specifically seeing the blurry text when scrolling and the other issues don't so maybe a separate issue?

**Comment by noe132** [comment]
@rsese actually when I trying found solution, I found that the text become blurry is caused by css property `transform:translate3d` on a dpi scaled system, which screen physical pixel is not integer mutiple of css pixel.

When an element is applied css `transform:translate3d`, the renderer will be [forced to use **hardware acceleration**](http://stackoverflow.com/questions/18842450/translatez0-could-enable-an-acceleration-of-gpu-in-chrome-but-it-could-work-in) to render this element if hardware acceleration is avaliable.

As the css pixel and physical pixel is not mapped *1 to 1 or 1 to integer*` (eg. under 150% scale, 100px css pixel on screen is 150 physical pixel)`, when scroll to some position, there might be a physical physical pixel mapped between 2 css pixel, under this condition, the render kernel use some algorithm to calculate the color output on screen base that color of 2 css pixels average or something ( I guess ), that at the edge of a letter was backgound pixel (dark) and the letter's edge (light), mixed into a color in the middle of dark and light, and cause text look blurry.

**This is when I scroll the how text looks**
![gif](https://cloud.githubusercontent.com/assets/2271900/25165561/a74b5c6c-2509-11e7-8fbd-8ac16f4fc37f.gif)


**I made a gif of 2 frames cutted from when i scroll the editor and  zoomed in 4x**
![gif](https://cloud.githubusercontent.com/assets/2271900/25165500/6c7bcff4-2509-11e7-8a88-6dfbf544b872.gif)

**Comment by razvanilin** [comment]
any progress with this? I had this issue a while ago and now it reappeared when I got the latest update 9th of August 2017.

**Comment by noe132** [comment]
@razvanilin temporary walk around is disabled gpu acceleration by add lunch option `--disable-gpu`. The problem was cause by css property `transform`, rendering by cpu and by gpu differs. But the con is without gpu rendering, editer might not be as smooth as gpu accleterated.

**Comment by beholdnec** [comment]
I have this issue at 125% DPI scaling.

This issue appears to be related to subpixel anti-aliasing and GPU acceleration. Text is never blurry at the top of the document; It only turns blurry when scrolled.

I think the blurry text is graphically "accurate" - it's technically the most correct rendering of text at a fractional offset. But programmers don't want inconsistently blurry text.

**Comment by ClearMarble** [comment]
I'm experiencing this as well...just seems to have started today after an update. I'm on 1.19.0 using Win 10 x64

**Comment by TheGeka** [comment]
I have the same Problem it started to happen after the update to 1.19.0. Using Win 10 x64.

**Comment by HarryPhillips** [comment]
Noticed it too, 1440p monitor at 125% scaling. Happens on scrolling, only way to fix it is to scroll like mad until it resets or close the file and re-open. Tried changing fonts and themes, was no help.

**Comment by Orkat** [comment]
Having this issue for the past day or so on Windows 7

**Comment by Torniojaws** [comment]
Yes, happens to me too after the most recent update (1.19.0).

**Comment by axu2** [comment]
Where do I type --disable-gpu?

**Comment by Torniojaws** [comment]
@axu2 Right-click on the Atom shortcut and pick "Properties" (if you right click on the taskbar icon, you might need to right-click again on the smaller Atom icon):

![image](https://user-images.githubusercontent.com/5442750/29223499-71d282d4-7ecf-11e7-91e3-7a0e65a274af.png)

And then in the "Target" field, add the text ``--disable-gpu`` with a space between ``atom.exe`` and the text:

![image](https://user-images.githubusercontent.com/5442750/29223539-990be35e-7ecf-11e7-9dc4-9e1dd8fba0a2.png)

Then press OK, and make sure all Atom windows are closed. Then start Atom. Should work then.

**Comment by SantiagoLP98** [comment]
Thank you for the workaround, this blurry text issue was driving me mad.

**Comment by karyon** [comment]
to not miss on gpu acceleration (haven't actually tested whether that's noticeable) you can use `--force-device-scale-factor=1` as launch parameter. this disables scaling. in the editor itself, you can simply zoom, (ctrl-mousewheel for me), and to increase the UI element's size add this to your `styles.less`:

```@font-size: 14px;
html, body, .tree-view, .tab-bar .tab {
  font-size: @font-size;
}
```

**Comment by axu2** [comment]
You know, the simplest solution is actually just downloading the AtomSetup-x64.exe  installer for v1.18.0.
https://github.com/atom/atom/releases/tag/v1.18.0

Disabling wifi.
Installing it.
Opening it.
Disable auto update.
Turning wifi back on.

**Comment by SquirrelCoder** [comment]
Had the same problem, adding `--disable-gpu` fixed it.
