### ISSUE TITLE
Atom 64-bit Auto Update not working

### ISSUE THREAD

**Issue by modulexcite** [atom/atom#14234]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom 64-bit fails to update on Windows as the URL passed to Squirrel for updating does not exist. https://atom.io/api/updates-x64?version=1.15.0

### Steps to Reproduce

1. Check for Updates

**Expected behavior:** 
Atom should check for new released versions and display the version number if an update is available.

**Actual behavior:** 
No updates available.

**Reproduces how often:** 
100%

### Versions
- Atom version - 1.15.0 x64
- APM version - 1.15.3

**Comment by damieng** [comment]
Hi there.  

Where are you seeing that URL?  The correct URL is actually https://atom.io/api/updates-x64/RELEASES?version=1.15.0  which returns the correct response.

**Comment by modulexcite** [comment]
I clicked on "Check for updates" in Atom and inspected the process under process explorer, the startup paraus passed to update.exe is the URL I submitted when I reported the issue initially.

___________________________
Thanks
________________________________

**Comment by damieng** [comment]
Although that URL is passed to update.exe it is subsequently modified by update.exe to inject the RELEASE part - the code to do that is here; https://github.com/Squirrel/Squirrel.Windows/blob/14d6dc1599676a9d83daba60e73507d12b73164d/src/Squirrel/UpdateManager.Factory.cs#L47

Can you try using a tool like Fiddler to check what the final URL that actually goes over the wire is?

**Comment by modulexcite** [comment]
you're right @damieng, I should have verified that before logging an issue. The final URL which Squirrel uses is https://atom-installer.github.com/v1.16.0/RELEASES-x64?s=1492031008&ext=.RELEASES-x64 (identified using Fiddler).

However, I'm not sure why Atom wouldn't detect an update when I was using v1.15.0. I no longer have it to test that as I had to manually update Atom by downloading it from the releases page on GitHub.

Thank you for your help @damieng

**Comment by damieng** [comment]
No problem. Please let us know if you run into this issue again.  There definitely is a scenario where updating stops but it's hard to reproduce.
