### ISSUE TITLE
Renaming Opened File in Tree View does not update buffer

### ISSUE THREAD

**Issue by eltian** [atom/atom#14246]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When renaming an opened file using the rename function of the Tree View, the buffer does not update: instead, the old file stays opened in an unsaved state. Saving it creates a new file with the old name.

### Steps to Reproduce

1. Create file "test.html" in project
2. Open "test.html" so it shows in the main editor screen
3. Right click on the file in Tree View, click rename file and rename it to test2.html

**Expected behavior:** The buffer should update accordingly when renaming the file. The file present in the buffer should be the same file with the new name

**Actual behavior:** The buffer does not update. The old name shows in the tab and the file changes to an unsaved state. Saving the file creates a new file with the old name.

**Reproduces how often:** 100% of the time

### Versions

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.5
git 1.8.3.1

Working on CentOS 7

**Comment by 50Wliu** [comment]
Please reopen this on the atom/tree-view repository.  Thanks!
