### ISSUE TITLE
Ubuntu 17.04 unsupported

### ISSUE THREAD

**Issue by tatsujb** [atom/atom#14245]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

on ubuntu 17.04 discord is no longer installable by conventional means.

### Steps to Reproduce

1. download discord.deb
2. attempt to open with default app (double click, or click chrome download; this opens the software manager) this results in the software manager opening and doing nothing; clicking on install is normally the way to go from there but in this case it has no effect

**Expected behavior:** for discord to install on the system

**Actual behavior:** discord does not install on the system

**Reproduces how often:** 100%

### Versions

latest current discord.deb from the discord website (18/april/2017 at time of writing). installing to an ubuntu 17.04 64bit uefi (gpt) fresh install no kernel or other modifications.

### Additional Information

the current workaround I found is using gdebi instead of software manager but this cannot be asked to become the norm. as with other software a version compatible with 17.04 will come down the line. or at least I suppose.

**Comment by Zireael07** [comment]
Discord? This is not discord repo? You got something confused!
