### ISSUE TITLE
Atom crash opening a folder, adding a project folder or dragging folder

### ISSUE THREAD

**Issue by enrique2210** [atom/atom#14240]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The IDE crash when I drag a folder, use the option to open a folder or adding a folder 
I'm on a Windows10 Home edition x64

### Steps to Reproduce

1. Open Atom
2. Select option -> Add a Project folder
3. Atom crash

**Expected behavior:** The project tree open on the left

**Actual behavior:** Atom crash and show the message: The editor has crashed, please report this issue to https://github.com/atom/atom and 3 options -Close Window -Reload -Keep it Open

**Reproduces how often:** 100%

### Versions

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

It can open single files but not a folder

Everytime it crashes it give the same error in the crash log

> _companyName:GitHub
> _productName:Atom
> _version:1.16.0
> platform:win32
> process_type:renderer
> prod:Electron
> ptime:7859659
> rept:electron-crash-service
> ver:1.3.13

> _companyName:GitHub
> _productName:Atom
> _version:1.15.0
> platform:win32
> process_type:renderer
> prod:Electron
> ptime:14346
> rept:electron-crash-service
> ver:1.3.13

Tried in older versions

If I click in Reload, it just open a new window clean
If I click on Keep it Open stay frozen, waited 20min

This is the operation log
[operation_log.txt](https://github.com/atom/atom/files/926764/operation_log.txt)

I already tried: 
* Reinstalling
* Deleting .atom
* Change .atom to .atom-backup,
* Delete blob-store in .atom
* Delete storage in .atom
* Reinstall and restart computer
* Try on safe mode

If I need to add any more information let me know

**Comment by ungb** [comment]
>_companyName:GitHub
_productName:Atom
_version:1.16.0
platform:win32
process_type:renderer
prod:Electron
ptime:7859659
rept:electron-crash-service
ver:1.3.13


Looks like you have windows 64bit and based on the log, atom might be 32bit?  Can you try installing 64bit version of atom to see if the issue goes away?

1.16.0 releases: https://github.com/atom/atom/releases/tag/v1.16.0
Atom windows x64-bit: https://github.com/atom/atom/releases/download/v1.16.0/AtomSetup-x64.exe

**Comment by enrique2210** [comment]
Just downloaded that version also tried zip one, still give the same error but in the log says that I'm still using 32

> _companyName:GitHub
> _productName:Atom
> _version:1.16.0
> platform:win32
> process_type:renderer
> prod:Electron
> ptime:2821
> rept:electron-crash-service
> ver:1.3.13

**Comment by jeffswt** [comment]
You might have to remove your previous Atom installation to try and reproduce it.

**Comment by ungb** [comment]
I tried uninstalling and reinstalling and still didn't see the issue.  does the crash happen with any and every folder you open?    

have you tried with a new empty folder?  

also, last thing you can try is `atom --clear-window-state`, but this could lead to data-loss if you had unsaved buffer 

see: http://flight-manual.atom.io/hacking-atom/sections/debugging/

**Comment by enrique2210** [comment]
Tested `atom --clear-window-state` but same result, crash with 3 options

1. Using a diferent folder Atom dont crash 
2. When I try to open a specific folder inside the project it crash
2.1. Moving the same specific folder outside the project folder, Atom don't crash
2.2. Moving the whole project to a new folder, Atom crash
2.3. Moving all the subfolders from the project to outside the project folder and opening the same specific folder from before Atom crash
3. Just realized that the problem is the subfolder .git 
3.1 Moving the .git to another folder outside the project, make Atom works fine
3.2 Moving the .git folder back to the project once opened and don't close Atom, Atom works fine
3.3 Closing Atom and reopen, make Atom crash
3.4 Repeat step 3.1 and 3.2, Atom works fine

**Comment by enrique2210** [comment]
@Zireael07 

> $ git count-objects -vH
> count: 839
> size: 3.05 MiB
> in-pack: 10147
> packs: 4
> size-pack: 101.13 MiB
> prune-packable: 39
> garbage: 0
> size-garbage: 0 bytes

**Comment by julienlerch** [comment]
Hi folks,
Same issue here. Everytime I try to load a specific project folder in Atom, it crashes while other folders work fine. Reproduced even in safe mode, after deleting my profile and after --clear-window-state.
More or less the same repo size as Enrique : 
```
$ git count-objects -vH
count: 0
size: 0 bytes
in-pack: 18325
packs: 1
size-pack: 197.19 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```
It's a Prestashop repo (PHP) but other repo based on the same app (some much bigger) are loaded with no problem.
Just renaming the .git folder into .git.old and the project is successfully loaded.
I just cloned the repo from git server.

Hope it helps, and let me know if I can provide more info.

**Comment by ungb** [comment]
I'm wondering if this is related to the [git-diff](https://github.com/atom/git-diff) package since the issue seems related to the project being a git project.  

Can you guys try disabling the package?  You can do this by running `apm disable git-diff`.

**Comment by enrique2210** [comment]
Tested `apm disable git-diff`, did not work and received the same crash log

> _companyName:GitHub
> _productName:Atom
> _version:1.16.0
> platform:win32
> process_type:renderer
> prod:Electron
> ptime:1985
> rept:electron-crash-service
> ver:1.3.13

**Comment by ungb** [comment]
🤔  Is there any way someone can provide a repo for a repro?   

If you can't share your repo, can you provide any of the following info?
1. Does the repo contain large files?  (single line/large in data)
2. is there a lot of changes in the repo?  if you delete all your files on your repo and open the folder does this also crash atom?  
3. Is there something different about your git remote server setup?

**Comment by julienlerch** [comment]
Same as Enrique, disabling the git-diff plackage didn't help fixing the issue. 
I'll try to set up a public repo for you and keep you posted.

A few answer to your questions :

1. the repo may contain cached single line files generated by the application but my other repos also do without crashing
2. there are only a few changes in the repo. I'm te only one working on it
3. I deleted all files, only kept .gitignore, .gitattributes files and .git folder : Atom still crashes while trying to add the project folder - even in safe mode and even with disabled git-diff package
4. nothing special on my git server I'm aware of. I'll try to move the repo to github and check if it fixes the issue

**Comment by ungb** [comment]
Thanks @julienlerch!  Actually looking like this could be a bug within atom core(https://github.com/atom/atom/blob/b2daa1deac09d7a27a429a38ccb8b316595ef8a1/src/git-repository.coffee)

Having a repro would be very helpful in figuring out the issue and fixing it.

**Comment by julienlerch** [comment]
Hi @ungb 
Sorry I took far too much time to set this repo up.
Now you can test with https://github.com/julienlerch/git_issue.git
Hope it helps, and let me know if I can be of any help (and I'll be quicker to provide answers, promised)

**Comment by Astrydax** [comment]
Sorry to resurrect but was this solved? Having the same issue right now.

**Comment by ungb** [comment]
Thanks for bring this back up @Astrydax.  Somehow this issue slipped passed me.  I'll take a look at it to and get it prioritized if I can get a consistent repro.

**Comment by julienlerch** [comment]
Hi @ungb 
Have you tried the repo I gave above ? 
[https://github.com/julienlerch/git_issue.git](https://github.com/julienlerch/git_issue.git)

**Comment by ungb** [comment]
@julienlerch apologizes for the delay in response.  I just gave your repo a tried and I couldn't repro on mac or windows.

Any chance you were able to try again on latest and see if it repros?  I'll be more quicker to respond.  catching back up on everything!

**Comment by ungb** [comment]
I'm going to close this issue as I'm unable to repro it on Atom 1.23.1.  If you guys are still able to, please comment here and I'll reopen this issue.

**Comment by kourzanov** [comment]
I still have exact same issue with multiple (non-Git) folders, using both 1.24.0-beta1 x64, tried disabling git-diff,--safe, and --clear-window-state.

**Comment by ungb** [comment]
@kourzanov thanks for following up!  I'll reopen this issue.  

if possible, can you provide the following info?  It would help a lot!
- OS you're using
- How much ram you have
- How large are the folders
- How many folders did you add
- Any additional info that would help us get a solid repro!

Thanks!

**Comment by kourzanov** [comment]
Hi,

It is 4.13.0-19-generic #22-Ubuntu SMP Mon Dec 4 11:58:07 UTC 2017 x86_64
x86_64 x86_64 GNU/Linux (Ubuntu 17.10).
I have 8G of RAM
The folder is empty (I suspect the problem is in the containing folder
somehow, my /home).
I had just one extra folder added (also an empty one, from /tmp).

I also removed my .atom and .config/Atom before trying this.
I could add some other folders (with a .git subfolder in them), from the
same root (my /home) with no problem.

OK, a hot update.

Just found out that my home had somehow a .git in it (I am not sure how it
happened). Could it be that Atom initialized a Git repo in my home by
itself?
And also, this .git is invalid, causing Atom to crash.

That could explain something, indeed.
