### ISSUE TITLE
Max token length for highlighters is reduced to ~1000 in 1.16

### ISSUE THREAD

**Issue by 1st1** [atom/atom#14263]
Looks like Atom 1.16 stopped highlighting long strings for JavaScript and Python (using MagicPython). Highlighter marks long tokens as invalid or simply stops highlighting, see screenshot below:

### JavaScript

![screen shot 2017-04-19 at 9 56 22 pm](https://cloud.githubusercontent.com/assets/239003/25209986/f30732f6-254b-11e7-80af-5e638217cc20.png)

![screen shot 2017-04-19 at 9 57 22 pm](https://cloud.githubusercontent.com/assets/239003/25209987/f30f0aa8-254b-11e7-9e7a-81a1b403763b.png)

### Python

![screen shot 2017-04-19 at 9 57 39 pm](https://cloud.githubusercontent.com/assets/239003/25210015/1596437a-254c-11e7-8fd5-2355933e54ea.png)

![screen shot 2017-04-19 at 9 57 43 pm](https://cloud.githubusercontent.com/assets/239003/25210016/159d44cc-254c-11e7-9023-3d7efb739d3a.png)

### Python Multiline

![screen shot 2017-04-19 at 10 04 35 pm](https://cloud.githubusercontent.com/assets/239003/25210047/357cee50-254c-11e7-9ca3-a5d3f197210b.png)

![screen shot 2017-04-19 at 10 04 37 pm](https://cloud.githubusercontent.com/assets/239003/25210048/358eceae-254c-11e7-89ea-6e65bd4e6c0e.png)

See also https://github.com/MagicStack/MagicPython/issues/79.

**Comment by 50Wliu** [comment]
This is intentional for performance reasons, but with recent first-mate improvements we may be able to lift the restrictions.

**Comment by 1st1** [comment]
Thank you for the explanation. Is there a link to a discussion/PR for this change? Any estimate when you will be able to lift the restriction?

**Comment by 50Wliu** [comment]
https://github.com/atom/atom/pull/13820 and #979

No estimate - that comment was speculation and may or may not happen.
