### ISSUE TITLE
White Atom window when I open a file from terminal

### ISSUE THREAD

**Issue by FezVrasta** [atom/atom#14265]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

I did everything except the "Safe Mode" because I can't reproduce the problem constantly and I'm not able to run Atom in safe mode all the day.

### Description

When I open a file doing `cmd` + clicking on a file path in iTerm 2, some times (once a day?) a white window of Atom opens, the "custom titlebar" gets disabled, and I see a new Atom icon in the Dock.

As you can see, the Atom icon in the Dock is different from the custom one I have assigned to my Atom.app.

![image](https://cloud.githubusercontent.com/assets/5382443/25224135/cb0eba9a-25bd-11e7-89a0-3baf38a61f55.png)

![image](https://cloud.githubusercontent.com/assets/5382443/25224500/da3320f0-25be-11e7-9594-9d8a5f3d9e99.png)

**Open Files and Ports of the process**:
```
cwd
/
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/MacOS/Atom
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
txt
/System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI
txt
/usr/lib/libexpat.1.dylib
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/nslog/build/Release/nslog.node
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/en_GB.lproj/locale.pak
txt
/usr/share/icu/icudt57l.dat
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
txt
/usr/lib/libstdc++.6.0.9.dylib
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
txt
/Users/federicozivolo/Library/Application Support/Atom/GPUCache/data_0
txt
/Users/federicozivolo/Library/Application Support/Atom/GPUCache/data_1
txt
/Users/federicozivolo/Library/Application Support/Atom/GPUCache/data_2
txt
/Users/federicozivolo/Library/Application Support/Atom/GPUCache/data_3
txt
/System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
txt
/System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/AMDRadeonX4000GLDriver
txt
/System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib
txt
/System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/content_shell.pak
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
txt
/System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
txt
/System/Library/Caches/com.apple.IntlDataCache.le.kbdx
txt
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/pathwatcher/build/Release/pathwatcher.node
txt
/System/Library/Fonts/SFNSText.ttf
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLightAppearance.car
txt
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
txt
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
txt
/private/var/folders/78/glbtflts3sl9tsm2jq7btvqw0000gn/C/com.github.atom/com.apple.metal/libraries1.data
txt
/private/var/folders/78/glbtflts3sl9tsm2jq7btvqw0000gn/C/com.github.atom/com.apple.metal/AMD Radeon R9 M295X/functions1.data
txt
/Users/federicozivolo/Library/Caches/com.github.atom/Cache.db-shm
txt
/private/var/db/mds/messages/501/se_SecurityMessages
txt
/Users/federicozivolo/Library/Application Support/Atom/GPUCache/index
txt
/System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FunctionRowAppearance.car
txt
/System/Library/Fonts/Helvetica.dfont
txt
/usr/lib/dyld
txt
/private/var/db/dyld/dyld_shared_cache_x86_64h
0
/dev/null
1
/dev/null
2
/dev/null
3
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
4
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin
5
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
6
->0x521884d11ae23d67
7
->0x521884d11ae24367
8
count=0, state=0x9
9
->0x521884d11ae21727
10
->0x521884d11ae22aa7
11
->0x521884d11ae217e7
12
->0x521884d11ae238e7
13
/dev/urandom
14
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Resources/electron.asar
15
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Resources/app.asar
16
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/en_GB.lproj/locale.pak
17
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/content_shell.pak
18
19
->0x521884d13c2c5fbf
20
->0x521884d11ae24127
21
->0x521884d13c2c808f
22
->0x521884d11ae239a7
23
->0x521884d11ae22867
24
->0x521884d11ae22927
25
->0x521884d11ae24427
26
count=0, state=0x8
27
/
28
/private/etc
29
/private/etc/hosts
30
->0x521884d11ae220e7
31
->0x521884d13c2c8607
32
->0x521884d13c2c6dcf
33
->0x521884d11ae21f67
34
->0x521884d11ae23467
35
->0x521884d13c2c7987
36
->0x521884d13c2c6e97
37
->0x521884d11ae22567
38
->0x521884d11ae229e7
39
->0x521884d13c2c70ef
40
->0x521884d13c2c6857
41
->0x521884d13c2c853f
42
count=0, state=0xa
43
/Users/federicozivolo/.atom/config.cson
44
/dev/null
45
/var/folders/78/glbtflts3sl9tsm2jq7btvqw0000gn/T/atom-1.16.0-federicozivolo.sock
46
/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/Extras2.rsrc
47
->0x521884d13c2c8477
48
/System/Library/Frameworks/CoreImage.framework/ci_kernels.metallib
49
/private/var/folders/78/glbtflts3sl9tsm2jq7btvqw0000gn/C/com.github.atom/com.apple.metal/libraries1.maps
50
/private/var/folders/78/glbtflts3sl9tsm2jq7btvqw0000gn/C/com.github.atom/com.apple.metal/libraries1.data
51
/private/var/folders/78/glbtflts3sl9tsm2jq7btvqw0000gn/C/com.github.atom/com.apple.metal/AMD Radeon R9 M295X/functions1.maps
52
/private/var/folders/78/glbtflts3sl9tsm2jq7btvqw0000gn/C/com.github.atom/com.apple.metal/AMD Radeon R9 M295X/functions1.data
53
/Users/federicozivolo/Library/Caches/com.github.atom.ShipIt/update.r6icPEi/Atom.app/Contents/Resources/app.asar
54
/Users/federicozivolo/Library/Application Support/Atom/GPUCache/index
55
/Users/federicozivolo/Library/Application Support/Atom/GPUCache/data_0
56
/Users/federicozivolo/Library/Caches/com.github.atom/Cache.db
57
/Users/federicozivolo/Library/Application Support/Atom/GPUCache/data_1
58
/Users/federicozivolo/Library/Application Support/Atom/GPUCache/data_2
59
/Users/federicozivolo/Library/Application Support/Atom/GPUCache/data_3
60
/Users/federicozivolo/Library/Caches/com.github.atom/Cache.db-wal
61
/Users/federicozivolo/Library/Caches/com.github.atom/Cache.db-shm
62
FNetwork.defaultStorageSession
64
65
/Users/federicozivolo/Library/Saved Application State/com.github.atom.savedState/data.data
66
/Users/federicozivolo/Library/Saved Application State/com.github.atom.savedState/windows.plist
67
/Users/federicozivolo/Library/Saved Application State/com.github.atom.savedState/window_1.data
```

### Steps to Reproduce

1. `touch /tmp/test.js`
2. `ls /tmp/test.js`
3. CMD + Click on the file path to open Atom

**Expected behavior:** A normal Atom instance should be open.

**Actual behavior:** a white Atom window appears and the custom titlebar is disabled

**Reproduces how often:** few times a day

### Versions

```
$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.11.0

macOS 10.12.4 (16E195)
```

### Additional informations
I reproduce the same behavior if I use the `atom` CLI provided by "Atom Shell Commands" and also if I use the `open -a /Applications/Atom.app` command

**Comment by rsese** [comment]
In the blank editor, can you open dev tools (<kbd>Alt-Cmd-I</kbd>) and see if there are any console error messages?

**Comment by FezVrasta** [comment]
I'll try when I get the white window again.

**Comment by FezVrasta** [comment]
Nope, I can't open the dev tools. I have the window open right now, I'll keep it open for a while in case you reply and ask me to do any additional test.

**Comment by rsese** [comment]
Thanks for giving that a try, you can go ahead and close it if we can't get to devtools.

When you open a file from the command line, can you add `-f` e.g. `atom -f /path/to/file` and share any output you see when you get the white screen again?

Also just came across this issue which sounds very similar though it was closed as fixed, cross-referencing here /cc https://github.com/atom/atom/issues/4351.

**Comment by FezVrasta** [comment]
I usually open them with CMD + click, I'll use the `-f` argument when I open them from CLI tho, I'll keep you posted.

Isn't there anything helpful in the system monitor you may need?

**Comment by rsese** [comment]
> Isn't there anything helpful in the system monitor you may need?

Possibly but I personally wouldn't be able to use the information to debug the issue - the information could be useful to one of the other maintainers or others following the thread though.

**Comment by FezVrasta** [comment]
So, I have to correct myself.

This seems to happen **only** when I open a file using CMD + Click inside the terminal.

![image](https://cloud.githubusercontent.com/assets/5382443/25906637/7e4277fe-35a5-11e7-8585-d04a7cec4115.png)

When I CMD + Click on one of the blue lines of the above screenshot the error happens almost always.

**Comment by rsese** [comment]
> When I CMD + Click on one of the blue lines of the above screenshot the error happens almost always.

Interesting, I'll try and reproduce after installing iTerm2.  Can you update your steps to reproduce?

**Comment by rsese** [comment]
I had a chance to install iTerm2 but I couldn't reproduce - I just ran a `ls -l` in a directory with a Ruby file,`cmd-clicked` the filename to open in Atom, and the file opened with no problem.

I tried again on the same file a few more times and then another file associated with Atom (a Markdown file) and didn't run into a white window.

Can you reproduce with any type of file that you cmd-click in iTerm2?

**Comment by FezVrasta** [comment]
I tested this only with JS files because that's what I usually work with.

**Comment by magicdawn** [comment]
by this guide http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
I deleted a package that symlinks to another location. 
Fixed. just FYI. :)

**Comment by RichardLitt** [comment]
I have a similar problem. I made a screencapture of what the white window looks like, to me. @FezVrasta does this match your experience? 

<img width="1102" alt="screen shot 2017-08-24 at 3 54 38 pm" src="https://user-images.githubusercontent.com/910753/29685796-95051cd4-88e4-11e7-95fa-681a558f4d2f.png">

[Video showing interactions with the white square](https://www.screenmailer.com/v/5hsWgJaWLnW2wSY)

**Comment by sigxcpu76** [comment]
This happens 100% of the time on current Atom release (and previous one, at least) after closing a project window: another blank white window opens with the title set to the previously closed window. Dev Tools cannot be started in this window.
I've tried to run atom --reset but this didn't fix it.

It happens both when atom si started from terminal (iTerm2) or from Spotlight launcher.

**Comment by bcullman** [comment]
This has been an ongoing problem for me as well, intermittently occurring when typing `atom .` in a terminal window. I typically force quit and relaunch a second time with `atom .`

**Comment by rxupshaw** [comment]
I have the very same problem,  a blank white screen but on Windows 10.  It was working fine untill I ran a Windows Update on my machine last week.   Since then, it won't work.  Only a blank white screen.  I even removed and reinstalled Atom to no avail.

**Comment by Mariainesdk** [comment]
hi, I have the same issue in windows :-(, is there some news about how can I fix this?

**Comment by rsese** [comment]
Sorry, we've been unable to reproduce so no news  @Mariainesdk - if you (or anyone else) has any more repro steps we can try, please let me know.

**Comment by bcullman** [comment]
for the record, I have not seen this repro on my mac for a few months now...
