### ISSUE TITLE
Markdown syntax highlight glitches

### ISSUE THREAD

**Issue by Yajo** [atom/atom#14274]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

An image is worth 1000 words:

![captura de pantalla de 2017-04-21 09-36-36](https://cloud.githubusercontent.com/assets/973709/25268007/60395d50-2677-11e7-80d2-b47cff0964fe.png)

### Steps to Reproduce

1. Write something similar to the image in a .md file.

**Expected behavior:** Highlighted sections:

1. Should be rendered as a link.
2. Should be rendered as code block.
3. Should be rendered as a bold link.

**Actual behavior:**

1. Links with newlines in between do not render as such.
2. Code blocks inside lists do not render as such.
3. Links inside bold text do not render as such.

**Reproduces how often:** 100%

### Versions

```
➤ atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

➤ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.9.3

➤ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 25 (Twenty Five)
Release:	25
Codename:	TwentyFive
```

**Comment by 50Wliu** [comment]
Please reopen these issues _as separate issues if they don't already exist_ on the atom/language-gfm repository.

**Comment by Yajo** [comment]
Thanks, that repo's name was a hard one to guess 😅 

Done: https://github.com/atom/language-gfm/issues/82, https://github.com/atom/language-gfm/issues/70 & https://github.com/atom/language-gfm/issues/200
