### ISSUE TITLE
Packages globally preload nondeterministically before updateProcessEnv configures process.env properly

### ISSUE THREAD

**Issue by steakknife** [atom/atom#14277]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

updateProcessEnv MUST run before anything from ~/.atom because there are many, many packages which depend on the user's specific configuration, not the system-default configuration. This includes any community packages (maybe some built-in packages too, but not sure) from ~/.atom which may get preloaded. Basically, anything loading a community package has to synchronously await completion of `updateProcessEnv`.

### Steps to Reproduce

1. Move/backup `~/.atom` out of the way.
1. Add `sleep 5; export HI=5` to the top of user's login shell script.
1. Put a debugging `console.log "updateProcessEnv ran here"` in `src/update-process-env.js` near the end of `updateProcessEnv`.
1. `~/.atom/init.coffee`: Put a debugging `console.log "HI=#{process.env.HI}"`.
1. Some random package in the exports file: Put a debugging `console.log "HI=#{process.env.HI}"`.
2. Rebuild and install atom.
3. Install a [crap-ton of packages](https://gist.github.com/steakknife/c621c0d56eeeb10265b2fb549112cf1b).
4. Restart atom NOT from the command-line and check the console a few times for `HI=...`.

**Expected behavior:**

Packages are always configured for user's login shell environment. (Always `HI=5`)

**Actual behavior:**

Breaks because it's configured to the system-default environment.

**Reproduces how often:**

85%

### Versions

f4a83b238 head (1.18.0-dev-f4a83b238)  & 1.16.0

### Additional Information

macOS

**Comment by as-cii** [comment]
Thank you for the report, @steakknife. 

As mentioned in https://github.com/atom/atom/commit/de47a26c5d5bd31559a07b35fd607efa94b3d0d5#commitcomment-21876320, preloading only affects core packages, which at runtime are then disabled in case a dev version of the package is found or the user had disabled the package in her configuration file. For this reason, I am not sure this is due to the work done in #14080. 

However, I wonder if this may be related to `updateProcessEnv` instead. @joefitzgerald: does this ring any bell for you?

**Comment by joefitzgerald** [comment]
Packages that depend on the environment should use the `core:loaded-shell-env` activation hook to defer activation until after any environment adjustment is complete. E.g. https://github.com/joefitzgerald/go-plus/blob/master/package.json#L39
