### ISSUE TITLE
Missing behavior when dropping a tab in another editor window

### ISSUE THREAD

**Issue by bronson** [atom/atom#14273]
Receive highlighting and pane splitting don't happen when drag-and-dropping a tab into another editor window.

I'd expect drag-and-drop to work the same everywhere, no matter which editor window is receiving the drop.

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The split-pane layout management feature doesn't work when dragging tabs to a new window.

In fact, dropping a tab anywhere outside the tab bar just gets ignored.  This is surprising because that's not how dragging works in the main window.

This is related to this excellent PR: https://github.com/atom/tabs/pull/252

### Steps to Reproduce

1. Open a project
2. Create a new window with `cmd-shift-N`
3. Drag a tab from the project to the window you just opened

**Expected behavior:** Ideally, you'd see the shaded regions allowing you to open a new pane left/right/top...  But I'd settle for a drop in the content area working.

**Actual behavior:** The drag is ignored.  You must hit the tab bar exactly for it to work.

**Reproduces how often:** 100%

![bug3](https://cloud.githubusercontent.com/assets/1776/25256002/af8eb80e-25e2-11e7-9f14-9629488d2fce.gif)

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

MacOS Sierra

```
~$ atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
~$ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.9
git 2.2.1
```

**Comment by toremielck** [comment]
### Couldn't recreate your bug on:

Windows 10 64-bit Build 14393.1066

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### and couldn't recreate your bug on either:

MacOS Sierra 10.12.4

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Did you try reinstalling Atom and/or deleting your ~/.atom folder?

**Comment by hg42** [comment]
I can reproduce this on atom 1.17.0-beta3 on linux.

I actually see the drop areas (darkened areas in my light theme), but the file is not dropped there.

In one try the area remained permanently visible after dropping, but the file wasn't dropped.

When dropping on the tab-bar, I get a copy of the tab, it is not removed from the source window. I think it should be moved, right?

**Comment by toremielck** [comment]
> When dropping on the tab-bar, I get a copy of the tab, it is not removed from the source window. I think it should be moved, right?

I think this beahviour is wanted. The bug adressed here is that atom doesn't do anything when dropping a file from the tab bar of one window not in the tab bar of another window (which works) but in the empty content field of another window. @hg42

**Comment by hg42** [comment]
@toremielck ok.

I tried the same again and now I cannot see drop areas any more.
At one point it kind of flashed shortly (half window) and then never again...weird.

Some more observations:
* the area that remained permanently visible also was half window (on the right), but that was the only time I saw it on one half, the other appearances were full window, no matter where I dragged the mouse cursor
* the areas in the other window were never animated. Just on off, which let's me think it could be an animation problem
* the new rounded dock handles appearing in the source window while dragging never appeares in the destination window

I tried all this with my normal configuration and with --safe.
I also tried 1.16.0 with --safe, which behaves exactly like 1.17.0-beta3.
No drop areas, no dock handles and no dropping inside the text area.

@toremielck: for you it simply works?

**Comment by toremielck** [comment]
@hg42 I think we're talking about different things. Have another look at the animation from OP.
The issue is just about not being able to drop a tab in an empty window. Nothing more.
I don't think it's an animation problem.

And have a look at my update. It doesn't work for me either.

**Comment by toremielck** [comment]
### Maybe the issue is located somewhere in the function:
`describe "when a tab is dragged to another Atom window", ->` ...

### located in the file: 
https://github.com/atom/tabs/blob/0fb0ca9649b738289ce82347d46291983710f14b/spec/tabs-spec.coffee#L965-L1063

### @as-cii What do you think?

**Comment by hg42** [comment]
I didn't want to describe new problems.
I see my observations as indications what might going on.

E.g. if the drop areas are not shown as they should this might indicate, that there is a problem before dropping.

Unfortunately I don't see a pattern in this. May be others do.

**Comment by bronson** [comment]
After a few months' reflection, and thanks to your discussion @hg42 and @toremielck, I'm thinking this issue is too specific.

I wish I had written:

> Dragging-and-dropping a tab into a different window doesn't work the same as dropping into the same window: receive highlighting and pane splitting don't happen.  This is surprising!  I'd expect drag-and-drop to work similarly, no matter which editor window is receiving the drop.

I don't actually have too strong an opinion on what highlighting etc happens, so long as it's consistent!

Think I should close this one and open a new one?

**Comment by hg42** [comment]
you could edit the title, according to https://github.com/mikelbring/tinyissue/issues/98
you could also edit the description to reflect this

**Comment by hg42** [comment]
this still doesn't work for me in Atom 1.22.1

**Comment by bronson** [comment]
OK, edited.  Hope that's clearer.
