### ISSUE TITLE
Very Slow and Laggy Package List Loading

### ISSUE THREAD

**Issue by GeorgeWL** [atom/atom#14270]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
Very Slow  to load Package List, hung once. Using a unusually high amount of memory
### Steps to Reproduce

1. Open Package List
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
Faster load
**Actual behavior:** [What actually happens]
slow load
**Reproduces how often:** [What percentage of the time does it reproduce?]
every time
### Versions
Version 1.7.0-Beta3
Windows 10 Latest Version
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Can you re-open this in https://github.com/atom/settings-view @GeorgeWL?  Make sure to confirm if you've followed the debugging steps by checking the checkbox in the Prerequisites section too.
