### ISSUE TITLE
Minor: "Find File" match highlighting does not prefer contiguous word matches

### ISSUE THREAD

**Issue by atz** [atom/atom#14272]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Minor UI issue with the highlighting of matched text in the "Find File" feature.  While the ability to find files despite varying insertions around whitespace, underscores, etc. is *awesome*, when highlighting of matched strings in the paths displayed, there should still be a preference for matching the whole string.  

### Steps to Reproduce

1. Have files in project, e.g.:
- `./app/views/hyrax/admin/appearances/show.html.erb`
- `./spec/controllers/hyrax/admin/appearances_controller_spec.rb`
- `./spec/views/hyrax/admin/appearances/show.html.erb_spec.rb`
- etc.
2. Find > Find File > "appearances"

**Expected behavior:** If the full string is matched in the pathname, it should be highlighted. In this case "appearances".  
**Actual behavior:** The "a" is highlighted from earlier in the path, and subsequently, only "ppearances" or "rances" is highlighted.  
**Reproduces how often:** Deterministic, every time.

![screen shot 2017-04-20 at 3 14 52 pm](https://cloud.githubusercontent.com/assets/109954/25254964/3dd326aa-25dd-11e7-90ef-4b507f846758.png)

### Versions
```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by rsese** [comment]
Thanks for the report!  Can you re-open this in https://github.com/atom/fuzzy-finder if there's no existing issue in so we have it in the right place?
