### ISSUE TITLE
Win10 Jump Lists do not respect "Run as Administrator"

### ISSUE THREAD

**Issue by ZebraFlesh** [atom/atom#14289]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On Windows 10, recently opened files and projects are added to a Jump List. However, I have my atom shortcut configured to always Run as Administrator (due to stupid *$#!#$!!! Windows 10/IIS permissions). Unfortunately, none of the items in the Jump List launch as administrator. This renders the Jump List/Recent Items feature useless: I can't save any files when Atom is running with reduced permissions.

### Steps to Reproduce

1. Configure Atom to Run as administrator
    1. Launch Atom
    1. Pin Atom to taskbar
    1. Close Atom
    1. Right click on the Atom shortcut in the taskbar to bring up the context menu.
    1. Right click on Atom in the context menu to bring up the child context menu (thanks, Microsoft!)
    1. Click on Properties
    1. In the Shortcut tab, click Advanced
    1. Check the "Run as administrator" checkbox. 
    1. Press OK to close Advanced Properties. Press OK to close Properties.
1. Click the shortcut in the taskbar to launch Atom. Atom launches as Administrator.
1. Run the Application: Open Folder command (Ctrl+Shift+O by default) and open `C:\Windows\System32\drivers\etc`
1. Open the `hosts` file, add some whitespace, Ctrl+S to save.
1. Close Atom.
1. Right click the Atom shortcut in the taskbar and click the `etc` Project.
1. Open the `hosts` file, delete the whitespace that was previously added, and save the file. 

**Expected behavior:** 

Changes to the `hosts` file are saved because Atom was launched either (1) with the permissions in place when the recently used item was added to the list or (2) with the permissions defined in the taskbar shortcut.

**Actual behavior:** 

Changes to the `hosts` file fail to save with the error `EPERM: operation not permitted`

**Reproduces how often:** 

100%

### Versions

Windows 10 Pro (64-bit)

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by rsese** [comment]
Played around with this a bit and though I see the same behavior, seems like a general Windows issue?

* https://superuser.com/questions/482368/make-jumplist-shortcut-always-run-application-as-administrator
* https://answers.microsoft.com/en-us/windows/forum/windows_8-security/pinned-items-dont-open-application-as/85a84f88-3aa6-4943-9142-f5c61d3f22dc

I also see the same behavior in VS Code and Sublime (couldn't get jump lists to work with Notepad and Wordpad to test with those apps).

**Comment by ZebraFlesh** [comment]
It does look that way. Ugh, what a terrible OS shell. Clearly this is not an Atom issue then.  Thanks for investigating.
