### ISSUE TITLE
Atom is heating up my Mac!

### ISSUE THREAD

**Issue by trikyas** [atom/atom#14284]
As soon as I open atom my mac gets extremely hot. 

CPU is around 140

Spindump on Atom below.

[Spindump.txt](https://github.com/atom/atom/files/949397/Spindump.txt)

Screenshot below.

<img width="800" alt="screen shot 2017-04-23 at 11 03 44 am" src="https://cloud.githubusercontent.com/assets/4310786/25309593/ba6924e2-2814-11e7-959c-22ba99efb64b.png">

Screenshot below.

<img width="832" alt="screen shot 2017-04-23 at 11 00 35 am" src="https://cloud.githubusercontent.com/assets/4310786/25309596/c4988c50-2814-11e7-9f1c-4d876b9a5af2.png">

I have no idea how to approach this issue or how to gather the info needed to get assistance. If this information is not enough, please guide me to get the correct information. To give an example.

I'll open 'Terminal' navigate to my work folder.
mkdir new_folder_name
cd new_folder_name
touch index.html
atom .

As soon as Atom opens, I can feel the mac get hot. My CPU gets to 99 degrees in a mater of seconds. This is not good and I need to resolve this issue. 
Please help me.

My mac specs are below.

Macbook Pro (Retina, 15-inch, mid 2015 )
Processor -- 2.2 GHz intel Core i7
Memory -- 16GB 1600 MHz DDR3
Graphics -- Intel Iris Pro 1536 MB

**Comment by Ingramz** [comment]
This issue seems to be related to some package that you have installed for atom.

To verify, run `atom --safe`. Based on the dump file you provided, `hh_server` should be part of hhvm, so I would check by disabling packages related to that first.

**Comment by trikyas** [comment]
Thank you for your help :) You are correct. It seemed to be nuclide. After disabling that. The CPU usage has stopped...
I cannot thank you enough. You are awesome!!!
