### ISSUE TITLE
Per-package transpilation overhead

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#14300]
### Description

Utilizing per-package transpilation brings in some overhead from core dependencies being loaded.

### Steps to Reproduce

1. Have a package utilizing per-package transpilation
2. Profile activation
3. Note Atom core dependencies being counted as part of the package activation

#### Expected behavior

Per-package transpilation to have similar overhead to the built in transpilation, assuming the transpiled files are already cached.

#### Actual behavior

A few dependencies are loaded in Atom core, counting against the package's "activation time" in TimeCop.

#### Reproduces how often

100% of the time.

### Versions

```
Atom    : 1.17.0-beta3
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

Windows 10 x64

### Additional Information

Here is an example profile taken from a load of https://github.com/AtomLinter/linter-eslint/pull/890/commits/9096fe131d20ad281de1b548b11d55c43b014918:
![image](https://cloud.githubusercontent.com/assets/427137/25403755/428695a0-29b2-11e7-993e-d975012ce196.png)

The total time for `compileFileAtPath` in this trace is 28.9 ms.

Tracing things down it looks like `minimatch` isn't included in the snapshot (and thus being loaded here) due to https://github.com/atom/atom/pull/14096. Loading that in accounts for 7.8 ms of the time.

The other large require in `getTranspilerPath` looks to be bringing in the `resolve` module [here](https://github.com/atom/atom/blob/f4cfe7603fbe99c8f717eb92fdff20d33b3fd90a/src/package-transpilation-registry.js#L154), at least it looks to match the pattern in [that file](https://github.com/substack/node-resolve/blob/5f6e682396eca043624d0a13286b9015b1e6cfce/index.js).

Tagging @BinaryMuse and @as-cii here at the request of @BinaryMuse 😉.

**Comment by lee-dohm** [comment]
This is definitely something on our radar and something that we're intending to address with a future rearchitecture of apm. Keep eyes peeled for updates! :+1:
