### ISSUE TITLE
Please do something about big files.

### ISSUE THREAD

**Issue by maxKimoby** [atom/atom#14322]
This issue is probably gonna get closed right away because I am not respecting the code.

However, please do something about big files, that makes no sense! The editor crashes every time a big file is loaded and when opening it back, it still opens the same file so it crashes again.

**Comment by lee-dohm** [comment]
We have been making progress on large file problems. See the [Atom v1.14](http://blog.atom.io/2017/02/08/atom-1-14.html) and [Atom v1.15](http://blog.atom.io/2017/03/09/atom-1-15.html) blog posts for details. It is something that we continue to look at and work on.
