### ISSUE TITLE
Search (Find in project) has strange behaviour

### ISSUE THREAD

**Issue by paddotk** [atom/atom#14332]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Whenever I seach in my project files, there is a strange and incorrect difference between a normal 'Find in project' search and entering a project folder to search into.

I have two project folders in Atom. When search and leave the path field empty, it is done in about a second and returns an X number of search results.
When I then search within the directory of just one of the projects, the search takes much longer and returns many more results. What i looks like (but there are too many files and folders to be able to make sure), is that when I search within a project directory, it also searches within greyed out subfolders, so folders that are supposed to be excluded from the search. The option 'Exclude VCS ignored paths' is ticked.
I have a .gitignore and .dockerignore file in the project root directory that lists the subfolders that should be ignored.

I updated Atom to the newest version (1.16.0) and removed all packages that aren't there by default. I checked with someone else who is using 1.12.0 and he has the same issue.

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/find-and-replace if there's no existing issue already so we have it in the right place?

Please fill out the issue template completely and make sure to provide exact steps to reproduce as well.

**Comment by paddotk** [comment]
Ah I didn't know there was a separate repo for it but... Since I think https://github.com/atom/find-and-replace/issues/890 is the same issue I'll just keep my eye on that for now.

**Comment by rsese** [comment]
No problem, we have quite a few issues across many repos :v:
