### ISSUE TITLE
The editor is not responding.

### ISSUE THREAD

**Issue by mikecousins** [atom/atom#14346]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In many different cases the Atom editor will report "The editor is not responding" shortly after launch.

### Steps to Reproduce

1. Upgrade Atom
2. Launch Atom

or

1. Update Windows
2. Launch Atom

or

1. Update packages
2. Restart Atom

**Expected behavior:**
Atom should open properly

**Actual behavior:**
Atom freezes during the load and then says "The editor is not responding."

**Reproduces how often:**
Probably 50-75% of Atom upgrades. 100% of major Windows upgrades (Creators Update was the last one that caused it). 10% of package upgrades.

### Versions
Atom 1.16.0
Windows 10 Pro x64 (Creator's Update)

### Additional Information

atom --clear-window-state resolves this 100% of the time for me when it occurs.

**Comment by rsese** [comment]
Just trying to get more info - do you remember if you started seeing this behavior at a particular release version of Atom?  Sounds like you've hit this at least for every other release.

Also, you mentioned using `atom --clear-window-state` which fixes things for a while, but have you also tried temporarily [resetting to factory defaults](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) and trying to reproduce?  Though based on your description it doesn't seem super straightforward to try and reproduce though.

**Comment by mikecousins** [comment]
I don't remember when it started but it's been going on for at least 6 months. I've never tried resetting to factory defaults. I can try that next time it happens.

**Comment by Prgwf** [comment]
Firstly, I'm sorry for my poor English. I meet this problem too. And it occurs too frequent!!! I'm using atom in Archlinux(with i3wm). However, if I run atom with the option --safe, it will not happen. 
I install several Community Packages. 
There is the list:
1. autocomplete-clang 0.11.3
2. clang-format 1.29.0
3. gpp-compiler 3.0.7
4. linter 2.1.4
5. intentions 1.1.2
6. linter-ui-default 1.2.4
7. busy-singal 1.4.1
8. linter-clang 4.1.1
9. vim-mode 0.66.0

I'd like to know whether there are some packages incompatible.

**Comment by 50Wliu** [comment]
@Prgwf This is a Windows issue.  Can you please open a new issue instead so that we can investigate yours separately?  Thanks!

**Comment by Kezzel** [comment]
Hi there, I am experiencing this as well. I did not see the connection between the freezes and window updates, but it matches what I have seen.

I have switched to the beta branch last time (1.17.0-beta5 x64) in the hope that it would solve, but it did not. I will be happy to test things as well, if you have a good idea:-)

Mads

**Comment by ozarchie** [comment]
System Macbook Pro
macOS Sierra V10.12.5

I have just upgraded PlatformIO IDE to 2.0.0-beta,6, Core 3.4.0rc1
Atom reports 1.18.0 x64
I opened one of the sample apps for ESP32 and ...

![screen shot 2017-06-26 at 14 02 18](https://user-images.githubusercontent.com/6479143/27524836-20205b72-5a7c-11e7-9080-0c906bafc4f9.png)

 I have disabled spell checking.


Here is the dump from the activity monitor for the Atom Helper that is using the time:


`cwd
/
txt
/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper
txt
/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
txt
/Applications/Atom.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
txt
/Applications/Atom.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
txt
/Applications/Atom.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
txt
/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
txt
/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
txt
/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/en.lproj/locale.pak
txt
/System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI
txt
/usr/lib/libexpat.1.dylib
txt
/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin
txt
/usr/share/icu/icudt57l.dat
txt
/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat
txt
/usr/lib/dyld
txt
/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin
txt
/Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/content_shell.pak
txt
/System/Library/Extensions/GeForceTeslaGLDriver.bundle/Contents/MacOS/GeForceTeslaGLDriver
txt
/System/Library/Extensions/GeForceTeslaGLDriver.bundle/Contents/MacOS/libclh.dylib
txt
/private/var/db/dyld/dyld_shared_cache_x86_64
0
/dev/null
1`


HTH

**Comment by rsese** [comment]
Thanks @ozarchie :v: - this particular issue is about Windows so if you see this error in safe mode (`atom --safe`), feel free to open a new issue and fill out the issue template so we can take a look.

**Comment by helispot** [comment]
Try disabling the Spell Check package per the link below.  
https://github.com/atom/atom/issues/14739
Lots of reported success...  including me, just now.

**Comment by ltouro** [comment]
Had the same issue after trying to open a big file in a directory with many files.  Could start to use atom again by executing ```atom --clear-window-state```

**Comment by garretwilson** [comment]
In Atom 1.26.0 x64 on Windows 10 Pro I opened Atom to my last project. (Let's call it "Project X".) It immediately hangs, and eventually there is a message saying, "Editor is not responding", "The editor is not responding. Would you like to force close it or just keep waiting?"

I can force-close it as often as I like, but it still freezes when after startup.

I can open up another Atom instance to another project (while the first one is waiting to be force-closed), and it doesn't freeze. But if I shut everything down (shutting down the other project last), then go back in to Atom and try to switch back to "Project X", it freezes again. (I am using the `project-manager` plugin.)

"Project X" has 11 tabs open (which I consider to be a medium amount; any editor should be able to handle that). Interestingly if I start selecting text in an open document while Atom is still loading "Project X", you can see the point that it freezes, as the mouse selection will just stop and there will be no further response.

I'm sort of stuck now.

**Comment by garretwilson** [comment]
Ack! After running `atom --clear-window-state` Atom no longer hangs—but I lost all my open windows. 😢 Not happy.

**Comment by tfinneid** [comment]
Hi

I have for the last couple of weeks started experiencing the same kind of problem. I am running on ubuntu 18.04 with initial version of Atom being 1.28.1 when the problem started appearing. Currently I am using Atom 1.28.2, after an upgrade just now.
(This is a workplace installation, so I have to be brief and have to resort to emergency clean-up so I can continue working on my tasks)

I have read some of the comments and read a little in the Debugging section in the Documentation, so I have found the "--clear-window-state" solution. 

But before I do that, I will try to make a backup of the .atom directory, to try and save the current state to be able to reproduce the bug. (I am a fulltime developer, so I can help debug the code and resolve the matter, eventhough I am quite new at modern javascript)

So question number 1
- I am assuming tarballing $HOME/.atom is enough to keep the state, so I can debug the problem? If not please yell out as fast as you can, maybe I can see uit before resetting the atom state (its a far cry, but none the less)

Question number 2
- Is there any other information available on this or similar cases anyone know of, which is not linked in this issue, or not written in the debugging documentation or the prerequisites section at the beginning of this issue?

I like the idea of atom and I hope I might help debug the issue and get rid of it. I prefer to get to know Atom better as a IDE for frontend projects of bigger size, but if not I might have to switch to Intellij (which is a good tool, just bored with it and its inherent java community at work)

Regards

Thomas

**Comment by tfinneid** [comment]
Update on reproducing the failure

I have testet the following command line arguments, with no effect on the problem
$ atom --safe
$ atom --disable-gpu
$ atom --safe --disable-gpu
$ atom --safe --enable-gpu-rasterization --force-gpu-rasterization

But the I noticed that I could use the editor as long as I stayed away from one specific, window, whenever I try to switch to the window with that file, it hangs...

One other thing I also notice is that when atom starts up there are to warning boxes appearing on top of each other in the top right corner, the first one is disappears so fast I cant read what it says, is there a log file somewhere where these messages are logged?
The second is for the issue "length undefined (https://github.com/atom/atom/issues/16892)

So, I will save a copy of the local git repo, containing the specific file that seems to cause the problem as well as making a backup up $HOME/.atom

**Comment by Aerijo** [comment]
@tfinneid 
>  Is there a log file somewhere where these messages are logged?

If it's not in dev tools already, this will print all warning and error notifications (run it in dev tools)
```
atom.notifications.getNotifications().filter(n => n.type !== "info")
```

> making a backup up $HOME/.atom

Renaming (e.g., to `.atom-old`) should have the same effect. Atom will ignore it, and make a new `.atom` folder.

On a different note, this issue seems to be for Windows. You will probably be asked to make a new issue.

**Comment by tfinneid** [comment]
@Aerijo, of course the developer tools console... I forgot that atom is running on chromium... thanks

**Comment by dangowans** [comment]
Does Atom have control over the "Editor is not responding" window, or is that an operating system window?  Got one today, and it would be nice to have a third option to "restart with clear window state".
