### ISSUE TITLE
Super slow shell and window load time

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#14347]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With and without --safe my Shell load time is always above 2000ms

### Steps to Reproduce

1. Launch Atom
2. Open Timecop
3. Cry

**Expected behavior:** [What you expect to happen]
Less than 2k ms shell load time
**Actual behavior:** [What actually happens]
Above 2k ms shell load time
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
1.17-beta4 but it happened with 1.16 too.
![atom_2017-05-04_00-10-04](https://cloud.githubusercontent.com/assets/75278/25683778/1d6b2724-305e-11e7-9727-2f2f700758c0.png)
![atom_2017-04-02_20-42-17](https://cloud.githubusercontent.com/assets/75278/25683787/24a95df8-305e-11e7-85c3-125ca0a5840c.png)
![atom_2017-04-02_21-01-35](https://cloud.githubusercontent.com/assets/75278/25683789/24ad8694-305e-11e7-8062-4b24733e4e9d.png)
![atom_2017-04-25_02-47-24](https://cloud.githubusercontent.com/assets/75278/25683788/24acf8fa-305e-11e7-9251-bb625a3a1996.png)

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

I also tried a clean install, removed everything from my drive and it still happened. Sadly there is currently a bug that prevents me from saving a JS profile snapshot.

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
What version of Windows are you running?  Also, you mention that you:

> removed everything from my drive

Does that mean you also reset to [factory defaults](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) by moving your `~/.atom` directory?

For comparison, I just checked 1.17.0-beta4 on Windows 10 in safe mode and I saw a shell load time of 708ms and then with 1.16.0 in safe mode I saw 634ms.

**Comment by rsese** [comment]
Also cross-referencing https://github.com/atom/atom/issues/3673, a long standing issue about improving startup time.

**Comment by rsese** [comment]
Oh and for completeness, could you share your computer specs?  My Windows machine is running Windows 10 with 12GB of RAM and an HDD.

**Comment by Stanzilla** [comment]
Yup, sorry. I removed the .atom dir and my specs are Windows 8.1 with 16GB of RAM on a Samsung 840 Pro SSD.

**Comment by ungb** [comment]
let me see if I can get windows 8.1 running and try to repro.  on windows 10, I'm not seeing over 2000 ms

**Comment by Stanzilla** [comment]
I don't think it's something to do with the OS, just that something is seriously wrong on my machine. Without being able to save CPUProfiles and debugging knowledge it's probably hard to find.

**Comment by ungb** [comment]
We have a bug for the https://github.com/atom/atom/issues/13767 here.  This should be fixed with electron upgrading currently pending on pr: https://github.com/atom/atom/pull/12696.  

It's really hard to pin point the issue, but maybe something we can revisit once the electron upgrade goes in and we can save cpu profiles. 

Also, Are you running x64 or x32 bit of windows 8.1 and atom?

**Comment by Stanzilla** [comment]
both x64

**Comment by EAlufMedina** [comment]
Do the load times improve if you remove your project?  I found that a lot of my slow load time was due to having a project that some of the packages had trouble parsing through.

**Comment by Stanzilla** [comment]
Sadly nope, not at all.
![atom_2017-05-05_19-10-56](https://cloud.githubusercontent.com/assets/75278/25756321/9e2770c0-31c6-11e7-9b7b-e7db2ea016cb.png)

not that this is a screenshot with `--safe` so it can't be an extension

**Comment by ungb** [comment]
@Stanzilla,  By default, Atom automatically opens your last project unless you choose not to,  go to settings and uncheck `Restore Previous Window on start`


![image](https://cloud.githubusercontent.com/assets/5624870/25756420/90866d54-317b-11e7-8a79-95e569d3a83f.png)

**Comment by Stanzilla** [comment]
@ungb I started it with `atom . --safe` in a different folder, unchecked that option now though, result:
![atom_2017-05-05_19-17-08](https://cloud.githubusercontent.com/assets/75278/25756568/7c97384a-31c7-11e7-9186-b34446f6faba.png)

**Comment by rsese** [comment]
@Stanzilla - now that you have `Restore Previous Window on start` unchecked, can you start Atom in safe mode with no projects?  E.g. just `atom --safe`?

**Comment by Stanzilla** [comment]
@rsese Sure, here you go 
![atom_2017-05-05_19-59-47](https://cloud.githubusercontent.com/assets/75278/25758081/6e7e4dec-31cd-11e7-92b9-62a8d74e900d.png)

**Comment by Stanzilla** [comment]
Also renamed .atom folder again =>
![atom_2017-05-05_20-01-57](https://cloud.githubusercontent.com/assets/75278/25758179/c2dee64e-31cd-11e7-9c5c-dec963aac1a3.png)

**Comment by rsese** [comment]
Do you see a lot of variation in the timing if you quit and restart Atom a few times?  It looks like after resetting to factory defaults and starting with no project, Window load time was 8600ms and shell load time was 525ms which is at least an improvement from your first message, where it was 17735ms and 2409ms respectively.

Also a random question, do you happen to have any anti-virus programs running that you can temporarily disable to see if that makes a difference?

**Comment by Stanzilla** [comment]
Windows Defender ON:
1) Window 9380ms, Shell 2265ms
2) Window 2087ms, Shell 482ms
3) Window 1752ms, Shell 446ms
4) Window 1806ms, Shell 481ms
5) Window 1998ms, Shell 530ms

Windows Defender OFF:
1) Window 2084ms, Shell 513ms
2) Window 1848ms, Shell 440ms
3) Window 2240ms, Shell 592ms
4) Window 1745ms, Shell 410ms
5) Window 2315ms, Shell 525ms

**Comment by Stanzilla** [comment]
Yeah after I haven't opened Atom in a few hours, it superspikes on the first open:
```
Window load time
9626ms
Shell load time
2305ms
```

**Comment by Stanzilla** [comment]
I know the optimizations for 1.18 have not landed yet but just wanted to check in and say that I have the same problem on beta0.

**Comment by rsese** [comment]
Thanks @Stanzilla - curious if you're still seeing similar times as your comment in https://github.com/atom/atom/issues/14347#issuecomment-299582781 (without switching of Windows Defender since that didn't look like it had much effect)?

**Comment by Stanzilla** [comment]
@rsese I think `atom --safe` is a bit broken right now, it opens to this: 
![atom_2017-05-18_00-40-43](https://cloud.githubusercontent.com/assets/75278/26179222/b52511d8-3b62-11e7-8716-2cdc4204c613.png)

Which is an empty view and dev tools

**Comment by Stanzilla** [comment]
1) 
Window load time 2779ms 
Shell load time 515ms 
Workspace load time undefinedms 
Project load time undefinedms 
Window state load time 0ms

2) 
Window load time 2505ms 
Shell load time 465ms 
Workspace load time undefinedms 
Project load time undefinedms 
Window state load time 0ms 
3) 
Window load time 2481ms
Shell load time 461ms
Workspace load time undefinedms
Project load time undefinedms
Window state load time 0ms

**Comment by dagolinuxoid** [comment]
atom --safe -> Window load time — 336ms | Shell load time — 1537ms
However it was a second relaunch after closing. First time, when I've started ATOM (atom somefile) it took significantly more time. It vary but slowest one was about 3200ms or something.

**Comment by Stanzilla** [comment]
https://i.imgur.com/J2YDAT0.png


Atom    : 1.19.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by Stanzilla** [comment]
CPU Profile and Timeline data attached.
[AtomProfiles.zip](https://github.com/atom/atom/files/1133452/AtomProfiles.zip)

Window load time 4293ms
Shell load time 551ms
Workspace load time 557ms
Project load time 51ms
Window state load time 608ms

**Comment by ungb** [comment]
I'm going to dig into this more on windows 8.1, I don't currently have a 8.1 env to test on and will need to set one up.  I've add this to my priority list and will ping back once I have more info.

**Comment by myersg86** [comment]
Window load time
1738ms
Shell load time
6769ms
Workspace load time
1349ms
Project load time
188ms
Window state load time
1537ms

**Comment by shanff** [comment]
I'm unsure of that the deal is exactly, but when I ran 64bit on Win10Pro 64, i5 4xxx, 8G RAM on an SSD, it tool almost 20  seconds to load Shell.  Running 32bit brings it down to about 5 seconds, which is  close to what VSCode loads up on the same system.  VSCode has extensions installed, Atom is base, fresh install.

**Comment by CharlesKumar** [comment]
I disabled the installed packages which i don't use often to improve load time

starting with safe mode is very swift

**Comment by jeffgreenca** [comment]
Just on observation, on my Win10 system, turning off Windows Defender Real Time Protection improves my package load and activation times, by 9x and 3x respectively.

No significant change to Window and Shell load times.

Atom 1.23.1 x64 on Win10Pro i5 6xxx, 32GB RAM and on SSD.

**Comment by CharlesKumar** [comment]
@ungb 

> It's really hard to pin point the issue, but maybe something we can revisit once the electron upgrade goes in and we can save cpu profiles.

1. is the issue may be the atom tries to reindex project folders on startup?
2. can packages priority to be set on window load?
3. can the initial loading time be masked with logo/simple animation so that most windows user don't complain about that

**Comment by ungb** [comment]
@CharlesKumar sorry for the extremely late reply.  

I spoke to the team about the points you made today.

>is the issue may be the atom tries to reindex project folders on startup?
It's a possibility but it could also depend on people use cases and what packages they have installed as well. 
 
> can packages priority to be set on window load?
We don't currently do this but it's something we might invest in the future.

> can the initial loading time be masked with logo/simple animation so that most windows user don't complain about that
This would be possible but would require a bit of work to get this working.


Also wanted to mention that we publish [The State of Atom's Performance](http://blog.atom.io/2018/01/10/the-state-of-atoms-performance.html).

There are a few things we accomplished in 2017 and hopefully, a few of the things we tackle this year will solve this problem.
