### ISSUE TITLE
Regex backreference in replace field (of find and replace) does not respect syntax to separate the backreference from immediately following number literal

### ISSUE THREAD

**Issue by EsoterikStare** [atom/atom#14344]
### Description

When I try to use a backreference followed by a number literal, the expected correct syntax does not work and is instead taken as a literal itself. For example, ${1}4 does not result in the first backreference being followed by a 4, but rather the literal string "${1}4". 

The last paragraph (two sentences) in the first section at the following link describes the behavior I expect:
http://www.regular-expressions.info/replacebackref.html

### Steps to Reproduce

1. Create a value in the editor like "1, 2, 3"
2. Press CTRL+F and turn on regex search
3. Paste in the pattern (\d, \d, )\d, and make sure it matches correctly
4. Now, in the replace field past in the pattern ${1}4
5. Note that the highlighting looks like all literals, with no highlighting to indicate a backreference (remove the curly braces to see what I mean, then replace them.)
6. Do the replace, note the unexpected result of "${1}4"

**Expected behavior:** When I have a backreference that needs to be immediately followed by a number literal, I expect wrapping the backreference's number in curly braces to isolate it from any immediately following number literals. For example, ${1}4 should give me the value of the first backreference followed immediately by a 4.

**Actual behavior:** replace string ${1}4 replaces the found text with the literal string "${1}4", completely ignoring the backreference, when curly braces are added.

**Reproduces how often:** Every attempted use of this pattern.

### Versions

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

I don't have any packages installed which should have anything to do with this part of Atom's functionality. This appears to be the default behavior of the current code base.

**Comment by 50Wliu** [comment]
The source you linked to does not mention the `${}` syntax working in JavaScript, which is what find-and-replace uses.  You may want to provide your input in https://github.com/atom/find-and-replace/issues/571.

Also, I would encourage you to take a look at the [Atom and Packages](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages) section of the Contributing guide.  While find-and-replacing is a default component of Atom, due to Atom's modular nature that does not mean that the issue should be filed on atom/atom (in this case, this should have been filed on atom/find-and-replace).

**Comment by EsoterikStare** [comment]
Worth noting for posterity, I found _a_ way to get past this behavior in Javascript regex:

Because you can only ever have backreferences between 0-99, you can never have more than 2 digits as the backreference index/identifier. So, if you pass $01 instead of just $1, you can immediately follow the backreference with a number literal with no issue.

Hopefully this is a more helpful conclusion to this ticket. While not actually a bug (my mistake) and apparently not even related to this part of the code base (also my mistake), this behavior may still be a confusing difference to some, and it's worth providing a solution all the same, in case someone else ends up here with the same confusing issue.
