### ISSUE TITLE
Unable to installing atom-amd64.deb on Ubuntu 17.04

### ISSUE THREAD

**Issue by ungb** [atom/atom#14358]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Unable to install atom on ubuntu 17.04
### Steps to Reproduce

1. Download .deb package from atom.io on Ubuntu 17.04(a clean install is best for repro)
2. Double click to open the deb package on Ubuntu Software Store  
3. Click install

**Expected behavior:** [What you expect to happen]
Atom installs

**Actual behavior:** [What actually happens]
Nothing happens

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

**MORE INFO:**
If you attempt to install on terminal via `sudo dpkg -i atom-amd64.deb `
you get the following errors:
```
dpkg: dependency problems prevent configuration of atom:
 atom depends on git; however:
  Package git is not installed.
 atom depends on gconf2; however:
  Package gconf2 is not installed.
 atom depends on gconf-service; however:
  Package gconf-service is not installed.
```
If you try to start Atom after failed to install, you get
```
/usr/share/atom/atom: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```
If you run ` sudo apt --fix-broken install` this fixes the issue and atom starts working.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS: Ubuntu 17.04
**uname -a:**
```
Linux ubuntu 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ungb** [comment]
Related issue: https://github.com/atom/atom/issues/14235

**Comment by Gyslain** [comment]
I managed to install the package in terminal `sudo dpkg --install atom-amd64.deb `

**Comment by Lorrysant** [comment]
I had the same issue when installing on 17.04.
I found these instructions on the Ubuntu forums: https://goo.gl/j6HsRx

Whilst doing the following actions:

`sudo apt-get update`
`sudo apt-get clean`
`sudo apt-get autoremove`

I got an error and was suggested to run the following:

`sudo apt --fix-broken install`

That installed the missing  gconf2 and gconf2-service dependencies.
I followed the rest of the suggested lines:

`sudo apt-get update && sudo apt-get upgrade`
`sudo dpkg --configure -a`
`sudo apt-get install -f`

Afterwards I ran this again:
`sudo dpkg -i atom-amd64.deb`

And it successively installed then, hope it helps you.

**Comment by andyrichardson** [comment]
The [atom-updater-linux](https://atom.io/packages/atom-updater-linux) package installs updates via dpkg which, according to the responses, seems to work. If you're looking for a GUI implementation, this might be the way to go while installing via Ubuntu Software Center isn't working.

**Comment by Cousjava** [comment]
I had the same issue with 1.20.0. I successfully installed atom using dpkg -i.

When I tried installing via gdebi It got the following lintian output:
```
Unrecognized character \xCA; marked by <-- HERE after <-- HERE near column 1 at /usr/share/perl5/Lintian/Relation/Version.pm line 1.
Compilation failed in require at /usr/share/perl5/Lintian/Util.pm line 103.
BEGIN failed--compilation aborted at /usr/share/perl5/Lintian/Util.pm line 103.
Compilation failed in require at /usr/share/perl5/Lintian/DepMap.pm line 25.
BEGIN failed--compilation aborted at /usr/share/perl5/Lintian/DepMap.pm line 25.
Compilation failed in require at /usr/share/lintian/commands/lintian line 73.
BEGIN failed--compilation aborted at /usr/share/lintian/commands/lintian line 73.

Lintian finished with exit status 255
```

**Comment by denadaisicari** [comment]
Same issue, I solved with:
```
sudo apt-get update
sudo apt-get clean
sudo apt-get autoremove
sudo apt-get -f install
```
For me was missing git and some libs.

**Comment by SumNeuron** [comment]
I'm also having issues. I have tried a myraid of ways and solutions to get atom onto ubuntu 17, it just doesnt work.  The above solutions allow me to install atom but running it gives me broken html (unless I run with sudo). For a while, running whatever version of atom is under snap worked, but now that is also broken. Even when running via sudo, atom behaves very janky (not opening always) and when open crashing on resize, etc. 

No idea what is going on, I hope it gets fixed.

**Comment by Yelsin1** [comment]
I have tried all the commands i can't still install it on Zorin OS which is based on Ubuntu.

`~/Downloads$ sudo dpkg --install atom-amd64.deb
Selecting previously unselected package atom.
(Reading database ... 325612 files and directories currently installed.)
Preparing to unpack atom-amd64.deb ...
Unpacking atom (1.25.1) ...
dpkg: dependency problems prevent configuration of atom:
 atom depends on git; however:
  Package git is not installed.

dpkg: error processing package atom (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 atom
`

**Comment by alkisg** [comment]
This worked fine for me:
`apt install /tmp/mozilla_alkisg0/atom-amd64.deb`
apt installs dependencies, dpkg -i doesn't.

**Comment by isidro704** [comment]
i have a problem with istallation of atom and this is the error that  i obtain:

```
sudo dpkg -i atom-amd64.deb
Seleccionando el paquete atom:amd64 previamente no seleccionado.
(Leyendo la base de datos ... 144031 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar atom-amd64.deb ...
Desempaquetando atom:amd64 (1.30.0) ...
dpkg: problemas de dependencias impiden la configuración de atom:amd64:
 atom:amd64 depende de libgtk-3-0 (>= 3.9.10).
 atom:amd64 depende de libudev0 | libudev1.
 atom:amd64 depende de libnotify4.
 atom:amd64 depende de libxtst6.
 atom:amd64 depende de libnss3 (>= 2:3.22).
 atom:amd64 depende de python.
 atom:amd64 depende de libcap2.
 atom:amd64 depende de libx11-xcb1.
 atom:amd64 depende de libxss1.
 atom:amd64 depende de libasound2 (>= 1.0.16).
 atom:amd64 depende de libxkbfile1.

dpkg: error al procesar el paquete atom:amd64 (--install):
 problemas de dependencias - se deja sin configurar
Procesando disparadores para gnome-menus (3.13.3-9) ...
Procesando disparadores para desktop-file-utils (0.23-1) ...
Procesando disparadores para mime-support (3.60) ...
Se encontraron errores al procesar:
 atom:amd64
```

**Comment by rishabhdeepsingh** [comment]
I am facing the same error. ```whiteknife@kali:~/Downloads$ sudo dpkg -i atom-amd64.deb
Selecting previously unselected package atom.
(Reading database ... 341276 files and directories currently installed.)
Preparing to unpack atom-amd64.deb ...
Unpacking atom (1.30.0) ...
dpkg: dependency problems prevent configuration of atom:
 atom depends on gconf2; however:
  Package gconf2 is not installed.
 atom depends on gconf-service; however:
  Package gconf-service is not installed.

dpkg: error processing package atom (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-11) ...
Processing triggers for desktop-file-utils (0.23-3) ...
Processing triggers for mime-support (3.61) ...
Errors were encountered while processing:
 atom
```
After running ```sudo apt --fix-broken install``` It just delets the atom what to do?

**Comment by gwvt** [comment]
After unsuccessfuly trying everything above, the directions [here](https://www.admintome.com/blog/install-atom-ubuntu-18-04/) finally worked for me.

**Comment by r-trigo** [comment]
I had the same problem when upgraded to Ubuntu 20.04. I could install Atom and work with it, but that would break APT. To fix and use APT I had to remove Atom. Ended up installing Atom by Ubuntu Software app. Working fine now.

```
> sudo apt install atom      
       
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 atom : Depends: python but it is not installable
E: Unable to correct problems, you have held broken packages.
```

```
> sudo dpkg -i atom-amd64.deb 

Selecting previously unselected package atom.
(Reading database ... 223040 files and directories currently installed.)
Preparing to unpack atom.deb ...
Unpacking atom (1.45.0) ...
dpkg: dependency problems prevent configuration of atom:
 atom depends on libgconf-2-4 (>= 3.2.5) | libgconf2-4; however:
  Package libgconf-2-4 is not installed.
  Package libgconf2-4 is not installed.
 atom depends on python; however:
  Package python is not installed.

dpkg: error processing package atom (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 atom
```

**Comment by cristianogregnanin** [comment]
same problem like @r-trigo

**Comment by ErrorBot1122** [comment]
why does this say Closed when the issue is not solved yet?
