### ISSUE TITLE
Precompiled binary 'mksnapshot' breaks building process (Centos 6.x).

### ISSUE THREAD

**Issue by dm-blue** [atom/atom#14354]
Hi,
Starting with 1.17.0, the building process on a Centos 6.x machine is not working anymore.
Everything is crashing on snapshot creation:
..............
Verifying if snapshot can be executed via `mksnapshot`
Generating startup blob at "atom-1.17.0-beta4/out/snapshot_blob.bin"

atom-1.17.0-beta4/script/node_modules/electron-mksnapshot/bin/mksnapshot: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by atom-1.17.0-beta4/script/node_modules/electron-mksnapshot/bin/mksnapshot)

Error: Command failed: atom-1.17.0-beta4/script/node_modules/electron-mksnapshot/bin/mksnapshot atom-1.17.0-beta4/out/startup.js --startup_blob atom-1.17.0-beta4/out/snapshot_blob.bin
............
It seems that with this version, the building procedure calls a PRECOMPILED BINARY 'mksnapshot', not compiled during the building stage as other tools as before. By using a precompiled tool during building process, the portability is broken. I have no problems to run 'atom' in a different root environment (avoiding `GLIBCXX_3.4.15' not found` issues), but I cannot do this during the building procedure.

System: Centos 6.x (supported until the end of 2020).
atom: v1.17.0-beta4
nodejs: v6.10.3
npm: v3.10.10

I am not happy with precompiled tools during building process (like electron-mksnapshot), I consider this as a bad decision. It should be compiled during building process, not using precompiled binaries.

**Comment by 50Wliu** [comment]
Even if you get past that part Atom will still be unable to run because it has other dependencies on glibcxx 3.4.x.  See #2177 for more details.

**Comment by dm-blue** [comment]
Wrong !
I'm running atom on Centos 6.x since alpha versions (0.x.x) and works fine, even with 1.16.x !
The clue is to add the glibc-2.14 libraries in the applications path, just like google chrome and other applications !
