### ISSUE TITLE
Atom portable v 1.15.0 x64 could not upgrade to v1.16.0 on windows

### ISSUE THREAD

**Issue by nwanglu** [atom/atom#14362]
![image](https://cloud.githubusercontent.com/assets/11607990/25744765/2513cc6c-31ce-11e7-8675-671218cf7fc0.png)

As image attached no update option, is upgrade for portable version on windows disabled?

**Comment by nwanglu** [comment]
Updater is not working for previous portable version also.

**Comment by rsese** [comment]
Thanks for the report @nwanglu - for future issues, please completely fill out the issue template, it's very helpful for us when triaging issues.

I installed 1.15.0 as a portable version on Windows and didn't see an option to check for updates on the About page or the `Help` menu either.  Should updating with the portable version be possible @damieng or do you need to download the new version manually?

**Comment by damieng** [comment]
Portable installations have to be manually updated (at least on Windows, I'm not sure about mac)

The update system we used is based on Squirrel which has very specific ideas about where binaries live and get installed to on Windows.
