### ISSUE TITLE
Toggle Tree Side does not work on atom beta 1.17.0-beta5

### ISSUE THREAD

**Issue by 34code** [atom/atom#14368]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tree View side toggling does not work on macOS Sierra for atom beta 1.17.0-beta5

### Steps to Reproduce

1. Go to Packages > Tree View > Toggle Tree Side
2. Observe Tree View side is not changed

**Expected behavior:** [What you expect to happen]

Expect Tree View Side to toggle from left to right

**Actual behavior:** [What actually happens]

No toggling

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

atom beta - 1.17.0-beta5 on macOS Sierra OSX 10.12.4

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
This option was removed as you can now drag the Tree View to the right side of the window.

**Comment by BM5k** [comment]
First: Why does this command still exist if it does nothing?

The `Show On Right Side` option is still in Tree View package settings in the 1.17.0 release & it _also does nothing_.

This is unexpected AND frustrating. The tree view location is reset to the left when launching 1.17.0 for the first time, even if it was previously set to display on the right. None of the options that used to move it to the right side work, yet they still exist for some reason. 

> you can now drag the Tree View to the right side of the window.

Is neither obvious nor intuitive.

I managed to totally bork the UI before managing to figure out how to do this. Lost a lot of time trying to un-bork the UI. Still have the tree view on the left.

**Comment by 50Wliu** [comment]
> Why does this command still exist if it does nothing?

The setting [was removed](https://github.com/atom/tree-view/commit/9a70d1ea19c18c15bc3ecc539ab25c8436fbb4fa#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L48); what you're seeing is the fact that Atom will show you the entirety of your `config.cson`, regardless of whether the settings actually do anything.  However, it appears to be unintentional that the setting is ignored when upgrading.  Please feel free to file a new issue regarding that on the [atom/tree-view](https://github.com/atom/tree-view) repository.

Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762
