### ISSUE TITLE
Snippets take longer to load in larger files

### ISSUE THREAD

**Issue by eranimo** [atom/atom#14365]
### Description

When using snippets in large files, the snippet dropdown takes a noticeably longer period of time to appear.

### Steps to Reproduce

1. Open a large file (over 1000 lines seems to do it for me)
2. Use a snippet
3. Observe that the snippet dropdown appears after a delay

**Expected behavior:** Snippet dropdown should open immediately

**Actual behavior:** Snippet dropdown takes a few seconds to appear

**Reproduces how often:** Every time I use a snippet in a large file

### Versions

```shell
$ atom --version
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.11.0
```

### Additional Information

I can understand why autocomplete in general would take a while to load, but snippets shouldn't need to read the whole file to load -- they should appear immediately.

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/autocomplete-snippets if there's no existing issue already so we have it in the right place?  I think that's the best repo for this...also, if you can completely fill out the issue template that would be great (e.g. check-off the prerequisite section that lets us know if you tried in safe mode, add your operating system details, etc.).
