### ISSUE TITLE
1.17.0-Beta4 - Syntax highlighting fails on large flies

### ISSUE THREAD

**Issue by jarheck** [atom/atom#14363]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Large files do not show syntax highlighting, I have tried multiple files with more than 150,000 lines and no matter what I do it will not highlight the text correctly. I have found if you cut all the text out of the file, then past it into a new file, scroll to the top, it will highlight correctly (but not once you save and open the file again). The only way I can get the highlight to work consistently is when I physically shrink the file to ~50k lines.

### Steps to Reproduce

1. [First Step]
Open a large C, Java, XML, or some other syntax aware file (150,000 lines or more)
2. [Second Step]
Note that the text has no syntax highlighting even though the correct language is detected

**Expected behavior:** [What you expect to happen]
When opening a large text files (150k+ lines) the text is highlighted correctly based on the selected syntax.
**Actual behavior:** [What actually happens]
All text has no highlighting, only when shrinking the file to ~50k lines did highlighting start to function again.
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
1.17.0-Beta4 c64
Windows 7 x64

**Comment by Zireael07** [comment]
Does the file have any long lines?

**Comment by jarheck** [comment]
Here is a dummy XML file I created, it has the same issues as the files I have been working with. On a side note I had to create the file in Notepad++ as Atom crashed trying to save it.

[GenericXML2.zip](https://github.com/atom/atom/files/979070/GenericXML2.zip)

**Comment by ChristianLutz** [comment]
This already happens for me with Atom 1.16. I just open a large XML File as mentioned and it won't be highlighted. Small files however are working. Maybe this helps.

**Comment by chrisvio** [comment]
Atom treats all "large" files, anything over 2048K, as plain text.

**Comment by 50Wliu** [comment]
Thanks @chrisvio.
