### ISSUE TITLE
Theme Atom Material Issue!

### ISSUE THREAD

**Issue by Encr1pt3d** [atom/atom#14373]
Hi friends,

I found an issue when I was programing with Atom my Laravel backend in the .blade.php files. Some tags are not colored right, look the pictures:

Look the tag "value"
https://gyazo.com/37c998e2c52df0959fcefb63d22352c3
![image](https://cloud.githubusercontent.com/assets/7103591/25808498/8e7f9ca6-340a-11e7-8a78-69798e862954.png)

https://gyazo.com/9bf97a06f498365d5042bb2e7861e235
![image](https://cloud.githubusercontent.com/assets/7103591/25808510/95d7561a-340a-11e7-8f19-ba44fdbb70de.png)

Other issue, look the "span" tag
![image](https://cloud.githubusercontent.com/assets/7103591/25808492/894f1ce8-340a-11e7-8bbd-7c7769ac568f.png)

**Comment by 50Wliu** [comment]
You should report this to whatever package you are using to highlight Laravel files.

**Comment by Encr1pt3d** [comment]
Thanks!
