### ISSUE TITLE
Atom 64-bit and grammar rule crashing Windows 10 machine

### ISSUE THREAD

**Issue by MattyBalaam** [atom/atom#14399]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

A combination of Atom 64-bit on Windows and the Atom-Silverstripe language plugin causes memory usage in Atom to rocket up at a huge rate before eventually crashing the whole OS.

### Steps to Reproduce

1. Intall https://atom.io/packages/atom-silverstripe
2. Enter in a $ symbol

**Expected behavior:** Syntax in the format `$xx` is highlighted

**Actual behavior:** Editor freezes, and memory usage increases dramatically before crashing entire OS (video freeze, audio buffer looping)

**Reproduces how often:** Always

### Versions

Atom 1.16.0 x64 running on Windows 10. 

Originally I noticed this on my own Windows 10 box, but have just reproduced using VirtualBox and an official Microsoft machine. Edge on Win10 (x64) Stable (14.14393). Just fresh Atom installation and this package.

### Additional Information

The line which causes issues is in a .cson grammar file.

` 'match': '\\$(\\.?[a-zA-Z0-9]*(\\([a-zA-Z0-9\'\, ]*\\))*)*'`

I have also reported on the package repo: https://github.com/gorriecoe/atom-silverstripe/issues/7

I could not reproduce on Windows 7 with 32-bit Atom or MacOS.

**Comment by rsese** [comment]
I can reproduce this as well on Windows 10, Atom 1.16.0 though the OS doesn't crash for me.  After using the grammar selector to choose `HTML (Silverstripe)`, I enter `$` and Atom freezes for ~10-15 seconds and task manager shows a CPU and memory spike.  But the `$` does show up after ~10-15 seconds and then Atom settles down a bit until I enter another `$`. 

I started Atom in the foreground with `atom -f` and I did see this (can also see it in console):

```
[4452:0512/130359:INFO:CONSOLE(170)] "Popping rule because it loops at column 0 of line '$'", source: C:\Users\IEUser\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\first-mate\lib\grammar.js (170)
```

Searching around for "Popping rule because it loops", I ended up at https://github.com/atom/first-mate/issues/11 where it seems like a change was made to prevent a crash in cases like this?

**Comment by enoversum** [comment]
Unfortunately, it doesn't seem to be limited to your used package here. I never touched it, but CPU and memory spikes with the latest 1.8 beta are really intense and huge. It jumps up, sometimes to 99% usage of both, stays there for some moments, then down again. I can see it when sass-autocompile is running and compiling a file, it mostly spikes up to ~50% of my CPU and memory.

**Comment by enoversum** [comment]
@MattyBalaam Just read the Pigments package is causing such problems, any chance you happen to have that installed and active?

**Comment by MattyBalaam** [comment]
@enoversum I got the issue above on a totally fresh install with atom-silverstripe as the only extra plugin. Do you have any links to this issue?

**Comment by enoversum** [comment]
@MattyBalaam Oh, okay, so that might be something unrelated, though it as well turned up with the new beta version. Find the issue [here](https://github.com/abe33/atom-pigments/issues/308).

**Comment by MattyBalaam** [comment]
@enoversum This issue manifests at least as far back as 1.6 64-bit.

**Comment by wismill** [comment]
I encountered the same issue with the plugin `language-sparql`. This is a *really serious issue* that makes Atom unusable. I am using Atom 1.19.3 on Windows 10 (1703) 64 bit.
