### ISSUE TITLE
v1.16.0/Dockerfile script/build error

### ISSUE THREAD

**Issue by jcalfee** [atom/atom#14394]
https://github.com/atom/atom/blob/v1.16.0/Dockerfile
```bash
git checkout v1.16.0
docker build -t atom .
docker run -i -t atom bash
script/build --create-debian-package
...
make: Entering directory '/atom/node_modules/keyboard-layout/build'
  CXX(target) Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o
keyboard-layout-manager.target.mk:96: recipe for target 'Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o' failed
make: Leaving directory '/atom/node_modules/keyboard-layout/build'

...

In file included from ../src/keyboard-layout-manager-linux.cc:1:0:
../src/keyboard-layout-manager.h:7:22: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
                      ^
compilation terminated.
make: *** [Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o] Error 1
```

**Comment by andyrichardson** [comment]
I've looked at the Dockerfile and its using a fairly old version of Fedora. I'm not sure building deb packages in Fedora is supported nor advised.

Also, looking at the build instructions there's no mention of docker so I suspect contained builds are no longer in use/supported.

Are you able to [build outside of a contained environment](https://github.com/atom/atom/blob/v1.16.0/docs/build-instructions/linux.md)?

**Comment by jcalfee** [comment]
I'm building inside of the docker so I don't cause other version problems on my computer.  Also helps with security.

**Comment by jcalfee** [comment]
When I get a chance I look into updating the docker with the link you provided.
