### ISSUE TITLE
keymap handles case inconistently

### ISSUE THREAD

**Issue by NickAnderegg** [atom/atom#14396]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The behavior of the keymap and how it handles letter case is inconsistent. Setting a keykinding to the following values responds when the listed keys are pressed:

- `cmd-shift-P`: cmd-shift-p
- `cmd-P`: cmd-shift-p
- `cmd-shift-p`: cmd-shift-p

When a capital letter is listed in the keymap, `shift` must be pressed to use that command, meaning that all commands `x-shift-p`, `x-shift-P`, and `x-P` are effectively the same. This is an inconsistency because listing a capital letter forces an implied `shift` key to be used, while using a lowercase letter and listing an explicit `shift` key is fine.

Thus:

- `cmd-shift-p == cmd-shift-P`
- `cmd-p != cmd-P`
- `cmd-shift-p == cmd-P`

### Steps to Reproduce

1. In `keymap.cson`, add the lines:

```
'atom-workspace atom-pane':
  # 'cmd-shift-P': 'pane:decrease-size'
  # 'cmd-shift-p': 'pane:decrease-size'
  # 'cmd-P': 'pane:decrease-size'
  # 'cmd-p': 'pane:decrease-size'
```
2. Uncomment each line individually and try pressing the combinations:

- `command, shift, p`
- `command, p`

to see how Atom responds to each.

**Expected behavior:**

- The pane decreases when either of the lines `cmd-shift-P` or `cmd-shift-p` are uncommented and `command, shift, p` are pressed.
- The pane decreases when either of the lines `cmd-P` or `cmd-p` are uncommented and `command, p` are pressed.

**Actual behavior:**

- The pane decreases when any of the lines `cmd-shift-P`, `cmd-shift-p`, `cmd-P` are uncommented and `command, shift, p` are pressed.
- The pane decreases when the line `cmd-p` is uncommented and `command, p` are pressed.

**Reproduces how often:** Consistently according to this pattern.

### Versions

```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

n/a

**Comment by 50Wliu** [comment]
I'm not entirely sure what the inconsistency here is, but the behavior you're describing is expected.  The keymap is case-sensitive and translates capital letters into their shift+lowercase variant.
