### ISSUE TITLE
TitleBar (MacOS) - custom titlebar doesn't implement path or document proxy

### ISSUE THREAD

**Issue by mrstux** [atom/atom#14390]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

New custom MacOS TitleBar does not implement support for standard path popup or drag-n-drop document proxy, as per standard titlebars.

### Steps to Reproduce

1. Switch to custom title bar on macos and restart
2. open a document
3. cmd-click in document title in titlebar. A path pop up should appear, but doesn't.
4. drag the document icon, a document proxy should appear for drag and drop, but doesn't.

**Expected behavior:** [What you expect to happen]

I expect the path popup to appear, as it does in default mode, and I expect the document proxy to appear, as it does in default mode.

**Actual behavior:** [What actually happens]

Neither appear. This is perhaps refered to by "Custom" will affect functionality, but as nice as it is, this is a bridge to far, i'm just wondering if the authors are unaware of this default behaviour.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

1.16.0 x64 for Mac OS X.

**Comment by simurai** [comment]
> i'm just wondering if the authors are unaware of this default behaviour.

Yes, it got pointed out here: https://github.com/atom/atom/pull/11790#issuecomment-222168228. 

There is now this note in the settings:

![screen shot 2017-05-11 at 10 40 11 pm](https://cloud.githubusercontent.com/assets/378023/25952198/f314340a-369a-11e7-8b96-47b34e262ac2.png)

Meaning that, you're free to switch to a custom title bar, but some functionality (like dragging the icon or opening the dropdown) won't work. There aren't any short-term plans to reimplement these features, so I'm gonna close this as `wontfix`.

@mrstux thanks for pointing it out, though. 🙇
