### ISSUE TITLE
TextEditor::getPath() can return incorrect case on case-insensitive filesystems

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#14402]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you are on a case-insensitive file system such as Windows or OS X and Atom is opened from the CLI using a path that doesn't match the case of the folder/file in question, the file opens but Atom reports the wrong case.

### Steps to Reproduce

1. Have a directory and file with differing cases on a case in-sensitive filesystem.
    * For example: `C:\Temp\CapDir\CapFile.txt` on Windows.
2. Open Atom using the wrong case for the directory.
    * For example: `atom C:\temp\capdir`
3. Open the file in the directory
4. Run `atom.workspace.getActiveTextEditor().getPath()` from the Developer Tools and note the incorrect case on the path.

**Expected behavior:**

Running the above command should output `C:\Temp\CapDir\CapFile.txt` regardless of what command was used to launch Atom.

**Actual behavior:**

Any part of the path that was manually specified is taken as verbatim and not corrected to reflect the actual case on the file system. The above steps for example show `C:\temp\capdir\CapFile.txt` as the path to the file.

This causes problems with packages that rely on the correct path, including the case, to be returned such as linters that check for cross platform case issues on case-insensitive filesystems where it would normally not show for the user.

**Reproduces how often:**

100% of the time.

### Versions

Tested locally on Windows 10 x64:
Atom    : 1.17.0-beta5
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

Note that this investigation initially started from a user on macOS Sierra 10.12.3 (16D32) in https://github.com/benmosher/eslint-plugin-import/issues/831.

### Additional Information

Any part of the path that _isn't_ manually specified is handled correctly, for example if the CLI is in `C:\Temp` and Atom is called with `atom capdir` then the resulting path is `C:\Temp\capdir\CapFile.txt`.

Related to https://github.com/atom/atom/issues/8221.

Tagging @lee-dohm as requested.

**Comment by damieng** [comment]
While this might seem a simple thing to do it's actually very tricky as there is no facility built into node to achieve this at the file system level. 

Some people have written javascript code to 'achieve' this but they fall short of being able to accurately reflect that file system semantics when it comes to things such as the subtleties of case between languages and unicode normalization across the various filetypes.
