### ISSUE TITLE
Jelly code not being highlighted

### ISSUE THREAD

**Issue by ssbarnea** [atom/atom#14400]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It seems that atom does not recognize files with `.jelly` extension and there is no plugin that adds support for them.

### Steps to Reproduce

You can find a simple jelly file at https://wiki.jenkins-ci.org/display/JENKINS/Basic+guide+to+Jelly+usage+in+Jenkins

**Comment by 50Wliu** [comment]
Unfortunately, the Atom team only has finite resources, and as such does not have the bandwidth to create and maintain a Jelly language package.  You may want to ask on [Discuss, the Atom forum](https://discuss.atom.io) to see if there is any interest in creating such a package.

**Comment by ssbarnea** [comment]
Jelly is XML based, so adding jelly to the list of extensions for xml would be a good enough solution.

**Comment by 50Wliu** [comment]
If it is XML without any custom syntax, feel free to create either an issue or a pull request on the [atom/language-xml](https://github.com/atom/language-xml) repository.
