### ISSUE TITLE
No search results from directories with commas

### ISSUE THREAD

**Issue by gee4vee** [atom/atom#14404]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If a directory has commas in a folder name somewhere in the path, you get 0 search results. This seems similar to #8225.

### Steps to Reproduce

1. Create a directory path with commas in one of the folder names.
2. Add files to the folder or one of the subfolders.
3. Perform a search in Find In Project.

**Expected behavior:** 1 or more search results

**Actual behavior:** 0 search results

**Reproduces how often:** 100%

### Versions

1.16.0

### Additional Information

I confirmed it is because of commas by renaming the folder, changing the commas to underscores. I immediately got search results. The folder path does have periods in it as well.

**Comment by rsese** [comment]
Move to https://github.com/atom/find-and-replace/issues/893 :v:
