### ISSUE TITLE
Creating a file is not possible under macOS/OSX Sierra

### ISSUE THREAD

**Issue by changeyourstrings** [atom/atom#14408]
When i try to create a new file under OSX by pressing rightclick in the left hand side project explorer using "New File", a box opens and i enter a File name. Pressing the return key on my keyboard does not finish this action. Consequently the file cannot be created .

**Comment by Ben3eeE** [comment]
* What is the contents of your `keymap.cson`?
* Do you see the same error in safe mode `atom --safe`?

**Comment by changeyourstrings** [comment]
keymap overwrote the enter for editor: 'enter': 'editor:newline'
thanks!
