### ISSUE TITLE
Can't install packages and themes

### ISSUE THREAD

**Issue by bogdanostojic** [atom/atom#14407]
### Fetching featured packages failed.

module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\Users\SPACE\AppData\Local\atom\app-1.16.0\resources\app\apm\lib\cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

### Description

When i open the settings tab to install packages or  themes, or even the packages and theme tab cant load the  installed, it just says loading packages/themes... 

### Steps to Reproduce

1. I first tried uninstalling, reseting then installing again a newly downloaded atom.exe file. Same error
2. Uninstalled node.js then i got this error : 
  'node.exe' is not recognized as an internal or external command, operable program or batch file.
  Installed the newsest LTS from the site V6.10.3, same error as the first time.

### Versions

Windows 10 Education 64-bit
Version : 1607
OS Build : 14393.1198

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/settings-view if there's no existing issue already so we have it in the right place?  Also, please make sure to completely fill out the issue template including the Prerequisites section so we know that you've tried the baseline debugging steps.

**Comment by bogdanostojic** [comment]
Dang, my bad. Posted in /settings-view with more info
