### ISSUE TITLE
Line break after saving file

### ISSUE THREAD

**Issue by iamtodor** [atom/atom#14411]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom adds useless line break after saving file.

### Steps to Reproduce
Following steps are intended to terminal:
1. touch test
2. atom test
3. add some text into the first line of the file
4. press save (cmd+s)
5. the see second line in use

**Expected behavior:** 
See only lines, that I write

**Actual behavior:**
Atom adds line break

**Reproduces how often:**
10/10

### Additional Information
atom version:
```
Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

macos: `10.12.4`

**Comment by ibujs** [comment]
Isn't that normal behavior? ESLint in fact has a rule requiring you to add a line break and it's true everywhere including the ESLint:recommended configuration.

**Comment by tangledhelix** [comment]
The [whitespace][] package will do that by default. You can disable it using a checkbox in the package settings for that package. It's a core package, so it ships with all installs of Atom.

[whitespace]: https://atom.io/packages/whitespace

**Comment by lee-dohm** [comment]
As @tangledhelix stated, this is a feature of the [whitespace package](https://atom.io/packages/whitespace) and is intended behavior. Follow these instructions to disable the behavior:

1. Launch Atom
1. Open Settings View using <kbd>Cmd+,</kbd> on macOS or <kbd>Ctrl+,</kbd> on other platforms
1. Click the Packages tab
1. Search for "whitespace"
1. Click the Settings button on the whitespace package's card
1. Uncheck "Ensure Single Trailing Newline"

**Comment by iamtodor** [comment]
@lee-dohm thank you, it works
