### ISSUE TITLE
package-manager.js uncaught

### ISSUE THREAD

**Issue by d0ruk** [atom/atom#14412]
Hello,

![screenshot from 2017-05-14 18-57-41](https://cloud.githubusercontent.com/assets/4752656/26035567/3cd2ac46-38d7-11e7-9cab-b20e04877453.png)

When I'm on the Settings > Updates section, If I decide to remove one of the packages that require updating, and then pressing "Update All", this is what I get;

![screenshot from 2017-05-14 18-59-40](https://cloud.githubusercontent.com/assets/4752656/26035577/8bedd440-38d7-11e7-970f-660e6d1c5f80.png)

[Here](https://github.com/atom/atom/blob/master/src/package-manager.coffee#L543) it is, if you want.

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/settings-view if there's no existing issue already so we have it in the right place?  Also, please make sure to completely fill out the issue template including the Prerequisites section so we know that you've tried the baseline debugging steps.
