### ISSUE TITLE
"Find in project" output does not show matching lines in all cases

### ISSUE THREAD

**Issue by sbromberger** [atom/atom#14430]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using `1.18.0-beta0` downloaded today, I attempted to do a Find In Project. Three files matched; only the first file's lines were displayed. See screenshot.

### Steps to Reproduce
1. Open project
2. Find -> Find in Project -> enter search term
3. Expand all results.

**Expected behavior:** [What you expect to happen]

Results should display the instances of the found text.

**Actual behavior:** [What actually happens]

Results do not display all instances of the found text.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% when the found text is in a comment block.

### Versions
1.18.0-beta0

### Additional Information

see screenshot.

<img width="676" alt="screen shot 2017-05-16 at 12 39 40" src="https://cloud.githubusercontent.com/assets/941359/26124847/d802f7b2-3a34-11e7-8efd-6ebb2a4ba13e.png">

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/find-and-replace if there's no existing issue already so we have it in the right place?  Also if possible, would you be able to share that LICENSE.md file in the issue?

**Comment by sbromberger** [comment]
Sorry! I didn't realize that find-and-replace was a separate module. I'll reopen there.

**Comment by rsese** [comment]
Np, thanks for re-opening :bow:
