### ISSUE TITLE
Snapshot + Compile cache breaks linter-xo (and causes some unexpected behaviour)

### ISSUE THREAD

**Issue by forivall** [atom/atom#14434]
### Description

https://github.com/sindresorhus/atom-linter-xo/issues/74#issuecomment-301923088

Through more investigation in the debugger, the issue isn't seen when
* run in dev mode (which disables snapshots) or
* disabling the NativeCompileCache
  * in the debugger, setting a breakpoint after `NativeCompileCache.install()` (https://github.com/atom/atom/blob/master/static/index.js#L62) stepping over to the next line, and then running `NativeCompileCache.uninstall()` in the console.

### Steps to Reproduce

install the following packages:
```
» apm ls -i

Community Packages (5) ~/.atom/packages
├── busy-signal@1.4.1
├── intentions@1.1.2
├── linter@2.1.4
├── linter-ui-default@1.4.0
└── linter-xo@0.23.0
```

clone [forivall/node-module-template]

`npm install`

put `'use strict';` in index.js

lint.

**Expected behavior:**

no error should be seen.

**Actual behavior:**

the linter complains that the unicorn rules are not seen.

**Reproduces how often:** always

[screencast](https://imgur.com/a/zBnfy)

### Versions
```
» atom --version && apm --version
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.13.0
```
OSX 12.2.4

### Additional Information
i also deleted ~/.atom/compile-cache , with no luck.

**Comment by forivall** [comment]
This was caused due to improper use of `import-modules` (aka `req-all`), and its use of `require.parent` and has since been fix by making sure that absolute paths are used when using it. 

https://github.com/sindresorhus/atom-linter-xo/issues/74#issuecomment-309194910

**Comment by sindresorhus** [comment]
@forivall This shouldn't be closed. We just worked around it in `atom-linter-xo`. It should still be fixed in Atom. Using `module.parent` is a [very common pattern](https://github.com/search?utf8=%E2%9C%93&q=%22module.parent.filename%22&type=Code) in Node.js.

**Comment by sindresorhus** [comment]
ping @forivall
