### ISSUE TITLE
Unable to switch the encoding

### ISSUE THREAD

**Issue by irudoy** [atom/atom#14438]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since version 1.17.0 switching encoding to Windows 1251 working incorrectly. Selected encoding changes in the status bar, but cyrillic characters still ���.
 
Also, I have an error in the console: `TypeError: iconv.decodeStream is not a function`.

### Steps to Reproduce

1. Create file with contents: `абвгдеёжзфывапролджэ`
2. Save file and close
3. Re-open file in the Atom
4. Select Windows 1251 encoding

**Expected behavior:** `абвгдеёжзфывапролджэ`

**Actual behavior:** `���������`

**Reproduces how often:** always

### Versions

1.17.0
1.18.0 beta

**Comment by pluto1019** [comment]
please~~ same problem~~
my file encoding 'euc-kr' same problem~
not change~

**Comment by 50Wliu** [comment]
This issue was moved to atom/encoding-selector#48
