### ISSUE TITLE
Keystrokes lost when dock shows up

### ISSUE THREAD

**Issue by piuccio** [atom/atom#14439]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since updating to Atom 17 (earlier today) typing got weird when a new dock appears.

Linter package now uses the dock at the bottom to show errors and warnings. Every time this new dock appears, the main view either looses focus or lags behind, with the effect that a few keystrokes are lost

### Steps to Reproduce

1. Install Linter package 
2. Open a valid JS file
3. Start typing some rubbish quickly
4. Linter will start complaining
5. Notice how some of the characters you pressed don't appears on screen

**Expected behavior:** Every key press should end up in the editor

**Actual behavior:** I get upset

**Reproduces how often:** Every single time the lint dock shows up

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

Linter: 2.1.4
Linter-ui-default: 1.4.0

### Additional Information

Not sure if it's a problem in linter, but you might want to look into the creation of docks

**Comment by Positive07** [comment]
> Every key press should end up in the editor

What about console docks? Or other docks with inputs?

Also kinda related, clicking on the bottom dock, makes the dock lose focus and the focus goes back to the editor, closing the dock... Which is not intended, if the dock needs focus this behaviour is bad

Atom 1.18 beta (x64 Windows 10)

**Comment by ericeslinger** [comment]
Yah, I'm experiencing the same thing - I had thought it was a typescript thing: TypesStrong/atom-typescript#1260 but it seems more general to the bottom dock. Disabling tslint in my case fixes the problem, but now I don't have my linter anymore.

**Comment by piuccio** [comment]
I don't know if this is still a problem because in the meantime linter has moved from using the dock to contextual tooltip
