### ISSUE TITLE
Geometry support

### ISSUE THREAD

**Issue by mrichman** [atom/atom#14449]
I often need to record screencasts with Atom, and need it in a specific position and size on screen. 

Most X11 based application allow for a `-geometry` switch.

I realize Atom is Electron-based, and not X11. However, is it possible to support this switch?

Perhaps as follows:

`atom --geometry 1280x720-37+50`

where the value is `[{WIDTH}][x{HEIGHT}][{+-}{XOFF}[{+-}{YOFF}]]`

**Comment by JHonaker** [comment]
I don't think this is really necessary. Simply add a command like

    atom.commands.add 'atom-workspace',
        'custom:prepare-for-screencast': ->
            atom.setSize(1280, 720)
            atom.setPosition(37, 50)

to your init.coffee. You can call `Prepare for screencast` from the Command palette.

**Comment by mrichman** [comment]
This worked perfectly! Thanks.
