### ISSUE TITLE
HTML Syntax awareness inside script tags

### ISSUE THREAD

**Issue by wraytw** [atom/atom#14451]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Html is not highlighted between script tags in html files.

I'm working on a project with Ractive (http://www.ractivejs.org/) and ractive requires html inside script tags to work. However, the HTML written inside the script tags is not being syntactically highlighted in Atom. I can't seem to find any workaround for this.

![ractive](https://cloud.githubusercontent.com/assets/15827892/26158893/5b488006-3ada-11e7-88af-422bcc10a17a.png)

### Steps to Reproduce

1. Install Atom
2. Write HTML syntax inside script tags
3. [and so on...]

### Versions

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by 50Wliu** [comment]
You need to install a language package that adds support for Ractive.
