### ISSUE TITLE
Python `elif` unindent is over-eager when following commented, unindented lines

### ISSUE THREAD

**Issue by ShadowLNC** [atom/atom#14452]
### Prerequisites

* [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [ ] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [ ] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom automatically unindents an `elif` line with Python code when it believes the user has erroneously over-indented the line. If a commented line skews indentation before the `elif`, Atom will still unindent a correctly indented line.

### Steps to Reproduce

1. Write a Python `if` statement (conditionally executed code should be on a new line)
2. Add a commented line which has at least one level of indentation, but is less than the code inside the `if` condition
3. Add an `elif` condition, completed by typing the `:` (colon)

Example code:

    def myfunc():
        for i in range(5):
            if i%2:
                pass
            # A comment here
            elif i%3

**Expected behavior:** Indent for the `elif` line should not be altered (when the colon is typed).

**Actual behavior:** The line is unindented such that its level is one indentation less than the line above.

**Reproduces how often:** 100%

### Versions

    Microsoft Windows [Version 10.0.15063]
    (Win 10 Pro 64-bit, Creators Update)

    C:\Users\Scott>atom --version
    Atom    : 1.17.0
    Electron: 1.3.15
    Chrome  : 52.0.2743.82
    Node    : 6.5.0

    C:\Users\Scott>apm --version
    apm  1.17.0
    npm  3.10.5
    node 6.9.5 ia32
    python 3.5.2
    git 2.11.1.windows.1.2.g87ad093
    visual studio

### Additional Information

This can be reproduced by adding any character to the line, as long as the line begins with `elif` (excluding whitespace) and contains a colon.

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/language-python](https://github.com/atom/language-python) repository if an issue doesn't already exist for the bug you're describing.
