### ISSUE TITLE
'font-size' in atom-workspace

### ISSUE THREAD

**Issue by binhonglee** [atom/atom#14466]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There are no option to set the font-size for atom-workspace (everything outside of atom-text-editor) unless you use a theme that supports those changes (like [Atom Material UI](https://atom.io/themes/atom-material-ui) or [One Dark UI](https://atom.io/themes/one-dark-ui) ). Setting 'font-size' in atom-workspace does not change anything while setting 'font-family' changes it for most themes. 

The current workaround taken from the [forum](https://discuss.atom.io/t/font-size-in-atom-1-17/42782/2) is to do the following each time you change a theme and see if it works with that theme.

```less
.theme-atom-material {
    font-size: 20px;
}
```

Felt like the interaction is pretty confusing at this point.

### Steps to Reproduce

1. Open styles.less
2. Set 'font-size' for atom-workspace
```less
atom-workspace {
    font-size: 15px;
}
```
2. Save styles.less
3. Change the 'font-size' value
```less
atom-workspace {
    font-size: 20px;
}
```
4. Save styles.less

**Expected behavior:** The workspace font size changes according to the value set.

**Actual behavior:** Nothing happens

**Reproduces how often:** Everytime

### Versions

> Atom    : 1.17.0
> Electron: 1.3.15
> Chrome  : 52.0.2743.82
> Node    : 6.5.0

OS info:
> Operating System : Linux Mint 18.11 Cinnamon 64-bit
> Cinnamon Version : 3.2.7
> Linux Kernel : 4.4.0-57-generic

### Additional Information

**Comment by simurai** [comment]
Currently there isn't an easy way to change the font size outside of `atom-text-editor`. Some options:

- Change to `em` units everywhere. Probably not gonna happen until a next major version.
- Make it possible to override `ui-variables.less`. See https://github.com/atom/atom/issues/5903

Until then individual elements need to be overridden in your `style.less` file. Here two related issues:

https://github.com/atom/atom/issues/3636
https://github.com/atom/atom/issues/2530
