### ISSUE TITLE
Atom locks up computer with high CPU

### ISSUE THREAD

**Issue by danpalmer** [atom/atom#14475]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/

I haven't followed all of these steps yet because once it happens it's impossible to collect profiles or anything like that. I'll try safe mode when I have some time to dedicate to this, but thought it worth reporting before then as it seems fairly serious.

### Description

Shortly after launching Atom (seems to be 10-30 minutes after launching), it is using most of the processing resource on my computer, to the point where simply _quitting_ Atom can take 10 minutes.

Furthermore, after quitting Atom, Atom Helper processes remain around still using almost the same amount of resources.

![screenshot 2017-05-18 10 21 11](https://cloud.githubusercontent.com/assets/202400/26195663/79932ce8-3bb4-11e7-8788-44ef7343877b.png)

### Steps to Reproduce

1. Open Atom
2. Wait 10-30 minutes.

**Expected behavior:** I expect my computer to remain usable.

**Actual behavior:** Atom uses enough CPU for the computer to be essentially unusable.

**Reproduces how often:** 50% +

### Versions

Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

None right now, happy to add more to help debug.

**Comment by subesokun** [comment]
Same for me on macOS (10.12.4), very high CPU consumption caused by the Atom Beta Helper.

**Comment by 50Wliu** [comment]
Some previous reports suggested that the pigments package was causing this issue.  Do either of you have that package installed?

**Comment by subesokun** [comment]
@50Wliu I've installed that package and disabled it for now. Let's see if that solves already my issue.

**Comment by lee-dohm** [comment]
@danpalmer We're going to need you to follow the instructions in the [Atom Flight Manual](http://flight-manual.atom.io) on [Diagnosing Runtime Performance](http://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance). Unfortunately, this could be lots of things and this issue isn't actionable with the information it contains.

**Comment by danpalmer** [comment]
@lee-dohm unfortunately when this is occurring Atom doesn't perform fast enough to be able to do things like open the dev tools. I can try collecting a spindump or something like that from Activity Monitor, but I'm not sure when I'll next have time to dedicate to this (since it could require a hard reboot, I need to prepare my machine which will take some time).

**Comment by 50Wliu** [comment]
@danpalmer In addition, can you answer my question above as to whether you have the `pigments` package installed, and whether disabling it solves the performance issues?

**Comment by danpalmer** [comment]
Oh whoops, missed that comment! Will look at it when I'm at my work machine tomorrow (UTC+1, I've left for the day).

**Comment by oyeanuj** [comment]
FWIW, I am also seeing this issue since upgrading 0.18, and disabling pigments did not solve the issue for me. In terms of memory, the 10 odd instances of Atom Beta are consuming over 300MB each.

**Comment by lee-dohm** [comment]
@oyeanuj Please fill out a new issue. There's no way to know that you are experiencing the same issue that @danpalmer is.

**Comment by subesokun** [comment]
fyi, disabling pigments solved my issue but actually I've never seen that many helpers running in the background as in @danpalmer's case. I had only one instance running.

**Comment by danpalmer** [comment]
I had a pigments directory in my Atom directory – although I don't know if it was being actively used (I tried to open Atom to uninstall it from within there but ended up having to hard-reboot my machine). After deleting pigments I re-ran Atom and for the ~1 minute I had it open it appeared to be fine, however I didn't have time to try using it for real work in case I had to do another hard reboot. I _think_ pigments was likely the issue in this case.

Is pigments a package that got installed? I know I didn't install it, but I guess another plugin might have? Is it distributed by or included as a default package in Atom?

**Comment by 50Wliu** [comment]
It is a community package, meaning that it is not included by default when you install Atom.  There's two possibilities: you installed it a long, long time ago and forgot about it, or another package installed it for you (pretty unlikely).

At any rate, it appears that the problem has been resolved.  If it turns out that the high CPU usage continues even with pigments uninstalled, please just comment here and we'll reopen the issue.

**Comment by danpalmer** [comment]
@50Wliu thanks!

**Comment by BMayank0405** [comment]
atom 1.18 version is having high CPU usage even in safe mode. And also tried by opening just a single file results are the same
![atom1](https://user-images.githubusercontent.com/21199793/28494284-29b5569e-6f47-11e7-8c62-d433f2d1c4f8.png)

**Comment by middleagedman** [comment]
I'm having the same issue for the last month.. even -safe still one core goes 100% and the memory usage keeps growing.  I'll attach the debug items in a minute

**Comment by middleagedman** [comment]
Here's something strange.. I did an strace on the atom process and I could see it walking through my Chrome bookmarks directory?

[pid 10786] lstat("/home/XXXX/.config/google-chrome-backup/Default/Local Storage/https_www.panopta.com_0.localstorage", {st_mode=S_IFREG|0644, st_size=3072, ...}) = 0

**Comment by middleagedman** [comment]
I ran an strace on atom and it looks like the high cpu and memory usage is due to it walking all of the files under my home directory.. why does it do that?

**Comment by Zireael07** [comment]
@middleagedman  is your project in your home directory?

**Comment by middleagedman** [comment]
Yes, there was one.. I removed it and restarted from scratch.  Seems to be ok.
So maybe the issue for some people is large amounts of files in their home directories coupled with project creations?

**Comment by nickskitch** [comment]
came here for the high cpu usage problem. It starts slow and creeps up over time. Ran it in --safe mode, even moved my project to be outside of /Users/<username> folder.   Started a new file.   Just typing there is lag for a half second, then it resumes normally.  If I hold down the backspace, you can see it move normally, then all of a sudden it hangs for a few seconds then proceeds.

I use Atom for my day to day job. I rely on it as one of my primary tools.  If this many people are complaining about there being lag, I would hope this would be investigated.

I have followed guides on how to cleanly remove everything Atom installs, I've even tried older versions. There's something in the environment causing this.

**Comment by middleagedman** [comment]
nickskitch:
I think it has something to do with launching Atom in a directory that has a lot of subfolders/files, or creating a new project where the home directory has a lot of subfolders/files.  It looks like Atom starts to cache the directory structure in memory, thus the high cpu/memory usage.

**Comment by nickskitch** [comment]
@middleagedman I did try your suggestion to move my project out of my home folder and into subfolders.  That didn't seem to have any effect.  I used the faq and did the debugging to see in the chart there are a myriad of small tasks that fire every 5 seconds (about the time when I see lag).  

What fixed it for me was downloading an older version of Atom and disabling auto-update immediately.

This is not the first issue I've had with Atom lately, the remote-sync packages no longer work so there must be some core changes causing disruption to plugins and stability issues.

**Comment by Burgje** [comment]
If you disable package GitHub 0.3.4-1 (GitHub integration) , CPU usage of Atom helper drops to <0.5

**Comment by ken107** [comment]
Github integration is the culprit for me

**Comment by 50Wliu** [comment]
Atom 1.21.0-beta1 fixes high CPU issues under certain circumstances when the github package is enabled.

**Comment by jeffmcjunkin** [comment]
Atom `1.23.1` on Ubuntu 16.04 x64 also had high CPU utilization (around 30% of a core) with GitHub Integration, so I think there are ongoing issues. Disabling GitHub Integration and restarting Atom resolved the issue for me.

**Comment by moisesads** [comment]
Esse problema continua em maio de 2018

**Comment by heyiamvika** [comment]
Thanks, disabling GitHub integration helped as well
