### ISSUE TITLE
Build system installs desktop with wrong paths

### ISSUE THREAD

**Issue by paulmenzel** [atom/atom#14480]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Building Atom with `script/build --install /some/path` that path is not stripped in the generated `*.desktop` file

### Steps to Reproduce

1. Download source 1.17.0
2. script/build --install /some/path

**Expected behavior:** The destination directory should be stripped from paths.

**Actual behavior:** [What actually happens]

```
$ more /usr/share/applications/atom.desktop
[Desktop Entry]
Name=Atom
Comment=A hackable text editor for the 21st Century.
GenericName=Text Editor
Exec=/dev/shm/bee-root/atom/atom-1.17.0-0/image/usr/share/atom/atom %F
Icon=/dev/shm/bee-root/atom/atom-1.17.0-0/source/resources/app-icons/stable/png/1024.png
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;TextEditor;Development;
MimeType=text/plain;
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100 %

### Versions

```
$ atom --version
Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by thomasjo** [comment]
Can you elaborate on why you think the path should be stripped? If you want to create a relocatable "bundle", use one of the package generator flags, e.g. `--create-debian-package`.

**Comment by paulmenzel** [comment]
@thomasjo, we don’t want to use a Debian package.

Normal build systems allow to specify [a destination directory](https://www.gnu.org/prep/standards/html_node/DESTDIR.html), and I thought that’s what the new version of the switch `--install` allows.

Additionally, i forgot to add, the icon in `Icon=` is referenced from the source directory, while it should be *installed* also in the *target* directory.

**Comment by thomasjo** [comment]
As far as I know, the `install` argument is intended to mimic `prefix`. 

It would be great if you could update your issue body above with exact details on the current behavior, and what you expect — use illustrative examples that clearly shows what we currently have, and what you want. That will make it much easier for someone to come along and implement the proposed behavior. Also make sure to mention the `Icon` problem; that seems like a bug.
