### ISSUE TITLE
Why is Atom using the Contributor Covenant?

### ISSUE THREAD

**Issue by DelanoJ84** [atom/atom#14521]
The Contributor Covenant's "sole maintainer" has posted and defended a tweet calling for violence against a journalist for what he chose to report on. In reference to the physical assault of a man during a live interview, she asked:
> [Why didn’t anyone punch the reporter giving the nazi air time?](https://twitter.com/CoralineAda/status/823064825366360065)

Calls for violence are forbidden by the Contributor Covenant, which states that "project maintainers have the right and responsibility [...] to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful".
I opened an issue to address the infraction: https://github.com/ContributorCovenant/contributor_covenant/issues/393#issue-220473122

[The issue was closed by the maintainer in question 10 days after it was opened](https://github.com/ContributorCovenant/contributor_covenant/issues/393#issuecomment-302752285), with the following comment:

> I'm obviously a very toxic person, as evidenced by my hatred for bigots, racists, homophobes, transphobes, and other bad actors. No one should contribute to this project anymore and I should step down as sole maintainer and let it languish. I'll let the hundreds of people involved in translating the Contributor Covenant into 21 languages and the 20k open source adopters know that they are dealing with a person who believes that literal nazis should not be given a media platform so that they can find an alternate code of conduct, preferably one that leaves room for people to foment hatred under the guise of inclusivity.
> 
> Thanks for bringing this to my attention!

It is worth noting this comment made by the sole maintainer of the Contributor Covenant does not even acknowledge her call for violence. She instead conflated any criticism of this incitement with supporting bigotry, suggesting that not supporting violence and not supporting intolerance are mutually exclusive.

Also, the Github Terms of Service state "[while using GitHub, you agree that you will not under any circumstances [...] incite violence towards any individual or group](https://help.github.com/articles/github-terms-of-service/#c-acceptable-use)".

In short, the one person who created this code of conduct cannot recognize the difference between an opposition to unprovoked violence and a support of intolerance. Additionally, the only way this person can continue to operate on GitHub and on her own project is through the selective enforcement of both of these guidelines.

In this light, I have to ask how GitHub can, in good faith, use and promote this code of conduct as a way to make its community safer. Since by bringing this document on we are bringing in the work of someone who both threatens others and is incapable of seeing this, the logical conclusion of enforcing this code of conduct in her image is that only the intolerance and threats of certain people will be recognized. Any violations committed by a select few will not only be ignored but closed because of the assumed prejudices of the opener.

**Comment by kemko** [comment]
In my opinion, the CoC covers only aspects of contributor interaction with the open source community.

If the author of CoC wanted him to cover all aspects of a person's life, he could simply copy the commandments of any religion and that would be enough.

Until this happened, any person who allows himself to aggressively drive or make bad tweets, can not be considered a bad contributor.

**Comment by lee-dohm** [comment]
We, the Atom team, are using the Contributor Covenant Code of Conduct because it is the best and most comprehensive document for codifying respectful and inclusive behavior and enforcement of those cultural norms. Taking some, obviously sarcastic, quotes out of context does nothing to convince us that the Contributor Covenant Code of Conduct is anything less than that.

Closing and locking since this is obviously a vendetta that has nothing to do with Atom.
