### ISSUE TITLE
Autocomplete not functioning for Atom

### ISSUE THREAD

**Issue by Mirageee** [atom/atom#14538]
Autocomplete doesn't work on newly downloaded Atom

I am new to atom. I just downloaded the application and had not done any forms of modification to it. These are the actions i did:
1. created a new file and named it something.html.
2. typed html and enter to create the html boilerplate code
3. within body tags, tried the following code but unable to have an autocomplete:

Typing p doesn't generate /p automatically
Typing form doesn't generate form class"" action"" method""
Typing body doesn't generate /body
Typing div doesn't generate /div

I tried installing on Windows but it does not work as well.

**Expected behavior: I expected the above autocompletes to occur when I finish typing the first tag

**Actual behavior: autocomplete doesn't occur

**Reproduces how often:100%

### Versions 1.17.0 x64 

I am running Mac 10.12.4

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

All the default packages for autocomplete are installed and running.

**Comment by samuelrey** [comment]
What have you tried doing to solve the problem?

**Comment by Mirageee** [comment]
I've tried uninstalling and reinstalling twice on Mac, and tried installing the same on windows and it all didn't work. Tried disabling and re-enabling all autocomplete packages as well but didn't work. Followed an earlier thread clicking keybinder-->toggle, didn't work. Other than that I don't know what else I can do. Seek some advice from the experts here. Thank you.

**Comment by rsese** [comment]
Moved to https://github.com/atom/autocomplete-plus/issues/853 so we have it in the right repo :v:
