### ISSUE TITLE
Command Palette score increases with selection

### ISSUE THREAD

**Issue by kirkstrobeck** [atom/atom#14537]
Sublime will increase the score of an item for specific characters when selected.

ie. if I type `li.js` and I select `components/list/index.jsx` and it is several items down in the list, the next time I type `li.js` it will have higher scoring as a relevant result.

**Comment by rsese** [comment]
Thanks for the suggestion :v:  Seems like you're referring to the fuzzy-finder?  If so, can you re-open in https://github.com/atom/fuzzy-finder if there's not an existing issue for it so we have it in the right place?  If you can also use the template as much as possible, that would be super helpful for us.
