### ISSUE TITLE
TreeView side cannot be toggled on Atom 1.17.0

### ISSUE THREAD

**Issue by izaid** [atom/atom#14556]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Normally, I keep my TreeView on the right. Since I updated to version 1.17.0, my TreeView is stuck on the left and no amount of clicking "Toggle Tree Side" will move it. I'm on OS X 10.12.3. I have tried opening and closing all projects, and toggling the TreeView itself to no avail.

### Steps to Reproduce

Try clicking "Toggle Tree Side".

**Expected behavior:** [What you expect to happen]

I expect the TreeView side to toggle from the left side to the right side.

**Actual behavior:** [What actually happens]

The TreeView does not move from the left side.

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Please see the FAQ: https://discuss.atom.io/t/where-did-the-show-tree-view-on-right-side-option-go/42762
