### ISSUE TITLE
Text search cannot trigger automatically when switch to another pending pane item.

### ISSUE THREAD

**Issue by yubaoquan** [atom/atom#14565]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Text search cannot trigger automatically when switch to another pending pane item.

### Steps to Reproduce

1. Toggle the tree view
2. Open a file.
3. Command+f search some text, for example 'coupon'.
4. Click another file in the tree view so that the file is opened in pending mode.

**Expected behavior:** The search for text 'coupon' could trigger automatically. If the text exists, update the search result.

**Actual behavior:** The search does not triggered until I click the editor area to focus it.

**Reproduces how often:** 100%

### Versions

Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
OSX : Sierra 10.12.4

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/find-and-replace if there's no existing issue already so we have it in the right place?  Also, can you add more detail to your steps to reproduce as well?  E.g.:

> 1. Toggle the tree view
> 2. Open a file.

As a pending tab?

> 3. Command+f search some text, for example 'coupon'.

Should the file from step 2 have the text "coupon" in it?

> 4. Click another file in the tree view so that the file is opened in pending mode.

Should this other file also have the text "coupon" in it?
