### ISSUE TITLE
Tabs seems to be small; can’t reset size to default

### ISSUE THREAD

**Issue by martinbean** [atom/atom#14587]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The tabs in my Atom installation look different. They seem to be too short, and I can’t see the “top” of my tabs where it would sit in a gutter:

<img width="842" alt="screen shot 2017-05-23 at 10 24 57" src="https://cloud.githubusercontent.com/assets/167312/26347759/751eeb60-3fa2-11e7-98ae-120a677a9ebb.png">

I’ve tried re-loading Atom windows; re-opening the application; restart my MacBook; booting Atom in safe mode; but the problem still persists.

I want to go back to the “tall” tabs like this: http://macosxbits.com/wp-content/uploads/2015/04/atom-for-mac-os-x.jpg

Have I toggled an option somewhere? I’ve gone through the Core, Editor, and Dark UI theme settings, but can’t find anything to “reset” the size of my editor’s tabs.

### Steps to Reproduce

As above.

**Expected behavior:** [What you expect to happen]

http://macosxbits.com/wp-content/uploads/2015/04/atom-for-mac-os-x.jpg

**Actual behavior:** [What actually happens]

https://cloud.githubusercontent.com/assets/167312/26347759/751eeb60-3fa2-11e7-98ae-120a677a9ebb.png

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom: 1.17.0
apm: 1.17.0

### Additional Information

As above.

**Comment by thomasjo** [comment]
This changed in https://github.com/atom/one-dark-ui/pull/197, which shipped with Atom 1.17.

**Comment by simurai** [comment]
@martinbean Here an issue with suggestions how to make the tabs bigger: https://github.com/atom/one-dark-ui/issues/198
