### ISSUE TITLE
Bad Overlay Decoration performance on 1.19

### ISSUE THREAD

**Issue by pfitzseb** [atom/atom#14592]
Since the rewrite of the TextEditor rendering (which is pretty awesome, btw), performance of Overlay Decorations deteriorated. Badly... :(

Specifically, [adding a `ResizeObserver` to **each** overlay](https://github.com/atom/atom/pull/13880/commits/893da22c5594eb2b740f7c0ec66608a7dcd8bf9a#diff-dd884e004af84f2b91dafb5510de7271R3205) doesn't scale well at all -- on my machine, each resize callback will take something from 1 to 3ms (this is just the overlay decoration from autocomplete-plus):
![timeline](https://cloud.githubusercontent.com/assets/6735977/26364398/7fac66ec-3fe4-11e7-8392-200929db3fdf.png)

Let's add 100 more overlays and we get this beauty:
![timeline2](https://cloud.githubusercontent.com/assets/6735977/26363643/e9681b2e-3fe1-11e7-9754-37c6a01d00f2.png)

With Atom 1.18 (and 100 overlays), performance is much better (but not ideal):
![timeline3](https://cloud.githubusercontent.com/assets/6735977/26363835/9239b10e-3fe2-11e7-876c-ef460ea5f698.png)

The first thing I'd try here would be debouncing the `didResize` callback and not adding a `ResizeDetector` for each and every decoration, but I don't really understand why the `ResizeDetector` is needed anyways.
I'd be happy to look into this (and overlay performance in general), but would appreciate some guidance here. :)

### MWE on @lee-dohm's request:
To reproduce this, paste
```coffeescript
atom.commands.add 'atom-text-editor', 'generate-overlays', ->
  ed = atom.workspace.getActiveTextEditor()
  ed.setText("aa\n".repeat(100))
  for i in [0..99]
    m = ed.markBufferRange([[i, 0], [i, 2]])
    div = document.createElement('div')
    div.style.backgroundColor = 'white'
    div.innerText = "fooo#{i}"
    decoration = {item: div, type: 'overlay'}
    ed.decorateMarker(m, decoration)
```
into your `init.coffee`, reload Atom, open a new text editor and execute `generate-overlays`. You should immediately feel the drop in performance.

### Additional info:
- The tests above were performed on commit 85e65ff, on Windows 10, and on a fairly beefy PC. 
- [`ink`](https://github.com/JunoLab/atom-ink/) (in conjunction with `julia-client`) was used to generate the inline overlays, but I suspect packages like Hydrogen will end up having the same issues.
- If anyone is interested in the timelines I'd be happy to upload them (since they can finally be exported :D), but I do think the screenshots are enough of an explanation as to what is going wrong here.

cc: @nathansobo, @as-cii

**Comment by nathansobo** [comment]
Thanks for the report. We'll take a look at this today and I'm confident we can improve the performance before this code hits beta.
