### ISSUE TITLE
text Search isn't working at 

### ISSUE THREAD

**Issue by EsrefDurna** [atom/atom#14599]
### Description

text Search isn't working at 

### Steps to Reproduce

1. at any normal document control+f 
2. type any text which is in the document to the search area,
3. see that there is no results,
4. close the document, re-open it, try again and its working,

**Expected behavior:** [What you expect to happen]
search should work,

**Actual behavior:** [What actually happens]
not working,
**Reproduces how often:** [What percentage of the time does it reproduce?]
so frequently,

### Versions
1.17.0 at windows,

**Comment by pixilz** [comment]
@EsrefDurna If you open up the keybinding resolver (`ctrl+.` by default) and press `ctrl+f` in these instances can you see what is causing the error and/or send in a screenshot of the results? (After which we may need to see your installed packages)

**Comment by rsese** [comment]
Moved to https://github.com/atom/find-and-replace/issues/903 so we have it in the right repo.
