### ISSUE TITLE
Atom 1.18.0 - Multiple Remote Push URL's

### ISSUE THREAD

**Issue by GioLogist** [atom/atom#14601]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Not detecting remotes if multiple URL's are set for the same remote.

### Steps to Reproduce

1. Add an additional push URL
```
git remote set-url --add --push origin git@github.com:username/repo
git remote set-url --add --push origin git@github.com:username/repo2
```

2. Verify it worked
`git remote -v`
```
origin	git@github.com:username/repo (fetch)
origin	git@github.com:username/repo (push)
origin	git@github.com:username/repo2 (push)
```
3. Now try to do a push from inside of Atom and you will see

> Note: No remote detected for branch. Cannot push because there is no remote named "origin" for which to create a remote tracking branch.

**Expected behavior:** 
It should work the same as running the command:
> git push 

Which will push it to both just fine.

**Actual behavior:**
It doesn't allow me to push at all.

**Reproduces how often:**
100% of the time. Interestingly enough though, if I only add a second remote url **after** I have already loaded in the repo, it will continue to allow me to push - until i close and open atom or add the repo again (at which point it detects changes the error comes).

### Versions

1.18.0-beta0

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/github](https://github.com/atom/github) repository.
