### ISSUE TITLE
SemVer / BC policy for Atom editor

### ISSUE THREAD

**Issue by ethernal** [atom/atom#14624]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When 1.17 came out the treeView.mainModule.createView(); was replaced (AFAIK) with treeView.mainModule.getTreeViewInstance(); - this is from https://github.com/olmokramer/atom-permanent-delete package.

This is Minor version that should not introduce a BC change - I would like to propose what Symfony team does. When you want to delete/remove the function call because new one was introduced:
1. Delete the body of the function only.
2. Add deprecation notice with example on how to fix the code and comment code for removal in 2.0.
3. Include new function call in the body of "old" code (so new code is running), and all "legacy" requirements like parameters passed or other function calls that need to be invoked (in case of code separation into more detailed functions).
4. Allow everyone to update without issues until 2.0

Please see: http://symfony.com/doc/current/contributing/code/bc.html

This should in my view enhance quality as non working packages get abandoned by people/users potential contributors as they don't work. Deprecations are "annoying" so and are more likely to be fixed also you're not breaking the software for many users that way and give devs time to figure out new ways of handling issues.

I know that on the other hand you're "allowing" to use deprecated code that way, but that will have to change when 2.0 is defined. You will probably just reach that point faster and it will be better for us all.

### Steps to Reproduce
NA

**Expected behavior:** All packages for ^1.0 work but throw deprecation error.

**Actual behavior:** Packages break.

**Reproduces how often:** 100% on BC break

### Versions

ALL

### Additional Information

It works great with Symfony - one can always be sure they care about their software and that it will continue to work on "obsolete" packages, also note that there are versions that merge new functionallity in 2.0 with BC promise from 1.0 so last 1.x version has same functionality as 2.0 and throws deprecation errors but still works. This is a major feat and allows everyone to prepare for even major changes without breaking the application.

I feel this is THE solution for reliable software releases. I hope it can be achieved by Atom team.

**Comment by 50Wliu** [comment]
I don't believe the method in question is part of the [public API](https://atom.io/docs/api); therefore there is no guarantee about backwards compatibility.  In addition, Tree View itself is still pre-1.0, meaning that all releases have the potential to break backwards compatibility.

/cc @atom/feedback

**Comment by lee-dohm** [comment]
What @50Wliu stated is 100% correct. The tree-view package has a [public API of its own](https://github.com/atom/tree-view#api) apart from the Atom API but the function in question is not part of it.

**Comment by ethernal** [comment]
Ok, I did not dig deep enough it seems but can you explain how that package can provide it's functionality? The readme linked provides one API function - hardly enough for devs I think.

Also if developers are using "non-public" API couldn't that be reported by DeprecationCop and stats on such usage sent to atom team? Ex. if these functions are used by many developers you will know that they are needed in public API - win-win situation?

**Comment by lee-dohm** [comment]
@ethernal Regarding "how that package can provide it's functionality?", I'm not sure what you're asking. Can you please be more specific?

Regarding exposing more things in a public API, what if we don't want to or have the resources to support a larger public API than the one we have? Isn't it more responsible of us to state up front what we believe we can support and then let people decide if they want to take the risk of using undocumented functions, knowing that they could break at any time?
