### ISSUE TITLE
How do I disable the right sidebar showing by default?

### ISSUE THREAD

**Issue by kirkstrobeck** [atom/atom#14633]
I understand that this does not meet the issue guidelines. Feel free to close.

---

How do I disable the right sidebar showing by default in Atom Beta 1.18.0-beta-1?

![screen shot 2017-05-24 at 3 22 24 pm](https://cloud.githubusercontent.com/assets/241963/26428132/d1190d54-4094-11e7-86e6-f3a5f271d396.png)

**Comment by 50Wliu** [comment]
Not possible yet; you'll have to hide it manually for each project (but it should remember that setting per-project).  There is discussion about adding a setting to hide it by default globally but a decision hasn't been made.

For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
