### ISSUE TITLE
Atom forgot the previous open status.

### ISSUE THREAD

**Issue by yubaoquan** [atom/atom#14635]
### Description

Open multi project in the same same window, next time open, changed to separated window.

### Steps to Reproduce

1. Open a project A.
2. Click file -> reopen project, select a project B.
3. Now the two projects are in the same window of atom, atom show two tabs on the top of window: A and B.
4. Close atom. 
5. Open atom.

**Expected behavior:** The two tabs show in the same atom window as previous open time.

**Actual behavior:** Sometimes atom opens two separated window for the two projects, sometimes atom only open an empty window.

**Reproduces how often:** Frequently.

### Versions

Atom : 1.17.0
Electron: 1.3.15
Chrome : 52.0.2743.82
Node : 6.5.0
OSX : Sierra 10.12.4

**Comment by pixilz** [comment]
As part of this if I add a project folder to Atom from an empty window closing and reopening Atom has consistently lead to an empty window.

If I then reopen project (same project noted before) Atom opens a new window. If I then close the empty window and finally close the project window, reopening will open the project window.

**Comment by yubaoquan** [comment]
It seems that **the same window** I mentioned in step 3 is a feature of OSX but not atom. So I think   this issue is not an exact issue.
