### ISSUE TITLE
How to debug Atom >=1.17 

### ISSUE THREAD

**Issue by gandm** [atom/atom#14639]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Prior to Atom 1.17 I could 'Toggle Developer Tools' and set breakpoints inside Atom code. e.g. first-mate. Now this isn't possible as that code isn't available to inspect.  I guess this is since snapshots were introduced. How do I now achieve that?

### Versions

Atom  >= 1.17

**Comment by 50Wliu** [comment]
Have you tried dev mode (`atom --dev`)?  I don't think snapshots are loaded in dev mode.

**Comment by gandm** [comment]
@50Wliu No I didn't try --dev but should have! It works OK. Thanks
