### ISSUE TITLE
Opened files scroll with tree view

### ISSUE THREAD

**Issue by ozo2003** [atom/atom#14638]
### Description

In pre 1.17 versions, opened files stayed on top and scrolling tree didn't have effect on opened files. but in new 1.17 or 1.18 beta versions, opened files scroll with the tree view which is really unpleasant, especially when there's a lot of files in tree.

**Expected behavior:** Opened files stay above tree view and don't scroll with tree

**Actual behavior:** Opened files scroll with tree

**Reproduces how often:** 100%

### Versions

apm 1.17.0
npm 3.10.5
node 6.9.5 x64
python 2.7.12
git 2.7.4

Atom : 1.17.0-beta2
Electron: 1.3.14
Chrome : 52.0.2743.82
Node : 6.5.0

XUbuntu Linux puddle 4.11.0-041100-generic #201705041534 SMP Thu May 4 19:36:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 50Wliu** [comment]
Tree View does not have a way to display opened files.  Therefore, it would seem that this is coming from a community package you have installed.  It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
