### ISSUE TITLE
Graphical glitches in editors

### ISSUE THREAD

**Issue by fiso** [atom/atom#14646]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Lighter areas appear in my editors. This appears to be theme independent, as long as I'm using a dark theme. For light themes nothing strange happens.

![image](https://cloud.githubusercontent.com/assets/482355/26485715/60af7a48-41f8-11e7-90a8-48aaac27764f.png)

### Steps to Reproduce

1. Start Atom
2. Open any editor.

**Expected behavior:** No graphical glitches.

**Actual behavior:** See attached screenshot.

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
$ apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.9.2
```

OSX Sierra 10.12.4

### Additional Information

This space intentionally left blank.

**Comment by dackmin** [comment]
Same here, starting with v1.17.0

![capture d ecran 2017-05-26 a 09 50 18](https://cloud.githubusercontent.com/assets/1873323/26485823/c7177a74-41f8-11e7-8735-d5b59fc16215.png)

**Comment by fiso** [comment]
Closing this as it is duplicated by #14649 - which documents the problem slighty better (it has to do with color profiles).
