### ISSUE TITLE
Menubar text labels not displaying

### ISSUE THREAD

**Issue by exiva** [atom/atom#14642]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The menubar items (File, Edit, etc, etc) have no text labels, though if I click around they are there and I can use the menus. The only item that displays is the "Atom" menu from macOS. I've tried `atom --safe` as well as `atom --disable-gpu` also removed my `.atom` folder and it had no effect.

Gif of the issue: http://i.imgur.com/s7yCvWd.gifv

### Steps to Reproduce

1. Launch Atom
2. Observe no text labels on menubar items

**Expected behavior:**

Menubar to have it's text

**Actual behavior:**

Menubar does not have it's text.

**Reproduces how often:** 

Every time

### Versions

```
Atom    : 1.17.1
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 3.6.1
git 2.13.0

macOS 10.12.5
```

**Comment by rsese** [comment]
I just tried this in 1.17.1 in safe mode on 10.12.5 and the menu labels are showing up for me - did this happen immediately after upgrading to 1.17.1 @exiva?

**Comment by exiva** [comment]
@rsese No, sometime during 1.17 I think. Updated to 1.17.1 had the same issue.

**Comment by exiva** [comment]
🙄 Just accidentally discovered it seems to be caused by an issue with [Vanilla](http://matthewpalmer.net/vanilla/).

**Comment by rsese** [comment]
Glad you figured out what the issue was, thanks for letting us know too :v:
