### ISSUE TITLE
Atom doesn't start the second time. Exception thrown.

### ISSUE THREAD

**Issue by vp2177** [atom/atom#14644]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![image](https://cloud.githubusercontent.com/assets/451903/26469664/b7c1022c-4192-11e7-8f6c-1c61d6051676.png)

### Steps to Reproduce

1. Start Atom. Works fine.
2. Close Atom.
3. Start Atom.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by TangSteven** [comment]
Also occurs in 1.18.0-beta2

**Comment by rsese** [comment]
@vp2177 @TangSteven - if you navigate to the directory that contains the missing file mentioned in the error message (`main.js`) is there anything in the directory?

**Comment by TangSteven** [comment]
The /resources/ directory only contains one file(`electron.asar`), and does not contain `main.js`

**Comment by indiekindie** [comment]
Having this issue in atom 1.8.0-beta1 too.
![atom-error](https://cloud.githubusercontent.com/assets/15707197/26496871/855468d2-4229-11e7-81a2-0ea46b565d21.png)
There's no "main.js" in my resources directory either.

**Comment by rsese** [comment]
It looks a number of files weren't installed, can you try re-installing and let us know if you still have the same problem?

**Comment by indiekindie** [comment]
I'll try later! Thanks for the advice :)
