### ISSUE TITLE
Failure to create new system folder with "Save>New Folder" dialogue (on Atom 1.17.1)

### ISSUE THREAD

**Issue by mangobait** [atom/atom#14641]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[On creating a new file the Save dialogue fails to allow the creation of "New Folder"]

### Steps to Reproduce

1. [Create new file: CMD N]
2. [Type some words]
3. [Save file: CMD S]
4. [click "New Folder"]
5. [... nothing... no dialogue (just click sounds if you click elsewhere); ESC exits]

**Reproduces how often:** [100%]

### Versions

Atom 1.17.1 (in Safe Mode) on Sierra 10.12.4

**Comment by rsese** [comment]
I just tried this in 1.17.1 in safe mode on 10.12.4 and it worked ok for me - clicking `New Folder` in the save dialog prompted me to create a new folder and I created one with no problem.

Can you share a GIF or screencast of the behavior @mangobait?

**Comment by mangobait** [comment]
Okay. Might be in full screen mode that it happened. That sometimes 
causes funny behaviour.

**Comment by mangobait** [comment]
Yes, it works fine when I'm NOT in fullscreen mode.

But it continues to be a problem when in fullscreen mode.

**Comment by rsese** [comment]
Hmm, I tried in fullscreen mode and it worked ok for me there too - do you see similar behavior with any other apps?

**Comment by mangobait** [comment]
I was going to say "no" but sometimes (rarely) popup windows get lost on
other desktops ("spaces") and this was in fact the issue. So maybe it is an
issue pertaining to multiple desktops; it may be particularly when an app
is assigned to a particular desktop but I'd have to test that.

What I'd like to know is, is it Apple's "fault" or is there something that
is particular to the app in question, i.e. Atom?
