### ISSUE TITLE
How to custom file associations

### ISSUE THREAD

**Issue by magicdawn** [atom/atom#14647]
duplicates of https://github.com/atom/atom/issues/1718
but since that issue is locked, I'm creating new one here. Sorry

After I install package `language-babel`, all `.js` files become `Babel ES6 JavaScript`

![image](https://cloud.githubusercontent.com/assets/4067115/26485877/4e9440ea-422b-11e7-8b28-9411378c7f50.png)

And actually I want `language-babel` package only recognize `.jsx` files, and leave the `.js` file for other tools only work in `JavaScript` Grammar mode but not `Babel ES6 JavaScript` Grammer mode. 
In general, two or more packages wants to handle a file type with same ext. How to manualy config in the editor level ?

**Comment by thomasjo** [comment]
What you want isn't currently possible via configuration. If a community package "hijacks" an extension, the only (supported) way to resolve that is to uninstall/disable the package.

Your best bet in this case, if you want to keep language-babel installed, is to write a custom function in your [init file](http://flight-manual.atom.io/hacking-atom/sections/the-init-file/). If you need help with that approach, [join us on Slack](https://discuss.atom.io/t/join-us-on-slack/16638).
