### ISSUE TITLE
Add setting to disable docks arrows

### ISSUE THREAD

**Issue by damassi** [atom/atom#14655]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It would be nice if the new Dock feature released in `1.17.0` were in its own package so that users can enable and disable as needed. In my own personal use-case, its highly annoying to mouse over to the tree view and have the arrow always animate in and out. Since I don't use docks, I would like to disable. Alternatively, it would be nice if this functionality was behind a setting that I could toggle off. 

### Steps to Reproduce

1. Mouse over to tree-view, see arrow appear
2. Mouse out to main editor window, see arrow disappear
3. Repeat.

**Expected behavior:** [What you expect to happen]
I would expect to be able to disable this via disabling an external package, or a setting to disable.  

### Versions
1.17.*

**Comment by matthewwithanm** [comment]
Hey @damassi! You asked me on Twitter yesterday about disabling the arrows right? The One themes have an option for that. It sounds like your complaint is with those affordances and not docks themselves; maybe that setting should be moved into Atom proper (instead of the theme).

**Comment by damassi** [comment]
Oh yeah, it would be better if it was an Atom-proper setting rather than something set in a theme; I've spent a lot of time crafting my own look-and-feel and I would prefer to stick with it 😄

**Comment by rsese** [comment]
Thanks for contributing, I went ahead and updated the issue title since your request was clarified @damassi :v:

As a side note, besides the One themes settings option to turn off the docks arrows, another option is to add a bit of CSS to your styles.less /cc https://discuss.atom.io/t/hide-the-new-tree-view-dock-toggle-button/42793/2.

**Comment by jamieorc** [comment]
I agree that the slight animation of the dock arrow is too attention-grabbing.

**Comment by lee-dohm** [comment]
Thanks very much for the suggestion.

Given that this is achievable via the CSS that @rsese shared, we're not going to add an explicit feature for this. Additionally, we won't accept a pull request for this feature because we feel that this is a feature that themes should provide, not Atom itself.
