### ISSUE TITLE
Unable to grab scrollbar because of pane controls in atom 1.18 beta

### ISSUE THREAD

**Issue by moimael** [atom/atom#14651]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With the new pane feature, I'm unable to grab the scrollbar because the show pane control appears on top of it.

### Steps to Reproduce

1. Try to grab the scroll bar

**Expected behavior:** [What you expect to happen]
I should be able to drag the scrollbar

**Actual behavior:** [What actually happens]
I can't drag the scrollbar

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions
1.18.0-beta2 Fedora 26

**Comment by rsese** [comment]
Thanks for the report!  Can you share a GIF or screencast that shows the behavior you described @moimael?

**Comment by moimael** [comment]
[![ezgif.com-optimize7d05d.gif](https://gifyu.com/images/ezgif.com-optimize7d05d.gif)](https://gifyu.com/image/bRJO)

Here you go !

**Comment by rsese** [comment]
Thanks @moimael :bow:  Just to confirm, do you have Atom fullscreen and your cursor is all the way to right edge of your screen?  Or does the scrollbar not drag at all even if your cursor isn't all the way to the right edge?  /cc this recent similar issue with more details https://github.com/atom/atom/issues/14803.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/14651#issuecomment-309525230. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
