### ISSUE TITLE
macOS: nothing happens with "Reopen Project" when all windows are closed

### ISSUE THREAD

**Issue by brunnopleffken** [atom/atom#14653]
### Steps to Reproduce

1. Close the current window (on Mac we can close all windows without quitting the app).
2. Go to File > Reopen Project > Select any directory...

**Expected behavior:** Selecting a project with all windows closed in Mac should automatically open a new window and load the selected project in it.

**Actual behavior:** Nothing happens. I need to open a new window and then go to File > Reopen Project.

**Reproduces how often:** On Mac? Always.

### Versions

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

macOS Sierra 10.12.5 on MacBook Pro Retina 13" Late-2013

**Comment by rsese** [comment]
Thanks for the report!  I think this is close enough to https://github.com/atom/atom/issues/12508 to close as a dupe - no one specifically mentioned `Reopen Project` doesn't work either though, can you mention that in the issue @brunnopleffken?   If folks there think this can be a separate issue we can re-open.
