### ISSUE TITLE
Pinned windows icon -> "New Window" open last project

### ISSUE THREAD

**Issue by Nokel81** [atom/atom#14652]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you have atom pinned to the taskbar in windows and no windows open, right clicking and then clicking "New Window" will open a new window with the last open project loaded

### Steps to Reproduce

1. Close all atom windows
2. Right click pinned atom icon
3. Click "New Window"

**Expected behavior:** A new blank atom window opens

**Actual behavior:** A new atom window opens with the last project loaded

**Reproduces how often:** 100%

### Versions

Atom : 1.17.1
Electron: 1.3.15
Chrome : 52.0.2743.82
Node : 6.5.0

**Comment by himankpathak** [comment]
@Nokel81 if a window is already opened and you click on that "New Window" option it works fine, and thats the purpose why that option is over there.
I think this is an unnecessary issue raised friend.

**Comment by Nokel81** [comment]
I don't think so because other applications which have that button do work and because if you just click on the icon it will bring up the last opened project which you may not want.
