### ISSUE TITLE
Weird double cursor (video)

### ISSUE THREAD

**Issue by alanmacleod** [atom/atom#14669]
### Prerequisites

* [ ] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [ ] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Sometimes I get two cursors in the _same_ file in single pane mode which duplicates everything I type. Please see video link at the bottom for demonstration.

### Steps to Reproduce

Haven't been able to reliably determine factors leading to this behaviour other than it happens immediately upon switching to a tab.

**Reproduces how often:** three or four times a week using Atom every day for 8+ hours.

### Versions

Atom    : 1.17.1
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information
[https://youtu.be/bHEY51mAvBM  - video of behaviour (unlisted on YT)](https://youtu.be/bHEY51mAvBM)

**Comment by thomasjo** [comment]
This is a feature in Atom. You are most likely triggering this via holding down `ctrl` while clicking somewhere in the editor. Note that there are also various other ways of creating multiple cursors.

Pressing `esc` will return you to the state with original, single cursor.
