### ISSUE TITLE
Proposal: Allow pane items to be marked as "cannot cause activation"

### ISSUE THREAD

**Issue by pixilz** [atom/atom#14664]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Currently with Atom's new dock feature (Atom 1.17.0+) there is an issue with many packages using the `atom.workspace.getActiveTextEditor()` to get the currently active "editable" pane item. The problem is when docks were introduced many core features (such as the tree-view) were put into panes. Because of this the packages/items (like the tree-view) are marking their containing pane as active which causes certain pieces of functionality to not work as expected. As an example of this there was: [find-and-replace issue #901](https://github.com/atom/find-and-replace/issues/901) which was solved by forcing the find-and-replace package to always use the center pane (`atom.workspace.getCenter().getActiveTextEditor()`).

My proposed solution is to update the way that panes are activated. Currently when an item is activated inside of a pane it displays that item in the editor in it's corresponding pane. This does a few things:
  1. Focuses the activated item in it's pane (Potentially changing tabs)
  2. Shows the dock that the pane is contained in (if applicable)
  3. Marks the pane as active

Currently when you create/show a pane item you only have the option of either doing all 3 of these things or none of these things. I propose that we add another option which would be to allow a "soft-activate" which essentially does all of these things but the "final" step. The decision for whether or not a pane item is activated or "soft-activated" would potentially rely on a new config that can be passed when the pane item is created to mark it's "type." This would allow for both displaying items properly but not causing them to be considered when the `atom.workspace.getActiveTextEditor()` method is triggered. This prevents items like the tree-view from being "activated" while also allowing them to be properly displayed.

Because of the scope of this change it would likely need to be done in a few stages.  The stages that seemed to work best in my overview were these;
  0. Change activation to be item based rather than pane based. But keeping the item's pane as what is returned in api functions (I.E. `atom.workspace.getActiveTextEditor()`) as it does currently.
  1. Implement the api change (defaulting to normal activation functionality)
  2. Update the atom-flight-manual to document this new api change.
  3. Start with editing the tree-view to work with this new feature.
  4. Slowly convert other necessary core-packages to use this feature.

This should allow a fairly smooth transition and keep docks, panes, and Atom working as expected.

Potential issues:
  1. Making sure pane items cannot be "activated" regardless of pane.
  2. Being able to properly differentiate and document the differences between (activated, soft-activated, and not-activated)
  3. Validating that this change does not cause any unexpected functionality when relating to the focusing of different areas of the view.

The main purpose of this proposal was to get feedback, I was planning to implement this I just wanted to see if there were any thoughts, issues, or possible improvements.

**Comment by jasonrudolph** [comment]
@50Wliu: Thanks for the ping. :bow:

@pixilz: Thank you for the thoughtful proposal. :zap: :heart:

> Currently with Atom's new dock feature (Atom 1.17.0+) there is an issue with many packages using the atom.workspace.getActiveTextEditor() to get the currently active "editable" pane item.

We've been discussing this issue in https://github.com/atom/atom/issues/14648 and I'm working on a proposed solution in https://github.com/atom/atom/pull/14695.

Given the potential issues that you've cited in the proposal above, I find myself leaning toward https://github.com/atom/atom/pull/14695 as my preferred path forward. What do you think?

**Comment by pixilz** [comment]
@jasonrudolph I think it's a great solution for now but in the long term I think it's going to need to be revisited regardless of what is done.

It definitely is the best solution I've read though.
