### ISSUE TITLE
Scrollbar div still takes up space even if there's no scrollbar

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#14661]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Even when there is no need for a scrollbar, the scrollbar div is still rendered and has a non-zero size.
![useless-scrollbar-div](https://cloud.githubusercontent.com/assets/2766036/26524304/e751c272-42fc-11e7-94dd-38d406fc6497.png)

### Steps to Reproduce

1. Make sure that scrollbars are enabled (macOS only?)
2. Open a file whose contents can fit horizontally or vertically on the screen without a scrollbar.
3. Through devtools, notice that there are scrollbar divs taking up 20px.

**Expected behavior:** No scrollbar div if there's no scrollbar

**Actual behavior:** Scrollbar div is there

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.19.0-dev-9e64abef3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by nathansobo** [comment]
@50Wliu I always render the dummy divs because we use them to measure the width of scrollbars for use in various calculations. Maybe we can apply a CSS class to the scrollbar divs when the scrollbars are actually visible and only change the cursor then?

**Comment by nathansobo** [comment]
Basically, can you clarify the incorrect behavior that you're seeing as a result of the scrollbars always being rendered? Is it just the cursor styling or might it be other things as well?

**Comment by 50Wliu** [comment]
Right now, the only thing I've noticed as a direct effect of this is the incorrect cursor styling.  Though I suppose that any theme that adds extra styles to `.horizontal/vertical-scrollbar` will have those styles appear even when visually, there is no scrollbar.  For example:
![image](https://user-images.githubusercontent.com/2766036/29344479-1600fd02-8206-11e7-9ac5-26d16938655a.png)

**Comment by pfitzseb** [comment]
I'd like to second @50Wliu's point: 
For very small editors the (invisible) scrollbars take up most of the editor's area, hence the cursor will be incorrect for most of it:
![image](https://user-images.githubusercontent.com/6735977/29355297-c2dc23d4-8270-11e7-8630-b1fe561c7492.png)

**Comment by nathansobo** [comment]
@as-cii If you want to look into this one tomorrow, here are some thoughts: I think we may be able to hide the dummy scrollbars and only show them when they're actually needed or `forceScrollbarsVisible` is true. There are places where we assume they're rendered though, and I'm not sure if we'll need more sophisticated update logic to ensure that any time we assume they are rendered that they actually are.

Another approach might be to force their height / width to 0 unless `forceScrollbarsVisible` is true.
