### ISSUE TITLE
Linux Mint: Atom not reopening files

### ISSUE THREAD

**Issue by iuyte** [atom/atom#14663]
On Linux Mint 18.1 Serena, Atom does not reopen the files I last had open, causing an inconvenience that is quite annoying. On my Windows partition, it does reopen the files I was last editing. My `application.json` seems to always be
```Javascript
[{"initialPaths":["/home/ethan/VEX-709S-2018"]}]
```
and my icon on the dock runs the command
```Bash
/usr/share/atom/atom
```
This is reproducible in safe mode, and I quit by hitting the 'X' in the corner

**Comment by pixilz** [comment]
If you open your project with "Open Recent Project" and it opens in a new window. Then close the old window first then the new one. Does the path change (Just trying to find out if this is a duplicate issue)

**Comment by iuyte** [comment]
When I reopen a recent project, it's this:
```Javascript
[{"initialPaths":["/home/ethan/VEX-709S-2018","/home/ethan/VEX-709S-2018/cpls"]},{"initialPaths":["/home/ethan"]}]
```
Then is 
```Javascript
[{"initialPaths":["/home/ethan"]}]
```
After I close the first window and after the second

**Comment by iuyte** [comment]
A reinstall fixed it...
