### ISSUE TITLE
Beta: Crashes when saving a file to another dir contain other git repo

### ISSUE THREAD

**Issue by awo-dev** [atom/atom#14671]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am using Windows 10 Professional
```
Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

I have Repo-A and Repo-B. If I have added the folder containing Repo-A as a project in Atom and then try to save a file in the directory containing Repo-B, Atom will crash; it will still save the file in the directory containing Repo-B, however it still crashes. When opening Atom again, Atom will not recognize that the file was actually saved, and it will then open the file unsaved.

### Steps to Reproduce
1. Open Atom (the beta version)
2. Make sure to have 2 different git repositories
3. Add Repo-A to the project
4. Make a new file, save it in Repo-B directory
5. Wait for the crash

**Expected behavior:** I expected Atom to save and just ignore that the file is saved in another git repository.

**Actual behavior:** Atom crashed.

**Reproduces how often:** 100%

### Versions
```
OS      : Windows 10 Professional
Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

![atom-crash](https://cloud.githubusercontent.com/assets/5315872/26544628/b6fee728-4462-11e7-9476-5684f8a2c733.PNG)

**Comment by rsese** [comment]
Thanks for the report!  I wasn't able to reproduce with your steps though I'm on 1.18.0-beta2 on Windows 10.    If you update to 1.18.0-beta2 does Atom still crash?

Also, are you reproducing with specific git repos or can you also reproduce with simple test repos?

**Comment by awo-dev** [comment]
@rsese Can't reproduce in 1.18.0-beta2 either. I thought I was on the newest version. But well, seems like it has been fixed. Sorry for the inconvenience.

**Comment by rsese** [comment]
No problem, thanks for letting us know :bow:
