### ISSUE TITLE
Crash on ES.Next Class Method (Property) Decorator

### ISSUE THREAD

**Issue by joehannes** [atom/atom#14674]
Atom Crashes each time on parsing a property decorator (ES.Next/Babel)

![Screenshot or GIF movie](url)

## Repro Steps

1. Open a file with a property decorator and at least one letter for a function signature

or

1. Write a class with a property decorator
2. Start writing the funtion signature ... crash

**Expected:** Work as usual
**Actual:** Atom crashes

## Versions

* **Atom:**       1.16.0
* **Atom-Shell:** 
* **OS:**         linux 4.8.0-52-generic
* **Misc**
    * apm  1.16.1
    * npm  3.10.5
    * node 6.9.5 x64
    * python 2.7.12
    * git 2.7.4

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by joehannes** [comment]
So what's the issue now?
I think this issue is very easy to understand and doesn't necessarily need more clarification.
But anyway, I think I filled out the whole form as generated by the bug-report plugin.
The only thing I didn't do was make a screenie of my atom crashing ...
So what can I do to meet you half way ... I don't understand

**Comment by thomasjo** [comment]
There are details missing from your issue body. The most important of which is whether you have actually followed the required prerequisite checklist;

* Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

There's obviously a very good reason we use an issue template.

Either edit your original issue body using the issue template (or provide all required information in an equivalent format), or open a new issue where you use the issue template.

**Comment by 50Wliu** [comment]
`bug-report` was created before there were issue templates and doesn't include all the information that we need.  Now that issue templates exist, it is better that you file issues from the GitHub website.

**Comment by joehannes** [comment]
ahh, thx ...

**Comment by joehannes** [comment]
thx, you were right:
* it was an issue with linter-jscs
* linter-jscs they say is discontinued in favor of eslint
* the [issue](https://github.com/AtomLinter/linter-jscs/issues/313) was already reported
cheers
