### ISSUE TITLE
"Merge All Windows"

### ISSUE THREAD

**Issue by baelter** [atom/atom#14677]
MacOS Window menu item "Merge All Windows" would be awsm.

**Comment by jtbairdsr** [comment]
+1

**Comment by barraq** [comment]
This would be super convenient, for instance when you restart your computer and that previously all grouped windows reopen as independent windows ;) this is quite annoying.

**Comment by kaylanm** [comment]
Depends on underlying support in Electron, which is being added here:
https://github.com/electron/electron/pull/10271
and a forthcoming PR for the JS API.

**Comment by shaunc** [comment]
Looks like the electron PR has been merged. .. any news about "forthcoming PR"?

**Comment by 50Wliu** [comment]
@shaunc The PR is only in Electron 1.8.x, which is still in beta.

**Comment by kaylanm** [comment]
I did not end up sending another PR for the API because it was pointed out by @bpasero that

**Comment by guidezpl** [comment]
Electron 1.8 is out 👍

**Comment by mallchin** [comment]
Very frustrating trying to open multiple projects in one window.

**Comment by TG-KK** [comment]
Current Atom _v1.33.0_ is using Electron _v2.0.11_. I still don't see `Merge All Windows` option..

**Comment by whimshot** [comment]
BUMP!

I'm wondering if there is any traction on this. It would be awesome since I use Project Manager and it will open a new window any time I open a project.

Here's what I'm running at the moment:
_Atom: 1.34.0 x64_
_Electron: 2.0.16_
_Chrome: 61.0.3163.100_
_Node: v8.9.3_

**Comment by masscreation** [comment]
+1

**Comment by lee-dohm** [comment]
Thanks for the feedback.

Upon review with the team, this isn't something that we want to add. It would require significant architectural changes or workarounds and we don't feel that it would be of enough benefit to warrant the work that it would require. Because of this, we won't be accepting pull requests for this feature either.

Thanks again for the suggestions and interest in Atom.

**Comment by thebestbradley** [comment]
VS Code it is.
