### ISSUE TITLE
Disable repeated error notifications

### ISSUE THREAD

**Issue by adamboche** [atom/atom#14675]
Is it possible to disable repeated error notifications? They appear frequently and if "the issue has lready been reported" I don't really need to know about it. Here's an example:

![image](https://cloud.githubusercontent.com/assets/19828875/26562285/db6b457c-4479-11e7-8e14-2b8a29db7026.png)

Perhaps a "don't show this again" checkbox?

Related issues have varying degrees of resolution:

- https://github.com/atom/notifications/issues/104
- https://discuss.atom.io/t/can-i-turn-off-the-notifications/17117
- https://github.com/atom/atom/issues/8152

**Comment by rsese** [comment]
> Is it possible to disable repeated error notifications?

Based on the issues you referenced and since https://github.com/atom/notifications/issues/88 is still open, it doesn't look like this is currently possible.

Since requests for the behavior you're asking about looks to be covered in prior issues, I'll go ahead and close this as a duplicate.
