### ISSUE TITLE
"Open with Atom" won't work

### ISSUE THREAD

**Issue by Alivanar** [atom/atom#14688]
Hi there, (again), last time i forgot to fill up the  template, so here it is !

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

About 2 weeks ago now, the 'open with Atom' option in contextual menu (right click on file menu) won't work.

### Steps to Reproduce

Well idk how to reproduce that ....

**Expected behavior:** Open the file/folder i selected in the Atom editor

**Actual behavior:** Open the Windows menu to select a "default" application to open it with, if i reclick "atom", closes the window and opens the same one again
btw i noticed that there were no Atom icon on the side of that option -> missing shortcut or smth ? 

**Reproduces how often:** Well 100% of the time sadly ...

### Versions

I might be doing this wrong but "atom --version" wont work, saying that it does not recognise atom as a program, same for "apm --version". I'm currently running on W10 x64 Family.

### Additional Information

Until the moment it "broke" everything was running fine, i could use this option both on files and folders. 
+did not install other packages, etc ...

these are the screeshots of what i'm describing above, the seconds shows "atom.cmd" as default prog, that's because i saw smwhere it could fix the pb, (it did not) and of couse it has exacltly the same behavior as if i selected "atom" 

![openwith1](https://cloud.githubusercontent.com/assets/29014625/26654898/d529095c-4658-11e7-9e75-bf987a2f7e14.jpg)
![openwith2](https://cloud.githubusercontent.com/assets/29014625/26654913/e524b78e-4658-11e7-83d1-ddb81a626e07.jpg)

Thanks for your time, hope you'll be able to fix this soon !!
Ali

**Comment by 50Wliu** [comment]
Can you please try the following:
1. Open Atom
2. Open Settings (File -> Settings)
3. Navigate to the Systems tab
4. Uncheck and recheck the "Show in file context menus" option
and see if that works?

**Comment by Alivanar** [comment]
Well it seems to be working by re-checking the option, i guess it has been unchecked with the update !! Thanks for helping !

**Comment by 50Wliu** [comment]
Glad we figured out the problem!
