### ISSUE TITLE
Paste GitHub (Preview) auth token with mouse won't work

### ISSUE THREAD

**Issue by exalted** [atom/atom#14684]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [ ] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [ ] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [ ] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [ ] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using Atom `1.18.0-beta2` on Windows, right-click to paste the auth token for GitHub (Preview) won't show "paste" as an option; instead you have bunch of options for splitting and closing the pane.

Not a major issue (since `Ctrl-v` will do it), but still it doesn't seem to be the "correct" behaviour to me, hence the issue.

Cheers! 🍻 

### Versions

`1.18.0-beta2`

**Comment by rsese** [comment]
Thanks for the report!  Can you open this in https://github.com/atom/github?  I think that might be a better repo for this issue - if not we can always re-open this one :v:
