### ISSUE TITLE
Some command line options (--enable-gpu-rasterization) require a different order than specified in --help

### ISSUE THREAD

**Issue by olehermanse** [atom/atom#14680]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When starting atom from the command line, it seems some options have to be specified after the file path. This is not documented AFAICT.

Specifically I found that `--enable-gpu-rasterization` cannot come before the file path (as specified in `--help` usage, it only works correctly when it comes after).

I found this when reading and attempting workarounds for: 
https://github.com/atom/atom/issues/12634

### Steps to Reproduce

1. Make sure you close all atom windows and quit atom completely.
2. Start atom from the command line:
```
atom --enable-gpu-rasterization ~/some_project
```

**Expected behavior:** Atom starts, and opens the folder `~/some_project`

**Actual behavior:** Atom opens, but doesn't open the project folder

**Reproduces how often:** 100%

**Note:** Seems to be the same for `--disable-gpu` as well.

### Workaround
Switch the order of the arguments:
```
atom ~/some_project --enable-gpu-rasterization
```
or use a function (add to `~/.bash_profile`:
```
function atom-gpu {
    atom $1 --enable-gpu-rasterization ;
}
```

### Versions

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

Mac OS Sierra
Version 10.12.5

### Additional Information

This might be intended behaviour, for the more advanced options parameters, but I believe it should be documented (better?).

I'm sorry if this is documented somewhere, I tried searching Issues, FAQ, and message board, but couldn't find anything. Feel free to link to relevant docs and close issue if appropriate.

**Comment by 50Wliu** [comment]
I'm thinking that this is because the flags you're referencing are Chromium flags, not Atom flags.  So Atom disregards them when reading its options and passes them down to Chromium.
