### ISSUE TITLE
Rename file should replace the tab with the renamed file.

### ISSUE THREAD

**Issue by q4w56** [atom/atom#14692]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
   ...
### Description

Rename file should replace the tab with the renamed file.

### Steps to Reproduce

1. Right click a file in tab or file tree sidebar, 
2. Click rename
3. Enter the new name

**Expected behavior:** 
The active tab should be the newly renamed file.

**Actual behavior:**
The active tab remained the old un-renamed file. And I have to close it and open the renamed file.

### Versions
Atom: 1.16.0
OS: ubuntu 16.04

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/tree-view if there's no existing issue already so we have it in the right place?   Also, can you clarify your steps to reproduce a bit?  I'm not quite sure if you're renaming the file you currently have open or if you're renaming some other file.

**Comment by q4w56** [comment]
This is a duplicate of atom/tree-view#264
