### ISSUE TITLE
Horizontal scrollbar causes editor to jump to top

### ISSUE THREAD

**Issue by simurai** [atom/atom#14702]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When scrolling horizontally, the editor jumps to the top

### Steps to Reproduce

1. Open a file with long lines (that allow horizontal scrolling)
2. Scroll down a bit
3. Scroll to the right

**Expected behavior:**

Vertical scroll position shouldn't change.

**Actual behavior:**

Vertical scroll position jumps to the top

**Reproduces how often:**

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.19.0-dev-d16996f9c
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.12.2

macOS Sierra 10.12.5
```

### Additional Information

This PR https://github.com/atom/atom/pull/14686 sounded promising but didn't seem to fix the issue.

If I `display: none` the `.horizontal-scrollbar`, the issue seems fixed:

![jumping](https://cloud.githubusercontent.com/assets/378023/26708191/3de53380-4785-11e7-8e41-a50dcc83dc77.gif)

**Comment by 50Wliu** [comment]
Can't reproduce on Windows; assuming that this is a macOS-only bug (since scrollbars are always visible on non-macOS if you _can_ scroll).

**Comment by simurai** [comment]
Turned on the `scrollbars-visible-always` and it still happens:

![jumping2](https://cloud.githubusercontent.com/assets/378023/26708444/d3f31ecc-4786-11e7-9b04-9b3949a7bb27.gif)

**Comment by sean-codes** [comment]
Hi I was experiencing this same issue it was driving me crazy! I'm on Windows. Turned out was from me hiding scroll bar in my style sheet like this:

     .vertical-scrollbar{
        display:none;
     }

I removed that and seems to be working fine now. I was hiding that because I was using the mini map package. Hope it might help one thing I see in your gif is your vertical scrollbar is not visible something might be hiding it

**Comment by simurai** [comment]
I also can't reproduce it anymore. Let's close it again.

**Comment by jdanbrown** [comment]
This bug is happening for me in atom 1.23.3 on mac 10.11.6 (El Capitan) when I have:
```less
// Bad
atom-text-editor {
  .vertical-scrollbar {
    display: none;
  }
}
```

I can workaround the bug by hiding the horizontal-scrollbar as suggested above:
```less
// Good
atom-text-editor {
  .vertical-scrollbar {
    display: none;
  }
  .horizontal-scrollbar {
    display: none;
  }
}
```
