### ISSUE TITLE
Atom should warn user if file changed on disk if file is unsaved on Atom and has been modified elsewhere

### ISSUE THREAD

**Issue by ungb** [atom/atom#14709]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom should warn user if file changed on disk if file is unsaved on Atom and has been modified elsewhere.

### Steps to Reproduce

1. Open a file on atom and make some changes (e.g add a space somewhere)
2. Open the same file on vim, make some changes to the file and save.  
3. Go back to atom and save the file

**Expected behavior:** [What you expect to happen]
Atom should warn the user that the file on disk has been modify since it was last loaded. 

**Actual behavior:** [What actually happens]
Atom doesn't show or do anything.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.19.0-dev-d289ca447
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

subl warns the user:
![image](https://cloud.githubusercontent.com/assets/5624870/26746736/43265c9a-47a6-11e7-86f5-9578c3c6f2dd.png)

Vim does too:
![image](https://cloud.githubusercontent.com/assets/5624870/26746740/4ae60ebc-47a6-11e7-9770-35b9a43152b5.png)

VS Code:

![image](https://cloud.githubusercontent.com/assets/5624870/26746767/7432ab04-47a6-11e7-821a-aa29019a5283.png)

Any additional information, configuration or data that might be necessary to reproduce the issue.

/cc @iolsen @maxbrunsfeld

**Comment by emmanuelito** [comment]
A closely related point:
- edit in Atom a file F in a directory X
- move X elsewhere (mv on unix-like systems)
- save file F from Atom
*ouch*:
 - file is silently re-created in X (no warning)
 - directory X is created by Atom !

This is specially annoying when editing remotely shared files (eg NFS): if the volume is not mounted, Atom create the mounting point directory (empty, et /Volumes/X on MacOS) and fails. This empty directory stay in the way and prevent mounting the server's volume.
