### ISSUE TITLE
files with lots of lines hang the editor

### ISSUE THREAD

**Issue by ChrisRiddell** [atom/atom#14705]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When opening or selecting from the projects panel files that have alot of lines, file size of 600kb+ (.txt, .gcode) (around 23373+ lines with around 27 characters per line) the editor hangs and I get an error message saying the editor has stopped responding clicking wait the file will eventually load after some time.

### Steps to Reproduce

1. Open a file with many lines over 20,000 

**Expected behavior:** It to load the file in a timely manner with out hanging and displaying an error.

**Actual behavior:** The editor hangs.

**Reproduces how often:** 100%

### Versions

Atom    : 1.18.0-beta2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python
git
visual studio

Windows 10
Version 1703

### Additional Information

![error_1](https://cloud.githubusercontent.com/assets/2055566/26720363/1b8b94c2-47c7-11e7-9972-0c5efeda9bb6.PNG)

When I tried to do the CPU profiling it through an error and saving what was recorded leads to an empty .cpuprofile file
![error](https://cloud.githubusercontent.com/assets/2055566/26720456/8815bf0a-47c7-11e7-84df-31ec33830e38.PNG)

**Comment by rsese** [comment]
Thanks for the report!  There are a handful of issues that report the same behavior e.g https://github.com/atom/atom/issues/8864 but I couldn't find an open one to cross-ref.  Since you're on Windows though, curious if you might be hitting https://github.com/atom/spell-check/issues/190?  Can you try disabling spell-check and see if that helps?

**Comment by ChrisRiddell** [comment]
@rsese You are correct disabling spell-check fixed the issue.

**Comment by 50Wliu** [comment]
Thanks for following up @ChrisRiddell!  I think we'll close this issue in favor of the spell-check issue.
