### ISSUE TITLE
Creating a folder with multiple subdirectories entirely inside Atom on Windows makes folder undeletable

### ISSUE THREAD

**Issue by galexite** [atom/atom#14703]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Creating a new folder with subdirectories that have text files entirely created in the Atom text editor results in an inability to delete that folder _whilst Atom is open_.

### Steps to Reproduce

1. Create a heirarchy like the following entirely inside Atom's Tree View:

![tree](https://cloud.githubusercontent.com/assets/6300838/26750744/988ab6f6-483a-11e7-9ceb-e416ef99ba12.PNG)

2. Try and delete the directory inside either Atom or Explorer _whilst an Atom window is open_.

The problem does not apply to directories created inside Explorer.

**Expected behavior:** The entire directory is deleted.

**Actual behavior:**

Atom presents the following dialog box:

![Permissions](https://cloud.githubusercontent.com/assets/6300838/26711626/b2b487aa-4772-11e7-81b0-1f5b770c211e.PNG)

Giving UAC permissions does nothing.

Attempting to delete the folder in Explorer results in:

![Explorer](https://cloud.githubusercontent.com/assets/6300838/26712043/ad27ef90-4775-11e7-8027-034218157d03.PNG)

I *am* George. And this folder is inside my Documents directory.

**Reproduces how often:** Every time, in different parts of the C: filesystem, _and on a freshly formatted NTFS drive_.

### Versions

![Atom version 1.17.2](https://cloud.githubusercontent.com/assets/6300838/26711632/b5da1198-4772-11e7-9a9b-9d1d0ccb47b1.PNG)

![Windows 10](https://cloud.githubusercontent.com/assets/6300838/26711660/0e7763dc-4773-11e7-906a-1d1134614b36.PNG)

**Comment by galexite** [comment]
The `test2` folder contained `created-inside-atom`.

**Comment by rsese** [comment]
I'm unable to reproduce on Windows 10 and Atom 1.17.2 - did this behavior just start after updating to 1.17.2 or did you just install Atom?

**Comment by galexite** [comment]
@rsese Thinking about this, it must have started to show sometime after the 1.17.0 update because I had a few permission errors but nothing like this. I used other text editors for a whole week (Neovim, Notepad++ and a trial of Sublime Text) which never had such issues but came back to Atom a few days ago.

**Comment by galexite** [comment]
@rsese I can reproduce this on a freshly formatted NTFS USB drive.

**Comment by galexite** [comment]
Deleting each file from the directory going outwards works, i.e.:

1. Delete `created-in-atom/a/b/c/test.txt`
2. Delete `created-in-atom/a/b/c`
3. Delete `created-in-atom/a/b`
... and so on

Neither Atom nor Explorer simply allow you to delete any one of those directories until they are empty.

**Comment by galexite** [comment]
You know what? After searching around, I found open issue #5481, in which one user suggested closing all Atom windows before deleting the files. After entirely closing Atom, I can delete the directories like normal.

Atom must be locking something?
