### ISSUE TITLE
keybinding ctrl-tab conflicts with MacOS system keybinding

### ISSUE THREAD

**Issue by MarloweW** [atom/atom#14704]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

MacOS 10.12 has a system wide keybinding `ctrl-tab` which can be used to switch tabs inside a window, like this: 
![macos-switch-tabs](https://cloud.githubusercontent.com/assets/9361073/26719358/c9a83b52-47b6-11e7-82c0-ae5f66227d8d.gif)

But atom has use it for show-next-recently-used-item:

```
'body':
  'ctrl-tab': 'pane:show-next-recently-used-item'
```

Which causes I can't switch window-tab atom via shortcut.

![image](https://cloud.githubusercontent.com/assets/9361073/26719446/2696d0da-47b7-11e7-9476-22426dc4d9c2.png)

### Versions

Atom 1.17.2
MacOS 10.12

**Comment by rsese** [comment]
You can unset keybindings as described here:

https://github.com/atom/atom/issues/11035#issuecomment-209875101

But I've played with this a bit before and I *think* this might not currently be possible with Electron /cc https://discuss.atom.io/t/shortcut-for-cycling-between-macos-sierra-tabs/42312/3?

**Comment by MarloweW** [comment]
Yes, but disable that keybinding won't make switch tabs with ctrl-tab work. Seems vscode got it fixed.

**Comment by rsese** [comment]
> Seems vscode got it fixed.

Oh huh, I have VS Code installed but <kbd>ctrl-tab</kbd> doesn't switch native tabs for me - is there a setting I'm missing?
