### ISSUE TITLE
unable to update plugins

### ISSUE THREAD

**Issue by propertunist** [atom/atom#14719]
### Description

For many months now i have been unable to update any plugins inside atom. I am running Fedora 25 and currently running Atom 1.17.0 x64. After running the upgrade process i see a fatal error listed for all plugins and this is the same in safe mode.

### Steps to Reproduce

1. click 'Update all' in the plugin list area

**Expected behavior:** [What you expect to happen]

Plugins get updated.

**Actual behavior:** [What actually happens]

Error messages are displayed:

```
Updating to “highlight-selected@0.13.1” failed.Hide output…
/bin/sh: /bin/electron: No such file or directory


gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@6.10.3 | linux | x64
gyp ERR! install error 
gyp ERR! stack Error: Invalid version number: undefined
gyp ERR! stack     at install (/usr/lib/node_modules/node-gyp/lib/install.js:50:21)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/lib/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at run (/usr/lib/node_modules/node-gyp/bin/node-gyp.js:72:30)
gyp ERR! stack     at Object.<anonymous> (/usr/lib/node_modules/node-gyp/bin/node-gyp.js:133:1)
gyp ERR! stack     at Module._compile (module.js:570:32)
gyp ERR! stack     at Object.Module._extensions..js (module.js:579:10)
gyp ERR! stack     at Module.load (module.js:487:32)
gyp ERR! stack     at tryModuleLoad (module.js:446:12)
gyp ERR! stack     at Function.Module._load (module.js:438:3)
gyp ERR! stack     at Module.runMain (module.js:604:10)
gyp ERR! System Linux 4.10.15-200.fc25.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=undefined" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /home/ura/.atom
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

1.17.0 x64
Fedora 25 64bit

**Comment by propertunist** [comment]
so i uninstalled atom and downloaded the latest rpm from the atom website. i noticed that the atom icon is missing from the fedora activities menu. when i first ran atom, it looked like the same problem persisted.. but then, by magic, after closing atom and coming back to it about 10 minutes later, suddenly all the plugins updated. i doubt it is related but github had major system problems during the same time that the update process started working.

**Comment by 50Wliu** [comment]
Glad you managed to fix the issue @propertunist.  If it happens, please let us know and we'll investigate further.  In addition, next time you open an issue, it would be much appreciated if you copy/pasted the _entire_ output of `atom --version` since it contains more than just Atom's version info :smile:.

**Comment by wjs876046992** [comment]
I have had the same issue for some days.
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | linux | x64
gyp http GET https://atom.io/download/electron/v1.3.15/iojs-v1.3.15.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT 54.231.98.200:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.3.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /home/herman/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```
My atom version is **1.17.2**.

**Comment by anomaly256** [comment]
@wjs876046992 this looks like a separate issue (I've hit it too just now trying to build atom v1.18.0)

**Comment by fermulator** [comment]
What's the verdict here?

I ran into the same (running an OLD version of Atom though)  `atom-1.20.1-1.git966dfcc.fc25.x86_64`

Seems like it's expectations about where electron is is false...

$ locate electron | grep bin
/usr/bin/electron
/usr/bin/electron-1.3.13

$ ll /bin/electron
lrwxrwxrwx 1 root root 26 Nov  2 13:02 /bin/electron -> /etc/alternatives/electron

$ rpm -qa |  grep electron
electron-1.6.9-1.prebuilt.fc25.x86_64

$ ll /usr/bin/electron
lrwxrwxrwx 1 root root 26 Nov  2 13:02 /usr/bin/electron -> /etc/alternatives/electron

**Comment by fermulator** [comment]
I had to manually remove /usr/bin/electron broken link to /etc/alternatives/electron, and forcibly link it to /usr/bin/electron-#.#.# ... this feels like it will break on next upgrade.

**Comment by 50Wliu** [comment]
> atom-1.20.1-1.git966dfcc.fc25.x86_64

This seems like an unofficial distribution of Atom.  Make sure you are installing Atom from https://atom.io.

**Comment by rocketraman** [comment]
> I had to manually remove /usr/bin/electron broken link to /etc/alternatives/electron, and forcibly link it to /usr/bin/electron-#.#.# ... this feels like it will break on next upgrade.

Thanks for this, it worked on my Fedora 25 machine as well which uses mosquito-atom from copr... FYI rather than doing the link manually, you can use `alternatives --config electron` to have the system do it. Probably a previously bad package update broke the link somewhere along the way.
