### ISSUE TITLE
(Ctrl + Alt + -) i can no longer view my work

### ISSUE THREAD

**Issue by Dectom** [atom/atom#14726]
The combination is a hot key for me and i used it and it started shortening the size of my atom work space until it is now like this http://i.imgur.com/NyPBkRD.png,

i'm currently totally unable to look at what i have open, 
view settings
edit work

### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
<kbd>ctrl-alt-=</kbd> does the opposite and increases the pane size.  Alternatively, if you have no unsaved work, `atom --clear-window-state` is also an option.
