### ISSUE TITLE
"Save As" for new file doesn't default to a sensible directory location

### ISSUE THREAD

**Issue by jbt** [atom/atom#14732]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When creating a new file and hitting Save, the save dialog doesn't seem to have any particular directory set and defaults to a platform-dependent location.

### Steps to Reproduce

1. Create a new untitled file
2. Save it

**Expected behavior:**

"Save As" dialog should default to a sensible location (most likely the project root, which definitely _used_ to be the behaviour)

**Actual behavior:**

**On Ubuntu**, Save dialog opens at "Recently Used", sometimes making it a pain to find the logical place to save the file.

**On mac**, seems to default to project root directory, but **only** for the first window opened (I assume it defaults to the process's cwd)

Can't speak for windows right at the moment I'm afraid

Directory is set fine if you're hitting "save as" from a file that already exists.

**Reproduces how often:**

Every time

### Versions

Currently 1.18 beta but basically every version since #13978 was reported

### Additional Information

I guess #13978 got closed because the desired behaviour was fixed on mac for the first-opened window and for already-existing files. Looks like this was also reported in #14304 but that was closed because it didn't follow the template.

**Comment by rsese** [comment]
Thanks for the report!  I went ahead and installed 1.14.4 (the last stable release version before https://github.com/atom/atom/issues/13978 I think) on macOS and Atom seeeems to default to the project root of the current window when saving a new file.

On 1.17.2 and macOS, I do see different behavior though I'm not seeing the same behavior as you described:

> On mac, seems to default to project root directory, but only for the first window opened (I assume it defaults to the process's cwd)

My steps:

1. Start Atom with `atom --safe`
2. Open a project
3. Create a new file
4. Save the file <kbd>cmd-s</kbd>

At this point the default directory is one level above where the project is - if I start a new window and open a second project (the second project is located in the same directory level as the project above):

1. Start a new window <kbd>cmd-n</kbd>
2. Open another project 
3. Create a new file
4. Save the file <kbd>cmd-s</kbd>

The default directory is the same as above, one level above the project location.

I'll go ahead and label as a bug for now.

**Comment by jbt** [comment]
I admit I didn't dig too much into the mac behaviour (my main dev machine is ubuntu, where the experience is more painful, but I wanted to see how other platforms handled it and whether it was related) but here's the exact steps (as I recall) that I did:

 1. With Atom not running, in terminal, in my `~/Development` which contains folders `foo` and `bar`, `atom foo` (with or without `--safe`)
 2. (at this point Atom appears, and creating a new file with cmd-s defaults to `~/Development/foo` as expected)
 3. Without closing the existing Atom window, back in terminal, run `atom bar`
 4. The new Atom window that opens with `bar` still defaults to saving within `~/Development/foo` on saving a new file

I was only checking briefly with the "simple" / un-expanded osx save dialog, so literally just looking at the name of the directory that gets selected in the "where" dropdown - although I imagine whether or not you have the dialog in "expanded" mode probably doesn't have any bearing on this behaviour (other than maybe making it more visible)

**Comment by segevfiner** [comment]
On Windows it defaults to the process working directory. I think the native dialog does remember the last save location per process after saving something once, at least that's how it behaves for most programs but I didn't test this in Atom.

**Comment by pietrovismara** [comment]
This issue on ubuntu is really annoying. 95% of the times i want to save a new file i'd like to do it in the current project directory, but the save file dialog defaults on recently used and i have to search again for the current directory. I feel it was much better before, when it defaulted to the current project directory.
