### ISSUE TITLE
EDITOR IS NOT RESPONDING!!!

### ISSUE THREAD

**Issue by echonox** [atom/atom#14739]
### Description

This is happening for months its freaking annoying!
Editor is not responding every time I close atom with files left opened and then I try to open it again, the editor is stuck I always have to clear the state to fix this!

### Steps to Reproduce

1. Open some large project files 4-5 with over 10000 lines of code
2. Close the editor
3. Restart PC
4. Open atom from the desktop link
5. Atom is stuck

I expect atom to work

Atom gets stuck and its not responding

99.99%

### Versions

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Is there are a way to stop atom from saving the state?? or auto closing the tabs on exit?
Also: I have auto compile less plugin and a theme (not a chance its related as in safe mode I have same problem)

**Comment by swizzley** [comment]
Yeah mine too, I even updated today to try n resolve it, I'm on 1.17.2 now and I still have a project history but it's totally unusable. I can't open anything. 

<img width="514" alt="screen shot 2017-06-08 at 10 04 25 am" src="https://user-images.githubusercontent.com/8236665/26938604-e860ca3a-4c31-11e7-929f-ee11481e682b.png">

**Comment by swizzley** [comment]
Removing my ~/.atom dir resolved the issue, all config now lost.

**Comment by rsese** [comment]
Can you confirm what operating system you're on @echonox?  There are a handful of issues about hanging with files with a lot of lines (e.g. https://github.com/atom/atom/issues/14705 and https://github.com/atom/atom/issues/8864) though it sounds like it only happens to you after closing and re-opening Atom?  Also, are the set of files you work on public by any chance so we can try to reproduce?

> Is there are a way to stop atom from saving the state?? or auto closing the tabs on exit?

I don't think there's a way to stop Atom from saving project state but if you disable `Settings > Core > Restore Previous Windows On Start`, Atom will load a blank environment when you restart.

Though not automatic, there's also a command to close all tabs (`tabs:close-all-tabs`) so you could also add a keybinding for this command.

**Comment by rsese** [comment]
> Removing my ~/.atom dir resolved the issue, all config now lost.

Sorry @swizzley - if you run into something similar in the future, I'd recommend starting by clearing saved state:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

And if that doesn't work, temporarily reset to factory settings by moving your `~/.atom` directory rather than deleting it.  If that works, then you could try copying over your config.

**Comment by echonox** [comment]
@rsese 

OS: Windows 10 Pro X64
CPU: AMD APU a10 7300
GPU1: AMD R6
GPU2: AMD R7 m265

sorry but the project is private..

It only happens if I left some big file opened and then I close and restart the pc and then after I try to open Atom I get the issue, I will try disabling spell check and left large file opened on purpose will report tomorrow if this fixes my issue.

**Comment by rsese** [comment]
> It only happens if I left some big file opened and then I close and restart the pc

Interesting, only when you restart your computer?  So if you leave a big file open, quit Atom, and restart Atom you don't see the same behavior?

> I will try disabling spell check and left large file opened on purpose will report tomorrow if this fixes my issue.

Thanks, let us know how it goes :+1:

**Comment by vvs** [comment]
I am experiencing the same problem. Happens 2-3 times per day, when I have a rather big project, with 10-15 tabs open (mostly JS/HTML).

Basically, one time out of 5 the atom editor hangs on startup. I see the window, I can even see the content of the file (no coloring though), and then nothing actually works, and no mouse/keyboard input accepted. I have to kill the editor, clear the state and then it works, until it gets stuck again later on, during one of the attempts to launch Atom editor again.

Tried both 1.17.2 and 1.18 beta 2 and beta 3. Windows 10 x64.

I am basically copying `C:\users\USER_NAME\AppData\Roaming\Atom` folder every time after I close Atom. If the next Atom launch is stuck, I kill it, I delete the above mentioned Atom folder, and copy previous version (which is known to be good). Kinda annoying to say the least. :)

Launching in safe mode doesn't help. I either have to clear the saved state or do the trick with moving the Atom configuration folder.

Also, starting with empty Atom and then opening the "problematic" project also leads to hang-up of that window with the project.

Is there anything I could do to help solving this hanging problem? Some kind of logging, debugging, anything?

**Comment by vvs** [comment]
Disabling spell-check package solved the problem for me, many thanks!!!

**Comment by echonox** [comment]
I can confirm that disabling spell-check package also solved the problem, thanks :)
