### ISSUE TITLE
apm.sh script generates incorrect paths on cygwin

### ISSUE THREAD

**Issue by jh3141** [atom/atom#14730]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Basically the same as issue #9169, only for apm.sh rather than atom.sh.

When `apm` or `apm.sh` is run from a cygwin shell, it produces an incorrect path to the implementation .js file, producing an error that looks like this:

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\cygdrive\c\Users\admin\AppData\Local\atom\app-1.17.2\resources\app\apm\lib\cli.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
Presumably, apm.sh should have a windows-specific stub that corrects for cygwin/msys paths, similarly to the way atom.sh currently handles things.

### Steps to Reproduce

1. On a fresh install
2. Open cygwin bash
3. Run `/cygdrive/c/Users/[your username]/AppData/Local/atom/bin/apm`

**Expected behavior:** Should behave that same as if you run `/cygdrive/c/Users/[your username]/AppData/Local/atom/bin/apm.cmd`

**Actual behavior:** Produces error message quoted above.

**Reproduces how often:** Always

### Versions

```
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python
git 2.8.3
visual studio 2015
cygcheck (cygwin) 2.7.0
GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)
```

**Comment by rsese** [comment]
Thanks for the report!  I went ahead and moved it to atom/apm so we have it in the right place /cc https://github.com/atom/apm/issues/725
