### ISSUE TITLE
/usr/bin/atom: line 123: /home/suleiman/.atom/nohup.out: Permission denied

### ISSUE THREAD

**Issue by Omeiza17** [atom/atom#14742]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Permission denied to user Atom]

### Steps to Reproduce

1. [Download atom]
2. [Install via 'sudo dpkg --install package]
3. ['atom' to run]

**Expected behavior:** [Atom welcome page]

**Actual behavior:** ["/usr/bin/atom: line 123: /home/suleiman/.atom/nohup.out: Permission denied" Error gotten && 
![screenshot at 2017-06-09 01-43-16](https://user-images.githubusercontent.com/27736878/26953122-9fcb8dc2-4cb9-11e7-88c3-bf77cf697838.png)
]

**Reproduces how often:** [Happens everytime]

### Versions
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
OS: Linux Mint 
OS version : 18

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Can you please try removing the `~/.atom/compile-cache` folder and seeing if that fixes the issue?

**Comment by Omeiza17** [comment]
@50Wliu It still displays the same error and won't even run when I try opening from applications panel

**Comment by glona73** [comment]
Same problem, the file `~/.atom/nohup.out` was empty and owned by root. Deleting the file fixed the issue

**Comment by Olli** [comment]
In some cases it's a "problem" with apparmor. 
try
sudo su -
aa-complain /usr/bin/atom

And then start Atom. If it works you have to do the following

sudo su -
aa-logprof 
(follow the menu)
aa-enforce /usr/bin/atom

**Comment by rsese** [comment]
@Omeiza17 are you still having this problem?
