### ISSUE TITLE
Feature Request: Track which screen to display windows on

### ISSUE THREAD

**Issue by jeffmoss** [atom/atom#14746]
It'd be neat if, when I press the [Restart] button, Atom restarted on the same monitor that it was on, in the same place even.  Sometimes I have 2 editor windows on different screens. It'd be nice if Atom tracked all of the display-related information.

**Comment by LauraAubin** [comment]
I'd like to either work on this feature request or pair with someone who wants to take it on.

**Comment by 50Wliu** [comment]
This looks like a duplicate of #6268.

@LauraAubin Great to hear!  You might be able to find someone else in #6268, and there's also some advice at the bottom of that issue.
