### ISSUE TITLE
[v1.19] adding blockDecoration makes editor rendering odd

### ISSUE THREAD

**Issue by t9md** [atom/atom#14743]
![block-decoration-issue-on-v1 9](https://user-images.githubusercontent.com/155205/26959598-c1407704-4d0b-11e7-922c-66d4cca79aae.gif)

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Block decoration occupy two screen row, and after I render block decoration, cursor, line-gutter shows incorrect place.

Tried last build on #14435, (commit: https://github.com/atom/atom/pull/14435/commits/a5f4472f5d422d6185c6952ae2c3a6cef68eec1d) which is last commit before merged to master.

- [Download link](https://4126-3228505-gh.circle-artifacts.com/0/Users/distiller/atom/out/atom-mac.zip)
- version

```
Atom    : 1.19.0-dev-a5f4472
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Steps to Reproduce

I can reproduce with **safe-mode**

1. open editor, insert three lines of text whatever (`row0\nrow1\nrow3`)
2. open chrome dev-tools and paste following js code.

```javascript
(function reproduceIssue() {
  const editor = atom.workspace.getActiveTextEditor()
  const cursorRow = editor.getCursorBufferPosition().row
  const item = document.createElement("span")
  item.innerText = "[block decoration]"
  const marker = editor.markBufferPosition([cursorRow, 0])
  editor.decorateMarker(marker, { type: "block", item: item })
})()
```

3. See **line-gutter**, insert text to row0, row1, row2 and see cursor is shown in incorrect screen position.

**Expected behavior:** [What you expect to happen]

can edit normal way
block decoration occupy one screen row as like in previous release.

**Actual behavior:** [What actually happens]

rendering become odd.

**Reproduces how often:** [What percentage of the time does it reproduce?]

always

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

My [narrow](https://atom.io/packages/narrow) package directly affected this issue.
Here is gif with same-build-Atom.

The first line's buttons are items in single block decoration.
The cursor is row 0 in previous release, but with latest-build, cursor and lines render incorrectly because of this issue.

![block-decoration-issue-on-v1 9-2](https://user-images.githubusercontent.com/155205/26959759-cb225ab6-4d0c-11e7-9f9b-61d979b032ad.gif)

**Comment by 50Wliu** [comment]
@t9md do you know the last commit where you're certain that everything was working as expected?

**Comment by t9md** [comment]
Sorry, I can't tell when.

**Comment by maxbrunsfeld** [comment]
Yeah, this must have regressed in the editor rewrite.

/cc @nathansobo @as-cii
