### ISSUE TITLE
Pulling the tracking git branch via UI causes error

### ISSUE THREAD

**Issue by vvs** [atom/atom#14756]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Doing git pull via the new Atom UI (pressing the "down arrow" button in the bottom-right corner, and then pressing "Pull" button) causes the following error:

Unable to pull
fatal: Couldn't find remote ref my-local-branch-name

Doing the 'git pull' from the command line works fine.

Please note that there is no 'my-local-branch-name' on the server indeed, the remote branch name is different, but the local branch is set to track that remote branch, let's call it "my-remote-branch".

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions
Atom    : 1.18.0-beta3
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

Let me know if you need more info (and how to get that info).

**Comment by 50Wliu** [comment]
@vvs The git/github functionality is provided via the [github](https://github.com/atom/github) package; we would appreciate it if you could file this bug on that repository instead.  Thanks!
