### ISSUE TITLE
Typing problem 

### ISSUE THREAD

**Issue by efnan34** [atom/atom#14759]
### Description

i cant type.

### Steps to Reproduce

1. create a new file 
2. try to type 
3. but nothing happens

**Expected behavior:** 

I expect to type

**Actual behavior:** 
no typing

**Reproduces how often:** 
85

 %

### Versions

1.17.2 windows platform
### Additional Information

it occurs when the cursor looks like this . it s not insert thing 

<img width="642" alt="untitled" src="https://user-images.githubusercontent.com/22750352/27031419-d6bffb3a-4f78-11e7-8f0c-d98fde7353c8.png">
<img width="733" alt="untitled2" src="https://user-images.githubusercontent.com/22750352/27031421-d8131238-4f78-11e7-93ec-8f3e580ce76b.png">

**Comment by 50Wliu** [comment]
Ensure that:
* You do not have the `synced-sidebar` package installed
* If you are using a Vim package, that you are in insert mode (<kbd>i</kbd>)

**Comment by efnan34** [comment]
i figured out that it happens when i press ctrl+c .There is Vim package installed.
Thanks for reply .

**Comment by 50Wliu** [comment]
Glad you figured it out.
