### ISSUE TITLE
Spellcheck on file tree view items

### ISSUE THREAD

**Issue by oldo** [atom/atom#14755]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Spell check seems to be active for items in the file tree view, which isn't necessary. Can we deactivate spell check for the tree view? 

### Steps to Reproduce

1. Select a file in the tree view

![screen shot 2017-06-12 at 14 31 40](https://user-images.githubusercontent.com/4557648/27019486-42487d7a-4f7c-11e7-8996-8804a348a7de.png)

**Expected behavior:** [What you expect to happen]

Spell checking not necessary in tree view

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.10.1

MacOS 10.12.5

### Additional Information

`apm list`
```
Built-in Atom Packages (90)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.3
├── one-light-ui@1.10.3
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.6
├── archive-view@0.63.2
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.1
├── autocomplete-html@0.7.3
├── autocomplete-plus@2.35.3
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.2
├── background-tips@0.27.0
├── bookmarks@0.44.3
├── bracket-matcher@0.85.5
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.3
├── exception-reporting@0.41.4
├── find-and-replace@0.208.3
├── fuzzy-finder@1.5.8
├── git-diff@1.3.5
├── go-to-line@0.32.0
├── grammar-selector@0.49.4
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.6.3
├── link@0.31.3
├── markdown-preview@0.159.12
├── metrics@1.2.5
├── notifications@0.67.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.249.4
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.7
├── styleguide@0.49.6
├── symbols-view@0.115.5
├── tabs@0.106.0
├── timecop@0.36.0
├── tree-view@0.217.1
├── update-package-dependencies@0.12.0
├── welcome@0.36.3
├── whitespace@0.36.2
├── wrap-guide@0.40.1
├── language-c@0.57.0
├── language-clojure@0.22.2
├── language-coffee-script@0.48.6
├── language-csharp@0.14.2
├── language-css@0.42.2
├── language-gfm@0.88.1
├── language-git@0.19.0
├── language-go@0.43.1
├── language-html@0.47.2
├── language-hyperlink@0.16.1
├── language-java@0.27.0
├── language-javascript@0.126.1
├── language-json@0.19.0
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.13.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.38.0
├── language-property-list@0.9.1
├── language-python@0.45.2
├── language-ruby@0.71.0
├── language-ruby-on-rails@0.25.2
├── language-sass@0.59.0
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.4
├── language-text@0.7.2
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.0
└── language-yaml@0.29.0

Community Packages (19) /Users/oldo/.atom/packages
├── Sublime-Style-Column-Selection@1.7.4
├── atom-panda-syntax@0.18.0
├── atom-wrap-in-tag@0.6.0
├── autocomplete-modules@1.6.10
├── busy-signal@1.4.1
├── file-icons@2.1.5
├── intentions@1.1.2
├── linter@2.1.4
├── linter-eslint@8.1.7
├── linter-php@1.3.2
├── linter-ui-default@1.4.0
├── nuclide@0.229.0
├── oceanic-next@1.0.0
├── pigments@0.39.1
├── project-manager@3.3.5
├── react@0.16.2
├── sync-settings@0.8.1
├── tab-foldername-index@2.0.3
└── toggle-quotes@1.0.1
```

**Comment by scholtzm** [comment]
AtomLinter will underline names of files which are currently open and contain lint issues. Maybe that's your case?

![image](https://user-images.githubusercontent.com/2640934/27024083-83c50ace-4f55-11e7-8ab6-9439f3ee39ae.png)

**Comment by 50Wliu** [comment]
Yes, that is a feature of Linter.

**Comment by oldo** [comment]
Ok, thanks :-)
