### ISSUE TITLE
.DS_Store still gets recognized regardless of core settings

### ISSUE THREAD

**Issue by XavierFahn** [atom/atom#14752]
![screen shot 2017-06-10 at 3 51 52 pm](https://user-images.githubusercontent.com/24502450/27006876-6e53b3a4-4df5-11e7-8a71-6ad8c93d6910.png)

**Comment by arcticicestudio** [comment]
You should make sure to enable the *Hide Ignored Names* and *Hide VCS Ignored Files* settings of the Atom core package [`tree-view`](https://github.com/atom/tree-view).
The default values are `false`.

![ghi-14752-scrot-tree-view-package-settings](https://user-images.githubusercontent.com/7836623/27012139-904d288e-4eca-11e7-8f93-077637467360.png)

**Comment by XavierFahn** [comment]
Ok thank you very much.

**Comment by 50Wliu** [comment]
Looks like issue has been resolved.
