### ISSUE TITLE
ctrl+t bug on linux

### ISSUE THREAD

**Issue by austindenny** [atom/atom#14751]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
I'm using atom on Linux (elementary loki), and have noticed that the ctrl+t command only works to open a search modal when I remove the cursor from any open text documents and click into the window tab bar.

### Steps to Reproduce

1. open atom, open multiple text documents in one window
2. cursor in one of the docs, execute ctrl+t
3. click into the document tab bar at the top, execute ctrl+t again

**Expected behavior:** pressing ctrl+t with focus on atom opens new-file search modal at top of window

**Actual behavior:** pressing ctrl+t only opens search modal if cursor is removed from open text document by clicking into the window tab bar

**Reproduces how often:** 90%

### Versions

#bug

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Cannot reproduce on Windows 10 x64, Atom 1.19.0-dev-c6bf86c9b.

@austindenny can you please paste the output of `atom --version` here?  In addition, just as a confirmation, did you see if this behavior worked in safe mode (`atom --safe`)?

**Comment by austindenny** [comment]
not near my desktop at the moment, but it should be the most recent debian package running on elementary OS. I'll pull version later today

**Comment by notunderground** [comment]
Reproducted Ubuntu 16.04, atom 1.18.0
