### ISSUE TITLE
Nested git repo is ignored by fuzzy finder when "Exclude VCS Ignored Paths" checked

### ISSUE THREAD

**Issue by kuzi117** [atom/atom#14764]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Checking out a git repo inside another git repo while "Exclude VCS Ignored Paths"  is turned on ignores all files inside the nested repo when searching in the fuzzy finder. 

### Steps to Reproduce

1. git clone git@github.com:llvm-mirror/llvm.git
2. cd llvm/tools
3. git clone git@github.com:llvm-mirror/clang.git
4. add project folder <path to llvm> in atom
5. See that llvm/tools/clang is greyed out
6. ctrl + p (open fuzzy finder), search "driver.cpp"
7. See no file found
8. Open preferences, disable "Exclude VCS Ignored Paths"
9. See llvm/tools/clang still greyed out
10. ctrl + p (open fuzzy finder), search "driver.cpp"
11. See that llvm/tools/clang/tools/driver/driver.cpp is found

(Sorry for the choice of llvm/clang, I realize they're big repos but they're also a concrete example)

**Expected behavior:** 
The nested repo should not be greyed out nor missing from fuzzy finder when "Exclude VCS Ignored Paths" is on, only its .gitignore should be applied.

**Actual behavior:**
The nested repo remains greyed out no matter what, but if the option is disabled then the files are available in the fuzzy finder.

**Reproduces how often:** 
100%.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

`atom --version`
```Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

`apm --version`
```apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.7.4
```

OS
```Ubuntu 16.04.2 LTS
Linux 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 GNU/Linux
```

### Additional Information
Any additional information, configuration or data that might be necessary to reproduce the issue.
I'm not sure what else is needed, will provide when asked though.

**Comment by rsese** [comment]
> The nested repo should not be greyed out nor missing from fuzzy finder when "Exclude VCS Ignored Paths" is on, only its .gitignore should be applied.

Do you think the fuzzy finder behavior you expect is already covered in https://github.com/atom/fuzzy-finder/issues/55?

**Comment by rsese** [comment]
Ahhhh ok thanks for lettings us know what the issue was in this case - I wasn't able to clone those repos so didn't check the .gitignore myself so didn't see that either.
