### ISSUE TITLE
Crash on closing a network file

### ISSUE THREAD

**Issue by yogamurthy** [atom/atom#14760]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Atom app crashed when i saved the file in a network and then close the file. Tried this on Six(6) different network paths and all of them have the same effect.

### Steps to Reproduce

1. Open atom app and create a new file.
2. Type something in the file and save it in a network path
3. Close the file by clicking the middle button of the mouse on top of the file name 
4. App crashed

**Expected behavior:** Close the file without crashing

**Actual behavior:** Atom app crashed

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
Windows 10

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* Did this behavior just start recently (e.g. after updating to 1.17.2)?
* It looks like the checkbox in the Prerequisites section of the issue template isn't checked - can you reproduce the error in safe mode (`atom --safe`)?
* Can you share any crash logs that you find (http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs)?
