### ISSUE TITLE
Bottom dock focus issue

### ISSUE THREAD

**Issue by Positive07** [atom/atom#14762]
### Prerequisites

* Reproduced the problem in Safe Mode
* Followed all applicable steps in the debugging guide
* Checked the FAQs on the message board for common solutions
* Checked that the issue isn't already filed (This was actually posted as a comment in #14439)
* Checked that there is not already an Atom package that provides the described functionality

### Description
There is a series of problem with focus on the bottom dock.

### Steps to Reproduce

1. Install a package that belongs to the bottom dock (to explain all the different problems I'll use [atom-terminal-tab](https://atom.io/packages/atom-terminal-tab) and [linter-ui-default](https://atom.io/packages/linter-ui-default))
2. Manually open the bottom dog with the Up arrow displayed on hover
3. Type some text. **First issue:** The editor still has focus, I would expect the dock to have focus since I manually opened it.
4. Click the dock to give it focus. Now you can type in the dock
5. Now try to switch to the Linter dock. **Second issue:** The docks closes automatically giving focus back to the editor (Note in order to replicate this issue there should be no linter errors and `Hide Panel When Empty` should be enabled in linter-ui-default configuration)

I experienced more issues before that I can no longer replicate, like for example clicking inside the dock gave focus to the dock but it also closed it, so when you typed the text went to the dock but you couldn't see it. This has been fixed since (maybe in Atom 1.18 beta 3 or in the Terminal package)

The second issue probably belongs to @steelbrain /linter-ui-default so I would like to focus on the first issue since that is a problem with Atom itself.

**Actual behavior:**
![atom-bottom-dock-focus-issue](https://user-images.githubusercontent.com/1095969/27061083-ae6ce58c-4fb7-11e7-8e87-bda9f16f17a9.gif)

**Reproduces how often:**
Always

### Versions
I'm running on Atom 1.18 beta 3 (Windows 10 x64) but have replicated back to Atom 1.17 beta 0 when docks were first introduced.

### Additional Information
```
Atom  1.18.0-beta3
Electron  1.3.15
Chrome  52.0.2743.82
Node  6.5.0
apm  1.18.1
npm  3.10.10
node  6.9.5 x64
python  2.7.13
git  2.13.0.windows.1
visual studio 2015
```

**Comment by rsese** [comment]
Thanks for the report!

> First issue: The editor still has focus, I would expect the dock to have focus since I manually opened it.

I can reproduce this behavior with atom-terminal-tab :+1: 

> Now try to switch to the Linter dock. Second issue: The docks closes automatically giving focus back to the editor

I played with this a bit and found I can only reproduce when when `Settings > Packages > linter-ui-default > Hide Panel When Empty` was enabled and there were no linter messages.  If there is a linter message, then I can't reproduce.   Can you confirm if you see the same behavior?

**Comment by Positive07** [comment]
Yes, that's right, can't replicate without that option or in a non empty list... so it's probably an issue with linter-ui-default.

I would like to focus on the first issue though.

**Comment by steelbrain** [comment]
Latest update of linter-ui-default disables `hidePanelWhenEmpty` by default btw as hotfix

**Comment by rsese** [comment]
> Yes, that's right, can't replicate without that option or in a non empty list... so it's probably an issue with linter-ui-default.

Thanks for confirming, looks like this behavior will change /cc https://github.com/steelbrain/linter/issues/1488.

> I would like to focus on the first issue though.

:+1: - with your example of a terminal package as a dock, it makes sense to me too, I personally think that the terminal dock would have focus if I open it and I can start typing there.  Curious what  you think about more informational docks like linter for example?  Would you still want a dock like that to get focus if you manually opened it?

**Comment by rsese** [comment]
> Latest update of linter-ui-default disables hidePanelWhenEmpty by default btw as hotfix

Woops, issue didn't live update for me, thanks for mentioning @steelbrain :bow:

**Comment by Positive07** [comment]
> Curious what you think about more informational docks like linter for example? Would you still want a dock like that to get focus if you manually opened it?

To me, it doesn't matter, I'm fine with them being focused... But maybe it should be defined by the package, say information-only packages would specify that they aren't focusable and so Atom would not give them focus, while other packages can specify that they need focus so Atom will give them focus automatically.

How this would be done, I don't know. But at least as a feature it should be available.

Also thanks for the hotfix @steelbrain but as I commented in the issue... It still persists
