### ISSUE TITLE
Add key binding for unbound commands is difficult

### ISSUE THREAD

**Issue by Haacked** [atom/atom#14778]
Today I wanted to add a key binding for the "Toggle Soft Wrap" command. It was unclear to me how I'd do that.

I went to `Settings` > `Keybindings` but it only shows bindings for commands that are already bound.
I tried `CTRL+.` (`CMD+,` on Mac) which shows bindings for shortcuts invoked. I hoped maybe it'd show me the potential binding if I invoked the `Toggle Soft Wrap` menu. No luck.

So of course, I go to Google and @maxbrunsfeld answered [the question here](https://github.com/atom/atom/issues/5962).

```
'atom-text-editor':
  'f10': 'editor:toggle-soft-wrap'
```

That's great, but I can't rely on Max having answered that question for every binding I may want to set.

Would be nice to have `Keybindings` show unbound commands too (perhaps in a separate tab or at the end of the list). Or have it allow you to search. Or perhaps have a way to invoke a tooltip on menu items  that show you the name of the item for key binding. Many ways to address the problem.

**Comment by rsese** [comment]
Looks like we have an existing similar request here:

https://github.com/atom/settings-view/issues/165

I'll go ahead and close as a dupe but let me know if I mis-understood anything @Haacked :bow:
