### ISSUE TITLE
Entire IDE window flickers uncontrollably, can't use Atom on this machine

### ISSUE THREAD

**Issue by Tectract** [atom/atom#14776]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Upon starting the IDE, it flickers uncontrollably, at a high framerate. 

### Steps to Reproduce

atom . (in any folder)

**Expected behavior:** [What you expect to happen]

(normal IDE behavior with no flickering)

**Actual behavior:** [What actually happens]

Uncontrollably flickering of the entire app window.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every single time.

### Versions
atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.6
git 1.9.1

Linux Mint 17, qiana (ubuntu 14.04 base kernel)

### Additional Information

Here's my notes, so far... Please help stop the flicker?

(NOTES BELOW) 

I'm hoping someone here might be able to point me towards a resolution for a flicker issue with qt on desktop linux mint 17 machine running in dual monitor mode. I'm not sure if ALL QT apps are flickering uncontrollably, or just some. Specifically, if I start "zoom", a video chat app, another QT flickering app, I see such things as this: 

   If I do:
        export QSG_INFO=1
        zoom

I see:

Linux Client Version is 2.0.91373.0502
QSG_RENDER_LOOP is
Graphics Card Info:: 01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cypress PRO [Radeon HD 5850]
Zoom package arch is 64bit, runing OS arch is x86_64
AppIconMgr::systemDesktopName log Desktop Name: default
qt.scenegraph.general: threaded render loop
qt.scenegraph.general: Using sg animation driver
qt.scenegraph.general: Animation Driver: using vsync: 16.95 ms
qt.scenegraph.general: Animation Driver: using vsync: 16.95 ms
qt.scenegraph.general: texture atlas dimensions: 1024x512
qt.scenegraph.general: R/G/B/A Buffers:    8 8 8 8
qt.scenegraph.general: Depth Buffer:       24
qt.scenegraph.general: Stencil Buffer:     8
qt.scenegraph.general: Samples:            -1
qt.scenegraph.general: GL_VENDOR:          ATI Technologies Inc.
qt.scenegraph.general: GL_RENDERER:        AMD Radeon HD 5800 Series
qt.scenegraph.general: GL_VERSION:         4.3.12798 Compatibility Profile Context 13.35.1005
qt.scenegraph.general: GL_EXTENSIONS:  GL_EXT_timer_query GL_ARB_get_program_binary GL_ARB_color_buffer_float GL_ARB_vertex_shader GL_ARB_shader_image_size GL_ARB_texture_buffer_object GL_ARB_viewport_array GL_EXT_pixel_buffer_object GL_SGIS_generate_mipmap GL_ARB_texture_float GL_EXT_texture_edge_clamp GL_AMD_vertex_shader_tessellator GL_ARB_copy_image GL_EXT_geometry_shader4 GL_EXT_draw_range_elements GL_EXT_gpu_program_parameters GL_ARB_explicit_attrib_location GL_ARB_compatibility GL_ARB_occlusion_query GL_EXT_draw_instanced GL_EXT_framebuffer_object GL_ARB_seamless_cube_map GL_ARB_point_sprite GL_IBM_texture_mirrored_repeat GL_ARB_point_parameters GL_ARB_shader_subroutine GL_ARB_draw_buffers GL_ARB_multi_bind GL_EXT_transform_feedback GL_ARB_base_instance GL_ARB_ES2_compatibility GL_ARB_window_pos GL_ARB_separate_shader_objects GL_EXT_point_parameters GL_EXT_texture_storage GL_ARB_shading_language_420pack GL_ARB_shader_precision GL_EXT_texture_env_dot3 GL_EXT_blend_color GL_EXT_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_arrays_of_arrays GL_EXT_texture_rectangle GL_ARB_texture_border_clamp GL_ARB_shader_bit_encoding GL_ATI_fragment_shader GL_EXT_texture3D GL_NV_primitive_restart GL_AMD_debug_output GL_ATI_texture_mirror_once GL_ARB_fragment_program_shadow GL_ARB_shading_language_100 GL_ARB_provoking_vertex GL_ARB_stencil_texturing GL_ARB_texture_storage GL_ARB_vertex_array_object GL_ARB_seamless_cubemap_per_texture GL_ARB_texture_query_levels GL_EXT_packed_pixels GL_ARB_texture_env_dot3 GL_ARB_shadow_ambient GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_clear_buffer_object GL_ARB_shader_texture_lod GL_EXT_direct_state_access GL_ARB_shader_objects GL_ATI_envmap_bumpmap GL_EXT_texture_env_combine GL_NV_float_buffer GL_ARB_explicit_uniform_location GL_EXT_multi_draw_arrays GL_ARB_clear_texture GL_ARB_gpu_shader5 GL_AMD_name_gen_delete GL_ARB_pixel_buffer_object GL_ARB_texture_rgb10_a2ui GL_EXT_provoking_vertex GL_ARB_program_interface_query GL_ARB_invalidate_subdata GL_EXT_copy_buffer GL_EXT_blend_equation_separate GL_ARB_imaging GL_EXT_blend_subtract GL_EXT_packed_depth_stencil GL_AMD_multi_draw_indirect GL_EXT_copy_texture GL_EXT_texture_filter_anisotropic GL_EXT_framebuffer_blit GL_EXT_fog_coord GL_ARB_fragment_coord_conventions GL_ARB_shader_storage_buffer_object GL_ARB_sample_shading GL_ARB_geometry_shader4 GL_NV_depth_buffer_float GL_EXT_rescale_normal GL_ARB_texture_compression_rgtc GL_EXT_texture_integer GL_KHR_debug GL_EXT_vertex_attrib_64bit GL_ARB_texture_non_power_of_two GL_ARB_query_buffer_object GL_NV_half_float GL_EXT_compiled_vertex_array GL_NV_copy_image GL_ARB_texture_query_lod GL_ARB_texture_env_combine GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_view GL_EXT_texture_compression_s3tc GL_EXT_shadow_funcs GL_ARB_internalformat_query2 GL_AMD_vertex_shader_layer GL_ARB_blend_func_extended GL_ARB_shader_image_load_store GL_EXT_abgr GL_NV_conditional_render GL_ARB_shader_atomic_counters GL_EXT_texture_lod GL_EXT_packed_float GL_ARB_depth_clamp GL_EXT_separate_specular_color GL_ARB_framebuffer_object GL_AMD_pinned_memory GL_ARB_tessellation_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_AMD_depth_clamp_separate GL_ARB_vertex_attrib_64bit GL_ARB_multisample GL_ARB_shadow GL_ARB_half_float_pixel GL_EXT_texture_shared_exponent GL_SGIS_texture_lod GL_ARB_fragment_program GL_AMD_draw_buffers_blend GL_AMD_transform_feedback3_lines_triangles GL_ARB_draw_instanced GL_ARB_gpu_shader_fp64 GL_AMD_texture_texture4 GL_ATI_draw_buffers GL_ARB_framebuffer_no_attachments GL_ATI_texture_float GL_ARB_texture_gather GL_EXT_histogram GL_AMD_conservative_depth GL_NV_copy_depth_to_color GL_NV_texture_barrier GL_AMD_seamless_cubemap_per_texture GL_ARB_multitexture GL_ARB_map_buffer_alignment GL_AMD_query_buffer_object GL_EXT_bindable_uniform GL_ARB_shading_language_packing GL_NV_blend_square GL_ARB_fragment_shader GL_ARB_texture_snorm GL_ARB_depth_buffer_float GL_EXT_texture_buffer_object GL_EXT_stencil_wrap GL_ARB_shader_stencil_export GL_SGIS_texture_edge_clamp GL_ARB_sync GL_ARB_texture_multisample GL_ARB_internalformat_query GL_AMD_vertex_shader_viewport_index GL_ARB_texture_buffer_range GL_AMD_shader_stencil_export GL_ARB_texture_storage_multisample GL_AMDX_debug_output GL_ATI_meminfo GL_WIN_swap_hint GL_ARB_texture_env_add GL_ARB_framebuffer_sRGB GL_AMDX_vertex_shader_tessellator GL_EXT_framebuffer_sRGB GL_EXT_secondary_color GL_EXT_texture_lod_bias GL_EXT_framebuffer_multisample GL_ATI_separate_stencil GL_EXT_blend_func_separate GL_ARB_debug_output GL_EXT_blend_minmax GL_EXT_shader_image_load_store GL_ARB_texture_rg GL_ARB_transform_feedback3 GL_EXT_texture_env_add GL_ARB_ES3_compatibility GL_EXT_texture_snorm GL_ARB_texture_env_crossbar GL_AMD_shader_trace GL_ARB_uniform_buffer_object GL_EXT_texture_array GL_ARB_vertex_buffer_object GL_ARB_compressed_texture_pixel_storage GL_ARB_transform_feedback2 GL_EXT_vertex_array GL_ARB_vertex_attrib_binding GL_EXT_bgra GL_EXT_gpu_shader4 GL_EXT_texture_swizzle GL_NV_texgen_reflection GL_ARB_compute_shader GL_EXT_texture_compression_rgtc GL_EXT_texture_sRGB_decode GL_EXT_subtexture GL_KTX_buffer_region GL_EXT_draw_buffers2 GL_ARB_transpose_matrix GL_EXT_texture_compression_bptc GL_ARB_texture_rectangle GL_EXT_shader_integer_mix GL_ATI_texture_compression_3dc GL_EXT_texgen_reflection GL_ATI_texture_env_combine3 GL_ARB_texture_mirrored_repeat GL_AMD_performance_monitor GL_ARB_vertex_array_bgra GL_NV_explicit_multisample GL_ARB_depth_texture GL_ARB_multi_draw_indirect GL_EXT_texture_compression_latc GL_ARB_texture_cube_map GL_ARB_texture_mirror_clamp_to_edge GL_ARB_instanced_arrays GL_ARB_sampler_objects GL_ARB_timer_query GL_ARB_map_buffer_range GL_ARB_draw_buffers_blend GL_ARB_copy_buffer GL_ARB_conservative_depth GL_EXT_texture_mirror_clamp GL_ARB_texture_swizzle GL_ARB_half_float_vertex GL_ARB_draw_elements_base_vertex GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_fragment_layer_viewport GL_ARB_draw_indirect GL_AMD_sample_positions GL_ARB_transform_feedback_instanced GL_ARB_vertex_program GL_EXT_vertex_array_bgra GL_ARB_occlusion_query2 GL_AMD_texture_cube_map_array GL_SUN_multi_draw_arrays GL_EXT_texture_object GL_EXT_texture_sRGB
qt.scenegraph.general: Max Texture Size:  16384
qt.scenegraph.general: Debug context:     false
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument

   At this point the screen draws the app, but it is filled with black, or it is filled with the image that was already on the screen before the app was drawn. If I move my mouse over the app, or move it around on the screen, it flickers, and I can momentarily see the app, during the half-flicker states, lol.

   I've tried some things to remedy this, to no avail, such as:

(updating to newest version of QT)
export QT_SELECT=5
qmake -v
   QMake version 3.0
   Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu

export QT_OPENGL=angle
export QT_ANGLE_PLATFORM=d3d9
export QT_OPENGL=software
export LIBGL_ALWAYS_SOFTWARE=1
export QSG_RENDER_LOOP=basic
export FB_MULTI_BUFFER=2
export FB_MULTI_BUFFER=3
(installing / updating dependencies listed for ubuntu os via apt-get)
(gleaned info from here but nothing useful so far: [url]http://blog.qt.io/blog/2017/01/18/opengl-implementation-qt-quick-app-using-today/[/url])

I noticed my two monitors have two different refresh rates, changing them to both be at 60hz seemed to make no difference...

Any other ideas on how to troubleshoot this?

**Comment by 50Wliu** [comment]
You're using an outdated Atom version; the latest version is Atom 1.17.2.  The Zoom flickering is probably a different issue, considering that Atom is not built on Qt.  If the flickering is still an issue on the latest Atom version, I'll be glad to reopen this issue.

**Comment by Tectract** [comment]
This is the latest version of atom in the 14.04 repos.

**Comment by 50Wliu** [comment]
Then please update by downloading and installing the latest `.deb` package from https://atom.io: the versions in Linux software repositories are not maintained by the Atom team and we cannot guarantee that they will work as expected.

**Comment by Tectract** [comment]
Newest version installed. Issue remains :'(

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by Tectract** [comment]
What window-maker system does Atom use, may I ask? That might help debugging this issue. It appears to also occur on QT apps, not sure if all of them, need to do more testing....

**Comment by 50Wliu** [comment]
I'm not sure, to tell you the truth :/.  Can you try the following command-line options to see if one of them fixes your issue?
* `atom --safe --disable-gpu`
* `atom --safe --enable-gpu-rasterization --force-gpu-rasterization`

**Comment by Tectract** [comment]
--disable-gpu

Did the trick to stop the flicker for me. Thank you :)

**Comment by 50Wliu** [comment]
Awesome!  And does flickering also occur with Chromium/Chrome?

**Comment by Tectract** [comment]
Nope. In Chrome I have disabled "Use hardware rendering where available"
on this machine, and then overridden a gpu-blacklist to re-enable webGL :)

R

**Comment by 50Wliu** [comment]
So this is sounding like an upstream Chromium or GPU bug.  If you temporarily enable hardware acceleration in Chrome, does the flickering return?

**Comment by Tectract** [comment]
It's apparently an issue with this old ATI card I have running in dual-monitor mode, but there's no driver update I can apply on this OS. I'm actually still having the flicker issue with at least one QT app, and trying to learn if there's a way to completely disable GPU rendering in QT, but it's difficult. I believe I was having some flicker issues in Chrome before I disabled GPU rendering under this setup, but, strangely, webGL still works fine as long as I exclude the card from the chrome GPU blacklist.

But this card is the best card ever for vanity mining bitcoin private keys... lol. I might just have to replace it and mess with new GPU drivers this weekend.

**Comment by 50Wliu** [comment]
:+1:.  Since it doesn't seem like Atom is doing anything wrong here, I'm going to close this issue.

**Comment by Tectract** [comment]
My suggestion here is to list the commands

    atom --safe --disable-gpu
    atom --safe --enable-gpu-rasterization --force-gpu-rasterization

In the documentation some, possibly mention GPU/flicker issues and these commands as a workaround. 

Cheers~

**Comment by 50Wliu** [comment]
That sounds like a good idea.  Could you create an issue on [atom/flight-manual.atom.io](https://github.com/atom/flight-manual.atom.io) suggesting for the first command to be added to http://flight-manual.atom.io/hacking-atom/sections/debugging/? (I specify only the first because I don't think we've actually solved any issues with the second set yet...)
