### ISSUE TITLE
GitHub package doesn't load environment variables on commit

### ISSUE THREAD

**Issue by piuccio** [atom/atom#14798]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I've just updated Atom and tried to commit from the new GitHub/Git package but I get the error

```
Error: Failed to replace env in config: ${BINTRAY_TOKEN}
    at /usr/local/lib/node_modules/npm/lib/config/core.js:418:13
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at envReplace (/usr/local/lib/node_modules/npm/lib/config/core.js:414:12)
    at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:392:7)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:335:17
    at Array.forEach (native)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:334:23)
    at ConfigChain.addString (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf. (/usr/local/lib/node_modules/npm/lib/config/core.js:322:10)

/usr/local/lib/node_modules/npm/lib/npm.js:45
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/local/lib/node_modules/npm/lib/npm.js:45:13)
    at exit (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:74:40)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:194:3)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at processEmit [as emit] (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:155:32)
    at process._fatalException (bootstrap_node.js:304:26)
pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint:staged`
pre-commit: hook returned an exit code (7). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
```

I have the following `.npmrc` in my project

```
@private-stuff:registry=https://api.bintray.com/npm/private-repository/
//api.bintray.com/npm/private-repository/:_authToken=${BINTRAY_TOKEN}
//api.bintray.com/npm/private-repository/:username=${BINTRAY_USER}
//api.bintray.com/npm/private-repository/:email=${BINTRAY_EMAIL}
//api.bintray.com/npm/private-repository/:always-auth=true
```

The environment variables are defined in my `~/.bash_profile`

```
export BINTRAY_TOKEN=abc
# ...
```

It works fine from both the command line `git commit -m` and the `git gui`

I also have a pre-commit hook installed through [pre-commit](https://www.npmjs.com/package/pre-commit) and using [lint-staged](https://www.npmjs.com/package/lint-staged) to run eslint, but I'm not sure that's the problem

### Steps to Reproduce

1. Create an `.npmrc` file with a configuration variable
2. export the variable
3. try to commit

**Expected behavior:** You can create a commit

**Actual behavior:** Get the error

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.0

Using masOS Sierra 10.12.4

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/github](https://github.com/atom/github) repository.  Thanks!
