### ISSUE TITLE
Can't switch CRLF on Windows

### ISSUE THREAD

**Issue by torn4dom4n** [atom/atom#14791]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I switch `LF` into `CRLF`, atom still show `File uses LF (Unix) line endings`.

![image](https://user-images.githubusercontent.com/27698189/27200671-e51c1348-5244-11e7-8db6-ed5679fa5724.png)

### Versions

OS: Windows 10 Creator Update
Atom 1.19-beta-0

**Comment by maxbrunsfeld** [comment]
Is it changing the line endings and the indicator is just wrong, or is failing to change the line endings?

**Comment by maxbrunsfeld** [comment]
I just tried reproducing this on my windows VM, but I can't.

@ungb @rsese Are you seeing this on Atom 1.19 beta?

**Comment by torn4dom4n** [comment]
@maxbrunsfeld This is my screenshot after I run the `Window: Toggle Invisibles`:
![image](https://user-images.githubusercontent.com/27698189/27202251-0769185a-524b-11e7-954b-db559617f88d.png)

**Comment by maxbrunsfeld** [comment]
Ok, so it looks like the button is doing the right thing, but the tooltip is displaying the wrong text. I can reproduce something similar. Thanks for the screenshots; I wasn't paying attention to the tooltip on my machine.

**Comment by maxbrunsfeld** [comment]
Fixing now.

**Comment by rsese** [comment]
So fast, was installing the beta on Windows but you already found the bug 🚗 💨

**Comment by maxbrunsfeld** [comment]
This bug was introduced in https://github.com/atom/atom/issues/14791

**Comment by maxbrunsfeld** [comment]
@torn4dom4n The fix will go out in Atom v1.19.0-beta1 and v1.18.1. I'm not sure when we're going to publish those, but in the meantime, know that the tooltip is just wrong; the line endings actually are being converted.
