### ISSUE TITLE
macOS custom titlebar does not hide titlebar when reloading editor in fullscreen mode

### ISSUE THREAD

**Issue by preco21** [atom/atom#14799]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hello all!

I just noticed weird behavior of Atom that it does not hide its titlebar when reloading editor in fullscreen mode on `macOS`.

Here are the captured screenshots where in safe mode:

When not in full screen mode:
![image](https://user-images.githubusercontent.com/4936201/27217319-58e116ce-52b4-11e7-9ae8-c8cfe850e02c.png)

When in full screen mode:
![image](https://user-images.githubusercontent.com/4936201/27217324-5dc3373a-52b4-11e7-94a9-bc0a4aab9bce.png)

When in full screen mode after reloading right after previous step:
![image](https://user-images.githubusercontent.com/4936201/27217327-6073889a-52b4-11e7-91c6-15dccc987f2d.png)

### Steps to Reproduce

0. Prepare `macOS` environment. 🤑 
1. Open Atom.
2. Go to `Settings` and change `Title Bar` option to `custom` or `custom-inset` from `Core` setting.
3. Toggle fullscreen by `ctrl` + `cmd` + `f`.
4. Reload editor by `ctrl` + `alt` + `cmd` + `l`.
5. Hang tight until editor titlebar show up

**Expected behavior:** Titlebar hidden when reloading editor.

**Actual behavior:** Titlebar keep showing even in fullscreen mode.

**Reproduces how often:** Every time you follow above steps.

### Versions

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

`macOS Sierra 10.12.5`

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce with your steps on macOS 10.12.5 and Atom 1.18.0.

**Comment by rsese** [comment]
Not sure if this is more an Electron issue but tagging as a bug for now.

**Comment by sadick254** [comment]
This has now been resolved on the latest atom. `v1.50.0`. Am not able to reproduce the bug. Am happy to reopen this if it is still reproducible.
