### ISSUE TITLE
Having undo buffer outside of window session.

### ISSUE THREAD

**Issue by jonrohan** [atom/atom#148]
Sometimes I'll `command-R` the editor, then I realize I loose all my `command-Z` powers. It would be excellent if we serialized the undo buffer so that when the editor is reloaded, I don't loose my undo.

**Comment by maxbrunsfeld** [comment]
This has been 'implemented' for a long time, but it doesn't actually work; because the undo-stack is accidentally cleared when the buffer is reloaded from disk. I'm sorry this has stayed open for so long; I'm prioritizing it.
