### ISSUE TITLE
Windows context menu links don't get updated after atom update.

### ISSUE THREAD

**Issue by konstantin-popov** [atom/atom#14805]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After atom update settings in "System Settings" on Windows seem to be reset to default values. It makes the context menu links (right-click menu on file/folder, "Open with Atom") opens previous version of Atom. The menu elements get "updated" only by re-enabling the "Show in file context menu" and "Show in folder context menu".

### Steps to Reproduce

1. Update atom to newer version and restart it.
2. Open another atom window using context menu on any folder.
3. Check atom version in "Help" menu.

**Expected behavior:** Atom reports installed version number.

**Actual behavior:** Atom reports "before update" version number.

**Reproduces how often:** Every time atom get updated (at least 2 latest versions).

### Versions

OS: Windows 7 x64

`atom --version`
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

`apm --version`
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.0.windows.1
visual studio 2015

### Additional Information
-

**Comment by rsese** [comment]
Thanks for the report!  I just updated to 1.18.0 on Windows 10 and couldn't reproduce - the menu was updated and the `Settings > System` values weren't reset (i.e. they remained checked for me).

**Comment by konstantin-popov** [comment]
@rsese, thanks for checking this. I'll try to watch it closer on next update. Is there any additional info I can gather before/during/after update that could help?

**Comment by rsese** [comment]
Hmm, can't think of anything in particular - maybe just the basics e.g. note again the exact steps and behavior that you see.  A screencast or GIF of what you see could also be interesting.

**Comment by damieng** [comment]
You'll need to launch the 'new' atom just once and then it can update the shell links for you.

This normally happens when Atom restarts after updating.

Not sure why your system still has the old version of Atom installed.

**Comment by konstantin-popov** [comment]
Looks like the problem was in that all atom preferences for some reason were reset to default values with that update. Anyway, 1.19.0 update went perfecly, so the issue is not relevant I guess.
