### ISSUE TITLE
Still freezing on long lines / minified JS files

### ISSUE THREAD

**Issue by BlaM** [atom/atom#14802]
Issue #979 may have been closed, but while it has been getting better with the enforced linebreak I still often get locked up windows when I try to/accidently open minified JS files...

![image](https://user-images.githubusercontent.com/176011/27223042-240e419e-528f-11e7-84ff-5ada255db23b.png)

OS: Windows 8
Atom Version: 1.18.0

Appears in Safe-Mode, so no other addon/package/plugin is causing this.

In safe mode I just ended up with a completely empty window, in my normal editing mode I have a slight chance of closing the tab fast enough before syntax highlighting starts.

**Comment by 50Wliu** [comment]
:wave: Thanks for opening an issue @BlaM.  In the future we would really appreciate it if you could fill out the issue template - that gives us lots of useful information.

I have a few questions for you:
* Does Atom freeze on all minified JS files you've tried, or just a subset?  Can you try with `jquery.min.js` and see if that freezes Atom?
* Does this only happen with minified JS files?  What about minified CSS files, for example?
* Can you elaborate on what you mean by "In safe mode I just ended up with a completely empty window"?

**Comment by BlaM** [comment]
I investigated a little more: Atom does not freeze on all JS files. Actually I found out that it does not even freeze on the same file depending on how I open it.

(The last file that got me frozen was https://media.sivantos.com/includes/js/ote.js)

I was able to open the file directly (manually). However when I opened the "project" which had the file open from last time I edited it the Editor locked up on every attempt (so yes, I was able to reproduce this effect last week). Obviously, because computers like to do that, I can't get it to lock up today - probably just to make me look stupid. 

I haven't seen this on anything else than JS files, yet. I can't say, though, if that's because CSS does not have that problem or if my CSS files are just smaller.

"Empty window" in Safe Mode was just that: When I tried to open the project folder in safe mode the window just showed me the top navigation menu. There I was able to open the submenus, but clicking on any actions did nothing. Aside from that there were absolutely no elements in the window. No footer, no file tree and no handles for those new sidebar popouts.

**Comment by 50Wliu** [comment]
> However when I opened the "project" which had the file open from last time I edited it the Editor locked up on every attempt

It may be that some bad state was cached and Atom is struggling to load the file due to that.

I copy/pasted ote.js into a new tab and set the highlighting to JavaScript and it loaded fairly quickly for me.

Regarding safe mode: that sounds a bit troubling.  Can you try running `atom --safe --foreground` and copy/paste any errors that appear in the console here?

**Comment by BlaM** [comment]
I can't seem to reproduce the problem right now and it does not show any console messages in safe/foreground mode. For now it is working - so maybe there _was_ a bad state and it got fixed when I closed and reopened the file?

I'll need to wait until it happens again. :disappointed_relieved:

**Comment by 50Wliu** [comment]
Hehe, the usual heisenbug.  Do please keep us updated if it occurs again!  We may close this issue after some period of inactivity.

**Comment by BlaM** [comment]
Hasn't happened for a month, so I'll close this.
