### ISSUE TITLE
[1.19.0-beta0] Line gutter takes up horizontal space when hidden

### ISSUE THREAD

**Issue by mshenfield** [atom/atom#14808]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
In Atom 1.19.0-beta0, the line numbers gutter takes up horizontal space even when hidden

<img width="561" alt="screen shot 2017-06-16 at 7 38 48 am" src="https://user-images.githubusercontent.com/4812055/27226939-df871186-5266-11e7-9b3e-365e802dd2c3.png">
<img width="596" alt="screen shot 2017-06-16 at 7 38 34 am" src="https://user-images.githubusercontent.com/4812055/27226940-df8cf808-5266-11e7-8a7f-85168b8198ae.png">

### Steps to Reproduce

1. Open Atom in safe mode
2. Create or open any file
3. Toggle the line numbers gutter using the "Editor: Toggle Line Numbers" command
4. Observe a gutter taking up significant space on the left side when line numbers are toggled off

**Expected behavior:**
The line numbers gutter should be completely hidden when toggled off

**Actual behavior:**
The line numbers gutter remains as an empty div when toggled off

**Reproduces how often:**
100%

### Versions

Atom    : 1.19.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by 50Wliu** [comment]
Correct.  I believe that was intentional so that packages that use the gutter, such as linter, will function correctly even with line numbers disabled.

/cc @nathansobo just to be sure.

**Comment by t9md** [comment]
When you disabled line-number, you still can fold/unfold by clicking fold icon on gutter(try with file which have some fold).
In previous version(v1.18), this was not possible.

So this is **improvement**, I believe this is intentional.

**Comment by nathansobo** [comment]
Yes, this is intentional. A bit of custom CSS could solve your problem if you don't like it.
