### ISSUE TITLE
Can't scroll the editor when the mouse is at the right most edge of the screen

### ISSUE THREAD

**Issue by segevfiner** [atom/atom#14803]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I can't scroll the editor when the mouse is at the right most edge of the screen. Also happens when I close the right docks.

### Steps to Reproduce

1. Open Atom in full screen with a long enough file so that there will be a vertical scroll bar.
2. Move your mouse to the very right most edge of the screen and try to scroll by clicking the scroll bar. It doesn't work.
3. Move it slightly to the left and you can click and scroll.

**Expected behavior:** I can click the scroll bar even when the mouse is at the right most edge of the screen.

**Actual behavior:** I can't scroll. I have to move the mouse slightly to the left.

**Reproduces how often:** Always

### Versions

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.1.windows.2
visual studio 2015
```

Windows 10.0.15063 x64

### Additional Information

![atom-1_18-scroll-bug](https://user-images.githubusercontent.com/24731903/27223712-5ce3f5d0-529a-11e7-8696-a891021d10fd.gif)

**Comment by rsese** [comment]
Thanks for the report!  I was able to reproduce in Windows 10 and macOS 10.12.5 with Atom 1.18.0.  h/t @lee-dohm for finding https://github.com/atom/one-dark-ui/issues/181 which sounds like the same issue.  

It's in the One Dark repo though and I was able to reproduce with multiple UI themes (for One Dark I disabled the dock toggle buttons too) - can you confirm which UI theme you're using @segevfiner and if you can reproduce with multiple UI themes?

**Comment by segevfiner** [comment]
@rsese I'm using `one-dark-ui` It reproduces for me with all 4 built-in UI themes (`one-dark-ui`, `one-light-ui`, `atom-dark-ui`, `atom-light-ui`).

**Comment by lee-dohm** [comment]
Interestingly, this reproduces for me in Chrome also. So this may be a Chromium thing rather than an Atom thing.

**Comment by rsese** [comment]
Hmmm, I wasn't able to reproduce in Chrome on macOS 10.12.5 - do you see the same scrolling problem in Chrome @segevfiner?

**Comment by segevfiner** [comment]
I'm not seeing it with Chrome 59.0.3071.104 on Windows 10.0.15063. I don't have a copy of the same Chrome/Chromium version used by Atom.

**Comment by lee-dohm** [comment]
Turns out that it was a Chrome extension that was causing the problem for me in Chrome.

**Comment by rsese** [comment]
Ahhh gotcha, thanks @lee-dohm - since the issue isn't specific to a particular theme, I'll leave this issue open, tag as a bug, and leave a comment in https://github.com/atom/one-dark-ui/issues/181.  Let me know if you think this belongs somewhere else though @lee-dohm :v:

**Comment by simurai** [comment]
@segevfiner Can you drag the scrollbar if you go to `Settings > Themes > One Light/Dark` and then enable the "Hide docks toggle buttons" option? It should remove the 1px "hover area" for the docks toggle buttons.

![screen shot 2017-04-22 at 11 10 36 am](https://cloud.githubusercontent.com/assets/378023/25300546/83428940-274c-11e7-97f2-4dec0611772e.png)

Not sure what to do for people that want to keep the toggle buttons **AND** want to scroll on the outer edge... 🤔  Currently you have to choose.

**Comment by segevfiner** [comment]
@simurai This does work around the issue for me.

I wonder... Isn't there some magic with float and event bubbling that can be done so that the scroll bar still receives events despite the 1 pixel div?

**Comment by simurai** [comment]
> I wonder... Isn't there some magic with float and event bubbling that can be done so that the scroll bar still receives events despite the 1 pixel div?

Hmm.. yeah, maybe? The `.vertical-scrollbar` element is still touching the edge, with the 1px wide `.atom-dock-inner` element being physically on top. Maybe when pressing on `.atom-dock-inner` it could ignore all events and pass it to the underlying `.vertical-scrollbar`?

/cc @atom/core

**Comment by segevfiner** [comment]
@simurai Then this is probably caused by this ([static/docks.less:41-46](
https://github.com/atom/atom/blob/a73bb7e56c7d784372b92b3c5465ee0681f6e56f/static/docks.less#L41-L46)):
```less
  &:not(.atom-dock-open) {
    // The dock should only take up space when it's active (i.e. it shouldn't
    // take up space when you're dragging something into it).
    position: absolute;
    z-index: 10; // An arbitrary number. Seems high enough. ¯\_(ツ)_/¯
  }
```

I don't think events bubble from absolutely positioned elements to elements in normal flow... I guess this rule is for moving the dock out of normal flow which than makes it sized using shrink-to-fit/content-based sizing, which makes it 1px due to min-width/min-height. I wonder if there is a different way to do this rule... The other option is to manually propagate events using JavaScript.

**Comment by steelstring94** [comment]
Confirmed reproduced, hiding the dock works around for me.

**Comment by steelstring94** [comment]
@simurai What I don't understand here is, for this dock toggle button - it's on the left side of the screen.  The scrollbar is on the right.  Why would the toggle button affect the scrollbar?

**Comment by segevfiner** [comment]
@steelstring94 You can also place docks on the right side too. And the 1-pixel div there seems to exist even if you don't have any docks, but have them enabled. I think the div serves as a hover area for showing the dock buttons. It really should propagate events somehow so as not to cause this though. See https://github.com/atom/atom/issues/14803#issuecomment-310270264.

**Comment by steelstring94** [comment]
Confirming that going into the DOM and deleting the right dock also fixes this.

**Comment by steelstring94** [comment]
Adding the following to your styles.less will workaround this bug without getting rid of the button to open the left dock:

`.atom-dock-inner {
  &.right {
    display: none;
  }
}`

**Comment by segevfiner** [comment]
> Adding the following to your styles.less will workaround this bug without getting rid of the button to open the left dock:
> 
> .atom-dock-inner { &.right { display: none; } }

That will of course disable the right docks area. Note that it is currently used by default by the core GitHub package.

**Comment by steelstring94** [comment]
Using this will still let you open the dock, but you won't be able to do it with the pop-up button, you'll have to use a keyboard combo or something: `.atom-dock-inner {
 &.right {
   &:not(.atom-dock-open) {
   display: none;
    }
  }
}
`

**Comment by Khangeldy** [comment]
Same problem on my atom (Arch linux/gnome) present.  So there 2 solutions for me first - install minimap package and second is -  change  tree-view pac to right on screen. But i didn't find on setting of tree-view, so maybe they  deleted this feature.

**Comment by Zireael07** [comment]
The tree view setting is gone because now you can just drag the tree view over :)

**Comment by ricpelo** [comment]
I have the same issue. Is there a workaround, please? Thanks!

**Comment by vlad1777d** [comment]
I have this too. Didn't find this one and created duplicate.

Why do I consider this important:
for 2 matters: 1. Not to force users aiming on Atom's narrow scrollbar; 2. To be consistent with the majority of applications providing such action.

In other software you don't need to aim onto scrollbar, you can just move cursor to right edge of screen and drag it. For example, in Firefox, Xed, Gedit, Gnome-Terminal, Chromium, etc.

Video with reproducing the issue on YouTube and commentaries in subtitles (please, turn on them): https://youtu.be/GLXMQFgKJOA
Same video, but in .mkv format: [atom_suggestion-2017-12-16_20.37.09 (1).mkv.zip](https://github.com/atom/atom/files/1566103/atom_suggestion-2017-12-16_20.37.09.1.mkv.zip)

**Comment by simurai** [comment]
## ⛑  Workarounds ⛑

@ricpelo A workaround is to remove the right "dock hover affordance". As noted in the above comment https://github.com/atom/atom/issues/14803#issuecomment-317113760, paste the following in your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file:

```less
// Hide right dock when not open
.atom-dock-inner { &.right { &:not(.atom-dock-open) { display: none; } } }
```

Downside: You then need to use keyboard shortcuts to open the dock. Or for example the Git panel has a "changed files" button in the status bar at the right that can be clicked.

---

Another option if you use the One dark/light UI themes and don't need the "dock toggle buttons", you can disable them in the theme settings: https://github.com/atom/atom/issues/14803#issuecomment-310060058
