### ISSUE TITLE
Rename "Github: Push" to "Git: Push"

### ISSUE THREAD

**Issue by epelc** [atom/atom#14812]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

![image](https://user-images.githubusercontent.com/5204642/27238955-f5196cc0-529c-11e7-8a06-4740472827c2.png)
The `Github: Push` command is really just pushing via git(it works if your remote is hosted elsewhere). I'd recommend renaming this and the force push command to avoid confusion between git and GitHub.

**Expected behavior:** [What you expect to happen]
Git: Push

**Actual behavior:** [What actually happens]
GitHub: Push

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Atom 1.18 and 1.19beta0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by maxbrunsfeld** [comment]
Could you reopen this issue on https://github.com/atom/github?

**Comment by epelc** [comment]
https://github.com/atom/github/issues/945
