### ISSUE TITLE
git.exe consuming lots of memory and putting cursor in indefinite progress state.

### ISSUE THREAD

**Issue by hemant1612** [atom/atom#14814]
Hi,

I recently installed atom after uninstalling it on windows 10 , as earlier it was running a process called `git for windows` which was consuming a lot of memory .Now when I try to open atom  ,I am getting this error:

![atom_error](https://user-images.githubusercontent.com/20846397/27243573-347ccb24-5300-11e7-83c4-9d4878028e24.jpg)

OK .Somehow I get rid of this but now:

When I open atom there's a process in Task manager which is creating all the gotchas.It starts seconds after starting atom.This is located at : C:\Users\...\AppData\Local\atom\app-1.18.0\resources\app\node_modules\dugite\git\mingw64\bin\git.exe. 
This process consumes lots of memory & causes cursor to be in progress state indefinitely,

![prob](https://user-images.githubusercontent.com/20846397/27247094-807f1abe-5313-11e7-990f-70b3e94e7099.jpeg)

I am not sure why this started all of a sudden .Is this a default process?

**TEMP. SOLUTION**:
I ended the task from task manager .
Closed atom .
Deleted git.exe file.
And now I am not facing this problem, atleast .

**Comment by rsese** [comment]
Thanks for the report!  Do you see the same error in safe mode (`atom --safe`)?

---

Also, for future issues, please completely fill out the issue template - we require this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/14814#issuecomment-309149057. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
