### ISSUE TITLE
[v1.19-beta] Cannot scroll manually created editor

### ISSUE THREAD

**Issue by t9md** [atom/atom#14811]
In this gif, editor have 100 line from 1 to 100 text in each line, but not scrollable by mouse or `ctrl-p`, `ctrl-n`.

![scroll-issue](https://user-images.githubusercontent.com/155205/27237721-4358411e-5305-11e7-905a-257383d01943.gif)

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Cannot scroll manually created editor(by `new TextEditor()`.
- In v1.18: scrollable by mouse(trackpad) and normal motion command(`core:move-down`)
- In v1.19-beta: cannot scroll by mouse nor normal motion command(`core:move-down`)

### Steps to Reproduce

1. launch atom in safe mode.
2. Open dev-console and paste code below, it create editor and put 100 lines text.

```javascript
(function reproduceIssue() {
  const {TextEditor} = require("atom")
  editor = new TextEditor()

  // this is also not work
  // editor = atom.workspace.buildTextEditor()

  const lines = []
  for (let i = 1; i < 100; i++) {
    lines.push(i)
  }
  atom.workspace.open(editor)
  editor.setText(lines.join("\n"))
}())
```

3. see you can not scroll by mouse, and also `ctrl-n`(`core:move-down`).

- v1.18: have no problem with same reproduction steps.
- v1.19: have issue, it might be regression by rendering logic rewrite.

### Versions

macOS
```
ProductName:	Mac OS X
ProductVersion:	10.12.5
```

Atom
```
Atom    : 1.19.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

My [atom-narrow](https://atom.io/packages/narrow) affected by this issue.

**Comment by maxbrunsfeld** [comment]
I can reproduce this on master. It's probably related to the editor rewrite.

/cc @as-cii @nathansobo

**Comment by t9md** [comment]
Wow, quick! thanks for checking this!

**Comment by t9md** [comment]
When issue happened `atom.workspace.getActiveTextEditor().getLastVisibleScreenRow()` return final screen row of buffer(it's actually not visible), this is why scroll not happens.
`this.measurements.clientContainerHeight` holding last rows pixel of buffer(which is not actually visible).

**Comment by as-cii** [comment]
@t9md: thanks for the report, and apologies for this issue! Can you describe what happens when trying to create the `TextEditor` instance with `{autoHeight: false}`? e.g.

```js
(function reproduceIssue() {
  const {TextEditor} = require("atom")
  editor = new TextEditor({autoHeight: false})

  // this is also not work
  // editor = atom.workspace.buildTextEditor()

  const lines = []
  for (let i = 1; i < 100; i++) {
    lines.push(i)
  }
  atom.workspace.open(editor)
  editor.setText(lines.join("\n"))
}())
```

During the editor rewrite we switched to turning `autoHeight` on by default under the assumption the most text editors would not be used as *buffers*. This makes the editor automatically adjust to the height of the content and, as a result, disables scrolling as well.

**Comment by t9md** [comment]
> @t9md: thanks for the report, and apologies for this issue! Can you describe what happens when trying to create the TextEditor instance with {autoHeight: false}? e.g.

Thanks.
Adding `{autoHeight: false}` option solve issue, now scrollable.

So for now, my understanding for this issue is not bug, just a breaking change of default value.
So plugin author who want to use text-editor as buffer(changing content and need scroll), pass `autoHeight: false` at initialization.

If this my understanding is no problem, feel free to close this issue.

**Comment by t9md** [comment]
Summary: This is not bug. this is default behavior change in v1.19.0. Can recover previous behavior by explicitly passing option to the constructor like `new TextEditor({autoHeight: false})`.
