### ISSUE TITLE
Duplicate icons when pinning in taskbar - Windows 10

### ISSUE THREAD

**Issue by garygreen** [atom/atom#14813]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Duplicates the icon when pinned on taskbar in windows 10.

### Steps to Reproduce

1. Open atom
2. Right click on atom in taskbar > Pin to taskbar
3. See the duplicated icon.

**Expected behavior:**

Pin the taskbar icon without creating a duplicate.

**Actual behavior:**

Duplicates taskbar item.

**Reproduces how often:**

100%, everytime. Although doesn't seem to happen on my machine at home.

### Versions

apm  1.17.0
npm  3.10.5
node 6.9.5 ia32
python 2.7.12
git 1.9.5.msysgit.1
visual studio

Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

Windows 10.

### Additional Information

![27232686-dc7afaa0-52ae-11e7-8a61-070c361b59a7](https://user-images.githubusercontent.com/1702638/27241627-82e9e280-52d1-11e7-99a9-c56f749a8947.gif)

**Comment by dfreese** [comment]
I am seeing the same behavior on Windows 10 Enterprise 2015 LTSB and Atom 1.18.0 x64.

**Comment by jusder** [comment]
I am also seeing the same behavior on exactly the same software are dfreese: Win10 Enterprise/Atom 1.18.0 x64

**Comment by Daijobou** [comment]
Is that not a issue from a issue? You should start with the first issue. For me the first issue here is that a second icon appeared from a already pinned icon. Like your animation, all other programs use exists icon (with blue bar).

**Comment by mittalyashu** [comment]
Facing the same issue.

![Image](https://user-images.githubusercontent.com/29014463/28673747-008a5df6-7301-11e7-9d7a-cf03672fcc76.png)

**Comment by LiguidCool** [comment]
This problem occurs because the atom actually has two executable files:
'C:\ProgramData\user\atom\atom.exe'
'C:\ProgramData\user\atom\app-1.20.1\atom.exe' (insert your app version).
First atom.exe just run lastest version of atom.exe in app-* folder. If you pin first file, windows dont know about second. If you pin second, atom dont update.

**Comment by danieldudas** [comment]
I sometimes click on the original icon when Atom is open, realize my mistake and swiftly try to close it(the second instance which I don't need). This can result in 'editor has stopped responding' error, so I kill the process. Which in turn can result that when I reopen Atom all my previously opened projects are closed, and I have to reopen them(I get the same empty Atom that I opened by mistake).
This seems to occur less frequently if I wait for the second Atom instance to load properly.

**Comment by mittalyashu** [comment]
Does the problem of two icons in the taskbar is an electron issue?

**Comment by nmgtav** [comment]
Have the same issue on the latest version (1.36.0 x64 Windows 10)

**Comment by garygreen** [comment]
Closing as no longer really interested in this long outstanding issue. Switched to vscode 😜
