### ISSUE TITLE
[v1.19-beta] Creating block decoration on manually created editor make editor rendering odd.

### ISSUE THREAD

**Issue by t9md** [atom/atom#14817]
Same issue of already closed #14743
Also might be related to this #14811

![block-decoration-issue](https://user-images.githubusercontent.com/155205/27255493-eaba6d7c-53d9-11e7-8507-bcf742a84494.gif)

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Creating block decoration at manually created editor make editor rendering odd.

- In v1.18: no issue
- In v1.19-beta: have issue(so editor rendering degradation?)

Additionally
- If I open item by `workspace.open(item)`: issue happen
- If I open item by `pane.activateItem(item)`: issue NOT happen
- Although, both have un-scrollable issue described in #14811

### Steps to Reproduce

1. launch atom in safe mode.
2. Open dev-console and paste code below.
  - it create editor and put 100 lines text
  - And add block decoration at point [0, 0]

```javascript
(function reproduceIssue() {
  const {TextEditor} = require("atom")
  const editor = new TextEditor()

  // case-1: Open with workspace.open
  atom.workspace.open(editor)

  // case-2: Open with pane.activateItem
  //   If I opened by pane.activateItem, this rendering odd is not happens.
  //   But still can't scroll though
  // const pane = atom.workspace.getActivePane().splitRight()
  // pane.activateItem(editor)

  const lines = []
  for (let i = 1; i < 100; i++) {
    lines.push(i)
  }
  editor.insertText(lines.join("\n"))
  editor.setCursorBufferPosition([0, 0])

  // Add blockdecoration at point [0, 0]
  const item = document.createElement("div")
  item.innerText = "[block decoration]"
  const marker = editor.markBufferPosition([0, 0])
  editor.decorateMarker(marker, {type: "block", item: item})
})()
```

3. see text is inserted at different line where cursor is displayed.

### Versions

macOS
```
ProductName:	Mac OS X
ProductVersion:	10.12.5
```

Atom
```
Atom    : 1.19.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

I noticed this issue while I'm investigating slowness of beta when opening manually created editor on my atom-narrow package.
Opening manually created editor is slower than atom-stable, not fully investigated yet(maybe this rendering issue might be cause of slowness).

**Comment by Zireael07** [comment]
Please don't open clones of closed issues.

**Comment by t9md** [comment]
What do you mean?

**Comment by t9md** [comment]
Thanks very much @as-cii as always!!
