### ISSUE TITLE
1.18 is just showing a blank screen on Ubuntu 16.04

### ISSUE THREAD

**Issue by rajat1saxena** [atom/atom#14821]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I installed the atom .deb package on Ubuntu 16.04, it now only shows a blank screen. I have had Atom 1.16 already installed, prior to installing this new upgrade.

### Steps to Reproduce

1. dpkg -i atom-amd64.deb

**Expected behavior:** [What you expect to happen]
It should have launched the proper editor UI
**Actual behavior:** [What actually happens]
It shows only a blank screen
**Reproduces how often:** [What percentage of the time does it reproduce?]
Every single time
### Versions
1.18
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

**Update**: I had to delete `.atom` directory in my home folder. I think it must be some add-on which was not behaving properly. But all of my settings are gone. :(

**Comment by 50Wliu** [comment]
It looks from your update that things are working now, so I'm going to close this issue.  In the future, I would advise making a backup of the `.atom` folder before deleting it.  That way, you can keep a backup of all your settings, customizations, and packages.

**Comment by EZWrighter** [comment]
Just a not for future reference, I had this same issue on Ubuntu 16.04 when upgrading to 1.21.1.  Deleted .atom folder and it started working.  Would be great to know the exact data in that folder that was locking things up and fix this automatically on update!
