### ISSUE TITLE
Scrollbars missing in project explorer

### ISSUE THREAD

**Issue by smedegaard** [atom/atom#14820]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When expanding folders so the list is higher than the application window, the scrollbars does not appear. Trying to scroll up and down with the mouse has no effect. Navigating with the arrow keys works as expected.

This worked in version 15.0

### Steps to Reproduce

1. Expand folders so the list of files in the explorer is higher than the application window

**Expected behavior:** Scrollbars appear and you can scroll up and down to find files in the explorer

**Actual behavior:**   the scrollbars does not appear. Trying to scroll up and down with the mouse has no effect.

**Reproduces how often:** 100%

### Versions

17.x, 18.0

### Additional Information

System : Ubuntu 16.04.2

**Comment by 50Wliu** [comment]
Please update Material UI to at least version 2.0.4.
