### ISSUE TITLE
[1.19.0-beta0] editor scaling issue on HDPI screen.

### ISSUE THREAD

**Issue by alexdevero** [atom/atom#14824]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
After updating from 1.18.0-beta3 to 1.19.0-beta0, Atom editor is not scaled properly on HDPI screen - panels and content are much larger than they were.

Atom v1.19.0-beta0 (broken sizing):
![1 19 0-beta0](https://user-images.githubusercontent.com/4237724/27271891-ab5017a6-54c7-11e7-836a-f4fae64f6b61.jpg)

Atom v1.18.0-beta3 (correct sizing):
![1 18 0-beta3](https://user-images.githubusercontent.com/4237724/27271883-9d8f8b24-54c7-11e7-8849-ee59bcfb9b4e.jpg)

### Steps to Reproduce

1. Update (install) to Atom 1.19.0-beta0
2. Start Atom editor

**Expected behavior:** [What you expect to happen]
Editor will scale properly - like version 1.18.0-beta3 (2nd screen).

**Actual behavior:** [What actually happens]
Editor doesn't scale properly - editor panels are enlarged.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
1.18.0-beta3:
apm:  1.18.1
npm:  3.10.10
node: 6.9.5 x64
python 2.7.13
git 2.13.1.windows.1
visual studio 2015

1.19.0-beta0:
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.1.windows.1
visual studio 2015

OS: Windows 10 1703 (64bit)

**Comment by hillam** [comment]
I am experiencing this as well on 1.19.0-beta0 with Windows 7.

**Comment by alexdevero** [comment]
@hillam thanks for your comment! I tried to apply the same argument to Atom shortcut and can confirm the same outcome - atom then launches with new files open with the names `"/high-dpi-support=1"` & `"/force-device-scale-factor=1"`.

**Comment by 50Wliu** [comment]
Atom doesn't do anything with high-DPI: that is all inherited from Electron and Chrome.  So it looks like the Chrome update changed some things with respect to hidpi?

**Comment by alexdevero** [comment]
It seem like it. The last version of Chrome is broken on high-DPI as well. Fortunately, `/high-dpi-support=1` parameter fixes that. Atom is a different story.

**Comment by alexdevero** [comment]
So, I checked the repo for electron and there is an issue for "Wrong BrowserWindow size on Hi-dpi devices" https://github.com/electron/electron/issues/9691.

**Comment by alexdevero** [comment]
This should help with scaling issue:
```
if (process.platform === 'win32') {
  app.commandLine.appendSwitch('high-dpi-support', 'true')
  app.commandLine.appendSwitch('force-device-scale-factor', '1')
}
```
Is it possible to implement this, in some shape or form, via Atom init script?

**Comment by hillam** [comment]
@alexdevero I must assume you mean putting the above code in `main-process/start.js` since `app` is undefined when I run this snippet in the Dev Tools console. 

Without looking too deeply into it, I tried adding the following to my init script to no avail. I didn't exactly expect this to work, but maybe someone can explain exactly why it didn't and suggest an alternative bandaid fix.
```coffeescript
window.addEventListener "load", ->
  app = require('electron')
  if process.platform == 'win32'
      app.commandLine.appendSwitch('high-dpi-support', 'true')
      app.commandLine.appendSwitch('force-device-scale-factor', '1')
```

**Comment by alexdevero** [comment]
@hillam that's a bad news. I hoped it will work. I found it in https://github.com/electron/electron/issues/9417.

**Comment by 50Wliu** [comment]
@hillam I believe you need `{app} = require('electron')`, though I'm not sure if the init script launches soon enough for the switches to have any effect.

**Comment by alexdevero** [comment]
@50Wliu I don't think so. The init script is not a solution. It looks that we will have to wait until this is fixed in electron and implemented in Atom. Until then, the only option is to stick with 1.18.0.

**Comment by alexdevero** [comment]
@50Wliu Yes, you are right. I tested the solution on one of my apps build on electron. Adding that if statement to the main app script, below the `{app} = require('electron')` solved problems I had with hi-dpi scaling in my app. Is it possible to implement the fix to the Atom core script?

**Comment by hillam** [comment]
@50Wliu Yeah, I'm not sure what the startup order looks like exactly, but I wouldn't be surprised if the init script executes too late to make this change. 

@alexdevero I think the issue is that although HDPI scaling, although obviously not universally good/desired, is also not universally bad/undesired. Turning it off for everyone is probably not the right approach. I'll wager the best solution would be to introduce a new setting to atom that allows users to choose whether it is enabled.

**Comment by alexdevero** [comment]
@hillam such an option would be good. About `/high-dpi-support=1` and `/force-device-scale-factor=1`, I tried it and atom always launches with new files open with the names "/high-dpi-support=1" & "/force-device-scale-factor=1". So "Open with Atom" and similar features doesn't work.

**Comment by hillam** [comment]
@alexdevero see my first comment on this thread:
https://github.com/atom/atom/issues/14824#issuecomment-309429378

**Comment by alexdevero** [comment]
@hillam Sorry, my mistake. I forgot.

**Comment by alexdevero** [comment]
@hillam Any progress on, or information, about, implementing an option to disable HDPI scaling?

**Comment by hillam** [comment]
@alexdevero I've never contributed to atom before, but I might try to look into it this weekend.

**Comment by alexdevero** [comment]
@hillam I though you are already a contributor 😄. Let's do a competition. Who will come up with PR that solves the HDPI scaling issue wins. Are you in?

**Comment by alexdevero** [comment]
@hillam Until this issue is resolved, take a look at [hidpi](https://atom.io/packages/hidpi) Atom package. This package helped me solve the issue, at least for now. You may need to play with different settings to see what works for you. Settings which worked for me:
- Cutoff Height: 1080
- Cutoff Width: 1920
- Default Scale Factor: 0.85
- Hidpi Scale Factor: 1.25

The rest of values are default.

**Comment by mdirienzo** [comment]
I came across this issue when researching issue #15257. I've noticed this occurs when you scroll to hit the bottom of the current file. When you scroll to the top, the text becomes unblurred.

**Comment by GabrSaac** [comment]
It's not only when you scroll to hit the bottom, it occurs also on certain positions in the middle from top page to the bottom. Adding a few new lines at the end of file partially improves the issue.
