### ISSUE TITLE
Uncaught Error: Requested measurement of a line that is not currently rendered

### ISSUE THREAD

**Issue by g33ktony** [atom/atom#14834]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Requested measurement of a line that is not currently rendered

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2137

Error: Requested measurement of a line that is not currently rendered
  at horizontalPositionsToMeasure.forEach (<embedded>:8112:29)
  at Map.forEach (native)
  at TextEditorComponent.measureHorizontalPositions (<embedded>:8105:45)
  at TextEditorComponent.measureContentDuringUpdateSync (<embedded>:6350:16)
  at scheduler.readDocument (<embedded>:6240:20)
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (<embedded>:20026:15)
  at <embedded>:19838:65

```

### Commands

```
     -0:53 editor:toggle-line-comments (input.hidden-input)
     -0:51.2.0 core:save (input.hidden-input)
     -0:15.8.0 core:backspace (input.hidden-input)
     -0:11.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
file-icons 2.1.7 
language-babel 2.66.0 
nuclide 0.232.0 
wakatime 7.0.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by g33ktony** [comment]
I was just selecting some text, atom deselected and then started showing me the error again and again.

Til then I'm still working with atom-beta and the error never appeared again, but now the selection and deleting of a block of code it's weird, I select the code I want to delete, then press the delete key, the editor deletes that lines but the code below gets automatic selected, if I try to write before deleting I delete more lines that I wanted

**Comment by Ky6uk** [comment]
Atom version: `1.19.0-beta2`

It happend when I tried to open file with conflicts after running the `git rebase` command.

**Comment by SEAPUNK** [comment]
Randomly happens to me when copy/pasting code. The code looks half-pasted, where the first half of the code is just empty. Atom `1.19.0-beta2`

**Comment by Raindeer44** [comment]
This just happened to me for the first time on `1.19.0-beta2` upon opening a file containing a merge conflict. It wouldn't let me scroll down more than five lines. I closed the file, fixed the merge conflicts with vim and now Atom is fine.

**Comment by alexandernst** [comment]
Just happened to me after updating some packages in Atom and then trying to save a file

**Comment by fillphree** [comment]
Looks like I just hit this as well in Atom Beta.

I was simply copying text from MS Word and pasting it in a new file in Atom Beta 1.19.0-beta3.

Clicking anywhere on the pasted text in Atom pops up this Uncaught Error.
This is on:
System Version:	OS X 10.11.6 (15G1510)
Kernel Version:	Darwin 15.6.0

`/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2150
Hide Stack Trace
Error: Requested measurement of a line that is not currently rendered
    at horizontalPositionsToMeasure.forEach (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2148:29)
    at Map.forEach (native)
    at TextEditorComponent.measureHorizontalPositions (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2141:45)
    at TextEditorComponent.measureContentDuringUpdateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:382:16)
    at scheduler.readDocument (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:266:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:191:15)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:3:65`

**Comment by rsese** [comment]
> Til then I'm still working with atom-beta and the error never appeared again, but now the selection and deleting of a block of code it's weird, I select the code I want to delete, then press the delete key, the editor deletes that lines but the code below gets automatic selected, if I try to write before deleting I delete more lines that I wanted

Are you still seeing this with the latest beta (`1.19.0-beta4`) @g33ktony?  If so can you open a new issue and fill out the template?

**Comment by rsese** [comment]
For folks hitting this error copying/pasting text, can anyone confirm if it's reproducible in safe mode (`atom --safe`) and if so, can you share the text so we can try to reproduce?

**Comment by g33ktony** [comment]
I just stop using beta
