### ISSUE TITLE
New version 1.18.0 open and freezes on OSX sierra

### ISSUE THREAD

**Issue by Rovel** [atom/atom#14830]
### Description
Just updated to the new version of Atom 1.18.0 and it freezes after it's initialization
### Steps to Reproduce

1. open app
![captura de tela 2017-06-19 as 11 54 41](https://user-images.githubusercontent.com/2469500/27291391-74ecf0a2-54e6-11e7-892a-8b8d076156c2.png)

**Expected behavior:** [What you expect to happen]
open as usual with the elcome screen and stuff

**Actual behavior:** [What actually happens]
open as the image above
**Reproduces how often:** [What percentage of the time does it reproduce?]
if you initialize it straigh from a file it opens normally

### Versions

it was ok in the 1.17.2, after the update to 1.18.0 it ahs this behaviour

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm If disabling the github package gets you past the freeze?  If so, I think we can close this as a duplicate of https://github.com/atom/atom/issues/14806.

**Comment by rsese** [comment]
Oh also, it would be helpful if you can fill out the entire issue template for future issues - in particular, can you confirm if you see the same behavior in safe mode (`atom --safe`)?

**Comment by Rovel** [comment]
Oh ok,

I've tried to make those teste but the issue is not repeating after I configured the atom-github package with the token and stuff, probably it have something to do with the atom-github ans its configs

**Comment by rsese** [comment]
> I've tried to make those tests but the issue is not repeating after I configured the atom-github package with the token and stuff, probably it have something to do with the atom-github and its configs

Thanks for letting us know, that's interesting that logging in with a token in the GitHub panel made the problem go away.  I wasn't able to reproduce by starting Atom while not logged in through the GitHub tab but if you run into this issue again, feel free to open an issue in https://github.com/atom/github/issues :v:
