### ISSUE TITLE
Certificate Related Error when Checking for updates this morning

### ISSUE THREAD

**Issue by bobber205** [atom/atom#14833]
When I checked for updates this morning I got super strange error related to I think certificates? Anyway, cant' download the new update --

![image](https://user-images.githubusercontent.com/5841107/27299894-ae87ad60-54e2-11e7-91e7-2c5795e9e7fa.png)

Beta-1 for 1.19 is out and when I do check update now it just says .0 beta is the newest. Was the update pulled and just not removed from atom.io/releases ?

Sorry I can't give the actual error, maybe someone will see this ticket and include a screenshot of it? I'm not able to repo (or update).

Thanks!

**Comment by rsese** [comment]
Sorry about that!  There was a problem with that release so it's been removed for now - we'll post a new one when the certificate issue is resolved.

**Comment by bobber205** [comment]
Cool thanks! 👍

**Comment by rsese** [comment]
A new release is up, and the update worked ok for me - let us know if you have any trouble and thanks again for reporting :v:

**Comment by bobber205** [comment]
Updated just now thanks!
