### ISSUE TITLE
Continuing to see a lot of files show up in project search after I've renamed or deleted them. Makes

### ISSUE THREAD

**Issue by jbarnette** [atom/atom#1483]
Continuing to see a lot of files show up in project search after I've renamed or deleted them. Makes search pretty hard to use for manual refactoring.

Atom Version: 0.48.0
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Atom/0.48.0 Atom-Shell/0.8.5 Safari/537.36

**Comment by benogle** [comment]
@jbarnette please reopen if you still have this issue.
