### ISSUE TITLE
Replace doesn't work for replacing \" with "

### ISSUE THREAD

**Issue by azurinko** [atom/atom#14845]
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
+ Nuclide and few extensions

Open a new document...
Copy and paste this example into it:
`jQuery('#selector').html( '<div class=\"class1\"><div class=\"class2\" >Text1</div><div class=\"class1\"></div><br class=\"clear\"><div class=\"class1\"></div></div>' );`

Now open replace tool...
Replace: \\"
With: "

Replace doesn't work at all

Also a extension which makes markup html inside javascript's innerHTML function string would be awesome, but I don't have time :/ What would you call it?

**Comment by azurinko** [comment]
\\\" works as "\ this may be expected behaviur, but migrating from sublime text it was unexpected for me.

**Comment by rsese** [comment]
Thanks for the report!  It sounds like you have things sorted out?  Also, replace works for me if I follow your steps in the issue body.

If you think you've found a bug however, feel free to open an issue in https://github.com/atom/find-and-replace so we have it in the right place and completely fill out the issue template.

> Also a extension which makes markup html inside javascript's innerHTML function string would be awesome, but I don't have time :/ What would you call it?

Hmm, not sure what you mean but if you have general questions like this, a couple of great places to ask them is on the official message board or Atom Slack:

* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
