### ISSUE TITLE
Installing after build fails with a permission error

### ISSUE THREAD

**Issue by MoritzKn** [atom/atom#14848]
### Description

On Arch Linux building Atom from source with the `--install` flag fails with a permission error.

### Steps to Reproduce

1. `git clone git://github.com/atom/atom.git`
2. `cd atom`
3. `git checkout 1.19-releases`
4. `script/build --install`

**Expected behavior:**
Build ends without errors and atom `1.19.0-beta1` is installed.

**Actual behavior:**
Build fails with:
```
Installing "atom-beta-1.19.0-beta1-amd64" at "/usr/local/share/atom-beta"
Error: EACCES: permission denied, unlink '/usr/local/share/atom-beta/LICENSE'
  at Error (native)
  at Object.fs.unlinkSync (fs.js:1103:18)
  at copyFileSync (/home/moritz/code/atom/atom/script/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:13:10)
  at copySync (/home/moritz/code/atom/atom/script/node_modules/fs-extra/lib/copy-sync/copy-sync.js:32:7)
  at /home/moritz/code/atom/atom/script/node_modules/fs-extra/lib/copy-sync/copy-sync.js:40:7
  at Array.forEach (native)
  at Object.copySync (/home/moritz/code/atom/atom/script/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:14)
  at module.exports (/home/moritz/code/atom/atom/script/lib/install-application.js:62:8)
  at dumpSymbols.then.then.then.then.packagedAppPath (/home/moritz/code/atom/atom/script/build:111:7)
```

**Reproduces how often:** 
Always

### Versions
Atom: `1.19.0-beta1`
OS: Arch Linux

### Additional Information

I tried running the build script as root with `sudo script/build --install` but then the build failed with an error similar to #7134.

**Workaround:**:
Run `script/build` without the `--install` flag and then run:
```bash
packagedAppPath=$(echo ~/code/atom/atom/out/atom-*)
sudo node -e "require('./script/lib/install-application')('$packagedAppPath', '')"
```

**Comment by daviwil** [comment]
Hey @MoritzKn, thanks for the tip on using `node -e` to run the installation step, I used it to make a solution in PR #16528 to automate this for `scripts/build --install` :)

**Comment by twifty** [comment]
Same issue on Manjaro 4.14 while building atom 1.26

> Error: EACCES: permission denied, mkdir '/usr/local/share/applications'
>   at Object.fs.mkdirSync (fs.js:902:18)
>   at Object.mkdirsSync (/home/owen/github/atom/script/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
>   at module.exports (/home/owen/github/atom/script/lib/install-application.js:76:8)
>   at binariesPromise.then.then.then.then.packagedAppPath (/home/owen/github/atom/script/build:132:7)
>   at <anonymous>:null:null
Is there a way to manually install? I don't feel running `sudo build --install` is the right thing to do.
