### ISSUE TITLE
Feature request: number of pulls/pushes visible next to project name

### ISSUE THREAD

**Issue by Evertvz** [atom/atom#14847]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

First of all, adding git support is a great idea. I am thrilled with this new feature. This feature would in my opinion increase the usefulness even more. It's about the same as what SourceTree does although they periodically fetch information to keep the numbers accurate.

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]
It would be handy if Atom could show the number of pulls/pushes next to a project folder's name in the project pane. This would allow for a global overview if you have multiple projects open.
For example: ```my_project    2  1``` where 2 would be the number of pulls and 1 the number of pushes that are pending.

**Actual behavior:** [What actually happens]
Currently only the project name is shown

**Reproduces how often:** [What percentage of the time does it reproduce?]
new feature

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/github](https://github.com/atom/github) repository.  Thanks!
