### ISSUE TITLE
Stage All button not work on huge commits

### ISSUE THREAD

**Issue by khaninejad** [atom/atom#14840]
### Description

When I want to commit huge file it not work,(more than 700 files)

### Steps to Reproduce

1. 
I have files to commit
2. 
Click on git stage
3. 
Click on stage all button
4.
nothing happen

**Expected behavior:** 
All file moved to staged changes

**Actual behavior:** 
button or function not work

**Reproduces how often:**
with big commits(more than 700 files)

### Versions
1.18.0 x64 Windows

### Additional Information
I use gitlab
![attach-git](https://user-images.githubusercontent.com/4404500/27325595-360b5ae4-55be-11e7-8a52-f7336394b151.PNG)

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/github](https://github.com/atom/github) repository.  Thanks!
