### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by franklinrli** [atom/atom#14851]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 2.4.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/franklin/Downloads/Learn IDE 2.app/Contents/Resources/app.asar/node_modules/learn-term.js/src/term.js:1306

TypeError: Cannot read property '0' of undefined
    at TerminalWrapper.Terminal.refresh (/app.asar/node_modules/learn-term.js/src/term.js:1306:18)
    at TerminalWrapper.Terminal._cursorBlink (/app.asar/node_modules/learn-term.js/src/term.js:1422:8)
    at _blinker (/app.asar/node_modules/learn-term.js/src/term.js:1439:10)
```

### Commands

```
     -9:47.1.0 learn-ide:reset-connection (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for contributing!

It appears that this is being caused by the [learn-ide](https://atom.io/packages/learn-ide) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by ZuBB** [comment]
get this today

```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/partial-keyup-matcher.js:57

TypeError: Cannot read property '0' of undefined
    at PartialKeyupMatcher.getMatches (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/partial-keyup-matcher.js:42:105)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:375:91)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  7x -1:18.9.0 vim-mode-plus:move-down (input.hidden-input)
  7x -1:17.7.0 vim-mode-plus:move-up (input.hidden-input)
     -1:15.2.0 vim-mode-plus:next-tab (input.hidden-input)
     -1:14.8.0 vim-mode-plus:move-up (input.hidden-input)
     -1:14.5.0 vim-mode-plus:move-down (input.hidden-input)
     -1:13.8.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -1:13.3.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
  4x -1:13 vim-mode-plus:move-down (input.hidden-input)
     -1:00.7.0 vim-mode-plus:put-after (input.hidden-input)
     -0:58.5.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:42.3.0 vim-mode-plus:move-to-mark (input.hidden-input)
     -0:41.9.0 vim-mode-plus:set-input-char-g (input.hidden-input)
     -0:41.4.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:41.4.0 vim-mode-plus:move-to-mark (input.hidden-input)
     -0:40.6.0 core:cancel (input.hidden-input)
     -0:40.2.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-live-server 2.1.2 
atom-typescript 11.0.9 
atom-vim-keymap 1.0.1 
busy-signal 1.4.3 
compare-files 0.8.1 
editor-stats 0.17.0 
editorconfig 2.2.2 
emmet 2.4.3 
emmet-simplified 2.5.0 
ex-mode 0.18.0 
git-control 0.9.0 
git-plus 7.9.3 
go-plus 5.5.5 
goto-definition 1.3.4 
intentions 1.1.5 
language-scala 1.1.9 
linter 2.2.0 
linter-ui-default 1.6.10 
open-recent 5.0.0 
pretty-json 1.6.4 
show-invisibles-plus 0.3.1 
svg-preview 0.11.0 
sync-settings 0.8.3 
todo-show 2.0.0 
vim-mode-plus 1.7.0 
vim-mode-plus-ex-mode 0.9.1 
vim-plus-autocomplete-emmet-compatibility 0.1.0 
webbox-color 0.5.9 
xterm 1.2.1 
```

**Comment by rsese** [comment]
Looks like your error is coming from https://github.com/atom/atom-keymap?  Can you open an issue there @ZuBB?  If you can fill out the issue template and share steps to reproduce, that would be super helpful.
