### ISSUE TITLE
Docker/Kubernetes support

### ISSUE THREAD

**Issue by bhack** [atom/atom#14860]
Often a developer could use the editor on the host and mounting source volumes inside a docker container to compile, debug and run code there.
Instead of mounting a portable atom volume inside the container to run the editor in docker could be possible to run plugins command (build, make etc..) inside a container (cause generally they suppose run tools locally)? 
I don't really know if could be introduced some global feature in Atom for this.
I thought this cause I'm supposing that there could be some sensible informations in the .atom directory that could not be the best practice to have that exposed in every container mounting a "atom volume".

**Comment by bhack** [comment]
Probably a prefix for executing command with a `docker exec` on a running container.

**Comment by Glavin001** [comment]
In order to support Windows, Mac, Linux I have used Docker images from https://github.com/Unibeautify/docker-beautifiers and wrapped `docker exec unibeautify/PROGRAM` execution whenever running `PROGRAM` fails (not installed). The intention is to reduce user's required manual installation along with supporting cross platform.

I think this may be better suited as a separate Node.js package and recommend it to Atom package developers.

**Comment by bhack** [comment]
@Glavin001 what do you think of https://www.npmjs.com/package/docker-exec?

**Comment by Glavin001** [comment]
`docker-exec` looks great. I would like to abstract it further so I have what I call `Executables`. Let's say I have an executable for `atom` I could call `atom.run([arg1, arg2, ...])` and it would first call `atom arg1 arg2 ...` directly and then fallback to `docker exec ATOM_IMAGE arg1 arg2 ...`.

Let's talk over at https://github.com/Glavin001/executables.js

**Comment by bhack** [comment]
Generally third party libs/dependencies will be installed in the container and not on the host.
As Atom it is approaching to be and ide we need to figure out how to handle language server, remote debbugger, etc. inside the container. I.e. Take a look at https://github.com/lgeiger/ide-python/issues/48

**Comment by bhack** [comment]
See also https://medium.com/@kanecohen/running-dockerized-executables-from-atom-editor-5055913bb1ba

**Comment by bhack** [comment]
I mean something like https://github.com/Glavin001/executables.js/issues/1

**Comment by bhack** [comment]
Check https://github.com/Microsoft/vscode-python/issues/79

**Comment by bhack** [comment]
For Docker/Kubernetes something is landing in vscode: https://github.com/Azure/vscode-kubernetes-tools/

**Comment by bhack** [comment]
Now that you are good friends :wink: https://blogs.msdn.microsoft.com/visualstudio/2018/06/08/preview-of-visual-studio-kubernetes-tools/

**Comment by ibnesayeed** [comment]
I do not like to install too many language run times and development packages on my host machine and run most of my builds inside of a container instead. Having a uniform means of running language servers, builds, tests, and other such tasks in containers from Atom editor would be a great.
