### ISSUE TITLE
Gutter line numbers have different height

### ISSUE THREAD

**Issue by borishere** [atom/atom#14863]
![lines](https://user-images.githubusercontent.com/4622497/27390406-d387ae9e-56a9-11e7-8696-0d3acf22bc73.png)

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Some line numbers have different height.

**Expected behavior:** All lines have the same length

**Actual behavior:** Some lines have different length

### Versions

1.19.0-beta1

### Additional Information

Seems to happen only on lines with git icons but I`m not 100% sure.

My `config.cson` file: 

```
"*":
  "atom-beautify":
    general:
      _analyticsUserId: "de30d997-4c4b-405e-9444-5e949415aa8b"
    html: {}
    js:
      end_with_newline: true
  "autocomplete-plus":
    confirmCompletion: "enter"
  "bracket-matcher": {}
  build:
    saveOnBuild: true
    scrollOnError: true
  "build-sass": {}
  "color-picker":
    randomColor: false
  "console-log":
    contextMenu: false
    identifierCase: true
    noSelectionInsert: true
    semiColons: true
  core:
    autoHideMenuBar: true
    customFileTypes:
      "source.json": [
        "jsbeautifyrc"
        "eslintrc"
        "csslintrc"
        "stylelintrc"
      ]
    disabledPackages: [
      "wrap-guide"
      "welcome"
      "autoflow"
      "autosave"
      "dev-live-reload"
      "package-generator"
      "styleguide"
      "update-package-dependencies"
      "pigments"
    ]
    ignoredNames: [
      ".git"
      ".hg"
      ".svn"
      ".DS_Store"
      "._*"
      "Thumbs.db"
      "desktop.ini"
      ".sass-cache"
    ]
    packagesWithKeymapsDisabled: [
      "open-in-browser"
      "console-log"
      "goto-definition"
      "bookmarks"
      "highlight-selected"
      "opened-files"
      "encoding-selector"
      "ctrl-dir-scroll"
      "git-diff"
      "tree-view"
      "atom-beautify"
      "color-picker"
      "linter-ui-default"
      "atom-unsaved-changes"
    ]
    telemetryConsent: "limited"
  "cursor-blink-interval":
    cursorBlinkInterval: 1000
  "ease-blink": {}
  editor:
    fontSize: 17
    invisibles: {}
    nonWordCharacters: "/\\()\"':,.;<>~!@#$%^&*|+=[]{}`?…"
    scrollPastEnd: true
    showIndentGuide: true
    zoomFontWhenCtrlScrolling: false
  "exception-reporting":
    userId: "1867c94e-2de4-470f-a0e3-87b549f77ed8"
  "file-icons":
    tabPaneIcon: false
  "file-watcher":
    autoReload: true
    includeCompareOption: false
    promptWhenChange: true
  filesize: {}
  "find-and-replace":
    liveSearchMinimumCharacters: 1
    scrollToResultOnLiveSearch: true
  fonts:
    fontFamily: "Source Code Pro Light"
  "git-diff":
    showIconsInEditorGutter: true
  "highlight-selected":
    highlightInPanes: false
    onlyHighlightWholeWords: false
  linter:
    lintOnChange: false
    lintOnOpen: false
  "linter-csslint":
    disableTimeout: true
  "linter-eslint": {}
  "linter-less":
    strictUnits: true
  "linter-ui-default":
    decorateOnTreeView: "None"
    panelHeight: 400
    statusBarRepresents: "Current File"
    tooltipFollows: "Keyboard"
  minimap:
    displayPluginsControls: false
    minimapScrollIndicator: false
    scrollAnimation: true
    textOpacity: 0.5
  "minimap-git-diff":
    useGutterDecoration: true
  "one-dark-ui":
    fontSize: 13
    hideDockButtons: true
  "opened-files":
    highlightOnHover: false
    removeOnClose: true
  pigments:
    groupPaletteColors: "by file"
    markerType: "native-underline"
    sourceNames: [
      "none"
    ]
  "project-manager": {}
  "scope-inspector":
    userId: "e4d52407b15877bb0595000be34542d5013cf595"
  "spell-check":
    grammars: [
      "source.asciidoc"
      "source.gfm"
      "text.git-commit"
      "text.plain"
      "text.plain.null-grammar"
      "source.js"
      "text.html.basic"
    ]
  "split-diff":
    hideTreeView: true
  "status-bar": {}
  "sync-settings":
    _lastBackupHash: "1681496115b4ad589e10ebaeb578e82923ee17e6"
    gistId: "f60ba27f808f9c080ed5a03405c99ed6"
    personalAccessToken: "72802ac8f86cc48e521adf54a3d310933c9da4ba"
    quietUpdateCheck: true
    removeObsoletePackages: true
  "tab-control":
    autoSaveChanges: true
  tabs: {}
  "tree-view":
    hideIgnoredNames: true
    hideVcsIgnoredFiles: true
  "tree-view-autoresize": {}
  whitespace:
    ensureSingleTrailingNewline: false
    ignoreWhitespaceOnCurrentLine: false
".basic.html.text":
  editor:
    autoIndentOnPaste: true
    softWrap: true
    tabLength: 4
".css.less.source":
  editor:
    tabLength: 4
".css.source":
  editor:
    tabLength: 4
".js.regexp.replacement.source":
  editor:
    nonWordCharacters: "/\\()\"':,.;<>~!@#%^&*|+=[]{}`?…"
    tabLength: 4
".js.regexp.source":
  editor:
    nonWordCharacters: "/\\()\"':,.;<>~!@#%^&*|+=[]{}`?…"
    tabLength: 4
".js.source":
  editor:
    nonWordCharacters: "/\\()\"':,.;<>~!@#%^&*|+=[]{}`?…"
    softTabs: true
    tabLength: 4
".json.source":
  editor:
    tabLength: 4
".sass.source":
  editor:
    tabLength: 4

```

**Comment by rsese** [comment]
Thanks for the report!  Do you see this with all files or just a particular file?

And if you copy the file in your screenshot above to a new file (so it's no longer part of a git repository), do you still see the same thing?

**Comment by borishere** [comment]
@rsese It happens on all files. New file doesn't have this problem, so I confirm it happens only on git-marked-lines. Just try to open a `JavaScript` file and press `enter` many times, you are likely to reproduce it.

**Comment by rsese** [comment]
Hmm, I'm not able to reproduce with these steps:

1. mkdir test; cd test
2. git init
3. I created JS file `test.js` with:

```
printf 'var hi = function() {\n  console.log("Hello World!");\n};\n' >> test.js
```

4. git add test.js
5. git commit -m "Test"
6. atom test.js
7. Held down <kbd>enter</kbd> for a while till it got to ~100 lines

So I had a bunch of lines marked as added but the line numbers looked ok after doing this.

Can you reproduce with these steps?  

/cc a couple of other line numbering issues https://github.com/atom/atom/issues/14842 and https://github.com/atom/atom/issues/14735.  One is related to scrolling and the other is specific to large files though.

**Comment by borishere** [comment]
@rsese I moved to more stable `Atom - 1.18.0`, I don't want to use `beta` anymore :)
This bug doesn't appear here. So the problem is somewhere in `beta`.
As far as I know `beta` has modified gutter...

If you still can't reproduce it - try to open existent files, for example from atom repository and edit them.
I didn't try with initing new repositories.

**Comment by borishere** [comment]
Issue is still there in 1.19.0

**Comment by rsese** [comment]
I'll try and repro again in 1.19.0 - sorry if I missed this but what operating system are you running?

**Comment by borishere** [comment]
Windows 10 64-bit

**Comment by CharlSteynberg** [comment]
[same issue](https://github.com/atom/atom/issues/9344)
.. but "closed" .. face-desk
