### ISSUE TITLE
restorePreviousWindowsOnStart works only when path is not specified

### ISSUE THREAD

**Issue by martinosorb** [atom/atom#14865]
By request of @50Wliu, I'm opening a new issue to complement the closed #6605.
`restorePreviousWindowsOnStart` seems to work only when atom is launched without a specified location, as reported by @andreaferretti. See also https://discuss.atom.io/t/remember-open-projects-when-reopening-atom/7053/37

**Comment by yubaoquan** [comment]
I don't know whether it is the same issue of mine: when installed some update of packages, I click the restart button on the popup, then the previous state of window changed. I opened 2 or 3 projects in one maximized window with separated tabs. after restart, the previous tabs in one window changed to separated windows. 
Mac OS
