### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=407

### ISSUE THREAD

**Issue by topecz** [atom/atom#14866]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=407

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=407
    at ClientRequest.onConnect (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/tunnel-agent/index.js:166:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
```

### Non-Core Packages

```
minimap 4.26.8 
minimap-git-diff 4.3.1 
multi-cursor 2.1.5 
split-diff 1.1.4 
Sublime-Style-Column-Selection 1.7.3 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* are you using a proxy?

**Comment by jugalps** [comment]
I am getting the same error when performing the same operation and I am also behind a corporate proxy.

**Comment by rsese** [comment]
Are folks getting this error after setting up apm to use your proxy?

https://github.com/atom/apm/#using-a-proxy

**Comment by jugalps** [comment]
Yes, that's correct. I get the error even after setting up apm to use proxy. It seems recently there was a change to our proxy configuration which required us to authenticate, perhaps that's the reason it isn't working any more.

**Comment by Mikaciu** [comment]
Yep, my previous tests were done with the proxy set in apm : 
```
> apm config get http-proxy
http://localhost:8246

> apm config get https-proxy
http://localhost:8246/

> cat %userprofile%\.atom\.apmrc
http-proxy=http://localhost:8246
https-proxy=http://localhost:8246
strict-ssl=false
```

I don't know if the trailing forward slash in the https-proxy config has to do with this though, it's not present in the .apmrc file.

**Comment by zicklag** [comment]
@jugalps, I am also behind a proxy with authentication, but I was able to get it to work by setting the http and https proxy to `http://user:password@server:port`. I had my http_proxy and https_proxy environment variables set like that, but that only worked for apm on the commandline. After using `apm config set` it worked in the UI as well.

**Comment by hendrikbl** [comment]
I'm getting this again after updating atom to version 1.25.0. It worked just fine with 1.24.*.

Now I'm getting a `tunneling socket could not be established, statusCode=407` message when searching for packages or themes. When using `apm search` everything works fine and featured packages are shown too.

I have set my http and https proxy via `apm config` and as environment variables.

**Comment by astrapotro** [comment]
Same error like @hendrikbl here when trying to find a package:  `tunneling socket could not be established, statusCode=407`
Checking updates of atom itself works fine.
Atom version is last one, 1.25.0
http and https proxy in .atom/.apmrc are OK 
Installing package via apm works fine

**Comment by samuelharmer** [comment]
Talk about [SOUP][https://en.wikipedia.org/wiki/Software_of_unknown_pedigree]. These were all the URLs I needed access to through the proxy to install `sync-settings` (my particular use case).

* atom.io
* www.atom.io
* packagecloud.io
* packagecloud-repositories.s3.dualstack.us-west-1.amazonaws.com
* packagecloud-prod.global.ssl.fastly.net
* codeload.github.com
* gh-contractor-zcbenz.s3.amazonaws.com
* registry.npmjs.org

**Comment by Getz85** [comment]
Same issue as astrapotro described, even with the v1.25.1.

**Comment by moriyas1984** [comment]
I'm getting the same error.
I'm using v1.27.1 x64 on Windows (I'v updated it today).
The command `apm search ` via git bash returned proper results, but searching package on Atom GUI (Install new Package and Themes) failed and returned error message `tunneling socket could not be establised, status code=407 `.
I think my setting in .apmrc is OK, but something of Atom GUI isn't running normally.

**Comment by jpicton** [comment]
Can verify that this is a regression.

I have Atom 1.27.2 x64 installed and have observed the following:

* `apm search` returns expected results
* `apm install` installs packages as expected
* Featured Packages section in the GUI successfully loads results
* Available Updates in the GUI successfully loads results / checks for updates
* Install Package in the GUI always displays the _tunneling socket could not be established, statusCode=407_ error message

I have `https-proxy` config set in `.apmrc`, and it seems to be applied successfully in all cases except for installing packages via the GUI. I've only noticed this issue in the past month, so the regression must have been introduced in a recent release.

**Comment by fkiefl** [comment]
I have installed Atom 1.28.0 and can confirm exactly the same like jpicton was commented

**Comment by Mikaciu** [comment]
Same thing with 1.29.0-beta0.

**Comment by jpcozar** [comment]
Same thing as jpicton said in Atom 1.28.1.

**Comment by hendrikbl** [comment]
Same error with 1.29.0.

**Comment by nitishlobo** [comment]
Same error with 1.29.0

@hendrikbl when I use `<atom --proxy-server=http://my.proxy>` the error is no long reproducible. 
Your suggestion works. But how do I make it work with the windows explorer right click option "Open with Atom"?
