### ISSUE TITLE
The editor has crashed when try to open .psd file

### ISSUE THREAD

**Issue by borishere** [atom/atom#14875]
![screenshot_2](https://user-images.githubusercontent.com/4622497/27437023-a6b5b7a6-5769-11e7-844f-0e95c8bc6ea6.png)

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The editor has crashed when open `.psd` file.

**Reproduces how often:** always

### Versions

1.19.0-beta1

### Additional Information

I didn't encounter this in earlier versions. It opened and showed a character set.
As a suggestion: may be Atom could open `.psd` file as an image like `.png` or `.jpg`?

**Comment by maxbrunsfeld** [comment]
@borishere Can you share an example of a file that makes Atom crash?

**Comment by borishere** [comment]
Example file:
[no-screenshot.zip](https://github.com/atom/atom/files/1096114/no-screenshot.zip)

**Comment by maxbrunsfeld** [comment]
I can't reproduce this on Atom 1.19.0-beta1. What operating system are you using?

**Comment by maxbrunsfeld** [comment]
Are you using 32-bit or 64-bit Windows?

**Comment by borishere** [comment]
64

**Comment by Jmacek** [comment]
I can confirm the crash on Windows 10 x64 using the provided file (tree view seems to be irrelevant to the crash though). Though i'm not familiar with how to provide a stacktrace for this program.

**Comment by 50Wliu** [comment]
@Jmacek crash dumps should be available in `%TEMP%\Atom Crashes`.  Can you please upload the latest `.dmp` file?  You'll need to zip it in order for GitHub to accept it.

**Comment by 50Wliu** [comment]
I can reproduce the crash, though unfortunately it seems like the dumper isn't starting correctly and I'm not getting any crash dumps.  Windows 10 x64.
```
Atom    : 1.20.0-dev-ac99e0861
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by Jmacek** [comment]
@50Wliu Thanks, it looks like my dumper isn't starting either. I think it might be because the reporter-url is down? 

https://crashreporter.atom.io/

**Comment by maxbrunsfeld** [comment]
Ok, I have reproduced this on my windows VM. I'm sorry about this regression everyone. I'm debugging it now and we'll release a new beta hotfix shortly (probably Monday).

**Comment by maxbrunsfeld** [comment]
Ha! Actually, I believe this is already fixed, via https://github.com/atom/atom/pull/14835. It looks like there was a bug in the windows implementation of `codecvt_utf8_utf16`, which we are no longer using.
