### ISSUE TITLE
Atom hangs and crashes repeatedly

### ISSUE THREAD

**Issue by wjakethompson** [atom/atom#14874]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom hangs repeatedly upon scrolling and editing text. After a couple freezes, it will crash and give the following error:
![screen shot 2017-06-22 at 8 37 31 am](https://user-images.githubusercontent.com/6980750/27437027-9ae316a0-5726-11e7-991e-adb185334d42.png)

### Versions

```
$ atom --version
Atom: 1.18.0
Electron: 1.3.15
Chrome: 52.0.2743.82
Node: 6.5.0

$ apm --version
apm 1.18.1
npm 3.10.10
node 6.9.5 x64
python 3.5.2
git 2.11.0
```
OS: masOS Sierra, version 10.12.5

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if temporarily disabling the GitHub package makes any difference, see this comment for more details about the issues identified recently /cc https://github.com/atom/atom/issues/14806#issuecomment-309546499

Also can you share your crash file?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/14874#issuecomment-310456706. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
