### ISSUE TITLE
Problem with the new Git Integration in Atom 1.18 (32-bit)

### ISSUE THREAD

**Issue by airone506** [atom/atom#14889]
### Prerequisites

* [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* [ ] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The new Git Integration in Atom does not work on my computer, probably since the 1.18 version.

### Steps to Reproduce & Actual behavior:

1. Run 1.18.0 ia32; open project/directory that uses git VCS. *Note: The git repository has been properly initialized long ago and git seamlessly used for the project since then.*
2. The `.git` subdirectory can be seen in the seen in the Treeview - `Project` Tab/Pane. The files/folders have correct colors according to their git VCS state (black/green/dark-orange). The branch name is not displayed in the statusbar, as it used to be in the previous versions of Atom. However, the correct branch name can be seen in statusbar for the very short moment when starting Atom before the Atom's GUI gets fully initialized.
3. The `Create repository` button is present in the `Git` Tab/Pane. After clicking on that button the Error popup appears.
```
Unable to initialize git repository in /home/SOME_PATH_HERE_EDITED/006_sandbox

/opt/atom/resources/app/node_modules/dugite/git/bin/git: 1:
/opt/atom/resources/app/node_modules/dugite/git/bin/git:
Syntax error: Unterminated quoted string
```
4. The `Git` Tab/Pane is somewhat blank, see screenshot. There definitely are modified-unstaged files in the project folder, also the modified-staged files; these can be seen in system terminal via `git status` command. These files are not displayed in the Git Tab/Pane in the Atom editor. The `Commit` button is disabled. 
![atom-git](https://user-images.githubusercontent.com/22847930/27520461-816770ac-5a0c-11e7-9f63-9d0a5db0999a.png)
*Note: screenshot taken when Atom running in safe-mode.*

**Reproduces how often:** Always. Tested with multiple directories/projects using Git VCS. When Atom is used for the project/directory that actually is not the git repository (`git init` never ran in the directory; `.git` subdirectory not present in the directory), the steps 3 and 4 can also be reproduced in Atom.

### Versions
```
$ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

$ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 ia32
python 2.7.12
git 2.7.4
```
Ubuntu 16.04 32-bit
Linux 4.4.0-81-generic i686 GNU/Linux

### Additional info

Because the issue has not yet been reported, I suspect the issue could be 32-bit related only or very specific.

**Comment by rsese** [comment]
Thanks for the detailed report @airone506!  The GitHub package has its own repository at https://github.com/atom/github/issues, can you re-open there?
