### ISSUE TITLE
Atom Simply Not Working

### ISSUE THREAD

**Issue by chrisbeberness** [atom/atom#14883]
I went to log into atom today and this is what my terminal looks like:

![image](https://user-images.githubusercontent.com/19434960/27492331-ba402a18-57fa-11e7-99c9-8e0c084656b1.png)

Can someone please let me know how to fix this or what would have caused it. This is the second time this has happened in the last month. I can't do anything in Atom, it won't even let me access the settings!

**Comment by Keydex** [comment]
Please follow these guidelines for reporting your issue. 
https://github.com/atom/language-ruby/blob/master/ISSUE_TEMPLATE.md

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

**Comment by wolass** [comment]
Same here on ubuntu

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

![image](https://user-images.githubusercontent.com/2356167/27507267-c847e00c-58cb-11e7-83ca-80a7608b3ed4.png)

neither beta nor stable releases work on my machine.

**Comment by wolass** [comment]
@chrisbeberness this command worked for me quite well:

```
atom --clear-window-state
```

I'm not sure if this will help you on windows, but it is worth a try.

**Comment by kirillplatonov** [comment]
@wolass has the same issue and it was only with one folder on my computer. You command helped. Thanks a lot.
