### ISSUE TITLE
Upgraded to Debian 9 - libX11.so.6: undefined symbol: xcb_wait_for_reply64

### ISSUE THREAD

**Issue by mkody** [atom/atom#14880]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After upgrading from Debian 8 to Debian 9, I'm not able anymore to start Atom.  
I'm getting this message:  
```
/usr/share/atom/atom --executed-from=/home/kody/dev --pid=9770: symbol lookup error: /usr/lib/x86_64-linux-gnu/libX11.so.6: undefined symbol: xcb_wait_for_reply64
```

Same results with `--safe`.

### Steps to Reproduce

1. Upgrade to Debian 9 and upgrade all packages.
2. Start Atom and get an error in the console.

**Expected behavior:** Atom would open its main window.

**Actual behavior:** Atom doesn't start.

**Reproduces how often:** Everytime.

### Versions

```
$ atom --version

$ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0

$ uname -a
Linux remote 4.4.19-1-pve #1 SMP Wed Sep 14 14:33:50 CEST 2016 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch
```

FYI, I used the latest `.deb` from the website, Atom 1.18.0.

### Additional Information

I tried to remove both `libx11-dev` and `atom` with apt, then install back `libx11-dev` (`apt install libx11-dev`) and atom (`dpkg -i atom*.deb`). This didn't change anything.

**Comment by 50Wliu** [comment]
> FYI, I used the latest .deb from the website, Atom 1.8.0.

Can you please confirm that you meant Atom 1.18.0 and not Atom 1.8.0?

**Comment by mkody** [comment]
@50Wliu Sorry yes, I meant 1.18.0. I updated the issue.

**Comment by a4sriniv** [comment]
I removed `libxcb.so.1` from `/usr/share/atom` and this seemed to fix things. (I'd recommend doing something like `mv /usr/share/atom/libxcb.so.1 /usr/share/atom/libxcb.so.1.bk`, so you can easily revert if it doesn't work.)
