### ISSUE TITLE
Tree View Not Collapsing

### ISSUE THREAD

**Issue by nischkar** [atom/atom#14885]
### Description

[Description of the issue]
The tree view of the panel does not collapse,
the button "collapse" "extend" does not do anything, the treeview stays there.

### Steps to Reproduce

1. Click the "Collapse button" for the Tree view
2. Resize the window automatically using ( win key + right arrow)

**Expected behavior:** [What you expect to happen]
I expect the tree view to collapse so the "code" panel 

**Actual behavior:** [What actually happens]

The tree view stays there, even though i click the collapse button

### Versions
atom: 1.18.0
electron: 1.3.15
node: 6.5.0

### Additional Information
windows 10

**Comment by rsese** [comment]
Thanks for the report!  It would be super helpful if you can completely fill out the issue template, It looks like the Prerequisites section of the template isn't filled out.  Can you confirm if you have the same issue in safe mode (`atom --safe`)? 

Also, I' not sure which buttons you're referring to, can you share a screenshot?

**Comment by nischkar** [comment]
Thanks for the reply,
What i am trying to say is, the tree view is stacked over the code.
As the collapse button did not worked properly, the "code" pane is
below the tree view therefore it is not 100% seen,

**Comment by rsese** [comment]
Thanks for the extra details - can you share a screenshot and let us know if you see the same behavior in safe mode (`atom --safe`)?

**Comment by ghosh** [comment]
@nischkar Do you by any chance have `synced-sidebar` plugin installed? I was having the same issue, disabling `synced-sidebar` fixed it. It seems the plugin has been deprecated.

**Comment by rfiorentino** [comment]
@ghosh - Before removing synced-sidebar I couldn't close the tree view and none of the code windows would display a text cursor. Thanks! That fixed the issue.
