### ISSUE TITLE
Atom Keeps crashing after about a minute of being open MacOS Sierra

### ISSUE THREAD

**Issue by ETGgames** [atom/atom#14899]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
The title says it all

### Steps to Reproduce
Newest version of macos and atom
Open atom
after a minute it will crash after doing nothing.  Tried uninstalling completely and reinstalling.

**Expected behavior:** [What you expect to happen]
no crash
**Actual behavior:** [What actually happens]
crash
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 13r1an** [comment]
Could you please list your system information and atom/apm version? Also, make sure you don't have atom installed twice. Thanks.

**Comment by ETGgames** [comment]
Hardware Overview:

  Model Name:	iMac
  Model Identifier:	iMac14,2
  Processor Name:	Intel Core i7
  Processor Speed:	3.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	24 GB
  Boot ROM Version:	IM142.0118.B44
  SMC Version (system):	2.15f7
  Serial Number (system):	DGKMM01NFLHH
  Hardware UUID:	6B7629F7-FE11-5F09-8CA1-B09F53871103

Atom version 1.18.0
Latest MacOS Sierra 10.12.5

Defo not installed twice.

**Comment by rsese** [comment]
@ETGgames - to check if you might be hitting one of the recently identified issues with the GitHub package:

https://github.com/atom/atom/issues/14806#issuecomment-309077338

Can you confirm if Atom still crashes after temporarily disabling the GitHub package?

**Comment by ETGgames** [comment]
Ah! that seemed to solve the problem! Thanks!

**Comment by rsese** [comment]
Thanks for confirming 👍  If you're hitting one of the specific issues mentioned in that comment I referenced above, you can subscribe for updates if you'd like but if you have a different problem, feel free to open an issue in the GitHub package repository:

https://github.com/atom/github/
