### ISSUE TITLE
Build failed when i try to build on windows 7 using script/build` script

### ISSUE THREAD

**Issue by yoonhyung** [atom/atom#14890]
### Prerequisites

- [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
 - [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
 - [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
 - [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
 - [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Build failed when i try to build on windows 7 using script/build` script

### #Steps to Reproduce

1. go to the `{atom}/script/' directory on windows
2. type the `build` command and execute it.

**Expected behavior:** [What you expect to happen]
- build success

**Actual behavior:** [What actually happens]
```
λ build
Node:   v6.10.3
Npm:    v3.10.5
Python: v2.7.13
Installing script dependencies
Installing apm
Installing modules done
Wrote Dependencies Fingerprint: F:\Home\atom\node_modules\.dependencies-fingerprint 522e392629c5debc77902c467346d6823fdcd4b1
Cleaning F:\Home\atom\out
Copying assets to F:\Home\atom\out\app
Transpiling packages with custom transpiler configurations in F:\Home\atom\out\app
 transpiling for package github
Installing modules done
Transpiling Babel paths in F:\Home\atom\out\app
Transpiling CoffeeScript paths in F:\Home\atom\out\app
Transpiling CSON paths in F:\Home\atom\out\app
Transpiling PEG.js paths in F:\Home\atom\out\app
Generating module cache for F:\Home\atom\out\app
Generating pre-built less cache in F:\Home\atom\out\app\less-compile-cache
Generating metadata for F:\Home\atom\out\app\package.json
Generating API docs at F:\Home\atom\docs\output\atom-api.json
Skipping symbol dumping because minidump is not supported on Windows
Running electron-packager on F:\Home\atom\out\app with app name "atom"
Packaging app for platform win32 x64 using electron v1.6.9
Copying non-ASAR resources to F:\Home\atom\out\Atom x64\resources
Error: ENOENT: no such file or directory, stat 'F:\Home\atom\script\resources\win\atom.cmd'
  at Error (native)
  at Object.fs.statSync (fs.js:1000:11)
  at Object.statSync (F:\Home\atom\script\node_modules\graceful-fs\polyfills.js:297:22)
  at Object.copySync (F:\Home\atom\script\node_modules\fs-extra\lib\copy-sync\copy-sync.js:21:84)
  at forEach.file (F:\Home\atom\script\lib\package-application.js:76:27)
  at Array.forEach (native)
  at copyNonASARResources (F:\Home\atom\script\lib\package-application.js:76:8)
  at runPackager.then (F:\Home\atom\script\lib\package-application.js:50:12)


```

**Reproduces how often:** [What percentage of the time does it reproduce?]
- 100% (when i try to build on windows, always occurred.)

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
```
apm  1.18.1
npm  3.10.10
node 6.9.5 ia32
python 2.7.13
git 2.9.3.windows.1
visual studio 2015
windows 7
atom source target version:  5a8dce117541bef77d3b8404dbc55383cb278f16
```

### Additional Information
I fixed the build script at {atom}/build/lib/package-application.js:74, following

**path.join('resources', 'win', file) => path.join(CONFIG.repositoryRootPath, 'resources', 'win', file)**

**Current version**
```
  } else if (process.platform === 'win32') {
    [ 'atom.cmd', 'atom.sh', 'atom.js', 'apm.cmd', 'apm.sh', 'file.ico', 'folder.ico' ]
      .forEach(file => fs.copySync(path.join('resources', 'win', file), path.join(bundledResourcesPath, 'cli', file)))
  }
```

**Modified version**
```
  } else if (process.platform === 'win32') {
    [ 'atom.cmd', 'atom.sh', 'atom.js', 'apm.cmd', 'apm.sh', 'file.ico', 'folder.ico' ]
       .forEach(file => fs.copySync(path.join(CONFIG.repositoryRootPath, 'resources', 'win', file), path.join(bundledResourcesPath, 'cli', file)))
  }
```

so then, solved the above issue.

**Comment by damieng** [comment]
I think this error occurs for you and not for others because we normally execute `script/build` from the directory above.  Your fix would however appear to let you do it either way so I'll test and try and get it merged.

**Comment by QZSAMA** [comment]
@damieng  I think it did not work either way. I have tried executing both script/build and build in the script folder. I experience the same issue. I think there should be an issue on windows platform about building the project from source.

**Comment by damieng** [comment]
It is building fine here and on every single check-in on our Windows CI server so it's not a Windows-wide issue - it must be environment specific.  Can you open a new issue with your exact console input and output that you get when hitting this?  The original issue on here was a user issue as the script has to be executed from above so I'll close this one down.
