### ISSUE TITLE
Doesn't open file with Russian file name

### ISSUE THREAD

**Issue by borishere** [atom/atom#14894]
### Prerequisites

* [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
* Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
* Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom doesn't open file with Russian file name. It shows blank file instead. Example file name: `русский.txt`

**Actual behavior:** shows blank content

**Reproduces how often:** always

### Versions

Atom    : 1.19.0-beta1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

Windows 10 Enterprise 64-bit

**Comment by rsese** [comment]
Thanks again for reporting @borishere, I can reproduce using the example filename you shared.  I did note that it works ok in 1.18.0 but as you described, the same file is blank as of 1.19.0-beta0.

**Comment by rsese** [comment]
Seems like I can't reproduce on macOS 10.12.5 and the report in https://github.com/atom/atom/issues/14896 was also on Windows.

**Comment by AragurDEV** [comment]
It's still a thing on 1.19.0-beta1 with Windows 10 (Creator Update)

**Comment by maxbrunsfeld** [comment]
Yeah, the native buffer work almost definitely caused this.

**Comment by maxbrunsfeld** [comment]
@borishere @AragurDEV Sorry about this. I'm fixing it now and I think we will get a hotfix release out on Monday.

**Comment by maxbrunsfeld** [comment]
I've published 1.19.0-beta3, which contains the fix. Please let me know if you have any more problems!

**Comment by borishere** [comment]
@maxbrunsfeld I moved back to 1.18 because I'm tired of bugs in beta :)

**Comment by AragurDEV** [comment]
@maxbrunsfeld Okay it's working fine now.
Thank you 👍
