### ISSUE TITLE
The editor is not responding on Mac OS X

### ISSUE THREAD

**Issue by ozarchie** [atom/atom#14902]
**System Macbook Pro
macOS Sierra V10.12.5**

I have just upgraded PlatformIO IDE to 2.0.0-beta,6, Core 3.4.0rc1
Atom reports 1.18.0 x64
I opened one of the sample apps for ESP32 and ...

![screen shot 2017-06-26 at 14 02 18](https://user-images.githubusercontent.com/6479143/27565961-0a3800fe-5b25-11e7-9f9e-39497a40a827.png)

I have disabled spell checking.

Here is the dump from the activity monitor for the Atom Helper that is using the time:

`cwd / txt /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper txt /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework txt /Applications/Atom.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel txt /Applications/Atom.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa txt /Applications/Atom.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle txt /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib txt /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib txt /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/en.lproj/locale.pak txt /System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI txt /usr/lib/libexpat.1.dylib txt /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/natives_blob.bin txt /usr/share/icu/icudt57l.dat txt /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/icudtl.dat txt /usr/lib/dyld txt /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/snapshot_blob.bin txt /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/content_shell.pak txt /System/Library/Extensions/GeForceTeslaGLDriver.bundle/Contents/MacOS/GeForceTeslaGLDriver txt /System/Library/Extensions/GeForceTeslaGLDriver.bundle/Contents/MacOS/libclh.dylib txt /private/var/db/dyld/dyld_shared_cache_x86_64 0 /dev/null 1`

HTH

**Comment by ozarchie** [comment]
I think it has something to do with outstanding github files, but I am not sure ....

![screen shot 2017-06-27 at 11 31 08](https://user-images.githubusercontent.com/6479143/27567206-ca2a5814-5b2d-11e7-920d-a83d0bc44bb3.png)

Notice the 600000+ files at the bottom. They are not there on the initial screen but appear after the first editor message.

![screen shot 2017-06-27 at 11 44 49](https://user-images.githubusercontent.com/6479143/27567547-cba8b08a-5b2f-11e7-8341-5674e91962e7.png)


![screen shot 2017-06-27 at 11 30 00](https://user-images.githubusercontent.com/6479143/27567224-e9792a88-5b2d-11e7-9474-965877fc7f44.png)


```
- I have a github account.
- I have logged into Atom
- I have followed the github authorization procedure
```


![screen shot 2017-06-27 at 11 32 02](https://user-images.githubusercontent.com/6479143/27567443-16ad2c10-5b2f-11e7-911b-fbe48e001742.png)
![screen shot 2017-06-27 at 11 32 15](https://user-images.githubusercontent.com/6479143/27567457-27ff6e06-5b2f-11e7-9cd7-9e1d79ee0d62.png)

The number keeps ?growing/?changing -


![screen shot 2017-06-27 at 11 53 56](https://user-images.githubusercontent.com/6479143/27567511-8c6cef12-5b2f-11e7-988a-96b9f8cb431d.png)

**Comment by rsese** [comment]
Thanks for the report @ozarchie - do you happen to have a `.git` directory in your home directory?   /cc https://github.com/atom/github/issues/984 where someone reported similar behavior.

**Comment by ozarchie** [comment]
Hi rsese,
Yep .. that was the problem.
My apologies for making extra work for you.
Cheers Archie

**Comment by rsese** [comment]
No problem at all, glad we found the issue :v:  If you're interested, I believe this issue is tracking the problem /cc https://github.com/atom/github/issues/959.
