### ISSUE TITLE
Github tab won't authenticate 

### ISSUE THREAD

**Issue by TristanBrotherton** [atom/atom#14917]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

"Unknown error" shown when trying to connect to private repository on github with an API token

### Steps to Reproduce

1. Add api token to Atom 
2. Click next button
3. Error is shown

**Expected behavior:** [What you expect to happen]
The github tab to connect to git hub
**Actual behavior:** [What actually happens]
Unknown error is shown:

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

* **Atom:**       1.19.0-beta2
* **Atom-Shell:** 
* **OS:**         Mac OS X 10.12.5
* **Misc**
    * apm  1.18.2
    * npm  3.10.10
    * node 6.9.5 x64
    * python 2.7.10
    * git 2.11.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ungb** [comment]
@TristanBrotherton, I'm going to dup this issue to https://github.com/atom/github/issues/819 that's filed on github repo as it looks similar.  Currently, the github tab is still in `preview` and has some quirks that need to work out like these.
