### ISSUE TITLE
npm WARN enoent ENOENT: no such file or directory - when installing packages

### ISSUE THREAD

**Issue by mbrancato** [atom/atom#14913]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I recently updated to 1.18 with the Windows installer - note I am running as a non-Administrator on a corporate system. This changed the way I had previously installed to now installed in `$HOME\AppData\Local` which is great. My existing packages survived, but I was getting  errors when updating packages. I also cannot install packages. I can reproduce this reliably and I have reset to factory defaults (removed `.atom\`) and this problem persists.

The error appears to be related to the failed creation of the "apm-install" directory under `$HOME\AppData\Local\Temp\`.

### Steps to Reproduce

1. Click `Install` on any community package
2. Wait

**Expected behavior:** Package installs

**Actual behavior:** Install fails

**Reproduces how often:** 92.732%

This might reproduce 40 times in a row, then work 4 in a row. 

### Versions

`>atom --version`
> 
>Atom    : 1.18.0
>Electron: 1.3.15
>Chrome  : 52.0.2743.82
>Node    : 6.5.0

`>apm --version`
>apm  1.18.1
>npm  3.10.10
>node 6.9.5 x64
>python
>git
>visual studio

### Additional Information

Error output from failed install:

> Installing “vim-mode-plus@0.93.0” failed.Hide output…
> C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi
> `-- (empty)
> 
> 
> npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\package.json'
> npm WARN apm-install-dir-117528-20320-xdopcx.9igkl0udi No description
> npm WARN apm-install-dir-117528-20320-xdopcx.9igkl0udi No repository field.
> npm WARN apm-install-dir-117528-20320-xdopcx.9igkl0udi No README data
> npm WARN apm-install-dir-117528-20320-xdopcx.9igkl0udi No license field.
> npm ERR! Windows_NT 10.0.10586
> npm ERR! argv "C:\\Users\\username\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\username\\AppData\\Local\\atom\\app-1.18.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\username\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\username\\.atom\\.apmrc" "install" "C:\\Users\\username\\AppData\\Local\\Temp\\d-117528-20320-15ra7t7.j2pxecdi\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! path C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\node_modules\vim-mode-plus
> npm ERR! code EPERM
> npm ERR! errno -4048
> npm ERR! syscall rename
> 
> npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\node_modules\vim-mode-plus' -> 'C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\node_modules\.vim-mode-plus.DELETE'
> npm ERR!     at moveAway (C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:38:5)
> npm ERR!     at destStatted (C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:27:7)
> npm ERR!     at C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
> npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
> npm ERR! 
> npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\node_modules\vim-mode-plus' -> 'C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\node_modules\.vim-mode-plus.DELETE'
> npm ERR!     at Error (native)
> npm ERR!  Error: EPERM: operation not permitted, rename 'C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\node_modules\vim-mode-plus' -> 'C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\node_modules\.vim-mode-plus.DELETE'
> npm ERR!     at moveAway (C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:38:5)
> npm ERR!     at destStatted (C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\apm\node_modules\npm\lib\install\action\finalize.js:27:7)
> npm ERR!     at C:\Users\username\AppData\Local\atom\app-1.18.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:267:18
> npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
> npm ERR! 
> npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\node_modules\vim-mode-plus' -> 'C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\node_modules\.vim-mode-plus.DELETE'
> npm ERR!     at Error (native)
> npm ERR! 
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\Users\username\AppData\Local\Temp\apm-install-dir-117528-20320-xdopcx.9igkl0udi\npm-debug.log
> npm ERR! code 1

**Comment by Extarys** [comment]
Seems like atom doesnt have the right to write to that folder.
It's not necessarily Atom's fault though (It might also be :P)

[npm - EPERM: operation not permitted on Windows on Stackoverflow](https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows)

From [Microsoft blog](https://blogs.msdn.microsoft.com/matt-harrington/2012/02/23/how-to-fix-node-js-npm-permission-problems/):

> It turns out that you don’t have to run the command again as Administrator, and doing so won’t fix the problem.  Try `npm cache clean` first.  If that doesn’t fix things, take a look in `%APPDATA%\npm-cache`, or if you’re using _PowerShell_, `$env:APPDATA\npm-cache`.  After cleaning the cache, you may still be left with remnants.  Manually remove everything in that directory, and try again.  This has always fixed things for me.

Hope it helps!

**Comment by pabloazurduy** [comment]
Same error here, 
I also tryed with the @Extarys aproach but fail. I couln't install any package from the console or in the UI.
