### ISSUE TITLE
Atom always starts maximized

### ISSUE THREAD

**Issue by ffxsam** [atom/atom#14926]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom window starts maximized regardless of its previous location and width/height when quitting.

### Steps to Reproduce

1. Open Atom (`atom .`)

**Expected behavior:** [What you expect to happen]

Expected the window to open up with its previous state (unmaximized) with the previous location and width/height.

**Actual behavior:** [What actually happens]

Window is maximized.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time.

### Versions

```
OS: Ubuntu GNOME 17.04
Display: UHD 3840x2160
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0
```

**Comment by rsese** [comment]
I'm unable to reproduce on Ubuntu 16.04 and Atom 1.18.0 - just to confirm, if you:

1. Start Atom with `atom .`
2. Change the window position and size.
3. Click outside the Atom window (e.g. click the desktop).
4. Close Atom.
5. Start Atom with `atom .`

Does Atom still open maximized?

**Comment by ffxsam** [comment]
Please leave this open, I'll revisit this when I get a chance! (might be a couple weeks)

**Comment by alflanagan** [comment]
Are other apps opening maximized, or just Atom? If it's most apps, there's a gnome setting that controls this:
```
$ gsettings get org.gnome.mutter auto-maximize
true
$ gsettings set org.gnome.mutter auto-maximize false
```

**Comment by rsese** [comment]
Thanks @alflanagan :v:  

Cross referencing the issue I was thinking about /cc https://github.com/atom/atom/issues/13909.

**Comment by ffxsam** [comment]
Ok, this is no longer occurring. Actually, I switched to regular Ubuntu 17.04 (Unity). I'll reopen this next year if it's still an issue in 18.04 LTS when GNOME is the default environment.
