### ISSUE TITLE
Uncaught TypeError: this.resolveReady is not a function

### ISSUE THREAD

**Issue by FreddieOD** [atom/atom#14921]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.resolveReady is not a function

```
At /home/andrei/atom-1.11.1/out/app/node_modules/tree-view/lib/file.coffee:94659

TypeError: this.resolveReady is not a function
  at emitter.on (<embedded>:94659:18)
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63156:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63272:34)
  at EventEmitter.handleMessages (<embedded>:94649:28)
  at emitTwo (events.js:111:20)
  at EventEmitter.emit (events.js:191:7)

```

### Commands

```
```

### Non-Core Packages

```
nuclide 0.158.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by FreddieOD** [comment]
Dear Robert Sese

Thank you for your response. To answer your questions in order

1) I am opening a file within the app.
2) Yes it is reproducible. All I need to do is open a file
3) I can not longer open atom from my command line. It became unimaginably
slow. I have to open it from ubuntu's application tab bar (a little trick I
got from a forum of people with the same problem). No idea how to open it
in safe mode from this interface.

Kind regards
Freddie

**Comment by FreddieOD** [comment]
to clarify point (1) I am opening up the a file within atom I get the error.

**Comment by rsese** [comment]
Thanks for the details 👍  Since you mentioned slowness, just to rule out the GitHub package which is a core package in stable as of 1.18.0, can you disable the GitHub package and let me know if Atom is still slow after that?

You can do this from the command line with:

```
apm disable github
```

**Comment by camelscript** [comment]
I can confirm Atom 1.18.0
My error pops up, when i change focus by clicking in to file content. 
![image](https://user-images.githubusercontent.com/2886840/27966874-86d50f04-6349-11e7-88a3-8d49987a2b4f.png)
