### ISSUE TITLE
Packages aren't updated

### ISSUE THREAD

**Issue by Eremiteb** [atom/atom#14925]
Atom 1.18.0 x64 on Windows 7 x64.
Updating to “linter@2.2.0” failed.Hide output…
Unable to download https://www.atom.io/api/packages/linter/versions/2.2.0/tarball: unable to verify the first certificate.
The same in updating attempt linter-ui-default to 16.2 
The same with other packages too

**Comment by rsese** [comment]
Thanks for the report!  This might be a better issue for https://github.com/atom/apm, can you re-open this issue there?  When you do, please completely fill out the issue template and share any more details that might be helpful to know (e.g. are you behind a firewall or using a proxy?).
