### ISSUE TITLE
Atom freezes intermittently whenever I have any project folder

### ISSUE THREAD

**Issue by jakecabrera** [atom/atom#14936]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom consistently hangs up/ freezes whenever I have a project folder or had one since it has been open. Happens even in safe mode. I've checked many threads and none of them had a solution for my problem, nor did they fit my description well. I've already uninstalled and reinstalled atom, tried the beta, cleared the window state, deleted my .atom folder, upgraded my graphics drivers, disabled and uninstalled all packages, commented out my entire init file, and disabled my anti-virus.

### Steps to Reproduce

1. Start atom without any project folders or files open.
2. Click around and open settings, switch tabs, write some code; no freezing, works flawlessly.
3. File > add project folder (Happens with every folder I have tried)
4. Step 2 again, every 10 seconds or so, haven't timed it, Atom will just freeze completely.
5. Remove project folder that was added in step 3
6. Repeat step 2 again and find that the results are the same as those from step 4.

**Expected behavior:** [What you expect to happen]
No freezing

**Actual behavior:** [What actually happens]
Freezing

**Reproduces how often:** [What percentage of the time does it reproduce?]
50% of the time I have a project folder

### Versions
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 3.6.1
git 2.8.0.windows.1
visual studio
Windows 10 64bit

### Additional Information

Below is the cpuprofile I saved when I was reproducing the issue. In this profile, atom froze up 4 times, which I think is conveyed through the cpu profile if that helps. I also get the error `Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError` whenever I start up Atom.

[CPU-20170701T155442.zip](https://github.com/atom/atom/files/1117469/CPU-20170701T155442.zip)

**Comment by Nataniel4** [comment]
I have the same issue, I checked the activity monitor on Mac and the Atom Helper process is using +100% of CPU! A kind of loop script can't find his road?

**Comment by jakecabrera** [comment]
For me, when this freezing occurs, atom does indeed use a lot of my cpu as compared to regular use, jumps up to like 15% when it is normally at under 1%, but I don't have it using +100%

**Comment by danieldelouya** [comment]
Atom constantly jumps to 100% CPU for me, even in safe mode, and when it does, it becomes completely unresponsive.

**Comment by rsese** [comment]
There were 3 specific issues related to the GitHub package there were pulled from this recent issue, see the summary comment here:

https://github.com/atom/atom/issues/14806#issuecomment-309546499

Can folks confirm if you still see Atom freezing/high CPU usage after disabling the GitHub package?  If so, then  this is a duplicate of issues like https://github.com/atom/atom/issues/14877 and https://github.com/atom/atom/issues/14871.

**Comment by BNoiZe** [comment]
I had the exact same problem with atom freezing for about 10sec every few seconds. Disabling the GitHub package fixed the issue.

**Comment by jakecabrera** [comment]
Disabling the GitHub package fixed the issue for me too.

Thanks very much, I appreciate the help!
