### ISSUE TITLE
Atom-beta icon looks weird under macOS 10.13-beta

### ISSUE THREAD

**Issue by ooJerryLeeoo** [atom/atom#14932]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom-beta icon looks weird under macOS 10.13-beta.

### Steps to Reproduce

- Just install macOS 10.13-beta

**Expected behavior:**

![screen shot 2017-07-01 at 14 16 45](https://user-images.githubusercontent.com/20783502/27759642-f0905282-5e67-11e7-8b5c-3ad06ce9e9f9.png)

**Actual behavior:**

![screen shot 2017-07-01 at 14 12 24](https://user-images.githubusercontent.com/20783502/27759619-a9254dee-5e67-11e7-8b89-a0a60eb034c6.png)

### Versions

`atom`: `1.19.0-beta2`  
`OS`  : `10.13-beta`

**Comment by sadovnychyi** [comment]
Is it somehow fixed?

**Comment by ooJerryLeeoo** [comment]
No, I just think this isn't atom's problem.

**Comment by darkermatter** [comment]
The images are washed out in the Resources/atom.icns file. I downloaded the PNG files from https://github.com/atom/atom/tree/master/resources/app-icons/beta/png and manually made an atom.icns file and the colours are fine.

It's possible that this is related to #13672  and ```iconutil``` on 10.13 fixes it.

**Comment by jeffgeorge** [comment]
I can confirm this is still an issue on Atom 1.21.0-beta1 on macOS 10.13 GM.

**Comment by dresende** [comment]
https://github.com/jbergstroem/atom-icon
