### ISSUE TITLE
Unable to install a package.

### ISSUE THREAD

**Issue by beckno9** [atom/atom#14933]
Well, I just installed Atom, I tried to install a language pack but it shows "install failed".  
Here's the picture:
![Picture](https://image.ibb.co/eSg0q5/pic1.png)  
Seems it shows that it can't found a compiler, but I have Visual Studio 2017 installed already, so that makes this problem.  
I have both tried to install with command-line or in the package manager, I always get the error message:  
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.3.15/iojs-v1.3.15.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: self signed certificate
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
gyp ERR! stack     at emitNone (events.js:86:13)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:603:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\BeckNo9\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\BeckNo9\\AppData\\Local\\atom\\app-1.17.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.3.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\BeckNo9\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```
Please help me!  

Using OS: Windows 10 Build 15063  
Visual Studio: 2017

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/apm if there's no existing issue already so we have it in the right place?  Please use the issue template as much as possible as well (e.g. please share the output of `atom -v` and `apm -v`).

If you could also share as much information about your network setup (e.g. are you behind a firewall or using a proxy?), that would be helpful.
