### ISSUE TITLE
Docs do not mention getAllowedLocations() for Pane Items

### ISSUE THREAD

**Issue by RobertBColton** [atom/atom#14949]
So ``getAllowedLocations`` is mentioned in the [Atom flight manual](http://flight-manual.atom.io/hacking-atom/sections/package-active-editor-info/#constraining-our-items-locations), but it's not mentioned elsewhere in the docs. I thought I could implement just ``getDefaultLocation`` without having to also implement ``getAllowedLocations``, but I get the following in the developer tools:

`C:\Users\Owner\AppData\Local\atom\app-1.18.0\resources\app\node_modules\tabs\lib\layout.js:159 Uncaught TypeError: Cannot read property 'getAllowedLocations' of undefined`

It's also not clear to me if I can simply return ``'all'`` from ``getAllowedLocations``. The docs should explain both of these functions and specify that you have to provide both if you provide the other.

**Comment by iolsen** [comment]
@nathansobo do you have any concerns about this API becoming officially public, being as it's been unofficially public for a while now?

**Comment by nathansobo** [comment]
@iolsen I'm down to make it public and document it.

**Comment by lee-dohm** [comment]
We should probably fully document all of the "mystery functions" on various objects packages can create like Panes or PaneItems.

**Comment by trangngo1801** [comment]
#20204

**Comment by Destop-Trang1801** [comment]
getAllowedLocations
