### ISSUE TITLE
Windows 10 second taskbar icon

### ISSUE THREAD

**Issue by Daijobou** [atom/atom#14958]
I have in Windows 10 a pinned taskbar icon for Atom. After start Atom there is now a second icon in taskbar. It should use the pinned icon, not create a new one in taskbar, like all other programs. :)

Windows 10 Home x64

**Comment by flofriday** [comment]
I run also Windows 10 and on my system, it uses the pinned icon. Have you tried to repin it or reinstall atom at all? Furthermore, do you run the latest version of Atom?

**Comment by Daijobou** [comment]
Oh. crazy... its working. Thank you very much! :)

I use atom 1.18.0 (I updated yesterday windows 10 to creators update)
