### ISSUE TITLE
Installation has failed (Windows 10)

### ISSUE THREAD

**Issue by jlchavarriaga** [atom/atom#14953]
2017-07-04 13:19:30> Unhandled exception: System.IO.FileNotFoundException: No se puede cargar el archivo o ensamblado 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.
Nombre de archivo: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   en Squirrel.Update.Program.executeCommandLine(String[] args)
   en Squirrel.Update.Program.main(String[] args)

=== Información de estado anterior al enlace ===
LOG: DisplayName = PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Engineer/AppData/Local/SquirrelTemp/
LOG: PrivatePath inicial = NULL
Ensamblado de llamada : Update.exe, Version=1.7.5.0, Culture=neutral, PublicKeyToken=null.
===
LOG: Este enlace empieza en el contexto de carga default.
LOG: No se encontró ningún archivo de configuración de la aplicación.
LOG: Utilizando el archivo de configuración de host: 
LOG: Utilizando el archivo de configuración del equipo en C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Referencia posterior a la directiva: PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Intento de descarga de la nueva dirección URL file:///C:/Users/Engineer/AppData/Local/SquirrelTemp/PresentationFramework.DLL.
LOG: Intento de descarga de la nueva dirección URL file:///C:/Users/Engineer/AppData/Local/SquirrelTemp/PresentationFramework/PresentationFramework.DLL.
LOG: Intento de descarga de la nueva dirección URL file:///C:/Users/Engineer/AppData/Local/SquirrelTemp/PresentationFramework.EXE.
LOG: Intento de descarga de la nueva dirección URL file:///C:/Users/Engineer/AppData/Local/SquirrelTemp/PresentationFramework/PresentationFramework.EXE.

windows 10 pro  64 bits
Version 1703

**Comment by damieng** [comment]
Are you sure this is from Atom?  Many apps use Squirrel and we do not use PresentationFramework.
