### ISSUE TITLE
Editor hangs/freeze with open a big (~4MB) file that only have a single long line

### ISSUE THREAD

**Issue by Daijobou** [atom/atom#14952]
First, thanks for your great work! I love this editor. :)

### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Editor hangs with open a 5MB json-file, but it open successful a other 6MB json-file.

### Steps to Reproduce

Start atom and open (my) ~5MB json-file

**Expected behavior:** [What you expect to happen]

Loading the json-file. Other editors load it all in <1s

**Actual behavior:** [What actually happens]

Atom hangs with no response, so windows ask to wait or to close it. I have waited multiple times, never come back. CPU process is ~20% and RAM ~500MB.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

I think here is something in the file that atom not like. Other bigger files working fine. The difference here is that the file with issue is a single line json. Maybe that here the problem?

**Comment by rsese** [comment]
Thanks for the report!  Can you share what operating system you're running?  Also, would you be able to share the file that's causing the hang so we can try it out?

**Comment by Daijobou** [comment]
It's Windows 10 64bit. You only need a single line file like this code:

[{"FieldA":1,"FieldB":"Text","FieldC":"Text"},{"FieldA":1,"FieldB":"Text","FieldC":"Text"},,.....]

I have add a example as "TXT", you must rename it to "JSON" as file-type. I can't upload json here.

[atom_test.txt](https://github.com/atom/atom/files/1168290/atom_test.txt)

**Comment by Zireael07** [comment]
@Daijobou: You said the file is a single line. Does the problem happen if it's plain text (i.e. no syntax highlighting)?

**Comment by Daijobou** [comment]
I have tested it and yes, a plain text file have this problem too.

**Comment by 50Wliu** [comment]
Okay, I just tested on Atom 1.20.0-dev-cb08c1b87 and the file takes around 10 seconds to open and is pretty laggy afterwards.

**Comment by rsese** [comment]
Same on 1.19.1 - after opening, moving through that file is laggy for me too but Atom doesn't hang with no response.  @Daijobou can you update and let us know if Atom still hangs for you?

**Comment by Daijobou** [comment]
Atom 1.25.0: With my testfile (upload above) editor show messagebox with not responsing after waiting for 10-20s.
After click waiting-button in messagebox the file show up. So its working now but the scrolling in this file is very laggy.

**Comment by cutephoton** [comment]
On 1.34, Atom grinds to a halt when opening files with long lines. It eventually comes back to life.

Sadly, this is a common problem with many of the text editors I've used.

**Comment by nathansobo** [comment]
Fixed via https://github.com/atom/text-buffer/pull/312 and https://github.com/atom/atom/pull/19453.
