### ISSUE TITLE
Recreate template ~/.atom files when opened and non-existent

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#1495]
If something goes to `Open Your Keymap` and the file does not exist because they accidentally deleted it, it should recreate the file with the sample content.

Open it just as a blank editor prevents the person from reading the docs in the template file and seeing an exapmle.

**Comment by joeytwiddle** [comment]
I just tried Atom for the first time, on Ubuntu 12.04.

The "Welcome Guide" suggested I open the stylesheet and init script, and uncomment examples.

But when I clicked the blue buttons to open them, the files were blank - no comments, no examples.

**Comment by lee-dohm** [comment]
@joeytwiddle Did you download Atom from the website? Or did you use a package manager to install it?

**Comment by joeytwiddle** [comment]
Yeah it was from the PPA `ppa.launchpad.net_webupd8team_atom_ubuntu_trusty_main_binary-amd64_Packages`. Probably version 1.16.0. I haven't tried it again recently.
