### ISSUE TITLE
Let apm list only enabled packages 

### ISSUE THREAD

**Issue by pabloab** [atom/atom#14961]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

As [@lee-dohm  say here](https://discuss.atom.io/t/installed-packages-list-into-single-file/12227/19) right now `apm` let you list installed packages with `apm list --installed --bare > package-list.txt` (for backup or to install same packages on several computers with `apm install --packages-file package-list.txt`).
Would be greatly appreciated a `--enabled` parameter to list only enabled installed packages, the ones we really use. With the huge amount of packages out there is very common to install/try some and then just disable them to give another try later instead of uninstalling it, so the difference between the list of installed and the subset of enabled could be really big.

### Steps to Reproduce

1. Go to terminal
2. Run `apm list --installed --bare --enabled`

**Expected behavior:** List **only** installed enabled packages.

**Actual behavior:** List all installed packages.

**Reproduces how often:** 100%

### Versions

    $ lsb_release -d
    Description:    Ubuntu 16.04.2 LTS

    $ atom --version
    Atom    : 1.13.1
    Electron: 1.3.13
    Chrome  : 52.0.2743.82
    Node    : 6.5.0

    $ apm --version
    apm  1.14.1
    npm  3.10.5
    node 4.4.5
    python 2.7.12
    git 2.7.4

**Comment by rsese** [comment]
Thanks @pabloab :bow:  I couldn't have sworn there's an existing issue for this request but couldn't find it.  If you don't mind, can you re-open in https://github.com/atom/apm so we have it in the right place?

**Comment by pabloab** [comment]
Sorry, my mistake @rsese, reopened on [apm](https://github.com/atom/apm/), issue [#732](https://github.com/atom/apm/issues/732).
