### ISSUE TITLE
Alt-H shortcut on macOS overrides ₽ symbol in Russian keyboard layout

### ISSUE THREAD

**Issue by pepelsbey** [atom/atom#14965]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Alt-H shortcut on macOS overrides ₽ symbol (ruble currency sign) in Russian keyboard layout. So it’s impossible to type ₽ symbol in Atom. See ₽ on top right corner of H key on Russian keyboard layout: 

![image](https://user-images.githubusercontent.com/105274/27917196-f8979232-6273-11e7-89c0-7243a05896f9.png)

### Steps to Reproduce

1. Switch to Russian keyboard layout
2. Press Alt H

**Expected behavior:**

₽ symbol.

**Actual behavior:**

Word deleted.

**Reproduces how often:**

100%

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.2

macOS Sierra 10.12.5 (16F73)

### Additional Information

Because of this Alt-H shortcut [dot above](http://www.fileformat.info/info/unicode/char/02d9/index.htm) unicode symbol is also not available in English layout.

**Comment by rsese** [comment]
Thanks for the report!  It seems like there was a similar discussion here?

https://github.com/atom/atom/issues/4057

For macOS, you can add this to your keymaps file to unmap <kbd>alt-h</kbd>:

```
'atom-text-editor':
   'alt-h': 'unset!'
```

Going to go ahead and close since this can be worked around but let me know if I mis-understood anything.

**Comment by pepelsbey** [comment]
This is a default behaviour that breaks built-in shortcuts drawn on every Russian Mac keyboards. Do you really suggesting every Russian user to look for this workaround and apply it, instead of fixing it by default? I mean, why wouldn’t you map `Shift 4` for this? It would disable `$` symbold, but why not, it could be fixed. Or `Shift Option 2`, who needs `€` anyway.
