### ISSUE TITLE
Atom 1.18 Constantly Freezing

### ISSUE THREAD

**Issue by rubinca** [atom/atom#14971]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Using the app
**Expected behavior:** No idea

**Actual behavior:** The app constantly freezes and then crashes

**Reproduces how often:** Every time I open it

### Versions

atom version 1.18, mac version 10.11.6 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by maxbrunsfeld** [comment]
Does disabling the `github` package fix the issue for you?

**Comment by teekayx** [comment]
I have the same issue with fresh installs of Atom 1.18 on my MBP MacOS 10.12.5. Safe mode and uninstall / reinstall did not fix the issue. Couple of Atom Helper processes consume about ~1.5gb memory. Didn't install any packages, just out-of-the-box use.

**Comment by maxbrunsfeld** [comment]
@teekayx If you disable the built-in `github` package, does it prevent Atom from freezing?

**Comment by teekayx** [comment]
Thanks @maxbrunsfeld the memory still seems to hog ~500mb (~375mb by Atom Helpers) but its seamless now, no longer lugs.

**Comment by NidhoggC** [comment]
same problem, disable 'github'package will be fine

**Comment by thierryc** [comment]
same problem, disable 'github' package fix it for the moment !

**Comment by sijpkes** [comment]
Disabling github package does work.  I use @akonwi 's git-plus package instead.  The built in version looked nicer and seemed to have some cool features. I hope it goes stable soon!

**Comment by rsese** [comment]
One thing to check for is if you might accidentally have a `~/.git` repository in your home directory which seems to be related to https://github.com/atom/github/issues/959.  If you find that's the case and you didn't intend it, you can remove the directory or to be safe, just move it:

```
mv ~/.git ~/.git-backup
```

Additionally, there's been a few issues identified with the GitHub package detailed here:

https://github.com/atom/atom/issues/14806#issuecomment-309546499

If you have a [crash log](http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs) that matches up with one of those issues, you can subscribe for updates.

@rubinca - since you opened the issue, can you confirm if Atom still freezes for you after temporarily disabling the GitHub package?  And if so, do you have a `~/.git` directory in your home directory?

**Comment by Jinksi** [comment]
@rsese thanks, your solution worked for me

**Comment by DonkeyAfterDark** [comment]
Removing the package "PIGMENTS" (v0.39.1) by abe33 solved the lockups for me!

**Comment by simurai** [comment]
Here possibly a related issue for Pigments package: https://github.com/abe33/atom-pigments/issues/308

**Comment by rsese** [comment]
Thanks again for your issue @rubinca - we haven't received a response to our question in this comment https://github.com/atom/atom/issues/14971#issuecomment-316492371 so with only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

---

If anyone else is still having a problem that's separate from the GitHub package or other known issues like the Pigments issue, feel free to open a new issue and completely fill out the issue template so we can take a look.
