### ISSUE TITLE
Feature - keymap cross OS

### ISSUE THREAD

**Issue by XinYang-Pan** [atom/atom#14979]
I was thinking if it was a good idea to have cross OS keymap for Mac and Windows, and the Common keymap for both.

It would be like this.

- _keymap.cson_ still serve as it is now. it's the common keymap config
- _keymap-mac.cson_ for mac only keymap config, it override the _keymap.cson_
- _keymap-win.cson_ for windows only keymap config, it override the _keymap.cson_

I came up with this when I was using sync-settings.

**Comment by 50Wliu** [comment]
This is already possible.  The `.platform-darwin`, `.platform-linux`, and `.platform-windows` selectors are available on their respective platforms.
