### ISSUE TITLE
Windows V1.18.0 x64 - Self signed certifictate in certificate chain

### ISSUE THREAD

**Issue by bagoette** [atom/atom#14977]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Brand new install, first time user. Right when I open the program in regular or safe mode, the +Install screen says 'self signed certificate in certificate chain' in the Featured Packages section and when I try to search. Picture included. So I am unable to install packages. I've also tried from the command line using apm install. I've searched multiple threads that have this issue but all of the solutions already match my setup like checking environment variables and so on.
![image](https://user-images.githubusercontent.com/22378341/27980254-4a9b1c88-6342-11e7-81ce-5f9494919c5e.png)

### Steps to Reproduce

1. Open program
2. Go to +Install page

**Expected behavior:** Search and install packages

**Actual behavior:** Error

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

C:\Users\<user>>apm -version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python
git 2.10.2.windows.1
visual studio 2015

C:\Users\<user>>atom --version

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

Windows 7 x64

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lee-dohm** [comment]
Please see the [Atom FAQ](https://discuss.atom.io/c/faq) entry about [self-signed certificates](https://discuss.atom.io/t/im-getting-an-error-about-a-self-signed-certificate-what-do-i-do/39040).
