### ISSUE TITLE
Atom 1.18 Crashing

### ISSUE THREAD

**Issue by MyloTuT** [atom/atom#14973]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Atom is reporting "The editor has crashed please report this to https://github.com/atom/atom]

### Steps to Reproduce

1. Open Atom
2. Wait for 1 - 2 minutes
3. Atom crashes and provides a please report warning

**Expected behavior:** [What you expect to happen]
I expect it to work. 
**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time.
### Versions
1.18.0
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
@MyloTuT - to check if you might be hitting one of the recently identified issues with the GitHub package:

https://github.com/atom/atom/issues/14806#issuecomment-309077338

Can you confirm if Atom still crashes after temporarily disabling the GitHub package?

Also, can you share any crash logs?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs

**Comment by ziazek** [comment]
After disabling the GitHub package, Atom still crashes after a few minutes. 

Crash log: https://gist.github.com/ziazek/197ecda36871ee993b94951bcceb84d1

**Comment by rsese** [comment]
Thanks again for your issue @MyloTuT!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/14973#issuecomment-314565108. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by rsese** [comment]
@ziazek - can you open another issue and fill out the issue template?  You can drop the crash log link in the additional info section too (thanks for grabbing that).

**Comment by MyloTuT** [comment]
I’m currently working fine after disabling. Sorry for the late response.

**Comment by rsese** [comment]
No problem @MyloTuT - oh and one thing to check for is if you have a `.git` directory in your home directory.  If you do and it's unintentional, you can move it out of the way:

```
mv ~/.git ~/.git-backup
```
