### ISSUE TITLE
atom-beta: file added to .gitignore shows up in unstaged changes list

### ISSUE THREAD

**Issue by AFTERWAKE** [atom/atom#14984]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using this repository: https://github.com/AFTERWAKE/IRCBots
I added a file(theCount/scores.txt) to my .gitignore file, and when any changes are made to it, in atom-beta on the git preview panel, scores.txt shows up under Unstaged Changes.

### Steps to Reproduce

1. Clone repo
2. Open in atom-beta
3. Open Git preview panel
4. Make change to scores.txt
5. Notice that the file shows up in git preview, even though it is in .gitignore and the filename is text-muted on the file tree view.

**Expected behavior:** File should not show up on Unstaged changes if anything is changed in it. It works for the other file in the .gitignore.

**Actual behavior:** Supposedly ignored file shows up on unstaged changes list.

**Reproduces how often:** Just noticed it for this file, does not happen to a .pyc file I have set to ignore.

### Versions

```
nsiano@cn-vm-nsiano:~/Downloads$ atom-beta -v
Atom    : 1.19.0-beta3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
nsiano@cn-vm-nsiano:~/Downloads$ apm -v
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.6
git 1.9.1
```

Running inside an Ubuntu 14.04 LTS virtual machine on VirtualBox:
```
nsiano@cn-vm-nsiano:~/Downloads$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
```

### Additional Information

This is for Atom Beta v1.19. Happens in safe mode as well.

**Comment by lee-dohm** [comment]
Since, as described, this would be a bug in the github package, would you mind filing this on https://github.com/atom/github?
