### ISSUE TITLE
Atom doesn't reflect changes in environment for subsequent invocations of `atom .`

### ISSUE THREAD

**Issue by flawedmatrix** [atom/atom#14986]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm running Atom on Windows (with command prompt), so I'm not sure if the issue is reproducible on other platforms. All invocations of `atom .` seem to reflect the state of the environment from the first time I invoked atom. Moreover, when using WSL (Bash on Windows), atom seems to completely ignore any environment variables I've set in the shell beforehand. This might be an unrelated issue, but I've ruled out using WSL as a workaround.

### Steps to Reproduce

1. In one command prompt window, `set FOO=bar`
2. In the same command prompt window, `atom .`
3. In another command prompt window, `set FOO=foo`
4, In this other command prompt window, `atom .`
5. Print `process.env` in the Javascript console for both atom windows.

**Expected behavior:** `FOO` in the first window should be equal to `bar` and `FOO` in the second window should be equal to `foo`.

**Actual behavior:** Both windows report `FOO` as `bar`.

**Reproduces how often:** Every time.

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

Windows 10 Build 15063.332 x64

### Additional Information

I've noticed related closed issues or merged pull requests, but they seem to focus more on OS X. Whatever the fix was in the past, at the very least it doesn't work on Windows.

**Comment by lee-dohm** [comment]
I'm not able to reproduce this using Atom v1.20.0-dev-372cef218 on Mac OS X 10.12.6. So it would appear that it is a Windows-specific issue.

@ungb Can you reproduce this?

**Comment by 50Wliu** [comment]
Confirmed.
