### ISSUE TITLE
[Feature Request] Add support for making package recommendations

### ISSUE THREAD

**Issue by mehcode** [atom/atom#14995]
### Problem

A package that has additional _plugin_ packages that perhaps enable a tight integration with other packages or environments currently has no method outside of documentation to recommend their installation.

 - `minimap-linter` when both `linter` and `minimap` are installed
 - `build-coffee` when `build` is installed and the user opens a CoffeeScript file

A package that simply offers additional functionality when another package is installed has no avenue to recommend outside of documentation or [atom-package-deps](https://www.npmjs.com/package/atom-package-deps).

 - `hyperclick` when `go-plus` or `flow-ide` are installed. If I install a `hyperclick-javascript` package I assume it would use `atom-package-deps` to install `hyperclick` as it would be useless otherwise. Both `go-plus` and `flow-idea` have a fair amount of functionality outside of simply being a `hyperclick` provider.

Atom currently has dozens of builtin `language-` packages. What if instead these language packages were not builtin but _recommended_ to the user when the user opened the file for the first time? 

### Proposed Solution

A new package, `recommendations`, would be accepted in Atom core. This package would define the UI and the consume the `atom.recommendations` service that any package could provide to make recommendations. Alternatively this could be put into the `settings-view` package as recommended packages might make sense to be displayed above or below featured packages in the install area.

Atom core itself would make no recommendations for community packages.

Recommended packages would remember what packages recommended them and the UI would communicate this so that users would not feel that Atom itself is recommending them. Below is a mock that could exist on the Install tab of settings-view.

![screen shot 2017-07-11 at 2 31 22 pm](https://user-images.githubusercontent.com/753919/28091859-414c123e-6646-11e7-91a0-48e20ceb8146.png)

When a new recommendation is made it could show in the bottom-right similar to when updates are available. A message should also be presented to the user. Here is how this process looks in VS Code:

![screen shot 2017-07-11 at 2 42 27 pm](https://user-images.githubusercontent.com/753919/28092128-2fec5cdc-6647-11e7-8a3a-77539c92684b.png)

`go-plus` does do something like this already (see below) but we could formalize what it does and make the UX much cleaner by integrating the recommendation process into core.

![screen shot 2017-07-11 at 2 45 09 pm](https://user-images.githubusercontent.com/753919/28092336-cc0b2f08-6647-11e7-89d4-c2d19bafc6be.png)

Below is a quick mock of what it could look like unified. I'd still want the package desc. as well as perhaps a select/unselect and Install Selected/All button.

![screen shot 2017-07-11 at 2 49 18 pm](https://user-images.githubusercontent.com/753919/28092420-2b1107ac-6648-11e7-9555-3282c783f4ce.png)

**Comment by santhosh74** [comment]
Iam Intrested  in this topic
The idea is to introduce submenu named recomended software which displays plugin packages that enhance functionality of an atom

**Comment by santhosh74** [comment]
is this correct?

**Comment by santhosh74** [comment]
But  packages menu already exists in Atom Editor

**Comment by santhosh74** [comment]
There is already an feature named "INSTALL A PLUGIN" that displays various packages that enhances atom

**Comment by Arcanemagus** [comment]
@santhosh74 Please read this issue and understand what it is requesting, this is only tangentially related to the current packages implementation in Atom.

For some further backstory on previous pushes towards functionality similar to this see:
* https://github.com/atom/apm/pull/385 which added similar functionality to APM itself, but had no associated UI.
* https://github.com/atom/apm/pull/387 which allowed services to list dependencies (things like a linter plugin requiring something that consumes it).
