### ISSUE TITLE
Bracket matching not working at all

### ISSUE THREAD

**Issue by Niichie** [atom/atom#14994]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Bracket matcher doesn't work at all for me. It is not highlighting any matching brackets.
![2](https://user-images.githubusercontent.com/16381287/28075130-8236a4a8-6628-11e7-87b3-34146db6fc0c.JPG)

### Steps to Reproduce

1. Open HTML file
2. Get error regarding bracket-matcher

**Expected behavior:** Selecting a bracket will match it to the next bracket of that type.

**Actual behavior:** Nothing happens when bracket is selected.

**Reproduces how often:** Every time, reinstalled atom (latest beta), now there is no error but it's not working at expected at all.

### Versions 1.19-beta3 and 1.18.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!  When you say:

> Get error regarding bracket-matcher

Do you have a stack trace you can copy and paste for us?

**Comment by lee-dohm** [comment]
Thank you for your submission!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/14994#issuecomment-315449590. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
