### ISSUE TITLE
Tree View crashes Atom when opening file on remounted disk volume

### ISSUE THREAD

**Issue by cdon-dev-crew** [atom/atom#14992]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The editor crashes when using "tree view" to open a file in a "project folder" that is located on a **re**mounted drive.

Please note that it is not necessary to actually access the volume (by e.g. opening a file). It seems that the volume disappearing/reappearing is enough for the editor to crash.

Also note that this behavior is **not** present when using File -> Open on the volume. Hence I believe it is related to the "tree view".

Crash logs from _Scenario 2_ has been attached.

[e0003a1c-b264-414b-849c-96d6ce864538.txt](https://github.com/atom/atom/files/1138162/e0003a1c-b264-414b-849c-96d6ce864538.txt)
[operation_log.txt](https://github.com/atom/atom/files/1138163/operation_log.txt)
[e0003a1c-b264-414b-849c-96d6ce864538.zip](https://github.com/atom/atom/files/1138171/e0003a1c-b264-414b-849c-96d6ce864538.zip)

### Steps to Reproduce

Note that this crash is reproducible in both _safe_ and _regular_ mode.

#### Scenario 1:

1. Make sure the volume is **not** already a "project folder" in Atom.
2. Mount the volume in DiskCryptor.
3. Start Atom.
3. Add a "project folder" pointing to the mounted volume.
4. Unmount the volume in DiskCryptor.
5. Remount the volume in DiskCryptor.
6. Open any file from the mounted volume.

#### Scenario 2:

1. Make sure the volume **is** already a "project folder" in Atom.
2. Mount the volume in DiskCryptor.
3. Start Atom.
4. Unmount the volume in DiskCryptor.
5. Remount the volume in DiskCryptor.
6. Open any file from the mounted volume.

#### Scenario 3:

This is my daily usage scenario.
The volume has been automatically unmounted the the end of the day.
At the beginning of each work day, I wake the computer from sleep mode.

1. Make sure the volume **is** already a "project folder" in Atom.
2. Mount the volume in DiskCryptor.
3. Start Atom.
4. Unmount the volume in DiskCryptor.
5. Put the computer to sleep (and go home for the day).
6. Wake up the computer.
7. Remount the volume in DiskCryptor.
8. Open any file from the mounted volume.

#### Expected behavior:

The editor should not crash when opening a file on a volume that was first mounted, then unmounted and finally remounted.

#### Actual behavior:

The editor crashes when trying to open any file on a **re**mounted volume.
This is regardless of whether any file (on any volume) was opened or not.

#### Reproduces how often:

Every time the scenario is repeated.

### Versions

`atom --version`
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

This is the current version I'm using, but this problem has been present much, much longer than this. Perhaps for years? I'm not certain.

`apm --version`
apm  1.18.1
npm  3.10.10
node 6.9.5 ia32
python 3.6.1
git 2.10.2.windows.1
visual studio 2015

Windows 10 Enterprise

### Additional Information

This happens on Windows 10 using [DiskCryptor](https://diskcryptor.net/wiki/Main_Page) to simulate an unplugged volume. Presumably, it is related to a volume being remounted, but it **could** also be related to network shares, as described in [ticket 14760](https://github.com/atom/atom/issues/14760).

**Prerequisite**
Use e.g. DiskCryptor to create a new volume.
Place a text file in that volume (in order to have content that can be opened by Atom).

**Comment by mrv20** [comment]
Disabling the git-diff, github and open-on-github core packages does not prevent the crashes.

**Comment by mrv20** [comment]
I am no longer able to reproduce this on Atom 1.34.0, OS X 10.14.3 - it looks like the issue may have ben fixed

**Comment by 50Wliu** [comment]
Thanks @mrv20 - @cdon-dev-crew can you confirm if this is still happening to you?

**Comment by cdon-dev-crew** [comment]
> Thanks @mrv20 - @cdon-dev-crew can you confirm if this is still happening to you?

No, I am no longer able to reproduce this problem on Atom version 1.34.0 (Windows 10 x64).
This issue has been resolved!
