### ISSUE TITLE
GPG key with no passphrase fails with git integration

### ISSUE THREAD

**Issue by pconwell** [atom/atom#14999]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Signed commits using a GPG key that does not have a passphrase fails. 

### Steps to Reproduce

1. Generate a GPG key and leave the passphrase blank
2. Add the GPG key to github
3. Make changes to a repo in Atom
4. Move changes from 'Unstaged Changes' to 'Staged Changes'
5. Attempt to commit changes with GPG signature
6. Box pops up asking for passphrase
7. Hit 'enter' (entering a blank passphrase)
7. Commit fails

**Expected behavior:** 

GPG Keys with blank passphrases would be accepted when entering a blank passphrase

**Actual behavior:**

You get the following error message when entering a blank passphrase:

     \path\to\Local\atom\app-1.18.0\resources\app\node_modules\github\bin\gpg-no-tty.sh: line 22: exec: gpg: not found
     error: gpg failed to sign the data
     fatal: failed to write commit object

**Reproduces how often:**

Every time.

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

### Additional Information

Signing with GPG key (with a blank passphrase) works fine from term. I have not attempted to test this with a GPG key that requires a passphrase.

**Comment by rsese** [comment]
Thanks for the report!  Can you re-open this in https://github.com/atom/github so we have it in the right place?  I found https://github.com/atom/github/issues/814 but that's about a GPG key with a passphrase not working, not sure if that's the same issue.

**Comment by pconwell** [comment]
Resubmitted to https://github.com/atom/github/issues/1039
