### ISSUE TITLE
I want to add images or edit text as bold just like in libre office

### ISSUE THREAD

**Issue by caneraydinbey** [atom/atom#15000]
But i could not find any information about this. Is it possible?

**Comment by rye761** [comment]
Atom is a text editor for writing code. Therefore, the method used to bold text or add images depends on the language you are working in. If you are using HTML, you would need an <img> tag for images or <strong> for bold.

If you want to create documents, please use a program suited for doing that such as the aforementioned libreoffice writer.

**Comment by 50Wliu** [comment]
@rye761 is correct.  Atom is a text editor primarily meant for writing code or for markup purposes, not as a WYSIWYG editor.  However, it may be that there's a package offering that functionality for Atom, but you'll have to ask on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or [Slack](http://atom-slack.herokuapp.com/).
