### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by dsdorazio** [atom/atom#15002]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'firstChild' of undefined

```
At C:\Users\Daniel\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\text-editor-component.js:2110

TypeError: Cannot read property 'firstChild' of undefined
    at TextEditorComponent.measureLongestLineWidth (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/text-editor-component.js:2110:112)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/text-editor-component.js:381:16)
    at scheduler.readDocument (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/text-editor-component.js:266:20)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/view-registry.js:191:15)
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:36.4.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:00.9.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -1:00.8.0 core:select-all (input.hidden-input)
     -0:59.5.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -0:59.3.0 core:select-all (input.hidden-input)
  4x -0:57.6.0 core:select-right (input.hidden-input)
     -0:50.7.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -0:50.5.0 core:select-all (input.hidden-input)
     -0:49.7.0 core:backspace (input.hidden-input)
     -0:49.2.0 atom-terminal-panel:toggle-autocompletion (input.hidden-input)
     -0:49 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-terminal-panel 4.4.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by dsdorazio** [comment]
Hi Robert,

I was pasting code from a website "py4e playground" (python) into Atom. it
was unrecoverable, only closing fixed it.

Yes, it occurred multiple times.

I didn't try it in Atom Safe mode.

Cheers,
Dan

On Jul 14, 2017 14:10, "Robert Sese" <notifications@github.com> wrote:

Thanks for the report! Can you confirm a few things for us?

   - what were you doing at the time of the error?
   - is the error is reproducible?
   - if reproducible, do you see the error in safe mode (atom --safe)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/atom/atom/issues/15002#issuecomment-315455583>, or mute
the thread

**Comment by rsese** [comment]
> I was pasting code from a website "py4e playground" (python) into Atom. it
> was unrecoverable, only closing fixed it.

Thanks @dsdorazio - can you share a link to the code/file you pasted so I can give it a try?
