### ISSUE TITLE
Search to automatically open a fold?

### ISSUE THREAD

**Issue by brograhamer** [atom/atom#15001]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Searching a term does not automatically open a fold, whereas I believe it should.

### Steps to Reproduce

1. Fold all code within your document
2. Search a term within your code

**Expected behavior:** The fold should automatically open at it's parent ancestor level (nested)

**Actual behavior:** The term is highlighted but the fold remains

**Reproduces how often:** 100%

### Versions

1.19.0-beta3

**Comment by rsese** [comment]
Thanks for the report!  Can you share some screenshots or a GIF/screencast that shows the behavior you're describing?  Just want to make sure we're on the same page.

**Comment by brograhamer** [comment]
![capture](https://user-images.githubusercontent.com/23107066/28230987-0007a48c-68b7-11e7-8cd1-e43c09b8a6cd.gif)

**Comment by rsese** [comment]
Ahhh thanks @brograhamer, I think I see what you're saying now - I had initially tested searching for text within a fold and in that case, the fold is opened if a term is found within a fold.

So just to clarify, from your GIF it looks like you expect the code to unfold at line 483 if you search and find text from the visible part of the fold (i.e. "archive" or "index")?

**Comment by brograhamer** [comment]
@rsese Yes, the functionality you described for me is exactly what I'm looking for! Is that something you can help implement for a release?

The GIF below might address what you were first describing in your top paragraph. I have three SCSS classes, each with unique properties, and if you notice when I search `border` it does not open the fold. I think when you search for something natively you should be taken to the line with that class and have all of it's properties unfolded (right terminology?).

![capture](https://user-images.githubusercontent.com/23107066/28317874-a9770954-6b96-11e7-81e7-7a3704cb4b3c.gif)

**Comment by 50Wliu** [comment]
So it definitely looks like find-and-replace is _trying_ to unfold to get to your result, but it isn't trying hard enough (and assumes at most one fold).  @brograhamer could you please reopen this on the [find-and-replace](https://github.com/atom/find-and-replace) directory?

**Comment by brograhamer** [comment]
@50Wliu Absolutely, on it.
