### ISSUE TITLE
Color Scheme has BUG

### ISSUE THREAD

**Issue by i2027479** [atom/atom#15009]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
While using in a PHP file an issue regarding to color scheme is occurred:
When in PHP file I'm using <script> and assigning a number type variable through PHP
**eg.**
```javascript
<script>
var a = <?php $myVar ?>
</script>
```
In this case the colors of fonts are changed and showing wrong colours like as `</script>` is being shown in black instead of red and all HTML tags below this are also mis-coloured. If I remove this line or assign variable in PHP then it's OK. Fix this, I'm having a lot f perception problem in viewing due to this. 

### Steps to Reproduce

1. Create a `.PHP` file.
2. Open `<script>` tag.
3. Assign a PHP number variable to JS number variable (example: `var a = <?php $my ?>`)
4. Now see the `</script>` closing tag, It's colour is black which shouldn't be.

**Expected behavior:** Red colour for `</script> `like as the opening `<script>` tag and HTML tag colors below this.

**Actual behavior:**  Black colored tags instead of actual colors.

**Reproduces how often:**  **100%**

### Versions
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.5.0

UBUNTU 15.*

### Additional Information

Nothing
![screenshot from 2017-07-13 13-25-48](https://user-images.githubusercontent.com/30141967/28156089-d8ef5522-67ce-11e7-8ffe-e6ea75db7c03.png)

**Comment by 50Wliu** [comment]
You are on a very outdated Atom version - the latest is currently Atom 1.18.0.  This bug should be fixed if you update.

**Comment by i2027479** [comment]
Can you tell me how to update my Atom?

**Comment by 50Wliu** [comment]
You can download the latest version at https://atom.io.

**Comment by i2027479** [comment]
Thanks buddy... It worked and brought too many new great features too...   :smiley:
