### ISSUE TITLE
Atom keeps on uninstalling once PC is shut down

### ISSUE THREAD

**Issue by AndrejPetrushevski** [atom/atom#15017]
Every time I restart my PC, Atom gets uninstalled and I have to install it once more. However every package I've downloaded is still present in my .atom directory. Once I install the editor everything is back in its previous state. I have to go through this process all the time and I really enjoy this editor, any help would be greatly appreciated!

Thanks in advance

**Comment by 50Wliu** [comment]
@AndrejPetrushevski can you walk me through the steps you're taking to install Atom?

**Comment by AndrejPetrushevski** [comment]
@50Wliu The odd thing is, there are no required steps I just run the installer and it auto installs Atom. As I said before everything pops back in its previous state (All the files I have worked with before I restarted the PC).

**Comment by 50Wliu** [comment]
So you're using AtomSetup.exe?

**Comment by AndrejPetrushevski** [comment]
Atom Setup x64 that's correct. As of right now everything is set up in my .atom directory except the editor itself. I'll have to install it once more via the setup to have it available. This goes on every time i turn on my PC.

**Comment by 50Wliu** [comment]
This is very odd.  Did you ever use the `msi` variant by any chance (eg `AtomSetupx64.msi`)?

**Comment by mpboom** [comment]
Are you sure this isn’t some kind of policy that resets the `AppData` folder?
