### ISSUE TITLE
I have downloaded atom but can't see where it is installed...i have to sun the setup all over again all the time to use it.

### ISSUE THREAD

**Issue by sanchitghai24** [atom/atom#15015]
windows 8.1

**Comment by ShaishavJogani** [comment]
It will be probably stored at below location.
`C:\Users\<your-username>\AppData\Local\atom`

**Comment by 50Wliu** [comment]
Correct.

**Comment by sanchitghai24** [comment]
But I cant see its icon ???
from where do I run it from?

**Comment by 50Wliu** [comment]
@sanchitghai24 Can you run `AtomSetup.exe --squirrel-updated` from the command line?

**Comment by Spankyed** [comment]
same issue for months

**Comment by 50Wliu** [comment]
@Spankyed can you follow my instructions and see if that helps?

**Comment by lee-dohm** [comment]
Thanks for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/15015#issuecomment-315377627. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Spankyed** [comment]
I was able to get it working. Was getting chrome dev tools evreytime, deleted blob folder. And was able to locate the atom executable.


Thank you

________________________________
