### ISSUE TITLE
"Editor is not responding" after leaving "Save As" dialog open for some time on macOS Sierra

### ISSUE THREAD

**Issue by collinstocks-oscar** [atom/atom#15022]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If the save dialog is open for too long, when it closes, I get an "Editor is not responding" dialog. If I click "Keep Waiting", everything is actually fine. I suspect there's a synchronous call somewhere when opening the save dialog.

### Steps to Reproduce

1. Create a new file in atom.
2. File -> Save As
3. Stare at the "Save" modal for a couple minutes.
4. Input a file name and save the file.
5. Now the "Editor is not responding" dialog pops up.
6. Click "Keep Waiting".
7. Everything is fine and working as normal.

**Expected behavior:** "Editor is not responding" dialog should not pop up.

**Actual behavior:** "Editor is not responding" dialog pops up.

**Reproduces how often:** 100%

### Versions

macOS Sierra Version 10.12.5
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.11.0

### Additional Information

N/A

**Comment by qiang-bi** [comment]
I tried reproducing this a couple times but failed. However, I am using Atom 1.18.0 along with macOS Sierra 10.12.5. Maybe update your atom?

**Comment by collinstocks-oscar** [comment]
I can reproduce this using Atom 1.18.0.

**Comment by rsese** [comment]
I can reproduce as well with 1.18.0 and 1.19.0-beta4 on macOS 10.12.5.

**Comment by sadick254** [comment]
Thanks for reporting this!

I cannot reproduce this on the latest version of atom. `v1.50.0`
```
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
python 2.7.16
git 2.24.3
```
Am happy to reopen this when bug can be reproduced on the latest atom `v1.50.0`

**Comment by collinstocks-oscar** [comment]
Moved to PyCharm since 2017 but I'll let you know if I switch back and see the issue again.
