### ISSUE TITLE
Atom crashing with no plugins and no user data, in safe mode

### ISSUE THREAD

**Issue by iconmaster** [atom/atom#15026]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom started crashing regularly for me today, so I've been trying to narrow down the cause. Started by disabling all third-party plugins. Then I renamed my user data directory. Finally I tried safe mode. Still crashing. Doesn't require any user interaction, just waiting a few minutes.

### Steps to Reproduce

1. Launch Atom
2. Wait

**Expected behavior:** 
No crash.

**Actual behavior:**
Persistent crash.

**Reproduces how often:**
Every time.

### Versions

Atom 1.18
Mac OS 10.12.5

### Additional Information

Crash log attached.
[atom-crash.zip](https://github.com/atom/atom/files/1149214/atom-crash.zip)

**Comment by maxbrunsfeld** [comment]
Does this happen if you disable the built-in `github` package?

**Comment by iconmaster** [comment]
Tentatively, disabling the `github` package seems to be improving it. Haven't seen a crash for several minutes. Is that a known issue then?

**Comment by BinaryMuse** [comment]
The crash dump appears to be similar to the one at https://github.com/atom/github/issues/953 which I'm hoping is fixed by the PR that took care of https://github.com/atom/github/issues/959.

**Comment by iconmaster** [comment]
Okay, thanks.
