### ISSUE TITLE
Can't click gutter/line number to select entire line when line is already active with text cursor

### ISSUE THREAD

**Issue by repertor** [atom/atom#15024]
### Description

I am unable to click the gutter, where the line numbers are, to select the entire line if that line has the cursor in it. I have to click a different line number first, then click the line I want.

### Steps to Reproduce

1. Place cursor on any line
2. Click line number for that line to select the whole line

**Expected behavior:** The whole line is selected.

**Actual behavior:** Nothing happens

**Reproduces how often:** Every time

### Versions

1.19.0-beta3

macOS 10.12.6

### Additional Information
I could not find any guide for starting the Atom Beta in safe mode.

**Comment by 50Wliu** [comment]
Confirmed, though I'm not sure if this is expected behavior or not.

**Comment by Arcanemagus** [comment]
Looks like this is a regression in v1.19.0.

In v1.18.0 clicking the line number in the gutter selects the entire line and replaces any current cursors with a new cursor at the start of the line _after_ the one clicked on.

![2017-07-19_15-37-53](https://user-images.githubusercontent.com/427137/28392779-4c3d6c30-6c98-11e7-8928-92152ea082a1.gif)

**Comment by nathansobo** [comment]
I can't reproduce this. When I click a line number the results are exactly the same as in the animation you posted. Can this be closed?

**Comment by Ben3eeE** [comment]
I can reproduce this if I install an old Atom 1.19 beta but not on 1.19 stable so I guess this has been fixed.
