### ISSUE TITLE
XHTML gets stuck

### ISSUE THREAD

**Issue by zhanzhenzhen** [atom/atom#15030]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

XHTML gets stuck in the following case. The highlighting is also incorrect. That may be because it uses HTML as the parser and there's something wrong when `<style>` element has `CDATA` in it. If I switch to XML then it works fine.

### Steps to Reproduce

Create a file `"abc.xhtml"` with the following content:

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <style type="text/css"><![CDATA[
        html {
            font-size: 13pt;
        }
    ]]></style>
</head>
<body>
<pre class="try"><code class="try"><![CDATA[
    啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊"="

]]></code></pre>
</body>
</html>
```

Then open it with Atom.

**Expected behavior:** It shouldn't get stuck, and the highlighting should be correct.

**Actual behavior:** The whole UI gets stuck for a long time, after that the highlighting is incorrect.

**Reproduces how often:** Always

### Versions

Atom 1.18.0 on macOS 10.12.5

**Comment by 50Wliu** [comment]
Seems to be related to #14856.
