### ISSUE TITLE
Weird render glitches on Skylake GPU

### ISSUE THREAD

**Issue by awilkins** [atom/atom#15032]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:

### Description

Odd rendering glitches on Skylake GPU / HiDPI screen.

This seems to happen when the new rendering pipeline is under stress. While this happens *less* in safe mode (presumably because fewer things are rendering), it doesn't stop happening completely.

Most reliable way to provoke this seems to be triggering the install of a package with a long install time, like `atom-beautify` ; I'm guessing this is down to the rendering of the stripey throbber on the install button.

See [video of this happening](https://photos.app.goo.gl/f1RpNFfit9IwYwM53)

This only happens on my Skylake / HiDPI laptop - not seen it on my nvidia or Intel GPU.

### Steps to Reproduce

1. Open Atom 1.19.x
2. Install `atom-beatify`

**Expected behavior:** [What you expect to happen]

No glitching.

**Actual behavior:** [What actually happens]

Glitching.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always, but actual glitch trigger is obviously complex because it's not readily predictable.

### Versions

Atom 1.19.0 - 1.19.4
 
### Additional Information

The pattern of the glitches look like the have the footprint of various element redraws.

**Comment by jorenmartijn** [comment]
Experiencing something similar here!
```
Additional Information
The pattern of the glitches look like the have the footprint of various element redraws.
```
Are there artefacts appearing on the screen that are constantly changing?  
Like triangles and other weird shapes appearing?
My editor started to glitch out all of a sudden and do that.
Was worried for a second that my GPU was failing on me. But then I swiped over to a different desktop and everything else looked fine, swiped back and the editor was still glitching out.
Specs:
```
MacBook Pro (Retina, 13-inch, Early 2015)
Processor: 2,7 GHz Intel Core i5
Memory: 8 GB 1867 MHz DDR3
Graphics: Intel Iris Graphics 6100 1536 MB
macOS Sierra 10.12.4
Atom 1.18.0
```
I don't have atom-beautify installed but I do have atom-prettify, so maybe it does a similar thing?

**Comment by awilkins** [comment]
It's not something I've seen from any other application on the same machine ; including Chrome.

> I don't have atom-beautify installed but I do have atom-prettify

As plugins that edit buffer streams and don't really draw anything by themselves I doubt they have any influence - I chose `atom-beautify` to show off the effect as it has a relatively long install period (because it downloads a *lot* of dependencies), and thus shows the blue scroll/strobe/throb effect on the button for longer, that effect seems to trigger the glitches much more reliably than anything else in Atom (otherwise they are sporadic... like jump-scares in Half-Life games...).

>  triangles and other weird shapes

No triangles, only blocks - all looks like whole or partial html element footprints in the Atom application document. Triangles sounds more like composition issues (modern desktops are a 3D render... of a couple of big triangles per window, with the window a texture dynamically drawn by the 2D toolkit...)

**Comment by damieng** [comment]
Are you using a video card (if so, what name).

We have seen issues in the past where people using the on-board Intel video have issues caused by the default settings in *Graphics options* being set in favor of 3D games rather than GPU accelerated apps (like Atom).

You might want to try changing some of those settings to see if it helps.

**Comment by awilkins** [comment]
It's a laptop, I'm just using the internal graphics support in the CPU AFAIK.

> the default settings in Graphics options

Don't have any of those! It's Ubuntu, so it just configures the GPU options automatically. I guess I could mess with Xorg.conf a bit.

If you uninstall the Intel drivers, it falls back to the kernel modesetting driver. The problem with that is that you now have virtually no acceleration, video becomes a slideshow. But the flickering stops!

Atom is the only app I've used on this machine that does this though.

**Comment by damieng** [comment]
I definitely wouldn't advise disabling the graphics drivers.  

The previous issues were on Windows but the reason it tends to only show 'in Atom' is that Atom uses hardware accelerated (GPU) rendering typically used by games.  Not many apps use it but some do such as Chrome/Firefox and Electron-derived apps (like Atom).  On Windows we didn't see issues in Chrome because the Intel drivers specifically check for `chrome.exe` and disable their tweaks.

A few more things to try:

1. Post a screenshot here of the issue - I want to make sure we're talking about the same thing
2. Try launching atom from the command line with `atom --disable-gpu` and see if it still happens (this flag isn't sticky so next time you launch Atom it will use the GPU again)

**Comment by awilkins** [comment]
1. There's a video of it happening linked in the initial bug, it's almost impossible to catch the glitching with screenshots because it's so fast
1. Disabling the GPU does seem to remove the glitches

Also noted that the install takes aaaages with GPU on. `atom-beautify` takes it's time normally - about 60-70s - but with the GPU on it's more like 300s - 5x longer (and fires up the cooling fan when this doesn't normally happen much at all on this metal-case laptop). This compared with `apm install atom-beautify` taking 48s on the command line.

Subjectively the rest of the system operations involving screen draws are slowed down during the install as well, like it's spinning some GPU resource and everything is having to wait for it.

If I was guessing I'd say that something is trying to render way more frames than the GPU is actually capable of displaying, but that would be just a guess.

**Comment by mokasin** [comment]
I have similar issues on a "Intel Corporation HD Graphics 530" and on a PC with a "Radeon HD7970" using the `radeon` driver on linux. The first is on Debian Stretch and the second on Arch Linux.

But the flickering seems to be more local:

![Atom flickering](https://i.imgur.com/LJ2Yqc1.gif)

As you can see, the command palette is sometimes not rendered at all.

**Comment by damieng** [comment]
@mokasin Did you try the `atom --disable-gpu` option described above?

At the end of the day graphical glitches like these are down in the display driver level - Atom simply leverages Chromium to do all rendering and we have no control over those levels. 

I'd also recommend trying some other Chromium or Electron based apps and see if they also experience glitching and flickering like this.

**Comment by mokasin** [comment]
@damieng Sorry, forgot to mention, that this still happens with `atom --disable-gpu`. Also `wire` and `riot-web` seem to work fine. I don't have this issue on my third device, an 6th gen Intel CPU with Intel HD Graphics 520 using modesetting driver.

The other Intel machine should also use modesetting drivers, but I have to doublecheck.

**Comment by damieng** [comment]
That's weird it's still happening with disable gpu. Given that we only render using HTML and CSS we don't have any further control or ability to diagnose visual rendering issues below that level.

These problems do normally resolve themselves with OS graphics driver updates or updates to Chromium when we bump Electron.

I'm not familiar with Wire or Riot-Web - are they both Electron based apps?  If so do you know what version they are?

**Comment by mokasin** [comment]
Call me crazy, but after updating `vim-mode-plus` to version 1.2.0 and I cannot longer reproduce this.

**Comment by flamein** [comment]
preliminary results, after update to 1.3.3 it's gone for me as well... maybe @t9md can shed some light as to what happened? see nothing relevant in changelogs.

**Comment by awilkins** [comment]
While I do use `vim-mode-plus` these glitches happen for me on a bare naked install of Atom with no user-installed packages ; the use of `atom-beautify` to trigger the glitch is the first package to be installed in the test case I'm using to reproduce it.

I'll give it another go later though, with and without installing `vim-mode-plus` first.

**Comment by flamein** [comment]
sadly, they have returned for me as well, no `atom-beautify` installed though

**Comment by jorenmartijn** [comment]
<img width="660" alt="screen shot 2017-09-11 at 15 11 58" src="https://user-images.githubusercontent.com/2348805/30276240-7af5d85a-9704-11e7-9838-0a7d19c6a8bc.png">
The glitch I described in my first reply happened again just a few minutes ago. Elements are flickering and my file menu disappears as well.
Made a screenshot before I quit the app (which 'fixes' the glitch).
