### ISSUE TITLE
Default snippet doesn't work

### ISSUE THREAD

**Issue by whmountains** [atom/atom#15044]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Autocomplete-snippets doesn't report user snippets.

### Steps to Reproduce

1. Reset atom to factory settings (optional)
2. Open the snippets file
3. Type `snip` and press tab

**Expected behavior:** 

I expect an example snippet to appear

**Actual behavior:** 

Nothing happens

**Reproduces how often:** Always

### Versions

`atom --version`
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

`apm --version`
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.0

I'm running MacOS High Sierra build `17A306f`.

**Comment by lee-dohm** [comment]
I'm not sure when exactly this was fixed, but I'm not able to reproduce this in the latest development version of Atom.

**Comment by wanderingduck** [comment]
Same issue: snip tab not working in normal or safe mode. Any help appreciated.
![2017-09-27 15_59_13-snippets cson](https://user-images.githubusercontent.com/30722718/30921201-cad84b32-a39d-11e7-91a9-c3808889dc3c.png)

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/snippets/issues/243
