### ISSUE TITLE
OAuth Sign-In Screen for GitHub package says "not owned or operated by GitHub" when it is.

### ISSUE THREAD

**Issue by retnikt** [atom/atom#15057]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode _(NA)_
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/ _(NA)_
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages _(NA)_

### Description

When the GitHub package for Atom is authorised using the browser on the OAuth page, the text at the bottom says 

> Not owned or operated by GitHub

![chrome_2017-07-19_15-53-14](https://user-images.githubusercontent.com/24581770/28373516-71695fee-6c9a-11e7-854d-7d350032485c.png)

### Steps to Reproduce

1. Press Ctrl+Shift+8 to open the GitHub package panel in Atom. (I believe this requires GitHub for Desktop to be installed, but I'm not sure)
2. Click "Login" then follow the link
3. Authorise the Atom application, using password if necessary

**Expected behavior:** The OAuth page at the bottom shows "Owned and operated by GitHub". 

**Actual behavior:** The OAuth page at the bottom shows "Not owned or operated by GitHub". (see screenshot)

![chrome_2017-07-19_15-53-14](https://user-images.githubusercontent.com/24581770/28373516-71695fee-6c9a-11e7-854d-7d350032485c.png)

**Reproduces how often:** Always (100% of the time)

### Versions

`Atom    : 1.18.0`

`Electron: 1.3.15`

`Chrome  : 52.0.2743.82`

`Node    : 6.5.0`

### Additional Information

I have GitHub for Desktop installed, version 0.7.0. Browser used was Chrome 59.

**Comment by Arcanemagus** [comment]
You might want to file this over on the [github package](https://github.com/atom/github/issues).
