### ISSUE TITLE
Text Editor not updating properly after Cmd-A -> Delete

### ISSUE THREAD

**Issue by tjfryan** [atom/atom#15053]
### Description

Nuclide uses text editors for input in some places. As of Atom 1.19-beta4, these text editors will sometimes not delete the last line of input when Select All(Cmd-A)+Delete is run.

### Steps to Reproduce

Somewhat similar to #15005

1. Install Nuclide package
2. Toggle Nuclide Http Request Sender via command palette
3. Add some text.  Select All (Cmd-A) then delete
4. Some of the time, the last line won't get deleted.  Subsequent SelectAll+Deletes will usually properly delete them 

**Expected behavior:** [What you expect to happen]
All text goes away

**Actual behavior:** [What actually happens]
Last line of text remains

**Reproduces how often:** [What percentage of the time does it reproduce?]
50%?  I'm not able to determine a pattern when all gets deleted or all but the last line.

### Versions

Atom    : 1.19.0-beta6
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.0
MacOS 10.12.4

![cmdadelete](https://user-images.githubusercontent.com/3195775/28345345-8abdfcfa-6bde-11e7-8821-bb2b3e51e583.gif)

**Comment by rsese** [comment]
Thanks for the report - tagging as needs reproduction since I couldn't reproduce on macOS 10.12.5 and Atom 1.18.0.

**Comment by tjfryan** [comment]
Oops, I mistakenly put atom 1.18 when I meant 1.19-beta4.  However I'm no longer able to reproduce, so I'll assume this was caused by something else

**Comment by tjfryan** [comment]
Although, after upgrading to 1.19-beta6, I ran into the issue again, but it seems to repro less often.

**Comment by rsese** [comment]
Ohh gotcha, np - I tried again with 1.19-beta6 and still couldn't reproduce but we can leave this open for a bit to see if anyone runs into it or something similar.

**Comment by tjfryan** [comment]
This seems to be due to the behavior of Cmd-Backspace
