### ISSUE TITLE
Feature Request • Drag file from nagivator into editor to insert path

### ISSUE THREAD

**Issue by Randallcp** [atom/atom#15050]
### Problem

* When I drag a file from the navigator, I expect the file path to be inserted into the editor, upon where I place it.
* I expect this functionality when I am writing the path for image files, for html files in the `href` property, and other code files when I am writing `<script>` and `<stylesheet>` tags.

### Proposed Solution

When I drag a file from the project navigator, the path of that file should be inserted at the location where I let go of the click-and-drag. This capability is found in other text-editors, including Xcode, and is very helpful.

**Comment by lee-dohm** [comment]
You may want to check out https://atom.io/packages/drag-relative-path
