### ISSUE TITLE
Atom modifies random lines in files tracked by source control when saving.

### ISSUE THREAD

**Issue by PeterKaminski09** [atom/atom#15060]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom modifies random lines throughout the file on save or CMD + s

### Steps to Reproduce

1. Modify a line in a file which is being tracked in source control
2. Save the file
3. An unexpected line will appear as modified 

**Expected behavior:** Only lines that have been manually modified should show a yellow indicator as being modified

**Actual behavior:** A line which was not modified by me shows as changed in source control after saving the file.

**Reproduces how often:** [Has happened to me on both my work and home laptops]

### Versions

1.18.0

### Additional Information

![screen shot 2017-07-19 at 11 58 57 am](https://user-images.githubusercontent.com/5935411/28384467-b6899a42-6c79-11e7-8e12-ecc828d0f0a8.png)
Actual line modified

![screen shot 2017-07-19 at 11 59 49 am](https://user-images.githubusercontent.com/5935411/28384492-cd15d406-6c79-11e7-9c1b-f50a197363b9.png)
Random line which shows as modified after CMD+S

![screen shot 2017-07-19 at 12 42 54 pm](https://user-images.githubusercontent.com/5935411/28386252-dc6bc216-6c7f-11e7-915c-68ee5cd0cc77.png)
And the resulting diff in version control

**Comment by 50Wliu** [comment]
Without additional information, I am going to guess that Atom is removing trailing whitespace.  To turn off this feature, go into the Whitespace settings and disable the "Remove Trailing Whitespace" option.

**Comment by PeterKaminski09** [comment]
I think that was the issue. Thanks
