### ISSUE TITLE
Keyboard Shortcut to open bottom tab (Linter)

### ISSUE THREAD

**Issue by garethallenstringer** [atom/atom#15065]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I haven't found a means in which to open the bottom tab/drawer simply (i.e. like using `Ctrl + Shift + 9` to open the Git tab) in order to open, for instance, Linter (or any other package that may use such space)

**Expected behavior:** [What you expect to happen]

A simple keyboard shortcut to open the bottom tab.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python
git 2.13.2.windows.1
visual studio

Windows 10 Pro
Version 1703
OS Build 15063.483

**Comment by 50Wliu** [comment]
You can ask Linter to add a keybinding, or bind a keybinding to `window:toggle-bottom-dock`.
