### ISSUE TITLE
Atom crashes when copying contents from one editor tab to another. MacOS Sierra

### ISSUE THREAD

**Issue by loligans** [atom/atom#15078]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I received the below message **after** pasting all the text of a 33.8MB file into a new untitled file.

> The editor has crashed. Please report the issue to https://github.com/atom/atom

### Steps to Reproduce

1. Open a large file (e.g. [The file causing Atom to crash - Hosted On Google Drive](https://drive.google.com/open?id=0B2YHKXTPh6ezTU5hQkJ4TzN6cXM))
2. Press (Cmd + A) then press (Cmd + C) to put the contents of the file on your clipboard
3. Press (Cmd + N) to open a new untitled document.
4. Press (Cmd + V) to paste your clipboard contents into the new untitled document.

**Expected behavior:** Editor does not crash

**Actual behavior:** 

after about 10 seconds the editor will paste the contents into the new untitled document. However, the user interface will remain frozen even after the editor is filled with the contents from your clipboard. After another 5 seconds the editor crashes. Opening Atom in safe mode from the terminal yields the below results

```
$ /Application/Atom\ Beta.app/Contents/MacOS/Atom\ Beta --safe                           

<--- Last few GCs --->

[21851:0x7f8c91847a00]    83407 ms: Mark-sweep 1405.7 (1465.1) -> 1405.6 (1434.1) MB, 1254.6 / 6.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1255 ms) last resort 
[21851:0x7f8c91847a00]    84607 ms: Mark-sweep 1405.6 (1434.1) -> 1405.6 (1434.1) MB, 1199.2 / 2.3 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1662a60519c1 <String[7]: file://>
    2: new Symbol [<embedded>:~206370] [pc=0x16f63ecca07](this=0x29340d1c9239 <a Symbol with map 0x117fc7db541>,text=0x29340d1c8c21 <String[2]: e7>,scopes=0x29340d1c8a31 <JS Array[1]>)
    4: recomputeSymbolsForEditorInBufferRange [<embedded>:~206487] [pc=0x16f63fa77f2](this=0x9505fd55d81 <a SymbolStore with map 0x117fc7e17e9>,editor=0x38f711946929 <a TextEditor with map 0x117fc7d6f79>...
```

**Reproduces how often:** 100%

### Versions

```
$ /Application/Atom\ Beta.app/Contents/MacOS/Atom\ Beta --version
Atom    : 1.19.0-beta4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
Specs:
```
MacBookPro13,2 (A1706)
macOS Sierra: Version 10.12.5
```
### Additional Information

I am running the 64-bit build of atom. Interestingly the amount of RAM that was in use by Atom when I pasted the contents of the first editor into the untitled document jumped. **These tests were done on a file 33.8MB in size.**

With no document loaded Atom sat at around ~330MB
<img width="657" alt="screen shot 2017-07-22 at 5 36 04 pm" src="https://user-images.githubusercontent.com/3218210/28495530-4f5962a2-6f04-11e7-8668-6d7c96b02567.png">

With the document loaded Atom sat between 520MB - 700MB
<img width="615" alt="screen shot 2017-07-22 at 5 39 05 pm" src="https://user-images.githubusercontent.com/3218210/28495548-c401773e-6f04-11e7-989a-4f0dbf5760a4.png">

When I copied the document to a new untitled document, Atom jumped to ~2.0GB - 2.14GB then crashed.
<img width="580" alt="screen shot 2017-07-22 at 5 08 03 pm" src="https://user-images.githubusercontent.com/3218210/28495531-54bca588-6f04-11e7-9101-bf4711ea5ec3.png">
[Atom Beta Helper_2017-07-27-211501_Ethans-MacBook-Pro.crash.txt](https://github.com/atom/atom/files/1195136/Atom.Beta.Helper_2017-07-27-211501_Ethans-MacBook-Pro.crash.txt)

**Comment by rsese** [comment]
Thanks for the report!  I couldn't reproduce on macOS 10.12.5 and Atom 1.19.0-beta5 with a test 33 MB file (`a` character over and over but not on one line/not super long lines) - would you be able to share the specific file you're copying and pasting so we can give it a try?

**Comment by loligans** [comment]
Hi @rsese 

I confirmed that it is still occurring on Atom 1.19.9-beta5

I have attached the file. It is a pdf. I mistakenly got the size wrong it is a 55.8MB file.

The background is I was testing how well Atom handles binary files because I am working on an extension that can detect a certain proprietary encryption and then decrypt the file before presenting it to the user. 

In addition to the encryption stuff I also wanted to see how well Atom handles opening, rendering, and searching through large files. It is so much better now!

[The file causing Atom to crash - Hosted On Google Drive](https://drive.google.com/open?id=0B2YHKXTPh6ezTU5hQkJ4TzN6cXM)

**Comment by rsese** [comment]
Thanks for sharing the specific file, I can reproduce with it - I'll update your steps to repro so it links to it in step 1.

Can you grab the [crash log](http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs) and link to that as well?

**Comment by loligans** [comment]
Sure thing! Github does not support uploading MacOS crash logs so I had to upload it to my Google Drive instead. There are 12 Atom crash logs in the zip file.

Do you know what is causing the crash? I'm interested in these sort of things.

[Atom Crash Logs - Hosted On Google Drive](https://drive.google.com/open?id=0B2YHKXTPh6ezWS1Zc21kU0lkRjQ)

**Comment by loligans** [comment]
Should the tags for bug be changed?

**Comment by rsese** [comment]
Sorry I missed your followups @loligans:

> Github does not support uploading MacOS crash logs so I had to upload it to my Google Drive instead. There are 12 Atom crash logs in the zip file.

You can just add a `.txt` extension to the crash file, I went ahead and attached that latest crash file to the issue body.

> Do you know what is causing the crash? I'm interested in these sort of things.
> Should the tags for bug be changed?

I can't tell from the crash logs but tagging as a bug so it can be looked at by the team.

**Comment by jasonrudolph** [comment]
Out of curiosity, I wanted to see how Chrome would respond to a pasting this file into a textarea. Thanks to Chrome's tab isolation, it doesn't crash all of Chrome, but you're essentially forced to kill the tab. On my 2017 MacBook Pro, Chrome hangs for about 30 seconds after you paste into the textarea, and then Chrome informs you that the page has become unresponsive:

![demo](https://user-images.githubusercontent.com/2988/29047791-75f37512-7b9b-11e7-8c1e-4af5ea1274ff.gif)

I'll see what our options are for providing more graceful handling in Atom.

**Comment by jasonrudolph** [comment]
Continuing the early stages of investigation started [above]( https://github.com/atom/atom/issues/15078#issuecomment-320795637), it seems that Chrome and Electron both end up *hanging* when you paste this massive amount of text into a textarea, but pasting it into Atom crashes the renderer process instead of just causing the process to hang. (See examples below.) With that in mind, I'll look into our options.

### Chrome

Chrome 60.0.3112.90 (64-bit):

![chrome](https://user-images.githubusercontent.com/2988/29076138-92774682-7c22-11e7-8dfc-3ed3ab4dfa17.png)

### Electron

[electron-quick-start](https://github.com/electron/electron-quick-start/tree/dea012119e8532693458f4181d60efaec387e72c) app customized to provide a simple textarea and handlers for the [`unresponsive` event](https://electron.atom.io/docs/api/browser-window/#event-unresponsive) and the [`crash` event](https://electron.atom.io/docs/all/#event-crashed):

![electron](https://user-images.githubusercontent.com/2988/29076137-92761b36-7c22-11e7-87e6-351ac33810fa.png)

### Atom

Atom 1.21.0-dev-c850f38fe running in safe mode:

![atom](https://user-images.githubusercontent.com/2988/29076136-92711eec-7c22-11e7-8474-538ac0158f73.png)

**Comment by maxbrunsfeld** [comment]
@loligans Thanks for the detailed report. My apologizies that we're still crashing in this case; we definitely intend to handle this use case in the future.

In case anyone is interested, I believe the component that's causing the crash is Atom's autocomplete package, [autocomplete-plus](https://github.com/atom/autocomplete-plus). This package indexes the set of words found in every open buffer, and uses a lot of memory in the process.

We disable this indexing for large files, but if a file starts out empty and then you paste a lot of text into that file, we can end up consuming a lot of resources indexing the pasted text.

Luckily, we've already started on [a new approach to autocompletion](https://github.com/atom/superstring/pull/22) that leverages some new features of our Text Buffer, which has been [rewritten in C++](https://github.com/atom/superstring/pull/5) as of Atom 1.19. The plan is to completely eliminate the need for a word index, allowing autocomplete to work in arbitrarily large files without using an inappropriate amount of memory.

**Comment by rsese** [comment]
Going through some older issues - I can no longer reproduce on macOS 10.12.6 with 1.34.0-nightly3.   Perhaps the work Max mentioned above or other updates since this issue was opened have resolved the issue?

Going to go ahead and close for now but please re-open or comment if folks still see an issue.

Thanks again for reporting @loligans :v:
