### ISSUE TITLE
Switch to micromatch for performance?

### ISSUE THREAD

**Issue by danielbayley** [atom/atom#15089]
Since [minimatch is currently a dependency](https://github.com/atom/atom/blob/d9ebd7e125d5f07def1a057a0a8278d4d9d7d23a/package.json#L46), why not switch to _[micromatch]_? See [_Why use micromatch?_][micromatch]…

I think it’s a drop-in replacement, so should be an easy [if small] win?

[micromatch]: https://npmjs.com/package/micromatch#why-use-micromatch

**Comment by deankevorkian** [comment]
Although the document that states the key / major breaking differences between minimatch and micromatch is no longer maintained (see [](https://gist.github.com/jonschlinkert/96212e11d128fc659d12) ),
it seems like the only difference that remains is with backslashes (see [](https://github.com/micromatch/micromatch#backslashes)).
If the changes don't scale around the app so widely it's most definitely worth it..
