### ISSUE TITLE
Atom hangs indefinitely when executing a regex search and replace on a large file

### ISSUE THREAD

**Issue by domenicomastrangelo** [atom/atom#15097]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When doing a regex search and replace editor hangs for a long period of time

### Steps to Reproduce

1. Load a large text file ( I tested with one that's 180 MB, 365'542 lines )
2. Search and replace using a regex

**Expected behavior:** Some progress bar and not to hang prompting a message "Atom is taking a long time, do you want to close it or wait"

**Actual behavior:** hangs for an indefinite amount of time, sometimes 1 minute, sometimes 10 minutes not showing any progress

**Reproduces how often:** Everytime i do a regex search on a large file

### Versions

Atom version 1.18 and 1.19.0-beta5 tested.
Windows 10, latest update.
Intel core i7 6700HQ
16 GB RAM

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/find-and-replace if there's no existing issue already so we have it in the right place?

Also, if it's possible to share the file and an example search you're running that causes the hang, that would help for reproducing.
