### ISSUE TITLE
The editör has crashed. I don't wanna use sublime text :( HELP ME !

### ISSUE THREAD

**Issue by CagatayUNAL** [atom/atom#15095]
Hi everyone,
I have big problem, I open project at atom editor then my workspace is freezes,does not move. I don't improve my project with atom then opens a alert windows "This editör has crashed, Please report this issue to https://github.com/atom/atom" . How can I solve this problem.I don't wanna use sublime text.

**Comment by mpboom** [comment]
Did you try reinstalling Atom?

**Comment by maksim-litvinov** [comment]
You can check "View->Developer->Toggle developer tools>Console" for errors

**Comment by CagatayUNAL** [comment]
Yes, I did reinstall many times

**Comment by mpboom** [comment]
Did you also try to delete these folders, along with reinstalling Atom?

`C:\Users\[username]\AppData\Roaming` and `C:\Users\[username]\AppData\Local\atom`

Maybe even `C:\Users\[username]\.atom` but I think that wipes all your settings etc.. For me deleting the first one, in `AppData\Roaming` always works when Atom isn't behaving well.

**Comment by borishere** [comment]
Try this in command prompt: `atom --clear-window-state`

**Comment by CagatayUNAL** [comment]
I use mac os

**Comment by mpboom** [comment]
The solution from @borishere still works if you are using macOS.

**Comment by CagatayUNAL** [comment]
I did try this solution but problem is still happening

**Comment by 50Wliu** [comment]
@CagatayUNAL have you tried all the applicable steps in the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?

**Comment by ungb** [comment]
@CagatayUNAL Does it crash regardless of what project you open?  Does it crash when the project is empty or is it a git project or project with large files?

Any more info would be appreciated.

**Comment by CagatayUNAL** [comment]
I solved this problem. I disabled github plugin. Thanks everyone. I love atom :)
