### ISSUE TITLE
Add Workspace Items optional methods to documentation

### ISSUE THREAD

**Issue by UziTech** [atom/atom#15101]
### Description

The [Workspace documentation](https://atom.io/docs/api/v1.18.0/Workspace) lists a workspace item's [required methods](https://atom.io/docs/api/v1.18.0/Workspace#required-methods) but does not list the [optional methods](https://github.com/atom/atom/blob/master/src/workspace.js#L45) listed in the comments of /src/workspace.js.

![image](https://user-images.githubusercontent.com/97994/28640784-6a8cbb4e-7212-11e7-8c7f-ff92596a51e7.png)

**Comment by 50Wliu** [comment]
Probably a joanna/atomdoc bug?  Not sure which though.

**Comment by UziTech** [comment]
It looks like atomdoc is the culprit. I created an issue in that repo.

atom/atomdoc#13
