### ISSUE TITLE
Scrollbar appears to disappear/reappear when editor window is resized

### ISSUE THREAD

**Issue by ion201** [atom/atom#15107]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Scrollbar appears to disappear and reappear when the editor window is resized. I may open a file and the scrollbar is initially visible, but it will eventually disappear. From that state, changing the height of the scrollbar content (opening find-and-replace, resize window, etc) will cause the scrollbar to toggle between visible and invisible. From the inspector, the vertical-scrollbar and scrollbar-content don't seem to change other than the "height: ###px" of the scrollbar-content element changing. Manually changing the height in the style of the element also flips it's visibility on/off. It can even occur while scrolling with the mouse.

### Steps to Reproduce

1. Generate a large file, I used: `python -c '[print((n,)*50) for n in range(1000)]' > f`
2. Open the file with atom, using angle: `electron --app=/usr/lib/atom --use-gl=angle ./f` (I'm using angle because of this virtualbox issue: [Virtualbox 15417](https://www.virtualbox.org/ticket/15417), without it, atom causes the desktop to lock up. `--disable-gpu` has the same effect as far as this issue is concerned.) 
3. Observe the scrollbar disappear while resizing editor pane, triggered by scrolling, resizing window, opening/closing find-and-replace panel, etc.

**Expected behavior:** The scrollbar appears on the side of the editor and never disappears under any resize.

**Actual behavior:** Scrollbar disappears and reappears when editor is resized.

**Reproduces how often:** Inconsistently. I'm able to reproduce it every time by opening a the file like above. However, it does not always trigger on opening a new file from within atom.

### Versions

Platform: Arch Linux, up-to-date as of 26/7/2017
Atom    : 1.18.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0
apm  1.18.3
npm  5.3.0
node 8.2.1 x64
python 2.7.13
git 2.13.3

### Additional Information

If a second file is opened in atom, this scrollbar issue is observed independently. The issue appears to be specific to a file's window/tab and having the issue observed for one file's window/tab doesn't seem to have any impact on whether or not it will be observed when switching focus to another file. Closing and re-opening a file may temporarily alleviate the issue but switching context between files does not.

**Comment by ion201** [comment]
Closing because I can no longer reproduce after upgrading to:

    Atom    : 1.19.5
    Electron: 1.6.11
    Chrome  : 56.0.2924.87
    Node    : 7.4.0

**Comment by master-general** [comment]
Atom 1.21.1 ia32 windows 10 fall creators, display 1366x768 - can't scroll editor content :(

**Comment by bluantinoo** [comment]
I still have this exact behavior in 1.25.1 (High Sierra 10.13.4)

**Comment by cortical-iv** [comment]
I am having this problem in 1.25.1. Scrollbar disappears, but when I toggle tree mode it sometimes temporarily re-appears. Safe mode doesn't make a difference.

**Comment by cortical-iv** [comment]
Note I am only having the problem when I try to use a custom scrollbar:
`
// style scrollbar
.scrollbars-visible-always {
/deep/ ::-webkit-scrollbar {
width: 20px;
height: 20px;

&-track {
  border: 0px;
  border-radius: 0px;
  background-color: rgb(100, 100, 100) !important;
}

&-thumb {
  background-color: rgb(205, 100, 31) !important;
  border: 1px;
  border-radius: 1px;
}

}
}
// style scrollbar
.scrollbars-visible-always {
/deep/ ::-webkit-scrollbar {
width: 20px;
height: 20px;

&-track {
  border: 0px;
  border-radius: 0px;
  background-color: rgb(100, 100, 100) !important;
}

&-thumb {
  background-color: rgb(205, 100, 31) !important;
  border: 1px;
  border-radius: 1px;
}

}
`

When I cut that out of styles.less, I can see the scrollbar still.

I may start a new ticket.

**Comment by bluantinoo** [comment]
@cortical-iv you're right, if I remove custom scrollbar styles it's ok.
can't tell if it's why I've upgraded to 1.27 or was already like this in 1.25 

is there an alternative to make the scrollbar bigger?

**Comment by morkeltry** [comment]
[Related?](https://github.com/atom/atom/issues/5749#issuecomment-366886835)
The scrollbar's container needs to be greater than the scrollbar width.
container > scrollbar : no probs
scrollbar > container : width setting ignored
container = scrollbar : scrollbars sometimes disappear depending on status.
