### ISSUE TITLE
open file/directory dialog shows all text characters as boxes

### ISSUE THREAD

**Issue by mrummuka** [atom/atom#15116]
### Description
Open file/directory dialog shows all text as boxes. Font corrupt?

### Steps to Reproduce

1. open atom
2. select File / Open File or File / Open Directory

**Expected behavior:** 
Normal dialog with text.

**Actual behavior:** 
All text (including buttons) shown as boxes. 
![screenshot from 2017-07-28 15-43-07](https://user-images.githubusercontent.com/14860687/28718259-d85a633c-73ad-11e7-983c-3fc91d30dcc6.png)

**Reproduces how often:** 
Always

### Versions
$ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.13
git 2.13.3

$ cat /etc/redhat-release 
Fedora release 26 (Twenty Six)

lsb_release 
LSB Version:	:core-4.1-amd64:core-4.1-noarch

uname -a
Linux mr-laptop 4.11.10-300.fc26.x86_64 #1 SMP Wed Jul 12 17:05:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Gnome: Version 3.24.2

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Issue started after Fedora 25 -> 26 upgrade. Upgrade itself seemed succesfull.

**Comment by 50Wliu** [comment]
> Atom : 1.8.0

You are running an Atom version that is around one year old.  The current Atom version is 1.18.0 - I highly suggest you update it by downloading the new version at https://atom.io.

**Comment by mcpierce** [comment]
I'm running 1.11.1 and am seeing this same issue today. So it's not an old-version problem.

**Comment by 50Wliu** [comment]
@mcpierce the current Atom version is 1.23.1.

**Comment by fbuchmeier** [comment]
I had the same problem with ATOM 1.8 on Fedory 26 & 27. I have installed ATOM via Fedy and it would seem a regular "dnf update" would not update those packages. So I removed ATOM via Fedy and installed it again, and voila, everything is fine in the latest version.
```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
