### ISSUE TITLE
Command/ Ctrl + W quits Atom instantly. 

### ISSUE THREAD

**Issue by Martinnord** [atom/atom#15117]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In Atom you can close tabs with the shortcut "command/ctrl + W", but apparently you can also close down Atom itself if you use the shortcut one too many. 

### Steps to Reproduce

1. Have a bunch of tabs opened up.
2. Start using the shortcut.
3. If you use it one too many Atom will quit.

**Expected behavior:**
Just to close down the tabs in Atom, not Atom itself.

**Actual behavior:**
Atom shuts down. Which is really frustrating. 

**Reproduces how often:**
Not sure about what to type here, I'm sorry.

### Versions
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
### Additional Information

Thanks for reading.

**Comment by 50Wliu** [comment]
Disable the "Close Empty Windows" option in Settings -> Core.
