### ISSUE TITLE
copy multiple directories from left side project pane with Shift/Ctrl shortcut not work 

### ISSUE THREAD

**Issue by jacknlliu** [atom/atom#15113]
### Steps to Reproduce

- select some directories from left side project pane using Shift/Ctrl shortcut
- then using right-click menu bar select "copy"
- select other directory and then using right-click menu bar select "paste"

**Expected behavior:**
We hope all the directories should be copied to the target directory.

**Actual behavior:**
Only part or single director was copied to the target directory.

### Versions
```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by 50Wliu** [comment]
This will be fixed in Atom 1.20.0.
