### ISSUE TITLE
square fonts in atom gui - debian hebrew

### ISSUE THREAD

**Issue by EranGoldman** [atom/atom#15129]
Atom 1.9.9 
Debian 4.9.30-2
Hebrew system 
LANG = en_US.UTF-8

Reproduce : 
Just open any atom menu ...

![image](https://user-images.githubusercontent.com/16475635/28752517-195534f0-7522-11e7-8fba-28563ae1a04c.png)

![image](https://user-images.githubusercontent.com/16475635/28752519-2bf3a498-7522-11e7-8f3f-616024d4307f.png)

Thank you

**Comment by 50Wliu** [comment]
> Atom 1.9.9

The latest version of Atom is currently Atom 1.18.0.  You can upgrade by downloading the installer at https://atom.io.
