### ISSUE TITLE
Atom cli will not work, if Atom is already not open.

### ISSUE THREAD

**Issue by nappa32** [atom/atom#15131]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed:  
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If Atom.app is closed, `atom` cli will not open a file / folder from command line and generate an error like 

```
❯ atom /home
2017-07-31 13:51:26.205 atom[53386:1426259] *** Assertion failure in +[SQRLDirectoryManager currentApplicationManager], /Users/joshaber/Documents/Development/GitHub/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30
zsh: illegal hardware instruction  atom /home

```
```
bash-4.4$ atom ~/
2017-07-31 13:54:18.302 atom[53467:1428048] *** Assertion failure in +[SQRLDirectoryManager currentApplicationManager], /Users/joshaber/Documents/Development/GitHub/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30
Illegal instruction: 4
```
Important to note - I am NOT: @joshaber [Josh](https://github.com/joshaber).

### Steps to Reproduce

1. Close all copies of OSX atom app.
2. run `atom ./`

**Expected behavior:** [What you expect to happen]
If directory/file already open, open in right Atom Window based on project OR just open the file at all. Should not matter if the app is already open OR not. It should open the app, and then open the file.

**Actual behavior:** [What actually happens]
If the Application is already not open, it will crash and show error message.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
I
Atom    : 1.19.0-beta5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: OSX.

I've been able to verify this issue on non-beta app versions too.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Hmmm, looks like https://github.com/atom/atom/issues/10278?

Did you use the `Atom > Install Shell Commands` menu item to use Atom from the command line or some other method (e.g. manual symlink)?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15131#issuecomment-319756402. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
