### ISSUE TITLE
I think that atom should have templates for LICENSE.md and README.md.

### ISSUE THREAD

**Issue by RatanShreshtha** [atom/atom#15140]
I think whenever a user adds an README.md or LICENSE.md file in his/her folder then there should be an option to auto populate LICENSE.md for common licences and README.md can be made with a common template.

**Comment by awilkins** [comment]
Sounds like a good thing to use [snippets](https://github.com/atom/snippets) for.

**Comment by 50Wliu** [comment]
Thanks @awilkins - that sounds like a perfect use for snippets.
