### ISSUE TITLE
Support Command Metadata

### ISSUE THREAD

**Issue by wbinnssmith** [atom/atom#15143]
Atom commands should be able to reference arbitrary metadata, along with a human-written displayName and a description of what to expect when a command is executed.

This way, tools like the command palette could surface something potentially friendlier than the `_.humanizeEventName` version of the name string of the command, which is more of an implementation detail.

Potential arbitrary metadata could be keywords (which could or could not surface themselves in search results), aliases, search weight, etc.

It's possible to retain and simply augment the existing command registration API by supporting a complex object everywhere a callback function might be expected:

```js
atom.commands.add(
  'atom-text-editor', 
  'user:insert-date',
  {
    displayName: 'Insert a really awesome date',
    description: 'Whereever your cursor is, it inserts the current date!',
    keywords: ['timestamp', 'time', 'today', 'now'],
    aliases: ['user:insert-now'],
    callback(e) {
      const editor = this.getModel();
      editor.insertText(new Date().toLocaleString());
    },
  },
  true // throwOnInvalidSelector
);
```

or

```js
atom.commands.add(
  'atom-text-editor', 
  {
    'user:insert-date': {
      displayName: 'Insert a really awesome date',
      description: 'Whereever your cursor is, it inserts the current date!',
      callback(e) {
        const editor = this.getModel();
        editor.insertText(new Date().toLocaleString());
      },
    },
    'user:some-other-command': {
      displayName: 'Does something really cool',
      description: 'Really, it\'s super awesome',
      callback(e) {
        editor = this.getModel();
        editor.insertText('yay!');
      },
    }
  },
  true // throwOnInvalidSelector
);
```

I'm not 100% of whether this metadata should be declared at registration time, and what the consequences are for the same command name registered multiple times with different targets (something I assume from looking at the api is supported?).

Another thought I had was either declaratively defining this metadata in `package.json`, or registering metadata bound to command names separately, in the same way keybindings are decoupled from commands:

```js
atom.commands.register({
  'user:insert-date': {
      displayName: 'Insert a really awesome date',
      description: 'Whereever your cursor is, it inserts the current date!',
      keywords: ['timestamp', 'time', 'today', 'now'],
      aliases: ['user:insert-now'],
    },
  },
)
```

cc @matthewwithanm @hansonw @captbaritone @jinface @karincurkowicz

**Comment by nathansobo** [comment]
I think I prefer registering the metadata along with the command as in your first example, where it looks like you're just replacing the function with a more complex object? A few questions/comments:

* What do you envision as the API for reading this metadata?
* Do you think we should attach this metadata as a field on the command event passed to the function?
* What do you think about calling the `callback` field `action` or `listener`? I'm not *super* opposed to `callback` but wanted to suggest some alternatives as I don't love the word `callback`.
* Do you have an initial use case for this metadata in mind? Do you plan to open a PR on the command palette or does Nuclide have its own uses.

Thanks for this very clear write-up!

**Comment by wbinnssmith** [comment]
>> What do you envision as the API for reading this metadata?
I figured we'd pass a near-identical structure as was registered back to those using `atom.commands.findCommand()`, [using the existing api which already passes back an object](https://github.com/atom/atom/blob/master/src/command-registry.coffee#L145-L148). I haven't thought much about other APIs though.

>> Do you think we should attach this metadata as a field on the command event passed to the function?
Like attaching the metadata to the `CustomEvent` object that listeners get? Yes! A lot of the trivial use cases might not need it since the metadata is in scope at the time the listener is created, but for stuff like parameterized commands (see below) this is perfect :)

>> What do you think about calling the callback field action or listener? I'm not super opposed to callback but wanted to suggest some alternatives as I don't love the word callback.
Oh yeah, totally. I think I just called it callback because of [the argument name in the implementation](https://github.com/atom/atom/blob/master/src/command-registry.coffee#L94) :P Personally I like `listener` as it's in line with [the DOM api](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters) but `action` is a great idea too.

>> Do you have an initial use case for this metadata in mind? Do you plan to open a PR on the command palette or does Nuclide have its own uses.
We see a ton of power in the command palette but are exploring ways of making it more approachable. 

We'd also love to make commands optionally parameterized, so a schema could be easily defined on this metadata and presented in command palette.

I think **in the short term**, while we only have a few pieces of standardized metadata, it would be trivial for me to submit a couple patches to the core Atom command palette to show things like descriptions or hand-written displayNames for commands when available, all while we explore different interfaces and interactions inside Nuclide.

**Comment by matthewwithanm** [comment]
> Do you have an initial use case for this metadata in mind? Do you plan to open a PR on the command palette or does Nuclide have its own uses.

Making both user-facing fields (like a description) and non-user-facing fields searchable would be a great way to improve discoverability. For example, something like jumping to a related file could be surfaced to users searching for "C headers" or diagnostics commands to people searching for "linter" stuff.

**Comment by wbinnssmith** [comment]
Just a thought:

In the DOM, `addEventListener` can accept an [object as a listener rather than just a simple callback](https://developer.mozilla.org/en-US/docs/Web/API/EventListener). In that object, if `handleEvent` is defined, it will be called as the event handler.

As an analog, we could have something called `handleEvent` or `handleCommand` in this complex object, likewise as an alternative to the simple callback listener. Both object and callback versions can be called event `listener`s, as they are in the dom api.

**Comment by nathansobo** [comment]
The idea you've proposed here makes sense to me. I like the name `handleEvent` if it blends into DOM APIs.

>  it would be trivial for me to submit a couple patches to the core Atom command palette to show things like descriptions or hand-written displayNames for commands when available, all while we explore different interfaces and interactions inside Nuclide.

That sounds excellent. I'd love to see at least one feature using this in the stock Atom experience just so we have contact with it more regularly.

Please feel free to open up a pull request cross-linked to this issue and ping me on it.
