### ISSUE TITLE
Rendering issues on MacOS

### ISSUE THREAD

**Issue by jarrodek** [atom/atom#15146]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
See attached image:

![image](https://user-images.githubusercontent.com/3320020/28897090-012d828c-7794-11e7-8693-e4e923a3e551.png)

There are two areas of a darker background:
Darker color:
![color1](https://user-images.githubusercontent.com/3320020/28897483-ca62849e-7795-11e7-8173-cd4521e63519.png)

And lighter color:
![color2](https://user-images.githubusercontent.com/3320020/28897492-d678f75e-7795-11e7-9fbc-a235d11269a0.png)

This screenshots has been made after fresh stable atom install (and removing .atom directory). So there's no themes or any non-default packages installed.

### Steps to Reproduce

1. Open atom on mac os

**Expected behavior:** Solid color of the whole workspace

**Actual behavior:** Different shares 

**Reproduces how often:** 100%

### Versions

Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

This is strange because `node -v` shows `v7.1.0`

### Additional Information

I'm using Atom on Win10, Ubuntu (latest) and MacOS (also latest with all updates). I can only observe this behavior on MacOS.

**Comment by jarrodek** [comment]
This is not happening in Beta release:

![image](https://user-images.githubusercontent.com/3320020/28897887-c5774620-7797-11e7-83c4-bb26f62c2d25.png)

**Comment by 50Wliu** [comment]
Correct, this will be fixed in Atom 1.19.
