### ISSUE TITLE
Pane.destroyItem() can return a non-boolean value

### ISSUE THREAD

**Issue by captbaritone** [atom/atom#15157]
`Pane.destroyItem()` claims to return a promise of a boolean value. In the force case, or if the user does not need to save, we instead return the result of `item.destroy?()`.

I'll open a pull request to address this.

https://github.com/atom/atom/blob/master/src/pane.coffee#L629

cc @matthewwithanm @hansonw

**Comment by maxbrunsfeld** [comment]
Thanks for catching that @captbaritone. Will be glad to merge that PR.
