### ISSUE TITLE
Linux build fails after pulling from repo

### ISSUE THREAD

**Issue by capouch** [atom/atom#15155]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
After cloning Github repo for Linux source build, subsequent build attempts fail.

[Description of the issue]
Building from fresh checkout proceeds fine.  But after pulling changes, a series of errors occurs with ENOENT, e.g.
`npm ERR! enoent ENOENT: no such file or directory, rename '/home/brianc/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors' -> '/home/brianc/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
`
### Steps to Reproduce

1. Do a fresh checkout from Github
2. Build without problems
3. Next day, pull changes from repo
4. Build now fails in a section that appears to rename a series of directories
5. Fixing one such error (e.g. from above, creating the ansicolors directory, leads to another and then another, all of the same ilk.

**Expected behavior:** [What you expect to happen]
Clean build.

**Actual behavior:** [What actually happens]
Build fails as noted.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always.

### Versions
Current checkout from master; this has been happening for about a week.  Build system is Linux Slackware 14.2 (current),  Node v8.2.1, npm v3.10.10

**Comment by rsese** [comment]
Thanks for the report - I don't have a Linux install to test with right now but have you tried running a `script/clean` before building again?

**Comment by capouch** [comment]
That does indeed solve the issue, although it seems at the cost of an increased build time.  Thanks.

**Comment by 50Wliu** [comment]
The fix that's worked for me is to remove any package-lock files that npm may have generated before building again.  It seems like npm is still working out some issues with those files.
