### ISSUE TITLE
Atom slow

### ISSUE THREAD

**Issue by naccio8** [atom/atom#15150]
From yesterday atom has become really slow on two different computers.

Atom version: 1.18.0 x64
Platform: Windows 10

My config:
"*":
  core:
    disabledPackages: [
      "project-viewer"
      "Sublime-Style-Column-Selection"
      "text-manipulation"
      "tag"
      "sublime-word-navigation"
      "sublime-block-comment"
      "set-syntax"
      "satisfy-dependencies"
      "project-manager"
      "multi-cursor"
      "ctrl-dir-scroll"
      "build"
      "atom-wrap-in-tag"
      "wrap-guide"
    ]
    telemetryConsent: "limited"
    themes: [
      "atom-dark-ui"
      "atom-sublime-monokai-syntax"
    ]
  editor:
    fontSize: 12
    showIndentGuide: true
    tabLength: 4
  "exception-reporting":
    userId: "a14d2d27-dcb2-49c4-adf5-8d979b8e1078"
  "linter-php":
    executablePath: "D:\\wamp\\bin\\php\\php7.0.4\\php.exe"
  "linter-ui-default":
    panelHeight: 81
  "php-debug":
    PathMaps: [
      "remotepath;localpath"
      "/media/sf_win_debian;D:\\win_debian"
    ]
    PhpException:
      Notice: false
      ParseError: false
    ServerAddress: "192.168.111.174"
    ServerPort: 9000
    currentConsoleHeight: "213px"
    currentPanelHeight: "233px"
    currentPanelMode: "bottom"
  "project-manager":
    alwaysOpenInSameWindow: true
    environmentSpecificProjects: true
  welcome:
    showOnStartup: false

**Comment by naccio8** [comment]
Is slow when the app lost the focus.
For example: I edit some css on Atom, I pass on the browser for check the modify, when I return on Atom for write other line for ~3 second it not respond

**Comment by naccio8** [comment]
In the atom developer tool console in this moment I read:
Handling of 'mousewheel' input event was delayed for 830 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.

**Comment by naccio8** [comment]
I found the problem! I uninstalled https://it.malwarebytes.com/ and was return fast!

**Comment by laravelish** [comment]
its slow since the first release
