### ISSUE TITLE
The editor has crashed(atom)

### ISSUE THREAD

**Issue by Kikue** [atom/atom#15161]
<img width="517" alt="2017-08-04 12 42 44" src="https://user-images.githubusercontent.com/17269168/28953369-864663b0-7912-11e7-97ee-8d94cf2480f9.png">
① app clearner という関連するアプリのファイルを全て消すアプリ

② 
rm -rf  ~/.atom
rm /usr/local/bin/atom
rm /usr/local/bin/apm
rm ~/Library/Preferences/com.github.atom.plist
rm -rf ~/Library/Application\ Support/com.github.atom.ShipIt
rm -rf ~/Library/Application\ Support/Atom
rm ~/Library/Saved\ Application\ State/com.github.atom.savedState
rm ~/Library/Caches/com.github.atom
rm ~/Library/Caches/Atom
rm ~/Applications/Atom.app

①、②のとおり、アンインストールをし、atomを再インストールしても、atomを起動すると動作が止まってしまいます．．．

**Comment by rsese** [comment]
Closing as a duplicate of https://github.com/atom/atom/issues/15162.
