### ISSUE TITLE
package ansicolors not found but installed

### ISSUE THREAD

**Issue by JPRuehmann** [atom/atom#15164]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
git pull
2. [Second Step]
run build script
3. [and so on...]

**Expected behavior:** [What you expect to happen]

No errors

**Actual behavior:** [What actually happens]
`npm ERR! path /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors' -> '/home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ruehmann/.npm/_logs/2017-08-04T00_30_11_522Z-debug.log
child_process.js:513
    throw err;
    ^

Error: Command failed: /home/ruehmann/atom/script/node_modules/.bin/npm --global-style --loglevel=error install
npm ERR! path /home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/ansicolors' -> '/home/ruehmann/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/.ansicolors.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ruehmann/.npm/_logs/2017-08-04T00_30_11_522Z-debug.log`
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by segevfiner** [comment]
Might be related to https://github.com/npm/npm/issues/9633. I nuked `apm/package-lock.json` when it happened to make it work.

**Comment by 50Wliu** [comment]
Yeah.  This seems to be an npm issue.  For the time being, remove any package-lock files before rebuilding.

**Comment by JPRuehmann** [comment]
seems deleting the package-lock.json files had helped.
Thanks
