### ISSUE TITLE
Save project state periodically

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#1516]
The other day I had 4 panes and 2 dozen tabs open representing a particulary dumb / complicated refactor. Then my laptop hard locked. After rebooting and reopening the editor, I was presented with zero panes and zero tabs. This ruined my afternoon. We should probably save project state periodically rather than just on quit, as I only have so many laptops to throw out the window before I run out.

**Comment by OverloadUT** [comment]
Just chiming in that this would be very great! I got so used to this in Sublime that I implemented it in to my workflow - love being able to close Sublime at any time without any "save" prompts, and be able to open it back up to the same state. I would frequently leave "scratch" documents open for quick notes that I never actually saved to a file

**Comment by vauvenal5** [comment]
+1

**Comment by markwalkom** [comment]
+1 :)

**Comment by seranabede** [comment]
Would definitely like to see this feature implemented at some point, pretty much the only thing that Sublime has over Atom.

**Comment by rthangaveljv** [comment]
+1 .. Will be greatly helpful!

**Comment by ptlu** [comment]
+1 been looking for this!

**Comment by jehrenzweig** [comment]
+1 on this.  It's an essential feature in Sublime that I can no longer live without.

**Comment by nitzantomer** [comment]
+1 this is an absolute must

**Comment by destri8** [comment]
+1 :D

**Comment by jgpeak** [comment]
+1 is definitely needed in Atom

**Comment by ric2b** [comment]
+1 since I just lost 5 min work on a crash, not much, but still annoying (and that's because I save periodically).
Why the auto-save package is included but disabled by default is beyond me, can someone explain the reasoning?

**Comment by dugger** [comment]
+1

**Comment by billybonks** [comment]
updating the serialised atom editor state every minute if it has changed. and caching changed files at the same time would solve this problem ?

**Comment by mlalkaka** [comment]
+1

**Comment by dapitch666** [comment]
+1

**Comment by mnquintana** [comment]
Thanks for the feedback everyone! However, all these +1s and :+1:s are just adding noise, so to minimize that I'm going to lock this issue for now – we may unlock it once someone starts working on this enhancement to get further feedback.

**Comment by 50Wliu** [comment]
Starting in Atom 1.7.0, Atom periodically saves editor state for crash recovery.  Therefore, I believe this issue has been resolved.
