### ISSUE TITLE
Uncaught TypeError: Cannot read property 'createObjectStore' of undefined

### ISSUE THREAD

**Issue by harishgan** [atom/atom#15172]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'createObjectStore' of undefined

```
At C:\Users\Midhu\AppData\Local\atom\app-1.18.0\resources\app\src\state-store.js:17

TypeError: Cannot read property 'createObjectStore' of undefined
    at IDBOpenDBRequest.dbOpenRequest.onupgradeneeded (~/AppData/Local/atom/app-1.18.0/resources/app/src/state-store.js:17:19)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?
