### ISSUE TITLE
Atom crash at launch

### ISSUE THREAD

**Issue by bnjjj** [atom/atom#15176]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have downloaded the last beta version of atom 1.19.0-beta7 and when I launch for the first time Atom it doesn't display anything. After checking the console, it display some errors. (check screen in Additional information)

### Steps to Reproduce

1. Download atom 1.19.0-beta7
2. Launch atom Beta on Mac OS Sierra 10.12.6 (16G29)

**Expected behavior:** Display welcome tab in atom

**Actual behavior:** Nothing display, just empty window

**Reproduces how often:** Always

### Versions

atom 1.19.0-beta7
OS: Mac Os Sierra 10.12.6 (16G29)

### Additional Information

screenshot of console http://i.imgur.com/kLx7nFD.png

**Comment by rsese** [comment]
Thanks for the report - was there any difference at all when you ran in safe mode or temporarily reset to factory defaults, or did you see the exact same errors in both cases?

**Comment by rsese** [comment]
I also just updated to 1.19.0-beta7 on macOS 10.12.6 but didn't see the same error after restarting.

**Comment by bnjjj** [comment]
Ok I have found issue, it was due to very very old package. Sorry :)
