### ISSUE TITLE
Syntax style of Rust lifetimes gets overridden by unknown source

### ISSUE THREAD

**Issue by adrian5** [atom/atom#15174]
### Description

The Rust language uses the syntax `'name` to denote a lifetime qualifier. This gets overridden by a persistent styling whose origin I cannot pin down.

![style-override](https://user-images.githubusercontent.com/5426924/28999071-bf44007c-7a3a-11e7-90e7-025e3ddcdf98.png)

### Steps to Reproduce

(I tried to get confirmation through multiple channels, but found nobody willing)

1. Vanilla Atom
2. Install [language-rust](https://atom.io/packages/language-rust)
3. Create a `file.rs` and write e.g. `'test` in it; save the file.

**Expected behavior:**

Lifetime matches the given syntax highlighting theme.

**Actual behavior:**

Lifetime has cyan color _regardless of the syntax- and ui theme_ used.

**Reproduces how often:**

Persistently/Always.

### Versions

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
---
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.12+
git 2.9.3
```

OS: Xubuntu 16.10

### Additional Information

Relevant discussion: [atom-language-rust/issues/90](https://github.com/zargony/atom-language-rust/issues/90)

**Comment by DamnedScholar** [comment]
The `language-rust` package has its own [`styles.less`](https://github.com/zargony/atom-language-rust/blob/master/styles/rust.less) file, which has a rule for coloring lifetimes. This seems intentional on the part of the package creator and should be easy to override in your local stylesheet.

**Comment by adrian5** [comment]
Thanks again, replied to you in the Atom forum.
