### ISSUE TITLE
[from v1.19] highlight decoration node can be re-rendered which cause keyframe animation restart.

### ISSUE THREAD

**Issue by t9md** [atom/atom#15185]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This issue started from v1.19 which use new editor-rendering with etch.

CC @as-cii 

#### Short summary

From v1.19, highlight decoration node is re-rendered in it's lifetime which cause keyframe animation unwillingly re-started.
This was not issue in v1.18 where highlight decoration node was stable in it's lifetime.

See, each removal of brackets-matcher's highlight cause fadeout animation re-started.
Which is because highlight node of `class=t9md-test-flash` is re-created at that timing.

![decoration-node-unstable2](https://user-images.githubusercontent.com/155205/29040638-b6cee3ce-7bea-11e7-9aa3-4168238b2b6d.gif)

### Detail

When highlight decoration is created by `editor.decorateMarker`, corresponding `<div class="highlights">` node is created at top of LinesComponents.
Child nodes of this div represent actual decoration style.

- Till v1.18 these nodes are stable in its lifetime.
- From v1.19 with new editor-rendering, these nodes can be re-rendered during it's lifetime.

This is not problem when highlight class is simply set `background:` color.
But it's become problem when highlight class specify animation.
Lets' say

- I have set decoration which `class=flash-anime` which will be destroyed after 1.0 sec
- `flash-anime` css class have keyframe animation which fadeout flash during 1.0 sec.
- When Atom re-render(re-create) this decoration node within 1.0 sec, it cause re-start fadeout keyframe animation.
- This issue is more likely to happen when brackets-matcher involved, which create/remove decorations and it cause existing highlight node in the same LinesComponents **re-rendered**.

GIF: Animation in 10sec is separated into three because of re-render of highlight node.

<img width="1611" alt="untitled_ ___github_atom-vim-mode-plus" src="https://user-images.githubusercontent.com/155205/29040215-25968c64-7be9-11e7-9de7-9240fdf6baac.png">

GIF: style recalculation highlight decoration re-created which cause animation restart.

<img width="537" alt="untitled_ ___github_atom-vim-mode-plus" src="https://user-images.githubusercontent.com/155205/29040205-1a420550-7be9-11e7-9dd6-ac28be8c9ae5.png">

### Steps to Reproduce

I can reproduce this issue with safe-mode.

1. Prepare sample.txt and custom-style.

- sample.txt

`{a: 1}`

- style.less

```less
@keyframes t9md-test-animation {
  from { background-color: #5b91c8; }
  to { background-color: transparent; }
}

atom-text-editor .t9md-test-flash .region {
  animation-name: t9md-test-animation;
  animation-fill-mode: forwards;
  animation-duration: 10.0s;
  animation-iteration-count: 1;
}
```

2. Open sample.txt, place cursor at first line.
3. Paste following code in chrome-dev-tools console.

This code does.
- highlight inner range of `a: 1`(inner range of curly brackets).
- marker will destroyed after 10sec.
- highlight class is `t9md-test-flash` which fadeout background color in 10sec.

```javascript
(function flashreproduceIssue() {
  const editor = atom.workspace.getActiveTextEditor()
  const cursorPosition = editor.getCursorBufferPosition()
  const scanRange = editor.bufferRangeForBufferRow(cursorPosition.row)
  editor.scanInBufferRange(/{.*?}/, scanRange, ({range}) => {
    const innerRange = range.translate([0, +1], [0, -1])
    const marker = editor.markBufferRange(innerRange)
    editor.decorateMarker(marker, {type: "highlight", class: "t9md-test-flash"})
    setTimeout(function () {
      marker.destroy()
      console.log("destroyed");
    }, 10000);
  })
})()
```

4. Within 10sec, move cursor left/right to cause add/remove brackets-macher's highlight.

And see how keyframe animation is re-started because of re-creation of highlight node.

**Expected behavior:** [What you expect to happen]

Node used for highlight decoration is stabled(not re-rendered).

**Actual behavior:** [What actually happens]

Node used for highlight decoration is re-rendered, cause keyframe animation re-started.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%.

### Versions

```
Atom    : 1.19.0-beta7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

I use fadeout flash effect with keyframe animation a lot in [vim-mode-plus](https://atom.io/packages/vim-mode-plus) to give feedback to user.
E.g. when yank inner range of brackets, flash inner bracket range.

From v.1.19 cursor move cause brackets-matcher's highlights add/removal which cause vmp's flash effect re-started unwillingly.

**Comment by t9md** [comment]
I don't know etch's handling to avoid unnecessary re-rendering.

React use **key** to check identity of list item which avoid unnecessary re-creation of same item.
https://facebook.github.io/react/docs/lists-and-keys.html#keys

**Comment by nathansobo** [comment]
Looking into this. The highlight nodes are indeed associated with keys and appear to be getting updated rather than created and destroyed. It may be that Etch's reconciliation routine is unnecessarily removing the nodes and then adding them again.
