### ISSUE TITLE
1.19, Linux: Middle-clicking an unsaved tab causes entire desktop to be unresponsive to clicks

### ISSUE THREAD

**Issue by AgentME** [atom/atom#15197]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm on Ubuntu 16.04. Atom 1.18.0 was fine, but since updating to Atom 1.19.0, if I have a file with unsaved changes and I try to close the tab by middle-clicking on the tab, then a modal pops up (Are you sure you want to close the file without saving?), but I can't click on anything. The cursor doesn't change no matter what I hover over and no clicks register on the modal's buttons or even other (non-Atom) windows. Clicking another window doesn't focus it, bring it to the front, or get any reaction.

My computer is still responsive to keyboard inputs, though even if I alt-tab to another window, nothing reacts to my mouse still. I have to press escape on Atom's closing-confirmation modal or otherwise close it before anything reacts to my mouse again.

If I close the file tab in any other way (clicking the X button, or pressing ctrl-w), the modal and my mouse work perfectly normal. With little non-web UI experience, I'd guess the issue has to do with some kind of blocking call (like the modal) happening or a lock being hogged improperly during the middle-click event handler.

### Steps to Reproduce

1. Be on Ubuntu 16.04 (?)
2. Open Atom, open a file in Atom, and make some changes to the file without saving.
3. Middle-click on the file's tab.

**Expected behavior:** [What you expect to happen]

My mouse to work as usual: for the modal to be clickable, and to have the ability to click on other windows freely even while the modal is still open.

**Actual behavior:** [What actually happens]

See description.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%, tested with safe mode and a new ~/.atom directory too.

### Versions

```
$ atom --version
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm --version
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
$ uname -a
Linux canyon 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by neok-m4700** [comment]
Reproduced on 17.04 (Ubuntu MATE), can navigate with keyboard and use dialogs with keystrokes, but atom dialogs are inresponsive to mouse clicks (all frozen). Can't reproduce on 1.18.0; with the same build toolchain.

```bash
$ atom --version
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by dmmulroy** [comment]
This is a known issue with electron see: https://github.com/electron/electron/issues/10182

**Comment by 50Wliu** [comment]
We're using Electron 1.6.9 though.  Maybe it's also an issue in 1.6.x.

**Comment by dmmulroy** [comment]
Also found this: https://github.com/atom/atom/pull/15183

**Comment by ungb** [comment]
I can repro the issue.  Keyboard still seems to work on the dialog.  I'm looking into #15183 to see if it was caused by this change or not.

**Comment by ungb** [comment]
This is unrelated to #15183.  I was able to confirm when I reverted the changes in the PR, this issue still occurs.  Looks like it's most likely caused by an electron issue mentioned in https://github.com/atom/atom/issues/15197#issuecomment-321633842

**Comment by rdelpeso** [comment]
To add a couple details, on CentOS Linux release 7.3.1611 (Core) + xfce4-panel 4.12.0 (Xfce 4.12) I have the same issue (see #15278 for details) but unlike OP I get this issue on the following interactions:
- middle click
- left click the close X button

Also like the OP, I am able to interact with the dialogue if I use other methods to close the tab, such as:
- right click -> close tab
- alt+f4

**Comment by MattCz** [comment]
No middle mouse click is not working and I can't close tabs by doing that... Thanks guys! :/

**Comment by ungb** [comment]
@MattCz Can you provide more info?  which OS are you using? and what exactly are the repro steps for your situation.

Do you mean middle click doesn't work for closing tabs or doesn't work at all?
Also, which version of atom you're using (to make sure it was related to the latest change)
you can find this info by running `atom -version`

**Comment by MattCz** [comment]
Middle click doesn't work for closing tabs when there are more tabs opened than the window width is. It's a behavior after update to latest version 1.19.3 from 1.19.2 on Windows. When there are more tabs opened I can't close any by middle click. Instead there is a "scrolling" cursor and I can move whole tab pane (behavior is similar to shift+mouse scroll). Btw. fast scrolling by middle click could be useful but for editor, not tabs.. Imo the best solution if it comes to tabs and scrolling in editor is the one implemented in Notepad++.

**Comment by ungb** [comment]
Thanks for reporting @MattCz and providing more info.  I filed https://github.com/atom/atom/issues/15471 and cc you on the issue.
