### ISSUE TITLE
Folding with soft wrap enabled doesn't update text editor view correctly as of 1.19

### ISSUE THREAD

**Issue by calebmeyer** [atom/atom#15190]
### Prerequisites

- [x]    Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
- [x]    Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
- [x]    Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
- [x]    Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
- [x]    Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When folding text using `editor:fold-at-indent-level-2`, the visual representation of some of the folds is not updated correctly

### Steps to Reproduce

1. Open [this file](https://github.com/calebmeyer/git-links/blob/f5100a252734bc4b4de55dcc4b85b743d456d551/lib/git-links.coffee)
1. Run `editor:toggle-soft-wrap` to enable soft wrap if it is not already on
1. Run `editor:fold-at-indent-level-2` using the command palette

Size of the Atom window may be related /cc: https://github.com/atom/atom/issues/15190#issuecomment-322209970

**Expected behavior:**
Each element at the second level of indentation is folded, and shows as folded

**Actual behavior:**
Some (or none) of the elements are showing as folded.
Moving the cursor with the arrow keys navigates inside the fold
Moving the cursor with vim-mode-plus `hjkl` navigates over the fold

**Reproduces how often:**
I am able to see the problem in safe mode about 80% of the time. Almost always, at least one fold gets folded correctly, sometimes two. Very rarely all folds will show correctly.

### Versions
Windows 10 creator's update
`atom --version`
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
`apm --version`
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.13.0.windows.1
visual studio 2015

### Additional Information
Screenshots:
My configuration:
![mine](https://user-images.githubusercontent.com/3342777/29088025-8273c790-7c3d-11e7-9744-4fda97adbe34.png)

Safe Mode
![safe](https://user-images.githubusercontent.com/3342777/29088034-89210670-7c3d-11e7-8fa7-8d14888a8c93.png)

**Comment by calebmeyer** [comment]
Further notes:
- Clicking one of the fold indicators in the gutter makes all the ones for that fold disappear (unfolds the element).
- Forcing the cursor to move within one of the half-folded areas causes it to unfold (the markers in the gutter disappear)

**Comment by Arcanemagus** [comment]
This is likely the same root issue so I'll just comment here, let me know if this should be filed as a separate issue.

If you checkout https://github.com/AtomLinter/linter-eslint/commit/cd7de8d392926363cef29ca5dcb27e36b389423c and then attempt to fold [this line](https://github.com/AtomLinter/linter-eslint/blob/cd7de8d392926363cef29ca5dcb27e36b389423c/src/main.js#L48) the editor doesn't fold anything, instead all lines that _would_ have folded show the unfold marker as the screenshots above.

Note that if you fold [validScope](https://github.com/AtomLinter/linter-eslint/blob/cd7de8d392926363cef29ca5dcb27e36b389423c/src/main.js#L44) above it before attempting to fold the main export, and then fold the main export _both_ `validScope` and `module.export` are unfolded, but show the unfold marker on all lines:

![image](https://user-images.githubusercontent.com/427137/29107353-a71bdfb4-7c8e-11e7-9294-350473e07cd1.png)

**Comment by nathansobo** [comment]
I'm having trouble reproducing this. Is there particular content someone can share that reproduces the behavior?

**Comment by calebmeyer** [comment]
I'm able to reproduce it with my own package I wrote, [git links](https://github.com/calebmeyer/git-links/blob/f5100a252734bc4b4de55dcc4b85b743d456d551/lib/git-links.coffee).

Interestingly, it only happens when the window is large:
![atom-folding](https://user-images.githubusercontent.com/3342777/29276761-3dd6f1ce-80d5-11e7-85e7-1bcbac723a3b.gif)

**Comment by nathansobo** [comment]
@ungb @Ben3eeE @rsese I could you your help getting clarity on what is going on here.

**Comment by Ben3eeE** [comment]
@calebmeyer Thank you so much for the gif. It gave the information I need to reproduce 🙇 

----

@nathansobo It happens because @calebmeyer has toggled soft wrap for the editor. I was able to reproduce with the file he linked.

1. Open Atom with the file he linked
1. Run `editor:toggle-soft-wrap`
1. Shrink the Atom window so there is soft wrapping
1. Enlarge the Atom window so there is no soft wrapping
1. Run `editor:fold-at-indent-level-2`

**Comment by Arcanemagus** [comment]
> Edit: I am unable to reproduce the issue with soft wrap disabled but with soft wrap enabled I can reproduce even with just running the command I don't think you need to shrink and enlarge the Atom window.

I also have soft wrap enabled, but that content doesn't _trigger_ soft wrap, so another vote for it not being necessary to trigger this.

**Comment by Ben3eeE** [comment]
Agree. I have tweaked the steps to reproduce in the body of the issue.

**Comment by nathansobo** [comment]
Thanks everyone for the reports and excellent reproduction steps. This should be fixed this week with the next patch release. Sorry for the bumps. We made some pretty aggressive changes in 1.19 and some bugs made it through.

**Comment by Arcanemagus** [comment]
Sorry for not reporting things sooner in the betas 😉.
