### ISSUE TITLE
TextBuffer::onDidReload never fires for external changes

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#15200]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`TextEditor::onDidReload` appears to not be firing, at least within the 10 second timeout of package specs.

### Steps to Reproduce

1. Check out [`linter-eslint@8.2.1`](https://github.com/AtomLinter/linter-eslint/tree/v8.2.1)
2. Run the package specs
3. Note that [two](https://github.com/AtomLinter/linter-eslint/blob/v8.2.1/spec/linter-eslint-spec.js#L241) [specs](https://github.com/AtomLinter/linter-eslint/blob/v8.2.1/spec/linter-eslint-spec.js#L285) are failing.

**Expected behavior:**

`TextEditor::onDidReload` fires when the file is reloaded due to the external process changing the file.

**Actual behavior:**

The specs are expecting [a notification](https://github.com/AtomLinter/linter-eslint/blob/v8.2.1/spec/linter-eslint-spec.js#L92-L95) that the fix was complete from ESLint (which triggers), as well as Atom declaring via `TextBuffer::onDidReload` that it has finished reloading the file after the external ESLint process has finished changing the file [here](https://github.com/AtomLinter/linter-eslint/blob/v8.2.1/spec/linter-eslint-spec.js#L82-L87).

**Reproduces how often:**

100% of the time.

### Versions

```
Using Atom version:
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
Using APM version:
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.11
git 2.13.0
```

Tested on Windows 10 x64, and Ubuntu 14.04 x64.

### Additional Information

Possibly related to the problem in https://github.com/atom/atom/issues/14189, likely caused by https://github.com/atom/atom/pull/14435.

This is a regression from Atom v1.18.0, where these specs worked properly.

**Comment by maxbrunsfeld** [comment]
Ok, for posterity, the problem was only in the tests. The code that fires the `onDidReload` event now relies on the built-in `Date.now` method, which is mocked by default in tests.

**Comment by Arcanemagus** [comment]
If you run into this issue in your own specs, you can work around it by adding `jasmine.unspy(Date, 'now')` to the `beforeEach` of your spec to disable the mocking of `Date.now`. Assuming of course that your specs don't rely on that mocking. If your specs _do_ rely on that, you should be able to get this to work still by calling `advanceClock`.
