### ISSUE TITLE
Touch Bar support

### ISSUE THREAD

**Issue by arguiot** [atom/atom#15206]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There is currently no support of the Touch Bar on the new MacBook Pro 2017

### Steps to Reproduce

No steps

**Expected behavior:** Should have useful shortcuts on the Touch Bar

**Actual behavior:** Nothing

**Reproduces how often:** 100%

### Versions

macOS Sierra:
- `atom --version`:
```
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
- `apm --version`:
```
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.3
```
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
> There is currently no support of the Touch Bar on the new MacBook Pro 2017

Yes there is.  We are, however, leaving it to package developers to create TouchBar actions.  I know that there are already a few in the packages listing: https://atom.io/packages/search?q=touchbar.
