### ISSUE TITLE
Half of the workspace is unusable

### ISSUE THREAD

**Issue by Saul-BT** [atom/atom#15211]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The workspace only reaches the middle of the screen, in the empty half can not take any action.
This problem has only affected large projects like [this.](http://i.imgur.com/rTeuOiv.png)

### Steps to Reproduce

1. Be on Windows 10 Home
2. Open a large project on Atom

**Expected behavior:** Open the project without problems

**Actual behavior:** Half of the workspace is unusable

**Reproduces how often:** Always in these last 3 weeks

### Versions

OS: Windows 10 Home v.1703

Atom: 1.19.0
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0

apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python
git 2.8.1.windows.1
visual studio

**Comment by 50Wliu** [comment]
@Saul-BT please reupload your image; it doesn't look like it was uploaded correctly.

**Comment by Saul-BT** [comment]
updated

**Comment by 50Wliu** [comment]
Hmm...it looks like you may have accidentally changed the pane size.  Try pressing <kbd>Ctrl+Alt+=</kbd> a few times.

**Comment by Saul-BT** [comment]
It has been solved, Thank you very much.

**Comment by 50Wliu** [comment]
Glad to hear that it's fixed @Saul-BT!
