### ISSUE TITLE
Editor crashes while editing files on network drive

### ISSUE THREAD

**Issue by zwheaton** [atom/atom#15223]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashes while editing a file from a network drive. 
I use a drive mounted from my macbook on my windows computer to edit from time to time. While editing the files, if at any time I try to run the files (e.g. `rails s`) or any other command, or sometimes just for no reason, I get the "The Editor has crashed" alert and have to reload the window. Nothing is showing up in the developer tools. I've tried both mounting the drive in windows and directly accesing them via the file browser (`\\mymacbook\dev\projectfolder`)

### Steps to Reproduce

1. Open a file from a network/remote drive
2. Run a command  on the files (e.g. `npm install`, `bundle exec`) and the editor will crash

**Expected behavior:** Editor doesn't crash while editing remote files

**Actual behavior:** Atom crashes and I have to fully reload the program

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by ungb** [comment]
I was able to repro this issue by doing the following:
Have a mac SMB share with write/read access

Repro steps on windows:
1. Open the mac SMB share on windows example: \\Mac-computer-name\share
2. Create a new folder called 'newFolder'
3. Open `newFolder` on Atom
4. On Windows, do `git clone https://github.com/request/request` in newFolder

Expected: editor shouldn't crash 
Actual: editor crashes
