### ISSUE TITLE
Atom crashed when tried to open multiple files from remote disk

### ISSUE THREAD

**Issue by bhaskarmac** [atom/atom#15229]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom editor crashed when tried to open multiple files from remote disk

### Steps to Reproduce

1. Connect to remote disk using smb
2. Select multiple files from the shared folder
3. And editor crashed

**Expected behavior:** Editor should not crash if multiple files are opened from remote disk

**Actual behavior:** Editor is crashing when opened multiple files from remote disk connected via smb

**Reproduces how often:** 60%

### Versions

atom --version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm --version
apm  1.17.0
npm  3.10.5
node 6.9.5 x64
python 2.7.6
git 1.9.1

OS - ubuntu 14.04 LTS

**Comment by rsese** [comment]
Thanks for the report - it looks like you're running a slightly older version of Atom (1.19.0 was just released recently), can you install the latest version and let us know if you still get the crash?  If you do, can you share any [crash logs](http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs)?

And just to get more information, can you confirm if selecting a single file works fine?  When you say multiple files, does the number matter (will it crash if 2 files are selected or does it have to be more than 2)?

**Comment by bhaskarmac** [comment]
I have selected 4 files and it crashed. I will install the Atom 1.19.0 and get back if still crash persist or not.

**Comment by bhaskarmac** [comment]
Thank you very much @rsese After installing Atom 1.19.0 the issue got resolved. Now I can open multiple files from a network drive. Thanks for the suggestion.
