### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by HebaruSan** [atom/atom#15220]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode - **doesn't crash in safe mode, but it still crashes in normal mode and I do not wish to switch to safe mode for all usage**
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom - **unreasonable, I cannot read 4600 issues to find this exact crash, but I don't see it on the first page**
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages - **irrelevant, not looking for a package**

### Description

Since updating to Atom 1.19.0 (my tenth update), it crashes every time I run it.

### Steps to Reproduce

0. Install and enable the [git-gui] package

1. Launch Atom
2. Press ctrl-comma to open settings
3. Click Packages

OR simply:

1. Launch Atom (after doing the above steps once)

**Expected behavior:** Atom runs and I'm able to browse the packages list

**Actual behavior:** The deprecated packages never finish loading, and the core app seg faults:

![image](https://user-images.githubusercontent.com/1559108/29142005-12ec11dc-7d16-11e7-8cb4-8d1aa06bc77c.png)

stdout and ~/.atom/nohup.out both say:

```
/usr/bin/atom: line 130: 19908 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
(node:19908) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 focus listeners added. Use emitter.setMaxListeners() to increase limit
(node:19908) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 blur listeners added. Use emitter.setMaxListeners() to increase limit
Failed to generate minidump.
```
("Failed to generate minidump." is repeated 1210 times on that line, omitted for brevity.)

Browsing installed packages is kind of important after an update because some old packages might need to be updated, disabled, configured, or removed.

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0
```

Ubuntu 17.04

### Additional Information

Only happens if [git-gui] is installed and enabled.

[git-gui]: https://github.com/andrewrynhard/atom-git-gui

**Comment by maxbrunsfeld** [comment]
Since you're not experiencing this in safe mode, some package that you have installed must be contributing to the crash. Could you share your list of installed packages? You might also want to manually try disabling different packages to pinpoint which particular package is causing the issue.

**Comment by HebaruSan** [comment]
Here's the contents of ~/.atom/packages. I can't disable packages other than by deleting these directories, because that option is on the screen that crashes. Similarly, some of these are _already_ disabled, but I can't check which ones because the screen that would give me that information crashes.

```
advanced-open-file
ambiance
ambiance-dark-syntax
ambiance-dark-ui
ambiance-pro-ui
api-docs
atom-beautify
atom-html-preview
atom-jq
atom-make
atom-material-numix-syntax
atom-material-syntax
atom-material-ui
atom-runner
atom-sharp
atom-ternjs
atom-ubuntu-dark-ui
atom-yeoman
audio
autocomplete-en-en
autocomplete-haskell
autoupdate-packages
browser-plus
build
build-make
build-tools
build-tools-make
busy
busy-signal
coffee-compile
custom-folds
dark-flat-ui
elastic-tabstops
file-icons
file-types
focus-follows-mouse
git-clone
git-control
git-diff-details
git-gui
git-log
git-plus
git-status
git-time-machine
haskell-ghc-mod
highlight-selected
ide-haskell
ide-haskell-cabal
ide-haskell-repl
imagemin
indent-guide-improved
intentions
irc
json-schema
language-awk
language-diff
language-haskell
language-patch
language-pug
language-sln
language-vala
line-diff-details
linter
linter-coffeelint
linter-jsonlint
linter-pug
linter-python
linter-stylint
linter-ui-default
MagicPython
man
markdown-preview-enhanced
markdown-preview-plus
merge-conflicts
minimap
minimap-codeglance
minimap-git-diff
minimap-split-diff
mixup-dark-syntax
monokai-ubuntu
npm-debug.log
npm-plus
numix-dark-ui
numix-ui
pdf-view
preview
remember-folds
run-command2
script
solarized-dark-bold-syntax
solarized-dark-ui
solarized-light-ui
solarized-one-dark-syntax
solarized-one-light-ui
sourcerer
split-diff
Stylus
term
transpile
tree-view-autoresize
tree-view-git-branch
tree-view-git-status
xmldoc-snippets
```

**Comment by maxbrunsfeld** [comment]
You can enable or disable packages by editing `~/.atom/config.cson`, which you can access using the command `Application: Open your Config`. There should be a section called `disabledPackages` under `core`, like this:

```coffee
'*':
  core:
    # ...
    disabledPackages: [
      # ...
    ]
```

You can disable or enable packages by adding or removing their names from this section.

**Comment by HebaruSan** [comment]
Thanks, I checked my config.cson and split the disabled packages into a separate list in my previous comment.

**Comment by HebaruSan** [comment]
@maxbrunsfeld , a binary search of the list revealed that [git-gui] triggers the crash. I can turn the rest of my packages back on and there's no crash, but whenever git-gui is enabled, the packages tab freezes.

(I removed the full list from the earlier comment to reduce clutter. I'll look for a place to add this to the main issue report as well.)

[git-gui]: https://github.com/andrewrynhard/atom-git-gui

**Comment by maxbrunsfeld** [comment]
Thanks so much for that report @HebaruSan. That's really helpful.

**Comment by Ben3eeE** [comment]
I was not able to reproduce this with Atom 1.20.0-beta1 on Windows 7. Also I could not get the `git-gui` package to activate without throwing this exception https://github.com/andrewrynhard/atom-git-gui/issues/10.

**Comment by VadimDor** [comment]
Can confirm this on Windows 8.1 x64 only with Atom 1.19.1 and 1.19.2. 
With 1.18 all was OK. 
Disabling git-gui helps, thanks @HebaruSan  
Crash reports attached
[Atom Crashes.zip](https://github.com/atom/atom/files/1235539/Atom.Crashes.zip)

**Comment by noec** [comment]
It still crashes in Atom 1.23.2 and git-gui 0.1.27.
Only disabling or removing can be solved this issue.

**Comment by NullVoxPopuli** [comment]
I don't have git-gui installed, and am getting:

```
/usr/bin/atom: line 141: 12388 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
<memory>:1: Invalid color constant '##d3d3d3'
Gtk-Message: 09:01:51.687: (for origin information, set GTK_DEBUG): failed to retrieve property `ChromeGtkFrame::frame-color' of type `GdkColor' from rc file value ""##d3d3d3"" of type `gchararray'
```
