### ISSUE TITLE
Horizontal scrolling is always favored over vertical scrolling

### ISSUE THREAD

**Issue by ozthegreat** [atom/atom#15239]
Hey,

I can't see anything about it in the release notes but it's possible I've missed something. I've just updated to Atom 1.19.0 (OS X 10.12.6, MacBook Pro) and for some reason the horizontal scroll seems to have started catching when it shouldn't. It's hard to explain but, if you're using two fingers on the trackpad to vertically scroll up and down a file then, since the update, as you scroll it seems to catch horizontally much more often and start scrolling that way instead.

Has any of the sensitivity been changed? Am I missing something?

---

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On long files where horizontal scrolling is possible the horizontal scrolling sensitivity is now higher and kicks in when scrolling vertically.

### Steps to Reproduce

1. Make sure you're using a Mac.
2. Get a long file with lines that exceed the width of the screen.
3. Use two fingers on the trackpad to scroll vertically down the screen, if your fingers are at anything other than perfectly aligned then the horizontal scroll kicks in much sooner than it did before.

**Expected behavior:**

To scroll vertically, smoothly.

**Actual behavior:**

As you scroll vertically, it start scrolling horizontally

**Reproduces how often:**

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by rsese** [comment]
Thanks for reaching out @ozthegreat - the issue template provides super helpful baseline information so if you can create a new issue or edit your issue body to fill in the template we can go from there.    In particular, please also go through the `Prerequisites` section if you haven't already and try the documented debugging steps (http://flight-manual.atom.io/hacking-atom/sections/debugging/) and let us know if that makes a difference or not.

I don't believe there were any specific changes around scroll sensitivity but I wonder if this related to the Electron upgrade in 1.19.0.....

---

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by rsese** [comment]
I'm not sure if I'm noticing it more because of this issue, but I think I see what you're talking about - I'll try to downgrade to 1.18.0 later to compare.

**Comment by ozthegreat** [comment]
@rsese Sorry, I didn't fill it out cause I wasn't sure if it was actually a bug or not!! Yeah it's most prominent on long files with lines extending past the screen. Particularly if you try and scroll slowly.

Thanks!

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On long files where horizontal scrolling is possible the horizontal scrolling sensitivity is now higher and kicks in when scrolling vertically.

### Steps to Reproduce

1. Make sure you're using a Mac.
2. Get a long file with lines that exceed the width of the screen.
3. Use two fingers on the trackpad to scroll vertically down the screen, if your fingers are at anything other than perfectly aligned then the horizontal scroll kicks in much sooner than it did before.

**Expected behavior:**

To scroll vertically, smoothly.

**Actual behavior:**

As you scroll vertically, it start scrolling horizontally

**Reproduces how often:**

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by rsese** [comment]
Thanks @ozthegreat 👍  I installed 1.18.0 and see that the behavior was different, vertical scrolling didn't catch horizontally much at all - I'll ask the team to take a look.

I'll go ahead and copy/paste the issue template you filled out to the issue body (so folks won't have to read through a thread and the details they need are right there 📝).

**Comment by rsese** [comment]
Also tentatively added the `mac` label because I couldn't reproduce with my Windows 10 machine's trackpad.

**Comment by rsese** [comment]
Added to the project board but /cc @as-cii on another potential regression 📝

**Comment by ozthegreat** [comment]
@rsese excellent thanks, glad it's not just me!!

**Comment by nathansobo** [comment]
Thanks for the report. This revealed a pretty dumb coding error that I made when revamping the editor rendering layer. We'll have a fix out later this week.
