### ISSUE TITLE
Pressing "Cancel" on an unsaved buffer dialog will not cancel a restart

### ISSUE THREAD

**Issue by jbrowning** [atom/atom#15238]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

**Pressing "Cancel" on the unsaved buffer dialog will not cancel a restart**

Atom requests a restart in some situations, such as when a plugin has been updated. If one has an unsaved buffer open in a project-less window, after pressing "restart", the normal unsaved file dialog is presented with, on macOS at least, "Save", "Don't Save", and "Cancel" buttons. In this scenario, "Save" and "Don't Save" work as expected, but pressing "Cancel" will immediately re-present the same dialog. This can be especially problematic when the unsaved buffer is in another tab in the same window as one cannot switch tabs to inspect the file and determine if it should be saved or not.

### Steps to Reproduce

1. Open a new project-less window and buffer
2. Type in some content
3. Trigger a restart by either updating plugins or opening a developer console and entering `atom.restartApplication()`
4. Press "Cancel"

**Expected behavior:**
The restart operation should be canceled, returning me to the state I was in before I pressed "restart".

**Actual behavior:**
I am immediately presented with the same unsaved buffer dialog

**Reproduces how often:**
Every time

### Versions

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
macOS: 10.12.6

**Comment by rsese** [comment]
Thanks for the report!  I couldn't reproduce with Atom 1.19.0 on macOS 10.12.6 but with one extra bit of detail to this step I can reproduce (h/t 🎩  @50Wliu):

> 1. Open a new buffer and type in some content

I can only reproduce if the buffer isn't part of an open project - if there is an open project, Atom will just restart without prompting.  I'll tweak your steps to reproduce.

**Comment by jbrowning** [comment]
Ah, yes. Sorry, I was testing with a new project-less window so I forgot to mention that aspect. I've updated the issue to add this detail.
