### ISSUE TITLE
KDE wrong cursor theme in Atom window

### ISSUE THREAD

**Issue by olegantonyan** [atom/atom#15230]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom 1.19 openSUSE 64 bit KDE wrong mouse cursor theme
Normal cursor outside Atom window: https://yadi.sk/i/p5bHnpdy3LsZ7e
Cursor in the Atom window: https://yadi.sk/i/uShAUU803LsY5b

### Steps to Reproduce

1. Set Adwaita cursor theme in KDE systemsettings
2. Launch Atom and see how it changes in Atom's window

**Expected behavior:** Cursor theme must be global for all windows. Atom must not override it

**Actual behavior:** Cursor changed

**Reproduces how often:** Always

### Versions

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 3.6.0
git 2.14.0

**Comment by neok-m4700** [comment]
On Ubuntu MATE, these  are the icons that show under the atom window, regardless of what user theme is applied, on 1.19.0 ...
![x11_cursors_by_blackevilweredragon](https://user-images.githubusercontent.com/13423344/29183105-b3e84b0a-7e01-11e7-879b-3d23c9f1bedb.png)

strange, where does that come from ?

**Comment by olegantonyan** [comment]
I've created an issue for Electron since it reproduces there https://github.com/electron/electron/issues/10705

**Comment by 50Wliu** [comment]
Thanks @olegantonyan.  I'll be closing this issue since it'll naturally be fixed on our end when the Electron issue is fixed.
