### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by akaifi** [atom/atom#15247]
[Enter steps to reproduce:]

1. Updating atom from 1.10 to 1.19 and .....
2. I can not click update packages !!

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: "Fedora release
**Thrown From**: Atom Core

### Stack Trace

Uncaught RangeError: Invalid array length

```
At /usr/share/atom/resources/app/src/text-editor-component.js:2785

RangeError: Invalid array length
    at TextEditorComponent.populateVisibleTiles (/usr/share/atom/resources/app/src/text-editor-component.js:2785:45)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/usr/share/atom/resources/app/src/text-editor-component.js:363:16)
    at TextEditorComponent.updateSync (/usr/share/atom/resources/app/src/text-editor-component.js:266:16)
    at etch.getScheduler.updateDocument (/usr/share/atom/resources/app/src/text-editor-component.js:220:46)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/src/view-registry.js:187:15)
    at /usr/share/atom/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:37.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.4 
atom-runner 2.7.1 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
autocomplete-modules 1.6.10 
autocomplete-php 0.3.7 
autocomplete-python 1.10.0 
busy-signal 1.4.3 
caniuse 0.9.2 
color-picker 2.2.5 
docblockr 0.11.0 
file-icons 2.1.10 
flex-tool-bar 0.12.0 
git-plus 7.9.3 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-jsonlint 1.3.0 
linter-php 1.3.2 
linter-phpcs 1.6.7 
linter-phpmd 1.5.3 
linter-sass-lint 1.7.4 
linter-shellcheck 1.4.4 
linter-ui-default 1.6.4 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
open-in-browsers 0.0.30 
open-recent 5.0.0 
open-terminal-here 2.3.1 
php-twig 4.0.0 
pigments 0.40.2 
project-manager 3.3.5 
react 0.16.2 
Remote-FTP 1.1.3 
seti-syntax 1.1.3 
seti-ui 1.9.0 
svg-preview 0.11.0 
sync-settings 0.8.2 
todo-show 1.11.0 
tool-bar 1.1.0 
w3c-validation 0.4.0 
webbox-color 0.5.9 
wordpress-api 1.2.2 
```

**Comment by rsese** [comment]
Thanks for the report - is the error reproducible in safe mode (`atom --safe`)?

**Comment by Ben3eeE** [comment]
@akaifi Can you please update to Atom 1.19.1 to see if this error has been fixed?

**Comment by Benjamin-Porquet** [comment]
<img width="682" alt="capture d ecran 2017-08-16 a 08 19 17" src="https://user-images.githubusercontent.com/12295662/29349727-ad934b7a-825b-11e7-85f5-2125df28dc99.png">

<img width="628" alt="capture d ecran 2017-08-16 a 08 19 44" src="https://user-images.githubusercontent.com/12295662/29349731-b1391bec-825b-11e7-83b6-ac9c12e2a645.png">

**Comment by Ben3eeE** [comment]
@Benjamin-Porquet Can you please provide the output of `apm list`?

**Comment by Benjamin-Porquet** [comment]
`Built-in Atom Packages (91)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.5
├── one-light-ui@1.10.5
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.6
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.2
├── autocomplete-html@0.8.0
├── autocomplete-plus@2.35.5
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.4
├── exception-reporting@0.41.4
├── find-and-replace@0.208.3
├── fuzzy-finder@1.5.8
├── github@0.3.4-1
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.12
├── metrics@1.2.6
├── notifications@0.67.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.250.0
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.11
├── styleguide@0.49.6
├── symbols-view@0.116.1
├── tabs@0.106.2
├── timecop@0.36.0
├── tree-view@0.217.2
├── update-package-dependencies@0.12.0
├── welcome@0.36.4
├── whitespace@0.37.2
├── wrap-guide@0.40.2 (disabled)
├── language-c@0.58.1
├── language-clojure@0.22.3
├── language-coffee-script@0.48.7
├── language-csharp@0.14.2
├── language-css@0.42.4
├── language-gfm@0.89.1
├── language-git@0.19.1
├── language-go@0.44.1
├── language-html@0.47.3
├── language-hyperlink@0.16.1
├── language-java@0.27.2
├── language-javascript@0.126.1
├── language-json@0.19.1
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.39.0
├── language-property-list@0.9.1
├── language-python@0.45.3
├── language-ruby@0.71.1
├── language-ruby-on-rails@0.25.2
├── language-sass@0.59.0
├── language-shellscript@0.25.1
├── language-source@0.9.0
├── language-sql@0.25.6
├── language-text@0.7.3
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.1
└── language-yaml@0.30.0

Community Packages (8) /Users/benjaminporquet/.atom/packages
├── atom-autocomplete-php@0.25.6
├── highlight-selected@0.13.1
├── minimap@4.29.6
├── minimap-find-and-replace@4.5.2
├── php-cs-fixer@4.1.0
├── php-twig@4.0.0
├── project-manager@3.3.5
└── remote-edit@1.9.0`

**Comment by Ben3eeE** [comment]
@arnav-gudibande Reported in https://github.com/atom/atom/issues/15340 that this happens with the `remote-edit` package.

**Comment by georgebrindeiro** [comment]
Same error is happening with me:

[Enter steps to reproduce:]

1. Open two panes in Atom
2. Toggle Scroll Sync
3. Scroll down on one of the panes
4. It is not happening consistently, but I was able to reproduce it with two different files with nearly the same content being Scroll Sync'd

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core


### Stack Trace

Uncaught RangeError: Invalid array length

```
At C:\Users\George Brindeiro\AppData\Local\atom\app-1.19.2\resources\app\src\text-editor-component.js:2839

RangeError: Invalid array length
    at TextEditorComponent.populateVisibleTiles (~/AppData/Local/atom/app-1.19.2/resources/app/src/text-editor-component.js:2839:45)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.19.2/resources/app/src/text-editor-component.js:372:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.2/resources/app/src/text-editor-component.js:273:16)
    at TextEditorComponent.didMouseWheel (~/AppData/Local/atom/app-1.19.2/resources/app/src/text-editor-component.js:1532:59)
```

### Commands

```
     -1:36.5.0 scroll-sync:toggle (input.hidden-input)
```

### Non-Core Packages

```
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.5 
meld-diff 0.2.0 
minimap-split-diff 0.3.7 
scroll-sync 0.2.3 
split-diff 1.4.3 
wordcount 2.10.4 
```

**Comment by Ben3eeE** [comment]
Minimal repro steps I can find find `scroll-sync`

1. Install `scroll-sync`. I reproduced with only this package enabled
1. In the `atom/atom` repository open `language-mode-spec.coffee`
1. Split right using `pane:split-right-and-copy-active-item`
1. Run `editor:toggle-soft-wrap` in both editors to **enable** soft wrap if it is off
1. Run `scroll-sync:toggle`
1. In the left editor scroll using the scroll bar up and down several times repeatedly

**Gif using both minimap and scroll-sync**
![invalid arr length](https://user-images.githubusercontent.com/1058982/29398639-0aa75a8e-8326-11e7-83c3-3355c3ef886c.gif)


/cc: @as-cii There are reports of this happening with various packages all when scrolling. Some use remote edit packages. Random guess: some issue with lag and scrolling going out of sync and it's more prominent with `scroll-sync` because you are scrolling two editors at once. If you have minimap enabled it throws the `Invalid Point(NaN, 0)` exception that we have seen from other reports here.
