### ISSUE TITLE
v 1.19.0 freeze editor when  refreshing files 

### ISSUE THREAD

**Issue by evolutionjay** [atom/atom#15249]
<img width="741" alt="wx20170811-102711 2x" src="https://user-images.githubusercontent.com/4468540/29199518-3c5c83f6-7e80-11e7-80d3-46db3572db7d.png">
<img width="310" alt="2017-08-11 10 31 46" src="https://user-images.githubusercontent.com/4468540/29199534-51e71e0c-7e80-11e7-903f-6c5748bbe9f9.png">

this file tree no  'node_modules' dir

how to fixed this problem,  it  freeze editor every few secends.....

**Comment by 50Wliu** [comment]
You most likely have a `~/.git` folder (`%USERPROFILE%\.git` on Windows).  Delete it and your issue should be resolved.
