### ISSUE TITLE
Atom 1.19.0 breaks scrolling in plugin.

### ISSUE THREAD

**Issue by garretwilson** [atom/atom#15242]
With Atom 1.19.0, I can no longer use `Ctrl+Up` and `Ctrl+Down` to scroll using the https://github.com/callum-ramage/ctrl-dir-scroll/ plugin.

Before someone says "go file an issue on the `ctrl-dir-scroll` project" (note I already have: https://github.com/callum-ramage/ctrl-dir-scroll/issues/28), keep in mind that this plugin has not been modified since February of this year (almost eight months ago).

In fact Atom 1.19.0 has significant changes that break several plugins. For example https://github.com/atom/atom/issues/15225 completely breaks https://github.com/Glavin001/atom-beautify , corrupting content and losing data. As far as I can tell, this was caused by changed in Atom, not by something new in the plugin; see https://github.com/atom/atom/issues/15225 .

I suspect this is yet another instance of significant Atom changes in 1.19.0 breaking things. If I don't report it here, then no one may ever look into it. Thanks for any info you can find.

**Comment by 50Wliu** [comment]
@garretwilson there's a fix for this at #15244 and an existing conversation at https://github.com/callum-ramage/ctrl-dir-scroll/issues/28, so I think it's safe to close this.  If you'd rather keep it open though until the shim is merged, please let me know.
