### ISSUE TITLE
Cursor Position Indicator renders inside of characters

### ISSUE THREAD

**Issue by pbarbiero** [atom/atom#15241]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After upgrade from 1.18 to 1.19, Cursor position is broken and causes the cursor to show up INSIDE of the text, rather than the end of each character. See screenshot:
![cursor-indicator](https://user-images.githubusercontent.com/20247733/29179698-e45526ba-7dba-11e7-9a8c-1f095aa48e65.png)

### Steps to Reproduce

1. Normal operation

**Expected behavior:** [What you expect to happen]
Cursor indicator between characters properly

**Actual behavior:** [What actually happens]
Cursor position renders inside of characters

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

1.19.0
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
Windows 10 x64 (latest)
1080p with no dpi scaling.
Changing text size in atom.io has no effect

**Comment by rsese** [comment]
Thanks for the report - I was finally able to update to 1.19.0 but couldn't reproduce on Windows 10.

What font are you using?

**Comment by pbarbiero** [comment]
@rsese 
Default font. 

Figured out it is related to DPI scaling after all. I have per monitor DPI scaling enabled (1.25%) on my laptop monitor, external monitors are 100% (all are 1080p) I can see the issue on all monitors.

**Comment by pbarbiero** [comment]
Did some more testing on my laptop exhibiting the issue.

Undocked, no external monitors, 1080p display at 125% scaling. I see the issue.
Docked, only external monitors, 1080p displays at 100% scaling. I see the issue.

I dont think its related to DPI shift as when it boots up undocked, its at 125% scaling on its internal display and I see the issue. When I do dock, and the displays switch over, the issue remains.

Whats confusing is my home system as I described above exhibits NO issues on either monitor. Is there something else I can provide or grab to help you guys trace this down? Is there some debug info I can capture?

**Comment by august** [comment]
Having this problem as well. It affects not only the editor but the Find box and the Command palette as well.

**Comment by rsese** [comment]
Thanks @pbarbiero - do you see the issue only when using an external monitor?

@august - are you using an external monitor as well?

**Comment by pbarbiero** [comment]
@rsese my home machine is not a laptop so its only external monitors and reproduces on both. My laptop reproduces on internal and external monitors as well.

**Comment by august** [comment]
@rsese No, I'm seeing this just on my laptop screen. I haven't tried with an external monitor, but I will be able to later this week.

**Comment by as-cii** [comment]
Thanks for the report, @august and @pbarbiero! Apologies for this issue, we are aware of it and will try to get a fix out as soon as possible. Unfortunately we are currently unable to reproduce it, so it would be great if you could give us more information about your local installation of Atom. In particular:

* What UI theme are you using?
* What syntax theme are you using?
* Can you share the contents of your personal style sheet?

I'm mainly concerned that something related to styling is causing Atom's measurement mechanism to report the wrong pixel coordinates and, as a result, position UI elements such as cursors weirdly.

Thanks again for your help! ⚡️

**Comment by pbarbiero** [comment]
**UI Theme:** One Dark
**Syntax:** No Caffeine
**Custom stylesheet:** Not applicable. Both of my machines with the issue have the same themes, but only my laptop has a custom stylesheet (and thats just to tweak the tab sizes, I dont actually touch the editor)

Thanks for following up, and please let me know if there is anything else I can do to help you guys out.

**Comment by as-cii** [comment]
Okay, it looks like there is a problem with the `no-caffeine-syntax` theme. We are investigating why it causes this problem, but in the meantime you should be able to switch back to the bundled `one-dark` syntax theme.

Sorry again for this issue, we will post an update here as soon as we find the root cause.

**Comment by august** [comment]
*UI Theme:* One Dark
*Syntax:* Base 16 Darker High Contrast
*Custom Stylesheet:* 
`/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

// style the background and foreground colors on the atom-text-editor-element
// itself
atom-text-editor {

}

// To style other content in the text editor's shadow DOM, use the ::shadow
// expression
atom-text-editor::shadow .cursor {
    border-color: #37F72C;
}

atom-text-editor {
    line-height: 1.6;
}

atom-text-editor .gutter, atom-text-editor::shadow .lines {
  margin-left:1em;
}

.block-cursor {
  background-color: #F00;
  width: 7px !important;
  visibility: visible !important;
}

.vim-mode.command-mode {
  .cursor, .cursor.blink-off {
    .block-cursor;
  }

  &.editor.is-focused {
    .cursor, .cursor.blink-off {
      .block-cursor;
    }
  }
}

.editor.is-focused .cursor.blink-off {
  visibility: visible;
}

.editor { line-height: 1.75 }

/* thicker cursor */
.editor .cursor {
  border-left-width: 2px;
}

.editor.is-focused .line-number.cursor-line-no-selection, .editor.is-focused .line.cursor-line {
    background-color: rgba(53, 57, 60, 0)
}
`
