### ISSUE TITLE
Ignore `package-lock.json`

### ISSUE THREAD

**Issue by liuderchi** [atom/atom#15254]
When building Atom with newer version of npm,
it would generate `package-lock.json` at

  - `apm/package-lock.json`
  - `script/package-lock.json`

Maybe we can add `package-lock.json` to [`.gitignore`](https://github.com/atom/atom/blob/master/.gitignore) to avoid accidentally add it to git index.

**Comment by 50Wliu** [comment]
Package locks are meant to be committed.  However, they're still buggy (rebuilding on Linux and Windows with the package locks present usually result in an ansicolors issue) and we haven't fully decided how we're going to approach them.

**Comment by Xapphire13** [comment]
@50Wliu, Just wondering why this (and the related issues #15155 and #15161) are closed. Seems since it's still an issue, they should still be open no?

Any possibility of changing `script/build` to nuke the offending `package.lock` files?
