### ISSUE TITLE
No elevation of privilege prompt when attempting to edit files owned by root

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#15267]
Prior to v1.19, when attempting to save over a file that is owned by root on macOS, Atom would prompt for elevated permissions. It doesn't any longer and just gives an error.

## Steps to Reproduce

1. Launch Atom with `atom --safe /etc/profile`
1. Type `# testtesttest` and press <kbd>Enter</kbd> on the first line of the file
1. Save the file with <kbd>Cmd+S</kbd>

**Expected:** Dialog comes up asking for privilege elevation
**Actual:** Permission denied notification

### Atom

```
Atom: 1.21.0-dev-b0622d224
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
```

### apm

```
apm  1.18.3
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.0

```

### OS

Mac OS X 10.12.6

## Additional Info

<details>

<summary>Installed Packages</summary>

* about
* advanced-open-file
* archive-view
* atom-2048
* atom-dark-syntax
* atom-dark-ui
* atom-light-syntax
* atom-light-ui
* autocomplete-atom-api
* autocomplete-css
* autocomplete-emojis
* autocomplete-html
* autocomplete-html-entities
* autocomplete-plus
* autocomplete-snippets
* autoflow
* autosave
* background-tips
* badges
* base16-tomorrow-dark-theme
* base16-tomorrow-light-theme
* block-travel
* bookmarks
* bracket-matcher
* chmod
* command-palette
* convert-date
* dalek
* deprecation-cop
* dev-live-reload
* docblockr
* double-tag
* encoding-selector
* exception-reporting
* file-icons
* file-type-icons
* find-and-replace
* fonts
* fuzzy-finder
* git-diff
* github
* github-atom-light-syntax
* go-to-line
* grammar-selector
* hex
* highlight-selected
* image-view
* incompatible-packages
* indentation-indicator
* keybinding-resolver
* language-c
* language-clojure
* language-coffee-script
* language-csharp
* language-css
* language-diff
* language-elixir
* language-generic-config
* language-gfm
* language-git
* language-go
* language-html
* language-hyperlink
* language-java
* language-javascript
* language-json
* language-less
* language-make
* language-mustache
* language-objective-c
* language-pegjs
* language-perl
* language-php
* language-property-list
* language-python
* language-ruby
* language-ruby-on-rails
* language-rust
* language-sass
* language-shellscript
* language-slim
* language-source
* language-sql
* language-text
* language-todo
* language-toml
* language-typescript-grammars-only
* language-xml
* language-yaml
* less-than-slash
* line-ending-selector
* link
* markdown-helper
* markdown-mindmap
* markdown-preview
* metrics
* minimap-plus
* notifications
* one-dark-syntax
* one-dark-ui
* one-light-syntax
* one-light-ui
* open-on-github
* package-generator
* package-sync
* pretty-json
* real-time
* red-wavy-underline
* right-case
* set-syntax
* settings-view
* significant-other
* snippets
* soft-wrap-indicator
* solarized-dark-syntax
* solarized-light-syntax
* sort-lines
* spell-check
* status-bar
* styleguide
* symbols-view
* tabs
* tabs-to-spaces
* timecop
* toggle-quotes
* town-crier
* tree-view
* update-package-dependencies
* welcome
* whitespace
* wrap-guide

</details>

**Comment by lee-dohm** [comment]
Related to #11794

**Comment by andygagnon** [comment]
Same problem here.  Can no longer Save /etc/hosts file on mac osx:
Unable to save file: Permission denied '/etc/hosts'

Whereas before a password prompt appeared.

**Comment by pablocrs** [comment]
+1

**Comment by Hambern** [comment]
+1
