### ISSUE TITLE
Tilting wheel momentary scrolling to horizontal ends

### ISSUE THREAD

**Issue by Ilias48rus** [atom/atom#15272]
**Description**:
Button like triggered |scroll left|right| actions momentary scrolling to ends;

**Steps to reproduce**:
1. open|create file with at least 1 line longer than editor's window;
2. trigger horizontal scrolling by button like controller (tilt wheel for example);

**Additional information**:
if triggering vertical scrolling actions on buttons they working fine;

**Video**
https://gaming.youtube.com/watch?v=PKDeixvHYgQ&feature=share

**Comment by 50Wliu** [comment]
Fixed by #15324.

**Comment by Ilias48rus** [comment]
50Wliu
Sorry, but its not fixed

**Comment by 50Wliu** [comment]
@Ilias48rus Sorry, my mistake.  Can you please open a new issue and completely fill out the [issue template](https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md) so we can respond better?

**Comment by Ilias48rus** [comment]
50Wliu,
Sure, thank you for link, i couldn't find it before (suggestion: should make it bit easier to find)
