### ISSUE TITLE
No formatting after 1000th character in a line

### ISSUE THREAD

**Issue by eolognt** [atom/atom#15274]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In files with very long lines, Atom stops formatting after a specific number of characters. I counted and the number is 1000. This means if I have a line in for example XML-format that is 1008 characters long, the 8 last characters will not be formatted (colored in this case). I toggled between languages and the result is the same, no formatting after the 1000th character.

### Steps to Reproduce

1. Create a file.
2. Add a line with more than 1000 characters

**Expected behavior:** I expected the characters after the 1000th to be formatted as well, allowing me to have long lines in Atom.

**Actual behavior:** After the 1000th characteer, all characters are grey, no color (i.e. not formatted)

**Reproduces how often:** 100%, every time

### Versions

Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

OS: Windows 10 Pro Version 1703

### Additional Information
Here an image of the bug:

![image](https://user-images.githubusercontent.com/10940539/29241175-f8645566-7f74-11e7-9bc2-f6e74f2d6167.png)

**Comment by Swapnull** [comment]
It looks like this is just hitting the maxLineLength in the [GrammarRegistry](https://github.com/atom/atom/blob/62c1bad39c5347010c81ee8baf6b607caaa10cb6/src/grammar-registry.coffee#L18). 
It was added by Github staff on a standalone commit so I imagine there is good reasoning behind it. I imagine probably due to time to open files.

**Comment by avdg** [comment]
Seems to be a duplicate issue of #1667

**Comment by 50Wliu** [comment]
Thanks @avdg, and you are correct @Swapnull.
