### ISSUE TITLE
Block decoration scrolls instead of registering mouse clicks

### ISSUE THREAD

**Issue by lgeiger** [atom/atom#15282]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When interacting with a block decoration near the bottom of the text editor, the decoration scrolls up instead of registering the click event:

![scroll](https://user-images.githubusercontent.com/13285808/29250800-3ed964f8-8049-11e7-8ceb-97c405851c0b.gif)

This issue came up with the [Hydrogen](https://github.com/nteract/hydrogen) package which uses block decorations to display interactive outputs with "clickable" elements. But this is a general problem also present in safe mode.

### Steps to Reproduce

1. Open a file with at least 10 to 20 lines of code
2. Run the following code in the dev tools:
```js
function createBlock(row) {
  const div = document.createElement("div");
  const item = document.createElement("span");
  item.innerText = "[block decoration]\n".repeat(10);
  const button = document.createElement("button");
  button.innerText = "Click me!"
  button.addEventListener('click', () => {
    alert("CLICK!")
  });
  div.appendChild(item);
  div.appendChild(button);
  const editor = atom.workspace.getActiveTextEditor();
  const marker = editor.markBufferPosition([row, 0]);
  editor.decorateMarker(marker, { type: "block", item: div });
}

createBlock(8)
```
3. Scroll the block decoration to the bottom of the text editor and try to click the button.

**Expected behavior:** The button click is registered and a alert box pops up.

**Actual behavior:** The editor scrolls up and the click isn't registered. A second click on the button is necessary to show the pop up.

**Reproduces how often:** 100%

### Versions

macOS 10.12.6:
- Atom 1.20.0-beta0
- Atom 1.19.0

**Comment by 50Wliu** [comment]
@lgeiger do you know if this worked in Atom 1.18.0?

**Comment by lgeiger** [comment]
@50Wliu Sorry, forgot to check.

It works as expected in Atom 1.18.0, the problem appeared in Atom 1.19.0-beta0.
