### ISSUE TITLE
1.19 pixelRectForScreenRange regression

### ISSUE THREAD

**Issue by mupchrch** [atom/atom#15284]
### Description

TextEditorElement's pixelRectForScreenRange is returning incorrect values. 

### Steps to Reproduce

1. Perform a selection that spans 2 or more lines like in the below screenshot:
![image](https://user-images.githubusercontent.com/5797698/29252304-5f648804-8032-11e7-9318-840ce47cc369.png)
2. Run the below code snippet which uses pixelRectForScreenRange:
```
var editor = atom.workspace.getActiveTextEditor();
var screenRange= editor.getSelections()[0].getScreenRange();
atom.views.getView(editor).pixelRectForScreenRange(screenRange);
```

**Expected behavior:** I would expect the left value to be 0 and the width value to be meaningful. In Atom v1.18, they are correct.

**Actual behavior:** In Atom v1.19, left is not 0 and width is a negative number.

### Versions

Works in v1.18 - broken in v1.19. All OS.

**Comment by 50Wliu** [comment]
@mupchrch `pixelRectForScreenRange` appears to be a private method and is not part of the public Atom API.  You may want to use public APIs instead, or create a new issue requesting that `pixelRectForScreenRange` be added to the public API if the existing API methods are insufficient for your use case.
