### ISSUE TITLE
Text keeps selecting on mouse movement

### ISSUE THREAD

**Issue by gokulkulkarni1987** [atom/atom#15295]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Whenever I move the mouse in the editor, the text in the editor keeps on selecting.

**Note:** This issue only reproduces with the `atom-terminal-panel` package.

### Steps to Reproduce

1. Open Atom
1. Install the `atom-terminal-panel` package
1. Add Project Folder and add any folder
1. Open any file from the folder
1. Select some text using the mouse

**Expected behavior:** When the mouse button is release text stops being selected

**Actual behavior:** Mouse button is stuck and text keeps being selected on mouse movement

**Reproduces how often:** 10 out of 10 times.

### Versions
atom --version ==>
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version ==>
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0

uname -a ==>
Darwin Apples-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0:
macOS Sierra Version 10.12.6
![atomscreenselectionissue](https://user-images.githubusercontent.com/6063899/29265874-4c16027c-8100-11e7-942e-946fd142c0ad.gif)

**Comment by rsese** [comment]
Thanks for the report - I'm unable to reproduce with Atom 1.19.0 and macOS 10.12.6.   Did this behavior start right after updating 1.19.0?  Also, it looks like you tried in safe mode already with no difference but can you confirm if temporarily resetting to [factory defaults](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) helps?

**Comment by Ben3eeE** [comment]
There are a lot of reports in https://github.com/atom/atom/issues/11691 recently about the `atom-terminal-panel` package causing this.

@gokulkulkarni1987 
* Do you have the `atom-terminal-panel` package installed?
* Can you try disabling that to see if the issue goes away?

**Comment by gokulkulkarni1987** [comment]
@Ben3eeE u saved me from a hell. Disabling `atom-terminal-panel` is the workaround for this issue.
@rsese 

1. I tried with safe mode. In safe mode I do not face the issue (sorry forgot to mention in the ticket).
2. For your comment of if I got this after updating atom => I had installed OS freshly and when I installed the latest version of Atom I started facing this issue.
3. I do not want to do factory reset as I have setup my developing environment and doing factory reset would make me do all those once again.

Also in the issue #11691 they are talking about some touchscreen tap, I am not getting what is that.

**Comment by Ben3eeE** [comment]
@gokulkulkarni1987 Issue #11691 is another issue that affects users with a touch screen. The effect is the same so it got attention when there was this issue with `atom-terminal-panel`.

It looks like `atom-terminal-panel` did not get any recent updates.

**Comment by Ben3eeE** [comment]
@gokulkulkarni1987 I tweaked the steps to reproduce this issue in the body of the issue.

**Comment by nathansobo** [comment]
Taking a look at this. There may be some changes in our event handling that are interacting badly with the terminal. Hopefully we can get things working without needing to change that package.

**Comment by nathansobo** [comment]
Okay, found a solution via #15347. The fix will go out with Atom 1.19.3 in the next couple days. In the meantime you could downgrade to [1.18.0](https://github.com/atom/atom/releases/tag/v1.18.0). Apologies for breaking your setup.

**Comment by gokulkulkarni1987** [comment]
@nathansobo thanks for the quick support.
