### ISSUE TITLE
Native macOS tabs stopped working in Atom 1.19.0

### ISSUE THREAD

**Issue by ilyasotkov** [atom/atom#15292]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After updating to 1.19.0, native macOS tabs stopped working. Whenever I press Shift-Command-N or ```atom .``` in the command line, it pops up a new window.

### Steps to Reproduce

1. On macOS, update Atom from 1.18.0 to 1.19.0.
2. With atom having at least one window already open, try opening a new window by Shift-Command-N, or typing ```atom .``` in Terminal.

**Expected behavior:** 
New windows appear as native macOS tabs. You can drag a tab out of the window if you want to have two windows side-by-side.

**Actual behavior:** 
A separate windows pops up every time you reopen a project. 

**Reproduces how often:** 
Every time, 100% of the time. The feature does not work any more. Downgrading to 1.18.0 brings the feature back.

### Versions

Atom 1.19.0 and macOS (10.12.6 and, I presume, all versions of macOS since Apple added support for native tabs).

### Additional Information

I have done some digging and was very surprised to find that this feature was not actually intended or supported by Atom maintainers. 

Either way, the feature has always "just worked". I'm way too used to this behavior by now. It's a useful feature and there's no reason to get rid of it.

**Comment by kudorori** [comment]
Try #15202

**Comment by ilyasotkov** [comment]
That fixed it, thanks. 

#15202 does make it seem like the problem only arises when we use CLI, though. In reality, native tabs stopped working regardless of how you try to open a new window, whether by _Shift-Command-N_, or _Reopen Project_, or using the CLI.
