### ISSUE TITLE
Atom 1.19.0 crashes instantly after launching

### ISSUE THREAD

**Issue by trych** [atom/atom#15297]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashes right away after I launch it. I don't even get to see any window.

### Steps to Reproduce

Launch Atom.

**Expected behavior:** [What you expect to happen]

Atom should not crash.

**Actual behavior:** [What actually happens]

Atom crashes.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

I *cannot* get information via `atom --version` as it crashes right away. Atom is the new version 1.19.0, please let me know if you need more info.

apm info:
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.2.1

Mac OS X 10.8.5

### Additional Information
The issue started after updating to 1.19.0, it never occured, when I was still with 1.18.x.

Here's the console log of such a crash:

```
Process:         Atom [8382]
Path:            /Applications/Atom.app/Contents/MacOS/Atom
Identifier:      com.github.atom
Version:         1.19.0 (1.19.0)
Code Type:       X86-64 (Native)
Parent Process:  launchd [201]
User ID:         501

Date/Time:       2017-08-14 12:51:30.122 +0200
OS Version:      Mac OS X 10.8.5 (12F2560)
Report Version:  10

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/GameController.framework/Versions/A/GameController
  Referenced from: /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found

Binary Images:
       0x103ff2000 -        0x103ff2ff7 +com.github.atom (1.19.0 - 1.19.0) <CB63147A-C9DC-308B-8CA1-EE92A5042E8E> /Applications/Atom.app/Contents/MacOS/Atom
       0x103ff7000 -        0x107c7cf73 +com.github.electron.framework (0) <02EEB879-495F-3A71-9D22-B9C1710D7DC4> /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x1082c7000 -        0x1082e1fff +com.github.Squirrel (1.0 - 1) <4C459C36-AFB6-3B8A-8FEC-76C192C17E30> /Applications/Atom.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x10830d000 -        0x108370ff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Applications/Atom.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x1083ee000 -        0x108402fff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /Applications/Atom.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x10841b000 -        0x1092a7fff +libnode.dylib (0) <DAB1C2BB-5D2E-3517-B257-830B9D737750> /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib
       0x10951e000 -        0x109779fef +libffmpeg.dylib (0) <D787CAF4-FE4E-3859-906E-E1E54DE385B6> /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib
       0x109987000 -        0x1099d1ff7  com.apple.audio.midi.CoreMIDI (1.9 - 78) <28B1D3A5-973A-359A-99DC-18BE8C30C6B8> /System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI
    0x7fff63bf2000 -     0x7fff63c2693f  dyld (210.2.3) <A40597AA-5529-3337-8C09-D8A014EB1578> /usr/lib/dyld
    0x7fff897d2000 -     0x7fff89835fff  com.apple.audio.CoreAudio (4.1.2 - 4.1.2) <FEAB83AB-1DE5-3813-BA48-7A7F2374CCF0> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff89a01000 -     0x7fff8a62efff  com.apple.AppKit (6.8 - 1187.40) <F12CF463-6F88-32ED-9EBA-0FA2AD3CF576> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff8a66c000 -     0x7fff8a670fff  com.apple.IOSurface (86.0.5 - 86.0.5) <4841B89D-501E-306D-8891-3651AA9326E6> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff8a72b000 -     0x7fff8a8d9fff  com.apple.QuartzCore (1.8 - 304.5) <5674D50C-D96C-3A2D-95C5-C93311C7FB56> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff8a903000 -     0x7fff8a971fff  com.apple.framework.IOKit (2.0.1 - 755.42.2) <18E64CC5-2671-3C47-B2C6-0EEEDF899461> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff8abae000 -     0x7fff8ae8bfff  com.apple.security (7.0 - 55719.16.12) <C66C10FF-3ED8-3195-82D0-D5B2FB81E831> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff8b23c000 -     0x7fff8b23dff7  libSystem.B.dylib (169.3) <365477AB-D641-389D-B8F4-A1FAE9657EEE> /usr/lib/libSystem.B.dylib
    0x7fff8b693000 -     0x7fff8b693fff  com.apple.quartzframework (1.5 - 1.5) <6403C982-0D45-37EE-A0F0-0EF8BCFEF440> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff8b892000 -     0x7fff8b892ffd  com.apple.audio.units.AudioUnit (1.9.2 - 1.9.2) <6D314680-7409-3BC7-A807-36341411AF9A> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff8b893000 -     0x7fff8b8fbff7  libc++.1.dylib (65.1) <20E31B90-19B9-3C2A-A9EB-474E08F9FE05> /usr/lib/libc++.1.dylib
    0x7fff8bbb7000 -     0x7fff8bd09fff  com.apple.audio.toolbox.AudioToolbox (1.9.2 - 1.9.2) <DC5F3D1B-036A-37DE-BC24-7636DC95EA1C> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff8c0e0000 -     0x7fff8c10aff7  com.apple.CoreVideo (1.8 - 99.4) <E5082966-6D81-3973-A05A-38AA5B85F886> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff8c18d000 -     0x7fff8c377ff7  com.apple.CoreFoundation (6.8 - 744.19) <0F7403CA-2CB8-3D0A-992B-679701DF27CA> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff8c401000 -     0x7fff8c52bfff  com.apple.avfoundation (2.0 - 361.40.1) <82E0EE8C-6026-33AD-8947-B20D2ED7B2E1> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff8c566000 -     0x7fff8c566fff  com.apple.Carbon (154 - 155) <372716D2-6FA1-3611-8501-3DD1D4A6E8C8> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff8dbcb000 -     0x7fff8dc1cff7  com.apple.SystemConfiguration (1.12.2 - 1.12.2) <A4341BBD-A330-3A57-8891-E9C1A286A72D> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff8ebaf000 -     0x7fff8ebe3fff  com.apple.securityinterface (6.0 - 55024.4) <614C9B8E-2056-3A41-9A01-DAF74C97CC43> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff90214000 -     0x7fff9025ffff  com.apple.CoreMedia (1.0 - 926.107) <405690E6-D857-3136-AC3A-5EDC6C3ABF60> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff902b1000 -     0x7fff90610fff  com.apple.Foundation (6.8 - 945.19) <C98E55BA-553B-314B-B056-849FFB20C220> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff9108e000 -     0x7fff910adff7  libresolv.9.dylib (51) <0882DC2D-A892-31FF-AD8C-0BB518C48B23> /usr/lib/libresolv.9.dylib
    0x7fff9149f000 -     0x7fff91610ff7  com.apple.QTKit (7.7.1 - 2599.54) <12F9CD59-5BCC-3847-BA6F-2002DC865DFE> /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
    0x7fff929e6000 -     0x7fff929e6fff  com.apple.ApplicationServices (45 - 45) <A3ABF20B-ED3A-32B5-830E-B37831A45A80> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff937da000 -     0x7fff937e9fff  com.apple.opengl (1.8.10 - 1.8.10) <AD49CF56-B7C1-3598-8610-58532FC41345> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff952f5000 -     0x7fff952f5fff  com.apple.Accelerate (1.8 - Accelerate 1.8) <878A6E7E-CB34-380F-8212-47FBF12C7C96> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
```

**Comment by trych** [comment]
And yes, I reinstalled and reset to factory settings, it still crashes.

**Comment by rsese** [comment]
> I cannot get information via atom --version

Just running that on the command line crashes?  Is there any output on the command line?

Also, can you clarify how you start Atom?  From the command line, spotlight, etc.?  And does Atom crash no matter how you start it?

Lastly, if you start Atom like this is there any output?

```
atom --safe --foreground
```

**Comment by sbgraphic** [comment]
Hello,

Similar issue here, I cannot launch the latest Atom 1.1.19 on OSX 10.8.5.
After many test (trashing prefs,.atom, reinstalling, etc.) I revert back to 1.1.18 and it works fine again. 

Here is just part of the log:

*Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/GameController.framework/Versions/A/GameController
  Referenced from: /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found*

Best,
Eric

**Comment by sbgraphic** [comment]
Here is a screenshot

**Comment by sbgraphic** [comment]
Sorry I'm having issue commenting with my much too old Safari version unsupported on github...

**Comment by sbgraphic** [comment]
I'm trying to disable autoupdate too in 1.1.18, please check this popup too:
![atom_issue-2](https://user-images.githubusercontent.com/5297644/29295342-457bc9e8-8154-11e7-87da-0565cbf4a7bf.png)

**Comment by trych** [comment]
@rsese 

> Just running that on the command line crashes? Is there any output on the command line?

Exactly. No, there is no output. Here's a screenshot along with the same error message that @sbgraphic also posted, only in German this time.

![bildschirmfoto 2017-08-15 um 10 31 31](https://user-images.githubusercontent.com/9803905/29308224-4358c796-81a5-11e7-92ac-21431882061a.png)

> Also, can you clarify how you start Atom? From the command line, spotlight, etc.? And does Atom crash no matter how you start it?

Yes, it crashes no matter, how I start it. I have tried command line, Spotlight, application launcher (Alfred) and double clicking. It all crashes instantly.

> Lastly, if you start Atom like this is there any output?

> atom --safe --foreground

This also crashes Atom right away, but this *does* write an output to the console:

```
dyld: Library not loaded: /System/Library/Frameworks/GameController.framework/Versions/A/GameController
  Referenced from: /Applications/Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found
/usr/local/bin/atom: line 130: 10235 Trace/BPT trap: 5       "$ATOM_PATH/$ATOM_APP_NAME/Contents/MacOS/$ATOM_EXECUTABLE_NAME" --executed-from="$(pwd)" --pid=$$ "$@"
```

Let me know if I can provide any more info.

**Comment by rsese** [comment]
Thanks for the details - it looks like you're both on macOS 10.8.5, I wonder if that's related.  I'll bring it up with the team - you don't happen to have this version available for testing @ungb?

**Comment by trych** [comment]
@rsese @ungb
Is there any update on this / is somebody looking into this? Are there any Mac OS X 10.8.5 specific infos you need from me?

I assume updating to 1.19.2 won't fix this problem, right?

**Comment by lee-dohm** [comment]
Between Atom v1.18 and Atom v1.19, we upgraded to a new version of [Electron](https://electron.atom.io), v1.6.9. This new version of Electron is no longer compatible with OS X v10.8 and requires OS X v10.9 at a minimum. If you want to continue using Atom on OS X v10.8, you will have to downgrade to Atom v1.18 and disable Atom's automatic updates. You can do this by:

1. Launching Atom
1. Opening the Settings View with <kbd>Cmd+,</kbd>
1. Unchecking "Automatically Update"

<img width="737" alt="screen_shot_2017-08-24_at_11_48_27_am" src="https://user-images.githubusercontent.com/1038121/29683280-a23e0e00-88c2-11e7-9eb3-86db8fcc21c0.png">

If you update the version of OS X you're using, you can go back to using the latest version of Atom normally by checking the same box.

**Comment by trych** [comment]
Sigh … nothing much I can do then, I guess.

I think in this case the sentence "For macOS 10.8 or later" on Atom's front page should be replaced by "For macOS 10.9 or later".

Oh well, back to Sublime, I guess. :/

**Comment by lee-dohm** [comment]
> I think in this case the sentence "For macOS 10.8 or later" on Atom's front page should be replaced by "For macOS 10.9 or later".

Thanks for pointing this out. I'll take care of that right now.

**Comment by trych** [comment]
And actually come to think of it, it should not auto-update in the first place to a version that it won't be able to run. (I hate it when that happens. I probably spend days of my life downgrading software that let me upgrade to non-functioning updates.)

Should I file a new issue about that?

**Comment by lee-dohm** [comment]
@trych No, thank you. I'm not sure how we would even do that exactly, especially in a cross-platform way and this is the first time in the three-and-a-half years that Atom has been out that we've changed the minimum version of an OS we support. I'm not sure that we would prioritize detecting and handling this for how rarely it would come up.

I'll check with the Electron team to see if there's something they could do on their end though. It is a good suggestion.
