### ISSUE TITLE
three '-' won't work to make a separation line

### ISSUE THREAD

**Issue by Superkeyv** [atom/atom#15300]
I'm using 
atom 1.18.0 x64 at Arch linux
markdown-preview-plus 2.4.10

I found that when I make a separation line
'>---'           without any  'space' , it doesn't work
but ,if I insert a 'space' between two charactor. it works
for example
'> ---'
'>- --'
'>-- -'

I'm not sure if it a bug, if so, I hope you can fix it in your next version

**Comment by rsese** [comment]
It sounds like you're having an issue with the markdown-preview-plus package, you can open an issue in the package repository https://github.com/atom-community/markdown-preview-plus.
