### ISSUE TITLE
Typo on keybindings section of package settings

### ISSUE THREAD

**Issue by slawo-ch** [atom/atom#15312]
Atom version 1.19.4 x64 mac

Label on configuration section for package keybindgins says `package\'s` instead of `package's`.

For example on the 'Find and Replace' package:
![screen shot 2017-08-15 at 14 22 19](https://user-images.githubusercontent.com/6863403/29315832-93763a72-81c5-11e7-9ee9-f49a613ea45a.png)

**Comment by rsese** [comment]
Thanks for the report!  This sounds super familiar but I couldn't find an existing issue here or on https://github.com/atom/settings-view/.

I had 1.18 installed on another computer and see the same issue but I randomly had 1.14.4 lying around and didn't see the issue there so seems like a regression somewhere down the line.

---

As a side note, it's helpful even for small issues if you could fill out the issue template so we have all the baseline details to investigate :v:

**Comment by rsese** [comment]
Found out this has been fixed on master so will be resolved in a future release (h/t @Ben3eeE) - thanks again for reporting @slawo-ch :zap:
