### ISSUE TITLE
Atom 1.19.1 - atom.open causes Atom to takeover as active foreground app

### ISSUE THREAD

**Issue by dbslone** [atom/atom#15328]
I am the author of an Atom package called [git-tabs](https://atom.io/packages/git-tabs) which closes and reopens tabs based upon the projects current git branch. I am running into an issue with Atom entering the OS X foreground as the active application when changing branches.

It appears that the culprit in my code is the usage of `atom.open` when this is invoked and the Atom application is in the background (not minimized), the tabs are opened then Atom takes over as the active foreground application.

I have tried using the option `newWindow` and setting it to false but Atom still takes over as the active foreground application.

**Comment by rsese** [comment]
Thanks for the report - would you be able to link to the specific code where you think the issue is or share a minimal reproduction so the team can take a look?  Any more details you can share will be helpful.

And though I think this is what you're saying, just to clarify, the behavior was different in 1.18.0 or 1.19.0 and as of 1.19.1 the behavior changed?

**Comment by dbslone** [comment]
@rsese I went from 1.17 (no issue) to 1.19.0(issue) when I upgraded so I'm not sure about 1.18 but I'm happy to test with my enviroment. What is the best way to test with 1.18? Just clone the repo, checkout 1.18 and build from source?

I'm new to developing for Atom so I'm sure where in the source the issue is occurring but my first guess is it might be in application-delegate.coffee:12 which is using `ipcRender` from electron.

To reproduce the behavior:
- Open Atom editor
- Open the developer tools (<CMD>+<OPTION>+I)
- Paste the code below into the console
```
setTimeout(() => {
	console.log('open the tabs')
	atom.open({pathsToOpen: '<path to file>', newWindow: false})
}, 5000)
```
- Switch to another application and wait 5 seconds
- Atom will take over as the foreground application

**Comment by ungb** [comment]
@dbslone Best way to test with 1.18 is to download 1.18.0 from https://github.com/atom/atom/releases/tag/v1.18.0 and install it and test the behavior.

I tested between 1.17.0 and 1.19.2 and didn't see a different in behavior when I ran 
```
setTimeout(() => {
	console.log('open the tabs')
	atom.open({pathsToOpen: '~/readme.md', newWindow: false})
}, 5000)

```

**Comment by dbslone** [comment]
When testing with 1.18 I was able to reproduce the behavior. I'm starting to think this may be something introduced from another atom package I have installed. Going to strip atom down to the basics tonight and add each back individually to see if I can find the issue.

**Comment by dbslone** [comment]
@ungb In my opinion the expected behavior is the application should remain in the background when a tab is added/removed from the workspace. When testing the same use case with Chrome using the following code `setTimeout(() => window.open('http://www.google.com'), 3000)` when the browser opens a new tab it remains in the background.

Below is a list of packages from `apm list`
```
Built-in Atom Packages (91)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.5
├── one-light-ui@1.10.5
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.6
├── archive-view@0.63.3
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.2
├── autocomplete-html@0.8.0
├── autocomplete-plus@2.35.5
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.87.3
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.4
├── exception-reporting@0.41.4
├── find-and-replace@0.208.3
├── fuzzy-finder@1.5.8
├── github@0.3.4-1
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.3
├── link@0.31.3
├── markdown-preview@0.159.12
├── metrics@1.2.6
├── notifications@0.67.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.250.0
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.11
├── styleguide@0.49.6
├── symbols-view@0.116.1
├── tabs@0.106.2
├── timecop@0.36.0
├── tree-view@0.217.2
├── update-package-dependencies@0.12.0
├── welcome@0.36.4
├── whitespace@0.37.2
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.3
├── language-coffee-script@0.48.7
├── language-csharp@0.14.2
├── language-css@0.42.4
├── language-gfm@0.89.1
├── language-git@0.19.1
├── language-go@0.44.1
├── language-html@0.47.3
├── language-hyperlink@0.16.1
├── language-java@0.27.2
├── language-javascript@0.126.1
├── language-json@0.19.1
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.39.0
├── language-property-list@0.9.1
├── language-python@0.45.3
├── language-ruby@0.71.1
├── language-ruby-on-rails@0.25.2
├── language-sass@0.59.0
├── language-shellscript@0.25.1
├── language-source@0.9.0
├── language-sql@0.25.6
├── language-text@0.7.3
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.1
└── language-yaml@0.30.0

Community Packages (15) /Users/davidslone/.atom/packages
├── atom-material-syntax-light@0.4.6
├── autocomplete-modules@1.6.10
├── busy-signal@1.4.3
├── file-icons@2.1.11
├── git-blame@1.2.1
├── git-tabs@0.2.0
├── intentions@1.1.5
├── language-babel@2.71.0
├── linter@2.2.0
├── linter-eslint@8.2.1
├── linter-ui-default@1.6.7
├── material-ui@1.0.10
├── pigments@0.40.2
├── sort-lines@0.14.0
└── sync-settings@0.8.2
```
