### ISSUE TITLE
used "search in Directory" feature，  The search results is abnormal

### ISSUE THREAD

**Issue by Southhill** [atom/atom#15334]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Use the "search in Directory" feature, then open a non-search directory outside of a file, the search results tab will also show the file search after the match, **I do not understand whether this is a feature or a bug**

### Steps to Reproduce

1. search "test" on "/project/test" directory, then auto open search results tab 
2. open "project/git/readme.md" file
3. search results tab has "project/git/readme.md" file match search "test" results. 

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
OS: window10 64bit.
atom: 1.19.0 x64

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/find-and-replace if there's no existing issue already so we have it in the right place?  Also, if you can share more details in the steps to reproduce so we can try it ourselves or if you can share screenshots that show exactly what's happening step by step, that would be super helpful.
