### ISSUE TITLE
Window is blank on Mac

### ISSUE THREAD

**Issue by NeuralyzerGaming** [atom/atom#15342]
Hi,

I got atom and I know very little about programming HTML etc.  I wanted to get into it and I found out about the atom. I downloaded and installed it and it worked for a while. About an hour later, it completely stopped working. For whatever reason, when I open atom, it shows the window and it does not have anything besides the title of the window and all the commands on the top of my screen next to the apple sign. (command bar thing)

Trouble Shooting:
1. I deleted atom. (re- downloaded it from site)
2. restarted computer 
3. turned off Kaspersky Security
4. went through almost every setting on the command bar.
5. went to "library -> application support -> Atom" and deleted that. 
6. re-downloaded it from website
7. deleted anything else that would effect atom
8. restarted a few times
9. re downloaded atom 

No matter what I did, I could not get it to operate like it did when I first downloaded it. I think I may have been some command I did because it was right after I initiated a "command q" or something.(not sure) 

Also, when I hit "create buffer" I see a large text box and I see parts of huge letters. If I  type on my keyboard, I can see that I am typing in the buffer box but the letters are huge.

<img width="791" alt="screen shot 2017-08-16 at 1 56 33 pm" src="https://user-images.githubusercontent.com/31077943/29380267-c6b6de62-828a-11e7-8346-a5c7ffa0685c.png">
<img width="796" alt="screen shot 2017-08-16 at 1 56 51 pm" src="https://user-images.githubusercontent.com/31077943/29380266-c6ad223c-828a-11e7-9c03-f5795e3c44e7.png">

Thanks

**Comment by NeuralyzerGaming** [comment]
Note: I have the latest version of Atom as of 8/16/17. (I believe 1.19.1)

**Comment by NeuralyzerGaming** [comment]
I tried a test "beta atom" and I got a different view:

<img width="1015" alt="screen shot 2017-08-16 at 2 07 09 pm" src="https://user-images.githubusercontent.com/31077943/29380759-770dfcf4-828c-11e7-9b79-ca9796e52f89.png">
<img width="1000" alt="screen shot 2017-08-16 at 2 07 17 pm" src="https://user-images.githubusercontent.com/31077943/29380760-77126122-828c-11e7-9f1d-48ff01bc4fab.png">

**Comment by NeuralyzerGaming** [comment]
Note: if I use the command w (to close tabs), I can see the auto prompted tabs flash by on the screen, like "welcome" and "welcome guide".

**Comment by NeuralyzerGaming** [comment]
Note: Atom 1.19.0 does not work either.

**Comment by rsese** [comment]
Can you try temporarily resetting to factory defaults and see if that helps?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by NeuralyzerGaming** [comment]
Thanks!

Worked!

Side note:
Does Atom have a live updater like Brackets does. When I could not use Atom I found Brackets and I liked that feature. Does Atom have anything similar?

Thanks!

**Comment by Ben3eeE** [comment]
Closing this since it seems that resetting to factory defaults worked.

---

For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by rsese** [comment]
Great glad that helped :v:

> Does Atom have a live updater like Brackets does. When I could not use Atom I found Brackets and I liked that feature. Does Atom have anything similar?

If you mean previewing a web page, then you would need to install a package for that functionality, see this FAQ post for more details:

https://discuss.atom.io/t/how-do-i-preview-web-page-changes-automatically/22013

If you have more general questions, feel free to post in the official message board:

https://discuss.atom.io/

**Comment by rsese** [comment]
woops, looks like the issue didn't live update for me, missed your comment @Ben3eeE :bow:
