### ISSUE TITLE
1.19.2 - Avast detected atom\Update.exe as a false positive

### ISSUE THREAD

**Issue by TotomInc** [atom/atom#15349]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [ ] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After upgrading Atom to 1.19.2 and linter-ui-default to 1.6.7, I opened Atom and Avast flagged atom\Update.exe as an IDP.ARES.Generic malware.

### Steps to Reproduce

1. Updated Atom to 1.19.2, linter-ui-default to 1.6.7
2. Opened Atom
3. Avast poped-up with a false positive.

**Expected behavior:** expected to don't have Avast tell me Atom is a malware.

**Actual behavior:** according to Avast, Atom is a malware.

**Reproduces how often:** 100% since I actually done it 1 time.

### Versions

Atom : 1.19.2
Electron : 1.6.9
Chrome : 56.0.2924.87
Node : 7.4.0

apm : 1.18.4
npm : 3.10.10
node : 6.9.5 x64
python : 3.6.1
git : 2.13.3.windows.1
visual studio

Running Windows 10, build 1703 with Avast (version 17.5.2303 build 17.5.3585.203)

### Additional Information

I suspect the package linter-ui-default to cause the false positive.

**Comment by 50Wliu** [comment]
The best thing you can do is to report the incident as a false positive to Avast so that they can improve their virus detection models.  The auto-updater Atom uses is open source and available at https://github.com/Squirrel/Squirrel.Windows if you want to double check.
