### ISSUE TITLE
Composition characters mess up insertion point

### ISSUE THREAD

**Issue by oggy** [atom/atom#15344]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm trying out edge (586b818b) since #15314 was merged. I have a command bound to alt-n (a composing diacritic in the macOS US keyboard layout) that moves the cursor. Under Atom 0.19 the keystroke would run the command and insert the diacritic. On this edge version, it only runs the command, which is awesome. 🎉 

BUT, it seems like some internal buffer state then gets messed up. If after the alt-n I move the cursor with the arrows, and then insert a character, the cursor seems to jump back to where the alt-n left me, and the character gets inserted there. If I use a command that isn't a composition character, like `alt-o`, then the problem does not occur.

#### Keymap

```
'atom-text-editor':
  'alt-n': 'core:move-down'
  'alt-o': 'core:move-down'
```

1. Add the keymap above to your ~/.atom/keymap.cson
2. Have two lines of text in your buffer:
```
Foo
Bar
```

3. Have the cursor at the beginning of file(before `F` character) Type `alt-n`, then arrow right, then insert a character. Observe that the character is inserted at the beginning of the line (where the `alt-n` left you).
4. Repeat 2-3 using `alt-o` instead of `alt-n`. Observe the insertion happens where the cursor is, as expected.

**Expected behavior:** Character insertion following `alt-n` inserts the character where the cursor is.

**Actual behavior:** Character insertion following `alt-n` inserts the character at the wrong place (seems to be where the `alt-n` leaves you).

**Reproduces how often:** Always.

### Versions

Atom    : 1.21.0-dev-586b818ba
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: macOS Sierra 10.12.6

**Comment by ungb** [comment]
I was able to repro this issue with the following repro steps.
screenshot of issue:

![bug](https://user-images.githubusercontent.com/5624870/29386722-ebe4c2f6-8291-11e7-88e7-12cc89376cc7.gif)
