### ISSUE TITLE
onDidChangeScrollTop fired when no scrollTop change / can cause infinite loop

### ISSUE THREAD

**Issue by t9md** [atom/atom#15343]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`editor.onDidChangeScrollTop` can be fired with same scrollTop value.
And to make matters worse, it can cause infinite loop when registered callback call `component.getScrollTop` and `component.setScrollTop` indirectly.

Why this happen is here

- `editor.component.getScrollTop` update `component.scrollTop` value without **Math.round**
- guard(so that not fire event with same scrollTop) done in `component.setScrollTop` is compared with **rounded** value.

In my package, atom-narrow hit infinite loop because of this behavior(bug IMO).

What was [happened](https://github.com/t9md/atom-narrow/issues/239) is here.

0. In `editor.setScrollTop`
  scrollTop updated from xxx to `522`.
1. `editor.onDidChangeScrollTop` fired with (scrollTop = `522`)
2. In onDidChangeScrollTop callback, call `markerLayer.clear()` which markerLayer is used for text decoration.
3. `editor.onDidChangeScrollTop` fired again(goto step 1, this is infinite loop)
  - In some place, `editor.component.getScrollTop` is accessed which update `component.scrollTop` to `521.65625`)
  `this.scrollTop = Math.min(this.getMaxScrollTop(), this.scrollTop)` = Math.min(521.65625, 522)
  - During etch's rendering, `component.setScrollTop` is called with `548.65625`.
    - result of `scrollTop = Math.round(Math.max(0, Math.min(this.getMaxScrollTop(), scrollTop)))`
    - result of `scrollTop = Math.round(Math.max(0, Math.min(521.65625, 548.65625)))`
    - result of `scrollTop = Math.round(Math.max(0, 521.65625))`
    - result of `scrollTop = 522`
    - scrollTop = `522`
  - `did-change-scroll-top` fired with `522` (`522(rounded) !== 521.65625(<- this.scrollTop updated via getScrollTop)`)

### Steps to Reproduce

1. Make sure `editor.scrollPastEnd` is `false` (default).
When `editor.scrollPastEnd` is `true` this issue doesn't happen.

2. Prepare `style.less` bellow. paste&call `reproduceIssue()` on chrome-dev-console.

- style.less

```less
@import "octicon-mixins";
.scrolltop-issue-container {
  padding: @component-padding/3 @component-padding;
}

atom-text-editor {
  .scrolltop-issue-text-hl {
    color: @syntax-color-function;
  }
}
```

```javascript
function reproduceIssue() {
  atom.workspace.open().then(editor => {
    // Render 40 lines of text to make editor scrollable.
    const lines = []
    for (let i = 1; i < 40; i++) {
      lines.push(i)
    }
    editor.setText(lines.join("\n"))

    editor.setCursorBufferPosition([0, 0])

    // To make editor.component.maxScrollTop() have fractional portion(decimal point).
    const item = document.createElement("div")
    item.className = "scrolltop-issue-container"
    item.innerText = "[block decoration]"
    editor.decorateMarker(editor.markBufferPosition([0, 0]), {type: "block", item})

    // prepare decoration layer for text highlight
    const markerLayer = editor.addMarkerLayer()
    editor.decorateMarkerLayer(markerLayer, {type: "text", class: "scrolltop-issue-text-hl"})

    let oldScrollTop
    editor.onDidChangeScrollTop(newScrollTop => {
      console.log("fired")

      // This guard is necessary to prevent infinite loop.
      // if (oldScrollTop === newScrollTop) {
      //   return
      // }

      // Refresh highlight
      markerLayer.clear()
      editor.scan(/1|3|5|7|9/g, ({range}) => markerLayer.markBufferRange(range))

      oldScrollTop = newScrollTop
    })
  })
}
reproduceIssue()
```

3. Move cursor down by `core:move-down`
When last row was appeared, editor freeze by infinite loop on `onDidChangeScrollTop` event. Need to force close.

**Expected behavior:** [What you expect to happen]

`editor.onDidChangeScrollTop` should not be fired when not changed.

**Actual behavior:** [What actually happens]

`editor.onDidChangeScrollTop` is emitted with same scrollTop value which possibly cause infinite loop(depends on registered callback).

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

OS
```
ProductName:	Mac OS X
ProductVersion:	10.12.5
```

Atom(All stable/beta/master affects).

- Stable
```
Atom    : 1.19.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

- Beta
```
atom-beta  --version
Atom    : 1.20.0-beta2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

And master branch

### Additional Information

Original issue I hit this issue.
https://github.com/t9md/atom-narrow/issues/239

This guard 

https://github.com/atom/atom/blob/15e3fbaa07f90174ab84d35a4281956b54128d12/src/text-editor-component.js#L2713

should be `scrollTop !== Math.round(this.scrollTop)`.

Since calling `getScrollTop` update `this.scrollTop` with non rounded value.

https://github.com/atom/atom/blob/15e3fbaa07f90174ab84d35a4281956b54128d12/src/text-editor-component.js#L2707

**Comment by nathansobo** [comment]
@t9md Do you thinking just rounding in `getMaxScrollTop` would work too?

**Comment by t9md** [comment]
Yes.

**Comment by t9md** [comment]
While investigated, I coudn't understand why assinging scrollTop in `getMaxScrollTop` was necessary.
Things are simple if `this.scrollTop` was mutated only via `setScrollTop`

**Comment by nathansobo** [comment]
It's because the editor can get shorter and the max allowed scroll top changes when that happens. The easiest way to enforce that was on reading the value.
