### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by phamdung103** [atom/atom#15354]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'addEventListener' of undefined

```
At C:\Users\phamd\.atom\init.coffee:40

TypeError: Cannot read property 'addEventListener' of undefined
    at middleMouseScrollSetup (~/.atom/init.coffee:40:19)
    at init (~/.atom/init.coffee:61:7)
    at ~/.atom/init.coffee:64:3
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.2/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.19.2/resources/app/src/workspace.js:551:30
```

### Commands

```
     -1:00.1.0 platformio-ide-terminal:toggle (button.btn.icon.enablement.icon-playback-pause)
     -0:17.6.0 platformio-ide-terminal:new (input.hidden-input)
     -0:12.4.0 platformio-ide-terminal:close-all (input.hidden-input)
     -0:07.7.0 platformio-ide-terminal:new (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-minify 0.8.0 
autoclose 0.0.2 
gloom 0.6.4 
language-javascript-jsx 0.3.7 
minimap 4.29.3 
platformio-ide-terminal 2.5.5 
react 0.16.2 
```

**Comment by Ben3eeE** [comment]
The stack trace includes `init.coffee` so it looks like there is a bug in your `init.coffee` script.

**Comment by phamdung103** [comment]
@Ben3eeE I'm using script in (https://gist.github.com/ncreep/a87f127abd962d3cec56) => ok in ver 1.19.1.
but not working in atom v1.19.2

**Comment by nathansobo** [comment]
This is all acessing private APIs and it broke after a rewrite of `TextEditorComponent`. Other things might break, but you should replace `{scrollViewNode} = editorComponent` with `{scrollContainer} = editorComponent.refs`.
