### ISSUE TITLE
Atom crash when moving the unstaged changes tab 

### ISSUE THREAD

**Issue by TobiasAl** [atom/atom#15360]
# ##Description
Atom crashes when moving the unstaged changes tab 
###Steps to Reproduce
1.open Atom
2.open git tab
3.view unstaged changes
4.move unstaged changes tab
5.Atom crash

**Expected behavior:** unstaged changes tab will move

**Actual behavior:** Atom crash

**Reproduces how often:** Always

# ##Version
**Atom**    : 1.19.2 x64
**Electron** : 1.6.9
**Chrome**  : 56.0.2924.87
**Node**    : 7.4.0

**apm**  1.18.4
**npm**  3.10.10
**node** 6.9.5 x64
**python** 2.7.13
**git** 2.11.0

**OS** : Ubuntu 17.04

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/github/ if there's no existing issue already so we have it in the right place?  If you can also let us know if you've gone through the Prerequisites (e.g. have you tried in safe mode, etc.), that would be great too.
