### ISSUE TITLE
FR: Restart Button

### ISSUE THREAD

**Issue by TJProgrammer** [atom/atom#15366]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages (https://atom.io/packages/restart-atom)

### Description

This issue is a feature request.
Add a new button in file menu called "restart".
What do you think?

### Steps to Reproduce

1. Packages are updated.
2. An info appears asking the restart.
3. Close the info.
4. I haven't got any restart button.

**Expected behavior:** A restart button.

**Actual behavior:** No restart button.

**Reproduces how often:** Always.

### Versions

Atom: 1.19.2 windows10 64bits

**Comment by 50Wliu** [comment]
View -> Developer -> Reload Window

**Comment by TJProgrammer** [comment]
Ok, thanks, but why this option is so difficult to find?....
