### ISSUE TITLE
Add windows-build-tools to windows build instructions

### ISSUE THREAD

**Issue by ericcornelissen** [atom/atom#15368]
### Description

I would like to suggest adding [this package](https://www.npmjs.com/package/windows-build-tools) as an option for Visual C++ build tools to the build documentation for Windows (`docs/build-instructions/windows.md`). It makes building Atom from scratch a lot easier for people without prior knowledge of Visual C++ build tools, as it just installs it and updates your environment variables automatically. 

I drafted my idea of how to insert it into the `windows.md` file, but this is obviously open for discussion. The reason I put it in first is because I expect newcomers to just go ahead and try the first thing in the list, making the building process easier for them.

Also, maybe change the _"Visual Studio, either:"_ bullet to _"C++ build tools, either:"_ or something similar?

```markdown
...

* Visual Studio, either:
  * [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) (Also installs Python 2.7)
  * [Visual C++ Build Tools 2015](http://landinghub.visualstudio.com/visual-cpp-build-tools)
  * [Visual Studio 2013 Update 5](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs) (Express Edition or better)
  * [Visual Studio 2015](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs) (Community Edition or better)

...
```

#### Which would result in:
...
* Visual Studio, either:
  * [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) (Also installs Python 2.7)
  * [Visual C++ Build Tools 2015](http://landinghub.visualstudio.com/visual-cpp-build-tools)
  * [Visual Studio 2013 Update 5](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs) (Express Edition or better)
  * [Visual Studio 2015](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs) (Community Edition or better)

...

* * *

I want to make clear that I did not find out about this myself, I found it given as a solution in some other issue but unfortunately I'm not able to find that particular issue 😞

**Comment by lee-dohm** [comment]
See discussion on atom/flight-manual.atom.io#420.

Since this will be resolved either by accepting and merging that PR or denying and closing that PR, I'll go ahead and close this. Thanks for the input!
