### ISSUE TITLE
Can't uninstall nor reinstall crashed version of atom

### ISSUE THREAD

**Issue by Stekmo** [atom/atom#15364]
I was working on a project earlier today, when Avast Antivirus popped up with a message about potential harmful files. I didn't pay too much attention to the path, but it had atom in it for sure, which is why I clicked ignore. Avast kept popping up with the same message four times, and I accidently clicked "fix it" the fifth time it popped up. Anyways, it didn't seem like an issue, my atom was still running and I could continue my project. 
Now after I've closed atom, I can't find it on my computer anymore, its just not there. I  went "Add and Remove programs" on windows 10, to try to remove atom completely, so I could reinstall it again. But when I click uninstall, it gives me this error: 

"Windows cannot find 'C:\Users\steph\AppData\Local\atom\Update.exe". Make sure you typed the name correctly, and then try again.

I then tried to download the atom setup.exe, to try to install it, and it says:

"Installation has failed. There was an error while installing the application. Check the setup log for more information and contact the author."

The setup log: 
[SquirrelSetup.txt](https://github.com/atom/atom/files/1231131/SquirrelSetup.txt)

I've tried running the windows 10 Disk Cleanup and reinstalling atom again, with no luck.

**Comment by benjamenhogben** [comment]
Had the same(ish) thing happen to me and a colleague earlier. 

Temporarily disable avast components then run setup.exe again

**Comment by Stekmo** [comment]
@benjamenhogben that worked, thanks.
