### ISSUE TITLE
Request: Maintain Assigned Syntax of Unsaved Buffers

### ISSUE THREAD

**Issue by Ultrabenosaurus** [atom/atom#15376]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Syntax assigned to unsaved buffers is not preserved when restarting Atom.

I do a lot of work that involves editing HTML fragments, often from locations that either aren't directly editable or have no syntax highlighting. I will usually copy this into Atom, make the necessary changes, and paste it back. This provides a lot more than just syntax highlighting, such as auto-complete and auto-indent. However, if I restart Atom or my PC, the assigned syntax is lost and I have to re-assign it every time, on all buffers - there's no point in saving the copied HTML to actual files, as I'd have to regularly clean these files from my computer.

### Steps to Reproduce

1. Open Atom and add a project root
2. Open a new tab and add some content in a defined language, e.g. HTML or Python
3. Assign the correct syntax to the buffer
3. Do not save the content to a file
4. Restart Atom

**Expected behavior:** Atom re-opens with everything - content, settings, etc - preserved

**Actual behavior:** Atom re-opens with syntax set to plain text on unsaved buffers

**Reproduces how often:** 100% of the time, every time

### Versions

1.17.2 when I first started using Atom, currently on 1.19.2 ia32 and this behaviour has always been consistent. OS is 64-bit Windows 10 Pro 15063.483 running on an i5-6400 with 8GB RAM.

**Comment by sleepdeprivation** [comment]
I can't seem to reproduce this on Ubuntu Linux

Atom 1.20.0-dev-137ccf4e0

What I did:

* open atom, project root already saved
* press ctrl-n, new tab appears
* enter some html
* edit > select grammar > html, syntax highlighting appears
* close atom
* open atom, tab is still open, syntax still highlighted
