### ISSUE TITLE
[linux] Focus of atom editor over opened apps

### ISSUE THREAD

**Issue by neok-m4700** [atom/atom#15388]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On linux (Ubuntu 17.04) and atom (1.19.2), atom vampirizes the focus: I cannot cycle through open apps anymore (Alt+Tab), nor gain focus over an open app.

I must minimize atom with a system shortcut (Alt+F9) or right click on the taskbar + minimize, in order to switch applications.
When clicking an open item on my taskbar, atom stays as the active app (foreground).

This issue didn't appear in 1.18.x

### Steps to Reproduce

1. Open atom
2. Open a terminal (e.g. Ctrl+Alt+T, system shortcut), or Alt+Tab to select an opened app

**Expected behavior:** Terminal (or whatever app) gains focus (foreground) over atom

**Actual behavior:** Terminal (or whatever app) stays in background, cannot gain focus with the mouse/keyboard

**Reproduces how often:** 100%

### Versions
```bash
$ atom --version
Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0

$ lsb_release -a
LSB Version:	core-9.20160110ubuntu5-amd64:core-9.20160110ubuntu5-noarch:security-9.20160110ubuntu5-amd64:security-9.20160110ubuntu5-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

$ uname -a
Linux m4700 4.10.0-32-generic #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rsese** [comment]
I just gave this a try with 1.19.2 and Ubuntu 16.04 but wasn't able to reproduce - I'll tag as needs repro in case someone else can give it a try.  I can also try to install 17.04 and see if that makes a difference.
