### ISSUE TITLE
Pushing to GitHub extremely slow

### ISSUE THREAD

**Issue by LightningStalker** [atom/atom#15387]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Extreme slowness when pushing to github from Atom using the GitHub functionality

### Steps to Reproduce

1. [Open Atom]
2. [Open a git project folder]
3. [Make some changes]
4. [Stage, commit, and try pushing from within Atom]

**Expected behavior:** [Pushing with `git push` from the terminal takes less than 5 seconds]

**Actual behavior:** [Pushing in Atom takes several minutes]

**Reproduces how often:** [100% of the time]

### Versions

$ atom --version
Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
OS Linux Mint 18.2

### Additional Information

It is noted that pushing eventually does occur, however nowhere near as quickly as it does from a terminal.

**Comment by konstantingoretzki** [comment]
I have the same problem with an older version of Atom.
$ atom --version
Atom    : 1.18.0
Electron: 1.4.16
Chrome  : 53.0.2785.143
Node    : 6.5.0

$ apm --version
apm  1.18.3
npm  5.3.0
node 8.4.0 x64
python 2.7.13
git 2.14.1

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/github](https://github.com/atom/github) repository.  Thanks!

**Comment by LightningStalker** [comment]
Sorry wasn't aware of other repo
