### ISSUE TITLE
Tilting wheel momentary scrolling to horizontal ends

### ISSUE THREAD

**Issue by Ilias48rus** [atom/atom#15385]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Button like triggered |scroll left|right| actions momentary scrolling to ends;

### Steps to Reproduce

1. open|create file with at least 1 line longer than editor's window;
2. trigger horizontal scrolling by button like controller (tilt wheel for example);

**Expected behavior:** Smooth scrolling.

**Actual behavior:** Momentary scrolling to end.

**Reproduces how often:** !<100%

### Versions

1.19.2, but i'm sure what all

### Additional Information

if triggering vertical scrolling actions on buttons they working fine;
From all internet browsers i checked only Mozilla Firefox have it ~adequately, they made it scrolling on displayed page width (what is still bit problematic because there delay between scrollings ~0.04s (need to release button verrry fast to get scrolled only once))

Video
https://gaming.youtube.com/watch?v=PKDeixvHYgQ&feature=share

**Comment by Ben3eeE** [comment]
Does scrolling work in google chrome with this setup?

**Comment by Ilias48rus** [comment]
~130 characters in notepad,
displayed page width in firefox,
pretty mutch far away in google
and bit lower in IE11
