### ISSUE TITLE
Closing atom 1.19 produces many instances node.exe on Windows 8.1 x64

### ISSUE THREAD

**Issue by VadimDor** [atom/atom#15382]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Closing atom 1.19 on Windows 8.1 x64 produces many instances node.exe running and consuming all CPU. 
In atom --safe mode all is OK.
![node-exe](https://user-images.githubusercontent.com/29509093/29478274-be199a6a-8474-11e7-81fa-592015083852.jpg)

### Steps to Reproduce

1. Start atom
2. Close atom
 
**Expected behavior:**  closes in accepted time

**Actual behavior:** it takes 30 secs to  close

**Reproduces how often:** always since 1.19 version update

### Versions
Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
 
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python
git
visual studio 2015

### Additional Information
Packages list attached
[packages.txt](https://github.com/atom/atom/files/1235702/packages.txt)

**Comment by rsese** [comment]
Thanks for the report!

> In atom --safe mode all is OK.

If this is the case, then it's likely that the issue is caused by a community package. I don't have any guesses based on your package list but if you disable all your community packages and then re-enable them 1 at a time, that should help pinpoint which package is causing the error.
