### ISSUE TITLE
High memory consumption when opening a file

### ISSUE THREAD

**Issue by vdjkelly** [atom/atom#15399]
When I open a file the memory consumes up to a gb of memory
![captura de pantalla de 2017-08-21 06-57-52](https://user-images.githubusercontent.com/5873347/29516547-c341bfec-863e-11e7-819d-892416cf13eb.png)

**Comment by 50Wliu** [comment]
Please make sure you do not have a `~/.git` folder, and if you do, it should be safe to rename it to `~/.git-backup`.  If that does not fix the issue, please comment here and I'll reopen this issue.
