### ISSUE TITLE
Syntaxhighlighting broken for "Shell Script" highlight mode in HERE documents

### ISSUE THREAD

**Issue by rovf** [atom/atom#15397]
When using the highlight mode "Shell Script", HERE-documents are not recognized. 

For example, I have in my program code like this:

  cat << EOS
....
EOS

The code between the cat line and the closing EOS is highlighted as if it would be normal program code. This is in particular nasty, if this text contains a single (unpaired) quote, because the highlighter would then search for a matching quote in the code after the closing EOS, and the whole syntax highlightning is garbled.

I can provide a screenshot by email, if needed. I tried to upload a screenshot using this web interface, but it did not work.

I'm using Atom 1.16.0 x64 on Windows 7

**Comment by 50Wliu** [comment]
Please reopen this on the [language-shellscript](https://github.com/atom/language-shellscript) repository.  Thanks!
