### ISSUE TITLE
Improve handling of "Editor has crashed"

### ISSUE THREAD

**Issue by adderek** [atom/atom#15400]
### Prerequisites
* NOT able to reproduce in safe mode
* All the diagnosis steps are too complex for a programmer not mentioning a normal user - I have not followed that at all.... you should automate it in some way

### Description

Atom editor is crashing on Windows 10 x64 with windows dialogue "Editor has crashed".
Search your issues - there are many similar.
**Please, improve auto-diagnostic.**
Example similar issue #10717
I'm writing this one just to keep the information somewhere - you can close it immediatelly

### Steps to Reproduce

1. Use atom editor (with plugins)
2. At some point encounter the "editor has crashed" issue with no further details, no windows event log entries, no guidance on how to diagnose the issue
3. Run in safe mode and see that it disables plugins but works.... but still have no idea what might be wrong or what to do next
4. One-by-one move directories from ~/.atom/packages (and then move them back) - at some point it will stop crashing (in my case this was git-gui causing the issue)

**Expected behavior:**
Handle crash scenarios. Provide feedback for the user. Provide instructions for error handling.

**Actual behavior:**
Dummy message saying "report the issue on github" appears.

**Reproduces how often:**
100% reproducibility after atom is started

### Versions
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python
git 2.13.0.windows.1
visual studio

**Comment by lee-dohm** [comment]
Closed per request.

**Comment by lee-dohm** [comment]
Duplicate of https://github.com/atom/atom/issues/2357
