### ISSUE TITLE
Find and Replace not working when there's a samba mount

### ISSUE THREAD

**Issue by bencolder** [atom/atom#15409]
If I do a directory search that has samba mount, the search will fail and stop after indexing to the mount folder. The mount folder has large video files. Even if I have added the mount path to the .gitignore file with exclude VCS ignored paths option checked it still produces the same result. If I have unmounted that folder everything will work just fine.
Atom version 1.19.2 on OSX

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/find-and-replace if there's no existing issue already so we have it in the right place?  If you could also fill out the issue template, that would be super helpful as well.
