### ISSUE TITLE
1.19.3 installtion on openSUSE: Signature verification failed [6-File is unsigned]

### ISSUE THREAD

**Issue by olegantonyan** [atom/atom#15418]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

openSUSE Tumbleweed 64 bit
1.19.3 64 bit rpm (https://github.com/atom/atom/releases/download/v1.19.3/atom.x86_64.rpm) install error: Signature verification failed [6-File is unsigned]
Only when installing with `zypper`. `rpm -i` succeeded without errors.

### Steps to Reproduce

1. Download https://github.com/atom/atom/releases/download/v1.19.3/atom.x86_64.rpm
2. Try to install it on openSUSE with zypper `zypper in atom.x86_64.rpm`

**Expected behavior:** successful installation 

**Actual behavior:** 
```Retrieving package atom-1.19.3-0.1.x86_64                          (1/1), 127.5 MiB (405.8 MiB unpacked)
atom.x86_64.rpm:
    Package is not signed!

atom-1.19.3-0.1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
```

**Reproduces how often:** always

### Versions

openSUSE Tumbleweed latest updates (23.08.2017)
RPM version 4.13.0.1
zypper 1.13.31

**Comment by Ben3eeE** [comment]
@olegantonyan Do other releases of Atom install correctly?

/cc: @ungb Since you have been dealing with install errors on Linux before. Do you know anything about this?

**Comment by olegantonyan** [comment]
All prior 1.19.3 releases were ok

**Comment by ungb** [comment]
@olegantonyan, We've updated the README in https://github.com/atom/atom/pull/15380.  I believe that the best way to install atom is as you suggested:  `sudo rpm -i` and the README are now updated with those steps.

I'm going to close this issue, as I believe this issue is actually from the OS and Zypper maybe having a more strict policy on packages being signed.

**Comment by olegantonyan** [comment]
@ungb well, if you say so... 
It doesn't look like a good idea to me (almost as disabling SSL cert verification when you have problems with certificates)

**Comment by wismill** [comment]
@olegantonyan +1 following the spec is more secure and future-proof.

**Comment by ungb** [comment]
@olegantonyan Thanks for the feedback!

I've created issue https://github.com/atom/atom/issues/15509 to add signing for linux package and added it to the backlog.  Currently we’ve never signed our linux packages. The fact that you're seeing the warning now is a change in the OS
