### ISSUE TITLE
Scroll stops working when cursor image disappears using Unclutter

### ISSUE THREAD

**Issue by Cydfrey** [atom/atom#15419]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm using Unclutter to make my cursor disappear after a few seconds of inactivity. When in Atom, and given that Atom has the focus, the mouse scrolling will cease to work as soon as the cursor image has disappeared. This is reproduced everytime, but that's specific to Atom, other sowftware like Gedit, Firefox or Eclipse still have the scroll working.

### Steps to Reproduce

1. Install and run Unclutter
2. Open Atom
3. Give the focus to the editor, scroll a bit to check everything works
4. Wait for the cursor to disappear
5. Scroll without moving the cursor -> nothing happens
6. Move the cursor and scroll again -> it works

**Reproduces how often:** always

### Versions

OS: Ubuntu 17.04
Window Manager : awesome v4.0 (hopefully not relevant)
Unclutter version: standard package version
Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by nineway** [comment]
![gittry](https://user-images.githubusercontent.com/17272264/30277171-45c9f1ae-9707-11e7-8671-b068d6e0b1e6.gif)
I'm not able to reproduce the fault that's described with the same versions listed (awesome included).

I would suggest that you reinstall the programs, if you haven't tried that already.

**Comment by Cydfrey** [comment]
Hi,

Ok, that's very weird. Thank you for taking the time to try and reproduce it.
I won't have the time to look at it this week but I'll try to do what you suggest (and other things, too). i'll give you my findings.

**Comment by Cydfrey** [comment]
New findings:

* It does not work with Unity window manager (default wm for my Ubuntu version)
* It does not work after purging everything (dpkg -P, removed ~/.atom and ~/config/Atom)
* It **does work** when running unclutter with the -noevents option:
>       -noevents
>              stops unclutter sending a pseudo EnterNotify event to the X client whose cursor has been stolen.  Sending the event helps programs like emacs think that  they  have  not  lost  the  pointer focus.  This option is provided for backwards compatibility in case some clients get upset.

Used atom 1.20.0 for these new tests.

So there's still something with this unclutter/atom combination, but I don't know what's the configuration difference that prevents you from reproducing it.

**Comment by nineway** [comment]
Strange, now that  you've purged  both Atom and config we should have a similar setup. I don't have much else to go on as it seem to depend on something I don't know and therefore I will not be able to help you with your focus problem.
