### ISSUE TITLE
tree-view renders blurry text

### ISSUE THREAD

**Issue by pbarbiero** [atom/atom#15423]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In atom 1.19.3 (and first noticed in 1.19.2), while almost all blurriness has been fixed in .3, tree-view still renders blurry.

Blurry 
![blurry](https://user-images.githubusercontent.com/20247733/29620843-b7c1f978-87e4-11e7-81f1-67015c5c4618.png)
Not Blurry
![not-blurry](https://user-images.githubusercontent.com/20247733/29620842-b7c1226e-87e4-11e7-9dcb-bf71ccb5e828.png)

I tried disabling all my extensions/themes but no affect. However, `busy-signal` while its running (animating the little icon in the status bar) makes the text NOT blurry (which is how I captured the second screenshot above) but only while it is animating. The package is NOT the source of the issue.

And to be clear, ONLY tree-view seems to be outstanding after the fixes in 1.19.3.
I cant confirm what version this occurred in, I can only confirm 1.19.2 and 1.19.3 exhibit this.

### Steps to Reproduce

Atom on windows with per-monitor-dpi scaling enabled (occurs on monitors both with and without a dpi scale applied)

My exact system setup:
Laptop with three monitors:
- internal 1080p monitor set to 125% dpi scale
- 2x external 1080p monitors set to 100% dpi scale

### Versions

1.19.3
Windows 10 x64 latest

**Comment by Ben3eeE** [comment]
Thank you for reaching out! This issue belongs on the [tree-view](https://github.com/atom/tree-view) repository. Can you please open this issue there if one is not already open :bowing_man:

**Comment by pbarbiero** [comment]
@Ben3eeE sure but I opened it here because its quite obviously not a bug in tree-view but atom core. Possibly related to https://github.com/atom/atom/pull/15372
