### ISSUE TITLE
Unable to install some packages

### ISSUE THREAD

**Issue by cristiano-c** [atom/atom#15422]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Unable to install **some** packages, such as `latex` and `hihglight-selected`, others such as `atom-clock` are still working. I tried in safe mode, removing the `.atom` directory and via Terminal.

### Steps to Reproduce

1. open Terminal: `$ apm install highlight-selected`
2. press `Enter` and I get: `Installing highlight-selected to /Users/C3PO/.atom/packages ✗`
3. after some seconds I get: `Unable to download https://www.atom.io/api/packages/highlight-selected/versions/0.13.1/tarball: 500`

**Expected behavior:** 
See the packages installed.

**Actual behavior:**
Some packages cannot be installed.

**Reproduces how often:**
Since two hours ago.

**Comment by 50Wliu** [comment]
This is generally a temporary internet issue, either on your side or on the https://atom.io servers.  Please try again later.
