### ISSUE TITLE
Atom did not show previous file when reopening atom 

### ISSUE THREAD

**Issue by NoviceDuke** [atom/atom#15437]
### Description
OS: Mac Sierra
Atom:1.19.2

### Steps to Reproduce

1. click window x to exit atom
2. use short cut  command + q to exit atom
3. reopen atom

**Expected behavior:** [What you expect to happen]

If use step 1  or  2 . , atom should be reopen previous file

**Actual behavior:** [What actually happens]

In step 1 , it just got the empty window
In step 2 , it will show  previous file

**Comment by jirawat001** [comment]
in step 2

**Comment by 50Wliu** [comment]
This is the expected behavior on macOS and is consistent with how other macOS applications behave.  When you close Atom using the red "x", you haven't quit Atom yet.  Therefore, when you actually quit Atom, the only state that Atom saves is the empty window.
