### ISSUE TITLE
Modified file tab color

### ISSUE THREAD

**Issue by mmase** [atom/atom#15434]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I noticed that on the Atom website (https://atom.io/), there is a demo screenshot that shows that a modified file tab has yellow text (in both the side bar and file tab). However, this is not the case on a clean install of Atom. 

![image](https://user-images.githubusercontent.com/753529/29668336-d1ae036c-88ad-11e7-9597-f42bf2251a52.png)

Example:

![image](https://user-images.githubusercontent.com/753529/29668389-fa3c145e-88ad-11e7-8795-59b341aabe5e.png)

![image](https://user-images.githubusercontent.com/753529/29668395-fe7ed1be-88ad-11e7-8443-a1db805a8775.png)

### Steps to Reproduce

1. Modify a file
2. You will see it change only in the sidebar

**Expected behavior:** The tab font color changes
**Actual behavior:** It doesn't
**Reproduces how often:** 100%

**Comment by mmase** [comment]
the `tabs` package can enable this

**Comment by nsgawli** [comment]
Thanks @mmase,

You saved me!!! :-)
