### ISSUE TITLE
TextEditor rewrite data-grammar attribute updating regression

### ISSUE THREAD

**Issue by Siilwyn** [atom/atom#15447]
### Description
It seems like there's a regression with the TextEditor rewrite. The specs for my package [css-declaration-sorter-atom](https://github.com/Siilwyn/css-declaration-sorter-atom) suddenly started failing. @Arcanemagus found out that if you place a breakpoint at [main-spec.js#L39](https://github.com/Siilwyn/css-declaration-sorter-atom/blob/68825124d8c312376a4d809995935c1c1390aefb/spec/main-spec.js#L39) then `editor.getGrammar()` shows what you expect, but the `data-grammar` property of [main-spec.js#L9 ](https://github.com/Siilwyn/css-declaration-sorter-atom/blob/68825124d8c312376a4d809995935c1c1390aefb/spec/main-spec.js#L9) hasn't been updated, so the command "doesn't match".

Although `editor.GetGrammar()` is showing the expected CSS, the `data-grammar` property of the actual `workspaceElement` is still only `text plain null-grammar`. A workaround for now is [decreasing the editor specificity](https://github.com/Siilwyn/css-declaration-sorter-atom/pull/44/commits/95c1f2c47688d6629f0eed0b60e623472fa779f4).

### Steps to Reproduce

1. Change editor grammar
2. See editor's `data-grammar` not being changed

**Expected behavior:** `data-grammar` to reflect the currently used grammar.

**Actual behavior:** `data-grammar` stays the same.

**Reproduces how often:** 100%

### Versions
Atom    : 1.19.3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by as-cii** [comment]
Hello @Siilwyn and thanks for the bug report! ✨

> Although editor.GetGrammar() is showing the expected CSS, the data-grammar property of the actual **workspaceElement** is still only text plain null-grammar.

The `data-grammar` attribute is added and updated only on `atom-text-editor` elements, and never on `atom-workspace` element. Did you mean "the actual editorElement"?

If so, I am unable to reproduce this locally; when changing the grammar of the editor, the `data-grammar` attribute seems to update correctly for me. Can you post some reproduction steps that I can follow by opening Atom in safe mode? Thanks!

**Comment by Siilwyn** [comment]
@Arcanemagus could you shed some light on this? If I log `atom.workspace.getActiveTextEditor().getGrammar().scopeName` after setting the grammar it does return the proper grammar.

**Comment by Arcanemagus** [comment]
@as-cii @Siilwyn

Assuming you have reverted https://github.com/Siilwyn/css-declaration-sorter-atom/commit/36049ffdd2e02bdb453c91559fb024aec8aff69e locally, here are the steps to reproduce:

1. Open Atom on the project
2. For simplicities sake while testing, focus [this spec](https://github.com/Siilwyn/css-declaration-sorter-atom/blob/56998ffa1a244fe9038476376f3d10edf7708913/spec/main-spec.js#L35)
3. Run the specs (the focused spec will fail)
4. Open Developer Tools in the spec window and place breakpoints on these lines:
    * [here](https://github.com/Siilwyn/css-declaration-sorter-atom/blob/56998ffa1a244fe9038476376f3d10edf7708913/spec/main-spec.js#L38)
    * [here](https://github.com/Siilwyn/css-declaration-sorter-atom/blob/56998ffa1a244fe9038476376f3d10edf7708913/spec/main-spec.js#L9)
5. Run the specs again
6. When you hit the first breakpoint on L38, check `editor.getGrammar()` and note that it has correctly been changed to CSS. For some reason Developer tools doesn't allow access to `workspaceElement` here, even though it is in the closure, so let the code continue.
7. You should now hit the breakpoint on L9. Checking `workspaceElement.dataset.grammar` shows that it is still set to `text plain null-grammar`.

Note that if you save a reference to `editor` in the console (`var ed = editor`) you can access it on the breakpoint on L9 and see that `editor` still has the correct grammar.

**Comment by Siilwyn** [comment]
Thanks a ton @Arcanemagus, I can reproduce these steps!

**Comment by Siilwyn** [comment]
@Ben3eeE hi, could you re-label this issue since a way to reproduce has been given?

**Comment by nathansobo** [comment]
Bumping the priority on this since it's affecting a package author.

**Comment by nathansobo** [comment]
@Siilwyn if I understand the situation correctly, I think your problem may be due to the fact that the `dataset.grammar` property is now assigned asynchronously along with the rest of the editor updates. In general, it's not a good idea to rely on the state of the DOM for this kind of information. If you have a workaround that interacts directly with the model, I'd recommend sticking with that. I want to keep all of our editor DOM interaction asynchronous where possible going forward, so I'm going to close this. If you think I'm misunderstanding something, please let me know.

**Comment by Siilwyn** [comment]
Hi @nathansobo I understand however does that mean having grammar specific commands is not possible anymore? The [temporary fix](https://github.com/Siilwyn/css-declaration-sorter-atom/pull/44/commits/95c1f2c47688d6629f0eed0b60e623472fa779f4) just removes the specificity. I would actually expect the grammar to be set when the package is activated. Maybe I'm misunderstanding something too, thoughts?

**Comment by nathansobo** [comment]
@Siilwyn I'm seeing the grammar being reassigned when I inspect via the dev tools after switching the grammar.

![screen shot 2017-11-02 at 1 20 59 pm](https://user-images.githubusercontent.com/1789/32345728-b1a3bd82-bfd0-11e7-89bf-a520fa1da8d5.png)

Your mention of breakpoints leads me to suspect that your issue could be timing related, meaning there is a very narrow gap before the next frame render where the property isn't updated. For user-executed commands, using the grammar in the selector seems like it should work.

**Comment by Siilwyn** [comment]
@nathansobo thank you for for continuous help!

So if I understand it right, using the grammar selector still works but the issue is in the way my tests are written. Should I listen & wait for a particular event in the tests?

**Comment by nathansobo** [comment]
Yeah, it can be tricky and the API can be improved in this area. You should be able to wait on the scheduler update via `atom.views.getNextUpdatePromise()`.

**Comment by Siilwyn** [comment]
@nathansobo sorry to bother you again but that doesn't seem to work for me. Waiting for it (using `waitsForPromise` as `await` does not work at all) on any of the lines in this function causes the test to timeout after waiting five seconds:

https://github.com/Siilwyn/css-declaration-sorter-atom/blob/c438a873e78454c04cb8e2ea6d5b2c006d076524/spec/main-spec.js#L35-L43

**Comment by nathansobo** [comment]
You might try switching to [atom-mocha-test-runner](https://github.com/BinaryMuse/atom-mocha-test-runner) to get better support for returning promises from tests. That will help you leverage async/await but will take some work to restructure.

It was hard to see in your link exactly where you were having the problem.

**Comment by Siilwyn** [comment]
Yes, switching from test runner sounds good but more something I would do in the future.

Created a branch so the difference is visible and highlighted the view promise: https://github.com/Siilwyn/css-declaration-sorter-atom/compare/wait-for-view#diff-eb8118eda5229cd4256dde54e28ad36fR39

This results in the test timing out, I think because the promise never resolves.

**Comment by nathansobo** [comment]
Okay, sorry, after cloning that branch and messing with it I see I have led you astray.

You are using the legacy spec environment which forces all editor DOM updates to be synchronous, so it wasn't a timing issue. The problem is that the editor now only updates when it is visible. Since in that test your editor element isn't on the DOM, it isn't visible and therefore isn't getting updated.

If you need the editor element to update, try attaching it to the document like this:

```js
jasmine.attachToDOM(editor.element)
```

Good luck!

**Comment by Siilwyn** [comment]
Thanks that solved it! Did not know there is a new spec environment, [the atom flight manual](http://flight-manual.atom.io/hacking-atom/sections/writing-specs/) examples look similar. Any post on moving from to the new environment?

**Comment by nathansobo** [comment]
We have some basic documentation [here](http://flight-manual.atom.io/hacking-atom/sections/writing-specs/) in the "Customizing your test runner" section, but I think we need to do a better job advertising to people that they can transition off of Jasmine 1.3. Unfortunately many of our bundled packages are still on it, so we're still in transition ourselves.

**Comment by Ben3eeE** [comment]
I think we should open an issue for improving this documentation on the flight-manual repo. I can open one later unless someone gets to it first.

**Comment by Siilwyn** [comment]
All right! Opened an issue: https://github.com/atom/flight-manual.atom.io/issues/394

Appreciate all helpful replies, thanks a bunch!

**Comment by Ben3eeE** [comment]
Thank you for opening the issue @Siilwyn :bowing_man:
