### ISSUE TITLE
Scroll bars not showing in center pane items

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#15442]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Scroll bars not showing in pane items (text editors, settings view, etc)

### Steps to Reproduce

1. Go to System Preferences
1. Click General
2. Set "Show Scroll Bars" to "Always"
1. Launch Atom in your local Atom repository
1. Open `README.md`

**Expected behavior:** Scroll bars are visible in the text editor

**Actual behavior:** Scroll bars are only visible in the tree view

### Versions

```
Atom    : 1.19.3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.0
```

### Additional Information

Reproduces no matter what the OS preference is for scroll bars, "Always" just makes it more obvious.

**Comment by lee-dohm** [comment]
Possibly related: https://github.com/atom/atom/issues/15401 and https://github.com/atom/atom/pull/15367

**Comment by iolsen** [comment]
@nathansobo @as-cii likely caused by recent changes.

**Comment by hubertott** [comment]
Atom: 1.19.3
macOS: 10.12.5
Chrome: 60.0.3112.101 

For me scroll bars are hidden and unusable unless I set the OS preference to "Always" at which point they show. Note a restart of Atom is required for the OS change to have an effect.

**Comment by TitanNano** [comment]
I made the following discovery after the comment by @hubertott 

1. start with "when scrolling"
    1. tree-view shows native osx scrollbar on demand, editor has no scrollbar
    2. tree-view has static osx scrollbar, editor has no scrollbar
2. start with "always"
    1. tree-view as atoms custom scrollbar, edtior has also atoms custom scrollbar
    2. change to "when scrolling", tree-view has osx native on demand scrollbar, editor has no scroll bar
    3. change back to "always", both tree-view and editor have the osx native static scroll bar.
