### ISSUE TITLE
Major issue: Atom is creating infinite files and cannot be deleted

### ISSUE THREAD

**Issue by dasphillipbrau** [atom/atom#15454]
I created another question about 3 days ago, which was closed because I received a bot reply saying I should reproduce the problem on safe mode, even if I explicitly stated that I could not even get safe mode to launch.
Anyway, my problem started by Atom not opening, the uninstalling option didn't work (it would interrupt the process itself), so I manually deleted the folders and installed atom again.

It worked for a few days, until today, when the problem came back, and atom wouldn't open on any instance, even safe mode.

Now, when trying to delete it, I found out that the program was creating an infinite amount of files, so I can't even delete it manually. It's been trying to delete it for 15 minutes now and it's currently at 90000 files and it just keeps growing. How can I stop this? It's even affecting my PC's performance.

**Comment by Zireael07** [comment]
Where is it trying to create files at? Do you have write permissions for the folder it's trying to create files in?

**Comment by dasphillipbrau** [comment]
I don't know exactly at which folder is it trying to create the files because when I try to access the main atom folder in appData it just stays there, probably because of the huge amount of files in it.

I should clarify that I have never downloaded a single addon/package for atom

**Comment by maxbrunsfeld** [comment]
> Now, when trying to delete it, I found out that the program was creating an infinite amount of files

What do you mean when you say that Atom has created an infinite amount of files? What are you seeing exactly?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15454#issuecomment-325407492. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
