### ISSUE TITLE
keyframe animation re-triggered on pane-item activated again(after change tab and back).

### ISSUE THREAD

**Issue by t9md** [atom/atom#15451]
CC @nathansobo, @as-cii

Related #15185(fixed), #15449.

![keyframe-anime-retriggered](https://user-images.githubusercontent.com/155205/29739536-1d427a96-8a7b-11e7-889d-c6c27a557abc.gif)

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Switching active pane item(tab) and back changes `editor.element.style.display` from `"none"` to `""`, which cause keyfrmane animation re-triggered.

### Steps to Reproduce

Can reproduce in safe-mode.

1. Prepare style to use keyframe animation on your `style.less`

```less
@keyframes t9md-test-animation {
  from { background-color: red; }
  to { background-color: transparent; }
}

atom-text-editor .t9md-test-flash .region {
  animation-name: t9md-test-animation;
  animation-fill-mode: forwards;
  animation-duration: 10.0s;
  animation-iteration-count: 1;
}
```

2. Open more than two editor(editor1 and editor2) and select lines in editor1.
3. Open chrome dev-console and paste following code.

This code flash selected range which flash disappear after 10sec.

```javascript
(function flashreproduceIssue() {
  const editor = atom.workspace.getActiveTextEditor()
  const marker = editor.markBufferRange(editor.getSelectedBufferRange())
  editor.decorateMarker(marker, {type: "highlight", class: "t9md-test-flash"})
  setTimeout(function () {
    marker.destroy()
    console.log("destroyed");
  }, 10000);
})()
```

4. Within 10 sec, re-activate editor1 by switch to different item(=editor2) and back. See once fadeout-ed flash is restarted on editor1 become active again.

Keyfrmane animation is re-triggered when `editor.element.style.display` prop changed from `"none"` to `""`.

**Expected behavior:** [What you expect to happen]

Don't re-trigger keyframe animation.

**Actual behavior:** [What actually happens]

keyframe restarted

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%.

### Versions

```
Atom    : 1.20.0-beta4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

This article was helpful to understand this issue.
https://codepen.io/derekjp/post/keyframe-animations-display-vs-visibility

**Comment by t9md** [comment]
Experimenting in dev-console.

Using `editor.element.style.visibility = "hidden"` then `editor.element.style.visibility = ""` does not re-trigger  keyframe animation.
Animation state is maintained while disappear(hidden) and re-appear.

**Comment by t9md** [comment]
This article was helpful to understand this issue.
https://codepen.io/derekjp/post/keyframe-animations-display-vs-visibility

**Comment by nathansobo** [comment]
Yikes. This one could be tough unless we abandon tiles entirely and just absolutely position the lines in the scrollable area. I'm worried about the impact on layout time and paint behavior, but perhaps we should try it. We may want to wait until we have time to simplify the structure of lines.

**Comment by nathansobo** [comment]
@as-cii made a really good point to me a few minutes ago in chat. Now that we're no longer rendering individual tiles on the GPU, they no longer have opaque backgrounds for subpixel antialiasing.  That means we can actually just move the highlights outside of the tiles entirely and place them behind the text in the scroll container. This should be a pretty easy fix based on that and simplify the code.

**Comment by t9md** [comment]
Wow! Unbelievable good news.
Consolidating highlight nodes to the places out of line-tile would definately fix potential bugs we hadn't hit yet!

**Comment by as-cii** [comment]
This can be closed now that #15486 has been merged. ⚡️

**Comment by t9md** [comment]
This issue is caused when re-activating pane-item(tab).

> Switching active pane item(tab) and back changes editor.element.style.display from "none" to "", which cause keyfrmane animation re-triggered.

Does #15486 solve this issue?

**Comment by as-cii** [comment]
Oh okay, based on the conversation above related to tiles I assumed #15486 would fix it, but if it's related to showing/hiding the pane I don't think it will. Reopening this, sorry for the noise!

**Comment by t9md** [comment]
No sorry, comment we made was misleading/confusing.

The root cause of this issue is well explained by this.

https://codepen.io/derekjp/post/keyframe-animations-display-vs-visibility
