### ISSUE TITLE
When searching for a package to install, exact name is excluded from the list

### ISSUE THREAD

**Issue by felzix** [atom/atom#15464]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When searching for a package to install, using the package's exact name excludes that package from the list.

### Steps to Reproduce

1. Go to the `Install` tab in `Settings`.
2. Enter in, verbatim, `react`.

**Expected behavior:**
The `react` package is in the list of packages I could install. It should probable be the first one.

**Actual behavior:**

The `react` package isn't in the list at all. However, if I only enter in `reac` (less the `t`), the `react` package shows up.

<img width="846" alt="reac" src="https://user-images.githubusercontent.com/279660/29750902-d29f8a60-8afc-11e7-9ba7-40b5dbe61596.png">
<img width="889" alt="react" src="https://user-images.githubusercontent.com/279660/29750905-d60ef83e-8afc-11e7-9cc6-0bb2ae67aa11.png">

**Reproduces how often:** [What percentage of the time does it reproduce?]

always

### Versions
atom: 1.19.3
mac os sierra 10.12.6

**Comment by Ben3eeE** [comment]
Thank you for reaching out!

This issue belongs in the [settings-view](https://github.com/atom/settings-view) repository. Can you please open the issue there if one does not already exist, thank you :bowing_man:

**Comment by felzix** [comment]
This issue was moved to atom/settings-view#984
