### ISSUE TITLE
Atom seems to use some unneeded resources like CPU or additional GPU making laptop noisy

### ISSUE THREAD

**Issue by pgrycz** [atom/atom#15463]
Same issue found on both, Windows 10 and Ubuntu 17.04. Asus laptop with i7 core Intel.
When any version of Atom is used it results in produced noise by ASUS laptop's fan which doesn't exits when Bracket or Sublime is in use. In Atom every file opening, every editing file results in additional fan noise moments and this I have only with e.g Blender 3d when some constant countings are made during editing (constant use of CPU and GPU). I had similar issue with noisy fan or unneeded resources in use when wrong touchpad driver was installed - every scroll using touchpad resulted in additional fan noise. Installing proper driver fixed the issue and I think that there's something with Atom's internal engine to improve.

**Comment by maxbrunsfeld** [comment]
Efficiency is generally one of our top priorities, but without some specific information about what usage patterns cause high CPU usage, there's not much we can do with this issue. I'm going to close this out for now.

If you can [capture a CPU profile](http://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance) during a time where Atom appears to be using an unexpected amount of resources, that might be helpful for diagnosing the problem.
