### ISSUE TITLE
Highlight decorations on large ranges inconsistently rendered

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#15508]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Decorations of type `highlight` (possibly others) that cover a large range are inconsistently rendered in the editor.

### Steps to Reproduce

1. Install [large-decoration.zip](https://github.com/atom/atom/files/1264748/large-decoration.zip) as a package.
2. Open Atom.
3. Trigger `Large Decoration: Decorate` from the Command Palette

**Expected behavior:**

The entire text should be decorated with an underline.

**Actual behavior:**

The underline is inconsistently applied, skipping entire lines in a repeating pattern:
![image](https://user-images.githubusercontent.com/427137/29890018-027760a2-8d7b-11e7-940d-87c6506ed54e.png)

It looks like what's happening here is the highlights are in a separate `<div>`, and for some reason instead of creating one sub-`<div>` for each line, it creates only two: One for the first line and one that "covers" the rest of the lines in a "rendering block" which seems to contain 6 lines in the `TextEditor`.
![image](https://user-images.githubusercontent.com/427137/29890386-46f5644e-8d7c-11e7-9280-d78ac4a7bc4c.png)

**Reproduces how often:**

100% of the time.

### Versions

```
Atom    : 1.20.0-beta5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.1.windows.1
visual studio 2015
```

Note: This has been reported by users since at least the v1.19.0 betas, possibly earlier.

### Additional Information

Originally reported in https://github.com/steelbrain/linter-ui-default/issues/398, but I'm unsure how long this has been an issue.

**Comment by lee-dohm** [comment]
Reproduced using Atom v1.21.0-dev-bd9570b16 on Mac OS X 10.12.6.

**Comment by iolsen** [comment]
@nathansobo @as-cii This is an editor issue though we don't yet know whether it's a regression.

**Comment by Arcanemagus** [comment]
@iolsen Just got a chance to test this in v1.18.0, the behavior is _different_, but still incorrect:
![image](https://user-images.githubusercontent.com/427137/29896213-f7ce82be-8d90-11e7-8cfd-c3c9375d127b.png)

**Comment by Arcanemagus** [comment]
@as-cii As far as I can tell `text` decoration style works perfectly, thanks!

Looking over how the `highlight` style was meant to be used, it seems that the fact that it worked at all was a fluke. I'll put up a PR on `linter-ui-default` utilizing the new style.
