### ISSUE TITLE
Markdown table appears wrong

### ISSUE THREAD

**Issue by aleb** [atom/atom#15504]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Table in markdown file does not appear correct. 

### Steps to Reproduce

Create an test.md file with the following content:
```

| a | b | c |
 --- | --- | ---
a | a | a

```
Press ctrl+shift+m, notice a table with two rows appear and the first row has 4 cells instead of 3, first one being empty.

**Expected behavior:** 
https://gist.github.com/aleb/f6ed33806ca5dcbee0434544887360dd

**Actual behavior:** ![screen shot 2017-08-30 at 15 08 57](https://user-images.githubusercontent.com/505582/29873862-307daa14-8d95-11e7-86f3-aea733090709.png)

**Reproduces how often:** 100

### Versions

$ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
$ apm --version
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.1

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/markdown-preview if there's no existing issue already so we have it in the right place?

**Comment by aleb** [comment]
https://github.com/atom/markdown-preview/issues/496 Thanks!
