### ISSUE TITLE
Find in buffer or Find in Project, removes indent when use copy and paste block code

### ISSUE THREAD

**Issue by btrazzini** [atom/atom#15518]
Try to copy and paste the block code below and see the white-spaces to be removed.

[Original Block] 
```
.vitr{
    &-blog,
    &-prod{margin-top:20px;}
}
```

[Try to select only]
```
  &-blog,
  &-prod{margin-top:20px;}
```

[Paste in Find field - see white spaces removed]
```
&-blog,
&-prod{margin-top:20px;}
```

[Atom do not Found]

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/find-and-replace if there's no existing issue already so we have it in the right place?  And please fill out the issue template when creating a new issue, it's super helpful for us when triaging issues.
