### ISSUE TITLE
[broken items] No icon, github status in settings, packages

### ISSUE THREAD

**Issue by cchang62** [atom/atom#15519]
### Description

Due to company policy, I installed my Atom editor on my Ubuntu 16.04 of VirtualBox, and the internet of ubuntu in VirtualBox and its host, window 7 enterprise edition, is behind proxy. Proxy has been set up and installing new packages externally via apm is successful. Also, accessing projects on github or npm servers from my ubuntu are not problem. However, Atom editor can not show images or some status somehow, in the picture illustrated below.

At the same time, I also installed Atom editor on the host, window 7 enterprise edition, of VirtualBox. The editor shows everything correctly in the same condition of setting proxy. How can I debug the broken images?

### Versions
OS
VirtualBox:  5.1.26 r117224 (Qt5.6.2)
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Atom
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

### Additional Information

Attached image is my status I snipped from my desktop of 	**Ubuntu 16.04.2 LTS**.

![atomeditor](https://user-images.githubusercontent.com/15147139/29854188-f571bcee-8d76-11e7-8530-c9d5917049a1.jpg)

**Comment by rsese** [comment]
I went ahead and copied this over to the settings-view package @cchang62 so we have it in the right place.
