### ISSUE TITLE
Atom won't open files

### ISSUE THREAD

**Issue by sasquatch666** [atom/atom#15520]
I'm using Atom 1.19.4 on MacOS (10.12.6) and suddenly today I can't open files from Finder.  If I double click on a file associated with Atom, it opens in a totally blank window (no blank document, no file tree). Also, opening Atom by itself is not loading the previous state (it used to open the files from the last session). When I do open Atom by itself (ie not by trying to open a file), it does open a blank document. Also worth noting, I can open a file in Atom from the File menu once Atom is open.

The first time I had this problem today, Atom was 1.19.3, I updated and the problem persisted.

I have attached my console errors.

Uncaught (in promise) TypeError: Cannot read property 'onWillSave' of undefined
    at Project.module.exports.Project.subscribeToBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:560:19)
    at /Applications/Atom.app/Contents/Resources/app/src/project.js:133:25

Uncaught (in promise) TypeError: Cannot read property 'isRetained' of undefined
    at /Applications/Atom.app/Contents/Resources/app/src/project.js:149:27
    at Array.map (native)
    at Project.module.exports.Project.serialize (/Applications/Atom.app/Contents/Resources/app/src/project.js:147:47)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:876:37)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1209:33
    at AtomEnvironment.module.exports.AtomEnvironment.saveState (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1205:20)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:373:34

**Comment by rsese** [comment]
Thanks for the report - do you see any difference running in safe mode (`atom --safe`)?  If you open a file with Atom from the command line (e.g. `atom file`), do you see the same behavior where you get a blank window?

Lastly, does clearing saved state help (keep in mind that any unsaved changes will be lost):

http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

As a side not, it would be super helpful for future issues if you can use the issue template since it gives us a lot of baseline information.

**Comment by Noman50** [comment]
Hello,
Does atom work on window 10?

**Comment by sasquatch666** [comment]
Sorry I erased the template… I guess I posted in a hurry and just deleted all the default text without looking at it... I’ll use it next time.

Atom messes up when opened by launching a file, whether through the command line or from Finder.  Opening Atom cleanly, through the Finder interface or through the terminal in safe mode, opens with a blank document and I can then load a file (although tree view, if I display it, doesn’t display the file’s directory…).

Okay, I cleared the window state, and Atom now behaves normally.  Thanks for the help.

**Comment by rsese** [comment]
> Sorry I erased the template… I guess I posted in a hurry and just deleted all the default text without looking at it... I’ll use it next time.

No problem, thank you!

> Okay, I cleared the window state, and Atom now behaves normally.  Thanks for the help.

Glad that got you back up and running - we'll close this for now but we can re-open if you see this problem again or if someone else runs into the same issue.

**Comment by SeanFelipe** [comment]
I am seeing a similar issue on a brand new install. OSX 10.11.6, 2014 MBP15 Retina. Just installed the app and it won't open files using the open dialog.

**Comment by rajat1saxena** [comment]
Atom is not opening the files for me on `Ubuntu 16.04`. I am trying to open files by double clicking on a file in `Tree View` pane. I've tried re-installing, deleted `.atom` folder, open atom using `atom --safe`, but nothing works.

**Comment by heisian** [comment]
I can't open files using command+n.
I can't open files from Finder. Atom won't open them.
I can open a project folder within Atom, and files within that project just fine.

**Comment by bkecskemeti** [comment]
Same issue. Fresh install, atom won't open any file or project. Version info:
```
Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by Algomorph** [comment]
Same issue on 16.04.3 LTS with Atom 1.23.3.

**Comment by rsese** [comment]
Since the original issue as reported is resolved (and I'm assuming folks aren't getting the same console errors and clearing saved state didn't help), if you're having a problem with opening files please open a new issue and fill out the issue template and we'll take a look.

**Comment by Algomorph** [comment]
@rsese Actually, clearing the saved state did the trick. Sorry I did not read your solution comment to the end.
Wouldn't this still be a bug, though? I.e. something is causing this issue to come up, people shouldn't lose their time on looking for a closed GitHub issue and reading every comment to fix atom on their machine. I'll leave that up to the devs/maintainers to consider, hoping they have more time. I'm done here for now, sorry, I need to do something else right now.

**Comment by bpna** [comment]
I am unable to open files as well. This happened after editing a project for a few days with some friends using the Teletype package
