### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'onWillSave' of undefined

### ISSUE THREAD

**Issue by epaulet** [atom/atom#15535]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

```
Uncaught (in promise) TypeError: Cannot read property 'onWillSave' of undefined
    at Project.module.exports.Project.subscribeToBuffer (/Applications/Atom.app/Contents/Resources/app/src/project.js:560:19)
    at /Applications/Atom.app/Contents/Resources/app/src/project.js:133:25
```
Receiving this error every time I open atom in one specific repository. When this error pops up, Atom does open, but nothing loads. It's completely blank and I can't interact with the editor directly at all (I can still move the window around, open the top dropdowns, etc). Unsure what the root cause is, but it seems like maybe one of the `bufferPromises` resolved to `undefined`.

### Steps to Reproduce

1. Open Atom using `atom .` command inside of problematic directory. Happens when using `--safe` flag as well.

**Expected behavior:**
Atom opens and I'm able to open files within the selected directory.

**Actual behavior:**
Atom opens and stays blank.

**Reproduces how often:**
100% of the time in one directory. Never anywhere else.

### Versions
```
Atom    : 1.19.4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information
I would guess there there is some configuration that can reproduce this, but I'm able to identify what in this directory causes the problem to occur.

**Comment by Ben3eeE** [comment]
Thank you for the report :bowing_man: 

We have had a report for this error before and it seems that clearing saved state worked for them /cc: https://github.com/atom/atom/issues/15520#issuecomment-326398658

/cc: @rsese

**Comment by epaulet** [comment]
Clearing the window state seems to have taken care of the problem. Thank you!

**Comment by rsese** [comment]
Maybe we can keep this one (since it has the template filled out) open for a bit to see if other folks run into this error.

Do you happen to remember if you ran into this error right after updating to 1.19.4 @epaulet?

**Comment by epaulet** [comment]
@rsese I hadn't opened the problematic directory with atom in a few months at least so unfortunately I'm not really sure when it started happening.

**Comment by OscarBarrett** [comment]
I ran into this after upgrading from 1.16 to 1.20. Never experienced it on 1.16.

**Comment by rsese** [comment]
Thanks @OscarBarrett :+1:  Can you share more details about what happened? 

* What are the steps to reproduce for you (is it specific to a particular project as reported in this issue)?
* In addition to the error, is Atom also blank for you?
* What operating system are you running?
* What specific version of Atom are you running (`atom -v`)?

**Comment by Pondidum** [comment]
I got this error when migrating all my projects (and atom settings) to a new machine by copy and pasting the directories across.
Clearing window state `atom --clear-window-state` as suggested by @Ben3eeE fixed the issue.

**Comment by jorgebg** [comment]
This happened to me as well today

`atom --safe` didn't work either

Solved by running `atom --clear-window-state` 👍 thank you for this

**Comment by Bouska** [comment]
I just updated from Atom 1.0.7 to 1.21.2 on a Fedora 26 x64. Every time I open the root directory of an old (?) git repo (and only those: no problem on a sub directory or a hg root directory or even an newly cloned git repo for example) I get both the error and the blank page. I had no problem with the 1.0.7 version. I get the problem either the safe flag on or off. 

Also solved by running `atom --clear-window-state`

**Comment by oilart** [comment]
Facing the same issue: 
```
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

~~atom --clear-window-state~~ didn't help.

**Comment by rsese** [comment]
@oilart - not sure what the strikethrough  with `atom --clear-window-state` means but just to confirm, you  ran that command but you still get this error with a particular project?

**Comment by oilart** [comment]
@rsese yes, confirming this. I had to reinstall it completely.
```
rm ~/.atom 
rm -rf /usr/local/bin/atom
rm -rf /usr/local/bin/apm 
rm  ~/Library/Preferences/com.github.atom.plist 
```

Not sure what caused this but here some of the symptoms I've noticed before looking at dev tools:
```
- Menu was not fully working. e.g no way to open preferences via menu but `command` + `,` keys worked.
- Tabs were added when opening new files but tab focus wasn't changed.
- Editor settings were not properly loaded - no whitespaces displayed, trimming was not working etc. - feelt like the editor doesn't have any settings at all.
```

Hope this helps.
