### ISSUE TITLE
Installing any packages is failing in Atom Idle

### ISSUE THREAD

**Issue by Dipanjan17** [atom/atom#15536]
<!--
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.6.9/iojs-v1.6.9.tar.gz
gyp http 200 https://atom.io/download/electron/v1.6.9/iojs-v1.6.9.tar.gz
gyp http GET https://atom.io/download/electron/v1.6.9/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v1.6.9/win-x64/iojs.lib
gyp http GET https://atom.io/download/electron/v1.6.9/win-x86/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.6.9/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at TLSSocket.onHangUp (_tls_wrap.js:1111:19)
gyp ERR! stack     at TLSSocket.g (events.js:291:16)
gyp ERR! stack     at emitNone (events.js:91:20)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:974:12)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:98:9)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Users\\Dipanjan Chowdhury\\AppData\\Local\\atom\\app-1.19.5\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Dipanjan Chowdhury\\AppData\\Local\\atom\\app-1.19.5\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "--runtime=electron" "--target=1.6.9" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd C:\Users\Dipanjan Chowdhury\.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
