### ISSUE TITLE
Editor displays white screen for some time (approx 2 mins) when minimized for longer time and open back

### ISSUE THREAD

**Issue by bhaskarmac** [atom/atom#15537]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Editor displays white screen for some time (approx 2 mins) when minimized for longer time and opened back

[Description of the issue]

### Steps to Reproduce

1. Minimize the Atom Editor for longer time approx 3 hours
2. Open it after the time
3. Observe the white screen displayed in the editor (refer 
![whitescreen](https://user-images.githubusercontent.com/4056847/30021002-7ff8cb90-9183-11e7-8c50-21cf5adc7f23.png)
)

**Expected behavior:** White screen should not be displayed

**Actual behavior:** White screen is displaying when opened

**Reproduces how often:** 65%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

atom --verison
Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

OS
Windows 10 Pro 32 bit

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report - might be tough to reproduce since you say you only see 65% of the time but I just started 1.19.5 on Windows 10 and minimized it, I'll check again in a few hours.

When you see the white screen, do the menus work at all?  E.g. can you open a file?  

Also, can you check if there are any error in console in the dev tools?

**Comment by bhaskarmac** [comment]
Yes, sure I will check if the menus work. I will update.

**Comment by rsese** [comment]
Just dropping a note that I checked after ~3 hours and couldn't reproduce and I also left Atom minimized overnight and couldn't reproduce in the morning.  Can you also confirm that you only just started seeing this behavior after updating to 1.19.5 and didn't see it happen before?

**Comment by bhaskarmac** [comment]
@rsese  You can close this issue. I am unable to reproduce it with the latest version of Atom. :+1:

**Comment by rsese** [comment]
I wonder if an Electron update might have fixed this for you - in any case, thanks for letting us know!
