### ISSUE TITLE
MacOS Opening native tab toggles fullscreen

### ISSUE THREAD

**Issue by seaside98** [atom/atom#15534]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In MacOS when the "Prefer tabs when opening documents" is set to "Always", File->Open on a non-fullscreen session will toggle the fullscreen if atom remembers the new project as being fullscreen. This is really annoying when I open new tabs and get jerked out of my element into fullscreen. Atom should not toggle fullscreen when opening a new tab, only a new window.

### Steps to Reproduce

First we set up the scenario:
1. Navigate to ```Dock``` in the macOS System Preferences
2. Change ```Prefer tabs when opening documents:``` to ```Always```
3. Open up atom to a directory
4. File->Open another directory (You should now have 2 native tabs in the same window)
5. Enter the macOS native fullscreen mode
6. Close one of the native tabs [Taking note of that path] (So only one project is left open now)
7. Exit native fullscreen
8. Quit Atom

Now we can reproduce the bug:
1. Open up atom to the directory that was last open (Atom should open and NOT enter fullscreen)
2. Now File->Open the path you took note of in step 6

**Expected behavior:** [What you expect to happen]
The new native tab should open and the app should not enter native fullscreen.

**Actual behavior:** [What actually happens]
The app enters native fullscreen.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time

### Versions

Atom: 1.17.2
MacOS: 10.12.6

![out](https://user-images.githubusercontent.com/6372893/30006052-712a1ab6-90b5-11e7-83c8-a7c02318ad9f.gif)

**Comment by colllin** [comment]
@seaside98 I don't even see the preferences option `Prefer tabs when opening documents` in atom 1.20.0... 😬 I really wanted it after I saw your issue!  I can't figure out how to get native tabs at all in this version...

**Comment by seaside98** [comment]
@colllin It's in the macOS System Preferences app, not in atom. Open up the System Preferences and navigate to the Dock section to change the setting. 
![screen shot 2017-09-18 at 7 30 29 pm](https://user-images.githubusercontent.com/6372893/30570629-fb069388-9ca7-11e7-91b3-b7f489f995f3.jpg)

**Comment by colllin** [comment]
Ohhh.  Thanks for the clarification.  Either way, unfortunately, this capability seems to be blocked in Atom 1.20.0.  I’m not sure if this was an Atom decision, an Electron decision, or some combination.  If there’s any way to bring back native tabs, I would be happy to contribute a PR.

**Comment by 50Wliu** [comment]
@seaside98 can you check with Atom 1.21-beta?

@colllin Native tabs have been re-enabled in Atom 1.21-beta.

**Comment by seaside98** [comment]
@50Wliu I just tested with Atom 1.21-beta and the bug is still there.
