### ISSUE TITLE
Expanded code-blocks overlap with previous code

### ISSUE THREAD

**Issue by StuntHacks** [atom/atom#15549]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When expanding a collapsed code-block while the current viewport isn't scrollable (i.e. all code that is shown fits on the screen), the expanded code overlaps with the code right among it (See screenshot). Only re-opening the file helps.

**Reproduces how often:** Every time on the code I discovered it, never on some simple, short code.

### Versions

Atom    : 1.19.3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Screenshot

![atomcollapsebug](https://user-images.githubusercontent.com/11249519/30066809-51c86eac-9259-11e7-9ee7-7626f802ecaa.png)

**Comment by Ben3eeE** [comment]
> Every time on the code I discovered it, never on some simple, short code.

Can you share that code to help us reproduce?

**Comment by StuntHacks** [comment]
For some reason, I'm not able to re-create it now.

However, here is the full file in which I experienced the problem:

```cpp
#pragma once
#include "includes.h"
#include "drawing.h"
#include "./style.h"
#include "./notification.h"
// #include "./menuEntry.h"

class Menu {
private:
	std::vector<menuEntry_s*> m_entries;
	// std::vector<MenuEntry> m_menuEntries;
	unsigned int m_selected, m_frameCounter, m_batteryIconState;
	bool m_entryLaunched, m_batteryIconShown;

	sf2d_texture 	*m_buttonLaunchTex,
								*m_buttonLaunchPushedTex,
								*m_buttonSettingsTex,
								*m_buttonSettingsPushedTex;

	std::vector<sf2d_texture*> m_batteryIcons, m_wifiIcons;

	Text *m_settingsText, *m_launchText, *m_timeText;
	Notification m_not;

	// touch control
	bool m_settingsButtonTouched, m_launchButtonTouched, m_menuEntryTouched;
	unsigned int m_touchedEntry;

public:
	Menu();
	virtual ~Menu();

	void pushEntry(menuEntry_s* t_me) { this->m_entries.push_back(t_me); };
	void loadEntries(std::string t_path = "sdmc:/3ds");

	std::vector<menuEntry_s*> getEntries() { return this->m_entries; };
	unsigned int getEntryAmount() { return this->m_entries.size(); };
	unsigned int getSelected() { return this->m_selected; };
	menuEntry_s* getSelectedEntry() { return this->m_entries[this->m_selected]; };
	bool entryLaunched() { return this->m_entryLaunched; };

	// TODO: move these two to menu.cpp and clean them up
	inline bool touchInAbsoluteBox(int t_x, int t_y, int t_x2, int t_y2, int t_type = 0) {
		touchPosition touch;
		hidTouchRead(&touch);

		u32 keyState;

		if(t_type == 0) {
			keyState = hidKeysHeld();
		} else if(t_type == 1) {
			keyState = hidKeysDown();
		} else {
			keyState = hidKeysUp();
		}

		return	keyState & KEY_TOUCH
						&& touch.px >= t_x
						&& touch.py >= t_y
						&& touch.px <= t_x2
						&& touch.py <= t_y2;
	}
	inline bool touchInRelativeBox(int t_x, int t_y, int t_w, int t_h, int t_type = 0) {
		touchPosition touch;
		hidTouchRead(&touch);

		u32 keyState;

		if(t_type == 0) {
			keyState = hidKeysHeld();
		} else if(t_type == 1) {
			keyState = hidKeysDown();
		} else {
			keyState = hidKeysUp();
		}

		return	keyState & KEY_TOUCH
						&& touch.px >= t_x
						&& touch.py >= t_y
						&& touch.px <= t_x + t_w
						&& touch.py <= t_y + t_h;
	}

	void drawTop();
	void drawBottom();
	void draw();
	void update();
};
```

**Comment by Ben3eeE** [comment]
I can reproduce this /cc: https://github.com/atom/atom/issues/15761#issuecomment-332753144
