### ISSUE TITLE
Atom interface is corrupted on macOS 10.11.6 on versions > 1.19.2

### ISSUE THREAD

**Issue by mrdc** [atom/atom#15544]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom interface is completely corrupted (graphical glitches) after update to 1.19.3, 1.19.4 or 1.19.5.
--safe mode make no changes. Atom < 1.19.3 has no issues.
![untitled](https://user-images.githubusercontent.com/16876990/30058142-5698b61a-9242-11e7-8167-6617f3387831.png)

### Steps to Reproduce

1. Update Atom to 1.19.3+.
2. Run Atom.
3. As soon as the application starts interface graphics is completely corrupted.

**Expected behavior:** [What you expect to happen]

Interface without graphical glitches.

**Actual behavior:** [What actually happens]

Interface is completely corrupted - not possible to use.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% - each time I launch Atom > 1.19.2.

### Versions

Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

* Do you see any errors in the developer tools console?
* Have you tried clearing saved state or resetting to factory defaults as mentioned in the [flight-manual](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?

**Comment by mrdc** [comment]
1. Unfortunately, the whole interface is corrupted - I can see nothing inside Atom window (check a screen when I toggle Dev tools inside Atom).
![untitled](https://user-images.githubusercontent.com/16876990/30059577-4c56605c-9248-11e7-9fc1-236e2820f5a2.png)
2. Yes, I've done atom --clear-window-state. No changes in behaviour.
Installing 1.19.2 back fixes the issue.
3. In macOS Console I see these messages:

`9/5/17 13:46:15.360 Atom Helper[5204]: <<<< VTVideoEncoderSelection >>>> VTSelectAndCreateVideoEncoderInstanceInternal: no video encoder found for 'avc1'
9/5/17 13:46:15.360 Atom Helper[5204]: [13:46:15.360] VTSelectAndCreateVideoEncoderInstanceInternal signalled err=-12908 (err) (Video encoder not available) at /Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-1731.15.207/Sources/VideoToolbox/VTVideoEncoderSelection.c line 1308
9/5/17 13:46:15.360 Atom Helper[5204]: [13:46:15.360] VTCompressionSessionCreate signalled err=-12908 (err) (Could not select and open encoder instance) at /Library/Caches/com.apple.xbs/Sources/CoreMedia_frameworks/CoreMedia-1731.15.207/Sources/VideoToolbox/VTCompressionSession.c line 1003`

**Comment by Ben3eeE** [comment]
@mrdc Thank you for the additional information :bowing_man: Can you run `atom --foreground` and see if there is any additional output?

**Comment by mrdc** [comment]
Here you go:

atom --foreground
[9056:0905/145902.547433:INFO:CONSOLE(70096)] "Failed to require the main module of 'platformio-ide-terminal' because it requires one or more incompatible native modules (bin, bin, bin, bin, bin, bin, bin, bin).
Run `apm rebuild` in the package directory and restart Atom to resolve.", source: <embedded> (70096)

**Comment by Ben3eeE** [comment]
@mrdc I have some more questions, if you could answer them that would be great, thanks 🙇 

The error you are seeing when running Atom in the foreground can be fixed by running `apm rebuild` inside the `~/.atom/packages/platformio-ide-terminal` folder. Can you try doing this to see if that changes anything? See the commands you need to run below:

```
cd ~/.atom/packages/platformio-ide-terminal
apm rebuild
```

* How did you install Atom?
* From where did you download Atom?
* In what directory is Atom installed?
* Can you verify that you tried [resetting to factory defaults](http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults)? When I first asked about this you only answered that you tried to clear window state.
* Is there something unique about your system/hardware that you can tell us about?

**Comment by mrdc** [comment]
1. cd ~/.atom/packages/platformio-ide-terminal
app rebuild
No changes - the same issue.
2. Long time ago from zip from the Atom website. Was updating via auto-update.
3. See above.
4. /Applications.
5. Yes, I have tried resetting to factory defaults - see screenshot:
![untitled](https://user-images.githubusercontent.com/16876990/30068990-1d05b134-9268-11e7-8fe5-da16dfdad70e.png)
6. Yes, it's macOS running on Sony laptop :) Other software works fine - as Atom did before 1.19.3.

**Comment by rsese** [comment]
Thanks @mrdc - was taking a look at this issue too and just so I'm on the same page, can you copy and paste from Terminal a transcript of running these commands and their full output?  Thanks for bearing with us :v:

```
cd ~/.atom/packages/platformio-ide-terminal
apm rebuild
atom --clear-window-state
```

Lastly, if you have any other Electron apps installed (e.g. Slack, VS Code, etc.) can you check if you see any similar problems?  And the same with Chrome?

**Comment by mrdc** [comment]
MacBook-Pro  ~  cd ~/.atom/packages/platformio-ide-terminal
MacBook-Pro  ~/.atom/packages/platformio-ide-terminal  apm rebuild
Rebuilding modules ✓
MacBook-Pro  ~/.atom/packages/platformio-ide-terminal 
MacBook-Pro  ~/.atom/packages/platformio-ide-terminal  atom --clear-window-state
MacBook-Pro  ~/.atom/packages/platformio-ide-terminal 

Makes no changes - corrupted graphics.

>Lastly, if you have any other Electron apps installed (e.g. Slack, VS Code, etc.) can you check if you >see any similar problems? And the same with Chrome?
Yes, the same issue with Slack - "Reset app data" helps for a while, then it's again becomes corrupted.

**Comment by rsese** [comment]
Thanks @mrdc :+1:

> Yes, the same issue with Slack

Oh interesting, so it seems like this is maybe an Electron issue rather than an Atom issue yeah @Ben3eeE?

**Comment by ekajmada** [comment]
I had this problem today after update on a mac.  This is a similar problem I had with Chrome a while back. To fix run  "atom --disable-gpu" in the terminal that should clear it up

**Comment by Ben3eeE** [comment]
> Electron issue rather than an Atom issue yeah @Ben3eeE?

Yeah it does sound like an Electron issue.

> To fix run "atom --disable-gpu"

That was what I was going to recommend after learning that it is an Electron issue :+1: 
@mrdc Does `atom --disable-gpu` work for you?

**Comment by mrdc** [comment]
@ekajmada 
>To fix run "atom --disable-gpu" in the terminal that should clear it up

Thanks! It fixed the issue.

@Ben3eeE 
>Yeah it does sound like an Electron issue.

Electron wasn't updated - 1.6.9 has worked fine for Atom < 1.19.3.

**Comment by mrdc** [comment]
Atom 1.21.0 - the same issue :(
