### ISSUE TITLE
Add the TextEditor.element to the public API

### ISSUE THREAD

**Issue by komyg** [atom/atom#15559]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I would like to request that the `TextEditor.element` property be added to the public API, because it contains very helpful methods for package development such as the `getFirstVisibleScreenRow()` and `getLastVisibleScreenRow()`, which return which are the lines that are currently visible in an editor.

Note: I am also using these methods on my own package: [srt-helper](https://atom.io/packages/srt-helper). Previously I was using the `TextEditor.presenter.startRow` and `TextEditor.presenter.endRow` properties, but since the `presenter` no longer exists I had to start using the `element` property. This is another reason that I would like to request that the `TextEditor.element` be added to the public API: so that my package remains stable on the next versions of Atom.

### Steps to Reproduce

N/A

### Versions

Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Windows 10

### Additional Information

Link to discussion in the Atom forums: https://discuss.atom.io/t/how-to-get-visible-lines-numbers-in-atom-editor/47065/7

**Comment by iolsen** [comment]
@nathansobo do you have an opinion here?

**Comment by nathansobo** [comment]
I think it's a good idea to document the `.element` property.

Ultimately all the custom methods like the ones mentioned in the body (`getFirstVisibleScreenRow` etc) that are on element currently should be public methods on the editor itself that just don't always return values if the editor isn't associated with an attached element. But there's still utility in getting access to the DOM node.

We may want to explicitly emphasize that the DOM structure of the editor is not guaranteed to be stable and people should resort to DOM interaction only when what they are attempting isn't possible with more official facilities.

**Comment by pittsw** [comment]
Is there any progress on this?  I'm writing a plugin that would also need to access the current visible rows.

**Comment by khlevnov** [comment]
To reproduce it -- screenshot will work when the first line will be in bound of window. It can be invisible in editor, but should be visible in window. Scroll down from the first line by small steps and try to save screenshots

Works ok  

![image](https://user-images.githubusercontent.com/5495790/44996382-53cf4e80-afb0-11e8-8d3c-fa0a719f7ff7.png)

Works ok  

![image](https://user-images.githubusercontent.com/5495790/44996394-68134b80-afb0-11e8-91ea-bbf526329acb.png)

Doesn't work  

![image](https://user-images.githubusercontent.com/5495790/44996404-75303a80-afb0-11e8-9b6a-0d039180307f.png)
