### ISSUE TITLE
Select all automatically unfolds any folded content

### ISSUE THREAD

**Issue by MikeWillis** [atom/atom#15565]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When performing a select-all, any folded content is automatically unfolded.

### Steps to Reproduce

1. Fold some content
2. Select all

**Expected behavior:**

Folded content remains folded (but is available as part of any cut/copy/paste operations)

**Actual behavior:**

Folded content unfolds

**Reproduces how often:**

100%

### Versions

Atom    : 1.19.6
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Windows 10 64 bit

### Additional Information

Note that when you highlight a folded section by dragging the mouse over it, it remains folded, and its contents are available for cut/copy/paste operations.

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce on 1.19.6 on macOS 10.12.6 but just noting that this isn't a regression from 1.18.0 (h/t to @Ben3eeE for checking) and likely even some amount of time before that.  This behavior was referenced back in https://github.com/atom/atom/issues/2953#issuecomment-280672731 but it doesn't look like an issue was opened for this behavior.

I'll tag it as a bug for now and ask the team to take a look.
