### ISSUE TITLE
Crashing every few seconds. Android Studio unstaged changes.

### ISSUE THREAD

**Issue by gjgollub** [atom/atom#15561]
Hi all, 

I ran through the debugging report. I have run Atom on safe mode and checked to make sure I have the most updated version of atom. I was working on a new project last night with no issues. Early today, I started to edit the file, and atom crashed. I checked the window for any clue of what might have happened, and a new window appeared on my screen called git. It listed over 1000 unstaged changes from Android studio. The only thing I can think to do next is to clear the save state or return to factory settings, but I don't want to lose all my data. I'm unsure about what changed between yesterday and today. It did not crash at all yesterday. I have attached a screenshot below.

![screenshot 7](https://user-images.githubusercontent.com/23300893/30125710-f0721a1c-92fe-11e7-85c4-50c72dcb0d68.png) 

**Expected behavior:** When I open up Atom, I expect the program not to crash a few seconds after I make a change.

**Actual behavior:** The git window is filled with unstaged changes relating to android studio after I make any change to Atom. Atom then crashes. This has never happened before, I have had android studio installed the entire time I have had atom installed (a few months). 

**Reproduces how often:** Every time I open up Atom and click, or type, 100%.

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Just to be safe, I'd suggest copying the project you're working on if you haven't already.

Can you check if you have a `.git` directory in your home directory?

```
ls -ld ~/.git
```

If you do and you didn't create it intentionally, go ahead and rename it and start Atom again:

```
mv ~/.git ~/.git-backup
```

**Comment by rsese** [comment]
Sorry and just to clarify, you should run the commands I shared above in Git Bash which I see you have installed based on your screenshot.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15561#issuecomment-327587767. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
