### ISSUE TITLE
Atom not install the update after relaunch.

### ISSUE THREAD

**Issue by yubaoquan** [atom/atom#15574]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Quit atom and relaunch it, atom didn't install the update, but only show the squirrel icon.

### Steps to Reproduce

1. press cmd-q or right click atom icon in dock to quit it  
2.click the atom icon in dock to relaunch it

**Expected behavior:** Atom update to version 1.20.0-beta6

**Actual behavior:** Atom still in version 1.20.0-beta5 with the squirrel icon.

**Reproduces how often:** 100%

### Versions

Atom    : 1.20.0-beta5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 3.6.1
git 2.11.0

OS: macOS sierra 10.12.6

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by yubaoquan** [comment]
I tried several times later and finally it seems like the update data was fully downloaded, I relaunched it, and got an alert.
![popo_2017-09-07 18-26-01](https://user-images.githubusercontent.com/2340296/30159330-cef9449e-93fa-11e7-9c8e-b3e0e7a6891e.jpg)

**Comment by yubaoquan** [comment]
I did the steps again, this time I wait a long time for atom to relaunch, it updated correctly.

**Comment by tony-kerz** [comment]
i've been having the same issue for the past few releases, i've resorted to downloading new versions manually from the website...

**Comment by rsese** [comment]
Sounds like things are working ok for you now @yubaoquan so I'll go ahead and close this.

If you were hitting the same "The command is disabled and cannot be executed" error @tony-kerz, you can subscribe to https://github.com/atom/atom/issues/15417 if you'd like.
