### ISSUE TITLE
On Windows, .atom as symbol link not works

### ISSUE THREAD

**Issue by zyf0330** [atom/atom#15578]
### Description

I put a symbol link at `%userprofile%\.atom` on Windows, but atom doesn't start in the latest upgrade.

### Steps to Reproduce

If I remove that symbol link then it create a new `.atom` and start normally.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

The newest x64 version on Windows from atom.io

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Can you fill in all the template sections in more detail?  E.g. for steps to reproduce, can you share the exact command you used to create a symlink?  And for the actual behavior, you mentioned "atom doesn't start in the latest upgrade" - can you share more details about that (are there any error messages, does nothing happen, etc.)?  

Also what version of Atom worked ok with `%userprofile%\.atom` symlinked?  

Let us know when you've added more details and we can definitely re-open and go from there.
