### ISSUE TITLE
macOS plist files not showing correctly

### ISSUE THREAD

**Issue by Aerozolic** [atom/atom#15579]
Hi!

So I tried to open a plist file and Atom wasn't able to read/show it correctly. After some googling I installed plist-converter and also added:
customFileTypes:
      "text.xml.plist": [
        "plist"
      ]

Still, Atom is unable to show plist files correctly.

How to fix this?

Atom version: 1.19.6
macOS: 10.12.6

**Comment by Ingramz** [comment]
@Aerozolic could you please share a plist file that is displayed incorrectly for you.

**Comment by Aerozolic** [comment]
For example Transmissionbt plist.
Atom:
![screen shot 2017-09-07 at 18 53 24](https://user-images.githubusercontent.com/25500346/30172599-fe2ba63c-93fd-11e7-9256-d63523dd76fd.png)

BBEdit:
![screen shot 2017-09-07 at 18 54 01](https://user-images.githubusercontent.com/25500346/30172610-0344386e-93fe-11e7-9bc5-b48bead0fb84.png)

**Comment by danielbayley** [comment]
@Aerozolic This might be an issue with [my package](https://github.com/danielbayley/atom-plist-converter) as opposed to with Atom?

**Comment by danielbayley** [comment]
@Aerozolic This might be an issue with [my package](https://github.com/danielbayley/atom-plist-converter) as opposed to with Atom?

**Comment by Aerozolic** [comment]
@danielbayley how can you/we test this?

**Comment by danielbayley** [comment]
@Aerozolic Maybe file the issue over there, and upload your file so I can test.

**Comment by Ben3eeE** [comment]
Going to close this out since it appears to be a problem in the plist-converter package.
