### ISSUE TITLE
Open with Atom option for multiple files opens each file in different instance

### ISSUE THREAD

**Issue by bhaskarmac** [atom/atom#15573]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### "Open with Atom option" for multiple files opens each file in different instance

Opening multiple files using systems context menu by selecting multiple files causing the opening of each file in different instance

### Steps to Reproduce

1. Select multiple files.
2. Open all files by using context menu option "Open with Atom".
3. Observe each file is opened in different instance of Atom.

**Expected behavior:** It should open in existing instance if running otherwise all files should be opened in one instance

**Actual behavior:** Each file is opened in different instance

**Reproduces how often:** 100%

Note: Please ignore or add comment if this is intended in the latest version.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

atom --verison
Atom : 1.19.5
Electron: 1.6.9
Chrome : 56.0.2924.87
Node : 7.4.0

OS
Windows 10 Pro 32 bit

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!  This seems like something that's been reported before but I didn't quite find an issue for it.  I can reproduce this behavior with 1.19.5 on Windows 10 but see that on macOS 10.12.6 and Ubuntu 16.04, multiple files under the same project open in the same window when opened from Finder and Files respectively.

I'll tag as a bug for now and ask the team to take a look.

**Comment by Ben3eeE** [comment]
@rsese I was thinking about https://github.com/atom/tabs/issues/257 when reading this issue. Maybe that's what you were remembering as well?

**Comment by rsese** [comment]
ahhhh right, the discussion later on in that thread, does seem pretty similar :+1:

I guess we can keep this issue open to extract the report about opening multiple files in quick succession (e.g. in that issue with `atom file1 && atom file2` and in this case, opening multiple selected files with Atom from Explorer) opening in multiple windows since that issue is about the uncaught error.

**Comment by bhaskarmac** [comment]
This is also happening with the single file opening from the context menu in the "File explorer". Details as follows:
atom --version
Atom : 1.20.0 ia32

OS
Windows 10 Pro 32 bit

@rsese Should I create a new issue or In this issue is fine?

**Comment by rsese** [comment]
> This is also happening with the single file opening from the context menu in the "File explorer".

Hmmm, your original report was that opening multiple files at once in Explorer opens in multiple windows, can you clarify what you mean here when opening a single file?

**Comment by bhaskarmac** [comment]
I mean, Opening a single file from context menu also opening different Atom instance.

**Comment by rsese** [comment]
Thanks for clarifying, no need to open a new issue for that behavior - I think it falls under  this higher level issue we have about the different ways to start Atom /cc https://github.com/atom/atom/issues/10517.

**Comment by damieng** [comment]
The previous issue is at https://github.com/atom/atom/issues/13570

**Comment by damieng** [comment]
As per the other issue this is a limitation of the way the Windows shell works. An alternative workaround is available at that issue that adds Atom to the "Send to" menu which works in an alternative way.
