### ISSUE TITLE
Revert buffer / Revert to saved / Refresh from source

### ISSUE THREAD

**Issue by skylize** [atom/atom#15586]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[`revert-buffer` package](https://github.com/atom/revert-buffer/issues/3) should be rolled into core.  This package has zero documentation and appears to not be maintained. 

The functionality provided by this tiny package is just a single command to reset the buffered text to the content saved on disk. I am quite surprised this functionality is not already in core. We shouldn't need to install a package to do this. 

Atom should move this to core and make it available to various menus and deal with any open issues brought up on that package's repo.

### Steps to Reproduce

**Expected behavior:** 
Opening `File` menu or context clicking on a file in `Tree View` or typing `"revert` into `Command Palette` displays an option to revert file to it's saved state. `File` menu and `Command Palette` also displays the wisely selected default hotkey for this command.

**Actual behavior:** [What actually happens]
In order to revert file to saved, I must close and reopen the file or install the undocumented and poorly interfaced `revert-buffer` package.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Windows:    10
Atom    : 1.19.6
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python
git 2.12.0.windows.1
visual studio

### Additional Information

None

**Comment by maxbrunsfeld** [comment]
Great point. There is already an API for doing exactly this: [`TextBuffer::reload`](https://atom.io/docs/api/v1.19.7/TextBuffer#instance-reload).

**Comment by maxbrunsfeld** [comment]
Here's a quick solution. You can add this to your `~/.atom/init.js`:

```js
atom.commands.add('atom-text-editor', 'editor:reload', (event) =>
  event.target.closest('atom-text-editor').getModel().getBuffer().reload()
)
```

or, if you have an `init.coffee` rather than an `init.js`, add this:

```coffee
atom.commands.add 'atom-text-editor', 'editor:reload', (event) ->
  event.target.closest('atom-text-editor').getModel().getBuffer().reload()
```

Then you can use the `Editor: Reload` command from the Command Palette.

**Comment by skylize** [comment]
Thx @maxbrunsfeld for pointing that. Realizing there is an API already in place will hopefully allow someone to get on top of this more quickly.

I'll definitely use your init snippet. That seems cleaner to me than having yet another package installed for this tiny bit of code.

However, I think it's quite unfortunate that this (apparently already existing) feature should be limited to people willing and knowledgeable enough to edit their init script.

And that still does not make it available to any of the menu systems (File > Revert to Saved). I don't personally need it in the file menu because I am quite comfortable with the command palette for anything I don't remember a hotkey for. But new users and people who are just point-and-click by nature should be able to find this one.

**Comment by cronoklee** [comment]
Thanks for this post. Definitely should be native feature. 
I added this to my keymap.cson file today to bind F5 key to the reload function:

```
'atom-workspace':
    'f5':'editor:reload'
```

**Comment by crazymykl** [comment]
The lack of this feature can be annoying when switching branches.

**Comment by xgdgsc** [comment]
This should be the default behavior for modern editors/IDEs.

**Comment by Tejeev** [comment]
/open
Can we add this as a menu option and default keymap?  I find the lack of really jarring.

**Comment by chriskorosu** [comment]
Should be standard for every text editor 👀
