### ISSUE TITLE
[1.19.6/1.20.0-beta6] Block decorations mess up editor content when destroyed

### ISSUE THREAD

**Issue by lgeiger** [atom/atom#15582]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Block decorations mess up line numbers and editor content once destroyed.
The issue was originally reported by @srk-srinivasan on the Hydrogen repo: https://github.com/nteract/hydrogen/issues/981

This worked correctly till Atom 1.19.5 and 1.20.0-beta5.

### Steps to Reproduce

1. Open file with a few lines of code
2. Execute the following code in dev tools:
```js
function createBlock(row) {
  const item = document.createElement("span");
  item.innerText = "[block decoration]\n[block decoration]\n[block decoration]";
  const editor = atom.workspace.getActiveTextEditor();
  const marker = editor.markBufferPosition([row, 0]);
  editor.decorateMarker(marker, { type: "block", item: item });
  return marker;
}

const marker = createBlock(5);
```

3. Destroy marker with
```js
marker.destroy();
```

**Expected behavior: (Atom 1.19.5 / 1.20.0-beta5)**
Editor correctly renders as if the block decoration was never there.

**Actual behavior: (Atom 1.19.6 / 1.20.0-beta6)**
Editor doesn't correctly re-render and messes up line numbering and editor content:
![destroy](https://user-images.githubusercontent.com/13285808/30168951-3632efee-93eb-11e7-95f0-9df28a50a798.gif)

**Reproduces how often:** 100%

### Versions

Atom 1.19.6 and 1.20.0-beta6

### Additional Information

@as-cii This regression was likely introduced in #15503 or #15528

**Comment by Ben3eeE** [comment]
Thanks for the report 🙇 Adding it to the project board.

/cc: @as-cii

**Comment by as-cii** [comment]
Apologies for this regression and thanks for the report, @lgeiger. I have already provided a fix for it which will be included in the next hotfix releases.

**Comment by lgeiger** [comment]
Excellent, thanks for the fast fix @as-cii
