### ISSUE TITLE
"Symantec"'s "Norton Security Online" App Detects a "SONAR" Behavior in the Updating Process

### ISSUE THREAD

**Issue by dobrescumihai19** [atom/atom#15599]
### Prerequisites

* Reproduced the problem in Safe Mode:
http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

* Followed all applicable steps in the debugging guide:
http://flight-manual.atom.io/hacking-atom/sections/debugging/

* Checked the FAQs on the message board for common solutions:
https://discuss.atom.io/c/faq

* Checked that your issue isn't already filed:
https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom

* Checked that there is not already an Atom package that provides
the described functionality: https://atom.io/packages

### Description

Hi, "Atom.io" Team.
I apologize for the fact that I do not have time right now to check
whether this issue has already been reported or whether it is happening
all the time. Still, it has been bugging me and I feel the urge to report it.
1. I cannot find the "Atom.io" tile in the "Start Screen". I can find it
in the "Apps & features" list, but I cannot start it. "Cortana" does not find it
either - silly girl, she just finds the "Atomic Clock" app in the "Store".
The only workaround that I have found for this issue has been to pin
its tile to the task bar on the first run. This is not acceptable, but at least
I can start it. I prefer not to go and find the executable binary file.
2. The same issue described at (1) has also been previously happening
with the "GitHub Desktop" app, that initially was not to be found anywhere.
The workaround for it has been to go to the https://www.github.com/ web page
in the "Microsoft Edge" web browser and then to open a repository from it
by switching to the "GitHub Desktop" app.
However, this issue has been miraculously solved in the meantime
and the "GitHub Desktop" tile is now found by "Cortana", but it does not appear
in the "Start Screen" yet.
Even if I can start the "GitHub Desktop" app right now, still it does not
find the "Atom.io" editor, although I must have reinstalled it at least
two times already by now.
3. The updating system has a strange behavior. In order to install
the latest update (1.19.7 x64), I had to turn off "Symantec"'s "Norton Security
Online" app. It is reporting a "SONAR" behavior.

### Versions

"Microsoft Windows" Version 17603 (Operating System Build 15063.540) x64 © 2017

"GitHub Desktop" App Version 0.8.0

"Atom.io" Editor App Version 1.19.6 x64

**Comment by dobrescumihai19** [comment]
Note: I have managed to configure the behavior of the "F4" ("Edit") Key within GHISLER_Christian's "Total Commander" App in order to perform the `"C:\Users\Dobre\AppData\Local\Atom\Atom.EXE " "%1"` Command, which is a Great Success.

**Comment by rsese** [comment]
Thanks for taking the time to contribute!  It looks like you're reporting a couple of different things, in the future it would be helpful if you can open one issue per item you're reporting.

> > I cannot find the "Atom.io" tile in the "Start Screen". I can find it
> in the "Apps & features" list, but I cannot start it. "Cortana" does not find it
> either - silly girl, she just finds the "Atomic Clock" app in the "Store".
> The only workaround that I have found for this issue has been to pin
> its tile to the task bar on the first run. This is not acceptable, but at least
> I can start it. I prefer not to go and find the executable binary file.

This sounds like a duplicate of https://github.com/atom/atom/issues/14020 so you can subscribe there for updates if you'd like.

> The updating system has a strange behavior. In order to install
> the latest update (1.19.7 x64), I had to turn off "Symantec"'s "Norton Security
> Online" app. It is reporting a "SONAR" behavior.

This has been reported before as well:

https://github.com/atom/atom/issues/13234

As mentioned in that issue, you can report this to Symantec if it's not resolved after your next update. 

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by dobrescumihai19** [comment]
Hi, rsese.

    I guess then that the issue (2) should be reported to the Bug Tracker of the "_GitHub Desktop_" App?

    Does the Starting of the "_Atom.io_" Editor App from within the "_GitHub Desktop_" App have nothing to do with the current state of the "_Atom.io_" Editor App?

    I wonder.

    You have not commented anything yet about that.

**Comment by rsese** [comment]
> 2. The same issue described at (1) has also been previously happening
with the "GitHub Desktop" app, that initially was not to be found anywhere.
The workaround for it has been to go to the https://www.github.com/ web page
in the "Microsoft Edge" web browser and then to open a repository from it
by switching to the "GitHub Desktop" app.
However, this issue has been miraculously solved in the meantime
and the "GitHub Desktop" tile is now found by "Cortana", but it does not appear
in the "Start Screen" yet.
Even if I can start the "GitHub Desktop" app right now, still it does not
find the "Atom.io" editor, although I must have reinstalled it at least
two times already by now.

> > I guess then that the issue (2) should be reported to the Bug Tracker of the "GitHub Desktop" App?

Sorry, yes - if you're using the new Electron-based GitHub Desktop, you can report bugs in the repository issue tracker using their issue template if there isn't an existing issue already.

> Does the Starting of the "Atom.io" Editor App from within the "GitHub Desktop" App have nothing to do with the current state of the "Atom.io" Editor App?

I'm not sure, I've only briefly tried the new GitHub Desktop (I was able to open a repository in Atom via the `Repository > Open in Atom` menu item just now though) - if the Desktop folks think it's an Atom problem, feel free to let us know.
