### ISSUE TITLE
Warning: IntersectionObserver.observe(target): target element is not a descendant of root

### ISSUE THREAD

**Issue by caleb531** [atom/atom#15595]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

```
IntersectionObserver.observe(target): target element is not a descendant of root.
```

### Steps to Reproduce

1. Open the Chrome DevTools and look at the Console tab; the error will already be there

**Expected behavior:** I didn't expect

**Actual behavior:** [What actually happens]

**Reproduces how often:** Every time I open Atom, the error is there in the console; note that the console doesn't open on its own, but whenever I check the JS console, the warning is there:

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

macOS 10.12.6

**Comment by 50Wliu** [comment]
We decided not to fix this as the warning has already been removed in future versions of Chrome.
