### ISSUE TITLE
Atom 1.19.7 crashes on mac 10.10.2 when refocusing window.

### ISSUE THREAD

**Issue by annacrombie** [atom/atom#15592]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I downloaded atom for the first time on this computer yesterday and immediatley had this problem.  I have not installed any packages or modified any settings.  I did try reinstalling and nothing changed.

### Steps to Reproduce

1. Open Atom (behaves fine while in focus)
2. Focus a different application (e.g. Finder or Terminal)
3. Re-Focus Atom
4. Atom crashes in a fraction of a second

Reproduced with Atom, Atom in safe mode, and Atom Beta 1.20.0-beta7

**Expected behavior:** Atom to not crash when refocusing window

**Actual behavior:** Atom crashes when refocusing

**Reproduces how often:** 100%

### Versions

Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.6
git 2.5.4

### Additional Information
The crash log always contains this message:

```
Application Specific Information:
Crashing on exception: Invalid parameter not satisfying: (index >= 0) && (index < [_itemArray count])
```

**Comment by maxbrunsfeld** [comment]
Can you share the full crash log from `Console.app`?

**Comment by rsese** [comment]
Thanks for the report!  I wasn't able to reproduce with 1.19.7 on macOS 10.12.6 -  can you share any crash logs you find?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs

**Comment by annacrombie** [comment]
Sure, here is one of the logs.  All of the logs seem to be pretty similar, but I can post more if neccessary
[Atom_2017-09-07-202115_kro-bar.crash](https://gist.github.com/annacrombie/14feecf1ebba4ea0eb4ad87822624d7d)

**Comment by maxbrunsfeld** [comment]
Thanks @annacrombie, that's really useful.

**Comment by annacrombie** [comment]
Hey, I was playing around with atom some more and noticed that if I try to go to the Install Package tab of settings view, there is an Uncaught TypeError (Atom doesn't crash, I just cant see the install package view).  I was again able to reproduce it in Atom, safe mode Atom, and Atom 1.20.0-beta7.  Before I go and make another issue, I wonder if it is a related problem?
Here is the report it gave me:
[Enter steps to reproduce:]

1. Go to settings view
2. Click on install pacakge

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.10.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.250.0


### Stack Trace

Uncaught TypeError: packages[Symbol.iterator] is not a function

```
At /Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/install-panel.js:390

TypeError: packages[Symbol.iterator] is not a function
    at InstallPanel.addPackageViews (/Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/install-panel.js:390:30)
    at /Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/install-panel.js:461:26
    at /Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:68:26
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (/Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:160:22)
    at AtomIoClient.module.exports.AtomIoClient.featuredPackages (/Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/atom-io-client.js:65:25)
    at InstallPanel.loadFeaturedPackages (/Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/install-panel.js:455:27)
    at new InstallPanel (/Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/install-panel.js:128:16)
    at /Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:237:22
    at SettingsView.getOrCreatePanel (/Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:361:25)
    at SettingsView.showPanel (/Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:419:30)
    at HTMLDivElement.clickHandler (/Users/lattis/downloads/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/settings-view.js:186:24)
```

### Commands

```
     -0:22.3.0 settings-view:open (summary.welcome-summary.icon.icon-paintcan)
```

### Non-Core Packages

```

```

**Comment by annacrombie** [comment]
Another update, for some reason the package install works now, although Atom is still crashing on refocus.  Also, I completely uninstalled Atom and installed Atom 1.18.0, and everything works fine.  I guess that means that the problem was caused by something that changed in the update.

**Comment by rsese** [comment]
> Hey, I was playing around with atom some more and noticed that if I try to go to the Install Package tab of settings view, there is an Uncaught TypeError (Atom doesn't crash, I just cant see the install package view). I was again able to reproduce it in Atom, safe mode Atom, and Atom 1.20.0-beta7. Before I go and make another issue, I wonder if it is a related problem?
...
> Another update, for some reason the package install works now,

Glad package install is working ok for you again - the error that you shared with the package view was reported in another issue with no mention of crashing so  I don't think it's related to the focus crash that you've been seeing?  

https://github.com/atom/settings-view/issues/962

But if you run into it again, feel free to subscribe to that issue if you'd like.

> Also, I completely uninstalled Atom and installed Atom 1.18.0, and everything works fine. I guess that means that the problem was caused by something that changed in the update.

Awesome, thanks for doing that check, it's helpful to know that you don't see the error in 1.18.0 :+1:

**Comment by maxbrunsfeld** [comment]
@annacrombie Are you using the Mac app [MenuAndDockless](https://www.macupdate.com/app/mac/36314/menuanddockless)?

**Comment by annacrombie** [comment]
Yes I am

**Comment by iolsen** [comment]
Closing the loop here: this is an Electron bug, but a low priority one because it's caused by a third-party app injecting itself into Window management.

Closing the issue because it won't be addressed in the scope of Atom.

**Comment by maxbrunsfeld** [comment]
Yeah @annacrombie, I believe `MenuAndDockless` is causing this crash.

**Comment by annacrombie** [comment]
I see, thats a bummer because I really like auto-hiding my menubar...  Well Atom 1.18 has been working fine for me so far, so its not the most pressing issue for me.  Should I create an issue on Electron, or is it already made?

**Comment by maxbrunsfeld** [comment]
@annacrombie That would be great if you'd open an issue there. Thank you, and sorry for the poor experience!
