### ISSUE TITLE
Graphical glitches after 1.19.5 update

### ISSUE THREAD

**Issue by valorloff** [atom/atom#15601]
Hi!
after 1.19.5-7 updates on Ubuntu 16.04 LTS,
any mousing over sidebar or scrollbar is accompanied by glitches, moreover, search bar becomes unavailable:
![Graphical glitches](https://user-images.githubusercontent.com/19503975/30247337-a646c4aa-961a-11e7-92b6-8ae0e936064b.gif)

**Comment by 50Wliu** [comment]
At the current pace of development, this will be fixed in Atom 1.21.0.
