### ISSUE TITLE
Having two open atom instances with different ATOM_HOME causes the second instance to "share" partial state leading to unusual behavior in the secondary instance.

### ISSUE THREAD

**Issue by cstockton** [atom/atom#15605]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

ATOM_HOME environment variable is not respected when another atom editor is already open. The editors appear to share partial state that leads to unusual behavior within plugins.

### Steps to Reproduce

1. Create 2 fresh workspaces and ensure there are no atom processes
```bash
$ cd /tmp
$ mkdir /tmp/ws{1,2}
$ ls ws*
> ws1:
> ws2:
$ ps --forest -o cmd -C atom
>   CMD
```

2. Start and close each atom process in sequence, being certain to not run concurrently. Just to get a good baseline.

```bash
$ export ATOM_HOME=/tmp/ws1
$ atom
$ ps --forest -o pid,cmd -C atom
> CMD
> /bin/bash /usr/bin/atom
>  \_ /usr/share/atom/atom --executed-from=/tmp --pid=12766
>      \_ /usr/share/atom/atom --type=zygote --no-sandbox
>      |   \_ /usr/share/atom/atom --type=renderer --enable-experimental-web-platform-features --no-sandbox --primordial-pipe-token=
>      |       \_ /usr/share/atom/atom /usr/share/atom/resources/app/src/task-bootstrap.js /tmp/ws1/compile-cache /usr/share/atom/re
>      \_ /usr/share/atom/atom --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,23,71 --gpu
$ # (close atom editor)
$ export ATOM_HOME=/tmp/ws2 
$ atom
$ ps --forest -o pid,cmd -C atom
> CMD
> /bin/bash /usr/bin/atom
>  \_ /usr/share/atom/atom --executed-from=/tmp --pid=13456
>      \_ /usr/share/atom/atom --type=zygote --no-sandbox
>      |   \_ /usr/share/atom/atom --type=renderer --enable-experimental-web-platform-features --no-sandbox --primordial-pipe-token=
>      |       \_ /usr/share/atom/atom /usr/share/atom/resources/app/src/task-bootstrap.js /tmp/ws2/compile-cache /usr/share/atom/re
>     \_ /usr/share/atom/atom --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,23,71 --gpu
$ # (close second atom editor)
$ ls ws*
> ws1:
> compile-cache  config.cson  github.cson  nohup.out  storage
>
> ws2:
> compile-cache  config.cson  github.cson  nohup.out  storage
```

3. Open **ws1** all by itself and install "linter", then close it I can run  **ws2** and get no prompts to install Linter dependencies nor do I see "linter" in my "installed" packages.

4. Open **ws1** and minimize it.
5. Open **ws2** and begin getting a "prompt" to install linter dependencies, though it does not show up in installed packages. 

**Expected behavior:** [What you expect to happen]

Two completely independent editors with no plugins appearing in the second workspace. I am not sure if that is the intent of ATOM_HOME- but it has worked well for me since I first started using item (around it's release). I don't often (if ever) have two different workspaces open at the same time so I am not sure if this behavior was added in a recent version or always existed. At the very least I don't want it to break my second workspace, but I'm not sure if that is possible without all plugins being separate.

**Actual behavior:** [What actually happens]

The editors do not operate under independent HOME directories. What exactly merges between the two systems is not entirely clear to me from testing. Here for example we saw the "Linter" base package appears in **workspace#1** installed packages and the dependency prompt successfully installs the ui dependency. In **workspace#2** however it does not show under "installed" packages, though a prompt comes up to install Linter dependencies. Once dependencies are installed it still does not show under "installed" packages which is rather confusing.

The behavior gets much more unpredictable when you have two workspaces that are very different, for example I have a "work" workspace that uses different plugin versions (or missing some plugins all together) than my "home" workspace. If I open the second workspace without closing my "home" workspace .. the erorrs and prompts begin. Complains about config keys, it tries to install "missing" plugin dependencies and seems to have "broken" the "secondary" workspace entirely as it seems the config was mutated (upgraded perhaps by out of date plugins?) simply by opening it. An example of the biggest nuisance here would be `go-plus` which is not installed on my "work" workspace beginning to try install a bunch of binaries to my $GOPATH of my "work" workspace despite the plugin not being installed when ran independently.

Most important note: **Restoring both workspaces to initial state and opening each one in sequence with the proper *ATOM_HOME* and related env vars (at most 1 open at a time) each editor works perfectly and I can switch back and forth from the same terminal with no issues.**

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```bash
$ atom --version
Atom    : 1.19.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
$ uname -a
Linux cws 4.11.0-13-generic #19~16.04.1-Ubuntu SMP Wed Aug 2 20:06:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Additional Information

I attempted to find a related ATOM_HOME bug but nothing that was about this specific issue.

**Comment by rsese** [comment]
> I attempted to find a related ATOM_HOME bug but nothing that was about this specific issue.

Thanks for searching for an existing issue :+1:  I feel like I've seen an issue for this before but couldn't find a super specific one - this open pull request seems like it might address this issue?

**Comment by cstockton** [comment]
@rsese Did you mean to link me to a pull request? I could test it if you show me which one.

**Comment by rsese** [comment]
Ugh sorry, second time I've done that recently - I was trying to link to this PR:

https://github.com/atom/atom/pull/15081

I didn't particularly mention it so you can test it (it still needs review from the maintainers), I mainly wanted to let you know that there's an existing PR if you want to subscribe.

**Comment by cstockton** [comment]
Closing this issue since it's being worked on in another.
