### ISSUE TITLE
Flaky test: TextEditorComponent rendering resizes based on the content when the autoHeight and/or autoWidth options are true

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#15611]
Failed on AppVeyor in [build 8068](https://ci.appveyor.com/project/Atom/atom/build/8068/job/dw1qlwh66rx955cm) and then passed after re-running it in [build 8070](https://ci.appveyor.com/project/Atom/atom/build/8070).

![atom_-_appveyor](https://user-images.githubusercontent.com/2988/30279599-ae90f722-96db-11e7-81da-68233b059512.png)

```
TextEditorComponent
  rendering
    it resizes based on the content when the autoHeight and/or autoWidth options are true
      Expected false to be true.
        at it (C:\projects\atom\spec\text-editor-component-spec.js:716:47)
      Expected 808 to be 825.
        at it (C:\projects\atom\spec\text-editor-component-spec.js:717:35)

Finished in 529.611 seconds
1845 tests, 7290 assertions, 2 failures, 6 skipped
Command exited with code 1
```

**Comment by iolsen** [comment]
Recent flake on Appveyor: https://ci.appveyor.com/project/Atom/atom/build/8183/job/vdc4lxi8da4evc7w
