### ISSUE TITLE
Filebrowser should open in current workspace

### ISSUE THREAD

**Issue by goldsborough** [atom/atom#15614]
This is a feature request. Currently, when creating a new file, the file browser points to where it was last opened. When switching between projects, this is extremely unintuitive and takes time to move around in the browser. You should change it such that opening a new file points the file browser to the directory of the current project.

I'm on version 1.19.0 on macOS 10.12.6.

**Comment by rsese** [comment]
> Currently, when creating a new file, the file browser points to where it was last opened.

Just to clarify, do you mean the dialog that pops up when you try to save the new file?

**Comment by goldsborough** [comment]
Yes. I assume this is a macOS thing and nothing you're doing, but maybe you can specify the starting directory when opening the dialog to be the current project or something.

**Comment by rsese** [comment]
Ahh great thanks for confirming - that was reported before /cc https://github.com/atom/atom/issues/14732 and a fix should be in an upcoming release.

**Comment by Akumetsu-Dev** [comment]
linux too.
