### ISSUE TITLE
Wrong curly bracket color

### ISSUE THREAD

**Issue by umpirsky** [atom/atom#15624]
### Description

Open `{` is gray, `}` is yellow.

![screenshot from 2017-09-12 21-01-21](https://user-images.githubusercontent.com/208957/30343509-2326efec-97fe-11e7-8c64-8eec0d2e397b.png)

### Steps to Reproduce

1. Open any PHP file (e.g. https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php)

**Expected behavior:** Both brackets to be of same color.

**Actual behavior:** See description.

**Reproduces how often:** Always.

### Versions

```
atom-beta --version
Atom    : 1.21.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
```
```
cat /etc/issue
Ubuntu 16.04.3 LTS \n \l
```

**Comment by 50Wliu** [comment]
This has already been fixed in atom/language-php#257, but hasn't been released yet.  Working on it now.

**Comment by umpirsky** [comment]
@50Wliu When can we expect beta1?

**Comment by 50Wliu** [comment]
I can't commit to a release date to avoid false expectations when something gets delayed internally.  I know this is an annoying bug, but please bear with us :).

**Comment by umpirsky** [comment]
@50Wliu Just installed `1.21.0-beta1`, still same issue.

**Comment by 50Wliu** [comment]
@umpirsky That's odd, other people who have tried out the beta have reported it being fixed.  Can you please share a new screenshot?

**Comment by umpirsky** [comment]
@50Wliu Sure:

![screenshot from 2017-09-20 18-57-42](https://user-images.githubusercontent.com/208957/30656815-9f3f215c-9e35-11e7-8731-fbf0334639a9.png)

**Comment by 50Wliu** [comment]
Ok, thanks.  This is an issue with One Dark Syntax - I think it's highlighting anything with `.class` in it as yellow, even if it's punctuation (that opening bracket is scoped `punctuation.definition.class.begin.bracket.curly.php`).  The issue where the bracket colors would be mismatched has been fixed, however.

**Comment by umpirsky** [comment]
@50Wliu OK, should we report it somewhere?

**Comment by umpirsky** [comment]
Reported in https://github.com/atom/one-dark-syntax/issues/101, no response yet.

**Comment by 50Wliu** [comment]
simurai's on extended vacation, so expect to have to wait a while.
