### ISSUE TITLE
Update Atom from macOS fails

### ISSUE THREAD

**Issue by drorata** [atom/atom#15636]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Unable to update Atom from within the application using the squirrel icon.
 
### Steps to Reproduce

1. Open Atom
2. Notice that the blue squirrel appeared
3. Clicked on it, opening the `About` tab
4. It says that a new version is ready
5. Click on `Restart and install`

**Expected behavior:** Atom should close, updated and reopen

**Actual behavior:** Atom closes and then nothing.

**Reproduces how often:** Always.

### Versions

```
# atom --version
Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
# apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 3.6.2
git 2.13.4
```

Running on macOS 10.12.6

### Additional Information

As suggested by @lee-dohm in https://github.com/atom/atom/issues/13804#issuecomment-328403955 I followed the instruction on [FAQ](https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054).

These two directories are set OK:

- `/Applications/Atom.app/`
- `~/Library/Caches/com.github.atom.ShipIt`

However, this one: `~/Library/Application Support/com.github.atom.ShipIt` doesn't exists on my machine.

**Comment by kevinvdburgt** [comment]
I have the same problem, checked the permissions as well and also missing the `~/Library/Application Support/com.github.atom.ShipIt` directory.

```
➜  ~ whoami
kevin
➜  ~ stat -f "%Su" /Applications/Atom.app
kevin
➜  ~ stat -f "%Su" ~/Library/Caches/com.github.atom.ShipIt
kevin
➜  ~ stat -f "%Su" ~/Library/Application Support/com.github.atom.ShipIt
stat: /Users/kevin/Library/Application: stat: No such file or directory
stat: Support/com.github.atom.ShipIt: stat: No such file or directory
```

**Comment by drorata** [comment]
@kevinvdburgt Is it a permanent solution?

**Comment by kevinvdburgt** [comment]
@drorata I am not really sure, when I tried it on a second machine I had the same problem. After running it with `atom -f -d` it was on version 1.20.

**Comment by drorata** [comment]
I just tried it, `atom -f -d` (current version 1.19.7) and nothing happened. Clicking `Restart and install` exited Atom and that's it. Note however, that in the output in the console, I did see:

```
2017-09-15 08:20:06.608 Atom[27802:1823018] Download completed to: file:///Users/username/Library/Caches/com.github.atom.ShipIt/update.h1ZHTp6/atom-mac.zip
```

**Comment by kevinvdburgt** [comment]
If i remember correctly i also created the folder `/Users/kevin/Library/Application Support/com.github.atom.ShipIt` on my machine.

**Comment by drorata** [comment]
One one machine it worked out now (without creating new directory). However, it took couple of minutes!!! So maybe the solution is patience?

**Comment by Chewsterchew** [comment]
We've had this since #2230, I've been watching that for a while and I'm pretty sure I found a decent fix. I only tested it twice though, so I'm hoping I can try it again soon.

**Comment by drorata** [comment]
Well, the solution is not patience (maybe much more of it is needed...)

I just had the same problem when trying to update from 1.20.0 to 1.20.1.

**Comment by ourcore** [comment]
I experience issues updating most versions on macOS. Atom either shows the "Restart and Install" button, which does nothing, or it closes, but doesn't restart. Often, I have to manually restart Atom. Not sure if running multiple instances at once has any bearing on this, but it gets really annoying

**Comment by Chewsterchew** [comment]
It took me 3 tries of clicking Restart and Install until it finally worked.

**Comment by zhouyu1993** [comment]
To use [flag](https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054), I fix the problem.

**Comment by kevinvdburgt** [comment]
@zhouyu1993 that is what I tried as well, however, there was a non-existing directory:

```bash
➜  ~ stat -f "%Su" ~/Library/Application\ Support/com.github.atom.ShipIt
stat: /Users/kevin/Library/Application Support/com.github.atom.ShipIt: stat: No such file or directory
```

**Comment by lee-dohm** [comment]
I can't reproduce this issue using Atom v1.19.7 on Mac OS X 10.12.6. Here's what I tried:

1. Execute `mv ~/Library/Application\ Support/com.github.atom.ShipIt ~/Library/Application\ Support/com.github.atom.ShipIt-backup`
1. Download Atom v1.19.7 from https://github.com/atom/atom/releases
1. Unzip Atom v1.19.7 by clicking the `atom-mac.zip` file in my `~/Downloads` directory
1. Install Atom v1.19.7 by dragging `Atom.app` to the `/Applications` folder
1. Launch Atom v 1.19.7 from the terminal using `atom .` in my local Atom repository
1. Wait for the blue squirrel to show up
1. Click the blue squirrel
1. Click "Restart and install" button on the About screen

**Expected and Actual:** Atom shuts down and a short time later (less than a minute I believe, though I didn't time it) starts up running Atom v1.20.1

I also retried the above sequence after deleting the backup directory just in case. I believe that the Squirrel framework no longer uses `~/Library/Application Support/com.github.atom.ShipIt` and uses the `Caches` directory since the files in the directory I moved and then deleted hadn't been updated in over a year.

In any case, it isn't the fact that `~/Library/Application Support/com.github.atom.ShipIt` does not exist that is causing this issue. We'll need more information from people experiencing this problem to help track it down.

**Comment by drorata** [comment]
@lee-dohm In my case (having 1.20.0 installed) I don't have the directory `~/Library/Application\ Support/com.github.atom.ShipIt` at all. Thus, I cannot even start follow your steps.

**Comment by lee-dohm** [comment]
@drorata The point of the steps was to show that I get the expected behavior even without having a `~/Library/Application Support/com.github.atom.ShipIt` directory. So if you get something other than the expected behavior, it is not caused by the non-existence of the directory and I'll need to know more about what is different about your machine or configuration.

**Comment by drorata** [comment]
This works on one machine and on the other it doesn't. On the one it doesn't work, I have 1.20.0 installed. 

- I closed all tabs/projects/panes/etc. I qui
- I quit Atom
- Restarted Atom.
- Squirrel turned blue
- Clicked on the squirrel
- Clicked on "Restart and install"
- Atom closed
- NOTHING HAPPENS.

After ~2 minutes I manually opened Atom. I got no errors, no warnings no nothing. The squirrel was still there mentioning I can upgrade to 1.20.1

**Comment by zhouyu1993** [comment]
why not to mkdir ~/Library/Application Support/com.github.atom.ShipIt ?

**Comment by drorata** [comment]
@zhouyu1993 This didn't help.

However, I noticed, that after I re-open Atom manually (after it closes after clicking on the "restart and install"), it has to download the update again.

**Comment by lee-dohm** [comment]
@drorata I don't need the repro steps again. I understand what actions you're taking that reproduce the problem on your machine. I need to know what is different between the two machines, the one that works and the other than doesn't.

**Comment by tatwater** [comment]
For what it's worth I also use the Hyper terminal (also an Electron app as I understand it), which released an update recently and it too is stuck in a restart-to-update loop of no success.

**Comment by drorata** [comment]
@lee-dohm I would love to assist on this front. However, I don't really know what to look for. Could you send me a list of items you need and I could check them on both boxes.

**Comment by lee-dohm** [comment]
The only list I have is the one in the FAQ that's already been mentioned.
Other than that, I don't know what to look for either.

**Comment by drorata** [comment]
So @lee-dohm go wild. Ask me anything! I would love to help here. Maybe some debug mode and share logs?

**Comment by drorata** [comment]
(For some other reason) I looked at my `/var/log/system.log` and found the following:

```
Oct  4 10:09:32 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt[11609]): Service could not initialize: 16G29: xpcproxy + 11769 [1505][1E2A2740-D4E5-342E-A502-4792BD02598D]: 0xd
Oct  4 10:09:32 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Oct  4 10:09:34 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt[11610]): Service could not initialize: 16G29: xpcproxy + 11769 [1505][1E2A2740-D4E5-342E-A502-4792BD02598D]: 0xd
Oct  4 10:09:34 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Oct  4 10:09:37 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt[11611]): Service could not initialize: 16G29: xpcproxy + 11769 [1505][1E2A2740-D4E5-342E-A502-4792BD02598D]: 0xd
Oct  4 10:09:37 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Oct  4 10:09:39 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt[11612]): Service could not initialize: 16G29: xpcproxy + 11769 [1505][1E2A2740-D4E5-342E-A502-4792BD02598D]: 0xd
Oct  4 10:09:39 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Oct  4 10:09:41 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt[11613]): Service could not initialize: 16G29: xpcproxy + 11769 [1505][1E2A2740-D4E5-342E-A502-4792BD02598D]: 0xd
Oct  4 10:09:41 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Oct  4 10:09:43 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt[11614]): Service could not initialize: 16G29: xpcproxy + 11769 [1505][1E2A2740-D4E5-342E-A502-4792BD02598D]: 0xd
Oct  4 10:09:43 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Oct  4 10:09:45 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt[11617]): Service could not initialize: 16G29: xpcproxy + 11769 [1505][1E2A2740-D4E5-342E-A502-4792BD02598D]: 0xd
Oct  4 10:09:45 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
Oct  4 10:09:47 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt[11618]): Service could not initialize: 16G29: xpcproxy + 11769 [1505][1E2A2740-D4E5-342E-A502-4792BD02598D]: 0xd
Oct  4 10:09:47 hypercube com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
```

The log is pretty much packed by these messages. My guts feeling tells me it is somehow related to the issue. I have no idea how, let alone how to fix it.

**Comment by lee-dohm** [comment]
Can you find anything in logs other than `/var/log/system.log` that contains `ShipIt`? You can use the search function in Console.app. (If that's how you found these, I apologize for being too obvious.) Do you have anything in `~/Library/Caches/com.github.atom.ShipIt/ShipIt_stderr.log`?

**Comment by drorata** [comment]
After I noticed these error messages, I looked again into `~/Library/Caches/com.github.atom.ShipIt`. I noticed that even though the directory itself has `username:staff` ownership, inside it the two log files `ShipIt_stderr.log` and `ShipIt_stdout.log` were owned by `root`. Changing the owner of these file to `username` seems be a solution. Since then, the log doesn't contain the error messages I posted in my last post.

**Comment by lee-dohm** [comment]
Can you upgrade properly now?

**Comment by drorata** [comment]
I will check it once a new version is released and the Squirrel turns blue.

**Comment by lee-dohm** [comment]
You could also install [an older version](https://github.com/atom/atom/releases) and then let it update.

**Comment by drorata** [comment]
Problem seems to be solved. I would suggest to stress in the [FAQ](https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054) that the files in the directories should have the right settings as well.

**Comment by gudatcomputers** [comment]
Can confirm this was an issue updating from a fresh install of 1.21 to 1.23.  Same root cause.  Those log files weren't owned by my user.  `chown`ing them to me fixed it

**Comment by chimit** [comment]
The problem still takes place.

Steps described [here](https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054) returns my account. Only the last folder does't exist:
```
stat -f "%Su" ~/Library/Application Support/com.github.atom.ShipIt
stat: /Users/chimit/Library/Application: stat: No such file or directory
stat: Support/com.github.atom.ShipIt: stat: No such file or directory
```
