### ISSUE TITLE
Icons/images are distorted when starting Atom from the command line

### ISSUE THREAD

**Issue by scholtzm** [atom/atom#15634]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Seems like *some* images/icons are distorted when starting Atom via command line. This started happening after update to v1.19. I'm currently at v1.20 and it's still happening.

Atom started from command line using `atom .` command:

<img width="682" alt="screen shot 2017-09-13 at 09 42 45" src="https://user-images.githubusercontent.com/2640934/30365670-c0a4f63c-9868-11e7-849f-485a7a2696a4.png">

Atom started from Spotlight:

<img width="681" alt="screen shot 2017-09-13 at 09 43 35" src="https://user-images.githubusercontent.com/2640934/30365680-c6078748-9868-11e7-8e74-3843f40ac701.png">

(Markdown preview at the top, find and replace panel at the bottom.)

### Steps to Reproduce

1. Start Atom from command line.

**Expected behavior:** Icons to look 👌 

**Actual behavior:** Icons look like 💩 

**Reproduces how often:** 100%

### Versions

```
> atom --version
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

> apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.1
```

`macOS Sierra 10.12.6`

### Additional Information

This issue from VSCode repo might be relevant: https://github.com/Microsoft/vscode/issues/28345

**Comment by scholtzm** [comment]
This is no longer happening in v1.20.1. 🤔 

cc @50Wliu

**Comment by scholtzm** [comment]
Never mind, still happening.

**Comment by jasonrudolph** [comment]
@scholtzm: Are you still able to reproduce this issue? If so, can you point to a specific file I can open to see the problematic icons?

**Comment by scholtzm** [comment]
Seems like this is not an issue anymore.
