### ISSUE TITLE
Windows Install Shortcuts and File Associations

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [atom/atom#15644]
http://flight-manual.atom.io/getting-started/sections/installing-atom/

"This setup program will install Atom, add the atom and apm commands to your PATH, create shortcuts on the desktop and in the start menu, add an "Open with Atom" context menu in the Explorer and make Atom available for association with files using "Open with..."."

This is not happening.

**Comment by serafeimgr** [comment]
Hello, have a look at the System Settings.

Setting -> System

![image](https://user-images.githubusercontent.com/17761449/30444888-197d71c4-998d-11e7-90da-a092d71c68b9.png)

**Comment by Ben3eeE** [comment]
Thanks @serafeimgr 🙇 

@RefinedSoftwareLLC Thank you for the report 🙇 Can you reopen this on the [flight-manual.atom.io](https://github.com/atom/flight-manual.atom.io/issues/) repository and also mention in the new issue that the Settings -> System panel is not documented in the install instructions.
