### ISSUE TITLE
disk and path is missing the "\" separator for network mounted drives on Win7

### ISSUE THREAD

**Issue by petrdanecek** [atom/atom#15640]
### Description
Atom path returned by:
`atom.workspace.getActiveTextEditor().getPath()`
is missing separator `\` between disk and directory.

### Steps to Reproduce
1. Export some disk by Samba etc.
2. Mount the network drive to windows.
3. Open the file from mounted drive by Atom.
4. Open Developer tools console and run:
`atom.workspace.getActiveTextEditor().getPath()`

**Expected behavior:** [What you expect to happen]
The valid file path should be returned: 
`"N:\frontend\Templates\TemplatesList.jsx"`

**Actual behavior:** [What actually happens]
The actual path returned is missing `\` separator between DiskDrive and Directory:
`"N:frontend\Templates\TemplatesList.jsx"`

### Versions
Windows 7 x64
Atom version: 1.20.0-beta7

### Additional Information
Originally the problem was experienced for linter-eslint and reported here:
https://github.com/AtomLinter/linter-eslint/issues/1011

The same is not observed for local drives.

I'm observing some other issues like unable to rename/delete files.

**Comment by petrdanecek** [comment]
Hmm I did some troubleshooting and it seems to be related to restoring of project folder after Atom restart. Let me note that I wiped whole Atom, downloaded the latest 1.21.0-beta x64(atom-x64-windows.zip). I used vanila install as it was unpacked so no plugins, no customization.

1. Add new project folder CTRL+SHIFT+A => added  my N:\ network drive.
2. Open some JSX file
3. Open Developer Tools CTRL+SHIFT+I
3. Run atom.workspace.getActiveTextEditor().getPath() = > Got VALID PATH

4. Restart Atom
5. Project folder and files are restored - however the tree view is missing colorization of some files (seems to be like git differences are signed this way, not sure)
6. Developer Tool - CTRL+SHIFT+I  => atom.workspace.getActiveTextEditor().getPath() => PATH is VALID
7. Close the file Restored
8. Open the same file from TreeView
9. Developer Tool - CTRL+SHIFT+I => atom.workspace.getActiveTextEditor().getPath() => INVALID PATH
10. Remove Project folder, remove all opened files and start with step 1. All reoccurred same way.


So it seems that TreeView somehow broke the path once it is restored after Atom restart. All files opened after the TreeView restore are getting corrupted path.

**Comment by 50Wliu** [comment]
This is partly due to Node's decision of treating disk drives without a trailing path separator as referring to the cwd on that disk drive, rather than the root of the disk drive (which is technically correct, but not what is needed in practice 99% of the time).

**Comment by petrdanecek** [comment]
hmm but why the behavior is different for adding new project folder and auto-restoring session after startup? I would expect that Node is consistent. I mean the CWD provides the same disk/path for both cases.
Can I provide more details or help with troubleshooting somehow? Just let me know what is needed.

Thanks

**Comment by petrdanecek** [comment]
New observation on latest 1.22.0-beta1.
Atom is unable to recover the Project Folder after start. So I'm adding the project folder manually after any Atom start/restart. The difference is after the project folder is added. Once it is added, all works fine.

**Comment by jachee** [comment]
I'm still seeing this behavior with 1.23.3 x64. 

Interestingly, opening the \\server\path\to\folder path directly restores correctly, so that's been my work-around.

**Comment by petrdanecek** [comment]
I moved to VScode...

**Comment by petrdanecek** [comment]
I moved to VScode...

**Comment by danielocdh** [comment]
I can reproduce on windows 10 with ubuntu network drive.
