### ISSUE TITLE
Menu dropdowns in Themes panel aren't aligned

### ISSUE THREAD

**Issue by andrewmccullough** [atom/atom#15641]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The drop downs to choose the UI and Syntax themes in the Themes panel in Settings are misaligned when the window is below a certain width. See attached screenshots.

**Normal alignment**
![screen shot 2017-09-13 at 2 53 38 pm](https://user-images.githubusercontent.com/6857304/30395311-b63701ba-9893-11e7-8790-ce870127d2c8.png)

**Wrong alignment**
![screen shot 2017-09-13 at 2 53 56 pm](https://user-images.githubusercontent.com/6857304/30395312-b6391f9a-9893-11e7-84ef-a79fec715ca3.png)

### Steps to Reproduce

1. Open the Themes panel in Settings.
2. Shrink the window to less than approximately 1260 pixels wide.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

Atom 1.20.0
Electron 1.6.9
Chrome 56.0.2924.87
Node 7.4.0
MacOS 10.12.6

**Comment by 50Wliu** [comment]
Yikes!  @andrewmccullough could you please reopen this on the [atom/settings-view](https://github.com/atom/settings-view) repo?  Thanks so much :bow:.
