### ISSUE TITLE
error with apm package installation from cmd windows 10

### ISSUE THREAD

**Issue by xmen1412** [atom/atom#15650]
i would want to install https://atom.io/packages/autocomplete-python via apm with command prompt windows 10. when i  write it there's problem like this.

![probelm](https://user-images.githubusercontent.com/29954788/30416029-c9458350-9954-11e7-8379-1d517c889a26.PNG)

**Comment by serafeimgr** [comment]
Maybe you are behind a firewall?

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/apm if there's no existing issue already so we have it in the right place?  Please fill out the issue template as well and let us know if there's anything interesting about your network setup like if you're behind a proxy/firewall (thanks @serafeimgr :v:).
