### ISSUE TITLE
Git diff view shows "File has no contents" for modified files

### ISSUE THREAD

**Issue by jackfranklin** [atom/atom#15651]
Firstly, thank you for such an amazing project - I've just swapped to Atom and other than this issue it's been a great experience :)

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using Atom and viewing a modified file in Git, the editor always shows "File has no contents". It correctly shows for new files but not for deleted or modified files.

I have tried with Atom Beta and Atom both in and out of safe mode. The project I am working in has a `.git` folder in the root.

### Steps to Reproduce

1. Open a git based project in Atom.
2. Edit an existing file.
3. Bring up the git pane.
4. Click on a modified file to view it.

**Expected behavior:** The editor shows the git diff.

**Actual behavior:** The editor shows "File has no contents" (see screenshot)

**Reproduces how often:** 100% of the time, across two machines. I have never been able to get this to work.

<img width="1142" alt="screen shot 2017-09-14 at 09 22 59" src="https://user-images.githubusercontent.com/193238/30419660-1d28004a-992f-11e7-936e-1bea731537db.png">

### Versions

```
atom --version
  Atom    : 1.20.0
  Electron: 1.6.9
  Chrome  : 56.0.2924.87
  Node    : 7.4.0

apm --version            
  apm  1.18.4
  npm  3.10.10
  node 6.9.5 x64
  python 2.7.13
  git 2.13.4
```

I am on OS X 10.12.6. I have also tried a completely fresh install.

**Comment by jackfranklin** [comment]
I also opened the dev tools and noticed that when I click on a modified file I get this error:

```
Expected "* Unmerged path ", "diff ", "diff --cc ", or end of input but "\x1B" found."
name
:
"SyntaxError"
```

```
"SyntaxError: Expected "* Unmerged path ", "diff ", "diff --cc ", or end of input but "\x1B" found.
    at peg$buildStructuredError (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/what-the-diff/lib/parser.js:381:18)
    at Object.peg$parse [as parse] (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/what-the-diff/lib/parser.js:1942:17)
    at parse (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/what-the-diff/index.js:6:27)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/github/lib/git-shell-out-strategy.js:615:49
    at Generator.next (<anonymous>)
    at step (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/github/lib/git-shell-out-strategy.js:92:197)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/github/lib/git-shell-out-strategy.js:92:367
    at process._tickCallback (internal/process/next_tick.js:103:7)"
```

**Comment by jackfranklin** [comment]
I solved it! I found this issue in `atom/github`: https://github.com/atom/github/issues/977

I had `ui = always` under the `color` part of my `gitconfig`. Deleting that fixes it. I hope this saves someone else time if they have this problem.

**Comment by jgn-epp** [comment]
Isn't this still an issue, even though you found a solution? Does not sound like intended behavior.

**Comment by jackfranklin** [comment]
I closed it because I think the issue that is open and tracking it is the one in atom/github (which in hindsight is where I should have opened this in the first place). That's why I closed this - for people searching for the same issue they will still find the solution + a link to the canonical issue.

**Comment by jgn-epp** [comment]
I just realized that the reason for my Atom showing "File has no contents" is not due to the same error. When I open the console, what I'm seeing is:
"Unable to find item at path [path/of/file] with staging status unstaged"
Does anybody have an idea what is causing it?

**Comment by joadr** [comment]
@jgn-epp I'm having the same issue :(

**Comment by the-j0k3r** [comment]
I dont get why this bug issue is closed when its not fixed and its still broken.

**Comment by jgn-epp** [comment]
@the-j0k3r I think it's because there was also another issue open with this cause of the error. The reason I'm getting "File has no contents" in the git diff pane, is because the repo I'm working in contains spaces in the path.

**Comment by the-j0k3r** [comment]
Yes, I made a report there too but people are still commenting here and the open bug is ignored.

**Comment by Ben3eeE** [comment]
Hi Epp ❤️ 

https://github.com/atom/github/pull/1217 will fix the spaces in the path issue.

**Comment by the-j0k3r** [comment]
@Ben3eeE Excellent, thank you for the heads up, and I hope it will be merged and backported asap.
