### ISSUE TITLE
Failed to load XYZ - try again later.

### ISSUE THREAD

**Issue by alexmironof** [atom/atom#15662]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm behind a corporate firewall and using this settings inside `.atom/.apmrc` file:

```
proxy=http://user:password@host:port/
https-proxy=http://user:password@host:port/
strict-ssl=false
```

### Steps to Reproduce

1. Set up a proxy with self-signed certificate
2. Install clean version of latest atom
3. Go to "Install +" setting and click on any community package

**Expected behavior:**

View package description

**Actual behavior:**

Getting error: `Failed to load XYZ - try again later.`

**Reproduces how often:**

Every community package

### Versions

`atom --version`

```
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

`apm --version`

```
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.1.windows.1
```

`cmd /K ver`

```
Microsoft Windows [Version 6.1.7601]
```

### Additional Information

If I hit `CTRL+SHIFT+F5` on package description page, info message appears: `Loading XYZ...`
and then I get package description.

After I loaded it this way, I also get description of this package after restarting Atom

Also in Developers tools pane inside Network tab when I click on package in packag list I can't see any activity, it appears only when I hit refresh window keybinding

**Comment by guilhermep** [comment]
Hi, I was able to reproduce your issue but I believe it belongs in the [settings-view](https://github.com/atom/settings-view) repository.

**Comment by alexmironof** [comment]
I guess this error was gone
