### ISSUE TITLE
Add Project Folder Keyboard Shortcut Misbehaving

### ISSUE THREAD

**Issue by celestialorb** [atom/atom#15660]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using Atom on Windows 10, the Add Project Folder keyboard shortcut (Ctrl+Shift+A) does not respond to the first use of the shortcut, but will respond to the second use.  Once a project folder has been added via this method any other action taken afterward will prompt it to trigger once again, causing a major annoyance.

### Steps to Reproduce

1. Open Atom
2. Use the Add Project Folder keyboard shortcut once (Ctrl+Shift+A).
3. Open the Command Palette with a keyboard shortcut, Ctrl+Shift+P.

**Expected behavior:** The Add Project Folder dialog window should appear after the first instance of the keyboard shortcut, but it does not until the Command Palette keyboard shortcut is triggered.

**Actual behavior:** Add Project Folder dialog window only appears after another keyboard shortcut is used.

**Reproduces how often:** 100%

### Versions

Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.1
visual studio 2015

### Additional Information

I always run Atom in full-screen mode.  Doesn't seem to make a difference, but thought it might be helpful.

**Comment by 50Wliu** [comment]
What does the Keybinding Resolver (<kbd>Ctrl</kbd>+<kbd>.</kbd>) say when you use the Ctrl+Shift+A shortcut?

**Comment by celestialorb** [comment]
Looks like it was triggering shortcuts in the Git Plus package.  Git Plus had several shortcuts starting with Ctrl+Shift+A.  I removed those keymappings and Atom behaves as expected now.  Thanks!
