### ISSUE TITLE
DOMException: Failed to execute 'transaction' on 'IDBDatabase'

### ISSUE THREAD

**Issue by andrew-davis** [atom/atom#15663]
I just installed Atom on a Win 7 machine. And basic functionality is broken for me. For instance, when I try to open a file nothing happens. I use the menu bar at the top and click on 'open file' and select a file - but then nothing happens. Same thing with clicking on 'settings' in the file menu. I tried booting Atom into safe mode and it still happens.

I opened the dev tool and each time I make a click that results in nothing an error appears. This is it:

Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Promise (C:\Users\andrewd\AppData\Local\atom\app-1.20.0\resources\app\src\state-store.js:62:32)
    at dbPromise.then (C:\Users\andrewd\AppData\Local\atom\app-1.20.0\resources\app\src\state-store.js:61:20)

![image](https://user-images.githubusercontent.com/12276420/30504314-e1ba0036-9a22-11e7-80af-18c8d0921d1a.png)

I'm not sure what is going on or what other info is needed here to help debug. Thoughts? Thanks.
-Andrew

**Comment by jonzielen** [comment]
The same thing is happening to me.

**Comment by andrew-davis** [comment]
Sorry I missed this the first time. I did do all these steps. I don't know if this issue is posted in the right spot though. Thanks everyone.

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

**Comment by rsese** [comment]
Can you try clearing saved state?  Though it seems like you haven't gotten to the point where you can make changes in Atom, note that you'll lose any unsaved data:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by andrew-davis** [comment]
Thanks for your help. I tried starting Atom from command line with the --clear-window-state switch. The issue is still the same. I also tried renaming the settings folder so Atom would have to create a new one. It did create a new folder, but the issues persisted.

**Comment by rsese** [comment]
On Windows 7 do you have a folder called `C:\Users\USERNAME\AppData\Roaming\Atom`?

**Comment by andrew-davis** [comment]
Nope. There is no atom folder inside `C:\Users\USERNAME\AppData\Roaming`. Is there supposed to be?

I do have this folder `C:\Users\USERNAME\.atom`.

**Comment by rsese** [comment]
Hmm, that's where it is on Windows 10 - I don't have Windows 7 to check right now but I though it  be the same on Windows 7?  

So you do have a `C:\Users\USERNAME\AppData\Roaming` directory, just no Atom subdirectory?

> I do have this folder C:\Users\USERNAME\.atom.

That folder is where your settings and packages are stored, the folder we're looking for (and that I think is related to the error you're seeing?) is where project specific details like what tabs you had opened are stored.

I'll try to setup a Windows 7 VM to see if I can reproduce.

**Comment by andrew-davis** [comment]
Correct. I have a `C:\Users\USERNAME\AppData\Roaming` directory. But there is no Atom subdirectory inside of that.

I did some digging and I found `C:\Users\USERNAME\AppData\Local\atom`. Which has subdirectories like 'packages', 'bin', and 'app-1.20.1' and more. Is this what we are looking for?

**Comment by rsese** [comment]
> I did some digging and I found C:\Users\USERNAME\AppData\Local\atom. Which has subdirectories like 'packages', 'bin', and 'app-1.20.1' and more. Is this what we are looking for?

That's where the application itself lives, I don't believe that's where IndexedDB is (the folder we're looking for based on the error) - at least on Windows 10, it's in `C:\Users\USERNAME\AppData\Roaming`.  Hopefully I can setup a Windows 7 vm tomorrow or this weekend so I can install Atom on it and see where everything is.

To double check one more thing, when you quit Atom, there are no atom processes running in Task Manager yes?

**Comment by andrew-davis** [comment]
Correct. After quitting the Atom application, no Atom processes are visible in the task manager.

**Comment by rsese** [comment]
> Correct. After quitting the Atom application, no Atom processes are visible in the task manager.

Thanks for confirming - I finally had a chance to install a Windows 7 VM and there was an Atom subdirectory created under `C:\Users\USERNAME\AppData\Roaming` after starting Atom, I'm not sure why you don't have that folder.

Can you uninstall Atom and then download the latest version from https://atom.io and try installing again?

**Comment by andrew-davis** [comment]
I've already done that a couple times. Is there any way to debug the install process? See if there are any warnings or errors or anything?

**Comment by andrew-davis** [comment]
Uninstalled and reinstalled again. Still no Atom folder in `C:\Users\USERNAME\AppData\Roaming`. But I do see `C:\Users\USERNAME\.atom`.

**Comment by rsese** [comment]
> Never mind, I found it. It's located at \\NETWORK\Redirected\USERNAME\Application Data\Atom. Our work computers are configured with a redirected user folder.

Oh interesting, thanks for digging into that :+1:

> This is breaking Atom and GitHub Desktop too. What are my options? Can I force Atom to use C:\Users\USERNAME\AppData\Roaming instead?

I think this might work (at least it did from my testing) - can you quit Atom and then in `C:\Users\USERNAME\.atom` create a folder called `electronUserData`?  Then restart Atom and see if you still get the same error in dev tools.

**Comment by andrew-davis** [comment]
Yes! That seems to be working! Seems to be behaving as expected now. Any pitfalls to be aware of using this workaround?

**Comment by rsese** [comment]
Awesome!  Glad we have things sorted out - as far as I know, creating that directory under `.atom` only changes the location where Electron user data is stored but won't do anything else so I don't see how that would cause any issues.  But definitely feel free to let us know if you notice anything odd and we can take a look again.  

And thanks again for your patience :v:
