### ISSUE TITLE
coffeescript syntax highlighting broke

### ISSUE THREAD

**Issue by Inve1951** [atom/atom#15671]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since a few days coffeescript syntax highlighting broke in that it renders comments as code and regexes as comments and removes it alltogether in other parts.

### Steps to Reproduce

1. unknown

**Expected behavior:** old behaviour - correct syntax highlighting

**Actual behavior:** ![screenshot](https://i.imgur.com/eNflOex.png)

**Reproduces how often:** always for longer files

### Versions

```
>atom -v
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

>apm -v
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.8.1.windows.1
visual studio 2015

>coffee -v
CoffeeScript version 2.0.0-beta5

>systeminfo
Microsoft Windows 7 Professional
6.1.7601 Service Pack 1 Build 7601
```

### Additional Information

Had the idea it might be due to having coffeescript@2.0.0-beta5 installed which preserves single line comments but switching back to an older version and restarting atom didn't fix it. Having keywords in comments changes the outcome but it's broken either way.

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/language-coffee-script if there's no existing issue already so we have it in the right place?
