### ISSUE TITLE
Atom launchs as browser window, not as redactor.

### ISSUE THREAD

**Issue by evolcon** [atom/atom#15672]
Hi, i have a little broblem. I installed Atom from atom.io, and the redactor is launching as browser window. Whats problem?
![default](https://user-images.githubusercontent.com/17050686/30520681-a3b25d98-9bbb-11e7-868c-9a1ddcb0ca90.png)

**Comment by VACASh** [comment]
Try CTRL + SHIFT + I

**Comment by 50Wliu** [comment]
There is a fatal error preventing Atom from starting properly.  Please focus the `Console` tab and paste the error here.

**Comment by evolcon** [comment]
![default](https://user-images.githubusercontent.com/17050686/30522955-07ce2a62-9be1-11e7-92cf-4e268e9bcc74.png)

**Comment by evolcon** [comment]
Tried reinstalling, but it didn't help.

**Comment by 50Wliu** [comment]
What happens if you rename your `%USERPROFILE%\.atom` folder to `.atom-backup.`?

**Comment by evolcon** [comment]
Yea, that works! Thank u so much!

**Comment by 50Wliu** [comment]
Awesome!  You can safely delete `.atom-backup` then if you don't need anything from it.
