### ISSUE TITLE
When starting as a snap, it's impossible to drop back into the shell

### ISSUE THREAD

**Issue by NeoTheThird** [atom/atom#15673]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using the deb package on Ubuntu 16.04 to start atom in a project folder by running `atom .`, i can drop back into the terminal to continue working in the directory. This is not possible using the snap package, which can break the work-flow for developers who use the terminal a lot.

### Steps to Reproduce

1. Use Ubuntu 16.04
2. Run `sudo snap install atom`
3. Navigate to your project folder
4. Run `atom .`

**Expected behavior:** [What you expect to happen]

Atom starts in the project folder and i can continue to use the terminal window to work with `git` and other command line tools.

**Actual behavior:** [What actually happens]

Atom starts in the project folder and outputs debugging information in the terminal. It's impossible to use the same terminal window to continue working.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

- Atom: 1.20.0
- Electron: 1.6.9
- Chrome: 56.0.2924.87
- Node: 7.4.0

- Ubuntu 16.04.3 LTS

### Additional Information

The behavior only occurs when using the snap package.

**Comment by rsese** [comment]
> When using the deb package on Ubuntu 16.04 to start atom in a project folder by running atom ., i can drop back into the terminal to continue working in the directory. This is not possible using the snap package

Thanks for reaching out!

We've determined that this issue is being caused by the use of an unofficial build or distribution of Atom.  You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

I've seen some community members mention success using the snap install in the official message board so someone there might be able to help:

https://discuss.atom.io/

**Comment by NeoTheThird** [comment]
Hm, ok. Thanks anyways and keep up the good work.
