### ISSUE TITLE
"The repository for X:\ is not open in Atom." Git Unstaged Changes Tab Error

### ISSUE THREAD

**Issue by RankWinner** [atom/atom#15680]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Clicking to view unstaged changes in the git panel just opens a blank window with the error "This repository for D:\ is not open in Atom", this happens for every project I've tried it on.

### Steps to Reproduce

1. Open project in Atom
2. Expand git panel, click on unstaged change
3. The "Unstaged Changes" tab only says "The repository for D:\ is not open in Atom.", or with C:\ instead of D:\.

**Expected behavior:** Show file changes. This used to work but recently broke.

**Reproduces how often:** 100%

### Versions

Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 3.6.0
git 2.12.1.windows.1
visual studio

Running Windows 10 1073

### Additional Information

Atom correctly knows which files have been changed and it shows the right colours for changed/removed/new lines too.

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/github if there's no existing issue already so we have it in the right place?
