### ISSUE TITLE
Editor crash while debugging after doing a step over

### ISSUE THREAD

**Issue by segevfiner** [atom/atom#15688]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashes once I stop on a break point and click step over.

![virtualbox_linux mint 18 2_19_09_2017_12_17_23](https://user-images.githubusercontent.com/24731903/30585532-d78cee64-9d35-11e7-861c-fd7594527674.png)

This happened while trying to debug https://github.com/atom/symbols-view/pull/229.

Might be dependent on external factors such as the operating system and VirtualBox to reproduce this.

I'm seeing this in dmesg:
```
[ 1284.229480] traps: atom[4986] trap invalid opcode ip:1816b25 sp:7ffcbaabe390 error:0
[ 1284.229484]  in atom[400000+49ce000]
```

Disassembly: (Can't tell what function that is, binary is stripped)
```
 1816b12:       e8 89 fc 51 00          callq  1d367a0 <_ZSt9make_heapIN9__gnu_cxx17__normal_iteratorIPiSt6vectorIiSaIiEEEEEvT_S7_@@Base+0x6430>
 1816b17:       48 83 c4 50             add    $0x50,%rsp
 1816b1b:       e9 6e fd ff ff          jmpq   181688e <_ZSt22__final_insertion_sortIPiEvT_S1_@@Base+0x9934e>
 1816b20:       e8 9b 42 d8 fe          callq  59adc0 <__stack_chk_fail@plt>
 1816b25:       0f 0b                   ud2    
 1816b27:       90                      nop
 1816b28:       90                      nop
 1816b29:       90                      nop
 1816b2a:       90                      nop
```

Sadly Atom doesn't give me any more info on how to collect additional information about this.

### Steps to Reproduce

1. Run Package Specs on https://github.com/atom/symbols-view/pull/229.
2. Open the Dev Tools and set a breakpoint on `symbols-view.js:193`.
3. Reload Specs.
4. Press Step Over.
5. Crash ☹️.

**Expected behavior:** Step over.

**Actual behavior:** Editor Crash.

**Reproduces how often:** 100%

### Versions
```
Linux 18.2 Cinnamon x64 (Ubuntu 16.04 Based) Running in VirtualBox 5.1.28 under Windows 10.0.15063 x64

Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.14.1
```

**Comment by 50Wliu** [comment]
This is a known issue with the version of Electron that Atom is currently using.  It should be resolved when we switch to Electron 1.7+.

**Comment by segevfiner** [comment]
Are there any plans to upgrade electron? It's really quite annoying being unable to debug... ☹️ (The last electron upgrade took quite a while before it was done...)

**Comment by 50Wliu** [comment]
Atom running Electron 1.7 crashes on launch (except when run in dev mode).  So there is unfortunately a lot of work that will need to be done to get it running properly.  There are (loose) plans to start working on the Electron upgrade in the next month or two.
