### ISSUE TITLE
1.20.0: Popup jump when using macOS Chinese IME

### ISSUE THREAD

**Issue by xionglun** [atom/atom#15696]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
The popup panel will jump from top left corner to the bottom of current line when using Chinese pinyin IME(includes macOS built-in and squirrel and others).

It should keep under the bottom of current line.

### Steps to Reproduce
1. Open Atom (1.20.0)
2. Choose a Chinese IME
3. Try to input something

![image](https://user-images.githubusercontent.com/5624870/30604864-ef5eee4e-9d20-11e7-8ace-8d6ad21e8558.gif)

You can see more [here](https://github.com/atom/atom/issues/14911#issuecomment-330604185) and [here](https://github.com/atom/atom/issues/14911#issuecomment-330606144)

**Expected behavior:** The popup should keep under current line, not jump from top left corner.

**Actual behavior:** The popup jump from top left corner when try to type something.

**Reproduces how often:** Every time

### Versions
Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.1

### Additional Information
This issue has already discussed [here](https://github.com/atom/atom/issues/14911#issuecomment-330472422)

**Comment by ungb** [comment]
Also seeing this with Google japanese IME layout:  https://www.google.co.jp/ime/.  With this keyboard layout it never jumps to center and stays on top 

![image](https://user-images.githubusercontent.com/5624870/30718224-1ef755d8-9ed4-11e7-8a28-9e9e929bfb4c.png)

**Comment by akabekobeko** [comment]
IME also popups to the top-left in my environment. Initial input will be below the text but fixed from the second popup to the top-left.

My environment:

* IME : [Google Japanese Input](https://www.google.co.jp/ime/)
* OS: macOS High Sierra

Pop-up to the correct position in [vscode](https://github.com/Microsoft/vscode) even in the same environment. Since vscode is made of Electron as well as Atom, it may be a hint of correction.

**Comment by ungb** [comment]
I was able to verify that this is now fixed in Electron upgrade to 1.7.10 that is currently still in a PR 

see https://github.com/atom/atom/pull/16282.  This will be fixed once this hits beta and then stable.
