### ISSUE TITLE
Reopening of tabs from last session not working when relaunching Atom 1.19.6 on Ubuntu 16.04 X64

### ISSUE THREAD

**Issue by ckaldemeyer** [atom/atom#15697]
### Description

The re-opening/restoring of tabs as described in https://github.com/atom/atom/pull/9968, https://github.com/atom/atom/issues/1603 and https://github.com/atom/atom/issues/3665#issuecomment-57355820 is not working.

"Preferences>Open Emty Editor on Start" is set to "deactivated"
"Preferences>Restore Previous Windows On Start" is set to "always"

### Steps to Reproduce

1.) Open Atom 1.19.6 on Ubuntu 16.04 X64 from the unity launcher of terminal.
2.) Add a project folder, leave some tabs open, and close Atom via "File>Quit" or clicking on X.
3.) Reopen Atom by double-clicking a file associated with it, outside any project.

**Expected behavior:**

Opening the tabs opened in the last session.

**Actual behavior:**

Atom completely forgets what was last open, and launches with a single window open to double-clicked file's folder, with single tab for the double-clicked file.

**Reproduces how often:**

Always

### Versions

Atom    : 1.19.6
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by rsese** [comment]
I'm unable to reproduce on Ubuntu 16.04 and Atom 1.20.1 - can you share a screencast or GIF that demonstrates the behavior?  And just to check the other setting, does `yes` for `Preferences > Restore Previous Windows On Start` also not work for you or is it just `always`?

**Comment by ckaldemeyer** [comment]
> I'm unable to reproduce on Ubuntu 16.04 and Atom 1.20.1 - can you share a screencast or GIF that demonstrates the behavior? And just to check the other setting, does yes for Preferences > Restore Previous Windows On Start also not work for you or is it just always?

I have updated to your version, checked the preferences and it is still not working..

See this screencast: https://www.dropbox.com/s/gczuv2sg0bkbi38/atom-problem-tabs.mp4?dl=0

**Comment by ckaldemeyer** [comment]
Just to clarify: I have removed (apt-get purge) the old version before instaling 1.20.1 and deleted the folder .atom in my home folder to get rid of old preferences. So it should be a vanilla installation..

**Comment by rsese** [comment]
Hmmm, do you see any message in the Console tab of Dev Tools when you start Atom?

**Comment by ckaldemeyer** [comment]
<embedded>:18567 Could not connect to indexedDB Event
    dbOpenRequest.onerror @ <embedded>:18567

Nothing else.

**Comment by rsese** [comment]
Ahhh I wonder if that might be the issue, I ran into something similar on the message board:

https://discuss.atom.io/t/atom-needs-root-access-to-remember-my-session/41223/21?u=rsese

Can you share the output of these commands?

```
ls -l ~/.config/Atom
ls -l ~/.config/Atom/IndexedDB
```

**Comment by ckaldemeyer** [comment]
cord@cord-Laptop:~$ ls -l ~/.config/Atom
    insgesamt 48
    drwx------ 3 cord cord  4096 Sep 25 13:46 Cache
    -rw-r--r-- 1 cord cord  7168 Sep 25 13:47 Cookies
    -rw-r--r-- 1 cord cord     0 Sep 25 13:47 Cookies-journal
    drwx------ 2 cord cord  4096 Mär 10  2017 databases
    drwx------ 2 cord cord  4096 Mär 10  2017 GPUCache
    drwx------ 3 cord cord  4096 Mär 10  2017 IndexedDB
    drwx------ 2 cord cord  4096 Mär 15  2017 Local Storage
    -rw------- 1 cord cord   640 Sep 26 09:15 Preferences
    -rw-r--r-- 1 cord cord 15360 Mär 28 22:55 QuotaManager
    -rw-r--r-- 1 cord cord     0 Mär 28 22:55 QuotaManager-journal
    cord@cord-Laptop:~$ ls -l ~/.config/Atom/IndexedDB
    insgesamt 4
    drwx------ 2 cord cord 4096 Sep 26 10:17 file__0.indexeddb.leveldb
    cord@cord-Laptop:~$ 

Thanks!

**Comment by ckaldemeyer** [comment]
Your suggestion in the other repository fixed the problem:

> Can you try renaming it so it gets re-created when you restart Atom?
>    mv ~/.config/Atom/IndexedDB ~/.config/Atom/IndexedDB.tmp

Perfect ;-) Thanks a lot!
