### ISSUE TITLE
Uncaught Error: Access is denied./\?\~\AppData\Local\atom\app-1.20.1\resources\app\node_modules...

### ISSUE THREAD

**Issue by DennisDurairaj** [atom/atom#15707]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Access is denied.
\\?\C:\Users\Misie\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

```
At ELECTRON_ASAR.js:173

Error: Access is denied.
\\?\C:\Users\Misie\AppData\Local\atom\app-1.20.1\resources\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at get_KeyboardLayoutManager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:7:65)
    at get_manager (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:16:42)
    at getCurrentKeyboardLayout (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:32:17)
    at Object.getCurrentKeymap (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/keyboard-layout/lib/keyboard-layout.js:22:31)
    at exports.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/helpers.js:244:66)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.20.1/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
angularjs 0.4.0 
atom-beautify 0.30.5 
autoclose-html 0.23.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
emmet 2.4.3 
git-control 0.9.0 
intentions 1.1.5 
language-babel 2.74.2 
language-javascript-jsx 0.3.7 
language-latex 1.1.1 
language-pug 0.0.21 
latex 0.47.0 
latex-completions 0.3.3 
linter 2.2.0 
linter-ui-default 1.6.10 
monokai-complete-syntax 2.0.1 
open-terminal-here 2.3.1 
pdf-view 0.59.0 
platformio-ide-terminal 2.6.0 
react 0.16.2 
seti-classic 0.10.3 
tree-view-git-status 1.4.0 
```

**Comment by TransWebT** [comment]
import React, { Component } from 'react';
import { render } from 'react-dom';
import AceEditor from '../src/ace.js';
import 'brace/mode/jsx';

const languages = [
  'javascript',
  'java',
  'python',
  'xml',
  'ruby',
  'sass',
  'markdown',
  'mysql',
  'json',
  'html',
  'handlebars',
  'golang',
  'csharp',
  'elixir',
  'typescript',
  'css'
]

const themes = [
  'monokai',
  'github',
  'tomorrow',
  'kuroir',
  'twilight',
  'xcode',
  'textmate',
  'solarized_dark',
  'solarized_light',
  'terminal',
]

languages.forEach((lang) => {
  require(`brace/mode/${lang}`)
  require(`brace/snippets/${lang}`)
})

themes.forEach((theme) => {
  require(`brace/theme/${theme}`)
})
/*eslint-disable no-alert, no-console */
import 'brace/ext/language_tools';
import 'brace/ext/searchbox';


const defaultValue =
`function onLoad(editor) {
  console.log(\"i\'ve loaded\");
}`;
class App extends Component {
  onLoad() {
    console.log('i\'ve loaded');
  }
  onChange(newValue) {
    console.log('change', newValue);
    this.setState({
      value: newValue
    })
  }

  onSelectionChange(newValue, event) {
    console.log('select-change', newValue);
    console.log('select-change-event', event);
  }

  onValidate(annotations) {
    console.log('onValidate', annotations);
  }

  setTheme(e) {
    this.setState({
      theme: e.target.value
    })
  }
  setMode(e) {
    this.setState({
      mode: e.target.value
    })
  }
  setBoolean(name, value) {
    this.setState({
      [name]: value
    })
  }
  setFontSize(e) {
    this.setState({
      fontSize: parseInt(e.target.value,10)
    })
  }
  constructor(props) {
    super(props);
    this.state = {
      value: defaultValue,
      theme: 'monokai',
      mode: 'javascript',
      enableBasicAutocompletion: false,
      enableLiveAutocompletion: false,
      fontSize: 14,
      showGutter: true,
      showPrintMargin: true,
      highlightActiveLine: true,
      enableSnippets: false,
      showLineNumbers: true,
    };
    this.setTheme = this.setTheme.bind(this);
    this.setMode = this.setMode.bind(this);
    this.onChange = this.onChange.bind(this);
    this.setFontSize = this.setFontSize.bind(this);
    this.setBoolean = this.setBoolean.bind(this);
  }
  render() {
    return (
      <div className="columns">
        <div className="column">
           <div className="field">
             <label>
               Mode:
             </label>
               <p className="control">
                 <span className="select">
                   <select name="mode" onChange={this.setMode} value={this.state.mode}>
                     {languages.map((lang) => <option  key={lang} value={lang}>{lang}</option>)}
                   </select>
                  </span>
               </p>
           </div>

           <div className="field">
             <label>
               Theme:
             </label>
               <p className="control">
                 <span  className="select">
                   <select name="Theme" onChange={this.setTheme} value={this.state.theme}>
                    {themes.map((lang) => <option key={lang} value={lang}>{lang}</option>)}
                   </select></span>
               </p>
           </div>

           <div className="field">
             <label>
               Font Size:
             </label>
               <p className="control">
                 <span  className="select">
                   <select name="Font Size" onChange={this.setFontSize} value={this.state.fontSize}>
                    {[14,16,18,20,24,28,32,40].map((lang) => <option  key={lang} value={lang}>{lang}</option>)}
                   </select></span>
               </p>
           </div>
          <div className="field">
            <p className="control">
              <label className="checkbox">
                <input type="checkbox" checked={this.state.enableBasicAutocompletion} onChange={(e) => this.setBoolean('enableBasicAutocompletion', e.target.checked)} />
                 Enable Basic Autocomplete
              </label>
            </p>
          </div>
           <div className="field">
            <p className="control">
              <label className="checkbox">
                <input type="checkbox" checked={this.state.enableLiveAutocompletion} onChange={(e) => this.setBoolean('enableLiveAutocompletion', e.target.checked)} />
                 Enable Live Autocomplete
              </label>
            </p>
          </div>
           <div className="field">
            <p className="control">
              <label className="checkbox">
                <input type="checkbox" checked={this.state.showGutter} onChange={(e) => this.setBoolean('showGutter', e.target.checked)} />
                 Show Gutter
              </label>
            </p>
          </div>
           <div className="field">
            <p className="control">
              <label className="checkbox">
                <input type="checkbox" checked={this.state.showPrintMargin} onChange={(e) => this.setBoolean('showPrintMargin', e.target.checked)} />
                 Show Print Margin
              </label>
            </p>
          </div>
           <div className="field">
            <p className="control">
              <label className="checkbox">
                <input type="checkbox" checked={this.state.highlightActiveLine} onChange={(e) => this.setBoolean('highlightActiveLine', e.target.checked)} />
                 Highlight Active Line
              </label>
            </p>
          </div>
          <div className="field">
            <p className="control">
              <label className="checkbox">
                <input type="checkbox" checked={this.state.enableSnippets} onChange={(e) => this.setBoolean('enableSnippets', e.target.checked)} />
                 Enable Snippets
              </label>
            </p>
          </div>
          <div className="field">
            <p className="control">
              <label className="checkbox">
                <input type="checkbox" checked={this.state.showLineNumbers} onChange={(e) => this.setBoolean('showLineNumbers', e.target.checked)} />
                 Show Line Numbers
              </label>
            </p>
          </div>


      </div>
        <div className="examples column">
          <h2>Editor</h2>
          <AceEditor
          mode={this.state.mode}
          theme={this.state.theme}
          name="blah2"
          onLoad={this.onLoad}
          onChange={this.onChange}
          onSelectionChange={this.onSelectionChange}
          onValidate={this.onValidate}
          value={this.state.value}
          fontSize={this.state.fontSize}
          showPrintMargin={this.state.showPrintMargin}
          showGutter={this.state.showGutter}
          highlightActiveLine={this.state.highlightActiveLine}
          setOptions={{
            enableBasicAutocompletion: this.state.enableBasicAutocompletion,
            enableLiveAutocompletion: this.state.enableLiveAutocompletion,
            enableSnippets: this.state.enableSnippets,
            showLineNumbers: this.state.showLineNumbers,
            tabSize: 2,
          }}/>
      </div>
      <div className="column">
          <h2>Code</h2>
          <AceEditor
           mode="jsx"
           theme="monokai"
           readOnly={true}
           value={
            `<AceEditor
  mode="${this.state.mode}"
  theme="${this.state.theme}"
  name="blah2"
  onLoad={this.onLoad}
  onChange={this.onChange}
  fontSize={${this.state.fontSize}}
  showPrintMargin={${this.state.showPrintMargin}}
  showGutter={${this.state.showGutter}}
  highlightActiveLine={${this.state.highlightActiveLine}}
  value={\`${this.state.value}\`}
  setOptions={{
  enableBasicAutocompletion: ${this.state.enableBasicAutocompletion},
  enableLiveAutocompletion: ${this.state.enableLiveAutocompletion},
  enableSnippets: ${this.state.enableSnippets},
  showLineNumbers: ${this.state.showLineNumbers},
  tabSize: 2,
  }}/>
            `
          } />
      </div>
    </div>
    );
  }
}


render(
 <App />,
  document.getElementById('example')
);
