### ISSUE TITLE
Git Integration Orange Highlighting Broken

### ISSUE THREAD

**Issue by johndanek** [atom/atom#15703]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In the previous version of Atom, modifying a file would result in its tab and file in the highlighted orange until the next commit. In 1.20.1 x64 (macOS 10.12.6), modifying and saving a file results in it being highlighted orange for about .5 seconds, then reverting back to white.

### Steps to Reproduce

1. Open a file which has already been committed to git.
2. Modify the file and save it.
3. Watch as the tab and file in the Tree View turn orange briefly, then revert to white.

**Expected behavior:** The file tab and Tree View file should remain orange until the next git commit.

**Actual behavior:** It turns back to white. The issue doesn't also happen for new files, which stay green correctly.

**Reproduces how often:** 100%

### Versions

Atom 1.20.1 x64 with macOS 10.12.6

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/tree-view if there's no existing issue already so we have it in the right place?  If you can also let us know in the issue if you see this with any repository (e.g. a simple test repo) or just a particular repo, that could be helpful too.

As a side note, I was unable to reproduce on macOS 10.12.6 with Atom 1.22.0-dev-615b67b46.
