### ISSUE TITLE
Unable to push to GitHub

### ISSUE THREAD

**Issue by edvwib** [atom/atom#15701]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using the by default installed package "github" to push a commit to my repo i get the following error message:
Unable to push
Git credentials for https://github.com/edvwib/hello-world.git not found:
fork/exec C:/Users/[USER]/AppData/Local/Temp/github-117820-1760-1x4yd44.asem56ogvi/git-askpass-atom.sh: %1 is not a valid Win32 application.
error: failed to push some refs to 'https://github.com/edvwib/hello-world.git'

I'm able to pull and merge changes, but not pushing them.

### Steps to Reproduce

1. Open a cloned repo in Atom.
2. Make a change and try to push the commit.
3. Provide user/password and receive the message above

**Expected behavior:** [What you expect to happen]
Pushing the commit to the repository.

**Actual behavior:** [What actually happens]
Throws the error above.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time.

### Versions

Tested on both Windows 10 V.1709 Build 16288.1 and Windows 10 V.1703 Build 15063.608.
Works correctly on Atom 1.20.0. 64bit
Doesn't work on Atom 1.20.1 64bit or 1.21.0 Beta1 64bit.

atom --version
Atom    : 1.21.0-beta1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python
git 2.14.1.windows.1
visual studio

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/github if there's no existing issue already so we have it in the right place?

**Comment by matrix246** [comment]
Encountered the same problem and have not found the solution yet.

**Comment by edvwib** [comment]
I've opened a new issue [here](https://github.com/atom/github/issues/1184).

**Comment by ssp0929** [comment]
This seems to be a problem with git and not Atom, since I am encountering the same problem in Visual Studio Code.
