### ISSUE TITLE
atom.exe getting blocked by AV

### ISSUE THREAD

**Issue by aceecarig** [atom/atom#15711]
Our company's AV is blocking the software since it does not have a valid digital signature. Is it possible for the next released version to be signed? They are saying that it is a security risks without the digital signature and is asking us to look for an alternative software to use. 

### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
I'm not super familiar with code signing but I poked around a bit and see that according to https://github.com/atom/atom/issues/7635, the macOS and Windows builds are signed but the Linux releases are not.  So if you're asking about Linux, there's an existing request for that and you can subscribe to that issue if you'd like but otherwise, I think the macOS and Windows versions are signed.
