### ISSUE TITLE
Package user reviews

### ISSUE THREAD

**Issue by Progdrasil** [atom/atom#15710]
### Description

This is more of an enhancement request.
It would be nice to have a review system of packages, that way you can see the quality of the package other than just the number of times it was downloaded

**Comment by rsese** [comment]
Thanks for the suggestion!  I was almost positive I've seen this request before but couldn't find an issue - can you re-open this in https://github.com/atom/atom.io if there's no existing issue already so we have it in the right place?  I thinkkkkk that might be a better place for this request.

**Comment by Progdrasil** [comment]
okay
