### ISSUE TITLE
Install screen at small size and cannot be moved

### ISSUE THREAD

**Issue by thepeanutman98** [atom/atom#15724]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode 
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

During installation, the install screen appears at about 1/2 size and cannot be moved.

### Steps to Reproduce

1. Download Atom beta installer
2. Run installer
3. Accept Administrator permissions

**Expected behavior:** Appears at normal size and can be moved.

**Actual behavior:** Appears at 1/2 size and cannot be moved.

**Reproduces how often:** Unknown

### Versions

v1.21.0-beta1
Windows 7 SP2

### Additional Information

This is the image of my screen.
![image](https://user-images.githubusercontent.com/22580382/30755973-8b86ad58-9f96-11e7-8dbb-c5e9ef9570d3.png)
It is on a secondary screen (not primary) with resolution 1680x1050.

**Comment by 50Wliu** [comment]
This should be reported upstream to [Squirrel/Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows).  Thanks!

**Comment by damieng** [comment]
Caused by https://github.com/Squirrel/Squirrel.Windows/pull/1061
