### ISSUE TITLE
Highlight & Convert Indentation 

### ISSUE THREAD

**Issue by ruchitinfushion** [atom/atom#15726]
In sublimeText if you select indentation then it highlight spaces and tabs, plus you can convert indentation to spaces or tab.  (view->indentation) Which is very helpful for python dev. 

See this 
![tabs](https://user-images.githubusercontent.com/541597/30776114-6bd239cc-a0be-11e7-8880-daa625143eef.png)

![spaces](https://user-images.githubusercontent.com/541597/30776118-73a9ba08-a0be-11e7-8844-a9b7da93a762.png)

Can we get similar functionality inside Atom ??

**Comment by 50Wliu** [comment]
Displaying indentation when selected is being tracked at #12157.
Tabs conversion is handled by the [whitespace](https://github.com/atom/whitespace) package.
