### ISSUE TITLE
Only the last snippet listed works, the ones prior to it do not

### ISSUE THREAD

**Issue by captain-awesome** [atom/atom#15727]
Hello, I can only utilize the last snippet listed in my `snippets.cson` file.
A snippet as simple as:

```
'.text.plain':
  'foo':
    'prefix': 'foo'
    'body': 'foo foo foo'

'.text.plain':
  'bar':
    'prefix': 'bar'
    'body': 'bar bar bar'
```

Typing `foo` = no results
Typing `bar` = `bar bar bar`

---------------------------------------------

Now if I were to reverse the snippet order like so...

```
'.text.plain':
  'bar':
    'prefix': 'bar'
    'body': 'bar bar bar'

'.text.plain':
  'foo':
    'prefix': 'foo'
    'body': 'foo foo foo'
```
Typing `bar` = no results
Typing `foo` = `foo foo foo`

---------------------------------------------

Please note the following:

This still occurs in `atom --safe` mode
This occurs on two totally different systems:
```
Windows 10 64 - (using 32 bit version because 64 bit version fails to install)

Atom    : 1.13.1
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.14.1
npm  3.10.5
node 4.4.5
python
git 2.8.3.windows.1
visual studio 2010
```
---------------------------------------------
```
Windows 7 64 - Atom version 1.20.1 x64

Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python
git
visual studio
```

Please advise on how to resolve this.
Any help will greatly be appreciated.

**Comment by 50Wliu** [comment]
Please see the Flight Manual's entry on CSON: http://flight-manual.atom.io/using-atom/sections/basic-customization/#configuring-with-cson.  Your snippets file should be the following instead:
```cson
'.text.plain':
  'foo':
    'prefix': 'foo'
    'body': 'foo foo foo'

  'bar':
    'prefix': 'bar'
    'body': 'bar bar bar'
```

**Comment by captain-awesome** [comment]
wow that was fast!
thank you!
