### ISSUE TITLE
Ctrl-Tab deprecation warning with Untitled tabs in MRUListView

### ISSUE THREAD

**Issue by segevfiner** [atom/atom#15734]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom's Deprecation Cop shows deprecation warnings when using `Ctrl-Tab` when you have "Untitled" tabs open:
```
Argument to path.extname must be a string
Object.extname - /usr/share/atom/resources/app/src/electron-shims.js:20:10
DefaultFileIcons.iconClassForPath - /usr/share/atom/resources/app/node_modules/tabs/lib/default-file-icons.js:16:24
MRUItemView.initialize - /usr/share/atom/resources/app/node_modules/tabs/lib/mru-item-view.js:61:63
MRUListView.buildListView - /usr/share/atom/resources/app/node_modules/tabs/lib/mru-list-view.js:176:18
MRUListView.show - /usr/share/atom/resources/app/node_modules/tabs/lib/mru-list-view.js:99:36
MRUListView.choose - /usr/share/atom/resources/app/node_modules/tabs/lib/mru-list-view.js:87:12

Argument to path.extname must be a string
Object.extname - /usr/share/atom/resources/app/src/electron-shims.js:20:10
Proxy.isReadmePath - /usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:570:24
DefaultFileIcons.iconClassForPath - /usr/share/atom/resources/app/node_modules/tabs/lib/default-file-icons.js:19:21
MRUItemView.initialize - /usr/share/atom/resources/app/node_modules/tabs/lib/mru-item-view.js:61:63
MRUListView.buildListView - /usr/share/atom/resources/app/node_modules/tabs/lib/mru-list-view.js:176:18
MRUListView.show - /usr/share/atom/resources/app/node_modules/tabs/lib/mru-list-view.js:99:36

Arguments to path.basename must be strings
Object.basename - /usr/share/atom/resources/app/src/electron-shims.js:20:10
Proxy.isReadmePath - /usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:571:19
DefaultFileIcons.iconClassForPath - /usr/share/atom/resources/app/node_modules/tabs/lib/default-file-icons.js:19:21
MRUItemView.initialize - /usr/share/atom/resources/app/node_modules/tabs/lib/mru-item-view.js:61:63
MRUListView.buildListView - /usr/share/atom/resources/app/node_modules/tabs/lib/mru-list-view.js:176:18
MRUListView.show - /usr/share/atom/resources/app/node_modules/tabs/lib/mru-list-view.js:99:36
```

### Steps to Reproduce

1. Open an Atom Window with at least one "Untitled" tab.
2. Press `Ctrl-Tab`.

**Expected behavior:** No deprecation warnings.

**Actual behavior:** 3 deprecation warnings.

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
```
Ubuntu 16.04 x64

Atom    : 1.20.0
Electron: 1.6.9
Chrome. : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.11.0
```

**Comment by 50Wliu** [comment]
Unable to repro.  Atom 1.22.0-dev-f762bf954.

**Comment by 50Wliu** [comment]
Never mind.  Confirmed in safe mode.
