### ISSUE TITLE
[Python] Line, which starts from "elif" or "else" moves one indent level left

### ISSUE THREAD

**Issue by vlad1777d** [atom/atom#15730]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When line starts from "elif" or "else" keyword, has some indentation (I use tabs) and you add something to it, then it automatically moves to one indent level left.

### Steps to Reproduce

0. Maybe to check preferences to be consistent with myne. Also to use tab key (and tabs) for indentation.
1. Make some block with indentation
2. Add line with "if" on it; and it's block
3. Add line with "elif" or "else" and something into it. 
4. After you'll press ":", than this line will be moved to one indentation level left.
5. After this if you'll move this line to one indentation right - it'll be moved
6. If you'll try to change something on this line - it'll be moved to one indentation level left again.

**Expected behavior:** Nothing would be moved to one indentation level left
**Actual behavior:** Line is moved to one indentation level left

**Reproduces how often:** Always (or often)

### Versions

Atom    : 1.20.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.14rc1
git 2.14.1

OS: Debian Sid x64
Linux: 4.12.0-1-amd64

**Atom's preferences**:
____Editor tab:
________Auto Indent: True
________Auto Indent On Paste: True
________Soft Tabs: False
________Tab Type: Auto

### Additional Information

**Video** with reproduction of this bug on YouTube: https://youtu.be/I-b7O0y13Js
In 1.20.1 this error is present too.

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

This issue belongs in the [language-python](https://github.com/atom/language-python) repository. Can you reopen the issue in that repository if one does not already exist? Thank you :bowing_man:

**Comment by vlad1777d** [comment]
Thanks.
