### ISSUE TITLE
Sometimes  find-and-replace doesn't work when  use 'replace all' action

### ISSUE THREAD

**Issue by netmou** [atom/atom#15739]
![image](https://user-images.githubusercontent.com/7068058/30791521-92a2b4c8-a1e5-11e7-9f97-494903d3c1de.png)
I cut all  and paste ,then ok.
enc widnow10x64, atom v1.20.1

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/find-and-replace if there's no existing issue already so we have it in the right place?  If you can fill out the issue template in the new issue, that would be very helpful.
