### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by LiuJiJiJi** [atom/atom#15733]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:290:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:394:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
     -0:34 settings-view:uninstall-packages (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-ide-ui 0.3.3 
atom-maven 1.3.0 
autocomplete-java 1.2.7 
docblockr 0.11.0 
highlight-selected 0.13.1 
java-generator 2.2.3 
java-importer 1.4.1 
platformio-ide-terminal 2.6.0 
simplified-chinese-menu 5.3.4 
```

**Comment by rsese** [comment]
Thanks for the report! Can you confirm what were you doing at the time of the error and if it's reproducible?

**Comment by juanicondina** [comment]
Happened to me few moments ago, I'm currently using Manjaro Linux 17.0.5 and the error poped while browsing the themes

**Comment by rsese** [comment]
Was the error temporary @juanicondina?  And are you behind a proxy?

**Comment by irrigator** [comment]
@rsese I got the same error and I am behind a shadowsocks proxy.

**Comment by ERockZ** [comment]
This happens whenever I run Atom the first time after a reboot.
If I close and open Atom again the error doesn't pop up.
I am behind a proxy too.

**Comment by brucewayne521** [comment]
This happens too，when I try to update a package.
I am behind a shadowsocks proxy in windows 10 version 1803.
