### ISSUE TITLE
Unsigned Application Warning

### ISSUE THREAD

**Issue by tedivm** [atom/atom#15748]
When I downloaded the 1.20.1 version of Atom and attempted to install it over an existing install I got a warning from OSX saying that the application was unsigned. This is different from the "you downloaded this off the internet" warning- the actual code signing certificate itself was not trusted.

Downloading the app a second time got the appropriate installer which was properly signed.

Unfortunately I did not keep a copy of the original "unsigned" application for analysis (and yes, I'm regretting that), but I think you should spot check your download servers to make sure they are all pushing out the right application (and that a development version, or worse yet a malicious binary, were not being served).

**Comment by rsese** [comment]
Thanks for the heads up @tedivm, I'll close this issue for now (we can re-open if necessary) and I'll mention this to the team 👍
