### ISSUE TITLE
Heredocs not working correctly

### ISSUE THREAD

**Issue by akapa100** [atom/atom#15746]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Heredoc messes syntax and diagnostics gives errors

### Steps to Reproduce

1. Write heredoc PHP syntax

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime
### Versions
Atom    : 1.21.0-beta1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

When it's near the gutter it works as expected and syntax is right
![Works correctly](https://i.imgur.com/Sa5HD9J.png)

However as soon as you give an space from the gutter the syntax becomes all messed up and it gives errors from diagnostics
![Works correctly](https://i.imgur.com/J2J7W4A.png)

## Package list
advanced-open-file@0.16.6
angularjs@0.4.0
artisan@0.3.1
atom-alignment@0.13.0
atom-beautify@0.30.5
atom-ctags@5.1.0
atom-ide-ui@0.4.0
atom-material-syntax-dark@1.0.0
atom-typescript@11.0.9
autoclose-html@0.23.0
autocomplete-corona@1.1.4
autocomplete-modules@1.7.0
autocomplete-paths@2.11.0
blade-snippets@0.2.0
busy-signal@1.4.3
caniuse@0.9.2
color-picker@2.2.5
data-atom@0.25.2
docblockr@0.11.0
editorconfig@2.2.2
emmet@2.4.3
expose@0.14.0
file-icons@2.1.12
filesize@3.0.0
flex-tool-bar@0.12.0
flow-ide@1.8.1
git-plus@7.9.3
goto-definition@1.3.4
highlight-selected@0.13.1
Hydrogen@1.23.0
hydrogen-launcher@1.2.1
hyperclick@0.1.5
ide-flowtype@0.17.4
ide-php@0.6.8
ide-typescript@0.6.1
increment-selection@0.3.0
intentions@1.1.5
language-blade@0.36.0
language-htaccess@0.1.1
language-log@1.8.0
language-lua@0.9.11
language-puppet@0.23.0
language-vue@0.23.1
laravel@0.7.1
less-than-slash@0.17.0
linter@2.2.0
linter-coffeelint@1.3.1
linter-csslint@2.0.0
linter-erb@1.1.0
linter-jshint@3.1.6
linter-jsonlint@1.3.0
linter-lsc@2.4.0
linter-luacheck@2.0.1
linter-markdown@5.2.0
linter-php@1.5.1
linter-puppet-lint@0.8.3
linter-sass-lint@1.8.0
linter-scss-lint@3.1.1
linter-tidy@2.3.1
linter-ui-default@1.6.10
livestyle-atom@0.2.10
local-history@4.3.0
minimap@4.29.7
minimap-bookmarks@0.4.2
minimap-cursorline@0.2.0
minimap-find-and-replace@4.5.2
minimap-highlight-selected@4.6.1
minimap-linter@2.1.1
minimap-pigments@0.2.2
minimap-selection@4.5.0
minimap-split-diff@0.3.7
notifications-plus@0.69.8
package-cop@0.2.10
pdf-view@0.59.0
php-getters-setters@0.5.5
pigments@0.40.2
platformio-ide-terminal@2.7.0
project-manager@3.3.5
quick-highlight@0.10.0
regex-railroad-diagram@0.19.4
Remote-FTP@1.1.3
rest-client@1.3.1
simple-drag-drop-text@0.3.4
sort-lines@0.15.0
split-diff@1.5.1
swap-selection@0.4.0
symbols-tree-view@0.14.0
sync-settings@0.8.3
tab-control@0.6.10
tasks@2.6.7
todo-show@2.0.0
toggle-quotes@1.0.1
toggler@0.3.0
tool-bar@1.1.0
wordcount@2.10.4

**Comment by hultberg** [comment]
@akapa100 Thanks for you issue, however, you have a syntax error here, as the php manual documents regarding [heredocs](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.heredoc) syntax:
> **Warning**
> It is very important to note that the line with the closing identifier must contain no other characters, except a semicolon (;). That means especially that the identifier *may not be indented*, and there may not be any spaces or tabs before or after the semicolon. It's also important to realize that the first character before the closing identifier must be a newline as defined by the local operating system. This is \n on UNIX systems, including Mac OS X. The closing delimiter must also be followed by a newline.
> If this rule is broken and the closing identifier is not "clean", it will not be considered a closing identifier, and PHP will continue looking for one. If a proper closing identifier is not found before the end of the current file, a parse error will result at the last line. 

Same goes for newdoc.

*Note, I do not represent atom.*

**Comment by akapa100** [comment]
ok thank you
