### ISSUE TITLE
Text rendered as squares in dialogs

### ISSUE THREAD

**Issue by 7hibault** [atom/atom#15741]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The text in the dialogs is rendered as squares. For example, this is when I try to open a folder:
![screenshot_20170925_162212](https://user-images.githubusercontent.com/8068131/30813483-d8ab3c92-a20d-11e7-9a48-a3c4a837af6b.png)

This is a deletion confirmation dialog:
![screenshot_20170925_160650](https://user-images.githubusercontent.com/8068131/30813490-db51dff0-a20d-11e7-88d3-ca36e34011b8.png)

For some of these dialogs, I can copy/paste the text and get the expected text.

### Steps to Reproduce

1. Click File
2. Click Add Project Folder

**Expected behavior:** have the dialog open with readable text

**Actual behavior:** all text is replaced with squares

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

```
apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.13
git 2.14.1
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
```
```
KDE information:
KDE Plasma version: 5.8.7
KDE Frameworks version: 5.37.0
Qt version: 5.9.1
Kernel version: 4.12.0.1-amd64
OS type: 64-bit
```

### Additional Information

I could not find a way to debug the dialog in the suggested debugging steps.

**Comment by rsese** [comment]
> Atom    : 1.11.1

The latest stable release version of Atom is 1.20.1, can you install the latest and let us know if you still have the same issue?

**Comment by 50Wliu** [comment]
Closing until requested information is provided, as I believe there was a similar bug that has been fixed in recent Atom versions.
