### ISSUE TITLE
Segmentation Fault in Atom after installing atom-ide-ui package 

### ISSUE THREAD

**Issue by dchatterjee172** [atom/atom#15742]
If I open a file like,
$atom test.py
the main window is opening after a long wait, even after it opens, it's not responsive so i have to force close it. After force closing it, this is arriving in terminal,
/usr/bin/atom: line 129:  3930 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
Can someone tell me how can I provide more information about this bug?

Atom: 1.20.1
OS: Fedora 26
atom-ide-ui: 0.3.3

**Comment by rsese** [comment]
Thanks for the report - it looks like you opened an issue in the atom-ide-ui repository, that's probably a better place for this issue if the error happens specifically after install atom-ide-ui (assuming that if you disable or uninstall the package, things work ok?).  Also, for future issues, please fill out the issue template, it's super helpful for us and provides a lot of baseline information.

**Comment by dchatterjee172** [comment]
Thanks for your response. Yes the issue is specific to atom-ide-ui.
If i disable the package this doesn't happen.
