### ISSUE TITLE
Atom blog website's Subscribe button isn't working properly from chrome browser.

### ISSUE THREAD

**Issue by umedsondoniyor** [atom/atom#15744]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm total **newbie** and was gathering for making my _first Atom contribution_ and wanted to **Subscribe** from the following [http://blog.atom.io/2015/10/16/making-your-first-contribution.html](url) link and I realized that it's not working properly from _chrome_ cause I tried it from _mozilla_ and it worked so I wanted to open an issue about it.

### Steps to Reproduce

1. Click on Subscribe button [http://blog.atom.io/2015/10/16/making-your-first-contribution.html](url) from Chrome.
2. [Second Step]
3. [and so on...]

**Expected behavior:** [Open Subscribe page]

**Actual behavior:** [Opens long xml page with this message 

> This XML file does not appear to have any style information associated with it. The document tree is shown below.]

**Reproduces how often:** [100%]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Apologize If I opened the wrong issue or in wrong place.

**Comment by rsese** [comment]
Thanks for the report!

> it's not working properly from chrome

By not working properly I'm guessing you mean that when you click on subscribe you just see the raw XML?   I haven't used an RSS feed in a while but I kinda remember this behavior in Chrome,  seems like it's expected by default e.g.:

https://knowledge.hubspot.com/articles/kcs_article/cos-blog/do-rss-feeds-work-in-google-chrome

Hope the helps - if you have any other issues related to the blog or the https://atom.io website, I think the https://github.com/atom/atom.io would be the best place for reports.

**Comment by umedsondoniyor** [comment]
Thanks for help! Appreciate it. I was far busy with my school stuff that's why I'm giving late response. Sorry.
