### ISSUE TITLE
CMD+SHIFT+E for populating replace field

### ISSUE THREAD

**Issue by joachim-n** [atom/atom#15754]
There is a keyboard shortcut CMD+E which puts the current selection into the search field in the search dialog -- this is a standard across all of OS X, and Atom implements it.

TextMate extended this by having CMD+SHIFT+E populate the replace field.

It's very handy, and it would be nice to have this in Atom.

**Comment by 50Wliu** [comment]
Please reopen this on the [atom/find-and-replace](https://github.com/atom/find-and-replace) repository.  Thanks!

**Comment by joachim-n** [comment]
Done: https://github.com/atom/find-and-replace/issues/962
