### ISSUE TITLE
Convert Encoding BUG?

### ISSUE THREAD

**Issue by linfun486** [atom/atom#15751]
When I try to convert my JS file from GBK to UTF8, somtimes the file got empty, and I cant "redo". How do I find the file content back ?

![IMAGE](http://qiniu.linfun.cn/github/atom_convert_bug20170927.png)

### Steps to Reproduce

1. Open a javascript file with UTF8 encoding.
2. Convert to GBK encoding.
3. Convert to UTF8 encoding.
4. Loop ...
5. Sometimes happened

### Versions

**Atom**    : 1.20.1
**Electron**: 1.6.9
**Chrome**  : 56.0.2924.87
**Node**    : 7.4.0

**Script Language** javascript

**Comment by rsese** [comment]
Thanks for the report - just to confirm, when you say "Convert to GBK encoding" and "Convert to UTF-8 encoding", do you mean that you just use the [Encoding Selector](http://flight-manual.atom.io/using-atom/sections/editing-and-deleting-text/#encoding) to view the file in a particular encoding?  

Also, you mention "Sometimes happened", does that mean that this is reproducible for you?  About how many times do you have to switch encodings before the file becomes empty?  

It's not super clear to me what happened here so if undo doesn't get the content back, I'm not sure if there's any other way to get the file back.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15751#issuecomment-332422457. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
