### ISSUE TITLE
Keybinding Resolving Incorrectly: shift-alt-b resolves to shift-I

### ISSUE THREAD

**Issue by Gowiem** [atom/atom#15753]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm running into a problem where `shift-alt-b` resolves as `shift-i` within atom. It is not possible for the `shift-alt-b` key combination to resolve properly in my editor anywhere. This started occurring in the past week. It is only occurring in Atom as I have this globally setup as a keybinding on my Mac to be `select-backwards-by-word` via the KeyBindingsEditor app, and that is continuing to work globally (I have tried turned this off to confirm that it's no conflict). 

I've used the Keybinding Resolver to find out that `shift-alt-b` => `shift-i`, but now I'm stuck. Due to running in safe mode, I've confirmed this isn't a 3rd party package causing a problem. I'd like to debug this further, but I am not sure of what next steps to take. If someone can give me that next thing to try then I'd be happy to give it a go as this is an important keybinding in my workflow and it's driving me nuts. 

### Steps to Reproduce

I believe this to be a local issue with my machine, but in case it's not: 
1. Add the following to your keymap.cson: 
```coffeescript
'atom-workspace':
  'alt-shift-B': 'editor:select-to-beginning-of-word'
```
2. Try typing `shift-alt-b` in editor.
3. View in resolver that this resolves to `shift-I`

**Expected behavior:** I except my keybinding to work and have the correct keys resolved. 

**Actual behavior:** Resolving to incorrect keys. 

**Reproduces how often:** Consistently on my machine.

### Versions

```
 ~  » atom --version   
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

 ~  » apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0
```

### Additional Information

I believe I've covered it all. Happy to provide any other info if needed. 

Thanks for the help!

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

I have some questions to help debug this further.

* What keyboard layout are you using?
* Can you paste the full event if you run the following developer tools console script and press `shift-alt-b`?
```
document.addEventListener('keydown', e => console.log(e), true)
```

**Comment by Gowiem** [comment]
@Ben3eeE Thanks for the speed response!
Keyboard Layout: US (Happening on both my bluetooth Mac keyboard and my MacBook keyboard)
Full event: 
<img width="545" alt="screen shot 2017-09-27 at 11 40 38 am" src="https://user-images.githubusercontent.com/1392040/30906636-c2f92dc0-a378-11e7-877c-bc447a215d73.png">

This gives us some info because it's not resolving as `shift-i` as the resolver states but it's resolving as this little b*stard: `"ı"` which is the Mac alt character for b. Any reason that would start happening recently?

**Comment by Ben3eeE** [comment]
> Any reason that would start happening recently?

Not right now no. I am not very familiar with macOS keystroke resolution because I don't have a mac. Do other `shift-alt-` keys resolve this way? Or is it only `shift-alt-b`?

**Comment by Gowiem** [comment]
In the resolver the `shift-alt-b` keybinding is the only one that resolves without the `alt-` modifier and with a different character than I pressed. So all other alphabet keys resolve correctly it seems and then they print their Mac alt character equivalent to the editor. This would seem to be an issue with accepting that alt character (`ı`) into the resolver (as the other alt characters are not accepted). Would there be some way that I could blacklist that character from resolving? Even if it's with a monkey patch or some horrible hack?

**Comment by Ben3eeE** [comment]
> Would there be some way that I could blacklist that character from resolving?

Yes!

> Even if it's with a monkey patch or some horrible hack?

It's possible with an official API even! Here is the flight-manual entry describing how to do it http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/#overriding-atoms-keyboard-layout-recognition. Let me know if you need help writing the custom keystroke resolver and I will be happy to help.

**Comment by Gowiem** [comment]
@Ben3eeE Sweeeet, that works. This was an awesome issue debug experience. Thanks a ton for the time. Not sure if you're being paid by GH or not, but either way you're doing good work. Much appreciated. 

Here was the `init.coffee` code if others stumble upon this: 
```coffeescript
atom.keymaps.addKeystrokeResolver ({event}) ->
  if event and event.key is "ı"
    return 'alt-shift-B'
```

**Comment by Ben3eeE** [comment]
@Gowiem You're welcome and thank you for the kind words :slightly_smiling_face: I am a community volunteer maintainer so I am not being paid by GitHub.

Digging through the code it seems like this is the expected behavior if the character in the `KeyboardEvent.key` is a basic ascii character:

https://github.com/atom/atom-keymap/blob/23f82c8bc0398df66668911d3901d6e065ee2efd/src/helpers.coffee#L167-L172
