### ISSUE TITLE
Atom lags and crashes with no crash report

### ISSUE THREAD

**Issue by brandtparker** [atom/atom#15767]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using Atom, every 5 seconds the editor will lag for ~2 secs. (If I watch the cursor, it will blink 5 times, then pause 2, then start again.) Obviously see this when coding -- lag then type appears. If I leave the editor open, in the background while I'm working in other apps, it will eventually crash, after ~20mins.

Worth noting:
- I have latest stable release installed (1.20.1), with only the core packages installed and enabled.
- I've wiped my machine of Atom and all hidden files and reinstalled. Same result.
- I've tried safe mode. Same result.
- I've tried clearing saved state. Same result.
- I've reset to factory settings. Same result.
- Following a crash, I've looked in Console for a crash report. There is never one.

### Steps to Reproduce

1. Open Atom
2. Start working in any file, or even just working in the app at all
3. Notice the lagging
4. Leave app open, wait for the crash after ~20 mins

**Expected behavior:** I would expect to work in the editor with no lag and no intermittent crashes.

**Actual behavior:** It lags every 5 secs, for 2 secs; crashes after being open for ~20 mins.

**Reproduces how often:** Every time I have it open.

### Versions

Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Video: Watch cursor then lag when typing.
https://bazaarvoice.box.com/s/9a10ulqdsak8i0e8ul5qbr1i3t8ffqzq

![screen shot 2017-09-28 at 1 53 53 pm](https://user-images.githubusercontent.com/5889602/30986709-fa639dc2-a459-11e7-820f-f96de124dd52.png)

**Comment by rsese** [comment]
Thanks for the report - do you happen to have a `.git` folder in your home directory?

```
ls -ld ~/.git
```

**Comment by brandtparker** [comment]
Yes, there is a .`git` and `.gitconfig` file.

**Comment by rsese** [comment]
Thanks for confirming - I'm pretty sure that's the cause so if you don't need the directory, go ahead and delete it and let us know if you still see the lag.

Relatedly, this issue with large repos (where initializing a home directory as a repo is an example of that) should be resolved in an upcoming release /cc https://github.com/atom/github/pull/1153.

**Comment by brandtparker** [comment]
That was it. Thanks, @rsese.
