### ISSUE TITLE
Open path with space in it.

### ISSUE THREAD

**Issue by gabrielschulhof** [atom/atom#15762]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Opening a path with a space in it fails.

[Description of the issue]

### Steps to Reproduce

```
$ mkdir -p 'path/with a space/to/my'
$ echo 'file contents' > 'path/with a space/to/my/file'
$ atom 'path/with a space/to/my/file'
```

**Expected behavior:** [What you expect to happen]
atom opens with one tab showing content 'file contents'

**Actual behavior:** [What actually happens]
atom opens with three empty tabs named "with", "a", "file"

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by thomasjo** [comment]
I am unable to reproduce this on Linux (Ubuntu 17.04). What operating system are you using?

**Comment by gabrielschulhof** [comment]
Fedora 26 - 64-bit.

**Comment by rsese** [comment]
Hmmm, I tried it out on my Fedora 26 vm with Atom 1.20.1 but was unable to reproduce, `file` under  `path/with a space/to/my` gets opened in a single tab.

**Comment by gabrielschulhof** [comment]
NM. My bad.
