### ISSUE TITLE
Atom editor renders random text over each other.

### ISSUE THREAD

**Issue by ungb** [atom/atom#15761]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom editor renders random text over each other.

I am currently unable to get repro steps for this but have screenshots of the scenario

**Expected behavior:** [What you expect to happen]
Text should show up and other lines shouldn't be rendered on top

**Actual behavior:** [What actually happens]
Additional random lines are rendered above current lines and don't disappear after scrolling.
![image](https://user-images.githubusercontent.com/5624870/30943254-afe3ece4-a3a4-11e7-8b77-15f614f6a9d5.png)

![image](https://user-images.githubusercontent.com/5624870/30943260-b8698e5a-a3a4-11e7-8403-9f86de7c9055.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
I can't repro this again and unsure what I did to get to this scenario

### Versions

```
Atom    : 1.22.0-dev-1880e1401
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

While scrolling you can see it updates the line numbers but there's additional lines that just stay there.
![scrolling](https://user-images.githubusercontent.com/5624870/30943263-c51f8cf8-a3a4-11e7-8586-70acac3ee53a.gif)

/CC @nathansobo @as-cii

**Comment by rsese** [comment]
I remember this issue that looks similar /cc https://github.com/atom/atom/issues/15549?

/cc @Ben3eeE because I remember you had a go at reproducing the issue above.

**Comment by Ben3eeE** [comment]
Yeah I was able to reproduce https://github.com/atom/atom/issues/15549 but I was unable to find consistent repro steps. I can have a look at it again later.

@ungb did you use folds?

**Comment by nathansobo** [comment]
I think we should simplify our line update logic dramatically and see if it helps. There are only 6 lines per tile, so we should be able to afford a bit more brute-force of an approach than we're currently taking I think.

**Comment by Ben3eeE** [comment]
My repro was using the version mentioned in #15549 because they said in that issue it reproduced 100%. I was able to reproduce in that version but couldn't find steps to try in more recent versions.

Never reported back because more recent versions contained relevant fixes for soft wraps and folds. I'll check it out in a more recent version to see if I can repro it again somehow. @ungb We can try and find reliable steps later today when pairing.

**Comment by Ben3eeE** [comment]
Ok I have steps to reproduce in safe mode on latest beta using the file in https://github.com/atom/atom/issues/15549#issuecomment-327387699

**Gif of reproduction:**

![that double line thing](https://user-images.githubusercontent.com/1058982/30954147-607444fc-a42f-11e7-95e7-97fad3e83940.gif)

**Comment by maxbrunsfeld** [comment]
> Ok I have steps to reproduce in safe mode on beta

👏  👏  👏  👏  👏  👏  👏  👏  👏  👏  👏  👏  👏  👏  👏

**Comment by pbarbiero** [comment]
@Ben3eeE fwiw, I see this (or #15549) fairly regularly in 1.20.1, typically when I am folding and using prettier-atom.

**Comment by as-cii** [comment]
Unfortunately, we were able to reproduce this bug again after merging #15800. As a result, we decided to write a randomized test to verify some interactions in the rendering code path and managed to discover another problem that may be the cause of this issue. 

We are already working on fixing it and will submit a pull-request shortly.

**Comment by drewlandis** [comment]
I'm still seeing the random text in my Atom editor. I'm running the following:
(from `Atom > About Atom`)
```
Atom: 1.22.1 X64
```
(from `View > Developer > Toggle Developer Tools > console.log(process.versions)`):
```
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0
```

Is there anything glaring I need to update, or would it be better to open a new bug after following all of the appropriate bug steps (reproduce in safe-mode, etc).

Thanks!

**Comment by 50Wliu** [comment]
@drewlandis if this is occurring after folding, it may have to do with #16289 and #15831.  Otherwise, it would be :sparkles: if you could open a new issue!

**Comment by drewlandis** [comment]
Shucks. Unfortunately, this is not after folding. Thanks, I'll open a new issue.
