### ISSUE TITLE
Add git "stage updates" command

### ISSUE THREAD

**Issue by hagabaka** [atom/atom#15774]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In the Git user interface in Atom, there is a command to "Stage All" which is equivalent to `git add --all`. It would be useful to have another command to "Stage Updates" similar to `git add --update` which will only stage files which are already under version control and have been modified.

### Steps to Reproduce

1. Open a project with a git repository
2. Modify some version controlled files and create some new files
3. Open the git user interface

**Expected behavior:** A "Stage Update" command allows staging the modified files only, while "Stage All" does what it does currently.

**Actual behavior:** Only a "Stage All" command exists

**Reproduces how often:** 100%

### Versions

Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
Debian Sid

### Additional Information

None

**Comment by rsese** [comment]
Thanks for the suggestion! Can you re-open this in https://github.com/atom/github if there's no existing issue already so we have it in the right place?
