### ISSUE TITLE
Configure Atom to always open files in new windows

### ISSUE THREAD

**Issue by Feuermurmel** [atom/atom#15773]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm trying out Atom as a replacement for some or all my current set of text editors and I immediately found one behaviour of Atom very annoying. It seems that there is currently no way to configure Atom to open files in a separate windows instead of an already existing one. 

This even happens when there's no Atom window in the current Space but there's one on another Space. Then I'm inadvertently switched to that other Space (which breaks my workflow) and the file is opened in a window there.

### Steps to Reproduce

1. Open one file from Finder
2. Open a second file from Finder

**Expected behavior:** [What you expect to happen]

I now have two windows, each having one of the files opened.

**Actual behavior:** [What actually happens]

Both files are opened in a single window instead.

### Versions

I'm running OS X 10.11.6.

Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by rsese** [comment]
>  It seems that there is currently no way to configure Atom to open files in a separate windows instead of an already existing one.

You're right, there's no setting where Atom will always open files opened from Finder in a new window in all cases (from the command line you can start Atom with `atom -n file`).  The different ways Atom can be started is something the team is thinking of and the high level issue to watch is https://github.com/atom/atom/issues/10517.
