### ISSUE TITLE
Cursor jumps, changes are reverted after IME composition pops up on input-disabled-editor.

### ISSUE THREAD

**Issue by t9md** [atom/atom#15783]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When IME composition pops up on input-disabled-editor, it incorrectly create checkpoint.
After enable input and start insertion, buffer-state is reverted to wrongly created checkpoint(so cursor jumps, changes are reverted).

At final timing in GIF, text `a` is inserted elsewhere, and text-deletions are reverted.

![ime-issue](https://user-images.githubusercontent.com/155205/31051857-69ddbd26-a6ae-11e7-9e6f-d5f7240cf547.gif)

**This is really critical issue for vim-mode-plus user who use IME(e.g. Japanese, Chinese)**
Since vim-mode-plus fundamentally depends on disable/enable input(`editor.component.setInputEnabled(true/false)`) to achieve modal-editing.

##### Steps for explanatory purpose

1. Disable input `editor.component.setInputEnabled(false)`
2. Enable IME and pops up IME composition by entering some text.
3. Move cursor, also delete line by `editor:delete-line`(`ctrl-shift-K`).
4. Enable input `editor.composition.setInputEnabled(true)`.
5. Type some text to insert text.

At first char input timing.

- Char inserted at cursor position where last IME composition pop up happened.(position in step-2).
- Also all the buffer-text changes done after step-2 are **reverted**.

##### Steps for easy to observe.

1. Open non-empty editor.
2. Paste code bellow on chrome dev-console, at this point editor-input is disabled.

```javascript
(function emulateVimMode() {
  const editor = atom.workspace.getActiveTextEditor()
  editor.element.classList.add("vim-test")

  startInsert = () => {
    if (!editor.component.isInputEnabled()) {
      editor.component.setInputEnabled(true)
      console.log("start insert")
    }
  }
  stopInsert = () => {
    if (editor.component.isInputEnabled()) {
      editor.component.setInputEnabled(false)
      console.log("stop insert")
    }
  }

  atom.commands.add(editor.element, {
    "vim-test:start-insert": () => startInsert()
    "vim-test:stop-insert": () => stopInsert()
  })
  stopInsert()
})()
```

3. Enable IME and type some keys to make IME composition pops up then stop IME.
4. Move cursor, also delete line by `editor:delete-line`(`ctrl-shift-K`).
5. Enable input by executing `vim-test:start-insert` via command-palette.
6. Type some text to insert text.(see cursor jumps, changes are reverted)

**Expected behavior:** [What you expect to happen]

Text is inserted at cursor position and changes are NOT reverted.

**Actual behavior:** [What actually happens]

Text is inserted at different position and all changes are reverted.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% with safe-mode

### Versions

Issue not happens in v.1.18, so I believe this issue started after editor-rewrite.

- Could reproduce: v1.19.7, 1.20, 1.21-beta2

```
Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
Atom    : 1.21.0-beta2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

- could NOT reproduce: v1.18.0(haven't check all patch versions)

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

- Original issue in vim-mode-plus
https://github.com/t9md/atom-vim-mode-plus/issues/875

Other reported issue like "content reverted" might shares same cause with this issue.
al

**Comment by t9md** [comment]
I use google IME (Google日本語入力), also I confirmed this could be reproduce-able for macOS native IME for japanese(kotoeri).

**Comment by t9md** [comment]
For me and other IME+vim-mode-plus user, this is super critical issue.

- This gives new user "Atom is unstable" impression, since it move cursor, revert changes without any error. Just jump cursor, revert buffer state to when and where most recent IME pops up was opened.

I will try to investigate fix tomorrow.
Also I hope someone github-team take this regression as really serious one.

**Comment by lee-dohm** [comment]
Thanks for the ping @t9md. Yes, our team is definitely taking this seriously and looking into a fix as soon as possible.

**Comment by as-cii** [comment]
Thanks for the (as usual) detailed report, @t9md! 🙇 We are working on a fix right now, and will submit a pull-request shortly.

**Comment by t9md** [comment]
Thank you @lee-dohm for hearing me.
Thank you @as-cii  for working this!
