### ISSUE TITLE
Data loss when switching branches

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#15791]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have a successful repro for a data loss scenario that can occur when switching branches while having unsaved changes on a file that has been modified on the branch you're switching to.

### Steps to Reproduce

1. Checkout the `wl-data-loss` branch on [atom/language-html](https://github.com/atom/language-html)
2. Add the following code after line 354 (such that it lines up with the `it` on line 342 and has proper spacing):
```coffee
    describe "the 'style' attribute", ->
      beforeEach ->
        atom.packages.activatePackage('language-css')

      it "tokenizes the style attribute value as a CSS property list", ->
        tokens = grammar.tokenizeLine '<span style="color: red;">'

        expect(tokens[3]).toEqual value: 'style', scopes: ['text.html.basic', 'meta.tag.inline.span.html', 'meta.attribute-with-value.style.html', 'entity.other.attribute-name.style.html']
        expect(tokens[5]).toEqual value: '"', scopes: ['text.html.basic', 'meta.tag.inline.span.html', 'meta.attribute-with-value.style.html', 'string.quoted.double.html', 'punctuation.definition.string.begin.html']
        expect(tokens[6]).toEqual value: 'color', scopes: ['text.html.basic', 'meta.tag.inline.span.html', 'meta.attribute-with-value.style.html', 'source.css.style.html', 'meta.property-name.css', 'support.type.property-name.css']
```
I have also provided the modified file as a Gist here: https://gist.github.com/50Wliu/89ca9346904f8d9630e27ece49b52b8d
3. Checkout `wl-data-loss-here` _without saving the file_
4. Reload Atom

**Expected behavior:** Checkout to fail since there are unsaved changes and `html-spec.coffee` has been modified on `wl-data-loss-here`

**Actual behavior:** Checkout succeeds and shows the file as modified.  Upon reloading Atom, all unsaved changes are lost.

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.23.0-dev-c30cc9bc8
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

Windows 10 x64.

/cc: @maxbrunsfeld @smashwilson

**Comment by maxbrunsfeld** [comment]
@50Wliu Can you test this again on master? We should now prompt you to save your file before reloading. I think there are other improvements we can make in this area, but this may be good enough to close this issue for now. What do you think?

**Comment by 50Wliu** [comment]
Can confirm that I get a dialog prompt when attempting to reload.
