### ISSUE TITLE
Atom will not start, will not install

### ISSUE THREAD

**Issue by VergilPrime** [atom/atom#15806]
Windows 10 64 Bit

Atom version v1.21.0 (2017-10-03)

After an update today, several things occured. First the icon changed to the default application icon. Didn't think much of it.

After a restart, Atom won't open from terminal (Git for Windows) "atom" command. Decided to reinstall.

Attempted to reinstall using installer downloaded a week or two ago. Failed. Tried running installer as admin, failed. [https://i.imgur.com/5bzcWI8.png](https://i.imgur.com/5bzcWI8.png)

Uninstaller won't run, something about invalid uninstaller I think. Uninstalled using Revo Uninstaller.

Tried reinstalling, same failure message. Tried installing beta for giggles, same problem.

Here's the install log:
[http://paste.thezomg.com/23584/07097235/](http://paste.thezomg.com/23584/07097235/)

**Comment by rsese** [comment]
Do you have any anti-virus running?  If so, can you temporarily disable and try installing again?

As a side note, even if some of it doesn't apply, it's helpful for us if you use the issue template and fill in the information where you can.

**Comment by damieng** [comment]
`Access to the path 'C:\Users\Vergi\AppData\Local\atom\Update.exe' is denied.`  normally indicates an over-aggressive anti-virus. Additionally could be permissions or another copy of the installer/updater still running (hung?) in background (kill with task manager)

**Comment by VergilPrime** [comment]
That was likely related, I got 1.20 reinstalled on the system however, so was there a change in 1.21 that would cause Avast to treat it differently?

As for testing, I'm actually reinstalling my OS so I can't at the moment.

**Comment by damieng** [comment]
There were no changes relating to anti-virus specifically but as with every release the binaries change and sometimes the AV products get over-aggressive especially when they are seeing new binaries in the wild for the first time (e.g. the first day or two of release).

We digitally sign our atom.exe, update.exe and atomsetup.exe and there's only so much we can do to placate them.

**Comment by jonathanrjpereira** [comment]
Atom not opening on Windows 10 64 bit.

**Comment by damieng** [comment]
@jonathanrjpereira if you are using an anti-virus product I would try temporary disabling it.

If not please open a new issue with the template filled out.

**Comment by creatheon** [comment]
Hello, I had similar issues, and here's the log:


[AtomDisasterSquirrelSetup.log](https://github.com/atom/atom/files/1371636/AtomDisasterSquirrelSetup.log)


> Long story short, I accidentally ended up running the installation for Atom again (twice at once, and this is after I had been using it for a few days already). I closed both installations, and tried opening the Atom I already had - which is when I started getting error messages.
> 
> The shortcuts said that it linked to a location/file that no longer existed, so those got deleted. Then I deleted/uninstalled Atom from Win 10 Settings. Also forced shutdown from Task Manager. Downloaded latest version from GitHub, and tried running again. Error messages again.
> 
> 
> I would like to reiterate that I had shut down all previous versions of Atom as much as possible before running this installation again.

**Comment by creatheon** [comment]
Out of curiosity, why was Squirrel trying to interact with Discord at the beginning?

?_?

**Comment by damieng** [comment]
Discord also use Squirrel to install their desktop app.  Annoyingly Squirrel uses a single log file between the apps so you'll see multiple applications being installed in a single file.

**Comment by damieng** [comment]
I'd try clearing out the %appdata%\atom folder entirely after uninstalling and then try a reinstall.

If that fails you might just want to download the .zip and unpack it somewhere instead.

**Comment by the-j0k3r** [comment]
Smartscreen in Windows can be over protective also, especially for new executables. You could try [chocolatey](https://chocolatey.org/) to install Atom, maybe it will work better/play nicer with your anti-virus/setup.

**Comment by damieng** [comment]
Haven't seen any issue with Smartscreen as we sign Atom with digital certificates. (if you don't then it definitely gets upset)

**Comment by creatheon** [comment]
Actually, I tried out Damien's earlier suggestion of wiping out the temp folders and then trying to reinstall. 

Seems to have worked rather well, although somethings were weird (i.e. the downloading Atom screen was suddenly very tiny).

Thank you for your assistance

**Comment by rsese** [comment]
> Seems to have worked rather well, although somethings were weird (i.e. the downloading Atom screen was suddenly very tiny).

I think that's https://github.com/atom/atom/issues/15873 if you want to subscribe for that issue.
