### ISSUE TITLE
Atom & Atom Beta both crashing with Mac OS 10.13

### ISSUE THREAD

**Issue by michaelspeed** [atom/atom#15801]
### Description

Its freezes for 3-4 seconds and then become active again. if i do not stop at that point it crashes.
Tells me to report the problem here

### Steps to Reproduce

1. Update form 10.12.6 --> 10.13
2. Atom && Atom Beta both pre-installed in 10.12.6

**Expected behavior:** 
Not to crash

**Actual behavior:** 
Crashes so frequently that i cannot write any code

**Reproduces how often:** 20 times in an hour

### Versions

Atom - 1.21.0
Atom Beta - 1.21.0 beta -2

**Comment by PaulAndreRada** [comment]
1+ in mac 10.12.6
Can't even open atom for more than 5 minutes without it crashing. 
No action taken outside of `atom . ` inside the terminal to open a `.json` file

**Comment by rsese** [comment]
@michaelspeed - can you confirm if you went through the Prerequisites section of the issue template?  E.g. do you see the same behavior in safe mode (`atom --safe`)?

@PaulAndreRada - the latest stable release of Atom is 1.21.0, can you upgrade and if you're still seeing a crash, please open another issue with the issue template filled out and we'll take a look with you.

**Comment by michaelspeed** [comment]
atom --safe also crashes(not so frequently). what i did was i removed atom and atom beta, and also its supporting folders and everything.Then installed it again. Currently in one hour its not crashing

**Comment by PaulAndreRada** [comment]
@rsese Updated to 1.21.0, All working perfect so far. Thanks man

**Comment by rsese** [comment]
Good to hear that crashing has stopped for you @michaelspeed - we'll close this issue for now but if you see crashes again, let me know and we'll re-open.

Glad to hear things are looking good for you too @PaulAndreRada :+1:
