### ISSUE TITLE
Unable to git push since v1.21.0

### ISSUE THREAD

**Issue by HitomiTenshi** [atom/atom#15809]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since `v1.21.0` I get an error when I try to push my commits via the git window in atom.

```
error: cannot spawn .git/hooks/pre-push: No such file or directory
error: waitpid for .git/hooks/pre-push failed: No child processes
error: failed to push some refs to 'https://[url]/[project].git'
```

`v1.22.0-beta0` has the same issue.

### Steps to Reproduce

1. Stage changes and create a commit
2. Click on `Push`

**Expected behavior:** It should push commits to remote without errors.

**Actual behavior:** The above error appears.

**Reproduces how often:** Always since `v1.21.0`

Previous versions are not affected.

### Versions

Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Windows 10 x64

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/github if there's no existing issue already so we have it in the right place?
