### ISSUE TITLE
Atom with Electron 1.6.9+ causes dev tools to pause during autocomplete

### ISSUE THREAD

**Issue by ungb** [atom/atom#15803]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Electron upgrade to 1.6.9+ causes dev tools to pause during autocomplete

### Steps to Reproduce

1. Open Atom off master [currently](https://github.com/atom/atom/commit/5a67a05c7a81d19625e9b52b5e6020c71d1bd47e)
2. Open dev tools
3. go to sources and click pause
![image](https://user-images.githubusercontent.com/5624870/31149154-d91b0464-a843-11e7-9729-ce05c6c023b6.png)
3. type in something to auto complete. 

![slow-dev-tools-autocomplete](https://user-images.githubusercontent.com/5624870/31148922-0efd7f22-a843-11e7-9306-fdd73a72e181.gif)

**Expected behavior:** [What you expect to happen]
Atom doesn't pause when using dev tools in console while being paused

**Actual behavior:** [What actually happens]
Atom seems to pause a lot while typing and autocompleting.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.23.0-dev-c9c495792
Electron: 1.6.14
Chrome  : 56.0.2924.87
Node    : 7.4.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

/cc @Ben3eeE @nathansobo

**Comment by ungb** [comment]
going back versions I see this in atom 1.18.0 that has `Electron 1.3.15`

On 1.15.0 of Atom this doesn't occur with `Electron 1.3.13`

**Comment by nathansobo** [comment]
@ungb IT would be helpful to build Atom 1.15 with Electron 1.3.15 (it will probably just work) and see if it was the Electron bump that caused it. What about Atom 1.16 and 1.17?

**Comment by Ben3eeE** [comment]
1.15 with Electron 1.3.15 is not slow.
1.16 with Electron 1.3.13 is not slow.
Working on checking 1.17

**Comment by Ben3eeE** [comment]
Closed via https://github.com/atom/atom/commit/3f0f72ad0b3d33490a02ddcf25c4ed49b5a1f75e
