### ISSUE TITLE
I can't insert HTMl snippet in PHP and HTML files in Atom 1.22.0. 

### ISSUE THREAD

**Issue by gusbemacbe** [atom/atom#15819]
### Description

In PHP and HTML files, I can't insert HTML snippet. After I installed a Bootstrap package, I tried again to insert HTML snippet.

It seems that one of your developers removed '`meta.tag.anyhtml`' and removed our most wanted snippets. Check: https://github.com/atom/atom/pull/15712.

Then I have to write by myself

### Steps to Reproduce

1. Type "html"
2. Press tab or enter
3. You do not find the snippet

### Versions

Atom 1.22.0
macOS Sierra 10.12.6

**Comment by jasonrudolph** [comment]
@50Wliu: I'm seeing this as well, and it seems related to https://github.com/atom/language-html/commit/8f0908dc354d4b62b635394fc3be5568e2879741. Would you have a time to take a look?

cc @ungb @iolsen for :eyes:

**Comment by rsese** [comment]
> @50Wliu: I'm seeing this as well, and it seems related to atom/language-html@8f0908d. Would you have time to take a look?

@50Wliu is out for another week-ish but the issue has been added for discussion in the reactive meeting :v:

**Comment by youngjuning** [comment]
@rsese Thanks for your work

**Comment by youngjuning** [comment]
this issue still happen in 1.22.1 beta
