### ISSUE TITLE
`watchPath` fails for files/folders that do not exist yet

### ISSUE THREAD

**Issue by lloiser** [atom/atom#15818]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using the `watchPath` method fails if the file/folder does not exist yet.

To me this feels not correct because the documentation https://atom.io/docs/api/v1.21.0/PathWatcher mentions "created" events. So I assumed that it notifies me when the file/folder is created.

### Steps to Reproduce

Open the console and try this:
```js
require("atom").watchPath("/home/lloiser/does-not-exist.md", {}, (events) => { console.log(events) })
  .then((watcher) => { console.log(watcher) })
  .catch((err) => { console.log(err) })
```

**Expected behavior:**

It should not fail. Additionally it should call the provided callback with a "created" event once the file/folder is created.

**Actual behavior:** 

It shows the following error in the console:
```
Uncaught (in promise) Error: ENOENT: no such file or directory, lstat '/home/lloiser/.my-config-file'
```

It's also not possible to catch this error.

**Reproduces how often:**

100%

### Versions

OS: Ubuntu 16.04 and Windows 10

```
$ atom -v
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm -v
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
```

### Additional Information

It happens in this `fs` call, where an `err` is returned that causes the `Uncaught promise` error
https://github.com/atom/atom/blob/da7fa1f481ac3db2b803df54e1c2f31457b118c3/src/path-watcher.js#L390-L398

**Comment by rsese** [comment]
Added to the project board for discussion but /cc @smashwilson :v:

**Comment by smashwilson** [comment]
> To me this feels not correct because the documentation https://atom.io/docs/api/v1.21.0/PathWatcher mentions "created" events. So I assumed that it notifies me when the file/folder is created.

Watchers created by `watchPath` are recursive. The intent is that "created" events arrive when entries are created _within_ the subtree beneath a watched root directory, like so:

```js
const {watchPath} = require('atom')

const watcher = await watchPath('/home/lloiser', {}, events => { console.log(events) })
```

```sh
touch /home/lloiser/foo.md
mkdir -p /home/lloiser/dir0/dir1/dir2
```

Which should produce events like:

```js
{ action: 'created', kind: 'file', path: '/home/lloiser/foo.md' }
{ action: 'created', kind: 'directory', path: '/home/lloiser/dir0' }
{ action: 'created', kind: 'directory', path: '/home/lloiser/dir0/dir1' }
{ action: 'created', kind: 'directory', path: '/home/lloiser/dir0/dir1/dir2' }
```

So, I wouldn't expect the call you made to succeed. Now the question is, should we clarify the documentation, or change the expectation :smile:

What is your use case for watching a path that doesn't exist yet?

> It's also not possible to catch this error.

This part definitely feels wrong to me. I would expect a failing `fs.realpath` call to reject the Promise for you. 🤔 I'll have a look to see if the rejected Promise is being lost somewhere.

**Comment by lloiser** [comment]
> What is your use case for watching a path that doesn't exist yet?

[My package](https://github.com/lloiser/go-debug) has a settings where a user sets the path to a "configuration" file that contains further configuration for my package. In theory it should exist but a user can set any path in the settings, even files that may not exist yet. So it would have been nice to receive the created event if it is not available yet.

I could watch for changes in the parent dir and if this dir also does not exist (and the error is `catch`able) then I could show a notification to create the file first and the restart atom ☺️, no problem here.

> within the subtree beneath a watched root directory

> clarify the documentation

Actually it says in the very first line that events are received within the root directory you pass to it. I just debugged other calls of `watchPath` and the very first after a atom reload was the `config.cson` file so I assumed that it also works for files. Which it does if the file exists 😁. 

Thx for clarifying and looking into the error 🙇
