### ISSUE TITLE
Layout is lower or 1 px.

### ISSUE THREAD

**Issue by pingping-n** [atom/atom#15814]
### Description
![alt text](https://im3.ezgif.com/tmp/ezgif-3-873c1ad110.gif)

Layout "0 files" is lower or 1 px.

### Steps to Reproduce

1. Open Atom and look at bottom right.

### Versions

Atom 1.21.0 x64
Windows 10 x64 Education

**Comment by 50Wliu** [comment]
@pingping-n can you re-upload your gif?  It's giving me a "Not Found" error.

**Comment by Hydro95** [comment]
![image](https://user-images.githubusercontent.com/7350336/31196169-be5c1708-a91a-11e7-9b01-9ed78decff44.png)
![image](https://user-images.githubusercontent.com/7350336/31196189-ce7b2a20-a91a-11e7-8e7b-7d1dd5cf261a.png)
![image](https://user-images.githubusercontent.com/7350336/31196201-d801638e-a91a-11e7-84b3-08bdb2795264.png)

I think this is what @pingping-n is trying to say, expressed in these images. If you look carefully you can see how the text and the top of the highlight on the button sits a few pixels lower than the rest of its neighbors.

**Comment by 50Wliu** [comment]
Thanks @Hydro95!  Moved to https://github.com/atom/github/issues/1198.

**Comment by pingping-n** [comment]
Thank you!
