### ISSUE TITLE
small typo on UI in install view

### ISSUE THREAD

**Issue by fae92** [atom/atom#15811]
![oct -04-2017 12-01-33](https://user-images.githubusercontent.com/5829807/31170308-df23380a-a8fb-11e7-9c36-dffd97aa765c.gif)

see the gif ! 
see next  -> `core Themes`

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/settings-view if there's no existing issue already so we have it in the right place?  If you can also fill out the issue template, that would be super helpful for us.
