### ISSUE TITLE
Highlight is out of alignment with cursor and text positions

### ISSUE THREAD

**Issue by pbarbiero** [atom/atom#15829]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Highlighted text selection is offset improperly with certain syntax themes. In particular, `no-caffeine`. Similar to what I reported in https://github.com/atom/atom/issues/15241 except instead of the cursor being busted, now its the highlight.

### Steps to Reproduce

1. Upgrade to 1.21.0
2. Switch to no-caffeine syntax theme
3. Highlight text
4. Observe highlight is misaligned

**Expected behavior:** Highlight to be aligned with the text

**Actual behavior:** Highlight is offset

**Reproduces how often:** 100%

### Versions

1.21.0

### Additional Information

I did NOT see this in 1.20.x

Screenshots:
Working (atom dark) 
![working](https://user-images.githubusercontent.com/20247733/31253262-c1dc2a60-a9e9-11e7-8eba-ef9cd8331c3f.png)
Broken (no caffeine)
![broken](https://user-images.githubusercontent.com/20247733/31253275-d179592a-a9e9-11e7-8e10-317c39208e08.png)

**Comment by rsese** [comment]
I can reproduce on macOS 10.12.6 with Atom `1.23.0-dev-c30cc9bc8`.  A slightly bigger image (selecting from right to left, the selection is shifted a bit to the left and the right part of the `n` isn't highlighted):

![selection-highlight](https://github-slack.s3.amazonaws.com/monosnap/scratch.js__workjs-excercises_2017-10-05_17-52-14.png)

Adding to the project board but /cc @as-cii @nathansobo

**Comment by rsese** [comment]
> I did NOT see this in 1.20.x

Confirmed this too in 1.20.1, tagging as a regression.

**Comment by iolsen** [comment]
@nathansobo @as-cii looks like an editor regression if you can take a look.

**Comment by pbarbiero** [comment]
@rsese hate to bug you, but any chance this could get some traction for the next release?

**Comment by rsese** [comment]
No problem @pbarbiero - this issue has been added to the backlog of work for the team to investigate but in general we can't make any promises about a timeline for when it might get resolved.
