### ISSUE TITLE
Atom ui elements all zoomed

### ISSUE THREAD

**Issue by vigenere23** [atom/atom#15824]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom starts with everything zoomed up to 2x their normal size... I'm on a 2560x1440 25" monitor (118 ppi)

### Steps to Reproduce

1. Updating to **1.19.0** and further

**Expected behavior:** Opens with decently sized elements

**Actual behavior:** Every element is zoomed up to 1.5x-2.0x their normal size... But not blurry, just zoomed

**Reproduces how often:** ALWAYS

### Versions

Atom : 1.21.0 (happens every version form **1.19.0** to latest)
Electron : 1.6.9
Chrome : 56.0.2924.87
Node : 7.4.0
OS : Windows 10

### Additional Information

Picture (Left : normal (1.18.0 and below), Right : zoomed (1.19.0 and further)) : 
![image](https://user-images.githubusercontent.com/32545895/31237044-3643b152-a9cc-11e7-8ab6-0f5b834137e4.png)

**Comment by rsese** [comment]
I'll try to install 1.17.2 on my Windows 10 machine to compare though I didn't particularly see any changes that might be related while scanning through the 1.18 [release notes](https://github.com/atom/atom/releases/tag/v1.18.0).

I noticed your screenshot shows Atom isn't in safe mode, did you notice any difference in safe mode?

**Comment by vigenere23** [comment]
Ok, seems like I've trigged the automatic update by accident. I've edited the issue, it actually does this bug since **1.19.0**, and no unfortunatly safe mode doesn't help, nor any of the debug steps :/

**Comment by BalajiJBcs** [comment]
Just test by reducing the resolution to 1080p if it works fine then might be Atom not rendering correctly for the high-resolution monitor.

**Comment by vigenere23** [comment]
Still does it... Was the zooming just a decision taken by teh team? How to revert to the original size? 

Here's a picture again, left being 1.18.0 and right, 1.19.0, this time both in safe mode just to be sure. 
![image](https://user-images.githubusercontent.com/32545895/31248044-d98617c6-a9e8-11e7-9677-c2ec63d7d097.png)

**Comment by vigenere23** [comment]
That zoom occurs since the very first beta (#0) of 1.19.0

**Comment by vigenere23** [comment]
Any news?
