### ISSUE TITLE
Command palette (not file/project search) is iterating through node_modules

### ISSUE THREAD

**Issue by alechp** [atom/atom#15825]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
node_modules isn't excluded from **command palette**

<img width="636" alt="screen shot 2017-10-05 at 11 11 02 am" src="https://user-images.githubusercontent.com/3058939/31245612-be29fa8e-a9bf-11e7-9ec3-1bed46d92a29.png">

node_modules is currently excluded:
* in file/project search (CMD + F, SHIFT + CMD + F)
* .gitignore

Reason this is obnoxious is it momentarily reindexes project every time.
![screen shot 2017-10-05 at 11 22 08 am](https://user-images.githubusercontent.com/3058939/31245590-b2384262-a9bf-11e7-80b9-8287c4dac523.png)

### Steps to Reproduce

1. CMD + P
2. type term shared by file path in both your project and node_modules (in my case, "integration")

**Expected behavior:** [What you expect to happen]
Only show possible files in current workspace (excluding) 

**Actual behavior:** [What actually happens]
Includes node_modules:

<img width="624" alt="screen shot 2017-10-05 at 11 13 53 am" src="https://user-images.githubusercontent.com/3058939/31244770-c816ea44-a9be-11e7-9fab-c094f37bf2cc.png">

This is especially menacing because it quickly reindexes all of the files. 

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% (confirmed after safe-mode & clear-window-state):

![screen shot 2017-10-05 at 11 18 49 am](https://user-images.githubusercontent.com/3058939/31245375-0221b43a-a9bf-11e7-87a0-158758251fb0.png)

### Versions
```
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by rsese** [comment]
> node_modules is currently excluded:
> 
> in file/project search (CMD + F, SHIFT + CMD + F)
> .gitignore

Can you share your .gitignore?  And is the .gitignore in the root of the project you have open?

You can also add `node_modules` to `Settings > Packages > fuzzy-finder > Ignored Names` so it doesn't show up in fuzzy finder.

**Comment by alechp** [comment]
Adding to fuzzy-find fixed it. Thank you!

-----

Not necessary, but answering your original question:
```.gitignore
# See https://help.github.com/ignore-files/ for more about ignoring files.

# dependencies
/node_modules

# testing
/coverage

# production
/build

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*
```
