### ISSUE TITLE
Atom doesn't uninstall properly when removed [MacOS 10.12.6]

### ISSUE THREAD

**Issue by Jennigma** [atom/atom#15822]
I just tried to remove Atom. It had not properly registered with the OS, so when I deleted it, there were still Atom fingerprints all over my system. 

Most egregiously, I had to reset my LaunchServices because the application had claimed ownership of every possibly relevant file extension, and not released them when removed.

Ick.

I expect better from GitHub. I installed this editor without much thought because I trusted you.

For shame. 

### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks very much for the feedback @Jennigma - there’s a [discussion on our message board](https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/34) about this particular topic and I can definitely see how there could be a better uninstall experience based on comments there and your comments.    I’ll share your feedback with the team.

**Comment by Jennigma** [comment]
Thanks for the follow-up. 

I was considering using Atom in a tutorial I'm writing, because it looked like a good package for novices working on a git based Arduino project. I'm now warning against it instead.
