### ISSUE TITLE
missing "Show Tab Bar" on MacOS 10.13

### ISSUE THREAD

**Issue by loadingwyn** [atom/atom#15832]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There is no "Show Tab Bar" option under `macOS > Menu > View` with` Atom > Settings > Core > Title Bar`  set to `native`;

### Steps to Reproduce

1. Upgrade to Atom 1.21.0

2. Open `Menu > View`

![2017-10-06 12 42 42](https://user-images.githubusercontent.com/17921180/31263350-4b32a2fc-aa27-11e7-8d5a-2cf6e712f07f.png)

![2017-10-06 12 47 23](https://user-images.githubusercontent.com/17921180/31263412-9d079b6e-aa27-11e7-9fa3-cc63dbdf16fb.png)

**Expected behavior:** [What you expect to happen] show "Show Tab Bar" button under `View`

**Actual behavior:** [What actually happens] no "Show Tab Bar" button

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Versions

MacOS: 10.13
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by rsese** [comment]
Thanks for moving this over from https://github.com/atom/atom/pull/14711#issuecomment-334093919 @loadingwyn :v:

Noting from https://github.com/atom/atom/pull/14711 that Lee couldn't reproduce on High Sierra /cc https://github.com/atom/atom/pull/14711#issuecomment-334491228 and on macOS 10.12.6, I see the menu item is there.

Tagging as needs reproduction, I don't have High Sierra to test with.

Curious if you install the beta is `Show Tab Bar` not available there for you either?

**Comment by loadingwyn** [comment]
I reinstalled Atom(1.21.0) and Atom beta (1.22.0-beta0) , there is still no the "Show Tab Bar".

![2017-10-07 3 41 21](https://user-images.githubusercontent.com/17921180/31305912-e1da631a-ab09-11e7-96ea-fb0169ef6d52.png)

I'm clueless about this, so I'm sorry I can't give more infomation.

**Comment by peterw8102** [comment]
I had the same problem. Fixed it by:
+ switch to custom title bar (restart Atom)
+ switch back to native (restart atom)
+ show tab bar now available

**Comment by loadingwyn** [comment]
@peterw8102 Thank you, but it doesn't work for me.

**Comment by DonaldChiang** [comment]
same here on MacOS 10.13 and Atom 1.21.1

I have tried @peterw8102 's solution and it work for me, now I can open new Atom window in native tab but there is no `Show Tab Bar` in View menu

<img width="514" alt="2017-10-19 4 32 06" src="https://user-images.githubusercontent.com/29910065/31761613-1e562dfc-b4eb-11e7-8484-1f7ecc7f1f4b.png">

**Comment by rsese** [comment]
@loadingwyn just checking are you still seeing this in the latest Atom releases (1.27.1 and 1.28.0-beta1)?

**Comment by loadingwyn** [comment]
@rsese 😭Yes....no button in v1.27.1
macos: 10.13.4
node: 10.2.1

**Comment by danbates2** [comment]
Hi. 
+1
Also related to this, the 'native' or 'custom' title bar setting should be default for Atom on MacOS. I was unable to drag and reposition the window because I had no title bar to grab, from a 'hidden' setting.
The 'hidden' title bar setting needs to enable dragging of the window by using blank tab space or tree-view space, a bit like this: https://atom.io/packages/no-title-bar 
Except I don't this that package's behaviour with title bar setting 'custom' is good, it hides the bar and makes the first tab look messy against the three window radio buttons in the corner.

I have 10.11.6 El Capitan.
