### ISSUE TITLE
[master-branch] cursor.getEndOfCurrentWordBufferPosition() should return Point.

### ISSUE THREAD

**Issue by t9md** [atom/atom#15847]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Regression in master-branch.

- OK: v1.22.0-beta0: `cursor.getEndOfCurrentWordBufferPosition()` returns instance of `Point`.
- OK: v1.21.0: `cursor.getEndOfCurrentWordBufferPosition()` returns instance of `Point` too.
- BUG: master-branch: `cursor.getEndOfCurrentWordBufferPosition()` return Object with `row` and `column` field.

Which means, we can not call Point's method like `translate` anymore, breaks expectation we hold in older version.

### Steps to Reproduce

1. Open text editor with text "abc" place cursor at `a`.
2. execute `atom.workspace.getActiveTextEditor().getLastCursor().getEndOfCurrentWordBufferPosition()` in chrome-dev-console.
3. See output is `Object {row: 0, column: 0}`(not `Point {row:0, column: 0}`). So we cant call methods like `translate`(see `undefined` is returned)

**Expected behavior:** [What you expect to happen]

`getEndOfCurrentWordBufferPosition` should return point of instance.

**Actual behavior:** [What actually happens]

`getEndOfCurrentWordBufferPosition` should return plain object.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%.

### Versions

```
Atom    : 1.23.0-dev-683cdea
Electron: 1.6.14
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

Got report on vim-mode-plus and noticed it's regression of atom-core master-branch.
https://github.com/t9md/atom-vim-mode-plus/issues/907

**Comment by maxbrunsfeld** [comment]
Thanks for the report @t9md!
