### ISSUE TITLE
Unable to save with mouse click on close

### ISSUE THREAD

**Issue by buggsdummy** [atom/atom#15845]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
I renamed a file, and when saving the file it won't allow the mouse to click on any of the buttons, but I'm able to move the cursor freely and press enter 

### Steps to Reproduce

1. [First Step]
Edit file
2. [Second Step]
Rename file
3. [and so on...]
Try clicking on buttons with mouse

**Expected behavior:** [What you expect to happen]
Mouse should be able to click on buttons

**Actual behavior:** [What actually happens]
Mouse can't click on the buttons

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
atom --version
Atom    : 1.19.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!

> Also, please include the OS and what version of the OS you're running.

Can you share what operating system you're running?

About your steps to reproduce:

> Try clicking on buttons with mouse

Which  buttons are you trying to click?  Do you mean mouse buttons or buttons in Atom?

Lastly:

> Atom : 1.19.1

The current stable version of Atom is 1.21.0 - can you update and let us know if you're still having the same problem?

**Comment by buggsdummy** [comment]
Linux Mint 18.2 
Trying to click on the buttons in atom when in prompts. 
I will update and let you know if it fixed it.

**Comment by buggsdummy** [comment]
You can close this, it's fixed in latest one. Thanks! I'll remember to update first before posting :)
