### ISSUE TITLE
Text rendering is sometimes cut off a single pixel to the left.

### ISSUE THREAD

**Issue by p0lm** [atom/atom#15843]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Text is offset a single pixel to the left in some panes after splitting. Resizing the pane a couple of times sometimes fixes this. It happens in both the editor as well as the gutter. I use a converted pixel font (Terminus TTF), so the cut-off pixel is clearly visible. 

### Steps to Reproduce

1. Set editor font to Terminus TTF.
2. Type some text in the editor.
3. Split the pane a couple of times.

**Expected behavior:** No text offset
![screenshot_2017-10-08_23-42-59](https://user-images.githubusercontent.com/12779601/31321215-842762f2-ac82-11e7-9f26-bc5207d0c2a0.png)

**Actual behavior:** Text is offset a single pixel to the left.
![screenshot_2017-10-08_23-24-06](https://user-images.githubusercontent.com/12779601/31321214-81eadbd6-ac82-11e7-8717-e8e49bf23e59.png)

**Reproduces how often:** +/- 50%

### Versions
```bash
$ cat /proc/version
Linux version 4.9.51-1-MANJARO (builduser@manjaro) (gcc version 7.2.0 (GCC) ) #1 SMP PREEMPT Wed Sep 20 10:37:40 UTC 2017
$ atom --version
Atom    : 1.20.0
Electron: 1.6.11
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm --version
apm  1.18.5
npm  5.3.0
node 8.5.0 x64
python 2.7.13
git 2.14.1
```

### Additional Information

Terminus TTF is available as a package in all major Linux repositories. It can also be downloaded [here](https://files.ax86.net/terminus-ttf/).

**Comment by joedski** [comment]
I'd like to say I can add that this happens on Mac, too, but I have yet to actually reproduce it after it happened that one time.  It was visual apparent even without a pixel font.

**Comment by rsese** [comment]
Thanks @joedski - I'll remove the `linux` label for now but if you end up with steps to reproduce let us know.  Just to confirm, do you remember what version of Atom you were running when it happened?

**Comment by joedski** [comment]
It was on either 1.21.0 (current stable) or the version before that.  I remember it occurring pretty recently.

At present, `atom --version` gives this:

```
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

Will try to find steps to repro if I can!

**Comment by p0lm** [comment]
A few additions that might help reproducing:

* Only occurs on splitting panes horizontally
* Only occurs after third or fourth split
* Currently hacked a fix by adding `.lines { padding-left: 2px }` to my styles.less
* Problem persists on switching tabs or splitting vertically

**Comment by rsese** [comment]
Finally had a chance to try this on my Ubuntu VM and on macOS (I used the Fonts package to use the Terminus font in both cases).  This is how I tried to repro @p0lm, can you let me know if this matches your steps?

![text-render](https://user-images.githubusercontent.com/734194/31529573-a854c3e8-af9f-11e7-9cb2-1ac4e2563712.gif)

If not can you share a GIF/screencast of your repro?

**Comment by p0lm** [comment]
Doh. I meant split vertically. So the new pane is to the right. Sorry.

**Comment by p0lm** [comment]
I finally got around to screencasting this:

![screencast](https://thumbs.gfycat.com/ImmediateRashIslandcanary-max-14mb.gif)
