### ISSUE TITLE
Atom 'Install Shell Commands' links atom instead of atom.sh

### ISSUE THREAD

**Issue by waveclaw** [atom/atom#15857]
### Description

Atom 'Install Shell Commands' links atom instead of atom.sh

### Steps to Reproduce

1. Remove /usr/local/bin/atom
2. Open Atom from the GUI icon or from atom.sh (e.g. /Applications/Atom.app/Contents/Resources/app/atom.sh on Mac OS X)
3. Select File -> Install Shell Commands
4. In a terminal check /usr/local/bin/atom
`ls -l /usr/local/bin/atom`

**Expected behavior:**

The atom command line tool is expected to link to atom.sh.

**Actual behavior:** 

The atom command line tool links to the atom binary. Subsequent terminal invocation of atom to fail with errors like #10278.

```
/bin/bash-886>atom ./
2017-10-10 09:14:07.682 atom[1478:13872] *** Assertion failure in +[SQRLDirectoryManager currentApplicationManager], /Users/joshaber/Documents/Development/GitHub/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30
```
**Reproduces how often:** 

Always.

### Versions

Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
maOS Sierra: 10.12.6

### Additional Information

This has occurred since atom 1.18.0 and onward.

**Workarounds**

Remove the link and recreate it correctly:

`sudo ln -s -f /Applications/Atom.app/Contents/Resources/app/atom.sh /usr/local/bin/atom`

**Comment by damieng** [comment]
Just tried removing my atom link and using the Atom menu to reinstate it, looks correct;

```
 ls -l atom
lrwxr-xr-x  1 damieng  admin  70 Oct 13 11:09 atom -> /Users/damieng/Source/atom/out/Atom.app/Contents/Resources/app/atom.sh
```

Code also looks correct; https://github.com/atom/atom/blob/master/src/command-installer.js#L44

If you are able to reproduce this error please respond to this issue and I'll reopen it.
