### ISSUE TITLE
Uncaught Error: GitTabController instance is not associated with a valid virtualNode. Perhaps thi...

### ISSUE THREAD

**Issue by shemerey** [atom/atom#15855]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: GitTabController instance is not associated with a valid virtualNode. Perhaps this component was never initialized?

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:100

Error: GitTabController instance is not associated with a valid virtualNode. Perhaps this component was never initialized?
    at updateSync (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:100:17)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:72:13
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:187:15)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/view-registry.js:3:65
```

### Commands

```
     -0:12.9.0 project-manager:list-projects (div.tool-panel.tree-view)
  2x -0:11.4.0 core:move-down (input.hidden-input)
     -0:10.5.0 core:confirm (input.hidden-input)
     -0:04.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
busy-signal 1.4.3 
cursor-history 0.12.0 
go-debug 1.5.2 
go-plus 5.5.5 
go-rename 0.3.0 
go-signature-statusbar 1.2.3 
hyperclick 0.1.5 
ide-go 0.4.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
project-manager 3.3.5 
script 3.16.0 
significant-other 0.3.0 
toggler 0.3.0 
vim-mode-plus 1.9.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by wpiprox** [comment]
Hi,

I get the same error here.
It happens systematically when switching project using project-manager package, the error message appear and I cannot use any git feature afterwards.
I cannot reproduce in safe mode as this package is deactivated then and reopening a project results in opening a new atom window when in safe mode.

It might be related to the fact that project-manager loads the project without opening a new window, so perhaps is it more of a project-manager issue.

Note that reloading the window with Ctrl+Shift+F5 after switching project solves the problem.

**Comment by rsese** [comment]
Thanks @wpiprox, it looks like @shemerey also uses project-manager.  Can you share exact steps to reproduce?  Also, since the issue seems at least related to project-manager, I'd suggest opening an issue in their repository as well.  The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by wpiprox** [comment]
There are 2 ways I can reproduce:
- Open atom
- Switch project with the dedicated shortcut provided by project-manager package
- Switch one more time

or

- Open atom
- Open a file in the current project
- Switch project with the dedicated shortcut provided by project-manager package

I'll open an issue in the package repository as well.

**Comment by neumannrf** [comment]
I can confirm that when I switch projects using the package manager extension the same error happens to me. However, if I `Shift+Enter` the project that I want to open (in order to open it in a new window), the error does not happen.

**Comment by maxmoeschinger** [comment]
I also get this error

**Comment by Jeremiahgibson** [comment]
I'm seeing this error as well when I use shift-enter to open a project using atom project manager.

**Comment by eevargas** [comment]
I get this error as well when switching projects using atom project manager. I causes git integration to break until I restart Atom. 

![image](https://user-images.githubusercontent.com/5521167/32968068-8751492e-cba5-11e7-81e4-a334011c04e3.png)

**Comment by srilq** [comment]
I have the exact same error regardless of if I'm using [atom-project-manager](https://github.com/danielbrodin/atom-project-manager) or [atom-project-plus](https://github.com/mehcode/atom-project-plus). I'd wager it's a bug in atom, not either of these packages.

**Comment by srilq** [comment]
Here is some additional context:

atom version: 1.23.3 (also seen on many previous versions)
macOS version: 10.13.3 (also seen on a different machine on latest 10.12)
git version: 2.14.3 (Apple Git-98)

Installed packages at time of writing:
https://raw.githubusercontent.com/srilq/dotfiles/6ab26aacb26c627b63396caeebbb171900fd212a/atom.symlink/packages.txt

Other config in `~/.atom` at time of writing:
https://github.com/srilq/dotfiles/tree/6ab26aacb26c627b63396caeebbb171900fd212a/atom.symlink

STEPS TO REPRO:

* Get a fresh atom install (and delete `~/.atom`)
* Download the files in `atom.symlink` at [the above link](https://github.com/srilq/dotfiles/tree/6ab26aacb26c627b63396caeebbb171900fd212a/atom.symlink) and copy them into fresh `~/.atom`. [[Download ZIP]](https://github.com/srilq/dotfiles/archive/6ab26aacb26c627b63396caeebbb171900fd212a.zip)
* Run `apm install --production --compatible --packages-file ~/.atom/packages.txt`
* Run `mkdir -p ~/src/project1 && mkdir -p ~/src/project2`
* Create `~/.atom/projects.cson` with the following contents:
  ```
  [
    {
      title: "project1"
      paths: ["~/src/project1"]
    }
    {
      title: "project2"
      paths: ["~/src/project2"]
    }
  ]
  ```
* Open atom
* Run from command panel: `Project Plus: Toggle Project Finder`
* Select `project1`
* Run from command panel: `Project Plus: Toggle Project Finder`
* Select `project2`

This should not be difficult to reproduce but the above should work 100% so there is no ambiguity. 👍

**Comment by rsese** [comment]
I had some trouble trying to use project-manager, @srilq can you share steps to reproduce with project-plus?

**Comment by srilq** [comment]
@rsese if you have a `~/.atom/projects.cson` with this for example:

```cson
[
  {
    title: "git-project1"
    paths: ["/Users/sril/src/project1"]
  }
  {
    title: "git-project2"
    paths: ["/Users/sril/src/project2"]
  }
]
```

1. Command: `Application: New Window`.
2. Command: `Project Plus: Toggle Project Finder`
3. Select `git-project1`
4. Press Enter
5. Command: `Project Plus: Toggle Project Finder`
6. Select `git-project2`
7. Press Enter

It's not 100% reproducible, but it has happened to me several times every day for 6+ months (with both `atom-project-manager` and `atom-project plus`. I "fix" it by reloading the window. I have experimented for a long time and have never found a 100% repro. There appear to be some race conditions here.

Video: https://drive.google.com/file/d/1Zzyh_S652FvNDJJ791UyO5ohmTrmTYM0/view?usp=sharing

**Comment by cbovis** [comment]
I'm experiencing this in the exact same way @srilq is describing. Happens irregularly, multiple times per day.
