### ISSUE TITLE
On Windows 7 x64, the command `atom -n .` does not open the current folder in a new atom window. 

### ISSUE THREAD

**Issue by subhrm** [atom/atom#15853]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On Windows 7 , the command `atom -n .` does not open the current folder in a new atom window. 

### Steps to Reproduce

1. Open `Comand promt` or `powershell` 
2. Navigate to a folder using `cd` command[s]
3. Type `atom -n .`

**Expected behavior:**  
A new atom window should appear with the current folder open in the left-hand side Project pane.

**Actual behavior:** 

A new atom window appears, but with the folder `C:\Users\<user>\AppData\Local\atom\app-1.21.0` open in the project pane.

**Reproduces how often:**  

Always

### Versions

OS : Windows 7 Enterprise SP1 64 bit

The command `atom --version` does not produce any output in the command line.  

`Help > About Atom` shows that the installed version is `1.21.0 x64` . 

    D:\path>apm --version
        apm  1.18.5
        npm  3.10.10
        node 6.9.5 x64
        python 3.5.4
        git 2.9.0.windows.1
        visual studio 2013

**Comment by damieng** [comment]
Unable to repro here on master on Windows 10 64-bit.  Behaves exactly as user desired.

**Comment by aae42** [comment]
this works fine in my command line, just doesn't work in powershell
