### ISSUE TITLE
Toggle line comments on blank line indents incorrectly

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#15850]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The `editor:toggle-line-comments` command has broken for blank lines in Atom v1.22.0-beta0, it's starting the comment at the beginning of the line instead of at the proper indentation level.

### Steps to Reproduce

1. Have indented code
2. Go to a new line
3. Trigger `editor:toggle-line-comments`

**Expected behavior:**

Comment starts at the proper indentation.
![2017-10-09_11-52-22](https://user-images.githubusercontent.com/427137/31353687-5a26bb7c-ace8-11e7-9510-acd0a26a5074.gif)
(Atom v1.21.0)

**Actual behavior:**

Comment starts at the beginning of the line with no indentation.
![2017-10-09_11-57-11](https://user-images.githubusercontent.com/427137/31353861-04e0ace4-ace9-11e7-8fb6-13940a0be4d4.gif)
(Atom v1.22.0-beta0)

**Reproduces how often:**
100% of the time.

### Versions

Broken:
```
Atom    : 1.22.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

Working:
```
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by Ben3eeE** [comment]
I believe this was fixed by https://github.com/atom/atom/pull/15799

/cc: @maxbrunsfeld Should we hotfix this?

**Comment by maxbrunsfeld** [comment]
> Should we hotfix this?

Yes. Thanks for reminding me!

**Comment by maxbrunsfeld** [comment]
Sorry for this. This will go out in our next Beta hotfix.

**Comment by Arcanemagus** [comment]
No problem, that's what betas are for 😉.

**Comment by AlexWayfer** [comment]
Great, now it's indent with spaces, ignoring tabs :expressionless: 

Should I create the new issue?

**Comment by AlexWayfer** [comment]
I've created #16193 :man_shrugging:
