### ISSUE TITLE
Installer uses default .NET WinForms icon

### ISSUE THREAD

**Issue by Daniel15** [atom/atom#15874]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Noticed this in the taskbar while installing Atom:

![](https://ss.dan.cx/2017/10/chrome_12-15.51.48.png)

This is the default .NET WinForms icon that appears when you forget to set the icon for an app 😄 

### Steps to Reproduce

1. Install Atom on Windows 10

**Expected behavior:** [What you expect to happen]
Installer uses Atom icon

**Actual behavior:** [What actually happens]
Installer uses default .NET icon

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Microsoft Windows [Version 10.0.15063]
```
```
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by rsese** [comment]
Thanks for this report as well @Daniel15 :v:

x-ref: https://github.com/Squirrel/Squirrel.Windows/issues/1146

**Comment by damieng** [comment]
Was fixed in latest squirrel update.
