### ISSUE TITLE
Installer image doesn't appear correctly on Windows

### ISSUE THREAD

**Issue by Daniel15** [atom/atom#15873]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Image in the installer appears very pixelated, at half the size it's supposed to appear:
![](https://ss.dan.cx/2017/10/chrome_12-15.50.05.png)

### Steps to Reproduce
1. Install Atom 1.21.0 on a high-DPI Windows laptop (eg. Lenovo X1 Yoga)

**Expected behavior:**
Installer image is nice

**Actual behavior:**
Installer image is pixelated

**Reproduces how often:** 
100% on high-DPI screen

### Versions
```
Microsoft Windows [Version 10.0.15063]
```
```
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by rsese** [comment]
@ungb @Ben3eeE - my Windows laptop (and secondary monitor) doesn't have a high DPI screen, do either of you have a high DPI screen?

**Comment by rsese** [comment]
Thanks for the nudge to look through Squirrel issues Linus :v:

x-ref: https://github.com/Squirrel/Squirrel.Windows/issues/357

**Comment by Daniel15** [comment]
I think this was okay in older releases, but maybe I'm wrong and it's
always been broken. Not sure.

**Comment by Ben3eeE** [comment]
@Daniel15 No you are right. We updated Squirrel in Atom 1.21 which caused this. It doesn't look correct for me and I am not on a high DPI screen.

**Comment by Ben3eeE** [comment]
The update included https://github.com/Squirrel/Squirrel.Windows/commit/63512c7309a07305a639abbd10aeb0b16d73aba1 which sounds related.

**Comment by damieng** [comment]
https://github.com/Squirrel/Squirrel.Windows/issues/1161 is the issue.

Once that is fixed we can bump up to take it.

**Comment by Daniel15** [comment]
Just confirmed that it's not specific to High-DPI screens, I saw the same issue on my regular screen.

**Comment by damieng** [comment]
Previously reported at https://github.com/atom/atom/issues/15724 - we'll keep this one open to track the upstream fix.

**Comment by Ben3eeE** [comment]
Closing this one since it looks like it has been fixed. @damieng Please reopen in case I am wrong ✨
