### ISSUE TITLE
Uncaught Error: Can't save a buffer with no file

### ISSUE THREAD

**Issue by acidicirontooth** [atom/atom#15870]
[Enter steps to reproduce:]

1. ... Created new file with CTRL-N
2. ... Entered a bit of data
3. ... Hit CTRL-S and named it
4. ... Error

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Can't save a buffer with no file

```
At /usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1240

Error: Can't save a buffer with no file
    at TextBuffer.module.exports.TextBuffer.saveTo (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1240:21)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1224:25)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:1004:32)
    at /home/user/.atom/init.coffee:18:18
    at /home/user/.atom/init.coffee:15:7
    at CallbacksRegistry.apply (/usr/share/atom/resources/electron.asar/common/api/callbacks-registry.js:48:42)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/electron.asar/renderer/api/remote.js:299:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
 33x -1:47.9.0 core:move-up (input.hidden-input)
 46x -1:46.3.0 core:move-down (input.hidden-input)
     -1:42.3.0 core:move-up (input.hidden-input)
     -1:41.9.0 core:move-down (input.hidden-input)
 48x -1:41.4.0 core:move-up (input.hidden-input)
 76x -1:36.3.0 core:move-down (input.hidden-input)
 43x -1:14.5.0 core:move-up (input.hidden-input)
 50x -1:11.6.0 core:move-down (input.hidden-input)
 44x -1:09.4.0 core:move-up (input.hidden-input)
 34x -1:07.3.0 core:move-down (input.hidden-input)
 10x -1:05.5.0 core:move-up (input.hidden-input)
     -0:48.5.0 application:new-file (input.hidden-input)
     -0:46 core:save (input.hidden-input)
     -0:41.4.0 editor:newline (input.hidden-input)
     -0:36.7.0 core:move-right (input.hidden-input)
     -0:32.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.13 
geiger 2.1.0 
standard-formatter 2.8.0 
todo-show 2.1.0 
```

**Comment by rsese** [comment]
Thanks for the report - I see your init script mentioned in the stack trace, can you share that so we can take a look?  And to check if that's what causing the error, can you confirm if you can reproduce in safe mode?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

In safe mode, your init script won't be loaded.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment [insert URL here]. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by richardsimko** [comment]
I just stumbled across this. The issue appeared for me when following the steps mentioned in the ticket, however with the addition of having the snippet of code for auto save on lost focus from this [thread](https://discuss.atom.io/t/save-on-focus-lost/2555/11):

```js
atom.getCurrentWindow().on 'blur', ->
  for pane in atom.workspace.getPanes()
      for item in pane.items
        if atom.workspace.isTextEditor(item)
          if item.isModified?
            item.save() if item.isModified()
          else
            item.save()
```

That thread is among the top results when searching for "atom save on lost focus" and similar so it's possible that a lot of people are using it. Could you recommend a good way of catching this error in this case or checking that there is a file?

**Comment by 50Wliu** [comment]
You should check that [its path](https://atom.io/docs/api/v1.21.1/TextEditor#instance-getPath) is non-empty.

**Comment by richardsimko** [comment]
Thanks! In case anyone stumbles upon this issue the same way I did, here's the script I'm using now:

```js
atom.getCurrentWindow().on 'blur', ->
  for pane in atom.workspace.getPanes()
      for item in pane.items
        if atom.workspace.isTextEditor(item) && item.getPath()
          if item.isModified?
            item.save() if item.isModified()
          else
            item.save()
```
