### ISSUE TITLE
Document opens in wrong atom window

### ISSUE THREAD

**Issue by craigpfeifer** [atom/atom#15876]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using multiple Atom windows, opening a document (via File->Open or dragging from finder into a window) causes it to open in the first window, never in any of the other windows. 

### Steps to Reproduce

1. Start ATOM
2. Open a document in the window
3. Open a new window
4. drag a document to the new window to open it

**Expected behavior:** [What you expect to happen]

I expect the document to open in the window that I drag it to/open it from.

**Actual behavior:** [What actually happens]

The actual behavior is all documents open in the first atom window, regardless of which window the document is dropped onto.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

$ atom --version
Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.2

MacOS Sierra, 10.12.6

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!

> I expect the document to open in the window that I drag it to/open it from.

I believe this is the case if the file you're opening isn't part of the same project from your step 2.  If I follow your steps to reproduce but in step 4 open a file that lives in some other project/directory, it will open in the new window from your step 3.  Otherwise, if the file belongs to the same project, it will open in that project window.

We have a high level issue about the confusion around the different ways Atom launches so we'll close this in favor of that issue /cc #10517.

**Comment by craigpfeifer** [comment]
You are entirely correct, thanks for the prompt attention to my issue. I
didn't realize the distinction around projects. I keep a lot of my project
notes in the same directory, so they are probably in the same "project" and
that explains the problem I'm having.

I'd be happy to contribute use cases & test sample builds around this if
that would help.

Thanks again,

Craig

**Comment by rsese** [comment]
Thanks @craigpfeifer 👍  It does sound like you're running into the project behavior I described.

The team definitely sees how the different ways of starting Atom could be more clear (hence that issue I referenced) so feel free to subscribe to https://github.com/atom/atom/issues/10517 if you'd like.
