### ISSUE TITLE
running Atom on `arm64`

### ISSUE THREAD

**Issue by othiym23** [atom/atom#15881]
/cc @vanessayuenn, @kuychaco, @groundwater, @zcbenz

Here are the takeaways from a hack week that I and the above-linked folks did recently to get Atom up and running on an [`arm64` laptop](https://www.pine64.org/?page_id=3707). Towards the end there's a checklist of tasks that would need to be done to take our hacked-up build and turn it into a first-class member of the Electron / Atom commons.

### building Atom on and for `arm64`

The current Electron build infrastructure is designed to make it quick for end-user developers to assemble apps. Many pieces that are built at the same time (mostly as part of [`electron/libchromiumcontent`](https://github.com/electron/libchromiumcontent)) are packaged separately and then pulled together using package scripts that run downloaders at npm / yarn install time, because some or all of them may be unnecessary for some applications. This makes bootstrapping new architectures tricky, because it's difficult to build and incorporate those components incrementally, without bootstrapping the entire infrastructure.

In addition, Google _really_ wants anything ARM-related to be cross-compiled instead of built on ARM devices directly. (A pity, because @groundwater found a [really awesome and cheap](https://packet.net) service that rents out 96-core `arm64` servers.) With the exception of `armv7l` builds, which are special in other ways, cross-compilation isn't done for official Electron builds.

For example, `mksnapshot` is necessary to build the snapshot that is, by default, _required_ for the core Atom UI modules to be loaded into the editor (to get Atom running on `arm64`, because we couldn't get snapshotting working with our ARM frankenbuild, @zcbenz had to produce a one-off version of the Atom [ASAR](https://github.com/electron/asar) that includes the JavaScript that normally would have been compiled into the snapshot), and because it generates partially-compiled code meant to be consumed directly by a specific version of V8, is difficult to build without knowing the settings after the fact.

We used `gn` to build `arm64`-native and cross-targeted `linux-x64` builds of `mksnapshot` (that could be built using `ninja` instead of dealing with `gyp`). Neither produced a blob for V8 that worked, even though I'm pretty sure we had matching versions of V8. Using a `mksnapshot` built from the same tree as the rest of `libchromiumcontent` and `v8` would probably solve this
problem.

### packages built from Google's tree(s) in the frankenbuild

1. `electron` was built locally (from a `1.6.x` tree) instead of being pulled from the GH releases page, and required patches to be made to the installed copies of `electron-packager` and `electron-download`.
1. `dump_syms`, which is used by `minidump`, and is a part of `breakpad`, depends on a set of macros that need to have support for whatever ARM64 compiler pragma indicates the platform added to the include files.
1. `mksnapshot` is hosted on `atom/atom`; isn't built for `arm64`.
1. `chromedriver` is hosted on `atom/atom`; isn't built for `arm64`.

### hacks done to work around the preceding

1. A newer version of `electron-packager` that knows about `arm64` is required; update `package.json` to `electron-packager@9.1.0`.
1. `chromedriver` is only used for tests, and isn't available from the `electron/electron` Releases page for `arm64` (yet). Remove it from `package.json`.
1. Until the `dump_syms` issue is resolved, all of the crash reporter infrastrucure needs to be disabled (and `minidump` needs to be removed from `package.json`).
1. `mksnapshot` needs to be commented out; it's possible to build a natively-hosted version for arm that can be used in the build process, but until we can figure out how to get it to work, it just slows down the build without doing anything useful. `electron-mksnapshot` also needs to be removed from `package.json`.
1. The Atom ASAR needs to be built by hand to include the assets that would otherwise be compiled into the snapshot. Without this, Atom is a sad panda. All credit to @zcbenz for figuring this out.

## steps necessary to make `arm64` a first-class Electron citizen

- [ ] Modify Electron's build system to support cross-compilation. I'd be interested to hear from anyone at Google about how many of their own Chromium builds are cross-compiled; I suspect it's a far higher percentage than are currently done for either Electron or Atom.
- [ ] Alternatively, figure out why `mksnapshot` is specifically configured to not be compiled for native builds of chromium / libchromiumcontent in the GN configuration.
- [ ] Produce `arm64` release builds of `electron`, `breakpad`, and `electron-mksnapshot`. This is more than just modifying the build infrastructure; some of the native code needs to be modified to know about `arm64` and `arm64-linux` pragmas in things like header files. The changes are pretty simple and mostly just involve cut and paste, but they're scattered all over the place, so some care is required.

## steps necessary to make `arm64` a first-class platform for Atom
- One of:
  - [ ] Get `mksnapshot` working on `arm64`, either natively or via cross-compilation (cross-compilation is preferred, because then CI could produce the snapshot without requiring an ARM build machine).
  - [ ] Replace the Atom bootstrap that uses the snapshot with putting those same files in the ASAR, either specifically for `arm64` or in general. CPU cycles aren't cheap on the pine64 machines, but once Atom's up and running, its performance is at least acceptable, so this may be a worthwhile workaround until snapshotting can be made to work.

Some or all of the above could be turned into freestanding issues, once the determination is made to move forward with `arm64` / supporting the pinebook.

Also, if left to my own devices, I'd probably make some changes to Atom's build system to rely less on a monolithic builder script and more on a more cleanly-factored set of package scripts called from `package.json`, but that ventures onto the shaky ground of yak shaving and is best discussed elsewhere.

Hack week friends, what am I forgetting?

**Comment by 50Wliu** [comment]
See also #7822

**Comment by JBKingdon** [comment]
Thanks for writing this up. I just started down this path and found this issue when I started searching for answers to the immediate problems :)
+1 for arm64 support, atom on pinebook would be awesome.

**Comment by Pofilo** [comment]
+1 for the functionnality.
