### ISSUE TITLE
build error: download-chromedriver.js fails

### ISSUE THREAD

**Issue by cnd** [atom/atom#15885]
download-chromedriver.js:16
  if (error != null) throw error
                     ^

Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:606:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.6.0 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

version: 1.22.0 beta1

**Comment by damieng** [comment]
Are you on Windows?  If so can you type;

`set processor_identifier` 

and paste the output here?

**Comment by mpkh** [comment]
@damieng no, linux

**Comment by damieng** [comment]
`cat /proc/cpuinfo | grep -e model -e flags`
