### ISSUE TITLE
TrendMicro Identifies Atom as having HEU_AEGISCS_Malicious Virus

### ISSUE THREAD

**Issue by lucanos** [atom/atom#15897]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Trend Micro Maximum Security's Real Time Scan reports atom.exe contains HEU_AEGISCS_Malicious virus and removes the application.

### Steps to Reproduce

1. Install Atom
2. Install Trend Micro Maximum Security
3. Run Trend Micro Scan

**Expected behavior:** Unsure whether this is a false positive report or a true issue

**Actual behavior:** Trend Micro Maximum Security removes the atom.exe file, preventing Atom from running

**Reproduces how often:** Every time. Reinstalled Atom and same issue reoccurred.

### Versions

Latest Windows version available for download as at 14 Oct 2017

### Additional Information

Attempts to whitelist the file are useless - the file returns, Trend Micro advises that it is whitelisted, then when it is executed, Trend Micro detects an issue and once again deletes the file.

Tested atom.exe through VirusTotal with one engine reporting issue - https://www.virustotal.com/#/file/0f18b0fa16a4f4e1a4bf6b12ec4182a0d8d2e950da9410fa74fe8b2a83389597/detection

**Comment by 50Wliu** [comment]
@lucanos Sorry for the trouble - this is a false positive.  We updated one of our libraries recently and some antiviruses have taken issue with that.  Since Atom is open-source, you can manually verify that it is not a virus :).  I would advise telling TrendMicro that it's a false positive so that they can update their definitions.
