### ISSUE TITLE
Uncaught (in promise) TypeError: get_document(...).createElement is not a function

### ISSUE THREAD

**Issue by guilhermep** [atom/atom#15907]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Can't load atom core package for development.

### Steps to Reproduce

1. `git clone https://github.com/atom/atom.git`
2. `cd atom`
3. `apm link -d`
4. `atom --dev`

Also tried `apm install`.

**Expected behavior:** Atom to load.

**Actual behavior:**
![2017-10-16 16-59-36](https://user-images.githubusercontent.com/3932327/31630322-064197ea-b295-11e7-8ff8-c4118c608c46.png)

**Reproduces how often:** Every time.

### Versions

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
Ubuntu 16.04.03

**Comment by 50Wliu** [comment]
Atom itself is not a package, therefore you aren't supposed to run `apm link -d` on it.  Set `ATOM_DEV_RESOURCE_PATH` to where your Atom git repository is located, execute `script/build --install`, and then run `atom -d`.
