### ISSUE TITLE
Cursor disappears on column 80

### ISSUE THREAD

**Issue by pdonias** [atom/atom#15911]
The cursor *sometimes* disappears when it's at the "Preferred Line Length" position.
![cursor](https://user-images.githubusercontent.com/10992860/31657437-a6411c4a-b32e-11e7-8b0b-74d7a9fe9f24.gif)
I can tell it depends on the selected grammar and on the content of the line but couldn't figure out a list of conditions that make the bug occur.

Here is a simple example to reproduce it:
- 1 line file with 100 '*' characters
- Grammar: JavaScript
- Preferred Line Length: 80
- Place cursor on column 80

Atom 1.21.1 on Ubuntu 17.04

**Comment by Ben3eeE** [comment]
Because the wrap-guide is rendered above the cursor?

**Comment by pdonias** [comment]
After further investigation, it seems to be an issue with the syntax theme I use ([Outlander](https://github.com/mthadley/outlander-syntax)). Closing it, sorry for the useless issue.
