### ISSUE TITLE
Snapping causes strange behavior.

### ISSUE THREAD

**Issue by BenjaminHolland** [atom/atom#15910]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using the ctrl-?-arrow combinations to resize and snap the window, the Atom window can enter a state where the size of the window collapses into invisible single pixel strips. While it's possible to resize the window to a "normal" size, maximizing the window causes it to collapse again. 
### Steps to Reproduce

1. Snap the atom window to the sides and top until problem occurs.

**Expected behavior:** The window should be hidden completely, maximized, or snapped to a side of the screen. Maximizing the window should cause the window to fill the available screen.

**Actual behavior:** [What actually happens]
The window collapses into what seems to be the smallest possible dimension. Maximizing the window after resizing causes the window to collapse again.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0

Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!  I'm unable to reproduce on Ubuntu 16.04 with Atom 1.21.0 - can you share a GIF or screencast of the behavior?  

> Reproduces how often: [What percentage of the time does it reproduce?]

How often does it reproduce for you? 

Lastly, did you just see the behavior starting in 1.21.0 but not in previous versions?

**Comment by BenjaminHolland** [comment]
I can try to show screenshots, but I don't know how to screencast or gif my
screen. If you've got instructions  id be willing to try.

I'mt sure it's releavnt, but this is a guest on a windows machine using
virtualbox. I could potentially send someone the image with a bit of
cleanup.

As for the version, I haven't used any other versions, so i couldn't check.

**Comment by BenjaminHolland** [comment]
also, it reproduces consistently on my end.
