### ISSUE TITLE
Filesystem Watcher API fails on network drives

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#15919]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The `Native operating system APIs` File system watcher selection fails to detect file changes when the file resides on a network drive.

### Steps to Reproduce

1. Have Atom set to use the native operating system APIs to watch for file changes.
2. Create a folder on a network drive and initialize a `git` repo with a commit in the folder.
3. Open the folder in Atom.
4. Make a change to the file and save it.

**Expected behavior:**
Atom's File system watcher API detects the change.

**Actual behavior:**
The File system watcher API doesn't detect the change unless it is emulated using Atom events. The `github` package's built in File system watcher debugging was used to illustrate this here:

![2017-10-17_11-31-38](https://user-images.githubusercontent.com/427137/31682667-a2f1a00e-b32f-11e7-9abe-c483fa4eb51f.gif)

**Reproduces how often:**
100% of the time.

### Versions

```
Atom    : 1.22.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.2.windows.3
visual studio
```

OS: Windows 10 x64 Enterprise

**Comment by smashwilson** [comment]
Yah, the filesystem watching library we're using doesn't always work on network shares. The replacement I'm working on now _should_ gracefully fail back to throttled polling in these situations, but it's hard to say how well-behaved any specific filesystem will behave :smile:

Would you mind if I pinged you on an issue to test it out with your specific share once it's closer to ready?

**Comment by Arcanemagus** [comment]
Of course! Feel free to bug me on Slack any time 😉.

**Comment by Arcanemagus** [comment]
Doing some further testing with `@atom/watcher` it seems that this file system reports file creation and deletion events, but renames and modifications aren't reported.
