### ISSUE TITLE
File menu in title bar in Ubuntu16.04

### ISSUE THREAD

**Issue by steviesama** [atom/atom#15914]
I haven't a clue how to reproduce it except to say when I launch Atom with sudo, the menu bar behaves like I'd expect on Mac or Windows. It's either below the title bar, or hidden and alt will make it pop up (on Ubuntu alt is used for the dashboard so I can't use that).

If I launch it normally and the window is maximized but not fullscreen, the menu bar is inside of the title bar, directly to the right of the widgets such as close, maximize, etc. My question is...how do you reproduce this behavior if it happens to be disabled...I've never seen it before?

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Seems permissions-related if things work ok when you run with `sudo`?  Can you temporarily reset to factory defaults and see if that helps?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

As a side note, please fill in and use the issue template as much as possible, it's super helpful for us when looking at issues.  Please share what version of Atom you're running (`atom -v`) and if you can share a screenshot of what you see when starting Atom without `sudo`, that could be helpful too.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15914#issuecomment-337385522. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
