### ISSUE TITLE
fails to build on Linux because 'python' references 'python3', and `python-interceptor.sh` hardwires calls to `python`

### ISSUE THREAD

**Issue by yarko** [atom/atom#15925]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is still a problem on ubuntu (but probably generically):

I solved, and the issue seems to be centered in `apm/node_modules/atom-package-manager` in the shell script `python-interceptor.sh`  lines 37 & 40  (explicit call of `python`).

The problem is `python` is the default python, which increasingly will be python3  (currently python3.6, python3.6.3), and _not_ python2.

To quickly hack / see that this is the issue, changing those as shown here:
```
$ pwd; grep -n -i python python-interceptor.sh 
/home/yarko/workspace/atom/atom/apm/node_modules/atom-package-manager/bin
7:    export PYTHONPATH="${PYTHONPATH:-}:${SCRIPT_DIR}/../src/generator/"
37:    exec python2 "${ARGS[@]}"
40:    exec python2 "$@"
```
results in a successful build.

It would seem that one possible solution is to (somewhere) set an environment variable, e.g.
```
$ export PYTHON=python2
```
and fix `python-interceptor.sh` lines (above) to call $PYTHON.

Alternatively, and simply, `python-interceptor.sh`  can set PYTHON (by default) to be `python2`, since that should be valid for any installation with a python version 2 installation.

### Steps to Reproduce

1. This was a build on Ubuntu 16.04 LTS, with locally built pythons - 3.6 and 3.7a in /usr/local/bin
2. attempt build per instructions, including `npm config set python /usr/local/bin/python2 -g`

**Expected behavior:**
Successful build;

**Actual behavior:**
Error in python-intercept.sh (complaint about python version 3.6.3).

**Reproduces how often:**
Always.

### Versions
master / HEAD

**Comment by 50Wliu** [comment]
@smashwilson I thought you fixed this?

**Comment by smashwilson** [comment]
So did I!

My original fix was atom/apm#713 which shipped in apm 1.18.6, and there was a follow-on bugfix in atom/apm#748 that shipped in 1.18.8.

Atom's master branch as of d6a3a60469 is using [apm 1.18.8](https://github.com/atom/atom/blob/d6a3a604695df62a7b813bd229316042a501aee5/apm/package.json#L9), as is [the Atom 1.22 release branch](https://github.com/atom/atom/blob/1.22-releases/apm/package.json#L9). 1.21 is only using [1.18.5](https://github.com/atom/atom/blob/1.22-releases/apm/package.json#L9) though.

@yarko Can you confirm what versions of Atom and apm you're running, with `atom --version` and `apm --version`? That will tell us which master commit you're running and which apm you have installed.

**Comment by villamide** [comment]
I made a workaround and was able to build it on Arch Linux:
`
$   mv /usr/bin/python /usr/bin/python.bak
$   ln -s /usr/bin/python2 /usr/bin/python
`
And undo the changes after build

**Comment by alflanagan** [comment]
You need to be _really_ careful about renaming your system Python! A _lot_ of basic Linux functionality is now implemented in Python, and it's surprising what will break when you do that. 

`python-intercepter.sh` needs to be fixed, but the _real_ fix is for [node-gyp](git@github.com:nodejs/node-gyp.git) to either support python 3 or stop using python entirely. Unfortunately nothing seems to be happening there.

**Comment by jasonbridges** [comment]
Try
`ln -s $(which python2) python
export PATH=$PWD:$PATH`

**Comment by MattOates** [comment]
Why are their suggestions of people altering their local environment?! Just edit Atom itself, it's just a shell script that stupidly assumes `python` in a local environment means a compatible python 2. Minimally that should be changed to `python2` which worked for me to locally resolve anything depending on gyp from being blocked on install.

**Comment by twifty** [comment]
I had a similar problem with python while building atom v1.26 on Manjaro Linux 4.14

I `export PYTHON=/usr/bin/python2` but for some reason `node-gyp` was looking for `/usr/local/bin/python2`. I verified the file exists and checked my sanity with `printenv`. The only solution was to create a link at `/usr/local/bin/python2 -> /usr/bin/python2`.

Regardless, I still get build errors "Cannot read property 'localeCompare' of null" followed by  "Error: Unable to find the "dump_syms""

**Comment by ioquatix** [comment]
I used to be able to fix this problem by running `apm config set python python2.7`. However, somewhere in the past 12 months, this has stopped working. After running that command, the change is not applied. When I run `apm config list` it shows 

```
> apm config list
; cli configs
globalconfig = "/Users/samuel/.atom/.apm/.apmrc"
user-agent = "npm/3.10.10 node/v6.9.5 darwin x64"
userconfig = "/Users/samuel/.atom/.apmrc"

; environment configs
node-gyp = "/Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp"
python = "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh"

; globalconfig /Users/samuel/.atom/.apm/.apmrc
cache = "/Users/samuel/.atom/.apm"
progress = false
```

What's going on? This used to work.

**Comment by ioquatix** [comment]
The problem is this line: `https://github.com/atom/apm/blob/60b1efd07345f41e9c6263788bb52287f48aa0a7/bin/apm#L53`

When I removed that line from my local install, my user config was recognised immediately.

```
> apm config list 
; cli configs
globalconfig = "/Users/samuel/.atom/.apm/.apmrc"
user-agent = "npm/3.10.10 node/v6.9.5 darwin x64"
userconfig = "/Users/samuel/.atom/.apmrc"

; environment configs
node-gyp = "/Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp"

; userconfig /Users/samuel/.atom/.apmrc
python = "python2.7"
```

It seems like that line is taking precedence over user specified config. That's a problem and it's a breaking change to how it used to work.

**Comment by BenRussert** [comment]
What if we tried to call `python2` explicitly [here](https://github.com/atom/apm/blob/master/bin/python-interceptor.sh#L37:L40) and fall back to `python`?

**Comment by ioquatix** [comment]
The amount of crap being piled on to work around `node-gyp` is astounding. The right solution is just to make it work with Python 3.

**Comment by 50Wliu** [comment]
If you're referring to `node-gyp`, I don't think that's possible as `gyp` only works with Python 2.  As far as I know, Chromium isn't supporting gyp anymore as they've moved to `gn`.

**Comment by ioquatix** [comment]
Then perhaps `node-gyp` should be deprecated and projects that use it updated to use something else? I know that's outside of the scope of this issue, but ultimately Python2.7 is EOL. I don't know why `apm` includes cruft to work around upstream issues.

**Comment by thomasjo** [comment]
> Then perhaps node-gyp should be deprecated and projects that use it updated to use something else? I know that's outside of the scope of this issue, but ultimately Python2.7 is EOL. I don't know why apm includes cruft to work around upstream issues.

Sadly `node-gyp` is essentially enforced upon us by the Node.js ecosystem. There are currently no viable alternatives, and so many native npm packages use `node-gyp` that any alternative would need to be a drop-in replacement. Someone started an effort a while back to implement [GYP in JavaScript](https://github.com/indutny/gyp.js/), but it seems like that effort has stalled, sadly.

**Comment by ioquatix** [comment]
Here is the workaround that I currently use: https://github.com/atom/apm/issues/179#issuecomment-399618944

**Comment by ioquatix** [comment]
Why can't we just hard code `node-gyp` to use `python2.7` rather than `python`?

**Comment by kylebarron** [comment]
There should be a way for `python-interceptor.sh` to only look for Python 2 executables, right?

**Comment by paskatharos** [comment]
> > Then perhaps node-gyp should be deprecated and projects that use it updated to use something else? I know that's outside of the scope of this issue, but ultimately Python2.7 is EOL. I don't know why apm includes cruft to work around upstream issues.
> 
> Unfortunately `node-gyp` is essentially enforced upon us by the Node.js ecosystem. There are currently no viable alternatives, and since many native npm packages use `node-gyp`, the alternatives would need to be drop-in replacements. Someone started an effort a while back to implement [GYP in JavaScript](https://github.com/indutny/gyp.js/), but it seems like that effort has stalled, sadly.

As of September ([electron blog](https://electronjs.org/blog/gn)), Electron uses GN; since Atom depends on Electron, shouldn't this have been resolved?
