### ISSUE TITLE
Dehighlighting of file name that is closed

### ISSUE THREAD

**Issue by lavishsaluja** [atom/atom#15921]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
Right now whenever I open a file from multiple files from a single project folder, the name of the file get green coloured and it's a great idea to highlight that file that I have opened that helped to keep a track of files I am working on 
But, 
when I close a file after saving and editing done the file name still remains green coloured and it should not be because now I start getting confused which files are open and which are closed and it becomes worst in the case when I have opened all the files in the folder once but I'm working on some of the files but all the names remains highlighted.
### Steps to Reproduce

1. [First Step] Open a file in a project folder for editing, the name of file will get highlighted.
2. [Second Step] close that file and open a new file, the new file's name will also get highlighted.
3. [and so on...] but the older file's name is still highlighted.

**Expected behavior:** [What you expect to happen]
The file's names should not remain highlighted after they have been closed.
**Actual behavior:** [What actually happens]
the file's names remains highlighted after they have been closed.
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
I'm working on the latest version as of now, [10 october 2017]
I'm working on Windows 7.

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report - unless I'm mis-understanding, this is expected behavior if you're working with a Git repository.  The file name colors [represent their Git status](https://discuss.atom.io/t/file-tree-colors-what-do-they-mean/12770) , green for new files, orange if the file is modified, etc.

If you commit the new file, the file name should change to grey.

If you're not using a Git repo, feel free to open a new issue in https://github.com/atom/tree-view.
