### ISSUE TITLE
Difficult to select hard tabs

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#15924]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When dragging to select a hard tab, the selection flickers between not selecting and selecting the hard tab.  I think the root problem may be that the halfway point of the tab isn't being calculated properly - in most programs, once you pass the halfway point of a tab, it should be highlighted, or in the case of moving the cursor, the cursor should be placed on the other side of the tab.  In Atom, this behavior is erratic.  I'll showcase a GIF of Atom and a GIF of the developer tools to visually explain the difference.

| Atom | Chrome |
| ------ | --------- |
| ![atom-hard-tab-selection](https://user-images.githubusercontent.com/2766036/31688405-8ca5a7b6-b38c-11e7-8eb2-3e46fd74ce43.gif) | ![chrome-hard-tab-selection](https://user-images.githubusercontent.com/2766036/31688414-91c74d80-b38c-11e7-8cf1-00029b590897.gif) |

### Steps to Reproduce

1. Create a hard tab
2. Place the cursor at one end of the hard tab
3. Attempt to select the hard tab

**Expected behavior:** Hard tab to be consistently selected past the halfway mark

**Actual behavior:** Selection flickers between hard tab being selected and not being selected

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.23.0-dev-274b809b1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

/cc @nathansobo: Possibly caused by the text editor rewrite?

**Comment by nathansobo** [comment]
Yeah, looks like it could be. I can hit it during my reactive duty if I don't get to it sooner.
