### ISSUE TITLE
Issue downloading atom for windows 10. Not all files will download properly, therefore app wont work. 

### ISSUE THREAD

**Issue by jcovington16** [atom/atom#15934]
When downloading the windows-zip file or the windows 64bit-zip file not all files will download properly and it will give a message to reinstall the file. Tried reinstalling after deleting the files completely off of the pc. Don't know what to do to get all files to download. 

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
I just downloaded `atom-x64-windows.zip` from the 1.21.1 release:

https://github.com/atom/atom/releases/tag/v1.21.1

Then installed installed and started Atom in [portable mode](http://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode) on Windows 7 with no problem.

Did you also download the zip files for 1.21.1?  Also, can you share a screenshot of the message you mentioned here?

> When downloading the windows-zip file or the windows 64bit-zip file not all files will download properly and it will give a message to reinstall the file.

Also, have you tried the installer from https://atom.io?

As a side note, please use and fill in the issue template as much as possible, it's super helpful for us when looking at issues.

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/15934#issuecomment-337827037. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
