### ISSUE TITLE
Atom doesn't display a window

### ISSUE THREAD

**Issue by thomassnielsen** [atom/atom#15937]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When launching Atom I don't get a Window anymore.

```sh
> atom --safe --clear-window-state -f
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4
```

MacOS 10.12.6
MacBook Pro (Retina, 15-inch, Late 2013)

### Steps to Reproduce

1. ??? (get into whatever state I'm in where Atom looks for display 4)
2. Launch Atom
3. No window appears

**Expected behavior:** Window appears

**Actual behavior:** No window appears

**Reproduces how often:** 100%

### Versions

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.9
git 2.14.1

### Additional Information

I first discovered the issue when connecting to my new display through DisplayPort, and it's been that way since. I've tested with and without any external display connected, and I've also rebooted, reinstalled Atom and removed my config (`~/.atom`).

**Comment by rsese** [comment]
Thanks for the report - so just to confirm, everything worked fine on 1.21.1 right until you connected your laptop to a new monitor?  

Thanks for working through all the debugging steps too, it's useful to know that none of those steps helped.  What kind of video card do you have?  Does starting Atom like this make any difference?

```
atom --disable-gpu
```

**Comment by thomassnielsen** [comment]
> just to confirm, everything worked fine on 1.21.1 right until you connected your laptop to a new monitor?

Yes, that's correct. As far as I can tell, that's the triggering event. Haven't worked since, with or without that monitor or any of the other ones I use.

> What kind of video card do you have?

NVIDIA GeForce GT 750M 2048 MB
Intel Iris Pro 1536 MB



> Does starting Atom like this make any difference?

I tried this, and waited a good 20 seconds before hitting Ctrl+C because nothing happened. The output is interesting though:

```sh
❯ atom --disable-gpu -f .
^CAttempting to call a function in a renderer window that has been closed or released.
Function provided here: worker.js:71:22
Remote event names: destroyed, crashed
```

I tested this on each GPU just in case, and I got the same result.

**Comment by brunovelasco** [comment]
I am having the same problem. Whenever a try a new Atom window (e.g. ⌘+T), the error I get is:

> Attempting to call a function in a renderer window that has been closed or released.
Function provided here: worker-manager.js:390:32
Remote event names: destroyed, crashed

Same versions than above. Using El Capitan 10.11.6

**Comment by brunovelasco** [comment]
Downgrading to 1.21.0 works fine.

Atom    : 1.21.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by rsese** [comment]
@brunovelasco - was that with `--disable-gpu`?  And otherwise you also saw the same error as mentioned in the issue body?

@thomassnielsen - would be curious to know if installing 1.21.0 makes a difference for you (though you did mention the problem specifically started when plugging in that other monitor 🤔).

**Comment by thomassnielsen** [comment]
> @thomassnielsen - would be curious to know if installing 1.21.0 makes a difference for you (though you did mention the problem specifically started when plugging in that other monitor 🤔).

I'll test and report back. Since atom wasn't running when the monitor was connected, there may have been an update installed. I related it to the monitor since it was the first time I connected it and the error mentioned a display related issue.

**Comment by thomassnielsen** [comment]
The same problem persist with 1.21.0.

**Comment by brunovelasco** [comment]
> @brunovelasco - was that with --disable-gpu? And otherwise you also saw the same error as mentioned in the issue body?
`--disable-gpu` had no effect.  The error I saw, as mentioned, was:
`Attempting to call a function in a renderer window that has been closed or released.
Function provided here: worker-manager.js:390:32
Remote event names: destroyed, crashed`
It was not related to multiple displays, though, but at any time I attempt to open an Atom tab/window.
