### ISSUE TITLE
Unfold all does not work

### ISSUE THREAD

**Issue by Ben3eeE** [atom/atom#15943]
Reproduced by folding the last 2 describes in the `tree-view-package-spec.coffee` file and then trying to unfold all.

Repro steps from @ungb of gif:
1. checkout `https://github.com/atom/tree-view`
1. `atom tree-view`
1. open `tree-view-package-spec.coffee`
1. go to the bottom of the file.  
1. fold the last describe block at line `4141`
1. fold the second to last describe block at `4124`
1. put your cursor on line `4123` (dunno if it matters)
1. open command palette and run `unfold all`

**Expected:** all are unfolded

**Actual:**  all are unfolded but line `4124`.  If you try to unfold this line it won't do anything.
Also noticed that the carrot in the gutter looks like it's unfolded but it isn't.  If you click on the gutter twice it will unfold. 
![image](https://user-images.githubusercontent.com/5624870/31797404-f49ff98c-b4e2-11e7-88a5-e036d6ca30fc.png)

![unfold all](https://user-images.githubusercontent.com/1058982/31791223-377f0a42-b518-11e7-8f05-946a90ebf47f.gif)

/cc: @nathansobo since you could also reproduce @50Wliu since you have also seen folding issues

**Comment by ungb** [comment]
I am able to repro this off of latest in master.  I'm going back and verifying in older version to see if it regressed.  I'll update with repro steps

**Comment by nathansobo** [comment]
I've done some investigation. It looks like we're destroying all the markers corresponding to folds in the folds marker layer, but the display layer still has the wrong text for some reason, indicating it may be a bug updating it.

**Comment by Ben3eeE** [comment]
@ungb am I correct to assume that this is not a regression given your updated repro steps?

What's interesting is that this doesn't reproduce if you fold them in the other order. I don't think cursor position matters. I thought so when recording the gif but it seems to be folding order and not cursor position.
