### ISSUE TITLE
window:reset-font-size behavior changed

### ISSUE THREAD

**Issue by bcorcoran** [atom/atom#15941]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I think the functionality mentioned in https://github.com/atom/atom/issues/9060#issuecomment-145878664 has been changed to match the original poster's (on #9060) expectations.

### Steps to Reproduce

1. Set custom font size in Editor Settings that isn't 14 (the default default). For this example, assume 12.
2. Go to a document and CTRL + or CTRL - to increase/decrease font size (or CTRL+Scroll, as I often do by accident with a touchpad).
3. Press CTRL+0 to trigger window:reset-font-size.

**Expected behavior:**
Font size should be reset to 12.

**Actual behavior:**
Font size is cleared from configuration (set back to 14).

**Reproduces how often:**
100% of the time.

### Versions

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information
This was not previously the behavior (it used to reset to the value I set in Editor Settings), but I just noticed this today when I was using my laptop by itself (normally plugged into external display/keyboard/mouse).

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce this on macOS 10.12.6 with Atom `1.23.0-dev-bdfa61e84`.

I didn't see any particular related pull requests since https://github.com/atom/atom/pull/6673 so I don't think this was changed intentionally but I'll ask the team to take a look.

> This was not previously the behavior (it used to reset to the value I set in Editor Settings)

You don't happen to remember about what version you remember this last working?

**Comment by rsese** [comment]
@Ben3eeE kindly pointed me to https://github.com/atom/atom/issues/9873, looks like a duplicate.  Sorry I missed that one @bcorcoran but you can subscribe there for updates if you'd like.

**Comment by bcorcoran** [comment]
Unfortunately I can't say with any certainty. If I had to guess (which may not even be helpful since I really don't know), it was definitely working pre-1.21 (atom-ide), but I don't know how far... possibly 1.17 or 1.18. 

Again, though, I'm not sure.
