### ISSUE TITLE
moving to trash fail on ubuntu 17.10

### ISSUE THREAD

**Issue by guilhem** [atom/atom#15949]
### Description

![screenshot from 2017-10-20 16-19-15](https://user-images.githubusercontent.com/486876/31825415-8137a0e6-b5b2-11e7-9477-0d9dd90b8a24.png)
```
Is gvfs-trash installed?
```

### Versions

```
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

Background:
```sh
$ gvfs-trash
This tool has been deprecated, use 'gio trash' instead.
See 'gio help trash' for more info.
```

https://github.com/electron/electron/pull/9518 add a `gio` trash implementation but is only include in _electron 1.7.2+_

**Comment by parhs** [comment]
any workaround?

**Comment by joe-bader** [comment]
I'm having the same issue.

**Comment by Belval** [comment]
Running Ubuntu 17.10 and I have the same issue.

**Comment by smogstate** [comment]
same here

**Comment by opkiler22789** [comment]
+1

**Comment by parhs** [comment]
The only solution was to install it with deb package. Through software center it fails.

**Comment by francosalcedo** [comment]
need help

**Comment by bsdunx** [comment]
I specifically disable gvfs-trash on my system, please allow deletion via syscall as option or fallback.

**Comment by OscarSouth** [comment]
Same problem here, I'll be watching this issue!

**Comment by rsese** [comment]
> electron/electron#9518 add a gio trash implementation but is only include in electron 1.7.2+

Atom 1.25 included an [upgrade to Electron 1.7.11](http://blog.atom.io/2018/03/15/atom-1-25.html) - can folks confirm if they still get an error?

**Comment by seamlik** [comment]
I can confirm the problem is fixed.

**Comment by 50Wliu** [comment]
:+1: thanks for confirming @seamlik.

**Comment by Belval** [comment]
Fixed for me too, thank you!

**Comment by elephwebb** [comment]
Hi guys, just a quick update in the topic. I'm currently using Ubuntu 16.04 version and I've just download/installed a new .deb version of Atom and the same issue occurred to me. 

Displaying message "Is gvfs-trash installed" even with permissions to folder granted to all(777) and chown -R $user. One thing to point out is that Ubuntu releases like 17.10 and 18.04, the **gvfs-trash** is deprecated and redirected to **gio trash**. [Ubuntu Manuals](http://manpages.ubuntu.com/manpages/artful/man1/gvfs-trash.1.html)

Well, in my case the workaround was the solution well explained here by @DavidCWebs in his [blog](https://dev-notes.eu/) which is:

Create a new Trash directory that can be accessed from outside the user’s home directory:

```
# Create a Trash directory (with some subdirectories) in root
sudo mkdir -p /.Trash-1000/{expunged,files,info}

# Give ownership of this to your user:
sudo chown -R $USER /.Trash-1000
```
Then worked like charm! :-) All the best! Thank for Atom is just sublime not being Sublime.

**Comment by wyqydsyq** [comment]
I'm using OpenSUSE TumbleWeed w/ Atom 1.26.1 and still get this issue. I've tried the trick of creating a `/.Trash-1000/` directory with no luck.

**Comment by Xmetalfanx** [comment]
same issue here on OpenSuse Tumbleweed (the only distro I have on any system that is having this issue, other distros from Manjaro, to a few different 16.04 or 18.04 based Ubuntu distros are fine) 

I am thinking it's something specific to the way OpenSuse is setup.   I did have Atom 1.25.1, though I upgraded to 1.27.1 and even tried Atom safe mode and it still happens

**Comment by wyqydsyq** [comment]
It seems to fail on OpenSUSE because there is no `gvfs-trash` package, in the official repos or even on OBS it seems

**Comment by ionphractal** [comment]
Fails also on Archlinux. Creating `/.Trash-1000/...` did not solve it.
Atom 1.30.0

**Comment by devkral** [comment]
Also an archlinux user.
here a quick fix:
vim /usr/bin/gvfs-trash

add:
#! /bin/sh
gio trash "$@"

then:
sudo chmod +x /usr/bin/gvfs-trash 

What is the state of changing the command to "gio trash"?

**Comment by Xmetalfanx** [comment]
seeing this on Arch and/or Antergos (Arch based) too ... still the same with my Tumbleweed install ... Ubuntu based stuff IIRC is a-ok

**Comment by allanlei** [comment]
For Arch (and probably other platforms), there's a note to patch this

https://wiki.archlinux.org/index.php/atom#Unable_to_delete_files.

```
export ELECTRON_TRASH=gio
````
in `~/.bashrc` or `~/.zshrc` works for me

**Comment by ionphractal** [comment]
@allanlei 's workaround works for me, too.

**Comment by Xmetalfanx** [comment]
i'll give that a try .. wonder if its the same thing for OpenSuse

**Comment by elizabeth-dev** [comment]
Is this going to be fixed? Some of the commented workarounds are fine but i don't know why is Atom still using gvfs-trash

**Comment by muchweb** [comment]
`gvfsd` is running under my user, but Atom can't delete files… this needs to be fixed

---

```
$ gnome-shell --version
GNOME Shell 3.30.1

$ atom --version 
Atom    : 1.30.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by florianmw** [comment]
There's an open issue on Electron: https://github.com/electron/electron/issues/15011
An alternative to the `.*shrc` file editing:
```
cp /usr/share/applications/atom.desktop ~/.local/share/applications/
```
and add in the Exec line `env ELECTRON_TRASH=gio ` e.g.:
```
Exec=env ELECTRON_TRASH=gio /usr/lib/atom/atom %F
```
After the issue has been fixed the customized desktop file can be simply removed.

**Comment by equals215** [comment]
On Anarchy (Arch Linux) and
```
Atom    : 1.31.2
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
I still got the problem even though I'm on Cinnamon with no traces of Gnome

**Comment by mr-avila** [comment]
> > [electron/electron#9518](https://github.com/electron/electron/pull/9518) add a gio trash implementation but is only include in electron 1.7.2+
> 
> Atom 1.25 included an [upgrade to Electron 1.7.11](http://blog.atom.io/2018/03/15/atom-1-25.html) - can folks confirm if they still get an error?

I am sorry to bump into a closed issue, but might be helpful to other users. The issue was not solved for me (using manjaro 18/Gnome). 

[The workaround proposed](https://github.com/atom/tree-view/issues/1237#issuecomment-423803696) by @AlynxZhou did work for me. Apparently, `gvfs` dropped `gvfs-trash`, and should be updated to `gio`. 

The workaround is the following:

`sudo vim /usr/bin/gvfs-trash`

Fill it with content:

```
#!/bin/bash
# GVFS updated and dropped gvfs-trash to gio, but Atom didn't update.
/usr/bin/gio trash "$@"
```

and then:

`sudo chmod +x /usr/bin/gvfs-trash`

**Comment by parhs** [comment]
test

**Comment by parhs** [comment]
test r

**Comment by AlynxZhou** [comment]
@parhs Cinnamon comes from GNOME so they use the same library like GTK and
GIO, so gvfs affects you too.

**Comment by Xmetalfanx** [comment]
a tad off topic here but I know Cinnamon was spun off Gnomeshell when it first came out or something to that effect ... not sure if its at least somewhat like Budgie (Solus) where it was alot more dependent on Gnome stuff but over time (I know this is the case with Budgie anyway) they got less and less reliant on Gnome and for those things Solus/Budgie needed from Gnome, they did things "in house"
