### ISSUE TITLE
Unable to open properly when in the middle of conflict on git rebase

### ISSUE THREAD

**Issue by brutalcrozt** [atom/atom#15955]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Unable to open prev session in the middle of git rebase that have conflict

### Steps to Reproduce

1. Close atom.
2. do `git rebase` that have conflict file.
3. open atom.

**Expected behavior:** 
Atom open with last session

**Actual behavior:** 
Atom hang, no file shown. And keep asking to force close or keep waiting.

**Reproduces how often:** 
2/2 = 100 %

### Versions
Windows 8
```
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm 1.18.5
npm 3.10.10
node 6.9.5 ia32
python 2.7.11
git 2.14.1.windows.1
visual studio 2015
```

### Additional Information
I abort the rebase, then reopen atom. Atom works as expected.

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/github if there's no existing issue already so we have it in the right place?  I also wonder if it's related to/the same issue as https://github.com/atom/github/issues/961 🤔
