### ISSUE TITLE
Caml and Objective-Caml

### ISSUE THREAD

**Issue by New1997** [atom/atom#15957]
Hi,
It would be really nice if you could and highlight for caml and ocaml to the official release (I have been using the package developed by someone until now but I prefer to have an official version)
Thanks

**Comment by 50Wliu** [comment]
As per https://github.com/atom/atom/issues/13932#issuecomment-284279115 and https://github.com/atom/atom/issues/13932#issuecomment-284562845, this is unfortunately not something we can commit to at the moment.
