### ISSUE TITLE
Ubuntu + screen brokes Atom shortcuts

### ISSUE THREAD

**Issue by xzitlou** [atom/atom#15950]
Hi,

I'm getting this weird Atom crush in **UBUNTU 16.04** every time I try **CTRL+W** or **CTRL+O** also something basic like **CTRL+TAB**.

I noticed that this error start happening after install [Screen](https://help.ubuntu.com/community/Screen).

Follow these steps:

1. Install [Screen](https://help.ubuntu.com/community/Screen)

2. `vim ~/.bashrc`

3. Add at the end `[[ $TERM != "screen" ]] && exec screen -q`

4. Restart, Open Atom and try any simple shortcut

Regards,

**Comment by isoeugenol** [comment]
i do 4 step and input CTRL+W,CTRL+TAB 
but atom is no crush.

**Comment by bnarris** [comment]
am having the same issue with atom on Ubuntu 16.04 it's crushing every time . How do i fix this problem
