### ISSUE TITLE
Expanding directory with many items hangs editor

### ISSUE THREAD

**Issue by joshaber** [atom/atom#1596]
1. Expanded a directory that has a ton of entries (~600 items).
2. Clicked on an image.
3. Tried to click on another image.
4. Window locked up.
5. Got the "Editor not responding" error sheet.

I took a sample of the app while it was spinning but I'm not sure if it'd be helpful to you. It's mostly just `<unknown binary>` in `libchromiumcontent`.

**Comment by 50Wliu** [comment]
I can still reproduce this using the file that @jwoertink provided using the ASAR branch.  It opens up fine but after a few seconds locks up.

**Comment by MatthewHerbst** [comment]
:+1: this still happens to me, Atom 1.0.19, OSX 10.10.5

**Comment by gfviegas** [comment]
+1, Windows 7 Atom 1.1.0
