### ISSUE TITLE
Slow expanding directories with a ton of entries

### ISSUE THREAD

**Issue by joshaber** [atom/atom#1597]
1. Expand a directory with a ton of entries (~600).
2. Wait a few seconds while the editor blocks for it to expand.

**Comment by as-cii** [comment]
It seems like this is not an issue anymore. Expanding a directory with 1000 entries is flawless :zap: 

Opening a directory with a ton of entries (e.g. no expanding) appears to be slower, but that's a different issue I think.

Can this be closed? :smile_cat:

**Comment by benogle** [comment]
Thanks. The tree view has been improved a lot in the last year.
