### ISSUE TITLE
Highlight the beginning and ending of a block

### ISSUE THREAD

**Issue by samir-majhi** [atom/atom#15988]
### Description

VSCode has a nice feature where if you move your cursor to the end of a block (if, while .. etc) it highlights both the end of the block as well as the corresponding beginning of the same block. And vice versa.

This would be a nice to have feature in Atom to easily find out which block you are in. Especially with languages like Ruby where 2 space indentation conventions don't make it clear which block you are currently in.

### Steps to Reproduce

1. Write code in any language. Use blocks (if, while, for ... etc)
2. Put your cursor on the end or beginning of the block

**Expected behavior:** Both the beginning and ending of the block gets highlighted

**Actual behavior:** Nothing

**Reproduces how often:** 100%

### Versions

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

Ubuntu 16.04.3 LTS

**Comment by victorhqc** [comment]
You mean like this?
https://atom.io/packages/ruby-block

**Comment by 50Wliu** [comment]
@samir-majhi I'll need pictures to know what you are talking about.

**Comment by samir-majhi** [comment]
@victorhqc Yes. Thanks for pointing me to that. 
I already have the language-ruby package. But I can't get block highlighting to work. It says "Highlighting line and bottom panel are enable by default." But that's not working for me.

Also the settings that your link speaks of aren't there. This is all I see:
![image](https://user-images.githubusercontent.com/32010530/32033329-aa3ae8c4-ba29-11e7-85dd-a70e36aac4c3.png)

**Comment by victorhqc** [comment]
Maybe you'll have to report an issue directly to the maintainer of that package
