### ISSUE TITLE
Highlight decorations inconsistently covering block decorations

### ISSUE THREAD

**Issue by tjfryan** [atom/atom#15985]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using the decorations API to make a side-by-side code change comparison view.  Involves using highlight decorations to show added and removed lines, as well as block decorations so that context lines stay lined up. Sometimes the highlight decoration will cover the block decoration, and sometimes it won't.

![Example of it working as expected](https://user-images.githubusercontent.com/3195775/31974625-805c4276-b8e1-11e7-9782-a4bfa87347fb.png)
![Example of it working not as expected](https://user-images.githubusercontent.com/3195775/31974626-8074af78-b8e1-11e7-9aec-d3369a9ed0fb.png)

### Steps to Reproduce

decorate a marker with a highlight on bufferRange `[[startLine, 0], [lastLine + 1, 0]]`, have a block decoration at bufferPosition `[lastLine + 1, 0]` with `position: before`.

**Expected behavior:**
A block decoration after a highlight will be consistently highlighted or not highlighted (preferably not highlighted)

**Actual behavior:**
A block decoration after a highlight is sometimes highlighted

**Reproduces how often:**
Behavior is consistent for my example, but I'm unsure of the underlying conditions causing it.  That is, whenever I feed my component the same data, the block decoration under the red highlight is not highlighted, but the block decoration under the green highlight is highlighted, but the issue itself is inconsistent behavior.

### Versions

Atom    : 1.22.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5

cc @lee-dohm

**Comment by lee-dohm** [comment]
Thanks! I'll have the team take a look.
