### ISSUE TITLE
Documentation for UI elements

### ISSUE THREAD

**Issue by akonwi** [atom/atom#15997]
I've already created a thread about this on the forums - https://discuss.atom.io/t/documentation-for-native-ui-elements/49080

I’ve been developing for atom for 3+ years now and the APIs are always changing as the team continues to grow the editor and that is great. The problem is there are aspects of atom that are important for non-core team members developing new things for the editor. The biggest gap in documentation I think has been with UI elements. Since the initial steps to deprecate space-pen, the official docs on atom.io/docs have not included anything about how to use the new UI elements.

I’ve been frustrated about this for a while and haven’t a chance or investment to bring this up but now I’m working on an atom package full time and feeling the pain even more.

I’d be happy to help start this if someone points me in the right direction.

**Comment by lee-dohm** [comment]
Thanks for the feedback.

All of our common UI elements are documented in the style-guide package with the one minor exception of [the Etch-based select list component](https://github.com/atom/atom-select-list) which is documented in its own README. If you're talking about documenting a recommended UI framework, we don't have one. As you can probably see, we use [Etch](https://github.com/atom/etch) in most places now but we use [React](https://reactjs.org) in the [github package](https://github.com/atom/github) and there are still vestiges of space-pen lying around. Until that situation changes, I'm not sure that there's anything to document other than "look at what module you're editing and copy the patterns you see there".

If you're asking for a recommended UI framework for packages, that has already been asked and after long deliberation [finally answered](https://github.com/atom/atom/issues/5756#issuecomment-312712387).

**Comment by akonwi** [comment]
Thanks for responding. The styleguide is helpful but it's missing examples of using `<atom-text-editor>`. I've been bringing it up in a few places between here and the GitHub package because I'm running into issues with it and the GitHub package is too.

I have used atom-select-list and it is well documented, which is awesome.
