### ISSUE TITLE
Load files asynchronously

### ISSUE THREAD

**Issue by fulldecent** [atom/atom#16005]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom should not assume that opening a file is immediate. Correct this by displaying a new file opening indicator for new tabs while a file is loading.

It may be appropriate to use asynchronous file loading based on how long the file load operation takes (duck typing). There may also be an operating system API available to detect unreliable (network) file systems. However I am **SURE** you would get burned by using this.

### Steps to Reproduce

1. `sshfs root@yourserver.org ~/Mount/server`
2. `atom ~/Mount/server`
3. Yank the ethernet cord
4. Use the atom file browser to open a.txt on the opened ~/Mount/server folder

**Expected behavior:** 

1. A new tab is opened in the main window to represent the file to be opened
2. Typing is disabled in the main window (because the file is not yet loaded)
3. After 250 ms a spinner begins spinning (right where the blue "file modified" icon normally goes)
4. After 10 seconds an error displays in the tab and it explains why the file failed to open

**Actual behavior:**

Entire program becomes unresponsive.

**Reproduces how often:**

Every time

### Versions

Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

macOS 10.13 (17A405)

apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5

**Comment by 50Wliu** [comment]
Unless I'm misunderstanding something, file loading _is_ async: https://github.com/atom/atom/blob/e34d16740b8f97648d73afe53762f769d3b5fd2d/src/workspace.js#L912

**Comment by maxbrunsfeld** [comment]
Yeah, most of the work for loading a file already happens on a background thread. Could you record a CPU profile during the time where Atom is unresponsive? It might also be able to sample the busy Atom process using `Activity Monitor.app` in case there is anything expensive happening in C++ (as opposed to JavaScript).

A few code paths are still synchronous that I know of related to gather git metadata about files. I wonder if that's what you're seeing here. We already have plans for backgrounding those. It shouldn't be hard, but the main challenge is maintaining a reasonable level of API compatibility.

**Comment by lgeiger** [comment]
@50Wliu @maxbrunsfeld Attached is the CPU profile and a analysis of the Atom and Atom Helper processes illustrating the issue described above.
[file_not_available.zip](https://github.com/atom/atom/files/1436036/file_not_available.zip)

A similar problem also happens when accessing a network drive via normal speed Wifi:
The editor becomes unresponsive and almost unusable. Removing the project from the tree view immediately makes the editor responsive again. For me disabling the git integration doesn't resolve this problem either.
I'm happy to add a screencast and more profiles for the second problem if it'd be helpful for you to reproduce.

**Comment by fulldecent** [comment]
@lgeiger thanks for attaching!

---

Also noting a few potentially related issues: https://github.com/atom/atom/issues/10271 https://github.com/atom/atom/issues/2456 https://github.com/atom/atom/issues/2313 https://github.com/atom/atom/issues/1766
