### ISSUE TITLE
Navigating through a form with atom-text-editor as inputs with tab key

### ISSUE THREAD

**Issue by akonwi** [atom/atom#16004]
I opened an issue in the GitHub package repo (https://github.com/atom/github/issues/1234) with a gif demonstrating the problem. 

I'm seeing the same behavior when I use `<atom-text-editor>`s as input elements. The focus moves from the input to the next button.

**Comment by akonwi** [comment]
Giving the first input a tabIndex of -1 and working up from there solved the issue for me.

**Comment by rsese** [comment]
Thanks for the report @akonwi!  So it seems like you're reporting a higher level issue where https://github.com/atom/github/issues/1234 is an example of it?

Could you please edit the issue body and fill out the report using the issue template?  That will make it a lot easier to ask the team to take a look.  If you can share as much detail as possible, that would be helpful too (e.g. did this used to work in an older version of Atom, can you share a minimal code reproduction, etc.).

**Comment by itsmichaelwang** [comment]
I think I found the cause. If you trigger the modal with Cmd+Shift+P > GitHub: Clone and you look at the modal that pops up, the text boxes look something like this:

    <atom-text-editor tabindex="-1" mini="" class="editor mini" data-encoding="utf8" data-grammar="text plain null-grammar">
    ...
    </atom-text-editor>

When tabindex = -1, then it makes it so that you can't tab to those input boxes. I made the tabindex = 1 for the first box, and tabindex = 2 for the second, and it looks like that fixed the issue.

I don't know enough about atom to actually make the right PR. I'll look around, but that's my take.

**Comment by 50Wliu** [comment]
Right here. https://github.com/atom/atom/blob/4fd0345e8488d2fa09151316b4e99656e7861644/src/text-editor-component.js#L480

**Comment by itsmichaelwang** [comment]
My thought was to take the correct tabIndex (which is present in the props object in the constructor of `text-editor-component.js`) and to write it to a variable in the constructor. And save it for later.

Is there a better way to debug this then making changes and rebuilding? It takes about 5-10 minutes to rebuild for every little change I make, and it makes debugging... less than ideal. If not, that's fine too. I was just wondering if there was a trick I'm missing to improve my workflow.

I saw this: http://flight-manual.atom.io/hacking-atom/sections/contributing-to-official-atom-packages/
but it refers to packages and not the main project itself.

**Comment by 50Wliu** [comment]
1. Set `ATOM_DEV_RESOURCE_PATH` to where you cloned Atom.
2. Make changes.
3. `atom --dev`

**Comment by itsmichaelwang** [comment]
Thanks @50Wliu. I made a PR for your consideration. My fix isn't without pros and cons. Thoughts?

**Comment by jasonrudolph** [comment]
This issue is resolved in #16492, and those improvements will likely be available in Atom 1.25.
