### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('e...

### ISSUE THREAD

**Issue by wolfhawke** [atom/atom#16021]
1. Add HTML-based Header text in a variable called htmlhead as below: 
`htmlhead='''<?xml version="1.0" encoding="utf-8"?>`
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"`
`  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">`
` `
`<html xmlns="http://www.w3.org/1999/xhtml">`
`<head>`
`<title>%s</title>`
`<link rel="stylesheet" href="../Styles/mainstyle.css" />`
`</head>`
`<body>\n'''`

2. create a variable called htmlout. Every time it is typed in, this error manifests

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('encoding="utf-8"?>
<!DOCTYPE') contains HTML space characters, which are not valid in tokens.

```
At C:\Users\wolfh\AppData\Local\atom\app-1.21.1\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:368

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('encoding="utf-8"?>
<!DOCTYPE') contains HTML space characters, which are not valid in tokens.
    at SuggestionListElement.addClassToElement (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:368:50)
    at SuggestionListElement.renderItem (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:402:30)
    at SuggestionListElement.renderItems (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:260:18)
    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.21.1/resources/app/src/view-registry.js:187:15)
    at ~/AppData/Local/atom/app-1.21.1/resources/app/src/view-registry.js:3:65
```

### Commands

```
     -1:29.5.0 editor:newline (input.hidden-input)
     -1:21.5.0 autocomplete-plus:confirm (input.hidden-input)
     -1:20.9.0 editor:newline (input.hidden-input)
  5x -1:07.7.0 core:backspace (input.hidden-input)
     -1:04.4.0 core:move-up (input.hidden-input)
  5x -1:04.1.0 core:move-down (input.hidden-input)
     -1:02.5.0 autocomplete-plus:confirm (input.hidden-input)
     -1:01.7.0 editor:newline (input.hidden-input)
  2x -0:58.6.0 core:backspace (input.hidden-input)
  2x -0:56.1.0 autocomplete-plus:confirm (input.hidden-input)
     -0:49.8.0 core:move-right (input.hidden-input)
     -0:48.2.0 editor:newline (input.hidden-input)
  4x -0:43.3.0 core:backspace (input.hidden-input)
     -0:31.1.0 core:save (input.hidden-input)
     -0:18.2.0 autocomplete-plus:cancel (input.hidden-input)
  4x -0:10.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.3 
html-template-generator 0.3.0 
kite 0.50.0 
platformio-ide-terminal 2.7.0 
```

**Comment by wolfhawke** [comment]
Code is actually this:
`htmlhead = '''<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>%s</title>
<link rel="stylesheet" href="../Styles/mainstyle.css" />
</head>
<body>\n'''`

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible in safe mode (`atom --safe`)? 

Also, is there a stack trace from the error that you can copy and paste for us?

**Comment by wolfhawke** [comment]
Hey,

 

The error is not reproducible in safe mode. Here is the stack trace.

 

C:\Users\wolfh\AppData\Local\atom\app-1.21.1\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:368

 

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('encoding="utf-8"?>

<!DOCTYPE') contains HTML space characters, which are not valid in tokens.

    at SuggestionListElement.addClassToElement (C:\Users\wolfh\AppData\Local\atom\app-1.21.1\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:368:50)

    at SuggestionListElement.renderItem (C:\Users\wolfh\AppData\Local\atom\app-1.21.1\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:402:30)

    at SuggestionListElement.renderItems (C:\Users\wolfh\AppData\Local\atom\app-1.21.1\resources\app\node_modules\autocomplete-plus\lib\suggestion-list-element.js:260:18)

    at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (C:\Users\wolfh\AppData\Local\atom\app-1.21.1\resources\app\src\view-registry.js:187:15)

    at C:\Users\wolfh\AppData\Local\atom\app-1.21.1\resources\app\src\view-registry.js:3:65

 

I am running Kite in the background, which might be part of the issue.

 

Blessings, Josh

**Comment by rsese** [comment]
> The error is not reproducible in safe mode. Here is the stack trace.

Thanks for confirming 👍   If there's no problem in safe mode, then that likely means a community package is causing the issue:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

You can disable each community package one by one to try and pinpoint which is causing the problem and then file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
