### ISSUE TITLE
'Decrease Text Size' for Atom in Mac shows an underscore in the menu

### ISSUE THREAD

**Issue by TristanPeers** [atom/atom#16024]
### Prerequisites

    [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Decrease Text Size for Atom in Mac shows an underscore in the menu, which while it is the same key showing a minus symbol would both look better and be more intuitive.

Screenshot:

![image](https://user-images.githubusercontent.com/9379533/32160048-f16abfbe-bd47-11e7-856e-a28df770637c.png)

### Steps to Reproduce

1. Open Atom on Mac
2. Click 'View' menu.

**Expected behavior:** A minus symbol is used

**Actual behavior:** An underscore symbol is used

**Reproduces how often:** 100%

### Versions
```
~ $ atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
~ $ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5
```
### Additional Information

None

**Comment by 50Wliu** [comment]
[Both keybindings](https://github.com/atom/atom/blob/2f0e472e629fe8fef8534a668ab0d552fb95f3a9/keymaps/darwin.cson#L82-L83) are correct, though it looks like the accelerators are preferring the one that is defined later, which may be counterintuitive.
