### ISSUE TITLE
Invalid syntax highlighter for php7 function parameter value

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [atom/atom#16023]
Syntax highlighter has problem to detect PHP7 function parameter default value and detect as invalid syntax...

![screenshot from 2017-10-30 00-27-22](https://user-images.githubusercontent.com/17345129/32148306-207ac134-bd0a-11e7-8e22-595a3b222c84.png)

**Comment by 50Wliu** [comment]
Cannot reproduce.  Please make sure you are on the latest Atom version, currently Atom 1.21.1.
![php7-default-value](https://user-images.githubusercontent.com/2766036/32148430-16022b88-bcf7-11e7-8c67-b9786d103481.png)
