### ISSUE TITLE
reopen windows when relaunching Atom

### ISSUE THREAD

**Issue by jglovier** [atom/atom#1603]
A feature I love about ST2 and iA Writer, which I'm missing in Atom, is when you quit the app with open windows (including unsaved documents), they all appear again when you reopen. 

This has saved me countless times in my workflow to handle having to do a system restart for software update, etc and not have to take time to save all my unsaved docs, etc. 

It's also nice because I generally have five or six open projects that I just keep minimized in the editor for ease of access. It would be great to have such a feature in Atom.

**Comment by lstroud** [comment]
+1

**Comment by matugm** [comment]
:+1:

**Comment by bloemendal** [comment]
+1

**Comment by Phillipus** [comment]
Astonishing. This is 2015, not 1995.

**Comment by jBot-42** [comment]
I haven't been here for almost 6 months. And yes, it is 2015. Meanwhile, I have been using Brackets.

**Comment by devios1337** [comment]
Not only is this a feature of competing editors, it's actually standard expected behavior on Mac OS as of Lion. Apps should now by default restore their last open windows when the app is quit and relaunched. It feels very strange for Atom to be lacking in this behavior.

**Comment by Phillipus** [comment]
Not only is this "a feature of competing editors, and expected behavior on Mac OS as of Lion", it's present in just about every single application since time began. A bit like "Save", and "Quit".

**Comment by mark-hahn** [comment]
> it's present in just about every single application since time began.

I don't think is true for applications that have many instances running at
once.  Can you think of an example?

**Comment by jeffmcneill** [comment]
I think SublimeText did this. However, while it is true it is expected behavior, it seems the real stumbling block is the architecture of the program. I use the open-last-project package which will restore tabs and the sidebar (but not multiple windows). It works well enough for a single instance. https://atom.io/packages/open-last-project

**Comment by mnquintana** [comment]
@benogle Does this mean this is going in core? (ie. deprecating the community package [save-session](https://github.com/mpeterson2/save-session)

**Comment by benogle** [comment]
That is the plan. It should be on by default and in core.

**Comment by ggamel** [comment]
@benogle This is amazing news. :dancers: :100:

**Comment by joshery420** [comment]
@benogle Fantastic! :smile: Thanks for the confirmation on this one. It's one of the only things that's stopping me from switching from ST3 full-time.

**Comment by justo** [comment]
@benogle Great news, thank you!

**Comment by netmiller** [comment]
+1. Great, and thanks. Like @joshery420 said "..that's stopping me from switching from ST3 full-time....".  In many details Atom is better than ST3 (=customizing)

**Comment by kevinhikaruevans** [comment]
+1,000,000.

I hate having to reopen a folder or project everyday in the morning.

**Comment by leongaban** [comment]
@benogle that is great news.... Atom seems like a nice editor, definitely way more buggier then sublimetext... but the not remebering my last open folder/file structure kills it.

**Comment by zhangjx** [comment]
+11111

That's great!!! Expecting it!!

**Comment by dasilvacontin** [comment]
Is this a good first issue? I'm interested in getting involved.

**Comment by benogle** [comment]
I cant say for certain, but it shouldnt be terribly complex. A lot of it already happens. Say when you start in a directory with `atom .` and it opens that window with all the previous state. See [loadOrCreate](https://github.com/atom/atom/blob/master/src/atom.coffee#L32) for info on that deserialization process. You should be able to store a list of the open paths on quit, then somewhere in AtomApplication check if the `pathsToOpen` array is empty. If it is, then load the list of open paths that were saved on quit, and place them in the `pathsToOpen` array (maybe [here](https://github.com/atom/atom/blob/master/src/browser/atom-application.coffee#L68)). 

I am, however, not as well versed in this code as, say, @kevinsawicki, though. And the storage of those paths might require some thinking.

**Comment by dasilvacontin** [comment]
Okay, thanks for the pointers @benogle! I'll try taking a look at it.

**Comment by pitaj** [comment]
:+1:

**Comment by Stanzilla** [comment]
+1

**Comment by mkurde** [comment]
+1

**Comment by TheKing42** [comment]
Temporary Work Around, run it from the terminal in the folder. It should remember enough stuff for it not to be annoying, and it won't block the terminal.

**Comment by ardhipoetra** [comment]
As an ex sublime user. I also want this feature as well :+1:

**Comment by victorhooi** [comment]
I was previously using https://github.com/mpeterson2/save-session

This supports restoring unsaved files (similar to SublimeText)

I just tried out https://github.com/danielmahon/atom-open-last-project

This doesn't appear to support restoring unsaved files - if you quite, Atom will prompt you to save unsaved files.

@benogle @lee-dohm Can I confirm if this plugin is what will make it into Atom 1.0?

If so, this appears contrary to what most users are requesting - which is that Atom remember its state (similar to SublimeText, or most OSX native applications from OSX Lion onwards).

Would be great to get clarification from the Atom team.

**Comment by taka4sato** [comment]
Hi I really hope this feature being supported! +1.

**Comment by ralbt** [comment]
+1

**Comment by Nyrone** [comment]
+1, lack of this feature is the greatest disadvantage of Atom.

**Comment by pappacena** [comment]
+1

**Comment by tracykteal** [comment]
+100 to being able to restore unsaved files. I love Atom, but the fact that this isn't possible is very unexpected behavior, and I've lost work on computer crashes. Even emacs has autosave.

**Comment by dbpolito** [comment]
+1 for this too... https://atom.io/packages/remember-session looks to do this job perfectly but this should be in core by default.

**Comment by mnquintana** [comment]
I just want to reiterate (it can be hard to find it in all the comments now) that this is on the 1.0 roadmap, so it is definitely going to be added, it's just a matter of time (and if someone wants to take a crack at implementing it now).

**Comment by AJIh** [comment]
+1 atom's behavior is not expected now

**Comment by 50Wliu** [comment]
Once again, this is on the roadmap to 1.0.  This means that this feature will be available before Atom 1.0 is officially released.  If someone wants to work on this issue, please feel free to create a PR!  Otherwise, you can still track the progress on this issue by looking at the labels at the top and seeing whether it's `on-deck`, `in-progress`, `shipping`, etc.

**Comment by bolinfest** [comment]
Let me try to summarize what @maxbrunsfeld and @nathansobo and I spoke about:

We agreed that when you open Atom from Spotlight/Dock, then we should just restore everything from the previous session. Currently, Atom remembers nothing when you start it this way because its state is tied to root folders. We decided that the state of a Spotlight/Dock launch should be stored in an application.json file that can have multiple workspace states stored in it.

However, when you launch Atom from the command line, it should have only the root files/folders that you specified on the command line, and the cache key for the workspace should be a function of those root folders.

The analogy is that for Xcode, you basically never launch it from the command line and you expect it to restore the state when you re-launch it from the icon. However, for vi/emacs, you only expect it to open the files you specified on the command line.

**Comment by 50Wliu** [comment]
This will be in the next Atom version, 0.193.0. :fireworks: :sparkles: :boom:

**Comment by sinkingshriek** [comment]
I'm really excited by this. :stuck_out_tongue_closed_eyes: Congrats guys.

**Comment by dsnipe** [comment]
:+1:

**Comment by BrianHutchison** [comment]
+1, very much looking forward to this feature

**Comment by mrkaspa** [comment]
+1 I need it too

**Comment by djoos** [comment]
:+1:

**Comment by mtt87** [comment]
Good news :+1:

**Comment by Stanzilla** [comment]
Does the Desktop shortcut on Windows need updating for this to work, maybe? Because it does not work for me atm, see video: https://youtu.be/SETJog-VnkY

**Comment by victorhooi** [comment]
@Stanzilla My understanding is that this feature will be merged in Atom 0.193.0 - which isn't out yet.

**Comment by victorhooi** [comment]
@Stanzilla My understanding is that this feature will be merged in Atom 0.193.0 - which isn't out yet.

**Comment by benogle** [comment]
@Stanzilla can you make a new issue for this?

**Comment by wangchunyang** [comment]
From my testing, it doesn't work on Windows (Atom 0.193).

**Comment by victorhooi** [comment]
I'm running Atom 0.193.0 on OSX 10.10.3 (Yosemite).

However, I'm not really sure if the functionality is working correctly for me.

I am starting atom via OSX Spotlight.

I previously had the save-session package installed. I disabled this package.

If I have an untitled (i.e. unsaved) document open in Atom, when I quit, it will ask me if I want to save the document.

If I hit "Don't save", when I re-open Atom, that document will not be there.

My understanding was that this issue covered similar functionality to SublimeText, TextMate etc. (or any other modern OSX App) where if you quit, it won't prompt you to save, but will simply re-open to where you left off the next time it starts?

**Comment by mehcode** [comment]
@victorhooi This is just to remember your open windows, period. You'll want to look at #6455

**Comment by Stanzilla** [comment]
@benogle Done. https://github.com/atom/atom/issues/6466

**Comment by ivanlemeshev** [comment]
It's work when I press Cmd + Q on my Mac OS, but it does not work when I click on red cross to close the window.

**Comment by victorhooi** [comment]
@mehcode Aha, thanks for clarifying - Apparently #6455 has been closed in favour of an earlier issue, #942, so I'll keep my eye on that one.

**Comment by Xendd** [comment]
@ivanlemeshev similarly in Windows it will work when using File > Exit, but not when closing with the close button.

**Comment by wangchunyang** [comment]
@Xendd Aha, indeed. Thanks for your findings. :+1:

**Comment by Leonick** [comment]
@ivanlemeshev Is that really expected though? On OS X the red button on the window is just for closing that window, the app itself stays running. One could perhaps argue for an option to close the app with the last Window but that is not the conventional behaviour on OS X.

@Xendd Pretty serious for Windows on the other hand, closing the last windows should always work the same as File > Exit

**Comment by tesfabpel** [comment]
@Leonick, then, maybe, on OS X if you close the last window but the app is still running, reclicking on the app button reopens the last window.
It should work correctly... :)

**Comment by mnquintana** [comment]
> @ivanlemeshev: It's work when I press Cmd + Q on my Mac OS, but it does not work when I click on red cross to close the window.

I think this is expected behavior on OS X, since as @Leonick said closing the last window does not quit the app, so Atom shouldn't remember your open window if you close it (otherwise Atom would *always* remember your open windows no matter how many times you close them).

> @ivanlemeshev similarly in Windows it will work when using File > Exit, but not when closing with the close button.

That sounds like a Windows bug. Would you mind filing a separate issue for that?

**Comment by toxickg** [comment]
I can confirm that this feature doesn't work on Linux when the window is closed both using shortcut and close button, Atom version 0.194.0.

**Comment by bitbonk** [comment]
This feature also doesn't seem to work on Windows (7). Whenever I close the windows in Atom 
version 0.194.0 it asks me whether I want to save the changes and when I reopen Atom all tabs are gone.

**Comment by pierretusseau** [comment]
Actually the pluggin open-last-project for Atom did work better than the "core version". The first one works basically, the core version do not, at all... on my W8.1

**Comment by monotykamary** [comment]
Same here, I don't see any options for the core version of this package and it has not saved any session as of so far. (Windows 7)

**Comment by fedelibre** [comment]
Windows users, please subscribe to issue #6466 

Look forward to a new release, as I can't build atom on linux

**Comment by skladd** [comment]
For me on Linux (Gnome) it works only if I close it via menu or Ctrl+Q, it does not work if I use the close button in the title bar. Thus it seems to be a general problem.

**Comment by rebornishard** [comment]
same here on win 7 sp1 x64

**Comment by 50Wliu** [comment]
**PLEASE SUBSCRIBE TO #6466 IF YOU ARE ON WINDOWS**
I really don't want to lock this issue again.

If you have a different issue that hasn't already been opened, please create one instead of replying here.

**Comment by stanier** [comment]
Does not work through Gnome's exit button on Ubuntu 14.04.

+1 for working fix

**Comment by iclanzan** [comment]
When there is an update to Atom available and one clicks “Install and relaunch”, Atom loses open windows state.

**Comment by 50Wliu** [comment]
@iclanzan I believe that will be fixed by #6684.

**Comment by joergrech** [comment]
Restoring windows does not work for me in version 0.201.0 on a Mac with Yosemite 10.10.3. If I have two open windows with different files opened Atom will restore two windows but with the same files (a duplicate of the last active window). The same behaviour happens with three windows.

**Comment by mnquintana** [comment]
@joergrech Can you post a list of your installed packages? (`apm list --installed`)

**Comment by joergrech** [comment]
Here are my installed packages:
├── autohide-tree-view@0.19.2
├── language-groovy@0.4.0
├── minimap@4.9.0
├── sort-lines@0.11.0
└── wordcount@2.2.2
Btw. I  reinstalled / updated Atom last week after I had installed it in Spring 2014 (must have been one of the first public versions). If restoring windows should work and nothing else might help I can try to remove everything Atom installed and reinstall it.

**Comment by iclanzan** [comment]
@50Wliu it is still not fixed and in fact is even more broken now because it doesn’t even reopen windows under regular circumstances most of the time. If I reopen a project manually, open files are not remembered either.

**Comment by maxbrunsfeld** [comment]
> If I have two open windows with different files opened Atom will restore two windows but with the same files.

@joergrech are you saying that you have the same folder open in two different windows? Saving multiple states for the same folder is not a feature that we've implemented yet. Currently, we save a state per folder.

**Comment by 50Wliu** [comment]
@iclanzan could you please open a new issue for that and include the following:
* the version of Atom you're using
* your OS
* whether or not it happens in safe mode (`atom --safe`)
* and specific reproduction steps

Thanks!

**Comment by pitaj** [comment]
I think he means he had two windows open with two different projects. When
he reopened it, two windows opened, but both had the same project.

**Comment by iclanzan** [comment]
I was referring to two things.

First  #7156. Someone beat me to it and opened the issue for it.

The second one is opened files are not remembered in a project. I can’t find a way to reproduce this reliably. I did run into #7213 and #7214 while trying though.

**Comment by eljamz** [comment]
Atom 1.0
OSX 10.10.3
Both Atom --safe and with regular atom (for atom --safe I used the command not the dock/spotlight).

Only 1 atom-window open in all the tests.

1.- Start Atom from spotlight or dock (tried both)
2.- add folders or working files.
3.- click on the top left red cross. (but it actually only closes the "working window" not atom itself)
4.- start atom again from spotlight/dock (but it is actually running) 

RESULT:  empty workspace.


Different procedure.
1.- Start Atom from spotlight or dock (tried both)
2.- add folders or working files.
3.- cmd+q (it quits the whole application, not only the working window like in the last steps).
4.- start atom again from spotlight/dock (the apps still remains closed so is fresh start).

RESULT: showing the last working files/projects as expected.


Another different procedure.
1.- Start Atom from spotlight or dock (tried both)
2.- add folders or working files.
3.- Atom-menu/quit (it quits the whole application, not only the working window like in the last steps).
4.- start atom again from spotlight/dock (the apps still remains closed so is fresh start).

RESULT: showing the last working files/projects as expected.



RESUME:
Atom does not save the session of your last used window when you close it without exiting the application.

**Comment by mnquintana** [comment]
@eljamz That is intended behavior, and is how all OS X applications that save sessions work. Otherwise it would be impossible to remove windows from the saved session - you could only add windows and never remove them without resetting the entire session.

**Comment by eljamz** [comment]
@mnquintana Yup, I was just trying to explain the behaviour, that ATOM ISN'T WORKING WRONG, is actually working as expected and it do not save your last windows session because you still have the program running so you can create a new workspace/project but not trying to exit the app because you're done for the day...

So like you said, is not a malfunction is just a miss understanding of the behaviour from some others.

**Comment by Sogl** [comment]
+1
Need this feature...

Now with 1.0 I'm using save-session:
https://atom.io/packages/save-session

**Comment by 50Wliu** [comment]
> +1
> Need this feature...

This is already in 1.0 - is it not working for you?

**Comment by Sogl** [comment]
>This is already in 1.0 - is it not working for you?
I didn't see any tab after Atom crash.
This is the first day after ST3 and I thought that this function doesn't work =)

Just disable the extension and checked - works fine.

**Comment by schmeisers** [comment]
And is there a way to turn this off in 1.0?  I don't see any packages to disable.

**Comment by BrianMcBrayer** [comment]
Hello, I second @schmeisers that this should also be able to be disabled. It is the first thing I turn off when using Notepad++. I use Visual Studio most of the time and Atom as a quick text editor, and it is so frustrating now that it keeps remembering the previous files and projects I had open. What can I do to get this behavior turn-offable? Thanks! I really love Atom!

**Comment by samis** [comment]
Any chance of this happening soon? It doesn't seem to be exactly complex and wouldn't break anything. Shame I don't know java / coffeescript.

**Comment by 50Wliu** [comment]
> Any chance of this happening soon?

This has been implemented for more than a few versions now.  What Atom version are you currently on?

**Comment by samis** [comment]
Oops. Posted that in the wrong issue.

**Comment by alexchandel** [comment]
This doesn't count as implemented without #4161. Depending on how Atom decides to close on a given day, it may not restore windows.

**Comment by iclanzan** [comment]
@alexchandel Totally agree with you!

**Comment by stanier** [comment]
@alexchandel @iclanzan The feature was successfully implemented for use under typical circumstances not bound by conditions other than what was already stated.

In my personal experience, files will reopen successfully after a crash, though it seems to have a tendency to use the window data stored on the last successful exit preceding a crash.  This would be an issue with how atom handles restores rather than application open/close events.  In this sense, it is an issue for #4161 and not for this thread.

**Comment by ragekit** [comment]
This feature is nice, but is there a way NOT to do that ? I mean don't reopen last opened files/folders ? i can't find a way to do it

**Comment by alexchandel** [comment]
Actually, I think I've found an issue with this. On OS X, Atom 1.0.4, add a project folder, leave some tabs open, and close Atom; if Atom is reopened by double-clicking a file associated with it, then Atom completely forgets what was last open, and launches with a single window open to the file's folder, with a single tab for the aforementioned file.

**Comment by hypergnash** [comment]
+1

**Comment by mnquintana** [comment]
If there's behavior related to this feature you'd like to see changed, please comment in an appropriate open issue or open a new issue if one doesn't exist yet - it's too hard to keep track of in an old, already-implemented issue like this. Thanks!

**Comment by olezko46** [comment]
:+1:

**Comment by snario** [comment]
Please fix this ... makes Atom so frustrating to develop on.

**Comment by 50Wliu** [comment]
> Please fix this

This has already been fixed.  Please make sure you're running a recent version of Atom (1.2.x should be fine).  If you're still experiencing this even on 1.2.x, please file a new bug.

**Comment by snario** [comment]
Still experiencing it on 1.2.4. I guess I'll make an issue.

On Fri, Dec 4, 2015 at 12:21 PM Wliu <notifications@github.com> wrote:
Please fix this

This has already been fixed. Please make sure you're running a recent version of
Atom (1.2.x should be fine). If you're still experiencing this even on 1.2.x,
please file a new bug.

**Comment by Stanzilla** [comment]
Yeah it's also broken *again* for me. I think it broke between 1.3.0-beta1 and 1.3.0-beta4

**Comment by alexchandel** [comment]
@50Wliu It is not fixed. It has never been fixed on OS X. Never. I have tested it in every single version since 1.0.4. Pretending it's fixed and asking others to open new bugs helps no one. To replicate:

1. Open Atom 1.0.4 on OS X 10.11.1.
2. Add a project folder, leave some tabs open, and close Atom.
  * Repeat Step 2 multiple times for extra fail
3. Reopen Atom by double-clicking a file associated with it, outside any project.
4. Atom completely forgets what was last open, and launches with a single window open to double-clicked file's folder, with single tab for the double-clicked file.

**Comment by 50Wliu** [comment]
> Pretending it's fixed and asking others to open new bugs helps no one

There are multiple people on Mac who report this working for them, so I repeat: please make a new issue, and include the information asked for in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging) and [CONTRIBUTING.md](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report).

If it is then determined that this functionality has completely regressed, this issue will be re-opened.

**Comment by kpashka** [comment]
Experiencing this on 1.3.2 and OSX 10.11.2

**Comment by snario** [comment]
I think I have fixed this by doing

```bash
rm -rf ~/.atom/compile-cache
```

**Comment by aliwatters** [comment]
I was experiencing related symptoms on Ubuntu - a session from months ago was recreated on every restart of atom.

```rm -rf ~/.atom/compile-cache```

seems to have fixed the problem here as well - @snario thanks - first time I saw that suggestion.

**Comment by chuyik** [comment]
Just tested it's already implemented, but I think you need to disable `save-session` and restart atom, then try again.

**Comment by rdibona** [comment]
Thank you to @snario -- that worked for me on Mac OSX 10.11.3, Atom 1.5.3. I'm using Atom-Project-Manager and it restored my last open project finally.

How did you figure that fix out and why did that fix it? Thanks again.

**Comment by mwinham81** [comment]
@snario Thank you! This worked for me as well.

**Comment by alexchandel** [comment]
For reference, issue #10044 tracks the "multiple window" bug in the implementation of this issue.

**Comment by CoWinkKeyDinkInc** [comment]
So is this issue fixed?  Atom on 1.7.2 still doesn't remember to keep project folders in the sidebar.

**Comment by netfishx** [comment]
+1，Atom 1.7.2 in my macos 10.11.4 doesn't keep my project

**Comment by 50Wliu** [comment]
@CoWinkKeyDinkInc @netfishx Please open new issues.

**Comment by KeinborgMichael** [comment]
+1，Atom 1.7.3 in my macos 10.11.4 doesn't keep my project

**Comment by 50Wliu** [comment]
@KeinborgMichael Please open a new issue.

**Comment by gnomed** [comment]
dear god why was this not implemented as a plugin and is instead baked right into the core editor? Can't the atom devs adhere by their own philosophies?

**Comment by niij** [comment]
+1 Mac v10.11 and Atom 1.8.0 isn't keeping my state between relaunches of Atom

**Comment by 50Wliu** [comment]
@niij Please open a new issue.

**Comment by Vvkmnn** [comment]
OSX Fix from [old thread](https://github.com/atom/atom/issues/10044#issuecomment-198816861):

> Unbelievable. Finally got it working.
> 
> Problem: On a mac, if you close using the red X button in the window, the Atom will still be running. So (now obviously) this is the state it saves, an empty atom.
> 
> So, you have to close it using Cmd + Q. Then it will restore correctly the next time.
> 
> PS: There should be an option in the settings to close the app completely with the X button.

Referenced in #6605, and hopefully [implemented in Atom 1.8.0-beta0](https://github.com/atom/atom/issues/6605#issuecomment-203981148) via #11324. 

Other temporary fixes include:
- Clearing the cache
`rm -rf ~/.atom/compile-cache`
- And using the atom-project manager:
`apm install atom-project-manager `

**Comment by niij** [comment]
@Vvkmnn Thank you!  Using CTRL-Q instead of the Red X works for me.

**Comment by wmertens** [comment]
Note that this behavior is the default behavior of apps on OS X. An app can
be running, and it can optionally have windows.

On Mon, Jun 13, 2016 at 4:29 PM Brandon Annin <notifications@github.com>
wrote:

> @Vvkmnn <https://github.com/Vvkmnn> Thank you! Using CTRL-Q instead of
> the Red X works for me.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/atom/atom/issues/1603#issuecomment-225597537>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AADWlkXiD0pkHjLS00cFDOl_csXasE8Bks5qLWlBgaJpZM4Blkyg>
> .
>
-- 

Wout.
(typed on mobile, excuse terseness)

**Comment by marcosfede** [comment]
I have tried removing complile-cache and installing atom-project-manager. still not restoring my previous project on OS X, even if I close it with cmd-Q

**Comment by Leader138** [comment]
怎么下载

**Comment by 50Wliu** [comment]
@Leader138 请您用英文，所以别的人可以明白您在说什么呢。谢谢！您要下载什么？
***
Please use English, so that others can understand what you're saying.  Thanks!  What are you trying to download?

**Comment by marcosfede** [comment]
like @eliotsykes suggested on  #10044 ,  Instead of opening my project folder with a symlink, I used the full path , and now when I exit atom with cmd+Q the project restores succesfully. however, if I just close atom clicking the red close button then It restores empty, so it seems like there are two separate problems, one with symlinks and one with atom saving a blank project on mac

**Comment by x13945** [comment]
I m using Atom 1.8.0 on Ubuntu16.04LTS x64, and it not reopen the files I opened last time.

**Comment by 50Wliu** [comment]
@x13945 please open a new issue.

**Comment by bb-git** [comment]
+1 mac not restoring the tree view if you close using the red x

**Comment by mnquintana** [comment]
@bb-git Please open a issue for this, if there isn't one already.

Since this was implemented a long, long time ago, I'm going to lock this to keep noise levels down. If you run into issues with Atom not restoring UI state correctly, please see the [Contributing guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#before-submitting-a-bug-report) first, then open a new issue for it if there isn't one already.
