### ISSUE TITLE
atom - auto indentation issue - IF statement

### ISSUE THREAD

**Issue by riccardobosini** [atom/atom#16032]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Open the code attached.
2. Copy it and paste it in Atom.
3. Save it like a php file.
4. Execute an auto indentation.
5. Look at both switch statements.
6. Notice that if the case sentence contains a 'if' characters the auto-indentation goes wrong.

**Expected behavior:** [What you expect to happen]

A correct auto-indentation

**Actual behavior:** [What actually happens]

A wrong auto-indentation

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

Each version

### Additional Information

None

[atom_issue.txt](https://github.com/atom/atom/files/1428701/atom_issue.txt)

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/language-php if there's no existing issue already so we have it in the right place?
