### ISSUE TITLE
Inline documentation refers to setInvisibles, which doesn't exist

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#16042]
https://github.com/atom/atom/blob/bc061bb608773244b32edf18bc48db7b92efc609/src/text-editor.js#L3595-L3603

A project-wide search reveals only a single result for `setInvisibles`, which is the comment itself.

**Comment by 50Wliu** [comment]
Still an issue. URL updated.

**Comment by thomasstep** [comment]
What needs to be done to resolve this?

**Comment by 50Wliu** [comment]
@thomasstep updating the documentation to actually list the expected structure of the returned object.

**Comment by UziTech** [comment]
looks like the docs for `setInvisibles` used to be:

```coffee
# Set the invisible character substitutions for this editor.
#
# * `invisibles` An {Object} whose keys are names of invisible characters
#   and whose values are 1-character {Strings}s to display in place of those
#   invisble characters
```

from https://github.com/atom/atom/commit/4b0183d074848ae9a6d84cbf57ad7b04c6b3d96c#diff-561e90889eebfd1149f1b29006d738c4L2857

**Comment by dainmiller** [comment]
Should we add that method and documentation back? This would force a decision to be made around keeping the docs referencing `setInvisibles`. If it shouldn't exist it could be deleted with the docs after that, assuming ppl who would know will notice. 😉
