### ISSUE TITLE
Atom crashed

### ISSUE THREAD

**Issue by Aranjedeath** [atom/atom#16044]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashed and told me to come here to report it. It didn't give me a crash ID or something like that so I don't know what else I should do. The crash was during some part of updating Atom Beautify from 0.30.5 to 0.30.6. 

### Steps to Reproduce

1. open atom
2. click update in bottom right
3. atom runs update, crashes.
4. popup tells me sorry it crashed and to report it here

**Expected behavior:** 
not crash

### Versions

jacob@kafka:~$ atom --version
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

jacob@kafka:~$ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

I am using KDE NEON, which is ubuntu 16.04.* with updated KDE packages.

**Comment by rsese** [comment]
Thanks for the report @Aranjedeath - is atom-beautify updated at this point or does it still show that it can be updated and crashes if you try to update again?

**Comment by Aranjedeath** [comment]
Everything looks updated when I relaunched. If the auto-report crash function ran, you may have a trace.

**Comment by rsese** [comment]
Going through some older issues, thanks again for reporting @Aranjedeath :+1: we'll go ahead and close for now.
