### ISSUE TITLE
Can't install packages as local administrator

### ISSUE THREAD

**Issue by japfau** [atom/atom#16043]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

Atom can be successfully installed and opened with no problem. The problem comes when I want to install packages. This is the error I get when entering the install tab: 'This program is blocked by group policy. For more information, contact your system administrator.' I've tried running the atom and apm commands through the command line but they give the same error. This could simply be a problem with group policy that is only affecting Windows and not Macs. As kind of mentioned, this is a windows error with the latest atom version and with me as an administrator. Any help on this issue would be appreciated.

**Comment by isoeugenol** [comment]
what is package`s name?
i installed package(gpp-compiler) success and don`t check admin

**Comment by japfau** [comment]
It doesn't matter what package I try to install. The error pops up under the featured packages header and also when I search for any package. 
![atom_error](https://user-images.githubusercontent.com/21246669/32464440-a0448a66-c305-11e7-9773-23334ff2743a.PNG)
