### ISSUE TITLE
In Preference Settings, Package Filter Field Disabled On Mac

### ISSUE THREAD

**Issue by greghelton** [atom/atom#16062]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. On Mac open Atom and select Preferences & then Packages in Atom menu
2. Attempt to enter text in Filter field (where it says "Filter packages by name")
3. Note that you cannot enter text into Filter field

**Expected behavior:** In the Filter field I expect to be able to enter text

**Actual behavior:** No text appears in the Filter field and the screen does not respond with any filtering activity

**Reproduces how often:** 100%

### Versions macOS Sierra 10.12.6
$ atom --version
Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 3.6.3
git 2.13.5

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!  I'm unable to reproduce with Atom 1.21.2 on macOS 10.12.6.  It looks like you tried safe mode already, do you see any messages in dev tools (<kbd>alt-cmd-i</kbd>) console ?

**Comment by greghelton** [comment]
I could not enter text on any screen, not in settings dialog and not in a new file.  Problem has taken on new dimensions.

I deleted atom that was installed via Mac download & I reinstalled using homebrew.  

After installation completed, from terminal I created new folder & (with touch) created newfile.py file.  Ran 'atom newfile.py' in terminal and I still can't enter text.  Went into Preferences/Packages and tried to enter text in "Filter packages by name" and could not enter text there either.

Nothing appears in the console.  I've been using Mac for development for 12 yrs.  Is Atom like vim & you have to go into insert mode?  What's the magic key combination for insert mode?

Nothing has been printed in console.

**Comment by rsese** [comment]
Can you remove the Homebrew installation and install via the Zip file from https://atom.io (installation instructions are in the [Flight Manual](http://flight-manual.atom.io/getting-started/sections/installing-atom/))?

Then start Atom in safe mode and let us know if you still can't enter text:

```
$ atom --safe newfile.py
```

And just to confirm, have you been using previous versions of Atom that worked ok but then things stopped working with 1.21.2 or is this a new installation?

> Is Atom like vim & you have to go into insert mode? What's the magic key combination for insert mode?

Unless you specifically install a community package like https://atom.io/packages/vim-mode-plus,  you should be able to just type, there's no insert mode.

**Comment by greghelton** [comment]
Ran 'brew cask rm atom' and 'rm -rf ~/.atom' and installed atom-mac.zip from https://github.com/atom/atom/releases/tag/v1.21.2

I had to use alternative start command (since no alias shortcut installed I guess).  Single dash on safe.
$ open ./Atom.app -safe newfile.py

Everything seems fine.  I can enter text into a file and filter packages.  Atom's sluggish behavior is gone too.  Yay.  Thanks.

**Comment by 50Wliu** [comment]
:+1:
