### ISSUE TITLE
editor:delete-to-previous-word-boundary and editor:delete-to-next-word-boundary does not work properly with newlines

### ISSUE THREAD

**Issue by ungb** [atom/atom#16070]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

editor:delete-to-previous-word-boundary and editor:delete-to-next-word-boundary does not work properly with newlines

### Steps to Reproduce

1. Open Atom and insert the following js code snippet
```javascript
function doubleNumber (num) {




  return num*2
}

```

2. Put your cursor before the `r` in return.  
3. Open command palette and run `Delete to previous word boundary`

**Expected behavior:** [What you expect to happen]
Should go to the {

**Actual behavior:** [What actually happens]
deletes the white space before the return and sees each newline as a new word.  

If you repeat this step by putting your cursor on the new line after the `{` and run `editor:delete-to-next-word-boundary`  It just deletes 1 newline but doesn't go to the return statement.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.23.0-dev-cbc2bdb20
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

This issue was broken out from  https://github.com/atom/atom/issues/4026#issuecomment-338884328 from @bcorcoran and @PhiLhoSoft as it is a separate issue.

**Comment by lee-dohm** [comment]
This seems to be the expected behavior. Since there haven't been any other comments here, we're going to close for now barring someone giving some more explanation as to why the current behavior should be changed.
