### ISSUE TITLE
Repeated overlay measurement in some circumstances

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#16077]
After #15894, @DavidLGoldberg reports that the [Jumpy](https://atom.io/packages/jumpy) package has become unusably slow.

Here's an image he posted where timing violations are being reported measuring overlay decorations containing labels:
![image](https://user-images.githubusercontent.com/578479/32305431-e51a5c8c-bf4b-11e7-8247-2f995d8303c8.png)

@leroix I'm going to assign you to this one since you have the most context on the change that caused it, but am happy to help out with it. Since this is on stable we should investigate it 🔜 .

**Comment by DavidLGoldberg** [comment]
Just to add, on my local dev build of Atom, for some reason I don't see the issue happening (and it's fast)

Is the master branch / dev build pulling from a more nightly branch that happens to have whatever, just fixed?

Although, last I checked atom-beta still had the issue.

In which case I'd say it's something to do with my mac environment, but I was also able to reproduce it on windows stable.

So just a heads up that the local dev build (at least mine) doesn't show the issue...
Thanks again for the help!

**Comment by nathansobo** [comment]
Looks like #16083 only applies cleanly to master, so reopening. We'll close this again when we have PR we can hotfix to 1.21 and 1.22.

**Comment by nathansobo** [comment]
Thanks for following up on beta and stable @leroix. Closing this out. We may not manage to get a hot-fix out for this, but the next minor release is slated for next week.

**Comment by leroix** [comment]
🙇
