### ISSUE TITLE
Atom showing old versions of files

### ISSUE THREAD

**Issue by Ben3eeE** [atom/atom#16081]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I opened Atom and it's showing old versions of files. Three tabs are showing up as modified and all tabs are old versions of the on disk versions.

I have a Windows/Linux dual boot. I opened Atom on my Linux dual boot in a folder that had modified on disk when booted in Windows.

I am not sure if I modified any of these files when booted into Linux but I am fairly certain that I did not. I did not make any changes to atom/atom-keymap back then.

In one of the files the diff between what Atom is showing and what is on disk is just the two commits that went into that file since I last opened the folder:

https://github.com/atom/atom-keymap/commits/master/src/key-binding.coffee

```
diff atom-showing master 
80c80
<         bindingRemainderContainsOnlyKeyups = false unless bindingKeystroke.startsWith('^')
---
>         bindingRemainderContainsOnlyKeyups = false unless isKeyup(bindingKeystroke) 
```

### Steps to Reproduce

Not 100% sure about the repro steps here since it happened over a couple of months.

1. Open Atom in atom/atom-keymap on Linux
1. Don't boot Linux for a couple of months while working on atom/atom-keymap when booted into Windows
1. Boot into Linux
1. Upgrade Atom to 1.21.2. I had some 1.12-1.14 installed I think because last I booted was to check out keymap issues on Linux. But not sure since it was months ago.
1. Open Atom

**Expected behavior:** Show the on disk versions because they are newer

**Actual behavior:** Shows old versions of files

**Reproduces how often:** Not sure. Every time I open atom in atom/atom-keymap on my Linux machine. I have not saved or closed any of the three tabs.

### Versions

Atom 1.21.2

### Additional Information

Refs: https://github.com/atom/atom/issues/8888

I sent over the output of: `atom.stateStore.load(atom.getStateKey(atom.project.getPaths())).then(state => console.log(JSON.stringify(state)))` to @maxbrunsfeld on Slack

I have https://github.com/atom/atom-keymap/commit/18f00ac307de5770bb8f98958bd9a13ecffa9e68 checked out in `atom/atom-keymap`

I don't have any community packages installed.

`git status` is showing all files as modified for some reason. This happens in every git folder I tried on.

The project folder is located on my Windows hard disk so it should not have been mounted?

/cc: @ungb I chatted with Max about this and he said to open a new issue for it.

**Comment by maxbrunsfeld** [comment]
[stateStore.json.zip](https://github.com/atom/atom/files/1439450/stateStore.json.zip)

Here is the result of [`atom.stateStore.load`].

**Comment by ungb** [comment]
Here are my repro steps on mac.

**NOTE:** you should first run `atom --clear-window-state` to make sure no saved session from a newer version atom is saved.

**NOTE:** you need a usb or a drive you can mount.

**NOTE:** turn off auto update for atom 

1. Download and run [atom 1.12.0](https://github.com/atom/atom/releases/tag/v1.12.0) 
1.  Open the mounted drive on atom.
1. Create a file called `test.md`
1. Add the following content and save.
```
THIS IS A TEST
THIS IS A TEST
THIS IS A TEST
```
1. Add a space some where to mark the file as modified.  
1. Close out of Atom and unmount the drive.
1. Reinsert the drive and modify the `test.md` file on another editor like sublime-text.  I changed the doc to
```
This is not a test
```
1.  Install Atom latest and open the same folder.
1.  Content is old.



See gif for repro:

Setting up the data on atom 1.12.0
![gif1](https://user-images.githubusercontent.com/5624870/32356087-049bcef2-bff0-11e7-9794-4b9d63c78351.gif)


Unmounting drive:
![gif2](https://user-images.githubusercontent.com/5624870/32356129-499fffdc-bff0-11e7-9b0b-ceb37324d77e.gif)

Reinserting drive and modifying data on sublime-text:

![gif3](https://user-images.githubusercontent.com/5624870/32356137-575ccc7c-bff0-11e7-99da-c78c179f0f76.gif)

Opening on Atom latest(off master for me):
![gif4](https://user-images.githubusercontent.com/5624870/32356147-5fd874f0-bff0-11e7-801d-56d361d34ec4.gif)

I'm unsure if it has to do with usb drive or not, but this was a way I could consistently repro.

**Comment by Ben3eeE** [comment]
@ungb These steps don't seem to auto update. It would be interesting to know if we can repro in a recent version of Atom.

**Comment by Ben3eeE** [comment]
I just reproduced twice using these steps on Ubuntu 16.04.
I used `1.13.0-beta10` and `1.23.0-dev-61b4fc7`

1. Open Atom using `1.13.0-beta10` in `atom/dalek`. I am on the `fix-for-asar` branch
1. Open `README.md` `test/dalek.test.js`, `test/runner.js`
1. Focus the `test/dalek.test.js` tab and put the cursor on line 15 (Not sure if needed but I did it)
1. Close Atom saving this state of three files open
1. Open `test/dalek.test.js` using gedit
1. Edit line 15 to say `let this_is_some_edit_i_made = null`
1. Add an empty line so there is a whitespace line before `beforeEach`
1. Close gedit
1. Open Atom `1.23.0-dev-61b4fc7`

**Expected:** All restored tabs to be on disk versions
**Actual:** `test/dalek.test.js` shows up as modified and is the version that I opened in 1.13.0-beta10
**Additional information:** `atom/dalek` is located on my Windows drive but it was mounted all the time.
