### ISSUE TITLE
Remember last search term in command palette

### ISSUE THREAD

**Issue by lukaskollmer** [atom/atom#16097]
### Description

The command palette (`cmd+shift+p` on macOS) should remember the most recent search term.

### Steps to Reproduce

1. Open the command palette
2. Search for some command, press enter to run that command
3. Now open the command palette again, you'll have to re-enter the command's name

**Expected behavior:** This should behave similar to the Find and Replace feature and remember the last search term

**Actual behavior:** The last search term is not remembered

**Reproduces how often:** Always

### Versions
macOS 10.12.6 (16G29)

`atom --version`
```
Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

`apm --version`
```
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.11.0
```

### Additional Information

n/a

**Comment by Ben3eeE** [comment]
There is a setting for this in the command-palette package settings:

![image](https://user-images.githubusercontent.com/1058982/32405215-661e2482-c161-11e7-8005-436b32bff31d.png)
