### ISSUE TITLE
Flaky test - renderer process crashed on windows when running the core tests

### ISSUE THREAD

**Issue by kuychaco** [atom/atom#16117]
https://ci.appveyor.com/project/Atom/atom/build/8790/job/pka8dbjrr6brygwh

<img width="943" alt="atom_8790_-_appveyor" src="https://user-images.githubusercontent.com/7910250/32471000-fc895220-c30f-11e7-90e1-d9975b05d1a3.png">

**Comment by 50Wliu** [comment]
This time it crashed on main process tests.  The leading `R` is missing.
https://ci.appveyor.com/project/Atom/atom/build/8882/job/ufgkle7eeb32o6aw
