### ISSUE TITLE
Flaky test - AtomApplication launch reopens any previously opened windows when launched with no path

### ISSUE THREAD

**Issue by kuychaco** [atom/atom#16118]
https://travis-ci.org/atom/atom/builds/298258681

<img width="1295" alt="build__12327_-_atom_atom_-_travis_ci" src="https://user-images.githubusercontent.com/7910250/32471065-4ed50376-c310-11e7-9997-d97fe1647bc3.png">

**Comment by 50Wliu** [comment]
This test has been very flaky recently, starting with (surprisingly) [the bump to 1.24-dev](https://travis-ci.org/atom/atom/builds/296856414).

**Comment by jasonrudolph** [comment]
Happened again in https://travis-ci.org/atom/atom/builds/299607852

**Comment by 50Wliu** [comment]
And https://travis-ci.org/atom/atom/builds/299396576.

**Comment by jasonrudolph** [comment]
And https://travis-ci.org/atom/atom/builds/299715392

**Comment by jasonrudolph** [comment]
And https://circleci.com/gh/atom/atom/6040
