### ISSUE TITLE
Idea: atom.log

### ISSUE THREAD

**Issue by smashwilson** [atom/atom#16112]
In Atom today, package authors (and core developers) can produce logging and diagnostic output by sprinkling `console.log()` statements throughout the source, and trying to remember to delete them before publishing - the JavaScript flavor of "printf() debugging". Chrome's dev tooling is pretty cool and lets you do stuff like format data into tables or use CSS to style it, but:

* All packages write to the same console. You can't filter out and focus on messages from a specific package.
* `console.log()` statements are either present or absent in a package. You can gate them with conditionals on a package setting, like we do in atom/github, but that's verbose and a wheel that you need to re-invent for each package. You also can't _retroactively_ enable logging if you're trying to investigate something that's already happened.
* Log data is transient. When you close Atom, it's gone. If you have a problem that crashes Atom, even if you do have diagnostics enabled, you can't figure out what happened after the fact. _(Unless Electron saves console output to a logfile somewhere by default?)_
* Log data is unstructured. Free-form `console.log` messages can't easily be programmatically analyzed after the fact, correlated, or analyzed.

An idea that's been rattling in my head for some time now is to introduce an `atom.log()` API into Atom core. Atom code can emit structured logging messages:

```js
atom.log({
  severity: 'warning',
  message: 'language server process has terminated',
  context: ['core', 'process management'],
  pid: lsp.getPID(),
  signal: err.signal
})
```

Atom can buffer these messages. They can be serialized to a log file somewhere within `${ATOM_HOME}`, with file size limits and log file rotation. And: we can build a pane to efficiently configure, display, filter, and search them.

One big prerequisite of this is being able to determine the package that called a method on the `atom` global, ideally without having to do things like inspecting the stack.

**Comment by matthewwithanm** [comment]
We should talk about this! Nuclide already has a console along with [a service](https://github.com/facebook/nuclide/blob/18bb1939f0df8759fc5dcf0629151ff1df5a360c/pkg/nuclide-console/lib/types.js#L140-L150) for interacting with it! In addition to being used for historical loggy stuff, it also has REPL-like functionality (variable expansion, etc) for the debugger.

<img width="713" alt="screen shot 2017-11-07 at 10 41 23 am" src="https://user-images.githubusercontent.com/126263/32511318-4aba5a50-c3a8-11e7-8c23-ab12b9036e8e.png">
