### ISSUE TITLE
Flaky test: GitRepository.refreshStatus() caches the proper statuses when a subdir is open ... timed out

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#16113]
[This test](https://github.com/atom/atom/blob/b7504a2a72838b3de293ae88d48e5ad7731d2c9d/spec/git-repository-spec.coffee#L228-L255) fails frequently on CircleCI. Recent failures include:

- https://circleci.com/gh/atom/atom/5602
- https://circleci.com/gh/atom/atom/5696
- https://circleci.com/gh/atom/atom/5973
- https://circleci.com/gh/atom/atom/5974

Example output:

```
Executing core render process tests...

GitRepository
  .refreshStatus()
    it caches the proper statuses when a subdir is open
      timeout: timed out after 60000 msec waiting for something to happen


Finished in 552.421 seconds
1879 tests, 9765 assertions, 1 failure, 2 skipped
```

**Comment by 50Wliu** [comment]
Believe this was fixed by #16111.
