### ISSUE TITLE
Allow the gutter to show relative line numbers

### ISSUE THREAD

**Issue by probablycorey** [atom/atom#1612]
https://github.com/atom/vim-mode/issues/54#issuecomment-36278523

**Comment by jamezb** [comment]
+1

**Comment by vito-c** [comment]
+1

**Comment by qianlifeng** [comment]
:+1:

**Comment by murphyrandle** [comment]
+1

**Comment by meznaric** [comment]
+1

**Comment by zpconn** [comment]
:+1: :+1:

I use this all the time in vim and really miss it in Atom.

**Comment by erickbarron** [comment]
:+1:

**Comment by edazdarevic** [comment]
+1

**Comment by isair** [comment]
+1

**Comment by kai3x5** [comment]
Anyone working on this ? Is there an existing solution already ?

**Comment by lee-dohm** [comment]
Looks like there are a couple different packages to do this:

* [relative-line-numbers](https://atom.io/packages/relative-line-numbers)
* [relative-numbers](https://atom.io/packages/relative-numbers)

I haven't tried them, so I can't endorse them. But there you go :grinning:

**Comment by erickbarron** [comment]
relative-line-numbers: I have been using it for a while, works great. I installed it after relative-numbers didn't work. One problem it had before was that it was buggy if you were using soft-wrap. But it looks like he fixed it as I made opened an issue. 

relative-numbers: Have tried it before, it doesn't really work so hot. It crashes (for me at least)

**Comment by kai3x5** [comment]
Huzzah! relative-line-numbers works! 

relative-numbers is broken for me.

**Comment by spirityy** [comment]
relative-line-numbers is broken too?
Is there an solution ?

**Comment by gggritso** [comment]
There was a [big pull request](https://github.com/atom/atom/issues/5038) a while back to add an API for custom gutters, but at the time I couldn't find documentation for it. I assume this is the "right" way to implement something like this.

**Comment by yuriteixeira** [comment]
The current `relative-line-numbers` package (https://atom.io/packages/relative-line-numbers) isn't available anymore (404 on the repo's page). I'm using https://github.com/dimatter/atom-relative-line-numbers (although manually downloaded into my `~/.atom/packages` folder) and it is working very well, as you can see in the screenshot below: 

![screenshot 2015-08-28 14 49 29](https://cloud.githubusercontent.com/assets/461055/9546571/065f0a22-4d94-11e5-989f-cb54b21b1ec8.png)

**Comment by maxbrunsfeld** [comment]
Yeah, now that custom gutters have landed, I think that we can leave this up to packages to implement. Thanks for pointing out `atom-relative-line-numbers`, @yuriteixeira. I'm going to close this out for now. If anyone feels that this is still an Atom core issue, I can reopen.

**Comment by justmoon** [comment]
I saw that `relative-line-numbers` was broken (no longer exists) and [atom-relative-line-numbers](https://github.com/dimatter/atom-relative-line-numbers) was not available via apm.

So I forked [atom-relative-line-numbers](https://github.com/dimatter/atom-relative-line-numbers), added some fixes and published the result on `apm`:

**[relative-numbers](https://atom.io/packages/relative-numbers)**

@maxbrunsfeld The custom gutters feature seems to be intended only for gutters that contain markers, it doesn't really expose an API powerful enough to change line numbering. That said, in my plugin I ended up using it for lifecycle management, which makes at least that part a little bit more robust I hope.

**Comment by qianlifeng** [comment]
@justmoon awesome

**Comment by shicholas** [comment]
thank you @justmoon!

**Comment by elliottetzkorn** [comment]
much appreciated @justmoon

**Comment by Fabs** [comment]
thanks @justmoon

**Comment by spirityy** [comment]
@justmoon awesome!thx!
