### ISSUE TITLE
[v1.23.0-beta0] regex incompatibility in wordRegex option in various cursor's methods

### ISSUE THREAD

**Issue by t9md** [atom/atom#16126]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

/cc: @maxbrunsfeld

In v1.23.0-beta, `cursor.getBeginningOfCurrentWordBufferPosition()` does not accept JS's regex passed as `wordRegex`.
Because it's handled PCRE engine in superstring.
This was not problem in previous version.
This incompatibility in `wordRegExp` option used in various cursor's methods confuse pkg author(and of course limit what I want to do in vim-mode-plus).

From https://github.com/atom/atom/pull/15776 , this regex incompatibilities seems to be introduced.

- OK: `cursor.getPreviousWordBoundaryBufferPosition`
- NG: `cursor.getBeginningOfNextWordBufferPosition`
- NG: `cursor.getBeginningOfCurrentWordBufferPosition`

I see error like this`Error: PCRE does not support \L, \l, \N{name}, \U, or \u`.

### Steps to Reproduce

1. Execute following code in chrome-dev console

```javascript
;(function regexIncompatibility() {
  const cursor = atom.workspace.getActiveTextEditor().getLastCursor()
  const wordRegex = cursor.subwordRegExp()
  try {
    console.log("OK", cursor.getPreviousWordBoundaryBufferPosition({wordRegex}))
  } catch (e) {}
  try {
    console.log("NG", cursor.getBeginningOfNextWordBufferPosition({wordRegex}))
  } catch (e) {}
  try {
    console.log("NG", cursor.getBeginningOfCurrentWordBufferPosition({wordRegex}))
  } catch (e) {}
})()
```

- In v1.23.0-beta: Only 1st case("OK") is succeeded.
- In v1.22.0: All success

**Expected behavior:** [What you expect to happen]

The `wordRegex` options used in cursor's method should be handled consistently(same regex should be supported ideally).

**Actual behavior:** [What actually happens]

Some cursors' method accept certain regex, but other throw exception with same regex.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%.

### Versions

```
Atom    : 1.23.0-beta0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
### Additional Information

In vim-mode-plus, in motion command.
It use `cursor.getBeginningOfCurrentWordBufferPosition` and pass various `wordRegExp` to achieve various movement in different command.

In subword movement command, I had call like following
- `cursor.getBeginningOfCurrentWordBufferPosition({wordRegex: cursor.subwordRegExp()})`
- From v1.23.0-beta, it throw error since passed regex is eventually handled by superstring's PCRE engine.

https://github.com/t9md/atom-vim-mode-plus/blob/741c38a425b2d9c60124b6852ea7cb568b1bed35/lib/motion.js#L452

**Comment by maxbrunsfeld** [comment]
Wow, I'm sorry about that @t9md, I guess our test coverage of the subword commands is not great. I'll fix the `subwordRegExp` to be PCRE-compatible and we'll get that into a beta hotfix.

**Comment by t9md** [comment]
Thank you for really quick fix for this!
I could confirm fix with following build.
```
~/Downloads% ./Atom\ 10.app/Contents/MacOS/Atom  --version
Atom    : 1.24.0-dev-fd15062
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
