### ISSUE TITLE
python 2.7 found but 3.6 installed

### ISSUE THREAD

**Issue by JPRuehmann** [atom/atom#16129]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
the build script shows/finds python 2.7 but the highest installed Version is 3.6.
How can I make it find and use the latest version?
I am using Kubuntu 16.04 LTS (32Bit)

### Steps to Reproduce

1. [First Step]
script/build
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
find and use 3.6

**Actual behavior:** [What actually happens]
find 2.7 use ???

**Reproduces how often:** [What percentage of the time does it reproduce?]
everytime

### Versions
git

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
The build script will fail if you use Python 3.x due to gyp only working on Python 2.  I highly doubt that you want it to use 3.6 :wink:.

**Comment by JPRuehmann** [comment]
Thanks, that was quick!
