### ISSUE TITLE
High CPU usage for opening untracked project folder when parent is massive git repo, even in safe mode

### ISSUE THREAD

**Issue by ansonhoyt** [atom/atom#16123]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

An "Atom Helper" process has had 70-90% CPU usage for hours. It seems to only happen when I open a project folder that contains a brand-new (almost empty) app created with [Create React Native app](http://facebook.github.io/react-native/docs/getting-started.html).

### Steps to Reproduce

1. Launch atom with `atom --safe` (also happens launching normally).
2. See that Activity Monitor shows three processes using minimal CPU: `Atom` and two `Atom Helper` processes
3. Add Project Folder, selecting the parent folder of an almost brand-new React Native app.

**Expected behavior:**

Editor spawns new processes, high CPU usage while loading, but CPU usage settles to a minimal amount in a few seconds.

**Actual behavior:**

* Activity Monitor shows three processes: `Atom` and three `Atom Helper` processes. One `Atom Helper` is using 70-90% CPU, and will stay this way (observed for minutes to hours).
* Removing the project folder does not end the process.
* Closing the window does end the process.

**Reproduces how often:**

100% Can reproduce consistently.

### Versions

```
$ atom --version
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.15.0

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1036
```

### Additional Information

Opening the problematic React Native app as a project folder is normal:

1. Launch atom with `atom --safe` (also happens launching normally).
Activity Monitor shows three processes using minimal CPU: `Atom` and two `Atom Helper` processes
2. Add Project Folder and select the React Native app.
Activity Monitor shows four processes using minimal CPU: `Atom` and three `Atom Helper` processes

The parent folder contains only a `notes.md` file.

**Comment by ansonhoyt** [comment]
![screen shot 2017-11-07 at 2 51 04 pm](https://user-images.githubusercontent.com/543751/32514522-3f99953c-c3cb-11e7-8060-150028ca1a5b.png)

**Comment by ansonhoyt** [comment]
Would uploading a ZIP of the [CPU Profile](http://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance) help? Here's a screenshot.
![screen shot 2017-11-07 at 2 55 23 pm](https://user-images.githubusercontent.com/543751/32514685-c9a79b8e-c3cb-11e7-9b66-592aa99356df.png)

To my ignorant eyes, it looks idle, so perhaps it doesn't "see" the `Atom Helper` generating all the CPU usage?

**Comment by ansonhoyt** [comment]
Not sure if this is helpful....just some ways I see CPU usage come and go....

1. My [create-react-native-app](https://github.com/react-community/create-react-native-app) project has been running in iOS simulator (`yarn run ios`). When I quit iOS Simulator and kill the process, the CPU usage settled down after about 5 minutes.
2. The project is not running and iOS Simulator is closed. Then I relaunched `atom --safe .` on the problematic project, and CPU is high on an `Atom Helper`. Watched for 5 minutes, and usage dropped to minimal CPU.
3. Running `yarn run ios` again did not trigger CPU usage. Opening the `notes.md` file kicked things off again.

I'll stop adding observations. I'm not sure what information would be helpful.

**Comment by lee-dohm** [comment]
Can you share the project that reproduces this issue? Or another repo that you can cause to reproduce this problem? Given only the information here, we don't have a lot to go on.

**Comment by ansonhoyt** [comment]
Pushed the repository https://github.com/ansonhoyt/react-native-prototype

* CPU is low when I open this repo as a project folder (`atom --safe .`)
* CPU is high when I open the parent folder, which is otherwise empty.
* If I don't touch anything, it settles after maybe 5 minutes. If I type a character or save, it stays busy for another 5 minutes, then settles again.

Agree this is odd. So it doesn't seem stuck....just doing a lot of work when I would expect minimal.

**Comment by ansonhoyt** [comment]
Oh my, **I found the source**. My home folder is a ginormous git repo! 💥 😭 

* All my other windows with project folders were fine, likely because they are git repos.
* I had problems only when opening this project's parent (not a git repo).
* I can reproduce with:

      mkdir ~/test
      atom --safe ~/test

Now I have to go delete this awful git repo that is tracking *everything*.

**Is there anything Atom can do** to help poor, error-prone souls like myself from hurting themselves?
* Can Atom guard against this? (unlikely...people sometimes need to do crazy things)
* Can Atom give insight into this scenario? Nothing in the troubleshooting guide gave me a clue. I'm no ace at attaching debuggers to rogue processes, so would be great if the team knew of something to add to the editor to point out this sort of thing.
* Can Atom make this perform so well, that we can get away with it?

**Comment by ansonhoyt** [comment]
VS Code detects this problem, works around it, and shows a helpful warning:
![screen shot 2017-11-09 at 10 06 02 am](https://user-images.githubusercontent.com/543751/32612191-a4efbdce-c535-11e7-90f4-829e493d670b.png)

Looks like a great solution.

**Comment by lee-dohm** [comment]
> My home folder is a ginormous git repo!

This is an issue that we're well aware of and we have a tracking issue for, though I don't recall where that is right now. @50Wliu do you remember where the current "Git init in Home directory" performance issue is?

Since this is a known issue, I'm going to close this for now and we'll follow up with the correct issue to subscribe to.

**Comment by 50Wliu** [comment]
Hmm this was supposed to be fixed in the github package in Atom 1.22 (https://github.com/atom/atom/pull/15654).  /cc @BinaryMuse

**Comment by thomasjo** [comment]
> Hmm this was supposed to be fixed in the github package in Atom 1.22 (#15654). /cc @BinaryMuse

@50Wliu That only affects the equivalent problems in the github package. The bigger problem here is located in Atom Core, and has been a problem since The Early Days of Yonder™.

We should probably do something similar to VS Code; detect this specific scenario, warn the user, and disable/limit Git functionality for that specific workspace/project.

**Comment by 50Wliu** [comment]
@ansonhoyt Have you deleted the home git repo yet?  If not, could you please click on the `0 files` item in the lower-right corner and screenshot the resulting dock item that pops up?

**Comment by ansonhoyt** [comment]
@50Wliu sure, just put it back. Here's the screenshot after clicking `0 files`:
![screen shot 2017-11-10 at 1 07 53 pm](https://user-images.githubusercontent.com/543751/32672242-56736f68-c618-11e7-872d-d59de6ebacdd.png)

**Comment by 50Wliu** [comment]
And is the high CPU usage still present?

**Comment by ansonhoyt** [comment]
Yes, I took the snapshot while 1 `Atom Helper` was seeing high CPU on an untracked project folder that is inside a tracked home folder.

While the home git repo is small, I think it is the untracked files that are killing it.
```
$ git ls-files --others --exclude-standard >> untracked-files.txt
$ cat untracked-files.txt | wc -l
 1735804
```

That's quite a few files. A few are large (~40GB Virtual Machines).

**Comment by 50Wliu** [comment]
I'm reopening this issue for now because this shouldn't be happening - neither Atom core nor github traverse parent directories looking for Git repositories.

@ansonhoyt can you figure out what the command line for the offending Atom Helper process is?  Not sure how you do it on macOS unfortunately.  Also, can you please try disabling the following packages and noting if the CPU usage goes down:
* github
* fuzzy-finder
* autocomplete-plus
* spell-check

**Comment by ansonhoyt** [comment]
I disabled each package in order, restarting (in safe mode) after each one. Now:
* github, fuzzy-finder, autocomplete-plus and spell-check are disabled
* 1 `Atom` process with low CPU
* 2 `Atom Helper` processes....1 with the same symptoms (high CPU for several minutes. goes high again if I do anything)

I'm not sure how to go about "figuring out the command line", but happy to try if someone can point me towards what I should do.

**Comment by ansonhoyt** [comment]
Just kept disabling, restarting, disabling. Problem persists after also disabling all of these:
* about
* archive-view
* autocomplete-atom-api, autocomplete-css, autocomplete-html, autocomplete-snippets
* autosave
* dev-live-reload
* find-and-replace
* git-diff
* language-git
* metrics
* status-bar
* timecop
* tree-view
* update-package-dependencies

(and no CPU spike if I `echo '*' .gitignore` and restart Atom)

**Comment by ansonhoyt** [comment]
I got `gdb` working (signed), if someone can tell me how to give you something useful with that. I tried getting a backtrace from `Atom Helper` but it doesn't look useful. Might need an Atom compiled with debugging symbols???

```
$ gdb -ex backtrace -p 69256
...
Reading symbols from /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper...(no debugging symbols found)...done.

warning: unhandled dyld version (15)
0x00007fffb730034a in ?? ()
#0  0x00007fffb730034a in ?? ()
#1  0x00007fffb72ff797 in ?? ()
#2  0x00007faa00000000 in ?? ()
#3  0x0700080607000806 in ?? ()
#4  0x00007faac3323500 in ?? ()
#5  0x00000000ffffffff in ?? ()
#6  0x0000000007000806 in ?? ()
#7  0x00007fff527efc28 in ?? ()
#8  0x0000000000000c00 in ?? ()
#9  0x00007fff527efc40 in ?? ()
#10 0x00007fff527efb80 in ?? ()
#11 0x00007fffa1a54434 in ?? ()
#12 0x00007fff00000000 in ?? ()
#13 0xffffffffb721f47a in ?? ()
#14 0x00007fff527efc24 in ?? ()
#15 0x07000101c3012270 in ?? ()
#16 0x00007fff527efc38 in ?? ()
#17 0x0000260300004013 in ?? ()
#18 0x00007fff527efc30 in ?? ()
#19 0x00000000ffffffff in ?? ()
#20 0x0000000000000000 in ?? ()
```

**Comment by Announcement** [comment]
experiencing the same issue.

**Comment by PentagramPro** [comment]
Had similar issue until I disabled git-diff and github packages
