### ISSUE TITLE
target[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by UziTech** [atom/atom#16135]
`atom.tooltips.add` errors when given a jQuery object

https://github.com/atom/atom/blob/843f91c8d2b5d436da2de5a64fbed42f1757a61b/src/tooltip-manager.js#L115-L119

the `target` in the for loop is what is throwing the error

## Applicable Issues

https://github.com/morassman/process-palette/issues/55
https://github.com/platformio/platformio-atom-ide-terminal/issues/403

**Comment by maxbrunsfeld** [comment]
Looks like this problem was introduced by converting TooltipManager to JS.

**Comment by UziTech** [comment]
looks like it was added in jQuery 2.2.0 and `space-pen` uses 2.1.4 so any package using `atom-space-pen-views` will have this issue.

https://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/

**Comment by UziTech** [comment]
Any way you can release another beta version with this fix soon? I keep finding more packages that don't work because of this issue.

**Comment by nathansobo** [comment]
@rsese I put this on the reactor queue. We should really hotfix this.
