### ISSUE TITLE
Memory leak with git submodules project

### ISSUE THREAD

**Issue by mevatron** [atom/atom#16137]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Memory leak on git submodules project.

### Steps to Reproduce

1. cd ~/your/path && git clone --recursive https://github.com/resin-os/resin-up-board.git
2. atom --safe
3. File >> Add project folder... picking the above path you checked out

**Expected behavior:** [What you expect to happen]
Atom doesn't consume all of my memory :)

**Actual behavior:** [What actually happens]
Atom consumes all of my memory...

**Additional information:**
atom looks like it utilizes 1 processor to 100%. So, maybe an infinite loop?

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime...

### Versions
```
> atom --version
Atom    : 1.21.1                                                                                                                                                                                                    
Electron: 1.6.15                                                                                                                                                                                                    
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
> apm --version
apm  1.18.5
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
```

**Comment by rsese** [comment]
Thanks for the report!  I'm unable to reproduce with Atom 1.22.0 on macOS 10.12.6  Can you share what operating system you're running?

> Atom    : 1.21.1                                                                                                                                                                                                    

There was a fix in 1.21.2 related to symlink loops though it doesn't seem like there's a loop in the project you referenced, but can you update to 1.22.0 and let us know if that makes a difference?

**Comment by mevatron** [comment]
I'm on Ubuntu 16.04 LTS, I'm using the webupd8 PPA to track the atom
releases. I'll definitely try updating to that release manually.

Thanks!

**Comment by mevatron** [comment]
So, I'm testing the Atom 1.22.0 release and it does look like that
corrected some things. The processor is no longer pegged at 100%. I was
reaching 1GB in about 2 minutes on 1.21, but it seems to have stabilized at
~900MB right now after about an hour of runtime.

So, I think it's fixed!

**Comment by 50Wliu** [comment]
Great to hear @mevatron!  If you experience it again on Atom 1.22.0 or above please create a new issue and we'll be happy to look into it further.
