### ISSUE TITLE
Error searching packages when not running as administrator on Windows 10

### ISSUE THREAD

**Issue by jjhegedus** [atom/atom#16139]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When running Atom on Windows 10 as Administrator and searching for packages in the Setting->Install->Install Packages pane, the following error occurs: 'Searching for "<package name>" failed.  Unexpected end of JSON input:'.

In addition, the following error appears in the console in the Chrome dev tools.

Fetching outdated packages and themes failed.
    at createJsonParseError (C:\Users\e77663\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-manager.js:726:19)
    at C:\Users\e77663\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-manager.js:243:29
    at exit (C:\Users\e77663\AppData\Local\atom\app-1.22.0\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (C:\Users\e77663\AppData\Local\atom\app-1.22.0\resources\app\src\buffered-process.js:338:17)
    at ChildProcess.<anonymous> (C:\Users\e77663\AppData\Local\atom\app-1.22.0\resources\app\src\buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

The errors do not occur when running Atom "as Administrator".

### Steps to Reproduce

1. Run Atom as a regular user on Windows 10
2. Open settings and go to install.
3. Search for a package.
4. No packages are listed.
5. Error is displayed.  'Searching for "<package name>" failed.  Unexpected end of JSON input:'
6. Open the Chrome Dev Tools and go to the Console tab to see the console error.

**Expected behavior:** Packages are listed.  No errors are displayed and no errors appear in the Chrome Dev Tools console.

**Actual behavior:** Error is displayed and no packages are listed.  Errors also are shown in Chrome Dev Tools console.

**Reproduces how often:** 100%

### Versions

Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by rsese** [comment]
Thanks for the report - did this behavior start randomly or after something in particular happened (e.g. after updating Atom)?

If this is a fresh install of Atom, can you describe how you installed it?

**Comment by jjhegedus** [comment]
It was a fresh install.  I installed it using the AtomSetup-x64.exe which I downloaded from atom.io, the 64bit installer link located on the home page.

**Comment by jjhegedus** [comment]
I ran ProcMon and found a few errors when opening atom as a regular user that did not occur when opening as admin.  The most suspicious was an ACCESS DENIED error when calling RegOpenKey on HKLM\System\CurrentControlSet\Services\WinSock2\Parameters from atom.exe.
