### ISSUE TITLE
version discrepancy between git and about

### ISSUE THREAD

**Issue by JPRuehmann** [atom/atom#16130]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
git is showing v1.10.0-beta0-4472-g843f91c, atom about is showing 1.22.0-dev-ec38e4f.
how can I make that corresponding?
I am using the master Branch.

[Description of the issue]

### Steps to Reproduce

1. [First Step]
git describe --tags
2. [Second Step]
open atom
3. [and so on...]
open help/about

**Expected behavior:** [What you expect to happen]
Both numbers corresponding

**Actual behavior:** [What actually happens]
Different Numbers

**Reproduces how often:** [What percentage of the time does it reproduce?]
everytime

### Versions
git

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Hmm, this is interesting, I see the same thing.  Maybe it's because our tags are created off of release branches and not master?  v1.10.0-beta0 was the last tag to be created from master and was probably right before we moved off the old Grunt build system.
