### ISSUE TITLE
Ubuntu 16.04 fullscreen button problem

### ISSUE THREAD

**Issue by Hamzali** [atom/atom#16134]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
On Ubuntu, when you first open the atom application and try to transition to fullscreen by using the fullscreen button on the window frame, app window vanishes.
### Steps to Reproduce

1. Open Atom
2. Press the fullscreen button

**Expected behavior:** Switch to fullscreen

**Actual behavior:** Vanishes

**Reproduces how often:** Everytime

### Versions
OS: Ubuntu 16.04, Atom version: 1.12.17
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

**Comment by rsese** [comment]
Thanks for the report!

> OS: Ubuntu 16.04, Atom version: 1.12.17

The current stable release version of Atom is 1.22.0 - can you update and let us know if you still see the same problem?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16134#issuecomment-342964432. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
