### ISSUE TITLE
Don't display the version number in a disabled menu item

### ISSUE THREAD

**Issue by bskendig** [atom/atom#16148]
### Description

Under the Atom menu in the macOS version, and under the Help menu in the Windows version, is a disabled menu item showing the current version of Atom. For example: "Version 1.22.0"

Menu items shouldn't be used to convey static information like this. "A menu is a list of commands available to the user in the current context" (https://msdn.microsoft.com/en-us/library/windows/desktop/bb226797(v=vs.85).aspx); a menu item should "initiate an action, toggle a state on or off, or display a submenu of additional menu items" (https://developer.apple.com/macos/human-interface-guidelines/menus/menu-anatomy/). A version number doesn't meet any of these guidelines.

Using a menu to display information like this is reminiscent of the 1990s, when guidelines were loose and developers would put all kinds of static text into menus.

The Atom version number can easily be found by selecting "About Atom" instead. 

### Versions

1.22.0, Mac and Windows

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

**Comment by rsese** [comment]
Thanks for the feedback!

We've passed along your suggestion to the maintainers team - because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close feedback issues after passing along the information to the maintainers to keep our backlog clean and focused.
