### ISSUE TITLE
Some text input causing system crash

### ISSUE THREAD

**Issue by Lloyd-v05** [atom/atom#16153]
### Prerequisites

* [X]
### Description

Long sequences of the same character causes Atom to consume all ram and cpu, crashing the system.

### Steps to Reproduce

1. Save your work or run Atom in a virtual machine
2. Open a new file
3. Hold down any alphanumeric key on your keyboard
4. Tears

**Reproduces how often:** 100%
### Versions
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Windows 10 Pro
### Additional Information
Running in safe mode increases the number of characters before system crash from about 20 to 30.
I know this is a bit of a niche bug, but it means leaning on your keyboard can crash your system.
Am I really the first person to find this issue, or is it something specific on my end? I haven't found any references to this before. Any info would be appreciated.

**Comment by rsese** [comment]
Thanks for the report @Lloyd-v05 - I can reproduce on macOS 10.12.6 with Atom 1.22.0 by just repeatedly pressing `a`.  I think this is maybe the same issue being investigated in https://github.com/atom/language-shellscript/issues/88 @50Wliu?

**Comment by 50Wliu** [comment]
Yep.  I believe a superstring issue will be created shortly for it.
