### ISSUE TITLE
Atom crashes when I press and hold a letter key

### ISSUE THREAD

**Issue by raunolipp** [atom/atom#16159]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I press and hold a letter key to insert text to unsaved new file, at around column 40 adding letters becomes slow and after a moment Atom memory usage skyrockets

### Steps to Reproduce

1. Open Atom
2. Press and hold a letter key
3. Wait until adding new letters becomes slow
4. Watch RAM usage skyrocket and your system eventually crash

**Expected behavior:** Insert the letter pressed and held

**Actual behavior:** Atom becomes unresponsive and eats all the system memory 

**Reproduces how often:** 100%

### Versions
**OS:** Fedora 26

**$ atom --version**
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**$ apm --version**
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.13.6

### Additional Information

This is the first install of Atom on this system. I haven't installed anything extra to Atom.

**Comment by Zireael07** [comment]
investigated in  atom/language-shellscript#88

**Comment by 50Wliu** [comment]
Thanks.  @Zireael07 is correct that the issue for it right now is atom/language-shellscript#88, but we're investigating it internally as well and will probably create a new issue in atom/superstring once we have enough info.
