### ISSUE TITLE
Main process gets into a state where input is blocked for hundreds of milliseconds

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#16151]
The Atom main process is intermittently getting into a state where it blocks keyboard input for long period of time, on the order of 500ms or more. It's happened to me at least twice over the past few weeks.

Nov 9th 2017: The timeline below happened today. I'm experiencing intermittent pauses of ~500ms. Notice there's no main thread JS being executed, but input handling is being delayed.

![screen shot 2017-11-09 at 5 22 19 pm](https://user-images.githubusercontent.com/1789/32636802-9c0f2a4e-c573-11e7-818a-f492fcc2fc9d.png)

Oct 17th 2017: Here I dug in deeper with native tracing on the main process. It definitely seems like we're blocking running some kind of script in the main process.

<img width="871" alt="screen shot 2017-10-17 at 9 10 01 pm" src="https://user-images.githubusercontent.com/1789/32636820-b2f9a3d8-c573-11e7-94b1-b999eee8d8e3.png">

To fully diagnose this, it would be helpful to upgrade to the latest Electron so it's easier to profile the main process with the standard dev tools. In the meantime though, we should probably consider precautionary action.

* There is still some sync I/O happening in the main process. Could that be the culprit? It has no business being there anyway and should be eliminated.
* Are we doing any spawning in the main process? We know that can be problematic.
* Are we doing any output sync IPC in the main process?

Lurking intermittent performance issues like this are the weakest link in our performance story. Getting into this state even a couple times a week is enough to undermine months of performance work spent on known code paths. We need to get to the bottom of this ASAP.

/cc @as-cii @maxbrunsfeld @iolsen

**Comment by as-cii** [comment]
> Getting into this state even a couple times a week is enough to undermine months of performance work spent on known code paths. We need to get to the bottom of this ASAP.

Agreed 100%.

> There is still some sync I/O happening in the main process. Could that be the culprit? It has no business being there anyway and should be eliminated.

`FileRecoveryService` performs synchronous I/O every time a file is about to be saved. This was introduced in https://github.com/atom/atom/pull/11828 and the main design reason for that was to be 100% sure that a file could be recovered later, but 1) people are still observing data loss issues, and 2) I was not aware that blocking the main process would block input on the renderer processes. Not sure if this is the only culprit, but definitely something to look into as as soon as possible.

**Comment by nathansobo** [comment]
> FileRecoveryService performs synchronous I/O every time a file is about to be saved

I'm not sure that lines up with what I was experiencing, which was intermittent pauses in the background as I was editing. I don't have auto-save enabled. What the heck is happening?

**Comment by maxbrunsfeld** [comment]
We could really easily make that service async now that you can return a promise from an onWillChange listener and have it delay the save.

**Comment by maxbrunsfeld** [comment]
That would avoid the sync file writes but also the sync IPC.

**Comment by maxbrunsfeld** [comment]
Optimistically closing this out after our work on async IO in the main process.
