### ISSUE TITLE
When undo/redo, cursor is not restored on different editor where original change was made.

### ISSUE THREAD

**Issue by t9md** [atom/atom#16176]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
  * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Btw, this is very old issue, just I haven't opened issue.

When undo/redo-ing by `core:undo`, `core:redo`, cursor is restored and autoscroll happens appropriately.
So we can see textual change done by undo/redo.
But after copy-ing editor by `cmd-k right` and did undo/redo, cursor is no longer restored, autoscroll not happens, so textual changes happens in off-screen.

I noticed this behavior at about end of last year.
https://github.com/t9md/atom-vim-mode-plus/issues/617

In following GIF, I made `CHANGE-1` and `CHANGE-2` on editor-1, then split-and-copy editor.
Undo/redoing on this new editor does not scroll to textual changes. 
![change-happen-offscreen](https://user-images.githubusercontent.com/155205/32737102-882f975e-c8dc-11e7-9c33-32745ffbf8ef.gif)

### Steps to Reproduce

1. Open editor-1, insert text in 3 different places. Each changes must be made in very different place which require editor scroll.
2. Undo/redo and see undo/redo restore cursor and scroll to restored cursor.
3. Split and copy active editor by `cmd-k right` then do undo/redo.
4. See cursor is not restored, no scroll-to-cursor happens. So textual changes by undo/redo happens at completely off-screen.

**Expected behavior:** [What you expect to happen]

When undo/redo-ing on editor I want to see changes, want cursor restored as long as underlying text-buffer is same.

**Actual behavior:** [What actually happens]

Atom/text-buffer does not restore cursor and doesn't autoscroll to changes made by undo/redo.
So user cannot see changes.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
Atom    : 1.23.0-beta0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

I also tried to find a way to **detect** if cursor restoration was happened or not on undo/redo timing by observing marker's change event.
But I couldn't find concrete way for that.
If this issue is not fixable, I still want to know the way to distinguish cursor restoration was succeeded or not on undo/redo timing.

**Comment by maxbrunsfeld** [comment]
@t9md If I understand properly, this is the expected behavior: when you open a given file in two different panes, each editor has its own independent set of cursors. The editor in the right-hand pane did not *exist* at the time `CHANGE-1` or `CHANGE-2` were inserted, so it does not have a previous cursor position to restore after the undo.

Are you saying that the right-hand editor's cursors should be updated to the old cursor position in the left-hand pane? That would mean that all of the editors would share the same set of cursors, which would be a very different model from what we do today.

**Comment by t9md** [comment]
@maxbrunsfeld Thanks for replay, I understand what you are saying for the current model.

> Are you saying that the right-hand editor's cursors should be updated to the old cursor position in the left-hand pane?

Yes I hope so.
Unless that, user can not see changes when it happened.

Even in un-copied/original editor, when we undo/redo, original cursor position is **force updated** with restored marker's one.
This is good since user can see changes, can continue editing from the place changes are made.

And this is the intention when user hit undo/redo key.
This intention is **same** even in copied editor(basically user don't care if it copied or not), so make sense to serve same behavior even in copied editor.

Another case we hit this limitation is when re-launch atomEditor after `cmd-w` consecutive closing editor and quit atom.
After relaunch, we can undo/redo but difficult to follow changes since cursor/scroll position is not updated.

> That would mean that all of the editors for a given buffer would share the same set of cursors, which would be a very different model from what we do today.

How about overwrite/replace cursor with restored marker by undo/redo **only in undo/redo case**?


## Summary of request

I tried to sum up my request as following.

- As long as underlying text-buffer instance is same
- When undo/redo was executed
- Replace(destroy and create?) current cursor position with cursor position saved as marker snapshot.
- In other word, when restoring marker from snapshot, it skips checks what editor that markerLayer belongs.
- Just replace all cursors in editors which shares same text-buffer.

**Comment by t9md** [comment]
My request is to treat cursor history as buffer global not editor local when restoring from snapshot.
Like buffer text history is treated as buffer global not editor local.

**Comment by 50Wliu** [comment]
Treating cursors as existing across different editors that share the same buffer would also help for issues such as https://github.com/atom/whitespace/issues/76.

**Comment by t9md** [comment]
@50Wliu  I read whitespace issue, that issue is somewhat related, but I thisk it is different topic in implementation-wise.

My request is to handle cursor restoration on undo/redo exceptionally.
And treat other case as it was before.

I think whitespace issue can be fixable by whitespace pkg side, by checking all editor's cursor position to guard unwanted removal of trailing whitespace.

**Comment by maxbrunsfeld** [comment]
I would be ok with updating `editor:undo` so that after calling `.undo()` on the buffer, it checked if the cursor was in any of the changed ranges, and if not, it moved the cursor to the changed location.

**Comment by t9md** [comment]
Great, thanks.
But checking cursor position contained in one of change is not work when change is made at off-cursor position.
Like when directly mutate buffet by editor.setTextInBufferRange(range, text).
I use this way of change in vim-mode-plus and my other pkgs.

**Comment by t9md** [comment]
So how I want to sync cursor after undo/redo is like( just imagining)

Pass all cursor’s marker layer ids to buffer.undo(ids) then get updated marker and layer-id as return value.
Then recreate cursor based on marker info on editors except returned marker layer belonged to.

**Comment by Ben3eeE** [comment]
Going to reopen so this can be closed when https://github.com/atom/atom/pull/16564 is merged.
