### ISSUE TITLE
Unable to install Atom on Windows with Software Restriction Policy enabled.

### ISSUE THREAD

**Issue by rchildress87** [atom/atom#16185]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am unable to run the AtomSetup-x64.exe NuGet package from a user profile directory on 64-bit Windows 7 or 8.1 Professional.  The computer has a Software Restriction Policy enforced via GPO that prevents running applications from user profile directories.  Typically, permission to do so while logged in as a standard user is granted by right-clicking on file and selecting "Run as administrator."

I cannot tell if this is an issue with the Atom installer or with NuGet packages.

### Steps to Reproduce

1. Enable a software restriction policy on a 64-bit Windows 7 or 8.1 Professional computer with a default security level of disallowed.  Set the enforcement properties to apply software restriction policies to all users except local administrators.
2. Download AtomSetup-x64.exe and save to a directory in the user's profile, say "Downloads."
3. Right click on AtomSetup-x64.exe and select "Run as administrator."
4. Enter the credentials of a local or domain administrator.
5. Accept the security warning by clicking "Run."

**Expected behavior:** Atom is installed in the current user's profile directory.

**Actual behavior:** A generic Windows Software Restriction Policy message is displayed, stating "Your system administrator has blocked this program.  For more information, contact your system administrator."

**Reproduces how often:** 100%

### Versions

Atom: 1.22.0
Windows: 6.1.7601 (Windows 7 SP1) or 6.3.9600 (Windows 8.1 Professional with Update)

### Additional Information

I have tried to circumvent this error, as I have to with .MSI and .BAT files, by opening AtomSetup-x64.exe in an elevated Command Prompt or PowerShell.  I have also tried using the --machine parameter.  These workarounds are unsuccessful.  I have not tested on 32-bit versions of Windows 7 or 8.1

**Comment by 50Wliu** [comment]
The installer we use explicitly does not allow itself to be run under an elevated account.  It actually will quit and relaunch itself with standard permissions.  Whether that's a good idea or not I can't say, but you will have better luck filing an issue on the https://github.com/Squirrel/Squirrel.Windows repository with your use case.
