### ISSUE TITLE
No Option to prevent unfolding when pressing ctrl + A

### ISSUE THREAD

**Issue by Megajin** [atom/atom#16183]
When you fold code, and press `CTRL + A` everything gets unfolded. This can be a pain in larger files... 
I think there should be an option to prevent this behaviour.

Here is an example:

Unfolded:
![unfolded](https://user-images.githubusercontent.com/29223243/32773916-0540053c-c92b-11e7-95c9-d1805061367f.PNG)

Folded:
![folded](https://user-images.githubusercontent.com/29223243/32773998-37fb3d3e-c92b-11e7-9e91-e38e5a2e8b10.PNG)

Now pressing `CTRL + A`:
![unfo](https://user-images.githubusercontent.com/29223243/32774021-4d0553d6-c92b-11e7-94c2-1ada3cb7d777.PNG)

Code Example:`
```javascript
class MyClass {
  
  constructor() {
    /**
    * Some Code.
    */
  }

  method() {
    /**
    * Some Code.
    */
  }
}
```

Regards,
Megajin

**Comment by 50Wliu** [comment]
Good news!  This has been fixed and I believe will be available starting in Atom 1.24.
