### ISSUE TITLE
Toggle line comments on blank line indents with spaces instead of tabs

### ISSUE THREAD

**Issue by AlexWayfer** [atom/atom#16193]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After the fix of the #15850, I guess, `editor:toggle-line-comments` works incorrectly in tab-indented file on empty indented lines.

### Steps to Reproduce

1. Open file with tab-based indentation
2. Go to the empty line
3. Indent
4. Run `editor:toggle-line-comments` (`ctrl-/`)

**Expected behavior:** Line indented by tabs (like the rest of the file) and starts with comment symbol(s).

```
» » foo
» » #·
```

**Actual behavior:** Indentation becomes by spaces.

```
» » foo
····#·
```

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.15.0
```

### Additional Information

No.

**Comment by rsese** [comment]
Thanks for the report, I can reproduce on Atom 1.22.1 with macOS 10.12.6 - with this snippet indented by tabs:

```js
var hi = function() {
	console.log("hi");
	
	console.log("bye");
}
```

On 1.22.1:

![toggle-line-comments-1 22 1](https://user-images.githubusercontent.com/734194/32908668-14ec718e-cab9-11e7-91d9-d3705ad32c4a.gif)

Previous behavior in 1.21.1:

![toggle-line-comments-1 21 1](https://user-images.githubusercontent.com/734194/32908663-11846d8a-cab9-11e7-970a-df4ca74533c5.gif)
