### ISSUE TITLE
Use default theme instead of first theme in safe mode

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#16196]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If the user has a custom theme selected and launches Atom in safe mode currently the first theme in the list is selected (`Atom Dark`). It would be great if Atom's default theme (`One Dark` currently) was used instead as it is a _much_ better theme, considering the Atom Dark themes have essentially had no updates in years.

### Steps to Reproduce

1. Select a custom theme (e.g Atom Material)
2. Launch Atom in Safe Mode

**Expected behavior:**

Atom's default theme (`One Dark`) is used.

**Actual behavior:**

The first theme in the list (`Atom Dark`) is used as a fallback.

**Reproduces how often:**

100% of the time.

### Versions

```
Atom    : 1.23.0-beta0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by 50Wliu** [comment]
What's the default theme when Atom is first installed?  Is it also Atom Dark?

**Comment by Arcanemagus** [comment]
I get `One Dark` for both UI and Syntax on a fresh `~/.atom`.

**Comment by 50Wliu** [comment]
Sounds like a good idea then.
