### ISSUE TITLE
git branch shows empty in status bar

### ISSUE THREAD

**Issue by stevenlordiam** [atom/atom#16198]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The git branch becomes empty in status bar after I upgraded atom to 1.22.1 on macOS. Also when I click Packages-Github-Toggle git tab, there's no unstaged file showing there(actually there should be). There is a .git file showing in my opened project folder.

### Steps to Reproduce

1. Open a git repo folder in atom
2. See the status bar in lower right corner

**Expected behavior:** 
See the branch names and click them

**Actual behavior:** 
The branch shows empty

**Reproduces how often:** 
After I upgrade to 1.22.1 today

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.6

### Additional Information

See the screenshots below
![screen shot 2017-11-15 at 15 40 03](https://user-images.githubusercontent.com/3217051/32860207-efa03af4-ca1e-11e7-9553-068d254d09ad.png)

![screen shot 2017-11-15 at 16 04 55](https://user-images.githubusercontent.com/3217051/32860196-e31a1110-ca1e-11e7-8d5a-81c8053774dd.png)

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/github if there's no existing issue already so we have it in the right place?
