### ISSUE TITLE
Doc comments should have a different color

### ISSUE THREAD

**Issue by JonasT** [atom/atom#16200]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Doc comments should have a different color at the minimum in the default themes, as suggested here: https://github.com/atom/atom/issues/13527#issuecomment-273399767

I tried `/* .. */` and `/** .. */` in a `.java` file and they end up with the same color. Trying the same with `comment.block.documentation.bla` (as specified here http://manual.macromates.com/en/language_grammars ) vs other types like `comment.line.bla` in my custom grammar, I did also observe not any difference both with the old Atom Dark theme as well as the Atom One Dark theme.

Making this even worse, both the Atom and Atom One theme (and a lot of other themes) have comments in a hideous super-low-contrast unreadable hipster color which basically makes it a pain to read them. Therefore, please make the doc comments default to another color to make them stand out more and so that at least for those, theme creators are incentivized to pick something that is actually readable.

### Steps to Reproduce

1. Open new file
2. Name `test.java`
3. Type the following:

```
/* test 1  */

/** test 2 */
```

**Expected behavior:** the doc comment is in a slightly different shade of color to make it stand out more in comparison to regular comments, and to encourage theme creators to keep at least the doc comments easily readable

**Actual behavior:** both comments are in the same barely readable low-contrast color

**Reproduces how often:** 100%

### Versions

```
[jonas@falcon ~]$ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
[jonas@falcon ~]$ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.3
[jonas@falcon ~]$ uname -a
Linux falcon 4.13.12-300.fc27.x86_64 #1 SMP Wed Nov 8 16:38:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[jonas@falcon ~]$
```

**Comment by 50Wliu** [comment]
You need `comment.block.javadoc` for Java.  If you think that should be changed to `.documentation` please file an issue on language-java.

**Comment by JonasT** [comment]
@50Wliu sorry, I don't fully understand. Are you saying for Java it should work? Because with Atom Dark One and a Java doc comment it doesn't seem to.

> If you think that should be changed to `.documentation` please file an issue on language-java.

Not really no.. or how should I know? I'm not even sure what you are trying to say. Is this supposed to work or not? Does it work for other languages already?

**Comment by 50Wliu** [comment]
I'm saying that if you want `/**`-style comments for Java to appear differently you need to target them with the `comment.block.javadoc` selector.

**Comment by JonasT** [comment]
So are you saying the official language-java grammar/java.cson file actually has a bug? I tested with the standard highlighting for Java as included per default in Atom..

**Comment by 50Wliu** [comment]
Yes, I believe so.  You can create an issue on the language-java repo (or even better, create a PR - should be a simple find-and-replace operation).

**Comment by JonasT** [comment]
Ok, I'm interested in doing that. Before I do so however, which is the selector that should actually work? `comment.block...`? Also, is there a theme that actually colors it so I can test it?

**Comment by 50Wliu** [comment]
Yeah, it should be `comment.block.documentation.java`.  Not sure if there's a theme that does it, but you can add this to your `styles.less`:
```less
atom-text-editor {
  .syntax--comment.syntax--block.syntax--documentation {
    color: green;
  }
}
```
