### ISSUE TITLE
Registration of protocol handler prompts when set to 'never'

### ISSUE THREAD

**Issue by damieng** [atom/atom#16201]
I get this with every launch even when I set the config to never;

![image](https://user-images.githubusercontent.com/118951/32871886-7ee98b48-ca38-11e7-943a-d1cc4c934e36.png)

I put some debugging in and at run-time when it does the check it is 'prompt' although when I examine it with atom.config.get after launch it is 'never'.

I suspect the check happens too early in the start-up to get the actual value.

Additionally we want to make sure this dialog doesn't come up when running specs?  It looks like it interferes with some of the UI tests.  @BinaryMuse

**Comment by BinaryMuse** [comment]
Thanks for the ping. I think you're right — we should wait for the config to be loaded before initializing the protocol handler installer. And it should be fine to guard against in safe mode. I'll work on those things today.
