### ISSUE TITLE
Protocol handler - can't remove, does not fix path on upgrade

### ISSUE THREAD

**Issue by damieng** [atom/atom#16202]
Right now there is no way to remove this OS integration and manually doing it involves registry hacking on Windows and who-knows-what on macOS.

I think the button should allow you to de-register using the Electron `removeAsDefaultProtocolClient(protocol[, path, args])` api.

Additionally the new remove code path should be called from squirrel-update.coffee on the `--squirrel-uninstall` path so we clean up properly and also it should be rewritten for the newest exepath if it exists on `--squirrel-updated` as the binary moves on Windows with every update.

cc @BinaryMuse

**Comment by BinaryMuse** [comment]
So you can't actually "remove" a protocol handler on macOS, you can only replace the default with something else. On my system, where there's only one handler for `atom://`, calling the `remote AsDefaultProtocolClient` method does nothing. For this reason, I decided not to add a button — but maybe we could add one for Windows?

As for the Squirrel stuff, that sounds reasonable. I'll give it a shot and give you a ping if I get stuck.
