### ISSUE TITLE
Atom markdown syntax highlight doesn't work on C#

### ISSUE THREAD

**Issue by ZombieLei** [atom/atom#16219]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Write the following test markdown code:
```
- 在代码里写字面数值:
  - 字面数值用16进制表示: 加0x前缀,例如: 0x002A
    - 打印格式化时候指定16进制: x或X, 例如
        ```cs
        System.Console.WriteLine("0x{0:X}", 42); // This line preview as brown
        System.Console.WriteLine("0x{0:x}", 42); // This line preivew as green, why?
        ```
    - 浮点数变字符串后,再从字符串变浮点,为了保证两个浮点数是一致的,可以用:
      ```cs
      string.Format("{0:R}", number);
      ```
    - Something new but still appear as green text.
```
2. In source code view, the texts below line 6 are all green.
3. In preview view(Ctrl+Shift+m), although have same code, line 5 and line 6 have different colors.

**Expected behavior:** 
1. In source code view, the texts below line 6 shall have the normal syntax colors.
2. in preview view, line 5 and line 6 shall have same colors.

**Actual behavior:**
1. In source code view, the texts below line 6 are all green.
2. In preview view(Ctrl+Shift+m), although have same code, line 5 and line 6 have different colors.

**Reproduces how often:** 
Every time.

### Versions
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

**Comment by Ingramz** [comment]
Syntax highlighter expects you to provide a more complete C# file (with classes, functions, etc...). It doesn't know whether you have inserted a short snippet or complete file, so it always assumes that it is the whole document. This is the same as creating a new file, pasting these two lines and choosing C# as the language. You'll see incorrect highlighting.

GitHub has difficulties parsing those same lines as well:
```cs
System.Console.WriteLine("0x{0:X}", 42); // This line preview as brown
System.Console.WriteLine("0x{0:x}", 42); // This line preivew as green, why?
```

Compare it to this:
```cs
class MyProgram
{
    static void Main()
    {
        System.Console.WriteLine("0x{0:X}", 42); // This line preview as brown
	System.Console.WriteLine("0x{0:x}", 42); // This line preivew as green, why?
    }
}
```

Regarding why everything remains green after ` ``` ` characters, it is a [known issue](https://github.com/atom/language-gfm/issues/21) that is being worked on.

**Comment by 50Wliu** [comment]
Thanks @Ingramz.
