### ISSUE TITLE
Unable to open R files

### ISSUE THREAD

**Issue by ekhco** [atom/atom#16226]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom is unable to open R files. Environment: Mac OS X, Atom version 1.22.1

### Steps to Reproduce

1. Double click R file from finder (does't work)
2. Drag R file into new Atom window (doesn't work)

**Expected behavior:** I expect the R file to open in Atom

**Actual behavior:** nothing happens. Atom loads, in the launcher tray icon, it lists old files that were open. I can't show all windows, nothing shows. The file just doesn't open.  There appears to be a phantom window somewhere that I can't see.  I can't even create a new window.

**Reproduces how often:** now it is all the time. I literally can't work. Back to Sublime.

### Versions

Mac OS X 10.12.6

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report - if you start Atom in safe mode (`atom --safe`) and then try to open an R file from within Atom (<kbd>cmd-o</kbd>), does that work?

And are you only having trouble with R files?  If you try to open a plain text file does that work?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16226#issuecomment-345341067. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
