### ISSUE TITLE
custom settings lost

### ISSUE THREAD

**Issue by denis-gorin** [atom/atom#16220]
Very sad, all of my settings for core and installed packages whuch stored in config.cson were lost after last (1.22.1) update

**Comment by nasredin** [comment]
i guess i reached same error...  i have blank atom now :)

**Comment by rsese** [comment]
Hey @denis-gorin @nasredin - I'm really sorry that you two hit this error.  The team is using https://github.com/atom/atom/issues/14909 for investigation so you can subscribe there for updates if you'd like.  We'll go ahead and close this one as a duplicate.
