### ISSUE TITLE
Atom keeps crashing after upgrading to Atom IDE

### ISSUE THREAD

**Issue by mittalyashu** [atom/atom#16225]
## Prerequisites

- [x] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
- [x] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
- [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
- [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
- [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

## Description

Atom keeps crashing after upgrading to Atom IDE
![image](https://user-images.githubusercontent.com/29014463/32957940-0f22f572-cbe3-11e7-8056-5796d07c467b.png)

Here's the [discussion](https://discuss.atom.io/t/atom-keeps-crashing-after-upgrading-to-atom-ide) on Atom Discuss.

## Expected behavior

It should not show this error or it should not crash everytime.

## Actual behavior

Same as in description.

## Reproduces how often

It get crashs often times, and so after getting anoying i have to stop using Atom Text editor.

## Versions

Atom version `1.21.2`. *(When I started getting the problem)*
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Then I thought of installing the latest verision of atom
Atom    : 1.22.1 *(So, now this is the version installed in my machine)*

**Comment by rsese** [comment]
Thanks for the report @mittalyashu - I know you shared some details in the Discuss post but so everyone can see this information here in this issue, can you fill out the issue template so we can take a look?

**Comment by mittalyashu** [comment]
But, where's the issue template?

**Comment by 50Wliu** [comment]
https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md

**Comment by mittalyashu** [comment]
Done.

**Comment by mittalyashu** [comment]
Here's the task manager which shows the performance of Atom text editor.
When I was opened it was taking too much of memory and then it was closed.

![image](https://user-images.githubusercontent.com/29014463/32989756-a75e0dee-cd42-11e7-992b-6410b3583a7e.png)

**Comment by mittalyashu** [comment]
I recently inspected the atom and it shows up this.

![image](https://user-images.githubusercontent.com/29014463/32991516-1be9e488-cd63-11e7-9aff-a2560e16b3e7.png)

**Comment by rsese** [comment]
@mittalyashu can you share your list of installed packages?

```
apm list --packages
```

Also, it looks like you checked the box that says you reproduced in safe mode but that's not the case correct?  Based on the discussion, it looks like you mentioned this is related to the Atom IDE packages but those are disabled in safe mode because they're not core packages.  

If you disable all your community packages except `atom-id-ui` and whichever ide language packages you're using, does Atom still crash?

**Comment by mittalyashu** [comment]
I am sorry, I cannot list all the packages because I uninstalled the Atom and deleted the `.atom` to give it another try and hoping to remove the atom completely from the machine and installing it would fix the problem, but still, the problem was coming.

If you want the list of the packages, you can see the bunch of the packages I have installed in the screenshot below.

![list of the packages I have installed earlier on my machine](https://user-images.githubusercontent.com/29014463/32991297-8711bbaa-cd5e-11e7-9cc8-97f3eac4d84f.png)

>  but those are disabled in safe mode because they're not core packages.

Well, I am not sure about that but when I run the atom in safe mode, the atom still gets crashed.

(even before removing atom completing from my machine) I even try removing the package one by one to see if any package is created this error, but still, nothing changed.

**Comment by lee-dohm** [comment]
As I stated in Slack, please include a crash log. If you're concerned about posting what could be private information on the issue, please email the crash log to atom@github.com and reference this issue.

**Comment by mittalyashu** [comment]
There is no crash log with `.dmp` extension.

It has only this file.
[operation_log.txt](https://github.com/atom/atom/files/1488888/operation_log.txt)

**Comment by mittalyashu** [comment]
#12422. Check out this issue.

He is also getting the same issue *(sort of)*.

**Comment by mittalyashu** [comment]
Atom is still crashing even in the beta version.

**Comment by lee-dohm** [comment]
The only similarity on that issue is that Atom crashed. Unfortunately, there are so many possible reasons for Atom to crash that it is highly unlikely that it is related in any way.

**Comment by lee-dohm** [comment]
![image](https://user-images.githubusercontent.com/1038121/33088515-ab6c946c-cea2-11e7-8aa2-499bae983408.png)

@mittalyashu uploaded the above image to Slack just now. It appears that `msmpeng.exe` (a component of the built-in security system Windows Defender) is also crashing frequently, which points to a much deeper problem in the OS configuration, a possible hardware problem, or the system itself is infected.

We recommend following up with Microsoft to find out what could be causing the crash in Windows Defender. Until that is resolved, we won't be able to investigate this further.
