### ISSUE TITLE
Projects Pane Messed up

### ISSUE THREAD

**Issue by Mdstumpfy123** [atom/atom#16237]
Hello I somehow messed up where my settings open. It doesn't open as a tab. It opens where the project pane is suppose to be. Here is a image I have been trying to google it and cant find a answer. Can I have help. Please.

![image](https://user-images.githubusercontent.com/23144480/32996777-071722b6-cd4d-11e7-82da-3356af4af0e0.png)

**Comment by iamhansen** [comment]
HaVe yOu TrIEd cTRL + R?

**Comment by Mdstumpfy123** [comment]
yes didn't work

**Comment by Mdstumpfy123** [comment]
Nevermind it fixed itself
