### ISSUE TITLE
why I often can't open the editor

### ISSUE THREAD

**Issue by Niefee** [atom/atom#16239]
### Description
![qq 20171120094731](https://user-images.githubusercontent.com/10347495/32998645-e525a642-cdd7-11e7-86fc-c2388ff7afe2.jpg)

When I reboot or open, will often fail

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by mittalyashu** [comment]
There are a bunch of people, who are getting the similar problem. 

My atom text editor is crashing all the time. I think the problem is in the recent update of the atom itself.

**Comment by Niefee** [comment]
This issue lasted for a long time

**Comment by mittalyashu** [comment]
Can you share the screenshot of the timecop stats?

**Comment by rsese** [comment]
Thanks for the report @Niefee - can you update the issue body with the issue template information?  The information there is helpful for us when looking at issues and it's also helpful to know that you've tried the relevant suggestions from the [debugging documentation](http://flight-manual.atom.io/hacking-atom/sections/debugging/).  In particular, please let us know what version of Windows you're running and if you can reproduce in safe mode (`atom --safe`).

**Comment by Niefee** [comment]
My system is window 10，I don't know what can provide you with information，This problem is not to appear every time. But I restart the computer, and then open the software, the problem of the risk is very big

**Comment by Niefee** [comment]
```
$  atom --version

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 ia32
python 2.7.13
git 2.14.1.windows.1
visual studio
```

**Comment by rsese** [comment]
Can you share your list of installed packages?

```
apm list --installed
```

And any crash logs?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs

Lastly, are you able to reproduce the crash in safe mode?  Start Atom with this command to check:

```
atom --safe
```

**Comment by Niefee** [comment]
i am able to open in safe mode, this is the installed packages  list:
```
apm list --installed
Community Packages (47) C:\Users\Administrator\.atom\packages
├── activate-power-mode@2.6.0
├── atom-beautify@0.30.6
├── atom-ide-ui@0.6.0
├── atom-material-syntax@1.0.7
├── atom-material-ui@2.0.6
├── atom-ternjs@0.18.3
├── atom-wakatime@7.0.4
├── autocomplete-paths@2.12.1
├── autoprefixer@3.7.1
├── block-comment@0.4.3
├── busy@0.7.0
├── busy-signal@1.4.3
├── chester-atom-syntax@0.3.0
├── color-picker@2.2.5
├── docblockr@0.13.2
├── file-icons@2.1.14
├── git-time-machine@1.5.9
├── hyperclick@0.1.5
├── ide-css@0.2.0
├── ide-html@0.4.1
├── ide-typescript@0.7.0
├── ide-vue@0.1.8 (disabled)
├── intentions@1.1.5
├── js-hyperclick@1.12.2
├── language-babel@2.79.0
├── language-markdown@0.25.1
├── language-vue@0.23.1
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.0
├── linter-jshint@3.1.6
├── linter-ui-default@1.6.10
├── markdown-preview-enhanced@0.15.0
├── markdown-preview-plus@2.4.16
├── markdown-scroll-sync@2.1.2
├── markdown-writer@2.7.3
├── minimap@4.29.7
├── open-in-browser@0.5.2
├── open-terminal-here@2.3.1
├── path-hyperclick@0.3.0
├── platformio-ide-terminal@2.7.0
├── px2rem-plus@0.3.1
├── script@3.17.3
├── simplified-chinese-menu@5.3.5
├── teletype@0.2.2
├── tortoise-svn@0.5.1
├── tree-view-sort@0.8.1
└── vue-hyperclick@0.2.0
```

**Comment by rsese** [comment]
> i am able to open in safe mode, this is the installed packages list:

Thanks for confirming - if there's no problem in safe mode, then that likely means a community package is causing the issue:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

You can disable all community packages and then re-enable one by one to try and pinpoint which is causing the problem.  Or if you can remember which packages you installed around the same time you started seeing the crashes, you could also try disabling those first.
