### ISSUE TITLE
Suggestion: disable hw acceleration by default

### ISSUE THREAD

**Issue by JonasT** [atom/atom#16247]
### Description

It appears from https://discuss.atom.io/t/why-is-atom-so-slow/11376/209 that a lot of people have bad performance from the start due to hw acceleration issues. While this is not as bad as crashes and such (which are probably already taken care of by chromium's built-in black list of really bad drivers) this still gives people a bad first experience with the editor. Since I assume with Atom's barely changing UI in comparison to like, a complex dynamic rendered 3d world, the hw acceleration doesn't do terribly much anyway, I suggest reconsidering whether it should be enabled by default at all.

**Comment by 50Wliu** [comment]
> Since I assume with Atom's barely changing UI...the hw acceleration doesn't do terribly much 

This may come as a surprise to you but editor scrolling is entirely implemented using the GPU.  We use the `transform: translateY(amount)` property which signals to Chrome to use hardware acceleration.  You can test this yourself in Windows Fall Creators Update (and above) by opening the Task Manager, enabling the GPU column, and then looking at the value change when you scroll an editor in Atom.

![gpu-scrolling](https://user-images.githubusercontent.com/2766036/33068169-bb7506f6-ceb0-11e7-9ecf-0f362e69a8e5.gif)

Therefore it seems like hardware acceleration is fairly important to a smooth scrolling experience.  I'll defer to someone more experienced in this area like @nathansobo though in case I got something wrong.

**Comment by AlynxZhou** [comment]
Starting Atom with --disable-gpu seems faster, but some renderer work got broken in my computer.

**Comment by lee-dohm** [comment]
Thanks for the suggestion. As @50Wliu pointed out, Atom does use the hardware acceleration quite a bit. Additionally, disabling hardware acceleration across the board will have an extremely negative performance impact for many people. So this is not something that we'll be implementing anytime soon.
