### ISSUE TITLE
atom/dot-atom/keymap.cson example is wrong?

### ISSUE THREAD

**Issue by isoeugenol** [atom/atom#16249]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

ctrl-p and ctrl-shift-p is move-up,down in the atom/dot-atom/keymap.cson 
but i think they are toggle key

### Steps to Reproduce

1. [First Step]
ctrl-shift-p
![image](https://user-images.githubusercontent.com/31752719/33057224-1248d810-cecd-11e7-9d2c-551b8468200f.png)

2. [Second Step]
ctrl-p
![image](https://user-images.githubusercontent.com/31752719/33057297-6f8dcfe4-cecd-11e7-9924-33beed73c456.png)

3. [and so on...]
![image](https://user-images.githubusercontent.com/31752719/33057139-b11c3b72-cecc-11e7-8cd2-fce6e44d0a11.png)
**Expected behavior:** [What you expect to happen]
# 'atom-workspace':
#   'ctrl-up': 'core:move-up'
#   'ctrl-down': 'core:move-down'

**Actual behavior:** [What actually happens]
# 'atom-workspace':
#   'ctrl-shift-p': 'core:move-up'
#   'ctrl-p': 'core:move-down'

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
The examples are taken from the macOS keymap.  Given that these are just examples for how the keymap file should be formatted, I'm not convinced that we need to change them.  If you can find two keybindings that are identical across macOS, Windows, and Linux, though, please feel free to create a PR.
