### ISSUE TITLE
Scroll sensitivity is hard to set due to auto-completion

### ISSUE THREAD

**Issue by sbrandwoo** [atom/atom#16243]
### Description

In Editor settings when typing a Scroll Sensitivity value it auto-completes as you type; if you don't type fast enough this will lead you to the wrong value.

### Steps to Reproduce

For example, if I want to set my sensitivity to 120:

1. Type 1, value is now 1, this is too low so value is set to 10
2. Type 2, value is now 102
3. Type 0, value is now 1020, which is too high and value is set to 200

**Expected behavior:** Value should only be auto-corrected when I've finished typing

**Actual behavior:** Value is auto-corrected between key presses

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4

Ubuntu 16.04.3 LTS

**Comment by rsese** [comment]
Thanks for the report - I can reproduce this behavior on macOS 10.12.6 with atom 1.22.1.

**Comment by rsese** [comment]
Sorry just realized this should probably be in https://github.com/atom/settings-view, I'll move it later tonight.
