### ISSUE TITLE
Build Error 'script/bootstarp'. Ubuntu 16.04.3

### ISSUE THREAD

**Issue by GaramPaul** [atom/atom#16248]
When I've tried 'bootstrap' at the first time, it was  /usr/bin/env 'node': No such file or directory
So i did following step. 

sudo update-alternatives --install /usr/bin/node node /usr/bin/nodejs 1 --slave /usr/bin/js js /usr/bin/nodejs
sudo apt-get install curl
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install  -y nodejs

After these steps, i tried again. i got another error...
I've been looking for the solution in issues... but i couldn't find it.

garam@ubuntu:~/atom$ script/bootstrap
Node:	v6.12.0
Npm:	v3.10.10
Installing script dependencies
prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/garam/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install http 200 https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install info downloading to @ /home/garam/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v48-linux-x64.tar.gz.1940-8a1ac934fd27e.tmp
prebuild-install info renaming to @ /home/garam/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install info unpacking @ /home/garam/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/garam/OpenSourceDir/final_Project/atom/script/node_modules/leveldown/build/Release/leveldown.node
prebuild-install info unpack required /home/garam/OpenSourceDir/final_Project/atom/script/node_modules/leveldown/build/Release/leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!
/home/garam/OpenSourceDir/final_Project/atom/script/node_modules/electron-mksnapshot/download-mksnapshot.js:16
  if (error != null) throw error
                     ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TLSWrap.onread (net.js:568:26)
npm ERR! Linux 4.10.0-40-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--loglevel=error" "install"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron-mksnapshot@1.6.0 install: `node ./download-mksnapshot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-mksnapshot@1.6.0 install script 'node ./download-mksnapshot.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-mksnapshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download-mksnapshot.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-mksnapshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-mksnapshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/garam/OpenSourceDir/final_Project/atom/script/npm-debug.log
child_process.js:495
    throw err;
    ^

Error: Command failed: npm --loglevel=error install
prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install info looking for cached prebuild @ /home/garam/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install http 200 https://github.com/level/leveldown/releases/download/v1.9.0/leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install info downloading to @ /home/garam/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v48-linux-x64.tar.gz.1940-8a1ac934fd27e.tmp
prebuild-install info renaming to @ /home/garam/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install info unpacking @ /home/garam/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.9.0-leveldown-v1.9.0-node-v48-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/garam/OpenSourceDir/final_Project/atom/script/node_modules/leveldown/build/Release/leveldown.node
prebuild-install info unpack required /home/garam/OpenSourceDir/final_Project/atom/script/node_modules/leveldown/build/Release/leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!
/home/garam/OpenSourceDir/final_Project/atom/script/node_modules/electron-mksnapshot/download-mksnapshot.js:16
  if (error != null) throw error
                     ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TLSWrap.onread (net.js:568:26)
npm ERR! Linux 4.10.0-40-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--loglevel=error" "install"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron-mksnapshot@1.6.0 install: `node ./download-mksnapshot.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-mksnapshot@1.6.0 install script 'node ./download-mksnapshot.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-mksnapshot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./download-mksnapshot.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-mksnapshot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-mksnapshot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/garam/OpenSourceDir/final_Project/atom/script/npm-debug.log

    at checkExecSyncError (child_process.js:472:13)
    at Object.execFileSync (child_process.js:492:13)
    at module.exports (/home/garam/OpenSourceDir/final_Project/atom/script/lib/install-script-dependencies.js:9:16)
    at Object.<anonymous> (/home/garam/OpenSourceDir/final_Project/atom/script/bootstrap:28:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by 50Wliu** [comment]
ECONNRESET indicates a network error.  If you are behind a proxy, ensure that Node is setup to correctly read your proxy.  Otherwise, try again at a later time.
