### ISSUE TITLE
Atom can't "find" carriage return \r or "newline" \n in large files

### ISSUE THREAD

**Issue by andsat** [atom/atom#16246]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

trying to do a find/replace to remove newlines and carriage returns in a 800mb file, Atom says no results even though I can clearly see them myself.

### Steps to Reproduce

1. open huge file full of new lines and carriage returns
2. do a find/replace (in regex mode) for \n or \r
3. watch as atom says no results

**Expected behavior:** [What you expect to happen]

expected to find all of the new lines and carriage returns

**Actual behavior:** [What actually happens]

found no results

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Mac OS X 10.11.3 El Cap

**Comment by rsese** [comment]
Thanks for the report!  You can use https://github.com/atom/find-and-replace for find and replace issues.

With a 800mb file I'm surprised Atom didn't freeze for you because of https://github.com/atom/find-and-replace/issues/653 though.  Do you see any error in devtools console>

**Comment by imachequa** [comment]
@rsese I missed to find the answer in your link (find-and-replace package).
While searching a bit more I'd found proper way is to put in find: \r?\n|\r (with regedit activated) 

just curious whether I'd missed that information in your provided answer/link.

thanks in advance
