### ISSUE TITLE
Space encoding in markdown headings

### ISSUE THREAD

**Issue by sekmo** [atom/atom#16244]
In markdown headings, some spaces are badly encoded (so github readmes shows hashes instead of the actual markdown heading).

(It would be nice to check the invisibles in markdown, but spaces are not rendered even if "show invisibles" are enabled in the config)

I opened the file with an hex editor and it says that it's a C2A0.
![screen shot 2017-11-20 at 13 32 27](https://user-images.githubusercontent.com/336970/33018599-57915482-cdf7-11e7-91dd-3b37a0fc6e41.png)

![screen shot 2017-11-20 at 13 40 57](https://user-images.githubusercontent.com/336970/33018908-8019f71e-cdf8-11e7-98cf-c114dd5febdd.png)

**Comment by rsese** [comment]
Thanks for the suggestion! I see you opened an issue in https://github.com/atom/markdown-preview/issues/520 as well - I think that's a better place for this issue so I'll go ahead and close this one.
