### ISSUE TITLE
suggestion : Resize pinned datatip display

### ISSUE THREAD

**Issue by goojungpotato** [atom/atom#16261]
![1](https://user-images.githubusercontent.com/28240079/33135897-1ca7c10c-cfe7-11e7-88fb-98b5b96eb2b4.PNG)

Description
I often use this function when I usually code. However, there are times when I want to see more at a glance when I look at the api of each language. There is an inconvenience because the size can not be adjusted here. So I would like to be able to adjust the size of the pinned data tip freely.

**Comment by rsese** [comment]
Thanks for the suggestion, I believe this should go in https://github.com/facebook-atom/atom-ide-ui.
