### ISSUE TITLE
Atom crash. Too many file watchers?

### ISSUE THREAD

**Issue by roccomuso** [atom/atom#16268]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm on `Ubuntu 16.04`, Atom crash when launched together with another node process. They both watch files.

From my findings On Linux (or Mac) we have a max number of system watchers we can place at an IO level (from my understanding). So for large projects, it seems that atom is trying to watch just way too many files.

Result: Atom crash, and my other node process throw the `ENOSPC ` exception.
On ubuntu, for my user, the limit is `8192`, I got it with `cat /proc/sys/fs/inotify/max_user_watches`.

### Steps to Reproduce

1. Open a couple of projects with hundreds of files watched.
2. Run atom and wait..

**Expected behavior:** Do not crash. Or crash with an error message.

**Actual behavior:** Crash without a error message.

**Reproduces how often:** 90%

### Versions

```
Atom    : 1.22.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

I'm running `Ubuntu 16.04`.

**Comment by 50Wliu** [comment]
> my other node process throw the ENOSPC exception.

How much free space do you have left on your machine?  If the answer is "quite a lot", can you temporarily increase the number of available watchers and see if Atom continues to crash?
`sudo sysctl fs.inotify.max_user_watches=32768`

**Comment by roccomuso** [comment]
@50Wliu If you mean hard drive free space the answer is quite a lot yeah (over `130GB`).

Increasing the available watchers numbers to `32768` seems to fix the problem.
I get no more `ENOSPC` exceptions from the other node processes and atom still works.

**Comment by 50Wliu** [comment]
Ok, in that case you can permanently increase the number of available watchers using `echo 32768 | sudo tee -a /proc/sys/fs/inotify/max_user_watches`.  We are working on improving this situation by overhauling how Atom watches files, so hopefully you'll see Atom consume less watchers soon!

**Comment by roccomuso** [comment]
@50Wliu that's great but even if Atom consume less watchers you never know how many watchers other process will instantiate. And Atom will keep crashing. I'd suggest at least a more verbose error. Right now it crashes silently.
