### ISSUE TITLE
Jump-to-cursor behaviour glitches horizontal scrollbar & text rendering

### ISSUE THREAD

**Issue by Aerijo** [atom/atom#16260]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For a file with enough lines to require vertical scrolling, placing the cursor at the bottom and scrolling to the top will put the cursor out of the view. Pressing a key (eg. spacebar) will cause the view to jump down to the cursor (expected behaviour), but in the process glitches the horizontal scrollbar (if present) into appearing further up the window than it should. The text beneath the scrollbar will also disappear in chunks, likely because it is no longer considered "visible". In the extreme case, no text will be rendered at all and the view will appear devoid of text (like a blank file).

Swapping to a different tab/application and back resolves the issue. Trying to scroll horizontally manually also fixes the issue. Closing the find/replace box fixes it.

### Steps to Reproduce

1. Run `atom --safe`
2. Type random gibberish for many lines, at least until vertical scrolling is required
3. Place cursor on bottom line
4. Scroll to top, such that cursor is below view window
5. Press `spacebar`
6. Observe that horizontal scrollbar has moved, and text will disappear while still in view.

**Expected behavior:** [What you expect to happen]
It jumps to cursor and behaves as if the user scrolled there like normal.

**Actual behavior:** [What actually happens]
Glitches the horizontal scrollbar up the view window and causes text to derender early.

Shown in following GIF (horizontal scrollbar not present, but text rendering glitch shown)

![kapture 2017-11-23 at 0 03 42](https://user-images.githubusercontent.com/22167388/33131284-cf081d34-cfe1-11e7-8d29-ee97c0a3c8c6.gif)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.6

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

macOS 10.13.1

**Comment by 50Wliu** [comment]
@Aerijo thanks for reporting.  This should already be fixed in the Atom 1.23 betas.
