### ISSUE TITLE
Different versions when double clicking on icon and associate files

### ISSUE THREAD

**Issue by gemal** [atom/atom#16278]
my Atom editor was automatically updated to 1.23.0-beta1

now when I double click on the Atom icon I get version 1.23.0-beta1

but when you double click on a .php file I get version 1.23.0-beta0

Argh

Something is not working in the update procedure

**Comment by ungb** [comment]
Hey @gemal,

Are you running mac or windows?

**Comment by gemal** [comment]
Sorry forgot to write. Windows 10

**Comment by ungb** [comment]
hmm. I've never seen this before on Windows.  @damieng do you have any ideas on how they can fix this issue or why it's occurring?  I'll add it to my todo to see if I can repro this

**Comment by damieng** [comment]
Launch Atom 1.23.0-beta1 then go into Settings > System and uncheck (if it's checked) then re-check "Register as File Handler"

You can get into this odd state if you launch Atom before it's finished updating if I remember correctly.

**Comment by gemal** [comment]
Thank you. That worked:
`Launch latest Atom then go into Settings > System and uncheck (if it's checked) then re-check "Register as File Handler"`
