### ISSUE TITLE
I can't enter a space character.

### ISSUE THREAD

**Issue by fredRos** [atom/atom#16271]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I can't enter a space character in text

### Steps to Reproduce

1. Open any text file.
2. Hit  `ab c` where the third key is the space button

**Expected behavior:** A space between `b` and `c` 

**Actual behavior:** `abc`

**Reproduces how often:** always

### Versions

Debian Linux 9, gnome on wayland
```

~$ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

```

### Additional Information

I just downloaded the deb pkg today to try out atom with juno for julia. I thought it may be due to some juno thing but it also appears in safe mode

**Comment by rsese** [comment]
Can you share a screenshot of what the [keybinding resolver](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings) shows when typing the space character in safe mode?  Also, I'm assuming the space character otherwise works on your computer in general and with other apps when it stops working in Atom?

**Comment by fredRos** [comment]
Yes, they key works in all other programs. As you can see in the screenshot, atom sees `space` but it does insert the space character. Other characters are inserted, so the buffer isn't read-only.
![screenshot from 2017-11-27 08-42-54](https://user-images.githubusercontent.com/1833693/33255701-241e11b4-d34f-11e7-91a2-c9d4f39818e5.png)

**Comment by rsese** [comment]
It sounds like this is a fresh install of Atom 1.22.1 correct?  Just clarifying that this isn't something that worked ok previously but broke for you after updating to 1.22.1.

> gnome on wayland

Is there any difference if you try with Xorg instead of Wayland?

**Comment by youngheart80** [comment]
I think I have run into the same issue. I don't use Atom a lot, but I popped over into it today and couldn't enter space characters.  Symptoms are the same as OP. I've started the debug process, but haven't completed. Safe mode doesn't affect it and keybinding resolver just shows "space". This isn't a fresh install but one that updated.

Windows 10 Home
Atom: 1.22.1
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0

**Comment by rsese** [comment]
> This isn't a fresh install but one that updated.

@youngheart80 so this wasn't an issue before but now that you've updated to 1.22.1, the space key doesn't work at all?  Does temporarily resetting to factory defaults make a difference?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by youngheart80** [comment]
@rsese - This does seem to be something that popped up in the most recent 1.22.1 rev. I haven't had any issues with it previous to yesterday, but again, I'm not a frequent user so it's been probably 2 weeks since I was last in. To further clarify - I know for sure that the space doesn't get inserted into a editor window. And I think (will confirm) it also might not work in things like the package search field for example.

I'll try doing the factory reset a little later this morning and report back.

**Comment by youngheart80** [comment]
@rsese - Sorry for the late reply. 

Reset to factory defaults did fix it in my case. I had disabled the few packages I had added without effect but this did. I guess I can start investigating each to see which is causing the issue and submitting the bug reports there.

**Comment by rsese** [comment]
Ahhh great thanks for confirming @youngheart80 - if you figure out which package causes the problem, feel free to mention it here.

@fredRos it sounds like you had a fresh install of Atom?  Just to rule out any other settings, can you also try temporarily resetting to factory defaults and see if that makes a difference?

**Comment by fredRos** [comment]
I already set to factory defaults. It didn't help unfortunately


Am 11.12.2017 um 19:07 schrieb Robert Sese:

**Comment by fredRos** [comment]
I managed to fix my system so I can start X11 desktop environments again (instead of wayland). Under KDE, I can enter a space again.  It must some weird interaction between the various graphics systems. I'm happy it works now. I think it will be interesting to atom developers to understand why the space key can't be inserted but other characters are unaffected. Unfortunately I can't help with more details.
