### ISSUE TITLE
unable to scroll, layout broken in one specific file

### ISSUE THREAD

**Issue by davidak** [atom/atom#16275]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have one textfile, when i open the tab with it, there is no scroll bar and i can't use the scroll wheel on my mouse. To reach the bottom of the file i select text and move the cursor down. When i do that the layout of Atom breaks. The status bar is in the middle of the application and the tabs disappear.

![bildschirmfoto 2017-11-25 um 21 49 48](https://user-images.githubusercontent.com/91113/33235356-815269d4-d237-11e7-8504-31456d020cec.png)

### Steps to Reproduce

1. click on tab where this one file is opened
2. try to scroll down (nothing happens)
3. select text all the way down
4. ???
5. app broken

**Expected behavior:** usable app that don't breaks :)

**Actual behavior:** app that breaks in some situations :(

**Reproduces how often:** 100% until the workaround

**Workaround:** Close the tab and open it again. it then has a scroll bar and you can normally scroll with the mouse wheel. so duplicating this file don't lead to this problem

#### OS X 10.10.5
```
imac:~ davidak$ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
imac:~ davidak$ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.11
git 2.5.4
```

### Additional Information

I can't provide that file because it contains sensitive informations.

**Comment by rsese** [comment]
Thanks for the report - it doesn't seem like your screenshot is from safe mode.  Is there any difference if you start in safe mode (`atom --safe`)?

Also, have you worked on this particular file in older versions of Atom with no problem?

About the file itself, can you share how large it is?  Is there anything else interesting about it?

**Comment by davidak** [comment]
No differences in safe mode.

I'm not sure since when i have the issues. The file started with 2 lines and i add one some times... it's about 100 lines now. each line follows this syntax: `2017-11-29;site.tld+hash@domain.tld`

**Comment by rsese** [comment]
Can you try clearing  saved state?  Make sure to save/backup your work since you'll lose any unsaved data:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by davidak** [comment]
Yes. I don't had the issue before, so i need some time to see if it solves it permanently.

**Comment by twitwi** [comment]
I had the same issue, under linux, after updating from an old 1.9.6 to 1.23.1.
Clearing the saved state with `atom --clear-window-state` solved it for me.
Thanks.

**Comment by mraspaud** [comment]
@twitwi 's workaround worked for me.

**Comment by rsese** [comment]
@davidak just to confirm, did clearing saved state resolve the issue for you so far?

**Comment by davidak** [comment]
@rsese i don't had the issue again. Thanks!
