### ISSUE TITLE
Memory/CPU leak (fuzzy-finder)

### ISSUE THREAD

**Issue by darkdragon-001** [atom/atom#16273]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I start _atom_ normally or in safe mode, I can see that a process has about 25-30% CPU and one of them has increasing memory allocation (I closed it after it allocated several GB).

The command line from this process is `/opt/atom/atom /opt/atom/resources/app.asar/src/task-bootstrap.js /home/mschnirring/.atom/compile-cache /opt/atom/resources/app.asar/node_modules/fuzzy-finder/lib/load-paths-handler.js`.

Atom shows the home folder in tree view.

When I start atom via `atom --atom --clear-window-state` it works. But when I close it immediately and start it in normal mode afterwards, the same problem occurs again.

When I start atom in another folder, the problem also does not exist.

### Steps to Reproduce

1. Start atom in home folder

**Expected behavior:** Allocate a fixed amount of memory and little CPU when idle

**Actual behavior:** Increasing memory allocation and high CPU

**Reproduces how often:** 100%

### Versions

> Distributor ID:	Ubuntu
> Description:	Ubuntu 17.10
> Release:	17.10
> Codename:	artful

> Atom    : 1.22.1
> Electron: 1.6.15
> Chrome  : 56.0.2924.87
> Node    : 7.4.0

> apm  1.18.8
> npm  3.10.10
> node 6.9.5 x64
> python 2.7.14
> git 2.14.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by darkdragon-001** [comment]
This might have something to do with wine installed:
It creates a symlink `~/.wine/dosdevices/z:` which links to `/`.

When I turn off the option _Follow Symlinks_, this problem also does not exist.

**Comment by rsese** [comment]
> When I turn off the option Follow Symlinks, this problem also does not exist.

Thanks for the report - I wonder if this is a duplicate of https://github.com/atom/fuzzy-finder/issues/329?  That issue is fixed in 1.23 which is currently in beta - can you install the beta and confirm if you can still reproduce?

**Comment by darkdragon-001** [comment]
I can confirm that this problem is solved in the beta version 1.23.
