### ISSUE TITLE
Mac: Menu bar item does not flash while using a shortcut

### ISSUE THREAD

**Issue by SamuelSchepp** [atom/atom#16274]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using a shortcut on macOS, which fires a menu bar entry, the menu bar title of that dropdown menu flashes blue. Open a new TextEdit.app document and press CMD+a a few times. You will see that the "Edit" menu bar item on the top of the screen flashes with a blue highlight.

How it should look like:

<img width="704" alt="screenshot 2017-11-25 19 46 22" src="https://user-images.githubusercontent.com/11752441/33233664-b9a1c320-d219-11e7-82fa-dbb1adead204.png">

### Steps to Reproduce

1. Open an empty text file in atom
2. Press CMD+a

**Expected behavior:**
The "Edit" menu bar title item flashes with a blue highlight, like TextEdit.app or any other native app does it.

**Actual behavior:**
The "Edit" menu bar title item does not flash.

**Reproduces how often:**
100%

### Versions
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information
none

**Comment by rsese** [comment]
Thanks for the report - I do see the behavior you're describing on macOS 10.12.6.  Not sure if this is more an Electron issue or not though?  VS code has the same behavior but Slack doesn't....
