### ISSUE TITLE
Disabling/Enabling packages not working

### ISSUE THREAD

**Issue by Wj2ma** [atom/atom#16293]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Disabling a package does not always call the deactivate function on a package, so it doesn't get disabled.

### Steps to Reproduce

1. Generate new test package that is linked
2. Open command palette and make sure the package works.
3. Open settings view > packages, and find the test package
4. Disable the package (note that this will work).
5. Enable the package and disable it again.
6. Toggle the package in command palette again.

**Expected behavior:** The package should be disabled so it should not appear in command palette (and should not work).

**Actual behavior:** The package still appears in the command palette and works.

**Reproduces how often:** 100%

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.13.5

### Additional Information

Note that the key step to reproduce it is to enable the package and **not toggle it** before disabling it. If you toggle it while enabled, then disabling will work afterwards. Also, if you enable it and not toggle it, and uninstall the package, the package will still be enabled even after uninstall.

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce the behavior you're seeing, it seems to be related to the generated package itself (it's not reproducible across packages, I can't reproduce with [Teletype](https://atom.io/packages/teletype) but could with [expose](https://atom.io/packages/expose)).  

I added some debug log statements and do see that `deactivate()` isn't getting called like you mentioned when running through your repro steps - it looks like that happens when `activate()` doesn't seem to be called either, I wonder if it's related to some of the discussion about `activationCommands` in the [Flight Manual](http://flight-manual.atom.io/hacking-atom/sections/package-word-count/)?  In any case, we should move this issue to https://github.com/atom/package-generator - I can do that later tonight if you don't get to it.

**Comment by Wj2ma** [comment]
Sure, I'll report the issue there too. However, I'm not sure if it is the package-generator's issue. I'm assuming that a package with an activate and deactivate function should always get called when it is enabled/disabled, and I think that is on the package-manager.

**Comment by rsese** [comment]
Thanks @Wj2ma :bow:

> I'm assuming that a package with an activate and deactivate function should always get called when it is enabled/disabled,

I was wondering that too (I'm not a package author so don't have experience writing packages) but reading that section of the flight manual I linked to it says:

> The activate command does a number of things. For one, it is not called automatically when Atom starts up, it is first called when one of the activationCommands as defined in the package.json file are called.

For the package generated by the package manager, it does have an activationCommand defined (the toggle) which seems to line up with your description ("If you toggle it while enabled, then disabling will work afterwards.").

**Comment by Wj2ma** [comment]
Ah, I found this:
`activationCommands: an Object identifying commands that trigger your package's activation. The keys are CSS selectors, the values are Arrays of Strings identifying the command. The loading of your package is delayed until one of these events is triggered within the associated scope defined by the CSS selector. If not specified, the activate() method of your main export will be called when your package is loaded.`
It seems like the package is not loaded until an activationCommand is triggered. Therefore, the activate and deactivate does not get fired.
I'm not sure what goes on behind the scenes, but I believe the source of the issue is that deactivate somehow also disables the activation hook command from appearing (but since the package isn't loaded, the command still appears from cache or something?), and toggling a command does not check for the package being disabled before opening it.
