### ISSUE TITLE
Three finger swipes scrolls content

### ISSUE THREAD

**Issue by chbk** [atom/atom#16304]
Using Atom 1.22.1 on macOS Sierra 10.12.6

### Description

Content in the editor scrolls with three finger swipes. This conflicts with custom gestures already assigned to three finger swipes.

### Steps to Reproduce

1. Disable three finger swipes in the trackpad options

![s](https://user-images.githubusercontent.com/7478535/33494913-e5564a40-d6c4-11e7-9949-b3b918b631d8.png)

2. Open a file in the editor and swipe with three fingers. The content scrolls.

### Additional Information

No other application has this behaviour. Content scrolls on two finger swipes making three finger swipes redundant. It also conflicts with custom gestures set with applications such as [Better Touch Tool](https://www.boastr.net/).

**Comment by rsese** [comment]
Thanks for the report!  I see the same behavior as you described on macOS 10.12.6 but:

> No other application has this behaviour

I checked a couple of Electron apps and see that Slack and VS code will also scroll in this case when I 3 finger swipe up or down.  Then I checked Google Chrome, Firefox, and Safari and they all scroll in this case as well - am I mis-understanding what you meant here?

**Comment by chbk** [comment]
I tried again and realised other apps do have this behaviour as well. However, they all prioritise custom gestures over default ones when better touch tool is enabled. Atom is the only app that conflicts with custom gestures. Any idea what is causing this?
