### ISSUE TITLE
Shift + F2 should select text

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#16300]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Holding `Shift` while jumping to a bookmark doesn't select the text.

### Steps to Reproduce

1. Open any file with text/code inside
2. Go to any line and create a bookmark
3. Now go a few lines below the bookmark
4. Press and hold `Shift` and hit `F2` 

**Expected behavior:** All the lines between where the cursor was the momento I pressed `F2` and where the bookmark is should be selected.

**Actual behavior:** The cursor moved to the bookmark but the text wasn't selected.

**Reproduces how often:** 100%

### Versions

Any version.

**Comment by rsese** [comment]
Thanks @alexandernst 👍  Since https://github.com/atom/bookmarks/pull/91 was added, it looks like this works in the case where there's a bookmark below where your cursor is:

```
'atom-text-editor':
  'shift-f2': 'bookmarks:select-to-next-bookmark'
```

But not the case you described above where the next bookmark wraps past the end of the file.  I think we should maybe move this to https://github.com/atom/bookmarks?  I can do that later tonight if you don't get to it.

**Comment by alexandernst** [comment]
@rsese did you open a new issue in the right repo?

**Comment by rsese** [comment]
Sorry, doing that now @alexandernst thanks for the reminder :+1:

**Comment by alexandernst** [comment]
@rsese next time please don't close tasks before moving it.

**Comment by rsese** [comment]
Good idea, that will help things not fall through the cracks if neither person moves an issue :+1:
