### ISSUE TITLE
Using Atom inside WSL opens a blank file and System 32 as project folder in Atom for Windows

### ISSUE THREAD

**Issue by tommymcgahee** [atom/atom#16310]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using Atom to open a WSL file, Atom for Windows opens the file as blank and the System 32 folder is added as a Project Folder instead of the current WSL folder.

I apologize if I am using the wrong terminology for this. Please ask for any clarifications and I'll be happy to provide them. 

### Steps to Reproduce

1. Open Bash on Ubuntu on Windows (or any other bash shell)
2. Type atom [your file]

**Expected behavior:** [What you expect to happen]

Atom opens file with its contents and adds the current WSL folder as the project folder.

**Actual behavior:** [What actually happens]

Atom opens the file but it is blank and the System 32 folder is added as the project folder.

The file path in Atom says "C:\WINDOWS\system32\[name of file] which is wrong.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Constant.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

This occurred on latest stable Atom for Windows version and latest beta (1.23.0-beta1 x64)

OS is Windows 10 Pro with latest updates.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

This seems to have started after updating Ubuntu last night.

**Comment by tommymcgahee** [comment]
I guess I misunderstood what was possible in WSL. This explains what can and cannot be done with editing / opening WSL files from inside WSL using Windows programs - https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/ 

Is this information still correct with the Windows 10 Fall Creators Update?

**Comment by rsese** [comment]
Yeah I poked around a bit and found I can work with files under `/mnt/c/User/username`, otherwise I see the same error.  Issues like https://github.com/Microsoft/WSL/issues/2004 seem to confirm this?

> Is this information still correct with the Windows 10 Fall Creators Update?

The WSL [community links](https://github.com/Microsoft/WSL#community-links) might point to good places to ask that question.

**Comment by hcwoodrujm** [comment]
I get this issue:
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

Git Bash on WIndows

cd into working directory and command "atom filenm" will open the file in the directory but it will be empty (ie erases all content in file)
