### ISSUE TITLE
升级到 1.22.1 后，修改系统文件又不出现指纹了，只有密码输入框了

### ISSUE THREAD

**Issue by gooking** [atom/atom#16315]
升级到 1.22.1 后，修改系统文件又不出现指纹了，只有密码输入框了

之前的版本还是会弹出指纹的，手指按一下就可以了

**Comment by 50Wliu** [comment]
@gooking 对不起，但是如果你不用英文我们帮不了你。请利用[这个文件](https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md)。谢谢！
***
Sorry, but unless you use English we are unable to help you.  Please use [the issue template](https://raw.githubusercontent.com/atom/atom/master/ISSUE_TEMPLATE.md).  Thanks!
