### ISSUE TITLE
Node 9.0.0 and NPM 5.5.1 Compatibility Issue

### ISSUE THREAD

**Issue by CaptainJohnyAppleSeed** [atom/atom#16314]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
There seems to be a compatibility issue between NodeJS v9.0.0 and NPM v5.5.1.
NPM does not support NodeJS according to the attached screenshot (below).
This should be recognized since there may be components of Atom that are using npm v5.5.1 or older.

### Steps to Reproduce

1. Make a clean version of a Linux Ubuntu VirtualBox (16.04.3)
2. In terminal use the following command:
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
3. Restart/Reopen terminal and use the following commands:
nvm install v9.0.0
nvm alias default v9.0.0
npm install -g npm
npm config set python /usr/bin/python2 -g

**Expected behavior:** I would expect that nothing would happen (install happens successfully)

**Actual behavior:** I get an error message (attached) stating that npm does not support v9.0.0

**Reproduces how often:** 100%
### Versions
Linux Ubuntu 16.04.3 Virtual Box
npm 5.5.1
nvm 9.0.0 (had to set to 8.9.0)
Atom Version information
Atom: 1.24.0-dev-e21c757
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0

### Additional Information
Discussed this with arcanemagus on Slack at 9:16PM EST December 3, 2017
![node_npm_compatability_issue](https://user-images.githubusercontent.com/31418316/33533790-5161c072-d871-11e7-9d47-27dcc595f1b8.png)

**Comment by 50Wliu** [comment]
Copying my response from Slack:
> This looks strictly like a Node <-> npm issue that isn't related to Atom.  No matter what version of Node you build Atom with, it will still use Node 7.4.0 and npm 3.10.10.

I'll be closing this for now.
