### ISSUE TITLE
Git tab not working in ubuntu x86

### ISSUE THREAD

**Issue by storm1er** [atom/atom#16312]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Build the last version b930ad122520cdb8fef8a15766d54a93a8f38b12 and [1.22-releases's branch](https://github.com/atom/atom/tree/1.22-releases)  for my ubuntu 16.04 x86 without any error (fresh install of ubuntu & git this morning) And i can't Use the git tab ... As you can see in the screenshot below, git gutter is ok, file's color are ok, but git tab think it's not a repo ... 

### Steps to Reproduce

1. Build the last version b930ad122520cdb8fef8a15766d54a93a8f38b12 or [1.22-releases's branch](https://github.com/atom/atom/tree/1.22-releases) on x86 linux
2. Open atom in a git repo
3. Enjoy ?

**Expected behavior:** Git tabs should show us edited / added files

**Actual behavior:** Ask me to git init my project

**Reproduces how often:** Everytime i'm using atom in this system

### Versions

Fresh install of x86 ubuntu, up to date.

```bash
$> apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 ia32
python 2.7.12
git 2.7.4
```
```bash
$> atom --version
Atom    : 1.22.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

![capture-20171203-194737-1920x1053](https://user-images.githubusercontent.com/9821946/33528564-da05f1f0-d862-11e7-9502-441602e2d5d1.png)

**Comment by 50Wliu** [comment]
Thanks for creating an issue @storm1er.  Can you please reopen this on the [atom/github](https://github.com/atom/github) repository instead?  Thanks!

**Comment by storm1er** [comment]
It's done https://github.com/atom/github/issues/1265 Sorry about this mistake.
