### ISSUE TITLE
New unsaved file content lost after window close

### ISSUE THREAD

**Issue by canac** [atom/atom#16329]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Content of untitled file buffers are discarded when closing their associated window.

### Steps to Reproduce

1. Open any folder in an Atom window.
2. Create a new untitled file _without saving it to disk_.
3. Type anything into the buffer.
4. Click the red x on macOS to close the window.

**Expected behavior:** I expect Atom to prompt me to save my unsaved file.

**Actual behavior:** Atom closes without confirmation, discarding the content of that unsaved file.

**Reproduces how often:** Always.

### Versions

```
Atom    : 1.23.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
macOS   : 10.13.1
```

### Additional Information

Reproducible in safe mode. Not reproducible in Atom stable.

**Comment by rsese** [comment]
Thanks for the report - I can reproduce everything you mention except the last part where you mention that the changes are discarded.  If I re-open the same folder I opened in step 1, the unsaved buffer is there with my changes, is that not the case for you?

**Comment by canac** [comment]
@rsese You're right. I must have subconsciously been using the `advanced-open-file` package to reopen the project instead of the native command. Reopening via the "Application: Open" command  does indeed restore that unsaved buffer. Sorry for wasting your time; I'll refile this issue on that package.

**Comment by rsese** [comment]
No problem @canac, thanks for the followup :v:
