### ISSUE TITLE
Right clicking on selected text deselects the text

### ISSUE THREAD

**Issue by Ingramz** [atom/atom#16324]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![selection-broken](https://user-images.githubusercontent.com/1017132/33610482-54ccbc8a-d9d4-11e7-8fb3-4eb744d81d05.gif)

Previously:
![selection-ok](https://user-images.githubusercontent.com/1017132/33610546-7bb18286-d9d4-11e7-9a72-8802e244e15b.gif)

### Steps to Reproduce

1. Open a document
2. Select some text
3. Use right click to for example to copy the text

**Expected behavior:** Selections remain intact

**Actual behavior:** Everything is deselected and cursor is created.

**Reproduces how often:** Always

### Versions

Reproducible using the latest build 4f73e81080017303a66dcb020c8b451e0c4ca4dd

### Additional Information

Tried only on Windows 10.

Seems to be broken by #16192 

cc @50Wliu

**Comment by petergood** [comment]
I cannot confirm the issue - the text remains selected after right clicking on MacOS.
