### ISSUE TITLE
Blank Screen First Start

### ISSUE THREAD

**Issue by tribeldragon** [atom/atom#16325]
Installed Ubuntu today on my laptop and installed atom after that. Get a blank screen when launching with an element inspect window , nothing else. (See screenshot)
![screenshot from 2017-12-05 18-32-19](https://user-images.githubusercontent.com/5493312/33621330-a682fe02-d9ea-11e7-9862-875fda52d232.png)

**Comment by tribeldragon** [comment]
when running through the terminal
![screenshot from 2017-12-05 18-35-46](https://user-images.githubusercontent.com/5493312/33621470-20db08ac-d9eb-11e7-99dd-97070f69d559.png)

**Comment by 50Wliu** [comment]
It looks like you may have unintentionally started Atom using `sudo` at one point because your `.atom` folder has the incorrect permissions.  Delete `~/.atom` and try again.
