### ISSUE TITLE
atom cli does not handle arguments properly in fish shell on macOS

### ISSUE THREAD

**Issue by bennypowers** [atom/atom#16367]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The `atom` command does not work as expected in fish shell. specifically, it ignores the first argument.

### Steps to Reproduce

```
~ > atom .         // opens an empty new editor window
~ > atom -- .      // opens cwd as project dir 
~ > atom foo .     // opens cwd as project dir
~ > bash      
bash-3.2$ atom .      // opens cwd as project dir
bash-3.2$ atom -- .   // opens cwd as project dir
bash-3.2$ atom foo .  // opens a new file foo in cwd
```

**Expected behavior:** `atom .` should open the cwd. `atom foo .` should open foo in the cwd

**Actual behavior:** `atom .` opens an empty window

**Reproduces how often:** 100%

### Versions

```
~ > system_profiler SPSoftwareDataType
Software:

   System Software Overview:

     System Version: macOS 10.13.1 (17B1003)
     Kernel Version: Darwin 17.2.0
     Boot Volume: Macintosh HD
     Boot Mode: Normal
     Computer Name: Pro
     User Name: Benny Powers (bennyp)
     Secure Virtual Memory: Enabled
     System Integrity Protection: Enabled
     Time since boot: 1 day 19:21

~ > fish --version
fish, version 2.6.0
~ > atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by cleanenergyjoy** [comment]
(#16467)

13 gru 2017 09:27 "Benny Powers" <notifications@github.com> napisał(a):

**Comment by bennypowers** [comment]
Turns out I had aliased the command
