### ISSUE TITLE
Atom can open the same file twice in the same pane

### ISSUE THREAD

**Issue by rsese** [atom/atom#16364]
Repro steps from https://github.com/atom/atom/issues/16364#issuecomment-353061571

I noticed this bug also when following this routine:

1. `atom . filename`
2. close atom leaving the file tab open
3. `atom . samefilename`

Expected: should open same file
Actual: opens a new file

Reported in halp: support/052c0592d8b611e7852aa652e371c508

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom can open the same file twice in the same pane if you drag a file that's already opened in a project to an empty Atom window (and that project isn't already opened).

### Steps to Reproduce

1. `atom --safe`
2. Set `Restore Previous Windows on Start` set to `no` in `Settings > Core`.
3. Open some project and then open some file.
4. Quit Atom.
5. Start Atom.
6. Drag the same file you had open in step 3 from Finder or Windows Explorer to the Atom window.

**Expected behavior:** [What you expect to happen]

The project opened in step 3 opens and the file dragged is open in 1 tab. 

This would seem to match other behavior where if you have a file open, dragging the file from Finder to the same window just focuses the already open file?

**Actual behavior:** [What actually happens]

The project opened in step 3 opens and the file dragged is open in 2 tabs in the same pane.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

```
atom -v
Atom    : 1.24.0-dev-4f73e8108
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
apm -v
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.24.0-dev-4f73e8108
python 2.7.10
git 2.13.6
```

macOS 10.12.6

### Additional Information

Step 2 isn't necessary, you just need to make sure the project opened in step 3 isn't open in some window before step 6.

**Comment by ormung** [comment]
I noticed this bug also when following this routine:

1. `atom . filename`
2. close atom leaving the file tab open
3. `atom . samefilename`
