### ISSUE TITLE
Atom SASS/SCSS autocomplete doesn't work

### ISSUE THREAD

**Issue by AmirFawzy** [atom/atom#16366]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

**first of all this problem happening since i updated to atom v1.22.1 and i wait for releasing atom v1.23.0 thinking this problem solved in new version v1.23.0 but NO it's the same problem still happening again**
#16158 

when i working on sass/scss files and use mixin, custom function or variables atom doesn't detecting those mixin, variables...etc
for example: when i use a variable when i write "`$`" which is declaration with first letter of the variable name atom doesn't show autocomplete  list for all variables that start with that first letter i written it like autocomplete the variable ... and instead of that it show just suggestions for the most use words in project.

### Steps to Reproduce

1. open new SCSS file and import the _variables.scss and _mixins.scss
2. write the selector open brackets write the css property then colon .
3. write `$` and the first three letters of variable i need to use.
4. autocomplete list not work properly. 

**Expected behavior:** when i start type value in sass/scss starting with "`$`" and first, two or three  letter atom show autocomplete list of all variables which start with that letter ... when i write "`@include`" and first, two or three letter of mixin name it should show autocomplete list with all mixins start or match that letter or word i written.

**Actual behavior:** when i write `$`, `@include` it show suggestions(autocomplete) with the most used words in project not with actual variables or mixin it doesn't auto detecting variables or mixins like it's not exist or imported with project.
look to image in reference issue that i mention it above.

**Reproduces how often:** 100% all the time

### Versions

OS windows 10 pro v.1709 x64
Atom : 1.23.0
Electron: 1.6.15
Node : 7.4.0
apm 1.18.11
npm 3.10.10
node 6.9.5 x64

### Additional Information

problem still excite even after i update to v1.23.0 i don't know what i should to do or what caused this problem if there's something causing it ... please solve this problem i can't use atom for now because this problem(using other competitor) it make my workflow too slow.

**Comment by rsese** [comment]
> first of all this problem happening since i updated to atom v1.22.1 and i wait for releasing atom v1.23.0 thinking this problem solved in new version v1.23.0 but NO it's the same problem still happening again

Thanks I'll go ahead and re-open https://github.com/atom/atom/issues/16158 for now since this is an auto-complete issue.

**Comment by rsese** [comment]
Ohhh I think maybe this is in 1.24 and not 1.23 @leroix?

**Comment by leroix** [comment]
@rsese not sure exactly what's going wrong here. I think this should have been fixed by https://github.com/atom/autocomplete-plus/pull/930 which was included in 1.23.

**Comment by rsese** [comment]
Hmmm, here's what I found in 1.23.1 and 1.24.0-beta0 - here's 1.23.1:

![auto-complete-1 23 1](https://user-images.githubusercontent.com/734194/33967623-db8986d0-e029-11e7-8658-3c36f4ff2db7.gif)

And 1.24.0-beta0:

![auto-complete-1 24 0-beta0](https://user-images.githubusercontent.com/734194/33967635-e1b43000-e029-11e7-9c5b-52aa7a163c36.gif)

@AmirFawzy can you try the 1.24 beta and let us know if things work ok for you there?

**Comment by leroix** [comment]
@rsese It looks like I accidentally included `$` in nonWordCharacters for Sass. https://github.com/atom/language-sass/commit/bbb8247223b3ea388b2cbf8eb14bf946e609f856

I think I'll need to update the language-sass package to remove it.

**Comment by AmirFawzy** [comment]
@rsese i tried 1.24 beta and it's working pretty good with me for SCSS variables thanks for helping.

but when i use `@include` it not working very correctly actually autocomplete list it showing good but it not give first priority to project mixins but it give it to project variables... i mean the first 3 or 5...etc items in the autocomplete list it's variables not mixin and the correct is the opposite the first items it's mixin because i used `@include` ... isn't right? and sometimes mixins show in the list and other-times no.
i  don't know if that even a bug but i found the behavior weird a little bit with mixin `@include`

**Comment by leroix** [comment]
@AmirFawzy yea, I think I need to remove `@` from the nonWordCharacters list as well.

**Comment by rsese** [comment]
Thanks for trying things out @AmirFawzy and thanks for the 👓 @leroix :v:

Do you want me to open a separate issue in https://github.com/atom/language-sass (or https://github.com/atom/autocomplete-plus/?) to track this @leroix?

**Comment by leroix** [comment]
@rsese nope, that's ok. I'll make a note for myself.

**Comment by leroix** [comment]
should be fixed by https://github.com/atom/atom/commit/9519d0ff37fef7a63e030244234a08c31fe728ed

**Comment by RAFA3L** [comment]
Hello, is there a way to update language-sass to 0.61.4 without waiting for the Atom update?

**Comment by AmirFawzy** [comment]
@RAFA3L i hope so cuz it looks we will wait too long until atom v1.24
#16481
