### ISSUE TITLE
Collapsing comments collapses code too

### ISSUE THREAD

**Issue by aryzing** [atom/atom#16368]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Folding a comment adjacent to code will fold the comment and the code

### Steps to Reproduce

1. Write a block of code with a comment above
This piece of code will do (javascript)
```js
// comment line 1
// comment line 2
if (cond1) { 
  then1() 
} else if (cond2) {
  then2()
} else {
  then3()
}
```

2. Click the fold arrow
Next to the line `// comment line 1` there will be a fold arrow in the editor. Click it

**Expected behavior:**
I expected two behaviors: 
* That there would be two fold arrows, one for the comment, and one for the `if`
* Folding the comment would only fold the comment and not the `if`

**Actual behavior:**
* There is no fold arrow next to the starting `if`
* Folding the comment folds up to and including the `if (cond1) {` line, but not the `then1()` statement:

```js

// comment line 1 [...]
  then1() 
} else if (cond2) {
  then2()
} else {
  then3()
}
```

Also, folding the `else if` produces

```js
// comment line 1
// comment line 2
if (cond1) { 
  then1() 
} else if (cond2) { [...]
  then3()
}
```
which is clearly misleading.

**Reproduces how often:** 100%

### Versions
```
Atom    : 1.23.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by rsese** [comment]
Thanks for the report!  I'm unable to reproduce with macOS 10.12.6 and Atom 1.23.1:

![fold](https://user-images.githubusercontent.com/734194/33962013-b63f1c3c-e015-11e7-9789-4c40b73e9ae2.gif)

So when I fold at line 1, the `if` isn't folded and the GIF shows a fold arrow next the `if` as well.   I  tried in the 1.24.0 beta and couldn't reproduce there either.  What operating system are you on?

**Comment by aryzing** [comment]
My bad -- its TypeScript messing around with the IDE. I thought it would be disabled when running in safe mode, but apparently not.
