### ISSUE TITLE
Atom with no internet

### ISSUE THREAD

**Issue by iCrazyBlaze** [atom/atom#16373]
For some reason, Atom refuses to load without internet connectivity on Windows 10. Once I connehcted to the internet, it went back to normal. This issue really needs to be fixed - a text editor should NEVER require internet to work.

**Comment by ungb** [comment]
Hey @iCrazyBlaze,

I just tried atom on windows 10 without internet and didn't see any issues.  Can you provide more info on what's going on?  Is atom blank or do you see an error or it crashes?

It could be a community package is causing the issue.  If you open powershell/cmd and run `apm list` can you provide the list of community packages you have installed?

Also would be good to know what version of atom you're running.  you can find this by running `atom --version`

**Comment by iCrazyBlaze** [comment]
I suppose it's just me, so it shouldn't matter too much. I can always use
Atom with internet access, and there are other editors I can use without.
I'm running the latest version of Atom as of writing. Sorry that I don't
have enough time to replicate the issue.

**Comment by lee-dohm** [comment]
The only other [report of this with any details](https://discuss.atom.io/t/atom-is-not-starting-without-internet/53823/4?u=leedohm) was someone running Atom on a machine with no network connectivity at all: no network hardware, no network driver, nothing.

**Comment by Umidrifkatov** [comment]
Have the same problem, Windows 10 pro can't use without internet

**Comment by lee-dohm** [comment]
@Umidrifkatov please open a new issue and fill in the template so that we can be sure we have all the necessary information to investigate.

**Comment by cgbolesajr** [comment]
i just updated to windows 10 rs5, then atom doesn't work anymore without internet.

**Comment by willwartz** [comment]
Same case here. Atom wont run without internet on Windows 1809

**Comment by willwartz** [comment]
enabling the loopback adapter solves this issue

**Comment by Dayo-Odesola** [comment]
how to i enable loopback adapter

**Comment by willwartz** [comment]
> how to i enable loopback adapter

1. Just access your device manager, 
2. Click on any category e.g. "Network Adapter" 
3. then click on "action" at the top of the window
4. and select "Add legacy hardware" 
5. Click "next" on the window that pops up
6. Select the 2nd option on the next screen "install manually" 
7. Then select "Network adapter" and click next. Wait for next window to load
8. Choose manufacturer as "Microsoft" 
9. Find the "loopback" adapter and click next and next again. 
Done

**Comment by ishraaq21** [comment]
> enabling the loopback adapter solves this issue

Thanks, it does the job (Win 10 Enterprise LTSC Edition).

**Comment by willwartz** [comment]
I'm glad it did. You're welcome.


On 25 Jan 2019 at 06:16, <Ishraaq <notifications@github.com>> wrote:

enabling the loopback adapter solves this issue

Thanks, it does the job (Win 10 Enterprise LTSC Edition).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/atom/atom/issues/16373#issuecomment-457441115>, or mute
the thread
