### ISSUE TITLE
Crash when trying to open a git repository folder under an other folder with the same name

### ISSUE THREAD

**Issue by angelitodeb** [atom/atom#16383]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

"Open Folder..." not working when oppening git repository folder under an other folder with the same name.

Example:

/oneapp/oneapp

The second "oneapp" folder is a git repository, if you try to open it from Atom "File -> Open Folder..." it fails and the new Atom window is somehow crashed (no tab opens on it). If you change the second folder name then it works.

### Steps to Reproduce

1. Create a folder with any name
2. Create an other folder into the first one with the same name
3. Create a git repository into the second one folder
4. Open Atom and try to open the second folder using "File -> Open Folder..."

**Expected behavior:** Folder opens

**Actual behavior:** Folder isn't opening and Atom crash.

**Reproduces how often:** 100%

### Versions

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Debian 8.5 x64
Kernel: 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

**Comment by rsese** [comment]
Thanks for the report!  I'm unable to reproduce with Atom 1.23.1 on Ubuntu 16.04.  I see the perquisites section of the issue template isn't checked, can you confirm if you can reproduce in safe mode (`atom --safe`)?

And can you confirm if you installed Atom with the .deb file from https://atom.io?

Lastly, just confirm this step:

> Create a git repository into the second one folder

When I tried to reproduce I just ran `git init`, is that what you did as well?

**Comment by angelitodeb** [comment]
Hi,

It fails in safe mode too, I was testing the issue using other repos but I can't reproduce it, so it reproduce 100% with one git repository I has since time ago but I cannot deduce all the circunstances of the crash.

I'm using Atom from atom.io, upgraded original Debian package from the .deb file on Atom site.

When I open the console after triying to open the folder I get this errors:

```
Uncaught (in promise) TypeError: Cannot read property 'catch' of undefined
    at handleBufferState (/usr/share/atom/resources/app/src/project.js:96:55)
    at Project.deserialize (/usr/share/atom/resources/app/src/project.js:105:33)
    at AtomEnvironment.module.exports.AtomEnvironment.deserialize (/usr/share/atom/resources/app/src/atom-environment.js:1273:45)
    at /usr/share/atom/resources/app/src/atom-environment.js:834:32
```

And in safe mode I get this:

```
Uncaught (in promise) TypeError: Cannot read property 'catch' of undefined
    at handleBufferState (/usr/share/atom/resources/app/src/project.js:96:55)
    at Project.deserialize (/usr/share/atom/resources/app/src/project.js:105:33)
    at AtomEnvironment.module.exports.AtomEnvironment.deserialize (/usr/share/atom/resources/app/src/atom-environment.js:1273:45)
    at AtomEnvironment.module.exports.AtomEnvironment.restoreStateIntoThisEnvironment (/usr/share/atom/resources/app/src/atom-environment.js:1211:25)
    at AtomEnvironment.module.exports.AtomEnvironment.attemptRestoreProjectStateForPaths (/usr/share/atom/resources/app/src/atom-environment.js:1160:20)
    at /usr/share/atom/resources/app/src/atom-environment.js:1458:34
```

I can test all the things you need.

**Comment by rsese** [comment]
Thanks for sharing the console errors - can you confirm if clearing saved state helps (note the warning in the documentation, please save any unsaved work first)?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by angelitodeb** [comment]
You are correct, clearing saved state has solve the problem.

Sorry for the inconvenience, I think this issue can be closed then

**Comment by rsese** [comment]
No problem, I'm glad that worked for you :+1:
