### ISSUE TITLE
Atom is ignoring my .env files in laravel projects

### ISSUE THREAD

**Issue by AnthonyMichaelc** [atom/atom#16393]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Only seeing this in **Laravel** projects. Currently, the laravel .env file does not show in the project tree, however if I try to create a new .env file thinking it get deleted, it tells me that it already exist. I opened this same project in **sublime**, **vscode**, **brackets**, and **vim** and they all see the file.

Thinking it may be an update issue I updated to the current 1.23.1 x64 on OSX High Sierra. 

Now what is odd is I created an **AdonisJS** Application which is basically the node version of laravel and has a .env file in the project, the .env file shows and is accessible on the adonis project but not the laravel one.

It would be nice to not have to use more than one editor when I want to make changes to my .env file.]

### Steps to Reproduce

1. [Create/Open Laravel project]
2. [Open Project Panel]

**Expected behavior:** [Expect my .env file to be in the list and accessible, as well as searchable in the top panel when I click cmd+p]

**Actual behavior:** [Acts as if the file does not exist but tells me it exist when I try to save a new file named .env. Also does not show the file in the file search, Almost as if it set to ignore .env extensions (which my personal settings are not)]

**Reproduces how often:** [Recently, 100% of the time I open Atom]

### Versions

Atom : 1.23.1
Electron: 1.6.15
OSX: 10.13.1

### Additional Information
I am attaching screenshots:
### Laravel
<img width="119" alt="screen shot 2017-12-15 at 5 03 41 pm" src="https://user-images.githubusercontent.com/13970615/34062662-ccdc0c46-e1bb-11e7-9340-871c3714b33c.png">

### AdonisJS
<img width="172" alt="screen shot 2017-12-15 at 5 04 07 pm" src="https://user-images.githubusercontent.com/13970615/34062667-d4b225b8-e1bb-11e7-99c2-384d158ad19c.png">

### Searching for the .env file shows nothing but the example one 
<img width="842" alt="screen shot 2017-12-16 at 12 14 40 pm" src="https://user-images.githubusercontent.com/13970615/34072733-c313d2e4-e25a-11e7-8799-d509baaba9df.png">

**Comment by AnthonyMichaelc** [comment]
In Laravel and Adonis they include the .env.example for reference and for deploying since it is empty  when you commit it so people don't have your logins and all, but there should be both a .env and .env.example showing

**Comment by 50Wliu** [comment]
Is your `.gitignore` configured to ignore the `.env` file?

**Comment by AnthonyMichaelc** [comment]
@50Wliu Yes it actually is. Was there a change in Atom that hides files in the gitignore in the project panel? Cause it was always in the gitignore and never hid the env file. It used to jsut gray out the files/folders that were in the gitignore file.

**Comment by 50Wliu** [comment]
Atom has always hid gitignored files by default.  You must have accidentally hit `i` while the Tree View was focused - just focus it again, press `i`, and your gitignored files should appear grayed-out again :).
