### ISSUE TITLE
Update leaves behind old versions taking up unnecessary space

### ISSUE THREAD

**Issue by sheddup** [atom/atom#16396]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Update leaves behind old versions taking up unnecessary space, screenshot of C:\Users\username\AppData\Local\atom 
![aaaaaaaa](https://user-images.githubusercontent.com/5480335/34072184-d307776e-e269-11e7-8324-e3f5a2d322f6.png)

### Steps to Reproduce

1. Update

**Expected behavior:** [Cleanup old version/files]

**Actual behavior:** [No cleanup is done]

**Reproduces how often:** [100%]

### Versions
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
 / Windows 8.1 x64

**Comment by rsese** [comment]
Thanks for the report!  This was discussed in https://github.com/atom/atom/issues/15320 and https://github.com/atom/atom/issues/15320 - go ahead and manually remove the old version and I think the old versions should be cleared going forward (though one previous version is kept on purpose).
