### ISSUE TITLE
Duplicate mirror code 

### ISSUE THREAD

**Issue by Antonyselt** [atom/atom#16402]
### Description

I have some code appearing in the editor that doesn't exists

### Steps to Reproduce

This happend to me when I paste to much lines of code I don't know

**Expected behavior:** [What you expect to happen]
The code shouldn't repeat

**Actual behavior:** [What actually happens]
![captura de pantalla 15](https://user-images.githubusercontent.com/13181287/34135912-625b4bd4-e431-11e7-9135-b29caa2d4b33.png)

### Versions

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python
git 2.15.0.windows.1
visual studio

**Comment by rsese** [comment]
Thanks for the report!  Just to clarify, you only saw this issue once but can't reproduce?  About the code you pasted, was this copied/cut from Atom or some other application?

**Comment by Antonyselt** [comment]
I really don't know how you can be able to reproduce the bug.

It happend to me when I paste many lines of code

For example, I copied 10 lines of code and pasted in diferents sections of my code several times

My guess is that action triggered the bug

**Comment by rsese** [comment]
Thanks for the extra details - since we don't have more specific steps to reproduce we'll go ahead and close for now but if you run into this again and find a way to reproduce we can always reopen.
