### ISSUE TITLE
Atom is missing a very basic "text editor" feature

### ISSUE THREAD

**Issue by dacbarbos** [atom/atom#16400]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Missing **Print** feature.

### Steps to Reproduce

1. Atom Menu -> File -> Print

**Expected behavior:** Print current file(s)

**Actual behavior:** Missing feature

**Reproduces how often:** 100%

### Versions

All.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by chrisjpatty** [comment]
There's actually a popular package for this very purpose. Haven't ever needed to use it personally, but there's also some alternatives available to be installed. https://atom.io/packages/print-atom

**Comment by 50Wliu** [comment]
@dacbarbos The Atom team has decided that we are not going to add a printing feature to Atom core.  As @chrisjpatty noted, there are already community packages that add printing, should you need to print something.  See also https://atom.io/packages/print-code and https://github.com/atom/atom/issues/3525#issuecomment-324688942

**Comment by dacbarbos** [comment]
I'm using Atom for almost two years now and I also never had a need for printing, until today! I'm sure there are workarounds out there but still, it's a very basic feature one would expect to have in any text editor. Don't you agree? Btw, before submitting this "issue" I've made a quick search for "print" keyword in Pref->Settings->Packages. No relevant package was found. Thanks for your suggestion but according to https://github.com/luke-john/print-atom/issues/1 is a NO-GO.

**Comment by dacbarbos** [comment]
@50Wliu print-code satisfies my immediate need. However, rejecting or ignoring a core feature like this challenge me to look for alternatives 😞   Dupe of #3525

**Comment by jagooch** [comment]
same here, if Atom is going to be my go-to text editor, then it need to have the feature that are expected in any text/documentation application. 

"Hey, I got a meeting in 1 minute, can you print that bug list out so  I bring it up during the meeting? My computer is being rebuilt by local IT so I cannot access email" 
"Sure. I'll just file-print and ...oh wait. Sorry.  I guess we cannot get them the necessary attention to get them moved up the priority list."
