### ISSUE TITLE
New File Shortcode no longer switches tab when opened

### ISSUE THREAD

**Issue by raptor235** [atom/atom#16401]
Version 1.23.1

Just updated today and seems that when opening a new file in the current project Atom no longer switches the active tab to the new file... is this by intention?

**Comment by rsese** [comment]
Thanks for the report - this doesn't sound like an intentional change or any change that I remember seeing.  The issue template information would be super helpful here e.g.:

* Can you share exact steps to reproduce?  
* What operating system are you running?
* Have you tried running in safe mode?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16401#issuecomment-352879047. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
