### ISSUE TITLE
Package removed after failed update

### ISSUE THREAD

**Issue by black-snow** [atom/atom#16417]
### Prerequisites

* [-] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I updated the Hydrogen plugin to the latest version and after atom restart it was gone.

### Steps to Reproduce

I fear that it might not be so easy to reproduce. Wanted to report it anyway.
I clicked update all and Hydrogen 2.2.0 failed. After a restart Hydrogen was completely gone.

**Expected behavior:** [What you expect to happen]

I would've expected that the old version is still there.

**Actual behavior:**
The package was actually gone.

**Reproduces how often:** [What percentage of the time does it reproduce?]
0

### Versions

1.23.1

If it's atom's default behaviour to remove a package if the update fails to install I'm sorry. Still weird, though.

**Comment by 50Wliu** [comment]
There was a bug causing updating packages with uppercase letters (like `Hydrogen`) to fail.  We have already fixed it and it should be available in the next hotfix.
