### ISSUE TITLE
File.onDidRename throws error instead of calling callback function 

### ISSUE THREAD

**Issue by mkungla** [atom/atom#16413]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

File.onDidRename throws error instead of calling callback function

```
The handle(4) returned by watching <file-path> is the same with an already watched path(<file-oldPath>)
```

### Steps to Reproduce

1. consider following
```js
const file = new File(atom.project.resolvePath('./some-file'))
file.onDidRename(() => {
    // do something onDidRename
})
file.onDidDelete(() => {
   // do something onDidDelete
})
```
2. rename file in Atom and error mentioned above is thrown and callback is never called

3. rename file in file system `mv ./some-file ./_some-file` and `onDidDelete` is called instead `onDidRename`

4. using atom.project.onDidChangeFiles has correctly `ev.action = renamed`
```js
atom.project.onDidChangeFiles(ev => {
  for (const e of ev) {
    if (e.path === file || e.oldPath === file) {
      // e.action = 'renamed'
      break
    }
  }
})
```
**Expected behavior:** that `onDidRename` callback is called

**Actual behavior:** throws error mentioned above

**Reproduces how often:** 100%

### Versions

```
atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.14
git 2.14.3
```

`4.14.5-300.fc27.x86_64`

**Comment by lee-dohm** [comment]
We're working on improving our file-system watching and notification systems. You can track progress in https://github.com/atom/atom/pull/16124.

**Comment by mkungla** [comment]
@lee-dohm thanks will take a look
