### ISSUE TITLE
Cannot manage/update packages, cannot update Atom core

### ISSUE THREAD

**Issue by botondcs** [atom/atom#16418]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Cannot update packages in GUI.
GUI output on update tab:
`Fetching [...] packages failed. /snap/atom/109/usr/share/atom/resources/app/apm/bin/apm: line 63:  8163 Segmentation fault      (core dumped) "$binDir/$nodeBin" "$cliPath" "$@"`

Cannot enable or disable packages in GUI.
GUI output on package tab same as above.

Cannot use package manager in terminal.
Same output as above.

### Steps to Reproduce

1. Launch Atom
2. Go to settings
3. In settings, go to updates

OR in terminal

1. $ apm

**Expected behavior:** To show me all packages and available updates.

**Actual behavior:** Shows no packages, gives error message.

**Reproduces how often:** Everytime.

### Versions

Ubuntu 17.10

$ atom --version
$ Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Packages seem to work just fine. Only affects managing and updating packages.

I tried the following without any change in behavior:
Launched Atom in safe mode
Disabled packages in config.cson
Removed ~/.atom altogether

**Comment by lee-dohm** [comment]
Thanks for the bug report.

It appears that you installed Atom from a Snap? This isn't an official distribution of Atom. If you can reproduce this problem when installing Atom from one of the official distributions obtained from https://atom.io, please let us know and we'll investigate further.

Thanks again.
