### ISSUE TITLE
[bug] Can no longer highlight and right click selection in latest beta release..

### ISSUE THREAD

**Issue by JourneyOver** [atom/atom#16422]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Dunno exactly when this happened but it must of been at some point in the past 24 hours.. but the issue I am facing is this:

Whenever I highlight a section (several lines) or even just 1 line or word if I right click in the editor window to bring up the context menu it unhighlights everything that I had highlighted not allowing me to copy multiple lines or anything else that I can do in the context menu..

### Steps to Reproduce

1. make a few lines
2. highlight all lines
3. right click
4. it unhighlights everything

**Expected behavior:** [What you expect to happen]
for everything that I highlighted to stay highlighted when right clicking in the editor window to open the context menu..

**Actual behavior:** [What actually happens]
unhighlights everything I had highlighted when I right click in the editor window
 
**Reproduces how often:** 100%

### Versions

happens in version 1.24.0-beta1
doesn't happen in version 1.23.1

### Additional Information

This happens on both a clean install, in --safe mode, uninstalling and then reinstalling, with and without extensions.

**Comment by rsese** [comment]
Thanks for the report! 

> happens in version 1.24.0-beta1
> doesn't happen in version 1.23.1

 I can reproduce this in 1.24.0-beta1 on macOS 10.12.6 though I also saw it in 1.24.0-beta0 before i updated.  Also confirmed not an issue in 1.23.1.

@nathansobo @as-cii?

**Comment by 50Wliu** [comment]
I merged the fix for this a few hours ago and was just about to put it on the release branches.

**Comment by rsese** [comment]
ahhh sorry totally missed https://github.com/atom/atom/issues/16324.
