### ISSUE TITLE
Unknown Problem with installing atom

### ISSUE THREAD

**Issue by unitrixx** [atom/atom#16423]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
1. Tried to install Atom via the atomsetup-x64.exe
2. Error: Installation has failed
3. Tried the same with Administrator with the same result
[SquirrelSetup.log](https://github.com/atom/atom/files/1580469/SquirrelSetup.log)

**Comment by unitrixx** [comment]
solved by using the .zip file instead of the Setup.exe

**Comment by rsese** [comment]
I noticed this in your log:

> 2017-12-21 21:14:02> IEnableLogger: Failed to copy Update.exe to C:\Users\Leon\AppData\Local\atom\Update.exe: System.UnauthorizedAccessException: Der Zugriff auf den Pfad "C:\Users\Leon\AppData\Local\atom\Update.exe" wurde verweigert.

Seems to translate to a permission denied error?  We often see that error because of anti-virus programs - if you're running anti-virus and want to try using the installer again, go ahead and temporarily disable your anti-virus and try installing again.

**Comment by unitrixx** [comment]
Thanks for your help. Your suggestion worked. Sorry for this unnecessary issue

**Comment by rsese** [comment]
No problem, glad that helped!
