### ISSUE TITLE
watchPath don't show event "deleted"

### ISSUE THREAD

**Issue by alexeyvax** [atom/atom#16433]
When I deleted file or directory I didn't see any messages about it,
but when I did another actions such as create, modify or rename I saw "created", "modified" and "renamed" messages.
I used code from example page https://atom.io/docs/api/v1.23.1/PathWatcher
My OS is linux.

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/node-pathwatcher if there's no existing issue already so we have it in the right place?
