### ISSUE TITLE
watchPath send wrong data when I move file by drag and drop

### ISSUE THREAD

**Issue by alexeyvax** [atom/atom#16438]
When I rename file, watchPath work excellent, but when I move file by drag and drop, watchPath send me wrong data.
It send me similar paths from fields: "oldPath" and "path" when I expect different paths
![selection_007](https://user-images.githubusercontent.com/22244018/34327316-2997c052-e8d2-11e7-82a8-014526873876.png)

**Comment by rsese** [comment]
Thanks again @alexeyvax - like with https://github.com/atom/atom/issues/16433, can you re-open this in https://github.com/atom/node-pathwatcher?
