### ISSUE TITLE
delete require.cache['somekey'] does not affect customRequire.cache

### ISSUE THREAD

**Issue by wiggisser** [atom/atom#16435]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When a module is loaded via `require('/path/to/module')`, it is also placed in the `snapshotResult.customRequire.cache`. When reloading the module from disk, even after `delete require.cache['/path/to/module']`, the module is returned as it was initially read, because it's still contained in the `customRequire.cache`, but it's not part of the `require.cache` anymore (and doesn't get added in any of the subsequent require calls)

### Steps to Reproduce

1. open the Developer Tools console
2. load a module via `require('/path/to/module')`
3. delete it via `delete require.cache['/path/to/module']`
4. change something in the module file
5. load it again via `require('/path/to/module')`

**Expected behavior:** 
Should return the new changed module definition (or at least there should be an easy way to remove the module from the `customRequire.cache`)

**Actual behavior:** 
Returns the initial module definition, as it was when it was read from disk the first time.

**Reproduces how often:** 
100%. 

### Versions
Noticed this the first time, when I started to use the atom-build (https://github.com/noseglid/atom-build/) package in July 2017 with JSON configurations. Can be seen in all versions of Atom since (Linux and Windows, did not check on Mac)

### Additional Information

Does not occur in `--dev` mode, but does occur in `--safe` mode

**Comment by lee-dohm** [comment]
Thanks for reaching out :+1:

Yes, you're correct that this is the current semantics of the module caches in Atom. For a long time we had mechanisms in place to attempt to properly bust the module caches when things were updated. Over time, it proved to be problematic to do this properly in all cases and we decided to abandon the feature as requiring too much ongoing maintenance and having too many squirrely edge-cases.This is why Atom now recommends people restart the application when packages are updated.

Given the above, we don't have any plans to change this behavior of the module cache.

**Comment by UziTech** [comment]
for anyone else looking for a solution to this issue I have been using the following code:

```javascript
const path = require('path');

function removeCache(filePath) {
  delete require.cache[filePath];

  try {
    let relativeFilePath = path.relative(path.join(process.cwd(), 'resources', 'app', 'static'), filePath);
    if (process.platform === 'win32') {
      relativeFilePath = relativeFilePath.replace(/\\/g, '/');
    }
    delete snapshotResult.customRequire.cache[relativeFilePath];
  } catch (err) {
    // most likely snapshotResult is not defined
    // not sure why that happens but apparently it does
  }
}
```

**Comment by jedwards1211** [comment]
@lee-dohm why is monkeypatching `require` even necessary?  This just causes headaches for everyone

**Comment by jedwards1211** [comment]
@UziTech unfortunately the relative file path is not the same on my computer.

There's a reason that node's `require.cache` caches by absolute path instead of relative path.  I'm kind of shocked at the poor decisions going on here in atom core.

**Comment by jedwards1211** [comment]
I guess I shouldn't be so judgmental, surely you guys wouldn't have done this if some awkward situation you had to work around didn't compel you to do this...

**Comment by jedwards1211** [comment]
Here is how I worked around this:
```js
"use babel";
import path from "path";
import Module from "module";
import { transformsPath } from "./scaffold";

module.exports = function loadTransforms() {
  const transformsFilePath = transformsPath();
  return new Promise((resolve, reject) => {
    let transforms = [];
    try {
      delete Module._cache[require.resolve(transformsFilePath)];
      const factory = Module._load(transformsFilePath, module, false);
      resolve(factory());
    } catch (error) {
      reject(error);
    }
  });
};
```

**Comment by suchipi** [comment]
@jedwards1211 could you submit a PR to morpher with that change?

**Comment by UziTech** [comment]
@jedwards1211 I updated the removeCache function see if this works

```js
const path = require('path');

function removeCache(filePath) {
  delete require.cache[filePath];

  try {
    let relativeFilePath = path.relative(path.join(path.dirname(process.execPath), 'resources', 'app', 'static'), filePath);
    if (process.platform === 'win32') {
      relativeFilePath = relativeFilePath.replace(/\\/g, '/');
    }
    delete snapshotResult.customRequire.cache[relativeFilePath];
  } catch (err) {
    // most likely snapshotResult is not defined
    // not sure why that happens but apparently it does
  }
}
```

it should be relative to Atom's `static/` directory

https://github.com/atom/atom/blob/399ab9d5776e3302023ebe6961d06e25f4512d8c/static/index.js#L39-L52
