### ISSUE TITLE
Black menu bar 

### ISSUE THREAD

**Issue by jimovi24** [atom/atom#16432]
### Description

In my Windows 10 my menu bar have the black menu bar with black font, but the menu is functional

![image](https://user-images.githubusercontent.com/11744391/34307786-e7f2390e-e717-11e7-9371-0a43f4e234ac.png)

**Comment by rsese** [comment]
Thanks for reaching out!  Can you share the rest of the information from the issue template?  The details can be helpful when investigating issues - for example, what version of Atom are you running (`atom -v`)?  Can you reproduce in safe mode (`atom --safe`)?

Also, did this suddenly happen or have you had the black menu bar for a while?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16432#issuecomment-353691709. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
