### ISSUE TITLE
Give atom-panes unique identifier attributes which are the same as the TextEditor object ID

### ISSUE THREAD

**Issue by audunolsen** [atom/atom#16434]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm currently writing a package where I modify the DOM-elements within every atom-pane element through JS, but a problem arises because new unsaved files have no unique identifier. Other files have a name or path attribute which also exist on the TextEditor object, but the new unsaved file panes and the TextEditor object have no common data. I think it would be ideal for every atom-pane to have an ID attribute derived from the TextEditor object.

**Comment by lee-dohm** [comment]
Thanks for the suggestion :+1:

There are a few issues with this:

1. Panes can have multiple items within them, so there are potentially multiple `TextEditor` objects in each `Pane`
1. Panes can have items in them that aren't `TextEditors`, for example markdown previews or image views
1. If you want to associate panes to their items, you can walk the DOM to find what items a pane has in it or there is also the [`Pane.getItems()`](https://atom.io/docs/api/latest/Pane#instance-getItems) or `[Pane.itemForURI`](https://atom.io/docs/api/latestPane#instance-itemForURI) functions

Given the above, I don't see how your proposal would work. If you can flesh out your proposal with some use cases and example code that shows how it would all fit together, we can take another look.

Thanks again!

**Comment by audunolsen** [comment]
Thank you for the response!

I see, I thought one pane represented one `TextEditor` instance because my workflow when developing the package included switching between two panes each with only one `TextEditor`—this would have been more apparent had I not disabled tabs in the UI 😅.

However, my problem just got more complex upon realizing this. The premise of my package is simple, toggle the visibility of the `.wrap-guide` if it exceeds `preferredLineLength` on save for minimal visual noise. 

Before, I was under the impression that `<atom-pane>` represented a single textEditor object, and because these had common data (`data-active-item-path` and `getPath`), I could walk down the DOM to find the appropriate `.wrap-guide`. Here is a code example:

```
filePath   = atom.workspace.getActivePaneItem().getPath()
wrapGuide  = document.querySelector "atom-pane[data-active-item-path=\"#{filePath}\"]
                                    .wrap-guide"
```
Now as I understand that I need to use `atom-text-editor` as my selector and not `atom-pane`, I see that `<atom-text-editor>` in the DOM and the TextEditor object has **zero** common data and thus my code falls completely flat.

My proposal—now that I have a proper grasp on this—is to add an ID attribute to `<atom-text-editor>` where the value of the ID attribute would be derived from the the ID on the appropriate `textEditor` object. This would allow for selectors in the script that can target nested DOM elements of the `<atom-text-editor>` represented by the TextEditor object you are currently handling in your script.

If you understand my issue and know an alternative way to handle it then please let me know.

**Comment by lee-dohm** [comment]
`atom.views.getView(atom.workspace.getActiveTextEditor())`

https://atom.io/docs/api/latest/ViewRegistry#instance-getView

**Comment by audunolsen** [comment]
Ah I see, my bad. Should have been more thorough when reading the documentation. Anyhow, thank you for your patience and understanding.

**Comment by lee-dohm** [comment]
You're most welcome. Apologies for the succinct message, I was being dragged off to dinner but wanted to get you the answer before they got the keyboard out of my hands :laughing:
