### ISSUE TITLE
Menu Show/Hide on Language Keyboard Shortcut (Alt+Shift)

### ISSUE THREAD

**Issue by metemaddar** [atom/atom#16443]
Menu Shows/Hides on common Keyboard Language input change shortcut (Alt+Shift).
**To test** just hit (Alt+Shift)
**OS:** Slackware with KDE Plusma 5
**Atom version:** 1.23.1

Thanks a lot

**Comment by cybernetlab** [comment]
+1 - I can't find way to change this setting. In my case Alt+Shift start work (as described by @metemaddar) when I install package that has item in main menu (PlatformIO for example). Without such packages all works fine.

**Comment by Petemir** [comment]
I'm having the same problem. Installed nuclide, among others, which adds an item to the menu. Now every time I press alt+shift the menu opens.

OS: Ubuntu 18.04
Atom version: 1.28.2

**Comment by unti1x** [comment]
In my case `Alt-Shift` triggers the menu items without an underscored character (i.e. `&`). Temporary solution (based of [this](https://discuss.atom.io/t/alt-key-menu-bar-interaction-overrides-shortuts/9192/7) post) is to add the following lines in `~/.atom/init.coffee`:

```coffee
atom.menu.template.forEach (t) ->
  if t.label.indexOf('&') == -1
    t.label = "&#{t.label}"

atom.menu.update()
```

This adds the ampersand in front of a menu item label. May possibly break something if two items with the same character appear.

**Comment by lkashef** [comment]
Thanks for contributing!

All new issues now require steps to reproduce (also called "repro steps") the problem or the behavior you wish to see in Atom. We do this so we can be certain that we are understanding what it is you're describing and don't prematurely close the issue or implement the wrong feature. If you need help writing detailed repro steps, please see the How Can I Contribute? section of the Atom CONTRTIBUTING guide.
