### ISSUE TITLE
"Open with" in Windows breaks after autoupdating Atom

### ISSUE THREAD

**Issue by DervishD** [atom/atom#16442]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Windows Explorer right-click integration breaks after auto-updating Atom

### Steps to Reproduce

1. Install Atom and make sure you activate `Settings->Core->Automatically Update`
2. Activate `Settings->System->Show in file context menus` and `Settings->System->Show in folder context menus`
3. Check that right-clicking a file or folder in Windows Explorer shows `Open with Atom` entry and that the entry shows Atom's icon.
4. Wait until Atom has updated at least once since it was first installed
5. Right click on a file or folder in Windows Explorer or the desktop

**Expected behavior:** An entry named `Open with Atom` shows in the right-click menu, showing the Atom's icon.

**Actual behavior:** An entry named `Open with Atom` shows, but it doesn't show the icon because it's pointing to an old/removed version, and not to the latest installed updated. Or worse, it points to a previous version which haven't been uninstalled after the auto update. More on this below.

**Reproduces how often:** In my case, 100%, every time Atom autoupdates.

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 3.6.0
git 2.11.0.windows.1
visual studio

Windows 10 Home x64 Version 10.0.16299 Build 16299

### Additional Information

The problem is that the registry keys like `HKEY_CLASSES_ROOT\Directory\shell\Atom\command` and the others needed to implement the right-click system integration for `Open with Atom` doesn't get updated after Atom is updated. For example, right now I have installed Atom version 1.23.1, but the registry keys were pointing to version 1.22.1. Scripts in `%LOCALAPPDATA%\atom\bin` aren't updated, either, they keep pointing to 1.22.1, not 1.23.1.

The registry keys can be fixed by launching Atom and disable and re-enable the checkboxes under `Settings->System`, but the scripts aren't.

Something if failing after an automatic update, and the things related to launching Atom doesn't get updated.

Feel free to ask me any additional information you may need, and thanks in advance!

**Comment by damieng** [comment]
If you launch Atom once using a normal icon after updating it should auto-correct right?

**Comment by DervishD** [comment]
I don't know, I don't remember having tried that! I'll try that solution next time I update Atom.

Thanks for the suggestion :)

**Comment by DervishD** [comment]
@damieng no, it doesn't auto-correct. I just updated to 1.23.3. The "Open with Atom" pointed to 1.23.1 (the previous version I had installed). I then launched Atom using the Start Menu icon, and in fact it launched version 1.23.3, correctly. But it didn't auto-correct the "Open with Atom" menu, which still points to version 1.23.1.

Anyway, I find this auto-correction the wrong solution (in fact it didn't even work for me). A better approach would be to point the "Open with Atom" menu to `%localappdata%\atom\atom.exe` instead to  `%localappdata%\atom\<VERSION>\atom.exe`. That way, this menu would always point to the latest version.

Of course, a MUCH better solution would be the installer to examine the corresponding setting and if "Open with Atom" is in effect, update the registry keys after a successful installation.

And again, thanks for your help :) If you need more information from me, just ask

**Comment by damieng** [comment]
There is indeed code that updates the registry to the right location after
an update;

https://github.com/atom/atom/blob/master/src/main-process/squirrel-update.coffee#L145

and

https://github.com/atom/atom/blob/master/src/main-process/win-shell.js#L45

1. Are you on a locked-down machine that might not allow reg.exe to be run?
2. Did you update using the built-in updater or did you separately download
the latest atom and run it manually?

**Comment by DervishD** [comment]
Since there's code that should do all that, then there's something wrong on my end, @damieng . I'm going to check the code you linked .

Nope, my machine is not locked-down, `reg.exe` can be run as an unprivileged user and it works (I just tested it) but maybe the permissions on the keys are wrong, I'll check them.

I used the built-in updater, as always, in fact Atom updates unattendedly on the machine.

Again, the problem may be in the permissions of the needed registry keys, but then, why are they updated if I start the latest Atom version installed and I deselect and re-select the related settings I mentioned in my original message? I mean, if the problem are the key permissions, they couldn't be updated by a running instance of Atom, either, but they are!

Thanks a lot for your help, @damieng

**Comment by damieng** [comment]
Hmm, yeah if toggling the option in the Settings > System view works then reg.exe must be working.

It would seem that somehow after downloading the auto-update it didn't relaunch the new Atom.exe with the `--squirrel-updated` flag.  Did it auto-relaunch Atom automatically after updating?

**Comment by DervishD** [comment]
No, it didn't relaunch itself automatically, in fact I noticed it updated because I launched Atom using he Start Menu icon and not the "Open with Atom" menu, and the `About` showed a different version number. As far as I know, it updated silently but I don't think it relaunched or I would have noticed, since launching Atom in my machine is painfully slow.

I'll observe carefully next update and for the time being I'll always use the Start Menu shortcut to launch Atom, just in case the problem lies in accidentally running an old version after the update for been using the "Open with Atom" menu.

Anyway, @damieng , any log I can check to see if the update happened correctly or if something failed?

Thanks again!!!

**Comment by damieng** [comment]
There is a SquirrelSetup.log file in appdata\local\atom but I don't think it includes logging about the restart - it definitely doesn't include logging about our --squirrel-update code path because at that point squirrel has handed control over to us.

There's definitely some sequence that seems to avoid the update process but pinning it down has been tricky.

**Comment by DervishD** [comment]
Don't worry, @damieng , I'll keep an eye on this and if I discover anything new I'll post it here. Meanwhile this is not that terrible, it only requires a tiny bit of manual interaction after every update.

Thanks for your help :)
