### ISSUE TITLE
Ability to disable grammar for particular file type(s)

### ISSUE THREAD

**Issue by isiahmeadows** [atom/atom#16459]
By any chance, is there an option to change the base whitelist for what extensions a grammar applies to? My issue is that I want to have JSX highlighting separate from JS highlighting (I don't like the way it highlights JS), but if I install `language-babel` or `language-javascript-jsx` (the two main grammars for JSX), they also apply a more specific scope to JS than `source.js` (`source.js.babel` and `source.js.jsx` respectively), which makes `customFileTypes` no longer a viable workaround. I'd like a way to just prevent them from applying to `.js` files over the core grammar.

**Comment by Ingramz** [comment]
If I understood you correctly, you want to use the `source.js` grammar for `js` files instead of the ones that come in community packages which override the extension. Anything you define in `customFileTypes` takes precedence over what grammars define:
```
customFileTypes:
  "source.js": [
    "js"
  ]
```

**Comment by isiahmeadows** [comment]
Yes, but when I tried that with `language-babel` enabled, it did nothing.

**Comment by isiahmeadows** [comment]
To clarify, I want `source.js` instead of `source.js.babel`, broadening the scope rather than narrowing it.

Note: in case this is actually an Atom bug that the scope isn't being broadened, I'm running 1.23.1 on macOS Sierra.

**Comment by Ingramz** [comment]
![select-grammar](https://user-images.githubusercontent.com/1017132/34421588-d995acc8-ec18-11e7-8423-299437cf2635.gif)

**Comment by isiahmeadows** [comment]
@Ingramz Not what I was getting. I did literally the same thing and it didn't work. Disabling the grammar and closing/opening the file worked, though.

**Comment by Ingramz** [comment]
@isiahmeadows try without other community packages, (only have `language-babel` and maybe `language-javascript-jsx` enabled). It might be easier for you to temporarily back up `~/.atom` directory and let atom re-create a pristine one, then install the two packages and try setting `customFileTypes` again.

**Comment by isiahmeadows** [comment]
Figured it out: my `customFileTypes` wasn't indented far enough (it wasn't immediately after `core:`, so it wasn't obvious).
