### ISSUE TITLE
Using shift + tab to undo tabs deletes all the selected lines and then ctrl+z does not undo the changes

### ISSUE THREAD

**Issue by festiveox** [atom/atom#16470]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using shift + tab to undo tabs deletes all the selected lines and then ctrl+z does not undo the changes.

### Steps to Reproduce

1. Highlight the code you want to undo tabs to
2. Hit shift + tab on your keyboard
3. The code will be deleted
4. Try to undo the changes with ctrl+z or on the edit drop down
5. Nothing happens

**Expected behavior:** for shift + tab to undo tabs up until the first column, and for ctrl+z to undo the changes.

**Actual behavior:** Code gets deleted and ctrl+z does not work.

**Reproduces how often:** Every time I try it.

### Versions

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.14
git 2.14.2.windows.1
visual studio

### Additional Information

Video, it does not show me clicking shift+tab but it was the thing that I did after highlighting the code:
https://www.dropbox.com/s/kdl9qk2rbjkqmq3/File%20Dec%2031%2C%207%2004%2009%20PM.mov?dl=0

**Comment by 50Wliu** [comment]
:wave: Thanks for creating an issue @festiveox.  I took a look at the video you provided but it doesn't look like you started Atom in safe mode.  Can you try again by launching Atom using `atom --safe` from the command line?

If it still reproduces in safe mode, can you open the Keybinding Resolver (`ctrl-.`) and show the output when you `shift-tab`?

Thanks!

**Comment by pukapukan** [comment]
Happens to me as well but only when atom-react plugin is enabled.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16470#issuecomment-354863557. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by festiveox** [comment]
Hello, I will like to add that the issue was with the atom-react plugin, after I disabled it Atom worked correctly.

Thanks to Jason Park for pointing it out.

And thanks Atom for looking into this.
