### ISSUE TITLE
z-index of “conflict blocks” and z-index of “highlights” container are incompatible

### ISSUE THREAD

**Issue by mikol-styra** [atom/atom#16479]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I ran into issue #12722 – “Bracket matching is hidden by line background-color (due to z-index)”. As noted there, the root cause is that the cursor line highlight is rendered at a higher z-index than the matching bracket highlight. Well, the fix for that is pretty straightforward: bump the `class="highlights"` container up a notch so that it renders over its `class="lines"` sibling.

However, setting the z-index of the highlights container higher breaks portals like “conflict blocks”. Because conflict block portals (and presumably others) live within the lines container, and the highlights container is z-indexed above it, the portals are insensitive to mouse events (over, click, …). 

The DOM has put us between a rock and a hard place. If we want a cursor line highlight, we lose bracket matching highlights. If we “fix” bracket highlighting, we lose portals. 😞 

### Steps to Reproduce

1. Use a syntax theme with a current line highlight (e.g., https://github.com/mikol/filter-syntax/releases/tag/v0.3.1)
2. Notice that bracket matches on the current line are faint or invisible.
3. Now use a syntax theme with a current line highlight fixed to use a compatible z-index (e.g., https://github.com/mikol/filter-syntax/releases/tag/v0.3.3)
4. Notice that bracket matches on the current line are clearly visible
5. Introduce a merge conflict
6. Notice that the “Use me” buttons in the conflict blocks cannot be clicked and do not display the pointer cursor.

**Expected behavior:** Allow current line highlighting, matching brackets highlighting, and portals like “conflict blocks” to work together.

**Actual behavior:** You can have (a) matching brackets and conflict blocks but no current line highlight. Or (b) current line highlight and conflict blocks but broken bracket matching highlights. Or (c) current line and matching bracket highlights but broken conflict blocks. Never all three at the same time.

**Reproduces how often:** 100%

### Versions

 > atom --version
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

 > apm --version
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.10
git 2.15.1

**Comment by simurai** [comment]
Currently there is this option: Use transparency for the cursor line background. E.g. [one-dark-syntax](https://github.com/atom/one-dark-syntax/blob/8c4922f6f964a24ce8f4d352cbac1a9ec3a15f42/styles/syntax-variables.less#L51). Then things like the bracket matcher are still visible underneath.

Or if you use `z-index` on stuff in the highlights container, you might can try to also use `pointer-events: none;`. That should make it "invisible" to the mouse and "clicking through" should still work.

I'm also wondering if the cursor line should move into the highlights container, just like selections. That needs changes in the editor tough.

**Comment by mikol** [comment]
@simurai – Thanks for the `pointer-events` tip. Didn’t think of that.
