### ISSUE TITLE
Detect and resolve file paths in files

### ISSUE THREAD

**Issue by cameronmcefee** [atom/atom#1647]
/img mind blown

support/c1480c969fbf11e39822f9a01bbb8911?page=1

It'd be awesome if we could detect files, and provide a way to navigate to the link (relative or absolute). Perhaps it becomes a context menu option when you right click on a file path.

**Comment by nextlevelshit** [comment]
:+1:

**Comment by cameronmcefee** [comment]
Closing this as https://atom.io/packages/navigate takes care of it.
