### ISSUE TITLE
bug with font rendering on Debian

### ISSUE THREAD

**Issue by pprw** [atom/atom#16475]
### Description

Hi,

Atom is affected by a bug related to font rendering (screenshot attached) on Debian sid.

It is probably the same bug that affected firefox and thunderbird earlier (now patched).

See:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=878870

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Steps to Reproduce

Install and open Atom on Debian sid. Use the menu.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

$ atom --version
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Debian sid (unstable) with xfce.

**Comment by 50Wliu** [comment]
> Atom is affected by a bug related to font rendering (screenshot attached)

I'm not seeing any screenshots.  Though I do believe that it's the same freetype issue, and will be fixed in the upcoming Electron upgrade (#16282).  In the meantime, feel free to subscribe to #15737 for updates.

**Comment by pprw** [comment]
Yes it is the same bug than #15737 (sorry for that). Here is the screenshot missing for post 1. I wait the electron upgrade.
![capture d ecran_2018-01-02_23-02-32](https://user-images.githubusercontent.com/5262986/34501896-4447b52e-f011-11e7-8c93-8958ba19bc1a.png)
