### ISSUE TITLE
How to control what tabs load when Atom opens.

### ISSUE THREAD

**Issue by abalter** [atom/atom#16477]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I open Atom, it loads three tabs in a split screen mode. In the left split is "Welcome." In the right split is "Welcome Guide."

I'd prefer to have Atom open with either no loaded tabs, or reproduce the previous state. 

I currently have "Open Empty Editor on Start" checked, and have "Restore Previous Windows on Start" set to "Yes."

### Steps to Reproduce

1. Create a folder called "atom project" and place a file "hello.py" in that folder.
2. Open Atom.
3. Close the Welcome and Welcome Guide tabs.
4. Open the project directory from File>Add Project
5. Open hello.py
6. Close Atom
7. Open Atom

**Expected behavior:** 
Atom opens in single pane mode with project "atom project" loaded and "hello.py" open.

**Actual behavior:** 
Atom opens in split pane mode with "Welcome" and "hello.py" in the left pane, and "Welcome Guide" in the right pane.

### Versions
1.23.1

**Comment by 50Wliu** [comment]
You need to disable the Welcome Guide from appearing by unchecking the "Show Welcome Guide when opening Atom" checkbox.  If you need a visual indicator, see https://discuss.atom.io/t/how-to-get-rid-of-welcome-md/12838/10?u=wliu.

**Comment by abalter** [comment]
Ok. Thanks!
