### ISSUE TITLE
Core setting "Allow Pending Pane Items" don't work

### ISSUE THREAD

**Issue by leonimurilo** [atom/atom#16476]
### Description
I was searching for a solution to stop the annoying (my opinion) Atom feature that opens a tab and removes the other opened tabs (those that has no file changes). I ended up finding that the solution is just disabling the option "Allow Pending Pane Items" in settings.

However, when I disable this option my atom does't open any tab anymore. I tested on --safe mode too, and the same occurs.

### Steps to Reproduce

1. Go to settings
2. Select core tab
3. Uncheck the "Allow Pending Pane Items" option

**Expected behavior:** Open every file in a new tab

**Actual behavior:** Atom does't open any file

**Reproduces how often:** Always (even tried on --safe mode)

### Versions

`atom --version` output:
```
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
`apm --version` output:
```
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.10
git 2.14.3
```
OS:
macOS High Sierra 10.13.2

**Comment by 50Wliu** [comment]
When the "Allow Pending Pane Items" option is unset you have to double-click to open a file.  If you would rather have that option disabled but keep the ability to single-click open a file, you may be interested in the https://atom.io/packages/single-click-open package.
