### ISSUE TITLE
Feature requests: Load different package with different mode.

### ISSUE THREAD

**Issue by AlynxZhou** [atom/atom#16474]
First thanks your work on atom, I love it and custom it with my will.

I suggest that atom needs feature like emacs' modes, because now so many packages has different keymaps or loading time, for example I use autocomplete-java-minus, but it loads and scans classes every time even I am not doing with java code. If we have some manager let different package being used when their file types are loaded will be good.

Plus I created my own keymap, and when I want to make it a package I found key inflicting in Atom is really annoying, different packages has their own keymaps, and they will be applied into atom in a mess, I mean there is no way to change them in a efficient way but copy and paste them into my `keymap.cson` one by one, plus some keys can not be unset in this way, for example atom use `ctrl-k xxx` control panels but I want to change it to cut to line end, when I want to unset them I find I must unset all `xxx`, that's impossible. We may need a more efficient way to describe and change keymaps in config.

Just some of my advice, because I think those cannot be perfectly solved by one more package, if you have some reason that atom won't do this, I will follow and trying find my own way.

**Comment by 50Wliu** [comment]
Closing in favor of #11424.  @AlynxZhou feel free to add your own comments to that issue if they haven't already been raised.
