### ISSUE TITLE
5 GB Disk Space usage after several updates

### ISSUE THREAD

**Issue by domoran** [atom/atom#16482]
### Description

After Atom has updated itself a couple of times, I see now a disk space usage in the "atom" directory of 5 GBs ... Investigating I found, that Atom kept old versions inside its application directory

in the folders: 

app-1.19.3
app-1.19.5
app-1.19.7
app-1.20.0
app-1.23.1

the first four of these containing 245k files, eating up GBs of space on my hard drive. Are these files still necessary? I installed Atom because I wanted I lightweight editor (to not having to use Eclipse). 

### Steps to Reproduce

Use atom over some time. Have it update itself. 

**Expected behavior:** 

- Atom should only keep necessary files
- Atom should ask before the update if previous versions should be kept

**Actual behavior:** 

- I cannot remember atom asked me to keep these files. 

**Reproduces how often:** [What percentage of the time does it reproduce?]

Probably always reproducible. 

### Versions

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Windows 7 Corporate.

**Comment by 50Wliu** [comment]
@domoran there was a bug around the 1.19 versions with the updater we used where it would fail to delete old versions.  It looks like it's working now as there aren't any versions past 1.20.  Please inform me if that's not the case!
