### ISSUE TITLE
Resizing Atom on Fedora 26 freezes computer - restart required

### ISSUE THREAD

**Issue by gabefahl** [atom/atom#16489]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When attempting to resize the Atom window, my computer locks up, and I must restart my computer.

### Steps to Reproduce

1. Start Atom normally or in safe mode
2. Resize Atom window

**Expected behavior:** Resize Atom without computer locking up.

**Actual behavior:** Resize Atom and computer locks up, requiring a restart.

**Reproduces how often:** It usually occurs during the first resize attempt, if not, it will happen within 2 or 3 attempts.

### Versions

Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Fedora: 26
Linux version 4.14.8-200

#### Journal output

Jan 04 09:20:16 localhost.localdomain atom.desktop[3408]: bash: cannot set terminal process group (-1): Inappropriate ioctl for device
Jan 04 09:20:16 localhost.localdomain atom.desktop[3408]: bash: no job control in this shell
Jan 04 09:20:16 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:20:16 localhost.localdomain org.gnome.Shell.desktop[2146]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000001 (Atom)
Jan 04 09:20:16 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:20:19 localhost.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 04 09:20:20 localhost.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-localed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 04 09:20:23 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:20:27 localhost.localdomain gnome-terminal-[2713]: Allocating size to GtkScrollbar 0x55bf2af0e4f0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Jan 04 09:20:27 localhost.localdomain gnome-terminal-[2713]: Allocating size to GtkScrollbar 0x55bf2af0e4f0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Jan 04 09:20:27 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:20:27 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:20:36 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:20:40 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:20:40 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:20:40 localhost.localdomain gnome-terminal-[2713]: Allocating size to GtkScrollbar 0x55bf2af0e4f0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Jan 04 09:20:40 localhost.localdomain gnome-terminal-[2713]: Allocating size to GtkScrollbar 0x55bf2af0e4f0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Jan 04 09:20:40 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:20:41 localhost.localdomain realmd[1475]: quitting realmd service after timeout
Jan 04 09:20:41 localhost.localdomain realmd[1475]: stopping service
Jan 04 09:20:41 localhost.localdomain audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=realmd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan 04 09:21:20 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:21 localhost.localdomain atom.desktop[3408]: Attempting to call a function in a renderer window that has been closed or released.
Jan 04 09:21:21 localhost.localdomain atom.desktop[3408]: Function provided here: worker.js:71:22
Jan 04 09:21:21 localhost.localdomain atom.desktop[3408]: Remote event names: destroyed, crashed
Jan 04 09:21:28 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:28 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:28 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:29 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:29 localhost.localdomain org.gnome.Shell.desktop[2146]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3000001 (Atom)
Jan 04 09:21:29 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:29 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:31 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:33 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:34 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:34 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:34 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:34 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:34 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:34 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:34 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:34 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:34 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
Jan 04 09:21:34 localhost.localdomain kernel: nouveau 0000:01:00.0: imem: PRAMIN exhausted
-- Reboot --

**Comment by VukanJ** [comment]
I have exactly the same problem on x86_64 Linux 4.14.11-1-ARCH with xfce4. Sometimes, after I resize the atom window my computer freezes immediately and needs to be restarted. If i take the edge of the window and wiggle it long enough my computer freezes eventually.

**Comment by rsese** [comment]
Finally had a chance to try on a vm running Fedora 26 with Atom 1.23.2 but was unable to reproduce.  I tried with the 3 different login option as well `Gnome`, `Gnome Classic`, and `Gnome on Xorg`.

**Comment by rsese** [comment]
We were never able to reproduce, can anyone still reproduce this with the latest versions of Atom?  There's been some Electron updates since 1.23.2.
