### ISSUE TITLE
AtomEnvironment instance properties missing in 1.24.0-beta2

### ISSUE THREAD

**Issue by GlenCFL** [atom/atom#16487]
### Description

[AtomEnvironment](https://atom.io/docs/api/v1.23.2/AtomEnvironment) is decaffinated in the Atom v1.24.0-beta2 release; however, the instance properties for this class are no longer documented. This means that they don't appear in either the `atom-api.json` file or (presumably) the online documentation itself.

### Steps to Reproduce

1. Grab the `atom-api.json` file from the [1.24.0-beta2 Release Page](https://github.com/atom/atom/releases/tag/v1.24.0-beta2).
2. Attempt to search out any of the properties for the AtomEnvironment class, such as `textEditors`.
3. Note the absence of any of these properties.

**Expected behavior:** The properties for AtomEnvironment should be available within an array under the `instanceProperties` key.

**Actual behavior:** The `instanceProperties`, and all of its children, are missing for AtomEnvironment.

**Reproduces how often:** 100%.

**Comment by 50Wliu** [comment]
Good catch.

**Comment by 50Wliu** [comment]
@maxbrunsfeld pinging you because of #16141 and because of your work on Joanna.  Not sure how to get instance properties to show up properly.

**Comment by maxbrunsfeld** [comment]
Oh yeah, I introduced this bug. We'll need to add some logic to [Joanna](https://github.com/atom/joanna) for documenting instance properties.

**Comment by maxbrunsfeld** [comment]
I'm sorry about that @GlenCFL; that was a huge oversight on my part. Fixing now.

**Comment by maxbrunsfeld** [comment]
I think this will be fixed by https://github.com/atom/atom/commit/75b4a7a984dc7afe83da12cc884acd46216c4417.

**Comment by 50Wliu** [comment]
Yep, they're back! https://6464-3228505-gh.circle-artifacts.com/0/Users/distiller/atom/docs/output/atom-api.json

Should this be cherry-picked to 1.24-releases?

**Comment by maxbrunsfeld** [comment]
Yeah, you're right. I'll do that.
