### ISSUE TITLE
SASS/SCSS autocomplete doesn't work properly

### ISSUE THREAD

**Issue by AmirFawzy** [atom/atom#16481]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
**first of all this problem happening since i updated to atom v1.22.1 and i wait for releasing atom v1.23.0 , v1.23.1 and v1.23.2 thinking this problem solved in new versions since v1.23.0 released but NO it's the same problem still happening again in every version.
#16283 and #16366 
note for mention v1.24.0-beta working good with sass/scss autocomplete.**

when i working on sass/scss files and use mixin, custom function or variables atom doesn't detecting those mixin, variables...etc
for example: when i use a variable when i write "$" which is declaration with first letter of the variable name atom doesn't show autocomplete list for all variables that start with that first letter i written it like autocomplete the variable ... and instead of that it show just suggestions for the most use words in project.

### Steps to Reproduce

1. open new SCSS file and import the _variables.scss and _mixins.scss
/or/ open new SCSS file and write any variables you want.
2. write the selector open brackets write the css property then colon .
3. write $ and the first three letters of variable.
4. autocomplete list not work properly.

**Expected behavior:** when i start type value in sass/scss starting with "$" and first, two or three letter atom show autocomplete list of all variables which start with that letter ... when i write "@include" and first, two or three letter of mixin name it should show autocomplete list with all mixins start or match that letter or word i written.

**Actual behavior:** when i write $, @include it show suggestions(autocomplete) with the most used words in project not with actual variables or mixin it doesn't auto detecting variables or mixins like it's not exist or imported with project.
look to image in reference issue that i mention it above.

**Reproduces how often:** 100%

### Versions
OS windows 10 pro v.1709 x64
Atom : 1.23.2
Electron: 1.6.15
Node : 7.4.0
apm 1.18.12
npm 3.10.10
node 6.9.5 x64

### Additional Information
problem still happening for the third update after v1.23.0 i totally believed this problem gonna be solve in new version v1.23.2 specially after @leroix find out the source of problem i hope to see next version very soon without this problem .. good luck

**Comment by rsese** [comment]
Thanks for reaching out again @AmirFawzy - it's not necessary to open a new issue for this, not all fixes are hotfixed to stable so I'll go ahead and close this.  I should have been more clear in the other issue you opened, the fix looks like it's in 1.24 (currently beta) like you mentioned /cc https://github.com/atom/atom/issues/16158#issuecomment-353633377.

Are you having trouble with the beta?

**Comment by AmirFawzy** [comment]
1.24-beta no issue with it but what about next versions is this problem gonna fix?

**Comment by 50Wliu** [comment]
1.24+, yes.
