### ISSUE TITLE
Linux & Atom: Text entered into editor sometimes injected into wrong line

### ISSUE THREAD

**Issue by mrnagy88** [atom/atom#16480]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There is a really odd behavior where text entered looks correct when I enter it but after saving it's been put into a different part of my HTML file (like the wrong line).

### Steps to Reproduce

1. Enter some text into my html file, usually with "CTRL-V", or sometimes even when typing manually
2. Save my file
3. Switch windows and come back to Atom (not sure if this part is required but more likely the window updates on save?)
4. Come back to the text editor to view the code I just entered

You would expect the text to be entered exactly where the cursor was located when pasting or typing.

Sometimes when I return to the editor, I will find that my text was pasted or typed to the incorrect place in the file, often breaking other codes or causing pieces of code to show up on the page. The text i have just entered will have been injected in the middle of other code almost randomly instead of where I was actually typing or pasting it.

I've been very careful about where I paste the text, but this has happened about a dozen times already since I installed linux and the Atom editor.

It doesn't always happen but about once every 30-50 edits, maybe a bit less often.

I wonder if perhaps I'm accidentally pasting the text and not aware of it since I'm not sure about all keyboard shortcuts in linux, so there is a very small chance that this was a user error and I just pasted it in the wrong place and was not aware of it.

### Versions

**ATOM Version**
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.11

**APM Version**
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 2.7.13
git 2.15.1

I don't have many plugins installed yet as it's all a fresh install, but some things I've added are atom-zurb-foundation (snippets), linter, linter-csslint, linter-eslint, linter-js-yaml, minimap 4.29.7, intentions, file-icons, color-picker, busy-signal and 80 core packages pre-installed.

**OS Information**
Solus 3 64-bit v 3.26.2

I'm running in safe mode now but will let you know if it pops up again it takes a bit of time.

**Comment by Ben3eeE** [comment]
@mrnagy88 Can you say if pasting the text that reproduces this issue causes the horizontal scrollbar to show? Do you have a screenshot of the issue?

/cc: @nathansobo

**Comment by mrnagy88** [comment]
I have a feeling this is the middle button action, I'm probably just scrolling with my scroll wheel and not realizing it's pasting data along the way.
It was still happening after safe mode but I think it's just a linux user interface thing:
I'm supposed to disable editor.selectionClipboard (once I figure out how to do that)

So I guess this can be marked closed.

**Comment by Ben3eeE** [comment]
@mrnagy88 Thanks for reporting back 🙂 I don't know how to disable editor.selectionClipboard. Maybe you can find the answers on the forums: https://discuss.atom.io
