### ISSUE TITLE
Atom Linux releases should help users discover package repositories for future updates

### ISSUE THREAD

**Issue by daviwil** [atom/atom#16498]
Following up on @exploide's feedback from issue #2956:

> The discoverability of the new repositories is not optimal, yet. One needs to dive into the flight manual, but most users probably just download the standalone deb/rpm from the landing page. Maybe it's a good idea to adapt this install workflow by linking directly to the flight manual or by introducing explanatory "overlay-popups" like Signal does (click "Signal for Debian-based Linux") signal.org/download

We should find a good way to either educate the user about the availability of package repositories for Linux or help them configure the use of those repositories in an automated way.  It might be difficult to do complete automation for registering the package repositories on their system, but it's worth looking into.

**Comment by bhack** [comment]
Can we rely on https://flathub.org/apps.html#Atom for linux?

**Comment by daviwil** [comment]
You can certainly use it, if that's what you mean.  However, there could be downsides to that according to this information given by a user who tried it: https://github.com/atom/atom/issues/11837#issuecomment-351001958.

This particular issue is about surfacing information to Atom users on Linux that we have .deb and .rpm package feeds now and helping them configure one for use with their package manager.

**Comment by bhack** [comment]
Yes it is not easy today to combine sandboxing with Atom. See also https://github.com/atom/atom/issues/14860.
Where are the feeds?

**Comment by daviwil** [comment]
You can find information about that here: http://flight-manual.atom.io/getting-started/sections/installing-atom/#installing-atom-on-linux

**Comment by bhack** [comment]
Probably the deb could be something like [Google Chrome distributuon](https://www.google.com/linuxrepositories/)

**Comment by in-in** [comment]
Why adding an official Atom repository is such a complicated process?

In an unofficial repository, the process looks very simple
Only one line: `sudo add-apt-repository ppa:webupd8team/atom`

On the other side official approach:
```bash
curl -L https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
```
```bash
sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
```
I don't even understand what's going on. Perhaps you will start mining on my GPU 😉  



By the way fresh installation of Ubuntu 16.04 do not has curl

**Comment by bhack** [comment]
Are the beta packages out of sync?

**Comment by daviwil** [comment]
@bhack yep, that's my fault, it's been a manual process so far.  I'm finishing up release automation for it now so that they'll automatically get updated when we push an update.  We'll be up to date again tomorrow :)

**Comment by outfrost** [comment]
@in-in Wherein does the complication of said process lie?

PPAs are an Ubuntu-specific thing. The official repository is available to all APT-equipped distros (certainly to most or all Debian-based ones).

All these commands do is fetch a GPG signing key for the repository, add it to APT, and then add the repository as a package source for APT. Clean and safe, as long as you trust Atom packages ;) There are GUI options to do the same things (like Ubuntu's and Mint's "Software Sources" application), but these 2 shell commands are by far the quickest and most universal way (think different distros and different GUI tools in different desktop environments).

One good way to improve this whole process would be to get Atom onto major distros' central repositories (such as Ubuntu's `universe` repositories) and simply have it be installable via `apt install atom` or a GUI equivalent. I don't know what the process of achieving this would look like though.

**Comment by bhack** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=747824

**Comment by outfrost** [comment]
@bhack Thanks for the link, I had no idea. Seems like preparations went smoother than I'd expect, looking forward to the outcome of the undertaking.
