### ISSUE TITLE
github intergration package + unstaged binary files in project folder = 100%+ Atom Helper CPU usage

### ISSUE THREAD

**Issue by oleggromov** [atom/atom#16490]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I have a few big binary unstaged files (png screenshots) in a git repository in a project folder, Atom Helper goes crazy consuming ~100% of CPU. Removing these files (or maybe commiting them to a repository, haven't tried it) or disabling github plugin resolves the issue.

### Steps to Reproduce

1. Add/change some huge images in git repository in your project folder. Make sure they're not new, but existed before and have changed since then.
2. Open your project folder in Atom
3. Open Activity Monitor and look for Atom Helper
4. It should skyrocket consuming CPU

**Maybe it's also cause by git LFS being used in the project** but I'm not sure.

**Expected behavior:** it shouldn't cause any side effects 

**Actual behavior:** probably Atom starts somehow analyzing binary files not taking into consideration their relatively large size.

**Reproduces how often:** 100% 

### Versions

```
atom -v
Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

MacOS 10.13.2

```
git --version
git version 2.14.3 (Apple Git-98)
```

**Comment by rsese** [comment]
Thanks for the report - I went ahead and copied this over to https://github.com/atom/github/issues/1272 so we have it in the right place.
