### ISSUE TITLE
Windows installer graphic blurry on high-DPI screens

### ISSUE THREAD

**Issue by simurai** [atom/atom#16503]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Windows installer graphic looks blurry when using a hi-res screen.

![installer](https://user-images.githubusercontent.com/378023/34634855-a7092f50-f2cb-11e7-83fc-454e5ed4632c.gif)

### Steps to Reproduce

1. Install Atom on Windows with a hi-res screen

**Expected behavior:** Installer graphic should look sharp

**Actual behavior:** Installer graphic looks blurry

**Reproduces how often:** 100%

### Versions

Since 2 years

**Comment by simurai** [comment]
Not sure if we still have the source file to export the animation. If not, I can see two options:

- Make the text bigger and then scale the gif down to 50% when shown on hi-res screens. The animation will be half as big.
- Replace it with a different animation and make 1x and 2x versions.

**Comment by warpdesign** [comment]
And in low-DPI, it's too small and unreadable (that's on Wiindows 10, with a full-HD 1080p screen with default 100% scaling).

![atominstall](https://user-images.githubusercontent.com/199648/35231003-ef455216-ff97-11e7-90b5-5317b82be4e8.png)
