### ISSUE TITLE
DISPOSE of MENU item not functioning as expected.

### ISSUE THREAD

**Issue by ghost** [atom/atom#16508]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode.
    * Followed all applicable steps in the debugging guide.
    * Checked the FAQs on the message board for common solutions.
    * Checked that your issue isn't already filed.
    * Checked that there is not already an Atom package that provides the described functionality.

<br>

### Description

Tags: API, menu, atom.menu.add(), dispose()

If a menu object is disposed, this object is not disposed properly when one of the object's items is a 'separator`.

Building the object would be with the instruction
`favoritesMenu = atom.menu.add( .. )`

Disposing of the object would be..
`favoritesMenu.dispose()`

<br>

### Steps to Reproduce

1. Open the development console in Atom.
2. Execute code in the console to create a complex menu entry.
`favoritesMenu = atom.menu.add( .. )`
3. Execute code in the console to dispose of the menu entry.
`favoritesMenu.dispose()`

- - - -

#### Scenario1 - Does work
Execute code in the development console...
* Creates menu items as expected.<br>
Notice the `- - - -` item.
```js
favoritesMenu = atom.menu.add ([{
  label: 'Extra',
  submenu : [{
    label: 'Test',
    submenu: [
      {label: 'item1'},
      {label: '- - - - '},
      {label: 'item2'}
    ]
  }]
}])
```

* Dispose all menu items as expected.
```js
favoritesMenu.dispose()
```

- - - -

#### Scenario2 - Does not work
Execute code in the development console...
* Creates menu items as expected.<br>
Notice the `separator` item.
```js
favoritesMenu = atom.menu.add ([{
  label: 'Extra',
  submenu : [{
    label: 'Test',
    submenu: [
      {label: 'item1'},
      {type: 'separator'},
      {label: 'item2'}
    ]
  }]
}])
```

* Attempt to dispose all menu items with unexpected result.
```js
favoritesMenu.dispose()
```
- - - -

**Expected behavior:** [What you expect to happen]
All items are removed from the menu if `dispose()` is executed.

**Actual behavior:** [What actually happens]
Scenario1 occurs as expected. Scenario2 does not work as expected.
Scenario2: Items `item1` and `item2` is removed as expected. however `Extra -> Test -> separator` remains. Restarting Atom brings back normality.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

* Atom V1.23.2 
* Atom V1.24-beta 2
* Windows 10 Professional

### Additional Information

Originally reported by @gliviu on https://discuss.atom.io/t/menu-refresh-fails-for-separators/51255. @gliviu constructed similar coding in `init.js` which led him to discover the behaviour.

Thanks for your attention.
\- Dan Padric

**Comment by 50Wliu** [comment]
Confirmed.

**Comment by darangi** [comment]
This has already been fixed in the latest version of atom.
