### ISSUE TITLE
Atom giving unrelated suggestions

### ISSUE THREAD

**Issue by peterzhu2118** [atom/atom#16507]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom gives some totally unrelated suggestions that are ridiculously annoying. I think it is caused by Atom being too sensitive for the keywords. In this example, if I type `test` it gives me the suggestion `ActiveSupport` (which are totally unrelated to each other). I've had similar issues occur numerous times already.
![capture](https://user-images.githubusercontent.com/15860699/34651247-b02f0a70-f39b-11e7-8f4f-a42834a9b563.PNG)

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

OS: Windows 10 Professional
Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by maxbrunsfeld** [comment]
> if I type `test` it gives me the suggestion `ActiveSupport` (which are totally unrelated to each other).

This is the intended behavior. They aren't unrelated: `ActiveSupport` contains the sequence `t, e, s, t`. It's true that they don't *start* with the same letter... We already prioritize matches in a way that boosts suggestions that contain matches at the start of words.

Maybe what you want is a config setting that *requires* that autocomplete suggestions *must* start with the same letter as the current word? This would often have undesirable behavior though, we wouldn't be able to suggest `current_user` if you typed `user`.

**Comment by peterzhu2118** [comment]
@maxbrunsfeld What I'm saying is that this is too sensitive, to the point where its very annoying. `current_user` contains the word `user`, but `ActiveSupport` doesn't contain the word `test`. When I press enter on the word `test` (I want a new line), it instead replaces it with `ActiveSupport` which is not an action that I want. I now have to get into the habit of pressing space before every new line to prevent this from happening.

**Comment by 50Wliu** [comment]
> `ActiveSupport` doesn't contain the word `test`

There have been numerous discussions about this in the past, and the reason `ActiveSupport` is suggested is because there are people (including me) that like to type e.g. `lsre` for `LocationSuffixRegExp`.  Now of course in that example all the letters I typed are uppercase in what I want autocompleted, but that is not necessarily the case.

So to modify @maxbrunsfeld's suggestion: are you looking for a setting to only allow autocomplete-plus to suggest words that (strictly) contain what you're typing?

In the meantime you can change "Keymap for Confirming a Suggestion" to "tab always, enter when suggestion explicitly suggested" if you find the enter behavior to annoying.

**Comment by nishnash54** [comment]
It continues suggesting even after completion of the keyword.
![issue](https://user-images.githubusercontent.com/25393122/36348211-6d445ccc-1490-11e8-9255-1c7ead5e03ab.png)

**Comment by matt3224** [comment]
Something has changed and autocomplete is now fairly useless. Here's what I get if I type `$`:
<img width="735" alt="screen shot 2018-02-24 at 10 37 18" src="https://user-images.githubusercontent.com/2401925/36629536-e01d197e-194e-11e8-93f6-3dfc73a8c061.png">

Here's what i get if i type `log`:
<img width="782" alt="screen shot 2018-02-24 at 10 37 30" src="https://user-images.githubusercontent.com/2401925/36629550-f21e4652-194e-11e8-917e-ad203bbaa82e.png">

In the past if i typed log it would suggest `console.log()` and meant I could simply type log and hit enter. Now it's broken and is simply just in the way. It's not suggesting anything relevant in js currently

**Comment by rsese** [comment]
@matt3224 are you using ide-typescript?  If so it looks like you're hitting https://github.com/atom/ide-typescript/issues/93.

**Comment by matt3224** [comment]
@rsese yes i think so
