### ISSUE TITLE
Font rendering looks poor on non-retina

### ISSUE THREAD

**Issue by bnferguson** [atom/atom#1650]
> Font rendering looks non-native. In particular, on non-retina displays with subpixel font rendering enabled, it looks like your fonts are using a different rendering engine (Freetype?) and at least are not using subpixel antialiasing. It looks janky. I suppose you don't notice on a retina display?

From: support/6d8865b29fb811e391bb3f51061e064b

**Comment by AndreasBackx** [comment]
@kevinsawicki @nathansobo Care to take a look at this issue. Duplicates of this issue have been reported and the issue has been ignored so far. I would love to switch to Atom, but this hurts my eyes after a short while that Atom becomes unusable.

Here are 2 pictures, you decide which version is best:
![Screenshot 1](https://i.imgur.com/sisD776.png)
![Screenshot 2](https://i.imgur.com/zxuj1h0.png)

**Comment by nathansobo** [comment]
If someone could hound the Chrome team about using subpixel anti-aliasing on GPU layers with opaque backgrounds, or investigate the source of the issue in the Chromium rendering layer, that would really help. I agree not using subpixel AA is bad, but it represents a pretty big distraction for a core team member to go digging around in the rendering internals at this time. We will end up doing that if we have to.

**Comment by AndreasBackx** [comment]
@nathansobo I guess we need someone from a big company or we won't be getting a reply on any of Google's issue trackers. That's the way it goes these days from my experience. I want to use Atom 1.0 so badly now that it 1.0 has been released, but Atom 1.0 still seems to have this problem as I was expecting.

**Comment by nathansobo** [comment]
What platform? Because so far I've seen reports of it working correctly for people.

**Comment by AndreasBackx** [comment]
I'm currently on Mac OSX 10.11 Beta 2, I just compared Sublime Text 3 with Atom on Windows 7 and the problem persists. This is on a 1440p display without scaling.

**Comment by mmoh** [comment]
`.editor { -webkit-font-smoothing: subpixel-antialiased; }` does not seem to do anything on windows. E.g. source code pro is really hard to use with atom compared to sublime.

**Comment by peduxe** [comment]
@mmoh oh yes windows, renders really poorly. A hack I found is to add stroke to your fonts.

```less
-webkit-text-stroke: 0.015em;
```

Play around with the stroke width until you get something good, it will be blurry and you may not like but it's the best I could do when I was using Windows.

**Comment by mmoh** [comment]
@peduxe Yeah that really does not work well, just makes everything blurry even after playing around with it. The visual studio code editor has good font rendering. I wonder what they are doing. Unfortunately it's not open source, but I'm pretty sure they're using the same electron back-end.  On an unrelated note, that editor is substantially less buggy and a delight to use compared with atom, which alway seems to hang up for some random reason  (my experience on windows).

**Comment by AndreasBackx** [comment]
@mmoh Same goes for OSX at the time I posted those screenshots.

**Comment by derekperkins** [comment]
I still notice it on Retina and non-Retina displays, using OSX El Capitan.

**Comment by lee-dohm** [comment]
Atom uses the `-webkit-font-smoothing: subpixel-antialiased;` rule by default now (and has been for a long time). Unfortunately, there is no way to force Chromium to use subpixel antialiasing. The -webkit-font-smoothing CSS rule is a recommendation, not a requirement.

Because of our choice to use Chromium as the rendering engine, there will be differences between how Atom renders things and how other applications that use native font rendering display things. Unless we decide to switch completely to native font rendering across the board, this will continue to be the case. That change is far too expensive for us to consider at this point in time.

With that said, there are cases where there are bugs, not simply differences, in rendering and we are interested in finding and fixing those. If in doubt, please report any problems and we'll work with you to help track things down.

Thanks for your feedback!

**Comment by AndreasBackx** [comment]
Thank you for taking a look @lee-dohm. Unfortunate that this isn't valued that highly. It makes it pretty much unworkable because it stresses the eyes, those are at least my experiences.

**Comment by odahcam** [comment]
Forcing hardware rendering did the trick!

In stylesheet.less:

```less
.tree-view,
atom-text-editor {
    -webkit-font-smoothing: antialiased; // forces hardware rendering, which improves text quality in Mac
    // -webkit-text-stroke: 0.01em; // use when without font-smoothing, also almost does the trick
}
```

**Comment by LiamKlyneker** [comment]
@odahcam thanks!! 🙌
