### ISSUE TITLE
toggleLineCommentsForBufferRows not respected

### ISSUE THREAD

**Issue by rsese** [atom/atom#16514]
Reported in halp: support/9de8cd36f0dc11e794c1b414dfdb471a

> Atom used to take commentStartString verbatim; however, in recent versions, it no longer respects user wishes/configuration -- instead erroneously imposing arbitrary and undesired formatting. Specifically, toggleLineCommentsForBufferRows (in text-editor.js) is hardwired to trim commentStartString, then subsequently append a space, as opposed to simply respecting the value set in commentStartString. If a user has gone to the trouble of removing trailing space from commentStartString of any/all grammars, toggleLineCommentsForBufferRows should not be reintroducing them.

Behavior changed in https://github.com/atom/atom/pull/15977.

**Comment by lee-dohm** [comment]
Thanks for the bug report!

Unfortunately, we're not going to be able to get to this in the foreseeable future. However, we would be willing to review a well-written pull request addressing this.

Thanks again!
