### ISSUE TITLE
Data loss when renaming folder to same name but different case

### ISSUE THREAD

**Issue by lensbart** [atom/atom#16510]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When renaming a folder in the file tree panel, the folder itself and all of its contents are permanently lost (i.e. not moved to the trash) when an identical name is chosen except for the first letter which is switched from lowercase to uppercase or vice versa

### Steps to Reproduce

1. Open Atom
2. Don't rename an existing folder like I did and lose 2 days of work
3. Create an empty folder by right-clicking the file tree and choosing new -> folder
4. Choose a folder name e.g. `watskeburt`
5. Right-click this folder and choose "Rename"
6. Change the first letter of the name you chose to uppercase or lowercase, whichever is different, e.g. `Watskeburt`
7. Observe how this folder now irretrievably disappeared

**Expected behavior:** Renamed folder

**Actual behavior:** Folder disappeared

**Reproduces how often:** 100%

### Versions

1.23.2
macOS High Sierra 10.13.2

**Comment by 50Wliu** [comment]
Hmm, I'm unable to reproduce this on Windows 10 x64, Atom 1.25.0-dev-5849ebde7.  I've added a GIF of my attempted repro steps below; please tell me if I should be doing something different!
![rename-folder-case](https://user-images.githubusercontent.com/2766036/34687525-ef213302-f47c-11e7-8c62-2ae1a61cd144.gif)

/cc @ungb @rsese

**Comment by lensbart** [comment]
Hmm. That’s exactly what I did, though! Maybe it’s related to the file system on macOS.
![e](https://user-images.githubusercontent.com/20876627/34687798-21561bac-f4b0-11e7-9115-a08715e841fd.gif)

**Comment by rsese** [comment]
From the GIF it looks like you're using Nuclide?  I'm unable to reproduce with Atom's default tree view on macOS 10.12.6.

Can you reproduce in safe mode (`atom --safe`) @lensbart?  If not, I think this is an issue for https://github.com/facebook/nuclide.

**Comment by lensbart** [comment]
I can’t get the tree view to show up in safe mode. Is there a shortcut for this?

I thought I confirmed the problem in safe mode when initially submitting the issue, although it could be that in trying I opened a new window in which nuclide was active.

**Comment by rsese** [comment]
<kbd>cmd-\\</kbd> should toggle the tree view - it's also possible that tree-view might be disabled so you can check that too at `Settings > Packages` and then search for `tree-view` to see if you need to enable it.

**Comment by lensbart** [comment]
Thanks. `tree-view` was disabled. The issue doesn’t occur in safe mode, only with nuclide enabled as suggested above. I’ll post this issue at their repository
