### ISSUE TITLE
Can't see text after selecting it

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#16516]
### Description

Using a recent dev build of Atom (1.25.0-dev-dced608f4), selecting a line makes the line's text invisible.

### Demo

![demo](https://user-images.githubusercontent.com/2988/34727862-2ba26b26-f526-11e7-8b2f-7f1d61bba5a7.gif)

### Steps to Reproduce

1. Build Atom from source at https://github.com/atom/atom/commit/dced608f4
1. Start Atom in safe mode
1. Select a line of text

**Expected behavior:** The styling should show that the line is selected and you should still be able to see the line's text.

**Actual behavior:** The styling shows that the line is selected, but you can't see the line's text.

**Reproduces how often:** 100%

### Versions

On macOS 10.13.2...

```
$ atom --version
Atom    : 1.25.0-dev-dced608f4
Electron: 1.7.10
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-dev-dced608f4
python 2.7.10
git 2.15.1
```

**Comment by as-cii** [comment]
This has just been fixed via #16515, so I am going to close it. Thanks for reporting though! ❤️
