### ISSUE TITLE
Syntax highlighting not updating after inserting a missing comma on previous line

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#16519]
In the example below, I add a method to an object literal, but forget to insert a comma after the previous item. Note that the method name does not turn blue after inserting the missing comma. I have to go to the next line and change its indent level for the highlighting to update.

![highlight-invalidation-bug](https://user-images.githubusercontent.com/1789/34732041-4e7f0636-f521-11e7-86ea-689bff587dee.gif)

See [this gist](https://gist.github.com/nathansobo/c82809a5fe38151ac5601846687f0e4c) for the content being edited in the above gif.

/cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
Fixed via https://github.com/atom/atom/pull/16633
