### ISSUE TITLE
Atom taking down system after upgrading to 1.23.3

### ISSUE THREAD

**Issue by danqing** [atom/atom#16529]
Does *not* happen in safe mode but happens every time in dangerous mode.

Basically, immediately when I open Atom, it will try to open a *ton* of Atom Helpers (like maybe 100 of them), which takes about 40GB of memory (20GB+ in swap) and counting, freezing the entire OS. It doesn't happen in safe mode but because it happens immediately after opening, I'm not sure what I can do to see what's going on...

At least if someone run into the same problem we can surface it here.

macos 10.13.2.

**Comment by Zireael07** [comment]
What packages do you have installed? Since it doesn't happen in safe mode, it's a fairly safe guess that it's a misbehaving package.

**Comment by danqing** [comment]
@Zireael07 I have the following:

```
MagicPython@1.0.12
atom-beautify@0.30.9
atom-ide-ui@0.7.1
atom-jinja2@0.6.0
auto-detect-indentation@1.3.0
autocomplete-python@1.10.5
busy@0.7.0
busy-signal@1.4.3
duotone-dark-syntax@2.1.0
duotone-snow@2.2.0
duplicate-removal@0.1.3
file-icons@2.1.15
go-debug@1.5.3
go-plus@5.7.2
go-signature-statusbar@1.2.3
hey-pane@1.1.0
ide-typescript@0.7.2
import-sf-mono@1.0.1
indent-guide-improved@1.4.13
intentions@1.1.5
language-docker@1.1.8
language-gettext@0.6.1
language-ini@1.19.0
language-jade@0.7.2
language-mako@0.6.0
language-nginx@0.8.0
language-protobuf@0.7.1
language-pug@0.0.21
language-swift@0.5.0
linter@2.2.0
linter-docker@0.3.0
linter-eslint@8.4.0
linter-flake8@2.3.0
linter-json-lint@0.1.2
linter-ui-default@1.6.10
merge-conflicts@1.4.5
one-dark-vivid-syntax@1.8.0
pigments@0.40.2
pristine-ui@1.1.11
python-indent@1.1.4
python-tools@0.6.9
react@0.17.0
script@3.17.3
sort-lines@0.18.0
tone-syntax@0.2.0
uglify@1.3.1
```

I'm not sure - I've discovered that if I open a blank Atom window things don't blow up, but as soon as I open (any) project the problem appears. I've also downgraded to 1.23.2 and unfortunately the issue persists :(

**Comment by Zireael07** [comment]
Pigments is a common culprit in those kinds of issues, try disabling it?

**Comment by danqing** [comment]
That.... apparently worked. Thanks @Zireael07 !
