### ISSUE TITLE
Support protocol handlers on Linux

### ISSUE THREAD

**Issue by BinaryMuse** [atom/atom#16532]
Electron is getting protocol handlers on Linux via xdg-open in https://github.com/electron/electron/pull/10670. We should support Linux (by changing code in atom/atom and atom/settings-view) once we're using a version of Electron that supports this.

**Comment by daviwil** [comment]
I can take a look at this unless you had planned on it :)

**Comment by BinaryMuse** [comment]
@daviwil Feel free! By the time it's ready to be implemented, I won't be working on the feature anymore ;)

**Comment by daviwil** [comment]
Haha, true!

**Comment by thomasjo** [comment]
Electron v1.8.2 added the necessary bits for us to support this on our end. In other words, we'll have to upgrade to Electron v1.8.2 or newer.

**Comment by jasonrudolph** [comment]
> In other words, we'll have to upgrade to Electron v1.8.2 or newer.

Linking these Electron upgrade pull requests:

- https://github.com/atom/atom/pull/16755 - Electron 1.8
- https://github.com/atom/atom/pull/17273 - Electron 2.0

Once one of those pull requests is merged, this issue should become unblocked.

**Comment by bronson** [comment]
Looks like 2.0 is in!  https://github.com/atom/atom/pull/17273

**Comment by julian-alarcon** [comment]
No news about this?
