### ISSUE TITLE
Need to save in the correct current folder

### ISSUE THREAD

**Issue by ppKrauss** [atom/atom#16536]
Is a interface-behaviour problem, not a "real bug". It is a requeriments or specification bug.

### Steps to Reproduce

1. "New File"
2. Write something.
2. Save (^s) or "Save"
3. **ugly navigation** to store filename into the correct (project's) folder.

 
**Expected behavior:** 

No "ugly navigation", only navigating into the **"current project"**... So, what is "currect"?  Is the last used project or the current focus of my Atom's Tree-view of folders.

**Actual behavior:** 
The ugly navigation, starts at the root of the user folder or other "ramdom place".

**Reproduces how often:**

100%

### Versions

* Atom v1.22
* Ubuntu 16 LTS

**Comment by rsese** [comment]
Thanks for the report!  Can you share more exact steps to reproduce?  For example, this is what I tried:

1. `mkdir test`
2. `cd test`
3. `atom --safe .`
4. Create a new file with <kbd>ctrl-n</kbd>
5. Save the file with <kbd>ctrl-s</kbd>

Expected and actual behavior is the save dialog is in the `test/` directory.

I tried in the latest release version of Atom, 1.23.3.

**Comment by lee-dohm** [comment]
Thanks for the feedback.

This is a duplicate of https://github.com/atom/atom/issues/6088. You may want to subscribe there for updates.
