### ISSUE TITLE
Readonly editors can be edited using middle click paste (Linux)

### ISSUE THREAD

**Issue by fabianfiorotto** [atom/atom#16538]
### Description

Readonly editors can be edited using middle click paste on linux using atom 1.24 beta.
https://github.com/atom/atom/pull/16294

### Steps to Reproduce

1. You will need to write a custom package that opens a readonly editor
2. Open the readonly editor using the custom package
3. Split the panes so you will have a normal editor on one side and a readonly one in the other
4. Type some text in the normal editor and select it.
5. Middle click on the readonly editor.

**Expected behavior:** Readonly editor should keep unmodified

**Actual behavior:** The selected text is pasted on the readonly editor.

**Reproduces how often:** always

### Versions

Atom    : 1.24.0-beta3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.6
git 1.9.1

OS: Linux Mint 17.3

**Comment by fabianfiorotto** [comment]
@daviwil @50Wliu, I'm playing around with the final release and I found that I can paste code on read-only editors pressing <kbd>ctrl</kbd> + <kbd>v</kbd>. Is that a bug? or is it intended to work in that way?

**Comment by daviwil** [comment]
I believe this fix is only in 1.25.0-beta0, is that where you tried it?

**Comment by Ben3eeE** [comment]
@daviwil https://github.com/atom/atom/issues/16736 was just opened and that issue mentions testing on beta and being able to edit with many different commands.

**Comment by daviwil** [comment]
Thanks Linus!  Seems like a great candidate for the Reactor Queue

**Comment by fabianfiorotto** [comment]
You are right this fix hasn't been applied to atom 1.24. I don't understand atom's release schedule. If I create an issue now, Do I have to wait until 1.26 to see the fix published?
