### ISSUE TITLE
UTF-16 file incorrectly tagged as UTF-8

### ISSUE THREAD

**Issue by MichaelChirico** [atom/atom#16539]
When exploring this issue: https://github.com/Rdatatable/data.table/issues/2560 I used `Atom` to help identify the encoding of the [file in question](https://github.com/Rdatatable/data.table/files/1615683/test_file.txt); as seen in this screen shot, `Atom` determined it as being `UTF-8`, but as seen from the raw file, it actually has a `UTF-16` BOM, `U+FFFE` (clearly read correctly by `Atom`; related to #3427).

<img width="998" alt="screen shot of Atom" src="https://user-images.githubusercontent.com/7606389/34731302-f631b596-f52f-11e7-8f91-c11054b028e3.png">

Hex editor

![image](https://user-images.githubusercontent.com/6696142/34727867-7f34cfe0-f558-11e7-9809-6f27d38d17ed.png)

**Comment by 50Wliu** [comment]
> Atom determined it as being UTF-8

Can you walk me through the steps you took that led to this conclusions?  Please fill out the issue template next time as that gives us very useful information to work with (e.g., steps to reproduce).

**Comment by MichaelChirico** [comment]
Nothing special -- literally just open the file with Atom & the UTF-8 code appears in the bottom-right.

**Comment by 50Wliu** [comment]
Ok, thanks!  That's because we don't currently auto-detect the encoding by default.  You need to click "UTF-8" and then select the "Auto Detect" option at the top.
