### ISSUE TITLE
Invert I-bar cursor when a dark theme is used

### ISSUE THREAD

**Issue by tekkub** [atom/atom#1654]
The I-bar cursor is currently always black in Atom.  This makes it very hard to track when using a theme with a dark background.  Sublime inverts this cursor when you're using a dark theme... and it's quite wonderful.  I'd love if Atom did this too.

I don't think you can take a screenshot of the cursor, so here's some crazy photos.  Top is Atom, bottom is Sublime.  Both are using a dark solarized theme.

![2014-02-28 21 30 32](https://f.cloud.github.com/assets/706/2300567/95771684-a0fa-11e3-8351-881401e7a672.jpg)

**Comment by muhasturk** [comment]
+1

**Comment by muhasturk** [comment]
Why dont you embed [this package](https://atom.io/packages/white-cursor "White Cursor") into Atom?

**Comment by ravinggenius** [comment]
Here are screenshots comparing light and dark backgrounds. (from #8659).

<img width="273" alt="atom_light" src="https://cloud.githubusercontent.com/assets/21517/9666201/b7bc55d8-5242-11e5-88bd-5f4f4f7fca22.png">

<img width="277" alt="atom_dark" src="https://cloud.githubusercontent.com/assets/21517/9666200/b7bb0746-5242-11e5-8421-02060312fa22.png">

**Comment by mnquintana** [comment]
@lee-dohm What do you think about bringing this into core? I'd be :+1: for adding this to core, but I think the rest of @atom/feedback should weigh in too. :smile:

**Comment by lee-dohm** [comment]
I'd be fine merging [white-cursor](https://atom.io/packages/white-cursor) into core. This is only a problem on OS X though, right?

**Comment by DepthDeluxe** [comment]
The cursor is also hard to see in Linux as well.  It would be nice to have the option to turn this feature on.

**Comment by maxbrunsfeld** [comment]
What if we just added the [white cursor styling](https://github.com/lee-dohm/white-cursor/blob/1d9e205d00e328db3f73811e1f293b1ebd78d26e/styles/white-cursor.less#L5) to core, as a [less mixin](http://lesscss.org/features/#features-overview-feature-mixins)? That way, dark syntax themes could just include it.

**Comment by lee-dohm** [comment]
That's essentially what my white-cursor package does, provides a Less mixin. There's just a tiny bit of code to configure when to force it if the dark theme doesn't support it.

**Comment by maxbrunsfeld** [comment]
Yeah, I'm saying if we move this code into core, we should invert the process: let the themes import the mixin, rather than applying it separately based on a known list of 'dark' themes.

**Comment by lee-dohm** [comment]
That doesn't remove the need for the package until a critical mass of themes support it though.

**Comment by maxbrunsfeld** [comment]
> That doesn't remove the need for the package until a critical mass of themes support it though.

Agreed. The package is good as is; I'm just talking about what exactly we should add to core.

**Comment by DepthDeluxe** [comment]
Is there an option to style/color the I-bar cursor as part of a the theme?
That could be a nice feature otherwise...

**Comment by lee-dohm** [comment]
Closing this as it has now been addressed in #8663. I'll be retiring my white-cursor package also after this has been released.
