### ISSUE TITLE
Support packages with scoped names

### ISSUE THREAD

**Issue by szeck87** [atom/atom#16554]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

npm supports scoped package naming, for example `@scopename/packagename`, in package.json as a way of grouping similar packages together.  When installed, they are placed in `node_modules/@scopename/packagename`.

When Atom installs these packages, they are not recognized since the actual package(s) is in `.atom/packages/@scopename/package`.  It would be nice for Atom to support packages named this way.

### Steps to Reproduce

1. Create a new package and name it "@scopedname/packagename"
2. apm link the package (if not already), and reload Atom
3. Go to the installed packages

**Expected behavior:** Show the package in the packages view

**Actual behavior:** Shows the scoped name in the packages view, which does nothing, and package is installed to `.atom/packages/@scopename/package`

**Reproduces how often:** 100%

### Versions

1.23.3, MacOS

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by szeck87** [comment]
Moved this to `apm` repo https://github.com/atom/apm/issues/766.

**Comment by szeck87** [comment]
Actually, maybe it belongs in a few places.  Let me know where this should be opened.

**Comment by 50Wliu** [comment]
I think apm is more relevant for this.

**Comment by szeck87** [comment]
@50Wliu I thought so at first too, but the problem is the loading of packages, not installing them, which I think happens here:  https://github.com/atom/atom/blob/master/src/package-manager.js#L518

**Comment by 50Wliu** [comment]
Well apm would need to support them in the first place :).  If/when that support is implemented if there are changes necessary here they'll also be naturally updated.
