### ISSUE TITLE
Syntax setting not possible for unsaved file

### ISSUE THREAD

**Issue by garg-shubham** [atom/atom#16559]
As shown in the following screenshot, I could not find how to do syntax highlighting for an unsaved file. 
![image](https://user-images.githubusercontent.com/25582030/34919245-755da71c-f986-11e7-884a-c95279fb6d59.png)
Is there some way already implemented to do so? If not, I would like to discuss how it can be added.

**Comment by daviwil** [comment]
Have you tried using the "Grammar Selector: Show" command and then selecting the desired language grammar?  That should colorize the buffer correctly.

**Comment by garg-shubham** [comment]
Thanks for the help, @daviwil .

**Comment by daviwil** [comment]
No problem!  I'll close this issue for now.
