### ISSUE TITLE
failed to load config.cson

### ISSUE THREAD

**Issue by lintangtimur** [atom/atom#16555]
my default atom config like Theme, editor is back to default.
last time i used atom, and then shutdown my computer then BSOD (crash).

i reopen atom -> right click -> open with atom
my project is PHP, now it always show **choose autocomplete python engine**

Windows 10 64bit
6GB Ram

![alt text](https://image.ibb.co/ggSAj6/atomcrash.png "Atom error")
![alt text](https://image.ibb.co/gcgjcR/configcson.png"config.cson")

**Comment by rsese** [comment]
If you move or delete your `%USERPROFILE%\.atom\config.cson` file, a new one will be created and that should clear up the error.

For future issues, please fill out the issue template since it's helpful for us when triaging issues.
