### ISSUE TITLE
Using Atom Remotely [Lags]

### ISSUE THREAD

**Issue by EliterScripts** [atom/atom#16551]
### Prerequisites

N/A

### Description

Atom lags when saving, closing tabs, switching tabs, opening directory tree, opening file, and sometimes while typing in stuff. It also lags a LOT when opening the folder for the first time that day.

### Steps to Reproduce

1. Open nautilus
2. Click "Connect to server" (I am connecting to my Ubuntu OpenSSH server that runs my sftp/ssh--it just works)
3. Right-click on a system link on the remote site via nautilus GUI, and open with Atom.

**Expected behavior:** [What you expect to happen]
I expected the lag to only be during the connection to the server. I would think this would only happen when saving, MAYBE when listing the items within a directory in the tree, renaming, getting the file. Those would require over-the-internet information. Besides, my connection is fast enough to quickly transfer like up to 10KB's worth of information in a file to my SSH/sftp server. It should be able to send the entire directory listing of 20 items (the directories aren't that big anyway). Switching should not be a problem, as the text editor should already have all the files already saved to RAM.

**Actual behavior:** [What actually happens]
Every action lags, except when you are typing in the file you're currently in. However, sometimes typing in stuff lags when you newly open (or just switched to) a tab, then the lag goes away shortly.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time without fail. However, typing in stuff does not always lag when a tab is newly opened/switched to. I would say the "fresh-tab" typing lag happens about 1/3 of the time, but the lag goes away shortly.

### Versions
Operating System (both desktop and server):
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Nautilus:
GNOME nautilus 3.14.3

Atom:
Atom 1.23.3

### Additional Information

N/A

**Comment by catscarlet** [comment]
Atom is always watching the change of the opened files so every action will lag.

I think you can try the package [remote-ftp](https://atom.io/packages/remote-ftp), *although it can't watching the change on the remote. (I'm not sure about is. I saw a watch option but I didn't set it)*

![snap055](https://user-images.githubusercontent.com/10594035/35087881-a85556cc-fc6c-11e7-9785-e49c0d466243.png)

**Comment by lee-dohm** [comment]
Thanks for the feedback.

Making Atom work in a performant way against a remote file system isn't something that we're going to be putting resources into in the near future. One of the major benefits of Git is that it significantly reduces the dependence on a network connection to work with code in a shared project. Still, this is an important workflow for some so there are community packages available that people have put together. You may want to check them out.

Thanks again for reaching out :+1:
