### ISSUE TITLE
Git - File is corrupted when discard changes

### ISSUE THREAD

**Issue by nagman** [atom/atom#16566]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When you discard changes of a line or a group of lines in the Unstaged Changes view, it corrupts the file and you can't edit it anymore.
The only solution I've found so far is to restart the computer.

### Steps to Reproduce

1. Open a file
2. Do some changes
3. Save them
4. Go in the Unstaged Changes panel and click on the file
5. Select the line you changed
6. Right clic -> discard selection

**Expected behavior:**
I actually don't know what "discard selection" should do (I'm not an expert in Git), but I clicked on it by mistake while I wanted to click on "Stage selection".

**Actual behavior:**
The file becomes corrupted.
There's a yellow warning message saying: "Unable to save file: Permission denied".
The file also sometimes disappear from the left sidebar (not in safemoden though, so I suppose this is related to the settings where you can hide the ignored files).

You can't save it, you can't edit it, you can't delete it, and sometimes you can't open it.
I managed to open it with vim in console, but even with superadministrator rights (Windows) or sudo mode (bash for Windows) I couldn't delete it.

I had to restart the computer and THEN I could find my file back marked as deleted in the Unstaged Changes panel. Then I discard it and the file comes back in my sidebar.

**Reproduces how often:**
Each time I do the above steps (tried 3-4 times).

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python
git 2.14.1.windows.1
visual studio

**Comment by rsese** [comment]
Thanks for the report - I copied this over to https://github.com/atom/github so we have it in the right place /cc https://github.com/atom/github/issues/1283.
