### ISSUE TITLE
macOS emoji shortcut not working

### ISSUE THREAD

**Issue by DavidMay371** [atom/atom#16562]
### Description

The native emoji shortcut of macOS can not be used in atom. The shortcut for pasting in an emoji (cmd+ctrl+space) is not implemented.
It would be nice to add this to atom in order to use emojis more easily.

<img width="447" alt="bildschirmfoto 2018-01-15 um 02 12 46" src="https://user-images.githubusercontent.com/11695209/34923168-a9e97c3c-f999-11e7-9239-3ea7ebd4ab0e.png">
Here is the emoji shortcut working in vscode

**Comment by rsese** [comment]
Hmm, this is working ok for me on macOS 10.12.6 and Atom `1.25.0-dev-5a3e1d28c`:

![emoji-picker](https://user-images.githubusercontent.com/734194/34965411-7b4dc024-fa19-11e7-8e44-844feb7f855a.gif)

The issue template details would be helpful here e.g. what version of macOS are you using and what version of Atom?   Can you reproduce in safe mode (`atom --safe`)?

**Comment by DavidMay371** [comment]
Okay, so this behavior occurs on macOS 10.13.2 and Atom 1.23.3 (also not working in atom beta build 1.24.0-beta3).
It is completely irrelevant which language mode I am using (Plain Text, JSX, Javascript, HTML, CSS, etc.) the shortcut is not working. 
```atom --safe``` did not help with the issue.

**Comment by masiama** [comment]
Have macOS 10.13.2 an Atom 1.23.3 and emoji shortcut is working for me

**Comment by masiama** [comment]
By the way, this issue already exists https://github.com/atom/atom/issues/14963

**Comment by DavidMay371** [comment]
Thats weird. So the issue appears to exist on my MacBook Pro 13 2017 (MacBookPro14,1) and on my Hackintosh. I also changed the keyboard mapping in macOS from German to English which did not help. 

```apm --version```:
```
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.14.3
```

```sw_vers```:

```
ProductName:    Mac OS X
ProductVersion: 10.13.2
BuildVersion:   17C205

**Comment by masiama** [comment]
I have MacBook Pro (Retina, 13-inch, Early 2015) but everything else the same

`atom --version`:

```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

`apm --version`:

```
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.14.3
```

`sw_vers`:

```
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C205
```

**Comment by masiama** [comment]
@DavidMay371, do you have touch bar?

**Comment by DavidMay371** [comment]
@masiama Yeah I deleted the ```.atom``` directory and reinstalled Atom. But it did not help with the issue.

**Comment by masiama** [comment]
@DavidMay371 Did you installed Atom or built by your own?

**Comment by masiama** [comment]
@DavidMay371  what if remove everything listed here https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/12 ?

**Comment by masiama** [comment]
@DavidMay371 But still interesting why this happens only in Atom

**Comment by DavidMay371** [comment]
@masiama Thats why i thought Atom just did not activated this shortcut or so. VSCode, Finder, Chrome all working no problem.

**Comment by masiama** [comment]
@DavidMay371 Do you have something in Key Binding Resolver when you press cmd+ctrl+space?

**Comment by DavidMay371** [comment]
@masiama No the Key Binding Resolver is displaying nothing when hitting cmd-ctrl-space

**Comment by masiama** [comment]
@DavidMay371 Even `Key Binding Resolver: ctrl-cmd-space`?

**Comment by DavidMay371** [comment]
@masiama The `Key Binding Resolver: ctrl-cmd-space` is being displayed but no keybinding.

**Comment by masiama** [comment]
@DavidMay371 What if `Edit > Emoji & Symbols`?

**Comment by DavidMay371** [comment]
There is no Emoji entry. In VSCode it is there but Atom is not showing it.
[Uploading Bildschirmfoto 2018-01-16 um 18.10.36.png…]()

**Comment by masiama** [comment]
![screen shot 2018-01-16 at 19 14 24](https://user-images.githubusercontent.com/14037820/35002180-7ff4520e-faf1-11e7-832c-f15178ec1ea7.jpg)

**Comment by DavidMay371** [comment]
YEAH I GOT IT. So I had to set the language of the whole system to English and restart the computer in order to get the shortcut working and the entry showing up. 

So to reproduce the error, you have to change the macOS primary language to German and also set the keyboard configuration to German.

**Comment by masiama** [comment]
@DavidMay371 So the problem is solved?

**Comment by masiama** [comment]
Reproduced by setting primary language to German

**Comment by DavidMay371** [comment]
Nice okay. Thank you for your great help. 
Hopefully the devs are able to fix it easily 😀

**Comment by rsese** [comment]
Yes thanks very much @masiama and thanks for reporting @DavidMay371 :+1:

> By the way, this issue already exists #14963

I'll go ahead and close in favor of #14963, you can subscribe there for updates if you'd like @DavidMay371.

**Comment by herme5** [comment]
Sorry for reopenning the issue. Just to tell I think the same bug exists when French is the primary language. Neither the `edit` -> `emoji and symbols` button  nor the `cmd-ctrl-space` shortcut is available. 

<img width="443" alt="capture d ecran 2018-01-25 a 22 42 12" src="https://user-images.githubusercontent.com/5782013/35414079-b7dd56ca-0221-11e8-8b41-ecc7c4801bfe.png">

---

Here are my configs : 
- Atom v1.23.3 x64 (downloaded from the atom.io website)
- MacBookPro 13" - 2016, with touch bar, running on Mac OS High Sierra 10.16.3
- Primary language : French
- Keyboard language : French (AZERTY)

**Comment by rsese** [comment]
> Sorry for reopenning the issue 

No problem @herme5, this issue was just closed as a duplicate of https://github.com/atom/atom/issues/14963 so you can subscribe to https://github.com/atom/atom/issues/14963 for updates if you'd like.
