### ISSUE TITLE
Atom is being installed to the "application data" folder in Windows, for some reason

### ISSUE THREAD

**Issue by dizzy-egg** [atom/atom#16569]
When I run the latest installer on Windows 7, first of all it's [tiny and blurry/illegible](https://github.com/atom/atom/issues/16503), but secondly it doesn't give me the option to choose an install directory - or even tell me where it's installing to. 

It turns out it's installed to the "appdata" i.e. "application data" folder which seems totally backwards and illogical. I thought that folder is for, you know, application **data**, not applications themselves?

How about giving users the option to choose an install location or at the very least installing it somewhere logical?

**Comment by 50Wliu** [comment]
Thanks for your feedback!

This is intentional and we do not have plans to change this behavior.  See also https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/goals.md#installing and https://github.com/Squirrel/Squirrel.Windows/issues/1002.

**Comment by dizzy-egg** [comment]
Is there somewhere where the developers actually discuss this? In your [second link](https://github.com/Squirrel/Squirrel.Windows/issues/1002), where the submitter shares the same concerns I do, the repo's owner simply types an incredibly dismissive one-word response ("No")?

Guess I don't have plans to use or contribute to Atom.

**Comment by 50Wliu** [comment]
We are committed to using Squirrel.Windows for the foreseeable future.  Looks like they have a Slack channel with instructions to join at https://github.com/Squirrel/Squirrel.Windows/issues/9.

**Comment by lee-dohm** [comment]
@dizzy-egg There is [one main issue where it was discussed](https://github.com/atom/atom/issues/5259), yes. The part that you might be most interested in is from [my comment](https://github.com/atom/atom/issues/5259#issuecomment-175237027):

> If you want to be 100% in control of the installation and update process, you have that option. You can download the zip format for your platform and install it wherever you like. ... So while you may not approve of the choices that were made in designing the installer, there are options.

While we may not know what is best for all users, we do know best what **we** as developers are able to do and support adequately. So if you would like us to respect your desires and needs, we expect you to respect the hard work, effort, and ongoing support that we give to this project and product.
