### ISSUE TITLE
Change title of "Grammar Selector: Show" to "Grammar Selector: Change Language Mode"

### ISSUE THREAD

**Issue by daviwil** [atom/atom#16560]
Some users may have difficulty figuring out how to assign the language for the current file to enable colorization, etc.  I think part of this trouble is that the command to allow grammar selection has a name that most users wouldn't look for, "Grammar Selector: Show".  I think the command should at least have the word 'language' in the name, like "Grammar Selector: Change Language Mode".

Certainly possible for the user to click the language name in the right side of the status bar, but that may not be intuitive or expected for some users.

Related issue: https://github.com/atom/atom/issues/16559

**Comment by 50Wliu** [comment]
https://github.com/atom/grammar-selector/blob/c9234152ab2f658aac3e4b75ce2f4950ed792f68/lib/main.js#L10

**Comment by lee-dohm** [comment]
This is a perpetual argument. Some feel that we should use the term "language", some feel that [we should use the term "syntax"](https://github.com/atom/command-palette/issues/45) (there's a much longer issue where this is debated back and forth but I can't find it right now), and I'm sure there are people that are fine with "grammar".

I don't know that there is a good choice here.

**Comment by daviwil** [comment]
Let's hit all 3 with "Grammar Selector: Change Language Syntax Mode" :sunglasses:

**Comment by lee-dohm** [comment]
I was going to suggest that but didn't want to be snarky :laughing:
