### ISSUE TITLE
Saving discards forward editing history.

### ISSUE THREAD

**Issue by garretwilson** [atom/atom#16573]
I'm using Atom 1.23.3 on Windows 10 Pro 64-bit.

1. I made some edits, A, B, and C.
2. I had a problem in my code, so I wanted to see if my recent edits caused the problem. I hit `Ctrl+Z` to undo edits C and B. I saved my file and retested.
3. My recent edits weren't what caused the problem, so obviously I wanted to bring them back. I hit `Ctrl+Y` so the editor would re-do the edits B and C I just un-did.

Ack! They are gone! `Ctrl+Y` does nothing!! Apparently Atom discarded the future editing history when I saved the file!

This is a shock. I'm used to using Eclipse `Ctrl+Z` and `Ctrl+Y` all day, even when I save the file. (Of course I realize very well that _if I make an edit_ then my future history is discarded. But saving a file is not making an edit; it is merely updating the file system with the current state of the edit buffer. Why should that affect the edit history?)

Now I have to go re-do all those edits ("B" and "C" were just example; in reality there were lots of edits) that Atom discarded.

I hope this is a bug and not "expected behavior". If it is a bug, it is a huge one, as it results in loss of data.

**Comment by rsese** [comment]
Thanks for the report @garretwilson - I was looking at https://github.com/atom/atom/issues/9637 and I wonder if you're hitting something similar to what's described in https://github.com/atom/atom/issues/9637#issuecomment-214251380?

For example, if I have `Ensure Single Trailing Newline` enabled in the whitespace package, then I can reproduce:

1. Type `a` followed by a newline
2. Type `b`
3. <kbd>ctrl-z</kbd> to remove the `b`
4. <kbd>ctrl-z</kbd> to remove the newline
5. Save the file <kbd>ctrl-s</kbd>

At this point, a trailing newline is added on save and <kbd>ctrl-y</kbd> does nothing.

If I disable `Ensure Single Trailing Newline` and follow the same steps, <kbd>ctrl-y</kbd> works.

**Comment by garretwilson** [comment]
Actually, it was in the `whitespace` plugin alright, but after a quick check it seems to be the `Remove Trailing Whitespace` option.

I think this is a dangerous option because of this. `atom-beautify` should take care of that, anyway when I manually reformat. I'm disabling it.

**Comment by lee-dohm** [comment]
I'm glad things are working for you now :+1:
