### ISSUE TITLE
[OSX] Shortcut for reveal in tree view doesn't work

### ISSUE THREAD

**Issue by OlivierSohn** [atom/atom#16597]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Reveal in tree view works well when using the contextual menu, but not with the shortcut (cmd + I) on mac.

### Steps to Reproduce

1. Open a project file
2. collapse the tree
3. Hit cmd + I

**Expected behavior:** 

The tree should open and show the file

**Actual behavior:**

The tree remains closed

**Reproduces how often:**

Always

### Versions

OSX Sierra 10.13.2

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by 50Wliu** [comment]
Please reopen this over at [atom/tree-view](https://github.com/atom/tree-view).  In addition, I briefly tried to reproduce this on Windows but couldn't - if you could kindly provide a GIF of some sort or more detailed reproduction steps (such as exact commands, how nested the file is, where the focus is, etc.) in the tree-view issue that would be extremely helpful 🙇.

**Comment by OlivierSohn** [comment]
@50Wliu Thanks, I think it's easily reproducible on macosx. I'll transfer the issue.

**Comment by OlivierSohn** [comment]
In fact it seems it's just that I and | are too close to be distinguishable, cf. https://github.com/atom/tree-view/issues/1178
