### ISSUE TITLE
Bad rendering after ~1 million lines

### ISSUE THREAD

**Issue by Ben3eeE** [atom/atom#16591]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In Atom 1.23.3 the rendering stops after around ~800k lines and nothing is displayed. On a recent master Atom can render ~1 million lines and then the rendering looks really bad.

@ungb This might be due to the electron upgrade. We should add large files to the testing docs.

![bad renderer](https://user-images.githubusercontent.com/1058982/35113772-f2ffceda-fc82-11e7-81b6-6419c42ef3b4.gif)

### Steps to Reproduce

1. Open this file in Atom https://gist.github.com/Ben3eeE/22ad32cbd9106bad16648d1c23f85709
2. Scroll to the bottom

**Expected behavior:** All lines to render correctly

**Actual behavior:** Bad rendering

**Reproduces how often:** 100%

### Versions

**Atom**: 1.25.0-dev-3d8902d x64
**Electron**: 1.7.10
**OS**: Microsoft Windows 7 Professional

### Additional Information

/cc: @nathansobo @as-cii

**Comment by Zetagonality** [comment]
Can confirm, just generated a file with one million lines and it doesn't render after a large amount of lines.

**Comment by iolsen** [comment]
@maxbrunsfeld should we hardcode and add a friendly message here? Even the previous "working" version was a little weird, silently truncating at 800k lines.
