### ISSUE TITLE
Issue installing flake8

### ISSUE THREAD

**Issue by DrummyBeat** [atom/atom#16601]
So I am having some trouble install linter-flake8 on my atom for Python3.4.4.

I have installed pip and flake8 using pip in my cmd using python. That's great. I have installed the linter-base and linter-flake8 packages using atom. Also great. Then SHTF. I go into a .py file to edit some code and linter throws out this error.

[Linter] Error running Flake8 Error: Failed to spawn command `c:\python34\lib\site-packages\flake8`. Make sure `c:\python34\lib\site-packages\flake8` is installed and on your PATH
    at C:\Users\Acer\.atom\packages\linter-flake8\node_modules\atom-linter\lib\helpers.js:130
    at process._tickCallback (internal/process/next_tick.js:103)
(anonymous) @ linter-registry.js:137
_tickCallback @ internal/process/next_tick.js:103

Anyone know how I can fix this? And please explain how to set a path please as it is my first time using Atom.

**Comment by DrummyBeat** [comment]
I attempted to change the PATH in the linter-flake8 settings in atom to the above seen file pathing.

**Comment by 50Wliu** [comment]
@DrummyBeat issues are for reporting bugs with Atom itself - there are a lot more people who will be able to help you if you create a new topic on [Discuss](https://discuss.atom.io), the official Atom forum, instead.
