### ISSUE TITLE
Coding without Keyboard

### ISSUE THREAD

**Issue by SetCodesToFire** [atom/atom#16607]
This is an enhancement. I suggest we could integrate voice coding in the atom core. This could be build using deep neural networks (sequence model).

Unlike voice to speech conversion, the network could be made intelligent enough to take "equals to" as a voice input and translate it to "=".

As well as similar features and rules could be defined.

This could be the future of mobile coding.

**Comment by lee-dohm** [comment]
Thanks very much for your feedback!

I've had numerous talks with someone in the Atom community about making Atom work better with traditional accessibility tools like voice navigation and we all agree that making Atom more accessible is important. On the other hand, we simply don't have the resources or expertise to invest in adding voice support directly into Atom itself. We would rather leave that to experts in that field and simply make Atom work better with the existing tools.

Thanks for the suggestion :+1:
