### ISSUE TITLE
Autocomplete fail in php

### ISSUE THREAD

**Issue by sanada01** [atom/atom#16614]
Atom version: 1.23.3 x64

Sample:
![atombug](https://user-images.githubusercontent.com/28780118/35271792-7cd27d3e-0033-11e8-9249-54a12d1ad3bb.gif)

**Comment by rsese** [comment]
Thanks again for reporting @sanada01!  Can you re-open in https://github.com/atom/autocomplete-plus?  It might be an issue with a more specific autocomplete package but that's a better place for this issue for now.  Also please fill out the issue template, the details in the template are really helpful for us when investigating issues.
