### ISSUE TITLE
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by J-SPECTRE** [atom/atom#16612]
```javascript
PS D:\Projects_BK\BKWeiXinClient> npm run dev

> bk_seal@1.0.0 dev D:\Projects_BK\BKWeiXinClient
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
                                                                                     46% building modules 304/304 modules 0  75% advanced
Build completed in 25.754s

ERROR  Failed to compile with 27 errors                                                                                         13:58:59
 
error  in ./src/pages/seal/apply-list.vue

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/we
bpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (D:\Projects_BK\BKWeiXinClient\node_modules\extract-text-webpack-plugin\dist\loader.js:57:11)

 @ ./src/pages/seal/apply-list.vue 2:2-614
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
```
---
i am the new user for atom,i want to run application with vue and webpack,when i use cl `run dev server` with `platformio-ide-terminal`,and the error occured above,but when i use other ide like webstorm  or cmd  on windows 10 ,app can run normally and auto-open-browser,any idea for this error?

**Comment by rsese** [comment]
Thanks for reaching out!

This issue tracker is for Atom specific problems - if you're having issues with platformio-ide-terminal, you can ask for help on the official message board (https://discuss.atom.io) or the [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
