### ISSUE TITLE
Bracket Matcher Highlight color

### ISSUE THREAD

**Issue by svipben** [atom/atom#16626]
Currently color for **Highlight Matching Line Number** in `bracket-matcher` is too dark and I can't even see line number through it... So my suggestion is to change it or reduce darkness from current color to math `Atom One Dark` theme.

![image](https://user-images.githubusercontent.com/10441177/35334490-434734fe-011b-11e8-981e-2d0fe8d8dfd9.png)

Atom: 1.23.3
OS: macOS

**Comment by 50Wliu** [comment]
Please reopen on whatever syntax theme you are using.

Keep in mind that in the future your issues risk being closed without further resolution if you do not fill in the issue template.

**Comment by svipben** [comment]
@50Wliu opened it here: https://github.com/atom/one-dark-ui

Thanks!
