### ISSUE TITLE
Handlebars/Mustache coloring

### ISSUE THREAD

**Issue by svipben** [atom/atom#16624]
**Comments:**
As you can see in the picture below HTML is gray while commented with italic font style, but handlebars/mustache is not gray and not with italic font style. Expected behavior is to have everything gray and with italic font style because it's commented.

![image](https://user-images.githubusercontent.com/10441177/35330683-0897e0c8-010d-11e8-9c88-fc93d4d223aa.png)

**Bracket matcher:**
As you can see my cursor is on {{table}}, but it shows bracket matcher and underline on h4 tag which is wrong...

![image](https://user-images.githubusercontent.com/10441177/35332246-076ed5fc-0113-11e8-9acb-8e9ca11a77f3.png)

Atom: 1.23.3
OS: macOS

**Comment by 50Wliu** [comment]
For issue 1: please reopen on [atom/language-mustache](https://github.com/atom/language-mustache).
For issue 2: please reopen on [atom/bracket-matcher](https://github.com/atom/bracket-matcher).

Keep in mind that in the future your issues risk being closed without further resolution if you do not fill in the issue template.

**Comment by svipben** [comment]
@50Wliu thanks, done!
