### ISSUE TITLE
Hide files/folder from treeview

### ISSUE THREAD

**Issue by mittalyashu** [atom/atom#16632]
Adding the option to hide files/folder from treeview would be great.
 https://www.useloom.com/share/493f761048ad43f48af3a3404c7083fc

**Comment by rsese** [comment]
Thanks for the suggestion - you can do this already with the `Settings > Core > Ignored Names` setting and if you have `Settings > Packages > tree-view > Hide Ignored Names` enabled. 

For tree view feature requests, please use the https://github.com/atom/tree-view repository and check to see if there's already and existing request for the feature you're interested in.

And please use as much of the issue template as possible when opening issues - sharing what the current behavior is now and how the feature request would improve things is helpful when looking at feature requests.

**Comment by mittalyashu** [comment]
Using this `Settings > Core > Ignored Names`, it will hide those files/folder from all the directory, we open in the atom, what if we want different tree view configuration for a different project.

As in video you can see that it create a directory name `.vscode` and has a file name `settings.json`. It can give the power to customize each project with different settings.

@rsese, I did check, there is no issue, similar to mine in the tree-view repo.

**Comment by rsese** [comment]
> Using this Settings > Core > Ignored Names, it will hide those files/folder from all the directory, we open in the atom, what if we want different tree view configuration for a different project.

Ahhh gotcha - I think that would fall under this existing request for per project config settings:

https://github.com/atom/atom/issues/5168

**Comment by mittalyashu** [comment]
Yup. You can say that.
