### ISSUE TITLE
onDidChangeFiles rename showing same value for oldPath and path

### ISSUE THREAD

**Issue by mighty-pirate** [atom/atom#16647]
I am creating a package and have a callback function bound to `atom.project.onDidChangeFiles` using:
```js
atom.project.onDidChangeFiles(watcherEventHandler);
```

Below is the callback:
```js
const watcherEventHandler = events => {
    for (const event of events) {
      if (event.action === 'created' && typeof addedEvent === 'function') {
        addedEvent(event.path);
      } else if (event.action === 'modified' && typeof updatedEvent === 'function') {
        updatedEvent(event.path);
      } else if (event.action === 'deleted' && typeof removedEvent === 'function') {
        removedEvent(event.path);
      } else if (event.action === 'renamed' && typeof renamedEvent === 'function') {
        console.log(event);
        renamedEvent(event.oldPath, event.path);
      }
    }
  };
```
When I cut and paste a file using the tree-view package, use the atom rename functionality or just move the file using my terminal, to a subdirectory, the output to the console will show the `oldPath` for the `path` property meaning I have no way of knowing programmatically where the file has been moved to.

**Comment by rsese** [comment]
Thanks for the report!

> the output to the console will show the oldPath for the path property meaning I have no way of knowing programmatically where the file has been moved to.

Can you share the exact output?  Is it the same as described in https://github.com/atom/atom/issues/16413?

**Comment by mighty-pirate** [comment]
No, when the code I posted reaches the `console.log` call, when the action for the current event is 'renamed'.

**Comment by iolsen** [comment]
We're working on improving our file-system watching and notification systems. You can track progress in #16124.

**Comment by mighty-pirate** [comment]
Ok great. Thanks.
