### ISSUE TITLE
Font rendering issue

### ISSUE THREAD

**Issue by ShalokShalom** [atom/atom#16644]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In Atom and VSCode renders Electron the fonts with colorful dots:

![screenshot_20180129_133748](https://user-images.githubusercontent.com/6344099/35510825-fa0e3f16-04f9-11e8-94fe-29c027208add.png)

It happens in all the cases which get rendered directly to the DOM.

All content which is rendered as the extensions page looks fine.
It happens with two different drivers, one from Intel and with the KMS.

It is already confirmed, as you can [see here](https://github.com/electron/electron/issues/10895#issuecomment-340544166).

### Steps to Reproduce

1. Start Atom
2. Fill in text

**Expected behavior:** 

Rendering happens correctly

**Actual behavior:** 

Dots get rendered, where they should not.

**Reproduces how often:** 

Always

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
KaOS: rolling

### Additional Information

Here is the issue in Electron: https://github.com/electron/electron/issues/10895
And here in VSCode: https://github.com/Microsoft/vscode/issues/35169

Thanks a lot

**Comment by Ben3eeE** [comment]
Are you using freetype 2.8.1? /cc: https://github.com/atom/atom/issues/15737

**Comment by 50Wliu** [comment]
This should be fixed in Atom 1.25.0 when it is released.  You can use https://github.com/atom/atom/issues/15737#issuecomment-355936149 as a workaround for the time being.
