### ISSUE TITLE
weird composing in editor

### ISSUE THREAD

**Issue by catscarlet** [atom/atom#16641]
### Prerequisites

I didn't try to reproduced the problem in Safe Mode.

* [] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Please see the picture below.

### Steps to Reproduce

Actually I don't know how to reproduce this problem. I just get this problem but I can't get the trigger.

While editing, my composing comes into this:

![snap057](https://user-images.githubusercontent.com/10594035/35491019-e7dc9eac-04de-11e8-80fb-b814d9465f5f.png)

This problem can be recovered by no reason, or not. I don't why and how it happens. The best way to get recovered is to reopen the file. The file isn't damaged if I save when the problem happens

### Versions

Windows 7 x64

Installed by using the atom-windows-x64.zip

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3(x64)
python 3.6.3
git 2.15.1.windows.2
visual studio

And I believe this problem is in 1.23.x. I don't know exactly because I just update from a very old version (a version of 2016?).

### Additional Information

```
D:\Atom_x64\resources\app\apm\bin>apm list
Built-in Atom Packages (92)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.8
├── one-light-ui@1.10.8
├── one-dark-syntax@1.8.0
├── one-light-syntax@1.8.0
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.8
├── archive-view@0.64.1
├── autocomplete-atom-api@0.10.5
├── autocomplete-css@0.17.4
├── autocomplete-html@0.8.3
├── autocomplete-plus@2.40.0
├── autocomplete-snippets@1.11.2
├── autoflow@0.29.0
├── autosave@0.24.6
├── background-tips@0.27.1
├── bookmarks@0.44.4
├── bracket-matcher@0.88.0
├── command-palette@0.42.0
├── dalek@0.2.1
├── deprecation-cop@0.56.9
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.7
├── exception-reporting@0.42.0
├── find-and-replace@0.215.0
├── fuzzy-finder@1.7.3
├── github@0.8.3
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.8
├── image-view@0.62.4
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.1
├── line-ending-selector@0.7.4
├── link@0.31.3
├── markdown-preview@0.159.18
├── metrics@1.2.6
├── notifications@0.69.2
├── open-on-github@1.3.1
├── package-generator@1.1.1
├── settings-view@0.253.1-0
├── snippets@1.1.9
├── spell-check@0.72.5
├── status-bar@1.8.14
├── styleguide@0.49.8
├── symbols-view@0.118.1
├── tabs@0.109.1
├── timecop@0.36.0
├── tree-view@0.221.3
├── update-package-dependencies@0.12.0
├── welcome@0.36.6
├── whitespace@0.37.5
├── wrap-guide@0.40.2
├── language-c@0.58.1
├── language-clojure@0.22.4
├── language-coffee-script@0.49.3
├── language-csharp@0.14.3
├── language-css@0.42.7
├── language-gfm@0.90.2
├── language-git@0.19.1
├── language-go@0.44.3
├── language-html@0.48.5
├── language-hyperlink@0.16.3
├── language-java@0.27.6
├── language-javascript@0.127.6
├── language-json@0.19.1
├── language-less@0.33.0
├── language-make@0.22.3
├── language-mustache@0.14.4
├── language-objective-c@0.15.1
├── language-perl@0.38.1
├── language-php@0.42.2
├── language-property-list@0.9.1
├── language-python@0.45.5
├── language-ruby@0.71.4
├── language-ruby-on-rails@0.25.2
├── language-sass@0.61.1
├── language-shellscript@0.25.4
├── language-source@0.9.0
├── language-sql@0.25.8
├── language-text@0.7.3
├── language-todo@0.29.3
├── language-toml@0.18.1
├── language-typescript@0.2.2
├── language-xml@0.35.2
└── language-yaml@0.31.1

Community Packages (20) C:\Users\xusqd\.atom\pac
├── atom-beautify@0.30.9
├── atom-html-preview@0.2.5
├── busy-signal@1.4.3
├── color-picker@2.2.5
├── emmet@2.4.3 (disabled)
├── intentions@1.1.5
├── jscs-fixer@1.3.0
├── language-vue@0.23.1
├── linter@2.2.0
├── linter-csslint@2.0.0 (disabled)
├── linter-eslint@8.4.0 (disabled)
├── linter-gcc@0.7.1
├── linter-htmlhint@1.4.0
├── linter-jscs@4.1.3
├── linter-jsonlint@1.3.0
├── linter-php@1.5.1
├── linter-stylelint@4.2.0
├── linter-ui-default@1.6.10
├── linter-xmllint@1.4.3 (disabled)
└── Remote-FTP@1.3.4
```

**Comment by rsese** [comment]
Thanks for the report!  Since there are no steps to reproduce in this case and because https://github.com/atom/atom/issues/16289 exists and looks fairly similar (though one comment mentions re-opening the file doesn't fix things up), I'll go ahead and tentatively close as a duplicate for now.   If you end up with steps to reproduce however, please let us know.
