### ISSUE TITLE
editor:toggle-line-comments changes indentation from tabs to spaces on empty lines

### ISSUE THREAD

**Issue by Gkupce** [atom/atom#16650]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When toggling comments for indented empty lines tabs are converted to spaces.
![toggle comment](https://user-images.githubusercontent.com/6500411/35530893-269fe1b4-0514-11e8-91cf-a22b427be354.gif)

This bug seems to affect C like comments `//`, when setting the file to html, this behavior was not experienced

### Steps to Reproduce

1. Set the file to a language with C like comments
2. Have an empty line indented with hard tabs
3. use the editor:toggle-line-comments function
4. tabs are converted to spaces

**Expected behavior:**

Indented lines should keep the original type of indentation character.

**Actual behavior:**

Currently tabs are being converted to spaces, indentation es preserved as far as I've seen, but the character used does not.

**Reproduces how often:**

This seems to happen every time.

### Versions

`atom --version`
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

`apm --version`
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python
git 2.14.1.windows.1
visual studio 2013

### Additional Information

I have hard tabs set for indentation.

**Comment by 50Wliu** [comment]
This is fixed in Atom 1.24, currently in beta.  Thanks for reporting!
