### ISSUE TITLE
Github Error “fatal: Unable to find remote helper for ‘https’”

### ISSUE THREAD

**Issue by JacksonAudio** [atom/atom#16655]
Every time I try and FETCH or PULL from GitHub I get the following error:

" fatal: Unable to find remote helper for ‘https’ "

If it helps I only started getting this error after updating the OS to HIGH SIERRA 10.13.2
Atom as well as PlatformIO are all current.
<img width="507" alt="screen shot 2018-01-30 at 3 31 02 pm" src="https://user-images.githubusercontent.com/31942528/35597654-38ceb744-05e5-11e8-8221-4465c3258409.png">

Anyone know how to resolve this?

**Comment by rsese** [comment]
Thanks for the report - it looks like you're running into this issue:

https://github.com/atom/github/issues/1243

It's still being investigated but you can subscribe there for updates - Git from the command line should still work and I'm guessing if you use SSH as well, switching to the SSH remote URL might work too.

**Comment by JacksonAudio** [comment]
Pasting this into Terminal.app and hitting ENTER solved the problem for me:
"brew install git"

**Comment by Chocolat2** [comment]
still not working for me.
Windows 10 1703 v15063.936
atom v 1.24.0
![capture](https://user-images.githubusercontent.com/33324447/36723371-56261b76-1bb0-11e8-8a00-0ffc82043515.PNG)

**Comment by nbasinge** [comment]
![image](https://user-images.githubusercontent.com/19607999/36979024-30bef1f2-2054-11e8-871d-7793925994bb.png)

Now an issue for me after upgrading to High Sierra on macbook pro 15 2017 on Friday...

atom 1.24.0

**Comment by warlock57** [comment]
git push --force handler master
fatal: Unable to find remote helper for 'https'

**Comment by borysl** [comment]
I have this problem when I try to use it in npm scripts

**Comment by thiagodasal** [comment]
putting the git directory into the environment variables on windows10 solved it for me

**Comment by ddresch** [comment]
@nbasinge did you find a way to fix it for your setup?

**Comment by coreybeaumont** [comment]
Got this after updating to OSX 10.14 (18A391) (Mojave). These are the steps I took to fix it.

1. Open xcode and you should get prompted to update some xcode stuffs.
2. In xcode goto Preferences >  Locations > Command Line Tools > pick one (not 100% sure if this was necessary)
3. In terminal run `brew install git`
4. Restart Atom
5. Push from Atom. You may be prompted to store your git creds in osx keychain.

Along the way before I tried updating xcode I got the below error from Brew. Updating xcode fixed this.

```
~ » brew install git  
Updating Homebrew...
==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing; `git config --local --replace-all homebrew.analyticsmessage true` exited with 1.
==> Installing dependencies for git: gettext, pcre2
==> Installing git dependency: gettext
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing; `git config --local --replace-all homebrew.private true` exited with 1.
```

**Comment by jumbalaya09** [comment]
I followed @coreybeaumont 's instructions. 

I didn't get any updates when opening Xcode, but I didn't have anything selected under Command Line tools.  

Selecting the only option I had there solved the issue.

**Comment by nickbas** [comment]
@ddresch I think I am all good now. Thanks!

**Comment by Bl4Cc4t** [comment]
restarting Atom fixed this for me :)

**Comment by pete0959** [comment]
I have restarted the mac - reloaded atom - still the same issue

**Comment by Humungus-Fungus** [comment]
I fixed this by doing the following (on elementary OS) :
running 'brew install git' on terminal
restarting atom
redownloading my repo after deleting it off my computer
restarting atom
