### ISSUE TITLE
How to add Ubuntu repository when Atom was already installed with dpkg

### ISSUE THREAD

**Issue by knzudgt** [atom/atom#16652]
I am on a Ubuntu 14.04 LTS machine, currently running Atom 1.23.1 
I noticed that now Atom has a repository for Ubuntu, while before the only way to install and update Atom was with `dpkg`.

I already installed Atom years ago with `dpkg` and performed various updates with the same `dpkg` command, according to the old instructions. I was looking for the latest release, when I realised there are now new instructions for Linux. So I would like to add Atom repository in order to automate the update processes. Am I required to uninstall Atom before adding the repository?

Alternatively, what am I expected to do to get the last stable release? 
I could not find instructions for updates

**Comment by bhack** [comment]
See https://github.com/atom/atom/issues/16498

**Comment by 50Wliu** [comment]
To be safe, I would uninstall your current version of Atom first.  Please note that all your current settings and packages will be preserved.  Then you can follow the instructions at https://flight-manual.atom.io/getting-started/sections/installing-atom/#installing-atom-on-linux to add the repository.
