### ISSUE TITLE
Deletion indicators should go after line continuations

### ISSUE THREAD

**Issue by stuartpb** [atom/atom#16656]
### Description

"Deleted line" indicators in Atom are placed after the line number: if the lines are wrapped, these should go over the last line *that the line of text has been wrapped to*, instead of being placed after the *first* line (where the number ends).

![image](https://user-images.githubusercontent.com/572196/35601108-3147c6f4-05e6-11e8-883b-c2654534f395.png)

### Steps to Reproduce

1. Toggle Soft Wrap on (via "Toggle Soft Wrap" under the "View" menu).
2. Open a file with a long line followed by a deleted line (ie. in Git).
3. Narrow the window so that the long line preceding the deletion is wrapped to multiple lines.

**Expected behavior:** The deletion marker should be placed in the space between the end of the preceding line's content and the next line.

**Actual behavior:** The deletion marker is placed in the middle of the continued line, at the bottom of the first row of characters and before the rest of the continuation.

### Versions

1.23.3

**Comment by lee-dohm** [comment]
This issue was moved to atom/git-diff#148
