### ISSUE TITLE
Freezing in superstring find_all_sync

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#16651]
I've encountered long pauses a few times in the last couple days. This latest one never recovered. I took a sample and it appears to be something going on in `find_all_sync` within Superstring.

[Sample of Atom Helper.txt](https://github.com/atom/atom/files/1675358/Sample.of.Atom.Helper.txt)

/cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
Hmm I thought I just fixed an infinite loop in this code path in https://github.com/atom/superstring/pull/51. Let me know if you’re on the latest master. Maybe I missed something.

**Comment by nathansobo** [comment]
Cool, I hadn't rebuilt that recently but just wanted to report this just in case. It's probably the issue you fixed already.
