### ISSUE TITLE
Debian package missing dependencies

### ISSUE THREAD

**Issue by olafdietsche** [atom/atom#16659]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I downloaded the Debian package from atom.io and installed the package inside a Docker container with Ubuntu 16.04.
Prior to `dpkg -i atom-amd64.deb`, I installed the dependencies via `apt-get`.
When I tried running Atom, it failed with an error message about missing libX11-xcb.so.1.

The full list of missing packages is:

- libx11-xcb1
- libxss1
- libasound2
- libxkbfile1

Since I started with a minimal Ubuntu, there might be more missing dependencies.

The full working Dockerfile:

    FROM local/ubuntu-minbase:xenial
    
    ARG DEBIAN_FRONTEND=noninteractive
    ARG install_recommends=--no-install-recommends
    ARG packages="\
    git \
    gconf2 \
    gconf-service \
    libgtk2.0-0 \
    libnotify4 \
    libxtst6 \
    libnss3 \
    python \
    gvfs-bin \
    xdg-utils \
    "
    ARG missing_deps="\
    libx11-xcb1 \
    libxss1 \
    libasound2 \
    libxkbfile1 \
    "
    
    RUN apt-get update && \
        apt-get install -y ${install_recommends} \
            ${packages} ${missing_deps} && \
        rm -rf /var/lib/apt/lists/*
    
    COPY atom_1.23.3_amd64.deb /tmp/
    RUN dpkg -i /tmp/atom_1.23.3_amd64.deb
    RUN rm -f /tmp/atom_1.23.3_amd64.deb

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** I expect the atom-amd64.deb package to list all dependencies.

**Actual behavior:** At least four packages are missing:

- libx11-xcb1
- libxss1
- libasound2
- libxkbfile1

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

$ atom --version
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.12
git 2.7.4

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Arcanemagus** [comment]
Should be fixed on `master` now by https://github.com/atom/atom/pull/16812. 😉
