### ISSUE TITLE
Difference of comportement between atom.workspace.open and atom.workspace.toggle.

### ISSUE THREAD

**Issue by pelallemant** [atom/atom#16666]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There is a difference of comportement between atom.workspace.open and atom.workspace.toggle that I can't explain when reading the documentation.

I wrote a package with a view. In the "toggle" method i wrote initially:

```
toggle() {
    atom.workspace.toggle('atom://my-package');
}
```

When I have a left workspace and a right workspace, the package view can be present in only ONE of the workspaces. Even if I click on an editor of the right worspace when the view is opened in the left workspace, if I use the command of the package the view closes in the worspace it was present. 

When I change the code to:

```
toggle() {
    atom.workspace.open('atom://my-package');
}
```

Then I expect the same behaviour than toggle except that the view will be focused instead of being closed. If you have the package view opened in the left workspace, if you focus the right workspace and trigger the "toggle" method, then a 2nd package view opens ... instead of focusing the existing one.

**Expected behavior:** [What you expect to happen]

Workspace.Open should focus the instance of the package view.

**Actual behavior:** [What actually happens]

Workspace.Open opens a 2nd instance of the package view if another workspace is selected.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

The plugin http://flight-manual.atom.io/hacking-atom/sections/package-active-editor-info/ is the one on which I found that bug.

**Comment by lee-dohm** [comment]
Please include exact steps to reproduce the problem. Atom only has one "workspace", there's no such thing as "left workspace" and "right workspace", so I'm not sure what it is you're saying is going wrong.

**Comment by lee-dohm** [comment]
Talked it over on Slack. "workspace" &rarr; "pane". Explained the `searchAllPanes: true` option for `atom.workspace.open`. This is the expected behavior.
