### ISSUE TITLE
Auto Indenting on Paste is Wrong... Still.

### ISSUE THREAD

**Issue by pickeloe5** [atom/atom#16678]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Auto indenting on paste still doesn't work. Even with both autoIndentOnPaste and autoIndent both disabled, pasting a line continues to indent itself.

I know issues have been opened like this in the past, but they're all closed and for previous versions. I tried finding a package to solve this to no avail, and the settings don't seem to fix this.

### Steps to Reproduce

![indenting wrong](https://user-images.githubusercontent.com/14076162/35769676-31611a16-08c3-11e8-8835-9f863d62f50a.gif)

1. Write one line
2. Write a second line indented one past the first line
3. Copy this second line including it's newline
4. Paste at the end of the second line

**Expected behavior:** The third line maintains the second line's indentation level.

**Actual behavior:** The third line indents one level past the second line's.

**Reproduces how often:** 100%

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python
git 2.13.3.windows.1
visual studio

### Additional Information

This issue persists through safe mode and a moved .atom directory.

**Comment by madikarizma** [comment]
No software should ever assume you did not intend to paste something exactly how you copied it.

**Comment by rsese** [comment]
Thanks for the report - I found this issue that's still open and sounds pretty similar to what you're describing:

https://github.com/atom/atom/issues/5473

I'll ask the team to take a look at that issue again but as mentioned in https://github.com/atom/atom/issues/5473#issuecomment-340245952 there's a new command to paste without reformatting that you can use (on Windows it's bound to <kbd>ctrl-shitf-v</kbd>.

**Comment by pickeloe5** [comment]
Thanks, I found that issue before I made this one. I stopped reading the comments after it was closed though. That solution works, thanks.
