### ISSUE TITLE
[Question] EACCESS When using sudo to run build scripts, Atom can't create files in the folder

### ISSUE THREAD

**Issue by lsbyerley** [atom/atom#16670]
### Description

I have to use `sudo` to run build scripts such as `npx create-nuxt-app <my-project>` (https://github.com/nuxt-community/create-nuxt-app). When adding the project folder into Atom, I can't create any files inside of this folder because it was created by "root". I get the EACCESS: Permission Denied. Since I have to use sudo to build the project, is there anyway to get around this?

Aside from running atom as root everytime I open it?

**Comment by rsese** [comment]
I don't think so unfortunately, see Lee's comment here for more context:

https://github.com/atom/atom/issues/10566#issuecomment-281449503

The referenced feature request (https://github.com/atom/atom/issues/4115) might help though so you can subscribe there for updates if you'd like.

As a side note, as mentioned in the issue template the official message board (https://discuss.atom.io/) is the best place to ask questions in addition to the Atom Slack (http://atom-slack.herokuapp.com/).

**Comment by skylize** [comment]
You need to take ownership of the folder and its subfolders.

[Google Search: "linux recursively take ownership of folder"](https://www.google.com/search?q=linux+recursively+take+ownership+of+folder&oq=linux+recursively+take+ownership+of+folder)

**Comment by rsese** [comment]
heh sorry - yes if the process you described is a one time thing where you end up with files and directories owned by root, then you can change the ownership as mentioned above and you're done.  If you have to run the build scripts multiple times, then you'll need to change ownership of the files and directories each time which is better than running as root each time.

**Comment by lsbyerley** [comment]
Yeah, i actually just copy/pasted the folder contents into another folder. That changed the owner to my user and I was able to create/delete with atom. Thanks
