### ISSUE TITLE
NODE_MODULE_VERSION mismatch

### ISSUE THREAD

**Issue by SheldonLaw** [atom/atom#16671]
### Description

When I try to run Atom in dev mode with the code in my local code repository, an error alert pop up like this:
![image](https://user-images.githubusercontent.com/16605105/35713740-fa0a4c64-0803-11e8-91ef-11b6082b55b4.png)

I follow the guide line - [hacking-on-atom-core](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#platform-mac) but failed.

### Steps to Reproduce

1. [git clone git@github.com/SheldonLaw/atom.git]
2. [cd atom]
3. [script/bootstrap]
4. [export ATOM_DEV_RESOURCE_PATH='~/atom']
5. [atom --dev]

### Versions
```
#atom -v
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
#node -v
v7.4.0
#npm -v
4.0.5
```

Any help will be appreciated.

**Comment by Ben3eeE** [comment]
I'm guessing this error is because of the electron upgrade on master and when installing the modules the script used the master version of apm but you are running stable Atom in dev mode. I think running `apm rebuild` in ``

**Comment by Ben3eeE** [comment]
Or you could also build the dev version of Atom and run that in dev mode instead of stable that should also work.

**Comment by SheldonLaw** [comment]
@Ben3eeE Thank you for saving my time! `apm rebuild` work for me.
