### ISSUE TITLE
What is it called when you intentionally program something to be editable, like Atom is?

### ISSUE THREAD

**Issue by keeganjk** [atom/atom#16677]
What is it called when you intentionally program something to be editable, like Atom is?

**Comment by 50Wliu** [comment]
:wave: Thanks for reaching out!

This question is probably better suited for [Discuss](https://discuss.atom.io), where you'll get better answers than on this issue tracker.  You can also [join the Atom Slack team](http://atom-slack.herokuapp.com/) and ask your question there.

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
