### ISSUE TITLE
Scrolling through documents is extremely slow

### ISSUE THREAD

**Issue by michaloslav** [atom/atom#16686]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Whenever I open a file, the scrolling is EXTREMELY slow. Like I have to move the mouse wheel 20 times to move the document by a single line. The weird thing is scrolling works just fine when I'm in the settings, it's just in files. I tried reinstalling the whole thing and nothing. All my settings are on default, including scroll sensitivity which remains at 40 (I did try turning it up to 200 and it did start scrolling a bit faster but it was still unacceptably slow). This never happens in any other software.
I've also noticed a general slowness when trying out Atom, there's often a lag between pressing a key and the letter appearing on the screen. I tried turning off all the programs I could and running essentially just Atom and the Windows Task Manager. CPU was usually below 10%, occasionally peaking at around 40-50%, RAM was stable at roughly 30%. Maybe it could somehow be connected to the scrolling issue, I don't know

(I'm not sure what to write into the other fields, the issue is there all the time so there aren't really any steps to reproduce it other than to just turn the editor on.)

### Versions
Atom 1.23.3
apm 1.18.12

Windows 7, 64bit

**Comment by Ben3eeE** [comment]
Thanks for the report!

> Whenever I open a file, the scrolling is EXTREMELY slow. Like I have to move the mouse wheel 20 times to move the document by a single line.

Do you have vertical scroll speed set to `One screen at a time` in the Windows control panel mouse settings? If so then this was fixed in https://github.com/atom/atom/pull/16114 which is currently scheduled to be released in Atom 1.24 (Currently in beta).

![image](https://user-images.githubusercontent.com/1058982/35808903-af9ee0d2-0a87-11e8-9249-e1b5ce2b6473.png)

**Comment by michaloslav** [comment]
Thank you!! You were right, I did have that in my settings, I downloaded the beta and everything seems to work just fine now. If the problem somehow comes back even with the beta version, I'll update this issue thread
