### ISSUE TITLE
Atom-Beautify returns "spawn UNKNOWN" when trying to beautify python script

### ISSUE THREAD

**Issue by nwschurink** [atom/atom#16689]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Whenever I try to run atom beautify I receive a spawn UNKNOWN error message. I have only tried to perform the beautifier on python scripts so far.

### Steps to Reproduce

1. Open a random python script into atom
2. Ctrl + shift + p -> type in atom beautify: beautify editor
3. Get spawn UNKNOWN error message

**Expected behavior:** The python file should be run through the autopep8 module

**Actual behavior:**  An error message occurs and the python file has not been parsed

**Reproduces how often:** It happens 100% of the time

### Versions
atom --version

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.14
git 2.14.3.windows.1
visual studio 2015

I am running a 64 bit Enterprise edition of Windows 7.

### Additional Information
I have set the Atom Beautify autopep8 path to the executable script i.e.
D:\Anaconda3\Scripts\autopep8-script.py

I have set the Atom Beautify isort path to the executable script i.e.
D:\Anaconda3\Scripts\isort-script.py

In the Atom Beautify settings I have set the default beautifier to autopep8.
In the Atom Beautify settings I have set the default formatter to autopep8.

Calling >where autopep8 shows me:
C:\Python27\Scripts\autopep8.exe
C:\Users\n.schurink\AppData\Local\Programs\Python\Python36\Scripts\autopep8.exe

Indicating autopep is on my system path.

I have run the Atom Beautify Help Debug Editor and posted a gist on GitHub which can be accessed through:

https://gist.github.com/nwschurink/bd394228ad65e6a0c3fe4462fec2c70d

I have found a similar question [Issue 1979](https://github.com/Glavin001/atom-beautify/issues/1979) but without any solution. The same error message is also mentioned in [Issue 5000](https://github.com/atom/atom/issues/5000) but in a different context. Also there no solution is provided.

**Comment by 50Wliu** [comment]
Please report this to the [atom-beautify](https://atom.io/packagesg/atom-beautify) package instead.
