### ISSUE TITLE
Atom does not store settings in ".atom" when using it from PortableApps platform 

### ISSUE THREAD

**Issue by reypm** [atom/atom#16681]
### Description

I am trying to run Atom as a portable so settings and everything stay on the same folder but I couldn't make it to work. For PortableApps I am using [PortableApps Platform](https://portableapps.com/). I have followed the steps on [this docs](http://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode) however I don't know if those are the latest or are outdated.

### Steps to Reproduce

1. Download PortableApps Platform from the link above and install it wherever you want to (in my case I did it under F: but you can try with a USB flash drive)
2. Download the Atom ZIP file from https://github.com/atom/atom/releases I am using latest version 1.24.0-beta3
3. Go to your PortableApps folder (`f:\PortableApps\PortableApps\`) and unzip the downloaded file.
4. I have renamed the folder to `AtomPortable` but you can leave it as it's that doesn't matter.
5. Create the folder `.atom` under `f:\PortableApps\PortableApps\AtomPortable`
6. Using the PortableApps executable file - `f:\PortableApps\Start.exe` and open it
7. Run Atom from there and change any settings or install a new package and/or theme
8. Check the `.atom` folder, it will be empty (at least in my case)
9. All the settings went to `%userprofile%/.atom`

**Expected behavior:** everything related to Atom is stored under the `.atom` folder at the PortableApps path

**Actual behavior:** All the settings went to `%userprofile%/.atom`

**Reproduces how often:** I have tried only once cause I just downloaded Atom to use it recently

### Versions:

 - 1.24.0-beta3

**Comment by lee-dohm** [comment]
This is the expected behavior unless you set the `ATOM_HOME` environment variable to point to where you want your `.atom` folder to be.

**Comment by reypm** [comment]
@lee-dohm you should update docs. Read again [here](http://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode) what do you understand? (or I did understand at least).

- Alternatively you can set the ATOM_HOME environment variable to point wherever you want (you can write a .sh or .cmd script to temporarily set it and launch it from that)

That is not mandatory and as per your answer here, it is mandatory so it is a little confusing when you read that but you said something different here. Anyway thanks for the info I will try and see if that works
