### ISSUE TITLE
Text Editor keeps freezing after updating Atom-IDE

### ISSUE THREAD

**Issue by martezconner** [atom/atom#16683]
Atom ver: 1.23.3
Atom-IDE-ui ver: 0.8.1

The crash seems to have started after updating atom-ide-ui package. Before updating everything worked fine. After updating the application freezes after 20-30 seconds and I have to force close

**Comment by the-j0k3r** [comment]
You said it yourself, the issue is related to the IDE package not Atom.

**Comment by 50Wliu** [comment]
Yes, please report this to [atom-ide-ui](https://atom.io/packages/atom-ide-ui) instead.
