### ISSUE TITLE
Atom Crashes on Start after initial install

### ISSUE THREAD

**Issue by chasinglucid** [atom/atom#16680]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After install, when attempting to start Atom, application crashes. I receive a message from Windows stating:  "The editor has crashed. Please report this issue to https://github.com/atom/atom".

Windows then gives three options: "Close Window", "Reload", or "Keep It Open".

All three do as described, however, "Keep It Open" just keeps the window open and doesn't allow anything to actually work.

"Reload" will restart the application sometimes without the same error, but once you are working with the application and try to save, another crash occurs.

### Steps to Reproduce

1. Click on Atom.exe icon.
2. View error.
3. Close.
4. repeat 1-2.
5. Reload.
6. View error.

**Expected behavior:** 

Expect application to open and be operational.

**Actual behavior:** 

Application crashes on start.

**Reproduces how often:** 

Every time.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

System Info:
Windows 10 Home
Processor: AMD A9-9430 RADEON R5, 5 COMPTE CORES 2C+3G
RAM: 8.00GB
System type: 64-bit Operating System

Internet connection: Ethernet
\[37e13f9a-ed87-4e51-8343-646c37bdda48.txt](https://github.com/atom/atom/files/1692094/37e13f9a-ed87-4e51-8343-646c37bdda48.txt)
[operation_log.txt](https://github.com/atom/atom/files/1692095/operation_log.txt)

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by chasinglucid** [comment]
Yes, it's the newest version and I've never had any other version of Atom on my PC.

Yes, I tried it in safe mode, but it was the same behavior.

I tried to attached the related files in my initial post.

**Comment by rsese** [comment]
> "Reload" will restart the application sometimes without the same error, but once you are working with the application and try to save, another crash occurs.

Are you working on a particular project or file at this point or it doesn't matter what file you try to save (e.g. what about a tiny test file), Atom will crash on save?

Also, if you leave the console tab open while working (http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools), do you notice any errors?

**Comment by chasinglucid** [comment]
No particular project. I just tried a basic "Hello world" in HTML to test it. It really doesn't matter what file is opened or being saved.

I just tried it again and this is the first time I got anything other than the generic windows errors. See attached.

![image](https://user-images.githubusercontent.com/35589621/35941991-6f2fcf58-0c11-11e8-8ab9-eab29b3c3e91.png)

**Comment by rsese** [comment]
> I just tried it again and this is the first time I got anything other than the generic windows errors. See attached.

Oh huh, so now it doesn't crash it just shows those errors?  Which issue is the stack trace linking to?

**Comment by chasinglucid** [comment]
No, it still crashed first and I reloaded it.

All I did was try to save the file and those are the errors I got.

**Comment by chasinglucid** [comment]
OK so, I installed Atom on my laptop (which has the same version of Windows 10) and it came up looking entirely different and no crash.

![capture](https://user-images.githubusercontent.com/35589621/36004279-2af26c68-0cef-11e8-9cc7-29204bd7643d.JPG)

So, I uninstalled the problem Atom on the PC. I even went in and deleted the registry entries and all files. I then installed it again using the same exe file as above. The first time I launched it, this is what I got:

![atom broken 1](https://user-images.githubusercontent.com/35589621/36004346-8757d786-0cef-11e8-9dbb-771e8d2530c5.PNG)

I chose "Close Window" and relaunched it from the desktop shortcut and got the Telemetry tab (but not the welcome tab or the dark theme). When I added a Project folder, I got 4 or 5 of those errors which say:

`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/path-watcher.js:184:48
    at Array.map (native)
    at handler (~/AppData/Local/atom/app-1.23.3/resources/app/src/path-watcher.js:177:36)
```

### Commands

```
     -1:27.1.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```

```


However, it does add the Project Folder. When you try to remove the folder or do anything else, I get 1 to 8 of these errors:

`[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:468:7)
    at ~/AppData/Local/atom/app-1.23.3/resources/app/src/path-watcher.js:184:48
    at Array.map (native)
    at handler (~/AppData/Local/atom/app-1.23.3/resources/app/src/path-watcher.js:177:36)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
> OK so, I installed Atom on my laptop (which has the same version of Windows 10) and it came up looking entirely different and no crash.

Thanks for trying that :+1:

> I chose "Close Window" and relaunched it from the desktop shortcut and got the Telemetry tab (but not the welcome tab or the dark theme). When I added a Project folder, I got 4 or 5 of those errors which say:

Can you share the issue link that you get from those errors?

And the files you're working on, are they just on your local drive, no remote/network drive or anything like that?  Not sure what's unique about the machine that's having trouble....

One last thing to confirm, when you went through the debugging steps, did you also try clearing saved state?

http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16680#issuecomment-364549943. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
