### ISSUE TITLE
Question please help

### ISSUE THREAD

**Issue by margrettt** [atom/atom#16696]
I want one know how to retrieve or get texts or messages from another phone but it's showing symbols and Asian letter or pics .sometimes mix numbers and letters. If someone can help I greatly appreciate it. I think my wife is cheating and I'm loosing my mind. Ty. Blessings to all

**Comment by Aerijo** [comment]
If you want help with how to do something in Atom, [ask on the forums](https://discuss.atom.io/).

**Comment by lee-dohm** [comment]
This doesn't have anything to do with Atom. Atom is a [programmer's text editor](https://atom.io) and therefore doesn't have anything to do with text messages or phones. I hope things work out for you.
