### ISSUE TITLE
Error: Command failed: pandoc --from=markdown-raw_tex tex_math_single_backslash --to=html --filte...

### ISSUE THREAD

**Issue by psweers** [atom/atom#16697]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Error: Command failed: pandoc --from=markdown-raw_tex tex_math_single_backslash --to=html --filter=pandoc-citeproc --bibliography=C:\Users\psweers\Dropbox\Markdown\bibliography.bib --csl=C:\Users\psweers\Dropbox\Markdown\apa.csl --filter=pandoc-eqnos --filter=pandoc-fignos --filter=pandoc-tablenos --smart
pandoc: Error running filter pandoc-eqnos:
Could not find executable 'pandoc-eqnos'.

```
At Command failed: pandoc --from=markdown-raw_tex tex_math_single_backslash --to=html --filter=pandoc-citeproc --bibliography=C:\Users\psweers\Dropbox\Markdown\bibliography.bib --csl=C:\Users\psweers\Dropbox\Markdown\apa.csl --filter=pandoc-eqnos --filter=pandoc-fignos --filter=pandoc-tablenos --smart
pandoc: Error running filter pandoc-eqnos:
Could not find executable 'pandoc-eqnos'.


Error: Command failed: pandoc --from=markdown-raw_tex tex_math_single_backslash --to=html --filter=pandoc-citeproc --bibliography=C:\Users\psweers\Dropbox\Markdown\bibliography.bib --csl=C:\Users\psweers\Dropbox\Markdown\apa.csl --filter=pandoc-eqnos --filter=pandoc-fignos --filter=pandoc-tablenos --smart
pandoc: Error running filter pandoc-eqnos:
Could not find executable 'pandoc-eqnos'.

    at ChildProcess.exithandler (child_process.js:223:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -6:24.3.0 core:backspace (input.hidden-input)
     -6:22 core:confirm (input.hidden-input)
     -5:18.4.0 core:cut (input.hidden-input)
     -5:16.5.0 core:delete (input.hidden-input)
     -5:12 markdown-preview-plus:toggle (input.hidden-input)
     -4:48.2.0 core:paste (input.hidden-input)
     -4:28.8.0 find-and-replace:show (div.package-detail.panels-item)
     -4:04.2.0 markdown-preview-plus:toggle (input.hidden-input)
     -2:55.8.0 key-binding-resolver:toggle (input.hidden-input)
     -2:55.1.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-gpg 0.6.0 
atom-pgp 0.5.0 
autoclose-html 0.23.0 
highlight-selected 0.13.1 
language-markdown 0.25.1 
language-r 0.4.2 
markdown-pdf 2.1.0 
markdown-preview-plus 2.5.1 
markdown-preview-plus-opener 0.2.0 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
package-cop 0.2.10 
print-code 0.7.1 
Sublime-Style-Column-Selection 1.7.4 
tablr 1.8.3 
wordcount 2.10.4 
Zen 0.18.0 
zotero-citations 1.0.0 
```

**Comment by 50Wliu** [comment]
Thank you for reaching out!  This seems to be a bug with one of the markdown packages you are using.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
