### ISSUE TITLE
1.24.0-beta3 Some grammars are not applied at start to opened editors

### ISSUE THREAD

**Issue by paradoxxxzero** [atom/atom#16691]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On a fresh Atom 1.24.0-beta3, grammars like the ones in [language-babel](https://github.com/gandm/language-babel) do not get applied at start on already opened buffers.

### Steps to Reproduce

1. Remove all atom configs.
2. Open atom and install language-babel
3. Open or create a `.jsx` file
4. Restart atom (ctrl + shift + f5 or close and open)

**Expected behavior:** The opened jsx file has the jsx grammar applied

**Actual behavior:** The opened jsx file has the `NullGrammar` (Plain Text)

**Reproduces how often:** 100%

### Versions

Atom    : 1.24.0-beta3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Archlinux

### Additional Information

NB: When you close the file and open it again it works as expected.
It works with some other grammars.
Downstream issue: https://github.com/gandm/language-babel/issues/476

**Comment by rsese** [comment]
Thanks for the report - on macOS 10.12.6 I had 1.23.0-beta1 installed but couldn't reproduce but after updating to 1.24.0-beta3 I saw the behavior you described.

**Comment by paradoxxxzero** [comment]
This seems to be resolved in atom 1.25.0-beta0

**Comment by 50Wliu** [comment]
I think this was actually an issue with language-babel.
