### ISSUE TITLE
Roadmaps, goals and where to find them?

### ISSUE THREAD

**Issue by wldcordeiro** [atom/atom#16693]
I've been curious about following Atom development but between the blog and the repo I can't seem to find anything that indicates what is being slated for next release or anything of that nature. How can I find this stuff out? The Atom project doesn't seem to use milestones, projects or labels to tag things so it's just frustratingly opaque as someone who is both interested in the editor's advancement in general and getting involved in contributing.

**Comment by 50Wliu** [comment]
We're working on improving transparency.  You should see a public update of some kind later this week!

We do use organization-wide projects, but I think those are always private with no way to set them as public.

Milestones don't work, given the modular nature of Atom and cross-repository development.  In the meantime, you can get a rough idea of what the team is working on by creating a search query that searches for all PRs by Atom maintainers.  Something like `org:atom is:pr author:nathansobo author:maxbrunsfeld author:jasonrudolph author:daviwil author:kuychaco author:iolsen author:smashwilson author:lee-dohm author:rsese author:ungb author:simurai author:as-cii` (hopefully I didn't forget anyone 🙂).  Note that you would need to enter this query in the https://github.com search bar, _not_ a search bar that has `This repository` next to it.

**Comment by 50Wliu** [comment]
The first focus milestone PR is now available at #16714.  Going forward, you should be able to check `docs/focus` to see what the Atom team is engaged with.
