### ISSUE TITLE
Alias/Shortcut support

### ISSUE THREAD

**Issue by muuvmuuv** [atom/atom#16709]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I use aliases (mac) in my projects and want to open them within the editor, but as they are binary links I only get the binary code, not the linked file. So that would be a great new feature – open shortcut/alias files within the editor/treeview!

### Steps to Reproduce

1. Create an alias by right clicking a file
2. Move the alias somewhere in your project
3. Open the project
4. Open the file via atom treeview

**Expected behavior:** Linked file opens

**Actual behavior:** Binary content appears

**Reproduces how often:** always

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.14.3

**Comment by lee-dohm** [comment]
Thanks for reaching out.

Atom supports symlinks right now. If you switch to using those instead of aliases, things should work the way it seems you intend.

I hope that helps.
