### ISSUE TITLE
Issue in automatic braces

### ISSUE THREAD

**Issue by lavishsaluja** [atom/atom#16706]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
 
![capture](https://user-images.githubusercontent.com/25464742/36042765-ea97ff2a-0df2-11e8-95b6-bac26ebd3a74.PNG)
See line 42 in the above picture.
while I type a ( in front of print, inspite of having a string in front of print, closing brace also gets typed, whereas it should not be the case like most of the text editors. if there is a string in front of print statement then only 1 i.e. opening brace should get typed 

[Description of the issue]

### Steps to Reproduce

1. [First Step] just write a print statement and a string in front of it ( as in pyhton 2.x)
2. [Second Step] try including a brace realising that you had python 3.x installed
3. [and so on...] 

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]
It does not happen in case of a file name or anything except string.
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report! Can you re-open this in https://github.com/atom/bracket-matcher if there's no existing issue already so we have it in the right place?  If you can also be more explicit about the steps to reproduce (e.g. where is the cursor when you type a <kbd>(</kbd> in front of the `print`?) and expected/actual behavior (e.g. show the exact text that you expect vs. what you actually get) , that would be helpful too.
