### ISSUE TITLE
atom.packages.loadPackage name resolution

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#16703]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It seems the package name created from `atom.packages.loadPackage` has changed in Atom v1.24.0-beta3 from Atom v1.23.2.

### Steps to Reproduce

1. Clone [atom-minimap-linter](https://github.com/AtomLinter/atom-minimap-linter)
2. Checkout v2.1.3
3. Run the package specs

**Expected behavior:**

The `name` of a package loaded through `atom.packages.loadPackage` to match the `name` field of its `package.json` (`linter-minimaptest` in this case).

**Actual behavior:**

The `name` of a package loaded through `atom.packages.loadPackage` matches the folder name it was stored in (`fake-linter` in this case).

This is currently breaking the specs, but as `atom.packages.loadPackage` isn't a public function, this may just be something I need to work around there 😉.

**Reproduces how often:**

100% of the time.

### Versions

```
Atom    : 1.24.0-beta3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0-beta3
python 3.6.4
git 2.16.1.windows.3
visual studio 2015
```
and
```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.14
git 2.16.1.windows.4
visual studio 2015
```

### Additional Information

`atom.packages.loadPackage` is **NOT PUBLIC**, so this may be an expected change... but in case this is a regression I wanted to get this filed.

This _might_ be related to https://github.com/atom/atom/issues/15953.

**Comment by Arcanemagus** [comment]
The behavior here changed between v1.23.3 and v1.24.0-beta3, since #15953 was filed against 1.23.0-dev-02b133844, that helps narrow down the timeline of when this (might have) changed.

**Comment by lee-dohm** [comment]
@maxbrunsfeld Was this an intentional change?

**Comment by maxbrunsfeld** [comment]
@Arcanemagus I don't recall making changes to that method recently. Can you tell what commit or PR broke it? Even though it's private, we might be open to merging a PR that restores the old behavior if we can get some insight into why it changed.

**Comment by Arcanemagus** [comment]
@maxbrunsfeld It looks like this was introduced as part of https://github.com/atom/atom/pull/16199.

Previously the package name was determined like this:
https://github.com/atom/atom/blob/fdf0478a775f76e19b44d2f6383dcb7d3e4c6f83/src/package.coffee#L44

Note how `metadata.name` takes precedence if it exists.

Currently though it is determined like this:
https://github.com/atom/atom/blob/ce83c02ba208858e92ab63e2ef5284aa0c1218d8/src/package.js#L45-L48

This changed the order to prefer `params.name` before `metadata.name`. (`params.name` is determined from the package directory earlier.)

Since the name in the package metadata _should_ take precedence I can send in a PR if you think that should be changed back. If not, I've already worked around it in the spec that was depending on this behavior so I'm fine either way 😉.

**Comment by maxbrunsfeld** [comment]
Oh great job tracking that down! A PR fixing it would be much appreciated!
