### ISSUE TITLE
Tree-view shows deleted files/folders

### ISSUE THREAD

**Issue by zeten30** [atom/atom#16708]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Deleted files or directories do not disappear from tree-view on deletion (moving to thrash). Collapse & expand directory view is needed to refresh directory contents. 

This affects the bundled version tree-view@0.221.3.
I'm able to workaround this issue with manual install of tree-view@0.222.0

### Steps to Reproduce (only the bundled version)

1. open atom in a project directory (tested in normal and save mode)
2. create a file
3. delete a file or directory (from tree-view)
4. file or directory created still present
5. collapse & expand parent directory in tree-view
6 file or directory disappears 

**Expected behavior:** [What you expect to happen]
Deleted items should disappear immediately on deletion 

**Actual behavior:** [What actually happens]
 Collapse & expand parent directory is needed to refresh directory contents

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time. 100%

### Versions
atom --version
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.14
git 2.14.3

apm list | grep tree-view
├── tree-view@0.221.3

cat /etc/fedora-release 
Fedora release 27 (Twenty Seven)

DE: Gnome 3.26 on Wayland

**Comment by lee-dohm** [comment]
This is currently the expected behavior on Linux systems when you delete a file outside of Atom because of the file watcher infrastructure we're using. We have a new file watcher system that is in the works that _should_ improve things. Keep an eye out for it :+1:

**Comment by zeten30** [comment]
Hi,

all the file operations were executed from the tree-view/atom itself. No action in file manager or terminal. 

I think that tree-view package needs to be updated in atom bundle package.

Bundled version @0.221.3 is having issues. Manually installed @0.222.0 is working fine.

--
Milan

**Comment by zeten30** [comment]
Omit the previous workaround.
Adjusting sysctl variable  fs.inotify.max_user_watches from default 8192 to higher value resolved the issues.
