### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by swanny18** [atom/atom#16707]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
The editor crashes immediately and does not complete loading. The window displays 3 options; close window, reload and keep it open. Keep it open turns the screen from black to white and nothing further happens.

### Steps to Reproduce

1. Double click to open editor
2. Receive editor has crashed error message
3. Close window
4. Double click to open editor
5. Receive editor has crashed error message
6. Click Reload
7. Screen flashes white and then returns to black with error message
8. Click Keep It Open
9. Screen turns white and nothing further happens

**Expected behavior:** [What you expect to happen]
Atom to load, projects displayed, connect to FTP.
**Actual behavior:** [What actually happens]
Atom does not load
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
Atom: 1.23.3
Electron: 1.6.15
Chrome: 56.0.2924.87
Node: 7.4.0

Ubuntu 16.04 LTS

2nd Version of Atom, updated yesterday from 1.7.?

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information
also tried uninstalling and reinstalling but problem persists

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!

> 2nd Version of Atom, updated yesterday from 1.7.?

Oh wow that's a pretty big version jump - when you reinstalled, did you use the .deb from https://atom.io?

Also, I see you checked off the Prerequisites box but just to double check, was there any difference in behavior when you ran in safe mode?  And did you also try clearing saved state (http://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state)?

**Comment by swanny18** [comment]
Hi Robert, 

Thanks for getting back to me so quickly. 

Apologies, I thought i'd put in the original issue about safe mode. Atom will load in safe mode, but if you click configure it will crash and the message pops up again. As the packages don't load in safe mode, and Atom doesn't load in normal mode, it was difficult to faithfully recreate the step of disabling the packages one by one. 

The .deb was from atom.io, yes. 

Clearing the saved state did not fix the issue, it continued to crash while loading. I have just checked again and it continues to crash. 

Kind regards 

Zara 

Sales and Marketing 
Heales Medical 


27 Bridge Street 
Hitchin 
Hertfordshire 
SG5 2DF 

t. 0844 8421755 ext1002 
f. 0844 8421752 
www.heales.com 

The contents of this email are confidential and intended for the person(s) or organisations(s) named above. Unauthorised use, retention, distribution, copying or disclosure is strictly prohibited. Please let the sender know immediately and delete this email if it has been sent to you in error. 

Heales Medical is registered in England & Wales no. 3779908, Registered Office: 146 Sundon Park Road, Luton, Bedfordshire, LU3 3AH.

**Comment by rsese** [comment]
> Atom will load in safe mode, but if you click configure it will crash and the message pops up again. As the packages don't load in safe mode, and Atom doesn't load in normal mode, it was difficult to faithfully recreate the step of disabling the packages one by one.

Ahhh ok so it sounds like this is an issue with a community package since Atom works in safe mode, you're just having trouble pinpointing which package is causing the issue?

Also, when you say "click configure", where are you clicking this?

**Comment by rsese** [comment]
Thanks again for your issue!

We haven't received a response to our question in this comment https://github.com/atom/atom/issues/16707#issuecomment-365080647. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
