### ISSUE TITLE
Crash due to virtual memory leak when repeatedly running vagrant machines

### ISSUE THREAD

**Issue by lentzi90** [atom/atom#16711]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom crashes due to a virtual memory leak when repeatedly starting and stopping [vagrant][1] machines in an open project.

### Steps to Reproduce

1. Initialize a project with a vagrant file: `vagrant init ubuntu/xenial64`
2. Open the project folder in atom and change the vagrant file to use the virtualbox provider by uncommenting like so:
```
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end
```
3. Run `vagrant up; vagrant halt` repeatedly until atom crashes. Also, note that the virtual memory used by atom increases each time (easily reaching over 100 GB). I would suggest using a script in order to easily reproduce this, e.g:
```
COUNTER=0
while [  $COUNTER -lt 200 ]; do
    echo The counter is $COUNTER
    let COUNTER=COUNTER+1
    vagrant up
    vagrant halt
done
```

**Expected behavior:** The virtual memory usage should not increase infinitely and atom should not crash just because I start and stop vagrant machines in the project folder.

**Actual behavior:** Atom uses up to hundreds of GB's of virtual memory and finally crashes.

**Reproduces how often:** Every time after a repeating `vagrant up; vagrant halt` a number of times.

### Versions

Output from `atom --version`:
```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
Output from `apm --version`:
```
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.14
git 2.14.3
```
OS: Fedora 27
Kernel: 4.14.16-300.fc27.x86_64

### Additional Information

I tried doing an allocation timeline but it did not seem to show virtual memory.

Why would I start and stop my vagrant machines so many times? Because I sometimes do more complicated vagrant files and need to test them while working. Over the course of a day this can lead to a few hundred starts and stops, and then atom crashes unless I keep an eye on the virtual memory usage and restarts the editor every now and then.

[1]: https://www.vagrantup.com/

**Comment by lee-dohm** [comment]
I'm not understanding what the issue is here. Are you running Atom inside the vagrant VM? Or are you running the vagrant VM from inside Atom? If the former, 1024MB isn't exactly enough for Atom to run alongside the OS. If the latter, Atom isn't designed to be a task runner. If neither, then I'm not sure how Atom is affected on any modern operating system with process isolation.

**Comment by lentzi90** [comment]
Oh, I see the confusion, sorry about that.

I'm using atom to edit vagrant files (among other things) on my bare metal system. However, when I start the VMs repeatedly, this causes atom to crash. Atom really has nothing to do with the VMs or vagrant, I just happen to use it to edit the vagrant files. I'm executing all vagrant commands in a normal terminal not inside atom.

The uncommented lines about RAM and virtualbox is just because that particular image uses the virtulabox provider instead of libvirt (which is the default).

I *think* the problem is that atom is doing some kind of indexing on the files related to the VMs and never "releases" the files even though vagrant/virtualbox removes old files.

**Comment by lee-dohm** [comment]
If a bunch of files are rapidly appearing and disappearing in the directory Atom is monitoring without them being ignored, then yes, Atom will attempt to index them. This is because the common case is that the files in the directory that Atom is watching are source files that stick around for a long time. We haven't optimized Atom for extremely low lifetime files.

Perhaps you could mount the VM in a directory that is ignored by Atom? Or outside the directory that you have open in Atom?

If I'm understanding the situation correctly, I'm not sure that this is something that we'll dig too deeply into.

**Comment by sam00121** [comment]
SteamDatabase/steamdb.info

**Comment by lentzi90** [comment]
Okay I see.
I did not know about `.atomignore`, just googled it. This seems like a good use for that file so I'll try to add `.vagrant` to it and see what happens.
In any case, this is not that big of a problem for me, I can just make sure to restart atom every now and then.

**Comment by lentzi90** [comment]
Ignoring/hiding the `.vagrant` folder does not help unfortunately.

I'm not sure what files atom even finds. The whole project folder I'm using to reproduce this contains a total of 42 files, totaling 120 kB. That is the vagrant file and the script for looping `vagrant up; vagrant halt` along with a log file from the VM. Except for that, there is only the ignore files and the `.git` and `.vagrant` folders.

The VM images are stored in a folder outside of the project.

Anyway, I guess this issue can be closed if this is not something that will be addressed.

**Comment by lee-dohm** [comment]
Sorry we couldn't help more.
