### ISSUE TITLE
Open folder dialog is not scaled correctly with mixed scaling for high DPI monitor

### ISSUE THREAD

**Issue by hmaarrfk** [atom/atom#16717]
### Description

OS: Windows 10 64 bit.
3 monitors: Main monitor is a 4k set to 250% scaling. Seconday monitors set to 1080p (100% scaling).
On the secondary monitors, Atom looks fine, but the open folder dialog looks like it is scaled for the high DPI monitor

### Steps to Reproduce

1. Connect all 3 monitors. 
2. Open atom
3. Move it to the 1080p monitor (100% scaling).
4. Try to open a folder using Ctrl+Shift+o

**Expected behavior:**
The open folder dialog should be scaled for the given monitor.

**Actual behavior:**
The open folder dialog seems to be scaled for the primary monitor.

![image](https://user-images.githubusercontent.com/90008/36110216-bcaff3ca-0fd6-11e8-99a1-5aa540f249b9.png)

**Reproduces how often:**
100%

### Versions

Windows 10, 64 bit.
```
C:\Users\mark>atom --version

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
C:\Users\mark>apm --version
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 3.6.4
git 2.16.1.windows.4
visual studio
```

**Comment by Aerijo** [comment]
Windows is notorious for bad scaling between different monitors.

https://support.microsoft.com/en-au/help/3025083/windows-scaling-issues-for-high-dpi-devices

I don’t think this will be an easy fix, but then again, I don’t know anything about how it might be resolved.

**Comment by 50Wliu** [comment]
All native dialogs are handled by Electron/Chromium.  If this issue also reproduces using Chrome/Chromium, you should file an issue on their bugtracker; if not, you should file an issue on [electron/electron](https://github.com/electron/electron).

**Comment by hmaarrfk** [comment]
You are right. this is bug in chrome too.
