### ISSUE TITLE
[FEATURE] Highlighting destructed variables ?

### ISSUE THREAD

**Issue by justduy** [atom/atom#16716]
### Description
Highlighting destructed variables to make the code clearer. So that the connection between data and state is clearer. For example: 

```
render() {
    const { data } = this.state;

    return (
      <ResponsiveContainer>
        <AreaChart
          data={data}
        >
      </ ResponsiveContainer>
     );
}
```

### Versions
1.23.3

**Comment by Aerijo** [comment]
@justduy please raise this issue on the grammar package `language-javascript` instead. Syntax highlighting is a two part process, where the `language-<name>` package adds scopes to all the characters, and the theme applies colours to the scopes. 

In your case, you are asking for the grammar package to add a scope to destructed variables, which can then be used to apply a colour to.

**Comment by justduy** [comment]
@Aerijo Ahh okay, my bad!
