### ISSUE TITLE
"Updates available" indicator doesn't update when "Check for Updates" selected

### ISSUE THREAD

**Issue by sguergachi** [atom/atom#16728]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In the case where atom finds itself in an inconsistent state as indicated by this screenshot:
![image](https://user-images.githubusercontent.com/615386/36173345-be7f3b10-10d6-11e8-8ca7-7a9a7ebcf193.png)

Selecting the "Check for Updates" button should restore consistency; in this instance hide the 1 update indicator in the bottom right.

### Steps to Reproduce

1. Bring atom into inconsistent state described in screenshot above
2. Click "Check for Updates" button in the Updates screen

**Expected behavior:** [What you expect to happen]
Update the "updates available indicator" in bottom right. 

**Actual behavior:** [What actually happens]
Doesn't update the "updates available indicator" in bottom right
**Reproduces how often:** [What percentage of the time does it reproduce?]
Happens every time I've somehow managed to get atom into this state.

### Versions
1.23.3
Windows 10 64bit latest.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by daviwil** [comment]
Hey @sguergachi, thanks for the report! We just deployed a fix that should resolve this issue (see #16727), please try restarting Atom and check for updates again.

**Comment by rsese** [comment]
> Bring atom into inconsistent state described in screenshot above

Do you happen to remember anything about how you got into that state?

**Comment by sguergachi** [comment]
I think it was from uninstalling and reinstalling a package that had a problem updating to the latest version. Not sure this is how to reproduce the inconsistent state but here's what I remember doing before this happened: I opened Atom, had updates available, the update failed, I uninstalled it, then searched for it to reinstalled it again.

**Comment by 50Wliu** [comment]
Thanks for the report @sguergachi.  Can you please reopen this on the [atom/settings-view](https://github.com/atom/settings-view) repository?
