### ISSUE TITLE
Auto updater is broken

### ISSUE THREAD

**Issue by danqing** [atom/atom#16727]
There seems to be some issue with the auto-updater.

![screen shot 2018-02-13 at 11 59 42 am](https://user-images.githubusercontent.com/5134133/36170854-82a0c9e0-10b5-11e8-9ecf-93138130881a.png)

macOS 10.13.3
Atom 1.24b3 (trying to update)

**Comment by daviwil** [comment]
Thanks for the report!  We are currently looking into this issue, will report back once we uncover the cause.

/cc @lee-dohm @jasonrudolph

**Comment by jasonrudolph** [comment]
Thank you for reporting this issue. :bow: Auto-updates should be working now. Sorry for the trouble. 🤦‍♂️ 

If you continue to experience this issue, please let us know.
