### ISSUE TITLE
Editor sometimes scrambles editor content by rendering different lines over each other

### ISSUE THREAD

**Issue by doberkofler** [atom/atom#16722]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Sometimes Atom scrambles the editor content by rendering different lines over each other and even scrolling or minimizing/maximizing the editor does not correctly refresh the content.
The problem happens every couple of hours and is completely in-deterministic.
It can only be resolved by closing the editor and starting it again.

![2018-02-13 07_33_37-convert js d__mydev_ljs_app_trunk_periscope_build atom](https://user-images.githubusercontent.com/1009585/36136807-8446f8f0-1092-11e8-92ba-cf893fc315a4.png)

### Steps to Reproduce

Cannot be reproduced

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

Typically once every couple of hours.

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.3
git 2.12.2.windows.2
visual studio 2013

Running on Windows 7 x64

**Comment by rsese** [comment]
Thanks for the report @doberkofler - you mentioned that this happens "Typically once every couple of hours", do you happen to remember anything about what you were doing when this happens?  Also, what file type is that in your screenshot?

And lastly, do you have soft-wrap enabled and were there cold folds in the file?

x-ref: https://github.com/atom/atom/issues/16289

**Comment by doberkofler** [comment]
@rsese I understand that I offered very little information to track down the problem but because it happens quite often, I nevertheless decided to open a sr.
Unfortunately I have not been able to discover any pattern on when the problem starts.
Soft-wrap is disabled and there are no folds in the file.

**Comment by rsese** [comment]
No problem and thanks for all the details :+1:

https://github.com/atom/atom/issues/16289 was just closed with a fix so we can see if you can still reproduce when the fix makes it into an upcoming release.
