### ISSUE TITLE
Many ways to write to readonly editors

### ISSUE THREAD

**Issue by deprint** [atom/atom#16736]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The new `setReadOnly` command (introduced in `v1.24.0`) only prevents typing "normal" characters.
Commands and other packages can still change the editor, including:

- `core:backspace`
- `core:delete`
- `editor:newline`
- `editor:indent`
- `core:paste`
- `core:cut`

Same thing for packages and any other editor command, really.

**Expected behavior:** A read-only editor does not change at all.

**Actual behavior:** A read-only editor can be edited.

**Reproduces how often:** Always.

### Versions

```
Debian 9

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

Atom    : 1.25.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by iolsen** [comment]
/cc @kuychaco 

Putting this on prioritized for investigation, which may or may not yield a fix.

**Comment by smashwilson** [comment]
I'm taking a few steps to address this:

* I've retargeted the core commands that modify the buffer, like `core:backspace`, to `:not([readonly])` selectors. That solves the immediate problem of being able to hit <kbd>delete</kbd> or <kbd>ctrl</kbd>-<kbd>x</kbd> on read-only editors and change them.
* I'm also doing a sweep through the `TextEditor` and `Selection` methods that modify the buffer and adding a `{bypassReadOnly}` option parameter. Calling those methods on read-only TextEditors without explicitly setting `{bypassReadOnly: true}` results in an exception. This will guard against user packages being able to accidentally register modification commands on `atom-text-editor`, but will still allow packages to programmatically modify read-only editors as they need to.
