### ISSUE TITLE
Atom 1.24.0 Cursor Doesn't Remain on Screen When Collapsing Code

### ISSUE THREAD

**Issue by JosephTLyons** [atom/atom#16730]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom is not auto-scrolling to keep the cursor on the screen when collapsing code.

### Steps to Reproduce

1. Place cursor at end of collapsed code and scrolling your screen all the way up so the cursor is on the last line 
2. Uncollapse the code
3. Nothing happens

**Comment by rsese** [comment]
Thanks for the report - just to clarify, can you share a GIF/screencast of the behavior you're describing?

**Comment by JosephTLyons** [comment]
Here's a short video.  Maybe I misunderstood the feature.  I was under the impression that one of the new features of 1.24.0 was that the editor would scroll to keep the cursor in sight when collapsing or expanding code.

https://www.dropbox.com/s/dydbkznyq76hd0l/Atom%20Bug.mov?dl=0

**Comment by rsese** [comment]
Sorry for the delay @JosephTLyons - just to followup, I found that the blog post isn't quite right after talking it through with another maintainer (I'm assuming that's where you read about the feature?):

http://blog.atom.io/2018/02/13/atom-1-24.html

Where it says:

> Folding or unfolding large blocks of code could easily move your cursor off screen. Now, Atom will [automatically scroll the editor](https://github.com/atom/atom/pull/16092) to keep your cursors visible after the folding operation is complete.

The referenced PR was superseded by https://github.com/atom/atom/pull/16186 and so relatedly, the described functionality isn't as described in the blog post.  As mentioned in https://github.com/atom/atom/pull/16186, the previous behavior was a bit too aggressive and the new behavior is that the editor will autoscroll when you use keyboard commands to unfold (e.g. from the command palette or from a keybinding).

So in your video, if you use `Editor: Unfold Current Row`, you'll scroll to your cursor.

Hope that clears things up but if you have questions let me know :v:
