### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by 2sagarraut2** [atom/atom#16735]
### Description

As soon as I start atom live server it says editor is crashed
![image](https://user-images.githubusercontent.com/36417693/36205147-bd9c50c4-11b3-11e8-9300-1a57931111cd.png)

**Actual behavior:** Editor crashes
Please help me in starting live server

**Comment by Aerijo** [comment]
First thing to do would be opening the issue in the right repository. This is an issue with atom live server, so open it there. If the maintainers decide the bug is with Atom, they can then raise the issue on core.

**Comment by Aerijo** [comment]
@2sagarraut2  [Here](https://github.com/jas-chen/atom-live-server/issues?utf8=%E2%9C%93&q=is%3Aissue) is the place it should be raised.
