### ISSUE TITLE
Atom panes push left when switching files or panes

### ISSUE THREAD

**Issue by mirandashort** [atom/atom#16739]
### Description

When jumping around files or switching between panes, the editor appears to push the whole UI to the left, removing the tree from view as well as text in the left pane. 

![image](https://user-images.githubusercontent.com/22545566/36213447-c1ee9d1a-1174-11e8-9060-7ea56e415f12.png)

This does not occur every time, but has been happening more frequently since I first encountered the issue back in January. I've tried restarting and updating/removing packages but can't seem to fix itself. I also had to wipe my computer and start the editor from scratch, and it has been happening before and after wiping my HD. 

### Steps to Reproduce

1. Split panes (left or right, doesn't matter)
2. In your tree view, select another file to view
3. Observe the UI behavior

#### alt. steps
1. Split panes
2. Select the pane you are not currently in
3. Observe behavior

**Expected behavior:** 
I should be able to freely switch from pane to pane and/or file to file seamlessly.

**Actual behavior:** 
When trying to open a different file, the UI shifts left, most times making the tree inaccessible. 

**Reproduces how often:** 
About every other attempt to open a file. I can usually correct it by trying toggle the tree view or selecting the pane that was affected, but the screenshot above can only be resolved by restarting atom. 

### Versions

```
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.14.3
```

Currently on High Sierra 10.13.3

**Comment by rsese** [comment]
Thanks for the report - I'm unable to reproduce with both sets of repro steps with Atom 1.24.0 on macOS 10.12.6.  Can you reproduce in safe mode (`atom --safe`)?

**Comment by mirandashort** [comment]
I apologize for such the long response time @rsese - I somehow missed this comment. 

I have tried reproducing in safemode, but to be perfectly honest, the issue is so sporadic that when trying to reproduce, I can't, but when not trying, it inhibits my entire workflow. You'll notice I do have the IDE terminal open in the screencapture below, but the problem started happening before I even installed that package. 

One other thing to note, I recently had to get a new machine altogether and the problem still persists. Is there any additional information I might be able to provide? For a while the problem corrects itself once I click into the terminal or into the try, but it has since stopped doing that. Additionally, the view is pushing further to the left than it ever has before 

![atom_fuxd](https://user-images.githubusercontent.com/22545566/37575432-8a039fe8-2afd-11e8-8577-611e6dc658d3.gif)

**Comment by rsese** [comment]
> I apologize for such the long response time @rsese - I somehow missed this comment.

No problem, thanks for all the details :+1:

> Is there any additional information I might be able to provide?

Confirming if the issue is reproducible in safe mode is helpful for us because that lets us know that the issue is unrelated to a community package, but I know it's hard to verify in cases like this where the error is sporadic.  Relatedly, specific steps to reproduce is also something we need to take a look.

**Comment by goodusermf** [comment]
I see this problem frequently.  The way to get it out of this problem is by restarting the editor but soon it will go back again.  It might be a combination of plugins and the number of files i manage.

**Comment by mirandashort** [comment]
Phew I'm glad someone else has the same problem!! @goodusermf I've actually found that if I either select a new file in my tree (given it's not pushed too far over), or hit return in my IDE terminal, it shifts back. That way I don't have to constantly restart. Sometimes just clicking on another pane helps too

**Comment by goodusermf** [comment]
Yes, @mirandashort, it has been a problem for me for sometime.  I have also upgraded my OS from el Capitan to high sierra.  Not sure if that has also an impact.

**Comment by mirandashort** [comment]
@goodusermf how long ago did you upgrade? I've been on High Sierra for a while now

**Comment by goodusermf** [comment]
The upgrade has been for about 3 months.  I kept hitting this problem so frequently that I was ready to switch not notes sadly.  However, I decided to close all my tabs and I realized that it is cause by having too many tabs open.  So when you have too many tabs open and continue opening or switching tabs the shift happens.  I reduced the tabs open and problem goes away.

**Comment by rsese** [comment]
@goodusermf would you be able to share step-by-step instructions for reproducing?

**Comment by mirandashort** [comment]
@goodusermf that's actually really good information. how often are you using split pane though? i seem to have it with happen a lot when i'm using two panes. I also have contemplated going back to sublime...

**Comment by goodusermf** [comment]
I use split pane all the time.  

How to reproduce the issue:  
I manage in average about 50 files open concurrently.   
1.  Just open about 50 files and notice the shift happens

**Comment by mirandashort** [comment]
I can reproduce with only about 10 open. Basically if you see the tabs cut off, it's enough to cause the problem I'm sure

**Comment by mirandashort** [comment]
Confirming that I'm noticing the issue occur when too many tabs are open. It seems to occur once I have enough tabs to go beyond the width of the screen. Now that I know the approximate threshold, I'm no longer constantly about to throw my computer out the window. I keep my tabs at a manageable count and don't encounter the problem anymore! I will admit, though, I would like to be able to have more than 7 tabs open at once... Since I have tree view and minimap enabled, the real estate for tabs is taken up immensely. 

If we could have this addressed soon I'd really appreciate it as it is a bit frustrating. Once again, steps to reproduce would be to open up a lot of tabs.

**Comment by rsese** [comment]
> Once again, steps to reproduce would be to open up a lot of tabs.

We're unfortunately still unable to reproduce so what would help is exact step by step instructions to reproduce the behavior.  Based on this new bit of information:

> It seems to occur once I have enough tabs to go beyond the width of the screen

This is what I tried with the atom/atom repository:

1. `atom --safe .`
2. Double click the title bar so the Atom window was maximized and spanned the width of my screen
3. Open enough files so there enough tabs to go beyond the width of the screen.  For this step on my computer, I needed to open 21 files.

At this point the tabs spanned the window and there were enough tabs so that a few tabs were hidden but I didn't see any problem.  I then opened another 20 files so I had 41 tabs open and almost half the tabs weren't visible but wasn't able to reproduce with this setup either.  I did a few other things too like toggling the GitHub package and then splitting panes a couple of times.

**Comment by mirandashort** [comment]
Apologies as it was really difficult for me to simplify more the steps to reproduce. I don’t have to do a whole lot for it to happen. My steps are exactly like yours.

I would like to clarify that it can be affected just by window size, not necessarily screen size. It might be worth noting it occurs sometimes _after_ I try to type or click on a pane, but that’s not the behavior every time. 

Can you confirm your operating system that you are attempting to reproduce on as well? Once I get back online I can also look through and list all of my packages

**Comment by rsese** [comment]
> Apologies as it was really difficult for me to simplify more the steps to reproduce. I don’t have to do a whole lot for it to happen. My steps are exactly like yours.

No problem, these issues that are hard to reproduce across computers can be tough to pin down :+1:

> Can you confirm your operating system that you are attempting to reproduce on as well? Once I get back online I can also look through and list all of my packages

I'm on macOS 10.12.6

Also I realized it sounds like you can reproduce more reliably now than before when the issue was first opened?  If that's the case, can you confirm if running in safe mode so all community packages are disabled still reproduces the issue?

**Comment by mirandashort** [comment]
I might have gotten one more piece to the puzzle! I ran in safe mode and was not reproducing, but I did notice that in safe mode, I am able to horizontally scroll the open tabs. When not running safe mode, that ability has been removed. I can still horizontally scroll in tree view whenever the text spans larger than the width of the pane. 

With that said, is there anything you can think of that would disable the tab scroll? I feel like it's no coincidence that my window gets shifted to the left whenever I have too many tabs, and i can't get all the tabs without the scroll.

**Comment by rsese** [comment]
Hmmm that is interesting...my first guess is that it's related to one of your installed packages.  If you don't have a ton of packages, you could disable all packages and then enable them one-by-one until you see the behavior.  

Can you share your installed packages list?

```
apm list --packages --installed
```

**Comment by mirandashort** [comment]
Sure: 

`Community Packages (18) /Users/mirandashort/.atom/packages
├── aligner-ruby@1.7.0
├── atom-beautify@0.32.5
├── atom-formatter-jsbeautify@1.1.2
├── atom-mocha-snippets@0.6.3
├── autocomplete@0.47.0
├── clipboard-plus@0.5.1 (disabled)
├── cssbeautify@1.3.0
├── greppen-grok@0.2.1
├── line-number-color@0.2.0

├── minimap@4.29.8
├── node-debugger@1.10.1
├── platformio-ide-terminal@2.8.3 (disabled)
├── restart-atom@0.2.0
├── rubo-format@0.4.1 (disabled)
├── ruby-block@0.3.6
├── semicol@1.1.1 (disabled)
├── teletype@0.12.2
└── tokamak-terminal@10.0.1`

I'll give toggling the packages a try tonight when I'm a little freer 

@goodusermf can you confirm if you use any of the above packages?
