### ISSUE TITLE
1.25.0-Beta0 GrammarRegistry loadGrammar API changed behaviour.

### ISSUE THREAD

**Issue by gandm** [atom/atom#16733]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The Atom API loadGrammar callback return has changed in 1.25.0-Beta0. It is documented and in prior versions did return up to two fields (err, grammar) using the code [here](https://github.com/atom/atom/blob/894ce56821a2f6d2427aadab88dba8910249ea84/src/grammar-registry.js#L400-L402) and [here](https://github.com/atom/first-mate/blob/master/src/grammar-registry.coffee#L165-L171). The err field could be relied upon to indicate an error. It now it returns a single field either (err) or (grammar) [as shown here](https://github.com/atom/atom/blob/master/src/grammar-registry.js#L428-L434) and that field can't be used to determine success or failure!!

**Comment by maxbrunsfeld** [comment]
Oh wow, that's terrible. Sorry about that. I'll fix that shortly and we'll publish another beta release.

**Comment by gandm** [comment]
@maxbrunsfeld Thanks. Also, great work on tree-sitter, I've been looking forward to it for the past year and keeping an eye on what you've done. At last, no more TextMate grammars!
