### ISSUE TITLE
Uncaught TypeError: Cannot read property 'delete' of undefined

### ISSUE THREAD

**Issue by kevinmanify** [atom/atom#16749]
[Enter steps to reproduce:]

1. Wanted to get rid of weird empty space on right.
2. Followed steps mentioned in this FAQ topic: https://discuss.atom.io/t/where-did-this-empty-space-come-from-how-do-i-get-rid-of-it/30226?source_topic_id=29030
3. And after restarting Atom. Opened one file, that also triggered error. Then tried to close the file and got this issue.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'delete' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1447

TypeError: Cannot read property 'delete' of undefined
    at TextEditorComponent.didDetach (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1447:48)
    at HTMLElement.detachedCallback (/app.asar/src/text-editor-element.js:47:25)
    at HTMLElement.PaneElement.itemRemoved (/app.asar/src/pane-element.js:199:29)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:698:24)
    at Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:775:16)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.9 
atom-mysql-snippets 0.3.1 
atom-shell-commands 1.5.0 
autoclose-html 0.23.0 
autocomplete-php 0.3.7 
break-time 0.3.1 
busy-signal 1.4.3 
css-snippets 1.1.0 
docblockr 0.13.6 
emmet 2.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.6.10 
monokai 0.24.0 
php-cs-fixer 4.1.1 
remote-ftp 2.1.4 
split-diff 1.5.2 
tasks 2.9.1 
teletype 0.6.0 
text-manipulation 0.6.0 
touchbar-utility 3.0.3 
tree-view-git-status 1.4.0 
tree-view-open-files 0.3.0 
wakatime 7.0.4 
```

**Comment by rsese** [comment]
Thanks for the report @kevinmanify - based on the FAQ, you cleared saved state.  Just to confirm, are you continuously getting this error still?  If so, can you reproduce in safe mode (`atom --safe`)?

**Comment by lee-dohm** [comment]
Thanks for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16749#issuecomment-366056424. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by yuanchueh** [comment]
I have this error. Started this morning, and it does happen in safe mode.

Says it is in /opt/atom/resources/app/src/text-editor-component.js:1447

**Comment by yuanchueh** [comment]
I started atom with atom --clear-window-state and it appears to have fixed the issue.
