### ISSUE TITLE
atom --wait doesn't work as git editor on Windows

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#16740]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When attempting to use `atom --wait` as the `git config core.editor` setting as introduced in Atom v1.25.0-beta0 by https://github.com/atom/atom/pull/16497, it seems the functionality attempted in that PR doesn't work under Windows, since the Atom window that the editor was spawn in still needs to fully close for `git` to consider the message as ready.

### Steps to Reproduce

1. Set Atom as your `git` editor
    * Git (all platforms): `git config --global core.editor 'atom --wait'`
    * PowerShell: `$Env:GIT_EDITOR='atom --wait'`
    * CMD: `set GIT_EDITOR='atom --wait'`
2. Make a commit with `git`
3. Close the tab for the file that was opened

**Expected behavior:**

As soon as the tab is closed `git` considers the message done and does the commit.

**Actual behavior:**

`git` waits for the _specific_ window that the message was opened in to close before considering the commit ready.
![2018-02-14_09-34-07](https://user-images.githubusercontent.com/427137/36219525-995e4b3c-116c-11e8-8866-77a4fb8f5c74.gif)

Note: Although not shown in the GIF above, I have tested both the `git` and PowerShell methods described above, as well as using `atom --wait --safe` as the editor command.

**Reproduces how often:**

100% of the time.

### Versions

```
Atom    : 1.25.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-beta0
python 2.7.14
git 2.16.1.windows.4
visual studio 2015
```

OS: Windows 10 x64 Enterprise

**Comment by rsese** [comment]
:+1: I can repro with 1.25.0-beta0 on Windows 10 with Git Bash.

**Comment by maxbrunsfeld** [comment]
Looking into this now. VM time.

**Comment by maxbrunsfeld** [comment]
Ok, I can reproduce in Git Bash too. It's odd because `atom --wait` as expected seems to work by itself.
