### ISSUE TITLE
can't highlight japanese text

### ISSUE THREAD

**Issue by seaweedbeast** [atom/atom#16758]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am having trouble highlighting japanese text in atom.
My encoding is set to UTF-8, which I found to be a potential issue in a previous inquiry, but this didn't seem to resolve my issue.

### Steps to Reproduce

**Expected behavior:** I would like to be able to highlight and select Japanese text.

**Actual behavior:** As you can see, the English text correctly highlights all similar text, but it doesn't in Japanese. Please help! ><

<img width="227" alt="screen shot 2018-02-16 at 10 04 27" src="https://user-images.githubusercontent.com/31488158/36313927-37a3435c-1301-11e8-95f8-80aee5a915e0.png">

<img width="216" alt="screen shot 2018-02-16 at 10 04 35" src="https://user-images.githubusercontent.com/31488158/36313933-3b4f3a7e-1301-11e8-86ad-ee1b154ad109.png">

<img width="224" alt="screen shot 2018-02-16 at 10 04 43" src="https://user-images.githubusercontent.com/31488158/36313944-408acd78-1301-11e8-89ce-eb4aa7bb717b.png">

<img width="222" alt="screen shot 2018-02-16 at 10 04 53" src="https://user-images.githubusercontent.com/31488158/36313952-43c25c4a-1301-11e8-9b91-0c3ad5091708.png">

### Versions

I am running version 1.24.0 on Mac OSX High Sierra

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!  Just to clarify, are you using https://atom.io/packages/highlight-selected?  If so,  you can report this to https://atom.io/packages/highlight-selected.

**Comment by rsese** [comment]
I'll go ahead and close for now because this seems to be an issue with [highlight-selected](https://atom.io/packages/highlight-selected) but if I'm mis-understanding, please let me know and we can re-open.

**Comment by Arcanemagus** [comment]
This is likely a duplicate of https://github.com/richrace/highlight-selected/issues/157.
