### ISSUE TITLE
Unresponsive and white screen after new install

### ISSUE THREAD

**Issue by billwingate** [atom/atom#16759]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After performing a new install of Atom on my laptop, an unresponsive white screen appears. I am not able to open any files, perform any typing, install packages, edit setting, etc.. Below is a Dropbox link to the screen display:

[https://www.dropbox.com/s/a377uo8p0gj2rvj/Screenshot%202018-02-16%2009.24.55.png?dl=0](url)

### Steps to Reproduce

1. Typed "atom --safe" in the command line.
2. Typed "atom --clear-window-state" in the command line.
3. renamed .atom to .atom-backup and opened atom.
4. deleted .atom and squirrel and opened atom.

**Expected behavior:** I expect Atom to run correctly and be able to open files, projects and edit code.

**Actual behavior:** Atom displays a white and unresponsive screen.

**Reproduces how often:** Always.  It has never worked on this machine.

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python
git
visual studio 2010

Windows 10 / 64 bit

### Additional Information

Atom refuses to work on my laptop. I have uninstalled and reinstalled approximately ten times and get the same results every time.

**Comment by rsese** [comment]
Thanks for the report - if you start Atom in the foreground, do you see any error messages?

```
atom --foreground
```

**Comment by billwingate** [comment]
I tried running Atom in the foreground and did not receive any errors.  I received the same results previously mentioned.

**Comment by rsese** [comment]
I remember this older message board post with a similar description (white screen on Windows even after going through all the debugging steps):

https://discuss.atom.io/t/white-screen-on-startup/42544

Does starting Atom with `atom --disable-gpu` make any difference?

**Comment by billwingate** [comment]
That command got it working.  However, accessing atom by double clicking the icon still produces the unresponsive white screen.  Is there a workaround? Or will I need to access Atom via "atom --disable-gpu" every time?

**Comment by billwingate** [comment]
I just updated the driver for my NVIDIA Quadro and Atom is working great! Thanks for your fast response!!!

**Comment by rsese** [comment]
Oh awesome, glad you have things sorted out and thanks for sharing what got things working for you!
