### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by tylerFowler** [atom/atom#16767]
I find that in certain file types I get this exception thrown (Atom Beta). So far I've found it reliably does it in git commit message types (invoked by git-plus) and in Go files, but have not seen it with the same version in JS or Java files. It tends to keep throwing this error over and over as I type.

Worth noting this error was definitely *not* present until the latest Beta update.

**Atom**: 1.25.0-beta0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:527

TypeError: Cannot read property 'replace' of undefined
    at AutocompleteManager.getWordCharacterRegex (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:527:72)
    at AutocompleteManager.getPrefix (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:507:43)
    at AutocompleteManager.findSuggestions (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:260:31)
```

### Commands

```
  2x -0:09.1.0 core:move-down (input.hidden-input)
     -0:07.3.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:06.6.0 core:backspace (input.hidden-input)
     -0:05.8.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -0:04.3.0 core:move-up (input.hidden-input)
```

### Non-Core Packages
Was able to reproduce in safe mode

**Comment by Aerijo** [comment]
This looks like an `autocomplete-plus` issue. Specifically, `additionalWordChars` is returning `undefined` in the following function.

```js
getWordCharacterRegex (scopeDescriptor) {
    const additionalWordChars = getAdditionalWordCharacters(scopeDescriptor)
    let regex = wordCharacterRegexCache.get(additionalWordChars)

    if (!regex) {
      regex = new RegExp(`[${UnicodeLetters}${additionalWordChars.replace(']', '\\]')}]`)
      wordCharacterRegexCache.set(additionalWordChars, regex)
    }
    return regex
  }
```

Please close this issue and open one on the [`autocomplete-plus`](https://github.com/atom/autocomplete-plus/issues) repo.

**Comment by tylerFowler** [comment]
Oops 🤦‍♂️ ! Good call

**Comment by drorata** [comment]
See https://github.com/atom/autocomplete-plus/issues/956
