### ISSUE TITLE
Project path deduplication no longer happens

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#16764]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom is no longer deduplicating project paths when a request to open a path is made, this means that you open multiple windows to the same location instead of focusing the current window.

### Steps to Reproduce

1. Open a folder in Atom
2. Open the same folder again

**Expected behavior:**

Atom simply focuses the instance that is already open.

**Actual behavior:**

Atom v1.25.0-beta0 opens a new window on the same folder, so there are now two windows open to the same folder.

![2018-02-16_12-10-15](https://user-images.githubusercontent.com/427137/36327178-a682d4d4-1312-11e8-9ca1-556d984181a6.gif)

**Reproduces how often:**

100% of the time.

### Versions

OS: Windows 10 x64 Enterprise

```
Atom    : 1.25.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-beta0
python 2.7.14
git 2.16.1.windows.4
visual studio 2015
```

Also tested with the following as a point of comparison:
```
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

I _know_ I've seen discussions related to this in one of the other issues or PR's, but my search-fu is failing me!

**Comment by Arcanemagus** [comment]
Note: Although opening is only shown through a PowerShell in ConEmu, the same behavior happens in native Command Prompt, PowerShell, and simply right clicking in a folder and selecting "Open with Atom" multiple times.

**Comment by rsese** [comment]
> I know I've seen discussions related to this in one of the other issues or PR's, but my search-fu is failing me!

Ugh I feel like I saw this mentioned recently too but don't remember where 🤔 

I can repro on Windows 10 and it looks like Max is taking a look :zap:
