### ISSUE TITLE
Dragging to closed Dock impossible

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#16769]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you attempt to drag an item to a closed Dock panel, the panel goes into a fit of opening/closing and doesn't allow you to place the item in it.

### Steps to Reproduce

1. Open Atom v1.25.0-beta0 in safe mode
2. Have a closed Dock item
2. Attempt to drag something into the closed Dock item

**Expected behavior:**

The Dock panel opens and allows dropping the item in it.

Here is how Atom v1.24.0 behaves:
![2018-02-16_15-13-07](https://user-images.githubusercontent.com/427137/36338643-cb7acd94-1369-11e8-83cc-5c0594845f60.gif)
_Note: You can see that the Dock panel has a little "hiccup" that looks similar to what is now happening, but resolves itself._

**Actual behavior:**

The Dock panel rapidly opens and closes, preventing the item from being dropped there until you can open it (with another item).

![2018-02-16_15-10-35](https://user-images.githubusercontent.com/427137/36338656-00291050-136a-11e8-8e5a-f68d0e2f6487.gif)

**Reproduces how often:**

100% of the time.

### Versions

OS: Windows 10 x64 (Enterprise and Pro tested)

```
Atom    : 1.25.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0-beta0
python 2.7.14
git 2.16.1.windows.4
visual studio 2015
```

Compared against:
```
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
Confirmed.  Here's another GIF with something already in the dock.
![dock-toggle](https://user-images.githubusercontent.com/2766036/36343969-7c40fe2e-13e1-11e8-9f31-be672fe554b9.gif)

**Comment by emrednz07** [comment]
What can we do to prevent this issue ??? What is the difference between these two versions ???

**Comment by Arcanemagus** [comment]
@emrednz07 You can work around it by opening the Dock before you try to drag something into it, as for the cause I would guess it's due to the [Electron v1.7.11 update](https://github.com/atom/atom/pull/16282), but I don't actually know.

Issues like this happen on the betas, that's _why_ there are betas so things like this can be caught before they are sent to `stable`.

**Comment by daviwil** [comment]
There's a good chance it was caused by https://github.com/atom/atom/pull/16546, will investigate.

**Comment by daviwil** [comment]
I believe @as-cii is more familiar with this area since he made a related change in dock behavior recently, I'll leave it to him since he's got Reactor Duty next week :)

**Comment by matthewwithanm** [comment]
yeah, this does look like #16546. i'll fix it.

**Comment by daviwil** [comment]
Thanks a lot @matthewwithanm!
