### ISSUE TITLE
Split panes don't allow horizontal scrolling (sometimes)

### ISSUE THREAD

**Issue by aleclarson** [atom/atom#16761]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have two panes open, and one has text going beyond its pane viewport. But that same pane's text is not wide enough to trigger horizontal scrollbar (in other words, if the second pane wasn't there, the text wouldn't **need** to be scrolled, because it would all be visible). Unfortunately, when the second pane exists to the right, any overflowing text in the first pane cannot be horizontally scrolled into view.

### Steps to Reproduce

1. Create a new file
2. Add text to it, but not enough for horizontal scrolling
3. Open a split pane to the right
4. Resize the second pane until the text in the first pane is clipped
5. Try horizontally scrolling the first pane

**Expected behavior:** The first pane scrolls its clipped text into view

**Actual behavior:** The first pane is not horizontally scrollable

**Reproduces how often:** 100%

### Versions

```
atom 1.22.0
apm 1.18.8
macOS High Sierra 10.13
```

**Comment by rsese** [comment]
> atom 1.22.0

I'm unable to reproduce with your steps but Just to check if this has been fixed already, can you update to the latest release version (currently 1.24.0) and let us know if you can still reproduce?

**Comment by aleclarson** [comment]
@rsese It seems to have been an edge case. Can't reproduce again at the moment (still on 1.22.0). Closing for now.
