### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by drupalista-br** [atom/atom#16779]
I get this when opening a config file from .git folder.
PS: The error is NOT thrown every time I open it. It seems to be random.

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 16.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: Unexpected identifier

```
At /usr/share/atom/resources/app/node_modules/first-mate/lib/scope-selector-parser.js:526

SyntaxError: Unexpected identifier
    at new ScopeSelector (/usr/share/atom/resources/app/node_modules/first-mate/lib/scope-selector.js:8:48)
    at new Grammar (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar.js:53:40)
    at GrammarRegistry.module.exports.GrammarRegistry.createGrammar (/usr/share/atom/resources/app/node_modules/first-mate/lib/grammar-registry.js:207:23)
    at /usr/share/atom/resources/app/node_modules/first-mate/lib/grammar-registry.js:126:82
    at parseContents (/usr/share/atom/resources/app/node_modules/season/lib/cson.js:123:13)
    at /usr/share/atom/resources/app/node_modules/season/lib/cson.js:230:26
    at ELECTRON_ASAR.js:498:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:603:17)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!  It sounds like the error doesn't reproduce all the time but If the error happens relatively often, can you confirm if the is reproducible in safe mode (atom --safe)?

> I get this when opening a config file from .git folder.

Just to clarify, do you mean specifically `.git/config`?  And is this with any repository or just a particular repository?

**Comment by drupalista-br** [comment]
Any repository.

I turned the computer off last night and back on today. Now the error is gone. Can't get it to happen anymore.

**Comment by rsese** [comment]
Thanks @drupalista-br - since it's not reproducible we'll go ahead close for now but if you start seeing it again, please let us know.
