### ISSUE TITLE
Is Atom unstable under Windows 10?

### ISSUE THREAD

**Issue by leventmuslim** [atom/atom#16773]
* It loads too slow when first opened
* 5 minutes ago I was able to search in whole project, now I can only search within the selected file (ie.index.php)
* I can't open project from the menu bar. I must go to the project folder, right click and select open with Atom
* Favorited lines vanish with no reason. I had to install a bookmark extension which favs the whole file, now extension vanished too! 
* etc
* etc 
*etc

Pretty much anything I touch either doesn't work properly or doesn't work at all! 
Even if a miracle comes up and an option works good, I start praying it won't break down like the others after a core update, cause updates break down things that were working 1 hour ago! 

What's Atom's problem with me? Getting punished for now buying an iMac? How to solve these issues? Is the only solution to uninstall it and begin using something else? If so, is there any writer you know as efficient as Atom and hopefully working properly?

**Comment by 50Wliu** [comment]
Have you followed all the instructions in the [Prerequisites](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md#prerequisites) section as instructed?  That gives us valuable information to follow up on your issue so in the future please don't delete the issue template.

**Comment by lee-dohm** [comment]
Thanks for reaching out!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16773#issuecomment-366458554. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by leventmuslim** [comment]
It’s alright, close the topic. 
We are beginning to get along if I give it enough time to get ready :)) I treat it the same way like my gf when we’ll go out to a concert. I patiently wait and let it(her) be. Then everything goes smoothly after that. (: From my point of view Atom’s a she in that matters lol

**Comment by lee-dohm** [comment]
@leventmuslim your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

I understand what you were saying. Let's avoid using stereotypes like it in the future.

**Comment by leventmuslim** [comment]
Then get all Frenchs out of your life book.
Bah stereotype! French put genders to everything what will you do with that!?? Don’t warn me don’t threaten me! Stand behind your words you sexist bustard! It’s you who acts as a discriminator here not me! Stop accusing people for your miserability!
I’ll leave your damn forum anyway I cannot stand being among sexist maniacs like YOURSELF!!!

**Comment by leventmuslim** [comment]
You may consider as an official warning teaching you how much you have to take care of the way you communicate with outer world! So maybe, just maybe you’ll get more credibility when you walk out in street and do business !
