### ISSUE TITLE
Certain custom themes can load in Safe Mode

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#16770]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If certain custom themes are selected before entering safe mode, they are loaded and activated during safe mode instead of being forced to One Dark temporarily.

### Steps to Reproduce

1. Set a custom theme (`atom-material-ui@2.1.3`)
2. Close Atom
3. Launch Atom in safe mode using `atom --safe`
4. Note that the custom theme is still active and shows as an option in the list.
5. Select a built in theme (`one-dark-ui`)
6. Close Safe Mode and launch Atom in Safe Mode again
7. Note that only the built in themes show as options in the theme selection list.
8. Close Atom, launch in normal mode
9. Select a _different_ UI theme (`city-lights-ui@1.3.3`)
10. Restart Atom in safe mode
11. Note that One Dark is selected as the theme as it should be.

**Expected behavior:**

Custom themes are not loaded or available in Safe Mode.

**Actual behavior:**

Certain custom themes can continue showing in Safe Mode if they was selected before entering Safe Mode:

![2018-02-17_00-06-26](https://user-images.githubusercontent.com/427137/36339306-3516a432-1377-11e8-9a7f-c76d44e39acb.gif)

Atom Material UI is the only one found so far that does this.

**Reproduces how often:**

100% of the time.

### Versions

**Not** a beta bug 😆.

OS: Windows 10 x64 Enterprise

```
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.14
git 2.16.1.windows.4
visual studio 2015
```

### Additional Information

I've tested this back to Atom v1.17.2, all Atom versions behave the same. I also tested with `atom-material-ui@2.0.0` and found the same behavior.

**Comment by Achill113** [comment]
I would like to assist with this issues, is there anyone who can point me in the direction of where there is a check for safeMode and determines themes.

**Comment by Arcanemagus** [comment]
I would probably start in [config.js](https://github.com/atom/atom/blob/a1b03404e81fac37bebeb77276742730a388174c/src/config.js) as that is where the configuration is being loaded, however I don't know for sure where this bug actually is.
