### ISSUE TITLE
git difftool not working

### ISSUE THREAD

**Issue by rss81** [atom/atom#16787]
git difftool not working correctly

**Expected:**  ctrl-alt-d on file should open the difftool on that file.  NOTE: ctrl-shift-D does open difftool on project
**Actual:** nothing happens

using winmerge. also, need to add the following to keymap.cson to get ctrl-shft-D to work:
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-shift-D': 'unset!'

'atom-difftool project':
  'ctrl-shift-D': 'git-difftool:diff-project'

```
     -0:00.0 bug-report:open (div.package-detail.panels-item)
```

## Versions

* **Atom:**       1.24.0
* **Atom-Shell:** 
* **OS:**         Microsoft Windows 10 Pro
* **Misc**
    * apm  1.18.12
    * npm  3.10.10
    * node 6.9.5 x64
    * atom 1.24.0
    * python 
    * git 2.16.1.windows.4
    * visual studio 

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by Arcanemagus** [comment]
It looks like you have tried to add a custom keymap, but specified `atom-difftool project` as the allowed areas for it to activate. The default keymap from that package should have sufficed, so you can likely just remove that entirely. You can find out more about custom keymaps in the [Flight Manual](http://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/).

If that doesn't work you'll want to file this over on the [git-difftool](https://github.com/felixkiss/atom-git-difftool) repository, as the main Atom repository isn't the place to report bugs in packages. 😉
