### ISSUE TITLE
Segfault after system&atom update (Ubuntu 16.04)

### ISSUE THREAD

**Issue by lakonis** [atom/atom#16784]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After having updated the system (Ubuntu 16.04) (and on the way atom to 1.24), I get a Segfault when starting atom. It starts, then freeze with a package release notes open (atom-project-viewer). Eventually  I have a system message box saying Editor is not responding : Force close / keep waiting.

Lauching from a terminal does the same. Except I get the following message in the terminal after force-closing : `/usr/bin/atom : ligne 129 :  7311 Erreur de segmentation  (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1`

launching `atom --safe` works fine.

### Steps to Reproduce

1. update Ubuntu 16.04, update atom 1.24, update packages
2. launch atom

**Expected behavior:** [What you expect to happen]

working atom

**Actual behavior:** [What actually happens]

freezed atom and no other choice to force-close the freezed windows

**Reproduces how often:** [What percentage of the time does it reproduce?]

everytime.

### Versions
`apm --version` : 
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.12
git 2.7.4

`atom --version` :
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

I have tried to workaround going through [issue #15944](https://github.com/atom/atom/issues/15944), related to [Electron issue #11234](https://github.com/electron/electron/issues/11234), with no success.

**Comment by lakonis** [comment]
Update : after reinstalling atom and resetting the .atom folder, atom appeared to work fine. I could reinstall some package, until I tried to launch atom from the terminal. It froze previous atom windows and made them crash. 
From then I get the same Segfault error.

**Comment by lee-dohm** [comment]
Did you [clear the saved state](https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state) as described in the debugging guide?

**Comment by lakonis** [comment]
If removing .atom/ + reinstalling atom from scratch do clear the saved state, then yes, I did.

**Comment by lee-dohm** [comment]
@lakonis No, that doesn't clear the saved state.

**Comment by etorrenti** [comment]
After a dist upgrade from Kubuntu 18.04 to Kubuntu 18.10, this is what I get:

`/usr/bin/atom: line 157:  5062 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
`
All the following workarounds produced no effect:

- Reinstall from scratch
- Wipe out .atom folder
- Unset some environment variables as per suggestion here https://github.com/atom/atom/issues/16604#issuecomment-366250561
