### ISSUE TITLE
[Atom 1.24.0] atom.showSaveDialogSync doesn't return the result

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#16801]
The issue is pretty self-explanatory and is a result of a botched conversion from CoffeeScript in https://github.com/atom/atom/commit/bc774773f74557f50fc9b039ec90cdacf9412341:

https://github.com/atom/atom/blob/9b733c8c78798b418339cde30c42f056bfe072c0/src/atom-environment.js#L1120-L1122

I see it's fixed in `1.25-releases`,
https://github.com/atom/atom/blob/95863010fada6d9a4f3ed6a34a6f1ac606d22229/src/atom-environment.js#L1179-L1184
but not in `1.24-releases`:
https://github.com/atom/atom/blob/1cd820e25cf7e8f8cb7340de7eacbe93f8a0fff5/src/atom-environment.js#L1120-L1122

Please fix this in 1.24?

**Comment by 50Wliu** [comment]
Ah, I assume this is why save-as is failing in packages.

**Comment by 50Wliu** [comment]
Fixed by #16802.
