### ISSUE TITLE
scopeDescriptorForBufferPosition method of TextEditor does not accept point-compatible arrays

### ISSUE THREAD

**Issue by susisu** [atom/atom#16808]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When `Use Tree Sitter Parser` is enabled, `scopeDescriptorForBufferPosition` method of `TextEditor` does not accept point-compatible arrays `[row, column]`.

### Steps to Reproduce

1. Enable `Core > Use Tree Sitter Parser`
2. Open a file in which the tree-sitter parser is enabled (for example, a JavaScript source file)
3. Execute the following code from the development console:
``` javascript
var editor = atom.workspace.getActiveTextEditor();
editor.scopeDescriptorForBufferPosition([0, 0]);
```

**Expected behavior:** `ScopeDescriptor { ... }` is returned.

**Actual behavior:** `TypeError: Point.row must be a number` is raised.

**Reproduces how often:** 100%

### Versions
```
Atom    : 1.25.0-beta1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

### Additional Information
The related codes are

* https://github.com/atom/atom/blob/v1.25.0-beta1/src/text-editor.js#L3646-L3659
* https://github.com/atom/atom/blob/v1.25.0-beta1/src/tree-sitter-language-mode.js#L300
* https://github.com/tree-sitter/node-tree-sitter/blob/b2846701e980572ef287e0effe54d4a91e3c1075/src/ast_node.cc#L281
* https://github.com/tree-sitter/node-tree-sitter/blob/6aeac7a04e817006fbc59a4b4b63f7cbc150a1fa/src/conversions.cc#L46-L50

Perhaps the second one should be:
``` javascript
let node = this.document.rootNode.descendantForPosition(Point.fromObject(point))
```

**Comment by maxbrunsfeld** [comment]
This fix will be released in Atom 1.25.0-beta2.
