### ISSUE TITLE
Package launcher scripts better for the zip/tar packages

### ISSUE THREAD

**Issue by segevfiner** [atom/atom#16813]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom includes launcher scripts that handle various details required for better interaction with the platform. For example, on Windows the script for launching Atom handles the fact that Atom is a GUI (Windows Subsystem) application and makes it behave properly with console output, waiting for it to exit, or detaching from the shell. As another example, the script in Linux/Mac is meant for launching from the shell (Not from a `.desktop` file or similar) and handles setting `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT` and various other details that are somewhat similar to what is done in Windows.

Another issue is that there is no visible script for launching `apm` in the Linux/Mac zip/tar packages. You have to dig into `resources\app\apm\bin\apm` to run it, which is confusing for users not familiar with Atom's internals. I think the deb/rpm packages include a symlink but the zip/tar packages include no such thing.

I think that for all platforms such scripts should be packaged inside a `bin` folder at the root of the Atom installation. This way they are more visible, and you have a clear directory to add to your `PATH`.

The scripts for Windows are here [resources/win](https://github.com/atom/atom/tree/master/resources/win), and the script that is used in Linux/Mac is here [atom.sh](https://github.com/atom/atom/blob/master/atom.sh). apm on Linux/Mac includes it's own scripts and a symlink is created for the non tar/zip packages.

### Steps to Reproduce

1. Look at the contents of the portable zip

**Expected behavior:** I expect the launcher scripts to be packaged visibility.

**Actual behavior:** They are packaged inside the resources folder slightly out of view. `apm` on Linux/Mac is hidden deeply.

**Reproduces how often:** 100%

### Versions

```
Windows 10.0.16299.248 x64

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.14
git 2.16.2.windows.1
visual studio 2015
```

**Comment by iolsen** [comment]
Either a README in the root of the archive or potentially putting the launch scripts themselves in the root would address this.
