### ISSUE TITLE
Packages do not re-activate cleanly after deactivation

### ISSUE THREAD

**Issue by pelmers** [atom/atom#16824]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Disabling and enabling consecutively a package that provides services defined in its package.json will continue to provide those services even after disabling.

### Steps to Reproduce

1. install a package which provides a service, for example this simple autocomplete-math package https://github.com/lonekorean/atom-autocomplete-math
2. disable it
3. enable it
4. disable it
5. (optionally) enabling again here throws an exception.
[video example](https://github.com/atom/atom/files/1750169/atom.disable-enable-disable-enable.zip)

**Expected behavior:**
no longer receive autocompletion from the package

**Actual behavior:**
continue to receive autocomplete from the package

**Reproduces how often:**
always

### Versions
MacOS, Atom 1.23.3

clean .atom directory, no other packages installed

### Additional Information

From looking at `package.js`, it seems that the issue is that the `activationDisposables` field is not correctly reset by the `activateResources` method because it is not set to `null` by `deactivateResources`. 

A couple of easy ways to fix it I think:
1) either let activateResources also check the disposed field of the activationDisposables.
2) have deactivateResources also set activationDisposables to null.
[link to source](https://github.com/atom/atom/blob/master/src/package.js#L736)

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

> Atom 1.23.3

This file was converted to JavaScript in Atom 1.24 /cc: https://github.com/atom/atom/pull/16199 so the code has changed significantly between 1.23.3 and 1.24. Do you still see this issue if you update to the latest version?

Also can you reproduce this issue with a core package that provides a service? For example the `status-bar` package: https://github.com/atom/status-bar/blob/7077fddb06c640d7e4d0125714938732421505df/package.json#L16

**Comment by pelmers** [comment]
Same thing happens in 1.25-beta2, however I couldn't reproduce with the built-in status-bar package. Maybe it only happens when the package doesn't define a `deactivate` method, or it might only happen for the autocomplete-plus provider. The same occurs with the [autocomplete-date package](https://github.com/akameco/autocomplete-date) as well and it matches these conditions.

It's possible the issue belongs to the autocomplete-plus side, I might have been too broad in the original report.

**Comment by lee-dohm** [comment]
Packages need to provide a `deactivate` method to clean themselves up in order to be disabled cleanly (because Atom can't know all the things that the package author does about how the package is designed). If you find a package that doesn't clean itself up properly, you should file an issue on that package.

I'm not convinced this is a bug in Atom.

**Comment by Ben3eeE** [comment]
Thanks for taking the time to contribute!

Since this appears to happen for a package that doesn't have a `deactivate` method to clean itself up it's a problem with this package and not with Atom. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.
