### ISSUE TITLE
Release Anonymous Usage Statistics

### ISSUE THREAD

**Issue by Anonymouqs** [atom/atom#16830]
*[ insert speech about ethics and open-source values/ how such data would help a wider range of devs/gain trust in the public about Anonymous Usage Stats]*

Personally, I'm just curious on how the data looks like for fun. All programs usually have Stats but what do those stats look like to the devs. Other people are curious for other reasons... (freedom ect.)

**Comment by rsese** [comment]
Thanks for reaching out - looks like this was brought up already in https://github.com/atom/metrics/issues/56 if you want to read the discussion.

**Comment by gszingaro** [comment]
Unsubscribe 

using the 24/7 Realtime Comprehensive Collection/Analysis/Intelligent Machine Learning Processing & Prediction of every conceivable metric/data point streamlined into actionable easily interpreted customizable visual presentation.
