### ISSUE TITLE
multiprocessing package runs indefinitely

### ISSUE THREAD

**Issue by trackoverxc** [atom/atom#16833]
[Pre-reqs at bottom]

### Description

Running the multiprocessing package in Atom goes indefinitely. Running the same script from cmd runs in a second.

### Steps to Reproduce

1. Run the sample code from multiprocessing docs for python 3.6 https://docs.python.org/3.6/library/multiprocessing.html 
2. Watch the process run forever

**Expected behavior:** [What you expect to happen]
For the process to complete.

**Actual behavior:** [What actually happens]
The process does not complete, but provides no error.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python
git 2.9.0.windows.1
visual studio 2015

Microsoft Windows 10 home
Version 10.0.16299 Build 16299

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

**Comment by Arcanemagus** [comment]
Atom has no built in capability to "[Run] the multiprocessing package", it would help to diagnose this issue if you specified how you are attempting to do that.

**Comment by trackoverxc** [comment]
@Arcanemagus
`from multiprocessing import Pool

def f(x):
    return x*x

if __name__ == '__main__':
    with Pool(5) as p:
        print(p.map(f, [1, 2, 3]))`

**Comment by Arcanemagus** [comment]
Yep, that's what I would do as it's unlikely this has anything to do with Atom itself 😉.

**Comment by 50Wliu** [comment]
@Arcanemagus's advice is correct.
