### ISSUE TITLE
after installing atom bin folder is not creating

### ISSUE THREAD

**Issue by MandarSant** [atom/atom#16831]
### Description
![capture](https://user-images.githubusercontent.com/20091634/36640261-21b57d70-1a41-11e8-90e5-a72dc55b63f3.JPG)

[bin folder is not creating @ this location

>  C:\Users\<USERNAME>\AppData\Local\atom

]

[check ount this link in discuss forum](https://discuss.atom.io/t/installiing-packages-through-command-line/44465)

**Expected behavior:** [bin folder should be created]

**Actual behavior:** [bin folder is missing on fresh install ]

### Versions

latest Version 
windows 8.1 wmc

**Comment by rsese** [comment]
I just replied in the thread @MandarSant with the workaround mentioned in https://github.com/atom/atom/issues/11450 - going to close this since it's already reported in https://github.com/atom/atom/issues/11450 and you can subscribe there for updates if you'd like.
