### ISSUE TITLE
Choosing "About Atom" menu item displays error message

### ISSUE THREAD

**Issue by markovicpp** [atom/atom#16838]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Choosing "About Atom" from "Atom" menu on macOS displays following message:

> Unable to open project directory
> Project directory atom://about is no longer on disk.

### Steps to Reproduce

1. Start Atom app
2. Choose "About Atom" menu item from "Atom" app menu

**Expected behavior:** No error message should appear on "About Atom" window

**Actual behavior:** Error message appears on "About Atom" window

**Reproduces how often:** Always since updating Atom from version 1.23.2 to 1.24.0

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
![screen shot 2018-02-26 at 2 56 33 pm](https://user-images.githubusercontent.com/16366024/36650082-3a660d10-1b06-11e8-8dd6-4cf22cee61b0.png)

**Comment by rsese** [comment]
Thanks for the report - while going through the debugging steps did you try clearing saved state?  P lease save any unsaved work first.

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by markovicpp** [comment]
Thanks @rsese!
That fixed the problem, I must have overlooked the step when filling the bug.
