### ISSUE TITLE
add "Open current folder in terminal" option.

### ISSUE THREAD

**Issue by DividedByCero** [atom/atom#16847]
When i click above the tree view panel (left panel), couldn't find a option to bring a terminal of the current folder. I found myself relying into a `atom-terminal` to be capable of easily open a terminal, at least it seems like a feature that would be really useful to new users.

**Comment by rsese** [comment]
Thanks for the feedback - there's a feature request for an integrated terminal at https://github.com/atom/atom/issues/14490 so you can subscribe there for updates if you'd like.
