### ISSUE TITLE
Provide a "untrusted html view".

### ISSUE THREAD

**Issue by ptoomey3** [atom/atom#1684]
In addition to [locking down iframes](https://github.com/atom/atom-shell/issues/193#issuecomment-36634975) and [enabling CSP](https://github.com/atom/atom/issues/1682) I think it might be nice to provide a top level API that extensions can use to render HTML safely.  Extensions such as markdown-preview take a string of HTML and render it in a div within the main Atom UI.  As a result, the HTML is rendered in the same context as the rest of Atom (with Node integration).  While CSP should mitigate much of the risk associated with this, it doesn't totally solve the "render untrusted HTML" issue.  For example, user content could potentially still break the DOM of the main Atom app. So, we could just ask that markdown-preview use a sandboxed iframe to minimize the issues that could arise from rendering user provided content.  But, I was thinking it might be a nice API primitive if we allowed any extension to hand us a string of HTML and we render it for them. I'm not sure how extensible this would need to be (ex. does the rendered HTML inherit CSS styles from the outer frame, etc), but it does seem like a nice security API.

@kevinsawicki @mcolyer @nathansobo @gregose @mastahyeti

**Comment by kevinsawicki** [comment]
I think this can all be done in Electron now via the `<web-view>` tag, https://github.com/atom/electron/blob/master/docs/api/web-view-tag.md

Closing this out.
