### ISSUE TITLE
Why Atom doesn't have `rust` syntax highlighting by default?

### ISSUE THREAD

**Issue by IgorPolyakov** [atom/atom#16842]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    *  [X] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    *  [X] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    *  [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

atom doesn't have `rust` syntax highlighting by default.

### Steps to Reproduce

1. Open file with `rust` source code.

**Expected behavior:** [What you expect to happen]
Opened*.rs file. All code would be highlighted.

**Actual behavior:** [What actually happens]
Opened *.rs file. Atom use `plan text` template.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.24.0
Electron: 1.8.2
Chrome  : 59.0.3071.115
Node    : 8.2.1

apm  1.19.0
npm  5.6.0
node 9.6.1 x64
atom 1.24.0
python 2.7.14
git 2.16.2

Arch Linux

**Comment by 50Wliu** [comment]
Please see the explanations in https://github.com/atom/atom/issues/13932 as to why we are unable to ship with Rust language support by default at this time.

**Comment by IgorPolyakov** [comment]
Thanks for the feedback.
