### ISSUE TITLE
I Can't save my files on Atom and I can't find a solution to this problem.

### ISSUE THREAD

**Issue by baker13** [atom/atom#16848]
When I pres Ctrl+S to save my file. atom empties all the contents in the file. If I don't press Ctrl+Z then it saves the file as an empty document. which is extremely frustrating as I can't use atom because of this. It will just delete all my code. I have no custom packages and It does the same thing even in safe mode. 

Please if anyone has a solution to this problem please help me.

I am using Ubuntu 14.04

**Comment by rsese** [comment]
Thanks for the report - can you share more information about the issue?  In particular, the issue template information is really helpful and if you can add more details we can go from there:

* What version of Atom are you running?
* How did you install Atom?
* Did Atom work fine before and this behavior just started happening recently?  
* Besides trying safe mode, have you run through the rest of the debugging document (https://flight-manual.atom.io/hacking-atom/sections/debugging)?
  * Are there any errors in devtools console (https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools)?

**Comment by baker13** [comment]
I have a feeling the problem is not with Atom. do you know of any ubuntu things that could conflict with Atom Files?

**Comment by rsese** [comment]
> Atom : 1.23.3

The currently release version is 1.24 so you could install the latest to see if that helps.

> I haven't gone through the debug docs. didn't know they existed.

It looks like you tried resetting to factory defaults, have you tried clearing saved state as well?

> I installed atom through linux console. I have uninstalled and reinstalled it twice.

Sorry I was double checking if you used a supported installation method:

https://flight-manual.atom.io/getting-started/sections/installing-atom/#debian-and-ubuntu-debapt

If you haven't, uninstall Atom and re-install with one of the supported install methods.

> I have a feeling the problem is not with Atom. do you know of any ubuntu things that could conflict with Atom Files?

Oh are you having issues with other programs?  I don't recall specific issues with Ubuntu that have caused this behavior in the past.  If you think this is not Atom specific I'd suggest closing this issue for now but we can always re-open if you find more evidence that this is an Atom issue.

**Comment by baker13** [comment]
No I'm only having this problem with Atom. But it's really strange that's all. So was wandering if maybe it could be something with Ubuntu.

I will try other install methods and newer version and see if it works and post back afterwards. Thanks.

**Comment by baker13** [comment]
Even with the latest version I still have this same problem. I think it's a problem with Ubuntu. If I find the answer I will post it.

**Comment by rsese** [comment]
Ok thanks @baker13 :+1:
