### ISSUE TITLE
selecting last item in file pane.

### ISSUE THREAD

**Issue by kentdlee** [atom/atom#16856]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you open a series of directories in the left pane (what is called the "Project" pane) and the directories fill the pane from top to bottom, you cannot select the last directory to open it and look at its contents with the mouse or trackpad. You can open the directory by using the arrow keys to move the selection to the last directory and then pressing "Enter". 

The same goes for the last file in a series of files in the  "Project" pane. You cannot click on the last file in the pane if it goes all the way to the bottom.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
This issue was moved to atom/tree-view#1229
