### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=500

### ISSUE THREAD

**Issue by wuxiao356** [atom/atom#16857]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=500

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=500
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:290:19)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:394:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
  2x -4:03.0 application:reopen-project (ul.list-inline.tab-bar.inset-panel)
     -1:06.2.0 command-palette:toggle (summary.welcome-summary.icon.icon-keyboard)
 16x -0:59.8.0 core:backspace (input.hidden-input)
     -0:40.7.0 core:move-down (input.hidden-input)
     -0:34.9.0 core:confirm (input.hidden-input)
     -0:34.9.0 window:install-shell-commands (summary.welcome-summary.icon.icon-keyboard)
     -0:20.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
go-plus 5.8.2 
```

**Comment by rsese** [comment]
Thanks for the report - this looks like an error related to the proxy you're using?  If the error is intermittent or only happened once, then there might be a temporary issue with your network or proxy and retrying might help.  If the error is consistently reproducible and you've [configured Atom to work with your proxy](http://flight-manual.atom.io/getting-started/sections/installing-atom/#proxy-and-firewall-settings), then a good place to get help is our [official message board](https://discuss.atom.io/).  People in the community that have configured Atom to work with their proxies can chime to share what worked for them and provide suggestions.
