### ISSUE TITLE
'await' may be missing at async function call

### ISSUE THREAD

**Issue by jerry88kim** [atom/atom#16858]
### Description
Hi, I am a developer of JavaScript code quality service called DeepScan(https://deepscan.io).

We analyzed atom project's code with DeepScan for benchmarking, and found some issues which would be better to modify it.

I will report on the issues we found below and create pull request for fixing them.

And here is DeepScan's detailed result link for atom project.
https://deepscan.io/dashboard/#view=project&pid=2005&bid=9394&subview=issues

### Additional Information

Alarm 1: **Condition 'isOpenInEditor(realPath)' is always true because it evaluates to a 'Promise' object. The object is originated from the return value of the function defined at line 226.**
* Src: src/path-watcher.js(242:24-242:48)
    `this.subs.add(treeView.onEntryDeleted(async event => {`
    `  const realPath = await getRealPath(event.path)`
    `  if (!realPath || isOpenInEditor(realPath) /*alarm*/) return`
    `...})`
* Cause
  - 'isOpenInEditor()' is async function, and returns Promise object when calling without 'await', so the condition is always true.
  - 'isOpenInEditor()' function's body returns boolean, so maybe 'await' is unintendedly missing.
  - 'isOpenInEditor()' function code
    `const isOpenInEditor = async eventPath => {`
    `  const openPaths = await Promise.all(`
    `    atom.workspace.getTextEditors().map(editor => getRealPath(editor.getPath()))`
    `  )`
    `  return openPaths.includes(eventPath) // return boolean value`
    `}`

* Guide
  - Call 'isOpenInEditor()' with 'await'.

Alarm 2: **Number of arguments passed to 'RegExp.prototype.test()' should be 1. But 2 arguments are passed.**
* Src: src/main-process/application-menu.js (204:14-204:68)
  `if (item.command) {`
  `  item.accelerator = this.acceleratorForCommand(item.command, keystrokesByCommand)`
  `  item.click = () => global.atomApplication.sendCommand(item.command, item.commandDetail)`
  `  if (!/^application:/.test(item.command, item.commandDetail) /* alarm */) {`
  `    item.metadata.windowSpecific = true`
* Cause
  - 'RegExp.prototype.test()' only has one argument, so the second argument 'item.commandDetail' is ignored.
* Guide
  - Remove the second argument 'item.commandDetail'.

**Comment by 50Wliu** [comment]
Pretty cool project, thanks for creating the issue and PR!
