### ISSUE TITLE
Android version / mobile versions

### ISSUE THREAD

**Issue by emahuni** [atom/atom#16861]
I think it would be great to see Atom on Android. Android does not have any good code editors. And I think wrapping this using Cordova or something and help to bring a good code editor to Android.

**Comment by lee-dohm** [comment]
This is covered in the [Atom FAQ](https://discuss.atom.io/c/faq) under [Is Atom going to be available on mobile platforms like iOS or Android?](https://discuss.atom.io/t/is-atom-going-to-be-available-on-mobile-platforms-like-ios-or-android/29521)
