### ISSUE TITLE
Problems with Umlaut

### ISSUE THREAD

**Issue by obwohl** [atom/atom#16860]
Hi,
i am using atom 1.24.0 on a Macbook with Sierra 10.12.6, using the "script" package to run.

print("ä")

or any other Umlaut yields to 
(...) SyntaxError: Non-ASCII character '\xc3' in file (...)

Is there any package or any simple solution to fix this? Going through the encoding-jungle did not help me at all. I'll not be happy to add lots of encoding commands to every python script/program I am gonna write. IntelliJ for example does not have those issues at all.

**Comment by Arcanemagus** [comment]
It looks like there are [several issues](https://github.com/rgbkrk/atom-script/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+encoding) about this already filed on the `scripts` package, you should find the one that is most applicable to your use case and follow it there, or help contribute a fix 😉.

Atom itself has nothing to do with how packages handle external programs so this shouldn't be filed here.

**Comment by rsese** [comment]
> It looks like there are several issues about this already filed on the scripts package, you should find the one that is most applicable to your use case and follow it there, or help contribute a fix 😉.
> 
> Atom itself has nothing to do with how packages handle external programs so this shouldn't be filed here.

✨ 👍 

As @Arcanemagus mentions, this is an issue with the `scripts` package and you can followup there.
