### ISSUE TITLE
Cannot configue atom with git in win 10

### ISSUE THREAD

**Issue by yaraeb** [atom/atom#16869]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I cannot configure atom with git 

### Steps to Reproduce

i installed atom and pasted this line of code in git bash 
git config --global core.editor "'C:/users/[user]/appdata/local/atom/bin/atom.cmd' --new-window --wait"
and then wrote git commit to make it commit the changes made
**Expected behavior:** open atom editor with the files

**Actual behavior:** returns this message
hint: Waiting for your editor to close the file... 'C:/users/[user]/appdata/local/atom/bin/atom.cmd' --new-window --wait: C:/users/[user]/appdata/local/atom/bin/atom.cmd: No such file or directory
error: There was a problem with the editor ''C:/users/[user]/appdata/local/atom/bin/atom.cmd' --new-window --wait

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Arcanemagus** [comment]
You haven't filled out the requested information in the template, one of the more important bits of information being the version of Atom you are using. Proper support for this was only introduced with Atom v1.25.0-beta0. You should also only need `atom --wait` in there.

Note that on Windows there is currently [a bug](https://github.com/atom/atom/issues/16740) where you still need to close the entire window, not just the tab. It is [fixed](https://github.com/atom/atom/commit/3078c4d14fb2bc83b187ecf30c1e07610b4cceb0) on `master`, but hasn't been released in a beta build yet.

**Comment by rsese** [comment]
Thanks for the report @yaraeb and :+1: on everything @Arcanemagus said - if you have 1.25.0-beta0 installed already and you see behavior different than currently described in https://github.com/atom/atom/issues/16740 with `git config --global core.editor 'atom --wait'`, please let us know.  Otherwise, that particular bug will be fixed in an upcoming release.

**Comment by ahaque3** [comment]
I am having this exact issue and the exact error message:
atom version: 1.26.1 x64
windows 10

**Comment by rsese** [comment]
Thanks @ahaque3 - please create a new issue and fill out the issue template and we'll take a look.

**Comment by anand0427** [comment]
It actually works with the atom.exe file from Local/atom/
