### ISSUE TITLE
Still Having This Issue?

### ISSUE THREAD

**Issue by shoxter** [atom/atom#16877]
### Description

I'm still having this issue: https://github.com/atom/atom/issues/1667

I have tried the package to fix it to no avail. I really don't want to have to switch to IntelliJ because I like Atom so much better, but I cannot properly program with this bug as it stands.

Is there something I can do to help resolve it?

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

I'm running Mint Linux 18.2

**Comment by lee-dohm** [comment]
Please don't open duplicate issues, it takes maintainers time away from actually working on the project.

If you would like to help resolve this, you might want to take a look at the work being done on tree-sitter and help with that. tree-sitter is the grammar engine that is the replacement for first-mate that has the limitation you're concerned with.
