### ISSUE TITLE
Atom Installed by snap command doesn't open

### ISSUE THREAD

**Issue by gucoloradoc** [atom/atom#16874]
# Snaps 
Installing Atom by snap seemed interesting, but after installing it, I couldn't open it. Then I tried to install the program by the usual apt package manager and everything went fine, but the other one (Atom installed by snap) still in my desktop. I ended up uninstalling atom installed by snap and keep the one installed by apt.

I don't know if it is a problem of the snap package manager or the way in which atom uses it. 

## Specs

- ASUS AK45VD
- Ubuntu 17.10 GNOME Desktop

I hope this issue report to be useful.

**Comment by 50Wliu** [comment]
The snap version of Atom is community-maintained and not officially supported by the Atom maintainers.  Therefore, you'll have to ask the snap package maintainers for guidance.
