### ISSUE TITLE
Not possible to close About window using cmd-w shortcut

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1687]
Reported here:
* support/811a5042a1aa11e3955114c3b4bf65e6

![screen shot 2014-03-04 at 7 29 07 pm](https://f.cloud.github.com/assets/38924/2324580/e951c592-a3ca-11e3-99ff-b79715b7745e.png)

:tennis:

**Comment by kevinsawicki** [comment]
The native about window is now gone via https://github.com/atom/atom/pull/7377, closing this out.

**Comment by izuzak** [comment]
Best way to close this issue! :zap: to @mnquintana for the great work in #7377.
