### ISSUE TITLE
Restarting Atom doesn't restore tabs correctly.

### ISSUE THREAD

**Issue by hally9k** [atom/atom#16871]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Restarting Atom doesn't preserve my tabs, rather it opens a new window for each of my tabs.

### Steps to Reproduce

1. Open Atom.
2. Open a secondary tab.
3. Restart Atom.
4. Notice the two separate windows that reopen for each tab.

**Expected behavior:**
Atom to restart and restore a single window with two tabs.

**Actual behavior:** 
Two separate windows are opened on restart.

**Reproduces how often:** 
100%

### Versions
1.24.0 x64 on MacOS High Sierra

**Comment by Aerijo** [comment]
> Notice the two separate windows that reopen for each tab.

Did not notice this. Each tab appears as it was before running `Window: Reload`. I am using Atom v1.24.0, and macOS 10.13.3 (High Sierra).

**Comment by hally9k** [comment]
Aaah sorry full screen mode. Forgot to mention
Yes, I've tried it in safe mode.

Open Atom *in full screen*
⌘ ⇧ n for new window. (Adds a window tab strip at the top)
Restart atom.
Two separate windows.

This is frustrating because I have a real nice set up with my projects all set up in the right order etc and then I need to update a plugin and restart and I have no way to merge my windows again.

**Comment by Aerijo** [comment]
> ⌘ ⇧ n for new window. (Adds a window tab strip at the top)

That does open a new window...

> Now I have one window with two atom sessions running in each tab.

...which means you should have two windows open, not one.

When restarting Atom using `Window: Reload` with two tabs open (in the same window) & in fullscreen mode, I still don't have an issue.

**Comment by rsese** [comment]
Ohhh I think I see what you're saying @hally9k?  You have macOS native tabs enabled (probably `System Preferences > Dock > Prefer tabs when opening documents` set to `In Full Screen Only`?).

So when you have 2 native tabs open because you're in full screen, when you restart those 2 tabs are now 2 windows.  I can reproduce this behavior but I wonder if this is an Electron issue (I see the same behavior in VS Code) or a general issue on macOS (I see the same behavior in Sublime)?

**Comment by lee-dohm** [comment]
This sounds like a special case (and therefore duplicate) of #15534.

**Comment by hally9k** [comment]
@rsese I think that might be it, I haven’t really used native tabs other than with atom so I assumed this was an atom issue but the behaviour seems to be consistent across multiple other applications. Will dig further and maybe target this one else where, thanks for taking the time. Closing.
