### ISSUE TITLE
Atom/Core URL handler support for Markdown inside Datatip

### ISSUE THREAD

**Issue by BoykoAlex** [atom/atom#16888]
### Prerequisites

 [ X]   * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
 [ X]   * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
[ X]    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
[ X]    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
[ X]    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

MD preview and MD datatips (hovers) don't support `atom/core` URL handlers from #15935. Would be useful if I want to provide source code links inside the datatip (hover)

### Steps to Reproduce

1. Create an MD file with a link similar to `[This is a link](atom://core/open/file?filename=<path to file>)`
2. Open MD preview
3. Click on the link - nothing happens. At the same time if one switches the URL to `http://www.bbc.com` the link would work

**Expected behavior:**
The file specified by its path open in Atom text editor

**Actual behavior:**
Core URLs not supported

**Reproduces how often:**
100%

### Versions
All verions up to 1.25-beta2

### Additional Details
Looking for directions... What to look at if I am to provide a patch for this

**Comment by BinaryMuse** [comment]
This is due to dompurify removing unsafe links in this block of code in `markdown-preview`:

https://github.com/atom/markdown-preview/blob/6a502afe3937d02f9dd4631be43f89c2fbdc54fd/lib/renderer.coffee#L34-L49

If you check "Allow Unsafe Protocols" in the markdown-preview options, `atom://` links work correctly, but also allows other protocols you likely don't want enabled. Luckily, dompurify allows passing options to control this, so it shouldn't be too crazy to fix:

```javascript
// allow external protocol handlers in URL attributes (default is false)
// by default only http, https, ftp, ftps, tel, mailto, callto, cid and xmpp are allowed.
var clean = DOMPurify.sanitize(dirty, {ALLOW_UNKNOWN_PROTOCOLS: true});

// allow specific protocols handlers in URL attributes (default is false)
// by default only http, https, ftp, ftps, tel, mailto, callto, cid and xmpp are allowed.
// Default RegExp: /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i;
var clean = DOMPurify.sanitize(dirty, {ALLOWED_URI_REGEXP: /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp|xxx):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i;});
```

**Comment by BoykoAlex** [comment]
@BinaryMuse i think the setting `ALLOW_UNKNOWN_PROTOCOLS` and `ALLOWED_URI_REGEXP ` only helps to properly set `href` attribute to the `atom://...` URL value. Is that correct?
I've tried modifying the DOM directly via dev tools and set the `href` attribute to: `atom://atom://core/open/file?filename=<path to file>`. I think the result of this is the same as passing those 2 settings mentioned above. However, clicking on the link does nothing still.
Anything i need to set in Atom config for the atom core URLs to work within Atom? These URLs work when i try open `atom://` URL in my OS, but not in Atom...

**Comment by BoykoAlex** [comment]
@BinaryMuse hmm... maybe my atom core URL is in incorrect format. The URL I'm trying is: `atom://core/open/file?filename=/Users/aboyko/Documents/Language-Server/demo/src/main/java/com/example/DemoApplication.java`
The file name attribute being the absolute path to a file.
Does that look ok?

**Comment by BoykoAlex** [comment]
I still can't get Atom core URLs to work from MD preview even after setting the prefernce `Allow Unsafe Protocols`. I see with the DOM inspector (DevTools) that `href` attribute has the right Atom coe URL value, but clicking on the link doesn't nothing...
Can you provide me a Atom Core URL that worked for you? Or an MD content that worked from the MD preview? (just need it as an example, I understand that file name/path would be different)

**Comment by UziTech** [comment]
I was looking for the exact format too according to #15935 it's:

```
atom://core/open/file?filename=urlEncodedFileName&line=n&column=n
```

**Comment by BoykoAlex** [comment]
@UziTech I have tried encoding the file path and it again only works from the OS, i.e. Mac OSX URL in the Text Editor, right-click `Open URL` - works.
However, if I'm to put this URL in an MD file in a link format it doesn't work from MarkDown preview in Atom UI (same goes for hovers/datatips). Does this work for you?

**Comment by UziTech** [comment]
You are correct. It does seem to work with [hyperlink-hyperclick](https://atom.io/packages/hyperlink-hyperclick).

After a bit of research it looks like the "Open link" explicitly only works with http/https links https://github.com/atom/link/blob/add8170e69c84e1ea438e22b6a023a32f6582eaf/lib/link.js#L28

And markdown-preview doesn't seem to work with anything other than http or https (I tried `mailto://`) It seems atom would have to register the other protocols with [electron.protocol.registerHttpProtocol](https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolregisterhttpprotocolscheme-handler-completion) to allow links to open with those protocols.

**Comment by BoykoAlex** [comment]
@UziTech Thanks very much for the info! I think there is enough info for me to attempt a patch :-)

**Comment by UziTech** [comment]
I added a PR for language-hyperlink to include `atom://` URIs

https://github.com/atom/language-hyperlink/pull/21

**Comment by BoykoAlex** [comment]
Looks like I found the right solution for the problem. Wonder if anyone can merge this PR #16940 ?

**Comment by lee-dohm** [comment]
@daviwil Would you mind checking this out?
