### ISSUE TITLE
Latex completions don't work in the CTRL-F search field.

### ISSUE THREAD

**Issue by Aether59** [atom/atom#16882]
Julia 0.6.2 with Julia-Client 0.6.9 on Ubuntu 16.04 LTS.

Latex completions are great. But they don't work in the find/search/replace field so searching becomes a problem. (It is possible to copy/paste a Latex expression into the search field or to highlight an expression and hit CTRL-F.  But not possible to write an expression a priori in the search field.)

Feature request/suggestion:  Writing Latex completions to be supported in the search/find/replace fields.

Thanks.

**Comment by rsese** [comment]
Thanks for the feedback - I think your request is specific to the Julia community packages you're using?  If so, you should make the request with the maintainers of those packages.  If I'm misunderstanding let me know.
