### ISSUE TITLE
Helper HTML opening guides disappeared

### ISSUE THREAD

**Issue by gitHub-Alice** [atom/atom#16890]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

the first few times I used atom I was able to get the starter code for html projects as a selecter. And then it stopped doing that.

### Steps to Reproduce

1. type html
2. if Atom doesn’t offer to give you the starter code (<!DOCTYPE html> ...) then this is the problem

**Expected behavior:** [What you expect to happen]
atom offers to give the starter code (which starts with “<!DOCTYPE html> ...)
**Actual behavior:** [What actually happens]
atom doesn’t offer to give anything
**Reproduces how often:** [What percentage of the time does it reproduce?]
90%
### Versions
1.24
I’m using macOS High Sierra version 10.13.3
![screen shot 2018-03-06 at 00 02 16](https://user-images.githubusercontent.com/35408163/37020713-a8cb170c-20d1-11e8-9075-639ad9924160.png)

**Comment by phuongkt** [comment]
.

**Comment by phuongkt** [comment]
.

**Comment by phuongkt** [comment]
yé

**Comment by rsese** [comment]
Thanks for the report - just to clarify, are you working in a .html file or a new file?  If you're in a new file, is the grammar selector (<kbd>ctrl-shift-l</kbd>) set to HTML?

**Comment by gitHub-Alice** [comment]
Apparently grammar selecter is not set to html; thanks!

**Comment by rsese** [comment]
No problem, glad that helped 👍
