### ISSUE TITLE
Can't commit or stage changes from the git tab.

### ISSUE THREAD

**Issue by abhishekBM4576** [atom/atom#16897]
Did every possible thing mentioned in the debugging guide and searched for FAQ but couldn't find similar issues in github or other websites.

### Description

Whenever I open a local git repository and make changes to one of the files in Atom, I can see green, yellow and red lines indicating that the file has been modified. But I can't see the branch name in the status bar and I can't view or commit changes in the git tab. It is just empty even if I've made a change or staged.

### Steps to Reproduce

1. Make a change to file in a repository.
2. Go to the git tab.
3. Commit the changes (and the current branch should be visible in the status bar).

**Expected behavior:**
Be able to commit from the git tab.

**Actual behavior:**
Doesn't show the changes and the commit button is greyed out.

### Versions

**Atom version:**
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Apm version:**
apm  1.18.12
npm  3.10.10
node 6.9.5 ia32
atom 1.24.0
python 3.6.4
git 2.14.1.windows.1

**OS version:**
Windows 7(32-bit) with service pack 1

![1](https://user-images.githubusercontent.com/30763111/37106877-dd33625a-2258-11e8-9412-6564408ec1e3.png)
![2](https://user-images.githubusercontent.com/30763111/37106911-fadf4a4e-2258-11e8-88c9-b7f996c34c95.png)
![3](https://user-images.githubusercontent.com/30763111/37106930-05d76990-2259-11e8-9093-47c68ff84ead.png)

It would be so thankful if somebody helped me out. I'm trying to feel the real power of Atom text editor and its community.

**Comment by rsese** [comment]
This issue was moved to atom/github#1336
