### ISSUE TITLE
Not saved file cause lost git information

### ISSUE THREAD

**Issue by theGABS** [atom/atom#16895]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If I have not saved file after git merge I still see old state of file 

### Steps to Reproduce

1. Open file index.js
2. Change something but not save 
3. Do git pull witch should cause merge conflict for index.js file (I do from console)

**Expected behavior:** Not sure, but I want to see correct git file with <<<<<<< HEAD etc.

**Actual behavior:** I see old version of not saved file. So information from git lost. 

**Reproduces how often:** Everytime

**Comment by rsese** [comment]
This issue was moved to atom/github#1335
