### ISSUE TITLE
Command palette have 1px missing on border when focused

### ISSUE THREAD

**Issue by skylerlee** [atom/atom#16903]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I found the Atom's command palette editor have 1px missing on border when focused.

### Steps to Reproduce

1. Open Atom
2. Press <kbd>CtrlOrCmd+P</kbd>
3. It seems the input palette's blue border have 1px less at top, left and right, here is the screenshot:

![screenshot](https://user-images.githubusercontent.com/6789491/37141465-03a3b38a-22f0-11e8-9198-c881092f066a.png)

It seems like a rendering bug because when I move the selection around (pressing up/down),
the missing width get back. But when the palette reopens, it reproduces again.

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
**UI Theme**: One-Dark-UI

### My Attempting Solution

Set the `border-width` of the editor seems to solve the problem, but I just wondering the effect of 
`box-shadow`. Can I set it to none?

```less
atom-text-editor[mini].is-focused {
  border-width: 2px;
  box-shadow: none;
}
```

**Comment by 50Wliu** [comment]
Fixed.

**Comment by simurai** [comment]
Yep, fixed in https://github.com/atom/one-dark-ui/pull/244 that should land in Atom `1.26`.

> @skylerlee My Attempting Solution

👍 on that solution. In the ☝️ above PR, a 1px padding got added. I think the problem is that the backdrop is semi-transparent and causes a rendering glitch of the box-shadow. 🤷‍♂️

**Comment by skylerlee** [comment]
Good :+1: , thanks.
