### ISSUE TITLE
Atom change the theme on his own

### ISSUE THREAD

**Issue by Matows** [atom/atom#16908]
### Description

I just updated my atom software and whatever I do to change the theme, it change back to Atom Dark UI/Syntax theme instead of One Dark.

### Steps to Reproduce

1. open atom with the last version
2. change the theme to One Dark
3. wait a few seconds

**Expected behavior:** Keep the theme I want

**Actual behavior:** Change the theme on his own

**Reproduces how often:** I tried to change 5 times and failed 5 times

### Versions

Atom    : 1.24.1
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  : 1.18.12
npm  : 3.10.10
OS : Windows 10 Familly 1709

### Additional Information

Happened just after I updated on 1.24.1

**Comment by rsese** [comment]
Thanks for the report - I was unable to reproduce with Atom 1.24.1 on Windows 10.  It looks like you removed the `Prerequisites` section, are you able to reproduce in safe mode (`atom --safe`) or have you tried any of the other debugging advice?

**Comment by Matows** [comment]
Indeed, I remove the `Prerequisites` section because I didn't have the time when a post the report. But yes I tried it in safe mode and the problem is the same. I'll give you more details if I can when I'll be back at my place.

**Comment by Matows** [comment]
Okay so after I renamed my .atom to .atom-backup (as written in debugging section) it seems to work the good way. It's weird x) I'll install my config again step by step to see if there is something wrong and I'll come back to you if needed.

**Comment by Arcanemagus** [comment]
Thanks for reporting back!
