### ISSUE TITLE
`atom.config.get` inappropriately referring config.cson value in test-spec

### ISSUE THREAD

**Issue by t9md** [atom/atom#16910]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Here is the excerpt of test-spec for my cursor-history pkg.
Maybe because of bug of v1.25.0-beta3, `atom.config.get` return actual config defined in `config.cson` rather than it's default value in the very first executed section.
Which make `f`-ocused spec tested in wrong condition. Also very first test is executed in environment dependent config value.

From quick code check(not tested throughly), maybe these lines does set env specific config.
https://github.com/atom/atom/blame/master/src/atom-environment.js#L213-L225
May be because of change in https://github.com/atom/atom/pull/16628#issuecomment-367172653?

```javascript
  fdescribe('initial state of history entries', () => {
    it('1', () => {
      console.log('1-1', atom.config.get('cursor-history.columnDeltaToRemember'))
      console.log('1-2', atom.config.get('cursor-history.columnDeltaToRemember'))
      // v1.24.0:        9999(default value)
      // v1.25.0-beta3:  5(my local config set in config.cson!!)
    })
    it('2', () => {
      console.log('2-1', atom.config.get('cursor-history.columnDeltaToRemember'))
      console.log('2-2', atom.config.get('cursor-history.columnDeltaToRemember'))
      // v1.24.0:        9999(default value)
      // v1.25.0-beta3:  9999(default value)
    })
  })
```

<img width="680" alt="env-dependent" src="https://user-images.githubusercontent.com/155205/37186408-b7526032-2388-11e8-96d5-27eeac7628ef.png">

### Steps to Reproduce

1. write sample test spec I explained above using whatever config you want(e.g. `atom.config.get('editor.atomicSoftTabs')`).
2. See how `atom.config.get` return value change in 1st and 2nd section of test spec.

**Expected behavior:** [What you expect to happen]

Test spec should be executed in default configuration like in v1.24.0.

**Actual behavior:** [What actually happens]

Test spec is executed in env-dependent config for very first call of `atom.config.get`.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

```
$ atom-beta --version
Atom    : 1.25.0-beta3
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
$ atom --version
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Arcanemagus** [comment]
For slightly easier steps to reproduce on a machine with Docker using [this Gist](https://gist.github.com/Arcanemagus/a2db7a8eac51db532cecc1bd4a034670):

#### Stable
Run `docker run --rm -it arcanemagus/atom-docker-ci:stable bash`:
```ShellSession
atom@bc1b0cc80840:~$ git clone --quiet https://gist.github.com/a2db7a8eac51db532cecc1bd4a034670.git
atom@bc1b0cc80840:~$ cd a2db7a8eac51db532cecc1bd4a034670/
atom@bc1b0cc80840:~/a2db7a8eac51db532cecc1bd4a034670$ mkdir -p ~/.atom/
atom@bc1b0cc80840:~/a2db7a8eac51db532cecc1bd4a034670$ cp config.cson ~/.atom/
atom@bc1b0cc80840:~/a2db7a8eac51db532cecc1bd4a034670$ ${ATOM_SCRIPT_PATH} --enable-electron-logging --test test-spec.js
[42:0309/055016.927629:INFO:CONSOLE(12)] "Version: 1.24.1", source: /home/atom/a2db7a8eac51db532cecc1bd4a034670/test-spec.js (12)
[42:0309/055016.928323:INFO:CONSOLE(13)] "1-1: 9999", source: /home/atom/a2db7a8eac51db532cecc1bd4a034670/test-spec.js (13)
[42:0309/055016.928764:INFO:CONSOLE(14)] "1-2: 9999", source: /home/atom/a2db7a8eac51db532cecc1bd4a034670/test-spec.js (14)
.[42:0309/055017.035555:INFO:CONSOLE(19)] "2-1: 9999", source: /home/atom/a2db7a8eac51db532cecc1bd4a034670/test-spec.js (19)
[42:0309/055017.036716:INFO:CONSOLE(20)] "2-2: 9999", source: /home/atom/a2db7a8eac51db532cecc1bd4a034670/test-spec.js (20)
.

Finished in 0.378 seconds
2 tests, 0 assertions, 0 failures, 0 skipped

atom@bc1b0cc80840:~/a2db7a8eac51db532cecc1bd4a034670$
```

#### Beta

Run `docker run --rm -it arcanemagus/atom-docker-ci:beta bash`:
```ShellSession
atom@5a72c858eef2:~$ git clone --quiet https://gist.github.com/a2db7a8eac51db532cecc1bd4a034670.git
atom@5a72c858eef2:~$ cd a2db7a8eac51db532cecc1bd4a034670/
atom@5a72c858eef2:~/a2db7a8eac51db532cecc1bd4a034670$ mkdir -p ~/.atom/
atom@5a72c858eef2:~/a2db7a8eac51db532cecc1bd4a034670$ cp config.cson ~/.atom/
atom@5a72c858eef2:~/a2db7a8eac51db532cecc1bd4a034670$ ${ATOM_SCRIPT_PATH} --enable-electron-logging --test test-spec.js
[37:0309/055308.978217:INFO:CONSOLE(12)] "Version: 1.25.0-beta3", source: /home/atom/a2db7a8eac51db532cecc1bd4a034670/test-spec.js (12)
[37:0309/055308.979247:INFO:CONSOLE(13)] "1-1: 5", source: /home/atom/a2db7a8eac51db532cecc1bd4a034670/test-spec.js (13)
[37:0309/055308.979992:INFO:CONSOLE(14)] "1-2: 5", source: /home/atom/a2db7a8eac51db532cecc1bd4a034670/test-spec.js (14)
.[37:0309/055309.080661:INFO:CONSOLE(19)] "2-1: 9999", source: /home/atom/a2db7a8eac51db532cecc1bd4a034670/test-spec.js (19)
[37:0309/055309.081335:INFO:CONSOLE(20)] "2-2: 9999", source: /home/atom/a2db7a8eac51db532cecc1bd4a034670/test-spec.js (20)
.

Finished in 0.387 seconds
2 tests, 0 assertions, 0 failures, 0 skipped

atom@5a72c858eef2:~/a2db7a8eac51db532cecc1bd4a034670$
```

**Comment by maxbrunsfeld** [comment]
Oh wow that's really bad. Thanks so much for the report @t9md. Fixing now.
