### ISSUE TITLE
Linux only: editor crashes with rm -r node_modules

### ISSUE THREAD

**Issue by sgehrman** [atom/atom#16911]
I have the editor open, no tabs from node_modules showing.

If I sudo rm -r node_modules/

The editor crashes.   Also I have to do sudo, so not sure if atom has these files open when it shouldn't?  Windows and other systems didn't need sudo to remove node_modules.

I'm on Debian now.

**Comment by daviwil** [comment]
Seems like another issue caused by the old pathwatcher, @50Wliu's changes in tree-view may resolve this down the line.

**Comment by senyaak** [comment]
Have the same issue
`rm -rf node_modules` and the editor crashes. 
atom-typescript and tree-view plugins are used at the moment, and almost sure that atom-typescript is the one who caused it.
but I think the plugins shouldn't crash atom :)

**Comment by hbschr** [comment]
same issue w/ v1.34.0.
disabling `atom-typescript` didn't help.
disabling `tree-view` didn't help.
