### ISSUE TITLE
Escaped emoji strings not appearing in search results

### ISSUE THREAD

**Issue by revelt** [atom/atom#16912]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Emoji, escaped into two characters, for example blue cap `\uD83E\uDDE2`, are not appearing in string searches. If you have the actual un-escaped emoji, _they_ appear instead. This means, it's impossible to search for escaped emoji codes, for example, `\uD83E\uDDE2` as text.

### Steps to Reproduce

Notice how I search for `\uD83E\uDDE2` but cap emoji gets selected. The characters `\uD83E\uDDE2` never even get selected, I can't "cycle-through" them among the search results.

![emoji_chars](https://user-images.githubusercontent.com/8344688/37195537-2861e37e-236b-11e8-9e86-2509f20a6528.gif)

I guess correct behaviour would be "2 results found" in the screengrab above...

**Comment by 50Wliu** [comment]
It looks like we're not escaping hard enough.  Can you please reopen this on [atom/find-and-replace](https://github.com/atom/find-and-replace)?

**Comment by revelt** [comment]
Sure! Thanks!
