### ISSUE TITLE
After the "Xray Editor" appeared, "Atom Editor" is about to give up?

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#16939]
After the `Xray Editor` appeared, `Atom Editor` is about to give up?

**Comment by rsese** [comment]
Thanks for reaching out - as explained in the project  [README](https://github.com/atom/xray#xray), Xray is an experiment based off of the team's experience working with Atom and that's all right now.  The future of Xray will develop over time and you can follow the [updates](https://github.com/atom/xray#updates) to see how things progress if you'd like.
