### ISSUE TITLE
Idea: Hackable Web Browser

### ISSUE THREAD

**Issue by CleverSource** [atom/atom#16938]
Please make a hackable web browser

**Comment by Arcanemagus** [comment]
Thanks for the submission!

There are several different packages that allow previewing HTML code as you are editing it, perhaps one of those will fit what you are looking for?

This is not something that is within the scope that we have have envisioned for this project. For that reason, I'm going to close this. If the existing community packages don't satisfy the idea you have here and you need help building this as a package, please check out the [Atom Flight Manual section on publishing your own packages](https://flight-manual.atom.io) and feel free to ask any questions you have on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the [Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638).

Thanks again for contributing to Atom :+1:
