### ISSUE TITLE
"Panes > Split Down" doesn't split tabs if they are single-click-opened (italic tab label)

### ISSUE THREAD

**Issue by revelt** [atom/atom#16934]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When you single click on file tree on left sidebar, that file tab's label is in italic and tab doesn't stay opened, but another single-clicked file replaces it. I'm talking about this mode in particular, **as opposed to** file being double-clicked, when tab's label is in normal font.

When single-clicked, it's not possible to split down the pane with a file open. If it was double-clicked, it works as intended. While example is shown with an image, any file will not pane-split if it was opened by single-clicking (its tab's label was in italic).

![split](https://user-images.githubusercontent.com/8344688/37275412-04285cc2-25d7-11e8-9d9e-7be386e721c0.gif)

### Steps to Reproduce

1. Single-click on any file on the file Tree View panel. Make sure newly-created tab's label is in italic (you didn't double-click).
2. Activate menu item: View > Panes > Split Down

**Expected behavior:** Window splitting accordingly and file being open.

**Actual behavior:** Tree View sidebar splits instead with no file opened in newly-created split.

**Reproduces how often:** 100%

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
MacOS   : 10.13.3

**Comment by rsese** [comment]
Thanks for the report!  I believe this is expected behavior - this is happening because the tree view has focus on single click pending pane items (e.g. so you can rename the file you single clicked in the tree view).  In addition to double clicking the file so it isn't a pending pane item anymore I tried the code Michelle mentioned in https://github.com/atom/tree-view/pull/617#issuecomment-255240605 and that also worked.

**Comment by revelt** [comment]
Aha! Thanks!
