### ISSUE TITLE
Doesn't Ask for SSH Password 

### ISSUE THREAD

**Issue by lbunge** [atom/atom#16945]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom doesn't ask for ssh password when cloning from Github. Doesn't clone or throw errors - Dies silently.

### Steps to Reproduce

1. Have ssh key with password
2. Attempt to clone from GitHub using ssh
3. Be sad

**Expected behavior:** It clones repo

**Actual behavior:** Dies silently

**Reproduces how often:** 100%

### Versions

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by TimvdLippe** [comment]
I think this is an issue for https://github.com/atom/github instead

**Comment by lbunge** [comment]
Whoops, thanks!
