### ISSUE TITLE
Atom freezes in certain menus

### ISSUE THREAD

**Issue by EHProgHat** [atom/atom#16947]
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom works fine normally, but when i go into the themes or install menu it instantly freezes until i force close it. I've checked the board and cant find anything, but if I missed something, please link it!

### Steps to Reproduce

1. Go into the themes menu
2. It freezes

**Expected behavior:** 
It lets me go into the menu
**Actual behavior:** 
It freezes
**Reproduces how often:** 
100%
### Versions

1.24.1(It was installed today)

**Comment by rsese** [comment]
Thanks for the report - you don't mention what operating system you're running in the `Versions` section, can you share which OS and version you're running?

Also, was there any difference when you ran in safe mode or did it freeze in the exact same way?

Lastly, when you say "Go into the themes menu", are you just clicking `Settings > Themes` or are you clicking on one of the theme dropdowns (UI or Syntax)?

**Comment by EHProgHat** [comment]
im running windows 10, safe mode doesnt make a difference, and im just clicking it through settings

**Comment by rsese** [comment]
Hmmm, do you happen to use a community UI and/or syntax theme?  If so, do you notice if it's enabled even when you're in safe mode?

**Comment by rsese** [comment]
(I couldn't reproduce on 1.24.1 on Windows 10).

**Comment by EHProgHat** [comment]
I just downloaded it, i was trying to add a theme(I dont have one yet), and thats when it started crashing. Ive tried deleting and reinstalling it multiple times, the problem persists in safe mode too. Could it be my computer model?

**Comment by rsese** [comment]
> Could it be my computer model?

Anything's possible but there are more things we can try - not sure if you've tried everything in the debugging documentation, but have you also tried clearing saved state:

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

And resetting to factory defaults?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by EHProgHat** [comment]
i dont know exactly whhy but when i installed and uninstalled it like 7 times it started working, sorry for the inconvienence
