### ISSUE TITLE
Build fails: Error: ENOENT: no such file or directory, open './xregexp'

### ISSUE THREAD

**Issue by capouch** [atom/atom#16941]
### Description

Fresh checkout from master branch won't build, fails when generating snapshot with ENOENT  looking for ./xregexp.

### Steps to Reproduce

1. Checkout master branch
2. git pull
3. ./script/build --install

**Expected behavior:** 
Clean build, run atom, be happy

**Actual behavior:**
Build aborts with ENOENT error

**Reproduces how often:**
Always; tried "./script/clean first, still bombs

### Additional Information
Fails when generating snapshot:

`Application bundle created at /home/brianc/atom/out/atom-1.26.0-dev-00d72a95d-amd64
Generating snapshot script at "/home/brianc/atom/out/startup.js" (1)Error: ENOENT: no such file or directory, open './xregexp'
  at Object.fs.openSync (fs.js:663:18)
  at Object.fs.readFileSync (fs.js:568:33)
  at /home/brianc/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:26:27
  at Generator.next (<anonymous>:null:null)
  at step (/home/brianc/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:191)
  at /home/brianc/atom/script/node_modules/electron-link/lib/generate-snapshot-script.js:3:361
  at <anonymous>:null:null
`

Linux Slackware 14.2-current, running as a VM under VirtualBox 5.2.8

**Comment by rsese** [comment]
Thanks for the report!  Not sure if you pulled from master again recently but I believe this was fixed in https://github.com/atom/atom/pull/16942.  

We'll go ahead and close for now but if you still have problems after pulling let us know.

**Comment by capouch** [comment]
All is good, thanks to the team for the prompt fix!!
