### ISSUE TITLE
Please, add Use Both button

### ISSUE THREAD

**Issue by flypaper0** [atom/atom#16949]
Please, add Use Both button. It will be very useful 

<img width="600" alt="screen shot 2018-03-14 at 17 20 21" src="https://user-images.githubusercontent.com/5384197/37407972-27eb8248-27ac-11e8-8a53-ae5a72df560c.png">

**Comment by rsese** [comment]
Thanks for the suggestion! This should go in https://github.com/atom/github but I see it's already referenced in https://github.com/atom/github/issues/519 (see https://github.com/atom/github/issues/519#issuecomment-280844010) where folks are talking about this particular UI in general.  I'll go ahead and close as a duplicate and you can subscribe there if you'd like.
