### ISSUE TITLE
Wrong python folding with tree-sitter

### ISSUE THREAD

**Issue by gliviu** [atom/atom#16959]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Folding python code is not working properly when tree-sitter is activated. See case below.

### Steps to Reproduce
1. Set core.useTreeSitterParsers: false in config.cson and restart Atom
2. Create new python file with this content
```python
for cl in reversed(range(1, len(layers))):
    pl = cl-1
    nl = cl+1
```
3. Fold the first line

**Expected behavior:**
![image](https://user-images.githubusercontent.com/8597812/37526387-dcac5504-2937-11e8-9003-2974e44edb01.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/8597812/37526306-a7b062b4-2937-11e8-9bf0-d91082ccd40e.png)

**Reproduces how often:**
Always

### Versions
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.14
git 2.16.1.windows.1
visual studio 2015
Windows 10

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by maxbrunsfeld** [comment]
Thanks for the report! It looks like CRLF line endings are causing some problem for the python parser.

**Comment by maxbrunsfeld** [comment]
This will be fixed in Atom 1.25.1.

**Comment by Arcanemagus** [comment]
Looks like I need to refresh before posting, thanks for catching the `CRLF` line endings @maxbrunsfeld 😆.

**Comment by gliviu** [comment]
It is actually useTreeSitterParsers: true. Wrong copy/paste after I made sure it works with old version.
Sorry about that.

**Comment by maxbrunsfeld** [comment]
Hey, just an update on this - a fix will ship in Atom 1.26.0-beta1, or in 1.26.0 if you want to wait for the stable release.

**Comment by gliviu** [comment]
Waiting for beta to give it a try

**Comment by maxbrunsfeld** [comment]
Ok, 1.26.0-beta1 is out.

**Comment by gliviu** [comment]
I've tried with this piece of code
```python
for cl in reversed(range(1,
                         len(layers))):
    def f(a1:int,
          b1:List[int]):
        for cl in reversed(range(1,
                                 len(layers))):
            def f(a1:int, b1:List[int]):
                p2 = cl-1
                n2 = cl+1
        p2 = cl-1
        n2 = cl+1
        for cl in reversed(range(1, len(layers))):
            def f(a1:int, b1:List[int]):
                p2 = cl-1
                n2 = cl+1
    pl = cl-1
    nl = cl+1
```
and I've seen no mistake. We can consider this closed for good 👍
