### ISSUE TITLE
[Atom 1.25] Unclear documentation wrt TextBuffer.setTextInRange undo:"skip" option deprecation

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#16956]
There are multiple places where `undo:"skip"` option is accepted, namely (at least from what I could find):

- [`TextEditor.insertText`](https://atom.io/docs/api/v1.25.0/TextEditor#instance-insertText) (references `Selection.insertText`)
- [`TextEditor.pasteText`](https://atom.io/docs/api/v1.25.0/TextEditor#instance-pasteText) (references `Selection.insertText`)
- [`TextEditor.setTextInBufferRange`](https://atom.io/docs/api/v1.25.0/TextEditor#instance-setTextInBufferRange)
- [`Selection.insertText`](https://atom.io/docs/api/v1.25.0/Selection#instance-insertText)
- [`TextBuffer.setTextInRange`](https://atom.io/docs/api/v1.25.0/TextBuffer#instance-setTextInRange) (the deprecation warning is only here)
- [`TextBuffer.insert`](https://atom.io/docs/api/v1.25.0/TextBuffer#instance-insert)
- [`TextBuffer.append`](https://atom.io/docs/api/v1.25.0/TextBuffer#instance-append)

It is not immediately clear whether the deprecation notice applies to every instance (which I would expect), or only to `TextBuffer.setTextInRange`. If it's the former, deprecation notice isn't very visible. If it's the latter, it would seem to be too specific to be useful.

**Comment by Ben3eeE** [comment]
Refs https://github.com/atom/text-buffer/pull/282

**Comment by lee-dohm** [comment]
@maxbrunsfeld Can you clarify the documentation on this?
