### ISSUE TITLE
Config missing from Atom 1.25 docs

### ISSUE THREAD

**Issue by GlenCFL** [atom/atom#16955]
The entire Config class is missing from the [Atom 1.25 documentation](https://atom.io/docs/api/v1.25.0/Config), whereas it was present in the [Atom 1.24 documenation](https://atom.io/docs/api/v1.24.0/Config).

A quick search of the `atom-api.json` file for the beta indicates that it's missing there too.

**Comment by GlenCFL** [comment]
The v1.26 release branch doesn't have the commit that fixed this on the v1.25 release branch (#16957). Config will be missing again with the 1.26 release unless that commit is cherry picked.

@daviwil

**Comment by daviwil** [comment]
Thanks for catching that, @GlenCFL!  Cherry-picked that commit over to 1.26-releases.
