### ISSUE TITLE
[BUG]: Left panel code window not maximized (invisible artifacts?)

### ISSUE THREAD

**Issue by dsanalytics** [atom/atom#16969]
When I open Atom, code left panel window is not being maximized. After I maximize it manually by dragging edges to the right and bottom, window is back not maximized next time I open Atom. No errors or crashes and it happens every time. It almost seems as if that there are some artifacts (e.g. small pixel-size windows) that Atom tries to display while I don't see them - not sure though. Symptoms are the same with either dark or light themes. Did not have that before - it started some time back.

As a workaround, i.e. before the fix, is there a way to flash config file holding last window positions - thus forcing Atom to recreate it from scratch? If so, can you advise how to do it? Thanks.

Atom v1.23.3
Windows 7 and 10 64bit HP (two machines)

![atom-bug-code-window-not-maximized](https://user-images.githubusercontent.com/32625394/37552042-151e6fb0-297b-11e8-923d-a9d37c01a8d6.png)

**Comment by rsese** [comment]
Thanks for the report - the issue template is super helpful and gives us a lot of information that's helpful when looking at issues.  Did you try any of the debugging steps, in particular starting Atom in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) or [clearing saved state](https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state)?   

> is there a way to flash config file holding last window positions - thus forcing Atom to recreate it from scratch?

Clearing saved state should do this.

> Atom v1.23.3

The latest stable release of Atom is 1.25 so I would also recommend updating to the latest version if you can.

**Comment by dsanalytics** [comment]
Thx - executing `atom --clear-window-state` from the command line solved the issue.
