### ISSUE TITLE
Uncaught Can't find (document).ready(function () {  $('.click-me').on("click", EventClick);...

### ISSUE THREAD

**Issue by v4rldsfader** [atom/atom#16966]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find (document).ready(function () {
  $('.click-me').on("click", EventClick);

  function EventClick() {
    go();
  } file

```
At C:\Users\Alexander\AppData\Local\atom\app-1.25.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:959

undefined
```

### Commands

```
  2x -7:01.7.0 core:move-up (input.hidden-input)
     -7:01.1.0 editor:move-to-end-of-word (input.hidden-input)
     -7:00.2.0 core:save (input.hidden-input)
  8x -6:59.4.0 core:undo (input.hidden-input)
     -6:56.9.0 core:save (input.hidden-input)
  2x -6:51.4.0 editor:newline (input.hidden-input)
     -4:12.4.0 core:paste (input.hidden-input)
  3x -3:44.7.0 core:undo (input.hidden-input)
     -3:42.6.0 core:select-right (input.hidden-input)
     -3:35.3.0 core:save (input.hidden-input)
     -0:27.3.0 editor:toggle-line-comments (input.hidden-input)
     -0:24.7.0 core:undo (input.hidden-input)
     -0:17.4.0 emmet:encode-decode-data-url (input.hidden-input)
     -0:15.3.0 editor:consolidate-selections (input.hidden-input)
     -0:15.3.0 core:cancel (input.hidden-input)
     -0:06.1.0 emmet:encode-decode-data-url (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.2.0 
emmet 2.4.3 
ftp-remote-edit 0.12.11 
gitlab 0.1.3-7 
language-ethereum 0.3.9 
minimap 4.29.8 
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

All new issues now require steps to reproduce (also called "repro steps") the problem or the behavior you wish to see in Atom. We do this so we can be certain that we are understanding what it is you're describing and don't prematurely close the issue or implement the wrong feature. If you need help writing detailed repro steps, please see the [How Can I Contribute? section of the Atom CONTRTIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16966#issuecomment-373847919. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
