### ISSUE TITLE
Weird Syntax Highlighting after update (HTML & Python)

### ISSUE THREAD

**Issue by Hecsall** [atom/atom#16967]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I have a strange syntax highlighting bug, after updating atom i get strange colors in my HTML and Python (see images)

<img width="403" alt="schermata 2018-03-16 alle 23 57 28" src="https://user-images.githubusercontent.com/10171006/37548411-055b4204-2978-11e8-9611-dd524e5457bf.png">

<img width="393" alt="schermata 2018-03-17 alle 00 00 34" src="https://user-images.githubusercontent.com/10171006/37548420-0ce75044-2978-11e8-852b-64226da2ea47.png">

<img width="487" alt="schermata 2018-03-17 alle 00 11 58" src="https://user-images.githubusercontent.com/10171006/37548422-11ace9d6-2978-11e8-8262-c9d5bf93e781.png">

### Steps to Reproduce

Not really sure, it started happening after the last update
See code samples:

**HTML**
```
<div class="test" style="test"></div>
```

**Python**
```
def somePython(something):
        test = OneTwo(foo.BAR)
	if foo.bar == 'SPAM':
		something = eggs.bacon['pizza']
		return render(something, 'pizza.html')
```

**Expected behavior:** Atom rendering the right colors

**Actual behavior:** Colors rendering different, it seems like it's another language hightlighting (i already checked the language selector on the bottom right)

**Reproduces how often:** Always, even after disabling every plugin, no custom themes installed, and even moving the .atom folder to .atom-backup and restarting it.

### Versions
OS: macOS 10.12

$ atom --version
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.10
git 2.14.3

**Comment by Arcanemagus** [comment]
Your HTML example is to be expected, if you place the cursor within the "oddly" colored `"test"` you can see that it is bringing in the CSS styling:
![image](https://user-images.githubusercontent.com/427137/37548771-7a0299b8-2937-11e8-8033-a6360807d901.png)

Could you describe what in the Python example wasn't expected?

**Comment by Hecsall** [comment]
@Arcanemagus for the HTML part my fault, i didn't noticed that atom "grays-out" wrong spelled css attributes in html, so i thought it was highlighting wrong.

For Python all those colors changed suddently after the update, i dont really know if it's the correct highlighting or not, i've been using atom for more than 2 years and today i noticed that something in the highlighting was "strange". Sorry if this feels stupid, but i'm really confused about this

**Comment by Arcanemagus** [comment]
It looks like `language-python` got [_several_ updates](https://github.com/atom/language-python/compare/v0.45.6...v0.49.2) in Atom v1.25.0. Since nothing looks out of place there from what I can see I'm assuming that it's simply recognizing things better than it was before.

I'm going to go ahead and close this, but if you have any further questions or notice anything wrong don't hesitate to reach out!

**Comment by 50Wliu** [comment]
@Hecsall if you don't like the new Python highlighting please create a new topic on [Discuss](https://discuss.atom.io) - I'd appreciate your feedback.
