### ISSUE TITLE
Native menus do not scale

### ISSUE THREAD

**Issue by alexwhitman** [atom/atom#16973]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The native menus (right click and menu bar) font size doesn't scale with the rest of the desktop when using the fonts "Scaling Factor" setting in Gnome's Tweaks application.

Scale Factor: 1
![atom-scale-1](https://user-images.githubusercontent.com/422013/37553516-8eadbc64-29c1-11e8-91e0-2949c13f9787.png)

Scale Factor: 0.75
![atom-scale-075](https://user-images.githubusercontent.com/422013/37553521-96aa054e-29c1-11e8-94ef-27724c9c3895.png)

Notice how the "Activities" and "Tweaks" text is smaller when the scale factor is set to 0.75 but Atom's menu bar doesn't change.

This is **NOT** on a HiDPI display (I know there are other issues around HiDPI).  The screen resolution is 1920x1200.

### Steps to Reproduce

1. Open Atom, note the size of the menu bar text.
2. Close Atom
3. Open the Tweaks application -> Fonts
4. Set the Scaling Factor to something < 1
5. Open Atom, note the menu bar text is the same size as in step 1

**Expected behavior:** [What you expect to happen]

Menu font size should scale appropriately.

**Actual behavior:** [What actually happens]

Menu font size isn't scaled.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time.

### Versions

```
$ atom --version
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.14
git 2.16.2
```

I'm seeing this on both Ubuntu 17.10 and Ubuntu 18.04 (pre-release).

**Comment by gnurush1** [comment]
If this issue hasn't already been assigned to someone else, I could take a look and see if I could either fix the problem or find a workaround solution.

**Comment by lee-dohm** [comment]
We don't assign issues, so feel free to take a look :grinning:

**Comment by gnurush1** [comment]
Sure thing

**Comment by daviwil** [comment]
@gnurush1 did you have any luck looking into this?

**Comment by gnurush1** [comment]
Not quite, I know where the native menus are defined and how they could be changed, but I'm not quite sure how to find the font size given by Gnome.

**Comment by daviwil** [comment]
Hey @alexwhitman, we're using Electron 2.0 in more recent releases of Atom (1.28.0 and above).  This version of Electron uses GTK 3.0, so I'm thinking it might actually resolve this issue for you.  Can you let us know whether this is the case?

**Comment by alexwhitman** [comment]
@daviwil I've tested with 1.29.0 and the menus are still not taking the scale factor in to account.
