### ISSUE TITLE
RPM: Stop requiring LSB altogether

### ISSUE THREAD

**Issue by cobexer** [atom/atom#16977]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Atom requires LSB to be installed on my system. LSB is very obsolete see for example https://bugzilla.opensuse.org/show_bug.cgi?id=1071688 openSUSE Tumbleweed currently has LSBv4 but can't provide LSBv5 because that would require adding obsolete unmaintained insecure packages IIUC.
Introduced in https://github.com/atom/atom/commit/f919bc40dc033c914dcec014597c7b59da1617c5 DEB packages only got a recommends while RPM packages got a requires. Please stop relying on LSB or at least downgrade to a Recommends only.

### Steps to Reproduce
1. `docker run --rm opensuse:tumbleweed sh -c "zypper in -y curl && curl -L -o atom.rpm https://atom.io/download/rpm && zypper in -y -f atom.rpm"`

**Expected behavior:** does not pull in unnecessary dependencies.

**Actual behavior:** atom pulls in for example Qt3 o.O

**Reproduces how often:** Always

### Versions
every atom version since https://github.com/atom/atom/commit/f919bc40dc033c914dcec014597c7b59da1617c5 (0.202?)
OS: openSUSE Tumbleweed 20180308 (yeah I need to update... but qt3 dep is broken...)

### Additional Information
Why I (tried to) killed the LSB, Didier Raboud, DebConf 17: https://debconf17.debconf.org/talks/181/ Slides: https://annex.debconf.org/debconf-share/debconf17/slides/181-why_i_tried_to_kill_the_lsb.pdf

Debian dropping the Linux Standard Base: https://lwn.net/Articles/658809/

Tumbleweed is missing the lsb5 package: https://bugzilla.opensuse.org/show_bug.cgi?id=1071688

**Comment by jcayouette** [comment]
Agreed this is most annoying. :) A fix will be most appreciated!
