### ISSUE TITLE
No language showing + atom tooltip

### ISSUE THREAD

**Issue by cloudbluedigital** [atom/atom#16980]
Hi guys so I am using Atom with kali linux. However when I open a file, at the bottom it doesn't show me what language it is and if you look on the middle of the screen you can see atom 'tooltip' which usually appers when no files are opened

Any way to fix this?

![screenshot from 2018-03-18 18-30-29](https://user-images.githubusercontent.com/22678404/37569484-e3d41584-2ada-11e8-919d-c8a7ae704ac4.png)

**Comment by rsese** [comment]
Thanks for the report - can you update your issue with the issue template filled out and let us know if any of the debugging steps helped or not?

Also, can you confirm that you installed Atom with the official .deb from https://atom.io?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/16980#issuecomment-374367490. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
