### ISSUE TITLE
editor.scan, editor.scanInBufferRange skip too many rows

### ISSUE THREAD

**Issue by t9md** [atom/atom#16983]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is regression introduced in v1.25.0.
Following editor's methods skips empty rows where it shouldn't.

- `editor.scan` , `editor.backwardsScanInBufferRange` and `editor.scanInBufferRange`

```javascript
const e = atom.workspace.getActiveEditor()
e.scanInBufferRange(/^[\t\r ]*$/g, e.buffer.getRange(), event => console.log(event.range.toString()))

```

Here is result comparison between v1.24.1 and v1.25.0.

<img width="1318" alt="comparison" src="https://user-images.githubusercontent.com/155205/37588115-9cd292d0-2ba4-11e8-866c-308010b3e941.png">

v1.26.0-beta0: skips too many rows.
v1.25.0: skips too many rows.
v1.24.1: stop at each empty rows.

### Steps to Reproduce

1. Open empty editor create 5 empty rows
2. Execute code blow in chrome dev console and see which ranges are found by `scanInBufferRange`

```javascript
const e = atom.workspace.getActiveEditor()
e.scanInBufferRange(/^[\t\r ]*$/g, e.buffer.getRange(), event => console.log(event.range.toString()))
```

**Expected behavior:** [What you expect to happen]

Finds all beginning of line(do not skip some empty rows).
In other word, make it behave as it was in v1.24.1.

**Actual behavior:** [What actually happens]

Skips empty rows which row is next row of matched range.

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

v1.26.0-beta0: skips too many rows.
v1.25.0: skips too many rows.
v1.24.1: stop at each empty rows.

### Additional Information

- This issue breaks some vim-mode-plus's motion.

https://github.com/t9md/atom-vim-mode-plus/issues/1047

**Comment by smashwilson** [comment]
It turns out any zero-length regex match at the end of a line would trigger this. Looking good now:

<img width="729" alt="screen shot 2018-03-22 at 3 48 01 pm" src="https://user-images.githubusercontent.com/17565/37794633-70fbe0e4-2de8-11e8-8617-a52919a8c344.png">

**Comment by t9md** [comment]
Thanks for quick fix @smashwilson!!

**Comment by t9md** [comment]
@smashwilson
Any plan what branch this fix will come in? I hope this provided to stable(v1.25.0).
