### ISSUE TITLE
Squirrel.exe gets quarantined as a virus threat with each ATOM update by Cylance Protect

### ISSUE THREAD

**Issue by wurmtal868** [atom/atom#16986]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Each time ATOM,IO gets receives an update squirrel.exe gets quarantined by Cylance Protect as a suspicious threat 

### Steps to Reproduce

1. Check if you have Cylance Protect installed: 
![cylance](https://user-images.githubusercontent.com/32965910/37595864-909e66ee-2b7a-11e8-97b5-7bbeb9f590f1.png)

2. Apply an update
3. Wait for the popup:
![cylance_threat](https://user-images.githubusercontent.com/32965910/37596052-3247470e-2b7b-11e8-8d9b-728c29ed7f03.png)

**Expected behavior:** 
I expect that the updater does not behave the like virus 

**Actual behavior:** 
Help>About shows now ATOM version 1.24.1 x64 while the command line still shows version 1.24.0
I have folders for the latest and all previous installed version of ATOM on my system.

**Reproduces how often:** 
I have seen this on the updates from 1.23.3 -> 1.24.0 and 1.24.0 ->1.24.1

### Versions
I'm using on two systems one with Windows 7 the other with Windows 10

atom --version:
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm --version:
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.14
git
visual studio

### Additional Information

It seems that squirrel.exe has different check sums although the file size has not changed from the previous version. That may makes it look like a mutating virus.

**Comment by Floakey** [comment]
This is expected from NGAV products like Cylance/Carbon Black/whatever. They look at not just the signatures (sha256 hash in most cases) but the behavior of the application, processes started, commands run, invocations, etc. There is not much a developer can do to prevent this. Until the ngav provider has had a chance to scan and whitelist the application, this will continue to happen. You'll either have to add a policy exclusion for the path the .exe runs from or whitelist the process itself.

**Comment by wurmtal868** [comment]
In our enterprise environment I'm not in a position to get white list any version of squirrel.exe.
The version that came with 1.24.0 was quarantined and white listed on request. I cannot get an exclude for the upper level path. So the update to version 1.24.1 was quarantined again. What else can I do?

**Comment by Floakey** [comment]
My suggestion being wait and try again tomorrow.

**Comment by lee-dohm** [comment]
I can understand that this is frustrating. However, attempting to convince the myriad anti-virus systems that our installer is safe is not something that we're going to be devoting any significant time to. Figuring out a system that allows us to easily install, dynamically update, _and_ isn't flagged by all anti-virus systems just isn't our area of expertise or what we're interested in working on. Since this isn't something that we're going to prioritize, I'm going to close this.

**Comment by TheGoobertron** [comment]
If squirrel.exe was signed it would be much easier for people to whitelist this using certificate based whitelisting. That way future iterations will not be quarantined by the AV.

**Comment by dancapper** [comment]
Seconding the above - this is a major issue in many corp environments now - if the exectables were signed then it's easy to just trust the certificate and avoids this problem

**Comment by TyrelCB** [comment]
Downloading the Zip, Extracting, and running from there works like a charm if your running into issues with the install due to Cylance.
