### ISSUE TITLE
Python highlighting problems

### ISSUE THREAD

**Issue by MikeTam1021** [atom/atom#16989]
It seems like overnight Atom decided to change all it's python highlighting to be more colorful, and also more confusing.

I have things that are now inconsistently highlighted with instances uncolored in one case, and red in the next. import is purple in one place and red in another. I am importing from modules and it is red while my other imports are white.

This lack of consistency is disturbing and I would like to change my system back. I do not appreciate these auto-updates, many of which have been repeatedly crashing and opening multiple versions of Atom on my machine. 

How can I revert my version and stop this behavior from Atom?

**Comment by maxbrunsfeld** [comment]
Do you have the new experimental highlighting mode enabled? It's called Use Tree-sitter Parsers in the settings view.

**Comment by MikeTam1021** [comment]
Max, I didn't willingly change anything about my system. It happened to my colleague's computer as well this morning without his knowing. He did not like it either. I will check now.

**Comment by MikeTam1021** [comment]
![screen shot 2018-03-19 at 11 55 45 am](https://user-images.githubusercontent.com/7306740/37609985-80b34afa-2b6c-11e8-9b5d-14a8e4f463ae.png)

**Comment by MikeTam1021** [comment]
No it is unselected. When I disable language python I get no color, so it looks like a language python issue

**Comment by maxbrunsfeld** [comment]
@MikeTam1021 Ok, thanks. We'll need more specific information in order for this issue to be actionable. Can you post screenshots that show the highlighting that you don't like and explain in detail the problems with the new highlighting?

**Comment by Arcanemagus** [comment]
The `language-python` package received several updates in version included in v1.25.0, including many changes to how strings are parsed. Since we've confirmed you aren't using the Tree-sitter parser can you file an issue on [language-python](https://github.com/atom/language-python) with examples of code you feel isn't being highlighted correctly or consistently?

Thanks for taking the time to contribute!

**Comment by MikeTam1021** [comment]
Is there a way for me to easily modify the way `language python` is being used in Atom?

I will file an issue with `language-python`, but I think this should be an area of concern for Atom. It is quite possible that your `language-python` is not for python at all but javascript or some other non-python use case.

Just open up literally any python package in Atom and it should be obvious if you compare it with any other text editor or previous versions of Atom. Here's a shot from pandas
![screen shot 2018-03-20 at 9 07 48 am](https://user-images.githubusercontent.com/7306740/37659525-3a6a6f9e-2c1e-11e8-88b0-7a9f5a88474f.png)

**Comment by Ben3eeE** [comment]
@MikeTam1021 This is an intentional change in Atom 1.25. It seems you can revert back to how it was before using the stylesheet posted in https://discuss.atom.io/t/syntax-highlighting-different-after-reboot/53453/7?u=ben3eee

**Comment by MikeTam1021** [comment]
Thanks, I was able to remove some of the damage with the link!
