### ISSUE TITLE
Git Push up arrow does nothing

### ISSUE THREAD

**Issue by Pageboy** [atom/atom#16991]
### Description

Since update to 1.25 at the bottom of the GIT panel after commit message, there is an up arrow. Rolling over this I get `1 commit ahead of upstream` but the up arrow does nothing. 

Previous to the update, this then pushed the update to GitHub.

### Steps to Reproduce

1. Make a change
2. Stage the changes
3. write a commit message

**Expected behavior:** Should see changes being pushed with animated GitHub logo

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

1.25

This is MAC version of Atom 1.25

**Comment by rsese** [comment]
This issue was moved to atom/github#1360
