### ISSUE TITLE
Feature needed: Locate the current file in the project tree.

### ISSUE THREAD

**Issue by viccon** [atom/atom#17009]
Feature needed: Locate the current file in the project tree.

Just like what Intellij IDEA does:

![image](https://user-images.githubusercontent.com/8813556/37751904-148cc7aa-2dd0-11e8-921e-81cbb945f6fe.png)

**Comment by lee-dohm** [comment]
This already exists as the command `Tree View: Reveal Active File`. It can be found in the Command Palette.
