### ISSUE TITLE
No results found for 'április' in lowercase

### ISSUE THREAD

**Issue by borzaka** [atom/atom#17017]
### Description

I was looking for a word `április` in a PHP document. No result found, but I know there is, but it's in uppercase: `Április`. Atom wasn't able to find it.
Match Case was not enabled.

### Steps to Reproduce

1. create a document with `április` and `Április` words in it
2. search for `április`
3. only 1 result found, the lowercase version

**Expected behavior:** find the uppercase version of `április` as well

**Actual behavior:** only the lowercase version was found

**Reproduces how often:** 100%

### Versions

v1.25.0

### Additional Information

`Április` is a hungarian word for April.

![image](https://user-images.githubusercontent.com/1230402/37830838-c3c410a6-2ea3-11e8-8d2c-e64cf0e8cd8c.png)

**Comment by rsese** [comment]
This issue was moved to atom/superstring#56

**Comment by rsese** [comment]
Moved based on some comments from the other maintainers, thanks for the report!
