### ISSUE TITLE
atom hangs several seconds after creating newline

### ISSUE THREAD

**Issue by davidak** [atom/atom#17011]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

see title

### Steps to Reproduce

1. open atom
2. open textfile with **over 9000** lines of text
3. select random line
4. hit enter 5 times to create newlines (same with deleting lines or pasting text)
5. hangs for 5-8 seconds...

**Expected behavior:** responsive editor

**Actual behavior:** hanging editor

see video: https://youtu.be/YZ_lDwaVTdU

**Reproduces how often:** 100%

### Versions

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 
git 2.15.0

NixOS 17.09.3159.c665fcca9e7

### Additional Information

[CPUProfile.tar.gz](https://github.com/atom/atom/files/1837323/CPUProfile.tar.gz)

Sadly atom is the best user friendly open source editor we have. It annoys me every day with it's poor performance.

My hope lies in xray or xi or even better a collaboration of the two projects https://github.com/atom/xray/issues/4

**Comment by Ben3eeE** [comment]
Thanks for the report!

* In the video you are not using safe mode `atom --safe`. Can you confirm that you observe this slowdown in safe mode as well?
* Does the slowdown go away if you disable the `spell-check` package?

**Comment by davidak** [comment]
@Ben3eeE thanks for the fast response!

I have tested and can reproduce it in safe mode.

Yeah, it is `spell-check`! Can you see that also in the attached cpuprofile?

**Comment by Ben3eeE** [comment]
@davidak Thanks again for the report!

The cpuprofile seemed to indicate that spell-check is the problem.

Would you mind reopening this issue in the https://github.com/atom/spell-check repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us half way :+1:
