### ISSUE TITLE
Automatic Snapcraft Builds

### ISSUE THREAD

**Issue by nickhagen** [atom/atom#17012]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
The official snap package listed on the snapstore always lags the release by up to a week or more:
https://snapcraft.io/atom

This documentation seems to indicate you can setup an automatic deployment from the Git releases:
https://docs.snapcraft.io/build-snaps/ci-integration

It appears from your issue tracking that you already have travis-ci working from this repo.

**Comment by daviwil** [comment]
Thanks @nickhagen!  I was reading up on this recently, it'd definitely be nice to create official Snaps for our releases.  If we did this, I'd also want to make sure we could do something similar with Flatpak so that we can cover the widest possible set of users.

**Comment by joshcangit** [comment]
This will make sure the Snap version is up to date because the version from the PackageCloud.io repository can sometimes be a few to several major versions ahead of the Snap version.
BTW, PackageCloud.io is down for now.
