### ISSUE TITLE
cannot run javascript in atom

### ISSUE THREAD

**Issue by arno2233** [atom/atom#17018]
I have used processing IDE and Xcode to run code without problems. I thought Atom would be the same, but it seems much more complicated. Currently I am trying to learn javascript and wanted an editor. I typed some lines of code and have atom runner installed. this is what I get:

Atom Runner: test
Unable to find command: node Are you sure PATH is configured correctly?
ENV PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
Error: spawn node ENOENT at exports._errnoException (util.js:1050:11) at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32) at onErrorNT (internal/child_process.js:367:16) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by daviwil** [comment]
Hi @arno2233, this sounds like an issue for the [Atom Runner](https://atom.io/packages/atom-runner) package which isn't a built-in Atom package.  I'd recommend filing this issue here:

https://github.com/lsegal/atom-runner

Thanks a lot!
