### ISSUE TITLE
getGrammars() ignores tree-sitter grammars

### ISSUE THREAD

**Issue by Aerijo** [atom/atom#17029]
### Description

Tree-sitter grammars will not be returned by the `getGrammars()` function of a `GrammarRegistry`. Instead, only TextMate grammars are returned.

```js
  // Extended: Get all the grammars in this registry.
  //
  // Returns a non-empty {Array} of {Grammar} instances.
  getGrammars () {
    return this.textmateRegistry.getGrammars()
  }
```

This causes issues with the `grammar-selector` package, which uses that function to build the list of available grammars. All tree-sitter grammars will be hidden from it.

Interestingly, if a regex grammar has the same `name` value as a tree-sitter one, then the regex grammar will appear in the list, but selecting it will apply the tree-sitter grammar

This can be seen by selecting `Python`, and noticing the green tick mark is not applied to it when you reopen the menu (in contrast to a solely regex grammar, with no tree-sitter alternative).

### Steps to Reproduce

1. Open the grammar menu and select `Python`
2. Open the grammar menu and look at the `Python` entry; there is no tick mark
3. Select `Python Console` (or any other regex-only grammar)
4. Open the grammar menu and see the tick mark next to `Python Console`

Alternatively, a grammar that is solely tree-sitter based will not appear at all in the selection menu, but will be automatically applied when the right file type is opened.

**Expected behavior:** [What you expect to happen]

Tick next to `Python` because it was selected

**Actual behavior:** [What actually happens]

No tick, because we were actually selecting the regex gramar and the tree-sitter one "intercepted" it as it was being applied. So the result is that the regex grammar was _not_ applied, and so no tick mark.

**Reproduces how often:**
100%

### Versions

```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0-beta0
python 2.7.10
git 2.14.3

Atom    : 1.26.0-beta0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

macOS 10.13.3
```

**Comment by lee-dohm** [comment]
@maxbrunsfeld is this by design? What happens when we have a language package without a first-mate grammar?

**Comment by maxbrunsfeld** [comment]
No, this is not by design. Up until now, I've been trying to avoid backward compatibility problems from returning Tree-sitter grammars when packages expect First-Mate grammars. But I think we need to figure out a solution to this before we enable Tree-sitter by default.

**Comment by ashthespy** [comment]
Was just going to open up a new issue cause I couldn't find the new `language-bundled-rust` grammar in the `grammar-selector` menu.  

Was a solution found - given that Tree-sitter has been enabled by default now?

**Comment by jakofranko** [comment]
I'm seeing the exact same thing. Was working on a language package that uses a tree-sitter grammar, updated to v1.34.0 today and stopped seeing my grammar in the modal dropdown. After a while of debugging I realized that the package-generator's language package was working by default, and sure enough, the package-generator creates a Text Mate language package by default. Realized that if I comment out the `type: 'tree-sitter'` line in my language.cson file, my grammar would show up in the menu again...

**Comment by Aerijo** [comment]
@ashthespy @jakofranko While my PR is being finished, adding the following to your `init.js` file should allow you to see TS grammars (or you can translate to CoffeeScript for `init.coffee`)
```javascript
atom.grammars.getGrammars = () => {
  return [...atom.grammars.textmateRegistry.getGrammars(), ...Object.values(atom.grammars.treeSitterGrammarsById)]
}
```

It will show apparent duplicates for lots of languages, so you might want to filter out TextMate grammars with the same name.

**Comment by caleb531** [comment]
> @ashthespy @jakofranko While my PR is being finished, adding the following to your init.js file should allow you to see TS grammars (or you can translate to CoffeeScript for init.coffee)
> ...
> It will show apparent duplicates for lots of languages, so you might want to filter out TextMate grammars with the same name.

On that note, I've modified @Aerijo's code to correctly filter out the duplicates, preferring the TreeSitter grammar if available and showing the default (First Mate) grammar otherwise. Note that this example is in CoffeeScript for your `init.coffee`; use [js2.coffee](http://js2.coffee/) to convert the code to ES6 (if you use `init.js` instead).

```coffee
# Override getGrammars to work around bug with tree-sitter grammars never
# applying; see:
# <https://github.com/atom/atom/issues/17029#issuecomment-457084440>
atom.grammars.getGrammars = ->
  allGrammars = atom.grammars.textmateRegistry.getGrammars()
  tsGrammars = Object.values(atom.grammars.treeSitterGrammarsById)
  combinedGrammars = tsGrammars.concat(allGrammars)
  combinedGrammarNames = combinedGrammars.map (grammar) -> grammar.name
  return combinedGrammars.filter (grammar, g) ->
    return (grammar.constructor.name is 'TreeSitterGrammar') or (grammar.constructor.name isnt 'TreeSitterGrammar' and grammar.name and combinedGrammarNames.indexOf(grammar.name) is g)
```
