### ISSUE TITLE
PlatformIO upload problem with esp-idf but not with Arduino framework

### ISSUE THREAD

**Issue by williamesp2015** [atom/atom#17036]
My PlatformIO is updated  ATOM is 1.2.5.0 x64
I had no problem with Esp32 using Arduino but when I tried to use PlatformIO examples: espidf-hello-world I could compile it and when tried to upload I got this error even with stage version

esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: 'C:\\~Platform
Io\\~MYESP32\\~Final'
My platofrmIo.ini is:
[env:esp32dev]
platform = espressif32
;platform = https://github.com/platformio/platform-espressif32.git#feature/stage
framework = espidf
board = esp32dev

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

It looks like you are having an issue with the PlatformIO IDE, you'll want to file an issue over on [their repository](https://github.com/platformio/platformio-core/issues) in order to get that sorted out as we don't provide support for that.
