### ISSUE TITLE
Uncaught Can't find /bundle.js file

### ISSUE THREAD

**Issue by Siscs** [atom/atom#17031]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Can't find /bundle.js file

```
At C:\Users\Cesar\AppData\Local\atom\app-1.25.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:959

undefined
```

### Commands

```
     -7:32.6.0 editor:select-to-first-character-of-line (input.hidden-input)
     -7:32 core:delete (input.hidden-input)
  2x -4:09.2.0 core:move-down (input.hidden-input)
     -4:08.6.0 editor:move-to-first-character-of-line (input.hidden-input)
  3x -4:08.1.0 core:select-down (input.hidden-input)
     -4:07.0 core:select-up (input.hidden-input)
     -4:06.6.0 core:delete (input.hidden-input)
  2x -4:06.2.0 core:move-up (input.hidden-input)
     -4:05.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -4:04.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -4:04.0 editor:newline (input.hidden-input)
     -4:01.1.0 find-and-replace:select-next (input.hidden-input)
     -3:58.5.0 core:save (input.hidden-input)
  2x -2:43.2.0 emmet:encode-decode-data-url (input.hidden-input)
  3x -2:15.1.0 platformio-ide-terminal:toggle (div.tool-panel.tree-view)
     -0:12.5.0 emmet:encode-decode-data-url (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
atom-ide-ui 0.9.4 
atom-runner 2.7.1 
atom-typescript 12.3.8 
emmet 2.4.3 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by lee-dohm** [comment]
Thank you for your submission!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/17031#issuecomment-376612306. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
