### ISSUE TITLE
Saving on NFS (Network File System) causes Uncaught TypeError: Path must be a string. Received undefined 

### ISSUE THREAD

**Issue by levinandrew** [atom/atom#17046]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
I am using Atom on windows. The files I am editing are in an NTFS folder on windows. This folder is mounted on a linux server as an NFS (network file system) directory. Whenever I save a file from the linux server (I am ssh'd into it) or if I save a file from windows (saving within Atom), I get an error saying "Uncaught TypeError: Path must be a string. Received undefined". To be clear, even if I am editing the file on the linux server using vim, and I save the file on linux, the Atom editor on Windows displays the error.
### Steps to Reproduce

1. From windows (using Atom editor) or from linux (using command line), save any file within the shared network folder.

**Expected behavior:** 
I do not expect to see an error.
**Actual behavior:** 
I see the error every time I save a file.
**Reproduces how often:** 
Every single time I save a file even when I reboot in safe mode.
### Versions
I am running atom on Windows 7. The atom configuration is show below.
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by lee-dohm** [comment]
What do you have the "File System Watcher" configuration set to? What happens if you flip it to the other setting and restart Atom?

**Comment by levinandrew** [comment]
I had it set to "Native operating system APIs", and I switched it to "Emulated with Atom events" and it works now. Thank you!

**Comment by lee-dohm** [comment]
You're welcome. I'm glad we could help :grinning:
