### ISSUE TITLE
autocomplete suggest box text ghost rendering

### ISSUE THREAD

**Issue by noe132** [atom/atom#17053]
### Description
autocomplete suggestion box text rendering issue

I'm using typescript develop my app using [atom-typescript](https://atom.io/packages/atom-typescript) getting for suggestion. but as I scroll up and down using arrow keys the text rendering in suggestion box looks wierd.
I cannot reproduce this under safemode because I need the atom-typescript package to get suggestion display.
I've try to use default theme but doesn't change something.
I don't know it was related to atom or atom-typescript package, but I think It might be atom rendering issue?

gif:
![](https://user-images.githubusercontent.com/2271900/38135574-8d696cf6-344b-11e8-8f78-680fbdb9d499.gif)
I don't know how to inspect the suggestion box element using dev tools because it close immediatly after i click somewhere else :(

[Description of the issue]

### Steps to Reproduce

1. install atom-typescript
2. open some project using typescript
3. get suggeestion by typing something

**Reproduces how often:** 100%. I can reproduce it on my another laptop.

### Versions
```
λ  apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.13
git 2.12.2.windows.2
visual studio 2015

λ  atom --version
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by rsese** [comment]
Thanks for reaching out - have you always had this issue or did it start with Atom 1.25?

Also, if you try https://atom.io/packages/ide-typescript do you see the same behavior?

**Comment by noe132** [comment]
@rsese I can reproduce it under atom 1.24.1, with only ide-typescript and atom-ide-ui 2 community packages enabled. And it seems that there is another issue that the suggestion type detail won't render until I move onto it.
![](https://user-images.githubusercontent.com/2271900/38153447-73020072-349f-11e8-896b-839c9b9525e3.gif)

**Comment by Arcanemagus** [comment]
Can you try [disabling GPU rendering](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem)?

**Comment by noe132** [comment]
@Arcanemagus It can be reproduced with `atom --disable-gpu`. same behavior as above

**Comment by rsese** [comment]
Hmmm, do you have any custom styles in your `styles.less` file?

**Comment by noe132** [comment]
@rsese yeah I have some custom style in styles.less, but it seems no relations with this.
I've tried run `mv .atom .atombak` with new userprofile, and start atom with `atom --disable-gpu`, install only `atom-ide-ui` and `ide-typescript`, the issue still. (atom 1.24.1 and 1.25.0), but it doesn't look that severe as before.
![18-03-31 2](https://user-images.githubusercontent.com/2271900/38160475-4f90ea3e-34f1-11e8-8f93-13b695818412.gif)

**Comment by noe132** [comment]
no matter i choose which one of `ide-typescript atom-ide-ui` or `atom-typescript linter linter-ui-default intension busy-signal` 2 pack of autocomplete solution, there is still the text render issue. I can't tell if it's cause by `atom-ide-ui` or `intention`, both of them cause this issue.
