### ISSUE TITLE
Mouse cursor disappears when it enters the text editing area in a Dark theme

### ISSUE THREAD

**Issue by rayhinton** [atom/atom#17069]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The mouse cursor disappears inside the text editing area when using any Dark theme as your Syntax Theme. The mouse cursor behaves correctly in any Light theme.

### Steps to Reproduce

1. Open a document in Atom, using any Dark theme as your Syntax Theme.
2. Make sure your Atom window is in focus. Move your mouse cursor outside the Atom window, then drag it into the middle of the text editing area.
3. Observe that the mouse cursor disappears when you move it inside the text editing area.
4. Change the Syntax Theme to any Light theme, and repeat step 2. Observe that the mouse cursor does not disappear.

**Expected behavior:** The mouse cursor should not disappear in Step 3.

**Actual behavior:** The mouse cursor disappears in Step 3.

**Reproduces how often:** 100%

### Versions

* Atom version 1.25.0 
* just updated to macOS 10.13.4.

### Additional Information

Also tried deleting and reinstalling Atom. I also tried making a screen recording of this, but it actually showed the mouse cursor properly, which is confusing.

**Comment by lee-dohm** [comment]
I could not reproduce this using Atom v1.25.0 on Mac OS X 10.13.4 when running using the One Dark UI and One Dark Syntax themes (both in Safe Mode and not in Safe Mode). I suspect that this may be an issue with either the UI or syntax theme you're running. Please specify which themes you're running and if they are community themes, consider reporting this issue on the repository for the theme in question.

**Comment by hayeoiroo** [comment]
I'm facing the same issue only on high resolution settings on my external 4k monitor, when I reduce the resolution to <1080p the mouse cursor will show but on higher resolutions it wouldn't.
The issue seems to be fixed when I change to a light color theme but on all available dark themes the cursor will just disappear.
- by @mouhannad-sh comment (vs code) [https://github.com/Microsoft/vscode/issues/47076](url)

**Comment by lee-dohm** [comment]
Thanks @hayeoiroo but I'm running on an iMac 5K display, so I doubt that HiDPI is the cause of it.

**Comment by rayhinton** [comment]
Thanks so much for the quick response! I tested this in the following themes, with the same results:
- Atom Dark
- Base16 Tomorrow Dark
- One Dark
- Solarized Dark

Curiously, this is happening on my external monitor at 2560x1440. When I change the resolution to 1920x1080, it goes away, similar to that other issue. When I drag Atom over to my Macbook Pro monitor, running at default 1440x900, this does not happen.

**Comment by lee-dohm** [comment]
This sounds like similar symptoms to https://github.com/atom/atom/issues/12634 (in that it only appears to affect external monitors and all Electron applications), which some people were able to ameliorate by selecting a different color profile for their external monitors. You may want to try that.

**Comment by rayhinton** [comment]
Hmm, I tried all of the various command line options (`--disable-gpu`, `--force-gpu-rasterization`, and `--enable-gpu-rasterization`), but that did not change the behavior. I also tried all of the color profiles in System Preferences, including Color LCD and sRGB IEC61966-2.1 (which were mentioned in #12634), but still no change. 

I also downloaded the latest version (1.21.1) of VS Code, and saw the same behavior. That does seem to suggest an Electron issue. Would it make sense to post an issue on the Electron repo?

**Comment by 50Wliu** [comment]
> Would it make sense to post an issue on the Electron repo?

Yes, I think it would.

**Comment by GBirkel** [comment]
For a temporary workaround, edit Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.css ,
and comment out (or delete) the CSS rule for ".monaco-editor.hc-black.mac .view-lines, .monaco-editor.vs-dark.mac .view-lines"

**Comment by lee-dohm** [comment]
@GBirkel Wouldn't that be better shared on the VSCode repository?

**Comment by GBirkel** [comment]
Ah, I seem to have entered this into the wrong tab.  :D

**Comment by matt3224** [comment]
Same here! atom 1.25.1

**Comment by rayhinton** [comment]
Folks writing on other issue reports seem to indicate this is a larger macOS problem. I recommend folks make their voices heard by contacting Apple Feedback: https://www.apple.com/feedback/macos.html

**Comment by nik736** [comment]
I have this issue as well after updating macOS to the newest version. Increasing the cursor size helps (for now).

**Comment by mestrade** [comment]
Same issue here :/

**Comment by trickpattyFH20** [comment]
I had this bug on every IDE. Sublime, Atom, VS code etc. Confirmed that the accessibility cursor size workaround fixes it.

**Comment by andreuBiset** [comment]
Same here, after upgrading macOS with an external monitor. Increasing the cursor size works!

**Comment by jordpo** [comment]
So I adjusted the cursor size and it works like a charm but I notice now that when taking a screenshot via ctrl+shift+4, the cursor disappears! Is this happening to anyone else?

**Comment by nik736** [comment]
@jordpo now that you mention it I know where it comes from, lol ;-) was going crazy not knowing why it is disappearing...

**Comment by jordpo** [comment]
I was hoping the latest update would fix the issue but no luck

**Comment by rodmaz** [comment]
In my case the problem occurs when Atom is used with external monitor (4K) and resolution is scaled. When using non-scaled resolution, i.e. "looking like" 4K in macOS parlance, it works fine.
Other editors such as Textmate work fine in all resolutions.

**Comment by jordpo** [comment]
Yeah it was a 4k monitor issue with me as well and using the `Default for display` setting under Display fixes all the mouse related issues.

**Comment by khawkins98** [comment]
Have the same issue as described above when using resolution scaling on 4K monitor. In the Electron issue queue found a tip that scaling the mouse works around -- it works for me:

https://github.com/electron/electron/issues/12519#issuecomment-395914645

But, this seems to be an Electron issue more than an Atom one.
