### ISSUE TITLE
Unable to save when the encoding is set to Nordic

### ISSUE THREAD

**Issue by bulletkid** [atom/atom#17063]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom is unable to save any file if the file encoding is erroneously set to Nordic.
I use a Windows 10 box with atom version 1.25.0 x64. As part of configuring settings either I or one of the plugins set the Nordic from Western(Windows 1252). This was causing Atom to not be able to save *any* file. Also the error message string , while trying to save, was empty. Hence we didn't had an idea about what was Atom barfing about.

NOTE: This problem may be more widespread ie there may be bugs about switching "File Encodings" to other values as well even though the problem I encountered was about Nordic locale.

### Steps to Reproduce

1. Open Settings
2. Change file encoding to "Nordic"
3. Create a new file, write some gibberish and try to save it

**Expected behavior:** [What you expect to happen]
File should get saved. The * (showing unmodified file in cmd line) should disappear

**Actual behavior:** [What actually happens]
File doesn't get saved. The * (showing unmodified file in cmd line) is present.

*Edit by @rsese mentioning the console error*

On Windows, the error in console is:

```
Uncaught (in promise) Error: Invalid encoding name: ISO-8859-10
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% reproducible

### Versions

**atom.cmd --version **

Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**apm.cmd --version **
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.14
git 2.15.1
visual studio 2015

** OS **
Windows 10 x64

**Comment by rsese** [comment]
Thanks for opening a new issue for this @bulletkid :bow:

I can reproduce with Atom 1.25 on Windows 10 but I can't reproduce on macOS 10.12.6 with Atom 1.25.

On Windows, the error in console is:

```
Uncaught (in promise) Error: Invalid encoding name: ISO-88598-10
```

**Comment by rsese** [comment]
Double checked on 1.24 and still get an error:

```
Uncaught (in promise) Error: Invalid encoding name: ISO-8859-10
```

I mentioned above that the error I saw on 1.25 was:

```
Uncaught (in promise) Error: Invalid encoding name: ISO-88598-10
```

But after reinstalling 1.25 the error mentions `ISO-8859-10` 😕  Should have taken a screenshot.....

Also noticed that just switching the encoding to Nordic will generate in the error in console.

**Comment by jasonrudolph** [comment]
> I can reproduce with Atom 1.25 on Windows 10 but I can't reproduce on macOS 10.12.6 with Atom 1.25.

I also get the error on Atom 1.26.0-beta1 on Windows 10.

**Comment by jasonrudolph** [comment]
As far as I can tell, this issue was introduced in [Atom 1.19.0](https://github.com/atom/atom/releases/tag/v1.19.0). I can't reproduce it in Atom 1.18.0, but I _can_ reproduce it in 1.19.0.

I think the next step is to skim through the [Atom 1.19.0 release notes](https://github.com/atom/atom/releases/tag/v1.19.0) to look for changes that could have led to this regression. For example, I see that Atom 1.19.0 included an upgrade from Electron 1.3.15 to
1.6.9. Perhaps that's related?

**Comment by maxbrunsfeld** [comment]
This was almost definitely introduced by https://github.com/atom/text-buffer/pull/225. We now use the native `iconv` library for encoding text. I guess the windows port of `libiconv` does not support that encoding.

**Comment by maxbrunsfeld** [comment]
Here are the encodings supported by `win_incov`: 

https://github.com/win-iconv/win-iconv/blob/9f98392dfecadffd62572e73e9aba878e03496c4/win_iconv.c#L155-L606

**Comment by maxbrunsfeld** [comment]
> 28600 - ISO-8859-10 - Latin-6

According to [the wikipedia page on windows code pages](https://en.wikipedia.org/wiki/Windows_code_page), windows should natively be able to encode to ISO-8859-10. On windows, it is called code page 28600.

So I think the fix would be to simply add an entry to win-iconv's `codepage_alias` array (probably [here](https://github.com/win-iconv/win-iconv/blob/master/win_iconv.c#L558)). Something like this:

```c
{28600, "iso8859-10"}
```

It's pretty trivial, but would require testing to make sure that the nordic text saves properly.

**Comment by Ben3eeE** [comment]
This is also an issue with the `Western (Mac Roman)` encoding.

**Comment by maxbrunsfeld** [comment]
> Is it trying to find MACROMAN and the name is macintosh in win-iconv?

Yeah, I think so. We already have [some logic](https://github.com/atom/superstring/blob/fc262233c2c1d71ec19fbaa832f6f4ce4915e316/index.js#L339-L345) to convert the old encoding names into the format in which `libiconv` expects. We may have to add something similar for `MACROMAN`.

**Comment by maxbrunsfeld** [comment]
Actually, I forgot; I had already tried to fix this!

Those windows code pages didn't actually work when I tested; the windows APIs `IsValidCodePage` and `GetCPInfo` don't seem to recognize those code page numbers. I think the fix would be to remote those encodings from the encoding selector on windows.
