### ISSUE TITLE
Atom 1.25.0 will crash by switching system proxy

### ISSUE THREAD

**Issue by wyudong** [atom/atom#17071]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom (1.25.0) often crashes these days, I wonder if it's related to the system proxy. The crash will accidentally happen when my Macbook waked up or ShadowsocksX-NG switched between Global mode and PAC mode. It's not *always* but quite often. However, I found the steps to reproduce the issue 100%.

### Steps to Reproduce

1. Run Atom in safe mode.
2. Switch ShadowsocksX-NG mode repeatly.
3. Switching about 10 to 50 times will cause Atom to crash.

**Expected behavior:**

No so much crashes.

**Actual behavior:**

Always crashes.

**Reproduces how often:**

Always.

### Versions

```
Atom: 1.25.0
Electron: 1.7.11
Chrome: 58.0.3029.110
Node: 7.9.0
OS: macOS 10.13.3 (17D102)
```

### Additional Information

Video to reproduce the crash: [atom-crash-ss.mp4.zip](https://github.com/atom/atom/files/1870156/atom-crash-ss.mp4.zip)

Apple crash report: https://gist.github.com/wyudong/1996f3573a68ccb555f5ccd3595cd578

**Comment by wyudong** [comment]
#16937

**Comment by lee-dohm** [comment]
Is this reproducible with anything other than ShadowsocksX-NG?

**Comment by wyudong** [comment]
@lee-dohm Let me try. Later.

**Comment by wyudong** [comment]
@lee-dohm I cannot reproduce it without ShadowsocksX-NG. The crashed thread shown in report is always Proxy Resolver.

**Comment by lee-dohm** [comment]
There's no Atom code in the crashed thread from what I can see, so I'm not sure how this is an Atom issue. Or at least, I'm not sure how Atom would address it. This is likely an Electron or Chromium issue ... or potentially something that ShadowsocksX-NG is doing to put things in a weird state that is causing Electron or Chromium to crash. In any case, I don't believe that we're going to be able to spend any time to investigate this. Please let us know if your investigations turn up anything that Atom would be able to affect.

Thanks for the report.

**Comment by muzixinly** [comment]
I'm seemingly  the same case. I'have ShadowsocksX-NG too, but in my case, the atom would crash when atom is backgroud, and quite offen.

Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
OS        : 10.13.4 (17E199)
