### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by nyanzebra** [atom/atom#17081]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:535

TypeError: Cannot read property 'length' of undefined
    at SuggestionListElement.getDisplayFragment (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:535:54)
    at SuggestionListElement.renderItem (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:479:18)
    at SuggestionListElement.renderItems (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:293:18)
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -4:16.6.0 core:move-left (input.hidden-input)
  2x -4:01.7.0 core:move-down (input.hidden-input)
  2x -4:01.0 autocomplete-plus:confirm (input.hidden-input)
     -3:13.4.0 editor:newline (input.hidden-input)
     -3:06.9.0 core:backspace (input.hidden-input)
     -2:43.7.0 editor:newline (input.hidden-input)
  3x -2:39.2.0 core:backspace (input.hidden-input)
  2x -2:37 core:save (input.hidden-input)
  2x -1:52.7.0 editor:newline (input.hidden-input)
  2x -1:46.2.0 core:save (input.hidden-input)
     -1:22.3.0 core:move-left (input.hidden-input)
     -1:22.1.0 editor:newline (input.hidden-input)
     -1:21.8.0 core:move-up (input.hidden-input)
     -1:16.6.0 core:save (input.hidden-input)
     -0:08.5.0 core:backspace (input.hidden-input)
     -0:05.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-clock 0.1.16 
atom-ide-ui 0.9.4 
build 0.70.0 
build-cmake 0.11.0 
busy-signal 1.4.3 
file-icons 2.1.18 
git-plus 7.10.2 
Hydrogen 2.3.0 
ide-cpp 0.0.3 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-rust 0.15.1 
ide-yaml 0.4.2 
language-cmake 1.1.0 
language-rust 0.4.12 
minimap 4.29.8 
minimap-git-diff 4.3.1 
sort-lines 0.18.0 
teletype 0.12.0 
travis-ci-status 1.3.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* what were you doing at the time of the error?
* is the error is reproducible?
* if reproducible, do you see the error in safe mode (atom --safe)?

**Comment by Arcanemagus** [comment]
For reference, it looks like a similar stack trace was posted in https://github.com/atom/atom/issues/15992#issuecomment-358288024.

**Comment by rsese** [comment]
Thanks @nyanzebra :+1:  Can you reproduce in safe mode (`atom --safe`)?

In the comment @Arcanemagus pointed to where someone ran into an error with a similar stack trace, they have some Rust packages in common with you.  If you can't reproduce in safe mode, then it's likely one of those packages is generating the error.

**Comment by nyanzebra** [comment]
Will try and reproduce when home with safe flag, thx!

**Comment by nyanzebra** [comment]
issue does not occur in safe mode, so likely an issue with one of the pacakges

**Comment by rsese** [comment]
Thanks for confirming!   One way to narrow things down is to disable all installed packages and then enable one-by-one but we'd suggest starting with the Rust-related packages.

 It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
