### ISSUE TITLE
Window title not updating

### ISSUE THREAD

**Issue by orschiro** [atom/atom#17080]
Tested with 1.25.0 on GNOME 3.28

Demo screencast: https://youtu.be/7Fj6cufQQRA

Can someone reproduce?

1. Have an open tab
2. Press Ctrl + O to open a new document
3. The document is opened but the window title not updated

**Comment by rsese** [comment]
Thanks for the report - can you share more information about the issue? In particular, the issue template information is really helpful and if you can add more details we can go from there:

* Can you reproduce in safe mode (atom --safe)?
* Though the video is helpful, it would be great if your written steps were more detailed - specific written steps that we can follow one-by-one that reproduces what you're seeing is always helpful (e.g. the file in your video has a filename with punctuation characters, is that relevant to the behavior you're seeing?  Your video also seems to show that you have a file open and then open the same file, is that what's happening?).  

So if you can share the above details and the rest of the template information, we can go from there.

**Comment by orschiro** [comment]
Hey @rsese thanks for your feedback! Will definitely consider this for future reports. 

Went ahead and tried to reproduce my own issue and cannot any longer. 

Now it properly opens a new tab. I am not sure what exactly was the issue but it's no longer occurring. 

Shall it re-occur, I will reopen the issue.

Once again, sorry for the noise...

**Comment by rsese** [comment]
No problem and thanks for letting us know that the issue is no longer reproducible :bow:
