### ISSUE TITLE
text fields not showing typed characters

### ISSUE THREAD

**Issue by bidva** [atom/atom#17094]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

text fields not showing typed characters
a snap shot of these fields and all of those has value but they are invisible even in setting view 
![screen shot 2018-04-06 at 10 48 31 am](https://user-images.githubusercontent.com/8351624/38436302-1ec35b16-3989-11e8-90c4-c7c68d100f3c.png)
. 

![screen shot 2018-04-05 at 9 28 32 am](https://user-images.githubusercontent.com/8351624/38378999-36665348-38b4-11e8-95d5-5b05a51439d2.png)
![screen shot 2018-04-05 at 9 33 31 am](https://user-images.githubusercontent.com/8351624/38379064-6e82b316-38b4-11e8-8b97-607baee0fd54.png)

![screen shot 2018-04-05 at 9 30 31 am](https://user-images.githubusercontent.com/8351624/38379008-3e692b88-38b4-11e8-901c-6f00d0e32e41.png)

### Steps to Reproduce

1. oppening atom
2. try to find something by pushing Ctrl + f
3. start typing 

**Expected behavior: to show characters 

**Actual behavior: fields seems has value but they are invisible

**Reproduces how often: always

### Versions

Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Additional Information

I have virtual mac on my machine and i'm not sure if it's related to that one or not. I had older version of atom and was working properly after updating to last version happened to me.

**Comment by Arcanemagus** [comment]
Can you follow the steps in the [Debugging section](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem) of the Flight Manual to check if this is a GPU related issue?

**Comment by bidva** [comment]
I tried to turn off gpu no different

**Comment by Arcanemagus** [comment]
So to be sure, you are closing _all_ instances of Atom, and launching it with `atom --safe --disable-gpu` and are still seeing this?

**Comment by bidva** [comment]
this one worked so what should I do to fix it ?

**Comment by bidva** [comment]
that command worked!! So how can I disable gpu permanently?

**Comment by bidva** [comment]
I did it in additional information , By the way it's mac :)

**Comment by mrstux** [comment]
I am seeing this issue on Atom 1.27.2 on Mac OS 10.12.6 on a Mac Pro 5,1, with GT120 graphics. Reinstalled atom, no change.

`atom --safe --disable-gpu` works around the issue.

as does

`atom --disable-gpu`

How can I set this permanently?

And can we get this fixed :)

**Comment by bidva** [comment]
@mrstux you can use alias http://osxdaily.com/2017/05/22/how-make-shortcut-alias-mac/

**Comment by mrstux** [comment]
@bidva AFAIK you can't specify command line arguments/flags in an Alias, unlike in a Windows shortcut. Its much more like a soft symbolic link.

**Comment by jessekinsman** [comment]
I am having this same issue on Mac Pro (early 2008) OS X 10.11.6
Graphics NVIDIA Quadro FX 5600 1536 MB

I can start atom by using 
`atom --disable-gpu`

However, that is not a viable solution. Will there be an update?

**Comment by Vasfed** [comment]
Made a [patch](https://github.com/vasfed/atom/tree/feature/disable-gpu-setting) for permanent gpu disable support, but discovered that similar PR #17699 was already rejected.

**Comment by smartworld-konoha** [comment]
Here is a solution for those who use bash.
In your ~/.bashrc or ~/.bash_aliases type this, after this run source command

### Run atom without gpu acceleration
function runAtom {
	atom $@ --disable-gpu
}

alias atom=runAtom
