### ISSUE TITLE
Tree-sitter causes arrow-syntax functions to not be coloured as functions

### ISSUE THREAD

**Issue by adityavm** [atom/atom#17100]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Enabling tree-sitter causes Javascript arrow-syntax functions to not be coloured as functions. They show as normal variables.

### Steps to Reproduce

1. Turn on tree sitter
2. Check any code that has functions defined using arrow syntax

**Expected behavior:** Arrow syntax functions should be coloured as functions.

**Actual behavior:** Arrow syntax functions are coloured as variables.

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```
```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.1
python 2.7.10
git 2.16.0
```
on Mac OS X 10.13.3

### Additional Information

Screenshot for clarity. Notice `toggleLegs` and `state` have the same colour, while `componentWillReceiveProps` is coloured as a function.

<img width="408" alt="screen shot 2018-04-08 at 5 58 04 pm" src="https://user-images.githubusercontent.com/80849/38467485-bd3ce3e2-3b56-11e8-801d-c8c661eb03c0.png">

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm what syntax theme you're using and share a screenshot of what you see with tree-sitter disabled for comparison?

**Comment by adityavm** [comment]
@rsese I used safe mode for the screenshot, so it's with everything disabled and One Dark as the theme.

Here's what it looks like without tree-sitter:

<img width="430" alt="screen shot 2018-04-10 at 8 09 31 am" src="https://user-images.githubusercontent.com/80849/38533399-b9a64502-3c96-11e8-892d-c1b4541ea9e8.png">

**Comment by adityavm** [comment]
Investigated into this and realised that syntax type for js files was being set as Javascript and not Babel, causing the syntax to be highlighted differently. Added custom override and now it's fine.
