### ISSUE TITLE
feature request: drag one tab to a folder of the project (to quickly move the file)

### ISSUE THREAD

**Issue by WiliTest** [atom/atom#17110]
Example: I opened a file from my windows desktop which is not in my project. I now want to move it from the desktop to one of the project folders. It would be great if we could move that file by simply dragging its tab into a folder of the project pan (tree view).

**Comment by rsese** [comment]
Thanks very much for the feedback!

Would you mind reopening this issue in the https://github.com/atom/tree-view/ repository if there isn't an existing issue for this already? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us half way 👍
