### ISSUE TITLE
Atom unexpected crash

### ISSUE THREAD

**Issue by Raushanka** [atom/atom#17119]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Tried to run the Atom and it didn't run]

### Steps to Reproduce

1. [Run the atom]
2. [It didn't run]

**Expected behavior:** [I was expecting atom.exe to launch Atom IDE]

**Actual behavior:** [Nothing happened]

**Reproduces how often:** [4-5 times pressed the start button]

### Versions
version Atom  [@1.23.3.0]
Windows 8, 64 bit

### Additional Information

So,  I just uninstalled the Atom and downloaded the new version from official website atom.io

**Comment by Raushanka** [comment]
It was version 1.23.3 that crashed. Then I delete it and installed the new version 1.25.1.

**Comment by rsese** [comment]
Thanks for confirming - when you started in safe mode was there any difference or did Atom crash then too?

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Since it appears that the crash you experienced was resolved by upgrading to Atom 1.25 I am going to close this. Don't hesitate to reach out if you still encounter crashes while running the latest version and we will be happy to reopen the issue.
