### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by JKR007** [atom/atom#17120]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Cannot open - "log/development.log" - file in Rails project.  <development.log> is a file, in which all requests of my web-app is written. When I try to open this file:

1. I clicked - "Proceed"
![screen shot 2018-04-12 at 4 17 14 pm](https://user-images.githubusercontent.com/36299998/38675206-5f230f4e-3e70-11e8-8050-77d126b62485.png)
then it was frozen for about 15secs. 

2. Then, the following   
![screen shot 2018-04-12 at 4 17 32 pm](https://user-images.githubusercontent.com/36299998/38675477-5336c5da-3e71-11e8-8612-e330facb98f9.png)
I chose the option - "Reload". After reloading, Again I tried to open that file and again above shown steps (1, 2) repeated.

3. I checked with another editor and it opened - the <development.log> file, easily.

### Versions

`atom --version`
Atom    : 1.24.1
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

OS
macOS Sierra
10.12.6

**Comment by rsese** [comment]
> Cannot open - "log/development.log" - file in Rails project. <development.log> is a file, in which all requests of my web-app is written. When I try to open this file:

How large is the file?

Also, I see you didn't check the checkbox in the `Prerequisites` section - did you try safe mode or any of the other steps from that section?

> Atom : 1.24.1

I don't know if it will make a difference with the behavior you're seeing but can you update to the latest stable release (currently 1.25.1) and see if that makes a difference?

**Comment by JKR007** [comment]
## Thanks for feedback!

The file is **243MB**.

I tried in safe mode (**atom --safe**) but again editor crashed.

Updated editor to:
_Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0_

But again it crushed.

**Comment by rsese** [comment]
Sorry I missed your followup @JKR007 - a file that large is known to have problems in Atom though I'm not sure if the crash is specific to the file you're working on.  Curious though if disabling spell-check has any effect?

@zeff013 feel free to open a new issue and fill out the issue template for your crash and we'll take a look.  If you can share the exact file that's crashing that would be great but definitely understand if that's not possible.  I'd also be curious if disabling spell-check has changes anything for you when opening that file.

**Comment by JKR007** [comment]
Hi @rsese! My current version is v1.25.1. I could not find any solution to this problem. To avoid of this situation, I added a function to control the file size. (If it reaches to the limit, clear half of the file automatically). I hope this [link](http://ruby-doc.org/stdlib-1.9.3/libdoc/logger/rdoc/Logger.html#method-c-new) is helpful to get the general idea (especially for Ruby on Rails Developers).

**Comment by zeff013** [comment]
Hi @rsese! You were spot on! disabling spell checking solved the issue with freezing.
Created separate issue here https://github.com/atom/spell-check/issues/260

**Comment by DoctorKisow** [comment]
@rsese:  I was having an issue with v1.27.2 where an 11Mb file which contained XML and MIME encoded data.  This file hung Atom twice; upon searching I came across this thread and disabled spell check.  It is no longer hanging.  I hope this information helps improve the project.
