### ISSUE TITLE
Disable native TextEditor input in non-readonly editors

### ISSUE THREAD

**Issue by smashwilson** [atom/atom#17121]
To complement readonly mode, provide a way to tell a TextEditor that it should not accept keyboard input, but should still be modifiable. This would be useful for any package that wants to take control of the way the editor input is processed (i.e. vim-mode-plus).

@lee-dohm and I were brainstorming names for this mode the other day; `setKeyboardInput(false)`? `setNativeInput(false)`?

/cc @t9md

**Comment by t9md** [comment]
## This fix must included before releasing next-beta.

Unless that, `vim-mode-plus` become useless in `atom-beta` as it is useless in current atom-master.

## history and background

I what share brief history to share same background/context.

0. Originally vim-mode-plus have been setting `editor.component.setInputEnabled(false)` to prevent typed char inserted to editor in it's `normal-mode`.
This is the behavior `vim-mode-plus` want now.
1. #16294 introduced `readonly` editor. It also make calling `editor.component.setInputEnabled(false)` automatically be `readonly` editor(which I'm not happy as vim-mode-plus's author)
2. #16999 make `readonly` editor protect being mutated through editor's method such as `editor.insertText("aaa")`. All vim-mode-plus's operator no longer work properly.

## Two approaches to fix this.

Either case, what vim-mode-plus want is just get back original behavior which I described at `0.` of `history and background`.

A. Add `soft` read-only state: (COMPLEX)
  - How it is enabled: `editor.setReadOnly(true, {soft: true})`
  - TODO:
    - Remove `component.setInputEnabled` and `component.isInputEnabled` which is just proxying to editor's method and having different name other than `setReadOnly` is just confusing.
    - Reflect `soft` state to editor.element's className like `editor read-only-soft` to make it distinguishable from strict `read-only` only from className.

B. Allow the way to disable input without making editor `readOnly`
  - Introduce `editor.component.ignoreTextInput(true)`.
    - btw this is completely exact behavior of original `component.setInputEnabled`
    - Then independently have state at component which is checked in `component.didTextInput`.
  - Or revert `component.setInputEnabled` to the behavior before #16294 intrduced.
  - Who call `component.setInputEnabled` other than vim-mode-plus?
  - If plugin or atom-core really want to make editor `read-only` they should call `editor.setReadOnly` or build `<atom-text-editor read-only>` element.
  - If plugin or atom-core or vim-mode-plus just want to ignore keytype, use `compnent.ignoreTextInput`(or `component.setInputEnabled` whichever).

I like B. approach which is far more simple in implementation-wise.
And also vim-mode-plus's behavior less likely broken by the future change in `read-only` behavior.

**Comment by lee-dohm** [comment]
> This fix must included before releasing next-beta.

Don't worry, we've got it on our radar and don't plan to release without a fix in.

> Allow the way to disable input without making editor readOnly

Yes, this is the way we're leaning as well, as described in the body of this issue.

> Introduce `editor.component.ignoreTextInput(true)`

I kind of like `ignoreTextInput` as a name. What do you think @smashwilson?
