### ISSUE TITLE
Atom PHP comment syntax highlighting issue

### ISSUE THREAD

**Issue by HoyeongKim** [atom/atom#17147]
hi, My Atom has a issue in PHP Syntax highlight.
![2018-04-16 2 25 35](https://user-images.githubusercontent.com/21984563/38791393-5b658070-4182-11e8-9861-5da3a233b394.png)
![2018-04-16 2 25 19](https://user-images.githubusercontent.com/21984563/38791397-5f8e3372-4182-11e8-8716-795b74ab7cb8.png)

first thing is PHP Syntax of  sublime text 3. it cleared show php code and script code.
second thing is php syntax of ATOM. but it looks like has error the syntax function.
atom cann't detact closing comment tag so below script tag also hide by comment syntax.

i'm very sorry to my wrong english.
how can i fixed it?

My atom ver is 1.25.1
and i used mac OS 10.13.4 High Sieera

**Comment by rsese** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/language-php repository if there isn't already an issue for this? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

If you can also use the issue template and provide code that can be copied and pasted (so we can try the code ourselves), that would be helpful as well.

Thanks for meeting us half way 👍
