### ISSUE TITLE
Status Bar Overflow / Wrapping

### ISSUE THREAD

**Issue by iamsteelone** [atom/atom#17149]
My atom has an issue where by the data displayed in the footer bar is wrapping around and then the bottom of it is cut off.  Any idea on how to prevent this or how to make the bar larger?
![bigbar](https://user-images.githubusercontent.com/29373666/38803866-6b291a0e-4168-11e8-8919-beba0d3d6050.PNG)

**Comment by rsese** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/status-bar repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

If you can also use the issue template as much as possible and let us know which packages you're using so we can reproduce the behavior, that would helpful.

Thanks for meeting us half way 👍
