### ISSUE TITLE
Rapid Window Cycling Results in System Lock Up

### ISSUE THREAD

**Issue by KNNSpeed** [atom/atom#17145]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On Windows 10 64-bit, rapidly switching between application windows on screen locks up the system (as long as one of them is Atom).

### Steps to Reproduce

1. Open a file in Atom
2. Copy some code from Atom
* It's been hard to tell just how significant an impact this step actually has
3. Rapidly switch between programs 
* I've been using MS Office, mainly Word and Excel, and Chrome, and I've just been rapidly clicking between windows on-screen.
4. System will lock up, and going into and out of standby (S3) makes it respond again

**Expected behavior:** None; this shouldn't happen when cycling through windows.

**Actual behavior:** System locks up. Requires going into and out of standby mode to get the system to respond again. Sometimes when the system comes back up Atom will be closed, but other times it's still open and responding again.

**Reproduces how often:** Reliably. It also happens in Atom's Safe Mode.

### Versions

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.1
python 2.7.12
git
visual studio

Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

Windows 10 x64, Insider Build 17133.13 (latest Slow ring)

### Additional Information

Slowly switching windows seems to mitigate this behavior.

**Comment by KNNSpeed** [comment]
It looks like this has been fixed (don't know when/how long ago).
Currently, I'm using atom 1.35.1 on Windows 10 Pro x64 Insider Build 18362.53. I believe this Windows build will be similar to what consumers will know as 19H1.

**Comment by rsese** [comment]
Thanks for checking @KNNSpeed, we'll go ahead and close for now.
