### ISSUE TITLE
atom.project.onDidChangeFiles

### ISSUE THREAD

**Issue by twifty** [atom/atom#17150]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`project.onDidChangeFiles` Is wrongly documented and does not immediately fire 'deleted' events.

problem 1, The functions [comment block](https://github.com/atom/atom/blob/0dca25daf5f3ee57f3331a696bd4558baa310ce1/src/project.js#L177) and hence the atom.io documentation, state that the event object has a `type` property. However, after logging to the console, I see that it should be an `action` property.

problem 2, Deleting files does not fire an immediate 'deleted' event. The event is delayed until any other file system changes cause another event. For example, create a file - the 'created' event is triggered, delete that file - no events, edit another file - a 'deleted' AND 'modified' event is fired. 

**Reproduces how often:** 100%

### Versions

atom 1.25
Manjaro Linux

**Comment by smashwilson** [comment]
Good catch on problem 1 - looks like it was a find-and-replace bug.

For problem 2, there isn't much we can do about the timeliness of event delivery. If you're willing to try 1.26-beta (or if you remember when 1.26 is released), you can try [changing "File System Watcher" to "Experimental filesystem watching library" in your Atom core settings](http://blog.atom.io/2018/03/15/atom-1-25.html#file-system-watcher-improvements), but in the end we're bounded by the accuracy of the OS filesystem APIs.

**Comment by twifty** [comment]
I guessed it would be limited to the OS. Luckily in my situation, a late arrival of the event is no big deal.

Thanks for the heads up on the experimental though.
