### ISSUE TITLE
Atom Github package doesn't recognize changes

### ISSUE THREAD

**Issue by dkimot** [atom/atom#17160]
I am using atom and since two days ago the Github package, specifically the Git panel, doesn't recognize changes to the repository. What's weird is that the files get highlighted appropriately, yellow for changes, green for new, etc. and the line markings are still there.

If I quit atom the changes show up in the git panel on restart, but it doesn't ever update.

Any ideas?

Version:
Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by dkimot** [comment]
Also, there is no error in the dev console, just this warning:
`WebSocket connection to 'wss://ws-mt1.pusher.com/app/f119821248b7429bece3?protocol=7&client=js&version=4.2.2&flash=false' failed: WebSocket is closed before the connection is established.`

**Comment by rsese** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/github repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

If you can also fill out the issue template, that would be helpful as well (e.g. please share what operating system you're running and step-by-step instructions to reproduce the behavior you're seeing).

Thanks for meeting us half way 👍
