### ISSUE TITLE
Issues with file locking when file simultaneously worked on in Scientific Workplace

### ISSUE THREAD

**Issue by jborovicka** [atom/atom#17179]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

** ISSUE **: Incorrect behavior with file locking when using Atom in conjunction with Scientific Workplace

** SETUP **: Windows 10, Scientific Workplace 5.5, a clean installation of Atom 1.26.0 (no additional packages, replicated also in safe mode).

** EXPECTED BEHAVIOR **: I would like to edit a .tex file simultaneously in Atom and in Scientific Workplace (SW) as a WYSIWIG editor (i.e., when I edit and save the file in Atom, it refreshes in SW, and vice versa). This has successfully worked for me when using SW with WinEdt, and it also works when using WinEdt with Atom. However, the combination of Atom and SW leads to incorrect behavior.

** ACTUAL BEHAVIOR **: File gets locked after a sequence of steps and cannot be saved anymore in SW, until Atom is closed. When Atom is closed, it incorrectly erases the original file.

** REPRODUCES **: Always.

### Steps to Reproduce

The behavior differs (but is in both cases incorrect) whether the option to save backup (.bak) files is switched on or off in SW (under Tools -> User Setup -> Files).

**First, I describe the case when the option to save backup files is switched off in SW. This is not default but it is easier to explain. The case when it is on follows below.**

1. Create a file test.tex in an empty directory, e.g., containing
\documentclass{article}
\begin{document}
Some text.
\end{document}

2. Open the file using Atom. Left pane contains the content of the directory (only test.tex), right pane the content of the file.

3. Open the file using SW. Now the file is opened in both editors. SW created a temporary file test.aaa in the directory but we can ignore that one.

4. Edit the file in Atom and save. When moving focus back to SW, a dialog window in SW announces that the file has been overwritten and request reload. Click Yes. This is expected. The file on the hard drive is correctly modified.

5. Edit the file in SW and attempt to save. A message "**Error writing to disk.**" shows up in SW. **This is incorrect behavior.** Click OK in the message box.
The file test.tex is now locked and cannot be opened in a third editor (e.g., when attempting to view it in Total Commander, I get the message "**Access denied on file test.tex.**"

6. Return to Atom. Edit the file and attempt to save. Now Atom produces the message "**Unable to save file: Permission denied `C:\temp\atom-issue\test.tex.**". The file continues to be locked on hard drive and cannot be opened in a third editor.

7. Close the Atom application. Atom now produces the message "**`test.tex' has changes, do you want to save them? Your changes will be lost if you close this item without saving.**" There are two options "Save" and "Don't save". When clicking "Save", I receive the message "**Permission denied**" with an option to "Save As".

8. Click "**Don't save**". Atom application closes. But now, the file test.tex is erased completely from hard drive. **This is incorrect behavior.** Notice that the file was not originally created by Atom, but Atom nevertheless erases it, which is different from just not saving the changes.

9. Click back to SW. SW now produces the message "**File does not exist 'test.tex'. Remove the document from memory?**" Click No. Save the document in SW (File -> Save). Now the document test.tex is restored (with the last changes from SW) and it is normally accessible and unlocked.

**Now the case  when the saving backup file option is on (default). **

1. to 4. As above.

5. Now edit the file in SW and save. SW correctly saves the file and creates a backup (.bak) file with the previous content. **This is expected.** HOWEVER, at the same time, the file test.tex opened in Atom automatically changes to test.bak (the caption in the header of the window changes), and its contents indeed correspond to the test.bak file created by SW, **This is incorrect behavior.** Both files test.tex and test.bak are on the hard drive and can be viewed using a third editor. They are also both visible in the left pane of the Atom window.

6. Go back to Atom. Close the file test.bak (just the pane), and open the file test.tex. The file test.tex now contains the changes made in SW in step 5. Now edit this file in Atom and save.

7. Go to SW again. SW again opens a dialog box, requesting to update the file. Click Yes. The file is now updated with the changes made in Atom in step 6. Edit the file again and save. At this point, an error message shows up in SW saying "**Error writing to disk**" and the file is not saved. **This is incorrect behavior.** Click OK.

8. At this point, the backup (test.bak) file gets locked. **This is incorrect behavior.** When attempting to view the content of the test.bak file using Total Commander (or any other viewer), A receive the message: "**Access denied on file test.bak**"

9. Now attempt to save the file in SW again. Again, I receive the message "**Error writing to disk**" and the file is not saved. The test.bak file continues to be locked (and visible but not accessible in Total Commander). However, now the test.bak does not even show up in the directory listing in the left pane of Atom. **This is incorrect behavior.**

10. The file test.tex can now be edited and saved in Atom, and these changes are also reflected in SW. But any changes in SW cannot be saved (**Error writing to disk** message). The file test.bak continues to be locked.

11. Close the Atom application. The file test.bak is automatically erased from the directory. **This is incorrect behavior, Atom never created this file in the first place.** SW now can save the file test.tex, and create a new test.bak file while doing so.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python
git
visual studio

### Additional Information

N/A

**Comment by rsese** [comment]
Thanks for the detailed report!

We've seen recent reports of file locking issues on Windows as of Atom 1.25 (there were reports that things worked when installing back to 1.24) and we're currently using https://github.com/atom/atom/issues/17013 to track this issue if you'd like to subscribe.

And just to confirm, if you install 1.24 do you still see these lock issues?

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Comment by jborovicka** [comment]
I installed Atom 1.24, with configuration as follows:
Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

The file locking problem disappears. However, the problem with the backup files described in the second scenario persists. In particular:

1. Create a file test.tex in an empty directory, e.g., containing
\documentclass{article}
\begin{document}
Some text.
\end{document}

2. Open the file using Atom. Left pane contains the content of the directory (only test.tex), right pane the content of the file.

3. Open the file using SW. Now the file is opened in both editors. SW created a temporary file test.aaa in the directory but we can ignore that one.

4. Edit the file in Atom and save. When moving focus back to SW, a dialog window in SW announces that the file has been overwritten and request reload. Click Yes. **This is expected.** The file on the hard drive is correctly modified.

5. Now edit the file in SW and save. SW correctly saves the file and creates a backup (.bak) file with the previous content. This is expected. **HOWEVER, at the same time, the file test.tex opened in Atom automatically changes to test.bak (the caption in the header of the window changes), and its contents indeed correspond to the test.bak file created by SW, This is incorrect behavior.**

6. Close the file test.bak in Atom, and reopen test.tex. Go back to SW, edit the file test.tex, and save. **At that moment, the file test.tex opened in Atom again automatically changes to test.bak.** This can be repeated an arbitrary number of times.

Since this is distinct from the file locking problem, and persists even in an earlier version of Atom, I will file it as a new issue.
