### ISSUE TITLE
Intermittent "Unable to read supplied project specification file" error when opening files

### ISSUE THREAD

**Issue by ShaneBeee** [atom/atom#17178]
*Edit by @rsese to add repro steps and error*

1. Install Atom 1.25.1.
2. Open some project file e.g. from atom/atom `atom --safe src/text-editor-component.js`
3. After the update downloads, `Atom > Restart and Install Update` (after clicking that I waited for a minute or but I had to click it again for Atom to restart).

Expected is an Atom window opens with `src/text-editor-component.js`, actual is 
no Atom window opens, the application menu bar only has `Atom` (like in https://github.com/atom/atom/issues/17178#issuecomment-383180280), and I see this error in `/var/log/system.log`:

```
Apr 22 20:57:03 milhouse Atom[33796]: Error: Unable to read supplied project specification file.
	    at readProjectSpecificationSync (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/parse-command-line.js:212:11)
	    at parseCommandLine (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/parse-command-line.js:147:40)
	    at start (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/start.js:37:16)
	    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/main.js:40:1)
	    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/main.js:42:3)
	    at Module._compile (module.js:571:32)
	    at Object.Module._extensions..js (module.js:580:10)
	    at Module.load (module.js:488:32)
	    at tryModuleLoad (module.js:447:12)
	    at Function.Module._load (module.js:439:3)
```

That error message looks specific to https://github.com/atom/atom/pull/16845?

---

### Description

Atom no longer opening on my Mac, when I try to open a file. If I just open the APP itself, it opens, and then i can load said file, but If I just try to open the file from my desktop, atom "opens" but not fully.... nothing appears on the screen but atom pops up in my dock.

### Steps to Reproduce

1. Click a document to open.
2. Nothing opens

**Expected behavior:**
Up until last night, If I click a document, it would open it. 

**Actual behavior:**
As of last night, If I click a document, atom will not open.

**Reproduces how often:** 
100%

### Versions
Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 2.7.10
git 2.16.2
### Additional Information

I have not changed or touched any of the files in Atom. I up until last night it worked perfectly fine, no issues. I thought it was a problem with my computer. I have restarted the computer and nothing.
I tried the safe mode thing, but Like described, the problem is before atom actually opens. If I open atom, and then open a document its totally fine.
Not sure if this info helps but I am using a MacBook Pro OS X 10.13.4

**Comment by ShaneBeee** [comment]
Im going to add to this, just tested and not sure why this happens.
I use atom for writing Skript files (file.sk - Minecraft Skripts)
If I open a skript file from my documents folder (just the one file) it opens no problem
IF I open a skript file from my downloads folder (11 files) it will not open 
If I delete all the skript files, except 1 from my download folder, it still won't open, from the download folder

**Comment by rsese** [comment]
Thanks for the report!  It looks like you removed the `Prerequisites` section - can you confirm that you've tried the other suggestions from https://flight-manual.atom.io/hacking-atom/sections/debugging/ besides safe mode?

> IF I open a skript file from my downloads folder (11 files) it will not open
> If I delete all the skript files, except 1 from my download folder, it still won't open, from the download folder

So these are files that have been there already?  What if you download new skript files?

**Comment by ShaneBeee** [comment]
Hi... I have no removed the prerequisites section... I have not touched any of the files for atom. 
I will try more from that site that you sent, i dont understand most of it (I do not really know much about computer programming and the such)
It appears anything in my download folder I can not open by just clicking it. I downloaded new SK files and they do the same thing,

**Comment by ShaneBeee** [comment]
I have gone through that list and done everything that I can. At least the ones I understand.
Anywho, I think my best option at this point is to uninstall atom.... and reinstall it.
I was just curious what are the correct steps for uninstalling ATOM?

**Comment by rsese** [comment]
> It appears anything in my download folder I can not open by just clicking it. I downloaded new SK files and they do the same thing,

Hmmm, it's odd that it only happens for files in your Downloads folder - just to confirm, did you try clearing saved state when you went through the debugging document?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

> I was just curious what are the correct steps for uninstalling ATOM?

On macOS, uninstalling is detailed here:

https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/34

**Comment by ShaneBeee** [comment]
I did try clearing the save state... and it didn't seem to do anything,  Im going to follow the steps to uninstall, and then re-install and ill report back

**Comment by ShaneBeee** [comment]
Okay, so I uninstalled it, restarted my computer a could times... re installed it, restarted my computer, it wouldn't open when i first opened it.... closed it, opened it again and it opened.... sk files won't open from downloads still.... not really sure whats going on, but im going to blame my computer, because that seems to be the only logical thing

**Comment by ShaneBeee** [comment]
Okay, so i did some googling, and apparently this is a common issue
https://discuss.atom.io/t/atom-fails-to-open-mac/15095
So I took some screen shots to show you whats going on
First pic.... Atom "OPEN" shows in the dock and the top bar at the top it shows atom
https://i.imgur.com/OEfn5ML.jpg
Second/third pic... if i right click on the app it shows a bunch of windows available, if i click any of them nothing happens, if i click show all windows, it shows a bunch of pages (pic 3)
https://i.imgur.com/rw7l2bl.jpg
https://i.imgur.com/qiCbiLe.jpg
Hope this info helps a bit more

**Comment by mlcampbe** [comment]
Same problem here for me. I tried removing the ~/.atom directory and still no luck. The icon will show up and right-clicking still shows my recently edited files. But the app window never appears.

**Comment by ruschie** [comment]
Same issue... here . Tried reinstalling.  Does not work.

![image](https://user-images.githubusercontent.com/94961/39067090-583ae842-448c-11e8-83d4-3301f42d9328.png)

**Comment by mpdonovan** [comment]
Same thing here. If I open using terminal it works. But double clicking the file fails with just a menubar entry for Atom with not options.

**Comment by rsese** [comment]
@ShaneBeee if you remove the Atom icon from the dock, start Atom again, and then re-add it to the dock, does that make any difference?

**Comment by OmeletHopper** [comment]
I'm getting the same results as @mpdonovan, I can only open Atom from the terminal.

**Comment by mpdonovan** [comment]
Removing and replacing the icon did not change anything.

**Comment by mpdonovan** [comment]
After some more testing it is intermittently opening files correctly. If I double click a file on the desktop and it fails to open I can then quit and click the dock icon. It will then open with no file loaded I can double click the file and it will open. I can then quit again and double click a file and it will launch and open normally. I is completely inconsistent as to functionality.

**Comment by ShaneBeee** [comment]
@rsese  I do not have atom in my dock. It only appears there when the app opens.

**Comment by mpdonovan** [comment]
Even after removing it from the dock the intermittent behavior remains.

**Comment by TheQureshi** [comment]
Is there any guy from Atom that can resolve this issue? **I have wasted many hours in trying every solution.**

**Comment by rsese** [comment]
@mpdonovan what version of Atom are you running, are you also seeing this after updating to 1.26?  And just to confirm @mpdonovan @ShaneBeee, do you both see the same thing as the screenshot mentioned in https://github.com/atom/atom/issues/17178#issuecomment-383180280 where the menubar just shows `Atom`?

**Comment by ShaneBeee** [comment]
@rsese  Yes.... lets say I double click one of my SK files.... atom "opens" and by that I mean it shows up in my dock, and "ATOM" appears in the menu bar (right next to the apple) and if you click on that, the only option is "quit" ... nothing else! 
BUT.... If i open ATOM from my applications folder, it opens perfectly fine. I only have this issue when opening a file that should force atom open.

**Comment by rsese** [comment]
@ShaneBeee can you reproduce the behavior you're seeing and then check `/var/log/system.log`?  Do you see an Atom error at the end of that file?

**Comment by mpdonovan** [comment]
I am running version 1.26 and I do see the same thing as the screenshot intermittently. Here is the error  I got at the end of system.log

Apr 22 20:13:32 m725-128005 Atom[11837]: Unable to read supplied project specification file.
Apr 22 20:13:32 m725-128005 Atom[11837]: Error: Unable to read supplied project specification file.
	    at readProjectSpecificationSync (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/parse-command-line.js:212:11)
	    at parseCommandLine (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/parse-command-line.js:147:40)
	    at start (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/start.js:37:16)
	    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/main.js:40:1)
	    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/main.js:42:3)
	    at Module._compile (module.js:571:32)
	    at Object.Module._extensions..js (module.js:580:10)
	    at Module.load (module.js:488:32)
	    at tryModuleLoad (module.js:447:12)
	    at Function.Module._load (module.js:439:3)

**Comment by rsese** [comment]
Great thanks @mpdonovan - I haven't been able to reproduce by opening files through the recent files in the dock or by double clicking files but I finally was able to reproduce by:

1. Install Atom 1.25.1.
2. Open some project file e.g. from atom/atom `atom --safe src/text-editor-component.js`
3. After the update downloads, `Atom > Restart and Install Update` (after clicking that I waited for a minute or but I had to click it again for Atom to restart).

Expected is an Atom window opens with `src/text-editor-component.js`, actual is 
no Atom window opens, the application menu bar only has `Atom`, and I see this error in `/var/log/system.log`:

```
Apr 22 20:57:03 milhouse Atom[33796]: Error: Unable to read supplied project specification file.
	    at readProjectSpecificationSync (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/parse-command-line.js:212:11)
	    at parseCommandLine (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/parse-command-line.js:147:40)
	    at start (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/start.js:37:16)
	    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/main.js:40:1)
	    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/main.js:42:3)
	    at Module._compile (module.js:571:32)
	    at Object.Module._extensions..js (module.js:580:10)
	    at Module.load (module.js:488:32)
	    at tryModuleLoad (module.js:447:12)
	    at Function.Module._load (module.js:439:3)
```

That error message looks specific to https://github.com/atom/atom/pull/16845?

I'll ask the team to take a look.

**Comment by rsese** [comment]
Thanks @ShaneBeee it looks like you're getting the same error:

```
Apr 23 07:22:32 Shanes-MacBook-Pro Atom[951]: Error: Unable to read supplied project specification file.
	    at readProjectSpecificationSync (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/parse-command-line.js:212:11)
	    at parseCommandLine (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/parse-command-line.js:147:40)
	    at start (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/start.js:37:16)
	    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/main.js:40:1)
	    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/main-process/main.js:42:3)
	    at Module._compile (module.js:571:32)
	    at Object.Module._extensions..js (module.js:580:10)
	    at Module.load (module.js:488:32)
	    at tryModuleLoad (module.js:447:12)
	    at Function.Module._load (module.js:439:3)
```

**Comment by ShaneBeee** [comment]
Hopefully its fixable :)

**Comment by maxbrunsfeld** [comment]
I can reproduce this locally running a master build of Atom. Fixing now.

**Comment by ShaneBeee** [comment]
@maxbrunsfeld  Hey, since this is closed and merged, do you know how long it'll be before its released?

**Comment by maxbrunsfeld** [comment]
I will publish Atom 1.26.1 this week.
