### ISSUE TITLE
Automatically Update setting is just ignored on update to v1.26.0 and v1.27.0-beta

### ISSUE THREAD

**Issue by t9md** [atom/atom#17172]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I’m disabling auto-update of Atom by unchecking “Core > Automatically Update”.
So I normally need to manually “Check Update” to download new update.
But strangely, this time update is done automatically for both stable and beta.
This “auto update” setting seem to be ignored.
I checked in atom's slack channel and knew @ben3eee also hit this issue.

![settings_ ___downloads_vimconf](https://user-images.githubusercontent.com/155205/38978327-0b5c13d8-43f2-11e8-9276-e97d78e47883.jpg)

### Steps to Reproduce

1. start atom older than v1.26 with disabling auto-update
2. click "Atom" menu and see that "downloading update" automatically started before you instruct "check update".

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

latest update server or atom-stable and atom-beta

**Comment by Ben3eeE** [comment]
I have the setting disabled and when I started `Atom 1.26.0-beta2` it automatically downloaded `1.27.0-beta0`

**Comment by raduserbanescu** [comment]
This happened to me too. The option *"Automatically Update"* is disabled since I first installed Atom. Yet, I was automatically updated from 1.25.1 to 1.26.0 (using 32bit version on Windows 7 64bit).

**Comment by maxbrunsfeld** [comment]
Sorry about this everyone, a fix will go out this week in Atom 1.26.1.
