### ISSUE TITLE
npm, gitbash, atom don't play well together: npm WARN saveError EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by h3rb** [atom/atom#17187]
### Description

This happens to me when using GIT BASH and ATOM editor. If I have the project folder open in ATOM, npm generates npm WARN saveError EPERM: operation not permitted, rename

In the course of discovering this, I tried to take a lot of advice I found https://github.com/npm/npm/issues/9696 (here):

- turning off real-time protection in Windows Defender (no help)
- creating windows defender exceptions for the npm, development, project, nodejs and other related folder trees (python27) (no help)
- running gitbash escalated as administrator (no help)
- running npm cache clear or npm cache verify (no help)

It just came down to the fact that the file was locked by Atom Editor. (But it was not loaded in Atom, it was just in the project folder that was loaded.) This can happen when WinSCP is accessing the folder or the file, or other editors have it loaded (Notepad++ maybe? Komodo? not sure). Visual Studio somehow avoids the locking issue and gets a signal when a file has changed. I may submit an issue to Atom.io

### Steps to Reproduce
install on this environment:

Windows 10 64-bit Build 16299.rs3_release.170928-1534
Atom 1.26.0 x64
minty 2.8.5 / mingw64 / gitbash
git version 2.16.2.windows.1
$ npm --version
5.6.0

in gitbash, with nodejs 8.11.x and 5.6.0 npm attempt to update a package when, in atom editor, you have the project loaded.

sample output:

h3@DESKTOP-0KJDD63 MINGW64 /F/Development_Electron/elec-app (master)
$ npm install --save pixi.js
npm WARN saveError EPERM: operation not permitted, rename 'F:\Development_Electron\elec-app\package.json.1700113403' -> 'F:\Development_Electron\elec-app\package.json'
+ pixi.js@4.7.3
updated 1 package in 3.357s

**Expected behavior:** [What you expect to happen]

atom plays nice, responding to filesystem changes and not locking folders/files on windows

**Actual behavior:** [What actually happens]

npm blocked by atom

**Reproduces how often:** [What percentage of the time does it reproduce?]

always

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom  -- sort of similar to others, but not precisely
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Versions

Atom 1.26.0 x64

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Note: I do have the Github module installed.  I have turned on Filesystem Diagnostics Trace to just see if this has any useful data.

**Comment by h3rb** [comment]
Related to https://github.com/atom/atom/issues/17013

**Comment by h3rb** [comment]
Atom 1.24.1

ok the first time I ran npm I got a package-lock.json (may be related to package already being installed)
the second time i ran npm, on a different package, it did work.

command tested successful with:
npm install --save electron-build

**Comment by rsese** [comment]
Thanks for confirming that things work in 1.24.1 - a fix has been merged for https://github.com/atom/atom/issues/17013 and will be available in a future release but in the meantime, manually creating a `\recovery` folder in your Atom home directory (e.g. `C:\Users\YOUR_USERNAME\.atom\recovery` and restarting Atom should fix things. 

If not, please let us know.
