### ISSUE TITLE
Make file type -> language mapping locally configurable

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#1718]
Several halp issues about people wanting to add extensions to language plugins.

Currently they have to fork the package to do this, might be nice to support this through the config.

**Comment by PEM--** [comment]
+1

**Comment by shaunbent** [comment]
+1

**Comment by johngeorgewright** [comment]
Would love this feature. All my `.tag` files are seen as "Java Server Pages" when I want them as "JavaScript (JXP)".

**Comment by rsanchezsaez** [comment]
Somebody replied on [StackOverflow](http://stackoverflow.com/a/28142113/269753] pointing to the *file-types* package as way to achieve this. I have not tried it but looks legit.

**Comment by johngeorgewright** [comment]
Thanks @rsanchezsaez. That works form me.

**Comment by fundon** [comment]
How to custom them?

**Comment by alexchandel** [comment]
The fact that a `file-types` package is necessary is symptomatic of a design flaw. It seems like it would be so easy to implement. Each package lists its file types in its settings, e.g. `File Types: applescript, script editor`. An additional field allowing user-specified file types would solve this problem.

**Comment by peirancao** [comment]
+1

**Comment by aneeshjajodia** [comment]
When will this thing launch then?

**Comment by davedan7** [comment]
+1

**Comment by alexbooker** [comment]
:+1:

**Comment by smiller171** [comment]
:+1:

This is the #1 issue preventing me from using Atom

**Comment by TheDodd** [comment]
+1

**Comment by endzyme** [comment]
+1

**Comment by franklingu** [comment]
+1. a UI actaully works better

**Comment by mudfly** [comment]
+1

I need to add saltstack .sls files to language-yaml

**Comment by nathansobo** [comment]
:clap: :clap: :tada:

**Comment by maxbrunsfeld** [comment]
Ok, in next Atom release (1.0.8) you'll be able to do this:

```coffee
'*':
  'core':
    'customFiletypes':
      'source.yaml': ['.sls']
      'source.cpp': ['h']
      'source.ruby': [
        'Cheffile'
        'rb2'
      ]
```

The arrays can contain file names or file extensions, similar to the way filetypes are listed in Atom's grammars.

**Comment by steelbrain** [comment]
Beautiful :clap:

**Comment by izuzak** [comment]
:star2: :star2: :star2: :star2: :star2:  @maxbrunsfeld

**Comment by imsinu9** [comment]
+1. Waiting for 1.0.8

**Comment by MiincGu** [comment]
+1

**Comment by stffndtz** [comment]
great!

**Comment by mmcbride1007** [comment]
@maxbrunsfeld is it possible with this to have `.css` files use `.scss` syntax? I tried adding this to my config with no luck:

```coffeescript
"*":
  core:
    customFileTypes:
      "source.css.scss": [
        ".css"
      ]
```
am I missing something? sorry if this isn't the right place to ask that...

**Comment by balexand** [comment]
I also couldn't get this to work in 1.0.9. I'm using the following:

```
'*':
  'core':
    'customFileTypes':
      'source.js.jsx': [
        '.js'
      ]
```

**Comment by maxbrunsfeld** [comment]
Oh, sorry for the confusion @mmcbride1007, @balexand. You should not include the `.` characters in the filetypes list. We need to add some docs and validation for this so it doesn't silently fail.

**Comment by mmcbride1007** [comment]
Thanks @maxbrunsfeld!

**Comment by monotasker** [comment]
I'm trying to get Atom to treat .txt files as markdown, but can't get it to work. Here's what's in my config:

    "*":
      core:
        customFileTypes:
          markdown: [
            ".txt"
          ]

Am I getting something wrong here?

**Comment by balexand** [comment]
@monotasker You need to drop the `.` in `.txt` and use a valid scope:

```
"*":
  core:
    customFileTypes:
      "source.gfm": [
        "txt"
      ]
```

**Comment by stffndtz** [comment]
works like a charm - but +1 for documentation. thanks!

**Comment by omnidan** [comment]
any idea why adding this to my `config.cson` within `"*"` and `core`:

```
    customFileTypes: [
      "source.js": [
        "js-semantic"
      ]
    ]
```

causes Atom to refresh the file and remove the line when restarting Atom after saving the file? I use [language-javascript-semantic](https://atom.io/packages/language-javascript-semantic) and want to make sure every `.js` file uses semantic highlighting.

BTW: I looked at the source code of the plugin and it seems to try to take precedence over the normal javascript language, doesn't seem to work for me, though

**Comment by TangMonk** [comment]
Not work with following config

```
"*":
  core:
    customFileTypes:
      "source.cson": [
        "ruby"
      ]
```

**Comment by balupton** [comment]
@TangMonk getting the same thing

**Comment by MicahMartin** [comment]
Any Docs on this yet?

**Comment by thomasjo** [comment]
> Any Docs on this yet?

Nothing elaborate besides the config schema description (which should be sufficient) in the PR that introduced the functionality: [config-schema.coffee#L32](https://github.com/atom/atom/blob/0203438669e5ef10a3d048d72e2a005ca84189eb/src/config-schema.coffee#L32). Any help on documenting this in e.g. https://github.com/atom/docs would be greatly appreciated.

**Comment by izuzak** [comment]
@MicahMartin @thomasjo For now, I opened an issue on that repository so that we don't forget to add docs: https://github.com/atom/docs/issues/124.

**Comment by stijnsanders** [comment]
Hmm, I'm on v1.0.19 now and the settings tab is showing extra fields "Custom File Types Source" with the edit-box set to "[Object object]" and "Custom File Types Source Pascal" and an empty edit box. I guess the "Source Pascal" is from the bit I've added to config.cson:

    customFileTypes:
      "source.pascal": [
        "xxm"
        "xxmi"
      ]

**Comment by 50Wliu** [comment]
> the settings tab is showing extra fields "Custom File Types Source" with the edit-box set to "[Object object]" and "Custom File Types Source Pascal" and an empty edit box.

This will be fixed in the next release of Atom.

**Comment by derwaldgeist** [comment]
I tried this new setting to switch .html files from HTML to Spacebars. But I can't get it to work.

According to the docs, the config should be:

```cson
"*":
  core:
    customFileTypes:
      "source.spacebars.embedded.html": [
        "html"
      ]
```

But it still defaults to HTML instead of Spacebars. I've got the ```source.spacebars.embedded.html``` tag from the source code of the Spacebars plugin.

**Comment by Marqin** [comment]
@derwaldgeist It worked for me on Atom `1.2.4` on OS X. I had problem with .conf files being opened with Apache language ( I wanted to open them by default as Nginx ), and this config helped:
    "*":
      core:
        customFileTypes:
          "source.nginx": [
            "html"
          ]
From what I see, project that You are mention uses `text.html.spacebars` as [their scope name](https://github.com/Zaku-eu/atom-language-spacebars/blob/master/grammars/spacebars.cson#L459) instead of `source.spacebars.embedded.html`.

**Comment by derwaldgeist** [comment]
Thanks, I will try this!

**Comment by jdnier** [comment]
@omnidan You have an extra set of brackets. Try this instead (survives restarting Atom):

```coffeescript
  core:
    customFileTypes:
      "source.js-semantic": [
        "js"
      ]
```

**Comment by omnidan** [comment]
@jdnier Thanks for the info :smile: Shouldn't it be `source.js` and `js-semantic` though (not the other way around)?

**Comment by oshliaer** [comment]
> v1.4.3

```coffee
core:
    customFileTypes:
        "source.js": [
            "js-semantic"
        ]
```
It works fine. But this way registers an extension as the scope's (from the example as `source.js`) Grammar. This can be confusing for some extensions of Atom.

**Comment by emattias** [comment]
Is there support for extensionless files?

This doesn't work for me:

```coffee
"*":
  core:
    customFileTypes:
      "source.shell": [
        ""
      ]
```

**Comment by alexchandel** [comment]
As the confusion and abundant trailing comments make clear, there needs to be a GUI for this, just like the Keybindings GUI.

**Comment by Pysis868** [comment]
I wonder if this can reload the active views automatically, in case I have the file open already I want it to update and use the appropriate, new grammar I have just specified?

Even better, add the ".railsrc" file I was working in to a core list inside Atom :).

I have posted more information here: [Atom - Discuss - Edit/Set File Associations](https://discuss.atom.io/t/edit-set-file-associations/2650/19)

**Comment by 50Wliu** [comment]
> Even better, add the ".railsrc" file I was working in to a core list inside Atom :).

Feel free to do so by editing https://github.com/atom/language-ruby-on-rails/blob/master/grammars/ruby%20on%20rails.cson (I'm assuming `.railsrc` is Ruby on Rails?  If it's not just find the appropriate language repository) and submitting a PR.

**Comment by Pysis868** [comment]
hm, after some Googling I have found `.railsrc` to actually be more of a plain text file that merely contains shell-like options on each line.

It seems the code I used from this post [luca pette - Pry Everywhere](http://lucapette.me/pry-everywhere/) uses the filename incorrectly, as the style I just found elsewhere is more prevalent.

Since this is Atom's default grammar, I will leave it untouched :).

**Comment by omniacode** [comment]
Hate to reopen this discussion again, but this doesn't seem to be working in v1.8? Anyone else having issues with this? According to this thread, this should work:

`customFileTypes:
      "source.pdt": [
        "php"
      ]`

**Comment by undercoverSG** [comment]
Not working for me ever for rapid language which is mod extension:
  customFileTypes:
        "source.python": [
            "mod"
        ]

What is really missing is the possibility to customize your own  grammar and style. Like for new language or very old one. (RUST, Pascale, DELPHI, Basic..)

Having the possibilty to customize your own language would be pretty useful

**Comment by stijnsanders** [comment]
I'm using [language-pascal](https://atom.io/packages/language-pascal) for Delphi, which works kind-of OK.

**Comment by undercoverSG** [comment]
Yes in that case it works, but for instance, if i do assembly, what will you use ? 

The feature is pretty cool it is sure, but i'm wondering how to make my own syntax coloring for any language that have no common point with an other.

**Comment by viktorsec** [comment]
+1
