### ISSUE TITLE
Atom crashed

### ISSUE THREAD

**Issue by jglovier** [atom/atom#1719]
So Atom just crashed on me.

I was trying to update Bracket Matcher. I didn't see an update available via the Settings view, so using @kevinsawicki's [suggestion](https://github.com/atom/bracket-matcher/issues/7#issuecomment-36926407), I updated the package via command line. Then I switched back to Atom, and it didn't appear to have been updated (the view for the package in Preferences still showed version `0.23.0`), so I restarted.

Once I restarted, I got a blank screen, and then this: ![image](https://f.cloud.github.com/assets/1319791/2350670/5bb32f82-a573-11e3-9a01-af14b8a99d15.png)

Then moments later, OS X Problem Reporter, which generated [this report](https://gist.github.com/jglovier/c376ed285cc87dbeb107).

**Comment by as-cii** [comment]
@jglovier Have you experienced that issue again? Can we consider this solved?

**Comment by jglovier** [comment]
I have not, no. But I haven't been using Atom as my FT editor since around last August. In any case, I'd say go ahead and mark it resolved.

**Comment by benogle** [comment]
Thanks @jglovier
