### ISSUE TITLE
Template string syntax stop working

### ISSUE THREAD

**Issue by douglasduartetb** [atom/atom#17194]
Hi, i update to last vesion and template strings with highlight stop working.

![Error image](https://user-images.githubusercontent.com/7443043/39085555-bfa07528-455a-11e8-9405-8553811a0f49.png)

Version: 1.26.0 x64, windows 7

**Comment by rsese** [comment]
Thanks very much for the report!

I assume that's JavaScript?  If so, would you mind reopening this issue in the https://github.com/atom/language-javascript repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Please fill out the issue template as well, the information in the template is super helpful for us when triaging issues.

Thanks for meeting us half way 👍
