### ISSUE TITLE
macOS: CMD+backtick does not work in editor

### ISSUE THREAD

**Issue by fchoquet** [atom/atom#17227]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On mac we can normally use CMD+backtick to switch between open windows of the same application. 
In Atom it works fine from the menu or project pane, but not from the editor. It actually inserts a backtick, which is not the intended behavior.

### Steps to Reproduce

1. Open 2 Atom projects in 2 windows
2. In project 1, click into the editor. You should see the cursor blinking and be able to type text
3. Use the CMD+backtick key combination

**Expected behavior:** Activate the project 2 window

**Actual behavior:** A backtick is inserted in the editor. 

**Reproduces how often:** 100%

### Versions

Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 2.7.10
git 2.15.1

OS: macOS 10.13.4

French keyboard layout

### Additional Information

Looks like it's similar to this issue https://github.com/atom/atom/issues/11531 but in my case the key binding works from any pane or menu except the editor.

**Comment by rsese** [comment]
Thanks for the report!  Just mentioning that I can reproduce with a French keyboard layout on macOS 10.12.6 and Atom 1.26.1.
