### ISSUE TITLE
«Editor: Toggle soft Wrap» reseted when open «Find and Replace» by Ctrl-F

### ISSUE THREAD

**Issue by Eskander88** [atom/atom#17238]
1. I apply command «`Editor: Toggle soft Wrap`». 
2. Press short key `ctrl-f` (open `Find and Replace` toolbar)
3. `Editor: Toggle soft Wrap` applied automatically in this moment

Atom vesion -1.25.1 x64
Atom vesion -1.27.0-beta1 
OS – Windows 10 x64

**Comment by rsese** [comment]
Thanks for this one too @Eskander88!  We tried to reproduce this one but couldn't - in case we're missing something however, can you update the issue body to fill out the issue template information?  In particular, confirm if you can reproduce in safe mode and if you can add a GIF or screencast of the behavior, that might be helpful too.

Once you add that info we can re-open and go from there.

**Comment by Eskander88** [comment]
### Steps to Reproduce
1. Open new window `atom --safe`
2. Create new pane: `ctrl-n`
3. Copy-paste example text, writed below:
```
Vivendum dignissim conceptam pri ut, ei vel partem audiam sapientem. Mandamus abhorreant deseruisse mea at, mea elit deserunt persequeris at, in putant fuisset honestatis qui. Tation delenit percipitur at vix. Per cu iracundia splendide. An nam debet instructior, commodo mediocrem id cum. Per cu iracundia splendide.
Oratio accumsan et mea. Vivendum dignissim conceptam pri ut, ei vel partem audiam sapientem. Magna copiosae apeirian ius at. Per in illud petentium iudicabit, integre sententiae pro no. Oratio accumsan et mea. Vivendum dignissim conceptam pri ut, ei vel partem audiam sapientem. Ceteros assentior omittantur cum ad.
Sea esse deserunt ei, no diam ubique euripidis has. Ceteros assentior omittantur cum ad. Postulant assueverit ea his. Vel in dicant cetero phaedrum, usu populo interesset cu, eum ea facer nostrum pericula. Oratio accumsan et mea. . Oratio accumsan et mea. Tation delenit percipitur at vix. Sale liber et vel.
```
3. Press assigned shortkeys `ctrl-k` in `keymap.cson` for `Editor: Toggle Soft Wrap`
4. Horizontal scroll bar is hidden
5. Press `ctrl-f`
6. Panel `Find and Replaced` is opened and command `Editor: Toggle Soft Wrap` is reseted
7. Horizontal scroll bar is showed

my config file **KEYMAP.CSON**
```
'ctrl-tab': 'pane:show-next-item'
'ctrl-shift-tab': 'pane:show-previous-item'
'atom-workspace':
  'alt-shift-f': 'pigments:find-colors'
  'ctrl-k': null
  'ctrl-shift-k': null

'.workspace':
  'ctrl-shift-z': null

  'ctrl-shift-k': 'editor:toggle-soft-wrap'
  'ctrl-y': 'editor:delete-line'
  'ctrl-k': 'editor:toggle-soft-wrap'

 'ctrl-alt-m': 'minimap:toggle'
 'alt-shift-w': 'custom:close-panes-besides-current'
 'alt-o': 'open-in-browsers:toggle'
```

**Reproduces how often:** 
100%

### Version 
```
Atom    : 1.27.0-beta1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

OS: Windows 10 x64
```

**Comment by rsese** [comment]
Thanks @Eskander88 - we weren't able to reproduce just using the commands directly and not with your custom keybindings but after using your keybindings, I could reproduce.

Looking at the keybinding resolver, it looks like an issue using <kbd>ctrl-k</kbd>.  I see you try to unset <kbd>ctrl-k</kbd> but I think it might take more work to unset it e.g. see:

https://discuss.atom.io/t/how-to-remap-ctrl-k/19217/

If you use a different keybinding (e.g. <kbd>ctrl-shift-e</kbd> isn't bound by default and that worked for me) or you can try the package mentioned in the post, that should work.
