### ISSUE TITLE
Warn if using a git package with an unsupported version of Atom

### ISSUE THREAD

**Issue by UziTech** [atom/atom#17247]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When a package is installed from a git repository Atom doesn't check the [`engines`](https://docs.npmjs.com/files/package.json#engines) field in `package.json`. Atom should at least warn the user that their version of atom is not supported by that package, or wouldn't allow the package to be enabled/updated/installed like with regular community packages.

### Steps to Reproduce

1. Install a git package that doesn't support your version of atom. I have set up a package called [`test-engines-package`](https://atom.io/packages/test-engines-package) for this situation at https://github.com/UziTech/test-engines-package

**Expected behavior:** [What you expect to happen]

Somewhere Atom should warn that this package does not support this version of Atom

**Actual behavior:** [What actually happens]

Nothing. The package installs just fine.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.27.0-beta1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0-beta1
python 2.7.14
git 2.17.0.windows.1
visual studio 2015

### Additional Information

resubmitted from #14222

**Comment by UziTech** [comment]
This issue is still reproducible on v1.37.0-beta1 windows

**Comment by UziTech** [comment]
still an issue

**Comment by duochen13** [comment]
In the package.json, it says 
```
"engines": {
    "atom": ">=1.17.0 <2.0.0"
}
```
isn't the atom version 1.27.0 within the range >=1.17.0 <2.0.0?

**Comment by UziTech** [comment]
Which `package.json` says that?

The test-engine package it says:

```json
  "engines": {
    "atom": ">=100.0.0"
  },
```

https://github.com/UziTech/test-engines-package/blob/master/package.json#L13

**Comment by duochen13** [comment]
Cool I installed the package through **apm install test-engines-package**, and the package.json within path_to_atom/**.atom/packages/test-engines-package** directory

**Comment by UziTech** [comment]
@duochen13 that is because it did not install the latest version. Instead it installed the version that matches your version of Atom and probably warned you that there is a newer version that is not for your version of Atom. This issue is that Atom doesn't display that warning when installing through a github url.

install with `apm install https://github.com/UziTech/test-engines-package` and check the `package.json` of the installed package.

**Comment by UziTech** [comment]
Still an issue
