### ISSUE TITLE
Missing GConf2 dependency in rpm package

### ISSUE THREAD

**Issue by egdoc** [atom/atom#17241]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
The Atom rpm package is missing GConf2 dependency. 

### Steps to Reproduce

1. Install Atom (using repository or directly with rpm package)
2. Try to launch atom

**Expected behavior:**
Atom gets launched correctly

**Actual behavior:**
Atom it's not launched because of the missing dependency. The error is:
$ /usr/share/atom/atom: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Reproduces how often:** 
Always (until GConf2 is installed)

### Versions
All versions. Running on Fedora 27

### Additional Information
The missing dependency  doesn't get noticed when installing Atom on default Fedora Workstation
because some other package requires GConf2 which is already installed. However installing on a
customized environment highlights the problem. Altering the rpm with rpmrebuild and adding GConf2 as dependency solves the issue.

**Comment by cristianarbe** [comment]
Having this same problem, but don't understand the workaround to make it work. Can someone break it down?

**Comment by egdoc** [comment]
@cristianarbe I am the author of that guide. Can you tell me what is the result after the changes you made?

**Comment by cristianarbe** [comment]
Yes. I have followed the guide and after finished I have checked that the dependency was added to the rpm. Although when installing the rpm (after uninstalling) it would still complain that it could not find the libgconf2 library.

**Comment by egdoc** [comment]
Can you send me the rpm you modified? (I don't know if it's ok to put it here)

**Comment by cristianarbe** [comment]
I have uploaded two packages I rebuilt, the beta one and the stable one on [Mega](https://mega.nz/#!5gp1ASBR!pvvoaD87vx9lMm8eSQKKff6lPx-Hk8NKMHnnZaRd5q0). Let me know if you have any problem downloading it and I'll upload it elsewhere.

**Comment by egdoc** [comment]
Tested the package on a live Fedora29 and it works without problems. What distribution/environment are you using?

**Comment by cristianarbe** [comment]
Using Fedora29 just re-installed a few days ago.
