### ISSUE TITLE
Atom crashes since 1.24.1 on Windows 10

### ISSUE THREAD

**Issue by setalosas** [atom/atom#17253]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Atom crashes a few minutes (sometimes seconds) after start.

It always dumps the same error to the command line it was started from:
```
$ atom --safe
@ C:\Users\chuck\Desktop\Portables\atom 1.27.0-b1\Atom Beta x64
$
[33868:0501/052040.213:FATAL:layoutobject.cpp(1040)] Check failed: isRooted().
Backtrace:
        GetHandleVerifier [0x00007FF7B3468905+23093]
        GetHandleVerifier [0x00007FF7B34D8A63+482195]
        (No symbol) [0x00007FF7B3460554]
        IsSandboxedProcess [0x00007FF7B54A401D+30342709]
        IsSandboxedProcess [0x00007FF7B56AD474+32477836]
        IsSandboxedProcess [0x00007FF7B54ED14B+30642019]
        IsSandboxedProcess [0x00007FF7B54C9617+30495791]
        IsSandboxedProcess [0x00007FF7B56BE8C9+32548577]
        IsSandboxedProcess [0x00007FF7B56BFB0E+32553254]
        IsSandboxedProcess [0x00007FF7B54A9C3A+30366290]
        IsSandboxedProcess [0x00007FF7B54AA096+30367406]
        IsSandboxedProcess [0x00007FF7B54AA0DF+30367479]
        IsSandboxedProcess [0x00007FF7B56ABF1C+32472372]
        IsSandboxedProcess [0x00007FF7B56AB78F+32470439]
        IsSandboxedProcess [0x00007FF7B56A2FD3+32435691]
        IsSandboxedProcess [0x00007FF7B53060F7+28647183]
        IsSandboxedProcess [0x00007FF7B5305CD9+28646129]
        IsSandboxedProcess [0x00007FF7B53594EC+28988164]
        IsSandboxedProcess [0x00007FF7B53592E7+28987647]
        IsSandboxedProcess [0x00007FF7B517C010+27033128]
        IsSandboxedProcess [0x00007FF7B3D0C377+5603727]
        IsSandboxedProcess [0x00007FF7B3924CD4+1510124]
        IsSandboxedProcess [0x00007FF7B3920998+1492912]
        IsSandboxedProcess [0x00007FF7B391F525+1487677]
        IsSandboxedProcess [0x00007FF7B39259CF+1513447]
        GetHandleVerifier [0x00007FF7B35ECA7C+1612716]
        IsSandboxedProcess [0x00007FF7B3D17CF7+5651215]
        IsSandboxedProcess [0x00007FF7B3A0D719+2463025]
        IsSandboxedProcess [0x00007FF7B39360BC+1580756]
        IsSandboxedProcess [0x00007FF7B3D43F31+5832009]
        IsSandboxedProcess [0x00007FF7B407C9D6+9209838]
        IsSandboxedProcess [0x00007FF7B407CD3E+9210710]
        GetHandleVerifier [0x00007FF7B350697D+670381]
        IsSandboxedProcess [0x00007FF7B5A50421+36291129]
        IsSandboxedProcess [0x00007FF7B5A4F29B+36286643]
        IsSandboxedProcess [0x00007FF7B5A4CD1D+36277045]
        GetHandleVerifier [0x00007FF7B350697D+670381]
        GetHandleVerifier [0x00007FF7B34A7B86+281782]
        GetHandleVerifier [0x00007FF7B34A6670+276384]
        GetHandleVerifier [0x00007FF7B35088B3+678371]
        GetHandleVerifier [0x00007FF7B34A3BDE+265486]
        IsSandboxedProcess [0x00007FF7B3B4A21F+3760183]
        GetHandleVerifier [0x00007FF7B37B315D+3474061]
        GetHandleVerifier [0x00007FF7B37B3054+3473796]
        GetHandleVerifier [0x00007FF7B355B93C+1018476]
        (No symbol) [0x00007FF7B31B8EDC]
        IsSandboxedProcess [0x00007FF7B642CF37+46632271]
        BaseThreadInitThunk [0x00007FFF63F43034+20]
        RtlUserThreadStart [0x00007FFF66501551+33]
```
The message above appears at the exact moment of the crash. (I made a video of that to check, yes.)

The IDE itself goes white with this message in the center:
![image](https://user-images.githubusercontent.com/21111643/39460157-52eb47d8-4d01-11e8-8044-ead0a777129b.png)

### Steps to Reproduce

This bug is very easy to reproduce, in fact I never got through the first 5 minutes. 

1. start atom
2. start working in it (do anything)
3. wait 5 minutes at most

**Expected behavior:** Not crashing.

**Actual behavior:** Crashing.

**Reproduces how often:** 100%

### Versions

I can reproduce this bug with every version of Atom (betas included) since  after 1.24.1. Actually I still use 1.24.1 as it works flawlessly and never crashes. I try periodically to update to a newer version - updating or making a standalone portable version, I tried both - with the same result (failure). The version of Atom used in this current report is:

```
$ atom --version
Atom    : 1.27.0-beta1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
$ apm --version
apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.1
python 2.7.13
git 2.14.1.windows.1
visual studio 2015
```
OS versions:
```
Windows 10 Insider Preview 17134.1 (rs4_release) (and one or two previous IP versions before that)
Windows 10 Version 1803 for x64 (just upgraded a few hours ago)
```

### Additional Information

I use quite a lot of packages, but no matter that I can reproduce the crash with `atom --safe` too. (Actually it crashed after 3-4 secs after start last time I tried.) Anyway I attach the package list.
[package-list.txt](https://github.com/atom/atom/files/1962957/package-list.txt)

Additional details to add:
1. In the devtools console of Atom I get this message immediately after start:
`<embedded>:22786 'save-session.dataSaveFolder' could not set the default. Attempted default: undefined; Schema: {"type":"string","description":"The folder in which to save project states"}`
1. I believe that every time the crash occurs, it's when I move the mouse, like it's in a mouseover handler - of course I'm not sure, it's just a hunch.
1. I could report this bug in mid-march, but I thought it's a thing of the actual beta and it'll gone - it seems it chose to stay.

**Comment by rsese** [comment]
Thanks for the report!

> [33868:0501/052040.213:FATAL:layoutobject.cpp(1040)] Check failed: isRooted().
> Backtrace:
...
> I can reproduce this bug with every version of Atom (betas included) since after 1.24.1. Actually I still use 1.24.1 as it works flawlessly and never crashes.

Based on the error and the OS you're on, it looks like this Electron issue:

https://github.com/electron/electron/issues/12472

In 1.25, we upgraded our version of Electron to 1.7.11 so I think it makes sense why you don't see the error in 1.24.1.

Do you happen to have any custom CSS in your styles.less file?

**Comment by setalosas** [comment]
I have 110k of custom LESS, yes. I would say it's quite complex. Fortunately I didn't delete the 1.27 beta folder, so I can try again with the original CSS, I'll be back with the results.

**Comment by setalosas** [comment]
So, the offending line is:

.scrollbars-visible-always ::-webkit-scrollbar-thumb:hover {
  z-index: 9999;
}

Screencast: https://drive.google.com/uc?id=1OW9JSCA9tdw39tWxSrPO34wQm0rGDjcz
(hover on the round thingy invokes the crash).

I removed all z-index rules on scroll element hoverings from my styles.less, and  I cannot reproduce the crash anymore.

Thanks!

**Comment by TheMacNerd** [comment]
uninstall reinstall

**Comment by oviliz** [comment]
Indeed. Computer sleep at 5pm and often times the next morning Atom has died and it would not even kill the process so I need to reboot (or Sign Out and back in)... Reinstalling does not fix.
I'm on 1.28 now but I was on a slightly early version till a month back or so and I keep having the same issue.

**Comment by the-j0k3r** [comment]
and crashed https://github.com/atom/atom/issues/17642

and no, reinstall and re-install doesn't fix it either.

**Comment by kafoso** [comment]
Crashes 5-30 times in an 8 hour workday. Restarting it will often cause another freeze and the editor will not work again before having had 1-4 startup crashes as well. Still doing so in version 1.33.0 (Windows 10, 64-bit).

Re-installs do not fix it. Often times no debugging information is available because the editor flat out does respond to anything or write logs.

I love the Atom editor, but this is reaching unbearable and unsatisfying levels of annoyance and inconvenience.

**Comment by rsese** [comment]
@kafoso - please open a new issue with the template filled out and we'll take a look.  This issue is specific to the referenced Electron issue, https://github.com/electron/electron/issues/12472.

**Comment by daviwil** [comment]
Hey folks, I've been trying to reproduce this issue with Atom 1.34.0 and haven't had any luck.  If any of you are still able to reproduce the issue on Windows 10, could you send the newest 2 or 3 `.dmp` files in the `%TEMP%\Atom Crashes` folder to `daviwil [at] github.com`?  This file should help us narrow down the issue.

Thanks!

**Comment by abhinav1singhal** [comment]
I am seeing same issue on version 1.36.0 ia32 on windows 10.
Not and epert in Atom, but tried to use to learn python and Django. This is happening after every 3 minutes without any activity on the editor.

**Comment by rsese** [comment]
@abhinav1singhal - please open a new issue with the template filled out and we'll take a look. This issue is specific to the referenced Electron issue, electron/electron#12472.
