### ISSUE TITLE
Atom removes windows Owner and permissions on file update and git operation

### ISSUE THREAD

**Issue by conorot** [atom/atom#17260]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom removes file owner and permissions in Windows 10 when a file is edited and a git procedure occurs in the background.
Atom    : 1.26.1
Windows 10
User: Administrator
Emmet is NOT installed
Issue is reproducable in safe mode
Antivirus: inactive

### Steps to Reproduce

1. Create a new file in an exixsting git project e.g. test.txt
2. Commit file with git commit -m "test file added" on branch "dev"
3. Open atom --safe
4. Add some text to the file test.txt
5. Commit change with git commit -m "Updated test file in atom"
6. Leave the file "open" in atom IDE
7. Switch git branch with git checkout master

**Expected behavior:** 
I expect to be able to switch branch or edit the file or delete the file test.txt

**Actual behavior:**
Git cannot change branch and throws a "Permission denied" error. I cannot close the "open" file in atom, it prompts to Save or Don't Save, if I click Save, I get:

```'test.txt' could not be saved. Error: Permission denied```

The file is essentially locked completely and the only way to resolve it is to close Atom and reset the git branch to a previous stable commit. File can't even be deleted from the Windows interface.

**Reproduces how often:** 
100%

### Versions
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

### Additional Information
I have tried the same process using Notepad to edit the file in step 4 and can complete all actions as expected. The issue does not occur. This seems to rule out git as a cuplrit as well as any Windows file permission anomolies.

I have also reproduced this issue when running Atom as Administrator.

I have also removed my antivirus as other people have reported similar issues related to various antivirus software:
https://discuss.atom.io/t/unable-to-save-file-permission-denied/47534/14

My file is on a different hard drive to my system drive (where Atom runs from), however both are owned by the same Windows user (me, the Admin). I had suspected Windows file permission errors but can confirm I am the owner of all folders which are in fact wide open with no rescritctions on any users.

Notably, when the offending file gets permission denied, the windows permissions on the file get completely removed and they end up in a state with no "owner". This means that even an Admin cannot reassign permissions to it:

![atom_issue1](https://user-images.githubusercontent.com/4416581/39520510-d46fc43a-4e02-11e8-8519-ecc120ad59d8.PNG)

By accessing Advanced settings, you can see that the Owner has been completely unset, and after clicking "Change" as an admin, it still cannot be updated:

![atom_issue2](https://user-images.githubusercontent.com/4416581/39520539-f5e52cd6-4e02-11e8-813c-29d64ccc264f.PNG)

**Comment by conorot** [comment]
This was fixed for me by following this process recommended by @Ben3eeE 

> Do you have the %USERPROFILE%\.atom\recovery folder? Can you try creating this if it doesn’t already exist and restart Atom.

**Comment by Ben3eeE** [comment]
Duplicate of https://github.com/atom/atom/issues/17013. Closed via https://github.com/atom/atom/pull/17255
