### ISSUE TITLE
update check: "The certificate for this server is invalid"

### ISSUE THREAD

**Issue by taoeffect** [atom/atom#17270]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Running "Check for updates" produces this dialog:

![screen shot 2018-05-03 at 7 29 53 pm](https://user-images.githubusercontent.com/138706/39607327-63beb50a-4f08-11e8-83f7-d5bea9b5d27b.jpg)

### Steps to Reproduce

1. From the menu, choose "Check for updates"

**Expected behavior:** for it to work. ***And if it doesn't work, for it to give me more info to share with you in order to determine whether this is an actual attack or not***

**Actual behavior:** see above

**Reproduces how often:** it's been doing this for months

### Versions

```
-> % atom --version
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

### Additional Information

I have Little Snitch installed and AFAIK it isn't blocking the connection to the update server.

Strangely enough checking for updated packages works fine.

It would be great if Atom gave me more info as to the nature of the questionable SSL cert, that would help a lot with debugging this and determining whether it's an attack or a bug or what.

**Comment by rsese** [comment]
Thanks for the report - I haven't seen any other reports like this and can't reproduce myself.  Are you on a network behind a firewall or using a proxy by any chance?  If you connect to some other network to test are you able to reproduce?

**Comment by taoeffect** [comment]
I've tried on different networks and get the same result. :-\

That's why it would be useful if Atom displayed the certificate itself somehow, similar to how web browsers can show it to you.

**Comment by taoeffect** [comment]
OK, I figured it out, it is indeed my sandboxing profile for Atom that's causing the problem somehow.
