### ISSUE TITLE
feature request: Improved UX for git integration

### ISSUE THREAD

**Issue by phlogisticfugu** [atom/atom#17289]
I tried to use the git integration with Atom https://blog.atom.io/2017/05/16/git-and-github-integration-comes-to-atom.html

But ran into a problem of using it with existing repositories.  When naively opening up repositories I'd previously cloned and am actively developing in with Atom, the git panel would continue to be stubbornly blank.

I found through much digging on my own, and this help thread:
https://discuss.atom.io/t/how-do-i-link-to-an-existing-git-and-github-repository-in-1-18/44129/14
that the issue was with the way that I organize my Atom Project Folder's, which has been:

- "git" = "Atom Project Folder"
    - "repo1" = "git repo"
    - "repo2" = "git repo"

whereas the feature only works with:
- "git" = not loaded in Atom tree view
    - "repo1" = "git repo" = "Atom Project Folder"
    - "repo2" = "git repo" = "Atom Project Folder"

which is less useful for me when I am juggling a bunch of repos, but also frustratingly opaque about how to use the Git panel.

----------
Proposed change:

- On the blank "Git" panel in Atom, to add a help message directing people as to what to do to view an existing Git repo.  It currently only instructs folks on how to make a brand new git repo.
  Perhaps: "To load an existing Git repository, open it in as a separate Project Folder"

and/or

- Change the Git panel to work like git itself.  That is to recursively go up the folder tree to determine the current git repository.  So that if say I have the file `/git/repo1/folderA/file.txt` open, that the panel will show the repo `/git/repo1/` because that is a git repository folder (has a .git subfolder).  The panel would then switch repositories depending on the currently active tab/file.

**Comment by DamnedScholar** [comment]
This is a useful suggestion, but the proper place for it is [the repo for the `github` package](https://github.com/atom/github) and a pull request to implement either proposal would have to happen on that repo, so another issue should be opened there even if the discussion continues here.

**Comment by rsese** [comment]
Thanks for the suggestions - as @DamnedScholar mentioned, feature requests for the GitHub package should go in https://github.com/atom/github. 

About this part though, there's already an issue for it:

> Change the Git panel to work like git itself. That is to recursively go up the folder tree to determine the current git repository. So that if say I have the file /git/repo1/folderA/file.txt open, that the panel will show the repo /git/repo1/ because that is a git repository folder (has a .git subfolder). The panel would then switch repositories depending on the currently active tab/file.

See https://github.com/atom/github/issues/778 and see Michelle's comment /cc https://github.com/atom/github/issues/778#issuecomment-300623327.

As a side note, for future issues please use the issue template as much as possible - the information in the template is super helpful for us when triaging issues.

**Comment by DamnedScholar** [comment]
@phlogisticfugu You should definitely start an issue in the `github` package repo about revising the less-than-helpful help text on the blank Git tab. It's a huge amount of empty space where a brief explanation of the capabilities and limitations of the Git tab could be shown. Heck, why not a tutorial? It would only be a few hundred pixels high on a vertical pane item. This is work that would benefit new and intermediate Atom users alike.
