### ISSUE TITLE
Files still open in tabs even when tabs are disabled

### ISSUE THREAD

**Issue by Sollace** [atom/atom#17282]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I just recently started using Atom, and immediately noticed the really long startup times. So, I started disabling things I didn't need, and slowly re-enabling things that I later saw as useful.

One of the first things disabled were _tabs_. I want to just use it as a text editor and don't really care about workspaces, or tabs. I'd already hacked sublime to have each file open in a new window and I'd intended to get the same behaviour now.

### Steps to Reproduce

1. Start with a fresh installation
2. Disable the tabs package
3. Open some files
4. Re-enable the tabs package

**Expected behaviour:** Whilst the tabs package is disabled each file should open in a separate window.

**Actual behaviour:** The contents of the existing window (appear to) get replaced with the last one opened. Turning on the tabs package, though, reveals that _every_ file has secretly been opened in that same window.

**Reproduces how often:** 100%

### Versions

Atom version is 1.26.1 x64

(can't run atom or apm in the command line, sorry)

OS is Windows 10 x64 build 1803.

### Additional Information

There are also other problems, unrelated, but I think the installer is borked. I had to dig the atom.exe out of my appdata folder (why is it _there_ of all place!?) to create a desktop link.

**Comment by lee-dohm** [comment]
Tabs are simply a visualization of having multiple files open in the same window pane (called "pane items" in the Atom API). Without the tabs visualization, it is still possible to open multiple files in the same pane and switch between them using the standard keys. This is by design.

**Comment by Sollace** [comment]
@lee-dohm Well that's silly. How are you supposed to know they're open if you can't see them?

I still maintain that it shouldn't keep opening files in the same window, or at least give us some option to have them open in a new instance of Atom.

**Comment by lee-dohm** [comment]
The fuzzy-finder package allows you to list all open files and switch between them using <kbd>Cmd+B</kbd> on macOS and <kbd>Ctrl+B</kbd> on other platforms. We have no plans to add the feature you're requesting, so this is going to remain closed.

**Comment by Sollace** [comment]
@lee-dohm Ah, fair enough. The description for fuzzy-finder was just "Open an editor to a file in the project with `cmd-t`." do I disabled it, along with about 40 other packages.

I will either get used to it having tabs, or reinstall sublime.
