### ISSUE TITLE
Can't open the Settings View with 'ctrl + ,' when editing files

### ISSUE THREAD

**Issue by s597wang** [atom/atom#17285]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Can't open the Settings View with <kbd>ctrl</kbd> + <kbd>,</kbd> when editing files (nothing happens after <kbd>ctrl</kbd> + <kbd>,</kbd> are pressed). However, when not in editing mode, for example, on Welcome tab or Telemetry Consent tab, the shortcut <kbd>ctrl</kbd> + <kbd>,</kbd> does work (i.e. opens the Settings View). 

### Steps to Reproduce

1. Press <kbd>ctrl</kbd> + <kbd>,</kbd>

**Expected behavior:** Opens the Settings.
**Actual behavior:** Nothing.

**Reproduces how often:** 100%

### Versions

>atom --version
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

>apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python
git
visual studio

OS: Windows 10 Education Build 16299

### Additional Information

**I have no packages installed and I am using the default atom settings** (I have not changed the keybindings. I can verify this by pressing <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd> and search for "Settings", and it says "Settings View: Open <kbd>Ctrl+,</kbd>"). 

**I have also tried with Key Binding Resolver on.** All other shortcuts (i.e. <kbd>ctrl</kbd> + <kbd>.</kbd>, <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>,</kbd>) work correctly (and the Key Binding Resolver says "Key Binding Resolver: ctrl-." or "Key Binding Resolver: ctrl-alt-,"), except <kbd>ctrl</kbd> + <kbd>,</kbd>, which the Key Binding Resolver says "Key Binding Resolver: ctrl ". (When not in editing mode, for example, on the Welcome tab, it says "Key Binding Resolver: ctrl-,", which is correct.)

**The same behaviour in Safe Mode.** 

(Thanks a lot for looking at this issue. I would be very appreciated if this can be solved.)

**Comment by rsese** [comment]
Thanks for the report!  Did this work previously but then stopped working recently?  Have you tried temporarily resetting to factory defaults?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by s597wang** [comment]
Thank you for the reply!
It did not work previously, so I reinstalled Windows 10 and then installed Atom, and it did not work.
I have tried resetting Atom to factory defaults, and it did not solve the problem. :(

**Comment by rsese** [comment]
Hmmm, based on this:

> except ctrl + ,, which the Key Binding Resolver says "Key Binding Resolver: ctrl ".

It looks like the key press isn't making it to Atom - whenever we've seen this, it's always been another application causing the issue.  For folks on macOS, they've used a program that tells you what program is taking a particular keybinding but it's macOS only.  

I wasn't able to find one for Windows after a quick search but if you can track one down, that might be helpful.

Since you've reinstalled Windows completely and then Atom (did you install other programs too?), I don't know what else we could try on the Atom side.

**Comment by rsese** [comment]
Are you still seeing this issue on the latest releases of Atom @s597wang?

**Comment by s597wang** [comment]
It is working on the latest release. Thank you for your help!
