### ISSUE TITLE
Delay between save and close file

### ISSUE THREAD

**Issue by Ky6uk** [atom/atom#17287]
### Description

When I tried to push `Cmd+S` (save file) and immediately push `Cmd+W` (close file) on changed file then atom asks me to save file before a closing it. That happens because the saving procedure has a delay with 1-2 seconds and the closing operation doesn't wait finishing of that.

**Expected behavior:**

A closing file operation waits when a saving operation will complete.

**Actual behavior:**

Both operations happen asynchronously.

**Reproduces how often:**

Each time when I am trying to save and close a file with unsaved changes.

#### `atom --version`

```
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

#### `apm --version`

```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.10
git 2.17.0
```

#### `apm list --installed --bare`

```
Stylus@3.1.1
Zen@0.18.0
atom-beautify@0.32.2
atom-ide-debugger-node@0.7.1
atom-ide-ui@0.11.1
atom-typescript@12.4.1
busy-signal@1.4.3
docblockr@0.13.7
file-icons@2.1.19
git-plus@7.10.2
ide-typescript@0.7.6
intentions@1.1.5
language-babel@2.85.0
linter@2.2.0
linter-eslint@8.4.1
linter-tslint@1.9.1
linter-ui-default@1.7.1
lorem@1.5.0
pigments@0.40.2
prettier-atom@0.53.0
project-manager@3.3.5
typescript-duck-snippet@1.0.1
zentabs@0.8.9
```

**Comment by ziyadedher** [comment]
I cannot reproduce this on my system, even with near-instantaneous saving to closing.

```
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by Ky6uk** [comment]
@ziyadedher I have no idea what exactly happens here. I just think the pressing of `Cmd+S` should register a saving stuff and `Cmd+W` should wait a finishing of that. For me that issue happens almost always 😞.

**Comment by staceyshk** [comment]
Saving, opening and closing files takes ~3s for me. This is new since my most recent update. I haven't had this issue before, the lag is quite obvious.
