### ISSUE TITLE
Click to rename [Feature Request]

### ISSUE THREAD

**Issue by matt3224** [atom/atom#17295]
When renaming files in the tree view can we rename by clicking once then again to rename just like in Finder.

See short vid in zip for example

[atom.zip](https://github.com/atom/atom/files/1991901/atom.zip)

**Comment by lee-dohm** [comment]
This sounds like an interesting idea for a package but it isn't something that we're going to be investing any time on since one can rename files in the tree-view both by right-clicking and selecting Rename from the context menu or by pressing `m` on one's keyboard.

Thanks for the feedback!
