### ISSUE TITLE
Piping input into Atom doesn't work

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1729]
support/4aa96dda9fd511e3961e21f79eba7c86

> It'd be nice if piping input into atom were possible.
> `git diff | atom`
> Right now this seems to open a second instance of Atom that immediately closes. The data goes nowhere.

This probably belongs in the feature-request arena, but also seems like something to keep track of here. Personally, I think this would be great to have. :doughnut: 

Other reports:
- support/e9fab3a2a94a11e39ef7d68ca2b55878
- support/ddc261f2a5df11e39bf33f35dc393db2

**Comment by mrmark** [comment]
:+1: from me, use this in the CLI all the time.

**Comment by jackflips** [comment]
Me too please.

**Comment by alexchandel** [comment]
This is useful for lots of things, including disassembly:
```bash
echo "foo" | atom
otool -vVjhlt /usr/lib/libSystem.B.dylib | atom
dd bs=$[128*3] count=1 if=/dev/urandom | perl -MMIME::Base64 -E 'while(read STDIN, $x, 3){print encode_base64 $x,""}' | atom
```

**Comment by alexchandel** [comment]
Another use: inspecting / modifying unknown internet scripts before use, especially ones that you don't want to `sudo`.
```bash
curl  https://static.rust-lang.org/rustup.sh | subl
```

**Comment by batjko** [comment]
Wonder how that would work with Windows, though. Piping is possible there only in Powershell.

**Comment by alexchandel** [comment]
@batjko Um... wat?

Opening `cmd.exe` and running `echo %PATH% | perl -pe "s/;/\n/g" | perl -pE "say 'And now this:'"` works as expected. So clearly that's not true.

**Comment by batjko** [comment]
I don't know about perl, never had or used it.
But if I try some standard Windows stuff, say `echo "Hello | notepad", it doesn't work.

However, I also don't get error messages, so clearly the pipe is supported in some fashion, just not many windows apps using or expecting it, I suppose.

**Comment by alexchandel** [comment]
@batjko that's because notepad hasn't been maintained since 1934, and easily beats IE for the title of "Most Garbage Program in Common Use" although `cmd.exe` comes pretty close. I can't really tell why MS hates its users so much, but they do.

On OS X, `echo "hello" | subl` works for Sublime Text. This is ridiculously useful.

**Comment by batjko** [comment]
It would be pretty neat, indeed.

**Comment by tomrossi7** [comment]
Was this issue ever addressed?

**Comment by 50Wliu** [comment]
@tomrossi7 sorry, there was a bug with the stale bot that prevented it from giving a warning comment before closing.  I've added the triaged label so that it doesn't happen again.

**Comment by schlichtanders** [comment]
so what is the status on this?

**Comment by 50Wliu** [comment]
There is no status update and no ETA for when the Atom team will have time to work on it.  As indicated by the `help-wanted` label, we would be interested in reviewing a thought-out and well-crafted PR implementing this feature.

**Comment by nousacademy** [comment]
+1 make it happen capn'!!

**Comment by gsanchezd** [comment]
👍 make it happen

**Comment by patrickreiner** [comment]
I would really like to see this implemented. It's the only reason I still have TextMate installed because I can write:

git diff | mate

If git diff | atom worked that would make my life much easier.

**Comment by MarcoSulla** [comment]
`gedit` supports pipes. It's the only reason I don't disinstalled it yet... please support pipes.

**Comment by lee-dohm** [comment]
Thanks everyone for the feedback.

We discussed this in our team meeting this morning. The maintainers aren't going to be taking this on and we will be closing this issue. We would, however, be open to reviewing a well-written pull request for this feature. Because of this, I'm going to leave this labeled with `help-wanted` so that people interested in helping out can find it easily.

Thanks again for your interest in Atom.

**Comment by Marco-Sulla** [comment]
...... shame on you......
