### ISSUE TITLE
Package::registerConfigSchemaFromMainModule not called prior to deserialization

### ISSUE THREAD

**Issue by matthewwithanm** [atom/atom#17298]
The deserializers being registered in [`registerDeserializerMethods()`][1] don't guarantee that the main module config schema has been registered. Probably this should be done in [`initializeIfNeeded()`][2]. As a result, deserializers in packages with main module config schema can wind up getting incorrect values from `atom.config.get()` (`undefined` instead of the default).

[1]: https://github.com/atom/atom/blob/8e1ed49b5fea724864e27f62d123706753ffe313/src/package.js#L493
[2]: https://github.com/atom/atom/blob/8e1ed49b5fea724864e27f62d123706753ffe313/src/package.js#L171

**Comment by lee-dohm** [comment]
@maxbrunsfeld are you handling this one?
