### ISSUE TITLE
2018-05-11 12:38:44> Program: Starting Squirrel Updater: --install

### ISSUE THREAD

**Issue by isopen** [atom/atom#17300]
### Description

![image](https://user-images.githubusercontent.com/7373292/39908659-4b84f866-5519-11e8-9120-189163e4399f.png)

Log:
https://docs.google.com/document/d/1QyIqQzRsiU-qHFG5oz4v8y97PyNmDqQPuJN8xt2M71o/edit?usp=sharing

Another such sensational moment. The update removed atom and left one shortcut for it on the desktop.

### Steps to Reproduce

1. install atom
2. install atom (in this step, interrupt the installation in the picture)
3. try again to set atom

**Expected behavior:** the update should run correctly

**Actual behavior:** [What actually happens]

**Reproduces how often:**
![image](https://user-images.githubusercontent.com/7373292/39908659-4b84f866-5519-11e8-9120-189163e4399f.png)

### Versions
Windows 10
Atom 1.26.1

### Other
I wanted to write about the two cursor at the Atom editor, but unexpectedly it happened.
Now I can not install Atom at all (I'll have to do some kind of gestures to make it work).
It seems that Atom did not have time to clean up after itself.

**Comment by rsese** [comment]
Thanks for the report:

> https://docs.google.com/document/d/1QyIqQzRsiU-qHFG5oz4v8y97PyNmDqQPuJN8xt2M71o/edit?usp=sharing

Getting permission denied on the document, can you copy/paste the log or just share it as a gist?

https://gist.github.com/

**Comment by isopen** [comment]
https://gist.github.com/isopen/174f180a574035a7c8f5bfbbbb808429

**Comment by isopen** [comment]
Do you need a document located in Gist?

**Comment by rsese** [comment]
> Just want to add. Then I cleaned the rest of the Atom files, and everything was installed. 

Just to clarify, Atom was able to install successfully after you manually removed `C:\Users\AC\AppData\Local\atom\`?

**Comment by isopen** [comment]
Yes
