### ISSUE TITLE
atom 1.26.1 crashes 

### ISSUE THREAD

**Issue by saba06** [atom/atom#17308]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
atom 1.26.1 crashes after few mins of running; I have tried to follow some of steps mentioned above but 
don't see it running any good; i don't know the specific reason. There is another issue for v1.24.X mentioned it appears to be the same 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
not to crash
**Actual behavior:** [What actually happens]
crash
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions

![screenshot 1](https://user-images.githubusercontent.com/18358742/39951283-0462fe58-554e-11e8-94ba-98305c89418d.png)

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python
git 2.17.0.windows.1

windows 10 

### Additional Information
this happen just after windows April update any significance? until previously use to work fine on 1.25.0
I have tried reinstalled 1.25.0 but also crashes!

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report -

> atom 1.26.1 crashes after few mins of running;

Are you doing anything in particular when Atom crashes or does it happen if you just leave Atom running for a few minutes?

> I have tried to follow some of steps mentioned above but

Which specific debugging steps have you tried?

> There is another issue for v1.24.X mentioned it appears to be the same

Can you share a link?

**Comment by saba06** [comment]
Nothing in particular.. once opened it just crashes after few minutes, I leave it running.
 I have tried reinstalling it along with few steps at https://flight-manual.atom.io/hacking-atom/sections/debugging/  
Opening atom in safe mode; removing  all other packages except those that come with it! Checked for Linked packages.

https://github.com/atom/atom/issues/17253

This happen just after windows 10 home April update for me; I have also tried & install previous version 1.25.0 same result..

**Comment by saba06** [comment]
So.. I read to the debugging page... & I happen to found the following in console.....
 
Uncaught (in promise) Error: Git status failed
<embedded>:133934 Uncaught (in promise) Error: Git status failed
<embedded>:230849 Uncaught (in promise) TypeError: Cannot read property 'ahead' of undefined
    at C:\Users\sandeep\AppData\Local\atom\app-1.27.0\resources\app\node_modules\github\lib\models\repository-states\present.js:775:45
    at Generator.next (<anonymous>)
    at step (C:\Users\sandeep\AppData\Local\atom\app-1.27.0\resources\app\node_modules\github\lib\models\repository-states\present.js:84:197)
    at C:\Users\sandeep\AppData\Local\atom\app-1.27.0\resources\app\node_modules\github\lib\models\repository-states\present.js:84:367
    at <anonymous>
(anonymous) @ <embedded>:230849
step @ <embedded>:230158
(anonymous) @ <embedded>:230158
<embedded>:133934 Uncaught (in promise) Error: Git status failed

This happens when i try open file that is not in a git repo.. otherwise it works fine .. i don't know weather this was intended to be... also happy to receive update 1.27

**Comment by rsese** [comment]
Thanks @saba06 - I don't know if that error is particularly related to the crash you're seeing.  Just to confirm, if you temporarily disable the GitHub package, do you still see the crash after letting Atom run for a while?

**Comment by saba06** [comment]
Having disabled git-diff, GitHub, open on GitHub packages one by one.. nope it still crashes.. But after some time… the console outputs “Git status Failed” a couple of time when this happens!

**Comment by rsese** [comment]
> Having disabled git-diff, GitHub, open on GitHub packages one by one.. nope it still crashes.. But after some time… the console outputs “Git status Failed” a couple of time when this happens!

Can you confirm that you disabled the GitHub package, quit Atom, and then restarted in safe mode and you still see this behavior?  Also, are you opening Atom with a Git project?  If you start Atom with no project open, does Atom still crash?

**Comment by saba06** [comment]
yes

**Comment by saba06** [comment]
yes; I disabled GitHub package quit to restart in safe mode. With no project open the consoles is clean; only when I open a project NOT a Git project. this behavior happens! I get "Git status Failed" uncaught exception a few times before it crashes. I re-did it just to be sure!

**Comment by rsese** [comment]
Hmmm can you check if you happen to have a `.git` directory in your home directory?  On Windows this would be something like `C:\Users\YOUR_USERNAME\.git` (this would be a hidden folder I think so you would have to enable showing hidden files and folders to see it).

**Comment by saba06** [comment]
yes I do

**Comment by rsese** [comment]
I'm assuming that wasn't intentional to have your whole home directory as a Git repository?  In Windows Explorer you can rename it to something like `.git.tmp` and I believe that will stop the crash you're seeing.

**Comment by saba06** [comment]
Awesome! works great now... Thank you! No it wasn't intentional. is it something to be deleted?

**Comment by rsese** [comment]
If it wasn't intentional you can delete that directory if you want :+1:
