### ISSUE TITLE
Atom (via deb/rpm) utilizes an executable stack.

### ISSUE THREAD

**Issue by b1ack0wl** [atom/atom#17317]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The prebuilt packages for Linux (deb/rpm) contain a version of Atom that marks the stack as Read,Write,eXecute for each Atom process.

### Steps to Reproduce

1. Download Atom for Linux (deb || rpm)
2. Launch Atom
3. Grep the process maps for Atom and look at the permissions for the stack.
3a. Command: `for i in $(pidof atom); do cat /proc/$i/maps | grep stack; done`

**Expected behavior:**

The stack should not be marked as executable.

**Actual behavior:**

The stack is marked as executable.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

### Additional Information

There's a lot of RWX pages within each atom process
```
[a@localhost ~]$ for i in $(pidof atom); do cat /proc/$i/maps | grep rwxp | wc -l; done
328
154
120
292
```

**Comment by 50Wliu** [comment]
Thanks for the issue, @b1ack0wl.  There was a [known issue](electron/electron#11628) in Electron where Electron binaries also contained executable stacks.  That was resolved in Electron 2.0, which dev builds of Atom are now using; would you mind building Atom from master and re-running your test?  Thanks again 🙇‍♂️.

**Comment by b1ack0wl** [comment]
I used the pre-built packages that's available on https://atom.io/download/deb and https://atom.io/download/rpm. The packages hosted on those sites are shipping with an out-of-date version of Electron. (v1.7 from the --version output above)

**Comment by 50Wliu** [comment]
Yes, we're aware.  We're currently testing Electron 2.0 to make sure there aren't any bugs before using it in a stable version of Atom.

**Comment by b1ack0wl** [comment]
Awesome! Thanks for the help! :+1:
