### ISSUE TITLE
Atom Removal Tool for Windows

### ISSUE THREAD

**Issue by RayBowman2017b** [atom/atom#17316]
1. Open Control Panel > programs > Programs and Features
2. Right-Click on "Atom"
3. Click on "uninstall"

**Expected behavior:** Atom to be uninstalled

**Actual behavior:** nothing happens

**Reproduces how often:**   Fails to remove 100%

If Atom will not be completely removed with "uninstall" then you need a removal tool.

**Comment by rsese** [comment]
Thanks for the report - are there entries in your `SquirrelSetup.log` from the uninstall (should be in `C:\Users\USERNAME\AppData\Local\atom`)?

Also, please use the issue template as much as possible - if some of it doesn't apply, just mention it in the section.  Besides the `Prerequisites` section, it looks like the `Versions` section was also removed - I just tested removing Atom 1.26.1 on Windows 10 and it worked ok.  What version of Atom are you running and what version of Windows?

**Comment by lee-dohm** [comment]
Thanks for the feedback. We've specifically designed the Atom installer to remove the Atom icon and program files but leave the general configuration information in place. This is a common practice on Windows. There is documentation available on [Discuss, the official Atom message board,](https://discuss.atom.io) on how to completely remove all traces of Atom from your machine, if that is your desire. Right now though, we have no plans to create a removal tool.

I'm going to go ahead and close this based on my understanding of what it is you're asking for. If I'm misunderstanding, please give us some more information as to what exactly you mean by "completely removed" and "nothing happens" and we'll take a look at reopening the issue.
