### ISSUE TITLE
Incorrect display of two lines as one.

### ISSUE THREAD

**Issue by faliagas** [atom/atom#17338]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Incorrectly displays two lines of code as a single line. Other editors display them correctly.

### Steps to Reproduce

1. Load file discretizer2d.hpp
2. --
3. --

**Expected behavior:**
[Line 50] 	int _type; // 0 BO, 1 Function, 2 Constant, 3 BC
[Line 51]	int _order[2];

**Actual behavior:**
[Line 50]	int _type; // 0 BO, 1 Function, 2 Constant, 3 BC	int _order[2];

**Reproduces how often:** Always

### Versions
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.1
python 2.7.12
git 2.7.4

### Additional Information
OS: Linux Mint 18.3

[discretizer2d.hpp.zip](https://github.com/atom/atom/files/2010707/discretizer2d.hpp.zip)

**Comment by maxbrunsfeld** [comment]
It's because there's no line-feed (`\n`) character between those declarations; only a carriage return (`\r`). Atom does not consider a single carriage return to be a line ending.

> Other editors display them correctly.

Some other editors. Sublime text does treat this as a line break, but vim does not:

![one-line](https://user-images.githubusercontent.com/326587/40147192-8cba8988-591d-11e8-9a18-3197dcb5e31a.png)

**Comment by maxbrunsfeld** [comment]
I can see how this would be annoying, but I don't think we plan to change this behavior. It would introduce a fair amount of complexity in [our core data structures](https://github.com/atom/superstring) and it's not completely clear that it'd be a net win for our users. Single CR characters are pretty much never *intentionally* used as line endings anymore.

**Comment by faliagas** [comment]
I agree that "\n" line termination has become a de facto standard and there
is no point in supporting "\r\f". Besides Atom, I'm using CodeLite with its
EOL mode setting "Default"; this may be the source of the problem. I
changed it to "Linux mode". Thanks for the help!
