### ISSUE TITLE
Installing package on atom: ETIMEDOUT

### ISSUE THREAD

**Issue by bjce** [atom/atom#17332]
I installed `Atom` on my personal Mac which works fine. I just installed `Atom` on my PC at work and have problem to install packages. Here is the version of Atom I'm running:

    T:\>atom --version
    Atom    : 1.27.0

When trying to install a packages from Atom, I get the following error: 

    connect ETIMEDOUT 54.172.170.160:443

I also try to install the package from the command line with this command: `T:\>apm install hydrogen-launcher` and got this error message:

    failed
    Request for package information failed: connect ETIMEDOUT 54.164.206.44:443 (5 attempts) (ETIMEDOUT)

I looked at [this github page][1] but it didn't help or I couldn't implement the workaround

Any idea about what the problem could be?

  [1]: https://github.com/atom/atom/issues/11387

**Comment by rsese** [comment]
Thanks for the report - can you fill out the issue template so we have all the basic information we need?

Also, are you behind a firewall or proxy at work?  

Lastly, does it matter what package you try to install e.g. does this work or do you get the same error?

```
apm install zen
```

---

We require the template to be filled out on all new issues and pull requests so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by lastingman** [comment]
I have the same issue. 
![2018-05-19 14 52 49](https://user-images.githubusercontent.com/10057502/40265943-5b0a2c50-5b74-11e8-820c-5e0696441477.png)

**Comment by bjce** [comment]
Thank you for your message @rsese. I just wanted to make clear that you're probably not dealing with the best computer ninja around. That being said, I'm going to comply to the requirement as good as I can

### Prerequisites

I cannot put X in the prerequisites because, when I run the safe mode I cannot run a script although Atom starts correctly and load the script. what is the command / keyboard shortcut to run the script without packages installed? 

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I'm not able to install packages in Atom

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by bjce** [comment]
@rsese in order to be able to fill all the prerequisite, I just need to run the code in safe mode. I did read this link: [https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode](url). Unfortunatetly Although I was able to load Atom in safe mode, I could not run a script in safe mode. I guess it has to do with the fact that the packages like Hydrogen and the shortcuts that go with it are not usable in safe mode. I know it is probably a basic question but could please help me in that case? Thank you very much for your help

**Comment by rsese** [comment]
> I could not run a script in safe mode.

Sorry were you able to install packages or are you still having trouble doing that?  But yes, if you have community packages installed, they don't run in safe mode as mentioned in the [Flight Manual](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode).

> Regarding the firewall question: yes I'm behind a firewall

If you are still having trouble installing packages, since you're behind a firewall, see if this helps:

https://github.com/atom/apm/#behind-a-firewall

**Comment by bjce** [comment]
Thank you @rsese. So yes I still can't install packages. I'm going to try your solution. Many thanks for your feedback

**Comment by aminya** [comment]
I have this problem in the new version of the Atom: 
`Request for package information failed: connect EACCES 52.86.66.223:443`

**Comment by honeo** [comment]
Have the same problem...
I think that it happened after changing the internet line to MAP-E type (IPv4 over IPv6, port cannot be opened).
Is apm install not just a get request?

Atom v1.45.0
Win10 Pro v1909
```
Fetching outdated packages and themes failed.Hide output…
Request for package information failed: connect ETIMEDOUT 34.226.171.201:443
```

**Comment by prat23k** [comment]
I have same same issue, bewlo are the configuration details

Atom V1.30
Win10
