### ISSUE TITLE
1.27.0 (Or maybe 1.26.1?) won't launch on Windows 7

### ISSUE THREAD

**Issue by twinters01** [atom/atom#17342]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Cannot launch atom since the 1.27.0 release

### Steps to Reproduce

1. Auto-updated to Atom version 1.27 on Windows 7
2. Try to launch Atom

**Expected behavior:**
Atom to launch

**Actual behavior:** 
Nothing

**Reproduces how often:** 
Every time I try to launch since the update

### Versions

atom --version doesn't work (because it's using the same .exe that I'm trying to run atom with, I assume)
apm --version says 1.26.1
The highest version in the folder structure is app-1.27.0, and I've tried running the .exe in that folder and I get the same result.
I'm not sure which version the actual .exe in the main folder is running.

### Additional Information
I tried the clear-window-state command and the resetting factory defaults solution.
I am able to manually go into the file structure and run the .exe in atom/app-1.26.1 and that works.
I also tried clearing the Roaming/atom folder because a past issue where Atom wasn't launching suggested trying that.

**Comment by steveward** [comment]
Thanks for the report @twinters01.

- When you run `atom --version` do you see an error message?
- Could you go to `%LocalAppData%\SquirrelTemp` and grab the `squirrelsetup.log` file? Please upload that as an attachment.

**Comment by twinters01** [comment]
I don't get any message, it just looks like it runs something for a split second, then prompts for a new command. Attached is a screenshot of me attempting the command, as well as the file you requested from SquirrelTemp.

**Comment by rsese** [comment]
Thanks @twinters01 - I had a chance to update from 1.26 to 1.27 on Windows 10 and things worked ok after the update (I had some similar errors in my log file that I see in your log file but you have some that I don't).   I wonder if you just install 1.27.0 again if that will fix up the command line issue with the `atom` command?

**Comment by rsese** [comment]
We'll go ahead and close this for now @twinters01 but feel free to reach out on [message board](https://discuss.atom.io/) or the [Atom Slack](http://atom-slack.herokuapp.com) if you're still having trouble with atom --version and want to take a look at that.
