### ISSUE TITLE
atom 1.27.0 with permanent 7-9% cpu load

### ISSUE THREAD

**Issue by Daijobou** [atom/atom#17345]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In Task Manager (Windows 10) have atom always 7-9% CPU. Its the only program with such much cpu load. I detect this after update atom, because my laptop is in silent mode and I hear nothing, but since update the fan must working all time for atom process.

### Steps to Reproduce

Start atom (or in safe mode)

**Expected behavior:** [What you expect to happen]

less as 7-9% cpu for doing nothing.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python
git 2.7.0.windows.1
visual studio

Windows 10 (1803)

atom in safe mode:
![grafik](https://user-images.githubusercontent.com/260343/40177536-2c05812a-59df-11e8-9614-511f56182b66.png)

**Comment by steveward** [comment]
Thanks for opening this @Daijobou. I attempted to reproduce this on my Windows 10 machine, but was only seeing CPU usage hit ~1%. 

- Are you seeing this issue happen when you start Atom in `--safe` mode with no files loaded?
- Is there any difference if you temporarily remove any custom styles that you have set?

**Comment by Daijobou** [comment]
After hours its drop suddenly to <1%. I close this issue and open again its come back with answers to your questions. :)

**Comment by Daijobou** [comment]
The issue ist back.
After "Remove project folder" and close all tabs its jump to CPU 0%
Open recent project again, its about 0-1%

**Comment by Daijobou** [comment]
After again CPU 7-10% I closed atom and want restart, but now it not responding every time with start up. Always atom updater is running. The problem is in **atom --safe** too

![grafik](https://user-images.githubusercontent.com/260343/40316893-0507ae74-5d20-11e8-917c-c158d4609cdd.png)

**Comment by steveward** [comment]
Thanks for the update @Daijobou.

Can you go to the file menu in Atom and select `Help` to see if Atom is in the process of updating?

It may also be helpful if you could upload the Squirrel installer log to see if there are any issues happening during the update process. You can find that log in the following location using File Explorer:

`%LocalAppData%\atom\SquirrelSetup.log`

Please upload that as an attachment.
