### ISSUE TITLE
Highlight on changed files is not properly removed after stage/commit using git UI.

### ISSUE THREAD

**Issue by mattcollier** [atom/atom#17352]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Atom 1.27.0 on Debian 9.

As a long time `git-plus` user, I thought I would try atom's git UI since it looks like some work is going into that.  First, my `git-plus` is still functioning properly.

Changed files are highlighted in the project pane.  However after using the git UI to stage and commit all the changed files, the changed files remain highlighted *until* I click on another application window (e.g. Chromium) and click back on the atom editor.  Alt-tab can be used as well.

### Steps to Reproduce

1. change file in a github repo
2. stage/commit the file using the git UI

**Expected behavior:** [What you expect to happen]
Changed files should no longer be highlighted in the project pane after the files have been staged and commited.

**Actual behavior:** [What actually happens]
Highlight on changed files remains until switching to another application window and back to atom editor.  After switching back, the highlight is removed.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% 

### Versions
Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks @mattcollier :+1:

This probably belongs in https://github.com/atom/tree-view but I'm curious if you see this behavior no matter how you commit?  E.g. if you commit from the command line, does the tree-view highlighting still not update?

If so, seems similar to https://github.com/atom/tree-view/issues/1036.

**Comment by mattcollier** [comment]
If I do a command line commit (git version 2.11.0), the highlighting works properly.  It works properly without changing the active application windows.  That is, I've arranged my terminal and atom windows so that I can see them both.  As soon as I issue the `git commit` command the highlighting is properly removed in the atom window.

I'm going to try disabling git-plus (which is still working properly) just to see if there is any interference coming from there.

**Comment by mattcollier** [comment]
Disabling git-plus made no difference.  I can add now that I tried collapsing and expanding the tree view after doing a commit but the highlight remains.  The only thing that seems to trigger the removal of the highlight is focusing the atom window after it has lost focus.

**Comment by rsese** [comment]
> If I do a command line commit (git version 2.11.0), the highlighting works properly.

Oh that's interesting - when you tried in safe mode was there any difference?  The GitHub package is a core package so is still enabled in this case.

**Comment by mattcollier** [comment]
Same incorrect behavior in safe mode.  However, I did just discover that closing a changed file (tab), after commit, and reopening will cause the highlight to be removed.
