### ISSUE TITLE
ERB files default to HTML syntax highlighting

### ISSUE THREAD

**Issue by jglovier** [atom/atom#1737]
Atom appears to default to `HTML` syntax highlighting for docs labeled `filename.html.erb` instead of `HTML (Ruby - ERB)`, which of course is problematic because in regular HTML syntax highlighting embedded ruby variables are not highlighted correctly.

**Comment by chorstikus** [comment]
+1

**Comment by quozd** [comment]
+1

**Comment by ngelx** [comment]
+1

**Comment by danmolloy** [comment]
+1

**Comment by marek2901** [comment]
+1

**Comment by piperniehaus** [comment]
+1

**Comment by francisbautista** [comment]
+1

**Comment by humansounds** [comment]
+1

**Comment by jedmurdock** [comment]
+1

**Comment by nkcr** [comment]
+1

**Comment by CodeHex** [comment]
+1

**Comment by fabianschwarzfritz** [comment]
+1

**Comment by LandonSchropp** [comment]
+1

**Comment by kzeon** [comment]
+1

**Comment by HarlemSquirrel** [comment]
This seems to be working correctly for me wit Atom 1.8

**Comment by kevgathuku** [comment]
Also seems to be working okay with Atom 1.8 and above. ERB files are correctly identified as `HTML (Ruby - ERB)`
