### ISSUE TITLE
Some Filenames Underlined in Yellow

### ISSUE THREAD

**Issue by M1k3Comm** [atom/atom#17374]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Some file names in my project pane are underlined in yellow similar to Microsoft Word when a word has been misspelled (see image below).  

<img width="109" alt="atom_yellow_line" src="https://user-images.githubusercontent.com/39463448/40280967-a608807e-5c20-11e8-9293-fd225d5f3cc5.png">

### Steps to Reproduce
1. Open Atom
2. Select Project Folder
3. See Filenames in Project Pane under project Folder
4. Notice some underlined in yellow

**Expected behavior:** [What you expect to happen]
The File name should just appear as normal without the yellow line.  It's only recently that this has started occurring.  

**Actual behavior:** [What actually happens]
Yellow line appears even after the file is closed or Atom is reloaded.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Occurs every time for some files but not all.

### Versions
macOS High Sierra Version 10.13.4

**atom --version**
Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

**apm --version**
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python 2.7.10
git 2.10.1

**Comment by HipplerJ** [comment]
It looks like your using C for your development.  Are you also using any external packages like linter and linter-clang.  Include a list of your community packages if you could.  This can be done by running a command like apm list --installed --bare > comm_package.txt from the Apple terminal which will write all that information to a file called comm-package.txt.  If you do have linter-clang install, confirm that no warnings or errors are listed down in the very bottom left tray.  I've noticed in the past that if I have a warning present in any of my C/C++ files with linter-clang installed, It will underline my files like how you mentioned (Yellow for warnings.  Red for Errors).

**Comment by M1k3Comm** [comment]
Here's a list of my community packages.  You right, looks like linter/linter-clang are installed (thanks for that command, by the way).  I don't ever remember installing that, but it looks like it did have a warning listed and when corrected it removed the yellow underline. Thanks for the quick response!

autocomplete-ctags@0.4.1
busy-signal@1.4.3
file-icons@2.1.21
highlight-selected@0.13.1
intentions@1.1.5
**linter@2.2.0
linter-clang@4.1.2**
linter-ui-default@1.7.1
script@3.17.3

**Comment by HipplerJ** [comment]
No worries! Glad we got it sorted out!  I'll admit that I only knew what was going on because I'd seen this before in some of my projects.  Good luck with your programming!

Also, I'm not officially listed as a contributor so could you close this issue out if you're confident everything's working.

**Comment by M1k3Comm** [comment]
For sure, thanks again for your help!
