### ISSUE TITLE
Native title bar displaying with custom or custom-inset options in 1.28.0-beta.0

### ISSUE THREAD

**Issue by mikemcbride** [atom/atom#17377]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Native title bar always displaying in Atom 1.28.0-beta.0 when choosing `custom` or `custom-inset` title bar options.

### Steps to Reproduce

1. Go to Preferences > Core > Title Bar
2. Choose `custom` or `custom-inset`
3. Restart Atom (to allow new title bar to take effect)

**Expected behavior:** Native title bar is not displayed.

**Actual behavior:** Native title bar is displayed above the custom title bar.

**Reproduces how often:** 100%

### Versions

Atom: `1.28.0-beta.0`
apm: `1.19.0`
macOS 10.12.6

### Additional Information

I suspect this may be due to a changed API in Electron 2.0, but I haven't had time to dig in and verify this theory yet. Also of note, this works as expected when choosing the `hidden` or `native` options.

### Screenshots

With `custom-inset` selected. Notice there are two title bars - the native one and the custom-inset one. `custom` does the same thing, but I figured it wasn't worth an extra screenshot.

![image](https://user-images.githubusercontent.com/6248612/40308726-c44567ee-5ccc-11e8-80b7-b7df69f86f5f.png)

With `hidden`:

![image](https://user-images.githubusercontent.com/6248612/40308765-df2a06fa-5ccc-11e8-9db2-0966a8f8ac03.png)

And with `native`:

![image](https://user-images.githubusercontent.com/6248612/40308804-0199ec50-5ccd-11e8-9811-17f9e51f2033.png)

**Comment by rsese** [comment]
Thanks for the report!  Confirmed in `1.28.0-beta1` on macOS 10.12.6 and that the native title bar wasn't shown on top of the custom title bar in `1.27.0-beta1` (which is on Electron 1.7.11).

> I suspect this may be due to a changed API in Electron 2.0

/cc the pull request referenced above https://github.com/atom/atom/pull/17373

**Comment by mikemcbride** [comment]
good deal, thanks!

**Comment by jasonrudolph** [comment]
Fixed in https://github.com/atom/atom/pull/17373. We'll incorporate this change into Atom 1.28.0 before it graduates from beta to stable.
