### ISSUE TITLE
Numpy & Matplotlib suddenly cannot be imported in Atom although it works fine in the Terminal

### ISSUE THREAD

**Issue by bjce** [atom/atom#17375]
### Prerequisites
Unfortunately I cannot put X in the prerequisites because, when I run the safe mode I cannot run a script although Atom starts correctly and load the script. what is the command / keyboard shortcut to run the script without packages installed? Otherwise I did read FAQs and debugging guide but I still couldn't solve the problem

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

I'm regularly importing `Numpy` and `Matplotlib` in `Atom`. They unexpectedly cannot be import for an unknown reason and then appear to be again re-importable, again unexplained.

When trying to import matplotlib with the following command

    import matplotlib.pyplot as plt

This scripts runs without problems when I run in a `Jupyter notebook` or through the `Terminal`. But When trying to run on `Hydrogen` in `Atom`, I get the following error message: 

    File "<ipython-input-3-3dc8365ef973>", line 6
    ModuleNotFoundError: No module named 'matplotlib.backends'; 'matplotlib' is not a package
                                 ^
    SyntaxError: invalid syntax

I get the same error with Pyside2 when trying to run the line 

    from PySide2.QtWidgets import QApplication, QLabel

I get the error message

    ModuleNotFoundError: No module named 'PySide2.QtWidgets'; 'PySide2' is not a package

Here is the path of python (after having typed `which python` in the Terminal): `/anaconda3/bin/python`

I checked that the matplotlib is installed by running the command `conda list` in the Terminal and got (among all the other packages) those lines:

    matplotlib 2.1.2 py36h6d6146d_0
    matplotlib 2.2.2 <pip>
    PySide2 5.9.0a1.dev1525348214

I tried to run the following command in the Terminal but didn't solve the problem

`sudo apt-get install python3-matplotlib`
`sudo pip3 install matplotlib`

I had a similar issue with `numpy` when trying to import `import numpy`. Although import `numpy` was not a problem an hour ago, I get now the following error message (it seems it wants to connect to a previously used script in which numpy was used, to open numpy itself): 

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-5-592c151f282b> in <module>()
          1 # from numpy import genfromtxt as gft
    ----> 2 import numpy

    ~/Downloads/numpy.py in <module>()
    ----> 1 from numpy import genfromtxt
          2 my_data = genfromtxt('/Users/mymac/Documents/PyQt/image_viewer/csv_file_generator/eggs.csv',
          3     delimiter=',',
          4     dtype=None,
          5     encoding=None)

    ImportError: cannot import name 'genfromtxt'

I had the same issue when tryin to import opencv2: I got the following error message:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import--------------------------- 
------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-8f6675581547> in <module>()
      5 from PySide2.QtCore import *
      6 from PySide2.QtGui import *
----> 7 import cv2
      8 import numpy
      9 import csv

ImportError: numpy.core.multiarray failed to import
```

I also enter the following line in the Terminal: 
```atom --clear-window-state```
but it didn't help either

I visited the following site which didn't help me (or I didn't understand how to implement exactly the steps to fix the problem)

[ImportError: No module named matplotlib.pyplot][1]

[Importing matplotlib.pyplot in atom editor][2]

[matplotlib Error: No module named matplotlib even though it is installed][3]

I also posted

  [1]: https://stackoverflow.com/questions/18176591/importerror-no-module-named-matplotlib-pyplot
  [2]: https://stackoverflow.com/questions/43306980/importing-matplotlib-pyplot-in-atom-editor
  [3]: https://askubuntu.com/questions/427708/matplotlib-error-no-module-named-matplotlib-even-though-it-is-installed

**Expected behavior:** I want to be able to import package in a python script

**Actual behavior:** I get a message of the form `ModuleNotFoundError: No module named 'matplotlib.backends'; 'matplotlib' is not a package`

**Reproduces how often:** it varies, but it come and goes without a clear time pattern. I also cannot tell why it comes at a certain point. It seems to happen with `matplotlib` and `numpy`

### Versions

`python 3.6.5`
`macOS 10.13.4`
`Atom 1.26.1 x64`
`Hydrogen 2.4.1`

### Additional Information

When the problem happens, Atom seems to want to connect to a previously used script in which numpy was used, to open numpy itself

Please let me know if something is not clear or if more informations are needed

Many thanks in advance for your time!

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [Hydrogen](https://github.com/nteract/hydrogen) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
