### ISSUE TITLE
Mac: "Automatically Update" Non-functional

### ISSUE THREAD

**Issue by AbandonedCart** [atom/atom#17387]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:

### Description

When a new version is available, it is downloaded (somewhere). It will appear in the Mac context menu alongside the previous version. It will not replace the previous version. Any existing links to the application is Dock and Applications will point to the previous version. The "Check for Update" menu option inside the previous version will display "X.X.X is the latest version"

### Steps to Reproduce

1. Install Atom
2. New version released
3. Open Atom from Applications
3. Check for updates

**Expected behavior:** Updates to replace existing version, install automatically

**Actual behavior:** Update is downloaded and resides alongside existing version for manual install

**Reproduces how often:** Every update

### Versions

-> 1.27.0 -> 1.27.1

**Comment by rsese** [comment]
Thanks for the report - can you clarify a few things?

> 4. Check for updates

I'm assuming step 5 is click "Restart and Install Update"?

> Actual behavior: Update is downloaded and resides alongside existing version for manual install

Can you describe this in more detail?  After clicking "Restart and Install Update", does the original Atom window close or stay open?  And you're saying that you have 2 Atom windows running now, one running `1.27.0` and the other `1.27.1`?  After closing the Atom window running `1.27.0`, does Atom now always start `1.27.1`?

Also what version of macOS are you running?

**Comment by rsese** [comment]
Sorry I think I must have went straight to your repro steps after reading the title - from your description, it sounds like a duplicate of https://github.com/atom/atom/issues/11047.

> Any existing links to the application is Dock and Applications will point to the previous version. The "Check for Update" menu option inside the previous version will display "X.X.X is the latest version

Does Atom actually close and re-open after you update at this point or are you also starting Atom from the Dock or Applications as well?  If you close the Atom window showing the previous version and start Atom again, does it show the latest version?

**Comment by LoungeKatt** [comment]
There is no step 5. As I stated in the original report 

> The "Check for Update" menu option inside the previous version will display "X.X.X is the latest version"

In the version before 1.27.0 (not entirely sure of the exact number), I was able to get a restart and install item to appear by performing a full reboot of the system. I cannot do that for every update.

I have fully closed Atom (right click in dock, choose close) and it opens the old version when launched again.

I can open 1.27.1 through the context menu of a file, but it will open a new window with only an untitled item. It will not actually open the file.

It is MocOS 10.12.5

Just to make sure I am perfectly clear:
The update is **only** being downloaded, **not** installed. 
It does **not** provide an option to install it. 
It says the **existing version** is the newest.

I only discovered there was a newer version through the context menu of a file.

**Comment by NelsonScott** [comment]
It kept trying and failing to restart after it had downloaded the update (it would shut down but not start up again)

Only way I was able to get it to work was to uninstall atom and do a fresh install

**Comment by rsese** [comment]
Thanks for clarifying @LoungeKatt :+1:  I had a chance to install 1.27.1 so I could update to 1.27.2 and the update worked ok.  Did you have the same issue updating from 1.27.1 to 1.27.2?

**Comment by LoungeKatt** [comment]
Apparently it fixed itself along the way. Hopefully whatever accidentally corrected this issue isn't changed in the future. It is always much harder to trace a regression when the cause was never diagnosed.

**Comment by LoungeKatt** [comment]
The issue has continued going from 1.27.2 to 1.28.0

Both 1.27.2 and 1.28.0 showed up in the context menu to open a file.
I selected 1.28.0 and it immediately crashed. 
I attempted to open the file again, but 1.28.0 was no longer an option.
Selecting "Check for Updates" in 1.27.2 displays "Version 1.27.2 is the latest version"

**Comment by rsese** [comment]
Has everyone already tried the steps mentioned here?

https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054

**Comment by rajivshah3** [comment]
Just tried that, all of the folders were owned by me

**Comment by rsese** [comment]
There are a few long running issues where people have had problems with updates on macOS e.g. https://github.com/atom/atom/issues/13804 and https://github.com/atom/atom/issues/15636.  Some people mentioned an error though some haven't.  In some cases people have eventually been able to get past the problem but for those that haven't we've asked them to open new issues and check some baseline steps like the item in the FAQ I mentioned. 

> what information do you need 

We haven't been able to reproduce the behavior you've described and not everyone is running into this problem but we're happy to work with anyone to get more information about the issue.  What we need is to figure out how to get Atom in this state where the update doesn't work as described.  Just following the installation process isn't enough on its own since we can't reproduce with those steps.

@NelsonScott @rajivshah3 @axelson can you double check if the problems you're having are exactly as described in this issue?  If not, feel free to open a new issue since we try to avoid having general catch-all issues.

**Comment by rajivshah3** [comment]
@rsese from the information given, I believe I’m having the same issue. However if the others could share their ShipIt_stderr.log I’m sure it would help in figuring out the root cause.

**Comment by rajivshah3** [comment]
@LoungeKatt @NelsonScott @axelson is there a file at the path `~/Library/Caches/com.github.atom.ShipIt/ShipIt_stderr.log`? If you’re able to post it here I think that would be helpful in finding the root cause

**Comment by LoungeKatt** [comment]
<img width="1440" alt="screen shot 2018-07-05 at 5 29 45 pm" src="https://user-images.githubusercontent.com/1173913/42349575-363895d4-807b-11e8-9b38-a810d6afb0be.png">

**Comment by FutureSharks** [comment]
I've had this problem for years, so annoying!

After the update is downloaded into `~/Library/Caches/com.github.atom.ShipIt/update.xxxxx`, I have no logs, both `ShipIt_stderr.log` and `ShipIt_stdout.log` are empty. I click Atom menu "Restart and Install Update", the Atom windows exit but the process is still running, I wait 5-10 mins, nothing is happening, click Atom icon again, blank window opens, nothing happening, restart Atom, back to step 1, downloading same update again.

**Comment by brandonkal** [comment]
Yes, I have been experiencing this issue since Atom 1.27. Automatic Updates of Atom do not function with Mac 10.12.6 and Atom 10.28.0 --> 10.28.2.

Here is the ShipIt_stderr.log:
```
2018-06-01 15:20:09.535 ShipIt[2740:60689] Application launched at file:///Applications/Atom.app
2018-06-01 15:20:09.535 ShipIt[2740:60689] ShipIt quitting
2018-06-26 16:42:44.538 ShipIt[1696:277569] Beginning installation
2018-06-26 16:42:48.995 ShipIt[1696:277575] Installation error: Error Domain=SQRLInstallerErrorDomain Code=-1 "Failed to copy bundle file:///Users/brandonkal/Library/Caches/com.github.atom.ShipIt/update.mE3v2tZ/Atom.app/ to directory file:///var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/com.github.atom.ShipIt.YGAW363Y/Atom.app" UserInfo={NSSourceFilePathErrorKey=/Users/brandonkal/Library/Caches/com.github.atom.ShipIt/update.mE3v2tZ/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/com.github.atom.ShipIt.YGAW363Y/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property, NSFilePath=/Users/brandonkal/Library/Caches/com.github.atom.ShipIt/update.mE3v2tZ/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property, NSUnderlyingError=0x7ffe077456b0 {Error Domain=NSCocoaErrorDomain Code=4 "The file “is-property” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/Users/brandonkal/Library/Caches/com.github.atom.ShipIt/update.mE3v2tZ/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/com.github.atom.ShipIt.YGAW363Y/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property, NSFilePath=/Users/brandonkal/Library/Caches/com.github.atom.ShipIt/update.mE3v2tZ/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/node_modules/generate-object-property/node_modules/is-property, NSUnderlyingError=0x7ffe077488a0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}, NSLocalizedDescription=Failed to copy bundle file:///Users/brandonkal/Library/Caches/com.github.atom.ShipIt/update.mE3v2tZ/Atom.app/ to directory file:///var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/com.github.atom.ShipIt.YGAW363Y/Atom.app}
2018-06-26 16:42:48.995 ShipIt[1696:277575] ShipIt quitting
2018-06-26 22:13:23.521 ShipIt[11190:459363] Resuming installation attempt 2
2018-06-26 22:13:31.365 ShipIt[11190:459364] Installation error: Error Domain=SQRLCodeSignatureErrorDomain Code=-1 "Code signature at URL file:///var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/com.github.atom.ShipIt.Mvs98z7s/Atom.app did not pass validation" UserInfo={NSLocalizedFailureReason=CSSMERR_CSP_INVALID_CONTEXT_HANDLE, NSLocalizedDescription=Code signature at URL file:///var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/com.github.atom.ShipIt.Mvs98z7s/Atom.app did not pass validation, NSUnderlyingError=0x7ff62e402070 {Error Domain=NSOSStatusErrorDomain Code=-2147416000 "(null)" UserInfo={SecCSArchitecture=x86_64}}}
2018-06-26 22:13:31.365 ShipIt[11190:459364] ShipIt quitting
2018-06-27 02:21:15.153 ShipIt[16805:571679] Resuming installation attempt 3
2018-06-27 02:21:23.734 ShipIt[16805:571680] Moved bundle from file:///Applications/Atom.app to file:///var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/com.github.atom.ShipIt.bZx8zpAr/Atom.app
2018-06-27 02:21:23.734 ShipIt[16805:571680] Moved bundle from file:///var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/com.github.atom.ShipIt.iPUiXgSK/Atom.app to file:///Applications/Atom.app
2018-06-27 02:21:24.277 ShipIt[16805:571680] Couldn't remove owned bundle at location file:///var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/com.github.atom.ShipIt.iPUiXgSK/Atom.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Atom.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/nv/4dq8b8zd25j3sbx57nnwf8s40000gn/T/com.github.atom.ShipIt.iPUiXgSK/Atom.app";
    NSUserStringVariant =     (
        Remove
    );
} }
2018-06-27 02:21:24.866 ShipIt[16805:571680] Could not release power assertion: -536870199
2018-06-27 02:21:24.867 ShipIt[16805:571680] Installation completed successfully
2018-06-27 02:21:24.867 ShipIt[16805:571680] Could not release power assertion: -536870199
2018-06-27 02:21:24.867 ShipIt[16805:571680] ShipIt quitting
2018-07-31 12:30:35.008 ShipIt[2465:26842] Too many attempts to install, aborting update
2018-07-31 12:30:35.052 ShipIt[2465:26843] Application launched at file:///Applications/Atom.app
2018-07-31 12:30:35.052 ShipIt[2465:26843] ShipIt quitting
```

It looks like the issue may have to do with code signing, but it also should be noted that Atom doesn't actually ever quit (besides closing open windows) after clicking "restart and update"

**Comment by AbandonedCart** [comment]
After 1.29.0 was published, the automatic install *appeared* to almost work. Both versions were displayed in the context menus, and it even switched the default to the new version. It crashed the first time I opened a file, and disappeared from the context list shortly after.

I  stumbled onto [Visual Studio Code](https://code.visualstudio.com/) looking for an IDE that could verify Node.js code. Out of curiosity, I compared how it handled files I originally installed Atom to edit (which required maintaining whitespace and line endings) and found that it not only updated properly, but also did not require plugins.

It seems like Mac support for Atom is more of an experiment than a mainstream feature. I appreciate the single attempt to diagnose and resolve the issue, but cannot stop everything to perform a manual update every time a new version releases.

**Comment by brandonkal** [comment]
This is still an issue in 1.29.0. I don't see the point in closing this until it is resolved...

**Comment by FutureSharks** [comment]
@AbandonedCart the issue is not attached to you, it's for everyone who has the problem, of which there are many. Can you reopen it and then just unsubscribe from it?

**Comment by AbandonedCart** [comment]
@FutureSharks Unsubscribing from it does not do much, as you have proven. I hardly call three other people, including yourself, "many" others. Can't you just tag this issue in your original one, assuming you did make one in the years you claim to have had similar problems.
