### ISSUE TITLE
About using Atom base project to build other open-source IDE

### ISSUE THREAD

**Issue by jonatasfreitasv** [atom/atom#17381]
Hi guys,

I'm start this project (https://github.com/HouseOps/HouseOps) based on electron/react boilerplate.

But I spend a lot of time in front-end, and for IDE, is very hard to make a nice interface.

I think to use Atom project for speed a front-end development.

Is a good idea ? Or not ?

**Comment by Arcanemagus** [comment]
For reference: the [original question](https://atomio.slack.com/archives/C044E54H0/p1526948707000306), and [the response](https://atomio.slack.com/archives/C044E54H0/p1527004717000183).
