### ISSUE TITLE
Javascript syntax error

### ISSUE THREAD

**Issue by Voyager-One** [atom/atom#17395]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]
atom misclassify the syntax

![snip20180523_1](https://user-images.githubusercontent.com/23122353/40408135-1b2f6172-5e99-11e8-97a0-d927bd13b05c.png)

the correct syntax style:
![snip20180523_2](https://user-images.githubusercontent.com/23122353/40408159-38e72542-5e99-11e8-989b-88f33b7df689.png)

the incorrect syntax style:
![snip20180523_3](https://user-images.githubusercontent.com/23122353/40408179-4411ebdc-5e99-11e8-8495-57678f174eec.png)

### Steps to Reproduce

1. [First Step]
open atom create a new js file
2. [Second Step]
write `.sort().splice().slice` and so on
3. [and so on...]
you shall find the bug
**Expected behavior:** [What you expect to happen]
functions should be colored as blue
**Actual behavior:** [What actually happens]
some functions are blue and some are green
**Reproduces how often:** [What percentage of the time does it reproduce?]
always
### Versions
```
Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
```
```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.1
python 2.7.15
git 2.15.1
```

**Comment by maxbrunsfeld** [comment]
Yeah, [the TextMate grammar](https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson) distinguishes certain "known" function names for some reason. I don't really like that behavior either. You might tree enabling the `Use Tree-sitter Parsers` setting in the `Core` pane of the settings view.

**Comment by maxbrunsfeld** [comment]
What do you mean by 'babel syntax'?

**Comment by Voyager-One** [comment]
well...when you add language-babel to atom. when atom auto detects the lang to be babel. atom's Tree-Sitter would ignore some syntax...

**Comment by maxbrunsfeld** [comment]
Ok, I'm going to close this out because I think these different colorings are expected with the TextMate grammar.
