### ISSUE TITLE
Tree transforms for tree sitter

### ISSUE THREAD

**Issue by queerviolet** [atom/atom#17392]
## Summary

We'd like to be able to nest languages with tree sitter. That is, we want to somehow be able to specify that certain AST nodes (all terminals, currently, and probably in most cases) should have their content parsed with another grammar, generating a nested tree.

In the general case, we'd like to transform an antecedent (source) tree into a consequent (result) tree, and keep them both up to date with the buffer.

Basically, add a map method to a tree sitter tree like `Tree<T>::map<X>(transform: T -> X) -> Tree<X>`, where the returned tree handles traversal of nested trees and incremental parsing transparently in the case where `X` (somehow) contains a child tree. (This isn't intended as a final implementation, but as a general way of articulating the problem). We can compose multiple transforms together.

## Motivation

1. We'd like to offer support for styling escape sequences within string literals and regex operators and productions within regex literals. The TextMate grammars are able to do this, so it's technically a regression.

2. We'd like to be able to style certain variable names as keywords—for example, styling `module` or `exports` differently from just variables, even though they are really just variables.

3. In general, we'd like to be able to support nested languages—Javascript inside an HTML `<script>` tag, for example.

4. There are more exotic use cases for nested languages that would have great wow factor. Say, GraphQL / SQL expressions within appropriately tagged template literals in JS code. This is a little harder, because we either have to figure out what nested language to use (ML language detector anyone?) or wire in some config for users to do so.

## Describe alternatives you've considered

For use cases like (1), we could probably shim in an additional parse pass as we walk the tree. We could look for escape sequences before emitting styling tags specifically within string literal nodes, say. This doesn't scale that well, and opens up other questions, like whose regex grammar do we use, if we're highlighting regexes?

We could also just throw the necessary productions into the host language. This works well for escape sequences, regexes, Linq expressions, and other node types that really are conceptually part of the language. It's really not ideal for situations like nesting JS inside HTML; we'd prefer if the HTML parser didn't have to import the entire JS parser.

In the case of nesting languages where there's any possibility of dynamism in how the nesting occurs, simply having the parent language eat the child seems to be a non-starter—we'd have to re-compile the JS parser to include support for GraphQL tagged expressions *or* we'd have to include every child language we want to support in the host language, creating significant overhead (in terms of parser size if not parse time).

# Additional context & open questions

Ideally, we wouldn't have to change tree sitter proper, and I don't think we do. In all the cases above, we want to map the content of terminal nodes onto a new tree. @maxbrunsfeld and I discussed building a facade over the current tree cursor abstraction which understand when it needs to descend into a child tree and can do so, creating a nested cursor and iterating over it to completion, and then continuing on.

We'll also need some way to specify how languages are chained. That is, we'll want to be able to write a function that detects `<script>` tags or `graphql`-tagged template literals, and then knows how / is somehow handed a language dictionary that lets it parse the content of those nodes with a parser from another language.

**Comment by maxbrunsfeld** [comment]
Yeah, I'm really liking this direction of handling as much of the composition as possible *outside* of Tree-sitter.

Maybe a good first feature to tackle would be creating an HTML grammar and figuring out how to parse JS inside of the script tags.

> For use cases like (1), we could probably shim in an additional parse pass as we walk the tree. We could look for escape sequences before emitting styling tags specifically within string literal nodes, say.

I still feel like that approach might be a worth *also* having, for situations where the refinements that we're making to the highlighting are kind of "flat" in nature. I'm not sure that it's worth modeling thing things like escape sequences, TODO comments, etc as nested syntax trees and maintaining them as state. It might be simpler to compute them on the fly during syntax highlighting, as a simple sequence of regex matches. There is something elegant about handling all of these concerns via a unified approach though.

**Comment by queerviolet** [comment]
(So maybe this issue should be renamed to be transform-centric.)

**Comment by Ingramz** [comment]
Parsing template languages such as Razor or PHP together with HTML (or anything else) could be an interesting use case for parsing a document (or sections of it) twice.

Template language syntax can appear anywhere within the document, which makes it parsing with regular one-way parsers difficult if the user expects rest of the document to be as well some other language (like HTML), often times that other language manages to parse template syntax in some obscure position and we're left with imperfect detection for the template language.

Parsing the template language first will split the document into two - the template syntax part and plain text (leftovers). Then maybe try stitching the leftovers together and attempt to parse all of it as some other language, such as HTML. Such approach would guarantee that template language is always parsed correctly and there is at least some best-effort highlighting for rest of the document (maybe).

**Comment by queerviolet** [comment]
@Ingramz So, a nice thing about parsing it twice is that we're not really-really parsing the embedded language sections twice. The first time, when we scan them as literal template insertions, we're just looking for the end-of-section marker (`<?` in PHP, IIRC). So the sections in the templated language will end up being parse nodes in the parent tree.

Then, yeah, we should be able to concat all the embedded sections together and parse it as, say, HTML.

I think doing this correctly isn't the V1 goal. Initially, I'd like to just focus on being able to parse embedded languages where the embedded sections are single parseable entities. That just requires that we support `Tree::map`.

Supporting disjoint subdocuments will require that we be support `Tree::reduce`, to concat child nodes together and parse their content, while maintaining the ability to transform cursors in the parent tree to cursors in the deep tree. I suspect we'll need additional tooling, either within Tree sitter or around it, to support this transform.

**Comment by Ingramz** [comment]
Sure, I think that starting from the simplest case will both keep the issue at hand manageable and probably give some insight towards what is needed to support the more complex cases.

From practicality standpoint for the case I described, HTML parser and PHP parser both need to be figured out first before we can start thinking about combining them, which is why the simpler case would suffice right now.

**Comment by bennypowers** [comment]
WRT things like
```js
// js source

const graphqlDoc = gql`query Documents { documents { id } }`;
const litTemplate = html`<div>Hello ${user.name}</div>`;
```

My humble developer's perspective is that providing sensible defaults while

> wiring in some config for users to do so

Is the way to go.

This is exciting stuff. Thanks for putting these features forward.
