### ISSUE TITLE
Autocomplete popup covers the cursor, can't see what I'm typing.

### ISSUE THREAD

**Issue by trusktr** [atom/atom#17417]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:

### Description

When tooltip goes upward (because the cursor is close to bottom of the screen), it covers the cursor, blocking what we've type from being visible.

![screen shot 2018-05-28 at 9 53 48 pm](https://user-images.githubusercontent.com/297678/40638699-a1a6e4c4-62c1-11e8-8733-85764177620c.png)

### Steps to Reproduce

1. Just use the default autocomplete while near the bottom.

**Expected behavior:** [What you expect to happen]

It should not block the cursor.

**Actual behavior:** [What actually happens]

It blocks the cursor.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time that the popup goes upward.

### Versions

```
Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by rsese** [comment]
Thanks for this report too @trusktr - I wasn't able to repro on 1.27.1 on macOS 10.12.6.

The menu shows right above where I'm typing.  Are there any more specific step-by-step instructions for reproducing?  And how did things look when you ran in safe mode, exactly the same?
