### ISSUE TITLE
Command to resize width or height of pane.

### ISSUE THREAD

**Issue by trusktr** [atom/atom#17412]
## Summary

Currently we can press `alt-cmd--` or `alt-cmd-=` to resize a pane, but sometimes it resizes width, and other times it resizes height, depending on whether the pane is a horizontal or vertical split.

## Motivation

This is not as intuitive as it can be. It'd be nice to have commands like

```
Pane: Increase Width
Pane: Decrease Width
Pane: Increase Height
Pane: Decrease Height
```

## Describe alternatives you've considered

I haven't tried implementing this myself yet, and haven't yet found a plugin for it.

**Comment by trusktr** [comment]
@liuxiong332 I think you know most about this. Possible to add these commands?

**Comment by trusktr** [comment]
The problem with the current increase/decrease is that sometimes, depending on splits, it is impossible to resize width, only height. For example: 

- start with one pane
- then make a vertical split
- then in each vertical split make a horizontal split
- now you have four panes
- in any pane, try increasing or decreasing size, and you see it only works on one axis
- to resize the other axis, we are forced to use the mouse

It would be great to have complete control from the keyboard, so having four command like suggested above would be awesome.

**Comment by nischkar** [comment]
This is a good feature.
But it may not be useful for other users
Maybe a plugin can do this feature.
Instead of implementing it in the core editor
