### ISSUE TITLE
pane:increase/decrease-size commands introduce empty space

### ISSUE THREAD

**Issue by trusktr** [atom/atom#17415]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:

### Description

Resizing with keyboard causes what you see in the video:

https://youtu.be/mOYlLK1l10U

### Steps to Reproduce

1. create a horizontal split
2. create a vertical split in top and bottom
3. resize height of panes with the mouse so top and bottom aren't equal.
4. resize the pane widths so they aren't equal, like in the video.
5. resize panes with `pane:increase-size` or `pane:decrease-size`, likely one will introduce the empty space.

**Expected behavior:** [What you expect to happen]

No empty space

**Actual behavior:** [What actually happens]

Empty space

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time, with `--safe` mode.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
macOS: 10.13.4
Atom    : 1.27.1
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

**Comment by trusktr** [comment]
Updated with video above: https://youtu.be/mOYlLK1l10U

**Comment by rsese** [comment]
Thanks for the report - I wasn't able to reproduce with 1.27.1 on macOS 10.12.6 but I'll try again later after watching the video again.
