### ISSUE TITLE
'Open With Atom' Missing in Right Click Context Menu on Ubuntu 18.04

### ISSUE THREAD

**Issue by nasirkhan** [atom/atom#17428]
### Description

Open With Atom option is missing in Ubuntu 18.04. Yesterday i installed a fresh Ubuntu 18.04 and installed Atom Editor there. I tried both the Snap package and also downloaded the .deb version from the website. None of the cases i found this option. 
Earlier on Ubuntu 16.04 this option was available and i also use this on Windows 10.  

### Steps to Reproduce

1. Install Ubuntu 18.04
2. Download Atom from the website
3. Install the Atom
4. Open Nautilus file browser and click right button of the mouse on any project

**Expected behavior:** [What you expect to happen]
Open the context menu with an option 'Open with Atom'

**Actual behavior:** [What actually happens]
Context menu opened but the 'Open with Atom' option was not there.

**Comment by rsese** [comment]
Thanks for the report - I just checked 18.04 and it looks like you have to set it up first?  I.e. right-click on a file, click `Open With Other Application`, click `View All Applications`,  click Atom and select it.  After doing this, right-clicking on a file of that type has "Open With Atom" available by default.

Going to go ahead and close but if you have any trouble with this or I'm mis-understanding (do you think the "Open With Atom" should be available by default?), let me know.

**Comment by rsese** [comment]
> I tried both the Snap package and also downloaded the .deb version from the website.

Oh also, the Snap package is unofficial, the only officially supported installs are documented in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/) (the .deb from https://atom.io and the official package repos).

**Comment by rsese** [comment]
What do you see on right-click with files you've setup to open with Atom?  This is what I see on Ubuntu 18.04 after setting up Atom with `.md` files:

![right-click-atom](https://github-slack.s3.amazonaws.com/monosnap/Ubuntu_64-bit_18.04_2018-06-06_11-58-39.png)

**Comment by nasirkhan** [comment]
The menu was like the yours on my Ubuntu 16.04 but now Open with Atom is not available on my Ubuntu 18.04.

I downloaded the package from atom.io and followed the Flight manual again and still facing the same issue.

**Comment by nasirkhan** [comment]
I am now using this two step option to open the directory on Ubuntu 18.04. But it would be great to have this feature like it was previously on Ubuntu 16.04

**Comment by nasirkhan** [comment]
I think the issue should remain open and you can consider this as a feature request.
