### ISSUE TITLE
Typing in font family deletes characters

### ISSUE THREAD

**Issue by lukepighetti** [atom/atom#17427]
If you type in `Settings > Editor > Font Family` on macOS or Windows, it will delete your characters as you type.

**Comment by rsese** [comment]
Thanks for the report!

Would you mind reopening this issue in https://github.com/atom/settings-view/ if there isn't already an issue for it?  We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

And please fill out the issue template, the information in the template is super helpful for us when investigating issues.

Thanks for meeting us half way 👍
