### ISSUE TITLE
Atom crashes on big files - intelisense or something else?

### ISSUE THREAD

**Issue by AionDev** [atom/atom#17423]
I created a new file.. angular.js, and i copy pasted 34500 lines of code into it. See the angularjs source code here: https://ajax.googleapis.com/ajax/libs/angularjs/1.6.10/angular.js.

As soon as i paste it,  atom tries to run intelisense or something on this many lines of javascript. 
Because the file is this big, it crashes atom.
I can't close it...  This `not responding problem` appears.
![i cant close it](https://user-images.githubusercontent.com/20288140/40678312-e54c9a9e-6388-11e8-89ea-715d49178730.png)

Can't save it,
![cant save it](https://user-images.githubusercontent.com/20288140/40678360-14f90606-6389-11e8-8b3d-e180f5633651.png)

**Is important to mention, that even the focus is on another tab (as you can see in the first image)
I still can't close it.** 

And **once i close and restart atom, the file still hangs in there**.. in a semi-saved state or whatever state this is.

**How to get out of this state??**

The desired behavior would be for intelisense to stop running automagically when this big files are present.
Maybe i'm wrong and this is not even an intelisense problem.

EDIT: 
My atom version is: 1.25.1, Windows 10, 64 bits, 4GB ram,  processor i3 3.7GH

**Comment by Zireael07** [comment]
What is your atom version? You should have filled out the issue template...

**Comment by maxbrunsfeld** [comment]
I noticed you have the minimap in your screenshot. Do you still get this crash if you run Atom in Safe mode (`atom --safe`)?

**Comment by maxbrunsfeld** [comment]
Actually, I'm going to close this out, and we can reopen once you've provided the information requested in the issue template. That information really is needed for diagnosing issues.
