### ISSUE TITLE
Problems with opening a file at a specific line

### ISSUE THREAD

**Issue by probablycorey** [atom/atom#1743]
Running `atom file.coffee:20` will open something.coffee at line 20. But if the editor already has file.coffee open, it will not scroll to line 20. This is causing problems for people wanting to create links from stacktraces.

/via http://discuss.atom.io/t/open-file-at-specific-line-and-column/3883/6

**Comment by scwe** [comment]
This doesn't quite work yet. When opening a file to line 0, Atom will just try to open a file called "filename.txt:0" rather than just defaulting to the top of the file.

**Comment by izuzak** [comment]
Thanks for reporting this, @scwe -- I can reproduce this as well. I'm pretty sure this was working, so it's probably a regression. /cc @maxbrunsfeld @kevinsawicki for more :eyes:

**Comment by tomaskikutis** [comment]
The bug is still present for me at 1.0.7

**Comment by audiophens** [comment]
I can also confirm this bug.
I'm on Windows 7 64bit running Atom 1.0.7
