### ISSUE TITLE
A colorful palette of breakages since update to 1.26

### ISSUE THREAD

**Issue by Redsandro** [atom/atom#17430]
I've never experienced a break when updating Atom.

However, the last two weeks everything seems broken after an update. Not just a small annoyance, but bloodboil. As if there was a major update from stable to an alpha version.

There's just too much wrong for me to open 7 tickets and fill in all the details: I'm hoping someone will recognize this sudden breakage of many functionalities, and will recognize a certain common cause for this. Surely I can't be the only one that suddenly experienced this.

__Since upgrading to Atom 1.26:__

1. :warning: **The _Search Results_ tab no longer opens in a new panel**, and I cannot find a setting for this behavior.
1. ~~**Opening a result** from the _Search Results_ tab **no longer focuses the new tab**, and I cannot find a setting for this~~
1. ~~**Single-clicking** a search-result or a tree-view-item **no longer works**. Double-click-paradise.~~
1. `eslint` conflicts with **`atom-ide-diagnostics`** and I need to disable one (warning popup), which **is actually `atom-ide-ui`** (confusing)
1. Being a fan of progress, I pick the new thing (diagnostics) but **I can't get `atom-ide-diagnostics` to lint my files** (eslint), so I'm forced pick the old linter package in stead.
1. Now **`atom-ide-diagnostics` needs to be disabled _on every newly opened tab_ again**. The popup keeps coming back, forcing me to disable the entire `atom-ide-ui` package.
1. :warning: eslint now works on only the open tab. **For every new file, I need to close and re-open atom before I can see the linting errors.**

```
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
4.13.0-32-generic Ubuntu 16.04.1 SMP
```

What I could and probably will do is remove [evvverrryyythinggg](https://www.youtube.com/watch?v=A_iAE2JIyEE), start from scratch and enable functionality one by one.

However, I sincerely think that this is something that would have occured to many users, and I'm wondering if there's a known cause and perhaps a less drastic fix.

If not, don't dwell on it. I will waste a couple of hours setting everything up again and/or reinstalling version 1.24. In a couple of weeks I'll have forgotten about this, and promote Atom again amongst my now laughing Webstorm colleagues.

**Comment by daviwil** [comment]
Hey @Redsandro, have you tried Atom 1.27.1 yet?  I can't reproduce the first 3 bullets on Fedora Linux with that version.

For the other Diagnostics/linting problems you should file an issue on the [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) repo.

**Comment by rsese** [comment]
I was also unable to reproduce on Ubuntu 16.04 with 1.26.x or 1.27.x and I don't recall any reports of similar behavior.

Besides/in addition to trying 1.27.1, can you also confirm if you can reproduce in safe mode @Redsandro as asked in the `Prerequisites` section of the issue template?

**Comment by Redsandro** [comment]
@daviwil thank you for your suggestion. I've just installed Atom `1.27.1 x64`. I still experienced these errors. So I took the plunge and removed `~/.atom`. I've installed just the packages I need for today.

```
$ apm list --installed --bare
busy-signal@1.4.3
highlight-selected@0.13.1
intentions@1.1.5
js-refactor@0.8.1
linter@2.2.0
linter-eslint@8.4.1
linter-ui-default@1.7.1
minimap@4.29.8
minimap-cursorline@0.2.0
minimap-find-and-replace@4.5.2
minimap-git-diff@4.3.1
minimap-highlight-selected@4.6.1
minimap-linter@2.1.3
minimap-selection@4.5.0
refactor@0.11.5
```

This fixes 2 and 3, but I still have 1 (search not opening in new panel). Since you don't have this, I'm wondering if this is a setting. I've glanced over the settings multiple times, but nothing I recognize as related.

When I manually drag the search tab to a new empty panel, close it, and search again, it is again not in a new panel. I can't figure out how to make it automatically open in a new panel on the side.

Also when I open a search result by clicking on it once (point 3), now the file doesn't open in the panel with all the source file tabs, but in a new tab in the same panel as the search.

Also, searching for the first time concequently triggers https://github.com/atom/atom/issues/16898

(__Please note__ that I just installed 1.27.1 and removed the `.atom` directory before fresh installing the above modules.)

---

@rsese but in safe-mode, the packages ide-ui, ide-diagnostics, linter-eslint etc aren't loaded.

**Comment by Redsandro** [comment]
Today I worked on a laptop with Atom 1.24 and old packages, and I noticed how much more pleasant it is to work with because of little things and no error popups multiple times per day. I'm considering cloning the `~/.atom` directory and bringing it to the office, while installing an older Atom version.

I don't like this beta feeling Atom has lately. It turns former fans into normal users. Somewhere along the road a choice was seemingly made to drop the quality level in favor of development speed. This makes some users happy and chases others away. Just like some people choose Ubuntu Latest and Fedora; others prefer Ubuntu LTS and CentOS. For this reason, I would propose a change of repositories:

* `atom` -> should be atom <= 1.24
* `atom-beta` -> should be current atom
* `atom-next` (or `-alpha`) -> should be current atom-beta

It is necessary to be able to rely on things. Because without a stable branch and system for vetted stable packages, a commercial IDE is simply cheaper, considering the time lost on things like this.

**Comment by rsese** [comment]
Glad that you got past those 3 issues @Redsandro :+1:  If you do continue trying 1.27.1/ the latest stable and run into reproducible issues that haven't been reported, please do let us know.

Otherwise, though we can't make any promises about changes to the release process, we'll go ahead and share your feedback with the rest of the team.

**Comment by Redsandro** [comment]
Thanks for the help @rsese and @daviwil.

I'm always pleasantly surprised by the positive attitude here, even when confronted with opinions. I hope [the feedback](https://github.com/atom/atom/issues/17430#issuecomment-393483876) will trickle down somewhere influential, but if not, thanks for listening. :muscle:
