### ISSUE TITLE
Broken CLI

### ISSUE THREAD

**Issue by memeplex** [atom/atom#17437]
I have installed the 1.27.1 ubuntu snap and cli options are not working at all, `atom --help`, `atom --wait` etc. do nothing at all.

**Comment by daviwil** [comment]
Hi @memeplex, the Snap image for Atom is maintained and distributed by Snapcraft and isn't supported by the Atom team.  You should file this issue over at the repo that manages this project:

https://github.com/snapcrafters/atom

Thanks!

**Comment by memeplex** [comment]
Ok, thanks, I confirm the .deb provided by the atom team doesn't show the problem.
