### ISSUE TITLE
Allow to init a git repository under git managed home directories

### ISSUE THREAD

**Issue by memeplex** [atom/atom#17444]
Currently atom reports that it doesn't support git managed home directories which is fine.

But there is one problem: having a git repo in your home dir virtually disables the git repo creation/initialization abilities of atom, since it is expected that most or all of your projects will be under your user directory.

I suggest that when a project is under a git managed home dir the option to create a new git repository should be available.

**Comment by rsese** [comment]
Thanks for reaching out!

Would you mind reopening this issue in the https://github.com/atom/github/ repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.  Additionally, please use the issue template as much as possible when creating issues, the information in the template is helpful for us when triaging issues.

It might be useful to talk more about your use case as well - we found that people that had their home directory initialized as a git repository didn't do it on purpose.

And you can still initialize a git repository in a subdirectory under your home directory from the command line and the GitHub package will work with it as normal.

Thanks for meeting us half way 👍
