### ISSUE TITLE
Atom stopped working properly after updating to version 1.27.2

### ISSUE THREAD

**Issue by JDevezas** [atom/atom#17449]
I have been running Atom on Ubuntu 16 without any problems but today I decided to update from version 1.24 to version 1.27 because of a Hydrogen package error I was getting whenever I opened Atom.

I did so via command line with `apm udpate`

After that I can open Atom but then I can't do anything else. I try to manually open files selecting the folders they're in but nothing happens.

When I try opening Atom with atom --safe everything seems ok though.

**Comment by rsese** [comment]
Thanks for reaching out!

> When I try opening Atom with atom --safe everything seems ok though.

If there's no problem in safe mode, then that likely means a community package is causing the issue:

http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

You can disable each community package one by one to try and pinpoint which is causing the problem (maybe start with Hydrogen?).  If you have any trouble with this let me know.

Additionally, for future issues please fill out the issue template - the information in the template is super helpful for us when triaging issues.
