### ISSUE TITLE
RIP ATOM

### ISSUE THREAD

**Issue by marekr** [atom/atom#17460]
We know you are going to get axed first in the name of vscode.

RIP.

**Comment by medokin** [comment]
It does not make sense to develop 2 competing products. It's a valid question how Github will handle it.

**Comment by jonatjano** [comment]
I personally think this is not the only thing we all want to know about the future of GitHub but this question is so important **what will append to Atom ?** to all these package the community created ? We don't want to use vscode ! please don't die on us !!!

Why do microsoft take so much time to tell us what are their plans ? Do they fear more of us leave GitHub ?

**Comment by jonatjano** [comment]
@zmilonas but if Atom is not continued because as @medokin 
> said it make no sense to develop 2 competing products
will you continue to use an unsuported software (even if it was the coolest when it was active) ?
