### ISSUE TITLE
Make tree sitter parsers run in browsers

### ISSUE THREAD

**Issue by queerviolet** [atom/atom#17461]
## Summary

We want tree sitter to be able to generate parsers that run within browsers. Currently, the parsers are generated as C and linked into node as native modules via gyp.

## Motivation

This is necessary to use tree-sitter's incremental, async parsing in a web environment, where we'd eventually like to run.

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered. Be sure to explain why Atom's existing customizability isn't suitable for this feature.

Two possibilities for approach:

  1. We'll probably decide to compile the generated C parsers to wasm with emscripten. This will likely be faster than the alternative, which is...

  2. Modify tree sitter to produce Javascript. We may end up doing this later, for compatibility with browsers that don't support wasm.

**Comment by Arcanemagus** [comment]
This was implemented in https://github.com/tree-sitter/tree-sitter/pull/321 (and doesn't directly relate to Atom in the first place).
