### ISSUE TITLE
Where will atom go when Microsoft(VScode) own github?

### ISSUE THREAD

**Issue by g1mi** [atom/atom#17471]
As I was saying,  If github becomes part of Microsoft, atom as well .As a company which needs the profits, it would be such a waste to focus on both projects, I was just wondering if there will be a choice between them(atom & VScode), and if there is, enlighten me which gonna survive, plz?

**Comment by nkkollaw** [comment]
It's been asked via issues about 100 times.

**Comment by g1mi** [comment]
@nkkollaw
I know it's a boring question, I'm just so obssessed to see big companies fight with each other :) .
And I'm a little sad github has to be one of them, it's like she's gonna lose her neutral when it happens.

**Comment by nkkollaw** [comment]
@g1mi: it's not a boring question, it's been asked and answer before many times, which means every time someone spams issues with this question, someone wastes his time.

**Comment by lee-dohm** [comment]
Thanks for your concern.

Atom remains key to GitHub. Our product roadmap is set, and the team will continue all of their work.

**Comment by daviwil** [comment]
If you want to be further reassured that Atom will continue, see this comment by GitHub's future CEO: https://www.reddit.com/r/AMA/comments/8pc8mf/im_nat_friedman_future_ceo_of_github_ama/e0a235q/

>Developers are really particular about their setup, and choosing an editor is one of the most personal decisions a developer makes. Languages change, jobs change, you often get a new computer or upgrade your OS, but you usually pick an editor and grow with it for years. The last thing I would want to do is take that decision away from Atom users.
>
>Atom is a fantastic editor with a healthy community, adoring fans, excellent design, and a promising foray into real-time collaboration. At Microsoft, we already use every editor from Atom to VS Code to Sublime to Vim, and we want developers to use any editor they prefer with GitHub.
>
>So we will continue to develop and support both Atom and VS Code going forward.
