### ISSUE TITLE
getVisibleRowRange() does not respect folded lines

### ISSUE THREAD

**Issue by Fusseldieb** [atom/atom#17478]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`getVisibleRowRange()` returns only all unfolded lines. When I fold something, the range gets messed up and no longer works reliably until I unfold everything.

### Steps to Reproduce

1. Open up the Atom developer console
2. Access the `getVisibleRowRange()` of the active editor
3. Fold and unfold lines and watch the range not changing.

**Expected behavior:** When I fold something, it should increase the range and match the start and end of the editor line count.

**Actual behavior:** It shows the start and end line count until I fold something, but then stays the same count, while it should increase to match the beginning and ending of the editor lines count.

**Reproduces how often:** 100% of the time. It's probably intended (for earlier versions without code folding), but it should be changed now.

### Versions

Atom 1.27.2 x64
Windows 10 x64

### Additional Information

I also tried accessing
```
element.getFirstVisibleScreenRow()
element.getLastVisibleScreenRow()
```
but those commands above will show exactly the same wrong result as `getVisibleRowRange()`.

On top, my suggestion would be to maybe leave those function as they are (for backwards compatibility with packages) and add new ones which get all the visible lines (including the folded ones) and show the range reliably.

I was bugfixing a [package](https://github.com/camel-chased/editor-background) which has this exact issue mentioned above and I haven't found any functions to access all visible lines. Since those functions doesn't respect the folding, when something folds, the package missmatches lines and stuff get weird.

See [this](https://github.com/camel-chased/editor-background/blob/35f4d38cb57bf91dc89bb720dc4f72df7460c562/lib/editor-background.coffee#L781) for reference.

**Comment by ezhlobo** [comment]
@maxbrunsfeld so is there any public alternative to implement `getFirstVisibleScreenRow`? 

Now it ignores folded lines (that's not as advertised because by seeing "ScreenRow" I expect what I see on the screen instead of what's in buffer, according to the link you provided).
