### ISSUE TITLE
"Close All Tabs" does not work when tree-view is focused

### ISSUE THREAD

**Issue by aar0nr** [atom/atom#17509]
### Description

"Close All Tabs" does not work when the tree-view is focused.

### Steps to Reproduce

1. Open a few tabs.
2. Focus the tree-view pane.
3. Go to "File > Close All Tabs".

**Expected behavior:**

The tabs should close.

**Actual behavior:**

The tabs don't close.

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

```
System Version: OS X 10.11.6 (15G20015)
Kernel Version: Darwin 15.6.0
```

**Comment by 50Wliu** [comment]
This is intentional: Close All Tabs will only close the tabs in the pane/dock that you have focused.  Certain dock items, like the Tree View, are marked as unclosable.

**Comment by aar0nr** [comment]
Ah, I see. Thanks for the quick response. 👍
