### ISSUE TITLE
Option `-p` (`--project`) seems to be non-working

### ISSUE THREAD

**Issue by ktrushin** [atom/atom#17504]
I tried the atomproject feature described [here](https://github.com/atom/atom/pull/16845) but instead of opening the project at the specified path, Atom opened an empty editor.
Some console log:
    
    $ tree /depot/p/toolchain_test
    /depot/p/toolchain_test
    ├── LICENSE
    ├── main.cpp
    └── README.md

    0 directories, 3 files
    $ cat ~/toolchain_test.atomproject.json 
    {
        "paths" : ["/depot/p/toolchain_test"],
        "config" : {
            "*" : {
                "editor" : {
                    "tabLength" : 2
                },
                "preferredLineLength" : 80
            }
        }
    }
    $ atom -p ~/toolchain_test.atomproject.json

##### Expected behavior:
Atom opens directory `/depot/p/toolchain_test` and applies config from the `~/toolchain_test.atomproject.json` file.
##### Actual behavior:
Atom opens an empty editor window
##### Reproduces how often:
Each time option `-p` is used.

Options `--safe` and `--clear-window-state` don't improve the situation. Resetting to the factory defaults (`mv ~/.atom ~/.atom-backup`) doesn't help either.

##### Version:
I tried that on Atom vesions 1.26.0, 1.26.1 and 1.27.2.
The most recent set-up is:
OS: Ubuntu 18.04 64-bit
```
$ atom --version
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0
```
```
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.2
python 2.7.15rc1
git 2.17.1
```

**Comment by steveward** [comment]
Thanks for opening this @ktrushin. 

The `--project / -p` flag was removed in https://github.com/atom/atom/pull/17212 to fix the bug reported in https://github.com/atom/atom/issues/17178. As mentioned in https://github.com/atom/atom/pull/17212 this is something that will likely make it back in to Atom in the future, so keep an eye out for updates.

**Comment by ktrushin** [comment]
Oh, sorry for examining already created issues without enough attention.
@steveward, thank you for detailed clarification.
