### ISSUE TITLE
Folding method inside its definition fails if the opening brace is on the next line

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#17505]
### Description

In Rust, it's common to place the opening curly brace of a method on the next line if the method definition contains a `where` clause, like this:

```rust
    fn descend_to_start<S>(&mut self, mut subtree: Tree<T>, db: &S) -> Result<(), S::ReadError>
    where
        S: NodeStore<T>,
    {
      // implementation here...
    }
```

This seems to break folding from inside the method definition. If the curly brace is on the same line, toggling `editor:fold-current-row` will fold the method's body, but if in this case we fold the parent scope.

### Steps to Reproduce

1. For a simpler example, paste the following into a JavaScript file:
  ```
  function foo()
  {
  
  }
  ```
2. Place the cursor inside `foo` and toggle `editor:fold-current-row`.

**Expected behavior:** The method's body gets folded.

**Actual behavior:** Nothing happens, or the parent scope is folded if the method is inside one.

**Reproduces how often:** 100%

### Versions

Atom    : 1.29.0-dev-b81e33c37
Electron: 2.0.1
Chrome  : 61.0.3163.100
Node    : 8.9.3

/cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
Just to clarify, this issue isn't specific to Tree-sitter, right? Atom has never had a notion of *non-local* folds (where, for example, running a command with the cursor at line 1 creates a fold at line 2). When the cursor is on a given line, fold commands have always created or destroyed folds intersecting that line. Similarly, clicking a fold buttons in the gutter has always toggled folds at that line.

![fold](https://user-images.githubusercontent.com/326587/41370207-d9d3ae22-6efb-11e8-9a81-f188cbf72fe6.gif)

**Comment by maxbrunsfeld** [comment]
It would be cool to generalize Atom's fold system to allow for this kind of thing, but it's not totally clear what the UI should be. I assume we would only want to show one fold button in the gutter (on the line with the curly brace, as opposed to the line with the method name).

JetBrains IDEs seem to have the same behavior as Atom in this regard:

![jetbrains-folding](https://user-images.githubusercontent.com/326587/41371170-6279cdfe-6efe-11e8-80dc-98c1bd90b545.png)

The only way to fold the `new` method here is to click in the gutter on the line with the curly brace, or run the `Fold: Collapse` command with the cursor on that line.

**Comment by nathansobo** [comment]
Yeah you're right that it isn't specific to tree sitter. But it seems like with Tree Sitter's capabilities, you could potentially show the fold indicator at the start of the method definition. I could see how that might be confusing though, because maybe you want to fold the parameter list or something. I just reported this since I ran across the behavior while editing and found it unintuitive, and it seems like we might have the tools to improve it with the syntax tree at hand.
