### ISSUE TITLE
Feature request: html syntax definition inside es6 template literals.

### ISSUE THREAD

**Issue by trusktr** [atom/atom#17511]
## Summary

Same as https://github.com/atom/atom/issues/11589

## Motivation

It's be great to have this functionality built in, seeing as Atom is web-based and JavaScript is the primary language (and its derivatives), highlighting of languages inside template strings seems like a good default feature. It's handy especially with HTML and CSS, among other things, but the generic functionality can let it work with any sub-language.

## Describe alternatives you've considered

language-babel doesn't work with TypeScript, etc. We just need an official generic solution that can be hooked into by any other language packages (typescript, coffeescript, etc).

**Comment by rsese** [comment]
Hmmm, is this covered by https://github.com/atom/atom/issues/17392?
