### ISSUE TITLE
Double soft wrap indicator

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#17514]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I still haven't managed to pin down exactly when this happens, but I'd say it happens at least a few times per day when I'm working on soft-wrapped files.

<img width="44" alt="duplicate-soft-wrap-indicators" src="https://user-images.githubusercontent.com/2766036/41429626-a26383a0-6fdb-11e8-9af0-7549ece3554f.png">
Scrolling such that the soft wrap indicators are off the screen and then scrolling back fixes the issue.

### Steps to Reproduce

As of yet, unknown.  Prerequisites include having soft wrap turned on and from what I can tell, a file that is not only soft wrapped but also requires vertical scrolling.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
```
Atom    : 1.29.0-dev-0422e0d61
Electron: 2.0.1
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by bpasero** [comment]
Maybe https://github.com/electron/electron/issues/13367 ?
