### ISSUE TITLE
Atom is causing numerous taskgated errors on macOS

### ISSUE THREAD

**Issue by ErebusBat** [atom/atom#17517]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When launching Atom from the Finder (or Alfred) it will cause many taskgated errors, per second: 
![image](https://user-images.githubusercontent.com/93973/41479855-c75c6466-7089-11e8-8da7-6fb6260ba66a.png)

This causes the system to peg and the fans to turn on, which is hot and kills battery life.

Launching atom from the terminal (inside or outside of tmux) does _not_ reproduce the issue.

### Steps to Reproduce

1. Launch Atom from Dock
2. Observe numerous taskgated errors in Console.app, increased system load
3. Terminate Atom
4. Launch Atom from terminal
5. Observe that no excessive taskgated events are generated.

**Expected behavior:** Launching Atom should not cause my system to peg

**Actual behavior:** It pegs, many security events are generated

**Reproduces how often:** 100% (On my system)

### Versions

```
$ atom --version
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.2
python 2.7.15
git 2.17.0

$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G1408)
      Kernel Version: Darwin 16.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Thneed
      User Name: Andrew Burns (aburns)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2:34
```

### Additional Information

I think this is related to atom/atom#13084 as I can mitigate the issue by adding the following section to my `Info.plist`:

```
<key>LSEnvironment</key>
<dict>
     <key>ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT</key>
     <string>true</string>
</dict>
```

`/usr/local/bin/zsh -ilc 'command env'` does execute and returns the expected environment; however `ps aux | grep 'command env' | grep -v grep` does show that the task seems to hang when executed from Atom.

**Comment by rsese** [comment]
Thanks for the report - I see some of what you describe but not everything with Atom 1.27.2 on macOS 10.12.6.  

> Observe numerous taskgated errors in Console.app, increased system load

I do see the same errors in Console.app after starting Atom (it looks like about 5 errors on startup and it doesn't matter how I start it, I see the same thing from the Dock, command line, or Finder).  I also see if I open a file, another error pops up but otherwise, I don't see any more errors show up.  I also don't notice any large increase in system load in Activity Monitor.  

So you see the errors continue to show up when doing nothing in Atom?  If you temporarily reset to factory defaults, does that make any difference?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

Do you see this behavior with other applications?  E.g. VS Code or Slack?

Some refs based on my Google-ing since this doesn't seem to have been brought up before in Atom but has been reported in general:

* https://www.google.com/search?q=taskgated+macos+error+-67062
* https://www.reddit.com/r/applehelp/comments/3jfxok/what_the_heck_is_up_with_taskgated_process_on_my/
* https://discussions.apple.com/thread/7705551
* https://github.com/Homebrew/homebrew-core/issues/11378

**Comment by ErebusBat** [comment]
@rsese Thank you for looking into this.

>  after starting Atom (it looks like about 5 errors on startup and it doesn't matter how I start it, I see the same thing from the Dock, command line, or Finder). I also see if I open a file, another error pops up but otherwise, I don't see any more errors show up. I also don't notice any large increase in system load in Activity Monitor.

I agree that this is normal behavior and I see that as well (when things are 'good').

>  So you see the errors continue to show up when doing nothing in Atom? 

Correct...  it floods the Console.app and kicks the system into high load.

> If you temporarily reset to factory defaults, does that make any difference?

No it does not.  I even tried nuking Atom.app and re-downloading.  Same result.

> Do you see this behavior with other applications? E.g. VS Code or Slack?

I do not have VS Code.  Slack, Trello, Basecamp are all "normal".

RE: [this reddit post](https://www.reddit.com/r/applehelp/comments/3jfxok/what_the_heck_is_up_with_taskgated_process_on_my/cuqk73j/):

> My honest feeling is that it's probably some kind of process, possibly being launched at start up that gatekeeper is trying to suppress.(assuming that it isn't a bug).

that is what lead me to start looking at specific apps.

My (uneducated) guess is that atom is attempting to patch the ENV and for some reason that causes taskgated to freak out.  I can see that the zsh process doesn't exit quickly and if I manually kill it then it is respawned (and hangs).

I am also not sure exactly how long this has been happening given that I only occurred if it was first launched from the dock/alfred.

Is there any downside to disabling the env patch from the info.plist like I did?  I assume that functionality is there for a reason :)

**Comment by Arcanemagus** [comment]
> Is there any downside to disabling the env patch from the info.plist like I did? I assume that functionality is there for a reason :)

Anything that relies on the environment variables being filled out will fail (such as _many_ packages that launch external programs), if they don't have a separate workaround for macOS giving GUI applications a blank environment.

Atom itself is unlikely to be majorly affected though.

**Comment by RICKROSSWIFEINGRIDE** [comment]
THIS ME ATOM.IO ATOM.IDE INGRID D EALY WHY ALL   Stalking and frauding me
