### ISSUE TITLE
PaneItem onDidTerminatePendingState is ignored unless onDidDestroy is defined

### ISSUE THREAD

**Issue by smashwilson** [atom/atom#17535]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When implementing a PaneItem that's intended to be opened as pending, defining `onDidTerminatePendingState()` is insufficient - you need to implement `onDidDestroy()` as well.

https://github.com/atom/atom/blob/e2c89b29c8c6aabbcf338534a37a2065e978b027/src/pane.js#L617-L626

### Steps to Reproduce

1. Implement a new PaneItem with an opener. Implement `onDidTerminatePendingState` but not `onDidDestroy`.
2. Open it as a pending item with a call to `workspace.open(..., {pending: true})`.
3. Double-click on the tab title.

**Expected behavior:** The item should terminate its pending state and become a non-pending item.

**Actual behavior:** The item remains as a pending item.

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.30.0-dev-15e769a17
Electron: 2.0.2
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0-dev-15e769a17
python 2.7.15
git 2.17.1
```

### Additional Information

Interestingly, choosing "Keep pending tab" from the context menu on the tab works correctly.

**Comment by 50Wliu** [comment]
Ah!  This is probably why I've always been unable to double-click PDF files (`pdf-view`) to make them permanent.

**Comment by jasonrudolph** [comment]
@smashwilson: It sounds to me like we want to treat both `onDidTerminatePendingState` and `onDidDestroy` as optional functions that a `PaneItem` can implement:

- If you only implement `onDidTerminatePendingState`, that's fine: Atom will use it
- If you only implement `onDidDestroy`, that's fine, too: Atom will use it
- If you implement both, Atom will use both
- If you implement neither, that's fine as well

Does that sound right to you?

**Comment by smashwilson** [comment]
Yah, that's exactly what I would expect. I didn't see any reason why the two should be bound together as they are. If I missed something, we should at least amend the Workspace docs to note this.

Also: the [Workspace "Required Methods"](https://atom.io/docs/api/v1.28.2/Workspace) section where these _should_ be documented appears to be broken 😅

**Comment by jasonrudolph** [comment]
> Also: the [Workspace "Required Methods"](https://atom.io/docs/api/v1.28.2/Workspace) section where these _should_ be documented appears to be broken 😅 

@smashwilson: Thanks for pointing this out. I've opened #17746 to track this issue.
