### ISSUE TITLE
Atom freezes when trying to delete file on React App

### ISSUE THREAD

**Issue by rogercodes1** [atom/atom#17548]
Description: when i try and delete a file within atom it freezes and I have to force close atom. 
Replication steps
1. cd into react-app-project new usually
2. atom .
3. try to delete the logo.svg
4. say yes to deleting.
5. have to force close 

expected behavior: delete file || folder

actual: freezes

##repetition: it won't do it for a while then out of nowhere it starts happening where I cannot delete files period. 

##version: 
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

##additional: 
I've tried atom --save and issue still persists.
I have disabled all packages and still happening.

### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report -

> I've tried atom --save

I'm assuming this is a typo and you ran `atom --safe` but could still reproduce?

Are you seeing this behavior only with React applications or can you reproduce with any projects (e.g. a test directory with text files)?

Also, what operating system are you running (it's helpful if you can put all these details in the issue template itself)?

Lastly, did this just start happening recently and it never happened before in previous versions of Atom?

**Comment by rogercodes1** [comment]
That is correct, I just did clean re-install and it is working. I guess it must have been a package.

**Comment by rsese** [comment]
Ahh glad to hear it :+1:
