### ISSUE TITLE
Add a detailed information view to the about screen

### ISSUE THREAD

**Issue by PlanetVaster** [atom/atom#17547]
## Summary

Add an advanced/detailed view to the about screen that adds extra information like what version of electron, chromium, node, v8, etc is being used.

## Motivation

Doesn't necessarily help in a specific way, I just like knowing what my computer is running, and as a developer myself I like seeing what version of libraries are being used by certain software.

## Describe alternatives you've considered

Right now the only way to know what version is being used is to check github commits, which is a tedious and long task, especially for older versions of Atom.

## Additional context

Just a nice feature that I think is good to have.

**Comment by rsese** [comment]
Thanks for the suggestion -

> extra information like what version of electron, chromium, node, v8, etc is being used.

...

> Right now the only way to know what version is being used is to check github commits

`atom -v` provides this information unless I'm misunderstanding?

```
$ atom -v
Atom    : 1.30.0-dev-26cd4a07d
Electron: 2.0.2
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by PlanetVaster** [comment]
You are correct, I did not know that. Still would be nice to have in the about menu. A lot of apps like chrome lists it in their about menu, so it's a common and convenient place to go to imo.

**Comment by trevorrl** [comment]
Hey! I agree with this suggestion, and so I've submitted a PR to the atom/about package with a new 'show more' link below the atom version that, when clicked, shows the Electron, Chrome and Node versions that `atom -v` gives you from the command line. You can find the PR here: https://github.com/atom/about/pull/81

Hope you like it!

**Comment by rsese** [comment]
This was done in https://github.com/atom/about/pull/81, thanks for the contribution there @trevorrl :zap:  From `Application: About`:

![about](https://user-images.githubusercontent.com/734194/60056340-2f12a780-96a6-11e9-9767-283fc0b135bf.png)
