### ISSUE TITLE
Low resolution issue

### ISSUE THREAD

**Issue by mgkid3310** [atom/atom#17555]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom shows up with low resolution, and gets severe at times (looks like 480p at first, gets worse near to 144p at times)

### Steps to Reproduce

1. Open Atom

**Expected behavior:** Shows Atom screen with full resolution (1920 1080 in my case)

**Actual behavior:** Atom screen shows up with low resolution

**Reproduces how often:** Everytime Atom opens

### Versions

Windows 10 Home K 64bit
Atom 1.28.0 & 1.29.0 (beta)

### Additional Information

Issue occured after 1.28.0 update, and was the same on 1.29.0 (beta) when I tried.

Screenshot of the issue is here: https://imgur.com/Fa4LEqk
When you first look at the image, it may look right. But comparing the texts in Atom screen with Windows text, you can easily find out the low resolution issue.

**Comment by rsese** [comment]
Thanks for the report!

> Screenshot of the issue is here: https://imgur.com/Fa4LEqk
> When you first look at the image, it may look right. But comparing the texts in Atom screen with Windows text, you can easily find out the low resolution issue.

Can you share another screenshot that shows other Windows text next to the Atom window so we can see the difference?

**Comment by mgkid3310** [comment]
Sure. Here I have a same file opned with Atom & Sublime Text 3.
https://imgur.com/a/NHxCTTK
You When I focus on the Atom, the resolution increases up to around 480p, but gets lower if I have other window focused.

**Comment by mgkid3310** [comment]
Any idea this bug will be fixed? I can't proceed with any works with Atom now. Or is there a way I could downgrade the Atom?

**Comment by 50Wliu** [comment]
Can you see if this is a GPU issue? https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem

**Comment by mgkid3310** [comment]
Tried all three commands:
`atom --disable-gpu`
`atom --enable-gpu-rasterization --force-gpu-rasterization`
`atom --safe --enable-gpu-rasterization --force-gpu-rasterization`
but still having the same issue.

**Comment by mgkid3310** [comment]
After reinstalling 1.28.0 and using --disable-gpu option, bug is fixed. Seems like Nvidia GPU software issue. Thanks for the help!

ps. my current GPU is GTX1060 6GB (Laptop) model on MSI GS73VR 6RF. Maybe a laptop-GPU related issue?

**Comment by 50Wliu** [comment]
Yes, that's certainly possible.  Chromium (which Atom is built on) maintains a long list of workarounds for GPU bugs; it might be that the current version of Chromium we're using doesn't have a workaround for the bug you ran into.
