### ISSUE TITLE
The latest version cannot be opened

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#17552]
![default](https://user-images.githubusercontent.com/8848263/41753765-fc522b6a-7601-11e8-8030-ebfcce19bc51.png)

![default](https://user-images.githubusercontent.com/8848263/41753754-dee309c8-7601-11e8-83ba-4d78a8b8385a.png)

**Comment by CJK-Regan** [comment]
Same situation. It crashes on Windows 10

**Comment by Heier2013** [comment]
same in mac

**Comment by ServiceYun** [comment]
My mac is in the same situation. Version 10.13.5

**Comment by Varavarforvar** [comment]
same with me

**Comment by coderbean** [comment]
## if you are using shaodsocks,  try close shadowsocks or turn it to Global model or Manual model.
it works for me, but I do not know why

**Comment by linjialiang** [comment]
@coderbean thank you!  Shaodsocks does not change when they become global

**Comment by Varavarforvar** [comment]
@coderbean yet am i

**Comment by linjialiang** [comment]
Shaodsocks system agent can be turned off

**Comment by fengerzh** [comment]
Seems the way of Atom to fix a bug is to totally disable the feature related to bug.

**Comment by coderbean** [comment]
Me: you crash from time to time.
Atom: what? Excuses me?
Me: you crash sometimes.
Atom: Alright，it will be fixed on next version.
......new version release......
Me: I can't ever open atom
Atom: No open, no bug, no fix. everybody happy.

**Comment by thomasjo** [comment]
I'm closing this as a duplicate of #17557. Please subscribe there for updates.

**Comment by laudukang** [comment]
@coderbean  it works on windows 10 1709
