### ISSUE TITLE
Uncaught Error: The specified module could not be found. \?\C:\Users\Dewesoft\AppData\Local\atom\app-1.28.0\resources\app.asar.unpacked\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node

### ISSUE THREAD

**Issue by krachaan** [atom/atom#17558]
Steps to reproduce:
1. Open atom
2. Press any key

Bug:
Every key on the keyboard I press throws this error and doesnt execute the keys command. Can't even delete a single character. I can write code but can't delete anything because key shortcuts don't work. I just started atom this morning and this happened.
![image](https://user-images.githubusercontent.com/25060562/41771598-f0cbd070-7615-11e8-86f3-94a2bc33c005.png)

**Comment by daviwil** [comment]
Hi @krachaan, can you give some more details about your system?  What's the specific version of Windows you're using/

**Comment by daviwil** [comment]
Another thing: are you using any anti-virus software?  keyboard-layout-manager.node seems to commonly be marked as a trojan and gets deleted by some anti-virus vendors: https://github.com/atom/atom/issues/14461

I'd recommend marking `C:\Users\Dewesoft\AppData\Local\atom` to be ignored by your anti-virus software and then try reinstall Atom.

**Comment by krachaan** [comment]
Found a fix in this thread https://github.com/atom/atom/issues/14461 thanks anyway.
It's just weird it suddenly stopped working when I did nothing, I have no antivirus either.

**Comment by daviwil** [comment]
Can you tell me which fix you used from that thread?  Might be helpful to diagnose the issue.  Glad it worked for you at any rate!

**Comment by krachaan** [comment]
Tried every fix in the thread but the issue was finally fixed by just reinstalling without uninstalling atom.

**Comment by daviwil** [comment]
Thanks!  Seems like we need to keep a closer eye on how we unpack native modules from the Atom package, something may be going on there.
