### ISSUE TITLE
Crashes bug on MAC OS with Proxy

### ISSUE THREAD

**Issue by arthurkiller** [atom/atom#17567]
macos 10.13.5
atom 1.28.0
proxy: shadowsock-NG 1.7.1 with auto PAC mode

-------

Can you guys fix crash bugs on atom? 
Those problem really got me tired since 1.25 version.

**Comment by Bignan** [comment]
atom sucks

**Comment by Bignan** [comment]
already uninstall

**Comment by thomasjo** [comment]
Duplicate of #17557.
