### ISSUE TITLE
Tab reordering extremely slow in large projects

### ISSUE THREAD

**Issue by pkriete** [atom/atom#17561]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tab reordering slows to a crawl when the tree view contains a few hundred visible items. Related to atom/tabs#390, but unfortunately not fixed by it.

Happy to help contribute a PR if someone can point me in the right direction.

### Steps to Reproduce

1. Open a large directory
2. Expand the tree view so a few hundred items are visible
2. Open a few files to get some tabs
3. Try reordering tabs

**Expected behavior:** Tabs are reordered immediately

**Actual behavior:** Can take up to several seconds to reorder tabs

**Reproduces how often:** Always

### Versions

```
MacOS 10.13.4

Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by 50Wliu** [comment]
@pkriete Can you try creating a profile to see where the slowdown is happening? https://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance

**Comment by jmahhh** [comment]
I seem to be having a more extreme version of this on Arch Linux - my directory has less than 100 smallish files and moving a tab causes the editor to for an indeterminate amount of time...

**Comment by jmahhh** [comment]
@50Wliu I'd like to but the editor just hangs so I can't access the profiler either?
