### ISSUE TITLE
Colour rendering issue on Atom 1.28.0 / Windows 10

### ISSUE THREAD

**Issue by garyb** [atom/atom#17562]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Since updating to 1.28 the colours throughout Atom are no longer rendering correctly - it appears like the gamma has been altered or something, the contrast is lower and everything is slightly lighter.

Colours are not rendering correctly even in the dev tools. Here's two I screen-shotted from the "computed" panel:

![colours-off](https://user-images.githubusercontent.com/693642/41789270-9b582e0a-7646-11e8-9a9a-98515410149a.png)

Examining those colour squares in an image editor you can see that the colour reported as #cc6666 is actually #b36d68, and #1d1f21 is rendering as #232426.

Running with `--disable-gpu` does have some visible differences:

![image](https://user-images.githubusercontent.com/693642/41789427-2ad6ff84-7647-11e8-8fc5-abdd181daaab.png)

Note the render tile edges to the right. The darker area is showing the actual correct colour for the editor background.

### Steps to Reproduce

n/a - Atom auto-updated, now it's permanently in this state

**Expected behavior:** Colours to appear as they are defined

**Actual behavior:** Colours do not render as per their definitions

**Reproduces how often:** 100%

### Versions

Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

Windows 10
Nvidia GeForce GTX 1070, 398.11 drivers

Everything appears fine on my Mac, which is using the exact same editor and style configuration.

**Comment by ntilotta** [comment]
Ubuntu 18.04, same issues

**Comment by rsese** [comment]
Thanks for the report!

I think you may be running into the color profile issue described in our 1.28 release blog post:

http://blog.atom.io/2018/06/21/atom-1-28.html#support-for-custom-color-profiles

Try updating `Settings > Color Profile` to `Use sRGB color profile` and let us know if that restores the color rendering you saw previously.

**Comment by garyb** [comment]
Ok, well I feel pretty stupid now :smile: I did look around for a colour profile setting but not closely enough apparently. That does indeed fix it, thanks!
