### ISSUE TITLE
Shining noise appears between characters of menus and main panel

### ISSUE THREAD

**Issue by falsandtru** [atom/atom#17563]
What is this?

![screenshot from 2018-06-23 09-16-45](https://user-images.githubusercontent.com/3143368/41803666-32cd45ca-76c6-11e8-8da3-9a288af66ec9.png)

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

As described in the title.

### Steps to Reproduce

1. Launch Atom.

**Expected behavior:** [What you expect to happen]

No noise.

**Actual behavior:** [What actually happens]

Has noise.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always.

### Versions

Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.15rc1
git 2.17.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Arcanemagus** [comment]
Can you try [checking if your GPU](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem) is the issue here?

**Comment by Arcanemagus** [comment]
You are also running a _very_ out of date Atom, please try [installing the latest](https://flight-manual.atom.io/getting-started/sections/installing-atom/) v1.28.0 version from the official source?

**Comment by falsandtru** [comment]
v1.28.0 solved this problem, thanks!
