### ISSUE TITLE
Atom won't close

### ISSUE THREAD

**Issue by BlairLane22** [atom/atom#17570]
**Description**
When using atom and I want to close the window, I would go and click the X at the top left. But ever since atom crashed, those three icons at the top left. The X, the -, and the re-sizer aren't there anymore.  (On Mac)

**Expected behavior:** 
For those three icons, at the top left, to be there.

**Actual behavior:**
The aren't there anymore

**Reproduces how often:**
When ever I open atom they aren't there anymore.

### Versions
1.28.0

### Additional Information
I have tried deleting and re-installing atom and that still won't help.

**Comment by rsese** [comment]
Thanks for the report - it looks like the `Prerequisites` section of the issue template was removed, did you try safe mode or any of the other [debugging steps](https://flight-manual.atom.io/hacking-atom/sections/debugging/)?

Also, what version of macOS are you running?

**Comment by BlairLane22** [comment]
@rsese Thanks I went to the debugging steps and reset my settings back to the default settings and it works now.

**Comment by rsese** [comment]
Great, thanks for letting us know :+1:
