### ISSUE TITLE
Provide an ongoing working Terminal able to integrate with Atom.

### ISSUE THREAD

**Issue by the-j0k3r** [atom/atom#17580]
## Summary

>One paragraph explanation of the feature.

Provide or support the maintenance of a working terminal for Atom.

Contenders for forks: Platformio-IDE-Terminal

## Motivation

>Why are we doing this? What use cases does it support? What is the expected outcome?

Currently there is ONLY one barely just working Terminal for Atom and that is [no longer actively developed](https://github.com/platformio/platformio-atom-ide-terminal/issues/543) and has just about been able to survive the Atom 1.28.0 and electron 2.0.3.

Motivation: The future of Atom, how will Atom justify its existence in the modern editor world without a built-in or working Terminal that integrates in Atom? 

## Describe alternatives you've considered

>A clear and concise description of the alternative solutions you've considered. Be sure to explain why Atom's existing customizability isn't suitable for this feature.

One alternative is VScode from your parent company MIcrosoft, but its also the death to opensource competition and innovation.

A second alternative is revert to ancient editors and/or OLD workflows. Use convoluted workflows with external consoles.

## Additional context

There was already a request that was closed see  atom/atom#12649

Back then there were actively developed alternatives, now, the reality has changed.

**Comment by lierdakil** [comment]
[atom-ide-ui](https://atom.io/packages/atom-ide-ui) provides a terminal emulator since v0.11.0. Regrettably, the last version seems to be broken on Windows (https://github.com/facebook-atom/atom-ide-ui/issues/278)

**Comment by lee-dohm** [comment]
Thanks for the suggestion. The closest we're going to get to a built-in terminal is in atom-ide-ui.
