### ISSUE TITLE
[FIX] `Could not create temporary directory: Permission Denied` v1.28.0

### ISSUE THREAD

**Issue by RedcoatAsher** [atom/atom#17588]
![image](https://user-images.githubusercontent.com/6314239/41925894-abfe90c6-7922-11e8-9bf4-6692bc8b0600.png)
For those getting an error like this ^ when trying to update, run the following bash in terminal...

```shell
$ sudo chown -R $USER ~/Library/Caches/com.github.atom.ShipIt
$ sudo chown -R $USER ~/Library/Application\ Support/com.github.atom.ShipIt
```

I got this today trying to update to v1.28.0; Why does this continue to happen?!

**Comment by rsese** [comment]
> For those getting an error like this ^ when trying to update, run the following bash in terminal...

Thanks, we have this mentioned in our FAQ:

https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054

> I got this today trying to update to v1.28.0; Why does this continue to happen?!

Not everyone runs into this issue and we haven't been able to reproduce it ourselves as far as I know.  We've seen this when Atom is [installed as a different user](https://github.com/atom/atom/issues/13804#issuecomment-328403955) but I haven't seen many other explanations as to why it happens on a particular person's computer.   If you or anyone comes across more information, we're happy to hear it.

**Comment by OwenEdwards** [comment]
Just as a note here about one possible cause of this issue, for me it happened after I'd run **CleanMyMac 3** to clean up old cache files, and I'm almost certain that it cleaned `~/Library/Caches/com.github.atom.ShipIt`. I got the `Could not create temporary directory: Permission Denied` error message, and doing the two `sudo chown ...` commands above fixed it.

**Comment by ionescu77** [comment]
Happened to me today: Atom 1.34.0 on Mac Mojave. Thank you for the workaround
