### ISSUE TITLE
script/build --install <destroot> tries to install things elsewhere

### ISSUE THREAD

**Issue by RJVB** [atom/atom#17584]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
N/A

### Description

I'm trying to integrate a local Atom with a packaging approach that installs to a temporary location (destroot/DESTDIR), from which it would then be bundled and, ultimately, installed. I'm running into a few issues doing that, including the one below:
If I understand the build instructions correctly, this should be possible using `script/build --install=/path/to/destroot`. Initial results suggest that would inde indeed be the case if it weren't for certain files that are installed elsewhere (not even in the location provided by `getInstallDirectory()` in `command-installer.js`).

### Steps to Reproduce

1. script/build
2. script/build --install=/path/to/destroot

**Expected behavior:** [What you expect to happen]

The entire install tree should appear under /path/to/destroot/$prefix

**Actual behavior:** [What actually happens]
```
Moving generated startup blob into "/path/to/atom-1.28.0/out/atom-1.28.0-amd64/snapshot_blob.bin"
Skipping creating debian package. Specify the --create-debian-package option to create it.
Skipping creating rpm package. Specify the --create-rpm-package option to create it.
Skipping artifacts compression. Specify the --compress-artifacts option to compress Atom binaries (and symbols on macOS)
Installing "atom-1.28.0-amd64" at "/path/to/destroot/opt/local/share/atom"
>>> Installing icons at "/usr/share/icons/hicolor"
>>> Error: EACCES: permission denied, open '/usr/share/icons/hicolor/1024x1024/apps/atom.png'
  at Object.fs.openSync (fs.js:646:18)
  at copyFileSync (/path/to/atom-1.28.0/script/node_modules/fs-extra/lib/copy-sync/copy-file-sync.js:21:16)
  at Object.copySync (/path/to/atom-1.28.0/script/node_modules/fs-extra/lib/copy-sync/copy-sync.js:32:7)
  at fs.readdirSync.forEach.imageName (/path/to/atom-1.28.0/script/lib/install-application.js:103:14)
  at Array.forEach (<anonymous>:null:null)
  at module.exports (/path/to/atom-1.28.0/script/lib/install-application.js:99:36)
  at binariesPromise.then.then.then.then.packagedAppPath /path/to/atom-1.28.0/script/build:132:7)
  at <anonymous>:null:null

```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom 1.28.0 built from source (using npm 6.1.0 and nodejs 8.11.3), pulls in apm 1.19.0
Happens on Linux.

**Comment by rsese** [comment]
Thanks for the report!

>>> Error: EACCES: permission denied, open '/usr/share/icons/hicolor/1024x1024/apps/atom.png'

This particular error is a duplicate of https://github.com/atom/atom/issues/16853 so you can subscribe there for updates if you'd like.

> If I understand the build instructions correctly, this should be possible using script/build --install=/path/to/destroot. Initial results suggest that would inde indeed be the case if it weren't for certain files that are installed elsewhere (not even in the location provided by getInstallDirectory() in command-installer.js).

Would portable mode be an option for you?

https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode

**Comment by RJVB** [comment]
> Would portable mode be an option for you?

Not really, no.

The underlying idea was to build Atom from source and have it use the shared libraries already installed through the same package manager (or on the host), including nodejs and FFmpeg.
Apparently that's not what happens when you build from source...

**Comment by thomasjo** [comment]
The `--install` option unfortunately does not work great on non-macOS systems. Personally I always use the `--create-debian-package` instead, and install the package using `dpkg` instead. This gives me more control over the entire installation process. I would the same flexibility with the RPM package.

None of this solves the real problem, but hopefully it's a reasonable workaround for the time being.

**Comment by RJVB** [comment]
Actually, correcting the install path in that icon base dir function is the only thing required. That has to be a path-specific patch of course as I haven't found any way yet to control the install location (prefix), so it's not a generic fix either. But it works with a packaging system that supports patching the code automatically.

**Comment by RJVB** [comment]
The bigger problem here is the fact that nodejs applications apparently always fetch their own dependencies even if you build them from source. That really makes it a lot less interesting to include them in a packaging system that has its own dependency management (like one finds in almost any distribution).
