### ISSUE TITLE
Issue with importing Modules installed with pip3. MacOS

### ISSUE THREAD

**Issue by ethanbreck** [atom/atom#17581]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

Read the FAQ and the debugging guide, and there is still the ImportError. 
Full code im trying to work on, if that helps: https://github.com/ethanbreck/FFN-Scraper/blob/master/WebScraper.py

### Description
So i installed request to do the HTML requests for python 3 in my script, and so far it hasnt run. Ive made sure its installed with Pip3, and and made sure all my packages were up to date, and here is the error:

Traceback (most recent call last):
  File "/Users/ekb/Docs/github/FFN-Scraper/WebScraper.py", line 1, in <module>
    import requests
ImportError: No module named requests
[Finished in 0.087s]

### Steps to Reproduce

1. So i have imported requests on the first line of atom, and run the program, it outputs the traceback listed above, 
2. I check and run it in terminal, and it outputs correctly, and puts the output in the right file.

**Expected behavior:** For requests to import correctly, and it run the script correctly, like it does in terminal. 

**Actual behavior:** It fails every time with that traceback error popping out. 

**Reproduces how often:** 100% of the time

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0
python 2.7.15
git 2.15.2

### Additional Information

If any additional data is needed, ill try my best to provide it, Videos of me running the script, pictures, config settings.

**Comment by 50Wliu** [comment]
This seems like a support request, which is better suited for [Discuss, the official Atom and Electron message board](https://discuss.atom.io), where there are a bunch of helpful community members that should be willing to point you in the right direction.
