### ISSUE TITLE
Atom 1.28.0 - haml files crash the editor

### ISSUE THREAD

**Issue by calebmeyer** [atom/atom#17595]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I've been seeing intermittent crashes. When atom crashes, I end up having to clear the window state to get it back (it crashes on start until that).

### Steps to Reproduce

1. Open atom
2. Open several (somewhere between 5 and 8) haml files

**Expected behavior:** Atom is stable

**Actual behavior:** Atom crashes

**Reproduces how often:** 
I can reproduce this 100% of the time. Immediately after a crash, atom crashes on launch in safe mode or normal mode until I clear the window state.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
![image](https://user-images.githubusercontent.com/3342777/41990395-e52cdd90-7a07-11e8-8b98-437f16163e72.png)
![image](https://user-images.githubusercontent.com/3342777/41990424-fb15185c-7a07-11e8-8c5c-ebfd8b5161f5.png)

My full settings: https://gist.github.com/calebmeyer/57593e1d220fef2910e3d881852a04b3

### Additional Information
Because the crash happens so infrequently (about once every 2-5 hours), I've only reproduced it for my main work project, which is a ruby and rails app (single top level git folder).

Atom has only started crashing this way since I installed 1.28.0 (stable)

When it crashes, I only rarely get an actual crash dump. I'll email you the crash logs.

I tried debugging in visual studio, and it was usually corrupted heap errors

This will occasionally occur when I try to open a new file by double clicking it from the tree-view. I'm not sure if that's coincidence, but it's happened a few times (different files each time)

**Comment by calebmeyer** [comment]
Okay, some more data:
I can consistently reproduce the crash by opening files (either by double clicking the tree view or with ctrl-p) which have the .haml extension.

I can also consistently reproduce the crash (crashes fairly quickly) with settings open.

Neither of these seem to happen in safe mode anymore, despite my crashes from safe mode yesterday.

I'm going to try uninstalling language-haml from my packages

**Comment by calebmeyer** [comment]
I uninstalled language-haml, still getting crashes when not in safe mode. I'll keep debugging

**Comment by calebmeyer** [comment]
Okay, just got it to crash (at launch) in safe mode again. The window still had 7 haml files open from when it crashed in normal mode, and those somehow crashed it in safe mode.

I've been testing with different haml files (we have plenty), so I don't think it's a particular one.

**Comment by calebmeyer** [comment]
Got another crash in safe mode (after clearing window state), happened when I opened my 8th haml file.

**Comment by rsese** [comment]
Thanks again for the detailed report and updates @calebmeyer 👍 

> I can consistently reproduce the crash by opening files (either by double clicking the tree view or with ctrl-p) which have the .haml extension.

So it looks like you've narrowed things down to crashing when opening/working with the .haml files in your project, any chance you can now reproduce with some other random public Rails app using .haml files?

**Comment by calebmeyer** [comment]
Okay, I was able to reproduce the error using https://github.com/iwasrobbed/Brevidy and clicking the haml files (in safe mode) in app/views/badges

**Comment by calebmeyer** [comment]
I'll also note that my team has been having the same problems, but no one said anything until our retrospective today.

**Comment by rsese** [comment]
Finally finished cloning that repository - I opened it up in safe mode and double-clicked on all the .haml files in app/views/badges but Atom didn't crash for me.  I had also copied your init script and restarted Atom before testing.

I'll keep poking for a bit...

**Comment by rsese** [comment]
> I'll also note that my (exclusively macintosh) team (7 other engineers) has been having the same problems, but no one said anything until our retrospective today.

Oh interesting - so safe mode with Atom 1.28.0 for everyone?  What version(s) of macOS are they running and do any of them have crash logs?   I just tried on macOS 10.12.6 with Atom 1.28.0 in safe mode and the same .haml files but was unable to reproduce.

**Comment by calebmeyer** [comment]
They're all on high sierra, none of them even know about safe mode, but we all have completely different setups (everyone organically grew their setup). Most of the macs are 2016 touchbar models, a few 2017 touchbar and one slightly older model (before the touchbar)

**Comment by rsese** [comment]
> I'll see if someone will help me repro the issue.

:+1:  If any of them have a crash log, that would be great too.

**Comment by yogeshkm** [comment]
hi, atom 1.28.0 crashes when i open 'C' files as well. Should I open a new ticket ?

**Comment by thomasjo** [comment]
@yogeshkm Judging from the information visible in your screenshot, you're issue should be covered by #17557. Please see that issue, and feel free to subscribe there to receive notifications when the issue is updated/resolved.

**Comment by calebmeyer** [comment]
I got some responses back, but no one has sent me crash logs yet. They're seeing crashes despite not opening up any haml files.

**Comment by calebmeyer** [comment]
I've been able to reproduce the crash by opening the settings view with `ctrl-,` a few times now. Not sure if that helps.

I've had to switch to VS Code and Sublime to get any work done, and both are painful to work in. Keybindings are hard to figure out, and the tree views don't have hardly anything in their context menus.

**Comment by rsese** [comment]
Hmm, the biggest issues we've seen with 1.28.0 are crashes related to proxies (on both macOS and Windows) and a different crash specific to macOS 10.10.x and lower.  You and your team don't happen to be behind the same company proxy?  I didn't see that mentioned so far but since you and your whole team is having trouble across different machines I figured I'd double check.

Also, I assume that 1.27.2 doesn't crash or are there problems with that version too?

**Comment by calebmeyer** [comment]
We are all on the same work wifi. I don't know for sure if it is a proxy, but I know I can VPN from home. How do I find that out?

**Comment by rsese** [comment]
Not sure about the best way to test that but maybe a roundabout way to see if it's related to a network proxy is to temporarily connect to a different network if possible, like tethering on a phone for example and see if that makes any difference?

**Comment by yogeshkm** [comment]
FYI, the crash on my machine occurred while in office behind a proxy

**Comment by calebmeyer** [comment]
I connected to my home network and the crash persists.

**Comment by calebmeyer** [comment]
I downgraded to atom 1.27.2, turned off auto-updates, and am once again stable. I'm going to work with this version until 1.29 comes out, or until someone tells me the issue is fixed in (for example) a 1.28.1

**Comment by lee-dohm** [comment]
Have you tried using `atom --foreground` to see if it could give us some additional output on this?

**Comment by calebmeyer** [comment]
I see two blank lines, but no other output from WSL bash or from PowerShell when running with the --foreground flag. Also bash isn't listing the crash as a non-zero exit code.

**Comment by rsese** [comment]
Thanks for bearing with us @calebmeyer - another maintainer was interested in seeing what happens right up until the crash.  Would you be able to share a GIF/screencast with that https://github.com/iwasrobbed/Brevidy repository we used to test with 1.28.1 that shows the crash with your repro steps?

**Comment by calebmeyer** [comment]
Okay, so atom is now perfectly stable if I'm just editing files. If I try to change settings, though, it crashes (still in safe mode, now on 1.28.1).

Should I re-open this issue or log a new issue?

Screen Capture (mp4):
[crash.zip](https://github.com/atom/atom/files/2177892/crash.zip)
