### ISSUE TITLE
Ctrl + Shift+ P for command palette doesn't work on windows 10 64 bits

### ISSUE THREAD

**Issue by tgchen** [atom/atom#17597]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Toggle Command Palette from short cut key or menu bar, it will not work]

### Steps to Reproduce

1. [Open Atom]
2. [Press short cut key Ctrl Shift P]
3. [Menu Bar -> View -> Toggle Command Palette]

**Expected behavior:** [search bar show up]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3
Windows 10 x65

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report - I'm unable to reproduce with Atom 1.28.0 on Windows 10.

Was there any difference at all when you ran in safe mode?

Also, when you use <kbd>ctrl-shift-p</kbd>, can you share a screenshot of what you see with the keybinding resolver open?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings

**Comment by tgchen** [comment]
It shows the same thing if I did it in the save mode. 
![capture](https://user-images.githubusercontent.com/987425/42056691-e6392298-7acf-11e8-9698-9e786689a0de.JPG)

**Comment by rsese** [comment]
Did you mean to close the issue?  I see the command palette showing in your screenshot so it seems like things are working unless I mis-understood the issue you described?

**Comment by tgchen** [comment]
Yes. I figure it out, and it start to show, so I closed the ticket. Thank you
