### ISSUE TITLE
when open atom in first install

### ISSUE THREAD

**Issue by shenmiaoling** [atom/atom#17590]
![2018-06-27 4 52 31](https://user-images.githubusercontent.com/17367714/41963875-3cf2628e-7a2b-11e8-9e93-ec3ee520c9cf.png)

**Comment by thomasjo** [comment]
I don't understand what the screenshot says, and the issue template is not filled it, but based on the locale I'm going to assume this is a duplicate of #17557. Please subscribe there for updates.

**Comment by 50Wliu** [comment]
This seems more likely to be #17565 instead.
