### ISSUE TITLE
Specific Periodic Crashes (every 9.5 mins) on Windows 10

### ISSUE THREAD

**Issue by jlc-christie** [atom/atom#17599]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Periodic crashes (every ~9.5 minutes) on Windows 10. This is similar to 2 previously reported issues but it is not because of a proxy or VPN and this is not on Mac OS X. Also, Atom does not feel 'sluggish' as described in the Mac OS X issue. It performs perfectly normally up until the exact moment it crashes. No crash report log is given to me upon reopening Atom. 

I have followed the flight manual:
 - Latest version of Atom (1.28.0)
 - Tried in safe mode -> no change
 - Cleared saved state
 - Reset to factory defaults
 - Checked for linked packages (despite the fact I haven't done development on Atom itself)
 - Haven't changed any config files 

### Steps to Reproduce

1. Start Atom
2. Wait 9.5 mins
3. Crash

**Expected behavior:** [What you expect to happen]
It not to crash

**Actual behavior:** [What actually happens]
It crashes

**Reproduces how often:** [What percentage of the time does it reproduce?]
9.5 minutes after launch

### Versions

```
C:\Users\jlc_c>atom --version

Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

C:\Users\jlc_c>apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0
python
git 2.13.2.windows.1
visual studio

```

Running Windows 10 Pro (version 1803) on a Surface Pro 4 - i5 8GB RAM, 256GB SSD

### Additional Information

Can add crash dump files if needed. 
Also tried changing the File System Watcher to the 'Experimental Filesystem Watching Library' to see if it was something to do with the default watcher as this seems like it is periodic in nature; did not work.

-- Edit -- 
Forgot to mention, this problem still persists on the 1.29 beta

**Comment by stadelmanma** [comment]
@jlc-christie might try downgrading to Atom 1.27 and see if that works still. I'm having major issues on a Mac side with 1.28+ as well. If it works at least you have a functional IDE again until a patch is rolled out.

**Comment by rsese** [comment]
Thanks for the report - 

> it is not because of a proxy or VPN and this is not on Mac OS X

Just to clarify this point, you mean that you're not using a proxy?  We have had Windows users report crashes with proxies as well with 1.28, we ended up closing it as a duplicate (/cc https://github.com/atom/atom/issues/17574).

As referenced by @stadelmanma, did this crash just start when you updated to 1.28.0 or did you have this problem in 1.27.2 as well?

Lastly, if you wait 9.5 minutes will Atom crash if you're not doing anything at all in Atom?  Or do you need to be actually doing something before Atom crashes?

**Comment by jlc-christie** [comment]
@rsese 
Yes - no proxy is being used.

This crash wasn't present in 1.27.2 as far as I'm aware, although I may well have unintentionally skipped from a lower version. Are version history logs kept, if so, I can check this. 

It crashes without any interaction, (in fact, it crashed whilst typing this reply). I will try downgrading later today to see if it is resolved. 

Thanks

**Comment by the-j0k3r** [comment]
maybe related to this https://github.com/atom/atom/issues/17642 though I havent calculated any specific in between crash durations.

Im on windows 10 1803

**Comment by rsese** [comment]
> It crashes without any interaction, (in fact, it crashed whilst typing this reply). I will try downgrading later today to see if it is resolved.

Thanks @jlc-christie - one other check that I forgot ask about is if you happen to have a `.git\` directory in your home directory?  

> maybe related to this #17642 though I haven't calculated any specific in between crash durations.

Yeah seems like it could be related but it's not clear yet so thanks for opening a new issue :+1:

**Comment by the-j0k3r** [comment]
> Yeah seems like it could be related but it's not clear yet so thanks for opening a new issue +1

Yea I tried adding all the info I had available, the crash log maybe clews in there. Ive no idea so far.

**Comment by jlc-christie** [comment]
> Thanks @jlc-christie - one other check that I forgot ask about is if you happen to have a .git\ directory in your home directory?

@rsese No

**Comment by rsese** [comment]
@jlc-christie - can you confirm if you see any difference with 1.28.2?

**Comment by jlc-christie** [comment]
@rsese Problem does not occur after updating to 1.28.2, however it is interesting to note that Atom's automatic update did not work and may be what was causing the crash. I was on 1.28.0 this morning and the problem still occurred, after clicking in the help menu it said 'Checking for updates...' followed shortly after by 'Downloading update...' and then a little later subsequently crashed. The specific period between crashing may have been due to the time that Atom takes to check, then download and attempt to install an update. As my work connection is very stable, the time between crashes would also be very consistent... 

If this is not occurring with anyone else this will be of little use but may be interesting for maintainers to look in to in case of future bugs...
