### ISSUE TITLE
Strange color shift on Mac OSX when custom monitor profile applied

### ISSUE THREAD

**Issue by AlbertPMarti** [atom/atom#17594]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When custom monitor color profile applied, some blocks of background colour appear, specially in the editor.

### Steps to Reproduce

1. Apply custom color profile on Mac Preferences.
2. Color blocks appear.
3. [and so on...]

**Expected behavior:** [What you expect to happen]
![captura de pantalla 2018-06-27 a les 18 49 50](https://user-images.githubusercontent.com/39406701/41987921-f3ffe0aa-7a3a-11e8-8e57-2bcb1c1fa754.png)

**Actual behavior:** [What actually happens]
![captura de pantalla 2018-06-27 a les 18 45 49](https://user-images.githubusercontent.com/39406701/41987939-fde2d014-7a3a-11e8-96d3-68a2b9bac77b.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!

I think you may be running into the color profile issue described in our 1.28 release blog post:

http://blog.atom.io/2018/06/21/atom-1-28.html#support-for-custom-color-profiles

Try updating Settings > Color Profile to Use sRGB color profile and let us know if that restores the color rendering you saw previously.

**Comment by AlbertPMarti** [comment]
Thanks a lot for your reply. I apologize as I didn't read the 1.28 release blog post. I've done as you suggested and those colour blocks just disappeared.
I guess this addresses my colour problems. Thanks a lot, rsese.
