### ISSUE TITLE
Weird freezes in TextBuffer.findAllInRange (heisenbug)

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#17607]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

This is going to be somewhat weird, but I've found a heisenbug. That is, a bug that's very tricky to reproduce.

Basically, `superstring`'s `find_all` and `find_all_sync` seem to go into an infinite loop under some very particular circumstances which I don't completely understand myself, at least not yet.

### Steps to Reproduce

Long story short, I've created a test package https://github.com/lierdakil/superstring-regex-hang-test that runs `TextBuffer.findAllInRangeSync` on each text change in the range `(0,0), (1,0)`.

With that package active, the following steps trigger a hard freeze and an apparent runaway memory leak in Atom on Windows:

1. Create a new text document
2. Add two non-empty lines
3. Save the file (important!)
4. Select whole first line
5. Press delete or backspace

**Expected behavior:** No freeze

**Actual behavior:** Hard freeze

**Reproduces how often:** At least 80% of the time in my tests, but YMMV

I should note that I was *not* able to reproduce this on Linux. Not entirely sure why, but it *might* have something to do with CRLF vs LF.

A video demonstrating reproduction steps and the problem itself: https://youtu.be/VU7WNyzHq88

### Versions

`apm --version`:
```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.0
python
git 2.16.2.windows.1
visual studio
```

`atom --version`:
```
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

Originally reported here: https://github.com/atom-haskell/haskell-ghc-mod/issues/238

/cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
Thanks for creating that test package @lierdakil, that was extremely helpful. I reproduced the problem with a unit test and I think I have a fix.

**Comment by maxbrunsfeld** [comment]
When you get a chance, could you see if the bug is reproducible on Atom's master branch?

**Comment by lierdakil** [comment]
Yep, couldn't reproduce on 1.30.0-dev-a41a345de, so it's evidently fixed. Thanks!
