### ISSUE TITLE
Wrong version of file displayed in editor after changing git branch

### ISSUE THREAD

**Issue by meridionaljet** [atom/atom#17626]
The file contents displayed in the editor following a git commit and branch switch are not reliable. My workflow is the following:

Starting on the 'dev' branch:
* Edit some file in Atom
git commit
git checkout master
git merge dev
git push
git checkout dev
* Return to the Atom editor

A certain percentage of the time (less than 25%?), when I return to the editor after these operations, the file displayed will be the version that was in master prior to merging the changes from dev, even though I have switched back to the dev branch. It is not due to a small delay between the branch switch and the editor grabbing the new file, because I have frequently worked on these files without realizing they were incorrect, and then issued a new commit, only to find out the changes from my last commit were not present in the file anymore.

This occurs regardless of whether I use Atom's git functionality or use git in a terminal. It has occurred on at least 3 different machines that I have used, all running either Fedora or CentOS linux. This has happened to me in all versions of Atom since I started using it about a year ago, up to and including 1.27.0. The fact that the behavior is random makes this impossible for me to reproduce reliably. All I know is that I have to be very careful to make sure the file I'm editing has the correct contents in the editor following a branch switch. 

I'm not sure if this has something to do with performing back-to-back branch switches. When the problem occurs, it's like the editor followed my "git checkout master" just fine, but it missed the "git checkout dev" at the end, which is supposed to get me back to the file version I had before I stopped to commit changes. Again, this only happens a fraction of the time, but often enough that I can never trust the file contents in front of me after I switch branches.

**Comment by meridionaljet** [comment]
There do seem to be parallels there to the behavior I'm seeing. However, I am unable to consistently reproduce a problem with either workflow, as the buffer only fails to update a fraction of the time. This would also make it rather difficult to verify if it occurs in safe mode, and may be why this bug has been difficult to pin down for the last few years.

I've observed this behavior in CentOS 7.x with git 1.7.1 and 1.8.3, and in Fedora 25-28 with git 2.x up through 2.15.1.

**Comment by Josvanegmond** [comment]
Here's exactly what happens:
I disabled all core git packages just to be sure nothing is interfering there.
In a separate terminal I select the develop branch.
In Atom, I open a file and make a modification.
In terminal, I commit this modification and switch to the master branch.
In Atom, the file **updates automatically** to that of the file in master, reverting the changes.
In terminal, I merge develop with master.
In Atom, the file **does not update**.
In terminal, I switch back to develop.
In Atom, the file **remains unchanged**.
I don't know why it correctly updates when switching from develop to master, but not the other way around.
Re-opening the file will display the correct file in develop or merged master, but if you continue to develop you are thrown back in older versions of the file.

It seems that Atom needs to update all open files more reliably when there is an external change to that file.
