### ISSUE TITLE
Alert icons aren't displayed properly

### ISSUE THREAD

**Issue by szmarczak** [atom/atom#17629]
### Prerequisites

* Put an X between the brackets on this line if you have done all of the following:
    * [x] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [x] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [ ] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Alert icons aren't displayed properly.

### Steps to Reproduce

1. `sudo snap install atom`
2. Open Atom.
3. Check out any alert:
   1. Init a git repo using the GitHub panel.
   2. Try to force push.
   3. See the broken alert icon.

**Expected behavior:** Nice [existing] icons.

**Actual behavior:** Broken icons.

**Reproduces how often:** Always.

### Versions

```bash
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.2
python 2.7.15rc1
git 2.17.1
```

### Additional Information

![image](https://user-images.githubusercontent.com/36894700/42326446-75a73f5c-8069-11e8-9c83-32983eeb3320.png)

![screenshot from 2018-07-05 15-40-04](https://user-images.githubusercontent.com/36894700/42326555-c65f99e4-8069-11e8-99fe-8d70044b3c4c.png)

/cc @rsese 

> [#17398] Also, did you install Atom using one of officially supported installation methods?

I've used `snap`. I'll try this method: https://flight-manual.atom.io/getting-started/sections/installing-atom and let you know.

**Comment by szmarczak** [comment]
Snap just updated Atom to 1.28.1. It's fixed :heart:

**Comment by rsese** [comment]
Oh great glad to hear it! :+1:

I'd still recommend using one of the official installation methods but if the snap is working for you, that's fine too.  If you have future issues though, we'll ask you to confirm if you can reproduce with one of the documented install methods, so something to keep in mind 😄
