### ISSUE TITLE
System settings not working

### ISSUE THREAD

**Issue by jindradev** [atom/atom#17624]
### Description

Settings -> System -> {All checkboxes} 
a) checkboxes do not read user preferences from registry, they are "unchecked" by default
b) checkboxes only add functionality, unchecking them does not remove their functionality

**Expected behavior:** remove item from context menu on unchecking related checkbox

**Actual behavior:** item persists in context menu

**Reproduces how often:** 100%

### Versions

1.28.0 x64, Windows 10

### Additional Information

didn't test in safe mode, it just doesn't work and there is no issue to this quick fix
checkboxes are reset every time settings tab is open (even in the same app instance)

**Comment by the-j0k3r** [comment]
Cant duplicate this AT all/

![capture](https://user-images.githubusercontent.com/31389848/42386908-b31f2abe-8138-11e8-8116-c1a896f4fa10.PNG)

those settings are 100% followed.

```
> atom -v

Atom    : 1.28.1
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3

> apm -v

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.1
python 3.5.2
git 2.17.1.windows.2
visual studio
```

**Comment by rsese** [comment]
Do you see any errors in devtools console @jindradev?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools
