### ISSUE TITLE
No window opens with -d CLI flag on Ubuntu 18.04

### ISSUE THREAD

**Issue by kylebarron** [atom/atom#17632]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For a few versions now, using the `-d` flag to open Atom from the command line prevents any window from opening. I had thought that nothing at all was going on, but it appears that some processes are created with no windows.

![image](https://user-images.githubusercontent.com/15164633/42334364-194f3368-804b-11e8-903d-a0d4775869e7.png)

![image](https://user-images.githubusercontent.com/15164633/42334388-243441ce-804b-11e8-8fa0-a255fdd36159.png)
(no window opened)

It started some processes however:
```
> ps ax | grep atom
17394 pts/7    S      0:00 /bin/bash /usr/bin/atom . -d
17396 pts/7    Sl     0:00 /usr/share/atom/atom --executed-from=/home/kyle/github/atom --pid=17383 -d .
17419 pts/7    S      0:00 /usr/share/atom/atom --type=zygote --no-sandbox
17447 pts/7    Sl     0:00 /usr/share/atom/atom --type=gpu-process --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=9,27,84 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --disable-accelerated-video-decode --gpu-vendor-id=0x10de --gpu-device-id=0x1402 --gpu-driver-vendor=Nvidia --gpu-driver-version=396.24.02 --gpu-driver-date --service-request-channel-token=827F123A59F74892C28F3CD4FF75B73E
18510 pts/7    S+     0:00 grep --color=auto atom
```

`atom . -d --safe` doesn't open a window either, but the names of the processes created are different:
```
> ps ax | grep atom
20231 pts/7    S      0:00 /bin/bash /usr/bin/atom . -d --safe
20233 pts/7    Sl     0:00 /usr/share/atom/atom --executed-from=/home/kyle/github/atom --pid=20220 -d --safe .
20256 pts/7    S      0:00 /usr/share/atom/atom --type=zygote --no-sandbox
21827 pts/7    S+     0:00 grep --color=auto atom
```

### Steps to Reproduce

`atom . -d`.

**Expected behavior:** A window with dev mode opens.

**Actual behavior:** No window opens.

**Reproduces how often:** 100%.

### Versions

```
> atom --version
Atom    : 1.28.0
Electron: 2.0.3
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

System information (Ubuntu 18.04):
```
> uname --all
Linux desktop 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Additional Information

I installed from the `.deb` files distributed on Atom.io.

**Comment by rsese** [comment]
Thanks for the report!  I had 1.27.1 installed on an Ubuntu 18.04 VM and `atom -d` worked ok there and I then installed the latest 1.28.1 release with the .deb and that also worked ok for me.

If you start Atom in the foreground, do you see any error messages in the terminal?

```
atom -d --foreground
```

**Comment by kylebarron** [comment]
![image](https://user-images.githubusercontent.com/15164633/42339374-cb06d2aa-805a-11e8-8f22-5058bad7f3c0.png)

**Comment by kylebarron** [comment]
I'm not sure what it's looking for in `~/github/atom/`. I tried removing my `~/.atom` configuration folder, in case I had corrupted some file there, but that gave the same result.

**Comment by 50Wliu** [comment]
Does `~/github/atom` exist?  Launching Atom with the `-d` flag attempts to launch it in development mode, which loads Atom source files at `~/github/atom` by default.

**Comment by kylebarron** [comment]
Yes, that exists. I generally put all my Github projects in `~/github` and the Atom packages I work on at `~/github/atom`. 

I had no idea that it would try to read everything in `~/github/atom/`. Is it possible to turn this behavior off, or do I need to rename that folder?

It does open correctly when I change the location of `~/github/atom/`

**Comment by 50Wliu** [comment]
Is there a reason you are trying to launch Atom in development mode?

**Comment by kylebarron** [comment]
For what is I assume the intended reason: to make it easier to develop packages while still having a stable version in regular mode to do work with.

**Comment by kylebarron** [comment]
I renamed to `atom-dev` and it works fine now.
