### ISSUE TITLE
Fresh atom install crashes on load: Ubuntu in Windows WSL

### ISSUE THREAD

**Issue by abalter** [atom/atom#17635]
This is a proper and updated version of #17625

**NOTE:** I believe this is actually a problem with Electron on my system. I get the same error for any Electron app. See: https://github.com/electron/electron/issues/13566

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
After installing atom by any means, including the instructions [here](https://flight-manual.atom.io/getting-started/sections/installing-atom/) I get the following error:

>Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.

### Steps to Reproduce
1. Install Atom
2. Launch Atom

#### Example:

```
balter@spectre:~$ curl -sL https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
OK
balter@spectre:~$ sudo apt update
Get:1 http://archive.canonical.com/ubuntu xenial InRelease [11.5 kB]
Hit:2 http://ppa.launchpad.net/neovim-ppa/stable/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Hit:6 http://ppa.launchpad.net/teejee2008/ppa/ubuntu xenial InRelease
Get:7 http://archive.canonical.com/ubuntu xenial/partner amd64 Packages [3,128 B]
Hit:8 http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial InRelease
Get:9 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [518 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [804 kB]
Get:12 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [356 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [641 kB]
Get:14 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [133 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [258 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.4 kB]
Fetched 3,064 kB in 8s (379 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
19 packages can be upgraded. Run 'apt list --upgradable' to see them.
balter@spectre:~$ sudo apt install atom
Reading package lists... Done
Building dependency tree
Reading state information... Done
Suggested packages:
  gir1.2-gnomekeyring-1.0
The following NEW packages will be installed:
  atom
0 upgraded, 1 newly installed, 0 to remove and 19 not upgraded.
Need to get 86.7 MB of archives.
After this operation, 86.7 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/webupd8team/atom/ubuntu xenial/main amd64 atom amd64 1.26.1-1~webupd8~0 [86.7 MB]
Fetched 86.7 MB in 12min 42s (114 kB/s)
Selecting previously unselected package atom.
(Reading database ... 70052 files and directories currently installed.)
Preparing to unpack .../atom_1.26.1-1~webupd8~0_amd64.deb ...
Unpacking atom (1.26.1-1~webupd8~0) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.2) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up atom (1.26.1-1~webupd8~0) ...
balter@spectre:~$ atom
balter@spectre:~$ /usr/bin/atom: line 129: 12712 Aborted                 (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>
&1
Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.
```

**Expected behavior:** [What you expect to happen]
Atom to launch

**Actual behavior:** [What actually happens]
Receive error

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions

```
balter@spectre:~$ atom --version
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
balter@spectre:~$ apm --version
/usr/bin/apm: line 63: /opt/atom/resources/app/apm/bin/node.exe: No such file or directory
```

### Additional Information

```
balter@spectre:~$ uname -a
Linux spectre 4.4.0-17134-Microsoft #112-Microsoft Thu Jun 07 22:57:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
balter@spectre:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 50Wliu** [comment]
> NOTE: I believe this is actually a problem with Electron on my system. I get the same error for any Electron app.

Closing in favor of the linked Electron issue as this is not Atom-specific.

**Comment by PertuyF** [comment]
@50Wliu separately from the mutex error, there is a another atom-related problem.

The `apm` script does look for `node.exe` even in WSL, where the node binary is `node`.
I located the origin of this bug [there](https://github.com/atom/apm/commit/10525a7bd6b3680d961f7db04e1eb8d7211afb63#diff-e1b4fee1fe87e7cc5fb1c7d28453e624), where the following section causes the problem.
```bash
elif [[ $(uname -r) == *-Microsoft ]]; then
  nodeBin="node.exe"
```

Under WSL Ubuntu, `uname` returns `Linux`, so why not keeping only this info to identify the OS?
