### ISSUE TITLE
Atom Cannot open local file and cannot open files from remote FTP

### ISSUE THREAD

**Issue by FelixFanPenn** [atom/atom#17641]
Hi all,

I was using Atom and remote FTP package to access some files on a remote Linux server. I have a .ftpconfig file to store all information about this remote connection. However, at some point, I cannot open files from remote Linux and surprisingly I cannot open local files neither.

I tried right click and open with Atom, and I also tried double click. I tried click File and open files option too. None of them works. I tried this command: atom --clear-window-state. But it does not solve the problem. Anyone can shed any light about this issue?

**Comment by rsese** [comment]
Thanks for reaching out!

For help using a community package, you can ask on Atom's official message board:

https://discuss.atom.io

There are a bunch of helpful community members that should be willing to point you in the right direction.
