### ISSUE TITLE
Atom 1.28.1 random crash while idle.

### ISSUE THREAD

**Issue by the-j0k3r** [atom/atom#17642]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step] open atom
2. [Second Step] do some operations with github
3. [and so on...] left atom running comeback a while later and its crashed,

![capture](https://user-images.githubusercontent.com/31389848/42386512-a393991e-8137-11e8-804e-72c7390f6f50.PNG)

**Expected behavior:** [What you expect to happen]

no crash

**Actual behavior:** [What actually happens]

crash

**Reproduces how often:** [What percentage of the time does it reproduce?]

so far twice 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Windows 10 pro 1803

> atom -v

Atom    : 1.28.1
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3

> apm -v

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.1
python 3.5.2
git 2.17.1.windows.2
visual studio
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

I have related comments in https://github.com/atom/atom/issues/17253#issuecomment-400569961

Here is one crashlog https://gist.github.com/the-j0k3r/90ab81d07ca5dc070859bf46c7562068

**Comment by rsese** [comment]
Thanks again for opening a new issue for this @the-j0k3r :bow:  I see you've been commenting on some of the other crash issues so I'm sure you've checked some of these things but just so we have it all in one place for your issue:

* Have you seen the crashes before 1.28.1 or just starting with 1.28.1?
* Do you have a `.git\` directory in your home directory?
* Are you using a network proxy?

**Comment by the-j0k3r** [comment]
I cant reproduce any static or variable time lapse between crashes, but as it was said before all issues are around idle, crash, high random cpu usage, or what I get the most is hangs. Hanging is 9 times out of 10 along with high cpu usage and 1 random crash.

**Comment by the-j0k3r** [comment]
What more information would you actually need?

**Comment by cisen** [comment]
My atom verision of 1.28.1 have the same problem on mac.

**Comment by radicalviva** [comment]
@the-j0k3r 
I have the same probelm on Mac.
My mac version is 10.13.5 High Sierra

**Comment by cisen** [comment]
@the-j0k3r 
atom-beautify 0.32.2
atom-ternjs 0.18.3
atom-typescript 12.5.3
busy-signal 1.4.3
emmet 2.4.3
emmet-jsx-css-modules 1.0.0
file-icons 2.1.21
git-plus 7.10.2
highlight-selected 0.13.1
intentions 1.1.5
language-babel 2.85.0
language-graphql 0.10.1
language-javascript-jsx 0.3.7
language-kotlin 0.5.0
linter 2.2.0
linter-ui-default 1.7.1
minimap 4.29.8
minimap-find-and-replace 4.5.2
minimap-git-diff 4.3.1
minimap-highlight-selected 4.6.1
react 0.18.0
nuclide 0.317.0
nuclide-format-js 0.0.46

**Comment by the-j0k3r** [comment]
@radicalviva 

More information also would be appreciated by the devs trying to find a commonality or looking to fix.

Im not on mac but clearly this affects multi-platform, still without adequate information this wont get anywhere.

**Comment by rsese** [comment]
> What more information would you actually need?

For the crash specific to 1.28.1 that you've reported in this issue, ideally we could get to specific reproduction steps but your case has been hard to pin down, and you can get it to hang/crash with Atom just idling.

Based on what you've described here and in other issues, we know you've seen high CPU and hanging issues previous to 1.28 yeah?  If it only started with 1.28, then we could also point to the Electron upgrade from 1.27 to 1.28 as another possible issue but it sounds like that's not the case (the 1.28 specific crashes could still be related).

We've also ruled out some of the more typical causes of high CPU that I remember seeing (e.g. community packages, Git directory in the home directory, something in your init script).   For a couple of people recently the cause of the hanging they were seeing was specific to the type of files they were working on (e.g. they were working on large text files and spell-check was the issue) but I don't believe that's the type of project you're working on.   I also remember coming across a few random issues where people found that disabling a specific core package cleared up Atom slowness they were seeing.

But yeah, if anyone else has ideas about possible things to check, that would be great to hear.

@cisen @radicalviva - are you seeing the exact same issue as described in the issue body or is Atom crashing on start for you?  Are either of you using Shadowsocks proxy?  That's the most common issue we've found with 1.28 and macOS.

**Comment by cisen** [comment]
Wowww, @rsese, you are right.I reappear this bug when i using Shadowsocks. Thank you for your reply。

**Comment by radicalviva** [comment]
@rsese @cisen 
Me too, I am using Shadowsocks, so I have to close it if I want to use Atom ?

**Comment by the-j0k3r** [comment]
> If it only started with 1.28, then we could also point to the Electron upgrade from 1.27 to 1.28 as another possible issue but it sounds like that's not the case (the 1.28 specific crashes could still be related).

No started before see https://github.com/atom/atom/issues/17308 I was running 1.26.1 when I posted that.
I can trace hangs on idle and high CPU usage to since 1.26.0.
Also the first crash was after doing a large operation like doing a diff view of staged/unstaged chnages, where there were more than 8K lines, but it hung perpetually most of the time when trying to reproduce, had to kill process after some time (usually when Atom posts a popup asking if you want to close or wait its hung perpetually).

Hanging/high CPU sage was consistent since then crashing was sometimes.

What I do is 100% of the time.

1. Open Atom (pre 1.28)
2. The git project that opens with that 1st instance is rarely the one I need, so I open another folder that contains a git project I need. (hence why I have 2 instances of Atom running 9 out of 10 times)
3. Do some work on the 2nd instance and view diffs, usually around viewing diffs (unstaged/staged changes) things start to go weird. (hangs along high CPU usage)  happens 4 out of 10 times, crash 1 times.
4. Those 5 times which didnt crash or hang while viewing diffs,  I commit changes, go for a sh**.a shave and second cup of coffee.
5. Come back and the 2nd instance of Atom in those 5 times it didnt hang/crash in previous step) has now Hung perpetually along with high CPU usage.
6. Kill that hung 2nd Atom instance, the 1st Instance where I did nothing since Atom was opened is fine until I kill the 2nd instance which hung).
7. If I leave that first instance idling (focused instance) will start to randomly go into high CPU usage and hangs I never did any work on that 1st instance, its usually just used to open another project I need.

Since 1.28.1 it decided to randomly crash while idling on that running 2nd Atom instance aka step 5.

No shadowsocks here :)

**Comment by rsese** [comment]
> What I do is 100% of the time.

Would it be correct to say that the hanging/high CPU usage always involves having a git repository open in Atom?

@cisen @radicalviva - thanks for confirming.  The issue for that is https://github.com/atom/atom/issues/17557 and if you haven't seen it yet, it's [been fixed](https://github.com/atom/atom/issues/17557#issuecomment-405249057) in 1.28.2 and 1.29.0-beta2.

**Comment by radicalviva** [comment]
@rsese 
Thank you very much.
I have downlowned atom@1.28.2 and It can run successfully

**Comment by the-j0k3r** [comment]
> Would it be correct to say that the hanging/high CPU usage always involves having a git repository open in Atom?

In order to fully agree with this statement, requires equal testing out the scenario where Atom is used as a simple text editor, Problem is when I do use Atom like that, I dont leave it idling, I do my thing and close the instance, so I need to let it idle in that instance and see.

So let me test that out before committing to that. :)

I can say with certainty that scrolling though a long file no matter if git repository open or not causes really high CPU usage.

**Comment by the-j0k3r** [comment]
@rsese I preformed some regular tasks without involving git and were unable to reproduce the high cpu usage/hangs on idle.

But the scrolling on a large file still makes the cpu scream somewhat.

**Comment by the-j0k3r** [comment]
Crash on idle with 1,28.2 after some high CPU usage.

**Comment by Arcanemagus** [comment]
* Do you notice memory usage continuously increasing before a crash?
* Once it enters the "high CPU usage" state, does it ever leave it?
  * When it is in that state is Atom still usable (but slow)?
  * In Task Manager what process is using the CPU? `atom.exe`? `git.exe`?
* Does it still happen if you disable the `github` package?

**Comment by the-j0k3r** [comment]
> Do you notice memory usage continuously increasing before a crash?

No, memory usage doesnt seem to be a factor.
See below gif.

> Once it enters the "high CPU usage" state, does it ever leave it?

Yes, it fluctuates on and off but with when it crashes it on the High CPU usage curve.
Its more or less this, CPU goes higher than that in some occasions 40% around there highest Ive seen, then down to almost nothing or nothing.

![idlecpu](https://user-images.githubusercontent.com/31389848/42388240-ccc6d832-813c-11e8-9f2e-a2c116fb9732.gif)

Re Memory usage: what do you think? Is that normal?

> When it is in that state is Atom still usable (but slow)?

No cant do jack, it hangs when it doesnt crash.

> In Task Manager what process is using the CPU? atom.exe? git.exe?

Atom.exe 100% of the time.

>Does it still happen if you disable the github package?

It has nothing to do with GH package being ON/OFF afaict, Ive tested using atom in non git operations (not opening git projects at all) and nothing seems to happen and GH package was enabled on these tests (see two commnets above yours), ,Things start to go awry not when I open a git project, but after Ive done what I need to do, go away for a cup of coffee or whatever I come back and you can go though https://github.com/atom/atom/issues/17642#issuecomment-403729687

**Comment by the-j0k3r** [comment]
@Arcanemagus

Here it is again GH package was disabled

Cptures nicely idle OK and after it goes nuts

![highcpuusage](https://user-images.githubusercontent.com/31389848/42993270-da3e19fa-8c02-11e8-9ebc-6506a3339c08.gif)

At this moment no crash but seems like Atom has hang, interacting with atom does nothing doesnt respond.

**Comment by the-j0k3r** [comment]
@Arcanemagus again hung with only one instance of Atom running, GH package disabled always and the external terminal disabled after doing the git stuff (I need some way to do the git work and GH package is not essential to this) and going away come back and that was it.

Its hung, this time memory usage isnt nuts, but I cant say I see any correlation between a specific memory usage number and a specific CPU usage percentage before I experience hangs or crashes, only its on the higher curve not the less.

I also cant see any correlation between how many atom instances I have running at same time, see https://github.com/atom/atom/issues/17642#issuecomment-403729687 for what is what there.

Can you understand that?

![highcpuusage-hang](https://user-images.githubusercontent.com/31389848/42996466-921d7676-8c0b-11e8-9dda-22dfe19c3e37.gif)

**Comment by Arcanemagus** [comment]
I've seen similar issues with directory "loops" and things like the symbol cache increasing indefinitely as it kept scanning one more level deeper into the loop. Another potential case I've seen is a bug in the language parsing particular files. Just trying to narrow things down as to what is going on 😉.

If you enable the "Command Line" column in Task Manager you can get a _bit_ more detail as to what each process is, unfortunately often the problematic ones are the "anonymous" ones:
![image](https://user-images.githubusercontent.com/427137/43023985-9c0542e8-8c21-11e8-9a3a-867b784fae02.png)

If none of the culprit processes stand out as identifiable to you, the next thing that I would try is taking a memory heap snapshot and seeing what is eating all the RAM, you can find basic instructions [here](https://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance), however note that it looks like this now for memory:
![image](https://user-images.githubusercontent.com/427137/43024115-0c0c75e8-8c22-11e8-8ecd-49c944da8483.png)

Probably the best bet to track that down would be the "Record allocation timeline" option when you see it _starting_ to go bad. The full profiles over in the Performance tab can also be helpful, but they only have an overview of the memory allocations so you can't get to the actual data there.

**Comment by the-j0k3r** [comment]
@Arcanemagus 

The only problems so far with that is once things start going bad, clicking or performing any actions is that I find to be frozen out as it hangs the whole lot, I brought the devtools up in anticipation of these but nothing was happening when trying to initiate those captures.

Only way out force close after few attempts

Then if I started capturing before there's no way to stop the capture and force closing this yielded nothing of value.

Ill keep trying to catch some instance that I can successfully try to grab that extra information but so far its frustration avenue in the corner of bang head on wall road.

**Comment by mefsantos** [comment]
I'm not sure if its the same issue here however, in my workstation (which i leave plugged - but locked -  throughout the night), whenever i'm back to work i have following notifications:

![atom_crash](https://user-images.githubusercontent.com/5880985/48771250-cb13a500-ecb8-11e8-9f0e-3c3d1fb03a31.png). 
As for the free memory. I ran `free -m` and got the following output: 
```
              total        used        free      shared  buff/cache   available
Mem:          15986       10229        2874         110        2882        5169
Swap:         16324        2530       13794
```
**OS:** Ubuntu 16.04 LTS
**Atom:** 1.29.0
