### ISSUE TITLE
Use pnpm to manage packages' dependencies

### ISSUE THREAD

**Issue by KSXGitHub** [atom/atom#17655]
## Summary

By using symlinks/hardlinks, [pnpm](https://pnpm.js.org/) saves disk usage (My package directory is 1.3GB already) and network bandwidth. It's also faster than both yarn and npm in my experience.

## Motivation

* It minimizes disk usage by sharing packages via symlinks/hardlinks.
* It minimizes network bandwidth by reusing downloaded dependencies.
* It is faster than yarn/npm.

**Comment by rsese** [comment]
Thanks for the suggestion!

This probably belongs in https://github.com/atom/apm/ (e.g. a similar issue was brought up there before with [yarn and npm](https://github.com/atom/apm/issues/658)) but for this one, I'll go ahead and mention pnpm to the team (thanks for the link and list of benefits) and if it's something they want to look into further, we'll reopen in https://github.com/atom/apm.
