### ISSUE TITLE
Python highlighting is broken for some triple quote docstrings

### ISSUE THREAD

**Issue by irmatov** [atom/atom#17662]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Python highlighting is a bit broken with regard to triple quotes, see below.

### Steps to Reproduce

1. Open a new file with Ctrl+N
2. Set to Python grammar using a button in bottom right.
3. Enter following text:

code:

    class A:
        @classmethod
        def first(cls, iterable):
            """
            'REPLACE'
            """
            pass
    
        def other(self):
            pass

**Expected behavior:**

I expect the text between triple quotes (including them) to be colored as strings. Text that follows second triple quote should be highlighted as code.

**Actual behavior:**

All text following second triple quote till the end of file will be highlighted as a string.

**Reproduces how often:**

Everytime.

### Versions

Atom    : 1.28.1
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3
OS: Ubuntu 18.04

**Comment by maxbrunsfeld** [comment]
This code highlights properly with Atom's experimental new [Tree-sitter parsing system](https://github.com/atom/atom/pull/16299). To enable it, check `Use Tree-sitter Parsers` in the "Core" section of the settings view.

**Comment by maxbrunsfeld** [comment]
Also, this issue is specifically about this built-in Atom package: https://github.com/atom/language-python. Could you copy what you've written and reopen it on that repo?

**Comment by irmatov** [comment]
Reopened as https://github.com/atom/language-python/issues/264
