### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.5.244.180:8080

### ISSUE THREAD

**Issue by Devendra-Vidhale** [atom/atom#17676]
[Enter steps to reproduce:]

1. Atom editor was launched using Start Menu
2. It had one file open from previous editing session. The file exists on local disk.
3. Atom was left idle for a few minutes and then it showed up this bug.

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.5.244.180:8080

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, cause=connect ETIMEDOUT 10.5.244.180:8080
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
language-abaqus 0.2.0 
```

**Comment by rsese** [comment]
Thanks for the report - are you using a network proxy?  Also, did you see this error just the one time?  If so, it seems like it could be a temporary network issue.

**Comment by CRCinAU** [comment]
I see similar all the time using Fedora 28 and a http_proxy.

My environment shows:
```
declare -x http_proxy="http://192.168.1.1:8000"
declare -x https_proxy="http://192.168.1.1:8000"
```

Yet most of the network functions in atom don't work. The list of 'Featured Packages' loads, but you can't install any of them. The search for packages fails with: "connect ETIMEDOUT 52.72.251.164:443"

The IP changes each time I do a search, but it always times out.

**Comment by Devendra-Vidhale** [comment]
Yes, I am using a network proxy. This error recurs on every atom session, so its not a one time error.
