### ISSUE TITLE
[Bootstrap] Error: Module version mismatch. Expected 48, got 64.

### ISSUE THREAD

**Issue by qwelias** [atom/atom#17688]
### Description

Error: Module version mismatch. Expected 48, got 64.

### Steps to Reproduce

1. clone repo
2. `$ ./script/bootstrap`
3. `Error: Module version mismatch. Expected 48, got 64.`

**Expected behavior:**
Command exited with code 0

**Actual behavior:** 
Error: Module version mismatch. Expected 48, got 64.

### Versions
```
▶ npm version
{ atom: '1.30.0-dev',
  npm: '6.2.0',
  ares: '1.14.0',
  cldr: '33.0',
  http_parser: '2.8.1',
  icu: '61.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.32.0',
  node: '10.6.0',
  openssl: '1.1.0h',
  tz: '2018c',
  unicode: '10.0',
  uv: '1.22.0',
  v8: '6.7.288.46-node.13',
  zlib: '1.2.11' }
```

### Additional Information

[npm-debug.log](https://gist.github.com/qwelias/882aa3312494cd59f31dce7db9346df5)

**Comment by rsese** [comment]
Have you tried a `script/clean` before trying bootstrap again?

**Comment by vcommero** [comment]
Experiencing this same issue on Arch Linux 4.17.6-1. Running script/clean and trying script/bootstrap again produces the same results.

**Comment by mstmustisnt** [comment]
This usually happens when you switch to other node version than you used when installing. 
`npm rebuild` usually fixes it.
