### ISSUE TITLE
The application consumes resources in the background as a working application?

### ISSUE THREAD

**Issue by Eskander88** [atom/atom#17689]
### Description
I minimized the application to the taskbar. And I don't use it. But I noticed that my computer resources are being consumed. And saw that Atom periodically rises in line as the process that consumes the most CPU. Sometimes application is be on even top place in rating.

### Expected behavior
Other IDE and text editors do not consume so many resources. Especially when they do not work or minimized to the taskbar panel. 

What processes do Atom in the background?  May be need optimize or What is might be going on? 

```
Atom    : 1.27.0-beta1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

OS: Windows 10 x64
```

**Comment by rsese** [comment]
Thanks for the report - it looks like the `Prerequisites` section of the issue template was removed, did you try [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) or any of the other [debugging steps](https://flight-manual.atom.io/hacking-atom/sections/debugging)?




> But I noticed that my computer resources are being consumed. And saw that Atom periodically rises in line as the process that consumes the most CPU. Sometimes application is be on even top place in rating.
