### ISSUE TITLE
Cannot Disable Or Remove Built-In Debugger

### ISSUE THREAD

**Issue by repertor** [atom/atom#17693]
I cannot find a package that adds the built-in debugger to Atom, so it is apparently part of its core. Therefore, it is impossible to disable or remove.

The reason I wish to remove it is that I have no use for it. The _real_ reason is that I'm _constantly_
accidentally clicking the blue dots when I wish to simply select the line by clicking the line number, which causes the debugger to open. The majority of my work is in HTML, CSS, PHP, and some JS, so the Debugger being always-present makes no sense.

### Steps to Reproduce

1. Click the line number
2. Miss and instead click blue dot
3. Sigh

### Versions

Atom    : 1.29.0-beta2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
macOS 10.13.6

**Comment by Aerijo** [comment]
If you are referring to dev tools, I don’t believe there is a way.

I’m not sure what you mean about the blue dots and line numbers though, could you please expand on what they are and if they are present in safe mode (open Atom with `atom --safe`)?

**Comment by repertor** [comment]
I don't know what to make of the fact that the blue dots do not appear in safe mode.
I'm not sure when they appeared, but I feel like it was in the last month or two. 

Here's the editor content that appears to the left of every line number:
<span data-line="19" data-bp-id="f2ae011d-474f-458b-8ecc-70d0fbf09115" class="debugger-breakpoint-icon debugger-breakpoint-icon-nonconditional" title="Breakpoint" style="height: 16px;"></span>

The dots only appear on hover. I've not been able to nail down which package causes them.

![screen shot 2018-07-15 at 7 19 14 pm](https://user-images.githubusercontent.com/5770553/42739356-02075192-8864-11e8-8493-92195579c11c.png)

**Comment by rsese** [comment]
Yep that's part of atom-ide-ui :+1:, glad you found it.

> I cannot find a package that adds the built-in debugger to Atom, so it is apparently part of its core. Therefore, it is impossible to disable or remove.

The `Prerequisites` section of the issue template would have been somewhat helpful here - running in safe mode would disable all community packages including the ide packages.

Going to go ahead and close since you found the atom-ide-ui setting to disable the debugger.
