### ISSUE TITLE
For some reason Attom IO bootstrap and build dont work 

### ISSUE THREAD

**Issue by BooRar** [atom/atom#17696]
> script/bootstrap

>Node:   v8.11.2
>Npm:    v5.6.0
>Python: v2.7.10
>Installing script dependencies
>npm ERR! Unexpected end of JSON input while parsing near '..."_hasShrinkwrap":fals'

>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\Jono\AppData\Roaming\npm-cache\_logs\2018-07-16T08_00_29_037Z-debug.log
>child_process.js:624
    throw err;
    ^

>Error: Command failed: npm.cmd --loglevel=error install
>npm ERR! Unexpected end of JSON input while parsing near '..."_hasShrinkwrap":fals'

>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\Jono\AppData\Roaming\npm-cache\_logs\2018-07-16T08_00_29_037Z-debug.log

>    at checkExecSyncError (child_process.js:601:13)
 >   at Object.execFileSync (child_process.js:621:13)
>    at module.exports (C:\eleclearn\atom\atom\script\lib\install-script-dependencies.js:9:16)
>    at Object.<anonymous> (C:\eleclearn\atom\atom\script\bootstrap:28:1)
>    at Module._compile (module.js:652:30)
 >   at Object.Module._extensions..js (module.js:663:10)
 >   at Module.load (module.js:565:32)
>    at tryModuleLoad (module.js:505:12)
>   at Function.Module._load (module.js:497:3)
>    at Function.Module.runMain (module.js:693:10)

**Comment by BooRar** [comment]
error log
[2018-07-16T08_00_29_037Z-debug.txt](https://github.com/atom/atom/files/2196935/2018-07-16T08_00_29_037Z-debug.txt)

**Comment by 50Wliu** [comment]
#17697.
