### ISSUE TITLE
Font rendering changes when typing

### ISSUE THREAD

**Issue by lloiser** [atom/atom#17718]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Under certain conditions (specific text and editor size) the text editor renders the font a bit different. It feels like the font is "washed out".

### Steps to Reproduce

Given a file "todo.md" (so language `GitHub Markdown` is active) with the following content:
```markdown
### aaaa a aaa aaaaa aaa aaaa aaaaa

* aaaaa aaaaa aa aa aaa aaaa aaa aaaaaa a aaaaaaa aaaaaaaaaaa aaaa aaa aaaaa aaaa aaaaa-aaaaaaaaaaaaaaaaaa_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  * aa aaaaa aaa aaa aaaaaa aaaaaaa aaaaaa aaa a aaaaaaa_
    * a aaaa aa aaaaaa aaa aaa aaaaaaaa aaaaaaaaa aaaa aaaaa'a aaaaa ✓
    * aaa aaaaaaaaaaa aaaaaaa aaaa aa aaaa aaaaa aaaaaaa aa aaaaaaaaaaa aaaaaaaaa a aaaaaaa aa aaa aaaaaa aa aaaaaa aaaaaXXX
  * aaa aaaaaaaaaaa aaaa aaa aaaaaaaa aaaaaaa aaaaa aaa aaaa aaa aaaaaaaaaaaa aaaa_ aa aaaaaa... (aaaaaaaaa aaaa aaaa aaaaaa aaaaaa)

### aaaa a aaaa aa aaaaa

* aaaaaaaa aaaa aaa aaaaa

### aaaaaaaaaaa

* a
```

My active text editor has the following size:
```js
// $0 = <atom-text-editor>
$0.getBoundingClientRect()
DOMRect = {
  bottom: 792
  height: 767
  left: 301
  right: 1105
  top: 25
  width: 804
  x: 301
  y: 25
}
```
There are 2 plugins installed, `linter-ui-default` (and `linter` obviously) and `atom-ide-ui` that enhance the text editors gutter (that affects the size of the text editor too):
* left: breakpoints from atom-ide-ui
* center: line number
* right: linter errors

both these plugins take up 10px each (so 20 in total) of the gutter.

Inside the text above you can find `XXX`. This is where you have to place the cursor. Before you start typing look at the first heading, because it will change. Now type any character. 2 things happen:
* the character stays on the same line, even though there is barely any place (subjective I know)
* the heading kind of gets "washed out"

I had this problem for a very long time, now I finally found a way to 100% reproduce this.
The workaround to get the normal font rendering back is to switch to another tab and then back again.
Interestingly after that the editor has scrolled a bit to the right and therefore "cuts" the first char of each line.

Here is a gif that summarizes all these problems. You probably have to open it see all the details.
![error_atom](https://user-images.githubusercontent.com/3003233/42998704-6288c2e8-8c1b-11e8-9b4c-2368b416c2a4.gif)

---

Sry that this is a bit "complicated" but I already prepared everything with my official atom release (1.28).
I was able to reproduce this using atom-beta `1.29.0-beta2` in safe mode too!

**Expected behavior:** normal font rendering

**Actual behavior:** the text is "washed out"

**Reproduces how often:** 100%

### Versions

```
$ atom -v
Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
$ apm -v
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.2
python 2.7.10
git 2.15.2
```
```
linter: 2.2.0
linter-ui-default: 1.7.1
atom-ide-ui: 0.13.0
```

**Comment by lee-dohm** [comment]
I wasn't able to reproduce this using Atom v1.30.0-nightly6 on Mac OS X 10.13.6. I managed to get my bounding rect for the editor to be:

```
{
  bottom: 922
  height: 882
  left: 301
  right: 1102
  top: 40
  width: 801
  x: 301
  y: 40
}
```

I figured the width was the most important part and got it as close as I could.

Which OS and version are you running? What font and font size do you have configured? This could be specific to the font and its metrics as well.

**Comment by lloiser** [comment]
It happens at least on macOS (high sierra) and win 10 (version 1803) using 1.28 and 1.29.0-beta2 (tested on macOS only)

To be more specific about the sizes: 

![image](https://user-images.githubusercontent.com/3003233/43045129-01fa2112-8db3-11e8-9790-cf9e2e6ffe70.png)

* `.scroll-view` has `width: 753px` (which seems to be the actual width of the editor lines excluding the gutter)
* font: Hack, 10px, 1.4 line-height
  It also happened for Menlo with the same font-size and line-height on macOS
