### ISSUE TITLE
Consider providing deltas for deb packages

### ISSUE THREAD

**Issue by AnwarShah** [atom/atom#17713]
## delta updates would be very useful

[`debdelta`](http://debdelta.debian.net/html/index.html) is a project that is created to create, patch deltas from old debian package to new. This is very useful when the bandwidth is limited. I personally created deltas from old atom .deb package and apply it.  
It works always and neatly creates the new deb files.

## Motivation: Smaller update size
Why are we doing this? What use cases does it support? What is the expected outcome?

There are still large number of users who rely on data-capped internet packages. And electron apps are always large in size. So, updating these packages is not always possible. Providing and promoting deltas for those users would be very good support. 

The expected outcome is these users updating atom more frequently and happily.

## Alternatives?

There is no alternative to this yet. The only way to update is downloading the full package.

## Additional context
To create a delta from atom_1.24.deb to atom_1.27.deb, one need a simple command 

    debdelta atom_1.24.0_amd64.deb atom_1.27.2_amd64.deb atom-delta

The it can be patched using this command

    debpatch -A  atom-delta atom_1.24.0_amd64.deb atom_1.27.0_amd64.deb

If old deb isn't available, user can use `/` instead of old deb package like this 

    debpatch -A  / atom_1.27.0_amd64.deb

I used the same command and the generated delta is around 46 MB where the newer full deb is 84 MB. That is almost 45% saving which is significant. I myself have seen some deltas as small as a few megabytes.

Note: There is also rpmdelta which can be useful for rpm based linux distributions too. And major rpm based distros (RHEL, CentOS, Fedora, OpenSUSE) already integrated it to their package managers.

**Comment by lee-dohm** [comment]
Thanks for the suggestion!

Unfortunately, we're not prepared to take on the added complexity that this would cause in our build process in the foreseeable future. We'll review again later if this changes.

Thanks again!
