### ISSUE TITLE
Menu bar and menus are aligned to the right when they aren't translated and language settings are RTL

### ISSUE THREAD

**Issue by Shallev** [atom/atom#17712]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Same as issue #15875: Menu aligned right-to-left in Windows with right-to-left layout 

On windows 10, when OS language is right to left (e.g Hebrew), the Atom menus are aligned to the right (i.e. File is at the right most side of the menu bar, Edit menu is to its left and so on). This is wrong behavior as English menus should be aligned to the left. If the menus where translated to Hebrew (please don't) it was OK for them to be aligned right to left.

### Steps to Reproduce
1. Set OS display language as Hebrew
2. Open atom editor

**Expected behavior:** [What you expect to happen]
In the picture below you can see that notepad++ menus (on same OS) are left aligned as they should be because they are in English. I expect Atom to behave the same as notepad++.
![image](https://user-images.githubusercontent.com/41389073/42900819-895f6416-8ad2-11e8-8e89-11b2e9ad22e0.png)

**Actual behavior:** [What actually happens]
In the picture below, you can see that the msPaint menu bar is in Hebrew and aligned right to left - this is OK because Hebrew is right to left language. The atom menu bar and menu items are aligned right to left as well but they are in English and so they should have been aligned left to right (File on the left most corner)
![image](https://user-images.githubusercontent.com/41389073/42900592-fc152e2e-8ad1-11e8-943b-fae1dfe04e78.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.2
python 3.6.4
git
visual studio 2015
Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for opening a new issue and filling out the issue template @Shallev 👍 I'll ask the team to take a look.

x-ref: https://github.com/electron/electron/issues/11912 and https://github.com/Microsoft/vscode/issues/20377#issuecomment-279932691.

**Comment by lee-dohm** [comment]
Thanks for the feedback.

Unfortunately, this isn't something that we're going to be able to take on in the foreseeable future. However, we would be interested in reviewing a well-written PR for this. See the Electron issue that @rsese linked above for possibly the easiest solution.

Thanks again :bow:
