### ISSUE TITLE
Code auto completion in a Python module at commented lines

### ISSUE THREAD

**Issue by Pavche** [atom/atom#17719]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom performs code auto completion in Python modules at commented lines, this way changing the words in comments unexpectedly.

### Steps to Reproduce

1. Open a Python module.
2. Start writing a commented line, starting with hash sign "#".
3. Finish your sentence with dot.

**Expected behavior:**
Code auto completion is disabled, I can write sentences, put dots without changing my words in the comment.

**Actual behavior:**
Code auto completion is enabled at commented lines and it changes my words.

**Reproduces how often:**
100%

### Versions
Red Hat Enterprise Linux Workstation release 7.4 (Maipo)
Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information
Running Atom in safe mode:
- The issue persists

Clearing the saved state of Atom:
- The issue persists

Reset Atom configuration to factory defaults:
- The issue persists

Check for linked packages
/home/pgeorgie/.atom/dev/packages (0)
└── (no links)
/home/pgeorgie/.atom/packages (0)
└── (no links)

Check for incompatible packages:
- None

Check Atom and package settings:
- Done

**Comment by Aerijo** [comment]
Have you tried adding the comment scope to the blacklist in 
Settings -> Packages -> (search) autocomplete-plus -> Scope Blacklist ?

Additionally, if completion on <kbd>enter</kbd> is an issue (beyond just in comments), I recommend switching to "tab only". While it feels weird at first (I mae the swap), it becomes just as natural when you get used to it. And once you do, things like accidental completions are a non-issue.

**Comment by Pavche** [comment]
Now, I have tried Settings -> Packages -> (search) autocomplete-plus -> Scope Blacklist.
This solves the issue.
Thanks.
