### ISSUE TITLE
How to change installed package name back from Atom Dev to Atom

### ISSUE THREAD

**Issue by adamreisnz** [atom/atom#17726]
Hi, from 1.30 or so, the dev version of Atom packages and installs itself as "Atom Dev" instead of "Atom". This has messed up my github desktop integration and OS configuration.

How or where can I configure this to revert the build script back to using "Atom" as the package? (OS X)

**Comment by adamreisnz** [comment]
Nevermind think I found it in atom.sh as `ATOM_EXECUTABLE_NAME="Atom"`

**Comment by daviwil** [comment]
Hey Adam, can you tell me more about how it broke your GitHub Desktop configuration?

Also, is there a particular reason why you're using Atom Dev builds?  If you're interested in keeping up with the latest Atom changes on `master`, you can try out our Atom Nightly releases: https://github.com/atom/atom-nightly-releases/releases.  Installing the latest macOS build there will keep you up to date.

**Comment by adamreisnz** [comment]
I've tried using the nightlies now and removed Atom Dev, but now Github Desktop can no longer find Atom:

![image](https://user-images.githubusercontent.com/490562/43246792-e513f79c-9106-11e8-9ced-1e178aebfcfa.png)

Any script I can run to fix this?
