### ISSUE TITLE
Cannot run tests when TextEditor.insertText is called

### ISSUE THREAD

**Issue by ldez** [atom/atom#17729]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Due to:
- https://github.com/atom/text-buffer/pull/295
- https://github.com/atom/atom/issues/16956
- https://github.com/atom/atom/pull/17089

It's not possible to call [TextEditor.insertText](https://atom.io/docs/api/v1.25.0/TextEditor#instance-insertText) in tests.

```
    Error: Deprecated function(s) TextBuffer.setTextInRange) were called.
      TextBuffer.setTextInRange is deprecated. The `undo` option is deprecated. Call groupLastChanges() on the TextBuffer afterward instead.
      --------------------------------------------------------------------------------------------------------------------------------------
      TextBuffer.setTextInRange -- /home/travis/atom/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:655:16
      Selection.insertText -- /home/travis/atom/usr/share/atom/resources/app.asar/src/selection.js:491:47
      result.mutateSelectedText.selection -- /home/travis/atom/usr/share/atom/resources/app.asar/src/text-editor.js:1377:31
      getSelectionsOrderedByBufferPosition.map -- /home/travis/atom/usr/share/atom/resources/app.asar/src/text-editor.js:1425:86
      Array.map -- null:null:null
      transact -- /home/travis/atom/usr/share/atom/resources/app.asar/src/text-editor.js:1425:60
```

https://github.com/atom/atom/blob/107ec432e57839e4de12eb5d0034a96c750bf741/src/selection.js#L491

### Steps to Reproduce

1. create a test
2. use [TextEditor.insertText](https://atom.io/docs/api/v1.25.0/TextEditor#instance-insertText)

**Expected behavior:** [What you expect to happen]

Be able to run tests when using [TextEditor.insertText](https://atom.io/docs/api/v1.25.0/TextEditor#instance-insertText)

**Actual behavior:** [What actually happens]

Tests are failing due to use of the deprecated option `undo`

**Reproduces how often:** [What percentage of the time does it reproduce?]

every time.

### Versions

Since 1.25 on Linux, MacOS and Windows.
Currently on 1.28.2

### Additional information

- https://travis-ci.org/asciidoctor/atom-asciidoc-image-helper/jobs/407027295
- https://ci.appveyor.com/project/asciidoctor/atom-asciidoc-image-helper/build/37/job/f090ftcw2l0ph2f2

**Comment by lee-dohm** [comment]
Check the following:

https://github.com/atom/atom/blob/master/src/selection.js#L491
