### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by schigum** [atom/atom#17737]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Whenever I press the Windows/Meta key while having Atom focussed, I get an error with the stack trace which is attached below.
This started only today, have never seen it before.

### Steps to Reproduce

1. Focus Atom
2. Press Windows-Key

**Expected behavior:**
Nothing

**Actual behavior:**
Error message

**Reproduces how often:**
Works all the time

### Versions
Atom    : 1.26.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

Ubuntu 18.04, Linux 4.15.0-24-generic
KDE, Plasmashell 5.12.6

### Additional Information
I have installed updates today, but Atom was not updated for what I can tell.
Was reported before in Issue #16345

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of null

```
At /opt/atom/resources/app/node_modules/atom-keymap/lib/helpers.js:266

TypeError: Cannot read property 'indexOf' of null
    at exports.keystrokeForKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/helpers.js:266:115)
    at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:467:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:347:30)
    at WindowEventHandler.handleDocumentKeyEvent (/opt/atom/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report!

> Atom : 1.26.1
...
> I have installed updates today, but Atom was not updated for what I can tell.

The latest stable release version of Atom is 1.28.2 - can you confirm that you're using one of the supported installation methods (i.e. the .deb from https://atom.io or the official package repositories)?

https://flight-manual.atom.io/getting-started/sections/installing-atom/

**Comment by aachman22** [comment]
I have the same problem. I am using atom 1.28.2. I installed it using the .deb file from https://atom.io
OS - Kubuntu 18.04

**Comment by schigum** [comment]
After an upgrade this morning the issue disappeared. The packages updated were:
tlp-rdw:amd64 (1.1-2, 1.1-2ubuntu1),
google-chrome-stable:amd64 (67.0.3396.99-1, 68.0.3440.75-1),
console-setup-linux:amd64 (1.178ubuntu2.2, 1.178ubuntu2.3),
console-setup:amd64 (1.178ubuntu2.2, 1.178ubuntu2.3),
tlp:amd64 (1.1-2, 1.1-2ubuntu1),
keyboard-configuration:amd64 (1.178ubuntu2.2, 1.178ubuntu2.3)

Hope this might also help aachman22.
From my side the issue can be closed, as it seems it wasn't atom's fault.

Cheers

**Comment by aachman22** [comment]
After upgrading my packages, the issue disappeared for me as well. Certainly looks like some other package was interfering with Atom. This issue can be closed from my side too.

Cheers
