### ISSUE TITLE
Impossible to move something out of the side panels

### ISSUE THREAD

**Issue by nil** [atom/atom#17745]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![captura 24](https://user-images.githubusercontent.com/13088397/43212533-795340a8-9034-11e8-8e8b-9f2be87aa45a.jpg)

For some reason I don't know, the git panel has been moved to the left panel, where I also have the tree view. There is no way to move it out and I can't re-install the package as it comes by default on atom.

### Steps to Reproduce

I don't know how it got there.

**Expected behavior:** An way to move it out of here.

**Actual behavior:** I can't take it out of the left panel.

**Reproduces how often:** Always, there is no way to move it.

### Versions

Atom 1.28.2
macOS 10.14 beta

**Comment by rsese** [comment]
Hmmm, not sure why there's no tab bar that says "Git", you would be able to drag it over back to the right by clicking and dragging that tab bar.  I think that screenshot isn't in safe mode - if you run in safe mode is the "Git" tab bar there?  Or do you have any CSS hiding it, maybe in your [styles file](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks)?

**Comment by nil** [comment]
Yes, I was hiding the tab bar from the left panel. Removing the CSS, I was able to drag the panel to the right. Thanks 😃
