### ISSUE TITLE
make: *** [Release/obj.target/threads_a_gogo/src/threads_a_gogo.o] Error 1

### ISSUE THREAD

**Issue by master-ning** [atom/atom#17747]
i got a problen with sudo npm install threads_a_gogo ,i try many times ,but it does not work ,please help me,thanks
error is here:
make: *** [Release/obj.target/threads_a_gogo/src/threads_a_gogo.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "-v" "rebuild"
gyp ERR! cwd /private/var/root/node_modules/threads_a_gogo
gyp ERR! node -v v10.7.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! threads_a_gogo@0.1.13 install: `node-gyp -v rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the threads_a_gogo@0.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-07-26T07_13_26_298Z-debug.log

i do not know how to fix it out

**Comment by master-ning** [comment]
i need the answer,please help me ,thanks

**Comment by rsese** [comment]
Thanks for reaching out - 

> i got a problen with sudo npm install threads_a_gogo

This doesn't seem related to Atom?  Going to go ahead and close, maybe https://github.com/xk/node-threads-a-gogo is a better place to find help.

**Comment by master-ning** [comment]
yes,i did this,but it did not work...i do not know how to go on

**Comment by rsese** [comment]
Can you clarify how this is related to Atom?  Are you using a particular community package?
