### ISSUE TITLE
Show scrollbar when resting two fingers on the trackpad under macOS

### ISSUE THREAD

**Issue by sonicdoe** [atom/atom#17755]
## Summary

Show the scrollbar when resting two fingers on the trackpad under macOS.

## Motivation

This allows you to get a quick feel for where you are in a document without actually having to scroll. This is also standard macOS behavior.

## Additional context

You can try this in Safari or TextEdit, for example. To take a look at the scrollbar, you don’t actually have to scroll but just rest two fingers (as if you were about to scroll) on the trackpad.

**Comment by rsese** [comment]
Thanks for the suggestion @sonicdoe!  Though I can see how this could be useful, I don't think this is something the team would prioritize or have time to work on so I'm going to close for now but if that should change we'll reopen.
