### ISSUE TITLE
low resolution taskbar icon on windows binary

### ISSUE THREAD

**Issue by omarahmed-omar** [atom/atom#17757]
### Description

After a fresh atom installation on a windows machine the basic icon on desktop or the launcher looks fine but after launching the software the icon that appears on the bottom taskbar is really low in resolution. I mean its really ugly to look at. It feels like my screen ate a huge circle of pixels.

Note:This screenshot is a bit blurred by my snipping tool. the real icon looks more pixy.
![capture](https://user-images.githubusercontent.com/30370919/43364414-88fc94b4-933b-11e8-9d34-4e84eb8f26e7.PNG)

### Steps to Reproduce

1. Launch atom on a windows machine
2. Move you eyes to the bottom of the screen on the taskbar where atom in shown
3. Feel how bad it looks!

**Expected behavior:** [Showing an icon on the taskbar proper for my screen resolution]

**Actual behavior:** [Shows a low resolution icon]

**Reproduces how often:** [It reproduces every time]

### Versions

1.28.2

### Additional Information

None

**Comment by rsese** [comment]
I checked on 1.28.2 and Windows 10 but I don't think I see the same thing but my eyes might not be sharp enough to tell, we'll see if anyone else can reproduce.

Did you see this just with the 1.28 releases and the icon was ok for you before?
