### ISSUE TITLE
always position context menus to avoid scrolling if possible

### ISSUE THREAD

**Issue by jedwards1211** [atom/atom#17756]
### Prerequisites

I didn't actually try reproducing this in safe mode.  I have no doubt it behaves just the same.
I checked for duplicate issues in GitHub.
I didn't check the FAQ or atom packages because I contend that the current behavior should not be the default behavior (indeed it is not the default behavior in most programs).

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Because context menus are always positioned with the top at the mouse cursor, if I right click near the bottom of the screen, a very short context menu comes up requiring a lot of scrolling to get to the menu item I want.

![image](https://user-images.githubusercontent.com/1448194/43360055-36ea5d54-9274-11e8-927c-6dd8da2a5938.png)

I consider this a usability bug, because it costs time to scroll to the menu item I want.  These little amounts of time add up.

Most programs I use will position the top of the context menu higher than the mouse cursor if necessary to show all of the menu items and avoid scrolling.

### Steps to Reproduce

1. Right click near the bottom of the screen

**Expected behavior:** [What you expect to happen]

The context menu comes up showing all menu items instead of the scroll indicator, meaning its top is much higher than the mouse cursor and its bottom is clamped to the bottom of the screen.

**Actual behavior:** [What actually happens]

A very short context menu needing a lot of scrolling comes up

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.28.2
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.28.2
python 2.7.11
git 2.15.2

OS: macOS High Sierra 10.13.5 (17F77)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
I can reproduce as described on macOS 10.12.6 and Atom 1.31.0-nightly0 but, I wonder if this is an Electron issue...I see the same behavior in VS Code for example.

I also noticed that if you position the window at the bottom of the screen and then try to right click at the bottom of the Atom window, the menu is positioned higher (VS Code does this as well).

**Comment by jedwards1211** [comment]
Probably is because of Electron, but that makes it an issue with Atom nonetheless...

**Comment by jedwards1211** [comment]
If it is an Electron issue, then can you help me file an appropriate issue in Electron's repo?

**Comment by rsese** [comment]
Let me double check with the team about this one first to see if folks agree it's an Electron issue.

**Comment by jedwards1211** [comment]
I see the ability to control the X/Y position of Electron popup menus in their API docs, but it doesn't seem like the ideal way to solve this problem...assuming Electron is in charge of the layout and sizing of the popup menu, it would know best how to position it to avoid scrolling.
