### ISSUE TITLE
Missing dependency to libonig-dev in build instructions

### ISSUE THREAD

**Issue by fsievers** [atom/atom#17758]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When building atom from source, I had the following errormessage, while installing apm dependencies:
```
module.js:549
    throw err;
    ^

Error: Cannot find module '/mnt/data/user/projects/extern/atom/script/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oniguruma@6.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

After installing the package `libonig-dev` (Debian/Ubuntu), the build error has gone away. But I was unable to find this library in the build instructions at https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux

This library should be added to the linux installation instructions.

### Steps to Reproduce

1. Checkout this repo
2. Execute `script/build --create-debian-package`
3. See the error happen, if `libonig-dev` isn't installed

**Expected behavior:** 
I expect the package `libonig-dev` to be in the list of package to install.

**Actual behavior:** 
The package is not listed in the install instructions and when building atom from source, the build fails.

**Reproduces how often:** 
100% if the library is missing.

### Versions

Since somewhere in the 1.28 development release.

**Comment by fsievers** [comment]
Oh, I'm sorry. I did a build of another software in another terminal, that succeded. The error message above still exists if I install the `libonig-dev` debian package.

**Comment by rsese** [comment]
Thanks for the report - I just built from bc8e70d7 on Ubuntu 16.04 and didn't have any issues.

What commit are you building from?

> Error: Cannot find module '/mnt/data/user/projects/extern/atom/script/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'

Hmmm, looks like that file doesn't exist on your machine.  Does `/mnt/data/user/projects/extern/atom/script/node_modules/npm/node_modules/` exist?

> Since somewhere in the 1.28 development release.

So you successfully built from the 1.27 releases on the same machine?

**Comment by the-j0k3r** [comment]
If you are compiling in actual Debian you may find that Debian has its own (lets say) unique way of doing things.

**Comment by fsievers** [comment]
Sorry, but I'm not able to reproduce the error anymore. After checking out the last commit that build successfully and going forward to newer commits, I was unable to get the error again. I also tried it again after uninstalling the `libonig-dev` package.

Maybe I forgot the clean up the build environment before building or something else.

As I was able to build the 1.30-release branch even without `libonig-dev` package installed, this issue does not exist anymore (at least for me).

**Comment by fsievers** [comment]
Hmm, after writing my previous comment, I pulled 4 new commit from the 1.30-release branch and tried to build it. Now the error is back. I don't know why it build yesterday.

I was doing the following:
1. run `./script/clean`
2. run `./script/bootstrap`

The error from my initial report is back now. I also reinstalled `libonig-dev` without success.

This is the output of the npm debug log:
```
10609 silly install oniguruma@6.2.1
10610 info lifecycle oniguruma@6.2.1~install: oniguruma@6.2.1
10611 verbose lifecycle oniguruma@6.2.1~install: unsafe-perm in lifecycle true
10612 verbose lifecycle oniguruma@6.2.1~install: PATH: /mnt/data/florian/projects/extern/atom/script/node_modules/npm/bin/node-gyp-bin:/mnt/data/florian/projects/extern/atom/apm/node_modules/atom-package-manager/node_modules/oniguruma/node_modules/.bin:/mnt/data/florian/projects/extern/atom/apm/node_modules/atom-package-manager/node_modules/.bin:/mnt/data/florian/projects/extern/atom/apm/node_modules/.bin:/home/florian/.local/bin/:/home/florian/perl5/perlbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10613 verbose lifecycle oniguruma@6.2.1~install: CWD: /mnt/data/florian/projects/extern/atom/apm/node_modules/atom-package-manager/node_modules/oniguruma
10614 silly lifecycle oniguruma@6.2.1~install: Args: [ '-c', 'node-gyp rebuild' ]
10615 silly lifecycle oniguruma@6.2.1~install: Returned: code: 1  signal: null
10616 info lifecycle oniguruma@6.2.1~install: Failed to exec install script
10617 verbose unlock done using /home/florian/.npm/_locks/staging-0de1fc935dbaf394.lock for /mnt/data/florian/projects/extern/atom/apm/node_modules/.staging
10618 warn atom-bundled-apm@ No license field.
10619 verbose stack Error: oniguruma@6.2.1 install: `node-gyp rebuild`
10619 verbose stack Exit status 1
10619 verbose stack     at EventEmitter.<anonymous> (/mnt/data/florian/projects/extern/atom/script/node_modules/npm/lib/utils/lifecycle.js:289:16)
10619 verbose stack     at emitTwo (events.js:126:13)
10619 verbose stack     at EventEmitter.emit (events.js:214:7)
10619 verbose stack     at ChildProcess.<anonymous> (/mnt/data/florian/projects/extern/atom/script/node_modules/npm/lib/utils/spawn.js:40:14)
10619 verbose stack     at emitTwo (events.js:126:13)
10619 verbose stack     at ChildProcess.emit (events.js:214:7)
10619 verbose stack     at maybeClose (internal/child_process.js:925:16)
10619 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
10620 verbose pkgid oniguruma@6.2.1
10621 verbose cwd /mnt/data/florian/projects/extern/atom/apm
10622 verbose Linux 4.15.0-29-generic
10623 verbose argv "/usr/bin/node" "/mnt/data/florian/projects/extern/atom/script/node_modules/.bin/npm" "--global-style" "--loglevel=error" "install"
10624 verbose node v8.11.3
10625 verbose npm  v5.3.0
10626 error code ELIFECYCLE
10627 error errno 1
10628 error oniguruma@6.2.1 install: `node-gyp rebuild`
10628 error Exit status 1
10629 error Failed at the oniguruma@6.2.1 install script.
10629 error This is probably not a problem with npm. There is likely additional logging output above.
10630 verbose exit [ 1, true ]
```

Any hints what I do wrong or what I could do to find the problem?

**Comment by the-j0k3r** [comment]
if you cloned this via git, try running `git clean -xffd` to make sure you dont have any remnants in the git dir before youre compiling

**Comment by fsievers** [comment]
After running `git clean -xffd` I didn't face the problem with a failing `oniguruma` module installation anymore. But I found another problem.

If I first run `./script/bootstrap` all modules install successfully. But if I run `./script/build` after that, the installation fails. The problem in this case was, that while bootstrapping, my global installed `npm` version 6.2.0 is used. If I run the build after that, the npm version (`5.3.0`) from bootstrap is used. This produces some strange error like a missing `ansicolor` module.

This problem can be worked around, if I don't run `./script/bootstrap` but run `./script/build` and let it call the bootstrap process.

Finally this solves my problems with build from source:
- run `git clean -xffd`
- run `./script/build` (or in my case `./script/build --create-debian-package`)

**Comment by the-j0k3r** [comment]
I dont think youre suppose to call the bootstrap script manually, anyway case closed no?

**Comment by 50Wliu** [comment]
`script/build` automatically calls `script/bootstrap`.  There are occasionally problems with npm not knowing how to handle the own lockfiles it produces...leading to the ansicolors issue.  If that happens, just run `git clean` again (this should hopefully be rectified with the apm 2.0 upgrade #17675 - we'll see).

Closing this since you seem to be able to build Atom successfully now.
