### ISSUE TITLE
'Select Next' does not recognize scope

### ISSUE THREAD

**Issue by statsandthings** [atom/atom#17763]
Sublime text has a feature that allows you to highlight multiple identical selections to rename variables quickly. It is initiated with <kbd>Ctrl</kbd>+<kbd>D</kbd> on your keyboard, the same keyboard combination as Atom. Most importantly Sublime's *is* context aware. If I want to rename the variable `is` to `xy`, it won't, for instance, rename `this` to `thxy`. Atom's *does not* recognize scope in the same fashion.

In Atom - Highlight the first two letters in this code chunk below (ie 'is') and press <kbd>Ctrl</kbd>+<kbd>D</kbd>. It's jumps to the 'is' in th**is**. I want Atom to jump straight to the next unique occurrence of 'is' not just any text string that contains 'is'. I know I can get around this with RegEx, but what a pain that would be.

    is
    this is really cool
    code
    this is really cool
    code

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/ScObu.gif

**Comment by Aerijo** [comment]
> Sublime's is context aware

> it won't, for instance, rename `this` to `thxy`

To clarify, by context aware you mean it enforces word breaks at both ends of the search term? But not actually limiting itself to block / function scope?

**Comment by rsese** [comment]
I believe this is expected behavior if you select the text with your mouse or by double clicking the word.  You can do what you want by putting the cursor over `is` and hitting `ctrl-d` which will select it.  Subsequent `ctrl-d`s will only select `is` that isn't part of another word.  

Hope that helps but let me know if I mis-understood.

Also, for future issues please use the issue template - the information in the template is super helpful for us when triaging issues.

**Comment by statsandthings** [comment]
> Subsequent ctrl-ds will only select is that isn't part of another word

@rsese this isn't true on my Windows 7 Atom version 1.29.0 64bit. Highlight the word `is` in this code and `ctrl-d` or `alt-f3`. The 'is' in th'is' will be selected.

```
is
this is really cool
code
this is really cool
code
```

**Comment by rsese** [comment]
Did you select the first `is` with `ctrl-d`?  I just tried on 1.29 and Windows 10 and it worked for me:

![select-next](https://user-images.githubusercontent.com/734194/43599166-5f760f1c-964c-11e8-9ebe-a66632321a76.gif)

**Comment by statsandthings** [comment]
@rsese yes I am first selecting `is` with `ctrl-d`. I'll paste the gif below showing this issue. Do you think one of my packages or settings is different than yours? I checked my settings and my packages and there is not anything obviously wrong. Could it be an Atom bug?

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/IshcK.gif

**Comment by statsandthings** [comment]
@rsese Thanks for that tip. I launched Atom in safe mode (see GIF below) and I've still got the same issue. At this point it must be a bug, right? Want me to open a new bug report, and I'll fill in the full template like you recommended?


[![enter image description here][1]][1]


  [1]: https://im4.ezgif.com/tmp/ezgif-4-4d22dc584a.gif

**Comment by rsese** [comment]
That GIF link is 404-ing, can you re-share it?  

I'll go ahead and re-open this one since we've looked at some things already but if you can edit the issue body to use the issue template that would be great :+1:

**Comment by statsandthings** [comment]
@rsese I updated the original body to follow the issue template. I also fixed the *404 error*. I did both of these in this thread you're reading now as I am unable to edit anything on [the other thread](https://github.com/atom/find-and-replace/issues/1038) that this issue was moved to. I'm not sure how to update [that other](https://github.com/atom/find-and-replace/issues/1038) newer thread because the **move**`bot` has everything locked.

**Comment by rsese** [comment]
Ugh right sorry about that - I updated the issue body there, let's continue the conversation in https://github.com/atom/find-and-replace/issues/1038.
