### ISSUE TITLE
Atom doesn't open Preferences, About, Files, and more

### ISSUE THREAD

**Issue by marco-brandizi** [atom/atom#17790]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For some reason, there are severeal things I cannot open in Atom anymore: Atom->About, Aom->Preferences, opening files, drag/drop files and probably more. I've tried anything: upgrading to 1.29, removing .atom and ~/Library and more, cheching leftover processes, running --safe, running as root, running as a new user. Nothing help: when I try to open the mentioned item, nothing happens, even running Atom from the command line doesn't show any message.

### Steps to Reproduce

1. Open Atom
2. Open one of the items mentioned

**Expected behavior:** Atom opens the item as usually

**Actual behavior:** Anything whatsoever

**Reproduces how often:** always

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

macOS 10.13.6

**Comment by rsese** [comment]
Thanks for the report!  Since you're on 10.13.6 and Atom 1.29.0, this sounds like a duplicate of https://github.com/atom/atom/issues/17727.  I'll close in favor of that one for now and you can subscribe there for updates, but we can re-open this issue if it ends up being a separate problem.

**Comment by marco-brandizi** [comment]
@rsese I've read #17727 better and I think you should re-open this issue. As I wrote in that other issue, in my case the main window is appearing, but then there are many menu items that don't produce any action, so similar behavior and possibly same cause, but not exactly the same thing.

**Comment by rsese** [comment]
> in my case the main window is appearing

Yeah it seems like in the other issue people are reporting that they don't see any window.

So it sounds like you've tried safe mode, clearing saved state, and resetting to factory defaults is that correct?

And from your description, it sounds like this happened recently - can you confirm what version did work for you?

**Comment by marco-brandizi** [comment]
@rsese yes, I've tried every clearing options you mention. It started happening a few days ago, I believe after upgrading to 1.29, but I don't remember if I upgraded because it started doing it with 1.28 too. I can only add that a couple of weeks ago I migrated my home directory (`/Users/<loginid>`) to my new Mac. I might be able to investigate more if I could run Atom with more verbosity for the logger (it seems the command line has no such option, but maybe I can pass it some logger config file?).

**Comment by rsese** [comment]
> It started happening a few days ago, I believe after upgrading to 1.29, but I don't remember if I upgraded because it started doing it with 1.28 too.

Can you try installing 1.28 or 1.27 and see if you can still reproduce?

> I might be able to investigate more if I could run Atom with more verbosity for the logger (it seems the command line has no such option, but maybe I can pass it some logger config file?).

Hmmm, what logger are you referring to?

If you start Atom in the foreground, do you see any output?

```
atom --foreground
```

And for the window that does show, are you able to open devtools by any chance?  

Lastly, just so out of curiosity, can you share a screen shot of what Atom looks like for you?

**Comment by marco-brandizi** [comment]
Hi @rsese, sorry I had missed your last comment. I meant some logging that Atom might be doing when enabled, but apart from that, WOW! I've some valuable news: when I run atom with --foreground, everything works well as it used to.

This happens for the 1.29. I tried 1.30.0-beta2, 1.28, 1.27 and they all work as bad as explained in this issue, including when I use --foreground.

**Comment by rsese** [comment]
@marco-brandizi - just wanted to checkin and see if you still need to start Atom in the foreground for some of the menu items to work in the latest versions of Atom (currently 1.32.0-beta3 and 1.31.2 for stable)?

**Comment by marco-brandizi** [comment]
@rsese 1.31.2 behaves like before, things are opened only when starting with --foreground. 1.32.0-beta3 doesn't work even with the foreground option. Meanwhile I moved to Visual Studio Code. Sorry, I like Atom and its open source community, but it is too buggy and I've been waiting for years the fix of issues like this hereby, [Atom Helper sucking the CPU](https://discuss.atom.io/t/atomhelper-high-cpu-usage/2553) or [updates as regular user](https://discuss.atom.io/t/self-updates-with-non-admin-os-x-account/3155/4).

If you need, I can keep testing this issue, if you or others cannot reproduce.
