### ISSUE TITLE
Right Clicking Creates a Different Type of Text Selection

### ISSUE THREAD

**Issue by matthewwithanm** [atom/atom#17799]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There are currently two distinct kinds of selection in Atom. It seems like one may be an uncanceled native one, however, simply ignoring it isn't enough to really fix the behavior.

### Steps to Reproduce

1. Make a normal text selection. In the One Dark theme, it'll be highlighted in gray.
2. Right click another word. This will highlight that word in blue.
3. Select copy from the context menu. It will copy the Atom (gray-highlighted) selection.

**Expected behavior:** [What you expect to happen]

Right clicking a word updates the Atom selection. The word should then be highlighted in gray. There should be no blue selection.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

OSX

```
$ atom --version
Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 2.7.10
git 2.13.5
```

cc @daniel-ohayon who originally raised this bug with the Nuclide team 😊

**Comment by Arcanemagus** [comment]
This bug is at least partially macOS specific:

On Windows the word you right click isn't highlighted with the Chromium default selection (the "blue" selection above), however the Atom cursor isn't moved and the original selection isn't discarded so most of the problematic behavior is still evident.
![2018-08-07_13-27-52](https://user-images.githubusercontent.com/427137/43800614-b7a75630-9a45-11e8-8b6a-6e25cd8265ce.gif)

**Comment by 50Wliu** [comment]
> Right clicking a word updates the Atom selection.

This was reverted in #16627 (if I'm following correctly) following #16192.

**Comment by queerviolet** [comment]
> > Right clicking a word updates the Atom selection.
> 
> This was reverted in #16627 (if I'm following correctly) following #16192. See discussion at #16324 and #16328.

Here's what's going on at head:

![2018-09-05 17 40 36](https://user-images.githubusercontent.com/7763406/45128437-d97b0780-b132-11e8-9aaa-9e6c765354bf.gif)

The gray text is what's actually selected—selecting copy writes the gray selection to the pasteboard.

The blue selection appears to be meaningless—so, presumably, we just don't want to see it.
