### ISSUE TITLE
error when diffing file changes

### ISSUE THREAD

**Issue by kevwil** [atom/atom#17791]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

    unable to save file: Permissions denied '/atom:'

### Steps to Reproduce

1. Open project
2. Change something in a file
3. Click on the 'Open file in Diff View' icon next to the changed file under the UNCOMMITTED CHANGES section
4. Give credentials to Atom Helper dialog asking for permissions.

**Expected behavior:** [What you expect to happen]

Show visual diff of the changes made to the file.

**Actual behavior:** [What actually happens]

Error notification pops up with text from above

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
$ atom --version
Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 3.7.0
git 2.18.0
```
Mac OS 10.12.6.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!

> Click on the 'Open file in Diff View' icon next to the changed file under the UNCOMMITTED CHANGES section

Hmmm, can you clarify this part?  The GitHub package doesn't have an "UNCOMMITTED CHANGES" section but maybe I'm looking in the wrong place.  Can you share a screenshot?

**Comment by kevwil** [comment]
Yes I have the Nuclide plugin installed.

**Comment by rsese** [comment]
Ahhh ok - it may be that there is still a bug in Atom but if so, we'll need the https://github.com/facebook/nuclide maintainers to help track that down.  You should file this issue on [their repository](https://github.com/facebook/nuclide) so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by kevwil** [comment]
Looks like someone beat me to it https://github.com/facebook/nuclide/issues/1556
