### ISSUE TITLE
Atom in WSL does not respect changing the windows drive root mount point

### ISSUE THREAD

**Issue by Jinivus** [atom/atom#17794]
### Description

If the mount point for windows drives in WSL is changed via editing /etc/wsl.conf, detailed [here](https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/), atom no longer works to open windows directories/files that it once opened without issue.

### Steps to Reproduce

1. Change WSL default windows drive mount points to anything other than /mnt/%drive_letter%. 
This is done in the /etc/wsl.conf file, specified [here](https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/)
2. Navigate to a directory on the windows filesystem inside WSL. Eg /c/dev/
3. Run "atom ."

**Expected behavior:** Atom to open using the current directory

**Actual behavior:** Command line outputs "The system cannot find the path specified."

**Reproduces how often:** 100%

### Versions

Windows 10 - 18.03 + WSL Ubuntu 18.04

### Additional Information

Contents of /etc/wsl.conf are as follows:

> ```
> [network]
> generateResolvConf = false
> 
> [automount]
> root = /
> options = "metadata"
> ```

**Comment by rsese** [comment]
Thanks for the report (and for the pull request :v:)!  Reproduced on Windows 10 + Ubuntu 18.04 and Atom 1.29.
