### ISSUE TITLE
Scrollbar styles not being applied when stylesheets change

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#1780]
A recently merged [PR](pr) on the atom-dark-ui theme styles the scrollbars when they are always visible. Unfortunately, when scroll bar styling is added after a scrollbar is already visible (as occurs when we load the theme after deserializing the editor), the styling isn't applied.

Not sure what the best approach on this is. Maybe we could watch for stylesheet changes and change the overflow property away from scroll and then back. But I'm concerned this could hose our scroll position. Also, *anything* that's scrollable would need to be fixed.

@zcbenz How tough would a chromium patch be in this case? Even a native command to redraw scrollbars across the window could be a good workaround.

[pr]: https://github.com/atom/atom-dark-ui/pull/12

**Comment by thomasjo** [comment]
Unable to reproduce this on OS X 10.10.3.
