### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by LewisAn** [atom/atom#17818]
## Summary

One paragraph explanation of the feature.

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Describe alternatives you've considered

A clear and concise description of the alternative solutions you've considered. Be sure to explain why Atom's existing customizability isn't suitable for this feature.

## Additional context

When I'm trying to compile & run a .c file, it threw Segmentation fault 11. It worked fine on vim, but when I used atom, it became cracked.

**Comment by Aerijo** [comment]
> When I'm trying to compile & run a .c file

Atom does not provide code compilation by itself. You should work out which community package you are using to do this, and check out their repo for an existing issue or raise a new one there.

If the maintainers there think it's an issue with Atom core, they will be in a better position to pinpoint the issue. 

In the mean time, I'll close this issue as not core related.
