### ISSUE TITLE
Error build atom from release 1.29.0

### ISSUE THREAD

**Issue by PerduGames** [atom/atom#17828]
I'm trying to install the atom from the source code provided 
here: https://github.com/atom/atom/archive/v1.29.0.zip

and I get the following error:

[atom_install_error.txt](https://github.com/atom/atom/files/2281510/atom_install_error.txt)

also follows the "npm-debug.log":

[npm-debug.log](https://github.com/atom/atom/files/2281511/npm-debug.log)

OS: Void Linux
node -v: 9.8.0
npm -v: 5.6.0

**Comment by daviwil** [comment]
You'll need to figure out which package on Void includes this header and then install it:

```
keyboard-layout-manager-linux.cc:5:10: fatal error: X11/extensions/XKBrules.h: No such file or directory
 #include <X11/extensions/XKBrules.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by PerduGames** [comment]
Strange I had already installed from other times and this error never happened, is this new? and how do I find out which package you need? how to urge it?

**Comment by rsese** [comment]
A couple of other folks (on Ubuntu not Void) reported the same error:

* https://github.com/atom/atom/issues/13659
* https://github.com/electron-userland/electron-spellchecker/issues/91

In both cases they installed `libxkbfile-dev`, to fix the issue.  Perhaps you can ask on the Void forum if that/a similar package is available on Void (no one on the team uses Void unfortunately)?

https://forum.voidlinux.org/

**Comment by the-j0k3r** [comment]
@rsese @PerduGames 

Yes Void Linux has [libxkbfile-devel](https://github.com/void-linux/void-packages/blob/master/srcpkgs/libxkbfile-devel) current v1.0.9

**Comment by PerduGames** [comment]
I was able to solve by installing the package "libxkbfile-devel".

**Comment by the-j0k3r** [comment]
@PerduGames then feel free to close ticket. ;)
