### ISSUE TITLE
Atom doesn't soft wrap CJK(Chinese/Japanese/Korean) correctly

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1783]
Reported in Halp:
* support/b47caffcaba511e3903bfcd96bef4da2

> If I have a paragraph in CJK characters and toggle soft wrap, the wrapping point (should be the right edge of current window) is far away than the current edge and some characters are displayed out of window which is not visible.
> I think this may because of the wrong processing of character wide. A latin letter has a width "one character width", but usually a CJK character has a width twice as a latin letter, it's "two character width". Hope this information may help you.
> The debug info auto attached should include the test text I open now. It's include (from up to down): Chinese, Japanese, Korean, English. Actully they tell the same thing:)

I can reproduce this in Atom 0.75.0. (notice how CJK characters are not wrapped correctly at the right edge of the app)

![screen shot 2014-03-22 at 7 24 05 pm](https://f.cloud.github.com/assets/38924/2491493/404ad7da-b1ef-11e3-9143-272b55530c6c.png)

**Comment by allenfantasy** [comment]
Thank you very much! Though [japanese-wrap] is for Japanese but I found it works perfect in Chinese. @SaschaNaz

**Comment by DeckerCHAN** [comment]
@SaschaNaz Thankyou! Works good for me!

**Comment by clkao** [comment]
@SaschaNaz++! works perfectly for zh-hant as well.

**Comment by hanfeisun** [comment]
hope the issue could be fixed officially +1

**Comment by Maki-Daisuke** [comment]
Great!!  @SaschaNaz++!

**Comment by kmxz** [comment]
After updating my Atom to the latest version, the AtomicChar package no longer works... so sad.
Why isn't this issue officially fixed yet?

**Comment by SaschaNaz** [comment]
I'm investigating. Maybe I should just send a pull request...

**Comment by SaschaNaz** [comment]
@kmxz New version should now work. Thanks.

**Comment by kmxz** [comment]
@SaschaNaz The new version works perfectly. Thank you very much,

**Comment by SaschaNaz** [comment]
I'm working on this for a pull request.

**Comment by raccy** [comment]
@SaschaNaz Great working!
I'm looking forward to that your work is complete.
and... I'll be happy, because I don't have to fix japanese-wrap with `measureText`,
and for Chinese and Korean.
やっとメンテナンスの重圧から逃れられる(-д-; (Do not translate!)

**Comment by SaschaNaz** [comment]
@raccy A big :+1: for your pioneering work. :D I'm also looking forward to seeing this issue fixed.

**Comment by huangxg** [comment]
@SaschaNaz Thanks for your AuomicChar. Once I enable the package, lines with Chinese characters do wrap at window edge, but not at Preferred Line Length 80. And lines with Latin characters lost wrap, I have to disable it to bring the wrap on Latin lines back.

OS: Mac OS X Yosemite 10.10.3
Atom 0.201.0
AtomicChar 0.3.6

**Comment by Tedko** [comment]
![2015-05-28 18_41_54-undeliverable_ visual studio code cannot wrap cjk characters properly when soft](https://cloud.githubusercontent.com/assets/6687437/7886819/269d5f72-065f-11e5-968b-0a9433ffee2b.png)

**Comment by flyisland** [comment]
@SaschaNaz Thanks for your AuomicChar. Both Chinese and English characters are wrapped correctly now!

OS: Win 7
Atom 1.03
AtomicChar 0.3.8

**Comment by frantic1048** [comment]
@SaschaNaz 

Thanks you, works well !

BTW, is the gap on the right edge sometimes too big ?

![preview](https://cloud.githubusercontent.com/assets/3102803/9109325/6c38045e-3c67-11e5-96c8-6b27dead7408.png)

**OS** : Linux 4.1.4-1-ARCH
**Package** : archlinuxcn/atom-editor-bin, Precompiled binary from official repository
**Atom Version** : 1.03
**AtomicChar Version** : 0.3.8

**Comment by jkiss** [comment]
[japanese-wrap](https://atom.io/packages/japanese-wrap) can work well, thanks!

**Comment by sunsolve** [comment]
Neither Atomichar and Japanese-wrap did not work when I edit asciidoc (file's suffix is adoc),but it worked properly when I edit HTML file or others.

**Comment by Superpencil** [comment]
+1

**Comment by Blaisorblade** [comment]
Have you considered using the `wcwidth` API to measure how many columns a string takes? I suggested that earlier, but that was somewhere else. I also pointed to the code I believe should be changed to fix this cleanly:
https://discuss.atom.io/t/preferred-line-length-dont-support-chinese/4666/3?u=blaisorblade

**Comment by Superpencil** [comment]
Cant we just write some js that breaks the line at window width by adding a linebreak?

**Comment by benogle** [comment]
Hi all, there is a PR open to fix this https://github.com/atom/atom/pull/9162 If anyone of you are building from master, please give this PR a try!

cc @as-cii

**Comment by benogle** [comment]
This has been fixed by https://github.com/atom/atom/pull/9162. It will be out in the beta channel next week, and is in master now! :heart: @as-cii

**Comment by chloerei** [comment]
Still some problem.

Text:

```
文字文字 English 文文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字字文字文字
```

1.2.0-beta0:

![7](https://cloud.githubusercontent.com/assets/49931/10838793/6bfe83dc-7f06-11e5-8ab6-13f92609c5a3.png)

When mixing English and Chinese(or Japanese) with whitespace, Chinese(or Japanese) sentence can be break, instead of break in whitespace. like browser:

> 文字文字 English 文文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字字文字文字

**Comment by benogle** [comment]
Can you make a new issue @chloerei?

**Comment by chloerei** [comment]
@bencolon OK https://github.com/atom/atom/issues/9447

**Comment by webhacking** [comment]
using support fonts  `CamingoCode, Liberation Mono, DejaVu Sans Mono, monospace`
