### ISSUE TITLE
Permission denied on SAMBA network drive

### ISSUE THREAD

**Issue by TvviNN** [atom/atom#17858]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I cannot open folders in a SAMBA network drives as projects. Trying to open folders on the network drive gives the "Permission denied" error. Opening files is possible, but saving is not permitted (Unable to save file '[path]' --- EEXIST: file already exists, mkdir '[path]')

### Steps to Reproduce

1. Mount a folder including a file on a SAMBA network
2. Open Atom Editor and try to open the folder as a project folder, folder or directly open the file.
3. Try to save the opened file.

**Expected behavior:** Be able to open folder or save the file.

**Actual behavior:** 
* Trying to open network folder as project: Project folder does not even show up, nothing happens. 
* Trying to open folder: New window is opened, but "Permission denied" error is displayed. 
* Unable to save files. 

**Reproduces how often:** 100%

### Versions

Atom Version 1.29.0
apm 1.19.0
npm 3.10.10
node 6.9.5 x64

OS: Windows 7 Enterprise - Service Pack 1

### Additional Information

Trying to do all these things (opening project folder, folder or save file) on the local file system works as it should. In addition, opening SAMBA network files and editing is no problem with other programs like, e.g., Notepad++.

**Comment by rsese** [comment]
Thanks for the report - is this behavior new for you after updating to 1.29 and worked previously or is this a fresh install?

Also, do you see any difference if you try the other options for `Settings > Core > File System Watcher`?

**Comment by TvviNN** [comment]
Unfortunately I did never try to access network directories using SAMBA before. 

I tried all other options and did not see any difference, the problems still persist.
