### ISSUE TITLE
Decrease minimum allowed value of `maxScreenLineLength` from 500.

### ISSUE THREAD

**Issue by danfuzz** [atom/atom#17864]
## Summary

Propose reducing the minimum allowed value of `maxScreenLineLength`. As of this writing, the default value is `500`, and the minimum value is also `500`. Suggest that a value of `80` might be a better minimum.

## Motivation

Some people don't like to scroll back and forth on long lines. The existing enforced minimum value does not allow such people to configure Atom in a way that is friendly to their needs / desires.

## Describe alternatives you've considered

AFAIK there isn't an alternative other than changing the minimum as defined in `src/config-schema.js` in this repo. E.g., if you try to set the value to less than `500` right now (e.g. by manually editing your `config.cson`, Atom will remove the setting the next time it writes out that file.

## Additional context

Section of the schema file in question that would need to be updated: <https://github.com/atom/atom/blob/master/src/config-schema.js#L459>

```js
      maxScreenLineLength: {
        type: 'integer',
        default: 500,
        minimum: 500,
        description: 'Defines the maximum width of the editor window before soft wrapping is enforced, in number of characters.'
      },
```

**Comment by lee-dohm** [comment]
Thanks for the suggestion.

This value is intended to be used to enforce a minimum performance standard on excessively long lines, not to create a soft wrap boundary in a pane item that is wider than a certain size. For that, see the settings "Soft Wrap At Preferred Line Length" and the "Preferred Line Length" settings.

I hope that helps!

**Comment by danfuzz** [comment]
Near as I can tell, the settings you mention don't do what I'm trying to achieve. In particular, it looks like if I set my "preferred length" to (say) 250 and turn on both "soft wrap" and "soft wrap at preferred length", Atom will still wrap to my window width if that's less than my preferred length.

What I'm looking for is to have soft wrapping occur at a particular width, regardless of my window geometry. Near as I can tell, setting `maxScreenLineLength` does exactly what I want, except that it has a strangely-large enforced minimum.

**Comment by Aerijo** [comment]
@danfuzz The `maxScreenLineLength` is not really a user setting; it's for performance, but some users complained it was too low. 

The part about soft wrap not using the windows width is interesting though. It should be a straightforward change to make this optional.

**Comment by danfuzz** [comment]
Thanks for the explanation. I'd certainly be happy with the outcome you describe, though (rhetorically speaking) I remain confused why the existing setting can't be "retconned" into a bona fide user setting, _especially_ since it's already exposed to users in the main Editor settings panel.

**Comment by danfuzz** [comment]
So it goes. I appreciate your effort nonetheless. Thanks!
