### ISSUE TITLE
A Wrong Auto-Indent For PHP

### ISSUE THREAD

**Issue by sjchoiAtBI** [atom/atom#17871]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Incorrect indent in php file.
'{{' is a string but Atom indents the next line.

<img width="506" alt="untitled 2" src="https://user-images.githubusercontent.com/26270985/44182476-1eb6a580-a142-11e8-8048-9f2a2dd60e70.png">

### Steps to Reproduce

1. Open a php file.
2. Type like below.
```
curl_setopt($ch, CURLOPT_URL, "https://myurl.com");
curl_setopt($ch, CURLOPT_SSLPASSWORD, '{{');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
```

3. Auto-indent the line.
**Expected behavior:** [What you expect to happen]
<img width="538" alt="untitled" src="https://user-images.githubusercontent.com/26270985/44182546-6b9a7c00-a142-11e8-9d7d-34ac9be9c124.png">

**Actual behavior:** [What actually happens]
<img width="506" alt="untitled 2" src="https://user-images.githubusercontent.com/26270985/44182476-1eb6a580-a142-11e8-8048-9f2a2dd60e70.png">

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions
Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Aerijo** [comment]
Also note that the following will trigger it
```
<?php

{} // <- picked up as increaseIndentMatch

?>
```

Besides making [the indent regex](https://regex101.com/r/noJxIj/1) more complicated, I don't think there's a reliable way to get it right in every case. Maybe it could fail if the line ends with a semi colon (before any comments)?

Fortunately, this should be much easier with Tree-sitter.
