### ISSUE TITLE
Atom opens/reopens windows in bizarre locations

### ISSUE THREAD

**Issue by queerviolet** [atom/atom#17875]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When running with multiple displays, Atom makes some very strange choices about where to place new windows.

This is most pronounced when reloading an existing window with ⌥⌘I ⌘R, which typically re-opens the window on display 0, regardless of where it was before.

It seems to vaguely seek out another place where there's an Atom window—in some cases, switching Mission Control Spaces to do so. It's hard to underscore how irritating this is.

### Steps to Reproduce

*Space switching:*
1. Have multiple Spaces
2. Open an Atom window in one space
3. Create or move to another space
4. Open Terminal
5. Run `atom .`
6. Behold! You have been transported back to the space you were trying to escape, a metaphor for the inescapability of oppression in a world of pervasive capitalism.

*Reloading a window:*
1. Have multiple displays
2. Put Atom on a secondary display
2. Open the dev console (⌥⌘I) 
3. Reload window with ⌘R
4. Where is it? Where's the window? *it's a bloody mystery*

**Expected behavior:** Atom should (re)open windows on the same display and Space that the last key window occupied.

When opening a new window, you can defend the behavior of opening on the same Space as an existing Atom window, provided the Space is visible. Switching Spaces seems always wrong, and is massively disorienting to boot.

**Actual behavior:** We seem to pick the Space / display with an active Atom window, switching to it if necessary. But sometimes we don't.

**Reproduces how often:** *So* often.

### Versions
macOS High Sierra
Atom    : 1.30.0-dev-a41a345de
Electron: 2.0.4
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

I suspect we may need to kick this over to Electron; or, it might be inescapable garbage from macOS. Anyway, since we're talking papercuts, I wanted to capture this one.

**Comment by rnash2** [comment]
I experienced a similar problem except on Windows 10.  I opened Atom on second monitor, and later tried to open Atom on my laptop without the external monitor. Atom appeared to open on the second screen even thought the second monitor was not connected and the PC was configured for single monitor. 
I was able to recover only by opening again with second monitor and dragging the window back to the main window before closing.
