### ISSUE TITLE
Toggle 'show hidden files in tree view' from Command Palette

### ISSUE THREAD

**Issue by penx** [atom/atom#17880]
## Summary

Ability to toggle "show hidden files" in the tree view from the command palette.

I guess this means toggling some or all of these settings:
- "Exclude VCS Ignored Paths" under core settings 
- “Hide Ignored Names” and “Hide VCS Ignored Files” under tree settings

## Motivation

I transpile code to `/lib` which is in my .gitignore. Most of the time I don't want to look at this folder, or for it to be included in search results. There are occasions when I want to quickly look at the transpiled output - at the moment this either means finding and changing 2 config settings, or opening the files/folders manually in my OS.

This is a pain, and a toggle in the command palette to hide/show these files would save a lot of time.

## Related

#4203
#5423
#8276
https://medium.com/@panayiotisgeorgiou/how-to-show-hidden-files-atom-sidebar-c75a2de68709

**Comment by lee-dohm** [comment]
You can already select the Tree View and press the <kbd>I</kbd> key to do this. See the [Tree View keymap for details](https://github.com/atom/tree-view/blob/master/keymaps/tree-view.cson#L82).

**Comment by lee-dohm** [comment]
This also means that you can use "Tree View: Toggle VCS Ignored Files" in the Command Palette, though the Tree View has to be focused for it to show.
