### ISSUE TITLE
100% usage when started on home folder

### ISSUE THREAD

**Issue by igormcoelho** [atom/atom#17889]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

As described before https://github.com/atom/atom/issues/6437 I'm having the exactly same issue on Atom (just after upgrading Deepin 15.6 to 15.7). My Atom version is 1.29.0 x64. It consumes all my CPU if I open some file on the home folder, but does not happen anywhere else! I tried on my downloads folder, which has much more files, but nothing happens... I tried disabling GPU, mv .atom folder, removed everything and reinstalled from scratch.

### Steps to Reproduce

1. I just open `atom ~/file.txt`
2. Observe `top`: 120%

**Expected behavior:** [What you expect to happen]

Execute normally and not consume my entire CPU.

**Actual behavior:** [What actually happens]

It consumes my entire CPU.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time I open a file in home directory, it does that.

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

This is loading in different folder than home:
![image](https://user-images.githubusercontent.com/290989/44383119-fb974780-a4ed-11e8-803f-3c6ea177258b.png)

This is loading in home:
![image](https://user-images.githubusercontent.com/290989/44383168-27b2c880-a4ee-11e8-9025-439dede196c1.png)

**Comment by igormcoelho** [comment]
No, it's not.. just checked now. It contains a `.gitconfig` file, but I guess that may be normal.

**Comment by rsese** [comment]
> (just after upgrading Deepin 15.6 to 15.7). My Atom version is 1.29.0 x64.

Can you share the output of `atom -v`?  Also, how did you install Atom?

Was there any difference when you tried safe mode or was the behavior the same?

Lastly, does the CPU spike last as long as you have Atom open or does it stop after some amount of minutes?
