### ISSUE TITLE
snippet not working without spaces between char. 

### ISSUE THREAD

**Issue by axe-z** [atom/atom#17894]
latest, every version: 

been ussing Atom for 5 years now, I've waited long enough ;)

ex: 
.. is my snippet for an arrow FN in js.
I type :
setTimeout()
then want a function in there:
setTimeout(..)  , hit tab, nothing 👎 

I go back 
put spaces between:
setTimeout( .. )  hit tab: 

I finally get 
setTimeout( () =>  ) 
fix the unwanted space:
setTimeout(() =>  ) 

Got it !! 

if Bracket can do this right, there is no way Atom should have issues with this.

**Comment by rsese** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/snippets/ repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

If you can also use the issue template in the new issue, that would be helpful too.

Thanks for meeting us half way 👍
