### ISSUE TITLE
Virtual Reality support via UWP

### ISSUE THREAD

**Issue by zbyte64** [atom/atom#17895]
## Summary

It would be possible to launch Atom inside a VR room (aka cliff house) if the application was published as a UWP. 

## Motivation

VR allows for multiple projects to be open in their own windows and visible without clicking. Newer VR headsets have sufficient resolution for reading. Support for voice recognition lessens the need to hunt for a keyboard in the physical world.

## Describe alternatives you've considered

There are other code editors that do work in windows mixed reality but lack features beyond syntax highlighting. I've also ran the atom inside a desktop inside VR but that adds allot of interface cruft.

## Additional context

I'm aware of #11499 and that there is no desire to support mobile. However I think VR may offer a compelling reason to reconsider UWP.

**Comment by alflanagan** [comment]
It seems to me that if someone is working in VR, and all your other programs work with VR, you're not going to take off the headset to use Atom on a monitor. At some point VR is/will be good enough to replace traditional monitors.
I agree this should be in Electron, which begs the question: is Chrome working in VR?

**Comment by zbyte64** [comment]
@Aerijo VR represents a much bigger surface then what would be commercially viable for most people to acquire with just more monitors.

Please see the referenced issue #11499 for the original discussion on what it would take. In summary **there are tools to wrap electron apps for UWP compatibility**. A group offered to experiment with this and to even publish atom to the windows store.
