### ISSUE TITLE
Line Numbers in gutter missing/hidden

### ISSUE THREAD

**Issue by urscion** [atom/atom#17906]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For all file types, when viewing the file with line numbers, some of the numbers (fairly consistent between files) are missing. They sometimes show if hovered over or if the line is selected.

### Steps to Reproduce

1. Open a file
2. View the line numbers

**Expected behavior:** All line numbers are shown if the option is enabled.

**Actual behavior:** Some line numbers are missing.

![atom_line_numbers](https://user-images.githubusercontent.com/8176416/44495899-dc103400-a63f-11e8-84f7-14f3b117a621.gif)

**Reproduces how often:** 100%

### Versions

Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

Windows 7 Professional 64-bit

### Additional Information

Base installation. No packages.

**Comment by rsese** [comment]
Thanks for the report!

Did you try checking if this is related to your GPU?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem

**Comment by urscion** [comment]
Bingo, that was it. I didn't get all the way down the debugging list it appears :/ 

thanks :)
