### ISSUE TITLE
Dark themes display glitches

### ISSUE THREAD

**Issue by eliottvincent** [atom/atom#17900]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using a dark theme, the code editor display blocky color-shifts. No glitch is visible when using light themes.

### Steps to Reproduce

1. Open Atom
2. Open a file with text in it
3. See the glitches

**Expected behavior:** The background is rendered in a single dark color.

**Actual behavior:** The background includes blocky color-shifts.

**Reproduces how often:** 100%

### Versions

Atom    : 1.29.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 2.7.15rc1
git 2.17.1

OS: Ubuntu 18.04.1 LTS

### Additional Information

This issue looks a lot like #12634 & #14649.
![screenshot from 2018-08-22 16-31-28](https://user-images.githubusercontent.com/24720375/44470028-09051c80-a629-11e8-8891-a7bd509aea8e.png)

**Comment by rsese** [comment]
Thanks for the report!

Did this behavior just start for you recently?  Can you try updating `Settings > Color Profile` to `Use sRGB color profile` and let us know if that helps?

Similar graphical issues x-ref: https://github.com/atom/atom/issues/17776 and https://github.com/atom/atom/issues/17562

**Comment by eliottvincent** [comment]
@rsese It appeared after a fresh install of Atom on a fresh Ubuntu 18.04 laptop. Switching to `Use sRGB color profile` did the trick! Thanks

**Comment by rsese** [comment]
Great glad that helped :+1:

For reference, the custom color profile support was added in 1.28:

http://blog.atom.io/2018/06/21/atom-1-28.html#support-for-custom-color-profiles
