### ISSUE TITLE
missing space and alignment in about tab

### ISSUE THREAD

**Issue by unluisco** [atom/atom#17940]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

### Description

Since the [about package](https://github.com/atom/about) has been archived and incorporated into this repository, I publish here two design issues.

there is missing space before button to check for updates and the icons are not aligned correctly.

![about dropbox robotica dev bot dev 2018-08-28 15-26-31](https://user-images.githubusercontent.com/6332263/44749184-6c82c480-aad7-11e8-8c68-bd8decd43924.png)

### Steps to Reproduce

1. open atom in --safe mode
2. clic About Atom in menubar

### Versions

```
Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

related to #17896

can I fix this?
if so, can you guide me in the best way to fix these design issues?

Thanks.

**Comment by Arcanemagus** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/about/pull/84. It is currently scheduled for release when v1.31.0 reaches Stable.
