### ISSUE TITLE
Tooltips still not closing on keydown events

### ISSUE THREAD

**Issue by cacheflow** [atom/atom#17957]
### Prerequisites

* [X] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-
atom/sections/debugging/#using-safe-mode
* [X] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
* [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
* [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
* [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Tooltips should fade away on keydown events. 

### Steps to Reproduce

*Edit by @rsese to format repro steps*

Using atom/atom as an example:

1. `atom --safe .`
2. Open `SUPPORT.md`
3. Hover over the tab for the file so the path tooltip appears
4. Start typing

Expected behavior: Tooltip(s) should be gone either on mouse hover away OR when any input event happens like keyboard click, mouse click, etc..

Actual behavior: Tooltip keeps in the place until I move mouse away only.

Reproduces how often: 100%

### Versions

Atom 1.3.0^

### Additional Information

![tooltip-without-fix](https://user-images.githubusercontent.com/6132051/44882987-77ba2980-ac6a-11e8-9dfd-c2c751026f44.gif)

**Comment by rsese** [comment]
Thanks for opening a new issue (and for the pull request) @cacheflow, reproduced with 1.32.0-nightly0 on macOS 10.12.6.

x-ref: https://github.com/atom/atom/issues/17431
