### ISSUE TITLE
Git tab/panel (GitLab) wont work after Atom 1.30.0 x64

### ISSUE THREAD

**Issue by orukaz** [atom/atom#17966]
I just installed latest Atom update - version 1.30.0 x64 and Git tab/panel (GitLab) doesn't work anymore. It shows blank content, and I can't graphically commit and push my project to Git.

If I quit the Atom and restart it again several times, the Git tab sometimes starts working, but it is very uncomfortable.

[Here is screenshot](https://app.orumets.ee/screenshots/atom_git_tab_error.png)

**Comment by rsese** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/github repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

If you can also use the issue template in the new issue, that would be super helpful too.

Thanks for meeting us half way 👍
