### ISSUE TITLE
Editor Failing to Open

### ISSUE THREAD

**Issue by Thermixia** [atom/atom#17970]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom background processes starting, but then ending without the editor opening

### Steps to Reproduce

1. Attempt to open atom

**Expected behavior:** Editor Opening

**Actual behavior:** Editor does not open

**Reproduces how often:** 100%

### Versions

1.30.0

### Additional Information
Unknown what additional information would be needed

**Comment by rsese** [comment]
Thanks for the report!

> 1.30.0

Can you share the full output of `atom -v`?  What operating system are you running?

More information that could be helpful:

* Did you have the same issue with previous versions of Atom?
* Was there any difference when you ran in safe mode?
* Did you try any of the other debugging suggestions from the debugging guide like temporarily [resetting to factory defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) or [clearing saved state](https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state) (note that you'll lose any unsaved data when clearing saved state)?

**Comment by Thermixia** [comment]
I'm not currently at home and do not have access to the system. I can tell you I was using 32bit atom, if that's any help

More information:
  • No, in previous versions of atom the problem didn't occur.
  • No, in safe mode the problem continued in the descripted manner
  • I restarted the system otherwise no further attempt was made to fix the issue.

**Comment by rsese** [comment]
Thanks :+1:  What version of Windows are you running?

When you have access to your computer again, go ahead and try the other debugging suggestions I mentioned and let us know if that makes a difference or not.

**Comment by Thermixia** [comment]
Windows 10 Home

**Comment by jarnkata** [comment]
Atom craches on startup when opening it from Windows search. From desktop icon atom is not crashing.  Using windows 10.
Windows 10 Home. Version 1803. OS buils 17134.228

**Comment by anilmuppalla** [comment]
I can confirm this: 
OS: Mac High Sierra 10.13.4
Atom: 1.30.0

It does not open 100% of the time.

**Comment by jarnkata** [comment]
I was installing 1.30 atom and I have not seen problems after that.


pe 7. syysk. 2018 klo 0.26 Robert Sese <notifications@github.com> kirjoitti:
