### ISSUE TITLE
Installing grammars that use Tree-sitter

### ISSUE THREAD

**Issue by Aerijo** [atom/atom#17971]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Packages that use Tree-sitter currently rely on native build tools on the users machine. This may be common on a developers computer, but should not be assumed. See https://github.com/Aerijo/language-latex2e/issues/17 for an issue that was raised on my package because of this.

Additionally, Python 2 may not be installed, or `python` may be pointing to Python 3. Both of these will break node-gyp.

### Steps to Reproduce

1. Make a fresh Windows VM
2. Install Atom
3. Install a package that depends on a tree-sitter module (e.g., [language-latex2e](https://atom.io/packages/language-latex2e))
4. Get error
5. Attempt to install relevant tools by following [these steps](https://github.com/nodejs/node-gyp#option-2) (I was trying to avoid Admin privileges, or installing `npm` seperately. It may be possible to configure the bundled `npm` to run Option 1 though).
6. Get `MSB4132: The tools version "2.0" is unrecognised. Available tool versions are "12.0", "4.`

<img width="768" alt="screen shot 2018-09-04 at 12 34 16 am" src="https://user-images.githubusercontent.com/22167388/44992349-58a8f800-afda-11e8-98d8-c3382e6b750f.png">

**Expected behavior:** [What you expect to happen]

Either it works without issue, or notifies the user that certain build tools are required & either offers to install them, or links to detailed steps to do it manually.

**Actual behavior:** [What actually happens]

An error is thrown. Exactly what error depends on how much the user has installed. Fresh Windows throws that Python 2 is missing, installing that throws something about missing build tools, installing version 2.0 / 4.0 / 12.0 of something, etc.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

Atom 1.30.0

### Additional Information

- [More on MSB4132](https://github.com/chjj/pty.js/issues/60)

- The specific error is not the point of this issue. The issue is that it's possible to get an error at all.

- The Python issue is probably easier to fix 

- Avoiding Administrator privileges is also highly desirable. Many users will not have this, and installing these tools could be impossible / extremely difficult.

- There may also be issues with spaces in user names. I haven't tried it with this particular issue though.

**Comment by Aerijo** [comment]
Alternatively, it might be better to prebuild  the package like is done with core tree-sitter packages. That’s way, anyone who could use core languages can use it. This could happen when the package is published, and could be triggered by auto detecting something, or a setting in the package.json

/cc @maxbrunsfeld Thoughts? I quite like the prebuild idea. It completely circumvents the need for any build tools of the user.

**Comment by maxbrunsfeld** [comment]
Yeah, prebuilding the modules is good. We've already [done](https://github.com/tree-sitter/tree-sitter-ruby/pull/87) [that](https://github.com/tree-sitter/tree-sitter-bash/pull/20) for some of the parsers, and creators of grammars are free to do it without any changes on our side.

**Comment by Aerijo** [comment]
@maxbrunsfeld OK. I think I've got prebuilt binaries set up. Getting tags and releases working when I just run `npm version minor` etc. doesn't seem to work, so I also have to run `git push --tags`.

For some reason, Travis CI is [convinced that the credentials are bad](https://travis-ci.com/Aerijo/tree-sitter-biber/jobs/143834578#L750), but [it still manages to upload the binaries](https://github.com/Aerijo/tree-sitter-biber/releases). Overall, learning CI was slow and painful, but the results are great. I could install on a completely new Ubuntu VM with just Atom installed. Detailed steps for this should definitely go in the flight manual.

**Comment by maxbrunsfeld** [comment]
> Detailed steps for this should definitely go in the flight manual.

Would you be interested in submitting a PR for this? People seem to find your guides really helpful. I think it would make sense to add it to [this section](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#the-parser).

**Comment by Aerijo** [comment]
@maxbrunsfeld I've started on it. I'm thinking the actual setup guide should go in a separate place, maybe a gist. We could then have in the flight manual a paragraph explaining what the problem is, how CI solves it, and link to the setup gist.

Plus I still don't really get half of it;

- What process do you follow when releasing a new `tree-sitter-bash` version? I didn't see any GitHub credentials in the CI files, so does it work differently if you release via GitHub?

- Assuming we don't need those credentials, it looks like we can copy verbatim except for
  - Travis only needs `PREBUILD_UPLOAD=<github_token>` encrypted using `travis encrypt PREBUILD_UPLOAD=<github_token> --add` and the existing `env.global.secure` can be omitted , and 
  - Appveyor only needs to encrypt the token itself, and use it to replace the existing one

- Also remember to add the right scripts and dependencies to `package.json`

In any case, so far I have
> Importantly, by default the user will need to build the parser on their personal computer before it can be used in Atom. This requires them to have the proper build tools and environment, which is often difficult and sometimes impossible. Instead, consider setting up a CI deployment workflow. Properly configured, it will upload prebuilt binaries of the parser for every major platform each time you publish a release. You can find detailed instructions on how to do this [here](https://github.com/atom/atom/issues/17971#issuecomment-418795797)

**Comment by maxbrunsfeld** [comment]
> What process do you follow when releasing a new tree-sitter-bash version? I didn't see any GitHub credentials in the CI files

You do need credentials. There are encrypted environment variables in `appveyor.yml` and `.travis.yml` that contain a github oauth token.

> I'm thinking the actual setup guide should go in a separate place, maybe a gist. We could then have in the flight manual a paragraph explaining what the problem is, how CI solves it, and link to the setup gist.

👍  Yeah, that makes sense.
