### ISSUE TITLE
Atom's UX problems

### ISSUE THREAD

**Issue by simurai** [atom/atom#17974]
## Summary

Here a few UX problems that aren't really bugs nor feature requests, but can still negatively impact a user's experience. I'll keep adding more when something comes to mind. Also feel free to comment below, but keep in mind that this issue is not meant to brainstorm solutions and only focuses on the problems first. If we want to improve something, an RFC should be proposed.

---

## Can't quickly switch projects

When wanting to switch to another project, Atom opens a new window which takes a while. And you also have to close the current window. Also, the new window size and placement could be different and might need adjustment. 

**Workaround**:

- You could re-use the same window by removing and adding root folders in the tree-view, but that feels tedious.
- Use packages like [project-plus](https://atom.io/packages/project-plus), [project-jump](https://atom.io/packages/project-jump), [project-switcher2](https://atom.io/packages/project-switcher2)

## No way to limit the scope to a single root project

When having multiple root projects, find and replace or fuzzy finder always search in all projects. But sometimes you might want some projects not to be "active" and just use as reference. Similar issue: [https://github.com/atom/github/issues/1676](https://github.com/atom/github/issues/1676)

**Workaround**: Temporarily remove and then after the search, add the removed projects back again.

## Autocomplete is not auto enough

When Autocomplete shows several options, the order is chronological. If the option you want is not near the top, you have to spell it out or use the arrow key many times.

**Workaround**: None.

## Slow settings for Packages/Themes and Updates

It usually takes several seconds until the list of packages/themes is shown. Or when showing in the Status Bar that there are new updates available, it still takes a long time until the updates show up in the settings.

**Workaround**: Install [package-settings](https://atom.io/packages/package-settings) to open a package's settings directly.

## Package discovery is hard to find in the settings

People instinctively go to `Settings > Packages` and then start to type to search for a package, not realizing that they have to go to `Settings > Install`. This came up in the past https://github.com/atom/settings-view/issues/825, but hasn't gotten enough priority.

**Workaround**: Use `apm install package-name`.

## It's hard to know the health of a package

There are many packages that are abandoned and not maintained anymore. They are either broken or have bugs that make it less usable. But it's hard to know before installing a package and trying it out.

**Workaround**: Go to the repo to check a package's "health".

## Command palette could get over-polluted.

Because there are quite a few commands, more when installing a lot of packages, it becomes hard to use commands without spelling them out.

**Workaround**: Remove packages so they don't pollute the list, use a keymap or install the [tool-bar](https://atom.io/packages/tool-bar) package.

## Some functionality is hard to discover

For example the GitHub package has a dock item with current and open PRs, but it's hard to discover that this exists. See this [issue](https://github.com/atom/github/issues/1573)

**Workaround:**

- Look through `Menu > Packages`
- Look through command palette
- Package authors could add a button to the Status Bar, although the Status Bar shouldn't be (mis-)used as a navigation

## Package authors need to build their own UI

Atom provides some UI components like select-list, tooltip, mini-editor and there are also some CSS-only components in the [Styleguide](https://github.com/atom/styleguide/) like button, checkbox, inputs etc. But otherwise package authors need to build everything themselves. It's great to have the freedom, but it's also a lot of extra work and consistency lacks between all the packages.

**Workaround**: Package authors could use a 3rd party UI library.

**Comment by szeck87** [comment]
For **Slow settings for Packages/Themes and Updates**, another workaround could be that package authors that use the top menu in Atom add a "Settings" option that calls `atom.workspace.open('atom://config/packages/_package-name_')`.

**Comment by Aerijo** [comment]
Also 
- You can't close the command palette unless the cursor is in the text box
- You can't switch between list views (e.g., command palette to grammar selector) and start using the second view. The cursor will instead type in the editor.

**Comment by gnovaro** [comment]
In project tree, can't order the open projects by name for example. The order is determined by open secuency
