### ISSUE TITLE
1.30.0 bug after placing non-unicode 

### ISSUE THREAD

**Issue by sjaakvlaas** [atom/atom#17980]
*Edit by @rsese to clean up the formatting a bit*

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

## Stack Trace

Uncaught TypeError: Cannot read property 'reset' of null

```
At C:\Users\gebruiker\AppData\Local\atom\app-1.30.0\resources\app\src\tokenized-line.js:20

TypeError: Cannot read property 'reset' of null
    at TokenizedLine.module.exports.TokenizedLine.getTokenIterator (~/AppData/Local/atom/app-1.30.0/resources/app/src/tokenized-line.js:20:39)
    at SymbolStore.recomputeSymbolsForEditorInBufferRange (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/autocomplete-plus/lib/symbol-store.js:156:49)
    at ~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/autocomplete-plus/lib/symbol-provider.js:165:42
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1819:26)
    at later (~/AppData/Local/atom/app-1.30.0/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -0:54.8.0 snippets:expand (input.hidden-input)
     -0:54.8.0 editor:indent (input.hidden-input)
 25x -0:51.7.0 core:backspace (input.hidden-input)
     -0:19.6.0 autocomplete-plus:activate (input.hidden-input)
     -0:18.7.0 snippets:next-tab-stop (input.hidden-input)
     -0:18.7.0 snippets:expand (input.hidden-input)
     -0:18.7.0 editor:indent (input.hidden-input)
     -0:17.6.0 autocomplete-plus:activate (input.hidden-input)
     -0:16.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:16.9.0 snippets:expand (input.hidden-input)
     -0:16.9.0 editor:indent (input.hidden-input)
 11x -0:12.7.0 core:backspace (input.hidden-input)
     -0:07.3.0 autocomplete-plus:activate (input.hidden-input)
     -0:04.5.0 snippets:next-tab-stop (input.hidden-input)
     -0:04.5.0 snippets:expand (input.hidden-input)
     -0:04.5.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
data-atom 0.29.0 
Hydrogen 2.5.1 
open-in-browser 0.5.2 
open-in-browsers 0.0.30 
php-server 0.8.0 
```

### Steps to Reproduce

1. place non unicode character

**Expected behavior:** place the character

**Actual behavior:** place the character+ gives error

**Reproduces how often:** every non unicode character

### Versions

Atom 1.30.0

**OS**: Microsoft Windows 10 Pro

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!  It looks like you didn't go through the `Prerequisites` section, can you reproduce the error in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by rsese** [comment]
Also:

> place non unicode character

Can you share a specific character that will generate the error?

**Comment by Zireael07** [comment]
What is a "Tab"? Please give the character code (0x.....)
