### ISSUE TITLE
Diff lines only change on window focus after commit

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#17994]
_From @DepthDeluxe on July 7, 2014 21:29_

Minor issue but it would be nice if when a user committed files, line diffs were automatically updated as opposed to updating when the window is refocused.

i.e. when I change a line and then commit that change, atom still thinks the line is different than `HEAD` until refocusing the editor.

_Copied from original issue: atom/git-diff#28_

**Comment by maxbrunsfeld** [comment]
_From @izuzak on July 9, 2014 10:59_

I can reproduce this behavior, and I do think that it would be nice to update the editor even though it's not focused. cc @nathansobo for :thought_balloon:

**Comment by maxbrunsfeld** [comment]
_From @benogle on July 9, 2014 18:57_

The issue here is really in atom/atom see [this line](https://github.com/atom/atom/blob/master/src/git.coffee#L82). This would be nice to fix, I agree. 

Right now, changes are detected when the file is [changed or reloaded](https://github.com/atom/atom/blob/master/src/git.coffee#L91). I'm not sure if there are events from git when the status changes.

**Comment by shadow-light** [comment]
Same here.

Ubuntu 16.04
Atom 1.30.0
Electron 2.0.5
Chrome: 61.0.3163.100
Node: v8.9.3

See also https://github.com/atom/tree-view/issues/1240
