### ISSUE TITLE
Editor has crashed on Mac High Sierra 10.13.6 atom vs 1.29.0 and 1.30.0

### ISSUE THREAD

**Issue by CN45** [atom/atom#18009]
*Edit by @rsese to clean up formatting*

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. Open Atom on Mac high Sierra 10.13.6
2. Atom opens and says Editor has crashed, keep it open, reload or close window
3. I tried closing / then reloading, then keep it open.

**Expected behavior:** [What you expect to happen]

I just need atom.io to open and be usable.

**Actual behavior:** [What actually happens]

Nothing, after the window popup that says the editor has crashed.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Atom has not worked in days( about one week)

### Versions

1.29.0
1.30.0

Mac High Sierra 10.13.6 

### Additional Information

---I have tried going through the debugging steps, I tried clear window state, I tried safe mode, I tried rebooting, I deleted atom.io 1.29.0 and installed a newer vs of atom 1.30.0, nothing works. I checked the forum, I Googled atom Editor has crashed, I also tried lookin at my permissions after reading a related person's post that said this fixed the issue. Nothing has worked. Atom is now unusable???? I have attached the latest crash log.
[atom crash report sept 8.txt](https://github.com/atom/atom/files/2363834/atom.crash.report.sept.8.txt)

**Comment by rsese** [comment]
Thanks for the report - just to clarify, Atom worked ok for you previous to version 1.29?

> I have tried going through the debugging steps, I tried clear window state, I tried safe mode, I tried rebooting, I deleted atom.io 1.29.0 and installed a newer vs of atom 1.30.0, nothing works

When you tried these debugging steps, was there any difference at all, or did Atom crash in the same way?  Is Atom crashing after some amount of time, or right away?

Did you also try [temporarily resetting to factory defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults)?

**Comment by CN45** [comment]
That was it. I failed to try that one, I was hoping to not have to reset it back to the default. Just tried it on vs 1.30.0. It now works. Thank you. Closing this now.

**Comment by CN45** [comment]
Factory defaults command worked on vs 1.30.0

**Comment by CN45** [comment]
Atom did not work on 1.29 either.
That was it, I didn’t want to have to do that last one. But I just tried it and it now works.
Thank you.

I closed this issue.
