### ISSUE TITLE
Certain CSS classes in syntax tokens cause issues

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#1800]
Reported in https://github.com/atom/highlights/issues/2

Having a token with a `close` scope generates a `.close` class which makes the text render incorrectly since Bootstrap defined a `.close` class for dialogs.

**Comment by benogle** [comment]
@nathansobo can we close this now?

**Comment by nathansobo** [comment]
Yeah. It's still possible to turn the shadow DOM off but it's not recommended.
