### ISSUE TITLE
Two slightly different background colors in editor (Same as Issue #12634)

### ISSUE THREAD

**Issue by terescode** [atom/atom#18018]
### Prerequisites

- [x] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
- [ ] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
- [ ] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
- [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
- [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Issue #12634 seems to be back on Atom 1.30.0, Mac OS 10.13.6 High Sierra.  Image is below.

![image](https://user-images.githubusercontent.com/21975274/45386158-9e6c4e80-b5e0-11e8-9ab9-a2ad6943a9b5.png)

### Steps to Reproduce

1. Open Atom 1.30.0, Mac OS 10.13.6 High Sierra
2. Use a dark layout

**Expected behavior:**
Text displays with a single background color

**Actual behavior:** 
2 slightly different background colours in one editor (dark and light grey)

**Reproduces how often:**
100%

### Versions

Atom : 1.30.1
Electron: 2.0.5
Chrome : 61.0.3163.100
Node : v8.9.3
OS: Mac OS 10.13.6 High Sierra
MacBook Pro (Retina, 15-inch, Late 2013) (I know, it's old)
2.6 GHz Intel Core i7
16 GB 1600 MHz DDR3
NVIDIA GeForce GT 750M 2048 MB
Intel Iris Pro 1536 MB

### Additional Information

FWIW, this happens on both my external display (apple 27") as well as my built-in retina display.

**Comment by rsese** [comment]
Thanks for the report!  If you update `Settings > Color Profile` to `Use sRGB color profile`, does that make any difference?

**Comment by terescode** [comment]
@rsese that does seem to have resolved the issue!  Thank you!

**Comment by rsese** [comment]
Great, glad this helped you both :+1:

> Is this documented somewhere so others can find it? If not, could you use this ticket to update the doc?

The setting was introduced in 1.28 and we blogged about it:

http://blog.atom.io/2018/06/21/atom-1-28.html#support-for-custom-color-profiles

But I can see it being added to our debugging guide maybe:

https://flight-manual.atom.io/hacking-atom/sections/debugging/

Since the Flight Manual has its own repository, I'll close this and open an issue in https://github.com/atom/flight-manual.atom.io/ with the suggestion.  Pull requests welcome!

**Comment by rsese** [comment]
https://github.com/atom/flight-manual.atom.io/issues/486

**Comment by terescode** [comment]
Perfect, thanks so much!!
