### ISSUE TITLE
Clarify key mapping / add warning for fat-fingered Mac users

### ISSUE THREAD

**Issue by daviwil** [atom/atom#18022]
_From @kevinmickey on May 28, 2016 12:28_

The README states the key-mapping as cmd-alt-q.  I ignorantly/mistakenly used shift-option instead of option.  It turns out that, on a mac, this nearby key-mapping happens to _**force quit all applications and immediately log the user out...**_

Could you add `(or cmd-opt-q on Mac)` to the README?  (I did not use the command palette, which appears to use icons instead of 'alt' or 'opt'.)

Maybe also add a warning for those with fat fingers?

_Copied from original issue: atom/autoflow#49_

**Comment by daviwil** [comment]
_From @ManuelSchneid3r on March 7, 2017 12:34_

Further you could note the default for other platforms.

**Comment by thomasstep** [comment]
I made a PR for this and tried to follow to contributing guidelines as closely as I could. Any feedback is welcome.

**Comment by lee-dohm** [comment]
On review with the team, we've decided that we're not going to accept this change. We don't believe that duplicating macOS key bindings containing `alt` with ones that contain `opt` is going to make our README's or other documentation easier to follow on the whole. Additionally, there are many key bindings that, when mistyped, could have unforeseen consequences. There are hundreds of key bindings in Atom and placing and maintaining caveats on all the possible ways they could be mistyped is not something we want to take on.

Thanks for the suggestion and thank you @thomasstep for the help :bow:
