### ISSUE TITLE
Cannot autoflow JSDoc comments

### ISSUE THREAD

**Issue by daviwil** [atom/atom#18021]
_From @onury on June 12, 2016 18:6_

``` js
/**
 * Atom autoflow test. Cannot autoflow JSDoc comments.
 *
 * @readonly
 * @private
 */
```

this is autolowed into this :(

``` js
/**
 /** /** * Atom autoflow test. Cannot autoflow JSDoc comments. * * @readonly * /**
/**
 @private */
```

Atom v1.8.0
Mac OS X 10.11.5

_Copied from original issue: atom/autoflow#52_

**Comment by daviwil** [comment]
_From @50Wliu on December 21, 2017 4:15_

Current situation:
```js
/** * Atom autoflow test. Cannot autoflow JSDoc comments. * * @readonly *
/*@private */
```

@onury what what you expect the result to be if it worked correctly?

**Comment by daviwil** [comment]
_From @onury on December 21, 2017 10:31_

wow. I don't even remember I opened an issue here.
It should not alter the format if shorter than the max. width.
If longer, it should keep the [JSDoc style](http://usejsdoc.org/about-getting-started.html).

```js
/**
 * Atom autoflow test. Cannot autoflow JSDoc comments.
 *
 * @readonly
 * @private
 */
```
Above should remain the same.

```js
/**
 * Atom autoflow test. Longer than maximum width for example 80 chars. But this has 100 characters.
 *
 * @readonly
 * @private
 */
```
Above should be formatted to:
```js
/**
 * Atom autoflow test. Longer than maximum width for example 80 chars. But this 
 * has 100 characters.
 *
 * @readonly
 * @private
 */
```

**Comment by daviwil** [comment]
_From @matthewwithanm on January 5, 2018 19:45_

Would love to see this fixed!

**Comment by matthewwithanm** [comment]
We (the Nuclide team) continue to get complaints about this. (:

**Comment by PrimerMediaGroup** [comment]
[lockbot]
