### ISSUE TITLE
keyboard input is broken for tooltips.

### ISSUE THREAD

**Issue by annthurium** [atom/atom#18041]
### Description

Cannot use keyboard input on tooltips.

This is impacting teletype, the git branch menu, probably others.

It's related to https://github.com/atom/atom/pull/17651 and https://github.com/atom/atom/pull/17958

### Steps to Reproduce

1. Install nightly build.
2. Open git branch menu and try to create a new branch.
3. [and so on...]

**Expected behavior:** 

You should be able to type a new branch name.

**Actual behavior:** 

When you type a new branch name, the tooltip disappears.

**Reproduces how often:** 

100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lee-dohm** [comment]
Looks like this was fixed in #18044 :tada:
