### ISSUE TITLE
Js For of loop error in atom

### ISSUE THREAD

**Issue by axe-z** [atom/atom#18056]
Simple, latest version 1.30

for loop, 
the for of autocompletes (without any added snippets) this: 

 for (variable of iterable) {
   
 }

always f...s me up later. 

should be
 for (LET variable of iterable) {
   
 }

how can I correct the built in stuff ?

**Comment by danPadric** [comment]
Hello.

Best to ask your question here: 
 https://discuss.atom.io/

The path to your answer is documented here:
  https://flight-manual.atom.io/using-atom/sections/snippets/

You will be welcome at the community forum even if you still have doubts.

Best regards.

**Comment by axe-z** [comment]
this is not a question. It's a bug.

**Comment by 50Wliu** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/language-javascript repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us half way :+1:
