### ISSUE TITLE
Whitespace bug with files created by Visual Studio except for project and solution files.

### ISSUE THREAD

**Issue by HighwayStar54** [atom/atom#18052]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Any file I open that is a .cpp or .h file, will have this awkward spacing for every character. Those are actual "physical" spaces and can be removed to achieve normal spacing.
![immagine](https://user-images.githubusercontent.com/25094434/45554330-79ded380-b879-11e8-8621-6dbf7193d6f0.png)
![immagine](https://user-images.githubusercontent.com/25094434/45554794-89aae780-b87a-11e8-9e1d-03bf0f5670eb.png)
_Note: I removed the first two question marks from the first picture, they are visible in the second._

### Steps to Reproduce

1. Create a new project in VS
2. Edit it in any way.
3. Save and open in atom.

**Expected behavior:** [What you expect to happen]
Files should look like they do in other text editors.

**Actual behavior:** [What actually happens]
Files have a whitespace for every character. Spaces can be edited and saving the files applies the bug to the file and will be visible in every other editor, although otherwise it only appears in atom.
This seems to affect only files that are created with VS and are meant to be edited, for example, project files, solution files and XML files are viewed correctly. Editing files that were not created with Visual Studio and saving doesn't seem to trigger it, it has to be created from VS.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime I open a file created from VS2017.
### Versions

```
C:\Windows\System32>atom --version
Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
C:\Windows\System32>apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0
python
git
visual studio
```

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Windows 10 64-bits

**Comment by Arcanemagus** [comment]
This is actually due to two things:
* It seems that VS2017 for some bizarre reason is saving those files as UTF-16, even though virtually everything else uses UTF-8.
* The `encoding-selector` package currently can't auto-detect UTF-16 files, so it is defaulting to UTF-8

You can work around this by manually selecting UTF-16 in the bottom right of the status bar.

Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/encoding-selector repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us halfway :+1:

**Comment by HighwayStar54** [comment]
Thanks to you! I'll open a repository there as soon as I can.
