### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by charchas** [atom/atom#18050]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:1017

Error: Pane has been destroyed
    at Pane.activate (/Applications/Atom.app/Contents/Resources/app/src/pane.js:1017:41)
    at NotificationElement.module.exports.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:316:46)
    at NotificationElement.module.exports.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:272:27)
    at NotificationElement.module.exports.NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:277:18)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/notifications/lib/notification-element.js:156:30)
```

### Commands

```
     -5:21.2.0 core:copy (input.hidden-input)
     -5:21 core:paste (input.hidden-input)
     -5:21 editor:newline (input.hidden-input)
     -5:20.8.0 core:paste (input.hidden-input)
     -5:20.4.0 editor:newline (input.hidden-input)
     -5:17.7.0 core:save (input.hidden-input)
     -4:57.8.0 core:delete (input.hidden-input)
     -4:54.1.0 snippets:next-tab-stop (input.hidden-input)
     -4:54.1.0 snippets:expand (input.hidden-input)
     -4:54.1.0 editor:indent (input.hidden-input)
  3x -2:39.9.0 core:backspace (input.hidden-input)
  3x -2:34.1.0 core:delete (input.hidden-input)
     -2:31.6.0 core:save (input.hidden-input)
  2x -2:19.8.0 core:delete (input.hidden-input)
 18x -2:18.6.0 core:save (input.hidden-input)
  2x -0:31 tabs:close-all-tabs (div.title.icon.php-icon.dark-blue)
```

### Non-Core Packages

```
atom-beautify 0.33.1 
autoprefixer 3.7.1 
file-icons 2.1.24 
git-control 0.9.0 
minimap 4.29.8 
php-twig 4.0.0 
seti-ui 1.11.0 
structure-view 0.2.1 
sync-settings 0.8.6 
tree-view-autoresize 2.3.0 
tree-view-extended 2.1.0 
tree-view-git-status 1.5.2 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

Couple of issues with similar stack traces but closed x-ref: https://github.com/atom/notifications/issues/174, https://github.com/atom/atom/issues/16909

**Comment by Tessag159** [comment]
Hi!

I received an error in Atom, and the pane that pops up brings me here. I know it states that this is closed, but I have the answers to your questions above.
This is the error report:

[Enter steps to reproduce:]

1. Split the active window into two panes, top and bottom
2. Set the window to have a file in the bottom pane and not the top
3. Attempt to drag-and-drop said file to the top pane
4. Error is thrown
5. Error is also thrown when moving pane from top -> bottom rather than bottom -> top, except I can't get rid of the error message when I go in this direction. It's a continual loop.

This error happens every single time I attempt this, even after doing a full reboot of everything including my device itself. I don't see the error when using atom --safe, but then again when I'm using that the instant I try and have an empty pane it deletes the pan so I can't really reproduce the exact steps. I can, however, move and re-arrange my panes completely normally in atom --safe

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Linux Mint
**Thrown From**: Atom Core


### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /usr/share/atom/resources/app/static/<embedded>:11

Error: Pane has been destroyed
    at Pane.activate (/usr/share/atom/resources/app/static/<embedded>:11:460751)
    at HTMLElement.handleDrop (/app.asar/src/pane-element.js:62:23)
```

### Commands

```
     -2:20.1.0 editor:move-to-end-of-word (input.hidden-input)
     -2:19 core:move-right (input.hidden-input)
     -2:18.7.0 core:move-left (input.hidden-input)
     -2:18.5.0 core:move-right (input.hidden-input)
     -2:18.4.0 core:move-left (input.hidden-input)
     -2:18.2.0 core:move-right (input.hidden-input)
     -2:18.2.0 core:move-left (input.hidden-input)
     -2:15.9.0 window:focus-pane-on-right (input.hidden-input)
     -2:13.4.0 window:focus-pane-below (input.hidden-input)
     -2:13.1.0 editor:move-line-down (input.hidden-input)
     -2:12 window:focus-pane-above (input.hidden-input)
     -2:09.1.0 window:focus-pane-below (input.hidden-input)
     -2:08.4.0 window:focus-pane-on-right (input.hidden-input)
     -2:07.7.0 window:focus-pane-above (input.hidden-input)
     -2:07.0 window:focus-pane-on-right (input.hidden-input)
     -1:16.9.0 tabs:close-all-tabs (li.texteditor.tab.sortable.active.modified.right-clicked)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
autoclose-html 0.23.0 
better-window-title 1.0.3 
color-picker 2.3.0 
css-comb 2.5.0 
css-grid-snippets 1.1.1 
css-specificity 0.2.2 
emmet 2.4.3 
expose 0.15.0 
file-icons 2.1.26 
git-time-machine 2.1.0 
highlight-selected 0.14.0 
KeyCount 0.2.0 
less-than-slash 0.18.0 
material-syntax 0.6.1 
material-ui 1.0.10 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
pane-status-bar 0.1.0 
pigments 0.40.2 
rainbow-windows 0.3.0 
teletype 0.13.3 
todo-show 2.3.2 
wakatime 7.0.7 
window-focus 0.2.0 
```

**Comment by rsese** [comment]
Thanks @Tessag159 -

> I don't see the error when using atom --safe, but then again when I'm using that the instant I try and have an empty pane it deletes the pan so I can't really reproduce the exact steps. I can, however, move and re-arrange my panes completely normally in atom --safe

If you don't see the behavior in safe mode, then one of your community packages is likely causing the issue (I'm unable to reproduce as described in safe mode).  About this bit:

> but then again when I'm using that the instant I try and have an empty pane it deletes the pan so I can't really reproduce the exact steps

If you uncheck `Settings > Core > Remove Empty Panes`, Atom won't auto-close a pane that's empty.  If you uncheck this setting and can still reproduce in safe mode with your repro steps, let me know.

**Comment by Tessag159** [comment]
Nope. Unchecked that setting and retried in safe mode, but couldn't reproduce. Now it's just a matter of figuring out which community package it is that is causing the issue.

Thank You.
