### ISSUE TITLE
Step-through module loading on startup

### ISSUE THREAD

**Issue by jrial** [atom/atom#18064]
## Summary

It would be nice if Atom would support a startup mode that requests confirmation for each module being loaded. It would be a sort of diagnostic mode in between safe mode (no module loading) and normal mode (all modules loaded, you have no idea which one caused a particular issue).

## Motivation

When reporting issues, users are asked to see if the issue manifests itself in safe mode. If not, it's assumed that a particular module is responsible for the misbehaviour. Pinpointing which one though requires one to disable all their installed modules, and enabling them one by one, often combined with a restart for issues that only manifest themselves at startup.

If there was a third startup mode that would ask for confirmation for every module being loaded, it would be easier to spot which module is responsible for the behaviour.

As a practical example: my folds are usually not preserved during restart. I currently have 54 active community packages, 79 core packages, and 1 development package installed. Figuring out which package is responsible for expanding the folds on startup would require me to perform 134 restarts of Atom, which we need to multiply with a certain number since the issue does not always manifest itself. A confirmation dialog before every module load would allow me to pinpoint the misbehaving package with far less work and far less restarts.

## Describe alternatives you've considered

Can't come up with any alternatives that would solve this, but I'm open to ideas/discussion to identify a good solution that hopefully doesn't require too much work to implement.

## Additional context

N/A

**Comment by rsese** [comment]
Thanks for the detailed suggestion @jrial :v:  Though the details of how to do it differ where your suggestion is:

> a startup mode that requests confirmation for each module being loaded. 

and the suggestion in https://github.com/atom/atom/issues/2357 is:

>  It would launch Atom, then when Atom exits it could ask for "good", "bad", "reset" or "quit". It would perform a binary search of the packages until only one package is left and is marked bad (the most likely scenario) telling the user which package it is.

I think the main idea is the same where it would be useful to have another mode to help debugging whether a community package is causing a particular problem and we can close this in favor of #2357.  What do you think?

**Comment by jrial** [comment]
@rsese that actually makes a lot of sense. It didn't occur to me to apply bisection to this problem. Closing in support of lee-dohm's proposal. Thanks a bundle for pointing me in that direction.
