### ISSUE TITLE
Git diff : Sometimes, modifying a file and reversing the modification does not remove the diff.

### ISSUE THREAD

**Issue by glemiere** [atom/atom#18076]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
The Git diff features sometimes fails to shows no differences after reversing modifications.

### Steps to Reproduce

1. [Clone a git repository]
2. [Open the project in Atom]
3. [Modify a file]
4. [Save the file]
5. [Reverse the modifications (using ctrl/cmd + z)]
6. [Save the file]
7. [Repeat until diff fails to show no colors]

**Expected behavior:** [What you expect to happen]
The Git diff feature should not show any difference when there are no differences.

**Actual behavior:** [What actually happens]
The Git diff feature sometimes shows differences when there are none.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Easily 40%-60%.

### Versions
Atom 1.30.0
OSX High Sierra (10.13.6)

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Sorry, just to confirm, you're talking about the diff shown by the https://github.com/atom/github/ package or the colors shown in the gutter (i.e. https://flight-manual.atom.io/using-atom/sections/version-control-in-atom/#line-diffs)?

**Comment by glemiere** [comment]
@rsese I haven't had the time to look into the prerequisites further, so no I did not reproduce this in safe mode.

**How many times do you need to repeat before you see the problem?**
To answer your question, I usually don't need to repeat it. It bugs almost all the time, but sometimes the diff disappear when I reverse my modifications as it should.

**Can you only reproduce in a particular project, or can you also reproduce on a simple test repository with a single file?**
This problems affects every repositories, no exception.

I'll come back here to post a gif for you when I'm done with my day ;-)
Thanks for this fast reply!
