### ISSUE TITLE
Proxy settings are not respected in some places

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1807]
Noticed two Halp tickets about this so far:
- support/a10f96d4b08f11e3934b3dfc0d230d46
- support/45b5441aa86911e39c8bef69aceed9d5

> Finally, I didn't find any way to set my proxy info in the settings of your app, and I'm not sure you are respecting the proxy settings of the OS. So my first attempt to send feedback failed.

...

> I tried to submit this via the built-in feedback but it didn't say it was successful, it seemed to time out just like fetching packages or themes:
> Built-in package and theme fetching doesn't work when proxies are required. "Fetching featured packages and themes failed. connect ENETUNREACH". DNS resolves on this corporate network, but connections must use http or https proxies.
> Self-updating Atom itself works.

So, it seems that proxy settings are not respected, and it's not possible to set them in Atom.

**Comment by JPvRiel** [comment]
@duncanmapes ```strict-ssl = false``` implies being insecure and not validating TLS?

**Comment by damieng** [comment]
Atom automatically sets the environment variables when calling out to apm itself in 1.14 and beyond.

**Comment by tiankongmumian** [comment]
My problem is still unsolved！！！

**Comment by damieng** [comment]
Please open a new issue with the details necessary to investigate.
