### ISSUE TITLE
APM - Cannot Uninstall Packages - Atom v2.0.5 64

### ISSUE THREAD

**Issue by SkateDude** [atom/atom#18089]
Hello,

In apm i did -> apm list and the following packages appeared: 
Built-in Atom Packages (92)
├── atom-dark-syntax@0.29.0
├── atom-dark-ui@0.53.2
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.2
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.12.4
├── one-light-ui@1.12.4
├── one-dark-syntax@1.8.4
├── one-light-syntax@1.8.4
├── solarized-dark-syntax@1.1.5
├── solarized-light-syntax@1.1.5
├── about@1.10.0
├── archive-view@0.65.1
├── autocomplete-atom-api@0.10.7
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.4
├── autocomplete-plus@2.40.7
├── autocomplete-snippets@1.12.0
├── autoflow@0.29.4
├── autosave@0.24.6
├── background-tips@0.28.0
├── bookmarks@0.45.1
├── bracket-matcher@0.89.2
├── command-palette@0.43.5
├── dalek@0.2.2
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.9
├── exception-reporting@0.43.1
├── find-and-replace@0.215.12
├── fuzzy-finder@1.8.2
├── github@0.18.3
├── git-diff@1.3.9
├── go-to-line@0.33.0
├── grammar-selector@0.50.1
├── image-view@0.63.0
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.2
├── line-ending-selector@0.7.7
├── link@0.31.4
├── markdown-preview@0.159.20
├── metrics@1.6.1
├── notifications@0.70.5
├── open-on-github@1.3.1
├── package-generator@1.3.0
├── settings-view@0.255.0
├── snippets@1.3.3
├── spell-check@0.74.0
├── status-bar@1.8.15
├── styleguide@0.49.11
├── symbols-view@0.118.2
├── tabs@0.109.2
├── timecop@0.36.2
├── tree-view@0.222.0
├── update-package-dependencies@0.13.1
├── welcome@0.36.6
├── whitespace@0.37.6
├── wrap-guide@0.40.3
├── language-c@0.60.0
├── language-clojure@0.22.7
├── language-coffee-script@0.49.3
├── language-csharp@1.0.4
├── language-css@0.42.11
├── language-gfm@0.90.5
├── language-git@0.19.1
├── language-go@0.46.0
├── language-html@0.51.1
├── language-hyperlink@0.16.3
├── language-java@0.30.0
├── language-javascript@0.129.1
├── language-json@0.19.2
├── language-less@0.34.2
├── language-make@0.22.3
├── language-mustache@0.14.5
├── language-objective-c@0.15.1
├── language-perl@0.38.1
├── language-php@0.44.0
├── language-property-list@0.9.1
├── language-python@0.51.2
├── language-ruby@0.72.2
├── language-ruby-on-rails@0.25.3
├── language-sass@0.62.0
├── language-shellscript@0.27.0
├── language-source@0.9.0
├── language-sql@0.25.10
├── language-text@0.7.4
├── language-todo@0.29.4
├── language-toml@0.18.2
├── language-typescript@0.4.0
├── language-xml@0.35.2
└── language-yaml@0.32.0

An then i did: 
apm uninstall metrics
Uninstalling metrics ✗
Failed to delete metrics: Does not exist

and also:
apm uninstall metrics@1.6.1
Uninstalling metrics@1.6.1 ✗
Failed to delete metrics@1.6.1: Does not exist

My question is how can i delete a package in apm in Atom?

Thanks.

**Comment by Aerijo** [comment]
The `metrics` package is built in, and buried deep within the Atom application itself. The best you can do is disable it, as with all built in packages.

If you try with a community package, it should work (though I couldn't see any scanning the list just now).

If you really want it gone, you could customise and build Atom from source. But that would be over the top IMO.

**Comment by rsese** [comment]
I didn't spot any community package either, but you can list just your community packages with `apm list --installed --packages` if you want to check for community packages that you might want to uninstall.

Otherwise, you can't delete core packages like that with `apm` (in the Settings view, there's no   Uninstall button for core packages) like @Aerijo mentioned.  If you want to open an issue suggesting that the error message should be improved when trying to delete a core package, you can do that in https://github.com/atom/apm/ but please use the issue template.

If you have trouble deleting community package with `apm`, feel free to reach out on the [message board](https://discuss.atom.io/).
