### ISSUE TITLE
Font increase/decrease hotkeys don't change file manager pane

### ISSUE THREAD

**Issue by iandouglas** [atom/atom#18090]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using Cmd+ and Cmd- in Atom on a Mac increases the main code editor font size but not the file manager pane.

### Steps to Reproduce

1. Start Atom, open a project
2. Hold down Cmd and press + or -
3. Notice how the main editor pane increases and decreases the font, but the file manager pane does not

**Expected behavior:**

I'd expect that increasing/decreasing the font size would affect all panes

**Actual behavior:**

Nothing at all

**Reproduces how often:**

100% reproducable

### Versions

All

### Additional Information

Nothing special needed

**Comment by lee-dohm** [comment]
Thanks for reaching out.

This is intentional. The <kbd>Cmd+plus</kbd> and <kbd>Cmd+minus</kbd> keys control the editor font size and do not scale the UI as in Chrome. If you want to scale the UI, then you can use `window.setZoomFactor()` from the Developer Tools console. If you want to scale the font size in other areas of the UI, I have [an example of how to do so from your style sheet in my dotfiles](https://github.com/lee-dohm/dotfiles/blob/99f368bde3031e7f6a064c37dddbed4d77f727a6/atom/styles.less#L9-L24).

**Comment by iandouglas** [comment]
I understand now that this is intentional and not a bug, but it's not great UX for users with visual impairments who need to scale everything without fiddling with the innards of the editor. Should I reopen as a feature request?

**Comment by lee-dohm** [comment]
@iandouglas You can use the [atom-scale-factor package](https://atom.io/packages/atom-scale-factor) or use that as a basis for overriding the built-in keys to work as you expect.

**Comment by iandouglas** [comment]
I won't belabor the point and appreciate you linking to a plugin.

I do feel strongly, though, that this should be built into the editor, not an add-on that users have to seek out and install. It's a much better user experience for people with visual impairments that they can use the Cmd +/- hot keys and see *everything* increase/decrease "out of the box."

**Comment by lee-dohm** [comment]
We appreciate the feedback.

Let me ask you this. Given that it is unlikely that we would change the meaning of <kbd>Cmd +/-</kbd> so as not to disrupt the expected function for existing users, would it be useful to have a slider in the Settings View that allowed one to set a zoom factor between X and Y? (In other words, no hot keys.)

**Comment by iandouglas** [comment]
I can't speak for all visually impaired folks. For my own use cases, I'd prefer it to be linked to the hot keys instead of a slider since I go back and forth between zoomed in and not zoomed in at all. As a visually impaired developer, though, having to navigate through settings windows to find out how to zoom things could be problematic if zooming doesn't also zoom settings windows, etc..

(I teach software development and being able to zoom in on the file manager is helpful to show my students where to put files, but since I've also been involved in web accessibility I also see how this would be helpful for visually impaired folks who wish to use Atom, which is why I've presented the problem space as such)

**Comment by lee-dohm** [comment]
My proposed slider would be to zoom the entire UI. Thanks again for the feedback :+1:
