### ISSUE TITLE
Crashes every time on Windows 8.1 x64

### ISSUE THREAD

**Issue by itspramod21** [atom/atom#18101]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom 1.30.0 crashes within few seconds after launch on Windows 8.1 x64.

### Steps to Reproduce

1. Launch Atom 1.30.0
2. Wait for up to 30 seconds
3. It crashes.

**Expected behavior:** 
Not to crash every time.

**Actual behavior:**
Crashes every time.

**Reproduces how often:** 
100% of the times

### Versions
Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.30.0
python 3.6.5
git 2.16.1.windows.4
visual studio 2015

You can get this information from copy and pasting the output of `
atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information
[operation_log.txt]
(https://github.com/atom/atom/files/2415861/operation_log.txt)

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by itspramod21** [comment]
Yes. Crashes in safe mode too.
Did not try factory reset.. I will try that out and post back.

Regards,Pramod

Sent from Yahoo Mail on Android 
 
  On Wed, Sep 26, 2018 at 12:34 AM, Landon Abney<notifications@github.com> wrote:   
Do you see this when launching in Safe Mode? If so, can you see if Resetting to Factory Defaults helps?

**Comment by danPadric** [comment]
[ WARNING: do not read this as an official response ]
[ Feel free to ignore the notes that follows ]

Would you be a good sport and create a `portable version`? 
Instructions: https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode
The best is to make a separate `.atom` directory too. All this can be done on a USB key or external drive.

Back to the install you have now, a few diagnostic questions - please:
1. Have you used Atom before?

2. Did you have this problem since the beginning?

3. Where did you get the install file - which one did you use?

4. Do you have any other Electron applications installed?

5. You mention that crashing behaviour happens when the file is opened. Is this file opened from inside Atom or from example Windows File Explorer?

6. What happens if you open a TXT file?

7. What happens when..
    a) open Atom from the command line: `atom --clear-window-state`
    b) start writing python code text
    c) save file as `myfile.noname`  -- result 1
    d) save file as `myfile.txt` -- result 2
    d) <kbd>Ctrl-l</kbd> Change grammar to Python -- result 3
    d) save file as `myfile.py` -- result 4

**Comment by justin-s26** [comment]
Sounds very similar to my problem. Did you had any kind of success?

**Comment by itspramod21** [comment]
Nope.. not yet.

Regards,Pramod

Sent from Yahoo Mail on Android 
 
  On Fri, Sep 28, 2018 at 3:45 PM, justin-s26<notifications@github.com> wrote:   
Sounds very similar to my problem. Did you had any kind of success?

**Comment by itspramod21** [comment]
Thanks..
Would you be a good sport and create a portable version? --- will try this out and keep you posted.


1.   Have you used Atom before? -- No. First time.

2.   Did you have this problem since the beginning?  -- Yes. Since first install.
3.   Where did you get the install file - which one did you use? -- From atom.io -- Windows | For 64-bit Windows 7 or later [AtomSetup-x64.exe].
4.   Do you have any other Electron applications installed?  Guess, none.
5.   You mention that crashing behaviour happens when the file is opened. Is this file opened from inside Atom or from example Windows File Explorer?  --  Even if atom is kept open/ idle for a few seconds, it crashes.   
   -    
What happens if you open a TXT file? --  crashes too soon.

   -    
What happens when..  -- all below, crashes too soon.

   -    
a) open Atom from the command line: atom --clear-window-state --- no luck.   
b) start writing python code text   
c) save file as myfile.noname -- result 1   
d) save file as myfile.txt -- result 2   
d) Ctrl-l Change grammar to Python -- result 3   
d) save file as myfile.py -- result 4





Best Regards,Pramod 

    On Thursday, September 27, 2018, 2:18:55 AM GMT+8, danPadric <notifications@github.com> wrote:  
 
 
[ WARNING: do not read this as an official response ]
[ Feel free to ignore the notes that follows ]

Would you be a good sport and create a portable version?
Instructions: https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode
The best is to make a separate .atom directory too. All this can be done on a USB key or external drive.

Back to the install you have now, a few diagnostic questions - please:
   
   -    
Have you used Atom before?

   -    
Did you have this problem since the beginning?

   -    
Where did you get the install file - which one did you use?

   -    
Do you have any other Electron applications installed?

   -    
You mention that crashing behaviour happens when the file is opened. Is this file opened from inside Atom or from example Windows File Explorer?

   -    
What happens if you open a TXT file?

   -    
What happens when..   
a) open Atom from the command line: atom --clear-window-state   
b) start writing python code text   
c) save file as myfile.noname -- result 1   
d) save file as myfile.txt -- result 2   
d) Ctrl-l Change grammar to Python -- result 3   
d) save file as myfile.py -- result 4

**Comment by itspramod21** [comment]
I tried this creating a portable version.

Win8.1 would not let me create a folder name that starts with a dot (.).

---it turns out the first time, I opened two .py files, it was fine, no crashes.
---then I opened the third .py file and after few seconds, it crashed.
---reopened Atom and opened other two .py files and also one that happened to cause the editor to crash, all OK.... and then it crashed after like 2 - 3 minutes.

Hope this was helpful.  Thanks.

**Comment by itspramod21** [comment]
> Hello.
> 
> > Hope this was helpful. Thanks.
> 
> Thank you for taking the time to answer! I also hope the contributors can use this information. I am sorry that a clear path is not there yet.
> 
> > Win8.1 would not let me create a folder name that starts with a dot (.)
> 
>> Create the folder name as `.atom.` (two dots). This will create the folder `.atom` that we seek. I feel that it is kind of important as this will exclude windows-user-name issues. Please use the newest Atom version.
>
> Created .atom. folder and it kinda appeared to work fine, but then after few minutes/ reopening the editor, it started to crash.
>

> If you feel adventurous and web capacity, you could try an older version also. Perhaps... https://github.com/atom/atom/releases/tag/v1.25.1
>
>Installed v1.25.1;  yet crashed.   I'm guessing its something to do within my machine in this case.
>
> 
> One suggestion that I have left out - - Please check your anti-virus / security application. Check to see if there are any reports of functionality being blocked.
> 
> Again thank you for your co-operation.
> Good luck.

**Comment by justin-s26** [comment]
Do you have an ".git" folder? I read about that issue, but it was fixed before. But because thse issues where very similar to my problems I searched for the ".git" folder, but could not find it until I searched through the explorer. I found out that it was hidden, so not visible in cmd. Maybe you should look that up. It helped for me. I hope this is a kind of helpful :smile:

**Comment by justin-s26** [comment]
I forgot to say what you should do if you find it :laughing: . If so rename it. For example ".git_save" or something like that.
