### ISSUE TITLE
Atom issues with mohave 10.14 

### ISSUE THREAD

**Issue by axe-z** [atom/atom#18100]
latest: 1.30 

Font on Atom is noe weird since my update, and dark mode on hi dpi. 
10.13
![capture d ecran 2018-09-20 a 16 00 41](https://user-images.githubusercontent.com/27289270/46010221-e040ce80-c08f-11e8-8dae-f89eea581baa.png)

10.14
![capture d ecran le 2018-09-25 a 06 54 36](https://user-images.githubusercontent.com/27289270/46010250-fcdd0680-c08f-11e8-97ff-6350570ce725.png)

thinner font .

**Comment by daviwil** [comment]
@axe-z this command should resolve it for you:

```
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
```

Run that, restart Atom and check the fonts again.

See also: https://github.com/atom/atom/issues/17486#issuecomment-424140110

**Comment by joshhepworth** [comment]
Is there a solution to this that doesn't involve changing a global configuration option for every app? The same fonts are rendering ok in apps like Sublime Text without making the above change.

**Comment by daviwil** [comment]
Not yet, there would likely have to be a change to Electron itself to resolve this.  The upside of this workaround is that you can try it and then change it back to the old setting if it affects other apps negatively.

**Comment by axe-z** [comment]
tks, I 'm a bit worried when it's -global, but what the heck... It did fix the smoothing.
