### ISSUE TITLE
Display issues using Mojave through Parallels VM

### ISSUE THREAD

**Issue by hahntech** [atom/atom#18109]
### Prerequisites

* [instructions for starting in safe mode do not work. No such command ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Running macOS Mojave 10.14 through Parallels VM. (both Parallels 13 and 14)

### Steps to Reproduce

1. Download and install free trial of Parallels 14. 
2. Download Mojave from App store
3. Create new Parallels VM using Mojave install file
4. Download and install Atom
5. Open Atom

**Expected behavior:** Expected to be able to view welcome screen, open and view preferences, create and edit new documents

**Actual behavior:** Completely blank screen. Some of the contents of the welcome screen will appear as you move the mouse across the app window. But those areas disappear as soon as the mouse moves out of range.

**Reproduces how often:** 100% of the time. I have never been able to get it to display correctly.

### Version is current one available from the site: https://atom.io/ and the version number cannot be displayed due to this issue.

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. (as mentioned previously, this does not work. command not found)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report - do you have the same issue with other Electron applications or just Atom?  

> instructions for starting in safe mode do not work. No such command

Do you mean that you can't run `atom` from Terminal because you get a command not found error?

**Comment by hahntech** [comment]
I have not tried any other Electron based applications. In fact I am not aware of any. So please recommend one or two I might try. As to starting in safe mode. I contacted a friend and they explained that I needed to find the menu option "Install Shell Commands". Once I did that I was able to start it in safe mode and it produced the same issues.

**Comment by hahntech** [comment]
Update. You asked if these was impacting any other Electron applications. A friend of mine suggest Skype as one application I could test. And indeed Skype is affected in the very same way as Atom. Please advise of next steps for further troubleshooting or resolution. Thanks!

**Comment by hahntech** [comment]
Yes, in a previous reply I stated that a friend of mine explained how to enable shell commands. Running Atom from terminal using that command does solve the issue. This does not correct the many other **apps that are experiencing similar issues. I had a support session with Parallels yesterday. They connected to my computer remotely and collected some technical data. They are passing this on to their internal group for review. I'll keep you posted. I'm really skilled at working out issues on my own. By the time I contact support it always gets kicked up to the next level. 

**Yes, you are probably asking about those other apps experiencing similar issues. So far I have found that Skype is behaving exactly the same. Chrome is experiencing sporadic issues. Thinkorswim loads but the login screen is completely invisible. I am happy to test others if this gets us closer to understanding the root cause.

**Comment by fredngo** [comment]
Just reporting the same for me. `atom --disable-gpu` still results in a blank screen.

<img width="1524" alt="Screen Shot 2019-08-20 at 10 54 19 AM" src="https://user-images.githubusercontent.com/11791/63358356-e8090180-c338-11e9-9189-61d3ecafaeff.png">
