### ISSUE TITLE
Atom fullscreen freeze

### ISSUE THREAD

**Issue by tim2CF** [atom/atom#18108]
### Description

Atom freezes when the project is opened in full-screen mode.

<img width="1440" alt="screen shot 2018-09-26 at 00 58 56" src="https://user-images.githubusercontent.com/33688567/46046294-33b32b00-c129-11e8-8a1f-9759d478dc3a.png">

MacBook : Pro (13-inch, 2016)
MacOS : 10.13.6
Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Steps to Reproduce

```
cd ./my_project
atom .
⌃⌘F
⌘Q
atom .
```

**Expected behavior:** Project will be opened in fullscreen 

**Actual behavior:** Atom process freezes and not responding

**Reproduces how often:** always

**Comment by rsese** [comment]
Thanks for the report - it looks like the `Prerequisites` section of the issue template was removed, did you try [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) or any of the other [debugging steps](https://flight-manual.atom.io/hacking-atom/sections/debugging)?

I was unable to reproduce on macOS 10.12.6 with 1.33.0-nightly0.
