### ISSUE TITLE
Mojave Dark Mode title bar

### ISSUE THREAD

**Issue by dapetcu21** [atom/atom#18111]
## Summary

When using the native title bar in Mojave's Dark Mode, the title bar should be dark. It should be a simple `NSRequiresAquaSystemAppearance` set to `NO` in `Info.plist`.

## Motivation

Atom should fit in with the colour scheme of the rest of the system. Plus, Dark Mode looks super sleek.

## Describe alternatives you've considered

The only way I found to make this work was to edit `Info.plist`.

## Additional context

Here's how it looks when I edited `Info.plist` to add that key:

<img width="1552" alt="screenshot 2018-09-26 at 13 50 05" src="https://user-images.githubusercontent.com/428060/46075408-19159c00-c193-11e8-8254-073f6aa5dedf.png">

**Comment by rlancaste** [comment]
Thanks for posting the tip!  That will help us with KStars

**Comment by StormyMods** [comment]
Nice find.  Can you post a detailed tutorial on how to do this?

**Comment by cpoetter** [comment]
1. Close Atom
2. Find the **Atom.app** in your Application folder
3. Right click on Atom.app
4. Click on **Show Package Contents**
5. Open the folder **Contents**
6. Open **Info.plist** with your preferred editor
7. Replace
```
</dict>
</plist>
```
at the end of the file with 
```
	<key>NSRequiresAquaSystemAppearance</key>
	<string>NO</string>
</dict>
</plist>
```
8. Save and enjoy **Dark Mode**

**Comment by dapetcu21** [comment]
I have this in my `.zshrc` until all the apps I use update with support for Dark Mode:

```
enable-dark-mode() {
  defaults write "${1}/Contents/Info.plist" NSRequiresAquaSystemAppearance false
}
disable-dark-mode() {
  defaults delete "${1}/Contents/Info.plist" NSRequiresAquaSystemAppearance
}
```
Use like this:
```
enable-dark-mode /Applications/Atom.app
```

**Comment by duurkak** [comment]
The above-mentioned methods are not a permanent solution. The Info.plist file is overwritten when updating from the Atom menu. Each time the update is done, the white bar returns.

**Comment by eugenet8k** [comment]
Is this problem will be fixed in the actual Atom source code? Do you guys know if anyone is working on this?

**Comment by triangulum** [comment]
Aye, the workaround works, but it'd be nice if this were default functionality.

**Comment by vonerval** [comment]
This is the most simple workaround:
defaults write com.github.atom NSRequiresAquaSystemAppearance 0

**Comment by daviwil** [comment]
Coming in Atom 1.36.0-beta0 in February :tada: https://github.com/atom/atom/pull/18761
