### ISSUE TITLE
Atom doesn't remember changed settings

### ISSUE THREAD

**Issue by p-boiko** [atom/atom#18118]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom doesn't remeber or store changed settings

### Steps to Reproduce

1. Change any editor setting
2. Close the application
3. Open application and check the setting

**Expected behavior:** The setting should be remembered

**Actual behavior:** Atom did what asked untill session ended, on the new session old settings are loaded

**Reproduces how often:** 100%

### Versions

Atom    : 1.32.0-beta0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

Noticed since 1.31.0-beta1. As a long-term beta user, had to switch to a stable version 1.30. Recently 1.31 became a new stable, and after upgrade I noticed the the error persist. Also in brand new 1.32.0-beta0. A searched through issues, can't beleive I'm the only one affected, so it could be a duplication, but I was unable to find any similar issue.
It's Debian.
I tried to remove .atom and .config/Atom

**Comment by lee-dohm** [comment]
Is your `~/.atom/config.cson` symlinked to another location?

**Comment by nyoro712** [comment]
I encountered the same problem.

- Atom: 1.31.0
  - Using in portable mode
  - Installed with `atom-x64-windows.zip`
  - `atom.exe` is in `D:\Atom\Atom`
  - `config.cson` is in `D:\Atom\.atom`
- OS: Windows Pro 64-bit, version 1803

**Comment by p-boiko** [comment]
> Is your `~/.atom/config.cson` symlinked to another location?

No, it's a plain text file, not a simlink. But thank you for pointing to it. When I rename .atom folder a new one is created on the edit start. But no settings are stored there. It's always 3 bites size: two brackets and a new line. So, the editor never writes to it.

**Comment by lyutkin** [comment]
I have the same issue. Fresh Ubuntu 16.04 installed, fresh atom installed via official package repository (https://packagecloud.io/AtomEditor). Unable to save any settings.

Atom: 1.31.0
Electron: 2.0.7
Chrome: 61.0.3163.100
Node: v8.9.3

**Comment by lee-dohm** [comment]
Since this seems to be a regression, we're looking to see who has time to take a look at this. Any information you all can share about how this might be reproduced would be helpful.

**Comment by bliepp** [comment]
I've got the same issue too on Ubuntu 18.04 (Atom 1.31). On older Versions (1.27) it works. Also got the corrupted config.cson with the two brackets in it on recreating the .atom folder. Even when loading a "valid" config file manually nothing changes. Reinstalled atom completely a few times. Installed via snap.

**Comment by Arcanemagus** [comment]
@bliepp Just a note that the snap distributions are not official and are unsupported. We always recommend you run from one of the [official builds](https://flight-manual.atom.io/getting-started/sections/installing-atom/). Although it seems that isn't the cause of the problem in _this_ case 😉.

**Comment by daviwil** [comment]
Preparing hotfix releases now, should be out within the next 12 hours.

**Comment by nyoro712** [comment]
I tried 1.31.1.
It works fine.
