### ISSUE TITLE
Small white line above title bar

### ISSUE THREAD

**Issue by yochem** [atom/atom#18112]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
There appears to be a small white line above the title bar as seen in the screenshot below. This is especially irritating when in mojave dark mode and using a dark atom theme.

Atom on top of screen:
![on top of screen](https://user-images.githubusercontent.com/23235841/46075865-1f544a00-c18c-11e8-8b04-d136ed5f82d2.png)
Atom placed anywhere on screen:
![anywhere on screen](https://user-images.githubusercontent.com/23235841/46075748-bb318600-c18b-11e8-893f-72e83cfac2a4.png)

### Steps to Reproduce

1. none

**Expected behavior:** No white line, so the dark atom colour will go seamlessly into the status bar.
**Actual behavior:** There's a white line above atom which prevents this.
**Reproduces how often:** 100%

### Versions
atom: **1.30.0**
Mac: MacBook Air 13"
MacOS: Mojave **10.14 Dark Mode**

### Additional Information
I think there is none.

**Comment by rsese** [comment]
Thanks for the report!  I poked around in the Electron repository and found https://github.com/electron/electron/issues/13164, so seems like an Electron issue.
