### ISSUE TITLE
Atom is not saving

### ISSUE THREAD

**Issue by sharmidev** [atom/atom#18114]
### Description

Atom is not allowing me to save my files, even if i use file bar or key commands. And not even save as is working. 

### Steps to Reproduce

1. Open file in atom
2. Make changes to file
3. try Saving

**Expected behavior:** I expect it to save and the blue dot on the tab to disappear

**Actual behavior:** blue dot does not disappear and file is not updated

**Reproduces how often:** 90% not sure yet what makes it work some times. 
I have tried in safe mode and uninstalled all packages but the core ones.
### Versions

Atom    : 1.30.0
Electron: 2.0.5
Chrome  : 61.0.3163.100
Node    : 8.9.3
Running Windows 10

**Comment by danPadric** [comment]
Hello.

- Are you a new user or seasoned Atom user? 
..when did you notice this behaviour?

- Does this type of behaviour happen for all file type? 
..does it do it for TXT files, for example?

- Could you check the time stamp of the file that you ordered to be saved. Does the file's time stamp change if you order the file to save?

- Could you indicate which packages you have?
..please run `apm ls` from the command prompt

Thanks in advance for your co-operation.

**Comment by rsese** [comment]
Additionally, do you see any errors in devtools console?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools

**Comment by p-boiko** [comment]
Local or remote file system?

**Comment by romdoq** [comment]
I'm a new user to atom (~3 weeks), and have been encountering this problem repeatedly.
Fortunately, I'm managed to (accidentally) create a test project which reliably triggers the bug:
https://github.com/romdoq/hello-world-cljs

1. Git clone the repo
2. Run `atom --safe hello-world-cljs`
3. Open package.json
4. Enter a `g` at the end of the file
5. Save
6. Delete the `g`
7. Save
8. Type another `g`
9. Try to save, but note that the file does not get saved.

### Versions
Atom    : 1.31.2
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Notes

* I've had this happen with clojure, json and markdown files.
* The timestamp does not get updated, nor does an absent file get created
* This occurs even in safe mode
* There are no errors in the developer tools
* All files are on the local drive

**Comment by romdoq** [comment]
I've been doing some further investigation of this issue, and it appears to somehow be related to the git integration:

* If I clone my `hello-world-cljs` project from GitHub, Atom exhibits this bug.
* If I clone the same project from a local directory (which itself was cloned from GitHub) Atom does **not** exhibit this bug.
* If I run Atom so that the project root is outside the git repository, Atom does **not** exhibit the bug.
* If I delete or rename the `.git` directory, Atom does **not** exhibit the bug.
* If I `git remote remove origin`, Atom does **not** exhibit the bug.
* If I re-add the git remote, Atom exhibits the bug again.

These most recent tests were done using Atom 1.32.0-beta3

**Comment by romdoq** [comment]
I think this is something to do with the `github` core package. If I disable that, the problem goes away after a restart of Atom.
Re-enabling `github` doesn't immediately cause the problem to reappear for that repository though.

**Comment by guillaume-chevalier** [comment]
I didn't read the whole thread, but here is some info: 

- I have the same bug. 
- Running in safe mode makes things work. 
- I tried uninstalling atom, deleting the ~/.atom folder completely, and reinstalling the newest version. The bug is still there. 
- Often, it saves the first time I hit ctrl+s, and then every subsequent saves don't work. 
- Also I realized that once 1 file is opened, then it won't want to open more files. I tried to open more files by opening from file explorer, or dragging and dropping, or even clicking files in the project file tree to the left in atom, and nothing works. This seems to be an "off by 1 error" somewhere. 
- My linux is 64 bits and is a distro derived from debian. 

I completely can't use atom unless it's in safe mode. I didn't try to see which package was causing this. 

EDIT: I tried to disable some packages, and without the autosave 0.24.6 and without the spell-check 0.74.0, the saving seems to work fine (but the blue dot for a modified file never shows, as if files were now really autosaved live, or if files just don't have the blue dot indicator anymore. However, there is still the problem of opening a 2nd file: it won't want to do it. Hecking crap, I liked atom.

**Comment by guillaume-chevalier** [comment]
Note: after retrying safe mode, opening a 2nd file in the editor won't even work anymore.

**Comment by arimozes** [comment]
I have the exact same problem as @romdoq mentioned above.
Open atom (with or without safe mode).
Edit a file and save - works ok.
Edit a second time and save - works ok.
Edit a third time and save - blue dot remains and file does not get saved.  If I try to close atom - it indicates there is content that needs to be saved.
Try to open a file at this point (ctrl-o or via menu) does not do anything.
Restarting atom allows things to work once again for a moment, but then fails as above.
Disabling github integration fixes the problem as described by @romdoq .
Starting atom as root (sudo atom) does not exhibit the issue - so maybe a permission related issue (perhaps with git) ?
$ atom --version
Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ git --version
git version 2.7.4

Let me know if I can provide additional information.

**Comment by mckeown12** [comment]
Are you, by any chance, using Kite?  I'm experiencing the same saving problem and get the following error in the devtools console: 

```
/Users/jamesmckeown/.atom/packages/kite/lib/kite-editor.js:74 Uncaught (in promise) TypeError: Kite.isEditorWhitelisted is not a function
    at subs.add.editor.getBuffer.onWillSave (/Users/jamesmckeown/.atom/packages/kite/lib/kite-editor.js:74:16)
    at Function.module.exports.Emitter.simpleDispatch (/private/var/folders/bb/0p0qhck92bn0rx9flttmz7tc0000gp/T/AppTranslocation/A…d/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.<anonymous> (/private/var/folders/bb/0p0qhck92bn0rx9flttmz7tc0000gp/T/AppTranslocation/A…/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:154:50)
    at Emitter.module.exports.Emitter.emitAsync (/private/var/folders/bb/0p0qhck92bn0rx9flttmz7tc0000gp/T/AppTranslocation/A…/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:157:18)
    at /private/var/folders/bb/0p0qhck92bn0rx9flttmz7tc0000gp/T/AppTranslocation/A…pp/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1347:38
    at <anonymous>
```

**Comment by eric4867** [comment]
literally just had this tart happening as well

**Comment by eric4867** [comment]
does deactivating kite help?

**Comment by mckeown12** [comment]
Yeah, I deactivated it and was able to save right away.  I'm linking this issue a new ticket with kite.

**Comment by eric4867** [comment]
Awesome, will do the same.  Glad to hear someone else is having the same issue!  Did you just update windows by any chance?

**Comment by falcoso** [comment]
Have had the same issue on windows, was working fine yesterday, re-opened same project, nothing new in atom but won't let me save. Also find that I cannot run atom-python-run when this is an issue as well. Will also comment more details in the new issue

**Comment by hybridpicker** [comment]
Had the same issue, while I was creating a new file. After disabled Kite it was possible to safe the file.
![ohne titel](https://user-images.githubusercontent.com/40589021/49305962-1c017580-f4d1-11e8-8416-4d3e1ae2b92c.png)

**Comment by wohlben** [comment]
I'm having the same issue.
at least in my case its just as @romdoq said the github integration.

Its also quite easy to find out if you're caught in the bug. The GitHub Panel (bottom-right) will be stuck in an endless spinner. 

This is extremely annoying, as the git diff functionality is imo way to essential to any ide to leave this module disabled.

I guess i'll have to switch to VSC after all, despite its shitty vim-mode implementation.

**Comment by jameshahn2** [comment]
Not using Kite. Uninstalled all suspect packages. Deleted Atom and reinstalled. Still can't save a file. Anyboy????

**Comment by rsese** [comment]
@jameshahn2  - there's not enough information to know if you're having some of the issues mentioned in https://github.com/atom/atom/issues/18620 so go ahead and open a new issue and completely fill out the issue template and we'll take a look.

**Comment by jameshahn2** [comment]
Thanks @rsese. Will get to that when I have time today.

**Comment by jameshahn2** [comment]
Wow. This is the strangest thing... Couldn't get rid of the issue, so I disabled all the packages left, then enabled them again one at a time to try and see if I still had the package installed that caused the issue. None of them broke the save function again and I can suddenly save css files again. Weird... but thrilled to be back in Atom.

**Comment by voises** [comment]
I believe I know why: controlled folder access. If you are using Windows 10, and you have Controlled Folder Access on, then Atom may not be allowed to write to some folders on your computer. Try making an exception for Atom, or turn it off altogether.

**Comment by MiguelOrdnz** [comment]
I been experience a kind of related problem, when i try to save a new file, just does not do anything. 

The exception:
![imagen](https://user-images.githubusercontent.com/9314209/53251747-fa083100-3682-11e9-8591-818e913425fb.png)

var extension = (editor.getPath().match(/\..+?$/) || [])[0];

I does not undestand why the function editor.getPath it's been called when the file is new and so there's no such path.

**Comment by Arcanemagus** [comment]
@MiguelOrdnz Your issue is a bug in the `atom-format` package you have installed, nothing to do with Atom itself.

**Comment by winterdamsel** [comment]
I know this issue is closed but those with Windows 10 (if they arrive to this issues) could try disabling/uninstalling OneDrive.

**Comment by ctag** [comment]
I believe I'm seeing this issue as well. Atom shows that the file is "saved" and even keeps the changes between restarting the program with no errors on the dev console, but opening the file some other way shows an old version.

I don't have any package named kite installed. I have Atom 1.34.0

**Comment by jondkelley** [comment]
I've started seeing this issue as well. 1.36.0

I haven't done anything different with plugins or configuration since this issue appeared.

**Comment by Lcode123** [comment]
Yes having the same dang issue, Guess its back to sublime text editor. Big middle finger to atom. I literally was doing my whole files and it seemed to save just fine. 
Oh ,  was I wrong. It saved my project buuutt when I went to link with GitHub it wouldnt display the contents of the html files. I was pissed since the code is still saved in the index.html file. 

Basically extracted all the source code opened atom 
made new folder 
new files and copied and pasted. 
Boom! it saved and now it is up in running on github. I dont feel safe using this again if my work isnt going to be available / not available/ yes available/ MAke up your DAMN Fuc**ing mind ATOM.

**Comment by lee-dohm** [comment]
@Lcode123 your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by Lcode123** [comment]
I dont know why my comment was deleted, simply stating the truth. As a developer we want our work to be saved and when you put hours and hours into projects and they dont get saved I believe we have an option to voice our opinions. Its like building a giant lego tower / castle for someone to just knock it over. But I understand this is G rated speaking .
But all the best for those still using Atom, hope your work gets saved in the future. Wish you the best.

**Comment by mbraha** [comment]
I was having this bug. I also noticed that the GitHub integration wasn't working. When I tried to open the tab, it just showed the spinner endlessly. I disabled the core GitHub package, restarted atom in safe mode, and am now able to save. I'll be taking my git actions outside of the editor for now. 

Hope this helps someone!

**Comment by taykcrane** [comment]
Same problem here. Cannot use Atom at all. Don't have a package called Kite and I've tried disabling Github with no luck.

**Comment by ficsorr** [comment]
Same problem here, I consider it as a major problem, I have lost data becuase of this.

**Comment by Arcanemagus** [comment]
As the original author of this issue never responded, and none of the team have so far been able to reproduce this from the information provided I'm locking this thread.

If you feel like you are hitting this please file a _new_ issue, making sure you have filled out the template completely, _especially_ the part about having tested in safe mode as most of those reporting this have been from a third party package.

If you are still able to reproduce in safe mode please include as much detail about the file system and permissions of the file you are seeing this on so we can attempt to diagnose this.
