### ISSUE TITLE
1.32.0-beta0 replaced open files with empty untitled files after the update

### ISSUE THREAD

**Issue by CadenP** [atom/atom#18124]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [ ] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
        * I opened the already updated editor in Safe Mode, with the same result. I did not try downgrading and updating again.
    * [X] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * (N/A) Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * (N/A) Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I just updated to 1.32.0-beta0 from 1.31.0-beta1, and reopened Atom for the first time to find that all of the open files were changed to empty untitled files. From all appearances it had no effect on the files themselves. I had a mixture of open files from within the project, from without the project, and never saved files (used for notetaking). All existing files had no unsaved changes.

### Steps to Reproduce

1. Have open files on Atom 1.31.0-beta1 (or below?)
2. Update Atom to 1.32.0-beta0
3. Reopen Atom and observe

**Expected behavior:** [What you expect to happen]

Previously opened files are reopened, as per the norm.

**Actual behavior:** [What actually happens]

Previously opened files are each replaced by an empty "untitled" file.

**Reproduces how often:** [What percentage of the time does it reproduce?]

I only tried once... So I guess that makes it 100% 😄 

### Versions

Windows 10 Pro
Version 1803
OS Build 17134.285

Prior to Update:
Atom: 1.31.0-beta1
The rest: ???

Following Update:

`atom --version`
Atom    : 1.32.0-beta0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

`apm --version`
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0-beta0
python
git 2.18.0.windows.1
visual studio

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

A screenshot of the result:

![image](https://user-images.githubusercontent.com/17813566/46119523-f4401980-c1d0-11e8-8953-88f14a4aaf65.png)

I also tried disabling TreeSitter (because I previously disabled it for `language-babel` and the update re-enabled it) and reopened Atom, but that had no effect.

Packages installed:

```
atom-ide-debugger-node@0.7.3
atom-ide-ui@0.13.0
atom-material-syntax@1.0.8
atom-material-ui@2.1.3
busy-signal@1.4.3
file-icons@2.1.25
flow-ide@1.12.0
hyperclick@0.1.5
ide-css@0.3.0
ide-flowtype@0.23.1
ide-html@0.4.2
ide-json@0.2.1
ide-php@0.7.15
intentions@1.1.5
language-babel@2.85.0
language-gradle@0.0.5
language-postcss@1.3.1
linter@2.2.0
linter-ui-default@1.7.1
semanticolor@3.6.0
set-syntax@0.4.0
teletype@0.13.3
```

**Comment by Aerijo** [comment]
@CadenP There may have been an incompatible change in the way the state is serialised. If you go to the files in your system's file navigator, they should all be as expected.

To fix the issue with Atom, you can try opening with `atom --clear-window-state`. This may clear unsaved changes being tracked by Atom, but will not affect any saved files.

 Alternatively, I've found opening a file direclty inside the folder you want to open will trigger a "Use existing saved state or discard" dialogue. Picking the discard option (again, this will clear unsaved changes) will open the folder as expected. For both methods, future openings should behave as expected.

If this is not the case, please let us know.

**Comment by p-boiko** [comment]
I was affected too.
@Aerijo suggestion worked for me. First run of `atom-beta --clear-window-state` cleared the editor's window from open files, then I opened a couple of files, closed editor and ran `atom-beta` without parameters. Now the files are opened

**Comment by CadenP** [comment]
The solution works as advertised. To be clear, for other readers, it does not reopen the original state (which was converted to empty untitled files), but that is understandable.

Thanks @Aerijo for the solution, and @p-boiko for the confirmation.

And yes, to my knowledge no files were modified by this change. I had ruled that out pretty quickly, so I'm happy to say that there is no lasting effect with this problem - other than losing some notes in some never-saved documents, but I knew the risks of doing that 😄 

Should this issue be closed, then?

**Comment by rsese** [comment]
Let's leave the issue open for now - just to mention, I can reproduce as described in the OP while upgrading from 1.31.0-beta1 to 1.32.0-beta0 on Windows 10.
