### ISSUE TITLE
CMD+F keyboard functionality defaulting to Find in Project instead of Buffer

### ISSUE THREAD

**Issue by Dayjo** [atom/atom#18128]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The functionality of CMD+F has changed in a recent version (not 1.31.0, maybe the version before this). The context / top menu works as expected but the keyboard functionality is incorrect.

When opening a file, CMD+F is now opening "Find in Project" the first time you press it, pressing the menu item under `Find > Find in Buffer` works as expected. 

### Steps to Reproduce

![](http://c.dayjo.me/6ca26e7dc6b7/Screen%20Recording%202018-09-27%20at%2004.03%20pm.gif)

1. Click file1 in the file tree
2. Press CMD+F
3. Sometimes this first time it will show correctly the Find in Buffer panel.
4. Click file2 in the file tree (You can precede or follow this with closing the panel pressing ESC).
5. Press CMD+F

**Expected behavior:** Find in Buffer panel is open.

**Actual behavior:** Find in Project panel is open.

**Reproduces how often:** 100%

### Versions
```
MacOSX High Sierra 10.13.6

Atom    : 1.31.0
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.0
python 2.7.10
git 2.15.2
```

### Additional Information

One thing I have noticed, that if I select the file from the "Open Files" panel in the tree, it works as expected. I'm doing this on a local folder. I am using Nuclide 0.351.0.

**Comment by lee-dohm** [comment]
I can't reproduce this using Atom Nightly v1.33.0-nightly1 on macOS 10.13.6. Have you tried it using [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by Dayjo** [comment]
Thanks, I had, but my packages were enabled weirdly. Turns out it's whatever Nuclide is doing to the tree view.  I will raise it there (https://github.com/facebook/nuclide/issues).
