### ISSUE TITLE
different color with tree sitter than with not tree sitter

### ISSUE THREAD

**Issue by trusktr** [atom/atom#18120]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I get different colors. Compare the right half of both screenshots (with and without tree sitter, respectively):

![screen shot 2018-09-26 at 2 46 44 pm](https://user-images.githubusercontent.com/297678/46111460-f045d480-c19b-11e8-87de-fbe80cdb9a29.png)

![screen shot 2018-09-26 at 2 47 07 pm](https://user-images.githubusercontent.com/297678/46111463-f2a82e80-c19b-11e8-9a34-4e95956931d2.png)
 

### Steps to Reproduce

Change enable/disable tree sitter, notice colors are different.

**Expected behavior:** same color either way

**Reproduces how often:** 100%

### Versions

<details>
  <summary>debug info with package info</summary>

```json
{
  "atom": "1.30.0",
  "platform": "darwin",
  "release": "17.5.0",
  "vmpVersion": "1.34.0",
  "vmpConfig": {},
  "activeCommunityPackages": [
    "atom-material-syntax: 1.0.8",
    "atom-domterm: 0.6.0",
    "atom-ide-ui: 0.13.0",
    "atom-ide-busy-signal: 0.0.0",
    "atom-ide-code-actions: 0.0.0",
    "atom-ide-code-format: 0.0.0",
    "atom-ide-code-highlight: 0.0.0",
    "atom-ide-console: 0.0.0",
    "atom-ide-datatip: 0.0.0",
    "atom-ide-debugger: 0.0.0",
    "atom-ide-definitions: 0.0.0",
    "atom-ide-diagnostics: 0.0.0",
    "atom-ide-diagnostics-ui: 0.0.0",
    "atom-ide-find-references: 0.0.0",
    "atom-ide-global: 0.0.0",
    "atom-ide-outline-view: 0.0.0",
    "atom-ide-refactor: 0.0.0",
    "atom-ide-signature-help: 0.0.0",
    "atom-ide-terminal: 0.0.0",
    "hyperclick: 0.0.0",
    "atom-vim-like-tab: 1.5.1",
    "busy-signal: 1.4.3",
    "emmet: 2.4.3",
    "ex-mode-sort: 1.0.0",
    "file-icons: 2.1.21",
    "file-watcher: 1.2.6",
    "hey-pane: 1.1.0",
    "highlight-line: 0.12.0",
    "highlight-selected: 0.13.1",
    "ide-typescript: 0.7.6",
    "imdone-atom: 2.4.29",
    "indent-guide-improved: 1.4.13",
    "intentions: 1.1.5",
    "keystroke: 0.4.0",
    "linter-eslint: 8.4.1",
    "minimap: 4.29.8",
    "minimap-git-diff: 4.3.1",
    "minimap-highlight-selected: 4.6.1",
    "minimap-pigments: 0.2.2",
    "minimap-quick-highlight: 1.0.1",
    "pigments: 0.40.2",
    "project-plus: 1.0.0",
    "quick-highlight: 0.13.0",
    "teletype: 0.13.2",
    "todo-show: 2.3.0",
    "tree-view-git-status: 1.5.0",
    "vim-mode-plus: 1.34.0",
    "vim-mode-plus-keymaps-for-surround: 0.2.1",
    "editorconfig: 2.2.2",
    "language-jenkinsfile: 0.1.1",
    "language-vue: 0.23.1",
    "language-pug: 0.0.22",
    "ex-mode: 0.18.0"
  ]
}
```

</details>

**Comment by trusktr** [comment]
Also coloring in non-tree sitter mode is inconsistent. In the following screenshot, the top half is the tail end of a class definition, and bottom half is the beginning of a function definition:

![screen shot 2018-09-26 at 3 26 12 pm](https://user-images.githubusercontent.com/297678/46112783-a4e1f500-c1a0-11e8-94a0-150d9663abca.png)


Notice how objects and curly braces are different colors.

**Comment by Arcanemagus** [comment]
Some coloration differences are to be expected. They are different engines and will parse the same code differently. Tree-sitter is a full parsing engine, while TextMate is essentially line-by-line RegEx parsing.

This image (which you didn't label so I have no idea if it's TextMate or Tree-sitter), looks to be a parsing bug where the engine ran into an issue:
![screen shot 2018-09-26 at 2 46 44 pm](https://user-images.githubusercontent.com/297678/46111460-f045d480-c19b-11e8-87de-fbe80cdb9a29.png)

Would you mind reopening this issue in the [language-typescript](https://github.com/atom/language-typescript) repository? Please include the full file that reproduces that if at all possible.

We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us halfway :+1:

**Comment by trusktr** [comment]
@Arcanemagus I believe the discoloration is with TextMate. Tree sitter seems solid in this regard.
