### ISSUE TITLE
“Unknown stream file type” error on launch

### ISSUE THREAD

**Issue by keithduncan** [atom/atom#1812]
I get the following error “Error: Implement me. Unknown stream file type!” on launch, I saw this in 0.80.0 and 0.81.0.

![screen shot 2014-03-31 at 17 04 30](https://cloud.githubusercontent.com/assets/22101/2577889/699c8b36-b985-11e3-98e9-883897eebf31.png)

This occurs when launching from Finder or from the `atom` command line helper.

The application is non functional after this error :cry:.

/cc #1333

**Comment by mnquintana** [comment]
Gonna close this out - please feel free to reopen / comment if you can reproduce this with the latest version of Atom (0.210.0)
