### ISSUE TITLE
non-tree-sitter mode chops characters from rendering

### ISSUE THREAD

**Issue by trusktr** [atom/atom#18121]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Here's what it looks like with tree sitter enabled (note the `y` at the end of `display`):

![screen shot 2018-09-26 at 2 58 32 pm](https://user-images.githubusercontent.com/297678/46111725-db1d7580-c19c-11e8-9fd1-0025025300f3.png)

and here's what it looks like without tree-sitter (note the `y`):

![screen shot 2018-09-26 at 2 58 15 pm](https://user-images.githubusercontent.com/297678/46111744-e7a1ce00-c19c-11e8-8baa-1a633246c813.png)

### Steps to Reproduce

not sure, just enable/disable tree sitter until you see the problem.

**Expected behavior:** no chopping of characters when tree sitter disabled

**Reproduces how often:** not sure yet

### Versions

<details>
  <summary>debug info with package info</summary>

```json
{
  "atom": "1.30.0",
  "platform": "darwin",
  "release": "17.5.0",
  "vmpVersion": "1.34.0",
  "vmpConfig": {},
  "activeCommunityPackages": [
    "atom-material-syntax: 1.0.8",
    "atom-domterm: 0.6.0",
    "atom-ide-ui: 0.13.0",
    "atom-ide-busy-signal: 0.0.0",
    "atom-ide-code-actions: 0.0.0",
    "atom-ide-code-format: 0.0.0",
    "atom-ide-code-highlight: 0.0.0",
    "atom-ide-console: 0.0.0",
    "atom-ide-datatip: 0.0.0",
    "atom-ide-debugger: 0.0.0",
    "atom-ide-definitions: 0.0.0",
    "atom-ide-diagnostics: 0.0.0",
    "atom-ide-diagnostics-ui: 0.0.0",
    "atom-ide-find-references: 0.0.0",
    "atom-ide-global: 0.0.0",
    "atom-ide-outline-view: 0.0.0",
    "atom-ide-refactor: 0.0.0",
    "atom-ide-signature-help: 0.0.0",
    "atom-ide-terminal: 0.0.0",
    "hyperclick: 0.0.0",
    "atom-vim-like-tab: 1.5.1",
    "busy-signal: 1.4.3",
    "emmet: 2.4.3",
    "ex-mode-sort: 1.0.0",
    "file-icons: 2.1.21",
    "file-watcher: 1.2.6",
    "hey-pane: 1.1.0",
    "highlight-line: 0.12.0",
    "highlight-selected: 0.13.1",
    "ide-typescript: 0.7.6",
    "imdone-atom: 2.4.29",
    "indent-guide-improved: 1.4.13",
    "intentions: 1.1.5",
    "keystroke: 0.4.0",
    "linter-eslint: 8.4.1",
    "minimap: 4.29.8",
    "minimap-git-diff: 4.3.1",
    "minimap-highlight-selected: 4.6.1",
    "minimap-pigments: 0.2.2",
    "minimap-quick-highlight: 1.0.1",
    "pigments: 0.40.2",
    "project-plus: 1.0.0",
    "quick-highlight: 0.13.0",
    "teletype: 0.13.2",
    "todo-show: 2.3.0",
    "tree-view-git-status: 1.5.0",
    "vim-mode-plus: 1.34.0",
    "vim-mode-plus-keymaps-for-surround: 0.2.1",
    "editorconfig: 2.2.2",
    "language-jenkinsfile: 0.1.1",
    "language-vue: 0.23.1",
    "language-pug: 0.0.22",
    "ex-mode: 0.18.0"
  ]
}
```

</details>

**Comment by trusktr** [comment]
If you take a closer look at the second image, you'll see that the colons (`:`) have a darker background, and it appears this is what chips the previous line's character. I can reproduce this 100%.

**Comment by Arcanemagus** [comment]
Tree-sitter has nothing to do with the rendering, other than potentially changing the scopes assigned, which can change the colors depending on the theme.

Do you see this in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
What theme are you using?
