### ISSUE TITLE
One Dark UI Sticky Projects visual glitch

### ISSUE THREAD

**Issue by jsg2021** [atom/atom#18130]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Scroll tree down... observe:
![screen shot 2018-09-27 at 9 57 54 am](https://user-images.githubusercontent.com/577453/46155058-17ec7980-c23c-11e8-9d4b-d6cdb95b5fb9.png)

### Steps to Reproduce

Scroll a bit and mouse over the header while the project header is in sticky position.

**Expected behavior:** header is not obscured 

**Actual behavior:** folder contents are on top of the header or there is no background color...

**Reproduces how often:** every time

### Versions

Atom    : 1.31.0
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.0
python 2.7.15
git 2.17.1

**Comment by rsese** [comment]
Thanks for the report!  This was fixed in https://github.com/atom/one-dark-ui/pull/268 and I thought this made it into 1.31 but it looks like it didn't (/cc @simurai is that right?)?  It does look fixed as of the 1.32 beta though.

**Comment by jsg2021** [comment]
Oh, thanks!

Should I close this then?

**Comment by rsese** [comment]
Yeah let's go ahead and close it since if it's the same bug, it's fixed but just not released yet - if you try the beta and see that this isn't fixed however, we can definitely reopen :+1:
