### ISSUE TITLE
Mojave dark mode

### ISSUE THREAD

**Issue by calintat** [atom/atom#18137]
## Summary

Dark mode support for Atom on macOS Mojave.

## Motivation

Many themes in Atom have both a light and dark variant. It would be nice if Atom could take advantage of the system-wide dark mode in macOS Mojave and switch between the light and dark variants of the user-selected theme according to the system setting in System Preferences > General > Appearance.

## Describe alternatives you've considered

Atom should at least change the theme of the title bar, if changing the whole theme is too much.

**Comment by lurajon** [comment]
@calintat - By adding `  <key>NSRequiresAquaSystemAppearance</key>
    <false/>`

to your info.plist file - you get the dark mode on the title bar.

**Comment by simurai** [comment]
Seems like Electron recently added a way to get the macOS's appearance setting: https://github.com/electron/electron/pull/14755. Which then themes might can use to automatically switch between light and dark. Will still take a while till it's available in Atom, though.

**Comment by fenhl** [comment]
There are [two](https://atom.io/packages/dark-mode) [packages](https://atom.io/packages/mojave-dark-mode) which claim to add this functionality, but neither of them work properly. (One doesn't do anything and the other keeps toggling between themes). So it would be great if support could be added to Atom itself.

**Comment by Arcanemagus** [comment]
The required functionality was first introduced in Electron v4, so this should be possible now as of #19373.
