### ISSUE TITLE
Request: Indicate that package is looking for existing issue

### ISSUE THREAD

**Issue by daviwil** [atom/atom#18143]
_From @tairun on September 26, 2015 15:6_

I think its really cool, that the package checks if there is already an open issue on github. But the default button says **Report Error** and if you click it and the issue was in fact already reported, nothing happens. A good 2-3 seconds later the button changes to **View Issue**. I would appreciate it, if there was a visual indicator, that atom is searching online.

_Copied from original issue: atom/exception-reporting#16_

**Comment by daviwil** [comment]
_From @damieng on January 10, 2017 16:45_

That part of the functionality is actually handled in the notification package.

**Comment by sompylasar** [comment]
Stumbled upon this issue while researching how Atom finds similar issues on GitHub, so here's specific references to the code:

- `NotificationElement`'s `renderFatalError` calls `findSimilarIssues` and waits for its Promise to resolve here: https://github.com/atom/notifications/blob/5617672e30325bebe8f7bcd8132669bdf83a2adc/lib/notification-element.coffee#L181
- `findSimilarIssues` definition here: https://github.com/atom/notifications/blob/5617672e30325bebe8f7bcd8132669bdf83a2adc/lib/notification-issue.coffee#L16-L39
