### ISSUE TITLE
Error when drag and dropping a file with a comma in the filename

### ISSUE THREAD

**Issue by jazz-X** [atom/atom#18163]
*Edit by @rsese to add generic repro steps*

In safe mode:

1. Create a new file and save it with a comma in the filename e.g. `test,file.txt`
1. Create a directory called `mydir`
1. Drag and drop the file from step (1) to the directory in step (2)

Using a comma in a filename isn't illegal as far I found but seems like not the safest choice?  Assuming we're ok allowing commas in filenames, expected behavior is that the file is dragged successfully to a directory.  Actual behavior is the file isn't moved and you get the error below.

Also noticed that cutting/copying and pasting does nothing but no error is thrown.

---

[Enter steps to reproduce:]

1. ...Created new folder
2. ...Selected files to move
3. Moved files to new folder which caused error ENONET

**Atom**: 1.32.0-beta1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ Enterprise Edition- The Jav….webloc'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/ Enterprise Edition- The Jav….webloc'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:336:29)
    at TreeView.t.exports.TreeView.moveEntry (/private/var/folders/7t/cw1b31zd3752f756cj9zxnmh0000gp/T/AppTranslocation/C41D32F4-F4D3-441A-A6ED-CF9BF6788BC6/d/Atom Beta 1.32.app/Contents/Resources/app/static/<embedded>:14:916037)
    at TreeView.t.exports.TreeView.onDrop (/private/var/folders/7t/cw1b31zd3752f756cj9zxnmh0000gp/T/AppTranslocation/C41D32F4-F4D3-441A-A6ED-CF9BF6788BC6/d/Atom Beta 1.32.app/Contents/Resources/app/static/<embedded>:14:921791)
    at HTMLDivElement.<anonymous> (/private/var/folders/7t/cw1b31zd3752f756cj9zxnmh0000gp/T/AppTranslocation/C41D32F4-F4D3-441A-A6ED-CF9BF6788BC6/d/Atom Beta 1.32.app/Contents/Resources/app/static/<embedded>:14:895702)
```

### Commands

```
     -1:33.8.0 application:add-project-folder (input.hidden-input)
     -0:44.5.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:39.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.12.1 
autocomplete-asciidoc 0.1.2 
build-make 0.13.0 
language-asciidoc 1.11.0 
```

**Comment by jazz-X** [comment]
Isolated the file that cause the exception. A web shortcut:
35.2 Developing Embeddable Enterprise Bean Applications - Java Platform, Enterprise Edition- The Jav….webloc

**Comment by jazz-X** [comment]
renaming the file to: 
35.2 Developing Embeddable Enterprise Bean Applications.webloc
solved the issue.

**Comment by rsese** [comment]
Thanks for the report - I feel like there's an existing issue for this somewhere but couldn't find one.  Looks like the issue is with `,`, if I create a file just called `test,file.txt`, I can reproduce the error by trying to drag and drop the file to another directory.  Trying to cut and paste the file to another directory doesn't do anything and didn't see any errors in devtools console.

Maybe belongs in atom/tree-view but I'll leave it here for now.
