### ISSUE TITLE
Remove `!important` from styles

### ISSUE THREAD

**Issue by daviwil** [atom/atom#18174]
_From @dsandstrom on June 12, 2017 17:28_

Makes it more of a pain to override the background color.

https://github.com/atom/deprecation-cop/blob/master/styles/deprecation-cop.less#L16

_Copied from original issue: atom/deprecation-cop#82_

**Comment by RyanPisuena** [comment]
'This repository has been archived by the owner. It is now read-only.' When attempting to submit a pull request.

**Comment by Arcanemagus** [comment]
@RyanPisuena As explained in the archived repository's README, the code for that now lives here: https://github.com/atom/atom/tree/master/packages/deprecation-cop

**Comment by RyanPisuena** [comment]
Issue can now be closed per #18266

**Comment by thomasjo** [comment]
@RyanPisuena Thanks! :tada:
