### ISSUE TITLE
Change Report Issue button to reflect current status of the deprecation

### ISSUE THREAD

**Issue by daviwil** [atom/atom#18176]
_From @eboracus on July 17, 2015 18:31_

It would be nice if the report issue button behaved similarly to the Uncaught Error notification's report issue button. So if the error/issue has already been reported the button changes visually to inform the user, and they know it's not necessary to go and report it.

The button could still link through to the logged issue's page as it does now, but just give the information to the user without them having to click and open up the link to find out.

![depcop_report_issue](https://cloud.githubusercontent.com/assets/11758299/8754208/c2983b06-2cb9-11e5-9001-f9e957e6f352.png)
This is how it currently looks for a deprecation that has already been reported.

_Copied from original issue: atom/deprecation-cop#61_

**Comment by daviwil** [comment]
_From @50Wliu on July 18, 2015 15:33_

This should have been fixed in #46.

**Comment by daviwil** [comment]
_From @izuzak on July 20, 2015 14:38_

@eboracus Can you share the version of Atom you're using and the exact steps which reproduce the problem shown in the screenshot? (Assume I have only Atom installed, no packages.)

**Comment by daviwil** [comment]
_From @eboracus on July 20, 2015 23:8_

This is with v1.0.2 and I can't reproduce the above in strict safe mode as I can only display the deprecation in question with the offending packages enabled. `linter-clang` in this case (which I guess needs `linter` to actually activate itself), with only these two packages installed I get the above screenshot. So at least from clean Atom the steps should be: install/load these two packages -> load atom -> click on deprecation message in status bar and the button displays as shown, thought the issue is reported.

**Comment by daviwil** [comment]
_From @izuzak on July 22, 2015 11:32_

Ahhh, thanks for clarifying. I totally misunderstood your report -- I thought you were saying that existing issues were not detected correctly. 

Yeah, the "Report issue" button checks for existing issues when clicked, not before that. I guess it would be nice if the behavior matched the Notifications package. Gonna add the "enhancement" label to this :+1:

**Comment by ceciliamalmrud** [comment]
I'm looking for a way to contribute to the project, I found this interesting. I have not contributed to Atom before, but think I might be able to add this enhancement. Unless there is some reason not to, I jump right on it. Thoughts?
