### ISSUE TITLE
Update report after package update

### ISSUE THREAD

**Issue by daviwil** [atom/atom#18175]
_From @Stanzilla on July 20, 2015 0:31_

When you update a package and that update fixed the deprecations, deprecation cop still thinks it has deprecations until you restart Atom. Maybe it can rescan for them after each package update?

_Copied from original issue: atom/deprecation-cop#62_

**Comment by daviwil** [comment]
_From @Stanzilla on January 11, 2017 9:53_

would still love to see this

**Comment by Arcanemagus** [comment]
As package updates are only applied on restarting Atom now, instead of attempting to live-reload them like was done back when this issue was first filed, this issue is no longer relevant. Thanks for taking the time to file the original issue @Stanzilla!
