### ISSUE TITLE
sRGB no longer working in Mojave

### ISSUE THREAD

**Issue by matt3224** [atom/atom#18171]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Color profile is no longer making any difference when set to sRGB, both the display color profile and the override setting in Atom produce the same colors. This happens in safe mode also

### Steps to Reproduce

1. Use the standard color profile on mac
2. Open Atom and set the color profile to sRGB
3. You will notice no change between the two

**Expected behavior:** 
Previously on High Sierra switching to sRGB would make the colors more vibrant compared with the default system profile. After upgrading to Mojave the colors seem dull and there is no visible change between the two settings

**Actual behavior:**
There is no change between settings

**Reproduces how often:**
100%

### Versions
macOS 10.14 (18A391)
Atom    : 1.31.1
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.1
python 2.7.10
git 2.17.1

### Additional Information

![atom](https://user-images.githubusercontent.com/2401925/46351457-4eb4fc00-c64f-11e8-8be1-75a3dbb19c84.png)

**Comment by rsese** [comment]
Thanks for opening a new issue for this:

> Previously on High Sierra switching to sRGB would make the colors more vibrant compared with the default system profile. After upgrading to Mojave the colors seem dull and there is no visible change between the two settings

Just to clarify, is your system-wide color profile set to sRGB?  The color profile setting in Atom gives you control over whether Atom respects the color profile you have set so it's expected that if your system-wide color profile is sRGB, then you won't see a difference.

**Comment by matt3224** [comment]
@rsese I have my MacBook Pro display set to the default (Color LCD) and I also tested on an LG 5K UltraFine set to (LG UltraFine) which again is the default.

**Comment by rsese** [comment]
Sorry bear with me, I don't use color profiles myself so had to spend some time reading through https://github.com/atom/atom/issues/17356 and playing with the settings on my computer.

Would you be able to share the debugging details Jason asked for in https://github.com/atom/atom/issues/17564#issuecomment-399999110 (with the current version of Atom you're using for steps 2 and 3)?  As mentioned there, if you can use the Digital Color Meter app to get the hex or RGB values, that would be helpful.  

Based on your description, I would guess that the colors in 1.27 (the version before the color profile settings was added) are more vibrant.

**Comment by redkhalil** [comment]
I just upgraded to Mojave and came across this when searching for 'dull color'. However I'm not using Atom. Looks like an OS issue.

**Comment by matt3224** [comment]
@rsese Using Atom 1.31.1 for both screens. Here is a comparison again between setting atom to sRGB and using the Digital Colour Meter app, then again with default color profile.

![dcm 2x](https://user-images.githubusercontent.com/2401925/46534208-4bb04a80-c89f-11e8-8b26-61a6b3c67138.png)

**Comment by 1pocketaces1** [comment]
I have this same issue. Was using High Sierra with excellent colors on Atom, updated to Mojave today and now have dull color scheme with Atom.

**Comment by atomiks** [comment]
The "Use sRGB color profile" checkbox has zero effect (back on High Sierra as well, I made an issue). 

If you go to System Preferences > Displays > Color and change it to `sRGB IEC61966-2.1` then the whole OS gets the vibrant color profile (including Atom). However, I _only_ want Atom to have it, because it causes images look oversaturated with it, but syntax highlighting looks nice with it. That's why I wanted the checkbox to work but leave it on Color LCD (default profile on Mac), so it worked like 1.27.0. I remember Chrome 61 changed the way color profiles worked, so it's linked to Chromium
