### ISSUE TITLE
Error building atom-keyboard-macros 0.12.1 on atom 1.31.1

### ISSUE THREAD

**Issue by brucehvn** [atom/atom#18183]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Please refer to issue https://github.com/atom/atom/issues/17828

I just upgraded to Ubuntu 18.04 LTS and am experiencing the same problem with the atom-keyboard-macros program.  Unfortunately the solution in issue 17828 of installing libxkbfile-dev is not available as it appears the package does not exist in the Ubuntu repos anymore.  The only libxkb* packages available are as follows:
```
ii  libxkbcommon-dev                          0.8.0-1                   amd64                     library interface to the XKB compiler - development files
ii  libxkbcommon-x11-0:amd64                  0.8.0-1                   amd64                     library to create keymaps with the XKB X11 protocol
ii  libxkbcommon0:amd64                       0.8.0-1                   amd64                     library interface to the XKB compiler - shared library
ii  libxkbfile1:amd64                         1:1.0.9-2                 amd64                     X11 keyboard file manipulation library
```

### Steps to Reproduce

1. Start atom
2. One update shows for atom-keyboard-macros, click on it and then hit the update button
3. update fails

**Expected behavior:** [What you expect to happen]
Package is expected to update normally

**Actual behavior:** [What actually happens]
Package update fails with stack trace.  Pertinent information is below:
```
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
../src/keyboard-layout-manager-linux.cc:5:10: fatal error: X11/extensions/XKBrules.h: No such file or directory
 #include <X11/extensions/XKBrules.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Release/obj.target/keyboard-layout-manager/src/keyboard-layout-manager-linux.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-36-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11892-24006-1t2wuqh.fpja/node_modules/atom-keyboard-macros/node_modules/keyboard-layout
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
```
bruce@BRUCE-CUSA:~/gitroot/3dprint/Marlin$ atom --version
Atom    : 1.31.1
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

Ubuntu 18.04 Linux 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
### Additional Information
Problem occurs in safe mode as well

**Comment by daviwil** [comment]
I'm surprised that the `libxkbfile-dev` package doesn't show up for you, it seems to be in Ubuntu's package site for 18.04: https://launchpad.net/ubuntu/bionic/+package/libxkbfile-dev.  I did a brief search and can't find any information about it being removed in that release.

What's the output of `sudo apt-get install libxkbfile-dev`?

**Comment by brucehvn** [comment]
Sorry, it is in the repo.  I was doing a dpkg-query to try and find it.  I must have been mistaken in thinking that would show me all packages available.  When I ran Synaptic, the libxkbfile-dev was there.  It's installed and the package builds now.  Closing this issue.

**Comment by daviwil** [comment]
Glad to hear it's resolved for you now, thanks a lot for following up!

**Comment by aayushdutt** [comment]
> I'm surprised that the `libxkbfile-dev` package doesn't show up for you, it seems to be in Ubuntu's package site for 18.04: https://launchpad.net/ubuntu/bionic/+package/libxkbfile-dev. I did a brief search and can't find any information about it being removed in that release.
> 
> What's the output of `sudo apt-get install libxkbfile-dev`?

Thanks!
Was getting the same errors on doing `npm install` in [Automattic/wp-desktop](https://github.com/Automattic/wp-desktop). Fixed after running `sudo apt-get install libxkbfile-dev`
