### ISSUE TITLE
Atom not saving theme settings. 

### ISSUE THREAD

**Issue by servicioswebavr** [atom/atom#18185]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Although I change theme, everytime I start atom, default theme is loaded. No external package is installed yet.

### Steps to Reproduce

1.- Change default theme
2. Close Atom
3. Open Atom

**Expected behavior:** The theme I choose is loaded. Welcome tabs are not opened.

**Actual behavior:** Default theme is loaded. Welcome tabs are opened.

**Reproduces how often:** Everytime I run Atom

### Versions
Atom    : 1.31.0
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Aerijo** [comment]
@servicioswebavr The current version of Atom is 1.31.1

Please update, as this issue should be patched in that release.

**Comment by daviwil** [comment]
@Aerijo is correct, this issue will be fixed by updating to Atom 1.31.1.  I'll close this issue for now, but if the issue persists after updating let us know and we will investigate.  Thanks!
