### ISSUE TITLE
Jump to (find) char position in file

### ISSUE THREAD

**Issue by simadsen** [atom/atom#18191]
## Summary

Allow Atom to jump to a character position within a file.

## Motivation

Some error logging outputs a character position where the code breaks. Entering a character position and jumping to it within a given fule will make it easier to debug and fix.

## Describe alternatives you've considered

A plugin or reg-ex may be able to jump to a character position, but haven't been able to find a solution.

## Additional context

Vim has this feature. It would be nice if Atom had too.

**Comment by thomasjo** [comment]
This is already supported, and is documented in `atom --help`
```
$ atom --help
Atom Editor v1.31.1

Usage:
  atom [options] [path ...]
  atom file[:line[:column]]

One or more paths to files or folders may be specified. If there is an
existing Atom window that contains all of the given folders, the paths
will be opened in that window. Otherwise, they will be opened in a new
window.

A file may be opened at the desired line (and optionally column) by
appending the numbers right after the file name, e.g. `atom file:5:8`.

...
```
From within Atom you can additionally use <kbd>Ctrl+G</kbd> to jump to any row-column position within the current document. For more details, see [Moving in Atom](https://flight-manual.atom.io/using-atom/sections/moving-in-atom/#moving-in-atom).

**Comment by simadsen** [comment]
@thomasjo in sublime you can jump to a character by doint cmd+t ::N where N is the Nth character in the file that you want to go to. i.e. precede the number with 2 colons. You can also to cmd+t :L where L is the line number. It would be really cool if you could to the same in atom as you can in sublime for that.

**Comment by simadsen** [comment]
I want to be able to go the n'th character (byte) in the file in absolute terms, independently of the row and column.

**Comment by thomasjo** [comment]
@simadsen That seems like a perfect feature for either a community package. However, if you just want to scratch your own itch, you can solve this by writing a custom command. See [The Init File](https://flight-manual.atom.io/hacking-atom/sections/the-init-file/) for more details, including how to create a custom keybinding for the custom command. If I remember correctly, the method you'll want to use to implement your buffer jump logic is [TextEditor::setCursorBufferPosition](https://atom.io/docs/api/v1.31.1/TextEditor#instance-setCursorBufferPosition).

If you have further questions regarding this, please continue the discussion in our [Slack](https://discuss.atom.io/t/join-us-on-slack/16638) or [Discuss](https://discuss.atom.io/).

**Comment by rmaunder** [comment]
I don't agree this is supported or solved, however this title is maybe not so helpful. Really what is needed is support to jump to Nth absolutely character, counting chars from first (regardless of lines). For example I have a Python error reading a text file:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2650: ordinal not in range(128)`

and would like to hop to the offending character. There was a community package which I thought would help: https://atom.io/packages/status-bar-cursor-position
however this seems to been removed / unsupported (won't install via Atom or apt for me).

**Comment by dev-serverlessguru** [comment]
Like this: https://marketplace.visualstudio.com/items?itemName=jtr.vscode-position

**Comment by GabrielBakker** [comment]
Yes, because the error messages in Atom give the Character position in terms of the Absolute Character Position, Atom needs a shortcut key that will allow you to jump to that character!

I second this! Please add way to do this. This issue is not resolved!

![image](https://user-images.githubusercontent.com/30029319/61924433-6be3ef80-af2d-11e9-97a3-077f1c64be54.png)

**Comment by Arcanemagus** [comment]
As was [already stated](https://github.com/atom/atom/issues/18191#issuecomment-426981392) this is something that is relatively simple to implement in a package, and it seems there is already one that may just need a bit of work to get usable again. Note that the earlier advice was slightly incorrect, you'll likely need to use a combination of [TextBuffer::positionForCharacterIndex](https://atom.io/docs/api/v1.31.1/TextBuffer#instance-positionForCharacterIndex) and [TextBuffer::characterIndexForPosition](https://atom.io/docs/api/v1.31.1/TextBuffer#instance-characterIndexForPosition) to go back and forth between row/column coordinates and character indexes into the file.

See the earlier comment for resources on package development if you need any help.
