### ISSUE TITLE
can't focus on the search box with keyboard

### ISSUE THREAD

**Issue by tr15tan** [atom/atom#18203]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[can't focus on the search box with keyboard]

### Steps to Reproduce

1. open an arbitrary file
2. use the command palette to open the settingsview : show keybindings panel
3. try to focus on the "search keybindings" box with keyboard

**Expected behavior:** [can focus on the "search keybindings" box with keyboard]

**Actual behavior:** [can not focus on the "search keybindings" box with keyboard]

**Reproduces how often:** [must]

### Versions

Atom    : 1.31.0
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

Linux tristan-home 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce on macOS 10.12.6 with 1.33.0-nightly10.

I also noticed that the `Open Config Folder` does get highlighted as I <kbd>tab</kbd>.
