### ISSUE TITLE
Atom file explorer cannot see files.

### ISSUE THREAD

**Issue by DoomDuck** [atom/atom#18206]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When trying to access /usr/include/GL/glew.h using Atom's file explorer the glew.h file does not show up in the /usr/include/GL file (while all others do ). Knowing the glew.h does exist on my computer as I can open it through Emacs, File and many other programs. Moreover as this file cannot be seen by Atom's file explorer the packages trying to compile my program fail as they don't see my file.

### Steps to Reproduce

1. Install libglew-dev through the command line using apt-get.
2. Launch atom.
3. Hit ctrl+o and go to the /usr/include/GL/ folder
Optional :
4. You can and drag and drop the file as a new empty buffer called glew.h is created.

**Expected behavior:** I expected to see my glew.h file through the explorer

**Actual behavior:** The file does not show up. While it shows up in every other possible program

**Reproduces how often:** Every time I try to access this file

### Versions

The atom command does not exist on my laptop but I use the 1.30.0 version.

This bug occurred using an HP omen computer running Linux Mint 19.

### Additional Information

![file_opener_bug](https://user-images.githubusercontent.com/37777252/46580781-daea6900-ca2b-11e8-9879-2f7418bef3f2.png)

**Comment by danPadric** [comment]
Hello.

Could you please check..
1. Does that specific file have any special attributes that that the other files do not have?
2. What happens if the file is duplicated to another file name?
3. If the file is copied to another location, does the file become visible now?

(I am an exclusive Windows user. so will not be able to detail the above.)

Regards.
