### ISSUE TITLE
HTML style tags do not have syntax highlighting enabled

### ISSUE THREAD

**Issue by matt3224** [atom/atom#18212]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

HTML style tag syntax highlighting does not work

### Steps to Reproduce

1. Create html file 
2. Write a style tag with a css declaration

**Expected behaviour:**
Styles would be syntax highlighted

**Actual behavior:**
Style tag content is not syntax highlighted 

**Reproduces how often:**
100%

### Versions

macOS : 10.14
Atom    : 1.31.2
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.2
python 2.7.10
git 2.17.1

**Comment by Arcanemagus** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the [language-html](https://github.com/atom/language-html) repository? When doing so please include some actual code to reproduce this with, thanks! We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us halfway :+1:
