### ISSUE TITLE
Default Project Location not working

### ISSUE THREAD

**Issue by fynxgloire** [atom/atom#18225]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I change the default Project Location within the settings, it does not affect anything, NOTHING HAPPENS.

### Steps to Reproduce

1. Go To Settings, choose the Core Tab
2. Change the default Poroject settings location to: \\NASDA7604\Documents\Programming\Python
3. Close Settings, now on the left hand side of the GUI under Project, it is still showing .atom, which is under the C: drive somewhere

**Expected behavior:** On the left hand side of the GUI under Project, it should show the NEW location eg. \\NASDA7604\Documents\Programming\Python containing the python files located there, NOT the default C drive

**Actual behavior:** It still shows .Atom location under the C: drive

**Reproduces how often:** 100%

### Versions
Atom    : 1.31.2
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
Windows 10 64 bit

**Comment by thomasjo** [comment]
This is working as intended; the setting is used by some parts of Atom, in particular the package generator. Sadly the name and description is somewhat confusing, and it does not impact the current window's active projects that you can see in the tree-view as you describe. See [Opening Directories](https://flight-manual.atom.io/getting-started/sections/atom-basics/#opening-directories) for more information on that.

Reference: https://discuss.atom.io/t/what-is-project-home-in-settings/4638/4
