### ISSUE TITLE
Regex word boundary broken

### ISSUE THREAD

**Issue by jophut** [atom/atom#18226]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Finding a word boundary using regular expression is broken.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/3954707/46870783-e674d000-ce2f-11e8-94e3-c9a2c464b5cf.png)

1. Create a new file with contents:
```Ha HaHa```
2. Open the search tool (windows: CTRL+F)
3. Click on '.*' or press CTRL+ALT+/ to enable 'Use regex'
4. In the upper input field 'Find in current buffer' enter:
```\bHa```

**Expected behavior:**
Two results: (The \< and \> characters mark the start and end of the results.)
\<Ha\> \<Ha\>Ha

**Actual behavior:**
Three results:
\<Ha\> \<Ha\>\<Ha\>

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

Atom    : 1.31.2
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.2
python 2.7
git 2.7.2.windows.1
visual studio 2015

### Additional Information

none

**Comment by zpolygon95** [comment]
Reproduced in
MacOS: 10.13.6
Atom: 1.31.2
Electron: 2.0.7
Chrome: 61.0.3163.100
Node: v8.9.3
