### ISSUE TITLE
Atom suddenly switched to dark mode and shows welcome guide.

### ISSUE THREAD

**Issue by garretwilson** [atom/atom#18229]
I'm on Windows 10 using Atom 1.31.2 x64. I had Atom set to the light theme ever since I installed it, years ago.

Suddenly I started up Atom today and it is set to the "One Dark" UI and syntax themes. In addition the welcome guide is shown, with "Show Welcome Guide when opening Atom" checked.

* It still opened my last opened directory.
* All my projects are still there using the project manager.
* My plugins still seem to be installed.

Why did Atom suddenly revert my theme and show me the welcome guide? This sounds scary, like some configuration corruption or something. I'll have to go through and see if any other settings have changed.

Oh, no—I had "Auto Indent On Paste" disabled, and now it's enabled again. It looks like Atom reset my settings.

Anyone know what happened? How can I get back a copy of my original settings? (I may have backed up my development environment yesterday. Where would they be stored, so I can try to copy them back?)

**Comment by garretwilson** [comment]
Arg, it toggled off invisibles and reset the size of the font. Why, why?

**Comment by rsese** [comment]
Sorry for the trouble here, it sounds like you've hit the same issue described in https://github.com/atom/atom/issues/14909.  The team pushed some changes to address the problem but some folks are still hitting the issue it looks like.

> (I may have backed up my development environment yesterday. Where would they be stored, so I can try to copy them back?)

Your settings are in your `config.cson` file:

https://flight-manual.atom.io/using-atom/sections/basic-customization/#global-configuration-settings

If you have that file backed up, you should be able to copy it to your home directory to restore your settings.

I just asked in https://github.com/atom/atom/issues/14909 if someone could open a new issue so the team can track this problem - can you edit the issue body to fill out the issue template as much as possible so we can use this issue to track it?

**Comment by garretwilson** [comment]
> can you edit the issue body to fill out the issue template as much as possible so we can use this issue to track it

Sorry, after all the problems over the years—random changes, random freezes that make me have to reset the windows preferences, an end-of-line bug that corrupted files, broken scrolling, a silly thing where Atom forces the lines to wrap even though I turn wrapping off… I could go on. But dumping almost the entire configuration is a pretty serious thing. It was the proverbial straw that broke the camel's back. Everyone had been telling me to try VisualStudio Code. This bug was too much; I tried VS Code and I'm not looking back.

**Comment by garretwilson** [comment]
Oh, and I've written a complete software development course in which we recommended Atom. We start another term next week, and I'll be rewriting the lessons to recommend VS Code instead.

**Comment by rsese** [comment]
Sorry to hear that - I know you were a long-time user of Atom and I've seen some of those issues you've mentioned, I can see how frustrating they were (I was hit by a settings loss too).  If you happen to come back to Atom in the future we'll be here but in any case, thanks so much for your contributions in issues and on the message board.
