### ISSUE TITLE
Right-click menu disappear by itself after few seconds

### ISSUE THREAD

**Issue by EvansXIV** [atom/atom#18227]
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

HI there,
I have a problem started with the latest update that’s really annoying.

When I right click both in the Tree View or in the Editor the menu fade out by itself after a few seconds. I don’t even have time to select the option I want.
(I’m running 1.31.2 on macOS 10.14)

Has someone else encountered this issue as well? How to solve it?

### Steps to Reproduce

1. Right click on a file to on the tree view
2. wait for it to magically disappear after like 3 seconds

Expected behavior: Menu has to stay active untile I select something

Actual behavior: It doesn't.

Reproduces how often: about 50% of the times I right click on a file 

### Versions

1.31.2
macOS 10.14

See attached gif for better understanding of my problem:
(Every time it fades out it's not because I clicked out, it disappear by itself)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34335719/46874079-99e1c280-ce38-11e8-8b59-489ebd98e65b.gif)

**Comment by EvansXIV** [comment]
Btw, I have never encountered this bug until now, it started with 1.31.2

**Comment by rsese** [comment]
Thanks for the report!  I can't reproduce on macOS 10.12.6 with Atom 1.31.2 - it looks like your GIF isn't in safe mode, is the behavior exactly the same in safe mode?  Did you try any other of the [debugging suggestions](https://flight-manual.atom.io/hacking-atom/sections/debugging/)?

**Comment by EvansXIV** [comment]
Yes, it happens in safe mode too 😩 
I really don't know why, could it be 'cause of performance issues? 

Recently my Mac is having same issues with free storage left and RAM overloading (because of Virtual Machines I have to use for work.)

Besides, I've noticed that out of all running programs Atom always takes the most of CPU. Is that normal?

**Comment by rsese** [comment]
> I really don't know why, could it be 'cause of performance issues?

Hmmm, not sure - do you see this behavior with other applications or just Atom?  If you have very few programs running and your system isn't overloaded, do you still see the same issue in Atom?

> Besides, I've noticed that out of all running programs Atom always takes the most of CPU. Is that normal?

If you start Atom in safe mode and aren't doing anything with Atom but it's still using a lot of CPU, that does seem odd.  Is that the case or do you only notice this when you start Atom not in safe mode and while working on projects?

Also, you mentioned that this started with the last update - if you install the previous version of Atom where this wasn't an issue, do you still see the same behavior?
