### ISSUE TITLE
A search bug

### ISSUE THREAD

**Issue by dtssv** [atom/atom#18236]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I want to search some word in the file，then i use crtl+f and copy the word to the find text，but nothing in the text，and the word copy to the file。but i don`t know if other package cause it。

### Steps to Reproduce

like Description

**Expected behavior:** I want copy the word to the find text

**Actual behavior:** the word copy to the file

**Reproduces how often:** every time

### Versions

1.25.0 ia32 windows

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks very much for the report!

> 1.25.0 ia32 windows

The current stable release version of Atom is 1.31.2, can you update and try to reproduce the issue again?  And please also go through the `Prerequisites` section and try to reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) for example.

If you can reproduce on the latest stable release of Atom and in safe mode, please reopen the issue in https://github.com/atom/find-and-replace.  We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us half way 👍
