### ISSUE TITLE
Show each grammar's responsible package & link to its settings

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#18259]
_From @saizai on April 17, 2018 11:21_

Sometimes multiple packages provide very similar (or identically named) items. Or you forget what you installed that provides this and don't want it any more.

So, always show (right-aligned) the package responsible for this entry, and a gear button linking to its settings page.

crosslink: https://github.com/atom/encoding-selector/issues/60

_Copied from original issue: atom/grammar-selector#56_

**Comment by Zearin** [comment]
I’ve spent the last 2 hours trying to find (or figure out how to hack) exactly this feature!  

## Motivations

* It’s easy to customize the CSS for any given syntax!  But it’s _not_ easy to customize how a syntax is _parsed_.  
* I wanted to tweak how Atom parses and tokenizes JS.  (I noticed it does not wrap anything around the `this` keyword, so I wanted to add this functionality.)

----

I know the retirement of Nuclide has everyone scrambling to keep the ecosystem it kicked-off alive.  At the same time, don’t let good stuff like this get lost in the shuffle. :)
