### ISSUE TITLE
Atom on Mac App Store

### ISSUE THREAD

**Issue by mmattioli** [atom/atom#18252]
## Summary

Make Atom available on the Mac App Store.

## Motivation

Makes Atom more accessible and distributable in enterprise environments (via Apple VPP and MDM).

## Describe alternatives you've considered

Manually packaging and distributing the app via MDM can be painful whenever there is a new update to Atom.

## Additional context

@lee-dohm makes a comment in #10976 referencing the sandbox which Mac Apps are required to stay in and I don't believe that is still an issue considering that apps such as [Text Wrangler are available in the Mac App Store](
https://itunes.apple.com/us/app/textwrangler/id404010395).

**Comment by lee-dohm** [comment]
Thanks for the suggestion.

We're still not interested in distributing Atom via either the Mac or Windows App Stores. We don't believe that the added overhead for us, to our development and distribution processes, is worth the meager discoverability benefit for our users. While it is true that Text Wrangler is available in the Mac App Store, [Bare Bones Software's more full-featured programmer-targeted editor, BBEdit,](https://www.barebones.com/products/bbedit/) is no longer available in the Mac App Store. And there are [specific differences](https://www.barebones.com/store/macappstore.html#appstore_differences) between the App Store and non-App Store versions.

**Comment by mmattioli** [comment]
@lee-dohm the interest is more in the distribution of the app in large enterprise and education environments than it is in discoverability. Earlier this year at Apple's WWDC, [it was announced that Microsoft Office, BBEdit and Panic Transmit will be returning to the Mac App Store because of sandboxing improvements](https://9to5mac.com/2018/06/04/new-sandboxing-improvements-bring-transmit-back-to-the-mac-app-store/).

**Comment by mmattioli** [comment]
@lee-dohm bumping this

**Comment by lee-dohm** [comment]
Even assuming that the sandboxing would be a complete non-issue, there is still additional overhead in having another distribution mechanism as well as other concerns around review periods and other minutiae. We simply don't have the resources to take this on at this time and have no plans to do so for the foreseeable future.
