### ISSUE TITLE
Paste with formatting

### ISSUE THREAD

**Issue by jonmagic** [atom/atom#1825]
When I paste a snippet of code that has indentation I want my editor to be smart enough to correctly indent things for me.

### Example 1

Steps to reproduce:

1. Go to https://github.com/atom/atom/blob/master/src/clipboard.coffee
1. Copy some indented text but on the first line just go to the beginning of the text, not the beginning of the line
1. Paste the text into Atom at an indentation level different than what it should be indented at

![](http://cl.ly/image/3G1A3u3P043a/paste.gif)

### Example 2

When you go across windows it loses the indentation magic.

![](http://cl.ly/image/1R0T2J0j111z/paste2.gif)

**Comment by jackson-sandland** [comment]
What is the solution to this...
