### ISSUE TITLE
Atom Crash Problem (Segmentation fault)

### ISSUE THREAD

**Issue by hhlp** [atom/atom#18268]
### Prerequisites

    * [x] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [x] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

all command give me segmentation fault :

atom --version (display nothing without error)
atom --safe
atom --clear-window-state

this works well :

> apm links
> 
> /home/hhlp/.atom/dev/packages (0)
> └── (no links)
> /home/hhlp/.atom/packages (0)
> └── (no links)

in /home/hhlp/.atom/packages I have 37 packages

I delete config file to start fresh and nothing happenned same behaviour

### Description

I have two problem :

1.- Segmentation fault

> /usr/bin/atom: línea 157: 13874 Segmentation fault      (`core' generado) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

2.- when install from flathub doesn't find .atom directory where my configuration are store (works well but without any configuration)

[Description of the issue]

### Steps to Reproduce

1. Install 
2. Execute 
3. Crash

**Expected behavior:** [What you expect to happen]

work as usual

**Actual behavior:** [What actually happens]

problem in startup

**Reproduces how often:** [What percentage of the time does it reproduce?]

always

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

I don't have problem in Fedora 28 now in Fedora 29 I've got this -> 64 bits

`Linux localhost-localdomain 4.18.14-300.fc29.x86_64 #1 SMP Mon Oct 15 13:13:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`
> atom --version (doesn't work)
> 

using the .rpm package from atom.io

> rpm -qa atom                                           
> atom-1.31.2-0.1.x86_64
> 

> apm --version (works well)
> 
> apm  2.1.1
> npm  6.2.0
> node 8.9.3 x64
> atom 1.31.2
> python 2.7.15
> git 2.19.1
> 

### Additional Information

Check if your GPU is causing the problem

atom --disable-gpu
atom --enable-gpu-rasterization --force-gpu-rasterization
atom --safe --enable-gpu-rasterization --force-gpu-rasterization

> /usr/bin/atom: línea 157: 15421 Segmentation fault      (`core' generado) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1

**Comment by solsticedhiver** [comment]
Using ubuntu 18.10, I got the same segfault when attempting to launch atom. using the .deb package from atom.io

**Comment by rsese** [comment]
Thanks for the report!  As @solsticedhiver mentioned, this was an issue with the version of glibc.  The problem was resolved in https://github.com/atom/atom/pull/18012 and the fix is available in 1.32, currently in beta.

> 2.- when install from flathub doesn't find .atom directory where my configuration are store (works well but without any configuration)

The only official installation are documented in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/).  If there's a problem installing from Flaathub, you would need to reach out to them.

Going to go ahead and close but if you still have a problem in the beta @hhlp, please let us know.

**Comment by rsese** [comment]
Just wanted to mention that [1.32.0 stable](http://blog.atom.io/2018/10/23/atom-1-32.html) has been released :v:
