### ISSUE TITLE
Recognize grammar abbreviations in Grammar selector

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#18260]
_From @MoritzKn on January 4, 2018 23:24_

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It would be great if the ordering would be influenced by abbreviations. 

### Steps to Reproduce

1. <kbd>ctrl</kbd><kbd>shift</kbd>+<kbd>L</kbd>
2. enter `js`

**Expected behavior:**
E.g. if I enter `js` I would expect Java Script to be the first result since it's an exact abbreviation. I would expect this for other abbreviations too.

**Actual behavior:**
I get the following grammars:
1. `JSON`
2. `JSDoc`
3. `JSON (Twig)`
4. `Java Properties`
5. `Javascript (Twig)`
6. `JUnit Test Report`
7. `JavaScript`

I could understand if it were on the 4th place since the 1st to 3rd places match on the beginning.
However I would prefer if abbreviations would be rated just a little less then a full match.

**Reproduces how often:**
100%

### Versions
`$ atom --version`
```
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

`$  apm --version`
```
apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.23.1
python 3.6.4
git 2.15.1
```

 `$ uname -a`  (OS)
```
Linux arch-pc 4.14.10-1-ARCH #1 SMP PREEMPT Fri Dec 29 20:17:35 UTC 2017 x86_64 GNU/Linux
```
  

_Copied from original issue: atom/grammar-selector#53_

**Comment by maxbrunsfeld** [comment]
_From @50Wliu on January 5, 2018 0:29_

Yeah, I've done this way too much myself.

**Comment by maxbrunsfeld** [comment]
_From @50Wliu on January 5, 2018 0:30_

I wonder is switching to fuzzaldrin-plus in atom-select-list would solve the case you're looking at.

**Comment by maxbrunsfeld** [comment]
_From @MoritzKn on January 6, 2018 0:0_

That seems to be what `fuzzaldrin-plus` promises. Do you think adding a `useAlternateScoring` config to use `fuzzaldrin-plus` like it is the case in the [fuzzy-finder](https://github.com/atom/fuzzy-finder/blob/5ad5a295eafe418aa4b8d7ceaa9b200b253a516d/lib/fuzzy-finder-view.js#L64) would be a good idea? Or would you prefer not to add a new option for this?

**Comment by MoritzKn** [comment]
@maxbrunsfeld may I ask why I ask why this was moved? The issue concerned the grammar-selector or maybe fuzzaldrin. Why is it in core now?

**Comment by Ben3eeE** [comment]
@MoritzKn We are moving some packages to core https://github.com/atom/atom/blob/master/docs/rfcs/003-consolidate-core-packages.md

**Comment by maxbrunsfeld** [comment]
See https://github.com/atom/atom/pull/18256.
