### ISSUE TITLE
Running repeatedly occurs when my package is running.

### ISSUE THREAD

**Issue by xxKarina** [atom/atom#18262]
### Prerequisites

- Running the generator by invoking the command palette and searching for "Generate Package".
- Name it yxx-test.
- Atom package.json files have their own additions like activationCommands, when you change the key of it, you can also running by your hot key
- but when you running your package by clicking the menu, and then you want to close it by using your hot key, it will fail, it will running again

**Comment by rsese** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/package-generator repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Also, please fill out the issue template when you reopen the issue - the information in the template is very helpful for us when investigating issues.  For example, I think I followed the steps you described but couldn't reproduce the problem, so detailed steps to reproduce would be helpful.

Thanks for meeting us half way 👍
