### ISSUE TITLE
/usr/bin not added to PATH when starting as app (macOS)

### ISSUE THREAD

**Issue by edahlseng** [atom/atom#18299]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When starting Atom from the GUI (clicking the icon from the doc, selecting File > Reopen Project, etc.) Atom does not load the correct path. More specifically the path that it loads does not contain `/usr/bin`. This is causing several different errors when using Atom (selecting a file from tree view and choosing "Show in Finder" fails with a `spawn open ENOENT` error, git operations don't work, checking for package updates don't work, etc.) If I edit the path from the developer tools by setting `process.env.PATH = process.env.PATH + ":/usr/bin"`, then all of those actions work as expected.

When starting the application from Terminal, everything works as expected (this includes starting the application in safe mode, which is done from the command line).

I don't know if this is related to my specific system or not, but I can't find a way to fix this. I saw that Atom had problem with properly loading paths when started from the GUI in the past, but all of the relevant issues are marked as resolved now, but I'm still having the issue.

### Steps to Reproduce

1. From a running instance of Atom, selected File > Reopen Project > [Any Project]
2. Right click a file
3. Show in Finder

**Expected behavior:** [What you expect to happen]

For the file to be shown in Finder.

**Actual behavior:** [What actually happens]

`spawn open ENOENT`

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time when started from the GUI

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.31.0
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.0
python 2.7.15
git 2.19.1

macOS v10.14

**Comment by lee-dohm** [comment]
Can you supply the output of `cat /etc/paths`? Because `/usr/bin` is virtually guaranteed to be included in every `PATH` that Atom would ascertain. The only case that I know of where that would not be the case is when someone removed `/usr/bin` from their `/etc/paths` file.

For more background, Atom [makes an attempt at mimicking your command-line environment](https://github.com/atom/atom/pull/11054) even when launched from the Dock. It is possible that Atom is picking up an incorrect environment, but at this point, I would be more likely to suspect a strange configuration that we could not anticipate rather than a bug in the feature in Atom.

**Comment by edahlseng** [comment]
Thanks for the help @lee-dohm.

```
$ cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

Everything there looks good as far as I can tell.

I also suspect that this would be due to a strange configuration rather than a bug, but I'm not sure what it could be. Is there a way that I can debug the environment generation to see where it's picking up the current environment? I'll have a look at that PR you linked in the meantime!

**Comment by lee-dohm** [comment]
Can you include the full contents of `process.env.PATH` both when you launch Atom from the Terminal and when you launch Atom from the Dock? I suspect that there are more differences than just `/usr/bin` and those other differences may point you to where the difference in behavior is occurring.

**Comment by edahlseng** [comment]
Sure thing. From the Dock:
```javascript
process.env.PATH = "./bin:/usr/local/bin:/usr/local/sbin:/Users/ericdahlseng/.dotfiles/bin:/Users/ericdahlseng/go/bin:/Users/ericdahlseng/Library/Python/3.7 (default, Jul 31 2018, 20:28:55) "
```

From Terminal:
```javascript
process.env.PATH = "./bin:/usr/local/bin:/usr/local/sbin:/Users/ericdahlseng/.dotfiles/bin:/Users/ericdahlseng/go/bin:/Users/ericdahlseng/Library/Python/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Wireshark.app/Contents/MacOS"
```

The default message after the Python path in the Dock instance looks particularly fishy, especially considering that /usr/bin comes after the Python path in the Terminal instance.

**Comment by lee-dohm** [comment]
This is the current code that gets the environment stuff from the shell:

https://github.com/atom/atom/blob/2f827bfc23260eece024b8f179421fa833b1834d/src/update-process-env.js#L61-L119

Take a look and see if you can see anything that might cause problems.

**Comment by thomasjo** [comment]
@edahlseng Your problems stems from this file https://github.com/edahlseng/dotfiles/blob/fcff524a7a3a66459b078ab47e04eda50ecabcd0/macos/path.zsh#L1

The sed expression does not handle the macOS bundled Python version naming scheme. Fix that and your problem should go away.

For reference, the problem file/line:
``` bash
export PATH="$HOME/go/bin:$HOME/Library/Python/$(python3 --version | sed -E 's/Python\ (.*)\.[0-9]+/\1/')/bin:$PATH"
```

**Comment by edahlseng** [comment]
Thanks for all of the help @lee-dohm and @thomasjo. I really appreciate it, especially considering that this is just a problem with my own configuration!

@thomasjo do you know why the version number is reported differently when loaded through Atom? Even if I replace `python3` with `/usr/local/bin/python3` it loads differently in Atom than it does from Terminal.

**Comment by edahlseng** [comment]
Interesting – I can reproduce the problem locally if I explicitly run `python3 --version --version`. Still not sure why it behaves differently when loaded by Atom, though... 🤔
