### ISSUE TITLE
[Atom 1.32.0] Missing documentation

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#18308]
With release 1.32.0, suddenly documentation for some classes is missing. Particularly, for event-kit classes and for `TextBuffer`

-  `CompositeDisposable`
https://atom.io/docs/api/v1.31.2/CompositeDisposable (ok) 
https://atom.io/docs/api/v1.32.0/CompositeDisposable (error 404)
-  `Disposable`
https://atom.io/docs/api/v1.31.2/Disposable (ok)
https://atom.io/docs/api/v1.32.0/Disposable (error 404)
-  `Emitter`
https://atom.io/docs/api/v1.31.2/Emitter (ok)
https://atom.io/docs/api/v1.32.0/Emitter (error 404)
-  `TextBuffer`
https://atom.io/docs/api/v1.31.2/TextBuffer (ok)
https://atom.io/docs/api/v1.32.0/TextBuffer (error 404)

It would appear that the recent conversion to JavaScript is the culprit, but I can't say why exactly this is.

**Comment by maxbrunsfeld** [comment]
Thanks so much for the report @lierdakil! Fixed via https://github.com/atom/text-buffer/pull/306 and https://github.com/atom/event-kit/pull/47.
