### ISSUE TITLE
Move syntax-selection keybinds to base

### ISSUE THREAD

**Issue by tribut** [atom/atom#18312]
## Summary

Now that the darwin hotkey for `editor:select-smaller/larger-syntax-node` is `alt-up/down` (instead of the earlier `ctrl-alt-up/down`) there is no reason to restrict it to OSX. I'm suggesting to [move these hotkeys to base](https://github.com/tribut/atom/commit/509e36fa8a4d036f6fd310938cf4ece2d94be8db) so users on linux and windows can make use of the feature as well.

## Motivation

There is currently no default shortcut assigned for non-OSX folks and `alt-up/down` does not seem to cause conflicts.

**Comment by maxbrunsfeld** [comment]
I would love to have these bindings be cross-platform. I think I was hesitant to add new `Alt` bindings on Linux and Windows because I wasn't sure if they would conflict with bindings that might exist in the OS.

/cc @daviwil @Ben3eeE @thomasjo @smashwilson 

Are you aware of any problems with adding the `alt-up` and `alt-down` key bindings on Windows or Linux?

**Comment by Arcanemagus** [comment]
For Windows I'm not seeing anything relevant in the:
* [List of Accessibility shortcuts](https://support.microsoft.com/en-us/help/13810/windows-keyboard-shortcuts-accessibility)
* [List of Windows shortcuts](https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts)
    * File Explorer has <kbd>Alt</kbd> + <kbd>Up</kbd> for "View the folder that the folder was in"
* [List of Windows app shortcuts](https://support.microsoft.com/en-us/help/13805/windows-keyboard-shortcuts-in-apps)
    * Paint 3D has <kbd>Alt</kbd> + <kbd>Up</kbd> / <kbd>Down</kbd> for panning

Wikipedia has [it listed](https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#User_interface_navigation_(widgets_and_controls)) for "Expand a drop-down list".

**Comment by Ben3eeE** [comment]
In addition to what @Arcanemagus said it works fine to add this to your personal keymap on Windows:

```
'atom-text-editor:not([mini])':
  'alt-up': 'editor:select-smaller-syntax-node'
  'alt-down': 'editor:select-larger-syntax-node'
```

**Comment by maxbrunsfeld** [comment]
👍 Ok, it sounds like it's fine to add these shortcuts on windows. And I'm not seeing any issues mentioned about alt-arrow key bindings on linux, so unless there's any objection, I will do as @tribut suggested.

@tribut In the meantime, you can achieve the same effect by adding [the snippet](https://github.com/atom/atom/issues/18312#issuecomment-432750212) that @Ben3eeE shared to your `$HOME/.atom/keymap.cson` file.

**Comment by daviwil** [comment]
I think <kbd>Alt + Up/Down</kbd> should be fine on Windows and Linux!
