### ISSUE TITLE
Atom crash every time on MAC Mojave 

### ISSUE THREAD

**Issue by micheletolve** [atom/atom#18322]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom 1.32.0 on macOS Mojave 10.14 crashes every time after launch and open project folder

### Steps to Reproduce

1. Launch Atom 1.32.0 on Mojave 10.14
2. Open project folder
3. Wait for up to 30 seconds / 1 minute
3. It crashes.

**Expected behavior:** [What you expect to happen]
Not to crash every time.

**Actual behavior:** [What actually happens]
Crash every time.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of time

### Versions
Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0
python 2.7.10
git 2.17.1

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

[Atom Helper_2018-10-25-095016_XXX.crash.txt](https://github.com/atom/atom/files/2514138/Atom.Helper_2018-10-25-095016_XXX.crash.txt)

**Comment by rsese** [comment]
Thanks for the report - it looks like the `Prerequisites` section of the issue template wasn't checked off, can you reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?  Also, did you try any of the other [debugging steps](https://flight-manual.atom.io/hacking-atom/sections/debugging)?

Also, do you happen to have a `.git/` directory in your home folder?

```
ls -ld ~/.git
```

**Comment by micheletolve** [comment]
Yes i have a `.git/` directory in my home.

**Comment by mattzzw** [comment]
Same here (Mojave, not `.git` in my home directory).
Safe mode did not help, renaming .atom did not help, --clear-window-state did not help.

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

Console.app also tells me that `atom helper` is the culprit.

I can pretty much reproduce the crash while typing something along the lines of  `['``']` in markdown syntax file.

**Comment by rsese** [comment]
@mattzzw - the crashed thread from your crash log looks like https://github.com/atom/atom/issues/15912 if you want to subscribe there.  Can you let us know if you used the `Locales` spell-check setting in https://github.com/atom/atom/issues/15912?

**Comment by mattzzw** [comment]
@rsese  - thanks for pointing me at #15912. I added the requested info.

**Comment by rsese** [comment]
@ogbdn - go ahead and open a new issue with the template filled out and we can take a look, thanks!

**Comment by fmonday** [comment]
Same problem, except force quitting Atom doesn't resolve the problem, and hard rebooting the mac is required. Restarting Atom reproduces the problem immediately upon starting the application. Deleting just the Atom application and reinstalling causes the problem to recur immediately. Deleting all Atom support files and reinstalling Atom yields a working program for about a day, then the whole thing occurs again.
