### ISSUE TITLE
Unstyled Scrollbars When Plugging in Mice

### ISSUE THREAD

**Issue by matthewwithanm** [atom/atom#18320]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In some situations, `scrollbar-style` doesn't notice changes to (or report correct values for) `preferredScrollStyle`.

Related: #15350

cc @hansonw 

### Steps to Reproduce

1. Have Magic Mouse active on my computer.
2. Plug in Logitech M500 (I think?) mouse.
3. Turn off Magic Mouse.

**Expected behavior:** [What you expect to happen]

The "scrollbars-visible-always" class is added to the workspace element.

**Actual behavior:** [What actually happens]

It's not.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% with these repro steps.

### Versions

MacOS 10.13.6 (High Sierra)

```
$ atom --version
Atom    : 1.31.1
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ apm --version
apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.1
python 2.7.10
git 2.13.5
```

### Additional Information

It turns out that if you do the observation from the main process instead, it *does* get the correct values! In other words:

```js
const scrollbarStyle = require('scrollbar-style');
const remoteScrollbarStyle = require('electron').remote.require('scrollbar-style');
assert(scrollbarStyle.getPreferredScrollbarStyle() === remoteScrollbarStyle.getPreferredScrollbarStyle()) // throws!
```

Using `remote.require()` is [the workaround we'll be using in Nuclide][3] until this is fixed in core. It's worth noting, though, that because of [Chromium Bug 454346][1] (which was fixed in Chromium 62—Atom 1.32 uses Chromium 61), this isn't sufficient for a complete fix. The scrollable elements must also be forcefully redrawn. See [this commit][2] for more details.

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=454346
[2]: https://github.com/facebook/nuclide/commit/0a860a29acfa7ee4294907b92c658aa88b3be92e
[3]: https://github.com/facebook/nuclide/tree/c3166db75e234e1fcee9df2476afeb392bc16806/pkg/nuclide-scrollbar-style-fix

**Comment by rsese** [comment]
Thanks @matthewwithanm 👍  Just noting that I can't reproduce with my setup, I have a Magic Trackpad and some other Logitech mouse on macOS 10.12.6 with Atom 1.34.0-nightly5 (I can still reproduce https://github.com/atom/atom/issues/15350).  After following your repro steps, the scrollbars are still styled and I see the `scrollbars-visible-always`class on `<atom-workspace>`.

Anything I might be missing?  Does the macOS scrollbar setting (`Always`, `When Scrolling`, etc) matter?  I tried both `Always` and `When Scrolling`.
