### ISSUE TITLE
Commenting javascript code in a html file applies html comment

### ISSUE THREAD

**Issue by mindrones** [atom/atom#18325]
### Description

After the latest update I'm getting html comments within <script> tags.

### Steps to Reproduce

- create an html file with a script

```html
<script>
  const foo = 2;
</script>
```

- move the cursor to the javascript line and toggle comment (cmd-/)

**Expected behavior:** [What you expect to happen]

```html
<script>
  // const foo = 2;
</script>
```

**Actual behavior:** [What actually happens]

```html
<script>
  <!-- const foo = 2; -->
</script>
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always, after the latest update to 1.32.0.

Same happens for block comments, *very very* annoying as you need to comment line by line or comment blocks typing `/*` and `*/`.

### Versions

`atom --version`

Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

`apm --version`

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0
python 2.7.15
git 2.18.0

MacOS High Sierra 10.13.6 (17G65)

**Comment by maxbrunsfeld** [comment]
Oops, sorry for breaking this @mindrones! Fixing now.

**Comment by maxbrunsfeld** [comment]
This fix will go out in Atom 1.32.1.

**Comment by mindrones** [comment]
@maxbrunsfeld nice thanks!

Not sure if this is related but syntax highlighting is broken too 1.32.0.

<img width="411" alt="screen shot 2018-10-29 at 14 12 06" src="https://user-images.githubusercontent.com/1309648/47655381-ce69b400-db84-11e8-8652-0c175a7cde46.png">

Can you check this? If needed I can open a new issue, thanks!

**Comment by Ben3eeE** [comment]
@mindrones We are tracking this issue in https://github.com/atom/atom/issues/18327 and working on solving it in https://github.com/atom/language-css/pull/156

**Comment by mindrones** [comment]
@Ben3eeE 👍 perfect thanks!
