### ISSUE TITLE
Code Folding is Unreliable in Atom 1.32.0 with Tree Parser

### ISSUE THREAD

**Issue by JosephTLyons** [atom/atom#18324]
I filled out a report for erroneous code folding in the Tree Sitter Github repo, as I wasn't sure if I should report it there or here, but [I'm placing the link to that report ](https://github.com/tree-sitter/tree-sitter/issues/208), in case that was the wrong place to report it.

**Comment by Aerijo** [comment]
@JosephTLyons Yep, the right place is in the Atom repo. Tree-sitter only makes a syntax tree for the code, how this is used for features like code folding is specific to Atom.

Could you move the contents here and close the other issue?

**Comment by Ben3eeE** [comment]
The correct place to report this is https://github.com/atom/language-c. Please open a new issue there will the full issue template.

Also please include the the example code that you can fold in text.
