### ISSUE TITLE
Atom crashes when opening on Ubuntu 18.10

### ISSUE THREAD

**Issue by archiesmuts** [atom/atom#18328]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom (Snap package) crashes approximately 20 seconds after launching

### Steps to Reproduce

1. Launch from terminal
2. Launch in safe mode
3. Uninstall  snap package and reinstall snap package
4. Uninstall snap package and Install latest .deb package from Atom website
5. Uninstall latest .deb package and install 1.33 beta package
6. Uninstall 1.33 beta and install earlier version 1.31.2
7. Removed all installed packages from ~/ .atom folder
8. Disconnected second monitor

**Expected behavior:** [What you expect to happen]
Expect atom to launch successfully
**Actual behavior:** [What actually happens]
Crashes after 20 seconds

**Reproduces how often:** [What percentage of the time does it reproduce?]
Reproduces 100% of the time

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

OS: ubuntu 18.10 upgraded from 18.04 on October 18th 2018
$ atom --version
Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

$ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0
python 2.7.15+
git 2.19.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!

> Atom (Snap package) crashes approximately 20 seconds after launching

The Snap package is unofficial and not supported by us but it sounds like you installed with the official .deb and Atom still crashes for you after updating to 18.10?  Did Atom work on 18.10 with a previous version of Atom?

And just so we're on the same page, now that the Snap install is removed, can you install 1.32 from the official .deb (it looks like you installed  1.31.2 last)?

Then after that, can you confirm whether or not any of the [debugging suggestions](https://flight-manual.atom.io/hacking-atom/sections/debugging/) makes any difference with 1.32?  For example, safe mode, temporarily resetting to factory defaults, and clearing saved state (note that any unsaved data will be lost in this case).

**Comment by archiesmuts** [comment]
Thank you for the quick response.
If you look at point #4 I downloaded the version 1.32 from the Atom website and experienced the same crash. 
I suspect it could be the latest updates in Ubuntu as shortly after the upgrade I couldn’t perform a git push/pull from Atom throwing errors about missing libraries. 

However I realized that I hadn’t tried “Clearing Saved State” as suggested under the debugging section. After executing $atom  --clear-window-state the problem seems to have resolved. I was reluctant to do this the first time around. 

Thank you again or the excellent response.

**Comment by rsese** [comment]
Awesome, glad you have things sorted out :+1:  About:

> I suspect it could be the latest updates in Ubuntu as shortly after the upgrade I couldn’t perform a git push/pull from Atom throwing errors about missing libraries.

That issue is being tracked in https://github.com/atom/github/issues/848 and as mentioned in https://github.com/atom/github/issues/848#issuecomment-433974759,  this should be resolved in the next hotfix release.
