### ISSUE TITLE
ANSI C operators not being highlighted properly

### ISSUE THREAD

**Issue by Shompi** [atom/atom#18347]
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Math Operators not being highlighted as in the previous syntax highlight.

### Steps to Reproduce
Just open a new .c file in atom, inside int main(){
//type something like int b=5 or if(b>=5) you will see the operators not being highlighted. 
//Im going to attach some images.
}

**Expected behavior:**
Operators being highlighted
**Actual behavior:** [What actually happens]
Operators are not being highlighted.
**Reproduces how often:** [What percentage of the time does it reproduce?]
100% only when launching atom in normal mode.
### Versions
atom 1.32.0
Windows 10.

### Additional Information
Packages are not causing this issue because I disabled all of them, and also did a factory reset to atom.
I liked the old syntax highlight theme (See image number 1), if there's any way that I can use it I would like to know.
Also when launching atom in safe mode it goes back to the previous syntax highlight theme.
Init file is all commented.

Image number 1:
![old highlights](https://user-images.githubusercontent.com/10200647/47621445-c5baa480-dad6-11e8-850e-77329d988ebc.png)
Image number 2: Operators not being highlighted in the new syntax highlight theme.
![current highlight](https://user-images.githubusercontent.com/10200647/47621449-e97dea80-dad6-11e8-936a-d38312f00d6f.png)

**Comment by Ben3eeE** [comment]
Thanks for reaching out and sorry for the regression 🙇 

The fix for this issue will ship in Atom 1.32.1.

**Comment by Shompi** [comment]
Re-open this because this operator ">" is not being highlighted with the new tree sitter parser.
![atom_2018-11-01_05-32-58](https://user-images.githubusercontent.com/10200647/47841269-d188be00-dd97-11e8-80e7-f388a98e3a2e.png)

**Comment by Ben3eeE** [comment]
@Shompi Thanks for the report 🙇 I opened a PR to fix this issue https://github.com/atom/language-c/pull/303

I will leave this issue closed.

**Comment by Ben3eeE** [comment]
Thanks again for the report 🙇 https://github.com/atom/language-c/pull/303 which contains the fix for this issue and a few more issues is going to be included in Atom 1.32.2
