### ISSUE TITLE
Tree-sitter parsing breaks function-like macro syntax highlighting in C

### ISSUE THREAD

**Issue by prati0100** [atom/atom#18346]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The syntax highlighting for C breaks when using tree-sitter parsers for function-like macros in global scope. The highlighting works fine when using these macros in a function scope.

### Steps to Reproduce

1. Use a function-like macro in global scope
2. In my case, I am pasing two strings as parameters to the macro and they are not highlighted properly. They work correctly when not using tree-sitter parser. Also, the macro M_BUSDMA_XEN should be highlighted orange if we follow how the tree-sitter highlights these type of macros.

**Expected behavior:** The macro name should be blue and the strings should be green
![atom without tree-sitter](https://user-images.githubusercontent.com/8817931/47616605-5304f580-dae5-11e8-9bc7-6eb5a3db757e.png)

**Actual behavior:** The macro name is orange and the strings are colored blue.
![atom with tree-sitter](https://user-images.githubusercontent.com/8817931/47616625-89db0b80-dae5-11e8-89be-d29bfc8ac95f.png)

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
`atom --version`:
Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

`apm --version`:
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0
python 2.7.12
git 2.18.0

OS:
Ubuntu 16.04

Kernel:
Linux 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Shompi** [comment]
Same thing happened to me

Here you can see the old syntax highlight (most likely in the type of variable and symbols =<>)
![old highlights](https://user-images.githubusercontent.com/10200647/47620867-6ce70e00-dace-11e8-8123-221c8339f3a9.png)
And Here you can see how it looks right now:
![current highlight](https://user-images.githubusercontent.com/10200647/47620870-7e301a80-dace-11e8-90b7-3ad894689e3f.png)

The problem gets fixed when I launch atom from the CMD in safe mode, but that means that I can't use any packages that I use when launching atom normally.

**Comment by prati0100** [comment]
@Shompi in the case of int and char being highlighted differently, it might be intentional. They are being highlighted as types rather than keywords. It is regression, but I'll wait to hear from the people involved in the development.

But in my case, the entire highlighting is completely off. The string is being highlighted as a type, which is a much more severe problem IMO.

**Comment by Ben3eeE** [comment]
@Shompi Primitive types being highlighted differently is intentional. All operators not being highlighted is not intentional. Please open a new issue for this though so we can take a look 🙇

**Comment by maxbrunsfeld** [comment]
Thanks for the reports! Both of these problems will be fixed in 1.32.1, which I think we'll ship within a week.

**Comment by openformatproj** [comment]
This issue is still present. To reproduce it, define a global function macro

```
#define IFERR(RET) \
if (RET<0) {

#define CONTINUE \
  continue; \
}
```

and instantiate it

```
IFERR(bytes_red)
 errsys("Ricezione nuova richiesta");
CONTINUE;
```

result

![atom syntax](https://user-images.githubusercontent.com/15074240/50513576-e6808580-0a98-11e9-9f8f-a6b8033829cc.PNG)

Atom Version: 1.33.1
OS: Ubuntu 18.04, Windows 10

**Comment by 50Wliu** [comment]
@openformatproj can you please open a new issue on the https://github.com/atom/language-c repository? Thanks!
