### ISSUE TITLE
Uncaught TypeError: Cannot destructure property `itemHeight` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by Nomklong** [atom/atom#18350]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot destructure property `itemHeight` of 'undefined' or 'null'.

```
At C:\Users\WorkByThai001\AppData\Local\atom\app-1.32.0\resources\app\static\<embedded>:14

TypeError: Cannot destructure property `itemHeight` of 'undefined' or 'null'.
    at SuggestionListElement.scrollSelectedItemIntoView (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:1977425)
    at SuggestionListElement.renderSelectedItem (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:14:1977210)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.32.0/resources/app/static/<embedded>:11:322430)
```

### Commands

```
     -0:08.1.0 editor:select-to-end-of-word (input.hidden-input)
     -0:07.7.0 core:backspace (input.hidden-input)
     -0:07.2.0 core:move-down (input.hidden-input)
  2x -0:06.8.0 core:move-right (input.hidden-input)
     -0:06.1.0 core:backspace (input.hidden-input)
     -0:05.6.0 core:move-down (input.hidden-input)
     -0:04.9.0 editor:select-to-end-of-word (input.hidden-input)
     -0:04.5.0 core:backspace (input.hidden-input)
     -0:04.1.0 core:move-down (input.hidden-input)
  2x -0:03.9.0 core:move-left (input.hidden-input)
     -0:03.4.0 editor:select-to-end-of-word (input.hidden-input)
     -0:03.0 core:backspace (input.hidden-input)
     -0:02.3.0 core:move-down (input.hidden-input)
 21x -0:02.1.0 core:move-right (input.hidden-input)
     -0:00.6.0 core:move-left (input.hidden-input)
     -0:00.1.0 core:select-right (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.33.4 
color-picker 2.3.0 
file-icons 2.1.26 
minimap 4.29.9 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by dscottboggs** [comment]
I've just received a similar error:

```
Uncaught TypeError: Cannot destructure property itemHeight of 'undefined' or 'null'.
/usr/share/atom/resources/app/static/<embedded>:14

TypeError: Cannot destructure property `itemHeight` of 'undefined' or 'null'.
    at SuggestionListElement.scrollSelectedItemIntoView (/usr/share/atom/resources/app/static/<embedded>:14:1977483)
    at SuggestionListElement.renderSelectedItem (/usr/share/atom/resources/app/static/<embedded>:14:1977268)
    at ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/static/<embedded>:11:326637)
```

However, I am on Ubuntu 18.04. I just switched my install from the snap package to the official repo you guys provide, and this error came up a few minutes after the first launch.

**Comment by rsese** [comment]
@dscottboggs - does the error reproduce consistently on launch and in safe mode?  And this is 1.34.0 yes?

**Comment by dscottboggs** [comment]
I reinstalled the snap version just now and it didn't do it again. I'd say the solution if you run into this issue with Atom installed through snapd is to install it through an alternative means.

**Comment by Aerijo** [comment]
@dscottboggs Unofficial Atom distributions often have introduced bugs, because these distributors tend to upgrade components across breaking change boundaries. It's not surprising in the least when this causes errors, so that's why the official installation is the only supported one.

> However, I am on Ubuntu 18.04. I just switched my install from the snap package to the official repo you guys provide, and this error came up a few minutes after the first launch.

So this error happens on the official install but not the Snap one? That's possibly a legitimate issue. In addtion to making sure you're in safe mode and on 1.34.0 like @rsese says, you can try opening Atom from the command line with `atom --clear-window-state`. This should fix it if it's a serialisation issue (be sure to save all changes to files; this will wipe unsaved changes).

**Comment by dscottboggs** [comment]
No, I'm sorry, I phrased that wrong, the snap package was the one with the problem. When I switched to the official installation the issue went away. I haven't been able to reproduce this issue since the day I posted the original comment.
