### ISSUE TITLE
Wrong colors of variables and keywords

### ISSUE THREAD

**Issue by Vanals** [atom/atom#18353]
Not proper highlight of keywords

Today opening my React project on Atom lots of keywords were not anymore highlighted properly. They are white instead of red. This happens whit curly brackets as well.

EXAMPLE:
![Uploading Screen Shot 2018-10-29 at 09.39.05.png…]()

curly brackets, about you(being a variable) and the keyword this should be red but they are white.

ATOM VERSION:  1.32.0

**Comment by danPadric** [comment]
You may wish to review:
[https://discuss.atom.io/t/error-with-syntax-colouring/59817](https://discuss.atom.io/t/error-with-syntax-colouring/59817)

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We are working on fixing many of these issues for an upcoming hotfix release. If you have as specific issue that is not mentioned in https://github.com/atom/atom/issues/18307 or https://github.com/atom/atom/issues/18327 then please open a new issue with the full issue template so we can take a look, thanks :bowing_man:
