### ISSUE TITLE
Empty parts of the editor have a slightly different color 

### ISSUE THREAD

**Issue by isgj** [atom/atom#18356]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The background of the editor has 2 different colors depending on where the cursor is or if there is text. The empty parts of the editor looks like don't get rendered. This happens with all the dark syntax themes that come preinstalled. 

### Steps to Reproduce

1. Open a file
2. Click on different parts of the code

![atom_render](https://user-images.githubusercontent.com/20517048/47678349-d4ca5100-dbc1-11e8-8d27-2d9796f17028.gif)

**Expected behavior:** [What you expect to happen]
The background of the editor has the same color

**Actual behavior:** [What actually happens]
The background has different colors on different parts

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time with dark syntax themes

### Versions

Atom: 1.32.0
Electron: 2.0.9
Chrome: 61.0.3163.100
Node: v8.9.3

```bash
apm -v
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0
python 
git 2.17.1
```
OS: Ubuntu 18.04 x64

### Additional Information

I had this issue also with older versions of Atom. I don't remember when this appeared.

**Comment by rsese** [comment]
Thanks for the report @isgj!  And thanks for the pointer @danPadric - @isgj, please let us know if changing your Color Profile setting helps.

**Comment by isgj** [comment]
Changing to `sRGB color profile` fixed the issue, the editor renders the way it should

**Comment by rsese** [comment]
Thanks for confirming @isgj, glad that helped :+1:  For reference, see this blog post for more details about the setting:

http://blog.atom.io/2018/06/21/atom-1-28.html#support-for-custom-color-profiles
