### ISSUE TITLE
Duplicate lines sometimes wrongs

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#1835]
I'm seeing this occasionally where even with one cursor, the duplicate lines command duplicates more than one line. This GIF shows it happening twice in a row:

![duplicate-lines](https://cloud.githubusercontent.com/assets/671378/2610759/e3fef9c0-bb8f-11e3-8f53-f054a62c5ccf.gif)

**Comment by benogle** [comment]
I havent seen this in the last several months with many many duplications. @kevinsawicki reopen if you wanna
