### ISSUE TITLE
atom.config.set will erase settings when scopeSelector is "*"

### ISSUE THREAD

**Issue by UziTech** [atom/atom#18372]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

```js
atom.config.set("test.test", true, {scopeSelector: "*"}); 
```

The above command will erase all settings in the "*" selector and add `test.test: true`

### Steps to Reproduce

1. Back up your config.cson file.
2. Open debug console. (<kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd>)
3. Paste the above command into the console.
4. Press <kbd>Enter</kbd>.

**Expected behavior:**

`test.test: true` is added to your config.cson file under the "*" scope

**Actual behavior:**

All settings under "\*" scope are erased, then `test.test: true` is added to your config.cson file under the "*" scope

**Reproduces how often:** 100%

### Versions

```
Windows 10 Pro Insider Preview

Atom    : 1.33.0-beta0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0-beta0
python 2.7.14
git 2.19.1.windows.1
visual studio 2015
```

### Additional Information

related https://github.com/atom/atom/issues/14909#issuecomment-434554388

**Comment by rsese** [comment]
Thanks @UziTech :+1:   Reproduced on macOS 10.12.6 with Atom 1.34.0-nightly5.

**Comment by rafeca** [comment]
Thanks for reporting!! I've sent a PR that should fix this issue: https://github.com/atom/atom/pull/19054
