### ISSUE TITLE
[1.33.0-beta1] Typing "#" is currently broken in the beta

### ISSUE THREAD

**Issue by mmstick** [atom/atom#18376]
In 1.32.0, Typing `#` within double quotes would just enter `#`. Now, it does more than that, and for some reason inserts `#{}` with the cursor moved between the `{}` instead. This is mildly infuriating when trying to write out an expression like so:

```rust
eprintln!("{:#?}", value);
```
![peek 2018-10-31 21-32](https://user-images.githubusercontent.com/4143535/47831058-826d6980-dd54-11e8-8afd-3b17f6a91673.gif)

**Comment by Aerijo** [comment]
@mmstick I tried it just now in a new blank file, but could not reproduce. Please fill out the issue template that is given when creating an issue completely, so we know what steps to follow.

**Comment by Aerijo** [comment]
@mmstick For now, you can work around it by toggling `Settings -> Core -> Use Tree Sitter Parsers`, or alternatively disable the `bracket-matcher` package.

**Comment by maxbrunsfeld** [comment]
Wow, that's awful. It looks like a features associated with Ruby, that's happening *all* the time for some reason.

**Comment by Aerijo** [comment]
@maxbrunsfeld[See this](https://github.com/atom/bracket-matcher/blob/09a27afa873ed1a027da8da6835c8d03a4c5b801/lib/bracket-matcher.coffee#L187-L192)

**Comment by maxbrunsfeld** [comment]
Oh yeah, of course; the bracket-matcher has all of this language-specific stuff baked into it. I want to make bracket-matching work completely differently now that we have Tree-sitter, but haven't had the chance yet. I'll just fix this by keeping with the "bunch of hard-coded languages" approach in bracket-matcher.

**Comment by mmstick** [comment]
@Aerijo It's happening for me with Rust files.

**Comment by devsware** [comment]
I can reproduce that in ver. 1.32.1 too, with Javascript files (for example writing a css selector like `#my-element` produces `#{my-element}`).

Disabling bracket-matcher plugin alone doesn't seem to do the trick, while disabling the Tree Sitter Parsers restores the desired behavior.

**Comment by maxbrunsfeld** [comment]
This fix will go out in 132.2 and 1.33.0-beta2.

**Comment by loesberg** [comment]
Just installed the update, and this issue is fixed. Thank you!
