### ISSUE TITLE
When color profile is set to 'use color profile... operating system,' Atom displays an incorrect background.

### ISSUE THREAD

**Issue by AppIns** [atom/atom#18389]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The operating system palate causes very odd graphical issues on my system. The background color is only found in specific 256-pixel chunks.

### Steps to Reproduce

1. Install Atom
2. Set color profile to 'Use profile configured in the operating system' (see additional information to see exactly how I go this profile). Switching to SRGB fixes this issue.
3. Switch to any screen where there are spaces without text.

**Expected behavior:** Background should be one unified color. How it looks on srgb mode:
![image](https://user-images.githubusercontent.com/13598541/47945553-f37d6000-debf-11e8-9d21-3e3f93d1a33e.png)
![image](https://user-images.githubusercontent.com/13598541/47945560-fed08b80-debf-11e8-9a27-2d5101d82b73.png)

**Actual behavior:** There are 256x256 pixel chunks where the color is different. See images bellow.
![image](https://user-images.githubusercontent.com/13598541/47945495-a5685c80-debf-11e8-9313-4e7e868caeda.png)
![image](https://user-images.githubusercontent.com/13598541/47945519-d34da100-debf-11e8-919f-3d0e80fd436f.png)

**Reproduces how often:** 100%

### Versions

```
$ atom --version
Atom    : 1.32.0
Electron: 2.0.12
Chrome  : 61.0.3163.100
Node    : 8.9.

$ apm --version
apm  2.1.3
npm  6.4.1
node 11.0.0 x64
atom 1.32.0
python 2.7.15
git 2.19.1
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Some other users had similar issues but solutions (like forcing rasterization) didn't have any effect. The only solution I found was to change to sRGB.

I am running a Manjaro Linux system with Budgie-desktop as the DE. The theme is Arc-darker, a very popular system theme, and the icon theme is Papyrus. 

Screenfetch information:
```
$ screenfetch

 ██████████████████  ████████     appins@B-Arch
 ██████████████████  ████████     OS: Manjaro 18.0.0 Illyria
 ██████████████████  ████████     Kernel: x86_64 Linux 4.19.0-3-MANJARO
 ██████████████████  ████████     Uptime: 23m
 ████████            ████████     Packages: 1159
 ████████  ████████  ████████     Shell: bash 4.4.23
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: Budgie
 ████████  ████████  ████████     WM: BudgieWM
 ████████  ████████  ████████     WM Theme: Adwaita
 ████████  ████████  ████████     GTK Theme: Arc-Darker [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Papirus-Adapta
 ████████  ████████  ████████     Font: Cantarell Regular 12
 ████████  ████████  ████████     CPU: AMD Athlon X4 860K Quad Core @ 4x 4.23GHz
                                  GPU: AMD/ATI Ellesmere [Radeon RX 470/480/570/570X/580/580X]
                                  RAM: 3528MiB / 7999MiB
```

Thank you,
AppIns

**Comment by AppIns** [comment]
Oh, I forgot to mention that issue happens with all UI and syntax themes as well. The only way around it is to change to sRGB.

**Comment by gnarum** [comment]
I am experiencing the same issue in a fresh install of Ubuntu 18.10.
Changing to sRGB does indeed solve the issue.

**Comment by rsese** [comment]
Thanks for the report!

> Atom : 1.32.0
> Electron: 2.0.12

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!
