### ISSUE TITLE
All non-visible characters should be displayable when `showInvisibles` is enabled

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1839]
Halp ticket:
* support/b6556d18b6f511e396195226a240cace

> Control characters aren't showing up. For example, create a file in vim and type ctl+v,ctl+h to insert a backspace character in a shell script and notice that it is invisible in Atom. Maybe not _all_ invisibles should be hidden. Then again, I just started using this today, so maybe I haven't discovered the proper setting.

Screenshot time! Here's Vim:

![screen shot 2014-04-04 at 3 15 27 pm](https://cloud.githubusercontent.com/assets/38924/2615541/51595b3a-bbfb-11e3-91ed-0868ab97cb1d.png)

And here's Sublime:

![screen shot 2014-04-04 at 3 15 52 pm](https://cloud.githubusercontent.com/assets/38924/2615543/595eeebc-bbfb-11e3-9179-efed992b065c.png)

And Atom:

![screen shot 2014-04-04 at 3 16 47 pm](https://cloud.githubusercontent.com/assets/38924/2615549/697823cc-bbfb-11e3-9603-0a65a61bb8b5.png)

**Comment by ponychicken** [comment]
This has bitten me once already. (I had a control character in an html file which threw off Firefox)

**Comment by xfq** [comment]
FYI - The [Info](http://www.gnu.org/software/texinfo/manual/texinfo/texinfo.html#Info-Files) format uses a few control characters to separate nodes and provide navigational information for menus, cross references, indices, and so on.

**Comment by RayFoss** [comment]
This bug has wasted half a day of my time in two separate occasions. 
`$this­->getT`

**Comment by wfdd** [comment]
If one were so inclined to address this issue, where would they begin to look?

**Comment by RayFoss** [comment]
This is more of a problem with the chromium based renderer. The easiest solution would be to add all control characters to the Show Invisibles feature. I can't figure out what control character this is
`Here->­<-Here`

**Comment by steventen** [comment]
Do we have a plan to fix this? This bug really drives me crazy, I have to switch back to sublime every time to double check...

**Comment by va1m** [comment]
Does anybody know atom team plans to fix this problem?

**Comment by lee-dohm** [comment]
Unifying all invisibles-related enhancements and fixes under #12157. You may want to subscribe there for updates.
