### ISSUE TITLE
Different colored blocky background for dark themes

### ISSUE THREAD

**Issue by statsandthings** [atom/atom#18401]
### Description

This problem appears on Atom 1.32.1 under Ubuntu 18.04 in `atom --safe` mode. Enable a dark theme and start typing text, and the background alters between dark black, and dark grey, in large blocky chunks. Looks like an Atari 2600 game.

**Expected behavior:** One consistent background.

**Actual behavior:** See this picture.

[![enter image description here][1]][1]

  [1]: https://discourse-cdn-sjc1.com/business6/uploads/github_atom/optimized/3X/6/a/6aa7fd98ccc53af471b5dd4a2fb61423f5858262_1_690x258.png

**Reproduces how often:** All the time.

**Comment by rsese** [comment]
Thanks for the report!  If you update `Settings > Color Profile` to `Use sRGB color profile`, does that make any difference?

**Comment by statsandthings** [comment]
I will try this and get back to you in the next several days.

**Comment by rsese** [comment]
Great, glad that helped :+1:
