### ISSUE TITLE
can't install after a fresh untar

### ISSUE THREAD

**Issue by jieppu** [atom/atom#18400]
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

for every package it the same

0 info it worked if it ends with ok
1 verbose cli [ '~/user//atom-portable/resources/app/apm/bin/node',
1 verbose cli   '~/user//atom-portable/resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '~/user//.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '~/user//.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/linter-jshint/versions/3.1.9/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.9',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session 3a1d6768719c2f13
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose stack TypeError: asyncWrite is not a function
7 verbose stack     at onwrite (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:480:7)
7 verbose stack     at WritableState.onwrite (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:180:5)
7 verbose stack     at WriteStream.to [as _worker] (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/make-fetch-happen/cache.js:154:13)
7 verbose stack     at WriteStream._write (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/flush-write-stream/index.js:37:13)
7 verbose stack     at doWrite (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
7 verbose stack     at WriteStream.Writable.write (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
7 verbose stack     at WriteStream.to [as _worker] (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/make-fetch-happen/cache.js:171:25)
7 verbose stack     at WriteStream._write (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/flush-write-stream/index.js:37:13)
7 verbose stack     at doWrite (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
7 verbose stack     at WriteStream.Writable.write (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:334:11)
7 verbose stack     at WriteStream.to [as _worker] (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/make-fetch-happen/cache.js:182:19)
7 verbose stack     at WriteStream._write (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/flush-write-stream/index.js:37:13)
7 verbose stack     at doWrite (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:428:64)
7 verbose stack     at writeOrBuffer (~/user//atom-portable/resources/app/apm/node_modules/npm/node_modules/readable-stream/lib/_stream_writable.js:417:5)
8 verbose cwd /tmp/apm-install-dir-118105-8276-1ki3c6a.0xx1
9 verbose Linux 4.19.0_3
10 verbose argv "~/user//atom-portable/resources/app/apm/bin/node" "~/user//atom-portable/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "~/user//.atom/.apm/.apmrc" "--userconfig" "~/user//.atom/.apmrc" "install" "https://www.atom.io/api/packages/linter-jshint/versions/3.1.9/tarball" "--runtime=electron" "--target=2.0.9" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style"
11 verbose node v8.9.3
12 verbose npm  v6.2.0
13 error asyncWrite is not a function
14 verbose exit [ 1, true ]

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests so if you can open a new issue with the template filled out, that would be very helpful for us. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
