### ISSUE TITLE
MISDIAGNOSED: Apparent Conflict with Homebrew for macOS - Unable to install/upgrade packages

### ISSUE THREAD

**Issue by johnstonjs** [atom/atom#18418]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using macOS Mojave (10.14.1) I am unable to install or upgrade packages within the atom editor or using _apm_ when the [Homebrew](https://brew.sh) package manager is also installed.

### Steps to Reproduce

1. Install macOS command line tools: `xcode-select --install`
2. Install [Homebrew](https://brew.sh)
3. Attempt to install/upgrade any package using atom editor or _apm_

**Expected behavior:**

Installation of package _atom-ide-ui_ should be accomplished by:

```
~$ apm install atom-ide-ui
Installing atom-ide-ui to /Users/user/.atom/packages ✓  
```
This is what occurs on Mojave without Homebrew installed.

**Actual behavior:**

```
~$ apm install atom-ide-ui
Installing atom-ide-ui to /Users/user/.atom/packages                                    
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | darwin | x64
gyp http GET https://atom.io/download/electron/v2.0.9/iojs-v2.0.9.tar.gz                 
gyp WARN install got an error, rolling back install                                      
gyp ERR! install error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/install.js:193:21)                                          
gyp ERR! stack     at emitOne (events.js:116:13)                                         
gyp ERR! stack     at Request.emit (events.js:211:7)                                     
gyp ERR! stack     at Request.onRequestError (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/request/request.js:881:8)
gyp ERR! stack     at emitOne (events.js:116:13)                                         
gyp ERR! stack     at ClientRequest.emit (events.js:211:7)                               
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:387:9)              
gyp ERR! stack     at emitOne (events.js:116:13)                                         
gyp ERR! stack     at TLSSocket.emit (events.js:211:7)                                   
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:64:8)                     
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=2.0.9" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/user/.atom
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```
This is what occurs on Mojave with Homebrew installed.  Please note that the installation of macOS Command Line Tools without Homebrew does not cause this issue.

**Reproduces how often:**

On three separate Macs running Mojave, this has occurred on two with Homebrew installed and does not occur on the remaining Mac without.  The result is the same whether using the atom editor or _apm_.  The result is the same whether installing a new package or upgrading an existing.

### Versions

```
~$ atom --version
Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
~$ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python 2.7.10
git 2.9.3
```

System Version: macOS 10.14.1 (18B75)
Kernel Version: Darwin 18.2.0

### Additional Information

One one of the Macs, I've attempted to install `node-gyp` but still get the same error message.

Many of the issue reports I've searched through indicate that that similar errors are caused by network connectivity.  All of the Macs I've tested on are on the same network and are correctly configured.

In case in matters, the list of installed _brews_:
```
~$ brew list
asciidoc        cvs             git             openssl         wget                     
bash-completion cvsps           htop            p7zip           yadm                     
bison           docbook         libevent        tmux 
```

Also, I've deleted `~/.atom` and experience the same result.

**Comment by rsese** [comment]
Thanks for the report - I don't have Mojave to test with (I have Homebrew installed on macOS 10.12.6 with no problem however) but it would be great to hear if others are seeing this behavior with the same combination.   Also just to clarify, when did this behavior start (e.g. after the upgrade to Mojave, after installing Homebrew, after updating Atom, etc.)?

**Comment by johnstonjs** [comment]
Thank you for replying, and agreed that this is a strange behavior.  Since Homebrew installs into its own separate folders than the Darwin defaults, I'm surprised that it seems to be having an impact for me.

This behavior started on my iMac after installing Homebrew.  It was running the latest version of Mojave, Xcode-tools, and Atom without problem.  I hadn't used Atom in a while, but after installing Homebrew and upgrading Atom to the latest version, I started experiencing this behavior.

After getting a new MacBook, I installed Atom (and Xcode-tools) and was able to install/upgrade packages without problem.  Shortly after installing Homebrew, I experienced the same problem.

An older Mac Mini was running a previous version of Atom and wasn't experiencing this issue.  I dug into it further last night and found I had an older version of Homebrew installed as well.  When I upgraded both Homebrew and Atom, this problem manifested.

I've tried removing Homebrew, but that doesn't seem to correct the issue.  That indicates that Homebrew may not be the problem, but unfortunately I haven't been able to isolate it otherwise.

Also, I've tried reverting to prior version of Atom without successfully resolving the issue.

If I can get some time this weekend, I may do a fresh install of Mojave on one of the systems and identify the exact point at which this behavior starts occurring.

**Comment by johnstonjs** [comment]
How embarrassing...

I figured out that Homebrew, at least, is not the root cause.  Its caused by unreachable hosts (at least from my network) likely caused by the Adblock tool running on my router.  I'm not sure why it only seems affect it when certain tools are installed, but this isn't a problem with Atom.

Thanks again for the great tool and quick response.  Sorry to have wasted your time.

**Comment by Arcanemagus** [comment]
Thanks for reporting back with the cause!
