### ISSUE TITLE
Writing tests for Tree-sitter grammars

### ISSUE THREAD

**Issue by Aerijo** [atom/atom#18443]
## Summary

Requesting API methods to easily parse text and access the scopes it's given when using a Tree-sitter grammar. I.e., a `tokenizeLine` equivalent.

## Motivation

The TS grammar has a large set of tests already, but we are currently not testing how the tree is translated into scopes by Atom. While the tree is generally more useful, the scopes are important for syntax highlighting and backwards compatibility with existing scope based packages.

## Describe alternatives you've considered

I tried accessing it in a test as follows (for `language-javascript`), but it's ugly and the scope is just reported as `source.js` for everything
```cson
# spec/tree-sitter-javascript-spec.js
fs = require 'fs'
path = require 'path'
{ Range } = require 'atom'
TextEditor = null
buildTextEditor = (params) ->
  if atom.workspace.buildTextEditor?
    atom.workspace.buildTextEditor(params)
  else
    TextEditor ?= require('atom').TextEditor
    new TextEditor(params)

describe "JavaScript grammar", ->
  grammar = atom.grammars.grammarForScopeName("source.js")
  languageMode = atom.grammars.languageModeForGrammarAndBuffer(grammar, buildTextEditor({}).buffer)


  beforeEach ->
    atom.config.set('core.useTreeSitterParsers', true)

    waitsForPromise ->
      atom.packages.activatePackage("language-javascript")

    runs ->
      grammar = atom.grammars.grammarForScopeName("source.js")
      languageMode = atom.grammars.languageModeForGrammarAndBuffer(grammar, buildTextEditor({}).buffer)

  it "parses the grammar", ->
    expect(grammar).toBeTruthy()
    expect(grammar.scopeName).toBe "source.js"

  describe "assignment", ->

    it "tokenizes", ->
      languageMode.buffer.buffer.setText("let foo = 5;")
      tree = languageMode.parse(grammar.languageModule, null, new Range([0,0], [Infinity, Infinity]))

      expect(tree.rootNode.type).toBe "program" # no point to this; just confirming it's as expected

      expect(languageMode.scopeDescriptorForPosition({row: 0, column: 1}).scopes).toEqual ["source.js", "storage.type"]
```

## Additional context

/cc @maxbrunsfeld. I did try to get it working before resorting to this issue.

**Comment by maxbrunsfeld** [comment]
> the scope is just reported as `source.js` for everything

If you want, you can test the scopes similarly to [what we do](https://github.com/atom/atom/blob/b3d3a52d9e4eb41f33df7b91ad1f8a2657a04487/spec/tree-sitter-language-mode-spec.js#L47-L55) in the tests for `TreeSitterLanguageMode`, using `TextEditor.tokensForScreenRow`. This method is private, but I believe all of the tests for the TextMate grammars already used private APIs.

**Comment by maxbrunsfeld** [comment]
Alternatively, you can use the public `scopeDescriptorForBufferPosition` API, but that is more suited for querying one particular point in the buffer, as opposed to all of the tokens for a line.
