### ISSUE TITLE
Install on linux fails with error 

### ISSUE THREAD

**Issue by ZenwalkerD** [atom/atom#18458]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
[2018-11-18T16_57_29_799Z-debug.log](https://github.com/atom/atom/files/2593023/2018-11-18T16_57_29_799Z-debug.log)

   * [X]  Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [X]  Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Installing Atom on Slackware 14.2 X64 results in error

### Steps to Reproduce

1. Run command as root account `script/build --build-dir /tmp/atom-build/ --install`

**Expected behavior:** 
Compilation successful with installation done to proper paths.

**Actual behavior:**
Compilation succeeds
doParallel preinstall succeeds
Install phase completed
PostInstall fails

**Reproduces how often:**
Every time under root and non root account. Both times, latest Git repo cloned.

### Versions
Latest Git Clone of Atom

> Linux darkstar.example.net 4.14.47 #1 SMP Wed May 30 19:35:39 CDT 2018 x86_64 Intel(R) Core(TM) i7 CPU       M 640  @ 2.80GHz GenuineIntel GNU/Linux

### Additional Information
Following is the error output:
> 19704 verbose stack Error: dugite@1.78.0 postinstall: `node ./script/download-git.js`
19704 verbose stack Exit status 1
19704 verbose stack     at EventEmitter.<anonymous> (/root/Public/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
19704 verbose stack     at emitTwo (events.js:126:13)
19704 verbose stack     at EventEmitter.emit (events.js:214:7)
19704 verbose stack     at ChildProcess.<anonymous> (/root/Public/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
19704 verbose stack     at emitTwo (events.js:126:13)
19704 verbose stack     at ChildProcess.emit (events.js:214:7)
19704 verbose stack     at maybeClose (internal/child_process.js:925:16)
19704 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
19705 verbose pkgid dugite@1.78.0
19706 verbose cwd /root/Public/atom
19707 verbose Linux 4.14.47
19708 verbose argv "/root/Public/atom/apm/node_modules/atom-package-manager/bin/node" "/root/Public/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/root/.atom/.apm/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "--runtime=electron" "--target=2.0.12" "--dist-url=https://atom.io/download/electron" "--arch=x64"
19709 verbose node v8.9.3
19710 verbose npm  v6.2.0
19711 error code ELIFECYCLE
19712 error errno 1
19713 error dugite@1.78.0 postinstall: `node ./script/download-git.js`
19713 error Exit status 1
19714 error Failed at the dugite@1.78.0 postinstall script.
19714 error This is probably not a problem with npm. There is likely additional logging output above.
19715 verbose exit [ 1, true ]

Attached is the log file.
[2018-11-18T16_57_29_799Z-debug.log](https://github.com/atom/atom/files/2593025/2018-11-18T16_57_29_799Z-debug.log)

**Comment by rsese** [comment]
Thanks for the report!  What SHA are you building from?  I just built from a384dde3 on Ubuntu 18.04 and didn't see this error.  Also, if you run `./script/clean` and then build again, do you still get the same error?

**Comment by ZenwalkerD** [comment]
@rsese 
I took the latest master branch. Even again i tried yesterday night by cloning again. Got the same error. 
This error i get in the first instance itself, so i dont think cleaning script needs to be run. Right?
