### ISSUE TITLE
Atom - script package problem

### ISSUE THREAD

**Issue by javaboi03** [atom/atom#18457]
Im trying to run python 3 code. For some reason small things such as 
`print("hello")`
but this just loads forever ....
import time

```
signs = ["|", "/", "-", "\\"]
while True:
    for i in range(4):
         print(signs[i].format(i), end = '\r', flush = True)
         time.sleep(.5)
        
```                          

I would be very pleased if someone could help me

**Comment by rsese** [comment]
Thanks for reaching out - since this is an issue with a community package, please report on the package repository if an issue for this problem doesn't already exist: https://atom.io/packages/script.
