### ISSUE TITLE
Scope of cursor at end of line

### ISSUE THREAD

**Issue by Aerijo** [atom/atom#18463]
### Description

The scope of the cursor is taken to be of the character to the right of it. This works most of the time, but can have unexpected behaviour when the cursor is at the end of a line and scopes do not extend to the newline character.

E.g., in [this issue](https://github.com/atom/autocomplete-plus/issues/1006) the TS parser does not count the newline as part of the comment, so autocomplete suggestions were not suppressed when typing at the end of the line. I raised [this issue](https://github.com/tree-sitter/tree-sitter-javascript/issues/87) to suggest a fix, but decided this is more general than comments.

I think Atom should in general use the left character if the next is a newline. This behaviour matches the TextMate grammars, but I'm not sure if that's because they apply the scope to the newline character or because they already do this.

It potentially makes the following confusing, but it also makes sense in a way (and matches TextMate behaviour, so not really confusing at all). Here, `|` is the cursor (not a character), and the scopes are how TextMate handles it
```js
// End of line: 'source string' 
"foo"|

// Not end of line: 'source'
"foo"| bar 
```

/cc @maxbrunsfeld This falls under Tree-sitter, and I've made my argument.

**Comment by maxbrunsfeld** [comment]
> I think Atom should in general use the left character if the next is a newline.

> It potentially makes the following confusing, but it also makes sense in a way (and matches TextMate behaviour, so not really confusing at all).

Yeah, I guess I'm cool with that.
