### ISSUE TITLE
Specific project keeps project pane from opening more than two files

### ISSUE THREAD

**Issue by SSPJ** [atom/atom#18476]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On Ubuntu 18.04, [this repo](https://github.com/open-craft/configuration) when opened in Atom, allows me to click on two files in the sidebar. Both will open but a third won't. The filename I click highlights, but nothing opens.

There is nothing in the console log. Additionally, when trying this outside of safe mode, if I press ctrl-alt-p to bring up my project switcher, it can't find any projects.

Other repos work fine.

### Steps to Reproduce

1. Clone [this repo](https://github.com/open-craft/configuration)
2. Open in Atom
3. Try to open files

**Expected behavior:** Files to open when clicked on

**Actual behavior:** Nada

**Reproduces how often:** Always for me

### Versions

Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 2.7.15rc1
git 2.17.1

**Comment by SSPJ** [comment]
Extra note: opening a different repo in Atom, then switching to the problem repo from the other using my project switcher cleared the issue.

**Comment by rsese** [comment]
Thanks for the report!  I was unable to reproduce on Ubuntu 18.04 with 1.32.1.

So now that the issue cleared up after using whichever project manager/switching community package you have installed, you can no longer reproduce?

And just to clarify, were you able to reproduce in safe mode?

**Comment by rsese** [comment]
Hmm not sure what the issue could be - I tried to reproduce again but couldn't and haven't seen any other reports of similar behavior that I could find.

Is this the first time you've seen this behavior, in Atom 1.32.1 and things worked ok before?  Any difference in the recently released 1.33.0?

**Comment by SSPJ** [comment]
I've never had the issue before, no. I recently switched from XFCE to XMonad for my primary development laptop (and from Ubuntu 16.04 to 18.04). Could be an obscure window manager bug.

**Comment by rsese** [comment]
> I've never had the issue before, no. I recently switched from XFCE to XMonad for my primary development laptop (and from Ubuntu 16.04 to 18.04). Could be an obscure window manager bug.

:+1:  Since we can't reproduce and there haven't been other reports, I'll tag as needs-repro for now.
