### ISSUE TITLE
Tree-sitter code fold markers out of sync

### ISSUE THREAD

**Issue by Aerijo** [atom/atom#18489]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On nightly, the code fold arrows in the line gutter remain in place, even when the text changes line. These arrows no longer do anything.

### Steps to Reproduce

1. Open a JS file
2. Make something foldable
```js
function foo() {
  
}
```
3. Confirm it folds normally, and unfold
4. Insert a newline at the start of the first line
5. Try to fold the function again

**Expected behavior:** [What you expect to happen]

Fold marker shifts with text

**Actual behavior:** [What actually happens]

Fold marker stayed in top line

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

1.34.0-nightly18

### Additional Information

/cc @maxbrunsfeld 

This was in safe mode, so I'm 99% sure it's not caused by me messing with the folding logic (which I am currently massacring).

Also, am I using the label right? It's not in Beta / Stable yet, so no panic. I checked CONTRIBUTING.md, but it doesn't have explanations of the latest labels.

**Comment by maxbrunsfeld** [comment]
🙇 Thanks so much for the report @Aerijo.
