### ISSUE TITLE
Syntax Grammar matches incorrect file

### ISSUE THREAD

**Issue by vsoch** [atom/atom#18485]
### Description
We have a [grammar for Singularity recipe files](https://github.com/singularityhub/language-singularity) and are having a hard time matching a file type called "Singularity.*" (starting with Singularity, and matching *just* Singularity or Singularity with some extension. [Here](https://github.com/singularityhub/language-singularity/blob/master/grammars/singularity.cson) is the cson grammar file, and specifically this doesn't seem to work:

```yaml
'fileTypes': [
    'Singularity'
    'def'
]
```
We have also tried Singularity.* but it leads to the wrong behavior in both cases. For these cases, what happens is that it recognized *all* files as Singularity after a save action (see the [issue here](https://github.com/singularityhub/language-singularity/issues/4#issuecomment-441269492)). Could you please help? Thank you!

### Steps to Reproduce

1. Install the grammer
2. Create a file called Singularity and save it
3. Create other recipe files (Singularity.tag) and regular files

**Expected behavior:**
The Singularity and Singularity.tag should be highlighted

**Actual behavior:**
All files are highlighted

**Reproduces how often:** 
Always

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Versions

```bash
$ atom --version
Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```bash
$ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 3.6.4
git 2.7.4
```

### Additional Information

@tsnowlan can provide additional context, as he was helping with the issue [here](https://github.com/singularityhub/language-singularity/issues/4#issuecomment-441269492)

**Comment by Ingramz** [comment]
If you define fileTypes for a grammar, then each entry is only suffix matched against a given file path, meaning the fileTypes is just an array of file extensions that it is searching against. For a fileType `Singularity`, it will match either a file named `Singularity` or a file ending with `.Singularity`.

It is currently not possible to use this feature to prefix match file paths. However if the files for Singularity start with a common pattern, you might be able to use `firstLineMatch` to hint Atom to use your grammar.

**Comment by tsnowlan** [comment]
The problem is not so much that files named `Singularity` or `Singularity.*` are not having the right grammar assigned, it's that their presence in an Atom window causes *all other files* to have the Singularity grammar assigned when they are saved. This occurs if the filename matches `.*Singularity.*`, so it's also not just acting as a suffix.

This happens even when `'Singularity'` is the only `fileTypes` entry, matching the [language-docker](https://github.com/jagregory/language-docker/blob/master/grammars/dockerfile.cson) grammar that does not have this issue. e.g.,
```cson
'scopeName': 'source.singularity'
'name': 'Singularity'
'fileTypes': [
    'Singularity'
]
'patterns': [
    ...
]
```

There is not a lot documentation for creating these grammars, so it's certainly possible that it's some misconfigured setting somewhere but I cannot see any difference (beyond the actual syntax `patterns`) that cause this to happen for having `Singularity` as a `fileType` but not for `Dockerfile`.

**Comment by Ingramz** [comment]
Thank you for the clarification. I am now also able to confirm that any files saved after `Singularity` are also detected as Singularity after saving.

**Comment by Ingramz** [comment]
After closer inspection I noticed that there is a [script](https://github.com/singularityhub/language-singularity/blob/master/lib/main.js) which is manipulating grammars. Without it, the behavior is as expected, so I don't think there is anything wrong with the grammar file or Atom.

**Comment by vsoch** [comment]
Ah that might be it! @Ingramz do we need a script like that (or similar) or can we remove it?

**Comment by tsnowlan** [comment]
Ah, that's it. On file save it searches through all open tabs and looks for one with `Singularity` in the title, not necessarily the one being saved.

I renamed the `lib` directory, restarted window and all was well. Created new files named `Singularity` and `somefile.def` and both were correctly identified on save. I think that can be safely removed.

Thanks so much for seeing that, @Ingramz

**Comment by vsoch** [comment]
Yes huge +1! I'm not a big enough atom user to pick up on these things. I think we can close the issue - @tsnowlan do you have enough to PR to the grammar to fix the issue?

**Comment by tsnowlan** [comment]
Yup, should only take a moment

**Comment by vsoch** [comment]
Awesome, thanks again @Ingramz and @tsnowlan, closing issue here.
