### ISSUE TITLE
Support for Swift Language via Sourcekit-LSP

### ISSUE THREAD

**Issue by ios3** [atom/atom#18494]
## Summary
[SourceKit-LSP](https://github.com/apple/sourcekit-lsp)

Implementaton of Swift Support using Sourcekit-LSP

# SourceKit-LSP

SourceKit-LSP is an implementation of the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) (LSP) for Swift and C-based languages. It provides features like code-completion and jump-to-definition to editors that support LSP. SourceKit-LSP is built on top of [sourcekitd](https://github.com/apple/swift/tree/master/tools/SourceKit) and [clangd](https://clang.llvm.org/extra/clangd.html) for high-fidelity language support, and provides a powerful source code index as well as cross-language support. SourceKit-LSP supports projects that use the Swift Package Manager.

## Motivation

Support for Swift Language

**Comment by thomasjo** [comment]
Thanks for the suggestion!

There is not built-in support for Swift, but there's a community package called [ide-swift](https://atom.io/packages/ide-swift) that does provide support. It seems like they are planning to switch from their current solution to sourcekit-lsp. You can track that progress at https://github.com/elegantchaos/atom-ide-swift/issues/19.
