### ISSUE TITLE
Tree-Sitter: Tree-Sitter parser is not used with "non-default" extensions

### ISSUE THREAD

**Issue by robertrossmann** [atom/atom#18496]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

For some file extensions, when I open a file with Tree-Sitter parsers enabled, the old parser is used. Selecting the current language/grammar again re-parses the file using Tree-Sitter.

I have tested this on the following file extensions/grammars:

- `.mjs`, `.es` - JavaScript
- `.erb`, `.ruby` - Ruby

This problem **does not** occur when opening a file with the following ("default") extensions, meaning that Tree-Sitter is used immediately after opening the file (expected behaviour):

- `.js` - JavaScript
- `.rb` - Ruby

### Steps to Reproduce

1. Enable Tree-Sitter parsers
2. Create a file with any of the "offending" file extensions listed above and write some valid code for that language ([example file with offending extension here](https://github.com/strvcom/atlas.js/blob/master/packages/atlas/src/atlas.mjs))
3. Observe old parsing system being used
4. Select the currently-selected syntax using the `Set Syntax` command
5. Observe the tree-sitter parsing system being used (some colouring changes will occur in buffer)

**Expected behavior:** Tree-Sitter parsers being used all the time for all extensions associated with a language

**Actual behavior:** Tree-Sitter parsers are only being used after manually re-selecting the syntax of the currently opened file

**Reproduces how often:** 100% of the time for all "non-default" file extensions

### Versions

```
Atom    : 1.33.0-beta3
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

> **NOTE**: The term "non-default" has no meaning beyond what seems as "default" for Atom for the given language, based solely on which file extensions are properly parsed using Tree-Sitter on first opening. No further meaning implied.

I made an ugly gif showcasing the problem. 🎨 

![atom tree-sitter not being used](https://user-images.githubusercontent.com/3058150/49023672-0110c780-f198-11e8-9920-0112e86ac7bd.gif)

**Comment by Ben3eeE** [comment]
This is probably because `mjs` for example is not listed as a filetype in the tree-sitter grammar but it is in the textmate grammar:

Tree-sitter:
https://github.com/atom/language-javascript/blob/master/grammars/tree-sitter-javascript.cson#L6

TextMate:
https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson#L2-L23

**Comment by robertrossmann** [comment]
I discovered the following in my config file which I added quite some time ago:

```cson
core:
  customFileTypes:
    javascript: [
      "mjs"
      "js"
      "es"
    ]
```

Removing this setting causes Atom to properly parse my `.mjs` files using Tree-Sitter. However, the problem does not seem to have been completely caused by this since the Ruby extensions are also affected and removing the setting above did nothing to fix the problem so I'll keep this open for now.

**Comment by robertrossmann** [comment]
Update: Removing the setting actually causes Atom to still parse the file using old parsers. ⚠️ I did not test it properly. However, changing the scope name from `javascript` to `'source.js'` **does** fix the problem, meaning Tree-Sitter is now correctly used on files with these extensions.

> `javascript` was the grammar name used by Tree-Sitter in the past, that is why I had this in my config. I think the scope was renamed to `source.js` when Tree-Sitter was enabled by default, not completely sure.

**Comment by zachwaugh** [comment]
I'm seeing this same issue with plain `.html` files as well in Atom 1.34.0. Opening an existing `.html` file uses the old parser. Manually setting the syntax to HTML or creating a new file with the same content and setting the syntax to HTML will use tree-sitter.
