### ISSUE TITLE
Wrong coloring under php

### ISSUE THREAD

**Issue by sanada01** [atom/atom#18508]
### Description

It often spoils the color of long lines.

[sample.txt](https://github.com/atom/atom/files/2623666/sample.txt)

### Steps to Reproduce

1. Open sample.txt and change file format to php
2. Wrong coloring on line four end

**Expected behavior:** Correct coloring

**Actual behavior:** Wrong coloring

**Reproduces how often:** 100%

### Versions

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python
git 2.11.0.windows.1
visual studio

**Comment by thomasjo** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the [language-php](https://github.com/atom/language-php) repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us half way :+1:
