### ISSUE TITLE
allow panel option autoFocus to be used as initialFocus

### ISSUE THREAD

**Issue by UziTech** [atom/atom#18511]
## Summary

The [autoFocus](https://atom.io/docs/api/v1.32.2/Workspace#instance-addModalPanel) option for atom.workspace.addModalPanel should be able to be the object that you want focused initially instead of only focusing on the first tabbable element.

## Motivation

```js
atom.workspace.addModalPanel({item: panelElement, autoFocus: inputElement});
```

or

```js
atom.workspace.addModalPanel({item: panelElement, autoFocus: '.input-element'});
```

## Describe alternatives you've considered

The current way to get this to work is to focus the element after adding the panel

```js
atom.workspace.addModalPanel({item: panelElement, autoFocus: true});
inputElement.focus();
```

I think it makes it a little bit easier and a lot more intuitive to allow the autoFocus options to be the element that you want automatically focused.

## Additional context

[focus-trap](https://github.com/davidtheclark/focus-trap#usage) (which is used when autoFocus is set) can be passed an option for initialFocus that can be an element, selector string, or function that returns an element.

The change would be a few lines of code to check if the autoFocus option is one of those and set the initalFocus option.

https://github.com/atom/atom/compare/master...UziTech:autoFocus-element?expand=1#diff-287ffd9dadb8379157bf7474679cbbd0
```diff
-      if (panel.autoFocus) {
-        const modalFocusTrap = focusTrap(panelElement, {
+      if (panel.autoFocus !== false) {
+        const focusOptions = {
           // focus-trap will attempt to give focus to the first tabbable element
           // on activation. If there aren't any tabbable elements,
           // give focus to the panel element itself
           fallbackFocus: panelElement,
           // closing is handled by core Atom commands and this already deactivates
           // on visibility changes
           escapeDeactivates: false
-        })
+        }
+         if (panel.autoFocus !== true) {
+          focusOptions.initialFocus = panel.autoFocus
+        }
+        const modalFocusTrap = focusTrap(panelElement, focusOptions)
```

**Comment by lee-dohm** [comment]
If you wanted to submit a PR for this we would take a look at it. Given that the workaround is so trivial, implementing this is not something the team would prioritize at this point.

Thanks for the contribution!
