### ISSUE TITLE
Broken links in API TextBuffer docs

### ISSUE THREAD

**Issue by Aerijo** [atom/atom#18518]
### Description

The docs [appear now](https://atom.io/docs/api/v1.33.0/TextBuffer), but clicking [the link to the source](https://github.com/atom/text-buffer/blob/v13.15.0/Users/max/github/text-buffer/src/text-buffer.js#L62) takes you to @maxbrunsfeld's (deleted?) version.

### Steps to Reproduce

1. Click above links

**Expected behavior:** [What you expect to happen]

Docs

**Actual behavior:** [What actually happens]

Error 404

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

**Comment by maxbrunsfeld** [comment]
Wow, it's accidentally putting an **absolute** path into the link 😬

```
https://github.com/atom/text-buffer/blob/v13.15.0/Users/max/github/text-buffer/src/text-buffer.js#L62
```

I guess this is a bug in how [we're running joanna](https://github.com/atom/text-buffer/blob/master/script/generate-docs#L11-L20) in the `text-buffer` `prepublish` step.

**Comment by maxbrunsfeld** [comment]
I guess you have to pass relative paths to `joanna` so that the paths will be relative in the generated output.
