### ISSUE TITLE
[THEME|One Dark] PHP return types on closures aren't themed 

### ISSUE THREAD

**Issue by carusogabriel** [atom/atom#18512]
### Description

The return types on closures in PHP files don't theme

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/16328050/49185154-525fb900-f348-11e8-8b32-cebd3ad55aad.png)

**Expected behavior:** [What you expect to happen]

`: string` should be themed.

**Actual behavior:** [What actually happens]

`: string` isn't themed, like `: void` in the method return type.

**Reproduces how often:** [What percentage of the time does it reproduce?]

All the time.

### Versions

1.26.1

**Comment by damieng** [comment]
Actually caused by lack of support for this syntax in language-php, track at https://github.com/atom/language-php/issues/343
