### ISSUE TITLE
The directory tree is not displayed

### ISSUE THREAD

**Issue by Lwenli1224** [atom/atom#18528]
[Enter steps to reproduce:]

Atom: 1.33.0 x64
Electron: 2.0.11
OS: Mac OS X 10.14.1
Thrown From: Atom Core

### Description
The directory tree is not displayed

### Non-Core Packages
├── Stylus@3.2.0
├── activate-power-mode@2.7.0 (disabled)
├── atom-beautify@0.33.4
├── atom-ide-ui@0.13.0 (disabled)
├── atom-jade@0.3.0
├── atom-live-server@2.3.0
├── atom-material-ui@2.1.3
├── atom-react-autocomplete@0.1.10
├── atom-ternjs@0.18.3
├── atom-typescript@12.6.3
├── atom-wrap-in-tag@0.6.0
├── atom-wx@0.1.1
├── autoclose-html@0.23.0
├── autocomplete-html-entities@0.2.0
├── autocomplete-json@5.5.2
├── autocomplete-modules@2.2.2
├── autocomplete-paths@2.12.2
├── autoprefixer@3.7.1
├── block-comment@0.4.3 (disabled)
├── busy-signal@1.4.3
├── chester-atom-syntax@0.3.2
├── city-lights-ui@1.5.3
├── color-picker@2.3.0
├── comment@0.6.1
├── csslint@1.2.0
├── docblockr@0.13.7
├── docker@0.8.0
├── emmet@2.4.3
├── file-icons@2.1.26
├── git-control@0.9.0
├── git-plus@8.1.0
├── goto-definition@1.3.4 (disabled)
├── highlight-selected@0.14.0
├── hyperclick@0.1.5
├── ide-typescript@0.7.9 (disabled)
├── intellij-idea-keymap@0.2.3
├── intentions@1.1.5
├── javascript-snippets@1.2.1
├── jquery-snippets@11.0.0 (disabled)
├── js-hyperclick@1.13.3
├── language-babel@2.85.0
├── language-docker@1.1.8
├── language-graphql@0.11.0
├── language-haskell@1.17.8
├── language-ini@1.20.0
├── language-javascript-jsx@0.3.7
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-markdown@0.27.0
├── language-mongodb@0.3.1
├── language-ocaml@1.9.5
├── language-pug@0.0.22
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── language-vue@0.23.1
├── linter@2.2.0 (disabled)
├── linter-csslint@2.0.1
├── linter-docker@0.3.2
├── linter-eslint@8.4.1 (disabled)
├── linter-jshint@3.1.9 (disabled)
├── linter-pug@2.0.3
├── linter-ui-default@1.7.1 (disabled)
├── markdown-img-paste@0.3.11
├── markdown-preview-enhanced@0.15.7
├── markdown-preview-plus@3.7.0
├── minimap@4.29.9
├── minimap-quick-highlight@1.0.1
├── monokai@0.24.0
├── nucleus-dark-ui@0.12.3
├── nuclide@0.362.0
├── nuclide-format-js@0.0.47
├── one-dark-vivid-syntax@1.8.1
├── open-in-browser@0.5.2
├── pdf-view@0.71.0
├── pigments@0.40.2
├── platformio-ide-terminal@2.8.4
├── prettier-atom@0.55.2
├── project-manager@3.3.6
├── quick-highlight@0.13.0
├── react-redux-atom-snippets@0.7.2
├── script@3.18.1
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── source-preview-pug@0.2.0
├── sync-settings@0.8.6 (disabled)
├── tool-bar@1.1.10
├── tool-bar-main@0.0.11
├── vue2-autocomplete@0.1.0-alpha.4
├── vuejs2-snippets@1.1.0
└── xml-formatter@0.11.0

**Comment by lee-dohm** [comment]
As @Ben3eeE pointed out in your [last issue](https://github.com/atom/atom/issues/18527), we require the [issue template](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md) to be filled out on all new issues and pull requests.

The first section of the issue template asks you to certify that you've [performed the standard debugging steps](https://flight-manual.atom.io/hacking-atom/sections/debugging/) before filling out an issue to ensure it isn't some common problem, or not a problem with Atom at all.

The second section of the issue template asks for steps to reproduce the problem. I wrote [a blog post on how to write good bug reports](https://www.lee-dohm.com/2015/01/04/writing-good-bug-reports/) if you need help with crafting the steps to reproduce the problem.

Finally, continuing to ignore the issue template and our requests to follow it will be considered harassment under the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md). You may consider this an official warning.
