### ISSUE TITLE
tree view is not displayed

### ISSUE THREAD

**Issue by Lwenli1224** [atom/atom#18527]
Issue and Steps to Reproduce
The tree view is not displayed

Expected Behavior
Tell us what should happen.

Actual Behavior
Tell us what happens instead.

Versions
Atom: 1.33.0
Nuclide: 0.366.0
Client OS: macOS 10.14.1
Server OS (optional):
Additional Details
Installed packages (apm ls --installed):
├── Stylus@3.2.0
├── activate-power-mode@2.7.0 (disabled)
├── atom-beautify@0.33.4
├── atom-ide-ui@0.13.0 (disabled)
├── atom-jade@0.3.0
├── atom-live-server@2.3.0
├── atom-material-ui@2.1.3
├── atom-react-autocomplete@0.1.10
├── atom-ternjs@0.18.3
├── atom-typescript@12.6.3
├── atom-wrap-in-tag@0.6.0
├── atom-wx@0.1.1
├── autoclose-html@0.23.0
├── autocomplete-html-entities@0.2.0
├── autocomplete-json@5.5.2
├── autocomplete-modules@2.2.2
├── autocomplete-paths@2.12.2
├── autoprefixer@3.7.1
├── block-comment@0.4.3 (disabled)
├── busy-signal@1.4.3
├── chester-atom-syntax@0.3.2
├── city-lights-ui@1.5.3
├── color-picker@2.3.0
├── comment@0.6.1
├── csslint@1.2.0
├── docblockr@0.13.7
├── docker@0.8.0
├── emmet@2.4.3
├── file-icons@2.1.26
├── git-control@0.9.0
├── git-plus@8.1.0
├── goto-definition@1.3.4 (disabled)
├── highlight-selected@0.14.0
├── hyperclick@0.1.5
├── ide-typescript@0.7.9 (disabled)
├── intellij-idea-keymap@0.2.3
├── intentions@1.1.5
├── javascript-snippets@1.2.1
├── jquery-snippets@11.0.0 (disabled)
├── js-hyperclick@1.13.3
├── language-babel@2.85.0
├── language-docker@1.1.8
├── language-graphql@0.11.0
├── language-haskell@1.17.8
├── language-ini@1.20.0
├── language-javascript-jsx@0.3.7
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-markdown@0.27.0
├── language-mongodb@0.3.1
├── language-ocaml@1.9.5
├── language-pug@0.0.22
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── language-vue@0.23.1
├── linter@2.2.0 (disabled)
├── linter-csslint@2.0.1
├── linter-docker@0.3.2
├── linter-eslint@8.4.1 (disabled)
├── linter-jshint@3.1.9 (disabled)
├── linter-pug@2.0.3
├── linter-ui-default@1.7.1 (disabled)
├── markdown-img-paste@0.3.11
├── markdown-preview-enhanced@0.15.7
├── markdown-preview-plus@3.7.0
├── minimap@4.29.9
├── minimap-quick-highlight@1.0.1
├── monokai@0.24.0
├── nucleus-dark-ui@0.12.3
├── nuclide@0.362.0
├── nuclide-format-js@0.0.47
├── one-dark-vivid-syntax@1.8.1
├── open-in-browser@0.5.2
├── pdf-view@0.71.0
├── pigments@0.40.2
├── platformio-ide-terminal@2.8.4
├── prettier-atom@0.55.2
├── project-manager@3.3.6
├── quick-highlight@0.13.0
├── react-redux-atom-snippets@0.7.2
├── script@3.18.1
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── source-preview-pug@0.2.0
├── sync-settings@0.8.6 (disabled)
├── tool-bar@1.1.10
├── tool-bar-main@0.0.11
├── vue2-autocomplete@0.1.0-alpha.4
├── vuejs2-snippets@1.1.0
└── xml-formatter@0.11.0

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
