### ISSUE TITLE
Display an animation in Atom written in Octave

### ISSUE THREAD

**Issue by bjce** [atom/atom#18536]
I have the following animation written in `Octave/Matlab`. I can display the animation in `Octave` or `Matlab` without problem when I run the code. As I mainly use `Atom` as text editor, I would like to display the animation from `Atom`. However, as I run the script in `Atom`, it only displays the last image of the animation (after having computed all the previous ones, but without displaying them). 

Here is the code of an animation: 

    for i = 1:0.1:12; plot( sin( [1:0.1:12] + i ) ); drawnow; end;

Specifications: 
Atom : 1.33.0
MacOS 10.14
Octave version: 4.4.1

I originally asked this question in [stackoverflow](https://stackoverflow.com/questions/53579742/display-an-animation-in-atom-written-in-octave)

**Comment by rsese** [comment]
Thanks for reaching out!

> However, as I run the script in Atom

Atom doesn't run code by default so I'm guessing you're having trouble with a community package?   If that's the case, the [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
