### ISSUE TITLE
Menu bar underlines stuck on after ALT+TAB

### ISSUE THREAD

**Issue by BitKing2** [atom/atom#18547]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Menu bar (file, edit, view bar) underlines stay active after alt+tabbing between windows

### Steps to Reproduce

1. Open Atom
2. Make sure the window has focus, then `alt + tab` to another window
3. `alt + tab` back to Atom

**Expected behavior:** Menu Bar underlines not displayed when `alt + tab` is pressed

**Actual behavior:** Menu Bar underlines stay displayed after window has re-gained focus via `alt + tab`

**Reproduces how often:** 100%

### Versions

Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

OS: Microsoft Windows 10 Pro 10.0.17 134 Build 17134

### Additional Information

Menu bar acts as expected after pressing `alt` when window has re-gained focus.

**Comment by BitKing2** [comment]
If someone could point me to where the code is for rendering the menu bar, I would gladly put in pull request to fix it. I just don't have the time to dig though 20 js files right now :)

**Comment by thomasjo** [comment]
Please do not remove mandatory parts from the issue template. We need to know that you've followed all the the required steps, which includes whether your problem is reproducible in safe mode.

Therefore, please edit your issue body or let us know in a follow-up comment whether you've followed all of the prerequisities. Thanks!

``` markdown
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages
```

**Comment by BitKing2** [comment]
I have edited the Issue to reflect you suggestions.  
  
Yes, the issue can be replicated in Safe Mode.

**Comment by BitKing2** [comment]
@rsese Yes I suspect it is probably an issue with Electron implementation. Most likely with how it handles behavior with the `alt` key in general.

**Comment by lee-dohm** [comment]
@BitKing2 would you mind trying to reproduce this on Electron 2.x and Electron 3.x using the [API demos app](https://github.com/electron/electron-api-demos/releases) and let us know what you  find?
