### ISSUE TITLE
Mac: Script/bootstrap fails to install apm

### ISSUE THREAD

**Issue by ryanolsonx** [atom/atom#18540]
[2018-12-04T18_33_48_069Z-debug.log](https://github.com/atom/atom/files/2645586/2018-12-04T18_33_48_069Z-debug.log)
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When attempting to build atom on mac osx, I get the following error when it gets to the install apm step. This is when running `script/bootstrap` for the first time.
```
Error: The module '/Users/ryan/github/atom/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** Things to get bootstrapped

**Actual behavior:** Failed to install deps for apm install

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Node:	v10.10.0
Npm:	v6.4.1

### Additional Information

Latest master

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Does running `script/clean` before building again clear things up for you?

**Comment by ryanolsonx** [comment]
It doesn't. The error comes back the same way after a `script/clean`. Also, if I completely delete the atom repository from my computer and re-clone before running `script/bootstrap`, I get the same issue. I attached a full npm log to the issue above, if that helps out at all.

**Comment by thomasjo** [comment]
@ryanolsonx Thanks for sharing the log file. After looking at the log, it looks like the build fails when trying to use node-gyp to build oniguruma. What's the output of `python -V` on your system?

**Comment by ryanolsonx** [comment]
python -V:
Python 2.7.15

**Comment by parlock** [comment]
In my case I found the "node" executable in the "atom-package-manager/bin" folder is v8.9.3.   I removed  it and copied my node v11.3.0 binary in there.  it then runs apm..  That was able to get me past this error in the bootstrap script..

**Comment by thomasjo** [comment]
I'm unable to reproduce this on macOS 10.14 and Ubuntu 16.04. 
Builds were run on `master` branch (aad7705) using Node.js 11.3.0, npm 6.4.1, and Python 2.7.15.

It looks like the module version mismatch error originally reported might be a red herring caused by running either `npm rebuild` or `npm install`. The original error is not found in the shared log file, but instead reports a problem with building Oniguruma (v6.2.1). At first I had hoped this was caused by building with Python 3, but it seems like that is not the case after all.

@ryanolsonx Are you able to build Oniguruma on your system? Try something like the following

```
$ mkdir /tmp/foo && cd /tmp/foo
$ npm install oniguruma@6.2.1 --no-save
```

**Comment by ryanolsonx** [comment]
@parlock Would that indicate that we should upgrade the node binary in atom-package-manager? I'll give that a try in a bit here.

@thomasjo I was able to build oniguruma on my system with my node version 10.14.1 and npm version 6.4.1.

**Comment by parlock** [comment]
In my case if I do a script/clean it just puts back the old node binary when doing a script/bootstrap again.  So its not fixed, they need to update the bundled node binary to the newer version.

**Comment by parlock** [comment]
Figured it out, once you install the released Atom app, it went away.  So that must install something different that fixes the issue.  Odd, that you can't start clean with the source.

**Comment by rsese** [comment]
> Figured it out, once you install the released Atom app, it went away. So that must install something different that fixes the issue.

Just to clarify @parlock, you need to do more than just a `script/clean` and then run bootstrap to reproduce the problem?

**Comment by parlock** [comment]
To reproduce, you have to not have Atom installed on the machine.  Then grab the source code fresh from GitHub.  Then doing a `script/clean` and `script/bootstrap` will fail.  Installing Atom appears to put in a working copy of `apm` that fixes it.  But `apm `won't build clean from source from a fresh setup..

**Comment by vinkla** [comment]
I can confirm this is still an issue setting up a fresh install. I was able to reproduce with a stable version of Atom installed on my machine.

**macOS:** 10.14.3
**Node:** v11.11.0
**npm:** 6.9.0

**Comment by vinkla** [comment]
With @50Wliu's great pull request removing `node-gyp` dependency in atom/apm#832 and #19189 it seems to fix the issue on my machine.

**Comment by rsese** [comment]
Curious how you reproduced this @vinkla?  I remember running `script/clean` and then removing  the installed Atom app I had from `Applications/`, but I wasn't able to reproduce.

Did you just run a `script/clean` and then `script/bootstrap` would reproduce the error for you?

**Comment by vinkla** [comment]
> Did you just run a script/clean and then script/bootstrap would reproduce the error for you?

Yes, that is correct. Didn't know removing the Atom application from the `Applications` directory was necessary. Is it?

**Comment by rsese** [comment]
> Yes, that is correct. Didn't know removing the Atom application from the `Applications` directory was necessary. Is it? If so, should we add it to the [hacking on Atom core guide](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/)?

Oh sorry, no that's not necessary for building - I was unable to reproduce the error mentioned in this issue by just running clean before bootstrap but I saw this comment [above](https://github.com/atom/atom/issues/18540#issuecomment-446732997):

> To reproduce, you have to not have Atom installed on the machine

I assumed that also meant that you if you installed Atom normally with the .zip, that would affect whether you could reproduce.
