### ISSUE TITLE
Atom stopped open plots in Julia

### ISSUE THREAD

**Issue by MMalakhov** [atom/atom#18541]
Hello!
I’m using Julia and Atom for it, operation system Linux Mint. This morning I pressed “update” button in Atom and typed “] update” in Julia terminal. 

So that is all, program is calculating right numbers, but Atom ignores plotting commands. No warnings, no information. REPL behaves exactly like everything is plotting.
Also plotting in Julia terminal still works. So it should be some problems with Juno and Atom I suppose

This warning emerges only if I try to recompile Julia:
`[ Info: Precompiling Atom [c52e3926-4ff0-5f6e-af25-54175e0327b1]
WARNING: Method definition displayable(Atom.JunoDisplay, Base.MIME{Symbol("application/prs.juno.jlpane")}) in module Atom at /home/mikhail/.julia/packages/Atom/v2iqN/src/display/showdisplay.jl:92 overwritten at /home/mikhail/.julia/packages/Atom/v2iqN/src/display/showdisplay.jl:94.
WARNING: could not import Base.endof into StringDistances`

**Comment by steveward** [comment]
Thanks for contributing @MMalakhov. It looks like this is a specific issue with the Juno package -- I would recommend looking through their [troubleshooting steps](http://docs.junolab.org/latest/man/faq.html#FAQ-1) to try and resolve this issue. If you continue to have problems you can post in the Juno [discussion board](https://discourse.julialang.org/) or [issue tracker](https://github.com/JunoLab/Juno.jl/issues) for further help.
