### ISSUE TITLE
Atom crashes user session under Ubuntu Wayland

### ISSUE THREAD

**Issue by karldw** [atom/atom#18556]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Opening Atom crashes my user session when I use Wayland and don't pass the `--disable-gpu` argument. Using X11 or passing the `--disable-gpu` flag allow things to work as expected.

### Steps to Reproduce

1. Log into Ubuntu 18.10 with Wayland
2. Open Atom

**Expected behavior:** Atom opens

**Actual behavior:** Atom doesn't open and the entire user session crashes

**Reproduces how often:** 100%

### Versions

```
snap info atom
name:      atom
summary:   A hackable text editor for the 21st Century.
publisher: Snapcrafters
contact:   https://github.com/snapcrafters/atom/issues
license:   unset
description: |
  Atom is a free and open source text editor that is modern,
  approachable, and hackable to the core.
  
  This snap is maintained by the Snapcrafters community, and is not
  necessarily endorsed or officially maintained by the upstream developers.
commands:
  - atom.apm
  - atom
snap-id:      Lf1MF6tizzusVuA6l13ETyH5VDXxwA0D
tracking:     stable
refresh-date: 5 days ago, at 07:02 PST
channels:
  stable:    1.33.0 (207) 189MB classic <
  candidate: ↑
  beta:      1.33.0 (207) 189MB classic 
  edge:      1.33.0 (207) 189MB classic 
installed:   1.33.0 (207) 189MB classic 


apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.15+
git 2.19.1
```

(I'm providing the snap version info because `atom --version` has no output.)

### Additional Information

While debugging this, I noticed the following:
- `--safe` doesn't solve things
- `--disable-gpu` works
- `--version` doesn't display the version, but doesn't crash
- `--clear-window-state` still crashes, and also doesn't clear the window state (which I was able to see when I logged in with X11)
- The crash behavior is the same after `--clear-window-state` was run successfully (using X11)
- apm works as expected

**Comment by rsese** [comment]
Thanks for the report -

> (I'm providing the snap version info because `atom --version` has no output.)

The Snap install of Atom is unofficial, can you confirm if you have the same issue using one of the official installation methods?

https://flight-manual.atom.io/getting-started/sections/installing-atom/

**Comment by karldw** [comment]
You're right, this only happens with the Snap install.

**Comment by rsese** [comment]
Thanks for confirming @karldw :+1:, we'll go ahead and close since this doesn't reproduce with one of the supported installation methods.

**Comment by fractalbach** [comment]
Just had this happen to me on Ubuntu 18.04 LTS with Wayland.

I removed my current ATOM, and reinstalled the official way:
https://flight-manual.atom.io/getting-started/sections/installing-atom/
And now it works!

Thanks for this posting this! :smiley:
