### ISSUE TITLE
Atom marker jumping while editing

### ISSUE THREAD

**Issue by sboer** [atom/atom#18551]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

 have an extremely annoying problem, and unfortunately I could not find any previous issues with this problem (possibly due to using the wrong search words). 

But when editing files in atom, the marker is jumping to the last ` of a code block, when pressing space, typing a letter etc. I have no idea when and why it is happening, and it may happen both after and before these code blocks. 

 I have opened atom in safe mode, and the problem persists. 

This is an example. As you can see, the marker in in the line in the middle of the code block. 

![skjermbilde 2018-12-06 17 03 31](https://user-images.githubusercontent.com/35312839/49595724-e8af6280-f978-11e8-95bf-f494d250218e.png)

Then, when I type the letter "l" - this happens:

![skjermbilde 2018-12-06 16 55 26](https://user-images.githubusercontent.com/35312839/49595756-fd8bf600-f978-11e8-8811-e631d3912871.png)

The last ` of the codeblock have been deleted, and the l is placed there instead. 

Why this strange behaviour? Appreciate any help!

(I have been using other markdown editors without this strange issue, so it must be an atom thing which is obviously not possible to turn off)

### Steps to Reproduce

I don´t really know how to reproduce. Copying just the code block into a new document did not reproduce the problem. Deleting some lines and starting over, does not reproduce it. Part of the problem is that I do not understand why and when it occurs, to me it seems random. 

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

I expect to have the letter "l" after the cursor

**Actual behavior:** [What actually happens]

The last ` of the codeblock is deleted, and has been replaced by an "l"

**Reproduces how often:** [What percentage of the time does it reproduce?]

It does not happen with every code block, but after using atom for a week, I have discovered this problem 4-5 times, not being able to solve it (the code block keeps getting deleted, no matter what I do). 

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report!  I don't remember any similar issue off the top of my head, or at least nothing recent.  A few questions:

* If you used Atom previously, did this behavior start with 1.33.0?
* Does [temporarily resetting to factory defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) make any difference?
* It sounds like you see this issue randomly, not just in Markdown code blocks is that right?

**Comment by sboer** [comment]
Thank you so much for your answer!

Strange that you have not heard of the problem before, I was hoping there was something obvious I was doing wrong.. 

I have not used Atom until the last couple of weeks. I have previously used Macdown for my markdown documents, and have not experienced the same problem there. Actually all the documents I have been working with, have been previously written with Macdown, if that could matter..?  I thought since it was just plain it should be safe.. 

The problem occurred before I installed any packages, or changed any settings, but when the problem appears again (I cannot reproduce the problem - it seems to happen completely randomly, but quite often though), I will try to reset to factory defaults. 

I have only seen the issue with the markdown code blocks actually; either editing text above or after, makes the marker jump to the last code block. The first time it happened, I deleted a few words, and then removing a newline. When hitting space after removing the newline, the previously deleted text appeared again, and the last code block was deleted, and no matter how I tried to do it, the same thing happened over and over. 

Is it posssible to somehow turn off everything auto-complete? I have disabled all packages but the problem still remain (guess it will similar to starting up in safe mode)

**Comment by rsese** [comment]
> Actually all the documents I have been working with, have been previously written with Macdown, if that could matter..?

If MacDown just produced Markdown files, I don't think it would matter?  Guessing you can probably reproduce with a new Markdown file you create in Atom?  It is interesting that you've only seen the issue with Markdown blocks though:

> I have only seen the issue with the markdown code blocks actually; either editing text above or after, makes the marker jump to the last code block. The first time it happened, I deleted a few words, and then removing a newline. When hitting space after removing the newline, the previously deleted text appeared again, and the last code block was deleted, and no matter how I tried to do it, the same thing happened over and over.

If you find specific repro steps based on the description above, that would be super helpful :+1:

> Is it posssible to somehow turn off everything auto-complete?

You can disable autocomplete by disabling `autocomplete-plus`.   Or since you're only seeing this issue in Markdown files, you can add `*.md` to `Settings > Packages > autocomplete-plus > File Blacklist`.

**Comment by sboer** [comment]
I still have not been able to reproduce it, but I think there is something about spacing after the code blocks, or some other hidden signs after the code blocks, just not entirely sure what, since I cannot reproduce it. While making new documents, and adding a space after the code blocks, I have not have the issue, actually I have only had the issue while editing "old" MacDown files, never when creating new ones, I guess that is why I cannot reproduce the issue either. (However, adding an extra space after the code blocks makes the syntax highlighting after the code change)

As long as I can handle the problem in my "old" by adding some spaces I am satisfied. 

Thank you so much for helping!

**Comment by rsese** [comment]
Ok sounds good :+1:   We'll go ahead and close for now but if you end up finding specific steps to reproduce, please let us know!
