### ISSUE TITLE
AmbientLightSensor: Could not connect to a sensor

### ISSUE THREAD

**Issue by Exelord** [atom/atom#18569]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Accessing `AmbientLightSensor` API returns `DOMException: Could not connect to a sensor` error while this feature works properly on chromium.

### Steps to Reproduce

In developer console type:
```js
s = new AmbientLightSensor();
s.onchange = event => console.log(event.reading.illuminance);
s.onerror = (e) => console.log(e)
s.start();
```

**Expected behavior:** [What you expect to happen]
Not raise an error and call onchange event with proper sensor readings

**Actual behavior:** [What actually happens]

```
SensorErrorEvent {isTrusted: true, error: DOMException: Could not connect to a sensor, type: "error", target: AmbientLightSensor, currentTarget: AmbientLightSensor, …}
```
**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Versions

```
Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.14
git 2.17.2
```

**Comment by lee-dohm** [comment]
Atom is built on a version of Electron and Chromium that doesn't include the code for this API. You may have to use a Node module for this. Perhaps [ambient-light-sensor](https://www.npmjs.com/package/ambient-light-sensor) would work?
