### ISSUE TITLE
UI & Editor fonts revert to serif on Ubuntu

### ISSUE THREAD

**Issue by alphachai** [atom/atom#18574]
### Description

On a fresh install of Ubuntu with Atom installed via snap, all fonts (editor and UI) are falling back on some serif font. I've tried setting `.atom-workspace` `font-family` to sans-serif, to no avail. I've also tried uninstalling and reinstalling the snap.

![screenshot from 2018-12-12 23-43-24](https://user-images.githubusercontent.com/484580/49918299-28d67f80-fe68-11e8-88a0-20e1e355d3d9.png)

### Versions

Ubuntu 18.10, Gnome 3.30.1
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.0
python 2.7.15+
git 2.19.1

**Comment by rsese** [comment]
Thanks for the report!

> installed via snap

The Snap installation is unofficial and not supported by us - if you can reproduce this issue using an official installation method however, please let us know:

https://flight-manual.atom.io/getting-started/sections/installing-atom/
