### ISSUE TITLE
When rename file to name with capital letter, file is not marked as modified

### ISSUE THREAD

**Issue by danyadev** [atom/atom#18579]
### Description

When you rename a file to name with capital letter, the file is no longer marked as modified and is not added to the list of modified files.

### Steps to Reproduce

1. Edit file
2. Change the first letter of the file name to a larger one
3. Look at the file in the file tree and the list of modified files

**Expected behavior:** The file remains marked as modified or new, and the file with a capital letter is displayed in the list of modified files

**Actual behavior:** The file is not marked as changed and the file with a small letter is in the list of changed files

**Reproduces how often:** always

### Versions

Atom: 1.31.2
Windows: 7 x64 Ultimate

**Comment by lee-dohm** [comment]
This is almost certainly because Windows considers `foobar.txt` and `Foobar.txt` to be the same file. So no change happened on disk with regard to the rename.
