### ISSUE TITLE
Support Atom-Ide

### ISSUE THREAD

**Issue by afridley** [atom/atom#18584]
## Summary

With Facebook dropping Atom-Ide / Nuclide I would like to request that Atoms core team take up support of these packages.

## Motivation

Atom-Ide, and to a further extent, Nuclide adds functionality that allows Atom to compete with VSCode. Since many of the features of Atom-Ide, you can get with VSCode out of the box. I believe these features should be available as a core package As many developers who use Atom rely on them. The package could be disabled by default or just maintained by Atoms core team and still stay a separate package. 

## Describe alternatives you've considered

You may be able to get the same functionality out of user-created packages, but the support and stability of the suite would not be there.

Sadly I feel the only viable alternative would be to move away from Atom. Or for Atom-ide to receive support from another large team.

**Comment by lee-dohm** [comment]
Thanks very much for sharing your thoughts and concerns!

We're constantly evaluating and re-evaluating our priorities and doing research into what will bring the greatest benefit to the Atom community. Right now, we're concentrating more on fixing bugs, implementing smaller features, and doing more rigorous user research. More active maintenance of Atom IDE at some later date isn't off the table but it isn't something that we're going to be doing in the near term.

I disagree, though, that community-maintained packages won't be able to match the stability and support of ones maintained by Atom's core team. Take a look at any of the "trending" packages for great examples of stable and successful packages, many of which have been proudly community-maintained for years. We built Atom as a platform that the community could build upon and always knew that there would be some functionality that the Atom community would have to provide for themselves if they wanted it. That strategy has proven successful so far and we believe that it will continue to do so.

Thanks again for reaching out and your desire to see Atom succeed!
