### ISSUE TITLE
Atom freezing for 10-30s when pasting in JSON text

### ISSUE THREAD

**Issue by Jakemangan** [atom/atom#18595]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom seems to slow down and freeze when pasting in JSON text. I am not sure what is causing this problem as the JSON files I am pasting aren't even big (150~ lines). But when I paste the files into the Atom editor the whole application freezes and prevents any further action for between 10-30s. At one point I thought it might be due to having the Find/Replace bar open, which was causing atom to search for characters automatically when the JSON was pasted, however even after closing Find/Replace this problem still persists.

### Steps to Reproduce

1. Paste JSON into Atom.
2. Select all and paste over existing JSON with new JSON.

**Expected behavior:** [What you expect to happen]

Atom to act responsively and not freeze when pasting small files.

**Actual behavior:** [What actually happens]

Atom freezes for between 10-30s

**Reproduces how often:** [What percentage of the time does it reproduce?]

Almost every time I overwrite JSON in a unsaved file.

### Versions

Atom    : 1.33.0
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3

Windows 10 Version	10.0.16299 Build 16299

### Additional Information

None.

**Comment by rsese** [comment]
Thanks for the report!  Can you share some example JSON content that reproduces this behavior for you that we can use to test?  Also, was there any difference when you ran in safe mode or exact same behavior?
