### ISSUE TITLE
one-dark-syntax background color

### ISSUE THREAD

**Issue by umpirsky** [atom/atom#18594]
Background color is no the same as text background color.

![screenshot from 2018-12-18 12-41-09](https://user-images.githubusercontent.com/208957/50151801-3ce40c00-02c2-11e9-818c-2512d2338694.png)

```
atom --version
Atom    : 1.32.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
```
apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.0
python 2.7.15rc1
git 2.17.1
```
```
cat /etc/issue
Ubuntu 18.04.1 LTS \n \l
```

**Comment by rsese** [comment]
Thanks for the report - not sure when this changed for you but I think this is maybe a duplicate of issues like https://github.com/atom/atom/issues/18401?  If you update `Settings > Color Profile` to `Use sRGB color profile`, does that make any difference?

**Comment by umpirsky** [comment]
That fixed the issue, thanks!
