### ISSUE TITLE
Uncaught TypeError: d.item.getTitle is not a function

### ISSUE THREAD

**Issue by berrylaw** [atom/atom#18613]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: d.item.getTitle is not a function

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

TypeError: d.item.getTitle is not a function
    at TabView.t.exports.TabView.updateTitle (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:871627)
    at TabBarView.t.exports.TabBarView.removeTabForItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1133084)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1130641
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190759)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1192200)
    at Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:459737)
    at Pane.moveItemToPane (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:460247)
    at Object.end (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1124981)
    at HTMLLIElement.TabView.element.ondragend (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:865972)
```

### Commands

```
     -9:59.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated.teletype-Host)
     -9:56.7.0 core:confirm (div.github-FilePatchListView-item.github-FilePatchListView-pathItem)
     -9:51.5.0 github:resolve-file-as-ours (span.github-FilePatchListView-path)
     -9:47.6.0 core:confirm (span.github-FilePatchListView-path)
     -9:32.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated.teletype-Host)
  3x -8:57 core:confirm (span.github-FilePatchListView-path)
  2x -5:52.2.0 github:resolve-file-as-ours (span.github-FilePatchListView-path)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-eclipse-syntax 0.0.6 
autumn-highlighter-syntax 3.0.2 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
hey-pane 1.1.2 
Hydrogen 2.6.0 
jackhammer-syntax 1.1.0 
scroll-through-time 0.3.0 
styri-syntax 1.0.0 
teletype 0.13.3 
zentabs 0.8.9 
```

**Comment by Rabbss** [comment]
-9:59.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated.teletype-Host)
     -9:56.7.0 core:confirm (div.github-FilePatchListView-item.github-FilePatchListView-pathItem)
     -9:51.5.0 github:resolve-file-as-ours (span.github-FilePatchListView-path)
     -9:47.6.0 core:confirm (span.github-FilePatchListView-path)
     -9:32.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.teletype-Authenticated.teletype-Host)
  3x -8:57 core:confirm (span.github-FilePatchListView-path)
  2x -5:52.2.0 github:resolve-file-as-ours (span.github-FilePatchListView-path)

**Comment by Rabbss** [comment]
atom-clock 0.1.16 
atom-eclipse-syntax 0.0.6 
autumn-highlighter-syntax 3.0.2 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
hey-pane 1.1.2 
Hydrogen 2.6.0 
jackhammer-syntax 1.1.0 
scroll-through-time 0.3.0 
styri-syntax 1.0.0 
teletype 0.13.3 
zentabs 0.8.9

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?
