### ISSUE TITLE
"Soft Wrap at preferred line length" is not respected on small window

### ISSUE THREAD

**Issue by 0tho** [atom/atom#18623]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Soft wrap at preferred line length is not respected when window is smaller than line length.

### Steps to Reproduce

1. Turn on Soft Wrap
2. Turn on Soft Wrap at preferred line length
3. Set line length to a number bigger than window width, 200 for example

**Expected behavior:** I expected that the Soft Wrap at preferred line length was respected and that the wrap would occur only at the current Preferred line length.

**Actual behavior:** The lines are wrapped at the minimum of window size and preferred line length, which tends to disrespect the Soft Wrap at preferred line length option

**Reproduces how often:** 100%

### Versions

```
OS: Linux Mint 18.3 Sylvia
Atom    : 1.33.1
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

Related Issue:
1) https://github.com/atom/atom/issues/11303

Related discuss topics:
2) https://discuss.atom.io/t/truly-soft-wrap-at-preferred-line-length/10633/9
3) https://discuss.atom.io/t/soft-wrap-at-preferred-line-length-isnt-honored/61194/4

From what I can see from these related links is that a PR is welcome, and I am willing to work on it. But I am not sure what would be the best way to solve this, as apparently it is considered a feature by some and not a bug.

As far as I can tell this is the line that forces the described behavior: https://github.com/atom/atom/blob/master/src/text-editor.js#L3672

**Comment by rsese** [comment]
Thanks for your interest @0tho!

> Related Issue:
> 
> 1. #11303

Yes this is the best issue for this behavior, it's not necessary to open another issue for it.

> From what I can see from these related links is that a PR is welcome, and I am willing to work on it. But I am not sure what would be the best way to solve this, as apparently it is considered a feature by some and not a bug.

I can try to get some feedback from the team to clarify what behavior or setting we would accept but  feel free to ask in #11303 too.

**Comment by 0tho** [comment]
@rsese Should I mark people on the other thread? I fear that nobody will look at it since its a very old closed issue

**Comment by rsese** [comment]
I don't think so @0tho - I've asked the maintainers for input and I'll share that when I hear more details, and any other folks on that thread that are interested in the issue are probably still subscribed so they'll get a notification of your comment.
