### ISSUE TITLE
Atom project lacks a way to submit positive feedback 😉

### ISSUE THREAD

**Issue by kopischke** [atom/atom#18638]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

There is no obvious way to submit positive feedback to the Atom team. While every nit an deviation from well trodden paths (insert XKCD Workflow joke here) can be considered a regession or defect and thus be rightfully submitted as an issue, this cannot be said of the things done right by the Atom team.

### Steps to Reproduce

1. Identify an aspect of development the Atom team shines in, like its thoroughly friendly professionalism in handling the flood of issue reports in the above mentioned categories, or its ability to steer the course among devs fluttering to the new shiny while actually investing in making code editing better (as exemplified by @maxbrunsfeld patiently and repeatedly educating people in the advantages of semantically consistent syntax highlighting versus the “lovin’ me bright lights” Xmas decoration approach);
2. Decide to formulate positive feedback to counter the issue bias;
3. Seek a less fleeting place to post it than the stream of consciousness discussion board.

**Expected behavior:** Find an obvious place to post your feedback.

**Actual behavior:** There is no such place. Post a silly OT issue instead.

**Reproduces how often:** Every. Single. Time.

### Versions

Version independent.

### Additional Information

This issue is not to be taken entirely seriously; however, the express and implied praise in it very much is. Cheers, and a Happy New Year to all whose calendar advances a year tonight.

**Comment by rsese** [comment]
Thanks @kopischke!  I guess you're right, there's no specific single place where we tell people to go if they have positive feedback to share.  When any of us do see positive feedback (whether it's in a message board post, the Atom Slack, a tweet, an email, etc.), we try to share it with each other so everyone gets to see it :smile:  I'll say that the discussion board and the Atom Slack are probably the best places for now though but I'll mention this to the team in case folks have other ideas.

Thanks again for the kind words and we hope you have a great 2019!
