### ISSUE TITLE
Installation on windows 10 failed

### ISSUE THREAD

**Issue by olekhov** [atom/atom#18642]
I've downloaded AtomSetup-x64.exe current release is 1.33.1
sha1: bba1f5d10b2a5c494b59422cd617b21212bd4d3b
When I run it, it fails with this message:
![image](https://user-images.githubusercontent.com/2698890/50629262-e24ae100-0f4c-11e9-8790-318902afb744.png)

There is no setup log available anywhere.
There is one trace on filesystem: %LocalSettings%\SquirrelTemp with files:
```
atom-1.33.1-full.nupkg
background.gif
RELEASES
Update.exe
```
sha1 sum of .nupkg matches with RELEASES file.
I've tried this solution: https://github.com/atom/atom/issues/5109#issuecomment-153311100
I've extracted files and tried to run Update.exe --install=. from c:\tmp folder within cmd shell with administrative rights - with no effect. Update.exe just exits silently

Probably related to #9515 #5109
My path is (406 bytes):
```
PATH=C:\Program Files\Far Manager\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python37\Scripts\;C:\Python37\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Pandoc\;c:\gow\bin;C:\Users\olekh\AppData\Local\Microsoft\WindowsApps;
```
I have no antivirus installed, Windows defender is disabled.

Are there any means to get more detailed logs from the installer?
I've even checked Windows Events with no success.

Same issue with AtomSetup.exe (for x86), sha1: df4a83b9743071ecb336424b9e081e045e4c7c29

**Comment by rsese** [comment]
Do you have a log file at `%AppData%\local\atom\SquirrelSetup.log`?  Also what version of Windows are you running?

**Comment by olekhov** [comment]
```
Windows 10 Pro N 1803
Microsoft Windows [Version 10.0.17134.472]
```
`%appdata%` is `C:\Users\olekh\AppData\Roaming`, there is no `%appdata%\local` folder

I'm using portable variant of Atom now, probably it messed with folders already.
There is a folder `%appdata%\Atom\logs` which is empty.
`C:\Users\olekh\AppData\Local` does not contain `Atom` folder.

**Comment by olekhov** [comment]
Well, I've run procmon (SysInternals Process Monitor) on Update.exe from x64 installation package. It seems to be a 32-bit executable, huh?
It depends on 32-bit msvcr120_clr0400.dll
I have x64 copy of this dll in system32 folder, but not in SysWOW64.
I have tried to install VS2013 redist both x86 and x64, this file is not from this redist probably.
My .NET framework is 4.7.2 and it says everything is already up to date. 
Same applies to x86 installation package as it has 32-bit Update.exe too

**Comment by olekhov** [comment]
Ok, I've run sfc /scannow and it restored missing dll.
Atom now installs successfully.

The cause of this error was probably that I've recently uninstalled Visual Studio 2017 from this machine.
