### ISSUE TITLE
Split pane down: bottom pane does not maintain scroll position previously shown

### ISSUE THREAD

**Issue by wbt** [atom/atom#18662]
*edit by @rsese to add more specific repro steps and expected behavior*

Using https://github.com/atom/atom/blob/be8097272f40a069c08e8879a49de72223fd03b2/src/pane.js:

1. Open src/pane.js in atom/atom
2. Scroll down so that the last line of the `findOrCreateBottommostSibling()` function is the last visible line, line 1208.
3. Click on line 1185
4. Right-click and `Split Down`

Expected behavior:

> code on the top and bottom halves of the screen are pretty much the same as before choosing Split Panes.

So line 1208 will still be the last visible line of the bottom pane.

But actual behavior is that the top most lines in both panes match (so line 1208 isn't the last visible line in the bottom pane).

[Also](https://github.com/atom/atom/issues/18662#issuecomment-453182668):

> The actual current behavior is slightly worse than described, in that the bottom pane shifts so that the first visible line (1164) doesn't even match what's visible above (1164 is not visible in practice; only a few non-interpretable pixels of it are shown). This makes the split even more disorienting / harder to get reoriented.
Whatever fraction of line 1209 (the last visible line) is visible before the split, I expect to see the same fraction of the same line in the same place after.

---

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When splitting the pane Down, the scroll bar for the new pane is set so that the new top matches the old top of the viewport, instead of the new bottom matching the old bottom.  

### Steps to Reproduce
Open a [reasonably long code file](https://github.com/atom/atom/blob/master/src/pane.js), viewing it in a single pane top to bottom.  The code contains many short, modular functions. 
Recognize you would like to view two on the screen at the same time, that are not next to each other in the file. 
Align the file so the bottom one is correct, planning to split the view and scroll the top to the reference point for reading while developing down below.  
Right-click around the middle and choose Split Down. 
![Screencast demo](https://user-images.githubusercontent.com/563406/50852766-7dc5c280-134e-11e9-83fc-1f49e6fefcfe.gif)

**Expected behavior:** 
There is a new pane division running horizontally across the center of the screen, and possibly obscuring a few lines of code in the middle, but code on the top and bottom halves of the screen are pretty much the same as before choosing Split Panes.

**Actual behavior:** 
The bottom pane is scrolled so that the top is at the top of whatever line the upper pane started in.  Whatever was previously shown on the bottom half of the screen is now scrolled out of view.

**Reproduces how often:**
Very reliably, even in safe mode. 

### Versions
Atom    : 1.23.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
Windows: 10 Pro

**Comment by rsese** [comment]
Thanks for the report - just so we're on the same page, are these steps accurate?  Using https://github.com/atom/atom/blob/be8097272f40a069c08e8879a49de72223fd03b2/src/pane.js:

1. Open src/pane.js in atom/atom
2. Scroll down so that the last line of the `findOrCreateBottommostSibling()` function is the last visible line, line 1208.
3. Click on line 1185
4. Right-click and `Split Down`

Then for your expected behavior:

> code on the top and bottom halves of the screen are pretty much the same as before choosing Split Panes.

So that line 1208 will still be the last visible line of the bottom pane yes?

But actual behavior is that the top most lines in both panes match (so line 1208 isn't the last visible line in the bottom pane)?

**Comment by rsese** [comment]
Thanks for confirming :+1:  I'm not 100% sure what the expected behavior is supposed to be so it could be intentional, but I'll ask the team to take a look (FWIW I noticed that Vim and Emacs seem to behave similarly, though I'm sure there are other editors that behave like you expect).

**Comment by rsese** [comment]
I double checked with the team and this split behavior is intentional and not something the team would change at this point so we're going to close this out.

> If there are other editors that behave as expected, and Atom makes a deliberate choice not to, I'd like to find out what those others are and switch. (Exception: MS Word, which does behave like that, doesn't count as a text editor for code).

Sorry if this is deal breaker for you - I don't know of an editor that behaves the way you expect off the top of my head (I tried VS Code as well just now and it seems to split similarly) so can't offer any suggestions myself.

**Comment by wbt** [comment]
Could you please share any of the logic on *why* this would be an *intentional* design decision?  It seems like a very bad UI choice, and if there's any logic behind it this would be a good place to share it.

**Comment by wbt** [comment]
Some ideas on how this issue might be fixed, if "the team" changes their mind:

The "Split Down" menu item [corresponds](https://github.com/atom/atom/blob/2f827bfc23260eece024b8f179421fa833b1834d/menus/win32.cson#L119) to the command `pane:split-down-and-copy-active-item` which [corresponds](https://github.com/atom/atom/blob/11bd210ee3f2b5a570d27d63435c0024ed1f5e50/src/register-default-commands.coffee#L109) to the function `splitDown(copyActiveItem: true)`.



In [split](https://github.com/atom/atom/blob/0360d26b033797d038cd6c012233762fa2e2c924/src/pane.js#L1096), [line 1099](https://github.com/atom/atom/blob/0360d26b033797d038cd6c012233762fa2e2c924/src/pane.js#L1099) (`params.items.push(this.copyActiveItem())`) could be replaced with something like:
```
var item = this.copyActiveItem()
if(side == 'after') {
  if(orientation == 'vertical') {
    if (item instanceof TextEditor) {
      var bottom = item.getElement().component.getScrollBottom()
      item.getElement().component.setScrollBottom(bottom)
    }
  } else /*if (orientation == 'horizontal')*/  {
    //If desired, similar adjustment for the left/right scroll when splitting right.
  }
}
params.items.push(item)
```
`getElement` is defined [here](https://github.com/atom/atom/blob/be8097272f40a069c08e8879a49de72223fd03b2/src/text-editor.js#L4471).  Its use with `.component` is shown in [`TextEditor::setScrollTopRow`](https://github.com/atom/atom/blob/be8097272f40a069c08e8879a49de72223fd03b2/src/text-editor.js#L4682), but the `.component` piece may be optional thanks to [definition of pass-through functions](https://github.com/atom/atom/blob/2f827bfc23260eece024b8f179421fa833b1834d/src/text-editor-element.js#L178). 

Use of the temporary variable `bottom` is intended purely for code readability.

Another approach might call [`TextEditor::getLastVisibleScreenRow()`](https://github.com/atom/atom/blob/0360d26b033797d038cd6c012233762fa2e2c924/src/text-editor.js#L4606) or [`TextEditorElement::getLastVisibleScreenRow()`](https://github.com/atom/atom/blob/0360d26b033797d038cd6c012233762fa2e2c924/src/text-editor-element.js#L318) on the item being copied and add a corresponding setter to make it the same on the new copy.

The `initialScrollTopRow` [parameter](https://github.com/atom/atom/blob/0360d26b033797d038cd6c012233762fa2e2c924/src/text-editor.js#L135) to the constructor of TextEditor could also be used.  
A utility function for fetching the current editor is defined [here](https://github.com/atom/atom/blob/0360d26b033797d038cd6c012233762fa2e2c924/src/pane.js#L466).

As previously stated, it would be nice to know what if any logic is behind an intentional choice to not change the behavior.
