### ISSUE TITLE
Keymaps ignored for non-English keyboard layouts (atom 1.33.1 on Ubuntu 18.04.1)

### ISSUE THREAD

**Issue by x1o** [atom/atom#18674]
### Description

When the input language is not English (Russian in my case) some keymaps are ignored: for example Ctrl+C or Ctrl+V. Interestingly, some other shortcuts work (like Ctrl-F).

### Versions

* Atom 1.33.1 installed via snap
* Ubuntu 18.04.1

### Additional Information

Saw a couple of very similar issues:
* https://github.com/atom/atom-keymap/issues/203
*  https://github.com/brave/browser-laptop/issues/13559

**Comment by x1o** [comment]
*Temporal* solution:

```
'atom-text-editor':
    'ctrl-с': 'core:copy'
    'ctrl-м': 'core:paste'
    'ctrl-ч': 'core:cut'
    'ctrl-я': 'core:undo'
```

**Comment by rsese** [comment]
Thanks for the report!

> * Atom 1.33.1 installed via snap

The Snap install is unofficial, if you can reproduce with a supported installation method (https://flight-manual.atom.io/getting-started/sections/installing-atom/), please let us know and we can reopen.

**Comment by x1o** [comment]
The problem doesn't persist if atom is installed with `apt`, thank you. Albeit text editing is for some reason slower comparing with the previous installation. 🤔

**Comment by rsese** [comment]
Glad that helped :+1:

> Albeit text editing is for some reason slower comparing with the previous installation. 🤔

If you have a reproducible case (ideally with a minimal test file/project) in safe mode and after having tried some of the other debugging suggestions (https://flight-manual.atom.io/hacking-atom/sections/debugging/), feel free to open a new issue and fill out the issue template with the details.
