### ISSUE TITLE
Snippets aren't detected when the snippets.cson file is created for the first time

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1867]
Halp ticket:
* support/c7984784bffc11e3936c51033c8a3e07

> Snippet system needs to be worked on, when i setup a snippet in the config file, and then i save it and go back to my work, i use the short word and hit tab, and nothing ever expands.

I could reproduce this:

1. quit Atom
2. remove ~/.atom/snippets.cson
3. start Atom
4. go "Atom > Open your snippets", and add a snippet to snippets.cson
5. try triggering the snippet you just added -- it won't work
6. quit and restart Atom
7. try triggering the snippet again -- it will work

**Comment by yihangho** [comment]
I believe this is fixed. @izuzak, can you still reproduce this problem?

**Comment by izuzak** [comment]
@yihangho Yep, seems like it was fixed -- can't reproduce anymore. Thanks for the nudge! :zap:

**Comment by admmasters** [comment]
Snippets seem to be pretty broken for customised .cson files unfortunately.

**Comment by mnquintana** [comment]
@admmasters Can you elaborate? I suspect you're running into duplicate keys in your `snippets.cson` – see https://github.com/atom/atom/issues/7302#issuecomment-112564548:

> Atom's config files (including `snippets.cson`) are a simple key-value format just like JSON (but CSON), which means that keys must always be unique. If you repeat keys, then only one of those values will actually be registered.

**Comment by weboide** [comment]
I believe I just hit this problem with my snippets on version 1.0.11.
I added my first snippet below and it wouldn't list this snippet until I had restarted Atom.

```coffeescript
'.text.html.php':
  'Drupal Render Array Form Element':
    'prefix': 'rafe'
    'body':"""
    $form['${1:fs}'] = array(
      '#type' => '${2:fieldset}',
      '#title' => '$3',
      '#attributes' => array($4),
    );
    """

Fresh (.deb) install on ubuntu 14.10 (64bits)

**Comment by izuzak** [comment]
@weboide Would you mind sharing exact steps to reproduce the problem for you in Atom 1.0.15 in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Here's what I tried:

1. Quit Atom completely
2. Removed my .atom folder to wipe all local settings
3. Started Atom
4. Opened snippets.cson
5. Replaced the content of snippets.cson with this:

  ```
'.source.coffee':
  'Console log':
    'prefix': 'log'
    'body': 'console.log $1'
```

6. Saved snippets.cson
7. Opened new empty file (`cmd-n`)
8. Change the language of the file to CoffeeScript using the Grammar Selector (`ctrl-shift-l`)
9. Typed `log` and pressed `tab`

The snippet was successfully expanded.

If you can still reproduce this an provide detailed steps (like I did above), it would be great if you could share a GIF of that happening as well. Thanks!

**Comment by weboide** [comment]
Your steps worked. I'm wondering if my issue came from another module or the snippets stopped working after installing/uninstalling so many modules (with some that failed).

**Comment by izuzak** [comment]
> I'm wondering if my issue came from another module or the snippets stopped working after installing/uninstalling so many modules (with some that failed).

Possibly, but it would be great to have reproduction steps for this. Happy to reopen if we can get reliable steps to trigger this problem. Thanks for helping investigate this :zap:

**Comment by xixixao** [comment]
Same happened to me with 1.1.0. Nothing more to reproduce than that changing snippets for the first time didn't work for me, had to restart (same as your original report).

**Comment by mnquintana** [comment]
@xixixao You're running an old version of Atom – can you upgrade to the latest version of Atom (1.3.2) and see if you can still reproduce this in safe mode? (`atom --safe`)

**Comment by MartinMuzatko** [comment]
I'm on 1.5.3 this still happens to me

**Comment by garralab** [comment]
I'm on 1.12.9, Windows 7, this still appens to me. I'm sure it worked before, not sure when it started not working since it's been a while since I did add my previous snippet. Lot's of modules to, obviously.

**Comment by cgarnier** [comment]
It s appened to me too on 1.13.0.
You should reopen

**Comment by jlafica** [comment]
I see that this issue is closed, and perhaps it should be. But just in case anyone didn't catch what @mnquintana said, I just wanted to highlight it again...

>I suspect you're running into duplicate keys in your snippets.cson – see #7302 (comment):

> Atom's config files (including snippets.cson) are a simple key-value format just like JSON (but CSON), which means that keys must always be unique. If you repeat keys, then only one of those values will actually be registered.

It's easy to overlook, but duplicate 'source' keys are probably the _source_ of the problem in many cases. This won't work, because '.source.js' is duplicated:

```coffeescript
'.source.js': // 1
  'React Component Class':
    'prefix': 'recomp'
    'body': 'export default class $1 extends Component {\n\trender() {\n\t\treturn (\n\t\t\t$2\n\t\t);\n\t}\n}'
'.source.js': // 2
  'Import React Component':
    'prefix': 'reimp'
    'body': 'import React, { Component } from \'react\';'
```

This _will_ work, because both snippets are nested under a single key for the source:
```coffeescript
'.source.js': // 1
  'React Component Class':
    'prefix': 'recomp'
    'body': 'export default class $1 extends Component {\n\trender() {\n\t\treturn (\n\t\t\t$2\n\t\t);\n\t}\n}'
  'Import React Component':
    'prefix': 'reimp'
    'body': 'import React, { Component } from \'react\';'
```

**Comment by cgarnier** [comment]
No, the issue appears when you are running a fresh install of atom with no snippets.cson file.
The first time you edit this file, atom doesnt take care of the change. You have to restart atom. 
After the restart, it works like expected.

It s wrote nowhere you have to restart atom so you can waspe a lot of time trying to understand what you have done wrong.

**Comment by jlafica** [comment]
@cgarnier Certainly, I hear you. The google search that landed me on this thread was "atom snippets.cson not picking up changes". I'm just making the safe assumption that many others have done the same.
