### ISSUE TITLE
Background Mismatch

### ISSUE THREAD

**Issue by movabo** [atom/atom#18676]
### Prerequisites

 * [x] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
 * [x] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
 * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
 * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
 * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The background of the editor changes with the cursor position and text length. It is not the same across the full width.
This might be related to #12634, #15083.

The difference is, that in the related issue atom seems to be running on Mac OS. Here atom is running on Ubuntu `Ubuntu 18.04.1 LTS`.

![atom-bug](https://user-images.githubusercontent.com/4041740/50984689-bc03e300-1502-11e9-985d-b83a91fd9601.gif)

This bug (like in the other issues) to disappear on light themes.
In other issues `atom --disable-gpu` and `atom --enable-gpu-rasterization --force-gpu-rasterization` are suggested, which did solve the issue.

The issue also remains when starting via `atom --safe` or `atom --clear-window-state`.

I hope i did not create a duplicate. If i did I am very sorry.

### Steps to Reproduce

1. Open default atom with the default theme.
2. Open any text file.
3. Edit some text.

**Expected behavior:** A smooth, nice background without changes. :)

**Actual behavior:** The background changes depending on 

**Reproduces how often:** 100%

### Versions

```sh
$ atom --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.15rc1
git 2.17.1
$ uname -a
Linux jupiter 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 18.04.1 LTS
```

### Additional Information

The bug seems to disappear when removing `background-color: inherit;` from `atom-text-editor > div`:

![atom-bugfix](https://user-images.githubusercontent.com/4041740/50986359-f0799e00-1506-11e9-8133-70a6b4b2a686.gif)

or as little script (executed in the developer console):

```js
let flatten = arr => [].concat.apply([], arr)
let parent_elements = Object.values(document.getElementsByTagName('atom-text-editor'))
let children_elements = flatten(flatten(parent_elements.map(x => Array.from(x.children))))
children_elements.forEach((el) => { el.style.backgroundColor = null; })
```

**Comment by movabo** [comment]
Yes it does! Now it works as expected.
I hope I did not skip any comment mentioning that in the other issues.

**Comment by rsese** [comment]
Great glad that helped :+1:  

And you didn't miss any comments in those issues you referenced, see more recent ones like https://github.com/atom/atom/issues/17900 :smile:
