### ISSUE TITLE
[git-diff] place icons in a gutter

### ISSUE THREAD

**Issue by trusktr** [atom/atom#18684]
## Summary

place git-diff icons in a gutter

## Motivation

At the moment the icons are styled as `::before` content with CSS, which makes them hard to align, and when we do they can conflict with other gutters.

For example, currently we have this (notice the mis-alignment):

<img width="202" alt="screen shot 2019-01-11 at 1 57 16 pm" src="https://user-images.githubusercontent.com/297678/51061647-d5f80100-15a8-11e9-981d-6f06c08b5ff2.png">

and we'd want to put them in a gutter so we get alignment, like:

<img width="194" alt="screen shot 2019-01-11 at 1 56 49 pm" src="https://user-images.githubusercontent.com/297678/51061639-d1cbe380-15a8-11e9-89cd-cdd4369548e1.png">

CSS alone may not be good enough, because the way I did it, it can conflict with other gutters. For example, with the CSS

```css
atom-text-editor .gutter.git-diff-icon .line-number:before {
 position: absolute;
 right: -5px;
}
```

we achieve the alignment, but they overlap with content from another gutter:

<img width="184" alt="screen shot 2019-01-11 at 1 59 09 pm" src="https://user-images.githubusercontent.com/297678/51061909-b31a1c80-15a9-11e9-9fb1-594b3c196216.png">

**Comment by trusktr** [comment]
If we move the icons over more, it is not easy to make things `overflow: visible` in order to show the icons:

<img width="176" alt="screen shot 2019-01-11 at 2 15 57 pm" src="https://user-images.githubusercontent.com/297678/51062332-6d5e5380-15ab-11e9-8ae9-e56385e719ed.png">

**Comment by simurai** [comment]
In PR #18844 the icons aren't in their own gutter and still left of the line number, but the alignment should be fixed.
