### ISSUE TITLE
`atom -a <path>` opens in new window if run from different terminal

### ISSUE THREAD

**Issue by ssfrr** [atom/atom#18698]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When opening a path using `atom -a <path>`, 

### Steps to Reproduce

1. Open a terminal
2. run `atom <path>` to open a directory as a project in atom
3. open a 2nd terminal
4. in the new terminal, run `atom -a <newpath>` on a different path

**Expected behavior:**

`<newpath>` would open in the same window as `<path>`

**Actual behavior:**

`<newpath>` is opened in a new window

**Reproduces how often:**

100%

### Versions

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

`uname -a`: Linux eye 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

I confirmed that if I ran `atom -a <newpath>` from the same terminal as `<path>`, then it opens in the same Atom session as expected.

**Comment by rsese** [comment]
Thanks for the report!

I'm unable to reproduce with 1.34.0 on Ubuntu 18.04.  You installed Atom using one of the [supported installation methods yes](https://flight-manual.atom.io/getting-started/sections/installing-atom/)?

**Comment by rsese** [comment]
> Which I believe matches what I should have from those instructions.

Yep that looks right thanks for checking :+1:

> I'm using the XFCE window manager - perhaps that's contributing to the issue?

Hmm, not sure but I'm using whatever the default is for Ubuntu 18.04 (that's gdm3/Gnome these days yes?) - are you able to easily switch to see if that makes a difference?

Also do you happen to be working in separate workspaces?
