### ISSUE TITLE
getTextInBufferRange not works

### ISSUE THREAD

**Issue by yuis-ice** [atom/atom#18708]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

getTextInBufferRange(range) not works.

### Steps to Reproduce

The following script in init.coffee outputs nothing.

*Edit by @rsese to flesh out repro steps*

1. Create and save a file with some content e.g. 

```text
hello world
hello world
hello world
hello world
```
2. Add this to your init script:

```
atom.workspace.observeTextEditors (editor) ->
  editor.onDidSave ->
    console.log editor.getTextInBufferRange(new Range([0, 0], [3, 3]))
```
3. Make some edit to the file in (1) and save the file

**Expected behavior:** [What you expect to happen]

outputs enclosed text in range. I expect that some text is outputted.

**Actual behavior:** [What actually happens]

Nothing outputs.

even though the following script works well. (outputs the cursol position by ctrl+S)
```
atom.workspace.observeTextEditors (editor) ->
  editor.onDidSave ->
    console.log "info: getCursorScreenPosition() is #{editor.getCursorScreenPosition()}"
```

We did notice that using a Range compatible array seemed to work?  /cc https://github.com/atom/atom/issues/18708#issuecomment-454976927

### Versions

atom --version

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce on macOS 10.12.6 with 1.34.0 though I'm not sure if I'm just misunderstanding how to use that function.

I did note that using a Range compatible array seems to work though, do you see the same?

```coffee
atom.workspace.observeTextEditors (editor) ->
  editor.onDidSave ->
  console.log "hi: " + editor.getTextInBufferRange([[0, 0], [3, 3]])
```

**Comment by maxbrunsfeld** [comment]
Where is `Range` coming from? Do you have this code somewhere in your init script?

```coffee
{Range} = require('atom')
```

If not, then you're using the DOM's built-in [Range](https://developer.mozilla.org/en-US/docs/Web/API/Range) class, which is unrelated, and *not* meant to be passed to `getTextInBufferRange`.

**Comment by rsese** [comment]
Ohhh, that's definitely the issue I ran into reproducing since I just copy/pasted that snippet without adding that require.  Things worked with the addition above, thanks Max :bow:

I'm going to assume that this will fix things for you too @yuis-ice but if it doesn't, please share your entire init script and we can reopen and take a look.

**Comment by yuis-ice** [comment]
> {Range} = require('atom')

I've solved this issue by that. thanks @maxbrunsfeld
