### ISSUE TITLE
Running "atom ." in bash on Ubuntu WSL fails on Windows 10 1809

### ISSUE THREAD

**Issue by Jinivus** [atom/atom#18702]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Something changed between windows builds 1803 and 1809 that caused the atom.sh script to fail to launch atom.exe on the windows side FROM Ubuntu bash correctly.

### Steps to Reproduce

1. Open WSL Bash
2. Move to windows accessible directory ie `cd /c/dev/`
3. Run `atom .`

**Expected behavior:** Atom should launch opening the current directory (/c/dev/)

**Actual behavior:** Prints "The system cannot find the path specified." and does not launch

**Reproduces how often:** 100%

### Versions

Windows 1809 + Ubuntu 18.04 + Atom 1.35.0-beta0 x64

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report - I'm unable to reproduce the error that you see with 1.34.0 on Windows 10.  If I try to run `atom` in WSL Ubuntu 18.04 I get the error reported in https://github.com/atom/atom/issues/18126.  

Do you think your PR will fix https://github.com/atom/atom/issues/18126?

**Comment by mslinn** [comment]
When I type `atom .` on WSL I get this error message:

        shared memfd open() failed: Function not implemented
