### ISSUE TITLE
Tree view not refreshed after commit

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [atom/atom#18723]
Hi, I use Atom git package installed by default, But when add a new commit files color in tree view does not refresh until i close and reopen/preview the file.

**Comment by rsese** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/tree-view repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Also, please fill out the issue template when opening an issue, the issue template details are super helpful for us when triaging issues.

Thanks for meeting us half way 👍
