### ISSUE TITLE
Atom won't release git pack files

### ISSUE THREAD

**Issue by NetherGranite** [atom/atom#18728]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom will keep pack files located in a local git repository at `.git\objects\pack` in use even after a project has been removed from Atom, preventing you from deleting the project on Windows. This will also cause git garbage collection to fail because it cannot modify the pack files while Atom keeps them in permanent use. The only way to delete a project or successfully execute a git garbage collection is to close Atom, regardless of if the project has been removed from Atom or not.

### Steps to Reproduce

1. Clone a git repository.
2. Add that repository as a project to Atom.
3. Attempt to call `git gc`. It will fail because git cannot modify the pack files (which can be revealed to be in use by Atom through Resource Manager).
3. Remove the project from Atom.
4. Attempt to call `git gc`. It will still fail.
5. Attempt to delete the repository. You can successfully delete everything except the pack files located at `.git\objects\pack` (which can be revealed to be in use by Atom through Resource Manager).

*edit by @rsese - the errors I see from steps (3) and (5) after cloning https://github.com/atom/github*

```
git gc
Enumerating objects: 54899, done.
Counting objects: 100% (54899/54899), done.
Delta compression using up to 2 threads
Compressing objects: 100% (11978/11978), done.
Writing objects: 100% (54899/54899), done.
Total 54899 (delta 42387), reused 54899 (delta 42387)
Unlink of file '.git/objects/pack/pack-b9e8d15fd53c5a512360450f65ef42d5e36c152a.pack' failed. Should I try again? (y/n) n
Unlink of file '.git/objects/pack/pack-b9e8d15fd53c5a512360450f65ef42d5e36c152a.idx' failed. Should I try again? (y/n) n
```

**Expected behavior:** [What you expect to happen]

I should be able to delete the project from my computer once I remove the project from Atom, and `git gc` shouldn't fail even when a project is still in Atom.

**Actual behavior:** [What actually happens]

I could not delete the project from my computer even after removing the project from Atom, and `git gc` fails once a project has been added to Atom (and will continue to fail even after a project has been removed from Atom), both of which are due to git's pack files being in use by Atom. Atom must be closed for either operation to succeed, even after a project has been removed from Atom.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of the time for me.

### Versions

**Windows Version (`winver`)**

Windows Update 1803 Build 17134.556

**Atom Version (`atom --version`)**

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

**APM Version (`apm --version`)**

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python
git 2.20.1.windows.1
visual studio

**Comment by rsese** [comment]
Just to followup, we took another look and feel like this is close enough to (if not the same issue as) https://github.com/atom/atom/issues/3365, that we're going to close in favor of that issue if you want to subscribe.  If https://github.com/atom/atom/issues/3365 is resolved and this is still a problem we can always reopen.

Thanks again for reporting!
