### ISSUE TITLE
Incorrectly Saving a file in a FUSE folder (cryptomator vault)

### ISSUE THREAD

**Issue by nikolayhg** [atom/atom#18730]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I want to save a new file to a [cryptomator](https://cryptomator.org/) vault folder. But often the file content is changed automatically after saving it. I found one example that I can reproduce every time, shared below.

### Steps to Reproduce

1. Create and unlock a [cryptomator](https://cryptomator.org/) FUSE vault folder.
2. Open Atom editor and create test.txt inside the cryptomator FUSE vault folder.
3. Enter the following contents in the file:
```
1
2
3
4
```
4. Save the file.
5. Delete the line 2 and 3 so that you see the following content:
```
1
4
```
6. Save the file.
7. The content has automatically changed to and saved into the file:
```
1
4
3
4
```

**Expected behavior:** [What you expect to happen]
After the second save (step 6), the file content should have remained as described in step 5.

**Actual behavior:** [What actually happens]
The content changed as described in step 7.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%. Tested it 5 times. On two different machines.

### Versions

atom 1.34.0
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.15rc1
git 2.17.1

OS: Ubuntu 18.04
Cryptomator 1.4.1

### Additional Information
Cannot reproduce the issue with other editors like gedit and sublimetext.

Screenshot:
![atom-cryptomator-vault-save](https://user-images.githubusercontent.com/14300004/51538172-83d89a80-1e48-11e9-8d1e-4dc6fc33c860.gif)

**Comment by rsese** [comment]
It sounds like this is specific to using cryptomator with Atom yes @nikolayhg?  You otherwise have no problem saving files on your local filesystem?

A few questions:

* Did you install Atom using a [supported installation method](https://flight-manual.atom.io/getting-started/sections/installing-atom/)?
* Does adjusting `Settings > Core > File System Watcher` make any difference?
* Are there any errors in [devtools console](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools) when saving a file?

**Comment by nikolayhg** [comment]
@rsese, 2x yes. Answers on the few questions:
* yes
* no. I tried the different options for File System Watcher.
* no errors in the devtools console.
