### ISSUE TITLE
Indenting a large number of lines is slow

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1873]
Halp ticket
- support/2bbd81a4c57811e393fadd0c383f63a6

> Atom is slow to process commands on large selections:
> Steps to reproduce:
> 1. Using the markup in this gist https://gist.github.com/mcanas/10888195, paste the code into Atom
> 2. Select All
> 3. Click the Tab button
> 
> I'm noticing 10 seconds or more to complete the operation, and sometimes pop-up warnings about the operation taking too long.

I'm not noticing a 10s delay, but more around 0.5s for 1000 lines. However, if I try to indent 2000 lines -- the delay get's worse and is about 1s.

**Comment by alexandernst** [comment]
Still an issue

**Comment by yanzhang0219** [comment]
The issue is still there.
