### ISSUE TITLE
Unable to edit text in search field

### ISSUE THREAD

**Issue by john-cj** [atom/atom#18746]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Sometimes you will not be able to edit text in search field.

### Steps to Reproduce

1. Create new tab with 2 lines: `foo` and `bar`.
2. Press Ctrl-F. Type "foo" in search field in bottom pane. Then press Escape to close the pane.
3. Press Ctrl-F again. Press End or Right-Arrow keys on the keyboard - it will not do anything. The cursor will be just blinking in the very start of search field.

### Versions

Atom 1.34.0 ia32. Windows 7.

**Comment by rsese** [comment]
Should be in https://github.com/atom/find-and-replace, thanks for opening https://github.com/atom/find-and-replace/issues/1067 :+1:
