### ISSUE TITLE
Bitmap fonts break GTK menus

### ISSUE THREAD

**Issue by f0x52** [atom/atom#18741]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When the global gtk font is set to a bitmap font (with `lxappearance`), GTK dialogs render all characters as squares. This only happens in Atom (even chromium works fine). If I set the font to something like Roboto, start Atom, then change it back, the Atom dialogs will display fine.

### Steps to Reproduce

1. Use a bitmap font for gtk applications ([zevv-peep](http://zevv.nl/play/code/zevv-peep/) in my case)
2. Start Atom, open the "Open File" dialog
3. all text is rendered as squares

**Expected behavior:** 
All text gets displayed in the bitmap font

**Actual behavior:**
it's just squares
![image](https://user-images.githubusercontent.com/23422690/51682447-bec50480-1fe7-11e9-917e-cf0b0dd99447.png)

**Reproduces how often:**
always

### Versions
```
atom --version

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm --version

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.15+
git 2.20.1
```
Running on Debian Sid

### Additional Information

Font used is http://zevv.nl/play/code/zevv-peep/

**Comment by rsese** [comment]
Thanks for the report!  Just to clarify, you installed Atom using one of the [official installation methods](https://flight-manual.atom.io/getting-started/sections/installing-atom/)?

Also:

> Use a bitmap font for gtk applications (zevv-peep in my case)

Can you share step-by-step instructions for this?  I test things on Ubuntu but don't use it as my everyday OS so I don't really spend much time tweaking settings.

**Comment by f0x52** [comment]
Yes I installed it from the packagecloud repo.

Not 100% how it'd work on Ubuntu, but:
download the [pcf version of peep I converted](https://f.0x52.eu/media/_e317a4e46cb197986e2f8ccbfda4ad84peep.pcf), put that in `~/.fonts/`, follow https://askubuntu.com/questions/90001/how-can-i-activate-bitmap-fonts
and then you'd probably want to use dconf to change it globally https://askubuntu.com/questions/918909/change-desktops-font-family

**Comment by Synaxis** [comment]
in ubuntu 19.04 the menu fonts disappeared completely 
( i know this might be an issue with Ubuntu 19.04 beta)
but other apps seems to work normally 
(discord/ vlc/ vscode)

**Comment by Phaenyxx** [comment]
I'm also experiencing this issue on fedora 29, with ohsnap and undefined font.

**Comment by mrchristian** [comment]
Hmmm, I have exactly the same problem too
