### ISSUE TITLE
Atom Integration with KDE QT kwallet password manager

### ISSUE THREAD

**Issue by thommierother** [atom/atom#18778]
(re-opened/copied issue from https://github.com/atom/atom/issues/17575 for 1.28)

Current Atom releases do not use the kwallet password manager when operated in a QT/kde environment (eg. OpenSUSE or Kubuntu). Instead atom calls gcr-prompter from Gnome and then starts gnome-keyring-daemon. But on a KDE system (plasma 5) normally there is no Gnome keyring, all passwords are stored through kwalletd instead. There should be a connector to kwallet and also a possibility to select the password manager through config.

**Comment by rsese** [comment]
Ahh sorry for losing track of that one @thommierother - going to close this in favor of #17575 since it has more details and then move that issue to https://github.com/atom/node-keytar and we can go from there
