### ISSUE TITLE
[RFI] language mapping locally configurable

### ISSUE THREAD

**Issue by TriMoon** [atom/atom#18786]
## Summary
Allow path and globing with this setting.
This is an "Request For Improvement" aka RFI for the 2 years ago closed issue #1718

## Motivation
Sometimes it's just not possible or wanted to **only** use file extensions to override the scope used for certain files.
As an example lets take `.conf` files:
  - Are these **Apache** config files ?
  - Are these **Bind9** config files ?
  - Are these ??? config files ?

The above applications both allow to include other files with or without extension with a path.
Now if one creates those files without extensions, because they are included and known to the author of the config file, how is atom to know which scope to use so it can properly highlight etc?

### Conclusion
We need a way to extend the functionality of [customFileTypes](https://github.com/atom/atom/blob/master/src/config-schema.js#L47) in such a way that it also accepts paths and globs.
In particular globs **together** with paths like `somepath/*.ext`, `somepath/*` and `somepath/foo*` to properly override in a selective manner.
Where `somepath` can be absolute starting with a slash or relative to a root dir in the listing (project).

## Describe alternatives you've considered
Maybe it needs a similar function with a different config key, if that is easier to code, but i would prefer to extend the current one :wink: 

## Additional context
None at moment

**Comment by lee-dohm** [comment]
Thanks for the suggestion!

This sounds like a great idea for a community package. We reviewed this with the team and we feel that this behavior is a bit too niche to take on the added complexity.

Thanks again for reaching out.
