### ISSUE TITLE
[Debian] Not working when configured in alternatives for editor

### ISSUE THREAD

**Issue by TriMoon** [atom/atom#18792]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When atom (beta) is configured using the alternatives system for the default editor, it is not working.

### Steps to Reproduce

1. Check the current setup for `editor` to be able to undo in case of errors.
   Keep the info of `update-alternatives --display editor` in a separate terminal output or note it down.
2. In a separate terminal execute:
   `sudo update-alternatives --install /usr/bin/editor editor /usr/bin/atom-beta 200`
   - I used `200` as priority as it was higher as anything listed in step 1, so it would be automatically choosen as current alternatve.
3. In a separate terminal execute `update-alternatives --display editor`, to check it is now listed as default for `editor`.
   1. If step 3 is positive we can continue to step 4, **otherwise** you made a mistake and might want to undo your error and start over.
   1. To undo step 2 execute `sudo update-alternatives --remove editor /usr/bin/atom-beta`.
5. We can continue in the same terminal as step 3.
   1. Execute `select-editor` to change the preferred editor for the current user.
   2. Select the option in which `/usr/bin/atom-beta` is listed.
   3. Execute `sensible-editor -h` to display the help of the preferred editor, which is by now the atom editor. **This should work.**
   4. Execute `editor -h` to display the help of the default editor, which is by now the atom editor. **This will NOT work.**

**Expected behavior:** [What you expect to happen]
That you would see the same output in step `4.iv` as you see in step `4.iii`

**Actual behavior:** [What actually happens]
Step `4.iii` gives proper help output of the atom editor, which indicates it is working.
Step `4.iv` gives **no output at all**, which indicates it is **not working**.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%, eg. every time.

### Versions
```console
~/ atom-beta --version 
Atom    : 1.35.0-beta0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
~/ apm-beta --version 
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.0-beta0
python 2.7.15+
git 2.20.1
~/ neofetch --stdout
OS: Debian GNU/Linux buster/sid x86_64 
Model: Manual build Rev:xxx 
Mainboard: X99-PRO/USB 3.1 Rev 1.xx (ASUSTeK COMPUTER INC.) 
Bios: 2017-08-10 AMI Ver:3801 
Kernel: 4.19.0-1-amd64 
Uptime: 1 day, 2 hours, 6 mins 
Packages: 2278 (dpkg) 
Shell: zsh 5.7 
Resolution: 1680x1050 @ 59.88Hz 
DE: Cinnamon 3.8.8 
WM: Mutter (Muffin) 
WM Theme: Adapta-Nokto (Adapta-Nokto) 
Theme: Adapta-Nokto [GTK2/3] 
Icons: Papirus [GTK2/3] 
Terminal: xterm 
Font: DejaVu Serif Semi-Condensed 10 [GTK2/3] 
Locale: en_US.UTF-8 
Memory: 17301MiB / 32143MiB [--------=======] 
CPU: i7-5820K (12) @ 3.6GHz [43.0°C] 
GPU: GeForce GTX 1080 Ti 
GPU: GeForce 210 
GPU Driver: NVIDIA 390.87 
CPU Usage: 7% 
```
### Additional Information
It is vital to be able to set atom as the default editor using the alternatives system(ref) in debian related distributions (or any other that uses the alternatives system) if atom wants to become the defacto editor on linux :flags: :1st_place_medal: 
You might try to do the same steps with every occurrence of `atom-beta` replaced by `atom` or any other version...
Nothing more i can think of at moment :wink: 

ref:
  - https://debian-administration.org/article/91/Using_the_Debian_alternatives_system
  - https://wiki.debian.org/DebianAlternatives
  - https://unix.stackexchange.com/questions/229373/debian-alternatives-system-programs-with-the-same-name-and-priorities

**Comment by rsese** [comment]
Finally had a chance to try this out (I was running Atom 1.34.0 on Ubuntu 18.04) but couldn't reproduce.  After following your repro steps, the behavior was your described actual behavior (the help output from Atom).

**Comment by SpaceCow404** [comment]
I was able to replicate the issue and narrow down what's causing it but not sure how to fix it.

In the atom-beta bash script, $CHANNEL is being set to **stable** and not **beta** which then causes ATOM_PATH later in the script to go $USR_DIRECTORY/share/atom/atom which is incorrect. This is due to basename returning an unexpected result(see below). Then since it can't get there it instead tries to open atom in the tmp folder which also fails and causes no output as a result.

**basename $0 is returning the following:**
sensible-editor -h: atom-beta
editor -h: editor
