### ISSUE TITLE
Unable to compile atom from source. Fails when creating mksnaphost 

### ISSUE THREAD

**Issue by alexqbo** [atom/atom#18803]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Unable to compile atom from source. Fails creating mksnaphost

Generating startup blob with mksnapshot
Moving generated startup blob into "/home/alex/atom/out/atom-dev-1.36.0-dev-c79716659-amd64/v8_context_snapshot.bin"
Error: ENOENT: no such file or directory, rename '/home/alex/atom/out/v8_context_snapshot.bin' -> '/home/alex/atom/out/atom-dev-1.36.0-dev-c79716659-amd64/v8_context_snapshot.bin'

### Steps to Reproduce
script/clean 
script/build --create-rpm-package

**Expected behavior:** [What you expect to happen]
Complete the build

**Actual behavior:** [What actually happens]
Unable to build
**Reproduces how often:** [What percentage of the time does it reproduce?]
all the time

### Versions

cat /etc/redhat-release 
Fedora release 26 (Twenty Six)

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.15
git 2.13.6

### Additional Information

Downloading electron-v3.0.14-linux-x64.zip
[============================================>] 100.0% of 51.5 MB (4.04 MB/s)
Packaging app for platform linux x64 using electron v3.0.14
Changing permissions for node files in /home/alex/atom/out/atom-dev-1.36.0-dev-c79716659-amd64
Copying non-ASAR resources to /home/alex/atom/out/atom-dev-1.36.0-dev-c79716659-amd64/resources
Writing LICENSE.md to /home/alex/atom/out/atom-dev-1.36.0-dev-c79716659-amd64/resources
Application bundle created at /home/alex/atom/out/atom-dev-1.36.0-dev-c79716659-amd64
Generating snapshot script at "/home/alex/atom/out/startup.js" (3986)
Minifying startup script
Verifying if snapshot can be executed via `mksnapshot`
Generating startup blob with mksnapshot
Moving generated startup blob into "/home/alex/atom/out/atom-dev-1.36.0-dev-c79716659-amd64/v8_context_snapshot.bin"
Error: ENOENT: no such file or directory, rename '/home/alex/atom/out/v8_context_snapshot.bin' -> '/home/alex/atom/out/atom-dev-1.36.0-dev-c79716659-amd64/v8_context_snapshot.bin'
  at Error (native)
  at Object.fs.renameSync (fs.js:819:18)
  at electronLink.then.err (/home/alex/atom/script/lib/generate-startup-snapshot.js:128:10)

**Comment by daviwil** [comment]
A couple questions to help diagnose the issue:

1. In your Atom repo's `script/` folder, what does `npm ls electron-mksnapshot` return?
2. What are the top-level contents of the `out/` folder after building Atom?

**Comment by alexqbo** [comment]
@daviwil  thank you!

electron-mksnapshot@3.0.10 
└── UNMET PEER DEPENDENCY graphql@0.12.3

npm ERR! peer dep missing: graphql@^0.13.0, required by relay-compiler@1.7.0
[alex@dell atom]$ np
npm    nproc  
[alex@dell atom]$ ls out/
app  atom-dev-1.36.0-dev-c79716659-amd64  startup.js  symbols

Thanks for the `ls` cmd. That gave it away. There was a pb with the fc26 npm installation. I was unable to upgrade to the latest version. 

This was my solution. After this compilation and rpm installation was successful .

git clone git://github.com/creationix/nvm.git ~/nvm
echo "source ~/nvm/nvm.sh" >> ~/.bashrc
source ~/.bashrc
nmv
nvm_install_latest_npm

**Comment by daviwil** [comment]
Awesome, glad that helped you uncover the issue!  I'll go ahead and close this out, let us know if you run into any other issues.
