### ISSUE TITLE
cursor disappears on macos if I switch to atom after sleep.

### ISSUE THREAD

**Issue by Pionell** [atom/atom#18836]
### Description
I manage to consistently loose my cursor on macos after opening the lid and atom being the first program on screen. The cursor disappears system wide. cmd+tabing and opening different programs does not help, only switching the screen to another program and then closing and reopening the lid. I had this issue a few times already, don't know how specific it is to my setup. If I wake the laptop from sleep when theres a different program on screen and then switch to atom - there is no problem (usually, still happened a few times, but it's not consistent)

### Steps to Reproduce

1. have atom open as the main screen
2. close the lid of the laptop
3. open the lid of the laptop - the cursor is gone.

### Versions

atom : 1.34
electron: 2.0.16
chrome: 61.0.3163.100
node: 8.9.3
macojs mojave 10.14.2

### Additional Information

If you need a list of installed plugins - let me know.

**Comment by rsese** [comment]
Thanks for the report!

> If you need a list of installed plugins - let me know.

Looks like the `Prerequisites` section was removed, can you confirm if you can reproduce if Atom is running in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by Pionell** [comment]
Update to the issue - after turning atom off, the problem persisted, so this most likely is a macos bug. I'll update this issue if I find out more about this.

**Comment by rsese** [comment]
:+1:  I did quick Google search and a disappearing cursor seems to be a general issue people have come across in various versions of macOS.
