### ISSUE TITLE
"Open Folder" activates "Open File" dialog instead

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#18835]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

File -> Open Folder opens the "Open File" dialog instead.

### Steps to Reproduce

1. File -> Open Folder

**Expected behavior:** Open Folder dialog appears

**Actual behavior:** Open File dialog appears

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.37.0-dev-363741a88
Electron: 3.1.3
Chrome  : 66.0.3359.181
Node    : 10.2.0
```
Windows 10 x64

### Additional Information
![open-folder-file](https://user-images.githubusercontent.com/2766036/52656678-d85dbb80-2ec4-11e9-97c7-01dd71c3bba9.gif)

`application:open-folder` and Ctrl+Shift+O work as expected.

**Comment by 50Wliu** [comment]
Add Project Folder is fine.

**Comment by daviwil** [comment]
Fix is here: https://github.com/atom/atom/pull/18855

**Comment by ruesier** [comment]
I'm on linux (ubuntu 16.04), I just updated today to atom version today and I get the same problem.

atom --version
Atom    : 1.35.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by jasonrudolph** [comment]
@ruesier: Sorry for the trouble. We're tracking this regression in https://github.com/atom/atom/issues/18971 and we're actively [working on a fix](https://github.com/atom/atom/issues/18971#issuecomment-472178783). Please subscribe to https://github.com/atom/atom/issues/18971 if you'd like to get updates on the status of the fix.
