### ISSUE TITLE
copied keybinding with single quote should be escaped

### ISSUE THREAD

**Issue by htor** [atom/atom#18845]
when copying a keybinding like `emmet:remove-tag` (which is binded by default to `cmd-'`) using the copy button in keybindings the `'` should be escaped in order not to break the CSON format.

**Expected behavior:** [What you expect to happen]

copied string is:

```
'.platform-darwin atom-text-editor:not([mini])':
  'cmd-\'': 'emmet:remove-tag'
```

**Actual behavior:** [What actually happens]

copied string is:

```
'.platform-darwin atom-text-editor:not([mini])':
  'cmd-'': 'emmet:remove-tag'
```

### Versions

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by Aerijo** [comment]
@htor FYI, the repo for this issue should be atom/settings-view
