### ISSUE TITLE
Duplicate entries for certain modes shown in grammar selector

### ISSUE THREAD

**Issue by wesinator** [atom/atom#18852]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Duplicate entries for some grammar modes are shown in grammar language selector
<img width="609" alt="image" src="https://user-images.githubusercontent.com/5124946/52816274-ea7b5d80-306e-11e9-92f5-d6ce77f0409d.png">

<img width="602" alt="image" src="https://user-images.githubusercontent.com/5124946/52816642-b5bbd600-306f-11e9-9603-f87d76b994cb.png">

### Steps to Reproduce

Multiple tabs, git tab was open
1. Pasted Python code to new file
2. Open grammar selector, filter 'python'

**Expected behavior:** One entry per grammar

**Actual behavior:** Duplicates of the following grammars
Python grammars
plain text
JSON
Hydrogen breakpoints

Couldn't reproduce in safe mode

**Reproduces how often:** Sometimes

### Versions

macOS
```
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.10
git 2.17.2
```

### Additional Information

Relevant installed packages:
 - Hydrogen
 - linter, linter-pylint, linter-ui-default, busy-signal, intentions
grammar-selector 0.50.1

**Comment by rsese** [comment]
Thanks for the report - 

> Couldn't reproduce in safe mode

Not sure if by "sometimes" you mean that you can reproduce relatively easily (e.g. you don't have to wait all day for it to show up) but if it's easy to reproduce, did you try disabling any of those packages to see if that makes a difference?  

Also, when you see the duplicates, if you run `atom.grammars.getGrammars()` in devtools console do you see the duplicates there as well?  If so, what do you see for the `path` property of the duplicates?

**Comment by wesinator** [comment]
sometimes meaning it doesn't reproduce consistently.

So disabling hydrogen and restarting seemed to fix it, but even since re-enabling hydrogen, I haven't seen it again.

**Comment by rsese** [comment]
:+1:  Since it's not reproducible now and it's unclear how Atom got in this state, we'll close for now but can reopen if you or anyone else sees the same issue.
