### ISSUE TITLE
Deleting folded code not working as expected

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1885]
Halp ticket:
- support/11bdd39ac40011e3954faf564804671b

> When you fold a code chunk, then go to the line below the folded code and hit backspace, you expect it to delete the newline and jump to the line with the folded code. It deletes the newline AND the folded code. Probably not the behavior most people are expecting (caught me by surprise the first time).

Currently, I can't reproduce exactly this behavior. However, deleting folded code does not work as I would expect either -- when I press backspace, not only is the folded code deleted, but also the whole line containing the ellipsis representing the folded code as well.

Here's a GIF of me pressing backspace once to delete some folded code:

![foobar](https://cloud.githubusercontent.com/assets/38924/2748043/85ca7064-c7a1-11e3-89d9-2b1ea1be8a05.gif)

**Comment by zeckalpha** [comment]
This issue is a bit stale. @izuzak, @philipgiuliani, is this still occurring for you?

**Comment by revelt** [comment]
Hi all, should we close this issue? It seems to be fixed since:

![deleting](https://cloud.githubusercontent.com/assets/8344688/20464025/7cc284c2-af37-11e6-839a-45aedf159763.gif)

**Comment by Ben3eeE** [comment]
Closing since this seems to have been fixed. If you still experience this issue in a recent version of Atom then please open a new issue and fill out the issue template. Thanks @revelt.
