### ISSUE TITLE
my install package error ,Please help me.!!!

### ISSUE THREAD

**Issue by joseonjun** [atom/atom#18868]
When installing the package, an error occurred and it cannot be installed. Please help me.
-------------------------------------------------------------------------------------------------------------
spawn C:\Program Files (x86)\Windows Kits\10\bin ENOENT

Installing “atom-js-console@1.2.2” failed.Show output…
Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.

**Comment by 50Wliu** [comment]
Please install Python 2.7 and Visual Studio, as instructed by the error output.
