### ISSUE TITLE
Virtual memory leak, while executing make

### ISSUE THREAD

**Issue by bgottschall** [atom/atom#18869]
Atom allocates huge amounts of memory without freeing it while a make process is running in a project directory of atom. Memory allocation stops when make exits and starts over when make is called. This happens for me on **linux** in **safe mode**.

### Steps to Reproduce

I'm checking out the linux repo and compile it with a default config. Other projects with some make load are working as well!

1. `git clone https://github.com/torvalds/linux.git `
2. `cd linux`
3. `make clean distclean`
4. `yes "" | make oldconfig`
5. `atom --safe ./`
6. `make`

**Expected behavior:**
Atom should not allocate huge amounts of memory.

**Actual behavior:**
While make is running atom allocates around 150 MB per second. After make is finished atom uses around 50 GB virtual memory on my system. 

**Reproduces how often:**
100% of the time.

### Versions

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

at least from 1.32.0 this issue was present.

### Additional Information

Linux Mint Tara 19 (Ubuntu 18.04) @ 4.19.4-041904-generic
Dell XPS 15 9570 @ 32 GB RAM

**Comment by bgottschall** [comment]
I want to add that I'm aware that this is about virtual memory and not real memory usage. However, atom easily ends up with 500 GB of virtual memory mapped on my system in a normal 1-2 hour workflow.

**Comment by rsese** [comment]
Just to clarify, how are you measuring how much virtual memory you're using (e.g. are you running `free` periodically or just running `top` while it's building)?

**Comment by bgottschall** [comment]
Im running `htop` to watch the virtual memory of atom. If its using too much several hundreds of gb it gets killed.
