### ISSUE TITLE
Markdown Literary Programming that don't break the syntax of any programming language

### ISSUE THREAD

**Issue by linpengcheng** [atom/atom#18867]
Markdown Literary Programming that don't break the syntax of any programming language

from : 

[Markdown Literary Programming that don't break the syntax of any programming language](https://github.com/linpengcheng/PurefunctionPipelineDataflow/blob/master/doc/markdown_literary_programming.md)

**Comment by lee-dohm** [comment]
Thanks for the pointer. We don't use the [Literate Programming model](http://www.literateprogramming.com/knuthweb.pdf) for our code or documentation, so this isn't going to be useful to us. Good luck in using it with your own projects though!
