### ISSUE TITLE
Menu bars aren't flashed when keyboard shortcuts are used

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1887]
Halp ticket
- support/3c957af0c7a211e39af58f4647ff645a

> As a Mac user, in general, I expect the appropriate menu bar item to flash blue (or, I guess the system highlight color) when I use a keyboard shortcut. Without this visual feedback, I constantly find myself second-guessing whether or not I've hit the keys for the shortcut hard enough to actually trigger the shortcut.

**Comment by bomberstudios** [comment]
> Woah, this is a OSX feature? I hate the stupid flashing!

Some of us expect it, and use it as a visual proof that we hit the correct shortcut : )

I just spent a few seconds hitting CMD+C repeatedly, thinking it wasn't working because the menu didn't flash ; )

**Comment by alexrussell** [comment]
@bomberstudios You know what, I must say I've definitely become more accustomed to it these days. I still don't *need* it there, but I wouldn't quite call it "stupid flashing" any more.

In fact I occasionally use it (not in Atom) to work out where a given keyboard shortcut's original menu item is located - seeing which menu flashes can narrow it down a fair bit.
