### ISSUE TITLE
No graphical window opens on Ubuntu 18.04.2

### ISSUE THREAD

**Issue by fowlie** [atom/atom#18874]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I installed Atom version 1.34.0 from https://atom.io/download/deb with dpkg on Ubuntu 18.04.2. This is the first time I installed the Atom package on this particular system. When I start the application there is no graphical window showing up. The Atom icon and the application name shows up in the activites bar on the top of my screen, and I can click on it and it will display a dropdown list with just an option to quit (which do work). A process is also started, and when I kill it from command line a dialog box pops up suggesting to report the issue on github.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%.

### Versions
```
$ atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

$ grep VERSION= /etc/os-release
VERSION="18.04.2 LTS (Bionic Beaver)"
```

**Comment by rsese** [comment]
Thanks for the report -

> The Atom icon and the application name shows up in the activites bar on the top of my screen, and I can click on it and it will display a dropdown list with just an option to quit (which do work).

If you click on `Window > Zoom` does that bring up any window?

**Comment by kylesmith63** [comment]
I have the same problem on ElementaryOS.

$ atom --version
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ cat /etc/os-release 
NAME="elementary OS"
VERSION="5.0 Juno"

**Comment by fowlie** [comment]
> If you click on `Window > Zoom` does that bring up any window?

Not sure where on the screen you think I have a zoom option, I can't see anything like that.

**Comment by rsese** [comment]
Ahhh sorry, mixed up my operating systems (was remembering people having similar issues on macOS) - for Ubuntu, in case the window is there but just off-screen, does this help @fowlie?

https://github.com/atom/atom/issues/8737#issuecomment-139608891
