### ISSUE TITLE
`Atom is only available for 64-bit Linux systems.` is false

### ISSUE THREAD

**Issue by zaoqi** [atom/atom#18873]
README.md: `Atom is only available for 64-bit Linux systems.`
 is false
https://discuss.atom.io/t/atom-on-the-raspberry-pi/33332
It is possible to install Atom on the Raspberry Pi. armv7l.

**Comment by lee-dohm** [comment]
Thanks for the pointer. While it is true that Atom can be compiled for multiple platforms and architectures that we don't provide downloads for, conveying that people can figure out how to build their own copy and support themselves in a README in a way that people will understand is pretty challenging. If you have some suggestions on how it can be better worded, in a way that people will understand that they can support themselves at a glance, please let us know.

**Comment by zaoqi** [comment]
@lee-dohm 
`The provided binary is only available for 64-bit systems.`?

**Comment by Aerijo** [comment]
@zaoqi ...which is true. The steps you link to do not use the provided binary; they build from source.

**Comment by zaoqi** [comment]
@Aerijo 
`amd64` is not `64-bit`.
@lee-dohm
`The provided binary files is only available for Intel or AMD 64-bit Linux systems.`?

**Comment by Arcanemagus** [comment]
Ah, are you talking about how the current wording says generically "64 bit Linux systems", when it should say something like "x86_64 Linux systems"?

The problem with saying "Intel or AMD" is that is just making the same error, but the other way (as there are VIA x86-64 chips). It's probably a better wording though as most people don't know about those processors.

----

> `amd64` is not `64-bit`.There is `aarch64`.

`amd64` _is_ 64-bit, it's just not _all_ of the available 64-bit architectures.
