### ISSUE TITLE
Using ibus,The previous character has a high probability of being deleted.

### ISSUE THREAD

**Issue by zaoqi-unsafe** [atom/atom#18872]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Using ibus,The previous character has a high probability of being deleted.

### Steps to Reproduce
```
$ sudo apt install ibus-pinyin ...
...
$ wget https://github.com/atom/atom/releases/download/v1.34.0/atom-amd64.deb
$ sudo dpkg -i atom-amd64.deb
$ xhost si:localuser:...
$ sudo -i -u ... 'sh' -c "XMODIFIERS='$XMODIFIERS' atom"
```

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
```
Debian 9
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.13
git 2.11.0
```
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks for the report - I don't have Debian available so I tried to set things up on Ubuntu 18.04 with Atom 1.34.0, here's what I did:

1. `sudo apt install ibus-pinyin`
2. In `Settings > Region & Language`, clicked `Manage Installed Languages`
3. Clicked `Install / Remove Language`
4. Checked `Chinese (Simplified)`, then clicked `Apply`
5. Language wasn't available under `Settings > Region & Language > Input Sources` so restarted, then added Chinese through `Settings > Region & Language > Input Sources`, clicking the `+`, and adding Chinese from there.
6. Changed the input to `Chinese (Pinyin)` in the menu bar drop down

Then in Atom, I just tried choosing random characters:

![chinese-input](https://user-images.githubusercontent.com/734194/53206832-9c7ad280-35f7-11e9-8231-3ca6db894337.gif)

Didn't notice any characters getting deleted.

Can you share any more details for reproducing?  If you can share a GIF of the behavior, that could be helpful too.

Lastly, have you used previous versions of Atom?  If so, is this a problem new to 1.34.0 or have you seen this problem in older versions of Atom?

**Comment by zaoqi** [comment]
@rsese 
https://github.com/zaoqi/share/blob/master/ibus-atom.mp4.zip

**Comment by zaoqi** [comment]
@rsese I haven't used previous versions of Atom.

**Comment by zaoqi** [comment]
@rsese
