### ISSUE TITLE
EBUSY: resource busy or locked, unlink

### ISSUE THREAD

**Issue by jmiguel-hdez** [atom/atom#18879]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    *x Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    *x Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * xChecked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    *x Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * xChecked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
EBUSY: resource busy or locked
[Description of the issue]
I am not able to install any package for some reason. It looks like a file is locked but even if i delete the temp directory i can't fix it. I tried safe mode and it doesn't work either 

VM22 <embedded>:14 Installing package sort-lines failed Error: Installing “sort-lines@0.18.0” failed.
    at C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:899339
    at r (C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:11:893791)
    at o (C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\static\<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12) C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:218
      throw er
      ^

Error: EBUSY: resource busy or locked, unlink 'C:\Users\jherna3\AppData\Local\Temp\8\apm-install-dir-119119-19568-ng8g0e.ck9qp'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at rimrafSync (C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:211:13)
    at cleanupDirsSync (C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\apm\node_modules\temp\lib\temp.js:143:5)
    at process.cleanupSync (C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\apm\node_modules\temp\lib\temp.js:196:19)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)

(anonymous) @ VM22 <embedded>:14
m @ VM22 <embedded>:11
(anonymous) @ VM22 <embedded>:11
r @ VM22 <embedded>:11
o @ VM22 <embedded>:14
n.process.on.e @ VM22 <embedded>:14
emitTwo @ events.js:126
emit @ events.js:214
ChildProcess._handle.onexit @ internal/child_process.js:198

### Steps to Reproduce

1. [First Step]
if happen during regular use, i notice while trying to install a package today 
however, it is not limited to a single package. IT happen to me once and i was to solve by deleting and reinstalling everything. but i can't be doing this on a daily basis. 

2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]
i should be able to update or remove packages 

**Actual behavior:** [What actually happens]
i can't install packages anymore 

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
C:\Users\jherna3>atom --version

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

C:\Users\jherna3>atom --clear-window-state

C:\Users\jherna3>atom --clear-window-state

C:\Users\jherna3>apm links
C:\Users\jherna3\.atom\dev\packages (0)
└── (no links)
C:\Users\jherna3\.atom\packages (0)
└── (no links)

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jmiguel-hdez** [comment]
ok, doing this helps 
rename %USERPROFILE%\.atom .atom-backup  

which could mean only user directory is corrupted. 
it would be cool to be able to recover it and/or discover how to avoid this problem. 
i will do a backup and reinstall everything in the mean time

**Comment by rsese** [comment]
> ok, doing this helps
> rename %USERPROFILE%.atom .atom-backup
> 
> which could mean only user directory is corrupted.

If you haven't seen the same problem since [resetting to factory defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults), it does sound like there was some problem in your home directory.

So just to clarify, you can no longer reproduce now?

**Comment by jmiguel-hdez** [comment]
no, it happened again 
just by leaving the the editor open for a while 
it seems something locks 

  throw er
      ^

Error: EBUSY: resource busy or locked, unlink 'C:\Users\jherna3\AppData\Local\Temp\8\apm-install-dir-119122-79648-1g017xw.at7i'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at rimrafSync (C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:211:13)
    at cleanupDirsSync (C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\apm\node_modules\temp\lib\temp.js:143:5)
    at process.cleanupSync (C:\Users\jherna3\AppData\Local\atom\app-1.34.0\resources\app\apm\node_modules\temp\lib\temp.js:196:19)
    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)

**Comment by jmiguel-hdez** [comment]
wonder if this is related to these
https://github.com/isaacs/node-graceful-fs/issues/127
https://github.com/isaacs/rimraf/issues/86

**Comment by NorthRiver** [comment]
I'm having the same issue here. I wonder if it could be related to permissions relative to software installation. I'm on a company computer. However i can't delete the temp folder as i also get a "busy" error in that case. Packages appear installed afterward so maybe it's just the deletion that is blocked ? Isn't "unlink" the command to delete the remaining package installer from the temp folder ?

**Comment by PaulJaval** [comment]
I had the same issue on a company computer. You can trick a little by opening Atom as admin, install the packages, and move the packages from the .atom/packages of the admin folder to your own .atom/packages folder. When you will open up Atom in a non-admin way after that, it will install the added package: some parts of the installation might still fail though, as the process might need admin rights for some modules (for instance, if you want to install Juno that comes with parts of Julia, webIO module will probably fail on install)
