### ISSUE TITLE
Clipboard works only for English keyboard layout ubuntu 18.04. (russian layout not)

### ISSUE THREAD

**Issue by manking99** [atom/atom#18881]
Good day. Clipboard works only for English keyboard layout.
For Russian, text from the clipboard is not inserted.

### Versions
1.34.0 64.
Ubuntu 18.04

omen hp
OMEN 17-w226ur 3RM81EA

**Comment by rsese** [comment]
Thanks for the report!  It looks like this was an issue in earlier versions of Atom but fixed back in 1.14 e.g. see https://github.com/atom/atom/issues/13626.  If you're reproducing with a [supported installation of Atom](https://flight-manual.atom.io/getting-started/sections/installing-atom/), can you re-open this in https://github.com/atom/atom-keymap so we have it in the right place?  We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Also, please completely fill out the issue template, the information in the template is super helpful for us when triaging issues.

Thanks for meeting us half way 👍
