### ISSUE TITLE
linux.cson makes it impossible to set custom keyboard shortcuts

### ISSUE THREAD

**Issue by Jogala** [atom/atom#18909]
Hej I am running atom under linux Fedora 28.

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3

If I set in the keymap.cson file:

```
'atom-text-editor:not([mini])':
  'alt-left': 'last-cursor-position:previous'

'atom-text-editor:not([mini])':
  'alt-right': 'last-cursor-position:next'
```
I get the error message 

**Duplicate key 'atom-text-editor:not([mini])'**

Using ctrl + . I can see the the problem is that also core:linux.cson uses that file.
So I click on the link to the linux.cson file and just delete the two entries. 

It was still not working but I thought, that is clear it probably needs to be reloaded, hence I restarted atom. But the problem persisted. The problem is that the linux.cson is newly created in the tmp folder everytime I start atom! 

Hence it seems impossible to change change the keyboard bindings for keys that are used by linux.cson!

PS:  atom is great, great job

![screenshot from 2019-02-26 00-19-58](https://user-images.githubusercontent.com/5442389/53375808-9456c600-395c-11e9-9b64-317a2ce948ff.png)

**Comment by Aerijo** [comment]
```cson
'atom-text-editor:not([mini])':
  'alt-left': 'last-cursor-position:previous'
  'alt-right': 'last-cursor-position:next'
```

Had you tried not duplicating the key?

**Comment by 50Wliu** [comment]
@Aerijo is correct; see the warning in [this section](https://flight-manual.atom.io/using-atom/sections/basic-customization/#configuring-with-cson) of the Flight Manual.

**Comment by Jogala** [comment]
Sorry for my stupidity and thanks a lot for your help!
