### ISSUE TITLE
tree-view .gitignore `/folder/**/` pattern mismatch

### ISSUE THREAD

**Issue by CharlSteynberg** [atom/atom#18903]
If you have a `.gitignore` file in your repo root, and you want to ignore sub-directories inside a folder, the following pattern works in git, but Atom shows in tree-view that **ALL** items in "folder" are ignored (dark grey), instead of only the sub-folders.

```
    /folder/**/
```
-OR-
```
    folder/**/
```
I've ran the following command to verify what is being ignored by Git, and it showed only items inside the sub-folders are being ignored:
```
   find . -type f  | git check-ignore --stdin
```
-hence the specific pattern matching in the tree-view is ignored. I do contract & expand tree folder item to refresh after saving the `.gitignore`.

I hope this gets fixed to save someone else the trouble for gawking in disbelief about "working" gitignore commands on StackOverflow, when only the tree-view highlighting was lying.

**Comment by rsese** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/tree-view/ repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Also, please use the issue template when opening issues - the information and format of the template is super helpful for us when triaging issues.

Thanks for meeting us half way 👍
