### ISSUE TITLE
Bug: Goto line opens intermediary code folds 

### ISSUE THREAD

**Issue by Nokel81** [atom/atom#18901]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When using atom's Goto line feature it currently goes to every line after each new number is typed. In doing so it opens any code folds which is really annoying.

### Steps to Reproduce

1. Have code folded on line 13
2. Start going to line 134
3. Once Goto 13 has been typed observe that the code fold is opened

**Expected behavior:** Not opened until enter is hit (or the dialogue is closed)

**Actual behavior:** code fold opens

*Edit by @rsese to add a GIF (fold at line 26, trying to go to line 265, code at line 26 unfolds):*

![go-to-unfold](https://user-images.githubusercontent.com/734194/53359989-021dd600-38fa-11e9-92fe-8b1b65c8d38d.gif)

**Reproduces how often:** Everytime

### Versions:

Recent

**Comment by rsese** [comment]
Thanks for opening a separate issue for this @Nokel81 - reproduced on macOS 10.12.6 with 1.34.0.

**Comment by lee-dohm** [comment]
Thanks for the report.

This was a consequence of the recent incremental search change. Because we feel that this was a beneficial change, we aren't going to revert it to fix this behavior. However, we would be open to a well-written pull request that _refolds_ the unfolded section if it is navigated away from as part of an incremental search. For that, I'll mark this `help-wanted` so that it is easily searchable.

Thanks again for the well-written issue!

**Comment by Nokel81** [comment]
Would it be possible to instead have an option that doesn't unfold the code until the goto dialog is closed?

**Comment by lee-dohm** [comment]
I'm much less sure about something like that because with incremental search, we can't know if `13` is where you intend to stop and what if you're not sure if it is `13`, `14`, or `15` until the code is unfolded?

**Comment by Nokel81** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} I generally use 'goto line' after receiving an error from the runtime or compiler. So I don't generally look at the unfolded code as it goes along.                                                                                                                                                                                                                                                                                                                 From: notifications@github.comSent: February 26, 2019 7:40 PMTo: atom@noreply.github.comReply to: reply@reply.github.comCc: sebastian@malton.name; mention@noreply.github.comSubject: Re: [atom/atom] Bug: Goto line opens intermediary code folds  (#18901)  I'm much less sure about something like that because with incremental search, we can't know if 13 is where you intend to stop and what if you're not sure if it is 13, 14, or 15 until the code is unfolded?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lee-dohm** [comment]
Unfortunately, you're not the only person that uses this feature. We have to consider all the other users too. If you want something that's completely tailored for your use case, you can feel free to fork the original https://github.com/atom/go-to-line package and modify it to work however you want.
