### ISSUE TITLE
Programmatically calling pane.activate() does not update its isFocused() state

### ISSUE THREAD

**Issue by robertrossmann** [atom/atom#18913]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Programmatically activating a pane does not update the pane's `isFocused()` status (the pane is still reporting as not being focused), despite the docs stating that upon calling this function the pane should gain focus. The pane actually _does gain focus_ as I can type in the pane's view and perform all the expected operations inside the view; this is only an internal inconsistency with how the pane's focus is reported when the pane is focused programmatically.

### Steps to Reproduce

1. Programmatically activate a pane:
  ```js
  const pane = atom.workspace.paneForURI('atom://nuclide-terminal-view')
  // Check that the pane is not focused
  assert.ok(!pane.isFocused())
  pane.activate()
  ```
2. Programmatically observe the pane's focus state
  ```js
  assert.ok(pane.isFocused()) // fails
  ```

*Edit by @rsese: [alternate repro code snippet](https://github.com/atom/atom/issues/18913#issuecomment-479285351)*

```javascript
const assert = require('assert')
const pane = atom.workspace.paneForURI('atom://config')
assert.ok(!pane.isFocused())
pane.activate()
assert.ok(pane.isFocused()) 
```

**Expected behavior:** Programmatically focusing a pane should update it's `.isFocused()` status

**Actual behavior:** Programmatically focusing a pane does not update the pane's `.isFocused()` status, causing plugins to not recognise that pane as being focused

**Reproduces how often:** 100%

### Versions

```sh
Atom    : 1.35.0-beta0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

I believe the `Pane.activate()` method should call `this.focus()` to toggle the focus programmatically. Alternatively, this is some Electron issue where the expectation would be that the "view layer" toggles the focus once the pane becomes activated, though I am uncertain how these things work in Atom. 🤔 

-----

#### Possibly related

The `Pane` class also has an `.activateItemForURI(URI)` method. This method's name suggests that the pane would become _activated_, much like what would happen when you call `.activate()` on the pane, thus gaining focus etc. However, this method does not make the pane _activated_ at all. In other words, to actually activate the pane, I have to manually activate it after activating the item for URI:

```js
pane.activateItemForURI('atom://nuclide-terminal-view')
// Dock does not appear if it is currently hidden, but the pane switches to the correct view
// To actually open the dock and focus the item, I have to activate the pane explicitly:
pane.activate()
```

Not sure if this is intended behaviour or a separate bug. 🤷‍♂️

**Comment by rsese** [comment]
Thanks @robertrossmann :+1:   Can you share a code sample that works without Nuclide?  E.g. is this the equivalent assuming I have settings open?

```javascript
const assert = require('assert')
const pane = atom.workspace.paneForURI('atom://config')
assert.ok(!pane.isFocused())
pane.activate()
assert.ok(pane.isFocused()) 
```

**Comment by robertrossmann** [comment]
@rsese Yes, the above code snippet exhibits the problem - just tried on Atom `1.36.0-beta2`.

**Comment by rsese** [comment]
Great thanks for confirming @robertrossmann :+1:

**Comment by rafeca** [comment]
I'm not super familiar with the lifecycle of panes in Atom (@nathansobo may not much better), but I can send a PR changing the logic to set the `focused` flag to true whenever `activate()` is called and see if all tests pass.
