### ISSUE TITLE
Deactivate "Atom" name translation in Spanish

### ISSUE THREAD

**Issue by danielramos001** [atom/atom#18927]
## Summary

Deactivate "Atom" name translation in Spanish.

## Motivation

It is translated to "Atomo", it does not sound good and "Atom" is more used to refer to the editor in the Spanish community.

## Describe alternatives you've considered

This must be changed in the repository for all Spanish users.

**Comment by lee-dohm** [comment]
Since Atom doesn't perform any sort of translations or have a localizable UI, I'm not sure how this translation you're talking about might be occurring. If this is in Atom, it is most likely due to a community package. Can you give some repro steps of how to find this mistaken translation?

**Comment by exequielbc** [comment]
@danielramos001 please provide with more information, e.g. reproduction steps or screenshots; I agree that that would sound bad haha
