### ISSUE TITLE
Atom Helper using 101% of CPU on macOS

### ISSUE THREAD

**Issue by manasesjesus** [atom/atom#18925]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom Helper is using more than 100%of CPU. I don't have a GitHub repository. 
I opened a subdirectory of a mercurial repository which only contains .md files as it is used for documentation. Atom Helper always runs with high CPU usage.

### Steps to Reproduce

1. Open Atom
2. Open Activity Monitor
3. Verify CPU usage

**Expected behavior:** Atom Helper uses low CPU percentage 

**Actual behavior:** Atom Helper uses high CPU percentage 

**Reproduces how often:** Always

### Versions

Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0
python 2.7.10
git 2.17.2

macOS Mojave 10.14.2

**Comment by rsese** [comment]
Thanks for the report!

> I don't have a GitHub repository.

Do you mean that you've already checked if you have a `.git/` directory in your home directory or just that you're not working with a Git repository when you see the high CPU usage?

> I opened a subdirectory of a mercurial repository which only contains .md files as it is used for documentation. Atom Helper always runs with high CPU usage.

Just to clarify, do you only see the high CPU usage when you work with this project or do you see it with any project?

Lastly, when you tried in safe mode was the behavior exactly the same?

**Comment by manasesjesus** [comment]
> Do you mean that you've already checked if you have a `.git/` directory in your home directory or just that you're not working with a Git repository when you see the high CPU usage?

It is not a git repository, hence there's no `.git/` folder. I mentioned it because others reported a similar issue while working with git.

> Just to clarify, do you only see the high CPU usage when you work with this project or do you see it with any project?

I followed the classic *have you turned it off and on again?* and after restart the CPU usage went down to 0.2% 
I have been working since and everything seems normal, so there was no need to try the safe mode.

**Comment by rsese** [comment]
> It is not a git repository, hence there's no `.git/` folder. I mentioned it because others reported a similar issue while working with git.

Thanks but I was also wondering if you checked for a `.git/` directory in your home directory?  We've seen reports where people have done that accidentally and that can cause problems.

> I followed the classic _have you turned it off and on again?_ and after restart the CPU usage went down to 0.2%
> I have been working since and everything seems normal, so there was no need to try the safe mode.

Ahh ok so just to clarify, you can no longer reproduce the high CPU usage?

**Comment by manasesjesus** [comment]
> Thanks but I was also wondering if you checked for a .git/ directory in your home directory? We've seen reports where people have done that accidentally and that can cause problems.

No, I don't have it. Doubled checked.

> Ahh ok so just to clarify, you can no longer reproduce the high CPU usage?

Fortunately (or unfortunately) not. Maybe it was a one-time issue. So far CPU usage has been under 1%.

**Comment by rsese** [comment]
> Fortunately (or unfortunately) not. Maybe it was a one-time issue. So far CPU usage has been under 1%.

Thanks for confirming :+1:  Since it's not reproducible right now, we'll go ahead and close but we can always reopen if you see this again and have steps to reproduce the high CPU usage.

**Comment by Jesssullivan** [comment]
<img width="303" alt="Atom1" src="https://user-images.githubusercontent.com/37297218/54075522-82372a80-426e-11e9-9210-bc8d492bd4d6.png">
<img width="237" alt="Atom2" src="https://user-images.githubusercontent.com/37297218/54075523-82372a80-426e-11e9-97b2-82ea754221e8.png">

I have the same issues stated here.  Atom is unusable on OSX 10.14.3 for me- I disabled all Git related plugins as well.  Hmmm.  Any ideas?

**Comment by rsese** [comment]
Go ahead and open a new issue and fill out the issue template @Jesssullivan and we'll take a look with you.
