### ISSUE TITLE
Atom opens chrome developer tools on startup (unless it is run as root) [issue is different from issue #9220]

### ISSUE THREAD

**Issue by soutzis** [atom/atom#18936]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When running atom as normal user (not root), then atom only opens chrome dev tools. Note, that there is no error displayed on the dev tools window.

### Steps to Reproduce

1. Download latest atom .deb package .
`$ wget -O atom-amd64.deb https://atom.io/download/deb`
2. Install atom using `gdebi`.
`$ sudo gdebi atom-amd64.deb`
3. Run atom as user.

**Expected behavior:** [What you expect to happen]
Expect atom to open normally when ran.

**Actual behavior:** [What actually happens]
If atom is ran as: 
`$ sudo atom`
Then atom runs normally; no problems there.
BUT if atom is not ran as root:
`$ atom`
Then atom opens chrome developer tools
**Reproduces how often:** [What percentage of the time does it reproduce?]
Always.

**SOLUTION**
-DO NOT install atom using `gdebi`. Install with `dpkg` fixes the issue.
(Replace {step 2} from steps to reproduce, with the following command to fix:
`$ sudo dpkg -i atom-amd64.deb`

### Versions
1.34 (latest as of today)

### Additional Information
Operating System: Ubuntu 18.04 LTS

**Comment by Arcanemagus** [comment]
Could you elaborate on why this is an Atom issue? `gdebi` is not our [recommended way of installing Atom](https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux), and since it is working with how we recommend you install it this sounds like `gdebi` is doing something incorrect when installing it.

**Comment by soutzis** [comment]
My mistake then. I assumed that you'd like to know about this issue with `gdebi`. Closing this issue now.
