### ISSUE TITLE
Caret graphical glitch when moved

### ISSUE THREAD

**Issue by nidoro** [atom/atom#18934]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The caret does not show where I would expect it to show when using keybinded movement.

### Steps to Reproduce

1. Map `core:move-down` to `ctrl-j` and `core:move-up` to `ctrl-k`.
2. Open a file and move down once with `ctrl-j`.
3. Try to move up once with `ctrl-k`.

**Expected behavior:** The caret move down or up just like when using arrow keys.

**Actual behavior:** The caret does not move. But it after step 3 I type something, the text goes to the line that I would expect the caret to be. So it seems to be a rendering issue for the most part. The arrow keys do not present the same issue.

**Reproduces how often:** 100%.

### Versions
Atom: 1.24.x to 1.34.0
Windows 10 64bit

**Comment by rsese** [comment]
Thanks for the report -

> 3\. Try to move up once with `ctrl-k`.

I think `ctrl-k` is the issue, see this message board post for example:

https://discuss.atom.io/t/whats-wrong-with-my-ctrl-hjkl-and-ctrl-keybindings/35229/2

Go ahead and give the suggestion there a try and see if it helps.  If you're not tied specifically to `ctrl-k`, using a different keybinding should work too.
