### ISSUE TITLE
bootstrap error on centos 6.6: a lot errors and warnings for ../src/parser.c

### ISSUE THREAD

**Issue by alexdongli** [atom/atom#18930]
Tried to build atom v1.34.0 on centOS v6.6. All the prerequisites have been installed, but when running "./script/bootstra", I got a lot of errors and warnings (see below, only very few error and warning lines are copied here). I believe it is a very small issue that caused a lot errors.

Alex.

Stdout:
Node:   v6.11.4
Npm:    v3.10.10
Installing script dependencies
Installing apm
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom unknown
python 2.7.11
git 2.18.0
Installing modules ✗

Stderr:
....
gyp verb build/config.gypi writing out config file: /mnt/share/rh/source/small_packages/temp/atom-1.34.0/node_modules/tree-sitter-c/build/config.gypi
gyp verb config.gypi checking for gypi file: /mnt/share/rh/source/small_packages/temp/atom-1.34.0/node_modules/tree-sitter-c/config.gypi
gyp verb common.gypi checking for gypi file: /mnt/share/rh/source/small_packages/temp/atom-1.34.0/node_modules/tree-sitter-c/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /mnt/share/rh/source/small_packages/temp/atom-1.34.0/apm/node_modules/atom-package-manager/bin/python-interceptor.sh
gyp info spawn args [ '/mnt/share/rh/source/small_packages/temp/atom-1.34.0/apm/node_modules/atom-package-manager/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/share/rh/source/small_packages/temp/atom-1.34.0/node_modules/tree-sitter-c/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/share/rh/source/small_packages/temp/atom-1.34.0/apm/node_modules/atom-package-manager/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/shengxin/.atom/.node-gyp/.node-gyp/iojs-2.0.16/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/shengxin/.atom/.node-gyp/.node-gyp/iojs-2.0.16',
gyp info spawn args   '-Dnode_gyp_dir=/mnt/share/rh/source/small_packages/temp/atom-1.34.0/apm/node_modules/atom-package-manager/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/share/rh/source/small_packages/temp/atom-1.34.0/node_modules/tree-sitter-c',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/shengxin/.atom/.node-gyp/.node-gyp/iojs-2.0.16
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../src/parser.c:1:
../src/tree_sitter/parser.h:52: warning: declaration does not declare anything
../src/tree_sitter/parser.h:58: warning: declaration does not declare anything
../src/tree_sitter/parser.h:73: warning: declaration does not declare anything
../src/parser.c:4: warning: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’
../src/parser.c:58245: error: unknown field ‘count’ specified in initializer
../src/parser.c:58245: warning: missing braces around initializer
../src/parser.c:58245: warning: (near initialization for ‘ts_parse_actions[0].action’)

...

make: *** [Release/obj.target/tree_sitter_c_binding/src/parser.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/mnt/share/rh/source/small_packages/temp/atom-1.34.0/apm/node_modules/atom-package-manager/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-504.el6.x86_64
gyp ERR! command "/mnt/share/rh/source/small_packages/temp/atom-1.34.0/apm/node_modules/atom-package-manager/bin/node" "/mnt/share/rh/source/small_packages/temp/atom-1.34.0/apm/node_modules/atom-package-manager/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /mnt/share/rh/source/small_packages/temp/atom-1.34.0/node_modules/tree-sitter-c
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-c@0.13.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-c@0.13.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shengxin/.atom/.apm/_logs/2019-03-01T00_06_14_997Z-debug.log[39m
child_process.js:495
    throw err;
    ^

Error: Command failed: /mnt/share/rh/source/small_packages/temp/atom-1.34.0/apm/node_modules/atom-package-manager/bin/apm --loglevel=error install
    at checkExecSyncError (child_process.js:472:13)
    at Object.execFileSync (child_process.js:492:13)
    at module.exports (/mnt/share/rh/source/small_packages/temp/atom-1.34.0/script/lib/run-apm-install.js:14:16)
    at Object.<anonymous> (/mnt/share/rh/source/small_packages/temp/atom-1.34.0/script/bootstrap:44:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by Aerijo** [comment]
> Node: v6.11.4

I don't know if the Electron version Atom uses works with that Node version; what happens if you build with Node 8.9.3?

**Comment by alexdongli** [comment]
Dear Gray,

Thanks for trying to help! I installed Node 8.9.3, updated PATH,
LD_LIBRARY_PATH, and PKG_CONFIG_PATH accordingly, and tried to run
script/bootstrap again but got the same error message.

Alex.
