### ISSUE TITLE
Missing libgconf2 although GConf2 is installed

### ISSUE THREAD

**Issue by cristianarbe** [atom/atom#18938]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

In Fedora 29, getting: `/usr/share/atom/atom: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory` when trying to open atom on Fedora although gconf2 is installed. Started happening after a `dnf upgrade`.

### Steps to Reproduce

1. Open atom from the terminal

**Expected behavior:** [What you expect to happen]

Atom is opened normally.

**Actual behavior:** [What actually happens]

`/usr/share/atom/atom: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

Tried 1.34.0 and 1.35.0. Happens in both.

### Additional Information

What I tried:
* Installing GConf2
* Reinstalling
* Installing different versions
* Rebuilding the rpm and adding GConf2

**Comment by nejcokorn** [comment]
@cristianarbe Please run the command bellow and paste the output in this thread

`sudo find / -name libgconf*`

This will list all the files on your system starting with **libgconf***

**Comment by cristianarbe** [comment]
Output is:

```
/usr/lib/GConf/2/libgconfbackend-oldxml.so
/usr/lib/GConf/2/libgconfbackend-xml.so
/usr/lib/libgconf-2.so.4.1.5
/usr/lib/libgconf-2.so.4
```

**Comment by nejcokorn** [comment]
Great, so the library does exist.
I would have guessed it is the issue with the path to the libraries.

What do the following commands return
`cat /etc/ld.so.conf.d/*`
and
`echo $LD_LIBRARY_PATH`

**Comment by cristianarbe** [comment]
I get `/usr/lib64//bind9-export/`

**Comment by nejcokorn** [comment]
Try setting `LD_LIBRARY_PATH` to `/usr/lib` and running atom from the terminal in the same session as
```
export LD_LIBRARY_PATH=/usr/lib
atom
```

This will temporarly set the library path so you can see if this is the issue.

If you wish to permenately set the library path to **/usr/lib** then create a file in **/etc/ld.so.conf.d/example.conf** with the following content
```
/usr/lib
```
and run `sudo ldconfig` to activate the above library path

**Comment by cristianarbe** [comment]
After doing what you mentioned I got: `/usr/share/atom/atom: error while loading shared libraries: libgconf-2.so.4: wrong ELF class: ELFCLASS32` when opening atom.

**Comment by nejcokorn** [comment]
The error you get is probably because the **libgconf-2.so.4** you have is a 32bit library

I have checked the path to the **libgconf-2.so.4** on my Ubuntu 18.04 and it is located under `/usr/lib/x86_64-linux-gnu`
By the path name on your system and my system I would say you don't have 64bit **libgconf-2.so.4** as it is located in `/usr/lib` but of course that is just a guess

How did you install GConf2?
What version of GConf2 did you install?

If you are unable to install 64bit **GConf2** using system package mananger you could still install 64bit version manually - [https://rpmfind.net/linux/rpm2html/search.php?query=gconf2](url)

**Comment by cristianarbe** [comment]
Removing GConf2 32 bits and installing GConf2 64 bits solved the issue. Thanks a lot :+1:

**Comment by rsese** [comment]
Yes, thanks very much for the help debugging this one @nejcokorn :bow:
