### ISSUE TITLE
Nonoptimal CI build / lint ordering

### ISSUE THREAD

**Issue by Aerijo** [atom/atom#18940]
### Description

The CI script will build Atom before running the linter on it. As building takes a significant amount of time, and linting does (or at least should) not depend on generated files, the linter should be run first to fail early.

### Steps to Reproduce

1. Make a PR with a linting error (e.g., using double instead of single quotes)
2. Wait [insert long time] for the CI to build Atom
3. Fail immediately after because the linting script errored

**Expected behavior:** [What you expect to happen]
To tell me as soon as it started that the linting failed

**Actual behavior:** [What actually happens]
Waited until it built everything

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
1.34.0

### Additional Information

There may be other steps that can be done earlier, but this is the one I run into most often. We can call `script/lint` on the main repo, but packages don't have this.

**Comment by lee-dohm** [comment]
If you wouldn't mind submitting a PR for this, we would prioritize it @Aerijo :+1: Thanks for catching this!

**Comment by 50Wliu** [comment]
The slight hitch with this is that the required dependencies for the linter aren't installed until after `script\bootstrap` is run, which occurs as part of the build script...

**Comment by Aerijo** [comment]
It would be possible to install the linter dependencies separately though, right?
