### ISSUE TITLE
File > Open… doesn't work when there are no open windows

### ISSUE THREAD

**Issue by wvteijlingen** [atom/atom#18941]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When there is no open window, the `File > Open…` menu item doesn't do anything.

### Steps to Reproduce

1. Close all open windows.
2. Select `File > Open…` in the menu bar.
3. Nothing happens.

**Expected behavior:** I expect the "Open" dialog to show.

**Actual behavior:** Nothing happens when there is no window open. It does work when there is a window open.

**Reproduces how often:** 100$

### Versions
```
Atom    : 1.35.0-beta0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
OS      : Mac OS 10.14.3
```

**Comment by rsese** [comment]
Thanks for the report!  This was fixed in https://github.com/atom/atom/pull/17529 and the fix will be available in the next releases.
