### ISSUE TITLE
Uncaught error: no dialog when can't move file

### ISSUE THREAD

**Issue by mrfelipenoronha** [atom/atom#18943]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The editor don't show any kind of dialog/warning when trying to move a file to a folder that already has a file with the same name.

### Steps to Reproduce

1. Create a file 'tet.c' (1);
2. Create a empty folder;
3. Create a file 'tet.c' inside the folder (2);
4. Try to copy/cut the tet.c (1) inside the created folder;
5. Nothing happens, no dialog shown.

**Expected behavior:** A messageBox or something from the kind saying "File already exists!".

**Actual behavior:** Nothing happens.

**Reproduces how often:** All the time

### Versions

Atom    : 1.31.1
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.1
python 3.7.1
git 2.17.1

Ubuntu 18.04.2 LTS

**Comment by rsese** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the https://github.com/atom/tree-view repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

One note:

> Try to copy/cut the tet.c (1) inside the created folder;
> Nothing happens, no dialog shown.
>
> **Expected behavior:** A messageBox or something from the kind saying "File already exists!".
> 
> **Actual behavior:** Nothing happens.

The copy case does copy the file, the copy created has a `0` is appended to the file name.  There's an existing request for a prompt in that case /cc https://github.com/atom/tree-view/issues/567.

Thanks for meeting us half way 👍
