### ISSUE TITLE
Soft wrap cuts off text sometimes

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1894]
Halp ticket:
- support/99c4b424c63611e397d244a7153df9be

> Soft wrap is very buggy. Often, the cursor will stop displaying in the right position. Seems to happen more after doing a find and replace. It'll show up about 4 characters away from where it's actually inserted. And some characters will be impossible to select/delete.

...

> Disabled all my packages. Still having wrapping issues. See line 30 in this screen shot: https://www.dropbox.com/s/p2416k52npr3sre/Screenshot%202014-04-22%2011.00.33.png
> The end of that data-tooltip-position attribute should have “bottom left”, but bottom is just getting cut off. I’m on version 0.90.0 now.

![screenshot 2014-04-22 11 00 33](https://cloud.githubusercontent.com/assets/38924/2769147/73a0c92a-ca4d-11e3-8be3-0a4feb0958c8.png)

**Comment by sbaker7** [comment]
This is still an issue. It's been an issue since the new update. and I can't even scroll to see what's at the end when it goes way over for no reason. The issue is in latex and some files wrap properly, but others don't. I haven't worked out why yet. Here's a photo example of the issue: http://puu.sh/kftyQ/37467ad672.png

**Comment by benogle** [comment]
@as-cii will this be fixed due to text measurement fixes?

**Comment by as-cii** [comment]
@benogle: I don't think so, as soft-wrapping right now relies on counting the column rather than actually measuring the text. We're going to talk to the Chromium team about this soon because they could probably expose a soft-wrapping API which returns all the soft wrapping points.

**Comment by nabsiddiqui** [comment]
+1
