### ISSUE TITLE
stylesheet wont change background  atom 1.34.0

### ISSUE THREAD

**Issue by crazycoder121** [atom/atom#18957]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

when changing the editor background in the stylesheet it doesnt change, but when you do the exact same in the inspector (in the same element) it works...

### Steps to Reproduce
this wallpaper will be on any macOS NEWER than el capitan. if you run linux, change the wallpaper to something diffrent. 
1. open the user stylesheet
2. paste this in the otherwise stock stylesheet:.flexbox-repaint-hack  {
  background:  url("/Library/Destop Pictures/Sierra.jpg");
}
3. presss cmd + s
4 see nothing happen
5 open the inspector, and go to .flexbox.repaint-hack
6 get the part where you added the flexbox paint (will only contain background url)
7 copy and paste the background property and value
8 inherit/disable the copied background property
9 paste the copied property, and tadaaa! it works...

**Expected behavior:** [What you expect to happen]
change the wallpaper
**Actual behavior:** [What actually happens]
nothing
**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time
### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
1.34.0
### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
i tested this with an clean install

**Comment by rsese** [comment]
Thanks for reaching out - not sure why that's happening but this seems like a better question for the official message board or the Atom Slack:

* https://discuss.atom.io
* http://atom-slack.herokuapp.com/

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

I searched around and also found that there's a community package that lets you set the background image:

https://atom.io/packages/editor-background

And I gave it a quick try and it seems to work.
