### ISSUE TITLE
Add an event for text backspace and deletion

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#18951]
## Summary

Add a new event for text backspaces and deletions. Something like `TextEditor::onWill/DidBackspace/Delete()`.

## Motivation

Events exist for inserting text, but not for deleting text. Packages that need to act when text is deleted need to resort to methods such as monkey-patching the delete and backspace methods.

## Describe alternatives you've considered

The new event could be `TextEditor::onWill/DidDelete(backspace)` rather than having two separate events for backspace and delete.

## Additional context

bracket-matcher currently has to monkey-patch backspace: https://github.com/atom/bracket-matcher/blob/8a3bd1e347b02d8ad0c30ffa1a80836d9625a234/lib/bracket-matcher.js#L19

**Comment by lee-dohm** [comment]
Hey, we noticed this was related to https://github.com/atom/atom/issues/18950 ... seems like this should be one RFC that explains the general theory?

**Comment by 50Wliu** [comment]
Sure.
