### ISSUE TITLE
Provide Option to Enable 'darkTheme' Option of BrowserWindow

### ISSUE THREAD

**Issue by amxmln** [atom/atom#18958]
### Description

This has come up multiple times, but all issues regarding this problem I could find have been locked because of low activity, so I’m opening a new one.
On Linux many GTK themes provide a dark variant of the theme for windows with predominantly dark contents. Electron allows windows to request this dark variant through the "darkTheme" option of the BrowserWindow class, but Atom provides no way to set that option for a user.
This is an issue because if title bars are generally light, they stick out like a sore thumb if the user chooses to use a dark UI / syntax theme and are very distracting. In such cases it would be ideal for the user to be able to set an option to have Atom use the dark theme variant.

### Steps to Reproduce

1. Open Atom on a Linux system with a light gtk theme with a dark variant
2. See the light title bar of Atom and be distracted by it
3. Look for an option to set Atom to use the dark theme variant and not find it

**Expected behavior:** Finding an option to have Atom use the dark theme variant, set it and restart Atom, now without a distracting light titlebar.
**Actual behavior:** There's no such option.

**Reproduces how often:** Every time.

### Versions

Atom: 1.34.0
APM: 2.1.3

### Additional Information

Perhaps this could be implemented similiarly to how the custom title bar styles on macOS are handled, i.e. during the initialisation of a BrowserWindow, check the configuration whether the option for 'darkTheme' is set and if it is, set it to `true` in the BrowserWindow options. 

Thank you all for your hard work and for considering this issue.

**Comment by rsese** [comment]
Is this issue different than https://github.com/atom/atom/issues/13249?

> * Open Atom on a Linux system with a light gtk theme with a dark variant
> * See the light title bar of Atom and be distracted by it

Not sure if I'm misunderstanding here but I installed gnome-tweaks and after switching from Adwaita to Adwaita-dark, Atom's title bar updates to dark?

![linux-dark](https://user-images.githubusercontent.com/734194/54057195-ddf2ac80-41b7-11e9-9f12-fb688c401741.gif)

**Comment by amxmln** [comment]
Actually I believe it’s different, yes. As far as I can tell, that issue is talking about generally providing a way to customise the titlebar similarly to how it’s done on macOS. What I’m talking about is enabling the dark variant of a GTK theme.

It works fine if you shift your whole environment to a dark variant, what doesn’t work currently is an application specific dark variant. In your case, leaving it on Adwaita, but having Atom use Adwaita-dark (similarly to how the Terminal and Videos apps use the dark variant even though you’re just using Adwaita). To achieve that in Electron there’s the darkTheme BrowserWindow option as far as I know.

**Comment by amxmln** [comment]
This issue is still relevant for the current version of Atom.

- Version: 1.44.0
- Ubuntu 19.10, elementary OS 5.1
- Open Atom with a dark syntax theme, but a light GTK theme that supports a dark variant (i.e. Adwaita). The window titlebar, menubar and dialogues use the light GTK theme and there is no way to set Atom to request a dark style

This should be able to be fixed by using the `darkTheme` option of the Electron BrowserWindow class upon initialisation if a corresponding setting is set in the Atom config.
