### ISSUE TITLE
Saving moved files is confusing for some users

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1896]
Halp tickets:
* support/5faf0c18c3ab11e38dacd5d22cc224b1
* support/00caa684c59111e393ec7e730bc5c159

>1) Open a file
> 2) Move the file to different folder ( while it is still open )
> Now the file stays open and is still editable. When I save it. it saves to the previous location instead of the new location. I found it quite annoying.

...

> I have a directory with files open for editing. Now I clicked rename to rename that directory and I actually moved the directory one-level-up, but the files that were opened in editor are still saved to old location, whereas they should be now saved to new location.

**Comment by peterjeliot** [comment]
I'm experiencing the same problem as cosnis. When autosave is enabled and the file is open, duplicating a file will not cause the tab to update to the new filename, and so rename duplicates the file instead. If the file is closed, it works as expected.

**Comment by izuzak** [comment]
This is being tracked over in https://github.com/atom/autosave/issues/9 so closing this one.
