### ISSUE TITLE
RHEL 7.6: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by bigbrozer** [atom/atom#18974]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Under RHEL 7.6, with libstdc++.x64 version 4.8.5-36.el7, when running `atom` nothing is appearing. Looking at `~/.atom/nohup.out`:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/atom/resources/app.asar.unpacked/node_modules/nslog/build/Release/nslog.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nslog/lib/nslog.js:5:11)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/nslog/lib/nslog.js:15:4)
```

Looking at available `GLIBCXX_*`:

```shell
$ strings /lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

`GLIBCXX_3.4.21` is not available.

### Steps to Reproduce

1. Upgrade / install atom-1.35.0 from RPM package repository.
2. Run `atom`.

**Expected behavior:** Atom window appearing.

**Actual behavior:** Nothing is appearing

**Reproduces how often:** 100%

### Versions

**RHEL 7.6** with **atom-1.35.0-0.1** installed from official RPM repository.

**Comment by bigbrozer** [comment]
**UPDATES**

Did a test with new version 1.35.1 and works again perfectly ! I think this issue can be closed ?

**Comment by PrimerMediaGroup** [comment]
Every number has to stay the same due to a an old memories on simpler devices using simpler technology

**Comment by rsese** [comment]
> Did a test with new version 1.35.1 and works again perfectly ! I think this issue can be closed ?

I don't have a RHEL to test with so if things are working for you we can close this out :+1:  I did poke around a bit though and it seemed like this was an issue with RHEL?  ref: https://access.redhat.com/discussions/3405861
