### ISSUE TITLE
There is no application menu for splitting panes

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1897]
Halp ticket:
* support/85a2c09ec59111e38c6c9405f6a8beeb

> I'm missing the functionality to arrange editors horizontally next to each other to be able to see/edit two files at once.
> ...
> damn it, I was looking in the menu and couldn't find it there. 

Seems reasonable to add pane-splitting commands to the menu, and I think I've seen another email like this before, but can't find it now.

**Comment by ricardograca** [comment]
Probably stupid question, but was this ever added? I can't see anything related to splitting views in my menus.

Ubuntu 14.04, Atom 0.177.0.

**Comment by izuzak** [comment]
@ricardograca It was added. You don't see this?

![screen shot 2015-02-27 at 13 33 58](https://cloud.githubusercontent.com/assets/38924/6412529/5bfbc54a-be85-11e4-9f9a-3fb2d12b3874.png)

Can you update to the latest version of Atom and share a screenshot?

**Comment by ricardograca** [comment]
Nope. Only:

...
Toggle Full Screen
Toggle Menu Bar
Developer
...

**Comment by ricardograca** [comment]
Looking at the commit it seems this change was only implemented for OSX. @probablycorey Any reason for that?

**Comment by izuzak** [comment]
Great eyes, @ricardograca - I completely missed that. I don't see a reason not to have those in the Linux version as well. Reopening this

**Comment by asantos3** [comment]
Just like @ricardograca said, this was only implemented in OSX and Windows, it's missing in Linux. [Here's a screenshot of it.](https://cloud.githubusercontent.com/assets/1958425/7028919/378f4732-dd51-11e4-8e95-0a6e7a094038.png)

**Comment by kevinsawicki** [comment]
Sorry this took so long to fix, it will be included in the next Atom release 0.191
