### ISSUE TITLE
enhanced (non twinview) dual-display support

### ISSUE THREAD

**Issue by tempest766** [atom/atom#18970]
No support for traditional multi-monitor/separate-$DISPLAY configs in X11?  Not surprising, but the lack of that feature limits its utility for old UNIX hacks like myself.

In current behaviour spawning additional instances places them in the same DISPLAY and same desktop panel as the primary atom GUI.  With multiple monitors, each running separate fvwm window managers, that's less than optimal behaiour.

**Comment by rsese** [comment]
Sorry for the delay and thanks for the note - there are known problems around multiple monitors/workspaces so we'll close this in favor of those issues (e.g. https://github.com/atom/atom/issues/11610).  For future issues, it would also be super useful for us if you could fill out the issue template - the template format and information helps us when triaging issues.

Thanks again :v:
