### ISSUE TITLE
Opening atom using exe file: Exception error

### ISSUE THREAD

**Issue by rster2002** [atom/atom#18975]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When opening atom using the executable it crashes stating: "Error: The specified module could not be found". Opening a atom from the command line works fine.

### Steps to Reproduce

1. Open Atom using the executable (found in `C:\Users\<username>\AppData\Local\atom`). It won't open.
2. Open a random folder with the command line and type `atom`. This **does** work.

**Expected behavior:** [What you expect to happen]

It should open atom like normal.

**Actual behavior:** [What actually happens]

It crashes with an Javascript error. See attachment 1.

**Reproduces how often:** [What percentage of the time does it reproduce?]

I had this since I restarted my PC at 12th of March. 100%

### Versions

Enviorments: 
* Windows: `10 Home`
* Atom: `1.34.0`
* Electron: `2.0.16`
* Chrome: `61.0.3163.100`
* Node: `8.9.3`

### Additional Information

![image](https://user-images.githubusercontent.com/26026518/54217594-37c2e180-44ec-11e9-8155-a8e751ddada3.png)

**Comment by rsese** [comment]
Thanks for the report!

> * Atom: `1.34.0`

I see the screenshot mentions Atom 1.35.0, I wonder if there was an issue after updating?  If you close Atom and then reinstall with the installer from https://atom.io, does that clear things up for you?

**Comment by rster2002** [comment]
It does. Atom now launches using the exe. It updated to version `1.35.1`.

**Comment by rster2002** [comment]
I think future updates will tell if it is an reacurring issue.

**Comment by rsese** [comment]
Ok sounds good - we'll go ahead and close for now but can reopen later if necessary.  For what it's worth, I updated to 1.35.1 on Windows yesterday and didn't notice any problems.
