### ISSUE TITLE
Package specs can't use external packages

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#18983]
### Prerequisites

Not applicable.

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

https://github.com/atom/atom/pull/18801 changed how the Atom profile for spec runs works, making it use an entirely new profile folder. This had the unintended side-effect of breaking the specs of packages that rely on loading other packages in while testing, since the external packages can no longer be loaded.

#### In general

1. Run `apm install <external package>`
2. Run `atom --test spec` on a _different_ package, that calls `atom.packages.activatePackage('<external package>');`

#### Exact steps

1. Start a container with `docker run --rm -it arcanemagus/atom-docker-ci:v1.36.0-beta1 bash`
  * All subsequent steps are run within the container
2. `git clone https://github.com/AtomLinter/linter-bailey.git && cd linter-bailey`
3. `git checkout c502b71`
4. `${APM_SCRIPT_PATH} install "language-bailey"`
5. `${APM_SCRIPT_PATH} install`
6. `${ATOM_SCRIPT_PATH} --test spec`

Compare with running the same steps in a container started with:
`docker run --rm -it arcanemagus/atom-docker-ci:v1.35.1 bash`

**Expected behavior:**

External packages that were installed before the specs were ran are able to be resolved and loaded in the specs.

**Actual behavior:**

The external packages can no longer be resolved.

**Reproduces how often:**

100% of the time.

Example failure: https://circleci.com/workflow-run/18b1cb01-c82e-4e7f-8a5b-861bdacf5936

### Versions

```
Atom    : 1.36.0-beta1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0-beta1
python 2.7.15rc1
git 2.17.1
```

OS: Tested in Linux containers and locally on Windows.

### Additional Information

Potential solutions outlined in chats with @smashwilson:

* If `ATOM_TEST_PACKAGES` is set in the environment, symlink all of those into the temporary profile folder
  * This will work for _most_ configurations that have followed the example of `atom/ci`, but doesn't account for manual configurations that are just running the commands directly
* Create some API to mark packages for including in the temporary profile explicit
  * This won't work for existing setups, but is a nice solution for the future
* Disable using a temporary profile in CI environments
  * This brings us back to the risk of corruption/non-reproducibility that the original PR was meant to solve

I verified locally that #18801 was the culprit by running a build that exhibited the issue at first, running `git revert 8e6d833`, and checking that the issue was gone.

**Comment by banacorn** [comment]
I have problem using `atom.packages.activatePackage("XXX")` in my spec.
It always throws `Error: Failed to load package 'XXX'`, is it related to this issue?

**Comment by Arcanemagus** [comment]
That depends on whether `XXX` is the pacakge you are testing, or a _different_ package that your package that you are testing requires in order to run. If it's a separate package you can work around this issue by adding it to the `APM_TEST_PACKAGES` environment variable (added in #18984).

**Comment by banacorn** [comment]
Sorry, after changing a different test-runner, my problem is gone.
Now I can see `XXX` in `atom.packages.getLoadedPackages()` after `atom.packages.loadPackages()` again!

**Comment by sadick254** [comment]
Good to now the issue was resolved. Closing this issue based on https://github.com/atom/atom/issues/18983#issuecomment-510313141
