### ISSUE TITLE
Atom won't run without Internet

### ISSUE THREAD

**Issue by cubetronic** [atom/atom#18997]
issue exists as of today. i downloaded the latest installer for windows 10.. 64 bit..
i installed, used it while i was online, and it worked ok, though it does seem to be a heavy program and takes a few moments to load...
then i tried running it while offline, and... *nothing*... i couldn't open a file with it, or run it directly from the start menu.
i restarted my computer, thinking that might help, but it didn't help.
i got online and of course it loaded up normally.

sorry if i don't have all the bug testing info you're looking for. i'm not into spending time on this. and i'm not going to try messing around with safe mode or anything else. i will say i'm on the latest version of windows 10 as of this writing

**Comment by cubetronic** [comment]
ok so i read in some other post that enabling some adapter or something "solves the issue" for someone.. but honestly, that is not a "solution".. just a workaround at best

>atom --version

Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

>ver

Microsoft Windows [Version 10.0.17763.253]

**Comment by cubetronic** [comment]
i don't know if this is noteworthy, but i don't use chrome. i'm a firefox person. so chrome is not installed on this machine

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by cubetronic** [comment]
that's one way of closing bug reports...

i really don't like how this program might not work if i'm offline, regardless of the circumstances. so i don't see how it's important for me to spend a bunch of time filling out forms. i don't plan on using it now anyway.
