### ISSUE TITLE
Flaky build: AppVeyor build sometimes fails due to problems uploading JUnit XML

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#18994]
In our AppVeyor builds, we sometimes see the build fail when it has trouble uploading the JUnit XML files. For example...

```
...
Finished in 710.703 seconds
2089 tests, 11649 assertions, 0 failures, 8 skipped
Command exited with code 1
$wc = New-Object 'System.Net.WebClient'
$endpoint = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
Write-Output "Searching for JUnit XML output beneath $($env:TEST_JUNIT_XML_ROOT)"
Get-ChildItem -Path $env:TEST_JUNIT_XML_ROOT -Recurse -File -Name -Include "*.xml" | ForEach-Object {
  $full = "$($env:TEST_JUNIT_XML_ROOT)\$($_)"
  Write-Output "Uploading JUnit XML file $($full)"
  $wc.UploadFile($endpoint, $full)
}
Searching for JUnit XML output beneath c:\projects\junit-test-results
Uploading JUnit XML file c:\projects\junit-test-results\core-main-process.xml
Uploading JUnit XML file c:\projects\junit-test-results\core-render-process.xml
Exception calling "UploadFile" with "2" argument(s): "The remote server returned an error: (500) Internal Server Error."
At line:7 char:3
+   $wc.UploadFile($endpoint, $full)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

Rebuilding can sometimes resolve the failure.

I wonder if we could enhance the build script to retry the upload if it fails at first. Alternatively, perhaps we could consider catching this error and logging it, but not allowing it to cause the overall build to fail.

---

**Affected CI provider(s)**: AppVeyor

**Affected platform(s)**: Windows

**Example commit experiencing flakiness**: https://github.com/atom/atom/commit/b6bf3a5c5d2d74c998cb953131d516e854893288

**Example failing build at that commit**: https://ci.appveyor.com/project/Atom/atom/builds/23020313/job/aeqv4kml7rhony8o

**Example passing build at that commit**: https://ci.appveyor.com/project/Atom/atom/builds/23023754

**Example log from failing build**: https://github.com/atom/atom/files/2968124/build.log

**Comment by jasonrudolph** [comment]
Happened two more times: 

- https://ci.appveyor.com/project/Atom/atom/builds/22988139/job/qsbmjlisx3m70qd8#L2237
- https://ci.appveyor.com/project/Atom/atom/builds/22989936/job/q8ns484u2l970ksx#L2229

**Comment by rafeca** [comment]
Another time:

* https://ci.appveyor.com/project/Atom/atom/builds/23187726/job/deb4by5jr3mcr0k8

**Comment by jasonrudolph** [comment]
A couple more:

- https://ci.appveyor.com/project/Atom/atom/builds/23222531/job/x4afnj1o7x9phiho#L2224
- https://ci.appveyor.com/project/Atom/atom/builds/23280615/job/81uh9159k4s6691v#L2250
