### ISSUE TITLE
Flaky test: WorkspaceElement mousing over docks ... shows the toggle button when the dock is open

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#18992]
In our Windows builds, we sometimes see the build fail at [this point in the test suite](https://github.visualstudio.com/Atom/_build/results?buildId=35191&view=logs&jobId=4fbced83-508e-5fe0-c978-5c71ec0fc506&taskId=469abba8-e098-5409-562f-26dedf3df794&lineStart=86&lineEnd=103&colStart=1&colEnd=32)...

```
WorkspaceElement
  mousing over docks
    it shows the toggle button when the dock is open
      Expected '<div class="atom-dock-toggle-button left atom-dock-toggle-button-visible"><div class="atom-dock-toggle-button-inner left"><span class="icon icon-chevron-right"></div></div>' not to have class 'atom-dock-toggle-button-visible'.
        at expectToggleButtonHidden (file:///D:/a/1/s/spec/workspace-element-spec.js:703:50)
        at file:///D:/a/1/s/spec/workspace-element-spec.js:642:7
        at Generator.next (<anonymous>)
        at step (D:\a\1\s\spec\workspace-element-spec.js:1:428)
        at <anonymous>

Finished in 939.691 seconds
2083 tests, 11764 assertions, 1 failure, 8 skipped
```

Rebuilding can sometimes resolve the failure.

---

**Affected CI provider(s)**: Azure DevOps

**Affected platform(s)**: Windows 64-bit

**Example commit experiencing flakiness**: https://github.com/atom/atom/commit/8d8e39d0f85dfe96c1985c3d0159c3c1bba10c22

**Example failing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=35191

**Example passing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=35164

**Example log from failing build**: https://github.com/atom/atom/files/2967697/build.log

**Comment by rafeca** [comment]
I'm gonna investigate this one

**Comment by rafeca** [comment]
I've added a `for` loop on [that test](https://github.com/atom/atom/blob/master/spec/workspace-element-spec.js#L593) to do a stress run of 500 consecutive executions and saw 13 of them fail (~2.6% of indeterminism).

Looks like a timing issue, gonna check how hard is to fix
