### ISSUE TITLE
TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by Oi-apps** [atom/atom#19004]
Issue  https://github.com/atom/atom/issues/18696 was closed because of the lack of response from the original  bug reporter. Bug hasn't been patched as there are some more complaints about it in the original thread as well.

Issue appeared during the package installation process or immediately after it.
I installed package "terminal..." which promises to start  the search  from the current folder. After trying the command ls> list.txt in this terminal inside Atom, terminal changed the cursor size and reported error message appeared.  I remove the package completely.As of now package search in Atom  doesn't work, and the bug message appears every time when I try to search a package. Apparently, exact  title of this package can't be found as of now.
As of Node itself, Sublime works with it correctly and I run the js from it as I wish. Node works from  system terminal as well.

------------------------------------------------------

 usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:248
Hide Stack Trace
TypeError: Cannot read property 'version' of undefined
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:248:40
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:333:24
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

    [Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:248

TypeError: Cannot read property 'version' of undefined
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:248:40
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:333:24
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -2:26.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-ide-ui 0.0.0 
atom-perl6-editor-tools 0.10.7 
build 0.69.0 
busy-signal 1.4.3 
dark-green-ui 0.1.0 
file-icons 2.1.13 
fonts 3.0.3 
glacier-dark-ui 0.5.0 
hackify-ui 0.3.0 
hacking-the-kernel 1.6.2 
hacking-the-kernel-ui 1.6.2 
Hydrogen 2.0.1 
hyperclick 0.1.5 
intentions 1.1.5 
ksx-matrix 1.4.1 
ksx-matrix-ui 1.2.8 
language-perl6 1.16.0 
linter 2.2.0 
linter-ui-default 1.6.10 
naturegreen-dark-syntax 0.1.1 
react 0.18.0 
react-autocomplete 1.2.0 
react-snippets 1.1.2 
script 3.17.2 
seafoam-syntax 2.2.0 
tree-view-autoresize 2.3.0 
tree-view-panes 0.3.7 
tron-green-ui 0.7.0 
```

**Comment by Oi-apps** [comment]
after some experimenting it seems that the culprit is atom-terminal@0.8.0
Rebooting after package removal  helped to get rid of  Cannot read property 'version' error, but with this package installation module didn't work for me. Also after leaving the installation panel removing the package is not possible. Probably, I can do it after one more reboot.
atom-ide-terminal@5.0.1 works just fine anyway.
I think that the initial crash was caused by em dash (long  dash) symbol in directory name. But after removing this symbol another  issue caused by this package (installer can't being called) is still present

**Comment by Oi-apps** [comment]
the issue was definitely caused by atom-terminal@0.8.0.
It takes TWO more reboots to get rid of the error message. First reboot- -to get rid of atom-terminal@0.8.0 (when Settings tab appeared I removed atom-terminal@0.8.0., but after reopening Atom error message repeated).
After 2nd reboot thing seem to settled down. 
Probably atom-terminal@0.8.0 conflicts with another similar packages- it was installed as a second package after another terminal-related (working) package was already here.

**Comment by rsese** [comment]
> Issue #18696 was closed because of the lack of response from the original bug reporter. Bug hasn't been patched as there are some more complaints about it in the original thread as well.

Doesn't seem like anyone shared specific repro steps but I'll ask in that issue.

> the issue was definitely caused by atom-terminal@0.8.0.

Thanks for tracking that down for the error in your case - it may be that there is still a bug in Atom but if so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
