### ISSUE TITLE
#! in package.json breaks package install: npm ERR! path /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/sntp/package.json

### ISSUE THREAD

**Issue by AJCxZ0** [atom/atom#19005]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Steps to Reproduce

1. Start Atom
2. Select Edit > Preferences > + Install
3. Search for a package, e.g. _ansible_
4. Click desired blue [Install] button on matching package, e.g. _language-ansible_

**Expected behavior:** [What you expect to happen]

Package installs.

**Actual behavior:** [What actually happens]

Pink error box reports, `Installing “language-ansible@0.2.2” failed.Show output…`
Clicking `Show output…` reveals

    npm ERR! path /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/sntp/package.json
    npm ERR! Error parsing /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/sntp/package.json: Unexpected token # in JSON at position 0

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/cainesaj/.atom/.apm/_logs/2019-03-18T16_34_52_243Z-debug.log

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%.

### Versions

    $ cat /etc/redhat-release ; atom --version ; atom --safe
    Fedora release 29 (Twenty Nine)
    Atom    : 1.34.0
    Electron: 2.0.16
    Chrome  : 61.0.3163.100
    Node    : 8.9.3

and

    $ cat /etc/lsb-release ; atom --version ; atom --safe
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=18.04
    DISTRIB_CODENAME=bionic
    DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
    Atom    : 1.35.1
    Electron: 2.0.18
    Chrome  : 61.0.3163.100
    Node    : 8.9.3

### Additional Information

Removing the first line, `#!/usr/bin/node`, from `/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/sntp/package.json` results in the package installing as expected.

Note that this file is part of the installed atom package and that having a #! on the first line of any interpreted script is always appropriate (though `#!/usr/bin/env node` would be more portable).

    $ rpm -qf /usr/share/atom/resources/app/apm/node_modules/npm/node_modules/sntp/package.json
    atom-1.34.0-2.fc29.x86_64

**Comment by 50Wliu** [comment]
`#!/usr/bin/node` is indeed invalid JSON, and so Atom is correctly reporting that as an error.

How have you been installing Atom?

**Comment by AJCxZ0** [comment]
> How have you been installing Atom?

Installed from package on both platforms: `atom-1.34.0-2.fc29.x86_64` via Unitedrpms on Fedora and `atom-1.35.1` via Packagecloud on Ubuntu.

**Comment by AJCxZ0** [comment]
Having subsequently switched to using Atom Flatpak and Snap packages, this appears to be correct in both.

```
$ head -1 /snap/atom/248/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/sntp/package.json
{
```

```
$ head -1 /var/lib/flatpak/app/io.atom.Atom/x86_64/stable/03453d16b0fd884b182ea49f2da11751f27def6f806ae38d6d503414cdb807f6/files/share/atom/resources/app/apm/node_modules/npm/node_modules/sntp/package.json
{
```
