### ISSUE TITLE
Enhance CI build to "fail fast"

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#19006]
As one part of resolving https://github.com/atom/atom/issues/18990, let's enhance the CI build script so it terminates immediately if a package's tests fail.

### Background

https://github.com/atom/atom/issues/18990 reported problems with CI builds failing when running tests for the `language-yaml` package. The end of the CI build logs reported the following results:

```
...
Executing language-yaml tests
##[error]Bash exited with code '1'.
##[section]Finishing: Run tests
```

Upon investigation, we realized that the failures aren't happening in `language-yaml` after all. The failures are happening in other packages, but the test suite doesn't exit until it has run _all_ package tests. Since `language-yaml` is the last package whose tests are run as part of the build, we see the rather misleading output shown above.

If we look higher up in the build log, we see the real source of the failure. For example, in [this build log](https://github.visualstudio.com/Atom/_build/results?buildId=35579&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=bde16fc7-7659-5b1c-12aa-0110866d993c&lineStart=2446&lineEnd=2454&colStart=1&colEnd=1), we see that the failure occurs while running the tests for the `autosave` package:

```...
Executing autosave tests
Package tests failed for autosave:
...
Autosave > when the buffer is modified > when a pane loses focus > suppresses autosave if the file does not exist 2019-03-14 14:09:45.013 Atom Dev[84832:130522] Renderer process crashed, exiting
Executing background-tips tests
...
Executing language-yaml tests
##[error]Bash exited with code '1'.
##[section]Finishing: Run tests
```

### Proposed improvement: Teach atom/atom builds to fail fast

Currently, if the tests fail for package _x_, the build continues running the tests for all the other packages. This approach has two undesirable consequences:

1. **Developers have to wait longer than necessary to discover that their build failed.** Today, atom/atom builds are s-l-o-w. (Fixing that is a separate issue. :innocent:) If a build takes 60 minutes to run, and the tests failed 30 minutes into the build, developers currently have to wait the full 60 minutes before they learn that the build failed.

2. **The cause of the build failure is buried in the middle of the build log.** If you read the end of the build log, it _looks_ like `language-yaml` is the culprit. To find the real culprit, you have to search the build log for the word "failed".

If a package's tests fail, let's teach the atom/atom build to terminate the build immediately (to resolve # 1 above) and ensure that the cause of the failed build is present at the end of the build log (to resolve # 2 above).

**Comment by asheren** [comment]
@jasonrudolph In your opinion, how closely is this related to https://github.com/atom/atom/issues/19366 ? And I see there is a related PR that was merged in. Is this still an open issue to the same extent? I'm wondering if we should a) keep the issue, b) close the issue and reference it from https://github.com/atom/atom/issues/19366?, and/or c) remove the fy2019q5 label from it.

**Comment by jasonrudolph** [comment]
> In your opinion, how closely is this related to #19366 ?

@asheren: This issue and #19366 both describe efforts to shorten the feedback loop that we get from CI. The _goals_ are related, but the steps are unique and complementary.

> Is this still an open issue to the same extent?

Yes.

> I'm wondering if we should a) keep the issue, b) close the issue and reference it from #19366?, and/or c) remove the fy2019q5 label from it.

I think we should keep this issue _or_ make it a part of #19366.

Does that help?
