### ISSUE TITLE
Trojan:Win32/Skeeyah.l (false positive?!)

### ISSUE THREAD

**Issue by ldrizze** [atom/atom#19019]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * [ ] Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * [ ] Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * [x] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * [x] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * [x] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Just downloaded Atom and tryied to install after the new windows update (Windows 10 Version 1703 x64 KB4023057).

### Steps to Reproduce

1. Just install

**Expected behavior:** Open Atom normally

**Actual behavior:** Trojan:Win32/Skeeyahh.l detected by Windows deffender, cannot be installed.

**Reproduces how often:** 100%

### Versions

Atom: 1.35.1
Windows 10 Version 1703 x64 KB4023057

### Additional Information

I can't install Atom package so I can't debug it. I can put the node.dll in except files but I thought it was better show the issue.

![Capturar](https://user-images.githubusercontent.com/8744271/54735691-5a0ccd00-4b86-11e9-9184-b73de497e29b.PNG)

**Comment by kum4423** [comment]
I had the same problems he did. can't install atom 1.35.1 (Win 10 Pro 1809  x64 OS build 17763.379)

**Comment by Arcanemagus** [comment]
You didn't mention which version of Atom you installed, but for reference here are the SHA512 hashes for both versions:

* x86: `58B66E2585312643B4BFF858E3C64FA21D72E0B35BA38E1097F40BC5ED5B4C2E126D727000BED2D4803A9F1BFF76C698270F0A2EDF838C46CC5FDD3B11570A23`
* x64: `841E38D88CADEA44126F7BBFF2BDC302A02182F85977389B786A0F23B061D3EC9CE9EBDF086C29C18955F6E92692DA142AF6284947E0CA69C1A46AAE6B7A6156`

Assuming the `node.dll` file on your computer matches that it's a false positive from your AV vendor that you should contact them about as we have no control over that. You can try whitelisting that file to work around the issue in your AV software.

If the hashes _don't_ match then there is likely something else on your computer that is infecting random `.dll` files on your system to attempt to spread itself.

Thanks for reaching out!
