### ISSUE TITLE
Cannot open Atom editor

### ISSUE THREAD

**Issue by askonivala** [atom/atom#19039]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I cannot open Atom editor on macOS Mojave. All I get is the dialog "The editor has crashed. Please report this issue to https://github/atom/atom [Keep It Open] [Reload [Close Window]]" (see the screenshot). I have tried safemode, clearing cache, deleting storage.

![Screenshot 2019-03-24 08 46 33](https://user-images.githubusercontent.com/5494504/54876029-b6cfe800-4e11-11e9-9fd6-71d5ba9c1929.png)

If I reinstall Atom do I need to configure all my packages from scratch?

### Steps to Reproduce

1. Turning on Atom produces immediate crash.

### Versions

Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for the report - just to confirm, was there any difference when starting in safe mode?

**Comment by rsese** [comment]
> I have tried safemode, clearing cache, deleting storage.

Sorry, I missed this sentence from your report - can you clarify what you mean when you say you cleared cache and deleted storage?  Do you mean that you [cleared saved state](https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state)?

**Comment by askonivala** [comment]
Exactly, I cleared saved state, but there was no help. Running in safe mode produced exactly the same response and my editor is still not starting.

**Comment by rsese** [comment]
Thanks for confirming :+1:

After you cleared saved state, are you trying to open a specific project or are you just starting Atom with `atom --safe`?

And did you also try [temporarily resetting to factory defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults)?

**Comment by askonivala** [comment]
I have now moved my .atom folder to .atom_backup, but it does not make any difference. I have tried both running `atom --safe` on terminal or clicking the icon after clearing the save state and resetting to default settings: both result in the above mentioned error. After that I am unable to do anything else than quit the application.

By the way, after restarting the application multiple times, I can see two Atom icons on the launchbar of my Mac. Maybe that helps in debugging this.

I can keep this broken installation for few days for debugging purposes and use Sublime Text instead, but at some point I am going to uninstall it, reinstall a fresh version, and try to restore the backup of my .atom folder by simple copying it over the factor defaults. It will probably retain all my settings and packages?

**Comment by Aerijo** [comment]
> It will probably retain all my settings and packages?

@askonivala Inside the `.atom` folder, the key items are `config.cson`, `init.coffee`, `keymap.cson`, `styles.less`, and `snippets.cson`. You may want to keep a backup of those files if you don't want to risk losing your configuration somehow.

There is also the `packages` folder, which contains all community packages you have installed (core packages are stored in the application). You can choose to keep these or not; their configuration is stored in `config.cson`.

**Comment by askonivala** [comment]
I now tried to make a clean reinstall, but weird thing is that Atom still crashes on startup on my system! I did the following steps:

1. Delete the app from the Applications folder
2. rm -rf ~/.atom
3. rm /usr/local/bin/atom
4. rm /usr/local/bin/apm
5. rm ~/Library/Preferences/com.github.atom.plist
6. rm ~/Library/Application Support/com.github.atom.ShipIt
7. rm -rf ~/Library/Application Support/Atom/
8 Download the app from http://atom.io and move it to the Applications folder

**Comment by rsese** [comment]
Do you have a [crash log](https://flight-manual.atom.io/hacking-atom/sections/debugging/#find-crash-logs) that you can share @askonivala?

Also, is this crash new for you with 1.35.1 and Atom worked fine before that?  Not sure if you've used previous versions of Atom or if this is a new install with 1.35.1.

**Comment by askonivala** [comment]
Sure, see the relevant part of the crash log here:
[atom_crash.log](https://github.com/atom/atom/files/3011989/atom_crash.log)

1.35.1 is the first version of Atom I have ever installed. It has been working fine with this machine for several weeks before this. I hope the crash log helps you to debug the problem.

**Comment by bernaferrari** [comment]
Same issue here!
[atom crash logs.zip](https://github.com/atom/atom/files/3108698/atom.crash.logs.zip)

**Comment by rsese** [comment]
Sorry I missed your followup @askonivala - nothing from your crash log jumped out to me as something as I've seen before.  Have you updated to 1.36.0 and still see the same crash?

@bernaferrari -

> safe works

...

> This is new to 1.36, but I installed some plugins before getting the endless crashes, so they might be responsible for it.

If there's no problem in safe mode, then it's likely a community package causing the issue :+1:

**Comment by bernaferrari** [comment]
Yeah, but shouldn't Atom avoid this kind of problem - at least showing why it is crashing? Currently it just crashes, no explanation.
