### ISSUE TITLE
A JavaScript Error Occured in the main process

### ISSUE THREAD

**Issue by PhirosWolf** [atom/atom#19034]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Here is the complete error : 
```
A JavaScript error occured in the main process
Uncaught Exception:
Error: The specified module cannot be found.
\\?\C:\ProgramData\MyUserName\atom\app-1.35.1\resources\app.asar.unpacked\nod...\nslog.node
	at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
	at Object.Module._extensions..node (module.js:671:18)
	at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Object.<anonymous>
(C:\ProgramData\MyUserName\atom\app-1.35.1\resources\app.asar\node_modules\nslog\lib\...:11)
	at Object.<anonymous>
(C:\ProgramData\MyUserName\atom\app-1.35.1\resources\app.asar\node_modules\nslog\lib\n...:4)
```
(translated from French)
And here is the screenshot of the error : 
<img width="418" alt="Error" src="https://user-images.githubusercontent.com/34209854/54841911-bc71e480-4cd0-11e9-9f1d-c705a14062d1.PNG">

Before getting this error, I installed this : https://aka.ms/vs/15/release/VC_redist.x64.exe
(Microsoft Visual C++ Redistributable for Visual Studio 2017)

Even after reinstalling Atom, cleaning .atom, uninstalled VC_redist.x64.exe, restarting my computer, I still get this error. The only time atom actually opens is when it's launched automatically for the first time, after (re)installation.

Trying to run the `atom` command results in the same error.

### Steps to Reproduce

1. Install the Microsoft Visual C++ Redistributable for Visual Studio 2017 x64
2. Launch Atom

**Expected behavior:** I don't know if it does the same thing on other computers so I can't tell

**Actual behavior:** It causes an error, like described in the Description section

**Reproduces how often:** 100%

### Versions

Atom : 1.35.1 x64
Windows : Windows 10 Family (10.0.17134.590) x64
APM : (I don't know, because the " "apm" is not recognized as internal or external command, operable program or batch file")

**Comment by rsese** [comment]
Do you have any anti-virus software running?  If so, can you temporarily disable and then reinstall Atom and see if you still get the error after quitting and restarting Atom?

**Comment by PhirosWolf** [comment]
I have Norton Security Life Lock (Standard). Even after turning off the protection of Norton Security, I get the same error from Atom.

**Comment by PhirosWolf** [comment]
Hello,
I found how to fix this problem.
I copied the folder resources (atom/app-1.35.1/resources) from a working Atom of a friend on my resources folder.
In my resources folder, app.asar.unpacked folder and cli folder weren't present. In the working Atom, they were.
So I think the error came from the fact that these folders weren't here.
