### ISSUE TITLE
Atom Security Bug : Troj/Skeeyah-H

### ISSUE THREAD

**Issue by chowdhuryadian** [atom/atom#19033]
I had previous experience with Atom on Linux it worked just fine. I want to let you all know I love Atom! But when I installed it for the first time on Windows, all was fine until a few minutes later, Windows Defender popped up saying that there's a virus of my computer. I checked it out and saw the affected files were Atom's program files. I chose the remove option and I immediately uninstalled atom. I want to use atom on my PC but I was to be confident that this security flaw is resolved.

Virus Name:
Troj/Skeeyah-H

**Comment by 50Wliu** [comment]
Thanks for the report! Antivirus programs occasionally detect false positives, and it looks like it's misidentifying Atom as a virus in this case. If this is the same as #19019, you can check the integrity of your `node.dll` file by following the steps in that issue. Please let us know if you have any further questions!
