### ISSUE TITLE
Uncaught Error: Error writing to stdin: git -c color.ui=false -c color.status=false -c color.show...

### ISSUE THREAD

**Issue by duong7** [atom/atom#19038]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.11.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Error writing to stdin: git -c color.ui=false -c color.status=false -c color.showBranch=false -c color.diff=false -c color.branch=false rev-parse --show-toplevel in /Users/phongnguyen/Documents
undefined
Error: read EBADF

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14

Error: Error writing to stdin: git -c color.ui=false -c color.status=false -c color.showBranch=false -c color.diff=false -c color.branch=false rev-parse --show-toplevel in /Users/phongnguyen/Documents
undefined
Error: read EBADF
    at Socket.n.stdin.on.n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2756375)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
native-ui 0.27.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?
