### ISSUE TITLE
Atom "starts" but never displays

### ISSUE THREAD

**Issue by laidbackwebsage** [atom/atom#19059]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Regardless of how or from where atom is launched, the icon appears in the dock, but the window/ui never appears. Strangely, if you right-click on the icon in the dock and click on "All Windows", there is "sliver" of a window displayed. 
![atom-bug](https://user-images.githubusercontent.com/766325/55017724-b11c0300-4fc7-11e9-8aaf-a0835e6efbd9.png)

### Steps to Reproduce

1.Fresh install of Ubuntu 18.04.01, with "apt dist-upgrade."
2.Install of "atom-amd86.deb", both version 1.35.1 and atom-beta. OR
  ` sudo snap install atom --classic`

**Expected behavior:** 
Atom should start and display the UI.

**Actual behavior:** [What actually happens]
Atom starts but does NOT display the UI. If launched from the terminal, no output is provided.

**Reproduces how often:**
Happens 100% of the times that atom is launched, whether from clicking on icon, or from the terminal.

### Versions
1.35.1 and atom-beta (Not sure which version the snap package is, I think it might be 1.34).

`atom --version` outputs nothing.
`apm --version` gives me:

- apm  2.1.3
- npm  6.2.0
- node 8.9.3 x64
- atom 1.35.1
- python 2.7.15rc1
- git 2.17.1

OS: Ubuntu 18.04.2 LTS x86_64 && Ubuntu 18.10.1
Kernel: 4.15.0-46-generic

### Additional Information
What else do you need?

**Comment by rsese** [comment]
Thank for the report!

> OR
> ` sudo snap install atom --classic`

Just wanted to mention that the Snap package is unofficial and not supported by us so I'd suggest using the .deb or the official package repository.

About the issue you're reporting though, can you see if this helps?

https://github.com/atom/atom/issues/8737#issuecomment-139608891
