### ISSUE TITLE
Feature Request: Allow files/directories to be ignored by Atom Helper process.

### ISSUE THREAD

**Issue by edgartheunready** [atom/atom#19057]
## Summary

Create a way to exclude directories from the project index, maybe use .gitignore or allow files/directories to be manually selected.

I noticed a CPU usage spike from the Atom Helper process every time I loaded a Rails page. The page load caused updates to the ./log/development.log file along with updates to ./tmp/cache/assets/sprockets... Both of these directories (./log and ./tmp) are in my .gitignore. I was able to avoid the CPU usage spike by moving my log and tmp directories out of the Atom project directory. The CPU spike was caused by updates to files that I never open in atom, but lived in my project directory. 

In some worst-case testing, I held cmd+shift+r on my rails page to constantly refresh the page. With rails writing to ./log and ./tmp, I observed an Atom Helper Energy impact of 55-60 (system power draw of 38.8w). With rails writing to directories outside of the Atom project, I observed an Atom Helper Energy impact of 0.1-0.4 (system power draw of 32.5w).

**Comment by rsese** [comment]
Thanks for the suggestion -

> Create a way to exclude directories from the project index, maybe use .gitignore or allow files/directories to be manually selected.

Unless I'm misunderstanding what you're describing, you can already do this with `Settings > Exclude VCS Ignored Paths`, can you see if you have this setting enabled?  Also see `Settings > Ignored Names`.  

Also, please fill out the entire issue template when opening issues - the information is super helpful for us when triaging issues.

**Comment by edgartheunready** [comment]
Hey @rsese, thanks for pointing out those features. I do have both those directories added to my .gitignore (they are greyed out in my project tree view). The Exclude VCS Ignored Paths was already enabled, so that particular feature doesn't seem to resolve this issue. I also added *.log and *.cache to my Ignored Names list and I am still getting high  Atom Helper CPU usage (these changes seem to have no effect on the issue I'd like to resolve with this feature). Where can I find the source code for the Atom Helper process? Maybe I could poke around and see if I can find what is consuming these cycles.

**Comment by edgartheunready** [comment]
Thanks for the response @rsese, I will work on filling out the rest of the template. Exclude VCS Ignored Paths was already checked, and the ./tmp and ./log directories are greyed out in the project tree view. I updated my Ignored Names pattern and still observed the same behavior (high Atom Helper CPU usage when log file is written to and when files are created/updated/deleted in ./tmp). 

Where can I find the source code for the Atom Helper process? I'd like to poke around and better understand how it works. Thanks again for your response and help.

**Comment by edgartheunready** [comment]
Doing some more research and I found that Rails creates/modifies 1700 tmp files when loading my webapp for the first time when tmp has been cleared. My guess is that there is some sort of a filesystem watcher getting 1700+ events and maybe that's what is causing the CPU spike?

**Comment by chalofa** [comment]
@edgartheunready @rsese I can confirm having the exact same issue, a temporarily `AtomHelper` process trying to use 100% of the CPU. It's not solved with any configuration or by starting Atom in safe mode.
![image](https://user-images.githubusercontent.com/217029/57325474-b6449580-70cf-11e9-9de8-e601ed8a924a.png)


It happens with any page reload in the browser, when there has been some CSS change, which causes:

- Rails sprocket needs to recompile the affected styles (Asset Pipeline).
- Rails will create a bunch of files in `tmp/cache/assets/sprockets` (even tho that directory is my `.gitignore`, and I have atom configured to `Exclude VCS Ignored Paths`)

If I close the Atom project before the reload (even if left Atom app still open), then page reload goes way faster (I guess bc now the CPU can be fully used to compile the assets).

Some stats about `tmp/cache/assets/sprockets`: it has **13,387 files** in 1,445 directories, ~ 46 MBs in size.
![image](https://user-images.githubusercontent.com/217029/57325031-c445e680-70ce-11e9-93db-82833d5168f7.png)

- Page reload with Atom open & with assets precompilation/update takes around 22 secs.
![image](https://user-images.githubusercontent.com/217029/57325294-577f1c00-70cf-11e9-8cff-447d69e58608.png)


- Page reload with Atom open & with assets precompilation/update takes around 30 secs (and AtomHelper trying to scan every file in `tmp/cache` and using 100% of my CPU).
![image](https://user-images.githubusercontent.com/217029/57324989-aed0bc80-70ce-11e9-9618-a06a645d664e.png)

I need to confirm if this is also an issue in Linux, will do that this week and post here.

@rsese what kind of logs/info would help you guys to see what could be happening?

**Comment by edgartheunready** [comment]
@chalofa, glad to hear that I'm not alone. I was able to work around the issue by changing the logger and moving the Sprockets tmp directory. Here's what I added to my development.rb

```
Rails.logger = Logger.new STDOUT
config.log_path = '/tmp/'

config.assets.configure do |env|
 env.cache = Sprockets::Cache::FileStore.new(
     File.join('/tmp/cache/assets'),
     config.assets.cache_limit,
     env.logger
 )
end
```

It does seem like Atom should be able to completely ignore a sub-directory. In the mean time, those changes will help reduce the load on your CPU.

**Comment by rsese** [comment]
Sorry I missed your initial followup @edgartheunready - so just to clarify, the issue is that the project you're working on and have open in Atom includes a temp directory where a large number (thousands) of files are created when you load a page in your app.  Then when this happens, there's a large CPU spike (and this is even when you have the temp directory specifically ignored)?

**Comment by edgartheunready** [comment]
Exactly

**Comment by chalofa** [comment]
> ... the project you're working on and have open in Atom includes a temp directory where a large number (thousands) of files are created when you load a page in your app. Then when this happens, there's a large CPU spike (and this is even when you have the temp directory specifically ignored)?

yes, and this is the default setup for every Rails app, so it's not something only a few of us are facing (every Rails dev using a Mac and with a "normal" amount of CSS code).

After taking a closer look, this only affects macOS, with both Windows & Linux versions working like a charm (not sure bc of the fact that it's the only platform release that has an `Atom Helper.app` to run async code, like files/directory changes).

I also found a workaround with an Atom config that will prevent this issue:  
`core.fileSystemWatcher: "atom"`  
(@edgartheunready can you help confirming if it also works for you?) 

The default setting for `fileSystemWatcher` = `native`, which I tracked in Atom' source code to use `NSFWNativeWatcher` (a directory watcher) is implemented different in each OS, as stated by the creator of the `nsfw` package in the link below (_TL/DR_: macOS uses `FSEvents`, Linux uses `inotify`, while Windows has native support):
https://blog.axosoft.com/nsfw/

So, @rsese, I believe the issue with the default `fileSystemWatcher` setting (`NSFWNativeWatcher`) is located here:
https://github.com/atom/atom/blob/master/src/path-watcher.js#L282-L288

IMO, there should be some check that the `normalizedPath` is not in the `VCS Ignored Files` or `Ignored Names` settings, kind of what the `tree-view` plugin does to show/hide those:
https://github.com/atom/tree-view/blob/master/lib/directory.js#L185

Should we do some kind of very basic project that reproduces the error, but with a bash script creating/updating a bunch of tmp files, so you can reproduce it easier without having that dependency on Ruby/Rails?

**Comment by edgartheunready** [comment]
@chalofa, I updated my config.cson as you described and it did resolve the issue with an Atom process consuming 100% CPU while files are being created.
Here's my config.cson:
![image](https://user-images.githubusercontent.com/3502769/57477862-95af4380-7267-11e9-9afe-ca67171d5caf.png)

**Comment by rsese** [comment]
> After taking a closer look, this only affects macOS, with both Windows & Linux versions working like a charm

@edgartheunready are you on macOS as well?

And thanks for all the details @edgartheunready @chalofa - coincidentally, the team is looking at providing a new default file watcher system:

https://github.com/atom/atom/pull/19244

I'll ask the team about this issue but the fact that this is only an issue on macOS is interesting so I do wonder how the new file watcher system will affect things - maybe y'all would be willing to test things out when that work is available?

**Comment by edgartheunready** [comment]
I am also on Mac OS using a 2016 mbp

**Comment by chalofa** [comment]
> ... the team is looking at providing a new default file watcher system: #19244

thanks for pointing in that direction!

so, I just ran `atom --dev` using @nathansobo `ns/notify` branch, and the `Experimental` watcher "mitigates" the original `Atom Helper` high CPU usage, but it's still slower than the emulated `atom` watcher and now I see another process with high CPU usage temporarily: `notify-subprocess-darwin`
![image](https://user-images.githubusercontent.com/217029/57506445-7513d780-72c1-11e9-9837-3135480f570b.png)

### fileSystemWatcher performance with page reloads & compiling assets:

- `atom` = ~18 seconds:
![image](https://user-images.githubusercontent.com/217029/57506078-57923e00-72c0-11e9-915b-3860081c6662.png)

- `experimental` = ~25 seconds:
![image](https://user-images.githubusercontent.com/217029/57506690-2d418000-72c2-11e9-8677-95d71a942125.png)

- `native` = ~22 seconds:
![image](https://user-images.githubusercontent.com/217029/57507343-19971900-72c4-11e9-802d-bcbddce48a10.png)


@nathansobo: After a few page reloads, the `notify-subprocess-darwin` just started using high CPU until I had to manually `kill` it (quitting Atom didn't work).
There was something weird with it when continually monitoring these huge amount of temporarily files (a lot of the directories are removed after every page reload):
![image](https://user-images.githubusercontent.com/217029/57506920-d38d8580-72c2-11e9-9c98-2716999c81fb.png)

Love the idea of this new experimental watcher, but seems like there's no reason to "watch" a VCS ignored path.



> I'll ask the team about this issue but the fact that this is only an issue on macOS is interesting so I do wonder how the new file watcher system will affect things - maybe y'all would be willing to test things out when that work is available?

Of course!

Thanks for your time & help @rsese so far, it's been a great digging inside Aton's code
