### ISSUE TITLE
Invisible window when Atom starts on Elementary OS

### ISSUE THREAD

**Issue by edwino-stein** [atom/atom#19066]
### Description

I've taken invisible window when Atom starts, this behavior occurs when the Atom has closed in maximized window mode.

### Steps to Reproduce

1. Open Atom normally
2. Put in maximized window mode
3. Close the Atom
4. Re-open the Atom

**Expected behavior:**
Expected the Atom's window displayed.

**Actual behavior:**
Atom's window don't displays.

To get the window back, I click on top-left of desktop (bellow "Application menu") and drag to some direction to unmaximize the window.

### Versions
**Atom version**
```
Atom    : 1.35.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**OS version**
```
Distributor ID:	elementary
Description:	elementary OS 5.0 Juno
Release:	5.0
Codename:	juno
Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### Additional Information
**My partial solucion**
To prevent maximized window during Atom loading, I put this snippet of code in `init.coffee`  file:
```coffeescript
if atom.applicationDelegate.isWindowMaximized()
    atom.applicationDelegate.unmaximizeWindow();
```
Sorry for my bad english.

**Comment by rsese** [comment]
Thanks for the report!  I'm unable to reproduce with 1.35.1 on Ubuntu 18.04 - it looks like the `Prerequisites` section has been removed, I'm guessing this reproduced in safe mode?

Also, I haven't used Elementary OS, can you confirm how you install Atom on Elementary?

**Comment by edwino-stein** [comment]
Thanks for your response. I tested in safe mode and normal mode, and both taken the same behavior. Also I tested the others instructions describled in [Debugging](https://flight-manual.atom.io/hacking-atom/sections/debugging/#platform-linux) page.

Also tested in two computers with diferentes GPUs, my desktop with Geforce GTX 770 (with nvidia-driver-340) and my latoptop with Intel integreded graphcs (Atom Processor Z36xxx/Z37xxx Series Graphics & Display).

About the installation method, i used the `.deb package` and `apt` installation methods for Ubuntu describled in [Installing Atom](https://flight-manual.atom.io/getting-started/sections/installing-atom/#debian-and-ubuntu-debapt) page.

**Comment by rsese** [comment]
Hmm, not sure if this is specific to Elementary in some way?

What window manager are you using?

**Comment by iDaviddd** [comment]
I have the same issue

**Comment by iDaviddd** [comment]
I found a solution! Press the windows key and arrow up together when you have opened Atom: `win + arrow up`

**Comment by edwino-stein** [comment]
> Hmm, not sure if this is specific to Elementary in some way?

Yes, I think it's a bug only in Elementary OS. Before I ran the Atom with Ubuntu 16.04 with Unity normally.

> What window manager are you using?

I think Elementary OS uses [Gala](https://github.com/elementary/gala) as the window manager.

But other applications that use Electron like [vscode](https://github.com/Microsoft/vscode) do not have this behavior in Elementary OS.



> I found a solution! Press the windows key and arrow up together when you have opened Atom: `win + arrow up`

Thanks for alternative solution. You tryed my solution?

**Comment by iDaviddd** [comment]
> 
> Thanks for alternative solution. You tryed my solution?
Yes, I did just like you did and it seems specific to Elementary.

**Comment by juarezfranco** [comment]
same problem here, thanks for alternative solution @edwino-stein
