### ISSUE TITLE
Flaky build: Windows builds failing even when all tests are passing

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#19089]
Sometimes Windows build end up failing with the following error even after all the tests succeeded:

```
...
##[error]Cmd.exe exited with code '1'.
##[section]Finishing: Run tests
```

Rebuilding can sometimes resolve the failure.

---

**Affected CI provider(s)**: Azure DevOps

**Affected platform(s)**: Windows x86, Windows x64

**Example commit experiencing flakiness**: https://github.com/atom/atom/commit/aca476c48ac241092e2c5970e52eadd37328f30d

**Example failing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=36073&view=logs&jobId=97a617bf-bcbd-5dfa-bba2-cfba2747b693&taskId=1e1369e9-1c56-59b0-830c-f1606a680c8a&lineStart=14&lineEnd=30&colStart=1&colEnd=1

**Example passing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=36136

**Example log from failing build**: https://github.com/atom/atom/files/3034360/build.log

**Comment by jasonrudolph** [comment]
A few more occurrences:

- https://github.visualstudio.com/Atom/_build/results?buildId=35799&view=logs
- https://github.visualstudio.com/Atom/_build/results?buildId=36208&view=logs
- https://github.visualstudio.com/Atom/_build/results?buildId=36846&view=logs

**Comment by jasonrudolph** [comment]
Another one:

- https://github.visualstudio.com/Atom/_build/results?buildId=33073

**Comment by jasonrudolph** [comment]
Another one:

- https://ci.appveyor.com/project/Atom/atom/builds/23463872/job/7pg68dkgeo6ehfb2?fullLog=true#L70

    ```
    Executing core main process tests
      . AtomApplication waits until all the windows have saved their state before quitting: 14168ms
        AtomApplication prevents quitting if user cancels when prompted to save an item: Object has been destroyed
    Error: Object has been destroyed
        at WebContents.send (C:\projects\atom\out\Atom Dev x64\resources\electron.asar\browser\api\web-contents.js:101:15)
        at EventEmitter.exports.on (C:\projects\atom\src\ipc-helpers.js:41:18)
        at <anonymous>:null:null
      . AtomApplication prevents quitting if user cancels when prompted to save an item: 7995ms
    ...
    ```

**Comment by jasonrudolph** [comment]
Another one:

- https://github.visualstudio.com/Atom/_build/results?buildId=36605&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=bde16fc7-7659-5b1c-12aa-0110866d993c&lineStart=24&lineEnd=29&colStart=1&colEnd=1

**Comment by jasonrudolph** [comment]
One more:

- https://github.visualstudio.com/Atom/_build/results?buildId=37057&view=logs&jobId=4fbced83-508e-5fe0-c978-5c71ec0fc506&taskId=ee27e2dd-d235-5e40-8292-5f5961d971ba&lineStart=18&lineEnd=19&colStart=1&colEnd=1

**Comment by rafeca** [comment]
After some investigation, the `Error: Object has been destroyed` trace is not causing builds to fail: this is also printed on builds that pass ([example](https://github.visualstudio.com/Atom/_build/results?buildId=37491&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=8b9bff53-2841-58c7-68fc-e30c30330fc3&lineStart=35&lineEnd=38&colStart=1&colEnd=29)).

Some of the builds linked in this PR failed because of https://github.com/atom/atom/issues/18993 and some other seemed to fail because the exit code of the main process tests is 1 even after all the tests passed.

I'm gonna rename and edit slightly this issue to focus it on the exit code problem.

**Comment by rafeca** [comment]
Based on the logs, it looks like the tests fail somehow when an exit code from any of the test steps is not 0 ([source](https://github.com/atom/atom/blob/master/script/test#L228-L229)).

It's possible that #19124 fixed this issue (I haven't seen another failure in the last few days), but anyways I'm gonna change a bit the test logic to be able to print additional debug information when the condition mentioned above happens.

**Comment by rafeca** [comment]
I haven't seen any CI failure related to this issue after #19124 was merged which was 9 days ago, so I'm going to close this issue. If we see this failure again in the future we can just reopen.
