### ISSUE TITLE
Uncaught The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Prince-Mandor** [atom/atom#19081]
[Enter steps to reproduce:]

1. open a really big project with .gitignored 'build' directory 
2. make project from other console, so contents of this build directory start to change very quickly (downloading and unpacking linux kernel, for example)

sometimes everything works fine, sometime atom just hangs and asks to be restarted.
This is first time I see it actually crash with some 'callstack info' in such situation

**Atom**: 1.35.1 x64
**Electron**: 3.1.6
**OS**: linux 5.0.4-arch1-1-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1157:7)
    at onEvents.events.map.event (/usr/lib/atom/src/path-watcher.js:274:34)
    at Array.map (<anonymous>)
    at handler (/usr/lib/atom/src/path-watcher.js:267:28)
```

### Commands

```
     -7:19.7.0 intentions:highlight (input.hidden-input)
     -7:19.3.0 core:copy (input.hidden-input)
 15x -7:18.8.0 core:move-right (input.hidden-input)
     -7:17.5.0 core:move-left (input.hidden-input)
  2x -7:17 core:select-right (input.hidden-input)
     -7:16.1.0 core:paste (input.hidden-input)
     -7:14.6.0 intentions:highlight (input.hidden-input)
     -7:14 core:save (input.hidden-input)
     -7:09.0 tree-view:move (li.file.entry.list-item.status-added.selected)
     -7:05.9.0 core:move-left (input.hidden-input)
     -7:03.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
  3x -7:03.0 core:backspace (input.hidden-input)
     -6:51.5.0 core:confirm (input.hidden-input)
     -3:18.8.0 core:delete (input.hidden-input)
     -3:16.1.0 intentions:highlight (input.hidden-input)
     -3:16 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-search-everywhere 1.1.0 
better-git-blame 0.4.7 
build-tools 4.5.12 
build-tools-make 0.2.1 
busy-signal 2.0.1 
buttons 0.0.0 
console-log 1.10.0 
dbg 1.6.3 
dbg-arm-none-eabi-gdb 0.1.5 
dbg-gdb 1.7.8 
dbg-gdb-custom-server 0.3.0 
editorconfig 2.3.0 
git-plus 8.6.2 
intentions 1.1.5 
language-dts 0.3.1 
language-lua 0.9.11 
language-patch 1.2.0 
linter 2.3.0 
linter-gcc2 0.8.7 
linter-json-lint 0.1.3 
linter-lua 2.0.0 
linter-markdown 5.2.6 
linter-pylama 0.10.1 
linter-shellcheck 1.6.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
narrow 0.65.1 
narrow-git-ls 0.2.0 
open-terminal-here 2.3.2 
output-panel 0.3.4 
pigments 0.40.2 
process-palette 0.17.0 
run-in-terminal 1.0.1 
split-diff 1.6.0 
swd-debugger 0.1.1 
teletype 0.13.3 
```

**Comment by rsese** [comment]
Thanks for the report!

> **Atom**: 1.35.1 x64
> **Electron**: 3.1.6

Based on this version information, we can see that you're currently using an unofficial build or distribution of Atom (i.e. the current release version of Atom, 1.35.1, is on Electron 2.0.18). Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by rodrigo-klein** [comment]
just got this problem today..

[Enter steps to reproduce:]

1. dont know, just opened the project and got this message.. project folder is just 4mb (doesnt have git)

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: Atom Core


### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:434:7)
    at onEvents.e.map.e (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:24548)
    at Array.map (<anonymous>)
    at watcher.e (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:24400)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-autocomplete-php 0.25.6 
atom-beautify undefined 
autoclose-html 0.23.0 
autocomplete-paths 2.12.2 
busy-signal 2.0.1 
goto-definition 1.3.4 
highlight-selected 0.16.0 
hyperclick 0.1.5 
ide-php 0.7.18 
intentions 1.1.5 
local-history 4.3.1 
minimap 4.29.9 
open-recent 5.0.0 
php-cs-fixer 4.1.1 
php-hyperclick 1.2.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
remote-sync 4.1.8 
scroll-color 0.3.0 
```

my config:
"*":
  core:
    telemetryConsent: "no"
    uriHandlerRegistration: "always"
  editor:
    showInvisibles: true
  "exception-reporting":
    userId: "9185a407-1977-41e5-afc4-041e295be067"
  "ide-php":
    memoryLimit: "1G"
    phpPath: "C:/php/php.exe"
  welcome:
    showOnStartup: false
"linter-php":
  executablePath: "C:/php/php.exe"

php is in system path variable, but it wasnt "installed" (its a portable version of php: php-7.3.9-Win32-VC15-x64.zip)

**Comment by rsese** [comment]
Can you reproduce in safe mode @rodrigo-klein?

**Comment by Jihoon** [comment]
Same here.

[Enter steps to reproduce:]

1. Open any code on Atom
2. Press ctrl-s to save it

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core


### Stack Trace

Uncaught The "path" argument must be of type string. Received type undefined

```
At path.js:39

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:434:7)
    at onEvents.e.map.e (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:24548)
    at Array.map (<anonymous>)
    at watcher.e (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:24400)
```

### Commands

```
     -1:06.5.0 core:backspace (input.hidden-input)
     -1:05.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
teletype 0.13.4 
```
