### ISSUE TITLE
Do Atom can link to custom mixin details ?

### ISSUE THREAD

**Issue by webmasterpf** [atom/atom#19098]
## Summary

Mixin details link to.

## Motivation

In purpose to switch from netbeans.

## Describe alternatives you've considered

As Netbeans does, do Atom can link to custom mixin details on click on it ? If yes, how to that (ctl + click don't) ?

Thanks

**Comment by rsese** [comment]
Thanks for the suggestion!

> Mixin details link to.

...

> As Netbeans does, do Atom can link to custom mixin details on click on it ? If yes, how to that (ctl + click don't) ?

Can you share more details about what you're describing?  Is there a documentation link for this functionality in Netbeans that you can share?

**Comment by webmasterpf** [comment]
Perhaps can you find info in these links ? 
http://wiki.netbeans.org/SourceMapsExampleSASS
http://plugins.netbeans.org/plugin/34929/scss-support

**Comment by webmasterpf** [comment]
Hi,
There are some news on this ? I saw VS Code can display the mixin details in popup bubble. It's another way to do.
