### ISSUE TITLE
"Fetching outdated packages and themes failed" console error when starting Atom

### ISSUE THREAD

**Issue by linjialiang** [atom/atom#19097]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

![图片](https://user-images.githubusercontent.com/8848263/55445846-cc9e9380-55ef-11e9-88f6-6f8b9bb143cb.png)

### Steps to Reproduce

> Open atom and it appears

**Expected behavior:** [What you expect to happen]

> Don't complain

**Actual behavior:** [What actually happens]

> The console reported an error

**Reproduces how often:** [What percentage of the time does it reproduce?]

> 100% 
> - Even though I used `atom --safe`

### Versions

![图片](https://user-images.githubusercontent.com/8848263/55445929-3028c100-55f0-11e9-84c5-eec06f64688a.png)

### Additional Information

```shell
├── atom-beautify@0.33.4
├── atom-ide-datatip@0.9.4
├── atom-ide-definitions@0.2.0
├── atom-ide-markdown-service@1.1.1
├── atom-ide-signature-help@0.4.5
├── atom-material-syntax@1.0.8
├── atom-ternjs@0.19.1
├── autoprefixer@3.7.1
├── busy-signal@2.0.1
├── color-picker@2.3.0
├── docblockr@0.13.7
├── emmet@2.4.3
├── ex-mode@0.18.0
├── file-header@1.13.9
├── file-icons@2.1.31
├── git-time-machine@2.1.0
├── highlight-selected@0.16.0
├── ide-php@0.7.18
├── intentions@1.1.5
├── language-apache@1.8.0
├── language-ini@1.20.0
├── language-nginx@0.8.0
├── linter@2.3.0
├── linter-jshint@3.1.15
├── linter-ui-default@1.7.1
├── markdown-preview-enhanced@0.15.10 (disabled)
├── merge-conflicts@1.4.5
├── minimap@4.29.9
├── minimap-bookmarks@0.4.2
├── minimap-cursorline@0.2.0
├── minimap-git-diff@4.3.1
├── minimap-linter@2.2.1
├── minimap-quick-highlight@1.0.1
├── minimap-selection@4.5.0
├── minimap-split-diff@0.3.7
├── open-in-browser@0.5.2
├── pigments@0.40.2
├── platformio-ide-terminal@2.9.1
├── project-manager@3.3.6
├── quick-highlight@0.13.0
├── relative-numbers@0.9.0
├── remote-ftp@2.2.2
├── split-diff@1.6.0
├── sync-settings@0.8.6
├── todo-show@2.3.2
├── tree-view-git-status@1.5.2
└── vim-mode-plus@1.36.0
```

**Comment by rsese** [comment]
Thanks for the report - just to clarify, are you seeing any problem using Atom (can you check for package updates in `Settings > Updates`) or are you just seeing the console error?

Also, is this error new for you recently?

**Comment by linjialiang** [comment]
> Sometimes it comes up, sometimes it doesn't

**Comment by olsonpm** [comment]
This is likely a bug in `apm`.

I had a dependency which lacked a master branch and that was tripping up apm.  This must have been from a recent change in apm because I'm on arch linux and update my dependencies pretty frequently.

Anyhoo the short term solution was for me to push a master branch to the dependency - it was a package I made for personal use, so this was a reasonable solution.

I still don't like that software often depends on the master branch existing because it's such a weird branch name - this isn't the first time I've come across such a bug.

**Comment by rsese** [comment]
> Sometimes it comes up, sometimes it doesn't

@linjialiang I remember from another issue that you connect through a VPN?  Since this happens sometimes and isn't generally reproducible, it seems like thee issue could be related to how you connect to the internet.  Are you able to try a different network connection?

**Comment by 50Wliu** [comment]
We really need better diagnostic information for this error message.

**Comment by linjialiang** [comment]
@rsese 
> It seems that you have not encountered this problem, that should be my side of the problem, I am win10

**Comment by linjialiang** [comment]
@rsese 
> The problem is that our network does not support the installation of atom plug-in. We have to use VPN. This will happen when I turn off the VPN interface

`~/.atom/.prmrc`

```conf
strict-ssl = false
http-proxy = http://127.0.0.1:1080
https-proxy = https://127.0.0.1:1080
```

**Comment by VictorSago** [comment]
I have the same issue on Debian. And it doesn't matter whether I start Atom from the console or from the start menu -- it still displays "Fetching outdated packages and themes failed" when I open settings and try to see if there are any updates to the installed packages. Even if I run in safe mode, it still cannot fetch outdated package information.

And I don't connect through a VPN or a proxy.

### System:
```
$ uname -srvmo
Linux 5.18.0-0.bpo.1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1~bpo11+1 (2022-06-14) x86_64 GNU/Linux
```

### OS:
```
$ lsb_release -idrc
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

### Atom version:
```
$ atom --version
Atom    : 1.60.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
```
### apm version:
```
$ apm --version
apm  2.6.2
npm  6.14.13
node 12.14.1 x64
atom 1.60.0
python 3.9.2
git 2.34.1
```
### Additional installed packages:
```
$ apm ls
Built-in Atom Packages (93)
├── atom-dark-syntax@0.29.1
├── atom-dark-ui@0.53.3
├── atom-light-syntax@0.29.1
├── atom-light-ui@0.46.3
├── base16-tomorrow-dark-theme@1.6.0
├── base16-tomorrow-light-theme@1.6.0
├── one-dark-ui@1.12.5
├── one-light-ui@1.12.5
├── one-dark-syntax@1.8.4
├── one-light-syntax@1.8.4
├── solarized-dark-syntax@1.3.0
├── solarized-light-syntax@1.3.0
├── about@1.9.1
├── archive-view@0.66.0
├── autocomplete-atom-api@0.10.7
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.8
├── autocomplete-plus@2.42.4
├── autocomplete-snippets@1.12.1
├── autoflow@0.29.4
├── autosave@0.24.6
├── background-tips@0.28.0
├── bookmarks@0.46.0
├── bracket-matcher@0.92.0
├── command-palette@0.43.5
├── dalek@0.2.2
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.9
├── exception-reporting@0.43.1
├── find-and-replace@0.219.8
├── fuzzy-finder@1.14.3
├── github@0.36.9
├── git-diff@1.3.9
├── go-to-line@0.33.0
├── grammar-selector@0.50.1
├── image-view@0.64.0
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.39.1
├── line-ending-selector@0.7.7
├── link@0.31.6
├── markdown-preview@0.160.2
├── metrics@1.8.1
├── notifications@0.72.1
├── open-on-github@1.3.2
├── package-generator@1.3.0
├── settings-view@0.261.8
├── snippets@1.5.1
├── spell-check@0.77.1
├── status-bar@1.8.17
├── styleguide@0.49.12
├── symbols-view@0.118.4
├── tabs@0.110.2
├── timecop@0.36.2
├── tree-view@0.229.1
├── update-package-dependencies@0.13.1
├── welcome@0.36.9
├── whitespace@0.37.8
├── wrap-guide@0.41.0
├── language-c@0.60.19
├── language-clojure@0.22.8
├── language-coffee-script@0.50.0
├── language-csharp@1.1.0 (disabled)
├── language-css@0.45.1
├── language-gfm@0.90.8
├── language-git@0.19.1
├── language-go@0.47.2
├── language-html@0.53.1
├── language-hyperlink@0.17.1
├── language-java@0.32.1
├── language-javascript@0.134.1
├── language-json@1.0.5
├── language-less@0.34.3
├── language-make@0.23.0
├── language-mustache@0.14.5
├── language-objective-c@0.16.0
├── language-perl@0.38.1
├── language-php@0.47.0
├── language-property-list@0.9.1
├── language-python@0.53.6
├── language-ruby@0.72.23 (disabled)
├── language-ruby-on-rails@0.25.3 (disabled)
├── language-rust-bundled@0.1.0
├── language-sass@0.62.1
├── language-shellscript@0.28.2
├── language-source@0.9.0
├── language-sql@0.25.10
├── language-text@0.7.4
├── language-todo@0.29.4
├── language-toml@0.20.0
├── language-typescript@0.6.3
├── language-xml@0.35.3
└── language-yaml@0.32.0

Community Packages (47) /home/<--->/.atom/packages
├── Sublime-Style-Column-Selection@1.7.5
├── an-old-hope-syntax@1.0.4
├── atom-beautify@0.33.4
├── atom-html-preview@0.2.7
├── atom-live-server@2.3.0
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── atom-monokai@0.10.9
├── atom-ternjs@0.20.0
├── autoclose-html@0.23.0
├── base16-syntax@1.8.1
├── busy-signal@2.0.1
├── csslint@1.2.0
├── dash-syntax@0.4.2
├── dash-ui@0.4.4
├── dracula-ui@0.6.0
├── emmet@2.4.3
├── firewatch-syntax@1.1.1
├── git-plus@8.7.1
├── gitlab@0.1.3-7
├── highlight-selected@0.17.0
├── hyperclick@0.1.5
├── ide-csharp@0.6.2
├── intentions@2.1.1
├── isotope-ui@2.8.5
├── language-ejs@0.4.0
├── language-sln@0.1.0
├── linter@3.4.0
├── linter-csslint@2.0.6
├── linter-erlang@0.4.0
├── linter-eslint@9.0.1
├── linter-htmlhint@1.6.3
├── linter-ui-default@3.4.1
├── monokai@0.28.0
├── monokai-seti@0.9.0
├── native-ui@0.27.0
├── omnisharp-atom@0.31.2
├── open-in-browsers@0.0.30
├── open-recent@5.0.0
├── pigments@0.40.6
├── script@3.32.2
├── seti-syntax@1.2.0
├── seti-ui@1.11.0
├── styri-syntax@1.0.0
├── todo-show@2.3.2
├── tree-view-git-status@1.5.3
└── unity-ui@2.1.11
```

**Comment by NJT145** [comment]
> @rsese
> 
> > The problem is that our network does not support the installation of atom plug-in. We have to use VPN. This will happen when I turn off the VPN interface
> 
> `~/.atom/.aprmrc`
> 
> ```
> strict-ssl = false
> http-proxy = http://127.0.0.1:1080
> https-proxy = https://127.0.0.1:1080
> ```

I got the same error and I don't use any vpn. however, when I open any package's page from https://atom.io/packages with its direct link, sometimes website gives error. I think your api just break connection at first error or something else... so, that more than a vpn issue.
