### ISSUE TITLE
Open Folder causes a crash (Linux Fedora)

### ISSUE THREAD

**Issue by damiantoczek** [atom/atom#19113]
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom is crashing when "Open Folder" is selected.

### Steps to Reproduce

1. Open Atom
2. Hover on File
3. Click "Open Folder..." (It also crashes when using the shortcut)

**Expected behavior:** I expect a window where I'm able to select my folder I want to open.

**Actual behavior:** Atom closes itself (crashes?), no errors are shown.

**Reproduces how often:** 100%

### Versions
 atom --version doesn't output anything for me.
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.35.1
python 
git 2.19.1

Fedora 29, Gnome 3.30.1, 64-Bit

### Additional Information

I installed Atom using "snap install atom --classic".

**Comment by rsese** [comment]
Thanks for the report!

> I installed Atom using "snap install atom --classic".

The Snap install is unofficial and not supported by us - I'd suggest uninstalling that version of Atom and trying one of the official installation methods:

https://flight-manual.atom.io/getting-started/sections/installing-atom/

Then if you still have trouble, go ahead and open another issue and we can take a look.
