### ISSUE TITLE
Bash: atom: command not found

### ISSUE THREAD

**Issue by Ludrique** [atom/atom#19117]
Hello, i cloned a repository from GitHub and created a new file using git but when I try to open the file in atom I get an error message: "bash: atom: command not found"

**Comment by rsese** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

Without the template information I don't know what operating system you're running but if you're on [macOS](https://flight-manual.atom.io/getting-started/sections/installing-atom/#installing-atom-on-mac), did you already run `Atom > Install Shell Commands` from the menu?

**Comment by Ludrique** [comment]
Hello Robert, thanks for getting back to me... I'm using Windows 10 and I
solved the problem using alias atom=PATH but I ran into another problem...
I created an html file using atom and I'm having difficulties accessing it
on the web using open <filename.html>... I get an error message 'bash:
open: command not found'

**Comment by rsese** [comment]
It sounds like you're using Git for Windows?  If so, can you share the output of `ls ~/AppData/Local/atom/bin`?

**Comment by Ludrique** [comment]
Hello Robert... The output of the code "ls ~/AppData/Local/atom/bin" is
"apm* apm.cmd atom* atom.cmd" . Both atom* and apm* are coloured green

**Comment by rsese** [comment]
Thanks - is that directory listed in your `PATH` when you run `echo $PATH` in Git for Windows?

**Comment by Ludrique** [comment]
It's not exactly the same... here is the output :
c/Users/Ludrick/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/Ludrick/bin:/c/Program
Files (x86)/Intel/TXE
Components/TCS:/c/Users/Ludrick/AppData/Local/Programs/Python/Python37":/c/Program
Files/Intel/TXE
Components/TCS:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program
Files/Intel/TXE Components/DAL:/c/Program Files (x86)/Intel/TXE
Components/DAL:/c/Program Files/Intel/TXE Components/IPT:/c/Program Files
(x86)/Intel/TXE
Components/IPT:/c/Users/Ludrick/AppData/Local/Programs/Python/Python37:/c/Users/Ludrick/AppData/Local/Programs/Python/Python37/Scripts:/c/WINDOWS/System32/OpenSSH:/cmd:/c/Users/Ludrick/AppData/Local/Microsoft/WindowsApps:/usr/bin/vendor_perl:/usr/bin/core_perl

**Comment by rsese** [comment]
Ok thanks - go ahead and remove the alias you created and then add that directory to your `PATH` environment variable:

1. Click Start Menu and search for `Environment Variable`
2. Select `Edit the system environment variables`
3. Click the `Environment Variables` button
4. Select `Path` under `User variables for...` and click `Edit...`
5. Click `New` and add `C:\Users\Ludrick\AppData\Local\atom\bin`
6. Click `Ok` to close out the open popups

Then open a new Git for Windows window and try to start Atom.

**Comment by Ludrique** [comment]
Hello Robert... I removed the alias and added a new path but when I try to
open atom from Git I get an error message bash: C:
UsersLudrickAppDataLocalatomatom.exe: command not found.
Thanks

**Comment by rsese** [comment]
What does your `PATH` look like now (`echo $PATH`)?  And also what's the output of `which atom`?

**Comment by Ludrique** [comment]
The output for echo $PATH hasn't changed

**Comment by rsese** [comment]
Hmm, the path should be different after updating the environment variable - did you open a new Git for Windows window?
