### ISSUE TITLE
"Open file..." opens a new window

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19133]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On Windows, when opening a file using the "Open file..." item from the app menu, the file gets opened in a new Atom window instead of reusing the existing window.

### Steps to Reproduce

1. Open Atom.
2. Go to "File" -> "Open file..." and open a random file.

**Expected behavior:** The file should get opened in the same Atom window.

**Actual behavior:** a new Atom window gets opened.

**Reproduces how often:** Always.

### Versions

This started failing on the 1.36 branch.

### Additional Information

N/A

**Comment by vlad1777d** [comment]
Same thing for mac and linux, for the same Atom version.
