### ISSUE TITLE
Uncaught Error: ::set with a 'source' and no 'sourceSelector' is not yet implemented!

### ISSUE THREAD

**Issue by styx** [atom/atom#19144]
[Enter steps to reproduce:]

1. On Atom start

**Atom**: 1.37.0-beta0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ::set with a 'source' and no 'sourceSelector' is not yet implemented!

```
At /Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11

Error: ::set with a 'source' and no 'sourceSelector' is not yet implemented!
    at Config.set (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:330629)
    at SettingsFile.activate (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:6114)
    at SettingsFile.load (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:3425225)
    at l.readFile (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:5992)
    at /Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:581165
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-change-case-menu 0.2.0 
atom-jest-snippets 2.1.0 
atom-lcov 2.0.0 
autoclose-html 0.23.0 
build 0.70.0 
busy 0.7.0 
busy-signal 2.0.1 
clipboard-plus 0.5.1 
cucumber-step 0.2.0 
cursor-history 0.13.2 
double-tag 1.7.0 
editorconfig 2.4.0 
egghead-react-snippets 1.2.2 
erb-snippets 1.1.0 
es6-javascript 1.0.0 
ex-mode 0.18.0 
expand-region 0.4.2 
file-icons 2.1.31 
git-blame 1.8.0 
git-plus 8.6.2 
go-debug 1.6.2 
go-expanderr 0.1.1 
go-find-references 1.2.3 
go-imports 0.2.0 
go-plus 6.1.0 
go-quick-import 0.3.1 
go-rename 0.3.0 
go-signature-statusbar 1.2.3 
haskell-grammar 0.4.0 
highlight-selected 0.16.0 
hyperclick 0.1.5 
intentions 1.1.5 
jump-to-import 3.6.5 
jumpy 5.0.2 
language-actionscript 0.2.0 
language-arduino 0.4.3 
language-babel 2.85.0 
language-docker 1.1.8 
language-elixir 0.22.1 
language-gherkin 1.0.4 
language-haml 0.32.1 
language-nginx 0.8.0 
language-ocaml 1.9.5 
language-powershell 5.0.0 
language-thrift 1.0.2 
language-x86asm 0.9.0 
last-cursor-position 0.9.3 
line-ending-converter 1.3.2 
linter 2.3.0 
linter-csslint 2.0.5 
linter-docker 0.3.2 
linter-eslint 8.5.3 
linter-flow 5.6.1 
linter-golinter 1.3.0 
linter-gotype 1.0.0 
linter-govet 1.0.0 
linter-ruby 1.3.0 
linter-ui-default 1.7.1 
nuclide 0.366.0 
open-git-modified-files 0.2.4 
open-this 0.5.0 
pigments 0.40.2 
prettier-atom 0.56.4 
pretty-json 2.1.1 
ruby-block-converter 4.1.1 
ruby-syntax-replacer 0.5.1 
teletype 0.13.3 
todo-show 2.3.2 
toggle-quotes 1.1.3 
vim-mode-clipboard-plus 0.3.0 
vim-mode-plus 1.36.0 
vim-mode-plus-move-selected-text 0.12.0 
you-complete-me 0.8.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if the error is reproducible and if so, can you reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by styx** [comment]
@rsese works well in safe mode. I think problem is with `expand-region` plugin, as it stopped working in beta.

**Comment by rsese** [comment]
Ahhh ok :+1:

It may be that there is still a bug in Atom but if so, we'll need the maintainer of https://atom.io/packages/expand-region to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).

**Comment by caleb531** [comment]
@rsese I believe this error was caused by https://github.com/atom/atom/pull/19054, which was released publicly with Atom v1.37.0. The settings file for expand-region (`settings/expand-region.cson`) contains a settings group scoped by `'*'`:

```cson
'*':
  'expand-region':
    commands: [
      {
        command: 'editor:select-word'
        recursive: false
      }
      # ...
```

Any suggestions for how to handle this? Is there a different (better) way to structure/store the expand-region settings?

**Comment by rsese** [comment]
> @rsese I believe this error was caused by #19054,

I see that the error for atom-expand-region was [resolved on the package side](https://github.com/aki77/atom-expand-region/issues/37#issuecomment-492492651) - just to confirm, do you think there's still an issue on the Atom side because of #19054?

**Comment by caleb531** [comment]
@rsese I don't believe so. I upgraded expand-region to the newly-released v0.5.0 and can confirm the package is working again without error. It seems it was just a matter of following proper convention for defining package settings, not anything mis-implemented in core Atom.

**Comment by seeker105** [comment]
I don't have expand-region installed, but I'm getting this issue on atom start.

**Comment by rsese** [comment]
Have you confirmed whether this is related to a community package by starting in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) @seeker105?

**Comment by lukasoppermann** [comment]
Hey, can someone let me know what the fix for this is? According to the docs the '*' is how on is supposed to set up global settings: https://flight-manual.atom.io/using-atom/sections/basic-customization/#global-configuration-settings

What would I have to change in my language.cson file?

```cson
"*":
  core:
    customFileTypes:
      "source.mplus": [
         "inp",
         "out"
      ]
```

**Comment by Arcanemagus** [comment]
You'll need to determine which package you have installed that is triggering this error. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it.

**Comment by lukasoppermann** [comment]
I am pretty much sure it is my package https://github.com/lukasoppermann/mplus. When I install it (I don't use it, wrote it for my wife) I get the error. Also as mentioned above I am using the `'*'`selector in the settings, but I am not sure how to NOT do that with the same result.
