### ISSUE TITLE
`File > Reopen Project` adds the project as a folder to the current window on Windows and Linux, doesn't work on macOS

### ISSUE THREAD

**Issue by CharlotteDunois** [atom/atom#19149]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When trying to re-open a project inside Atom with an already open project, then instead of opening a new window with the project, Atom will add the project as project folder to the current project instead (performs "Add Project Folder" instead).

### Steps to Reproduce

1. Open a project
2. File -> Reopen Project -> [Select a project]

**Expected behavior:** Atom opening a new window with the selected project.

**Actual behavior:** Atom adds the selected project as a project folder.

**Reproduces how often:** Always.

### Versions

Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0
python 3.6.0
git 2.14.1.windows.1
visual studio 2015

OS: Windows 7 Pro x64

*Edit by @rsese to add more version/behavior details*

`File > Reopen Project` on different OSs:

| Operating System     | 1.36.0     | 1.37.0-beta0     |
| :------------- | :------------- | :------------- |
| macOS 10.12.6   | Project Doesn't Reopen | New Window |
| Windows 10     |  Same Window  | Same Window |
| Ubuntu 18.04   |  Same Window  | Same Window |

### Additional Information

This started happening after ugrading to 1.36.0. This did not happen before.

**Comment by rsese** [comment]
Thanks for the report!  I can reproduce on Windows 10 with 1.36.0 but not on macOS 10.12.6.  I'm assuming this is related to the changes resulting in https://github.com/atom/atom/issues/19146 and https://github.com/atom/atom/issues/19147 but I'll keep this open separately for now.

**Comment by rsese** [comment]
It looks like I was running 1.37.0-beta0 on macOS 10.12.6 - on 1.36.0, `File > Reopen Project` doesn't seem to do anything (no errors and the project doesn't open in the current or new window).

Also checked Ubuntu 18.04 and it behaves like Windows with both 1.36.0 and 1.37.0-beta0 - `File > Reopen Project` will open the project in the same window rather than a new window.

**Comment by dimitrik-fr** [comment]
In my case just nothing happens on File-> Reopen Project -> Select Project..
just updated to 1.36.0 and this bug is really frustrating.. -- any way to get a quick fix / hack for this ?
otherwise, rollback to 1.35.x ?

**Comment by rsese** [comment]
Since I was trying to see what happens with `File > Reopen Project` on different OSs:

| Operating System     | 1.36.0     | 1.37.0-beta0     |
| :------------- | :------------- | :------------- |
| macOS 10.12.6   | Project Doesn't Reopen | New Window |
| Windows 10     |  Same Window  | Same Window |
| Ubuntu 18.04   |  Same Window  | Same Window |

**Comment by rsese** [comment]
@dimitrik-fr - sorry, there's no quick fix for macOS where `File > Reopen Project` doesn't do anything (it looks like you need to <kbd>cmd-o</kbd> and open the project directly).  So rolling back to 1.35.1 is an option, just make sure that you have `Settings > Core > Automatically Update` disabled or else you'll get updated back to 1.36.0.

Once we have more information we'll comment back in this (and the other) issues.

**Comment by dimitrik-fr** [comment]
I've tried also : open New Window, and then Reopen Project in this new window, and nothing happen either.. Also looks very strange for me you see different reactions on the same issue on different OS platforms -- wasn't any app in Electron expected to work the same way on any supported OS ?

**Comment by dimitrik-fr** [comment]
Ok, seems like workaround by opening Project directory directly via CMD+O is working at least, ouf ! I see there is a bug fix in 1.37 : https://github.com/atom/atom/pull/19058 -- hope it'll cover this issue as well ?

**Comment by rsese** [comment]
> I see there is a bug fix in 1.37 : #19058 -- hope it'll cover this issue as well ?

Hmm, not sure - that pull request was meant to fix a specific issue where `Reopen Project` didn't work if you had no windows open, so not exactly the same.  But as I noted in that table above, `Reopen Project` does work in 1.37.0-beta0 so perhaps that PR or some other change fixed it.

**Comment by christiaanwesterbeek** [comment]
> macOS 10.12.6 | Project Doesn't Reopen | New Window

I confirm this behavior. It started after upgrading to 1.36.0, before upgrading (I was on the latest before 1.36.0) reopening did work.

**Comment by thekodester** [comment]
I'm on macOS 10.14.4 and the 'Reopen Project' does nothing. See https://youtu.be/1oripT7WyRk.

**Comment by dimitrik-fr** [comment]
yes, so until the next release is delivered, use CMD+O workaround (see above)..

**Comment by smashwilson** [comment]
Atom 1.36.1 and 1.37.0-beta1 have been released and include a fix for this issue. Thanks for your patience :bowing_man: :rocket:
