### ISSUE TITLE
Re-open Atom File Not Exists (but actually exists) & can't Reopen Project

### ISSUE THREAD

**Issue by ditatompel** [atom/atom#19146]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom won't show previously unclosed file when reopen Atom. It says _unable to open project folder_ (even though the actual file is exists)
This is not happen when previous unclosed thing is project folder. Looks like Atom treat file as a folder, not as a single file.
Also, can't "Reopen Project" from Atom Menus > File > Reopen Project. (Nothing happen)

![Screen Shot 2019-04-12 at 17 25 54](https://user-images.githubusercontent.com/1184957/56033289-75669480-5d4e-11e9-802c-efce50b2f14f.png)

### Steps to Reproduce

1. Open a file to Atom
2. Quit atom without closing opened file
3. Re-open Atom
4. Previous opened file doesn't appear (it say **directory** not found)

**Expected behavior:**
Previous opened file should be appear.
Reopen Project should be working.

**Actual behavior:**
Atom show warning message.
Reopen Project feature from Atom Menus should be working.

**Reproduces how often:** 
Everytime

### Versions
Atom Version
```
Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
apm Version
```
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0
python 2.7.10
git 2.21.0
```
OS MacOS Mojave 10.14.4 (18E226)

### Additional Information
This happen after updating to version 1.36.0.
Trying launch `atom --save` still produce the same problems.
Trying to reinstall, but still no luck.

**Comment by joshmaines** [comment]
There's a good chance this is causing files to open in new windows, too, right? Seems like a recent update screwed a few things up.

**Comment by smashwilson** [comment]
🤔 Looks like we're attempting to use a previously opened file as a root directory. Two questions:

1. How exactly did you open the file in Atom? Did you run `atom path/to/file` from the command line, or open Atom from the dock and open the file with <kbd>Ctrl-O</kbd>, or some other sequence of events?
2. Can you share the contents of the file `${ATOM_HOME}/.atom/application.json` between steps 2 and 3?

> There's a good chance this is causing files to open in new windows, too, right? Seems like a recent update screwed a few things up.

I _think_ that's unrelated, other than both being consequences of touching some ancient `AtomApplication` code. Can you open a separate issue for that one and fill out the template? I'm especially interested in your OS and the exact steps that result in an unexpected new window. We caught [an issue that sounds very similar](https://github.com/atom/atom/pull/19136) to that just before release and while we tested it out on all three platforms it's quite likely that we missed an execution path somewhere. (Fun fact: different methods get called when if you use the <kbd>Ctrl-O</kbd> shortcut, `application:open-file` command from the command palette, or run "File -> Open File..." from the system menu 🙃 )

**Comment by ditatompel** [comment]
> 🤔 Looks like we're attempting to use a previously opened file as a root directory. Two questions:
> 
> 1. How exactly did you open the file in Atom? Did you run `atom path/to/file` from the command line, or open Atom from the dock and open the file with Ctrl-O, or some other sequence of events?

I've try these steps: 
1. Both method from CLI  `atom path/to/file.txt` or GUI (by opening Atom from dock or right click file > Open With > Atom) produce error warning when I reopen Atom.
2. Opening file with `Ctrl-O` or "File -> Open File..."  or `application:open-file` command from the command palette. I quit Atom and reopen again > Atom still looking for the previous file I open from CLI  `atom path/to/file.txt` or GUI (and say not found)
3. Reopen previous closed project from CLI / GUI work. But reopen another project from Atom Menu > File > Reopen Project doesn't work at all.  (The same issue with #19149)
![atom](https://user-images.githubusercontent.com/1184957/56068021-7d9eee00-5da7-11e9-96f2-fcbeb6479471.gif)

> 2. Can you share the contents of the file `${ATOM_HOME}/.atom/application.json` between steps 2 and 3?


No application.json under ~/.atom directory between step 2 and 3.
The strange thing is when I run : 
```bash
cat ${ATOM_HOME}/.atom/application.json
cat: /.atom/application.json: No such file or directory
```
when I do echo `${ATOM_HOME}` it's empty and it's like Atom act their home dir is root of my OS directory ( / ) instead of my home user directory. 
*Note : The output of echo ${ATOM_HOME} is same both on my zsh or bash shells.*

> 
> > There's a good chance this is causing files to open in new windows, too, right? Seems like a recent update screwed a few things up.
> 
> I _think_ that's unrelated, other than both being consequences of touching some ancient `AtomApplication` code. Can you open a separate issue for that one and fill out the template? I'm especially interested in your OS and the exact steps that result in an unexpected new window. We caught [an issue that sounds very similar](https://github.com/atom/atom/pull/19136) to that just before release and while we tested it out on all three platforms it's quite likely that we missed an execution path somewhere. (Fun fact: different methods get called when if you use the Ctrl-O shortcut, `application:open-file` command from the command palette, or run "File -> Open File..." from the system menu 🙃 )

Yes I've same issue about window behaviour like @joshmaines the others #19147

**Comment by smashwilson** [comment]
> No `application.json` under `~/.atom` directory between step 2 and 3.

Oh! Sorry, that was a mistype. It should be `${ATOM_HOME}/storage/application.json`, and `ATOM_HOME` defaults to `${HOME}/.atom` if unset. So the real path for you should be `${HOME}/.atom/storage/application.json`.

**Comment by rsese** [comment]
Using the repro steps in the issue body (for step (1) I opened a file from the command line with `atom README.md`), I was able to reproduce and I see the file I opened from the command line listed when I check my `application.json`:

```
cat ~/.atom/storage/application.json 
[{"initialPaths":["/Users/rsese/sandbox/test-open/README.md"]}]
```

This as after step (2) and it's the same if I close/restart Atom.

**Comment by ditatompel** [comment]
> > No `application.json` under `~/.atom` directory between step 2 and 3.
> 
> Oh! Sorry, that was a mistype. It should be `${ATOM_HOME}/storage/application.json`, and `ATOM_HOME` defaults to `${HOME}/.atom` if unset. So the real path for you should be `${HOME}/.atom/storage/application.json`.

Here is my ~/.atom/storage/application.json 
```
[{"initialPaths":["/Users/ditatompel/atom-test/another-file-1.txt"]}]
```

Figuring that my ${ATOM_HOME} is empty, I've try to set ATOM_HOME to ${HOME}/.atom and try the same procedure, but still throw the same warning message.

Note : Try to Downgrade to Atom 1.35.1 and everything works normal as expected.

**Comment by oriondollar** [comment]
I'd just like to chime and say I'm having the same issue with File > Reopen Project where nothing happens regardless of if I have an atom window open or not on MacOS High Sierra 10.13.6. Downgrading to v1.35.1 like ditatompel suggested works as a temporary fix.

**Comment by xinst** [comment]
I reinstalled the atom before search in the issues, now, it seems that is a bug. looking forward the patch

**Comment by seanodell** [comment]
Happening for me as well, except I can't even "Add Project Folder" for projects that are failing to reopen automatically or via menu.

**Comment by smashwilson** [comment]
Atom 1.36.1 and 1.37.0-beta1 have been released and include a fix for this issue. Thanks for your patience :bowing_man: :rocket:

**Comment by corinthian13** [comment]
That's bullshit.
I've had the same problem with 1.38.2 - basically, it never worked right on opening. Just a blank home window. Reopen Project didn't work either. And Reopen Last Item doesn't work.
Time someone hired an ex-Notepad++ coder - they've never had this stupid problem.

**Comment by lee-dohm** [comment]
@corinthian13 your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.
