### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by limweebeng** [atom/atom#19156]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At C:\Users\Annoymous\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11

TypeError: Cannot read property 'element' of undefined
    at TextEditorComponent.measureLongestLineWidth (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:104563)
    at TextEditorComponent.measureContentDuringUpdateSync (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:70559)
    at e.readDocument (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:67706)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:326811)
```

### Commands

```
     -6:33.3.0 core:paste (input.hidden-input)
     -6:13.2.0 atom-beautify:beautify-editor (input.hidden-input)
  2x -0:25.1.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
color-picker 2.3.0 
csscomb 0.3.1 
emmet 2.4.3 
file-type-icons 1.3.4 
html-outliner 0.1.1 
ocaml-indent 0.7.1 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by felipe-vicente** [comment]
Had the same problema. it started yesterday at night (when Atom probably updated after it was closed). Experiencing strange situations here. When I click a file from treeview, it pins the tab up there in the window. But it doesn't show the code. And I can't access de file unless I click the tab. If I have other files opened, I cant navigate to that new file. It's like it's not there. And when that happens, if I enter that file (by clicking the tab), it doesn't do things like "automatic brackets/parentesis". Using.

When I click a file in the treeview, console logs this:

```
Uncaught (in promise) Cannot get services before activation
Promise rejected (async)
t.exports.TreeView.fileViewEntryClicked @ VM22 <embedded>:14
t.exports.TreeView.entryClicked @ VM22 <embedded>:14
(anonymous) @ VM22 <embedded>:14
```

It does not happen in --safe mode
