### ISSUE TITLE
Support Semantic Highlighting on Tree-Sitter Grammars

### ISSUE THREAD

**Issue by sharedprophet** [atom/atom#19151]
## Summary

Please make token text available to Tree-Sitter grammars when requesting scope information, and possibly create a way to return different scopes for each lexical token.

## Motivation

The current implementation of [semanticolor](https://atom.io/packages/semanticolor) doesn't work with Tree-Sitter grammars. I'd like to be able to take advantage of Tree-Sitter, but this requires the grammar to be aware of the text a scope is being requested for, and to be able to return separate scopes for each lexical token in a scope.

## Describe alternatives you've considered

By changing `tree-sitter-language-mode.js` line 1060 from this:

```
return this.languageLayer.languageMode.grammar.idForScope(scopeName)
```

to this:

```
return this.languageLayer.languageMode.grammar.idForScope(scopeName, this.treeCursor.nodeText)
```

I was able to produce somewhat reasonable results, but this doesn't give me a way to assign different scopes to each lexical token, so the results aren't perfect:

![example](https://raw.githubusercontent.com/digitallyserviced/semanticolor/master/tree-sitter.png)

**Comment by maxbrunsfeld** [comment]
Thanks for experimenting and proposing that very concrete change; it makes clearer what your package needs.

The `.nodeText` accessor on the `TreeCursor` has some performance cost. It needs to read a string from the native text buffer, and for internal syntax nodes (like a function declaration) it may be a very big string. And that line of code executes *many* times per syntax-highlighted line. So I'd like to avoid that performance cost if possible.

Maybe we could set it up to *only* read the node text if it's on a certain type of node (e.g. an `identifier`)?

**Comment by sharedprophet** [comment]
That would be a good improvement on my suggestion, but my suggestion was not sufficient. Notice in my example image how some of the identifiers are still white, for example parameters. This is because the tree-sitter grammar is producing a single node for the entire parameter list, for example. Is there a way to get more discrete lexical tokens from it?

**Comment by maxbrunsfeld** [comment]
> This is because the tree-sitter grammar is producing a single node for the entire decomposed parameter list, for example.

No, the Tree-sitter grammar parses the list into individual tokens. I think it's just that plain `identifier` nodes aren't assigned a special scope in pthe JavaScript syntax highlighting config](https://github.com/atom/language-javascript/blob/master/grammars/tree-sitter-javascript.cson#L58).

**Comment by sharedprophet** [comment]
Hmm...

In that case, limiting the `.nodeText` fetch to `identifier` type nodes would only work on grammars that have a node type of `identifier`, and only fully work if they have a scope that applies to all identifiers. It's probably not feasible to attempt to enforce that...

**Comment by sharedprophet** [comment]
Would it be possible to only read the `.nodeText` for leaf nodes?

**Comment by sharedprophet** [comment]
How about this? This works: https://github.com/atom/atom/compare/master...sharedprophet:support-semanticolor

**Comment by sharedprophet** [comment]
@maxbrunsfeld please?

**Comment by ret394** [comment]
would've been faster if you had commit rights.

**Comment by lkashef** [comment]
Hey @sharedprophet, I didn't take a deep look into the suggested diff, however I want to understand if were able to verify that can help semanticolor run on tree-sitter grammar.

Also were you able to write tests for these changes?

**Comment by sharedprophet** [comment]
I was able to verify that this does allow `semanticolor` to function on tree-sitter grammars. I used this change for development locally for a couple months (until I had to get a replacement laptop) and didn't see it causing any issues. Not sure what tests I would write for it, though.

**Comment by lkashef** [comment]
That's great! to get this going I think it would make sense to a PR that closes this issue, we can make sure that the tests are passing and that the changes will integrate well with the current code base.

As for the tests, you can check the existing specs for [ tree-sitter-language-mode-spec](https://github.com/atom/atom/blob/master/spec/tree-sitter-language-mode-spec.js) and see if there are applicable tests to match the changes or inspire you for new tests.

**Comment by sharedprophet** [comment]
@lkashef test added.

**Comment by lkashef** [comment]
Hey @sharedprophet that's great, are you able to link the PR or open one if you didn't yet?

**Comment by sharedprophet** [comment]
It is linked above, but: #20212
