### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sendCrawlEvent' of undefined

### ISSUE THREAD

**Issue by Leushenko** [atom/atom#19163]
[Enter steps to reproduce:]

1. do anything
2. this issue will appear at random
3. no consistency at all in what I'm doing in Atom in terms of getting this to appear, it's just constantly coming up every minute or two, sometimes in bursts, sometimes when Atom is out of focus

**Atom**: 1.37.0-beta0 x64
**Electron**: 2.0.18
**OS**: Debian GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'sendCrawlEvent' of undefined

```
At /usr/share/atom-beta/resources/app/static/<embedded>:11

TypeError: Cannot read property 'sendCrawlEvent' of undefined
    at Task.p.once [as callback] (/usr/share/atom-beta/resources/app/static/<embedded>:11:809462)
    at /usr/share/atom-beta/resources/app/static/<embedded>:14:36910
    at /usr/share/atom-beta/resources/app/static/<embedded>:14:38272
    at Function.simpleDispatch (/usr/share/atom-beta/resources/app/static/<embedded>:11:1191973)
    at Emitter.emit (/usr/share/atom-beta/resources/app/static/<embedded>:11:1193414)
    at ChildProcess.<anonymous> (/usr/share/atom-beta/resources/app/static/<embedded>:14:37385)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -2:27 core:save (input.hidden-input)
     -2:23.1.0 core:save-as (input.hidden-input)
     -2:06.7.0 core:save (input.hidden-input)
     -0:54.7.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:54 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -0:49.4.0 editor:newline (input.hidden-input)
     -0:38.3.0 editor:move-to-beginning-of-word (input.hidden-input)
  3x -0:38 core:move-right (input.hidden-input)
     -0:37.4.0 core:delete (input.hidden-input)
     -0:37.2.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -0:16.1.0 core:backspace (input.hidden-input)
  2x -0:13.5.0 editor:delete-to-beginning-of-word (input.hidden-input)
  2x -0:09.7.0 core:backspace (input.hidden-input)
     -0:06.7.0 editor:consolidate-selections (input.hidden-input)
     -0:06.7.0 core:cancel (input.hidden-input)
     -0:06.5.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
auto-soft-wrap 0.3.1 
autocomplete-clang 0.11.5 
build 0.70.0 
busy 0.7.0 
busy-signal 2.0.1 
case-switch 2.2.4 
cpp-refactor 2.2.3 
fonts-cjk 2.1.1 
gpp-compiler 3.0.7 
language-awk 0.1.12 
language-cpp14 0.6.2 
language-scheme 1.4.0 
language-webassembly 1.0.1 
revert-buffer 0.6.0 
simple-align 0.2.0 
single-click-open 0.2.2 
Sublime-Style-Column-Selection 1.7.5 
switch-header-source 0.33.0 
wordcount 3.0.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by Leushenko** [comment]
Following the directions on that page, it appears to go away when I disable the [switch-headers-source](https://github.com/dschwen/switch-header-source) package.

**Comment by robobenklein** [comment]
Confirmed that this seems to be a bug(?) in the switch-headers-source package:

https://github.com/dschwen/switch-header-source/blob/master/lib/switch-header-source.coffee#L124-L135

because pathloader startTask now requires the metricsReporter from fuzzy finder as well,

ran into this on my own plugin, so might make a PR to that one

**Comment by 50Wliu** [comment]
Doesn't look like this is an Atom-related issue.

**Comment by sbrl** [comment]
It seems strange that Atom claims it's a bug in Atom and not `switch-headers-source`.

**Comment by Aerijo** [comment]
@sbrl That identifier isn't particularly reliable; it does it's best with what it's got.

On the other hand, if a user confirms that disabling a certain package stops an error being thrown, that strongly indicates that that package was causing the error. It may still be an issue on Atom's side, but that would have to be investigated and reported as such by the package maintainer.

**Comment by dschwen** [comment]
Whoops. Yeah, that's my package. Fix is in.
