### ISSUE TITLE
uriHandler functions are not awaited

### ISSUE THREAD

**Issue by UziTech** [atom/atom#19174]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

uriHandler functions are not awaited when called so an async function could fail without changing the history.

### Steps to Reproduce

see #19175

**Comment by lee-dohm** [comment]
We need a little more detail on what the impact is to you as a user of Atom or a package author. Can you give a specific example of a problem caused?

**Comment by UziTech** [comment]
I came across this when testing a [`open`](https://atom.io/packages/open). It opens a file in atom from a url like `atom://open?url=file://<file_path>`.

`open`'s handleURI function is async, as most handleURI packages should be, since it is [recommended](https://github.com/atom/atom/blob/0cd702003662990a13cbb420a9141c58a43ec93f/src/uri-handler-registry.js#L14-L16) to confirm any action since the command is coming from outside Atom.

The problem is when trying to test with `atom.uriHandlerRegistry.handleURI("atom://open")` there is no way to await the result.

**Comment by jasonrudolph** [comment]
> The problem is when trying to test with `atom.uriHandlerRegistry.handleURI("atom://open")` there is no way to await the result.

@UziTech: Thanks for taking the time to explain the motivation for this issue. And thanks for the fix in #19175. ✨
