### ISSUE TITLE
Dialogs are closed when Atom loses focus

### ISSUE THREAD

**Issue by izuzak** [atom/atom#1918]
Halp reports:
- support/a3fbafb2d0c011e3855fe03a98b207e5
- support/4068a4a4d08f11e39bd83f5315db0b57

Related Issues
- https://github.com/atom/feedback/issues/22
- https://github.com/atom/fuzzy-finder/issues/37

> If you have opened up the Command Palette (Command-Shift-P) in Atom v.0.92.0, and then switch to another app, say the Mac OS X Terminal app to run something you've been working on, the Command Palette is gone when you switch back (this is also true of this "Send us feedback" drop-down pane). It would be preferable if, on switching back to the Atom app v.0.92.0, that the Command Palette were still open where you left it.

I've noticed this myself, but never fund it particularly annoying. Also, some other dialogs are affected by this as well, such as the fuzzy finder. Unsure if this is something that's handled on a per-package basis or in Atom core, so opened an issue here. :pizza: 
- It seems that SublimeText doesn't have consistent behavior with these dialogs -- the command palette is closed similar to Atom, but the fuzzy finder is not (it stays open even after the app loses focus).

**Comment by jasoncavett** [comment]
Per #5754, and @izuzak's request to update this issue, I am noticing the same problem with the quick file/folder add dialog when it is done from the file explore menu.

**Comment by posita** [comment]
> Also, some other dialogs are affected by this as well, such as the fuzzy finder. Unsure if this is something that's handled on a per-package basis or in Atom core, so opened an issue here. :pizza:
>
>* It seems that SublimeText doesn't have consistent behavior with these dialogs -- the command palette is closed similar to Atom, but the fuzzy finder is not (it stays open even after the app loses focus).

I've gotten feedback from at least one developer (see Trudko/advanced-new-file#17) that this is an application-wide behavior and not a package thing. To avoid the SublimeText problem of inconsistent behaviors across packages, I suggest either fixing this in the Atom core, or at least providing a (perhaps hidden) setting that would apply to all dialog or pop-up behaviors.

**Comment by aev1tas** [comment]
Is such a feature or setting planned?

**Comment by christopherdumas** [comment]
It would be great if this were implemented/fixed.

**Comment by 50Wliu** [comment]
I did some brief investigation into this and the issue seems to be this line: https://github.com/atom/atom-space-pen-views/blob/73e07af07b90c47da1b37e29d98f3c66f9d87125/src/select-list-view.coffee#L36

It seems to have good intentions (ie it makes the modal disappear when you click anywhere else) but a `blur` event is also received when tabbing out.  I think this can be combated by checking if the window is actually focused before cancelling the modal (hopefully `window.isFocused()` already returns false when the blur is received).  I might take a stab at this tomorrow.

**Comment by 50Wliu** [comment]
This has been fixed and at the current pace of development will be included in Atom 1.7.0.

**Comment by 50Wliu** [comment]
This is back with the transition to atom-select-list.
