### ISSUE TITLE
Atom opens in new window instead of new tab, unlike previous behavior

### ISSUE THREAD

**Issue by fsa-development** [atom/atom#19196]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Recent update of Atom, or reinstallation to latest version, changes behavior of files opened externally from explorer, filezilla, winscp, etc. This behavior change is incredibly time wasting, frustrating and hopefully unintentional as it's a terrible user experience

### Steps to Reproduce

1. Install atom and any tool for remote browsing
2. Open a remote file using said tool
3. Atom launches a new window every time like an idiot

**Expected behavior:** 
The same behavior I've had since becoming an Atom user. Open in new tab

**Actual behavior:**
500,000 Atom windows

**Reproduces how often:** 
100%

### Versions
1.36.0 x64
Win 10

### Additional Information
Team members all wanting me to switch us to VSCode because of this. Is there no user testing before releases

**Comment by n8felton** [comment]
I am experiencing the same behavior with Atom 1.36.0 x64 on Win 10 (1803)

I attempted the steps in https://github.com/atom/atom/issues/12800#issuecomment-250076584, but they did not help.

**Comment by 50Wliu** [comment]
Thanks for creating an issue! We're aware of this and are tracking it in https://github.com/atom/atom/issues/19147 - feel free to subscribe there for updates.
