### ISSUE TITLE
macOS 10.14.4: Discard State Popup Works Half The Time

### ISSUE THREAD

**Issue by thekodester** [atom/atom#19199]
### Description

The discard state up only appears about half the time.

### Steps

1. File > Open

WORKING: https://youtu.be/KBKrbg6QpCs
NOT WORKING: https://youtu.be/-LaVY-nhy5A

### Prerequisites

[ X] Put an X between the brackets on this line if you have done all of the following:
Reproduced the problem in Safe Mode: Yes
Followed all applicable steps in the debugging guide: Yes
Checked the FAQs on the message board for common solutions: Yes
Checked that your issue isn't already filed: No.

### Versions

atom --version:
Atom : 1.36.0
Electron: 2.0.18
Chrome : 61.0.3163.100
Node : 8.9.3

apm --version:
apm 2.1.3
npm 6.2.0
node 8.9.3 x64
atom 1.36.0
python 2.7.10
git 2.20.1

**Comment by rsese** [comment]
Thanks for opening a new issue @thekodester - I think this is related to some of the issues reported in 1.36.0.  I had 1.35.1 installed and couldn't reproduce by enabling `Show Welcome Guide When Opening Atom` and then:

1. `atom --safe`
2. close all open windows
3. open a new window <kbd>Cmd+Shift+N</kbd>
4. Open some project with <kbd>Cmd+O</kbd>

*(though your videos were useful, exact step-by-step instructions to reproduce are super helpful for us)*

At this point with 1.35.1, I'm prompted to discard or recover project state.  After updating to 1.36.0, I'm no longer prompted with these steps.

I believe a hotfix will be released to address some of the 1.36.0 issues, lets see if this behavior is resolved too when that comes out.

**Comment by rsese** [comment]
1.36.1 is out and I just tried my [steps above](https://github.com/atom/atom/issues/19199#issuecomment-486057522) and see in 1.36.1, I'm prompted to discard or recover project state again.

Can you confirm @thekodester?

**Comment by thekodester** [comment]
Same. Now works as expected. :-)
