### ISSUE TITLE
Atom won't launch only open background processes

### ISSUE THREAD

**Issue by TheOnlyArtz** [atom/atom#19195]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom won't launch and just open some processes in the background

### Steps to Reproduce
I don't have any steps to reproduce, I've just randomally went to work on one of my projects and Atom didn't launch
**Expected behavior:** Atom will launch
**Actual behavior:** Atom only opens new processes in the background
but doesn't launch

### Versions

```
Atom    : 1.37.0-beta0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```
Note that I've installed 1.37.0-beta0 after it happened to me in
1.36.0!

**Comment by Aerijo** [comment]
What OS?

**Comment by TheOnlyArtz** [comment]
I'm actually managed to fix that right now, it was a syntax error in the `config.cson`.
