### ISSUE TITLE
macOS 10.14.4: Multiple Bugs Open/Closing

### ISSUE THREAD

**Issue by thekodester** [atom/atom#19190]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: Yes
    * Followed all applicable steps in the debugging guide: Yes
    * Checked the FAQs on the message board for common solutions: Yes
    * Checked that your issue isn't already filed: There is similar issues.

#### Description

When opening Atom sometimes it opens the last project I closed and other times I get the welcome guide.

#### Steps to Reproduce

1. Press _red circle/x_
2. Press Atom icon
3. Either I get welcome guide or the project I just closed

#### Description

When opening a project with 'File > Reopen Project' nothing happens or the project opens in a new window (no option to discard state).

#### Steps to Reproduce

1. Press File > Reopen Project
2. Select a project
3. Nothing or new window

**Expected behavior:** Issue 1 should just open welcome guide. Issue 2 should ask me if I want to discard state.

**Reproduces how often:** Issue 1 most of the time opens welcome guide with the rare time it opens the last project. Issue 2 happens all the time.

### Versions

_atom --version_:
Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

_apm --version_:
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0
python 2.7.10
git 2.20.1

<img width="698" alt="Screen Shot 2019-04-21 at 3 32 55 PM" src="https://user-images.githubusercontent.com/23484460/56474661-cd865080-644a-11e9-8259-7a3ab0a7edfa.png">

**Comment by rsese** [comment]
Thanks for the reports @thekodester!

Please open only 1 report per issue however - this makes it easier for the team to track things and close issues if something is fixed.

> ### Issue 2
> #### Description
> When opening a project with 'File > Reopen Project' nothing happens or the project opens in a new window (no option to discard state).

`Reopen Project` not working is a duplicate of https://github.com/atom/atom/issues/19149 so you can subscribe there for updates if you'd like.  Not sure about the other behavior you mention though ("or the project opens in a new window (no option to discard state).").  Might be related, but if you have specific steps to reproduce, please open a new issue and we'll take a look.

About issue 1:

> When opening Atom sometimes it opens the last project I closed and other times I get the welcome guide.

So it sounds like the behavior isn't consistent, is it 50/50?  Half the time it will open the last project and the other half you get the welcome guide?  Do you have showing the welcome guide enabled?

About your repro steps:

> 1. Press red circle/x
> 2. Press Atom icon
> 3. Either I get welcome guide or the project I just closed

Hmmm, based on your steps, I would think that an empty window is opened.  If you have 1 window open and close it (but don't quit Atom), then Atom's current state is with no projects open.  If you want the last project you had open to reopen, you should quit Atom (e.g. with <kbd>cmd-q</kbd>).  x-ref: https://github.com/atom/atom/issues/11361#issuecomment-242459033

**Comment by thekodester** [comment]
Thanks for the info.
