### ISSUE TITLE
error with install react

### ISSUE THREAD

**Issue by lxfljw** [atom/atom#19205]
when I install the package react  
it told me  that :
------------------------------------------------------------
 Installing “react@0.18.0” failed.Hide output…
Failed to install react because Git was not found.

The react package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.
--------------------------------------------------------------------

So, how can I do?

**Comment by 50Wliu** [comment]
Please follow the instructions listed in the error message. If you have further questions, please post them on https://discuss.atom.io. Thanks!
