### ISSUE TITLE
The editor has crashed with 128 find/replace python errors

### ISSUE THREAD

**Issue by mike663** [atom/atom#19212]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When causing 128 (or more) string errors in a python file with a find/replace, you can crash the editor.

### Steps to Reproduce

0. Use normal or safe mode
1. Create a file call it foo.py with 128 lines of print('foo')
2. Choose Find/Replace
3. Enter foo' in Find in current buffer line
4. Enter foo in Replace in current buffer line
5. Click Replace All

**Expected behavior:** 128 replaces

**Actual behavior:** "The editor has crashed"

~/.config$  /Applications/Atom.app/Contents/MacOS/Atom --safe
libc++abi.dylib: terminating with uncaught exception of type std::length_error: vector

**Reproduces how often:** 100%

### Versions

~/.config$ atom --version
Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

If you use 127 lines or fewer, the error doesn't happen.
If you use a non-python file, the error doesn't happen.

![image](https://user-images.githubusercontent.com/17882620/56753606-efd4e280-6758-11e9-9c83-8ebab49d4d92.png)

**Comment by 50Wliu** [comment]
@maxbrunsfeld is this the hard crash you fixed already, by any chance?

**Comment by maxbrunsfeld** [comment]
I believe so.

**Comment by 50Wliu** [comment]
@mike663 would you mind trying out Atom Beta and seeing if you can still reproduce the error?

**Comment by mike663** [comment]
I ran my example up to 4096 replaces generating syntax errors with no issue using Atom Beta. Looks good! Thanks!
