### ISSUE TITLE
Opening file causes system to lock for ~10 seconds on Ubuntu 19.04

### ISSUE THREAD

**Issue by khaeru** [atom/atom#19228]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following: [snip]

### Description

After upgrading from Ubuntu 18.10 to 19.04, certain simple operations in Atom cause the system to lock/hang for up to 10 seconds.

### Steps to Reproduce

1. Open `atom-beta --safe`.
2. Open a small text file (Ctrl+O).

**Expected behavior:** The file opens more or less instantly and is available for editing. This was the behaviour under Ubuntu 18.10.

**Actual behavior:**
- Keyboard input locks and the screen (including other visible windows) freezes for about 10 seconds. 
- The mouse cursor is movable if under the default Ubuntu `gdm3` session; or also locks if under the Ubuntu Wayland session.
- `gnome-shell` CPU usage (from `top` or `htop`) spikes to 100% and settles back to a low value after the screen unfreezes.
- The lock is usually long enough that Ubuntu/Gnome/apport offers to kill Atom after the screen unfreezes.

**Reproduces how often:** 100%

### Versions

```
$ atom-beta --version
Atom    : 1.37.0-beta1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ apm-beta --version
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.37.0-beta1
python 2.7.16
git 2.20.1
$ lsb_release -rd
Description:    Ubuntu 19.04
Release:        19.04
$ apt-cache policy atom-beta | head -n11
atom-beta:
  Installed: 1.37.0-beta1
  Candidate: 1.37.0-beta1
  Version table:
 *** 1.37.0-beta1 500
        500 https://packagecloud.io/AtomEditor/atom/any any/main amd64 Packages
        100 /var/lib/dpkg/status
     1.37.0-beta0 500
        500 https://packagecloud.io/AtomEditor/atom/any any/main amd64 Packages
     1.36.0-beta2 500
        500 https://packagecloud.io/AtomEditor/atom/any any/main amd64 Packages
```

### Additional Information

- See [this Ubuntu bug](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1826219) for further description.
- Saving a file causes a similar lock, though much shorter (~1 second).
- Google Chrome seems to cause similar locks (though much shorter in duration: ≤1 second, and not as repeatable), which maybe points to something underlying Electron/Chromium?

**Comment by rsese** [comment]
Thanks for the report @khaeru - I just installed 19.04 in a vm and with 1.37.0-beta1, I didn't notice any problem with a simple test file that just had "hello world" (I logged in both with the default and with Wayland).

Looking at your Ubuntu report, I see you mention other applications with the same problem like gedit and claws-mail?  So seems like an issue not specific to Atom or Electron?

**Comment by khaeru** [comment]
@rsese thanks for trying to reproduce. Yes, the issue also occurs with other applications—but the problem is worst under Atom, and I was able to identify concrete events that triggered it.

I was hoping to get instructions on how to profile or debug Atom's interaction with the underlying filesystem or OS. Perhaps the bug is upstream in gnome-shell or similar, but this would be one way to identify it precisely.

**Comment by rsese** [comment]
> I was hoping to get instructions on how to profile or debug Atom's interaction with the underlying filesystem or OS. Perhaps the bug is upstream in gnome-shell or similar, but this would be one way to identify it precisely.

I'm not sure if this will help diagnose interaction with the filesystem/OS but we have this section in our documentation on diagnosing runtime performance: https://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance.  Sorry I don't have more details here but you might get more suggestions on the [official message board](https://discuss.atom.io/) or the [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638).

**Comment by khaeru** [comment]
The failure mode here seemed to be:
1. the GNOME Shell extension 'desktop-icons' redraws the desktop any time a file in the desktop directory is modified; even if the file is hidden or the desktop is not visible. This process can be very slow; see https://gitlab.gnome.org/World/ShellExtensions/desktop-icons/-/issues/58
2. On my system, `$HOME` is used as the desktop directory.
3. The Atom package [wakatime](https://atom.io/packages/wakatime) modified `$HOME/.wakatime.{cfg,log}`.

(3) thus triggered (1). The mitigation was to set the `$WAKATIME_HOME` environment variable so that Wakatime would not modify files in the desktop directory.

cf. wakatime/atom-wakatime#90, wakatime/atom-wakatime#94
