### ISSUE TITLE
Move to trash can on C: from E: USB drive

### ISSUE THREAD

**Issue by mbpscruise** [atom/atom#19232]
## Summary

**This feature would remove a file and send it to the recycle bin in a user chosen drive, if the active project you are working on is in a separate mounted drive** (E: in my example). What would happen is if it does not find a trash can, Atom will send trash to the C: drive, based on an optional setting: `Send files to drive [Drive letter]`. An additional option in the `Drive letter` parameter list is `Ask each time`. The default setting would be `Current project's drive`, or something like that, better worded.

## Motivation

**It's annoying when you attempt to delete files on a project which is opened on a USB drive.**

```
The following file couldn't be moved to the trash.
E:\bootstrap-intro\a
Is there a Recycle Bin on the drive where the files are stored?
```

**This error pops up each time you attempt to delete a file stored in a drive without a recycle bin `[DriveLetter]:\$Recycle.Bin` directory.** In my case, Windows Explorer takes too long to remove files (~30s per file deletion/rename on my PC, no matter the file size, likely because of its instability on lower-end machines), and it forces me to move to Powershell to `cd` and `rm` it separately.

## Describe alternatives you've considered

- **A package would not be suitable, because it is built-in functionality which is not working.**
- I could create a recycle bin on my drive, but I would rather send it to my "master" C: drive's trash where all my other deleted files are on my mounted OS, than to constantly remove these random files from a created trash drive as a second step.

## Additional context

![image](https://user-images.githubusercontent.com/16228713/56871727-49524100-69e7-11e9-8e01-1fe7676812cb.png)

**Comment by 50Wliu** [comment]
@mbpscruise this is a limitation of Electron's `shell.moveItemToTrash` function -- I would recommend that you subscribe to https://github.com/electron/electron/issues/4974 for updates.
