### ISSUE TITLE
Flaky build: atom-application test sometimes fails on Linux

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19235]
In our Linux builds on the Azure pipelines, sometimes the `atom-application` test step fails with a timeout:

```
  1) FileRecoveryService when no crash happens during a save creates a recovery file and deletes it after saving:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at <anonymous>:null:null
  

  2) FileRecoveryService when a crash happens during a save restores the created recovery file and deletes it:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
      at <anonymous>:null:null
```

---

**Affected CI provider(s)**: Azure DevOps

**Affected platform(s)**: Linux

**Example commit experiencing flakiness**: https://github.com/atom/atom/commit/0219306c873dc3b8cfda640007b1f7f15a7df170

**Example failing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=39012

**Example passing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=39028

**Comment by 50Wliu** [comment]
@rafeca the example failing build is from Appveyor, which runs Windows? That one also contains a renderer crash, not the one listed in this issue.

**Comment by rafeca** [comment]
Ups you're right 😅 I've updated the description (the example of passing build is still building, if for some reason it does not pass I'll restart it).

**Comment by rafeca** [comment]
I've had the `atom-application` tests running using the following command:

```
$ while ATOM_DEV_RESOURCE_PATH=/home/atom/atom atom --test --main-process spec/main-process/; do :; done
```

I have kept running this command for ~5h continuously without experiencing any issue, using an Ubuntu 16.04 VM (which should be similar to the one used in our CI systems), so I'm not sure how can I reproduce the flakiness.

I'll think more about potential differences between my local VM setup and the one in CI tomorrow

**Comment by rafeca** [comment]
Another failure in our CI systems: https://github.visualstudio.com/Atom/_build/results?buildId=39353&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=6c939d89-0d1a-51f2-8b30-091a7a82e98c&lineStart=256&lineEnd=259&colStart=1&colEnd=31

**Comment by jasonrudolph** [comment]
Another one:

https://github.visualstudio.com/Atom/_build/results?buildId=39395&view=ms.vss-test-web.build-test-results-tab

**Comment by jasonrudolph** [comment]
And one more for good measure 🙀 

https://github.visualstudio.com/Atom/_build/results?buildId=39485&view=ms.vss-test-web.build-test-results-tab&runId=1065208&resultId=100112&paneView=debug

**Comment by rafeca** [comment]
Another one: https://github.visualstudio.com/Atom/_build/results?buildId=39585

I've checked the differences in the logs between test runs that are successful vs the ones that fail and they are almost identical, the only difference is that [this group of tests](https://github.com/atom/atom/blob/master/spec/main-process/file-recovery-service.test.js#L29-L153) take much longer to execute on some builds (each of them usually take 1-6ms and in some builds they take from 200ms up to 2s). Since the timeout for these tests is 2s, on the "slow builds" these tests timeout.

I'm gonna investigate for ~30min what could be the root cause of that slowness... but if I cannot find it I may just increase the timeout for that group of tests to something like ~20s (similar to the `atom-application` tests).
