### ISSUE TITLE
Performance regression in v1.36.1

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19239]
By looking at the [Atom usage metrics](https://github.com/atom/metrics), we've discovered that the [Shell load time](https://github.com/atom/metrics/blob/master/docs/events.md#shell-load-time) (which is a proxy for the Atom startup time) has regressed on the v1.36.1 release on Windows machines:

<img width="1288" alt="Screen Shot 2019-04-30 at 15 14 53" src="https://user-images.githubusercontent.com/408035/56966562-a7099900-6b5f-11e9-9a29-88c38736d1fb.png">

After doing some investigation, this regression was introduced in https://github.com/atom/atom/pull/19109, and more specifically it's caused [by this line](https://github.com/atom/atom/blob/master/src/main-process/atom-application.js#L79), which takes up to a second to execute on Windows (blocking the main process and therefore the startup of Atom).

Looks like this issue may be caused by https://github.com/electron/electron/issues/2073

**Comment by rafeca** [comment]
Related to this issue, [this line](https://github.com/atom/season/blob/master/src/cson.coffee#L14) which is on the Atom startup path also takes ~500ms and the root cause seems to be the same.

/cc @codebytere are you folks aware of this issue with `crypto.randomBytes()` on Windows?

**Comment by codebytere** [comment]
hrmmmm no but i can take a look!

**Comment by rafeca** [comment]
@codebytere I've just tried to reproduce the issue using [the electron quickstart repo](https://github.com/electron/electron-quick-start) and I could see the regression when pointing to [the commit](https://github.com/electron/electron-quick-start/commit/9f0ab1460f949e656b0ff37a732cd950363dc1cd) that uses `electron@v2.0.0`, but the issue is no longer there when using `v3.0.0` and upwards, so seems like it was fixed, no need to worry 😄

**Comment by codebytere** [comment]
Awesome! glad it's sorted, feel free to ping us anytime!
