### ISSUE TITLE
Atom freezes randomly when opening a folder

### ISSUE THREAD

**Issue by misode** [atom/atom#19261]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Sometimes, Atom freezes completely when I click a folder in the project tree. Force closing Atom and restarting it is the only solution.

### Steps to Reproduce

1. Work on a large project
2. Start opening folders in the project tree
3. Sometimes this will cause Atom to freeze completely

**Reproduces how often:** 
Happens fairly often.
I believe this happens more often if there are already a lot of folders unfolded (opened).

### Versions
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

Windows 10 Home
Version 1803
OS Build 17134.706

**Comment by rsese** [comment]
Thanks for the report!   Can you confirm if the behavior was exactly the same in safe mode where you would randomly see Atom freeze when opening a folder?  And have you seen this on multiple projects or just a particular project?

Also, if you've used previous versions of Atom, is this behavior new for you as of 1.36.1?

Lastly, some clarifying questions:

> Work on a large project

How large?  

> I believe this happens more often if there are already a lot of folders unfolded (opened).

About how many folders are in the project and about how many need to be unfolded before you see this behavior?

**Comment by slime-man** [comment]
I am on macOS 10.14. Atom v 1.36.1

I leave the same Atom window open for long stretches of time, and in this single window I do a lot of "Add project folder".... do some work.... "Remove project folder".... on to the next one.

I find that if I have added and removed a lot of project folders without closing the window, eventually Atom starts to slow down, and trying to open a file from the tree will eventually freeze the app. A quit+reopen fixes the problem.

I will have to investigate if it happens more often when I am deleting the underlying folders that were/are in the project folder list.

I wish I could tell you what "a lot of adds/removals" meant. It's probably greater than 10, but definitely less than 100.
