### ISSUE TITLE
1.38.0-nightly18 is unusable on mac

### ISSUE THREAD

**Issue by akonwi** [atom/atom#19278]
latest nightly (1.38.0-nightly18) doesn't launch new windows on mac. Starting Atom Nightly from the launcher starts the app but there is no 'File' menu from which to attempt to open a window. Even from the command line with file path specified, the outcome is the same.

**Comment by Arcanemagus** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/atom/pull/19277. It should be available in the next `nightly` build.

----

In the future please fill out the template as we usually close issues that aren't correctly filed.
