### ISSUE TITLE
Ctrl + Shift + Backspace to delete entire line

### ISSUE THREAD

**Issue by doakey3** [atom/atom#19289]
Both Geany and the Ace editors have a shortcut for deleting an entire line of text. It's one I use frequently. I propose adding it to the default set of shortcuts in Atom.

Ctrl + Shift + Backspace:

![untitled](https://user-images.githubusercontent.com/16495887/57447507-dd5cad80-721c-11e9-8112-ad9320c465bd.gif)

**Comment by rsese** [comment]
Thanks again for the suggestion @doakey3 - as I mentioned in the other issue you opened and as mentioned in the issue template, we're unlikely to prioritize feature requests right now.  And additionally, we strongly prefer that people take advantage of Atom's customizability where possible.

For keybindings in particular, we expect that people will [customize them](https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/) to fit their needs e.g. if someone wanted this functionality, they can add this to their keymap:

```cson
'atom-text-editor':
 'ctrl-shift-backspace': 'editor:delete-line'
```

And about default keybindings, we're at a place where we're not adding/changing default keybindings unless there's a strong reason to do so.

For these reasons, we'll close this issue but thanks again for your interest!
