### ISSUE TITLE
`apm --version` doesn't work in Windows

### ISSUE THREAD

**Issue by kaiyoma** [atom/atom#19309]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

`apm --version` doesn't work in Windows.

### Steps to Reproduce

1. Run `apm --version`.

**Expected behavior:** [What you expect to happen]
Versions to be printed.

**Actual behavior:** [What actually happens]
```
$ apm --version
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at EventEmitter.<anonymous> (...\AppData\Local\atom\app-1.36.1\resources\app\apm\lib\apm-cli.js:169:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

```
$ atom --version

Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

**Comment by 50Wliu** [comment]
Do you have Python 2 installed? That line is the line it tries to determine which Python version you have installed.

**Comment by kaiyoma** [comment]
Yes indeed:

```
$ which python
/c/Program Files/Python/python

$ python --version
Python 2.7.15
```

Even if I didn't have it installed, I think this would still be a bug, because there should be a proper error message, not a stack trace.

**Comment by 50Wliu** [comment]
Ah, what shell are you running those commands from? Seems like it's a bash shell? Does this work if you run it using `cmd.exe` or Powershell?

**Comment by kaiyoma** [comment]
Yeah, it's the git bash shell: https://git-scm.com/download/win

I can confirm that the command works correctly in the normal command prompt and PowerShell. I would think that the git bash shell would be popular among Windows web developers.

**Comment by 50Wliu** [comment]
Cool, thanks. I'm not sure why this wouldn't work using Git Bash. Sure would be helpful if we got more output than an `UNKNOWN` error...

Would you mind closing this issue and re-opening it on the [atom/apm](https://github.com/atom/apm) repo? Thanks :)

**Comment by kaiyoma** [comment]
Opened https://github.com/atom/apm/issues/846
