### ISSUE TITLE
UI Coloring Discrepancy with EOF

### ISSUE THREAD

**Issue by rodibin-at-placemaildotonline** [atom/atom#19306]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Coloring gets whack 

### Steps to Reproduce

1. Add this code to atom (runs fine)

```
#!/system/bin/sh

function parse_plex() {
    read -r -d '' pyfunc <<-"----EOF"
        print("test")
----EOF
    python -c $pyfunc
}

PY_RESULT='command -v python3'
  if [ "${PY_RESULT:-null}" = null ]; then
    echo "$LOG_DATE: Python is not installed, trying a regex..." &
      PLX_IP=$(
        curl -b ${MN_DIR}/plexcookie.txt "https://plex.tv/pms/resources.xml?includeHttps=1&X-Plex-Token=${PLX_TOK}" | \
        grep 'local="1"' | \
        sed 's/.*uri=\"\([^\"]*\)\"\slocal.*/\1/g' | \
        tail -n 1)
  else
    echo "$LOG_DATE: Python is installed, parsing Plex XML with python..." &
    parse_plex
  fi
```
2. Look at text below the last` ----EOF`
3. Coloring is incorrect
4. Break code by adding a quote " to the end of the last ` ----EOF` so it reads ` ----EOF"` OR remove the parentheses around `("test")`
5. Coloring becomes correct, but code gets broken

**Expected behavior:** Syntax is properly picked up and coloring remains the same

**Actual behavior:** Coloring changes. Please see [here](https://stackoverflow.com/questions/2189098/embedding-short-python-scripts-inside-a-bash-script) if you'd like an explanation of the code

**Reproduces how often:** 100%

### Versions
MacOS 10.14.4

Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by 50Wliu** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the [language-shellscript](https://github.com/atom/language-shellscript) repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us half way :+1:
