### ISSUE TITLE
[WSL] atom.sh assumes default root automount

### ISSUE THREAD

**Issue by solvaholic** [atom/atom#19317]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * n/a Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * n/a Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * X Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * X Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * n/a Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If I mount C: at /c, running `atom` in WSL won't load Atom:

```
$ findmnt --source C:
TARGET SOURCE FSTYPE OPTIONS
/c     C:     drvfs  rw,noatime,uid=1000,gid=1000,umask=22,fmask=11,metadata,case=off
$ atom
The system cannot find the path specified.
```

`atom.sh` sets $root; It doesn't use it when setting $ATOMCMD, though:

https://github.com/atom/atom/blob/c5ebfbddd096a24bb99b832432a5dfcd67da4714/resources/win/atom.sh#L8-L15

To me this seems like https://github.com/atom/atom/issues/17794, but it's happening with Ubuntu 18.04 on WSL with Windows 10 (1809) and Atom 1.36.1.

### Steps to Reproduce

1. On Windows 10 (1809): Enable WSL, install Atom, install Ubuntu.
2. In Ubuntu on WSL, configure `/etc/wsl.conf` to mount root at /:
    ```
    [automount]
    root = /
    ```
3. Exit Ubuntu, run Ubuntu again, and run `atom`:
    ```
    atom
    ```

**Expected behavior:** Atom should open.
**Actual behavior:**

```
$ atom
The system cannot find the path specified.
```

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Windows 10 (1809), Ubuntu 18.04:
```
$ systeminfo.exe | grep -E '^OS (Name|Version)'
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
$ grep ^VERSION= /etc/os-release
VERSION="18.04.2 LTS (Bionic Beaver)"
$ uname -r -o
4.4.0-17763-Microsoft GNU/Linux
```

Atom 1.36.1:
```
C:\Users\Solvaholic>atom --version

Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

C:\Users\Solvaholic>apm --version
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.1
python 3.7.1
git 2.21.0.windows.1
visual studio
```

### Additional Information

This issue is just about _opening_ Atom using the built-in methods. With a fresh install of the Ubuntu app (no custom aliases or functions) and current default Windows / WSL (appends Windows %Path% to Linux $PATH), running `atom` in Linux will run `%LOCALAPPDATA%\atom\bin\atom` in your Windows user's home directory. That script calls your current Atom version's `atom.sh`:

```
$ cat $(which atom)
#!/bin/sh
"$(dirname "$0")/../app-1.36.1/resources/cli/atom.sh" "$@"
```

Other issues related to running Atom from Linux/WSL, like path availability or translation, are outside the scope of this issue.

**Comment by Khorsan** [comment]
Have you tried `atom $DIR`, specifying the directory you're working on?

i.e. If you are currently on the directory you want to open, execute `atom .`

**Comment by solvaholic** [comment]
@Khorsan thank you for suggesting that. I get different results with 1.38.2 and an updated Windows, also unsuccessful. Will have to dig into this later:

```
$ atom
'\\wsl$\Ubuntu\home\solvaholic'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
The system cannot find the path specified.
```

First I re-installed Atom and deleted and re-created my Ubuntu WSL environment.

<details>

**Re-install Atom and re-create Ubuntu environment:**

1. Uninstall Atom.
2. Download and run Atom 1.38.2 installer.
3. Use `wsl --unregister Ubuntu` to uninstall my Ubuntu environment. Then run Ubuntu to create a new one. Created my user account, and:

    ```
    sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y
    ```

4. Mounted `C:\` at `/c`:

    ```
    $ sudo findmnt --source 'C:\'
    TARGET SOURCE FSTYPE OPTIONS
    /c     C:\    drvfs  rw,noatime,uid=1000,gid=1000,umask=22,fmask=11,metadata,case=off
    ```

**Windows and WSL Ubuntu versions:**

```
$ systeminfo.exe | grep -E '^OS (Name|Version)'
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
$ grep ^VERSION= /etc/os-release
VERSION="18.04.2 LTS (Bionic Beaver)"
$ uname -r -o
4.4.0-18362-Microsoft GNU/Linux
```

**Atom version:**

```
C:\Users\solvaholic>atom --version

Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

C:\Users\solvaholic>apm --version
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 3.7.1
git 2.19.2.windows.1
visual studio
```

</details>

Then I tried these:

```
$ alias atom
-bash: alias: atom: not found
$ which -a atom
/c/Users/solvaholic/AppData/Local/atom/bin/atom

$ atom .
'\\wsl$\Ubuntu\home\solvaholic'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
The system cannot find the path specified.

$ atom thisisnotarealdirectoryname
'\\wsl$\Ubuntu\home\solvaholic'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
The system cannot find the path specified.
```

**Comment by Khorsan** [comment]
I didn't realize that you were working on WSL. Code works in that way and Atom works with that command within native Linux.

Maybe WSL doesn't have support for starting Atom using the same method

**Comment by solvaholic** [comment]
> I get different results with 1.38.2 and an updated Windows, also unsuccessful.

I see now, the error from running `atom` is the same. The additional error is just explains a WSL path translation issue.

Using a different command to illustrate:

```
$ cmd.exe /C "echo" "LOOK AT ME :D"
'\\wsl$\Ubuntu\home\solvaholic'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
"LOOK AT ME :D"
```

When I ran `atom` [above](https://github.com/atom/atom/issues/19317#issuecomment-504785708), `The system cannot find the path specified.` was the error from that.

**Comment by solvaholic** [comment]
Thank you stalebot!

Both Atom and WSL have evolved and idk whether this issue still exists, so I'll close it.
