### ISSUE TITLE
Unable to spawn notify subprocess on Windows

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#19311]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On opening a project, I get the following error message:
```
Uncaught Error: spawn ../node_modules/@atom/notify/lib/../notify-subprocess-win32 ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

`notify/notify-subprocess-win32` indeed does not exist, but `notify/notify-subprocess-win32.exe` does. Though curiously, renaming the file doesn't fix the error...

### Steps to Reproduce

1. Select the new `@atom/notify` filesystem watcher in Settings
2. Restart Atom

**Expected behavior:** No error

**Actual behavior:** See above

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.39.0-dev-d35e39605
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

This is after a full `script\clean` and rebuild. I'm running this on the apm branch, but since the subprocess executable exists, I don't think my apm changes have anything to do with this.
/cc @nathansobo

**Comment by nathansobo** [comment]
@50Wliu You say the notify subprocess executable exists? What is its location? I found that the `.exe` extension doesn't matter when spawning.

**Comment by nathansobo** [comment]
I wonder if this is related to the ASAR bundle. I tested in dev mode but never with a full build.

**Comment by Arcanemagus** [comment]
I'm seeing the same thing when attempting to enable the `@atom/notify` watcher, however it doesn't appear that the executable file exists _at all_ for me in `1.39.0-nightly2`.

The `C:\Users\abneyl\AppData\Local\atom\app-1.39.0-nightly2\resources\app.asar.unpacked\node_modules\@atom` folder only contains `fuzzy-native`, `nsfw`, and `watcher`. I'm assuming that is where it should be located at least, the `../node_modules/@atom/notify/lib/../notify-subprocess-win32` doesn't appear to make sense anywhere else.

Additionally I'm seeing two copies of this warning message, possibly from `atom/github` trying to launch a file watcher?
```
net.js:726 Uncaught (in promise) Error: This socket is closed
    at Socket._writeGeneric (net.js:726:18)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at Watcher._sendRequest (C:\Users\abneyl\AppData\Local\atom\app-1.39.0-nightly2\resources\app\static\<embedded>:14:1149228)
    at Watcher.watchPath (C:\Users\abneyl\AppData\Local\atom\app-1.39.0-nightly2\resources\app\static\<embedded>:14:1148886)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by nathansobo** [comment]
I'm hoping that if I exclude the file from ASAR that we'll be golden.

**Comment by 50Wliu** [comment]
> What is its location?

`atom\node_modules\@atom\notify\notify-subprocess-win32.exe`

**Comment by Arcanemagus** [comment]
I'm still seeing this on a zip from [this build](https://ci.appveyor.com/project/Atom/atom/builds/24515900) from merging #19325.

**Comment by Arcanemagus** [comment]
It looks like the `cwd` isn't being set in the call to `spawn`, I'm _guessing_ it would inherit from `process.cwd` in that case, which is the main folder containing `atom.exe`.

In the case of the test run that gives us:
`process.cwd`: `C:\Users\abneyl\AppData\Local\atom\Atom_Dev_x64_da8b1a1a`

Meaning the path `..\node_modules\@atom\notify\bin\notify-subprocess-win32` isn't valid.

At least after #19325 the executable file is under `resources\app.asar.unpacked\node_modules\@atom\notify\bin` 😉.

**Comment by nathansobo** [comment]
I will dig in this morning specifically on Windows and figure this out.

**Comment by 50Wliu** [comment]
Okay, I take that back. It's still not working, unfortunately... Not sure what happened that one time.

This is with a `script\clean` followed by a `script\build --install`.
![image](https://user-images.githubusercontent.com/2766036/57747550-ff827f80-76a3-11e9-8a1c-948392b05762.png)

There **is no `notify` folder** under `node_modules\@atom`, which @Arcanemagus mentioned earlier.
