### ISSUE TITLE
Reopen Project in safe/dev mode opens existing project in normal window

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#19310]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

If you have Project A open in a normal Atom window and want to open it as well using the Reopen Project command in a safe/dev window, the existing Atom window will be focused.
This does _not_ happen using Add Folder.

### Steps to Reproduce

1. `atom some-project`
2. `atom --safe`
3. `application:reopen-project`
4. Select `some-project`

**Expected behavior:** `some-project` to open in the safe window

**Actual behavior:** The normal window is focused

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.39.0-dev-d35e39605
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

/cc @smashwilson

**Comment by pavan5555** [comment]
Hi I would like to give it a try!

**Comment by sadick254** [comment]
@pavan5555 Sure. Feel free to ping me if you have any questions.

**Comment by pavan5555** [comment]
@sadick254  sure, thank you!

**Comment by RuchiGitHu** [comment]
I want to contribute in this issue, please let me know something about this issue for my understanding..
Thanks in advance.
