### ISSUE TITLE
Atom doesn't open a new window with a new file.

### ISSUE THREAD

**Issue by miguelms95** [atom/atom#19319]
### Description

When you Open a new file (Ctrl + N), if you want to edit it in a new window, Atom doesn't open the new window.

### Steps to Reproduce

1. Open Atom, a new or existing project
2. Open a new tab (Ctrl + N)
3. Right click on the new tab and click "Open In New Window"

**Expected behavior:**

Atoms opens a new window with the new file for editing.

**Actual behavior:**

When you click "Open In New Window", it doesn't do anything.

**Reproduces how often:**

Always.

### Versions

Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

OS: Ubuntu 18.04.2 LTS

**Comment by smashwilson** [comment]
Transfering this over to atom/atom because this is a core issue 📬

**Comment by 50Wliu** [comment]
Cannot confirm on Windows 1.38.0-dev. Though I get different behavior that doesn't align with what "Open in New Window" is supposed to do...will open a separate issue for that.

@miguelms95 if you update to Atom 1.36.1, do you still encounter the same issue?

**Comment by wadethestealth** [comment]
My Versions:
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

Windows 10 Home
Version	10.0.17134 Build 17134

I have the exact same behavior as open. Meaning nothing happens.

**Comment by rsese** [comment]
I can reproduce with 1.38.0-beta0 when trying to `Open in New Window` with a new unsaved file but seems like this is reported already? 

https://github.com/atom/tabs/issues/400

**Comment by rsese** [comment]
Oops, accidentally commented too quickly - I'm going to close in favor of https://github.com/atom/tabs/issues/400 but if I'm misunderstanding let me know and we can reopen.

**Comment by wadethestealth** [comment]
@rsese yes this post appears to be a duplicate.
