### ISSUE TITLE
Ctrl+tab, then holding Ctrl and using arrow keys to select tab doesn't work

### ISSUE THREAD

**Issue by michaelkonecny** [atom/atom#19330]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When switching tabs and the list of tabs is shown (I'm holding Ctrl to keep it open), I would like to be able to select among this list using the arrow keys.

### Steps to Reproduce

1. Open multiple tabs
2. Press <kbd>Ctrl</kbd>+<kbd>tab</kbd>, keep holding <kbd>Ctrl</kbd> to keep the list open
3. Use up and down arrow keys

**Expected behavior:** Selection among open tabs list

**Actual behavior:** Current line gets moved up an down in the editor. This is especially bad because the editor is in the background and one might not even notice.

**Reproduces how often:** 100%

### Versions

atom: 1.36.1 x64
apm: 2.1.3
Windows 7 Pro

**Comment by lee-dohm** [comment]
Thanks very much for the suggestion!

On review with the team, this isn't something that we're going to have the time to work on anytime soon. However, we would be open to a well-written pull request that implements this feature as-described. Because of this, I'm going to mark it `help-wanted` and close it so that others can easily find it.

Thanks again for the great idea!
