### ISSUE TITLE
.atom-socket-secret-* needs to be added to .gitignore for .atom folders.

### ISSUE THREAD

**Issue by trusktr** [atom/atom#19334]
F.e., The new Atom makes a new `~/.atom/.atom-socket-secret-trusktr-1.37.0` file in my case.

I believe this needs to be added to .gitignore in `~/.atom` for the convenience of the users synching their `~/.atom` folders, right?

**Comment by rafeca** [comment]
Yup that’s right: this is a temporary file that gets created and deleted by atom on startup/shutdown

**Comment by 50Wliu** [comment]
@trusktr is talking about https://github.com/atom/atom/blob/master/dot-atom/.gitignore, which does need to be updated.

**Comment by rafeca** [comment]
Ups, sorry about that, i thought it was just a question 🙃

**Comment by Arcanemagus** [comment]
@trusktr The above is _exactly_ why the template is required for _all_ issues. In the future please remember to fill it out 😉.
