### ISSUE TITLE
Enabling @atom/notify by default causes CI failures with electron v3

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19333]
We're getting some CI failures on the [`electron-3.1` branch](https://github.com/atom/atom/pull/18916/) on Windows:

```
Error: async hook stack has become corrupted (actual: 5580, expected: 0)
 1: v8::RetainedObjectInfo::~RetainedObjectInfo
 2: node::RemoveEnvironmentCleanupHook
 3: node::InternalCallbackScope::Close
 4: uv_run
 5: 0140999B
 6: 0140A236
 7: 015738DC
 8: 015AF71E
 9: 015AF892
10: 015AFA54
11: 015B04B3
12: 015B00F5
13: 01581448
14: GetHandleVerifier
15: GetHandleVerifier
16: IsSandboxedProcess
17: IsSandboxedProcess
18: IsSandboxedProcess
19: GetHandleVerifier
20: 01404AB6
21: IsSandboxedProcess
22: BaseThreadInitThunk
23: RtlInitializeExceptionChain
24: RtlInitializeExceptionChain
Error! The 'core-main-process' test step finished with a non-zero exit code
```

The issue seems to be caused by `@atom/notify`

**Comment by nathansobo** [comment]
Crazy. We don’t do anything interesting in that module other than spawn a subprocess with normal APIs.

**Comment by rafeca** [comment]
I could isolate the crash to this specific test: https://github.com/atom/atom/blob/master/spec/main-process/atom-window.test.js#L84

The test does not seem to need to use or require the `path-watcher` module, so I'm confused as well... Maybe the root cause has nothing to do with `@atom/notify`...

**Comment by rafeca** [comment]
The reason why I think that it may be related to `@atom/notify` is because I bisected the issue between two different builds in Azure:

- ✅ [First build](https://dev.azure.com/github/Atom/_build/results?buildId=40558) from commit e043512b9571f0b837f34d606e87e6868539b8fc
- ❌ [Second build](https://dev.azure.com/github/Atom/_build/results?buildId=40560) from commit bc0e0c5f26adaaae6ffbf5a1f5fe284f39720cfd

And when looking [at the list of changes between both commits](https://github.com/atom/atom/compare/e043512b9571f0b837f34d606e87e6868539b8fc...bc0e0c5f26adaaae6ffbf5a1f5fe284f39720cfd), there's only the `@atom/notify` commits.

**Comment by rafeca** [comment]
It seems that after [disabling `@atom/notify`](https://github.com/atom/atom/pull/19345) and rebasing the `electron-3.1` branch, [the build failures on CI are gone](https://github.com/atom/atom/pull/18916).

Since the current plan is to keep `@atom/notify` disabled, I'm going to remove this issue from the list of blockers for the electron v3 upgrade, but I'll keep this issue opened and rename it just in case we ever want to explore using `@atom/notify` in the future.

**Comment by nathansobo** [comment]
I feel like we could close this, since we're taking a different path and the `@atom/notify` option isn't even in the code base now.
