### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=500

### ISSUE THREAD

**Issue by EsanL** [atom/atom#19341]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=500

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, statusCode=500
    at ClientRequest.onConnect (/app.asar/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -3:53.5.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  3x -3:37.6.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -3:23.4.0 core:confirm (input.hidden-input)
     -0:30.6.0 core:select-all (input.hidden-input)
  6x -0:29.3.0 core:backspace (input.hidden-input)
  2x -0:24.8.0 core:confirm (input.hidden-input)
     -0:11.1.0 core:select-all (input.hidden-input)
  2x -0:09.5.0 core:backspace (input.hidden-input)
     -0:07.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```

```

**Comment by rsese** [comment]
Thanks for the report - this looks like an error related to the proxy you're using?  If the error is intermittent or only happened once, then there might be a temporary issue with your network or proxy and retrying might help.  If the error is consistently reproducible and you've [configured Atom to work with your proxy](http://flight-manual.atom.io/getting-started/sections/installing-atom/#proxy-and-firewall-settings), then a good place to get help is our [official message board](https://discuss.atom.io/).  People in the community that have configured Atom to work with their proxies can chime to share what worked for them and provide suggestions.
