### ISSUE TITLE
Saved files never get closed

### ISSUE THREAD

**Issue by TomekTrzeciak** [atom/atom#19342]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Each time a file is saved atom reopens it in read mode and never closes the file descriptor. This causes problems on network shares if the file is unlinked (stale .nfsXXX files), e.g. after git checkout.

### Steps to Reproduce

1. touch /tmp/foo
2. atom /tmp/foo
3. save /tmp/foo (from file menu or ctrl+s)
4. lsof /tmp/foo will show atom process holding /tmp/foo open in read mode
5. repeat steps 3&4, to get more file descriptors open (I got to over 2000 just by keeping cltr+s pressed for long enough)

**Expected behavior:** close file after save

**Actual behavior:** file is kept open after save (file descriptor is not released)

**Reproduces how often:** every time

### Versions
```
$ atom --version
Atom    : 1.26.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

$ apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.26.0
python 2.7.5
git 2.16.5

$ cat /etc/redhat-release 
Red Hat Enterprise Linux Client release 7.6 (Maipo)
```
### Additional Information

Possibly related to #17355

**Comment by Aerijo** [comment]
@TomekTrzeciak FYI, your Atom version is 11 releases out of date

**Comment by TomekTrzeciak** [comment]
@Aerijo, I don't have access to more recent version, but that should change later this month. I'll update this ticket then.

**Comment by TomekTrzeciak** [comment]
I've tested  on the latest release (1.37) and this issue appears to be fixed.
