### ISSUE TITLE
Keyboard shortcut: Add selection Above/Below

### ISSUE THREAD

**Issue by Frozenfire92** [atom/atom#1934]
By default this shortcut is `control-shift-up` or `control-shift-down`

Yet this is a default  OSX shortcut for Mission Control / Application Windows with the slow modifier being shift

![screen shot 2014-05-06 at 1 15 47 pm 2](https://cloud.githubusercontent.com/assets/5893112/2892147/baebbffa-d539-11e3-9e3c-725e473a97da.png)

**Comment by myung** [comment]
+1

**Comment by pankil-shah** [comment]
+1 to @joshua-mcginnis 's solution above. The code is to be added to the `/user/yourName/.atom/keymap.cson` file.

Additional feature: after you extend the cursor to multiple lines continue to hold down `alt` + `shift` and press `left` or `right` to select everything to the start or end of the line.

**Comment by 3noch** [comment]
+1

**Comment by 3noch** [comment]
I think this could safely be moved from the enhancement label to the bug label. The menu short cuts simply don't work at all on Mac.

**Comment by Cram974** [comment]
+1

**Comment by lee-dohm** [comment]
Thanks for the feedback on this Issue everyone. We understand the default chosen is perhaps not the best for everyone. Since customizing Atom's keybindings is pretty easy we're not looking to change the defaults for everyone right now. I've updated the example above for the latest keybinding selectors here:

```coffee
'atom-workspace atom-text-editor:not([mini])':
  'shift-alt-up': 'editor:add-selection-above'
  'shift-alt-down': 'editor:add-selection-below'
```

Thanks again for everyone's contribution!

**Comment by 3noch** [comment]
> We understand the default chosen is perhaps not the best for everyone.

@lee-dohm Any chance the default could be per-OS? On Mac the chosen default just doesn't work.

**Comment by zinkkrysty** [comment]
Personally I never use that OSX shortcut. It also has a weird animation bug, where it slowly creeps in/out. So I went on and disabled it. 

You can change/disable that in System Preferences > Mission Control > Keyboard and Mouse Shortcuts > Mission Control and Application windows.

**Comment by chadnickbok** [comment]
This is a terrible user experience for people switching from other editors, as is often touted as the "killer feature" of next-generation editors.

Letting this be the default is a lazy choice - you should re-open this and fix it.

**Comment by kuthair** [comment]
I can't believe this is Closed.

This is a defect. It's completely unusable on Mac without changing it.
