### ISSUE TITLE
Nightly autoupdates are not getting installed

### ISSUE THREAD

**Issue by npezza93** [atom/atom#19350]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Hey there! Ever since about 1.39.0-nightly1 whenever a new nightly version is downloaded and "Restart & Install" is clicked, atom reboots, but the version doesnt get updated and it re downloads the new version. 

### Steps to Reproduce

1. Download 1.39.0-nightly4
2. Try auto updating to 1.39.0-nightly5

**Expected behavior:** After restarting upon installation the new version should be installed

**Actual behavior:** The old version stays installed

**Reproduces how often:** 100%

### Versions

Atom    : 1.39.0-nightly4
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

macOS 10.14.5

**Comment by rsese** [comment]
Thanks for the report!  I had 1.39.0-nightly3 installed on macOS 10.12.6 and tried to update - got to the point where I could restart to install but it was still at 1.39.0-nightly3 when Atom restarted.  I just installed 1.39.0-nightly5 directly, and 1.39.0-nightly6 should be available shortly, let's see if there's any issues with that update.

**Comment by npezza93** [comment]
Hey @rsese, seeing the same behavior on 5 when I try to go to 6.

**Comment by rsese** [comment]
Hmm, me too, thanks for checking :+1:

**Comment by akonwi** [comment]
I'm also seeing this. I've been installing manually

**Comment by rsese** [comment]
I was on `1.39.0-nightly10` and see that updating to `1.39.0-nightly11` worked ok just now - can anyone else confirm if updating from `1.39.0-nightly10` to `1.39.0-nightly11` works for them?

**Comment by npezza93** [comment]
@rsese Yep! Just went from 9 to 11 and had no issue!
