### ISSUE TITLE
Packages view cannot be opened on Ubuntu

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19367]
### Description

`apm` is not executable by users on linux. This makes the package installer tab on the settings view unusable.

### Steps to Reproduce

1. Open Atom nightly on Ubuntu.
2. Go to the "package" tab on the settings page.

**Expected behavior:** See all installed packages.

**Actual behavior:** An error appears on the dev console and the package tab stays in a loading state.

**Reproduces how often:** 100% of times

### Versions

Atom v1.39-nightly-9

It cannot be reproduced on Atom v1.38-beta0.

### Additional Information

When checking the contents of the `apm` bin folder, both the `apm` and the `npm` executables can only be read and executed by root:

```sh
atomuser@ubuntu:~$ ls -al /usr/share/atom-dev/resources/app/apm/bin/
total 34408
drwxr-xr-x  2 root root     4096 May 20 04:09 .
drwxr-xr-x 10 root root     4096 May 20 04:09 ..
-r-x------  1 root root     1457 May 17 04:37 apm
-rw-r--r--  1 root root      796 May 17 04:37 apm.cmd
-r-x------  1 root root     1457 May 20 03:40 apm-ori
-rwxr-xr-x  1 root root 35200878 May 17 04:37 node
-r-x------  1 root root      955 May 17 04:37 npm
```

**Comment by rafeca** [comment]
@50Wliu this is probably caused by https://github.com/atom/apm/pull/847, which is resetting the original permissions of both files and making them readable and executable by only the owner (which for linux it seems to be `root`).

Can you change the permissions to be something like `0o755`?

**Comment by 50Wliu** [comment]
Yeah, of course.

**Comment by rafeca** [comment]
Thanks for taking care of this! 😍
