### ISSUE TITLE
Investigate faster CI builds

### ISSUE THREAD

**Issue by as-cii** [atom/atom#19366]
As of today, testing out a change on CI approximately takes 50-60 minutes. Not only this introduces major friction in the feedback loop of the development process, but it is also source of slowdowns when a new version of Atom needs to be published. This is made worse by some flaky tests, which e.g. may cause us to wait multiple hours before publishing an important hotfix.

## Caching

Related: #19326 

After transitioning to Azure Pipelines as our CI provider, we lost an essential functionality for a project like Atom: caching. Our dependencies don't change that often, and when they do, only a small part of them gets updated/removed. [On any given build](https://dev.azure.com/github/Atom/_build/results?buildId=40844), we have to wait approximately 15-20 minutes (~ 30-50% of our build times) to setup dependencies and generate a snapshot script. 

<img width="1054" alt="Screen Shot 2019-05-20 at 10 02 21" src="https://user-images.githubusercontent.com/482957/58005755-af158280-7ae6-11e9-9e93-e87e4bcf9a7e.png">

Even though it seems like official support for caching hasn't yet been added to Azure Pipelines (apparently, it is [slated for 2019 Q2](https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1458319)), I discovered [an extension](https://github.com/microsoft/azure-pipelines-artifact-caching-tasks) (developed by Microsoft) that, if installed, claims to enable caching for arbitrary artifacts.

While it may not be fully baked yet, I would be inclined to try it out and see whether it makes a difference on this repository.

## Testing

Atom's test suite is quite thorough, and we even run tests against the latest bundled version of core packages to catch unwanted API changes. Having an extensive set of test is valuable, but every test contributes to a slower build.

<img width="1054" alt="Screen Shot 2019-05-20 at 10 02 21" src="https://user-images.githubusercontent.com/482957/58006339-239cf100-7ae8-11e9-9d47-ede770983501.png">

The above screenshot captures how long it takes to run main-process, renderer-process and package tests on macOS. On platforms like Windows x64, this time drops to 15 minutes because we simply don't run package tests there.

A simple solution to this could be to take advantage of the pipeline infrastructure offered by Azure. We could build Atom once on macOS and, in parallel, run two sub-jobs, each taking care of running main/renderer-process tests and package tests, respectively. This would dramatically decrease variance within an individual build, as macOS and Windows would roughly take the same amount of time to bootstrap and run tests.

Moreover, if we're willing to increase the granularity of our build, we could split package/renderer tests into further sub-jobs and increase parallelism even more. This would require a few minor changes to `script/test` but, alongside caching, could lead to builds that take ~5 minutes.

## Final Remarks

I believe this work would be worth doing for a number of reasons:

- Reduced friction while we're trying to publish a new Atom version.
- Decreased time between opening a pull request and merging it.
- Flaky tests would become easier to fix. We could test "fix hypotheses" much more quickly.
- Addressing caching and parallelism shouldn't require a lot of engineering effort.

/cc: @atom/maintainers for 👀 and 💭

**Comment by rafeca** [comment]
Thanks for writing this up! Both ideas are great!

This initiative is one of the things that will allow people to do these small improvements that [get killed by the friction](https://overreacted.io/fix-like-no-ones-watching/).

Regarding parallelisation of tasks, we'll need to increase our current number of maximum parallel jobs that can be run by Azure: [it's currently set to 10](https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops#microsoft-hosted-cicd) and that's going to quickly become a bottleneck (it already is during peak hours where several PRs/commits need to be built).

**Comment by asheren** [comment]
> This would require a few minor changes to script/test but, alongside caching, could lead to builds that take ~5 minutes.
This would be truly incredible and would definitely lead to more developer productivity for us and our volunteer maintainer/contributors. 

I saw a few different options for going about this in the testing section. Because this extension isn't fully baked, do you have a sense of what sort of level of effort is needed to try this out for either option? And at what points (either by amount of time or work completed) will be good places to pause and determine "move forward" vs. "wait for this to ship in Q2"?

**Comment by as-cii** [comment]
With respect to the caching extension, based on their README, it seems like enabling it on our repository shouldn't take more than 4-5 days. I expect to be able to validate whether this approach would work at all or not in 1 or 2 days. Ideally, it would take even less than that but I am expecting slow feedback loops, as it always is when experimenting with CI. 

As for the testing optimization, I think we should start out by running core and package tests simultaneously on macOS. I don't expect major problems with this optimization, so I am hoping it will take 3-4 days (this may depend on what @rafeca pointed out in https://github.com/atom/atom/issues/19366#issuecomment-493967810, as we need to contact Microsoft to increase our limits). If we can do that and the caching extension works, I would expect our builds to take ~15 minutes (27% of what they take today).

Based on everything we'll learn as part of those two steps, we could then take a step back and decide whether we want to invest some extra engineering time to cut the build time down even further.

**Comment by rafeca** [comment]
@as-cii the builds have got much faster now thanks to the caching of node_modules and the parallelization of builds, can we close this one?

**Comment by as-cii** [comment]
I think so, thanks for the heads-up.
