### ISSUE TITLE
Needs to use openat() with gvfs so that stale but remounted connections work.

### ISSUE THREAD

**Issue by shawnl** [atom/atom#19379]
### Description

If you try to save to a file over gvfs where the connection has been closed, and the remounted it reports a fuse error. This is because it is holding a state file handle, instead of using openat() and letting the kernel traverse the directories each time. Sometimes you would want the functionality where it holds on to the fds, but in this case I do not want that.

### Steps to Reproduce

1. Open a file on GNOME from over gvfs to a ssh host (sftp)
2. disconnect the sftp connection
3. reconnect the sftp connection
3. try to save a file

**Expected behavior:**
works

**Actual behavior:**
can't save over socket

**Reproduces how often:**
100%

### Versions

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.37.0
python 2.7.16
git 2.20.1

Ubuntu disco x86_64

**Comment by rsese** [comment]
Sorry for the delay and thanks for the report -

> can't save over socket

Are you getting a specific error or does Atom crash?

> * disconnect the sftp connection
> * reconnect the sftp connection

If Atom is crashing and based on these steps, this sounds like https://github.com/atom/atom/issues/10271?

**Comment by shawnl** [comment]
I switched to vscode over this (which works unlike most editors, but there is also a multiple round trips problem with FUSE, which they are trying to get people to use proprietary limited code to address)
