### ISSUE TITLE
[PACKAGE DETECTED AS MALWARE] simple-drag-drop-text

### ISSUE THREAD

**Issue by aurora-of-earth** [atom/atom#19381]
The atom package <a href="https://atom.io/packages/simple-drag-drop-text">simple-drag-drop-text</a> is detected as malware by the <a href="https://www.drweb.com/">Dr.Web<a/> antivirus.

<pre>
Threat: JS.DownLoader.1080 ‌
Isolated: 08/05/2019 13:12
Quarantine type: User
Object name: jquery.js
Owner: aurora
Modified: 08/05/2019 13:12
Size: 251.51 KB
Origin path:
/home/aurora/.atom/packages/simple-drag-drop-text/node_modules/jquery/dist/jquery.js
</pre>

- <a href="https://vms.drweb.com/search/?q=JS.DownLoader.1080">vms.drweb.com/search/?q=JS.DownLoader.1080</a>

However the <a href="https://virusdesk.kaspersky.com/">Kaspersky VirusDesk</a> showed no results.

**Comment by Arcanemagus** [comment]
The package lives up to the "simple" part of its name, with nothing suspicious in the [tiny bit of code](https://github.com/geoffthibeau/simple-drag-drop-text/blob/v0.4.0/lib/simple-drag-drop-text.coffee) that makes up the package.

This sounds like a false positive from your AV vendor, an unfortunately common problem.

Thanks for contributing!

**Comment by aurora-of-earth** [comment]
@Arcanemagus When I looked closer, I've found the malicious file was not part of this package at all, but of the dependencies.
The root cause was actually jQuery JavaScript Library v2.2.4.
I've reinstalled the package and just rescanned the suspected file but no issue was found!
I don't know, maybe another program injected something into that directory; I hope not.
