### ISSUE TITLE
Atom UI discolourisation

### ISSUE THREAD

**Issue by Jirubizu** [atom/atom#19394]
### Description

The UI especially main code window has a colour mismatch, certain parts are darker than others but if my cursur is on a certain line that whole block will be lighter. I have attached a screenshot as it is hard for me to describe what is happening. I have also ran atom in safe mode but the issue persists
EDIT: This happens with any type of theme I use
### Versions
OS: Ubuntu 18.04.2 LTS
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.37.0
python 2.7.15rc1
git 2.17.1
### Additional Information
[Photo](http://i.imgur.com/CAJ3KjG.png)

**Comment by Arcanemagus** [comment]
Does forcing sRGB rendering work around the issue for you? You can enable this by changing Settings -> Color Profile to `Use sRGB color profile`.

This is likely a bug in the underlying Chromium version that will be fixed in a future upgrade of Electron in Atom.

**Comment by Jirubizu** [comment]
You are a god thank you so much, It fixed. Hope there will be an update to chromium soon as even though its not hard to fix it shouldn't be there to begin with but its not atoms fault ^^

**Comment by Arcanemagus** [comment]
Thanks for reporting back, I'm glad to hear that worked for you.

I'll go ahead and mark this closed since it's not something we can fix here 😉.
