### ISSUE TITLE
Bad {} Match

### ISSUE THREAD

**Issue by materia-cccp** [atom/atom#19409]
### Prerequisites

* [] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. The following C++ Code
```cpp
#include<bits/stdc++.h>
#define rep(i,a,b) for(int i=a;i<=b;i++)
#define op return
using namespace std;
typedef long long int ll;
const ll maxn=405,xrj=1e9+7;
inline ll su(ll x){op(x*(x+1))/2;}
int n,q;
ll cc[maxn],dd[maxn];
ll ss[maxn][maxn];
ll dp[2][maxn][maxn],dp2[maxn][maxn];
void wrk(int l,int r,int pos){
    //cout<<l<<" "<<r<<" "<<pos<<" "<<cc[pos]<<endl;
    rep(i,l,r)rep(j,i,r)dp[0][i][j]=(i==l&&j==r);
    int p=0;
    rep(k,1,q){
        p^=1;
        rep(i,l,r){
            ll tmp=0;
            for(int j=r;j>=i;j--){
                dp[p][i][j]=tmp;(tmp+=dp[p^1][i][j]*(n-j))%=xrj;}
        }
        rep(i,l,r)dd[i]=0;
        rep(i,l,r)rep(j,i,r){
            (dp[p][i][j]+=dd[j])%=xrj;
            (dd[j]+=dp[p^1][i][j]*(i-1))%=xrj;
        }
        rep(i,l,r)rep(j,i,r)(dp[p][i][j]+=dp[p^1][i][j]*ss[i][j])%=xrj;
    }
    rep(i,l,r){
        ll tmp=0;
        for(int j=r;j>=i;j--){
            (tmp+=dp[p][i][j])%=xrj;(dp2[j][cc[pos]]+=tmp)%=xrj;
            //cout<<i<<" "<<j<<" "<<tmp<<" "<<dp2[j][cc[pos]]<<endl;;
            }}
}
struct no{ll a;ll b;}aa[maxn];
bool operator<(no a,no b){return a.a<b.a;}
ll ee[maxn];
int main(){
    cin>>n>>q;
    rep(i,1,n){cin>>aa[i].a;;aa[i].b=i;ee[i]=aa[i].a;}
    sort(aa+1,aa+n+1);
    rep(i,1,n)cc[aa[i].b]=i;
    rep(i,1,n)rep(j,i,n)ss[i][j]=su(i-1)+su(n-j)+su(j-i+1);
    rep(i,1,n){
        int l=i,r=i;
        while(l>1&&ee[l-1]<ee[i])l--;
        while(r<n&&ee[r+1]<ee[i])r++;
        wrk(l,r,i);
    }
    //rep(i,1,n){rep(j,i+1,n)cout<<dp[0][i][j]<<","<<dp[1][i][j]<<" ";;cout<<endl;}
    //rep(i,1,n){rep(j,i+1,n)cout<<dp2[i][j]<<" ";;cout<<endl;}
    rep(i,1,n){
        ll tmp=0,ans=0;
        rep(j,1,n)if(dp2[i][j]){
            (dp2[i][j]+=xrj-tmp)%=xrj;
            (ans+=dp2[i][j]*ee[aa[j].b])%=xrj;
            (tmp+=dp2[i][j])%=xrj;
        }
        printf("%lld ",ans);
    }
    op 0;}
```

(The code is correct and can pass compilation) 

**Expected behavior:** 

"}" on line 36 is supposed to match with "{" on line 12
"}" on line 29 is supposed to match with "{" on line 16
"}" on line 27 is supposed to match with "{" on line 24

**Actual behavior:** "
"}" on line 36 doesn't match anything.
"}" on line 29 is matches with "{" on line 12
"}" on line 27 is matches with "{" on line 16

**Reproduces how often:** 100%

### Versions

Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
OS: MacOS Mojave 10.14

### Additional Information

Tested in safe mode, with every third-party package disabled.

**Comment by Arcanemagus** [comment]
I'm unable to reproduce this using Atom v1.39.0-nightly9 (using [swackets](https://atom.io/packages/swackets) to show matches):
![image](https://user-images.githubusercontent.com/427137/58498075-1e682380-8132-11e9-94eb-0558eff77e0f.png)

There have been [a few updates](https://github.com/atom/language-c/compare/v0.60.14...v0.60.17) to `language-c` as well as [improvements](https://github.com/tree-sitter/tree-sitter-cpp/compare/v0.13.13...v0.13.15) to the underlying `tree-sitter-cpp`. It's possible one of those already fixed this since v1.37.0 was branched off.

In the future note that language issues like this should generally be filed in their respective repositories.

Thanks for taking the time to file an issue!
