### ISSUE TITLE
Session is not restored (multiple instances; using ATOM_HOME)

### ISSUE THREAD

**Issue by Andrade** [atom/atom#19425]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I opened one instance of Atom by clicking the icon. This works well and state is restored if I reopen the window. This state is kept in standard location at `~/.atom`.

While having that first window opened I tried opening a second instance/window with `$ ATOM_HOME=~/.atomnb atom`. The goal is having a second window of atom with different packages and panes layout, themes, etc.

I modified this second window, opened a project and some tabs. Then closed it and reopened running again the same command: `$ ATOM_HOME=~/.atomnb atom`.

The window appears again showing the correct theme and settings. The previously opened project is also there. However, the opened tabs are now gone and the project layout (e.g. panes) and window dimensions appear to have been forgotten.

In the dev tools console I see the error `Could not connect to indexedDB`.

### Steps to Reproduce

1. Open Atom normally via icon. (This is Window 1.)
2. Open Atom via terminal with `$ ATOM_HOME=~/.atomnb atom` (This is Window 2.)
3. Open a project in Window 2
4. Open some tabs in Window 2 from the project
5. Change the dimensions and layout of the panes.
6. Close Window 2.
7. Reopen Window 2 with the same command: `$ ATOM_HOME=~/.atomnb atom`
8. The project is still there, but the panes' layout and tabs are not restored.

**Expected behavior:** Panes' layout and tabs should have been restored.

**Actual behavior:** The session appears to have been lost, although the project folder is still in the tree view.

**Reproduces how often:** Always.

### Versions

OS: Ubuntu 18.04. Atom installed from snap.

```
$ atom --version
$ apm --version
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.37.0
python 2.7.15rc1
git 2.17.1
```

### Additional Information

The issue is with Window 2. Note I open Window 1 first using the Atom icon and leave it open.

Window 1 functions as expected, it is the state of Window 2 (opened via terminal) that is not restored.

#### Update

I tried the same steps in a different machine (Ubuntu 16.04, Atom 1.32.0) and the same thing happens.

I'm wondering if the IndexDB location is shared by all instances and that prevents Window 2 from working properly. I say this because while I have two different locations for settings (`~/.atom` and `.atomV2`) the IndexDB location is the same in both cases.

In the second machine:

1. Open Window 1: `ATOM_HOME=~/.atom atom` (session restored OK)
2. Open Window 2: `ATOM_HOME=~/.atomV2 atom` (session NOT restored)
3. Close Window 1 and Window 2.
4. Open Window 2: `ATOM_HOME=~/.atomV2 atom` (session restored OK)
5. Open Window 1: `ATOM_HOME=~/.atom atom` (session NOT restored)
6. Close Window 1 and Window 2. Repeat to obtain consistent result. Essentially it appears only one window at a time is capable of showing its state restored, never both. However, the state is not lost; simply not shown.

**Comment by rsese** [comment]
Thanks for the report!   Before looking further:

> OS: Ubuntu 18.04. Atom installed from snap.

The Snap install of Atom is unofficial - please install Atom using one of the supported installation methods:

https://flight-manual.atom.io/getting-started/sections/installing-atom/

You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You still might have the same issue but we need to eliminate the possibility that the unofficial installation method is part of the issue.

If you can still reproduce using an supported installation method, go ahead and open a new issue and we'll take a look.
