### ISSUE TITLE
"Open link" does not work if different line is selected

### ISSUE THREAD

**Issue by wesinator** [atom/atom#19422]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

"Open link" does nothing if the cursor is on a different line than the link

### Steps to Reproduce

1. Open file containing URL highlighted
2. Set cursor on line after URL
3. Right click URL, "Open link"

**Expected behavior:** opens link

**Actual behavior:** nothing happens

**Reproduces how often:** always

### Versions

macOS 10.14.5
```
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.37.0
python 2.7.10
git 2.20.1
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by rsese** [comment]
Thanks again for reporting :+1:

I double checked and this is expected behavior since the cursor is on a different line per your step (2) and not on the link itself.  From the README of the Link package https://github.com/atom/atom/tree/master/packages/link#link-package:

> Opens http(s) links under the cursor.

**Comment by wesinator** [comment]
Ok - could it be changed to hide the menu item when the cursor is on a
different line ?
