### ISSUE TITLE
go to line changes scroll even if the target line is already in view

### ISSUE THREAD

**Issue by dwiel** [atom/atom#19467]
### Description

When using the `go to line` functionality, atom occasionally scrolls the buffer to move the target line towards the bottom of the window. I can understand if this is done when the target line is not currently visible and so the buffer needs to be scrolled to make it visible. But this occurs even if the line is already visible.

### Steps to Reproduce

1. Open buffer with 231 lines
2. Change zoom/window size so that 126 lines are visible
3. go to line 1
4. go to line 199
5. go to line 135

**Expected behavior:** on step 5, line 135 is already well in view, no scrolling is necessary after going to that line.

**Actual behavior:** on step 5, the buffer is scrolled unnecessarily.

**Reproduces how often:** this particular buffer size/window size/line number combination reliably reproduces the problem, however slight modifications result in different behavior. For example:

1. Open buffer with 231 lines
2. Change zoom/window size so that 126 lines are visible
3. go to line 1
4. go to line 231
5. go to line 135

In this case, the window buffer scroll positions up until step 5 are exactly the same as the first example, but the jump to line 135 doesn't scroll the buffer in that case.

### Versions

```
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
OS X: 10.14.4 (18E226)
```

**Comment by dwiel** [comment]
Another particularly bad case:

1. Buffer with 211 lines
2. 126 lines visible
3. go to line 211 (lines 86 - 121 now visible)
4. go to line 126 which is around the center of the window, but still, the buffer is scrolled so that line 126 is at the very bottom of the window.

**Comment by rsese** [comment]
Thanks for the report - can you share a GIF/screencast of the behavior you see?  Just want to make sure I see what you're describing.  Also do you have repro steps that don't need as many lines visible on the screen?

**Comment by dwiel** [comment]
It looks like the behavior is partially modified by the speed of the keypresses. Using typical keyboard speed (as opposed to keypresses automatically generated by software) the behavior is a little bit different than described above. Here is a video: https://youtu.be/Vuj7LIilpCc

**Comment by utkarsh-dixit** [comment]
I'd like to working on a PR for this issue.
