### ISSUE TITLE
Flaky build: test on the `markdown-preview` package times out

### ISSUE THREAD

**Issue by rafeca** [atom/atom#19477]
Sometimes builds end up failing with a test failure on the `markdown-preview` package:

```
Markdown Preview
  when a preview has been created for the file
    when a new grammar is loaded
      it Markdown Preview when a preview has been created for the file when a new grammar is loaded re-renders the preview
        timeout: timed out after 60000 msec waiting for markdown to be rendered after grammar was added
```

Rebuilding can sometimes resolve the failure.

---

**Affected CI provider(s)**: Azure DevOps

**Affected platform(s)**: macOS

**Example commit experiencing flakiness**: https://github.com/atom/atom/commit/faa36949d94ad919364f852faf1cb9d9464c10f9

**Example failing build at that commit**: https://github.visualstudio.com/Atom/_build/results?buildId=42644
**Example passing build at that commit**: https://dev.azure.com/github/Atom/_build/results?buildId=42640

**Comment by rafeca** [comment]
The first failure of this test happened in https://github.visualstudio.com/Atom/_build/results?buildId=42546, just when https://github.com/atom/atom/pull/19457 got merged.

It's unlikely that https://github.com/atom/atom/pull/19457 is the root cause of this: it seems like that the changes in that PR have surfaced a latent race condition or existing problem in that test.

**Comment by nathansobo** [comment]
I decided to just delete this test in https://github.com/atom/markdown-preview/commit/9f6a33e1b1e0e86b3def9a82f2a1f80040f1610c.
