### ISSUE TITLE
Scroll Position is lost in child element

### ISSUE THREAD

**Issue by wadethestealth** [atom/atom#19473]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Added child elements to the active text editor lose their scrollTop property when they are scrolled out of view.

Hydrogen a popular atom package adds a React Component inline to the text editor to view results from external code execution through jupyter kernels.

This React Component contains a standard div element (not an immediate child but down the sub tree) that if their is enough output can scroll.

If you scroll inside of the element and then scroll down the text editor for it to fall out of view and be temporarily removed from the DOM. If you scroll back up that scroll position inside the element is lost.

### Steps to Reproduce

1. Have hydrogen active and setup properly
2. Use `Run Cell` command from hydrogen on the code below with about 50 extra new lines
```
for i in range(1000):
    print(i)
```
3. Scroll down the editor
4. Scroll back up the editor

**Expected behavior:** Everything to look the same

**Actual behavior:** Scroll top of the result view has been set to 0 upon removal and adding back to the active DOM

**Reproduces how often:** 100% of the time

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

### Additional Information

This isnt platform specific either, and I don't believe its a hydrogen problem.
I  believe this is a problem with how etch processes the render of React Components or how it stores html nodes when removing them. But I understand its more complex than that.

Hydrogen issue nteract/hydrogen#785

**Comment by rsese** [comment]
Thanks for the report - it sounds like you think this isn't specific to Hydrogen, would it be possible to share a minimal example to reproduce that doesn't use Hydrogen?  Also I scanned the issue that you referenced and I see in https://github.com/nteract/hydrogen/issues/785#issuecomment-308277334, it's mentioned that they think it's "most likely a little bug in hydrogen".  Is that comment just outdated at this point (or was just a hunch at the time) and y'all believe it's an Atom issue?

**Comment by wadethestealth** [comment]
@rsese I will provide you with a sample, but the thread is very old. I did my own test and debugging and was inspecting via react dev tools and element view to observe both react and element properties. the view contains no state so I believe it's etch related. Once I can give you a smaller test case I could probably prove it.
