### ISSUE TITLE
Crash when opening files with .py suffix

### ISSUE THREAD

**Issue by GregoryREvans** [atom/atom#19495]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

With newest update, the window crashes when opening any file with a `.py` suffix.

### Steps to Reproduce

1. Open project folder with atom by dragging and dropping
2. Click on python file within folder

**Expected behavior:** Opens file to be able to be edited.

**Actual behavior:** Application crashes

**Reproduces how often:** Happens every time I try to open a python file. But other file suffixes such as `.scd` open as expected.

### Versions

Atom    : 1.38.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.0
python 3.6.5
git 2.10.1

Mac OSX 10.11

### Additional Information

N/A

**Comment by Arcanemagus** [comment]
Have you tried [Safe Mode](https://flight-manual.atom.io/faq/sections/what-does-safe-mode-do/) to verify this isn't a third party package you have installed?

**Comment by GregoryREvans** [comment]
Yes, problem persists in safe mode. Sorry, I guess I didn't check the box.

**Comment by rsese** [comment]
> * Open project folder with atom by dragging and dropping

Hmm, are you opening the same project every time?

If you create a new directory and put a `test.py` file in it (e.g. that just prints "hello world"), does that cause a crash if you open that project and open the test file?

**Comment by GregoryREvans** [comment]
I've tried on several different directories and on isolated files in many different locations on my machine. If a file is on the desktop is either dragged to the atom icon *or* double clicked to open in atom the following file extensions work:`.md`, `.txt`, `.scd`, `.java`, `.pl`

while the following file extensions crash the application: `.py`, `.cc`, `.C`, `.cxx`, `.c++`, `.rs`, `.rb`,  `.js`, 

I have tried vanilla atom, atom beta, I have tried reinstalling atom, I have tried safe mode, I have manually deactivated all plugins. Interestingly, the `.pl` extension opens a directory tree in atom's sidebar when double clicked, while no other file extension I tried did this.

**Comment by Aerijo** [comment]
> the following file extensions work:.md, .txt, .scd, .java, .pl

> while the following file extensions crash the application: .py, .cc, .C, .cxx, .c++, .rs, .rb, .js,

Looks like a Tree-sitter issue.

**Comment by oomcreative** [comment]
Having same issues as @GregoryREvans - and same config - just tried Core > Use Tree-sitter off- and can now load .js file. All good, but then switch Use Tree-sitter on again and it crashes, hope that helps.

**Comment by GregoryREvans** [comment]
@Aerijo I can confirm that what @oomcreative happens to me as well. Files open with Tree-sitter off and crash again with it on.

**Comment by chaoxu95** [comment]
> @Aerijo I can confirm that what said @oomcreative happens to me as well. Files open with Tree-sitter off and crash again with it on.

I also encounter the same problem. But when I disable the 'language-python' package, the error disappear. But I can not use python by atom.

**Comment by rsese** [comment]
> Mac OSX 10.11

...

> Looks like a Tree-sitter issue.

> Does toggling off Settings > Core > Use Tree-sitter Parsers stop the crashing?


Ahhh it looks like this is the same issue reported in https://github.com/atom/atom/issues/19497 where it was tracked down to versions of macOS prior to 10.12.  See this comment for more details: https://github.com/atom/atom/issues/19497#issuecomment-501311338.  The workaround for now as mentioned there is to temporarily disable Tree-sitter as @Aerijo also suggested.

Since we're using https://github.com/atom/atom/issues/19497 to track the investigation, we'll close in favor of that issue if you want to subscribe there for updates.
