### ISSUE TITLE
"Restart and install" closes and updates Atom but doesn't restart on Windows

### ISSUE THREAD

**Issue by kaiyoma** [atom/atom#19493]
### Steps to Reproduce
1. Wait for Atom to report that an app update is available.
2. Click the button to restart and install the update.
3. Wait forever.

**Expected behavior:**
Atom should restart.

**Actual behavior:**
Nothing. Atom never starts again.

**Reproduces how often:**
100% of the time when an app update is available.

### Versions
OS: Windows 10

```
$ atom --version

Atom    : 1.38.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

```
$ apm --version
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at EventEmitter.<anonymous> (...\atom\app-1.38.0\resources\app\apm\lib\apm-cli.js:169:17)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by rsese** [comment]
> Nothing. Atom never starts again.

Just to clarify, Atom is updated to the new version when you start Atom manually, it just doesn't restart on it's own after you click the update button?

**Comment by kaiyoma** [comment]
Then why does it say "Restart and install"?

**Comment by Aerijo** [comment]
@kaiyoma He is asking you if that is the case, not saying it is expected.

**Comment by rsese** [comment]
Yeah I just want to make sure I know exactly what happens since I think there's an open issue that describes this behavior.  I need to figure out what to keep open, close, etc.

**Comment by kaiyoma** [comment]
Yes, I think we're all in agreement. The page says "Restart and install" (or something very similar, I'll have to take a screenshot next time), so when I click the button, that's what I expect to happen.

What actually happens: Atom shuts down and that's it. When I manually start Atom again, the version is indeed updated.
