### ISSUE TITLE
Menu bar not visible when using Ubuntu 19.04 Yaru theme

### ISSUE THREAD

**Issue by ytx21cn** [atom/atom#19496]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. In Ubuntu 19.04, set the system UI theme to be Yaru
2. Open Atom editor

**Expected behavior:** The menu bar should be using white text color

**Actual behavior:** The menu bar uses black color instead on a black background, thus totally unreadable

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
1.37.0 x64

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
![Screenshot from 2019-06-11 17-34-38](https://user-images.githubusercontent.com/5900105/59315650-76914080-8c6f-11e9-82d8-1bdce9c969eb.png)
![Screenshot from 2019-06-11 17-32-33](https://user-images.githubusercontent.com/5900105/59315653-7abd5e00-8c6f-11e9-99be-6375a7f10bd4.png)

**Comment by Arcanemagus** [comment]
Do you still see this if you [disable GPU rendering](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem)?

**Comment by rsese** [comment]
If that ☝️ doesn't help, I also wonder if you're hitting https://github.com/atom/atom/issues/18535?  Can you try the 1.39 beta and see how things look there?

**Comment by ytx21cn** [comment]
> Do you still see this if you [disable GPU rendering](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem)?

Yes, problem still exists.

**Comment by Arcanemagus** [comment]
> Can you try the 1.39 beta and see how things look there?

One more thing to try 😉

**Comment by klvenky** [comment]
It's working 1.39.beta2 it's mentioned in #18535 thanks guys :)

**Comment by g0m3z78** [comment]
Same issue for me with Atom 1.38 on a fresh default Ubuntu 19.04 install. After checking the 1.39 beta2 the menu bar appears properly.

**Comment by ytx21cn** [comment]
Working in 1.39
![Screenshot from 2019-08-10 16-49-45](https://user-images.githubusercontent.com/5900105/62827899-fca60680-bb8e-11e9-89b3-27a4db801a67.png)
