### ISSUE TITLE
Flaky test: Project .onDidChangeFiles() reports filesystem changes within project paths

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#19507]
[This test](https://github.com/atom/atom/blob/afabe007c1228c1ebed03174941bbd109820f1f6/spec/project-spec.js#L1083-L1110) sometimes fails:

```
Project
  .onDidChangeFiles()
    it Project .onDidChangeFiles() reports filesystem changes within project paths
      timeout: timed out after 60000 msec waiting for promise to be resolved or rejected
```

Rebuilding usually resolves the failure.

---

**Example failing build**: https://github.visualstudio.com/Atom/_build/results?buildId=42865&view=logs&jobId=4fbced83-508e-5fe0-c978-5c71ec0fc506&taskId=8ab1786f-98fc-5bc4-a8d0-c08e0675c13a&lineStart=2419&lineEnd=2422&colStart=1&colEnd=89

**Comment by jasonrudolph** [comment]
Another one: https://github.visualstudio.com/Atom/_build/results?buildId=42869&view=logs&jobId=4fbced83-508e-5fe0-c978-5c71ec0fc506&taskId=8ab1786f-98fc-5bc4-a8d0-c08e0675c13a&lineStart=2419&lineEnd=2420&colStart=1&colEnd=1

**Comment by Arcanemagus** [comment]
Another one: https://github.visualstudio.com/Atom/_build/results?buildId=42909&view=logs&jobId=4fbced83-508e-5fe0-c978-5c71ec0fc506&taskId=8ab1786f-98fc-5bc4-a8d0-c08e0675c13a&lineStart=2420&lineEnd=2424&colStart=1&colEnd=1

**Comment by jasonrudolph** [comment]
Another one:

https://github.visualstudio.com/Atom/_build/results?buildId=42918&view=logs&jobId=4fbced83-508e-5fe0-c978-5c71ec0fc506&taskId=8ab1786f-98fc-5bc4-a8d0-c08e0675c13a&lineStart=2419&lineEnd=2420&colStart=1&colEnd=1

**Comment by jasonrudolph** [comment]
We're one step closer to figuring out this flake. The test includes 3 promises, and at first, it wasn't clear which promise was failing to resolve. @as-cii and I pushed up [a build with some debugging logic](https://github.visualstudio.com/Atom/_build/results?buildId=43072&view=logs&jobId=4fbced83-508e-5fe0-c978-5c71ec0fc506&taskId=8ab1786f-98fc-5bc4-a8d0-c08e0675c13a&lineStart=439&lineEnd=444&colStart=1&colEnd=1) in it, and we have isolated the problem to this part of the test:

https://github.com/atom/atom/blob/c947c8005aff1de0586a757684158c1cef051efb/spec/project-spec.js#L1108
