### ISSUE TITLE
Atom UI is blurry when moving mouse.

### ISSUE THREAD

**Issue by ReolSt** [atom/atom#19510]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When I clicked Atom editor tab and move mouse randomly or scroll at other window Atom UI was blurry. i've tried different solutions (e.g., "--disable-gpu" or "--safe" or changing nvidial control panel antialiasing options) but It still happened.

![Imgur](https://i.imgur.com/AIPBgqk.png)
![Imgur](https://i.imgur.com/XHcoJ8J.png)

### Steps to Reproduce

1. Open editor tab on Atom.
2. Open other window(e.g., firefox, emacs, hyper, etc.)
3. move mouse at any window including Atom window or scroll at other window.

### Versions

Atom : 1.38.0
Electron : 2.0.18
Chrome : 61.0.3163.100
Node : 8.9.3

Windows 10 x64
Ryzen 3 1200
GTX 1060
DDR4 ram 8GB

### Additional Information
I used "auto hide menu bar"
my plugin list
- emacs emulation
- Markdown preview
- Power mode
- platformio-ide-terminal
- language support plugins

I didn't open program having tray icon without nvidial control panel and Realtek HD Audio Manager
I didn't use wallpaper engine.
my gpu usage was under 3%.
It is very strange that I can't reproduce this. I didn't make any changes at my system.

**Comment by rsese** [comment]
Thanks for the report - just to confirm, if you've used previous versions of Atom is this behavior new for you as of 1.38.0 or you've seen it in previous versions of Atom?

**Comment by ReolSt** [comment]
> 
> 
> Thanks for the report - just to confirm, if you've used previous versions of Atom is this behavior new for you as of 1.38.0 or you've seen it in previous versions of Atom?

When I saw your reply, I tried to reproduce that symptom but It is strange that that doesn't occured.
I'm trying to reproduce now and I will come back if I find out exact reproducing process.

**Comment by rsese** [comment]
Oh interesting, thanks for the update :+1:  I'll go ahead and tag this as `more-information-needed` again so it will close over time if you end up not seeing this again and we don't hear back from you.

**Comment by nnnyan** [comment]
Here is a relevant issue:
electron/electron#13646
