### ISSUE TITLE
Flaky test: AtomApplication command-line interface behavior: atom:// URLs with a "core" host sends a URI message to the most recently focused non-spec window that owns the open locations

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#19512]
[This test](https://github.com/atom/atom/blob/898c12fe21ad35015793f6b1479cf18713f349ba/spec/main-process/atom-application.test.js#L674-L693) sometimes fails:

```
  1) AtomApplication command-line interface behavior atom:// URLs with a "core" host sends a URI message to the most recently focused non-spec window that owns the open locations:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

Rebuilding usually resolves the failure.

---

**Affected CI provider(s)**: Travis CI, Azure Pipelines

**Affected platform(s)**: Linux

**Example failing build**: https://github.visualstudio.com/Atom/_build/results?buildId=42903&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=6c939d89-0d1a-51f2-8b30-091a7a82e98c&lineStart=270&lineEnd=277&colStart=4&colEnd=1

**Comment by jasonrudolph** [comment]
A couple more occurrences:

- https://github.visualstudio.com/Atom/_build/results?buildId=42869&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=6c939d89-0d1a-51f2-8b30-091a7a82e98c&lineStart=273&lineEnd=275&colStart=1&colEnd=1

- https://travis-ci.org/atom/atom/builds/544693739#L939

**Comment by jasonrudolph** [comment]
Another one:

https://github.visualstudio.com/Atom/_build/results?buildId=42930&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=3367cfe7-6aa5-5a88-c888-e6814d74f6eb&lineStart=273&lineEnd=274&colStart=1&colEnd=1

**Comment by rafeca** [comment]
Another one: https://dev.azure.com/github/Atom/_build/results?buildId=43038
