### ISSUE TITLE
Setting font size to 14 doesn't persist and has unexpected behaviour on `window:reset-font-size`

### ISSUE THREAD

**Issue by Songworks** [atom/atom#19521]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I got the following behaviour starting with Atom 1.38.x.
When I set the font size as 14 (which is the default), the setting doesn't persist beyond restart and when executing `window:reset-font-size` it sets font size to whatever was previously set by first executed command of either `window:increase-font-size` or `window:decrease-font-size`.

### Steps to Reproduce

If I set the font size as 14 and restart Atom, font size appears as empty (renders placeholder: *Default: 14*), I then get the following two different behaviour depending on the steps:

* Increase font-size with `window:increase-font-size`
* Reset font-size with `window:reset-font-size`
* Result: Font size is now set to `15`

Another result:

* Decrease font-size with `window:decrease-font-size`
* Reset font-size with `window:reset-font-size`
* Result: Font size is now set to `13`

Additional if it Atom already knows a previous font size (like the 13 or 15), `window:reset-font-size` will keep using this font size, even if the user enters another font size manually, fe. 16.

**Expected behavior:** Should be able to manually enter font size 14 and `window:reset-font-size` should reset to whatever was the last manually entered font size

**Actual behavior:** Manually setting font size 14 doesn't persist and `window:reset-font-size` sets font size to whatever was previously known or last used by/in Atom

**Reproduces how often:** 100%

### Versions
Atom    : 1.38.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.1
python 2.7.12
git 2.21.0

OS: Linux Mint 17.3 (Ubuntu 16.04 based)

### Additional Information

Perhaps related to this pull request?
https://github.com/atom/atom/pull/19192

Cheers!

**Comment by Songworks** [comment]
@nathansobo Issue is resolved with 1.38.2 for me. Thanks for the fast work!

**Comment by dirtyarteaga** [comment]
:construction_worker:
