### ISSUE TITLE
Welcome Guide keeps opening up

### ISSUE THREAD

**Issue by crysxd** [atom/atom#19547]
[Enter steps to reproduce:]

1. Install Atom
2. Open Atom
3. Untick "Show welcome guide when opening Atom"
4. Close all welcome panes
5. Close Atom
6. Open Atom
7. Welcome guide shows up again

**Atom**: 1.38.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**:  /

### Non-Core Packages

```
atom-beautify 0.33.4 
build 0.70.0 
busy-signal 2.0.1 
rest-client 1.3.1 
```

The welcome panes keep showing on every startup. This is extremely annoying. I also tried disabling the welcome package, but it is enables again on every start. Also disabling the checkbox in the welcome package's settings does not help, this checkbox as well as the checkbox on the welcome page itself is ticked again every time Atom is started.

**Comment by rsese** [comment]
> I also tried disabling the welcome package, but it is enables again on every start.

Hmm it sounds like none of your settings changes are saving?  For example, if you uncheck `Audio Beep` from the Settings View (<kbd>Ctrl-,</kbd>), does that change save after you restart?

And do you see any error in [devtools console](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools) after you uncheck the checkbox or make any other settings changes?

Lastly, it looks like the `Prerequisites` section was removed - did you see the same behavior in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by crysxd** [comment]
You are actually right. I went ahead and changed the theme in the settings and restarted Atom. The theme was again the old one. 

I checked the console and there are no logs, neither when opening nor when changing a settings. Running in safe mode makes no difference. I started Atom in safe mode, unticked the "show welcome" box, closed the window and started again in safe mode. Result is the same (box ticked again).

I need to mention that Atom was not starting anymore a couple weeks ago. I had to remove the compile cache as described [here](https://github.com/atom/settings-view/issues/992).

**Comment by Arcanemagus** [comment]
It sounds like you have permissions issues on the folders Atom needs to access, are you running in a enterprise environment that could potentially be using roaming profiles? Do other applications have issues like this?

**Comment by crysxd** [comment]
No, it's personal PC with Windows 10. Nothing special. And Atom definitely did run without issues before as I used it a lot. I'd just go ahead and remove the entire installation and try to reinstall.

**Comment by crysxd** [comment]
I deleted the entire folder and installed Atom again. This seems to have fixed the issue. I inspected the access rights of the .atom folder before deleting it and everything seemed normal. Would be interesting to know why there was nothing in the logs if writing the settings to disk failed.

Thanks for your help!

**Comment by rsese** [comment]
Oh great :+1:  I also wonder what the issue was, kinda surprised there wasn't an error in console.  I wonder if starting Atom in the foreground would have shown any useful messages (`atom -f`).  In any case, glad you have things sorted out.
