### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setEncoding' of undefined

### ISSUE THREAD

**Issue by robertavram-md** [atom/atom#19542]
[Enter steps to reproduce:]

1.  Open large (>130 mb) csv file
2.  Set encoding to UTF-8
3. Export the large CSV file
4. This error shows up but export works fine

**Atom**: 1.38.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.15
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'setEncoding' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

TypeError: Cannot read property 'setEncoding' of undefined
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:719698)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:871741)
    at SelectListView.didClickItem (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:869683)
    at ListItemView.onclick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:868673)
    at ListItemView.didClick (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:872761)
```

### Commands

```
     -0:57.6.0 core:save-as (input.hidden-input)
     -0:18.5.0 encoding-selector:show (atom-text-editor.editor)
  3x -0:18.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-sombre-theme.theme-atom-dark-ui)
     -0:18.4.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-sombre-theme.theme-atom-dark-ui)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
compare-files 0.8.1 
gtk-dark-theme 0.1.4 
Hydrogen 2.8.0 
indent-guide-improved 1.4.13 
jackhammer-syntax 1.1.0 
pretty-json 2.0.3 
sombre-theme 1.0.0 
```

**Comment by rsese** [comment]
Thanks for the report!  

> * Open large (>130 mb) csv file
> * Set encoding to UTF-8
> * Export the large CSV file
> * This error shows up but export works fine

Can you clarify what you mean in step 3?  Are you using a community package for that functionality?  
 Can you confirm if the error is reproducible in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
