### ISSUE TITLE
Settings randomly reset after restarting Atom

### ISSUE THREAD

**Issue by xavierfoucrier** [atom/atom#19572]
### Description

Sometimes the editor **completely reset the configuration file** `config.cson` after reboot. This is happening since version 1.30+.

I also noticed that the `userId` field inside the configuration file is changing every times this issue occurs, but I am always working with the same user account... don't know if it is related.

### Steps to Reproduce

1. Difficult to reproduce because it is random

*Edit by @rsese to add comment from https://github.com/atom/atom/issues/19572#issuecomment-503748126*

> I mean, rebooting the app: shutting down with the close button at the top-right, then start Atom again a few seconds later. No packages updates, no Atom core updates. Just close+open. Since I am working with the light theme, I know when the issue is happening.

**Expected behavior:**

Keep the configuration untouched.

**Actual behavior:**

The configuration is lost, theme is changed.
Hopefully I have a backed up my configuration and I can restore it on the fly...

**Reproduces how often:**

Once or twice a week, randomly.

### Versions

**Atom**
Atom    : 1.37.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**APM**
apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.37.0
python
git 2.18.0.windows.1
visual studio 2015

### Additional Information

Windows 7 SP1 x64

**Comment by rsese** [comment]
Thanks for opening a new issue for this @xavierfoucrier -

> Sometimes the editor **completely reset the configuration file** `config.cson` after reboot. This is happening since version 1.30+.

When you say "reboot", do you mean your computer or after restarting Atom?  Do you remember any other details before your settings are reset?  For example, are you updating Atom to a new version or updating installed packages?

And can you share your list of community packages (`apm list --installed`)?

x-ref: https://github.com/atom/atom/issues/14909

**Comment by xavierfoucrier** [comment]
Hi @rsese,

Thanks for your fast answer first!

I mean, rebooting the app: shutting down with the close button at the top-right, then start Atom again a few seconds later. No packages updates, no Atom core updates. Just close+open. Since I am working with the light theme, I know when the issue is happening.

Here is the list of Atom packages:
├── atom-soft-tabs-length@0.5.2
├── busy-signal@2.0.1
├── caniuse@1.0.0
├── editorconfig@2.4.0
├── es6-javascript@1.0.0
├── intentions@1.1.5
├── language-htaccess@0.2.0
├── language-ini@1.21.0
├── less-autocompile@1.0.0 (disabled)
├── linter@2.3.0
├── linter-eslint@8.5.5
├── linter-lesshint@6.0.2 (disabled)
├── linter-stylelint@4.4.8
├── linter-ui-default@1.7.1
└── terminal-tab@0.5.7

Hope this help :wink:

**Comment by rsese** [comment]
Thanks @xavierfoucrier - if this happens again and you come across more information or steps to reproduce consistently, please let us know.

**Comment by rsese** [comment]
Ahh sorry - as I looked back more at the issues around this, I see we have an open issue about settings getting wiped relatedly with some of the community packages you have installed: 
 https://github.com/atom/atom/issues/17060

See the "Additional Information" section of the issue in particular.

Since that issue is still open, I'm going to go ahead and tentatively close in favor of that issue and you can subscribe there for updates if you'd like.

**Comment by xavierfoucrier** [comment]
Thanks for your feedback @rsese, don't know if it is package related, not sure since I am using all the same package since the beginning... but let see the investigation on the other issue. :wink:
