### ISSUE TITLE
Weird color Python subclasses in One Theme

### ISSUE THREAD

**Issue by silentsokolov** [atom/atom#19588]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

After the [RR language-python#298](https://github.com/atom/language-python/pull/298) a python subclasses are displayed weird color. They are color like string. This is confusing.

### Steps to Reproduce

1. Open Atom
2. Write python class with subclass

**Expected behavior:**

![266d3bf764](https://user-images.githubusercontent.com/398939/60003495-7e8bb000-9673-11e9-80ac-6a58150f425e.jpg)

**Actual behavior:**

Subclasses must be of any other color ...

### Versions

Atom 1.38.2
MacOS 10.13.6

**Comment by rsese** [comment]
Thanks for the report!  Can you share your example so we can copy/paste?  And just to clarify, you only see this issue with the One themes and not other themes yes?

**Comment by silentsokolov** [comment]
I think the color of subclasses changed in all themes. The target of PR is highlight subclasses. But in at moment in One theme the color of subclasses same the color of string and this is make difficult reading code.

```python
from mixins import TestMixin
from module import models, validators, _


class Push(TestMixin, models.Model):
    field1 = models.OneToOneField('test.ClassTest', on_delete=models.CASCADE,
                                  related_name='like')
    percent = models.PositiveSmallIntegerField(validators=[validators.MaxValueValidator(100)])

    class Meta:
        verbose_name = _('test')
        verbose_name_plural = _('tests')

    def __str__(self):
        return str(self.field1.name)
```
