### ISSUE TITLE
Atom menus in ubuntu 13.10 are cut off or don't show

### ISSUE THREAD

**Issue by batista** [atom/atom#1959]
The top menus are being cut off. This means that I click on the menus and no menu rolls down, but the menu bar still displays the hovering effect as it should.

![ubuntu-no-menus](https://cloud.githubusercontent.com/assets/976915/2895600/d564dc7c-d561-11e3-8662-ec243bf51a61.gif)

This is a recurrent issue with some applications on ubuntu, the more common one is the eclipse issue. check: http://askubuntu.com/questions/361040/eclipse-menus-are-cut-off-or-dont-show

a quick fix for this is to run from the command line every time that you want to run atom:
```shell
$ UBUNTU_MENUPROXY= atom
```
OS details: Ubuntu 13.10 x64

---
EDIT: Added the screenshot

**Comment by mnquintana** [comment]
Can anyone reproduce this with the latest version of Atom (0.210.0)?

**Comment by mnquintana** [comment]
I'm going to close this out - feel free to comment if you still experience this with the latest version of Atom (1.2.0) and I'll reopen this.

**Comment by darrenleeweber** [comment]
Still see it on atom 1.8.0
```sh
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_CODENAME=vivid
DISTRIB_DESCRIPTION="Ubuntu 15.04"
```

Running ubuntu as a guest on OSX 10.10.5 using VirtualBox 5.0.24

**Comment by darrenleeweber** [comment]
It works fine after turning off the VirtualBox 3D acceleration.

**Comment by darrenleeweber** [comment]
Still see hidden menu drop-downs for Ubuntu 16.04 guest on VirtualBox 5.1.2 with 3D acceleration on (and working fine on other apps):
```
$ atom --version
Atom    : 1.9.4
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ unity --version
unity 7.4.0
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```
