### ISSUE TITLE
Create issue button not working: ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by yha** [atom/atom#19596]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

"Create issue on atom/atom" button does not work

### Steps to Reproduce

1. Produce an error, e.g. (atom/tree-view#1282):
  1a. create a file with a comma in its name
  1b. drag it in the tree view to a different folder
2. In the dialog that opens, click "Create issue on atom/atom" 

No browser window is opened. Console (ctrl+shift+i) shows two new errors:
```
POST https://is.gd/create.php?format=simple net::ERR_INSECURE_RESPONSE
```
and
```
Uncaught (in promise) TypeError: Error processing argument at index 0, conversion failure from null
    at C:\Users\sternlab\AppData\Local\atom\app-1.38.2\resources\app\static\<embedded>:11:905732
    at <anonymous>
```

**Reproduces how often:**

Always

### Versions

Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
Windows 10

**Comment by rsese** [comment]
Thanks for the report!  I was unable to reproduce just now with 1.38.2 on Windows 10.  Can you still reproduce now?  I wonder if it was just a temporary issue with that URL shortening service.

**Comment by yha** [comment]
Yes, still reproduces.
I also remember having this issue before (or at least, the same button not working), on the same machine, which then had Windows 7.

**Comment by rsese** [comment]
hmm, do you see the same error if you visit the site in Chrome?

**Comment by yha** [comment]
Visiting the URL mentioned in the error (`https://is.gd/create.php?format=simple`) in chrome gives

> Your connection is not private
> Attackers might be trying to steal your information from is.gd (for example, passwords, messages, or credit cards). Learn more
> NET::ERR_CERT_COMMON_NAME_INVALID
> 

and under the "advanced" button:
> This server could not prove that it is is.gd; its security certificate is from *.technion.ac.il. 
> This may be caused by a misconfiguration or an attacker intercepting your connection.

technion.ac.il is the local domain where the machine is, so I guess this might be a firewall issue?  
A `ping is.gd` also yields a reply from inside that domain.
