### ISSUE TITLE
Cannot enter chinese character after pressing Backspace

### ISSUE THREAD

**Issue by nyaachen** [atom/atom#19619]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

After pressing Backspace to delete characters, chances are that the Chinese IME will be unable to input words, which only appears in atom.

### Steps to Reproduce

1. open atom with any text editing window
2. using a Chinese IME, for example, the Microsoft Pinyin IME
3. type "ceshi" and press the space bar so possibley you get the word 测试
4. press Backspace so the second character is deleted only a 测 is left
5. try to type "ceshi" again

**Expected behavior:**

You can type another "ceshi" 测试

**Actual behavior:**

It is possible that you typed out "eshi" and it becomes 俄式 in my IME.
That is, the first character c was eaten by program.
Another situation is that more characters was eaten

**Reproduces how often:**

Sometimes.

### Versions
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 3.7.3
git 2.21.0.windows.1
visual studio

OS: Windows 10 Professional 64bit 1803
 
### Additional Information

The RIME IME produce this almost every time.
The Microsoft IME have a chance to produce this, but after it was produced, this happened more often.
As we do not delete words so often than typing, this may be rarely found.
I also consider it a possible problem of RIME IME or the Microsoft input system. So I also opened an issue in RIME IME [here](https://github.com/rime/weasel/issues/398).

**Comment by rsese** [comment]
Thanks for the report!  I think this may be a duplicate of https://github.com/atom/atom/issues/18439 - since you can reproduce very consistently with RIME IME, if it's not too much trouble, would you mind seeing if you can reproduce with Atom [1.19.0](https://github.com/atom/atom/releases/tag/v1.19.0)?

I found in https://github.com/atom/atom/issues/18439#issuecomment-438924696 that the issue reported there started in 1.20.0 but worked ok in 1.19.0.  If you can't reproduce with 1.19.0, then I think we can close in favor of https://github.com/atom/atom/issues/18439.

**Comment by nyaachen** [comment]
I checked ver 1.19.0 although it is buggy when dealing with Microsoft Pinyin IME it did work normally.
Thank you for the suggestion about this.
