### ISSUE TITLE
Settings -> Install page fails to open

### ISSUE THREAD

**Issue by joshupetersen** [atom/atom#19610]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Install does not work when on fresh install under WSL/Ubuntu/VcXsrv/LXDE

### Steps to Reproduce

1. Install Atom under WSL/Ubuntu/VcXsrv/LXDE environment

Can navigate to Install page of settings

Cannot navigate to install page of settings, error thrown

100% of the time

### Versions

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 18.04.2
**Thrown From**: Atom Core

### Additional Information

Error: 

Given:
1.Run WSL (Windows Serving Linux) with Ubuntu using VcXsrv (portable version)
3. Run LXDE
4. Fresh Install of Atom
5. Go to Settings
6. Click Install
Expected:
Package install page appears
Actual:
Error flashes, and install page is not navigated to.

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /opt/atom/resources/app/node_modules/settings-view/lib/install-panel.js:385

TypeError: undefined is not a function
    at InstallPanel.addPackageViews (/opt/atom/resources/app/node_modules/settings-view/lib/install-panel.js:385:30)
    at /opt/atom/resources/app/node_modules/settings-view/lib/install-panel.js:456:26
    at /opt/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:68:26
    at AtomIoClient.module.exports.AtomIoClient.fetchFromCache (/opt/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:159:22)
    at AtomIoClient.module.exports.AtomIoClient.featuredPackages (/opt/atom/resources/app/node_modules/settings-view/lib/atom-io-client.js:65:25)
    at InstallPanel.loadFeaturedPackages (/opt/atom/resources/app/node_modules/settings-view/lib/install-panel.js:450:27)
    at new InstallPanel (/opt/atom/resources/app/node_modules/settings-view/lib/install-panel.js:124:16)
    at /opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:247:22
    at SettingsView.getOrCreatePanel (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at HTMLDivElement.clickHandler (/opt/atom/resources/app/node_modules/settings-view/lib/settings-view.js:190:24)
```

### Commands
Click +INSTALL in the settings menu

### Non-Core Packages

None

**Comment by Arcanemagus** [comment]
> Atom: 1.26.1 x64

This is a _very_ old version of Atom, do you still see this when using the current stable version?

_Note: This looks to have been filed once before under https://github.com/atom/atom/issues/17732, but the previous reporter gave no information._

**Comment by joshupetersen** [comment]
#17732 was closed due to inactivity and instructed opening a new issue, hence this issue. As far installing the latest version, it reports as the most recent version in each repository I find, and WSL/Ubuntu/VcXsrv/LXDE doesn't seem to like gui package managers.

**Comment by joshupetersen** [comment]
With updated version of atom... stll errors, however, at least _navigates_ to the Install Packages page, however, displays the following error, 

```
Fetching featured packages failed.

/usr/share/atom/resources/app/apm/bin/apm: line 63: /usr/share/atom/resources/app/apm/bin/node.exe: No such file or directory"
```

**Comment by danikiev** [comment]
> 
> 
> With updated version of atom... stll errors, however, at least _navigates_ to the Install Packages page, however, displays the following error,
> 
> ```
> Fetching featured packages failed.
> 
> /usr/share/atom/resources/app/apm/bin/apm: line 63: /usr/share/atom/resources/app/apm/bin/node.exe: No such file or directory"
> ```

This can be solved:
https://github.com/atom/apm/issues/751
