### ISSUE TITLE
regarding google drive + atom

### ISSUE THREAD

**Issue by vainaijr** [atom/atom#19613]
how to directly access google drive files in atom, without having to download them to my local machine?

**Comment by Arcanemagus** [comment]
Thanks for the submission!

That would definitely be useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for Atom core. For that reason, I'm going to close this.

If you are using a GApps Suite account (Work or School) you should be able to contact your administrator about Drive File Stream which handles this automatically for you. If you have a consumer Google account there are third party solutions that can emulate this functionality.

This could also be implemented as an Atom package, although it would likely be quite the undertaking. If you need help building this as a package, please check out the [Atom Flight Manual section on publishing your own packages](https://flight-manual.atom.io) and feel free to ask any questions you have on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the Atom Slack team.

Thanks again for contributing to Atom :+1:
