### ISSUE TITLE
language detection detects JavaServer Pages instead of shell

### ISSUE THREAD

**Issue by frederik-b** [atom/atom#19629]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
create new file with the following content:
```
#!/usr/bin/env bash
set -eu
# shellcheck source=./colors
. "$(cd -P -- "$(dirname -- "$0")" && pwd -P)/colors"
```
file name is `colors` (no extension)
2. 
open the file in atom

**Expected behavior:**

The language detection should detect `Shell Script`

**Actual behavior:**
The language detection detects `JavaServer Pages`

**Reproduces how often:**
every time, over two dozens of files

about a tenth of all my script files
### Versions
```
$ atom --version
Atom    : 1.32.1
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
$ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.1
python 2.7.16
git 2.21.0
```

**Comment by rsese** [comment]
Thanks for the report - I'm unable to reproduce with 1.38.2 on macOS 10.12.6:

> Atom    : 1.32.1

Please update to the latest stable version of Atom and let us know if you can reproduce in safe mode?
