### ISSUE TITLE
RPM Installer missing icon

### ISSUE THREAD

**Issue by asdf23** [atom/atom#19626]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

After installing atom on Fedora 30 via an rpm file i can see that the appropiate menu and icons are present except from the run command. If I install some other thing I do see this icon only atom seems to have this problem.

### Steps to Reproduce
Alt+F2 , type "atom" , look at icon preview. Icon is not there.

**Expected behavior:**
See icon

**Actual behavior:**
No icon

**Reproduces how often:**
Everytime

### Versions
$  atom --version
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

Fedora Core 30

**Comment by rsese** [comment]
Thanks for the report - trying to get my Fedora VM up and running but just to confirm, the .rpm you used is from https://atom.io correct?

Also, did you just notice this in 1.38.2 and the icon was there previously?

**Comment by asdf23** [comment]
Yes from atom, yes 1.38.2, previous icon..? Sorry do not know this.

**Comment by rsese** [comment]
> previous icon..? Sorry do not know this.

Sorry, I meant to ask if you've used versions of Atom before 1.38.2?  And if so, did the icon show up?

Also, can you share more details about this?

> Alt+F2 , type "atom" , look at icon preview. Icon is not there.

I haven't run programs like that before, can you clarify what preview icon you're referring to?  Can you share a screenshot of what another program looks like vs. Atom?

**Comment by asdf23** [comment]
I am sorry I do not know. I don't think rpm was available when last I
installed or, might have been a repo add rather than a download, dnf
install. I may have also fixed this myself, not sure. Sorry

**Comment by rsese** [comment]
> I may have also fixed this myself, not sure. Sorry

No problem - so it sounds like you're no longer seeing this issue?  We'll go ahead and close for now but if you think this is still an issue let me know.
