### ISSUE TITLE
Horizontal scroll margin seems broken

### ISSUE THREAD

**Issue by AxelJunker** [atom/atom#19635]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I'm trying to set the horizontal scroll margin to something else than its default (6).
### Steps to Reproduce

I tried this in my init.coffee:

```
atom.workspace.observeTextEditors (editor) ->
    editor.setHorizontalScrollMargin(1)
    console.log(editor.getHorizontalScrollMargin())
```

**Expected behavior:**
The console.log should print 1

**Actual behavior:**
It prints NaN

**Reproduces how often:**

### Versions
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
MacOS: 10.14.3

**Comment by lee-dohm** [comment]
If you execute the following in the JavaScript Console with an editor open:

```
editor = atom.workspace.getActiveTextEditor()
editor.setHorizontalScrollMargin(1)
```

the value that is returned is `1`, showing that the value was properly set. There may, however, be a bug in `editor.getHorizontalScrollMargin()` but that shouldn't block you from your stated goal.

**Comment by AxelJunker** [comment]
@lee-dohm Sorry if I wasn't clear enough. I tried what you suggested, and the `setHorizontalScrollMargin` returns 1, but the margin is still 6 (or more than 1) when I try it in the editor. This is what I'm trying to prevent by setting the horizontalScrollMargin:

![horizontal](https://user-images.githubusercontent.com/17730345/60705582-c928ea00-9f07-11e9-9940-f27224553179.gif)

**Comment by lee-dohm** [comment]
It would be helpful if you could track down where things are going wrong. Perhaps you could try looking for where `getHorizontalScrollMargin` is called? Or how the implementation of that function (or the functions and properties it depends on) has changed since the the version prior to v1.34.0?
