### ISSUE TITLE
Atom is crashing on my Mac

### ISSUE THREAD

**Issue by DWinterfell** [atom/atom#19642]
Hello I am on a MacBook Pro (13-inch, Early 2011) running 10.12.6 (16G2016) and I have downloaded the latest version of atom - "atom-mac.zip" v.1.38.2.  Every time I go to run atom, it crashes now.  I have basically tried almost everything to get it to run, but it still crashes.

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by 1170300812** [comment]
If you can tell me what measures you have taken, I may be able to help you.

**Comment by tothpeter** [comment]
I’ve experienced a crash as well on osx with the following message:

```
The editor has crashed

Please report this issue to https://github.com/atom/atom
```

In my case:
Safe mode worked.
I suspect the atom ctags plugin caused the crash. The problem disappeared into thin air after removing the `.tags` file from the project folder I tried to open with atom. You can regenerate it with the `Atom Ctags: Rebuild` command from the command plate.

**Comment by Arcanemagus** [comment]
@DWinterfell Can you please try [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), as requested in the template?

**Comment by DWinterfell** [comment]
Welp, when I am in terminal, I type 'atom' and it doesn't recognize 'atom' as a command.  Even though I  have the application installed in my applications folder, terminal is not seeing this command.

**Comment by Aerijo** [comment]
@DWinterfell On mac you need to install the shell commands through Atom the first time.

To simulate safe mode, try renaming the `~/.atom` folder to something else.

**Comment by uzibutt** [comment]
i read a lot of stuff and i found that the way of writing to clarifying that exactly want to say was very good so i am impressed. <a href="http://mixedthought.com/what-are-the-minimally-invasive-surgical-procedures-and-how-it-works/">orthopedic surgeon salary 2018</a>

**Comment by uzibutt** [comment]
i am also facing the same issue please some body help me.<a href="https://drwajiddd.livejournal.com/479.html ">Fire-resistant fabric</a>
