### ISSUE TITLE
Vietnamese language display error with some specific chars.

### ISSUE THREAD

**Issue by pierreneter** [atom/atom#19641]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

A few Vietnamese chars have display issues although the font has support Vietnamese.

### Steps to Reproduce

1. Open `atom`
2. New file
3. Type or paste: `ế, ề, ể, ồ, ể, ề, ở, ...` and type `è é, ẽ, ư, ô, ê, ừ, ứ, ...` to compare.

<img width="504" alt="Screen Shot 2019-07-07 at 7 23 39 AM" src="https://user-images.githubusercontent.com/12815768/60762357-2f3c7b00-a088-11e9-8ce6-089d3cea1685.png">

**Expected behavior:**

Show normally

**Actual behavior:**

Text displayed as font errors.

**Reproduces how often:**

Always.

### Versions

```
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

### Additional Information

Nothing.

**Comment by rsese** [comment]
Thanks for the report -

> 3\. Type or paste: `ế, ề, ể, ồ, ể, ề, ở, ...` and type `è é, ẽ, ư, ô, ê, ừ, ứ, ...` to compare.

Just to clarify, that second set of characters (`è é, ẽ, ư, ô, ê, ừ, ứ, ...`) will be displayed incorrectly only when typed but will look ok if you copy/paste them? 

> the font has support Vietnamese.

Which font are you using?

**Comment by duythanhvn** [comment]
Hi rsese,

I have the same problem. This issue always displays data entry or copy/paste content. I use the default Atom font information.

Kindly regards,
Thanh Doan

**Comment by pierreneter** [comment]
> Thanks for the report -
> 
> > 3. Type or paste: `ế, ề, ể, ồ, ể, ề, ở, ...` and type `è é, ẽ, ư, ô, ê, ừ, ứ, ...` to compare.
> 
> Just to clarify, that second set of characters (`è é, ẽ, ư, ô, ê, ừ, ứ, ...`) will be displayed incorrectly only when typed but will look ok if you copy/paste them?
> 
> > the font has support Vietnamese.
> 
> Which font are you using?

default font, which your OS?

**Comment by rsese** [comment]
> default font, which your OS?

I'm on macOS 10.14.

Also I looked at your screenshot again - just to clarify, the display error you're talking about is the fact that the 2 lines look like they're using different fonts yes?

**Comment by pierreneter** [comment]
> > default font, which your OS?
> 
> I'm on macOS 10.14.
> 
> Also I looked at your screenshot again - just to clarify, the display error you're talking about is the fact that the 2 lines look like they're using different fonts yes?

You can reproduce by yourself with your device and feel for yourself, don't ask silly questions anymore.
I think it still the same font but line 2 have the height is shrinking.

**Comment by rsese** [comment]
@pierreneter - we're just trying to understand the issue as best we can so we can help so we need to ask questions; please keep the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) in mind when commenting.

> I think it still the same font but line 2 have the height is shrinking.

Following this: https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-font-rendering-issues

It looks like they're 2 different fonts on line 1:

![line-1](https://user-images.githubusercontent.com/734194/62072029-5f98b480-b203-11e9-81b2-37efe5c46f60.png)

Vs. line 2:

![line-2](https://user-images.githubusercontent.com/734194/62072043-66272c00-b203-11e9-98d7-ca3d3d3cdd98.png)

I tried the 2 lines of text in VS Code and see they seem consistent; looking in devtools there, it looks like they have "Monaco" in their font stack and it shows up in the Rendered Fonts along with Menlo vs. in Atom where we saw it was Menlo and Courier New.  If I update `Settings > Editor > Font Family` to add "Monaco" before "monospace" at the end (`Menlo, Consolas, DejaVu Sans Mono, Monacao, monospace`) I now see this which looks a lot more consistent:

![with-monaco](https://user-images.githubusercontent.com/734194/62072372-201e9800-b204-11e9-9bb7-06fce061b786.png)
