### ISSUE TITLE
Incorrect keyboard shortcut for file renaming on macOS

### ISSUE THREAD

**Issue by oskarkrawczyk** [atom/atom#19650]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Incorrect keyboard shortcut for file renaming on macOS. While the one to actually rename is open for discussion, it's definitely not `F2`, like on Windows.

<img width="429" alt="Screen Shot 2019-07-09 at 16 01 01" src="https://user-images.githubusercontent.com/34213/60894539-32d82980-a263-11e9-81fc-1fd546532cb0.png">

**Reproduces how often:**

Always

### Versions

1.38.2

**Comment by alfonsocv12** [comment]
it could be r, i think with the touchbar its wors on the normal old keyboard was not that bad

**Comment by rsese** [comment]
Thanks for the feedback!   I know this has come up before but I can't find the link right now; as far as I know, at this point we're not changing existing defaults unless there's a pressing reason to do so.  In addition to <kbd>F2</kbd>, we also have <kbd>m</kbd> for renaming files (looks like <kbd>F2</kbd> was added later across all platforms).  Or someone could add a [keybinding](https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/) for whatever they'd like for rename in the tree view.

If someone wanted to change what's shown on the popup menu on macOS, adding a keybinding would also replace what's shown on the menu e.g.:

```cson
'.tree-view':
  'r': 'tree-view:move'
```

Going to close this out but thanks again for the feedback and I'll mention this to the other maintainers in case I'm mis-remembering anything about this.
