### ISSUE TITLE
Line count is not visible

### ISSUE THREAD

**Issue by eithan1231** [atom/atom#19652]
### Description

When editing any file, regardless of syntax highlighting, themes, and plugins, some line counts don't get displayed. It appears to alternate the displaying every 30 lines. Sorry for the broad description, but there really isn't much to be described.

### Steps to Reproduce

1. Open atom
2. Edit a text file

**Expected behavior:**

Edit a text file with all line counts on the left side of the editor.

**Actual behavior:**

Edit a text file with missing line-counts on the left side of the editor.

**Reproduces how often:**

This bug occurs every time I load Atom.

### Versions

Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3
Operating System: Windows 10 Pro - 10.0.17134

### Additional Information

Here's a video of what I mean by the bug. My text description isn't helpful, I figure a video may be more insightful.

https://www.youtube.com/watch?v=guguHZfUyK4

Again, sorry for the broad description of everything. It's just hard to describe the issue.

**Comment by Arcanemagus** [comment]
The template isn't just there for fun, it contains some important first steps 😉.

Are you able to reproduce this in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
Have you tried [Disabling GPU rendering](https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-your-gpu-is-causing-the-problem)?

**Comment by eithan1231** [comment]
Yes I know the template contained important steps. I tried safemode, I read the FAQ's, and checked if there was already an issue. I didn't entirely follow the debugging section, just the first several steps.

Also, I just tried and disabled GPU rendering. It appears to have fixed it, though this isn't a permanent fix.  I get that this may not be a problem directly associated with Atom, but can you point me in the direction to possibly fix this issue? I got the latest drivers on the latest build of windows. Ideas?

**Comment by Arcanemagus** [comment]
Do you see the same behavior on the beta branch? There's a major upgrade to the version of Electron (the framework Atom runs on) available for testing, one of the many improvements coming from that is updated GPU handling.

**Comment by eithan1231** [comment]
Ill take a look later, thanks. I will close this thread now. If your beta solution doesn't work, ill just run it with disable gpu mode from a shortcut or something. But anyway, thanks!
