### ISSUE TITLE
Final atom binary requires root/sudo to launch

### ISSUE THREAD

**Issue by superlinkx** [atom/atom#1965]
After running the grunt install task, I have a working atom binary, but it requires root/sudo to launch. Fixing the permissions on /usr/local/bin/atom to be executable by all causes atom-shell to launch without the atom editor.

**Comment by Moter8** [comment]
Any update on this issue? Does it still happen with ~ 0.169.0?

**Comment by krngrvr09** [comment]
Still happening in Ubuntu 14.04 and atom version ``1.0.2-9432598``.
