### ISSUE TITLE
Java 8 projects built with 11 now

### ISSUE THREAD

**Issue by kjluyr435** [atom/atom#19661]
Hi, my builds here [www.diplomaclub.net](https://www.diplomaclub.net)
are still "failing", because even though it's a java 8 project, it's being compiled by java 10 or 11, and setting the flag: --release 8 doesn't seem to work.
Any way to compile with JDK 8 on jitpack now?

**Comment by lee-dohm** [comment]
Atom doesn't build or compile code by itself, it's a text editor. If you're using some sort of package that allows you to build or compile Java code within Atom, you should reach out to the maintainers of that package for assistance.
