### ISSUE TITLE
Uninstall on Windows asks for admin permissions

### ISSUE THREAD

**Issue by yha** [atom/atom#19663]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom can be installed without admin privileges, so uninstall should not ask for admin password either.

### Steps to Reproduce

1. Go to Windows 10's "Apps&Features"
2. Find Atom and click "Uninstall"

**Expected behavior:**

Uninstall

**Actual behavior:**

Requests admin password

**Reproduces how often:**

Always

### Versions

Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by rsese** [comment]
Thanks for the report -

> * Go to Windows 10's "Apps&Features"

I'm guessing you don't see the UAC prompt if you uninstall from `Programs and Features`?

Based on https://github.com/Squirrel/Squirrel.Windows/issues/1209, Squirrel (the installer framework we use) doesn't need admin permission to uninstall and this is likely an issue with Windows when uninstalling from `Apps & Features`.
