### ISSUE TITLE
Launching atom from wsl2 command line

### ISSUE THREAD

**Issue by tj84** [atom/atom#19686]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Trying to launch atom from the WSL2 (windows subsystem on linux) command line throws an error: bad interpreter: no such file or directory.

### Steps to Reproduce

1. Launch WSL2 (currently running Ubuntu 18.04 LTS but applies to all)
2. type command atom "hello_world.txt"
3. error message in command line and atom doesn't launch
### Versions

Occurs on all versions of Atom running on WSL2. Currently running atom v 1.39.0 beta 3

### Fix:

It appears that Microsoft has changed how the command "uname -r" reports the version of windows from the from *-Microsoft to *-microsoft-standard (note the lower m in Microsoft). To fix this need to change the following file: atom\app-1.39.0-beta3\resources\cli\atom.sh from:
  if [[ $(uname -r) == *-Microsoft ]]; then
to
  if [[ $(uname -r) == *-microsoft-* ]]; then

and comment out the line:
eval $(grep "^root" /etc/wsl.conf | sed -e "s/ //g")

you will also need to re-save the file: 
\atom\bin\atom in LF (unix) line ending format rather than CRLF (windows line ending)

Atom should then launch in wsl2

**Comment by lee-dohm** [comment]
We don't generally make changes to Atom for pre-release versions of OS components since they're likely to change again before release. Any hint on when WSL2 will be fully released?
