### ISSUE TITLE
Request; File size in the tree view next to file names

### ISSUE THREAD

**Issue by arkid** [atom/atom#19683]
Something I miss from other editors is the file size listed next to the file names in the tree view.  I've looked for packages that can add this but can't find one.

**Comment by Arcanemagus** [comment]
Thanks for the submission!

That would definitely be useful in some people's workflows. However, it is not something that the Atom team will currently take on. For that reason, I'm going to close this. It sounds like a great idea for an Atom package though. If you need help building this as a package, please check out the [Atom Flight Manual section on publishing your own packages](https://flight-manual.atom.io) and feel free to ask any questions you have on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the Atom Slack team.

Thanks again for contributing to Atom :+1:
