### ISSUE TITLE
Crashing of Editor on windows 8.1

### ISSUE THREAD

**Issue by Prashant1102** [atom/atom#19685]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by Prashant1102** [comment]
The Editor I have Installed and after the first use it started crashing .
When i open it in 15sec it crashed every time 
How to fix that?

**Comment by Prashant1102** [comment]
![Crashed](https://user-images.githubusercontent.com/52916888/61588990-ba0d9180-abc1-11e9-89c7-eba0598bc147.PNG)

This is screnshot of the crashed Editor

**Comment by rsese** [comment]
Thanks for the report - if you can share more details and the information asked for in the issue template, we can definitely take a look with you:

* Though it sounds like this is a fresh install, did you try starting in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* What specific version of Atom are you running?
* Are you opening any particular project/directory when you start Atom?

**Comment by lyndenbow** [comment]
Hi,

I am having the same issue on Windows 8.1...started happening about 3 days ago. Also crashes when starting in safe mode. When selecting 'Debug' i get this break message 

Unhandled exception at 0x00007FF906A61CD0 (ntdll.dll) in atom.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FF906A9ED40)

**Comment by rsese** [comment]
@lyndenbow - was this also a fresh install of Atom?   Also:

* What specific version of Atom are you running?
* Are you opening any particular project/directory when you start Atom?

**Comment by Prashant1102** [comment]
I am using latest version of atom.
And before opening any project it's crashing.

**Comment by Prashant1102** [comment]
And when I am opening any project like p5.js for live server it crashed.

**Comment by joaopedroraldi** [comment]
It was not happening before last update.
Packages i use (to compare with others):
Bracket Matcher
Command Palette
Config Import Export
Dev Live Reload
Emmet
Ftp-Remote
Highlight Selected
Keybinding Resolver
Markdown Preview
Minimap
Package Generator
Settings View
Snippets
Spell Check
Styleguide
Symbols
Timecop
Tree View
Whitespace

**Comment by rsese** [comment]
> I am using latest version of atom.

I assume you mean 1.39.0 @Prashant1102?  It's helpful to know the exact version.

I wonder if you're having a similar issue as https://github.com/atom/atom/issues/19698 - please note that you'll lose unsaved data (including unsaved files) but if that's not an issue, does clearing saved state help?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state

**Comment by rsese** [comment]
Just saw your edit @joaopedroraldi :smile:  Glad clearing saved state helped.

**Comment by nicolasbarra** [comment]
The same is happening with me on Mac since the last update.

**Comment by joaopedroraldi** [comment]
> Just saw your edit @joaopedroraldi 😄 Glad clearing saved state helped.

Thanks, but the problem has not been eradicated. Decreased frequency but didn't stop.

**Comment by rsese** [comment]
@joaopedroraldi - so after some amount of time using Atom, it will start crashing until you clear saved state?  Are you always working on the same project when this happens?
