### ISSUE TITLE
Can you make it optional to have all the windows for options open up EVERY time I open Atom?

### ISSUE THREAD

**Issue by cwpittman** [atom/atom#19688]

**Comment by cwpittman** [comment]
I would like to simply have an option to turn off all the clutter that appears when I open Atom. I love this product, but its annoying to close three windows every time.

**Comment by lee-dohm** [comment]
If you mean the welcome experience, it is optional and the simplest way to turn it off is by unchecking "Show Welcome Guide when opening Atom":

<img width="1325" alt="Screen Shot 2019-07-21 at 7 47 20 PM" src="https://user-images.githubusercontent.com/1038121/61602963-8ac24900-abf0-11e9-87a0-ca867cc5500d.png">

If you mean something else, please include a screenshot or some other indication of what you mean by "three windows".
