### ISSUE TITLE
GitHub Desktop can't find atom-beta

### ISSUE THREAD

**Issue by UziTech** [atom/atom#19696]
GitHub Desktop can't find atom v1.40.0-beta0

![image](https://user-images.githubusercontent.com/97994/61764410-b7b45e80-ad9e-11e9-93b7-fe531c42826e.png)

It looks like this might be due to the exe being renamed from `atom.exe` to `atom-beta.exe`
https://github.com/atom/atom/pull/17813

https://github.com/desktop/desktop/issues/8010

**Comment by Arcanemagus** [comment]
Thanks for bringing this up!

As this is an intentional change for the purposes outlined in the PR you linked I'm going to close this issue here, thanks for filing one over on `desktop/desktop` to bring this to that team's attention though!
