### ISSUE TITLE
Atom is not saving

### ISSUE THREAD

**Issue by gaflinux** [atom/atom#19710]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I run Fedora 30 Linux and am a software engineer. I am running atom 1.39.1. 
### Steps to Reproduce

1. Open file
2. edit file
3. ctrl s, File Save, File Save As

**Expected behavior:**
Updated file will be saved

**Actual behavior:**
Nothing

**Reproduces how often:**
Always

100%
### Versions

Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 2.7.16
git 2.21.0

### Additional Information
I have been using atom for several years. Yesterday it worked fine. Today I noticed the issue because atom-python-run failed 

I usually install atom via the Fedora DNF command and have the atom repo installed. 

I read bug #18114 with the same title.

**Comment by lee-dohm** [comment]
The cause of this is virtually always a package that you have installed. The way that you can confirm this is by running Atom in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode). Please verify that you can reproduce the problem when running in Safe Mode.

**Comment by gaflinux** [comment]
Works in safe mode. I am going through the other steps. 
Fails 'atom --clear-window-state'
Succeeds when I remove the ~/.atom folder. 
So, that proves it is a package. 
You can close this

**Comment by gaflinux** [comment]
I verified it is a packages, not sure which
