### ISSUE TITLE
Atom freezing while writing over selected text

### ISSUE THREAD

**Issue by brhaka** [atom/atom#19744]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * [X] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * [X] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * [X] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * [X] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When you select a specific text than start typing over it, Atom freezes.
Text: `background-image: url(./img/icones/right-arrow-grey.png);`
Happened just now when just writing `500px` after deleting `50%`.

### Steps to Reproduce

1. Open any file;
2. Select some text;
3. Start writing over that text;
4. BOOM!

**Expected behavior:**

Overwrite the selected text.

**Actual behavior:**

Atom freezes, needs to be closed by Task Manager.

**Reproduces how often:**

Sometimes

### Versions

Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 3.5.2
git 2.18.0.windows.1
visual studio 2015

Windows 10 Pro x64

### Additional Information

I have some packages intalled, but I disabled all of them and Atom still freezes.
Probably this is an issue with HTML *"* highlighting.

**Comment by lee-dohm** [comment]
Can you reproduce this in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)? I ask because you mention manually disabling packages, which Safe Mode does for you, among other things.

**Comment by brhaka** [comment]
Yes @lee-dohm, it's possible to reproduce in Safe Mode.

**Comment by rsese** [comment]
Thanks for confirming that @brhaka - I was unable to reproduce on Windows 10 with 1.39.1 but I might be misunderstanding your repro steps.

Can you share more specific steps so I can try again?  It sounds like you can reproduce by selecting and overwriting any text but you also mention HTML specifically so I'd like to confirm.

For example, can you reproduce with these steps?

1. `atom --safe`
2. Create a new file
3. Paste this content and save as `test.html`:

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>hello world</h1>
  </body>
</html>
```
4. Select "hello world"
5. Type "bye" to overwrite "hello world"

**Comment by brhaka** [comment]
No @rsese, I can't reproduce with these steps. Atom just freezes some times, I don't know exactly why...

**Comment by rsese** [comment]
> Atom just freezes some times, I don't know exactly why...

ahh ok, I misunderstood the information in the issue template (I edited it so it doesn't say "Always" for how often it reproduces).

If you come across specific steps to reproduce with a minimal example, please let us know and we can take a look again.
