### ISSUE TITLE
Wrong cursor position with line-height: normal

### ISSUE THREAD

**Issue by andrewpavlenko** [atom/atom#19758]
### Description

Cursor renders in wrong position with this settings in user stylesheet:
```
atom-text-editor {
  font-weight: bold;
  line-height: normal;
}
```
Here is how it looks
![screenshot](https://i.imgur.com/hwUqYST.png?1)
### Steps to Reproduce

1. Open user stylesheet (edit -> stylesheet)
2. Insert snippet that was desribed above
3. Save

**Expected behavior:**

Cursor renders exactly at selected line.

**Actual behavior:**

Cursor renders below the selected line.

**Reproduces how often:**

Always.

### Versions
Atom 1.39.1
Ubuntu 19.04

### Additional Information

Font on screenshot: [this](https://github.com/belluzj/fantasque-sans).

**Comment by lee-dohm** [comment]
Verified using Atom Nightly v1.41.0-nightly7 on macOS 10.14.6

**Comment by woolenkitten** [comment]
I've found that Atom use `transform: translate` for setting cursor position. Also we can add some position calculations for given line height, but will it be performance-cheap? I think, cursor position can be corrected by playing with `position` property in user stylesheet.
In my case, the main aim of setting line-height was getting more code on my low-resolution laptop screen, and I've done it by scaling editor view with `ctrl + mouse wheel `.

**Comment by sadick254** [comment]
Closing this issue, adding position calculations is not performance-cheap. Since this is introduced with a user style mod. The fix should also be through a modification on the same user style.
