### ISSUE TITLE
Issue Using Keyboard Macros

### ISSUE THREAD

**Issue by numashev** [atom/atom#19761]
I use iCUE software to create keyboard macros related to working to LaTeX in atom and have had an issue with a macro (using the prnt screen key) that produces the following:

_\begin{itemize}
    \item
\end{itemize}_

The macro works fine in every programming, however in atom the output of the macro changes at random. Here is a gif that shows the issue when I press the macro key (you can see it works the first two times but not the next two):

![Atom Issue (0)](https://user-images.githubusercontent.com/40768692/62695678-25f15600-ba1a-11e9-905d-579e618717c1.gif)

**Comment by Aerijo** [comment]
How is this macro interfacing with Atom?

**Comment by numashev** [comment]
> How is this macro interfacing with Atom?

You can see how it is interfacing with atom in the above gif. The macro is based off of a third party software called iCUE.

**Comment by Aerijo** [comment]
> You can see how it is interfacing with atom in the above gif.

No, I can't. Is is just pasting text?

**Comment by numashev** [comment]
The macro doesn't paste text, it works by pressing and releasing the keys on my keyboard. Here is a gif of the macros does. 

![Atom Issue (0)](https://user-images.githubusercontent.com/40768692/62696628-27238280-ba1c-11e9-9214-86ff0a0fbe3e.gif)

Thanks!

**Comment by rsese** [comment]
> The macro doesn't paste text, it works by pressing and releasing the keys on my keyboard.

After the macro stops working correctly, if you just type out the key sequence of the macro yourself does the behavior reproduce?

Also I see that `Delays` checkbox in your screenshot - is that a setting for delay between keypresses?  If you add a small delay does that help?

**Comment by numashev** [comment]
Hi Rsese,

Thanks for your response.

Typing out the key sequence works fine without the behaviour/error of the macro reproducing.

I added the delays since by increasing the delays between the keys the macro is less likely to fail. However, at 10ms failure is still quite common. I imagine this indicates that this means the issue is a result of the processing power of my computer and atoms high processing demands.
