### ISSUE TITLE
Cannot read property 'bigint' of undefined

### ISSUE THREAD

**Issue by UziTech** [atom/atom#19783]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

when fs.stat has undefined as second argument it throws the error:

```
Cannot read property 'bigint' of undefined
```

### Steps to Reproduce

1. Run `require("fs").stat("somefile", undefined, (stats) => {})` in the console

**Expected behavior:**

calls callback with "somfile"'s stats

**Actual behavior:**

throws error:

```
Cannot read property 'bigint' of undefined
```

**Reproduces how often:**

100%

### Versions

 Atom    : 1.41.0-beta0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

### Additional Information

This wasn't an issue before v1.41.0-beta0

**Comment by Aerijo** [comment]
See the [fs module documentation](https://nodejs.org/api/fs.html#fs_fs_stat_path_options_callback). The callback is non-optional after v10.0.0, and an options object was introduced after 10.5.0. I imagine the check if the second param is a function, and treat it as the options if not.

As such, your example where you pass undefined as the second param is not supported behaviour. If you feel this should be changed, you would have to raise the issue NodeJS itself.

**Comment by UziTech** [comment]
Submitted an issue at https://github.com/nodejs/node/issues/29113
