### ISSUE TITLE
atom does not run a file saved in a folder 

### ISSUE THREAD

**Issue by crazybelaruski** [atom/atom#19806]
Hello, 
I have installed atom and python 3, 
as well as created a file test.py, 
however when I try to run it a syntax error occurs. 
Thank you
![2019-08-16_09-02-49](https://user-images.githubusercontent.com/54166536/63146748-a90b4100-c004-11e9-9c2c-ed59057e7486.png)

**Comment by rsese** [comment]
Thanks for reaching out!  Atom by default doesn't run code so I assume you're using a community package.  The best place to start for help with a community package is the package repository - the [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581). Then a couple of other resources are the official [message board]](https://discuss.atom.io) and the [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638); on the message board and in the Atom Slack, there are a bunch of helpful community members that might be able to help.
