### ISSUE TITLE
PROJECT_PATH and PROJECT_NAME

### ISSUE THREAD

**Issue by mosesontheweb** [atom/atom#19805]
Hi,

I have linter and linter-mypy installed and it always complains that it can't find modules/packages which I created in my project folder using virtual environments. In the linter settings I found a possible setting, saying that I could use using PROJECT_PATH.

Now, I added my project using "Add project folder" and thought that this variable is set and usable, but when I right-click on the project root folder and click on "Copy project path", the value seems not to be set. At least I can't paste a thing in a newly created file.

So I was wondering on how to get linter working and use PROJECT_PATH for generally use python virtual environments.

Any hints welcome!

Regards, Thomas

**Comment by rsese** [comment]
Thanks for reaching out!  This best place to start for help with a community package is the package repository: https://atom.io/packages/linter-mypy.  Then a couple of other resources are the official [message board]](https://discuss.atom.io) and the [Atom Slack](https://discuss.atom.io/t/join-us-on-slack/16638); 
on the message board and in the Atom Slack, there are a bunch of helpful community members that might be able to help.
