### ISSUE TITLE
Atom wont reopen last session after last update

### ISSUE THREAD

**Issue by Julien-Rozet** [atom/atom#19816]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom wont restore last session like previously release. Even with option "Restore Previous Windows On Start" set to "yes" or "always".

### Steps to Reproduce

1. Start Atom
2. Open some files
3. Close Atom
4. Restart Atom

**Expected behavior:**

Previously opened files on step 2 must be reopened after a restart of Atom.

**Actual behavior:**

A new session is open after a restart of Atom.

**Reproduces how often:**

100%

### Versions

Atom    : 1.40.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

**Comment by rsese** [comment]
Thanks for the report!

> Open some files

Can you clarify exactly how you're opening files?  For example, are you opening single files with `atom myfile.txt`?

**Comment by Julien-Rozet** [comment]
By drag & drop and/or "Open File..." in the menu.

**Comment by rsese** [comment]
Ahh ok I assume you drag and drop or "Open File..." in an Atom window with an empty tree view (so no project open)?   If so, then this issue is being tracked in https://github.com/atom/settings-view/issues/1129.

**Comment by Julien-Rozet** [comment]
Yes, you're right. But I remember that in previously version (on Windows), that's worked!

**Comment by rsese** [comment]
Thanks for confirming :+1:  We'll go ahead and close in favor of https://github.com/atom/settings-view/issues/1129 and you can subscribe there if you'd like.
