### ISSUE TITLE
Atom crashes after scrolling down code

### ISSUE THREAD

**Issue by Snowzt** [atom/atom#19835]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom crashes when I scroll down my code.

**Expected behavior:**

To scroll down my code.

**Actual behavior:**

Atom crashes

**Reproduces how often:**

Everytime I scroll down

### Versions

Atom: 1.40.1

**Comment by rsese** [comment]
Thanks for the report - 

> To scroll down my code.

Can you share the file by any chance so we can test with it?  Also, is it just one particular file?  If so, what programming language is it?

Was there any difference when you ran in safe mode or did it crash in the same way?

> ### Versions

What operating system are you running?

**Comment by Snowzt** [comment]
> Thanks for the report -
> 
> > To scroll down my code.
> 
> Can you share the file by any chance so we can test with it? Also, is it just one particular file? If so, what programming language is it?
is python
> 
> Was there any difference when you ran in safe mode or did it crash in the same way?
it still crashed
> 
> > ### Versions
> 
> What operating system are you running?
windows 8.1

**Comment by rsese** [comment]
Thanks - are you able to share the file where you see the crash?

Also, if you disable `Settings > Core > Use Tree Sitter Parsers` do you still see the crash?

**Comment by Snowzt** [comment]
> My FIle:
[main.zip](https://github.com/atom/atom/files/3561675/main.zip)

I disabled Use Tree Sitter Parsers and it still crashes.

**Comment by rsese** [comment]
Thanks for sharing the file, I had some trouble with the .zip though - can you post again or share a link to the file itself on https://gist.github.com/ or a similar service?

**Comment by Snowzt** [comment]
I have closed this as I no longer use Atom due to this issue.
