### ISSUE TITLE
atom.open error starting in 1.36.0: The "path" argument must be of type string

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#19842]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

`atom.open` by all accounts should open a new Atom window, or at least open a file in the current Atom window. Neither of those actually happens.

### Steps to Reproduce

1. Open Atom 1.40.1 devTools
2. Run `atom.open({pathsToOpen: ["test.txt"], newWindow: true})`

Another option:

1. Run `atom.open()` in devTools
2. Select a directory

**Expected behavior:**

A new Atom window is opened

**Actual behavior:**

Nothing happens

**Reproduces how often:**

100%

### Versions

Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python
git
visual studio

# Additional Information

Sorry, can't test on other platforms right now, but the original report that prompted this comes from macOS user.

Original report: https://github.com/atom-community/markdown-preview-plus/issues/464

**Comment by cbourke** [comment]
Just checking in to see if there is a recommended workaround for this if not a forthcoming patch.  The issue still exists in 1.45.0 (mac).  Thanks.

**Comment by sadick254** [comment]
This has now been resolved on the latest version `v1.50.0`. See  https://github.com/atom-community/markdown-preview-plus/issues/464#issuecomment-657246501

![atomopen](https://user-images.githubusercontent.com/5238135/91489197-152bb080-e8b9-11ea-83cf-163e07386bb3.gif)

**Comment by lierdakil** [comment]
@sadick254, atom-community/markdown-preview-plus#464 is irrelevant, I've reimplemented the feature without using `atom.open`. But I can confirm, `atom.open` seems to mysteriously work again on v1.50.
