### ISSUE TITLE
Uncaught TypeError: this.getModel is not a function

### ISSUE THREAD

**Issue by Gubith** [atom/atom#19855]
1. New Atom install, nothing else added to inits
2. [flight manual keymaps example](https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/)  to init.js 
```
atom.commands.add('atom-text-editor', {
  'user:insert-date': (event) => {
    const editor = this.getModel()
    return editor.insertText(new Date().toLocaleString())
  }
})
```
3. Add keybinding
```
'atom-workspace':
    'alt-g': 'custom:insert-date'
```
4. Reload window.
5. Observe error: TypeError: this.getModel is not a **function**

Notes:
1. Resolved by changing to 
```
editor = atom.workspace.getActiveTextEditor() 
```
2. This function is not applied to a keybinding in the manual... I'm not sure why it is even there.
3. Changed user: to **custom:** to make the keybinding work.  The function seems out of place, and serves only to confuse.
4. The real intent here was to report a buggy manual, but it is also a Core issue...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.getModel is not a function

```
At C:\Users\charles\.atom\init.js:44

TypeError: this.getModel is not a function
    at HTMLElement.atom.commands.add (~/.atom/init.js:44:23)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1249835)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:1245969)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:284329)
```

### Commands

```
     -0:14.7.0 custom:testc (input.hidden-input)
```

### Non-Core Packages

```
atom-pure-black-syntax 0.3.0 
black-corail-ui 0.0.1 
gtk-dark-theme 0.1.4 
hyper-black-syntax 0.1.0 
ir-black-k-syntax 0.2.3 
language-AHK 0.0.2 
language-autohotkey2 1.0.1 
language-batchfile 0.7.5 
```

**Comment by Aerijo** [comment]
That flight manual code snippet is incorrect; it should be the following
```
atom.commands.add('atom-text-editor', {
  'user:insert-date'(event) {
    const editor = this.getModel()
    return editor.insertText(new Date().toLocaleString())
  }
})
```
