### ISSUE TITLE
Unable to install packages with a postinstall script with apm

### ISSUE THREAD

**Issue by coroa** [atom/atom#19866]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * ~~Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>~~ (not applicable)
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/> (`apm install --check` -> `Checking for native build tools ✓`)
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * ~~Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>~~ (not applicable)

### Description

Installing a package like `hydrogen` or `ink` (which both have a postinstall script) with `apm` fails with
```
➜  ~ grep -E "(warn|error)" /home/coroa/.atom/.apm/_logs/2019-09-03T08_20_10_064Z-debug.log
2173 warn enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11983-23670-1efcohp.qn82/package.json'
2175 warn apm-install-dir-11983-23670-1efcohp.qn82 No description
2176 warn apm-install-dir-11983-23670-1efcohp.qn82 No repository field.
2177 warn apm-install-dir-11983-23670-1efcohp.qn82 No README data
2178 warn apm-install-dir-11983-23670-1efcohp.qn82 No license field.
2186 error code ELIFECYCLE
2187 error errno 134
2188 error ink@0.10.12 postinstall: `node scripts/postinstall.js`
2188 error Exit status 134
2189 error Failed at the ink@0.10.12 postinstall script.
2189 error This is probably not a problem with npm. There is likely additional logging output above.
```

Attached you find the logfile for the run by `apm-beta install ink` after removing `~/.atom` to start from a clean slate: 
[2019-09-03T08_20_10_064Z-debug.log](https://github.com/atom/atom/files/3568558/2019-09-03T08_20_10_064Z-debug.log)

I am at a loss on how to proceed? Any pointers on how to debug this further?

### Versions

Same behaviour on latest stable (1.41.0) and beta (1.14.0-beta1) Debian packages (running on a Debian sid).

```shell
➜  ~ apm-beta --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0-beta1
python 2.7.16+
git 2.23.0
```

**Comment by Aerijo** [comment]
I would suggest raising the issue on the `atom-ink` repo, but [the issue already exists](https://github.com/JunoLab/atom-ink/issues/212)

**Comment by coroa** [comment]
@Aerijo Thanks for the initial screening. Filed additionally a new issue with the more active hydrogen package (see above)

**Comment by rsese** [comment]
Following up on some issues - looks like issues have been opened on the package repositories so going to close in favor of https://github.com/JunoLab/atom-ink/issues/212 and https://github.com/nteract/hydrogen/issues/1762.  Package maintainers can let us know if there's an issue on the Atom side (but if folks thinks this issue should be open let me know).

**Comment by fkastner** [comment]
I think we need to reopen this issue since it still persists in the current atom v1.44.0 and neither JunoLab/atom-ink#212 nor nteract/hydrogen#1762 seem to be able to get to the bottom of this.
One workaround that was found though is to use [apx](https://github.com/Aerijo/apx).
