### ISSUE TITLE
RECURRING: Uncaught TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by LCaineCustoms** [atom/atom#19875]
[Enter steps to reproduce:]

1. Locate/ follow the directory path of the applications installation folder on your PC.
(mine has been downloaded to an external source due to space limitations.)
2. Once the application successfully launches on your desktop, an error will apport in a modal
box.
![Desktop screenshot (1)](https://user-images.githubusercontent.com/53426213/64332500-8af08b00-cf89-11e9-990b-28d1615e57df.png)

"`
**Atom**: 1.25.1 ia32
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'version' of undefined

```
At I:\AtomPortable\AtomPortable_1.25.1\App\Atom\resources\app\node_modules\settings-view\lib\package-card.js:248

TypeError: Cannot read property 'version' of undefined
    at I:/AtomPortable/AtomPortable_1.25.1/App/Atom/resources/app/node_modules/settings-view/lib/package-card.js:248:40
    at I:/AtomPortable/AtomPortable_1.25.1/App/Atom/resources/app/node_modules/settings-view/lib/package-manager.js:333:24
    at exit (I:/AtomPortable/AtomPortable_1.25.1/App/Atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (I:/AtomPortable/AtomPortable_1.25.1/App/Atom/resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (I:/AtomPortable/AtomPortable_1.25.1/App/Atom/resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
```

### Non-Core Packages

```
emmet 2.4.3 
```

<hr>
Have you read Atom's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/atom/.github/blob/master/CODE_OF_CONDUCT.md

Do you want to ask a question? Are you looking for support? The Atom message board is the best place for getting support: https://discuss.atom.io

-->

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 1. Locate/ follow the directory path of the applications installation folder on your PC.
(mine has been downloaded to an external source due to space limitations.)
2. Once the application successfully launches on your desktop, an error will apport in a modal
box.
![Desktop screenshot (1)](https://user-images.githubusercontent.com/53426213/64332500-8af08b00-cf89-11e9-990b-28d1615e57df.png) 

**Expected behavior:**

-- I honestly expected to be able to utilize Atom in my development business.
**Actual behavior:**

The application crashes immediately regardless of the location of saving the download and all other technical self support performed.

**Reproduces how often:**

Now, this has been occurring 100% of the time, I have not had the chance to type a single bit of code.

**Comment by Aerijo** [comment]
> Atom: 1.25.1 ia32

Atom is currently on version 1.40.1; please verify the issue with the current version first.
