### ISSUE TITLE
BUG:The folder has more than 14 Chinese characters and cannot be opened.

### ISSUE THREAD

**Issue by acdiost** [atom/atom#19878]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
The folder has more than 14 Chinese characters and cannot be opened.

### Steps to Reproduce

1. file
2. open folder
3. choose folder

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**
every time.

### Versions
OS:Ubuntu 18.04.3 LTS
Atom Version:1.40.1 x64

**Comment by acdiost** [comment]
OS:Ubuntu 18.04.3 LTS

**Comment by acdiost** [comment]
Version:1.40.1 x64

**Comment by rsese** [comment]
Thanks for the report!

> The folder has more than 14 Chinese characters and cannot be opened.

Can you share a specific example that we can copy and paste to try and reproduce? 

> Atom Version:1.40.1 x64

Can you confirm how you installed Atom and share the full output of `atom -v`?

**Comment by acdiost** [comment]
It works fine.
