### ISSUE TITLE
Atom starts as a blank Window

### ISSUE THREAD

**Issue by Dr-Mart** [atom/atom#19887]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
I used Atom a Time but now it won´t work anymore. When I´m starting it only a blank winsow comes. 

### Steps to Reproduce

1. Starting Atom
2. It opens
3. A window with no UI 

**Expected behavior:**
An Ui so that i can use Atom.
**Actual behavior:**
A Blank Window
**Reproduces how often:**
100%

### Versions

`Os: elementary OS 5.0 Juno`
`Based on Ubuntu 18.04.2 LTS`
`Kernel: Linux 4.15.0-60-generic`
`GTK+ 3.22.30`
`apm:  2.4.3`
`npm: 6.2.0`
`node: 10.2.1 x64`
`atom 1.40.1`
`python 2.7.15+`
`git 2.17.1`
**How it looks like:**
![Screenshot von 2019-09-06 18 39 58](https://user-images.githubusercontent.com/52884390/64445854-ab2e6000-d0d7-11e9-9f58-abd0edbeaea5.png)

**Comment by rsese** [comment]
Thanks for filling out the template - did you see any difference when starting in safe mode?  Also you mentioned:

> I used Atom a Time but now it won´t work anymore

So Atom started showing a blank window recently?  Did this issue start just after updating to 1.40.1?

Not sure if it's the same issue, but do any of the suggestions in https://github.com/atom/atom/issues/19066 help?

**Comment by Dr-Mart** [comment]
Thank you it works now!

**Comment by rsese** [comment]
Oh great glad to hear it :+1:  I'll go ahead and close this out - curious what helped?  Was is it the same issue as https://github.com/atom/atom/issues/19066?
