### ISSUE TITLE
cmd.exe  Not found

### ISSUE THREAD

**Issue by PetrKryslUCSD** [atom/atom#19895]
Atom 1.401 on Windows 64-bit: I had to change atom.sh in its last five lines to explicitly refer to cmd.exe when running atom from the git bash. Previously this used to work. Note the second line of this listing.
```
if [ "$(uname -o)" == "Msys" ]; then
  "C:\\WINDOWS\\system32\\cmd.exe" //C "$ATOMCMD" "$@" # Msys thinks /C is a Windows path...
else
  cmd.exe /C "$ATOMCMD" "$@" # Cygwin does not
fi
```
I am not sure if this is an issue of Atom configuration, or perhaps rather the git bash.

**Comment by PetrKryslUCSD** [comment]
I think at this point that my system got somehow misconfigured: no basic programs are in the path (cmd, powershell). Can that is most likely the source of this error.

**Comment by Akashprk** [comment]
Great Sir you help me lot i can not express in word !!!!!! 
Lot of Thanks
