### ISSUE TITLE
keep getting error

### ISSUE THREAD

**Issue by tarbear123** [atom/atom#19910]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

i expect to be able to open it and start coding

the error shows up everytime i  open Atom

100%

### Additional Information

![Screenshot from 2019-09-13 11-32-16](https://user-images.githubusercontent.com/38800609/64882378-36e54680-d61a-11e9-802f-f35f6f3b3e1d.png)

**Comment by Arcanemagus** [comment]
Have you tried opening Atom in safe mode as requested in the template?
You also haven't provided this information:
> Copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Thanks!

**Comment by tarbear123** [comment]
the Atom --version is 1.40.1, how do I find the apm --version is  I'm running Linux, version --ubuntu 19.04

**Comment by Arcanemagus** [comment]
> Have you tried opening Atom in safe mode as requested in the template?

**Comment by tarbear123** [comment]
no, I haven't, how do I get into safe mode?

**Comment by Arcanemagus** [comment]
The link is given rught under the checkmark bos 😉
https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode

**Comment by tarbear123** [comment]
got it working, had to reset the app

**Comment by Arcanemagus** [comment]
Thanks for reporting back!
