### ISSUE TITLE
Scroll past end option won't go out

### ISSUE THREAD

**Issue by nickjannes101** [atom/atom#19928]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I turned on the option to Scroll past the end of my files and now it won't go off.
I even reinstalled atom from scratch and the issue was still there.

### Versions

Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

Windows 10

**Comment by rsese** [comment]
Thanks for the report - I was unable to reproduce on Windows 10 with 1.40.1.  I enabled `Scroll Past End` and saw that it worked, then I unchecked the option and the behavior stopped working as expected.

> I turned on the option to Scroll past the end of my files and now it won't go off.

Just to clarify, you unchecked the `Scroll Past End` setting?

Have you tried temporarily resetting to factory defaults?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults

**Comment by nickjannes101** [comment]
I tried the factory reset.
When I uncheck the option it works. But when I then restart atom with the unchecked option, it enables again when it restarts.

**Comment by rsese** [comment]
Hmm, do you have an issue with other settings too?  For example, if you uncheck `Settings > Audio Beep` and then restart Atom, is it checked again?

**Comment by nickjannes101** [comment]
They keep the same value. It is only with the Scroll past end option.

**Comment by rsese** [comment]
Looks like someone had the same issue https://github.com/atom/atom/issues/19993 and mentioned that the Kite package was causing the problem for them.  I installed Kite on Windows and was able to reproduce.

When you reset to factory defaults, did you notice if you still had community packages installed and running?   Do you use Kite?

**Comment by nickjannes101** [comment]
Hi,

yes I'm using that package. If I disable Kite the Scroll past end option sticks. Thanks for the solution!
