### ISSUE TITLE
Split pane does not close after last tab is closed

### ISSUE THREAD

**Issue by stvcisco** [atom/atom#19948]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
After closing the last tab in a pane, the empty pane remains around. It used to close automatically. I have to right-click and "close pane" (or cmd-W) to clear it.

### Steps to Reproduce

1. open any file 
2. right click on its tab and select "split right"
3. a new instance of the editor opens in a new pane to the right
4. Close the tab in the new right pane
5. The empty right pane remains even though there are no files to show

**Expected behavior:**
I expected the extra pane to automatically close when its last tab is closed.

**Actual behavior:**
The empty pane hangs around taking up space

**Reproduces how often:**
100%

### Versions
Atom    : 1.34.0
Electron: 2.0.16
Chrome  : 61.0.3163.100
Node    : 8.9.3
MacOS: Mojave 10.14.6

**Comment by rsese** [comment]
Thanks for reaching out - do you have a `Settings > Core > Remove Empty Panes` enabled?

Also a side note:

> Atom : 1.34.0

Not sure if you're sticking with 1.34.0 for a particular reason but if not, the latest stable release version of Atom is 1.40.1 so I'd suggest updating if you can.

**Comment by stvcisco** [comment]
You're right on both points.  I did not have "remove empty panes" checked, though I only noticed this starting to happen recently.
I'm also upgrading to 1.40.x now. 
Thanks!
