### ISSUE TITLE
Uncaught TypeError: Cannot destructure property `itemHeight` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by bad-at-code** [atom/atom#19954]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot destructure property `itemHeight` of 'undefined' or 'null'.

```
At C:\Users\Josh\AppData\Local\atom\app-1.40.1\resources\app\static\<embedded>:14

TypeError: Cannot destructure property `itemHeight` of 'undefined' or 'null'.
    at SuggestionListElement.scrollSelectedItemIntoView (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:1490932)
    at SuggestionListElement.renderSelectedItem (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:14:1490717)
    at ViewRegistry.performDocumentUpdate (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:325676)
```

### Commands

```
  2x -1:56.1.0 run:file (input.hidden-input)
 25x -1:21.9.0 core:move-up (input.hidden-input)
     -1:20.6.0 core:move-right (input.hidden-input)
     -1:20.6.0 core:move-down (input.hidden-input)
     -1:20 core:move-up (input.hidden-input)
  2x -1:01.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-runner 2.7.1 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.1 
linter-flake8 2.4.0 
linter-ui-default 1.8.0 
teletype 0.13.4 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm a few things for us?

* What were you doing at the time of the error?
* Is the error is reproducible?
* If reproducible, do you see the error in safe mode (`atom --safe`)?

**Comment by bad-at-code** [comment]
Its been awhile since I posted this and I was able to fix the error, but I forgot how. Sorry.

**Comment by rsese** [comment]
ahh no problem, thanks for the followup :+1:  We'll close for now but if you end up finding steps to reproduce, please let us know and we can reopen.
