### ISSUE TITLE
Uncaught ReferenceError: ent is not defined

### ISSUE THREAD

**Issue by ReiCat** [atom/atom#19963]
Idk if it will work on your machine but I've just started it and closed welcome tabs and started typing.

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Ubuntu 18.04.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught ReferenceError: ent is not defined

```
At /usr/share/atom/resources/app/static/<embedded>:14

ReferenceError: ent is not defined
    at SuggestionListElement.renderItem (/usr/share/atom/resources/app/static/<embedded>:14:1493415)
    at SuggestionListElement.renderItems (/usr/share/atom/resources/app/static/<embedded>:14:1489766)
    at ViewRegistry.performDocumentUpdate (/usr/share/atom/resources/app/static/<embedded>:11:325676)
```

### Commands

```
```

### Non-Core Packages

```
atom-format-lua 0.1.5 
```

**Comment by rsese** [comment]
Thanks for the report!  It sounds like the error is reproducible for you by just typing in a new unsaved file?  Can you reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by ReiCat** [comment]
I can't reproduce it anymore. In safe mode too. Maybe it has been updated and error disappeared.

**Comment by rsese** [comment]
Thanks for the update - since it's not reproducible at the moment we'll go ahead and close, but if you find steps to reproduce in safe mode, let us know and we can take a look.
