### ISSUE TITLE
Previously automatically-saved state dialog even in safe mode.

### ISSUE THREAD

**Issue by cbuteau** [atom/atom#19967]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Hello,

This happens only on my laptop (which might be snappier than my desktop)

My workplace uses a homegrown SCM.
So there might be other files in the directory I do not know about.
If you guys give me ideas on how to enable logging perhaps there are files I can clean before opening the directory again.

I constantly open atom in a directory.
I even have an alias (doskey) a. to do it quickly.

Even in safe mode.
atom --safe . it pops this dialog.
![image](https://user-images.githubusercontent.com/1906839/65684269-3773d900-e02d-11e9-85dd-ed4b07ff5879.png)

I did search for this issue and found this locked issue so I am opening a fresh bug.
https://github.com/atom/atom/issues/14968
Because that one is locked.

I found this Discuss...topic...
https://discuss.atom.io/t/previous-automatically-saved-project-state-detected-comes-up-every-time/43051
But apm update did not do anything for the problem.

### Steps to Reproduce

1. Save a file in the directory.
2. Close Atom.
3. Open Atom again.

**Expected behavior:**
It just opens the directory.

**Actual behavior:**
The dialog happens and I choose 
Open window with state.
And I have to close the other atom window.

**Reproduces how often:**
100%

### Versions

e:\WS\CBU1_2019x_lap_welcome>atom --version

Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

e:\WS\CBU1_2019x_lap_welcome>apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.16
git 2.23.0.windows.1
visual studio

### Additional Information

e:\WS\CBU1_2019x_lap_welcome>apm update
Package Updates Available (0)
└── (empty)

e:\WS\CBU1_2019x_lap_welcome>a.

e:\WS\CBU1_2019x_lap_welcome>apm links
C:\Users\cbu1\.atom\dev\packages (0)
└── (no links)
C:\Users\cbu1\.atom\packages (0)
└── (no links)

**Comment by lee-dohm** [comment]
Have you followed **all** of the steps in [the Debugging section of the Flight Manual](https://flight-manual.atom.io/hacking-atom/sections/debugging/)? It's pretty likely that clearing saved state or resetting to factory defaults could resolve this problem.

**Comment by cbuteau** [comment]
Um
I want atom to remember which files I had open
and I don't want to clear state every time.

So either you did not read my whole report or there is no loggig or other investigation on my part.

i guess close the bug if nothing is going to happen.

**Comment by lee-dohm** [comment]
Yes, I read your report. I didn't suggest you need to try this every time, only once. I can't reproduce the problem you're experiencing and suspect it is a transient issue. So trying the two things I mentioned above are things you can do to help investigate the problem.

**Comment by cbuteau** [comment]
No logging....there might be other files in the directory that are fooling atom...

**Comment by PrimerMediaGroup** [comment]
thanks

**Comment by PrimerMediaGroup** [comment]
thanks to all .apk

**Comment by cbuteau** [comment]
Okay
I did --clear-window-state
and the problem reproduces.

Is there no logging or do I have to debug atom itself to find the source of this annoyance?

How do I cause debugger to break on initialization in safe mode?
