### ISSUE TITLE
Can’t copy text from “Spec Suite” window

### ISSUE THREAD

**Issue by ariasuni** [atom/atom#19978]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Execute command `Window: Run Package Specs` or hit `Ctrl+Shift+Y`
2. Try to copy text from the “Spec Suite” window that opens.

**Expected behavior:**

Being able to copy text.

**Actual behavior:**

Nothing is copied in clipboard, be it by using the Menu bar → File → Copy action, or by using a keyboard shortcut.

**Reproduces how often:**

Everytime.

### Versions

```
Atom    : 1.40.1
Electron: 4.2.11
Chrome  : 69.0.3497.128
Node    : 10.11.0

apm  2.4.3
npm  6.11.3
node 12.11.0 x64
atom 1.40.1
python 2.7.16
git 2.23.0
```

**Comment by rsese** [comment]
Thanks for the report - I thought this was reported before but couldn't find an existing issues so I'm probably misremembering.  Reproduced on macOS 10.14.6 with Atom 1.40.1.

**Comment by rsese** [comment]
> be it by using the Menu bar → File → Copy action

Just to followup on this bit, it looks like on macOS that copying from the `Edit` menu works - I think when I first tried it, the specs were still running and my selection was removed but after I let the specs finish running, I could copy/paste text from the `Edit` menu.  What operating system are you running?

**Comment by ariasuni** [comment]
I’m on Linux. I tested it again, I can confirm it doesn’t work even after the specs finished running.

**Comment by binaryfunt** [comment]
Reproduced on Windows 10 v1903 with Atom 1.40.1. Neither <kbd>Ctrl</kbd>+<kbd>C</kbd> or `Edit > Copy` work. Right clicking on the text doesn't bring up a context menu.

A workaround is to open the dev tools for the spec suite window and grab the innerHTML instead
