### ISSUE TITLE
Insert at EOF

### ISSUE THREAD

**Issue by buggsdummy** [atom/atom#19974]
## Summary

It would be nice to have an insertion feature that could insert at a particular line # / regex for a line / EOF for all files of a particular file <file name>.txt in the searched folders 

## Motivation

This would be nice to have to add properties to multiple applications when making a mass change. Saves a lot of time!

## Describe alternatives you've considered

https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html

The ansible module would be good if making live changes, but it isn't great for editing changes to be pushed upstream. There are no insertion option available at all other than search and replace function which doesn't fit this unless it's massaged to do so.

**Comment by Arcanemagus** [comment]
Thanks for the submission!

That would definitely be useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for this project. For that reason, I'm going to close this. It sounds like a great idea for an Atom package though. If you need help building this as a package, please check out the [Atom Flight Manual section on publishing your own packages](https://flight-manual.atom.io) and feel free to ask any questions you have on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the Atom Slack team.

Thanks again for contributing to Atom :+1:
