### ISSUE TITLE
Files are not highlighted in Tree View and tabs

### ISSUE THREAD

**Issue by yuriihabrusiev** [atom/atom#19972]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)
    * Followed all applicable steps in [the debugging guide](https://flight-manual.atom.io/hacking-atom/sections/debugging/)
    * Checked [the FAQs on the message board for common solutions](https://discuss.atom.io/c/faq)
    * Checked that your [issue isn't already filed](https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom)
    * Checked [that there is not already an Atom package that provides the described functionality](https://atom.io/packages)

### Description

After installing Atom 1.40, files in Tree View and tabs are not highlighted according to their status and I see this error in inspector's console.
```
Uncaught (in promise) Error: Git status failed
```
Atom Beta also has this issue. And "GitHub" package works as intended.

### Steps to Reproduce

1. Launch `atom .` inside git repository 

**Expected behavior:**

Changed or added files are highlighted in Tree View.

**Actual behavior:**

No highlights at all.

**Reproduces how often:**

Every time I launch Atom.

### Versions

```
$ atom --version
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
$ apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python 2.7.10
git 2.23.0
```

**Comment by rsese** [comment]
Thanks for the report!  Do you see this issue with any repository or just a particular repository?  For example, if you create a new repository with a single file, can you reproduce?

> After installing Atom 1.40

Just to clarify, do you mean that previous versions of Atom don't have this issue with the same repository?

**Comment by yuriihabrusiev** [comment]
> Do you see this issue with any repository or just a particular repository? 

Yes, in all old and new.

> do you mean that previous versions of Atom don't have this issue with the same repository?

Yes, before 1.40 I didn't have this issue.

**Comment by rsese** [comment]
Hmm, I'm unable to reproduce on macOS 10.14.6.

> Yes, in all old and new.

Not sure if this is what you mean by a new repository but can you also reproduce if you create a brand new repo and then add/commit a single file, do you see the issue there as well?

Also, what operating system are you running and can you confirm that if you install 1.39.1 the problem goes away?

**Comment by yuriihabrusiev** [comment]
> can you also reproduce if you create a brand new repo and then add/commit a single file, do you see the issue there as well?

I did this already and problem still occurs 

> what operating system are you running

I'm also on macOS 10.14.6

> can you confirm that if you install 1.39.1 the problem goes away?

yes, with 1.39.1 there is no issue. I just checked.

**Comment by rsese** [comment]
Does that "Uncaught (in promise) Error: Git status failed" error appear right when you open a repository?  Also, if you start Atom in the foreground with `atom --foreground`, are there any more error details, maybe a stacktrace?

**Comment by yuriihabrusiev** [comment]
> Does that "Uncaught (in promise) Error: Git status failed" error appear right when you open a repository?

I think it's happening every time "tree-view" or "tabs" try to read file's status.
<img width="1792" alt="Screen Shot 2019-10-02 at 9 38 46 AM" src="https://user-images.githubusercontent.com/901000/66023342-8e7c2100-e4f9-11e9-82db-215564874e90.png">


> Also, if you start Atom in the foreground with atom --foreground, are there any more error details, maybe a stacktrace?

Not sure if this is relevant, but that is all I got:
```
$ atom-beta --foreground .
2019-10-02 09:44:45.567 Atom Beta[31970:1586365] *** WARNING: Textured window <AtomNSWindow: 0x7fb2b5c59bd0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

(using beta here because I'd like to keep stable at 1.39.1)

**Comment by rsese** [comment]
Yeah the output looks unrelated - do you happen to have any global`.gitconfig` settings that you enabled?

**Comment by yuriihabrusiev** [comment]
Hey, thank you for the tip - the issue was in my global `~/.config/git/ignore`!

It has these lines:
```ignore
# *.sql
# Exclude Rails' db/structure.sql
!structure.sql
```

I commented `*.sql` long time ago and everything worked until this issue with Atom 1.40.

**Comment by rsese** [comment]
Oh awesome, glad you tracked things down!  And thanks for sharing your findings, hopefully that can be helpful as something to check if anyone runs into similar behavior :bow:
