### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND www-proxy-...

### ISSUE THREAD

**Issue by rajeshvig** [atom/atom#19970]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND www-xxxxx.com xxxxx:80

```
At internal/streams/legacy.js:57

Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND xxxx.com xxxx.com:80
    at ClientRequest.onError (/app.asar/node_modules/tunnel-agent/index.js:177:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketErrorListener (_http_client.js:382:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Commands

```
```

### Non-Core Packages

```
ftp-remote-edit 0.17.4 
itg-dark-syntax 2.0.0 
itg-light-syntax 0.4.0 
language-tcltk 0.1.5 
notepad-plus-plus-syntax 0.2.7 
print-atom 0.1.1 
Sublime-Style-Column-Selection 1.7.5 
sublime-ui-dark 0.0.7 
sublimify 0.10.0 
```

**Comment by PrimerMediaGroup** [comment]
I'm webhot;30303

**Comment by PrimerMediaGroup** [comment]
null:3030{master}

**Comment by wvidana** [comment]
I have the same issue. Note that the configs on `apm` work (like `apm config set https-proxy "https://127.0.0.1:9000"`) but only when installing from the command line using `apm install`, the GUI to search/install packages doesn't work. My `.bashrc` is already configured to export the `http_proxy` env var, maybe the issue is that Atom boots without them?

**Comment by rsese** [comment]
Is the error from `apm` on the command line or from Settings View?

> I have the same issue.

You had the same `getaddrinfo ENOTFOUND` error @wvidana?

> Note that the configs on `apm` work (like `apm config set https-proxy "https://127.0.0.1:9000"`) but only when installing from the command line using `apm install`, the GUI to search/install packages doesn't work.

I think there's an existing issue for that behavior but couldn't find it just now.

**Comment by rajeshvig** [comment]
for me the error was in console in developer tools while trying to access files using ftp-remote-edit

**Comment by wvidana** [comment]
> Is the error from `apm` on the command line or from Settings View?

  * From Settings View

> You had the same `getaddrinfo ENOTFOUND` error @wvidana?
  * For me it was `tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.35.40:80 - Local (10.203.40.199:60269)`

For me `apm` works fine after I configured the proxy settings. Sadly I had to configure `apm`, instead of Atom getting the proxy settings from the system (like `.bashrc` exports `http_proxy`, `https_proxy`...)

**Comment by rajeshvig** [comment]
yes worked for me after explicity disabling proxy for local domain using "apm config set no-proxy=".<domain>"

**Comment by rsese** [comment]
> For me `apm` works fine after I configured the proxy settings. Sadly I had to configure `apm`, instead of Atom getting the proxy settings from the system (like `.bashrc` exports `http_proxy`, `https_proxy`...)

@wvidana does apm work with your system settings if you enable `Settings > Core > Use Proxy Settings When Calling APM`?

**Comment by wvidana** [comment]
Yes, that setting is marked, and apm works, but I had to manually type in
the command line apm config set http-proxy...
