### ISSUE TITLE
Scroll Past End Resets After App Close

### ISSUE THREAD

**Issue by paulcruse3** [atom/atom#19993]
### Description

I would like to NOT Scroll Past End, so I uncheck the box in "Settings -> Editor".

When I close atom and re-open it, Scroll Past End is enabled again.

### Steps to Reproduce

1. Use version 1.40.1 (on Mac
2. Go to "Settings -> Editor" and uncheck "Scroll Past End"
3. Close Atom and ReOpen (doesn't stick)

**Expected behavior:**

I expect Scroll Past End checkbox to remain unchecked even after closing Atom.

**Actual behavior:**

Scroll Past End Resets After App Close 

**Reproduces how often:**

This happens every time

### Versions

Mac 10.14.6 
Atom 1.40.1

**Comment by Arcanemagus** [comment]
Could you answer the part of the template you removed? Thanks!

* Are you able to reproduce the problem in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
* Have you tried the recommended [Debugging Steps](https://flight-manual.atom.io/hacking-atom/sections/debugging/)?
  * Specifically resetting to Factory Defaults, as it sounds like you are running into a permissions issue, possibly from accidentally running Atom as `root`.

**Comment by paulcruse3** [comment]
@Arcanemagus Thank for your help.

I admit section I removed from the template was TLDR.

I was able to stop it it from happening, by removing a packaged called [Kite](https://atom.io/packages/kite).

I will be taking the issue up with them
