### ISSUE TITLE
AutocompleteManager.deprecateForSuggestion is deprecated.

### ISSUE THREAD

**Issue by MarekZ98** [atom/atom#19996]
Autocomplete provider 'ClassProvider(undefined)'
      returns suggestions with a `prefix` attribute.
      The `prefix` attribute is now `replacementPrefix` and is optional.
      See https://github.com/atom/autocomplete-plus/wiki/Provider-API
```
AutocompleteManager.deprecateForSuggestion (<embedded>:11:649515)
n.push.Promise.resolve.then.n (<embedded>:11:647289)
```

**Comment by rsese** [comment]
Based on some older issues like https://github.com/atom/about/issues/62, I think this might be an an issue with one of your community packages, an autocomplete package in particular.  If you can reproduce in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) however, please let us know.
