### ISSUE TITLE
JavaScript optional catch binding causes UncaughtException: TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by Timber-stone** [atom/atom#19999]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

In a .js file, if there is a catch block using optional catch binding (i.e. write a catch block without binding the error, see https://github.com/tc39/proposal-optional-catch-binding ), the editor will continuously give the error "UncaughtException: TypeError: Cannot read property 'type' of null. Restarting server..." when you continue typing anywhere in the file.

### Steps to Reproduce

1. Create a .js-file and write a try catch block with optional catch binding. For example: 

```
try {  
//Some js code here  
} catch {  
//Maybe some more code here  
}
```

2. Type anywhere in the same file. The error will now appear.

**Expected behavior:**

Support for optional catch binding should be implemented so the error doesn't appear (these errors also make the editor lag).

**Actual behavior:**

The error appears when a try catch-block with optional catch binding is present.

**Reproduces how often:**

This error is 100% reproducible.

### Versions

Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.40.1
python
git
visual studio 2015

Microsoft Windows 10 Pro
10.0.17763 Build 17763

**Comment by Arcanemagus** [comment]
I'm unable to reproduce this on Atom v1.42.0-nightly8.

> `UncaughtException: TypeError: Cannot read property 'type' of null. Restarting server...`

This sounds like something coming from a package, are you able to reproduce this in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by Timber-stone** [comment]
I'm sorry, I thought I checked this in safe mode but you're right, it doesn't occur in safe mode.
I found that the problem is in the atom-ternjs package. Apparently it doesn't support ECMAScript 2019 yet.
My apologies for not checking the packages thoroughly first.
