### ISSUE TITLE
Centos7 install via repo fails

### ISSUE THREAD

**Issue by cuky23** [atom/atom#20005]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
WONT get this far!
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
running atom in a terminal with an xserver gives the following error.

/tmp/atom-build/Atom/atom: No such file or directory

### Steps to Reproduce

1. 

install yum repo
/etc/yum.repos.d/atom.repo 
[Atom]
name=Atom Editor
baseurl=https://packagecloud.io/AtomEditor/atom/el/7/$basearch
enabled=1
gpgcheck=0
repo_gpgcheck=1
gpgkey=https://packagecloud.io/AtomEditor/atom/gpgkey

2. yum install atom
3. atom

**Expected behavior:**
load atom ide via X

error 

**Actual behavior:**

**Reproduces how often:**

### Versions
[root@cuky01virt tmp]# npm --version
6.9.0
[root@cuky01virt tmp]# node --version
v10.16.3

Installed Packages
Name        : atom
Arch        : x86_64
Version     : 1.40.1
Release     : 0.1

### Additional Information

Is this supported to run via X?

**Comment by rsese** [comment]
Just to clarify, you don't have any issues running Atom locally yes?

**Comment by igavelyuk** [comment]
Just to clarify, do you try `atom-beta`?
