### ISSUE TITLE
1.40.1 fails to launch on macOS 10.12.6, 1.40.0 is OK

### ISSUE THREAD

**Issue by twardoch** [atom/atom#20006]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Install Atom 1.40.1 on macOS 10.12.6 and try to launch: Atom quits pretty instantly. No messages, nothing in system Console, no UI. Trying to run with --safe yields the same. 

Install 1.40.0 and the app runs fine. 

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by rsese** [comment]
Is there any output if you start Atom in the foreground with `atom --foreground`?  Also, if you [temporarily reset to factory defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) does Atom still not start with 1.40.1?

As a side note, please completely fill out the issue template when opening issues - the format and information in the template is super helpful for us when triaging issues.
