### ISSUE TITLE
atom 1.40.1 could not be displayed correctly on mac os 10.15

### ISSUE THREAD

**Issue by binbjz** [atom/atom#20014]
### Description
I opened atom, it does not display correctly after I upgraded to the mac os latest version (10.15 catalina)

### Steps to Reproduce
1. upgrade mac os to 10.15 catalina
2. open atom 1.40.1
3. atom only shows the menu bar, I've reinstalled atom with 1.40.1, but it still doesn't work

**Expected behavior:**
It displays the editor's interface correctly and works properly

**Actual behavior:**
It only displays the editor's menu bar interface correctly, and it doesn't work properly.
Where is my atom editor interface ?

<img width="1220" alt="Screen Shot 2019-10-13 at 10 44 08" src="https://user-images.githubusercontent.com/8213913/66710213-74b6c580-eda6-11e9-8515-92df4e2f5eaa.png">

**Reproduces how often:**
always

### Versions
Atom: 1.40.1
Mac os: 10.15 catalina

Hardware overview:
Model Name:	MacBook Pro
  MacBook Pro (15-inch, 2019)
  Processor 2.4 GHz 8-Core Intel Core i9
  Memory 32 GB 2400 MHz DDR4
  Graphics Radeon Pro Vega 20 4 GB
                   Intel UHD Graphics 630 1536 MB

**Comment by eiGelbGeek** [comment]
I can't reproduce this .... On my MacBook Air with 10.15 Atom 1.40.1 works properly.
![Bildschirmfoto 2019-10-13 um 05 28 34](https://user-images.githubusercontent.com/26887967/66710508-5aff8900-ed7a-11e9-9ab1-e4e4f78e7b05.png)

**Comment by eiGelbGeek** [comment]
If you Click on -- File -> Add Project Folder -- what happen on your Systems?

**Comment by binbjz** [comment]
@eiGelbGeek Just this "Add Project Folder" menu was opened and nothing happened，


<img width="1217" alt="Screen Shot 2019-10-13 at 12 36 53" src="https://user-images.githubusercontent.com/8213913/66711075-2d850080-edb7-11e9-82ae-ade10fb6c677.png">

**Comment by binbjz** [comment]
> If you Click on -- File -> Add Project Folder -- what happens on your System?

I try this way, but all my unsaved documents are gone. How can I restore them?

**Comment by binbjz** [comment]
Who can tell me which files I back up can restore my previous session，I have a lot of unsaved files that are very important. This bug really bugs me

**Comment by binbjz** [comment]
After backing up the data in the image below, I deleted all of it and reinstalled atom, now atom works fine.
<img width="746" alt="Screen Shot 2019-10-13 at 20 42 06" src="https://user-images.githubusercontent.com/8213913/66716349-5fba5080-edff-11e9-8c8b-ccb7f289d193.png">
@rsese

**Comment by lee-dohm** [comment]
Have you tried the `File | Reopen Project` menu item? If you had an open project and saved that project's state by exiting Atom, then the project directory should show up in the list there. If you didn't have an open project or if Atom crashed, then the only recovery option is the `~/.atom/recovery` directory.

Since this is no longer a submission of a bug but a request for assistance, I would recommend you check the [Support resources](https://github.com/atom/atom/blob/master/SUPPORT.md) if you have more questions.

**Comment by binbjz** [comment]
@lee-dohm Atom did not crash,Atom 1.40.1 could not be displayed correctly and all unsaved files were lost after I upgraded mac os to 10.15. These unsaved files are very important to me. Why are you closing it ? Isn't this a bug ?  After backing up the data in the image below, I deleted all of them and reinstalled atom, now atom works fine.  How can I use all the atom files I backed up to recover the unsaved files I lost. This is my appeal.

**Comment by qawemlilo** [comment]
I'm having the same issue with atom 1.41.0 on OSX 10.13.2. Menu shows but the atom window is invisible.

![Screen Shot 2019-10-31 at 15 58 31](https://user-images.githubusercontent.com/363359/67953380-af6a8b80-fbf7-11e9-843d-d3cec96bff7f.png)

**Comment by binbjz** [comment]
This is a bug and you shouldn't close it！

**Comment by qawemlilo** [comment]
@binbjz I've had to switch to vscode because I couldn't get any help. Hopefully someone will take notice and reopen this issue.

**Comment by gandhiShepard** [comment]
After upgrading to Catalina Atom stopped working. I was able to get it working again in 2 steps:

xcode-select --install
removing the .atom directory
Atom opened up fine after that. I copied my Packages folder back over to the .atom directory.

I hope this helps others.
