### ISSUE TITLE
Dependency errors when building Atom (Ubuntu 12.04) as well as other strange problems

### ISSUE THREAD

**Issue by Zekka** [atom/atom#2003]
When installing Atom, I received a long block of errors roughly matching this pattern:

npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/init-package-json requires semver@'2.x' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined

cding to build and running npm install followed by npm install npm seemed to help, as build continued normally with only a few hiccups after that.

Some logs:
> zekka@zekka-yk:~/code/atom$ script/build
> 
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/grunt-download-atom-shell requires github-releases@'0.1.1' but will load
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/github-releases,
> npm WARN unmet dependency which is version 0.2.0
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/init-package-json requires semver@'2.x' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/node-gyp requires semver@'~2.2.1' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/node-gyp requires tar@'0' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/node-gyp requires which@'1' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/npm-install-checks requires semver@'~2.2.1' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/npm-registry-client requires semver@'^2.2.1' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/npm-registry-client requires slide@'~1.1.3' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/npm-registry-client requires retry@'0.6.0' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/npmconf requires semver@'2' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/read-installed requires semver@'2' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/read-installed requires slide@'~1.1.3' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data requires semver@'2' but will load
> npm WARN unmet dependency undefined,
> npm WARN unmet dependency which is version undefined
> /bin/sh: 1: /home/zekka/code/atom/build/node_modules/.bin/npm: not found
> zekka@zekka-yk:~/code/atom$ cd build
> zekka@zekka-yk:~/code/atom/build$ ls
> Gruntfile.coffee  node_modules  package.json  README.md  tasks
> zekka@zekka-yk:~/code/atom/build$ npm install npm
> npm http GET https://registry.npmjs.org/npm
> npm http 200 https://registry.npmjs.org/npm
> npm http GET https://registry.npmjs.org/npm/-/npm-1.4.10.tgz
> npm http 200 https://registry.npmjs.org/npm/-/npm-1.4.10.tgz
> npm WARN package.json github-url-from-git@1.1.1 No repository field.
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/grunt-download-atom-shell requires github-releases@'0.1.1' but will load
> npm WARN unmet dependency /home/zekka/code/atom/build/node_modules/github-releases,
> npm WARN unmet dependency which is version 0.2.0
> npm@1.4.10 node_modules/npm

After that, all modules installed successfully until I reached this phase of the process:

> Installing modules ✓
> Deduping modules ✓

> events.js:72
>         throw er; // Unhandled 'error' event
              ^
> Error: spawn ENOENT
>     at errnoException (child_process.js:998:11)
>     at Process.ChildProcess._handle.onexit (child_process.js:789:34)

After this, running sudo script/grunt install results in the same output.

**Comment by 50Wliu** [comment]
This should be fixed in the latest build scripts.
