### ISSUE TITLE
Atom stopped starting

### ISSUE THREAD

**Issue by Ningaro** [atom/atom#20032]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Suddenly, the Atom stopped working. I do not understand what this may be connected with. When you try to start in Windows, two processes appear and nothing else happens.

Sorry for my English 😢 

### Steps to Reproduce

IDK

**Expected behavior:**

application launch

**Actual behavior:**

nothing

**Reproduces how often:**

all time

### Versions
💻  - Windows 10 x64
:atom: - All (I try `1.40.1`, `1.39.0` and `Nightly`)

### Additional Information

It is strange that nothing has changed even after reinstalling the text editor. Also, the editor does not respond to arguments at startup `--safe` etc.

**Comment by rsese** [comment]
Thanks for the report -

> Also, the editor does not respond to arguments at startup --safe etc.

Can you clarify what you mean when you say Atom doesn't respond?  Does the command just return on the command line and nothing happens or do you see an error? 

Have you tried [temporarily resetting to factory defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults)?

**Comment by Ningaro** [comment]
> command just return on the command line and nothing happens

Everything happens just like that.

_Screenshot for more informative, unfortunately, Windows in one language 🇷🇺 😞_ 

![image](https://user-images.githubusercontent.com/23503775/67433226-6eb7b480-f5f0-11e9-8690-229852ca6bc6.png)

**Comment by rsese** [comment]
Thanks for the screenshots :+1:  How about my other question?

> Have you tried temporarily resetting to factory defaults?

Also, if you start Atom in the foreground is there any output?

```
atom --foreground
```

**Comment by Ningaro** [comment]
Nothing 😞 
![image](https://user-images.githubusercontent.com/23503775/67988191-452a0900-fc40-11e9-9177-c0f5e3ac9b17.png)

**Comment by rsese** [comment]
Hmm, did you try this too?

> Have you tried temporarily resetting to factory defaults?

Also curious if `atom -v` returns anything?

**Comment by Ningaro** [comment]
> Also curious if `atom -v` returns anything?

I try to reinstall Atom, but nothings changes...

![image](https://user-images.githubusercontent.com/23503775/69225670-d8939180-0b8f-11ea-9616-e4f609caf25e.png)

**Comment by WilSnoop** [comment]
Hello.

The last messages you get is about the command for `Atom` not registered for global usage. It could be that is requires you to make it available in a manual way. Or the installation is corrupted. 

Side-by-side installation of `Atom` version (installing more than one `Atom` version on the PC) is only possible when using `portable` installation method. Some users also have other issues that is solved by using the `portable` installation.

Please follow a recent conversation:
 https://discuss.atom.io/t/atom-does-not-open/68931

Consider starting a conversation at the user-help-user forum (discuss.atom.io).

**Comment by Ningaro** [comment]
@WilSnoop thank you very much 👍  I find a solution to my problem!

**Comment by Ningaro** [comment]
So, how could I solve my problem with Atom...

1. Restarted Windows in order to kill all the processes of Atom
2. Deleted the contents of the folder `%localappdata%\atom\`
3. Deleted the contents of the folder `%homepath%/.atom`

✔️  After that, the latest version of Atom was successfully installed and LAUNCHED.
I express my gratitude in the help and support @WilSnoop & @rsese 😃
