### ISSUE TITLE
Incredibly long Shell/Window load time 

### ISSUE THREAD

**Issue by jeengbe** [atom/atom#20037]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
Atom is starting incredibly slowly. Timecop says Shell/Window load time are taking >4000ms each
### Steps to Reproduce

1. Launch Atom
2. Take a nap, do exercise
3. Finally open, check Timecop for timings

**Expected behavior:**
Load times < 1000ms
**Actual behavior:**
Load times > 4000ms
**Reproduces how often:**
Every time
### Versions
```atom --version``` doesn't do anything and 
I have no idea where my apm is
Help>About says that I am running v1.40.1

OS Name: Windows 10 Home 
OS Version: 10.0.17763
Processor: Intel Core i7-7700HQ
RAM: 16GB 

### Additional Information
I also renamed ~/.atom and did a few restarts, did also use Atom Beta. Nothing changed.

**Comment by rsese** [comment]
Can you share a screenshot of what timecop is showing?  On my Windows 10 machine with Atom 1.40.1 shell load time is around 500 - 700ms and Window load time ~100ms.  Also are you opening a particular project when you start Atom?

x-ref: https://github.com/atom/atom/issues/14347.  Another issue where this came up but wasn't generally reproducible.

**Comment by rsese** [comment]
Oh also, do the times look similar with the latest [Atom Beta](https://atom.io/beta)?  That's running a newer version of Electron.

**Comment by jeengbe** [comment]
It does the exactly same with Atom Beta.
[Screenshot](https://i.gyazo.com/238ffa9d3677f9e2922b1deaa3bfc9a2.png)

**Comment by Arcanemagus** [comment]
What does Timecop look like if you start Atom in [Safe Mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by jeengbe** [comment]
![Like so](https://i.gyazo.com/4adb2f01283b105ed95ee777b3cab6f8.png)

**Comment by jeengbe** [comment]
Any update on this?
