### ISSUE TITLE
Entire window becomes blurry on Windows 10.

### ISSUE THREAD

**Issue by Peilonrayz** [atom/atom#20040]
### Prerequisites

* [x] Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
* [ ] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>

    * Reproducible in with `atom --safe --disable-gpu`.
    * The Developer Tools doesn't have any errors.

* [x] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
* [x] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * https://github.com/atom/atom/issues?utf8=%E2%9C%93&q=is%3Aissue+blurry+text
* [ ] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

This is what Atom normally looks like for me, rather blurry, but I can deal with that.

![safe_clear](https://user-images.githubusercontent.com/5623093/67216459-2b581d00-f41b-11e9-8b26-915f42037b6f.png)

Every now and then Atom decides to turn the blur settings to max and looks like this.

![safe_blurry](https://user-images.githubusercontent.com/5623093/67216475-31e69480-f41b-11e9-80d7-ae0b203bdcf6.png)

It should be noted that even though the picture shows the entire screen as blurry, it can affect only segments of the screen. For example `"stories"` to `"id": 1` may be completely legible, but everything else is blurry.

### Steps to Reproduce

1. Open a file with a lot of CJK characters. (Doesn't have to be the active tab)
2. Wait a bit - when waiting don't use the mouse or keyboard.
3. If you're waiting too long click on Atom and repeat from 2.

**Reproduces how often:**

Started off at about 0.01%-1% of the time, now it feels like 90% of the time.

Nearly every time I stop interacting with the code, say to read it. And bam it's gone blurry.

### Versions

```
Atom    : 1.40.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0
```

### Additional info

```
> window.devicePixelRatio
1
```

**Comment by Peilonrayz** [comment]
I installed VS Code as a something to use whilst trying to get this fix and reproduced it in that too.

I Googled around and found [this answer](https://stackoverflow.com/a/53856774) which I followed:
1. Open NVIDIA Control Panel.
2. 3D Settings > Adjust image setting with preview
    1. Select Let the 3D application decide
3. 3D Settings > Manage 3D settings
    1. Restore

This caused (3D Settings > Adjust image settings with preview > Use the advanced 3D image settings) to be selected, and I have yet to reproduce this in either Atom or VS Code. The text is also no longer blurry in the default view either.

![safe_clean](https://user-images.githubusercontent.com/5623093/67219441-f3070d80-f41f-11e9-84a0-8b8279d59e33.png)

---

I will leave this open for the moment to see if this has fixed the screen randomly becoming very blurry. Because I don't think a couple of minutes is enough time to check for that.

**Comment by rsese** [comment]
Thanks for the report -

> I installed VS Code as something to use whilst waiting for this to get fixed, and reproduced this in that too.

:+1: seems like an Electron issue if you can reproduce in VS Code as well.

> Reproducible in with `atom --safe --disable-gpu`.

Hmm, I would expect it to not reproduce with `--disable-gpu` - can you try just `atom --disable-gpu` and let us know if you still see the same problem?

**Comment by Peilonrayz** [comment]
> can you try just `atom --disable-gpu` and let us know if you still see the same problem?

Unfortunately, even though that surprised me too, I didn't check for that. It seems my solution really did solve the problem. Given that I know the fix I can probably find a way to un-fix it.

I'll try break my system again in the coming week, but I can't promise anything.

**Comment by rsese** [comment]
> I'll try break my system again in the coming week, but I can't promise anything.

No problem, glad you have a workaround - I'll tag this as `more-information-needed` so if you don't get a chance to (or prefer not to) unfix things :smile:   so the issue will auto-close if we don't hear back.

**Comment by hatemalimam** [comment]
This is also happening on Mac:
Info:

1.41.0 x64
Electron: 4.2.7
Chrome: 69.0.3497.128
Node: v10.11.0
