### ISSUE TITLE
Atom will not start on Catalina -- Needs notarization

### ISSUE THREAD

**Issue by directionless** [atom/atom#20071]
Hi! I was taking a quick look at Atom, and I noticed that the current macOS download is not notarized. Notarization is apple's current malware scanning service. There's some information up at https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

While there are some ways for end users to skip this check, it would be best practice to notarized directly. 

I've gone and notarized the 1.41.0 download (`md5:622281426390b6649dee88807b5a1434`), it passes with the current apple rules. These are set to get a bit stricter in January 2020.

I'm not sure what your build and release process. Perhaps electron or xcode have simple workflows. My usual workflow is something like:
```
xcrun altool --username $APPLEID --password @env:N_PASS --asc-provider $TEAMID --notarize-app --file ~/Downloads/atom-mac.zip  --primary-bundle-id com.github.atom
xcrun altool --username $APPLEID --password @env:N_PASS --asc-provider $TEAMID  --notarization-info $REQUEST_GUUID
staple Atom.app
```

**Comment by geoffrey4444** [comment]
I also have this issue. I really like atom, but as a new user, I almost threw it away after it triggered Catalina’s “cannot be checked for malware” alert. Any chance the macOS build can be notarized?

**Comment by lkashef** [comment]
Hello @directionless thanks for the report!

Atom has been recently notarized, you can access it right away by downloading [the nightly version](https://atom.io/nightly) and it will take it's cycle to go from nightly to beta and beta to stable.

**Comment by jusjosgra** [comment]
I tried installing Atom Nightly today on Catalina 10.15.2 and still got an error telling me that Atom couldn't be checked for malicious content.

**Comment by lkashef** [comment]
Hey @jusjosgra, one of the indirect dependencies notarization was breaking, so it broke Atom's notarization. The dugite team is working on it and should have a fix soon, so we can turn re-enable notarization on Atom.

Reference: https://github.com/atom/atom/pull/20390
