### ISSUE TITLE
Atom wont install on Windows 7 

### ISSUE THREAD

**Issue by Michaeljmq** [atom/atom#20084]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by Michaeljmq** [comment]
Sorry I closed this in error, I still have this problem.

**Comment by prajwal-mendon** [comment]
me too I had  the same problem but it is in windows 8.1

**Comment by prajwal-mendon** [comment]
did you try the zip file

**Comment by Michaeljmq** [comment]
prajwal-mendon - I have now tried that on your recommendation and it works, many thanks.

**Comment by lkashef** [comment]
Hey @Michaeljmq thanks for reaching out, I am glad your problem was resolved.
Thanks @prajwal-mendon for helping out.
