### ISSUE TITLE
Atom quits without promting to save file after clicking Cancel once

### ISSUE THREAD

**Issue by xdavidhu** [atom/atom#20105]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When creating at lest 2 unsaved files, and closing the Atom window, it prompts the user that `'untitled' has changes, do you want to save them?`, but if the user select `Cancel` and clicks the closes the window again, no warning is shown an Atom closes without saving any of the unsaved files.

### Steps to Reproduce

1. Open Atom
2. Create 2 new files with some content in them
3. Close the Atom window
4. To the prompt `'untitled' has changes, do you want to save them?`, select `Cancel`
5. Close the Atom window again
6. See that Atom closes and the unsaved files are lost

**Expected behavior:**

Atom prompts the user until they select `Don't Save` or `Save`.

**Actual behavior:**

Atom closes after clicking `Cancel` and closing the window again.

**Reproduces how often:**

Every time.

### Versions

Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
OS: macOS 10.15 Catalina

**Comment by tim-sorrels** [comment]
Hi, I am interested on working on this issue.

**Comment by lee-dohm** [comment]
Hey, thanks for the offer! @darangi will point you in the right direction in the next few days 👍

**Comment by lkashef** [comment]
@tim-sorrels, I am excited to give you some pointers on your first contribution.

I would first go through https://github.com/atom/atom/blob/master/CONTRIBUTING.md and https://blog.atom.io/2015/10/16/making-your-first-contribution.html, they are kind of similar but could offer slightly different information or tips more than the other.

https://github.com/atom/flight-manual.atom.io: is also a great resource to learn about how to setup atom for development and work on packages.

Last but not least, discuss.atom.io is a good place to ask questions and here are some good tips from @lee-dohm https://discuss.atom.io/t/how-can-i-contribute-to-atom/27083 on general contribution.

---

Now, regarding this specific issue, I did a quick search `org:atom has changes, do you want to save them?` and https://github.com/atom/atom/blob/1d9a4cafcf6cc288d675512db8fd984e13aab869/src/pane.js looks like a good place to start.

I hope my comment would help you get started, reading through this document you will learn about the different channels of communication to get better and more prompt support.

**Comment by sadick254** [comment]
Hey @xdavidhu I am not able to reproduce this behaviour on Atom 1.49.0. It looks like the issue has been fixed.
