### ISSUE TITLE
"Show Tab Bar" under the "View" menu has disappeared

### ISSUE THREAD

**Issue by nrigaudiere** [atom/atom#20113]
### Prerequisites

- [X] Reproduced the problem in Safe Mode

- [X] Followed all applicable steps in the debugging guide

- [X] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
- [X] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
- [X] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When upgrading to v1.41.0, the "Show Tab Bar" option which is located under the "View" menu is not accessible anymore.

I have downgraded to the v1.40.1 and it is available on that version. I assume that it is linked to the Electron 4 upgrade.

#### Before
<img width="250" alt="Screen Shot 2019-11-04 at 10 33 08" src="https://user-images.githubusercontent.com/5648148/68113564-6286fd80-fef4-11e9-8d31-2c5231e06e8c.png">

#### After
![Screen Shot 2019-11-04 at 10 34 44](https://user-images.githubusercontent.com/5648148/68113592-70d51980-fef4-11e9-9141-a8a6f0a9074c.png)

### Steps to Reproduce

1. Upgrade to v1.41.0
2. Open "View" menu

**Expected behavior:**

"Show Tab Bar" to be available

**Actual behavior:**

The "Show Tab Bar" doesn't exist anymore

**Reproduces how often:**
100% of the time

### Versions

Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

--- 
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 2.7.15
git 2.19.1

---
OSX: 10.12.6

**Comment by ayakoaohara** [comment]
It seems "Show Tab Bar" is available with v1.41.0. I am using OSX: 10.13.6

**Comment by nrigaudiere** [comment]
@ayakoaohara So you think it could be related to my version of OSX? 😞

**Comment by ayakoaohara** [comment]
If other people with OSX 10.12.6 can reproduce the bug, that would be great

**Comment by calebmeyer** [comment]
I can confirm that this works as expected on macOS Catalina (10.15.1)

**Comment by nrigaudiere** [comment]
I have finally upgraded to High Sierra (10.13)... Not just for that of course but it fixes my issue.
Thanks for your help!
