### ISSUE TITLE
Preferred line length resets on restart

### ISSUE THREAD

**Issue by anandaltekar** [atom/atom#20121]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I tried changing the Preferred Line Length to 120 in under Settings>Editor and I have also changed it in config.cson but it always resets to 80 every time I quit Atom.

### Steps to Reproduce

1. Go to Settings>Editor
2. Enable Soft wrap
3. Change the Value of Preferred Line Length to 100 from 80
4. Quit Atom
5. Open Atom

**Expected behavior:**

Preferred Line Length should be equal to 100

**Actual behavior:**

Preferred Line Length is 80 

**Reproduces how often:**

100%

### Versions

Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

macOS Catalina 10.15.1

**Comment by rsese** [comment]
Thanks for the report!  I was unable to reproduce with 1.41.0 on macOS 10.14.6 - there was a similar issue with a setting getting reset and the person found that it was caused be a community package (Kite I think).  Besides running in safe mode, did you also try [temporarily resetting to factory defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults)?
