### ISSUE TITLE
Append scopes instead of overriding them in tree-sitter grammars

### ISSUE THREAD

**Issue by chbk** [atom/atom#20147]
## Summary

When creating a grammar, there needs to be an option to append scopes instead of overriding them.

## Motivation

When targeting tree-sitter nodes in a grammar file, scopes inevitably get repeated. This makes grammars cumbersome and hard to maintain.

## Describe alternatives you've considered

None.

## Additional context

Consider the following example:

```cson
# Identifier
'identifier': [
  {
    # Match a long list of exceptions
    match: '^(Exception|TypeError|VeryLongListOfExceptions)$',
    scopes: 'entity.class.exception'
  },
  'entity'
]

# Inherited class
'class_definition > argument_list > identifier': [
  {
    # Match a long list of exceptions (again)
    match: '^(Exception|TypeError|VeryLongListOfExceptions)$',
    scopes: 'entity.class.exception.inherited'
  },
  'entity.class.inherited'
]
```

Would be much easier to maintain if scopes were appendable:

```cson
# Identifier
'identifier': [
  {
     # Match a long list of exceptions
    match: '^(Exception|TypeError|VeryLongListOfExceptions)$',
    scopes: 'entity.class.exception'
  },
  'entity'
]

# Inherited class
'class_definition > argument_list > identifier': + 'class.inherited' # Append
```

**Comment by chbk** [comment]
A syntax proposal:
- scopes starting with a period are appended

```
# Inherited class
'class_definition > argument_list > identifier': '.class.inherited' # Append to other scopes
```

- scopes with no period override others

```
# Inherited class
'class_definition > argument_list > identifier': 'class.inherited' # Override all other scopes
```

**Comment by sadick254** [comment]
@chbk Thank you for filing this issue
Am sorry to say, this is not a feature we are interested in at the moment. We are currently interested in features or fixes that have a direct impact on Atom users. I am happy to revisit this feature sometime in the future when the verbosity of the grammar become a real user issue.
