### ISSUE TITLE
Error when installing on Ubuntu 14.04  (script/build)

### ISSUE THREAD

**Issue by a9entropy** [atom/atom#2015]
I am following the steps given here: https://github.com/atom/atom#linux-requirements

The versions I have installed are:
![screenshot from 2014-05-07 13 30 56](https://cloud.githubusercontent.com/assets/2264421/2899850/dd9a03de-d5bd-11e3-9a7e-79b1d5d3e89b.png)

When I execute 
```script/build # Creates application at /tmp/atom-build/Atom```

I get an error
```
home/aju/atom/apm/node_modules/atom-package-manager/bin/apm: line 40: /home/aju/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory
```

![screenshot from 2014-05-07 13 33 38](https://cloud.githubusercontent.com/assets/2264421/2899861/37a5f27a-d5be-11e3-9b39-d10e53746a2f.png)

**Comment by 50Wliu** [comment]
Hi @a9entropy, if you can still reproduce this, feel free to comment here.  I'm going to close this in the meantime however.
