### ISSUE TITLE
Atom crashes on creating new file without extension

### ISSUE THREAD

**Issue by piotrmonsiorski** [atom/atom#20160]
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
Atom crashes when I create a new empty file without extension throught project tree tab. It throws an error 'The editor has crashed. Please report this issue to https://github.com/atom/atom'. When I reopen the edit the file is there, but clicking it causes the same error. 

### Steps to Reproduce
1. RMB click on project tree tab, choose 'New File'
2. Enter name of the file without extension, press 'Enter' key

**Expected behavior:**
Either create file withour extension or don't let create it at all.

**Actual behavior:**
Atom crashes.

**Reproduces how often:**
Every time i reproduce steps.

### Versions
Atom 1.41.0 x64
Windows 10 Pro x64

### Additional Information
I can remove it from source tree, but when renaming, it appears it is called 'index.js'. I do have anther 'index.js' file in the folder, maybe that's the problem?
Quick idea, maybe creating new file and new folder can be merged - name without extension would be a folder, with extension would be a file.

**Comment by WilSnoop** [comment]
I have the same configuration as you have.
I cannot reproduce the results you get.

Please confirm - have you tried with Atom in safe mode?
That is important as external packages are then not active.
Try that if you can or deactivate all external packages.

Also comment out all code in the `init.coffee` / `init.js` file.
(I have seen `init` code before that forces unknown files to known grammars.)
Do a restart on `Atom` before doing your test again.

Built-in packages that has given me some problems in the past,
were packages relating to `git`.
But even with these activated on my install now, does not show ill effects.

My money is on something that makes your installation _special_.
Or there is something _special_ about the work folder.
What do you think?

**Comment by piotrmonsiorski** [comment]
Whoops, I actually forgot to disable extensions... I tried a bit and it appeared that the problematic package was... atom-prettier ;x
Thanks for the help ;)
