### ISSUE TITLE
Atom Update Error İ'cant İnstall ATOM ***WİNDOWS 8.1***

### ISSUE THREAD

**Issue by GitHubCSYTEAM** [atom/atom#20169]
Hi All i get "aTOM İNstaller has stopped working" *UPDATE.EXE*
***[21.11.19 14:19:32] ınfo: Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
[21.11.19 14:19:32] ınfo: Program: Starting install, writing to C:\Users\Emre\AppData\Local\SquirrelTemp
[21.11.19 14:19:32] ınfo: Program: About to install to: C:\Users\Emre\AppData\Local\atom
[21.11.19 14:19:32] ınfo: CheckForUpdateImpl: Reading RELEASES file from C:\Users\Emre\AppData\Local\SquirrelTemp
[21.11.19 14:19:32] fatal: Finished with unhandled exception: System.AggregateException: Bir veya daha fazla hata oluştu. ---> System.MissingMethodException: Yöntem bulunamadı: 'System.String System.String.Format(System.IFormatProvider, System.String, System.Object)'.
   konum: NuGet.SemanticVersion.Parse(String version)
   konum: Squirrel.VersionExtensions.ToSemanticVersion(String fileName)
   konum: Squirrel.Utility.<>c.<FindCurrentVersion>b__29_0(ReleaseEntry x)
   konum: System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   konum: System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   konum: System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   konum: System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   konum: Squirrel.Utility.FindCurrentVersion(IEnumerable`1 localReleases)
   konum: Squirrel.UpdateManager.CheckForUpdateImpl.determineUpdateInfo(UpdaterIntention intention, IEnumerable`1 localReleases, IEnumerable`1 remoteReleases, Boolean ignoreDeltaUpdates)
   konum: Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   konum: Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- İç özel durum yığını izlemesinin sonu ---
   konum: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   konum: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   konum: Squirrel.Update.Program.executeCommandLine(String[] args)
   konum: Squirrel.Update.Program.main(String[] args)
---> (İç Özel Durum #0) System.MissingMethodException: Yöntem bulunamadı: 'System.String System.String.Format(System.IFormatProvider, System.String, System.Object)'.
   konum: NuGet.SemanticVersion.Parse(String version)
   konum: Squirrel.VersionExtensions.ToSemanticVersion(String fileName)
   konum: Squirrel.Utility.<>c.<FindCurrentVersion>b__29_0(ReleaseEntry x)
   konum: System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   konum: System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   konum: System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   konum: System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   konum: Squirrel.Utility.FindCurrentVersion(IEnumerable`1 localReleases)
   konum: Squirrel.UpdateManager.CheckForUpdateImpl.determineUpdateInfo(UpdaterIntention intention, IEnumerable`1 localReleases, IEnumerable`1 remoteReleases, Boolean ignoreDeltaUpdates)
   konum: Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   konum: Squirrel.Update.Program.<Install>d__4.MoveNext()<---***

**Comment by GitHubCSYTEAM** [comment]
Please Help

**Comment by WilSnoop** [comment]
What happened that lead up to this point?
Did you attempt a manual installation from ..?
 https://github.com/atom/atom/releases/tag/v1.41.0

Consider a portable installation if you continue having problems.
 https://flight-manual.atom.io/getting-started/sections/installing-atom/#portable-mode
 (https://discuss.atom.io/t/atom-does-not-open/68931/4)

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
