### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Downloads\europe.png'

### ISSUE THREAD

**Issue by hstrakna** [atom/atom#20165]
Tried to drag and drop an image from downloads.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Hannah\Downloads\europe.png'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\Hannah\Downloads\europe.png'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1008510)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1015683)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:989070)
```

### Commands

```
  3x -8:53.4.0 core:backspace (input.hidden-input)
     -8:48.9.0 intentions:highlight (input.hidden-input)
     -8:48.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-jshint 3.1.17 
linter-ui-default 1.8.0 
pigments 0.40.2 
```

**Comment by WilSnoop** [comment]
Hi Hannah.

- What did you expect `Atom` to do with the picture?
- Why did you drag the picture into `Atom`?
- What is the size of the picture?
- Does that PNG open in a picture viewer?

Testing with a 720x720px PNG of ~20kB on my install: `Atom` opens the picture.

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
