### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/projects/py38/hw2'

### ISSUE THREAD

**Issue by fuzzyklein** [atom/atom#20166]
[Enter steps to reproduce:]

1. Open a second instance of `atom`.
2. Add a project tree to the second instance with a different directory than the one you're working
    with.
3. Cut a symbolic link to your `cgi-bin` directory from the second project and try to paste it into the
    other.
4. Paste the symbolic link into a subdirectory of the first project and then the error message with the
    link to start this issue appeared.

The entire directory represented by the project tree in the second window is now gone from the file system.

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/fuzzy/projects/py38/hw2'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '/home/fuzzy/projects/py38/hw2'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (/usr/share/atom/resources/app/static/<embedded>:14:1008489)
    at TreeView.onDrop (/usr/share/atom/resources/app/static/<embedded>:14:1015418)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:989049)
```

### Commands

```
     -3:56 pane:split-right-and-copy-active-item (li.directory.entry.list-nested-item.expanded.selected)
     -3:38.9.0 pane:close (div.item-views)
     -2:10.2.0 editor:consolidate-selections (input.hidden-input)
     -2:10.2.0 core:cancel (input.hidden-input)
     -0:29.5.0 tree-view:paste (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```

```

**Comment by fuzzyklein** [comment]
OK, apparently the project directory from the second window moved into the project directory of the first window and I failed to notice it. Still not at all what I was trying to do but not a big deal. What I _really_ wanted to do was split the project tree to the right. Which I did, but the right tree is empty and has no option to add a project folder to it. :(

**Comment by sadick254** [comment]
@fuzzyklein Thank you for reporting this. It looks like you have a different issue (splitting the project tree). I encourage you to open a new issue on the problem. For now I will close this. Feel free to let me know if I should reopen this issue.
