### ISSUE TITLE
Feature Request: Read and Write to Google Docs

### ISSUE THREAD

**Issue by milanlakhani** [atom/atom#20170]
## Summary

I'm not sure how feasible this is but if at all possible it would be great to have integration with Google Docs so I can sync to my account and read and write to my Google Docs from my text editor!

## Motivation

Easy access to Google docs so they can be edited offline and share the same text editor that I write scripts in

## Describe alternatives you've considered

Haven't been able to find any Linux OS alternatives, only Chrome OS

**Comment by Arcanemagus** [comment]
Thanks for the submission!

That would definitely be useful in some people's workflows. However, it is not something that is within the scope that we have have envisioned for Atom. For that reason, I'm going to close this. It sounds like a great idea for an Atom package though. If you need help building this as a package, please check out the [Atom Flight Manual section on publishing your own packages](https://flight-manual.atom.io) and feel free to ask any questions you have on [Discuss, the official Atom and Electron message board](https://discuss.atom.io) or the Atom Slack team.

You can find information on accessing Drive from Linux here, among other places around the internet:
https://itsfoss.com/use-google-drive-linux/

Thanks again for contributing to Atom :+1:
