### ISSUE TITLE
Uncaught Error: Cannot call function 'getPosition' on missing remote object 1154

### ISSUE THREAD

**Issue by Kashif1Naqvi** [atom/atom#20189]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call function 'getPosition' on missing remote object 1154

```
At C:\Users\Kashif\AppData\Local\atom\app-1.41.0\resources\electron.asar\renderer\api\remote.js:222

Error: Cannot call function 'getPosition' on missing remote object 1154
    at throwRPCError (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:148:17)
    at ~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:406:5
    at EventEmitter.ipcMain.on.args (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/rpc-server.js:273:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.41.0/resources/electron.asar/browser/api/web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

```

### Commands

```
  2x -1:53.4.0 core:save (input.hidden-input)
  4x -1:39.8.0 core:backspace (input.hidden-input)
  2x -1:38.6.0 core:save (input.hidden-input)
  5x -1:10.8.0 core:move-left (input.hidden-input)
  2x -1:08.7.0 core:move-right (input.hidden-input)
  7x -1:04.6.0 core:move-left (input.hidden-input)
  2x -0:53.8.0 core:move-right (input.hidden-input)
  9x -0:52.5.0 core:select-right (input.hidden-input)
     -0:51.2.0 core:select-left (input.hidden-input)
     -0:50.9.0 core:backspace (input.hidden-input)
     -0:43.5.0 core:save (input.hidden-input)
 25x -0:32.5.0 core:move-left (input.hidden-input)
     -0:31.1.0 core:save (input.hidden-input)
 25x -0:25.6.0 core:move-right (input.hidden-input)
  2x -0:23.2.0 core:backspace (input.hidden-input)
     -0:22.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
```

**Comment by lkashef** [comment]
Hey @Kashif1Naqvi, Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by WilSnoop** [comment]
@lkashef: I have noticed very many of these reports popping up. Some are redirected:
> We noticed that this looks like a duplicate of #16630 so you can subscribe there for updates if you'd like (we believe that this will be fixed in a future Electron upgrade).

Not expecting action, but sharing an observation. A quick check shows that most of the reports' 'commands' mention `core:save` as last or second last items.

**Comment by lkashef** [comment]
@WilSnoop Thanks a lot 🙇‍♂️, that is actually super helpful, I will try to redirect people to the open issue then to try capturing better reproduction steps.
