### ISSUE TITLE
Unable to delete Windows shared (SMB) folder

### ISSUE THREAD

**Issue by UA4IUGI** [atom/atom#20187]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Open a shared folder.
2. Delete a file or folder in the tree view.
3. An error occurs when you press "Move to Trash (I cannot do it)".

**Expected behavior:**

The object can be deleted.

**Actual behavior:**

The object cannot be deleted.

**Reproduces how often:**

anytime

### Versions

- atom
```
PS > atom --version

 Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```
- apm
```
PS > apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.41.0
python 3.8.0
git 2.24.0.windows.2
visual studio
```

- OS
```
Edition: Windows 10 Pro
Version: 1809
Installed: 2019/11/12
OS Build: 17763.864
```

### Additional Information

What is clear from the confirmation message and the error contents is designed based on the local object, not the remote object.

**Comment by Arcanemagus** [comment]
Atom doesn't allow deletion of files _period_, regardless of where they are located. If it can find a "recycle bin" and send the file there it will allow you to "Delete" a file, but only then. If it can't move the file to your operating system's location for recoverable files it will refuse to remove the file.

This is a compromise that unfortunately leads to some confusion like this about it, but not one that we will be changing.

Thanks for taking the time to file an issue!
