### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/\student03.fwcs.k12.in.us\user\05'

### ISSUE THREAD

**Issue by Mepz939-officialz** [atom/atom#20207]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '\\student03.fwcs.k12.in.us\user\05'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '\\student03.fwcs.k12.in.us\user\05'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at atom.project.getPaths.map.e (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:816901)
    at Array.map (<anonymous>)
    at Object.startTask (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:816892)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:189146)
    at get_process.nextTick (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:187110)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by WilSnoop** [comment]
Please describe what lead to this error report.
On its own this error report (to me) doe not give a starting point to work from. 

Additionally: 
What is this `\\student03.fwcs.k12.in.us\user\05`?
Is it suppose to be a path to a remotely hosted file?
Are you using a remote-file-accessing service for this?

Access rights and connectivity comes in play with remote files.
Making a local copy of the file you are trying to access may present less issues.
Ask you educator about your use case.

**Comment by Mepz939-officialz** [comment]
It is a thing for school. I code from my school laptop. My user is a bunch of numbers, and my user is stored on the N: drive. Other than that, it is just windows.Elias Campbellelicampbell09@gmail.com12603539614
null

**Comment by WilSnoop** [comment]
Hey Campbell. 

It is best if you take this case up with your teacher. He/She can guide you better than I am able to.

I suggest you do not work with the remote file. Make a local copy on your laptop and work with the local copy. Atom does see the difference between local and remote files, even though Windows File Explorer may not show the difference clearly.

There are ways to work with remotely hosted files from Atom. I am the wrong person to instruct you on this. Though I do know that sometimes problems come up and people loose data. Best you avoid this by not working directly with a remote file.

Last note - Best to not publish your email address for all public to see. Consider returning here and editing your last message, if admin does not do it for you.

Good luck forward.

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
