### ISSUE TITLE
Add dependency GLIBC_2.15 to documentation and a corresponding check to the build tool

### ISSUE THREAD

**Issue by ddeimeke** [atom/atom#2020]
Built Atom on Debian Wheezy with NodeJS v0.10.28

```
$ atom
/usr/local/share/atom/atom: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/atom/atom)
/usr/local/share/atom/atom: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/atom/libchromiumcontent.so)
/usr/local/share/atom/atom: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /usr/local/share/atom/libchromiumcontent.so)
```

**Comment by scotte** [comment]
Thank you @vellerefond for fully and well documenting a solution that doesn't require hacking up a stable Wheezy system with cross-release packages. Takes a few minutes to get through it, but the net result is a private version of libc for Atom that doesn't compromise everything else on my perfectly stable desktop - Thanks again!

**Comment by ikrauchanka** [comment]
thank you @ikks

**Comment by cosinekitty** [comment]
The method by @vellerefond was also very helpful for me to get Atom running on Debian Wheezy 7.3.  Now I ran into another similar issue trying to add a package (https://atom.io/packages/language-typescript, not that it matters).  It turns out running `apm` causes a similar problem.

````
don@spearmint:~$ apm

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by /usr/share/atom/resources/app/apm/node_modules/git-utils/build/Release/git.node)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
don@spearmint:~$ 
````
It turns out `apm` itself is a shell script, so no use trying to patchelf it!  I made backups and tried using patchelf to fix the `node` executable (patch worked but no change in behavior, so I restored from backup copy).  I also tried that git.node file from the error message, but it failed saying "cannot find section .interp".  I feel like a chimp with a handgun... ignorant and dangerous.

Any ideas for how to fix `apm` also?  Thanks in advance.

**Comment by cosinekitty** [comment]
OK, good news... I figured out how to get `apm` to work.  For anybody else with the same problem trying to install an Atom package, follow all of vellerefond's steps, then do this if you see the "GLIBC_2.15 not found" error running `apm`:

1. Figure out where apm is installed:  `which apm`.  On my system this shows `/usr/bin/apm`.
2. Follow a chain of file links to the actual location of the script `apm` by using `readlink`.  Here is how it looked when I did it:
````
don@spearmint:~$ which apm
/usr/bin/apm
don@spearmint:~$ cd /usr/bin
don@spearmint:/usr/bin$ readlink apm
../share/atom/resources/app/apm/node_modules/.bin/apm
don@spearmint:/usr/bin$ cd ../share/atom/resources/app/apm/node_modules/.bin
don@spearmint:/usr/share/atom/resources/app/apm/node_modules/.bin$ readlink apm
../../bin/apm
don@spearmint:/usr/share/atom/resources/app/apm/node_modules/.bin$ cd ../../bin
don@spearmint:/usr/share/atom/resources/app/apm/bin$ readlink apm
don@spearmint:/usr/share/atom/resources/app/apm/bin$ 
````

The fact that `readlink` finally did not print anything means we have found the correct directory where both `apm` and the version of `node` it uses are located.  So now we make a safe backup of `node` and patch it.

````
don@spearmint:/usr/share/atom/resources/app/apm/bin$ dir node
-rwxr-xr-x 1 root root 11171138 Jul  3 15:52 node
don@spearmint:/usr/share/atom/resources/app/apm/bin$ mkdir ~/mybackup
don@spearmint:/usr/share/atom/resources/app/apm/bin$ cp node ~/mybackup/
don@spearmint:/usr/share/atom/resources/app/apm/bin$ sudo patchelf --set-interpreter /opt/eglibc-2.19/lib/ld-2.19.so node
````

Now when I run `apm` it works!

````
don@spearmint:/usr/share/atom/resources/app/apm/bin$ cd ~
don@spearmint:~$ apm

apm - Atom Package Manager powered by https://atom.io

Usage: apm <command>

where <command> is one of:
    clean, config, dedupe, deinstall, delete, dev, develop, docs, erase,
    featured, home, init, install, link, linked, links, list, ln, lns, login,
    ls, open, outdated, publish, rebuild, rebuild-module-cache, remove, rm,
    search, show, star, starred, stars, test, uninstall, unlink, unpublish,
    unstar, update, upgrade, view.

Run `apm help <command>` to see the more details about a specific command.

Options:
  --color        Enable colored output                                     [boolean] [default: true]
  -v, --version  Print the apm version
  -h, --help     Print this usage message

  Prefix an option with `no-` to set it to false such as --no-color to disable
````

I was able to install the TypeScript plugin after: `apm install atom-typescript`

**Comment by scotte** [comment]
@cosinekitty if you upgrade to Debian Jessie, Atom will work out of the box since GLIBC is the current version there. Just an FYI if you weren't already aware...

**Comment by cosinekitty** [comment]
@scotte Thanks for letting me know! I am reading about it now. I'm reluctant because it's a nice stable system with lots of tweaks (I have 40+ pages of typed notes for how I got it here). But maybe the upgrade isn't so dangerous. I'm going to do a full image backup tonight and decide tomorrow.
