### ISSUE TITLE
problem with installing github on desktop.

### ISSUE THREAD

**Issue by djolestoj** [atom/atom#20211]
hey guys, I can't install GitHub on desktop, here is .txt doc with a log. 

[GitHubDesktopSetup.txt](https://github.com/atom/atom/files/3931485/GitHubDesktopSetup.txt)

edit: Github desktop has only a 64bit version for Win. How I can install this on 32bit win7?

**Comment by WilSnoop** [comment]
Consider taking up your question 
with the maintainers of `Github Desktop` at
https://github.com/desktop/desktop/issues

**Comment by djolestoj** [comment]
hey man, ty for u answer. I looked at Github.Help.com, and only for 64bit win7.
