### ISSUE TITLE
Crashing on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by ytakemon** [atom/atom#20223]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Saving a new file crashes Atom. At the moment I am only able to work by copy and pasting a existing script and renaming it. 

### Steps to Reproduce

1. Ctrl + N to create new file 
2. Ctrl + S to save new file 

**Expected behavior:**

1. Ctrl + N to create new file 
2. Ctrl + S to save new file 
3. (Window asking what to name new file)

**Actual behavior:**

3. (crashes)

**Reproduces how often:**

100 %

### Versions

MacOS Majave
10.14.6

Atom    : 1.41.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

**Comment by darangi** [comment]
Did you try reproducing this in safe mode?

**Comment by ytakemon** [comment]
@darangi, yes I did follow the prerequisite.

**Comment by ytakemon** [comment]
Update: it seems to be an internal systems network issue accessing my account at my place of work. The IT department here was able to fix the issue. Closing issue.
