### ISSUE TITLE
Inconsistent configuration state during startup

### ISSUE THREAD

**Issue by sht** [atom/atom#20268]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

There is an edge case on Windows where, when launching Atom, the process does not wait for the configuration file to load before creating the editor's window. It has been setup that way because of performance issues of electron 2, which resulted in longer startup time on Windows. This has a side effect of inconsistently launching a blank environment when the "restorePreviousWindowsOnStart" configuration option is set to "no". This problem can be traced back to this file: https://github.com/atom/atom/blob/25015f1cc03a2aad600f8245c0329d37107e52a1/src/main-process/atom-application.js#L323-L327

I did test *always* awaiting for the configuration file to load (uncommenting lines 325 and 327), and the issue immediately went away. ~I am not sure if there still is a performance hit due to Electron, but nothing showed up on Timecop.~ I created a startup performance profile as described [here](https://flight-manual.atom.io/hacking-atom/sections/debugging/#profiling-startup-performance) for both release 1.42.0 and the master branch with this fix applied, and there was no added delay (startup operations and time cost were almost identical between the two). I can attach the CPU profiles here if needed.

### Steps to Reproduce

1. Start Atom
2. Set the "Restore Previous Windows On Start" configuration option (Settings -> Core) to "no"
3. Open a project
4. Interact with it (e.g. save a file)
5. Close Atom
6. Relaunch Atom with no command line parameters

**Expected behavior:**

Atom should open a blank environment.

**Actual behavior:**

Atom restores the last opened project.

**Reproduces how often:**

70%ish

### Versions

Atom version: 1.42.0  
apm version: 2.4.3  
Operating system: Windows 10 (1909)  

### Additional Information

It seems like a straightforward fix, but I would love if someone from the atom dev team verified that there is indeed no performance hit, just in case that I did something wrong when benchmarking atom's startup. I can submit a pull request if needed.

**Comment by sadick254** [comment]
Thanks for reporting this!

You have already fixed this in https://github.com/atom/atom/pull/20547. The fix is currently available in the latest version of atom `v1.51.0`.

Thank you for your contribution.
