### ISSUE TITLE
Clojure autocomplete does not work

### ISSUE THREAD

**Issue by dboxodds** [atom/atom#20260]
and you fucking clowns have 30,380 issues.

Sou do I really think you need to have this issue? Of course not.

This fucking project is a fuck up. Just a pain for any clown who thinks this IDE is ok or will ever be ok. A deprecation is a joke in this environment.

This project is sou fuck up, that is impossible to find anything meaningful with google.
This is like microsoft documentation. Have a vizard to find out my problen and I break my laptop with a hammer.

**Comment by lee-dohm** [comment]
Happy holidays! 🎁
