### ISSUE TITLE
2.10.0 doesn't install on 1.42.0 (Linux) 

### ISSUE THREAD

**Issue by bashguru** [atom/atom#20271]
**[SYSTEM]**
OS: Pop!_OS 19.10 x86_64 
Kernel: 5.3.0-7625-generic 
Shell: bash 5.0.3 

**DESCRIPTION**

> Installing “platformio-ide-terminal@2.10.0” failed.Hide output…
> 
> > node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install /tmp/apm-install-dir-1191125-18952-8v4tl4.ok4ys/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> > prebuild-install || node scripts/install.js
> 
> 
> Aborted (core dumped)
> Aborted (core dumped)
> gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
> gyp ERR! System Linux 5.3.0-7625-generic
> gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /tmp/apm-install-dir-1191125-18952-8v4tl4.ok4ys/node_modules/platformio-ide-terminal/node_modules/node-pty-prebuilt-multiarch
> gyp ERR! node -v v10.2.1
> gyp ERR! node-gyp -v v3.7.0
> gyp ERR! not ok 
> Aborted (core dumped)
> Aborted (core dumped)
> npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1191125-18952-8v4tl4.ok4ys/package.json'
> npm WARN apm-install-dir-1191125-18952-8v4tl4.ok4ys No description
> npm WARN apm-install-dir-1191125-18952-8v4tl4.ok4ys No repository field.
> npm WARN apm-install-dir-1191125-18952-8v4tl4.ok4ys No README data
> npm WARN apm-install-dir-1191125-18952-8v4tl4.ok4ys No license field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 134
> npm ERR! node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install: `prebuild-install || node scripts/install.js`
> npm ERR! Exit status 134
> npm ERR! 
> npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0-beta21.legacy install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/bashguru/.atom/.apm/_logs/2019-12-26T03_30_38_800Z-debug.log

**Steps to reproduce**
Open Settings->Install
Find platformio-ide-terminal 2.10.0
Click: Install.
Expected behavior:
The package should install. </code>

**Actual behavior:**
The package doesn't install.

**Reproduces how often:**
Always.

**Versions**
`$ atom --version
Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0`

`$ apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.42.0
python 2.7.17
git 2.20.1`

**NOTE**
I attempted the resolution from this closed ticket:
https://github.com/platformio/platformio-atom-ide-terminal/issues/812

$ mkdir $HOME/atom
$ cd $HOME/atom
$ sudo chown -R $USER:$USER .

I received the same result.

**Comment by lkashef** [comment]
Thanks for contributing!

It appears that this is being caused by the [hplatformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The Atom FAQ has information on how to contact the maintainers of any Atom community package or theme.
