### ISSUE TITLE
Building on Mint 16 (Ubuntu 13.10)

### ISSUE THREAD

**Issue by ResidentBiscuit** [atom/atom#2029]
This thread will document the troubles and solutions to said troubles of building on Mint 16.

Make you sure you have G++ installed. Haven't looked to see if you need a C++11 compliant compiler, but you the repos should have G++4.8.1, which does support most, if not all, of C++11 (think it still needs <regex> implemented>. I'm guessing this does not require C++11 due to the use of typedefs, and the VC++2010 requirements on Windows.

The npm package out of the repos is version 1.2.x. To upgrade, all you have to do is `sudo npm install -g npm` and you'll then have 1.4.10.

Current issue: script/build fails with
Traceback (most recent call last):
  File "/home/jready/Development/atom/build/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/jready/Development/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.11.0-12-generic
gyp ERR! command "node" "/home/jready/Development/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jready/Development/atom/apm/node_modules/atom-package-manager/node_modules/runas
gyp ERR! node -v v0.10.15
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm WARN package.json github-url-from-git@1.1.1 No repository field.
Traceback (most recent call last):
  File "/home/jready/Development/atom/build/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/jready/Development/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.11.0-12-generic
gyp ERR! command "node" "/home/jready/Development/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jready/Development/atom/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v0.10.15
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
chdir(): No such file or directory

There are also a ton of compiler warnings about unused typedefs. You can safely ignore those.

Will be looking into this error, and will report back with what I find.

**Comment by mnquintana** [comment]
https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md has much more complete build instructions now (including all of the dependencies you'll need first to build Atom).
