### ISSUE TITLE
backticks' weird autoclose behaviour on Mac

### ISSUE THREAD

**Issue by giorgiobeggiora** [atom/atom#20308]
### Prerequisites

* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

In order to type backticks, I have to do a ` and then a left or right arrow on my keyboard, to get the closing backtick.

### Steps to Reproduce

1.  in the editor, write a backtick pressing OPT+9

**Expected behavior:**

 an additional backtick should be added next the cursor

**Actual behavior:**

 the additional backtick will be added only pressing left or right arrow key, but in this way the cursor goes out of the backticks

**Reproduces how often:**

 100%

### Versions

Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

**Comment by Aerijo** [comment]
Hey @giorgiobeggiora, I'm not familiar with the `OPT+9` notation. Does this mean <kbd>alt-9</kbd>?

I was trying with just <kbd>alt-&#96;</kbd> though, and think I see what you mean. Pressing <kbd>alt-&#96;</kbd> will create a special backtick ready to turn into an accent, and pressing the arrow key turns it into a normal backtick. The `bracket-matcher` package then sees this backtick, adds the closing one, and the right arrow moves the cursor right, past them both.

TextEdit does the same thing though, as doing this before text in TextEdit will cause the cursor to move to the right of the first character. 

Given this behaviour is consistent with other macOS applications though, I doubt it will be changed in Atom. I'm not even sure if it's possible to change in Atom; the special accent behaviour appears to be handled by macOS. As an alternative to the right arrow, I found pressing space seems to work as you want it to.

**Comment by giorgiobeggiora** [comment]
Hi @Aerijo,

Hitting the spacebar is a good workaround, thank you for the suggestion. 

I googled and [found](https://stackoverflow.com/questions/53061569/backticks-in-javascript-file-not-auto-closing-in-vscode) the following declaration: 

> by default the backtick (`) is a dead key, meaning it will not produce a character until the next key is hit

I'm using an Italian keyboard for Mac that does not have the BACKTICK <code>`</code> key, so I didn't know about that. To write a backtick I use the combination of OPTION <code>⌥</code> key (the equivalent for ALT in Windows) plus <code>9</code> key.

I tested the behaviour in Visual Studio Code and It too works with a spacebar hit.

TextEdit doesn't have the "auto close quotes" feature.

Thanks again, I hope that in the future an option or package will add a feature to autoclose backticks without hitting any other key.

**Comment by giorgiobeggiora** [comment]
I just discovered that <code>OPT+\</code> is the solution for the Italian keyboard layout 🤦

In the Italian layout <code>\</code> key is where the <code>`</code> key is in the US layout.

**Comment by Aerijo** [comment]
> TextEdit doesn't have the "auto close quotes" feature.

No, but when you have `|foo` (`|` as the cursor), pressing `alt-9` and then rightarrow will result in `` `f|oo ``, showing it resolves the backtick and then the rightarrow separately.

In any case, that isn't the actual backtick key (it's for accenting letters) and you've found the proper shortcut, so this should be resolved.

**Comment by collimarco** [comment]
I'm trying to edit a markdown file with atom and Italian keyboard and there is a really weird behavior... It seems that there are many bug related to backticks. They don't work normally as they do on other editors or normal websites.

In particular there are issues when you enter three backticks for code snippets in markdown.
