### ISSUE TITLE
ENTER (RETURN) not working

### ISSUE THREAD

**Issue by jbrepogmailcom** [atom/atom#20302]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I just installed ATOM on Debian Jessie and I am connected over VNC. The Return key is not working and there is no emmet to disable. When I enable package Key Binding Resolver and press ENTER, I get white message (SPACE) in blue background

### Steps to Reproduce

1. launch atom (or atom --safe)
2. enable Key Binding Resolver
3. press ENER

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

### Versions

Atom 1.42.0
Electron 4.2.7

**Comment by Arcanemagus** [comment]
This sounds like an issue with how your VNC server is operating. Do you see this when accessing the machine locally?

**Comment by fawaz990** [comment]
0509949858 انا موفاهم البرنامج ذا اتصل بي
