### ISSUE TITLE
Atom does not detect the language (typescript) if I do not run atom with sudo.

### ISSUE THREAD

**Issue by sirpask** [atom/atom#20330]
4 days ago everything worked perfectly, and suddenly Atom stopped showing me the colors in the variables of the .ts files

Any suggestions? thanks.
on Ubuntu.

SS Up without sudo, down with sudo

![error_atom](https://user-images.githubusercontent.com/17196846/72617155-a9ec2a00-3938-11ea-914c-2c254b020638.jpg)

**Comment by lkashef** [comment]
I can see that the bottom right you have the Grammar set to `Plain Text`.

---

Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by lee-dohm** [comment]
@sirpask Sounds like you installed Atom as `root`, so it isn't operating properly when you run it as a normal user. You may want to uninstall Atom and reinstall according to the instructions in the [Atom Flight Manual](http://flight-manual.atom.io).

**Comment by sirpask** [comment]
Thanks... solved.

**Comment by lee-dohm** [comment]
I can't reproduce the behavior you're describing using Atom Nightly v1.45.0-nightly0 on macOS 10.15.2. If you're still running into problems, you should take a look at our [support resources](https://github.com/atom/blob/master/SUPPORT.md).

**Comment by sirpask** [comment]
Ok, all solved.

I have had to uninstall all the community packages, and I have reset the .atom / config.cson file

I have only left this code:

"*":
  core:
    telemetryConsent: "no"
  "exception-reporting":
    userId: "xxxxxxx-xxxx-xxxxx-xxxx-xxxxxxxxxxxxx"

And it has already begun to detect the TypeScript language.

I will try to detect what configuration and what package I was giving the problem by gradually installing them again.

**Comment by sirpask** [comment]
The problem was in the package Kite. v0.176.0.

thanks.

**Comment by FREECREDIT10MYR** [comment]
🔥NAK MENJANA INCOME SETIAP HARI TAMPA MEMERLUKAN MODAL 👇🔥

🔥INVITE DAN REGISTER SAHAJA🔥

🔥MAU MENJANA INCOME SETIAP HARI TAMPA MEMERLUKAN MODAL ATAU CARI ORANG INILAH LINK YANG WAJIB DIDAFTAR 🔥

STEP 1.👇

💥JOIN TELEGRAM CHANNEL💥👇

https://t.me/FREECREDIT20MYRCHANNEL

STEP 2 .👇

💥JOIN TELEGRAM GROUP💥👇

@FREECREDIT20MYR

STEP 3.👇

🔥INVITE TELEGRAM GROUP 100 ORANG

STEP4:👇

💥SHARE INI POST KE 6 GROUP 

🔥WASSAP🔥 FACEBOOK🔥
 🔥TELEGRAM 🔥 


🔥HANYA REGISTER🔥

FOLLOW THIS LINK👇👇👇

(1)https://www.virtualmining.farm/signup/?referrer=5E13C5F45E09A💯

(2)https://getzen.cash/auth/register?ref=185056💯

(3)-https://minepi.com/FreeCredit070707myr💯

(4)https://uplibra.io/?refer=778805#.XhQoYxOjNmw.telegram💯

(5)https://www.coinpayu.com/?r=FREECREDIT20💯

(6)https://uzemoney.xyz/7815024065995💯

(7)http://jomkiss.com/claim?r=88983💯

(8)https://dropbit.me/r/@FREECREDIT07070💯

(9)https://www.mobrog.com/my/paid-online-surveys/sign-up-malaysia.html?membership_promotion=0&i_invite=9932249-5e1c45d1e543b💯

(10)
https://hourspayday.com/?ref=FREECREDIT200MYR 💯     

(11)https://bitcoinaliens.com/?ref=1215811&game=8&pf=2💯

(12)https://supercryptofinance.com/sys/register.php?trader=Freecredit20myr💯

(13)https://cashzinedownload-jzc6w32blq-an.a.run.app/DownloadMe.html?571669💯

🔥 KEJAYAAN BERMULA DENGAN SATU LANGKAH 🔥


💥PAYPAY💥👇

https://www.paypal.com/paypalme/my/profile💯

💥 WHATSAPP💥👇

https://www.wasap.my/60168758920💯

💥 TWITTER💥👇

https://twitter.com/FREECREDIT07070💯

💥YOUTUBE💥👇

https://youtu.be/aHJXukC6Eek💯

💥 FACEBOOK 💥👇

https://www.facebook.com/groups/489043962017047/?ref=group_header💯

https://www.facebook.com/Freecredit20/💯

https://www.facebook.com/farah.azwin.90💯

https://www.facebook.com/100045791633362/posts/112208363648884/💯

💥LINKED💥👇

https://www.linkedin.com/in/free-free-credit-b7092219a💯

💥MYCHIMPSITES💥👇

http://httpfreecredit10myrgmailcom.mailchimpsites.com💯

💥REDDIT💥👇

https://www.reddit.com/u/FREECREDIT10MYR?utm_medium=android_app&utm_source=share💯

💥 INSTAGRAM 💥👇

https://www.instagram.com/freecredit20myrrr?r=nametag💯

💥TUMBLY💥👇

Check it out
https://freecredit200myr.tumblr.com/post/190147202501/httpsetorotw36b4ktx💯

💥 DISCORD 💥👇

https://discord.gg/https://

discord.gg/zQ3meUb💯

https://discord.gg/💯

https://discord.gg/efux8e hntar💯

💥 PINTEREST 💥👇

https://pin.it/ym2mbebcwgktds💯

💥GITHUB💥👇

https://github.com/FREECREDIT10MYR💯

https://github.com/FREECREDIT10MYR/FREECREDIT20MYR#freecredit20myr💯

https://github.com/FREECREDIT10MYR/POSTMan-Chrome-Extension.git💯

💥DROPBOX💥👇 

https://www.dropbox.com/transfer/AAAAAGBhlCg50vt302884WZuUDeJAWaF9uiMCyc6vsYnhD9ynFwB9xg💯

💥BLOG💥👇

https://freecredit20myr.wordpress.com/author/mimpiencikmimpi/💯

https://freecredit20myr.wordpress.com/2020/01/19/https-t-me-freecredit20myrrr/💯

💥KIBANA💥👇

https://kibana-ci.elastic.co/user/freecredit10myr💯

https://kibana-ci.elastic.co/user/freecredit10myr/credentials/store/user💯

💥POSTMAN💥👇

https://explore.postman.com/team/43emcYQE4GK9y3💯

🔥SUBSCRIBE SEMUA 🤗🤗🤗🔥

🔥REGISTER FOR CLAIM MYR EVERYDAY20🔥

🔥💯TRUSTED 🔥COMPANY💯🔥

**Comment by oxydeon** [comment]
same problem on Windows 10, Atom 1.43.0

**Comment by sirpask** [comment]
The problem is exactly that this line is in the config.cson file:
    **useTreeSitterParsers: false**

if you delete it, atom will detect the TypeScript language again.

regards.

**Comment by sli** [comment]
I don't have Kite installed, but I can confirm that the solution from @sirpask fixed the problem for me after an update to 1.45.0 (somehow) caused this bug.

**Comment by lkashef** [comment]
@sli can you confirm if you followed the prerequisites of submitting an issue and trying the solution above?

You can find the prerequisites in the template when reporting a new issue, it might not be the same package but it might still be a community package problem, if you feel it's unrelated it might be worth opening a separate issue with more details to help us reproduce the bug.
