### ISSUE TITLE
BIG Files

### ISSUE THREAD

**Issue by marcdubois71450** [atom/atom#20348]
It's a bug or it's normal, I'm not at the bottom of the scroll and the lines no longer appear!

![Bug_Atom](https://user-images.githubusercontent.com/38250422/72995342-051a9280-3df9-11ea-9a5f-b51ed08b57c9.png)

The image is pretty telling I think!

**Comment by darangi** [comment]
Thanks for contributing!

All new issues now require steps to reproduce (also called "repro steps") the problem or the behavior you wish to see in Atom. We do this so we can be certain that we are understanding what it is you're describing and don't prematurely close the issue or implement the wrong feature. If you need help writing detailed repro steps, please see the [How Can I Contribute? section of the Atom CONTRTIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
