### ISSUE TITLE
Can't install the .deb package in Ubuntu 20.04 (Focal Fossa) development branch (due to changes in Ubuntu's python packaging)

### ISSUE THREAD

**Issue by DeeDeeG** [atom/atom#20356]
[Update:  Fixed by #20406. This is fixed in `atom-nightly` now, will presumably be fixed in `atom-beta` and `atom` once those reach version 1.47. To workaround, do `sudo apt install atom-nightly`, or once Ubuntu 20.04 is released you should be able to do `sudo apt install python-is-python2 atom`.]

### Description

The `atom` package fails to install on Ubuntu 20.04 (Focal Fossa) development branch, because Atom's dependency `python` can't be installed.

### Steps to Reproduce

1. boot an up-to-date daily ISO image of Ubuntu 20.04 (Focal Fossa) development branch, OR install Ubuntu 20.04 and ensure all apt updates are installed (`sudo apt dist-upgrade`)
2. Attempt to install the `atom` text editor .deb package ([standalone .deb file](https://atom.io/download/deb) or from [the Atom packagecloud repository](https://packagecloud.io/AtomEditor/atom)).

**Expected behavior:**

Atom should install successfully on Ubuntu 20.04.

**Actual behavior:**

Installation fails due to missing/non-installable dependency `python` (which, as of recently, conflicts with some similarly-named packages that are already installed).

**Reproduces how often:**

100% of the time.

### Versions

OS: Ubuntu 20.04 Focal Fossa development branch, as of about January 7th-ish.

Atom: Any version, I think? (Any version of Atom that depends on the `python` package).

### Additional Information

The `atom` package depends on the `python` package. But this package seems to have been discontinued recently, and replaced with similar-named packages as part of the transition away from Python 2 toward Python 3 as the default Python. So `python` can't be installed without uninstalling the default packages for said programming language.

Due to some changes in Ubuntu's package repositories for 20.04 (Focal Fossa), the `python` package is not installed anymore by default in Ubuntu 20.04 (Focal). It also conflicts with the `python2` and related packages that _are_ installed now. So the `python` package can't be installed, and consequently the `atom` package, which depends on the `python` package` can't be installed either.

See this [changelog](http://changelogs.ubuntu.com/changelogs/pool/universe/p/python-defaults/python-defaults_2.7.17-2ubuntu2/changelog) entry for the `python2` package for details:

>   * Stop building the python, python-dev, python-dbg, python-doc,
    python-minimal, libpython-dev, libpython-dbg, libpython-stdlib packages.
>
> -- Matthias Klose <doko[AT]ubuntu.com>  Mon, 06 Jan 2020 12:02:01 +0100

This just happened to me today after doing routine package updates; I needed to uninstall `atom` in order to install all of the updates, including some related to `python`. Since then, my system can't reinstall atom.

I suppose there is a chance this is just a temporary mistake or mishap upstream at the Ubuntu repos, and perhaps not being able to install the `python` package is unintentional. If you'd like me to try again in a few days, to update my packages and try to install atom again to see if this issue is still occurring, just send me a comment on this issue -- I'll get back to you saying whether it is still an issue or if it has been fixed.

**Comment by zorn-v** [comment]
Same here. I came here to create similar issue but you done it better :smile:

**Comment by zorn-v** [comment]
```bash
wget http://mirrors.kernel.org/ubuntu/pool/universe/p/python-defaults/python2_2.7.17-1_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/universe/p/python-defaults/python2-minimal_2.7.17-1_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/universe/p/python-defaults/libpython2-stdlib_2.7.17-1_amd64.deb
sudo dpkg -i libpython2*.deb python2*.deb
sudo apt install atom
```

**Comment by Aerijo** [comment]
As far as I can tell, Python2 is only required for building native modules with the bundled node-gyp. It might be possible now to upgrade it to Python3, as node-gyp has landed Python3 support. This would need to be done in `apm`.

Assuming it's just for that, it might also be possible to remove it entirely for the prebuilt distributions.

**Comment by DeeDeeG** [comment]
@zorn-v I can confirm that your workaround that you posted works... Just that the `dpkg -i` step errors out the first time due to one of the three downgraded packages (`python2-minimal`)  being a pre-requisite for the other two... Running the same `dpkg -i` command twice resolves the dependencies properly and successfully downgrades the relevant Python packages. (Or one can install `python2-minimal` first, separately from the other two packages... see my updated script below.)

I updated the script slightly (so it won't give any errors), by splitting the `dpkg -i` step into two commands.

```sh
   mkdir old_python_debs && cd old_python_debs \
&& wget http://mirrors.kernel.org/ubuntu/pool/universe/p/python-defaults/python2_2.7.17-1_amd64.deb \
&& wget http://mirrors.kernel.org/ubuntu/pool/universe/p/python-defaults/python2-minimal_2.7.17-1_amd64.deb \
&& wget http://mirrors.kernel.org/ubuntu/pool/universe/p/python-defaults/libpython2-stdlib_2.7.17-1_amd64.deb \
&& sudo dpkg -i python2-minimal_2.7.17-1_amd64.deb \
&& sudo dpkg -i libpython2-stdlib_2.7.17-1_amd64.deb python2_2.7.17-1_amd64.deb \
&& sudo apt install atom
```

Optionally delete the old python debs after this, with `rm -r old_python_debs`.

**Comment by zorn-v** [comment]
Seems `python` package was completely removed from ubuntu repo. Maybe change dep to `python2` for now and then to `python3` ?
Here
https://github.com/atom/atom/blob/917a00e195b93c8c2a9adc349fd8fa1844f61dbc/resources/linux/debian/control.in#L3

**Comment by DeeDeeG** [comment]
@zorn-v that looks reasonable to me, as a random atom user. Particularly, the `python | python2` requirement appears like it would work on older Ubuntu, such as 16.06 and 18.04, 19.10, due to allowing `python` to be used, but will now _aditionally_ work with Ubuntu 20.04, due to allowing `python2` as an alternative for `python`.

Nice backward-compatibility. Also a nice"minimal intervention" style of fix. 👍

**Comment by wheelcomplex** [comment]
@zorn-v FYI: the slack-desktop (slack for ubuntu) all so failed for the same issue in 20.04, change dep to python2 works well (repack the official deb).

**Comment by DeeDeeG** [comment]
Update on the situation, with comments from Canonical:

https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-20.04-Clear-Python2

https://lists.ubuntu.com/archives/ubuntu-devel/2020-February/040918.html

Basically using `python2` as your dependency is the best way to depend on Python 2 in Focal, from a packager's perspective.

For upgrades from older Ubuntu: There will be a package `python-is-python2` that "provides" the `python` package dependency, so this should save folks who upgrade from e.g. Bionic, Xenial or Eoan. But if I understand correctly, this will _not_ be included on fresh installs of Focal. So relying on that leaves fresh Ubuntu 20.04 LTS install users unable to install `atom` without manually installing `python-is-python2` to sort things out.

Depending on `python-is-python2` in the `atom` package's dependencies is not recommended, as it would be unnecessary and invasive to the system -- it would change the behavior of the `python` command for the whole system to mean `python2`.

Depending on the `python2` package is good enough to solve this problem for Focal users. (`python | python2` seems like the best for Focal + backward compatibility with older Ubuntu, IMO.)

**Comment by zorn-v** [comment]
I hope they plan how to migrate to python3 instead of support python2. April is in next two month )

**Comment by zorn-v** [comment]
My opinion - after purhasing github by microsoft, atom is like zombie. But I like zombies )

**Comment by zorn-v** [comment]
@wheelcomplex Oh realy. Did you notice behind "atom" and "electron" ?
BTW electron was named "atom-shell" before

**Comment by rodrigopmatias** [comment]
We know that developers start testing new versions of ubuntu a month or two before it becomes stable, and for that we tested the tools we used to develop, it would be very interesting that the atom could work, even in the night version to have a idea of how everything will work.

As well as desktop environments, many server environments will be migrated since this version of ubuntu is LTS, so it would be very interesting to be able to test the atom in this new LTS.

**Comment by v1r0x** [comment]
@DeeDeeG Unfortunately, your fix doesn't work (anymore?) on latest dev build of Ubuntu 20.04. I tried installing `python-is-python2-but-deprecated` and installing `python2` and `python3` as alternatives
```bash
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
sudo update-alternatives --config python
```
but I still get the error
```bash
Preparing to unpack .../Downloads/atom-amd64.deb ...
Unpacking atom-beta (1.46.0-beta0) over (1.46.0-beta0) ...
dpkg: dependency problems prevent configuration of atom-beta:
 atom-beta depends on libgconf-2-4 (>= 3.2.5) | libgconf2-4; however:
  Package libgconf-2-4 is not installed.
  Package libgconf2-4 is not installed.
 atom-beta depends on python; however:
  Package python is not installed.

dpkg: error processing package atom-beta (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Errors were encountered while processing:
 atom-beta
```

**Comment by DeeDeeG** [comment]
Hi @v1r0x,

My most recent comment was about how to re-package the `atom` package (what dependencies to use in the `atom` package itself). It isn't helpful for getting the current `atom` packages installed on Ubuntu Focal. (I think the solutions you tried don't install a package named `python`, so `apt` will still be unsatisfied and fail to install `atom`... That's how it will be for now, until the atom devs update `atom's` packaging/dependencies.)

For workarounds that still work, see either of these comments:
- https://github.com/atom/atom/issues/20356#issuecomment-578376727
  - (from @zorn-v)
- https://github.com/atom/atom/issues/20356#issuecomment-578418796
  - (my slightly edited version of the same thing. More script-ified, and it can be run without seeing errors, and it puts the python debs in their own folder for safe keeping, etc.)

**Comment by v1r0x** [comment]
Ok, sorry for the misunderstanding and thanks for the explanation!
Let's hope the next (beta) release runs fine on 20.04 :crossed_fingers:

**Comment by DeeDeeG** [comment]
On second thought, I'm surprised that installing `python-is-python2-but-deprecated` doesn't solve the problem. But I can confirm it doesn't fix the issue. Wow.

**Comment by zorn-v** [comment]
> I wonder where I can file a bug about this with Ubuntu

Try here https://launchpad.net/ubuntu/focal/

**Comment by v1r0x** [comment]
I found another solution to install atom on Ubuntu 20.04

With dpkg you can repack an existing deb package. This way you don't have to mess with downgrading packages.

```bash
dpkg -x atom-amd64.deb atom-src
dpkg -e atom-amd64.deb atom-src/DEBIAN
# Modify python dependency in atom-src/DEBIAN/control (from python to python | python2
dpkg -b atom-src/ new-atom-amd64.deb
sudo dpkg -i new-atom-amd64.deb
```

**Comment by dayfuaim** [comment]
_For a while_, I did it too.
And held back the version in Synaptic.

Atom works _for now_.

But waiting to be fixed shortly. :)

**Comment by DeeDeeG** [comment]
Heads up to everybody: You can now install `atom-nightly` on Ubuntu 20.4 Focal Fossa! :tada: 

This PR got merged to fix the problem: #20406

Next time a beta or stable build happens of atom 1.47, those would be installable on Ubuntu 20.04 as well. Check here to see if said packages have been built yet: https://packagecloud.io/AtomEditor/atom/

(I assume the current stable/beta branches of atom, 1.45 and 1.46 respectively, probably won't have this fix backported, so only `atom-nightly` has the fix, for now. When 1.47 hits beta, `atom-beta` will be installable, then when 1.47 hits stable, plain old `atom` will be installable on Ubuntu 20.04.)

**Comment by v1r0x** [comment]
That's good news! Thanks for the info.
Let's hope the next release will be released anytime soon. 🚀

**Comment by sryze** [comment]
This workaround worked for me on Ubuntu 20.04:

```
sudo dpkg --ignore-depends python -i atom-amd64.deb
```

**Comment by DeeDeeG** [comment]
@sryze that does work to install atom, but there is a downside to that method. When you try to upgrade your system with `apt upgrade`, it says you have broken packages.

(Personally, I prefer downloading `atom-nightly` for now on Ubuntu Focal, simply because it doesn't require workarounds.)

---

If you must install stable `atom` right now on Focal, I think the best (most minimal-impact) workaround is modifying the `.deb` package to not require just `python`, but also allow `python2`.

You can do the following (based on @v1r0x's [comment](https://github.com/atom/atom/issues/20356#issuecomment-603762624) above):

```sh
### repackage_atom.sh
mkdir -p repackage_atom && cd repackage_atom \
&& wget https://packagecloud.io/AtomEditor/atom/packages/any/any/atom_1.45.0_amd64.deb/download -O atom_1.45.0_amd64.deb \
&& dpkg -x atom_*.deb atom_deb_files \
&& dpkg -e atom_*.deb atom_deb_files/DEBIAN \
&& sed -i 's/, python,/, python | python2,/g' atom_files/DEBIAN/control \
&& dpkg -b atom_deb_files/ atom-with-fixed-dependencies.deb \
&& sudo apt install -y ./atom-with-fixed-dependencies.deb \
&& cd -
```

**Comment by Native-Coder** [comment]
> @sryze that does work to install atom, but there is a downside to that method. When you try to upgrade your system with `apt upgrade`, it says you have broken packages.
> 
> (Personally, I prefer downloading `atom-nightly` for now on Ubuntu Focal, simply because it doesn't require workarounds.)
> 
> If you must install stable `atom` right now on Focal, I think the best (most minimal-impact) workaround is modifying the `.deb` package to not require just `python`, but also allow `python2`.
> 
> You can do the following (based on @v1r0x's [comment](https://github.com/atom/atom/issues/20356#issuecomment-603762624) above):
> 
> ```shell
> ### repackage_atom.sh
> mkdir -p repackage_atom && cd repackage_atom \
> && wget https://packagecloud.io/AtomEditor/atom/packages/any/any/atom_1.45.0_amd64.deb/download -O atom_1.45.0_amd64.deb \
> && dpkg -x atom_*.deb atom_deb_files \
> && dpkg -e atom_*.deb atom_deb_files/DEBIAN \
> && sed -i 's/, python,/, python | python2,/g' atom_deb_files/DEBIAN/control \
> && dpkg -b atom_deb_files/ atom-with-fixed-dependencies.deb \
> && sudo apt install -y ./atom-with-fixed-dependencies.deb \
> && cd -
> ```
> 
> [Edit: fixed a typo in the script. Whoops!]

When I do this i get ```E: Unable to locate package atom```

**Comment by DeeDeeG** [comment]
Hi, @sryze.

 I should have posted an update at the bottom of this thread... Better late than never I suppose. There is no need for workarounds anymore.

You can install atom like normal on Ubuntu Focal Fossa. (`sudo apt install atom` just works.)

---

There is now a package called `python-is-python2` that tells `apt` that it "provides" the `python` dependency. This package `python-is-python2` was set up this way on about April 16th, only a week before Ubuntu Focal Fossa was released.

In hindsight, I should have understood that was going to happen. It was announced ahead of time. I simply misunderstood the details and exact meaning of certain parts of the announcement. The issue turned out not to be a problem at all in the final release of Ubuntu Focal Fossa.

---

I am also working on fully enabling Python 3 support in `apm`/`atom`. See: https://github.com/atom/apm/pull/887 and https://github.com/atom/atom/issues/20585. This is to prepare for the next Ubuntu/Debian releases, which aren't planning to ship Python 2 at all.
