### ISSUE TITLE
How to uninstall in Linux?

### ISSUE THREAD

**Issue by rhoconlinux** [atom/atom#2035]
Hi there. Again. 

I successfully installed the program on Linux but I want to check replicability of my installation process on Ubuntu 14.04. In order to do that I need to uninstall all Atom files.  However, I don't know how to wipe them all out. 

Any suggestions?

**Comment by 50Wliu** [comment]
I'm going to close this.  In the future, these types of issues might be better suited for [Discuss](https://discuss.atom.io).
