### ISSUE TITLE
open files with atom:// handler

### ISSUE THREAD

**Issue by matreyes** [atom/atom#2037]
It should open an html handler like:
The handler opens atom, but doesn't works with params.
atom://open?url=file://Users/myuser/myapp/myfile.rb&line=32&column=12

it would be very useful for rails_panel !

**Comment by jaredmoody** [comment]
+1

**Comment by jmuheim** [comment]
:+1: This is the only thing keeping me from abandoning TextMate2 in favour Atom at the moment.

**Comment by martinratinaud** [comment]
agreed

**Comment by lifeiscontent** [comment]
@izuzak any updates on this?

**Comment by izuzak** [comment]
> @izuzak any updates on this?

@lifeiscontent I think @thedaniel has been making some progress in this area, see for example https://github.com/atom/welcome/pull/38 and https://github.com/atom/settings-view/pull/614.

**Comment by lifeiscontent** [comment]
@izuzak thanks! :+1:

**Comment by EloB** [comment]
+1

**Comment by shanept** [comment]
+1

**Comment by WizardOfOgz** [comment]
I would also like to see this feature built into Atom directly. Until that happens, and if you are on OSX, you can use this project I started which will open links with the atm:// protocol in Atom. https://github.com/WizardOfOgz/atom-handler

**Comment by shanept** [comment]
Interesting, WizardOfOzg - I'm working on a plugin to give us an atm:// handler too

**Comment by jmatsushita** [comment]
Apart from @WizardOfOgz OSX handler there is also a Linux based handler (which I haven't tested) https://github.com/eclemens/atom-url-handler

**Comment by UziTech** [comment]
Looks like they just merged the pull request for this :tada: #11399 

Hopefully out soon!!

**Comment by pabloab** [comment]
Going to [Atom home page](https://atom.io/#teletype) and clic on [atom://settings-view/show-package?package=teletype](atom://settings-view/show-package?package=teletype) don't do anything on my Ubuntu 16.04 LTS. So [I do this](https://askubuntu.com/a/1023143/349837):

- Edit `/usr/share/applications/atom.desktop`
- Append `x-scheme-handler/atom;` to line starting `MimeType=text/plain;`
- Register the protocol: `xdg-mime default atom.desktop x-scheme-handler/atom`

Now browser runs atom but just open a new file. With `xdg-open` on CLI: _Client failed to connect to the D-BUS daemon:_ and _Failed to connect to socket /tmp/dbus-2i6A77jamf: Connection refused_. I'm missing something or should file a new bug...?

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

**Comment by Arcanemagus** [comment]
Please update to a current version of Atom @pabloab, if you are still having issues after doing that please file a new issue, thanks!

**Comment by pabloab** [comment]
Just installed last version from .deb package, now:
Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
Same things happen, but `atom "atom://settings-view/show-package?package=teletype"` works (of course almost nobody visiting atom.io would do this). Maybe I did something wrong registering MIME type / URL scheme on my system.

**Comment by shanept** [comment]
@pabloab Last I saw, they don't register the mime time with the OS - absurd as it is very simple to do.

**Comment by UziTech** [comment]
@shanept A PR would be much appreciated
