### ISSUE TITLE
Snakefile detected as source.python, should be source.yaml

### ISSUE THREAD

**Issue by HDembinski** [atom/atom#20382]
### Description

https://snakemake.readthedocs.io/en/stable/ is a popular tool in data science. It parses so-called "Snakefile"s which are similar to "Makefile"s.

The grammar selector detects a "Snakefile" as source.python, but it should be source.yaml. This causes issues with linters and autoformatters like python-black, which should not be run for Snakefiles.

### Steps to Reproduce

1. Generate a file called "Snakefile" with the following content:
```
import glob

rule all:
    input: ["data/foo.root", "data/bar.root"]

rule make_foo:
    input: "{name}.root"
    output: "{name}_pv.root"
    shell: "./make_foo.py {input} {output}"
```

2. Open file in Atom, it is detected as python.source.

**Expected behavior:**

The grammar selector should detect a "Snakefile" as source.yaml.

**Actual behavior:**

The grammar selector detects a "Snakefile" as source.python.

**Reproduces how often:**

Always.

### Versions

Atom    : 1.43.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

**Comment by isiahmeadows** [comment]
Try opening an issue in the relevant packages, https://github.com/atom/language-python and https://github.com/atom/language-yaml. You might have better luck there.

**Comment by Arcanemagus** [comment]
You can customize language recognition following [these steps in the documentation](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition).

It's likely your `import` at the top that is messing up the automatic detection, possibly adding a comment before that might help, but automatically determining the language for a file will always be a guessing game if you don't explicitly specify it.

Thanks for taking the time to file an issue though!

**Comment by HDembinski** [comment]
@Arcanemagus This is a non-solution since Snakefiles, like Makefiles, do not have an extension. I cannot give them an extension. A solution has to detect the filename "Snakefile" and then set the language accordingly. I checked the steps in the documentation (thanks for the link), but it is not possible to customizing language recognition based on the filename, only based on the extension.

Please reopen.

**Comment by HDembinski** [comment]
If anyone stumbles over this: a workaround is to install https://atom.io/packages/vim-modeline and put this line on top of each Snakefile
`# atom: set grammar=yaml:`
