### ISSUE TITLE
Atom crashes randomly when interacting with tree view

### ISSUE THREAD

**Issue by evgenyneu** [atom/atom#20405]
Atom keep crashing, the crash is random, but it happens to me about about 10-30% of the time I interact with the tree view via right-click menu and choosing things like "copy project path", "new file" among others. I get crashes many times in an hour an this is very annoying.

I know this bug report is not very helpful, because it is not reproducible. But is there a way to get a crash report and find exactly what caused the crash? I looked at Console.app, but it does not have "User Reports" option mentioned in [Debugging](https://flight-manual.atom.io/hacking-atom/sections/debugging/).

Thanks

Atom 1.44.0 on MacOS 10.15.3.

(Atom was crashing for me for several months in older versions as well)

**Comment by UziTech** [comment]
could be part of #20034

**Comment by evgenyneu** [comment]
@UziTech thanks, sorry for the duplicate.
