### ISSUE TITLE
Colors disappearing after about 135 characters in PHP code

### ISSUE THREAD

**Issue by JoeyEamigh** [atom/atom#20426]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Write out a line of code that exceeds about 135 characters with the PHP syntax on.
2.  Look as the colors between quotes, etc. are no longer showing up

**Expected behavior:**

I would expect that the colors continue to stay consistent throughout the document.

**Actual behavior:**

The colors abruptly stop at 135 characters.

**Reproduces how often:**

Every singe time on multiple devices.

### Versions

Atom    : 1.44.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.44.0
python 3.8.1
git
visual studio

Windows 10 v1909

### Additional Information

I have done this on multiple devices. I have no idea why it happens.
![image](https://user-images.githubusercontent.com/55670930/74687281-f928b300-51a1-11ea-8fee-b2324b953453.png)

**Comment by UziTech** [comment]
this would be a question for https://github.com/atom/language-php

**Comment by Arcanemagus** [comment]
You are either running into the maximum tokens per line limit (odd for such a small character count) (Atom issue), or a bug in the tokenizer (language-php issue).

Can you post the _exact_ code you are seeing this on so we can narrow down the issue?
