### ISSUE TITLE
When you click a menu, such as creating a new file, the atom application sometimes exits unexpectedly

### ISSUE THREAD

**Issue by Brolly0204** [atom/atom#20438]
## Versions
Atom: 1.44.0
MacOs: 10.15.3

## Installed plugin
├── Hydrogen@2.14.0
├── Leetcode@0.11.1
├── Stylus@3.2.0
├── TabNine@2.1.7 (disabled)
├── ace-material-syntax@1.5.0
├── activate-power-mode@2.7.0 (disabled)
├── atom-beautify@0.33.4
├── atom-ide-debugger-python@0.7.3
├── atom-ide-ui@0.13.0 (disabled)
├── atom-jade@0.3.0
├── atom-jest-snippets@2.2.0 (disabled)
├── atom-live-server@2.3.0
├── atom-lupa@0.7.43
├── atom-material-syntax@1.0.8
├── atom-material-syntax-dark@1.0.0
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@2.1.3
├── atom-one-dark-syntax@1.13.0
├── atom-path-intellisense@1.2.2
├── atom-react-autocomplete@0.1.10
├── atom-runner@2.7.1
├── atom-solarized-dark-syntax@1.2.7
├── atom-ternjs@0.20.0
├── atom-typescript@13.5.0
├── atom-wrap-in-tag@0.6.0
├── autoclose-html@0.23.0
├── autocomplete-clang@0.12.1
├── autocomplete-html-entities@0.2.0
├── autocomplete-json@5.5.2
├── autocomplete-modules@2.3.0
├── autocomplete-paths@2.12.2
├── autoprefixer@4.2.0
├── block-comment@0.4.3 (disabled)
├── build@0.70.0
├── busy-signal@2.0.1
├── cdos-material-syntax@0.1.0
├── cdos-material-ui@1.2.0
├── chester-atom-syntax@0.3.2
├── city-lights-ui@1.5.3
├── codelf@13.2.0
├── color-picker@2.3.0
├── comment@0.6.1
├── csslint@1.2.0
├── dark-one-dark-syntax@2.3.0
├── dimmed-one-dark-syntax@1.9.5
├── docblockr@0.13.7
├── docker@0.8.0
├── emmet@2.4.3
├── es6-javascript@1.0.0
├── file-icons@2.1.39
├── git-control@0.9.0
├── git-plus@8.7.1
├── goto-definition@1.3.4 (disabled)
├── highlight-selected@0.17.0
├── hyperclick@0.1.5
├── ide-python@1.5.0
├── ide-typescript@0.9.1 (disabled)
├── intellij-idea-keymap@0.2.3
├── intentions@1.1.5
├── javascript-snippets@1.2.1
├── jquery-snippets@11.0.0 (disabled)
├── js-hyperclick@1.13.3
├── language-babel@2.85.0
├── language-docker@1.1.8
├── language-ejs@0.4.0
├── language-graphql@1.0.0
├── language-haskell@1.19.4
├── language-ini@1.23.0
├── language-javascript-jsx@0.3.7
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-markdown@0.37.0
├── language-mongodb@0.3.1
├── language-ocaml@1.9.5
├── language-pug@0.0.22
├── language-rust@0.4.12
├── language-scala@1.1.10
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── language-vue@0.26.0
├── learn-ide-material-ui@1.3.15
├── linter@2.3.1 (disabled)
├── linter-csslint@2.0.6
├── linter-docker@0.3.2
├── linter-eslint@8.5.5
├── linter-gcc2@0.8.8
├── linter-jshint@3.1.19 (disabled)
├── linter-ui-default@1.8.1 (disabled)
├── markdown-img-paste@0.4.0
├── markdown-preview-enhanced@0.17.7
├── markdown-preview-plus@3.11.5
├── material-colors@0.1.0
├── material-syntax@0.6.1
├── material-ui@1.0.10
├── minimap@4.29.9
├── minimap-quick-highlight@1.0.1
├── monokai@0.24.0
├── node-debugger@1.10.1 (disabled)
├── nucleus-dark-ui@0.12.3
├── nuclide@0.366.0
├── nuclide-format-js@0.0.47
├── oceanic-one-dark-syntax@2.0.0
├── one-dark-atom@1.7.1
├── one-dark-lite-syntax@0.1.0
├── one-dark-ocean-syntax@4.4.7
├── one-dark-pro-vivid-syntax@2.3.0
├── one-dark-vivid-syntax@1.8.1
├── open-in-browser@0.5.2
├── pdf-view@0.72.0
├── pigments@0.40.2
├── platformio-ide-debugger@1.2.6
├── platformio-ide-terminal@2.10.0
├── prettier-atom@0.58.2
├── project-manager@3.3.8
├── quick-highlight@0.13.0
├── react@0.18.0 (disabled)
├── react-redux-atom-snippets@0.7.2 (disabled)
├── react-snippets@1.2.0
├── script@3.25.0
├── set-syntax@0.4.0
├── sort-lines@0.19.0
├── source-preview-pug@0.2.0
├── sync-settings@3.0.0 (disabled)
├── tool-bar@1.2.0
├── tool-bar-main@0.0.12
├── vue2-autocomplete@0.1.0-alpha.4
├── vuejs2-snippets@1.1.0
└── xml-formatter@0.13.0

**Comment by sethfloydjr** [comment]
Im seeing the same issue with the same version of Atom. 1.44.0
Fresh install and here are the only packages i have installed...
atom-beautify@0.33.4
atom-monokai@0.10.9
busy-signal@2.0.1
git-status@0.3.4
intentions@1.1.5
language-terraform@0.8.1
linter@2.3.1
linter-python@3.1.2
linter-terraform-syntax@1.4.0
linter-ui-default@1.8.1
markdown-writer@2.11.9
minimap@4.29.9
monokai@0.24.0
monokai-seti@0.9.0
seti-syntax@1.2.0
seti-ui@1.11.0
split-diff@1.6.1
tree-view-git-status@1.5.3

I typically see this when I right click on New File, New Folder, Copy File Path.
Actually as i typed that I right clicked in the menu to see the sub menu items that I typically click...without even clicking on the submenu, I clicked in my browser to get focus here and Atom crashed.

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

---

@Brolly0204 and @sethfloydjr thanks for the report folks, just something very important to point out, following the steps on the template can be very helpful and you definitely need to run Atom in the safe mode with all plugins/packages disabled, in case one of the community packages are causing this then it's up to the developer to resolve it or reach out to us if there is a conflict.

**Comment by Brolly0204** [comment]
> Thanks for reaching out!
> 
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> Thanks for understanding and meeting us half way 😀
> 
> @Brolly0204 and @sethfloydjr thanks for the report folks, just something very important to point out, following the steps on the template can be very helpful and you definitely need to run Atom in the safe mode with all plugins/packages disabled, in case one of the community packages are causing this then it's up to the developer to resolve it or reach out to us if there is a conflict.

I think it's time to upgrade the electronic and node versions, which vscode team did well, but I also like atom

**Comment by orchidfire** [comment]
Keep happening to me to

**Comment by orchidfire** [comment]
@lkashef  link to template ?

**Comment by Brolly0204** [comment]
The application of atom is not stable enough, and the application starts slowly taking up CPU. I hope it can be improved

**Comment by lkashef** [comment]
> @lkashef link to template ?

@orchidfire when you report a new issue, the body will have the template by default
