### ISSUE TITLE
Atom with strange behavior when you suspend the OS

### ISSUE THREAD

**Issue by wjuniorw** [atom/atom#20439]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
   * [x] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * [x] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * [x] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
 The Problem ocurred at suspend the OS (ElementaryOS and ubuntu flavors in my case) wiht the project opened in atom.
When awake de system Atom 
* works slowly 
* do not open new panes or switch between open panes.
* can`t save changes on files

After refreshing(ctrl+ shift + f5) the same issues are present.

### Steps to Reproduce

1.  open a project with ``` atom . ```
2.  suspend O.S
3.  come back 

**Expected behavior:**
work's normaly

**Actual behavior:**

* works slowly 
* do not open new panes or switch between open panes.
* can`t save changes on files

**Reproduces how often:**
even when suspend system

### Versions
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 2.7.17
git 2.17.1

elementaryOS Hera(5)

**Comment by Arcanemagus** [comment]
> Atom : 1.38.2

You are running a very old version of Atom, please update to the current version and see if this still reproduces. You'll also need to explain what "SO" means.

**Comment by wjuniorw** [comment]
> > Atom : 1.38.2
> 
> You are running a very old version of Atom, please update to the current version and see if this still reproduces. You'll also need to explain what "SO" means.

I updated and the same happens.
But, i inspec the console and i have the folowing error message when try to save an arquive:
```
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at dbPromise.then.s (/usr/share/atom/resources/app/static/<embedded>:11:287785)

```
atom version now is 1.44.0

**Comment by wjuniorw** [comment]
i "solved" this issue for not ignoring the request keyring password on ubuntu or ubuntu based system.
