### ISSUE TITLE
W10 - issue when hiding .atom folder

### ISSUE THREAD

**Issue by scollovati** [atom/atom#20433]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom loads in Chrome inspection mode after hiding folder `.atom` folder inside `C:\Users\USERNAME`.

### Steps to Reproduce

1. clean install of Atom on Windows 10
2. hide folder `.atom` folder inside `C:\Users\USERNAME`
3. launch Atom

**Expected behavior:**

Atom opens normally.

**Actual behavior:**

Atom opens in Chrome inspection mode.

**Comment by lee-dohm** [comment]
Thanks for reaching out.

Hidden files and folders on Windows don't work like they do on Unix derivatives. We would have to make special system calls to find hidden files or folders and every package author that stores special configuration in the, now hidden, configuration folder would need to do so as well. This isn't something that we'll be able to plan for, communicate to package authors, and handle easily. For these reasons, we're not going to fix this.

Thanks for the well-written bug report 🙇
