### ISSUE TITLE
Atom is not saving sign-in info when "Remeber" is checked. Github tab is forgetting login after reloading atom.

### ISSUE THREAD

**Issue by AlastairWoodbury** [atom/atom#20445]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    *Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Login for "Control Button" (![image](https://user-images.githubusercontent.com/29340449/75194486-23edab00-5750-11ea-879d-abb6811d89fb.png)) not saving after ticking `Remember`, instead just requests username and password when attempting to preform another action, like pulling.

The GitHub panel is also not saving login across restart

#### Bottom bar git controls

1. Open a git repository that is synced to a remote repository. (Private)
2. Click `Fetch` to get the latest
3. Enter username and password, then check `Remember`
4. _(Issue)_ Attempt to pull, and authentication is required.

#### Github Tab

1. Open github tab and click login
2. Get sent to [here](https://github.atom.io/auth/github_package/token), and paste token into atom.
3. Close atom, and reopen.
4. _(Issue)_ Github login is not saved, and i would have to login again.

#### Git controls

* Credentials are saved when `remember` is checked

#### Github tab

* Login is saved across sessions/restarts

#### Git controls

* Credentials are never saved, even with `Remember` checked

#### Github tab

* Login is not saved across sessions/restarts

**Reproduces how often:**

This is reproduced 100% of the time (_On Arch Linux_). I have tested:
* Switching User (Locally)
* Switching Machine (To another archlinux machine)

##### `cat /etc/os-release`
    NAME="Arch Linux"
    PRETTY_NAME="Arch Linux"
    ID=arch
    BUILD_ID=rolling
    ANSI_COLOR="0;36"
    HOME_URL="https://www.archlinux.org/"
    DOCUMENTATION_URL="https://wiki.archlinux.org/"
    SUPPORT_URL="https://bbs.archlinux.org/"
    BUG_REPORT_URL="https://bugs.archlinux.org/"
    LOGO=archlinux
##### `hostnamectl`
    Static hostname: DanLaptop
    Icon name: computer-laptop
    Chassis: laptop
    Machine ID: e8c9fcba050a4b1790cd5fa19489c2c5
    Boot ID: a816897508ae46618382a298a0ca09f1
    Operating System: Arch Linux
    Kernel: Linux 5.5.5-arch1-1
    Architecture: x86-64
##### `uname -r`
    5.5.5-arch1-1
#### Atom
    Atom    : 1.44.0
    Electron: 4.2.12
    Chrome  : 69.0.3497.128
    Node    : 10.11.0
#### Apm
    apm  2.4.5
    npm  6.13.7
    node 13.9.0 x64
    atom 1.44.0
    python 3.8.1
    git 2.25.1
### Additional Information
* This does not occur when I use windows.
* Still occurs after moving .atom
* When checking the owner of .atom, it is me
 * When logging in with the GitHub tab, a `.atom-socket-secret-alastair-1.44.0` file is created which contains what appears to be a token.
* There is a warning in the console (`ctr + shift + i`) that says:
        `Using an InMemoryStrategy strategy for storing tokens. 
        The tokens will only be stored for the current window.`

**Comment by l4tte** [comment]
Same problem here

**Comment by ThatXliner** [comment]
For me, the Git tab says "Git identify". This glitch happens 70% (or less) of the time. It's annoying to press "continue" all the time. A simple reload could fix but this ought to be a glitch
<img width="402" alt="Screen Shot 2020-11-15 at 3 35 25 PM" src="https://user-images.githubusercontent.com/66848002/99200095-2ff32000-2758-11eb-9c98-c56f0ba379a4.png">

**Comment by KSpakes87** [comment]
I have been having this same issue for a couple of weeks now. Extremely annoying!

Windows 10 1909
Build - 18363.1198
Atom Version - 1.53.0

**Comment by OliverBalfour** [comment]
Same problem here, also on Arch Linux. Every time I switch between a file in my git repository and a file elsewhere on my computer, it asks me to reset my Git identity in the Git tab. Every time I open the GitHub tab it asks me to re-enter my access token, rendering it completely useless. My Git identity is cached using `git config --global ...` as well.

**Comment by ceverettkoop** [comment]
Same issue here also on Arch linux. Is there any documentation on where atom stores saved credentials? I assume it is separate from git?

**Comment by giacomo-c** [comment]
I have this problem on my desktop running manjaro.

Oddly, my laptop running manjaro saves the login information, but gives me a dialogue box when I start atom stating "Authentication required:  The login keyring did not get unlocked when you logged into your computer."

**Comment by sixtusg** [comment]
I am having the exact same issue running Arch. Why was the issue closed? Is there a solution?

**Comment by sixtusg** [comment]
So for anyone who has yet to receive this thread in their query or for others who haven't been able to properly use Atom Editor because of this issue, I have discovered why it happens:

This issue disproportionately affecting Arch Linux users, and that is because if you do not have GNOME or GNOME packages installed, you do not have packages "gnome-keyring" and "libsecret" installed. They are needed in order to access certain applications such as Atom. If you install these packages, it will save your GitHub and Git credentials. :smile:

**Comment by izzortsi** [comment]
@sixtusg Your solution actually worked here (I'm on Manjaro KDE). I just had to install "gnome-keyring". Thanks :))
