### ISSUE TITLE
Atom is not opening an empty editor on start

### ISSUE THREAD

**Issue by lohoris-crane** [atom/atom#20449]
Atom is not opening an empty editor on start.

It's basically issue #10623, except it apparently hasn't been solved for some reason.

- "Open Empty Editor At Start" is checked
- "Restore Previous Windows On Start" is "no"
- `welcome: showOnStartup: false`
- Tried in safe mode, problem was still there
- the `process.nextTick ->` trick for `init.coffee` had no effect
- closing manually every single tab, still opened the same "project" at startup

I have an open folder and open files, some of the files modified, and I'm closing it with the top-right X.

Atom:
```
$ atom --version

Atom    : 1.44.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

Windows:
```
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.18362 Build 18362
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/atom/pull/20547. The fix is currently available in the latest version of atom `v1.51.0`.
