### ISSUE TITLE
Desktop file produced by script/grunt mkdev isn't working

### ISSUE THREAD

**Issue by htor** [atom/atom#2046]
Following the installation guide for Linux in the README I ran into some problems using the `.desktop` file produced (See #1969 ). The atom icon shows up, but nothing happens when I hit it.

Running Debian Sid 3.14 with GNOME Shell 3.8.4.

A little summary:

    htor@ultra:~/.local/src/atom$ script/grunt mkdeb
    Running "mkdeb" task
    Done, without errors.
    htor@ultra:~/.local/src/atom$ cd /tmp/
    htor@ultra:/tmp$ file atom-build
    atom-build: Debian binary package (format 2.0)
    htor@ultra:/tmp$ sudo dpkg -i atom-build
    (Reading database ... 194042 files and directories currently installed.)
    Preparing to unpack atom-build ...
    Unpacking atom (0.95.0) over (0.95.0) ...
    Setting up atom (0.95.0) ...
    Processing triggers for desktop-file-utils (0.22-1) ...
    Processing triggers for gnome-menus (3.8.0-2) ...
    Processing triggers for mime-support (3.54) ...
    htor@ultra:/tmp$ sudo dpkg -L atom 
    /.
    /usr
    /usr/share
    /usr/share/applications
    /usr/share/applications/Atom.desktop
    /usr/share/pixmaps
    /usr/share/pixmaps/atom.png
    /usr/bin
    /usr/bin/atom
    htor@ultra:/usr/share/applications$ cat Atom.desktop
    [Desktop Entry]
    Name=Atom
    Comment=A hackable text editor for the 21st Century.
    Exec=/usr/share/atom/atom %U
    Icon=atom
    Type=Application
    StartupNotify=true
    Categories=GNOME;GTK;Utility;TextEditor;
    htor@ultra:/usr/share/applications$

Hmm, I wonder what the `/usr/share/atom/atom` is..

    htor@ultra:/usr/share/applications$ file /usr/share/atom/atom
    /usr/share/atom/atom: cannot open `/usr/share/atom/atom' (No such file or directory)

Apparently nothing. Let's change that to where `atom` was actually installed:

    Exec=/usr/local/bin/atom

Now it works and I can launch atom normally.

**Comment by 50Wliu** [comment]
Assuming fixed.  If this is still reproducible on the latest Atom version please comment here!
