### ISSUE TITLE
Status-bar slow loadtime in atom 1.47.0-nightly3

### ISSUE THREAD

**Issue by aminya** [atom/atom#20531]
### Description

In the latest nightly (1.47.0-nightly3), when I open Atom, the status-bar has a very high activation time.

<img src="https://user-images.githubusercontent.com/16418197/77041183-6db06680-6987-11ea-9b11-eb259b889369.png" width="500"/>

This doesn't happen in atom 1.47.0-nightly2:

<img src="https://user-images.githubusercontent.com/16418197/77041919-c16f7f80-6988-11ea-9294-1d60bc4744c9.png" width="500"/>

It is related to one of these commits:
https://github.com/atom/atom/compare/97565c62...0b34be79. 

Maybe this one: https://github.com/atom/atom/commit/3bf17ac0045ce0bd462b63816cebab4a229e6623

### Steps to Reproduce

1. Open atom-nightly.exe from C:\Users\~\AppData\Local\atom-nightly\app-1.47.0-nightly3
(or use `atom-nightly` from CLI)
2. Check Timecop

**Expected behavior:**
Shouldn't have this much of loading time
**Actual behavior:**
Long activation time

**Reproduces how often:**
Always

Doesn't happen in `atom-nightly --safe` (no one is using the status-bar, so isn't related).

### Versions
Atom    : 1.47.0-nightly3
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

The previous version that doesn't have any issues:

 Atom    : 1.47.0-nightly2
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

**Comment by aminya** [comment]
Here is the result with many packages disabled:

Nightly 3:
<img src="https://user-images.githubusercontent.com/16418197/77293699-d9a90c80-6cb0-11ea-8494-b0146cda004a.jpg" width="500"/>

Nightly 2:
<img src="https://user-images.githubusercontent.com/16418197/77293722-e2014780-6cb0-11ea-813c-a6a86bf96695.jpg" width="500"/>

Same problem happens

**Comment by lee-dohm** [comment]
If it doesn't reproduce when running in Safe Mode, then this almost certainly isn't a bug in Atom. Additionally, I can't reproduce this even when _not_ running in Safe Mode:

<img width="714" alt="Screen Shot 2020-03-26 at 9 38 33 AM" src="https://user-images.githubusercontent.com/1038121/77671991-94e9d380-6f45-11ea-8696-530daf63b56a.png">

So it would appear to be something to do with your configuration. You may want to follow the debugging steps in the Flight Manual on [profiling startup performance](https://flight-manual.atom.io/hacking-atom/sections/debugging/#profiling-startup-performance) to track down where the problem might be.

**Comment by aminya** [comment]
But this all happens when I use nightly3. I didn't change anything for my configuration.

**Comment by lee-dohm** [comment]
> But this all happens when I use nightly3. I didn't change anything for my configuration.

Notice that between `nightly2` and `nightly3` the Electron version changed. This can cause a number of effects:

1. Some binaries may need to be rebuilt for the new Node and Electron versions on first startup
1. Some packages may not work the same or as efficiently under the new Node and Electron versions
1. There might be an incompatibility between some package or configuration you have with the new Node and Electron versions

All of these (and I'm certain others) could be causes of what you're seeing without you needing to change your configuration.

So, if you can't reproduce this in Safe Mode, it is almost certain there is some package you have installed that is causing this problem. Unfortunately, we'll need you to track down which one that might be and follow up with the package author.

**Comment by aminya** [comment]
Here is the result for all community packages disbaled:
![image](https://user-images.githubusercontent.com/16418197/77710278-9cd46280-6f9b-11ea-8906-c745f6b18236.png)

**Comment by lee-dohm** [comment]
The value you're showing there isn't problematic in and of itself. If you have some profiling data (using the techniques I linked to above) that identifies a problem, we'll take a deeper look at things.

**Comment by aminya** [comment]
> 
> 
> The value you're showing there isn't problematic in and of itself. If you have some profiling data (using the techniques I linked to above) that identifies a problem, we'll take a deeper look at things.

For reference untill I do profiling, this is on Atom 1.47 nightly 2 with the same packages:
![image](https://user-images.githubusercontent.com/16418197/77711642-8cbe8200-6f9f-11ea-8eef-139225132fe0.png)

100 vs 10 is something.

**Comment by aminya** [comment]
Here are reload profiling data
[nightly3.zip](https://github.com/atom/atom/files/4391140/nightly3.zip)
[nightly2.zip](https://github.com/atom/atom/files/4391142/nightly2.zip)

**Comment by aminya** [comment]
I don't understand why this issue is closed. It isn't fixed yet.

**Comment by aminya** [comment]
First thing I notice is this part at the end which isn't in nightly 2 data:
![image](https://user-images.githubusercontent.com/16418197/77715758-6ce08b80-6faa-11ea-88a7-dadee4630179.png)

**Comment by aminya** [comment]
@darangi Could you take a look at this? I don't understand why this issue is closed. It isn't fixed yet.

**Comment by lee-dohm** [comment]
@aminya We close issues that we aren't going to work on. When you refused to cooperate with me and address my questions yesterday after repeated requests, I closed this issue. When I get a chance, I'll take a look at your profiling information and then make a determination if this should be reopened.

**Comment by aminya** [comment]
> 
> 
> @aminya We close issues that we aren't going to work on. When you refused to cooperate with me and address my questions yesterday after repeated requests, I closed this issue. When I get a chance, I'll take a look at your profiling information and then make a determination if this should be reopened.

I didn't refuse to address your question. It took only 1 hour to upload the profiling data. This issue has been open for 9 days without any response. If you don't want to fix the issues of nightly releases, then don't bother making them. This behavior is disrespectful.
