### ISSUE TITLE
Theme inconsistencies in Incompatible Packages dialog

### ISSUE THREAD

**Issue by idleberg** [atom/atom#20545]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

On dark themes, the container boxes in the `incompatible-packages` view look very different from the rest of the Atom UI. This is due to hard-coded colors being used, rather that UI variables.

### Steps to Reproduce

I don't know how to artificially produce packages that need to be rebuild, but they are prerequisite to the following steps

1. Switch to a dark theme
2. Open the incompatible packages dialog

**Expected behavior:**

The look should be consistent with the rest of Atom's UI, more specifically the background- and border-colors.

**Actual behavior:**

The colors for background and borders are clearly addressing light themes only.

**Reproduces how often:**

100%

### Additional Information

**atom-one-light**

![Screenshot 2020-03-22 at 12 45 48](https://user-images.githubusercontent.com/1504938/77248859-11766c80-6c3d-11ea-9a7b-7e16f2b2ba18.png)

**atom-one-dark**

Without PR

![Screenshot 2020-03-22 at 12 45 36](https://user-images.githubusercontent.com/1504938/77248858-10453f80-6c3d-11ea-8388-72c001c432d7.png)

With PR

![Screenshot 2020-03-22 at 13 13 54](https://user-images.githubusercontent.com/1504938/77249087-0c1a2180-6c3f-11ea-842d-83ae1b143a79.png)

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/atom/pull/20546. It is currently scheduled for release when `v1.52.0` reaches Stable.
