### ISSUE TITLE
Atom Is not saving files

### ISSUE THREAD

**Issue by Marcellofabrizio** [atom/atom#20551]
**The previous reports on this got close and had no solutions that worked for my case, so I'm opening a new one.**

I can’t save some files in Atom. I have the autosave-onchange package and sometimes it seems to work just fine. But, in others, even CTRL + S won’t work, and if I try to “save as” or close the file while the blue dot is still there, I receive the following message: " could not be saved. Error: undefined". Have no clues on what to do. Tried opening Atom with atom --safe, but still no result.

I use:
Ubuntu 18.04.4 LTS
Atom 1.45.0

Packages:
atom-beautify
atom-clock
autocomplete
autocomplete-java
autocomplete-modules
autosave-onchange
file-icons
ide-java
language-vue
linter
linter-eslint
minimap
python-ident

**Comment by blackswanburst** [comment]
Ubuntu 18.04.4 LTS \n \l
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

apm ls
Built-in Atom Packages (93)
├── atom-dark-syntax@0.29.1
├── atom-dark-ui@0.53.3
├── atom-light-syntax@0.29.1
├── atom-light-ui@0.46.3
├── base16-tomorrow-dark-theme@1.6.0
├── base16-tomorrow-light-theme@1.6.0
├── one-dark-ui@1.12.5
├── one-light-ui@1.12.5
├── one-dark-syntax@1.8.4
├── one-light-syntax@1.8.4
├── solarized-dark-syntax@1.3.0
├── solarized-light-syntax@1.3.0
├── about@1.9.1
├── archive-view@0.65.1
├── autocomplete-atom-api@0.10.7
├── autocomplete-css@0.17.5
├── autocomplete-html@0.8.8
├── autocomplete-plus@2.42.3
├── autocomplete-snippets@1.12.1
├── autoflow@0.29.4
├── autosave@0.24.6
├── background-tips@0.28.0
├── bookmarks@0.46.0
├── bracket-matcher@0.91.2
├── command-palette@0.43.5
├── dalek@0.2.2
├── deprecation-cop@0.56.9
├── dev-live-reload@0.48.1
├── encoding-selector@0.23.9
├── exception-reporting@0.43.1
├── find-and-replace@0.219.1
├── fuzzy-finder@1.14.1
├── github@0.34.0 (disabled)
├── git-diff@1.3.9 (disabled)
├── go-to-line@0.33.0
├── grammar-selector@0.50.1
├── image-view@0.64.0
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.39.0
├── line-ending-selector@0.7.7
├── link@0.31.6
├── markdown-preview@0.160.2
├── metrics@1.8.1
├── notifications@0.71.0
├── open-on-github@1.3.2
├── package-generator@1.3.0
├── settings-view@0.261.3
├── snippets@1.5.0
├── spell-check@0.75.0 (disabled)
├── status-bar@1.8.17
├── styleguide@0.49.12
├── symbols-view@0.118.2
├── tabs@0.110.0
├── timecop@0.36.2
├── tree-view@0.228.0
├── update-package-dependencies@0.13.1
├── welcome@0.36.9
├── whitespace@0.37.7
├── wrap-guide@0.41.0
├── language-c@0.60.18
├── language-clojure@0.22.8
├── language-coffee-script@0.50.0
├── language-csharp@1.1.0
├── language-css@0.44.2
├── language-gfm@0.90.7
├── language-git@0.19.1
├── language-go@0.47.1
├── language-html@0.53.0
├── language-hyperlink@0.17.1
├── language-java@0.31.4
├── language-javascript@0.134.0
├── language-json@1.0.4
├── language-less@0.34.3
├── language-make@0.23.0
├── language-mustache@0.14.5
├── language-objective-c@0.16.0
├── language-perl@0.38.1
├── language-php@0.44.4
├── language-property-list@0.9.1
├── language-python@0.53.3
├── language-ruby@0.72.22
├── language-ruby-on-rails@0.25.3
├── language-rust-bundled@0.1.0
├── language-sass@0.62.1
├── language-shellscript@0.28.0
├── language-source@0.9.0
├── language-sql@0.25.10
├── language-text@0.7.4
├── language-todo@0.29.4
├── language-toml@0.20.0
├── language-typescript@0.6.0
├── language-xml@0.35.3
└── language-yaml@0.32.0

Community Packages (5) /home/praxis/.atom/packages
├── language-latex@1.2.0
├── language-ocaml@1.9.5
├── latex@0.50.2
├── ocaml-indent@0.7.1
└── ocaml-merlin@0.14.7
+1 
I used the workaround of disabling git, gitdiff, and github. It allows me to keep working but is super annoying. Can we get some traction and answers on this? Why do the git packages break the saving functionality?

**Comment by Marcellofabrizio** [comment]
That worked for me, but as you said, super annoying. Still, I don't know why this is happening.

**Comment by aminya** [comment]
Does disabling that auto-save package solve the issue?

**Comment by Marcellofabrizio** [comment]
No. Neither trying opening it in safe mode.

**Comment by chrisbarnettster** [comment]
Hi everyone :wave: 

# Overview
Same issue. I found that the problem occurs for any file that is in one of my coding directories. So any file whether it is git tracked or not as long as it is in a git managed directory.

The GitHub pane shows an OctoCat spinner but never seems to figure out that the remote public repo is available. 
![image](https://user-images.githubusercontent.com/4262750/79872153-b07db800-83e5-11ea-8afb-6cf032b5e207.png)

# Versions 
Running Ubuntu 18.04.4 LTS
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

# What doesn't solve the problem
Running `atom --safe` doesn't solve the problem. 

# Solving the problem
Solved already by @blackswanburst, thanks for that! In my case, only needed to disable one package, the GitHub package, but agreed this is not ideal. GitHub is a core package so this is definitely unexpected behaviour.

Go to the Edit menu, choose Preferences. Click on Packages, then find the github package. Disable it.
![image](https://user-images.githubusercontent.com/4262750/79870323-174da200-83e3-11ea-861f-75bc7e6d6bb7.png)
If Preferences will not open then make sure to open Atom without opening any files, when I had any git managed files open the Preferences menu would not open.
