### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.45.0\1.5).txt'

### ISSUE THREAD

**Issue by LokiFlux** [atom/atom#20567]
[Enter steps to reproduce:]

1. Open a project folder, and create a subfolder inside of it.
2. Create a text file called "geneticOutput(500,10000000,100,1.5).txt" inside of the project folder.
3. Attempt to move the text file into the subfolder.

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\admin\AppData\Local\atom\app-1.45.0\1.5).txt'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\admin\AppData\Local\atom\app-1.45.0\1.5).txt'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1005297)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:1012226)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:14:985857)
```

### Commands

```
     -1:47.2.0 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
 13x -1:37.5.0 core:backspace (input.hidden-input)
     -1:29.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/tree-view/pull/1358. It is currently scheduled for release when `v1.53.0` reaches Stable.
