### ISSUE TITLE
The location of the "Preferences, Config etc." buttons is highly unintuitive

### ISSUE THREAD

**Issue by void4** [atom/atom#20577]
### Description

Whenever I want to install a new package, or want to view the installed ones, or change the editor configuration, I find myself completely lost.

### Steps to Reproduce

1. Try to find 'Preferences' button
2. Don't find it in the 'Packages' nav
3. Go through all navs: File, Edit, View, Find, Packages, Help
4. Despair
5. Give up or finally find it in the long 'Edit' list

![image](https://user-images.githubusercontent.com/11392207/77926099-ff807380-72a5-11ea-9e7f-df5669f9501b.png)

**Expected behavior:**

'Edit' should be reserved for options pertaining to text editing, the IDE options should be put elsewhere.

I propose to either add them to 'File' or add a new nav element (second to last to help probably) called 'IDE Options' where all these can be put.

**Comment by calebmeyer** [comment]
For what it's worth, these are under Atom on macOS:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/3342777/77936798-0644c180-7279-11ea-819f-7e1cf99f5363.png">
and under File on Windows:
![image](https://user-images.githubusercontent.com/3342777/77936855-19f02800-7279-11ea-91c3-f6d3f300fefc.png)

However, I'd say more than half of the applications I've used have put preferences or settings or options (it's different in every app, I swear!) under Edit. Fortunately, Atom also assigns a reasonable keyboard shortcut (control-comma, or command-comma on macOS), which is the way I usually access settings.

I agree it would be nice to have a shortcut to the packages view in settings (for installing/managing packages) from the packages menu, though.

**Comment by lee-dohm** [comment]
The Preferences/Settings menu items are in the menu that is the platform standard per-platform: the application menu on macOS, the File menu on Windows, and the Edit menu on Linux. See https://github.com/atom/atom/issues/2467 for when this was changed for Linux.
