### ISSUE TITLE
Usage Rights

### ISSUE THREAD

**Issue by Moonie68** [atom/atom#20588]
Hello! I just made an electron app and now I have to make installers... ugh... But I am almost complete! I have no idea on how to make a installer gif, so may I modify your original loading gif for my app, Cook.ie? I have attached a .gif file 
![background](https://user-images.githubusercontent.com/58180094/78309669-dd3a6000-7508-11ea-8cb8-a8c118a8bd8a.gif)
so you can look at it. Thanks!

**Comment by lee-dohm** [comment]
Thanks for reaching out.

We're glad you like the animation. Unfortunately, all of our logos, animation, and imagery is covered by the same [Logo Guidelines](https://github.com/logos) as the other GitHub logos. 

I hope that helps!
