### ISSUE TITLE
GitHub Desktop does not detect GitHub Atom on Windows x64.

### ISSUE THREAD

**Issue by Neustradamus** [atom/atom#20601]
GitHub Desktop does not detect GitHub Atom on Windows x64, please solve it.

Linked to:
- https://github.com/desktop/desktop/issues/9475

**Comment by constantinexisc** [comment]
So you just created the same issue twice for no reason, and also provided zero information about it.

**Comment by Neustradamus** [comment]
When we install Desktop and Desktop says to install Atom (because some editors are not detected), so we install Atom and no detection in Desktop: Problem.

**Comment by Neustradamus** [comment]
@steveward: It is possible to solve the installer?
The problem is in Desktop and Atom?

**Comment by steveward** [comment]
@Neustradamus is it possible you didn't restart GitHub Desktop after installing Atom? That's a necessary step in order for GitHub Desktop to detect the editor. I'm going to close this out as we're already discussing this over in the GitHub Desktop issue tracker.

**Comment by Neustradamus** [comment]
@steveward: There is a bug here, it must be solved...
I have of course.

**Comment by Neustradamus** [comment]
@steveward: GitHub teams can be sync for this problem?
We need a real solution in the Atom Installer!
