### ISSUE TITLE
Atom nightly breaks webviews (Electron 5.x API changes)

### ISSUE THREAD

**Issue by ashthespy** [atom/atom#20604]
### Description
Atom nightly now uses electron 5.x, which [disables `webview` and `nodeintegration`](https://github.com/electron/electron/releases/tag/v5.0.0) by default. 

1bc06505d5cccb452724c5628f6288787f16aa44 enables the `nodeIntegration` but `webview` is still disabled by default. 
Could we have it enabled? 

cc: https://github.com/ashthespy/Atom-LaTeX/issues/244

**Comment by lkashef** [comment]
Hey @ashthespy, thanks for the report!

I will bring this up in our next meeting to discuss with the team, any extra information would be helpful:

- any known drawbacks?
- what's the motive? (whether this is a use case you are implementing or a known reported issue)

**Comment by ashthespy** [comment]
@lkashef Well, it was enabled by default in previous Electron versions. The use case (for me) is a tabbed viewer that renders a locally hosted pdf.js based pdf viewer. (Linked issue in the first post and workaround using an `iframe` for now)

**Comment by lkashef** [comment]
Thanks @ashthespy that's pretty helpful, we will update the issue with any progress.

**Comment by ashthespy** [comment]
@lkashef Looks like this didn't make it to Atom 1.47.0? 
Do you know when the next release with the fix is going to land? I don't feel particularly inclined patching stuff..

**Comment by lkashef** [comment]
@ashthespy You are right, unfortunately it didn't, also wee don't have a published release schedule, but you can definitely check things out on Nightly and share with us any feedback.

--- 

On the other hand, have you considered using `BrowserView` since this seems to be the Electron way starting v5 (available in stable)

**Comment by ashthespy** [comment]
@lkashef Thanks for the heads up on the `BrowserView` - do you have an example of what's the best way to use this to [create a view](https://github.com/atom/atom/blob/1d9a4cafcf6cc288d675512db8fd984e13aab869/src/view-registry.js#L139) to use in a panel?

**Comment by lkashef** [comment]
Hey @ashthespy, you are most welcome.

I think collaborating on the Atom's Slack or discuss would be more helpful, although here are a couple of thoughts that might help put you in the right direction.

1. BrowserView docs for the current supported electron version https://github.com/electron/electron/blob/v5.0.13/docs/api/browser-view.md
2. Check [Atom's Markdown-Preview](https://github.com/atom/markdown-preview), it doesn't use BrowserView per-say, but it could be an alternative design, you might consider.

--- 

#### Communication Channels and Documentation Links

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

**Comment by lierdakil** [comment]
Hey, just wanted to say, this is extremely painful for a few reasonably popular packages. Maybe we can, like, fix this, backport it to 1.47 branch and release as 1.47.1? Because it's been 2 weeks since 1.47 released already, and it's getting pretty annoying to deal with it both for users and maintainers.

**Comment by lierdakil** [comment]
FWIW, BrowserView doesn't quite fill the same niche in Atom as webview tag does -- BrowserView is literally drawn over any element in Atom, so it's quite literally impossible to make it a part of Atom UI.

**Comment by aubreyz** [comment]
+1 to the above. Raises some pretty serious questions about beta testing if it breaks at least three packages with mass 100K+installation and is now still unfixed and un-reverted after several weeks. I fear this sort of thing will lead users to try other editors.

**Comment by sean-codes** [comment]
@lkashef What do we need to do to release this? Can we help in any way?

**Comment by lkashef** [comment]
Hey @sean-codes, thanks for reaching out.

This fix is already available in Atom Nightly, we are also working on a release to patch this issue in stable and beta.
