### ISSUE TITLE
createRequire is not a function

### ISSUE THREAD

**Issue by sayem314** [atom/atom#20610]
Without any Atom update, suddenly every time I try to save a file, Atom error panes occur. With safe mode everything is fine.

### Prerequisites

    [] Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    [x] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    [*] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    [*] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    [*] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Versions

```
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
```

```
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 2.7.17
git 2.17.1
```

```
Community Packages (5) /home/sayem/.atom/packages
├── busy-signal@2.0.1
├── intentions@1.1.5
├── linter@2.3.1
├── linter-ui-default@1.8.1
└── prettier-atom@0.58.2
```

![image](https://user-images.githubusercontent.com/14138401/79020080-ae238e80-7b99-11ea-8c35-92a840e2c131.png)

**Comment by sayem314** [comment]
Looks like an issue with prettier
https://github.com/prettier/prettier-atom/issues/725

**Comment by liqueurdetoile** [comment]
For those who may land here like me.

The *real* problem is that `createRequire` have only been introduced in Node 12.2.0 and current Electron version in Atom stable version is using Node 10. Prettier fixed it by giving away the API for now but I'm facing same issue with `eslint-plugin-vue` 6.2.2.

Hopefully, Atom Beta 1.47 have switched to Electron 5 wich relies on Node 12. Running my package in Atom beta solves this issue and I look forward 1.47 stable release 😉
