### ISSUE TITLE
Trojan? or false positive?

### ISSUE THREAD

**Issue by P4KM4N** [atom/atom#20618]
I just downloaded Atom 1.45 (for Mac) from official website and after scanning it I found 1 trojan (Trojan.Win32.IRCBot.l3vP) in this file "Atom.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework":
https://www.virustotal.com/gui/file/0c51ead13363760705e6632c65afeedd92bef6ace3ef716b7170cd8f8ab5f4ed/detection

**Comment by kiityman1** [comment]
A single random antivirus detected it? It is obviously a false positive.

**Comment by P4KM4N** [comment]
Yes, probably, I'm closing it.
