### ISSUE TITLE
Find/Replace while preserving case

### ISSUE THREAD

**Issue by darkdragon-001** [atom/atom#20625]
## Summary

When using case-insensitive search, it would be nice to allow a replace operation which preserves case (add an option for that).

## Motivation

Your project name is often spelled in `CamelCase` while the package name etc. should be in small letters (e.g. `camelcase`).

## Describe alternatives you've considered

Do consecutive operations with all different possible spellings. When using _Find in files_ will be a lot of work...

**Comment by UziTech** [comment]
this issue should probably be on the [`find-and-replace`](https://github.com/atom/find-and-replace) repo.

**Comment by darkdragon-001** [comment]
@UziTech Can you [transfer](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository) it or should I close this and create a new one there?

**Comment by UziTech** [comment]
You should create a new one
