### ISSUE TITLE
Atom won't launch from the terminal in OSX 10.9.3. 

### ISSUE THREAD

**Issue by hminaya** [atom/atom#2066]
Atom won't launch from the terminal in OSX 10.9.3. Here is the output:

![image](https://cloud.githubusercontent.com/assets/586656/2911417/597a5b00-d65b-11e3-84c7-16cd11aea96d.png)

**Comment by as-cii** [comment]
@hminaya Thanks for reporting this issue: unfortunately it hasn't received attention for a while; have you experienced this issue again or it works for you now?

Thank you :smile_cat:

**Comment by mnquintana** [comment]
Gonna close this out now - please feel free to reopen / comment if you can reproduce this with the latest version of Atom (0.210.0)
