### ISSUE TITLE
Atom crash when symbol #{ is in config.cson - v1.46.0

### ISSUE THREAD

**Issue by deleage-tanguy** [atom/atom#20708]
**### Solution in the next comment.**

Reproduce a bug :
1. Open config.cson
2. Add this configuration at the end :
`  example:
    dataexemple: "One symbol : #{"`
3. Atom crash at startup.

Hi,

Since I have updated my atom (v1.46.0), I have bug (not always) when I create a new file.
Atom has crashed and now, it's impossible to restart it.

When I start Atom, in tools menu of macOS I see "Atom" -> Quit only. 
No windows appear. 

**Version :** 
> Atom    : 1.46.0
> Electron: 4.2.7
> Chrome  : 69.0.3497.128
> Node    : 10.11.0

When I run `atom --foreground` : 
`2020-05-07 17:23:04.145 Atom[3607:20657] Syntax error on line 61, column 14: Unexpected StringWithInterpolations
2020-05-07 17:23:04.146 Atom[3607:20657] SyntaxError: Syntax error on line 61, column 14: Unexpected StringWithInterpolations
    at transformNode (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:214:13)
    at Value (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/cson-parser/lib/parse.js:97:12) 
[........]`

List of my packages : 

> ├── atom-clock-alarm@3.5.0
> ├── atom-ide-ui@0.13.0
> ├── atom-menu-patch-for-catalina@0.3.3
> ├── atom-react-mf-snippets@0.11.1
> ├── autoclose-html-plus@0.27.2
> ├── autocomplete-elixir@1.5.16
> ├── autocomplete-html-entities@0.2.0
> ├── better-git-blame@0.5.0
> ├── duplicate-line-or-selection@0.9.0
> ├── file-icons@2.1.40
> ├── git-control@0.9.0
> ├── git-log@0.4.1
> ├── git-time-machine@2.1.0
> ├── highlight-line@0.12.0
> ├── highlight-selected@0.17.0
> ├── hyperclick@0.1.5
> ├── ide-elixir@0.2.25
> ├── ide-html@0.6.0
> ├── ide-typescript@0.9.1
> ├── js-hyperclick@1.19.0
> ├── language-elixir@0.24.0
> ├── markdown-preview-plus@3.11.5
> ├── packages
> ├── script@3.26.0
> ├── split-diff@1.6.1
> ├── terminal-tab@0.6.0
> ├── touchbar@0.15.0
> └── zentabs@0.8.9

If I run atom in sudo mode, all it's OK...
Regards

**Comment by deleage-tanguy** [comment]
**I found the source of the problem**
In my config.cson I have plugin for customize my touche bar in MacOS.
In this plugin I have create bouton with label "#{x}". Symbol # in config.cson makes Atom crash at startup.

**Comment by lkashef** [comment]
Hey @deleage-tanguy, thanks for reaching out.

I am glad you were able to resolve the issue :)
