### ISSUE TITLE
Cant add a projekt folder from Windows FTP connection

### ISSUE THREAD

**Issue by tawissus** [atom/atom#20713]
Hello,

I can't add a projekt folder from FTP servers on Windows.
The FTP connection is not visible in the add folder dialouge.

![FTP](https://user-images.githubusercontent.com/1453423/81401858-7e33c080-9130-11ea-8320-b9bea9e92204.JPG)

V 1.45.0

Best
Guido

**Comment by lkashef** [comment]
Hey @tawissus, thanks for reaching out!

I will go ahead and close this issue, as the problem doesn't seem to be related to Atom.
