### ISSUE TITLE
Issue folding python code

### ISSUE THREAD

**Issue by avikarto** [atom/atom#20710]
There is some strange behavior with the code folding in python when folding a function with a multi-line declaration.   Declaring a function across multiple lines is recommended by pep8 for long declarations, but in such cases only the declaration folds - not the entire function block.

![multiline](https://user-images.githubusercontent.com/4030963/81335802-30f31880-9076-11ea-84b8-5d7023efafe6.gif)

**Comment by Crypronic-yash** [comment]
I wanna work on this issue. Please allow me to work on this issue.

**Comment by avikarto** [comment]
It turns out that this can be resolved through the core atom settings by disabling "Tree Sitter".  If anyone still wants to resolve this behavior with Tree Sitter enabled go nuts, but I am closing the issue.
