### ISSUE TITLE
Atom makes unhidden files hidden in Nautilus File Manager

### ISSUE THREAD

**Issue by kuntur-studio** [atom/atom#20712]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When opening a file on Atom, the "Show hidden files" setting in the Nautilus file manager gets unchecked.
### Steps to Reproduce

1. Go to Nautilus and set "Show hidden files" setting ON
2.  Go to Atom, click on the menu File -> Open File
3.  Cancel the open file operation
4. Go to Nautilus and check if "Show hidden files" is still ON

**Expected behavior:**

Let Nautilus settings untouched

**Actual behavior:**

https://youtu.be/ofeajYiAhDM

**Reproduces how often:**

It occurs 100% of the time

### Versions

Atom 1.46.0
Nautilus 3.26.4
Ubuntu 18.04

**Comment by Arcanemagus** [comment]
Atom has absolutely zero control over your OS's file dialog, it simply calls the Electron method to open the dialog and waits for the result.

Do you see the same behavior on the current beta branch? Recent Chrome versions? Other Electron based applications?

**Comment by rubensa** [comment]
Please see: https://github.com/microsoft/vscode/issues/107246

**Comment by rubensa** [comment]
@Arcanemagus Could you reopen this issues so anyone can investigate?

Just downloaded the latest Atom version (1.58.0) and the behavior is exactly the same. When I open a folder (project) in Atom, the Nautilus window is refreshed and the "Show hidden files" check is automatically disabled.
