### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.46.0\ Inc'

### ISSUE THREAD

**Issue by mayafox** [atom/atom#20734]
[Enter steps to reproduce:]
unknown
1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\jnixon\AppData\Local\atom\app-1.46.0\ Inc'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\jnixon\AppData\Local\atom\app-1.46.0\ Inc'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1002525)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1009454)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:983085)
```

### Commands

```
     -0:49.5.0 intentions:highlight (input.hidden-input)
     -0:49.3.0 core:save (input.hidden-input)
  2x -0:43.9.0 core:select-left (input.hidden-input)
     -0:42.3.0 intentions:highlight (input.hidden-input)
     -0:42.1.0 core:save (input.hidden-input)
  2x -0:34.2.0 core:select-left (input.hidden-input)
     -0:32.4.0 intentions:highlight (input.hidden-input)
     -0:32.2.0 core:save (input.hidden-input)
     -0:31.1.0 intentions:highlight (input.hidden-input)
  3x -0:30.9.0 core:close (input.hidden-input)
     -0:28 intentions:highlight (input.hidden-input)
     -0:27.5.0 core:close (input.hidden-input)
     -0:18.4.0 intentions:highlight (input.hidden-input)
     -0:18.3.0 core:save (input.hidden-input)
     -0:17.3.0 intentions:highlight (input.hidden-input)
     -0:17.2.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
django-templates 0.5.0 
docblock-python 0.18.2 
git-clone 0.2.0 
git-plus 8.7.1 
intentions 1.1.5 
kite 0.184.0 
language-django 0.1.1 
language-tcl 0.1.2 
language-yang 0.2.0 
linter 2.3.1 
linter-js-yaml 1.4.6 
linter-pycodestyle 2.1.3 
linter-ui-default 1.8.1 
multi-cursor 3.0.0 
python-indent 1.2.6 
python-requirements 1.2.0 
script 3.26.0 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by mayafox** [comment]
Darangi, 
If I knew the exact steps I would have put them in. nearest thing I can figure is it's related to a mouse movement and a clicking somewhere in the projects folder bar, as I was heading to open a new folder as that's what I was doing when the message popped up.

**Comment by lkashef** [comment]
Hey @mayafox, this looks like an issue with the new folder you were opening, it looks like it has a single quote in the middle of the name, if you remove the quote in the folder name or rename it to include just letters and underscores I think it should work just fine

**Comment by aliatode2030** [comment]
2030
