### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/AppData\Local\atom\app-1.46.0\CSS - M...

### ISSUE THREAD

**Issue by zaidmohammed2563** [atom/atom#20747]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\User\AppData\Local\atom\app-1.46.0\CSS - My Site Images'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat 'C:\Users\User\AppData\Local\atom\app-1.46.0\CSS - My Site Images'
    at Proxy.realpathSync (fs.js:1435:7)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:306:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1002525)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1009698)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:983085)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
autoclose-html-plus 0.27.2 
autocomplete-google-suggest 1.1.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.2 
```

**Comment by duboloms** [comment]
open the directory where your atom is located
**I have this C:\Users\_Your user name_\AppData\Local\atom**
**After that, go to the bin folder and open the atom.cmd file, just in case, click on apm.cmd.**
Close atom and open it again, it should work.

**Comment by darangi** [comment]
Thanks for reporting this!

This has already been fixed on `master`. It is currently scheduled for release when `v1.53.0` reaches Stable.
