### ISSUE TITLE
Atom v1.47.0 immediately crashes on Linux

### ISSUE THREAD

**Issue by Descear** [atom/atom#20756]
Thanks for reaching out!

### Prerequisites

* [an X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>
    * Thanks for reaching out!

### Description

Thanks for reaching out!

- Debian amd64 GNU/Linux 10 (buster)
- GNOME 3.30.2
- Atom installed from Atom's official package repository using APT

One can use [`debian-live-10.4.0-amd64-gnome.iso`](https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/) to reproduce this bug.

Possibly related: #20289

```
$ strace -f atom --version 2>& 1 | grep +++
[pid  5410] +++ exited with 0 +++
[pid  5412] +++ exited with 0 +++
[pid  5411] +++ exited with 0 +++
[pid  5413] +++ exited with 0 +++
[pid  5414] +++ exited with 0 +++
[pid  5415] +++ exited with 0 +++
[pid  5417] +++ exited with 0 +++
[pid  5416] +++ exited with 0 +++
[pid  5418] +++ exited with 0 +++
[pid  5420] +++ killed by SIGTRAP +++
[pid  5419] +++ killed by SIGTRAP +++
+++ exited with 133 +++
```

```
$ atom
/usr/bin/atom: line 190:  5558 Trace/breakpoint trap   nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[5558:0519/193533.492727:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/share/atom/chrome-sandbox is owned by root and has mode 4755.
```

```
$ stat /usr/share/atom/chrome-sandbox
  File: /usr/share/atom/chrome-sandbox
  Size: 5185424   	Blocks: 10128      IO Block: 4096   regular file
Device: 17h/23d	Inode: 137009      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-05-19 19:03:47.000000000 +0000
Modify: 2020-05-18 19:58:57.000000000 +0000
Change: 2020-05-19 19:03:57.648004641 +0000
 Birth: -
```

```
$ dpkg -c atom_1.47.0_amd64.deb | grep chrome-sandbox
-rwxr-xr-x root/root   5185424 2020-05-18 19:58 ./usr/share/atom/chrome-sandbox
```

Thanks for reaching out!

### Steps to Reproduce

1. Run Atom.

**Expected behavior:**

Atom should run.

**Actual behavior:**

It does not.

**Reproduces how often:**

100%.

### Versions

```
$ apt show atom
Package: atom
Version: 1.47.0
Priority: optional
Section: devel
Maintainer: GitHub <atom@github.com>
Installed-Size: 627 MB
Depends: git, libgconf-2-4 (>= 3.2.5) | libgconf2-4, libgtk-3-0 (>= 3.9.10), libgcrypt11 | libgcrypt20, libnotify4, libxtst6, libnss3 (>= 2:3.22), python | python2, gvfs-bin, xdg-utils, libx11-xcb1, libxss1, libasound2 (>= 1.0.16), libxkbfile1, libcurl3 | libcurl4, policykit-1 Thanks for reaching out!
Recommends: lsb-release
Suggests: libsecret-1-0, gir1.2-gnomekeyring-1.0
Download-Size: 124 MB
APT-Manual-Installed: yes
APT-Sources: https://packagecloud.io/AtomEditor/atom/any any/main amd64 Packages
Description: A hackable text editor for the 21st Century.
 Atom is a free and open source text editor that is modern, approachable, and hackable to the core.
```

```
$ apm --version
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.16
git 2.20.1
```

After manually fixing the file's permissions:

```
$ atom --version
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```

### Additional Information

Thanks for reaching out!

**Comment by allefeld** [comment]
Same problem here. Setting chrome-sandbox to mode 4755 manually works, but this should be fixed in the Debian package.

**Comment by Descear** [comment]
> Same problem here. Setting chrome-sandbox to mode 4755 manually works, but this should be fixed in the Debian package.

Thanks for reaching out!

Yeah, exactly.

**Comment by adibest** [comment]
I get the same problem on Ubuntu 18.04

**Comment by herpus-derpus** [comment]
Got the same on Debian 10 "Buster " myself.
Have responded on an atom discuss post with quick guidance for downgrading back to 1.46.0 , along the lines of:

    sudo apt-get install atom=1.46.0

**Comment by cold-distance** [comment]
I can't run Atom 1.47 on Debian Bullseye (Testing). It seems there is a regression and yes, I saw something related to sandbox trying to start from GNOME Terminal.

**Comment by darangi** [comment]
Thanks @Descear for reporting, we are working on reproducing this.

**Comment by cielavenir** [comment]
`sudo chmod 4755 /usr/share/atom/chrome-sandbox` reverts when new updates come; this can be done instead as permanent workaround:

```
sudo sysctl kernel.unprivileged_userns_clone=1
echo "kernel.unprivileged_userns_clone=1" | sudo tee /etc/sysctl.d/electron-fix.conf
```

https://github.com/electron/electron/issues/17972#issuecomment-486927073

**Comment by Descear** [comment]
> `sudo chmod 4755 /usr/share/atom/chrome-sandbox` reverts when new updates come; this can be done instead as permanent workaround:

When installed via system package managers (APT, YUM, etc), this _should_ not be the case. The permanent fix is to package the software correctly.

Thanks for reaching out!

I _think_ that something like this needs to be added to `script/lib/create-debian-package.js`:

```js
fs.chmodSync(
  path.join(
    debianPackageAtomDirPath,
    'chrome-sandbox'
  ),
  '4755'
);
```

And something similar in `script/lib/create-rpm-package.js`.

However, if you install via Npm, yeah, do use that workaround, I guess.

**Comment by yadickson** [comment]
Hello,

If you run atom by command line

$ atom --no-sandbox --disable-setuid-sandbox

This work OK

But, sudo sysctl kernel.unprivileged_userns_clone=1 is not recommended by vulnerabilities 

Best regards

**Comment by Jackfritt** [comment]
Also when editing root files etc. no Policy-Kit KDE Agent Window pops up for root password....
with old atom you could also edit files with "sudo atom file" this doesnt work also...
Got back to 1.46 with
sudo apt-get install atom=1.46.0
Now everything works as expected. 
Tried all workarounds mentioned here. But Policy-Kit and "sudo atom" didnt work with this.

**Comment by lebarde** [comment]
Same problem here on Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux.

**Comment by markcrossland** [comment]
I think this is all Linux distributions as the file has not been packaged correctly (we get this issue on our RHEL systems).

**Comment by Descear** [comment]
This is also reproducible on Fedora 32 after running this to break `CLONE_NEWUSER`, thus forcing it to use `chrome-sandbox`:

```
$ sudo sysctl user.max_user_namespaces=0
user.max_user_namespaces = 0
```

```
$ atom
/usr/bin/atom: line 190:  5098 Trace/breakpoint trap   (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$ATOM_HOME/nohup.out" 2>&1
[5098:0528/192220.451077:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/share/atom/chrome-sandbox is owned by root and has mode 4755.
```

**Comment by herpus-derpus** [comment]
> Got the same on Debian 10 "Buster " myself.
> Have responded on an atom discuss post with quick guidance for downgrading back to 1.46.0 , along the lines of:
> 
> ```
> sudo apt-get install atom=1.46.0
> ```

You may also wish to 'hold' the package at that 1.46.0 version with:
```
sudo apt-mark hold atom
```

Unhold with:
```
sudo apt-mark unhold <package-name>
```

Show all packages on hold:
```
sudo apt-mark unhold atom
```

**Comment by xXxrAinZyian** [comment]
Ok
