### ISSUE TITLE
Atom update flagged by antivirus

### ISSUE THREAD

**Issue by jpruiz114** [atom/atom#20758]
Hello,

Not sure if I'm going to report this in the right place but I got this warning by my antivirus:

![image](https://user-images.githubusercontent.com/4614970/82386930-ae6a4180-9a03-11ea-974e-3183885e6caf.png)

Is this normal?

Thanks.

**Comment by Arcanemagus** [comment]
We've had issues with Avast marking the updates as false positives before. As we aren't Avast though there is nothing we can do to fix it, you'll need to switch AV providers, contact them, or whitelist the update.
