### ISSUE TITLE
Atom No Longer launches after 1.47.0 Auto Update

### ISSUE THREAD

**Issue by OneSkiRalph** [atom/atom#20788]
Received this error when I launched Atom after auto update this morning.
Win 10 build 1087

![image](https://user-images.githubusercontent.com/4132641/82689741-f8803c80-9c28-11ea-9aa7-4cdb8d7532ce.png)

I am able to launch 1.46.0 in the app-1.46.0 folder.

**Comment by lkashef** [comment]
This looks like an installation issue, are you able to install 1.47 directly from atom.io?

**Comment by OneSkiRalph** [comment]
That worked! Thanks for your rapid response.
I opened Atom for a quick look this am and then closed it in < 1 minute. I wonder if this caused the installation issue?
Have a good day.
