### ISSUE TITLE
Find and replace across multiple files does not expand regex groups

### ISSUE THREAD

**Issue by Vanille-N** [atom/atom#20796]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Regex groups are not properly expanded in the actual project-wide find-and-replace, whereas the expected result is properly displayed on the preview

### Steps to Reproduce

1. Create a new project folder and add files
```
~/project$ ls
a.txt      b.txt
~/project$ cat a.txt
'A'
~/project$ cat b.txt
'B'
```
2. Open the folder in Atom
3. Open find-and-replace for whole project (Ctrl+Shift+F)
4. Enable Regex search
5. Find: `'(.)'`
6. Replace with: `<$1>`
![image](https://user-images.githubusercontent.com/58042063/82727496-27f77d80-9ceb-11ea-9a1e-1880188b8501.png)

**Expected behavior:**
```
~/project$ cat *
<A>
<B>
```
This behavior is not only what would happen in single-file find-and-replace, but also what the preview shows:
![image](https://user-images.githubusercontent.com/58042063/82727557-7ad13500-9ceb-11ea-8351-78406dd4da09.png)

**Actual behavior:**
```
~/project$ cat *
<$1>
<$1>
```

**Reproduces how often:**
100%

### Versions

Ubuntu 20.04
```
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```
```
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.18rc1
git 2.25.1
```

**Comment by darangi** [comment]
See https://github.com/atom/text-buffer/pull/318#issuecomment-613223586
