### ISSUE TITLE
Multi Cursor Click does not work

### ISSUE THREAD

**Issue by dustinmoorenet** [atom/atom#20803]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Multi Cursor clicking (using Ctrl) does not work. Multiple cursors are still possible with Shift+Alt arrow keys and Ctrl+D. This started happening after updating to beta version 1.48.0-beta0.

### Steps to Reproduce

1. Click to put cursor initially
2. Ctrl+Click at another location to attempt to add second cursor
3. Cursor moves to the new position instead of creating a second cursor

**Expected behavior:**

It should create a second cursor

**Actual behavior:**

It moves the cursor

**Reproduces how often:**

100%

### Versions

13:48 $ atom-beta --version
Atom    : 1.48.0-beta0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

### Additional Information

I noticed the new properly in settings for disabling the multi cursor click. I have tried disabling and enabling it, restarting and disabling and re-enabling, but nothing makes it work. I assume the work to add this properly to settings has somehow broken the multi cursor clicking.

**Comment by UziTech** [comment]
It looks like the setting it checks `core.editor.multiCursorOnClick` should be `editor.multiCursorOnClick`. This should be fixed by #20804

**Comment by mcelicalderon** [comment]
The PR pretty much already says it, but just in case, this is how you can fix it until this is released.

Edit your `~/.atom/config.cson` and add the key:

```yml
"*":
  core:
    editor:
      multiCursorOnClick: true

**Comment by NodeJoSe** [comment]
> #20804 pretty much already says it, but just in case, this is how you can fix it until this is released.
> 
> Edit your `~/.atom/config.cson` and add the key:
> 
> ```yaml
> "*":
>   core:
>     editor:
>       multiCursorOnClick: true
> ```

This partially works, the multi cursor is still bugged, sometimes it won't work, we need a fix :(

**Comment by UziTech** [comment]
You can also open the console (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>) and run `atom.config.set('core.editor.multiCursorOnClick', true);`

**Comment by kevinashworth** [comment]
> Temporary fix:
> Open the console (Ctrl + Shift + I) and run
> `atom.config.set('core.editor.multiCursorOnClick', true);`

There's a console? That keystroke doesn't do anything for me. Am I missing a console package?

I edited ~/.atom/config.cson, per mcelicalderon, and the behavior didn't change.

Thanks for any further help!

**Comment by UziTech** [comment]
If you are on a mac it might be <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>

Or you can find it in the Command Palette called `Window: Toggle Dev Tools`
Or in the top menu `View -> Developer -> Toggle Developer tools`

**Comment by kevinashworth** [comment]
Thanks, @UziTech! Ran command in the console under DevTools. Multi cursor restored. 👏

(It's Option + Command + I for me.)
