### ISSUE TITLE
Everything's right but, can't install atom on Ubuntu 14.04

### ISSUE THREAD

**Issue by Bost** [atom/atom#2080]
It seems like script/build should generate something under /tmp/atom* but it does not.
Does anyone know where's the catch?

thx

Bost

~/dev/atom$ lsb_release -d
Description:	Ubuntu 14.04 LTS

~/dev/atom$ uname -i
x86_64

~/dev/atom$ nodejs -v
v0.10.28

~/dev/atom$ npm -v
1.4.9

~/dev/atom$ sudo apt-get install libgnome-keyring-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgnome-keyring-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

~/dev/atom$ sudo npm config set python /usr/bin/python2 -g

~/dev/atom$ script/build # Creates application at /tmp/atom-build/Atom

~/dev/atom$ ls -la /tmp/atom/
ls: cannot access /tmp/atom/: No such file or directory

**Comment by 50Wliu** [comment]
Can someone still reproduce this?

**Comment by mnquintana** [comment]
Gonna close this out now - please feel free to reopen / comment if you can reproduce this with the latest version of Atom (0.210.0)
