### ISSUE TITLE
Find is not working correctly

### ISSUE THREAD

**Issue by lihost** [atom/atom#20818]
For many cases "Find & Replace" does not work properly and lead us to believe that term/phrase that we searched does not exist but it still there.

It's really tricky to reproduce. Here is an example term i.e. "Check on Fifth Avenue". 
1. This phrase was existing in my document-1 and document-2. 
2. Now when I tried to search phrase(copied from document-2) in document-1, it does not find. 

Here is the screenshot for reference.

![image](https://user-images.githubusercontent.com/430504/82937497-1c06f800-9f45-11ea-8188-97275cbbe49f.png)

 
<br><br>

I also tried to edit phrases by removing last word "Avenue" and now Atom matches both... Strange!!!

![image](https://user-images.githubusercontent.com/430504/82936820-0218e580-9f44-11ea-9454-bff6ca3f2493.png)

<br><br>
--

I am using Atom on Mac.

![image](https://user-images.githubusercontent.com/430504/82936417-69826580-9f43-11ea-99ab-900c1573e384.png)

**Comment by jaap-karssenberg** [comment]
Same issue - snap package on ubuntu - atom 1.47.0 and 1.48.0

**Comment by sadick254** [comment]
I can't seem to reproduce the bug. I am running on
Atom: 1.48
MacOs: 10.15.5
![Screenshot 2020-07-20 at 13 49 37](https://user-images.githubusercontent.com/5238135/87929933-e3d8ed00-ca8f-11ea-9439-c8c109b94581.png)

Have you tried to run [atom on safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) and see whether you can reproduce the bug.
