### ISSUE TITLE
[language-rust-bundled] Syntax highlighting stops mid file with 1.47

### ISSUE THREAD

**Issue by ashthespy** [atom/atom#20828]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>

### Description

After upgrading to Atom 1.47.0 my Rust syntax highlighting seems to be broken in files >~200LOC.
![image](https://user-images.githubusercontent.com/16233271/83017274-a45bca80-a023-11ea-8ea4-2e7d30fc78d5.png)
 
### Steps to Reproduce

1. Open any Rust grammar file (`file.rs`)
2. Scroll down a few hundred lines
3. No more syntax highlighting

### Versions

```
 atom --version

 Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

> apm --version
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 3.7.5
git 2.25.0.windows.1
visual studio 2017
```
### Additional Information

Downgraded back to 1.46 and everything works as expected.. 
```shell
> atom --version

 Atom    : 1.46.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0

>apm --version
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.46.0
python 3.7.5
git 2.25.0.windows.1
visual studio 2017

**Comment by Rua** [comment]
I am having the same problem in 1.47. In my case, it seems to be caused by macros with namespace qualifiers in front of them. `log::error!` removes all highlighting from that point on, but changing that to `error!` makes it reappear.

**Comment by ashthespy** [comment]
Do you have a snippet to reproduce in isolation? 
In my case I noticed that it stumbles when it encounters signatures like this within the file. 
However pulling out just this snippet works fine in isolation.. 
```rust
    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }
```

**Comment by Aerijo** [comment]
Not sure if it's the exact same bug (seen it in many Atom versions), but I'll add it here for good measure. 

In my experience it is an error in the parse tree that triggers it, but it isn't able to resolve the error. Tends to happen when there's a lot of functions in an `impl` for example (it's really noticeable because the text below where I'm editing flashes white and colored as it breaks and recovers).

I tried reducing the example, but I think it turned into a different issue; here's the minimal one though
```
match foo {
    Foo::Foo { foo } => {}
    // panic!("Unimplemented instruction: {:?}", instr);
}
```
deleting the first `}` on line 2 causes the comment on line three to be plain coloured, even though one would expect comments to remain comments. Unfortunately, the issue I meant to reproduce includes the remaining match patterns turning plain too and reduced highlighting (e.g., `let` colours but function calls do not) in the rest of the method. This doesn't happen in the example above.

**Comment by ashthespy** [comment]
Managed to distil down a snippet here as well. Found a case within an `imp`  block. 
Not really sure what is going on here - but it seems to misread the commented out section, causing issues. 
![image](https://user-images.githubusercontent.com/16233271/83034553-abd99e80-a038-11ea-8330-f724314e6580.png)
Further commenting out the block with trouble fixes the rest...
![Rust_tree_sitter](https://user-images.githubusercontent.com/16233271/83035026-3c17e380-a039-11ea-86c4-7b4cdce01383.gif)

[Snippet](https://gist.github.com/ashthespy/7e334de95c1f56528d1ef3e9a9d75dab)

**Comment by MaxChu23** [comment]
Having same issue here with JavaScript files.
For me it ignores whole files, showing everything in grey/white even though it says `JavaScript` below, in the status bar.
<img width="1039" alt="Screenshot 2020-06-02 at 17 09 04" src="https://user-images.githubusercontent.com/32452032/83543083-c5c12880-a4f3-11ea-8b33-21b22458360c.png">

**Comment by ZeePal** [comment]
I am also seeing this with 1.47 & 1.48.
Sample src file: https://github.com/starship/starship/blob/master/src/modules/time.rs

Looks like its related to the `log::*!(` macros. If i comment them out it the highlighting continues till the next log macro where it goes white from their till EOF.

**Comment by rllola** [comment]
I am also seeing this and it also seems to be related to the use of macro.

**Comment by svoop** [comment]
I can trigger this behavior in different ways e.g. by folding and unfolding part of the code. Here's an example with a Ruby file and **Atom started in safe mode**:

![Screen Recording 2020-06-23 at 15 29 01](https://user-images.githubusercontent.com/7255/85410684-aef87980-b567-11ea-9737-4e0ac3339c82.gif)

**Comment by svoop** [comment]
The above happens on both 1.48 and 1.47 (macOS). This is very unfortunate because it means that you have to downgrade to 1.46 to work around it. And since the Atom fix for macOS Catalina was only introduced with 1.47 (see #20034), you have to trade one nasty problem with another. May I suggest you unpin #20034 in favor of this issue?

**Comment by ashthespy** [comment]
@darangi Looks like this is not effecting only Rust, but a lot of other grammars as well - any thing we can do to help figure out what is going on?

**Comment by windy1** [comment]
Really unfortunate bug. Kind of a bummer that even if you want to downgrade you have to fight with atom trying to auto-update itself. Hope this gets fixed soon :/

**Comment by CyborgSemon** [comment]
Unfortunately this is a much wider issue that started with the 1.47 release https://github.com/atom/atom/issues/21093

**Comment by darangi** [comment]
This has been [resolved](https://github.com/atom/atom/pull/21790) the fix can be gotten on atom nightly
