### ISSUE TITLE
npm included in Dockerfile base image is too old

### ISSUE THREAD

**Issue by cryobry** [atom/atom#20844]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Dockerfile will not build atom because npm is too old.

### Steps to Reproduce

1. `docker build -t build-atom .`
2. `docker run -v "$PWD:$PWD" -w "$PWD" build-atom script/build`

**Expected behavior:**

Atom is built.

**Actual behavior:**

Atom build fails out due to npm errors. npm is too old even to display its version number.

**Reproduces how often:**

100%

### Versions

N/A

### Additional Information

PR coming soon.

**Comment by sadick254** [comment]
Closed by #20845
