### ISSUE TITLE
Uncaught TypeError: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by maxpiot** [atom/atom#20871]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type undefined

```
At internal/validators.js:105

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.join (path.js:372:7)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:24548
    at Array.map (<anonymous>)
    at watcher.c.debounceMS (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:24400)
```

### Commands

```
     -0:50.3.0 julia-client:start-julia (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.4 
julia-client 0.12.5 
language-julia 0.19.3 
latex-completions 0.3.6 
tool-bar 1.3.0 
uber-juno 0.3.0 
```

**Comment by CraigDamlo** [comment]
Still getting error in 1.49.0

**Comment by hturner08** [comment]
Also still getting this error

**Comment by CraigDamlo** [comment]
Yes, same error on same system. Nothing changed, just updated ATOM.

**Comment by void4main** [comment]
Hi, I get this error with an open file from a network drive.
The source of the file is a raspberry pi (samba).
The error occurs when I change the user permissions on the the raspberry.
atom - windows10 -> network-drive -> network -> smb -> raspberry pi)

**Comment by UnnamedMoose** [comment]
I get the same issue while working with files on a cluster mounted as a network drive on Windows 10.

**Comment by felixbaron** [comment]
Same here. i also get the error on a mapped SMB windows drive.

**Comment by kuloPo-com** [comment]
The error happens as soon as I changed the permission of the file on SMB.

**Comment by bennyborn** [comment]
Being affected and having to work with this on a daily basis I was finally fed up enough to take matters into my own hands. Hopefully the PR gets merged into a release asap :\

**Comment by teddychao** [comment]
Same issue on macOS Big Sur

**Comment by TheParanoik** [comment]
Got the error after opening repo from remote gitlab repository.


**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type undefined

```
At internal/validators.js:112

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:24810
    at Array.map (<anonymous>)
    at watcher.c.debounceMS (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:24662)
```

### Commands

```
     -3:29.3.0 core:backspace (input.hidden-input)
     -2:48.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-shell-commands 1.5.0 
kite 0.206.0 
```
