### ISSUE TITLE
[language-rust-bundled] Combo of use::{something, *} and quoted str breaks highlighting

### ISSUE THREAD

**Issue by CriesofCarrots** [atom/atom#20884]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

If there is a nested star in a use statement and a quoted str, highlighting breaks after the star:

![image](https://user-images.githubusercontent.com/3030561/83820810-eff91e80-a68a-11ea-82c0-9cd0bef8c200.png)

### Steps to Reproduce

This is some simple code that produces the issue:

```
use crate::checks::{self, *};

pub fn foo() -> Result<(), Box<dyn error::Error>> {
    let string = "foo";

    Ok(())
}
```

**Expected behavior:**

Removing quotes fixes issue (I know this won't compile). Notice the highlighting in the fn declaration:

![image](https://user-images.githubusercontent.com/3030561/83820888-15862800-a68b-11ea-9372-2cddf99722a3.png)

Un-nesting or removing the star also fixes issue:

![image](https://user-images.githubusercontent.com/3030561/83821121-41a1a900-a68b-11ea-964e-205536b5ff14.png)

**Actual behavior:**

See description

**Reproduces how often:**

100% of the time

### Versions

```
$ atom --version
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

$ apm --version
apm  2.4.5
npm  6.2.0
node 10.2.1 x64
atom 1.47.0
python 2.7.16
git 2.24.1
```

MacOS, Catalina 10.15.4 (19E287)

**Comment by musam7781** [comment]
Nice

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed in https://github.com/atom/atom/pull/21790. It is currently scheduled for release when `v1.56` reaches Stable.
