### ISSUE TITLE
my notes.html

### ISSUE THREAD

**Issue by AmeenSadeqAmeenQasem** [atom/atom#20893]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

### Additional Information

Ameen Sadeq Ameen Qasem note.html

**Comment by AmeenAlshoafi** [comment]
> 
> 
> ### Prerequisites
> 
> * [ ] Put an X between the brackets on this line if you have done all of the following:
>     * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
>     * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
>     * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
>     * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
>     * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>
> 
> ### Description
> 
> 
> 
> ### Steps to Reproduce
> 
> 1. 
> 2. 
> 3. 
> 
> **Expected behavior:**
> 
> 
> 
> **Actual behavior:**
> 
> 
> 
> **Reproduces how often:**
> 
> 
> 
> ### Versions
> 
> 
> 
> ### Additional Information
> 
> Ameen Sadeq Ameen Qasem note.html

**Comment by AmeenAlshoafi** [comment]
Thank God a second account was created on Atom

**Comment by AmeenAlshoafi** [comment]
Thank God ATOM account was created

**Comment by AmeenSadeqAmeenQasem** [comment]
Markup language, markup language, or text markup language, a set of hints on text that defines how it is organized, described, or formatted, and these languages have been in use for decades, and in recent years they have been used in letter-row systems, word processing, and page editing World Wide Web.

**Comment by AmeenSadeqAmeenQasem** [comment]
لغة ترميزية (بالإنجليزية: Markup language)‏ أو لغة الترميز أو لغة توصيف النص، وهي مجموعة من التلميحات على نص تحدد كيف يُنظّم أو يُصف أو يُنسّق، وهذه اللغات مستخدمة منذ عقود، وفي السنوات الأخيرة أصبحت تستخدم في أنظمة صف الحروف ومعالجة النصوص وتحرير صفحات الشبكة العالمية.

**Comment by AmeenSadeqAmeenQasem** [comment]
Welcome <em>Ameen!</em>

**Comment by AmeenSadeqAmeenQasem** [comment]
Welcome <em>Ameen!</em>

**Comment by Arcanemagus** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:

**Comment by AmeenSadeqAmeenQasem** [comment]
Hello sir Why is my account number 20893 closed? Please help me to open and use this account   
  
  

  
  
  

  
  
>
