### ISSUE TITLE
Rust's `async` Keyword not Recognized by Atom

### ISSUE THREAD

**Issue by slightknack** [atom/atom#20905]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

As described in [The Rust Programming Language](https://doc.rust-lang.org/book/appendix-01-keywords.html?highlight=keywords#keywords-currently-in-use), `async` is a keyword used to mark asynchronous functions. Currently, Atom's Rust syntax highlighter doesn't recognize `async` as a keyword.

### Steps to Reproduce

1. Create a new file with the language set to Rust
2. Enter an async function, such as `pub async fn main() {}`.
3. `async` won't be highlighted.

**Expected/Actual behavior:**

`async` currently isn't highlighted as a keyword, but it should be. I've also noticed that other keywords, such as `as`, `await`, and `self` aren't highlighted as keywords.

**Reproduces how often:**

Reproduces all of the time.

### Versions
```
Atom    : 1.47.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
MacOS   : 10.15.5 
```

**Comment by sadick254** [comment]
@slightknack This issue has now been fixed on the l[atest release 1.50](https://github.com/atom/atom/releases/tag/v1.50.0)
