### ISSUE TITLE
"Multi Cursor on Click" seems to always be disabled in Atom 1.48.0

### ISSUE THREAD

**Issue by garyb** [atom/atom#20911]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Multiple cursors on click don't seem to work now - this is regardless of whether "Multi Cursor on Click" is checked or not in the Editor panel. Disabling it in the settings does add the key to `config.cson`, but explicitly setting it to true in the config file does not work either.

### Steps to Reproduce

1. Open a file
2. Hold `Ctrl` and click multiple locations in the file

**Expected behavior:**

Multiple cursors to be active at each location that is clicked.

**Actual behavior:**

The cursor moves to the last location that is clicked.

**Reproduces how often:**

100%

### Versions

```
Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```
```
apm  2.5.0
npm  6.14.5
node 10.20.1 ia32
atom 1.48.0
python 2.7.10
git 2.18.0.windows.1
visual studio 2015
```

Windows 10

### Additional Information

I know this can arise due to an interaction with hyperclick, but that should not be the case here as I have my hyperclick configured to use another key combination. Also I did check that it occurs in safe mode.

**Comment by seanoquinn** [comment]
Updating the config file with multiCursorOnClick: true did not work for me

**Comment by LRydin** [comment]
Same here. I've tried the usual steps. Removed `hyperclick`, reinstalled `hyperclick`, installed and uninstalled `atom-ide-ui`. `atom --safe` also does not have multi cursor selection anymore. `multiCursorOnClick: true` did nothing.

**Comment by Anthonykung** [comment]
> @HugoMcPhee posted and deleted a comment linking to #20804 which does indeed seem to offer a fix for this 😄
> 
> As a workaround I added
> 
> ```
> editor:
>   multiCursorOnClick: true
> ```
> 
> under `core` in my `config.cson` which resolves it for now, so thanks for that! 👍

This workaround doesn't work for me, reverting to version 1.47 seems to be a better option

**Comment by NicoSchulthess** [comment]
> 
> 
> > @HugoMcPhee posted and deleted a comment linking to #20804 which does indeed seem to offer a fix for this smile
> > As a workaround I added
> > ```
> > editor:
> >   multiCursorOnClick: true
> > ```
> > 
> > 
> > under `core` in my `config.cson` which resolves it for now, so thanks for that! +1
> 
> This workaround doesn't work for me...

At first, it was a bit misleading, but the key is to add the workaround under `core`. So in the end, I set it like that and it worked:
```
"*":
  core:
    editor:
      multiCursorOnClick: true
```

**Comment by LRydin** [comment]
I can confirm this works on my Atom (Ubuntu 19.04). Make sure to find the existent
```
"*":
  core:
```
and add `multiCursorOnClick: true` there. Don't open a new `core` if one already exists.

**Comment by dariygray** [comment]
> > > @HugoMcPhee опубликовал и удалил комментарий, ссылающийся на [# 20804,](https://github.com/atom/atom/pull/20804) который действительно предлагает исправление этой улыбки. 
> > > В качестве обходного пути я добавил
> > > ```
> > > editor:
> > >   multiCursorOnClick: true
> > > ```
> > > 
> > > 
> > > по `core`моему, `config.cson`который разрешает это сейчас, так что спасибо за это! +1
> > 
> > 
> > Этот обходной путь не работает для меня ...
> 
> Сначала это немного вводило в заблуждение, но главное - добавить обходной путь `core`. В итоге я установил это так, и это сработало:
> 
> ```
> "*":
>   core:
>     editor:
>       multiCursorOnClick: true
> ```

Works on Windows 10 build 2004

**Comment by kierandelaney** [comment]
QA on Atom is getting rougher and rougher, this was reported nearly three weeks ago during the beta. The last release broke several prominent plugins and this release has broken one of the editors' key features. 

The fix above works on all platforms, just ensure you find the appropriate place to insert the config lines (you probably have core already, you may have editor).

**Comment by NetSpud** [comment]
I've tried this, but no success, I tried it in safe mode as well, but no luck.

Anyone able to advise on what to do next?

**Comment by LRydin** [comment]
@NetSpud Maybe revert back to Atom 1.47?

**Comment by mrleblanc101** [comment]
The fix above worked for me, make sure your syntax is valid. Make sure to put it under "core" as said, if it doesn't exist, add this key as parent. You might need to relaunch atom to see the change

**Comment by DanielTamkin** [comment]
@NicoSchulthess Thanks! Curious as to why the `editor` key is below the `core` for this version.

**Comment by mrleblanc101** [comment]
> @NicoSchulthess Thanks! Curious as to why the `editor` key is below the `core` for this version.

The keys are sorted in alphabetical order the next time your relaunch atom

**Comment by ryangall7** [comment]
Can't get it working with `multiCursorOnClick: true` on my Mac... Till this is fixed I'm moving back to SublimeText

**Comment by danadaldos** [comment]
If you add   `multiCursorOnClick: true` under 

```
"*":
  editor:
```

This WILL NOT WORK. You need to add it under:

```
"*":
  core:
    editor:
        multiCursorOnClick: true
```

Which, for me, required adding a new `editor:` section under `core:`

**Comment by swamichan** [comment]
> If you add `multiCursorOnClick: true` under
> 
> ```
> "*":
>   editor:
> ```
> 
> This WILL NOT WORK. You need to add it under:
> 
> ```
> "*":
>   core:
>     editor:
>         multiCursorOnClick: true
> ```

This worked for me, but make sure you add it right under `core:` if you have other lines put them after `multiCursorOnClick: true`

**Comment by UziTech** [comment]
You can also open the console (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>) and run `atom.config.set('core.editor.multiCursorOnClick', true);`

**Comment by Clinton594** [comment]
Thanks so much;
This worked for me.
Using atom 1.48.0 on windows build 1909.

**Comment by mortche** [comment]
I noticed something weird in my config.cson. Its beginning looked like this after an update:
```cson
"*"
    "*"
        "atom-material-ui": ...
        "autoclose-html": ...
        more plugins...
    "atom-material-ui": ...
    "autoclose-html": ...
    more plugins...
```
The "\*" property included the same property again and the whole tree of configurations with it. So i deleted this nested branch, then added `multiCursorOnClick: true` to "\*".core.editor, as multiple people mentioned here, and it works

Atom 1.48.0, windows 10 build 1909

**Comment by surcoufx83** [comment]
> You can also open the console (Ctrl + Shift + I) and run `atom.config.set('core.editor.multiCursorOnClick', true);`

Thanks, this worked for me

**Comment by NetSpud** [comment]
> Can't get it working with `multiCursorOnClick: true` on my Mac... Till this is fixed I'm moving back to SublimeText
Yeah. I think I'm going to end up going back to vs code now...

**Comment by fmarrot** [comment]
> You can also open the console (Ctrl + Shift + I) and run `atom.config.set('core.editor.multiCursorOnClick', true);`

This works for me on Windows 10, editing core config didn't work

**Comment by lkashef** [comment]
Thanks for your feedback @fmarrot 

---
For the folks trying the workaround, `atom.config.set` is just an Atom API function that updates the config file, if you call it while having the config file open, you will notice the changes.

Changing the config file can be tricky if you are not familiar with it, so running the function is definitely more straightforward.

**Comment by yoarch** [comment]
```
"*":
  core:
    editor:
        multiCursorOnClick: true
```
Worked for me on archlinux.

**Comment by alnikolaj** [comment]
multiCursorOnClick: true does not work for me (Mac). This is super frustrating. Any alternative solution? Thanks in advance.

**Comment by LRydin** [comment]
@alnikolaj as mentioned before, you can downgrade/revert back to Atom 1.47, that should work :)

**Comment by Outright-Graham** [comment]
Windows 10, version 1909 / Atom Vers 1.48.0

_This did not work in my config.cson file:_

"*":
  core:
    telemetryConsent: "no"
    uriHandlerRegistration: "always"
  editor:
    fontSize: 13
    multiCursorOnClick: true
    softWrap: true
  "exception-reporting":
    userId: "7cf655aa-a3bf-4c7d-a891-2672ad8a81d4"


_This DID work for me (no idea why) in my config.cson file:_

"*":
  core:
    telemetryConsent: "no"
    uriHandlerRegistration: "always"
  editor:
    fontSize: 13
    softWrap: true
  "exception-reporting":
    userId: "7cf655aa-a3bf-4c7d-a891-2672ad8a81d4"

"*":
  core:
    editor:
      multiCursorOnClick: true

**Comment by lkashef** [comment]
@Outright-Graham I would recommend resetting your config.cson and using [this workaround](https://github.com/atom/atom/issues/20911#issuecomment-643035860) to avoid missing up your config file

**Comment by ivabby** [comment]
> "*":
>   core:
>     editor:
>       multiCursorOnClick: true

Yes this worked for me too.

**Comment by BryantIT** [comment]
> @HugoMcPhee posted and deleted a comment linking to #20804 which does indeed seem to offer a fix for this 
> 
> As a workaround I added
> 
> ```
> editor:
>   multiCursorOnClick: true
> ```
> 
> under `core` in my `config.cson` which resolves it for now, so thanks for that!

This not work for me. In fact if I put that in and close Atom, it will not open back up.  I tried this 3 times.  All 3 times it would cause Atom to error with:
`ninjalikereflex@codeninja:~$ atom -f
literal is not a function
[stdin]:44:11: error: literal is not a function`

If I delete the line (3rd time I was smart enough to have two editors open) Atom continues to work as normal.

**Comment by mzunigau** [comment]
> You can also open the console (Ctrl + Shift + I) and run `atom.config.set('core.editor.multiCursorOnClick', true);`

This worked for me. Restart is needed.

**Comment by dlewand691** [comment]
I'm also having the same issue and none of the solutions worked for me. 
- Hyperclick or atom-ide-ui not installed
- Ran `atom -safe` and not working
- Ran `atom.config.set('core.editor.multiCursorOnClick', true);` and get the error `zsh: number expected`
- Added `multiCursorOnClick: true` to config.cson under `editor:` with no results

Tried adding this in addition to all other configs:
```
 "*":
  core:
    editor:
      multiCursorOnClick: true
``` 
but that totally hosed my entire configuration and was luckily able to revert.

Will have to disable all plugins and go one-by-one to find the culprit.

**Comment by leondgarse** [comment]
> I'm also having the same issue and none of the solutions worked for me.
> 
> * Hyperclick or atom-ide-ui not installed
> * Ran `atom -safe` and not working
> * Ran `atom.config.set('core.editor.multiCursorOnClick', true);` and get the error `zsh: number expected`
> * Added `multiCursorOnClick: true` to config.cson under `editor:` with no results
> 
> Tried adding this in addition to all other configs:
> 
> ```
>  "*":
>   core:
>     editor:
>       multiCursorOnClick: true
> ```
> 
> but that totally hosed my entire configuration and was luckily able to revert.
> 
> Will have to disable all plugins and go one-by-one to find the culprit.

I think you are runing `atom.config.set('core.editor.multiCursorOnClick', true);` in your shell? it should be run under atom console.
Steps which work in my case:
- Open `setting` page first, as `Ctrl + Shift + I` is binded for insert image...
- Then press `Ctrl + Shift + I` to open atom console.
- Run `atom.config.set('core.editor.multiCursorOnClick', true);` after the `>` prefix.
- Restart `atom`, and it works!
- Check your config file, for me it's `~/.atom/config.cson`, and you can see `multiCursorOnClick: true` is added there.

**Comment by klcrowddesk** [comment]
When I'm running `atom.config.set('core.editor.multiCursorOnClick', true);` it just returns with `[No Match]` and nothing further happens. Does anybody know what the issue might be for that?

**Comment by UziTech** [comment]
@klcrowddesk 

> When I'm running `atom.config.set('core.editor.multiCursorOnClick', true);` it just returns with `[No Match]`

Where are you running it?

You should be running it in your developer console in Atom.

**Comment by klcrowddesk** [comment]
@UziTech 

I actually had no idea where to run it (quite new to atom) but then I found the atom-console package and tried that. Also I had to disable the Welcome package manually in the settings (just unchecking it with in the tab didn't work).

**Comment by UziTech** [comment]
To open the developer console you can click [View]->[Developer]->[Toggle Developer Tools]. Then click console and type the command. They are built into Atom and they are the same as the Chrome developer tools.

![image](https://user-images.githubusercontent.com/97994/87051302-0718b800-c1c5-11ea-999d-a53aab33a6e3.png)

![image](https://user-images.githubusercontent.com/97994/87051203-e0f31800-c1c4-11ea-85e2-433fc641532c.png)

**Comment by klcrowddesk** [comment]
> To open the developer console you can click [View]->[Developer]->[Toggle Developer Tools]. Then click console and type the command. They are built into Atom and they are the same as the Chrome developer tools.
> 
> ![image](https://user-images.githubusercontent.com/97994/87051302-0718b800-c1c5-11ea-999d-a53aab33a6e3.png)
> 
> ![image](https://user-images.githubusercontent.com/97994/87051203-e0f31800-c1c4-11ea-85e2-433fc641532c.png)

Awesome, thanks!

**Comment by dlewand691** [comment]
@UziTech @leondgarse OMG that worked! I was running it from my shell, not in Atom. THANK YOU!!! I could kiss you if we weren't in this damn pandemic 😘

**Comment by Nootaku** [comment]
Thank you @NicoSchulthess for the clarification:
> "*":
>   core:
>     editor:
>       multiCursorOnClick: true
> ```

Works on Ubuntu 18.04 (Atom version 1.48.0 x64)

**Comment by Bug-Reaper** [comment]
This worked lol, can I put in a PR to fix this for everybody? 


Also here's my full config after applying this patch. Note that `editor:` can appear under multiple parents:
```"*":
  "activate-power-mode":
    comboMode:
      streakTimeout: 100
    plugins:
      playAudio: true
      screenShake: true
  "atom-beautify":
    general:
      _analyticsUserId: "*******************************************************"
  core:
    editor:
      multiCursorOnClick: true
    disabledPackages: [
      "spell-check"
    ]
    telemetryConsent: "limited"
  editor:
    fontSize: 46
  "exception-reporting":
    userId: "***************************************************"
  "tree-view":
    hideVcsIgnoredFiles: true
  welcome:
    showOnStartup: false

```

You can access your own config with `Edit > Config`.

**Comment by UziTech** [comment]
@Bug-Reaper The PR #20804 has already been merged to fix this in the next release.

**Comment by wesleycsj** [comment]
> 
> 
> Windows 10, version 1909 / Atom Vers 1.48.0
> 
> _This did not work in my config.cson file:_
> 
> ```
> "*":
>   core:
>     telemetryConsent: "no"
>     uriHandlerRegistration: "always"
>   editor:
>     fontSize: 13
>     multiCursorOnClick: true
>     softWrap: true
>   "exception-reporting":
>     userId: "7cf655aa-a3bf-4c7d-a891-2672ad8a81d4"
> ```
> 
> _This DID work for me (no idea why) in my config.cson file:_
> 
> ```
> "*":
>   core:
>     telemetryConsent: "no"
>     uriHandlerRegistration: "always"
>   editor:
>     fontSize: 13
>     softWrap: true
>   "exception-reporting":
>     userId: "7cf655aa-a3bf-4c7d-a891-2672ad8a81d4"
> 
> "*":
>   core:
>     editor:
>       multiCursorOnClick: true
> ```

No others solutions worked to me, except this one. Thanks!
