### ISSUE TITLE
Atom 1.48.0 (2020-06-10) This Broke Multi-Highlight-Selected Package

### ISSUE THREAD

**Issue by Zwalraven** [atom/atom#20929]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Install Multi-Highlight-Selected
2. Click on a word to highlight
3. Press ctrl-click to highlight the next word, it will take the highlight off of the previous word.

Explained in #3

Explained n #3

Everytime

100%

### Additional Information

This is due to the Multiple Cursors toggle in Editor, I'm sure of it, because it is tied to that command and was not present before 1.48.0 This feature should be standard on Atom anyway Notepad++ has had it for years.

Before you ask I've tried it with the toggle on and off to no avail.

**Comment by ivanreese** [comment]
Do multiple cursors work for you? For instance, can you ctrl/command-click to put down multiple cursors at all?

**Comment by Zwalraven** [comment]
I no longer have that version installed, but if they did work, I would 
imagine the package would have worked as well. What I do know is whatever 
changed from 1.47.0 to 1.48.0 broke the package, and I can't do the work I 
need without it. The only feature I can think of that is tied to it is the 
cursor toggle. Are you able to make the package work on 1.48.0?

**Comment by ivanreese** [comment]
Yes, that package works for me using multiple cursors.

Version 1.48.0 has a bug that prevents multiple cursors from working, regardless of the way the new setting is set. If you check the [closed issues](https://github.com/atom/atom/issues?q=is%3Aissue+is%3Aclosed) page, you'll see a ton of people are hitting this. The comment I linked has the necessary fix while we wait for an updated version.

Cheers!

**Comment by Zwalraven** [comment]
This is wonderful news. I will just wait for the next version!
