### ISSUE TITLE
Multiple cursor not working after last Atom update

### ISSUE THREAD

**Issue by massimilianocomin** [atom/atom#20925]
Hello,

After the last update of Atom the multiple-cursor functionality stopped working !

Here is my version info:
Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

I am running on MacOS Mojave 10.14.6.

Thank you for your help !

EDIT: The issue appears in safe mode as well !

**Comment by Wintercypher** [comment]
Can confirm this just happened to me. I did a full factory reset of atom as well. Safe mode checked as well. Been pulling my hair out. I was however able to get the OPTION-SHIFT multi cursor working. I am still unable to get cmd+left click working. Been trying everything to the point that I'm starting to wonder if it was CMD+left click lol. 

Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

I had hyperclick disabled and I have changed those key binds and uninstalled. Also checked app cache etc.

**Comment by LonerganOnline** [comment]
I am also experiencing this issue,
OS:  Windows 10 
Atom : 1.48.0

**Comment by Trolleymusic** [comment]
I am also experiencing the same issue:

MacOS 10.15.5

Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

Have checked safe mode, and have checked with hyperlink disabled.

**Comment by apisdigital** [comment]
I think its a issue for everyone. We must wait for a solution.

**Comment by CyborgSemon** [comment]
Yep having same issue here on latest version. Also on MacOS 10.14.6

**Comment by UziTech** [comment]
duplicate of #20803 should be fixed in #20804 

temporary fix:
Open the console (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>) and run
`atom.config.set('core.editor.multiCursorOnClick', true);`
