### ISSUE TITLE
Atom startup broken, empty treeview, and also creates weird files

### ISSUE THREAD

**Issue by hollowdoor** [atom/atom#20937]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

I did not x the above since I cannot reproduce the exact problem in safe mode. In safe mode the treeview is empty, but the weird files aren't opened.

### Description

I open Atom, the treeview is now empty, and two non-existent files are opened that I never created.

One file is named `ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false`, and appears as in my home directory. The other file is named `atom`, and appears as in usr/bin. Neither file actually exists. They are just created, yet not saved.

As far as any other state, as far as I can tell any app state is just forgotten by Atom. But I can't tell why. Is it related to the treeview getting reset? Is it because of the weird files getting opened? I don't know.

### Steps to Reproduce

I have no way to describe how to reproduce the behavior because I simply opened atom yesterday, and it worked. And after opening it today it didn't work. The only difference between yesterday, and today is that I restarted my computer.

**Expected behavior:**

Atom opens with my projects in the treeview, and doesn't open weird files.

**Actual behavior:**

On starting Atom the Treeview doesn't open. When treeview is opened no projects are in it. After adding a project if I close Atom, and start it again the treeview is empty again.

If I add a project on restarting Atom the `~/.atom/storage/application.json` gets rewritten removing all projects.

On starting Atom weird files `~/ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false`, and `usr/bin/atom` are opened. These files are not yet written to my hard drive.

**Reproduces how often:**

Every time starting Atom.

### Versions

* apm  2.5.0
* atom 1.48.0
* ubuntu 20.04 LTS

### Additional Information

I tried deleting the `.atom` directory. After nuking `.atom` the problem persists. I thought of posting this problem in the forums, but this doesn't seem like something that can be simply fixed with advice. It's a very strange behavior which I had no hand in initiating.

To me it seems like atom is opening with `atom`, and `~/ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false` as files as if those were added in the command line. But I'm not running Atom from the command line. And that doesn't explain why the `~/.atom/storage/application.json` file keeps getting overwritten.

**Comment by hollowdoor** [comment]
Okay. I have an update. I uninstalled Atom. Then I deleted the `~/.atom`, and `~/.config/Atom directories.

I then reinstalled Atom. When I started the newly installed Atom the problem was still there. Weird!

It's a snap in the Ubuntu repos.

While writing this comment I stopped, and uninstalled Atom again. Then I went to the website, downloaded the .deb file, installed that, and the problem appears to be resolved for me.

I'm not closing this issue yet because there still might be something to sort out. The solution probably shouldn't be to reinstall from a different source. I deleted all config files just in case, and that shouldn't be a solution either.

Does anyone one know who authors the snaps? This newly installed version is the same version as the one I had installed before. So the problem must be in the snap.

**Comment by Danfro** [comment]
I can confirm this issue with the snap package. I have not tried yet the .deb version.

**Comment by hollowdoor** [comment]
@Danfro Oh good. I was thinking I might be the only one. I wish I knew more about Atom internals. I'm dying to know if it's a conflict with something Atom does, or just bad packaging. There's been no response so far by anyone at snapcrafters.

**Comment by connesy** [comment]
For me, everything is fine if I just open `atom` from the terminal, however the snap generated `.desktop` file in `/var/lib/snapd/desktop/applications/atom_atom.desktop` has the line 
```
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/atom_atom.desktop /snap/bin/atom ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom %F
```
which atom is apparently interpreting "as `use /snap/bin/atom` to open these two files".

**Comment by Aerijo** [comment]
Thanks for reaching out!

We've determined that you are currently using an unofficial build or distribution of Atom. Often these customized versions of Atom are modified versions of the Stable branch of Atom with mismatched versions of built-in components. These updated components are taken from the Beta channel or `master` branch and then injected into the Stable version and a new Atom package is generated. Because of the way Atom is constructed, using these mismatched components can cause mysterious and hard-to-diagnose problems. You can find out more about [why we chose to not support unofficial distributions here](https://github.com/atom/design-decisions/blob/master/unofficial-atom-distributions.md).

You can find instructions for installing an official version of Atom in the [Flight Manual](https://flight-manual.atom.io/getting-started/sections/installing-atom/). If you are still seeing this problem on an official build please file a new issue, thanks!

**Comment by hollowdoor** [comment]
@Aerijo Yes, I have installed from the official distribution (.deb file), and don't have the same problems. As I wrote above, but I'm rewriting it here so it's easy for others to find.

**Comment by fholzer** [comment]
I have the same issue on windows with the official build
