### ISSUE TITLE
os.release is function

### ISSUE THREAD

**Issue by mahnunchik** [atom/atom#20936]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

It seems there is misuse `os.release` as a value not as a function:

https://github.com/atom/atom/blob/b6dd3408ab79be22685d517af92bcf7d4723c93f/src/main-process/auto-update-manager.js#L38-L49

### Additional Information

Documentation: https://nodejs.org/docs/latest-v8.x/api/os.html#os_os_release

**Comment by sadick254** [comment]
@mahnunchik Thank you for opening this issue.

`os.release` works fine as is. You can try out this example
```js
const os = require('os')
// This works fine
console.log(`${os.release}`)

// As well as this one
console.log(`${os.release()}`)
```
