### ISSUE TITLE
deb-src packages not published

### ISSUE THREAD

**Issue by kravietz** [atom/atom#20959]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom PPA repo contains binary `amd64` and `x86_64` DEB packages but no `apt-src` packages which makes anyone using other architectures very sad.

### Steps to Reproduce

1. Use RaspberryPi or Pinebook or any other `armhf` architecture
2. Configure `deb--src` repository in `/etc/apt/sources.list.d/atom.list` per [instructions](https://packagecloud.io/AtomEditor/atom/)
3. Run `apt-src install atom`

**Expected behavior:**

Run `apt-src install atom` and `apt-src build atom` to build a new binary package for your architecture on any platform from source.

**Actual behavior:**

`apt-src install atom` fails because the source DEB packages are not published in the above repo

**Reproduces how often:**

Alwasy.

### Additional Information

This is a simple omission in the CI/CD system I suspect that should be easy to fix as the DEB source packages are natural part of the binary DEB build cycle, they just need to be published into the repo.

**Comment by Arcanemagus** [comment]
Unfortunately, despite being based on Electron, Atom is not maintained on ARM architecture as has been [explained](https://github.com/atom/atom/pull/19924#issuecomment-534685868) [before](https://github.com/atom/atom/pull/19921#issuecomment-531990071). We aren't going to officially distribute a package we know is broken, sorry!
