### ISSUE TITLE
Ctrl + Left click not adding cursor

### ISSUE THREAD

**Issue by EnderArchery** [atom/atom#20966]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Ctrl + Left click won't add a new cursor anymore.
Safe mode, reset and even clean install don't change the behavior.
Crtl + Alt + Up/Down work.

### Steps to Reproduce

1. Open a new or existing file in Atom
2. Ctrl + Left click

**Expected behavior:**

Adding another cursor at the selected position

**Actual behavior:**

Nothing

**Reproduces how often:**

100%

### Versions

Windows 10 - 1909 Build 18363.900

Broken in:

- Atom (x64) - 1.48.0
- Atom (x86?) - 1.48.0
- Atom (x64) - 1.49.0 - beta 0

Working in:

- Atom (x64) - 1.47.0

**Comment by UziTech** [comment]
fixed in #20804

**Comment by UziTech** [comment]
here is a fix for Atom v1.48.0: https://github.com/atom/atom/pull/20804#issuecomment-643279418

**Comment by EnderArchery** [comment]
<table>
 <tr>
  <th>
   Steps
  </th>
  <th colspan="2">
   For people stumbling over this issue
  </th>
 </tr>
 <tr>
  <td>
   1
  </td>
  <td>
   Press
  </td>
  <td>
   <code>Ctrl</code>+<code>Shift</code>+<code>I</code>
  </td> 
 </tr>
 <tr>
  <td>
   2
  </td>
  <td>
   Enter
  </td>
  <td>
   <code>atom.config.set('core.editor.multiCursorOnClick', true);</code>
  </td> 
 </tr>
 <tr>
  <td>
   3
  </td>
  <td>
   Press
  </td>
  <td>
   <code>Enter</code>
  </td> 
 </tr>
</table

**Comment by EnderArchery** [comment]
> here is a fix for Atom v1.48.0: [#20804 (comment)](https://github.com/atom/atom/pull/20804#issuecomment-643279418)

Thank you very much
