### ISSUE TITLE
Return of Atom Helper using 100%+ of CPU #17587

### ISSUE THREAD

**Issue by newscloud** [atom/atom#20979]
### Description

Atom Helper is repeatedly taking up 100% CPU and running my laptop super hot. Restarting Atom does not stop this from re-occuring

### Steps to Reproduce

1. Run Atom
2. In Terminal run, Python with Selenium Wire and Selenium
(Atom Helper activity shoots to 100%)

If I close Atom, then run my Python script - the script runs fine without iit.

I haven't yet tested Atom overnight on its own.

**Expected behavior:**
No AtomHelper problems

**Actual behavior:**

![activitymonitor](https://user-images.githubusercontent.com/40822/85604564-401e2d80-b606-11ea-9943-6e2e3b4bf606.png)

**Reproduces how often:**
Always

### Versions
MacOS 10.15.5
Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.48.0
python 3.7.4
git 2.24.3

**Comment by axelJacquet** [comment]
Same probleme on macOS 10.15.4 
MacBook Pro (15-inch, 2018)
2,6 GHz Intel Core i7 6 cœurs
16 Go 2400 MHz DDR4
Intel UHD Graphics 630 1536 Mo

My colleague does not have this problem with his Macbook pro 2019 I9 16GB

**Comment by newscloud** [comment]
Atomhelper runs at 100% immediately upon using Selenium. But, it also occurs in normal usage of Atom while I'm editing. I've added https://github.com/atom/atom/issues/21116

**Comment by newscloud** [comment]
Disabling the github package appears to have resolved this. 
![Uploading disable-package-github.gif…]()
