### ISSUE TITLE
When saving a file without a .filetype added windows 10 does not recognize what type it is.

### ISSUE THREAD

**Issue by BatmanHG** [atom/atom#20980]
This is a minor incontinence but if I just save a file windows will not recognize what type of file it is. Every time I go to open the file I have to select a program to open it and it will not give me the option to save as default.

First image is showing that windows doesn't recognize the file type and is just using the default file and the second is showing that its not giving me the option to always use a certain program

![458](https://user-images.githubusercontent.com/22604970/85649681-5c06eb00-b669-11ea-9b59-cf76b7236836.png)
![459](https://user-images.githubusercontent.com/22604970/85649683-5c9f8180-b669-11ea-8227-7516d083bf02.png)

**Comment by Arcanemagus** [comment]
That's how simply how Windows works, it uses the [file extension](https://en.wikipedia.org/wiki/Filename_extension) to determine what type of file it is. You may be more familiar with how Linux / macOS handle this where they scan the first parts of the file's content to try to determine it for you.

Thanks for reaching out and hopefully that clears it up for you!

**Comment by BatmanHG** [comment]
I have used windows my whole life no other program does this when I save a file it will save as the correct file type without having to manual type it. The issue here is atom does not do this so this is not a windows issue this is an atom issue and im wondering if there is anyway this can be changed.
