### ISSUE TITLE
An error occurred, view the console for more information.

### ISSUE THREAD

**Issue by russell7** [atom/atom#20994]
[Enter steps to reproduce:]

1. open atom
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

An error occurred, view the console for more information.

```
At undefined

undefined
```

### Commands

```
     -0:21.6.0 application:open-folder (input.hidden-input)
```

### Non-Core Packages

```
atom-yarn 0.9.0 
language-vue 0.26.0 
vk-terminal 3.0.1 
```

**Comment by ClaymasterJ** [comment]
This is likely due to the `atom-yarn` package. I had the package installed when I got this error. I uninstalled it, and stopped getting it.

**Comment by russell7** [comment]
yes.
no error message occur when open non yarn directory.
By the way, it's not a regular yarn project , it's a npm project which accidentally  contains a yarn.lock file.

**Comment by therobgirl** [comment]
Robin Howard 

***Sent from my iPhone
