### ISSUE TITLE
atom is not recognised as an internal or external program

### ISSUE THREAD

**Issue by dikshasethi27** [atom/atom#21009]
Hi Folks,

I want to run the atom github code without install atom.exe in my window system.
According to url(https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#running-in-development-mode), 
I have setup everything on my system,
But when im trying to run the atom --dev command, it is throwing error 
**atom is not recognised as an internal or external program** 

Can you please help guys

Thanks

**Comment by llouii** [comment]
This is my first time, so forgive if i'm not correct :>
It says here that:
> If the atom command does not respond in the terminal, try `atom-dev` or `atom-beta`

**Comment by llouii** [comment]
If the `atom-dev` oor `atom-beta` does not work, i believe that it has something to do with the _Window's path environment variable._

PS. forgive me again if i'm not correct ;>

**Comment by sadick254** [comment]
@dikshasethi27 Thanks for reaching out!

Things you can do
- Run `script/build` which builds the app and generates an atom.exe at the root of the project inside the out folder
- Add the path to the exe in your environment variable
