### ISSUE TITLE
Application not showing in front, unable to view any file

### ISSUE THREAD

**Issue by ankur-worktable** [atom/atom#21013]
Install ATOM in Mac (Catalina - 10.15.4), use it for some time, use in full screen, after several times, no file is showing in ATOM. Double click on file, or select open with ATOM, it's showing Atom window open on top but no file is showing in screen.

If I re-install ATOM it works fine for some time, but again getting same problem.

Check this image for sample: https://drive.google.com/file/d/1nllSAPuSUyZztTl3WycVy5whzYOM2gs8/view?usp=sharing

**Comment by hlydecker** [comment]
I was also experiencing the same issue, with Catalina 10.15.5. Reinstalling initially did not work, however I was able to get Atom working again after first manually deleting everything in `~/.atom/`

I hope that helps (and that it stays working for me!)

**Comment by gbstan** [comment]
I have a similar issue: Atom doesn't display a window at launch when launched via icon (click on icon) or via launcher (e.g. Alfred or Spotlight) but does produce one when launched via the 'atom' command in a terminal.

I would love to know how to solve this without removing all my config and packages from the folder ~/.atom

**Comment by FlavSF** [comment]
Getting a similar issue on Mojave (OSX 10.14.6) with latest Atom. Any clue as to what's happening?

**Comment by hlydecker** [comment]
I know this isn't a proper fix, but you could try saving a copy of your config stuff separately, deleting the one in ~/.atom, then reinstalling and adding back in systematically to identify any causes.

**Comment by FlavSF** [comment]
None of the debug steps worked, including the one you mention, at least for me it didn't.
