### ISSUE TITLE
Atom is installed but not launching !!! I mean it's not starting but has shown up in the task manager !??!! Strnge

### ISSUE THREAD

**Issue by arixank** [atom/atom#21024]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1.  Tried to run as administrator (on windows) !!
2.  Hunted the installed location and then ran it , but invain
3.  Also reinstalled freshly and restarted the system !!

**Expected behavior:** Start normally 

**Actual behavior:** Not even starting , but there is an entry in task manager !!

**Reproduces how often:** Everytime !!

**Comment by arixank** [comment]
My current atom ver 1.48

**Comment by arixank** [comment]
It seems that atom has ran into background process rather than ... being able to run directly !! I'm just not getting it to run on my system and even during the installation splash screen , after it installs it just vanishes away and nothing much !! In the task magaer it says updating rather than installing , why ??

**Comment by WindowsExperiments2020** [comment]
My tip would be to compile atom from source if it's "updating".

https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#platform-windows

**Comment by eelstork** [comment]
Have you plugged your laptop into an external display recently? I see this kind of effect when I do that (on Windows)
