### ISSUE TITLE
Uncaught TypeError: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by iseeface** [atom/atom#21052]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type object

```
At internal/validators.js:105

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:105:11)
    at Object.join (path.js:372:7)
    at MoveDialog.onConfirm (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:2638596)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:14:3159620)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:349786)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:1242246)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:1238380)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:284835)
```

### Commands

```
     -3:06.3.0 core:cancel (input.hidden-input)
     -2:47.6.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -2:43.1.0 core:confirm (input.hidden-input)
     -2:38.8.0 tree-view:add-file (div.header.list-item)
     -2:33.9.0 core:confirm (input.hidden-input)
     -1:59.9.0 core:save (input.hidden-input)
     -1:38.7.0 script:run (input.hidden-input)
     -1:28.1.0 fuzzy-finder:toggle-git-status-finder (ul.list-inline.tab-bar.inset-panel)
     -1:25.1.0 script:run (input.hidden-input)
     -1:01.2.0 core:paste (input.hidden-input)
     -0:58.1.0 script:run (input.hidden-input)
     -0:40.8.0 core:backspace (input.hidden-input)
     -0:26.1.0 script:run (input.hidden-input)
     -0:12.1.0 tree-view:move (div.header.list-item)
     -0:08.1.0 core:confirm (input.hidden-input)
     -0:06.4.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.9.7 
build-python 0.12.1 
ide-python 1.5.0 
script 3.26.0 
```

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by TheSkepticalOwl** [comment]
I encountered this error while trying to create or rename files on an external drive in the root folder.
1. Open second drive partition in atom
2. Create new file
3. It will show the path as `D:Filename` instead of `D:\Filename`

Fixing this will improve user experience. You have to manually add the \ by hand instead of it being there.

**Comment by shaunstearns** [comment]
> I encountered this error while trying to create or rename files on an external drive in the root folder.
> 
> 1. Open second drive partition in atom
> 2. Create new file
> 3. It will show the path as `D:Filename` instead of `D:\Filename`
> 
> Fixing this will improve user experience. You have to manually add the \ by hand instead of it being there.

Thanks for the fix! That was SUPER ANNOYING, especially as a new user you start to think "WOW! I can't even figure out how to rename my file!"
