### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/ same folder).jsx'

### ISSUE THREAD

**Issue by spaciousmind** [atom/atom#21069]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.13.6
**Thrown From**: Atom Core

trying to drag .jsx from one folder to another , not sure why this is happening.

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/ same folder).jsx'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat '/ same folder).jsx'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:943663)
    at TreeView.onDrop (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:950592)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:924223)
```

### Commands

```
     -1:30 tree-view:move (span.name.icon.icon-file-directory)
     -1:23.2.0 core:confirm (input.hidden-input)
     -1:15.1.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -1:06.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
adobe-script-runner 0.1.3 
autohide-tree-view 0.25.1 
bracket-colorizer 1.4.0 
fancy-bracket-matcher 2.1.0 
language-applescript 0.3.0 
nms-color-bracket 0.1.0 
open-unsupported-files 1.0.20 
pandoc-convert 1.1.1 
rainbow-csv 1.4.0 
run-in-indesign 0.1.2 
set-syntax 0.4.0 
tabular 0.1.0 
termination 0.7.6 
tree-view-autoresize 2.3.0 
tree-view-filter 0.5.5 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
