### ISSUE TITLE
Cant open Atom all of a sudden (screenshot attached)

### ISSUE THREAD

**Issue by Raghav-byte** [atom/atom#21073]
![atom](https://user-images.githubusercontent.com/55020567/87470604-a3661300-c63a-11ea-931a-afe4bd1bcd21.png)

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1.  Opening Atom
2. 
3. 

**Expected behavior:**

To open  Atom editor

**Actual behavior:**

Opening in chrome i think..showing some error

**Reproduces how often:**

 Everytime

### Versions

atom 1.49.0, Windows 10  ,10.0.19041 N/A Build 19041

**Comment by Raghav-byte** [comment]
Screenshot after Running atom --test in cmd

![image](https://user-images.githubusercontent.com/55020567/87471021-4d459f80-c63b-11ea-9966-e8259f264022.png)

**Comment by darangi** [comment]
what happened when you executed `atom --safe` ?

**Comment by Thierryonre** [comment]
> what happened when you executed `atom --safe` ?

He did use `atom --safe` in the picture but it didn't do anything.

**Comment by Raghav-byte** [comment]
> what happened when you executed `atom --safe` ?

No response sir , see the screenshot it is executed above the atom--test

**Comment by Raghav-byte** [comment]
I tried reinstalling ...but in vain

**Comment by darangi** [comment]
Okay, can you share a proper screenshot of the atom console? 

I tried reproducing this on windows 10 but I couldn't.

**Comment by Raghav-byte** [comment]
This is the atom console whenever i'm double clicking atom.exe !
![image](https://user-images.githubusercontent.com/55020567/87688216-569e4b80-c7a4-11ea-91dd-3c467a335787.png)

**Comment by Aerijo** [comment]
@Raghav-byte Yes, but you can see that the error is cut off. You can resize the console by making its pane bigger, or open the dedicated Console tab (at the top) to show the whole error.

**Comment by Raghav-byte** [comment]
Thanks for explaining @Aerijo  ..
![image](https://user-images.githubusercontent.com/55020567/87693684-e3e49e80-c7aa-11ea-8ca9-c2f4714dde43.png)

**Comment by darangi** [comment]
@Raghav-byte this is still not sufficient 😅 , can you resize the console, scroll to the top and take a screenshot? This way we can see the full error that was thrown.

**Comment by Raghav-byte** [comment]
![image](https://user-images.githubusercontent.com/55020567/87876254-7461ef80-c9f4-11ea-9177-3eebd77b12c6.png)

**Comment by Aerijo** [comment]
@Raghav-byte Thanks, that helps a lot.

It looks like permissions on the compile cache have been messed up. Deleting `~/.atom/compile-cache` should fix it. Atom will automatically regenerate it.

**Comment by Aerijo** [comment]
The `~` refers to your home folder. `C:\Users\shukl` in your case. You may need to enable showing hidden files to see the `.atom` folder in there, or you can try navigating to `~\.atom` directly.

**Comment by Raghav-byte** [comment]
Okay thanks !!
