### ISSUE TITLE
Unable to install any package

### ISSUE THREAD

**Issue by gmuder** [atom/atom#21100]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
 * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
 * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
 * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
 * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
 * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

With a fresh install, I am unable to search for any package.

### Steps to Reproduce

1. After a fresh install of the latest version running on Ubuntu
2. Open the Install Package view and start typing any package name. It should show a red message below the search field.

**Expected behavior:**

A list of available packages to appear

**Actual behavior:**

![image](https://user-images.githubusercontent.com/53446352/88286429-1c164080-ccc7-11ea-8134-09e9985f7f74.png)

**Reproduces how often:**

100% of the time it fails

### Versions

Atom:
```
Atom    : 1.49.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
```
APM:
```
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.49.0
python 2.7.18rc1
git 2.25.1
```
OS:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by UziTech** [comment]
looks like this is because https://atom.io/api/packages/search returns "Application Error"

**Comment by UziTech** [comment]
for a temporary fix running `apm install {package name}` in a terminal still works

**Comment by UziTech** [comment]
More debugging info:

Search view trys to search atom.io with the query: 
`https://atom.io/api/packages/search?q={query}&filter=package`

but it always responds with `{"message":"Application error"}`

@atom @darangi This seems like an important issue with atom.io

**Comment by darangi** [comment]
Thanks for reporting this issue, We are currently looking into this. @UziTech, Did this also happen on a Linux machine?

**Comment by UziTech** [comment]
I am on windows

**Comment by darangi** [comment]
Thanks 🙇‍♂️  @UziTech @gmuder.

**Comment by karthanistyr** [comment]
it's happening to me, on linux

**Comment by UziTech** [comment]
This isn't an issue with Atom but with atom.io.

**Comment by UziTech** [comment]
I created an issue on the atom.io repo in case that reaches other people

https://github.com/atom/atom.io/issues/203

**Comment by UziTech** [comment]
This seems to be fixed now :tada:
