### ISSUE TITLE
Not able to import Packages

### ISSUE THREAD

**Issue by Amazeryogo** [atom/atom#21107]
### The packages

I tried to install the following packages

1. Terminal by Atom 
2. emojiblast by emojicode

**Expected behaviour:**

Should have installed

**Actual behaviour:**

It does not install, even when I try multiple times

**Reproduces how often:**

Always

### Versions

Atom version :- 1.49.0
OS - macOS 10.5.6

### Additional Information

So, It does show that it is installing but stops in between the installation, and does not report any issue

**Comment by aminya** [comment]
Some of the packages are old and are not installed. Atom should tag them as incompatible. 

Use this if you need a terminal.
https://atom.io/packages/x-terminal

**Comment by Amazeryogo** [comment]
@aminya  Thanks, I'll try the x-terminal

**Comment by VijayBhaskar-G** [comment]
Can somebody help me fixing this . i don't know what's wrong . i want to install live-server package 
![image](https://user-images.githubusercontent.com/63191325/88792309-a7f10680-d1b8-11ea-9994-2744f7141b05.png)

**Comment by aminya** [comment]
Try `apm install atom-live-server`

**Comment by VijayBhaskar-G** [comment]
> Try `apm install atom-live-server`

Tqq for responding. I just Re-installed Atom 😅 issue solved
