### ISSUE TITLE
API Documentation for Atom IDE

### ISSUE THREAD

**Issue by ZiQiLN** [atom/atom#21101]
## Summary

`atom-ide` official API documentation, is somewhere it's available or should I read code and figure how to do things?

## Motivation

I'm actually forking `ide-yaml` package to make it usable for people that write YAML (mainly DevOps things) to implement important features such as autocomplete. https://github.com/ZiQiLN/ide-yaml/issues/1

**Comment by aminya** [comment]
atom-ide API is available in https://github.com/atom-ide-community/atom-ide-base.

**Comment by sadick254** [comment]
Closing this issue as it seems resolved. Let me know if there is any action expected from the atom team.
