### ISSUE TITLE
Settings/Install packages search throwing filter error.

### ISSUE THREAD

**Issue by mmestas** [atom/atom#21105]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Since this last update, cannot install Packages via the Settings/Install page

### Steps to Reproduce
1. Go to settings and click on Install
2. Search for a package

**Expected behavior:**
1. A list of available packages should show up

**Actual behavior:**
1.  I get an error with this message `Searching for “t” failed.Hide output…
i.filter is not a function...`

**Reproduces how often:**
1. Reproduces every time

### Versions
1.49.0

### Additional Information
I noticed this when I upgraded to the latest version of Atom, and my typescript editor no longer showed any syntax coloration.  I thought it might be because the package was out of date, or that I needed a new package, or even possibly a setting got erased.  When I tried searching for packages, I kept getting this error.  
In a way - there are two bugs that are happening here.... the typescript package no longer works and one cannot install a package via the Settings/Install tab.

**Comment by darangi** [comment]
Hi @mmestas , this issue was resolved yesterday, I just re-confirmed it on atom version 1.49. 

If it still persists on your end, feel free to re-open this issue.

**Comment by warren625968** [comment]
Thank you it worked

**Comment by mmestas** [comment]
I'm still having issues with .ts files being detected as typescript... that was the second part of the issue

**Comment by darangi** [comment]
> I'm still having issues with .ts files being detected as typescript... that was the second part of the issue

Do you mean `.ts` files are not detected as typescript files? 

Kindly open a new issue with a description of the issue you are facing

**Comment by blueedgetechno** [comment]
I'm facing the same

**Comment by ee-** [comment]
I can confirm the issue still exist on a fresh install just now. 

```
Searching for “xxx” failed.Hide output…
i.filter is not a function
[object Object]
```

**Comment by MrLivixx** [comment]
> Hi @mmestas , this issue was resolved yesterday, I just re-confirmed it on atom version 1.49.
> 
> If it still persists on your end, feel free to re-open this issue.

@darangi I also have this problem, OS: ubuntu 20.04. Atom Version 1.49.0.
![image](https://user-images.githubusercontent.com/54632865/89525743-574c5f80-d7ef-11ea-9d7c-dac6aaac17f0.png)
![image](https://user-images.githubusercontent.com/54632865/89525786-69c69900-d7ef-11ea-9f34-3f6e73915040.png)

**Comment by alehaa** [comment]
I'm having the same problem on Windows 10 / macOS Catalina with atom 1.49 and nightly 1.51.

**Comment by mmestas** [comment]
It seems to be a problem with the Tree Sitter Parser.  If I disable it, the .ts files read as plain text and not typescript.  If I enable it, the HTML closing tags indent incorrectly.
