### ISSUE TITLE
Trigger global search with scrolling up at the top of project tab.

### ISSUE THREAD

**Issue by davidlinhl** [atom/atom#21126]
I am recently taking notes with markdown in atom and have to use the project search function quite frequently. When I was using Typora, scrolling up when u are already at the top of the Files tab will trigger the project search function. Like shown below.
![image](https://user-images.githubusercontent.com/29757093/88808926-0ed8e480-d1e6-11ea-9e2f-18006864079d.png)
I am wondering is it possible to add this feature to atom. Currently scrolling up in the project tab wont't trigger anything, so there seems to be no conflict with existing features. This should be quite convenient when user need to use project search quite often.

**Comment by CyborgSemon** [comment]
There is already a keyboard shortcut you can use which has the same feature. Cmd (Ctl if on windows) + Shift + F will open "find in project" which should do what you are wanting. Its a really handy shortcut to know.

**Comment by UziTech** [comment]
or <kbd>Cmd/Ctrl + p</kbd> to open search by file name.

**Comment by davidlinhl** [comment]
This is really convent, I didn't realize there is keyboard shortcuts for this. Many thanks. But still, I think that scrolling up feature may be considered. It should be quite intuitive.
I am closing this.
