### ISSUE TITLE
I can' t install Live-server package 

### ISSUE THREAD

**Issue by VijayBhaskar-G** [atom/atom#21123]
I've tried many times . it shows an error that I cannot understand . please help me or guide me to fix this 
![image](https://user-images.githubusercontent.com/63191325/88792554-05855300-d1b9-11ea-8c8e-1bb813782c1d.png)

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by darangi** [comment]
Hi @VijayBhaskar-G, `atom-live-server` is not a project maintained by the atom team. However, you can open this issue on [atom-live-server repo](https://github.com/jas-chen/atom-live-server). Thanks!
