### ISSUE TITLE
Opening files in new tabs

### ISSUE THREAD

**Issue by ARTech-7** [atom/atom#21130]
When opening files, they close the current tab and open there, but I wanted to open some files in a new tab. When I right click the file, I can only open in a new window. Dragging the file to the tab bar also doesn't work.

I was forced to open everything in different windows. So, please, add a feature to open files in new tabs, or if I'm wrong and there is a way already, please tell me.

**Comment by UziTech** [comment]
Go to Settings > Core > __uncheck__ Allow Pending Pane Items

![image](https://user-images.githubusercontent.com/97994/88887245-a26bde80-d201-11ea-9201-63b2c81b7afc.png)

**Comment by ARTech-7** [comment]
Worked for me :D

**Comment by kogiokka** [comment]
@ARTech-7 The original behavior is single-clicking to preview (hence being replaced), and double-clicking to edit.
