### ISSUE TITLE
Atom coding style

### ISSUE THREAD

**Issue by kogiokka** [atom/atom#21132]
The styleguide in [CONTRIBUTING.md](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) states that "All JavaScript must adhere to [JavaScript Standard Style](https://standardjs.com/)", but it seems like Atom's source code does not actually follow this rule. For example, running `npx standard src/main-process/atom-window.js` shows lots of messages about "Extra semicolon" and "Missing space ...".

Has Atom adapted  another coding style? If so, what formatting or linting tools should be used? CONTRIBUTING.md should be updated correspondingly, maybe even suggesting some Atom extensions for new comers to develop Atom itself.

**Comment by Aerijo** [comment]
Atom [uses Prettier](https://github.com/atom/atom/pull/19391).

You'll probably want to install [`prettier-atom`](https://atom.io/packages/prettier-atom) to fix anything automatically for you. Or just run `script/lint --fix` before making a PR. And yes, the CONTRIBUTING.md file should be updated.

**Comment by jeff-hykin** [comment]
is the new style pretty much defined by the `stylelint.config.js`? @Aerijo

**Comment by Aerijo** [comment]
I don't know, I just remembered that PR and run `script/lint --fix` if the CI has a lint error.

**Comment by jeff-hykin** [comment]
okay thanks.
```
{
  "singleQuote": true
}
```
isn't much of a formatter config haha, but I guess the default values of everything else can be used
