### ISSUE TITLE
Git Repository using Atom

### ISSUE THREAD

**Issue by VijayBhaskar-G** [atom/atom#21146]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I can't create a repository using Atom. when i try to create one it says loading ... can somebody tell me if its my fault or error. 
### Steps to Reproduce
![image](https://user-images.githubusercontent.com/63191325/89281807-3f969f00-d668-11ea-89b5-0f91d66b9d54.png)

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by sadick254** [comment]
Hey @VijayBhaskar-G did you try login into github from atom? If yes did you paste the token generated into the github package in atom?
Which version of atom are you using?

**Comment by VijayBhaskar-G** [comment]
> Hey @VijayBhaskar-G did you try loging into github from atom? If yes did you paste the token generated into the github package in atom?
> Which version of atom are you using?

Thanks for Responding.. I can't see any Token Generated while creating A Repository . Can you briefly explain me please .. I can't find relevant Info in YouTube too ..

**Comment by VijayBhaskar-G** [comment]
> Hey @VijayBhaskar-G did you try loging into github from atom? If yes did you paste the token generated into the github package in atom?
> Which version of atom are you using?

Thanks for responding . I didn't logged into it. Now working fine...
