### ISSUE TITLE
Settings/Install packages search throwing filter error. Atom1.49 on Windows - 06Aug2020

### ISSUE THREAD

**Issue by mdmasih2k2** [atom/atom#21155]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by mdmasih2k2** [comment]
Description
Fresh Install on Windows 10 - Atom 1.49 today and unable to install packages give i.filter error
Steps to Reproduce
Go to settings and click on Install
Search for a package
Expected behavior:

A list of available packages should show up
Actual behavior:

I get an error with this message Searching for “t” failed.Hide output… i.filter is not a function...
Reproduces how often:

Reproduces every time
Versions
1.49.0

Additional Information
I read the previous ticket which said this issue is now resolved but its not. I am getting this error on fresh install of Atom which I did today.

**Comment by ryanolsonx** [comment]
One note - apm install still works. I'm seeing this too on Mac.

**Comment by bjascob** [comment]
I just installed Atom 1.49.0x64 on a fresh install of Ubuntu 20.04.1 and have the same issue. 
I used the .deb downloaded today.
Edit/Preferences/Install/<type work in search box> produces...
```
"Searching For "language" failed.
i.filter is not a function
```
I continually get these errors so I can't install any packages.

**Comment by UziTech** [comment]
The is an issue with atom.io that seems to keep happening. https://github.com/atom/atom.io/issues/203

**Comment by argos44** [comment]
just light up a neutronhash :)

**Comment by sadick254** [comment]
This issue has now been resolved. You can search and install packages normally without errors.

**Comment by zhanghan177** [comment]
I'm having the same issue in version 1.50.0

**Comment by argos44** [comment]
Hi Han, I'm not sure how could I help... could you please send more info?
