### ISSUE TITLE
Unable to run Atom locally after a local build on Mac OS X

### ISSUE THREAD

**Issue by funmu** [atom/atom#21166]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
Today is my first day with Atom. Instead of downloading and installing, I took the choice to build and run.
I used instructions at: [Hacking on Atom Core](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/)

I am trying this on Mac OS X with following versions for software
```
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G73
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom unknown
python 3.8.1
git 2.24.3
```
The Software build using *script/bootstrap* completed fine with checkmark for installing modules
```
$script/bootstrap
... 
Installing modules ✓
```

However I am unable to run the Atom after the build is complete. I get following errors
```
~/atom % atom --dev
zsh: command not found: atom
The application /Applications cannot be opened because its executable is missing.
~/atom % ./atom.sh
The application /Applications cannot be opened because its executable is missing.
~/atom % ./atom.sh --dev
The application /Applications cannot be opened because its executable is missing.
```

It seems that the entire Atom is not set up to run.
I had already set up to point to where I had cloned Atom at.

### Steps to Reproduce

1. 
Fresh clone of Atom on a Mac OS X machine that had no prior installation of Atom

2. 
*script/bootstrap*  to build and install modules

3. 
Try to launch *atom* and notice that it fails to even find the application

**Expected behavior:**
Freshly built atom works

**Actual behavior:**
Atom app is not found

**Reproduces how often:**
I had tried 4 times to build and install to run. None of the times have I seen success.

100%

### Versions

I cannot get version number since apm and atom are not functional

### Additional Information

I am a newbie to Atom. I wonder if I missed setting up some environment variables.
Is Atom even expected to run with just a fresh build vs. having a prior install of Atom?

**Comment by jeff-hykin** [comment]
atom --dev only works if you already have atom

Try running the `script/build` to build your own version. Beware there's probably going to be some errors (which I have yet to solve fully solve myself)

**Comment by funmu** [comment]
Yes

I already had done a build locally. But still I didn’t not find arom installed to run.

The web page doesn’t tell me how to run what might have been built

Thanks
- Murali

**Comment by jeff-hykin** [comment]
What happens if you do `script/build --compress-artifacts`?

**Comment by funmu** [comment]
Thanks Jeff for your inputs. I tried this.

Now I am running into other Errors in the node_module preparation.

```
Node:	v12.18.3
Npm:	v6.14.4
Python:	v3.8.1
Installing script dependencies
Installing apm
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom unknown
python 3.8.1
git 2.24.3
Installing modules ✓
Wrote Dependencies Fingerprint: /Users/murali/src/externals/atom/node_modules/.dependencies-fingerprint 952c4901b8fd1572ca0c74f8fec560cf084a4463
Cleaning /Users/murali/src/externals/atom/out
Copying assets to /Users/murali/src/externals/atom/out/app
Transpiling packages with custom transpiler configurations in /Users/murali/src/externals/atom/out/app
 transpiling for package github
Installing modules ✓
internal/modules/cjs/loader.js:490
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
  ^

[Error [ERR_PACKAGE_PATH_NOT_EXPORTED] [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/murali/src/externals/atom/out/app/node_modules/github/node_modules/@babel/helper-compilation-targets/package.json
```

The above seems to be an issue with node/npm. 
as per instructions on Error issues at https://github.com/nodejs/help/issues/1846 
I am trying out the following steps

> rm -rf node_modules
> npm install -g npm@latest
> npm i core-util-is

This has been failing in error compiling @atom/watcher
`
@atom/watcher@1.3.1 install: `prebuild-install || node-gyp rebuild`
` 

Still has not solved it. Nor do I want to just install atom directly and have this issue vanish. It is useful to find the root cause and fix it including updating atom documents for future use.
Thanks again for your help.

**Comment by michaellass** [comment]
Regarding that issue, see https://github.com/atom/atom/issues/21091.

**Comment by sadick254** [comment]
You can take a look at https://github.com/atom/atom/issues/21009#issuecomment-671529339

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* User Documentation &mdash; [The Atom Flight Manual](http://flight-manual.atom.io)
* Developer Documentation &mdash; [Atom API Documentation](https://atom.io/docs/api/latest)
* FAQ &mdash; [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* Message Board &mdash; [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* Chat &mdash; [Join the Atom Slack team](https://discuss.atom.io/t/join-us-on-slack/16638)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.
