### ISSUE TITLE
Can't use github commit feature

### ISSUE THREAD

**Issue by pranavwani** [atom/atom#21163]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * [x] Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. Stage files
2. Add commit message
3. Click on `Commit to`

**Expected behavior:**

Allow committing.

**Actual behavior:**

Permission issue

**Reproduces how often:**

100%

### Versions

1.49.0

**Note:** Also checked in 1.50.0-beta0 not work.

Working in `v1.46.0`, ext.: `.deb`

**Comment by sadick254** [comment]
Thanks for contributing!
Am unable to reproduce the bug. You might need to clarify the steps to reproduce.
What I have done within the git tab
- Staged files 
- Commit to `master`

**Comment by pranavwani** [comment]
Sorry @sadick254 for not mentioning detailed info

**Steps to reproduce**
1. Stage files
2. Add commit message
3. Click on Commit to

**Atom**
- version: `1.49.0`
- File type: `snap`
- Installed from: `software center`

**System**
- Ubuntu 20.04.1 LTS

**Screen shot**
![Screenshot from 2020-08-09 16-27-07](https://user-images.githubusercontent.com/26399261/90086605-6f186c00-dd38-11ea-9a68-0c4de2c557f2.png)

**Comment by jeff-hykin** [comment]
It looks like it might be an installation issue. I don't think pseudo should be needed for some of those commands, although I'm not familiar with husky. 

Atom probably checked to make sure the commands existed, but not if they had been installed with the correct permissions.

**Comment by pranavwani** [comment]
Ya tried using different file types and versions.

Deb. v1.4.7, v1.4.9 still facing the same issue. Work in v1.4.6.

**Comment by pranavwani** [comment]
Tested in the latest `v1.50.0`. 
![Screenshot from 2020-08-14 09-42-15](https://user-images.githubusercontent.com/26399261/90213126-980d2f80-de12-11ea-8f50-1b13ef9b59d3.png)

**Comment by pranavwani** [comment]
Ya, it can use node and npm outside of Atom. Even in Atom `v1.46.0` is also worked.
![Screenshot from 2020-08-24 19-09-46](https://user-images.githubusercontent.com/26399261/91051266-7f382180-e63d-11ea-9ec4-754ed3c23a43.png)

**Comment by DeeDeeG** [comment]
Hmm. Well 1.47.0 included the Electron 5 update... That's a big change. But still, it's working for me with that.

I wonder what are the permissions for your `node` and `npm` installs?

Here's what I have:

```console
[user]@[host]:~$ which node
/home/[user]/path/to/bin/node
[user]@[host]:~$ ls -l /home/[user]/path/to/bin/node
-rwxr-xr-x 1 [user] [user] 73630496 Aug 22 22:09 /home/[user]/path/to/bin/node
[user]@[host]:~$ which npm
/home/[user]/path/to/bin/npm
[user]@[host]:~$ ls -l /home/[user]/path/to/bin/npm
lrwxrwxrwx 1 [user] [user] 38 Aug 23 09:55 /home/[user]/path/to/bin/npm -> ../lib/node_modules/npm/bin/npm-cli.js
[user]@[host]:~$ ls -l /home/[user]/path/to/lib/node_modules/npm/bin/npm-cli.js 
-rwxrwxr-x 1 [user] [user] 4706 Oct 26  1985 /home/[user]/path/to/lib/node_modules/npm/bin/npm-cli.js
```

I edited out my username and the path `node`/`npm` are installed to. But you can see the "owner" and "group" for each file is set to match my username. And there is some working combination of [read, write and execute permissions](https://www.tutorialspoint.com/unix/unix-file-permission.htm) for each program. Maybe this is different on your machine?

**Comment by pranavwani** [comment]
@DeeDeeG Thanks for guiding. Node was installed via snap version which does not have all permission. :+1: 
![Screenshot from 2020-08-24 22-25-23](https://user-images.githubusercontent.com/26399261/91073505-c97acc00-e658-11ea-9995-aaac2575d8df.png)

**Comment by DeeDeeG** [comment]
Yes, no problem. Enjoy using Atom! :atom:
