### ISSUE TITLE
Uncaught Error: Cannot call constructor on missing remote object 212

### ISSUE THREAD

**Issue by theMrln** [atom/atom#21160]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Cannot call constructor on missing remote object 212

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222

Error: Cannot call constructor on missing remote object 212
    at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
    at /Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:375:5
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:275:21)
    at EventEmitter.emit (events.js:194:13)
    at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:420:21)
    at WebContents.emit (events.js:194:13)

```

### Commands

```
     -8:10.9.0 auto-indent:apply (atom-pane.pane)
  2x -7:55.7.0 core:backspace (input.hidden-input)
     -7:45.5.0 latex:build (input.hidden-input)
 21x -5:46.5.0 core:backspace (input.hidden-input)
     -5:41.8.0 core:paste (input.hidden-input)
     -5:37.2.0 core:save (input.hidden-input)
     -5:30.3.0 terminal:open (input.hidden-input)
  2x -4:18.4.0 tree-view:remove (li.file.entry.list-item.selected)
     -0:29.5.0 latex:build (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-brackets-glow 0.6.0 
atom-html-preview 0.2.6 
atom-idle-autosave 0.3.0 
atom-live-server-plus 3.0.1 
atom-markdown-wrapper 5.2.2 
atom-tag-wrapper 0.2.0 
auto-indent 0.5.0 
autoclose-html-plus 0.27.2 
build 0.70.0 
build-latex 0.0.3 
busy-signal 2.0.1 
character-table 0.4.3 
document-outline 2.1.2 
emmet 2.4.3 
format-shell 2.2.1 
html-outliner 0.1.1 
ide-python 1.5.0 
language-latex 1.2.0 
latex 0.50.2 
markdown-image-paste 2.5.2 
markdown-preview-enhanced 0.18.5 
markdown-preview-plus 4.5.0 
markdown-writer 2.11.10 
pandoc-convert 1.1.1 
pdfjs-viewer 1.0.0 
rainbow-csv 1.4.0 
script-runner 2.5.0 
terminal-tab 0.6.0 
tool-bar 1.3.0 
tool-bar-markdown-writer 0.5.1 
wordcount 3.2.0 
zotero-citations 5.2.0 
```

**Comment by PK-Patomsiri** [comment]
> [Enter steps to reproduce:]
> 
> 
> 
> 1. ...
> 
> 2. ...
> 
> 
> 
> **Atom**: 1.49.0 x64
> 
> **Electron**: 5.0.13
> 
> **OS**: Mac OS X 10.15.6
> 
> **Thrown From**: Atom Core
> 
> 
> 
> 
> 
> ### Stack Trace
> 
> 
> 
> Uncaught Error: Cannot call constructor on missing remote object 212
> 
> 
> 
> ```
> 
> At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:222
> 
> 
> 
> Error: Cannot call constructor on missing remote object 212
> 
>     at throwRPCError (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:148:17)
> 
>     at /Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:375:5
> 
>     at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:275:21)
> 
>     at EventEmitter.emit (events.js:194:13)
> 
>     at WebContents.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:420:21)
> 
>     at WebContents.emit (events.js:194:13)
> 
> 
> 
> ```
> 
> 
> 
> ### Commands
> 
> 
> 
> ```
> 
>      -8:10.9.0 auto-indent:apply (atom-pane.pane)
> 
>   2x -7:55.7.0 core:backspace (input.hidden-input)
> 
>      -7:45.5.0 latex:build (input.hidden-input)
> 
>  21x -5:46.5.0 core:backspace (input.hidden-input)
> 
>      -5:41.8.0 core:paste (input.hidden-input)
> 
>      -5:37.2.0 core:save (input.hidden-input)
> 
>      -5:30.3.0 terminal:open (input.hidden-input)
> 
>   2x -4:18.4.0 tree-view:remove (li.file.entry.list-item.selected)
> 
>      -0:29.5.0 latex:build (div.tool-panel.tree-view)
> 
> ```
> 
> 
> 
> ### Non-Core Packages
> 
> 
> 
> ```
> 
> atom-beautify 0.33.4 
> 
> atom-brackets-glow 0.6.0 
> 
> atom-html-preview 0.2.6 
> 
> atom-idle-autosave 0.3.0 
> 
> atom-live-server-plus 3.0.1 
> 
> atom-markdown-wrapper 5.2.2 
> 
> atom-tag-wrapper 0.2.0 
> 
> auto-indent 0.5.0 
> 
> autoclose-html-plus 0.27.2 
> 
> build 0.70.0 
> 
> build-latex 0.0.3 
> 
> busy-signal 2.0.1 
> 
> character-table 0.4.3 
> 
> document-outline 2.1.2 
> 
> emmet 2.4.3 
> 
> format-shell 2.2.1 
> 
> html-outliner 0.1.1 
> 
> ide-python 1.5.0 
> 
> language-latex 1.2.0 
> 
> latex 0.50.2 
> 
> markdown-image-paste 2.5.2 
> 
> markdown-preview-enhanced 0.18.5 
> 
> markdown-preview-plus 4.5.0 
> 
> markdown-writer 2.11.10 
> 
> pandoc-convert 1.1.1 
> 
> pdfjs-viewer 1.0.0 
> 
> rainbow-csv 1.4.0 
> 
> script-runner 2.5.0 
> 
> terminal-tab 0.6.0 
> 
> tool-bar 1.3.0 
> 
> tool-bar-markdown-writer 0.5.1 
> 
> wordcount 3.2.0 
> 
> zotero-citations 5.2.0 
> 
> ```
> 
> 
> 
>

**Comment by sadick254** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
