### ISSUE TITLE
disk usage 98% in windows 10

### ISSUE THREAD

**Issue by rajesh210198** [atom/atom#21161]
[

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. open Atom
2. open  task manager, 
3. check the disk usage,

**Expected behavior:**

it should not use 98% disk, even i have man other works to do, not to use Atom only.

**Actual behavior:**

It always slow down my PC. i am using a 4GB RAM PC, but after using ATOM it looks 2GB RAM PC. Atom always took more than 2 minutes to open. It always works slowly, even there is great space in my C-drive. 

**Reproduces how often:**
It happens always , whenever i open Atom and try to use it. 

### Versions

Atom version - 1.49.0
windows 10 pro
version 1903
OS build - 18362.30

**Comment by sadick254** [comment]
Thank you @rajesh210198 for opening this issue. I hope you found @DeeDeeG 's comment helpful. Am going to close this for now because it doesn't seem like an issue specific to atom only. The high disk usage could happen also when you open other resource intensive apps.

**Comment by cmcintosh** [comment]
Please consider reopening this issue I am seeing this behavior on a Ubuntu Virtual Box workstation. The system has 64GB ram, the guest os has 16 GB ram dedicated to it. I do have firefox running while using Atom during web development, and can confirm that the high disk use is from Atom scanning project files. This typically happens at launch and can cause the guest OS and atom to become unresponsive to all input.

**Comment by Rajeshsharma01** [comment]
Sir,
ATOM has closed my issue also, and i suggest to Uninstall ATOM and use
VSCode instead of "slowing down" your work because of this ATOM.
Move on and switch to VSCode and code better.

Just because ATOM is open source, Nobody is here to help us out for this
issue as they have many bugs to debug in this software.

**Comment by voxelands** [comment]
I've got the same issue on Linux Mint 20.2. Running atom from the menu starts an app.asar process that is constantly reading the harddrive. It's constant and all over the place, even when atom is in the background not being used.

```
ps aux
user   14402 11.8  2.9 4792072 238264 ?      Sl   14:41   0:02 /usr/share/atom/atom --executed-from=/home/user --pid=14390

iotop
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                                                                                                                                      
  14480 be/4     user 1595.01 K/s    0.00 B/s  0.00 % 98.63 %  app.asar --node-integration --node-integration-in-worker --webview-tag ~5 --no-v8-untrusted-code-mitigations --shared-files=v8_snapshot_data:100

  14480 be/4     user    3.52 M/s    0.00 B/s  0.00 % 96.00 %  app.asar --node-integration --node-integration-in-worker --webview-tag ~5 --no-v8-untrusted-code-mitigations --shared-files=v8_snapshot_data:100

  14480 be/4     user   12.05 M/s    0.00 B/s  0.00 % 86.44 % app.asar --node-integration --node-integration-in-worker --webview-tag ~5 --no-v8-untrusted-code-mitigations --shared-files=v8_snapshot_data:100


```

It also started an rg process that hammered the drive, but that seems to have stopped now.
