### ISSUE TITLE
can't search for packages to install, same issue from #21155

### ISSUE THREAD

**Issue by zhanghan177** [atom/atom#21188]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Can't search and install new packages. Same issue from #21155, but the old one was supposed to be patched in 1.49.0. Currently, I'm having the same issue in 1.50.0

### Steps to Reproduce

1.  Go to Settings -> Install
2.  Search any package
3.  See the error

**Expected behavior:**

Show a list of package search results. 
**Actual behavior:**

Searching for “t” failed.Hide output…
i.filter is not a function
[object Object]
**Reproduces how often:**

Every time.

### Versions

1.50.0

### Additional Information

Same issue as explained in #21155

**Comment by sadick254** [comment]
Kindly confirm if it now works. This has been resolved.
