### ISSUE TITLE
Forces GPU on OSX for pre-2011 MBP

### ISSUE THREAD

**Issue by knutaldrin** [atom/atom#2120]
Running Atom on OSX forces the hardware GPU to be enabled, which significantly increases power usage. Should not be necessary for a text editor.

Google Chrome has the same problem, so it is probably related to something in Chromium, but it is still a bug IMO.

**Comment by mnquintana** [comment]
Since Atom now requires the GPU for editor rendering, this isn't really possible now. Closing.
