### ISSUE TITLE
[BETA] `apm-beta link` does not work to install packages from source

### ISSUE THREAD

**Issue by calebmeyer** [atom/atom#21202]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: not possible for this particular problem, as it relies on loading packages.
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * [Checked that your issue isn't already filed](https://github.com/atom/atom/issues?page=1&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+apm+link)
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
The usual means to install a package from source (for example if you're developing on it) is to clone the repository, `apm link` (or `apm link --dev`), and `apm install`. This doesn't work to install packages to atom-beta, at least on my and @t9md's macs. (see [conversation on slack](https://atomio.slack.com/archives/C044E54H0/p1597846765033300))

### Steps to Reproduce

1. Install atom beta from atom.io/beta
2. Open it, and install the shell tools from the menu
3. Close it, and open up your terminal of choice (iTerm2 for me)
4. `git clone https://github.com/thomaslindstrom/color-picker.git`
  note that this is just an example, you can use any package you like
5. `cd color-picker`
6. `apm-beta link`
7. `apm-beta install`
8. Re-open atom beta
9. Open settings > packages, and search for color-picker

**Expected behavior:**
The package is installed and I can configure its settings

**Actual behavior:**
The package shows the install button, does not work, and I cannot configure its settings

**Reproduces how often:**
100% of the time, as far as I can tell

### Versions
```
$ atom-beta --version
Atom    : 1.51.0-beta0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

$ apm-beta --version
apm  2.5.0
npm  6.14.5
node 10.20.1 x64
atom 1.51.0-beta0
python 3.8.1
git 2.27.0
```

### Additional Information
This isn't possible to test in safe mode, since it's based on installing and using a package, which safe mode disables.

**Comment by UziTech** [comment]
this is fixed by #21065

**Comment by UziTech** [comment]
the only work around is to downgrade to atom v1.50.0-beta-0

**Comment by calebmeyer** [comment]
Closing this in favor of the linked issue. Thanks for the incredibly quick turnaround time, @UziTech
