### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by gustavobertolino** [atom/atom#21222]
### Description

When I try to search some package in the search bar in the Settings, the search breaks and throws error

### Steps to Reproduce

1. open "Settings"
2. search for anything the in the search bar, for new packages
3. an error will be shown just below the search bar

**Expected behavior:**

After searching some package by any keyword in the search bar, there should be packages as the result

**Actual behavior:**

No result is shown and an error is thrown instead, just below the search bar.

**Reproduces how often:**

100% of the time after I start using today night.

### Versions
Atom    : 1.49.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
OS: Linux Ubuntu 18.04

#### Additional Information
![Screenshot from 2020-08-26 20-04-15](https://user-images.githubusercontent.com/25723294/91366340-dc68da00-e7d9-11ea-924d-8ffe126f3313.png)

**Comment by sadick254** [comment]
@gustavobertolino This has now been resolved. Please try again and let me know if it works for you now.
