### ISSUE TITLE
Cursor disappears after holding Alt key 

### ISSUE THREAD

**Issue by kaibioinfo** [atom/atom#2122]
When I hold the Alt key for a second (with the side-effect that the entries in the menu bar are showing up) the cursor disappears. This is really annoying for key-bindings where the alt key is involved.
The cursor appears again after pressing a mouse button.

My ubuntu version is 14.04, atom version is 5b7b350 (built from github master).

**Comment by PanderMusubi** [comment]
This is not a problem for me with atom 0.165.0-1~webupd8~0

**Comment by rafalcieslak** [comment]
I can confirm this issue is not limited to the use of the Alt key and/or Unity HUD.
I use a DE-wide shortcut keystroke (ctrl+`) for opening/hiding a full-screen terminal. When I use Atom and switch to that terminal with this keyboard shortcut, Atom looses focus and the cursor disappears. When I return to Atom by hiding the terminal with the same keystroke, Atom regains focus, and I can write text there, but the cursor never re-appears.
So it would indeed seem the problem is related to regaining focus rather than to the Alt key in particular.

**Comment by cmtonkinson** [comment]
@rafalcieslak same here, on Arch Linux (Atom `0.174.0`). I too use that shortcut for the drop down terminal and see the same problem. As @alexandernst indicated, on the face of it this seems related to #3622.

**Comment by vimes1984** [comment]
and for me on Ubuntu 14... It's weird Sublime used to do the same...

**Comment by syndbg** [comment]
@vimes1984 http://askubuntu.com/questions/8494/prevent-windows-from-stealing-focus 

The problem is loss of focus.

**Comment by vimes1984** [comment]
@syndbg GENIUS! thank you that fixed it for me:D on day 3 of atom and lovely it so far...

**Comment by syndbg** [comment]
@vimes1984 You're welcome! :)

**Comment by haikyuu** [comment]
@vimes1984 or @syndbg , could you please provide a step by step solution.

**Comment by vimes1984** [comment]
just got back to the editor and click anywhere and it drops the cursor back in.

**Comment by syndbg** [comment]
@haikyuu On Xubuntu and Xfce4 desktops, follow the instructions in my earlier post.

On non-Xfce4 though:

* Install Compiz and open it.
* Go to `General Options` -> `Focus & Raise Behaviour`
* Try increasing `Focus Prevention Level` to different values until it works.

If it still doesn't work, try your luck with Window Rules http://wiki.compiz.org/WindowMatching

**Comment by ptihiy** [comment]
It's really annoying... I tried all Focus Prevention Levels and it doesn't work at all... Just fixed Alt key thanks to Unity HUD solution, but other combinations are kicking out focus as well. I'm truly embarassed, just switched from Vim and was quite happy... But as it is "not an Atom bug but OS's" seems either I have to drop Ubuntu with all my settings or drop Atom. Though dropping Ubuntu is not bad solution, it requires time, so I have to drop Atom(.

**Comment by ptihiy** [comment]
It's really stupid that cursor disappears when window loses focus at all

**Comment by ptihiy** [comment]
Really 

    atom-text-editor::shadow .cursor {
      opacity: 1 !important;
    }

solves the issue

**Comment by syndbg** [comment]
@ptihiy Nice! PR that.

**Comment by haikyuu** [comment]
@ptihiy i tried your suggestion but it didn't work.
I changed it in `static/text-editor-shadow.less`, built atom from the modified source code .. but that didn't work.
Any thoughts?

**Comment by despairblue** [comment]
for me the installation of *block-cursor* fixed it, so I suppose doing any css animation (and possibly other css statements like @ptihiy ones) will prevent the cursor from disappearing.

@haikyuu just add it to your personal style sheet (`Open your stylesheet` from the command palette)

**Comment by haikyuu** [comment]
@despairblue thanks, i knew it would be there, i think i just wanted to build from source :)
*block-cursor* is a nice plugin, but it didn't solve the problem (i'm running on Ubuntu 12.04)

**Comment by ptihiy** [comment]
@haikyuu  I put it into styles.less (personal stylesheet), this should work.

**Comment by haikyuu** [comment]
thanks @ptihiy . The cursor does not blink at all now

**Comment by ptihiy** [comment]
Yes. However, I even like it more that style. But I think this can also be styled.

**Comment by ferdy-galema** [comment]
```
atom-text-editor::shadow .cursor {
  opacity: 1 !important;
}
```
Is a workaround that works with Mint 17. However does anyone have a *blinking* cursor solution?

**Comment by kolAflash** [comment]
Try this (in ~/.atom/styles.less):
```
atom-text-editor:not(.mini)::shadow .cursor {
  opacity: 1;
}
atom-text-editor:not(.mini)::shadow .blink-off .cursor {
  opacity: 0;
}
```
From: https://github.com/atom/atom/issues/3622#issuecomment-73421592

**Comment by itoshkov** [comment]
I'm on ubuntu 15.04.

For me this happens also when I press keys like open brace '(', quote '"', open curly brace '{' or even upper-case letter, like 'L' or 'N', when they are start of a word. It doesn't happen for lower-case letters nor for open bracket '['.

**Comment by Sebastian69** [comment]
@ghost Yes, you solved it for me! Thank you very much, mister.

**Comment by 50Wliu** [comment]
Is anyone still experiencing this problem on Atom 1.3.x?

**Comment by alexandernst** [comment]
It's fixed for me.

**Comment by itoshkov** [comment]
It's fixed for me as well

**Comment by 50Wliu** [comment]
Awesome!
