### ISSUE TITLE
Unable to search themes & packages in atom .

### ISSUE THREAD

**Issue by benihime91** [atom/atom#21233]
Hi ! 
I just downloaded atom . Whenever I try to search for a package or a theme  I keep getting this weird error:
```
Searching for “file icons” failed.Hide output…
i.filter is not a function
[object Object]
```
I got the above output while searching for `file-icons`.
Alternatively if i search for `Hydrogen` package this error pops up:
```
Searching for “hydrogen” failed.Hide output…
i.filter is not a function
[object Object]
```
But I can download the packages that are showed in the `Featured Packages` list and they seem to be running fine.
I am Atom version: 1.50.0 on macOs Catalina 10.15.5

**Comment by Variable-X** [comment]
I am getting the same issue on 1.50.0, Windows 10. I however am not using a fresh install and have been able to download packages in the past

**Comment by AhmedHalat** [comment]
Same here,
Currently unable to search Atom.io for packages. 
It gives 500 errors https://atom.io/packages/search?q=Package

**Comment by Micronetic** [comment]
Everything works for, fresh install of Atom, see screenshot.

![image](https://user-images.githubusercontent.com/57453593/91682936-75d61a00-eb53-11ea-9fbe-812c5c9340b5.png)

**Comment by Variable-X** [comment]
Yeah, it is working again now. I think maybe around 2 or 3 pm est for me yesterday.

**Comment by sadick254** [comment]
Thank you for confirming it now works.
