### ISSUE TITLE
The atom-x64-windows.zip last relase archive is corrupted

### ISSUE THREAD

**Issue by gb85150** [atom/atom#21265]
The atom-x64-windows.zip last relase archive is corrupted. I've tried to download 2 times but i always have error (corrupted archive) with my unpacker (7zip, windows, Winrar...) I am on a windows10 x64 build 2004. If anybody can check this zip, it may help to find the real problem. Thanks to anybody who take time for this issue.

**Comment by gb85150** [comment]
the microsoft error code output 0x80004005. I found this [https://support.microsoft.com/en-us/help/4028090/windows-fix-error-0x80004005] on the web but it seems to be not liked to the issue

**Comment by darangi** [comment]
Could you provide the link you downloaded it from?

**Comment by gb85150** [comment]
https://github.com/atom/atom/releases/download/v1.50.0/atom-x64-windows.zip It seem to be patched with the new realase.
