### ISSUE TITLE
HTML Syntax Highlighting not working until file is closed and opened

### ISSUE THREAD

**Issue by danzen** [atom/atom#21263]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

HTML syntax highlighting not working when adding code from snippets.  Have to close and open the file and then it highlights.

### Steps to Reproduce

1. save html code in snippet 
2. open a new file and save it as .html
3. start typing the snippet name and select the snippet 
4. see that the some highlighting is missing
5. close the page and open it up again
6. see that the highlighting is there

**Expected behavior:**

Highlighting would be there when the snippet is added.

**Actual behavior:**

Highlighting is not there - or at least some is missing.  Must open and close the file to see the highlighting.

![image](https://user-images.githubusercontent.com/380281/92309054-12dbed00-ef70-11ea-9c08-f33035c55e1c.png)

**Reproduces how often:**

All the time - although, depending on the snippet code it may be partially working - see this example.

![image](https://user-images.githubusercontent.com/380281/92309102-87af2700-ef70-11ea-8398-a7f0ecc71f32.png)

### Versions

Atom    : 1.50.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0

Win 10 version 2004

**Comment by danzen** [comment]
Hmmm... I just made a new page and pasted in the code (not even getting it from snippets) and it still did not have the coloring right.  This has been like this in my atom for about 4 months or so.  I always get code from the snippet but now I see it is not a snippet issue per se.

![image](https://user-images.githubusercontent.com/380281/92311218-30ff1880-ef83-11ea-8aa1-1e8d5fa9bad9.png)

**Comment by danzen** [comment]
Any news on this Atom folks? It has happened to all my students as well and it has been happening for about 5 months.  Do you need more examples or anything?   Atom 1.53.0 on Windows 10.

**Comment by jeffdlange** [comment]
Second this. For me, this is most common in `html.erb` files, though occasionally occurs in others I can't recall off the top of my head.

**Comment by ThatXliner** [comment]
Do you have tree sisters parsing on?

**Comment by danzen** [comment]
@ThatXliner - I think all that is default - did you mean tree-sitter?  I looked and can't find out how to find out.

**Comment by ThatXliner** [comment]
[Tree sisters][tree] parsing is an experimental incremental parsing system which is more performance than TextMate-style grammars. But I would turn it off because currently, it seems to degrade the quality of most grammars.

[tree]: https://github.com/tree-sitter/tree-sitter

**Comment by jeffdlange** [comment]
@ThatXliner Yes, I have tree-sitter turned on. 

I tried turning it off, but having it off causes me to lose some highlighting (for example, in Ruby, methods and variables are highlighted with tree-sitters on, but show up only as black with tree-sitters off)

**Comment by ThatXliner** [comment]
I just realized, this is probably a problem with Atom dark. Try switching your syntax theme to One Dark

**Comment by jeffdlange** [comment]
@ThatXliner I actually use `Atom Light` for UI Theme and `Base16 Tomorrow Light` for syntax theme. I'd be surprised if the UI theme affected the syntax though

Next time I see the issue I'll try changing to `One Light` and see what happens

**Comment by ThatXliner** [comment]
> @ThatXliner I actually use `Atom Light` for UI Theme and `Base16 Tomorrow Light` for syntax theme. I'd be surprised if the UI theme affected the syntax though
> 
> 
> 
> Next time I see the issue I'll try changing to `One Light` and see what happens

Hmm, what does Atom think your language is (I.e. does it say "html" when you open HTML)

**Comment by danzen** [comment]
![image](https://user-images.githubusercontent.com/380281/104796942-84327480-5788-11eb-9e6d-3e3970e9e401.png)
Nope - just went to one dark and did the same thing - check out the script tag syntax in the header.  Probably the advice would be to rebuild atom or whatever...

**Comment by danzen** [comment]
I close the file and open it again and the syntax is good.  But no matter how many times I save the file before closing it the syntax is bad.  I have to close it and open it again.  Happening in both atom dark and one dark.  I guess I should try light...
![image](https://user-images.githubusercontent.com/380281/104797019-01f68000-5789-11eb-9f8a-902d14b21896.png)

**Comment by danzen** [comment]
![image](https://user-images.githubusercontent.com/380281/104797033-2eaa9780-5789-11eb-9a21-47994cc5dce1.png)
![image](https://user-images.githubusercontent.com/380281/104797035-3c601d00-5789-11eb-806e-7a16fc570263.png)
same thing in atom light...

**Comment by euxx** [comment]
Just found tree-sitter bug has been fixed: https://github.com/atom/atom/issues/20884#issuecomment-762555395
> This has already been fixed in #21790. It is currently scheduled for release when v1.56 reaches Stable.

**Comment by danzen** [comment]
Good!  I am on Atom 1.54 so looking forward to it!

**Comment by darangi** [comment]
Closing this because https://github.com/atom/atom/issues/21263#issuecomment-766532823
