### ISSUE TITLE
Auto complete not working as expected

### ISSUE THREAD

**Issue by tiagorocha1979** [atom/atom#21277]
Hi,

I'm a beginner developer and I've been using Brackets. I've decided to try Atom and I love it, but the auto complete isn't working the same way Brackets does. Here's what's happening:
1 - When I type for example "marg", it only shows me "margin". No margin-left, margin-right, nothing. Just margin. In Brackets it shows me all the options that contain the text "marg".
Atom 2 - https://snipboard.io/cq354w.jpg
Brackets - https://snipboard.io/IsaimZ.jpg

2 - I have an external CSS file with a class called "btn" (from Bootstrap). When I type "btn" it not only **doesn't** show me that option (and all the other that Bootstrap has such as btn-danger, btn-primary, etc), but it shows me other options that contain those letters, isolated, which doesn't make sense:
Atom 2 - https://snipboard.io/WMofTJ.jpg
Brackets - https://snipboard.io/Jab0n7.jpg

I'm using the latest version: 1.50.0
Mac osx 10.13.6

I have the packages that seems to be necessary (https://snipboard.io/RzEI18.jpg), but it's not working...

Can someone give me a hand? Am I missing something?
I really like Atom's workflow, themes, etc. And it seems to be faster than Brackets, so I would really love it to work.

Thanks! :)

**Comment by ThatXliner** [comment]
First off, I think you should move this issue to Atom's [autocomplete-plus](https://github.com/atom/autocomplete-plus) package. Second, Atom's autocomplete is basically like [Jedi](https://github.com/davidhalter/jedi) for python. If you want more powerful autocomplete, look forward to [TabNine](https://www.tabnine.com/) or something..
