### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Documents\Privat\Fastlane\HTML CSS\Ud...

### ISSUE THREAD

**Issue by kaankg** [atom/atom#21283]
[Enter steps to reproduce:]

1. Deleted one File
2. ...

**Atom**: 1.50.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\kaang\Documents\Privat\Fastlane\HTML CSS\Udemy Course\Web Developement\HTML-Personal Site\inputs.html'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat 'C:\Users\kaang\Documents\Privat\Fastlane\HTML CSS\Udemy Course\Web Developement\HTML-Personal Site\inputs.html'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:969251)
    at TreeView.onDrop (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:976180)
    at HTMLDivElement.<anonymous> (~/AppData/Local/atom/app-1.50.0/resources/app/static/<embedded>:14:949811)
```

### Commands

```
     -9:50.9.0 core:select-all (input.hidden-input)
     -9:50.2.0 core:copy (input.hidden-input)
     -0:31.5.0 tree-view:remove (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
