### ISSUE TITLE
github Stuck on loading

### ISSUE THREAD

**Issue by jwalker5006** [atom/atom#21334]
### Description
Install fresh Atom 1.51.0 on Catalina 10.15.6. Cannot connect atom to github account

### Steps to Reproduce

1. Click GitHub bottom right
1. Click create new repository
1. Publish GitHub repository screen stuck on "loading" and never prompted to authenticate to GitHub
![image](https://user-images.githubusercontent.com/6217843/93477018-18b2c600-f8c0-11ea-9076-b64df59c9a1d.png)

**Expected behavior:**
I thought I would be prompted to authenticate to GitHub to connect the GitHub account to Atom. Once Atom knows what account to create or clone a repository too, I should be able to do so.

So a new user to Atom who wants to create a new repository will not be able to do so. Never prompted to create a GitHub authorization token. This is confusing to new users, at least put a message that says "There is no GitHub account authorized to work with Atom. Clone a repository to authorize Atom to use your GitHub account first. you may delete the cloned repository locally when completed, this is necessary to create a repository". that way end users know how to authorize GitHub. Of course a better option is to run the same methods as clone repository uses when attempting to clone a repository to connected github accounts with lenght zero or null. not sure how you do the check for a github account.

From what I can tell, the GitHub account drop down in create GitHub repository has no error catch for null github accounts so just sticks on "loading..."

**Actual behavior:**
No way to tell atom what github account to create a new repository in. Stuck on Loading...

So then I thought well maybe they didnt program anything in to allow the first action in atom to create a new GitHub repository and maybe if I clone a repository, I will get prompted to connect my github to Atom. 

So I click Clone repository and sure enough

**Reproduces how often:**
Every-time

### Versions
Atom 1.51.0 on Catalina 10.15.6.  on Mac running 1TB SSD
![image](https://user-images.githubusercontent.com/6217843/93477449-a2629380-f8c0-11ea-9116-b15c0161a104.png)

**Comment by 404-unf** [comment]
Happening with me too...
Manjaro 20.1
i5 7th gen
8GB Ram

**Comment by chrisossi1** [comment]
Also happening with me.
Windows 10 Home
Intel i7 4720hq
16GB RAM

**Comment by Quazz** [comment]
If you close your current project and then try to clone an existing repo, the login windows shows up properly, you can add the atom api key there and then it will be available in the dropdown. 

It is still a bit buggy, but seems to work.

**Comment by GeorgeAlexandruS** [comment]
I have the same issue, been trying to solve it for days. I think I will give up atom, to buggy. Any other IDE you recommend?

**Comment by GeorgeAlexandruS** [comment]
I have the same issue, been trying to solve it for days. I think I will give up atom, to buggy.

**Comment by a22a-dev** [comment]
@GeorgeAlexandruS try sublime text with Github Desktop application

**Comment by GeorgeAlexandruS** [comment]
> @GeorgeAlexandruS try sublime text with Github Desktop application

Got vs, works like a charm

**Comment by B21-USER** [comment]
any update on this ? it's frustrating for many and there are no official word on this yet.

**Comment by a22a-dev** [comment]
I guess they don't care enough to even acknowledge the issue.


On 10-Nov-2020 at 9:54 am, GitHub Training <notifications@github.com>
wrote:

any update on this ? it's frustrating for many and there are no official
word on this yet.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/atom/atom/issues/21334#issuecomment-724441402>, or
unsubscribe

**Comment by UziTech** [comment]
This issue should probably be on the https://github.com/atom/github repo

**Comment by brianbatesactual** [comment]
I used Github desktop to create the repo, then opened with Atom.  Once the first repo was published, the login process in Atom kicked into gear.

**Comment by doingdevice** [comment]
I am also experiencing this problem :(

**Comment by kevingao25** [comment]
I guess we have one more person having the problem now

**Comment by krissharm** [comment]
Same thing.... thought it was just me

**Comment by hirin-byte** [comment]
I have same thing

**Comment by ThatXliner** [comment]
I've had to resort to `gh repo create`. Also, I think this issue should be transferred to [atom/github](https://github.com/atom/github) 😐.

**Comment by nerrevar** [comment]
Reinitializing git repository will help
`git init`

**Comment by TRL242** [comment]
Same issue

**Comment by Gennadion** [comment]
Same issue

**Comment by xhemil7cb** [comment]
Same here

**Comment by ThatXliner** [comment]
Please don't reply with "same here" or "+1". It gives us emails for these minor notifications. Utilize reactions instead, please.

**Comment by woodRock** [comment]
I'm experiencing the same issue on Windows 10.

**Comment by epic-not-gamer321** [comment]
> Reinitializing git repository will help
> `git init`

i did that and i get atom core (1 deprecation)

Arguments to path.basename must be strings

Object.basename - /usr/share/atom/resources/app.asar/src/electron-shims.js:34:10
<unknown> - <embedded>:14:3121122
Function.simpleDispatch - <embedded>:11:1171250
Emitter.emit - <embedded>:11:1172691
TextBuffer.emitDidChangeTextEvent - <embedded>:11:505720
TextBuffer.transact - <embedded>:11:493805

**Comment by epic-not-gamer321** [comment]
I opened a new repo and switched the github to that and i gave me the login instructions

**Comment by jwalker5006** [comment]
Im closing this one up - seems UI is a little buggy but works with various tricks.
1. close  and reopen
2. git init
3. gh repo create
4.There is no GitHub account authorized to work with Atom. Clone a repository to authorize Atom to use your GitHub account first. you may delete the cloned repository locally when completed, this is necessary to create a repository".
