### ISSUE TITLE
issue in Atom dark UI syntax theme

### ISSUE THREAD

**Issue by nikita2905** [atom/atom#21357]
Atom is not coloring the syntax properly if one thing gets colored other thing turns grey and after I  have used UI dark syntax ,this thing is happening to me.

**Comment by sadick254** [comment]
Hi @nikita2905 Could you provide screenshots of what you are seeing. And steps to reproduce the behaviour. This will help us know where to start looking. Thank you in advance.

---
All new issues now require steps to reproduce (also called "repro steps") the problem or the behavior you wish to see in Atom. We do this so we can be certain that we are understanding what it is you're describing and don't prematurely close the issue or implement the wrong feature. If you need help writing detailed repro steps, please see the [How Can I Contribute? section of the Atom CONTRTIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
