### ISSUE TITLE
Atom stuck in dev mode

### ISSUE THREAD

**Issue by adammodley** [atom/atom#21352]
I am using Atom 1.51.0 and it has recently started launching in dev mode only. I am running on PC with Windows 10 (which had an update today - 19/09/20). The problem started after launching Visual Studio Code and toggling the dev tools in that. Afterwards, Atom would not launch in anything but dev mode. I have tried restarting and reinstalling but nothing seems to work. I'm sure there is an obvious answer but I am lost at this point. Would appreciate some help.

**Comment by adammodley** [comment]
Update: Launched the portable version of Atom to test that and this fixed the issue. Prior to this, I had an error message related to .atom\config\cson. I'm assuming that something changed in the config. I'm still in the dark so if someone could shed some light on the actual issue I would be really grateful!

**Comment by codeit13** [comment]
I also recently got into this issue. When I was opening Atom, it by default opened in dev mode. But then I went to the console from dev mode and found that there were some errors indicating some permission errors on Atom config files. I quickly gave the necessary permissions and it worked like a cham.

If it helps, I am on Linux (Elementary OS)

**Comment by adammodley** [comment]
> 
> 
> I also recently got into this issue. When I was opening Atom, it by default opened in dev mode. But then I went to the console from dev mode and found that there were some errors indicating some permission errors on Atom config files. I quickly gave the necessary permissions and it worked like a cham.
> 
> If it helps, I am on Linux (Elementary OS)

**Comment by adammodley** [comment]
Hey, @codeit13 thanks for the tip. I ended up solving it by opening the portable version of Atom on my memory stick and this seemed to do the trick. I will bear your advice in mind if it happens again - thanks :)
