### ISSUE TITLE
Revrite in as rust?

### ISSUE THREAD

**Issue by BrianKevinson** [atom/atom#21378]
Hello I think is worth considering. Add my name to the contribution.

**Comment by sadick254** [comment]
Hey @BrianKevinson  are you suggesting rewriting atom in rust?

**Comment by bjorn3** [comment]
This users has been creating similar issues for several other projects including the rust compiler itself (https://github.com/rust-lang/rust/issues/77137)

**Comment by sadick254** [comment]
@bjorn3 interesting. I didn't know that. I will close this issue for now @BrianKevinson
