### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Dropbox/Corruption/ corruption overvi...

### ISSUE THREAD

**Issue by karthiktadepalli1** [atom/atom#21407]
When copying a file (or just PDF?) from one folder to another, if the file has a comma in its name, copying fails and the below bug is created. For example, below the file was `banerjee et al, corruption overview.pdf` but it lists the name as `/ corruption overview.pdf`.

To reproduce, run the following in shell:

```
mkdir test1 
mkdir test2 
touch "test1/filename, with comma.pdf"
```
Then open the root directory in atom and try to drag and drop `filename, with comma.pdf` to `test2`. 

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Debian GNU/Linux
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/karthiktadepalli1/Dropbox/Corruption/ corruption overview.pdf'

```
At fs.js:122

Error: ENOENT: no such file or directory, lstat '/home/karthiktadepalli1/Dropbox/Corruption/ corruption overview.pdf'
    at Proxy.realpathSync (fs.js:1512:7)
    at Proxy.fs.realpathSync (electron/js2c/asar.js:300:40)
    at TreeView.moveEntry (/usr/share/atom/resources/app/static/<embedded>:14:943663)
    at TreeView.onDrop (/usr/share/atom/resources/app/static/<embedded>:14:950592)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:924223)
```

### Commands

```
     -0:37.2.0 tree-view:move (span.name.icon.icon-file-directory)
  3x -0:35.5.0 core:backspace (input.hidden-input)
     -0:27.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-latex 0.9.1 
busy-signal 2.0.1 
file-icons 2.1.42 
Hydrogen 2.14.4 
intentions 1.1.5 
language-stata 1.7.3 
linter 2.3.1 
linter-proselint 3.3.0 
linter-ui-default 1.8.1 
markdown-writer 2.11.10 
pdf-view 0.72.0 
pen-paper-coffee-syntax 0.17.0 
script 3.26.0 
smart-quotes-plus 3.0.1 
tablr 1.8.3 
wordcount 3.2.0 
Zen 0.18.0 
```

**Comment by sadick254** [comment]
Thanks for reporting this!

This has already been fixed on the `master` branch. It is currently scheduled for release when `v1.53` reaches Stable.
