### ISSUE TITLE
File changes do not save.

### ISSUE THREAD

**Issue by sandeep-tukaram** [atom/atom#21424]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
     Open a file in atom, make changes to it and save.
2. 
      Repeat couple of times.

**Expected behavior:**

     Every save should persist changes.

**Actual behavior:**

     Save doesn't persist changes. A blue dot on the file name tab is observed.

**Reproduces how often:**

     Intermittent but frequent, near about 100% of the time.
### Versions
Atom    : 1.51.0                                                                                                                                                                                                  Electron: 5.0.13                                                                                                                                                                                                   Chrome  : 73.0.3683.121                                                                                                                                                                                            Node    : 12.0.0

**Comment by darangi** [comment]
Hi @sandeep-tukaram, I currently can't reproduce this issue, could you try running atom in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode) and confirm if this issue exists?

**Comment by sandeep-tukaram** [comment]
@darangi tries safe mode. Could repro the issue. One observation - the issue is seen with java projects and not on python projects.

**Comment by darangi** [comment]
@sandeep-tukaram this [PR](https://github.com/atom/ide-java/pull/116) fixes the issue with java files. The fix should hit [nightly](https://atom.io/nightly) soon
