### ISSUE TITLE
Nullish Coalescing Operator (??)

### ISSUE THREAD

**Issue by Ephellon** [atom/atom#21443]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
        * Replacing all `??` with `||` does not suffice, and causes errors
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>
        * Close, but does weird highlighting on large files: <https://atom.io/packages/language-javascript-jsx>

### Description

Atom does not take `??` into account when highlighting/folding

### Steps to Reproduce

1. Use the JavaScript syntax highlighter
2. `Copy/Paste`
```javascript
// ...
// Notifications
NOTIFICATIONS = $('[data-test-selector="onsite-notifications-toast-manager"i] [data-test-selector^="onsite-notification-toast"i]', true).map(
    element => {
        let streamer = {
            live: true,
            href: $('a', false, element)?.href,
            icon: $('figure img', false, element)?.src,
            name: $('figure img', false, element)?.alt,
        };

        if(!defined(streamer.name))
            return;

        element.setAttribute('draggable', true);
        element.setAttribute('twitch-tools-streamer-data', JSON.stringify(streamer));
        element.ondragstart ??= event => {
            let { currentTarget } = event;

            event.dataTransfer.setData('application/twitch-tools-streamer', currentTarget.getAttribute('twitch-tools-streamer-data'));
            event.dataTransfer.dropEffect = 'move';
        };
    }
);
// ...
```
3. Attempt to fold *line 17* (it should be matched with *line 22* but isn't)

### Expected Behavior

1. The JavaScript syntax highlighter should distinguish between `??` ([Nullish Coalescing Operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)) and `? ...: ...`
2. The highlighter should also allow the correct code-folding for `??`

### Actual Behavior

1. The syntax highlighter ignores `??` and treats it as `? ...: ...`
2. Code-folding currently mismatches `{}` `[]` and `()` due to it thinking `??` &rArr; `? ...: ...`

**Reproduces how often:**

`100%`

### Versions

* Electron Version: `5.0.13`
* Chrome Version: `73.0.3683.121`
* Node Version: `v12.0.0`
* Operating System:  `Windows 10`
* Last known working version: **N/A**

### Screenshots

> ### Incorrect pair being matched (*line 17* &rarr; *line 23*)
> ![image](https://user-images.githubusercontent.com/8632548/95227581-82393c80-07bb-11eb-9e33-53040229f281.png)

> ### Correct pair being matched (*line 17* &larr; *line 22*)
> ![image](https://user-images.githubusercontent.com/8632548/95227047-de4f9100-07ba-11eb-9145-5d8b69aa0099.png)

**Comment by UziTech** [comment]
This should be an issue in the [language-javascript](https://github.com/atom/language-javascript) repo.

**Comment by Ephellon** [comment]
OK, moving issue
