### ISSUE TITLE
Open with atom

### ISSUE THREAD

**Issue by donno2048** [atom/atom#21445]
##  Summary

When I use "popular" editor (like VS Code, JetBrains', etc) I can right-click on a file in the Explorer and choose to edit with a specific editor ("Open with Code", "Edit with PyCharm", etc)

## Motivation

It is way easier to be able to edit code right within the Explorer, that way I can see only the code I want to see (not all the files in the directory)

**Comment by debajitdeb11** [comment]
Hey @donno2048 I think this [article](https://www.radishlogic.com/atom-text-editor/showing-open-with-atom-when-right-clicking-file-or-folder-in-windows-10/)  might help you
