### ISSUE TITLE
Consider mentioning Electron 6 in the release notes for Atom 52.0

### ISSUE THREAD

**Issue by DeeDeeG** [atom/atom#21454]
Hi folks,

[The release notes for Atom 52.0-beta0](1.52.0-beta0) currently don't mention [the Electron 6 upgrade](https://github.com/atom/atom/commit/1d263e26b3812915700d1b8d1b415a552757a0b6) (https://github.com/atom/atom/pull/21079). That's arguably the biggest change.

(Hopefully most users won't notice, as Atom still works the same aside from better performance or low-level bugfixes in Chromium/V8/Node, or something like that. But it's still a very notable change in my opinion! At least it is for developers and folks who follow Electron development.)

So this issue is just to ask if the maintainers will please consider adding that to the release notes. (I'm surprised it wasn't added automatically, but I see the Electron 6 take two PR has no "Release Notes" section, so maybe that's why.)

Very quick issue because I don't know where else to post this.

Thanks.

@darangi @sadick254

**Comment by darangi** [comment]
Thanks for pointing it out 🙇🏾‍♂️

**Comment by darangi** [comment]
I updated the [release notes](https://github.com/atom/atom/releases/tag/v1.52.0-beta0) 🎉   I will go ahead and close this. Feel  free to re-open this if something is missing 😃
