### ISSUE TITLE
Editor panel on top

### ISSUE THREAD

**Issue by alexwhitman** [atom/atom#2149]
Ubuntu 14.04, built from current `master`.  Im seeing an odd issue with the editor panel being always on top but the window decorations act correctly:

![atom](https://cloud.githubusercontent.com/assets/422013/2936361/fc236a1a-d857-11e3-9b51-5cba1529be6d.png)

**Comment by mnquintana** [comment]
Can't reproduce this on Ubuntu 14.04 / 14.10 with Atom 0.190.0. Feel free to reopen if you still experience this!
