### ISSUE TITLE
Atom 1.52 installation on Ubuntu 20.10 Groovy Gorilla

### ISSUE THREAD

**Issue by bittin** [atom/atom#21494]
Hello!

Tried installing the Atom 1.52 deb on my Ubuntu testing machine today 

But the .deb file is missing two dependencies gvfs-bin that i had to install manually from Debian SID: https://packages.debian.org/unstable/gvfs-bin and gconf-service that i had to install from the Ubuntu package archive before the latest version of Atom worked maybe you wanna package all dependcies in the .deb file in the future ?

**Comment by seb128** [comment]
gvfs-bin is an old outdated transitional package, Debian removed it in this upload and Ubuntu followed up
https://packages.qa.debian.org/g/gvfs/news/20200910T003354Z.html

the binary has been added back to make easier the GNOME 3.38 landing but it's going to be remove from Debian again

the modern equivalent is the 'gio' command from libglib2.0-bin

**Comment by darangi** [comment]
@bittin this [PR](https://github.com/atom/atom/pull/21425) fixes the issue with installation on ubuntu groovy, it is currently [available in beta](https://atom.io/beta). I will go ahead close this issue, feel free to re-open it if it still persists

**Comment by bittin** [comment]
Nope solved in the Beta version, thanks :)

**Comment by sslavic** [comment]
Thanks for fixing this, works for me on Pop!_OS 20.10.

Is schedule for Atom 1.53 GA release known?
