### ISSUE TITLE
Markdown preview is broken, only on first preview

### ISSUE THREAD

**Issue by xavierfoucrier** [atom/atom#21500]
### Description

When previewing a Markdown file, **the first preview** remains broken and display an error.

### Steps to Reproduce

1. Open Atom
2. Add a project folder
3. Double click on a Markdown file
4. `Ctrl`+`Shift`+`M` to preview the file

**Expected behavior:**

The Markdown should properly render inside the preview tab.

**Actual behavior:**

The Markdown preview tab display an error:
![md](https://user-images.githubusercontent.com/2471223/95962058-3105fa00-0e06-11eb-9bad-d665a651ced6.png)

> Closing the tab and `Ctrl`+`Shift`+`M` again fixes the error.

**Reproduces how often:**

Every time a Markdown file is previewed **for the first time**. When Atom remains open, it doesn't happen anymore.
I already had this problem in previous versions of Atom: it is probably introduced since version 1.5+.

### Versions

**Atom**
Atom: 1.52.0
Electron: 6.1.12
Chrome: 76.0.3809.146
Node: 12.4.0

**APM**
apm 2.5.2
npm 6.14.8
node 12.4.0 x64
atom 1.52.0
python
git 2.28.0.windows.1
visual studio 2015

### Additional Information

Windows 7 SP1 x64

**Comment by mrwolferinc** [comment]
Im gonna have to fix this.

**Comment by mrwolferinc** [comment]
Im gonna have to fix this. I will let you know when this is fixed.

**Comment by jjcaine** [comment]
@mrwolferinc Hey! 👋  Were you still working on a fix for this? Just let us know!

**Comment by xavierfoucrier** [comment]
Hi @sadick254,

I have seen that a month ago already :wink: 
Thanks for the fix! :sunglasses:
