### ISSUE TITLE
Force Push no longer works after Amending a Commit

### ISSUE THREAD

**Issue by gothicserpent** [atom/atom#21529]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode> (safe mode does not show the same github amend prompt for me)
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/> (done)
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq> (done)
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom> (done)
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages> (done)

### Description

When I staged an edited file, amended the latest commit, and attempted to force push like i always do in atom, it didn't work this time.

![image](https://user-images.githubusercontent.com/36061843/96360503-b58c9d00-10d2-11eb-8bde-ad45f0f52e7c.png)

I had to disable "Block command line pushes that expose my email" in github email settings (https://github.com/settings/emails) to get it to work, and then do `git push --force` in the commandline while i was in the repo directory to make this work.

### Steps to Reproduce

1. edit a file that has a connected repo to github in atom. There should be a mark for a change on the right panel.
2. stage the change
3. right click the latest commit and click amend

![image](https://user-images.githubusercontent.com/36061843/96359675-59be1600-10ca-11eb-96f4-c5a23ed1f5d5.png)

**Expected behavior:**

After a few moments, the change *SHOULD* force push and the repo should be changed.

**Actual behavior:**

No force push is executed, leaving the pull notification still visible.  (in the past, this would always change to 0 changes after a few moments when atom does the force push) .

I attached a screenshot of what I'm seeing now: 

![image](https://user-images.githubusercontent.com/36061843/96359689-896d1e00-10ca-11eb-9a74-b021bb374dee.png)

**Reproduces how often:**

This reproduces 100% of the time for me. 

### Versions

 Atom    : 1.52.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

Windows 10  
(10.0.19041 Build 10941)

### Additional Information

One note to remember here is that this WAS working just a week or two ago when I tried it.

Although this can be resolved by simply force pushing via command line, I would love to see this functionality brought back as I used it all the time. I use amend / force pushes since I'm the only person working on my private repo, and I don't need to make a new commit for small changes I make to my repo.

Please let me know if you have any questions, and I hope this helps! Thanks!

**Comment by UziTech** [comment]
This should probably be an issue in the https://github.com/atom/github repo
