### ISSUE TITLE
Atom no longer opens files using atom:// URLS

### ISSUE THREAD

**Issue by TristanBrotherton** [atom/atom#21569]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom no longer responds to atom:// URLS and the URI Handling tab does not report recent URIs.
Such as: `atom://core/open/file?filename=/Users/name/Documents/development/image-panel.less&line=228`

Where the path is either absolute, or relative and references a file in the current project.

### Steps to Reproduce

1. Create a url that references a file in your project such as: `atom://core/open/file?filename=/path/to/file.txt`
2. Paste that URI into chrome and press enter.
3. Atom will focus but not open the file.

**Expected behavior:**

Atom will open the file requested.

**Actual behavior:**

Atom focuses but the file does not open.

**Reproduces how often:**

100% of the time

### Versions

1.52.0
OSX Catalina 10.15.7 (19H2)

**Comment by darangi** [comment]
Currently can't reproduce this on `atom 1.52` `macOS Catalina 10.15.7`. Are you sure the file path is valid?

**Comment by TristanBrotherton** [comment]
I made a quick video demonstrating the issue with both full and relative paths:
http://myvr-dev-files.s3.amazonaws.com/tristansjunk/screencast_2020-10-28_12-34-46.mp4

**Comment by darangi** [comment]
Thanks for the video, this happens because you are using the project path not the full-path. Atom needs the fullpath to be able to locate the file.

**Comment by TristanBrotherton** [comment]
You should be able to see me showing the behaviour in that video for both the full, and the project path.

**Comment by TristanBrotherton** [comment]
Worth noting that some time ago Atom did support opening the URL given the project path ( i filed a separate issue for that) but it stopped working. I then had to change my plugin to support the full path, which also no longer works.

**Comment by UziTech** [comment]
It seems to work for the full path on Windows 10 but not the project path.

You could also try using the [open](https://atom.io/packages/open) package, which uses the textmate url scheme.

**Comment by TristanBrotherton** [comment]
@UziTech thanks for that lead, i'll try that plugin as a workaround.

**Comment by darangi** [comment]
> You should be able to see me showing the behaviour in that video for both the full, and the project path.

![image](https://user-images.githubusercontent.com/15386677/97491309-3fa1f480-1962-11eb-856d-23aafda32199.png)
the query for the full-path doesn't look right?  could you confirm this?

**Comment by TristanBrotherton** [comment]
@darangi you found the issue. We can close this, sorry for wasting your time. I can confirm that it does work when i correct that.
