### ISSUE TITLE
Atom 1.52 fails to open on RHEL 7.9

### ISSUE THREAD

**Issue by kengreenlee** [atom/atom#21576]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom UI fails to open

### Steps to Reproduce

1. Install Atom 1.52 on RHEL 7.9 with all current yum updates applied
2. Launch Atom either from Applications or command line
3. Atom UI fails to open
4. Downgrading Atom to 1.51 resolves the issue

**Expected behavior:**

Atom UI should open

**Actual behavior:**

Atom UI fails to open

**Reproduces how often:**

Every single time

### Versions

Atom 1.52 on RHEL 7.9

**Comment by pinacoelho** [comment]
Seems to be the same as #21497

**Comment by kengreenlee** [comment]
Closing as a dupe of #21497
