### ISSUE TITLE
Unable to show file in Explorer warning appears erroneously when right clicking a file in project tab to show in explorer

### ISSUE THREAD

**Issue by gothicserpent** [atom/atom#21577]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When I right click a file in the project explorer and click `Show in Explorer`, it opens in windows explorer, yet there is a UI warning issued saying `Unable to show` in a yellow warning box.

### Steps to Reproduce

1. right click a text file in the project window and click `Show in Explorer`

![image](https://user-images.githubusercontent.com/36061843/97045705-17159700-152b-11eb-9126-84280da143ed.png)

**Expected behavior:**

There should not be a warning if the command is successfully executed.

**Actual behavior:**

file opens in explorer: 

![image](https://user-images.githubusercontent.com/36061843/97045920-74a9e380-152b-11eb-8997-74452c2cf0e0.png)

but a warning still appears saying it cannot show:

![image](https://user-images.githubusercontent.com/36061843/97045866-652a9a80-152b-11eb-8960-746b3db1e662.png)

An erroneous warning appears.

**Reproduces how often:**

reproduces 100% of the time.

### Versions

Atom : 1.52.0
Electron: 6.1.12
Chrome : 76.0.3809.146
Node : 12.4.0

Windows 10
(10.0.19041 Build 10941)

### Additional Information

No additional information.

**Comment by wgstjf** [comment]
Experiencing the same issue here too.  Win 10 Pro (1909).  Atom 1.52.0 x64

**Comment by darangi** [comment]
@gothicserpent @wgstjf Thanks for catching this issue. I have also reproduced this on macOS
