### ISSUE TITLE
Not autoscrolling on undo when selection does not change

### ISSUE THREAD

**Issue by colllin** [atom/atom#2158]
When I undo or redo something, could atom please scroll to the place where the undo/redo actions are having an effect?

I don't know if this is an intermittent or constant issue... if it's intermittent, one way to reproduce is to refresh your editor (ctrl+option+cmd+L) then try to undo a few things and it keeps me - no, *forces me* - to the top of the file.

**Comment by DiThi** [comment]
Can confirm by deleting a symbol (e.g. an =), scrolling out and then undoing: it doesn't scroll.

I'm not sure what I did but autocomplete showed up for something else while line was out of view.

Wouldn't be easier/better to always autoscroll on undo when cursor is out of view? (not when it changes)

**Comment by izuzak** [comment]
I can no longer reproduce this problem (even with the instructions from https://github.com/atom/atom/issues/2158#issuecomment-47306173), so going to close this issue. Let us know if anyone can still reproduce this in Atom 1.0.11.
