### ISSUE TITLE
Atom not saving theme settings

### ISSUE THREAD

**Issue by opioom** [atom/atom#21590]
Description

Although I change theme, everytime I start atom, default theme is loaded. No external package is installed yet.
Steps to Reproduce

1.- Change default theme
2. Close Atom
3. Open Atom

Expected behavior: The theme I choose is loaded. Welcome tabs are not opened.

Actual behavior: Default theme is loaded. Welcome tabs are opened.

Reproduces how often: Everytime I run Atom
Versions

Atom : 1.52.0
Electron: 6.1.12
Chrome: 76.0.3809.146
Node: v12.4.0

OS version; Mac OS Mojave 10.14.6

**Comment by darangi** [comment]
I tried changing the theme on `atom 1.52.0` `macOS catalina 10.15` it worked as expected and the change was saved after reloading. Have you tried running atom in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by opioom** [comment]
I fixed the issue by adding in config.cson following lines:
```
  themes: [
    "one-light-ui"
    "one-light-syntax"
  ]
```
