### ISSUE TITLE
Wrong File Rename Prompted

### ISSUE THREAD

**Issue by ichezhia** [atom/atom#21616]
### Description

When in split-screen, and the user right clicks to rename a file, Atom prompts to rename the active file rather than the inactive file which was right clicked on.

### Steps to Reproduce

1. Open two files.
2. Click and drag the file name to do split-screen (up and down or left and right).
3. Click one file name to make it active.
4. Right click on the other inactive file name.
5. Click Rename.

**Expected behavior:**

Right clicking an inactive file should rename the same file.

**Actual behavior:**

Right clicking an inactive file prompts to rename the active file.

**Reproduces how often:**

100%

### Versions

1.52.0 x64
Windows 10

### Additional Information

Other actions (close tab) seem to work on the right-clicked file. It seems that only rename acts on the inactive file.

By active file, I mean clicking the file name at the top of the opened file such that a blue line appears on the left side of the file name.

By inactive file, I mean file names that have a gray line on the left side of the file name.

**Comment by darangi** [comment]
Reproduced on atom 1.52  MacOS. 🙇🏾‍♂️

**Comment by darangi** [comment]
Fixed in https://github.com/atom/tabs/pull/531
