### ISSUE TITLE
"Find and replace all" button is broken in 1.54.0-nightly8

### ISSUE THREAD

**Issue by aminya** [atom/atom#21622]
<details>
<summary>Prerequisites</summary>

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

</details>

### Description

"Find and replace all" button does not work anymore in 1.54.0-nightly8. It works fine in nightly 7.

![image](https://user-images.githubusercontent.com/16418197/97775123-26e53a80-1b2c-11eb-82f2-90bd8586a458.png)

### Steps to Reproduce

1. Press CTRL+SHIFT+F in a project
2. Try to "find and replace all" some string

**Expected behavior:**
Find and replace all

**Actual behavior:**

The button does not do anything

**Reproduces how often:**

Always
### Versions

```
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0-nightly8
python 3.7.4
git 2.29.1.windows.1
visual studio
```

### Additional Information

The offending PR seems to be https://github.com/atom/atom/pull/21587

cc: @Benjamin-Dobell 

This is similar to the error that we had in https://github.com/atom/find-and-replace/pull/1128

**Comment by Benjamin-Dobell** [comment]
I believe an issue ought to be opened against atom/find-and-replace, not here. As https://github.com/atom/find-and-replace/issues/1129 should be reverted. It's incorrectly working around a breakage in Atom's APIs, rather than addressing the underlying cause.

https://github.com/atom/atom/pull/21587 fixed the underlying issue. We shouldn't roll that back, as it's restoring the documented API behaviour that _many_ packages rely upon, not just find-and-replace.

**Comment by Benjamin-Dobell** [comment]
Relevant API documentation: https://flight-manual.atom.io/api/v1.52.0/AtomEnvironment/#instance-confirm

Note that the `confirm` takes a callback, as opposed to returning a promise.

**Comment by aminya** [comment]
>  As atom/find-and-replace#1129 should be reverted.

@Benjamin-Dobell This seems like a good PR!
