### ISSUE TITLE
An additional line is created after saving the codes.

### ISSUE THREAD

**Issue by shuvo-bhuiyan** [atom/atom#21628]
**Steps to Reproduce**
1. Open the **Atom**.
2. Create a .html file in a folder.
3. Write some **HTML** codes.
4. Save the code using the keyboard buttons `Ctrl + S` buttons. 

**Expected behavior:**
-  When a user saves the code of **HTML**, an additional line gets created. 
For instance, the last line number of the codes is 45. However, 46 number line gets created after saving the code.

**Actual behavior:**
- No additional line should get created after saving the code in the file.

### Versions
1.52.0

**Comment by belcar-s** [comment]
I believe this is intended. Disable it by browsing to the settings for the whitespace package and unchecking the box labeled "Ensure Single Trailing Newline" 🙂.

**Comment by shuvo-bhuiyan** [comment]
Found it working as per the [comment](https://github.com/atom/atom/issues/21628#issuecomment-720210381) of @belcar-s. Hence, this issue can be closed.
