### ISSUE TITLE
atom's dependency gvfs-bin, now the package is not available for ubuntu 20.10

### ISSUE THREAD

**Issue by omegaui** [atom/atom#21625]
The **gvfs-bin** package has been removed and now the latest version of **ubuntu 20.10(groovy gorilla)** does not include it by default. And also the package cannot be installed by users manually it may broke the system. The docs says that the package was of no use in ubuntu 20.10 so it was **deprecated**.

So, I request to add the remedy to this problem.
The only method left to install it is via snap-store and I do not know whether that will work or not.
![Screenshot from 2020-10-31 20-13-35](https://user-images.githubusercontent.com/73544069/97782171-05309580-1bb6-11eb-98f2-6503f588ae52.png)
![Screenshot from 2020-10-31 20-13-19](https://user-images.githubusercontent.com/73544069/97782180-0f529400-1bb6-11eb-8768-04db6b591fae.png)

**Comment by zevlee** [comment]
While I can't use the stable version, I am able to install Atom Beta without issue. Hopefully the stable version will be similarly compatible when it's updated to 1.53.0.
