### ISSUE TITLE
Atom: gvfs-bin dependency problem in Ubuntu 20.10

### ISSUE THREAD

**Issue by anikburagohain** [atom/atom#21666]
**gvfs-bin** has been removed in **Ubuntu 20.10**. Due to missing/obsolete dependency **gvfs-bin**, Atom is no longer installable.

Please fix the issue as soon as possible.
Thankyou!

**Comment by darangi** [comment]
Hi @anikburagohain , this issue has been resolved, what version of atom are you running?

**Comment by anikburagohain** [comment]
I was using Atom 1.52.0. Thankyou for informing. The issue has been solved in the latest version.

**Comment by anikburagohain** [comment]
I was using Atom 1.52.0. Thankyou for informing. The issue has been solved in the latest version.
