### ISSUE TITLE
dev-tools on save? 

### ISSUE THREAD

**Issue by Alex-CodeLab** [atom/atom#21667]
Since today Atom opens  dev-tools on ctrl-s.
And even worse, every time it auto-saves a file.

It used to be ctrl-shift-C and ctrl-shift-I (still works). 

I did not set any keymaps or install a plugin 
(perhaps some plugin updated recently, is there a way I can check that? )

### Versions
version 1.52.0
ubuntu 20.4

**Comment by Alex-CodeLab** [comment]
issue magically disappeared.

**Comment by ju276** [comment]
Yep
