### ISSUE TITLE
Some OpenType tags not working

### ISSUE THREAD

**Issue by AlsoScratch** [atom/atom#21682]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Some OpenType tags don't work

### Steps to Reproduce

1. Download [Iosevka](https://typeof.net/Iosevka/) font
2. Launch Atom and open Stylesheet
3. Specify the following `font-feature-settings`:
```
    font-feature-settings: "cv04" 2, "cv15" 2, "cv33" 3, "cv36" 2, "cv37" 1,
                           "cv38" 3, "cv40" 2, "cv41" 2, "cv42" 2, "cv44" 2,
                           "cv46" 2, "cv47" 2, "cv49" 1, "cv53" 1, "cv50" 2,
                           "cv51" 2, "cv21" 2, "cv11" 1, "cv13" 1, "cv14" 6,
                           "cv17" 3, "cv19" 1, "cv20" 6, "cv27" 1, "cv31" 1;

```

**Expected behavior:**

The `¶`, `^`, `#` and `&` should look like this:
<img width="675" alt="Screenshot 2020-11-10 at 7 29 42 PM" src="https://user-images.githubusercontent.com/48752273/98668779-53e6e800-238b-11eb-9d2c-882ee7dca873.png">

**Actual behavior:**

They still have their default appearance.

**Reproduces how often:**

Always

### Versions
- OS: macOS 10.15.7
- Font version: 4.0.0-alpha.1
- Atom version: 1.52.0

**Comment by UziTech** [comment]
Can you provide your whole styles.less file? What selector are you adding that css to?

**Comment by AlsoScratch** [comment]
```
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */


/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
    // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
    // color: white;
    // background-color: hsl(180, 24%, 12%);
}

// style UI elements inside atom-text-editor
atom-text-editor .cursor {
    // border-color: red;
}

/*
    @real fox.quick(h){ *is_brown && it_jumps_over(dogs.lazy) }
    0123456789 ABC.DEF.GHI.JKL.MNO.PQRS.TUV.WXYZ ß <= ~¶^$#% >=
*/
atom-workspace {
    -webkit-font-smoothing: antialiased;
    font-family: "Iosevka Fixed", "Argentum Sans", "IBM Plex Sans";
    font-variant-ligatures: no-common-ligatures;
    font-feature-settings: "cv04" 2, "cv15" 2, "cv33" 3, "cv36" 2, "cv37" 1,
                           "cv38" 3, "cv40" 2, "cv41" 2, "cv42" 2, "cv44" 2,
                           "cv46" 2, "cv47" 2, "cv49" 1, "cv53" 1, "cv50" 2,
                           "cv51" 2, "cv21" 2, "cv11" 1, "cv13" 1, "cv14" 6,
                           "cv17" 3, "cv19" 1, "cv20" 6, "cv27" 1, "cv31" 1;
}

code {
    font-family: "Iosevka Fixed";
}

kbd {
    font-family: "Iosevka Fixed";
}

.github-Git {
    font-family: "Iosevka Fixed", "Argentum Sans", "IBM Plex Sans" !important;
}

.keystroke {
    font-family: "Iosevka Fixed", "Argentum Sans", "IBM Plex Sans" !important;
}

.suggestion-description-content {
    font-family: "Iosevka Fixed", "Argentum Sans", "IBM Plex Sans" !important;
}

.suggestion-description-more-link {
    font-family: "Iosevka Fixed", "Argentum Sans", "IBM Plex Sans" !important;
}

.tooltip {
    -webkit-font-smoothing: antialiased;
    font-family: "Iosevka Fixed";
    font-variant-ligatures: no-common-ligatures;
    font-variant-numeric: oldstyle-nums;
    font-feature-settings: "cv04" 2, "cv15" 2, "cv33" 3, "cv36" 2, "cv37" 1,
                           "cv38" 3, "cv40" 2, "cv41" 2, "cv42" 2, "cv44" 2,
                           "cv46" 2, "cv47" 2, "cv49" 1, "cv53" 1, "cv50" 2,
                           "cv51" 2, "cv21" 2, "cv11" 1, "cv13" 1, "cv14" 6,
                           "cv17" 3, "cv19" 1, "cv20" 6, "cv27" 1, "cv31" 1;
}

```

**Comment by UziTech** [comment]
I don't think Atom does anything with `font-feature-settings` If something isn't working it is either a bug in the version of chrome compiled with Atom (Chrome v76.0.3809.146 i think) or the font.

**Comment by AlsoScratch** [comment]
The creator of the font suspects it's an issue with Harfbuzz.

**Comment by UziTech** [comment]
So it is an issue with the font. To fix it you will have to follow their advice and create a custom build.

**Comment by AlsoScratch** [comment]
It works fine on the website: <https://typeof.net/Iosevka/>

**Comment by ju276** [comment]
Ok
