### ISSUE TITLE
SyntaxError: unknown: 'with' in strict mode

### ISSUE THREAD

**Issue by gogo9th** [atom/atom#21749]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

SyntaxError: unknown: 'with' in strict mode (1:27)

### Steps to Reproduce

I ran the following program:

```
const babel = require('@babel/core');

var code = 'function f(foo, values) {  with (foo) {   }  }'

var res = babel.transform(code, {
   retainLines: true,
   compact: false,
   presets: ['@babel/preset-env'],
   plugins: [
    ["@babel/plugin-transform-modules-commonjs", { "strictMode": false }]
  ]
}).code;

```

**Expected behavior:**

The instrumentation should succeed. 

**Actual behavior:**

SyntaxError: unknown: 'with' in strict mode (1:27)

**Reproduces how often:**

Always

### Versions

7.12.3

**Comment by darangi** [comment]
Hey @gogo9th, how did you execute this on atom? Did this happen by just typing it into the text editor?
