### ISSUE TITLE
"Clang is not installed in your syste!" on start, after clicking "Install Clang" nothing happens and it occurs again next start

### ISSUE THREAD

**Issue by jayjupdhig** [atom/atom#21754]
So it will NOT be installed...

Version: Most current on 2020-11-24
System: Windows 10 x64 Pro, most current version on 2020-11-24
![123](https://user-images.githubusercontent.com/42765391/100081194-09637200-2e47-11eb-9f17-c271e4b54436.jpg)

Screenshot:
https://i.ibb.co/jMCvMck/123.jpg

thx for feedback.``

**Comment by jayjupdhig** [comment]
IS the only one way to bypass that message to install "clang" ??

**Comment by jayjupdhig** [comment]
I think i can't move that, maybe a project admin can?

**Comment by UziTech** [comment]
You could close this and open a new issue on that repo

**Comment by jayjupdhig** [comment]
done
