### ISSUE TITLE
Trying to create a map using atom/folium

### ISSUE THREAD

**Issue by jonex6119** [atom/atom#21756]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Hey My name is jonex I was doing a course on udemy and that course asked me to use atom and make a web map and the map tiles was default to "openstreertmap" And i tried to change the tiles of the map to "Stamen Terrain" but it didn't work. Please help !!!!!

### Steps to Reproduce
1. open atom
2. click on view >> developer >> open in dev mode
3. create a file name "Mapping" and select it 
4.  open the terminal and install folium "pip install folium"
5. then type "python" and press enter
6. then "import folium" press enter
7. then I created a map object by typing "map = folium.Map" press enter 
8. map =folium.Map(location = [38.58, -99.09])
9. type "map" press enter
10. then type map.save("Map1.html")
11. open the "Map1.html" file from the mapping folder in a browser 
12. it will show you a normal map and then come back to atom 
13. Create a new file under mapping named "map1.py"
14. then write the following code in it >
 import folium
map = folium.Map(location = [38.58, -99.09], zoom_start=6, tiles="Stamen Terrain")

map.add_child(folium.Marker(location=[38.2, -99.1], popup="Hi there", icon=folium.Icon(color='green')))

map.save("Map1.html")
15. now open a new terminal and wirte "python map1.py" and press enter .
16. Now open the browser and reload it. 

**Expected behavior:**

![image](https://user-images.githubusercontent.com/73393144/100100985-a645ff80-2e87-11eb-8421-0d04430cc4ce.png)

**Actual behavior:**

![image](https://user-images.githubusercontent.com/73393144/100101034-b231c180-2e87-11eb-8a3d-9fddb7761769.png)

**Reproduces how often:**

 every time

### Versions

Atom    : 1.53.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.53.0
python 3.8.5
git
visual studio

**Comment by darangi** [comment]
Hey @jonex6119 , This isn't a problem related to atom, this is a problem with folio.

**Comment by jonex6119** [comment]
> Hey @jonex6119 , This isn't a problem related to atom, this is a problem with folio.

@darangi Thank you for your reply .But how should I fix this problem ????????
