### ISSUE TITLE
"Try PlatformIO IDE for VSCode" on start, then click "Do not shot this message", but it occurs again on next start

### ISSUE THREAD

**Issue by jayjupdhig** [atom/atom#21755]
Versions:

Atom: Most current on 2020-11-24
Windows: Windows 10 Pro x64

![321](https://user-images.githubusercontent.com/42765391/100081523-69f2af00-2e47-11eb-92a9-56767ab33532.png)

or

https://i.ibb.co/f0zDGyb/321.png

Why that?

Thanks for feedback.

**Comment by jayjupdhig** [comment]
IS the only one way to bypass that message to install "vs code" ??

**Comment by jayjupdhig** [comment]
Now, i tested it: AFter installing VS Code, the message still occurs.

WTF...

**Comment by UziTech** [comment]
You have to uninstall [platformio-ide](https://atom.io/packages/platformio-ide) to stop the message. This should be an issue on their [repo](https://github.com/platformio/platformio-atom-ide)

**Comment by jayjupdhig** [comment]
OK, thx. 

But what is if it need `platform-ide` for some special reasons...?

**Comment by UziTech** [comment]
You should ask on that repo

**Comment by jayjupdhig** [comment]
ok
