### ISSUE TITLE
How to run this repository on my local environment?

### ISSUE THREAD

**Issue by RisingStar-Web** [atom/atom#21761]
I am going to run this repo on my local environment.
I already installed the npm packages.
And what should I do now?

**Comment by darangi** [comment]
@RisingStar-Web , here is a[ guide](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#hacking-on-atom-core)

**Comment by RisingStar-Web** [comment]
Thanks.
One more question is that how can I run this repository on web browser?

**Comment by RisingStar-Web** [comment]
I am going to change some source code and rebuild it.

**Comment by darangi** [comment]
> Thanks.
> One more question is that how can I run this repository on web browser?

You can't run atom on the web browser

**Comment by darangi** [comment]
> Thanks.
> One more question is that how can I run this repository on web browser?

You can't run atom on the web browser
