### ISSUE TITLE
the bulid have long time

### ISSUE THREAD

**Issue by sxy562102838** [atom/atom#21760]
C:\atom-1.53.0>script\build
Node:   v12.12.0
Npm:    v6.11.3
Python: v3.9.0
Installing script dependencies

**Comment by aminya** [comment]
This was fixed in #21308 #21401 #21421 #21431. You should ask the maintainers to merge those PRs.

**Comment by sadick254** [comment]
In my experience atom build tend to be slow due to 
 - Slow network
 - Slow computer
 What are the specs of the computer you are building atom on?
