### ISSUE TITLE
Can't run on CentOS 6.5

### ISSUE THREAD

**Issue by Grimeh** [atom/atom#2177]
Successfully builds and installs, but complains about a missing library when run.
`/usr/local/share/atom/atom: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory`
libnotify, and libnotify-devel are installed. Looks like it thinks it was built against a different version of libnotify (libnotify4), one that seemingly isn't readily available on CentOS.

**Comment by pcoady** [comment]
Has anyone had any success installing on CentOS 6.5?

**Comment by juanchaur** [comment]
Yes, I've succeed installing it. I used the solution they provide in the Wiki: https://github.com/nwjs/nw.js/wiki/The-solution-of-lacking-libudev.so.0

So the steps I did were:
* Create a folder were nodewebkit is going to be: ~/Documents/NW
* Download the nw zip, unzip it and copy all the content to the folder you created. https://github.com/nwjs/nw.js)
* create a folder 'lib' and added all the libraries missing
```
├── ld-linux-x86-64.so.0
├── libc.so.6
├── libdl.so.2
├── libgdk_pixbuf-2.0.so.0
├── libgdk-x11-2.0.so.0
├── libgio-2.0.so.0
├── libglib-2.0.so.0
├── libgnome-keyring.so.0
├── libgobject-2.0.so.0
├── libgtk-x11-2.0.so.0
├── libpeerconnection.so
├── libstdc++.so.6
└── unset_var.so
```
* rename the binary nw to nw.bin
* create a empty file named nw: ```nano nw```
* in the file you just created add the following:
```
#!/bin/bash
MYAPP_WRAPPER="`readlink -f "$0"`"
HERE="`dirname "$MYAPP_WRAPPER"`"

# Always use our versions of ffmpeg libs.
# This also makes RPMs find our library symlinks.
export LD_LIBRARY_PATH=$([ -n "$LD_LIBRARY_PATH" ] && echo "$HERE:$HERE/lib:$LD_LIBRARY_PATH" || echo "$HERE:$HERE/lib")

exec -a "$0" "$HERE/nw.bin"  "$@"
```
* change the mode of the file: ```chmod u+x nw ```
* And now you can run it by doing: ```./nw ```

Hope this can help

**Comment by gliurn** [comment]
@juanchaur  the discussion is about atom-shell not NW. Your solution work for both?

**Comment by qubitrenegade** [comment]
We're having the same issue.  We're trying to install Atom on a CentOS server and attempting to run over a forwarded X11 session, though I don't think that it's contributing to runtime errors.

Has there been any movement on this issue?

**Comment by sodonnell** [comment]
I'm getting the same issue on CentOS 6.5.

```/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libnss3.so: version `NSS_3.14.3' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/libnode.so)
/usr/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/libnode.so)
/usr/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/share/atom/libgcrypt.so.11)
/usr/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /usr/share/atom/libgcrypt.so.11)```

I tried: sudo yum install libc.so.6 libstdc++.so.6 libnss3.so, but encountered the following:

```Package glibc-2.12-1.80.el6.i686 already installed and latest version
Package libstdc++-4.4.6-4.el6.i686 already installed and latest version
Package nss-3.13.6-2.el6_3.i686 already installed and latest version```

**Comment by siddharthgoel88** [comment]
Is this issue still looked into?

**Comment by sodonnell** [comment]
I gave-up and installed sublime3, which is actually much more light-weight and has many more features I'd prefer.

**Comment by sodonnell** [comment]
I gave-up and installed sublime3, which is actually much more light-weight and has many more features I'd prefer.

**Comment by 1wiseash** [comment]
I haven't given up yet. I love Atom on my Windows and Mac. I don't have sudo privileges on my work's CentOS 6 systems. Anyone else still trying to find a solution? (That doesn't require sudo (not a strict requirement, but helpful)?)

**Comment by Albertc** [comment]
Sorry, but... is this solved?

```
[root@gw Descargas]# atom
[root@gw Descargas]# /usr/share/atom/atom: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

```

Thanks

**Comment by colin-zhang** [comment]
maybe the solution is update CentOS 6.5 to CentOS 7

**Comment by Troop666** [comment]
Same error on CentOS 6.8

$ atom
$ /usr/share/atom/atom: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory
^C
$ whereis libnotify.so
libnotify: /usr/lib64/libnotify.so /usr/include/libnotify
# ln -s /usr/lib64/libnotify.so /usr/lib64/libnotify.so.4
$ atom
$ /usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/libnode.so)
^C

$ strings /usr/lib/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by scottjgibson** [comment]
Same libnotify.so.4 error here after finally got it built non-root on RHEL6.  Upgrading isn't an option as its not a personally owned machine.

**Comment by 1wiseash** [comment]
I finally gave up. I created an Ubuntu VM and save files to a shared drive. Works well enough for me and I didn't give in to the hundreds of Sublimers insisting it's the only editor "real" programmers should use—which is a win in itself. (They are still light years better than the emacsters, though.)

**Comment by juanchaur** [comment]
Sublime, atom... At the end, anyone should use which ever editor they like. I use both and others in my daily work (but more IntelliJ) and I have no complains with any. Regarding the issue which is the main point, yeah, you should give up on CentOS, it's a nightmare.

**Comment by 1wiseash** [comment]
I agree with you 100%. I was (mostly) joking. I use NetBeans, PyCharm, CLion, notepad++, atom, sed, and others as necessary to get the job done. I don't use vim, though, for fear of never being able to exit the program!

**Comment by 1wiseash** [comment]
CentOS install seems like a deadend at this point. I'll still follow this thread, but I feel like it's hopeless and probably not worth the effort unless we are aiming for a pull request.

**Comment by yakkadesign** [comment]
How anyone know how to specify the compiler?   I found this article about setting up a C++11 complier but I don't think the build utility is picking this up: https://edwards.sdsu.edu/research/c11-on-centos-6/ 

I'm getting this error:
-----------------
In file included from ../src/main.cc:1:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /root/.node-gyp/6.6.0/include/node/node.h:42,
                 from ../../nan/nan.h:47,
                 from ../src/main.cc:1:
-----------------

Here is what I did:
yum install -y git gnome-keyring gnome-keyring-devel

#setup C++11 complier:  https://edwards.sdsu.edu/research/c11-on-centos-6/
wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
yum upgrade
yum install devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++
scl enable devtoolset-2 bash

#from https://nodejs.org/en/download/package-manager/
curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
yum install -y nodejs
#to test should be 6.x
node -v

npm install -g node-gyp

#point to complied version of python 2.7
npm config set python /usr/local/python2p7/bin/python -g 

cd /usr/src 
git clone https://github.com/atom/atom.git
cd atom

./script/build --install

**Comment by mirov09** [comment]
Desperately trying to have a suitable alternative to eclipse on my company's dev server.
No choice on the OS : RHEL6.7 provided by the HW vendor and same as on our HPC nodes.
Has anyone managed to install atom or vscode on RHEL6.7 yet? Or has everyone give up?
I am just at the beginning of the compilation process with the glibc error.
Do I try further, or is it a lost cause?
Thx

**Comment by Albertc** [comment]
I coludn't install atom on Centos, actually using atom on windows against samba linux
You can try on Centos, Sublimetext

**Comment by tgonzalez89** [comment]
any solution to this? I m downloaded https://github.com/atom/atom/releases/download/v1.11.2/atom-amd64.tar.gz and tried to run it, but I get the https://github.com/atom/atom/releases/download/v1.11.2/atom-amd64.tar.gz  error...
I don't have access to root. Should I try to compile it myself? Meanwhile I am using Sublime.

**Comment by r17n** [comment]
Get the same error in Fedora 24.1.2. Running in a VM. Fresh VM with ActiveMQ being the only thing I've installed besides Atom. Error is similar:
'/usr/share/atom/atom: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory'

**Comment by dm-blue** [comment]
There is a solution to build and run atom on Centos 6.x, and I'm using it up to now, on 1.17.x version.
It is required to add in the /opt/atom/share/atom the glibc-2.14.1 and stdc++ libraries from Fedora 15 (trick learned from google-chrome, which had the same issue).
Starting with 1.17.x, the decision to use a precompiled tool (mksnapshot) to build a snapshot breaks the building process. From my perspective, this is a portability issue.

**Comment by avdhesh-agnisys** [comment]
I am trying to install on CentOs 6.5 but It gives below error.
   **error: Failed dependencies:
        libsecret-1.so.0()(64bit) is needed by atom-1.18.0-0.1.x86_64**

**Comment by dm-blue** [comment]
Yes, it's a new dependency. I took libsecret-18.5-2.fc25.src.rpm from latest Fedora and compiled for Centos 6 (rpmbuild --rebuild  libsecret-18.5-2.fc25.src.rpm). I installed the resulted binary package and now atom works fine.

**Comment by unmanifest** [comment]
@dm-blue Can you provide any pointers on more details on your comment: 
"There is a solution to build and run atom on Centos 6.x, and I'm using it up to now, on 1.17.x version." 

How did you get this working? Thanks!

**Comment by dm-blue** [comment]
@unmanifest  Since that message, I managed to use the latest version, 1.19.5. These are the main steps. Still, I'm not sure if they are enough, my system suffered a lot of changes since first install, years ago.

1. Install from SCLo repository, the latest devtoolset (6) and python27 (see http://wiki.centos.org/SpecialInterestGroup/SCLo).

2. Install latest nodejs from rpm.nodesource.com respository.(eg. 6.11.3)

3. Build the latest libstdc++ library from latest gcc, following next steps:
a. Install compiler dependencies:
 yum install gcc gcc-g++ libmpc-devel mpfr-devel gmp-devel
b. Enable the latest gcc compiler, to avoid compiling issues:
 source /opt/rh/devtoolset-6/enable
c. Get the latest gcc sources and unpack:
wget ftp://ftp.gnu.org/gnu/gcc/gcc-7.1.0/gcc-7.1.0.tar.bz2
tar jxvf gcc-7.1.0.tar.bz2
d: Build latest gcc (boostrap only)
mkdir -p objdir
cd objdir
../gcc-7.1.0/configure --disable-multiarch --disable-multilib --enable-languages=c++
make -j4 BOOT_CFLAGS='-O' bootstrap
e: libstdc++.so.6 will be available as:
x86_64-pc-linux-gnu/libstdc++-v3/src/.libs/libstdc++.so.6.0.23
f: copy the new build libstdc++ library and symlinks in a specific location (eg. /opt/lib.stdc)

4. Create a script to compile the atom from source, adding these lines:
source /opt/rh/devtoolset-6/enable
source /opt/rh/python27/enable
export LD_LIBRARY_PATH=/opt/lib.stdc${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
./script/build --no-quiet
# If you want to change the default path where to install (eg. /opt/atom instead of /usr/local)
sed -e "s/'\/usr', 'local'/'\/opt', 'atom'/" -i script/lib/install-application.js
./script/build --install
cp -r /opt/lib.stdc/* /opt/atom/share/atom

5. Symlink the /opt/atom/bin/atom into execution path (eg. /usr/local/bin)

Perhaps there are missing steps, fell free to ask.

**Comment by unmanifest** [comment]
@dm-blue Thanks for the detailed instructions! Till Step #4 everything worked great! Now I'm stuck on libsecrect errors in step 4 - while building atom. I saw your comment above about using the libsecrect rpm from fc25 and rebuilding. But that leads to many missing packages. See output below.

So I go chasing each of them and gobject-introspection-devel is a problem. Will keep trying - but was wondering if I should take a different route. 

$ rpmbuild --rebuild libsecret-0.18.5-2.fc25.src.rpm
Installing libsecret-0.18.5-2.fc25.src.rpm
warning: InstallSourcePackage at: psm.c:244: Header V3 RSA/SHA256 Signature, key ID fdb19c98: NOKEY
warning: user mockbuild does not exist - using root
warning: group mockbuild does not exist - using root
warning: user mockbuild does not exist - using root
warning: group mockbuild does not exist - using root
error: Failed build dependencies:
	gobject-introspection-devel is needed by libsecret-0.18.5-2.el6.x86_64
	intltool is needed by libsecret-0.18.5-2.el6.x86_64
	vala-devel >= 0.17.2.12 is needed by libsecret-0.18.5-2.el6.x86_64
	vala is needed by libsecret-0.18.5-2.el6.x86_64
	valgrind-devel is needed by libsecret-0.18.5-2.el6.x86_64

**Comment by dm-blue** [comment]
Except vala, (which I also backported to Centos 6), the rest cannot be installed ?
Try 'yum install <missing-package>'

**Comment by unmanifest** [comment]
Got it working with atom from git. Thanks!
