### ISSUE TITLE
Atom crashes every time files are saved, and is slow when opening a file.

### ISSUE THREAD

**Issue by CHGLtd** [atom/atom#21814]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom crashes every time files are saved, and is slow when opening a file.

### Steps to Reproduce

1. Open the Atom.io application.
2. Open any file (even a small 1-line .txt file will do) - sometimes this may take a few seconds to open in a new tab.
3. Save the file.
4. Atom.io crashes, with a pop-up window with the content: "The editor has crashed - Please report this issue to https://github.com/atom/atom".

**Expected behavior:**

1. Open the Atom.io application.
2. Open any file (even a small 1-line .txt file will do) - this **shouldn't** take a few seconds to open in a new tab.
3. Save the file.
4. No crashing.

**Actual behavior:**

1. Open the Atom.io application.
2. Open any file (even a small 1-line .txt file will do) - sometimes this may take a few seconds to open in a new tab.
3. Save the file.
4. Atom.io crashes, with a pop-up window with the content: "The editor has crashed - Please report this issue to https://github.com/atom/atom".

**Reproduces how often:**

Every time I try to do anything with files, Atom crashes.

### Versions

**atom --version**
Atom    : 1.53.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

**apm --version**
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.53.0
python 2.7.16
git 2.29.2

**Running on**
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports) - The most-recent MacBook Pro - Bought on the 17th of September 2020.
macOS Big Sur - Version 11.1 (20C69) Most up-to-date.

### Additional Information

I have fully-uninstalled Atom to try and resolve this issue, however even with a fresh-install this issue still occurs.

I have ran "atom --safe" to try and replicate the this issue, however it does not reproduce (files save without issues, however I would like to run Atom not in safe mode all the time... I've temporality had to start use another code editor...)

**Comment by ThatXliner** [comment]
You probably have a problem with a packages/configuration

**Comment by CHGLtd** [comment]
Hi @ThatXliner, very much correct! Next time I run into a problem I'll disable all packages and work from there.

Thanks for the comment! Time to find a new favourite package to replace the broken one...
