### ISSUE TITLE
Atom's CI fails to download code signing certificates.

### ISSUE THREAD

**Issue by DeeDeeG** [atom/atom#21817]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom's CI fails to download code signing certificates.

Windows:

```
Downloading file from GitHub Repository to C:\Users\VSSADM~1\AppData\Local\Temp\win.p12
Error: Error downloading file. HTTP Status 404.
  at module.exports (D:\a\1\s\script\lib\download-file-from-github.js:20:11)
  at module.exports (D:\a\1\s\script\lib\code-sign-on-windows.js:22:5)
  at D:\a\1\s\script\build:118:13
```

macOS:

```
Downloading file from GitHub Repository to /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/mac.p12
Error: Error downloading file. HTTP Status 404.
  at module.exports (/Users/runner/work/1/s/script/lib/download-file-from-github.js:20:11)
  at module.exports (/Users/runner/work/1/s/script/lib/code-sign-on-mac.js:30:5)
  at /Users/runner/work/1/s/script/build:99:19
```

Example run of of CI failing to download the certificates: https://github.visualstudio.com/Atom/_build/results?buildId=93214

### Steps to Reproduce

1. Trigger a build on either the "Atom Production Branches" or "Atom Nightly" pipeline

**Expected behavior:**

Certificates should successfully download, CI should be able to sign the Windows and macOS apps.

**Actual behavior:**

404 error.

**Reproduces how often:**

100% of the time.

### Versions

All recent CI runs on the Production and Nightly pipelines. (All runs after November 6 -- first affected build was November 18).

Nightly history: https://github.visualstudio.com/Atom/_build?definitionId=1

Production history: https://github.visualstudio.com/Atom/_build?definitionId=32

### Additional Information

Given that these code signing certificates are fairly sensitive/private files, I have to assume the Atom team are hosting these on some private repository somewhere.

The Atom build scripts appear to download these files using the GitHub API, judging by the `Accept: 'application/vnd.github.v3.raw'` HTTP header. (Code: https://github.com/atom/atom/blob/v1.53.0/script/lib/download-file-from-github.js#L11). But it's unclear if any authentication is being used, perhaps as part of the download URL? If authentication is being used, it appears to have expired, or it's not in a form that the API will currently accept. In any case, the authentication method should be updated to be valid/accepted by the API.

- Suggestion: the authentication can be an HTTP header of the form: `Authorization: token INSERTACCESSTOKENHERE`
  - Token should be for an account with access to the private repo hosting the code signing certificate files.
  - For the token, can maybe just use `process.env.GITHUB_TOKEN`.
- Download URLs might (?) need to be updated. They are set in the following CI environment variables:
  - `ATOM_MAC_CODE_SIGNING_CERT_DOWNLOAD_URL`
  - `ATOM_WIN_CODE_SIGNING_CERT_DOWNLOAD_URL`

Example of valid use of the API with authentication: https://stackoverflow.com/a/22314290

**Comment by sadick254** [comment]
This has now been fixed and merged to the master branch. Check out [the latest build](https://github.visualstudio.com/Atom/_build/results?buildId=94538&view=results)

**Comment by DeeDeeG** [comment]
Great, thank you! Good to see the green check marks!
