### ISSUE TITLE
Atom 1.54.0 (snap) not working on Ubuntu 18.04.5

### ISSUE THREAD

**Issue by lucas2595** [atom/atom#21866]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

My atom stopped working when it upgraded to 1.54.0
The process starts but dies immediately.

Doing `sudo snap revert atom --revision 265` to revert to 1.53.0 made it work again.
Doing `sudo snap revert atom --revision 270` to go to 1.54.0 breaks atom.

### Steps to Reproduce

1. Upgrade atom to 1.54.0 via snap
2. Try to run `atom` on the terminal. Process starts but dies right away.

**Expected behavior:**

I expected atom to open

**Actual behavior:**

Atom doesn't open

**Reproduces how often:**

In my machine it happened when I upgraded to 1.54.0. It fails 100% of the time on atom 1.54.0

### Versions

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 2.7.17
git 2.17.1

snap    2.48.2
snapd   2.48.2
series  16
ubuntu  18.04
kernel  5.4.0-60-generic

### Additional Info

This is what shows up on `/var/log/syslog`: 
```
Ubuntu kernel: [17722.344415] atom[28621]: segfault at 1 ip 00007f113cf3e7b8 sp 00007ffdd98dcc18 error 6 in libc-2.31.so[7f113cdd5000+178000]
Ubuntu kernel: [17722.344420] Code: fe 7f 6c 17 c0 c5 fe 7f 74 17 a0 c5 fe 7f 7c 17 80 c5 f8 77 c3 c5 fe 6f 06 c5 fe 6f 4e 20 c5 fe 6f 54 16 e0 c5 fe 6f 5c 16 c0 <c5> fe 7f 07 c5 fe 7f 4f 20 c5 fe 7f 54 17 e0 c5 fe 7f 5c 17 c0 c5
```

Output of `locate libc-2.31.so`:
```
$ locate libc-2.31.so
/snap/atom/270/lib/x86_64-linux-gnu/libc-2.31.so
/snap/core20/904/usr/lib/i386-linux-gnu/libc-2.31.so
/snap/core20/904/usr/lib/x86_64-linux-gnu/libc-2.31.so
```

**Comment by jaime-ez** [comment]
Same issue here

**Comment by MiiliH** [comment]
Same issue, same behavior...

Ubuntu 18.04.5 LTS

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 3.6.9
git 2.17.1

**Comment by drhogarth** [comment]
Exact same issue here with Atom 1.54.0 failing to launch in Ubuntu 18.04.5 LTS.

**Comment by esquinas** [comment]
Same here. It sped up the CPU until a prompt came up to force-quit Atom or keep running.
Somehow, I got it working  by `atom . --clear-window-state`.
Hope this helps.

```
# atom --version
Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

# lsb_release -a 
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
```

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 2.7.17
git 2.30.0

**Comment by lucas2595** [comment]
> Somehow, I got it working by `atom . --clear-window-state`.

Neither `atom --clear-window-state` nor `atom --safe` work for me.

**Comment by DavidEBrumbaugh** [comment]
I have the same issue whether I use snap or apt to install it.

**Comment by DavidEBrumbaugh** [comment]
This appears to be an issue with snap (as opposed to an issue with atom):
https://github.com/snapcrafters/atom/issues/68

**Comment by lucas2595** [comment]
@DavidEBrumbaugh , indeed. I just installed the deb package (without snap) and it ran just fine.
