### ISSUE TITLE
Authentication failed in GitHub Desktop, no problem with Git bash

### ISSUE THREAD

**Issue by Neustradamus** [atom/atom#21867]
Please transfer my issue to https://github.com/desktop/desktop, I can not do it myself.

cc @steveward.

I have done on discourse too:
- https://github.community/t/authentication-failure/155753

Thanks in advance.

### Describe the bug

There are problem of Authentication in GitHub Desktop.

The user account has all right on the machine, he is administrator.

No problem with git "bash" for Windows x64, the GitHub verification window is opened and in the browser too:
- https://i.ibb.co/KLBmh0p/1-git-bash-github-sign-in-with-your-browser-connection-without-problem.png

First launch in C:\Users\USER\AppData\Roaming\GitHub Desktop\logs file:

error: [main] Failed inserting bin path into PATH environment variable
Error: Could not find PATH environment variable
    at q (C:\Users\USER\AppData\Local\SquirrelTemp\webpack:\app\src\lib\process\win32.ts:26:9)
    at Q (C:\Users\USER\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\squirrel-updater.ts:54:19)
    at C:\Users\USER\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\squirrel-updater.ts:39:38
info: [main] Received possible protocol arguments: 2
error: [main] Malformed launch arguments received: C:\Users\USER\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe,--squirrel-firstrun

Try to add authentification: File -> Options -> Accounts - > Github.com Sign in -> Continue with browser:
- https://i.ibb.co/X344NF1/2-github-desktop-authentication-failed-connection-problem.png
- https://i.ibb.co/qsTDrXj/3-github-desktop-file-options-accounts.png
- https://i.ibb.co/8DWzq9f/4-github-desktop-file-options-accounts-sign-in-using-your-browser-before-continue-with-browser.png
- https://i.ibb.co/94gmqz1/5-github-desktop-file-options-accounts-sign-in-using-your-browser-after-continue-with-browser.png

info: [ui] [SignInStore] initializing OAuth flow
info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=CLIENTID&scope=repo%20user%20workflow&state=STATE
info: [main] Received possible protocol arguments: 3
error: [main] Malformed launch arguments received: C:\Users\USER\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe,--allow-file-access-from-files,x-github-desktop-auth://oauth?code=CODE&state=STATE
info: [main] Received possible protocol arguments: 2
error: [main] Malformed launch arguments received: C:\Users\USER\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe,x-github-desktop-auth://oauth?code=CODE&state=STATE

The problem is not new.

GitHub Desktop has been removed from "Programs and Features" in Windows.
Reinstalled, removed again...

Same for GitHub Desktop folders:
- C:\Users\USER\AppData\Local\GitHubDesktop
- C:\Users\USER\AppData\Roaming\GitHub Desktop
- C:\Users\USER\AppData\Local\SquirrelTemp

### Version & OS

- GitHub 2.6.2
- Windows x64

### Steps to reproduce the behavior

Try to add authentification: File -> Options -> Accounts - > Github.com Sign in -> Continue with browser:
- https://i.ibb.co/X344NF1/2-github-desktop-authentication-failed-connection-problem.png
- https://i.ibb.co/qsTDrXj/3-github-desktop-file-options-accounts.png
- https://i.ibb.co/8DWzq9f/4-github-desktop-file-options-accounts-sign-in-using-your-browser-before-continue-with-browser.png
- https://i.ibb.co/94gmqz1/5-github-desktop-file-options-accounts-sign-in-using-your-browser-after-continue-with-browser.png

### Expected behavior

Authentication

### Actual behavior

Authentication failed

### Screenshots

- https://i.ibb.co/X344NF1/2-github-desktop-authentication-failed-connection-problem.png
- https://i.ibb.co/qsTDrXj/3-github-desktop-file-options-accounts.png
- https://i.ibb.co/8DWzq9f/4-github-desktop-file-options-accounts-sign-in-using-your-browser-before-continue-with-browser.png
- https://i.ibb.co/94gmqz1/5-github-desktop-file-options-accounts-sign-in-using-your-browser-after-continue-with-browser.png

### Logs

First launch in C:\Users\USER\AppData\Roaming\GitHub Desktop\logs file:

error: [main] Failed inserting bin path into PATH environment variable
Error: Could not find PATH environment variable
    at q (C:\Users\USER\AppData\Local\SquirrelTemp\webpack:\app\src\lib\process\win32.ts:26:9)
    at Q (C:\Users\USER\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\squirrel-updater.ts:54:19)
    at C:\Users\USER\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\squirrel-updater.ts:39:38
info: [main] Received possible protocol arguments: 2
error: [main] Malformed launch arguments received: C:\Users\USER\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe,--squirrel-firstrun

Try to add authentification: File -> Options -> Accounts - > Github.com Sign in -> Continue with browser:
- https://i.ibb.co/X344NF1/2-github-desktop-authentication-failed-connection-problem.png
- https://i.ibb.co/qsTDrXj/3-github-desktop-file-options-accounts.png
- https://i.ibb.co/8DWzq9f/4-github-desktop-file-options-accounts-sign-in-using-your-browser-before-continue-with-browser.png
- https://i.ibb.co/94gmqz1/5-github-desktop-file-options-accounts-sign-in-using-your-browser-after-continue-with-browser.png

info: [ui] [SignInStore] initializing OAuth flow
info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=CLIENTID&scope=repo%20user%20workflow&state=STATE
info: [main] Received possible protocol arguments: 3
error: [main] Malformed launch arguments received: C:\Users\USER\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe,--allow-file-access-from-files,x-github-desktop-auth://oauth?code=CODE&state=STATE
info: [main] Received possible protocol arguments: 2
error: [main] Malformed launch arguments received: C:\Users\USER\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe,x-github-desktop-auth://oauth?code=CODE&state=STATE

### Additional context

You have all.

**Comment by Neustradamus** [comment]
I have removed my original Desktop [Authorized OAuth Apps] in https://github.com/settings/connections/applications/

Now, I have:
- [GitHub Desktop]
- Never used · Owned by [desktop](https://github.com/desktop)

The problem is always here.

### Logs:
info: [ui] [SignInStore] initializing OAuth flow
info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=CLIENT_ID&scope=repo%20user%20workflow&state=STATE
info: [main] Received possible protocol arguments: 3
error: [main] Malformed launch arguments received: C:\Users\USER\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe,--allow-file-access-from-files,x-github-desktop-auth://oauth?code=CODE&state=STATE

cc @steveward.

**Comment by Neustradamus** [comment]
I have removed my original Desktop [Authorized OAuth Apps] in https://github.com/settings/connections/applications/

Now, I have:
- [GitHub Desktop]
- Never used · Owned by [desktop](https://github.com/desktop)

The problem is always here.

### Logs:
info: [ui] [SignInStore] initializing OAuth flow
info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=CLIENT_ID&scope=repo%20user%20workflow&state=STATE
info: [main] Received possible protocol arguments: 3
error: [main] Malformed launch arguments received: C:\Users\USER\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe,--allow-file-access-from-files,x-github-desktop-auth://oauth?code=CODE&state=STATE
info: [main] Received possible protocol arguments: 2
error: [main] Malformed launch arguments received: C:\Users\USER\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe,x-github-desktop-auth://oauth?code=CODE&state=STATE

cc @steveward.

**Comment by sadick254** [comment]
Thanks very much for the report!

Would you mind reopening this issue in the [github desktop](https://github.com/desktop/desktop) repository? We use multiple repositories to keep the work items tied to the code they apply to. This helps the maintainers spend more time working directly on Atom and less time triaging issues.

Thanks for meeting us half way :+1:

**Comment by Neustradamus** [comment]
@sadick254: Can you unban me from desktop org?

cc @steveward.

**Comment by Neustradamus** [comment]
@sadick254: Thanks for your reply!
Can you unban me from desktop org or reopen my issue?
Thanks in advance.

cc @steveward.
