### ISSUE TITLE
Not launching 

### ISSUE THREAD

**Issue by hjulienne** [atom/atom#21872]
Since atom updated to 1.54, it doesn't launch anymore under Ubuntu 18.04.5 LTS.

It does not launch neither from visual interface, neither from command line.

**Comment by sadick254** [comment]
Can you try installing  the deb package (without snap)

**Comment by josebailo** [comment]
I had the same problem and installed the deb package, all is working now.

The problem must be when you install it with snap.

**Comment by hjulienne** [comment]
Indeed, it's working when installing from the deb package.
Thanks!
