### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Godson-debug** [atom/atom#21878]
[](https://github.com/atom/atom/commit/3e156435ec1a9051b257dfa1ae2159f4f4071ab3?branch=3e156435ec1a9051b257dfa1ae2159f4f4071ab3&diff=split#commitcomment-46130327) 

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

**Comment by Godson-debug** [comment]
Big report

**Comment by Godson-debug** [comment]
[](https://github.com/atom/atom/commit/3e156435ec1a9051b257dfa1ae2159f4f4071ab3?branch=3e156435ec1a9051b257dfa1ae2159f4f4071ab3&diff=split#commitcomment-46130327)

**Comment by Godson-debug** [comment]
https://github.com/atom/atom/commit/3e156435ec1a9051b257dfa1ae2159f4f4071ab3?branch=3e156435ec1a9051b257dfa1ae2159f4f4071ab3&diff=split#commitcomment-46130327

**Comment by Barwaranuj** [comment]
Closed #21878 <https://github.com/atom/atom/issues/21878>.
