### ISSUE TITLE
Atom crashes when using the file open dialog

### ISSUE THREAD

**Issue by jbwdevries** [atom/atom#21890]
### Prerequisites
I have already tried:
```
atom --safe
atom --clear-window-state
mv ~/.atom ~/.atom-backup
atom --disable-gpu
```
### Description
Atom crashes when using the file open dialog. Selecting a file in the tree works ok.

### Steps to Reproduce

I've installed atom via snapd on Ubuntu 18.04. Then simply use CTRL+O or `File -> Open File...`.

**Expected behavior:**
File open dialog shows

**Actual behavior:**
Atom crashes

**Reproduces how often:**
Every time

### Versions
According to the UI and to the help window, I've got 1.54.0 installed. However, if I run `atom --version` I get no output at all. 
```
$ apm --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 2.7.17
git 2.17.1
```

### Additional Information
`/var/log/syslog`:
```
Jan 23 11:40:19 johan-desktop kernel: [ 6064.035139] traps: atom[14563] trap int3 ip:7fc002bc40d5 sp:7fffabe57380 error:0 in libglib-2.0.so.0.6400.3[7fc002b88000+84000]
```

I tried running under gdb but snap makes that difficult, so got nowhere. Not sure how to debug further.

**Comment by jbwdevries** [comment]
The save dialog has the same issue.

**Comment by darangi** [comment]
I currently can't reproduce this issue, can you confirm if it persists when you download atom directly from [atom.io](https://atom.io)?

**Comment by jbwdevries** [comment]
Installing the atom debian package from atom.io does not have this same issue. I can open and save files no problem.

**Comment by darangi** [comment]
Thanks for confirming this.

Unfortunately, we don't support installations via snapd.
