### ISSUE TITLE
Github stuck on loading.

### ISSUE THREAD

**Issue by Anchovy-s3** [atom/atom#21896]
### Description
Github stuck on loading when open GitHub on my Atom editor.

### Steps to Reproduce

1. Make new directory.
2. Click on GitHub in Atom.
3. Click on "Publish on Github".

**Expected behavior:**
Displaying user name.

**Actual behavior:**
User name field is endless loading.
<img width="599" alt="スクリーンショット 2021-01-26 18 13 29" src="https://user-images.githubusercontent.com/59955057/105825804-56a8bf00-6003-11eb-8239-377a561b0d57.png">

**Reproduces how often:**
Every times.

### Versions
<img width="698" alt="スクリーンショット 2021-01-26 18 24 38" src="https://user-images.githubusercontent.com/59955057/105826143-c3bc5480-6003-11eb-813f-e30d98a2b004.png">
<img width="599" alt="スクリーンショット 2021-01-26 18 25 13" src="https://user-images.githubusercontent.com/59955057/105826210-d6cf2480-6003-11eb-986f-0c21daafb99d.png">
Atom    : 1.54.0
<br>
Electron: 6.1.12
<br>
Chrome  : 76.0.3809.146
<br>
Node    : 12.4.0
<br>
<br>

**Comment by ThatXliner** [comment]
I have this problem too!
