### ISSUE TITLE
Cusror not positioning after replace

### ISSUE THREAD

**Issue by ggl** [atom/atom#21897]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

After one replaces newlines with spaces and presses home/nd the cursor doesn't reposition itself correctly altough the column counter shows the correct position. Select with Ctrl+End also doesn't work.

### Steps to Reproduce

1. Open a new empty file ctrl+n
2. Paste a buffer with many lines
3. regex replace $\n with a space
4. press ctrl+end

**Expected behavior:**

Line should be selected and cursor should reposition itself at the end of line.

**Actual behavior:**

Cursor remains at the initial position, line is not selected.

**Reproduces how often:**

100%

### Versions

Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

Npm    : 6.14.10

Linux 5.4.0-62-generic #70~18.04.1-Ubuntu SMP Tue Jan 12 17:18:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by darangi** [comment]
Hi @g2p could you provide a screen recording or screenshots to assist us in reproducing this issue?
