### ISSUE TITLE
word double-click selection in 1.54.0

### ISSUE THREAD

**Issue by ftaiolivista** [atom/atom#21892]
After upgrade to 1.54.0 double clicking on a code (Javascript) word do not select the whole word but stops at first symbol ($)

![Screenshot_20210125_095201](https://user-images.githubusercontent.com/150721/105682643-00e4f180-5ef3-11eb-9f11-47dd6732c664.png)

**Comment by maurice-ellis** [comment]
I'm experiencing the same issue with PHP and double clicking $variable only select the word variable.

**Comment by darangi** [comment]
Thanks for reporting this,

I can also reproduce this on atom 1.54 on Mac OS

**Comment by ThatXliner** [comment]
We should be able to configure the word boundaries (e.g. I want _ to be a non-word for python snake_case)

**Comment by ThatXliner** [comment]
On second thought, why not make it a per-language option?

**Comment by maurice-ellis** [comment]
@ThatXliner, agree... it would be nice to have more control over copying. Right now, it sucks being in PHP and not getting the $, however, there are some times when I just want the text.

**Comment by ThatXliner** [comment]
I think we would need to some how dynamically change the regex here

https://github.com/atom/atom/blob/2f6f41b96e8dc4a1b4eac4647e67de5b85b89bcf/src/cursor.js#L731

depending on the grammar

**Comment by rushl** [comment]
Any movement on this? I've had to freeze my Atom version at 1.53.0.

**Comment by sadick254** [comment]
This has now been fixed on the latest Atom version https://github.com/atom/atom/releases/tag/v1.56.0
