### ISSUE TITLE
Language Ruby

### ISSUE THREAD

**Issue by SampsonCrowley** [atom/atom#21915]
Issues and PRs for **your** package [language-ruby](https://github.com/atom/language-ruby) have received no response from any maintainers for over 2 years now.  There are a LOT of AST errors and a LOT of fixes that need to be merged.

Please don't create a package people depend on and then just abandon it without appointing new maintainers

**Comment by SampsonCrowley** [comment]
[linked issue](https://github.com/atom/language-ruby/issues/287)

**Comment by ThatXliner** [comment]
The maintainers probably forgot some PRs so I usually pop in and out asking about the status of it 😅 . Also, the maintainers are working on some [other stuff][electron] (general [bugfixes][mac] and [performance][p]) so I'm think they just got to get the monstrous problems 👽 down first, then the specifics, like [this one][py] 🐍 . 

[electron]: https://github.com/atom/atom/pull/21815
[mac]: https://github.com/atom/atom/pull/21847
[py]: https://github.com/atom/language-python/pull/325

**Comment by SampsonCrowley** [comment]
It's one thing to forget a few PRs, it's another thing entirely to just not
respond *at all* to *any* issues *or PRs* for *years*
