### ISSUE TITLE
Debug console opens

### ISSUE THREAD

**Issue by Abhijeetrkushwaha** [atom/atom#21922]
### Description
I had recently started using atom and when i code for a while it starts opening debug console everything time since last two days.

### Steps to Reproduce

1. Debug console opens and when I close it, it reopens again.

**Comment by ThatXliner** [comment]
Hey, when you reload Atom, the debug panel (inspect element) opens. (Personally, I would like a way to disable it, but I guess I should open a new bug)

**Comment by Abhijeetrkushwaha** [comment]
I will try to disable it then...thanks
