### ISSUE TITLE
Package (git-diff) doesn't remove panel commands after package is disabled.

### ISSUE THREAD

**Issue by M3TIOR** [atom/atom#21966]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
`git-diff` leaves command hooks registered when they should be destroyed.

### Steps to Reproduce
1. Load Atom with the package enabled
2. Unload package.
3. Optionally, click on any editor then on open the Command Pallet and type `Git Diff`.
4. Re-enable the package.
4. Repeat steps 2-4.

**Expected behavior:**

The command hooks should be destroyed and be unavailable in any editor after the package is disabled.

**Actual behavior:**

If you do step 3, you can see the command hooks stack up.
![screenshot of issue](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/4d4704c5-0c7f-4776-b2e3-c413bd14879a/dee7cci-a23dd5d3-030a-4d67-948d-d93a559a49e8.png/v1/fill/w_1142,h_700,q_70,strp/atomissues1_by_m3tior_dee7cci-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD03MTciLCJwYXRoIjoiXC9mXC80ZDQ3MDRjNS0wYzdmLTQ3NzYtYjJlMy1jNDEzYmQxNDg3OWFcL2RlZTdjY2ktYTIzZGQ1ZDMtMDMwYS00ZDY3LTk0OGQtZDkzYTU1OWE0OWU4LnBuZyIsIndpZHRoIjoiPD0xMTcwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.fbqpLjbDZVVrNHFWNsk9qfbIkFoYn8xV2mrZJz85P2A)

**Reproduces how often:**

Always happens when the package is disabled and re-enabled.

### Versions
Atom    : 1.53.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

**Comment by DeeDeeG** [comment]
I tested this and I can confirm the duplicate commands showing up in the Command Palette, following the steps to reproduce.

---

Atom Nightly 1.56.0-nightly11 (and nightly17 after I did a quick update)
macOS 10.15.7
