### ISSUE TITLE
M1 freeze

### ISSUE THREAD

**Issue by fbongcam** [atom/atom#21971]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Atom editor freezes after a while. The only way to continue is to force quit Atom.

### Steps to Reproduce

1. Start Atom
2. Code for a while

**Reproduces how often:**

After some time of usage.

### Versions

Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 2.7.16
git 2.30.1

Installed Packages
├── Hydrogen@2.14.7
├── Visual-Studio-2015-Dark-Theme@2.4.2
├── accents-ui@1.3.0
├── atom-beautify@0.33.4
├── atom-black-ui@0.28.0
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── atom-minify@0.8.0
├── atom-sass@0.4.0
├── atom-visual-studio-code-ui@2.1.0
├── busy-signal@2.0.1
├── city-lights-syntax@1.1.8
├── city-lights-ui@1.5.3
├── counter@0.3.5
├── dash-syntax@0.4.2
├── dash-ui@0.4.4
├── dracula-syntax@3.0.2
├── dracula-ui@0.6.0
├── file-icons@2.1.46
├── html-template-generator@0.3.0
├── intentions@1.1.5
├── linter@3.3.0
├── linter-flake8@2.4.0
├── linter-jshint@3.1.19
├── linter-ui-default@3.2.4
├── minimap@4.39.8 (disabled)
├── pigments@0.40.6
├── project-manager@3.3.8
├── react@0.18.0
├── script@3.29.3
├── seti-ui@1.11.0
└── sync-settings@5.2.6

macOS: 11.2.1
MacBook Air M1

**Comment by sadick254** [comment]
All the issues related to M1 are tracked on https://github.com/atom/atom/discussions/22023 and https://github.com/atom/atom/issues/21688. For updates you could subscribe there. Am going to close this one out for now.

**Comment by ctkjose** [comment]
These crashes are happening quite often, specially the longer you leave Atom open. In an hour there could be more than 4 freezes.
