### ISSUE TITLE
Menu Bar not fully loading

### ISSUE THREAD

**Issue by Charlie-Sumorok** [atom/atom#21984]
Atom menu bar is not fully loading on launch

## Steps to Reproduce

1. Open Launchpad
1. Find Atom
1. Launch Atom
1. Look at the menu bar
1. See that it is incomplete

**Expected:** The menu bar fully loads<br/>
**Actual:** The menu bar partially loads<br/>

### Atom

```
Atom: 1.54.0
Electron: undefined
Chrome: 76.0.3809.146
Node: 12.4.0
```

### apm

```
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.54.0
python 2.7.16
git 2.24.3

```

### OS

Mac OS X 10.15.7

## Additional Info

The menu bar fully loads when launching using the cli

## Optional Information

<details>
<summary>Installed Package List</summary>
* about
* archive-view
* atom-animations
* atom-autocomplete-python
* atom-beautify
* atom-dark-syntax
* atom-dark-ui
* atom-light-syntax
* atom-light-ui
* atom-vue-hyperclick
* atom-wrap-in-tag
* autocomplete
* autocomplete-atom-api
* autocomplete-css
* autocomplete-html
* autocomplete-plus
* autocomplete-snippets
* autoflow
* autosave
* background-tips
* base16-tomorrow-dark-theme
* base16-tomorrow-light-theme
* bookmarks
* bracket-matcher
* browser-plus
* command-palette
* cson
* dalek
* deprecation-cop
* dev-live-reload
* ds-ignore
* emmet
* emoji-syntax
* encoding-selector
* exception-reporting
* file-icons
* find-and-replace
* find-tab
* fuzzy-finder
* git-diff
* git-plus
* git-plus-toolbar
* github
* github-atom-dark-syntax
* github-dark-theme-syntax
* github-dark-theme-ui-template
* go-to-line
* grammar-selector
* html-includes
* image-view
* incompatible-packages
* keybinding-resolver
* language-c
* language-clojure
* language-coffee-script
* language-csharp
* language-css
* language-gfm
* language-git
* language-gitattributes
* language-go
* language-html
* language-hyperlink
* language-ignore
* language-java
* language-javascript
* language-json
* language-less
* language-make
* language-mustache
* language-objective-c
* language-perl
* language-php
* language-property-list
* language-python
* language-ruby
* language-ruby-on-rails
* language-rust-bundled
* language-sass
* language-shellscript
* language-source
* language-sql
* language-svg
* language-text
* language-todo
* language-todo-more-words
* language-toml
* language-typescript
* language-unix-shell
* language-xml
* language-yaml
* line-ending-selector
* link
* markdown-preview
* metrics
* minimal-icons-menu-tolls
* minimap
* minimap-pigments
* multiline-tab
* notifications
* one-dark-syntax
* one-dark-ui
* one-light-syntax
* one-light-ui
* open-on-github
* package-generator
* package-settings
* pigments
* platformio-ide-terminal
* quick-vue
* satisfy-dependencies
* settings-view
* smart-html-tags
* snippets
* solarized-dark-syntax
* solarized-light-syntax
* sort-attributes
* spell-check
* status-bar
* styleguide
* svg-icons
* svg-preview
* symbols-view
* syntax-theme-boilerplate-syntax
* tabs
* teletype
* template-syntax
* terminal-tab
* timecop
* todo-show
* tool-bar
* town-crier
* tree-view
* update-package-dependencies
* vue-atom-snippets
* vue-autocompile
* vue-autocomplete
* vue-template
* welcome
* whitespace
* wrap-guide

</details>

**Comment by sadick254** [comment]
@Charlie-Sumorok Could you provide screenshots of what you are seeing versus what is expected. That would help us debug the issue.

**Comment by Charlie-Sumorok** [comment]
The issue is not occurring anymore
