### ISSUE TITLE
Close tab button defined on left comes back to the right

### ISSUE THREAD

**Issue by Kwadz** [atom/atom#21992]
### Description

After some time (minutes or hours) I noticed the close tab button comes back to the right, even thought I defined it one the left (which is the normal place on Mac).

### Steps to Reproduce

1. Go to Atom > Preferences > Themes 
2. Click on the gear at the right of the dropdown menu of UI Theme
3. Go to Tab Close Button
4. Select _Left_
5. Notice the new position on the left
6. Keep Atom open and do your life
7. Come back and notice the button is now back on the right

**Expected behavior:**

Close tab button should always remain on the left until further notice.

**Actual behavior:**

Close tab button comes back to the right.

**Reproduces how often:**

100% if you wait enough time.

### Versions

```
Atom    : 1.54.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
macOS   : 10.14.6 (18G7016)
```

### Additional Information

Location of the option: 

<img width="905" alt="image" src="https://user-images.githubusercontent.com/1472599/109066800-e5d1f100-76ed-11eb-90d8-8efd6ff0736a.png">

**Comment by rmwalk85** [comment]
suck a dick

**Comment by Kwadz** [comment]
Closing as, for some reason, I'm not able to reproduce the issue again. If a face it again, or someone else, I'll reopen it.
