### ISSUE TITLE
Packages can override vital keyboard shorcuts like copy/paste

### ISSUE THREAD

**Issue by the100rabh** [atom/atom#2201]
Hi,
I can see that copy shortcut key in linux has the same as another package for script. 

``` cson
'.editor':
  'ctrl-c': 'script:kill-process'
```

I think core shortcut keys must not be overridden by the package script in any situation.

**Comment by Nemesis9765** [comment]
+1 on this.  Have a package where I only use a few of its keybindings but it overrides my copy and paste and it's all or nothing deal for me.
