### ISSUE TITLE
> > Just set up new MacBook Air with M1. Atom will not launch. Googling how to launch. Came across this thread.

### ISSUE THREAD

**Issue by Amirnateghi1** [atom/atom#22036]
> > Just set up new MacBook Air with M1. Atom will not launch. Googling how to launch. Came across this thread.
> 
> @ash37 do you have Rosetta 2 installed?

No, I did not. Had to right click app in finder. Open. Was then prompted to install Rosetta 2.

Launched with Rosetta 2.

_Originally posted by @ash37 in https://github.com/atom/atom/issues/21688#issuecomment-729560729_

**Comment by darangi** [comment]
Take a look https://github.com/atom/atom/issues/21688#issuecomment-792871589
