### ISSUE TITLE
Tree view command - crashes atom

### ISSUE THREAD

**Issue by SimaLima** [atom/atom#22051]
### Steps to Reproduce

1. select folder in tree view
2. press alt + right arrow (windows)
3. atom crashes

**Comment by ThatXliner** [comment]
What's your atom version? If there's a stack trace, that'd be useful, too.

**Comment by SimaLima** [comment]
Atom version: 1.55.0 ia32
Electron: 6.1.12
Chrome: 76.0.3809.146
Node: v12.4.0

I also noticed this happens only on root folder of project and when folder is collapsed.

This is window that pops up.
![Screenshot_2](https://user-images.githubusercontent.com/19992824/111866500-2ed43880-896e-11eb-9f86-25e80af4ab98.png)

**Comment by dk868** [comment]
I apologize deeply for the Delay and errors that are currently happening, my computer is down and it should close . If there’s anything I can do for now please let me know and I will get it done. Once again I apologize for any inconvenience

**Comment by SimaLima** [comment]
It's not some important problem. It's just one keyboard shortcut, nothing else.
Have a nice day :)
