### ISSUE TITLE
Release notes: Please mention Electron 9 upgrade for Atom 1.56.0-beta0

### ISSUE THREAD

**Issue by DeeDeeG** [atom/atom#22054]
## Summary

Hi,

The Electron 9 upgrade ( https://github.com/atom/atom/pull/22003 ) was included in the 1.56 beta release. I think it should be mentioned in the Atom 1.56 beta release notes!

## Motivation

Testers (and early adopters) will want to know that this changed, in order to have a better idea what may be causing bugs, and to have fair warning that this is a really large behind-the-scenes change, and it may take some time for problems to become apparent and get fixed. So this is a riskier daily driver or may be somewhat less functional as small issues continue to be noticed and fixed.

## Describe alternatives you've considered

N/A

(Maybe let Electron 9 live in Nightly for a cycle before landing in Beta? It seems a little late for that though, and it's mostly working.)

## Additional context

Electron 9 PR: https://github.com/atom/atom/pull/22003

Compare Atom 1.55.0 stable to Atom 1.56.0-beta0: https://github.com/atom/atom/compare/v1.55.0...v1.56.0-beta0

**Comment by sadick254** [comment]
@DeeDeeG  thanks for pointing that out. [Release](https://github.com/atom/atom/releases/tag/v1.56.0-beta0) notes updated.

**Comment by DeeDeeG** [comment]
Thank you for updating the release notes!

But... Oops, I linked to the wrong PR. I linked to the tiny "9.4.1 --> 9.4.4" patch version bump PR.

I meant to link to the main Electron 9 PR, specifically this one: https://github.com/atom/atom/pull/21777
