### ISSUE TITLE
Atom Electron 9 - iterator.seek is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by aminya** [atom/atom#22078]
<details>
<summary>Prerequisites</summary>

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

</details>

### Description
Electron 9 has broken `TreeSitterLanguageMode.scopeDescriptorForPosition` function somehow. The linter tests now fail with this error:

```js
      TypeError: iterator.seek is not a function or its return value is not iterable
        at TreeSitterLanguageMode.scopeDescriptorForPosition (/home/runner/work/_temp/atom/usr/share/atom-beta/resources/app.asar/src/tree-sitter-language-mode.js:588:34)
        at TextEditor.scopeDescriptorForBufferPosition (/home/runner/work/_temp/atom/usr/share/atom-beta/resources/app.asar/src/text-editor.js:4539:22)
        at Cursor.getScopeDescriptor (/home/runner/work/_temp/atom/usr/share/atom-beta/resources/app.asar/src/cursor.js:206:24)
        at /home/runner/work/linter/linter/dist/helpers.js:23:99
        at Array.reduce (<anonymous>)
        at Object.getEditorCursorScopes (/home/runner/work/linter/linter/dist/helpers.js:23:51)
        at LinterRegistry.lint (/home/runner/work/linter/linter/dist/linter-registry.js:83:32)
```

### Steps to Reproduce

1. Run the tests for the [linter](https://github.com/steelbrain/linter) package on Electron 9
Here is the link to the CI:
https://github.com/steelbrain/linter/runs/2178504515#step:6:76

**Expected behavior:**

State the breaking changes in the docs or the changelog

**Actual behavior:**

![image](https://user-images.githubusercontent.com/16418197/112208772-baf09500-8be6-11eb-8111-85cc4d1071de.png)

**Reproduces how often:**
100%

### Versions
```
Atom    : 1.57.0-nightly1
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
```

**Comment by lierdakil** [comment]
After a quick look, the offending change seems to be https://github.com/atom/atom/commit/847e787014ceff5a1f573985ef59aacc350c48df#diff-a856237d76fcd8445854bfc4816818af71ffb0a734cc0d1626ecef540131aebcR1342. I would attempt a fix, but I do not understand the code at all -- looking at it, I find myself thinking that it shouldn't work, but it evidently did up until Atom 1.56 (probably)

/cc @maxbrunsfeld

**Comment by lierdakil** [comment]
Nvm, I think I got it. Trying to make a PR now.

**Comment by sadick254** [comment]
Closed by https://github.com/atom/atom/pull/22080
