### ISSUE TITLE
Copy project path stopped working

### ISSUE THREAD

**Issue by hippo-guy** [atom/atom#22074]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * [X] Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * [X] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * [X] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * [X] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * [X] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

"copy project path" is not working.    
I right click, I click on "copy project path" but nothing is registered on the clipboard.    
When I paste - it's the same value I had before on the clipboard. 

### Steps to Reproduce

0. Copy the words `hello world`
1. Right click on desired file on tree view
2. Select copy project path
3. Perform Paste somewhere (new tab?) 

**Expected behavior:**

Project path to be pasted

**Actual behavior:**

`hello world` is pasted (previous clipboard value)

**Reproduces how often:**

consistent

### Versions

Atom    : 1.57.0-nightly1
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.57.0-nightly1
python 2.7.16
git 2.21.0

Mac 10.15.7

**Comment by darangi** [comment]
This is related to the [context menu bug ](https://github.com/atom/atom/issues/22018) which has been [fixed in master](https://github.com/atom/atom/pull/22046), could you verify it's just the copy project path feature that is not working or other actions on the context menu are not working too?

**Comment by hippo-guy** [comment]
@darangi seems to be related. Can I install master directly?

**Comment by darangi** [comment]
@hippo-guy yes, you can either get it on [atom nightly](https://atom.io) or by [build atom from the master branch](https://github.com/atom/atom/blob/ba746fdd511c2cebccd3cd75f6789fb42d49faa5/spec/spec-helper.coffee#L321)
