### ISSUE TITLE
Context menus have no effect (Linux)

### ISSUE THREAD

**Issue by khaeru** [atom/atom#22114]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Using the context menus has no effect.

### Steps to Reproduce

1. Open a context menu, for instance:
    1. in the tree view dock.
    2. in the Git dock.
    3. in the editor area

    The bug occurs whether the menu is opened via secondary (right) mouse click, or the keyboard key for the context menus.
2. Activate a menu item. Correspondingly:
    1. "Rename", "New file", etc.
    2. "Stage"
    3. "Copy"

   As in (1), the bug occurs whether the item is activated by mouse click or by keyboard arrow keys + Enter.

**Expected behavior:**

The selected action is executed.

**Actual behavior:**

Nothing happens.

**Reproduces how often:**

100%

### Versions

```
$ atom-beta --version && apm-beta --version && lsb_release -rd
Atom    : 1.56.0-beta0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0-beta0
python 3.8.6
git 2.27.0
Description:    Ubuntu 20.10
Release:        20.10
```

### Additional Information

All the commands which cannot be activated through the context menus still work when activated by keyboard shortcuts. For instance, I can set focus on the tree view dock and press "a", and the pop-up "Enter the path for the new file." appears; or "Ctrl+C" works in the editor, etc.

**Comment by huseyinozkilic** [comment]
and win10

**Comment by huseyinozkilic** [comment]
and win10

**Comment by sadick254** [comment]
This has already been resolved on the nightly build. You can download it [here](https://atom.io/nightly). Kindly let me know if this is still an issue on win10 and Linux so that I can re-open this.

**Comment by khaeru** [comment]
@sadick254 I confirm that the nightly build fixes the issue! Thanks so much.
