### ISSUE TITLE
"Show in Explorer" command on a folder in the treeview cann't be assigned a shortcut ?

### ISSUE THREAD

**Issue by jiewangjs** [atom/atom#22128]
Is it possible to assign a shortcut to this command ? It is very useful.

**Comment by denisdeoniss** [comment]
[]()

**Comment by ThatXliner** [comment]
You can remap it with your keymap.

**Comment by jiewangjs** [comment]
> keymap.

![image](https://user-images.githubusercontent.com/11204422/113525923-507a2480-95ea-11eb-834a-1cbfedebd2e3.png)
Am I missing something, to my feeling, this command is not there by default.

**Comment by steveoabcd1234** [comment]
Unsubscribe
Sent from Yahoo Mail on Android 
 
  On Sun, Apr 4, 2021 at 7:40 PM, ***@***.***> wrote:   




keymap.



Am I missing something, to my feeling, this command is not there by default.

**Comment by jiewangjs** [comment]
> Unsubscribe Sent from Yahoo Mail on Android On Sun, Apr 4, 2021 at 7:40 PM, ***@***.***> wrote: keymap. Am I missing something, to my feeling, this command is not there by default. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Mind elaborating on the specific syntax. I thought if you cannot find the command in the search box, there just doesnt exist such a command. If there is indeed one, I cannot find the specific syntax on web.

**Comment by UziTech** [comment]
@jiewangjs 

```cson
"tree-view":
  "{whatever keys you want to press}": "tree-view:show-in-file-manager"
```

**Comment by ThatXliner** [comment]
> > keymap.
> 
> ![image](https://user-images.githubusercontent.com/11204422/113525923-507a2480-95ea-11eb-834a-1cbfedebd2e3.png)
> Am I missing something, to my feeling, this command is not there by default.

I see. So it's not a separate command. I'm pretty sure (at least on macOS) you can simulate it with `open -a`

**Comment by UziTech** [comment]
> So it's not a separate command.

The command is `tree-view:show-in-file-manager` but it doesn't work in the command palette because `tree-view` has to be selected.

**Comment by jiewangjs** [comment]
> > So it's not a separate command.
> 
> The command is `tree-view:show-in-file-manager` but it doesn't work in the command palette because `tree-view` has to be selected.

![image](https://user-images.githubusercontent.com/11204422/113543516-22f89f80-9619-11eb-9235-d0eafd4b9735.png)

my keymap file is like this. still not working, this kind of problem is really anoying. Seems trivial, just cannot get it to work.

**Comment by UziTech** [comment]
Do you have a tree-view entry selected when you press <kbd>F7</kbd>? What OS, Atom version are you using?

**Comment by UziTech** [comment]
Ok I just tested it out and it doesn't work with `"f7"` but does work with other key bindings. Not sure why. It does work for me as:

```cson
"atom-workspace":
  "f7": "tree-view:show-in-file-manager"
```

**Comment by jiewangjs** [comment]
> Do you have a tree-view entry selected when you press F7? What OS, Atom version are you using?

Yes. window 10. atom version is 1.55.0x64

**Comment by jiewangjs** [comment]
> ```coffee
> "atom-workspace":
>   "f7": "tree-view:show-in-file-manager"
> ```

Thanks, now it works. your previous comment is different from this one. This one works.

**Comment by UziTech** [comment]
Ya I think it has something to do with precedence of selectors. `"atom-workspace"` has higher precedence than `"tree-view"` so that key mapping will be selected instead of others.

**Comment by darangi** [comment]
Thanks for the input @UziTech
