### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by nitish770** [atom/atom#22158]
### Prerequisites

* [X]  Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
* [X] Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
*  [x] Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
*  [x] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
*  [x] Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
When working on language which uses indentation as its prime factor to identify block of code space plays a major role like in  python. Although Atom is better than Sublime but still it lacks a few functions which sublime have. For example if you mix up spaces and tabs in python code you can't tell in Atom where are the problems. But in Sublime if you select whole code you can tell exactly where are the problems. So I'd like Atom to have this feature of Sublime. We can use **.** to represent space like sublime do.

### Steps to Reproduce

1. Make a python File
2. write a for loop. Hit enter.
3. This first indentation can be either tab or spaces depending on your settings.
4. Just reverse the indentation method in next line. 

**Expected behaviour:**
I'd like Atom to change all the inconsistent indentation method to single method on save.

**Reproduces how often:**
Whenever you forgot some lines to add or you have to debug code 50% chances are there you might catch this error. And sometimes it becomes nearly becomes impossible to deal with in atom.
For small codes we can manually figure out where are the problems but when working on large projects it becomes ticklish to go to each line and change it manually.

**Comment by ThatXliner** [comment]
I think you can hack the init script to do this

**Comment by UziTech** [comment]
You can do this with the atom-beautify package. It has a format on save setting.

**Comment by nitish770** [comment]
> You can do this with the atom-beautify package. It has a format on save setting.

I installed that package but when I ran beautify python it showed autopep8 not found so I donwloaded autopep8. But still it shows the same message.
Although I can use autopep8 from terminal.

And to be honest I think Atom should support that basic feature in built to identify tabs and spaces. We must  not be dependent on any package for that.
