### ISSUE TITLE
The atom/language-ruby package needs a new release immediately

### ISSUE THREAD

**Issue by brunnopleffken** [atom/atom#22160]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Just take a look at this: atom/language-ruby#261.

The official [Ruby language tree-sitter](https://github.com/atom/language-ruby) package is extremely problematic. It's so difficult to use Ruby and ERB files with the syntax coloring going and coming since the release of tree-sitter (see yourselves in atom/language-ruby#279, atom/language-ruby#295, atom/language-ruby#256) that I and several other users migrated to Visual Studio Code to work with Ruby on Rails projects.

The latest version of this package is dated **November 2019** (atom/language-ruby#293). There are some pull requests and pending commits that may fix this issue that users are awaiting impatiently ().

I urge the Atom team to pay attention to the atom/language-ruby package. There are several commits and pull requests from us, users, that the repository maintainers are ignoring. Many developers are afraid to use Microsoft software, with a large company from behind, but it seems that Open-source is not working well with atom in recent times.

### Steps to Reproduce

1. Create a new Ruby file.
2. Use some of the several examples from the issues linked above.
3. See Ruby tree-sitter parser fail miserably.

**Expected behavior:**

The tree-sitter parser should work in all circumstances.

**Actual behavior:**

The tree-sitter parser lost syntax coloring.

**Reproduces how often:**

It happens a lot. I mean... A LOT. With several users on Windows, MacOS and Linux since few years ago.

**Comment by ThatXliner** [comment]
+1. I've seen a lot of complaints about Ruby ~~Ruby is dead~~. @maintainers, we should really take care of Ruby (is it fine if I ping of one of you?).

**Comment by SampsonCrowley** [comment]
PLEASE RELEASE A NEW VERSION ALREADY!!!!!

**Comment by SampsonCrowley** [comment]
You are losing tons of ruby devs to sublime and VScode due to the complete and utter lack of movement on the package over the last 2 years. the syntax highlighting issues with tree-sitter in ruby are a real problem that can't just be ignored away

**Comment by icecream17** [comment]
I've posted a pr: https://github.com/atom/language-ruby/pull/297
But nothing happened

**Comment by SampsonCrowley** [comment]
@icecream17  I saw that and I was quite hopeful, but that was FOUR months ago now with the atom maintainer still not moving forward to help us out

**Comment by SampsonCrowley** [comment]
Also what's the point of having core languages be separate repos and packages if they still are required to be released inside of the main atom package schedule? not being able to release and update them as they are actually maintained seems like a real issue. if language-ruby has an update, it should be possible to update without waiting for a full release of atom...

**Comment by SampsonCrowley** [comment]
If it's that some packages are vital to the actual functionality of a specific atom release itself; then `language-ruby` should not be put in to that category. it should be put into a `standard`, `main` or `extra` category to denote that it comes directly from atom; not from the community, but it not a core package
