### ISSUE TITLE
Cannot open "about"

### ISSUE THREAD

**Issue by ThatXliner** [atom/atom#22203]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

Click on `About Atom`
<img width="569" alt="Screen Shot 2021-04-14 at 8 29 04 PM" src="https://user-images.githubusercontent.com/66848002/114810004-10404200-9d60-11eb-81e8-425d94d5dcab.png">

**Expected behavior:**

Opens the "about" page

**Actual behavior:**
makes a new empty file named "about" or "about:"

**Reproduces how often:**
100%

### Versions

Atom    : 1.56.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0
python 3.7.9
git 2.24.3

**Comment by sadick254** [comment]
I can't reproduce this @ThatXliner. Have you tried opening atom in safe mode, or reinstalling atom?

https://user-images.githubusercontent.com/5238135/114818309-41525e00-9dc4-11eb-840b-40a61e29d453.mov

**Comment by joseppinilla** [comment]
Had the same issue in Windows after updating from Atom 1.55 to 1.56 through the app.
Reinstall didn't fix it. Issue didn't come back after uninstalling, deleting `~/.atom` and installing again.

**Comment by ThatXliner** [comment]
Didn't I add it though?

**Comment by ThatXliner** [comment]
Latest version doesn't fix it

**Comment by ThatXliner** [comment]
...even in safe mode

**Comment by icecream17** [comment]
Maybe try doing it in `atom --dev` and looking at the console (ctrl+shift+i) to see if any errors pop up
