### ISSUE TITLE
Deprecated calls electron  1.56

### ISSUE THREAD

**Issue by yuriydzobak** [atom/atom#22211]
### Description

Upgrade atom from 1.55 to 1.56 that shows an error

**Expected behavior:**

**Actual behavior:**

<img width="658" alt="image" src="https://user-images.githubusercontent.com/70581130/114996884-f873d580-9ea7-11eb-95f4-28e74422d0f7.png">

**Reproduces how often:**

### Versions

```
$ atom --version
Atom    : 1.56.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
$ apm --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0
python 2.7.16
git 2.31.1
```

**Comment by blackr2d** [comment]
Seems to be a duplicate of [22208](https://github.com/atom/atom/issues/22208).

**Comment by yuriydzobak** [comment]
thank you
