### ISSUE TITLE
Discoloured php/js variables

### ISSUE THREAD

**Issue by MichaelOdita** [atom/atom#22237]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

php variables '$' symbols are displayed in white, same with css written inside php <style> code, 
### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

### Versions
1.56.0

### Additional Information

There aren't any errors in my code, everything works fine but I just hate the new color. 
![Screenshot (13)](https://user-images.githubusercontent.com/82849835/115316342-16279000-a171-11eb-9235-25ce7a645991.png)
![Screenshot (14)](https://user-images.githubusercontent.com/82849835/115316344-16c02680-a171-11eb-90e7-dd9011e7b69c.png)

**Comment by denisdeoniss** [comment]
#

**Comment by denisdeoniss** [comment]
#22239 #22168
