### ISSUE TITLE
Indents do not show up

### ISSUE THREAD

**Issue by leopons** [atom/atom#22295]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

 **--> I do NOT reproduce the bug in safe mode, but I've tried disabling each of my packages one by one, and the bug comes from none of them (at least none of them _individually_). I did follow the debugging guide, so I don't know what to do anymore. I've come to ask for some help / some clues on what might be happening. Any info or idea might help me. Thanks !!**

### Description

The indents do not show up. They are here (the minimap actually displays them correctly, and you can see the indentation lines on the main window) but the code is always aligned to the top left on the main window. See screenshot : 

<img width="1139" alt="Capture d’écran 2021-04-28 à 11 04 35" src="https://user-images.githubusercontent.com/23342230/116380568-5ee7e480-a814-11eb-975b-123282adc5e1.png">

### Steps to Reproduce

Open a file with indents, or simply create a new file, write some whitespace characters followed by a non-whitespace character.

**Expected behavior:**

The indents show up on the main window

**Actual behavior:**

The indents do not show up on the main window

**Reproduces how often:**

100%

### Versions

Atom    : 1.56.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1

apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0
python 2.7.16
git 2.24.3

OS : Mac OS 11.1 on ARM Apple M1 chip

### Additional Information

My config: https://gist.github.com/leopons/88f7fdc8c9982244a5e4134ecf7ca67b

**Comment by ThatXliner** [comment]
Possible duplicate of #22202

**Comment by leopons** [comment]
Yes, it is. Thanks !
I close the issue and continue the discussion on #22202.
