### ISSUE TITLE
Hey @gopipofficial the best place to start would be https://github.com/atom/atom/blob/0f2975930e506785c05068a1c57934160e094e10/static/variables/octicon-mixins.less#L36-L48

### ISSUE THREAD

**Issue by Amirnateghi1** [atom/atom#22331]
Hey @gopipofficial the best place to start would be https://github.com/atom/atom/blob/0f2975930e506785c05068a1c57934160e094e10/static/variables/octicon-mixins.less#L36-L48

However looking at the direction that github took to [deliver octicons as svg rather than icon fonts](https://github.blog/2016-02-22-delivering-octicons-with-svg/), working on this would require a rework on how atom uses the icons.

Apologies I miss labeled this issue. If you are still willing to proceed working on this issue let me know.

_Originally posted by @sadick254 in https://github.com/atom/atom/issues/21049#issuecomment-703461841_

**Comment by sadick254** [comment]
@Amirnateghi1 Yes we are still open to have the svg icons on Atom. I would encourage you to open a PR and let's track progress on that PR instead of this issue. Once the PR is in a draft mode. Please reach out to me, I will take a look.
