### ISSUE TITLE
(electron) crashReporter.start is deprecated in the renderer process. Call it from the main process instead.

### ISSUE THREAD

**Issue by icecream17** [atom/atom#22423]
![image](https://user-images.githubusercontent.com/58114641/118221126-a7bdb100-b442-11eb-85ec-1bf2c1eef298.png)

I have to sleep rn, just creating this easy issue for later

**Comment by sadick254** [comment]
Hey @icecream17 could you provide more details on this.

**Comment by icecream17** [comment]
If I remember correctly, the steps are
`atom-beta --dev --safe` `ctrl+shift+i` --> console shows this warning

(Don't have access to editor right now)

**Comment by sadick254** [comment]
The console warning is rather strange, from the [electron docs](https://github.com/electron/electron/blob/v9.4.4/docs/api/crash-reporter.md) it should be fine to call `crashReporter` from both the `Main` and `Renderer` process. I don't think the warning is worth resolving for now, even on the latest electron version it's still ok to call `crashReporter` from both the `Main` and `Renderer` process. I will close this for now.
