### ISSUE TITLE
Change "File uses the *x* grammar" to "File uses *x* syntax"

### ISSUE THREAD

**Issue by hwittenborn** [atom/atom#22471]
When hovering over the button for syntax selection, it currently reads "File uses the [syntax] grammar".

I feel like it would fit better if it read "File uses [syntax] syntax" (i.e. "File uses Javascript syntax").

**Comment by icecream17** [comment]
"Syntax" does seem to be a more usual word than "grammar".
But internally, atom uses a `GrammarRegistry` https://github.com/atom/atom/blob/ea4cbb7e8433efdd74d969fe89b00d8470e8c58a/src/atom-environment.js#L122
I'm fine with both.

**Comment by ThatXliner** [comment]
We just need to edit this line:

https://github.com/atom/atom/blob/9a84b67e272291afdc27ab941cebcb2264bbbf22/packages/grammar-selector/lib/grammar-status-view.js#L107

To implement that

**Comment by hwittenborn** [comment]
Is there a consensus on if it should be changed then? (I'm down for it of course)

**Comment by icecream17** [comment]
Note: See #22476, especially Sadick's comment

**Comment by sadick254** [comment]
Closing this due to this comment. https://github.com/atom/atom/pull/22476#issuecomment-849312665
