### ISSUE TITLE
<!-- Please make sure you are posting an technical issue related to Dogecoin Core. -->

### ISSUE THREAD

**Issue by Codingprodigy-tech** [atom/atom#22505]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

__Originally posted by @gator6615 in https://github.com/dogecoin/dogecoin/issues/2199__

**Comment by sadick254** [comment]
Possibly a spam issue.
