### ISSUE TITLE
Issue publishing a package for a language grammar

### ISSUE THREAD

**Issue by iamtheblackunicorn** [atom/atom#22529]
I wrote a package to give syntax highlighting to a custom language I have written an interpreter for and I wanted to publish my custom grammar for Atom package on Atom but it doesn't work. I followed the guide and everything seems to be in order. 
Here's a link to the source code of my grammar: https://github.com/iamtheblackunicorn/language-chromos
Here's a link to the tutorial I followed: https://flight-manual.atom.io/hacking-atom/sections/publishing/
And here's the error I am getting:
```text
Registering package in iamtheblackunicorn/language-chromos repository failed: That repo does not exist, isn't an atom package, or you do not have access
```

**Comment by icecream17** [comment]
Maybe this is the reason? <sub>(This is the first thing I found. It's a pretty silly reason)<sub>

![image](https://user-images.githubusercontent.com/58114641/120493957-0363c600-c381-11eb-933e-2c68e5b1eec4.png)

Your version is `1.0.0`

https://github.com/iamtheblackunicorn/language-chromos/blob/main/package.json#L3

**Comment by sadick254** [comment]
Try renaming the default branch to `master` and then try again.

**Comment by iamtheblackunicorn** [comment]
@icecream17 Oh, ok am I not allowed to have an initial version of `1.0.0`? That is kinda silly but I'll try changing it and reporting back what happened here! Thank you very very much!🙏 @sadick254 If the suggestion of @icecream17 fails, I will try your suggestion! Thank you so much! I'll try the suggested solutions you two posted here and then let both of you know as soon as possible what happened!!

**Comment by iamtheblackunicorn** [comment]
@icecream17 @sadick254 So apparently doing what you guys suggested at the same time worked for me and my packages is now live! Here's the link: https://atom.io/packages/language-chromos
Thanks once again for all your help! ❤️
