### ISSUE TITLE
I cant download any extension 

### ISSUE THREAD

**Issue by RealYusufIsmail** [atom/atom#22599]
For example i get this error 

Installing “TabNine@3.0.3” failed.Hide output…

npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/YusufIsmail/.atom/.apm/_logs/2021-06-14T22_09_35_728Z-deb

**Comment by ThatXliner** [comment]
What command are you using? `apm install tabnine`

**Comment by RealYusufIsmail** [comment]
I am doing it throgh the app

**Comment by Loom4k** [comment]
You should try uninstalling Atom completely and reinstalling it. Works most of the time. Also restart your pc. These are very basic and quick fixes. If it still doesn't work try using the terminal command as @ThatXliner said. Hope this can help a bit.
