### ISSUE TITLE
Atom cant open in browser

### ISSUE THREAD

**Issue by mhdhafizddin** [atom/atom#22592]
Hi sorry for asking as im newbie in this field. Trying to learn. My atom file cant update the new one whenever i click the html file once i finish the format html. But if i type in notepad, and then save it. It work well with the current update. How to solve this ya? Thankyou in advance guys

**Comment by ThatXliner** [comment]
This should be asked in [discussions](https://github.com/atom/atom/discussions) *first*. If it then seems like a bug, report it here.
