### ISSUE TITLE
XML file error

### ISSUE THREAD

**Issue by porg13231** [atom/atom#22604]
I can not download atom nightly because there is a XML file error. Please fix.

**Comment by icecream17** [comment]
I don't think Atom Nightly's been released in a while. In fact I think Atom Beta is the latest version,,,?

**Comment by sadick254** [comment]
@porg13231 This has now been resolved.

**Comment by 1zizi1** [comment]
@sadick254 I still can't download Atom.

It gives this error: `This XML file does not appear to have any style information associated with it. The document tree is shown below.`

https://atom-installer.github.com/v1.57.0/AtomSetup-x64.exe?s=1620674356&ext=.exe

**Comment by sadick254** [comment]
We are working on a fix for windows. Hopefully we should have a fix soon.
