### ISSUE TITLE
Atom downloads not working from atom.io

### ISSUE THREAD

**Issue by UziTech** [atom/atom#22650]
### Description

Downloading Atom does not work when clicking download from atom.io or going to https://atom.io/download/deb?channel=stable

### Steps to Reproduce

1. Go to https://atom.io on windows or linux (not sure if mac is also failing)
2. Click Download

**Expected behavior:**

Download Atom

**Actual behavior:**

Redirects to url: https://atom-installer.github.com/v1.57.0/AtomSetup-x64.exe?s=1620674356&ext=.exe
Error:

```
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:62130dd9-601e-0022-76f9-69e77a000000 Time:2021-06-25T19:40:05.7100940Z</Message>
</Error>
```

**Reproduces how often:**

100%

### Additional Information

https://github.com/UziTech/action-setup-atom/issues/222

**Comment by ThatXliner** [comment]
I can download when clicking "download" from atom.io, but I get the 
```xml
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:a8f7c16f-601e-001d-5c12-6a2fd9000000 Time:2021-06-25T22:36:43.8373033Z
</Message>
</Error>
```

(I get redirected to https://atom-installer.github.com/v1.57.0/atom-amd64.deb?s=1620674304&ext=.deb, as well)

**Comment by pingogamer543** [comment]
You can put the download file? here?

**Comment by TheMartinfer22** [comment]
Even here, I used the download directly https://github.com/atom/atom/releases/tag/v1.57.0

**Comment by mimi89999** [comment]
```
$ curl -L https://atom.io/download/windows_x64
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:7d08d495-301e-005d-3e62-6a28e1000000
Time:2021-06-26T08:05:31.5448540Z</Message></Error>
```

**Comment by lannasmind** [comment]
I need to be able to download Atom and I am having the same issue as everyone else here. I am new and trying to complete bootstrap 4 courses.

**Comment by icecream17** [comment]
I managed to install atom with chocolatey

`choco install atom`

(atom beta)
`choco install atom --pre=True`

**Comment by lannasmind** [comment]
just to be clear is Choco atom a good temporary substitute for atom ? if so than I am gonna try to download now and thank you so much for helping me out

**Comment by darangi** [comment]
Thanks for reporting 🙇🏾‍♂️ 

it has been resolved, you can now download from https://atom.io
