### ISSUE TITLE
Suggest an idea for this project. If this doesn’t look right,

### ISSUE THREAD

**Issue by kabirkhan98** [atom/atom#22660]

**Comment by kabirkhan98** [comment]
> ## Summary
> ## Motivation
> ## Describe alternatives you've considered
> ## Additional context

**Comment by kabirkhan98** [comment]
Suggest an idea for this project. If this doesn’t look right,

**Comment by kabirkhan98** [comment]
Suggest an idea for this project. If this doesn’t look right,

**Comment by kabirkhan98** [comment]
> []() @mojombo

**Comment by kabirkhan98** [comment]
1. @mojombo

**Comment by kabirkhan98** [comment]
@schacon

**Comment by kabirkhan98** [comment]
@caged

**Comment by kabirkhan98** [comment]
@defunkt

**Comment by kabirkhan98** [comment]
@kabirkhan98

**Comment by kabirkhan98** [comment]
@mojombo

**Comment by ThatXliner** [comment]
Oh no

**Comment by ThatXliner** [comment]
Someone lock this (cc @sadick254 maybe ;-;)

**Comment by icecream17** [comment]
There should be a `spam` tag
