### ISSUE TITLE
Problem fetching and pulling data from GitHub

### ISSUE THREAD

**Issue by Chaxiraxi** [atom/atom#22673]
### Discussed in https://github.com/atom/atom/discussions/22668

<div type='discussions-op-text'>

<sup>Originally posted by **Chaxiraxi** June 27, 2021</sup>
# Problem fetching and pulling data from GitHub
Hi !

I have a problem when I want to pull and fetch my remote repo to my local repo.
It works fine in cli, and correctly fetch and pull my repo, but when I do it in Atom, it simply doesn't work and give me this error:
`fatal: couldn't find remote ref refs/heads/main`

Someone can tell me why it goes wrong ?
PS: It doesn't work with any repo, and I can commit and push in Atom without problems btw</div>
Let me know if you want some additionnal infos to help to fix this issue

**Comment by Chaxiraxi** [comment]
Well, that's the reason why it makes no sense for me, because there's no reason to fail, and when I'm using Git in a terminal, it works fine without problem, but when I fetch or pull from Atom, it give me this error. I can give you my system configuration if it can help 

Operating System : ParrotOS (a Debian based distro)
CPU: Intel core i3 8th gen 4.00 Ghz
GPU: NVIDIA GTX 1660 SUPER
Motherboard: MSI (idk which model)
RAM: 16 go 2660 Mhz (idk which brand)

I have a dual boot with Windows 10, I didn't tried if it works there. I can try if you want to see if it's a mistake that I did somewhere, or if it's really a bug with the OS I'm using

**Comment by kkanekii** [comment]
This is not a hardware issue, try using your dual windows boot
