### ISSUE TITLE
Can only open one file at a time.

### ISSUE THREAD

**Issue by Nihal247** [atom/atom#22696]
I work on multiple files at a time, but Atom only opens one file at a time, whereas other text editors allow multiple files to get opened at the same time.

Whenever I open another file, while already working on one file, it overlaps the current file, and the project on which I earlier work goes.  This sometimes becomes very frustrating.

I want to suggest that we shall be able to open multiple files in Atom, instead of only one file at a time. Is there a way to do that? if not, this feature is required.

Thank you in advance.

**Comment by ThatXliner** [comment]
Do you mean you want to [split the pane](https://flight-manual.atom.io/using-atom/sections/panes/)?

**Comment by Nihal247** [comment]
Yes, thanks for it!
