### ISSUE TITLE
Error while installing packages

### ISSUE THREAD

**Issue by TarunVuta** [atom/atom#22690]
i am getting the below error when installing package. can someone guide me to solve this

**npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! Unexpected end of JSON input while parsing near '...5f3ca35761e47e05b206c'

npm ERR! A complete log of this run can be found in:
npm ERR!     [E:\Users\tarun\.atom\.apm\_logs\2021-07-05T07_44_18_428Z-debug.log]**

[2021-07-05T07_44_18_428Z-debug.log](https://github.com/atom/atom/files/6762885/2021-07-05T07_44_18_428Z-debug.log)

**Comment by sadick254** [comment]
@TarunVuta Which package are you trying to install?

**Comment by TarunVuta** [comment]
@sadick254 linter-eslint, atom-beautify, atom-ternJS etc. since it was failing through installer i tried to do it manually(PowerShell, npm). it worked but with a bunch of warnings.

**Comment by kkanekii** [comment]
@TarunVuta what node version are u using

**Comment by TarunVuta** [comment]
@kkanekii v16.4.2

**Comment by kkanekii** [comment]
Try re installing
