### ISSUE TITLE
Un install Atom

### ISSUE THREAD

**Issue by askhangwle** [atom/atom#22706]
hey How to UN install atom? as I uninstalled it from control panel and deleted all its traces in C drive and reg keys but it still reinstall itself after reboot the following day
appreciate your help !
Thanks

**Comment by kkanekii** [comment]
Go to your users and delete .atom, delete the files from appdata, and programdata and every other place you can think of, It usually doesn't re install, just delete the installer first

**Comment by Nihal247** [comment]
Go to the file location of Atom (C:\Users\_username_\AppData\Local\atom), and delete everything. Next uninstall it from the Control Panel, it will tell you to **Remove it from Program and Features List**, click **OK**. Then delete .atom file from your username folder. If you have a shortcut on your desktop, it may be there. Just double click on it and you will get the message that **The App Wasn't Found**, click **Delete**.

**Comment by Nihal247** [comment]
Go to the file location of Atom (C:\Users\_username_\AppData\Local\atom), and delete everything. Next uninstall it from the Control Panel, it will tell you to Remove it from Program and Features List, click OK. Then delete .atom file from your username folder. If you have a shortcut on your desktop, it may be there. Just double click on it and you will get the message that The App Wasn't Found, click Delete.

**Comment by askhangwle** [comment]
thanks guys but I have already tried all these few times but still no luck and Atom launches itself next morning

**Comment by Nihal247** [comment]
Is it the case only for Atom?

**Comment by kkanekii** [comment]
@Nihal247 ive seen you comment over every single issue in this repo, take a chill man

**Comment by askhangwle** [comment]
I wanted to give feedback on the fix advised by members here otherwise how would they know whats working/not working

**Comment by askhangwle** [comment]
sorry disregard my above message

**Comment by Nihal247** [comment]
Yes @kkanekii, I'll take a chill!

**Comment by Nihal247** [comment]
@askhangwle, I would suggest you to try uninstalling it from Command Prompt.

Please refer to this article https://www.howtogeek.com/702540/how-to-uninstall-a-program-on-windows-10-from-command-prompt/, I hope it works for you!

**Comment by askhangwle** [comment]
I have tried that but the problem is Product get name command doesn't even show Atom as an installed app
used powershell as well still no luck

**Comment by kkanekii** [comment]
Try running a search with the word atom, and delete every single file

**Comment by askhangwle** [comment]
that worked thanks guys

**Comment by sadick254** [comment]
@askhangwle I am closing this, it seems the issue you were facing has been resolved.
