### ISSUE TITLE
"Your Hydrogen config is broken: startupCode. SyntaxError: Unexpected token P in JSON at position 1"

### ISSUE THREAD

**Issue by AtomicNess123** [atom/atom#22748]
I quickly wanted to ask about this error. How to tackle it? Where can I find the JSON file it refers to? Thanks.

![image](https://user-images.githubusercontent.com/47029233/126131920-5b617b3b-6fd0-4397-ab21-32a065b0a6cb.png)

**Comment by kazaksaeed** [comment]
> سریع خواستم در مورد این خطا س askال کنم. چگونه می توان با آن مقابله کرد؟ فایل JSON که به آن اشاره دارد را از کجا می توانم پیدا کنم؟ با تشکر.
> 
> ![تصویر](https://user-images.githubusercontent.com/47029233/126131920-5b617b3b-6fd0-4397-ab21-32a065b0a6cb.png)

**Comment by darangi** [comment]
Hello, we do not maintain hydrogen.
