### ISSUE TITLE
Upgrade Electron

### ISSUE THREAD

**Issue by brettz9** [atom/atom#22765]
## Summary

Upgrade to Electron 12+

## Motivation

Earlier Node versions were buggy about ESM imports. Linter is causing our plugin `eslint-plugin-jsdoc` to crash (due to our depending on a package which uses nested `exports` paths).

(There is of course other good stuff in Node 14.)

## Describe alternatives you've considered

Reverting our package to depend on a version with some bugs in the dependency we require. 

## Additional context

I know your upgrades are based on more than just one plug-in, but proper functioning of ESM is compelling as packages may now use this format natively and Node advertises support in its LTS versions (including for the Node 12 that you currently use, but that is an older less patched version).

**Comment by icecream17** [comment]
It's not easy to upgrade - the actual pr for this is here: https://github.com/atom/atom/pull/22687

**Comment by brettz9** [comment]
Thanks. I think I might have found a workaround on our end. But would be great to come through.

**Comment by ioquatix** [comment]
@brettz9 what was your workaround?

**Comment by brettz9** [comment]
In our case, the original package was amenable to exporting what we needed for now in a non-nested way.
