### ISSUE TITLE
Atom Core Packages Failed 

### ISSUE THREAD

**Issue by paulkckho** [atom/atom#22782]
I tried reinstalling this program multiple times over the past 48 hours. I had even temporary disable my firewall. Nothing worked. I need a solution to this problem ASAP. Without this "electron" package Atom is unstable and crashes frequently. 
![Atom core packages install failures](https://user-images.githubusercontent.com/72099759/127386483-3f9f7675-9841-4c94-8776-39addb55615e.jpg)

**Comment by sadick254** [comment]
@paulkckho `Spectral-selection` package has been deleted by the owner. https://github.com/Tizoner/Spectral-selection. Unfortunately, there is nothing we can do about it. You can try to look out for alternatives. Am closing this since it is not something within our capability to resolve.
