### ISSUE TITLE
A certain package is crashing Atom 

### ISSUE THREAD

**Issue by HadasKharilker** [atom/atom#22803]
### Description
When uninstalling the pigments package and install it again (right away) Atom is crashing

### Steps to Reproduce

1. go to install package window
2. uninstall pigments package
3. install pigments package again

**Actual behavior:**
Atom is crashing

**Reproduces how often:**
Reproduces all the time

100%

_### Versions_
**Atom version** 1.58.0X64
**pigments version** 0.40.6
**OS version** -Edition	Windows 10 Home
Version	21H1
Installed on	‎3/‎16/‎2021
OS build	19043.1110
Serial number	PF10DYR7
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by ASMaksimov2007** [comment]
Reproduced with latest Atom and Win10. This is certainly a bug.

**Comment by darangi** [comment]
Could you report this issue in the pigment repo? We do not maintain that package

**Comment by HadasKharilker** [comment]
Yes of course

**Comment by darangi** [comment]
Thanks!
