### ISSUE TITLE
[devtools] Debugging gets silently disabled

### ISSUE THREAD

**Issue by pritambaral** [atom/atom#2282]
React editor. Happened while trying to debug #2186

Very specific steps to reproduce:

1) Open up `app/src/editor.js` in _Sources_
2) Place a breakpoint on the first line after `Editor.prototype.insertText = ...`
3) Paste using `Ctrl+V`

This breakpoint should fire on every insert. Even if I stop trying to paste, and try to input a single character, insertText should fire, thus this breakpoint should too.

**Comment by benogle** [comment]
Closing as this no longer seems to be an issue.
