### ISSUE TITLE
I really love this icon!

### ISSUE THREAD

**Issue by jen801** [atom/atom#22839]
I really love this icon!
Thank you 🙏🏻
<img width="363" alt="Schermata 2021-04-24 alle 01 17 22" src="https://user-images.githubusercontent.com/35035423/115938414-d6c3b100-a49a-11eb-8759-8078ebcfe908.png">

_Originally posted by @ludovicobesana in https://github.com/atom/atom/issues/21128#issuecomment-825988545_

**Comment by heynan0** [comment]
That looks nice. Is there an actual issue to be addressed in this Issue or can we close?
