### ISSUE TITLE
Atom consuming 1.5gb of ram on idle.

### ISSUE THREAD

**Issue by Mehul-N265** [atom/atom#22871]
Atom the hackable editor is consuming lots of ram. Maybe its happening due to more ram used by css.

**Comment by haneenmahd** [comment]
More of the consumed ram is caused by electron/chromium

**Comment by Mehul-N265** [comment]
But this is not the case with visual studio code which also uses
electron/chromium. It consumes barely 500-700mb on idle.

**Comment by haneenmahd** [comment]
But, vscode optimises the ram usage.
