### ISSUE TITLE
No atom gui arch linux

### ISSUE THREAD

**Issue by Senpai-10** [atom/atom#22898]
I installed atom package from the `arch community repo` 
when i run atom nothing happens

i ran this command `top -b -n1 | grep atom` to make sure if atom is still running and it's still running

**Output**

```
  15132 senpai    20   0    7388   2052   1480 S   0.0   0.1   0:00.00 atom
  15135 senpai    20   0 4900020 191628  97980 S   0.0   4.8   0:02.58 atom
```

## System info

OS: `Arch Linux x86_64`
Kernel: `5.13.10-arch1-1`
window manager: `bspwm`

## Atom info

`atom -v`

Atom    : `1.58.0`
Electron: `9.4.4`
Chrome  : `83.0.4103.122`
Node    : `12.14.1`

**Comment by DeeDeeG** [comment]
Works for me.

Atom is `1.58.0-1` from the Arch community repos.
OS is Manjaro 21.1.1 Xfce edition, live .iso loaded in VirtualBox.

Can you try doing `killall atom` in terminal? And then you can run `/usr/lib/atom/atom` directly and see if there is any useful terminal output? (Usually `atom` is launched from a launcher script that lives at `/usr/bin/atom` as it's packaged for Arch Linux users. `/usr/lib/atom/atom` is the actual Electron binary for Atom, and if run directly, it will output any warnings/errors to the console. There are currently some known deprecation notices affecting Atom 1.58 with Electron 9, so feel free to disregard those repetitive messages about the same deprecation warning.)

**Comment by Senpai-10** [comment]
Now i get 

```
App threw an error during load
[stdin]:6:13: error: missing "
    userId: "240b3e73-bab8-4bf9-b229-504068fc7575
            ^
missing "
[stdin]:6:13: error: missing "
    userId: "240b3e73-bab8-4bf9-b229-504068fc7575
```

**Comment by alerque** [comment]
This is not an issue with Atom upstream project, if you still have an issue with the current Arch Linux packages please report it to the Arch Linux bug tracker (link from the package page). I believe this issue is obsolete and can be closed (I say this as the downstream Arch Linux maintainer).
