### ISSUE TITLE
.octicon-font-legacy() {   font-family: 'Octicons Regular';   src: url("icons/octicons-2.1.2.woff") format("woff");   font-weight: normal;   font-style: normal; }   .octicon-font() {   font-family: 'Octicons Regular';   src: url("icons/octicons.woff") format("woff");   font-weight: normal;   font-style: normal; }

### ISSUE THREAD

**Issue by JpD9119** [atom/atom#22919]
https://github.com/atom/atom/blob/0f2975930e506785c05068a1c57934160e094e10/static/variables/octicon-mixins.less#L36-L48

**Comment by hamdan33-com** [comment]
I don't know anything, because I'm a beginner, maybe I clicked wrong


Pada tanggal Rab, 1 Sep 2021 12.52 PM, Sadick ***@***.***>
menulis:
