### ISSUE TITLE
I'm not able to open my project

### ISSUE THREAD

**Issue by thecuteadegoke** [atom/atom#22923]
so i just joined the app dev team and my first project after saving with .py refuse to open, the command prompt keeps shutting down. Pls what can i do

**Comment by lildaddy423** [comment]
sounds like you aint got the right commands are you using if elif and else?

Sent from Yahoo Mail on Android 
 
  On Wed, Sep 1, 2021 at 8:52 PM, ***@***.***> wrote:   


so i just joined the app dev team and my first project after saving with .py refuse to open, the command prompt keeps shutting down. Pls what can i do

**Comment by icecream17** [comment]
Maybe the terminal finishes before anything happens?
How are you running the file?

**Comment by sadick254** [comment]
This is possibly spam.

**Comment by thecuteadegoke** [comment]
Its correct. Whenever I try to open my program from my file explorer I
shows a black screen and disappears immediately.

**Comment by thecuteadegoke** [comment]
My linr of code is correct sir, the main problem is that whenever I try
opening my program from file explorer it pops up a black screen and
disappears immediately. And have downloaded script and am working with a
Windows 10 computer.

**Comment by thecuteadegoke** [comment]
What do you mean by spam please?? The problem I noticed is that whenever I
try to open my .py file from file explorer it pops a black screen and goes
away immediately. And have downloaded script it still isn't working.
