### ISSUE TITLE
Same error on Windows and Atom 1.58.0

### ISSUE THREAD

**Issue by best-lucky1030** [atom/atom#22927]
Same error on Windows and Atom 1.8

(without the `gvfs-trash` reference)

_Originally posted by @gdlx in https://github.com/atom/tree-view/issues/799#issuecomment-226453619_

**Comment by the-j0k3r** [comment]
atom 1.8?

**Comment by best-lucky1030** [comment]
@the-j0k3r 
it's Atom version.
This error was from `https://github.com/atom/tree-view/issues/799#issuecomment-226453619`

**Comment by the-j0k3r** [comment]
> it's Atom version.

I'll assume that you meant 1.58.0 because there is no Atom version 1.8.

>  This error was from https://github.com/atom/tree-view/issues/799#issuecomment-226453619

And again have you tried the workarounds posted?

**Comment by best-lucky1030** [comment]
not yet.
I tried to find the answer, but couldn't get it.
If you have any solutions, please let me know.

**Comment by the-j0k3r** [comment]
The solution here https://github.com/atom/tree-view/issues/799#issuecomment-238135395 and https://github.com/atom/tree-view/issues/799#issuecomment-257256214 and others work.

Have you tried it or not?

**Comment by best-lucky1030** [comment]
@the-j0k3r 
As I mentioned at the title, my OS is not Ubuntu, it's Windows.
So I couldn't try it.

**Comment by the-j0k3r** [comment]
You need to post atom logs, something more to action the issue, this report is nowhere helpful to action cause not everyone may be able to dupe the issue.

**Comment by best-lucky1030** [comment]
@the-j0k3r 
okay. thanks. will close this issue and post atom logs.
