### ISSUE TITLE
Bootstrap syntax error

### ISSUE THREAD

**Issue by iggy12345** [atom/atom#22969]
Hi,

Before we start, I'm fully aware that atom is only supported on Linux 64-bit however, I know that JavaScript runs on bytecode, which is universal, so I'm trying to install it for an i386 machine by installing it from source. If I'm wrong, please explain.

But when I run `./script/boostrap` I get an error about an unexpected error 

Ill add a screenshot in a bit, but the gist is that there's an unexpected token 

`verify-machine-requirements.js:97`

```
} catch {}
        ^

Unexpected token {
```

# Edit
Here's a dump of the error

```
/home/aaron/Workspace/atom-1.58.0/script/lib/verify-machine-requirements.js:97
      } catch {}
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/aaron/Workspace/atom-1.58.0/script/bootstrap:14:35)
```

**Comment by DeeDeeG** [comment]
Hi,

This is a syntax error in Node earlier than 10.0.0.

Older Node isn't supported in Atom's build scripts... But it's a little ironic for the system requirements checker to error out on older Node versions. We should at least support older Node in the system requirements checker so we can print an appropriate error... (In this case, we'd be printing an error about your system's Node being too old an unsupported!)

See: [Optional catch binding added in V8 version 6.6](https://v8.dev/blog/v8-release-66#optional-catch-binding) --> [V8 version 6.6 adopted for Node 10.0.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.0.0).

JavaScript authors used to have to bind the error to some variable when writing a `catch` block.

e.g.:

```js
catch (e) {
  // maybe do something with e here... or maybe don't
}
```


As of ECMAScript 2019 (and V8 engine version 6.6, and Node 10.0.0), you can omit the error binding if you're not going to use the bound error for anything, e.g.:

```js
catch {
  // We're not going to do anything with the error, don't bother binding it to a variable such as e
}
```

**Comment by DeeDeeG** [comment]
I posted a pull request to fix the error, but for now please use Node 10.12 or newer to build Atom.

I haven't checked if it works on Linux 32-bit, so I'm curious about your results if you do try it again.

**Comment by iggy12345** [comment]
I will give it a shot, I'm compiling pytorch from source right now, so my pentium is a bit occupied at the moment

**Comment by iggy12345** [comment]
It looks like I can't just 'install' node 10.12.0 because it's only offered for x64, but I will see if I can compile it from source
