### ISSUE TITLE
Atom version not properly displayed

### ISSUE THREAD

**Issue by aegypius** [atom/atom#2298]
@probablycorey ask me to report this issue from [discuss.atom.io](http://discuss.atom.io/t/atom-version-not-properly-displayed/9390) 

> I managed to build a working version of Atom for Gentoo Linux but I can't get the
> proper Atom version in Help menu (Version 0.1.0 is displayed instead of 0.96.0).
>
> I tried to understand the way the menu was generated and, if I understood correctly,  it seems to read Atom package.json version which seems good :
>
```json
{
  "name": "atom",
  "productName": "Atom",
  "version": "0.96.0-7410f9a",
  "description": "A hackable text editor for the 21st Century.",
  "main": "./src/browser/main.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/atom/atom.git"
  },
  ...
}
```
> Have I missed something ?

I should mention that atom-shell is build standalone and I run atom this way : 

    $ /usr/share/atom-shell/atom /usr/share/atom 
    $ echo $ATOM_RESOURCE_PATH
    /usr/share/atom
---
Atom Commit: 7410f9a
OS Version: Gentoo Linux ([Unofficial overlay build](https://github.com/aegypius/overlay/tree/master/app-editors/atom) - aegypius/overlay#7)

**What steps will reproduce the problem?**
1. Launch Atom
2. Click Help Menu 

**What is the expected result?**

Version 0.96.0

**What happens instead?**

Version 0.1.0 is displayed

**Comment by mnquintana** [comment]
Gonna close this one out - please feel free to comment / reopen if you can reproduce this with the latest version of Atom (0.209.0).
