### ISSUE TITLE
Updatation on Linux ( Ubuntu )

### ISSUE THREAD

**Issue by TypeHrishi** [atom/atom#23050]
Hii
I installed the latest 'Atom' Editor using the .deb file on my Ubuntu Desktop
The question I have is that,
To update it:
I will need to remove the first version and then download the latest from the site and install again!?
Or It'll automatically update in the 'Update Manager' or basically ```sudo apt update; sudo apt upgrade```

If it will not upgrade automatically,
I'll use Flatpak/Flathub

**Comment by YATHARTH-Codr** [comment]
*Unsubscribe*

**Comment by TypeHrishi** [comment]
WHAT!?

**Comment by TypeHrishi** [comment]
ILL USE FLATPAK NVM

**Comment by TypeHrishi** [comment]
nvm ill use deb
