### ISSUE TITLE
Use Shift+Ctrl+ instead of cmd-shift- in documentation when applicable

### ISSUE THREAD

**Issue by PanderMusubi** [atom/atom#2308]
On non-OS X systems, please use Shift+Ctrl+ etc. in documentation instead of cmd-shift-.

For example welcome.md refers to cmd-shift-p but on Linux on a non-Apple based machine all the menu items show shortcuts called Shift+Ctrl+P. To properly match documentation with offered menu items and shortcuts, please use the correct shortcut format in documentation included in a build for Linux on non-Apple based machines.

**Comment by 50Wliu** [comment]
Closing this in favor of atom/docs#16, please subscribe there for updates.
