### ISSUE TITLE
Possible M1 Mac build

### ISSUE THREAD

**Issue by ReturnRei** [atom/atom#23113]
## Summary

Apple Silicon M1 build

## Motivation

Performance and efficiency are better when running native code

## Describe alternatives you've considered

Running Atom with Rosetta translation
Running a proprietary IDE

## Additional context

As far as I understand every dependency is available for a M1 native build, if I'm correct it shouldn't be that complicated to get a working native build, but tinker with config files is necessary.

Tried to do it myself but have no real experience with js
Will continue to look into the config and update if I find anything relevant

**Comment by kevingrabher** [comment]
See: #22023
