### ISSUE TITLE
Editor Does Not Preview / Edit Files on Network Drive

### ISSUE THREAD

**Issue by ozone702** [atom/atom#2313]
OS: Windows 7
Atom Version: 0.95.0-3f0640f

Hosting files on a network drive (i.e. \network\private\myfiles) and opening files in atom does not show anything.  Files list on left pane and a tab opens up in editor, but tab is empty and shows nothing.

Additional Note:  I tested using a mapped drive and it worked.  It appears there's an issue running atom in Windows and trying to open files on a network path.

**Comment by okoetter** [comment]
Why has this been closed? I still see this on 0.166.0

**Comment by GomatoX** [comment]
Still crashing using network drive. v0.174.00

**Comment by 50Wliu** [comment]
Re-opening because it looks like some people are still having issues.

**Comment by GomatoX** [comment]
Any plans for fixing this problem?

**Comment by jerone** [comment]
I'm having the same problem with all my text files. I do however can open images (`.png` & `.gif`).

**Comment by jerone** [comment]
@jerone commented on [20 jan. 2015 14:32 CET](https://github.com/atom/atom/issues/2313#issuecomment-70653160 "2015-01-20T13:32:00Z - Replied by Github Comment Enhancer"):
> I'm having the same problem with all my text files. I do however can open images (`.png` & `.gif`).
> 
> Windows 8.1
> Atom 0.174.0

After inspection (running `--safe`-mode and enabling/disabling all packages) this seems only related to atom-editorconfig package. Reported here: https://github.com/sindresorhus/atom-editorconfig/issues/28

**Comment by okoetter** [comment]
I indeed had editorconfig installed. I disabled it but that did not help. Uninstalled it and restarted Atom and it seems so work now.

**Comment by jerone** [comment]
@okoetter commented on [21 jan. 2015 09:20 CET](https://github.com/atom/atom/issues/2313#issuecomment-70800136 "2015-01-21T08:20:40Z - Replied by Github Comment Enhancer"):
> I indeed had editorconfig installed. I disabled it but that did not help. Uninstalled it and restarted Atom and it seems so work now.

Disabling a package doesn't disable the package completely. A restart of atom is required for it to fully disable. It would be nice if you can add your support to https://github.com/sindresorhus/atom-editorconfig/issues/28 so it gets more attention from the developers.

**Comment by gsklee** [comment]
Having the same issue as well. Guess I'll give up using Atom with NFS.

**Comment by E-Unit** [comment]
I appologize for the newbie question here. I am quite sure I have fs-pluse 2.5 on my system. Atom keeps crashing when trying to open a networked file. I don't know if it helps to treat network files as absolute or not but the thing is. I'm not sure how to do that. I would love to say I'm on Linux but I'm using it at work on a windows 7 pc. Any help is appreaciated. 
I did read just further up that the issue had been closed and re-opened again.
I would really appreaciate any help, I enjoy editing out G-Code for our cnc's quite a bit with the G-Code package thanks to audreyt

**Comment by jerone** [comment]
Do you have [EditorConfig](http://editorconfig.org) installed [too](https://github.com/atom/atom/issues/2313#issuecomment-70799163)?

**Comment by E-Unit** [comment]
no I did not... just actually installed it (I'll laugh if I wasn't supposed to)

**Comment by awayken** [comment]
:frowning: I'm having this issue, too.

**Comment by iamstarkov** [comment]
Editrconfig fixed the issue on its side 13 march sindresorhus/atom-editorconfig#28. Is it still an issue?

**Comment by awayken** [comment]
Works for me!

**Comment by adalisan** [comment]
I don't have editorconfig installed. and atom crashes constantly with files on NFS.
This is Windows 7 and atom 1.0.6

**Comment by pke** [comment]
Running into this every single day. Working on a OSX samba share.

**Comment by jonasflint** [comment]
Also running into this. Crashes constantly, especially when saving to.  On Mac OSX el capitan, using a mapped network ubuntu share.

**Comment by sfinevelir** [comment]
Having this issue as well. OS X El Capitan, connecting to a mapped Windows 7 share.

**Comment by trickpattyFH20** [comment]
Samesies. OSX 10.11.2. Atom 1.5.4. We work on a samba share mounted volume.

Performance has pretty much been killed for me after upgrading from Atom 1.3 to 1.5. Switching between files now takes 10+ seconds, keyboard shortcuts also give me delays of 10+ seconds.

Does anyone have any tips for what editors work well with samba?

**Comment by jjmorse** [comment]
Also facing this issue on macOS Samba shared folder mapped as a network drive in Windows 10.

**Comment by ozone702** [comment]
I use Visual Studio Code now.  It uses Electron and Atom Shell Archive.  It is feature packed, multi-platform, and has a plethora of extensions to do just about anything you want it to.

I'm tempted to close this issue because of this but realize there are others who will use Atom for things that VS Code might not be able to do.  What those things might be, I have no idea.
