### ISSUE TITLE
Indent guides mess up with mixed indentation

### ISSUE THREAD

**Issue by alexrussell** [atom/atom#2314]
Definitely an odd situation that coders shouldn't be getting into I grant you, but if the indentation mode of the current file is tabs and the indentation actually mixes tabs and spaces, the indent guides go a bit funny:

![indent-guides](https://cloud.githubusercontent.com/assets/412784/3029068/6900d09c-e031-11e3-877f-3e534d303dda.gif)

(Similar with invisibles shown:)

![indent-guides-invisibles](https://cloud.githubusercontent.com/assets/412784/3029078/7bd675d2-e031-11e3-8cd1-552b3bc02e1a.gif)

Version 0.95.0. Will test with updated version later.

**Comment by thomasjo** [comment]
Unable to reproduce this on v0.190.0. Please re-open if you manage to reproduce it.

**Comment by alexrussell** [comment]
@thomasjo agreed, seems to be fixed now.
