### ISSUE TITLE
Tags not colouring in HTML

### ISSUE THREAD

**Issue by debanjanpaul10** [atom/atom#23252]
Whenever I'm using HTML code in Atom, after two to three lines of codes suddenly the auto indentation and auto coloring of the tags go away. This looks very odd. Please fix this bug soon.

**Comment by apicgg** [comment]
Could you please elaborate the issue? Maybe screen capture or something!

**Comment by debanjanpaul10** [comment]
The issue was solved. Installed the latest version and now it's working. Thanks.
