### ISSUE TITLE
Want to make a Portable version of Atom

### ISSUE THREAD

**Issue by Dynastray** [atom/atom#23299]
### Description

Description of the issue 
I want to make a portable version of atom but no folders are creating and atom doesn't use the folders i set up

### What i already tried

1. Setting up `ATOM_HOME` but every time i launch atom a new .atom folder appears in my Userprofile folder 
2. tried to run `atom --portable` but there is no new folder creating by running this command i tried step one before this

**Expected behavior:**

I thought by setting up `ATOM_HOME` and than running `atom --portable` Atom is creating a portable folder and i can use the program from my USB drive

**Actual behavior:**

Actually it happens nothing if i run `ATOM_HOME` atom crates a folder on my USB drive but atom doesn't use it
And if i run `atom --portable` atom starts but its not crating a new folder

**Reproduces how often:**

I tried it several hours running `ATOM_HOME` from a  .bat file setting up different Directorys and so on

### Versions

Atom version 1.58.0

**Comment by lucknaumann** [comment]
Download the atom-x64-windows.zip (or atom-windows.zip for 32-bit) from the [latest releases](https://github.com/atom/atom/releases/latest), and unpack to a folder on your USB drive.

Your folders should look like this:

USBDrive:\Atom
USBDrive:\Atom\Atom x64 (_This is where you unpack the zip. It's where the atom.exe is. You can call this folder what you want._)
USBDrive:\Atom\\.atom (_create this folder_)
USBDrive:\Atom\\.atom\electronUserData (_create this folder_)

These are the relations between the installed Atom folders and the portable Atom folders:

Installed Location | Action | Portable Location
--------------|:----------:|--------------
"%LocalAppData%\atom" | Don't Copy | "USBDrive:\Atom\Atom x64"
"%USERPROFILE%\\.atom" | Copy | "USBDrive:\Atom\\.atom"
"%AppData%\Atom" | Copy | "USBDrive:\Atom\\.atom\electronUserData"

**Comment by Dynastray** [comment]
thank you very very much for helping me out with my problem

**Comment by Dynastray** [comment]
But i have a question in %AppData% is atom crating a folder with the content of a folder wich is named Dictionaries is there a way to avoid this?

**Comment by lucknaumann** [comment]
Yes, it does create that folder, but as far as I know, there's no way to prevent this. I'm guessing Atom uses this for spell checking or a similar function.

**Comment by backforeground** [comment]
If you use a portable installation like I mentioned, you may be able to remove (I think it removes it) 
\AppData\Roaming\Atom\Dictionaries
by using the file"
"E:\Atom Install\Portable\AtomPortable_1.38.2\App\AppInfo\Launcher\AtomPortable.ini" 

and specifying after the entry
[DirectoriesCleanupIfEmpty]

what directories you want to delete when Atom quits.

**Comment by lucknaumann** [comment]
**FYI** - **Atom is EOL**:

[https://atom.io/](https://atom.io/)
> Atom and all repositories under Atom will be archived on December 15, 2022 [Learn more in our official statement](https://github.blog/2022-06-08-sunsetting-atom/)

**Comment by backforeground** [comment]
Microsoft is killing Atom in favor of VS Code
