### ISSUE TITLE
Atom text edit pane went unresponsive and then overwrote file with only my typed characters on save

### ISSUE THREAD

**Issue by mfclarke** [atom/atom#2333]
I was working in Atom 0.96.0 with a horizontal split screen. 1 file open at the top and 2 files in the bottom. When I went to select some text in the top pane the chrome developer console popped up. There was no error in the console, so I figured I must have triggered a shortcut. I closed the console and tried to select again. It wouldn't let me select or type or move the curser, but the curser was still flashing. I mashed the keyboard in an attempt to see changes on the screen. When nothing worked, I closed the file and it prompted me to save my changes. Figuring it just got stuck on a keyboard shortcut or mouse gesture, I said save and then reloaded Atom. On reload I opened my file and it was just 8 characters, which I'm pretty sure were the keys I mashed after the window was unresponsive ('asdfasdf').

The only indication that Atom had issues was the developer console popping up. But there was no error in the console so no indication that anything was actually wrong. If there were some kind of error message or warning I would never have saved my work.

**Comment by benogle** [comment]
Closing as this hadsnt come up in a while and #1854 and atom/emissary#4 have both been fixed.
