### ISSUE TITLE
Atom editor not tracking changes and updating the application

### ISSUE THREAD

**Issue by kevalshah90** [atom/atom#23472]
I have been using atom editor for making changes to my application code. I recently made a change in my directory - deleted `.git` and then moved all my files to a new folder. 

Now, when I open the folder in atom editor, I do not see different file colors that I use to. It doesn't track which files have changed or anything like that. When I launch the app locally using MacOS terminal, I don't see the changes reflected in my App. 

It's quite strange. What do I need to do to fix this issue?  I am on atom version 1.58.0 x64

**Comment by darangi** [comment]
The .git file is necessary to help track file changes. To fix this you should initialize your new folder as a git repo by executing `git init` and a .git file is generated again
