### ISSUE TITLE
Github Copilot on Atom

### ISSUE THREAD

**Issue by Amazeryogo** [atom/atom#23548]
## Summary

To have GitHub copilot on atom

## Motivation

Since both Copilot and Atom are products by GitHub, why not have copilot on atom just like how we have it on IntelliJ/Pycharm?

I'm a bit surprised that nobody has asked about this before therefore I decided to ask. I'm sorry if this is already posted before or an announcement was made that copilot won't be coming to atom, I didn't know about it.

Thanks,

Suvid

**Comment by UziTech** [comment]
Atom was created by GitHub but I don't think anyone at GitHub is actually working on it. The current contributors are just community members that work on it in their spare time.

**Comment by darangi** [comment]
Hi @Amazeryogo 👋🏾  At the moment, there are no plans for co-pilot support on atom

**Comment by mentash** [comment]
Microsoft is investing heavily in VS Code and treating it as a first class citizen. VS Code is loaded with tons of extensions and features that are supported by giant tech companies as well as individual developers. If you recall, this was a characteristic of Atom. which was once one of the coolest editors out there, now it's dying after Microsoft acquired GitHub. 

I guess people at Microsoft want VS Code to have all the attention possible from developers' communities and tech companies to help them evolve VS Code to become an ultimate tool that has it all, and integrates seamlessly in almost everything.

**Comment by UniqueName12345** [comment]
There should be a plugin (official or unofficial) for atom, as vscode has been acting up lately.

**Comment by olvidate** [comment]
please integrate it for atom!

**Comment by ANDREI12333** [comment]
Please integrate it for atom!

**Comment by mhkarimi1383** [comment]
please integrate it for atom!

**Comment by TheDragonkeeper** [comment]
id like for atom as well

**Comment by atc0m** [comment]
+1 Atom plugin please!

**Comment by DazFather** [comment]
Is so sad that they are letting Atom dieing... is such a cool, minimalistic and fast text-editor.

**Comment by stassop** [comment]
Atom plugin is a must! ⚛️🔌

**Comment by ANDREI12333** [comment]
+1 It would be awesome.

**Comment by Moosems** [comment]
How do we plan on creating such a plugin?

**Comment by UniqueName12345** [comment]
> How do we plan on creating such a plugin?

Are you a staff member for Github?

**Comment by Moosems** [comment]
> Are you a staff member for Github?

No but as a community we can figure it out ourselves

**Comment by UniqueName12345** [comment]
> > Are you a staff member for Github?
> 
> No but as a community we can figure it out ourselves

Just letting you know that since Copilot is now apparently a commercial product, it could technically be considered "piracy" to do this.

**Comment by Moosems** [comment]
Well since it requires an account to authenticate it and actually pay for it copilot has a built in safety system making it seem like it should be fine

**Comment by UniqueName12345** [comment]
> Well since it requires an account to authenticate it and actually pay for it copilot has a built in safety system making it seem like it should be fine

Ok.

**Comment by Moosems** [comment]
However if the worry of piracy exists then it would be better to just not do this

**Comment by UniqueName12345** [comment]
> However if the worry of piracy exists then it would be better to just not do this

wdym

**Comment by Moosems** [comment]
If there is a possibility of legal issues it is better not to make an unofficial extension

**Comment by UniqueName12345** [comment]
> If there is a possibility of legal issues it is better not to make an unofficial extension

???

**Comment by RMagician** [comment]
+1 for atom

**Comment by CyberKiller40** [comment]
+1 for Atom, honestly, how did this get missed???

**Comment by Moosems** [comment]
It didn't get missed but because they're stopping support for atom and because vscode has taken the scene it just wasn't worth the time for them

**Comment by kikoseijo** [comment]
ATOM cant die! We love it!

**Comment by jerbear2008** [comment]
:(

**Comment by sylterin** [comment]
Sorry to break the news to you, but Atom is officially dead, see https://github.blog/2022-06-08-sunsetting-atom/.

**Comment by Moosems** [comment]
Not exactly new news

**Comment by Moosems** [comment]
Take a look at [fauxpilot](https://github.com/moyix/fauxpilot)
