### ISSUE TITLE
Atom crashes after I installed arduino package

### ISSUE THREAD

**Issue by KRISCHOMAT** [atom/atom#23542]
After I installed a package to upload arduino code I cannot open Atom anymore. It immediately crashes with an alert saying "The editor has crashed. Please report this issue to https://github.com/atom/atom."  I also made a new install of it but it did not change anything. I am on a Mac Version 10.15.7.

**Comment by icecream17** [comment]
Your new install might still use the previous install location (which for some reason might not be deleted?), which means the package you've installed still might be causing the error.

So be sure to delete _everything_ and then reinstall: https://flight-manual.atom.io/faq/sections/how-do-i-uninstall-atom-on-macos/

```shell
rm -rf ~/.atom
rm -rf /usr/local/bin/atom
rm -rf /usr/local/bin/apm
rm -rf /Applications/Atom.app
rm -rf ~/Library/Preferences/com.github.atom.plist
rm -rf "~/Library/Application Support/com.github.atom.ShipIt"
rm -rf "~/Library/Application Support/Atom"
rm -rf "~/Library/Saved Application State/com.github.atom.savedState"
rm -rf ~/Library/Caches/com.github.atom
rm -rf ~/Library/Caches/Atom
```

**Comment by KRISCHOMAT** [comment]
Thanks! Working again =)
