### ISSUE TITLE
Consider removing the RPM dependency on lsb-core-noarch.

### ISSUE THREAD

**Issue by expeehaa** [atom/atom#23560]
## Summary

Installing atom without satisfying `lsb-core-noarch` does not seem to break anything obvious in atom, which leads me to believe that it is not strictly required.
If this assumption is true, the dependency could either be completely removed or weakened to a `Suggests`.

## Motivation

On openSUSE Tumbleweed, `lsb-core-noarch` is provided by the package `lsb`, which depends on a lot of programs and packages, including Python 2.7, but is completely unnecessary.

## Describe alternatives you've considered

- Add a lock on `lsb` using `zypper addlock lsb`, then install atom and choose to break it by not installing `lsb`.
  - Works, but it is an annoying workaround for a problem that shouldn’t exist.
- Change dependencies of Tumbleweed’s `lsb` package.
  - This has been done before for atom (https://bugzilla.opensuse.org/show_bug.cgi?id=1086166), but comments in the bug report suggest that the atom RPM shouldn’t require it in the first place.

## Additional information

If an implementation would be as simple as removing the requirement from `resources/linux/redhat/atom.spec.in`, I would be happy to make a pull request.

**Comment by tmichett** [comment]
The error also happens with RHEL 9 and CentOS Stream 9

Error: 
 Problem: conflicting requests
  - nothing provides lsb-core-noarch needed by atom-beta-1.61.0.beta0-0.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

Red Hat based on this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2012924 is no longer planning on including or supporting this package, so the RPM will not be able to be installed easily.

**Comment by beza2000** [comment]
The error also happens with AlmaLinux 9.0

**Comment by alexxa** [comment]
It's the same on F35, I had to install `redhat-lsb-core` which provides `lsb-core-noarch`. Meanwhile [the Atom installation pages](https://flight-manual.atom.io/getting-started/sections/installing-atom/) don't say anth about `lsb-core-noarch` dependency.
