### ISSUE TITLE
Create an `atom bisect` command for determining which package is causing a problem

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#2357]
Similar to the `git bisect` command, this command would load Atom with a subset of the packages available to it. It would launch Atom, then when Atom exits it could ask for "good", "bad", "reset" or "quit". It would perform a binary search of the packages until only one package is left and is marked bad (the most likely scenario) telling the user which package it is.

**Comment by dmnd** [comment]
The bisect package @mark-hahn made is released and it's called [package-cop](https://atom.io/packages/package-cop)

(I googled for "atom package bisect" and ended up here, but didn't see it linked earlier)

**Comment by mark-hahn** [comment]
@leedohm has pointed out my `package-cop` package and its readme are
bloated and overly complex.  If no one does a competing package I'll trim
mine down to basics.  It should be usable now if not a little painful to
learn.

I have no trouble understanding it and use it all the time (grin).

**Comment by bronson** [comment]
Gotta say, the package-cop readme gif kinda scared me off...  I just want to bisect a few packages, not learn how to use Bugzilla.  :)  A leaner version sounds great.

**Comment by monkpit** [comment]
package-cop just helped me narrow down a weird issue in record time - thanks so much @mark-hahn and @dmnd for mentioning it in these comments :)

**Comment by Zireael07** [comment]
Bump, is that going to happen?

**Comment by sadick254** [comment]
`package-cop` seem to solve this use case very well. I am going to close this issue in favour of using the `package-cop` package.
