### ISSUE TITLE
Installing symbols-view@0.53.0 ✗   error

### ISSUE THREAD

**Issue by hamiltino** [atom/atom#2389]
Installing symbols-view@0.53.0 ✗

> ctags@0.12.0 install /home/tux/atom/node_modules/symbols-view/node_modules/ctags
> node-gyp rebuild

make: Entering directory `/home/tux/atom/node_modules/symbols-view/node_modules/ctags/build'
  CC(target) Release/obj.target/ctags/src/readtags.o
  CXX(target) Release/obj.target/ctags/src/tags.o
  CXX(target) Release/obj.target/ctags/src/tag-finder.o
make: Leaving directory `/home/tux/atom/node_modules/symbols-view/node_modules/ctags/build'

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.11.10"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp"
In file included from /home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:134,
                 from ../src/tags.h:5,
                 from ../src/tags.cc:2:
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h: In member function ‘void v8::ReturnValue<T>::Set(uint32_t)’:
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:5816:31: warning: typedef ‘I’ locally defined but not used [-Wunused-local-typedefs]
   typedef internal::Internals I;
                               ^
In file included from /home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:134,
                 from ../src/tag-finder.h:6,
                 from ../src/tag-finder.cc:1:
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h: In member function ‘void v8::ReturnValue<T>::Set(uint32_t)’:
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:5816:31: warning: typedef ‘I’ locally defined but not used [-Wunused-local-typedefs]
   typedef internal::Internals I;
                               ^
../src/tag-finder.cc: In member function ‘virtual void TagFinder::HandleOKCallback()’:
../src/tag-finder.cc:28:29: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Handle<v8::Primitive>)’
     Local<Value>::New(Null()),
                             ^
../src/tag-finder.cc:28:29: note: candidates are:
In file included from /home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:134,
                 from ../src/tag-finder.h:6,
                 from ../src/tag-finder.cc:1:
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:381:29: note: static v8::Local<T> v8::Local<T>::New(v8::Isolate*, v8::Handle<T>) [with T = v8::Value]
   V8_INLINE static Local<T> New(Isolate* isolate, Handle<T> that);
                             ^
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:381:29: note:   candidate expects 2 arguments, 1 provided
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:383:29: note: template<class M> static v8::Local<T> v8::Local<T>::New(v8::Isolate*, const v8::Persistent<T, M>&) [with M = M; T = v8::Value]
   V8_INLINE static Local<T> New(Isolate* isolate,
                             ^
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:383:29: note:   template argument deduction/substitution failed:
../src/tag-finder.cc:28:29: note:   cannot convert ‘v8::Null()’ (type ‘v8::Handle<v8::Primitive>’) to type ‘v8::Isolate*’
     Local<Value>::New(Null()),
                             ^
In file included from /home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:134,
                 from ../src/tag-finder.h:6,
                 from ../src/tag-finder.cc:1:
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:406:29: note: static v8::Local<T> v8::Local<T>::New(v8::Isolate*, T*) [with T = v8::Value]
   V8_INLINE static Local<T> New(Isolate* isolate, T* that);
                             ^
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:406:29: note:   candidate expects 2 arguments, 1 provided
../src/tag-finder.cc:29:28: error: no matching function for call to ‘v8::Local<v8::Value>::New(v8::Handle<v8::Array>&)’
     Local<Value>::New(array)
                            ^
../src/tag-finder.cc:29:28: note: candidates are:
In file included from /home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:134,
                 from ../src/tag-finder.h:6,
                 from ../src/tag-finder.cc:1:
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:381:29: note: static v8::Local<T> v8::Local<T>::New(v8::Isolate*, v8::Handle<T>) [with T = v8::Value]
   V8_INLINE static Local<T> New(Isolate* isolate, Handle<T> that);
                             ^
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:381:29: note:   candidate expects 2 arguments, 1 provided
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:383:29: note: template<class M> static v8::Local<T> v8::Local<T>::New(v8::Isolate*, const v8::Persistent<T, M>&) [with M = M; T = v8::Value]
   V8_INLINE static Local<T> New(Isolate* isolate,
                             ^
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:383:29: note:   template argument deduction/substitution failed:
../src/tag-finder.cc:29:28: note:   cannot convert ‘array’ (type ‘v8::Handle<v8::Array>’) to type ‘v8::Isolate*’
     Local<Value>::New(array)
                            ^
In file included from /home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/src/node.h:61:0,
                 from ../node_modules/nan/nan.h:134,
                 from ../src/tag-finder.h:6,
                 from ../src/tag-finder.cc:1:
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:406:29: note: static v8::Local<T> v8::Local<T>::New(v8::Isolate*, T*) [with T = v8::Value]
   V8_INLINE static Local<T> New(Isolate* isolate, T* that);
                             ^
/home/tux/atom/node_modules/symbols-view/node_modules/ctags/.node-gyp/0.11.10/deps/v8/include/v8.h:406:29: note:   candidate expects 2 arguments, 1 provided
make: *** [Release/obj.target/ctags/src/tag-finder.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/tux/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/home/tux/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tux/atom/node_modules/symbols-view/node_modules/ctags
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! ctags@0.12.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctags@0.12.0 install script.
npm ERR! This is most likely a problem with the ctags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ctags
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/home/tux/atom/apm/node_modules/atom-package-manager/bin/node" "/home/tux/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/tux/atom/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "/root/.atom/.node-gyp/.atom/.apm/symbols-view/0.53.0/package.tgz" "--target=0.11.10" "--arch=x64" "--quiet"
npm ERR! cwd /home/tux/atom
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/tux/atom/npm-debug.log
npm ERR! not ok code 0

Help appreciated. Running Debian stable with a few unstable packages to satisfy dependencies.

**Comment by 50Wliu** [comment]
Most likely user error and/or fixed in the latest version.  If you're still experiencing this, please comment here!
