### ISSUE TITLE
Package manager should allow dependencies to be placed on other plugins

### ISSUE THREAD

**Issue by park9140** [atom/atom#2412]
Currently, packages that are pluggable (such as autocomplete-plus, and AtomLinter) are dependent on their own implementations of plugin style functionality.  In order to better support packages like this I think that we should be able to support packages having dependencies.  

What I would like to see is capabilities added for the following.
- Subscribe to package manager to get instance of package when it is loaded
- When loaded a subscribed package should expose instance of package created so sub modules can execute against loaded package, for instance if the workspace was a separate module we would get the workspace by subscribing to the workspace load rather than it being available globally on the atom object.
- Ability to subscribe to loaded packages by metadata filter, something like what atom linter does to find linters that have been loaded, but subscribed like we subscribe to all current and future editors.
- A simple interface for verifying version (via semver) of the subscribed package(s) are of the correct version, and when not alerting the user that the modules need updating.

This would give us the ability to dynamically, and bi-directionally link modules to each other.

**Comment by capaj** [comment]
have you guys noticed this npm package: https://github.com/travs/atom-package-dependencies ?

**Comment by balupton** [comment]
For what it's worth, in DocPad land, we use npm's `peerDependencies` for this.

**Comment by lijunle** [comment]
The behavior of `peerDependencies` will be [changed](http://blog.npmjs.org/post/110924823920/npm-weekly-5) in NPM@3. They will not be installed automatically any more. I don't think it meets the requirement here.

**Comment by balupton** [comment]
That's correct, hence why we already add the extra checks, and will be adding such installation magic to our system, which we plan to abstract out into an independent system, if useful to others.
