### ISSUE TITLE
chmod build for deb or build in place instead of /tmp

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#2437]
The assumption of your build scripts is that all people use the default insecure permissions provided by Ubuntu but this is not true, quite a few of us default all user `umask`'s to `0077` and use `getfacl` and `setfacl` to adjust per directory permissions inside of the home directory, this results in dpkg going nuts unless you adjust the `umask` ahead of time which is fair enough for programmers and systems experts but if you plan to build a one-stop shop for building atom please consider taking into consideration consistency enforcement to prevent silly `dpkg-deb` errors.

There are several options here in my opinion:
- Set the `umask` before you even get started.
- Build in place and use `setfacl` on a custom tmp folder inside of the build directory.
- `chmod` everything.

If you guys provide me with your preference I'd be more than happy to send a pull addressing this issue and providing quite a bit of system consistency enforcement for your Debian build scripts.

**Comment by tribut** [comment]
Just changing the umask before calling `script/{build,grunt}` will still result in a bad `.deb`. It would be great if someone with more insight into the build process could look at that.

**Comment by envygeeks** [comment]
I've never had a problem when I set the umask ahead of time but that said, {set,get}facl is probably the better solution here, they can create a folder in tmp and set the default mask avoiding any problems, this isn't such a big deal since most (if not all) modern distros have it, but in the event it's not available they can always go the slow way and find -exec chmod for file types and flags.

**Comment by envygeeks** [comment]
This could have been an issue with ACL because it seems that this is no longer a problem, when we set an ACL on a folder with default masks now it works as expected, that or Atom/Node/io.js started working with ACL's on Linux? I don't know but this is not a problem for anymore, if @tribut wants it to remain open I'll leave it open otherwise I'll close it in a couple of days.
