### ISSUE TITLE
Follow FHS when building packages for Linux.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#2439]
As it stands right now you place your `.so` and `javascript` files inside of `/usr/share/atom` which is a violation of the FHS IMO, even if it's pretty broad on the explanation to you the FHS further defines what `/usr/lib` is intended for: http://www.pathname.com/fhs/pub/fhs-2.3.html#USRLIBLIBRARIESFORPROGRAMMINGANDPA

**Comment by envygeeks** [comment]
This is still an issue, should I submit an issue? As I would this resolved before 1.0 hits stable.

**Comment by thedaniel** [comment]
Atom is going to hit 1.0 quite soon, and I doubt anyone on the core team will be able to address this before then.

**Comment by thedaniel** [comment]
As always PRs accepted -  I know that can sound dismissive but I think community help is the best hope for this happening anytime in the near future.

**Comment by paulcbetts** [comment]
The best way to fix this is probably to replace all of the `/usr/share/atom` bits with `/usr/lib/atom` which still wouldn't be technically correct but would be more Correcty, and fairly easy to do

**Comment by envygeeks** [comment]
The easiest bit is to just have `atom` use `/opt/atom` and use alternatives to link the bin.  This won't work for Fedora/CentOS or any non-Debian based distro but that doesn't matter since they don't strictly follow the FHS (at least since the last time I checked a few years ago.)

**Comment by envygeeks** [comment]
And by it won't work on Fedora I don't mean that `/opt/atom` doesn't work.  I mean that Fedora doesn't include the alternatives system by default (from what I remember, I'd have to get on my Fedora laptop to confirm.)

**Comment by paulcbetts** [comment]
@envygeeks If you wanted to have a crack at fixing this, here's the relevant files:

* https://github.com/atom/atom/blob/master/build/tasks/mkdeb-task.coffee is the top-level "Make a Debian" task, it fills out:

* https://github.com/atom/atom/blob/master/resources/linux/debian/control.in, then proceeds to shell out to:

* https://github.com/atom/atom/blob/master/script/mkdeb, which actually creates the package

**Comment by envygeeks** [comment]
I'm actually looking at doing it right now already :P I was just seeing how much work I had to do in order to add a postinstall file and how much I would have to adjust to make the file a tad more readable (because some of that file was rather confusing to me -- I hope you don't mind me saying that.)

**Comment by paulcbetts** [comment]
@envygeeks I didn't write it, I just reverse engineered it :)  Adjust away!
