### ISSUE TITLE
Log config parsing errors as errors, not warnings

### ISSUE THREAD

**Issue by fxdgear** [atom/atom#2445]
I'm not sure what happened. I installed a plugin (pep8 python linter), I tried to configure it. The next time I opened atom it went back to the default settings. Anything in my config.cson is not being used. Even when I manually make changes in the settings pane, they aren't being set. 

ideas on how to trouble shoot this?

Thanks

**Comment by benogle** [comment]
The latest version of atom shows a notification with the error message.
