### ISSUE TITLE
[OS X] Application doesn't replace colon with slash in file name presented to user

### ISSUE THREAD

**Issue by otaran** [atom/atom#2451]
##### Steps to reproduce
1. `touch Foo\:Bar.txt`
2. `open -b com.github.atom Foo\:Bar.txt`
3. Inspect opened window
##### Expected result

Application presents file name as `Foo/Bar.txt`
##### Actual result

Application presents file name as `Foo:Bar.txt`
##### Screenshots

Window title:
![Window title](https://cloud.githubusercontent.com/assets/1595470/3129134/fa810bae-e7de-11e3-9993-0099fe873f18.png)

Tab title:
![Tab title](https://cloud.githubusercontent.com/assets/1595470/3129142/1f9da154-e7df-11e3-8021-0117aa4a6437.png)

Sidebar:
![Sidebar](https://cloud.githubusercontent.com/assets/1595470/3129151/30f9c842-e7df-11e3-819f-40c6d4ec471e.png)

Bottom bar:

![Bottom bar](https://cloud.githubusercontent.com/assets/1595470/3129154/3ce3ac68-e7df-11e3-987c-b3497ed4ee47.png)
##### Affected version

0.100.0
##### Environment

OS X 10.9.3

**Comment by damieng** [comment]
Given the lack of interest and progress in this I'm going to go ahead and close this issue.
