### ISSUE TITLE
"Move Line Up" and "Move Line Down" with multiple selections

### ISSUE THREAD

**Issue by ifthenelse** [atom/atom#2470]
After making multiple selections, "Move Line Up" (<kbd>Ctrl</kbd> <kbd>Cmd</kbd> <kbd>Up</kbd>) and "Move Line Down" (<kbd>Ctrl</kbd> <kbd>Cmd</kbd> <kbd>Down</kbd>) works only on the last selected line, instead it should move all the lines.

![atom-multiple-selection-move-issue](https://cloud.githubusercontent.com/assets/50681/3138639/e528d254-e8a2-11e3-9608-e67da60182cf.gif)

**Comment by jonathandelgado** [comment]
+1

**Comment by sobi3ch** [comment]
+1

**Comment by tonka3000** [comment]
+1

**Comment by stokescomp** [comment]
+1

**Comment by xaviergmail** [comment]
+1

**Comment by blqke** [comment]
+1

**Comment by devonestes** [comment]
+1

**Comment by ryanjuve-porch** [comment]
+1

**Comment by quinHD** [comment]
+1

**Comment by fnfilho** [comment]
+1

**Comment by mnquintana** [comment]
Thanks for the feedback everyone! However, all these +1s and :+1:s are just adding noise, so to minimize that I'm going to lock this issue for now – we may unlock it once someone starts working on this enhancement to get further feedback.

**Comment by 50Wliu** [comment]
This has been fixed in #8232 (thanks to @lpommers and @abe33) and should be available in the next Atom beta or the Atom 1.2.0 stable release.

**Comment by nathansobo** [comment]
Clarification: 1.3.0 stable since it was merged into 1.3.0-dev. 1.2.0-betaN is already out.
