### ISSUE TITLE
"Reveal in Tree  View" does not work in "Project Find Results"

### ISSUE THREAD

**Issue by varesa** [atom/atom#2483]
I have searched for a string in the project, which results in a list of results. Right-clicking a result gives option "Reveal in Tree View", which I assume should highlight the file it was found in the project tree view.

However it only moves the focus to the tree view. It does not matter if the tree is collapsed or not. Even if the file is visible, it does not get selected.

The same problem seems to affect "Reveal in Tree View" in the context-menu for the active tab.

**Comment by kevinsawicki** [comment]
This option is no longer available in the find results, it is only available on pane items that have a path.

Fixed by https://github.com/atom/tree-view/pull/406
