### ISSUE TITLE
Log error when a command fails

### ISSUE THREAD

**Issue by JoshCheek** [atom/atom#2499]
The problem
----------------

When brand-new, like me, the problem could be anywhere, so I'm clumsily looking at **everything** to try and figure out where the issue is. All I can see is that nothing happens. The specific issue was that I had the command correctly loaded into the `activationEvents` in the json file, and my "lib/my-project.coffee" worked correctly, but I didn't have the `main` set up to load the file (because I generated it with `$ apm init --convert` to load my TextMate plugin rather than with `generate:package`).

I assume what happens is that when I run the command, it goes to find the command, which should be there because it is added in the `activate` key. But it is not there since the file did not get loaded. Because it is not there, it silently fails and removes the commands from the list of commands.

The desired behaviour
----------------------------

Ideally, the system would log enough information for me to figure out where the issue is.

Keep in mind that I'm very very new so I have very little ability to troubleshoot based on reasoning about the system. I'd like to know it's not in my keymap file, it's not in my package.json. Something like this would be helpful: "my-package:my-command was registered as an activationEvent, but could not be found as a command." maybe also a link to common reasons this could happen such as: the command was never, the name is wrong (describing a way to see the list of registered commands in the given namespace would help a lot here), the file was never required, the file wasn't specified in the main command of package.json.

Another Possibility
-----------------------

I don't know if it's reasonable to have .coffee files in lib without having a main in package.json, but maybe a linting of package.json would catch this? Or maybe there's a combination of things: files in lib, no main, commands in activationList. If this is something that could be caught, it would also be nice if it would run automatically on saving of package.json

**Comment by kevinsawicki** [comment]
There is now a core `atom.notifications` API and a notifications package to display them so this should be pretty well handled since there are also custom notifications for common IO errors and package loading/activation errors, closing this out.
