### ISSUE TITLE
[Bug] Stop auto-changing parts of code when saving, it becomes problematic

### ISSUE THREAD

**Issue by t3dium** [atom/atom#25090]
When saving a print statement, it takes the one line of code and puts it on multiple

https://user-images.githubusercontent.com/83690012/161508080-24a10136-b448-4f15-9e40-f0a2720814e5.mp4

When concatenating variables with commas.. it puts an extra space after the comma which results in syntax errors in my case

https://user-images.githubusercontent.com/83690012/161508537-751242fb-efbd-4c98-8938-d547294ae5fd.mp4

**Platform:** linux, however I've also reproduced these bugs on windows as well
**Version:** latest

**Comment by icecream17** [comment]
probably in the settings
1. Disable "soft wrap" https://flight-manual.atom.io/getting-started/sections/atom-basics/#soft-wrap
2. Maybe the `whitespace` package or some other auto-formatter? https://flight-manual.atom.io/faq/sections/why-is-atom-deleting-trailing-whitespace-why-is-there-a-newline-at-the-end-of-the-file/ doesn't say anything about commas though.
