### ISSUE TITLE
[Bug] linux - incorrect electron dependency - v9 instead of 11

### ISSUE THREAD

**Issue by t3dium** [atom/atom#25154]
**Platform:** Linux, arch
**Version:** latest

Lately after updating all system packages, atom gives an error when interacting with certain parts of the ui (for e.g browsing packages), as atom requires electron 11 yet electron 9 gets installed instead when installing atom. The issue was quickly resolved when reinstalling and manually installing electron 11.
```
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/lib/electron11/version'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object. (/usr/lib/node_modules/atom-package-manager/bin/apm:7:88)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/lib/electron11/version'
}
```

My issue is similar to: 
https://libredd.it/r/Atom/comments/tsvwl9/apm_depends_on_nodeltsgallium_but_doesnt_work/

Proposed solution: list electron 11 as dependency

**Comment by alerque** [comment]
This is not a bug in the upstream atom project and can be closed. This is an Arch Linux packaging issue (and I say this as the Arch Linux maintainer of these packages).

The Atom package is completely broken right now and still stuck at 1.58.0 (and hence validly depending on Electron 9). I recently adopted it and am working on getting it updated, but it is a royal fiasco to package. The `apm` package is now working but `atom` isn't there yet.

**Comment by weirdo-neutrino** [comment]
https://archlinux.org/packages/community/x86_64/atom/
atom 1.61.0beta0-2 
Working smooth. Issue probably can be closed.

**Comment by EdwinFairchild** [comment]
I dont see an  atom 1.61.0beta0-2  anywhere

**Comment by alerque** [comment]
@EdwinFairchild Did you both to look at the [link](https://archlinux.org/packages/community/x86_64/atom/) in the previous comment?

**Comment by Bhooty** [comment]
Install electron11 from pacman

**Comment by alerque** [comment]
@Bhooty If you install `atom` from pacman it will give you the right Electron.

----

He yo upstream @atom project anybody, can we get this issues closed? It has nothing to do with the upstream project, it is a downstream packaging issue and dealt with besides. Further similar issues should be on Arch Linux's bug tracker anyway.

**Comment by Bhooty** [comment]
> @Bhooty If you install `atom` from pacman it will give you the right Electron.
> 
> He yo upstream @atom project anybody, can we get this issues closed? It has nothing to do with the upstream project, it is a downstream packaging issue and dealt with besides. Further similar issues should be on Arch Linux's bug tracker anyway.

depends on distro
for example on my manjaro one it installed electron 9 and was working but after update, it asked for electron 11 inside the app. Thus I had to install electron 11

**Comment by alerque** [comment]
@Bhooty That is Manjaro's issue and should be reported to them. They are way behind in syncing fixes from Arch Linux or implementing their own fixes. But again that does not belong on *this issue tracker*.
