### ISSUE TITLE
Error for possible memory leak

### ISSUE THREAD

**Issue by pengux** [atom/atom#2535]
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit. events.js:166
EventEmitter.addListener events.js:166
console.trace() events.js:170
EventEmitter.addListener events.js:170

**Comment by kevinsawicki** [comment]
Closing this out, this warning comes from core node and can be configured on a per listener basis. If it still occurs for any core stack traces then separate issues should be opened for each one so they can be specifically addressed.
