### ISSUE TITLE
Help newbies with a tutorial

### ISSUE THREAD

**Issue by batjko** [atom/atom#2540]
I realize it's all still early days, but after fighting my way through the windows build, I am now struggling to find out how to actually use the program. 

There's a lot of info out there on how cool the customizations are, packages, themes, dev tools etc... which is all awesome.

But I have it open and wonder what to do next... Apart from the above, I want to know all the basic features of the editor window itself, that allegedly allow me to write code somehow better than with other editors... 
And no, I haven't used Sublime before so saying that it's basically just like that, doesn't really help.

What would be really helpful though, is if there was a simple wiki page or something that gives us something like a "10 things to try after installing Atom" kind of primer.

Next step maybe a migration helper, something like "Atom for Notepad++ users", you get my drift...

**Comment by 50Wliu** [comment]
The new welcome guide and the flight manual should cover this.
