### ISSUE TITLE
Atom packages not accessible

### ISSUE THREAD

**Issue by arnaudbore** [atom/atom#25429]
Atom packages not accessible such as https://www.atom.io/api/packages/atom-latex/versions/0.9.1/tarball

**Comment by lexonerus** [comment]
Same problem

**Comment by ladar** [comment]
Seems to have been fixed for most people. See this issue #25417...

**Comment by ken-eXs** [comment]
The same issue.
As of now, unable to install package.
![image](https://user-images.githubusercontent.com/86753024/166103725-dd0d0188-7855-4fb3-bdae-bf500edfbf82.png)
![image](https://user-images.githubusercontent.com/86753024/166103742-fa36a9fb-9284-4413-868e-0806a8cf9289.png)
Please help.
Thank you.

**Comment by darangi** [comment]
This issue has been resolved, I will go ahead and close this. Feel free to re-open it if you still experience this
