### ISSUE TITLE
Latest Atom 1.60 on Linux suddenly freezes GNOME when requiring file open popup

### ISSUE THREAD

**Issue by hermidalc** [atom/atom#25437]
Not sure if it was due to recent 5.17 kernel update or some other recent update on Fedora 35. But as of a few days ago I could get a GNOME file open popup from Atom. Now if you do anything in Atom that requires a file open popup it dims like it is going to display it but then nothing comes up and the entire GNOME desktop is frozen. Sad.

**Comment by pjuhen** [comment]
I have other strange things with KDE. When I launch Atom, the window of keepaxc, which is hidden, appears. I dont think that the problem is linked with the kernel, but more with the window manager, and more globally, with the desktop management.

**Comment by hermidalc** [comment]
On Fedora 35 GNOME now when you do something within Atom that triggers a file open popup, the Atom window dims slightly (which is normal and expected) because it's going to be in the background and getting ready to show the GNOME file open popup in the foreground, but instead of showing the popup GNOME freezes with Atom dimmed.

**Comment by hermidalc** [comment]
> I have other strange things with KDE. When I launch Atom, the window of keepaxc, which is hidden, appears. I dont think that the problem is linked with the kernel, but more with the window manager, and more globally, with the desktop management.

Did this just start happening to you recently? I haven't been coding for a couple weeks but a couple weeks my Atom 1.60 was working perfectly fine on Fedora 35. Some Fedora update since then triggered this sudden problem. Might rollback my dnf history to see where, but either way still not good because then I cannot update Fedora anymore for fear of breaking Atom again, not a long-term solution.

**Comment by pjuhen** [comment]
No, I installed Atom a week ago.

Seems that atom uses dbus. I would look into that direction.


Le 03/05/2022 à 23:14, Leandro Hermida a écrit :

**Comment by hermidalc** [comment]
Another update to Fedora 35 packages now fixed the problem, so must've been a temporary issue or regression caused by a GNOME or Fedora package Atom uses.
