### ISSUE TITLE
npm error code E500 when trying to download atom packages / themes

### ISSUE THREAD

**Issue by CorrosiveSt** [atom/atom#25431]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

When trying to download atom packets and themes, it'll be stuck for a good while and then give out an error as such:
```
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://www.atom.io/api/packages/teletype/versions/0.13.4/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/corrosive/.atom/.apm/_logs/2022-04-25T17_07_38_400Z-debug.log
```
I was trying to install teletype in this case, but it applies to any packet and theme currently. Exact same happens when trying to use `apm install`.

### Steps to Reproduce

1. Open atom
2. Head to settings -> Install -> Search for packet -> Install
3. Wait for a while as it tries to download
4. Update the tab by leaving the install tab, and going back
5. The error message can be seen

**Expected behavior:**

Download and install the packages as it did the day before

**Actual behavior:**

Fails every time

**Reproduces how often:**

100%

### Versions
ATOM:
- Atom    : 1.58.0
- Electron: 9.4.4
- Chrome  : 83.0.4103.122
- Node    : 12.14.1

OS:
- Pop!_OS 21.10
- 64 bit
- GNOME version 40.4.0
- Windowing system X11

### Additional Information

Worked all fine yesterday (24.4 UTC +3)
Wondered if I was duping issue #25429, thought it was fine due to the wording

**Comment by lblais** [comment]
It happening to me also. under Windows  11, used VPN to hit the servers from different continent and could also replicate the issue. I'm trying to install ide-python package amd script (version 3.32.2) packages with no success.

**Comment by CorrosiveSt** [comment]
Did not realise this was a problem for people so long ago, just found this comment:
https://github.com/atom/atom/issues/25417#issuecomment-1108884733
In issue: #25417 
And using that method, I could install packages. Hope these help you as well @lblais

**Comment by CorrosiveSt** [comment]
Closing issue, and waiting for the fix
