### ISSUE TITLE
Personal info exposed

### ISSUE THREAD

**Issue by jeffinrp** [atom/atom#25456]
Can anyone please remove the following ticket

https://github.com/atom/atom/issues/14945

It has my personal information exposed

The email which i issues to create the issue is deactivated. So I couldn't do it personally

I didn't know my email signature was captured in the bug report

**Comment by darangi** [comment]
Hi @jeffinrp could you verify if your personal details are still visible in the issue?

**Comment by jeffinrp** [comment]
Thanks a lot @darangi : Its deleted now 😍

**Comment by darangi** [comment]
You are welcome 🎉

**Comment by Nobody-loses-like-trump** [comment]
but I can see it using the Wayback Machine
