### ISSUE TITLE
I need people to help continue this project. I forked it but I don't have enough skills to continue it on my own.

### ISSUE THREAD

**Issue by flashtechstudios** [atom/atom#25516]
https://github.com/flashtechstudios/atomcommunity

**Comment by a-chacon** [comment]
But what about the atom-community version? I know it is not maintained for a long time, but I think that is the project that should continue with this beautiful code editor or not? and f u Microsoft

**Comment by andre-koch** [comment]
Why not just continue the atom-community version?: https://github.com/atom-community/atom

**Comment by quenbyako** [comment]
With respect to your enthusiasm to keep working on a (really cool) code editor, it's incredibly difficult to create a fork  from scratch environment that will be popular, actively maintained, and has a healthy community. 

I'm not in the position to make recommendations, but still, in my opinion, it would be much more productive to reach out to the @atom-community maintainers and offer them your help. Yes, this fork has not been updated for a long time, but it has at least an initial audience and a basic community pipelines, this is already a good start.

The worst thing what could be with closed opensource project — dozens of forks, which are all dead. Better to concentrate on single, most popular fork (even if it's not so good for you)

**Comment by flashtechstudios** [comment]
> With respect to your enthusiasm to keep working on a (really cool) code editor, it's incredibly difficult to create a fork from scratch environment that will be popular, actively maintained, and has a healthy community.
> 
> I'm not in the position to make recommendations, but still, in my opinion, it would be much more productive to reach out to the @atom-community maintainers and offer them your help. Yes, this fork has not been updated for a long time, but it has at least an initial audience and a basic community pipelines, this is already a good start.
> 
> The worst thing what could be with closed opensource project — dozens of forks, which are all dead. Better to concentrate on single, most popular fork (even if it's not so good for you)

It's severely outdated? If it wasn't outdated I would totally contribute and would fork this project.

**Comment by SoftOrangeTech** [comment]
> > With respect to your enthusiasm to keep working on a (really cool) code editor, it's incredibly difficult to create a fork from scratch environment that will be popular, actively maintained, and has a healthy community.
> > I'm not in the position to make recommendations, but still, in my opinion, it would be much more productive to reach out to the @atom-community maintainers and offer them your help. Yes, this fork has not been updated for a long time, but it has at least an initial audience and a basic community pipelines, this is already a good start.
> > The worst thing what could be with closed opensource project — dozens of forks, which are all dead. Better to concentrate on single, most popular fork (even if it's not so good for you)
> 
> It's severely outdated? If it wasn't outdated I would totally contribute and would fork this project.

I have another one here:
https://github.com/SoftOrangeTech/AtomNoAbandon

**Comment by flashtechstudios** [comment]
> > > With respect to your enthusiasm to keep working on a (really cool) code editor, it's incredibly difficult to create a fork from scratch environment that will be popular, actively maintained, and has a healthy community.
> > > I'm not in the position to make recommendations, but still, in my opinion, it would be much more productive to reach out to the @atom-community maintainers and offer them your help. Yes, this fork has not been updated for a long time, but it has at least an initial audience and a basic community pipelines, this is already a good start.
> > > The worst thing what could be with closed opensource project — dozens of forks, which are all dead. Better to concentrate on single, most popular fork (even if it's not so good for you)
> > 
> > 
> > It's severely outdated? If it wasn't outdated I would totally contribute and would fork this project.
> 
> I have another one here: https://github.com/SoftOrangeTech/AtomNoAbandon

It's not outdated anymore, the community has started pulling changes : )

**Comment by SoftOrangeTech** [comment]
@flashtechstudios I'll start pulling changes aswell - I might archive my fork lol

**Comment by flashtechstudios** [comment]
> @flashtechstudios I'll start pulling changes aswell - I might archive my fork lol

Oh, I deleted my fork lol

**Comment by SoftOrangeTech** [comment]
@flashtechstudios lol just fork again, pull changes, do it

**Comment by SoftOrangeTech** [comment]
> > @flashtechstudios I'll start pulling changes aswell - I might archive my fork lol
> 
> Oh, I deleted my fork lol

OK, I will add you as collaborator on my own fork @flashtechstudios.

**Comment by flashtechstudios** [comment]
> > > @flashtechstudios I'll start pulling changes aswell - I might archive my fork lol
> > 
> > 
> > Oh, I deleted my fork lol
> 
> OK, I will add you as collaborator on my own fork @flashtechstudios.

Thanks

**Comment by stixxlee** [comment]
Cty for collaboration with me on my code I'm so lost can u help me more I play and record music also I can share with u

**Comment by stixxlee** [comment]
@stixxlee

**Comment by softorangetech11** [comment]
@flashtechstudios i got deleted my previous acc lol. I will add you to my new fork, which got renamed.

**Comment by flashtechstudios** [comment]
> @flashtechstudios i got deleted my previous acc lol. I will add you to my new fork, which got renamed.

uhh kay

**Comment by quenbyako** [comment]
> @flashtechstudios It's severely outdated? If it wasn't outdated I would totally contribute and would fork this project.

As i said previously, that doesn't mean, that you need to create fork 🙃 Try to reach out their maintainers, maybe they abandoned repo, because they're waiting for **you** 😉 I also have pretty abandoned project, and looking for an active maintainer, even if this project wasn't updated a year (which is sucks honestly)

**Comment by quenbyako** [comment]
@flashtechstudios https://github.com/atom-community/atom was updated 3 days ago btw!
