### ISSUE TITLE
Atom.io opens developer tools? I know it's NOT supposed to look like this,

### ISSUE THREAD

**Issue by KitsuTheFloof** [atom/atom#25604]
Okay I will just let the screenshot explain the issue.
![image](https://user-images.githubusercontent.com/90358192/186786786-e4c572cf-7d19-4358-818f-acd27ed9af8c.png)

I've used Atom.IO before and it shouldn't look like this at all. I uninstalled it but it didn't fix it.

**Comment by KitsuTheFloof** [comment]
Simple fix I did on my own. I deleted the entire .atom folder in
 C:\Users\[Username]\.atom
but you can do
 C:\Users\[Username]\.atom\storage\application.json
and just delete that

**Comment by TheDude53** [comment]
Could you please explain in a bit more detail how you ended up with the error this screenshot shows?
