### ISSUE TITLE
build-cmake package with Geant4

### ISSUE THREAD

**Issue by byba1990** [atom/atom#25612]
### Description

I don't know how I can launch the `build-cmake` package. I want to use cmake to compile Geant4 with the following command:

`cmake -DGeant4_DIR=$path_project ../`

I tried to fill the settings without success. I receive this error: "Cannot extract target for generator "Green Hills Multi". What it means?

### Versions
1.58.0 on Linux.

### Additional Information
For more information about the compilation of Geant4, you can check from the official website.

Thanks in advance for your time.
Best regards,

Christian

**Comment by nicki314juansyah** [comment]
> ### Description
> I don't know how I can launch the `build-cmake` package. I want to use cmake to compile Geant4 with the following command:
> 
> `cmake -DGeant4_DIR=$path_project ../`
> 
> I tried to fill the settings without success. I receive this error: "Cannot extract target for generator "Green Hills Multi". What it means?
> 
> ### Versions
> 1.58.0 on Linux.
> 
> ### Additional Information
> For more information about the compilation of Geant4, you can check from the official website.
> 
> Thanks in advance for your time. Best regards,
> 
> Christian

eroor.code

**Comment by nicki314juansyah** [comment]
cede eroor

**Comment by byba1990** [comment]
no problem, solved by using the configuration file .json. 

Christian
