### ISSUE TITLE
Show all invisible characters

### ISSUE THREAD

**Issue by postcasio** [atom/atom#2572]
Is there a way to get Atom to apply the `invisible-character` class to *all* invisible spaces, instead of just those at the start and end of the line?

Tabs are shown anywhere on the line, but spaces are only shown at the start and end.

**Comment by Cimplex** [comment]
Is this issue still being looked at? Is there a way to do this through an package?

**Comment by nathansobo** [comment]
There's probably not a good way to do this through a package as it's pretty baked into the editor implementation. I anticipate some changes to the layer that handles invisibles in the near future for performance reasons. After that, I'd happily entertain a PR that added this.

**Comment by rasschaert** [comment]
:+1:

**Comment by jadengore** [comment]
:+1:

**Comment by worldsayshi** [comment]
+1 one on this one. I just had a problem with a [punctuation space](http://www.fileformat.info/info/unicode/char/2008/index.htm) lurking in my bash script. Tearing my hair out trying to figure out why bash couldn't find `cat somefile`.

**Comment by lillem4n** [comment]
:+1:

**Comment by chharvey** [comment]
Any updates on this issue? #10053 is waiting

**Comment by lee-dohm** [comment]
I'm unifying all of these roughly-related invisibles Issues into one under #1839. You may want to subscribe there for updates.
