### ISSUE TITLE
Command Palette not working with default keymap

### ISSUE THREAD

**Issue by johnpaulmedina** [atom/atom#2591]
I checked the keymaps and in previous releases the command palette would come up by pressing

shift-cmd-p

However I am running the OS X 10.10 (Yosemite) not sure if this has anything to do with it but that keymap will not work.

I tried creating a custom keymap with that exact command and still nothing. I had to change the command to ctrl-shift-p in order for it to work properly. I do not use that command for anything else on the system in face while in Sublime Text I can use that same command to pull up the Sublime Text command palette and have no issues.

**Comment by JBoothUA** [comment]
space-keys issue

**Comment by mnquintana** [comment]
Gonna close this out - please feel free to reopen / comment if you can reproduce this with Atom (0.210.0) in safe mode (`atom --safe`)

**Comment by tripflex** [comment]
I'm running 1.0.19 on El Capitan and having this same exact problem.  Seems like I'm not the only one as well (there are numerous open issues for `cmd+shift` key combinations).  To get it to work I had to switch to `alt-shift-p` 

Using key binding resolver you can see `cmd-shift` but once those two keys are pressed together, any other letter/key you press is not recognized.  I checked the keybinding in core OSX and there isn't anything specifically tied to `cmd-shift-p` .... seems to me like it may be something specific to OSX that is causing none of the `cmd-shift-` combinations to work correctly.  Found issues on other projects with similar keybinding issues as well

**Comment by jeffmcneill** [comment]
+1 ongoing problems with OSX keybinding, rendering Atom broken for certain keyboard shortcuts

**Comment by wagnerone** [comment]
+1 came here to look for/report this.

**Comment by kevinchandler** [comment]
+1 still happens in safe mode

**Comment by caseywatts** [comment]
I just had this issue - and it was a conflict with another OSX app I have. Another thing to try would be a separate OSX account with no startup items, and you might discover that something maps a keybinding you didn't realize :)

My conflict was with the OSX app "Pomodoro Time"
![image](https://cloud.githubusercontent.com/assets/273653/17485840/e51182f8-5d5c-11e6-808d-133a07d7c0ce.png)

**Comment by mneumark** [comment]
I have found that this tends to happen when you have ^↑ and ^↓ defined in the Mission Control System Preference. Try changing that setting to another key and see if it helps.

**Comment by danielsneijers** [comment]
Same problem here, for me it was the default play/pause shortcut of the app 'Noiz.io' 
![screen shot 2016-09-28 at 10 54 10](https://cloud.githubusercontent.com/assets/1942473/18906939/e81bedf0-8569-11e6-93fc-0479dbc248a6.png)

**Comment by jennPeavler** [comment]
I am having the same issue.  I tried changing the shortcut in Mission Control and it had no effect.  Is there a different resolution to this problem?

**Comment by natterstefan** [comment]
@caseywatts @danielsneijers How did you find this out? Is there an easy way to see which app is using which shortcut on one page?

**Comment by caseywatts** [comment]
@natterstefan I haven't found any way to list out all keybindings for tray apps etc - I had to use process of elimination to determine this (by comparing a new/empty account to my actual account).

**Comment by lxk5477** [comment]
I have the same issue on the Windows 10. I checked with keybinding resolver and it does not recognize P after ctrl + shift. Did anyone find the solution. I hardly doubt that some other program is interfering with this one...
