### ISSUE TITLE
Display multi-key bindings in a more clear way; (Split Up/Left/Right/Down keyboard shortcut doesn't work)

### ISSUE THREAD

**Issue by Frozenfire92** [atom/atom#2594]
Using OSX 10.9.3 and Atom 0.102.0 Although I have noticed this bug on earlier versions aswell.

I have not changed my keymap either.

The keyboard shortcuts `cmd + k + arrow` won't work for me. Pressing `cmd + shift + p` And searching for the command will work through that menu.

**Comment by RobertGloverJr** [comment]
+1 to  make shortcut instructions clearer.

**Comment by igorpan** [comment]
+1 I was trying to make it work for 5 minutes before I stumbled upon this issue. It's really not clear that arrow shouldn't be pressed while holding CMD+K

**Comment by benogle** [comment]
@simurai might you have any ideas on making this more clear?

**Comment by igorpan** [comment]
I think that instead having it written all in one rectangle [Cmd K ->] it could be in two rectangles: [Cmd K] + [->]

That would indicate that it's a combination rather than all-at-once

**Comment by simurai** [comment]
I was wondering if there is some sort of convention about this.. From [Wikipedia](http://en.wikipedia.org/wiki/Keyboard_shortcut#Notation):

* key names separated by `+` or `-` and `space` for the next sequence: `Cmd+K →` or `Cmd-K →`
* sequence separated by commas or semicolons: `Cmd K, →` or `Cmd K; →`

But it's still not that clear. If you don't know about the convention, you might try to also type `+` or `,`.

@igorpan Yeah, I like your suggestion of splitting it up into 2 "rectangles". Then it's not actual text and only a visual hint.

Instead of:

![screen shot 2015-01-24 at 10 48 49 am](https://cloud.githubusercontent.com/assets/378023/5885702/b177f838-a3b7-11e4-9188-1d69ef2dfedc.png)

like this:

![key](https://cloud.githubusercontent.com/assets/378023/5885689/427527d0-a3b7-11e4-8829-2c2a608b7a61.png)

**Comment by mark-hahn** [comment]
None of these, including the separate rectangles, would clue me in.  I
don't think this is possible without some text explaining it.  But I don't
understand why it is such a big problem to find out by trial and error.
Was there someone who couldn't actually figure this out?

**Comment by benogle** [comment]
> None of these, including the separate rectangles, would clue me in.

Yeah, I'm with you. 

> Was there someone who couldn't actually figure this out?

There have been a few issues opened (though I cannot find them) saying splitting didnt work, when the commands were being used incorrectly. 

Basically it would be nice to convey that one needs to hold `cmd` down and type more than 1 character. Not sure how, though.

**Comment by simurai** [comment]
I think the main issue is that currently the space between the `K` and the `→` is quite small and could be seen as "together":

![screen shot 2015-01-24 at 11 19 20 am](https://cloud.githubusercontent.com/assets/378023/5885781/4aad4352-a3bb-11e4-8821-8d89b52553f7.png)

So separating them by 2-3 spaces might already help to make it clearer, not for everyone, but at least a few more.

![screen shot 2015-01-24 at 11 34 46 am](https://cloud.githubusercontent.com/assets/378023/5885824/08c101ca-a3bd-11e4-83b7-c9e59f107801.png)

**Comment by 50Wliu** [comment]
I like the two rectangles better than the 'extra spaces' method-the rectangle method might alert me, but not the extra spaces one.

**Comment by igorpan** [comment]
@mark-hahn I couldn't figure it out. Only when I Googled it I found this issue and on it I discovered that it's actually a combo. Thread creator also thought it was a bug. Current hint had nothing to even suggest it's a combo.

Honestly, when seeing two rectangles (maybe with a + sign in between) I would definitely try to combo right away. 

I don't think putting a comma in between is a good idea for the following reasons:

1. If it's one rectangle with comma, there is no easy way to tell the user that comma isn't actually another key that needs to be pressed (like CMD+, for preferences).
2. If it's two rectangles with a comma in between, then it looks more like two shortcuts for same action than like a combo. Eg. if I see [CMD P], [B] my intuition would be that I can do any of those to get what I want.

**Comment by robhicks** [comment]
@mark-hahn I couldn't figure it out either. And the [docs](https://atom.io/docs/v0.176.0/getting-started) don't help either. Although I don't think the suggestion of @igorpan to split the keyboard shortcut hints into separate rectangles is ideal, I think it is much better than using a comma or leaving it as is.

**Comment by nickiaconis** [comment]
@mark-hahn I'm in the same boat as @robhicks on this one. I couldn't figure it out until I wound up here. I found the shortcut in the ⌘⇧P dialog, but it looked to me like it was meant to be pressed all at once. If I had seen two boxes, it's likely I would have tried pressing → separately.

@igorpan While I sympathize with your second point regarding two boxes being interpreted as synonymous shortcuts, I'm not sure anyone would think → by itself is a shortcut.

Even if they did, wouldn't it stand to reason they might try the first (⌘K), then, upon seeing it didn't work, try the second (→), and eventually come to realize that the two must be used in sequence?
