### ISSUE TITLE
atom --wait focusses the wrong atom window

### ISSUE THREAD

**Issue by dmnd** [atom/atom#2598]
Scenario:
1. Have `GIT_EDITOR="atom --wait"`
2. Edit a file in an atom window
3. `git commit` from Terminal
4. See new atom window pop up with a cursor
5. Try to type commit message
6. Notice you're typing in the atom window you were editing in, not the one popped up for the commit
7. Do this enough times to decide to report it

**Comment by lee-dohm** [comment]
@ungb Can you attempt to reproduce this based on @izuzak's repro steps? Let me know :grinning:

**Comment by ungb** [comment]
I was not able to repro this issue as describe, also when I open the second file, it opened in the first atom project, but I was not able to drag the file in the tab to a new atom window.   I think this is a much wanted feature: https://github.com/atom/tabs/issues/39.  Instead I open the folder then open the file.

After I open the second project in a new Atom window, I drag it to a different display and close it, After opening it again, it opens in the same display I dragged it to.  When I type it was working as expected, I also tried to repro the issue above and couldn't.  I'm going to close this issue out, if anyone is able to to provide more info or is able to still repro, please let us know and I'll reopen this issue.
