### ISSUE TITLE
editor:cut-to-end-of-line should cut to end of actual line in soft wrap

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#2607]
^k only kills to the edge of the editor when soft wrap is on. I expect the behavior to be the same as if the file wasn't soft-wrapped - that is to say, a line's a line (and it's the line represented in the file, bounded by newlines), even if I have the editor temporarily showing it as three or four.

**Comment by izuzak** [comment]
There's now a `editor:cut-to-end-of-buffer-line` command which can be used to cut text to the end of the buffer line. It will be included in the next release of Atom (see #8828 which adds this functionality).

However, by default, `ctrl-k` is still bound to `editor:cut-to-end-of-line`, so if anyone wants to switch to the new behavior -- you need to add something like this to your keymap.cson:

```
'atom-text-editor':
  'ctrl-k': 'editor:cut-to-end-of-buffer-line'
```
