### ISSUE TITLE
Menu bar is not displayed correctly in full screen mode

### ISSUE THREAD

**Issue by anxolerd** [atom/atom#2613]
Built Atom for x32 systems. Have win7 x64 (home basic).
Have a trouble with displaying menubar in fullscreen mode. When i press 'alt' key -- i see no menu bar -- only small lines on the top.
Attaching a screenshot:
![menubug](https://cloud.githubusercontent.com/assets/6533582/3280721/ba02b4e6-f478-11e3-9b29-8f6dd103a23e.png)

**Comment by damieng** [comment]
I think this has been fixed at some point since this issue was filed - the full menu bar is showing for me in Atom 1.5.3 on Windows 7.
