### ISSUE TITLE
32-bit version takes ages to load

### ISSUE THREAD

**Issue by Gabriel-p** [atom/atom#2625]
I installed Atom 32bit via the [Webupd8 PPA](http://www.webupd8.org/2014/06/atom-text-editor-available-for-linux.html) and it takes forever to load.

It shows quite a bit of lag in normal use too (just typing plain text)

OS: elementary 0.2 (Luna)

**Comment by kevinsawicki** [comment]
Closing this in favor of https://github.com/atom/atom/issues/2654 which has tons of discussion and analysis in it.
