### ISSUE TITLE
Wrap guide is above selection

### ISSUE THREAD

**Issue by probablycorey** [atom/atom#2644]
Issue moved from https://github.com/atom/atom-dark-ui/issues/1

> For some reason the wrap-guide is now above the selection which makes it look odd. I think it might have been related to the styles because the DOM order looks correct. @benogle any ideas?

![screen shot 2013-09-18 at 5 40 08 pm](https://f.cloud.github.com/assets/1424/1170023/8fe6ca72-20c4-11e3-90cf-4ab6356d7c86.png)

**Comment by kevinsawicki** [comment]
Closing this out, this doesn't seem like an issue still since themes can style both explicitly and completely control how they are presented.
