### ISSUE TITLE
Hide .pyc and other common generated files by default?

### ISSUE THREAD

**Issue by miohtama** [atom/atom#2646]
Some programming languages leave binary compiled files to the source tree by default. `.pyc` files in Python being the most notably example.

Together with `tree-view` `hideIgnoredNames` being false by default this makes navigation in the source tree little bit cumbersome due to scrolling through unnecessary `.pyc` duplicates, as demonstrated in the screenshot below:

![screen shot 2014-06-18 at 12 27 00](https://cloud.githubusercontent.com/assets/49922/3311919/c71be7c0-f6ca-11e3-90b4-e39d89fcb45d.png)

What is Atom stance towards "sane defaults"? Could it be acceptable patch to have `.pyc` in the ignored files by default (thus giving better out of the box experience), or should things like that go to a separate package which all Python developers then install? (Though Python highlighter comes with the default installation.) I am not sure if I want to make a pull request on this, as I am not aware of the authors stance on the matter like this. 

For comparison, Sublime Text & co. seem to hide `.pyc` files by default.

**Comment by ferdy-galema** [comment]
Are there any plans to have a "language" package to support ignored files? Because in that case we could add this to the python package? If not, then I'd suggest simply change the general default list.

**Comment by DustinWehr** [comment]
Agree with @miohtama; the first thing I noticed upon opening the settings page is that, despite having just installed Atom for OSX, the developer-useless files .DS_store and .localized present in every directory are not ignored by default.

**Comment by Zireael07** [comment]
Hiding common generated files would be a good idea and as far as I can see they are not hidden in the current version of Atom.
