### ISSUE TITLE
Rename the editor.projectHome config option

### ISSUE THREAD

**Issue by probablycorey** [atom/atom#2677]
We should rename this config option to something that describes it better. It is not easy to figure the intent via the name. Also, Atom has a class named `project` which adds to the confusion.

This option is currently describes:
1. Where projects and themes are created by Package Generator
2. Where projects are assumed to be stored by Atom. So if there was an "Open Project" command and I gave it "foo" it would look for a "foo" directory in this path.

@lee-dohm also suggested that `core` would be a more appropriate namespace than `editor.

/via https://github.com/atom/atom/issues/1648

**Comment by mnquintana** [comment]
This is also the directory used by `apm develop` and where Atom will look for resources by default in dev mode.
