### ISSUE TITLE
on packages' "activated" event getActivePackages() returns an empty list

### ISSUE THREAD

**Issue by klorenz** [atom/atom#2685]
This is pretty easy to test.  Create a package, remove the activation trigger from packages.json and fill activate method:

``` coffee
    activate: ->
        atom.packages.once "activated", =>
             console.log "activated", atom.packages.getActivePackages()
```

I expected this to print a list of all active packages.

I found out, that "activated" event is triggered right after all activations are promised.  At that time, the dictionary of
activated packages is still empty, they all drop in one by one, as soon the activate method returned.

Is this by design?  Then there should be another event, as soon all packages' activation methods returned. Maybe packages "ready" event?

**Comment by lee-dohm** [comment]
There's now the [`atom.packages.onDidActivateInitialPackages`](https://atom.io/docs/api/latest/PackageManager#instance-onDidActivateInitialPackages) event that solves this problem.
