### ISSUE TITLE
Snippets that overwrite existing ones

### ISSUE THREAD

**Issue by siannopollo** [atom/atom#2695]
The Language Rspec package comes with it's set of snippets, and those are fine, _except_ that they use double quoted strings (I know, I know, roll your eyes so we can get past that part :-). Anyway, I set up my own snippets in my snippets.cson file (the one accessed via Atom > Open Your Snippets) that overwrite some of the existing Rspec ones.

When I first open up Atom and try to use one of my custom snippets they don't seem to be loaded and the Language Rspec ones are used instead. If I then open up my snippets.cson file and hit cmd+s Atom picks them up and starts using my snippets.

**Comment by bclinkinbeard** [comment]
Is this going to be addressed? Pretty annoying to not be able to modify snippets I use several times a day like `console.log`

**Comment by benogle** [comment]
@bclinkinbeard I am able to override them

Add this to your snippets.cson, then reload, and open a coffee file:

```
'.source.coffee':
  'log':
    'prefix': 'log'
    'body': 'console.omgwowlog $0'
```

**Comment by bclinkinbeard** [comment]
That works, but overriding for JS files doesn't seem to. I have tried both of the following to avoid the semi-colon to no avail.

```
'.source.js':
  'log':
    'prefix': 'log'
    'body': 'console.log($1)'
```
and
```
'.source.js':
  'console.log':
    'prefix': 'log'
    'body': 'console.log($1)'
```

**Comment by benogle** [comment]
Not sure. This works for me in js:

```coffee
'.source.js':
  'log':
    'prefix': 'log'
    'body': 'console.OMGlog($1);$0'
```

Did you reload?

**Comment by bclinkinbeard** [comment]
That does not work for me, even if I completely quit Atom and reopen.

**Comment by benogle** [comment]
What else is in your snippets file? What if that is the only thing? Try `atom --safe`? I assume you're on the latest (1.0.2).

**Comment by bclinkinbeard** [comment]
OK that is weird. The only other thing in my snippets file is this, which is what is breaking it.

```
'.source.js':
  'require()':
    'prefix': 'req'
    'body': 'var ${1:module} = require(\'${2:$1}\')$3'
```

If I remove that, the `log` snippet works.

**Comment by benogle** [comment]
Did you have 2 top level `.source.js` keys? Like json, the second will overwrite the first.

**Comment by bclinkinbeard** [comment]
Ah jeez, that was in fact the problem. Sorry about that, and thanks for helping me sort it out.

**Comment by devunwired** [comment]
> Did you have 2 top level .source.js keys? Like json, the second will overwrite the first.

Oh, man. That really needs to be documented [here](https://atom.io/docs/v1.0.2/using-atom-snippets). Just spent an hour trying to figure out why none of my snippets except that last one was getting picked up…

**Comment by benogle** [comment]
Docs added in https://github.com/atom/docs/pull/102. I'm going to close this as it seems to be a poorly-communicated limitation.

**Comment by jesusjjf** [comment]
I am having similar issue. Can not override the `p` expand. The `html5` snippet works fine.

```
'*':
  'paragraph':
    'prefix': 'p'
    'body': '<p>$1</p>'
  'html5':
    'prefix': 'html5'
    'body': '<!DOCTYPE html>\n<html lang="en">\n<head>\n\t<meta charset="utf-8">\n\t<meta http-equiv="X-UA-Compatible" content="IE=edge">\n\t<meta name="viewport" content="width=device-width, initial-scale=1.0">\n\t<meta name="description" content="">\n\t<meta name="keywords" content="">\n\t<title>${1:title}</title>\n</head>\n\n<body>\n</body>\n</html>'
```
