### ISSUE TITLE
Escape Characters Messing Up Text Alignment

### ISSUE THREAD

**Issue by NWPlayer123** [atom/atom#2712]
I don't know why it's doing this, I compiled 0.106.0(since for whatever reason the code from the repo last night was giving me errors when building), running Windows 8, and I'm editing a python script I made earlier and for whatever reason the \x00 escape code alignment gets really messed up and messes up the alignment of the line after it as well. I tried changing the theme and code syntax highlighting too, and even the default Atom Dark does this.
EDIT: Also, notice how it's only the \x00 and later in that code the \x1a works.

![atomalignment](https://cloud.githubusercontent.com/assets/3280345/3350177/0a4201a8-f994-11e3-9f20-82242313868b.png)

Here's how it's supposed to look: (this is in Notepad++)
![notepad alignment](https://cloud.githubusercontent.com/assets/3280345/3350180/609a2efe-f994-11e3-91db-d3d5b432834c.png)

**Comment by damieng** [comment]
Unable to repro on latest.
