### ISSUE TITLE
errors with Unicode Hex Input on OS X

### ISSUE THREAD

**Issue by jeremy-engel** [atom/atom#2728]
Using the input method Unicode Hex Input on OS X 10.9.3 with atom 0.106.0 doesn't work with all characters. Holding alt and entering `201d` should enter the character `”` but nothing appears. Other unicode characters in the same range work. Entering `201c` with bracket-completion completes to `“”`.

This issue doesn't appear in any other OS X programs I have tried. It also works fine entering unicode on the latest linux build using crtl+shift+u and entering `201d`.

**Comment by grizzilus** [comment]
Just in case anyone else comes across this issue, I made a package to get around the original problem called [unicode-input](https://atom.io/packages/unicode-input). I found it easier to use this than to switch keyboard types, and it makes entering Unicode on Windows a lot less painful.
