### ISSUE TITLE
process.cwd() behaviour

### ISSUE THREAD

**Issue by nshtg** [atom/atom#2733]
It's not a bug, it's a feature!

If I start multiple instances of atom, process.cwd() is the same for all instances (matches the cwd of the first instance started). Even if that one is closed process.cwd() continues to be the cwd of the first instance.

Produces lots of funny bugs if I don't use absolute paths with `fs` for example.

**Comment by stevemao** [comment]
`process.cwd()` always return `'/'` for me

**Comment by stevemao** [comment]
Is this bug fixed?

**Comment by rsese** [comment]
With Atom 1.19.0 on Windows 10, I see the same behavior as described in the issue body.  On macOS 10.12.6 and Atom 1.19.0, `process.cwd()` seems to always return `/` as you mentioned @stevemao.
