### ISSUE TITLE
"Cannot call method 'matchesAttributes' of undefined"

### ISSUE THREAD

**Issue by samuela** [atom/atom#2741]
I got this error after hitting Ctrl-D to select other instance of a word. I was in a split pane. I'm running version 104 on Ubuntu. The error occurs at /Atom/resources/app/src/editor.js:2002.

**Comment by 50Wliu** [comment]
Hi @samuela, if you ever manage to reproduce this again, please comment here!  In the meantime, I'm going to close this.
