### ISSUE TITLE
Multiline-mini-editor

### ISSUE THREAD

**Issue by Azeirah** [atom/atom#2770]
It's possible to create a single-line mini-editor, but it is not yet possible to create a multi-line mini-editor.

Creating a full-fledged editor in small Atom packages is overkill, while the mini-editor is far too small.

Hereby I pledge to the Atom gods to give us a way to create a multi-line mini editor.

**Comment by simurai** [comment]
Ref. discussion https://github.com/atom/atom/issues/5503 about adding a `<atom-text-area>`.

**Comment by hultberg** [comment]
In my mind, this issue can be closed because the goal is - in my mind - achived. For instance, in ex-mode package, we use an text editor for the command input.
