### ISSUE TITLE
Bad curly braces indentation

### ISSUE THREAD

**Issue by ShinDarth** [atom/atom#2777]
Version 0.106.0

Language: C

How is it:

![how-it-is](https://cloud.githubusercontent.com/assets/75517/3433041/70d34e48-007b-11e4-85a4-20c6cd9d32d8.png)

How it should be:

![how-it-should-be](https://cloud.githubusercontent.com/assets/75517/3433044/7aa1d994-007b-11e4-81af-55a90e3e6898.png)

**Comment by damieng** [comment]
This no longer repros for me - unknown at which point it got fixed.
