### ISSUE TITLE
When building atom, the install directory should be configurable or installation should be optional

### ISSUE THREAD

**Issue by grenade** [atom/atom#2786]
The default behaviour when building atom using `script/build` for platforms [other than Linux](https://github.com/atom/atom/blob/8a377c9339d58ee3bdc42f7a38964362d2b4cdbd/build/Gruntfile.coffee#L228), is to [install to a pre-configured folder](https://github.com/atom/atom/blob/8a377c9339d58ee3bdc42f7a38964362d2b4cdbd/build/Gruntfile.coffee#L45-L52).

It would be useful to be able to either configure the installation directory with an argument to `script/build` (eg: `script/build --install-path /some/path`) or alternatively, to either remove the install option from default build tasks or accept a command line argument that prevents installation (eg: `script/build --no-install`).

I think an even better option is for `script/build` to stick to just _build_ and another script (like `script/install`) could be responsible for installation.

See also: https://github.com/atom/atom/issues/2688

**Comment by 50Wliu** [comment]
This has been added-please see https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#advanced-options for more info.
