### ISSUE TITLE
Embed git and detect system git without PATH

### ISSUE THREAD

**Issue by damccull** [atom/atom#2798]
As of now, installing atom on windows involves cloning the repo and building it from source. This assumes you already have git because the build system uses git to download other parts of the program.

As atom gets an official windows build, however, git may or may not be installed on users machines. A user may also choose between github's Git for Desktop or msysgit. There should be 4 operating modes for atom based on these cases.
1. Integrate with github's Git for Desktop.
2. Detect the user's msysgit installation WITHOUT using the PATH environment variable. First check the default installation location, and if it's not there, prompt the user to supply a path where it's installed. Call the binaries directly from that path.
3. Operate with an embedded version of git. This can be accomplished in the same way atlassian's SourceTree works: Download a portable release of msysgit, and use the binaries from that.
4. Operate without git integration and not complain.

The user should have the option to choose any of the 4 modes in the the settings dialog, and by default, atom should attempt to use them in that order.

This suggestion is mostly based on the windows version of atom, but could apply equally across all platforms with minor modifications. Remove the github desktop option, substitute msysgit for git, etc.

**Comment by darkmorpher** [comment]
CC @damieng to comment on current ATOM version changes, _if any_.

**Comment by damieng** [comment]
This is a nice feature to have but execution is somewhat problematic.

For all the packages to reliably work git has to be in the PATH. Which means Atom would need to add it there. This is not too difficult although you'd probably have to restart Atom and is obviously a no-go for portable versions.

1. The path changed for GitHub for Desktop every release, we'd have to scan for it
2. I'm not sure this would work - normally packages/Atom shell out via cmd.exe not msysgit. Would probably require a whole bunch of additional plumbing and troubleshooting to support shelling out to bash on Windows.
3. An embedded version would be possible although going with the regular official Git for Windows binaries would seem to make more sense given 2.
4. A bunch of packages need to check things out - I think this would be an ongoing break as authors continued to expect it to be available.

**Comment by damieng** [comment]
Closing this as the original issue was referring to when Atom needed to be installed from source.

The apm.cmd in apm itself does now actually do this although the apm.cmd included with atom does not.
