### ISSUE TITLE
Add support for inline editors.

### ISSUE THREAD

**Issue by eugeneo** [atom/atom#2802]
Brackets (based on CodeMirror) provide an interface for inline editors so the plugins can provide specialized editors for colors and such or even to provide a way to edit another file without opening it.

Currently Atom plugins need to either open a popup (e.g. different color pickers) or use a panel (e.g. Regex railroad graph plugin).

**Comment by davidtaylorjr** [comment]
Any word on this?

**Comment by Fihtangolz** [comment]
Ability to cut editor tape, it can help create space. Good example of using this capabilities inline editor (like Peek Definition on VS), but I would have thought of a more general concept of embedding.
