### ISSUE TITLE
Window size error on latest (running Yosemite Dev. Preview latest)

### ISSUE THREAD

**Issue by markthethomas** [atom/atom#2804]
__Atom version__: 0.107.0
`apm` v:  0.69.0
`npm` 1.4.4
`node` 0.10.26
OS: Yosemite latest

When trying to launch Atom, I can only view the following interface (shown using exposé to illustrate size): 
![8r1iion-ozojx4w4-bemcdss2mkhc2mj7_d8nzsukrs](https://cloud.githubusercontent.com/assets/4926721/3462841/6304bd48-0232-11e4-8aa7-82aaced535c5.png)

Summary:
When not using exposé to bring up all panes, no windows are viewable. The menu bar still works and I can open files without a viewable error. However, no window panes can be viewed. 

Attempted fixes: 
I've tried restarting, clearing my node cache, but to no avail. 

Anyone else seeing this in the same enviro?

**Comment by kevinsawicki** [comment]
Closing this out, this does not seem to still be an issue on Yosemite or later.
