### ISSUE TITLE
bufferRangeForScopeAtCursor() returns only range from one line

### ISSUE THREAD

**Issue by klorenz** [atom/atom#2814]
Having a coffee script

``` coffee
   foo = ///
      first line
      second line
      ///
```

if cursor is on "first line", editor's getBufferRangeForScopeAtCursor() returns only range for "      first line", not for "\n     first line\n      second line\n    " as I expected.

**Comment by nickvanderstel** [comment]
I could really use this if it returned a range with all surrounding lines within the given scope. Any chance this will be changed?

**Comment by nathansobo** [comment]
We need to keep backward compatibility with the existing (admittedly stupid) API. We *could* add an optional boolean argument to enable multi-line, however. If anyone wants to submit a PR and ping me about it, I'm open to it.
