### ISSUE TITLE
UNIX/Mac or Windows text format option for line endings

### ISSUE THREAD

**Issue by bently0602** [atom/atom#2822]
Developing on windows machine for running on linux machines doesnt work without running through a converter. Could there be an option to switch between the different kind of formats? I'm running a Windows build of Atom v.107 and it defaults to Windows line endings when editing.

**Comment by buckleytom** [comment]
:+1:

**Comment by ipaq3115** [comment]
:+1:

**Comment by esterp** [comment]
:+1: +1:

**Comment by jessebarocio** [comment]
:+1:

**Comment by sbrech** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by konstantin-popov** [comment]
:+1:

**Comment by mocathe1st** [comment]
+1

**Comment by mletterle** [comment]
Please.

**Comment by jaustinhughey** [comment]
+1. Whether we like it or not, there are lots of folks on Windows and it's not going away, so it would be great to have an option to auto-convert all line endings to Unix standards on save. Even better if you could have it convert to Windows standards on save as an option as well (so the developer can make their own choices for their target runtime platform).

**Comment by paulcbetts** [comment]
This shouldn't be an option for the *vast* majority of cases, the only correct answer is "Save in whatever format the rest of the file is like", and if it's a new file, it's "Save in whatever format the other files in the repo are like". Doing some stats to figure this out is super easy, and it'll be right in like 98%+ of cases.

**Comment by jaustinhughey** [comment]
> and if it's a new file, it's "Save in whatever format the other files in the repo are like".

I have to respectfully disagree that this is the *only* correct answer. What if it's a new repo, with no files in it and the first thing we did was ```git init .```? Now we're going to be stuck falling back on the OS's definition of a new line, which might be the "wrong one" (aka, Windows). I'd be fine with an option to just make everything standard LF instead of CRLF - in other words, save in LF automatically regardless of the operating system. Bottom line: the community needs a way to edit in Windows and run on *nix, and converting CRLF to LF needs to be able to happen automagically.

**Comment by mark-hahn** [comment]
>  I'd be fine with an option to just make everything standard LF instead
of CRLF

I tried to do this on windows and ran into a load of trouble and gave up.
All my tools properly supported "real" LF line endings but I still had
trouble.  I admit I don't remember the specific problems right now but I
remember researching the web and finding several sites talking about how
you had to always use git translation to CR/LF.  I'm curious now.  I'll
look it up again.

**Comment by basarat** [comment]
Note that I've had issues with buffer `onDidChange` giving me reliable diffs on what it is actually going to get inserted. I've had to do: 
```ts
editor.buffer.onDidChange((diff) => {
                   // Atom only gives you an `\n` as diff but it sometimes inserts \r\n. 
                    var newText = diff.newText;
                    // This works reliably
                    newText = editor.buffer.getTextInRange(diff.newRange);
```

**Comment by paulcbetts** [comment]
>  I'd be fine with an option to just make everything standard LF instead of CRLF

This is the exact *wrong* choice. This is what .gitconfig did and it's _still_ a nightmare 8+ years later. There is no correct setting where you will not accidentally fuck up somebody else repo or files.

**Comment by mletterle** [comment]
Notepad++ as a status bar notification of what linefeeds are being used and a simple menu option under File to convert the file to one or the other format. As someone who FREQUENTLY works cross platform (sometimes literally editing a *nix file over a share in Windows) I find the functionality invaluable. 

At the least having a built-in option to set the default preference seems reasonable, likely a plugin could be written to do the notification/conversion.  I seem to recall there being at least one conversion plugin..

**Comment by NicholasGW** [comment]
:+1:

**Comment by NicholasGW** [comment]
I use https://atom.io/packages/line-ending-converter which works great for converting, but it's still a huge pain to have to remember to do it every time I edit the file, then upload it to my *Nix server. Would really love to be able to specify a default.

**Comment by msssk** [comment]
This is an editor for programmers, and programmers should absolutely have fine-grained control over the format of their code files, which is why we have things like tab size, soft vs hard tabs, and file encoding. The editor should not presume to make the choice for me for line endings. Additionally, if the editor includes a user setting for line endings, and exposes it through the API, this facilitates Atom packages that generate or modify files using the correct line ending according to user preference.

**Comment by SimonKaluza** [comment]
Fine-grained control over line endings is also an essential feature for programming in the healthcare space as the HL7 field separator is defined as the "Carriage Return".  Currently running line-ending-converter is a decent work around, but it'd be great if there were a plugin that could let us specify what character/combo to use as a line ending (upon pressing return).

**Comment by jmm** [comment]
Please fix this. Necessary:
* Dead simple way to see what type of line endings are in the open file / buffer.
* Dead simple way to toggle to the desired line ending.

That's usually a given with even relatively simple / antiquated text editors.

@paulcbetts
> This shouldn't be an option for the vast majority of cases,

What shouldn't be? A manual option to select the desired line ending, or an option to default to saving with a certain line ending, or both? The former is a no-brainer, must have. The latter is slightly less clear cut, but probably ought to be an option.

> the only correct answer is "Save in whatever format the rest of the file is like",

What is this in reference to? Did anyone even suggest anything about mixing line endings within a file?

> and if it's a new file, it's "Save in whatever format the other files in the repo are like". Doing some stats to figure this out is super easy, and it'll be right in like 98%+ of cases.

Not every file is in a repo. And setting that aside, what is a high level overview of how you propose that would work? And how do you propose that the user exert control over their own files in the unknown percentage of cases where the magical detection gets it wrong (i.e. not what the user wants)?

**Comment by jaustinhughey** [comment]
Just as an FYI, Microsoft did this already with their "Code" editor (free, multiplatform, based on electron/atom): https://code.visualstudio.com/ - it does line endings, bottom right hand area of the screen with the status bar. LF/CRLF. Defaults to platform/OS native.

**Comment by basarat** [comment]
If only it was OSS :(

**Comment by paulcbetts** [comment]
> And setting that aside, what is a high level overview of how you propose that would work?

I can tell you how it works, because I've already implemented it in GitHub for Windows :P  Run down the blobs in the current tree that have line endings and do some basic statistics on the line endings. It's not magic, most repos are like 95%+ consistently one style.

**Comment by jmm** [comment]
@paulcbetts It sounds automagical to me. Maybe that's a fine default, for the subset of files that are in git repos, but it needs to be overrideable.

> Run down the blobs in the current tree that have line endings and do some basic statistics on the line endings.

What is the performance impact of that?

**Comment by paulcbetts** [comment]
> What is the performance impact of that?

You generally only have to do it once per repo, so it's not that bad

**Comment by fgimian** [comment]
This is really essential for me and something I rely on in Sublime Text.

Sublime Text allows you to update this in the View menu:

![image](https://cloud.githubusercontent.com/assets/1811813/7901995/3c6d7d48-07e8-11e5-84bb-a6d3aaaf9b1f.png)

But more importantly, it lets you set default line endings in your settings file:

![image](https://cloud.githubusercontent.com/assets/1811813/7902002/5cad2220-07e8-11e5-8fe5-eaee3df08525.png)

This is important for users like myself who work over Samba (or similar) and edit code on a remote Linux server.  Even when I'm editing on my Windows machine, I still prefer my line-endings to be Unix format because I know that my target platform is Unix and so I don't want users to see those ugly Windows ^M characters in my code.

Atom team, would you please consider this as part of your roadmap for the 1.0 release?  The editor is incomplete without it :smile:

**Comment by llgcode** [comment]
+1

**Comment by rosshays** [comment]
Something I have noticed in sublime is that it seems when you copy multi-line text, it converts the line endings to the appropriate type for the operating system you are on. So copying unix-style line endings and pasting into notepad works as expected, but the editor still uses unix-style.

Is this something available in atom? Or that could be considered? It seems like useful behavior. I assume sublime also converts line endings to the file's kind when you paste into it, but that I haven't checked into as much.

**Comment by jmm** [comment]
@paulcbetts 
> You generally only have to do it once per repo, so it's not that bad

That's good, because it already struggles with performance and just opening files.

**Comment by chaosprinz** [comment]
+1 here. Would be realy nice. ATM, to hold consistence, while working on Win, i let get git check in with correct endings.

**Comment by ardrigh** [comment]
Also a +1 for me. 
I have used a number of different editors to convert line endings, so I was rather amazed Atom doesn't have this ability.
In the short term I have to use gvim to convert line endings.

**Comment by AluisioASG** [comment]
@ardrigh Did you try [line-ending-converter](https://atom.io/packages/line-ending-converter) linked above?

**Comment by zhouji** [comment]
+1

**Comment by danielcbright** [comment]
:+1:

**Comment by claycephas** [comment]
+1

**Comment by claycephas** [comment]
This may be too aggressive for some. But if you want to ensure you always have one type of line ending, you can place this in your init script (`~/.atom/init.coffee`). Just change `preferredLineEnding` to whatever you'd like.

    #borrowed from https://atom.io/packages/line-ending-converter
    atom.workspace.observeTextEditors (editor) ->
        editor.getBuffer().onWillSave ->
            preferredLineEnding = '\r\n'
            buffer = editor.getBuffer()
            lastRowIndex = buffer.getLastRow()
            buffer.transact ->
                for rowIndex in [0...lastRowIndex]
                    do (rowIndex) ->
                        currEol = buffer.lineEndingForRow rowIndex
                        if currEol isnt preferredLineEnding
                            lineEndingRange = new Range(
                                new Point(rowIndex, buffer.lineLengthForRow(rowIndex)),
                                new Point(rowIndex + 1, 0)
                            )
                            buffer.setTextInRange lineEndingRange, preferredLineEnding,
                                { normalizeLineEndings: false }

**Comment by jaustinhughey** [comment]
Clay, thanks for posting this, that's *really* useful!

**Comment by photofroggy** [comment]
:+1: seems like a massive oversight.

I have git on windows set up to commit and checkout as-is rather than converting line-endings.

**Comment by famousgarkin** [comment]
+1

**Comment by impinball** [comment]
+1...this is definitely an oversight. At least the case I need this for has a .gitattributes file, but it's already annoying, and I haven't even started the work yet.

**Comment by 3ffy** [comment]
I love atom, packages and everything, then i came across this "bug" and decided to still use my old sublime text editor :( ... I don't get how it's possible to publish an editor who can't handle linebreaks it's pretty or less the first thing i would have coded ! I don't want to be rude, i really love the work done so far, that's why i'm so disapointed to have to don't use it :(. Please work on this asap...

:+1:

**Comment by MattiJarvinen-BA** [comment]
This shows a major disregard of Windows users from project managers' side. I really hope they get this sorted out.

While reading comments on this issue, issue voting would remove useless +1 comments.

**Comment by impinball** [comment]
To be honest, this seems perfect for an Atom extension, one that may not last long out of core, but would be vital until then.

**Comment by jqol** [comment]
+1

**Comment by mnquintana** [comment]
Thanks for the feedback everyone! However, all these +1s and :+1:s are just adding noise, so to minimize that I'm going to lock this issue for now – this is currently being worked on as part of the [Quality Initiative](https://github.com/atom/atom/issues/7995).

**Comment by maxbrunsfeld** [comment]
Atom 1.0.8 will include the [line-ending-selector](https://github.com/atom/line-ending-selector) package, which I hope will address this issue. Sorry for the long wait everybody.
