### ISSUE TITLE
New window on Atom

### ISSUE THREAD

**Issue by mervekaya** [atom/atom#2839]
How can i add new window like in image on Atom ? I want to open two window at the same time . i looked source code of atom and i tried but i wasn't successful.

![screen shot 2014-07-07 at 9 26 35 am 1](https://cloud.githubusercontent.com/assets/6431301/3491915/e85836c6-059f-11e4-9c53-cb425598623a.png)

**Comment by mnquintana** [comment]
You can do this with `atom.open()`: https://atom.io/docs/api/v0.210.0/Atom#instance-open
