### ISSUE TITLE
[Mac] Admin password dialog not focussed when saving changes to write protected file

### ISSUE THREAD

**Issue by ddbrierton** [atom/atom#2862]
On Mac, if I make changes to a file to which I don’t have write access and attempt to save them, the dialog that pops up asking for an administrator password is not focussed, and if you start typing your password without noticing you end up typing it into the file you are trying to save. Neither Sublime Text nor TextMate do this.

**Comment by fuzzy76** [comment]
As someone who uses atom daily to edit /etc/hosts, this is really irritating :(

**Comment by danyalette** [comment]
Agreed, I think this is problematic.
If - thinking that the password field in the modal has focus - you type your password, your password appears *in plain text* in the file that you have open once the modal is dismissed. This could happen while screensharing, giving a presentation, etc.

**Comment by ddbrierton** [comment]
Actually this problem is no longer present for me, not sure when it was resolved. I am on Atom 1.4.0 and Mac OS X 10.11.2.
