### ISSUE TITLE
[Windows Alpha] Files located in deeply nested folders don't open

### ISSUE THREAD

**Issue by wdalrymple** [atom/atom#2864]
For windows.... 

Files located in deeply nested folders (or folders with very long names) won't open. It will navigate there, but:
1) the header on that file tab doesn't truncate the long path and takes up the whole windows
2) A  repeating subset of that path over and over is instead displayed in the tab header
2) the file itself doesn't open

**Comment by benogle** [comment]
Is this still an issue?

**Comment by damieng** [comment]
No response as to whether this is still an issue. Please re-open if it is.
