### ISSUE TITLE
window:save-all touches all the opened files

### ISSUE THREAD

**Issue by Zequez** [atom/atom#2871]
Due to https://github.com/atom/atom/issues/1690 now when you call `window:save-all`, all the files opened by the editor get touched. That is definitely not a good idea, since it can trigger file watcher for files that didn't change, and it can cause performance problems when you have a lot of files open and you are working on a slow disk, or with third party programs that monitor your filesystem (Dropbox, anyone?)

**Comment by b-long** [comment]
:+1:

**Comment by ssfrr** [comment]
:+1:

**Comment by levity** [comment]
+1

**Comment by TrondKjeldas** [comment]
+1

When working on a C/C++ project, saving unchanged header files can trigger massive unecessary rebuilds, hence is highly undesirable.

**Comment by michael-murphree** [comment]
+1

git status --> ALL THE THINGS...

**Comment by isaachess** [comment]
+1
