### ISSUE TITLE
Enabling the 'Use React Editor' option causes ligatures not to render with Hasklig font

### ISSUE THREAD

**Issue by bjz** [atom/atom#2880]
I have my `styles.less` set up so that it renders the [Hasklig font](https://github.com/i-tu/Hasklig)'s ligatures:

~~~css
.editor {
    text-rendering: optimizeLegibility;
}
~~~

This is with the 'Use React Editor' option unchecked in the settings:

![Without React](https://cloud.githubusercontent.com/assets/695077/3526878/c7be5f58-077f-11e4-8939-62988188cffa.png)

When I enable the React option and close/reopen the file the ligatures no longer render:

![With React](https://cloud.githubusercontent.com/assets/695077/3526903/046d0396-0780-11e4-974e-93822e35e9e9.png)

This only occurs when opening old files. A new React editor will render the ligatures fine as you type.

Interestingly the `::` operator alone renders ok in all instances when in React mode.

**Comment by murphyrandle** [comment]
Also, I'm not finding "disable hardware acceleration" in settings anymore. Was it removed?

**Comment by lee-dohm** [comment]
@murphyrandle Yes, it was. I don't have a reference to when though. Sorry :cry:

**Comment by benogle** [comment]
Closing as this is fixed on master.

[.](https://cloud.githubusercontent.com/assets/69169/10744473/73c9d75e-7bf7-11e5-82b1-1871793f0eb8.png)
