### ISSUE TITLE
Alt+Shift+S executes as Alt+S and Alt+Shift+S.

### ISSUE THREAD

**Issue by gjatkinson** [atom/atom#2906]
I'm on Windows 7, Atom version 0.113.0.

When I use Alt+Shift+S, I get two menu - both the Alt+S menu and the Alt+Shift+S menu. Alt seems to underline the menu options that can be selected next (F for File, E for Edit, etc.) but that underlining, and the ability to select a menu option, should go away if the next pressed key is not one of the menu options. Other windows apps like MS Word work this way. Below is the screen shot of the result of press Alt+Shift+S - I get both the menu dropdown for Selection and the Snippet window.
![2014-07-10 10_48_18-untitled](https://cloud.githubusercontent.com/assets/1690018/3541310/eb9e9cd2-084a-11e4-91fe-f85e544377ca.png)

**Comment by damieng** [comment]
Unable to repro - assuming fixed either in Electron or Atom in the intervening time. Please comment here if you run into this issue in recent Atom builds so we can re-open.
