### ISSUE TITLE
TextBuffer::setText won't doesn't work

### ISSUE THREAD

**Issue by ibigbug** [atom/atom#2930]
Calling `TextBuffer::setText` to the Buffer, the content will be replaced again by the file content on the disk.

So I must call `buffer.save()` after `buffer.setText('something')`. However this is not what we want.

**Comment by izuzak** [comment]
I can't reproduce this on Atom 1.0.4-d5a86c1 and OSX 10.10.4. If anyone can still reproduce this in the latest version of Atom (in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)) -- please let us know, and provide exact steps to reproduce and the OS+version you're using.
