### ISSUE TITLE
Middle Mouse Button Sroll Cursor Not Visible

### ISSUE THREAD

**Issue by FalconGames** [atom/atom#2944]
The middle mouse button scroll mode, which is available in most Windows applications, works, although it does not display the cursor -- the cursor just straight-up disappears when you press the middle mouse button.

**Comment by jerone** [comment]
Confirmed _Windows 7 64-bits_ and _Windows 8.1 64-bits_ on _Atom 0.201.0_.

**Comment by damieng** [comment]
Can't get cursor to disappear.  I think middle-button-scroll-mode would be an enhancement.

**Comment by jerone** [comment]
> Can't get cursor to disappear.

Can not confirm this issue anymore. Even middle-mouse-button-scroll doesn't seem to work anymore (with or without cursor).

_Atom 1.9.8_

**Comment by Ben3eeE** [comment]
> I think middle-button-scroll-mode would be an enhancement.

There is an enhancement for middle mouse scroll already https://github.com/atom/atom/issues/6884

**Comment by damieng** [comment]
Will track on #6884
