### ISSUE TITLE
Cannot select folded block of code

### ISSUE THREAD

**Issue by spascalb** [atom/atom#2953]
Folded block of code can't be selected (in order to delete, copy or move folded) as in ST. It unfolds when clicked.

**Comment by timkelty** [comment]
This behavior is bugging me too.
Here's the situations I'm noticing (beginning with a folded block, with the intention of selecting it and deleting it):

- From the beginning of that line, `shift + ↓` selects the whole block without expanding :)
- From the beginning of the line following the folded text, `shift + ↑` selects the whole block without expanding :)
- triple clicking line, expecting line selection, expands text :(
- selecting the entire line above the folded code, expands it :( :question: 
- `⌘ + l` (select line) expands fold :(
- selection with the cursor is just weird....can only put cursor at beginning of line. If I drag to the right (to select the line) nothing happens. I can only select the line be clicking and dragging down to the next line.

**Comment by DophinL** [comment]
why is it still exist? that's really inconvenient..

**Comment by bowen31337** [comment]
It is really a bad UX that the folded line can not be selected on its own, and it only works when being selected together with adjacent lines.

**Comment by MikeWillis** [comment]
I stumbled onto this while searching for solutions to a similar problem. Has anyone else noticed that if you select all, any folded sections are automatically unfolded? Could be one of my packages, or a setting, I haven't investigated too closely yet.
