### ISSUE TITLE
Installing packages fail

### ISSUE THREAD

**Issue by valsamakis** [atom/atom#2963]
When I try to install a package form gui or command line I got an error 

PS C:\Users\grmsevf8> apm install atom-beautify
Installing atom-beautify to C:\Users\grmsevf8\.atom\packages
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.26 | win32 | ia32
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.11.10/node-v0.11.10.tar.gz
gyp WARN install got an error, rolling back install
gyp
PS C:\Users\grmsevf8>

**Comment by tborychowski** [comment]
I have the same issue - cannot install any package or theme (using neither `apm` nor settings UI).
e.g.:
```sh
> apm install autocomplete-plus
Installing autocomplete-plus to C:\Users\i313281\.atom\packages
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp WARN install got an error, rolling back install
gyp
```
My setup:
```sh
> apm -v
apm  0.157.0
npm  2.5.1
node 0.10.35
python 2.7.3
git 1.9.5.msysgit.0
visual studio 2012
```

**Comment by tborychowski** [comment]
seems related to https://github.com/atom/apm/issues/322

**Comment by kevinsawicki** [comment]
Yeah, I believe this is a proxy issue with apm that is being tracked in https://github.com/atom/apm/issues/322
