### ISSUE TITLE
Just can't build for Linux Mint 

### ISSUE THREAD

**Issue by aovchinn** [atom/atom#2967]
(and that not issue i think, but where else I can find a solution?)

passed all the steps in here: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

but get this
![screenshot from 2014-07-14 17 28 06](https://cloud.githubusercontent.com/assets/3647829/3571311/eaf6f1da-0b5b-11e4-822d-7dd7a8f034e2.png)

**Comment by mnquintana** [comment]
Gonna close this out - please feel free to reopen / comment if you can reproduce this with the latest version of Atom (0.210.0) and the [latest build instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md).
