### ISSUE TITLE
Atom crashes immediately after opening on Windows 7 x64

### ISSUE THREAD

**Issue by cobrabr** [atom/atom#2969]
Hi,

I installed Atom via Chocolatey (and also tried the ZIP file), but I cannot use it. The installation runs fine, but whenever I run the executable, I get a popup window with a *"The editor has crashed"* error message, which includes 3 buttons: Close Window, Reload and Keep It Open:

![image](https://cloud.githubusercontent.com/assets/724969/3572974/377779e2-0b6d-11e4-9b80-146a35193ddc.png)

Quickly searching through the code repo, I found out that this error message is generated by the handler of the `@browserWindow.webContents.on 'crashed'` event (in `/src/browser/atom-window.coffee`), but I don't know what could be causing the browserWindow to crash, since my teammates' computers are identical to mine, and they can all run it just fine.

I've just updated to version 0.115.0, but the error persists.

Thanks,
Luciano.

**Comment by thiagolucio** [comment]
Outher solution, simple and fast is return to version 1.0.19 and whait the new stable version..but is a lazy solution :(

**Comment by damieng** [comment]
Very old bug that is almost certainly solved with newer versions given lack of activity.

**Comment by napalm23zero** [comment]
@yunga your tip worked nicely to me
but still take too long to start

**Comment by ovenslove** [comment]
Same issue for me. version-1.13.0 ia32/window 10. The problem appeared about 10 times a day, but i run "atom --safe" ,There is no problem。i think it due to the large project or install the plugin too much . Meanwhile .the CPU occupancy is particularly high and the memory occupancy increased gradually .
