### ISSUE TITLE
Dragging shortcuts to folders

### ISSUE THREAD

**Issue by jasonhansel** [atom/atom#2985]
Currently, dragging a shortcut to a folder in Atom (on Windows) opens the `.lnk` file itself rather than the target of the shortcut; the latter behavior would make more sense. I keep a bunch of shortcuts to project folders on my Desktop and it would be nice to be able to drag the shortcuts directly into Atom and have the project itself be opened (rather than the `.lnk`)

**Comment by 1j01** [comment]
:+1: If I have projects in my favorites bar, I would like to be able to drag them to atom to open them.

**Comment by 1j01** [comment]
By the way, there's [a module](https://www.npmjs.com/package/windows-shortcuts) for dealing with shortcut files.

**Comment by diminutivesloop** [comment]
Suprised this issue has been quiet for so long. Seems obvious that `.lnk` files should be treated the same as aliases are treated on OS X.
