### ISSUE TITLE
Atom v0.117.0 on Windows 7, black screen

### ISSUE THREAD

**Issue by helmus** [atom/atom#2998]
I just installed Atom v0.115.0 on windows 7 x64 using chocolatey. Installation seemed to work fine, but When I launch the app ( with or without elevation ) I can see the menu bar but the editor area is black and just remains black. I tried `New File`, `New Window`, `Reload` but nothing seems to have any effect.

EDIT:
Updated to v0.117, same results

![image](https://cloud.githubusercontent.com/assets/1042463/3610190/8fa31cf4-0d87-11e4-8f70-ad80547af158.png)

**Comment by benogle** [comment]
Is this still an issue for anyone on the latest version?

**Comment by fskinner** [comment]
yep. i'm having this issue on my new DELL PC. (on my previous Vaio it was ok tho)

**Comment by batjko** [comment]
@fskinner How did you install it, which OS and Atom versions are you on, and does it still happen if you start atom in safe mode (`atom --safe`)?

**Comment by fskinner** [comment]
@batjko I'm on Windows. Just downloaded the AtomSetup.exe from the site. I just re-downloaded on past week so i guess I´m on v1.0

And yes. It still happens even using atom --safe :(

**Comment by fskinner** [comment]
just got Atom running by forcing it to use my Intel HD Graphics instead of my NVIDIA chipset! weird tho

**Comment by mortalisk** [comment]
I have this issue in a virtual machine. It also happens with chrome.

**Comment by Phaedra144** [comment]
It also happens to atom and chrome if I wanna switch between them, thankfully I have a magical touchpad and can check out from the black screen, still no solution? :(

**Comment by rsese** [comment]
Since this issue is pretty stale, can you open a new issue and fill out the issue template @Phaedra144 so we can take a look?
