### ISSUE TITLE
Cmd + Shift + D should duplicate currently selected word

### ISSUE THREAD

**Issue by valllabh** [atom/atom#3002]
Cmd + Shift + D should duplicate not only current line, but current selection if available.

Sublime Text allows it !! :hushed:

**Comment by nick** [comment]
:+1: Would love to see this too.

**Comment by steelbrain** [comment]
I just feel like I am gonna create this package.

**Comment by steelbrain** [comment]
Here you go people, https://atom.io/packages/duplicate-selection

**Comment by nick** [comment]
@steelbrain thanks but I wanted it more sublime style, where it would duplicate the line if there was no selection, otherwise it would duplicate the current selection. Also wanted the buffer selection to be the same as sublime.

I created https://atom.io/packages/duplicate-line-or-selection which basically mirrors sublime duplication functionality.

**Comment by varemenos** [comment]
thanks @nick, really needed this behavior, it's one of the golden things about sublime that I would miss for sure.

**Comment by kirkch** [comment]
Fantastic, thank you for the new package!

For the record, it is not just sublime that behaves like this.  I for one cannot live with out it, this should be the default behaviour.

**Comment by ZeeCoder** [comment]
Thanks @nick! That is just what I wanted. :+1:

**Comment by hacfi** [comment]
Sweet @nick - works like a charm

**Comment by jpillora** [comment]
thanks @nick +1 for adding this into atom core

**Comment by nilssanderson** [comment]
Thanks @nick so great!
+1 for atom core too.

**Comment by ichbinedgar** [comment]
Thanks @nick!  :+1:

**Comment by Yappli** [comment]
Thanks @nick, you are a good man.

**Comment by robsonsobral** [comment]
I agree to @kirkch . This should be the default behavior. It will not create any problems, but it will give us flexibility.

I can't see this as an "special case".

**Comment by hacfi** [comment]
:+1: for putting @nick ’s code into atom "core"

**Comment by davePlug** [comment]
Thanks @nick, Brilliant!
Would love to see this in the base atom core.

**Comment by dlcdiego** [comment]
Thanks!

**Comment by emamut** [comment]
@nick very pleased with your contribution, I hope to see you soon in the core :+1:

**Comment by hacfi** [comment]
@lee-dohm Any plans to integrate this into atom? I really think that this functionality is a general feature you could expect from an editor and not a special case for a separate package.

**Comment by lee-dohm** [comment]
We don't currently have an ETA on when we would be able to get around to this. Pull requests are always welcome.

**Comment by thebarty** [comment]
@nick: Thanks a lot for creating the package! So happy to have it! 👍
