### ISSUE TITLE
BSOD on Windows with NFS share

### ISSUE THREAD

**Issue by rileywhite** [atom/atom#3010]
This occurs intermittently (but regularly) when browsing an NFS shared directory through tree view. It has also happened when closing tabs  with files opened from the NFS share.

Atom version is 0.115.0.

The opened directory contains several gigabytes of code, but it also seems to happen on opened subdirectories that are much smaller.

The files are perl, though that probably does not matter.

![bsod](https://cloud.githubusercontent.com/assets/869495/3627732/a6eb791e-0e8c-11e4-8e74-c391b34e26f8.jpg)

Additional information provided on Windows startup after the crash:

    Problem signature:
      Problem Event Name:	BlueScreen
      OS Version:	6.1.7601.2.1.0.256.4
      Locale ID:	1033

    Additional information about the problem:
      BCCode:	27
      BCP1:	00000000BAAD0073
      BCP2:	FFFFF8800F14A7C8
      BCP3:	FFFFF8800F14A020
      BCP4:	FFFFF8800C06BDA0
      OS Version:	6_1_7601
      Service Pack:	1_0
      Product:	256_1

**Comment by davidbrochart** [comment]
Any progress on this issue? I have the same problem.

**Comment by paulcbetts** [comment]
There is nothing that we can do about this, you need to contact Microsoft or (more likely) upgrade to Windows 8.1.

**Comment by opichals** [comment]
I have just seen this a couple of times when closing Atom in Windows 8.1 Enterprise

**Comment by bdjnk** [comment]
@paulcbetts I've also experienced this issue. My coworkers and I now have a negative impression. Somehow other editors, from Notepad++ to Sublime to Eclipse manage this situation just fine.

**Comment by 50Wliu** [comment]
Re-opening as this isn't resolved in Windows 8.1.

**Comment by paulcbetts** [comment]
It is very unlikely that can do anything about this bug other than hope that Microsoft fixes it.

**Comment by damieng** [comment]
Agree with @paulcbetts a user-mode application should not be able to cause BSODs. This is firmly in Microsoft's court.
