### ISSUE TITLE
Clicking file quickly opens the file twice

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#3029]
If you click the same entry in the tree view a second time before the first one opens, it will open two editors for that file.

Noticed this while testing a slow network drive on Windows but it isn't Windows specific since it can happen whenever loading a file is slow.

**Comment by mnquintana** [comment]
I can't reproduce this with OS X 10.10.3, Ubuntu 15.04, or Windows 8.1 with Atom 0.210.0. I'm going to close this for now, but we can always reopen if it crops up again.

**Comment by corsen2000** [comment]
This happens consistently for me after first opening the editor.  If I let the editor sit for a minute before clicking it does not occur.  It occasionally reoccurs even after the editor has been opened for some time.

**Comment by ldynia** [comment]
The same here

**Comment by ZuchaoWang** [comment]
I also have this problem in OSX 10.11.5, atom 1.8.0

**Comment by keathmilligan** [comment]
Also present in 1.9.0-beta0.

**Comment by thelamborghinistory** [comment]
can confirm for atom 1.8.0 on osx 10.11.5.

**Comment by 50Wliu** [comment]
This had been fixed, but it has not been published yet.  atom/tree-view#847.
