### ISSUE TITLE
Linux unable to edit commit message from atom

### ISSUE THREAD

**Issue by Frozenfire92** [atom/atom#3030]
Ubuntu 14.04 x64
Atom 0.116.0-4960a63

[Forum Post](http://discuss.atom.io/t/linux-edit-commit-message-automatically-aborts/11004)

I have tried setting atom as my git editor with
```
 git config --global core.editor atom
 git config --global core.editor atom -w
 git config --global core.editor atom --wait
```
and whenever I go to commit atom will open but git automatically cancels via `Aborting commit due to empty commit message.`

![atomgiteditor](https://cloud.githubusercontent.com/assets/5893112/3651703/67f0c136-112c-11e4-82c9-85dfe0eae101.png)

**Comment by moozzyk** [comment]
+1

**Comment by sedabull** [comment]
+1

**Comment by lachy-xe** [comment]
:+1: on Windows 8.1

**Comment by jayflo** [comment]
+1

Windows 7
Atom v0.208.0

**Comment by 50Wliu** [comment]
I'm going to close this in favor of #3074 which seems to have a few workarounds and suggestions.
