### ISSUE TITLE
Tab Length Detection

### ISSUE THREAD

**Issue by muchweb** [atom/atom#3043]
Default setting for tab length is 2 spaces.
- When I open a file that uses 3 spaces for indentation, and press `Tab`, I expect editor to insert 3 spaces (currently 2)
- When I open a file that uses 4 spaces for indentation, and press `Tab`, I expect editor to insert 4 spaces (currently 2)

There already were discussions to allow custom settings [per language](https://github.com/atom/atom/issues/1723) or [per project](http://rosettacode.org/wiki/Knapsack_problem/Bounded#JavaScript), although **this issue is do detect indentation automatically on file open**, because there can be different guidelines for same language files on same project. It is also handy when editing unrelated files.

Default 'tab width' setting is to be still used when creating new files and for `\t` display width.

---

Here is a screenshot from proprietary Sublime Text (some of these features are for [atom/whitespace](https://github.com/atom/whitespace), but I think initial detection should be handled in core.

![tab_size](https://cloud.githubusercontent.com/assets/7157049/3666025/3ab2ba06-11ec-11e4-81c3-d125259a0eef.png)

**Comment by driskell** [comment]
@muchweb I've been tampering with Atom to make the way indentation is displayed separate from the way it is saved to a file.

So if you have a indentation width set to "4 characters" - and you load a file with tab width of 2, the loaded file, you see this:

![Image](https://github.com/driskell/tabulation-control/blob/master/SNAPSHOT1.png)

Planning to make it so it can automatically set the indentation width to match in the event you don't really have a width preference.

Just thought I'd gather some thoughts :-)

**Comment by driskell** [comment]
@muchweb I've been tampering with Atom to make the way indentation is displayed separate from the way it is saved to a file.

So if you have a indentation width set to "4 characters" - and you load a file with tab width of 2, the loaded file, you see this:

![Image](https://github.com/driskell/tabulation-control/raw/master/SNAPSHOT1.png)

Planning to make it so it can automatically set the indentation width to match in the event you don't really have a width preference.

Just thought I'd gather some thoughts :-)

**Comment by JordiOrlando** [comment]
@driskell What you've done looks absolutely fantastic. Is it anywhere near stable? If so, I'd love to try it out and give you my thoughts.

**Comment by driskell** [comment]
It is stable. I'll do some rebasing and update to latest atom though. I've been testing other patches lately.

**Comment by JordiOrlando** [comment]
Awesome, I look forward to testing it out.

**Comment by driskell** [comment]
The specific code that detects the tab length when using spaces I'll be raising as a PR here soon too so at least your original request would be implemented hopefully. Just I have another PR to fix some other issue and I don't like to raise more than 1 at once - but if that doesn't go forward in next few days I'll raise it anyway.

My changes for the enforced width preference so even 2 spaces "appears" as 4-width indentation - that's a bigger change and probably contentious - likely leave it till last :-)

**Comment by Ciantic** [comment]
@driskell is it also possible to align the cursor to non-existent indentation in empty line?

Typically the Atom (using whitespace package) removes the indentation from empty lines, such as:

    function something() {
        if (something) {
            // ...
        }
        
        aboveLineIsEmpty();
    }

If I move cursor to line above the "aboveLineIsEmpty()" cursor jumps to zero column because it was emptied by whitespace plugin. It's fine to leave the line empty, but cursor should still have indentation when I go to it, and the indentation should appear magically when I start typing there.

If I understand your effort, it can add phantom indentations and could also be used to this.

**Comment by driskell** [comment]
I'm going to raise a PR for detecting tab length as well as tab type when opening a file. I was waiting for my current one to merge or progress but it has completely stalled so guess I'll just do this one alongside.

@Ciantic That's a good thought. I'll ponder on that soon. I like the term "phantom whitespace" btw :-) Probably not new but first time I've heard it!

**Comment by lee-dohm** [comment]
Related: #11049

**Comment by marcoms** [comment]
Any updates on this? Its not great having to change my global indentation settings when opening a project with a different tab length :(

**Comment by alexandernst** [comment]
Just as a reminder from #11049 , there is a great article on medium about code indent detection: https://medium.com/firefox-developer-tools/detecting-code-indentation-eff3ed0fb56b

**Comment by nirabhratapaswi** [comment]
@muchweb, @0xdec, is this issue resolved? Or can I work on it?
I am very new to opensource and wanted to get started, this seems like something I can fix.

**Comment by lee-dohm** [comment]
@nirabhratapaswi The issue is still marked `Open` so it is not yet resolved.

**Comment by muchweb** [comment]
@stale how about you stop closing perfectly good issues to fake statistics, and maybe work on code to actually fix them.
