### ISSUE TITLE
Make invisibles tab character span multiple spaces

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#3051]
In other editors I'm used to have a wide character (em dash) representing a tab and while Atom has something like that, it doesn't work quite how I'd expect it to work.

Currently, if you set an em dash in "Invisibles Tab" field and "Tab width" to 4 spaces, the em dash would be painted with the width of a single character. Here is a screenshot showing this:

![alt text](https://virtual-host-discourse.global.ssl.fastly.net/uploads/github_atom/23682/5e3564883ffa487d.png "Bug invisibles tab")

Note that the em dash should have the width of 4 spaces.

Brackets fixed this in a really cool way, VIM has it also. This way, IMHO, should be how this should work:

The "Invisibles Tab" setting should have 2 fields. The first field is for the character that should be used to fill the space of the tab. And the second field is for the character that should finish the drawing (if any).

Practical examples of this setting:

Example A
First character: -
Second character: >
Result for 4 spaces: --->

Example B
First character: -
Second character: -
Result for 4 spaces: ----

Regards

**Comment by Felicis** [comment]
I found a fix, that achieves almost the desired result: 
just use the "LONG ARROW RIGHTWARDS" (0x27f6)  character in the unicode table, which is really wide and comes really near to the wide dash I'm used to: "⟶"
![selection_017](https://cloud.githubusercontent.com/assets/11877488/10863853/39782d68-7fd9-11e5-9f6f-eef7e4331111.png)

Best

**Comment by alexandernst** [comment]
This is indeed a really nice trick!

**Comment by alexandernst** [comment]
Spoke too soon. It's not looking good here: http://ibin.co/2KwgTvtt2TEr

**Comment by Felicis** [comment]
you sure you took the right character?
for me it looks like the closely related simple right arrow...
Best

**Comment by natbraun** [comment]
@alexandernst I'd be happy to work on this issue. However, we need to specify it precisely. Here is a tentative specification. There are several 'kinds' of tabs users could want to use:

A. Mandatory first  character, and repeating secondary character. For the '>' and '-' couple, and for length 1, 2 and 5 the tabs would respectively show like this '>', '>-', '>----'

B. Mandatory last character, and repeating preceding character. For the '-' and '>' couple, and for length 1, 2 and 5 the tabs would respectively show like this '>', '->', '---->'

C. Mandatory last character, optional first character and repeating middle character. For the '<', '-' and '>' triplet and for length 1, 2 and 5 the tabs would respectively show like this '>', '<>', '<--->' (notice the last character is used when length is 1, not the first character)

It's possible to support all three at once. Thanks for your feedback.

**Comment by alexandernst** [comment]
I think what most (all?) common editors do is option B. This is also how I'd like it the most.
C could also fit in as a possible fix for the issue because it's basically B + an initial character. It has the benefit of allowing even more styling option, so I'd say "go with C".

**Comment by natbraun** [comment]
@alexandernst vim & emacs implement option A, I think. On the other hand, Notepad++ uses a nice arrow, similar to option B. We can do a mix of C & B, meaning:

- If two characters are set:
   * the first one is mandatory
   * the second one is repeated to fill the length
- If three characters are set:
    * the last one is mandatory
    * the first one is put if the tab is at least of length 2
    * the middle one is repeated to fill the length

**Comment by natbraun** [comment]
This way, you can emulate option A by setting the first two characters to the same character, I think

**Comment by alexandernst** [comment]
Yes, I like it, it does sound reasonable and I can't think of a situation in which it won't work.

**Comment by natbraun** [comment]
Perfect :)

**Comment by lee-dohm** [comment]
I'm unifying all invisibles-related Issues under #12157. You may want to subscribe there for updates.

**Comment by trinet-jieli** [comment]
Thanks, Felicis! Your solution works for me! My result.

<img width="463" alt="atom-result" src="https://cloud.githubusercontent.com/assets/17131675/18009422/3636f7e6-6b7a-11e6-9942-ba78fcf8a1fc.png">

2 steps to achieve this.
1. enter long arrow in Settings > Invisibles Tab field using Mac Keyboard Viewer

<img width="620" alt="atom-invisible-tab" src="https://cloud.githubusercontent.com/assets/17131675/18009490/799e9d9a-6b7a-11e6-89af-f6f6f1545a21.png">

![mac-show-keyboard-viewer](https://cloud.githubusercontent.com/assets/17131675/18009528/aa724d0e-6b7a-11e6-998b-c0ae292ab2b9.png)

2. set the Tab size to 1 in Settings > Tab Length field

<img width="326" alt="atom-tab-size" src="https://cloud.githubusercontent.com/assets/17131675/18009567/d4c26e90-6b7a-11e6-91da-d704713dec25.png">

Enjoy!

**Comment by phuongkt** [comment]
.

**Comment by Rojuinex** [comment]
I've found that ⏤ (U+23E4) the symbol for straightness works well as an analog for the types of dashes in sublime text.  It isn't as long but it brings that familiarity back.
