### ISSUE TITLE
Open folder on linux is broken

### ISSUE THREAD

**Issue by jwir3** [atom/atom#3063]
**Steps to Reproduce:**
1. Select File -> Open Folder.
2. Navigate to folder where you want to open (E.g. Double click on 'File System', then 'tmp', then 'blah'. Blah will be opened in the file chooser window.
3. Click 'Ok'.

**Expected Results:**
:white_check_mark:  Atom opens folder /tmp/blah for editing.

**Actual Results:**
:x: Atom opens user's home folder (in my case, /home/sjohnson).

In order to actually open the folder I want, I would have to navigate to /tmp and then select (but not double-click) blah. I think that, if nothing is selected in the current folder in the navigation window, it should use the current folder instead of the user's home folder.

**Comment by igorpan** [comment]
Same for me on ElementaryOS Luna

**Comment by i2000s** [comment]
Same here on Atom 0.187.0 and Ubuntu 12.04.

**Comment by OscarOrSomething** [comment]
I read somewhere this was waiting on atom/electron#613 , That is closed so is this working now?

**Comment by mnquintana** [comment]
Yup, this should be fixed now (with an OS update for anyone experiencing this still). Thanks!
