### ISSUE TITLE
Duplication opened files when relaunching atom

### ISSUE THREAD

**Issue by BOOMER74** [atom/atom#3065]
When I relaunch atom with opened files (stored in session), file open again (and again if tab not closed when exit). [Win8.1, 0.117]
![image](https://cloud.githubusercontent.com/assets/4272432/3687166/132117b6-1323-11e4-9347-647db8c98867.JPEG)

**Comment by kevinsawicki** [comment]
Closing this out as something that was probably fixed over the last year by rewriting how Atom saves/loads window state, support for reopening windows, support for multi-folder projects, and general bug fixes to the `atom.workspace.open` API.

Please comment if you still see it happening on Atom 1.0.3+
