### ISSUE TITLE
atom --wait doesn't wait

### ISSUE THREAD

**Issue by xori** [atom/atom#3074]
Version 0.118.0 on Windows 7 x64

    PS C:\ > atom --wait myfile.txt

Immediately terminates, but does continue to open the file. Expected result is to wait until the file is closed in the editor.

https://github.com/atom/language-git
and
http://blog.atom.io/2014/03/13/git-integration.html 
say that the syntax that I'm using is correct. Is there a new syntax to enable this or is this feature no longer supported.

**Comment by jordao76** [comment]
I think that the correct way to use atom for `git commit` is: `atom --new-window --wait`. This way, it opens a new window and shouldn't interfere with a currently running instance. 

But, if I already have a running instance, the new window is opened, but the command won't wait. So, this is still a bug. I'm using `0.190.0`.

So, to reproduce:
1. Run `atom`, this opens atom and doesn't wait, which is OK
2. Run `atom -n -w`, this opens a new atom window but doesn't wait, which is **not OK**

Note that doing step 2 alone works.

**Comment by jordao76** [comment]
I think that the correct way to use atom for `git commit` is: `atom --new-window --wait`. This way, it opens a new window and shouldn't interfere with a currently running instance. 

But, if I already have a running instance, the new window is opened, but the command won't wait. So, this is still a bug. I'm using `0.190.0`.

So, to reproduce:
1. Run `atom`, this opens atom and doesn't wait, which is OK
2. Run `atom -n -w`, this opens a new atom window but doesn't wait, which is **not OK**

Note that doing step 2 alone works.

**Comment by ccoenen** [comment]
What if `--wait` would imply `--new-window`? I can't really think of a use case, where i would want to edit something in an existing editor and then wait around until that one gets closed.

If this is / should be the case already, just ignore my message

**Comment by jordao76** [comment]
I think you're right! It looks like it implies that already. So no need for `--new-window`...

**Comment by robnext9981** [comment]
I've got the same strange behavior as @jordao76 explained.
Really annoying for newbie...I've got to change default editor :worried: 
Here's my dev environment \: 
Atom 0.209.0, Windows 7 Professional SP1 x64

**Comment by jacaseyclyde** [comment]
Still happening in v1.0.2. guess i'll jsut have to use npp for commits for now

**Comment by robnasby** [comment]
This is an issue for me as well on Atom v1.0.2, running on WIndows 7 x64.  Git opens Atom for interactive rebase, etc. but doesn't wait.  I've tried --wait and --new-window --wait, without luck.

**Comment by oomlaut** [comment]
Using 1.0.3 on Windows 7. Experiencing this issue only when Atom is already running.

**Comment by openben** [comment]
1.0.7 on Windows 8.1 -> same problem

**Comment by collinjackson93** [comment]
Using 1.0.10 on Windows 10. I have this issue regardless if Atom is already running or not.

**Comment by abhisekp** [comment]
+1

I've the same issue in **Win 7 SP1 x64** using **Atom 1.0.11**

With a running atom editor instance, I tried with the following, but to no success. :worried: 
- `atom --wait`
- `atom --wait --new-window`
- `atom --wait --foreground`
- `atom --wait --new-window --foreground`

*The process didn't wait.*

**Comment by abhisekp** [comment]
@paulcbetts could you please explain about the `update.com` trick?

**Comment by unguiculus** [comment]
Same here. Only works if Atom isn't already running.

**Comment by bijeebuss** [comment]
+1

**Comment by mnquintana** [comment]
Thanks for the feedback everyone! However, all these +1s and :+1:s are just adding noise, so to minimize that I'm going to lock this issue for now – we may unlock it once someone starts working on this enhancement to get further feedback.

**Comment by 50Wliu** [comment]
This has been fixed and should be out in Atom 1.6.0.
