### ISSUE TITLE
Separate core/installed packages in Settings view

### ISSUE THREAD

**Issue by toddmbloom** [atom/atom#3090]
Would it be possible to separate the package list by core and custom? Or, perhaps, have a checkbox to hide core items and only show custom ones? I know I can see the author but sometimes the text is pretty small and I just want to see everything I personally added to adjust settings quickly or disable. 

Also - and I'm not sure how difficult it would be - but is there any way to provide reports on package usage maybe? Like a graph showing how each of them contribute to start up time or something? I know you can click on each one but sometimes it's nice to see a breakdown and determine what is really needed.

**Comment by mnquintana** [comment]
Packages are listed by category in Settings View now - closing
