### ISSUE TITLE
LSOpenURLsWithRole() strikes back

### ISSUE THREAD

**Issue by aclissold** [atom/atom#3093]
I am unable to open Atom from the command line on Mac OS X 10.10 (Beta 4)—I don't remember when it broke or what caused it, but re-downloading/re-installing the command line tools didn't fix it. I believe this is different from #1103 because I'm on Atom `0.119.0`.

I investigated which line of `/usr/local/bin/atom` was causing the error and discovered that

```
open -a /Applications/Atom.app
```

works fine, but

```
open -a /Applications/Atom.app -n
```

causes the error.

Full error message:

```
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.
```

**Comment by Dentosal** [comment]
For me it crashes every time. I have tried: inside tmux, outside tmux and from dock. It crashes every time. Crash report it always same, and it can be seen on my own issue report https://github.com/atom/atom/issues/6135.

**Comment by fb55** [comment]
Atom stopped working for me completely:

```sh
$ atom
LSOpenURLsWithRole() failed for the application /Users/feedy/Applications/Atom.app with error -10810.
$ reattach-to-user-namespace atom -v

$ reattach-to-user-namespace atom
LSOpenURLsWithRole() failed for the application /Users/feedy/Applications/Atom.app with error -10810.
$ /opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/MacOS/Atom
dyld: Library not loaded: @rpath/Atom Framework.framework/Atom Framework
  Referenced from: /opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/MacOS/./Atom
  Reason: no suitable image found.  Did find:
	/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/MacOS/../Frameworks/Atom Framework.framework/Atom Framework: code signature invalid for '/opt/homebrew-cask/Caskroom/atom/1.0.7/Atom.app/Contents/MacOS/../Frameworks/Atom Framework.framework/Atom Framework'

Trace/BPT trap: 5
```

This started with a restart to upgrade to the latest version. I only saw a white window, which I force-quit after several minutes. Now, atom crashes every time I try to start it.

**Comment by darkn3rd** [comment]
I don't have tmux installed, but it is happening for me.

**Comment by jdsimcoe** [comment]
This is happening for me when using [Black Screen](https://github.com/black-screen/black-screen/i) on `OS X`:

https://github.com/black-screen/black-screen/issues/58

**Comment by jamesward** [comment]
For me this issue was due to my unzip tool not preserving the symlinks in `Atom.app/Contents/Frameworks/Electron\ Framework.framework`

**Comment by jdsimcoe** [comment]
@jamesward How would I go about fixing this?

**Comment by jamesward** [comment]
@jdsimcoe Electron could not use symlinks.

**Comment by gabriel** [comment]
FYI, I think this can happen is the executable name changes (Gatekeeper gets confused)... e.g. Foo.app/Contents/MacOS/Electron to Foo.app/Contents/MacOS/Foo

**Comment by gabriel** [comment]
The electron-packager changed recently which changes the executable name from Electron to app name: https://github.com/electron-userland/electron-packager/commit/aaeee768cfbcc7932a1413161afe2a3df28490eb

**Comment by opes** [comment]
FWIW, I had this issue when trying to use a terminal (terminal-plus extension) within Atom to open a file within my current Atom session. The fix mentioned above in the original issue filing, while not ideal, did indeed fix it for me. I am not using `reattach-to-user-namespace`.

To be explicit about what I changed, I did the following:

1. `vim /usr/local/bin/atom`
1. Changed line 88 (for me) to match the following (just removed the `-n` option):
  `open -a "$ATOM_PATH/$ATOM_APP_NAME" --args --executed-from="$(pwd)" --pid=$$ --path-environment="$PATH" "$@"`
1. Reloaded my shell
1. `atom /path/to/some/file` was working again.

**Comment by nixpulvis** [comment]
@opes doing this fixed the error, but doesn't actually make the files open when running `atom <path>`.

**Comment by fndaily** [comment]
The only that works for us so far in **OS X 10.12.2** is to add the following to your ~/.bash_profile or relevant shell script:

`alias atom="open -a /Applications/Atom.app/Contents/MacOS/Atom"`

**Comment by Hum4n01d** [comment]
That's basically what I do

**Comment by robrecord** [comment]
It doesn't seem to help for me.
Changing the executable as @opes says fixes the error but doesn't open the file.
Creating the alias doesn't stop the error for me.

This is when using git via terminal-plus

**Comment by ivorscott** [comment]
@fndaily nice

**Comment by tbehrsin** [comment]
I got this when running atom within `platformio-ide-terminal` (`terminal-plus`).

I was able to bypass the error using a wrapper shell script:

```bash
#!/usr/bin/env -i bash
exec atom $@
```

`env - i` resets the environment... so `terminal-plus` should probably be sanitising Atom / Electron environment variables when creating a terminal window.

**Comment by kmsquire** [comment]
For those having this problem in iTerm.app after upgrading that app, see 

   https://gitlab.com/gnachman/iterm2/issues/4694

which points to

   https://gitlab.com/gnachman/iterm2/wikis/brokenafterupdate

**Comment by chrislovecnm** [comment]
I am suddenly having this problem from within iTerm2 and when I exec atom from the LaunchPad.  Tried some of these work around to no luck.  Any update on this?

**Comment by kenhkelly** [comment]
I'm having this issue too. I am not using tmux, just regular OS X terminal.

Last time, a week ago, I completely reinstalled Atom and all of my plugins.

**Comment by luaybs** [comment]
FWIW, I fixed the problem by reinstalling Atom. I didn't lose any of my settings, packages, etc.

**Comment by kenhkelly** [comment]
I have been reinstalling, but it's becoming increasingly more common that I have to do this.

**Comment by tamsky** [comment]
https://github.com/Radarr/Radarr/issues/1353#issuecomment-293187409

`chmod +x` fixed this for me.
