### ISSUE TITLE
Possible Translations?

### ISSUE THREAD

**Issue by ziyaddin** [atom/atom#3103]
Hi, how can I translate Atom into Azerbaijani language? Thanks!

**Comment by kr428** [comment]
Not sure whether this belongs here (sorry if so): Following https://atom.io/packages/localization , I found that the way described in this page doesn't work on Linux as the localization package is not available...?

**Comment by blobgo** [comment]
https://atom.io/packages/localization was finally deleted by @pandarison and it used depreciated APis before anyway.
As far as I see the package was not really deleted as I can see it here: https://atom.io/packages/localization
But I could not find it before anyway so it does not seem to be listed any more.

So what's the future of translations in Atom? Does someone wants to create a new package?
Note that the old package was downloaded 10,706 times and stared 41 times (according to the [Atom.io site](https://archive.is/d8KDG)) so it seems there are user who wanted it.

**Comment by rugk** [comment]
https://atom.io/packages/localization was finally deleted by @pandarison and it used depreciated APis before anyway.
As far as I see the package was not really deleted as I can see it here: https://atom.io/packages/localization
But I could not find it before anyway so it does not seem to be listed any more.

So what's the future of translations in Atom? Does someone wants to create a new package?
Note that the old package was downloaded 10,706 times and stared 41 times (according to the [Atom.io site](https://archive.is/d8KDG)) so it seems there are user who wanted it.

**Comment by samueloph** [comment]
In case someone wants to create a new localization package, I can help in the brazilian's portuguese translation.

**Comment by rugk** [comment]
I could help with the German translation too BTW.

**Comment by Volluta** [comment]
I can do the Dutch translation

**Comment by ftoledo** [comment]
I can help in spanish

**Comment by preco21** [comment]
I can help for Korean translation!

**Comment by swirly** [comment]
i18n for atom is really necessary.

I want to use it with floobits for pupils in school. They don't know enough english to feel confortable with atom english interface

If any i18n infrastructure existed, I would glady and rapidly translate it to french.

**Comment by goneau** [comment]
Hi, I am new to coding - learning Java right now at Teluq and found atom.io to help me. Would love to have it in french and would gladly help too!

**Comment by horvan** [comment]
German Translation could also be done

**Comment by stsewd** [comment]
I would be happy to help with the spanish translation :)

**Comment by ideafr** [comment]
Is it possible to translate Atom app in French?

**Comment by HLFH** [comment]
cc @kevinsawicki @50Wliu Hi, do you plan to support i18n for Atom? Thanks.

**Comment by AmrIKhudair** [comment]
I can do the translation to Arabic but how?

**Comment by bhaskardabhi-oviyum** [comment]
@AmrIKhudair you can use following package for translation to arabic. https://atom.io/packages/atom-translator.

I am using that for one of my project.

**Comment by shreyasminocha** [comment]
I could help with Hindi.

**Comment by trifirew** [comment]
I would be glad to help with Simplified Chinese translation :)

**Comment by liuderchi** [comment]
hey guys,
I am developing [atom-i18n](https://atom.io/packages/atom-i18n) for multiple languages :globe_with_meridians:

Languages mentioned in the comments above are supported (as config option)
but *translation is not complete*.

Hopefully the enthusiasts can help. :+1:
[Guide of contribution](https://github.com/liuderchi/atom-i18n/blob/master/CONTRIBUTING.md) is prepared.

currently support: `ar`, `es`, `de`, `fr`, `hi`, `ja`, `ko`, `nl`, `pt-br`, `zh-cn`, `zh-tw`
BTW I will be working on Traditional Chinese :computer:


@samueloph, @rugk, @horvan, @Volluta, @ftoledo, @stsewd, @preco21, @swirly, @AmrIKhudair, @shreyasminocha, @trifirew I need you guys help

**Comment by ziyaddin** [comment]
Well done, @liuderchi.

**Comment by trifirew** [comment]
@liuderchi 合作愉快！

**Comment by preco21** [comment]
@liuderchi Awesome work!

**Comment by alexcarrascob** [comment]
How can I translate Atom in Spanish on Windows 10? Does anyone knows?
Thanks. Greetings from Chile!

**Comment by stsewd** [comment]
@alexcarrascob Podrías ayudar en el proyecto de @liuderchi https://github.com/liuderchi/atom-i18n, yo estuve colaborando con la traducción, pero últimamente no he podido continuar por falta de tiempo (hay unas pequeñas partes que actualizar en la traducción).

**Comment by liuderchi** [comment]
@alexcarrascob package [atom-i18n](https://atom.io/packages/atom-i18n) is supporting Spanish right now.  
You may try it and I would like to hear your feedback. : ]

**Comment by Umoxfo** [comment]
+1

**Comment by payamnaghdy** [comment]
Persian and Kurdish translation if U want :)
