### ISSUE TITLE
Integrate Atom API lookup

### ISSUE THREAD

**Issue by batjko** [atom/atom#3123]
This is to track the [idea](https://github.com/atom/atom/issues/3122) to allow package developers to conveniently access Atom API documentation for classes, methods etc, directly from the source code.

This might be done via a second pane for each call, showing the docs HTML page for the selected method/class etc.
Or maybe via an inline tool-tip kind of implementation, similar to popular IDEs.

**Comment by kevinsawicki** [comment]
I think this can be closed now.

An `atom-api.json` file is now published for each release that packages can download/bundle with metadata information for all the public globals, classes, and methods: https://github.com/atom/atom/releases

There is also https://github.com/atom/autocomplete-atom-api which uses this metadata file and provides suggestions via a service.
