### ISSUE TITLE
Cursor not visible while typing

### ISSUE THREAD

**Issue by jBot-42** [atom/atom#3130]
Sometimes the cursor will disappear while typing or selecting text, and it will show again if I click a few times.

**Comment by GhassenRjab** [comment]
A temporary solution will be pressing Ctrl + space to show suggestions. It will show the cursor again, this what I do. I hope we have a better solution.

**Comment by nathansobo** [comment]
Is anyone still experiencing this issue?

**Comment by GhassenRjab** [comment]
Yes. I am using the new 1.0.2 version on Ubuntu 14.04.2 64 bits

**Comment by jBot-42** [comment]
I no longer have the issue with the latest version.

**Comment by 50Wliu** [comment]
Closing this since there haven't been any new reports and @jBot-42 reported it as fixed.

**Comment by 7Moses** [comment]
I am having the same or similar problems with cursor visibility, editor is still useable. I am using Atom 1.19.0-beta0 on Mac OS X Yosemite (10.10.5). I can reproduce the issue using atom --safe. Trying to figure out if I have arrived here by something other than a bug with the editor, is there a New-ish function to show/hide cursor,

**Comment by 50Wliu** [comment]
@7Moses would you mind creating a new issue and completely filling out the issue template?  We'll be able to assist you better that way.

**Comment by 7Moses** [comment]
@50Wliu Thanks for letting me know, will hopefully do this;  1.19.0-beta1 did not fix the invisible cursor problem, editor otherwise just fine.
