### ISSUE TITLE
Move Line Down/Up Bugs

### ISSUE THREAD

**Issue by ehuss** [atom/atom#3135]
move-line-down (and up) seem to be pretty buggy (and slow).  I will try to summarize the different issues I've come across (some are enhancements depending on your perspective):
- move-line-down with cursor in column 0.  Then press undo.  The cursor will start going down below the buffer and exceptions will start being thrown from tokenized-buffer.
- Select entire penultimate line, won't allow you to move it down (whether or not there is a trailing newline at EOF).
- Moving folds will cause it to unfold (and generally cause lots of problems).  The fold markers can be corrupted if you try to undo.
- Moving lines past a fold can cause it to unfold and have issues.
- Slow with large number of lines (issue #3128).
- Only supports 1 cursor (issue #2470).

I attempted to rewrite the moveLineDown function, and solved most of these issues except for the undo problems (which became much worse due to my approach).  Generally, undo gets very confused if you have `selection.setBufferRange` or `editor.createFold` in conjunction with insert/delete.  The only reason I can see that rebuilding the selection or the folds is necessary is because there is no way to insert text just before the cursor without it becoming part of the selection or fold.

If someone can point me towards a way to insert just before a selection or fold without the text becoming part of that selection or fold, then I can simplify the code and not run into any undo problems.  Alternatively, perhaps it is a bug that undo can cause problems, but that may be more difficult for me to know how to fix properly.

I can provide more details or test code if desired.

I tossed my initial prototype up here: https://gist.github.com/anonymous/aaaa9ec5bb642dab8d26

atom 0.121

**Comment by adzenith** [comment]
Any progress on this? I'm also seeing a bug when trying to move the final line in a file up. If that line doesn't end with a newline (i.e. the file doesn't have a trailing newline) then the last two lines of the file get merged together.

**Comment by cgoettel** [comment]
@adzenith I came here looking to see if a bug report had been filed for that bug (still exists in 1.17.2). Is there a separate bug report for that? If not, should we submit one?

**Comment by adzenith** [comment]
This is the only bug I know about. I'm not sure if a new one needs to be submitted. Hopefully this one gets some attention.

**Comment by cgoettel** [comment]
This seems to be the general bug list for all move line bugs, so I guess we should just add more information here so it's documented.

I'm using Atom 1.17.2 (current as of time of writing) on Windows 7. Will have to test on Fedora later. Bug was reproducible in safe mode.

Description of bug:

- When the last line of the file is not followed by a newline, moving the last line up causes the last line to be prepended to the penultimate line.
- This behavior seems to be independent of file length.
- Is independent of line highlighting and cursor position.

To reproduce:

- Create a new file.
- Add text to lines 1 and 2.
- Use the command (or shortcut) to move the line up.
