### ISSUE TITLE
Atom changes file after commit automatically

### ISSUE THREAD

**Issue by DennisAhaus** [atom/atom#3137]
After changing a file and do a git commit the file is rechanged to the old version automatically while atom is runnning.
May be another issue (or problem of this issue): If i start atom and close the application there are still node.exe processes in task manager in windows although there are no other applicatons running especially using node.exe. 
The path of the node.exe running multiple times is
C:\[...]\atom-windows(2)\Atom\resources\app\apm\node_modules\atom-package-manager\bin

OS Windows 7 Home Premium SR1, x64
Atom: v0.118.0

![2014-07-31 13_50_27-mingw32__c_dennis_dev_projects_mannheimer_avw](https://cloud.githubusercontent.com/assets/1810042/3763978/d9375438-18aa-11e4-9593-adf71adb75e9.jpg)
![2014-07-31 13_55_03-windows task-manager](https://cloud.githubusercontent.com/assets/1810042/3763979/d93a09a8-18aa-11e4-9f2e-56a3f0e94d78.jpg)

**Comment by 50Wliu** [comment]
Hi @DennisAhaus I'm going to assume that this has been resolved in later Atom versions.  However if you're still experiencing this please comment here to let us know!
