### ISSUE TITLE
Hide the first indent guide?

### ISSUE THREAD

**Issue by philipgiuliani** [atom/atom#3149]
I just noticed that there is a indent guide always shown at position 0. First i thought that it is a border of the line-numbers. If i write something at position 0 it gets removed and then it looks like a bug.

What do you think about removing/hiding the indent guide for the Level 0 since it makes no sense there?

![bildschirmfoto 2014-08-01 um 13 06 21](https://cloud.githubusercontent.com/assets/5446019/3778053/1d9e907a-196c-11e4-99a5-65f76290bd26.png)

/cc @benogle @nathansobo i think you wrote the indent guide :)

**Comment by benogle** [comment]
Closing this as I feel the themes should handle this.
