### ISSUE TITLE
Right click opening file opens it multiple times.

### ISSUE THREAD

**Issue by russellds** [atom/atom#3152]
When you right click a file in windows explorer and select "Open with Atom" if the file was previously opened it will open it a second time.

![image](https://cloud.githubusercontent.com/assets/457324/3779110/1b2dc286-197e-11e4-9f21-936dbe0f7142.png)

![image](https://cloud.githubusercontent.com/assets/457324/3779133/5d15f45c-197e-11e4-93db-4cb27dc1e60a.png)

**Comment by kevinsawicki** [comment]
I believe this has been resolved and is no longer an issue on Atom 1.0.3+.

Please comment if you still see it happening.
