### ISSUE TITLE
Make indent guides indicate changing indentation earlier

### ISSUE THREAD

**Issue by dmnd** [atom/atom#3160]
The current indent-guides _lazily_ indicate when the indentation level changes. By "lazy", I mean that the indentation guides keep showing up until a line appears with different content. Example of lazy indentation guides:

![image](https://cloud.githubusercontent.com/assets/4427/3789451/b265f116-1aa3-11e4-91eb-123e73337590.png)

Contrast this to _eager_ indentation guides, which disappear as soon as they can:
![image](https://cloud.githubusercontent.com/assets/4427/3789447/a5430e06-1aa3-11e4-8665-55b190872467.png)

Lazy indentation guides work well in curly-brace languages because there is content on the line to indicate when a block finishes. However, in CoffeeScript and Python, they don't work well because there is no closing brace, and we end up with confusing guides that don't seem to match up with blocks.

This issue is asking that Atom indentation guides are changed from lazy to eager. Another way of describing it is to change the indentation guides so that they end where the closing brace would be in a curly-brace language.

**Comment by warpkanal** [comment]
+1 for eager indent guides

**Comment by Kosyne** [comment]
+1 as well.

The package 'indent-guide-improved' does this, but it straight up mangles the editor for me sometimes :(
(That, and I'm not a fan of it highlighting the indent guide of the level you're on).

**Comment by pvorona** [comment]
This is very nice suggestion, +1

**Comment by Zireael07** [comment]
'Indent-guide-improved' seems a must have.

**Comment by Emilios1995** [comment]
A very useful package indeed. 
If you don't like the highlighting of the current level, paste this in your stylesheet:
```
.indent-guide-improved {
  &.indent-guide-stack {
    background-color: @syntax-indent-guide-color;
    &.indent-guide-active {
      background-color: @syntax-indent-guide-color;
    }
  }
}
```
