### ISSUE TITLE
Error when building latest version on OSX

### ISSUE THREAD

**Issue by abe33** [atom/atom#3184]
I could build it without issue on my MBA that run OSX 10.10 but it fails on an iMac with OSX 10.9.4 + XCode up to date.
Here's the log of the `script/build` task: 

```
Node: v0.11.13
npm: v1.4.9
Installing build modules...
npm WARN engine coffee-script-redux@2.0.0-beta8: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"v0.11.13","npm":"1.4.9"})
npm WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"v0.11.13","npm":"1.4.9"})
npm WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"v0.11.13","npm":"1.4.9"})
Installing apm...
npm WARN package.json github-url-from-git@1.1.1 No repository field.
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/cedric/github/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/cedric/github/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

/Users/cedric/github/atom/apm/node_modules/atom-package-manager/bin/apm: line 40: 69330 Trace/BPT trap: 5       "$binDir/$nodeBin" --harmony_collections "$binDir/../lib/cli.js" "$@"
```

I also tried to build it on node 0.10 but when running `npm install` I get: 

```
../src/scrollbar-style-observer-mac.mm:42:3: error: no matching function for call to
      'uv_async_init'
  uv_async_init(loop, &async, asyncSendHandler);
  ^~~~~~~~~~~~~
/Users/cedric/.node-gyp/0.10.21/deps/uv/include/uv.h:1186:15: note: candidate function not
      viable: no known conversion from 'void (uv_async_t *)' to 'uv_async_cb' (aka
      'void (*)(uv_async_t *, int)') for 3rd argument
UV_EXTERN int uv_async_init(uv_loop_t*, uv_async_t* async,
              ^
1 error generated.
make: *** [Release/obj.target/scrollbar-style-observer/src/scrollbar-style-observer-mac.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/cedric/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/Users/cedric/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cedric/github/atom/node_modules/scrollbar-style
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
```
And then forcing a build after that gave the same error as with node v0.11.13.

Is there's something I missed regarding my system configuration.

**Comment by murphyrandle** [comment]
@geoff-codes would `export LDFLAGS=$LDFLAGS:-Wl,-export_dynamic` do it? Sorry, I haven't dealt with C-lang compilers in a while.

**Comment by geoff-codes** [comment]
Erm, not necessarily. Does atom's node build with gyp (like standalone node)?

Give me a sec, I'll take a look.

**Comment by murphyrandle** [comment]
Thanks! I'm not sure it matters now, the errors have changed when trying to build with io.js.

**Comment by YuriSolovyov** [comment]
@kevinsawicki node 0.12 is out for a couple of day now, any plans to upgrade? What about io.js ?

**Comment by geoff-codes** [comment]
Actually, I **was** just able to figure out the issue that @totallymike reported. Its a bug in [apm](https://github.com/atom/apm) or, more technically, the version of node that amp is using. I still haven't quite got the whole thing to build as yet, (there are a couple more issues with a few modules), but @YuriSolovyov, yup, this issue is resolved in 0.12. I'll have a patch presently.

**Comment by murphyrandle** [comment]
Thanks, @geoff-codes! :cake:

**Comment by geoff-codes** [comment]
Yeah, there's also a bug in the "base-minimal" package. The last one if trying to figure out is a missing weird Objective-C++ symbol that's using NSlog with std::string...

**Comment by geoff-codes** [comment]
@murphyrandle @YuriSolovyov 
That's about as far as I got, as the nslog bit seems to be a bit of a blocker. Passing the baton for now.
@kevinsawicki @zcbenz and friends, patches and issues for your consideration. :smirk_cat:

**Comment by kevinsawicki** [comment]
I know this issue was initially about node 0.11, but since node 0.12 is out and supported vi #5628 I think this can be closed.

**Comment by kans** [comment]
@kevinsawicki 
Latest master is still subject to the same problems for me. Any thoughts?

```
(master) $ ./script/build
Node: v1.2.0
npm: v2.5.1
Installing build modules...
Installing apm...
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/kans/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /Users/kans/atom/apm/node_modules/atom-package-manager/node_modules/keytar/build/Release/keytar.node
  Expected in: dynamic lookup

/Users/kans/atom/apm/node_modules/atom-package-manager/bin/apm: line 40:  1416 Trace/BPT trap: 5       "$binDir/$nodeBin" --harmony_collections "$binDir/../lib/cli.js" "$@"
```

**Comment by kevinsawicki** [comment]
@kans can you try removing `apm/node_modules` and build again?

**Comment by kans** [comment]
@kevinsawicki 
I think that did the trick, thanks!

**Comment by kevinsawicki** [comment]
> I think that did the trick, thanks!

Great, yeah, sorry, should have mentioned that that may be required depending on the state your Atom working directory is in.

**Comment by bmustata** [comment]
Try reinstalling "Command Line Tools" on MacOSX. http://www.hongkiat.com/blog/mountain-lion-git-fix/
