### ISSUE TITLE
Atom doesn't launch on Ubuntu

### ISSUE THREAD

**Issue by yaph** [atom/atom#3190]
Installed atom from a24d1d1 running Ubuntu 14.04, Immediately after trying to start atom from the terminal the atom process turns into a zombie process, partial output from `ps -aux`:

    user   25788  0.0  0.0      0     0 pts/1    Z    09:33   0:00 [atom] <defunct>

**Comment by benogle** [comment]
@tribut is this still an issue with the latest version? What was the solution?

**Comment by tribut** [comment]
Yes, still a problem with v0.177.0 built from git (5cae6f20c448fddea5dd8beeae1b26df77b05919). The deb from atom.io works fine.

**Comment by mnquintana** [comment]
@tribut Is this still an issue with the latest version (0.190.0)?

**Comment by yaph** [comment]
I haven't had problems with Atom on a fresh Ubuntu install, so I close this now. If Atom doesn't launch for you, there is a related issue #6317.

**Comment by dtrenin7** [comment]
just kill atom before launch them:

run terminal session, then:
sudo -i
<enter root password>
pkill -f atom
atom
