### ISSUE TITLE
Title bar displayed with multiple fullscreen windows (OS X)

### ISSUE THREAD

**Issue by chrimifi** [atom/atom#3194]
1. Open an Atom window with a file or project. (For some reason, this bug didn't happen when I tried to reproduce from an empty Atom window.)
2. Enter fullscreen mode (Ctrl-Cmd-F)
3. Open another window of Atom. (e.g. with the command line, File > Open [and then select a folder], or with the Project Quick Open package)

The window that opens will have a vestigial title bar at the top that looks like this:
![screen shot 2014-08-06 at 4 08 32 pm](https://cloud.githubusercontent.com/assets/1977010/3835399/bbbdf11e-1dbe-11e4-8bf4-d9a0d2049336.png)

It's not a big deal, but it does undermine the purpose of fullscreen mode a little bit. ;)

This is on Atom 0.120.0 running on OS X 10.9.3. I was able to reproduce the problem in safe mode.

**Comment by mnquintana** [comment]
I can't reproduce this with OS X 10.10.3 and Atom 0.210.0 - please feel free to reopen / comment if you can reproduce this with the latest version of Atom.
