### ISSUE TITLE
Multi-key Binding with same Prefix does not work

### ISSUE THREAD

**Issue by EdVanDance** [atom/atom#3195]
Hi guys,

I'm trying to add some key bindings for tab navigation in vim command mode. This is my `keymap.cson`:

```
'.editor.vim-mode:not(.insert-mode)':
  ', h': 'pane:show-previous-item'

'.editor.vim-mode:not(.insert-mode)':
  ', l': 'pane:show-next-item'
```

Pressing `,` while Key Binding Resolver is open shows only the later `, l` key binding. `, h` does not work. But `g t` and `g Shift-T` bindings from vim-mode are fine.

What also does not work correctly for me is something like:

```
 '.editor.vim-mode.insert-mode':
   'i i': 'vim-mode:activate-command-mode'
```

The keybinding itself works, but pressing a single `i` does not add it in text.

I'm on Windows 7 32-Bit. Atom 0.120.

Greetings,
Ed

**Comment by mnquintana** [comment]
`keymap.cson` is in a key-value format just like JSON – this means that keys must be unique, otherwise there could be unexpected behavior. You've repeated the same key twice here:

```cson
'.editor.vim-mode:not(.insert-mode)':
  ', h': 'pane:show-previous-item'

'.editor.vim-mode:not(.insert-mode)':
  ', l': 'pane:show-next-item'
```

It should actually be:
```cson
'.editor.vim-mode:not(.insert-mode)':
  ', h': 'pane:show-previous-item'
  ', l': 'pane:show-next-item'
```
