### ISSUE TITLE
Deleting a file locks up Atom (Windows 7)

### ISSUE THREAD

**Issue by jwoertink** [atom/atom#3198]
I'm getting a weird locking issue when deleting a file, or sometimes folder, in windows. This only happens if I've opened the file. Files I haven't touched delete just fine.

**Process:**
- Open Atom
- Click on file in side pane to open
- Click "x" to close file
- Right click file
- Select "Delete"
- Select "Move to Trash"
- Get "Editor is not responding" error

![capture](https://cloud.githubusercontent.com/assets/2391/3830021/1df7410c-1d86-11e4-894d-cfaf838aca9d.PNG)

More details, these are .js and .coffee files from a node app I'm working on. So these files have also been running as a server or process at some point. 

**Versions:**
Atom 0.120.0. Windows 7 SP1.

**Comment by damieng** [comment]
Just tried to repro this and didn't happen - I suspect it has been fixed at some point since this bug was filed but the bug was not closed. Please re-open if newer versions of Atom are still crashing for you.
