### ISSUE TITLE
Hermit Font causes cursor display to misalign

### ISSUE THREAD

**Issue by askmattcairns** [atom/atom#3201]
Atom Version: 0.120.0
OS: OS X 10.9.4

The Hermit font found at https://pcaro.es/p/hermit/ causes the selection display to misalign.

Image 1 using Source Code Pro

![screen shot 2014-08-07 at 5 51 57 pm](https://cloud.githubusercontent.com/assets/661147/3849812/4da24454-1e7d-11e4-9402-c2d2e87d871a.png)

Image 2 using Hermit.

![screen shot 2014-08-07 at 5 52 14 pm](https://cloud.githubusercontent.com/assets/661147/3849813/50f67c60-1e7d-11e4-9e5b-6310295bb1d3.png)

In both instances the font size is 16 and line height is 1.3.

**Comment by odran037** [comment]
I'm having this issue on OSX 10.10.2. Just started using Atom and am having this problem regardless of the font. Just out of curiosity, I tried non monospace fonts such as Arial and the cursor ends up past the text. While any monospace fonts the cursor ends up behind.

**Comment by benogle** [comment]
This is fixed on master!
