### ISSUE TITLE
Atom segfaults on Ubuntu

### ISSUE THREAD

**Issue by juh2** [atom/atom#3202]
Hello,

I am not sure whether this is a core atom problem. But anyway. I am using atom on linux Ubuntu 14.04 with the  ppa:webupd8team/atom. It segfaults 

    Aug  8 11:22:15 sokrates kernel: [14540.293747] atom[17431]: segfault at 0 ip 00007f2d674fb93a sp 00007fff1b4bdf08 error 4 in libc-2.19.so[7f2d67472000+1bc000]
    Aug  8 11:22:19 sokrates kernel: [14544.923021] atom[17415]: segfault at 0 ip 00007fcf1a2db93a sp 00007fffef4d6758 error 4 in libc-2.19.so[7fcf1a252000+1bc000]

I added the  ppa:chris-lea/node.js to my apt-get-repository list.

The version is 0.116.0-262ba6b

**Comment by benogle** [comment]
@juh2 have you seen this since August?

**Comment by kevin-brown** [comment]
I haven't personally seen this recently @benogle.

**Comment by juh2** [comment]
I haven't seen this again, but I don't use Atom every day.

**Comment by benogle** [comment]
Closing as a lot has changed since august.
