### ISSUE TITLE
Enable native Services menu on OS X

### ISSUE THREAD

**Issue by danielbayley** [atom/atom#3204]
Looks like Atom disables the native Services menu on OS X. Any chance of enabling it? I have loads of useful services that I don't want to have to reimplement/replace as packages.

**Comment by robdecker** [comment]
I know this issue has been marked fixed, and I can indeed see a Services menu, but it is empty. It should be filled with numerous text services.

**Comment by tulushev** [comment]
Confirmed on 0.182.0 as well, still no services.

**Comment by thomasjo** [comment]
This is indeed not fixed; we need to implement support for this. Maybe I'll find some time over the weekend, but if anybody else wants to give it a go, here's a starting point:
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/SysServices/Articles/using.html#//apple_ref/doc/uid/20000854-CEGDDHJJ

**Comment by danielbayley** [comment]
The Services menu shows up under `Atom > Services` and those services work, but nothing in the context menu when I right-click within the document (meaning those text services don't show up).

**Comment by trueschool** [comment]
I see the Services menu but I'm only seeing a small subset of the enabled services that should be appearing. Seems weird that I should see some but not others?

**Comment by gholts** [comment]
To add to this, I'm seeing the correct services, and I can click on one and it will activate from the menu. The issue I'm having is that the keyboard shortcut isn't working for them.

Ah, though while writing this I figured it would be a good idea to check the keybindings, and it looks like Linter is taking over the shortcut I had set the service up to use. Not sure what the solution could be for that... should services over-ride?

**Comment by robdecker** [comment]
I'm now on 0.192.0 and still no services.

**Comment by stevencombs** [comment]
Version .204 and while I see the *Services* menu, there are no services available.

**Comment by kfix** [comment]
ditto to @stevencombs

**Comment by Sulcalibur** [comment]
Any idea when (or if) this will be actioned?

**Comment by danielbayley** [comment]
The Services menu does show up (although not the equivalent contextual menu), however they don't seem to have access to Atom. You can't use the system level text manipulation, or any such services you create.

**Comment by erwinia** [comment]
Use of the services within Atom would be great. Where do we vote on new features?

**Comment by mauceri** [comment]
I agree, it would be great to have services

**Comment by paultopia** [comment]
Does this issue being closed imply that this feature is coming out whenever 1.3.0 is out of beta?  Because I'm on 1.2.4, and still no services...

**Comment by 50Wliu** [comment]
> Does this issue being closed imply that this feature is coming out whenever 1.3.0 is out of beta?

Yes.

**Comment by naoboo** [comment]
I use 1.3.1 (on OS X 10.11.1), but the services function doesn't seem to be working.  What I noticed is the following.  If I select some text in the editor, no services appears under Atom > Services.  However, for instance, if I select some selectable text in Atom > Preferences... > Settings (the line starting with "These are Atom's..." is selectable), then services do appear under Atom > Services.

**Comment by erwinia** [comment]
I agree with naoboo. Same here.

**Comment by kfix** [comment]
Based on @naoboo's observation, I would guess that Atom's editor view simply doesn't use NSText, thereby not feeding selected text to Services[*], but the config panels do.

[*]: https://en.wikipedia.org/wiki/Cocoa_text_system

**Comment by magp** [comment]
Same issue. I can see my non-text services but not my text services. This would confirm @kfix hypothesis. Non-text services work as expected.

**Comment by mnquintana** [comment]
@kfix @magp That sounds right – the text editor portion of Atom is a custom component, where as the views in settings-view are just standard DOM components that allow for native text Services. Would you mind opening a new issue for enhancing Atom's Services support to include text services?

**Comment by zazazack** [comment]
any update on this?

**Comment by jjiangweilan** [comment]
It's 2017 and the services are still not supported. Surprised

**Comment by kfix** [comment]
@jjiangweilan " its <current year>" does not advance a feature request. see #10213, which is the core problem for Text services, and its not trivial.

**Comment by khx42** [comment]
Atom 1.17.2, Services menu still broken.

**Comment by chreliot** [comment]
Similarly frustrated by this, here's my work-around. _It's not for everyone_, as it involves commercial OS X software. And it requires more keystrokes than a regular service would. But it might inspire other solutions.

This workflow uses [Launchbar](https://www.obdev.at/products/launchbar/index.html). One could use Alfred or another keyboard shortcut tool for this.

1. Select text in Atom
2. Long press ⌘-space to send that text to Launchbar (or your custom shortcut)
3. Type part of the name of a text service and select it. (The text is processed in the buffer.)
4. Hit tab to invoke a new command.
5. Select Paste in Frontmost Application to replace the originally-selected text in Atom with the processed text.
