### ISSUE TITLE
application title Unknown

### ISSUE THREAD

**Issue by dteskera** [atom/atom#3213]
linux, debian testing, built from source
gnome 3.12

application title is set to Unknown when started from terminal.
~/some work folder/ $ atom
![screenshot from 2014-08-10 07 03 00](https://cloud.githubusercontent.com/assets/5214456/3868532/e73da3fe-204b-11e4-932b-caf2b42b19e7.png)

but when started with using the .desktop file, application title is set to Atom.
![screenshot from 2014-08-10 07 03 37](https://cloud.githubusercontent.com/assets/5214456/3868534/f7d1995a-204b-11e4-938f-af8eacdcfede.png)

**Comment by 50Wliu** [comment]
Assuming fixed.  If this is still reproducible on the latest Atom version please comment here!
