### ISSUE TITLE
cannot open atom from command line

### ISSUE THREAD

**Issue by jasonshark** [atom/atom#3224]
This command was working for me, then I set some permissions or something. How do I fix this?

```
$ atom .
usage: dirname path
Cannot locate Atom.app, it is usually located in /Applications. 
Set the ATOM_PATH environment variable to the directory containing Atom.app.
```

Running OSX

**Comment by mnquintana** [comment]
Gonna close this out - please feel free to reopen / comment if you can reproduce this with the latest version of Atom (0.210.0)

**Comment by Karla-Isabel-Sandoval** [comment]
The error message, `Cannot locate Atom.app, it is usually located in /Applications. Set the ATOM_PATH environment variable to the directory containing Atom.app.` is being produced intermittently with Atom version 1.6.2 while running on OSX. At times the issue disappears completely and then it returns. Not entirely sure how to fix this.
