### ISSUE TITLE
Saving read-only file causes Dev Tools to open

### ISSUE THREAD

**Issue by Stoyvo** [atom/atom#3231]
Regardless if I press CTRL+S (which is mapped to core:save) or try to close a modified file and click save, the developer tools open... I can't save the file.....

Edit:
Turns out an error is thrown in the Console.
Uncaught Error: EPERM, operation not permitted '\\UBUNTU\www\MYAPP\MYFILE.php'

**Comment by dotnetdan** [comment]
What would be the appropriate fix for this?  A message in the status bar at the bottom?

**Comment by dotnetdan** [comment]
Holy crap, that was a quick response.  Thanks a bunch!
