### ISSUE TITLE
Keybinding for switching tabs should work from anywhere.

### ISSUE THREAD

**Issue by colllin** [atom/atom#3235]
Is this change possible?

An example of something I can't do right now:
- `cmd+f` to search in the current file
- type something & search
- `cmd+shift+[` or `cmd+shift+]` to change tabs and search the same string in a different file.

Pressing `esc` gets me out of the "find" panel but that's not good enough.  Unless the "find" panel is using the same keybinding for something, maybe it could just fall through and let me change tabs?

**Comment by Valve** [comment]
Don't want to pollute the issue, but please-please fix it.
