### ISSUE TITLE
Pasting from Parallels VM results in bad line-endings?

### ISSUE THREAD

**Issue by amazingant** [atom/atom#3238]
When pasting text from a Windows VM with Parallels into a new document, the document is saved with carriage-returns only.

I'm including screenshots of how Notepad++ shows the document for clarity as to what is showing up and what _should_ be showing up. Note that the screenshot used for the expected results is what I copied from the VM, and so has the Windows-style line-endings; I would be perfectly happy with the current Linux/OSX norm of `\n` instead.
#### Steps to Reproduce:
1. Create a new document in Atom
2. Copy text with line-breaks from anything in Windows VM
3. Paste into Atom
4. Save
#### Expected Results:

The resulting file contents should delimit line endings with either the line-feed character (ASCII 0x0A, `\n`, etc.) or a carriage-return character (ASCII 0x0D, `\r`, etc.) followed by a line-feed character.

![screen shot 2014-08-12 at 4 23 58 pm](https://cloud.githubusercontent.com/assets/1761309/3897190/8f5313a2-225f-11e4-8704-f32057d87ed8.png)
#### Actual Results:

The line endings in the resulting file contents are delimited by the carriage-return character.

![screen shot 2014-08-12 at 4 24 11 pm](https://cloud.githubusercontent.com/assets/1761309/3897235/fc009092-225f-11e4-8b19-dfedd499f484.png)

This of course causes git to show erroneous control characters in Terminal.app.

![screen shot 2014-08-12 at 4 24 53 pm](https://cloud.githubusercontent.com/assets/1761309/3897254/1dac6270-2260-11e4-8065-89c0c31b2a1b.png)
#### Extra Notes:
- The dev tools don't show any errors or warnings.
- Running `atom.workspace.getActiveEditor().getText().replace(/\r/g, '\\r').replace(/\n/g, '\\n')` in the console with an un-saved file returns `This\ris\ra\rtest\r`
- Pasting the same text into a new document with XCode results in a document using line-feed only
- I am currently observing this behavior in v0.120, but it is not new behavior

**Comment by mnquintana** [comment]
Is anyone still running into this with the latest versions of Parallels and Atom?

**Comment by amazingant** [comment]
I'm not, but only because I do not use atom on a regular basis? If nobody else has a minute to try it, I can give it a go when I get back to work on Tuesday.

**Comment by lee-dohm** [comment]
Seeing as we haven't had any new reports of this in over three years, I'm going to go ahead and close it. Please let me know if anyone can reproduce it :+1:
