### ISSUE TITLE
Overlapping errors in status bar when it's hidden

### ISSUE THREAD

**Issue by bobber205** [atom/atom#3259]
When you hide the status bar and cause new notifications that would normally be shown in the status bar to appear (such as opening new files) they're all running on top of each other.

Looks like to me when the status bar is open the status bar is either cleared for each tab or has state on a per tab basis?

![name_email_controller_js_-__users_alexwait_chirpify_chirpify-frontend_and_new_issue_ _atom_atom](https://cloud.githubusercontent.com/assets/5841107/3912344/08f773ea-232a-11e4-8187-752cc5bced9c.png)

Let me know if there is any other info needed to fix this. Will try to fix if I get some spare time as well. :)

**Comment by benogle** [comment]
Closing in favor of https://github.com/atom/status-bar/issues/48
