### ISSUE TITLE
Undo selection `Ctrl + U`

### ISSUE THREAD

**Issue by jhasse** [atom/atom#3262]
Sublime Text offers a key shortcut for undoing the last selection (`Ctrl + U`). Would be nice to have something like this in Atom, too.

**Comment by jhasse** [comment]
This seems to be fixed in newer Atom versions :) Thanks!

**Comment by bradonomics** [comment]
This seems to be broken in the newest version (1.23.3). Can anyone else confirm?

**Comment by rsese** [comment]
I can't reproduce in 1.23.3 and Windows 10 - if you can reproduce in safe mode @bradonomics, please open a new issue and fill out the issue template so we can take a look.

**Comment by bradonomics** [comment]
Didn't think to check safe mode, but you're right, it's working fine that way. Must be a package. I'll track it down. Cheers.
