### ISSUE TITLE
Switch between header and implementation file `Alt + O`

### ISSUE THREAD

**Issue by jhasse** [atom/atom#3263]
One very handy feature when programming with C, C++ or Objective-C is switching between header (.h, .hpp, .hh) and the matching implementation file (.c, .cpp, .cc, .m, .mm). Sublime Text (and some other editors) allow this with the key combination `Alt + O` (on Windows and Linux).

**Comment by jhasse** [comment]
There's now a plugin for this functionality: https://github.com/dschwen/switch-header-source

**Comment by kevinsawicki** [comment]
Closing this out, this is best handled by an Atom package such as the one mentioned in the comment.
