### ISSUE TITLE
Install atom without internet connection

### ISSUE THREAD

**Issue by mruz** [atom/atom#3269]
Hi,

I'm trying to create openSUSE package and I must to build atom without network due to https://en.opensuse.org/openSUSE:Packaging_nodejs#npm_ERR.21_network_getaddrinfo_enotfound. Can anyone give me a full list of required sources, because NPM can install from online URL or from local file.

**Comment by kevinsawicki** [comment]
> Can anyone give me a full list of required sources, because NPM can install from online URL or from local file.

The libraries are listed in the root `package.json` file and also `build/package.json` and `apm/package.json`.

Also, electron is downloaded via the https://github.com/atom/grunt-download-electron/ grunt plugin.

Closing this out, please let me know if you need more details.
