### ISSUE TITLE
Delete does not work for files on NFS-shares

### ISSUE THREAD

**Issue by somebody32** [atom/atom#3306]
I'm trying to remove files/dirs using sidebar, Atom asks if I want to move them to Trash and then nothing happens (files stay in the sidebar and on the disk).

This is valid only for files on a network partition, everything is ok with local ones

Version: 0.123

**Comment by somebody32** [comment]
Hi! Maybe any extra info that I can provide here? The issue is still persist with the latest Atom (1.0.2)

**Comment by somebody32** [comment]
Deleting is still failing with the latest atom (1.19.0) with message `The following file couldn't be moved to the trash. Is Trash enabled on the volume where the files are stored?`

**Comment by 1Reinier** [comment]
Still failing...

**Comment by blockba5her** [comment]
Same issue here.

**Comment by Benibur** [comment]
same problem for me. note being able to delete a file from your editor is quite a pain, but atom is considering it is a feature... : https://github.com/atom/tree-view/issues/856
Workaround with permanent-delete plugin : https://github.com/zorn-v/atom-permanent-delete
