### ISSUE TITLE
Android port of Atom

### ISSUE THREAD

**Issue by jehrhardt** [atom/atom#3322]
Since there are keyboards available for Android tablets, it makes a lot of sence to use a modern text editor on these devices. Since Atom is based on Chromium and web technologies, it should be possible to port it to Android.

I guess Atom could be a great first step to coding on Android devices.

**Comment by njrabit** [comment]
There are tablets with fairly beefy 8-core CPUs and full OpenGL and OpenCV (hardware-accelerated 2D rendering API) support that outperform some current laptops and MacBook Pros from a few years ago.  Also, tablets keep getting far better displays than laptops.  Seen the Samsung 10.4 S's?

There are some good Android programming editors but even if it's sluggish compared to a native app, I'd love to have Atom running on my tablet alongside my laptop for coding.

**Comment by paulcbetts** [comment]
If someone wants to attempt this it should be theoretically possible, but I suspect it would be a metric _ton_ of work. However, it would actually also be super interesting, because of [ARC Welder](https://developer.chrome.com/apps/getstarted_arc) - this could be a vector to get Atom onto ChromeOS, but not be limited by ChromeOS's super strict APIs

**Comment by batjko** [comment]
Also the "Can we do web-based?" question keeps coming up:
http://discuss.atom.io/t/what-parts-of-atom-are-desktop-dependent/16054

Naturally, if anybody can spend _that_ metric ton of sweat, that would be an even more universal solution.

**Comment by v3ss0n** [comment]
Porting electron to Android should be the first step.

**Comment by alfonsojon** [comment]
As a BlackBerry user, I can see this being very useful as my device has both Android app compatibility and a full keyboard. This device has become a little server management machine, and this would only make the experience greater.

**Comment by cstachris** [comment]
for those curious and beyond, GNURoot (i tested deb,fedora,gentoo) & debian noroot are on android firing off linux.  Aiming at a portable javadev/sa setup, it wasn't *ideal*, but the whole desktop is available ... and therefore running. i haven't run a desktop on it but plenty of ppl on yt have as i was more interested in running java from command line - LAMP stack is readily available.

for MEAN deving a keyboard with trackpad is more workable, i might give it a go - i'm new to atom but the perceived clunkiness may be really good on a touch screen i.e. copy paste rename a file compared to command line is an order of magnitude slower ;)

**Comment by timofonic** [comment]
Yes, please. Maybe Webassembly can make it happen?

**Comment by bgrayburn** [comment]
+1, I've been moving more and more of my dev environments to docker containers running on aws. Then when on my laptop, i mount the drive locally and use in atom. More and more I've been sshing into the machines with juicessh on my tablet (nexus5) and using vim, but i miss multiple cursors and all my favorite packages. Just a possible use case for all the skeptics out there.

**Comment by mbirth** [comment]
@bgrayburn Check out https://github.com/terryma/vim-multiple-cursors

**Comment by bgrayburn** [comment]
Ooh that is cool :) thanks @mbirth, would still enjoy having atom
everywhere, but this vim package makes remote editing better for sure

**Comment by trusktr** [comment]
> What's so bad about DroidEdit or similar editors?

I want the web to win, so a web based solution would help that cause. DroidEdit itself is a great example of something we can aim for with a web-based solution. To this day, there's still no web-based editor that I can use on an Android phone or iPhone. The Ace and CodeMirror experiences on mobile are horrible.

**Comment by RdeWilde** [comment]
Would be very cool to have with Android OS going mainstream soon.

Also new products like Pixel (from Google, https://pixel.google.com) would be very interesting to see run Atom.

**Comment by lee-dohm** [comment]
We completely agree that it would be cool to have Atom available on Android and other mobile platforms :grinning: Right now, we're focusing on making Atom an amazing desktop application. Support for mobile platforms isn't on our roadmap at the current time or in the foreseeable future. When that changes, we'll reopen this.

Thanks everyone for your support of Atom!

**Comment by MaxPleaner** [comment]
It's not so much Atom in particular that brought me to this issue, but rather my wondering if Electron supported Android platforms (since Atom is built on Electron). I suppose I was hoping that "cross-platform" in this context included mobile.

**Comment by v3ss0n** [comment]
checkout Intel's XDK and Crosswalk. it is basically chromium ported to android and it works amazingly fast.

**Comment by v3ss0n** [comment]
https://crosswalk-project.org/documentation/android.html

**Comment by FireAntJoe** [comment]
So will this ever happen? I would love to program on my tablet in atom.

**Comment by lee-dohm** [comment]
@FireAntJoe See [my comment above](https://github.com/atom/atom/issues/3322#issuecomment-182998035).

**Comment by toddmbloom** [comment]
I'd love to have it on iOS, too! I use Coda now but it's not as fully featured as Atom.

**Comment by lee-dohm** [comment]
Since people seem to be missing my comment above, I'm going to repost it here and then lock this Issue for comments so that it remains at the bottom for people to see:

> We completely agree that it would be cool to have Atom available on Android and other mobile platforms :grinning: Right now, we're focusing on making Atom an amazing desktop application. Support for mobile platforms isn't on our roadmap at the current time or in the foreseeable future. When that changes, we'll reopen this.

> Thanks everyone for your support of Atom!
