### ISSUE TITLE
Cursor position miscalculated when input and editor fonts differ

### ISSUE THREAD

**Issue by dgraham** [atom/atom#3345]
The cursor position in input fields is miscalculated when the editor font is not the same as the `input` element font.  This screenshot is with an editor font of Source Code Pro and input font of Lucida Grande, provided by the [Unity UI](https://github.com/orderedlist/unity-ui) theme.

![cmd-t-cursor](https://cloud.githubusercontent.com/assets/122102/3985882/2b9ff90a-2896-11e4-926f-ddc15bbb60c0.png)

The stock Atom Light theme works fine because the fonts are the same in both the editor and input fields.

**Comment by benogle** [comment]
This was fixed by #8811
