### ISSUE TITLE
Add TUI

### ISSUE THREAD

**Issue by prodigeni** [atom/atom#3346]
Atom is great, and there is no doubt. It already has a good gui, if you could add a ncurses/termbox tui to it, it would be a lot better and more useful. I think this could be done by using lime's backend/frontend model, it would also help performance.

**Comment by doug** [comment]
:+1: I know this isn't on the core roadmap, but just wanted to echo the desire for this feature.

**Comment by maxbrunsfeld** [comment]
The [slap](https://github.com/slap-editor/slap) editor is terminal-based and [uses](https://github.com/slap-editor/editor-widget/blob/b68e6ed28b0a26e774ad19400ed68d4401fdf38a/package.json#L19) Atom's underlying `text-buffer` module.

**Comment by doug** [comment]
As an easier alternative, if you could start up atom as a server. Have the UI forward all backend calls that would go to node via electron to a headless instance and have the full atom UI rendered in a browser and proxied to your remote instance. Then you could use atom from a chromebook or ipad with an ssh client and a browser.
