### ISSUE TITLE
Unexpected Ctrl + Del behaviour

### ISSUE THREAD

**Issue by aerouk** [atom/atom#3362]
In other programs, pressing **Ctrl + Del** on the end of a line would delete newline characters and bring the next line after the cursor.

Example in Sublime Text:

![](https://s.kpvp.in/gifs/WfVaC.gif)

([https://s.kpvp.in/gifs/WfVaC.gif](https://s.kpvp.in/gifs/WfVaC.gif))

**Comment by jhasse** [comment]
I think #4026 is a duplicate of this.

**Comment by aerouk** [comment]
@jhasse that issue does show the problem I'm having, yeah

**Comment by dwelle** [comment]
As mentioned in #4026, you can rebind via:

```
'ctrl-backspace': 'editor:delete-to-previous-word-boundary'
'ctrl-delete': 'editor:delete-to-next-word-boundary'
```

**Comment by glen-84** [comment]
```
Atom                    delete-to-end-of-word
Brackets                delete-to-next-word-boundary
Eclipse                 delete-to-next-word-boundary
Programmer's Notepad    delete-to-next-word-boundary
Sublime Text            delete-to-next-word-boundary
Visual Studio 2015      delete-to-next-word-boundary
```

Spot the odd one out.

Please change the default.

**Comment by YemSalat** [comment]
I also think that the default needs to be changed. In #4026 it is justified by the fact that this behavior "is similar to most text boxes on your system"
But that is exactly why I don't write code in text boxes and if I ever have to - I miss my editor at those times and one of the things I miss is exactly removing only whitespace on Ctrl+Backspace/Del

I do not think that Atom should be copying other editors, but this is not "copying" - this is complying with common code editor logic.

**Comment by lucasvw** [comment]
:+1: change the default

**Comment by joshrhoderick** [comment]
So Atom *really is* going to become the new Emacs: incredibly powerful but unusable out-of-the-box due to unintuitive behavior. I shouldn't need to modify my configuration just to retain the standard behavior of every other editor I have ever used. My text editor shouldn't behave like a text field, even if it really is one under the covers.

**Comment by jims** [comment]
:+1: This is probably my nr 1 grief with text editing in atom!

**Comment by DKhalil** [comment]
This is so incredibly annoying, +1

**Comment by splintor** [comment]
:thumbsup:

**Comment by westtrade** [comment]
:+1:

**Comment by efkan** [comment]
+1

**Comment by zenbaku** [comment]
+1, number one reason to keep going back to sublime.

**Comment by denisazevedo** [comment]
+1

**Comment by glen-84** [comment]
@denisazevedo You can use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) now, instead of +1 comments.

**Comment by luisaceituno** [comment]
PLEASE change this default so I don't need to configure the keybindings on every new machine.

**Comment by ilkome** [comment]
+1

**Comment by ElliottJRo** [comment]
I dont suppose we have any progress to this? It has been 2 years T_T

**Comment by YemSalat** [comment]
Just submitted a PR to fix this: https://github.com/atom/atom/pull/12098

**Comment by DavidEichmann** [comment]
+1 trying out Atom after using Sublime. The current delete-to-end-of-word behavior was unexpected/undesirable for me.

**Comment by QueueHammer** [comment]
I have been using Atom for about 6 months now, and this is still my most unfavorite feature. I have see a couple of these threads that eventually point to a PR that end the same way it did. Closed; without a merge. @glen-84 summed it up best with his comment. If this doesn't change soon I'll have to take break back to Brackets, while I know others who will go to VS Code (shudder).

**Comment by abumalick** [comment]
An easy fix for getting the sublime text behavior for CTRL-BACKSPACE and CTRL-DELETE : 
Click File / Keymap
Add this at the end of your keymap.cson : 
```json
'atom-workspace atom-text-editor':
  'ctrl-backspace': 'editor:delete-to-previous-word-boundary'
  'ctrl-delete': 'editor:delete-to-next-word-boundary'
```

**Comment by abumalick** [comment]
Well, there is still a thing that don't work like sublime text.
CTRL-DELETE before a CR (Carriage return) don't delete the CR.

**Comment by dwelle** [comment]
> @abumalick  CTRL-DELETE before a CR (Carriage return) don't delete the CR.

I think we had to migrate our whole codebase to `LF` line endings because of this ;) (which we should have done anyway)

**Comment by lynnellemmanuel** [comment]
Hello. I also face this issue. Ctrl+Delete deletes the whole line instead of just the white space. The same thing with Ctrl+Backspace.

**Comment by vanboom** [comment]
Thank you, please make this the default.

**Comment by cxai** [comment]
Pretty please?
