### ISSUE TITLE
Unable to use some git commands from atom or sub-packages.

### ISSUE THREAD

**Issue by Icehunter** [atom/atom#3367]
git-pull, merge so far don't work from within packages in atom.

To fix this I did the following (OSX):
- cd /Applications/Atom.app/Contents/MacOS/
- mv Atom Atom-bin
- vi Atom
- paste:

```
#!/bin/sh
${0}-bin
```
- save
- chmod +x Atom

When I start Atom it can now use git commands like no ones business but updating fails.

Here is the error I get when using git-pull:

```
/Library/Developer/CommandLineTools/usr/libexec/git-core/git-pull: line 11: git-sh-setup: No such file or directory
```

I am using Yosemite at this point DP6. I had this issue on DP5 and PB1 as well.

Another way to fix it is to manually modify a few git-core files and hardcode a few file locations.

Please let me know if there's any more info I can provide. Thanks!

**Comment by damieng** [comment]
No reports on this for some time please let us know if this is still an issue.
