### ISSUE TITLE
Window load time - performance problems in general.

### ISSUE THREAD

**Issue by keeev** [atom/atom#3405]
Hey, 

since the update to 0.124.0 the performance got even worse (it wasn't the best before) the console says that the "Window load time" takes up to **7390ms**. Right now I'm trying to merge two files with the up-to-date one on the right pane. 

And opening a folder does take even longer. It happens on two different computers (private and work) both with the latest version.

Is there any other way to see loading times and help you with that? 

On Mac OS X (Mavericks)

**Comment by benogle** [comment]
Closing this in favor of #3673, our most commented issue!
