### ISSUE TITLE
Mutlicomments not behaving as suspected

### ISSUE THREAD

**Issue by stanzheng** [atom/atom#3424]
Atom: Version 0.101.0-ae1b640 (0.101.0-ae1b640)
OSX: 10.9

Multi-comments in different languages (.js/java/etc) aren't behaving as known (cmd+opt+/) 

```
//normal single

step 1: 
function foo (){
  return  "bar";
};

step2: (ctr+/)
//step 1: 
//function foo (){
//  return  "bar";
//};

//multi
step 1: 
function foo (){
  return  "bar";
};

#No Change 
step2: (ctr+options+/)
function foo (){
  return  "bar";
};
#Expected
/*function foo (){
  return  "bar";
};*/
```
sounds similar to #2488

**Comment by 50Wliu** [comment]
I'm going to assume here that it's a community package that added the <kbd>alt+cmd+/</kbd> keybinding.  If that's not the case, however, and you can still reproduce this using the latest Atom version in safe mode (`atom --safe`), please let us know with a comment here!
