### ISSUE TITLE
Text Randomly Scrambled!?!?

### ISSUE THREAD

**Issue by jBot-42** [atom/atom#3435]
Atom 0.124.0, Mac OS X 10.9

Twice today (9/1/2014) I have had an issue where I click and all the text after where my cursor previously was is randomly scrambled, seemingly removing certain characters and mixing the rest. The issue seems to be so rare that it would be hard to reproduce. Any ideas of what exactly is causing this?

**Comment by benogle** [comment]
Is this still an issue @jBot-42?
