### ISSUE TITLE
Horizontal scrolling bug with soft wrap of many spaces

### ISSUE THREAD

**Issue by sylund** [atom/atom#3437]
When the soft wrap setting is turned on, horizontal scrolling should not happen. In special case of having abundant spaces, we can horizontally scroll it even though there is no character is shown.
- Atom version: 0.124.0
- OSX 10.9.4 and 10.10 (preview 2)
- Can reproduce it in the safe mode
- Using a monospace font. Tested in Menlo and Monaco.

Reproducing steps. Pleaser refer (http://pastie.org/9522131)
- Create a new file.
- In one line: put one word followed by about 80 space, and put another word in the end.
- Turn on soft wrap and try various window sizes.
- You can do horizontally scrolling; it shouldn't be.

**Comment by firefoxic** [comment]
I also reproduced this bug.

**Comment by GhostGambler** [comment]
What is the status of this issue? This seems to be an issue even with English characters only.

**Comment by coreyk** [comment]
This just cropped up for me on 1.13.0

**Comment by MaxBittker** [comment]
Any word on this? Atom is an awesome tool for code but I'm finding this weirdly disruptive for writing some markdown. 

Is this something that should be fixable in just styles? and if so, does anyone have an injectable or installable style sheet workaround (maybe one that could be promoted to a patch)?

**Comment by lee-dohm** [comment]
I can't reproduce this on Atom v1.16.0 on Mac OS X 10.12.4 using the steps to reproduce listed above. It would appear that the original issue here is fixed.

@MaxBittker If you're running into something similar, please open a new issue and fill in the issue template so that we can have all the appropriate information so we can investigate.

**Comment by MaxBittker** [comment]
thanks lee, I'll do that. the workaround i found was re-enabling `soft wrap at preferred line length`, this at least gives me a usable experience
