### ISSUE TITLE
"Show Line Numbers" option removes the gutter when turned off

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#3466]
Which is very rarely what the user wants. The gutter is a location that shows much other useful information, disabling it necessarily disables all that other functionality. The Show Line Numbers option should just hide the line numbers and _not_ remove the gutter completely.

See Discuss topics:
- https://discuss.atom.io/t/use-the-gutter-without-enabling-linenumbers/2461
- https://discuss.atom.io/t/hide-line-numbers/11987/2

**Comment by r-owen** [comment]
I also would like this feature. The gutter is crucial for linting, but I don't find line numbers useful.

I suggest independent options to show/hide line numbers and show/hide gutter.

**Comment by benogle** [comment]
This will be much easier when @nathansobo is all done with the editor internal changes / performance tuning.

**Comment by skariel** [comment]
+1

**Comment by spencerlyon2** [comment]
:+1:

**Comment by kaicataldo** [comment]
Still looking for help with this? I can take a look at it this week

**Comment by lee-dohm** [comment]
Yes, help would be wonderful :grinning:

**Comment by kaicataldo** [comment]
Cool :) Would having independent options to show/hide line numbers and show/hide the gutter as suggested above be the preferred approach?

**Comment by kaicataldo** [comment]
@r-owen lee-dohm So what's really missing is the git diff in the gutter, correct? I'm using https://github.com/atom-community/linter and am still seeing lines with errors still have a mark and show the correct error. The git diff is currently part of the line number elements themselves, but I don't think it would be difficult to change that.

<img width="533" alt="screen shot 2016-01-19 at 12 54 20 am" src="https://cloud.githubusercontent.com/assets/7041728/12410883/320ba4cc-be47-11e5-91e2-7ed3159d0ccb.png">

**Comment by wandoujun** [comment]
@kaicataldo What is the name of the theme that you using in your screenshots? It is beautiful ~!

**Comment by kaicataldo** [comment]
@wandoujun Hey there, I'm not using Atom much these days and I don't seem to have that theme installed any more, but I think it's a port of [Oceanic Next](https://atom.io/themes/oceanic-next) from Sublime

**Comment by wandoujun** [comment]
@kaicataldo Thanks~man.It is really helpful.

**Comment by nivv** [comment]
Any progress on this? I don't like the clutter line numbers bring. But the git gutter itself is neat

**Comment by GitTom** [comment]
+1

**Comment by TotomInc** [comment]
[I can't fold my code](https://discuss.atom.io/t/i-cant-fold-my-code/32077/10)

**Comment by dogweather** [comment]
(I just added https://discuss.atom.io/t/id-like-to-be-able-to-see-the-git-change-markers-in-the-gutter-even-if-i-hide-line-numbers/32487 )

A workaround would be to style the line numbers to be less bright using CSS. Could someone point me to the file and class style I'd edit to do this?

**Comment by dogweather** [comment]
@kaicataldo Yes, it'd be extremely helpful to have the git diff markers decoupled from the line numbers. See [my screenshots on discuss](https://discuss.atom.io/t/id-like-to-be-able-to-see-the-git-change-markers-in-the-gutter-even-if-i-hide-line-numbers/32487).

**Comment by 50Wliu** [comment]
This has been fixed by #14694.  When disabling the "Show Line Numbers" option, the gutter will continue to be visible.  Assuming no serious regressions are found, this setting should start to work as expected in Atom 1.19.0.
Example:
![gutter-without-line-numbers](https://cloud.githubusercontent.com/assets/2766036/26707903/0dc7f0d0-4716-11e7-826a-18791efb7937.png)

**Comment by jj-globant** [comment]
Atom 1.20.0 freshly downloaded still has this issue... in fact, i can't find a way to reinstate the gutter and the line numbers

**Comment by Ben3eeE** [comment]
@jj-globant Please open a new issue and completely fill out the issue template. Thank you 🙇

**Comment by jj-globant** [comment]
actually, my bad... it was some package with a conflict, did a bit of cleaning and everything works now 😄
