### ISSUE TITLE
Cursor's event 'moved' not triggered properly.

### ISSUE THREAD

**Issue by banacorn** [atom/atom#3473]
This issue can be reproduced as follows:

This code will move the cursor `right`, when it's `moved`
```coffeescript
editor.cursors[0].on 'moved', =>
  editor.moveCursorRight()
```

If you manually move the cursor `right`, the event will be triggered properly and the cursor will just go all the way to the end of the buffer. It's all good.

if you manually move the cursor `left`,  the event will be triggered properly, the cursor will be moved back to where you started.

``` 
1. initial cursor position

   *
   ^

2. manually move left

   *
  ^ 

3. 'moved' triggered, cursor move right

   *
   ^
```

But then, when you manually move the cursor `left` **again**, the event `moved` is not triggered at all. 
 
``` 
4. manually move `left` again

   * 
  ^

```

I think it has something to do with the state of the cursor position, it is not modified properly when `moveCursorRight` is called, so when we move the cursor `left` manually again, the editor will think that the cursor wasn't moved at all.

I'm on Darwin and I'm using `0.124.0`, thanks!

**Comment by benogle** [comment]
Anything come of this @nathansobo?

**Comment by nathansobo** [comment]
It's a deprecated API anyway so I'm not sure I care anymore.
