### ISSUE TITLE
Copy paste performance on large amount of text - display and syntax highlighting

### ISSUE THREAD

**Issue by xixixao** [atom/atom#3480]
Hi,

There is probably an issue for this, but just in case: I just compared CodeMirror, Ace and Atom in terms of performance, by pasting in [jQuery 2.2.1](http://code.jquery.com/jquery-2.1.1.js), my observations:
- [Ace](http://ace.c9.io/build/kitchen-sink.html) and [CodeMirror](http://codemirror.net/demo/sublime.html) performance is identical
- Both display the source instantaneously (FF 31, Mac), syntax highlighted
- Atom takes some time, probably sub-second, to display the text. It takes several seconds! to finish highlighting the source

If you guys have an insight into why this is so, I'd greatly appreciate some overview. Thanks for open-sourcing Atom!

**Comment by charleswhchan** [comment]
Pasting large amount of plain text (~8000 lines) into a new file is also very slow.
~15-20 seconds on Windows (For comparison, Notepad++ takes <1s)

**Comment by lee-dohm** [comment]
#5534 should have helped with copy/pasting large amounts of text. Please try it again and let us know if this is still an issue.

**Comment by charleswhchan** [comment]
Thanks @lee-dohm! I just upgraded to the latest 0.181.0 and can definitely see a significant improvement. 

Subjectively, it is still not as fast as a native app like Notepad++. However I would say the same operation in Atom only takes ~1 to 2s (max) now. Definitely more usable than 0.179.0.
