### ISSUE TITLE
Deleting files/directories fails (Debian x64)

### ISSUE THREAD

**Issue by olmokramer** [atom/atom#3491]
Deleting files from the right-click menu in the sidebar fails to actually delete the file. After clicking "delete" in the menu, the dialog pops up asking me if I want to move the file/dir to the trash. So I click "Move to trash" and then nothing happens. The file is still visible in the sidebar, and it still exists on my filesystem.

I'm on Linux (Debian) x64, Atom version 0.126, but I had the same problem with 0.124 and 0.123

**Comment by kelunik** [comment]
You still can't delete files that can't be moved to trash. Those files can't be deleted in the file manager either, but they can be deleted there using `shift + del`. Times ago, atom had an option to delete files directly without moving them to trash, but unfortunately that option has been removed.

**Comment by olmokramer** [comment]
Yeah, I know. I filed a pull request for permanent delete option here: https://github.com/atom/tree-view/pull/262

It probably needs to be rewritten though, because it's using old APIs i think.

**Comment by lee-dohm** [comment]
@kelunik @olmokramer #2897 has links to all the background on why the delete option was removed. I think you may have seen all of this, but I wanted to be sure and to point anyone else reading these posts in the right direction.

Thanks!

**Comment by kelunik** [comment]
@lee-dohm I can understand those arguments, but that doesn't change my opinion.

When I try do delete any file in `/var/www` (which is owned by me) in nautilus, I get an error sound using the `del` key. Using the context menu → delete results in a dialog asking if I want to remove the file permanently.

Those are files that can't be moved to trash and should thereby get an delete directly option. It's fine if only files that can't be moved to trash get this option.

**Comment by lee-dohm** [comment]
@kelunik I understand and I wasn't trying to change your opinion, just giving you and anyone else who finds this conversation all the information.
