### ISSUE TITLE
CPU Hog 90% + when text is selected

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#3500]
I am at latest master right now and i am experiencing slowness when i drag select text.
I am on Linux 64 bit  with GT70 Dominator (pro) Core i7 4th gen , Quad core. 8 GB Ram .
It happen when some line of text is selected up and down , CPU shoots up straight to 90%.

**Comment by benogle** [comment]
Is this still an issue?

**Comment by lee-dohm** [comment]
@v3ss0n Is this still an issue?

**Comment by v3ss0n** [comment]
let me try , I have become a driver for a past few months and no time to code :v

**Comment by benogle** [comment]
> I have become a driver

You're jason statham in my head now.

![enhanced-buzz-9943-1345346058-7](https://cloud.githubusercontent.com/assets/69169/12855328/a08030ee-cbf3-11e5-92be-14a4a9095024.jpg)

**Comment by demhydraz** [comment]
I honestly thought we were dealing with an AI that has become a video card driver

**Comment by v3ss0n** [comment]
Jason as frank (transpoter 1) : Rule #1. Never change the deal. :smile: 
Actually i practice a good deal of martial arts and look quite serious like Jason :laughing: 

Tested , after pasting long long long lines (over 10k lines) , scroll is smooth , cpu shoots up a bit (but now it is parallel processed across 8 cpus so never bog down the atom but still shoot about 50% ) .

Thanks a lot , I am back to coding after "Transporting" Projects to "Clients" :laughing: .

**Comment by v3ss0n** [comment]
Frank Martin: It was just a favor. I don't usually do this sort of a job.
Audrey Billings: I thought you were a professional driver?
Frank Martin: A different kind of driver.
/close
