### ISSUE TITLE
Cursor doesn't move on right mouse down

### ISSUE THREAD

**Issue by 1j01** [atom/atom#3502]
The cursor doesn't move, so the context for the context menu isn't updated or so to speak, which is a problem when pasting or [correcting spelling](https://github.com/atom/spell-check/issues/32).

Fixing this breaks ([at least](http://xkcd.com/1172/#You-should-have-known-I-was-linking-you-here)) the workflow of right-clicking outside of the selection to perform actions on it.

**Comment by thomaslindstrom** [comment]
Any updates on this? For me, it's completely obvious that when I right click somewhere in the editor, the cursor follows. Anything else is bad UX, and this has annoyed me for a while.

What am I actually interacting with?
![screen shot 2015-06-11 at 15 16 57](https://cloud.githubusercontent.com/assets/2833514/8107866/eb0f1ef8-104c-11e5-8e8e-a3134082f694.png)

This also applies to context menu interaction in the tree view sidebar: I have absolutely no idea what I'm actually interacting with when right clicking anything but the active selection.

![screen shot 2015-06-11 at 15 15 58](https://cloud.githubusercontent.com/assets/2833514/8107855/d0c14e90-104c-11e5-899b-cba1ce1b426d.png)

**Comment by mnquintana** [comment]
FWIW, Sublime and TextMate work the same way; Brackets selects the nearest word when you right-click. VS Code does work this way, however. I would personally be :+1: for this.

**Comment by 1j01** [comment]
To clarify, option 3. should be "Move the mouse on RMD unless clicking on a selection" (because otherwise you wouldn't be able to copy anything from the context menu)

**Comment by carlosdp** [comment]
I would love this too. I'm trying to develop a package right now that has a context-menu that has different options based on data derived from the line right-clicked and it's near impossible with the Shadow DOM right now. If the cursor moved with the right-click, it would be trivial. :+1:

**Comment by 1j01** [comment]
@carlosdp Yeah, packages definitely should not have to work around the lack of context associated with context menus.

**Comment by Galadirith** [comment]
I would echo @carlosdp and @1j01. Not having contextual information associated with a right-click event/context menu makes certain designs very difficult to implement and it would be a really welcome improvement. :+1:
