### ISSUE TITLE
Atom close the process "Explorer" on Windows when saving a file.

### ISSUE THREAD

**Issue by Xety** [atom/atom#3533]
Hello,

I have a little problem with Atom. When i save a file, **sometimes** Atom (or maybe a plugin) kill the process "Explorer" on Windows. I have trying to disable 95% of all my plugins, but still the same. The problem is that it's not all times, but just sometimes. And i'm 100% sure that is Atom and not another soft, because when i use PhpStorm, it's never happened.
![xdcc0sd](https://cloud.githubusercontent.com/assets/8210023/4262196/7a885e5e-3b92-11e4-83ee-9c135f08d556.png)

And in the console, i have nothing about that, only one error about the plugin AtomLinter when i start Atom :
![0t8ihup](https://cloud.githubusercontent.com/assets/8210023/4262199/e3063a8c-3b92-11e4-88a9-ea6f743d665e.png)

Configuration :
Atom : 0.127.0
Windows : 8.1

(Sorry for my english, i'm french.)

**Comment by BlaM** [comment]
Just as a side note: Haven't seen that problem anymore for quite some time now. May be fixed.

**Comment by Xety** [comment]
@BlaM Same for me, it look like it had be fixed.

I close the issue and if the problem is back i will re-open it.

**Comment by tortuetorche** [comment]
Back again with Atom 0.176.0 :disappointed:

**Comment by tortuetorche** [comment]
FYI I have this issue with Atom 0.186.0

**Comment by Xety** [comment]
For me, it's fixed. Atom 0.182.0, Windows 10 Technical Preview

**Comment by BlaM** [comment]
Haven't seen the problem appear since [my last post](#issuecomment-69553125)

**Comment by tortuetorche** [comment]
If I apply the [patch](https://github.com/atom/atom/issues/3533#issuecomment-56857630) of @kevinsawicki, this issue is gone.

**Comment by tortuetorche** [comment]
FYI this issue still occurs with Atom 0.188.0

**Comment by batjko** [comment]
@tortuetorche It's been a while for this issue so let's cover the basics. 
Can you re-iterate what file you were trying to save in which location when this happens?
Does it happen every single time (with the same file or in the same location) or rather randomly?

**Comment by tortuetorche** [comment]
It happens randomly.

**Comment by tortuetorche** [comment]
Same issue with Atom 0.194.0.
And the `resources\app\src\buffered-process.js` file doesn't exist anymore.
We can edit the `resources/app.asar` file to apply the [patch](https://github.com/kevinsawicki) of @kevinsawicki but then `atom` fails to load.
How can I edit the `resources/app.asar` file safely ?

**Comment by BlaM** [comment]
Have you tried doing a clean reinstall of ATOM (including .atom directory)? And maybe a reinstall of PHP/PHPCS for the linter?

**Comment by tortuetorche** [comment]
I cleanly reinstall Atom, but not the `.atom` directory, and I already reinstall PHP linters with no luck.

**Comment by tortuetorche** [comment]
I'll try this week to test Atom with a fresh `.atom` directory.

**Comment by 50Wliu** [comment]
@tortuetorche have you gotten a chance to test this again?

**Comment by tortuetorche** [comment]
Yep, since version 1.0.x this issue is gone :+1:

**Comment by Xety** [comment]
I didn't get this error again since months now. Seem to be fixed.

**Comment by leluna** [comment]
I am having this issue with Atom 1.21.1. explorer.exe gets randomly killed, I have not yet found out the trigger. I don't have any php linters installed. Any hint on how to find out the cause?

**Comment by atom75** [comment]
I'm also having this issue with v1.21.1 x64. I'm writing Python and I think it happens when I'm saving, quite frequently, though not always, so I'm not sure. Couldn't find the js file mentioned above to see if it makes any difference. Is there any way I can make a similar change so I'll be able to pass this issue and work normally? Please let me know if I can help somehow by supplying more information

**Comment by BlaM** [comment]
a) I think you should probably open a new issue as the old one here has been solved and you probably have a new problem.
b) I'd assume that the problem is connected with starting something as a shell command (probably another EXE file, like php.exe, python.exe or something similar). Maybe there is a connection to atom-ide?
