### ISSUE TITLE
Register commands to disable/enable packages

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#3553]
Instead of having to dig deep into the settings view, there should probably be top level commands to enable/disable each package.

That way if you want to turn of something like spell check, you can do it from the command palette (`Cmd-Shift-P`) instead of having to click around the settings view.

Refs https://github.com/atom/spell-check/pull/33

**Comment by mnquintana** [comment]
Refs https://github.com/atom/settings-view/issues/464

**Comment by bronson** [comment]
I really like the idea of keeping packages around, but not using them (and not having them occupy memory / load time) until I actually need them.  :+1:

**Comment by liuderchi** [comment]
I agree with @dmnd and now using [package-manager-command](https://atom.io/packages/toggle-packages "url"). 
btw I type command ```Package-Manager : Enable Package``` to list disabled packages
