### ISSUE TITLE
normalizeIndentOnPaste deletes indent

### ISSUE THREAD

**Issue by jwalton** [atom/atom#3558]
`normalizeIndentOnPaste` is supposed to [convert tabs to spaces, or spaces to tabs](https://atom.io/docs/v0.59.0/customizing-atom#configuration-key-reference).  Instead it [removes all indentation from the start of the line](https://discuss.atom.io/t/normalize-indent-on-paste-doesnt-work-as-expected/3503/5).

In a coffee file, try cutting and then immediately pasting the middle line:

```
    console.log "foo"
    console.log "bar"
    console.log "baz"
```

You get:

```
    console.log "foo"
console.log "bar"
    console.log "baz"
```

which is definitely note what `normalizeIndentOnPaste` should be doing.

**Comment by izuzak** [comment]
@jwalton Wondering if you can still reproduce this problem in Atom 1.0.11. The `normalizeIndentOnPaste` config option was removed a while ago in https://github.com/atom/atom/pull/4239 and the functionality related to it is always triggered. I just tried reproducing the problem you reported and wasn't able to, so I was wondering if you can still trigger the issue somehow. :thought_balloon:

**Comment by jwalton** [comment]
No, seems to be working for me now.
