### ISSUE TITLE
Pressing enter for long cause CPU to shootup 100%

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#3563]
Performance regression while entering new lines.
After 2-3 secs CPU will shoot up to 100% of pressing and holding enter.
Tested with --safe, after about 1000 lines Atom gives up , quit with a crash. 
Also tested with auto-save turned off.

**Comment by damieng** [comment]
Going to close this as there's been no additional reports/commentary on this for 2 years.

**Comment by v3ss0n** [comment]
It was gone since 1.x releases  thanks.
