### ISSUE TITLE
"Invisible" devtools mode

### ISSUE THREAD

**Issue by dmnd** [atom/atom#3568]
When I have the devtools closed, sometimes they pop up to tell me about an error that occurred. But there's never a stack trace, so this error message isn't very actionable. It's my understanding that stacktraces are only captured when the devtools are open before the error is thrown.

One solution to this is to always have the devtools open, but that takes up screen space. Another is to pop them out of the Atom window, but that gets confusing if you have multiple windows open.

It would be nice to have some kind of "invisible" devtools mode where it will still capture stacktraces (and do whatever else it does), but otherwise have the editor work normally. There's probably some kind of performance penalty incurred by having the devtools open, so maybe this could be behind a flag like `atom --debug`.

**Comment by 50Wliu** [comment]
The Notifications package should be sufficient now.
