### ISSUE TITLE
Ability to log in with GitHub account to sync Atom config

### ISSUE THREAD

**Issue by ilanbiala** [atom/atom#3572]
It would be great if I could login with a GitHub account and have Atom store my settings either in Dropbox, or GitHub as a repository, or in some way that is easy to access and maybe even sync them across all my installations of Atom so that when I download a new package, it is downloaded everywhere. Another suggestion is to be able to manually export a .atomconfig JSON file that I could just import to Atom at any point to configure settings, install packages, change themes, etc.

I think having the first would be more important for most people, but for anyone who is offline and for anyone who likes to keep their own backups in other places, the manual settings export is really useful.

If this sounds like a good idea to Atom contributors and consumers, I'd like to help out with the PR to make this happen.

**Comment by zephraph** [comment]
I think it'd be interesting if there was a websocket connection between Atom and atom.io on sign in. Then you could technically add "install" buttons and the like to atom.io and have that action automatically reciprocated on Atom. 

@simurai mentioned something to this effect on my [PR](https://github.com/atom/settings-view/pull/351#issuecomment-72020587) for atom settings-view

**Comment by thedaniel** [comment]
:+1: I want this, but IMO if we are going to support it as an official  package, it will require integration work to use the (non-open-source) atom.io API as the sync source. 

I'm down to do that but I have other things on my plate right now so I think what this needs to go forward first is an API proposal. That is to say, someone should think about how the sync API would work and document it, and we can talk about it and refine it.

 An upside to starting there is that having this nicely documented means that a) the package is easier to write and b) if people want to create their own sync servers and not use the one atom.io provides, the doc will make it super easy for them (and once we agree on a doc we will commit to atom.io staying compatible).

**Comment by zephraph** [comment]
Agreed. One other thing Atom will need before that gets implemented is an official Auth package. Setting up and storing personal tokens (or whatever auth method chosen) securely. I'll probably go ahead and create an issue on that for visibility.

**Comment by thedaniel** [comment]
Pretty sure there's already keychain support, and the apm client definitely stores tokens securely on all platforms.

**Comment by zephraph** [comment]
I'll have to look into that. It'd just be nice if there was built in support for doing that with GitHub.

**Comment by chrisfarms** [comment]
:+1: this would be the killer feature for me ... I'm so bored of managing .vimrc in dotfiles repositories, I just want to download atom, login and have my usual environment

**Comment by shaohua** [comment]
This would be a killer feature and it fits great into the strategy goal of github as the ecosystem

**Comment by Xaviju** [comment]
+1

**Comment by batjko** [comment]
There's still this package:
https://atom.io/packages/sync-settings

But I don't know if it still works or gets maintained.

**Comment by ilanbiala** [comment]
@thedaniel what else can be configured/customized other than:
* packages
* themes
* atom stylesheets, init scripts, keymaps
* preferences

If that's all, I think the simplest way is to just sync on program startup?

A few ideas as to where the data is stored:
* GitHub server as part of user account
* GitHub repository

**Comment by thedaniel** [comment]
@ilanbiala That's pretty much it. Here are a couple interesting edge cases:

- packages that users check out into their packages directory directly rather than install from atom.io
- packages that need to compile native node dependencies
- stylesheets and init scripts that refer to other files, whether under the .atom tree or elsewhere on disk

A first pass at this that just syncs a list of package and theme names and installs them via APM, as well as the contents of init.coffee, styles.less, config.cson, keymap.cson, and snippets.cson would be acceptable, and just assume that if someone is checking out git repos or extracting tarballs into .atom or doing clever things with config they can handle that themselves, or just check it all into a repo and be done with it.

**Comment by thedaniel** [comment]
> or just check it all into a repo and be done with it.

Also, it would be quite easy for someone to write a package that automates this particular method without it having to touch core or the API.

**Comment by mrmckeb** [comment]
it would be ideal to have this as a native feature. sync-settings is great, but it needs to be maintained and works in a bit of a 'hacky' way.

**Comment by ahmetabdi** [comment]
:+1:

**Comment by alexander-jiang** [comment]
+1 This would make it a lot easier to just install and work comfortably, without having to hunt down packages and change keybinds.

**Comment by harangue** [comment]
+1 Keeping packages in sync is a pain

**Comment by raphway** [comment]
+1 Having all my settings and packages synced across all my devices would be awesome.

**Comment by orthros** [comment]
:+1: Working on 3 devices makes this an _absolute_ must-have for me.

**Comment by petersandor** [comment]
+1 Yes please.

**Comment by cbstodd** [comment]
+ 1.  

Isn't Atom built of off Chromium? I know very little about what it would take to get this feature, but signing in as you would sign into your Chrome or Firefox browser and have all settings/addons synced seems like it could be done. But again, I know very little.

**Comment by fnkr** [comment]
- AFAIK Chromium (open source) doesn't have the syncing capabilities that Google Chrome (based on Chromium but closed source) has.
- Atom uses the node package manager (npm) for installing packages (with hooks, dependencies and everything). Chrome/Chromium extensions are just zip files with another file extension (`.crx`), extracted into a specific directory
- Chrome/Chromium extensions store their config data in localStorage (sqlite), Atom extensions store their config data in Atom's config file or their own config file (yaml).

**Comment by brevilo** [comment]
It would be great to have the actual profile storage implemented in a pluggable way such that alternative profile storage solutions (WebDAV, Dropbox) could be added later on. Or just provide built-in WebDAV sync right away :grin: 

Other than that: :+1: this one is a must since syncing `~/.atom` as a whole via WebDAV is way too heavyweight and unreliable with (at least some) available sync solutions...

**Comment by tclzcja** [comment]
Do we have any progress on this? I mean yes we can use sync-setting and it works pretty fine, but I really feel like this should be a built-in feature. It also enhance the connection between Atom and Github.com - just like how the "Open in Atom" in Github for Windows enhances the connection between Atom and itself.

**Comment by raphalvessa** [comment]
This might be a stale issue, but this feature still isn't available.

**Comment by sra1mothe** [comment]
can someone please tell me where i can find the signin-form in atom,
which allows me to upload stuff to my github repo

**Comment by ilanbiala** [comment]
@thomasjo @kevinsawicki it seems like some people have developed packages to do this, but why isn't this bundled with Atom/developed by the core Atom team?

**Comment by Ali-00-Ridha** [comment]
would you ever consider working on this issue/feature? I beleave it's a very good idea to backup atom settings/packages/snippets, so if anything go wrong you could restore everything.

besides that you could easly copy/move atom to another PC using this feature.

**Comment by UziTech** [comment]
@Ali-00-Ridha this is possible with [`sync-settings`](https://atom.io/packages/sync-settings)
