### ISSUE TITLE
Invalid characters saved in wrong format

### ISSUE THREAD

**Issue by itzurabhi** [atom/atom#3607]
-/* | 0x000000~0x030000: ÖÐÎÄÏÔÊ¾×Ö¿â | 0x030000~0x0AF000: 24*24´òÓ¡×Ö¿â 
-   | 0x0AF000~0x0E4FB0: 16*16´òÓ¡×Ö¿â| */

the above text in my file was saved as below:

+/* | 0x000000~0x030000: ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê¾ï¿½Ö¿ï¿½ | 0x030000~0x0AF000: 24*24ï¿½ï¿½Ó¡ï¿½Ö¿ï¿½
+   | 0x0AF000~0x0E4FB0: 16*16ï¿½ï¿½Ó¡ï¿½Ö¿ï¿½| */

**Comment by kevinsawicki** [comment]
This should be addressed by the encoding selector Atom added awhile back that is available from the status bar and hitting `ctrl-shift-U`.
