### ISSUE TITLE
Editing longest line repaints entire editor

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#3621]
The entire editor area repaints on every keystroke when the cursor is on the longest line in the file.

Not sure if this can be avoided since I assume it is updating some width calculation.

![repaint-longest-line](https://cloud.githubusercontent.com/assets/671378/4397288/02af9ac6-4440-11e4-9482-bdf6f78863d1.gif)

/cc @nathansobo we talked briefly about this and thought initially it was an issue when editing the first line but it appears to be related to longest line editing.

**Comment by mnquintana** [comment]
Is this still an issue?

**Comment by nathansobo** [comment]
Not sure. I'll check real quick. The tiled rendering that's about to land should shift the landscape pretty significantly.

**Comment by nathansobo** [comment]
Somewhere along the way this got fixed. Hurray for accidental improvement.
