### ISSUE TITLE
Editor crashes on saving or on opening a file that has been modified

### ISSUE THREAD

**Issue by matthewpennell** [atom/atom#3627]
In the last 2 days, Atom has started to:

* Crash immediately after saving an edited file
* Crash whenever you try to open a file that has been modified but not committed (according to git) - verified by committing the file and then trying to open it, which then works

It appears to have issues reconciling the git status of the file on opening or saving, maybe? I'm not using any complex arrangement of plugins.

**Comment by daithi-coombes** [comment]
I am getting this issue as well. Steps:
 - `$ atom --safe`
 - new file | rename file

std outputs the following after the crash:
``` bash
$ /usr/bin/atom: line 92:  5996 Segmentation fault      (core dumped) nohup "$ATOM_PATH" --executed-from="$(pwd)" --pid=$$ "$@" > "$DOT_ATOM_DIR/nohup.out" 2>&1
[5996:0110/210959:ERROR:browser_main_loop.cc(163)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[6029:0110/210959:INFO:renderer_main.cc(207)] Renderer process started
App load time: 347ms
[5996:0110/211002:INFO:CONSOLE(64)] "Window load time: 2239ms", source: file:///usr/share/atom/resources/app/static/index.js (64)
Crash dump id: ea8eb240-07ec-4776-a32b-d9db8b788bb9
```

should also note that my git repo is in a sub directory of the project root, but this issue still happens if I open in the repo root folder.

**Comment by kevinsawicki** [comment]
@daithi-coombes is the repository you are seeing this issue in public? If so, can you share a link and which branch you have checked out when this happened?

**Comment by matthewpennell** [comment]
Just to update this bug report (I was the original reporter) I am still having this problem after upgrading to Atom 1.0. Modify a file, save, Atom crashes. Re-open Atom and try to reopen the file, Atom crashes every time.

**Comment by cleung2010** [comment]
I am also having this issue on Atom 1.0

**Comment by matthewpennell** [comment]
This problem now manifests even when Atom is opened in safe mode (atom --safe). Attempting to re-open a modified file crashes the app.

**Comment by ClemensSahs** [comment]
@zcbenz
Sorry for missing feedback. Yes in my case gitlib update was fixed this problem.

**Comment by Ian5015** [comment]
Just started receiving this issue today after changing branches and then back again. Removing .gitattributes doesn't help and Starting atom in safe mode doesn't help. Only occurs when attempting to open files in this particular repo. Opening any files in another repo works fine.

**Comment by nialexsan** [comment]
I have the same issue after updating to 1.1.0. On 1.0.19 it works fine

**Comment by Ian5015** [comment]
@nialexsan thank you for mentioning that it still works on the 1.0.19.

**Comment by rahul-wyzen** [comment]
I am having the same issue from the last two days or so. I am using the atom 1.1.0 version.

**Comment by briantweed** [comment]
I've starting experiencing this problem as of 2-3 days ago. Whenever I try to open a newly created file  Atom crashes. However if I commit the files to github I can then open them in Atom without any problems

**Comment by cttibbetts** [comment]
Getting this same exact issue. Atom is completely unusable. Saving any file causes an immediate crash.

**Comment by Zireael07** [comment]
Related to #9339?

**Comment by briantweed** [comment]
Yes,thanks

**Comment by marcofranssen** [comment]
Same error on my side for newly added files inside a git repository folder. As soon you create a new file via atom it crashes immediately.
As soon you try to open a newly created file it crashes. Meaning if you created the file using notepad.

I'm on Windows 8.1 using Atom 1.1.0. 

Didn't had this issue before.

**Comment by ramumb** [comment]
I just started experiencing this issue two days ago.  I'm on Windows 10 and using Atom 1.1.0.  It occurs every time I try to open a file.  I've had to revert to Notepad++ to get any work done :-(

**Comment by 50Wliu** [comment]
Please try 1.2.0-beta2 which should fix this issue.

**Comment by ramumb** [comment]
@50Wliu: I just tried installing the 1.2.0-beta2 but ran into https://github.com/atom/atom/issues/5109.

**Comment by Ian5015** [comment]
@ramumb if you had a previous version of Atom installed, you can still run it from the appdata/local if you're on Windows. I'm using 1.0.19 until this is resolved.

**Comment by ramumb** [comment]
@Ian5015: +1.  I'm back in business baby!  Thank you.

**Comment by beelol** [comment]
I'm having this on 1.8.0. Whenever I run webpack to generate a bundle.js file, my editor freezes.

**Comment by heliosam** [comment]
@beelol that happened also to me and I realized that it was because I had the `bundle.js` file opened in the editor. Closing the generated file solved the issue. Maybe same problem for you?

**Comment by nicholaschris** [comment]
@beelol I have the same problem sometimes (having `bundle.js` open causes the editor to freeze. I am curious to why having bundle.js open would cause the editor to freeze? Do you know?

**Comment by azz0r** [comment]
I suspect its due to the editor colouring such a large single line - can a length check be performed and colouring skipped if its past a certain length?

**Comment by Zireael07** [comment]
@azz0r I believe such a check is currently in the beta3.

**Comment by 50Wliu** [comment]
(though you'll want beta4 for an additional JS performance fix)
