### ISSUE TITLE
Resize cursor doesn't appear in tree view.

### ISSUE THREAD

**Issue by filipesilva** [atom/atom#3629]
In windows, the resize cursor doesn't appear for the tree view.
![cursor](https://cloud.githubusercontent.com/assets/4172079/4403436/23ceb5b2-44a3-11e4-8c2f-5d31cf94e267.gif)

**Comment by mnquintana** [comment]
This should've been fixed awhile ago, so I'm going to close this. Feel free to comment / reopen if you experience this again!
