### ISSUE TITLE
Error building Atom on Windows 7 x64

### ISSUE THREAD

**Issue by Andeke** [atom/atom#3634]
Hi, 
I'm trying to build atom on my Windows 7 64-bit PC, and here's the error:

>D:\atom [master]> script/build
>Node: v0.10.32
>npm: v1.4.28
>Python: v2.7.8
>Installing build modules...
>Installing apm...
>Installing modules failed
> atom@0.132.0 preinstall D:\atom
> node -e 'process.exit(0)'
>
>
> scrollbar-style@1.0.2 install D:\atom\node_modules\scrollbar-style
> node-gyp rebuild
>
>
>D:\atom\node_modules\scrollbar-style>node "D:\atom\apm\node_modules\atom-package
>-manager\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node
>-gyp.js" rebuild
>Building the projects in this solution one at a time. To enable parallel build,
>please add the "/m" switch.
>Project file contains ToolsVersion="12.0". This toolset may be unknown or missin
>g, in which case you may be able to resolve this by installing the appropriate v
>ersion of MSBuild, or the build may have been forced to a particular ToolsVersio
>n for policy reasons. Treating the project as if it had ToolsVersion="4.0". For
>more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
>Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not in
>stalled or invalid. Please make sure that a supported PlatformToolset value is s
>elected. [D:\atom\node_modules\scrollbar-style\build\scrollbar-style-observer.vc
>xproj]
>
> keyboard-layout@0.7.0 install D:\atom\node_modules\atom-keymap\node_modules\ke
>yboard-layout
> node-gyp rebuild
>
>
>D:\atom\node_modules\atom-keymap\node_modules\keyboard-layout>node "D:\atom\apm\
>node_modules\atom-package-manager\node_modules\npm\bin\node-gyp-bin\\..\..\node_
>modules\node-gyp\bin\node-gyp.js" rebuild
>Building the projects in this solution one at a time. To enable parallel build,
>please add the "/m" switch.
>Project file contains ToolsVersion="12.0". This toolset may be unknown or missin
>g, in which case you may be able to resolve this by installing the appropriate v
>ersion of MSBuild, or the build may have been forced to a particular ToolsVersio
>n for policy reasons. Treating the project as if it had ToolsVersion="4.0". For
>more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
>Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not in
>stalled or invalid. Please make sure that a supported PlatformToolset value is s
>elected. [D:\atom\node_modules\atom-keymap\node_modules\keyboard-layout\build\ke
>yboard-layout-observer.vcxproj]
>
> runas@1.0.1 install D:\atom\node_modules\runas
> node-gyp rebuild
>
>
>D:\atom\node_modules\runas>node "D:\atom\apm\node_modules\atom-package-manager\n
>ode_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" r
>ebuild
>Building the projects in this solution one at a time. To enable parallel build,
>please add the "/m" switch.
>Project file contains ToolsVersion="12.0". This toolset may be unknown or missin
>g, in which case you may be able to resolve this by installing the appropriate v
>ersion of MSBuild, or the build may have been forced to a particular ToolsVersio
>n for policy reasons. Treating the project as if it had ToolsVersion="4.0". For
>more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
>Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not in
>stalled or invalid. Please make sure that a supported PlatformToolset value is s
>elected. [D:\atom\node_modules\runas\build\runas.vcxproj]
>
> nslog@1.0.1 install D:\atom\node_modules\nslog
> node-gyp rebuild
>
>
>D:\atom\node_modules\nslog>node "D:\atom\apm\node_modules\atom-package-manager\n
>ode_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" r
>ebuild
>Building the projects in this solution one at a time. To enable parallel build,
>please add the "/m" switch.
>Project file contains ToolsVersion="12.0". This toolset may be unknown or missin
>g, in which case you may be able to resolve this by installing the appropriate v
>ersion of MSBuild, or the build may have been forced to a particular ToolsVersio
>n for policy reasons. Treating the project as if it had ToolsVersion="4.0". For
>more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
>Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not in
>stalled or invalid. Please make sure that a supported PlatformToolset value is s
>elected. [D:\atom\node_modules\nslog\build\nslog.vcxproj]
>
> pathwatcher@2.1.3 install D:\atom\node_modules\pathwatcher
> node-gyp rebuild
>
>
>D:\atom\node_modules\pathwatcher>node "D:\atom\apm\node_modules\atom-package-man
>ager\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
>.js" rebuild
>Building the projects in this solution one at a time. To enable parallel build,
>please add the "/m" switch.
>Project file contains ToolsVersion="12.0". This toolset may be unknown or missin
>g, in which case you may be able to resolve this by installing the appropriate v
>ersion of MSBuild, or the build may have been forced to a particular ToolsVersio
>n for policy reasons. Treating the project as if it had ToolsVersion="4.0". For
>more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
>Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not in
>stalled or invalid. Please make sure that a supported PlatformToolset value is s
>elected. [D:\atom\node_modules\pathwatcher\build\pathwatcher.vcxproj]
>
> oniguruma@3.0.4 install D:\atom\node_modules\oniguruma
> node-gyp rebuild
>
>
>D:\atom\node_modules\oniguruma>node "D:\atom\apm\node_modules\atom-package-manag
>er\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.j
>s" rebuild
>Building the projects in this solution one at a time. To enable parallel build,
>please add the "/m" switch.
>Project file contains ToolsVersion="12.0". This toolset may be unknown or missin
>g, in which case you may be able to resolve this by installing the appropriate v
>ersion of MSBuild, or the build may have been forced to a particular ToolsVersio
>n for policy reasons. Treating the project as if it had ToolsVersion="4.0". For
>more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
>Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not in
>stalled or invalid. Please make sure that a supported PlatformToolset value is s
>elected. [D:\atom\node_modules\oniguruma\build\oniguruma.vcxproj]
>
> git-utils@2.1.4 install D:\atom\node_modules\git-utils
> node-gyp rebuild
>
>
>D:\atom\node_modules\git-utils>node "D:\atom\apm\node_modules\atom-package-manag
>er\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.j
>s" rebuild
>Building the projects in this solution one at a time. To enable parallel build,
>please add the "/m" switch.
>Project file contains ToolsVersion="12.0". This toolset may be unknown or missin
>g, in which case you may be able to resolve this by installing the appropriate v
>ersion of MSBuild, or the build may have been forced to a particular ToolsVersio
>n for policy reasons. Treating the project as if it had ToolsVersion="4.0". For
>more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
>Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not in
>stalled or invalid. Please make sure that a supported PlatformToolset value is s
>elected. [D:\atom\node_modules\git-utils\build\libgit2.vcxproj]
>Project file contains ToolsVersion="12.0". This toolset may be unknown or missin
>g, in which case you may be able to resolve this by installing the appropriate v
>ersion of MSBuild, or the build may have been forced to a particular ToolsVersio
>n for policy reasons. Treating the project as if it had ToolsVersion="4.0". For
>more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
>Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not in
>stalled or invalid. Please make sure that a supported PlatformToolset value is s
>elected. [D:\atom\node_modules\git-utils\build\zlib.vcxproj]
>Project file contains ToolsVersion="12.0". This toolset may be unknown or missin
>g, in which case you may be able to resolve this by installing the appropriate v
>ersion of MSBuild, or the build may have been forced to a particular ToolsVersio
>n for policy reasons. Treating the project as if it had ToolsVersion="4.0". For
>more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.
>Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not in
>stalled or invalid. Please make sure that a supported PlatformToolset value is s
>elected. [D:\atom\node_modules\git-utils\build\http_parser.vcxproj]
>
>gypnpm WARN engine specificity@0.1.3: wanted: {"node":"~0.8.x"} (current: {"node
>":"v0.10.32","npm":"1.4.4"})
>
>gypnpm ERR! scrollbar-style@1.0.2 install: `node-gyp rebuild`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the scrollbar-style@1.0.2 install script.
>npm ERR! This is most likely a problem with the scrollbar-style package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node-gyp rebuild
>npm ERR! You can get their info via:
>npm ERR!     npm owner ls scrollbar-style
>npm ERR! There is likely additional logging output above.
>npm ERR! System Windows_NT 6.1.7601
>npm ERR! command "D:\\atom\\apm\\node_modules\\atom-package-manager\\bin\\\\node
>.exe" "D:\\atom\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin
>\\npm-cli.js" "--globalconfig" "D:\\atom\\apm\\node_modules\\atom-package-manage
>r\\.apmrc" "--userconfig" "C:\\Users\\Andeke\\.atom\\.apmrc" "install" "--target
>=0.16.0" "--arch=ia32" "--quiet" "--msvs_version=2013"
>npm ERR! cwd D:\atom
>npm ERR! node -v v0.10.32
>npm ERR! npm -v 1.4.4
>npm ERR! code ELIFECYCLE
>gypgypgypgypgypnpm

**Comment by jimgraham** [comment]
This error

```
 error MSB8008: Specified platform toolset (v120) is not in
stalled or invalid. Please make sure that a supported PlatformToolset value is s
elected. [D:\atom\node_modules\git-utils\build\zlib.vcxproj]
Project file contains ToolsVersion="12.0". This toolset may be unknown or missin
g, in which case you may be able to resolve this by installing the appropriate v
ersion of MSBuild, or the build may have been forced to a particular ToolsVersio
n for policy reasons.
```

and the fact that some of the node modules build with ` "--msvs_version=2013"` implies that you may need VS 2013 (although the [build docs](https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md) say that it is not necessary for windows 7). Toolset `v120` corresponds to VS 2013.

Caveat: I've not tried to build the full Atom, only atom-shell

You can download the free [VS 2013 Community](http://www.visualstudio.com/en-us/downloads/download-visual-studio-vs#DownloadFamilies_2)

**Comment by kevinsawicki** [comment]
Closing this out, visual studio is a requirement to build on Windows, you can run `apm -v` to check the detected version.
