### ISSUE TITLE
Atom not able to use a new version of npm

### ISSUE THREAD

**Issue by TCS-JMI** [atom/atom#3653]
The installation of package Proton-IDE is failing because Atom is working with npm 1.4.4
Even after installing npm 1.4.28 on the PC,  and installing npm2.0.0 package in Atom,  Atom still works with npm1.4.4 when loading Proton-IDE package:

npm ERR! Error: ENOENT, open 'C:\Users\MJ04026\AppData\Local\Temp\apm-install-dir-114829-2180-1u6ffns\node_modules\Proton-IDE\node_modules\xml2js\node_modules\xmlbuilder\node_modules\lodash-node\compat\arrays\range.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\MyPrograms\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\MyPrograms\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\MyPrograms\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\MJ04026\\.atom\\.apmrc" "install" "C:\\Users\\MJ04026\\.atom\\.node-gyp\\.atom\\.apm\\Proton-IDE\\0.10.0\\package.tgz" "--target=0.16.0" "--arch=ia32" "--msvs_version=2010"
npm ERR! cwd C:\Users\MJ04026\AppData\Local\Temp\apm-install-dir-114829-2180-1u6ffns
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.4

**Comment by 50Wliu** [comment]
@TCS-JMI can you still reproduce this?

**Comment by TCS-JMI** [comment]
I don't need proton-ide anymore, so I close the case. 
Regards
