### ISSUE TITLE
Keymaps works partially on Ubuntu

### ISSUE THREAD

**Issue by vinigdex** [atom/atom#3659]
Hi guys, the keymaps part works on Ubuntu. An example is Split View does not work with keymaps

Ubuntu 14.04

![screenshot from 2014-09-30 03 36 12](https://cloud.githubusercontent.com/assets/4214807/4454203/1692b818-486c-11e4-940b-1354aae4a290.png)

**Comment by richtmat** [comment]
@benogle @vinigdex with version 0.172.0 I can confirm that multi-stroke commands do work now.

**Comment by benogle** [comment]
Closing as multi-stroke commands work.
