### ISSUE TITLE
Improve startup time

### ISSUE THREAD

**Issue by benogle** [atom/atom#3673]
Status: This is an ongoing effort.

Via @kevinsawicki 

The current plan is to investigate what is slow on startup, optimize it, and then investigate concatenating all the CoffeeScript requires to save eval time on startup.
### Merged Changes

Times below are were taken with a Macbook Pro on OS X 10.8.5 with 2.6 Ghz Intel Core i7 processors and 16 GB of memory
- https://github.com/atom/less-cache/commit/dbddce5d34aee85f8b3687d5ec9e5837bdb9bb7a
  - Saves `~40ms` when starting Atom with a fully warm Less cache
- https://github.com/atom/atom/pull/3453
  - Cuts browser process launch time by `~33%`
  - Saves `~60ms` on startup
- https://github.com/atom/atom/pull/3470
  - Cuts time taken to apply stylesheets by `~66%`
  - Saves `~40ms` on startup
- https://github.com/atom/wrap-guide/pull/16
  - Saves `~10ms` on startup
- https://github.com/atom/atom/pull/3519
  - Saves `~250ms` on startup
- https://github.com/atom/tree-view/pull/219
  - Saves `~200ms` on startup for large projects.
- https://github.com/atom/status-bar/pull/35
  - Save `~30ms` on startup
- https://github.com/atom/tabs/pull/82
  - Saves `~15ms` on startup
- https://github.com/atom/atom/pull/3917
  - Reduces number of files read at startup
- https://github.com/atom/atom/pull/3761
  - Caches requires across all installed packages and speeds up require resolution

**Comment by m1ga** [comment]
:+1: me too! The main problem I have at the moment: I start atom (which takes a bit) and then select my old project to open (which takes a while because in linux it opens a second window). After the window is open the speed is fine. Just the "opening" time could be better

**Comment by hyiltiz** [comment]
I hate the fact that I have to wait seconds for my editor to open a file; all I do is editing.

**Comment by batjko** [comment]
How is everyone's impression these days, both compared to a few months ago and to other similar editors?

Personally, I find massive improvements in startup time since, say, version 150 or even 160. It's not quite on the level of Notepad++ (yet), but it's certainly not enough time to get a coffee anymore. I'd say roughly on par with many equivalent full-featured editors.

**Comment by mark-hahn** [comment]
When I started using atom 9 months ago I was getting 6 to 8 second loads.
When the big fix was made it went down to 2 to 3 seconds.  Unfortunately I
have added so many packages it has gone back to 6 or 7 seconds.  I suspect
that I can remove half of the packages.  That might get it back down.

**Comment by ilanbiala** [comment]
I've noticed that it still runs slower than Sublime/N++ or other native editors, and it cannot handle more startup packages like a native editor can..

**Comment by Globegitter** [comment]
Yep same here - really like Atom Text editor, but the only thing so far noticeably worse compared to Sublime is performance. Especially startup time, having roughly the same amount of plugins. Hope there is still some room for improvements.

**Comment by charleswhchan** [comment]
On my PC:
- Notepad++ starts up <1s
- Atom v0.181.0 starts up ~3-5s (clean install)

Noticeably improvement! Keep up the good work.

**Comment by asantos3** [comment]
I just noticed this, hopefully someone can enlighten me or tell me if they have or not the same problem.

I'm running Ubuntu 14.04. I start the PC and then start atom, it takes about ~12s to startup but then if I close it and start it again it takes about ~3s. I also have windows and it behaves the same.

Is this normal or what? I don't see any process running after I close atom so I doubt it's do to being in memory.

If anyone needs I have screenshots of timecop.

**Comment by 50Wliu** [comment]
I believe it's because Atom has to load everything from fresh the first time.  Every startup after that, some of those things are cached and therefore it takes much less time to load.

**Comment by batjko** [comment]
Yes, this has been observed on Windows ever since Window support came out. I wasn't aware it affects Linux as well, but there you go.

Having said that, since Windows got the squirrel updater, people don't normally have to re-install from scratch, so this issue should affect most Windows users only once.

Time Linux to get an updater as well.

**Comment by m1ga** [comment]
@asantos3 have a look at iotop: 
https://github.com/atom/atom/issues/5566
I have 4 apps running the first time

**Comment by asantos3** [comment]
@m1ga just tested it, doesn't happen with me. Have you tried other distros?

**Comment by m1ga** [comment]
@asantos3 no sorry. It only happens at the first start in a KDE session. So if it was open before it won't show up again. But it might get fixed with asar. So I'll wait

**Comment by asantos3** [comment]
Just cleared up my buffer cache and the startup took about the same time as the first run. As @m1ga said, hopefully this is fixed with asar. Keep up the good work :+1:

**Comment by jeffmcneill** [comment]
I use multiple Atom editors with multiple tabs in each window instance. I launch these from scripts. I'm on OSX 10.10 Macbook Air 2011 with 4gb RAM. It takes about 4 seconds to launch each window (after the first instance each window launches an Atom Helper process with about 100mb ram). 

Is there any way I can get that 4 second launch time down to 1-2 seconds?

**Comment by 50Wliu** [comment]
There will be some speed improvements arriving in 0.193.0.  You can also try starting Atom with the `--one` argument if you don't have any packages that rely on deprecated APIs.  For most people that speeds up loading time by 200-500ms.

**Comment by jeffmcneill** [comment]
@50Wliu Thanks I do see some improvement with the -1 and on 0.194.0. Still some more speed would be nice, but there is progress here.

**Comment by benogle** [comment]
@jeffmcneill is `atom --safe` any faster? You may have packages slowing things down. Looking at timecop (`cmd-shift-p`, search for timecop) will show you which ones are the biggest offenders.

**Comment by yongkangchen** [comment]
I suggest that atom should have package load level instead of load all package at start time.
For example:
- tabs、status-bar、tree-view are the level 1, which load and active on start.
- other packages are level 2, which should delay load and active when atom started.

see #4293

**Comment by mark-hahn** [comment]
> instead of load all package at start time

What if a level 2 package modifies the appearance of a level 1?  Then you
would see a "pop".

**Comment by jeffmcneill** [comment]
I've disabled several core packages, including markdown preview, and things have sped up. See attached for my Timecop on one of the instances (with 5 tabs, about 14,000  words that the wordcount needed to count.

![screen shot 2015-04-29 at 1 10 01 pm](https://cloud.githubusercontent.com/assets/3119827/7385475/24e79126-ee71-11e4-977f-084300b9d1a6.png)

It's not instantaneous but definitely better. I use atom to write books with (previously used Multimarkdown and others). Each chapter is a markdown+latex file. With notes and other items, about 30 text files are in a directory (only about 7 might load into tabs).

**Comment by yongkangchen** [comment]
Just for a example. Package should can define the level in package.json, so
package which modifies the appearance should be defined level 1.

2015-04-29 14:13 GMT+08:00 mark-hahn <notifications@github.com>:

**Comment by ypresto** [comment]
I created PR for improvement here!
https://github.com/atom/deprecation-cop/pull/54

**Comment by Penagwin** [comment]
Do plugins load asynchronously? Can they even load asynchronously? Would that help load times at all?

**Comment by jpxd** [comment]
Async package loading would be really great!
On some packages I try to cheat at the activation time by adding a timeout and executing the activation code 5 seconds later to shorten the time until I see the editor window. I would love If one could specify when the package has to be loaded and activated in the `package.json` in cases `activationCommands ` are not an option.

E.g.
sync loading before editor is shown *or*
async loading in the background after the editor is ready and already shown to the user.

**Comment by joselightware** [comment]
As a quick fix atom editor should have a background service like chrome does, this a simple solution that should work even with lots of packages. Service mode could have an enable/disable option for people who might be short on RAM, but now days a small service running in the background shouldn't be an issue for any hardware. This doesn't mean startup improvement efforts should be halted, nevertheless atom as a service should be a option no matter the startup time. 

I think atom is awesome, and js (and friends) as the GUI is a perfect choice, with all the promised "hackability" and beauty only achievable by a cornucopia of options, but IMO most user, including me will be drawback by the current startup speed ~4s.

A text editor, no matter how many cool things it has, will fail as a text editor if startup time is >1s simply because the experience is not acceptable compared to other native apps, this fact won't pass unnoticed to most people, but once again its just my constructive opinion.

**Comment by benogle** [comment]
> IMO most user, including me will be drawback by the current startup speed ~4s.

Note that there are a few huge speedups coming up in the next couple versions of atom:

* Huge speedup from a native compile cache https://github.com/atom/atom/pull/9318 (in master)
* Unfold all :racehorse: https://github.com/atom/atom/pull/9468 (in master)
* Lazy snippet loading https://github.com/atom/snippets/pull/182 (soon to be in master)

Startup speed is @as-cii's full time focus right now. He is finding things and improving things weekly, so keep an eye out for new stuff!

**Comment by joselightware** [comment]
Great!, looking forward to it, nice work.

**Comment by timofonic** [comment]
Is this a step forward to having a more native-like performance? Great!

**Comment by tomByrer** [comment]
When measuring speed, might want to factor in Chrome's [garbage collection services](http://blog.chromium.org/2015/12/smarter-garbage-collection-for-smoother.html).

**Comment by ilanbiala** [comment]
@benogle any update on this?

**Comment by passeride** [comment]
Suggestion: i have disabled some packages for faster startup, now if i could toggle them from the Shift+Ctrl P menu, that would be a great addition for me (But not as default tho), also would it be possible for a deamon to keep it running in background?

**Comment by Tzrlk** [comment]
Any thoughts on incorporating something like https://github.com/atom/atom/issues/4293 to get the editor displaying faster up-front? Or adding an option on the plugins to delay their startup?

Additionally, have you thought about using something like http://rollupjs.org/ for tree-shaking? Certainly running a tree-shake, minify and bundle as a runtime cache per combination of plugins should get subsequent load times up a bit?

**Comment by 50Wliu** [comment]
We are actively working on this in #13949, #13940, #13916, and other PRs.
