### ISSUE TITLE
Update text editor to use the Shadow DOM

### ISSUE THREAD

**Issue by benogle** [atom/atom#3677]
Via @nathansobo 

Status: Will be enabled by default in 0.166.0.

**Comment by QuantumInformation** [comment]
@nathansobo  So do you find that using native js, is better overall than the "supposed" productivity gains that react gives developers?

**Comment by nathansobo** [comment]
@QuantumInformation I wouldn't say better overall. I'd say more appropriate for our use case in the editor.

**Comment by rolfen** [comment]
Thank you for the reasonable responses.

**Comment by DemiMarie** [comment]
Did this cause a performance regression?
