### ISSUE TITLE
Custom elements for built-in components

### ISSUE THREAD

**Issue by benogle** [atom/atom#3679]
Status: Initial planning / brainstorming

Via @nathansobo 

We have `SelectListView` and `ScrollView` that still require SpacePen interactions. We should replace them with custom elements. `TextEditorElement` and the `<atom-text-editor>` tag will already be available after #56 is completed.

`ScrollView` _may_ be able to be implemented purely as a class you apply to an element that hooks it up to global commands that can adjust the scroll position, plus some default styles.

**Comment by lee-dohm** [comment]
We've gone as far as we want with custom elements. They work for some things but they're not ideal in all cases since they're a global namespace and can't be redefined.

**Comment by nathansobo** [comment]
👍
