### ISSUE TITLE
Preview pane items / Smart Tabs

### ISSUE THREAD

**Issue by benogle** [atom/atom#3683]
Support sublime-like preview mode when opening files from the tree view, fuzzy finder, find and replace, etc.

The main issue being tracked is here: https://github.com/atom/tree-view/issues/3

**Comment by tknerr** [comment]
oh yes please! :+1:

**Comment by brendanfalkowski** [comment]
This will be super useful warding off the tab-pocalypse. Hope it goes back "on deck" soon.

**Comment by Zireael07** [comment]
Agreed, it'd be very useful.

**Comment by Stanzilla** [comment]
is this still on track for 1.0?

**Comment by mehcode** [comment]
@Stanzilla So says the `1.0-roadmap` tag.

**Comment by 50Wliu** [comment]
Fixed by atom/tabs#3.
