### ISSUE TITLE
Selection order changes copy paste order. 

### ISSUE THREAD

**Issue by chick-chains** [atom/atom#3692]
If I select multiple lines one at a time using the cursor, when I copy paste those lines they show in the order they were clicked.
So when i choose the following lines one at a time from bottom to top:
1
2
3
When I paste the it shows:
3
2
1

**Comment by izuzak** [comment]
I just tried reproducing this and wasn't able to:

![order](https://cloud.githubusercontent.com/assets/38924/9184586/75969662-3fb6-11e5-9075-ec5fe66d024a.gif)

Can anyone still reproduce this?

**Comment by mnquintana** [comment]
I can't reproduce this with Atom 1.0.6-24e3ab4

**Comment by izuzak** [comment]
Thanks for checking, @mnquintana -- closing this out then. If anyone can still reproduce -- let us know.
