### ISSUE TITLE
A package not auto-loaded by atom cannot register serializers

### ISSUE THREAD

**Issue by anandthakker** [atom/atom#3695]
Suppose I have a package that's only activated in response to the `my-package:start` command, and in response to that command, it adds an instance of `MyPackageView` as a new item in the current `Pane`.  

If I want that view to be serialized when the editor closes, it seems like I'd just register deserialization like this:

``` coffeescript
class MyPackageView
  atom.deserializers.add(this)

  constructor: (@data) -> #property assigned
  serialize: -> { deserializer: 'MyPackageView', data: @data } 
  @deserialize: ({data}) -> new MyPackageView(data)
```

(from [serialization docs](https://atom.io/docs/latest/advanced/serialization), see also [DeserializeManager](https://github.com/atom/atom/blob/v0.133.0/src/deserializer-manager.coffee#L24))

But the problem with this is that, if we add this view and then close/reopen Atom, it can't find `MyPackageView` when trying to deserialize this pane item.

It seems that instead of loading the package but then waiting until activation event to call `activate()`, the package isn't even being _loaded_ until the activation event fires.  I'm not sure whether this is the intended behavior or not, but based on the comments about deferring `require`s in #2654 and also in [How To Speed Up Your Packages](https://discuss.atom.io/t/how-to-speed-up-your-packages/10903), it appears to be a change, one consequence of this is that deferring `require` until `activate()` makes no difference to application load time.  (Although, deferring it until some point even later than that could still speed up _package_ activation time.)

If this is actually the intended behavior of the package loading system, then one approach would be to register your package (or have it automatically inferred) when doing `deseralizers.add()`, so that the package could be stored as deserializer metadata, and then loaded during deserialization if necessary.

**Comment by jessegrosjean** [comment]
I think maybe related is the fact that serialization happens before packages are activated. In Atom.startEditorWindow the sequence is:

```
      this.deserializeEditorWindow();
      this.watchProjectPath();
      this.packages.activate();
 ```

This creates some problems. Since for example I register my viewProviders when my package activates. So as things currently stand deserialization fails for my view since it's not yet registered when deserialization takes place.

**Comment by lee-dohm** [comment]
You can [register deserializers in the `package.json` now.](https://github.com/atom/settings-view/blob/5e5c6219f5993dba8fd617379a23b1910a06df22/package.json#L37-L39)
