### ISSUE TITLE
Yosemite Beta 4 bug with formatting

### ISSUE THREAD

**Issue by cyberwombat** [atom/atom#3700]
I am experiencing an issue with the JSFormat package which adds a line break after each word/symbol. This happened right after the Yosemite Beta 4 upgrade. Upgrading the package/atom, reinstalling, etc had no effect. The author of the JSFormat as well as myself think it has something to do with Yosemite itself which may affect Atom as a whole so I am posting it here. Please refer to this issue for the original post: https://github.com/jdc0589/jsformat-atom/issues/31#issuecomment-57574982

**Comment by izuzak** [comment]
Based on the discussion in https://github.com/jdc0589/jsformat-atom/issues/31, this doesn't sound like an issue in Atom. Also, I tried installing JSFormat on Yosemite and couldn't reproduce the issue.
