### ISSUE TITLE
Support GitHub Releases changelog in package settings

### ISSUE THREAD

**Issue by YurySolovyov** [atom/atom#3705]
Originated from https://github.com/sindresorhus/atom-fixmyjs/issues/3

> Not sure if Atom supports that, but would be a bit ironic if it doesn't.

**Comment by zenopopovici** [comment]
This is really a big issue. 
Every time a package updates you don't know what improvements or changes are being made. 

Maybe display the changelog button in addition to "Update" button if a new update is detected. A more elaborate solution would be to display a new window with the concatenated change logs every time packages are updated.

**Comment by mnquintana** [comment]
@zenopopovici I think what you're referring to is more in line with https://github.com/atom/settings-view/issues/282 than this issue - this is just for supporting GitHub Releases as a "changelog". Atom already supports changelogs as files in the repo, though.

**Comment by zenopopovici** [comment]
Yeah, you're right, thanks. I'll comment over there. I know about changelog files, they should be more accesibile when updating. Clicking trough every is getting tiresome really fast.

**Comment by iamstarkov** [comment]
> This is really a big issue.
> Every time a package updates you don't know what improvements or changes are being made. 

so much true, subscribed to https://github.com/atom/settings-view/issues/282

---

> @zenopopovici I think what you're referring to is more in line with atom/settings-view#282 than this issue - this is just for supporting GitHub Releases as a "changelog". Atom already supports changelogs as files in the repo, though.

Thinking that this is issue can be closed, as far as original title is already implemented in Atom itself, and view changes while updating is another issue in another project

**Comment by YuriSolovyov** [comment]
I think this is a step in right direction, though, not everyone are using GitHub Releases for changelogs.
I think we should encourage people using Releases by pointing this out on publishing packages guidelines or something.

**Comment by lee-dohm** [comment]
@YuriSolovyov, we should encourage people who are using Releases to use `CHANGELOG.md`? Or do you mean something different?

**Comment by YuriSolovyov** [comment]
@lee-dohm I mean we should encourage GitHub Releases for both new packages and existing packages that are using `{changelog,history}.md`.

**Comment by lee-dohm** [comment]
What are the benefits of GitHub Releases over `CHANGELOG`? What are the drawbacks? I'm not going to want to switch if it is just people's personal preference given that I have multiple packages that I would have to convert.

**Comment by mnquintana** [comment]
@lee-dohm Here's what I'm thinking right now for benefits / drawbacks:

### Benefits
- Changes are associated with a git tag, which would make it much easier to do things with per-version changelogs (granted, you could diff changes in `CHANGELOG.md` from tag to tag to get something similar, but that's a lot of extra work)
- GitHub Releases has an API

### Drawbacks
- We would need standardized tooling for creating a GitHub Release when `apm publish`ing a new version
- `CHANGELOG.md` and similar files are version-controlled, meaning that you don't have to worry about entering all your changes at once or accidentally losing some if you add them piecemeal before a release

Refs https://github.com/atom/atom.io/issues/13

**Comment by iamstarkov** [comment]
Why wouldnt we be able to extract latest changelog info from both sources from `{CHANGELOG,HISTORY,WHATEVERGITLOG}.md` and github releases. This way will not force contributors to change their habits

**Comment by lee-dohm** [comment]
I think supporting all the options, while more work, is probably the best approach.

**Comment by iamstarkov** [comment]
the same

**Comment by iamstarkov** [comment]
if `amp publish` will offer tool to make proper changelog and publish it some way which will be easy to use in `update card` then it can first version
