### ISSUE TITLE
Config gets stuck to default if config.cson has a syntax error

### ISSUE THREAD

**Issue by jbt** [atom/atom#3715]
I somehow managed to get a syntax error in my config.cson (completely unable to reproduce what caused it now), which caused Atom to fail to parse it, and instead just used defaults.

Thinking I'd managed to delete some config somewhere went and set stuff back to how it was, but nothing was persisted and everything was reset on next restart. I'm guessing this is Atom refusing to overwrite the existing file, though I couldn't see any errors to that effect in the dev tools.

The behaviour of not completely clobbering an invalid config is good but maybe there could be a warning in the UI and/or the invalid config.cson be copied somewhere else so that subsequent changes can be persisted properly.

**Comment by 50Wliu** [comment]
Notifications should have solved this.
