### ISSUE TITLE
Use package.json engine field to prevent package update or installation

### ISSUE THREAD

**Issue by abe33** [atom/atom#3741]
This feature spans several package/repo (apm, settings-view, atom), so I'll put it there as reference. 
### Use Case

I created a package on Atom version X and relied on some API that was broken on version Y. If I fix the package to use the new API, people that still use version X will be notified of the update and will end up with errors due to the new API not being available in their current version. 
One solution packages-side would be to detect which API is available and switch between implementation. But as you can guess, this is far from ideal as it puts a lots of constraints in maintaining such a package.
### A Simple Solution

Atom is already assuming that every package must define an `engine` field with an Atom semver string as value. A simple solution would be to test this version against the current Atom version. 
This test could be done at several moments: 
- When loading a package in Atom, for instance, a package sets its engine version to `<= 0.123`, if Atom version is `0.124` the package is not loaded and reported as an incompatible package.
- When installing a package with `apm install <package>`. If the package engine version doesn't match the current Atom version, the install is cancelled and reported to the user with the adhoc message (package X expects version Y of Atom).
- When searching/installing/updating a package from the settings view, the package block could display mention of the expected engine version, and the install/update button should be disabled if the versions doesn't match.

That way, people with legacy versions of Atom won't see errors poping up due to a package update relying on new API not available in their version while, at the same time, providing them with information about the incompatibility

**Comment by park9140** [comment]
This would be super useful, had many issues on the repose for both `linter` and a `autocomplet-plus` while rolling to 1.0 apis that could have been passively resolved if the user knew to update their version of atom when installing the new version of both packages.
