### ISSUE TITLE
API for creating views in packages

### ISSUE THREAD

**Issue by benogle** [atom/atom#3752]
If we plan to deprecate the space pen `View` class, we need a story for what folks can move to. Some kind of system that interoperates with custom elements. Something that UI heavy packages like settings view and fnr can use. 

* Maybe it looks like space pen (space-pencil)?
* Maybe it's react?

We need to do more thinking.

**Comment by thedaniel** [comment]
I opened #5756 with a high-level overview of where we're at today and started a list of options. I'm closing this issue in favor of that one, in the interest of starting fresh with the current thinking & requirements.
