### ISSUE TITLE
Popover-list styleclass not working

### ISSUE THREAD

**Issue by lhk** [atom/atom#3755]
I'm trying to display a SelectListView inline, next to the cursor. The correct styleclass seems to be popover-list. Unfortunately it doesn't work.
The View does not display at all - it becomes invisible.
Using overlay and from-top the List is displayed - but at the top. I would like to inline it.

I'm rather sure that this is not a problem with my code. The View does display, just not with the styleclasses I need.

Here are detailed descriptions:
https://discuss.atom.io/t/how-to-position-selectlistview-inline/12500
http://stackoverflow.com/questions/26236205/atom-editor-display-selectlistview-inline

**Comment by 50Wliu** [comment]
@lhk is this still an issue in Atom 1.3.x?

**Comment by lee-dohm** [comment]
Since this has gone so long without a response, I'm going to assume that this isn't an issue anymore. If that isn't the case, please let us know :grinning:
