### ISSUE TITLE
Error: Cannot find module 'cookie-jar'

### ISSUE THREAD

**Issue by Vgandhi9** [atom/atom#3759]
I have a system running on ubuntu 12.04 64 bit.  I have cloned the repository then i ran the few commands given in this link https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md but when i run script/build  I get the following output (i ran this command previously also and at the end i got the same error that it can't find the module named 'cookie--jar')

![selection_005](https://cloud.githubusercontent.com/assets/5131088/4564929/a3543f82-4f1b-11e4-9d7a-466ff87965fa.png)

P.S. :- thanks in advance.

**Comment by kevinsawicki** [comment]
This looks like a build module was not installed properly causing it to be missing when the build was run.

Running `script/clean` and then rebuilding should fix this.
