### ISSUE TITLE
Window title cut off when using Classic Theme

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#3767]
My laptop reverted to the classic (non-Aero) theme today due to some stuff I was doing.  Chrome transitioned successfully, but Atom didn't.

![image](https://cloud.githubusercontent.com/assets/2766036/4569304/867b153a-4f47-11e4-9128-c57a5372a399.png)
You can see that the title bar is slightly cut off.
Version 0.136.0, Windows 7 x64.

*Wasn't sure if this should belong on the Atom repo or atom-shell.  I decided to put it here because the issue about windows not maximizing by default/being larger than the screen was also reported here.

**Comment by damieng** [comment]
A lot of apps fail if you change theme without starting them or stop hardware acceleration. It's an unusual scenario that is gnarly to fix and easily worked around (restart app).  Going to suggest won't fix.
