### ISSUE TITLE
update all package with the wrong message "Compiler tools not found"

### ISSUE THREAD

**Issue by netmou** [atom/atom#3770]
![qq 20141009130545](https://cloud.githubusercontent.com/assets/7068058/4571231/f8fef1a6-4f71-11e4-819d-e2757abc540d.png)
env: win7 v0.136

**Comment by filipesilva** [comment]
I'm having this problem with 0.180.0 on windows as well, with packages that previously updated with no problem. In my specific case, I did updated Atom from 0.176.0 to 0.180 (interim versions had the 'path too long' error) and then updated all packages. 

Updating all showed this error on a couple of them, but apparently updating one by one worked. So I guess it's a concurrency issue.

**Comment by TyrrellStephen** [comment]
@netmou, seeing as this issue has yet to be closed I thought that I would add that it was my understanding that only Python 2.7.x (e.g. v2.7.8) was supported. Python 3.x is quite a different beast.

**Comment by harshana5** [comment]
Hello,

I'm having the same issue with 0.194.0

Got
python 2.7.5
node js v0.12.2
Visual studio 2013
win 7.1 SDK

**Comment by payaxy** [comment]
hello 

same issue here.
Atom 0.190.0 07/04/2015 23:14:19
Installed programs:
Visual Studio Community 2014 with Update 4
Python 2.7.8
Node.js 0.12.2
Microsoft .NET framework 4.5.1 SDK

**Comment by Anthropic** [comment]
same issue, installed all packages from the link provided in the message.
Atom 0.207.0 10/06/2015
Installed programs:
Visual Studio 2010 + 2012
Python 2.7.2
Node.js 0.12.2

It's a pity it can't tell you specifically what is missing, could be something not on the PATH for example but I can't find out what without code diving.

**Comment by Monte-Christo** [comment]
Same problem here.

I have VS 2013 Pro, Python 2.7.9 x86, Node.js 0.12.5 x64
on a 64-bit Win 8.1 Pro PC.

Error message:
Installing “language-fsharp@0.8.4” failed.Hide output…
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp WARN install got an error, rolling back install
gyp
Compiler tools not found

**Comment by aureliojargas** [comment]
https://github.com/atom/apm/issues/322#issuecomment-96430856 solved this issue for me

**Comment by YogurtBee** [comment]
I encountered the same problem when I was trying to install the packages today. I wonder if you have solved the problem?

**Comment by filipesilva** [comment]
@YogurtBee for me all I had to do was install packages one by one.

**Comment by DaveyD** [comment]
Hi, I'm new to Atom
I tried installing some packages, but every package I try I am getting this error "Compiler tools not found"

1. I am behind a proxy
2. Proxy is set correctly - I am able to browse packages from within Atom
3. I am running Windows 10 Pro 64bit
4. I have both Python and VS2015 installed
5. Tried both from within Atom and from the command line - nothing is working

@filipesilva I am trying to install one package at a time and I'm getting errors!

**Comment by damieng** [comment]
It is necessary when installing VS201x to ensure the C++ tools are included. Alternatively you can install the C++ Build Tools instead of VS at http://landinghub.visualstudio.com/visual-cpp-build-tools   (2017 isn't supported in any way by the nodegyp build system at this time)
