### ISSUE TITLE
Proxy settings not fully respected in windows

### ISSUE THREAD

**Issue by kryptonianson** [atom/atom#3786]
I am on windows 8.1 update 1 using Atom 0.136.0

I have added the following to .atom/.apmrc (for testing purposes I also tried putting it in the global config .apmrc file as well):
https-proxy=http://myproxy:8080
http-proxy=http://myproxy:8080
strict-ssl=false

No spaces exist in this configuration. All items are configured very specifically to instructions. I even tried using the ip address of the proxy to eliminate the possibility of a dns issue as suggested. Everything works fine unless it is calling npm. That is when the git connection fails.

Once those are added, the settings view can see all the packages available, search etc. (without this I get a connection error). However when calling git on package install it fails to connect. I can call git from the command line and from other applications without issue since the global git proxy configuration is set. I also run this on a Mac (same network proxy etc) and it works fine. Any help would be much appreciated. The following is the error I receive when trying to install a package:

npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/temp/0.5.0
npm http GET https://registry.npmjs.org/fs-plus
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/delegato
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/temp/0.5.0
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/delegato
npm http 304 https://registry.npmjs.org/event-kit
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/rimraf
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) 
npm http 304 https://registry.npmjs.org/property-accessors
npm ERR! git clone https://github.com/Benvie/harmony-collections.git Cloning into bare repository 'C:\Users\NAME.atom.node-gyp.atom.apm_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100'...
npm ERR! git clone https://github.com/Benvie/harmony-collections.git fatal: unable to access 'https://github.com/Benvie/harmony-collections.git/': Failed connect to github.com:443; No error
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\NAME.atom.node-gyp.atom.apm_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100'...
npm ERR! fatal: unable to access 'https://github.com/Benvie/harmony-collections.git/': Failed connect to github.com:443; No error
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "e:\utils\Atom\resources\app\apm\node_modules\atom-package-manager\bin\\node.exe" "e:\utils\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\bin\npm-cli.js" "--globalconfig" "e:\utils\Atom\resources\app\apm\node_modules\atom-package-manager\.apmrc" "--userconfig" "C:\Users\NAME\.atom\.apmrc" "install" "C:\Users\NAME\.atom\.node-gyp\.atom\.apm\minimap\3.3.1\package.tgz" "--target=0.17.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\NAME\AppData\Local\Temp\apm-install-dir-114910-5044-flzuiu
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm

**Comment by damieng** [comment]
Atom now sets the environment variables for APM when shelling out by interrogating Chrome directly. This should alleviate many common scenarios for proxy users.  Please open a new issue if you experience any additional problems with it.
