### ISSUE TITLE
Investigate GPU rasterization

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#3787]
I've been following the Chromium graphics discussion list and they've been talking about GPU accelerated rasterization. Curious if this is something we can enable in Atom (if it isn't already) and what the benefits would be.

http://www.chromium.org/developers/design-documents/chromium-graphics/how-to-get-gpu-rasterization

/cc @zcbenz

**Comment by MayhemYDG** [comment]
You can enable this on the desktop too in Canary via chrome://flags/#enable-gpu-rasterization
I think this is worth another investigation.

**Comment by nathansobo** [comment]
@MayhemYDG I just checked it out in Chrome 40 and at least on OS X it's not available:
![screenshot 2015-01-25 07 08 42](https://cloud.githubusercontent.com/assets/1789/5891685/0b348e82-a461-11e4-8dad-ec8931d8d6bd.png)

**Comment by MayhemYDG** [comment]
That's why I specifically mentioned "in Canary".

**Comment by nathansobo** [comment]
@MayhemYDG Oh sorry I missed that!

**Comment by MayhemYDG** [comment]
So now that Atom is on Chrome 41, can we access flags somehow to enable gpu rasterization?

**Comment by postcasio** [comment]
You can start atom with `atom --force-gpu-rasterization` to enable it.

**Comment by YuriSolovyov** [comment]
not sure if that placebo effect, but it seems to work smoother, probably need to profile to be sure.

**Comment by kevinsawicki** [comment]
@nathansobo is this still something to investigate or can this be closed?

**Comment by nathansobo** [comment]
@zcbenz Is this enabled by default now? It's unclear to me whether options that are enabled by default in Chrome need to be explicitly enabled in Electron.

**Comment by simurai** [comment]
Followed the steps [here](https://www.chromium.org/developers/design-documents/chromium-graphics/how-to-get-gpu-rasterization).

![screen shot 2015-07-29 at 11 47 40 am](https://cloud.githubusercontent.com/assets/378023/8948948/0c773b82-35e8-11e5-8da9-a29dcfc0d722.png)

So in my case it's "off (device) - not supported on the device". I'm on a MBP (Retina, 13-inch, Late 2012)

**Comment by nathansobo** [comment]
As soon as @zcbenz can confirm that there's nothing more to do to enable GPU rasterization when it's supported on the underlying platform, I'm happy to close this. Until then, I personally would like to keep it open as a reminder.

**Comment by timofonic** [comment]
Any news about this? :)

**Comment by paulcbetts** [comment]
You can check this with the following code:

```
bw = require('remote').require('browser-window')
b = new bw({width:500, height: 500})
b.loadUrl('chrome://gpu')
```

Whether it's on or not depends on all kinds of factors - we actually explicitly force GPU rasterization in the Slack app

**Comment by limoragni** [comment]
If you are lazy like me you can go to the console and use `window.location.href = "chrome://gpu/"` to load the GPU info screen. I have a Macbook Pro mid 2015 and have it disabled. Any ideas why? Is there any downsides on explicitly forcing GPU rasterization?  Would I benefit from this when using video and svg?

**Comment by YurySolovyov** [comment]
@limoragni it should print reasons of disabling features a little below (shot from Chrome, not Atom)
![image](https://cloud.githubusercontent.com/assets/2168518/16303190/2525ce90-3958-11e6-947e-c1b6dad457b4.png)

**Comment by limoragni** [comment]
@YurySolovyov The reason is the same than you screenshot. It says that its disabled by command line or about:flags. Isn't supposed to be enabled by default?

**Comment by YurySolovyov** [comment]
@limoragni maybe file a bug to chrome then?
