### ISSUE TITLE
atom default editor vs samba share bug

### ISSUE THREAD

**Issue by acmmcc** [atom/atom#3788]
I've set Atom up as the default editor on Windows7. If I don't have Atom running, and double click a file on a samba share to open it, the editor will open, then immediately crash. I can double click local files and open them without any problems. If I open Atom up, and then open the files on the samba share via Ctrl-O, they open as expected and do not crash.

**Comment by damieng** [comment]
No longer able to reproduce this on latest builds with either a mapped SMB drive (x:) or direct using the share name (\\wdmycloudex4\public\test.txt)  Assuming fix. Please comment if this is still an issue for you in recent Atom builds.
