### ISSUE TITLE
Investigate Atom + DisplayFusion

### ISSUE THREAD

**Issue by Signus** [atom/atom#3791]
Atom persistently causes crashes in DisplayFusion when using Atom on a second monitor.

Reproducible, but not consistently nor by hand. Noticed generally after two instances:

1) The Atom window is moved between screens.
2) Atom is restarted after installing a new plugin.

Issue is persistent on two Windows 7x64 machines with DisplayFusion installed.

**Comment by izuzak** [comment]
@Signus Are you still seeing this problem with Atom 1.0.11?

**Comment by Signus** [comment]
At this point I haven't noticed this problem since v0.195.0. I will close this issue.
