### ISSUE TITLE
All package install failed like this,please help me to solve the problem.

### ISSUE THREAD

**Issue by JinLingChristopher** [atom/atom#3801]
Microsoft Windows [版本 6.3.9600]
(c) 2013 Microsoft Corporation。保留所有权利。

C:\Users\Christopher>apm install autocomplete-clang
Installing autocomplete-clang to C:\Users\Christopher.atom\packages
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.32 | win32 | ia32
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/node-v0.17.0.tar.gz
gyp WARN install got an error, rolling back install
gyp

C:\Users\Christopher>apm install minimap
Installing minimap to C:\Users\Christopher.atom\packages
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.32 | win32 | ia32
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/node-v0.17.0.tar.gz
gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/node-v0.17.0.tar.gz
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/x64/node.lib
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/node.lib
gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/node.lib
gyp WARN install got an error, rolling back install
gyp

C:\Users\Christopher>apm install web-browser
Installing web-browser to C:\Users\Christopher.atom\packages
gyp info it worked if it ends with ok
gyp info using node-gyp@0.12.2
gyp info using node@0.10.32 | win32 | ia32
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/node-v0.17.0.tar.gz
gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/node-v0.17.0.tar.gz
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/x64/node.lib
gyp http GET https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/node.lib
gyp http 200 https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.17.0/x64/node.lib
gyp WARN install got an error, rolling back install
gyp

is there anyone else meet this problem too?

**Comment by Bantes** [comment]
I have met the same problem as you.what the fuck GFW!
