### ISSUE TITLE
Cannot read property 'getDOMNode' of undefined [...]/app/src/text-editor-component.js

### ISSUE THREAD

**Issue by thomaslindstrom** [atom/atom#3811]
`Uncaught TypeError: Cannot read property 'getDOMNode' of undefined /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1486`

Copying something off a file using `CMD-c` (with another file open), not letting go of `CMD` before pressing `CMD-w`, fires this error.

http://cl.ly/363E3c3d1o2F

I'm on Mac OS X, `10.9.5`, using Atom `0.136.0`.

**Comment by benogle** [comment]
Closing as it is likely fixed. If you can still reproduce, please reopen.
