### ISSUE TITLE
editor:delete-to-beginning-of-word at start of line should just remove up to the linebreak

### ISSUE THREAD

**Issue by SmileyChris** [atom/atom#3816]
When pressing `ctrl+backspace` to delete a word, it shouldn't delete any characters on the previous line.

![bleh](https://cloud.githubusercontent.com/assets/109951/4621544/d24d8c52-532c-11e4-979c-89cf304dc045.gif)

![bleh2](https://cloud.githubusercontent.com/assets/109951/4621570/4b5d9a4c-532d-11e4-8036-c09097fff4b2.gif)

**Comment by carragom** [comment]
Hello guys, this issue is still around. Using Debian 8 and Atom 0.198.0. If the file uses DOS line endings everything works as it should. But with UNIX line endings the problem is visible. I could beta test if anyone comes up with a fix.

**Comment by charlesswartz** [comment]
Hello everyone, as of version 0.211.0 the behavior described in the OP's original post (Ctrl+Backspace at the beginning of the line deletes words on the previous line) still exists on Ubuntu 14.04.2 but does not exist on Windows 7. Any ideas on workaround?

**Comment by charlesswartz** [comment]
Further confirming my previous comment, if I use the line-ending-selector package to switch to CRLF then using Ctrl-Backspace at the beginning of a line works as expected and does not delete words on the previous line. Any ideas on a fix? It's driving me crazy.

**Comment by ice-blaze** [comment]
Thanks zyklus! I use Ubuntu 14.04 with unity, this is how I changed the keybindings: 
```
'.workspace .editor':
  'ctrl-delete'     : 'editor:delete-to-next-word-boundary'
  'ctrl-backspace'  : 'editor:delete-to-previous-word-boundary'
  'ctrl-left'       : 'editor:move-to-previous-word-boundary'
  'ctrl-right'      : 'editor:move-to-next-word-boundary'
  'ctrl-shift-left' : 'editor:select-to-previous-word-boundary'
  'ctrl-shift-right': 'editor:select-to-next-word-boundary'
```

**Comment by martinruenz** [comment]
Apparently still not fixed?
System: Ubuntu 16.04.1 LTS
Line ending: LF
Atom: 1.11.2
Community Packages (11):
├── autocomplete-cmake@0.3.1
├── editorconfig@1.5.3
├── es6-javascript@1.0.0
├── javascript-snippets@1.2.1
├── language-babel@2.45.0
├── language-cmake@0.2.0
├── language-diff@0.6.0
├── language-latex@1.0.0
├── linter@1.11.18
├── linter-eslint@8.0.0
└── minimap@4.25.5
As cswartzvi already said, it is really frustrating!

**Comment by marcbachmann** [comment]
I just tried to switch to atom about the 10th time and ran into that issue.
I'm using OSX 10.12.5 and Atom 1.19.5.
