### ISSUE TITLE
Ligatures aren't spaced correctly

### ISSUE THREAD

**Issue by YawarRaza7349** [atom/atom#3821]
I'm using the Atom for Windows Alpha from the Atom website (not Chocolatey), version 0.136.0 (as viewed in the Help menu and with `--version` in the command line, the `version` file in the Atom folder says v0.17.1; it was downloaded around 12:30AM US Eastern on October 14, 2014 if that helps) on Windows 8.1. I set `text-rendering: optimizeLegibility;` for `.editor` in `styles.less` (because otherwise the ligatures aren't in effect and I get each individual character). This happens regardless of whether hardware acceleration is enabled. It also happens in `--safe` mode, and the developer tools console shows no errors.

![temp](https://cloud.githubusercontent.com/assets/4254261/4624455/bad18f5a-5364-11e4-9a0f-8c59596bcd59.png)
```
(<*>)::Functor f=>(a->b)->(f a->f b)
fmap::Functor f=>(a->b)->(f a->f b)
```
in [Hasklig](https://github.com/i-tu/Hasklig), which has ligatures for `<*>`, `::`, `=>`, and `->`.

![temp](https://cloud.githubusercontent.com/assets/4254261/4624502/6b794cee-5365-11e4-8d85-a129dee8ae1d.png)
```
fifififififififififi
```
in Calibri, using the ligature for `fi`. The cursor is at the end of the line, and the misspell underline only leads up to that point as well. The ligature for `ff` in Calibri has the opposite effect; the cursor and underline extend farther than text on the screen if you put enough f's on a line.

I can provide more details if you need them.

**Comment by ai** [comment]
```css
body {
    -webkit-font-feature-settings: "liga" 1;
    font-feature-settings: "liga" 1;
    text-rendering: optimizeLegibility;
}
```

makes little bit better, but not enough

**Comment by ai** [comment]
Also same problems are with [Fire Code](https://github.com/tonsky/FiraCode)

**Comment by benogle** [comment]
Try disabling `Use hardware acceleration` in the settings. Does that help?

**Comment by ai** [comment]
@benogle thanks for advice. But it really not help. LIgatures behaviour is totally same without “Use hardware acceleration”.

**Comment by 50Wliu** [comment]
Refs #2880 (possible duplicate).

**Comment by ai** [comment]
@50Wliu nope. #2880 is about disabled rendering ligatures (two symbols instead of one) and this issue is about wrong caret position on font with ligatures.

**Comment by 50Wliu** [comment]
Oh, whoops.

**Comment by killercup** [comment]
Is there any progress on this? A recent update (I guess it was 0.177) made this much worse for me.

Compare the position of colons and semicolons, for example:

![styles_less_-__users_pascal_documents_uni_2014ws-pg-web_episodefever-ausarbeitung_-_atom](https://cloud.githubusercontent.com/assets/20063/6064671/edfbb7b6-ad5f-11e4-913e-ec1ec97ed952.png)

![styles_less_-__users_pascal_documents_uni_2014ws-pg-web_episodefever-ausarbeitung_-_atom](https://cloud.githubusercontent.com/assets/20063/6064683/02cc9584-ad60-11e4-87b6-bebb27097821.png)

**Comment by benogle** [comment]
@killercup what font are you using?

**Comment by killercup** [comment]
That's Hasklig (same as a previous commenter IIRC).

**Comment by aceLren** [comment]
I'm having the same issue and it makes it impossible to use - the cursor shows up far left of where it actually is on the page; I switched to Atom for its support of ligatures (Hasklig).

**Comment by jutaro** [comment]
I would like to use Hasklig with ligatures as well. Unusable on Linux (tried with all kind of options). Please fix!

**Comment by braver** [comment]
optimizeLegibility seems to be giving issues: https://discuss.atom.io/t/wrong-font-rendering/14725.

**Comment by frabert** [comment]
I tried to make a html file with this style in its head
```css
textarea {
    -webkit-font-feature-settings: "liga" 1;
    font-feature-settings: "liga" 1;
    text-rendering: optimizeLegibility;

    font-family: "Hasklig";
}
```
And writing in a textarea within such file with Chrome works perfectly fine, no misplaced carets nor problems deleting characters...

**Comment by postcasio** [comment]
@frabert The problem is caused by Atom using a custom editor control, not a `<textarea>`. It performs its own character measurements to find out where the cursor should be rendered on screen - enabling ligatures throws the measurements off because the character widths can change depending on surrounding characters, which Atom doesn't account for.

**Comment by frabert** [comment]
I see, sorry for the misleading results. Out of curiosity, how does Atom calculate text metrics? Something like a Freetype wrapper?

**Comment by postcasio** [comment]
From my understanding it copies lines into an invisible dummy node, then it iterates over each character. For each character It creates a selection and asks the browser for the width of the selection.

**Comment by frabert** [comment]
So the browser is incorrectly calculating the width of such a selection? Is it because the characters making up the ligatures are stored in different elements, tricking the algorithm?

**Comment by kumarrishav** [comment]
@postcasio @benogle I am unable to reproduce this issue (on Linux). Can you help in reproducing it?

**Comment by jutaro** [comment]
Try to install the Hasklig font and then edit a Haskell file. The problem
sometimes doesn't appear immediately, but for me it never took long before
it gets a mess (The cursor and the point you are editing differ).
Hope very much you can fix it.
Jürgen
Am 17.03.2015 14:48 schrieb "Kumar Rishav" <notifications@github.com>:

**Comment by sudodoki** [comment]
Using FiraCode with addition of 
```
.editor {
  text-rendering: optimizeLegibility;
}
```
in my styles.
Had issue with horizontal spacing & selection boundary box not matching the last letter, but extending beyond that which also affect the correctness of selection functionality.
Here's [recording](https://www.dropbox.com/s/9r0fjc4e8pmen87/atom-ligatures-rendering.mov?dl=0) of the screen - top is sublime, bottom is atom. Will be glad to add any other info regarding my setup and why it's broken.

**Comment by iamstarkov** [comment]
faced same issue =(

**Comment by sqd** [comment]
please fix it. I switched from Sublime to Atom for ligatures supports :-(

**Comment by larsenwork** [comment]
fwiw I'm also having this issue. I've made a font where e.g. `downloadIcon` gets replaced with an actual download icon icon but the cursor position does not update (should be right after the `d`) - let me know if more details is needed :) 

![screen shot 2015-06-06 at 06 32 09](https://cloud.githubusercontent.com/assets/3859425/8018308/d0e949f8-0c15-11e5-8d1a-b7d11b1b5fc6.png)

**Comment by larsenwork** [comment]
Just to clarify: contextual substitution works without problems - so this is only a problem for longer words being shortened in ligatures. The ligatures in Fira Code and Hasklig could be changed to contextual alternates making this a non issue for those fonts but my example above still wouldn't work
![screen shot 2015-06-06 at 07 05 54](https://cloud.githubusercontent.com/assets/3859425/8018403/8298ae92-0c1a-11e5-900f-3212fce42cc8.png)

**Comment by frabert** [comment]
https://github.com/atom/atom/pull/6083 this might solve some issues...

**Comment by Laurian** [comment]
As workaround, I disable the ligatures on the current line, see https://gist.github.com/Laurian/ca3ff713c76cc1bf81a0

**Comment by larsenwork** [comment]
@Laurian neat - although that jumping in line length is a bit annoying:)

**Comment by iamstarkov** [comment]
@Laurian thx, for this fix. but it doesn’t work for me =(

**Comment by iamstarkov** [comment]
oh, you need to install package to enable styling https://atom.io/packages/highlight-line

**Comment by gusaiani** [comment]
Installed Atom 1, character spacing still broken.
Would love to be able to see ligatures working nicely.

**Comment by frabert** [comment]
I'm a bit disappointed too this didn't make it into the final release. It was even on the roadmap! Doh! :(

**Comment by ai** [comment]
My heart bleeds every time I see tweets about Fira Code, because of this issue :'(.

**Comment by Eiyeron** [comment]
@iamstarkov your stylesheet here only works when I'm editing the stylesheet after loading. If I run atom without this style fix and then I add your stylesheet, the cursor position will work. If I run atom with the stylesheet, the cursor will fall back to its erratic placement.

**Comment by Fresheyeball** [comment]
Does anyone know where in the Atom.io code the problem exists? Where char size is being calculated?

**Comment by kubetz** [comment]
@Fresheyeball There is an [ongoing PR reworking char measurement](https://github.com/atom/atom/pull/6083) so I would look there :+1: .

**Comment by richardwooding** [comment]
Would love this to work so I can use http://larsenwork.com/monoid/ ligature support

**Comment by larsenwork** [comment]
@richardwooding everything but the icons should work? If not then please add an issue on https://github.com/larsenwork/monoid/issues

**Comment by larsenwork** [comment]
@as-cii does #7945 also address the ligatures or is it "only" the measurement?

**Comment by richardwooding** [comment]
@larsenwork 

I seem to have everything working with this styles.less

 * {
   -webkit-font-smoothing: antialiased;
   -webkit-font-feature-settings: "liga" on, "calt" on;
 }

 atom-text-editor::shadow {
   .cursor-line {
     -webkit-font-feature-settings: "liga" off, "calt" off;
   }
 }

.tree-view {

}

atom-text-editor {
  font-family: 'monoid';
  font-size: 15px;
}

atom-text-editor .cursor {

}

**Comment by Rydgel** [comment]
@richardwooding not working here.

**Comment by FrankVanVuuren** [comment]
@larsenwork That solution works perfect for me.

**Comment by Fresheyeball** [comment]
Weirdly, that css code works well for me on windows, but not on osx or linux

**Comment by nadavwr** [comment]
Using @richardwooding's configuration I was able to see ligatures on osx.
Works like a charm for plain text files, and when using 'language-scala'.
Strangely enough, it didn't work as well in Java: => would present as double right arrow when inside a string literal, but as plain '=' and '>' in code.

**Comment by andrewdcato** [comment]
@richardwooding's workaround was successful for me in OS X (tested mainly in PHP), but the ligatures would never display on the active line.

**Comment by 50Wliu** [comment]
@as-cii This is fixed now, right?

**Comment by as-cii** [comment]
I think so, as on **master** Atom now behaves exactly as Chrome `<textarea>`. This is how Monoid support looks like without any particular configuration (except for `text-rendering: optimizeLegibility`):

![monoid](https://cloud.githubusercontent.com/assets/482957/10219574/600909c6-6840-11e5-8b76-6d3e841991df.gif)

Unfortunately, Hasklig/Fira Code are not 100% supported as Chrome won't report the exact space between characters when there is a ligature (e.g. they _seem_ to be considered as a single character), so the cursor won't be positioned "inside" it:

![hasklig](https://cloud.githubusercontent.com/assets/482957/10219676/3c5272be-6841-11e5-9b1c-510c2d562d6d.gif)

However, we now degrade gracefully and allow the cursor to be positioned correctly even on subsequent characters without any special configuration. So, you shouldn't see stuff like the following happening anymore:

![master](https://cloud.githubusercontent.com/assets/482957/10219827/9d273240-6842-11e5-8bd5-561ba188b384.gif)

Ideally I'd love to put a break in between characters when some kind of edit action is happening, but that comes with a performance overhead because we'd have to change the line every time e.g. a cursor is moved. 

I am going to close this for now, as Atom should now be usable regardless of the font configuration and behaves exactly like Chrome text area does. Please, let me know if we should reopen this because of some issue I am not taking into account.

Thanks everyone! :pray:

**Comment by Rydgel** [comment]
@as-cii This looks much better indeed, thank you.

**Comment by MrLoh** [comment]
When will this be active? In the current Atom the ligatures work mostly fine (no rendering of `!=` though) but there are a bunch of spacing issues with text when `text-rendering: optimizeLegibility` is on.

**Comment by thomasjo** [comment]
> When will this be active?

Most likely in the v1.2.0 release I believe (unless some serious regressions are discovered). If you want it immediately, consider building the `master` branch yourself. It's fairly straight forward.

**Comment by alexandernst** [comment]
@thomasjo WIll `text-rendering: optimizeLegibility` be enabled by default? aka, will ligatures work out of the box?

**Comment by thomasjo** [comment]
> WIll text-rendering: optimizeLegibility be enabled by default?

No, that hasn't changed. I could see that being introduced as a configuration option though... I'm pretty sure such a PR would be accepted :smirk:

**Comment by altaic** [comment]
This is great; thank you so much.

**Comment by gusaiani** [comment]
Thanks to everyone who made this happen.

**Comment by Fresheyeball** [comment]
This made my day. Thank you so much for making this happen.

**Comment by hyiltiz** [comment]
Cheers for making this happen!

**Comment by ngeor** [comment]
I stumbled upon this post trying to understand why the "Space Mono" font renders the characters "fi" funny (and converts html closing tags into arrows). Linux with Atom 1.9.9 and Mac OS X with Atom 1.10.2, for me a fine workaround is to shut down this feature completely by adding this to the stylesheet:

```
atom-text-editor {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}
```

after that the font works fine.
