### ISSUE TITLE
Atom: doesn't recognize "~" as home on path

### ISSUE THREAD

**Issue by cusspvz** [atom/atom#3829]
Atom doesn't recognize "~" as home on paths, even on CLI if it is provided as string.

You could replicate with:
* api
```coffeescript
atom.open "~/some/folder/on/your/home"
```
* bash:
```bash
atom "~/some/folder/on/your/home"
```

Running Atom on MacOS X 10.10 Yosemite.

**Comment by andersennl** [comment]
I'm having the same problem. 
I have two different computers, both having the Atom folder synched via symlinks over dropbox. With absolute paths to a Rubocop installation, everything works fine. For one computer, the other one is spawning a lot of read warning boxes. 

Long story short, `~/.rvm/gems/ruby-2.2.0/bin/rubocop` doens't seem to work.

**Comment by cusspvz** [comment]
@kevinnathan @postcasio 
Is this a bug on `atom` itself or `node` core? Fortunately at the time we aren't depending on this, but i guess this may be a major bug for some plugins.
Can't we workaround it by replacing `~` by `process.env.HOME`?

**Comment by postcasio** [comment]
I'm not part of the atom team but I would have reservations about doing expansions like this - what happens if you do want to open a file named `~`? How can Atom differentiate between a `~` you want to expand and one you don't?

**Comment by mark-hahn** [comment]
This code is required to find the user's `~` directory ...

```coffeescript
home =
  if process.platform is 'win32' then process.env.USERPROFILE
  else process.env.HOME
```

**Comment by cusspvz** [comment]
@postcasio you have a point, there are a lot of files with `~` char, specially when it comes to tmp files.

I think we could workarround with a simple regexp replacement like this:
```js

var home = process.platform == 'win32' && process.env.USERPROFILE || process.env.HOME || '~';

function getFullPath ( path ) {
  return path.replace( /^~(?:\/)/, home + '/' );
}

```

`/^~(?:\/)/` regexp would select the first `~` char only if it has a slash after it.

I've also [created some path scenarios](http://jsbin.com/banifotudi/1/edit?js,console) to check if it covers all them.

@mark-hahn thanks for your suggestion

**Comment by cusspvz** [comment]
I checked @kevinsawicki commits about `ATOM_HOME`, won't `fs.absolute` fix this?

**Comment by kevinsawicki** [comment]
`fs.absolute` does handle `~/`

**Comment by cusspvz** [comment]
@kevinsawicki so, would the add of `fs.absolute` into [atom-application.coffee](https://github.com/atom/atom/blob/c3bd501b84a9207cbc0a7de4d89b29340ab616d9/src/browser/atom-application.coffee#L347) fix this issue?

```
-      pathToOpenStat = fs.statSyncNoException(pathToOpen)
+      pathToOpenStat = fs.statSyncNoException fs.absolute pathToOpen 
```

**Comment by kevinsawicki** [comment]
Opened paths via the `atom.open` API and atom command line will now be normalized which resolves `~`, `.`, `..`, and converts to proper platform separators.

**Comment by cusspvz** [comment]
Nice! Thanks @kevinsawicki
