### ISSUE TITLE
Fonts are a bit blurred compared to other editors

### ISSUE THREAD

**Issue by valsamakis** [atom/atom#3869]
I am using Windows 8.1 and I always use Consolas fonts for source code.
Antialiasing seems to not working for atom, so if I compare how the fonts are look like with
other editors there is a difference against atom. To see the difference put next to each other a code
opened with Eclipse or Intellj with code open with atom. Even Gvim looks better. This is a major drawback.

**Comment by mnquintana** [comment]
Just out of curiosity, is this still the case with Atom 0.177.0, and do you experience the same thing with Brackets?

**Comment by valsamakis** [comment]
Yes I think this is the case. Brackets is a little better

**Comment by paulcbetts** [comment]
I've found that if you have a High DPI (scaled) display and you have it at the default of 1.5x scaling, you'll see this. Setting it to 2x (i.e. usually one notch toward "Larger" than recommended), it's cleared up. You can check this via opening the console and printing the value of `window.devicePixelRatio`

**Comment by 50Wliu** [comment]
Most likely fixed via #15372.
