### ISSUE TITLE
can't get rid of untitled tabs

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#3913]
There are two problems with untitled tabs.  These untitled tabs are created with `atom.workspace.open()`.

- When there is an untitled tab with contents, and you close Atom and select `Don't Save`, when atom reopens the untitled tab reappears with no contents.  This happens even when there are multiple normal tabs.  If you do this over and over you get more and more untitled tabs.

-  When my code executes `editor.delete()` for an untitled tab the contents are deleted but the tab view doesn't go away.

These seem like the same bug to me.

windows 8.0   --  atom 0.138.0

**Comment by 50Wliu** [comment]
@mark-hahn are you still experiencing the second issue?  The first one has been fixed in the 1.4.0 betas due to the new "autosave" feature for untitled tabs.

**Comment by mark-hahn** [comment]
> the contents are deleted but the tab view doesn't go away.
>  are you still experiencing the second issue? 

I would have to put together a test to check this.  Let's assume it's also fixed until someone complains.
