### ISSUE TITLE
Update the app icon on OS X to fit with the new Yosemite UI style

### ISSUE THREAD

**Issue by brandonweiss** [atom/atom#3923]

**Comment by brandonweiss** [comment]
![fark_4glikgpuzfc4wtk5h1urhsbq0n0](https://cloud.githubusercontent.com/assets/4727/5674062/8e027398-9759-11e4-8b65-8692d21b2b70.jpg)

It's beautiful...

**Comment by kevinsawicki** [comment]
:tada:
