### ISSUE TITLE
Debian package conflicts with "apmd"

### ISSUE THREAD

**Issue by borisovg** [atom/atom#3926]
Error when installing on a system with "apmd" package installed:

````
Selecting previously unselected package atom.
(Reading database ... 183328 files and directories currently installed.)
Preparing to unpack atom-amd64.deb ...
Unpacking atom (0.138.0) ...
dpkg: error processing archive atom-amd64.deb (--install):
 trying to overwrite '/usr/bin/apm', which is also in package apmd 3.2.2-15
Processing triggers for mime-support (3.57) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Errors were encountered while processing:
 atom-amd64.deb
````

**Comment by pascalopitz** [comment]
Also conflicts with Ubuntu's "Advanced Power Management" interface, result is this:

    $ apm
    No APM support in kernel

**Comment by frankgerhardt** [comment]
5 months later, still doesn't work

**Comment by mehiel** [comment]
+1, please fix this one.

For those not using the apm command which is just an interface for the APM subsystem installing atom with dpkg --force-overwrite and pin the current version of apmd package maybe a working solution for now.

**Comment by paulcbetts** [comment]
APM is dead, the kernel doesn't even support it anymore, why is this being installed on modern machines

**Comment by mehiel** [comment]
@paulcbetts, I agree but can you just say to anyone out there to remove it? The last fully supporting kernel is 3.3 which is not that old even for desktop setups. I'm pretty sure it's not there on modern installations and it seems that people having this problem fall into two categories:

1. they're coming from rolling updates, so apmd is just a zombie package and can be safely removed (that's me with a debian installation coming from 2007 but being on unstable with a 3.19 kernel now)
2. they indeed have an old setup with support for APM

Anyways, you can just run `apm

**Comment by paulcbetts** [comment]
> but can you just say to anyone out there to remove it? 

Yes, I definitely can, there is no reason _anyone_ should think about APM in 2015, it's like making sure a PCMCIA daemon is running "just in case"

**Comment by thomasjo** [comment]
I'm with @paulcbetts on this one. "Fixing" this on our end by renaming `apm` on Debian systems is simply not worth the effort considering the state of APM; it's practically speaking been EOL'ed. Just uninstall APM.

**Comment by thomasjo** [comment]
Closing this as this can easily be resolved by uninstalling APM.  If anyone feels strongly about this, and for whatever reason cannot uninstall APM, open a pull request with a fix.

**Comment by felicitus** [comment]
I have no idea why apm is on my system, or if it is required. I'm not going to uninstall apm on my system, as I have no clue about the side effects and rather stick with another editor than atom.

**Comment by trinaldi** [comment]
I'm not going to uninstall it either, but I'm creating an alias for Atom's apm. 

alias atapm='/path/to/your/apm'

**Comment by celvin** [comment]
This is happening with Ubuntu 16.04 and atom 1.8.0, please fix it! 

if you want to have both packages installed **apmd** and **atom** is not possible, please fix it.

this is a silly bug

Unpacking apmd (3.2.2-15) ...
dpkg: error processing archive /var/cache/apt/archives/apmd_3.2.2-15_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/apm', which is also in package atom 1.8.0

**Comment by thomasjo** [comment]
@celvin Ubuntu 16.04 ships with Linux kernel 4.4 which does **not** support APM. The last Linux kernel that supported APM was 3.3.

**Comment by celvin** [comment]
mmmmm look at this:
http://packages.ubuntu.com/xenial/apmd

**Comment by thomasjo** [comment]
Yeah, but does it work? The kernel explicitly needs to be built with APM functionality switched on these days. Unless Canonical is doing that by default for some reason, you'd need to compile the kernel yourself.

**Comment by rafaelsoaresbr** [comment]
I'm running Debian Sid, and some important packages suggests apmd (not installed):
hdparm, laptop-mode-tools, etc
But, there's this another package that replaces apmd named powermgmt-base (witch is installed).

**Comment by stmllr** [comment]
From the Debian package description of apmd:
`aptitude show apmd`

>  Since lenny Debian kernels are not built with APM support anymore. You need to compile a kernel with apm support enabled to use this package. You need to boot the kernel with the "apm=on"
 option if you want to enable the driver.                                                                                                                                                     
                                                                                                                                                                                              
> In most cases, users may want to know that there are newer power management schemes, like ACPI.

Lenny reached end of life on Feb 06, 2012

**Comment by celvin** [comment]
how ever is not correct to name the binaries as another that already
exists.

Celvin Rivas
http://www.vitelika.com
7126-9172 (24/7)
2231-1165 (8am-3pm / L-V)

**Comment by glandium** [comment]
There are two possible resolutions to this issue:
- Rename apm
- Add an explicit conflict to the atom .deb package. (`Conflicts: apmd`)

The former would allow installing both packages at the same time.
With the latter, `apt install atom` would work, by giving the user the option to remove `apmd` and anything that has a hard dependency on it.

**Comment by borisovg** [comment]
@glandium I don't think that the rules allow for a "conflicts" in this situation.

From https://www.debian.org/doc/debian-policy/ch-files.html#s-binaries

```
Two different packages must not install programs with different functionality but with the same filenames. (The case of two programs having the same functionality but different implementations is handled via "alternatives" or the "Conflicts" mechanism. See Maintainer Scripts, Section 3.9 and Conflicting binary packages - Conflicts, Section 7.4 respectively.) If this case happens, one of the programs must be renamed. The maintainers should report this to the debian-devel mailing list and try to find a consensus about which program will have to be renamed. If a consensus cannot be reached, both programs must be renamed.
```

Looks like conflicts is for packages that provide similar functionality.

**Comment by celvin** [comment]
we should change the name of the package apmd -> atomd

Celvin Rivas
http://www.vitelika.com
7126-9172 (24/7)
2231-1165 (8am-3pm / L-V)

**Comment by arnoFleming** [comment]
From a usability point of view, I think that the installer of Atom could find out if the `/usr/bin/apm` binary is installed on the machine, and if it is, output a link to this issue, and give a tl;dr: `sudo apt-get remove apmd` (or equivalent). That feels so much better than just erroring out (and leaving the user wondering / googling for a solution). 

If `apmd` is so incredibly outdated, we should not let our users go through the hassle of searching for this issue. If the installation problem can be resolved so easy ( at least on most machines used by developers interested in Atom).

**Comment by 50Wliu** [comment]
@arnoFleming please create a new issue for that.

**Comment by celvin** [comment]
If apmd is NOT outdated

**Comment by davidhaile** [comment]
This worked for me:

1.) Rename /usr/bin/apm to anything else (may not actually need this step with the force-overwrite below)
2.) sudo dpkg --force-overwrite -i atom-amd64.deb
