### ISSUE TITLE
Feature: OSX - Recent Projects on right click in Dock

### ISSUE THREAD

**Issue by habermann24** [atom/atom#3935]
Other editors (e.g. Textmate) give a list of recently used projects/files when right clicking on the icon in the dock.

See these screenshots:

![screen shot 2014-10-23 at 00 36 31](https://cloud.githubusercontent.com/assets/7480/4745559/f54196de-5a3b-11e4-905c-7cdd97f11dd9.png)
![screen shot 2014-10-23 at 00 36 09](https://cloud.githubusercontent.com/assets/7480/4745560/f542b992-5a3b-11e4-8a03-95bc82685ef8.png)

It would be great if Atom would do the same.

I was not sure what package to post this issue in. Maybe it belongs to atom-shell.
There needs to be some code that can hook into native OSX APIs, since that is how i believe that it works.

**Comment by aequitas** [comment]
I would love to see this feature, as I use it frequently with Textmate.

**Comment by janbaykara** [comment]
+1

**Comment by brianmoran** [comment]
Is there a way to Clear closed projects? When I right click on the dock icon, it shows projects that I have deleted or no longer want to show up.

**Comment by grahm** [comment]
needs to be a preference setting to turn this off

**Comment by thecodeassassin** [comment]
Take a look at this:

http://tca0.nl/Alp

The recent items setting is turned to None in my general settings and yet my atom context menu is flooded with recent items.

**Comment by starriv** [comment]
> Is there a way to Clear closed projects? When I right click on the dock icon, it shows projects that I have deleted or no longer want to show up.

I also encountered the same problem
