### ISSUE TITLE
Open multiple files from fuzzy finder

### ISSUE THREAD

**Issue by openben** [atom/atom#3948]
Hi guys, 

from another IDE I am using I like the feature to have multiple files opened at one time. This works by pressing Shift and Arrow up/down to mark them and then simply Enter to open. A new tab for each file will then be opened. 

Regards Benedikt

**Comment by samrayner** [comment]
See https://github.com/atom/fuzzy-finder/issues/70

**Comment by mnquintana** [comment]
Thanks @samrayner! Closing this out in favor of https://github.com/atom/fuzzy-finder/issues/70.
