### ISSUE TITLE
Bug in Markdown Links where URL has Parenthesis 

### ISSUE THREAD

**Issue by ChristopherA** [atom/atom#3956]
In Atom 0.139.0 on Macintosh Yosemite 10.10:

This link doesn't work correctly – the internal parenthetical should be ignored for closing the markdown link. Instead, the closing parenthesis in the valid URL closes the entire markdown link, causing the link to be bad and the closing .pdf to be rendered as text.

```
["A Taxonomy of Privacy"](https://www.law.upenn.edu/journals/lawreview/articles/volume154/issue3/Solove154U.Pa.L.Rev.477(2006).pdf).
```

**Comment by Dentosal** [comment]
It's not just markdown, it looks like this bug exists whenever we have URLs displayed in Atom. While they may not be "allowed" in URLs, they are used commonly, so it would be nice to support them. For example Wikipedia uses them: [https://en.wikipedia.org/wiki/Python_(programming_language)](https://en.wikipedia.org/wiki/Python_(programming_language)).

![screen shot 2016-10-23 at 22 39 18](https://cloud.githubusercontent.com/assets/2204863/19628915/b1adfa1c-9971-11e6-8b64-b881ea4d2798.png)

**Comment by Dentosal** [comment]
I can still reproduce. Atom 1.17.2, OS X El Capitan 10.11.6.
