### ISSUE TITLE
Bug in TextBuffer::setTextInBufferRange() ?

### ISSUE THREAD

**Issue by brunetton** [atom/atom#3971]
Hi, 

I'm not sure, but something seems not logical to me. According to the doc of *TextBuffer::setTextInBufferRange()* :

>   Public: Set the text in the given range.
>  
>   * `range` A {Range}
>   * `text` A {String}
>   * `normalizeLineEndings` (optional) {Boolean} (default: true)
>  
>   Returns the {Range} of the inserted text.

But when passing a Range argument to the method, I do not observe a text replacement, but an insert.

I've seen in the unit tests that you use an array as param, witch works as excepted : the old text is *replaced* by the given one.

## Steps to reproduce :

     atom --safe

  * add some text in a new file : `1234` in the first line
  * then in developper tools console :

```javascript
textBuffer = atom.workspace.getActiveTextEditor().getBuffer();
textBuffer.setTextInRange([[0,0], [0,1]], 'a');
```

=> **Ok** first line becomes `a234`

  * now trying to replace back the 'a' by '1', using a Range argument :

```javascript
textBuffer.setTextInRange(new Range([0,0], [0,1]), '1')
```

=> **Not Ok** first line becomes `1a234`, it's not a replace but an insert

**Comment by benogle** [comment]
We did not rename as part of the api freeze. Closing as we plan on keeping it the way it is.
