### ISSUE TITLE
Opening Atom in Windows 7

### ISSUE THREAD

**Issue by Lerogero** [atom/atom#3973]
Just downloaded Atom to use at Uni but it's not opening like usual.

![image](https://cloud.githubusercontent.com/assets/5865044/4789063/f4194706-5dc0-11e4-9dd5-eae699125c0c.png)

Is all I see.

Have I done something wrong, or do the uni computers have something missing.

**Comment by kevinsawicki** [comment]
I think this issue has been resolved with several of the load path fixes and asar support added since October, closing this out.

Please comment if you still see this issue on Atom 1.0.5+.
