### ISSUE TITLE
How to fold level 1 code but not comments

### ISSUE THREAD

**Issue by joelstein** [atom/atom#3995]
I recently made the transition from long-time use of TextMate to Atom. One TextMate feature I greatly miss is the ability to fold all code to level 1 while not folding the comments. When I "Fold Level 1" in Atom, it folds all code and all comments.

See this PHP example:

``` php
<?php

/**
 * Comments for function 1.
 */
function function_1() {
  return 'Do something.';
}

/**
 * Comments for function 2.
 */
function function_2() {
  return 'Do something else.';
}
```

Folding level 1 in Atom looks like this:

![image](https://cloud.githubusercontent.com/assets/152397/4825796/2fc9da6e-5f69-11e4-988c-9b32d0609feb.png)

The same code folded to level 1 in TextMate looks like this:

![image](https://cloud.githubusercontent.com/assets/152397/4825809/565a1c52-5f69-11e4-8e6e-ae16275abb2d.png)

Is there any way to accomplish this behavior in Atom? I have version 0.140.0.

**Comment by arta** [comment]
Agree. It's unexpected and frustrating; a bug? In Ruby, folding level 1 folds the method definition and the unindented comments above it:

    # Elaborate comment
    # conveys terribly important points
    # all the way up to here
    def method_name( foo, bar )
      foo + bar
    end

    # Elaborate comment <..>
    def method_name( foo, bar ) <..>

That's not cool, not by default.

**Comment by arta** [comment]
Agree. It's unexpected and frustrating; a bug? In Ruby, Folding Level 1

```
# Elaborate comment
# conveys terribly important thoughts
# all the way down up to this point
def sum_it_up( foo, bar )
  foo + bar
end
```

produces:

```
# Elaborate comment<..>
# def sum_it_up<..>
```

That's not helpful; not by default.
