### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by jwchameleoncorp** [atom/atom#4004]
Hello,

I've tried installing Atom via the Command Prompt and Application File method, but both have been unsuccessful.

Attached are the screen shots of both results.

Any suggestions?

Thanks,

Jeff
![command prompt install](https://cloud.githubusercontent.com/assets/8533262/4837874/6c7dee66-5fdf-11e4-85a2-a2b760a0b037.JPG)
![stand alone install](https://cloud.githubusercontent.com/assets/8533262/4837873/6c7d5c80-5fdf-11e4-8b74-380ce878e81c.JPG)

**Comment by 50Wliu** [comment]
I'm going to assume that this has been fixed in the Squirrel installer.
