### ISSUE TITLE
Horizontal scrolling stops after using code folding, recovers eventually

### ISSUE THREAD

**Issue by tomschlenkhoff** [atom/atom#4005]
0.140.0 Atom, started with "atom --safe" on OS X 10.9.5.
Opened one tab with a smallish html file.
Sideways scrolling works nicely, once I fold a code block, sideways scrolling dies.
Unfolding, folding, unfolding, sometimes helps. I don't see any other irregularities, neither in the developer tools console nor the system console.

Attached you'll find a 01:20 movie documenting the problem.

https://dl.dropboxusercontent.com/u/3898368/sideways_scrolling_bug_720.mov

**Comment by aviflax** [comment]
I’m experiencing this as well. 0.187.0 on OS X 10.10.2 (14C109). Whenever I perform “fold all” or “fold at indent level 1” in a file, the horizontal scroll bar disappears and I cannot scroll horizontally with mouse, trackpad, or keyboard. This does *not* happen when I use “fold current row” or “fold at indent level N” where N > 1. Using “unfold all” always restores scrolling and the scroll bar for me.
