### ISSUE TITLE
Package Installations are failing

### ISSUE THREAD

**Issue by harshdeep21** [atom/atom#4030]
Hi There,

Atom is greatly shaping up as full stream editor with help of it's packages. For not sure why packages are stopping being installed. I am getting following error on install.

Thanks,
Harshdeep Mehta

npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http GET https://registry.npmjs.org/sinon
npm http GET https://registry.npmjs.org/chai
npm http 304 https://registry.npmjs.org/jshint
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/sinon
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/chai
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/underscore-plus
npm ERR! Error: ENOENT, open 'C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\sinon\lib\sinon\call.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Harshdeep\\.atom\\.apmrc" "install" "C:\\Users\\Harshdeep\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.7.3\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\sinon\lib\sinon\call.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, lstat 'C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\chai\lib\chai\interface\assert.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Harshdeep\\.atom\\.apmrc" "install" "C:\\Users\\Harshdeep\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.7.3\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\chai\lib\chai\interface\assert.js
npm ERR! fstream_path C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\chai\lib\chai\interface\assert.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\ProgramData\chocolatey\lib\Atom.0.141.0\tools\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\lodash\dist\lodash.compat.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Harshdeep\\.atom\\.apmrc" "install" "C:\\Users\\Harshdeep\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.7.3\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\lodash\dist\lodash.compat.js
npm ERR! fstream_path C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\lodash\dist\lodash.compat.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\ProgramData\chocolatey\lib\Atom.0.141.0\tools\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: EPERM, unlink 'C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js'
npm ERR! error rolling back  linter@0.7.3 { [Error: EPERM, unlink 'C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js']
npm ERR! error rolling back   errno: 50,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   path: 'C:\\Users\\HARSHD~1\\AppData\\Local\\Temp\\apm-install-dir-114101-8332-1kxl1rr\\node_modules\\linter\\node_modules\\jshint\\dist\\jshint-rhino.js' }
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Harshdeep\\.atom\\.apmrc" "install" "C:\\Users\\Harshdeep\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.7.3\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm ERR! Error: ENOENT, lstat 'C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\ProgramData\\chocolatey\\lib\\Atom.0.141.0\\tools\\Atom\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Harshdeep\\.atom\\.apmrc" "install" "C:\\Users\\Harshdeep\\.atom\\.node-gyp\\.atom\\.apm\\linter\\0.7.3\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js
npm ERR! fstream_path C:\Users\HARSHD~1\AppData\Local\Temp\apm-install-dir-114101-8332-1kxl1rr\node_modules\linter\node_modules\jshint\dist\jshint-rhino.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\ProgramData\chocolatey\lib\Atom.0.141.0\tools\Atom\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/property-accessors
npm

**Comment by mnquintana** [comment]
Please feel free to reopen this if you run into this issue on the latest version of Atom (0.194.0).
