### ISSUE TITLE
Atom version in rpm, deb, and dmg packages

### ISSUE THREAD

**Issue by dhollinger** [atom/atom#4044]
Can we get the version appended to the rpm, deb and dmg packages as they are built.

I can't speak to dmg for mac, but it is considered standard practice to include the version and release as part of the filename in rpm and deb packages, especially since atom doesn't update itself and there are no YUM repos (yet).

**Comment by LordGaav** [comment]
Looks like that script actually creates a properly named package, and it gets renamed at the end. Seems like something that could easily be changed, provided that the system that calls mkdeb can handle it.

**Comment by rhcarvalho** [comment]
:+1: this would be helpful

**Comment by freakabcd** [comment]
Since @LordGaav has clearly identified the problem, can someone tell us why it is being mangled?

**Comment by LordGaav** [comment]
This is still an issue, most packages still do not contain the version number.

**Comment by amendment19** [comment]
Hi! This is still an issue. When I try to upgrade atom for linux I see the "Download .deb" and "Download.rpm" buttons, but nowhere on the page does it say what version these downloads are. 
Steps taken

- I click the "Download .deb" button and a download begins. 

- When it finishes downloading, I look in my downloads folder and see the package called "atom-amd64.deb". 

- After changing permissions to allow execution, I double click this package and it opens in Ubuntu Software, in this screen I can see the version number but the version number is not in the file name where I would prefer. 

Thanks for your time. 
![atom01](https://user-images.githubusercontent.com/12578033/32858903-98be0682-ca12-11e7-9065-b1ce05e57dce.png)
