### ISSUE TITLE
Error on load: Cannot read property 'length' of undefined 

### ISSUE THREAD

**Issue by brentonstrine** [atom/atom#4070]
Upon initial load of Atom (OSX Maverics), the developer tools window pops up and gives this error:
````
Uncaught TypeError: Cannot read property 'length' of undefined 
/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:385
````

**Comment by davetoxa** [comment]
Same error, updated `linter` using `apm upgrade` inside `.atom` dir and everything began work

**Comment by 50Wliu** [comment]
Closing as per @dmnd's suggestion.
