### ISSUE TITLE
Hardware acceleration can actually be slower on Windows

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom#4072]
Depending on the environment and whether the machine's video card sucks, Atom's performance can actually be improved by unchecking "Use Hardware Acceleration". 

It'd be a good idea at some point to get a video card blacklist going where the default value of "Use Hardware Acceleration" is informed by this data point. You can fetch the video card Vendor/DeviceID via `wmic`.

A shorter term thing would be to update the copy below the option to note that it might help to uncheck it

**Comment by damieng** [comment]
Is this really still an issue?

**Comment by paulcbetts** [comment]
Nah, kill it
