### ISSUE TITLE
Unable to install extensions under proxy

### ISSUE THREAD

**Issue by iamvoid13** [atom/atom#4081]
I am unable to install extensions or themes from atom.
I am using proxy server for internet connection. Here is the screenshot
![screenshot 258](https://cloud.githubusercontent.com/assets/8265616/4942964/409964ee-65f0-11e4-8a58-b98ea2650f1d.png)

**Comment by 50Wliu** [comment]
@animedbz16 did you resolve your problem?

**Comment by kevinsawicki** [comment]
Closing in favor of https://github.com/atom/apm/issues/322
