### ISSUE TITLE
cmd+ and cmd- should keep you at the same line in the file

### ISSUE THREAD

**Issue by colllin** [atom/atom#4084]

**Comment by mnquintana** [comment]
Still an issue on Atom 0.196.0 and OS X 10.10.3

**Comment by phord** [comment]
The proposed fix from @mnquintana doesn't quite do the right thing.  It tries to keep the cursor on the display, but the cursor is not necessarily on the viewport in the first place.  So this adds a new oddity to the problem.  

I do have a fix that almost works when auto-wrap is disabled, but it gets the viewport wrong when wrap is enabled. I haven't figured out how to properly position the screen when wrap is on.  Or maybe there's a bug in pixelPositionForBufferPosition.  I'm not sure what it's expected to do.

But my fix only works for the active buffer.  Other buffers which are not currently visible do not get updated correctly.  There's some discussion of that in #6673, hinting at a more extensive architectural fix that's required to address it.

**Comment by phord** [comment]
Confirmed this is fixed in 1.19.0
