### ISSUE TITLE
Tree view show files greyed out that should not be greyed out

### ISSUE THREAD

**Issue by tfar** [atom/atom#4095]
Freshly checking out a project I'm working on via ```git clone https://git.swift.im/review/swift``` and opening it via ```open -a "Atom" swift``` it shows all source files (.cpp/.h) under Swift/QtUI as greyed out ( https://www.dropbox.com/s/hpb089qah49itsl/Screenshot%202014-11-07%2019.04.41.png ), as if they were covered by .gitignore, but they aren't. This also prevents them to be easily opened via ```CMD+P```.

OS: OS X 10.9.5
Atom Version: 0.141.0

**Comment by Kev** [comment]
Hi, has there been any progress on this (still seems to be a bug in the latest), or is there any additional information anyone can give to help?

It's more serious than just not rendering in the sidebar - because Atom thinks these files are ignored, it won't open them in the normal way either.

**Comment by andersryanc** [comment]
I'm experiencing a similar (if not same) issue.

See screenshot:
https://www.dropbox.com/s/a8m3k2h4if63hgz/Screen%20Shot%202015-03-12%20at%202.51.45%20PM.png?dl=0

My case is a WP install where I only want to include the relevant theme and plugin files. I have pretty complex rules setup to ignore all, then not ignore some, ignore more, etc... I would expect the "themes/coconutbliss" folder to be highlighted, but as you can see from the screenshot, it is not.

I'm currently using Atom v0.187.0

**Comment by 50Wliu** [comment]
@andersryanc I believe you're describing a different issue atom/tree-view#196.

**Comment by cmjaimet** [comment]
Try looking up your file tree. You may find another .gitignore file in a parent folder that's causing the problem.

**Comment by lee-dohm** [comment]
I can't reproduce this using Atom v1.7.4 on Mac OS X 10.11.5 against the repository listed in the original report.

Is anyone here still experiencing this problem?

**Comment by lee-dohm** [comment]
Sounds like this has been fixed. Thanks everyone!

**Comment by lee-dohm** [comment]
Please let us know if anyone can still reproduce this.

**Comment by Kev** [comment]
Apologies for not replying. I can confirm I'm not seeing this any more.

**Comment by rightaboveit** [comment]
@lee-dohm I just got this issue except for seemingly random files after updating FB Nuclide and I believe language-babel as well. 

[https://i.imgur.com/Nzzk8RX.png](https://i.imgur.com/Nzzk8RX.png)

Doesn't seem to have any negative side effects as of right now.

**Comment by lee-dohm** [comment]
@rightaboveit Nuclide has its own implementation of tree-view last I checked. Let us know if you can reproduce it on the built-in tree-view.

**Comment by derwaldgeist** [comment]
Same problem here with Nuclide. Some files are just randomly greyed out. Which files are affected changes over time.
