### ISSUE TITLE
Multiple-window menu bug on Windows

### ISSUE THREAD

**Issue by rprichard** [atom/atom#4110]
On Windows only, when I open multiple Atom windows, then jump from one window's menu to the other window's menu, the menu actions affect the former window.  It should affect the latter window.

Steps to reproduce:
1. Open two windows in Atom.
2. In Window 1, click the "View" menu.  Leave it open.
3. In Window 2, click the "View" menu.  The menu in Window 1 will close when you click it.
4. Click something like, say, "View -> Developer -> Toggle Developer Tools".  The tools are toggled on Window 1, even though you clicked the item in Window 2.

I noticed this problem while looking at https://github.com/atom/atom-shell/issues/802.  In that case, I noticed that I could open two Atom windows, launch "File -> Open File..." in Window 2, then apparently open Window 2's menu by first clicking on Window 1's menu.  Selecting something in Window 2's apparent menu actually affects Window 1.

**Comment by damieng** [comment]
This is still an issue in master today.
