### ISSUE TITLE
Ask for root password when required

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#4115]
Some files require root permissions to be edited, but sometimes those files are already modified when one realizes those files require said permissions. It would be nice if Atom could ask for the root password and apply the changes instead of having to close the file, close Atom, open Atom with root privileges and re-edit the file.

**Comment by benogle** [comment]
This is currently supported in OSX when writing a file, but not when reading. With the addition of https://github.com/atom/node-runas/pull/14 we can support this in [read](https://github.com/atom/node-pathwatcher/blob/5b6e3dbfcd508115c56a7b79173b345fb00dfb23/src/file.coffee#L202) (though with a blocking read all at once).

**Comment by alexandernst** [comment]
Read all at once is a complete no-no. It will be slow and il will block the entire editor.

**Comment by benogle** [comment]
Word. Problem is that because of the privilege escalation, the read needs to happen in another process. So the 'right' way would need to be some kind of ipc streaming (via stdout?) in runas.

**Comment by alexandernst** [comment]
That would be an option, yes. Escalate the "reader" process and then send the content of the file to Atom.

One major drawback of that is that you'll be actually sending X amount of data via IPC (or any other mechanism) from one process to another. What happens if you open a 60mb file? Sending 60mb via IPC doesn't sound like a good idea.

A better approach would be to create a privileged "reader" process than can both send and receiver signals from Atom. When the "reader" is running, Atom can ask the "reader" just for the right chunks of the file  (for example, from line 1 to line 100 or from byte 943 to byte 1237). That way you'll have a no-blocking reader that won't be resource-hungry.

**Comment by alexandernst** [comment]
Btw, having in mind what I just said, this seems just the right moment to think about issue #307 

Refactor Atom to actually use reader processes to read files and ask those readers only for the exact amount of data required by the user.

**Comment by NikosEfthias** [comment]
same issue here

**Comment by orange-buffalo** [comment]
+1
Still a problem with 1.6.1 on Ubuntu 15.10

**Comment by ugyballoons** [comment]
This seems to be broken in OS X now too  (1.7.4 on osx 10.11.5)

Worse still, closing a tab and selecting save changes simply drops the tab when permission to save is denied.

**Comment by toXel** [comment]
Just as a workaround: this package does exactly the thing we miss: https://atom.io/packages/susave
I hope that we don't need a extra package for things like this in the future...

**Comment by pabloab** [comment]
Even with this package, [considering this](https://blog.martin-graesslin.com/blog/2017/02/editing-files-as-root/),  we can be sure this don't have any security risks? In this cases don't we should **always** use `sudoedit`?

**Comment by alexandernst** [comment]
Still an issue

**Comment by xenulv** [comment]
Is there a suggested alternative for those of us on Linux who want to edit Puppet files (or similar config mgmt tools) which require root?

**Comment by TimTinkers** [comment]
I don't think @benogle works on Atom anymore. Since this is Atom's oldest Linux bug maybe it should be reassigned.

**Comment by covertg** [comment]
Not a full solution, but the package [susave](https://github.com/sinkuu/atom-susave) provides an ok workaround for me. Unfortunately it hasn't been updated in a few years—I had to disable "Try Default Save," and even then it doesn't seem to communicate to Atom that the file has been updated. Just wanted to share in for anyone else finding this issue.

**Comment by Kreyren** [comment]
Same issue.

**Comment by tominventisbe** [comment]
It may be worth mentioning that [PolicyKit](https://gitlab.freedesktop.org/polkit/polkit/) is usually recommended as the successor to gksu. It can also be configured on a per-user basis to allow (and remember) access to specific binaries or even execute scripts to determine whether privileges should be granted.
