### ISSUE TITLE
"SELF_SIGNED_CERT_IN_CHAIN" in packages and themes tab of settings

### ISSUE THREAD

**Issue by youngdad33** [atom/atom#4122]
Hello,

I've been using Atom now as my main code editor for months and I love it. However, I've noticed in the last couple of versions that there seems to be a problem with accessing the packages and Themes tab of the settings. Whenever I search for something, I get this error come up:
    SELF_SIGNED_CERT_IN_CHAIN
I have tried uninstalling Atom and reinstalling it, and the same problem comes up.
Is this an Atom problem, or more likely something to do with my laptop, and if so, what?
I'm running a MacBook Air on Mac OSX 10.10 Yosemite with Atom version 0.144.0.
Any help would be most appreciated, since I don't seem to be able to add extensions any more.

Many thanks,
Dominic Ross,

**Comment by LoneBoco** [comment]
This error is really sinister for me.  I'm on version 0.169.0 for Windows.  I'm behind a proxy at work.

I was able to create a **~/.atom/.apmrc** file and add **strict-ssl = false** to solve the issue with apm.  However, I have no idea how to tell atom itself to allow self-signed certs.  When this error occurs, it will sometimes get stuck in a loop spamming the error over and over, locking up the editor completely.

Here are two of the errors I've seen.  I usually see the stream.js:94 one.
```
stream.js:94
Error: self signed certificate in certificate chain
  at Error (native)
  at TLSSocket.<anonymous> (_tls_wrap.js:914:36)
  at TLSSocket.emit (events.js:104:17)
  at TLSSocket._finishInit (_tls_wrap.js:457:8)

events.js:85
Error: self signed certificate in certificate chain
  at Error (native)
  at TLSSocket.<anonymous> (_tls_wrap.js:914:36)
  at TLSSocket.emit (events.js:104:17)
  at TLSSocket._finishInit (_tls_wrap.js:457:8)
```

**Comment by sveilleux** [comment]
apm config set strict-ssl false

**Comment by kevinsawicki** [comment]
Closing this out, this is a configuration issue where you may need to configure apm/npm when behind a firewall/proxy, see https://github.com/atom/apm#behind-a-firewall for more details.

**Comment by adjenks** [comment]
Disabling SSL is not safe, if you cannot connect it may be due to your corporate firewall, In this case you need to install a trusted certificate. See #8465

**Comment by adjenks** [comment]
@sveilleux This leaves you open to man-in-the-middle attacks. Anyone can pretend to be npmjs.org at this point and then you could end up getting hacked if someone knows that you are using this setting. I do not recommend anyone do this.
