### ISSUE TITLE
Command F randomly stops working sometimes 

### ISSUE THREAD

**Issue by omarmeky** [atom/atom#4131]
Randomly the find feature for files will stop working; the global find (shift + command + f) still works though. I have to restart the editor for it to work again.

**Comment by nevins-b** [comment]
I just ran into this with version 0.199.0. I didn't check to see if the command palette was available. No find commands where available until after restart.

**Comment by omarmeky** [comment]
@nevins-b for me, it turned out to be user error; I would set the scope to highlighted text only (the quote option in the find tool) and then once I am done searching, the next time I search if nothing is highlighted then of course there will be no match.

**Comment by omarmeky** [comment]
I will close my issue but I guess re-open if you indeed have a bug.

**Comment by kolen** [comment]
For me, sometimes it stops working too, both when invoking with *cmd+f* and via menu bar (*Find -> Find in buffer*). Search panel does not appear. After restarting Atom it works again. Version 0.206.0.

**Comment by dhavalsharma** [comment]
yes, it happens to me also, when i switch to another file and then come back to current file then i can search in current buffer again

**Comment by nathansobo** [comment]
There was a seemingly related issue where cmd-f wouldn't work when a dock was focused. Should be fixed now.
