### ISSUE TITLE
Copy (ctrl+c) copies only the first character of selection

### ISSUE THREAD

**Issue by nylki** [atom/atom#4132]
In 0.145 on linux, after some encoding trouble, I also noticed the problem that i can't copy selected text anymore. Also the file saved as UTF8 is unreadable in eg. gedit or vim (might be an additional issue)

**Comment by 50Wliu** [comment]
I can confirm that copying will sometimes fail and only copy one character.  Re-copying does not help.

**Comment by mnmnc** [comment]
Not sure if you care, but this bug still happens in 2017. 
Atom version 1.18.0 x64.
