### ISSUE TITLE
Make project.getRepositories pluggable to support VCS other than Git

### ISSUE THREAD

**Issue by benad** [atom/atom#4138]
Right now, Project populates "@repo" only with the result GitRepository.open. There is no way to make Atom support other VCS like Subversion or Mercurial from a plugin because of that. Also, subclassing GitRepository is difficult because it does far more than simply forwarding Git status information, for example subscribing to window focus changes in the constructor.

There should be a simple, generic base class for VCS support, with a mean for Project to ask each VCS module if the current project has any repository for its directory, and a clean API to refresh any item status.

**Comment by iorlas** [comment]
So?

**Comment by lmcardle** [comment]
+1

**Comment by tynril** [comment]
+1

**Comment by Emnalyeriar** [comment]
+1

**Comment by rodrigopmatias** [comment]
+1

**Comment by ergo** [comment]
+1

**Comment by diegomarquez** [comment]
+1

**Comment by batisteo** [comment]
+1
1.0-roadmap please

**Comment by nistvan86** [comment]
+1
Please merge this. I need Mercurial integration :)

**Comment by andischerer** [comment]
Actually this is already possible by using the `atom.repository-provider`. Today i've released a package in early dev state that supports svn.
https://github.com/andischerer/atom-svn

**Comment by BlaM** [comment]
There seems to be https://atom.io/packages/nuclide-hg-repository - but as far as I can tell that package - at least with Windows - does not work.

**Comment by josser** [comment]
@BlaM You have to install nuclide-file-tree to get it work

**Comment by BlaM** [comment]
I tried to use nuclide-installer for a full installation, but that didn't do anything. Not an issue of atom, though, so we shouldn't discuss that here. I just wanted to point users watching this issue to a possible solution.

**Comment by bolinfest** [comment]
We upstreamed https://github.com/atom/atom/pull/5491 to Atom so that we could support Mercurial (via https://atom.io/packages/nuclide-hg-repository) as part of Nuclide. If anyone else wants to add support for another version control system in Atom, I recommend following the pattern we set forth in `nuclide-hg-repository`.

Since the necessary API is there, I am going to close this issue.
