### ISSUE TITLE
Collapsing Multi-line comments does not work at all

### ISSUE THREAD

**Issue by Ageoneitor** [atom/atom#4140]
If I write comments without a empty new line, it works. But if I don't do that, Atom only collapses the part before the new line (instead of the whole comment), like if they were single-line comments (I have to click the two arrows of the multi-line comment to semi-collapse it):

(I' using Atom 144 and my OS is Linux Mint 17)

Before collapsing them - After Collapsing
![before collapsing](https://cloud.githubusercontent.com/assets/6506988/4986198/11e0a0dc-6937-11e4-9291-b35dda49d859.png) ![after collapsing2](https://cloud.githubusercontent.com/assets/6506988/4986199/11e7829e-6937-11e4-8d8e-cfb3e54b04c9.png)

**Comment by pleonex** [comment]
Hi, any progress on this?
I can see a referenced commit that seems to fix the issue.

**Comment by fkraus** [comment]
Does not seem to be fixed (using atom 1.2.4)

**Comment by kennethjfalbous** [comment]
I am not able to do multiline comment help please.

**Comment by 50Wliu** [comment]
> I am not able to do multiline comment help please.

This should be available starting in Atom 1.7.0.
