### ISSUE TITLE
Project-wide find and replace with regex does not replace

### ISSUE THREAD

**Issue by shawnacscott** [atom/atom#4154]
The find and replace with the project-wide tool (Cmd-Shift-F) is refusing to make replacements. I can replace with a standard find and replace, but not with the regex option enabled.

Atom 0.145.0, OS X 10.10
No errors were logged in the Atom console, or in Console.app.

![atom_find_and_replace_issue](https://cloud.githubusercontent.com/assets/1648967/5002757/5f8ba2fa-69b9-11e4-88cf-17219802da41.gif)

**Comment by marnen** [comment]
Still having this issue with complex regexes in 1.0.19 (Mac OS X 10.10). The specific regex I've been using is as follows.
Find: `\((->[^\u0000]*?)\n\s*\)\.observes[( ](.*?)[) ]?$`
Replace: `Ember.observer $2, $1`

**Comment by bbasic** [comment]
Same here. 
I tried to use following regex `table-responsive.*(.|[\r\n])\s+<table` simply to find files having matching text. 
With **Find in Project** it doesn't work. However, when I use **Find in Buffer** in a file that has the matching text, it finds the matching text.

Atom 1.1.0
Mac OS X 10.10

**Comment by benogle** [comment]
The issue is the new line in both @bbasic and @marnen's comments. See https://github.com/atom/scandal/issues/5 for more info

**Comment by infinitec** [comment]
Project find and replace is not working for me with the following expressions.
Find:  `("\+[a-z,A-Z]*)" \);$`
Replace:  `$1+"" );`
