### ISSUE TITLE
Syntax highlighting in C++ headers

### ISSUE THREAD

**Issue by sryze** [atom/atom#4156]
I noticed that Atom highlights .h files as C although they can be C++ as well. So keywords like `class` or `namespace` are not highlighted.

I think it would be nice to have some sort of automatic C vs. C++ detection. Or maybe you could just set it to C++ by default, they both have the same keywords anyway.

**Comment by randomstuff** [comment]
A workaround is to add this to your `~/.atom/init.coffee`:

~~~coffee
# Remove ".h" from C grammar (use C++ instead):
atom.grammars.onDidAddGrammar (grammar) ->
  if grammar.name is "C"
    grammar.fileTypes.splice(grammar.fileTypes.indexOf("h"), 1)
~~~

**Comment by andreldm** [comment]
@randomstuff thanks, it works, but there's a `)` missing at the end of `indexOf("h"), 1`

**Comment by maxbrunsfeld** [comment]
We plan to make the mapping of file extensions to grammars configurable sometime soon.

**Comment by thomasjo** [comment]
> We plan to make the mapping of file extensions to grammars configurable sometime soon.

:sparkling_heart:

**Comment by randomstuff** [comment]
@andreldm, Whoops copy/paste error. Thanks.

**Comment by patgithub** [comment]
I tried the file-types package which makes it easily possible to overwrite file type association in the `~/.atom/config-cson`. I just added this line:
```
  "file-types":
    h: "source.cpp"
```

(https://atom.io/packages/file-types)

**Comment by thomasjo** [comment]
@patgithub That functionality is built into Atom. No need to use a package, just use the `core.customFileTypes` option. This was only recently documented however, and the documentation doesn't seem to have gone live just yet, so for the time being check out:
https://github.com/atom/docs/blob/6e8baeecaf939426e66ee960c168cf27117215ef/book/02-using-atom/sections/06-customizing.asc#customizing-language-recognition

**Comment by patgithub** [comment]
@thomasjo much thanks - works good too!

**Comment by slgu** [comment]
@patgithub Really works .thx for your help

**Comment by inspiralpatterns** [comment]
Thanks for all the foregoing suggestions!
I tried the easy way selecting manually C++ with the grammar-selector package. 
I don't get any error now, but still I have couple of red points and that's the error message I get:

![screen shot 2016-10-28 at 22 58 36](https://cloud.githubusercontent.com/assets/8710333/19822114/22691d38-9d62-11e6-8174-6fac64aa0606.png)

even though I get the green light and `no issues` at the bottom.
How is such a behaviour possible?

**Comment by 50Wliu** [comment]
@inspiralpatterns That's an issue with whatever linter package you're using.
