### ISSUE TITLE
Feature Request: add crash restore

### ISSUE THREAD

**Issue by darkdragon-001** [atom/atom#4161]
Today my Atom crashed and I realized that there is no such thing as restore your unsaved work.
Since this is more than standard nowadays - please add this!

**Comment by 1j01** [comment]
Ideally there should never be a time where your changes aren't saved. [Scratch](https://launchpad.net/scratch) does this nicely. It's actually like you just edit the file when you edit a file. There's no unsaved state, and you can just undo when you need to. I find this is a much better model for editors to have, although then it makes sense to back up the original (which git does for you of course).
At any rate, there's no excuse for not having crash handling.

**Comment by hyiltiz** [comment]
Thought we already have that in Atom. If not yet (such as now), it really is a must.

**Comment by 1j01** [comment]
Atom has crashed at least 5 times, in several different ways since I've last commented.

**Comment by jaxzin** [comment]
+1 here, lost an unsaved buffer and was surprised Atom didn't have this feature. Seems a pretty standard in other popular text editors, so much so that I assumed Atom had it until it burned me.

**Comment by alexchandel** [comment]
:+1: How it is possible that atom is almost 1.0 and STILL doesn't have this? If 1.0 is released without supporting unsaved buffers, then atom is a lie. It's just not safe to edit documents when your computer could kernel panic, power down, or–in the case of Windows–*forcibly* shut you down to install updates, unless your text editor protects you by restoring its previous state. ST does this. IDEs do this. Literally all OS X NSDocument apps do this. Even internet browsers do this.

**Comment by 50Wliu** [comment]
> How it is possible that atom is almost 1.0 and STILL doesn't have this

It's on the 1.0 roadmap, so this should be addressed soon (especially since window restoring was added a few versions ago, but I'm not a member of the Atom team so I can't guarantee that).  Just because Atom is *almost* at 1.0 doesn't mean it *is* at 1.0.

**Comment by benogle** [comment]
We wont be able to get to this in the next couple weeks, but it is still on the list. It will have to go in after 1.0.

**Comment by alexandernst** [comment]
@benogle I'd say Atom's team should rather adapt the 1.0 release to the remaining critical tasks instead of the announced release date.

**Comment by benogle** [comment]
It's same same. If we declared 1.0 today or in 2 months, this would likely get done in the same time frame.

**Comment by alexandernst** [comment]
If the critical pre-1.0 tasks list is *that* big for you to say that (and exclude from it such a critical task), I think the team should seriously reconsider the release date.

**Comment by dejj** [comment]
+1 Heard of Atom.io today; amazed. First thing I try is killing it with unsaved changes; found this page; disappointed. Not switching from SublimeText. Maybe I'll be checking back in a few months.

**Comment by ivanmayes** [comment]
+1

**Comment by SpainTrain** [comment]
:+1: Agree on this being a critical feature for any serious text editor.  Assumed this was a feature and just lost some work due to Atom-unrelated system event.  sad :panda_face:

**Comment by mlms13** [comment]
:+1: Just lost an unsaved todo list when atom became unresponsive. Without it, I'm now aimless and confused.

**Comment by pareeohnos** [comment]
:+1: badly need this! I often (stupidly) keep a list of things I need to do in a new tab that I don't save given how temporary it is. Just had atom lock up due to a minified JS file having too long of a line (another bug I believe). It then prompted me to either keep waiting, or shut so I shut. When it returned, I lost my temporary files. This is a desperately needed feature!!

**Comment by Sogl** [comment]
+1 
need this!

**Comment by batjko** [comment]
@Sogl and all: Looks like this ticket is now on the roadmap for a quality improvement push (see #7995 as linked by @benogle).

No further +1s necessary ;)

**Comment by Eutropia** [comment]
was literally putting the finishing touches on a sonnet in fourteens for the love of my life and (surprise surprise) the mac crashes.  Then I found out atom doesn't have a temp file buffer.

**Comment by 1j01** [comment]
> No further +1s necessary ;)

but that issue was closed, so how about a
### This is the most important issue with Atom.
At *least* save things *somewhere* while you're editing them.

**Comment by 50Wliu** [comment]
Ok.  At this point there's not much constructive discussion happening, so I'm going to lock this issue.  Updates will still be posted here as they appear.  I'd also like to remind everyone that while the Quality Initiative may have ended, this issue is still open and is still on the post-1.0 roadmap.

**Comment by 50Wliu** [comment]
#10605 has been merged and at the current pace of development crash restore should be available in Atom 1.7.0! :sparkles:
