### ISSUE TITLE
Mac Atom Update infinite loop

### ISSUE THREAD

**Issue by kwatson** [atom/atom#4166]
Atom is unable to update itself -- it does the download and asks you to restart and update, but after doing so you notice that it's on the same version and it begins to download the update again.

It will continue to do this all day long...

Mac OS: Yosemite
Atom Version: 0.145.0

In looking at the logs, and in the directory of where the update is downloaded to, the updated app appears to be missing.

Here is the update error from my console:

![screen shot 2014-11-12 at 5 03 01 pm](https://cloud.githubusercontent.com/assets/47849/5021685/cd1b03ae-6a8d-11e4-9ee0-27e7a3f2b7a2.png)

A few notes about my environment: My user account does not have sudo/Admin privileges, so installing apps will always prompt me to authenticate with my 'admin' user -- I never get prompted by Atom, so if admin rights are required, then it should be prompting me. 

Thanks

**Comment by johnmichel** [comment]
I am also experiencing this behavior, with Atom being installed to `/Applications`.  I'd rather not move my installation to `~/Applications` if possible.

**Comment by mnquintana** [comment]
I think this is the same issue as https://github.com/atom/atom/issues/4166 – closing out in favor of that issue. Let me know if I'm misunderstanding though!

**Comment by johnmichel** [comment]
@mnquintana I don't think that you referenced the correct issue number in your last comment.

**Comment by mnquintana** [comment]
Haha talk about infinite loops... updated the issue number

**Comment by johnmichel** [comment]
:+1:
