### ISSUE TITLE
Implement Chromium task manager

### ISSUE THREAD

**Issue by swrobel** [atom/atom#4168]
Users frequently report issues with high CPU or memory usage, and the typical response is that it must be a package that is the root cause, not Atom itself. Presently, the operating system task managers just show a bunch of Atom Helper processes, so it is impossible to determine which package is associated with the offending process.

Since Atom is based on Chromium, it would be beneficial to implement the Chromium task manager so that a user can see resource usage by package. Here is what Chromium's task manager looks like:

![screen shot 2014-10-25 at 8 46 34 am](https://cloud.githubusercontent.com/assets/157270/5021790/eb491578-6a97-11e4-81b5-feb2330f2360.png)

**Comment by mybks** [comment]
@postcasio why atom is not using a process for each tab? as atom is blocking on some operations?

**Comment by swrobel** [comment]
Is it possible to make use of this new-ish Electron API? https://github.com/electron/electron/pull/5526

**Comment by stevencollinscn** [comment]
@swrobel I eventually give up Atom because of the high CPU usage you mention. It has been a couple of new versions released since I installed it and nothing seems improved over time. It takes more than 20 to 30 percent of CPU usage when I literally do nothing but just open it!

**Comment by Aerijo** [comment]
@stevencollinscn I understand you're not using Atom, but when you say

> It takes more than 20 to 30 percent of CPU usage when I literally do nothing but just open it!

Is that only at start up, or when idle (in foreground or background)? Because while it's still not desirable, a relatively higher usage when opening is to be expected, as it indexes files (`autocomplete-paths` is especially bad for this), indexes Git repos, and generally activates itself and packages.

**Comment by stevencollinscn** [comment]
I don't have that `autocomplete-paths` extension.
![image](https://user-images.githubusercontent.com/33796896/51746056-e319f300-2072-11e9-97af-ddb52de6b1c8.png)
I used to have a github for windows process that takes 10 to 20 percent cpu usage and then I disabled it.
![image](https://user-images.githubusercontent.com/33796896/51746211-502d8880-2073-11e9-8fbc-46736f0e9c8b.png)
The usage will drop if I don't interact with the Atom window (like simply click a tab or something), it will keep a high usage if I have a file open.

**Comment by michael-gracy** [comment]
I almost opened another ticket, but this is a match for my issue. I am experiencing the same symptoms.
Upon startup, depending if I have several windows each with a couple of tabs. I will have between 1-5 Helpers. Even with a single window with one tab, I have had 1-2 Helpers running, each taking 100+%, some of them spiking to nearly 300%. Yesterday I was noting extremely slow response to typing. Hit key....wait a few seconds...character is rendered.
I have a 2017 MBP with i7(8 core (yeahyeah, I know about hyperthreading),16GB ram and a 512GB ssd with plenty of space (osx high sierra).
I started Atom (1.[2|3]x.xx) in normal or safe mode and I get similar results of Helper claiming huge chunks of cpu time (1 core plus) for at least 45 seconds before Atom is useful. As soon as I open a directory in the left pane, everything slows to a crawl if there are numerous files sitting there (not being opened), this happens in normal and safe mode. I personally would love to drill down further and be able to give more pertinent information, but the tools just aren't there.

![Screen Shot 2019-03-13 at 11 44 33 AM](https://user-images.githubusercontent.com/21319707/54310992-ecaeda00-4590-11e9-89fe-34a441f14735.png)
![Screen Shot 2019-03-13 at 11 59 37 AM](https://user-images.githubusercontent.com/21319707/54310993-ecaeda00-4590-11e9-9d9a-707346c7d4f1.png)
![Screen Shot 2019-03-13 at 11 58 37 AM](https://user-images.githubusercontent.com/21319707/54310995-ed477080-4590-11e9-82f3-1a4b595373fd.png)
![Screen Shot 2019-03-13 at 11 56 54 AM](https://user-images.githubusercontent.com/21319707/54310997-ed477080-4590-11e9-83d0-fa76afce05d6.png)
