### ISSUE TITLE
You should auto save the content when crash

### ISSUE THREAD

**Issue by answer1989** [atom/atom#4172]
Today I use atom to write my blog,  but suddenly it crash, when I reopen it, I cannot find the content, it is so bad because it cost me a lot time to write the blog. I'm so sad for this, please fix it.

Atom version: 0.144.0
Mac version: OS X Yosemite 10.10 (14A389)
Reason I guess: Maybe I add about six image at it, I was writting markdown, is it cause of memory?

**Comment by benogle** [comment]
Closing in favor of #4161
