### ISSUE TITLE
editor:will-be-removed appears in command palette

### ISSUE THREAD

**Issue by postcasio** [atom/atom#4187]
Atom 0.146.0, when working on a project with a git repository, the command palette will contain the `editor:will-be-removed` event. If the project has no repo, it doesn't seem to appear.

![screen shot 2014-11-14 at 14 05 50](https://cloud.githubusercontent.com/assets/1759837/5047896/73d2a7cc-6c11-11e4-9cc3-3c46d72983e9.png)

Steps to reproduce:

```shell
$ git init
$ atom --safe .
```
* `cmd-n` to open a new editor.
* `cmd-shift-p` to open the palette and search for `will be removed`.

**Comment by kevinsawicki** [comment]
Closing this since this was removed in the Atom 1.0 API and so the command is no longer visible in the command palette.
