### ISSUE TITLE
After copying with multiple selections, TextEditor::pasteText skips '{did,will}-insert-text' events

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#4190]
`TextEditor::pasteText` calls `insertText` directly on selections when clipboard metadata contains multiple selections. This bypasses said events.

https://github.com/atom/atom/blob/master/src/text-editor.coffee#L2499

**Comment by jacekkopecky** [comment]
This affects the performance of replace mode in the vim-mode package (to be PRd shortly).

**Comment by izuzak** [comment]
@maxbrunsfeld I _think_ this was fixed in https://github.com/atom/atom/pull/7748 and https://github.com/atom/atom/pull/8105. Is it okay to close this or is there more to do here?

**Comment by maxbrunsfeld** [comment]
@izuzak :+1: Thanks!
