### ISSUE TITLE
Bug when starting editor under certain conditions

### ISSUE THREAD

**Issue by ericwhyne** [atom/atom#4199]
When I closed the editor I had a file open in a tab. It was named "summarize". 
With the editor closed I ended up having to do some restructuring of the project folder and this file was moved into a directory called "summarize" under a different name.
Later in the day I tried to start up Atom again, it failed to the debug screen. It was throwing an error saying that this file was now a directory. I ended up having to rename the directory temporarily to be able to open the editor, then close the tab in the editor, rename the directory again to it's original name and all was well.
Suggestion: the editor should fail more gracefully in this circumstance. When a directory replaces a file of the same name, the editor should just close the tab or gray it out with an explanation or alert.

**Comment by nathansobo** [comment]
:zap:
