### ISSUE TITLE
Reload causes cursor/selection misalignment (for @font-face fonts)

### ISSUE THREAD

**Issue by braver** [atom/atom#4200]
Possibly related to #3201, if you have fonts loaded through `@font-face` (e.g. using my fonts package), a reload causes the cursor/selection alignment to misbehave. Switching to the default font (i.e. empty the font family box in settings) restores it. You can then switch back to an `@font-face` font and it will work properly again.

Steps to reproduce:
- Use an `@font-face` font as outlined here: https://discuss.atom.io/t/how-do-i-load-google-fonts-into-my-editors-styles/8321/7 (or by using http://atom.io/packages/fonts).
- Put the name of the font in settings (e.g. 'aka-coder').
- Open a file in Atom: all should look well in the new font.
- Choose View > Reload.
- Cursor and selection should now misalign. You can check this by double-click-selecting a word or by typing a row of characters.
- Switch to settings.
- Empty the font-family setting.
- Switch to the file and all should look well again in the default font.
- Switch to settings. 
- Put the name of the font in settings (e.g. 'aka-coder').
- Switch to the file and all should look well again in aka-coder.

**Comment by coopermaruyama** [comment]
Hi just an FYI I experienced this in my theme and have worked around it as follows:

```coffee
class MyClass
  constructor: ->
    atom.workspace.observeTextEditors (editor) =>
      editorView = atom.views.getview editor
      @remeasureCharacters editor

  remeasureCharacters: (editor) ->
    if editor?
      @viewDisposables.add editor?.onDidChangeCursorPosition (event) =>
        editorView = atom.views.getView?(event.cursor.editor)
        editorView.component?.linesComponent?.remeasureCharacterWidths?()
        editorView.component?.remeasureCharacterWidths?()
        @viewDisposables?.dispose()
```
