### ISSUE TITLE
Consider bundling default font

### ISSUE THREAD

**Issue by wutong** [atom/atom#4201]
wish u addon Noto fonts to editor and support laravel syntax hints and highlights

**Comment by mnquintana** [comment]
I updated the title to better reflect what it seemed like you were asking for @wutong – does it look alright to you?

I think shipping with a default font is probably a good idea, especially for Linux, since some distros might not have great default monospace fonts. Especially since @simurai has started using it for some screenshots (and it looks awesome), I'd be a big fan of bundling [Fira Mono](http://mozilla.github.io/Fira/). It's also an [open source font](https://github.com/mozilla/Fira), so we should be good for licensing (as long as we include the license).

/cc @atom/non-github-maintainers

**Comment by lee-dohm** [comment]
:+1: I think this would just save us a lot of headache as far as fonts on Linux go.

**Comment by paulcbetts** [comment]
Droid Sans Mono also seems to look (generally) pretty good on all three operating systems

**Comment by mnquintana** [comment]
@paulcbetts Droid Sans Mono seems to only have one weight though :confused:

**Comment by paulcbetts** [comment]
@mnquintana Legit

**Comment by simurai** [comment]
Somehow I just liked the unique `@` in Fira Mono.

There is the [Fonts](https://atom.io/packages/fonts) package if you wanna try out some fonts. Here my 3 favs:

- Fira Mono -> Used in Firefox OS.
- DejaVu Mono
- Source Code Pro -> Used in Brackets.

![fonts](https://cloud.githubusercontent.com/assets/378023/7362401/35817cb4-eda3-11e4-802e-91e2b5548532.gif)

**Comment by mark-hahn** [comment]
+1 for Source Code Pro.

**Comment by lee-dohm** [comment]
Actually, if people were looking for a comprehensive list, [this one](http://programmingfonts.org/list) was pointed out in [this topic on Discuss](https://discuss.atom.io/t/hebrew-not-showing-in-0-190-on-ubuntu/16035).

And something to keep in mind. If we package a "default font", we might want to be sure that it doesn't override the font that people already have set. We don't want to [surprise people negatively](https://discuss.atom.io/t/you-changed-my-theme-when-i-wasnt-looking/15731).

**Comment by simurai** [comment]
> If we package a "default font", we might want to be sure that it doesn't override the font that people already have set.

Right, the font-family set in the settings should still have priority over the bundled one.

**Comment by simurai** [comment]
> If we package a "default font", we might want to be sure that it doesn't override the font that people already have set.

Actually.. the current default is set like [this](https://github.com/atom/atom/blob/master/static/text-editor-light.less#L7):

```css
font-family: Inconsolata, Monaco, Consolas, 'Courier New', Courier;
```

Meaning first it will try to use `Inconsolata` and if that font is not installed on the system, it will move on to `Monaco` then `Consolas` etc. So if we bundle a default font, people that have not entered a font in the settings will get the new default and that will cause another "negative surprise".

Not sure if there is a way around this? Soo..

1. Either we ship a new default pre `1.0` and ask for forgiveness. :bow: 
2. Or keep as is and wait till `2.0`.

**Comment by mnquintana** [comment]
> Either we ship a new default pre 1.0 and ask for forgiveness. :bow:

Wellll... pre-1.0 is the time for breaking changes if there ever was one :grin: - it's true that Atom's been out long enough now that people have grown attached to certain settings and defaults, but that will only become more true the longer we wait to do something like this. I think if we do do this, then we should probably publish a blog post announcing the change to make it more transparent.

**Comment by mnquintana** [comment]
Also as for Source Code Pro, even though I like it, since it's Brackets' default font (and Adobe's font at that), I think we should go for something else to help give Atom a more unique identity.

**Comment by simurai** [comment]
If we can agree on a better default, then maybe it's ok to change it. :innocent: But yeah, that's subjective.

Just in case.. based on [this](http://fontfamily.io), currently if you don't have `Inconsolata` installed you should get this:

- OS X: `Monaco`
- Win: `Consolas`
- Linux: `Courier New`

So we could at least do this:

```css
font-family: Inconsolata, Monaco, Consolas, [Better default font for Linux], 'Courier New', Courier;
```

Then people on OS X and Win shouldn't see a change, and for Linux it replaces `Courier New`.

**Comment by fvsch** [comment]
About the Linux default: `DejaVu Sans Mono` is a good solution.

When working on Linux I was using DejaVu Sans Mono for all monospace needs. It is closer in style and readability to the likes of Monaco or Consolas than to the (often smallish and hard to read) Courier New.

Years ago, DejaVu Sans Mono was not always installed on distros, and several had the older Bitstream Vera Sans Mono (which the DejaVu fonts are based on). That was before 2010 though, and it seems that nowadays most distros bundle the DejaVu fonts instead (or in addition), according to [Wikipedia](https://en.wikipedia.org/wiki/DejaVu_fonts) and to [fontfamily.io](http://fontfamily.io/dejavu_sans_mono,monospace).

**Comment by nathco** [comment]
Have a look at the new [Office Code Pro](https://github.com/nathco/Office-Code-Pro) fonts…

**Comment by lee-dohm** [comment]
> Not sure if there is a way around this? Soo..
>
> 1. Either we ship a new default pre 1.0 and ask for forgiveness. :bow:
> 1. Or keep as is and wait till 2.0.

Or we could:

1. Package a new default font, but not activate it by leaving it out of the font-family declaration for now
1. Let people know by blog post that it is there for anyone who wants it
1. Let people know that it will be added as a new default for Linux at some point in the future

**Comment by Zireael07** [comment]
I like Droid Sans, but if it can't be the default due to some issues, I cast my vote for Source Code/Office Code Pro.

**Comment by mnquintana** [comment]
@nathco Awesome! What did you change compared to Source Code Pro? It looks like the characters might be taller but I'm not sure what else.

@simurai Do you think we should have separate default fonts for each system instead of a bundled default font?

**Comment by nathco** [comment]
@mnquintana check out the **Release Notes** section near the bottom of the [README.md](https://github.com/nathco/Office-Code-Pro/blob/master/README.md)

**Comment by simurai** [comment]
@nathco `Office Code Pro` looks nice. Thanks for point that out.

> 1. Package a new default font, but not activate it by leaving it out of the font-family declaration for now
2. Let people know by blog post that it is there for anyone who wants it
3. Let people know that it will be added as a new default for Linux at some point in the future

Hmm.. I feel like if we only change it for Linux, then we should go with @fvsch's suggestion and just add `DejaVu Sans Mono` to Atom's font stack without bundling a new font. Made a PR for that: #6567. That hopefully fixes the "Linux issues".

**Comment by simurai** [comment]
FYI: #6567 is now in master and we decided to leave it at that.. for now.

Bundling a default font is still a good idea, but since it would change the font that some people currently use, it would be quite intrusive. If we ever do it, then only if there are more visually breaking changes and we can do it all at once.
