### ISSUE TITLE
Ubuntu 14.04 64bits BufferedNodeProcess failed

### ISSUE THREAD

**Issue by me6iaton** [atom/atom#4226]
Hi, this error
` kernel: [83655.735990] atom[19273]: segfault at 0 ip 00007ffff439717d sp 00007fffffffb2f0 error 4 in libchromiumcontent.so[7ffff2145000+447b000]`
 written in syslog when i call child_process.spawn or  BufferedNodeProcess and write to file. Child_process exit whith code null. 
Atom 0.147, ubuntu 14.04  
I don't  know  how I can get gdb  stack traces to  child_process, do I need edit source code for this?

**Comment by kevinsawicki** [comment]
I'm going to optimistically close this out since we've upgrade node and Chromium versions a bunch since November and we haven't got any recent reports of this. Please comment if you still see this happening on Atom 1.0.3+, thanks.
