### ISSUE TITLE
Failure to install packages on Ubuntu due to node

### ISSUE THREAD

**Issue by karloluis** [atom/atom#4236]
Using Ubuntu 14.04 and apt-get to install utilities is causing problems to install and update packages for atom. This is due to ubuntu maintainers not updating regularly to the latest versions in a timely manner. As of this post the nodejs package is on 10.25 when the latest and atom used is the 10.33. Although npm also has similar issues from time to time I am only concerned for nodejs as of now. If it is at all possible to manage atom packages using nodejs 10.25+ it would facilitate linux users access.

**Comment by kevinsawicki** [comment]
apm ships with its own version of node so this shouldn't be an issue I believe, closing it out.
