### ISSUE TITLE
`Shift` key breaks multikey bindings on Linux

### ISSUE THREAD

**Issue by autochthe** [atom/atom#4254]
If you press `<shift>` during a multikey binding, the keybinding is unable to resolve.  To demonstrate, here are the results in Atom 0.147.0 on Ubuntu Linux 14.04 x86-64.

In dev tools, do:
```
atom.keymaps.add("test", {"body": {"o P": "core:confirm" }})
```

Keybinding resolver output:

`o`:
![image](https://cloud.githubusercontent.com/assets/333673/5119915/be6c93ca-703e-11e4-8f79-0e109e0c4dc8.png)

`o<shift-down>`:
![image](https://cloud.githubusercontent.com/assets/333673/5119922/e4f022dc-703e-11e4-9d51-075f5dcf92c5.png)

`o<shift-down>p`:
![image](https://cloud.githubusercontent.com/assets/333673/5119935/212d72d6-703f-11e4-940d-d5c7e3b07a37.png)

Also tried another keybinding `O P`:

This works. `<shift-down>op<shift-up>`:
![image](https://cloud.githubusercontent.com/assets/333673/5119963/70ea2b3e-703f-11e4-816e-cf18259332fe.png)

However, if I released shift and pressed it again, then once again, the keybinding would fail to resolve. When I tested a third keybinding, `O p`, I found that it always succeeded, unless I pressed shift at some point before typing `p`.

This seems to indicate that the `<shift-down>` event is breaking multikey bindings.

See also atom/vim-mode#442

**Comment by nesmyslny** [comment]
:+1: I'm also affected (using Atom 0.174.0 on Arch x86-64). A fix would be awesome :)

**Comment by nesmyslny** [comment]
Just want to let you know, that this issue is fixed (at least in my case). I'm using 0.182.0, but skipped 180 and 181. Version 0.180.0 included a fix regarding key bindings, so maybe that also fixed this issue.

@autochthe Can you confirm, that the issue is fixed?

**Comment by autochthe** [comment]
I just tested this in 0.182.0.  The issue seems to have been fixed with the update.
