### ISSUE TITLE
"Open Changelog" / "Open README" buttons stay visible

### ISSUE THREAD

**Issue by Bengt** [atom/atom#4261]
When I click the "Open Changelog" button of a package in the settings view, it sometimes stays visible. I can even click the button repeatedly. Also, the tab does not get changed somehow. When there is an open tab containing the changelog, everything works as expected.

![bildschirmfoto von 2014-11-20 20 21 48](https://cloud.githubusercontent.com/assets/11575/5131699/be1a47a2-70f5-11e4-821d-4699f9d1286e.png)

atom -v 0.149.0-46ff794
apm -v 0.111.0
uname -r 3.17.2-200.fc20.x86_64

**Comment by mnquintana** [comment]
@Bengt Are you still seeing this with the latest version of Atom (0.192.0)?

**Comment by mnquintana** [comment]
Gonna close this out - please feel free to comment / reopen if you're still experiencing this with the latest version of Atom in safe mode.
