### ISSUE TITLE
"Project Find" -> "Replace All" breaks encoding sometimes

### ISSUE THREAD

**Issue by UdjinM6** [atom/atom#4268]
Example:
- clone https://github.com/bitcoin/bitcoin
- cmd + shift + f
- fill
  - 8333
  - 2222
  - *ru.ts
- hit "Replace All" and you'll get not only changes that you expected but also this (I did a cut from "git diff" to illustrate it better)

```
-        <translation>Промежуток от:</translation>
+        <translation>Промежуток ��т:</translation>

-        <translation>Не удалось записать информацию файла</translation>
+        <translation>Не удалось записать ин��ормацию файла</translation>
```

Atom 0.150.0
Mac OS 10.10

**Comment by benogle** [comment]
What encoding are you using?

**Comment by UdjinM6** [comment]
It's utf-8 I believe. And it not just *ru.ts, you can try *.ts to reproduce it for other languages. Also please note that bitcoin source changed since then so you will also need ```git checkout 0.9``` to switch to the old branch in order to reproduce exactly the same case.

Reproduced again with Atom 1.0.2 on MacOS 10.10.3

**Comment by Uninen** [comment]
I found this same bug while opening old files in ISO 8859-1, and trying to search & replace content in them. A file that has been opened in the project is ok, all other files end up mangled.

**Comment by exse2** [comment]
If you have .editorconfig file with these two lines:
[*]
charset = iso88591

Then do a "Replace All", not only it replaces all, but it also mangles German Umlauts (e.g. äöü). I suppose it does not convert the file back to this encoding after doing the replace internally. In short: The find-replace does not give a crap about .editorconfig.

**Comment by gtsop** [comment]
Same issue here. I have a project with files in ISO-8859-7 encoding. Find-replace-all ruins the greek letters.

**Comment by 50Wliu** [comment]
This issue was moved to atom/find-and-replace#945
