### ISSUE TITLE
Cannot update or view packages in preferences window: tunneling socket errors

### ISSUE THREAD

**Issue by jackmaney** [atom/atom#4278]
I'm running OS X Mavericks with Atom 0.150.0 behind a corporate firewall. My (anonymized) `.apmrc` is as follows:

```
https-proxy = https://[user]:[pw]@[host]:[port]
http-proxy = http://[user]:[pw]@[host]:[port]
proxy = http://[user]:[pw]@[host]:[port]
strict-ssl = false
```

Fetching outdated packages and themes fails with this error message:

```
Request for package information failed: tunneling socket could not be established, cause=140735230071568:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:795:
```

Fetching featured packages fails with this error message:

```
tunneling socket could not be established, cause=140735230071568:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:795:
```

Googling and further searching doesn't seem to bring up anything immediately relevant and helpful. I'd really like to use Atom as my primary text editor, but I have no idea how to get past these issues. Thank you in advance for your time and help.

**Comment by kanikashridhar** [comment]
changing https to http worked for me too !! Thanks :+1:

**Comment by Prabhnith** [comment]
Request for package information failed: tunneling socket could not be established, cause=140358160631680:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:
 (5 attempts) (ECONNRESET)
