### ISSUE TITLE
How to deal with unused config settings

### ISSUE THREAD

**Issue by dmnd** [atom/atom#4292]
I'm changing what used to a a number of different boolean configs into an enum with the new config API. It works great, except users that have a non-default setting in their config.cson see the now unused config option in package settings. It makes the package settings confusing because options are present that no longer work. 

 1. Is there any way to remove the setting beyond asking the user to manually remove it from their config?
 2. If there's a reason not to remove it (messing with people's configs might be annoying), can we hide the unused setting, or give it some other visual treatment that indicates that it is not in use?

**Comment by benogle** [comment]
This has changed to [unset](https://atom.io/docs/api/v0.174.0/Config#instance-unset).
