### ISSUE TITLE
boom!!!  Here is a hack solution to make atom start faster.

### ISSUE THREAD

**Issue by yongkangchen** [atom/atom#4293]
After discuss in [why-is-atom-so-slow](https://discuss.atom.io/t/why-is-atom-so-slow/11376/50), I pull a request `Better user experience for start atom`: https://github.com/atom/atom/pull/4269.

Today, I do a deep review the atom source code, and find a hack solution to make atom start faster:
this is the final modify screen video demo:
https://drive.google.com/file/d/0B8i7zRr2bfCAV0NoeG50dURMaW8/view?usp=sharing

## What It Is
It delay the config file load, and the packages load and active, which cost much time on start.
After change, atom only load and active the must packages on start, which is ui theme、syntax theme、tabs、status-bar、tree-view.
Then delay to load and active other package. Window and mainly package will show quickly.

## How To Do:
1、open atom.js
for mac: `/Applications/Atom.app/Contents/Resources/app/src/atom.js`
for win8:
```
C:\ProgramData\chocolatey\lib\Atom.{replace to atom version}\tools\Atom\resources\app\src\atom.js  
````
2、replace the below function `Atom.prototype.startEditorWindow`
3、you can test and change the setTimeout time to adapt your computer.
4、notice that you should modify atom.js again after you update the atom.
```
    Atom.prototype.startEditorWindow = function() {
      var CommandInstaller, dimensions, maximize, resourcePath, safeMode, _ref;
      _ref = this.getLoadSettings(), resourcePath = _ref.resourcePath, safeMode = _ref.safeMode;
      CommandInstaller = require('./command-installer');
      CommandInstaller.installAtomCommand(resourcePath, false, function(error) {
        if (error != null) {
          return console.warn(error.message);
        }
      });
      CommandInstaller.installApmCommand(resourcePath, false, function(error) {
        if (error != null) {
          return console.warn(error.message);
        }
      });
      dimensions = this.restoreWindowDimensions();
      // this.loadConfig();    
      this.themes.loadBaseStylesheets();
      this.keymaps.loadBundledKeymaps();

      setImmediate((function(_this) {
        return function() {
          _this.themes.activatePackages();
          _this.packages.activatePackage("tabs");
          _this.packages.activatePackage("status-bar");
          _this.packages.activatePackage("tree-view");
          
          _this.loadConfig();
          setTimeout(function(){
            _this.packages.loadPackages();
            _this.packages.activate();
            if (!safeMode) {
              _this.requireUserInitScript();
            }
            _this.subscribe(_this.config.onDidChange('core.autoHideMenuBar', (function(_this) {
              return function(_arg) {
                var newValue;
                newValue = _arg.newValue;
                return _this.setAutoHideMenuBar(newValue);
              };
            })(_this)));
            if (_this.config.get('core.autoHideMenuBar')) {
              _this.setAutoHideMenuBar(true);
            }
          }, 300); //NOTE: here can change
        };
      })(this));

      // this.packages.loadPackages();
      this.deserializeEditorWindow();
      this.watchProjectPath();
      // this.packages.activate();
      this.keymaps.loadUserKeymap();
      // if (!safeMode) {
      //   this.requireUserInitScript();
      // }
      this.menu.update();
      // this.subscribe(this.config.onDidChange('core.autoHideMenuBar', (function(_this) {
      //   return function(_arg) {
      //     var newValue;
      //     newValue = _arg.newValue;
      //     return _this.setAutoHideMenuBar(newValue);
      //   };
      // })(this)));
      // if (this.config.get('core.autoHideMenuBar')) {
      //   this.setAutoHideMenuBar(true);
      // }
      maximize = (dimensions != null ? dimensions.maximized : void 0) && process.platform !== 'darwin';
      return this.displayWindow({
        maximize: maximize
      });
    };
```

**Comment by MartinLichtblau** [comment]
Thx!
But why is Atom loading the whole recursive file structure if I click only on one file, that's a big waste of performance.

**Comment by aly006** [comment]
helped me out greatly, thank you.

**Comment by Nijikokun** [comment]
@kevinsawicki ?

**Comment by lmartins** [comment]
Thank you, this does improve things for me too.

**Comment by patrickgilmour** [comment]
Dramatically faster on MacBook Air (2011) with 1.8 GHz Intel Core i7 - thanks!

**Comment by yongkangchen** [comment]
Since v0.193.0: `Atom now ships its main code bundle as an asar archive file`, so this hack will only work before v0.193.0, have not find how to hack asar file.

And good news with atom v0.199.0: `Opening editors is now significantly faster than previously releases`.

**Comment by orliesaurus** [comment]
it's still quite slow compared to Sublime, but thanks for putting this in the new release :)

**Comment by OwenMelbz** [comment]
Is this fix still relevant in the latest releases? Or are there any mods that replicate the deferred loading?

**Comment by cscuderi** [comment]
I came here wondering the same thing as @OwenMelbz. Is this still relevant?

**Comment by rnarian** [comment]
@OwenMelbz @cscuderi Apparently not: https://github.com/atom/atom/issues/4293#issuecomment-102284752 :disappointed:

**Comment by JosueB** [comment]
Anyone tried doing this on windows 7? I found the atom.js file but it only has the following. 

```
var path  = require('path');
var spawn = require('child_process').spawn;

var atomCommandPath = path.resolve(__dirname, '..', '..', 'atom.exe');
var arguments = process.argv.slice(2);
arguments.unshift('--executed-from', process.cwd());
var options = {detached: true, stdio: 'ignore'};
spawn(atomCommandPath, arguments, options);
process.exit(0);
```

**Comment by yogeshnikam** [comment]
I am also getting the above one. for windows 7

**Comment by yogeshnikam** [comment]
Can any one tell me how to increase the speed for windows 7 using the below code,
var path  = require('path');
var spawn = require('child_process').spawn;

var atomCommandPath = path.resolve(__dirname, '..', '..', 'atom.exe');
var arguments = process.argv.slice(2);
arguments.unshift('--executed-from', process.cwd());
var options = {detached: true, stdio: 'ignore'};
spawn(atomCommandPath, arguments, options);
process.exit(0);

**Comment by VentGrey** [comment]
D: how about Linux users? config is not the same :(

**Comment by KJReid** [comment]
+1 for Linux support if possible. Great work on this!

**Comment by Just4Ease** [comment]
Can't find the config for Ubuntu.

**Comment by csvan** [comment]
I hate to be negative, but it's been almost 3 years since this (great!) hack was published, and Atom is still impossibly slow. IntelliJ IDEA literally starts faster for me. Will , despite being an entire (Java based!) IDE. Will this ever be fixed?

**Comment by 50Wliu** [comment]
@csvan Atom 1.17.0, currently in beta, improves startup performance by around 50%.
http://blog.atom.io/2017/04/18/improving-startup-time.html

**Comment by seanfuture** [comment]
That's nice @50Wliu - However it's still very slow relatively speaking ( not going to name competition ) as of 1.18.0.  So please keep up the work on improving the start time - Thank you

**Comment by 50Wliu** [comment]
Yeah, we're aware - future improvements are detailed at the bottom of the blog post.

**Comment by mittalyashu** [comment]
Why don't developers of the Atom re-develop the software in C++ and Python (just like sublime text) to make it faster?

**Comment by tommywalkie** [comment]
"Why don't developers just re-develop their app in several different languages ? They are so lazy." ( ͡° ͜ʖ ͡°)

**Comment by ishanray** [comment]
its still slow as of 1.21.1

**Comment by acrolink** [comment]
Which language Atom is written in?

**Comment by OwenMelbz** [comment]
@acrolink English

**Comment by acrolink** [comment]
@OwenMelbz , question edited.

**Comment by mittalyashu** [comment]
It is written in Javascript and CSS.
![image](https://user-images.githubusercontent.com/29014463/31718842-f0f6dbc0-b42e-11e7-8baf-51b0fe06bd70.png)

**Comment by OwenMelbz** [comment]
Although it’s basically a glorified chrome plugin, so the actual underlying system is most likely in some sort of C derivative

**Comment by logankratos61** [comment]
for windows 10???
