### ISSUE TITLE
Weird display artifact in the tab strip

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#4297]
<h1>Steps to reproduce:</h1>
1. `atom --safe`
2. Open a folder
3. Open a file
4. Open Settings (doesn't look like I can reproduce this using a normal file)
5. Close one of the two files (aka not Settings)
6. Notice that there's a weird artifact left where the Settings tab was (before you closed the file)

Can be fixed simply by switching or closing a tab (including Settings).

Atom 0.150.0, Windows 7 x64.  This has been happening since way back, but I just got around to testing it in safe mode.

Two files open:
![step1](https://cloud.githubusercontent.com/assets/2766036/5159245/6db8bde2-732b-11e4-8ded-844635e698d9.png)

File closed:
![step2](https://cloud.githubusercontent.com/assets/2766036/5159246/6f6c4bb8-732b-11e4-8ac1-aeac5fc073c3.png)

**Comment by jimgraham** [comment]
I could reproduce this on 0.165 on Windows 7 x64 sp1, in safe mode, but only with the UI Theme = Atom Light. With the Atom Dark UI Theme there was no tab strip remnant.

**Comment by 50Wliu** [comment]
I think I also got this again on Ubuntu a few days back.

**Comment by jimgraham** [comment]
This is seems to be fixed on Windows with Atom 0.169

**Comment by lee-dohm** [comment]
@50Wliu are you ok with me closing this since it seems to be fixed for Windows? We can always reopen it if you get a repro for Linux.

**Comment by 50Wliu** [comment]
Seems fine to me.  I haven't been on Windows for a while (after nearly breaking it), so I'll assume that @jimgraham's right.
