### ISSUE TITLE
Make programmatic scrolling more transitional and less jumpy

### ISSUE THREAD

**Issue by ilanbiala** [atom/atom#4308]
The autoscroll option for many programmatic methods right now is way too jumpy and really negatively impacts UX. It would be nice to be able to say `.setBufferPosition(position, { autoscroll: true, transitionDuration: '0.5s', transitionTiming: 'ease' })` or something similar that will provide developers a way to transition the editor how they see fit. If the transition duration and timing aren't provided, then fall back to a nice `'0.3s'` and `'ease'` or something like that.

**Comment by ilanbiala** [comment]
@benogle @kevinsawicki any progress on this?

**Comment by thomasjo** [comment]
@ilanbiala I suggest you open a PR for this. I'm sure the core team and other folks like myself would be happy to provide guidance etc.

**Comment by ilanbiala** [comment]
@thomasjo I'm not really sure what would be involved. The easiest thing I can think of is an implementation like this:
```
var scrollAmount = 300; // let's just use this as a simulation, but in reality we'll have to get this px value
var timeToScroll = 0.2; // Assume 60 FPS

console.time('Starting scroll');

function transitionalScroll() {
  if (window.scrollY < scrollAmount) {
    window.scrollBy(0, scrollAmount / (timeToScroll * 60)); // scroll, in this case 300 / (0.2 * 60) = 25px
    requestAnimationFrame(transitionalScroll); // repeat
  } else {
    console.timeEnd('Starting scroll');
  }
}

requestAnimationFrame(transitionalScroll);
```

Not sure how to implement that though, and it would be great if you guys could define some sort of requirements for this spec.
