### ISSUE TITLE
Improved "Show Invisibles"

### ISSUE THREAD

**Issue by phortx** [atom/atom#4311]
I'm not a big fan of eclipse, but regarding the "show invisibles" feature, it provides some realy nice configuration:
- changing the opacity of the invisible chars
- specify which type of chars to display (tabs, spaces, line endings etc)
- specify which type chars to display depending on their position (leading, enclosed, trailing)

That's awesome, since I like to reduce the opacity and hide the line endings, enclosed whitespace and stuff (I just want to see the the leading whitespace type with a low opacity).

It would be awesome to have similar options in atom.

![invisibles](https://cloud.githubusercontent.com/assets/107634/5183318/0e366e44-74ae-11e4-8f6c-1d2274129f8d.png)

**Comment by izuzak** [comment]
:link: https://github.com/atom/atom/issues/1634 which requests an option to control leading and trailing invisibles separately.
