### ISSUE TITLE
Installing atom without sudo privilidges

### ISSUE THREAD

**Issue by franciscovargas** [atom/atom#4330]
When atempting to compile atom from source on a university machine without user privilidges tons of access errors occur (1. the npm version is not 1.4 and compiling a local  node + running from that does not work). Is there a way to just obtain a compiled form to run ? for example sublime is easy to install without user prvilidges. Can this be added ?

**Comment by mizzoji** [comment]
@franciscovargas 
Could you solve this issue? I am facing the same problem with the dependencies ..older gcc version, no electron, node, npm etc and no Sudo :(
