### ISSUE TITLE
Font size too small in the settings GUI.

### ISSUE THREAD

**Issue by dcarrera** [atom/atom#4342]
As other people have reported, Atom comes with a small font size can only be fixed by editing config files (see #3792). I had the same problem with the Settings GUI. Unfortunately, this is very difficult to fix by editing `styles.less`. In particular, you cannot simply change `@font-size` in your local `styles.less` file. To make Atom usable for me, I had to locate my Atom installation, locate my theme, locate `ui-variables.less` and edit `@font-size` there directly. I still have not managed to get the check buttons to have a reasonable font size.

Clearly, fixing the font size is far more difficult than it should be. I ask that you add the UI font size and font family to the settings menu so that people can change them easily.

**Comment by thiago-om** [comment]
What worked for me was changing @font-size in  
Atom.app ▸ Contents ▸ Resources ▸ app ▸ node_modules ▸ atom-dark-ui ▸ styles ▸ ui-variables.less

**Comment by simurai** [comment]
@thiago-om Right, that somewhat works, but AFAIK, once the theme gets updated it will override your change again. So it's probably a bit annoying having to keep changing it after every update.

I still hope that someday it's possible to change it in the settings.

**Comment by simurai** [comment]
Ok, the `font-size` of the settings can ~~now~~ (in the next release) be changed with

```less
// in styles.less
.settings-view { font-size: 12px; }
```

**Note:** Not everything scales, controls like buttons and text inputs still stay the same. But at least you can change the titles, descriptions etc.

**Comment by thiagodebastos** [comment]
Great thank you :+1: ! More apps need to do this, one of the downsides of high-res screens :(

**Comment by matanster** [comment]
I wonder why this isn't a first class option in the settings tab.... or is it?

**Comment by zaindaniyal** [comment]
How can I change the font size of the search bar text? Any easy code for that?

**Comment by chharvey** [comment]
What do I do if the font size is too small for some instances of the editor but not for others? For example the font size is too small when I open `folder1` with Atom, but not when I open `folder2`. The stylesheet is the same for both instances.

**Comment by simurai** [comment]
> @chharvey  For example the font size is too small when I open `folder1` with Atom, but not when I open `folder2`.

The font size should be the same, regardless of which project (`folder1` or `folder2`) you open.

What theme are you using? The font size around the code is set by the theme and can't be changed easily. But some themes allow to change it in the theme settings.

**Comment by chharvey** [comment]
@simurai I agree, the font size should be the same, however that is not the case I am observing.

I'm using Atom v1.7.4 on OS X 10.10.5. I'm using the **One Dark** UI theme and **Solarized Dark** syntax theme.

I open `folder1` in Atom (either by drag-dropping the folder from Finder to Atom in the dock, or by using the command `$ atom folder1`). I also open `folder2` using either method. When I compare Atom windows, the UI components in one window have a larger font size than in the other window.

**Comment by simurai** [comment]
@chharvey Oh.. I see. The `Font Size: Auto` setting in the One theme changes the font size automatically based on **how big** the window is. You can set it to a fixed size so that is doesn't change anymore. Or if you prefer to **only** change the settings, but not the rest of the UI, you could add the following to your `styles.less` file:

```css
.theme-one-dark-ui .settings-view {
  font-size: 14px;
}
```

I'll add a note to that setting to make the auto feature more clear. Thanks for pointing that out. 🙇

**Comment by chharvey** [comment]
@simurai that explains a lot, thank you. i think the easiest solution is to resize the window :wink:

**Comment by sdayers** [comment]
Still no solution. I can auto-hid the "menubar" as it's referred to, but there doesn't seem to be any option to make it viewable (or usable) in the UI or config files.
