### ISSUE TITLE
Editor blank on startup intermittently

### ISSUE THREAD

**Issue by jakepark** [atom/atom#4351]
Upon startup, Atom goes into a whitescreen dev mode type of environment. After closing and reopening, the IDE interface appears. Not sure if this is by design. Windows 7 64-bit, atom v0.146

**Comment by brunorios1** [comment]
Same here: 
![image](https://cloud.githubusercontent.com/assets/954184/7812938/fb916bcc-038c-11e5-98e1-7f18e6490ef9.png)

**Comment by kevinsawicki** [comment]
I believe this issue has been fixed via several changes to electron, bundling the app in an asar bundle, and better handling of startup errors.

So I'm going to close this out but please comment back if you still see it happening on Atom 1.0+.

**Comment by zaheer9869** [comment]
It happened to me as well, uninstalling and reinstalling didn't solve it.

I believe it happened after I opened a filed (don't remember which one) and then after every time I tried to start atom, it tried to load it.

Solution was to delete 
%userprofile%\AppData\Roaming\Atom

not sure why uninstall doesn't clear it.

**Comment by guptadivyansh** [comment]
Problem persists in atom 1.6.0

`$ atom` or `$ atom --safe`
![screenshot from 2016-03-22 04 31 21](https://cloud.githubusercontent.com/assets/9139390/13936899/0cf73148-efe7-11e5-8824-0a77cdb99346.png)

`$ atom --version`
`1.6.0`

**Comment by 50Wliu** [comment]
@guptadivyansh Your issue is most likely #10819.

**Comment by guptadivyansh** [comment]
@50Wliu Thanks! 

Downgraded atom to get it to work

**Comment by PyroSA** [comment]
I had a similar issue.
Interface loads as blank screen. (Windows 10 x64, Atom 1.6.1)

As suggested by @guptadivyansh, clearing out the roaming folder solved it.
https://github.com/atom/atom/issues/4351#issuecomment-186504559

Log file:
[blankload.SquirrelSetup.log.txt](https://github.com/atom/atom/files/198718/blankload.SquirrelSetup.log.txt)

**Comment by roshimon** [comment]
Upgrading to atom 1.8.0-beta1 has fixed the issue for me. Working flawlessly now :)

**Comment by keenan-burnett** [comment]
Still seeing this problem on 1.8.0, beta does not fix, clearing roaming folder does not fix.

![scrnsht](https://cloud.githubusercontent.com/assets/9027562/16781194/156f8e4c-4848-11e6-8834-4507392c664a.png)

**Comment by lee-dohm** [comment]
@keenan-burnett If you look at the error message, it is saying that you don't have permissions to read a file under `C:\Users\IBM_ADMIN\.atom\compile-cache`. That is the problem you need to fix.

The problem you're having is not related to the original issue at all. Also, [we're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll probably be able to find answers faster.

**Comment by nelsonic** [comment]
Was this issue _resolved_?

I am seeing it _now_:
![image](https://user-images.githubusercontent.com/194400/30583048-bb93847e-9d1d-11e7-9dc9-c2d86a335f26.png)
(_blank window when opening atom_)
Note: I'm trying to open atom from command line with:
```
atom .
```
(_this **used to** open the project folder for the CWD in the terminal window_)

My Atom version is _apparently_ "_up-to-date_":
![image](https://user-images.githubusercontent.com/194400/30583152-16b2c630-9d1e-11e7-8baf-7fb544457582.png)

Running on Mac OS Sierra v 10.12.6 (16G29) (_also latest_)
