### ISSUE TITLE
Re-enable DirectWrite, possibly conditionally

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom#4355]
On my machine, DirectWrite looks a decent amount better than GDI+ when rendering Atom. Now that we're on Chrome 38, #3869 might no longer be an issue. We should (in order of preference):

1. Reenable this for erry'body, because Chrome 38 Fixed All The Bugs :sparkling_heart: 
1. Attempt to figure out which group of people this looks better for (Hi-DPI people?), then renable it automatically based on that
1. Enable this conditionally based on a user setting

**Comment by lee-dohm** [comment]
Has this been fixed? There is this issue https://github.com/atom/atom/issues/8089 that wants it turned off.

**Comment by paulcbetts** [comment]
@lee-dohm this person is using a system-wide hack that replaces the entire font rendering stack using shady hooks, I don't think this should be a supported scenario

**Comment by lee-dohm** [comment]
I agree that it shouldn't be a supported scenario. But if what he's saying is true and the hack is conflicting with DirectWrite, then wouldn't that mean that DirectWrite is enabled? And if DirectWrite is enabled, then is this Issue fixed?

**Comment by qrqiuren** [comment]
Is it still available to enable/disable DirectWrite while hacking Atom? I'd like to find where the option is.

**Comment by 50Wliu** [comment]
It's already enabled by default, so I'm going to close this.

@qrqiuren, this is where the option is set: https://github.com/atom/atom/blob/8b76c3d57cf3f74ead5fdd2eee747c3fc18f6d26/src/browser/atom-window.coffee#L30
