### ISSUE TITLE
Atom does not start when using x2go

### ISSUE THREAD

**Issue by nestoru** [atom/atom#4360]
- I first saw the issue for version v0.152.0 debian package in ubuntu 12.04 VM running on vmware ESXi.

$ [20853:1201/101159:ERROR:browser_main_loop.cc(162)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Xlib:  extension "XInputExtension" missing on display ":10.0".
Xlib:  extension "XInputExtension" missing on display ":10.0".
App load time: 368ms
[20877:1201/101159:ERROR:gl_surface_glx.cc(333)] GLX 1.3 or later is required.
[20877:1201/101159:ERROR:gl_surface_x11.cc(57)] GLSurfaceGLX::InitializeOneOff failed.
[20877:1201/101200:ERROR:gpu_child_thread.cc(143)] Exiting GPU process due to errors during initialization
atom: Fatal IO error 11 (Resource temporarily unavailable) on X server :10.0.
- I then installed it from webupd8 team:

sudo add-apt-repository ppa:webupd8team/atom
sudo apt-get update
sudo apt-get install atom

However I got the same issue. 
- I compiled then from sources following all instructions from README but still got the same issue.

To replicate just right click on a file to get a context menu and once you start moving your mouse it will fail with the error above.
- I updated to latest version debian package (186) won't even start. It will fail right up front with the same error.

**Comment by antond** [comment]
I am on 0.179.0 and facing the same issue on Ubuntu 12.04.5 LTS (precise) with the Trusty Hardware Enablement Stack. If it matters, I am running this on a VM (i.e. most likely software rendering).

**Comment by rpavlik** [comment]
If this is the general "doesn't work without DRI GLX", consider this a me-too. Running latest release from source on Debian Jessie, in a Virtualbox VM accessed through a Cygwin X-server (which supports aiglx). Initially it crashes on startup because it can't find swrast, after installing swrast I get this error (here just using raw X from guest to host, no ssh forwarding):

```
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 259 error_code 2 request_code 12 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by batjko** [comment]
Updated from v177 to the latest version (186) today without a problem, using the .deb installer.

**Comment by fusentasticus** [comment]
On Ubuntu 14.04 (Mint 17) as host (running X client) Atom.io will not run in either x2go or TurboVNC sessions for similar reasons. 

So is Atom usable with any remote desktop software when running under Linux?

Is there a way to pass something like " --disable-webgl " to Atom?

Tried with Atom editor version: 0.192.

**Comment by fusentasticus** [comment]
Answering my own question: tigervnc (v 1.4.3.) does the job!  Atom starts without a hitch.

**Comment by rpavlik** [comment]
Still would be good to know if we could disable unnecessary webgl, since there's no reason to use VNC to access a VM running on the same computer.

**Comment by arussell** [comment]
Confirming that it won't work for me either under X2Go due to the lack of GLX support. Chromium's `--disable-gpu` flag silences the complaints about GLX errors, but it still fails to connect to the X server despite this.

**Comment by boustanihani** [comment]
Same here using X2Go & Xubuntu 14.04 :(

**Comment by thejordanclark** [comment]
Not that the distro's really matters it's an Atom issue, but this also is preventing Atom to work through X2Go on Manjaro.

**Comment by pla1** [comment]
rdesktop over VPN connection to a Ubuntu 14.04.2 LTS desktop fails with **GLX 1.3 or later is required.** 

**Atom version 0.202.0**

**Comment by elico** [comment]
Same thing on Debian Jessie amd64 using x2go client atom 1.0.11

**Comment by jrgifford** [comment]
@thomasjo Why is this closed without any information? Is the bug fixed?

**Comment by thomasjo** [comment]
@jrgifford Pretty sure I didn't mean to close this one. At the very least I don't understand why I did. Thanks for the heads up!

**Comment by arussell** [comment]
Another "me too" for this. Been hoping to try Atom for a while but my main dev environment is an X2go one, so no dice. Tried every possible chromium option I could think of that disabled GPU acceleration/WebGL but no dice. Chrome/Chromium on the other hand do work over X2go.

**Comment by satulovsky** [comment]
Me too... trying to use Atom via a manually compiled xrdp 0.9.0. Chrome, however, complaints in the same way as Atom, but starts fine:
$ /opt/google/chrome/chrome
Xlib:  extension "XInputExtension" missing on display ":10.0".

**Comment by 029xue** [comment]
Same problem using Ubuntu 15.10 desktop. 

Any workarounds yet?

**Comment by gclifford** [comment]
I am also getting this issue on Ubuntu Mate 15.10

**Comment by dsmithdewarcom** [comment]
Same issue with dpkg install of v1.5 (atom-amd64.deb) on headless 12.04 server (bare metal) --> vnc

**Comment by tonywmnix** [comment]
I was seeing the same error message and debugged it down to an X extension "BIG-REQUESTS". You can use xtrace to trace all the X traffic and I saw an 8MB message before it crashed. 
I first disabled all extensions with (xtrace -e ) and that worked. 
My final hack was to copy libxcb.so.1 into /usr/share/atom, open up in editor, and change 'BIG-REQUESTS' to '_IG-REQUESTS'. I figure when the client library asks if this extension is supported it will reply no and no more big messages. 
hope this helps

**Comment by IronicBadger** [comment]
@tonywmnix - the libxcb.so.1 hack worked for me with Ubuntu Mate 15.10 via XRDP. Thanks.

**Comment by bs-ug** [comment]
@tonywmnix & @IronicBadger 
Could you please write a step-by-step instruction? I've no idea how you did it. When I view the file in mc I can't find 'BIG-REQUESTS'. There are only 'big_requests' but when I change them I get errors when running atom (something like "don't know what to do with _ig_requests...").

I've Windows10 host with Xubuntu 15.10 on Hyper-V and RDP session (not the most convenient solution but the only one working reasonably with UHD monitor).

**Comment by IronicBadger** [comment]
@bs-ug I just used `vi`. Then search for the string and replaced it.

**Comment by bs-ug** [comment]
@IronicBadger - So simple! Thanks!

**Comment by gary-dalton** [comment]
@tonywmnix libxcb.so.1 hack worked for me on Debian. Well done

**Comment by elico** [comment]
And why not just use a symlink to the original file?
For cases when it is binded to a specific libxcb.so version then it would make sense to use this specific library file.

**Comment by nestoru** [comment]
Just to give an update here that ubuntu 14.04 LTS with atom 1.5.4 debian package downloaded from https://atom.io/ works out of the box without any issues over xrdp. Cheers, - Nestor

**Comment by roterdam** [comment]
+1 for @tonywmnix this really did fix the issue. It also fixes it for Visual Studio Code.

One of the rare times a GitHub issue saves you so much time. Thanks!

**Comment by HaiyangDING** [comment]
+1 to @tonywmnix 's solution. It works for me.

Ubuntu 14.04.3 LTS + .deb package downloaded from atom.io today.

**Comment by isirad** [comment]
Ubuntu 15.10, headless system accessed over xRDP.  Thank you @tonywmnix.

**Comment by NelsonCrosby** [comment]
In case you're looking for a step-by-step for @tonywmnix's hack:

- Find `libxcb.so.1` (somewhere under `/usr`) (we'll call it `$LIBXCB`)
- `cd /usr/local/atom`
- `cp "$LIBXCB" .`
- `sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' libxcb.so.1`

Note that you may need to run the last two as `sudo`. Also usual disclaimer for running commands off the internet.

**Comment by thecodix** [comment]
Did the trick for me as well, and works with the beta version too

**Comment by pmarecki** [comment]
@tonywmnix solution works on Fedora 22 xfce, where $LIBXCB=/usr/share/atom, and the  .so is in /usr/lib64

**Comment by superm1** [comment]
Worked for me on Ubuntu 16.04 as well over XVnc.  LBXCB=/usr/lib/x86_64-linux-gnu/libxcb.so.1

**Comment by elico** [comment]
@nestoru , what version of ubuntu and what desktop environment are you using with the xrdp?

**Comment by nestoru** [comment]
@elico, see my comment above ( Mar 14).

**Comment by elico** [comment]
@nestoru I have seen the comment but maybe I am missing what desktop.
- GNOME
- MATE
- XFCE
- OTHER..

**Comment by nestoru** [comment]
@elico, gotcha. This was tested with lxde.

**Comment by NelsonCrosby** [comment]
@elico It worked for me on XFCE.

**Comment by elico** [comment]
@NelsonCrosby thanks for the details.

**Comment by groone** [comment]
@tonywmnix @NelsonCrosby Thanks! Workaround fixed GLX problems on Ubuntu MATE 16.04 when using it over xrdp.

**Comment by danielpclark** [comment]
If you're having trouble finding the file `libxcb.so.1` like I was you can type `dpkg -L libxcb1`

**Comment by AlexZeitler** [comment]
@NelsonCrosby Thanks for your suggestion. Tried it on Ubuntu 14.04 server with Mate Desktop but it didn't work.
Atom is /usr/bin/atom 
libxcb.so.1 is at /usr/lib/x86_64-linux-gnu/libxcb.so.1
Copied libxcb.so.1 to /usr/bin/ but it looks like atom does ignore it.

**Comment by danielpclark** [comment]
@AlexZeitler you need to copy `libxcb.so.1` to that atom application installation directory.  Once it's there you need to modify the file with:  `sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' libxcb.so.1` ?

**Comment by AlexZeitler** [comment]
@danielpclark Thanks, I just located the directory using `dpkg -L atom` which pointed me to `/usr/share/atom`.
After copying the modified version of `libxcb.so.1` into that directory, I was able to start Atom.

**Comment by Cotix** [comment]
While the libxcb.so.1 hack makes it possible to start atom, it is very, very slow over x2go. Barely usable.

**Comment by elico** [comment]
@Cotix What Link Quality Compression are you using? also what Display Size?
These affect anything inside a x2go session.
I am using it over x2go on a Atom(the remote..) server and it works ok for me on 1440x900.
And It's not related to the libxcb.so.1 but to other properties of the software in general.

**Comment by ihavenoideawhatimdoing** [comment]
Thanks @NelsonCrosby  @tonywmnix !

FYI to others, my atom executable was in /opt/atom; atom was installed via apt.

Ubuntu 16.04.1 LTS
Atom 1.9.8-1~webupd8~0

Here was the full fix:

`sudo cp /usr/lib/x86_64-linux-gnu/libxcb.so.1 /opt/atom/`
`sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /opt/atom/libxcb.so.1`

No restart of xrdp service was required; worked immediately

**Comment by citleon** [comment]
Ubuntu 16.04.1 LTS
sudo add-apt-repository ppa:webupd8team/atom
sudo apt-get update
sudo apt-get install atom
sudo cp /usr/lib/x86_64-linux-gnu/libxcb.so.1 /opt/atom/
sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /opt/atom/libxcb.so.1

Thank you! Atom is working via RDP (xrdp/mate)

**Comment by wgv-sethlivingston** [comment]
Would prefer to see a real solution here rather than a hack.

**Comment by jludwi2** [comment]
It worked fine for my on 16.04.1 using TightVnc and I'm happy it's working
even with a hack.  (but I still agree with Seth).

**Comment by TerribleNews** [comment]
Using atom-beta .deb package on Ubuntu 16.04 with LXDE over X2Go and couldn't get atom to start with the same error as above. I happened to be logged into the system locally at the same time and noticed that atom was actually opening on my local desktop when I tried to launch from X2Go before implementing the hack for disabling big messages. I'm not sure if that information helps locate and fix the bug, but I thought I'd provide it in case.

**Comment by zparihar** [comment]
It worked for me on CentOS 7 with XFCE on X2GO with both the Website Version of Atom and the COPR Repository Version:

Instructions:

WEBSITE METHOD


yum install libXScrnSaver redhat-lsb-core.x86_64 libXScrnSaver.i686
wget https://atom.io/download/rpm
mv rpm atom-`date +%b-%d-%Y`-Centos7.x86_64.rpm
rpm -ivh atom-*Centos7.x86-64.rpm
yum install libxcb.x86_64
cp /usr/lib64/libxcb.so.1* /usr/share/atom/
cd /usr/share/atom/
sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' libxcb.so.1*




COPR REPOSITORY METHOD


wget https://copr-be.cloud.fedoraproject.org/results/alonid/yum-plugin-copr/epel-7-x86_64/00110045-yum-plugin-copr/yum-plugin-copr-1.1.31-508.el7.centos.noarch.rpm
rpm -ivh yum-plugin-copr-1.1.31-508.el7.centos.noarch.rpm
yum copr enable helber/atom
yum update
yum install atom
yum install libxcb.x86_64
cp /usr/lib64/libxcb.so.1* /usr/share/atom/
cd /usr/share/atom/
sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' libxcb.so.1*






HOWTO INSTALL X2GO with XFCE on Cento7

#1.     Add EPEL repository first.
yum install epel-release

#2.     Then, install X2Go server package using command:
yum install fuse-sshfs
yum install x2goserver x2goserver-xsession

#3.     Install XFCE Desktop
yum -y groupinstall "Xfce"



Hope this helps!

**Comment by clintidau** [comment]
The libxcb.so.1 hack works for me on Fedora 25 with X2Go and XFCE.

**Comment by chagara** [comment]
@zparihar 
this worked for me on rhel 7.2 but, I can only launch it from CL.

**Comment by zparihar** [comment]
That's interesting... Can you specify the full path of atom when you edit
the menu item?

**Comment by elico** [comment]
@zacharysarah woks for me on CentOS latest(7.3?).
a MATE desktop over x2go.

**Comment by wanjizheng** [comment]
Here is the solution. Tested in Ubuntu 14.04 LTS
sudo cp /usr/lib/x86_64-linux-gnu/libxcb.so.1 /opt/atom/ (Folder of the Atom)
cd /opt/atom (Folder of the Atom)
sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' libxcb.so.1

**Comment by gm42** [comment]
Bug still present in Atom 1.15.0

**Comment by Daemoen** [comment]
Bug is also present in the 1.16 beta.  If you happen to be testing the beta, remember to update the copy and said as appropriate.  Using CentOS 7.3 x2go with MATE works just fine now.

**Comment by pumuckly** [comment]
Bug is still exists in 1.15.0 but @tonywmnix hack's works well on Ubuntu 14.04.5 LTS

**Comment by PRAVEENT26** [comment]
The libgconf-2-4 package might be missing preventing the application to launch.
This might help:
`sudo apt-get install libgconf-2-4`

**Comment by defong** [comment]
Title is a just Atom does not start when using x2go

it more of window manager not x2go or tightvncserver

Came across this when

Debian from minimal install
using 
lxde http://lxde.org/
or
awesomewm https://awesomewm.org 

apply  @tonywmnix hack's 

and it works for x2go and tightvncserver

**Comment by edwinjhlee** [comment]
The hack does works. However, I found the backspace doesn't work in the vscode editor and also, I cannot select the completion with enter. Is it possible that is the side-effect of the hack library?

**Comment by bneijt** [comment]
I use atom via X2GO and decided to disable the BIG-REQUESTS extension of X2Go:

- open /etc/x2go/x2goagent.options
- Change X2GO_NXAGENT_DEFAULT_OPTIONS to include -extension BIG-REQUESTS

Then restart the server and reconnect to have atom working in x2go

**Comment by blaer** [comment]
bneijt's solution worked like a charm. Prefer it over patching shared objects with regular expressions.

**Comment by elico** [comment]
@bneijt by server do you mean service(software) or server(machine)?

**Comment by bneijt** [comment]
@elico service, not the whole server. It is a setting specific to the x2go service (software)

**Comment by elico** [comment]
@bneijt Thanks!
I was 99% that this is what you meant but now 100%.
I tried it here with CentOS and it seems to work great.
No need for any libraries patches\hacks to work with atom and couple other applications.

**Comment by johann-petrak** [comment]
Getting problems when running this on a server to which I connect using ssvnc. 
With an old version of atom (1.6.2) the following fix worked:
* copy libxcb.so.1 into /usr/share/atom
* sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' libxcb.so.1

However with more recent versions, 1.19.0 or 1.20.--beta0 a different problem occurs: atom does start but all characters inside the editor window (with the exception of the menu bar which is in Courier) are shown as reactangles (unknown character placeholders?)

**Comment by erioshi** [comment]
The easy fix for x2go and x11 forwarding using Ubuntu 16.04 and Mint is:
~$ sudo ln -s /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0 /opt/atom/libxcb.so.1
~$ sudo sed -i 's/BIG-REQUESTS/_IG-REQUESTS/' /opt/atom/libxcb.so.1

I did not have the same problem listed by @johann-petrak.

**Comment by myudkowsky** [comment]
I experienced the atom/x2go problem on Ubuntu with atom from both the standard repository (i.e., installation via "snap") and with atom from the webupd8team launchpad repository.

@bneijt's answer works, and as others have mentioned, has the advantage that it does not require patching code that may or may not need to be re-patched in the next release.

Please note that you must add "-extension BIG_REQUESTS" on the server, i.e., the remote server that you're connecting to.

**Comment by ssplavec** [comment]
Not using x2go (at least I don't believe I am), but experienced the same problem on Linux Mint 18.2 (MATE).
Copied /usr/lib/x86_64-linux-gnu/libxcb.so.1  to /usr/share/atom
Opened libxcb.so.1 in 'vi' and change BIG-REQUESTS to _IG-REQUESTS
Now Atom starts just fine.
Thanks to all who helped solve this problem.

**Comment by 2vishnui** [comment]
Thanks @ggodreau for the easy steps specific to version 16
thanks @NelsonCrosby  for steps 
thanks @tonywmnix for fix

**Comment by sitsofe** [comment]
As noted in other Atom bugs this appears to be a version of an upstream bug https://github.com/electron/electron/issues/2256 that affects some VNC/NX servers (note that new versions of tigervnc's server do not seem to manifest this issue).
