### ISSUE TITLE
Add support for multiline string configuration options

### ISSUE THREAD

**Issue by eddieantonio** [atom/atom#4361]
The text for an configuration string with multiple lines overflows past the text box when a configuration is _set_, but not when it has a default value.
## With default

![screen shot 2014-12-01 at 11 42 07 am](https://cloud.githubusercontent.com/assets/2294397/5251090/bd420506-794f-11e4-84d5-ab3cd068c3c8.png)
## With option set in config

![screen shot 2014-12-01 at 11 39 21 am](https://cloud.githubusercontent.com/assets/2294397/5251101/d2f5a81c-794f-11e4-8674-e416b17cf920.png)

``` sh
$ atom --version
0.152.0
```

This is on OS X 10.9.5.

**Comment by benogle** [comment]
Work to fix the overflowing is happening at #4400. I changed the title to be a feature request to add multiline string config options.
