### ISSUE TITLE
Autocomplete Next

### ISSUE THREAD

**Issue by benogle** [atom/atom#4364]
We're not quite ready to tackle a new autocomplete yet, but I wanted to start the conversation as there are several folks interested in working on autocomplete: @mark-hahn, @lee-dohm, @joefitzgerald, @abe33.

Once we finish with API related things, I was planning on:

* Looking at `autocomplete-plus` code
* Checking out all of the existing providers out there.
  * How many are out there? What are the popular ones?
* Looking at code @mark-hahn and @lee-dohm produced recently
* Looking at other editors. How do they do it? Do they have APIs?
* Are there autocomplete daemons out there we can use (e.g. https://github.com/nsf/gocode for Go)

Then I would come up with a plan of attack for the new version. In my mind, we have a couple options:

* Extend `autocomplete` with an API
* Take over `autocomplete-plus` with some modifications and API changes
* Write something completely new

I am not sure what the best way forward is right now. I do feel, though, that the hard part is not the UI that pops up the completion box, it's having great language support, and a nice API for adding completions.

It would be great if you guys could help me / us work through the research phase. Off the top of my head, I'm thinking these would be a big help:

* Your opinions and suggestions for the provider API.
* Your architectural suggestions (I know @mark-hahn wrote one recently)
* Comments explaining the pitfalls and your frustrations of the current `autocomplete-plus` API. Maybe suggestions on improvements.
* Links to autocomplete providers for languages (either generic providers or for other editors)
* Explanations / links to APIs in other editors
* General autocomplete API related frustrations and desires

## Resources

* Discuss thread: https://discuss.atom.io/t/what-can-we-do-to-improve-autocomplete/13001
* @mark-hahn + @lee-dohm's autocomplete: https://github.com/mark-hahn/autocomplete-generic
* https://github.com/atom-community/autocomplete-plus
* https://github.com/HaxeIDE/atom-autocomplete-plus-async

### Providers

* Ruby provider: https://atom.io/packages/rsense
* Rust provider: https://atom.io/packages/racer
* Go generic provider: https://github.com/nsf/gocode
* Python generic provider: https://github.com/davidhalter/jedi
* JS: https://github.com/marijnh/tern ; https://github.com/majutsushi/tagbar/wiki#javascript
* Coffee: https://github.com/lukaszkorecki/CoffeeTags ; https://github.com/mntmn/tern-coffeescript

### Autocomplete+ providers

https://github.com/atom-community/autocomplete-plus/wiki/Autocomplete-Providers

**Comment by joefitzgerald** [comment]
@benogle I know it's now January and you're nearing completion of the 1.0 API. If your focus starts to shift to this, please ensure you discuss with @nathansobo and take a look at the work we're doing in atom-community/autocomplete-plus#189 and atom-community/autocomplete-plus#184.

**Comment by benogle** [comment]
Will do

**Comment by mnquintana** [comment]
Are there any updates on the direction for autocomplete going forward? (ie. is Atom going to adopt autocomplete-plus now?)

**Comment by kevinsawicki** [comment]
> Are there any updates on the direction for autocomplete going forward?

It is definitely in progress, we shipped two new autocomplete-plus providers this week, [autocomplete-html](https://github.com/atom/autocomplete-html) and [autocomplete-css](https://github.com/atom/autocomplete-css)

I would guess it would start to ship with Atom in the next couple weeks or so

**Comment by joefitzgerald** [comment]
... And we're more than happy to facilitate transition of the repo from https://github.com/atom-community to https://github.com/atom, as well as autocomplete-snippets and autocomplete-paths - if desired.

**Comment by steelbrain** [comment]
Tara Rum Pum, Bump

**Comment by benogle** [comment]
This is happening. I cant commit to a specific date, but autocomplete-plus will be the main deal soonish.

**Comment by russlescai** [comment]
:+1:

**Comment by brendanfalkowski** [comment]
Markup closing would be a great core feature for the autocompleter: https://github.com/mrhanlon/less-than-slash

**Comment by joefitzgerald** [comment]
> Markup closing would be a great core feature for the autocompleter: https://github.com/mrhanlon/less-than-slash

That wouldn't be a core feature but it sounds like a great provider. Would be cool if the current package converted to become an autocomplete-plus provider.

**Comment by brendanfalkowski** [comment]
@joefitzgerald Ah, I'll suggest there. Maybe wrong word choice, meant: would be nice if "Atom just behaved this way by default" rather than it belongs in this package specifically. This seemed like the right place among the `roadmap` tasks.

**Comment by sandstrom** [comment]
A wish would be 'inline-autocomplete', i.e. an UI-less mode where a keypress will rotate among the alternatives (similar to how it works in Textmate).

This package supports this, but it's not as nicely integrated with Atom as the regular autocomplete package, and since this is a core feature of an editor I'd much prefer using an official package.
https://atom.io/packages/inline-autocomplete

**Comment by steelbrain** [comment]
-1 for inline-autocomplete. 
Because I use autocomplete to not only get autocomplete but to also get the type of the variable, for example, identify if it's a `Map<string,mixed` or `Map<string,string`.

Auto-Complete-Plus provides a label attribute that serves this purpose grealy.

**Comment by sandstrom** [comment]
@steelbrain I'm thinking of an optional, opt-in, mode. You wouldn't be forced to use it.

**Comment by benogle** [comment]
> A wish would be 'inline-autocomplete',

I think this should be a separate package. For the people who want this behavior, they can disable the default, and install an `inline-autocomplete` package.

**Comment by zslabs** [comment]
Just throwing in my +1 on an AutoComplete system that can stand-up against PHP Storm's. For example, working in a Laravel app, if I start typing:

`Route`

it gives me options on what class to import and even tells me when I have imported classes that are not in use in the current doc, which is fantastic. This is the ONLY feature that is keeping me from moving to Atom full-time -- right now it's just for frontend work.

**Comment by benogle** [comment]
@zslabs out of the box, it wont provide PHP intelligence. We will be bundling autocomplete-plus in the near future. You can install it today and get a much better experience over the built-in autocomplete. You may get some mileage out of @steelbrain's [atom hack](https://atom.io/packages/atom-hack) package. Also, I do know facebook will be soon releasing [nuclide](nuclide.io) soon, which will include hack tooling, likely with autocomplete providers for PHP.

**Comment by benogle** [comment]
A note to everyone following this issue: there is a plan for bundling autocomplete-plus with core outlined in https://github.com/atom-community/autocomplete-plus/issues/351
