### ISSUE TITLE
New packages not installing Mac

### ISSUE THREAD

**Issue by BillyChick** [atom/atom#4371]
Hi
I don't know if your aware but new packages, that is packages not already installed, won't install if Xcode has been updated and not used. The reason is the Xcode terms have to be agreed to in the welcome window. This may also be an issue with other apps that use npm and git for users that have Xcode installed but don't use it much. It took me a while to resolve this issue so it may be worth mentioning it on the Atom site.
Billy Chick

**Comment by kevinsawicki** [comment]
Closing this out, I'm not sure there is any way around this in Atom when the native toolchain requires a interaction before building can be done.
