### ISSUE TITLE
Text only displaying on half of the Panel/Tab, double status and horizontal scroll bar.

### ISSUE THREAD

**Issue by Moter8** [atom/atom#4377]
Atom appears weird. I was able to select text and edit it but the scroll bars etc were broken. Resizing temporarely fixed this.
![tftgqk7](https://cloud.githubusercontent.com/assets/3776997/5270856/e24f57fa-7a66-11e4-8137-a663638531a1.png)

Previously launched atom via `sudo atom some.conf` and now I opened atom through Gnome's file-roller.
Resizing the windows fixed this issue the first time. After closing and reopening it appeared again. After that it completely dissapeared.

Got it to reproduce 3 out of ~10 times. Guake was running at the same time too.

atom `0.153.0-1d6087f`

```
shell@arch-moter8 ~> ~/scripts/meksysinfo.sh 
Host:   arch-moter8
Kernel: Linux 3.17.4-1-ARCH x86_64
Distro: Arch Linux
CPU:    Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
        4 cores/threads
        4200.00 MHz
RAM:    23.50 GiB
GPU:    AMD Radeon R9 200 Series
        OpenGL/core 4.4.12968 Core Profile Context 14.201.1006.1002
        GLSL/core 4.40
        OpenGL 4.4.12968 Compatibility Profile Context 14.201.1006.1002
        GLSL 4.40
Screen: No screen detected. You might need to install xwininfo.
WM/DE:  GNOME
```

**Comment by mnquintana** [comment]
@Moter8 Are you still experiencing this issue with the latest version of Atom (0.190.0)?

**Comment by Moter8** [comment]
@mnquintana Hey, thanks for reminding me of this issue. I will boot into this system tomorrow and try to reproduce this with the current version.

**Comment by Moter8** [comment]
Sorry, I'm unable to log into the old system for now. I will close this.
