### ISSUE TITLE
Can't download certain packages

### ISSUE THREAD

**Issue by Paranormalcow** [atom/atom#4385]
http://puu.sh/ddLmM/1bd92a348d.png
http://puu.sh/ddLCp/02c9692313.txt
I'm running on windows 7 ultimate. 0.152.0
Can anyone help me with this?
I know this isn't related to the DNS issue that happened yesterday.
I can download the package "Color Picker." But other spit this error.
npm ERR! Please check if you have git installed and in your PATH. stands out, but I don't know how to resolve that error.

**Comment by mnquintana** [comment]
You can track atom/apm#236 for updates - there is also a new error message for this now which should help clear things up.
