### ISSUE TITLE
Crash on right click after opening folder Linux

### ISSUE THREAD

**Issue by slackboxster** [atom/atom#4388]
Application crashes with the following output after I right click having opened a folder, but not opened any files (so the untitled file is the only file showing). 

Running atom 0.152.0 on Debian jessie/sid -- partially on testing, partially on stable -- using i3 for window management (kdm underlying I believe). I am aware this is a bit of a funky setup. The error also occurs in safe mode.

To confirm, steps to reproduce:
1. Run atom (from command line to see error output)
2. File -> Open Folder...
3. Choose a folder (at first I was using a network drive, but no difference with local FS)
4. Right click in empty file editing window
Application crashes.

Error output on console is as follows:
```
[9107:1203/111941:ERROR:browser_main_loop.cc(162)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 141ms
[9141:1203/111942:INFO:renderer_main.cc(204)] Renderer process started
[9107:1203/111943:INFO:CONSOLE(64)] "Window load time: 1270ms", source: file:///usr/share/atom/resources/app/static/index.js (64)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.                                                                                                                                            
The error was 'BadWindow (invalid Window parameter)'.                                                                                                                                   
  (Details: serial 4532 error_code 3 request_code 3 minor_code 0)                                                                                                                       
  (Note to programmers: normally, X errors are reported asynchronously;                                                                                                                 
   that is, you will receive the error a while after causing it.                                                                                                                        
   To debug your program, run it with the --sync command line                                                                                                                           
   option to change this behavior. You can then get a meaningful                                                                                                                        
   backtrace from your debugger if you break on the gdk_x_error() function.)  
```

**Comment by stramel** [comment]
Related issue: #4892

**Comment by mnquintana** [comment]
This is fixed for me in 0.169.0 on Ubuntu 14.04.1 LTS. (See #4892)

**Comment by kevinsawicki** [comment]
@slackboxster Can you try upgrading to Atom 0.169 or later?

**Comment by slackboxster** [comment]
This still occurs for me with Atom 0.182 in i3 4.2 on my funky debian system. Atom 0.182 does not have issues in KDE on said debian system, or in i3 4.7.2 on my laptop running ubuntu 14.04.2 LTS. The problematic debian system, in addition to being subject to debain's stability motivated package lag, is in a state where some, but not all of the packages are on testing, with the remainder lagging on stable because of a dependency deep down not upgrading. Somewhere therein probably lies the rub. Is this issue worth keeping open at all?

**Comment by kevinsawicki** [comment]
> Somewhere therein probably lies the rub. Is this issue worth keeping open at all?

I think this is worth closing.
