### ISSUE TITLE
Multiline paste in find box overflows box

### ISSUE THREAD

**Issue by eddiemonge** [atom/atom#4400]
Pasting something like this in the Find box displays incorrectly

```

    'use strict';

```

![paste](https://cloud.githubusercontent.com/assets/127535/5308709/f7235d2a-7bce-11e4-90c9-a2f6b2f092b8.png)

It seems like the box gets the height of the content so the overflow hidden doesnt happen.

![css](https://cloud.githubusercontent.com/assets/127535/5308745/6c95c1ba-7bcf-11e4-9e50-0f76dfc586eb.png)

Mac 0.152.0

**Comment by simurai** [comment]
There is now overflow scrolling when pasting multiple lines.

![overflow](https://cloud.githubusercontent.com/assets/378023/5775362/53dbd0e2-9dbc-11e4-8bc5-538a62cc70f6.gif)

Another option might be to expand the height to show all lines?

**Comment by postcasio** [comment]
@simurai that might be better. Without a scrollbar, it's not obvious that the editor has multiple lines.

The other option is just to render a newline as regular whitespace in a mini editor so it all goes on one line.

**Comment by simurai** [comment]
We could force a scrollbar. But looks a bit funny.

![overflow](https://cloud.githubusercontent.com/assets/378023/5775820/a6eb8b32-9dc2-11e4-8219-eeccde9ad1a6.gif)

I like the "render a newline as regular whitespace in a mini editor so it all goes on one line." I'll reopen this issue again.

**Comment by lijunle** [comment]
I expect that, it just join each lines as one long string, then display.

**Comment by simurai** [comment]
This issue is technically not "in-progress" anymore. I only did the overflow scrolling as a quick fix (which is already on master), but the better solution would be to do the "render a newline as regular whitespace". I think I'll leave that to somebody else.

In other words, this issue is again up for grabs.

**Comment by bombless** [comment]
I'd add a checkbox there named "Lock as single line".
But I guess dynamically change style of a DOM node is not our idiom? (I don't know.)
