### ISSUE TITLE
Mouse button 4 and 5 for navigation

### ISSUE THREAD

**Issue by bpasero** [atom/atom#4402]
Atom should bind mouse keys 4 and 5 for backward / forward navigation in documents I edited in the active session.

**Comment by pvoisin** [comment]
+1
That should be basics in modern code editors... :)

**Comment by cqcallaw** [comment]
+1

**Comment by Pholey** [comment]
Game changing feature i'd love to see!

**Comment by a7madgamal** [comment]
+100000

**Comment by a7madgamal** [comment]
until this lands, any packages or hacks are very welcome as I just bought a super expensive mouse for this :D

**Comment by ChugunovRoman** [comment]
+++++++++++++++++++++

**Comment by JoseFMP** [comment]
Any news on this issue?
