### ISSUE TITLE
Atom won't start on OS X 10.10

### ISSUE THREAD

**Issue by tom-alcorn** [atom/atom#4408]
I recently updated Atom to 0.152, now it won't start. Here's the error message I'm getting

![screen shot 2014-12-05 at 12 46 03 pm](https://cloud.githubusercontent.com/assets/8483583/5320098/e8fddd2a-7c7c-11e4-8cc6-f9e6362e70a1.png)

Any ideas what's going on?

**Comment by kevinsawicki** [comment]
This issue is quite old now and hasn't been reported by others on recent versions of Atom so I'm going to close this out. Please comment if you still experience this crash on Atom 1.0+.
