### ISSUE TITLE
OS X dictionary doesn't work

### ISSUE THREAD

**Issue by defunkt** [atom/atom#441]
Usually you can highlight a word in OS X and hit `cmd-ctrl-d` to see its definition but this doesn't work in Atom.

![image](https://f.cloud.github.com/assets/2/287750/2a48fe7c-925f-11e2-9fae-4f642df36ce6.png)

**Comment by unordered** [comment]
click menu Atom => Stylesheet
and add follow code to it.
```
atom-text-editor .editor-contents--private {
  -webkit-user-select: initial;
}
```

**Comment by nathansobo** [comment]
Don't use that private class. It's going away soon.

**Comment by Aerijo** [comment]
@defunkt @nathansobo This issue seems like it's fixed. I was able to open the dictionary popup using the shortcut and the three finger tap in atom (safe mode).
