### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by wmariuss** [atom/atom#4421]
Uncaught Error: Atom can only handle files < 2MB for now.

**Atom Version**: 0.153.0
**System**: linux 3.13.0-40-generic
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package

**Comment by lee-dohm** [comment]
Sorry @wmariuss, this is the Issue we are using to track this problem. I'm going to reopen this so we can continue tracking it.

**Comment by wmariuss** [comment]
No worries.

2015-01-05 7:13 GMT+02:00 Lee Dohm <notifications@github.com>:

> Sorry @wmariuss <https://github.com/wmariuss>, this is the Issue we are
> using to track this problem. I'm going to reopen this so we can continue
> tracking it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/4421#issuecomment-68669200>.
>



-- 
Marius Stanca
email: hi@mariuss.net | web: www.mariuss.net <http://mariuss.net> | tel. +4
076.795.5578 | Linkedin <http://ro.linkedin.com/in/wmariuss> | Gmail
<stanca.marius7@gmail.com> | Skype: wmariuss

**Comment by steelbrain** [comment]
I think this should be re-opened so for users running previous versions of atom don't keep opening new issues for this.

**Comment by 50Wliu** [comment]
There'll be less issues coming in as more and more people upgrade to newer versions of Atom.
