### ISSUE TITLE
Uncaught Error: IPC channel is already disconnected

### ISSUE THREAD

**Issue by mythmon** [atom/atom#4451]
Uncaught Error: IPC channel is already disconnected

**Atom Version**: 0.152.0
**System**: linux 3.17.4-1-ARCH
**Thrown From**: Atom Core

**Comment by felixcrive** [comment]
@mythmon Hi, I wonder if you figured it out what was causing this issue, I am having the same issue on OS X. Thanks.

**Comment by mnquintana** [comment]
@felixcrive What version of Atom are you using? What version of OS X?

**Comment by felixcrive** [comment]
@mnquintana I am using electron-prebuilt @0.36.2 and OS X 10.10.5.

**Comment by mnquintana** [comment]
@felixcrive I'd recommend opening an issue on https://github.com/atom/electron instead then (if there isn't one already) – this issue tracker is for Atom, not Electron.

**Comment by 50Wliu** [comment]
Haven't seen this since the original report, so closing.
