### ISSUE TITLE
Auto indent still misbehaving

### ISSUE THREAD

**Issue by ghost** [atom/atom#4461]
Atom 0.154 on Mac OS.

![auto-ind](https://cloud.githubusercontent.com/assets/440132/5354669/deb66bfa-7f3f-11e4-8fd8-9d62e7b221d6.gif)

Code below (make sure your syntax mode is CoffeeScript). Follow the instructions therein.

```
$ ->
  $(window).load ->

# Copy the below and paste it on the line below $(window).load ->
# Make sure the cursor is indented one level in from $(window).load (col = 5)
    if 2 is 2
      celebrate()
```

**Comment by brentshermana** [comment]
Please help me test my pull request on Windows :)
