### ISSUE TITLE
Uncaught Error: spawn /Users/Mitch/Library/Application Support/com.github.atom.ShipIt/update.7v9wl5y/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

### ISSUE THREAD

**Issue by mitchwilson1** [atom/atom#4475]
Uncaught Error: spawn /Users/Mitch/Library/Application Support/com.github.atom.ShipIt/update.7v9wl5y/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT

**Atom Version**: 0.154.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At events.js:85

Error: spawn /Users/Mitch/Library/Application Support/com.github.atom.ShipIt/update.7v9wl5y/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/notifications/pull/62
