### ISSUE TITLE
Update Atom icon location when installing

### ISSUE THREAD

**Issue by digitalvapor** [atom/atom#4482]
I just uninstalled the webupd8team Atom ppa and Atom and installed via the [Ubuntu release](https://github.com/atom/atom#debian-linux-ubuntu). I can run Atom via the command line, which is how I am going to use it 99% of the time, but when using the icon, I get `Failed to execute command "/opt/atom/atom %F". Failed to execute child process "/opt/atom/atom" (No such file or directory)`. I'll probably just edit the location cited manually because nothing is in `/opt/atom/` anymore, and everything will be okay. Just passing along, thanks.

**Comment by kevinsawicki** [comment]
I believe this has been resolved since this issue was reported and so I'm going to close it out. Please let me know if you still see this issue on Atom 1.0+.
