### ISSUE TITLE
Uncaught SyntaxError: Expected "-" or end of input but "/" found.

### ISSUE THREAD

**Issue by sedrickcz** [atom/atom#4485]
Uncaught SyntaxError: Expected "-" or end of input but "/" found.

**Atom Version**: 0.153.0
**System**: linux 3.13.0-40-generic
**Thrown From**: Atom Core

**Comment by kevinsawicki** [comment]
Closing this out, this is going to be incredibly hard to reproduce since it is a really old version, no longer being experienced, and missing a stack trace.
