### ISSUE TITLE
cannot delete folders from project tree

### ISSUE THREAD

**Issue by saniko** [atom/atom#4503]
using latest version (0.155.0)
using the "project manager" package.

when i select a folder on the left side project tree, right click and select "delete"
nothing happens.

EDIT: apparently it was permission issue, but still, no indication in editor, you select to delete and nothing happens.

**Comment by brad-jones** [comment]
Perhaps this could be part of the problem:
https://discuss.atom.io/t/cannot-delete-files-in-atom-in-linux/13546/4
