### ISSUE TITLE
Uncaught Error: spawn /opt/atom/atom (deleted) ENOENT

### ISSUE THREAD

**Issue by Apostropher** [atom/atom#4505]
**TEMPORARY WORKAROUND**: `ln -s /usr/share/atom/atom "/usr/share/atom/atom (deleted)"`

Uncaught Error: spawn /opt/atom/atom (deleted) ENOENT

**Atom Version**: 0.152.0
**System**: linux 3.13.0-40-generic
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At events.js:85

Error: spawn /opt/atom/atom (deleted) ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by dideler** [comment]
Just ran into this issue.

I had one instance of atom open for a few days with lots of open tabs in it. Then I started another instance of atom (via the command line) but for a different project and that's when the error kept popping up. Closed both instances and now the error is gone when I start atom again.

**Comment by Qard** [comment]
I get this too. With multiple projects open, it happens every time I switch focus to that window.

As previously suggested, it does seem to only happen when opening new windows after atom has been open for awhile. If I start fresh, opening two windows together, neither will encounter this.

**Comment by ljbade** [comment]
Happening for me.

I just opened a second folder with another window open with another folder open.

Happens everytime I click in the new window.

Went away after I closed all atom windows and reopened atom.

I am on Ubuntu 14.04 with atom 0.177.0

**Comment by MateuszG** [comment]
**Atom Version**: 0.177.0
**System**: linux 3.16.0-30-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /opt/atom/atom (deleted) ENOENT

```
At events.js:94

Error: spawn /opt/atom/atom (deleted) ENOENT
  at exports._errnoException (util.js:753:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:364:11)

```

### Commands

```
     -5:36.9 snippets:next-tab-stop (atom-text-editor.editor.autocomplete-active.is-focused)
     -5:36.9 snippets:expand (atom-text-editor.editor.autocomplete-active.is-focused)
     -5:36.9 editor:indent (atom-text-editor.editor.autocomplete-active.is-focused)
     -5:35.1 snippets:next-tab-stop (atom-text-editor.editor.autocomplete-active.is-focused)
     -5:35.1 snippets:expand (atom-text-editor.editor.autocomplete-active.is-focused)
     -5:34.5 core:save (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:28.3 core:copy (atom-text-editor.editor.autocomplete-active.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-blame",
      "minimap",
      "terminal-status",
      "welcome",
      "git-log",
      "git-log",
      "git-log",
      "git-log",
      "git-log",
      "feedback",
      "exception-reporting",
      "atom-html-preview",
      "open-on-search-engine",
      "ask-stack",
      "Search",
      "atom-runner",
      "script",
      "linter-pep8",
      "linter-pylint"
    ],
    "themes": [
      "atom-light-ui",
      "imperator-day-syntax"
    ],
    "audioBeep": false,
    "autoHideMenuBar": true
  },
  "editor": {
    "fontSize": 17,
    "showInvisibles": true,
    "autoIndentOnPaste": false,
    "tabLength": 4,
    "softWrap": true,
    "softTabs": false,
    "softWrapAtPreferredLineLength": true,
    "invisibles": {
      "eol": " "
    },
    "zoomFontWhenCtrlScrolling": false
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autoclose-html, v0.15.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.4
autohide-tree-view, v0.12.0
color-picker, v1.4.4
compare-files, v0.4.0
file-icons, v1.4.9
git-tab-status, v1.5.3
highlight-selected, v0.7.0
imperator-day-syntax, v0.0.0
linter, v0.11.1
linter-pylama, v0.0.15
preview-tabs, v0.1.6
project-manager, v1.15.5
pulsing-cursor, v0.3.0
python-isort, v0.0.5
tabs-to-spaces, v0.8.1
zentabs, v0.7.1

# Dev
No dev packages
```

**Comment by pdgago** [comment]
**Atom Version**: 0.180.0
**System**: linux 3.13.0-45-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /opt/atom/atom (deleted) ENOENT

```
At events.js:94

Error: spawn /opt/atom/atom (deleted) ENOENT
    at exports._errnoException (util.js:753:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
    at child_process.js:1142:20
    at process._tickCallback (node.js:364:11)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontFamily": "monaco",
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
docblockr, v0.5.8
javascript-snippets, v1.0.0
jshint, v1.2.0
tasks, v1.2.4
web-browser, v1.3.0

# Dev
No dev packages
```

**Comment by noseglid** [comment]
I just got this and it totally spammed with an error every 10 seconds or so (Ubuntu 14.04.2 LTS).

Since it seems to complain about a file `atom (deleteid) doesn't exists, I did this to silence it (which seems to have been successful) although I don't know the impact it might have:

    sudo cp /opt/atom/atom "/opt/atom/atom (deleted)"

**Comment by thiagokronig** [comment]
Happened to me also after dpkg -i the 0.187.0 version over already installed 0.186.0. 
Following @noseglid, did a `ln -s /usr/share/atom/atom "/usr/share/atom/atom (deleted)"` to remedy.

**Comment by MichaelBanks** [comment]
Happened to me on Windows

**Comment by AlonsoCN** [comment]
Same here :( someone have a soft solution?

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/notifications/pull/62
