### ISSUE TITLE
"Reveal in Tree View" does not work when there is no folder selected.

### ISSUE THREAD

**Issue by Bengt** [atom/atom#4524]
Wouldn't it be nice to have this open the tree view in directory the file is located in?

**Comment by tommytroylin** [comment]
Same problem. Even when there is a folder in Tree View, nothing happened when I press the Reveal in Tree View on a file that isn't in this current folder. 
My System & Version:
Mac OS X Yosemite 
atom 169

**Comment by tommytroylin** [comment]
![qq20150115-1](https://cloud.githubusercontent.com/assets/3364271/5743501/9524506a-9c54-11e4-87fa-e99121dd3a76.png)
the location in title is wrong 
![qq20150115-3](https://cloud.githubusercontent.com/assets/3364271/5743503/956f6f5a-9c54-11e4-98e8-d836648ffd31.png)
actually the correct file location is like this, you can see these 2 files are not in the same folder
![qq20150115-5](https://cloud.githubusercontent.com/assets/3364271/5743506/9719c788-9c54-11e4-8160-d2b4df6e28c0.png)

**Comment by nicomfe** [comment]
any news on this? same issue here. Atom 1.15.0, Mac OSX 10.11.3

**Comment by nicomfe** [comment]
I realised this issue was being caused by nuclide instead of atom itself, updating nuclide package to 0.220.0 fixed this in my case.
