### ISSUE TITLE
Uncaught Error: spawn scss-lint ENOENT

### ISSUE THREAD

**Issue by nruth** [atom/atom#4557]
Uncaught Error: spawn scss-lint ENOENT

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

1. open application.css 
2. open command pallet and find treeview rename
3. rename file to application.scss
4. uncaught error popup appears, but seems like no harm done

### Stack Trace

```
At events.js:85

Error: spawn scss-lint ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by benogle** [comment]
Closing as there is a better error message now
