### ISSUE TITLE
Cannot grab vertical scrollbar

### ISSUE THREAD

**Issue by jimgraham** [atom/atom#4563]
Windows 7 sp1 x64, Atom 0.156.0

I can scroll with mouse wheel, but cannot click on the vertical scroll slider and mouse-drag to scroll. I can do this with the horizontal scroll.

Related to #2751 ?

**Comment by jimgraham** [comment]
@simurai Following what I did in https://github.com/atom/atom/issues/4563#issuecomment-66824881 and what you recommended in https://github.com/atom/atom/issues/4563#issuecomment-68032493 , if I add the attribute `style="display: none"` to the `<atom-notifications>` node, I can grab the scrollbar. Removing it makes it so I can no longer grab the scrollbar.

![scrolldisplaynone](https://cloud.githubusercontent.com/assets/430293/5620864/f86ff632-94fd-11e4-8abe-419748320dad.png)

I don't know enough about Atom to know what that means though

**Comment by simurai** [comment]
@jimgraham Thanks, that already helped a lot. For some reason `pointer-events: none;` was missing. Might got lost in a merge conflict.. Anyways, should be fixed in the next update.
