### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by LewisGauss** [atom/atom#4568]
So I have been trying to install the auto complete plus plugin, but I have not been able to do so because an error keeps coming up. The output of the error is below. Can somebody help me?

npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/atom-space-pen-views
npm http GET https://registry.npmjs.org/event-kit
npm http GET https://registry.npmjs.org/fuzzaldrin
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/event-kit
npm http 200 https://registry.npmjs.org/underscore-plus
npm http 200 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.2.tgz
npm http 304 https://registry.npmjs.org/minimatch
npm http 200 https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.2.tgz
npm http 304 https://registry.npmjs.org/atom-space-pen-views
npm http 304 https://registry.npmjs.org/fuzzaldrin
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/brace-expansion
npm http 200 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/concat-map/0.0.0
npm http GET https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map/0.0.0
npm http 304 https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm ERR! Error: EPERM, lstat 'C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map\README.markdown'
npm ERR!  { [Error: EPERM, lstat 'C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map\README.markdown']
npm ERR!   errno: 50,
npm ERR!   code: 'EPERM',
npm ERR!   path: 'C:\\Users\\Lewis\\AppData\\Local\\Temp\\apm-install-dir-1141112-2536-1opq1z\\node_modules\\autocomplete-plus\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\concat-map\\README.markdown',
npm ERR!   fstream_type: 'File',
npm ERR!   fstream_path: 'C:\\Users\\Lewis\\AppData\\Local\\Temp\\apm-install-dir-1141112-2536-1opq1z\\node_modules\\autocomplete-plus\\node_modules\\minimatch\\node_modules\\brace-expansion\\node_modules\\concat-map\\README.markdown',
npm ERR!   fstream_class: 'FileWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ 'c:\\Users\\Lewis\\AppData\\Local\\atom\\app-0.156.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\node_modules\\fstream\\lib\\writer.js:284:26',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\Lewis\\AppData\\Local\\atom\\app-0.156.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Lewis\\AppData\\Local\\atom\\app-0.156.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Lewis\\AppData\\Local\\atom\\app-0.156.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Lewis\\.atom\\.apmrc" "install" "C:\\Users\\Lewis\\AppData\\Local\\Temp\\d-1141112-2536-npdbms\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map\README.markdown
npm ERR! fstream_path C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map\README.markdown
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, lstat 'C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z\node_modules\autocomplete-plus\node_modules\minimatch\node_modules\brace-expansion\node_modules\concat-map\README.markdown'
npm ERR! fstream_stack c:\Users\Lewis\AppData\Local\atom\app-0.156.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat 'C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z\node_modules\autocomplete-plus\node_modules\atom-space-pen-views\node_modules\grim\node_modules\emissary\lib\subscriber.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\Lewis\\AppData\\Local\\atom\\app-0.156.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Lewis\\AppData\\Local\\atom\\app-0.156.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Lewis\\AppData\\Local\\atom\\app-0.156.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Lewis\\.atom\\.apmrc" "install" "C:\\Users\\Lewis\\AppData\\Local\\Temp\\d-1141112-2536-npdbms\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z\node_modules\autocomplete-plus\node_modules\atom-space-pen-views\node_modules\grim\node_modules\emissary\lib\subscriber.js
npm ERR! fstream_path C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z\node_modules\autocomplete-plus\node_modules\atom-space-pen-views\node_modules\grim\node_modules\emissary\lib\subscriber.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack c:\Users\Lewis\AppData\Local\atom\app-0.156.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\node_modules\fstream\lib\writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Users\\Lewis\\AppData\\Local\\atom\\app-0.156.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\Lewis\\AppData\\Local\\atom\\app-0.156.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Lewis\\AppData\\Local\\atom\\app-0.156.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\Lewis\\.atom\\.apmrc" "install" "C:\\Users\\Lewis\\AppData\\Local\\Temp\\d-1141112-2536-npdbms\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\Lewis\AppData\Local\Temp\apm-install-dir-1141112-2536-1opq1z
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/property-accessors
npm

**Comment by kevinsawicki** [comment]
This looks like an issue with installing a package that requires Git but Git not being installed or detected by `npm`. There is now better support for this in `apm` and so I'm going to close this out since the message is more informative now.
