### ISSUE TITLE
Empty files after opening Atom

### ISSUE THREAD

**Issue by Dharmoslap** [atom/atom#4573]
Every time after I open Atom the new empty "untitled" file is being created. Makes sense.
Problem is, that after I close Atom, this "untitled" file stays there and if I reopen Atom the number of "untitled" files is increasing.

![screen shot 2014-12-12 at 13 20 17](https://cloud.githubusercontent.com/assets/3543614/5411533/b0942e64-8201-11e4-838f-400d131fbbf2.png)

**Comment by 50Wliu** [comment]
What I'd prefer is for the Untitled tab to get replaced with the first file you select *if you have not touched the Untitled tab*.  I don't mind it at all except that I have to manually close it each time I open a new window followed by an existing file.  Otherwise, just replicate the current behavior which is to open up the new file in a separate tab.

**Comment by jorangreef** [comment]
It would be better if the untitled editor was only ever opened the very first time that Atom runs (for the benefit of novice users). Thereafter it should never open an untitled editor unless requested. Having to press CMD+Shift+W all the time is huge waste of time IMHO. Most of the time, I would prefer if Atom just opened the last folder I had open before quitting Atom (or restarting my machine).

**Comment by jonathandelgado** [comment]
+1 for removing it all together, as @mark-hahn said, it's pretty easy to press `ctrl-n`. I can't remember the last time I actually used it, I just open project folders.

**Comment by jorangreef** [comment]
It would be great if this could be fixed soon. Or at least an option under settings to disable it.

**Comment by jorangreef** [comment]
I just noticed this morning that when Atom is first started on Mac, it creates the untitled editor (would be great if it didn't do that every time), but then when this editor is closed, and the Atom icon in the dock is clicked again (Atom is already running now), it opens another new untitled editor.
