### ISSUE TITLE
Atom crashing reproducibly immediately after update

### ISSUE THREAD

**Issue by cobyism** [atom/atom#4574]
This morning, I clicked the blue squirrel in the corner, opted to update and restart via the button at the bottom of the release notes, and now whenever I launch atom I see an empty window, and a disembodied alert pane telling me I should report the issue. Screenshot:

![2014-12-12 at 12 12 pm](https://cloud.githubusercontent.com/assets/296432/5411452/80be8422-81f8-11e4-8b1b-4da8e2b294e0.png)

Notes:
- I can’t get to a usable atom editor by clicking any of the three buttons in the alert pane.
  - clicking "reload" just makes the alert pane show up again (this time connected to the atom window).
  - clicking "keep it open" just dismisses the alert pane, leaving me with an empty atom window.
  - clicking "close window" hangs for approx ~1s and then closes the window, leaving atom running, but with no open windows.
- The behaviour is the same whether I start atom from the terminal, or via Finder.
- `atom --safe` and `atom --dev` both produces the same behaviour.
- `atom --version` shows `0.157.0`.

**Comment by devios1337** [comment]
Atom 0.176 editor is crashing for me immediately after the update whenever I try to open a window.

Crash report: https://gist.github.com/devios1337/c0dcab382613cb89e43d

**Comment by benogle** [comment]
cc @zcbenz

**Comment by lee-dohm** [comment]
@lsc95 Please open a new Issue and specify if you can reproduce the crash. It doesn't sound like your crash has anything to do with updating Atom.
