### ISSUE TITLE
graphic glitches in scrollbar

### ISSUE THREAD

**Issue by kmdavis** [atom/atom#4578]
![screen shot 2014-12-12 at 12 00 49 pm](https://cloud.githubusercontent.com/assets/132806/5415627/96ce01f4-81f6-11e4-8757-83fe153488bf.png)

**Comment by kmdavis** [comment]
[CLUE] It happened to me a again -- immediately after resizing the treeview (with the scrollbar visible), and I also got this artifact after scrolling up and down a few times:

![screen shot 2015-01-05 at 10 32 05 am](https://cloud.githubusercontent.com/assets/132806/5615133/310a4ca0-94c6-11e4-85ae-9d29e4e74ab2.png)

**Comment by kmdavis** [comment]
Again, this time I renamed a file (green line in the screenshot):

![screen shot 2015-01-05 at 10 35 25 am](https://cloud.githubusercontent.com/assets/132806/5615177/ab0bac9c-94c6-11e4-8f0e-5428c8caa68a.png)

**Comment by simurai** [comment]
Tested some more and changing to an opaque background color really seems to help. @dteskera thanks for your suggestion. Should be fixed in the next update of the "Atom Dark UI" theme.

**Comment by netmou** [comment]
![qq 20150108193925](https://cloud.githubusercontent.com/assets/7068058/5662059/907338b4-976e-11e4-8ad7-56714ac69398.png)
atom  v0.168.0 win7x64   in safe mode
