### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined

### ISSUE THREAD

**Issue by benogle** [atom/atom#4582]
_From @benogle on December 11, 2014 17:11_

_From @Trudko on December 2, 2014 20:8_

Hi, I am getting error Uncaught TypeError: Cannot read property 'tokenAtBufferColumn' of undefined.

Steps to reproduce:
1. Open Atom with atom --safe.
2. Create new lines.
3. Select them.
4. Use command Editor: Split Selections Into lines.
5. Write something.
6. Press escape to cancel multi selection.
7. Run Core:Undo.
8. Run Core:Undo for second time.

Gif with example:

![](https://virtual-host-discourse.global.ssl.fastly.net/uploads/github_atom/25437/cc83b11b0d27552d.gif)

[Whole stack trace.](https://gist.github.com/Trudko/cab20d6a4f6299bd44e9)

I have tried this on Windows 7 Pro and Ubuntu 14.04 both running Atom 0.152. I might try this on Windows 8 if this helps

Issue seems similiar to https://github.com/atom/atom/issues/3187.

_Copied from original issue: atom/atom#4376_

_Copied from original issue: atom/bracket-matcher#90_

**Comment by 50Wliu** [comment]
Cannot reproduce on Atom 1.9.0-dev-02d7bde, assuming fixed.
