### ISSUE TITLE
wrong cursor location with multi-byte characters

### ISSUE THREAD

**Issue by takasek** [atom/atom#4595]
Atom 0.158 on Mac OS.

![atom](https://cloud.githubusercontent.com/assets/1290052/5423732/913a5ebc-830f-11e4-841e-33e31ea2652f.gif)

Pushing up/down arrow key,  I expected the cursor to move to the nearest location vertically.
tab indent also seems to be laid out in wrong way.

**Comment by kumarrishav** [comment]
@lee-dohm Can you help in this. I mean how to tackle this issue and where code lies (as codebase is huge). What approach should be considered. What basic idea got is, have a constant left (follow the left: a px;) of it's previous cursor.
