### ISSUE TITLE
Hide system window title bar

### ISSUE THREAD

**Issue by dustContributor** [atom/atom#4599]
Hi! Could it be possible to implement system window title bar/borders hiding like Chromium/Chrome has?

If you have used Chromium/Chrome you can notice it lacks the "system window title bar" by default (ie, the bar that says the name of the window and has the minimize, maximize and close buttons), while at the same time providing its own tiny minimize, maximize and close buttons in the top, rightmost part of the window.

Some window managers for Linux let you hide the window title bar, but since Atom lacks its own minimize/maximize/close buttons, it becomes inconvenient. Besides, it would be something nice to have in Windows/OSX too.

IMHO, this feature manages to save (precious!) vertical space, and looks much more pleasant.

EDIT: Made a discussion thread about this https://discuss.atom.io/t/hide-system-window-title-bar/14578

**Comment by mnquintana** [comment]
Ooooh, this would be pretty cool. I don't know if there should be no title bar by default, but having a config setting for it would be nice. I think whether or not this is currently possible to implement would depend on [atom-shell](https://github.com/atom/atom-shell), and not really Atom core. @zcbenz would this be possible with atom-shell?

**Comment by zcbenz** [comment]
@mnquintana Yeah it is possible with [frameless window](https://github.com/atom/atom-shell/blob/master/docs/api/frameless-window.md).

**Comment by luqmaan** [comment]
If you want a borderless window now, just add

```js
transparent: true,
frame: false,
```

to https://github.com/atom/atom/blob/master/src/browser/atom-window.coffee#L26-L31

![image](https://cloud.githubusercontent.com/assets/1275831/6157402/abbc7d1c-b206-11e4-85f8-0ca66ac576dd.png)

**Comment by dustContributor** [comment]
I'm pretty sure I explained thoroughly what I want and it isn't a plain borderless window (much less one that doesn't uses the gained space like you're showing), you should read the OP and the linked discussion.

**Comment by dustContributor** [comment]
Nevermind, I tried it and I can maximize the window just fine, it also removes the menu bar sadly :cry:

**Comment by mathieucivel** [comment]
@luqmaan thanks, I have now retrieved the perfect distraction free mode I used to like on Sublime. 

I guess there is now way to keep the change across versions yet ?

**Comment by yutzhead** [comment]
Also relevant: http://askubuntu.com/questions/75284/remove-titlebar-from-maximized-terminal-window

**Comment by bramcordie** [comment]
@luqmaan I tries the borderless window trick but with version 1.0 the file seems to have moved to _Atom.app/Contents/Resources/app.asar/src/browser/atom-window.js_. Whenever I change it and restart the editor, the changes are gone.

**Comment by mnquintana** [comment]
For anyone following this, here's some more discussion / background: https://discuss.atom.io/t/hide-system-window-title-bar/14578?u=mnquintana

**Comment by tj** [comment]
:+1: this would be really nice, the native one looks pretty out of place for most themes

**Comment by BeamerCola** [comment]
![screen shot 2015-11-02 at 11 51 01 am](https://cloud.githubusercontent.com/assets/8060/10927444/b5924866-8254-11e5-8f62-b30603027ad0.png)

Hey all, so I ended up just hacking this together yesterday.  It works really well overall.

Repos here:
* https://github.com/BeamerCola/atom
* https://github.com/BeamerCola/tree-view
* https://github.com/BeamerCola/tabs

If you use the one-dark-ui package, there was a slight change i made to it that's here:
* https://github.com/BeamerCola/one-dark-chromeless-ui

I'll hopefully be tidying this up and submitting a pull request.  Love to hear your thoughts.

**Comment by dustContributor** [comment]
I'm more of a fan of the close/minimize icons to the right. Although as a second best option, I'd choose yours.

**Comment by simurai** [comment]
@BeamerCola That looks slick.

Is there a plan to do the same for Windows and Linux? Or OS X only? Also, is it technically possible to have it as a setting in Atom? Just thinking some people might miss the title with the name/path.

**Comment by abe33** [comment]
@BeamerCola Nice work here, would like to see it available as well. 

I also agree with @simurai that it should be a toggled through a setting.

**Comment by davidpelaez** [comment]
This with iTerm2 on OS X would make a great match.

**Comment by flipbug** [comment]
@BeamerCola Great work! Would love to see the pull request. 
This works especially well with the dark menu bar on osx

**Comment by BeamerCola** [comment]
@flipbug @abe33 well thanks!  needs a bit more work to be official enough that they'd accept a pul request.  I'll try to find the time

**Comment by BeamerCola** [comment]
@simurai So this is using native Yosemite APIs, it's not custom UI.  So up to Windows or Linux guys to change it to fit their OS.  And yes, it'd probably have to be a setting.  Things I'll likely never get around to unfortunately

**Comment by williambout** [comment]
@BeamerCola Really nice work.

**Comment by chl1996** [comment]
🆙

**Comment by dimatter** [comment]
🆙

**Comment by treiber** [comment]
🆙

**Comment by tj** [comment]
:camel:

**Comment by victorbotamedi** [comment]
Up!

**Comment by joaodallarosa** [comment]
Up!

**Comment by alekzonder** [comment]
Up!

**Comment by 50Wliu** [comment]
Please refrain from adding "+1" comments or similar (in this case, "Up!") and instead add a reaction to the original comment.  Thanks!

**Comment by The-Penultimate-Defenestrator** [comment]
@BeamerCola Have you submitted a PR? If not, you should. FYI, [this](https://github.com/atom/atom/pull/11790) would also be a _huge_ improvement when/if it is merged.

**Comment by BeamerCola** [comment]
@controversial I haven't yet - unfortunately it requires a lot of unit tests and making sure it works cross-platform.  You guys are welcome to fork it and do that.  Would be happy to see it cross the finish line.

There's a bug in OS X with these windows where they jump around a lot, but I don't think that's anything we can solve.

**Comment by controversial** [comment]
@BeamerCola Ok, thanks. I'm stupid at anything besides Python and JavaScript, so I'm afraid I won't be of much use. Glad to have an update, though.

**Comment by BeamerCola** [comment]
@controversial well this is all javascript bruh so get to it! ;)

**Comment by controversial** [comment]
@BeamerCola How different is CoffeeScript's syntax?

**Comment by BeamerCola** [comment]
@controversial you'll be fine.  I don't mess with CS, but all the examples on the coffeescript site make it easy to fumble through.  Atom dev environment is really great

**Comment by controversial** [comment]
Ok. I’ll give it a look soon. Thanks :thumbsup:

**Comment by simurai** [comment]
@controversial Just a quick update before you jump into coding: By removing the native title bar, we would loose the functionality of the [proxy icon](https://github.com/atom/atom/pull/11790#issuecomment-222168228). Reimplementing that isn't easy.

Adding a [config to hide the title bar](https://github.com/atom/atom/pull/11790#issuecomment-222191019) might be an alternative, but it would be the first config that is platform specific and that needs a reload of Atom.

**Comment by controversial** [comment]
I won't be jumping into coding any time soon, but thanks.

**Comment by deeperx** [comment]
# Full Recipe

```
npm -g install asar 
asar e /Applications/Atom.app/Contents/Resources/app.asar /tmp/atomasar

# edit atom-window.coffee & add:
# frame: false
# after the line title: 'Atom'
# save

asar p /tmp/atomasar /Applications/Atom.app/Contents/Resources/app.asar
mv -f /tmp.atomasar
```

**Comment by hyiltiz** [comment]
It should be merged back into Atom Dark themes as an option by now :( Having to deal with separate repos diminishes all those goodies that Atom promises by being friendly (and hackable, but enough hacking for almost two years on this feature?)

**Comment by peterpme** [comment]
Hey @deeperx!

Thanks for your awesome tip! I'm assuming if i want to go down this path I have to build atom from source, right?

**Comment by deeperx** [comment]
@peterpme np! Not exactly. With the delicious recipe above, we just adjusting a file inside a tar-like compressed package with `asar`. See more of `asar` here: https://github.com/electron/asar

**Comment by peterpme** [comment]
@deeperx thank you for the speedy response! I guess that brings me to my next question - haha.

When I run the recipe commands I can't seem to find atom-window.coffee anywhere!

Does that file exist within the asar?

Thanks again!

**Comment by deeperx** [comment]
@peterpme hi there, np! I've just updated the recipe and tested it again. Now, you can do it.

**Comment by peterpme** [comment]
You are awesome! Thank you

**Comment by peterpme** [comment]
Hey @deeperx,

Just for the sake of documentation, I had to open up `/src/main-process/atom-window.js` to make the change :)

**Comment by deeperx** [comment]
@peterpme Yeah, I'd updated the code regardingly already.

**Comment by frizadiga** [comment]
I got this error on my console, what the problem?

C:\Users\hiuWave\AppData\Roaming\npm>asar e app.asar a
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\hiuWave\AppData\Roaming\npm\app.asar.unpacked\node_modules\cached-run-in-this-context\build\Release\cached-run-in-this-context.node'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.module.exports.readFileSync (C:\Users\hiuWave\AppData\Roaming\npm\node_modules\asar\lib\disk.js:122:19)
    at Object.module.exports.extractAll (C:\Users\hiuWave\AppData\Roaming\npm\node_modules\asar\lib\asar.js:223:24)
    at Command.<anonymous> (C:\Users\hiuWave\AppData\Roaming\npm\node_modules\asar\bin\asar:59:15)
    at Command.listener (C:\Users\hiuWave\AppData\Roaming\npm\node_modules\asar\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\Users\hiuWave\AppData\Roaming\npm\node_modules\asar\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\hiuWave\AppData\Roaming\npm\node_modules\asar\node_modules\commander\index.js:458:21)

**Comment by KamranMackey** [comment]
@frizadiga That is completely unrelated to Atom and is in the wrong issue. Report that issue at the asar repo, please.

**Comment by lexicalunit** [comment]
Using the _Custom Title Bar_ feature we can achieve a hidden window title bar while still maintaining the ability to drag-and-drop things like editor tabs and `tree-view` entries. To make it work I added window draggability basically everywhere, and then specifically disabled it where we don't want it (tabs, `tree-view` entires, the editor itself, etc...). Seems to be working fairly well.

https://atom.io/packages/no-title-bar

**Comment by inancgumus** [comment]
# Solution without a plugin:

```cson
##### Atom Menu > Config ##### 
core:
  useCustomTitleBar: true
```

```sass
// ##### Atom Menu > Stylesheet ##### 

// Append this there:

// Hide title
.title-bar .title {
  display: none;
}

// Remove background from titlebar and toolbars
.title-bar,
.tool-bar,
.tool-bar button.tool-bar-btn {
  background-color: transparent;
  border-width: 0;
}

// Shift the tabs up
atom-workspace atom-workspace-axis.horizontal {
  // NOTE: comment this out if you want draggable titlebar:
  margin-top: -20px;
}

// Keep the side panels aligned
atom-panel-container{
  &.left {
    margin-top: 20px;
  }
  &.right {
    margin-top: 20px;
  }
}

.fullscreen {
  atom-workspace atom-workspace-axis.horizontal {
    margin-top: 0px;
  }
  atom-panel-container{
    &.left {
      margin-top: 0px;
    }
    &.right {
      margin-top: 0px;
    }
  }
}

atom-workspace atom-panel-container.left:empty + atom-workspace-axis.vertical .tab-bar {
  margin-left: 70px;
}
```

[For more information about how I achieved to this solution](https://github.com/atom/atom/pull/10208)

**Comment by lexicalunit** [comment]
@inancgumus Yep, my package is nothing more than a stylesheet based on the same sources you mentioned, so this should work just fine for those who don't want to install a package 👍 

One nice thing about using a package is that people can open issues against it and we can iterate over them as a community, continually improving the solution. For example, there's two bugs in the code you posted:

1. You will lose tabs completely in fullscreen mode. You can fix this by changing the `atom-workspace` selector to something like `:not(.fullscreen) > atom-workspace`.
2. With the `tree-view` toggled off and the editor panes split vertically, all panes except the first will have `margin-left: 70px` incorrectly applied to them. You can fix this by using an `nth-child` selector like so: `atom-panel-container.left:empty + atom-workspace-axis.vertical .pane:nth-child(1) .tab-bar`.

Also you no longer have to choose between draggable tabs and a draggable window. I've updated my package to support both at the same time 😄

**Comment by balupton** [comment]
Anyway to get rid of the traffic lights? I have keyboard hotkeys for them.

**Comment by elliotbonneville** [comment]
@balupton Did you ever find a way to hide the traffic lights?

**Comment by simurai** [comment]
Completely hiding the title bar:

- [x] macOS: Will land in Atom `1.16` 👉  https://github.com/atom/atom/pull/13616
- [ ] Win/Linux: Open issue 👉  https://github.com/atom/atom/issues/13249

**Comment by elliotbonneville** [comment]
Thanks! I found that not long after I posted here. 

For the impatient: I compiled the latest version of of the `master` branch on macOS and it works great there.

**Comment by miguelsmuller** [comment]
Is it going to be released a version for windows that I can do this?
The title bar of windows is very ugly

**Comment by DFNCTSC** [comment]
@maxbrunsfeld @50Wliu @leroix @jasonrudolph @matthewwithanm 

Can someone please take a look at this and implement it? 

I think a lot more Windows users would convert to Atom if the program looked like the screenshots they see on the website before downloading it, right?

Shouldn't be too hard considering to enable it on MacOS it's changing a single value.

<3
