### ISSUE TITLE
Uncaught Error: ENOENT, open ''

### ISSUE THREAD

**Issue by comeontom** [atom/atom#4615]
Uncaught Error: ENOENT, open ''

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At stream.js:94

Error: ENOENT, open ''
  at Error (native)

```

**Comment by kevinsawicki** [comment]
This error message should no longer display as an uncaught error in Atom 0.173.0 or later, see #4906 for more details.
