### ISSUE TITLE
Incorrect git status on OS X when accented characters are used in file names

### ISSUE THREAD

**Issue by morberg** [atom/atom#4637]
When an accented character (e.g. åäö, but probably other unicode characters as well) is used in a file name the git implementation in Atom on OS X thinks that the file is new, even though it exists on github. You can test with this repo (small, markdown files only):

`git clone https://github.com/morberg/recept.git`

Open root folder in atom and look at the incorrect status in the left tree navigation.

Problem is seen with Atom 0.158.0 on OS X 10.10.1:
![screen shot 2014-12-16 at 09 03 48](https://cloud.githubusercontent.com/assets/956034/5450195/84f191da-8502-11e4-9f01-685719d6dc47.png)

Problem is *not* seen with Atom 0.158.0 on Windows 7 SP 1.
![screen shot 2014-12-16 at 09 04 45](https://cloud.githubusercontent.com/assets/956034/5450203/a25e5c1c-8502-11e4-977f-3f64a6bbb69a.png)

**Comment by andrewringler** [comment]
Replicated on Atom v0.179.0 on Mac OS-X 10.10.2

**Comment by izuzak** [comment]
This looks like a duplicate of https://github.com/atom/atom/issues/1890, let me know if I misunderstood the report, though.

**Comment by andrewringler** [comment]
Thanks!

Andrew
