### ISSUE TITLE
Atom automatically opens up old Atom install folder after updating

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#4653]
Does not happen once you close Atom and reopen it again.  Windows 7 x64.
![bad](https://cloud.githubusercontent.com/assets/2766036/5463427/bf1cf370-854a-11e4-8ce3-800a6336e0d4.png)
Possibly related to the new `atom.cmd|sh` startup scripts?

**Comment by 50Wliu** [comment]
This is back.  Just updated to 0.182.0 from 0.179.0, though I'm pretty sure it also happened 0.174.0-->0.179.0.

![bad](https://cloud.githubusercontent.com/assets/2766036/6316282/8d190ae2-b9ef-11e4-8a66-81dc24bf6395.png)

**Comment by mnquintana** [comment]
@50Wliu Is this still an issue?

**Comment by 50Wliu** [comment]
I believe so, but I haven't been able to repro recently because of #5692.

**Comment by 50Wliu** [comment]
Closing - no new reports and I've been building Atom from source lately.
