### ISSUE TITLE
Reloading files changed externally only works once

### ISSUE THREAD

**Issue by gidoca** [atom/atom#4663]
When a file is opened in Atom and then changed in some external application, such as git, it is reloaded only once. Subsequent external changes are not reflected in the Atom text buffer. 
## Repro Steps
1. Open a file in a git repository in Atom
2. Make some changes and save
3. Stash the changes: `git stash`
4. Reapply the changes: `git stash pop`

**Expected:** Atom should show the state of the file after step 2
**Actual:** Atom shows the original file, as it was after `git stash`
## Command History

```
     -0:03.5 editor:will-be-removed (atom-text-editor#editor.scrollSensitivity.editor.editor-colors.mini)
     -0:03.5 editor:detached (atom-text-editor#editor.undoGroupingInterval.editor.editor-colors.mini)
     -0:03.5 editor:will-be-removed (atom-text-editor#editor.undoGroupingInterval.editor.editor-colors.mini)
     -0:03.5 editor:detached (atom-text-editor.editor.editor-colors.mini)
     -0:03.5 editor:will-be-removed (atom-text-editor.editor.editor-colors.mini)
     -0:03.5 pane:item-removed (atom-pane.pane.active)
     -0:02.0 command-palette:toggle (input.hidden-input)
     -0:00.6 core:backspace (input.hidden-input)
     -0:00.0 core:confirm (input.hidden-input)
     -0:00.0 bug-report:open (input.hidden-input)
```
## Versions
- **Atom:**       0.158.0
- **Atom-Shell:** 0.19.4
- **OS:**         linux 3.16.0-28-generic
- **Misc**
  - apm  0.114.0
  - npm  1.4.4
  - node 0.10.33
  - python 2.7.8
  - git 2.1.0

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.5.3.</small>

**Comment by izuzak** [comment]
@gidoca Can you still reproduce the problem with Atom 1.0.11? 

Also, in your last comment you said "I think it may actually be a problem with OpenAFS. In a first test, the issue did not appear in a directory on an ext4 FS. Did you perhaps confirm this and open an issue on OpenAFS? Do you see that problem on OpenAFS with other editors, or just with Atom?

**Comment by gidoca** [comment]
At one point, I saw what seemed to be the same problem also on ext4, but it was much harder to reproduce. I therefore suspect that it may have been some kind of race condition which manifested itself more often due to the distributed nature of OpenAFS. However, I stopped using Atom after this, and I no longer work at the place where we used OpenAFS. I will try if I can still reproduce it on ext4.
