### ISSUE TITLE
generated sample app html question

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#4673]
The generated sample app now generates the html programmatically.  This is obviously something no one would consider doing in real life.  This has two problems.  It doesn't show the idiomatic method and it is no good as a template to start adding to.

What is the idiomatic way?  Is there an equivalent way to space-pen?  There is a cool npm module call `teacup` which seems to be the inspiration for space-pen.  Has anyone tried that?

**Comment by basarat** [comment]
What's the update on this. As far as I can tell `space-pen-views` is the way to go for new development?

**Comment by mnquintana** [comment]
@basarat You can track https://github.com/atom/atom/issues/5756 for updates on this.
