### ISSUE TITLE
Can't type : < > and = with Neo Keyboard Layout on Mac OS X

### ISSUE THREAD

**Issue by screendriver** [atom/atom#4680]
I am running Atom 0.161.0 on Mac OS X Yosemite and use the [German Neo Layout](http://www.neo-layout.org/). Unfortunately I can't type the characters : < > and =. In other applications (Browser, Email and so forth) it works as expected.
I am aware of the issues atom/atom-keymap#35, #1625 and #3834 but these are only for the "right ALT" key.

**Comment by Crenshinibon** [comment]
Same issue here, with 1.0.11. Did you find out which key-bindings had to be changed to get those keys working again.

**Comment by screendriver** [comment]
My current workaround is to use [atom-keyboard-localization](https://github.com/andischerer/atom-keyboard-localization) and set `de-DE-neo` in the layout settings.

**Comment by mnquintana** [comment]
This does look like the same issue as https://github.com/atom/atom-keymap/issues/37 to me, so I'm going to close this out in favor of that issue (it's not specific to the German keyboard layout, but rather any non-US keyboard layout). Let me know if I'm misunderstanding though!

**Comment by Crenshinibon** [comment]
@screendriver thanks, I fixed the issue by using that package and layout.

**Comment by screendriver** [comment]
@Crenshinibon you're welcome :sunglasses:
