### ISSUE TITLE
Option for "Open with Atom" 

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#4695]
Is there an option to disable the "Open with Atom" shell entry? I can't find one, if there isn't, see this as a feature request :)

**Comment by Moter8** [comment]
:+1: Could be very annoying for some people.

**Comment by Moter8** [comment]
To cite @leranus:

>[There should be] a preference where it can be turned off or on entirely, or just for specific files and folders. For example, not many people will open images from Explorer with Atom.

**Comment by leranus** [comment]
And as was pointed out, the specific code which adds and removes the "Open with Atom" item is in https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee.

**Comment by laktak** [comment]
:+1:

**Comment by Hrxn** [comment]
The same here..

New Atom user, works good so far, but the installer integrates stuff into the Windows shell WITHOUT ASKING. Not nice...

This should be opt-in, definitely.

One simply does not write stuff into system keys like HKEY_CLASSES_ROOT\*, directory etc. without asking the user.

**Comment by Hrxn** [comment]
Is this issue still relevant?

Labeled as 'enhancement' hence nobody cares :-)

Should every user modify
> https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee
themself?

If the option in question will not make it into Atom, maybe provide a simple script executing Update.exe with the specific flags?

To quote a comment from another issue by @paulcbetts

> This might be nice to have as a preference in Atom, so that folks who don't want the menus can disable them. While Atom works far better if you open folders rather than files, I also can totally see not wanting Atom on every folder's menu

**Comment by Hrxn** [comment]
Okay, I hacked something together...

Remove Windows Shell integration:
```batchfile
@echo off
C:
cd %LocalAppData%\atom\bin\
for /f "delims=" %%g in (atom.cmd) do set _atom=%%g
set _atom=%_atom:~10,9%
cd ..
cd %_atom%*
atom.exe --squirrel-uninstall
```
This should do the trick..

It's quite an ugly hack, but the Update.exe in %LocalAppData%\atom does not work.
Using the --uninstall switch here deletes the whole atom app dir, so we need atom.exe, it seems.

**Comment by paulcbetts** [comment]
@Hrxn You don't have to run it on every folder, just on the latest one

**Comment by Hrxn** [comment]
Uh, yes?!

That's what I am trying to do..

The most straightforward way would have been to just use `cd %LocalAppData%\atom\app-*` , but this has some potential for failure. I haven't tried it myself, but CMD normally just sorts by alphanumeric value, just as the TAB autocompletion, so you might end up in a situation where you want to go ...app-2.x.y but land in app-1.x.y instead.

The other choice would be something along the lines of `where /r %LocalAppData%\atom atom.exe` , but this doesn't really help either. You can find the correct path, but not without jumping through some ridiculous hoops. Definitely not within the scope of a basic script.

So I looked for a file where the correct path is stored, and `atom.cmd` in `\atom\bin` seems to be right. Not sure if this is true, or if it stays this way, but still better than just guessing.

The script works for now, that is what really matters in the end.

**Comment by mnquintana** [comment]
Closing in favor of https://github.com/atom/atom/issues/5901
