### ISSUE TITLE
Add Downloading Update progress

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#4696]
Basicly what the title says, I don't know how much it downloaded now because it has no progress indicator but I've had atom open for over 30minutes now and the update has not finished downloading. That seems wrong.

**Comment by MartinPeverelli** [comment]
+1

**Comment by muhammad-saleh** [comment]
+1 (I've a slow connection this would be super helpful)

**Comment by JosephTLyons** [comment]
Atom is the best editors on the market now that the performance issues have been addressed, but I can't understand, for the life of me, why the updates (package and Atom itself) have no progress bar.

**Comment by jhabdas** [comment]
@Stanzilla would you kindly reopen this issue? I'm on a slow network connection and am having trouble determining if I should switch networks to complete the installation without being able to know the amount of the total for the download. All I see is a busy signal during the update:

<img width="514" alt="screen shot 2017-06-05 at 5 08 36 pm" src="https://cloud.githubusercontent.com/assets/440298/26778012/0613da08-4a12-11e7-8d8d-ef9a5a46d215.png">
