### ISSUE TITLE
New windows are not maximized

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#4697]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd> opens up a new, *non-maximized* window on Windows.  This results in some graphical issues as described in #2936.
However, opening up a folder (which opens up a new window after the first time, which is a different bug-#3406) using <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd> or Open in Atom works fine.

Windows 7 x64, Atom 0.162.0.

**Comment by 50Wliu** [comment]
I can't reproduce this anymore.  The window starts up un-maximized but once it initializes properly maximizes itself.

**Comment by jarnix** [comment]
Hello, I still have this issue on Windows 10, using the 1.6.2 version. I have to maximize the editor every time I start it. And it's the same thing with new windows (ctrl + shift + n).
