### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by Xatpy** [atom/atom#4708]
Uncaught Error: write EPIPE

**Atom Version**: 0.161.0
**System**: Mac OS X 10.10
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At events.js:85

Error: write EPIPE
  at exports._errnoException (util.js:742:11)
  at Object.afterWrite (net.js:749:14)

```

**Comment by djpowers** [comment]
Back again! Currently able to reproduce reliably.

In an .html.erb file here is an example of the syntax that triggers the error:

```erb
<%= if @instance_variable %>
  function();
<% end %>
```

Commenting out the JavaScript function line triggers a linter error, as well as the Atom error.

My stack trace is slightly different:
```
Error: write EPIPE
  at exports._errnoException (util.js:746:11)
  at Object.afterWrite (net.js:757:14)
```
I'm using Atom 0.175.0 on OS X 10.9.5.

I cannot reproduce the error in safe mode, so I suspect it may be related to the linter/linter-erb packages.

**Comment by benogle** [comment]
@djpowers is this file local? Can you save the file just fine?

**Comment by djpowers** [comment]
@benogle, yes the file is local.

I can save, however, if the syntax error that caused the initial error is still present, each save will trigger an additional error of the same type. Fixing the syntax issue allows me to save without generating any warnings.a

Currently I can trigger it by changing `<% if @instance_variable %>` to `<%= if @instance_variable %>`.

**Comment by algolicious** [comment]
I am getting this error when I save a c++ file :(

**Comment by benogle** [comment]
From #5320 cc @gttiankai 

**Atom Version**: 0.174.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:85

Error: write EPIPE
  at exports._errnoException (util.js:746:11)
  at Object.afterWrite (net.js:757:14)

```

### Commands

```
 29x -0:42.2 core:move-down (atom-text-editor.editor.is-focused)
 11x -0:40.7 core:move-up (atom-text-editor.editor.is-focused)
  9x -0:39.9 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:39.1 core:move-up (atom-text-editor.editor.is-focused)
     -0:38.2 core:move-left (atom-text-editor.editor.is-focused)
     -0:37.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.0 clang-format:format (atom-text-editor.editor.is-focused)
     -0:23.9 core:select-all (atom-text-editor.editor.is-focused)
     -0:19.8 clang-format:format (atom-text-editor.editor.is-focused)
     -0:15.8 core:move-left (atom-text-editor.editor.is-focused)
     -0:15.2 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:15.2 snippets:expand (atom-text-editor.editor.is-focused)
     -0:15.2 editor:indent (atom-text-editor.editor.is-focused)
     -0:14.2 core:save (atom-text-editor.editor.is-focused)
     -0:01.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 17,
    "lineHeight": 1.4,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.6.1
clang-format, v1.7.0
monokai, v0.12.0

# Dev
No dev packages
```

**Comment by basarat** [comment]
Happened for me. Turns out my bug. I was writing to a child process that was terminated.

**Comment by benogle** [comment]
@djpowers What packages do you have installed? can you `apm list`? Try `atom --safe`. it sounds like a maybe a linter or some package trying to save the file.

**Comment by djpowers** [comment]
@benogle, here are the packages I've installed:

```
/Users/[user_name]/.atom/packages (9)
├── color-picker@1.4.4
├── linter@0.11.1
├── linter-coffeelint@0.1.7
├── linter-erb@0.1.0
├── linter-jshint@0.1.0
├── linter-ruby@0.1.4
├── linter-scss-lint@0.0.11
├── minimap@4.2.3
└── vim-mode@0.32.0
```

I tried safe mode previously, and I did not see any errors while testing. Based on where I've noticed the problem being triggered, I suspect it has to do specifically with the linter-erb package, so I had opened an [issue](https://github.com/AtomLinter/linter-erb/issues/4) there.
