### ISSUE TITLE
Uncaught Error: read ECONNRESET

### ISSUE THREAD

**Issue by SamuelMoy** [atom/atom#4710]
Uncaught Error: read ECONNRESET

**Atom Version**: 0.162.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At stream.js:94

Error: read ECONNRESET
  at exports._errnoException (util.js:742:11)
  at TCP.onread (net.js:535:26)

```

**Comment by benogle** [comment]
Can you give us a little more info? What packages were you using? Can you try in safe mode (quit atom completely and run `atom --safe`)? Can you reproduce this on a regular basis? What are the steps?

**Comment by framerate** [comment]
I just hit this too and wasn't doing anything. I was fullscreen mode in OSX and I had moved to my chrome full-screen window to watch a youtube video. Came back and Atom had 2 of these errors.

**Comment by GeoffreyPlitt** [comment]
Happens to me all the time. How best to capture logs/debug info and share here?

**Comment by pgkos** [comment]
Happened to me while using autocomplete-plus (version 2.9.0) with Python provider (autocomplete-plus-python-jedi 0.2.5).

After this error had occurred, autocomplete-plus completely stopped working (both in Python and in other languages) until restart.

(I am using Atom 0.190.0 on Ubuntu 14.04)

**Comment by Thor77** [comment]
happens to me with latest autocomplete-plus-python-jedi and autocomplete-plus.
My steps to reproduce:
* Open any .py-file
* do any import with `from lib import Class_or_function`
* error occurs at `from lib `

**Comment by pgkos** [comment]
I can confirm what @Thor77 said, it often happens when writing `from lib import ...`
Here is the message:
```
Uncaught Error: read ECONNRESET
events.js:141
Error: read ECONNRESET
    at exports._errnoException (util.js:734:11)
    at Pipe.onread (net.js:538:26)
```

**Comment by tinloaf** [comment]
Huh! This definitely is a bug in the autocomplete-plus-python-jedi provider (or Jedi itself). I'll look into it!

**Comment by tinloaf** [comment]
Sometimes, Jedi is throwing exceptions I cannot explain. I just pushed version 0.2.6 of autocomplete-plus-python-jedi, which just catches *all* exceptions coming from Jedi. That's not clean, but it should work.

Please make sure you upraded to 0.2.6 and tell me if you still experience this problem.

**Comment by pgkos** [comment]
I have upgraded to 0.2.6 and now it works perfectly! Thank you.
