### ISSUE TITLE
Uncaught Error: EEXIST, file already exists '/Users/yoannjaspar/.atom/storage'

### ISSUE THREAD

**Issue by Noxen** [atom/atom#4713]
Uncaught Error: EEXIST, file already exists '/Users/yoannjaspar/.atom/storage'

**Atom Version**: 0.162.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/mkdirp/index.js:74

undefined
```

**Comment by benogle** [comment]
Closing in favor of #4806 as there is more detail on that issue
