### ISSUE TITLE
Fatal error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by underoot** [atom/atom#4715]
I have problem with building atom in Arch Linux (x86_64)

Node: v0.10.34
npm: v1.4.28

Log [here](http://pastebin.com/Khafj4rZ)

P.S. After downgrading my node version to 0.10.33 - problem desapiearred

**Comment by tirithen** [comment]
@jakecleary I use nvm (https://github.com/creationix/nvm) on Arch, installed via cURL as per instructions, install any node version by $ nvm install <version> then do $ nvm use 0.10 in the terminal before running Atom.

**Comment by kevinsawicki** [comment]
Closing this out since it is a bug in node that @abduelhamit linked to which has been fixed and released.
