### ISSUE TITLE
How to build without downloading modules?

### ISSUE THREAD

**Issue by somasis** [atom/atom#4727]
I'm trying to package Atom for a distribution I use called [Exherbo Linux](http://exherbo.org/), which is a source-based distribution akin to Gentoo, and it's package manager uses a sandbox when building packages so that they do not mess with the system outside when not expected. This includes sandboxing the network, so that it can not contact the outside world and is only allowed to use any whitelisted IP addresses, or instead has to fetch dependencies outside of the compilation process.

Atom presents a problem here, because it's build script fetches dependencies while installing, which is not allowed in the sandbox.

To get the point, my question is: is there a supported way to fetch dependencies of the build script, disable any network related operations during compilation, and then build as normal?

**Comment by Somasis** [comment]
...

**Comment by kevinsawicki** [comment]
> To get the point, my question is: is there a supported way to fetch dependencies of the build script, disable any network related operations during compilation, and then build as normal?

Once the modules and bundled packages have been installed a network connection shouldn't be needed to build.

Modules are only downloaded when they are out of date so once they are synced, the network shouldn't be required.

So these steps should work:

* Run `script/bootstrap`
* Disable the network
* Run `script/build`
* Atom is built

Please let me know what issues you see, if any, with these steps, sorry for the delayed response.

**Comment by Somasis** [comment]
This is almost right, but the issue now is that it still compiles with `script/bootstrap`. All resources need to be fetched, and then compiled in a later phase; [this](http://exherbo.org/docs/exheres-for-smarties.html) might help with understanding the environment being worked with.

Atom's `script/bootstrap` still compiles things instead of just downloading what is needed and then compiling with `script/build`

**Comment by kevinsawicki** [comment]
> but the issue now is that it still compiles with script/bootstrap.

Yeah, npm, which is what Atom uses, compiles things as they are installed during bootstrap, I'm not sure there is a way around this currently.

**Comment by Somasis** [comment]
Dang.

**Comment by thedaniel** [comment]
#3717 needs this as well, apparently

**Comment by jedahan** [comment]
So, is there a related npm issue that allows building 'offline'? Would really love pointers into how this can happen...

**Comment by simdol** [comment]
Hello,

I would like to ask if there are any updates in regard to this. I am also for Exherbo, and I am wondering if there is any way to download all of the modules without having to download them one by one through npm.

Thanks!
