### ISSUE TITLE
Uncaught Error: spawn \usr\local\bin\rebar ENOENT

### ISSUE THREAD

**Issue by xiongxin** [atom/atom#4728]
Uncaught Error: spawn \usr\local\bin\rebar ENOENT

**Atom Version**: 0.162.0
**System**: Unknown Windows Version
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At events.js:85

Error: spawn \usr\local\bin\rebar ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by barnie** [comment]
Hi,
I have the same bug today.
I used a arch linux,
atom --version
0.172.0
i change path in erlang-build setting to /usr/bin/rebar : 
➜  erlang  ls /usr/bin/rebar
/usr/bin/rebar
➜  erlang  whereis rebar
rebar: /usr/bin/rebar
And rebar exist in my system, and working quite well, but I cannot use in atom to build project with using erlang build package.

**Comment by barnie** [comment]
I fix it with editing:
.atom/packages/erlang-build/lib/erlang-build.coffee 
and modify this line
``` rebarPath: "/usr/bin/" ```
to my correct path.
I think when you set the path in package editor there is a small bug with Path join and in path was created extra space. Like this :
```/usr/bin/rebar /rebar```
That was happens in my version, at now i re-install atom and change this value in sources ;) and it's workings.

**Comment by maxbrunsfeld** [comment]
@barnie, that's great! You should report your findings as an issue on [the erlang-build repo](https://github.com/spiegela/atom-erlang-build).

**Comment by barnie** [comment]
@maxbrunsfeld Thanks ;)! I will do that ;)!
