### ISSUE TITLE
Fn + Delete on Mac (delete forwards) doesn’t work in Dvorak – Qwerty ⌘

### ISSUE THREAD

**Issue by dangodev** [atom/atom#4740]
`Delete` works fine; `Fn + Delete` yields no behavior whatsoever. This is specifically for Dvorak – Qwerty ⌘; it seems Dvorak works fine. For non-users (i.e., the 99.9%), yes—no other programs have a problem with the `Fn + Delete` thing.

Same for `⌘ + Fn + Delete`; works fine on Dvorak; does nothing on Dvorak – Qwerty ⌘.

**Comment by dangodev** [comment]
![screen shot 2015-01-06 at 6 51 28 pm](https://cloud.githubusercontent.com/assets/1369770/5638478/167c4554-95d5-11e4-97f8-f2db176f5dae.png)

**Comment by dangodev** [comment]
Also, just for reference: 
![screen shot 2015-01-06 at 6 55 08 pm](https://cloud.githubusercontent.com/assets/1369770/5638521/9a17b4a2-95d5-11e4-9873-83d5bc02aa2a.png)

**Comment by dangodev** [comment]
@benogle is there any more information you need for the issue?

**Comment by benogle** [comment]
My assumption is that your dvorak keymap is mapping function delete to something else. `fn-delete` works fine for my on a standard keyboard. This does not seem a fault of atom as it is not seeing `fn-delete` as the `delete` key.

**Comment by dangodev** [comment]
Even if that may be, just wanted to bring it to your attention that it works correctly on 100% of the other programs on my computer (Adobe Suite, other text editors, browsers, etc.). So if it’s not anything in Atom, perhaps every other program I use has accounted for this.

Atom does do keymapping somewhat differently, from what it appears, as I noticed you only recently added support for Dvorak-Qwerty in September.

**Comment by benogle** [comment]
@nathansobo might this be an issue related to or fixable within the dvorak layout? Refs https://github.com/atom/atom-keymap/pull/51

**Comment by nathansobo** [comment]
It might be another quirk of the reported key with Dvorak-Qwerty enabled. Since we have a custom workaround for that, if we can figure out a way to correctly detect `fn-delete` we can add that to the workaround. I don't have time to dive into it right now though.

**Comment by dangodev** [comment]
I should also add that hitting `⌘ + /` in Dvorak-Qwerty (Toggle line comments) produces
```
Key Binding Resolver: cmd-¿
```

**Comment by dangodev** [comment]
Just wanted to bug you guys again to ask if this is a fixable issue or not. I may look into other editors if not. But sincerely, thank you for your time on this and developing such an amazing, amazing platform.

**Comment by nathansobo** [comment]
Thanks for poking this one again. The fix didn't end up being a big deal. Will be out with 0.185.0.

**Comment by dangodev** [comment]
Oh man! Thanks! Really excited for this. Hello, forward delete!
