### ISSUE TITLE
atom  download or update speed slow  ...so  much

### ISSUE THREAD

**Issue by bunnyblue** [atom/atom#4745]
I use OSX, download Atom.zip from https://sx.amazonaws.com/   ,need 2 hours to download. so bad. atom.zip can uploaded somewhere  where can easy download.Oh  my location is China, network so poor.

**Comment by abdul** [comment]
@bunnyblue that's so true. I found about a mirror, and it allows faster downloads: http://cnpmjs.org/mirrors/atom/

**Comment by izuzak** [comment]
I think we can close this in favor of https://github.com/atom/atom/issues/7575.
