### ISSUE TITLE
Quitting one window == all Atom windows being closed.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#4757]
I discovered today when I did `CTRL`+`Q` on my Ubuntu machine that it closed all the windows, all of which were different folders and entirely different spawns of Atom (or what should have been.)

This a pretty severe bug IMO because it severely inhibits working with the keyboard efficiently.

**Comment by ricardograca** [comment]
@envygeeks You're wrong. `ctrl+w` to close the current window and `ctrl+q` to close all windows is also the default behavior on Ubuntu for some other programs, not just Atom. Granted not all programs work this way, so you probably never noticed it before.

You can see this behavior in Nautilus, Firefox and LibreOffice.

I also tested Gedit and Gnome Terminal and these only closed the current window with `ctrl+q`.

**Comment by envygeeks** [comment]
@ricardograca Please learn to read, I never said it wasn't the default for (keyword - notice it) some (end) other applications, I said it shouldn't be which is an opinion that cannot be expressed as right or wrong.  Now onto more interesting things: I don't know if you Ubuntu much, and I don't really care, but I just double checked that the bug was never really properly fixed on Unity and Nautilus and it turns out on all 8 machines that I have with Ubuntu, CTRL+Q does treat individual processes as individual and does not in-fact close all random windows opened that have the tag "nautilus"  I tested this by opening 3 windows per machine and pressing CTRL+Q and watching the other two windows stay open.

That could very well be a bug, as it was listed as bug before, but if it is a bug, it sure has lasted a long time because as long as I can remember it has always been that way, except for a brief period of time when it wasn't but that quickly changed.

Also, let me add: On Ubuntu (Yes I mean Ubuntu not Ubuntu Gnome, not Lubuntu, not Xubuntu, not Edubuntu, I mean Ubuntu with Unity) Gnome Terminal does not even have a CTRL+Q so how exactly did you test it again? That is... unless Ubuntu 14.10 drastically changed things (then I concede because I only use LTS releases.)

**Comment by envygeeks** [comment]
I'm closing this bug because it's just not worth it and we already started patching upstream to behave the way we want it, and there is no reason for me to argue that people should accept behavior I want if they want it to remain the same.
