### ISSUE TITLE
Windows High Contrast Check for Updates

### ISSUE THREAD

**Issue by christiantschoepe** [atom/atom#4760]
The `Help->Check for Update` dialog does not show any text for Windows dark high contrast themes (it actually probably does, just in white). By windows themes, I'm talking about the themes you can get to in windows 8 by, on the desktop, `[right click]->Personalize`. All of the windows 8 built-in high contrast themes, with the exception of "High Contrast White," have this issue. 
![image](https://cloud.githubusercontent.com/assets/4203662/5550707/2f2742e2-8b72-11e4-90f7-47e97ae00560.png)

**Comment by kevinsawicki** [comment]
@zcbenz do you think this is an atom shell issue?

**Comment by zcbenz** [comment]
Yeah, I have created an issue in https://github.com/atom/atom-shell/issues/975.

**Comment by damieng** [comment]
Fixed in Electron. Other high contrast dark issues still exist however, such as menu bar.
