### ISSUE TITLE
Uncaught TypeError: Unable to watch path

### ISSUE THREAD

**Issue by davidcastellani** [atom/atom#4771]
[Enter steps to reproduce below:]
1. Was working on a saved .md file on my desktop, via a remote SMB(not sure which version, but both computers are running Yosemite 10.10.1, so I assume SMB2) share on my macbook pro.
2. On my local computer where Atom was open with the .md, went to Finder and moved the document from the folder it was, in to a parent folder on the remote share. 
3. TypeError popped up immediately in Atom.

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: Unable to watch path

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:66

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/lib/main.js:43:25
  at Object.oncomplete (fs.js:93:15)

```
### Commands

```
     -7:16.0 core:cancel (input.hidden-input)
     -7:15.6 editor:consolidate-selections (input.hidden-input)
     -7:15.6 core:cancel (input.hidden-input)
     -7:15.5 editor:consolidate-selections (input.hidden-input)
     -7:15.5 core:cancel (input.hidden-input)
  2x -7:14.2 core:backspace (input.hidden-input)
  2x -7:08.2 spell-check:correct-misspelling (input.hidden-input)
 12x -6:58.4 core:backspace (input.hidden-input)
     -0:45.0 core:save (input.hidden-input)
     -0:24.2 editor:newline (input.hidden-input)
     -0:22.2 core:move-left (input.hidden-input)
     -0:19.8 core:save (input.hidden-input)
     -0:11.4 editor:newline (input.hidden-input)
     -0:10.7 core:save (input.hidden-input)
  2x -0:02.7 editor:newline (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```
### Config

```
{
  "core": {},
  "editor": {
    "fontFamily": "Inconsolata",
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
travis-ci-status, v0.11.0

# Dev
No dev packages
```

**Comment by jelmerdemaat** [comment]
I have this error when I open a file that I'm not the owner of, issue can in my case be solved by doing `chown <yourusername>` on the file(s). Where "yourusername" is your name that is *not* root.

Atom v0.165, Ubuntu 14.10.

**Comment by Lynges** [comment]
I am having this problem as well. Ubuntu 14.10 Atom 0.165.0 and 0.153.0 both versions.

The above tip from @jelmerdemaat does not work for me.

Atom is unable to open any file. Even files it opened fine just 2 days ago. It even gives this error when saving a new file just created with atom.

Can it be the new year somehow? I had my workstation on suspend from 2014.12.31 till today, with Atom open. But that just seems silly.
