### ISSUE TITLE
Can't paste file path in the open dialog with Cmd+G

### ISSUE THREAD

**Issue by mikebelanger** [atom/atom#4777]
Latest Atom build (.165.0) on OS X Yosamite (v. 10.10.1) won't allow for pasting into the file-path in the open dialog after hitting Cmd+G.  Open dialogues in other programs on OS X appear to allow this, which makes me think Atom is messing up.

Seems like everyone here posts a Console.log message - here's the message.  This stuff only happens when Atom starts, not during the disallowed paste behavior. 

```
2014-12-27 12:59:48.630 PM Atom[870]: App load time: 270ms
2014-12-27 12:59:54.265 PM Atom[870]: assertion failed: 14B25: libxpc.dylib + 97940 [9437C02E-A07B-38C8-91CB-299FAA63083D]: 0x89
```

**Comment by bedge** [comment]
Can't paste into open file dialog with Cmd-v either. Have to rt-click then chose "paste"

**Comment by Pysis868** [comment]
I also have the problem, and if those methods were not able to paste the path into the OS' Open File Dialog, I have also tried Cmd+Shift+v to some success.

**Comment by Pysis868** [comment]
This package may mitigate the problem by offering a workaround: [Atom - Packages - Advanced Open File](https://atom.io/packages/advanced-open-file)
