### ISSUE TITLE
Tabbing in a Sass Map sometimes causes error

### ISSUE THREAD

**Issue by halleycarleton** [atom/atom#4778]
Alright, I've tried but cannot seem to recreate the cause of this issue, but it occurs fairly regularly.

When working in Sass files if I try to tab indent a line within a map I sometimes get an error.

Error:
`Uncaught TypeError: Cannot read property 'shift' of undefined c:\ProgramData\chocolatey\lib-bad\Atom.0.150.0\tools\Atom\resources\app\node_modules\text-buffer\lib\history.js:109`

Sample Code:
```css
$my_map: (
  a_key: a_value
);
``` 

---
### System Specs
Windows 8.1
Node 0.10.26
Atom 0.150.0

**Comment by kevinsawicki** [comment]
Can you upgrade to a later version of Atom? 0.166 is the latest release and it looks like you are on 0.150

**Comment by izuzak** [comment]
@maxbrunsfeld This might also be fixed given the changes in https://github.com/atom/text-buffer/pull/58? :thought_balloon:

**Comment by maxbrunsfeld** [comment]
Yes. It's hard to say why this error happened, but the relevant code has been rewritten since then, so I think we can close this.

**Comment by maxbrunsfeld** [comment]
@halleycarleton We can definitely reopen if you experience any similar errors on the latest version of Atom.
