### ISSUE TITLE
npm 1.4 is required to build Atom. 

### ISSUE THREAD

**Issue by jprice** [atom/atom#4782]
```bash
npm 1.4 is required to build Atom. An error (Error: spawn EACCES) occured when checking the version.
jprice at xxxxx in ~/atom/ ❮git:85456ad...❯ ✱ ⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅⋅ 21:58:15
 ❯❯ npm -v
1.4.28
```

Any ideas? Or am I stupid?

**Comment by izuzak** [comment]
Strange, I don't remember seeing that before. The EACCES error indicates a permission problem. What command did you use exactly to get that output? Which OS are you using?

**Comment by jeremy-evert** [comment]
running ubuntu LTS inside a virtual box.
```
kidd@kiddVBox:~/atom$ script/build
npm 1.4 is required to build Atom. An error (Error: spawn ENOENT) occured when checking the version.
```
so I tried with sudo, because sometimes that helps...
```
kidd@kiddVBox:~/atom$ sudo script/build
npm 1.4 is required to build Atom. An error (Error: spawn ENOENT) occured when checking the version.
kidd@kiddVBox:~/atom$
```
So jprice, or anyone else, any pointers?

**Comment by jeremy-evert** [comment]
So I think that drewmnoel has this handled.
https://github.com/atom/atom/issues/10918
 Atom does not function with the latest freetype2 #10918 

I did not verify that this fixed the problem or recreated it.
It looks like this also points to 
https://github.com/atom/electron/issues/4513
which is for 
 Rendering crashes (white screen) when FontAwesome is used (Archlinux) #4513 

But is listed as open.

My work around for today was to go to atom.io and download .deb.
This is not a satisfying answer, but it gets you back up and running with Atom.
Thanks Drew!
