### ISSUE TITLE
Can't assign a key to "Toggle Soft Wrap"

### ISSUE THREAD

**Issue by DiThi** [atom/atom#4795]
Just as the title says. The menu option View -> Toggle Soft Wrap doesn't appear in the command list and therefore I can't assign a key to it.

I propose to be F10 by default, which is not assigned to anything and it's the same key as other editors I've used such as Kate.

**Comment by kevinsawicki** [comment]
The `editor:toggle-soft-wrap` will appear in the command list when an editor is open (similar to other editor commands).

![screen shot 2015-01-06 at 10 06 53 am](https://cloud.githubusercontent.com/assets/671378/5633412/d4f4be2a-958b-11e4-8dcd-e69db20a596d.png)
