### ISSUE TITLE
alt-f and alt-h default keybindings

### ISSUE THREAD

**Issue by ArashMotamedi** [atom/atom#4808]
By default, alt-f is bound to `editor:move-to-end-of-word` and alt-h to `editor:delete-to-beginning-of-word`. These conflict with activating `File` and `Help` menus in Windows. 

Suggestions:
* Reserve alt-f and alt-h for menu bar access and change editor shortcuts.
* Focus and activate menu bar via a single alt press so user can navigate through the menus using arrow keys (customary behavior in Windows).

**Comment by bekroogle** [comment]
>
>These conflict with activating `File` and `Help` menus in Windows. 

This problem applies to more than just Windows. Same applies to:

__Linux Mint 16__ "petra""
Cinnamon 64-bit DE.
>
>* Reserve alt-f and alt-h for menu bar access and change editor shortcuts.
* Focus and activate menu bar via a single alt press so user can navigate through the menus using arrow keys (customary behavior in Windows).

Using arrow keys to navigate menus didn't work for me either. I absolutely could not activate the `File` or `Help` menus without using a mouse. I'd say this is a very _serious accessibility issue_. (Not to mention a barrier to adoption--until I poked around in the settings, I just thought it was really buggy.)

**Comment by nycdotnet** [comment]
This is a duplicate of #4057

**Comment by 50Wliu** [comment]
Thanks @nycdotnet.
