### ISSUE TITLE
Window icon is pixelated

### ISSUE THREAD

**Issue by GameplayJDK** [atom/atom#4811]
Status: waiting for the next release of atom shell.

The icon of the editor windows seems to be pixelated, at least on windows. (Atom v0.165.0; Windows 8.1)

![issue00](https://cloud.githubusercontent.com/assets/4069263/5584108/51b27cb6-9084-11e4-9409-27b1b07bfd4f.png)

**Comment by jimgraham** [comment]
This seems to be an issue with which icon is referenced in the main window. The `atom.exe` has a 16x16 scaled icon, and that one is used in explorer and for short cuts

![atomicon2](https://cloud.githubusercontent.com/assets/430293/5620877/18c83494-94fe-11e4-93a4-18c21a19562f.png)

However, it does not appear to be the one used in the main window -- the main window seems to use a larger icon that is reduced to 16x16 by the OS. One can see that by using the "Magnify" tool -- the icon looks great when magnified up.

![atomicon](https://cloud.githubusercontent.com/assets/430293/5620876/16ac5564-94fe-11e4-8767-8cc27487eaaa.png)

**Comment by simurai** [comment]
From this [comment](http://stackoverflow.com/questions/3236115/which-icon-sizes-should-my-windows-applications-icon-include#comment11003729_3244679):

> I did some more testing. For display on the desktop, when I set it to 144dpi ("150%") on Windows 7, for the smallest possible icon it used the 24px icon (if it is there, otherwise uprezzed 16px).

So adding a `24px` version might fix it. I'll try that part of #4807.

**Comment by jimgraham** [comment]
I don't think the issue is with the embedded icon. I think that creating the atom window sets the icon to a resource PNG.

https://github.com/atom/atom/blob/master/src/browser/atom-window.coffee#L13

``` coffee
module.exports =
class AtomWindow
  _.extend @prototype, EventEmitter.prototype

  @iconPath: path.resolve(__dirname, '..', '..', 'resources', 'atom.png')
  @includeShellLoadTime: true

  browserWindow: null
  loaded: null
  isSpec: null

  constructor: (settings={}) ->
    {@resourcePath, pathToOpen, initialLine, initialColumn, @isSpec, @exitWhenDone, @safeMode, @devMode} = settings

    # Normalize to make sure drive letter case is consistent on Windows
    @resourcePath = path.normalize(@resourcePath) if @resourcePath

    @browserWindow = new BrowserWindow
      show: false
      title: 'Atom'
      icon: @constructor.iconPath
      'web-preferences':
        'direct-write': false
        'subpixel-font-scaling': false
    global.atomApplication.addWindow(this)


```

This line `@iconPath: path.resolve(__dirname, '..', '..', 'resources', 'atom.png')` ends up pointing at a 1024 x 1024px png 

https://github.com/atom/atom/blob/master/resources/atom.png

The windows `atom.ico` file https://github.com/atom/atom/blob/master/resources/win/atom.ico does not have a white border (atom 0.169.0) for icon sizes < 64x64px, but the de-rezzed title bar does

![atom_ico](https://cloud.githubusercontent.com/assets/430293/5693752/a8f832a8-98fa-11e4-8001-c92c5c9eb83a.png)

Not sure what to do here. If one doesn't set the icon path for Windows, will it default to the embedded (most-likely correct) .ico?

**Comment by jimgraham** [comment]
Further experimentation.

 1. If I go into my `atom` install @ `atom\app-0.169.0\resources\app\src\browser\atom-window.js` and edit the lines 
```javascript
      this.browserWindow = new BrowserWindow({
        show: false,
        title: 'Atom',
        // icon: this.constructor.iconPath,
        'web-preferences': {
          'direct-write': false,
          'subpixel-font-scaling': false
        }
```
then the main window is shown with the default icon, but with the correct icon in the task bar

![noicon](https://cloud.githubusercontent.com/assets/430293/5693807/429fe9ee-98fd-11e4-9921-820fed123c3f.png)

 2. If I replace the 1024x1024 px PNG file in `atom\app-0.169.0\resources\app\resources` with a 16 x 16px image (extracted from the `atom.ico` file), the main window icon is correct, but the task bar icon is up-rezzed from the 16x16 and looks bad

![newatomicon](https://cloud.githubusercontent.com/assets/430293/5693809/6cfb3b58-98fd-11e4-8981-b480f19a0796.png)

**Comment by simurai** [comment]
Hmm.. interesting. What if instead of pointing to a 1024x1024 or 16x16 file, point to the `atom.ico` file which has multiple sizes in it?

```coffee
@iconPath: path.resolve(__dirname, '..', '..', 'resources/win', 'atom.ico')
```

Or was there a specific reason to use the `resources\app\resources\atom.png` icon?

**Comment by Stanzilla** [comment]
@simurai that currently does this: http://i.imgur.com/lqNEZZe.png

**Comment by simurai** [comment]
@Stanzilla Sorry.. I probably made a mistake with the path. My coding skills are kinda limited. :wink:  

Maybe 'resources/win' needs to be split up like:

Maybe 
```less
@iconPath: path.resolve(__dirname, '..', '..', 'resources', 'win', 'atom.ico')
```

**Comment by Stanzilla** [comment]
Okay, so you probably have to change that in line22 which already has the iconPath, not add it, like I did! :(

Anyway, as the .ico is not there in my installation, I downloaded the one from your commit and put it next to the png but it refused to load it. No more error though.

**Comment by Moter8** [comment]
![1](http://i.imgur.com/3vM611S.png)

:+1:

**Comment by paulcbetts** [comment]
@jimgraham is correct - the way to fix this is to correctly embed the ICO file in the EXE (which afaik is already being done), then not set an icon on the BrowserWindow when you create it

**Comment by jimgraham** [comment]
@paulcbetts When I commented out the `iconPath` when creating the `BrowserWindow`, the window was shown with the `no-icon` Windows icon.

```javascript
      this.browserWindow = new BrowserWindow({
        show: false,
        title: 'Atom',
        // icon: this.constructor.iconPath,
        'web-preferences': {
          'direct-write': false,
          'subpixel-font-scaling': false
        }
```

![noicon](https://cloud.githubusercontent.com/assets/430293/5693807/429fe9ee-98fd-11e4-9921-820fed123c3f.png)

I assume the call to `LoadIcon` or `LoadImage` isn't done in `atom-shell` to load the embedded ICO resource because it's assumed that window icons will be set from BrowserWindow. Or am I missing something there?

**Comment by jimgraham** [comment]
@simurai @Stanzilla The [`Image`](https://github.com/atom/atom-shell/blob/master/docs/api/image.md) used in BrowserWindow only supports png and jpg.

**Comment by paulcbetts** [comment]
@jimgraham Hm, I could've sworn this worked in the past, but now it doesn't seem to. You could try using a prescaled PNG image instead (i.e. one that is the correct 32x32 dimensions for 200% DPI screens)

**Comment by Stanzilla** [comment]
@jimgraham yeah, thought so. Thanks :)

**Comment by simurai** [comment]
Ok, no `ico`'s.

After reading the [hi res](https://github.com/atom/atom-shell/blob/master/docs/api/image.md#high-resolution-image) section in the docs. We could try to add multiple sizes with the `@` ratio:

* `resources/icon.png` (16px)
* `resources/icon@1.5x.png` (24px)
* `resources/icon@2x.png` (32px)
* `resources/icon@3x.png` (48px)

and change the file name to:

```coffee
@iconPath: path.resolve(__dirname, '..', '..', 'resources', 'icon.png')
```

Then it should pick the right resolution.

**Comment by simurai** [comment]
__Update__: In the next release of Atom Shell it will use the `ico` file when no `BrowserWindow` icon is defined: https://github.com/atom/atom-shell/issues/863#issuecomment-70197230

I'll make a new PR, most likely after Atom Shell `v0.20.7` is released.

**Comment by jimgraham** [comment]
:+1:

Does unsetting the `BrowserWindow` icon affect Linux? I don't think it affects Mac because the main window doesn't have an icon.

**Comment by zcbenz** [comment]
@jimgraham On Linux I believe all modern desktop environments are using the icon written in `.desktop` now.

**Comment by benogle** [comment]
Looks like atom-shell 0.20.7 is out.

**Comment by mark-hahn** [comment]
Does it have chrome 40?

**Comment by Stanzilla** [comment]
@mark-hahn not on master, there is a chrome40 branch though.

**Comment by benogle** [comment]
Can folks upgrade to 176 and see if this issue is still there?

**Comment by AluisioASG** [comment]
Looks like it's fixed for me.  Using Windows 8.1.

**Comment by jimgraham** [comment]
Looks great to me: 

Windows 7sp1 x64 

![icon-0 176](https://cloud.githubusercontent.com/assets/430293/5909717/07baca98-a581-11e4-8bc6-0b853ba326d2.png)

**Comment by benogle** [comment]
:boom:

**Comment by yesemsanthoshkumar** [comment]
Anyone know why is the desktop shortcut not showing the icon properly
![capture](https://cloud.githubusercontent.com/assets/8852302/9310035/f9294226-452a-11e5-903e-df9dce96aac8.PNG)

Its not the same in the start menu
![capture 1](https://cloud.githubusercontent.com/assets/8852302/9310136/804ce988-452b-11e5-9ec2-3e9ada98111c.png)

**Comment by Stanzilla** [comment]
Looks like it does not use the app.icon in the root but the icon of atom exe in the versioned folder?

**Comment by yesemsanthoshkumar** [comment]
It not the same in all the time...
Sometimes the icon gets displayed correctly..
And sometimes, the icon changes and when clicking pops up  showing
Update.exe doesnot exist. Do you want to remove this shortcut?

**Comment by paulcbetts** [comment]
This is a bug that will be fixed in the next version of Squirrel
