### ISSUE TITLE
Highlighting styling not being applied

### ISSUE THREAD

**Issue by stramel** [atom/atom#4816]
When highlighting text with cursor, the highlighted text does not have any styling being applied to it. The line numbers do however change color. 

**OS:** Ubuntu 14.04
**Atom:** 0.166.0-5276cb7
**UI:** Atom Dark v0.42.0
**Syntax:** Atom Dark v0.23.0

**Comment by izuzak** [comment]
@stramel I'm not sure I understand. Can you provide a GIF which clearly demonstrates the problem and clarify what you expected to see instead?

**Comment by stramel** [comment]
@izuzak Sure, is there an easy way to generate a GIF on Linux?

**Comment by izuzak** [comment]
> Sure, is there an easy way to generate a GIF on Linux?

I have to admit that I don't know -- haven't used Linux in a while. How about a screenshot or two? :smile_cat:

**Comment by stramel** [comment]
Okay, so this one is without anything selected just my cursor at the end of the function: ![Nothing selected](http://s18.postimg.org/4aknpm2xl/Screenshot_from_2015_01_02_15_18_42.png)

This is what happens when I try to highlight the entire function:
![Entire function highlighted](http://s15.postimg.org/6gs51f36z/Screenshot_from_2015_01_02_15_19_31.png)

**Comment by izuzak** [comment]
Here's what I see when I select things:

![screen shot 2015-01-02 at 22 25 15](https://cloud.githubusercontent.com/assets/38924/5599799/496209e0-92ce-11e4-89d6-f085f5237eac.png)

Can you reproduce the problem in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by stramel** [comment]
@izuzak Sorry, I had a derp moment while writing this issue. For some reason I thought I was using Atom Dark Syntax. It appears to be an issue with Atom Monokai Dark. I will raise the issue with them. Thank you for your patience!
