### ISSUE TITLE
who is putting a shadow dom on my checkbox?

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#4819]
My input checkboxes all have a shadow DOM attached.  When I add `checked="checked"` to them nothing happens.  What code is doing this and how do I disable it?

**Comment by mark-hahn** [comment]
I want to bump this.  I found that no add-on packages were at fault by disabling all but the one I'm testing.  I'm using modules "underscore",  "atom-space-pen-views",  and "fs-plus".  I checked the atom-space-pen-views repo and searches for "checkbox", "input", and "shadow" turned up nothing.

So I'm 90% sure it is some core code doing this.

Does anyone have a clue?  Can someone suggest how to chase this problem down?  Unfortunately I can't even look to see what the shadow root contains.  See https://github.com/atom/atom-shell/issues/965.

Not having checkboxes is a pain in the a**.

**Comment by paulcbetts** [comment]
@mark-hahn Not 100% sure, but maybe you can catch this with a DOM breakpoint?

**Comment by mark-hahn** [comment]
By coincidence I was trying that when I got your reply.  Now I'm pretty
sure it is `atom-space-pen-views`.  Specifically it happens when I use
`$$`.  I'll try stepping into the code.

**Comment by nathansobo** [comment]
Taking a look.

**Comment by nathansobo** [comment]
@mark-hahn Can you point me to a specific piece of code that demonstrates the issue? There's nothing I'm aware of that should be interfering with checkboxes. The only place we used the shadow DOM was in the text editor.

**Comment by mark-hahn** [comment]
>  The only place we used the shadow DOM was in the text editor.

That's weird.  There is definitely a shadow root inside all my checkboxes.
And I thought I traced the `space-pen-views` code that put it there but
I'll check again.

I'll try to show an isolated case.

**Comment by nathansobo** [comment]
I'm not seeing a shadow root beneath the checkbox when I load your sample, but I am able to get it to work correctly by using `$.fn.prop`, which I think is the recommended way to check/uncheck a box in jQuery. Try the following:

```coffee
  testClick: ->
    console.log 'BEFORE', @$sampleChkBox.is ':checked'

    if @$sampleChkBox.is ':checked'
      console.log "UNCHECKING"
      @$sampleChkBox.prop 'checked', false
    else
      console.log "CHECKING"
      @$sampleChkBox.prop 'checked', true

    console.log 'AFTER:', @$sampleChkBox.is ':checked'
```

**Comment by mark-hahn** [comment]
Thanks mucho.  Using `prop` worked.

I guess it shouldn't, but it makes me nervous you didn't see the `shadow-root`.

> I am able to get it to work correctly

Did you ever see the problem?  I assumed it was due to the `shadow-root`.

So I guess this is a chrome bug.  Having the checked attribute set properly and not showing the check has to be a chrome html rendering bug.

**Comment by nathansobo** [comment]
I did see the problem, yes.
