### ISSUE TITLE
Atom doesn't start (AwesomeWM, Arch linux)

### ISSUE THREAD

**Issue by tomassvoboda** [atom/atom#4826]
Hello,

please help me, I am not sure if it is a bug or I don't know how to use something.

I use Arch Linux and AwesomeWM, I installed Atom 0.165 from AUR.
When I click on some file in some file manager and select "Open with..." and then Atom, Atom starts fine and opens the selected file, but when I want to start Atom on its own with the Mod4+R run command "atom" in AwesomeWM, I only get spinning wheel cursor for a few seconds and nothing happens, when I write "atom ~/test" for example, where "test" is a text file, Atom starts fine.

Thanks..

**Comment by k4nar** [comment]
What happens if you start atom from a terminal ?

BTW I'm using Atom with Archlinux (via the `atom-editor-bin` AUR package) and I don't have any issue.

**Comment by tomassvoboda** [comment]
I tried `atom-editor` and `atom-editor-bin` packages, both with the same result.

When started from terminal with only the `atom` command, Atom opens fine. Moreover, when I start Atom that way, quit it and then I try to open it with Mod4+R prompt it opens correctly, but when I try it first through the Mod4+R prompt, nothing happens, except the momentary spinning wheel.

**Comment by muchweb** [comment]
I can confirm this. Atom will open fine from terminal emulator, but not using <kbd>Mod4</kbd>+<kbd>R</kbd> launcher.

I am using Awesome WM `v3.5.5` and Atom `v0.165.0` on GNU Operating System.

**Comment by barwinco** [comment]
Works fine for me (starts from Mod4+R). Gentoo / awesome v3.5.5 / atom-0.167.0-f77f481

**Comment by tomassvoboda** [comment]
It has been working now for a few versions. I am now on 0.175.0. (Running the ```atom-editor-bin``` from AUR.)

**Comment by muchweb** [comment]
+1, `v0.175.0` does work.
