### ISSUE TITLE
Uncaught Error: spawn jekyll ENOENT

### ISSUE THREAD

**Issue by imageaid** [atom/atom#4828]
[Enter steps to reproduce below:]

1. Start Atom
2. Install/Use Jekyll package (0.4.2).
3. Attempt to start the Jekyll server from within Atom (alt-shift-T or use the command palette). 

If I start Jekyll (jekyll serve) from a Terminal, it works fine. 

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn jekyll ENOENT

```
At events.js:85

Error: spawn jekyll ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

### Commands

```
     -9:13.1 command-palette:toggle (input.hidden-input)
  3x -9:11.0 core:move-up (input.hidden-input)
     -9:03.5 core:confirm (input.hidden-input)
     -9:03.4 jekyll:toggle-server (input.hidden-input)
     -6:40.3 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.remove)
     -0:04.3 command-palette:toggle (input.hidden-input)
  7x -0:02.3 core:move-down (input.hidden-input)
     -0:00.0 core:confirm (input.hidden-input)
     -0:00.0 jekyll:toggle-server (input.hidden-input)
```

### Config

```
{
  "core": {
    "disabledPackages": [
      "language-java",
      "language-go",
      "language-php",
      "language-perl",
      "language-toml"
    ],
    "useReactEditor": true,
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "fontSize": 14,
    "fontFamily": "Monaco",
    "showIndentGuide": true,
    "softWrap": true,
    "preferredLineLength": 300
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-angularjs, v0.1.2
color-picker, v1.2.6
ember-cli-helper, v0.4.0
ember-snippets, v1.0.0
emmet, v2.3.0
html2haml, v0.3.0
jekyll, v0.4.2
language-ember-script, v0.1.0
language-haml, v0.14.0
language-rspec, v0.2.1
project-manager, v1.14.1
rspec-snippets, v0.4.0
ruby-define-method, v0.1.1
save-session, v0.11.2
seti-syntax, v0.2.1
seti-ui, v0.5.1
travis-ci-status, v0.11.1

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
Can you report the path to `jekyll` on your machine, and the output of `process.env.PATH` from the Atom dev console?

If you want Atom to inherit environment variables from your login shell, you need to start it using the `atom` command line launcher. To set environment variables for apps started from Spotlight of Finder, I believe you need to [use the `/etc/launchd.conf` file](http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x/588442#588442).

**Comment by imageaid** [comment]
Thank you, Max. 

When I do start Atom from my project's directory at the command-line with `atom .`, it works very well. No issues at all. 

Here are my paths: 

jekyll - `/usr/local/var/rbenv/shims/jekyll` 
process.env.PATH - "/usr/local/heroku/bin:/usr/local/var/rbenv/shims:/usr/local/heroku/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/share/npm/bin:/usr/local/lib/node:/usr/local/lib/node_modules:/Applications/Postgres93.app/Contents/MacOS/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin"

FWIW, I only reported this since I was 'encouraged' to by Atom itself ... starting from the command line is great and easy and what I typically do. When I encountered this issue it was from opening a project with the Project Manager package, which I rarely do anyway.

**Comment by kevinsawicki** [comment]
As @maxbrunsfeld mentioned, this should be reported against the https://github.com/arcath/jekyll-atom package
