### ISSUE TITLE
Command Palette not working at all

### ISSUE THREAD

**Issue by halleycarleton** [atom/atom#4832]
I've seen some issues on here about the command palette key binding not working, but I'm having an issue where the command palette won't show up even if I select it from the tool bar. So this is not an issue with the key binding.

Windows 8.1

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* Do you have the [Emmet package](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by halleycarleton** [comment]
Atom 0.150.0
Yes I have emmet installed
I can't get atom to run from the command line, so I can't try `--safe`

**Comment by lee-dohm** [comment]
Version 0.150.0 is somewhat old, we're up to v0.165.0 of Atom now. You might want to consider upgrading. There is also this similar topic from Discuss:

https://discuss.atom.io/t/error-when-trying-to-activate-the-command-palette/13909

And it also is from someone that is on Windows and was using an older version. You might be able to use the same solution if Atom is not working 100% for you.

Also, not being able to reproduce in safe mode generally means that there is a third-party package at fault.

**Comment by halleycarleton** [comment]
How do you update the version? The only documentation I can find says to use the "Atom > Check for update" menu, which I don't see anywhere.

**Comment by lee-dohm** [comment]
You're probably on an old enough version that you need to follow the instructions in this blog post:

http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html

After you get that done, you should get the automatic update notifications and such.

**Comment by halleycarleton** [comment]
Thanks!

I'll try that and report back.

**Comment by mark-hahn** [comment]
>How do you upgrade the version? 

On windows, the best is to start fresh with the giant green download button at http://atom.io.  This version will auto-update from now on.

 If you are on chocolatey then you need to blow it away first.  Follow the instructions in the blog linked from that same page.  If you do not follow all the instructions there you will have trouble.

**Comment by halleycarleton** [comment]
Reinstalling with the Windows installer seems to have fixed the issue. Thanks!
