### ISSUE TITLE
Show zoom level (in status bar?)

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#4835]
I wasn't sure the best place to put this (maybe [status-bar?](https://github.com/atom/status-bar)), but it would be nice to be able to see the zoom level somewhere in the UI. Since it's possible to zoom using `Cmd + -` / `Cmd + =`, it's possible to not realize the editor is zoomed because there's no way of telling.

It might also be cool to have some kind of visual feedback when you do zoom - maybe some kind of modal alert that pops up saying "Zoom: 125%" (for example) and fades away.

**Comment by benogle** [comment]
There is no such thing as zoom: 100%. All 'zooming' does is increase or decrease the font-size. One could create a package to display the font-size in the status bar, though. 

I'm going to close this out as it is unlikely something we will add to core.

**Comment by mnquintana** [comment]
Does it increase / decrease the font size by a pixel amount, or by a multiplier (e.g. `1.5em` or something)? If it is by a multiplier, there can still be a zoom factor: `1em` (the theme's font-size) is 100%. `1.5em` is 150%, and so on.

Even if it is by a pixel amount, a zoom factor could still be calculated.

But if you think this would be better off in a non-core package that works too.

**Comment by benogle** [comment]
It changes by +/- 1px
