### ISSUE TITLE
IME doesn't work on linux version

### ISSUE THREAD

**Issue by imeoer** [atom/atom#4840]
environment: ubuntu 14.04 x64, fictx IME, atom 0.166.0-25b44ce, self build version
behavior: input any char doesn't popup IME
thanks for reply :)

**Comment by izuzak** [comment]
This sounds similar to https://github.com/atom/atom/issues/2266. Can you check that issue and see if you're observing the same behavior?

**Comment by imeoer** [comment]
@izuzak thanks, have little different with #2266 : Switch to some file opened in Atom, type something → **not works**
I will focus the issue. :)
