### ISSUE TITLE
Install atom on specific location in windows

### ISSUE THREAD

**Issue by patelkunal** [atom/atom#4859]
I am not sure if solution to this is already exists or not.

Lets say, I want to install atom on custom location like C:/apps/atom - Current installer doesn't provide something like this.

I know, we can do this using zip version but in this case we will not able to add atom editor ('Open with atom') in windows context menu.

Please advice if this feature is already added.

**Comment by kevinsawicki** [comment]
There is not currently supported and probably won't be since it isn't supported by the installer library being used,  https://github.com/Squirrel/Squirrel.Windows/
