### ISSUE TITLE
HELP/QUESTION: "Frame" to preview SPA

### ISSUE THREAD

**Issue by thebigredgeek** [atom/atom#4860]
Is it possible to embed a "frame" next to the text editor area that acts as a preview for CSS/HTML being written?  I don't really know where to even look to get started.  Thanks

**Comment by lee-dohm** [comment]
We have a *long* topic on Discuss, the official Atom forum, for specifically this:

https://discuss.atom.io/t/browser-live-preview/612

There have been a few packages created that offer this, you can find links to them there.
