### ISSUE TITLE
Windows Installer do not uninstall old version of Atom

### ISSUE THREAD

**Issue by KKyang** [atom/atom#4863]
This is the first time I use Windows Installer to upgrade from 1.6.5 to 1.6.6.

Although it upgrade successfully, but the old one still remains that I have to manually remove the folder.

**Comment by 50Wliu** [comment]
It keeps a backup copy, just in case.  Chrome also does this.

**Comment by KKyang** [comment]
Can we have an option to delete? Since the backup of Atom isn't very small.

**Comment by kevinsawicki** [comment]
@KKyang this is managed by the installer library that Atom uses, https://github.com/Squirrel/Squirrel.Windows/

Would you mind opening an issue there requesting support for this feature? Thanks.
