### ISSUE TITLE
Uncaught Error: spawn /Users/tvoet/.rbenv/shims/rubocop ENOENT

### ISSUE THREAD

**Issue by timvoet** [atom/atom#4864]
Uncaught Error: spawn /Users/tvoet/.rbenv/shims/rubocop ENOENT

**Atom Version**: 0.156.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At events.js:85

Error: spawn /Users/tvoet/.rbenv/shims/rubocop ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by benogle** [comment]
Please install `rubocop` and make sure it is on your path

**Comment by timvoet** [comment]
@benogle are you kidding me?  I've been using Rubocop on this same computer for months now, Atom crashed when i opened it up, and asked if i wanted to submit the error.  Nothing has changed.  It was perhaps a fluke, but telling ym to install rubocop is kind of ridiculous without finding out more details.  Very helpful.

**Comment by benogle** [comment]
Sorry about that. So far every time we have had this error reported (and we get it a lot), it is because some package is trying to spawn a binary that does not exist, or is not on the path. Please make sure the plugin spawning rubocop is able to.

**Comment by timvoet** [comment]
I think i have diagnosed the error ( or at least the cause ).  If you happen to close atom with a blank file, when restarting atom, it re-opens said file and rubocop then fails to validate the file.  But then again, this appears to be a best guess type of situation

**Comment by timvoet** [comment]
@benogle I've updated the issue with the steps i just sent you.

**Comment by benogle** [comment]
Can you open an issue on the related package?

**Comment by timvoet** [comment]
yes.

**Comment by benogle** [comment]
Thanks
