### ISSUE TITLE
New dependancies

### ISSUE THREAD

**Issue by HomeyD5** [atom/atom#4867]
Seems that a new release or patch for Atom (my system is showing "0.165.0" now) appeared either yesterday or this morning (Jan 5 or 6)?  My package management system notified me of the update this morning.  After installing the update, I could not get Atom to load on my Xubuntu 14.10 64-bit system, getting a series of dependency errors:

/opt/atom/atom: error while loading shared libraries: blahblahblah: cannot open shared object file: No such file or directory

Executing the following command apparently loaded the 32-bit versions of these libraries, which got me working again:

apt-get install libgconf2-4:i386 libnss3:i386 libxtst6:i386 libcap2:i386

**Comment by lee-dohm** [comment]
The version of Atom that was released yesterday was v0.166.0. And Atom doesn't release a 32-bit version for Linux. From the README:

> Debian Linux (Ubuntu)
>
> Currently only a 64-bit version is available.

I suspect you're using webupd8? Which according to #4865 seems to be having some trouble today?

**Comment by HomeyD5** [comment]
Thanks for the prompt reply!  Yes, webup8...  guess I'll wait till they sort their act and update again.
