### ISSUE TITLE
Uncaught Error: ENOENT, unlink '/Users/chris.simeone/webdev-lampo/stewardshipcentral/vendor/assets/javascripts/preview-temp-file-1420586493653.js'

### ISSUE THREAD

**Issue by simspace-dr** [atom/atom#4874]
[Enter steps to reproduce below:]

1. I'm just viewing a .js file and I get this error.

**Atom Version**: 0.165.0
**System**: Mac OS X 10.8.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, unlink '/Users/chris.simeone/webdev-lampo/stewardshipcentral/vendor/assets/javascripts/preview-temp-file-1420586493653.js'

```
At fs.js:75

Error: ENOENT, unlink '/Users/chris.simeone/webdev-lampo/stewardshipcentral/vendor/assets/javascripts/preview-temp-file-1420586493653.js'
  at Error (native)

```

### Commands

```
     -1:06.9 project-find:show (input.hidden-input)
     -0:59.5 core:confirm (input.hidden-input)
  4x -0:00.0 core:close (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "suranyami-light-ui",
      "suranyami-light-syntax"
    ],
    "disabledPackages": [
      "emmet"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "preferredLineLength": 255,
    "scrollPastEnd": true,
    "lineHeight": 1.66,
    "fontFamily": "Courier New",
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.1.3
atom-beautify, v0.21.2
atom-lint, v0.20.1
change-case, v0.4.0
color, v0.5.0
git-log, v0.2.0
git-plus, v4.3.0
linter, v0.9.1
linter-ruby, v0.1.4
minimap, v3.5.0
open-in-browser, v0.3.0
open-last-project, v0.1.1
preview, v0.13.4
project-manager, v1.14.1
rest-client, v0.2.0
rsense, v0.6.0
ruby-string-interpolation, v0.1.8
soft-wrap-indicator, v0.3.0
suranyami-light-syntax, v0.8.0
suranyami-light-ui, v0.5.0
tabclick, v0.1.0
toggle-tabs, v0.1.8
wakatime, v2.2.0
wordpress-api, v1.0.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Were you viewing the file that is in the title? Does something in the background rebuild this file or delete it or something like that?

I think we really just need a better error message for this.

**Comment by simspace-dr** [comment]
I was not viewing the file in the title. I was attempting to open a .js file. I'm not even sure what that file is.

I agree, a clearer error message would be very helpful. But I love Atom. After I started using it, I never looked back!

Thanks,
Chris

On Jan 6, 2015, at 6:27 PM, Ben Ogle <notifications@github.com<mailto:notifications@github.com>> wrote:


Were you viewing the file that is in the title? Does something in the background rebuild this file or delete it or something like that?

I think we really just need a better error message for this.

**Comment by benogle** [comment]
Similar to https://github.com/atom/atom/issues/4874

**Comment by shingonoide** [comment]
:+1: I'm using v0.175 and this bug is there too.
Just for see or navigate to a .js file after a little freeze time the error message pop-up.

**Comment by benogle** [comment]
@shingonoide So you're saying you just open the file, and it throws this error? Can you paste in the stack trace? What system, are you on? What are the attributes of the file? Can you run `ls -la your-broken-file.js` and paste the results in here?

**Comment by shingonoide** [comment]
@benogle sorry for delay...
I can't see the error anymore, I'm using **atom/0.196.0-cf9b00c** and **preview/0.13.8**.
I guess the error has been fixed, thanks.

**Comment by benogle** [comment]
Ok, let me know if you see it again.
