### ISSUE TITLE
Package manager buttons (uninstall/learn more/settings) have no vertical margin  

### ISSUE THREAD

**Issue by YemSalat** [atom/atom#4876]
![screen-shot-2015-01-07-at-11 08 53-am](https://cloud.githubusercontent.com/assets/2361381/5638673/8b96c268-965e-11e4-8a83-6bb4d15afb13.jpg)

**Comment by thedaniel** [comment]
In master of settings-view, these boxes are only used to show package updates, and they look fine there:

![screen shot 2015-01-06 at 4 56 31 pm](https://cloud.githubusercontent.com/assets/1476/5639067/1bbf0df4-95c5-11e4-807b-28063ad28f36.png)

![screen shot 2015-01-06 at 4 56 36 pm](https://cloud.githubusercontent.com/assets/1476/5639069/20a36270-95c5-11e4-972f-fc3c29c846a3.png)

**Comment by YemSalat** [comment]
Does it mean this was already fixed on master and I am just using an outdated version?

**Comment by kevinsawicki** [comment]
> Does it mean this was already fixed on master and I am just using an outdated version?

It has been fixed on master but not in a released version of Atom yet.

**Comment by benogle** [comment]
It's on master, but not released yet. It should be released within one or two atom releases. We're running it on our end to make sure there are no issues, as there are a lot of changes.

**Comment by thedaniel** [comment]
This has now shipped. Feel free to reopen if you still see this on 0.168.0+

**Comment by YemSalat** [comment]
Confirm this is fixed in the new release. Looks and works great. Thank you!
