### ISSUE TITLE
When rename file, paste a string with LF cause bug

### ISSUE THREAD

**Issue by lijunle** [atom/atom#4878]
![untitled](https://cloud.githubusercontent.com/assets/1296500/5640185/3bbc1552-961a-11e4-9a45-b2145acc2a97.png)

**Comment by lee-dohm** [comment]
I think this is a duplicate of #4400 in that they almost certainly have the same root cause. Please let me know if I've misunderstood.

**Comment by lijunle** [comment]
I have no idea that is caused by the same root. Will follow up after that is fixed.
