### ISSUE TITLE
Add input checking on Settings, Font Size

### ISSUE THREAD

**Issue by nlsn** [atom/atom#4880]
My young son typed in 1000000 for the Font Size in settings and Atom froze. I had to edit the config back to a sane number with a different editor.

Might I suggest limiting the setting to a range, maybe 4 to 1000?

**Comment by mnquintana** [comment]
This is a great idea! The [JSON Schema spec already supports this](http://json-schema.org/latest/json-schema-validation.html#anchor17), and we should too.
