### ISSUE TITLE
Indent guides are colored strangely

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#4882]
Curious if other people are seeing this.

I'm on Atom 0.166 using the Atom Dark syntax theme and I see these dots between the indent guide lines.  This is on a 13' MBP retina running mavericks.

![screen shot 2015-01-06 at 8 32 50 pm](https://cloud.githubusercontent.com/assets/671378/5640979/4565bf72-95e3-11e4-9e8d-dda9fb9cdb1d.png)

**Comment by izuzak** [comment]
Here's what I see on Atom 0.167.0-06cbbe4, OSX, MBA 13', Atom Dark theme:

![screen shot 2015-01-07 at 17 42 21](https://cloud.githubusercontent.com/assets/38924/5649255/c36d4c94-9694-11e4-8a05-251a738cd0ea.png)

**Comment by izuzak** [comment]
Yep, closing in favor of https://github.com/atom/atom/issues/4279. Thanks @50Wliu :smile:
