### ISSUE TITLE
File replacement does not work against directories

### ISSUE THREAD

**Issue by elifoster** [atom/atom#4885]
When saving a new file, if you decide to save it as the same name of a directory (no extension), it will ask if you would like to replace it. If you choose yes, it will error saying that that file is already a directory 

I am running Atom 0.165.0 for OSX.

There is no log in the debug console to provide.

There are basically three solutions to this:
1. Have it error after the "replace" button is clicked but before the dialog box is closed
2. Have it replace the directory
3. Have it handle directories and files separately (I'm not sure about other operating systems, but I'm pretty sure on OSX it considers them <name>.folder)

**Comment by elifoster** [comment]
This is still kind of an issue. The error it outputs is different now: `Unable to save file: EISDIR: illegal operation on a directory, open 'path/to/folder/being/replaced'`

Tested on Atom 1.17.2.

**Comment by 50Wliu** [comment]
I am unable to reproduce this on Windows. @elifoster can you describe the exact steps you're taking to save the file?

**Comment by elifoster** [comment]
1. Create new folder, name it something
2. Create new blank untitled file
3. Save as whatever you named the folder
4. Select "Replace"

**Comment by 50Wliu** [comment]
> Create new folder, name it something

How are you creating this folder?  Outside of Atom?  Using the `tree-view:add-folder` command?  Or some other way?

> Save as whatever you named the folder

Similarly, how are you saving?  `cmd/ctrl-s`?

**Comment by elifoster** [comment]
I'm creating a folder by right clicking the project section(?) and selecting new folder.

I'm saving using cmd s, yes.

**Comment by 50Wliu** [comment]
Thanks for the info.  I'm still unable to reproduce this on Windows.  Here are the steps I followed, please tell me if I did something wrong.
1. `tree-view:add-folder`, enter `test` as the folder name
2. `application:new-file`
3. `core:save`
4. Navigate to the directory that has the `test` folder in it
5. Type `test` as the file name
6. Click save

What happens here is that Windows' file dialog intelligently realizes that the file is the same name as the directory and automatically cd's into the folder for you.  Meaning that once I hit save, I am now inside the `test` directory and have to choose a different filename.

Perhaps things are different on macOS and/or Linux: /cc @ungb for reproduction on those platforms.

**Comment by rsese** [comment]
I tried on macOS 10.12.5 following @50Wliu's steps and I can reproduce there with Atom 1.17.2- at step 6 I get:

![warn](https://github-slack.s3.amazonaws.com/monosnap/Monosnap_2017-06-07_15-47-07.png)

Then after I click Replace, I get:

`Unable to save file: EISDIR: illegal operation on a directory, open '/path/to/folder/being/replaced'`

And in console:

```
fs.js:731 Uncaught (in promise) Error: EISDIR: illegal operation on a directory, read(…)
fs.readSync @ fs.js:731
tryReadSync @ fs.js:486
fs.readFileSync @ fs.js:534
fs.readFileSync @ ELECTRON_ASAR.js:501
module.exports.File.readSync @ <embedded>:104385
module.exports.File.getDigestSync @ <embedded>:104286
module.exports.TextBuffer.serialize @ <embedded>:27562
(anonymous function) @ <embedded>:21890
module.exports.Project.serialize @ <embedded>:21887
module.exports.AtomEnvironment.serialize @ <embedded>:1117
(anonymous function) @ <embedded>:1433
module.exports.AtomEnvironment.saveState @ <embedded>:1429
(anonymous function) @ <embedded>:620
```

**Comment by duochen13** [comment]
The EISDIR error is related to 'try to open a file but the path give is a directory', consider the following case, where test is a directory

```
const fs = require('fs');
const path = './test'
const sync_files = fs.readFileSync(path);
```
the error message is very similar to what @rsese got, 'fs' built-in package cannot read a directory, atom exports fs somewhere in source code

```
fs.js:119
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:514:3)
    at tryReadSync (fs.js:337:20)
    at Object.readFileSync (fs.js:374:19)
    at Object.<anonymous> (/.../play.js:8:23)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
```

consider another method fs.readFile(), the difference between fs.readFile() and fs.readFileSync is that we can add callback function in fs.readFile()
```
const files = fs.readFile(path, (err, data) => {
    if (err) throw err;
    console.log(data);
})
```
it will throw following EISDIR error:
```
    if (err) throw err;
             ^
Error: EISDIR: illegal operation on a directory, read
```

**Comment by sadick254** [comment]
I cannot reproduce the bug in the latest atom version 1.50.
When trying to save a new file with the same name as an existing directory I get this  message.

![Screenshot 2020-08-26 at 13 19 28](https://user-images.githubusercontent.com/5238135/91292175-d0135b80-e79e-11ea-8e9e-aeb7b60b356d.png)

Am happy to reopen this issue if anyone is able to reproduce the bug.
```
apm  2.5.0 
npm  6.14.5
node 10.20.1 x64
atom 1.50.0
python 2.7.16
git 2.24.3 
```
