### ISSUE TITLE
Wrong git modified color when using git subtree

### ISSUE THREAD

**Issue by hugomn** [atom/atom#4889]
Hi!

I have a git subtree under my directory `src/Rockbee/CoreBundle` and everything is up-to-date. Atom shows all other files as if they are modified (in yellow). Probably the file tree coloring is not dealing with subtrees correctly. Has anyone had the same problem? Maybe someone can give me some ideas on how to fix it on atom module. Thanks in advance.

![screenshot 2015-01-07 10 10 09](https://cloud.githubusercontent.com/assets/497957/5645348/90022616-9655-11e4-86aa-940c9011ca96.png)

**Comment by lee-dohm** [comment]
Is it a git [submodule](http://git-scm.com/book/en/v2/Git-Tools-Submodules)? Atom has support for submodules built-in, but the icon looks different:

![submodule](https://cloud.githubusercontent.com/assets/1038121/5658124/d77de0a6-96b0-11e4-9ba7-92331c397d9a.png)

**Comment by hugomn** [comment]
Hi @lee-dohm! Subtrees are different from submodules. Submodules don't mantain a copy of the inner versioned project inside the main one, subtree does. (http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/). It's being really bad using atom with this project, because it's showing all my files as modified ones (in yellow), =/

Thanks!

**Comment by lee-dohm** [comment]
Thanks, I didn't know subtree was an actual thing. As far as the subtree thing goes, I don't think Atom supports them yet. I'll mark this as an enhancement.

As far as things showing as modified when maybe they shouldn't be, check out this topic on Discuss, the official Atom message board:

https://discuss.atom.io/t/atom-on-windows-incorrectly-showing-files-as-modified-git/12805

There are a couple reasons why this could happen, specifically sharing files with Windows systems or file mode changes.

**Comment by hugomn** [comment]
Perfect, thanks @lee-dohm. I'll check how can I help.

**Comment by hugomn** [comment]
Hey, I did some tests and realized it was nothing related to Atom. After cloning the repo again, Atom is now considering correctly my subtree, without marking other files as modified. I dunno exactly what caused the issue, but if someone face the same issue the solution is recreate your workspace. Sorry about that!

**Comment by lee-dohm** [comment]
No problem! I'm glad it got fixed :grinning:

**Comment by chfast** [comment]
I have the same problem.
