### ISSUE TITLE
Atom crashed and can no longer open (Windows 8.1)

### ISSUE THREAD

**Issue by mesosteros** [atom/atom#4895]
Atom suddenly crashed while I was in setting some options in the trailing spaces package.
Then, I couldn't get it to open again. On the Task Manager several instances of Atom showed but none were open. I had to reinstall Atom and when I did I got this error:
![atom error](https://cloud.githubusercontent.com/assets/1943233/5649201/f5833d5a-968b-11e4-8bd4-d20434f5f20c.jpg)

Afterwards I did a full uninstall by deleting whatever remained in the Atom folder and running the installer once more, and Atom began working again.

**Comment by kevinsawicki** [comment]
Thanks for reporting this, it will be fixed in the next Atom release, 0.167
