### ISSUE TITLE
Atom updates

### ISSUE THREAD

**Issue by iamdriz** [atom/atom#4896]
How does Atom handle its updates? As apparently it uses the Squirrel framework, but according to the atom-shell docs, Squirrel isn't implemented in atom-shell for Windows yet.

**Comment by kevinsawicki** [comment]
It uses Squirrel on Windows and Mac.

It shells out to Squirrel on Windows, API support in Atom Shell is planned.

**Comment by iamdriz** [comment]
@kevinsawicki if API support is planned (i.e. not implemented yet) and Atom uses atom-shell, then how does it do it?

**Comment by kevinsawicki** [comment]
> if API support is planned (i.e. not implemented yet) and Atom uses atom-shell, then how does it do it?

Squirrel launches Atom with certain arguments telling it that it was installed, updated, uninstalled and Atom installs shortcuts, context menus, etc. when these happen.

https://github.com/atom/atom/blob/184aecb4a4348bd4e58c0d3c35948583665cbfea/src/browser/squirrel-update.coffee#L207

https://github.com/atom/atom/blob/184aecb4a4348bd4e58c0d3c35948583665cbfea/src/browser/auto-updater-win32.coffee#L36

> Also why does Atom require to be installed via the installer instead of the ZIP for the updates to work?

Squirrel assumes certain locations and installs updates to the same location that the installer installs the app too.

I'd assume perhaps we could somehow offer a .zip that auto updates, but I don't think anyone has ever looked into it.

The goal was to provide easy installation and automatic updates at the same time.

**Comment by kevinsawicki** [comment]
Going to close this out since it seemed like a question that has now been answered.

**Comment by iamdriz** [comment]
Still confused about this :P

Are you saying that the Atom Editor has to implement Squirrel itself rather than use the one within the atom-shell framework as it's not implemented on Windows yet?
