### ISSUE TITLE
Common uncaught errors

### ISSUE THREAD

**Issue by benogle** [atom/atom#4900]
I went through the uncaught errors looking for patterns. I know there are some we see over and over. It would be nice to dig into these.

These are ordered by apparent frequency.

### Permission / file doesnt exist / file in use issues

These just need better error messages. e.g.

* https://github.com/atom/atom/issues/4797
* https://github.com/atom/atom/issues/4850

Should be an easy fix, difficulty is catching all the cases.

#### Error from pathwatcher

Seems like a path is being watched, then something happens to that file, and pathwatcher freaks out

https://github.com/atom/atom/labels/error-from-pathwatcher

#### No trace; At fs.js:75

* EBUSY open: https://github.com/atom/atom/issues/4735
* EBUSY unlink: https://github.com/atom/atom/issues/4805
* ENOENT unlink: https://github.com/atom/atom/issues/4874

### Unable to watch path

* https://github.com/atom/node-pathwatcher/issues/39 (windows)
* https://github.com/atom/atom/issues?q=is%3Aissue+is%3Aopen+unable+to+watch+path

Seems almost entirely linux based. Not sure how to fix.

### Spawn /atom/dir/atom ENOENT

Again, mostly linux. But a handful in OSX too. We need to figure out how to reproduce.

* linux: https://github.com/atom/atom/issues/4505
* osx: (these might be different?) https://github.com/atom/atom/issues/4538, https://github.com/atom/atom/issues/4754, https://github.com/atom/atom/issues/4538

### EEXIST .atom/storage exists

Again, we need to reproduce

https://github.com/atom/atom/issues?q=is%3Aissue+EEXIST+storage+is%3Aopen

**Comment by therufs** [comment]
Just created another fs.js no trace bug, #5272.

**Comment by izuzak** [comment]
There's still a large number of these issues being created, which is a suboptimal user experience and it's also hard to triage these issues because it's not really clear why some are happening and some are impossible to reproduce. For example, there's more than 30 ENOENT issues open right now: 

https://github.com/atom/atom/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+enoent

**Comment by benogle** [comment]
Closing in favor of #7740
