### ISSUE TITLE
Problem Installing Atom Packages on MS Windows with Github Installed Git

### ISSUE THREAD

**Issue by GGillan** [atom/atom#4902]
I am attempting to install an Atom package and the install keeps failing with the same error (see below). After investigating, it seems that there is a mismatch between the way that the GitHub installer installs Git on Windows (Windows 7 in this case) and the way that Atom expects to find Git.

GitHub is installing Git as a "ClickOnce Application Reference". It does not get it's own place on the system path, and the deeply nested directory where it is located has a hellishly long name that is not conducive to being added to the path. See below for a partial image of that directory. Notice the path information displayed at the top is only partial!

All of the advice that I found for solving issues of this sort involve adding the Git directory to the system's path, but that is not practical with the way GitHub currently installs itself. Is there another solution?

Thanks for your help.

George
______

Installing “Sublime-Style-Column-Selection@1.1.3” failed.Hide output…

npm http GET https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/underscore-plus
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\George\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\George\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\George\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\George\\.atom\\.apmrc" "install" "C:\\Users\\George\\AppData\\Local\\Temp\\d-11507-7104-mfvqtr\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\George\AppData\Local\Temp\apm-install-dir-11507-7104-1s0c3gy
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/mixto
npm

![gith tion_317444273a93ac29_0002 0006_159c473f7cb71f94_2015-01-07_15-47-03](https://cloud.githubusercontent.com/assets/9140259/5654842/85a33e92-9684-11e4-8208-567226fdb1b6.jpg)

**Comment by Ingramz** [comment]
The most elegant solution to this so far (that I know of) is to add `%localappdata%\GitHub\PortableGit_<somegibberish>\cmd` to system PATH.

**Comment by GGillan** [comment]
Thank you, Ingramz. I was just coming back here to report my workaround. I found that PortableGit_<somegibberish> and decided to copy the entire contents to C:\Git to make the resulting paths shorter. I then added to the system path:

C:\Git\;C:\Git\bin\;C:\Git\libexec\git-core\

I'm not sure if Git and \bin and \git-core are all necessary, but it does work now.

This seems to really be a problem with the way GitHub is doing its installation rather than Atom directly. But it would make sense if the Atom folks inside GitHub see this that they would call the installation issue to the attention of the team that oversees GitHub installation for MS Windows.

**Comment by paulcbetts** [comment]
@GGillan You can just run apm from the "Git Shell" shortcut, no need for all of this file copying business

**Comment by GGillan** [comment]
@paulcbetts Thanks for the tip. The errors I ran into are when running Atom and trying to install packages from the Settings. If I understand right, running apm from the Git shell means I can manually download and install packages? I would still have the errors trying to install packages from inside Atom's Settings tab?

**Comment by paulcbetts** [comment]
@GGillan Yeah, that is a negative side-effect, though afaik many packages won't require Git to be installed. You can also install MSysGit and it won't affect GitHub for Windows's Git too

**Comment by GGillan** [comment]
@paulcbetts I had an email exchange with GitHub (they don't have an issues section available for their installer because it's not a public repository so I reported and gave my feedback through Support) where that was mentioned. Ironically, I had that installed before removing it in favor of GitHub's version! :-)  I've suggested they might add themselves to the path so that other packages could find them and use their Git. It just seems like they would want their package to be the choice for people to rely on, but they might have reasons why not to want that.

Thanks again!

**Comment by paulcbetts** [comment]
@GGillan Yep, I'm the one who set that up in GitHub for Windows long ago :)  We were really adamant that the app not mess with people's machines, even if it has a few disadvantages like this

**Comment by GGillan** [comment]
@paulcbetts I understand that approach and respect it.

**Comment by smarts** [comment]
If atom is going to rely on git, why doesn't it do the following during installation:
have a list of paths that it looks through to find git, and if it doesn't, then install git

**Comment by paulcbetts** [comment]
I bet that @shiftkey, @niik, and @ammeep could think of a way for Atom to find GH4W's version of Git.

**Comment by luizpaulo165** [comment]
Just install the "msysGit" on site "https://msysgit.github.io/#contribute" and restart the PC. Projects start install normally.

**Comment by niik** [comment]
I think @kevinsawicki was looking at this the other day. Right now locating the git executable requires a bit of tinkering but it's doable.

**Comment by damieng** [comment]
The apm.cmd supplied with APM now detects and adds git.exe installed by GitHub Desktop/Windows to the path! https://github.com/atom/apm/blob/master/bin/apm.cmd
