### ISSUE TITLE
Broken (?) theming in 0.167.0

### ISSUE THREAD

**Issue by dmnd** [atom/atom#4903]
I installed 0.167.0 and immediately noticed that some colours were off. I'm using Atom Dark UI and syntax, and it seems much more washed out.

Compare 0.166.0:

![image](https://cloud.githubusercontent.com/assets/4427/5655012/16236cdc-967e-11e4-9200-b63e88700b9c.png)

Here's 0.167.0:

![image](https://cloud.githubusercontent.com/assets/4427/5655033/5cfb1074-967e-11e4-89e6-c95ce89768d8.png)

Messing around in settings, it seem that the UI and syntax theming is getting mixed up. Here's what it looks like with dark UI, light syntax:

![image](https://cloud.githubusercontent.com/assets/4427/5655125/0fea96c8-967f-11e4-8939-07f62f9bac9b.png)

**Comment by marshallbu** [comment]
:+1:

**Comment by nathansobo** [comment]
Fixed via a40632274828b9441942abe2c7a2975fd8581ace.
