### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/home/pbustos/Software/python/Demain/main.py'

### ISSUE THREAD

**Issue by pbustos** [atom/atom#4905]
Uncaught Error: EACCES, permission denied '/home/pbustos/Software/python/Demain/main.py'

**Atom Version**: 0.153.0
**System**: linux 3.16.0-28-generic
**Thrown From**: Atom Core

**Comment by benogle** [comment]
Please upgrade to the latest version of atom. This should have a better message in the newest version.
