### ISSUE TITLE
How do you listen for an event from inside the shadow dom?

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#4908]
I'm sorry if this is a stupid question but I'm stuck.  I need to respond to a click on a line-number inside the `atom-text-editor` and I can't figure out how to do it.  The dom shadow gets in my way for everything I try.  

A simple `$('.line-number')` gets zero matches when the dom shadow is enabled.  I can match on the `atom-text-editor` element but nothing inside.  I read the package update doc and it just refers to `$(window)` which doesn't help.

This is a bit of a duplicate from .https://discuss.atom.io/t/events-from-elements-inside-shadow-dom/14119.

**Comment by postcasio** [comment]
You can use `$('atom-text-editor::shadow .line-number')`. You can also get a reference to the shadow root with `atom.views.getView(editor).shadowRoot`.

**Comment by mark-hahn** [comment]
Thanks.  Sorry for wasting time here with a newbie question.
