### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/darrenrogan/development/ruby/thelocker/website/thelocker/project.json'

### ISSUE THREAD

**Issue by darrenrogan** [atom/atom#4909]
[Enter steps to reproduce below:]

1.  I'm just working on my rails / ember project. 
2. Keeps popping up this error
3. I don't have a project.json file, not sure whats trying to load it

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/darrenrogan/development/ruby/thelocker/website/thelocker/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/darrenrogan/development/ruby/thelocker/website/thelocker/project.json'
  at Error (native)

```

### Commands

```
     -0:02.1 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {},
  "editor": {
    "showInvisibles": true,
    "showIndentGuide": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.17.0
circle-ci, v0.3.0
ember-cli-helper, v0.4.0
ember-snippets, v1.0.0
language-docker, v1.1.1
language-ember-script, v0.1.0
language-emberscript, v0.1.0
language-emblem, v0.1.0
minimap, v3.3.12
recent-files, v0.3.0
ruby-slim, v0.2.0
save-session, v0.11.0
tabs-to-spaces, v0.8.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
This should be fixed in the latest version of save-session. Please upgrade the save-session package.

See https://github.com/mpeterson2/save-session/issues/43 for reference.
