### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/cassiano/gamesys/modules/gamesys_puppet_spec_helper/project.json'

### ISSUE THREAD

**Issue by cassianoleal** [atom/atom#4914]
1. Open terminal
2. cd into some application's directory where a `project.json` file does not exist
3. Type `atom` to open the editor
4. Boom!

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/cassiano/gamesys/modules/gamesys_puppet_spec_helper/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/cassiano/gamesys/modules/gamesys_puppet_spec_helper/project.json'
  at Error (native)

```

### Commands

```
     -0:00.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "editor": {
    "fontFamily": "Essential PragmataPro",
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
color-picker, v1.2.6
git-log, v0.2.0
git-tab-status, v1.3.0
language-apache, v1.2.0
language-chef, v0.4.0
language-docker, v1.1.2
language-haml, v0.14.0
language-puppet, v0.10.0
language-ruby, v0.47.0
language-ruby-on-rails, v0.18.0
linter, v0.9.1
minimap, v3.5.2
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.0
remote-edit, v1.6.3
ruby-define-method, v0.1.1
save-session, v0.11.2
sync-settings, v0.2.0
trailing-spaces, v0.2.3

# Dev
No dev packages
```

**Comment by cassianoleal** [comment]
This has now been happening randomly and usually in pairs (two of the same error each time) since I upgraded Atom to 0.168.0

**Comment by postcasio** [comment]
This is an issue with `save-session`, updating it to v0.11.3 should fix it.

**Comment by cassianoleal** [comment]
It's already on 0.11.3, and the error keeps popping up. I'm not sure how to gather more information, but I'd be glad to help debug this.

**Comment by postcasio** [comment]
Ah, sorry. The issue is here: https://github.com/mpeterson2/save-session/issues/43

**Comment by cassianoleal** [comment]
Cool, I'm closing this then. Thanks!
