### ISSUE TITLE
opening via zero opacity

### ISSUE THREAD

**Issue by vtworockman** [atom/atom#4915]
always atom application open via zerio opacity in linux mint 17 and i restore full opacity to show atom application
![screenshot from 2015-01-08 14 06 56](https://cloud.githubusercontent.com/assets/9331878/5661375/3c283954-9740-11e4-9f4b-16c8ee3baa8a.png)

**Comment by Swistaku** [comment]
That's possible cinnamon issue, see here -> https://github.com/linuxmint/Cinnamon/issues/3547

**Comment by vtworockman** [comment]
I problem just with Atom, so I disable effects and test it.
