### ISSUE TITLE
Atom 168 is stuck on endless update loop on Windows

### ISSUE THREAD

**Issue by jcgallaher** [atom/atom#4916]
After downloading the latest update for Atom .0168.0 for Windows, Atom appears to be stuck in an endless downloading update. After the update is downloaded and the install and restart Atom message appears, I click update and restart. After Atom starts again, it starts downloading the latest update again.

**Comment by motapc97** [comment]
The same happens to me. Windows 8.1 64-bit

![](http://i.imgur.com/Urt3fna.png)

**Comment by hastebrot** [comment]
Would be nice to be able to disable the update mechanism (e.g. by disabling a package) as a quick work-around.

**Comment by kevinsawicki** [comment]
I believe this is related to https://github.com/Squirrel/Squirrel.Windows/issues/145

Downgrades appear to not be working on Windows currently. We pulled the 0.168 and 0.167 builds on Windows last night after discovering a crash when clicking context menu items.

0.169 should be out shortly though with the crash fixed.

**Comment by motapc97** [comment]
I just found out that you can download `atom-windows.zip` file from the releases page and that it will not automatically update. It's a workaround for those who are experiencing the same problem. (sorry for my english)

**Comment by jonathandelgado** [comment]
The 0.169 update fixed the issue for me.

**Comment by aengelke** [comment]
Just downloaded and installed 0.169, and it installs 0.166 after starting atom (why?). Then it removes the just unpacked files from 0.166 again (except atom.exe). The shortcuts were changed to point to 0.166.

Relevant log:

```
Program: Starting Squirrel Updater: --update https://atom.io/api/updates
Program: Starting update, downloading from https://atom.io/api/updates
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: 
CheckForUpdateImpl: hwhat, local version is greater than remote version
FileDownloader: Downloading file: 
ApplyReleasesImpl: Writing files to app directory: C:\Users\aengelke\AppData\Local\atom\app-0.166.0
ApplyReleasesImpl: runPostInstallAndCleanup: starting fixPinnedExecutables
ApplyReleasesImpl: Processing shortcut 'C:\Users\aengelke\AppData\Local\atom\app-0.169.0\atom.exe'
ApplyReleasesImpl: Processing shortcut 'C:\Windows\explorer.exe'
ApplyReleasesImpl: Does not match 'C:\Users\aengelke\AppData\Local\atom\app-0.169.0', continuing to next directory
ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\aengelke\AppData\Local\atom\app-0.169.0\atom.exe]
ApplyReleasesImpl: cleanDeadVersions: for version 0.169.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.169.0
ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.169.0
... (Here it says that it removed several files from 0.166)
```

**Comment by Ingramz** [comment]
@aengelke do your desktop and taskbar icon point to the same version? The one on desktop seems to link to 0.169 and the one on taskbar to 0.166

**Comment by aengelke** [comment]
The shortcut in the start menu and on the desktop is not updated. This was also the case in Atom with Squirrel <0.165.

**Comment by kevinsawicki** [comment]
0.169 was just deployed on Windows so it should update to that now and no longer loop, sorry about this.

**Comment by jcgallaher** [comment]
Thanks @kevinsawicki
