### ISSUE TITLE
Uncaught Error: spawn /bin/oracle ENOENT

### ISSUE THREAD

**Issue by xylifyx** [atom/atom#4919]
[Enter steps to reproduce below:]

1. Open Go file
2. Choose Packages / Go Oracle / Oracle in the packages menu

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /bin/oracle ENOENT

```
At events.js:85

Error: spawn /bin/oracle ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

### Commands

```
     -0:15.0 core:backspace (input)
     -0:13.4 autocomplete-plus:cancel (input)
     -0:01.3 window:update-available (atom-workspace.workspace.theme-atom-dark-syntax.theme-atom-dark-ui.scrollbars-visible-always)
     -0:00.0 go-oracle:oracle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```
{}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
go-format, v1.0.7
go-oracle, v0.2.0
go-plus, v3.0.11

# Dev
No dev packages
```

**Comment by benogle** [comment]
Please install oracle the binary or make sure it is on your path.

**Comment by seveibar** [comment]
This may be an actual issue- I also got this error until I created a symlink from my binary to /bin/oracle, even though oracle was in my path.

**Comment by benogle** [comment]
You might want to check how the package thats shelling out to oracle is doing it. If it is a bug, it's likely a bug in that package.

**Comment by seveibar** [comment]
Thanks! It was in fact an issue with the configuration in the package.
