### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/{user}/{redacted}/project.json'

### ISSUE THREAD

**Issue by xdumaine** [atom/atom#4922]
1. launch atom from terminal
2. create new file

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/{user}/{redacted}/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/{user}/{redacted}/project.json'
  at Error (native)

```

### Commands

```
  2x -0:00.0 application:new-file (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "term"
    ]
  },
  "editor": {
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.1.3
atom-jshint, v1.5.0
autocomplete-plus, v0.21.0
caniuse, v0.4.2
color-picker, v1.2.5
editor-stats, v0.16.0
editorconfig, v0.2.1
jshint, v1.1.2
pdf-view, v0.14.0
save-session, v0.11.2
trailing-spaces, v0.2.3

# Dev
No dev packages
```

**Comment by xdumaine** [comment]
Currently getting this constantly while typing. Quitting atom doesn't help.

**Comment by benogle** [comment]
This is from save-session. Please upgrade save-session and try again.

**Comment by xdumaine** [comment]
Ran all updates and the issue seems to have gone away. Thanks.
