### ISSUE TITLE
Rendering artifacts since Chrome 39 upgrade

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#4924]
Most noticeable in the tree view, resizing it, scrolling, etc. makes it redraw and go away.

![screen shot 2015-01-07 at 2 47 31 pm](https://cloud.githubusercontent.com/assets/671378/5666877/fe272bc4-9717-11e4-9d81-c6f737e03def.png)

/cc @zcbenz Any ideas on this one?

**Comment by zcbenz** [comment]
I saw this too sometimes, I believe it is a rendering bug of Chrome.

**Comment by paulcbetts** [comment]
We're getting rendering issues too, though ours are worse; here's a video:

http://cl.ly/3q3x2t3F3f30

On both OS X and Windows, these boxes blank out (they should normally have content in them). The weird thing is, opening the Dev Tools seems to sometimes make the bug go away

**Comment by kevinsawicki** [comment]
@zcbenz So should we try reporting it to Chromium or maybe search their issue tracker?

**Comment by zcbenz** [comment]
We have to make it reproducible on Chrome browser, otherwise it would be unlikely for them to look into this.

I think we can check if this bug exists in Chrome 40 first, it is still beta but the next stable release should be quite close.

**Comment by simurai** [comment]
I saw it too on OS X, when I enabled "General > Show scroll bars: always" on a retina screen. But can't reproduce it when trying the same again.

Ohh.. It happened when using a theme that has a transparent scrollbar track. So might be related to #4578. The Atom Dark and One Dark theme now have an opaque scrollbar background, which might fix it.

**Comment by wyand** [comment]
@simurai I am seeing the tree view artifacts while using Atom Dark for both UI and syntax, on OSX.

**Comment by simurai** [comment]
@wyand Did you see it happen again just recently? I haven't seen it since making the scrollbars have an opaque color #4578.

**Comment by wyand** [comment]
@simurai I messed up! I I have not made the scrollbars opaque. Misunderstood the previous comment to imply that Atom Dark had opaque scrollbars by default. Sorry about that.

**Comment by simurai** [comment]
@wyand NP. Yeah, it used to be semi transparent, but got changed to opaque. Not sure when exactly, maybe since 1-2 weeks ago. So if you still see it happen from now on, then this issue might not be related to the scrollbar transparency.

**Comment by iclanzan** [comment]
It is still happening to me, on Atom 0.177  on OS X using One Dark UI.

**Comment by aldendaniels** [comment]
Yep - happening to me as well on Atom 0.176, OS X Yosemite using One Dark UI.

**Comment by idflood** [comment]
The problem is still visible for me, even after setting an opaque background to the scrollbars in my custom stylesheet.

One problem is that I can't find a way to reproduce the problem 100% of the time. The best I can find is to have a lot of files and nested folders and then try to scroll, open and close folders many times. Sometimes the bug is visible after 2 clicks but most of the time it take 10 or more clicks.

For reference here is the little css I added to my style:

    @bg: #1e232a;
    
    ::-webkit-scrollbar {
      background: @bg;
    }

    ::-webkit-scrollbar-corner {
      background: @bg;
    }

    ::-webkit-scrollbar-thumb {
      background: lighten(@bg, 10%);
      border: 0;
    }

**Comment by vincentisambart** [comment]
Here's a copy of what I wrote in #7361:
I often get the following display bug in the tree view, with some file names unreadable:
![screen shot](https://cloud.githubusercontent.com/assets/34704/8276774/42068ae2-18f5-11e5-8025-397a7f171172.png)
Using Atom 0.210 on OSX 10.10.3.

I can reproduce it pretty reliably the following way:
- `git clone --depth 1 https://github.com/CocoaPods/CocoaPods.git`
- `atom --safe CocoaPods`
- ensure no folder is expanded. If some are, just close all of them, close the window and Atom, and reopen it with `atom --safe CocoaPods`.
- expand `lib` → `cocoapods` → `installer` → `target_installer`

And I get the screenshot I posted above. Note that it seems to depend partly on the width of the tree view and window.

**Comment by kileras** [comment]
Same here in a retina iMac with 10.10.4 and Atom 1.0.0.

**Comment by techapman** [comment]
Similar problem here! Running Mac OS 10.10.4 on MacBook Pro
<img width="958" alt="atombug" src="https://cloud.githubusercontent.com/assets/12398454/8680371/f0ab318e-2a2e-11e5-94c2-0a4679dfd31a.png">

**Comment by zyklus** [comment]
+1, OSX 10.10.4, Atom 1.0.2, Chrome 43.0.2357.132
<img width="192" alt="screen shot 2015-07-23 at 11 07 37 pm" src="https://cloud.githubusercontent.com/assets/320562/8853956/e9a65e96-318f-11e5-9708-b637d86852f2.png">

**Comment by mnquintana** [comment]
For those following this issue, the rendering artifacts have nothing to do with the version of Chrome you have installed on your system – rather, this has to do with the version of Chrome (Chromium) that ships with [Electron](http://electron.atom.io/).

**Comment by techapman** [comment]
@mnquintana is there any way to fix it until Electron ships with a new version of Chromium?

**Comment by Nijikokun** [comment]
Welcome to my life. 

![image](http://dump.nexua.org/Screen_Shot_2015-06-09_at_5.18.35_PM.png)

**Comment by benogle** [comment]
We've upgraded a number of chrome versions since August. I haven't seen this in a while. Anyone else?

**Comment by iclanzan** [comment]
Can confirm this is no longer an issue for me.

**Comment by benogle** [comment]
Closing. If anyone sees this again on a recent version (>1.4.0), let us know!

**Comment by sunsunych** [comment]
OSX 10.11.3
Chrome Version 48.0.2564.116 (64-bit)
Atom 1.5.3

Still have issues with artifacts in Google Chrome.
![screen shot 2016-03-03 at 23 44 53](https://cloud.githubusercontent.com/assets/439547/13508980/5cd3a904-e19a-11e5-997f-8e51194f4a56.png)

**Comment by mnpenner** [comment]
Atom and other Electron-based programs are completely unusable for me. On Ubuntu 15.10. Had the same problem on an older version of Ubuntu.

![image](https://cloud.githubusercontent.com/assets/1112998/14499322/acb0b58e-0152-11e6-89e9-44b684330b18.png)

**Comment by WindfallLabs** [comment]
Atom 1.8.0 artifacting on Windows 8.x.  
Chrome Version "51.0.2704.84 m" was having similar issues until I turned off Hardware Acceleration. 

![atom_madness](https://cloud.githubusercontent.com/assets/10524780/16098526/be4e4cc6-3310-11e6-9fb0-ffbab5ce849e.PNG)
