### ISSUE TITLE
After 0.168 not able to press enter in any file

### ISSUE THREAD

**Issue by bobber205** [atom/atom#4925]
Enter does nothing.
***Alt-enter*** is needed to make a new line.
Also just updated to 169 and it persists. 
So far happening in both .haml files, ruby and js files.

**Comment by bobber205** [comment]
Looks like Command+/ doesn't do comment a line out anymore either? :(

**Comment by bobber205** [comment]
Tabbing also broken.

**Comment by bobber205** [comment]
Looks like this is issue with autocomplete-plus plugin. Reopening there.

**Comment by bobber205** [comment]
Reopening because this keeps happening even with that plugin turned off.

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by bobber205** [comment]
I've been in safe mode off and on all day and been seeing this all day. 
The best info I have is that it started with 168

**Comment by postcasio** [comment]
Do you have emmet installed? I've had this happen a couple of times and checking keybindings showed emmet was taking over the keybind.

**Comment by bobber205** [comment]
Emmet is indeed the cause. Uninstalled and cannot repo issue.

On Thu, Jan 8, 2015 at 2:42 PM, dominic <notifications@github.com> wrote:

> Do you have emmet installed? I've had this happen a couple of times and
> checking keybindings showed emmet was taking over the keybind.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/4925#issuecomment-69263734>.
>



-- 
Buoyancy and displacement float my boat.

**Comment by lee-dohm** [comment]
Closing since this seems to be resolved. Thanks @postcasio, you beat me to the punch :laughing:

Let us know if the issue reoccurs!
