### ISSUE TITLE
Return & Tab Keys no longer work at random

### ISSUE THREAD

**Issue by tylerFowler** [atom/atom#4926]
After updating to `0.169.0 ` I find that, seemingly at random, the Return and Tab keys on my MacBook Pro no longer work. Pressing them will just do nothing, and the only way to regain functionality is to completely quit atom and restart it, but even then it seems that it's only a matter of time before they stop working again.

Didn't see this at all before the update. No clues as to what's going on either.

**Comment by benogle** [comment]
Are you using autocomplete plus or emmet? Can you try `atom --safe`?

**Comment by kiriost** [comment]
I have the same problem on Linux!

**Comment by kiriost** [comment]
It seems to be a problema with autocomplete-plus plugin. Or with emet, maybe.

**Comment by 50Wliu** [comment]
Related to #4925 possibly?

**Comment by tylerFowler** [comment]
Haven't noticed it yet in safe mode, though I do have both autocomplete-plus and emmet. They never caused problems before now though.

**Comment by salimane** [comment]
+1

**Comment by Cipa** [comment]
disabling emmet made it work for me, but that's the most useful plugin for me :(

**Comment by benogle** [comment]
Can you guys open an issue on the emmet package?

**Comment by benogle** [comment]
Also, this might be related to the shadow dom being enabled by default. You can disable it for now in the settings. Though that will only be temporary, the issue will still need to be solved in the emmet package.

**Comment by tylerFowler** [comment]
+1 for Emmet causing this, disabled it and I haven't had the issue in the last several hours I've been working in Atom.

**Comment by benogle** [comment]
Can you try enabling emmet and disabling the shadow DOM? Does it happen then?

**Comment by tylerFowler** [comment]
Yes it still happens with the Shadow DOM disabled.

**Comment by lee-dohm** [comment]
Yeah, these exact symptoms have happened before with Emmet. See emmetio/emmet-atom#155 et al.

**Comment by marcker** [comment]
+1 :cry:

**Comment by benogle** [comment]
Closing in favor of https://github.com/emmetio/emmet-atom/issues/186
