### ISSUE TITLE
"ctrl-," keybinding only works if you hold it down (Ubuntu Linux)

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#4927]
**System**: Ubuntu 14.04.1 LTS
**Atom:** 0.169.0

**Steps to reproduce:**
1. Assign the keybinding `'ctrl-,'` to any command you want or leave it set to `settings-view:open`
2. Try entering the shortcut as you would any other keyboard shortcut. Nothing should happen.
3. Try entering the shortcut repeatedly. Nothing should happen.
4. Hold down the shortcut until the command executes.

This is definitely not a Mac issue, as I've never encountered it on my Mac running Yosemite - just on Ubuntu.

**Comment by 50Wliu** [comment]
I can't reproduce on Ubuntu 14.10, Atom 0.169.

**Comment by mnquintana** [comment]
@50Wliu Hmmm that's interesting, I wonder if it's specific to the LTS release? I'll investigate when I get home and I can try installing a bunch of clean VMs.

**Comment by mnquintana** [comment]
Can't reproduce on a clean Ubuntu 14.04.1LTS VM (with all the same Atom packages installed) with Atom 0.169.0. Looks like there's something weird going on with my Ubuntu at work. I'll keep investigating.

**Comment by barwinco** [comment]
do you have Emmet package installed? try to disable it.

**Comment by mnquintana** [comment]
Nope, don't have Emmet.

**Comment by lee-dohm** [comment]
I just tried reproducing this on my Ubuntu 14.04 VM:

1. Install updates
1. Install Atom (following the instructions in the README)
1. Launch Atom using `atom` from the same terminal window I just used to install it
1. Press <kbd>Ctrl+,</kbd>

**Expected and Actual:** Settings View opened immediately without having to hold down the key for any extended period of time.

**Comment by ricardograca** [comment]
I also tested in my Ubuntu 14.04 PC and I can't reproduce the bug. Pressing `ctrl+,` immediately opens the settings window.

**Comment by mnquintana** [comment]
I just tried:

1) Starting Atom in safe mode with `atom --safe`,
2) Tried uninstalling and reinstalling Atom on my Ubuntu 14.04 LTS computer at work, 

but I'm experiencing the same problem. 

I'm wondering what about my installation (or maybe even drivers) could be causing issues with this. I kinda doubt it's a driver issue though because I tried assigning `Ctrl+,` to an OS global hotkey shortcut for something, and the shortcut worked as expected.

**Comment by ricardograca** [comment]
It seems that Atom has several issues related to keyboard layouts, especially in non-English ones. Maybe the PC/keyboard you're using at work is using a layout that is causing that issue. What does the keybinding resolver (accessed with `ctrl+.`) say when you press `ctrl+,`?

**Comment by mnquintana** [comment]
@ricardograca Just checked my keyboard layout, and I'm using US English (contents of `/etc/default/keyboard`):

```ini
XKBMODEL="pc105"
XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS=""
```

When I have the keybinding resolver open and press `Ctrl+,`, nothing happens. If I hold it down, then eventually I get this:

![screenshot from 2015-01-12 10 34 30](https://cloud.githubusercontent.com/assets/823545/5705368/cfe7ffea-9a46-11e4-8684-a2a5cb16cabf.png)
Oddly enough though, when I clicked on the file path for the first key binding `settings-view:open` and opened the `settings-view.json` file, it was completely empty, which doesn't make any sense to me because it is definitely set in the [`.cson` version of the file.](https://github.com/atom/settings-view/blob/master/keymaps/settings-view.cson)

---
I also just noticed that when I uninstalled Atom before I missed the `.atom` folder in my user directory, so I tried deleting that this time and reinstalling again, but still no luck.

The only other thing I can think of is that maybe there are some weird remnants left from when I tried installing GNOME on here and it's interfering with that key binding for some reason (which I could only resolve by reinstalling the OS).

**Comment by ricardograca** [comment]
Have you checked the Accessibility options in that PC? There may be some setting there causing that behavior. Or it may be that some other package (leftover from your Gnome installation attempt) is grabbing that particular keyboard shortcut.

BTW, my `settings-view.json` file is also empty. In fact I don't think it even exists, since Atom throws an error whenever I open it (although it seems to be able to open it).

**Comment by mnquintana** [comment]
OMG I GOT IT! In System Settings > Keyboard > Shortcuts > Custom Shortcuts, I had a Custom Shortcut set for the command "Preferences", set to `Ctrl+,`. When I removed it, Atom's settings-view opened normally - when I put it back, I got the previous buggy behavior. Problem solved!

Thanks everyone! :smiley:
