### ISSUE TITLE
Error Installing Atom Package on Windows 8.1

### ISSUE THREAD

**Issue by GGillan** [atom/atom#4931]
After insuring that Atom can find Git (see Atom issue #4902, which resulted in success for Windows 7), the installation of a package is running into an error later in the process. The log says to open an issue for npm (npm issue # 7100), but there I was advised that Atom bundles an older version of npm that is no longer supported and that the error should be reported here.

Here is the entire log:

Installing “Sublime-Style-Column-Selection@1.1.3” failed.Hide output…

npm http GET https://registry.npmjs.org/emissary
npm http 200 https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/emissary/-/emissary-1.3.1.tgz
npm http 200 https://registry.npmjs.org/emissary/-/emissary-1.3.1.tgz
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/property-accessors
npm http 200 https://registry.npmjs.org/mixto
npm http 200 https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http GET https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm http 200 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.6.tgz
npm http 200 https://registry.npmjs.org/mixto/-/mixto-1.0.0.tgz
npm http 200 https://registry.npmjs.org/property-accessors/-/property-accessors-1.1.0.tgz
npm ERR! git clone https://github.com/Benvie/harmony-collections.git 
npm http 200 https://registry.npmjs.org/underscore-plus/-/underscore-plus-1.6.6.tgz
npm ERR! Error: Command failed: 
npm ERR! at ChildProcess.exithandler (child_process.js:648:15)
npm ERR! at ChildProcess.emit (events.js:98:17)
npm ERR! at maybeClose (child_process.js:756:16)
npm ERR! at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this entire log,
npm ERR! including the npm and node versions, at:
npm ERR! http://github.com/npm/npm/issues

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\Users\George\AppData\Local\atom\app-0.169.0\resources\app\apm\node_modules\atom-package-manager\bin\\node.exe" "c:\Users\George\AppData\Local\atom\app-0.169.0\resources\app\apm\node_modules\atom-package-manager\node_modules\npm\bin\npm-cli.js" "--globalconfig" "c:\Users\George\AppData\Local\atom\app-0.169.0\resources\app\apm\node_modules\atom-package-manager\.apmrc" "--userconfig" "c:\Users\George\.atom\.apmrc" "install" "C:\Users\George\AppData\Local\Temp\d-11508-8052-1qh51th\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\George\AppData\Local\Temp\apm-install-dir-11508-8052-1g96iav
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code -1073741515
npm

**Comment by kevinsawicki** [comment]
> The log says to open an issue for npm (npm issue # 7100), but there I was advised that Atom bundles an older version of npm that is no longer supported and that the error should be reported here.

The version of npm shipped with Atom/apm has been upgrade several times to newer version so I'm going to close this out as fixed now, please comment if you still see it happening on Atom 1.0.3+ and include the new error details please.
