### ISSUE TITLE
Better documentation for Disposables

### ISSUE THREAD

**Issue by postcasio** [atom/atom#4934]
One of the most common issues I've noticed with Atom packages is they fail to dispose their Disposables. This causes a whole load of problems with callbacks being registered multiple times when updating packages (or disabling and re-enabling them). Updating packages to fix issues often doesn't work because the old, broken callbacks stick around until you restart Atom.

The package development documentation hasn't really been updated since Disposables were introduced. [Your First Package](https://atom.io/docs/v0.169.0/your-first-package) and the [ascii-art package](https://github.com/atom/ascii-art/blob/master/lib/ascii-art.coffee) show how to register commands, but don't hold on to the Disposable, and don't call `dispose` in the `deactivate` method:

```coffee
atom.workspaceView.command "ascii-art:convert", => @convert()
```

A few examples of popular packages not behaving properly:

### emmet
https://github.com/emmetio/emmet-atom/blob/60ad28616defddc8fb8746476717cc726b53b15b/lib/emmet.coffee#L117

### linter
https://github.com/AtomLinter/Linter/blob/eff2c313efc240aca8d4bc3f9b7dc811988c8bd4/lib/linter-view.coffee#L94
https://github.com/AtomLinter/Linter/blob/eff2c313efc240aca8d4bc3f9b7dc811988c8bd4/lib/linter-view.coffee#L116

### color-picker
https://github.com/thomaslindstrom/color-picker/blob/e9b64487f827223ca9ec0479f7075db48b43f02d/lib/ColorPicker.coffee#L18

### atomatigit
https://github.com/diiq/atomatigit/blob/d521a615517e4e0643987cc4e02fd3a307205be0/lib/atomatigit.coffee#L43

So package developers often have no idea they're missing something. I think this is unfortunately contributing to a negative image - while Atom's core packages are great, users are bound to associate the problems caused by third party packages with Atom itself.

It needs to be made more explicit that when you register commands or other callbacks, you need to hold on to the Disposable, and you need to dispose it properly when you're done with it.

**Comment by benogle** [comment]
This is a legit concern. Thanks for bringing it up. We all talked about this last night. We discussed things from better docs, to some crazy package linter, to somehow tagging all disposables with the package they were created by. We're not totally sure what the right way forward is at this time though.

**Comment by postcasio** [comment]
> tagging all disposables with the package they were created by

This is something I thought about too, but I don't know how feasible it is.

I'm going to take a stab at updating the ascii-art package and the "Your First Package" tutorial this weekend, anyway.

**Comment by benogle** [comment]
> and the "Your First Package" tutorial

Cool. That would be super helpful. The minimum we can do is better docs.

**Comment by kevinsawicki** [comment]
I feel like this can be closed now, the flight manual, ascii-art repo, `apm init` examples, and API docs all track disposables consistently and clean them up accordingly.

**Comment by paulcbetts** [comment]
Do you have a port of `SerialDisposable` and `CompositeDisposable` from RxJS? This makes it _much_ easier to correctly clean up disposables.

**Comment by mnquintana** [comment]
@paulcbetts There is a `CompositeDisposable` - not sure how `SerialDisposable` works

**Comment by paulcbetts** [comment]
`SerialDisposable` is a Disposable which has exactly one "Slot" for an inner Disposable - if you set it, the previous one gets trashed:

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/disposables/serialdisposable.md

So any time you want to have an "Active" Disposable, (i.e. zero or one things), SerialDisposable is a huge help
