### ISSUE TITLE
*HUGE* memory leak

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#4938]
I just tested .168 and .169 and there is a <b>huge</b> memory leak.
I can't tell when exactly this started happening, but around .150 I don't recall seeing this.

What is the memory leak about?

When I launch Atom, it starts using 20% of my CPU (around 80% of 1 core) and keeps taking RAM until it hits 3GB, and then it stop taking RAM but it keeps using 20% of my CPU.

How I reproduce it?

I'm unable to reproduce the bug with `atom --safe`.
Anyways, I am able to reproduce the bug after completely removing `~/.atom` and then running `atom`, so this bug isn't caused by an external plugin or skin, but by some Atom plugin that isn't loaded with `--safe`.

What OS?

I'm on Arch Linux x64, everything is up to date. KDE desktop with KWin as WM. NVidia proprietary driver. Atom was installed via AUR.

**Comment by mark-hahn** [comment]
> this bug isn't caused by an external plugin or skin, but by some Atom
plugin that isn't loaded with --safe.

The definition of --safe is to not load external plugins, aka add-ons, aka
packages.  So it is very likely it is an add-on package.  You can use my
package `package-cop` to isolate which package is causing it.


On Thu, Jan 8, 2015 at 5:22 PM, Alexander Nestorov <notifications@github.com

**Comment by alexandernst** [comment]
@mark-hahn Are there any plugins that are installed outside `~/.atom` ? If not, then there simply are no external plugins as I'm deleting the entire folder.

**Comment by mark-hahn** [comment]
> Are there any plugins that are installed outside  ~/.atom ?

Just the core ones and any you've created somewhere else and linked.

On Thu, Jan 8, 2015 at 6:16 PM, Alexander Nestorov <notifications@github.com

**Comment by alexandernst** [comment]
Then it's a bug with some Atom plugin, because, as I already said, I remove the `~/.atom` folder before running Atom. There just can't be any 3rd party plugins. (and I haven't created any plugins myself).

**Comment by lee-dohm** [comment]
As far as I know, there aren't any Atom default-installed plugins that are not loaded in Safe Mode. It *could* be some difference in behavior between Safe Mode and non-Safe Mode ... but there isn't that much of a difference.

https://github.com/atom/atom/blob/d47efdb2f10b0d57933df744627f84d6cddbe407/src/package-manager.coffee#L35-L38

The non-obvious difference is here:

https://github.com/atom/atom/blob/d47efdb2f10b0d57933df744627f84d6cddbe407/src/theme-manager.coffee#L173-L209

When the configured themes aren't available because of running in Safe Mode (or they've been deleted by hand) it defaults to `atom-dark-ui` and `atom-dark-syntax`.

**Comment by alexandernst** [comment]
Well... there must be some difference, because there aren't any external plugins/skins, and Atom is mem-leaking if not run in safe mode. I can provide strace output (or anything else if you ask) if that would be helpful.

**Comment by induane** [comment]
I've noticed this as well - but only because I was looking at some other processes. My system has 48GB of Ram and 16 cores; I simply never noticed it eating up those resources before.

I can confirm that -safe also works for me and that the additional resource consuming happens even after clearing ~/.atom, ~/.config/Atom & ~/.config/Atom-Shell

Ubuntu 14.10 - Linux WormFlush 3.16.0-28-generic #38-Ubuntu SMP Fri Dec 12 17:37:40 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lee-dohm** [comment]
I wasn't suggesting you were wrong, just adding more info to the bug :grinning: I'm not sure what would help the guys debug this, so I'll let them chime in.

**Comment by lee-dohm** [comment]
Just out of curiosity @alexandernst, can you try installing from the https://atom.io website instead of AUR?

**Comment by alexandernst** [comment]
Btw, my hardware: 

[alexandernst@stupidbox 0s ~]$ uname -a
Linux stupidbox 3.17.6-1-ARCH #1 SMP PREEMPT Sun Dec 7 23:43:32 UTC 2014 x86_64 GNU/Linux

[alexandernst@stupidbox 0s ~]$ hwinfo --cpu
01: None 00.0: 10103 CPU                                        
  [Created at cpu.452]
  Unique ID: rdCR.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: X86-64
  Vendor: "GenuineIntel"
  Model: 6.45.7 "Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz"
  Features: fpu,vme,de,pse,tsc,msr,pae,mce,cx8,apic,sep,mtrr,pge,mca,cmov,pat,pse36,clflush,dts,acpi,mmx,fxsr,sse,sse2,ss,ht,tm,pbe,syscall,nx,pdpe1gb,rdtscp,lm,constant_tsc,arch_perfmon,pebs,bts,rep_good,nopl,xtopology,nonstop_tsc,aperfmperf,eagerfpu,pni,pclmulqdq,dtes64,monitor,ds_cpl,vmx,est,tm2,ssse3,cx16,xtpr,pdcm,pcid,dca,sse4_1,sse4_2,x2apic,popcnt,tsc_deadline_timer,aes,xsave,avx,lahf_lm,ida,arat,epb,pln,pts,dtherm,tpr_shadow,vnmi,flexpriority,ept,vpid,xsaveopt
  Clock: 1400 MHz
  BogoMips: 6402.73
  Cache: 10240 kb
  Units/Processor: 32
  Config Status: cfg=new, avail=yes, need=no, active=unknown


[alexandernst@stupidbox 0s ~]$ hwinfo --memory
01: None 00.0: 10102 Main Memory                                
  [Created at memory.74]
  Unique ID: rdCR.CxwsZFjVASF
  Hardware Class: memory
  Model: "Main Memory"
  Memory Range: 0x00000000-0x7d68bafff (rw)
  Memory Size: 32 GB
  Config Status: cfg=new, avail=yes, need=no, active=unknown

**Comment by CumpsD** [comment]
I can reproduce this on Windows using https://github.com/atom/atom/releases/download/v0.178.0/atom-windows.zip

I extracted the zip, added an environment variable for ```ATOM_HOME``` and simply started atom from commandline with ```atom .```

```
App load time: 156ms
[8256:0211/075640:INFO:renderer_main.cc(211)] Renderer process started
[8256:0211/075709:ERROR:atom_bindings.cc(32)] Fatal error in V8: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

It took 25% cpu (a whole core) and lots of RAM before it outputted the process out of memory line.

It was a clean setup, the home directory is empty, and there was nothing left in AppData.

**Comment by CumpsD** [comment]
Problem resolved. My ```ATOM_HOME``` contained 2 paths instead of one. Fixing that started atom again.

**Comment by batjko** [comment]
@CumpsD That's interesting behavior though. In that case, the path should have been rejected as invalid.

**Comment by alexandernst** [comment]
I'm closing this as I can't reproduce anymore in release 186. The problem got fixed somewhere in between.

**Comment by irakli2692** [comment]
for me, when ide-typescript is enabled atom memory usage increases regularly

**Comment by lee-dohm** [comment]
@irakli2692 Please file a new issue on the ide-typescript repository. This issue was fixed a number of years ago.
