### ISSUE TITLE
Formatting issue when pasting code

### ISSUE THREAD

**Issue by fpeng12** [atom/atom#4941]
When pasting code that omits brackets in one-line loops, such as:
for (int i = 0; i < 10; i++)
  num ++;
all following lines will be auto indented. This also happens when one does Edit-Lines-Auto Indent.

**Comment by benogle** [comment]
I'm not clear on what is happening vs what you want to happen. Can you elaborate?

**Comment by fpeng12** [comment]
This problem is gone once I update to v0.169. But just for completeness:

One runs into this problem when pasting blocks of code that contains loops like above, where {} are omitted. After pasting, the loop itself will be formatted correctly, but all lines in the pasted block that follow the loop will be indented by one additional tab.

A simple example:

int num = 0;
for (int i = 0; i < 10; i++)
    num ++;
int a = num;

if this whole thing is pasted into Atom, the last line will be indented by a tab.
