### ISSUE TITLE
Uncaught Error: socket hang up

### ISSUE THREAD

**Issue by sathyamoorthi** [atom/atom#4942]
What i did when i got this error:

1. I opened settings panel and i was in themes menu.
2. I clicked Packages menu. App did not respond. So clicked other menus fast. I got this error message.

**Atom Version**: 0.169.0
**System**: Microsoft Windows 8.1 Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: socket hang up

```
At stream.js:94

Error: socket hang up
  at createHangUpError (_http_client.js:214:15)
  at TLSSocket.socketOnEnd (_http_client.js:292:23)
  at TLSSocket.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:386:11)

```

### Commands

```
     -30:00.0 command-palette:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@sathyamoorthi Can you reproduce the error reliably? Are you behind a proxy?

**Comment by sathyamoorthi** [comment]
@izuzak Yes. I was behind a proxy. Actually i installed Atom today and it happened at the first time. I'm not able to reproduce it now.

**Comment by izuzak** [comment]
Thanks for letting us know, closing this then.
