### ISSUE TITLE
onDidChangeActivePaneItem triggered without the activePane item in the callback

### ISSUE THREAD

**Issue by skandasoft** [atom/atom#4946]
with the latest update 0.169.0 onDidChangeActivePaneItem is triggered without the activePane item in the callback when atom.workspace.open  is called

**Comment by maxbrunsfeld** [comment]
I can't reproduce this. From the dev tools:

```javascript
atom.workspace.onDidChangeActivePaneItem(function(item) { console.log("item:", item); });
atom.workspace.open("/Users/maxbrunsfeld/github/atom/.gitignore");

// output:
// item: TextEditor {softTabs: true…}
```

**Comment by maxbrunsfeld** [comment]
Can you report your list of installed packages (`apm list`) and your OS?

**Comment by benogle** [comment]
What happens when the only pane is removed/closed? It is null then?

**Comment by benogle** [comment]
After testing, it is correctly undefined when a pane's last item is removed. I'm going to close this out.

**Comment by postcasio** [comment]
@benogle the docs for this method say it returns an event object with an `activeItem` property https://atom.io/docs/api/v0.169.0/Workspace#instance-onDidChangeActivePaneItem but it returns just the item itself. Which behaviour is intended?

**Comment by maxbrunsfeld** [comment]
Thanks for catching that @postcasio. I think we should change the docs. The status-bar currently [relies on the current behavior](https://github.com/atom/status-bar/blob/master/lib/cursor-position-view.coffee#L5), as do two or three community packages.
