### ISSUE TITLE
Add Screenshot support to Markdown editing

### ISSUE THREAD

**Issue by DinisCruz** [atom/atom#4950]
One of the best features of the GitHub Issues UI (the one I'm currently writing on),  is the fact that I can just copy and paste images,  from the clipboard directly into an issue body.

It would be great if (when editing an Markdown file, as shown below) I could also just copy an paste an image. With the workflow being the same as now with the web UI:
- user takes screenshot locally
- user copy and paste into isue
- message 'uploading' is shown for a couple secs
- when upload is complete, the 'uploading' message is replaced with the actually Markdown image URL (as uploaded to the cloud.githubusercontent.com server)

![image](https://cloud.githubusercontent.com/assets/656739/5680245/8399c204-9802-11e4-8227-6c6f0514008e.png)

**Comment by lee-dohm** [comment]
Not the *exact* workflow you were asking for, but @mark-hahn created the [auto-host-markdown-image package](https://atom.io/packages/auto-host-markdown-image) for specifically this kind of thing.

**Comment by DinisCruz** [comment]
Kinda off, but even compared with that workflow, it is faster for me to have an github issues page open in a tab, and just copy and paste into it (to get the the image url)  :)

I also would like to use the GitHub image serving service, since its bound to me much more future proff

**Comment by allenhwkim** [comment]
+1, drag/drop is one thing, and copy/paste is another
