### ISSUE TITLE
Atom crash on load with 'SyntaxError: Unexpected end of input'

### ISSUE THREAD

**Issue by DinisCruz** [atom/atom#4951]
after installing https://atom.io/packages/git-plus, after Atom rebooted, I got this: 

![image](https://cloud.githubusercontent.com/assets/656739/5680373/5c42ea12-9804-11e4-8544-9ff494e59b2f.png)

the error happened in this line:

![image](https://cloud.githubusercontent.com/assets/656739/5680379/6f4e3986-9804-11e4-8c22-2d1f5a0b907b.png)

**Comment by DinisCruz** [comment]
For reference it loaded ok, on 2nd start

**Comment by kevinsawicki** [comment]
Do you remember how you launched Atom when it failed?

**Comment by DinisCruz** [comment]
If I remember correctly there something saying 'a restart is needed, click here to restart'

**Comment by kevinsawicki** [comment]
Great, thanks

**Comment by kevinsawicki** [comment]
This is now guarded against via https://github.com/atom/atom/blob/cf6a6fe2b129f676328de1f615c4857f5b56f9d6/static/index.js#L188-L196 so I think this can be closed out. Please comment if you still see it happening on Atom 1.0.3+
