### ISSUE TITLE
Checking for update says I am on the current version

### ISSUE THREAD

**Issue by aDroidman** [atom/atom#4952]
I installed Atom via the Windows exe. I was running version 166 and it did not auto update to version 167 or 168. I uninstalled and downloaded the exe again to install 168. Version 169 has been released and it still is not finding the update. 

Any idea why it is not finding the latest version?

**Comment by 50Wliu** [comment]
From what @kevinsawicki said in another issue, I believe they retracted the 0.167 and 0.168 versions due to a major crash bug.  Squirrel might not be able to handle that yet?  Kinda just guessing here.

**Comment by kevinsawicki** [comment]
Perhaps trying going directly to 169 by uninstalling 168 and downloading 169

**Comment by aDroidman** [comment]
I uninstalled 198 and installed 169 and it updated to 170 without any issues. Thanks!
