### ISSUE TITLE
Uncaught Error: getaddrinfo ENOTFOUND avatars1.githubusercontent.com

### ISSUE THREAD

**Issue by papac** [atom/atom#4953]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: linux 3.13.0-43-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: getaddrinfo ENOTFOUND avatars1.githubusercontent.com

```
At stream.js:94

Error: getaddrinfo ENOTFOUND avatars1.githubusercontent.com
  at errnoException (dns.js:41:10)
  at Object.onlookup [as oncomplete] (dns.js:91:26)

```

### Commands

```
     -0:00.0 settings-view:change-themes (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "editor": {
    "fontSize": 14,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v1.1.0
color-picker, v1.2.6

# Dev
No dev packages
```

**Comment by damonkreft** [comment]
:+1:

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/settings-view/commit/3fe0db5dc1c7db9f936b506a126d689057a24e0d
