### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, cause=socket hang up

### ISSUE THREAD

**Issue by Fank** [atom/atom#4958]
[Enter steps to reproduce below:]

Ubuntu:
1. Enter proxy settings in System settings and apply them globaly
2. Start atom (ive done this via launcher)

Atom:
3. Open Settings (ctrl + ,)
4. Click on + Install
-> Now the complete atom freezes until the socket timeout is reached (10 - 30seconds)
-> Feels like the socket thread are syncron with the main thread

The same problem exist in Windows too.

**Atom Version**: 0.169.0
**System**: linux 3.13.0-32-generic (Unbuntu 14.04)
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: tunneling socket could not be established, cause=socket hang up

```
At events.js:85

Error: tunneling socket could not be established, cause=socket hang up
  at ClientRequest.onError (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/tunnel-agent/index.js:168:17)
  at ClientRequest.g (events.js:199:16)
  at ClientRequest.emit (events.js:107:17)
  at TLSSocket.socketOnEnd (_http_client.js:292:9)
  at TLSSocket.emit (events.js:129:20)
  at _stream_readable.js:907:16
  at process._tickCallback (node.js:386:11)

```

### Commands

```
     -0:00.0 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Fank** [comment]
We have "internet connection failures" sometimes so i got this error often, when try to install new packages/themes

**Comment by zcbenz** [comment]
@Fank Does your proxy require username and password to use?

**Comment by Fank** [comment]
No only URL is needed

**Comment by zcbenz** [comment]
I can not reproduce on both Ubuntu 14.04 and Windows 8.1, I wonder whether it is related to the proxy server. Are you able to test with another proxy server?

**Comment by Fank** [comment]
not at work, ill try to reproduce this at home

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/settings-view/commit/3fe0db5dc1c7db9f936b506a126d689057a24e0d

**Comment by Fank** [comment]
Tested with 0.172.0, and works fine thanks

**Comment by liujb** [comment]
My atom version is 1.7.2. OS is mac osx. when I install package show

```
Installing “activate-power-mode@0.4.1” failed.Hide output…
Unable to download https://www.atom.io/api/packages/activate-power-mode/versions/0.4.1/tarball: socket hang up
```
How to solved this problem.
