### ISSUE TITLE
npm WARN package.json github-url-from-git No repository field

### ISSUE THREAD

**Issue by stramel** [atom/atom#4960]
I was unsure where to post this, but it seems like an easy fix for someone who has the knowledge of where it is.

During every install of atom, when it says `Installing apm...` I get the error:

```console
Installing apm...
npm WARN package.json github-url-from-git@1.1.1 No repository field.
```

**Comment by dideler** [comment]
I also get this warning.

**Comment by benogle** [comment]
Yeah, me too

**Comment by kevinsawicki** [comment]
I believe this has been resolved with the recent apm upgrade to use npm 2.x
