### ISSUE TITLE
Key binding and context menu selectors can't cross the shadow DOM

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#4961]
This is because `Element.matches` doesn't handle `::shadow` selectors properly. We could should probably add a special case to support them because the ability to target specific grammar scopes is an important feature.

**Comment by caleb531** [comment]
+1—aside from being a much-needed ability, this is also a great feature to have, as it brings a great deal of potential to the kinds of keybindings one could create.

**Comment by nathansobo** [comment]
This won't happen before 1.0 without some help. We need someone to implement a selector matcher that can cross shadow boundaries since `HTMLElement::matches` doesn't work that way in Chromium currently.

**Comment by caleb531** [comment]
Since[Atom 1.13 [removed the shadow DOM boundary](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html) from the editor, I think this issue can be closed now.
