### ISSUE TITLE
User Styles not loading with shadow DOM

### ISSUE THREAD

**Issue by sangregoriopaolo** [atom/atom#4962]
After the last release of yesterday, my stylesheet (that was working before) is not loading anymore.

**Comment by benogle** [comment]
If you disable the shadow DOM in the settings and reload the editor, does it work again?

Can you paste in your stylesheet?

**Comment by sangregoriopaolo** [comment]
Hi, disabling the shadow dom and restarting atom fixes the issue! thanks!

Here is my stylesheet, anyway:

    atom-text-editor .selection .region {
      background-color:#333;
    }

    atom-text-editor .invisible-character {
      color:#555;
    }

    .editor.is-focused .selection .region {
      background-color:#333;
    }

    .editor {
      background:#111;
    }

    .tree-view {

    }

    atom-text-editor {

    }

    atom-text-editor .cursor {

    }

**Comment by benogle** [comment]
You need to update your sheet for the shadow DOM change. You should be able to get away with changing it to this:

```
atom-text-editor::shadow .selection .region {
  background-color:#333;
}

atom-text-editor::shadow .invisible-character {
  color:#555;
}

atom-text-editor.is-focused::shadow .selection .region {
  background-color:#333;
}

.editor {
  background:#111;
}
```

Check out this document: https://atom.io/docs/latest/upgrading/upgrading-your-ui-theme

**Comment by benogle** [comment]
@nathansobo are we autoconverting the user's sheet? Can we? Or can we detect that they have improper styles and pop up a notification when the shadow DOM is enabled?

**Comment by sangregoriopaolo** [comment]
Great, it worked! Sorry for not being able to find that document by myself!

**Comment by benogle** [comment]
No prob, we should be better about notifying you that you need to make changes.

**Comment by nathansobo** [comment]
@benogle We could scan for `.editor` and `atom-text-editor` selectors that have descendants without a `::shadow` and warn...

**Comment by benogle** [comment]
That would be nice. Then I can write up a doc specific to the user sheet (basically trimmed down version of that doc above), and we can link to it in the doc. I think a notification rather than dep cop would be the best thing for the user sheet as the user can fix it.

**Comment by andrewpbrett** [comment]
Thanks for pointing in the right direction. FWIW this issues page was the first place I looked. A notification would be great!

**Comment by Zren** [comment]
The [default stylesheet](https://github.com/atom/atom/blob/master/dot-atom/styles.less) should be updated. I don't believe the `atom-text-editor .cursor {}` rule will work.

Eg:

```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

atom-text-editor {

}

/*
 * The editor itself uses a shadow DOM so rules must start with
 * atom-text-editor::shadow or they will be ignored.
 */
atom-text-editor::shadow {
  .cursor {
    
  }
}
```

**Comment by nathansobo** [comment]
@Zren Thanks for pointing that out. Updated via ab4588571dcbba05dbd15d3257bebdd0cce3d2d3.

**Comment by benogle** [comment]
Closing in favor of https://github.com/atom/atom/issues/5149 for a message.
