### ISSUE TITLE
Post an info notification in response to editor:log-cursor-scope

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#4969]
See: https://discuss.atom.io/t/how-to-see-what-syntax-markup-is-being-used/14172

Needing the console open inhibits the discoverability of this *very* useful command. If it popped up a notification, some Sublime users might try the key combination out of habit (I know I did when I first started using Atom) and get a little warm fuzzy out of it. (Besides putting notifications to use in a situation other than error logging :grinning:)

**Comment by benogle** [comment]
One could just replace the console log with 

```
atom.notifications.addInfo(scopes, dismissable: true)
```

**Comment by lee-dohm** [comment]
Cool ... I'll take care of this then. Thanks for the pointer!
