### ISSUE TITLE
last installer not working on windows

### ISSUE THREAD

**Issue by hanoc** [atom/atom#4977]
Hi,

I've just downloaded the windows installer and run it on windows and it's not installing.

I'm trying to install it into a operating sistem that has never had atom before.

Sometimes I get to see a "deplyment screen" (the rocket and the boxes) and less than a second after it closes.
Sometimes I don't see even that.

I've tried running in compatibility mode and as administrator with the following operating sistems:
windows 7.1
windows 8.0
windows 8.1

with the same results.

I don't know how to give more information... I've tried running atomsetup.exe from powershell but it just launches and closes without any output on the console.

I'm willing to provide more reports if somebody indicates me how to do it.

thanks!

**Comment by mark-hahn** [comment]
Did you get the installer from the atom.io home page?  Did you get a fresh
copy for all those different install attempts?

**Comment by hanoc** [comment]
Yes, to both questions.

I've just tried again with same results.

**Comment by 50Wliu** [comment]
Did `%userprofile%/AppData/local/.atom` get created?  If so, see if there's a `SquirrelSetup.log` or something similar in there and post that here.

*I'm on Ubuntu right now, so the installer path might be a bit different (I'm not sure if I remembered it correctly).

**Comment by Moter8** [comment]
(Installed Atom today on a Win10 VM, everything worked) - not a global issue I'd say

**Comment by kevinsawicki** [comment]
@hanoc Can you try again with the latest release? 0.170

**Comment by hanoc** [comment]
Sorry not to have answered before.
I don't have the windows machines I'm having trouble with available every day.

Anyway.. 

@50Wliu I only had a packages folder in the route you specified. No log.

although... @kevinsawicki After downloading the latest installer I run it again and the instalation process itself dettected a problem and opened a squirrel log by itself.

Here are it's contents:

	Program: Starting Squirrel Updater: --install .
	Program: Starting install, writing to C:\Users\nitrel\AppData\Local\SquirrelTemp
	CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.FileNotFoundException: Could not find file 'C:\Users\nitrel\AppData\Local\atom\packages\RELEASES'.
	File name: 'C:\Users\nitrel\AppData\Local\atom\packages\RELEASES'
	   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
	   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
	   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
	   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
	   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
	Utility: Starting to delete folder: C:\Users\nitrel\AppData\Local\atom\packages
	CheckForUpdateImpl: Reading RELEASES file from C:\Users\nitrel\AppData\Local\SquirrelTemp
	CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch

**Comment by batjko** [comment]
Sounds like this can be closed then...

**Comment by hanoc** [comment]
I see you have already seen this other issue:
https://github.com/atom/atom/issues/5074

Which I'm not sure if it's related.

The instalation did not faill, so yes, this one can be closed.
