### ISSUE TITLE
Snippets not working with Shadow DOM

### ISSUE THREAD

**Issue by sangregoriopaolo** [atom/atom#4978]
My super easy snippets file

    '.source.ruby.rails, .text.html.erb, .text.haml, .source.js.rails':
      'erb_percentage_block':
        'prefix': '%',
        'body': '<% $1 %>'

is not working if shadow DOM is enabled. Everything is fine if I disable shadow DOM
Do I need to change my syntax for supporting shadow DOM in snippets? I did a search on the documentation of the latest update but didn't find any info about it. Thanks!

**Comment by maxbrunsfeld** [comment]
I can't reproduce this. I tried this snippet in `Ruby on Rails`, `HTML (Ruby - ERB)`, `Ruby HAML`, and `Ruby on Rails (RJS)` and it worked in all cases.

Is this happening to you in safe mode? Are you using the latest version of Atom (v0.170)?

**Comment by sangregoriopaolo** [comment]
Hi @maxbrunsfeld , thanks for your answer! Actually I found out that seems like Emmet plugin is messing up a lot after the last Atom update, because if I disable it I have no issues at all.
The issues with snippets and keyboard shortcuts happened really in odd cases, without any logic. Sometimes the keybinding works, some other times it doesn't. Looking in the binding resolver, somethimes emmet got called first with a binding, and some other times it doesn't, with the same binding.
