### ISSUE TITLE
Auto-Indentation misbehaviour on JavaScript

### ISSUE THREAD

**Issue by ysndr** [atom/atom#4983]
I get a weird problem when applying auto-indentation to following code. When calling a function with a callback and finally the closing bracket in a new line everything from the closing bracket on get indented incorrectly.

I think Atom reduces the indentation when the callback's closing curly bracket closes. 
JSBeautify indents the callback by one to make it clearer.

I've come across this problem looking into [atom-jshint](https://github.com/Joezo/atom-jshint/blob/master/lib/atom-jshint.js#L16-L33) where it is indented correctly.

Atom version:0.169.0
OS: Win7

The behaviour I would expect based on JSBeautify:

``` js
function outer(){

    fnWithCallback('someLongAttributeikeAnEventString', 
        function(event,editor) { // new line 
            // some code
        }
    );
    anoterFunction();
} 
```

Atom's behavior:

``` js
function outer(){

    fnWithCallback('someLongAttributeikeAnEventString', 
    function(event,editor) { // new line 
        // some code
    }
); // uncorrectly indented
anotherFunction();// uncorrectly indented too
}
```

Bracket's (not really better) behaviour:

``` js
function outer(){

    fnWithCallback('someLongAttributeikeAnEventString', 
                   function(event,editor) {
        // some code
    }
                  );
    anoterFunction();
}
```

Sublimes behaviour:

``` js
function outer(){

    fnWithCallback('someLongAttributeikeAnEventString', 
    function(event,editor) { // new line 
        // some code
    }
    );
    anoterFunction();
}
```

**Comment by benogle** [comment]
This might be an issue with the https://github.com/atom/language-javascript regexes. @kevinsawicki ?

**Comment by connor4312** [comment]
I'm also having issues using the latest build on Windows. This is the indentation behaviour:

![](http://puu.sh/erFzl/fb9348ec5b.png)

I have never seen anyone actually code like this (thankfully)!

**Comment by AgentME** [comment]
@connor4312 That's reported here: https://github.com/atom/language-javascript/issues/77

**Comment by connor4312** [comment]
Ah, okay, sorry. Just hopping in, not yet too familar with Atom's systems :)

**Comment by muppetjones** [comment]
Ensuring cross-linkage: [here](https://github.com/atom/atom/issues/6655)

**Comment by chfritz** [comment]
Unfortunately, my fix for this (https://github.com/atom/atom/pull/10384) was never really given a chance. So for now I recommend using my package (https://atom.io/packages/sane-indentation) which monkey-patched the indentation logic in atom.io.
