### ISSUE TITLE
Uncaught Error: getaddrinfo ENOTFOUND avatars2.githubusercontent.com

### ISSUE THREAD

**Issue by FELS-Zak** [atom/atom#4986]
[Enter steps to reproduce below:]

1. Atom was open - then Clicked the update and restart option. 
2. It did it's thing, then restarted. 
3.Clicked on preferences
4.Clicked on packages. 

That was it.

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: getaddrinfo ENOTFOUND avatars2.githubusercontent.com

```
At stream.js:94

Error: getaddrinfo ENOTFOUND avatars2.githubusercontent.com
  at errnoException (dns.js:41:10)
  at Object.onlookup [as oncomplete] (dns.js:91:26)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "editor": {
    "fontSize": 14,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.12.0
autocomplete-plus, v0.21.0
color-picker, v1.2.4
inline-autocomplete, v0.3.2
language-jade, v0.3.0
linter, v0.7.3
open-last-project, v0.1.1
project-manager, v1.10.0
seti-syntax, v0.1.7
seti-ui, v0.3.6
slash-closer, v0.7.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/settings-view/commit/3fe0db5dc1c7db9f936b506a126d689057a24e0d
