### ISSUE TITLE
.invisible-character doesn't seem to work in user stylesheet

### ISSUE THREAD

**Issue by kyoh86** [atom/atom#4988]
![styles_less](https://cloud.githubusercontent.com/assets/5582459/5695098/864e050a-99d3-11e4-81a9-c8d0d70ee591.png)

**Comment by lee-dohm** [comment]
If you change the outermost `.editor` to `.editor, atom-text-editor::shadow`, it should work. Let us know if that does not work for you.

See:

* http://blog.atom.io/2014/11/18/avoiding-style-pollution-with-the-shadow-dom.html
* https://atom.io/docs/v0.169.0/upgrading/upgrading-your-ui-theme

**Comment by mjaggard** [comment]
Also, you seem to have to reload atom when you first change the stylesheet but subsequent changes are picked up automagically.
