### ISSUE TITLE
Improve dev experience of 'React DevTools' message

### ISSUE THREAD

**Issue by DinisCruz** [atom/atom#4991]
At the moment every time the DevTools is opened the ```Download the React DevTools for a better development experience: ``` message is shown:

![image](https://cloud.githubusercontent.com/assets/656739/5695701/dfbb2f82-99a6-11e4-8b29-113fa229616a.png)

As can be seen on this thread https://discuss.atom.io/t/adding-chrome-devtools-react-extension-to-atom/10941/5 this can be quite annoying and at the moment there isn't an easy solution (or clean understanding of that are the advantages or installing that chrome extension)

My proposed solution is to either

a) allow that message to be ignored (once and for all)
b) allow for an easy install of that extension, since:
 * the link provided cannot be clicked from the DevTools
 * the page is for the chrome webstore https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi (i.e. not immediate relevant how that can be done on Atom)

**Comment by DinisCruz** [comment]
For reference this is what happens if that chrome webstore page is opened inside Atom

![image](https://cloud.githubusercontent.com/assets/656739/5695730/f8871ce6-99a7-11e4-9d5c-56fe37b59285.png)

But it doesn't seem to be possible to install chrome extensions from inside Atom

![image](https://cloud.githubusercontent.com/assets/656739/5695753/18a4f2a4-99a9-11e4-961e-54cb7e0e4ae7.png)

**Comment by mark-hahn** [comment]
I'm assuming you were using my web-browser package?  The pages shown there
are in an iframe.  So there isn't much communicating with the webkit.

**Comment by DinisCruz** [comment]
@mark-hahn I think I was using https://atom.io/packages/atom-browser-webview (which I believe is a variation of yours)

My point with showing those screenshots is that there isn't an easy way to add those react tools to Atom

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/atom/commit/d5e4f051be9f12e82af598bc9b104916e06a1bc9

**Comment by DinisCruz** [comment]
Cool, out of curiosity, how long until this ends up in a release?

Do you have a page that explains the Atom release workflow?

**Comment by kevinsawicki** [comment]
> Cool, out of curiosity, how long until this ends up in a release?

Should be out in the next couple hours

> Do you have a page that explains the Atom release workflow?

Not exactly, we essentially release at least once a week, usually more than that though, 3-4 times.

**Comment by DinisCruz** [comment]
Nice, and where can I find the CI integration workflow? 

I.e. is there a process where for example all tests must pass in a TravisCI (or similar) environment, before the code is considered 'release ready'?

**Comment by kevinsawicki** [comment]
> Nice, and where can I find the CI integration workflow?

Atom packages build using Travis, see https://github.com/atom/ci for more details.

> is there a process where for example all tests must pass in a TravisCI (or similar) environment, before the code is considered 'release ready'?

We use an internal build farm for builds of atom/atom. Each time a master build passes it uploads the build assets to a draft release on https://github.com/atom/atom/releases

Then we just push the Publish Release button on the release page when we want it deployed.

**Comment by DinisCruz** [comment]
Thanks for the great answer (just tweeted about it here https://twitter.com/DinisCruz/status/555098031998402561 )

**Comment by kevinsawicki** [comment]
:+1:
