### ISSUE TITLE
2 of 5 Settings View menu items do not open their intended views

### ISSUE THREAD

**Issue by steelbrain** [atom/atom#4993]
## Steps of Reproduction:
1. Download Atom v169 on Linux/Windows/Mac
2. Remove ~/.atom for a clean new life
3. Click on Packages-> Settings View -> Install Packages from the top bar --- wont work
4. Click on Packages-> Settings View -> Uninstall Packages from the top bar --- works
5. Click on Packages-> Settings View -> Install Themes from the top bar --- wont work
6. Click on Packages-> Settings View -> Uninstall Themes from the top bar --- works
6. Click on Packages-> Settings View -> Change Theme from the top bar --- works

**Comment by Moter8** [comment]
What happens when you try and open it?
What version of Atom are you using and what OS is it on?
Provide some repro steps please?

**Comment by steelbrain** [comment]
## Steps:
1. Download Atom v169 on Linux or Windows
2. Remove ~/.atom for a clean new life
3. Click on Packages-> Settings View -> Install Packages from the top bar --- wont work
4. Click on Packages-> Settings View -> Uninstall Packages from the top bar --- works
5. Click on Packages-> Settings View -> Install Themes from the top bar --- wont work
6. Click on Packages-> Settings View -> Uninstall Themes from the top bar --- works
6. Click on Packages-> Settings View -> Change Theme from the top bar --- works

**Comment by Moter8** [comment]
Well, I'd rather spell the issue as "2 of 5 Settings View entries don't open anything" :)

The repro steps clarified the issue.

:+1: Can repro on 0.169.0 Win10

**Comment by lee-dohm** [comment]
Made the title more clear. I can reproduce this on Atom v0.170.0-29f95b8 on Mac OS X 10.10.1. Repro steps:

1. Closed all running instances of Atom
1. `mv ~/.atom ~/.atom-backup`
1. Launch Atom
1. Click `Packages > Settings View > Install Packages` (or `Install Themes`)

**Expected:** Settings Install view should be displayed with the appropriate mode selector checked
**Actual:** Nothing happens

**Comment by thedaniel** [comment]
Thanks for the detailed report, I'll fix this up.
