### ISSUE TITLE
Open folder on linux will open a new window, even if first instance is untouched

### ISSUE THREAD

**Issue by m1ga** [atom/atom#4996]
Steps:
Open atom
File - Open folder
select folder
2nd instance of atom is opened

expected behavior: one window open with the new project (windows is doing it like this)

Fedora 21
Atom 0.170.0-29f95b8

**Comment by kevinsawicki** [comment]
Hmm, having trouble reproducing this on Fedora 20, this is what I'm seeing:

![fedora-open](https://cloud.githubusercontent.com/assets/671378/5731754/2c9491ae-9b3c-11e4-9b2c-f6d96b8bbc32.gif)

**Comment by m1ga** [comment]
I'm using kde perhaps thats the difference. Will record a gif later on

**Comment by telkomsel666** [comment]
#1

**Comment by m1ga** [comment]
![http://www.migaweb.de/atom.gif](http://www.migaweb.de/atom.gif)

**Comment by m1ga** [comment]
I still have this problem with todays atom :cry: a new .atom folder and safe-mode still produce this bug. Is there a way how I can find the problem? Can I debug something to see where it should open keep the existing window?

**Comment by m1ga** [comment]
trying to debug this issue because I'm still facing it.

Is atom-application.coffee the right place?

I've added some console.log messages:

~~~
  openPath: ({pathToOpen, pidToKillWhenClosed, newWindow, devMode, safeMode, apiPreviewMode, window}) ->
    console.log("OPEN PATH");
~~~

~~~
openPaths: ({pathsToOpen, pidToKillWhenClosed, newWindow, devMode, safeMode, apiPreviewMode, windowDimensions, window}={}) ->
    pathsToOpen = (fs.normalize(pathToOpen) for pathToOpen in pathsToOpen)
    locationsToOpen = (@locationForPathToOpen(pathToOpen) for pathToOpen in pathsToOpen)

    console.log(pathToOpen + " dm: " + devMode + " sm: " + safeMode + " nw: " + newWindow+ " pid: "+pidToKillWhenClosed);
~~~

but they never show up

**Comment by m1ga** [comment]
Found out how I can get it to open in the existing window:

- open atom
- ctrl + shift + n (new window)
- open folder
- it will use the existing window!

so it looks like it will automatically flag the application as used when I start with step 1 (open atom) but when I create a new window inside atom it will use this window again when opening a folder (as it should)

**Comment by m1ga** [comment]
finally fixed in latest git (0.199.0-f1f8c3d)! Speeds up opening first folder so much!

**Comment by m1ga** [comment]
back to old (wrong) behavior in 0.200.0-6ca8e11 :(

**Comment by mymainmanbrown** [comment]
I just installed atom today, and I'm seeing this on Linux, too.  The easiest way I have found to get multiple folders into the same project is to right click on the tree and choose "Add Project Folder".  I think that opening a folder or dragging a folder into a window should open it in that window, not in a new one.
