### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Volumes/Media/Users/Mark/Developer/Wedding-Site/project.json'

### ISSUE THREAD

**Issue by MarkOnFire** [atom/atom#4999]
[Enter steps to reproduce below:]

1. Opened directory tree with several files in tabs.
2. Error occurred.

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Volumes/Media/Users/Mark/Developer/Wedding-Site/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Volumes/Media/Users/Mark/Developer/Wedding-Site/project.json'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "whitespace"
    ],
    "themes": [
      "atom-light-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 10,
    "softWrapAtPreferredLineLength": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.2.6
save-session, v0.11.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update `save-session` to the latest version.
