### ISSUE TITLE
"spawn UNKNOWN" error, and no Packages or Themes loaded at Atom Settings (Windows 7, atom version: 0.169)

### ISSUE THREAD

**Issue by Leonard1980** [atom/atom#5000]
The "spawn UNKNOWN" error appears on:
- Settings / Updates --> Available updates 
- Settings / Install --> Featured Packages

When I click on "Show output…" nothing shows.

Also it does not show any package in Settings / Packages on Installed Packages, and it shows only "Loading packages..." on Community, Core and Development Packages no matter how long I wait.
In Settings / Themes ---> Community Themes, it shows also "Loading themes..." no matter how long I wait.

I had an old atom version installed with Chocolatey, which I uninstalled before installing the new version with the Windows Installer.

**Comment by kevinsawicki** [comment]
Can you open the dev tools View > Developer menu and run `atom.packages.getApmPath()` from the Console tab?

That should output a path, can you try running that path from a command prompt and verify it executes correctly?

**Comment by Leonard1980** [comment]
Hi! Thanks for the reply.

The output is 

> "c:\Users\Leonard\AppData\Local\atom\app-0.169.0\resources\app\apm\node_modules\atom-package-manager\bin\apm.cmd"

and it executes correctly.

If it helps, I run the above command with "--version" parameter and it displays:

>apm  0.117.0
>npm  1.4.4
>node 0.10.33
>python
>git 1.9.5.msysgit.0
>visual studio

The same thing displays when I run just "apm --version" from anywhere, without the path.

**Comment by basarat** [comment]
This seems related to : https://github.com/atom/atom/issues/2887

A simple code segment in any package:

```js
var childprocess = require('child_process');
try{
    childprocess.spawn(__dirname + '/../worker/process.js');
}
catch(ex){
    console.log(ex);
}
```

Will result in this error as shown : 

![image](https://cloud.githubusercontent.com/assets/874898/5996348/d2058c28-aafb-11e4-8faa-bc70b4266725.png)

**Comment by Leonard1980** [comment]
I uninstalled Atom, and perfomed a program leftovers cleanup with an utility, and reinstalled. Nothing changed, and the error stayed. I guess i will stay with Brackets until this is solved.
Please, tell me what more information do you need, because I really want atom to work.

**Comment by basarat** [comment]
Can you uninstall all packages. Delete the packages directory. Happened to me when I incorrectly called spawn in MY atom package.

**Comment by Leonard1980** [comment]
I uninstalled all packages, one by one, via apm commandline, I deleted the contents of the "AppData\Local\atom\packages" folder, after that I uninstalled & cleaned (deleted every atom folder - from "AppData\Local and from "AppData\Roaming) & reinstalled atom, but with the same result.

**Comment by Leonard1980** [comment]
I also opened "developer tools" and copied the output:

> Failed to activate package named 'metrics' Error: spawn UNKNOWN
>  at exports._errnoException (util.js:753:11)
>  at ChildProcess.spawn (child_process.js:1160:11)
>  at exports.spawn (child_process.js:993:9)
>  at Object.exports.execFile (child_process.js:687:15)
>  at Object.module.(anonymous function) [as execFile] (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\atom\common\lib\asar.js:448:20)
>  at exports.exec (child_process.js:655:18)
>  at Object.getMac (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\node_modules\metrics\node_modules\getmac\out\lib\getmac.js:44:14)
>  at Object.module.exports.createUserId (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\node_modules\metrics\lib\metrics.js:101:32)
>  at Object.module.exports.ensureUserInfo (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\node_modules\metrics\lib\metrics.js:92:21)
>  at Object.module.exports.activate (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\node_modules\metrics\lib\metrics.js:19:19)
>  at Package.module.exports.Package.activateNow (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\package.js:235:27)
>  at C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\package.js:221:28
>  at Package.module.exports.Package.measure (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\package.js:167:15)
>  at Package.module.exports.Package.activate (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\package.js:215:14)
>  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\package-manager.js:464:21)
>  at C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\package-manager.js:445:29
>  at Config.module.exports.Config.transact (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\config.js:350:16)
>  at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\package-manager.js:439:19)
>  at PackageManager.module.exports.PackageManager.activate (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\package-manager.js:422:46)
>  at Atom.module.exports.Atom.startEditorWindow (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\atom.js:611:21)
>  at Object.<anonymous> (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\window-bootstrap.js:12:8)
>  at Object.<anonymous> (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\window-bootstrap.js:23:4)
>  at Module._compile (module.js:475:26)
>  at Object.loadFile [as .js] (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\src\6to5.js:140:21)
>  at Module.load (C:\Users\Leonard\AppData\Local\atom\app-0.177.0\resources\app\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
>  at Function.Module._load (module.js:325:12)
>  at Module.require (module.js:380:17)
>  at require (module.js:399:17)
>  at window.onload (file:///C:/Users/Leonard/AppData/Local/atom/app-0.177.0/resources/app/static/index.js:57:25)
>
> index.js:62 Window load time: 5517ms

Now I have no package installed. 
When I run the  command "apm list -installed" it returns `(empty)`.
When I run "apm --version", now it returns:
>apm  0.134.0
>npm  2.3.0
>node 0.10.35
>python
>git 1.9.5.msysgit.0
>visual studio

I hope this information helps.

**Comment by benogle** [comment]
Looks like the metrics package should have better error handling.

**Comment by benogle** [comment]
Sorry about that. This is a crappy bug. It'll be out in the next version of atom.

**Comment by Leonard1980** [comment]
Thanks. No need to be sorry. I hope this will solve my issue.

**Comment by Mottie** [comment]
I'm seeing this issue when I type in `apm --version`.

```
$ atom --version

Atom    : 1.19.0-beta3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm --version
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at EventEmitter.<anonymous> (C:\Users\Me\AppData\Local\atom\app-1.19.0-beta3\resources\app\apm\lib\apm-cli.js:150:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

If I follow the instructions above, getting the path and adding `--version` to the end, I see this:

```
$ /c/Users/Me/AppData/Local/atom/app-1.19.0-beta3/resources/app/apm/bin/apm.cmd --version
apm  1.18.2
npm  3.10.10
node 6.9.5 x64
python 3.6.1
git 2.13.0.windows.1
visual studio 2015
```

I haven't tried uninstalling and reinstalling Atom yet...
