### ISSUE TITLE
Standalone TextEditor 

### ISSUE THREAD

**Issue by mizchi** [atom/atom#5001]
I tried to extract only text-editor component but it's difficult because of some native module and global properties(mainly atom.config). My purpose is to use instead of CodeMirror or use on other atom-shell project.

As far as I read, essential native module to work is only oniguruma for TextEditor,  and it wil be able to replace by pure RegExp (of cource I know it has speed problem}.

Atom can support this in the future? If anyone allow it I will refactor so but it looks difficult to touch many files under many pull requests...

My working log is here(dirty commits)
https://github.com/mizchi-sandbox/standalone-atom-editor

**Comment by maxbrunsfeld** [comment]
@mizchi We would like to do this, but as you have mentioned, it would be a very big change. I would not recommend submitting a PR to do this right now. Unfortunately, it will be probably be many several months before we do anything along these lines. Sorry.

**Comment by abe33** [comment]
Sorry to say that you won't be able to replace oniguruma  with JS Regexp, if a grammar use a positive or negative lookbehind, options blocks or back references for instance you won't be able to convert these grammars to JS.
You'll also fail short when it'll come to managing events as `event-kit` rely on `WeakMap`, and you'll have trouble making the view works as it use custom elements and shadow DOM (both are still to consider as experimental feature: http://caniuse.com/#feat=shadowdom)

**Comment by parisk** [comment]
Hello. Are there any updates or plans on this? It would be great if the editor component of Atom could be used also outside the context of native apps.

**Comment by benogle** [comment]
No updates. It is something that would be nice, but is a lot of work and wont really net us much at this time.
