### ISSUE TITLE
Enter/Return Ignored

### ISSUE THREAD

**Issue by jdcauley** [atom/atom#5003]
I can't use my Enter/Return key in Atom.

OSX Yosemite
Version 10.10.1

MacBook Pro (13-inch, Mid 2012)
Processor 2.9 GHz Intel Core i7
Memory 8GB

**Comment by vesparny** [comment]
try to disable emmet if you have it installed

**Comment by maxbrunsfeld** [comment]
Yeah, this has come up a lot in relation to the [emmet package](https://github.com/emmetio/emmet-atom). Do you have that installed? If not, can you report your installed packages (`apm list`) and whether or not this occurs in safe mode?

**Comment by benogle** [comment]
See https://github.com/emmetio/emmet-atom/issues/186

**Comment by jdcauley** [comment]
Confirm this is an issue with Emmet
