### ISSUE TITLE
Version - Help -> Release Notes

### ISSUE THREAD

**Issue by picibucor** [atom/atom#5005]
Hi all,

Here's what do I see by clicking on : Help -> Release Notes

![release_notes](https://cloud.githubusercontent.com/assets/1676457/5704205/89651f2a-9a6f-11e4-8e8f-8008b315c535.png)

And here's what my (Win 7) control Panel says:
![win_version](https://cloud.githubusercontent.com/assets/1676457/5704210/91ed6d0a-9a6f-11e4-9e36-67076fc90af8.png)

I suppose the versions should be the same....

**Comment by Moter8** [comment]
I hope you clicked on "Restart and update" some time? If yes, that's a different bug then I guess

**Comment by picibucor** [comment]
Double-checked:

-> clicked on "Restart and update"
-> restarts
-> nothing changed

**Comment by Moter8** [comment]
Mind opening a Explorer window and copying in `%localappdata%/atom/app-0.169.0` and opening atom.exe from there? (I'm not sure if this would be helpful though)

**Comment by picibucor** [comment]
Same result: 0.150.0

**Comment by AluisioASG** [comment]
#3757 strikes again?

**Comment by picibucor** [comment]
yes, it's the same...

**Comment by picibucor** [comment]
I close this, and I'll wait till #3757 will be closed...

**Comment by Moter8** [comment]
@picibucor the bug there is already closed. Possibly comment there to reopen it, else your bug won't get fixed.

**Comment by picibucor** [comment]
oh, THX
