### ISSUE TITLE
No newline character after running my code

### ISSUE THREAD

**Issue by picibucor** [atom/atom#5006]
Hi all,

after running my (python) code in Atom I cannot write a NewLine character. 
Basically as I press the "Enter" key and nothing happens. 
Before running the code there was no problem...

Atom-version: most probably 0.16.9  (see: #5005) 
OS: Win 7

installed packages:
ask-stack@0.1.0
atom-alignment@0.9.3
atom-beautify@0.21.2
atom-bitcoin@0.6.0
atom-django@0.1.0
atom-jinja2@0.5.0
atom-runner@2.2.0
autocomplete-plus@1.1.0
change-case@0.4.0
color-picker@1.2.6
emmet@2.3.0
fancy-new-file@0.7.0
file-icons@1.4.4
highlight-css-color@1.3.0
highlight-line@0.9.2
jshint@1.1.4
minimap@3.5.4
minimap-color-highlight@3.1.0
minimap-find-and-replace@3.1.0
minimap-selection@3.1.1
open-last-project@0.1.1
project-colorize@0.1.0
task-list@0.6.0
web-browser@0.2.3

**Comment by 50Wliu** [comment]
Disable emmet for now.

**Comment by picibucor** [comment]
It worked. :+1:  THX :)

**Comment by picibucor** [comment]
Should I close this issue?

**Comment by 50Wliu** [comment]
Yup :).

**Comment by maxbrunsfeld** [comment]
Thanks @50Wliu.
