### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/lenikirilov/project.json'

### ISSUE THREAD

**Issue by lenikirilov-taulia** [atom/atom#5011]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.166.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/lenikirilov/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/lenikirilov/project.json'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "editor": {
    "fontSize": 13,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
save-session, v0.11.2

# Dev
No dev packages
```

**Comment by benogle** [comment]
Please upgrade save-session to 11.3
