### ISSUE TITLE
A little too heavy-weighted?

### ISSUE THREAD

**Issue by hyiltiz** [atom/atom#5012]
I checked this issue list and it seems it is not a duplicate. I suppose this could be considered an enhancement request.

Atom is too heavy-weighted. Given all those features such as package management, even some support like a web-browser way, it should be alright. But taking the official release as example, they are approximately 100 Mb, which is almost the size of Firefox browser. I see for windows compilation, chromiumcontent.dll is the single biggest file, along with others. 

Is there any way or work goign on to slim down Atom a little bit more?

**Comment by thedaniel** [comment]
> Which is almost the size of Firefox browser

Atom is based on Chromium, and is has all the rendering and JS features of a web browser, with added node integration, so it will not likely ever have a significantly smaller disk footprint than a modern browser.

**Comment by svnpenn** [comment]
https://github.com/visualfc/liteide/issues/891

**Comment by svnpenn** [comment]
https://github.com/adobe/brackets/issues/14071

**Comment by svnpenn** [comment]
https://github.com/Komodo/KomodoEdit/issues/3438
