### ISSUE TITLE
Chocolatey Package out of date

### ISSUE THREAD

**Issue by gep13** [atom/atom#5016]
Am I right in saying that the chocolatey package for atom is maintained out of this repository?

I have noticed, via disqus comments:

https://chocolatey.org/packages/Atom#comment-1787917190

That the chocolatey package for Atom is quite a bit out of date.  Would it be possible to get this package updated?

**Comment by kevinsawicki** [comment]
A new installer was added for Atom that replaces the functionality that the Chocolatey scripts contained, http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html

We are switching the Chocolatey package to use this new installer but it is waiting on an issue in the installed library to be addressed, see https://github.com/atom/chocolatey/pull/35 for more details.

**Comment by gep13** [comment]
:+1: thanks for the information!
