### ISSUE TITLE
Snippet with current date

### ISSUE THREAD

**Issue by pathawks** [atom/atom#5018]
Is it possible to have a snippet insert the current date?

I was hoping to use the [date](https://atom.io/packages/date) package to do this, but it would seem that this is currently not possible.

laktak/atom-date#1

**Comment by mark-hahn** [comment]
I put in a pull request to snippets months ago that does this and much more
but so far I've gotten no response.

**Comment by kevinsawicki** [comment]
> so far I've gotten no response.

Sorry, I didn't know that PR was ready for review, it looked like the specs were failing, https://travis-ci.org/atom/snippets/builds/42705297

**Comment by mark-hahn** [comment]
>  I didn't know that PR was ready for review

That was my first PR.  Is there something I should have done to mark it as
ready?

> it looked like the specs were failing,

They worked for me when I submitted it.  If this is something you want then
I'll go in and fix it.

**Comment by kevinsawicki** [comment]
>  Is there something I should have done to mark it as
ready?

Yeah, usually PRs will failing specs on CI aren't looked at that since the assumption is they aren't ready yet.

**Comment by kevinsawicki** [comment]
This issue seems pretty similar to https://github.com/atom/snippets/issues/33 so I'm going to close it out here.
