### ISSUE TITLE
Umlaute not displayed correctly

### ISSUE THREAD

**Issue by Prior99** [atom/atom#5024]
Atom is currently having issues with displaying umlaute (äüö).
When an umlaut character is typed or pasted it appears until the end of the line.

![screenshot - 011315 - 12 50 26](https://cloud.githubusercontent.com/assets/1491574/5720388/c0aaee9c-9b23-11e4-81f5-a0261557cb28.png)

When it is removed, everything looks just fine:

![screenshot - 011315 - 12 51 54](https://cloud.githubusercontent.com/assets/1491574/5720387/be19a90c-9b23-11e4-8c23-45bb4fc14037.png)

It also seem to be related to syntax highlighting, when selecting "Plain Text", everything is fine:

![screenshot - 011315 - 12 52 10](https://cloud.githubusercontent.com/assets/1491574/5720385/bbe8efee-9b23-11e4-9185-d75cd153e118.png)

Issue found on Arch Linux, build 0.171.0-296409d
Working without issues on Windows.

Document is UTF-8.

Tested with Syntax Highlighting for C, C++, Javascript, Latex and PHP. (Might affect other languages too, but I did not test it. I believe every language is affected.)

**Comment by mnquintana** [comment]
Can't reproduce in Atom 0.170.0, OS X Yosemite, with UTF-8 char encoding.

**Steps taken:**
1. Create new file (e.g. File > New File)
2. Change syntax to C, C++, JS, and PHP
3. Type umlauts
4. Try copying and pasting umlauted U's

(Btw, did you build from master? 0.171.0 hasn't been tagged yet)

I'll check on my Ubuntu later today to see if it's a general Linux issue. (Maybe it's a 0.171.0-specific issue though?)

**Comment by Prior99** [comment]
Yes, I built from master. Give me some time to test other releases too.

**Comment by mnquintana** [comment]
Hmmm, can't reproduce on Ubuntu 14.04 LTS either. What's your keyboard layout?

**Comment by postcasio** [comment]
@Prior99 can you upload a file demonstrating the issue somewhere?

**Comment by Prior99** [comment]
@postcasio https://cronosx.de/share/download.php?id=8d23cf6c86e834a7aa6eded54c26ce2bb2e74903538c61bdd5d2197997ab2f72

The file looks like this:
![screenshot - 011415 - 08 48 52](https://cloud.githubusercontent.com/assets/1491574/5735693/5a6c6a00-9bca-11e4-8986-93572a535dac.png)

**Comment by Prior99** [comment]
@mnquintana 

    [fg716463@rz-e4310 cluster]$ locale
    locale: Cannot set LC_CTYPE to default locale: No such file or directory
    locale: Cannot set LC_MESSAGES to default locale: No such file or directory
    locale: Cannot set LC_ALL to default locale: No such file or directory
    LANG=en_US.UTF-8
    LC_CTYPE="en_US.UTF-8"
    LC_NUMERIC="en_US.UTF-8"
    LC_TIME="en_US.UTF-8"
    LC_COLLATE="en_US.UTF-8"
    LC_MONETARY="en_US.UTF-8"
    LC_MESSAGES="en_US.UTF-8"
    LC_PAPER="en_US.UTF-8"
    LC_NAME="en_US.UTF-8"
    LC_ADDRESS="en_US.UTF-8"
    LC_TELEPHONE="en_US.UTF-8"
    LC_MEASUREMENT="en_US.UTF-8"
    LC_IDENTIFICATION="en_US.UTF-8"
    LC_ALL=
    [fg716463@rz-e4310 cluster]$ localectl
       System Locale: LANG=en_US.UTF-8
           VC Keymap: de-latin1-nodeadkeys
          X11 Layout: n/a

Maybe the issue is related to me not having set LC_ALL?
But this should not affect Atom in such way.

**Comment by Prior99** [comment]
**Update:** I tested this on a second machine, also running arch linux and can not reproduce it there.
This seems to be related to a misconfiguration on the first machine or version mismatches.

The machine it works on:

	[prior@cronosl ~]$ locale
	LANG=en_US.UTF-8
	LC_CTYPE="en_US.UTF-8"
	LC_NUMERIC="en_US.UTF-8"
	LC_TIME="en_US.UTF-8"
	LC_COLLATE=en_US.UTF-8
	LC_MONETARY="en_US.UTF-8"
	LC_MESSAGES="en_US.UTF-8"
	LC_PAPER="en_US.UTF-8"
	LC_NAME="en_US.UTF-8"
	LC_ADDRESS="en_US.UTF-8"
	LC_TELEPHONE="en_US.UTF-8"
	LC_MEASUREMENT="en_US.UTF-8"
	LC_IDENTIFICATION="en_US.UTF-8"
	LC_ALL=
	[prior@cronosl ~]$ locale
	locale      localectl   localedef   locale-gen  
	[prior@cronosl ~]$ localectl 
	   System Locale: LANG=en_US.UTF-8
	       VC Keymap: de-latin1
	      X11 Layout: n/a
	[prior@cronosl ~]$ uname -a
	Linux cronosl 3.17.3-1-ARCH #1 SMP PREEMPT Fri Nov 14 23:13:48 CET 2014 x86_64 GNU/Linux
	[prior@cronosl ~]$ atom -v
	0.124.0-024d7f8
The machine this bug occurs on:

	[fg716463@rz-e4310 cluster]$ locale
	locale: Cannot set LC_CTYPE to default locale: No such file or directory
	locale: Cannot set LC_MESSAGES to default locale: No such file or directory
	locale: Cannot set LC_ALL to default locale: No such file or directory
	LANG=en_US.UTF-8
	LC_CTYPE="en_US.UTF-8"
	LC_NUMERIC="en_US.UTF-8"
	LC_TIME="en_US.UTF-8"
	LC_COLLATE="en_US.UTF-8"
	LC_MONETARY="en_US.UTF-8"
	LC_MESSAGES="en_US.UTF-8"
	LC_PAPER="en_US.UTF-8"
	LC_NAME="en_US.UTF-8"
	LC_ADDRESS="en_US.UTF-8"
	LC_TELEPHONE="en_US.UTF-8"
	LC_MEASUREMENT="en_US.UTF-8"
	LC_IDENTIFICATION="en_US.UTF-8"
	LC_ALL=
	[fg716463@rz-e4310 cluster]$ localectl
	System Locale: LANG=en_US.UTF-8
	VC Keymap: de-latin1-nodeadkeys
	X11 Layout: n/a
	[fg716463@rz-e4310 ~]$ uname -a
	Linux rz-e4310 3.17.4-1-ARCH #1 SMP PREEMPT Fri Nov 21 21:14:42 CET 2014 x86_64 GNU/Linux
	[fg716463@rz-e4310 ~]$ atom -v
	0.170.0-b39cee3

Let me update the second machine to the latest versions of atom and compare the issue again.

**Comment by Prior99** [comment]
**Update:**
Both machines updated to atom 0.172.0-366ded2 without effect.

**Comment by Prior99** [comment]
**Update:**
Fixing the corrupted locales on the machine the issue occured on fixed the issue. The file is displayed correctly now.

I would however not to close this issue but suggest to display a warning message when corrupted locales are detected.

**Comment by mnquintana** [comment]
@Prior99 Nice work! It definitely seems to me like Atom should display a warning notification when corrupted locales are detected, but it might be better to close this one and open a new issue just for that (to increase visibility / relevance for the core team).

**Comment by Prior99** [comment]
Opened new issue #5073 and closing this issue accordingly.
