### ISSUE TITLE
Cursor blinking does not respect system settings

### ISSUE THREAD

**Issue by renkun-ken** [atom/atom#5029]
I'm using Atom 0.169.0 under Windows 8.1. My system settings is not to blink the cursor. However, in Atom this setting is not respected. Would it be possible for Atom to respect the system settings on cursor blinking?

**Comment by kevinsawicki** [comment]
System setting support is not likely to be added in the near term.

You can however style the cursor using your local stylesheet at `~/.atom/styles.less`.
