### ISSUE TITLE
Show the contents without open the file at the Find Files feature.

### ISSUE THREAD

**Issue by joowh85** [atom/atom#5033]
Show the contents without open the file at the Find Files feature.

I think you'll hard to understand my issue..  
I've video for you. here is the link.
Very short video (:

http://www.youtube.com/watch?v=OHTfCr9aPfE

Do you have a plan for support this feature?

**Comment by kevinsawicki** [comment]
Yup, this is planned, you can subscribe to https://github.com/atom/atom/issues/3683 to get updates.
