### ISSUE TITLE
Linux build steps should recommend unzip master.zip instead of cloning from repo

### ISSUE THREAD

**Issue by horvan** [atom/atom#5036]
I actually cloning atoms repository for building atom on ubuntu. I ran ubuntu in a virtual box and the cloning process runs for about 2 hours now. perhaps you should recommend to wget and unzip the master.zip, because this is far more quicker.

**Comment by maxbrunsfeld** [comment]
Maybe we should recommend `git clone --depth=1` in these docs, since the repo historically was so large?

**Comment by kevinsawicki** [comment]
> git clone --depth=1

I think this would usually prevent the latest tag from being checked out unless it is the most recent commit.
