### ISSUE TITLE
[ubuntu][multi-select][copy/paste]

### ISSUE THREAD

**Issue by aitboudad** [atom/atom#5039]
When I copy/paste multi-lines I noticed that it's paste only the first line but cut/paste work as expected

**Comment by kevinsawicki** [comment]
What version of ubuntu are you on?

Also, how are you pasting? `ctrl-v`, the Paste menu? Some other way?

**Comment by 50Wliu** [comment]
I just tried the following, which all worked as expected:
* Selecting multiple lines using the cursor, pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> and then <kbd>Ctrl</kbd>+<kbd>V</kbd>
* Selecting multiple lines using the cursor, right-clicking and selecting `Copy`, then right-clicking and selecting `Paste`
* Selecting multiple lines using the cursor, then pressing the middle mouse button
This was on Atom 0.169.0 on Ubuntu 14.10.

To add on to @kevinsawicki's comments:
* What version of Atom are you using?
* Can you reproduce this in safe mode (`atom --safe`)?

**Comment by aitboudad** [comment]
Hi, I just checked with safe mode (atom --safe) and it's work :),
but without safe mode the problem still persist in all case given by @50Wliu 

* atom version : 0.172.0
* ubuntu 14.10

**Comment by philipgiuliani** [comment]
If its working with safe mode, it means that the issue is caused by a package that you are using. Safe mode does not load your custom packages. Try to disable them one by one and you will found out which causes the issue.

**Comment by aitboudad** [comment]
@philipgiuliani  right :), I found the package https://atom.io/packages/clipboard-history
