### ISSUE TITLE
Font is blurry on retina screens

### ISSUE THREAD

**Issue by sdthornton** [atom/atom#5040]
Just updated to 0.172.0 from 0.166.0 and the entire app is now non-retina ready. I've added `-webkit-font-smoothing: antialiased;` which smooths the font, but it's still quite blurry and not retina ready.

![screen shot 2015-01-13 at 3 59 31 pm](https://cloud.githubusercontent.com/assets/1181184/5731837/3d441d66-9b3d-11e4-8da6-4310edea3d69.png)

![screen shot 2015-01-13 at 3 59 45 pm](https://cloud.githubusercontent.com/assets/1181184/5731840/4116301e-9b3d-11e4-8bf3-edaa75ae9a0f.png)

Looked through the existing issues and only found font issues concerning non-retina devices, but my apologies if this is a repeat.

**Comment by sdthornton** [comment]
The above theme is Neutron, but I've switched tried it with the default Atom themes as well.

**Comment by kevinsawicki** [comment]
Does changing this setting make any difference?

![screen shot 2015-01-13 at 4 03 27 pm](https://cloud.githubusercontent.com/assets/671378/5731871/c0455a0e-9b3d-11e4-9a9c-142ab21e371d.png)

**Comment by sdthornton** [comment]
No difference. But I actually was able to solve the problem. Ended up finding an already closed issue with the solution: https://github.com/atom/atom/issues/3430.

For some reason moving Atom into Applications caused the default OSX setting to be "Open in low resolution". It's a curious thing. Working beautifully again though.

My apologies for the duplication. Closing.

**Comment by yursha** [comment]
I had the same issue though OSX "Open in low resolution" was not checked as I installed Atom with `brew cask`. I fixed it with adding `-webkit-font-smoothing: antialiased;` to my theme.

**Comment by Jpoliachik** [comment]
Had the same issue when using Atom on an external display. It became blurry when I unplugged the monitor and switched to the Retina display on my Macbook. A quit and re-open fixed it for me.
