### ISSUE TITLE
pac proxy didn't work well，suddenly appear on yesterday

### ISSUE THREAD

**Issue by Cifer-Y** [atom/atom#5043]
atom online update and install package are timeout, before yesterday, global pac proxy fine with atom, 
but from yesterday, when using global pac proxy, atom was timeout for update, so I try to set the
pac proxy in ~/.atom/.apmrc, still bad... so sad :(

**Atom Version**: 0.170.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: getaddrinfo ENOTFOUND avatars1.githubusercontent.com

```
At stream.js:94

Error: getaddrinfo ENOTFOUND avatars1.githubusercontent.com
  at errnoException (dns.js:41:10)
  at Object.onlookup [as oncomplete] (dns.js:91:26)

```

### Commands

```
     -1:27.6 settings-view:open (atom-text-editor.editor)
     -0:00.0 symbols-view:toggle-file-symbols (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "emmet",
      "atomic-emacs",
      "linter-rubocop",
      "linter-ruby",
      "linter-erb",
      "linter",
      "vim-mode"
    ],
    "destroyEmptyPanes": false
  },
  "editor": {
    "fontFamily": "Monaco",
    "fontSize": 15,
    "showIndentGuide": true,
    "invisibles": {},
    "zoomFontWhenCtrlScrolling": true
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.3
autoclose-html, v0.13.0
autocomplete-plus, v1.1.0
autocomplete-snippets, v0.3.2
file-icons, v1.4.4
language-elixir, v0.3.3
language-erlang, v2.0.0
language-haml, v0.14.0
language-haskell, v1.0.0
linter-hlint, v0.3.1
minimap, v3.5.4
pretty-json, v0.3.1

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Can you try upgrading to Atom 0.171 or later? I believe this was fixed by https://github.com/atom/settings-view/commit/3fe0db5dc1c7db9f936b506a126d689057a24e0d

**Comment by Cifer-Y** [comment]
Still bad...now my atom version is 0.172....  the error is `Request for package information failed: tunneling socket could not be established, cause=Parse Error`, the pac proxy is working well for everything except atom, so confused...

**Comment by kevinsawicki** [comment]
Can you post the stack trace for the new error?

**Comment by Cifer-Y** [comment]
But I am not sure that is the atom's fault, because my sublime text also suddenly tear down...... ok, wait a minuite

**Comment by Cifer-Y** [comment]
![untitled - atom atom today at 09 17 30](https://cloud.githubusercontent.com/assets/4470516/5732524/39c30594-9bce-11e4-94e1-811bba70d698.png)
There is no stack trace on new version, just an connection error

**Comment by kevinsawicki** [comment]
Okay, I'm going to close this out since the original uncaught error with avatars has been fixed, this is a different issue.

Would you mind opening an issue on the atom/apm repo with details about this new error?

You can try `apm install --verbose color-picker` from the command line to get more information.

**Comment by Cifer-Y** [comment]
I tried `apm install --verbose color-picker` , it worked well... the color-picker package was installed successfully......... I am very confused... ok, I will open an issue on atom/apm
