### ISSUE TITLE
Paste without formatting/indentation

### ISSUE THREAD

**Issue by dmnd** [atom/atom#5046]
In #1407 @nathansobo wrote:

> I wonder if we should offer a non-normalized variant of paste, like alt-cmd-v.

Opening this issue to ask for the above.

Rationale: I leave auto indentation on, and it (mostly) does the right thing, but sometimes I am moving code around that has indentation rules more complicated than Atom can understand. I'd love to have a quick way to paste the "raw" text without having Atom try to indent it. Kind of like "paste without formatting" in a spreadsheet.

An example of complicated indentation might be a docstring, or PEP8-style indenting to opening parens in Python. Ideally Atom would understand all these rules and do the right thing, but right now I often find myself re-indenting things after Atom strips them during paste.

**Comment by 50Wliu** [comment]
:+1:.  On Windows and Linux the keybinding would be <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd>.

**Comment by mnquintana** [comment]
:+1: This is pretty much what I had configured in Sublime (`Cmd+Shift+V` for Macs of course :smiley:)

**Comment by bronson** [comment]
Totally agree.  Cmd-V should paste-and-reindent, Cmd-Shift-V paste verbatim.

I would like it if the editor pasted, and THEN indented, in two separate steps.  If I didn't like the reindenting, I could hit Undo once to get back the original text.  And if I didn't want to paste at all, I could hit Undo twice.

I think.

This seems discoverable and doesn't require settings/modes...  Any downsides?

**Comment by imbenclifford** [comment]
+1 I'd love this feature too. Would be a game changer for atom.

**Comment by jenius** [comment]
Would also really enjoy this feature!

**Comment by felixkempf** [comment]
This!

**Comment by jonathanphz** [comment]
Yeah I've been looking for this functionality too.

**Comment by Misterdjack** [comment]
Did we just become best friends? Yup! Wanna practice karate in the basement? Yup!  Wanna paste with formatting? Yup!

**Comment by klarkc** [comment]
Nice feature, having to switch off auto indent everytime I need plain paste is a pain

**Comment by jackson-sandland** [comment]
Can we get this feature? This is a time saver, and improves our efficiency while keeping us focused on more important lines of thought!

**Comment by Ben3eeE** [comment]
Closed via https://github.com/atom/atom/pull/15976
