### ISSUE TITLE
[win7] Atom opens another copy of itself

### ISSUE THREAD

**Issue by xlaywan** [atom/atom#5053]
When i open pinned atom from windows taskbar it's open another copy of itself.
![316 paintiago 1](https://cloud.githubusercontent.com/assets/9087446/5739095/c2498cf8-9c05-11e4-877f-c7a10a0a4325.png)
In 0.166 everything was good.

**Comment by 50Wliu** [comment]
What path is the pinned Atom pointing to?

**Comment by xlaywan** [comment]
`C:\Users\User\AppData\Local\atom\app-0.172.0\atom.exe`
The same path which opens.

**Comment by xlaywan** [comment]
After updating to version 0.174.0 bug disappeared. Issue can be closed.
