### ISSUE TITLE
"Exclude VCS Ignored Paths" not working

### ISSUE THREAD

**Issue by 7diracseas** [atom/atom#5054]
Would like to see if anyone else is getting this issue as well before I attempt to tackle the issue. Haven't contributed to this project yet so I'll probably be less efficient than someone else doing it.

**Environment**

OS: Mac OSX 10.10.1
Atom Version: 0.172.0

``*.pyc`` is in my ``.gitignore`` file and git properly ignores them.

![screen shot 2015-01-14 at 8 36 06 am](https://cloud.githubusercontent.com/assets/3121915/5739555/bc0ebf6c-9bc8-11e4-84c0-12c99091b0f4.png)

**Comment by 50Wliu** [comment]
Go to the Tree View settings where there's another option to disable VCS ignored paths from showing up in the tree view.

**Comment by jpstevens** [comment]
I have the same issue. The `Exclude VCS Ignored Paths` toggle does nothing; if there is a `.gitignore` present, then the ignored files will not show, regardless of the settings.

Any ideas why?

By default Atom used to just grey-out ignored files... Is this not the case anymore?

*Running Atom 0.170.0 on Mavericks.*

**Comment by 7diracseas** [comment]
@50Wliu's comment fixed it for me. Looks like the setting changed to be available in 2 places now - a separate place for the tree view.

**Comment by jpstevens** [comment]
Ahh yes, you are absolutely right. You are both brilliant, thank you.

FYI anyone else who stumbles on this, the issue is that Atom's tree-view is a package, so its settings are separate to the core settings of Atom.

To fix, go to `Packages > Tree View > Settings` then toggle `Hide VCS Ignored Files` off.

![image](https://cloud.githubusercontent.com/assets/6638657/5741913/3fe0cb4a-9c06-11e4-9eea-055fb3771fb0.png)

**Comment by warwickp** [comment]
Thanks @jpstevens this has been bugging me.

**Comment by enlacee** [comment]
today i have this problem, hmm, it's issues enough is enabled, **so i must be reopen this ISSUE?**

**Comment by rustanacexd** [comment]
same problem

**Comment by MartinMuzatko** [comment]
![image](https://cloud.githubusercontent.com/assets/2950505/18581051/214311e0-7bff-11e6-86db-f5d0bc674d1c.png)

Same problem here.
I ticked "Exclude VC Ignored Paths" and I still get the results in the fuzzy finder

**Comment by paddotk** [comment]
This issue still persists. When I search within my project (ctrl+shift+f), these files are being shown as search results. There are certain phrases I can now not look for, as 111.000 results make Atom crash every time.

**Comment by MaciejJanyska** [comment]
I've noticed the same problem.

**Comment by paddotk** [comment]
@MaciejJanyska Updating Atom seems to fix the problem, it seems that the 'regular' way of updating (through the terminal) doesn't actually update it right. Current version is v1.14.2.
As a sidenote, this version seems pretty unstable and prone to crashing, so take that into account before updating.
