### ISSUE TITLE
atom.exe location in windows

### ISSUE THREAD

**Issue by TheChymera** [atom/atom#5055]
I have just installed atom on Windows and would like to know where its executable is located - so that I can point other programs (e.g. Gitbash) to it. I have not selected anything specific during the installation wizard so I guess it should be at some standard location, which, however, I could not find in the documentation.

**Comment by lee-dohm** [comment]
Updated title to be more clear. I thought you were talking about font rendering :grinning:

Atom uses the Squirrel framework for installation and update. From the [Squirrel.Windows project](https://github.com/Squirrel/Squirrel.Windows):

> ...installs to the local user account (i.e. under %LocalAppData%)

I hope that helps :smile:

**Comment by kevinsawicki** [comment]
Yeah, there are two commands, `apm` and `atom` that will be in `%LocalAppData\atom\bin`

**Comment by georgejost** [comment]
Gees that's unnecessarily complicated. You have several installed binaries and you have to be psychic to find which one is the actual executable. (Not to mention, that the AppData directory is hidden by default.

**Comment by webspresso** [comment]
I echo these comments - just spent 15 mins looking for it in all the wrong places!

**Comment by thomascallahan** [comment]
Yes this is irritating. Every time it updates, shortcuts to it break, icons get duplicated, etc. Atom needs to install something in the standard application location in Windows that doesn't change with version updates. Several other programs I use do this (ITUNES!) and it's very annoying.

**Comment by muhammadabraham1982** [comment]
did you searched in the windows applications menu ?
