### ISSUE TITLE
hard to see cursor

### ISSUE THREAD

**Issue by muhasturk** [atom/atom#5057]
When I edit my file on Atom, cursor is hard to see on editor. What should I do?

**Comment by kevinsawicki** [comment]
Can you post a screenshot? What theme are you using?

**Comment by kevinsawicki** [comment]
You can style the cursor from your `~/.atom/styles.less` file as well.

```less
atom-text-editor::shadow {
  .cursor {
    border-color: red;
  }
}

**Comment by muhasturk** [comment]
I mean mouse cursor. Do you have and documentation for styles.less? I know how to write less, but I do not know what class names should I use.

**Comment by kevinsawicki** [comment]
Oh okay, thanks for the info, this sounds like https://github.com/atom/atom/issues/1654 

You might want to try this package: https://atom.io/packages/white-cursor
