### ISSUE TITLE
Atom installation/updating garbles %PATH%

### ISSUE THREAD

**Issue by renecrapts** [atom/atom#5063]
The character *é* in my user %PATH% environment variable gets garbled after installing Atom. It seems to happen after an auto-update as well.

Before installation:
```
C:\Users\René\AppData\Roaming\npm
```
After installation (actual):
```
C:\Users\Ren�\AppData\Roaming\npm;c:\Users\René\AppData\Local\atom\bin
```
Expected:
```
C:\Users\René\AppData\Roaming\npm;c:\Users\René\AppData\Local\atom\bin
```
Windows 7 SP1
Atom 0.172.0

**Comment by kevinsawicki** [comment]
I've added a check so it will no longer corrupt the path, we still need to find a better long term solution
