### ISSUE TITLE
Failed to load keymap.cson

### ISSUE THREAD

**Issue by angiolucci** [atom/atom#5071]
**Error Message:**
While attempting to open a whole folder content in atom, it shows an error message:
"Failed to load keymap.cson"

**How to reproduce:**
Just try to open atom (with or without a folder as argument), like:
`$ atom linux-3.18.2`  or `$ atom`

Then the (ugly) message below will be shown:
![screenshot](https://cloud.githubusercontent.com/assets/4237343/5753493/9675c594-9c71-11e4-862d-951620826e1e.png)

**Details:**
* Atom 0.172.0 , who is supposed to [fix an issue  with `.cson` files](https://atom.io/releases);
* Fedora Linux 20 (64bit);
* It should be related to [this](https://github.com/atom/atom/issues/5037#issuecomment-69951466).

**Comment by gau1991** [comment]
Same ugli message on Fedoa Linux 21 64bit with Atom 0.172.0

**Comment by mnquintana** [comment]
See https://github.com/atom/atom/issues/5037#issuecomment-69951466

There was an issue with the `.rpm` build that should be fixed in 0.173.0

**Comment by 50Wliu** [comment]
Fixed in 0.173.0, please update to that.
