### ISSUE TITLE
Windows installer shouldn't assume the install location

### ISSUE THREAD

**Issue by Jragonmiris** [atom/atom#5072]
While I admire the simplicity of the installer, it also globs it onto the C drive without asking. My C drive is a very small SSD, and while Atom isn't exactly a huge program, I'd prefer to have it on my HDD.

**Comment by batjko** [comment]
Check out #4859, of which this could be considered a duplicate.

Essentially the Squirrel framework being used does not currently support custom locations. It's weird and undesirable, but there you go.

However, you can use the zip version to put the application in any location you wish, as long as you don't care too much about the bells and whistles the installer gives you (context menu entries etc).

**Comment by 50Wliu** [comment]
Yeah, I'm going to close this as a duplicate.  You can open up an issue on [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) if you want.

**Comment by paulcbetts** [comment]
@Jragonmiris Do you know about `mklink /D`? You can use this to put folders anywhere they want but have them still think that they're on the SSD. In this case, you can definitely put `C:\Users\YOURNAME\AppData\Local\atom` on the HDD then Symlink to it, and everything will work (even updates will be fine)
