### ISSUE TITLE
Atom javascript error on windows 8.1

### ISSUE THREAD

**Issue by MiquelAdell** [atom/atom#5074]
HI, I'm trying to run atom 0.172.0 on windows 81.

It installed correctly but it does not launch.

I have atom and apm avaialable in the console (I can run atom -v f.ex.)

If I execute the program directly nothing happens. If I execute atom -s in the console I get the following error:

![capture](https://cloud.githubusercontent.com/assets/4996457/5754316/8c414d70-9c97-11e4-9c62-2f170c6a5ceb.PNG)

I have no packages installed. It's a completelly clean install.

I don't know if there are logs that could help debugging this.

the setup seemed to go well and I've got this in squirrelsetup.log

    Program: Starting Squirrel Updater: --download https://atom.io/api/updates
    Program: Fetching update information, downloading from https://atom.io/api/updates
    CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
    FileDownloader: Downloading url:

**Comment by batjko** [comment]
No idea.
I mean the path resolve error seems to indicate some issue with finding a location or file. But it's the standard path anyway and your username is not exactly containing unusual characters or anything...

Could it be a permissions thing? Do you use more than one user account or use custom permissions on any atom-related folders?

**Comment by hanoc** [comment]
I don't see anything wrong with my directories...
I've checked a little more and the error comes from that line:
        return path.resolve((_ref = args.executedFrom) != null ? _ref : process.cwd(), pathToOpen.toString());

Either 
    (_ref = args.executedFrom) != null ? _ref : process.cwd()
or 
    pathToOpen.toString()

seems not to be a string.
I guess that it's _ref but I don't know how to check it's contents. I tried with console and alert but it does not get outputed to anywhere I know how to look at.

If somebody could help me print some traces I'll gladly help to debug it.

**Comment by batjko** [comment]
I assume you've been opening atom without any parameters, right? I remember a while back there was an issue when passing any path or folder location to atom when launching. This is not that issue but it's a similar error.

**Comment by hanoc** [comment]
I've tried:

- opening atom on terminal by typing atom
    - no error, nor on the console neither as a popup but the program "does not launch"
- opening atom with a folder path
    - same as above
- opening  atom via double clicking in the app
    - same as above
- opening atom in the console just with "atom -s"
    - I got the popup of the screenshot on the first post.

**Comment by postcasio** [comment]
`atom -s` is for running specs, and expects a directory to load the specs from, which is why that error occurs. I assume you wanted to open in safe mode, which is `atom --safe`.

Can you try `atom -f` and see if anything is output to the terminal?

**Comment by hanoc** [comment]
Oh, my bad, thanks.

The outputs you requested:

    C:\Users\Miquel\AppData\Local>atom --safe

    C:\Users\Miquel\AppData\Local>[5640:0115/140827:INFO:CONSOLE(0)] C:\Users\Miquel\AppData\Local
    App load time: 203ms

    C:\Users\Miquel\AppData\Local>atom -f
    App load time: 161ms

I think atom was not running before the first command and it is now. I don't see any window and I'm not able to kill the program from the windows task manager with quite a lot of tries.

**Comment by mesosteros** [comment]
Same thing I get now

**Comment by kevinsawicki** [comment]
> (_ref = args.executedFrom) != null ? _ref : process.cwd()

Can you edit this line to log out the ref via a `console.log("HERE!!! " + _ref + " <<<< ")`, then completely quit Atom, and relaunch with `atom -f` and see what prints out

**Comment by kevinsawicki** [comment]
I believe this has been fixed by the linked commits, please comment if you still see this on Atom 1.0+
