### ISSUE TITLE
Suitify Atom CSS

### ISSUE THREAD

**Issue by vanesyan** [atom/atom#5075]
Let's make Atom CSS componentable.For this we can use BEM methodology or more powerful and maintainable [SUIT CSS](https://github.com/suitcss/suit) project by @necolas. It'll allow us to maintain CSS very-very easy.
Also it break compatibility, but You really don't worry about it, do you?

If You like it, please, let me know and I'll start to work on it. Thanks.

**Comment by simurai** [comment]
I would love to use SUIT, at least adapt it's [naming convention](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md). It's my favorite amongst all the BEM flavors. It would reduce selector nesting and help to bring specificity down.

That said, the API freeze for the 1.0 is very very close. Changing a lot CSS selectors would break all the community packages and themes that are already out there. Plus all the custom styling done in a user's `styles.less` file.

So I'm afraid I'll have to close this issue again. But for a `2.0` release it's definitely something to consider.

ps. where is the `2.0` label. :smile:

**Comment by vanesyan** [comment]
Okay :( But I always open to helping you guys with building awesome Atom.

**Comment by simurai** [comment]
:+1: Good to hear and thanks for your suggestion.
