### ISSUE TITLE
Master branch compilation error.

### ISSUE THREAD

**Issue by joowh85** [atom/atom#5077]
I usually use master branch because I want receive latest fastest.
But today, It has lots errors. So I rollback it.

Please check and test before commit on master.

Warning and errors.

../node_modules/native-mate/vendor/base-minimal/src/base/bind.h:499:18: warning: typedef ‘p7_is_refcounted_type_and_needs_scoped_refptr’ locally defined but not used [-Wunused-local-typedefs]

Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/usr/local/src/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:230:14)

**Comment by batjko** [comment]
Well be aware that the master branch is not the official live version! It's fluid and often breaks momentarily before being fixed shortly afterward.

The official releases are what you can expect have been tested more thoroughly.

**Comment by maxbrunsfeld** [comment]
@joowh85, yeah there is a build warning on our master branch, but there are no errors. The error you reported is not a compilation error; a download failed. This might have been a temporary server outage.
