### ISSUE TITLE
'Search in Directory' not showing results

### ISSUE THREAD

**Issue by filipesilva** [atom/atom#5082]
Sometimes 'Search in Directory' will not show results. It seems to happen mostly in directories with more than a few files, but I cannot pinpoint the volume needed. 

My system is Win7, Atom 0.172.0, but I've seen it happen in previous versions.

Here's a gif it it happening while searching for a word contained in Ionic's scss files.

![search](https://cloud.githubusercontent.com/assets/4172079/5761361/dfe1d52c-9cd2-11e4-95e9-9e515d0e0a9d.gif)

**Comment by postcasio** [comment]
It looks like those files are being matched by your `.gitignore` file, do you have "Hide VCS Ignored Files" enabled? That will prevent them from showing in project searches.

**Comment by filipesilva** [comment]
You are very correct. I did not know that the option excluded for searches! Thank you for making this clear to me.
