### ISSUE TITLE
Atom stopped working for good in Windows 8.1

### ISSUE THREAD

**Issue by mesosteros** [atom/atom#5083]
Atom stopped opening for me after the 0.170.0 to 0.172.0 update. I closed Atom normally and when I went to open it again it no longer did.
There are no errors showing however Atom is definitely running as it has tasks opened when I open the Task Manager.
And the worst part... I already reinstalled it and it still isn't opening.

I can open it with atom --safe however the problem is not solved with this.

**Comment by kevinsawicki** [comment]
> I can open it with atom --safe however the problem is not solved with this.

So it opens in safe mode and you see the normal editor window?

So no window at all appears when you run without `--safe`?

**Comment by mesosteros** [comment]
I get the normal window editor. But even if I disable my packages and try to start atom normally it doesn't.

**Comment by kevinsawicki** [comment]
Could you try running it from the command prompt or powershell with the `-f` flag and see if the `atom` command generates any messages in the console?

**Comment by mesosteros** [comment]
It shows the app load time message (123 ms)

**Comment by kevinsawicki** [comment]
If you temporarily rename the `~/.atom/packages` directory to `~/.atom/packages2`, does Atom start normally then without the `--safe` flag?

**Comment by mesosteros** [comment]
Yes... guess it's a package issue then. Off to start taking them out one by one :/

**Comment by kevinsawicki** [comment]
Okay, closing this out then for now, please comment back when you figure out what caused it and if you think it is a core issue or an error that could be handled better.

**Comment by mark-hahn** [comment]
> Off to start taking them out one by one :/

The package package-cop lets you disable and deactivate many at once.
Often you don't even need to reboot.

**Comment by mesosteros** [comment]
You should merge this with #5074 . I now get the same error message and can't even start atom with atom --safe.

**Comment by mesosteros** [comment]
Well I seem to have gotten it up and running again. I did it by updating to 0.174.0 with all packages disabled. The only package I was not able to install at the time was Atom Ungit.
