### ISSUE TITLE
Why is Atom using bandwidth?

### ISSUE THREAD

**Issue by spencerkohan** [atom/atom#5085]
I'm paying by the GB this week, so I've been monitoring my network activity pretty closely, and I've noticed that Atom is pulling down 74 MB every time it starts up.  That's not huge, but it's a significant chunk of data.  What's going on there?

**Comment by kevinsawicki** [comment]
It is probably downloading an update (74mb is around the size of each release).

It should only be doing this when a new update is available for something is clearly going wrong, what version of Atom and what OS are you on?

**Comment by spencerkohan** [comment]
Atom 0.172.0 (0.172.0)
on OSX Yosemite 10.10.1 (14B25)

**Comment by spencerkohan** [comment]
That must have been it.  There was an option for "Install Update and Restart" under the Atom menu, and now it's only pulling 18 kb on startup.  It never prompted me for the update - not sure if that was an option I turned off or something.

**Comment by kevinsawicki** [comment]
> It never prompted me for the update - not sure if that was an option I turned off or something.

Nope, there aren't any options for this right now, it only shows update information in the menu.

There is some discussion about it here https://github.com/atom/atom/issues/4936
