### ISSUE TITLE
Hard crash when hitting enter twice in JSX grammar (provided by a package)

### ISSUE THREAD

**Issue by dmnd** [atom/atom#5088]
See orktes/atom-react#21. 

I'm reporting to core too because this causes a hard crash of Atom instead of just an exception. It seems bad that a package can take down the whole editor. Also I couldn't get a stacktrace, but I have clear repro steps.

/cc @zgotsch

**Comment by orktes** [comment]
crash caused by providing undefined string to oniguruma.testSync

**Comment by orktes** [comment]
Repro:
var OnigRegExp  = require('oniguruma').OnigRegExp; 
var regex = new OnigRegExp('foobar'); 
regex.testSync(undefined);

Might actually be more a bug with atom-oniguruma than atom itself.

**Comment by kevinsawicki** [comment]
Yeah, I'll fix it over there but we can leave this open here.

**Comment by kevinsawicki** [comment]
This will be fixed in the next Atom release, 0.175

**Comment by dmnd** [comment]
:heart:

**Comment by zgotsch** [comment]
You guys are so fast!
