### ISSUE TITLE
Ogg files shown as text file

### ISSUE THREAD

**Issue by aki237** [atom/atom#5091]
An ogg file in the working directory showed up some garbage text..
![image](https://cloud.githubusercontent.com/assets/8568726/5770429/390a63da-9d50-11e4-9047-560363f2e47c.png)

**Comment by kevinsawicki** [comment]
What does the file look like in notepad?

**Comment by aki237** [comment]
Sir,
   The image loaded looks like an image. I expected it to at least
recognize the format and when clicked it can route it to some other
suitable application to play it. Sorry for reporting. This is my first
issue. Now I learnt to discuss with others to post an issue.

Thanx

**Comment by kevinsawicki** [comment]
Yeah, currently the only binary files Atom supports by default are image and archive files, all other types open in the editor.
