### ISSUE TITLE
Atom Windows Installer Deletes User Path

### ISSUE THREAD

**Issue by robatron** [atom/atom#5092]
The latest Atom Windows installer completely overwrites the user's `PATH` environment variable with `c:\Users\<user>\AppData\Local\atom\bin`.

**Comment by robatron** [comment]
CC @jskjons

**Comment by simonjosefsson** [comment]
New install or auto-update?

Didn't happen for me with auto-updated 0.174.0 on win 8.1 64bit

**Comment by jskjons** [comment]
I had the same issue with a fresh install of 0.170.0 on win7x64

**Comment by 50Wliu** [comment]
@paulcbetts would this be an issue with Squirrel?

**Comment by robatron** [comment]
@simonjosefsson, a new install on Windows 7 x64. First time using the installer. (Had previously been using Chocolatey.)

**Comment by kevinsawicki** [comment]
>  would this be an issue with Squirrel?

Most likely not, Atom manages the path

**Comment by kevinsawicki** [comment]
For people having this issue can you run the following command and include the output in a comment?

```
reg query HKCU\\Environment /v Path
```

**Comment by robatron** [comment]
@kevinsawicki , from an admin `cmd.exe`:

    C:\>reg query HKCU\Environment /v Path

    HKEY_CURRENT_USER\Environment
        Path    REG_SZ    ;C:\Program Files\Boot2Docker for Windows

**Comment by kevinsawicki** [comment]
@robatron what about from a non-admin `cmd.exe`?

**Comment by robatron** [comment]
@kevinsawicki , unfortunately, I don't have perms. (Work machine.)

    c:\>reg query HKCU\Environment /v Path
    ERROR: Registry editing has been disabled by your administrator.

**Comment by kevinsawicki** [comment]
@robatron so did you run the Atom installer as an administrator?

**Comment by jskjons** [comment]
from admin: C:\tools\atlassian-plugin-sdk\bin;C:\tools\boot2docker
non-admin: (had to do powershell for the same reason as @robatron) 
get-itemproperty HKCU:\Environment
PATH         : C:\tools\devops-toolkit;c:\Users\jskjons\AppData\Local\atom\bin;C:\tools\apache-maven-3.2.1\bin;C:\tools\c
               hromedriver_win32-2.11\bin;C:\tools\git-1.9.3\bin;C:\tools\groovy-2.2.2\bin;C:\tools\httpd-rei.com-2.2.22.
               01\bin;C:\tools\jboss-eap-6.3.0\bin;C:\tools\jdk7-51\bin;C:\tools\node-0.10.33\bin;C:\tools\rei.com-local-
               runner-2.3\bin

I ran the installer as a non-admin user and it totally replaced that PATH variable with the atom path, it only has that stuff in it now because I re-added all the stuff

**Comment by robatron** [comment]
@kevinsawicki , no, as a standard user. Atom was installed to: 

    C:\Users\<user>\AppData\Local\atom\app-0.174.0\atom.exe

**Comment by kevinsawicki** [comment]
@robatron or @jskjons when you run `reg query HKCU\Environment /v Path` and it fails with the `ERROR: Registry editing has been disabled by your administrator.` message, do you know what the exit  code of that command was?

**Comment by robatron** [comment]
@kevinsawicki , looks like 1:

    C:\>reg query HKCU\Environment /v Path
    ERROR: Registry editing has been disabled by your administrator.

    C:\>echo %errorlevel%
    1

**Comment by kevinsawicki** [comment]
Great thanks, that is definitely the issue.

Originally I thought the only error this command returned was when the key didn't exist, which indicated it could be safely added using the `setx` command

It looks like other errors exist but use the same code which will make them tough to differentiate since I'm assuming this message is translated for different locales.

**Comment by robatron** [comment]
Thanks for the fast response on this issue. Windows is fun sometimes, isn't it? ;-)

**Comment by paulcbetts** [comment]
@kevinsawicki Maybe you want to switch to the `winreg` package? https://www.npmjs.com/package/winreg

**Comment by jskjons** [comment]
how does it set the path variable if it isn't able to read it?

**Comment by kevinsawicki** [comment]
> how does it set the path variable if it isn't able to read it?

It uses the `setx` command which appears to still work I guess in this case.

**Comment by jskjons** [comment]
ah, makes sense. You can use this command as a fallback if the reg command fails:
powershell.exe -inputformat none -command "[environment]::GetEnvironmentVariable('$name','User')"

**Comment by kevinsawicki** [comment]
>  You can use this command as a fallback if the reg command fails:
powershell.exe -inputformat none -command "[environment]::GetEnvironmentVariable('$name','User')"

Hmm, I didn't think powershell.exe was always spawn-able from node because of different security settings

**Comment by jskjons** [comment]
no idea about from within node but I've used that successfully in our locked down environment from java/groovy code.

**Comment by kevinsawicki** [comment]
Okay, I'll take a look, thanks

**Comment by paulcbetts** [comment]
> Hmm, I didn't think powershell.exe was always spawn-able from node because of different security settings

If you're spawning the EXE itself, you can pass `-ExecutionPolicy Unrestricted` to get around this silly goosery

**Comment by kevinsawicki** [comment]
@paulcbetts thanks!

**Comment by jskjons** [comment]
Any traction on getting this fixed? I've noticed that it also kills my path when it updates as well which happens pretty frequently, it's getting painful having to save my path in a text file and reset it every time

**Comment by kevinsawicki** [comment]
I've added an explicit check for this message until a better long term solution is added.

It will be released in Atom 0.185

**Comment by jskjons** [comment]
awesome, thanks for fixing this
