### ISSUE TITLE
Atom loses language-specific configs

### ISSUE THREAD

**Issue by clhynfield** [atom/atom#5095]
## Steps to Reproduce

1. Start Atom (normally or in safe mode)
2. Change CoffeeScript Tab Length config (Settings→Packages→language-coffee-script→Tab Length)
3. Restart Atom
4. Observe CoffeeScript Tab Length config has reverted

Alternately: 

1. Start Atom
2. Add the following to config.cson and save:
    ```cson
    '.coffee.source':
      'editor':
        'tabLength': 3
    ```

3. Observe indent guides change to three spaces
4. Restart Atom
5. Observe `.coffee.source` configs are missing, indent guides have reverted

**Atom Version**: 0.174.0
**System**: Mac OS X 10.10.1

## Config

Verified this happens even with a blank config: 

```cson
"*":
  "exception-reporting":
    userId: "ef120142-1f00-4aba-80ca-3bebf3c8a8dc"
  welcome:
    showOnStartup: false
```

## Installed Packages

```
# Dev
find-and-replace@0.155.0

# User
atom-beautify@0.21.2
atom-prairie-twilight-dark-syntax@0.0.0
autocomplete-plus@1.1.0
base16-ocean-dark-spacegray@0.9.0
base16-ocean-light-syntax@0.1.0
base64@0.1.0
color-picker@1.2.6
emmet@2.3.2
gist-it@0.6.3
git-plus@4.3.1
layout-manager@0.2.3
linter@0.10.0
linter-bootlint@0.0.3
linter-htmlhint@0.0.8
linter-jshint@0.1.0
linter-tidy@0.0.1
merge-conflicts@1.2.8
minimap@3.5.5
prairie-dawn-syntax@0.30.0
prairie-dusk-syntax@0.30.0
regex-railroad-diagram@0.6.3
solarized-dark-syntax@0.30.0
```

**Comment by vapask** [comment]
Get the same with '.source.jade'

**Comment by clhynfield** [comment]
Yeah, should have mentioned, it's the same with any language.

**Comment by kevinsawicki** [comment]
@maxbrunsfeld can you take a look at this one?

**Comment by maxbrunsfeld** [comment]
Damn. Fixing now.

**Comment by maxbrunsfeld** [comment]
Thanks for catching that really important bug @clhynfield. I believe it is fixed on master. Please let me know if there still issues with this after v0.175 comes out.

**Comment by clhynfield** [comment]
Will do, @maxbrunsfeld, and thanks very much for the super-quick fix!
