### ISSUE TITLE
Can't use Github for mac and Chrome with Atom together.

### ISSUE THREAD

**Issue by Murriouz** [atom/atom#5103]
Recently I use atom to coding in my work. But after some time, I found Github for mac can't push, pull sync, commit. It also tell me file exists or something. At the mean time Goolge Chrome browser cant load any page either. Quit atom, all things get back. Github can commit, pull, push, sync, and Chrome can load page. I don't know what happened, but every time this happen, I just restart atom.

Atom version: 0.16x ~ 0.17x, I can't remember if an ealier version had this issue.

Here's my installed packages.

```
atom-beautify
auto-update-packages
autocomplete-gocode
autocomplete-paths
autocomplete-plus
autocomplete-snippets
compass
emmet
file-icons
git-plus
hex
project-manager
save-session
seti-syntax
seti-ui
webbox-color
```

**Comment by mnquintana** [comment]
What versions of OS X and GitHub for Mac are you running?

**Comment by maxbrunsfeld** [comment]
Can you report the exact error message that GitHub for Mac shows?

**Comment by achalatsis** [comment]
I can confirm this behavior and was collecting data for a bug report.
The issue is broader; no further processes can be forked.
This issue was present for me since 0.14x.

**Comment by mnquintana** [comment]
Huh, I've never experienced this on OS X 10.10.x. @achalatsis I'd like to see what you find

**Comment by MiincGu** [comment]
OS X 10.10.1
Github for Mac Honourary Brit (194)

**Comment by MiincGu** [comment]
Here's a screenshot.

When I want to commit, Github for Mac tell me file exists. Restart Atom will resolve this.

![5c42564d-2b28-4dc2-a7af-3d99e9e18d76](https://cloud.githubusercontent.com/assets/4125903/5788475/7c711a60-9e72-11e4-9cc8-1abb6130b08b.png)

By the way, this time I found Photoshop can't lanuch either...

**Comment by kevinsawicki** [comment]
This looks like a GitHub for Mac issue and not something we will be able to fix here.

Please reach out to GitHub Support via https://github.com/contact if you are still experiencing this issue.

I'll be able to follow the ticket in our help system and try to figure out how Atom may be impacting GitHub for Mac.

**Comment by pillowsoft** [comment]
This is NOT a GitHub for Mac only issue (note that the original poster said it also affects Chrome, not just GitHub for Mac). I see similar issues when running Atom on my Mac. At some point after running Atom, Chrome will not longer open Web pages (or shows a web page crashed), SourceTree fails on commits, running node in the terminal can no longer exec, etc. Basically once an hour I need to quit and relaunch Atom to make things work. I have never seen any odd app to app interaction like this on my Mac before. I will try to diagnose further, but am unsure why other Mac users are not seeing this as well. I will see if I can get any more console log files to help diagnose.

**Comment by kevinsawicki** [comment]
> I will see if I can get any more console log files to help diagnose.

That would be great, any further details would be great, perhaps also checking the Activity Monitor when this happens and seeing how many Atom Helper processes exist when this starts happening and what their CPU and memory usage is.

**Comment by pillowsoft** [comment]
Just had things error again and this is what I see:

___
- Activity monitor shows 6 Atom Helpers
- cpu usage is low (0.1 %), 27 threads
- Atom memory is 80 MB, helpers are between 100 and 400 MB

___
Spawning a node command gets this:

npm ERR! argv "node" "/Users/bpillow/.nvm/versions/node/v0.12.2/bin/npm" "run" "jsnotebooks"
npm ERR! node v0.12.2
npm ERR! npm  v2.10.0
npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno EAGAIN
npm ERR! syscall spawn sh
___
At this point, most new Chrome windows end up in "Aw Snap" (crashed). No useful output in the console :-( Sometimes if I wait a bit (without exiting Atom), reloading some Chrome windows will work, intermittently. I've just never seen anything like this on a Mac where one app can affect another in this way. FWIW, I am on Yosemite, 10.10.4

**Comment by pillowsoft** [comment]
Apparently this is not an Electron issue. My apologies. After seeing a related bug report (https://github.com/facebook/nuclide/issues/84) over on the Nuclide repo, I removed all my Nuclide packages. Since I did that, I have had none of the issues reported here. It seems Nuclide has the problem (perhaps from some native modules it uses?). When the issue occurs, it prevents other processes from spawning child processes. This causes new pages in chrome, SourceTree commits, npm commands, etc. to all fail, as they spawn child process that end up returning an error. I believe you can close this out and we can hope that Nuclide gets fixed at some point.

**Comment by MiincGu** [comment]
I never use Nuclide packages, and this happens. So I dont think it's a Nuclide issue.

**Comment by pillowsoft** [comment]
Odd, that getting rid of Nuclide worked for me. Perhaps their use just exacerbates some underlying issue in Atom (I meant Atom, not Electron in my previous post)?
