### ISSUE TITLE
Keymap resolver reports keys according to US layout when on sv_SE layout

### ISSUE THREAD

**Issue by cortex** [atom/atom#5104]
When I use the keymap resolver, all keys except for alphabetic are mapped according to US keyboard layout:

Example in keymap resolver
pressing < shows up as \ 
pressing shift-7 (which should be /) shows up as & 
pressing å shows up as ]
pressing ö shows up as ;
pressing ä shows up as '

When I use Dvorak(sv) I get a similar behaviour but it seems the non-alpha keys are mapped to the US key that would be where the swedish key would be:

For example, pressing the key that would be 'q' in qwerty (and which should be å in dvorak) maps to ']', which is on the same position on US keyboard as 'å' is on a normal swedish keyboard.

This is Atom 0.174.0 on Arch linux. Shortcuts and keys work just fine in all other applications.

**Comment by 50Wliu** [comment]
This is being tracked at atom/atom-keymap#37, please subscribe there for updates.
