### ISSUE TITLE
Atom can no longer open readonly files

### ISSUE THREAD

**Issue by ecbrodie** [atom/atom#5107]
I have been using Atom on a project where files are managed by a Perforce depot. That means that all files are marked as readonly until they are checked out by Perforce. On my Mac machine, this means that only the read flag is set in the file permissions.

Up until today, I was able to open these readonly files in Atom to view its contents, just like any normal file. I could even save to the readonly files, with Atom giving me an extra prompt to let me know that I'm overwriting a readonly file.

But as of today, that has completely changed. When I attempt to open up the readonly file, instead of the file opening in the Atom editor, I instead get the following error message on the top right corner: *"Permission denied '/my/path/to/file'"*. Perhaps there was some sort of Atom update released today or this week that changed its functionality. I would say that it is quite desirable to be able to open up readonly files, at least for just reading if not writing. All other major text editors, especially Sublime, support viewing readonly files.

Note that I could probably use `sudo atom` to get superuser access and be able to read/write files that are readonly, but needlessly relying on root is not the best idea.

**Comment by ecbrodie** [comment]
Thanks!

**Comment by ecbrodie** [comment]
I just checked again today and I'm still seeing the issue. I still get the "Permission denied ..." error when I try to open a readonly file with Atom. I am using the latest Atom version, 0.174.0.

Perhaps has this bug fix not been released to the wild yet? If not, when is the planned release?

**Comment by 50Wliu** [comment]
I believe it'll be released in 0.175.0, which should be coming soon™.
