### ISSUE TITLE
Uncaught Error: EEXIST, file already exists '/Users/<<Username>>/.atom/storage'

### ISSUE THREAD

**Issue by pkurimella** [atom/atom#5108]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: EEXIST, file already exists '/Users/<<username>>/.atom/storage'

```
At /Users/<<username>>/.atom/packages/auto-update-packages/node_modules/fs-plus/node_modules/mkdirp/index.js:74

undefined
```

### Commands

```
     -0:00.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v0.2.1
autocomplete-plus, v0.22.3
jsformat, v0.7.18

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please update to the latest version-I believe the errors have been greatly improved for these types of things.

**Comment by kevinsawicki** [comment]
Dupe of https://github.com/atom/atom/issues/4806
