### ISSUE TITLE
Consider replacing :lipstick: in the git commit message emoji guide?

### ISSUE THREAD

**Issue by beaugunderson** [atom/atom#5111]
We recently adopted the awesome [git commit message emoji guide](https://github.com/atom/atom/blob/97d697f1952eaa4bb0d5d71f4895877183ad53ba/CONTRIBUTING.md#git-commit-messages) outlined in atom's CONTRIBUTING.md for our own projects but a coworker felt uncomfortable because :lipstick: is a gendered form of beauty (and while some men do wear lipstick, [makeup is a very different experience for women](http://faculty.georgetown.edu/tannend/nyt062093.htm)). I also felt uncomfortable once it was pointed out.

In our own version we chose to use :rose: instead as an un-gendered form of beauty and I figured I should raise the issue 'upstream' too. :sparkles:

**Comment by kevinsawicki** [comment]
Thanks for pointing this out, I think it is definitely something worth considering changing.

Just to add a bit of context, historically I believe it started as a reference to the [lipstick on a pig](http://en.wikipedia.org/wiki/Lipstick_on_a_pig) saying, meaning the commit was improving things cosmetically but code could still be a mess functionally.

**Comment by rachelmyers** [comment]
Looking through the emoji, :art: (`:art:`) jumps out at me as a non-gendered way to signal surface changes. What do people think?

**Comment by shana** [comment]
:+1: on :art:, it has the right meaning for this imo.

**Comment by kevinsawicki** [comment]
Thanks @beaugunderson for raising this

**Comment by beaugunderson** [comment]
Thanks for being so responsive!
