### ISSUE TITLE
Autocomplete allows CTRL-Z (undo) in textbox

### ISSUE THREAD

**Issue by GameplayJDK** [atom/atom#5115]
The autocomplete feature allows CTRL-Z (undo) shortcut in it's textbox.. I don't know if that's how it's supposed to be...

![bug3](https://cloud.githubusercontent.com/assets/4069263/5783215/58a5e9f0-9dc1-11e4-808d-2437be190bbb.png)

Example (html): When I typed `body` once and pressed enter, the next time I enter something, I can use CTRL-Z to revert the content of the little textbox to `body` again.

**Comment by izuzak** [comment]
This issue was moved to atom/autocomplete#62
