### ISSUE TITLE
Renaming open file or directory makes copy

### ISSUE THREAD

**Issue by macu** [atom/atom#5119]
Right-click in the tree view to rename a file (which is currently open in the editor) and the file gets copied/duplicated to the new name while the old file remains open. They are not symlinked as editing one does not produce changes in the other after closing/reopening.

Renaming a directory (containing a file open in the editor) has similar effect. The old directory remains, including any files currently open in the editor. Everything else is moved to the new directory, including copies of open files.

Atom 0.170 on OS X 10.10. Has been happening for a while, and happens even when all plugins are disabled. I tested by opening my Desktop folder in Atom, creating a folder and some files, and renaming the folder while with some files open.

**Comment by izuzak** [comment]
Thanks for the report, @macu. This seems similar to https://github.com/atom/autosave/issues/9 (also see https://github.com/atom/tree-view/issues/123 for context). Could you take a look at that issue and close this one if it is indeed the same one? If not, could you clarify what's different? Thanks! :bow:

**Comment by macu** [comment]
Yep, same issue. I searched the atom issues before creating this one. Didn't notice there were issues tracked separately in atom/autosave etc. Thanks!

**Comment by krainboltgreene** [comment]
This still seems to be an issue in the latest atom releases. Should this be re-opened?

**Comment by 50Wliu** [comment]
This issue was closed because it was a duplicate, not because it was fixed.  Please follow the links that @izuzak provided.

**Comment by krainboltgreene** [comment]
One of the links is closed and the other seems to describe an different context (and is still open 10 months later).

**Comment by eltian** [comment]
Just FYI I'm using Atom 1.15 and this is NOT fixed. When renaming an opened file, the buffer doesn't update the filename and keeps the old one opened. If you save such file, Atom creates a new one with the old name. I think the buffer should update the filename accordingly.

**Comment by 50Wliu** [comment]
This issue was closed because it was a duplicate, not because it was fixed. Please follow the links that @izuzak provided.

**Comment by eltian** [comment]
Those two issues are already closed, and the autosave solution didn't work for this case, apparently.

**Comment by 50Wliu** [comment]
In that case, feel free to open a new issue so that we can get the necessary information to investigate.
