### ISSUE TITLE
Crashes when opening any file.

### ISSUE THREAD

**Issue by Zyluss** [atom/atom#5120]
Im using the latest version of atom with no packages on a Mac latest version and whenever I open a file with atom it crashes.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by Zyluss** [comment]
Sorry I've fixed this, it was an issue with the git index. Sorry for bothering you.
