### ISSUE TITLE
PHP files incorrectly identified as HTML

### ISSUE THREAD

**Issue by polybuildr** [atom/atom#5124]
If I have an PHP file with a `.php` extension that contains only HTML, the editor identifies it as HTML (as shown in the status bar). This becomes an issue because even after some php code is added (within `<?php ?>` tags) the editor does not update the file type and syntax highlighting does not get enabled for PHP. I have to manually change the file type to PHP to get correct syntax highlighting.

Are there any fixes for this, or am I doing something wrong?

**Comment by Bengt** [comment]
So to paraphrase, you have an HTML file with embedded PHP and would expect that the HTML parts and the PHP parts are both highlighted according to their respective syntax? This is a very similar issue to having different (natural) languages in the same document and spell checking them according to their respective spellings. See https://github.com/atom/spell-check/issues/25. Atom does not currently support either, so you will have to do without highlighting resp. ignore the spellchecking or not mix syntaxes / languages in documents.

**Comment by Bengt** [comment]
Detecting each fragment is one solution to this, but another is defining a syntax scheme for HTML-with-Embedded-PHP and equivalents for all possible embeddable scripting languages and templating languages. ... There is [a package that does this for Python's django templates and HTML](https://atom.io/packages/language-python-django-templates), perhaps there is an equivalent for PHP and HTML, too.

**Comment by polybuildr** [comment]
@Bengt, it's not really the same issue. PHP supports embedded HTML (by default, as a language itself) and atom correctly highlights HTML, CSS, JS and PHP in a file with a PHP file type. My basic issue is that even though my files have a `.php` extension, atom identifies them as HTML (because they have only HTML code) and so I don't get the right highlighting.

**Comment by Bengt** [comment]
Isn't a file which only contains HTML highlighted correctly regardless of whether it is highlighted using [language-HTML](https://github.com/atom/language-html) or [language-PHP](https://github.com/atom/language-php) then?

**Comment by m1ga** [comment]
A quick fix is to insert an empty line at the beginning. Otherwise its still open here: https://github.com/atom/language-php/issues/35

**Comment by polybuildr** [comment]
@Bengt yes, it is. But after that, if I add in some PHP, it is still identified as HTML, and that's where the issue is.

@m1ga I see. I'll follow up the issue there then. Thanks!
