### ISSUE TITLE
Missing directory name when multiple files with same name in different tab groups

### ISSUE THREAD

**Issue by StewartAtkins** [atom/atom#5125]
Using 0.174.0 on windows

When opening multiple files of the same name, the directory name is appended to the tab to allow the user to differentiate which version of the file each tab represents. 

This behaviour does not appear to work between different editor panes, the attachment below shows 3 .jshintrc files, the ones on the left correctly displaying the folder name (as it has two files called .jshintrc), while the third one in other pane (being the only .jshintrc in its window). If there is only one .jshintrc on each pane then they both do not show the folder name.

(.jshintrc is unrelated to the issue it just happened to be a file I had three of in a repository)

![atom](https://cloud.githubusercontent.com/assets/4512498/5790160/f689b076-9e83-11e4-87cf-64fd9823f6bd.PNG)

Expected behaviour: folder name should be displayed if tab filename is not unique across all tabs, not just the tabs on that editor pane. This is how sublime behaves.

**Comment by goeddea** [comment]
+1 for fixing this. As is, working with several project with similar structure (or just "index.html") can get complicated.
