### ISSUE TITLE
Gigantic menu fonts on HiDPI (Linux, GNOME)

### ISSUE THREAD

**Issue by danielquinn** [atom/atom#5130]
I see that HiDPI support appears to mostly work in Atom, but with `org.gnome.desktop.interface` set to `2`, atom launches with menu items of a crazy size:

![atom](https://cloud.githubusercontent.com/assets/218205/5790894/a9baed6a-9eaf-11e4-8534-27727a242867.png)

Launching atom with `--force-device-scale-factor=1` appears to have no effect.

    $ atom --version
    0.174.0-2f76597

This was built from source on Gentoo Linux manually, because there's no ebuild available :-(

**Comment by mnquintana** [comment]
:grimacing: I wonder if this is more of an Atom or [atom-shell](https://github.com/atom/atom-shell) issue.

**Comment by danielquinn** [comment]
I have no idea, but I can file this bug there instead if you think that's more appropriate.

**Comment by zcbenz** [comment]
This is Chromium's bug on HiDPI support on Linux, and you can track it at https://code.google.com/p/chromium/issues/detail?id=143619.

**Comment by wvengen** [comment]
Is there any known workaround?

**Comment by kevinjqiu** [comment]
Any news on this now that Chrome has decent support for HiDPI on Linux?

**Comment by mnquintana** [comment]
Closing this in favor of https://github.com/atom/atom/issues/3826 – please subscribe there for updates.
