### ISSUE TITLE
coffeescript highlighting syntax error

### ISSUE THREAD

**Issue by faceair** [atom/atom#5134]
source code:

    matches = body.match /lbxsh">(.+?)<\/[\s\S]+?lbzyh">(.+?)<\/[\s\S]+?lbbh">(.+?)<\/[\s\S]+?Lbxh">(.+?)<\/[\s\S]+?tbxsxm.+?value="(.+?)"[\s\S]+?selected" value="\d*">(.+?)<\/[\s\S]+?selected" value="\d*">(.+?)<\/[\s\S]+?tbpycc.+?value="(.+?)"[\s\S]+?tbrxrq.+?value="(.+?)"[\s\S]+?tbsfzh.+?value="(.+?)"/
    unless matches
      console.error body
      return callback '未知错误，请稍后重试。'
    matches = _.map matches, (match) ->
      return if match is '(请选择)' then null else match

![qq20150118-1](https://cloud.githubusercontent.com/assets/3659110/5792220/72a98734-9f48-11e4-8e7d-87c45622d46d.png)

**Comment by 50Wliu** [comment]
Atom cannot highlight more than 100 characters in a line currently.  See #1667.
