### ISSUE TITLE
Can't open files owned by root

### ISSUE THREAD

**Issue by olmokramer** [atom/atom#5136]
I'm on Linux Debian 8, Atom v0.174.0. When I try to open a file (`/etc/hosts`) that is owned by root, either by
* `file-menu->open file` 
* pressing <kbd>Ctrl-O</kbd>, navigating to the file and double-click it
* dragging a file onto the atom window 
* typing `atom <file>` from a command line

I get an error notification saying `Permission denied: <file>`, even though the file has permissions `644`, so reading is permitted for everyone. No messages in the console

Then I tried to `sudo atom <file>`, expecting a new atom window would open with root permissions, with also the file opened, but instead atom tried to open the file in the atom window that was already open (without root permissions), and I got the same error.

So then I tried just `sudo atom`, expecting again that a new window with root permissions would open, only to find out that it opened a new window without root permissions. This <i>does</i> work, however, when no other atom window is already open.

This means that when I just want to <i>read</i> a file owned by root, I have to shut down all other atom windows, then open up another window with root permissions and open the file. Now I'm risking saving edits to a file I just want to read.

**Comment by postcasio** [comment]
This will be fixed in 0.175.0 thanks to https://github.com/atom/atom/pull/5114. It should be out soon, feel free to reopen this issue if the issue persists.

**Comment by olmokramer** [comment]
Great! Thanks for the link
