### ISSUE TITLE
Atom.open opens new window even if newWindow is set to false.

### ISSUE THREAD

**Issue by Trudko** [atom/atom#5138]
Hi, I am bit confused about atom.open with newWindow option.

If I open the console and try running atom.open({'pathsToOpen': ['test.txt'], 'newWindow': false});  Test.txt opens in new window even though newWindow is set to false. If I run same command with absoluthe path to file, file opens in same window. I am curious if that's what this part of documentation is talking about:

> .newWindow A Boolean, true to always open a new window instead of reusing existing windows  **depending on the paths to open.**

So you need to provide absoluth path in order for file to open in same window?

**Comment by mnquintana** [comment]
> atom.open({'pathsToOpen': ['test.txt'], '.newWindow': false})
Correct me if I"m wrong, but this kinda looks like a typo: `'.newWindow'`

Should it be `'newWindow'` instead? My understanding from the API docs is that the `.` is there just as a reminder that they should be properties on the `options` object.

**Comment by Trudko** [comment]
@mnquintana you are correct, but behavior is same without typo too. I fixed the type in description.

**Comment by basarat** [comment]
I am getting the same issue. Only happens in some circumstances and its unclear why. E.g. you can see that it *shouldn't happen* in the below case as the path is in the project but yet *it does happen* i.e the file opens in a new window.

![image](https://cloud.githubusercontent.com/assets/874898/6261472/dbcf35d8-b843-11e4-9962-b19bf1d34b9b.png)
 

refs: https://github.com/TypeStrong/atom-typescript/issues/99

**Comment by basarat** [comment]
workaround : use https://atom.io/docs/api/v0.181.0/Workspace#instance-open

**Comment by bernieperez** [comment]
Also from the command line

```
$atom --help
Atom Editor v0.187.8016939

Usage: atom [options] [path ...]
...
-n, --new-window      Open a new window.      [boolean]
```

but ```atom -n false .``` or ```atom -n=false .``` doesn't open in the same window.

**Comment by kans** [comment]
I'd also like to add that atom sometimes closes the current window when atom.open is called and then does nothing.  I can detect no pattern - calling it again may have the desired behavior.

**Comment by akhilcb** [comment]
I am also having this same issue. I want to open in same atom window, but it always opens in new window when I try from command line as "atom <filepath>". I couldn't find any way to merge both windows too. Is there any solution for this?

**Comment by 0505gonzalez** [comment]
Same problem. Sometimes it works, others it doesn't.

**Comment by ssbarnea** [comment]
I discovered that opening in new window instead of tab always happens when the file does not exist yet. I filed that as a separate bug because is very easy to reproduce: https://github.com/atom/atom/issues/14801
