### ISSUE TITLE
Package missing in search from within editor settings

### ISSUE THREAD

**Issue by cdwilson** [atom/atom#5139]
Any idea why the https://atom.io/packages/language-nesc package doesn't show up in the search results within the editor settings?

![search_language-nesc](https://cloud.githubusercontent.com/assets/14631/5793606/eda811d4-9efe-11e4-9084-37955ccb746f.png)

It installs just fine via `apm`:

![apm_install_language-nesc](https://cloud.githubusercontent.com/assets/14631/5793608/f38b0c8c-9efe-11e4-86e6-d42379f5731c.png)

**Comment by lee-dohm** [comment]
The search field you're looking for is on the Install tab now. The field you're editing in your screenshot is more accurately a filter, filtering the packages that are already installed.

**Comment by cdwilson** [comment]
DOH!...thanks :+1:
