### ISSUE TITLE
Uncaught Error: Cannot find module 'jshint/src/cli'

### ISSUE THREAD

**Issue by GianLaz** [atom/atom#5145]
Uncaught Error: Cannot find module 'jshint/src/cli'

**Atom Version**: 0.153.0
**System**: linux 3.17.4-031704-generic
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package

**Comment by benogle** [comment]
Please update atom. This issue may have been fixed.

**Comment by GianLaz** [comment]
Update & fixed. Thanks
