### ISSUE TITLE
find not working

### ISSUE THREAD

**Issue by jesseolssondirt** [atom/atom#5147]
command-f and command-shift-f have completely stopped working. on osx yosemite. i tried reinstalling everything. can anyone confirm this?

**Comment by 50Wliu** [comment]
Can you reproduce using safe mode (`atom --safe`)?
What version of Atom are you using?

**Comment by jesseolssondirt** [comment]
yes, reproduced in safe mode. Version 0.174.0

it doesn't work with "find in buffer" in the menu either.

**Comment by mnquintana** [comment]
Can you use those keyboard shortcuts in other apps?

**Comment by jesseolssondirt** [comment]
yes

**Comment by benogle** [comment]
What system are you on? Is there anything in the dev tools? Can you open the keybinding resolver (`cmd-.`), try the find commands, and paste a screenshot? Can you paste in your `keymap.cson`? Can you move your `.atom` folder, and start atom? Does it work then?

**Comment by jesseolssondirt** [comment]
i cleared the .atom folder and everything else and it is working again. sorry!

**Comment by benogle** [comment]
My guess is something in your `keymap.cson` or your config.

**Comment by clintconklin** [comment]
Ran into this as well today. Yosemite 10.10.3, with and without safe mode, nothing in the console, same regex on the same file worked fine in sublime.

For me, removing keymap.cson didn't fix it, but removing atom/compile-cache and restarting did.

**Comment by AndyDorman** [comment]
Same thing just happened to me.  Atom 0.200.0, Debian testing, with & without safe mode.

Not sure when it happened, but yesterday I noticed that neither Ctrl-F nor menu "Find in Buffer" would bring up Find.  Based on clintconklin report I removed my .atom/compile-cache and restarted and that fixed it.

**Comment by dtracers** [comment]
I just got this too.
I did not even clear the cash but instead just restarting fixed it.

**Comment by torleif** [comment]
Confirmed for me

Windows 7.0
Atom 1.0

**Comment by zharvey-welltok** [comment]
Ditto for me, on Yosemite as well. Bump

**Comment by WestleyArgentum** [comment]
Still a problem for me, 

OSX 10.11.6 (15G1108)
Atom 1.11.2

**Comment by LunaCodeGirl** [comment]
Restart fixed it for me as well

**Comment by uncleGena** [comment]
It was helpful for me to check out the styles and **display:none** property :-)
