### ISSUE TITLE
Ability to specify display and space (OS X) within which to open a new window

### ISSUE THREAD

**Issue by wolfspyre** [atom/atom#5153]
I think it would be really useful to be able to tell atom to open a new window on a specific space which resides on a specific physical display. Use case would be in combination with a few other tools to create a new space on a specific display, open a terminal window with specific geometry, an atom window with specific geometry, both relative to the display's current resolution. (amongst other things)

there are workarounds I'm thinking about if this isn't possible, but if it's simple to add, it would simplify the scripting pipeline a bit.

**Comment by mnquintana** [comment]
Oooh this would be cool. Are you thinking it would be implemented with extra option flags in the `atom` CLI?

**Comment by postcasio** [comment]
Here's a related chromium bug https://code.google.com/p/chromium/issues/detail?id=74812 apparently OS X has no API for doing this (presumably its something that should only ever be under the user's control).

cc @zcbenz since this would need an atom-shell change
