### ISSUE TITLE
Document tabs stack on top of each other vertically, instead of horizontally

### ISSUE THREAD

**Issue by mattmogford** [atom/atom#5156]
Occurred after updating to 0.172.0

Have the following packages installed - (tried disabling them all, but same problem)
autocomplete-plus
javascript-snippets
jsformat
jshint
open-last-project
terminal-panel

**Comment by mnquintana** [comment]
Can you post a screenshot?

**Comment by mattmogford** [comment]
![screen shot 2015-01-20 at 10 00 21](https://cloud.githubusercontent.com/assets/2421265/5818857/c79a6466-a0b0-11e4-844e-113dde8c48e8.png)
Thank you

**Comment by mnquintana** [comment]
Do you have any themes installed?

**Comment by mattmogford** [comment]
Yes - 
darkula-ui
darkula-syntax
monokai

**Comment by mnquintana** [comment]
What's your current theme (and its version)?

**Comment by mattmogford** [comment]
Darkula - 0.1.0

**Comment by mnquintana** [comment]
Can you switch to Atom Dark and see if the issue persists?

**Comment by mattmogford** [comment]
It doesn't persist no.

I've just looked into the Darkula CSS and commented out the display as below.
This fixed it. Do you think that it's required for anything else?

.tab-bar {
  color: @silver;
  background-image: -webkit-linear-gradient(top, #4f5051, #4f4f4f);
  border-top: 1px solid @dove-gray;
  border-bottom: 1px solid #454648;
  padding-bottom: 4px;
  // display: block;
  clear: both;

**Comment by mnquintana** [comment]
I'm not sure off-hand (I've never used that theme), but my guess is that some stuff is broken because [Darkula hasn't been updated since March](https://github.com/benburton/darkula-ui). 

(But this is really a Darkula issue, not so much an Atom issue.)

**Comment by mattmogford** [comment]
I've mentioned it on the Darkula github.
Thanks for your help.
