### ISSUE TITLE
node-sass Module did not self-register.

### ISSUE THREAD

**Issue by GomatoX** [atom/atom#5158]
Hello,

I'm getting error when i'm trying to load node-sass library in my package:

``Uncaught Error: Module did not self-register.``

It's working with other node libraries but with this one I'm stuck.
Any ideas why i'm getting that?

**Comment by kevinsawicki** [comment]
Have you tried running `apm rebuild` at the root of the package you are developing?

**Comment by GomatoX** [comment]
Yes I tried with no results.

**Comment by kevinsawicki** [comment]
It looks like node-sass ships pre-compiled binaries, https://github.com/sass/node-sass#rebuilding-binaries and that is the issue.

These binaries will need to be recompiled using apm to properly compile/link against the v8 headers that Atom ships with.

Your best option is to fork the project and build it for atom-shell, you might want to look at https://github.com/atom/atom-shell/issues/1031 for more details on this.

**Comment by GomatoX** [comment]
Thanks.
