### ISSUE TITLE
Cant update Atom due to writing to temp directory

### ISSUE THREAD

**Issue by paulcruse3** [atom/atom#5160]
I can't update atom.

Every time I try I get the error: "Could not create temporary directory."

I have full permissions on my MacBook Pro, 13inch running OSX10.10.1. I have Atom 0.172

I have tried with the command line as well and get no luck.

I get this:

`npm ERR! install Couldn't read dependencies`
`package.json npm can't find a package.json file in your current directory.`
`path /Users/pcruse3/.atom/package.json`

Any thoughts?

**Comment by mnquintana** [comment]
How were you updating Atom (before you tried running `apm update`)? Could you paste the full error / stack trace?

**Comment by paulcruse3** [comment]
It has never worked...

Here is the code:

`npm ERR! install Couldn't read dependencies
npm ERR! package.json ENOENT, open '/Users/pcruse3/.atom/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! System Darwin 14.0.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/pcruse3/.atom/.apmrc" "install" "--target=0.20.0" "--arch=x64"
npm ERR! cwd /Users/pcruse3/.atom
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! path /Users/pcruse3/.atom/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno 34
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/pcruse3/.atom/npm-debug.log
npm ERR! not ok code 0`

**Comment by mnquintana** [comment]
So wait, have you only ever tried updating Atom with `apm update`?

As far as I know, `apm update` just updates an Atom package's dependencies like `npm` does (which is why it's looking for a `package.json`), and there is no way to update Atom from the command line. `apm upgrade` updates your packages, but still not Atom itself. I posted a related issue at atom/apm#246

If you want to update Atom you need to check for updates in the GUI.

**Comment by paulcruse3** [comment]
Oh really?

I thought `apm upgrade` updated packages while `apm update` updated atom.

Either way trying to update atom form the GUI doesn't work either...

**Comment by mnquintana** [comment]
Can you post the full stack trace (or a screenshot) of the error you get when you try to update from the GUI?

**Comment by paulcruse3** [comment]
Here is the screen shot (not sure how to do a stack trace via the GUI):

![screen shot 2015-01-20 at 10 52 49 am](https://cloud.githubusercontent.com/assets/7433251/5821536/82009204-a092-11e4-9f42-0e8a785ce5c0.png)

**Comment by mnquintana** [comment]
I don't really know enough Obj-C to parse this, but I found the line of the Squirrel updater Atom uses: https://github.com/Squirrel/Squirrel.Mac/blob/d0b18ef3a48f0fa222a835dffe1de5ee14defcb5/Squirrel/SQRLUpdater.m#L437

My guess is that your permissions got messed up in whatever directory Squirrel is trying to create a temp directory.

**Comment by maxbrunsfeld** [comment]
@paulcruse3 when this happens, is there any corresponding output in the `Console` app?

**Comment by paulcruse3** [comment]
how do I access the console for atom? @maxbrunsfeld

**Comment by mnquintana** [comment]
@paulcruse3 Check the OS X Console (Console.app)

**Comment by paulcruse3** [comment]
@mnquintana @maxbrunsfeld anywhere I can find/install an older version of atom? I got tired of the error and manually re-downloaded atom and installed it (not ideal process to have to do every time)....

**Comment by gldnspud** [comment]
I am running into this too. Same screenshot & symptoms. I can't find anything Atom related in console except for "App load time" messages. I ended up installing from fresh ZIP file as @paulcruse3 resorted to.

Of note is that I use three different user accounts on my system, for different contexts. I try to keep updates happening in only a single account, but sometimes auto-update mechanisms trigger in various apps while using other accounts.

So this very well may be a permissions problem, at least on my system.

I'll look a little deeper next time there's a new release.

**Comment by slartibardfast** [comment]
doing a
````
sudo chown -R $USER ~/Library/Application\ Support/com.github.atom.ShipIt
```` 
should allow you to update. 

on my system, this folder picked up root ownership, no idea why!

**Comment by gldnspud** [comment]
Thanks @slartibardfast, that fixed it for me too.

root also owned that dir on my system:

```
drwxr--r--   2 root  staff     68 Jan 15 16:12 com.github.atom.ShipIt
```

**Comment by natarajanrodrigues** [comment]
It worked for me. But I done with:

**Comment by natarajanrodrigues** [comment]
It worked for me: ```sudo chown -R $USER ~/Library/Application\ Support/com.github.atom.ShipIt``` and ```sudo chown -R $USER /Applications/Atom.app/```. It seems like a weight has come off.

**Comment by dresh** [comment]
chown: /Users/deepesh/Library/Application Support/com.github.atom.ShipIt: No such file or directory

**Comment by meetbryce** [comment]
I'm having the same issue on OS X Sierra with Atom v1.12.6

Tried the above commands and didn't see any change.

**Comment by stephenvoisey** [comment]
@meetbryce Had the same problem and the previous solution didn't work (and the directory ownership was $USER already anyway). Checking the Atom site, it looks like Atom stable has progressed to 1.13, so I simply downloaded and dragged Atom into the applications folder and replaced it. Running it, all seems fine and updates don't throw an error.

**Comment by tomoat** [comment]
I'm having the same issue on OS X Sierra with Atom v1.14.3
Tried the below commands and didn't see any change.
```sh
sudo chown -R $USER ~/Library/Application\ Support/com.github.atom.ShipIt
```
![image](https://cloud.githubusercontent.com/assets/7428698/23751965/71b6a446-050e-11e7-841d-925703169f5f.png)
![image](https://cloud.githubusercontent.com/assets/7428698/23752003/9d91e256-050e-11e7-9cc3-dd6326be8e4f.png)

**Comment by keymone** [comment]
having the same problem on version 1.14.4, had it on previous version too, downloading `Atom.app` and replacing in `/Applications` did nothing. `~/Library/Application\ Support/com.github.atom.ShipIt` doesn't exist.

**Comment by AndreaGriffiths11** [comment]
@keymone check out this FAQ, it might help [unable to update to the latest version of Atom](https://discuss.atom.io/t/i-am-unable-to-update-to-the-latest-version-of-atom-on-macos-how-do-i-fix-this/40054).

**Comment by andreasblomqvist** [comment]
same problem as @keymone the last dir doesn't exist. Any ideas on how to proceed? On mac with v1.17.2

**Comment by eevirgen** [comment]
in order : 
. sudo chown -R $USER ~/Library/Caches/com.github.atom.ShipIt
. sudo chown -R $USER ~/Library/Application Support/com.github.atom.ShipIt
and/or 
. sudo chown -R $USER ~/Library/Caches/com.github.atom.ShipI
👍

**Comment by AsherPeruscini** [comment]
Had to add a `t` to the end of the last one, but it worked for me!

**Comment by Bex0-0** [comment]
Mine Atom version was 1.18.0 x64 and I run into the same problem. After reading above suggestions, I found the directory at ~/Library/Caches/com.github.atom.ShipIt. I got its Info and just changed the permission of staff from custom to read & write, then the update went on without the problem.

**Comment by mattmattmatt** [comment]
Thanks everyone for posting. I suddenly ran into the same problem and this did the trick for me:
```bash
$ sudo chown -R $USER ~/Library/Caches/com.github.atom.ShipIt
```
