### ISSUE TITLE
Optimize typing, cursor movement, and scrolling performance

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#5163]

**Comment by YuriSolovyov** [comment]
possibly related to scrolling: #3154

**Comment by gregersrygg** [comment]
Good to see you're planning on improving the typing performance :) It can take many seconds to type 1 character when using a few hundred cursors. Not sure you need it, but here is a CPU-profile I saved while typing. The first plateau (in the profiler chart view) is when I pressed <kbd>⌘</kbd><kbd>⇧</kbd><kbd>L</kbd> to convert the selection into multiple cursors. The rest of the plateaus are typing.

[multiple-cursors-typing.cpuprofile](https://www.dropbox.com/s/4pw45ii6gxtai59/multiple-cursors-typing.cpuprofile?dl=0)

![screen shot 2015-02-18 at 19 40 06](https://cloud.githubusercontent.com/assets/149725/6254056/0553f720-b7a6-11e4-9ca5-e2dd899dcc32.png)

To me it looks like it's in the `reducer` inside `TextEditor.prototype.mergeIntersectingSelections` most of the time is spent (actually inside underscore-methods called from `reducer`).

If `mergeIntersectingSelections` does what it sounds like it does. Then why does it need to be called when I'm typing without any selection?

**Comment by nathansobo** [comment]
@gregersrygg It probably doesn't. Would you be interested in playing around with some optimizations? Sounds like some quick wins are available here.

**Comment by gregersrygg** [comment]
I really wish I had time to contribute, but I don't :(

**Comment by nathansobo** [comment]
@gregersrygg That's okay, just investigating things is helpful. One big issue is probably that merging intersection selections is N^2, which doesn't having the greatest scaling properties. We do need to merge them because if cursors overlap they need to be merged.

**Comment by benogle** [comment]
@nathansobo can this be closed for now? I assume the rest of the optimizations will come from the work to fix #307

**Comment by nathansobo** [comment]
It really wasn't complete, but we can reopen it later if you want.

**Comment by nathansobo** [comment]
Wait a minute. The story name in tracker didn't match. This is fine.
