### ISSUE TITLE
Improve app update experience

### ISSUE THREAD

**Issue by benogle** [atom/atom#5166]

**Comment by MayhemYDG** [comment]
http://www.chromium.org/developers/design-documents/software-updates-courgette

**Comment by YuriSolovyov** [comment]
On Windows, there is currenly no update progress vivible anywhere, just discrete values like
- checking
- restart to update

It would be great if you can see download progress, etc.
Update download progress and other update status can be also integared with status bar.

**Comment by mnquintana** [comment]
Same with OS X and Linux – there's currently no visible download or installation progress.

> Update download progress and other update status can be also integrated with status bar.
Ooooh I like this idea. It would be nice and unobtrusive too.

**Comment by amelekhin** [comment]
It would be good if there will be an option to change the installation path on Windows.

**Comment by BinoSam** [comment]
It would be cool to be able to sort in some kind of manner the available packages (like n° of downloads, popularity, ... )

**Comment by stanier** [comment]
:+1:

Linux build needs update support.  Not should have, but *needs*.  I can't emphasize this enough.

**Comment by goroskob** [comment]
Shouldn't Linux version update from repository through distribution's package manager (apt in Debian or Ubuntu, rpm in Fedora etc)?

**Comment by stanier** [comment]
@goroskob, the README.md does not specify an official repository and last I checked, no official build has been pushed to the main package sources.

**Comment by elMauNunez** [comment]
I thought this issue would be solved for 1.0 release. U_U

**Comment by stanier** [comment]
@elMauNunez the disappointment is strong with this one

**Comment by rubencaro** [comment]
An official Atom for Linux repo (one deb and one rpm) would be really nice. An auto updater (just fetch from github and install) may be simpler. Both would work.

+1 for this

**Comment by peduxe** [comment]
@rubencaro [this might interest you](http://askubuntu.com/questions/589469/how-to-automatically-update-atom-editor).

**Comment by rubencaro** [comment]
Nice! That proves that it is actually easy! @peduxe thanks!

**Comment by benogle** [comment]
Closing in favor of https://github.com/atom/atom/issues/9164
