### ISSUE TITLE
opening in a new window option in the new settings interface

### ISSUE THREAD

**Issue by schisma** [atom/atom#5167]
am i blind? on my newest atom version, ran on linux, projects open in a new window. there's an option for disabling that, right?

**Comment by kevinsawicki** [comment]
This behavior hasn't intentionally changed, can you provide some concrete reproduction steps?

**Comment by ix** [comment]
well, i run a x64 arch linux laptop with xfce as the desktop environment. i'm running atom version 0.174.0. everytime i open a new project via the module 'project-quick-open', it opens in a new window.
