### ISSUE TITLE
Panes are not restored correctly after a reload

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#5169]
Often when I reload, my panes are not restored with the right items. Maybe an exception is being thrown during teardown, preventing serialization from completing?

* [x] TextBuffer's history sometimes throws an exception during serialization, probably because `Checkpoints` don't implement `serialize`. atom/text-buffer@bfbee5f503dccc1aedc92ef1142f8cbccdc1021d

**Comment by nathansobo** [comment]
:spaghetti: Nice work.
