### ISSUE TITLE
Atom does not run on RHEL 6.6

### ISSUE THREAD

**Issue by swarnendubiswas** [atom/atom#5172]
The Atom installation page says it supports RHEL. I have installed Atom on RHEL 6.6, and Atom doesn't work. The failed dependencies are with GLIBC_2.14, GLIBC_2.15, and libstdc++. 

/usr/local/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/atom/atom)
/usr/local/share/atom/atom: /lib64/libc.so.6: version`GLIBC_2.14' not found (required by /usr/local/share/atom/libchromiumcontent.so)
/usr/local/share/atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/atom/libgcrypt.so.11)
/usr/local/share/atom/atom: /lib64/libc.so.6: version`GLIBC_2.15' not found (required by /usr/local/share/atom/libgcrypt.so.11)

So does this mean that RHEL 6.6 isn't supported? I have installed gcc 4.6.2 to get around the problem with libstdc++, but now am stuck with the glibc issues. My glibc version is 2.12.

**Comment by ardeshirj** [comment]
Have you tried to install ```glibc-devel``` package? This package is recommended in [build instruction](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md), which shouldn't be required if you are installing from ```rpm``` package, but to just troubleshoot lets see if that is going to help.

If it didn't help, can you use ```yum info``` to send information about ```glibc``` and ```glibc-devel``` versions?

**Comment by swarnendubiswas** [comment]
Glibc-devel is installed, version is glibc-devel-2.12-1.149.el6_6.4.x86_64. It doesn't help.

Here are the details, all are version 2.12.xxx.

Name        : glibc
Arch        : x86_64
Version     : 2.12
Release     : 1.149.el6_6.4
Size        : 12 M
Repo        : installed
From repo   : rhel-x86_64-workstation-6

Name        : glibc-devel
Arch        : x86_64
Version     : 2.12
Release     : 1.149.el6_6.4
Size        : 967 k
Repo        : installed
From repo   : rhel-x86_64-workstation-6

**Comment by ardeshirj** [comment]
Seems like the build version that comes with rpm package is built with glibc 2.14, and that's why it is required by ```libchromiumcontent.so``` and ```libgcrypt.so```. My suggestion is to try to build Atom in your system and see if you still get the same error.

**Comment by jlargent** [comment]
Checked out version v1.0.9 and built on CentOS 6.7
The problem still exists.

/tmp/atom-build/Atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /tmp/atom-build/Atom/atom)
/tmp/atom-build/Atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /tmp/atom-build/Atom/atom)
/tmp/atom-build/Atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/atom-build/Atom/atom)
/tmp/atom-build/Atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /tmp/atom-build/Atom/libchromiumcontent.so)
/tmp/atom-build/Atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/atom-build/Atom/libchromiumcontent.so)
/tmp/atom-build/Atom/atom: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/atom-build/Atom/libgcrypt.so.11)
/tmp/atom-build/Atom/atom: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /tmp/atom-build/Atom/libgcrypt.so.11)

**Comment by Rat-S** [comment]
The issue still exists on RHEL 6.7.

**Comment by makeittotop** [comment]
The issue still exists on Centos 6.6

**Comment by branden-thompson** [comment]
Any updates on this?  Attempting to run atom for me, I encounter this:

`/usr/share/atom/atom: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory`

**Comment by dvasilen** [comment]
Getting the same error on RHEL 6.7

/usr/share/atom/atom: error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory

**Comment by dawnsong** [comment]
Same error here on RHEL 6.8,
Atom 1.12.7 rpi complained `GLIBCXX_3.4.15' not found, which is required by atom and libnode.so

**Comment by kluophysics** [comment]
Same as [dawnsong](https://github.com/dawnsong)

/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/atom)
/usr/share/atom/atom: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /usr/share/atom/libnode.so)

**Comment by mvanportfleet** [comment]
Try this...
https://github.com/atom/atom/issues/13176

I followed it and I am able to open Atom.

**Comment by weiway** [comment]
Any updates? I found some tips suggesting manually updating glibc, but it comes with other issues. Is it possible to build Atom for this specific Redhat version to get it working ( with old glibc )?

**Comment by dm-blue** [comment]
A solution for me (and it still works since two years ago) was to download glibc-2.14.1-6.x86_64.rpm
from <fedora 15> repository and unpack from /lib64 package folder the ld-2.14.1.so, libc-2.14.1.so, libdl-2.14.1.so library files (also their symnlinks) and copy them in the /share/atom folder (I'm using /opt/atom, if that matter). The same thing with libstdc++.so.6.0.16 from libstdc++-4.6.0.fc15.x86_64.rpm from the same repository.
With this solution, atom worked fine until 1.16.x.

**Comment by EdwinHuijsing** [comment]
@dm-blue thank!

I just updated to 1.19.0-beta0 and got the libstdc++ version error.
* I downloaded a newer version of libstdc++
* unpacked it next to the atom directory
* linked the libstdc++.so.6.0.21 with the name libstdc++.so.6 in the path where the atom executable is standing.

Now the all is working.

_Note that use a portable version (atom-amd64.tar.gz) and have atom on my home/<user name>._
