### ISSUE TITLE
Improve tab switching performance

### ISSUE THREAD

**Issue by benogle** [atom/atom#5174]

**Comment by KeitIG** [comment]
The main difference between Sublime and Atom for tab switching, is Atom use "onmouseup" event while Sublime use "onmouseup": 

With Atom, you only switch tab after releasing your finger from your mouse. This is noticeable with the eye.

**Comment by as-cii** [comment]
@benogle: could you provide some more feedback on this, please? I tried opening a ton of files under the same window, and switched tab through `pane:show-next-item`: everything seems quite responsive, though. What am I missing?

Thank you :bow:

**Comment by benogle** [comment]
This was a ticket to look into it -- profile it and see if there is low hanging fruit. Some people were having issues. The recent speedups in the editor may have made things better. And I suspect packages (e.g. https://github.com/atom-community/autocomplete-plus/issues/247) are contributing to some of the slowdown.

**Comment by as-cii** [comment]
:+1: I see. To be honest, I cannot notice any slowdown when switching lots of tabs and, therefore, I assume this issue is mostly related to autocomplete-plus, rather than to Atom itself. 

Shall we keep it anyways, or can we say this was fixed? Thanks :dancers:

**Comment by marcelgwerder** [comment]
How about switching to "mousedown" like @KeitIG mentioned?
All tabs I use daily (Chrome, Nautilus, Firefox, Gimp, Sublime etc.) work that way. 
I think that would definitely help. Or is there already some preparation stuff done on mouse down I don't know about?

**Comment by as-cii** [comment]
> How about switching to "mousedown" like @KeitIG mentioned?
> All tabs I use daily (Chrome, Nautilus, Firefox, Gimp, Sublime etc.) work that way. 
> I think that would definitely help. Or is there already some preparation stuff done on mouse down I don't know about?

--------------------

> The main difference between Sublime and Atom for tab switching is Atom use "onmouseup" event while Sublime use "onmouseup" when clicking a tab.
> 
> With Atom, you only switch tab after releasing your finger from your mouse. This is noticeable with the eye.

@marcelgwerder: as explained by @benogle earlier on, this issue is more about slowdowns experienced while switching tabs. Could you explain how your proposal could impact speed? Moreover, I'd say the behavior you're requesting belongs to https://github.com/atom/tabs, thus you may want to open an issue there.

Thanks for your feedback! :blush:

**Comment by marcelgwerder** [comment]
@as-cii It will not speed up the process itself. It will just feel faster for the user because the switch is already invoked on mousedown. Some quick tests show me a personal difference of ~60ms between mousedown and mouseup. That of course depends on the user but it's a "quick win" if you will.

**Comment by mark-hahn** [comment]
> . It will just feel faster

It's more than feeling faster.  Your eyes see the new tab sooner and can
start doing their thing.

**Comment by mnquintana** [comment]
Resolved in atom/tabs#124 - tabs are quite snappy now.

**Comment by KeitIG** [comment]
@mnquintana 
My PR didn't really improve "tab switching performance", but "tab switching performance feeling"

> @marcelgwerder: as explained by @benogle earlier on, this issue is more about slowdowns experienced while switching tabs
