### ISSUE TITLE
Couldn't load plugin

### ISSUE THREAD

**Issue by skandasoft** [atom/atom#5177]
Hi, When I try to embed something in the view,it is bringing a grey screen with could nt load plugin

![image](https://cloud.githubusercontent.com/assets/9875379/5829053/0e9071dc-a0d2-11e4-9ffc-901a63436f0d.png)

**Comment by kevinsawicki** [comment]
Can you provide the code for the view?

**Comment by skandasoft** [comment]
<object data="abc.pdf" type="application/pdf">
    <embed src="abc.pdf" type="application/pdf" />
</object>

**Comment by skandasoft** [comment]
Please Let me know if you needed any more info
