### ISSUE TITLE
Trouble building on Ubuntu 10.04

### ISSUE THREAD

**Issue by HighCommander4** [atom/atom#5179]
I'm trying to use your instructions here [1] to build Atom on Ubuntu 10.04 (64-bit), but at the "script/build" step I get the following error:

Node: v0.10.35
npm: v1.4.28
Installing build modules...
Installing apm...
npm WARN package.json github-url-from-git@1.1.1 No repository field.
Installing modules ✗
atom@0.174.0 preinstall /exp/builds/atom
node -e 'process.exit(0)'

npm WARN deprecated guid@0.0.10: Please use node-uuid instead. It is much better.
npm ERR! fetch failed https://registry.npmjs.org/reactionary-atom-fork/-/reactionary-atom-fork-1.0.0.tgz
npm ERR! Error: 400 Bad Request
npm ERR! at WriteStream.<anonymous> (/exp/builds/atom/apm/node_modules/atom-package-manager/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR! at WriteStream.emit (events.js:117:20)
npm ERR! at fs.js:1610:14
npm ERR! at /exp/builds/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:105:5
npm ERR! at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR! <http://github.com/npm/npm/issues>

npm ERR! System Linux 2.6.32-70-generic
npm ERR! command "/exp/builds/atom/apm/node_modules/atom-package-manager/bin/node" "/exp/builds/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/exp/builds/atom/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/home/nr/.atom/.apmrc" "install" "--target=0.20.0" "--arch=x64" "--quiet"
npm ERR! cwd /exp/builds/atom
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! /exp/builds/atom/npm-debug.log
npm ERR! not ok code 0

Any ideas as to what I'm doing wrong?

[1] https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

**Comment by maxbrunsfeld** [comment]
Maybe retry? It looks like `registry.npm.js` responded w/ a `400` to a URL that seems to work for me.

**Comment by kevinsawicki** [comment]
> npm ERR! fetch failed https://registry.npmjs.org/reactionary-atom-fork/-/reactionary-atom-fork-1.0.0.tgz
npm ERR! Error: 400 Bad Request

This seems to suggest an npm issue with the server your machine is hitting.

Looks like this sort of this has been reported before, https://github.com/npm/npm/issues/6775

It usually seems to resolve itself once the servers sync again

**Comment by HighCommander4** [comment]
Thanks, re-trying seemed to fix this problem. I am now able to get the 'script/build' and 'script/grunt install' steps to complete successfully. However, when I try to run atom, I get:

/usr/local/share/atom/atom: /lib/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/atom/atom)
/usr/local/share/atom/atom: /lib/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/atom/libchromiumcontent.so)
/usr/local/share/atom/atom: /lib/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/atom/libgcrypt.so.11)
/usr/local/share/atom/atom: /lib/libc.so.6: version `GLIBC_2.15' not found (required by /usr/local/share/atom/libgcrypt.so.11)

**Comment by ricardograca** [comment]
Ubuntu 10.04 is using glibc 2.11.1, and apparently Atom requires at least 2.14.

**Comment by hotice** [comment]
By the way, Ubuntu 10.04 is no longer supported on the desktop, it's only supported on servers (until April, 2015): https://wiki.ubuntu.com/Releases

**Comment by horvan** [comment]
this issue must to b an unity one I have installed gnome-shell and made a build without problems yesterday on Ubuntu 10.04

**Comment by maxbrunsfeld** [comment]
There is already an issue about Atom's `glibc` dependency. I'm going to close this in favor of that one: #2020.
