### ISSUE TITLE
Files missing when you drag a git repo into atom

### ISSUE THREAD

**Issue by AdamKyle** [atom/atom#5181]
Lets assume you have a rails project and one of the files you said for git to ignore is `database.yml` in some cases when you drag a folder from finder (**osx 10.10.x**) to the latest version of atom (I am running **0.174.0** that file instead of being greyed out to show that its apart of git ignore will just not show up at all in the editor, but is in the finder window for that project. This doesn't always happen though, that same project might be dragged into a new instance of the editor and the file might appear.

**Comment by maxbrunsfeld** [comment]
I can't reproduce this yet. Can you tell anything else about when this happens and when it doesn't?

**Comment by AdamKyle** [comment]
The only thing I can add is that it was happening today. In mac I do the following, with a git repository that has a set of known files to be ignored:

Open atom
Open Finder
Find Project, drag the projects directory into atom.

Lets assume your git ignore has `database.yml`, for me specifically. on 10.10.1 of OSX  running the latest build of Atom, this file exists in finder - but does not show up in the editor window any where. In fact I have found all my files that are ignored by a git ignore, when the project is dragged into atom  - they do not show up, when they use to be greyed out.

**Comment by benogle** [comment]
I cant reproduce this either with your steps. It shows the gitignored things as greyed out. Can you check your tree-view settings for me? What is hide ignored names set to? (packages tab in settings, search for tree-view, click settings) 

![screen shot 2015-01-22 at 9 38 38 am](https://cloud.githubusercontent.com/assets/69169/5860991/7cc0b0f6-a21a-11e4-8348-afbc69199a96.png)

**Comment by AdamKyle** [comment]
its actually oddly set. The Hide VSC ignored files is checked off, accept I never checked it oO is this on by default? It might explain so much.

**Comment by benogle** [comment]
Did you ever paste anything into your config file? Maybe some package messes with it?

**Comment by AdamKyle** [comment]
I never knew there was a cofig file. And the only packages I have is editor config, which i use to set  up indentation for different file types. I do have a couple that help you add syntaxt support for react js and php (advanced features for php) but nothing that would touch the file tree.

Odd indeed

**Comment by kevinsawicki** [comment]
There is a keybinding to toggle this setting, https://github.com/atom/tree-view/blob/ac7d9a10834a24a50594b33e331c540ce21d6c05/keymaps/tree-view.cson#L48

Perhaps you hit `i` by accident when the tree view was focused?

**Comment by AdamKyle** [comment]
quite possibly yes, there are times when I change a file name and fail at typing. I should change this key binding. Thank you very much good sir.
