### ISSUE TITLE
Can't open and view readonly files / Must have write access to be able to open file

### ISSUE THREAD

**Issue by perzi** [atom/atom#5183]
Platform: MacOS 10.10.
Atom: 0.174.0

Trying to open a readonly file shows an error: "Permission denied '<Path to file>'". It was possible to open readonly files before. The change was introduced some version ago. 

Steps to reproduce: 
1. In terminal, change access permission to read only with "chmod 444 <filename>"
2. Try to open file in atom

**Comment by 50Wliu** [comment]
This will be fixed in the next Atom version.
