### ISSUE TITLE
Editor window is blank after switching tabs

### ISSUE THREAD

**Issue by entepe85** [atom/atom#5187]
When using Atom for a while and editing a single file within a project and then switching tabs to a different file the editor window is blank until it is scrolled, then the content of the current tab is rendered correctly.

Atom Version 0.174.0 on OSX 10.10.1.

**Comment by maxbrunsfeld** [comment]
Does this happen if you ran Atom with `--safe`?

**Comment by benogle** [comment]
I see this every now and then as well. Next time, I will stop and debug it.

**Comment by entepe85** [comment]
Unfortunately, as this happens rather sporadically, I haven't had the chance to check if the issue persists while Atom is run in safe mode - mainly because I need most of the additional packages for my production environment.

**Comment by benogle** [comment]
This is legit. I saw this ~10 times yesterday. It's impossible to debug, though. Anytime I touch the editor, it comes back. 

It seemed to happen with the following:

* Have multiple tabs
* Resize the editor
* Switch to a different tab
* Editor is blank

Though reproducing is not consistent. I was using the one light theme.

**Comment by kevinsawicki** [comment]
Yeah, I saw this a bunch yesterday too, I was using the default themes.

**Comment by nathansobo** [comment]
:eyeglasses: now.

**Comment by nathansobo** [comment]
@benogle  What percentage of the time can you reproduce this? I can't reproduce it even once.

**Comment by benogle** [comment]
I unfortunately dont have a good metric.

**Comment by benogle** [comment]
Ok, try this:

* have 3 tabs open
* split one of them
* close the split
* split again!
* focus on the previous pane
* select a different tab
* blank

This is like 50% reproducable for me

**Comment by benogle** [comment]
![screen shot 2015-01-22 at 10 15 01 am](https://cloud.githubusercontent.com/assets/69169/5861589/8c28ac88-a21f-11e4-9b38-1b12235efea9.png)

Pretty consistent for me

**Comment by nathansobo** [comment]
@benogle Nice. I got it.

**Comment by nathansobo** [comment]
Found the issue. Working on test coverage for the fix.
