### ISSUE TITLE
[Idea] Tabs

### ISSUE THREAD

**Issue by ghost** [atom/atom#5188]
Idea is to delete from DOM unfocused tab container as it made with main editor lines, so it's allow to boost atom performance a lot, less nodes = better speed.

**Comment by YuriSolovyov** [comment]
adding/deleting nodes in not free, so I doubt this will improve anything, it also can increase lag for tab switching

**Comment by mehcode** [comment]
However.. perhaps if used as a paging system when a *threshold* number of tabs were open. That could improve overall responsiveness if a user has 50 tabs open.

**Comment by wmertens** [comment]
A bit like https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg - when done right it's not annoying and it does save quite a few resources

**Comment by vanesyan** [comment]
@YuriSolovyov But editor lines uses the same way of adding/deleting nodes, thus it can processing a lot of code-lines without lagging...

**Comment by vanesyan** [comment]
Also React optimizes way of (un)mounting nodes

**Comment by kevinsawicki** [comment]
Closing this out, tiled rendering is now done and a more performant editor component now exists and react is no longer used.
