### ISSUE TITLE
replace 4 spaces with a tab(key) not working

### ISSUE THREAD

**Issue by Cipa** [atom/atom#5190]
Hi,

just tried replacing 4 space with a tab in a file, just to make the formatting consistent and it did not work

Steps to reproduce
1. ctrl + f
2. paste/put in 4 spaces in the first box
3. paste a tab in the second box(just copy paste a tab from the edited file)

Click replace

result: 4 spaces are replaced by 2 spaces not by a tab

**Comment by 50Wliu** [comment]
What version of Atom are you using?
Can you reproduce this using safe mode (`atom --safe`)?

**Comment by Cipa** [comment]
latest one 0.175.0 seems to work
I swear I restarted a few times on 0.174.0, maybe related to #5192

Closing, will reopen if needed
