### ISSUE TITLE
can't copy a tab and paste on a new line

### ISSUE THREAD

**Issue by Cipa** [atom/atom#5191]
![screen shot 2015-01-21 at 12 19 47 pm](https://cloud.githubusercontent.com/assets/293377/5841041/cfc34204-a167-11e4-88f9-6b3c112e75d8.png)

Try copying a tab and pasting

**Comment by 50Wliu** [comment]
Works fine for me-what are you seeing?

**Comment by Cipa** [comment]
seems to work now, maybe it was somehow related to #5192
