### ISSUE TITLE
Gracefully suggest user to install git

### ISSUE THREAD

**Issue by flannelhead** [atom/atom#5193]
I was trying out Atom on Windows, where I don't have git installed. I tried to install vim-mode, but the installation failed with the error code ENOGIT. In the installation log there was an error message much like that in https://github.com/atom/atom/issues/4030 

If the user actually reads the failure log, it'll become quite obvious that they need to install git / put it in their %PATH for the installation to succeed. However, I think it would be better (if possible) to notify the user about the need to install git with a dialog, for example. Another option would be to have a text "git is required to install this package" next to the package in the GUI.

Edit: of course the very simplest way would be to say somewhere on the download page, or in the installer, that installing git is required.

**Comment by philipgiuliani** [comment]
@benogle something new for the notifications probably :)

**Comment by mark-hahn** [comment]
I missed the beginning of this thread. Why not just install git
transparently?  That is how Node is installed

**Comment by mnquintana** [comment]
Related to atom/apm#236
