### ISSUE TITLE
Multiple tab regressions

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#5198]
I just upgraded to 0.174.0 from 0.172.0 today using Webupd8's PPA.
The 'x' button in each tab seems to be missing, and it therefore makes closing tabs much more difficult (now you have to right-click the tab you want to close and click `Close Tab`).

Replicated on Ubuntu 14.10, Atom 0.174.0, safe mode.  I don't think a picture is needed, but if you want one, just tell me.

**Comment by 50Wliu** [comment]
The blue circle that indicates that a file has been modified also does not appear.

**Comment by idenkov** [comment]
I have the same bug. 
Ubuntu 14.04 x64 Atom 0.174.0 from the http://www.webupd8.org/ ppa

**Comment by Qard** [comment]
Same here.

**Comment by idenkov** [comment]
I just saw they have version 0.175.0 released, after I jumped on the report. Will give it a go to see if I am still getting this bug.

**Comment by idenkov** [comment]
Version 0.175.0 fix this bug. Please update manually from here. I have done this before and haven't any issues using the webupd8 ppa after that, so you should be safe.
I guess someone can close the ticket?

**Comment by 50Wliu** [comment]
So this just happened:
![Oh noes even more](https://cloud.githubusercontent.com/assets/2766036/5847094/86d48a8c-a197-11e4-8612-e58f8fbceb4b.png)
Not sure if this is the same bug, but I can't even switch tabs now without clicking on the file I want in the tree view.  Closing any tab other than the `language-` tab (which should be `language-sourcepawn.coffee`) is impossible.

**Comment by 50Wliu** [comment]
So I'm just going to keep adding onto this (hopefully I'm not doing this for nothing if it's already been fixed in 0.175 :P):
Attempting to move a tab by clicking-and-dragging it results in the title of the tab getting selected.
![image](https://cloud.githubusercontent.com/assets/2766036/5847202/92d0408c-a198-11e4-90d3-e1ffe5948d60.png)
:cry:

**Comment by idenkov** [comment]
@50Wliu Just upload to 0.175 - this bugs are not presented there.

**Comment by benogle** [comment]
What themes do you all have?

For the one theme, can you pull down the latest master?

This is fine for me on the latest master.

**Comment by 50Wliu** [comment]
Looks like it's a bug with just 0.173-0.174 then?  Odd.
I'm already on the latest master of One-light, and I also tested with both Atom Dark and Atom Light in safe mode.  Syntax theme is Fizzy (which is arguably pretty outdated) and Atom Light Syntax in safe mode.

**Comment by mthadley** [comment]
I'm also seeing this on Atom `0.175`. This is on Ubuntu 14.10:

![selection_002](https://cloud.githubusercontent.com/assets/2635560/5860561/f85d1f00-a216-11e4-8caf-f9da50af8508.png)

There seems to be some extra bottom margin on the `.tab-bar` as well. This is with the atom-dark-ui theme, but I'm also seeing it on other themes as well.

**Comment by benogle** [comment]
@mthadley how did you install atom?

**Comment by benogle** [comment]
Is anyone here _not_ on linux?

**Comment by mthadley** [comment]
I installed Atom using the webupd8 PPA.

**Comment by Qard** [comment]
Yep. We're all linux users using the webupd8 ppa. I too fixed it by installing the latest package manually.

**Comment by 50Wliu** [comment]
Ok, then I'm going to assume it's a packaging issue.
Hopefully it gets resolved by the time they update to 0.175.0.

**Comment by benogle** [comment]
cc @hotice this issue seems to be limited to the webupd8 ppa

**Comment by Qard** [comment]
It's back.

The problem seemed to go away when I install 0.175.0, but it randomly returned when creating a new file and seems to be persisting even after closing the app and restarting it.

**Comment by idenkov** [comment]
Ok, it is back after I updated to version 0.175 from the webupd PPA.
So I think it is some packaging bug related just to the webupd PPA.
There wasn't way to open a ticket on Launchpad so I contacted the maintainer trough e-mail and linked him to this thread.
Hopefully he will check it out soon.

**Comment by hotice** [comment]
I can't think of a reason why it could be related to my packaging, I just build it using the official instructions. Any ideas? Maybe the official debs are built in a different way, with a different set of packages or something?

**Comment by hotice** [comment]
I removed the ~/.atom folder and I can't replicate this issue any more (the close button/circle is always displayed). Can you guys please rename ~/.atom to something else (so you don't lose your settings), open Atom and try to replicate it? I too installed the official debs, then Atom from the PPA and I think that maybe somehow installing Atom from both sources messes with the settings.

**Comment by seb2411** [comment]
@hotice I purge your version and installed the .deb from the website without removing .atom  and is working fine for me now. (Some dependency problem ?)

**Comment by hotice** [comment]
@seb2411 what I mean is, rename ~/.atom and try Atom from the WebUpd8 Atom PPA. Does the issue still occur in this case?

**Comment by seb2411** [comment]
@hotice I will test it later today and I say you.

**Comment by seb2411** [comment]
@hotice so I purge the Atom from the website (apt-get purge atom). I move my .atom folder and I install again Atom from your PPA. Everything seem to work. So I move bit by bit the content of my old .atom folder in the new one (testing each time) and I don't have the problem... So it's ok for me. Strange.

**Comment by hotice** [comment]
Thanks for testing it! I've also tried to replicate it again with no success, even installing older versions, upgrading, etc. It's just fixed all of a sudden.

**Comment by hotice** [comment]
The only explanation that I could think of is that some Atom files were renamed and there were some leftovers in /opt/atom and for some reason, Atom tried to load them, causing this issue. So I added a preinst script to the deb packages that clean up /opt/atom before installation/upgrades. I've also updated the 64bit package to use the official binary, just to make sure.

But, like I said, even after installing an older Atom version and upgrading, I couldn't replicate the issue so I can't test this myself. So if you were affected by this, please try the latest PPA build ("0.175.0-1~webupd8~2" - make sure you're running the version with "2" at the end) and let me know if it's fixed. Thank you and sorry for this issue!

**Comment by seb2411** [comment]
Ok Thx you. ;-)

**Comment by 50Wliu** [comment]
Confirmed fixed.  Thanks!
