### ISSUE TITLE
Atom hangs while trying to access networked paths

### ISSUE THREAD

**Issue by LouisTakePILLz** [atom/atom#5199]
As mentioned in the title, Atom hangs while switching to a tab wherein the opened file is no longer accessible (in my case, from a network drive which I had lost connection to).

Is this a known issue?
This is perhaps related to issue #1766.

**Comment by 50Wliu** [comment]
What Atom version are you running?
This *may* have been fixed in recent versions.

**Comment by LouisTakePILLz** [comment]
I'm on version 0.174.0.

**Comment by kevinsawicki** [comment]
> This may have been fixed in recent versions

I don't think so, I don't believe the recent filesystem error improvements didn't deal with this issue specifically.

**Comment by thedaniel** [comment]
Is this still an issue?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/5199#issuecomment-150210576. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
