### ISSUE TITLE
Atom saving workspace issue.

### ISSUE THREAD

**Issue by ubilli** [atom/atom#5203]
i am just new to atom, i use sublime a lot, but because of it paid version i am coming to atom, but i want to see most functionality on sublime, like saving workspace for next time usage, correct me if i am wrong, if this feature is available. and please show me how to do it on my atom or if i have to install a package. Opps!!! i forgot my OS is Ubuntu 14.04 LTS. thanks

**Comment by sadovnychyi** [comment]
https://github.com/atom/atom/issues/5168

**Comment by mnquintana** [comment]
Which feature do you mean exactly? Do you mean per-project config settings like in #5168 (e.g. `.sublime-project` files), or do you mean Sublime remembering your workspace state when you quit? If it's the latter, you should check out [save-session](https://atom.io/packages/save-session).

**Comment by ubilli** [comment]
I mean the save session for next time usage.

**Comment by mnquintana** [comment]
Then I think [save-session](https://atom.io/packages/save-session) will do what you're looking for.

**Comment by benogle** [comment]
Closing in favor of #1603

**Comment by denieler** [comment]
To save few sessions\workspaces you can use plugin [save-workspace](https://atom.io/packages/save-workspace)
