### ISSUE TITLE
Search in Directory won't find line breaks (\n)

### ISSUE THREAD

**Issue by promythyus** [atom/atom#5204]
Put a file that has line breaks in a directory, eg. 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<foo>
  <bar>hello world</bar>
</foo>
```

Right click the directory and select "Search in Directory". Turn regex on and enter \n in the search input, and perform the search. No results will be found.

If you search the file in the buffer (eg. ⌘-F) and search for \n with regex on, the line breaks will be found.

Fresh Install of OS X 10.10, running Atom 0.175.0. Files in question are definitely using Unix line endings.

**Comment by benogle** [comment]
Sorry about that. It's being tracked over at https://github.com/atom/scandal/issues/5
