### ISSUE TITLE
Bundle Git with Atom

### ISSUE THREAD

**Issue by karai17** [atom/atom#5206]
I feel like Atom should come with everything needed to make it work. This includes Git for installing packages (arguably the most important feature of Atom). When you try to install a package without Git, it throws a pretty useless and confusing error. I think Atom should check to see if Git is installed, and if not, prompt the user to install it along side Atom.

**Comment by mnquintana** [comment]
Related to (maybe duplicates of) atom/apm#236 and #5193

**Comment by kevinsawicki** [comment]
Yeah, closing as duplicate of those two @mnquintana linked to.
