### ISSUE TITLE
Alt + F and Alt +H not working to open menu on windows

### ISSUE THREAD

**Issue by adrien59cadri** [atom/atom#5207]
hello

I often use my keyboard to access menus of the editor,
I installed atom yesterday and like it, thank you!

But I doscovered this morning that I can't open menus on Windows 8.1 using the shortcuts Alt+H and Alt +F.
stangely the other menus work fine (find, edit, packages and selection)

**Comment by 50Wliu** [comment]
Duplicate of #4808, please subscribe there for updates.
