### ISSUE TITLE
restart and install update restarts lost 1 window

### ISSUE THREAD

**Issue by adrien59cadri** [atom/atom#5212]
I used the install and update button,

(but I did not know I was already in the latest version, so this should not have been available I guess)

I had 2 Atom windows open,
1 reopened well,
The second reopened showing the folder app-0.174.0 with the DLL inside
![untitled](https://cloud.githubusercontent.com/assets/536398/5856748/3a931058-a246-11e4-9f50-46ae6cd80e6c.png)
And I'm still in 0.174.0 (which is normal)

**Comment by 50Wliu** [comment]
I can confirm when I upgraded to 0.174.0 on Windows (refs #4653).

**Comment by cthielen** [comment]
This might be a separate issue but on the Mac when I "Install & restart" a new Atom from the menu, Atom always closes all windows and re-opens a new blank one. I don't get my original window back.

**Comment by 50Wliu** [comment]
@cthielen that's #1603.

**Comment by damieng** [comment]
One part of this is covered by #1603 and the other (button not available when it should be) has I think been fixed (not able to repro).
