### ISSUE TITLE
Packages not finding updates

### ISSUE THREAD

**Issue by stramel** [atom/atom#5213]
### Versions
**Atom:** 0.176.0-f7ecc3e
**OS:** Ubuntu 14.04
**settings-view:** 0.174.0

When going to the "Updates" section of "Settings", it says "All of your installed packages are up to date!". I have friends who are seeing packages updating. They are running previous versions of Atom ~0.173.0 on Linux. I also know for a fact there are updates, ie: `Linter` my current version is `0.10.0` and the newest version is `0.10.1`. I'm not sure what happened or when, but I have not received any updates for a few days now at least.

Issue still occurs when attempting `atom --safe` and `sudo atom`

**Comment by kevinsawicki** [comment]
If you run `apm upgrade` from the command line, does it show any?

**Comment by stramel** [comment]
@kevinsawicki Would it be affected by the fact I had been testing a package I've been developing through the same atom?

```console
$ apm upgrade
Package Updates Available (0)
└── (empty)
```

**Comment by kevinsawicki** [comment]
> Would it be affected by the fact I had been testing a package I've been developing through the same atom instance?

It shouldn't be, unless that package is linter.

So if you run `apm list`, you see `linter@0.10.0` in the output?

**Comment by stramel** [comment]
> It shouldn't be, unless that package is linter.
Haven't messed with linter at all.

```console
$ apm list
Built-in Atom packages (79)
├── archive-view@0.44.0
├── ...
└── wrap-guide@0.31.0

/home/stramel/.atom/dev/packages (1)
└── Atom-Music@0.0.10

/home/stramel/.atom/packages (23)
├── angularjs@0.1.0
├── atom-beautify@0.21.2
├── atom-color-highlight@3.0.4
├── atom-jasmine@0.5.0
├── atom-monokai-dark@0.4.0
├── autoclose-html@0.13.0
├── autocomplete-paths@0.9.1
├── autocomplete-plus@1.1.0
├── autocomplete-snippets@0.3.2
├── editorconfig@0.3.0
├── file-icons@1.4.6
├── highlight-line@0.9.3
├── highlight-selected@0.7.0
├── linter@0.10.0
├── linter-jscs@1.4.9
├── linter-jshint@0.1.0
├── linter-less@0.3.1
├── lodash-snippets@1.1.0
├── monokai@0.9.0
├── pain-split@1.1.2
├── peacock-syntax@1.2.2
├── project-manager@1.14.1
└── project-palette-finder@2.4.9
```

**Comment by jbt** [comment]
I'm seeing this too, exactly same atom version (also, just checked and still happening built straight off master 0.176.0-4baea35), ubuntu 14.04 too if that's relevant.

Couple of other things I managed to find:
 * `apm install packagename@version` seems to work fine to install updated versions of the packages that aren't seeing updates, but...
 * `apm install packagename` without explicit version fails with `No available version compatible with the installed Atom version: 0.176.0-f7ecc3e`

Could it be somehow to do with the [updated semver version](https://github.com/atom/apm/commit/86aa7e0fff85cc2343211a8b91921a7eac2ed558) in apm a week or so ago, getting confused by the `-f7ecc3e` appended to the end of the version?

**Comment by kevinsawicki** [comment]
> Could it be somehow to do with the updated semver version in apm a week or so ago, getting confused by the -f7ecc3e appended to the end of the version?

Totally could be, thanks for the tip, will check into that now.

**Comment by jbt** [comment]
Further digging shows this which I guess is what's breaking stuff (I chucked a few logs in my apm install getLatestCompatibleVersion and `>0.50.0` is what it's trying to satisfy):

```
> require('npm/node_modules/semver').satisfies('0.176.0-aaaaaa', '>0.50.0')
false
> require('npm/node_modules/semver').satisfies('0.176.0', '>0.50.0')
true
```

(run from in my apm dir, reason for `npm/node_modules/semver` rather than just `semver` is because [that's what it is in apm's install.coffee](https://github.com/atom/apm/blob/071475e9a24f8a5f6c8ed943a58e719f48efc219/src/install.coffee#L7), although I'm not sure why)

**Comment by stramel** [comment]
@jbt great work! :+1:

**Comment by kevinsawicki** [comment]
Thanks @stramel for reporting this and @jbt for the insight, should be fixed on master now.

**Comment by jbt** [comment]
Confirmed (well, for me at least), woop! :+1:

**Comment by stramel** [comment]
@jbt @kevinsawicki Thank you both! :+1:
