### ISSUE TITLE
Using "Show in Explorer" command on a folder in the treeview does not show the complete folder path on Windows

### ISSUE THREAD

**Issue by Tareck117** [atom/atom#5218]
Description : It is not possible to navigate easly in the windows explorer when using the "Open in explorer" command in the Atom Tree view on Windows.

To test : 
Create a folder with a text file in it.
Right click > Open with Atom
In the tree view, click on "Open in explorer"
http://i.imgur.com/NUNUBYA.png

*To compare, click on the path at the top of the window that just opened, and copy & past it into a new window explorer*

You can see from the following image that the explorer that Atom opened (left one in the printscreen) does not show all the path and that you can not click on the previous button either.

http://i.imgur.com/tbe0n8y.png

Because of that behavior, it is difficult to navigate in windows that Atom opens.

**Comment by zephraph** [comment]
+1

I have to deal with this all the time at work.

**Comment by Tareck117** [comment]
@zephraph Probably, I did not check the other atoms projects so I did not know it existed. Maybe we can move it there.

**Comment by zephraph** [comment]
@Tareck117, close this issue and see my pull request. This is a tree-view issue.

**Comment by Tareck117** [comment]
@zephraph Perfect. Thank you very much
