### ISSUE TITLE
Add about the team page to atom.io

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#5223]
I would like to see an "about us" page on atom.io.  It should have a photo and short bio for every core team member along with primary responsibilities.  Many consider these public relations junk but I for one would like to see faces on the people that have such a big impact on Atom.  I think this would put a human face on the project and make it more welcoming.

Also a brief history of Atom, motivation for creating Atom, and a vision for the future would be nice.

Normally on an open-source project it would be hard to pick out contributors to be considered "core" but here it would be any github employee assigned to Atom.

**Comment by Trudko** [comment]
+1

**Comment by mnquintana** [comment]
:+1:

**Comment by thedaniel** [comment]
Thanks for the suggestion, this is a good idea. We'll add it to our list of site enhancements, though it probably won't happen for a while.

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#20
