### ISSUE TITLE
Select menu flashes white when opening and closing in settings-view (Linux and Windows)

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#5224]
(I'm opening this here instead of in [settings-view](https://github.com/atom/settings-view) because I suspect this is a bigger issue than just settings-view.)

**OS:** Ubuntu 14.04.1 LTS
**Atom:** 0.175.0

Whenever you you open or close a `select` in Settings it briefly flashes white, which can be kind of jarring. I've never experienced this on my Mac running Yosemite, so I suspect it's a Linux issue (which I can find out for sure when I go home and test on my VMs). This happens regardless of theme and in safe mode as well.

![screencast](https://cloud.githubusercontent.com/assets/823545/5865577/896c8a62-a258-11e4-9024-b950627cea1e.gif)

**Comment by mnquintana** [comment]
**UPDATE:** Reproduced on Ubuntu 14.10 too.

**Comment by mnquintana** [comment]
**UPDATE:** Reproduced in Windows 8.1 too.

**Comment by damieng** [comment]
Still repros. Looks like CSS applied after the drop-down?  Not sure why that would occur.

**Comment by PapsOu** [comment]
I'm experiencing the same problem on drop-down, and generally on whole atom screen randomly.
