### ISSUE TITLE
workspaceView.eachEditorView does not seem to subscribe to future views

### ISSUE THREAD

**Issue by joeferraro** [atom/atom#5226]
Mac OS X 10.10.1
Atom 0.172.0

I have some extremely basic code to subscribe to current and future WorkspaceViews:

```
atom.workspaceView.eachEditorView (editorView) ->
  console.log ' ------> editorView handler!'
``` 

This has worked in previous versions of my package, but in 0.172.0, I get a single log statement when Atom opens (if I have an open editor view), then no future log statements in the console as editor views are opened. I've tried moving these 2 lines of code around in my package to figure out whether there was perhaps a silent error somewhere, but no luck. Also, no errors in the console whatsoever. Any ideas?

Cheers

**Comment by mark-hahn** [comment]
Does this happen in safe mode?

**Comment by benogle** [comment]
You really should be using `atom.workspace.eachTextEditor` as editor views are going away.

**Comment by joeferraro** [comment]
@benogle do you mean `atom.workspace.eachEditor`?

**Comment by benogle** [comment]
Sorry for the misinformation. You should use [`atom.workspace.observeTextEditors`](https://atom.io/docs/api/v0.175.0/Workspace#instance-observeTextEditors)
