### ISSUE TITLE
Uncaught Error: spawn /usr/share/atom/atom (deleted) ENOENT

### ISSUE THREAD

**Issue by storozhukBM** [atom/atom#5232]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.13.0-44-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /usr/share/atom/atom (deleted) ENOENT

```
At events.js:85

Error: spawn /usr/share/atom/atom (deleted) ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1047:32)
  at child_process.js:1138:20
  at process._tickCallback (node.js:386:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 17,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
language-rust, v0.3.5

# Dev
No dev packages
```

**Comment by Moter8** [comment]
Similar to #4505 I guess?

Please fill out the steps you followed before the bug appeared.

```
[Enter steps to reproduce below:]

1. ...
2. ...
```

**Comment by cardimajs** [comment]
i have the same problem

**Comment by benogle** [comment]
Can either of you post steps to reproduce this over at #4505?

Does it happen when updating / rebuilding atom with an atom window open?

**Comment by ljbade** [comment]
Happening for me.

I just opened a second folder with another window open with another folder open.

Happens everytime I open a file in the new window.

**Comment by Moter8** [comment]
@ljbade Please post this at #4505 instead, please also include the atom version and the OS version you are on!

**Comment by ljbade** [comment]
@Moter8 you should get atom to point to that issue instead of this one.

**Comment by benogle** [comment]
The notification looks for a title match people of different linux flavors are getting different paths for this issue.
