### ISSUE TITLE
Feature Request: Make package updates automatically happen in the background

### ISSUE THREAD

**Issue by amingilani** [atom/atom#5236]
Since I don't need to visit the settings page often, I often find my packages out of date. Automatic package updates in the background will ensure that.

I would recommend this by default, but there should at the very least be a setting to opt-in.

**Comment by steelbrain** [comment]
+1 because a lot of people don't even pay attention to the bottom bar. and never update their packages. (or they're new to atom)

**Comment by steelbrain** [comment]
I am not sure if Atom is implementing this in core any time soon, So I am gonna create a package for it.

**Comment by steelbrain** [comment]
@amingilani Check out [Package-Upgrader][1].

[1]:https://github.com/steelbrain/Atom-Package-Upgrader

**Comment by amingilani** [comment]
I think this addresses the issue! thank you steelbrain! :smiley:
