### ISSUE TITLE
package upgrade failure stops all following upgrades

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#5237]
I have 11 packages waiting to be upgraded.  My first one is throwing an exception and the whole process dies.  This means until I solve the problem with the first one all others will have to wait.

I will uninstall the offending package for now but this should be fixed.

**Comment by mark-hahn** [comment]
windows 8.1
apm  0.123.0
npm  2.1.18
node 0.10.35
python 2.7.8
git 1.7.11.msysgit.1
visual studio 2013

**Comment by kevinsawicki** [comment]
Are you upgrading from within Atom or via `apm` on the command line?

**Comment by mark-hahn** [comment]
command line
