### ISSUE TITLE
Specific pane manipulation prevents panes from being deleted.

### ISSUE THREAD

**Issue by chemoish** [atom/atom#5239]
Atom 0.175.0
Mac OSX 10.10.1

When I split Panes in a window-like fashion.... Image 1

```
panes = atom.workspace.getPanes()
panes[0].splitDown()
panes[0].splitRight()
panes = atom.workspace.getPanes()
panes[2].splitRight()
```

Then open a untitled document in the 4th window.... Image 2

Then add and remove Panes until it changes to a horizontal layout.... Image 3

```
for pane in atom.workspace.getPanes()
  pane.destroy() if pane.getItems().length is 0
```

Then I can no longer remove Panes.... Image 4

Will continue to investigate incase this is a fault on my behalf.

---

For further details on pane manipulation: https://github.com/chemoish/atom-pane-layout

![screen shot 2015-01-23 at 7 45 28 pm](https://cloud.githubusercontent.com/assets/549319/5886035/d11cdec6-a338-11e4-9cc1-b3ab0e56c750.png)
![screen shot 2015-01-23 at 7 45 31 pm](https://cloud.githubusercontent.com/assets/549319/5886036/d3614b68-a338-11e4-8566-e795f3f4de74.png)
![screen shot 2015-01-23 at 7 45 35 pm](https://cloud.githubusercontent.com/assets/549319/5886037/d7bec668-a338-11e4-9410-562afeea7b1c.png)
![screen shot 2015-01-23 at 7 45 45 pm](https://cloud.githubusercontent.com/assets/549319/5886038/db8d2bfe-a338-11e4-8eb8-64ed195e2430.png)

**Comment by jonathandelgado** [comment]
+1

**Comment by chemoish** [comment]
I also noticed that if you delete the view before you delete the pane. It creates a slightly different error than above (Same error, but relates to the siblings rather than the pane which the untitled document is assigned).

```
atom.views.getView(atom.workspace.getPanes()[4]).remove()
atom.workspace.getPanes()[4].destroy()
```
