### ISSUE TITLE
Expose atoms version of prebuild atom-oniguruma

### ISSUE THREAD

**Issue by orktes** [atom/atom#5241]
Hi,

I'm currently maintaining a grammar extension (react) for atom. I was first using atom-oniguruma for regular expressions, but ended up dropping it as a dependency for the package as building it caused problems for windows users. As a workaround I had to leverage how LanguageMode creates OnigRegExp instances for patterns trough the config apis https://github.com/atom/atom/blob/master/src/language-mode.coffee#L319. This is really hackish and causes the config keys and values to appear in the package settings page.

``` javascript
// when plugin is activated
atom.config.set("react.decreaseIndentForNextLinePattern", decreaseIndentForNextLinePattern)

// And then
decreaseNextLineIndentRegex = languageMode.getRegexForProperty(scopeDescriptor, 'react.decreaseIndentForNextLinePattern')
```

Would be nice if native atom utility packages could be exposed trough the atom global variable (atom.utils etc.) or if you have other suggestions on how to use atom-oniguruma without causing problems for windows users.

Thanks!

**Comment by kevinsawicki** [comment]
What were the problems that people on Windows were seeing?

**Comment by orktes** [comment]
Mostly problems with node-gyp (i.e. building the native code). Some of the reports are listed here https://github.com/orktes/atom-react/issues/19
