### ISSUE TITLE
How to search and jump to IDs in HTML?

### ISSUE THREAD

**Issue by CaptSaltyJack** [atom/atom#5244]
I tried Cmd-Shift-R, but that didn't seem to find this in my current HTML file:

    <section id="dropin">
      ...
    </section>

I can't seem to figure it out from the documentation.

**Comment by mnquintana** [comment]
You might have better luck asking in the [Atom support forum here](https://discuss.atom.io/) – generally support questions are a better fit for Atom Discuss than GitHub Issues.

**Comment by CaptSaltyJack** [comment]
Ah, sorry. Thanks!
