### ISSUE TITLE
Expected "-" or [^\-] but end of input found.

### ISSUE THREAD

**Issue by Narven** [atom/atom#5245]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Expected "-" or [^\-] but end of input found.

```
At undefined

undefined
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
CoffeeCompile, v0.5.1
command-logger, v0.20.0
project-manager, v1.14.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by Narven** [comment]
Yes, i get the exactly the same error.

**Comment by Narven** [comment]
actually at this point of downloading and instaling on my mac, and try... cant see anything.. nothing works... the only thing it works is the settings options when press cmd + ,

other than that, to me is a completly useless piece of code...

**Comment by mmares** [comment]
had the same issue, it was an invalid entry inside the keymap.cson file

**Comment by kevinsawicki** [comment]
Closing this out, I believe this issue has been resolved with several custom error handlers added to startup and also changes made to the notifications package.

Please comment if you are still seeing this issue on Atom 1.0.5+.
