### ISSUE TITLE
Bug: Regex breaks Syntax Highlighting.

### ISSUE THREAD

**Issue by ryardley** [atom/atom#5247]
In Atom Version 0.175.0 (0.175.0) Mac OSX
language-javascript version 0.55.0

The following when placed in a javascript file should be legal but breaks syntax highlighting:

```javascript
// Regex from http://blog.stevenlevithan.com/archives/parseuri
var myobj = {
  strict: /^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,
};
console.log('This is all yellow.');
// And so is this!
```

![screen shot 2015-01-25 at 11 17 05 am](https://cloud.githubusercontent.com/assets/1256409/5889590/c21c94f6-a483-11e4-88ac-ee444dcc3ee0.png)

This also does a similar thing:
```javascript
// Regex from http://blog.stevenlevithan.com/archives/parseuri
var myobj = {
  loose:  /^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/
};
console.log('This is all green/blue.');
```

![screen shot 2015-01-25 at 11 19 36 am](https://cloud.githubusercontent.com/assets/1256409/5889602/6d19af9c-a484-11e4-9208-5a9f3b022c89.png)

**Comment by 50Wliu** [comment]
This is not related to regex-rather, you just have too long a line for Atom to handle at this point in time.  See #1667 for details.
