### ISSUE TITLE
atom.packages.packageStates is empty

### ISSUE THREAD

**Issue by skandasoft** [atom/atom#5252]
The atom.package.packageStates is empty object when I open a folder. Keeping it open If I open the folder again it is able to load the atom.package.packageStates.

**Comment by benogle** [comment]
What are you trying to do? `atom.package.packageStates` is not public and not a supported API.

**Comment by skandasoft** [comment]
when closing atom I serialize the state and when atom is opened again with blank page..and change to the my folder, i don't get the state back. I had to reopen the same folder again and I get the state back. I debugged I found that the packageStates is empty

**Comment by benogle** [comment]
Ok, so my assumption of the steps is this:

1. open atom with a folder: `atom my-folder`
1. do things in package
1. close atom; state is serialized by the package's `serialize` method
1. open atom, but without pointing to a specific directory
1. package's `activate()` method is called without previous state
1. open a directory
1. state for the package is never set

Also I am assuming that if you opened atom to the original directory, the package state is deserialized correctly.

**Comment by cooolbasha** [comment]
This is the package https://atom.io/packages/preview-plus 
Open Atom and any folder use command preview-plus:base. It opens up a dialog. change the directory or add a folder to the path. click confirm. exit atom. Reopen atom. go to the same folder. open preview-plus:base. It should have newly changed path. It will not have it.
So open atom once more and open the folder now use the command.. this time it should pull up. 

The first time when atom opens up and activate the package. I put a break point and found that packageStates is empty

**Comment by skandasoft** [comment]
bump::

**Comment by skandasoft** [comment]
@benogle 
yes... when you open with the folder/ without folder it doesn't serialize back. But if the developer tool was open and you restarted the atom the state is reinstated.
