### ISSUE TITLE
Delay onDidChange for string types.

### ISSUE THREAD

**Issue by andrewrynhard** [atom/atom#5256]
I have a situation where I need to ensure  the user inputs a string in a specific format. I thought it would be nice to do some regex on the config string and format it accordingly. Furthermore it would feel a lot cleaner if I could do this using the onDidChange method. I gave it a shot but Atom froze up and when it didn't the change was instant and trying something was impossible. I would like to request a feature that delays the process until the settings window is closed to execute the callback.

**Comment by benogle** [comment]
Seems like what you really want is a regex filter in the config schema. So you could write

```coffee
config: 
  mySetting:
    type: 'string'
    regex: '[a-fA-F0-9]+'
    default: 'abc123'
```

**Comment by arynhard** [comment]
@benogle: Did not know this existed. Is this in the documentation?

**Comment by lee-dohm** [comment]
@arynhard If you mean the config schema, yes it is. You can find the initial reference to it in Creating a Package:

https://atom.io/docs/latest/creating-a-package#adding-configuration-settings

Which then refers you to the Config API docs here:

https://atom.io/docs/api/latest/Config#config-schemas

If you mean specifically the regex filter, then no ... not yet.

**Comment by lee-dohm** [comment]
Whoops! Forgot to close this way back when :cry:
