### ISSUE TITLE
Build error : cannot find module 'walkdir' whole buildings.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#5260]
Hello , i haven't update Atom.io for long, today i did git pull to  updated from 143 to latest master.
When i tried to ./script/build i get this error.

Loading "index.js" tasks...ERROR
>> Error: Cannot find module 'walkdir'

Then continue to download-atom-shell task but , it stops after , nothing is printed out.

**Comment by kevinsawicki** [comment]
Can you try running `script/clean` and then re-running `script/build`?

**Comment by v3ss0n** [comment]
having connection problem today so it will take long , but i did that anyways. Waiting for results.

**Comment by kevinsawicki** [comment]
This can typically occur when an `npm install` is interrupted and only partially completes.

Cleaning and then re-bootstrapping should always fix it, closing this out.
