### ISSUE TITLE
Selecting Files in Tree View don't open until switching windows.

### ISSUE THREAD

**Issue by this-Mathieu** [atom/atom#5261]
Hi,

The issue I am seeing is when I select a file in the tree view, nothing happens. I can click it multiple times, click other files, continue editing, etc. Once I switch to any other window, and return to atom, anything I've clicked in the tree view will then open. Including the same files multiple times. I now have just grown a habit of clicking the file in the tree view, and then clicking another window and back into atom.

This is happening frequently, but not always for myself and some people I know. From what I can tell, this only happens to Windows Users, and did not happen prior to Windows auto Updates, though I can't give a specific version # I started seeing it.

**Comment by mark-hahn** [comment]
I haven't seen this on my two windows 8.1 machines.  I've used every
version.

**Comment by this-Mathieu** [comment]
These are windows 7 machines, if that helps. It's very strange and will be an issue for 6 hours, and then not happen for a few hours. I only now want to look for a fix since other people I work with updated to the latest version with auto updates and now are seeing the same issue.

**Comment by 50Wliu** [comment]
Is this reproducible in safe mode (`atom --safe`)?  If not, it's probably one of your installed plugins that are causing the issue.

**Comment by this-Mathieu** [comment]
Thanks 50Wliu, I think you nailed it. Safe worked fine. I only have 3 packages and 3 themes. I then went through and disabled/enabled all of my plugins 1 by 1 and noticed it stopped happening when I uninstalled seti-ui.

It's difficult to tell if it is seti-ui yet, or if it is just one of those times it begins to work, but I'm reasonably certain it is seti-ui.

Thanks!

**Comment by this-Mathieu** [comment]
Co-worker disabled seti-ui and it instantly stopped. Quite positive it is causing the issue.
