### ISSUE TITLE
atom:// url package installation

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#5262]
Elaborating on #2037:

To allow some interesting integrations with atom.io, we should allow users to initiate package installation from the `atom://` url handler. There are a number of questions to answer:
- [ ] What work in atom core & atom-shell is required to support this on all 3 platforms?
  - Windows registry doc: https://msdn.microsoft.com/en-us/library/aa767914(v=vs.85).aspx
  - The current top answer to this is relevant, showing how to use gconf on a system with gnome: http://stackoverflow.com/questions/1947209/registering-a-url-protocol-handler-in-a-multiple-platforms
- [ ] What are the user concerns around security and predictability and how can we address them?
  - Users should always know what is being installed and have to explicitly confirm installations initiated outside the editor
- [ ] What's a general-purpose UI look like for this, given the editor can be in any state when installation is initiated?
  - Probably a modal in the active window?

**Comment by zcbenz** [comment]
Atom already has `atom://` registered in Info.plist:

```plist
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>atom</string>
			</array>
			<key>CFBundleURLName</key>
			<string>Atom Shared Session Protocol</string>
		</dict>
	</array>
```

And it seems that there is already some meaning of `atom://` url handler:
https://github.com/atom/atom/blob/master/src/browser/atom-application.coffee#L402

**Comment by thedaniel** [comment]
@zcbenz That's mac-only though, we don't register the url with the Windows registry / try to set gnome/kde config for it do we?

**Comment by zcbenz** [comment]
@thedaniel Right, we only have it on Mac.

Registering URL on other platforms are quite similar, they are implemented usually by writing some settings to some registry, and the program specified will be called with the URL appended in command line. The work will mostly be in installers/packages.

**Comment by thedaniel** [comment]
Fortunately we can write and test all the app code for this without having to wait for the cross-platform URI handler stuff to be done. I probably won't have time this week but I'll wireframe or prototype this.

**Comment by jeancroy** [comment]
Btw GitHub Desktop use that feature for the `Clone In Desktop` feature. So you may have some solution in house.

**Comment by benogle** [comment]
> Btw GitHub Desktop use that feature for the Clone In Desktop feature. So you may have some solution in house.

There are a bunch of pieces of this that have been moving forward here and there. e.g. the settings-view now supports [opening a package via URI](https://github.com/atom/settings-view/pull/614)

**Comment by thedaniel** [comment]
cc @BinaryMuse for context

**Comment by UziTech** [comment]
Any update on this? From what I gathered the work is pretty much done in #14243

**Comment by BinaryMuse** [comment]
@uzitech I'll be handling this as part of the larger effort around https://github.com/atom/atom/pull/11399. Stay tuned!

**Comment by BinaryMuse** [comment]
Closed by https://github.com/atom/atom/pull/11399 and https://github.com/atom/settings-view/pull/1011
