### ISSUE TITLE
"Check for Update" on Windows appears broken

### ISSUE THREAD

**Issue by frankhale** [atom/atom#5265]
I'm running 0.175 and noticed when I looked at the Atom repo on Github that there is a new release 0.176. I went to the Help menu and clicked on "Check for Update" and it tells me that 0.175 is the latest version. Here is a screenshot:

![atom-auto-update-broken](https://cloud.githubusercontent.com/assets/190154/5909454/d550fa84-a57e-11e4-9482-77535a2f03ed.PNG)

**Comment by 50Wliu** [comment]
It may take a bit of time for the auto-updater to recognize that there's a new version.  If there's still no update tomorrow...then there might be a problem.

**Comment by kevinsawicki** [comment]
It can take some time to propagate to atom.io, it was only released a few minutes ago.

**Comment by frankhale** [comment]
Oh okay, no worries. I'll check later on then.

**Comment by frankhale** [comment]
Closing this for now, will reopen if it's really a problem.

**Comment by frankhale** [comment]
Sorry for the false alarm, LOL! The new version auto updated perfectly.

**Comment by kevinsawicki** [comment]
> The new version auto updated perfectly.

Awesome to hear this
