### ISSUE TITLE
API: getProjectRoot and pixelPositionForBufferPosition

### ISSUE THREAD

**Issue by jmquigs** [atom/atom#5266]
Hello,

I'm trying to upgrade the ide-haskell package to API 1.0, and I have a couple questions:

1. It looks like atom is moving away from having a single project root directory (as described in  #3691).  Does this mean that packages should define and track a project root themselves, if needed?

2. The deprecation cop says to use TextEditorElement::pixelPositionForBufferPosition, instead of the same function on the editor model.  I see that editor.displayBuffer appears to be the indicated TextEditorElement, however, there is no apparent accessor for it; is it a part of the public API?

Thanks

**Comment by benogle** [comment]
1. You can probably get away with just using `atom.project.getDirectories` and cycling through that.
1. You can get the `TextEditorElement` via `atom.views.getView(textEditor)`, then call `pixelPositionForBufferPosition` on that

**Comment by jmquigs** [comment]
Thanks, with your tips, I think I got it fixed up.
