### ISSUE TITLE
package settings should have repo link not issues link

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#5268]
In package settings there is no link to the repo.  There is just a direct link to issues.  This is a problem since you can't see other issues to see if it is a duplicate.  It should go to the repo. I know it is just one more click to the repo but this encourages people to not check for duplicates.

**Comment by mnquintana** [comment]
@mark-hahn Do you mean in Settings > Packages or Settings > Packages > `<package-name>`?

**Comment by 50Wliu** [comment]
I agree with @mark-hahn-currently it's a bit hard to get to the repository.  The "Report Issue" button is extremely prominent compared to the little text-based `author/packagename` above the buttons.

**Comment by zephraph** [comment]
Shouldn't this be an issue in [settings-view](https://github.com/atom/settings-view)?

**Comment by thedaniel** [comment]
@mark-hahn could you reopen on atom/settings-view?

**Comment by mark-hahn** [comment]
>  compared to the little text-based author/packagename above the buttons.

I didn't see that.  Sorry.
