### ISSUE TITLE
Builld on Ubuntu 14.04 done but with errors

### ISSUE THREAD

**Issue by voylinux** [atom/atom#5269]
I made a build from source in an Ubuntu 14.04 machine (current Ubuntu LTS version) and got some errors on the console.

The editor is wroking anyway.

Here is what I got.

```
Running "set-version" task
Done, without errors.
Running "install" task
Done, without errors.
Running "mkrpm" task
>> script/mkrpm: línea 12: rpmdev-setuptree: orden no encontrada
Aborted due to warnings.

 ```

**Comment by muchweb** [comment]
@voylinux, for Debian-based distributions (inc. Ubuntu) you only need to run `mkdeb`.

```bash
script/grunt mkdeb
```

---

`rpmdev-setuptree` script is part of Fedora's [`rpmdevtools`](https://fedoraproject.org/wiki/Rpmdevtools).
