### ISSUE TITLE
Problem opening/editing a file with Atom

### ISSUE THREAD

**Issue by tdegrunt** [atom/atom#5270]
Hi,

The following file will not open with Atom, but Brackets (and SublimeText, etc) will open the file instantly.
It's likely due to the very long line (with strange characters), but still ...

Here's a gist with the file:
https://gist.github.com/tdegrunt/1404dc0c35be458bdb59

Cheers,
Tom

**Comment by benogle** [comment]
Thanks for the report. Refs #979 and #1667.

**Comment by benogle** [comment]
Closing in favor of #979
