### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/ruthan/localhost/project.json'

### ISSUE THREAD

**Issue by therufs** [atom/atom#5272]
I was actually trying to open /Users/ruthan/localhost/replies_controller.rb. The file that's 'open' doesn't actually exist. 

**Atom Version**: 0.175.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/ruthan/localhost/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/ruthan/localhost/project.json'
  at Error (native)

```

### Commands

```
     -0:00.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  },
  "editor": {
    "fontSize": 14,
    "showInvisibles": true,
    "showIndentGuide": true,
    "tabLength": 4,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.7.3
save-session, v0.10.0

# Dev
No dev packages
```

:elephant:

**Comment by 50Wliu** [comment]
Please update `save-session` to the latest version.

**Comment by therufs** [comment]
I just did :/

**Comment by therufs** [comment]
Then I also quit and restarted atom, which helped -_-
