### ISSUE TITLE
No icon in panel

### ISSUE THREAD

**Issue by olmokramer** [atom/atom#5281]
After upgrading to Atom `v0.176.0` last night, the  icon on my panel has changed to the generic application icon instead:

![atom-no-icon](https://cloud.githubusercontent.com/assets/3612514/5930172/708f7a44-a68c-11e4-9524-fd87ae48f423.png)

I'm on Linux Debian 8 (jessie), using tint2 as my panel application.

**Comment by matugm** [comment]
Same problem here, just installed Atom v0.176.0 from .tar.gz on manjaro linux (xfce desktop).

**Comment by zcbenz** [comment]
Yeah it should be caused by #5235, I'll add the icon back on Linux.
