### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by asiniy** [atom/atom#5283]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.153.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package

:-1: 

I've got the same error. Ubuntu x86_64

**Comment by muchweb** [comment]
>Atom Version: 0.153.0

[`0.176.0` is out](https://github.com/atom/atom/releases/tag/v0.176.0). Does the error still happen there?

**Comment by lee-dohm** [comment]
If this is thrown from the linter package, then it is a problem with linter most likely. In any case, please update to the latest version and let us know if this reproduces.
