### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by asiniy** [atom/atom#5284]
Uncaught TypeError: Cannot read property 'remove' of undefined

**Atom Version**: 0.153.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [tabs](https://github.com/atom/tabs) package

Holy shit, else one exception? What's going wrong with atom?
It seems I need to go back to gEdit for a little time.

**Comment by muchweb** [comment]
>Atom Version: 0.153.0

[`0.176.0` is out.](https://github.com/atom/atom/releases/tag/v0.176.0) Give it a try.

**Comment by asiniy** [comment]
@muchweb, thanks. Problem has been solved, but there is a new error. I'm going to package `term2` developer with issue :)

**Comment by muchweb** [comment]
:+1:
