### ISSUE TITLE
Package failed to install on Windows (Git failed to clone)

### ISSUE THREAD

**Issue by slhck** [atom/atom#5285]
Windows 7 Professional, just downloaded latest Atom installer (0.176.0). Git (2.1.1) was installed through Cygwin and is in my PATH. 

When I install a package (linter@0.10.1), I get:

```
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/Benvie/harmony-collections.git) 
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git Cloning into 'C:\Users\ROBITZ~1.WER\AppData\Local\Temp\npm-7564-87558be8\git-cache-7b68b07c12d7\e81b4b808359e2def9eeeabfdee69c2989e1fe96'...
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git fatal: '/cygdrive/c/Users/robitza.werner/.atom/.node-gyp/.atom/.apm/_git-remotes/https-github-com-Benvie-harmony-collections-git-df214100/c:\Users\robitza.werner\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100' does not appear to be a git repository
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git fatal: Could not read from remote repository.
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git 
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git Please make sure you have the correct access rights
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git and the repository exists.
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Users\\robitza.werner\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\bin\\\\node.exe" "c:\\Users\\robitza.werner\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\robitza.werner\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\.apmrc" "--userconfig" "c:\\Users\\robitza.werner\\.atom\\.apmrc" "install" "C:\\Users\\ROBITZ~1.WER\\AppData\\Local\\Temp\\d-115028-8080-1qs2kqa\\package.tgz" "--target=0.20.0" "--arch=ia32"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\ROBITZ~1.WER\AppData\Local\Temp\npm-7564-87558be8\git-cache-7b68b07c12d7\e81b4b808359e2def9eeeabfdee69c2989e1fe96'...
npm ERR! fatal: '/cygdrive/c/Users/robitza.werner/.atom/.node-gyp/.atom/.apm/_git-remotes/https-github-com-Benvie-harmony-collections-git-df214100/c:\Users\robitza.werner\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

Is the error that my local folder has the wrong permissions? Or can't it read from the remote in the first place?

**Comment by benogle** [comment]
Did you have an internet connection? Do you have access to write to that crazy temp directory?

Another note: a really easy way to install git on windows is to install [github for windows](https://windows.github.com/)

**Comment by slhck** [comment]
Yes, I have a direct Internet connection. No proxy or anything.

I'm not sure if `\AppData\Local\Temp\` is such a crazy directory. Since it's under my user directory, I assume that I have. Also, the error makes it look like it tries to fetch

    git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96

… and I'm not sure if that's a valid repo?

Re. Git: I know that I could also use GitHub for Windows or msysgit. I didn't want any other Git installation though, since I already had the one from Cygwin and it was working.

**Comment by gstewart** [comment]
I think it has to do with the path it's trying to clone into. I'm having this same issue myself and haven't found a way around it yet.

The path it lists for the error message `does not appear to be a git repository` is actually two paths:

`/cygdrive/c/Users/robitza.werner/.atom/.node-gyp/.atom/.apm/_git-remotes/https-github-com-Benvie-harmony-collections-git-df214100/c:\Users\robitza.werner\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100`

The first part is the location from the cygwin point of view:

`/cygdrive/c/Users/robitza.werner/.atom/.node-gyp/.atom/.apm/_git-remotes/https-github-com-Benvie-harmony-collections-git-df214100/`

The second part is the same location from the windows point of view:

`c:\Users\robitza.werner\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100`

I'm not sure why it's combining these two together like this. I'm not sure if this is the actual problem but it stood out to me.

**Comment by Aldotroid** [comment]
I'm also experiencing the same issue with the same path:

`'/cygdrive/c/Users/Aldo/.atom/.node-gyp/.atom/.apm/_git-remotes/https-github-com-Benvie-harmony-collections-git-df214100/c:\Users\Aldo\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100' does not appear to be a git repository`

**Comment by Dharun** [comment]
Has anyone made any progress with this? Still seems to be an issue

**Comment by fundon** [comment]
https://github.com/atom/emissary/pull/10

Is it fixed? 
/cc @atom

**Comment by dax0** [comment]
Still not

**Comment by dax0** [comment]
Still not fixed despite the 1.0 release

**Comment by dax0** [comment]
I found a fix!  Take this file: https://gist.githubusercontent.com/mathieucarbou/fd5c619816b5efc0d2a8/raw/311d3e6061052c722e4b38493b0c39bc18ae3c21/git.diff

And replace ./Atom/resources/app/apm/node_modules/npm/lib/utils/git.js

It's a workaround - I don't think this fix will ever make it into NPM since they refuse to support cygwin at all

**Comment by OeinTwor** [comment]
@dax0 
process.env.ORIGINAL_PATH  is undefined on windows.(i use win10).No work.

 i  removed  'cygwin' ,and everything is ok.

Thanks for your code.

**Comment by cr1901** [comment]
@OeinTwor's solution worked for me for msys2 (but also make sure to remove the /cygdrive prefix from the replace as well). I wonder if there's a way to detect if the msys2 git is being used and update paths accordingly?

In general, msysgit/msys2 git's handling of Windows paths is... iffy.

**Comment by damieng** [comment]
There is not much we can do about the path limitations/mangling of cygwin/msys/msys2.

The solution would be to use a version of git that is capable of being called without going via an emulation layer - [Git for Windows](https://git-scm.com/download/win) has official releases that can work directly with Windows folders.
