### ISSUE TITLE
Python Files don't open properly

### ISSUE THREAD

**Issue by scott-w** [atom/atom#5287]
When I open my project then try to open a Python file, it doesn't open in the front, and a tab never appears for the file.

It does actually open as I can scroll the mouse wheel and the file itself will open but without a couple of things e.g. Linter, Line for 79 chars:

![python_file_opened](https://cloud.githubusercontent.com/assets/1969937/5935657/12de6506-a6d5-11e4-8d6a-89be4b4818e1.png)

In the above file you can see the `urls.py` file is open, but it doesn't appear in the tabs at the top.

I'm using Ubuntu 14.04 and installed Atom from the .deb on the website.

This issue is somewhat intermittent. After a while of Atom being open, it will start working normally again.

**Comment by benogle** [comment]
What version of atom do you have? Please quit atom completely and run `atom --safe`. Is the issue still there?

Is there anything in the console when this happens?

**Comment by scott-w** [comment]
Hi @benogle I've looked into it a little more and I think it's the Linter plugin. When I disabled it, Atom worked fine, then started showing the error when I re-enabled it. I'll close this bug and open one on the Linter repo.

**Comment by benogle** [comment]
Thanks!
