### ISSUE TITLE
Atom.exe fills my console log for no reason

### ISSUE THREAD

**Issue by bpasero** [atom/atom#5288]
I wonder why Atom is so verbose when launching from the command line. Imho this should be hidden away under a "--verbose" flag:

C:\Users\benny\AppData\Local\atom\app-0.176.0>[9208:0128/111502:ERROR:crash_reporter_win.cc(70)] Cannot initialize out-of-process crash handler
App load time: 311ms
[4208:0128/111502:INFO:renderer_main.cc(207)] Renderer process started
[9208:0128/111504:INFO:CONSOLE(54)] "Window load time: 1774ms", source: file:///C:/Users/benny/AppData/Local/atom/app-0.176.0/resources/app/static/index.js (54)

**Comment by kevinsawicki** [comment]
Are you launching the `atom.exe` directly?

**Comment by kevinsawicki** [comment]
You might want to just launch `atom.cmd` from `C:\Users\benny\AppData\Local\atom\bin` instead, it won't show this output.

**Comment by bpasero** [comment]
Right, I just found out about your workarounds in C:\Users\name\AppData\Local\atom\app-0.176.0\resources\cli\atom.js to avoid Atom shells output. I should maybe file this against Atom Shell directly instead.

**Comment by kevinsawicki** [comment]
> I should maybe file this against Atom Shell directly instead.

Some of those messages are printed by chromium, some by atom, none by atom shell.

**Comment by bpasero** [comment]
If every app that builds on top of atom shell has to write code like cli/atom.js, I think its fair to think about a bug report in the platform you are building on top of.
