### ISSUE TITLE
Windows: closing Atom leaves my console in a weird state

### ISSUE THREAD

**Issue by bpasero** [atom/atom#5289]
Are others seeing this too? On a normal windows shell I launch atom.exe and then I pick File > Exit. My console does not return to the command prompt though.

Interestingly I can type commands like "dir" and I see output. So in fact, the command terminated but my console is not indicating this.

**Comment by 50Wliu** [comment]
What Atom version are you on?  Are you installing through the new installer or through Chocolatey?  I thought this was an issue a while back but it got resolved by the new installer.

**Comment by bpasero** [comment]
Ah I see, I am running C:\Users\name\AppData\Local\atom\app-0.176.0\Atom.exe and this has a different experience compared to running Atom from command line. 

I see your C:\Users\name\AppData\Local\atom\app-0.176.0\resources\cli\atom.js code is doing quite some lifting to avoid output and issues from Atom Shell. So maybe I should file this against Atom Shell instead.

**Comment by mark-hahn** [comment]
Make sure chocolatey is totally removed.  See the blog post about it.

**Comment by 50Wliu** [comment]
Assuming fixed.  @bpasero please comment if it's still not fixed on your end and you're running Atom 1.0.19 (through the installer, not Chocolatey).
