### ISSUE TITLE
When pressing AltGR+] on fr keyboard on windows, the keybinding Ctrl+alt+] is called

### ISSUE THREAD

**Issue by adrien59cadri** [atom/atom#5290]
In order to write ']', I need on my french keyboard to type AltGr+° because the ] is made like that.
But this triggers the folding action Alt+Ctr+]...

this is really annoying I can't type] except if I remove the keybinding

**Comment by adrien59cadri** [comment]
Sorry it calls the ctrl + Alt + [ shortcut for a strange reason

**Comment by KeitIG** [comment]
`ctrl + Alt + [` nor ']' does not trigger anything in Atom for me. Have you installed an extension using this keybinding ?

**Comment by lee-dohm** [comment]
This is a duplicate of atom/atom-keymap#35. Please subscribe there for updates.
