### ISSUE TITLE
Is there atom editor's offline api document?

### ISSUE THREAD

**Issue by liugangnhm** [atom/atom#5291]
Is there atom editor's offline api document?
-----------------------
https://atom.io/docs/api/v0.176.0/Atom# is too slow for me :(, so i want to read it offline..

**Comment by benogle** [comment]
Sorry, there is no offline version of the docs.

**Comment by steveoh** [comment]
is this still the case? The atom/docs should contain this. It would be great. I wish I could have this for the plane i'm about to board.

**Comment by batjko** [comment]
Well there was a thought to bring Atom docs to [devdocs.io](http://devdocs.io/), which has an offline download feature.

https://trello.com/c/F9n8CLBk/207-atom
