### ISSUE TITLE
Atom Info.plist

### ISSUE THREAD

**Issue by Ryan050** [atom/atom#5294]
I was trying to add a new file type to Info.plist in OS X but no success about that.
The extension which i added don't is accepted by the editor ( the blank icon remains )
Others file in the editor like .md don't work too, someone know why?
I already rebuild the LaunchService database then what could be?

**Comment by kevinsawicki** [comment]
What is the issue you are experiencing?

**Comment by kevinsawicki** [comment]
I'm guessing this is spam, please let me know if it isn't

**Comment by Ryan050** [comment]
@kevinsawicki Sorry, i typed enter by mistake.

**Comment by Ryan050** [comment]
@kevinsawicki Finder preferences have a mark up option which is "Show preview icon" this override the atom icons with a OS X preview icon or a blank icon if the file type is unknown, this cause files like markdown and others to have a blank icon.
