### ISSUE TITLE
Windows: "Paul Betts" folder appears in Start Menu

### ISSUE THREAD

**Issue by rly** [atom/atom#5296]
I'm on Windows 7. I updated Atom from 0.175.0 to 0.176.0 yesterday. Today, I noticed a new folder in my Start Menu Programs called "Paul Betts". The folder is empty. The creation time is just 13 seconds after the creation of the folder atom/app-0.176.0/resources and before the creation time of the rest of the files in atom/app-0.176.0.

This seems like a bug. In case it's relevant, I do remember closing Atom during the update process.

**Comment by zephraph** [comment]
First bug that's made me laugh in a while.

**Comment by benogle** [comment]
rad. cc @paulcbetts

**Comment by paulcbetts** [comment]
This didn't happen on my machine. If it's not too much of a pain, can you take your entire `C:\Users\MYNAME\AppData\Local\atom` folder and Dropbox it to me?

**Comment by bwin** [comment]
> This didn't happen on my machine. If it's not too much of a pain, can you take your entire C:\Users\MYNAME\AppData\Local\atom folder and Dropbox it to me?

Just put it in your "Paul Betts" folder. ;)

**Comment by paulcbetts** [comment]
All of my folders are Paul Betts folders, that's what I name every folder on my machine of course! #laughsoyoudontcry

**Comment by bwin** [comment]
Sorry, I meant "rly" needs to put it in *his* "Paul Betts" folder, so it turns up in *your* Dropbox...

**Comment by benogle** [comment]
I <3 this thread

**Comment by rly** [comment]
It took a couple hours of tinkering but I managed to replicate the bug a few times. The timing required to create the bug requires a slowish PC but a fast internet connection. I could not create the bug on my fast PC. 

Long story short, if you start an update while a previous update is working, both update processes will try to modify `Local\atom\app-0.176.0`, and for whatever reason, this leads to "Paul Betts" appearing in my Start menu. 

1. For good measure, in Windows, create new standard user account and log onto it
1. Download and run `AtomSetup.exe` v0.175.0
1. Atom will open when the install completes and will begin downloading v0.176.0 to `Local\atom\packages\atom-0.176.0-full.nupkg`
1. Go to `Local\atom\packages` in Windows Explorer and monitor the download file size (F5 repeatedly)
1. After `Local\atom\packages\atom-0.176.0-full.nupkg` reaches final size of 77MB, the file size will drop to 0B and will gradually rise back up to 77MB
1. Close atom as early as after Local\atom\packages\atom-0.176.0-full.nupkg dropped to 0B and as late as right before when I say to open it below
1. When `Local\atom\packages\atom-0.176.0-full.nupkg` reaches its final size for the second time, `Local\Temp\nuget\[some chars]\` and `Local\atom\app-0.176.0\` will be created
1. Wait about a minute
1. `Local\atom\atom.exe` will be created but `Squirrel.exe` will not yet be created 
1. Close atom
1. Open atom
1. v0.176.0 will begin downloading for the second time - `Local\atom\packages\atom-0.176.0-full.nupkg` will go to 0B and rise to 77MB
1. After `Local\atom\packages\atom-0.176.0-full.nupkg` reaches final size of 77MB, the file size will drop to 0B and will gradually rise back up to 77MB
1. When `Local\atom\packages\atom-0.176.0-full.nupkg` reaches its final size for the fourth time now, `Local\atom\app-0.176.0\` will be cleared except for the `resources\` directory (I think the first update is still creating files in there)
1. Wait less than a minute
1. In `Local\atom\`, `squirrel.exe`, `ui_resources_200_percent.bak`, `vccorlib120.dll`, `xinput1_3.dll` will be created (from first update)
1. Wait about 5 seconds
1. `Local\atom\SquirrelSetup.log` will be created (from first update)
1. `Roaming\Microsoft\Windows\Start Menu\Programs\Paul Betts` directory will be made (??)
1. `Update.exe` will remain running and not doing anything as far as I can tell

Speculation: Maybe when Squirrel fails to find `Local\atom\app-0.176.0\atom.exe` to make a shortcut for it, Squirrel tries to create a Start menu shortcut for `squirrel.exe` instead, which leads to a directory for its company/org name ("Paul Betts"?) being created.

If you can't replicate this and would still like me to upload my atom folder to you, let me know.

**Comment by paulcbetts** [comment]
It sounds like what *might* be happening is that Squirrel is somehow failing to determine that Atom is a Squirrel-enabled application. Squirrel has two paths for generating shortcuts:

1. At least one of the apps is "Squirrel aware" - this means that they're marked with a special Version block header which says, "This app will understand us passing --squirrel-install to it". If this is true, we never explicitly create shortcuts, only allow the app itself to do so. Atom.exe is marked in this fashion. 

1. If no apps are Squirrel Aware, we fallback to "Dumb mode", where you just wanted to create an installer, so we'll take care of it for you. In this scenario, we run through every EXE file and create shortcuts for it, using the info in the EXE's version block to fill in the folder and file names.

If we were to fail to access Atom.exe when we made the check, we'd end up making a shortcut for Squirrel.exe, which probably has my name as the company name. 

@rly Thanks for the awesome write-up. A question, what Antivirus application are you using? It could be holding a lock on Atom.exe trying to scan it.

**Comment by jspahrsummers** [comment]
https://www.youtube.com/watch?v=T_EZesbpvag

**Comment by rly** [comment]
@paulcbetts I am using Avast Free antivirus. 

In case it wasn't clear, at the time that `Local\atom\atom-0.176.0\squirrel.exe` and `Local\atom\atom-0.176.0\SquirrelSetup.log` are created (from the first update process), `Local\atom\atom-0.176.0\atom.exe` does not exist (because the second update process deleted them).

**Comment by rick** [comment]
> Just put it in your "Paul Betts" folder. ;)

:star2:

**Comment by mark-hahn** [comment]
I'm thinking of selling "I have a Paul Betts" folder" T-shirts.

**Comment by bwin** [comment]
I'll take 8!

mark-hahn <notifications@github.com> schrieb am Sa., 31. Jan. 2015 21:13:

**Comment by paulcbetts** [comment]
> In case it wasn't clear, at the time that Local\atom\atom-0.176.0\squirrel.exe, Local\atom\atom-0.176.0\SquirrelSetup.log, and Roaming\Microsoft\Windows\Start Menu\Programs\Paul Betts\ are created (from the first update process), Local\atom\atom-0.176.0\atom.exe does not exist (because the second update process deleted it).

So our problem could be multiple `Update.exe` instances running concurrently, which was fixed in Squirrel/Squirrel.Windows#189, but that fix probably hadn't made it to Atom yet.

**Comment by 50Wliu** [comment]
This can be closed now, right?

**Comment by paulcbetts** [comment]
Yep afaik
