### ISSUE TITLE
Ability to set syntax via the command palette

### ISSUE THREAD

**Issue by LoneBoco** [atom/atom#5297]
Sublime Text has the ability to set the syntax of your file using the command palette.  It has a command called "Set Syntax" that will switch the syntax of the currently opened document.

The Sublime Text web page has an example of it in action where the user types "sspy" to fuzzy find the command "Set Syntax: Python".

The only way to open the syntax menu in Atom seems to be clicking the current syntax in the bottom-right corner of the window.  There doesn't seem to be any keybind or command to open that window.

**Comment by kevinsawicki** [comment]
> There doesn't seem to be any keybind or command to open that window.

There is https://github.com/atom/grammar-selector/blob/4bd9627cf9bbd6e4b8e4a34ef3b59419c10e19bb/keymaps/grammar-selector.cson

You should see it from the command palette if you search for grammar

**Comment by LoneBoco** [comment]
I don't know how I missed that.  I'll go ahead and close this then.
