### ISSUE TITLE
Atom on windows crashes a lot of it's attempting to do filesystem operations on a mounted network drive

### ISSUE THREAD

**Issue by Mortoc** [atom/atom#5298]
Specifically, I'm editing files on an OSX samba share. When I do any file system operations in the tree view, the app crashes. Also sometimes it just crashes. But mostly it works!

**Comment by 50Wliu** [comment]
Refs #4849.

**Comment by benogle** [comment]
Can you go into more detail on the crashes? Can you provide the output from `Console.app`? (search in spotlight for console, open it, and search for atom, paste the crash log in here)

Is this a crash crash? Or are you seeing a red error?

**Comment by 50Wliu** [comment]
Can you access programs through a samba share?  @Mortoc said that he's on Windows, not OS X.

**Comment by benogle** [comment]
My mistake, I just read the description.
