### ISSUE TITLE
Only a suggestion

### ISSUE THREAD

**Issue by alexbruno** [atom/atom#5303]
Would be great like Chrome and Firefox if we could to login with GitHub account and then sync all settings, themes, extensions...

**Comment by philipgiuliani** [comment]
Hi, there is already an issue open for that https://github.com/atom/atom/issues/3572

https://github.com/Hackafe/atom-sync-settings you can try this package for now! :)

**Comment by alexbruno** [comment]
Thank you very much!

**Comment by philipgiuliani** [comment]
Could you close the issue? :)
