### ISSUE TITLE
Package is of bad quality

### ISSUE THREAD

**Issue by amingilani** [atom/atom#5308]
**Package**: atom-amd64.deb 
**Release**:  0.176.0
**System**: linux 3.13.0-43-generic.
**OS**: Elementary OS (Luna). Based on Ubuntu 12.04

> The installation of a package which violates the quality standards isn't allowed. This could cause
> serious problems on your computer. Please contact the person or organisation who provided this
> package file and include the details beneath.

```
Lintian check results for /home/amingilani/Downloads/atom-amd64.deb:
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at /usr/bin/lintian line 108.
E: atom: package-installs-python-bytecode usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.pyc
E: atom: package-installs-python-bytecode usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.pyc
E: atom: package-installs-python-bytecode usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/__init__.pyc
E: atom: package-installs-python-bytecode usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.pyc
E: atom: package-installs-python-bytecode usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.pyc
E: atom: package-installs-python-bytecode usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.pyc
```

**Comment by maxvodo** [comment]
**Confirm** on deb atom 0.192.0. 
**System**: linux 3.13.0-49-generic.
**OS**: Elementary OS (Luna). Based on Ubuntu 12.04.

**Comment by batjko** [comment]
Dupe of #3462?

**Comment by maxvodo** [comment]
Look on #3462, this isn't dupe of it. This error causes when I trying install deb with GUI Software Center. But, if I installs deb over dpkg, there is no error.

**Comment by thinklinux** [comment]
Same problem.
Ubuntu 14.10.

I was having a problem to download it in a first place with Chromium because of a malware warning. You should look in to that too.

**Comment by vanillajonathan** [comment]
1.0.19

    Lintian check results for /tmp/atom-amd64.deb:
    Unknown tag "binary-file-compressed-with-upx" in profile "ubuntu/aptdaemon" at /usr/bin/lintian line 1661.

**Comment by zeke** [comment]
I just ran into this on Ubuntu 14 (using Parallels). Steps to reproduce:

- Visit https://atom.io/
- Download the .deb package
- Double-click it. This opens "Ubuntu Software Center"
- Click "Install". Then comes the sadness:

![screen shot 2016-10-24 at 11 55 32 am](https://cloud.githubusercontent.com/assets/2289/19659449/cf5896f2-99e0-11e6-892b-9bee637cd615.png)

**Comment by thomasjo** [comment]
@zeke I'm pretty sure you're seeing something completely different. Just look at your error message. `lintian` isn't even running, so I'm pretty sure that's a red herring. Will try to reproduce in a fresh VM, but I've been using Atom in Ubuntu VMs for a long, long time and I've never seen that error.

**Comment by zeke** [comment]
@thomasjo thanks for investigating. I'm on the default Ubuntu that ships with Parallels. Forgive my Linux/Debian ignorance here, but what's the cool-person (command-line) way of installing Atom on Ubuntu, short of building it from source?

**Comment by thomasjo** [comment]
On my phone, so forgive any errors; try `sudo dpkg -I atom.deb`. 

My clean test earlier was also Parallels with the provided Ubuntu 14.04 appliance. Tried re-downloading the deb file?

**Comment by amingilani** [comment]
Also on my phone, but the command is `sudo dpkg -i` with a lower case `i`

**Comment by amingilani** [comment]
closing this
