### ISSUE TITLE
Settings->Packages page scroll is not remembered

### ISSUE THREAD

**Issue by TheBestPessimist** [atom/atom#5310]
First time user, fresh install, but long time Sublime text 2/3 user (more than 2 years).
After i installed atom, i went to settings to check all the options, and one thing that really annoyed me was that after i click a package name (or the settings button for that package), to see its configs/properties, if i click at the top of the window "Packages" again, the list position is reset, so for example if i am at the middle of the list, i have to scroll again and find my position. 

Also another thing is that if i click (in the same menu) multiple times the "Settings' button, i can not see the "Packages" button at the top, so my only possibility is to go on the left panel and click "Packages" there (this again resets my scroll position)

**Comment by TheBestPessimist** [comment]
Should i add some images to explain exactly what I mean, or is it clear enough?

**Comment by 50Wliu** [comment]
Could you please open this issue on the [settings-view](https://github.com/atom/settings-view) packages instead?  Thanks.
