### ISSUE TITLE
"Find in Project" misses some button?

### ISSUE THREAD

**Issue by splendido** [atom/atom#5312]
Isn't a `Find` button supposed to be here?

![findinproject](https://cloud.githubusercontent.com/assets/6148980/5973432/73d8d3b6-a868-11e4-81b0-7c593b733f12.png)

This is what I get on Ubutnu 14.04 with Atom@0.176.0

**Comment by Fank** [comment]
Confirmed on Ubuntu 14.10 with Atom@0.176.0
Didn't noticed this issue because, I use the "Enter" key to search

**Comment by izuzak** [comment]
See https://github.com/atom/find-and-replace/issues/297 and please add a comment there. Thanks!

**Comment by splendido** [comment]
Oh, sorry, I've looked for already open issues, but didn't found out that one :(
tnx!
