### ISSUE TITLE
Cursor disappears after switching tags (Awesome WM)

### ISSUE THREAD

**Issue by muchweb** [atom/atom#5318]
Cursor disappears after switching between tags in [Awesome WM](http://awesome.naquadah.org/).

Steps to reproduce:
1. Atom is focused on tag `1`, cursor visible
2. Switch to tag `2`, <kbd>modkey+2</kbd>
3. Switch back to tag `1`, <kbd>modkey+1</kbd>
4. Atom is focused on tag `1`, cursor invisible

---

Atom `0.176.0` on  GNU Operating system

**Comment by bayprogrammer** [comment]
I am having a similar problem with the cursor disappearing when switching between desktops in [Openbox](http://openbox.org/wiki/Main_Page). The cursor reappears when I click in the window manually (even though it already has the focus), when I switch to the tree then back to the open file, or when I switch to a different window then back. Seems to be something subtle going on with how Atom decides it's re-received focus and thus should re-display the blinking cursor.

Using Atom 1.0 on ArchLinux, built from the AUR.
