### ISSUE TITLE
Feature Request: Magic Package Object

### ISSUE THREAD

**Issue by sedabull** [atom/atom#5319]
Let me start off by describing my use case. I'm writing a package where the version number is prominately displayed in the main view. Something like "Welcome to this awsome Atom Package v-X.Y.Z". In order to find the version number of the installed package, I have to write out this really long ugly line of code:
```coffeescript
versionNum = atom.packages.getLoadedPackage('my-package').metadata.version
```
and it got me thinking that it would be really nice to have a free variable that refers to *this* package, much like the node free variable `module` refers to *this* module. So instead of that long, ugly monster I could instead write:
```coffeescript
versionNum = package.metadata.version
```
which would mean *my* package's version number or even better:
```coffeescript
versionNum = package.version
```
Please note that this is not a vital request, and I can live without it. I simply think it would be convenient and much more elegant. Also note that I have no idea where to even begin implementing this, or if it's even possible to begin with. But I can't be the only one using my own package's metadata progmatically, so if it is possible, hopefully there's someone out there who could make it happen and make life on us package developers just that much easier! :smile:

**Comment by thedaniel** [comment]
Here's an alternate implementation suggestion: Pass a parsed package.json for the package as an option to the activate function, which wouldn't change anything significant to how package loading works but would still make it easily available for use. How do you feel about that?

**Comment by sedabull** [comment]
That sounds pretty clever actually. So I would have to retrieve the package via `atom.packages.getPackage('my-package')` and then attach it to the serialize object correct? That way it would be available on activation. My concern is if someone updates their package, won't the old version number still be displayed until Atom is shut down and reloaded? Or does the package reactive upon being updated?

**Comment by sedabull** [comment]
I've been mulling over this for the past hour, and I believe I have a new suggestion that wouldn't (hopefully) be too difficult to implement. My primary motivation for making this request is that I really don't like making that long, ugly call in my original post. For discussion purposes, I'm going to simplify the situation. What I want to do is serialize the current version number of my package so that it can be extracted on activation like this:
```coffeescript
activate: (state) ->
  @verNum = state.verNum
```
However, this presents two distinct problems. The first is that if this is the very first time the package is being activated, the version number won't be available, and I'm back to my original problem which is making that really long call to retrieve the version number. The second is that even if the first problem were solved, if the package gets updated (as it is likely to do) then `@verNum` is now out of date, and worse it will continue to serialize the outdated version number. So all subsequent activations will still load out of date information. However, I believe there is a solution: two new package hooks called `install` and `update`. Adding these hooks would change the layout of main package file to something like this:
```
#my-package.coffee

module.exports = MyPackage =
  verNum: null
  
  activate: (state) ->
    @verNum = state.verNum
    #other activation logic...
  
  deactivate: ->
    #deactivation logic...
  
  serialize: ->
    verNum: @verNum
    #other state to serialize...
  
  install: (metadata) ->
    verNum: metadata.version
    #other metadata to serialize...
  
  update: (metadata) ->
    @verNum = metadata.version
    #other update logic...
```
The install hook would be called once atom has finished installing the package and be feed all relevant package metadata as the first parameter. The object that this function returns would then be serialized just like normal so that any metadata the developer wishes to utilize is available on the first activation. The update hook would be called whenever atom updates this package and be feed all of the new metadata as it's first argument. The developer can then progmatically update whatever information they're using, with the bonus side effect that the next serialization will also reflect that new information.

In closing I would just like to say that I'm aware this is not exactly the best time to be requesting new features, and I completely understand if this doesn't get a lot of attention. If anyone has time, however, I'd love to hear any and all feedback, especially from the core team :smile:

**Comment by lee-dohm** [comment]
Here's what I do to get the package metadata:

```coffee
JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'))
```

I guess it isn't really any shorter, but the code never changes depending on what package it is in ... so long as you're always calling it from a file one level below the root of the package, anyway :laughing:

**Comment by abe33** [comment]
Node has a really handy feat that allow to require a json file with `require`, so the following works: 

```coffee
{version} = require(path.join(__dirname, '../package.json'))
```

**Comment by sedabull** [comment]
Yes, I've come to realize over the past few days that my requests add an unnessecary amount of complexity to solve a very trivial non-problem. It may not be the prettiest line of code, but what's important is that it works. I'm closing this in the interest of reducing the amount of noise here at atom so people can get back to solving real problems. Thank you to everyone who responded though! It's nice to be able to recieve honest, helpful feedback from the community.
