### ISSUE TITLE
Improve dropdown-menu style

### ISSUE THREAD

**Issue by GameplayJDK** [atom/atom#5321]
![screenshot_1](https://cloud.githubusercontent.com/assets/4069263/5979913/0e00dfea-a8ac-11e4-87be-84930d868b92.png)

This is pretty much just a design improvement, but I think the current design doesn't fit too well (especially the scroll bar) :smiley:

**Comment by benogle** [comment]
Can you be more specific?

**Comment by mehcode** [comment]
A custom rendering with a as-you-type search bar would be much better. Just using the autocomplete dropdown style here would be great.

**Comment by GameplayJDK** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/4069263/5981091/6bc5e462-a8b7-11e4-9ed9-e63b3476d41e.png)

The scroll bar of the drop-down (2) would look better (for a consistent style) if it would be the same as the one used in the editor (1).

**Comment by mnquintana** [comment]
@GameplayJDK What OS are you on?

**Comment by 50Wliu** [comment]
Those are the default scrollbars Chrome uses on Windows, so I'll take a wild guess and say Windows ;P.

**Comment by mnquintana** [comment]
Ah haha, sorry, I've been living in Mac and Linux land for awhile now. :blush: (Although now that I look at it, it looks almost identical on Linux too.)

Yeah it seems that it's just a standard OS `select` on every platform (although it happens to look the best on OS X):

## Mac OS X 10.10.2
![image](https://cloud.githubusercontent.com/assets/823545/5985885/5bf9feec-a8b7-11e4-9169-e0811fe6e281.png)

## Ubuntu 14.10
![image](https://cloud.githubusercontent.com/assets/823545/5985910/d79b8dea-a8b7-11e4-821d-d6deae886fcb.png)

It would be cool to have something like [Selectize](http://brianreavis.github.io/selectize.js/) / [Select2](https://select2.github.io/) / [Chosen](http://harvesthq.github.io/chosen/) for `select` dropdowns in Atom though. Or at least match the theme scrollbars for Windows & Linux.

**Comment by 50Wliu** [comment]
Hmm, you're absolutely right.  I'm on Ubuntu myself right now and I didn't notice that the scrollbars are identical to the ones used on Windows...
/excuse: I blame the fact that I've turned on Chrome's experimental scrollbars for ~3 versions now :P
