### ISSUE TITLE
Atom does not compile in FreeBSD 10

### ISSUE THREAD

**Issue by juanmtz79** [atom/atom#5322]
[root@pcbsd-7889] /home/jc/atom# script/build
Node: v0.10.32
npm: v1.4.28
Installing build modules...
Installing apm...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)

npm ERR! atom-package-manager@0.133.0 install: `node ./script/download-node.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the atom-package-manager@0.133.0 install script.
npm ERR! This is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/download-node.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.
npm ERR! System FreeBSD 10.1-RELEASE-p8
npm ERR! command "node" "/usr/home/jc/atom/build/node_modules/.bin/npm" "--userconfig=/usr/home/jc/atom/.npmrc" "install" "--loglevel" "error"
npm ERR! cwd /usr/home/jc/atom/apm
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Any Idea on how to solve this?

**Comment by 50Wliu** [comment]
Is this a duplicate of #2599?

**Comment by nakal** [comment]
I've got a similar problem. The instructions in [the howto](https://github.com/atom/atom/blob/master/docs/build-instructions/freebsd.md) do not work anymore ("the operating system is not supported", as seen in [#2599](https://github.com/atom/atom/issues/2599)). Then I replaced [www/node](http://www.freshports.org/www/node) with [www/node-devel](http://www.freshports.org/www/node-devel) and got a bit further. It still shows me multiple errors during `./script/build`:

```
de: v0.11.14
npm: v1.4.28
Installing build modules...
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo EAI_BADFLAGS
gyp ERR! stack     at Object.exports._errnoException (util.js:742:11)
gyp ERR! stack     at errnoException (dns.js:46:15)
gyp ERR! stack     at Object.onlookup [as oncomplete] (dns.js:91:26)
gyp ERR! System FreeBSD 10.1-RELEASE-p5
gyp ERR! command "node" "/usr/home/user/tmp/atom/build/node_modules/npm/node_modules/n
ode-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/user/tmp/atom/build/node_modules/minidump
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo EAI_BADFLAGS
gyp ERR! stack     at Object.exports._errnoException (util.js:742:11)
gyp ERR! stack     at errnoException (dns.js:46:15)
gyp ERR! stack     at Object.onlookup [as oncomplete] (dns.js:91:26)
gyp ERR! System FreeBSD 10.1-RELEASE-p5
gyp ERR! command "node" "/usr/home/user/tmp/atom/build/node_modules/npm/node_modules/n
ode-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/user/tmp/atom/build/node_modules/runas
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo EAI_BADFLAGS
gyp ERR! stack     at Object.exports._errnoException (util.js:742:11)              [1/1903]
gyp ERR! stack     at errnoException (dns.js:46:15)
gyp ERR! stack     at Object.onlookup [as oncomplete] (dns.js:91:26)
gyp ERR! System FreeBSD 10.1-RELEASE-p5
gyp ERR! command "node" "/usr/home/user/tmp/atom/build/node_modules/npm/node_modules/n
ode-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/user/tmp/atom/build/node_modules/grunt-atom-shell-installer/nod
e_modules/asar/node_modules/chromium-pickle
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! minidump@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minidump@0.8.0 install script.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.
npm ERR! System FreeBSD 10.1-RELEASE-p5
npm ERR! command "node" "/usr/home/user/tmp/atom/build/node_modules/.bin/npm" "--userc
onfig=/usr/home/user/tmp/atom/.npmrc" "install" "--loglevel" "error"
npm ERR! cwd /usr/home/user/tmp/atom/build
npm ERR! node -v v0.11.14
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

I am lost, what to do?

**Comment by pusateri** [comment]
This ticket should be closed. It's a duplicate of #6035 and there is more information there.

**Comment by 50Wliu** [comment]
Closing as a duplicate of #6035.
