### ISSUE TITLE
will atom do some change to utilize io.js

### ISSUE THREAD

**Issue by Pana** [atom/atom#5326]
FYI

**Comment by benogle** [comment]
cc @zcbenz

**Comment by kevinsawicki** [comment]
@Pana what do you mean by utilize?

Atom Shell was upgraded to use io.js in https://github.com/atom/atom-shell/pull/1002

Atom's next release will include this version of Atom Shell, so Atom will be running on top of io.js in the Atom 0.177 release.

I hope this answers your question, please comment if it doesn't.
