### ISSUE TITLE
IME makes cursor disappear and input nothing

### ISSUE THREAD

**Issue by xpol** [atom/atom#5328]
I'm under MacOS 10.10.2.

When using input ascii code it works well.

But when write Chinese (maybe other none Western characters as well) docs.

Steps:
1. Switch IME to **U.S.**, input some ascii character, and do not input tailing blanks.
2. Switch IME to **Pinyin Simplified**, input some pinyin, and press space to commit Chinese characters to Atom editor.

Result:
- the Chinese characters not add to the editor.
- and the cursor lost.

**Comment by xfq** [comment]
I can't reproduce this problem with Atom 0.178.0-e4ca11d (`--safe`) on OS X 10.10.2.
