### ISSUE TITLE
About some links to docs

### ISSUE THREAD

**Issue by xfq** [atom/atom#5332]
I didn't find links to the following pages on the [main documentation page](https://atom.io/docs/latest/):

* https://atom.io/docs/latest/apm-rest-api
* https://atom.io/docs/latest/theme-variables
* https://atom.io/docs/latest/your-first-package

Is it intentional or just forgetting to add the links?

**Comment by kevinsawicki** [comment]
Thanks for pointing this out, I fixed it on master, it will generate on atom.io the next time a release is published.
