### ISSUE TITLE
Disabling a package that provides shadow DOM scoped styles trashes all editor styles

### ISSUE THREAD

**Issue by dmnd** [atom/atom#5337]
1. Install a package that provides shadow DOM scoped styles for `atom-text-editor`. A minimal example is my [pulsing cursor package](https://github.com/dmnd/pulsing-cursor)
2. Activate the pulsing cursor
3. Open a file
4. Open a split pane (not sure if this is necessary to repro but it's what I did)
5. Open settings in the other pane and disable pulsing cursor
6. The editor that had the file open is now missing styles

Probably disabling the package removes all `atom-text-editor` styles instead of just [the ones provided by the package](https://github.com/dmnd/pulsing-cursor/blob/master/stylesheets/pulsing-cursor.atom-text-editor.less). If you enable the package again, the editor will be restored.

**Comment by nathansobo** [comment]
@dmnd I'm having trouble reproducing this on master. Is it still an issue for you?

**Comment by dmnd** [comment]
Nope, I can no longer reproduce this. 

It looks like the package's CSS now remains in the editor view. That is, when I disable pulsing-cursor, the cursor still pulses in any existing editor views. Only new editor views have the default cursor. Not a big deal though.
