### ISSUE TITLE
Dev tools don't show up.

### ISSUE THREAD

**Issue by mnemon1ck** [atom/atom#5341]
windows 7 

I don't remeber the exact steps, because even reinstalling of Atom doesn't fix the bug. But approximate steps were:
1. Open Dev tools
2. Undock dev tools
2. Close Dev tools
3. Open it again

Currently when I open Dev tools I have it openned (see the screensot) but when I click on it, nothing shows up.

![image](https://cloud.githubusercontent.com/assets/10331509/5991575/95cad436-aa22-11e4-8661-4105bb712f61.png)

**Comment by mnemon1ck** [comment]
I deleted completelly all the files that related to atom, then I reinstalled it and it worked out. But I don't know deleting of which exact file solved the problem.

**Comment by mark-hahn** [comment]
It is hidden off screen.  This has been happening to me for a long time but
I'm too lazy to post the issue.

>
The only way I have been able to fix it when it happens is too ...

- Go to the task bar and find the detached dev tool window.  It will be
next to Atom window.
- Maximize it.  It will appear full-screen.
- Reattach it to the Atom window.
- Reload Atom
- Detach again -- it will appear full screen
- Shrink it to something reasonable.

This should be posted as an issue to atom/atom-shell.

**Comment by damieng** [comment]
Looks like this was fixed in electron and we picked up the fix. Not sure which version it was fixed in but working here in 1.10 and likely earlier releases.
