### ISSUE TITLE
View > Panes doesn't show keybindings in menu

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#5343]
_(Issue version of https://github.com/atom/atom/issues/2594#issuecomment-56977044)_

**Expected:** When I click View > Panes and look at the available Panes operations, I should see their keybindings.

**Actual:** When I click View > Panes, I see no keybindings even though the Panes operations have keybindings by default.

**Steps to reproduce:**
1. Click on View in the main menu
2. Move to Panes
3. None of the Panes operations show their keybindings

![image](https://cloud.githubusercontent.com/assets/823545/5992350/ff58295a-a9f3-11e4-8ce5-4d20e4e90da6.png)

However, you can confirm that Panes operations do in fact have keybindings by checking the Keybindings list or by opening the Command Palette and searching for `pane`.

![image](https://cloud.githubusercontent.com/assets/823545/5992340/8c94022c-a9f3-11e4-90d4-622063b07f9b.png)

![image](https://cloud.githubusercontent.com/assets/823545/5992346/b831397c-a9f3-11e4-8053-897b4fb35007.png)

**Atom:** 0.176.0 (safe mode)
**OS:** OS X 10.10.2 Yosemite

---

**EDIT:** Reproduced in Windows 8 too:
![image](https://cloud.githubusercontent.com/assets/823545/5992450/c2a40d8a-a9f8-11e4-9cb1-dd3566ea8c9a.png)

**Comment by mnquintana** [comment]
View > Panes actually doesn't even exist on Linux. (?)

## Ubuntu 14.10
![screenshot_2015-02-01_09_47_30](https://cloud.githubusercontent.com/assets/823545/5992427/a8134626-a9f7-11e4-9646-99ba27a7ff1b.png)

**Comment by 50Wliu** [comment]
I think I remember a comment somewhere saying that multi-stroke keybindings weren't showing up properly in menus.

**Comment by mnquintana** [comment]
@50Wliu Ah, found it! https://github.com/atom/atom/issues/2594#issuecomment-56977044

**Comment by kevinsawicki** [comment]
Yeah, this issue has been around for a really long time (system menus not showing keybindings for multi-stroke keybindings), I thought there was an old issue for this but I couldn't find it.

**Comment by mnquintana** [comment]
@kevinsawicki Is this an Electron issue?
