### ISSUE TITLE
script/build stops at random module / plugin (Arch Linux)

### ISSUE THREAD

**Issue by mensinda** [atom/atom#5345]
`script/build` seams to stop (nothing happens for at least 30min) at a random plugin / module. There are also no warnings / errors on the console.

This strange behavior occurred first 3 days ago.
### What I have tried so far:
- an old atom commit (which worked a month ago)
- downgrading nodejs
- removing `$HOME/.atom` and `$HOME/.node-gyp`
- a different user account
- rebooting
- building manualy
- building from the [AUR](https://aur.archlinux.org/packages/atom-editor-git/)

Neither of these steps helped.

I don't know what I have changed at my system since my last rebuild was a month ago.
### My system:
- Arch Linux x86_64
- PYTHON=python2
- npm version: `2.4.1`
- nodejs version: `0.10.36`

**Comment by muchweb** [comment]
I know this might sound silly, but have you checked that you have enough free disk space?

**Comment by mensinda** [comment]
Jes. I have 500GB free disk space and 5GB free RAM.

**Comment by Arvius** [comment]
I can confirm that. Sole solution yet is to repeat the building process very often until it works. (My setup is very similar to mensinda's.)

**Comment by mensinda** [comment]
I did some further testing with a [precompiled](https://aur.archlinux.org/packages/atom-editor-bin/) Atom version. I found out that the random stop problem also occurs when installing single plugins via the Atom GUI or apm (it either runs forever or is done in less than 30 seconds). It also does not matter if a plugin is or was already installed.

Using the `--verbose` option showed even stranger behavior: It is not even random *if* it stops, it is also random **when** the build process stops. There are basically 2 different points where it is stoping (as far as I know):
 - apm only prints `Installing <x> to $HOME/.atom/packages`
 - after an entry like `REQUEST emitting complete <random path>`

Also the number of `REQUEST` entries is random (from `0` to some to a lot).

Is there a way to increase the verbosity level even further? Or is there a specific function that is constantly called?

**Comment by sjug** [comment]
I've seen reports of that happening as well on [arch](https://aur.archlinux.org/packages/atom-editor/). It just started happening with 0.176 I believe, but I'm not able to reproduce it.

**Comment by mensinda** [comment]
With the last system update I get a timeout error when the build process has stopped for more than a minute (I do not know how big the timeout exactly is):

```
Unable to download https://www.atom.io/api/packages/<plugin>/versions/<version>/tarball: connect ETIMEDOUT
```

This error message replaces the run-until-ctrl-c behavior. Additionaly this happens **ALSO** in the 0.177.0 release, so it has nothing to do with the last atom commits.

**Comment by m-namazi** [comment]
how can I install random module in ubuntu 14.04 for ndnSIM?
