### ISSUE TITLE
Expose editor settings to themes (less)

### ISSUE THREAD

**Issue by nevir** [atom/atom#5352]
It would be pretty handy to have a less function that exposes editor configuration (such as editor font family, size, etc)!  My current motivation is to honor the user's editor font family for styling things like `code`.

Maybe something along the lines of `setting('editor.fontFamily')`?

**Comment by nevir** [comment]
Also see related issue https://github.com/atom/atom/issues/4598#issuecomment-67152210 - seems like this would help there too (enabling theme authors to honor user settings)

**Comment by benogle** [comment]
A less function would be cool. Something like this is happening over at https://github.com/atom/atom/pull/4153. Though, in that PR, when settings are changed, it sets the variable, and regenerates the css.

**Comment by nevir** [comment]
Ah sweet!
