### ISSUE TITLE
What version of Jasmine is Atom using?

### ISSUE THREAD

**Issue by xfq** [atom/atom#5354]
In [vendor/jasmine.js](https://github.com/atom/atom/blob/52abb4afc9098454cea8e220a363be3a9b958934/vendor/jasmine.js#L2662), I found that the Jasmine version is 1.3. In [docs/writing-specs.md](https://raw.githubusercontent.com/atom/atom/2f62346c585361591e6a9de7349401c7ebe360eb/docs/writing-specs.md), I found links to both Jasmine 1.3 and 2.0. It would be nice to document the version of Jasmine used in Atom and correct the wrong link(s) in `writing-specs.md`.

**Comment by as-cii** [comment]
:+1: 

This has the added benefit of avoiding to write helpers like `fit`, which are already provided by new versions (`it.only`).

[This guide](http://jasmine.github.io/2.0/upgrading.html) provides some help in the upgrade process. If you consider this a feasible opportunity for upgrading I am interested in contributing (e.g. I can take care of it).

Meanwhile I'll make some experiments to see what breaks without changing tests.

**Comment by thedaniel** [comment]
Moving to 2.0 would be great, and we look forward to the results of your investigation ;) Some caveats:

- There are changes to how async specs work (though I'm not super familiar with the specifics) that will probably require a lot of big changes to the atom specs
- All community package specs are written to 1.3 so there would need to be some kind of mechanism to allow a package to opt-in to 2.0 and run 1.3 by default
- There are dozens of core package repos (everything from tree-view to markdown-preview) that will need spec updates or to be set to run on 1.3

cc @maxbrunsfeld as we briefly discussed this in chat

**Comment by kevinsawicki** [comment]
I believe this was fixed by https://github.com/atom/atom/pull/5368

**Comment by UziTech** [comment]
For anyone who is looking for a way to transition to jasmine 2.x I created a test runner that uses jasmine 2.x and falls back to the default jasmine 1.3 test runner for legacy tests. 

[atom-jasmine2-test-runner](https://www.npmjs.com/package/atom-jasmine2-test-runner)
