### ISSUE TITLE
sort items in File Finder / Buffer Finder in recent used order

### ISSUE THREAD

**Issue by weijar** [atom/atom#5358]
The initial order in Buffer Finder is recent used order, it is ok, but when I enter some characters to filter it, it tunes to alphabetical order :(

In File Finder, when I filter it, it then show many files I never edit it at top of this list.

In my previous editor Sublimetext, it saves file edit order info to workspace file and use this list to sort finder items.

**Comment by benogle** [comment]
This issue was moved to atom/fuzzy-finder#71
