### ISSUE TITLE
Causing Itunes crackle

### ISSUE THREAD

**Issue by Zilarrezko** [atom/atom#5361]
So a weird problem. But I pinpointed it to when Atom is open and I'm playing music on Itunes, I get a popping/crackling sound from my music.

I've never noticed it before but for some reason it started this morning, and the only package I got inbetween last time I played music while using atom was terminal-status.

**Comment by mark-hahn** [comment]
>  I get a popping/crackling sound from my music.

 It seems you are running out of cpu cycles.  What is your cpu load?  Check
what apps are using the cpu.

**Comment by Zilarrezko** [comment]
Do these help?

![cpu](https://cloud.githubusercontent.com/assets/8561784/6008208/9fa96fb4-aad4-11e4-8c44-824fa133db7e.png)

![dxdiag](https://cloud.githubusercontent.com/assets/8561784/6008209/a54cd96a-aad4-11e4-9f5e-6e2f2108a5c6.png)

**Comment by Zilarrezko** [comment]
Nvm... I restarted and it still has the problem when atom wasn't running. Sorry about that.

**Comment by paulcbetts** [comment]
@Zilarrezko Upgrade your video drivers, this is a classic Windows issue where video drivers are taking up too much of the CPU and you get audio dropout (because video driver schedules a DPC that is too long and the buffer runs out)

**Comment by Zilarrezko** [comment]
It's been up to date for a while.

![uptodate](https://cloud.githubusercontent.com/assets/8561784/6008926/1a5df248-aada-11e4-9ee2-f9f48cb0e996.png)

**Comment by flagbug** [comment]
@Zilarrezko Do you have VirtualBox, or any other virtualization tools installed? Try disabling the virtual network adapters they create (as seen in the picture below) in the device manager.
![2015-02-02 22 24 38](https://cloud.githubusercontent.com/assets/964691/6009468/4d28a0d8-ab2a-11e4-82b1-81bc677bb860.png)

**Comment by Zilarrezko** [comment]
Just this thing

![devicemanager](https://cloud.githubusercontent.com/assets/8561784/6012421/d3193780-aafc-11e4-94e9-aa3703454930.png)
