### ISSUE TITLE
ctrl + right doesn't wrap around lines that have CR LF line endings

### ISSUE THREAD

**Issue by ipaq3115** [atom/atom#5363]
In both tests the ctrl key is held down and the right arrow key is pressed twice.

![ctrl_right_atom_bug](https://cloud.githubusercontent.com/assets/8430611/6011041/cba690f2-ab05-11e4-882e-3b2faba7447f.gif)

**Comment by xlaywan** [comment]
+1

**Comment by nycdotnet** [comment]
+1

**Comment by Ben3eeE** [comment]
Unable to reproduce in Atom 1.19.4
