### ISSUE TITLE
Need cross-platform support in Getting Started doc

### ISSUE THREAD

**Issue by JoeArizona** [atom/atom#5365]
Can the doc owner find-and-replace Mac-only "cmd" keyboard shortcuts with the idiomatic cross-platform "ctrl/cmd"?

A lot of people won't actually know to translate cmd to ctrl. People at the beginning of their software journeys, so to speak, e.g. 12- or 18-year-olds who have only ever used Windows or Linux. And vast numbers of people in developing countries who have never been in the same room with a Mac, and again especially at the beginning of their journeys/careers, before they've encountered a lot of content that features "cmd".

**Comment by izuzak** [comment]
Closing this in favor of https://github.com/atom/docs/issues/16. I hope it's something we can do in the new docs, it would be useful. :star:
