### ISSUE TITLE
Some suggestions to CONTRIBUTING.md

### ISSUE THREAD

**Issue by xfq** [atom/atom#5367]
I have a few suggestions to CONTRIBUTING.md. Here are some items that can be added:
- A brief introduction to the workflow (or at least link to help.github.com)
- Web QA (find problems of atom.io across a variety of platforms and browsers)
- Atom QA (find bugs in Atom, Atom Shell, apm, and official Atom packages)
- Translation (I'm not sure whether/when Atom and/or atom.io will support languages other than English, though)
- Something like Mozilla's "Good First Bugs" and "Mentored Bugs"
- Contribute to Atom Wiki, perhaps. (See https://discuss.atom.io/t/a-multilingual-wiki-for-atom/14640)

Also, coding opportunities can be classified to languages/technologies. For example:
- CoffeeScript/JavaScript (Atom and its core packages)
- C++ (Atom Shell)
- Node.js
- CSS/Less (syntax/UI themes)
- Jasmine (spec)
- HTML
- Shell script (e.g., some scripts in `script/`, `atom.sh`, package CI scripts etc.)

**Comment by izuzak** [comment]
@xfq I'd love to improve our CONTRIBUTING docs in the near future -- thanks for these suggestions! :heart_decoration: 

> A brief introduction to the workflow (or at least link to help.github.com)

Just to make sure I understand your suggestion, could you clarify which workflow you're referring to exactly? I'm guessing how to submit a pull request?

**Comment by xfq** [comment]
@izuzak Thanks for your attention!

For "workflow", I mean how to find something to work on, get and build the code, fix something, build/test/benchmark the changes, submit the patch (pull request), respond to the review etc. You can have a look at a sample workflow (for TraceMonkey, the first JIT compiler for JavaScript): [Nicholas Nethercote: How I work on Tracemonkey](http://blog.mozilla.org/nnethercote/2009/07/27/how-i-work-on-tracemonkey/)

I have contributed to many free and open-source software projects. I'll list (and link to) some "contributing" docs I like below. Perhaps you can get some inspiration:

* [LibreOffice](http://www.libreoffice.org/community/get-involved/)
* [OpenStack](https://wiki.openstack.org/wiki/How_To_Contribute)
* [qooxdoo](http://qooxdoo.org/community/contribution)
* [Eclipse](https://www.eclipse.org/contribute/)
* [Homebrew-cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/hacking.md)
* [Bootstrap](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

**Comment by izuzak** [comment]
Great -- thanks for clarifying! I've been looking at the contributing docs for some of those projects myself and I agree we could use them for inspiration.  :+1:
