### ISSUE TITLE
Atom on Chromebook?

### ISSUE THREAD

**Issue by oktayacikalin** [atom/atom#5369]
Have you talked about bringing Atom to the world of Chromebooks as a packaged app or something? Any thoughts on that?

**Comment by philipgiuliani** [comment]
Hi, there is a discussion about ChromeOS!
https://discuss.atom.io/t/lets-talk-chromeos/8644

**Comment by theblacklion** [comment]
Uh nice. Hope that it will be having some fruits in the near future..

**Comment by KurtWAndrews** [comment]
OK, so I read at least a majority of the thread above.  I've got atom working in a chroot running Ubuntu.  What I really want to understand is what exactly need to be done to get atom to run on ChromeOS as a packaged app, or in a browser without Crouton or Ubutu.
