### ISSUE TITLE
Built-in documentation?

### ISSUE THREAD

**Issue by xfq** [atom/atom#5370]
Many editors have built-in documentation. For example, the `C-h` prefix in Emacs, `:help` in Vim, and `^G` in nano. Moreover, many of them also include a tutorial for new users (`:!vimtutor` in Vim and `help-with-tutorial` in Emacs, for example). But for Atom, I only found the `welcome` package.

Is there any plan for built-in documentation in Atom?

**Comment by telkomsel666** [comment]
#1125

**Comment by mark-hahn** [comment]
I have a package `web-browser` and a new version will be available in a
week or two that will load up contextual docs in their real web pages in a
tab in atom.  You can try it now but there is a bug that causes it to fail
in XSS conditions.

**Comment by thedaniel** [comment]
@xfq we're somewhat unofficially planning to add tutorial content to the welcome package, but not sure where it will land on the schedule.

**Comment by mnquintana** [comment]
@thedaniel Is there a, er, roadmap / schedule for the [roadmap](https://atom.io/roadmap) to Atom 1.0? It seems like there's been a lot of planning from the core team behind the scenes, but I feel like we've only really seen the tip of the iceberg here in a lot of cases. (For example, I've seen in a few comments that there's a docs / tutorial overhaul planned and someone to lead the charge, but I have no idea who or what or when.) Like it would be nice to see what the core team's priorities are, an estimated ship schedule for certain features / changes, and where you guys could use the most help from the community.

**Comment by mark-hahn** [comment]
http://blog.atom.io/2014/10/23/public-roadmap.html

**Comment by mnquintana** [comment]
@mark-hahn I linked to that roadmap in my comment :stuck_out_tongue_closed_eyes:  – I mean more that it seems like there's been a lot of planning going on that *isn't* reflected in the roadmap and isn't quite reflected on GitHub either.

**Comment by kevinsawicki** [comment]
> and where you guys could use the most help from the community.

On this note, we have started labelling issues with the *help wanted* label over the last couple months, https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aatom+label%3A%22help+wanted%22

**Comment by thedaniel** [comment]
@mnquintana the priorities and roadmap are largely reflected in this task list: https://github.com/atom/atom/issues/3684 There is not a *schedule*, and probably won't be.

The core team has a call at the beginning of each week prioritizing things at the task level, but anything at the feature / structural change level should be covered by the roadmap and 1.0 task list, and if they aren't (e.g. docs) it's definitely legit to bug us to add it to one or both. 

Definitely open to suggestions on the best way to ask for community help, but I think that PRs are welcome for just about anything that there's an open issue for (though a comment on the issue about the proposed solution is of course helpful).

**Comment by benogle** [comment]
New docs are happening. We even have a little package that shows those docs. But it's a little too early to show them. We will soon make the docs repo public and ask for doc contributions.

**Comment by lee-dohm** [comment]
Great news @benogle :+1: Thanks!

**Comment by xfq** [comment]
See also: atom/docs#9
