### ISSUE TITLE
Atom file types icon on OS X

### ISSUE THREAD

**Issue by Ryan050** [atom/atom#5373]
Some already created files are not showing the atom icon ( show blank or unix terminal icon ) if i create a new file, the icon is fine... but some file types like .md are showing blank icon.
This is a non-priority and useless issue but it's annoying see the terminal icon in some files.

**Comment by 50Wliu** [comment]
Does this still happen if you run Atom in safe mode (`atom --safe`)?
If it doesn't, it might be one of your themes or packages interfering with the icons.

**Comment by Ryan050** [comment]
Solved after trashing icons cache folder.
