### ISSUE TITLE
No SQL Highlighting

### ISSUE THREAD

**Issue by cblake78** [atom/atom#5378]
I have no highlighting for any sql file that I open
![image](https://cloud.githubusercontent.com/assets/10833464/6023938/ef576c40-ab84-11e4-91fa-20208372c970.png)

**Comment by benogle** [comment]
Hello, I think the [language-sql](https://github.com/atom/language-sql) package should have what you want.

**Comment by cblake78** [comment]
It's already installed, but I still don't have any highlighting.

**Comment by kevinsawicki** [comment]
@cblake78 What language is displayed on the status bar for the file you opened?

**Comment by cblake78** [comment]
SQL.  I've tried changing it to SQL(Rails) and SQL(Mustache), but I get the
same results.

**Comment by kevinsawicki** [comment]
Can you share the raw contents of one of the files that isn't highlighting?

**Comment by cblake78** [comment]
After opening the file in Notepad, I realized it may be the file itself....

**Comment by kevinsawicki** [comment]
> After opening the file in Notepad, I realized it may be the file itself....

Should this issue be closed then? Or are you thinking it could still be an Atom issue?

**Comment by cblake78** [comment]
Go ahead and close it.  Thanks for getting back to me so quickly.
