### ISSUE TITLE
Unable to install minimap package on Windows 8.1 with Atom v.0.176

### ISSUE THREAD

**Issue by joshku** [atom/atom#5379]
Hi, I tried to do a package install with Atom and I am unable to install minimap. Not sure what is going on but there is the error message that I got. I just did a fresh install of Atom to my Windows 8.1 laptop.

npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git Cloning into 'C:\Users\Josh\AppData\Local\Temp\npm-1952-09bd2c23\git-cache-d860487d2c7d\e81b4b808359e2def9eeeabfdee69c2989e1fe96'...
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git fatal: '/cygdrive/c/Users/Josh/.atom/.node-gyp/.atom/.apm/_git-remotes/https-github-com-Benvie-harmony-collections-git-df214100/c:\Users\Josh\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100' does not appear to be a git repository
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git fatal: Could not read from remote repository.
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git 
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git Please make sure you have the correct access rights
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git and the repository exists.
npm ERR! Failed to clone git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 from https://github.com/Benvie/harmony-collections.git 
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\Users\\Josh\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\bin\\\\node.exe" "c:\\Users\\Josh\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\Josh\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\.apmrc" "--userconfig" "c:\\Users\\Josh\\.atom\\.apmrc" "install" "C:\\Users\\Josh\\AppData\\Local\\Temp\\d-11513-9844-uadpna\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\Josh\AppData\Local\Temp\npm-1952-09bd2c23\git-cache-d860487d2c7d\e81b4b808359e2def9eeeabfdee69c2989e1fe96'...
npm ERR! fatal: '/cygdrive/c/Users/Josh/.atom/.node-gyp/.atom/.apm/_git-remotes/https-github-com-Benvie-harmony-collections-git-df214100/c:\Users\Josh\.atom\.node-gyp\.atom\.apm\_git-remotes\https-github-com-Benvie-harmony-collections-git-df214100' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by AbeEstrada** [comment]
You should report this in the package's repo.

https://github.com/fundon/atom-minimap/issues

**Comment by steelbrain** [comment]
@AbeEstrada I think the error is in the installation of minimap, not in the usage of minimap. and It's Atom who handles the installation process. :smiley:

**Comment by mnquintana** [comment]
Gonna close this one out since this was on such an old version - feel free to reopen if you experience this again with the latest version of Atom.
