### ISSUE TITLE
Atom 0.177.0 doesn't open from command line on MacOS 10.10.2

### ISSUE THREAD

**Issue by acgetchell** [atom/atom#5380]
┌─[adam][Hapkido][±][parallel ✓][~/CDT-plusplus]
└─▪ apm list
/Users/adam/.atom/packages (13)
├── Zen@0.10.0
├── dash@1.0.2
├── error-status@0.3.3
├── language-cmake@0.1.1
├── language-latex@0.4.1
├── latex@0.16.0
├── linter@0.10.1
├── linter-clang@2.22.0
├── linter-pylint@0.2.0
├── run-command@0.1.1
├── script@2.16.0
├── travis-ci-status@0.11.2
└── unity-ui@1.0.7

┌─[adam][Hapkido][±][parallel ✓][~/CDT-plusplus]
└─▪ atom
FSPathMakeRef(/Users/getchell/Applications/Atom.app) failed with error -43.
┌─[adam][Hapkido][±][parallel ✓][~/CDT-plusplus]
└─▪ atom --safe
FSPathMakeRef(/Users/getchell/Applications/Atom.app) failed with error -43.
┌─[adam][Hapkido][±][parallel ✓][~/CDT-plusplus]
└─▪ brew cask info atom
atom: latest
Atom
http://atom.io
/opt/homebrew-cask/Caskroom/atom/latest (11537 files, 239M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/atom.rb
==> Contents
  Atom.app (app)
  Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm (binary)
  Atom.app/Contents/Resources/app/atom.sh (binary)

**Comment by kevinsawicki** [comment]
Does `open -a /Users/getchell/Applications/Atom.app` work?

**Comment by acgetchell** [comment]
┌─[adam][Hapkido][±][master ✗][~/CDT-plusplus]
└─▪  open -a /Users/getchell/Applications/Atom.app
FSPathMakeRef(/Users/getchell/Applications/Atom.app) failed with error -43.

**Comment by kevinsawicki** [comment]
But `/Users/getchell/Applications/Atom.app` does exist? And contains `/Users/getchell/Applications/Atom.app/Contents/MacOS/Atom` as well?

**Comment by acgetchell** [comment]
No, it's installed via brew cask, so symlinked into the Applications directory:

┌─[adam][Hapkido][/Applications]
└─▪ ll
total 184
drwxrwxr-x+ 79 root  admin   2686 Feb  3 11:34 .
drwxr-xr-x  33 root  wheel   1190 Jan 17 15:20 ..
-rw-rw-r--   1 root  admin  18436 Jan 15 15:06 .DS_Store
-rw-r--r--   1 root  wheel      0 Sep  9 15:16 .localized
drwxr-xr-x   3 root  wheel    102 Jan 26 15:08 1Password.app
drwxr-xr-x   3 root  wheel    102 Sep 22 10:42 Alinof Timer.app
drwxr-xr-x+  3 root  wheel    102 Jan 27 12:18 App Store.app
lrwxr-xr-x   1 adam  admin     31 Feb  3 11:34 Assistant.app -> /usr/local/opt/qt/Assistant.app
lrwxr-xr-x   1 adam  admin     48 Oct  2 13:54 Atom.app -> /opt/homebrew-cask/Caskroom/atom/latest/Atom.app

┌─[adam][Hapkido][~/Applications]
└─▪ brew cask list atom
==> App Symlinks managed by brew-cask:
'/Applications/Atom.app' -> '/opt/homebrew-cask/Caskroom/atom/latest/Atom.app'
==> Binary Symlinks managed by brew-cask:
'/usr/local/bin/apm' -> '/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm'
'/usr/local/bin/atom' -> '/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/atom.sh'
==> Staged content:
/opt/homebrew-cask/Caskroom/atom/latest (11637 files)

**Comment by acgetchell** [comment]
Ah, I should clarify. open -a /Applications/Atom.app does work:

┌─[adam][Hapkido][±][master ✗][~/CDT-plusplus]
└─▪ open -a /Applications/Atom.app

**Comment by acgetchell** [comment]
Works now:

┌─[adam][Hapkido][±][master ✓][~/CDT-plusplus]
└─▪ atom -v
0.177.0
┌─[adam][Hapkido][±][master ✓][~/CDT-plusplus]
└─▪ atom
