### ISSUE TITLE
opening the Developer Tools pane prevents the Command Palette from taking focus

### ISSUE THREAD

**Issue by r-owen** [atom/atom#5381]
If I use the keyboard to open the developer tool panel (using the command palette) and then try to run another command using the command palette, I end up typing into the console. In detail:
- make sure the developer tool panel is closed
- type cmd-shift-p to open the command palette
- type "toggle dev" followed by a "return" to open the developer tool pane
- type cmd-shift-p to open the command palette again
- type anything; the text goes into the console (developer tool pane) at the prompt, instead of into the command palette. This is scary. I expected the text to go into the command palette.

By contrast, if I type cmd-t (to open the file palette) after I open the developer tool pane, nothing seems to happen. I don't get the file palette, but at least I don't end up typing somewhere unexpected and possibly dangerous.

Personally I wish cmd-t and cmd-ctrl-p both worked normally at that point. However, I admit that I am not an atom developer; I only open the developer panel when I want to see error messages. If I was a heavy atom developer I might prefer the cmd-t behavior. I can't imagine ever wanting the cmd-ctrl-p behavior.

I am on MacOS 10.9.5 with Atom 0.177.0

**Comment by damieng** [comment]
When you open the dev tools it takes focus. While it has focus it will intercept it's own shortcut combinations. Simply clicking into the Atom editor again will let Atom continue to accept its commands.
