### ISSUE TITLE
fs.existsSync() is deprecated. Use fs.accessSync() instead.

### ISSUE THREAD

**Issue by tststs** [atom/atom#5383]
Hey there,

The package atom-ternjs i'm working on, keeps throwing this error.
I checked twice and there are no calls to fs.existsSync() anymore.

Does this error also effects dependencies, that make use of it?

Greeting from Berlin
tststs

**Comment by kevinsawicki** [comment]
Are you seeing this error in the dev tools?

Do you have a stack trace for the error?

**Comment by tststs** [comment]
no.
![bildschirmfoto 2015-02-03 um 22 50 52](https://cloud.githubusercontent.com/assets/3591665/6030343/2ee25e48-abf7-11e4-8214-fd4f9094b4d1.png)

**Comment by zcbenz** [comment]
iojs deprecated `fs.existsSync()` for `fs.accessSync()`, I have turned off the warning in web pages by setting `process.noDeprecation` to `true`. The warning could still happen for `Task` for `BufferedNodeProcess`.

**Comment by tststs** [comment]
Yes, it is BufferedNodeProcess. Tried switching to BufferedProcess and the error disappeared.

**Comment by tststs** [comment]
Should i switch to BufferedProcess or does this may have any side-effects? At a first look, everything works fine.

**Comment by kevinsawicki** [comment]
> Should i switch to BufferedProcess

It depends on what you are spawning. BufferedNodeProcess is for spawning JavaScript files, BufferedProcess spawns commands.

**Comment by kevinsawicki** [comment]
Thanks for reporting this, deprecations will be suppressed in processes spawned by `BufferedNodeProcess` in the next release, 0.178
