### ISSUE TITLE
incorrect line ending

### ISSUE THREAD

**Issue by neurobashing** [atom/atom#5384]
When I updated to 0.177.0, line endings are incorrectly represented:

![screen shot 2015-02-03 at 17 04 49](https://cloud.githubusercontent.com/assets/59380/6030640/dee826aa-abc6-11e4-81aa-ed566decd461.png)

So in this pic, typing additional characters produces 
![screen shot 2015-02-03 at 17 07 32](https://cloud.githubusercontent.com/assets/59380/6030683/2c63ab66-abc7-11e4-8c42-72fb2f27f918.png)

This occurs in --safe mode as well.

**Comment by mnquintana** [comment]
What OS?

**Comment by neurobashing** [comment]
Mac OS X 10.10.2

**Comment by kevinsawicki** [comment]
@neurobashing Can you share a link to a file that exhibits the behavior in that screenshot?

**Comment by neurobashing** [comment]
I can recreate by simply typing a long string in an empty buffer; but here's a test file https://www.dropbox.com/s/hidyssinhm31v7w/broken_editor.txt?dl=0

**Comment by dasilvacontin** [comment]
I couldn't reproduce.

**Comment by postcasio** [comment]
What font are you using?

**Comment by neurobashing** [comment]
Tried w/ Source Code Pro, Menlo, and Inconsolata (ranged from 12 to 16). Inconsolata 14 fixes the problem; the former 2 show either the same problem or a kind of opposite number - where, as in my screenshot, the trailing quote appears between 'un' as if placed there w/ a funny CSS z-index.

**Comment by mnquintana** [comment]
Which syntax and UI themes do you have active?

**Comment by neurobashing** [comment]
happens for me with any combination of theme and syntax; I went through a few (the ones Atom ships with) and it's always the font that triggers it.

FWIW I moved ~/.atom out of the way and started a new instance which did not exhibit this.

**Comment by muchweb** [comment]
I have similar effect when using custom font that is missing some symbol. Atom will insert missing symbol from a different font, shifting the whole line a little bit, which will put cursor off the real position.

**Comment by miixit** [comment]
Exact same issue on Windows 8.1 since v0.177. Changing font may help a little but don't totally resolve the issue for me...

**Comment by miixit** [comment]
Reverted back to v0.176 to solve issue. Worked. Make a fresh install also resolve issue. Maybe an issue with updater or so...

**Comment by postcasio** [comment]
There was a similar issue to this reported on discuss.atom.io where the culprit was `text-rendering: optimizeLegibility;` in the user styles.

**Comment by developit** [comment]
@postcasio Thank you for that tip-off, that was my issue as well! It was causing strange things like overlapping single quotes.  FWIW, `-webkit-font-smoothing: antialiased;` seems to replicate the text rendering style without triggering the odd rendering.

**Comment by maqdev** [comment]
For me the problem was with theme `trendy-light-ui` which also uses `text-rendering: optimizeLegibility` in it's styles. Removed it from sources and now everything is OK.

**Comment by willogden** [comment]
Had the same issue and removing `text-rendering: optimizeLegibility;` from my user stylesheet fixed it for me.

**Comment by ebraminio** [comment]
This should be closed as the upgrade to Chrome 49 on Electron 0.37 which atom uses now which has set optimizeLegibility default, AFAIK.
