### ISSUE TITLE
Atom Installer windows does not let you choose your install location

### ISSUE THREAD

**Issue by Noah-Huppert** [atom/atom#5386]
When I went to install the newest version of Atom(0.150.0=>0.177.0) the installer did not let me choose an install location.  

This made it a little bit confusing to find out were Atom had put itself. It would be nice if there was an install location option(Or any options) on the installer.  

**OS**: Windows 8.1 x64

**Comment by paulcbetts** [comment]
Sorry, Atom's installer sole purpose is to open the Atom editor on your computer as fast as possible, we're not going to put in any options.

**Comment by 50Wliu** [comment]
@paulcbetts Going to close this as `wontfix` then.
