### ISSUE TITLE
Unified debugger interface?

### ISSUE THREAD

**Issue by xfq** [atom/atom#5387]
A growing number of packages out there deal with debuggers, like [debugger](https://atom.io/packages/debugger) (for JavaScript), [node-debugger](https://atom.io/packages/node-debugger) (for Node.js), and [codebug](https://atom.io/packages/codebug) (for PHP).

It would be really useful if there's a unified debugger interface (like [GUD](http://www.gnu.org/software/emacs/manual/html_node/emacs/Debuggers.html) in Emacs, or, to put it another way, like [linter](https://atom.io/packages/linter) has done to linting in Atom), so that other packages can just use that standard way without each and every one of them writing the same code over and over again. We can keep the functionality of the unified interface to a minimum, this lets other packages use it without being annoyed at the features they drag in.

Comments?

**Comment by mark-hahn** [comment]
Have you seen the package `atom-node-debugger`?

**Comment by maxbrunsfeld** [comment]
This type of unified debugger interface sounds like a good use case for the new [services API](https://atom.io/docs/v0.177.0/creating-a-package#providing-and-consuming-services).

**Comment by xfq** [comment]
@mark-hahn Do you mean [this one](https://github.com/kiddkai/atom-node-debugger)? I linked it in my original post.

**Comment by Trudko** [comment]
What about built in debbuger can't that be used for JavaScript?
