### ISSUE TITLE
Files deleted outside atom should be closed in atom

### ISSUE THREAD

**Issue by GerritWanderer** [atom/atom#5394]
When I delete a file in my project which is already opened, atom is still showing the contents of the deleted file in my editor tab. Surprisingly I can apply changes to it and save the file without any warning message.
In In this case Atom behaves like the file would still exist. Actually he's now editing the same file in my trash folder which is confusing.

I would assume that the editor tab of the deleted is either closed, or when saving it, atom should tell me that this file does not exist anymore and I should save it to a new location.

**Comment by 50Wliu** [comment]
When I try to close a deleted file Atom prompts me to either save|don't save|cancel.  Haven't tried actually editing it though.

**Comment by benogle** [comment]
This is legit. Delete the file from outside atom and note that it is still open in atom. If you save the file from atom, it will recreate the file.

**Comment by mark-hahn** [comment]
>  Actually he's now editing the same file in my trash folder which is
confusing.

It may be confusing but it is the standard way of doing things, at least in
unix.

**Comment by thedaniel** [comment]
I think the bug here is that we are editing the trash-folder file. I *personally* would expect if I deleted something on disk, that it would stay open in the editor (but marked as modified/unsaved in the tab/tree) and be recreated on save.

**Comment by benogle** [comment]
> I personally would expect if I deleted something on disk, that it would stay open in the editor (but marked as modified/unsaved in the tab/tree) and be recreated on save.

I'm down for anything that indicates it was deleted or otherwise changed.

**Comment by mark-hahn** [comment]
There is a package that gives notifications on file conflicts.  Wouldn't
this count as a conflict?

**Comment by 50Wliu** [comment]
If you delete a file outside Notepad++, it'll ask you if you want to keep it in the editor in an unsaved state.  Otherwise, it'll just close it.  I think that's a good compromise.

**Comment by 1j01** [comment]
This is really seriously annoying with autosave. And since I don't use tabs, I basically have to just close everything before I can delete a file without it being resurrected.

**Comment by rileylark** [comment]
I also use autosave. My preference would be that the buffer be immediately closed when its file is deleted (because my buffers are always very close to in sync with their files), +1 @1j01

**Comment by sberan** [comment]
This seems to be happening as desired in the latest version (0.199.0). Time to close?

![output](https://cloud.githubusercontent.com/assets/100066/7667122/d9edc00a-fbc2-11e4-9da7-def0383aba11.gif)

**Comment by 1j01** [comment]
Yes, I suppose it is time to close. This is not intended as prose.

**Comment by lexicalunit** [comment]
Can this be made an option? I use [Gerrit](https://www.gerritcodereview.com/) with [`git review`](https://pypi.python.org/pypi/git-review). Part of what `git review` does is a rebase and hard reset. When this occurs new files are briefly deleted and then restored, causing them to be closed out from Atom. If I want to continue editing the source code after submitting a review (frequent use case) then I have to re-open the files.

**Comment by northamerican** [comment]
There should be an option for this. In Sublime and other editors, deleted files are kept open. Consider this workflow: I have new files created in one branch, then i stash it and checkout another branch to quickly rebase or something. When I return to my original branch, I must reopen my files in Atom because it considered them deleted. In reality they were just in another branch.

**Comment by 1j01** [comment]
@northamerican joins the fray
Reopen, they say, for they need a way
A way, they say, to let the tabs stay
Okay, okay, I'm beginning to stray
(I digress; what a mess)

**Comment by sfowles** [comment]
I too recently had the above issue during a rebase. I think, from a UI stance, it's usually best to let users opt-in to features like this, either by a setting or some other means. It's good for anything that might remotely control a related feature, or do something while the user is otherwise engaged in a different activity (ex, deleting a file). Just my 2 cents.
