### ISSUE TITLE
Atom sources should not include compiled dependencies.

### ISSUE THREAD

**Issue by OhJeez** [atom/atom#5398]
Atom sources contain already compiled "atom-shell". Even if you compile atom to make sure it works with libraries in your system, it does not matter since it is build on top of atom-shell compiled on a different system.

In short: it is not "building from sources" when your sources contain something already built.

Here are some animated gifs, as they are listed as helpful (immensely) in contributing guide: 
![](http://i.imgur.com/yMtFbFQ.gif) ![](http://i.imgur.com/7V882xt.gif) ![](http://i.imgur.com/ziw7RRo.gif)

**Comment by kevinsawicki** [comment]
If we didn't include compiled dependencies than building Atom would require building Chromium which would take hours if not days.

I don't think this is something likely to change given the convenience of being able to build Atom in a reasonable amount of time.

**Comment by OhJeez** [comment]
**I cannot build it.**

Build process is broken. Although it completes without error I get something I cannot use, because it depends on different version of glibc than one in my system.

I regularly rebuild node.js which contains v8 and I live. I used Gentoo when I had cheap one-core processor and I live. My colleague yesterday compiled PhantomJS for use in karma tests and he lives.

Also: many systems out there have something called package dependency management. If the build process of atom-shell didn't came with chromium included, and instead depended on something else to provide it (e.g. apt-get, rpm, emerge...) you wouldn't have a problem of build taking hours.

**Comment by kevinsawicki** [comment]
If you need to build it from source, I'd recommend forking it and replacing the part that downloads the pre-built atom-shell libraries.

**Comment by OhJeez** [comment]
I don't need to and I don't want to anymore. I've been already fixing enough libraries I need to use in my programs at work. I'm ok with compiling thigs, but hacking a new text editor I want to try out is not worth effort going into creating yet-another-unmaintained-fork.
