### ISSUE TITLE
Uncaught Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by ssnyder** [atom/atom#5401]
[Enter steps to reproduce below:]

1. use project switcher to switch to another project
2.opens new atom window with the uncaught error described below.  Issue opened with the project manager project as well.

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: listen EADDRINUSE

```
At events.js:85

Error: listen EADDRINUSE
  at exports._errnoException (util.js:746:11)
  at Server._listen2 (net.js:1136:14)
  at listen (net.js:1162:10)
  at net.js:1260:9
  at Object.asyncCallback [as callback] (dns.js:78:16)
  at Object.onlookup [as oncomplete] (dns.js:96:10)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "quantum-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
column-select, v0.1.0
coverage, v0.5.1
cucumber, v0.4.1
git-log, v0.2.0
git-tab-status, v1.5.3
jenkins-dashboard, v0.2.0
language-gherkin, v0.3.0
language-gherkin-german, v0.5.2
language-rspec, v0.3.0
language-sql-mysql, v0.3.1
minimap, v3.5.6
open-in-atom, v0.1.8
open-last-project, v0.2.2
project-colorize, v0.1.0
project-manager, v1.15.5
quantum-syntax, v0.2.1
ruby-block-converter, v3.1.0
save-session, v0.11.3
ScssBundle, v0.4.0
select-rectangle, v1.0.1
seti-ui, vundefined
tabs-to-spaces, v0.8.1
tualo-git-context, v0.3.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Every time you switch projects? This is probably a bug on project switcher.

**Comment by benogle** [comment]
Actually, it might be the interaction with the project switching and some other package that has a server. Which of the packages you have installed start a server?

**Comment by izuzak** [comment]
@ssnyder This doesn't look like a problem in Atom. Suggestion: if you can reliably reproduce this, try disabling your packages to see which one causes the problem. As @benogle mentioned, this is probably a problem in a package or two packages which start a server.
