### ISSUE TITLE
Don't open path in new window

### ISSUE THREAD

**Issue by m-bra** [atom/atom#5409]
When I press `ctrl-shift-p`, open a path that is, atom opens it in a new window. 
Some might want that. I don't. It's annoying when I just want to switch the project that 1) I have to close the old window and 2) I have to wait for the new window to load (which, sadly, takes a little with atom). 
I'd at least ask for an option whether to open paths in a new window. But I think that this is not wanted anyways.
Like #1722 but with paths instead of files.

**Comment by kevinsawicki** [comment]
This will be added as part of https://github.com/atom/atom/issues/770
