### ISSUE TITLE
About transposing two characters at the end of a line

### ISSUE THREAD

**Issue by xfq** [atom/atom#5410]
In Emacs, one can use `C-t` (`transpose-chars`) to transpose two adjacent characters. Normally, `C-t` transposes the two characters on either side of point (the place in the buffer at which insertion and deletion occur). When given at the end of a line, rather than transposing the last character of the line with the newline, which would be useless, `C-t` transposes the last two characters on the line. So, if you catch your transposition error right away, you can fix it with just a `C-t`. If you don't catch it so fast, you must move the cursor back between the two transposed characters before you type `C-t`.

In Atom, `ctrl-t`   (`editor:transpose`) always transpose two adjacent characters, wherever they are. Will Atom change this behavior?

**Comment by kevinsawicki** [comment]
> Will Atom change this behavior?

Sounds reasonable to special case the end of line behavior. It looks like the behavior of other editors varies widely, Sublime and Atom behave the same currently, but TextMate has different end of line behavior (it seems to transpose the entire line when run at the end of the line)
