### ISSUE TITLE
Atom fails to fully start

### ISSUE THREAD

**Issue by nickelpro** [atom/atom#5412]
Arch Linux, latest git

Atom dies on something, spits this out in chrome console

```
TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:472:13)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/coffee-cache.js:14:19)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/coffee-cache.js:106:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/6to5.js:138:21)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:55:5)
```

**Comment by stramel** [comment]
I am running into the same thing when building from the latest git.

**OS:** Ubuntu 14.04
**Atom:** master branch (83c8d904cf)

It seems to fail off on the
```console
$ sudo script/grunt install
```

when running in verbose mode:
```console
$ sudo script/grunt install -v
...
Writing /usr/local/share/atom/version...OK
Copied /tmp/atom-build/Atom to /usr/local/share/atom.
Reading package.json...OK
Parsing package.json...OK
Warning: executable is not defined Use --force to continue.

Aborted due to warnings.
```

When building from the latest tag, there is no issue.

**Comment by thomasjo** [comment]
@stramel Your issue is not the same as reported by @nickelpro; his problem is a runtime issue, whereas yours is related to installation. I would suggest you open a separate issue for your problem.

**Comment by stramel** [comment]
@thomasjo When running `--force` on the `install` task, I get the exact same error message. But I will go ahead and open it in a separate issue.

**Comment by kevinsawicki** [comment]
@nickelpro in the dev tools console tab can you run `process.env.ATOM_HOME` and see what the value is?

**Comment by jbt** [comment]
I'm seeing this as well, ubuntu 14.04, for me `process.env.ATOM_HOME` is `undefined`

**Comment by stramel** [comment]
@kevinsawicki I am now seeing the same issue. 

```console
> process.env.ATOM_HOME
< undefined
```

**Comment by kevinsawicki** [comment]
Sorry about this one, this should be fixed on master now.

Looks like Linux behaves differently than Mac in terms of how environment variables are inherited between the browser and render processes that Atom spawns.

**Comment by stramel** [comment]
:+1: This solves the issue for me! Thanks @kevinsawicki, you are on a roll today.
