### ISSUE TITLE
About Input Method Editor and `onDidChange`

### ISSUE THREAD

**Issue by chrisyip** [atom/atom#5414]
Please take a look at this issue first: https://github.com/atom-community/autocomplete-plus/pull/244.

I noticed that when typing with IME, Atom fires `onDidChange` on each keypress, but it's a performance waste. Because of IME only transform characters into REAL words when `enter` or `whitespace` is hit. Before that, editor should do nothing. 

I suggest:
- If `compositionstart` fired, stop sending `onDidChange`
- If `compositionend` fired, send `onDidChange` with new values
- Add events for CompositionEvents, e.g. `onCompositionStart`

More info about `CompositionEvents`: https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent .

**Comment by jacekkopecky** [comment]
I would also add that on `compositionupdate`, `onDidChange` should not be sent either.

This is an issue that causes atom/vim-mode#791: we are using a transient editor to get a single character from the user. For example, if the user is typing `alt-e`+`e` on a US mac keyboard, we don't know when the editor says it added `´` (which happens after `alt-e`) that the user is compositing and actually about to finish typing `é`.
