### ISSUE TITLE
Uncaught Error: spawn puppet-lint ENOENT

### ISSUE THREAD

**Issue by Ichtaina** [atom/atom#5415]
Uncaught Error: spawn puppet-lint ENOENT

**Atom Version**: 0.154.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At events.js:85

Error: spawn puppet-lint ENOENT
  at exports._errnoException (util.js:742:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1051:32)
  at child_process.js:1142:20
  at process._tickCallback (node.js:378:11)

```

**Comment by batjko** [comment]
Looks like you're running an older version of Atom. The latest one is 177, have you tried upgrading Atom and then all your plugins, and seeing if the problem persists?

**Comment by 50Wliu** [comment]
In addition, upgrading Atom will produce a better error message for this.
