### ISSUE TITLE
Package config only appears after package is activated

### ISSUE THREAD

**Issue by Arcath** [atom/atom#5416]
This issue has cropped up in a couple of places and ultimately here: https://github.com/atom/settings-view/issues/356

I believe the issue is with `/src/package.coffee` and could be solved with calling `activateConfig()` in `load()` so that the defaults are loaded with the package but it will probably need a bit more tweaking than that.

**Comment by maxbrunsfeld** [comment]
We don't want to apply a package's configuration settings if it is disabled, so moving `activateConfig` to `load` won't work. I think the `settings-view` issue you referenced could be fixed within the `settings-view` package. When viewing the settings for an enabled package that has not yet been activated, the package should probably be activated.

**Comment by Arcath** [comment]
Atom's core still returns settings that are in the users own config. In the case of my plugin on my Atom this means that I see 1 setting in the list before activation and then 8 when I activate the package.

I suppose that getting `settings-view` to activate the package when you view the config does mean that we don't have to load the config schema from every package on load.

**Comment by maxbrunsfeld** [comment]
Yeah, so I think the settings-view issue pretty much captures the problem. I'm going to close this in favor of that issue.

**Comment by Arcath** [comment]
Yeah I've opened a pull request with a fix in, seems pretty easy to fix with settings-view

https://github.com/atom/settings-view/pull/371
