### ISSUE TITLE
Unable to update Atom on Linux using Master

### ISSUE THREAD

**Issue by stramel** [atom/atom#5419]
I am unable to update Atom to the latest commit on `master`.

**OS:** Ubuntu 14.04
**Atom:** master branch (83c8d904cf)

It seems to fail on the `install` task
```console
$ sudo script/grunt install
```

When running in verbose mode:
```console
$ sudo script/grunt install -v
...
Writing /usr/local/share/atom/version...OK
Copied /tmp/atom-build/Atom to /usr/local/share/atom.
Reading package.json...OK
Parsing package.json...OK
Warning: executable is not defined Use --force to continue.

Aborted due to warnings.
```

When building from the latest tag, there is no issue.

**Comment by kevinsawicki** [comment]
Can you run `sudo script/grunt install --stack`?

**Comment by kevinsawicki** [comment]
Sorry about this regression, should be fixed now on master, let me know how it goes.

**Comment by stramel** [comment]
@kevinsawicki Thank you for the quick fix, that solved it! No worries, it's part of the risk of using the master branch. I enjoy using the bleeding edge and helping find issues like this.
