### ISSUE TITLE
open dialog for atom config directory is misleading

### ISSUE THREAD

**Issue by rbellamy** [atom/atom#5426]
When launching atom:
```
2015-02-05 16:07:09
rbellamy@eanna i ~ % atom
++ uname
+ '[' Linux == Darwin ']'
+++ uname -s
++ expr substr Linux 1 5
+ '[' Linux == Linux ']'
+ OS=Linux
+ getopts :wtfvh-: opt
+ '[' ']'
+ '[' Linux == Mac ']'
+ '[' Linux == Linux ']'
++ readlink -f /usr/bin/atom
+ SCRIPT=/usr/bin/atom
+++ dirname /usr/bin/atom
++ readlink -f /usr/bin/..
+ USR_DIRECTORY=/usr
+ ATOM_PATH=/usr/share/atom/atom
+ ATOM_HOME=/home/rbellamy/.config/atom
+ export PYTHON=/usr/bin/python2
+ PYTHON=/usr/bin/python2
+ mkdir -p /home/rbellamy/.config/atom
+ : /tmp
+ '[' -x /usr/share/atom/atom ']'
+ '[' ']'
+ trap on_die SIGQUIT SIGTERM
+ '[' ']'
++ pwd
+ nohup /usr/share/atom/atom --executed-from=/home/rbellamy --pid=29059
2015-02-05 16:07:11
rbellamy@eanna i ~ % echo $ATOM_HOME
/home/rbellamy/.config/atom

```
And then when atom opens, it's clearly not using $ATOM_HOME, which is set to ~/.config/atom, not ~/.atom.

![selection 396x364 20150205160728-0800](https://cloud.githubusercontent.com/assets/94763/6072023/497e7fa6-ad51-11e4-8456-e1da28d15d42.png)

However, when you open the folder, and copy the full path, or open in file manager, it is pointed at the correct directory.

**Comment by kevinsawicki** [comment]
So it is just that one button that is wrong? Or are there other places that `ATOM_HOME` isn't being used?

**Comment by rbellamy** [comment]
You got it right and your solution solves the problem.

**Comment by kevinsawicki** [comment]
Great, thanks for reporting this, it was nice to catch it before it was released.
