### ISSUE TITLE
Cannot save: Uncaught ReferenceError: spawnSync is not defined

### ISSUE THREAD

**Issue by mattpwest** [atom/atom#5431]
I had this error before, realised I was on a rather old version of Atom and updated to the latest  (0.153 on Windows 7 64-bit). The update resolved the issue for a while, but now it's back again.

Steps to reproduce:
1. Start Atom
2. Open my timesheet.txt file
3. Make changes
4. Try to save (Ctrl-S or File->Save)

At this point Atom fails to save the file (blue 'unsaved' icon remains and changes are not saved to disk).

There are two errors visible in the developer tools (with full stacktraces):
![atomcannotsavetrace](https://cloud.githubusercontent.com/assets/6697562/6075274/d816d3ea-add7-11e4-8b07-89cf96117d67.png)

I initially thought this may be related to the file being in a Dropbox folder, but I just tried a folder in My Documents as well and it exhibits the same behaviour.

**Comment by 50Wliu** [comment]
0.153 is not the latest version-the latest version is currently 0.177.0.

**Comment by mattpwest** [comment]
As mentioned in a PM, 0.153 was not actually the latest version...

I now have a 0.177 installation and the problem seems to have gone away again.
