### ISSUE TITLE
styles.less no longer being applied

### ISSUE THREAD

**Issue by benplumley** [atom/atom#5438]
I recently updated from 150 to 177, and my styles.less is no longer applied. Deprecation Cop tells me that `editor` is now `atom-text-editor`, but doesn't specify this error existing in styles.less. I've changed it to reflect this and it's still not being applied.

**Comment by kevinsawicki** [comment]
Can you provide a snippet from your `~/.atom/styles.less` file that isn't being applied correctly?

**Comment by benplumley** [comment]
The following doesn't work now or before I changed `editor` to `atom-text-editor`.

    .atom-text-editor .cursor {
      border-color: lime;
      border-left-width: 2px;
      margin-left: -1px;
    }

    .bracket-matcher {
      background-color: #49483E;
      border: 1px dotted lime;
    }

    .atom-text-editor.is-focused .cursor {
      transition: opacity .2s;
      &.blink-off {
        visibility: visible;
        opacity: 0;
      }
    }

**Comment by 50Wliu** [comment]
`atom-text-editor`, not `.atom-text-editor`.

**Comment by kevinsawicki** [comment]
Good :eyes: @50Wliu, yeah, it needs to be an element selector, `atom-text-editor`.

Closing this out.

**Comment by benplumley** [comment]
Good spot, but no fix. Removing the dots does nothing, and `.bracket-matcher` shouldn't be affected because it's not inside `atom-text-editor`.

**Comment by kevinsawicki** [comment]
Try this:

```css
atom-text-editor::shadow .cursor {
  border-color: lime;
  border-left-width: 2px;
  margin-left: -1px;
}

```

**Comment by kevinsawicki** [comment]
And this:


```
atom-text-editor::shadow .bracket-matcher {
  background-color: #49483E;
  border: 1px dotted lime;
}
```

**Comment by kevinsawicki** [comment]
This is related to https://github.com/atom/deprecation-cop/issues/18

**Comment by benplumley** [comment]
What about

    atom-text-editor .wrap-guide {
        background-color: #282828;
    }

I've tried sticking `::shadow` in there but it doesn't change. This has also given the bracket matcher some funky formatting but that's another issue.

**Comment by kevinsawicki** [comment]
This wrap-guide CSS works for me:

```css
atom-text-editor .wrap-guide {
  background-color: red;
}
```

**Comment by benplumley** [comment]
Funny, I replaced mine with that in case there was a subtle difference and it didn't change. If it's not reproducible then I'm not too worried, it'll probably fix itself after an update.

**Comment by kevinsawicki** [comment]
I wonder if this could be at all related to https://github.com/atom/atom/issues/5337
