### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/etc/apache2/envvars'

### ISSUE THREAD

**Issue by stefanikolov** [atom/atom#5446]
Uncaught Error: EACCES, permission denied '/etc/apache2/envvars'

**Atom Version**: 0.153.0
**System**: linux 3.13.0-45-generic
**Thrown From**: Atom Core

**Comment by batjko** [comment]
Looks like you're on an old version. Could you try upgrading to (currently) v177?

That being said, the error seems to be with apache, rather than atom? Not sure why Atom would access any apache files, but I may have missed something.
What were you working on when the error occurred?

**Comment by 50Wliu** [comment]
It looks like @stefanikolov was just trying to open that file and got a permission error.  Those should be fixed in the latest version.
