### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by hkrdrm** [atom/atom#5450]
Uncaught TypeError: Cannot read property 'querySelector' of null

**Atom Version**: 0.153.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [color-picker](https://github.com/thomaslindstrom/color-picker) package

**Comment by 50Wliu** [comment]
Could you please upgrade Atom and all your packages to the latest versions and see if you can still reproduce this?

**Comment by hkrdrm** [comment]
that fixed it thanks
