### ISSUE TITLE
KDE taskswitcher takes longer if Atom is open

### ISSUE THREAD

**Issue by m1ga** [atom/atom#5453]
I have a strange "problem":

when I have Firefox and Kontact open the Taskswitcher (Alt+Tab) opens immediately. When I have atom open it takes longer (most a second). Could it be that the icon is too large/complex (svg?).

Its not a big deal but perhaps this could be easily improved and it feels better to switch tasks.

Atom 0.178.0-9105348
KDE 4.14.3

**Comment by DarkArc** [comment]
I notice no difference on my system running Plasma 5, this is probably something that should -- or already has been -- handled at a KDE level.

**Comment by m1ga** [comment]
did some tests today. When I copy the 256.png into /usr/local/share/atom/resources/app/resources/atom.png its as quick as before! So perhaps it would be good not to use the 1024px icon as a preview (since the taskswitcher is ways smaller)

**Comment by Petemir** [comment]
I have a problem that It's 

![snapshot-atom](https://cloud.githubusercontent.com/assets/287105/8894559/6c3a0efe-3391-11e5-8300-20b11d00c4f3.png)

**Comment by DarkArc** [comment]
@Petemir That's definitely something that needs to be addressed by KDE developers, though could be made better on Atom's part by reducing the icon size.

**Comment by Petemir** [comment]
Ok @DarkArc, I've reported it [there](https://bugs.kde.org/show_bug.cgi?id=350645). At first I thought it was atom's problem because I only noticed it with that app, but just today I ran another new app and it also happened. Thanks and sorry for the off-topic.
