### ISSUE TITLE
How do I remove commands when I deactivate a package?

### ISSUE THREAD

**Issue by jonmagic** [atom/atom#5454]
I can't seem to figure out how to remove commands I added using `atom.commands.add` from the command registry later when I deactivate a package. Is this a design decision or would you be open to a PR adding an `atom.commands.remove` feature?

**Comment by steelbrain** [comment]
```
var LeDisposible = atom.commands.add ... // Add it
LeDisposible.dispose(); // Remove it
```

**Comment by jonmagic** [comment]
Ahhh :) ok cool, thanks!
