### ISSUE TITLE
Website: can't find builds for other platforms

### ISSUE THREAD

**Issue by AgentME** [atom/atom#5455]
I was thinking about recommending Atom to a friend, and I went to the https://atom.io/ to see if there were Windows builds. The site saw I was on Linux, showed me the .deb and .rpm links, and a link for "Other platforms". That page contained this text:

>Prebuilt versions of Atom are available for OS X 10.8 or later, Windows 7 & 8, RedHat Linux, and Ubuntu Linux.

but doesn't link to them or really inspire confidence that they do exist somewhere. It seems like I'd be out of luck if I wanted to save one of their installers to a flash drive to install on another computer offline.

**Comment by mehcode** [comment]
I'd bet that they are using the user agent and only showing downloads for your platform. However I think that the *Other Platforms* button should take me to somewhere that have download buttons for other platforms.

**Comment by lee-dohm** [comment]
You can find the installers and all of the built versions on the releases page here on the repository:

https://github.com/atom/atom/releases

**Comment by mehcode** [comment]
@lee-dohm That's not the point. The point is the *website* doesn't show it.

**Comment by thedaniel** [comment]
![screen shot 2015-02-08 at 10 18 24 pm](https://cloud.githubusercontent.com/assets/1476/6101862/74404b84-afe0-11e4-9ae2-1991099d0c38.png)

**Comment by batjko** [comment]
Interestingly, the "Other platforms" link leads to the 'Building' section of the instructions.

It would indeed make sense to just have a direct link to the other installers, either the ['Installing' section](https://github.com/atom/atom/blob/master/README.md#installing) instead, or maybe the releases page for the current version.

**Comment by thedaniel** [comment]
That makes sense - that was last updated when there was only an installer for OS X.

**Comment by lee-dohm** [comment]
@thedaniel On OS X, the "Other platforms" link just leads to the [FAQ](https://atom.io/faq).

**Comment by mnquintana** [comment]
Related to (or duplicate of) atom/apm#266

**Comment by batjko** [comment]
Yes, although that one shouldn't have been on the apm repo. I'd close that other one instead.

**Comment by mnquintana** [comment]
@batjko, @kevinsawicki [mentioned on Discuss](https://discuss.atom.io/t/is-atom-io-atoms-website-open-sourced/14197/9?u=mnquintana) that it was better to open there than atom/atom.

**Comment by batjko** [comment]
Ah I see. Apologies, I didn't know they use that repo for the atom.io website as well.

**Comment by lee-dohm** [comment]
Ah, thanks @mnquintana! I'll close this as duplicate then since the other one is also already assigned to @thedaniel.
