### ISSUE TITLE
Can't navigate with ctrl key

### ISSUE THREAD

**Issue by Chris2011** [atom/atom#5457]
In maybe each applications, like notepad++, Netbeans IDE, Browser, Sublime Text and so on, I can navigate through words with holding ctrl key. I can use ctrl + backspace to delete the word before the cursor and ctrl + del to delete the word after the cursor. All this functionality is not possible inside atom. I use windows 7 64bit. I figured out, that ctrl + del is the same as ctrl + backspace, but this is not the correct behaviour. See the screenshot, for what I mean in sublime text 2.
![sublimebehaviour](https://cloud.githubusercontent.com/assets/795658/6102807/99dfbcba-b03c-11e4-8c1c-45af645bc346.gif)

**Comment by abe33** [comment]
Are you sure you haven't some keybinding that overrides the defaults? Looking at the keymap file for windows there's the proper bindings for text editor navigation: https://github.com/atom/atom/blob/master/keymaps/win32.cson#L81-L86

**Comment by Chris2011** [comment]
Thx, I will have a look. I installed atom and 2 plugins for show open files and the minimap, nothing more.

**Comment by Chris2011** [comment]
Ok, it works. Sry I had tested an old version, after I installed the new one. I used the old version of atom as a portable version in an other folder ^^. My failure. Works as expected.
