### ISSUE TITLE
.atomrc?

### ISSUE THREAD

**Issue by kevinSuttle** [atom/atom#5460]
Wondering if it would be easier to have an `~.atomrc` file instead of the 5 config files and extra folders in `~/.atom`. Could be easier to sync and keep in git perhaps. Open Atom, give it a gist or repo URL with your `.atomrc` file in it. :boom: 

On second thought, I guess customization would become a lot harder if the `.atomrc` route was taken. Maybe just keeping those 5 config files separate would be a good solution? Not sure of the feasibility or repercussions.

**Comment by icewind** [comment]
+1 would be a way more comfortable

**Comment by mnquintana** [comment]
What would make this tricky though is that those 5 config files aren't all the same language – some are CSON, one is Less (or CSS), and one is CoffeeScript (or JS). I for one wouldn't want to have to try to edit CSS inside of a CSON string in an `.atomrc` file.

**Comment by lee-dohm** [comment]
In addition to @mnquintana's points, there would still need to be an `~/.atom` directory for the `packages`, `dev/packages` and `storage` folders. There's no way that we could squash the 40 packages I have installed into a single file and make it as intelligible and flexible as the directory structure that exists now ... especially if you take into account the ease that symlinking adds to development.

I keep all my dotfiles in a GitHub repo, including my [Atom configuration files](https://github.com/lee-dohm/dotfiles/tree/master/atom). I know lots of people that sync their `~/.atom` directories using Dropbox. So I'm not even sure that this would make syncing any easier than either of those solutions.

**Comment by kevinsawicki** [comment]
Yeah, @lee-dohm brings up the major points why this isn't really achievable.

It should be pretty simple to version some/all of your `~/.atom` folder using a simple [dotfiles](https://dotfiles.github.io/) repo with a `.gitignore` file that decides which pieces you want to keep there (config files, packages, etc).

**Comment by kevinSuttle** [comment]
Good points all around, the same conclusions I quickly came to. However, as far as packages go, couldn't we have a list, like package.json or a gemfile where we could install them later? That way, we could just store 6 text files in git. Just seems like user-specific settings should be kept separate from packages (though I realize they each have their own settings also).

**Comment by mnquintana** [comment]
@kevinSuttle You can do that with `apm list`:

`apm list --bare --installed --no-dev > atom-packages.txt`

and 

`apm install --packages-file atom-packages.txt`

**Comment by kevinSuttle** [comment]
@mnquintana That's cool, but it'd be nicer to have a native config file, so I can install them from the CLI or UI if I wanted. 

The main point is to separate the user's config from the package and storage folders for easier syncing and versioning.

**Comment by bucaran** [comment]
There should be both `.atomrc.cson` and `.atomkey` files with configuration that is applied after Atom loads `.atom/config.cson` and `.atom/keymap.cson`.

**Comment by brunowego** [comment]
+1 `.atomrc` per project.

**Comment by sunnypatel** [comment]
+1 .atomrc per project
See here for another use case : https://github.com/atom/atom/issues/6619

**Comment by kevinSuttle** [comment]
There is a way to hack this, but only for packages you've starred, not your settings.
http://blog.atom.io/2014/06/09/stars.html
