### ISSUE TITLE
Key-bindings are using the english keyboard

### ISSUE THREAD

**Issue by DLade** [atom/atom#5461]
I'm using a german keyboard, but the key-bindings are mapped to english keyboard.

For exampel "toggle comment" is set to CTRL-/, though I need to press CTRL-# (because on the english keyboard the / is here). But on the german keyboard "/" is SHIFT-7, therefore "toggle comment" shall be CTRL-SHIFT-7.

english: "toggle comment" - CTRL-/
german: "toggle comment" - CTRL-SHIFT-7

**Comment by 50Wliu** [comment]
Please see atom/atom-keymap#37 and atom/atom-keymap#35 for details on this.
