### ISSUE TITLE
Unchecking `Show Invisibles` has no effect in js files

### ISSUE THREAD

**Issue by stebru** [atom/atom#5463]
Version 0.177.0 (0.177.0)
Mac OS X 10.10.2

https://gyazo.com/5951801f91f908b6e370b6083eea9273
https://gyazo.com/e4f44be12c4c6199f12824f2c1461cb7

**Comment by izuzak** [comment]
I'm having trouble reproducing this. 

Can you reproduce this in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)? Is this happening only for some JS files or all JS files? Is it happening for other file types? Is this happening only in one project or all projects?

**Comment by stebru** [comment]
Just tried in safe mode, and the issue persists. This happens for all JS files, and no other file types. It also happens in all projects.

**Comment by izuzak** [comment]
These config options for showing invisibles are available for individual languages as well. Are you changing the global option or the one for JavaScript?

![screen shot 2015-02-09 at 15 20 15](https://cloud.githubusercontent.com/assets/38924/6107942/54326d88-b06f-11e4-8d84-480fcbca525d.png)

Can you try changing the one in the language-javascript package?

**Comment by mnquintana** [comment]
Can you go to Settings > Packages > language-javascript and see if Show Invisibles is checked there? Each language grammar has its own editor settings.

**Comment by stebru** [comment]
Ah, silly me. Yes, that certainly did help. Thanks :smile:

**Comment by izuzak** [comment]
Happy to hear that. :) Closing this then
