### ISSUE TITLE
Failed to spawn command

### ISSUE THREAD

**Issue by Gouvi** [atom/atom#5464]
Most likely an error on my behalf but I have tried to remove all traces of Atom, performed a fresh install and am still receiving:

`Failed to spawn command`
`C:\Users\<user>\AppData\Local\atom\app-0.177.0\resources\app\apm\bin\apm.cmd`
`.make sure `
`C:\Users\<user>\AppData\Local\atom\app-0.177.0\resources\app\apm\bin\apm.cmd`
`is installed and on your PATH`

I have added it to my path, other than that I have no clue.

Thanks!

**Comment by izuzak** [comment]
@Gouvi What did you do exactly to trigger that error? When does it happen?

**Comment by Gouvi** [comment]
It triggers any time I load Atom.

It started happening when I tried installing a package, php-lint I believe, not 100% sure package could have possibly caused it.

**Comment by izuzak** [comment]
@Gouvi Does Atom load and then you see the error or it doesn't load at all? Can you try running Atom in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by Gouvi** [comment]
Atom loads and I can use it fine with the exception of accessing packages. When accessing packages it simply reproduces the error with another dialogue box and console error.

Dialogue box:
![failed to spawn command](https://cloud.githubusercontent.com/assets/6964274/6106268/ed20129a-b09a-11e4-819b-35b690af156a.PNG)


Console error:
![console](https://cloud.githubusercontent.com/assets/6964274/6106278/151899c0-b09b-11e4-90b1-2a47a10a4067.PNG)

**Comment by kevinsawicki** [comment]
@Gouvi Can you check what is in the `C:\Users\<user>\AppData\Local\atom\app-0.177.0\resources\app\apm\bin` folder?

**Comment by Gouvi** [comment]
@kevinsawicki Just the following Kevin:
![bin](https://cloud.githubusercontent.com/assets/6964274/6119576/a7609750-b105-11e4-8aa3-60de03023a92.PNG)

**Comment by kevinsawicki** [comment]
So it looks like `C:\Users\<user>\AppData\Local\atom\app-0.177.0\resources\app\apm\bin\apm.cmd` does exist then right?

**Comment by Gouvi** [comment]
That's right.

**Comment by Gouvi** [comment]
If I try to run the script it says it cannot find itself. If I run it as an Administrator it runs, but needs commands to do anything as you would know.

I have set Atom to always run as an Administrator, this did not fix the issue.

**Comment by dominicbetts** [comment]
@gouvi Did you resolve this issue? I'm seeing exactly the same behaviour.

**Comment by Gouvi** [comment]
@dominicbetts No, I couldn't work it out. I have stopped using Atom because of this unfortunately. Started using PHPStorm which has been brilliant!

@kevinnathan was last having a look at it, he had been making commits to this file. Maybe when he figures it out it will be sorted.

**Comment by mark-hahn** [comment]
> . Started using PHPStorm which has been brilliant!

My editor-of-choice for years was webstorm.  It was awesome, much better
than sublime.

FWIW, I am now able to use Atom with the same webstorm feature set by
choice of packages and writing some of my own.  And now I like Atom much
more because I am using features beyond webstorm that I love.  And I can
customize every little detail of UX behavior including the few annoyances
in webstorm, like not being able to dbl-click to select whitespace.

Don't give up.

**Comment by jelmerdemaat** [comment]
I'm having the exact same issue with almost any command inside Atom.
I recently updated npm to 2.x, could that be a problem?

**Comment by dominicbetts** [comment]
I think this maybe a problem with my Windows settings. I can run .bat and .cmd files from a command prompt, but double-clicking any .bat or .cmd file results in the same error (unless I try it with admin rights, in which case it works). Once I've figured out how to fix this in Windows, I'll try Atom again.

**Comment by eSedano** [comment]
@dominicbetts Did you manage to fix it? I'm having the same issue here...

**Comment by dominicbetts** [comment]
The problem has disappeared now that I've upgraded my OS to the Windows 10 beta. 
It was definitely a problem with my Windows 8.1 installation and not Atom because of the general problem of not being able to run a cmd file by double-clicking...

**Comment by eSedano** [comment]
@dominicbetts Ok, thanks! I'll have to figure out why is it not working then in my Windows 7. Buty I'm having the same issue with the double-clicking, so...

**Comment by LorenzLeitner** [comment]
I have the same error even  a clean reinstall.

It popped up after I installed flake8, but only the next day.

**Comment by damieng** [comment]
Tracking this and other bugs under a central bug https://github.com/atom/atom/issues/11450
