### ISSUE TITLE
Atom not finding package updates

### ISSUE THREAD

**Issue by Ajedi32** [atom/atom#5467]
I am experiencing an issue very similar to the one described in #5213. However, I'm using a version of Atom/APM which was supposedly fixed (Atom v0.177.0, APM v1.3.4), and I'm not running a version of atom with a commit hash in the version number (as was the case in #5213).

Specifically, I'm trying to update my installation of the [web-browser][] plugin from 1.1.3 to 1.1.6. Unfortunately, neither APM nor atom seem to recognise that the plugin has an update available.

APM says:

```
Ajedi32@LAPTOP /c/Sites
$ apm --version
apm  0.134.0
npm  2.3.0
node 0.10.35
python
git 1.7.9.msysgit.0
visual studio 2012

Ajedi32@LAPTOP /c/Sites
$ apm update
Package Updates Available (0)
└── (empty)

Ajedi32@LAPTOP /c/Sites
$ apm list
Built-in Atom packages (83)
├── archive-view@0.46.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.46.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.40.0
├── autocomplete@0.44.0
├── autoflow@0.21.0
├── autosave@0.20.0
├── background-tips@0.22.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.71.0
├── command-palette@0.34.0
├── deprecation-cop@0.34.0
├── dev-live-reload@0.41.0
├── encoding-selector@0.17.0
├── exception-reporting@0.21.0
├── find-and-replace@0.156.0
├── fuzzy-finder@0.65.0
├── git-diff@0.50.0
├── go-to-line@0.30.0
├── grammar-selector@0.44.0
├── image-view@0.48.0
├── incompatible-packages@0.21.0
├── keybinding-resolver@0.27.0
├── language-c@0.38.0
├── language-clojure@0.10.0
├── language-coffee-script@0.39.0
├── language-css@0.26.0
├── language-gfm@0.63.0
├── language-git@0.10.0
├── language-go@0.21.0
├── language-html@0.28.0
├── language-hyperlink@0.12.2
├── language-java@0.14.0
├── language-javascript@0.56.0
├── language-json@0.11.0
├── language-less@0.24.0
├── language-make@0.13.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.10.0
├── language-php@0.20.0
├── language-property-list@0.8.0
├── language-python@0.30.0
├── language-ruby@0.47.0
├── language-ruby-on-rails@0.18.0
├── language-sass@0.31.0
├── language-shellscript@0.12.0
├── language-source@0.9.0
├── language-sql@0.14.0
├── language-text@0.6.0
├── language-todo@0.16.0
├── language-toml@0.15.0
├── language-xml@0.27.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.132.0
├── metrics@0.41.0
├── notifications@0.26.0
├── one-dark-syntax@0.2.0
├── one-dark-ui@0.2.0
├── one-light-syntax@0.2.0
├── one-light-ui@0.1.0
├── open-on-github@0.32.0
├── package-generator@0.37.0
├── release-notes@0.47.0
├── settings-view@0.174.0
├── snippets@0.72.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.54.0
├── status-bar@0.57.0
├── styleguide@0.43.0
├── symbols-view@0.81.0
├── tabs@0.64.0
├── timecop@0.28.0
├── tree-view@0.154.0
├── update-package-dependencies@0.7.0
├── welcome@0.21.0
├── whitespace@0.28.0
└── wrap-guide@0.31.0

C:\Users\Ajedi32\.atom\packages (8)
├── css-snippets@0.5.0
├── html-helper@0.2.3
├── linter@0.11.1
├── linter-csslint@0.0.11
├── linter-javac@0.1.3
├── preview-plus@1.1.19
├── web-browser@1.1.3
└── webbox-color@0.5.4
```

And Atom's UI says:

![Atom package screenshot](https://cloud.githubusercontent.com/assets/1876931/6108726/071840c4-b03b-11e4-8fc5-1472c44f1a1f.png)
![No updates available](https://cloud.githubusercontent.com/assets/1876931/6108757/46dfedec-b03b-11e4-9eae-94305ff54ae2.png)

Even though atom.io clearly shows that the latest version of the package is 1.1.6:

![web-browser package is version 1.1.6](https://cloud.githubusercontent.com/assets/1876931/6108795/8eba6a16-b03b-11e4-8da3-4ede1719c150.png)

I tried uninstalling and then reinstalling web-browser using APM, but I just ended up with an *older* version of web-browser instead:

```
Ajedi32@LAPTOP /c/Sites
$ apm uninstall web-browser
Uninstalling web-browser done

Ajedi32@LAPTOP /c/Sites
$ apm install web-browser
Installing web-browser to C:\Users\Ajedi32\.atom\packages done

Ajedi32@LAPTOP /c/Sites
$ apm list
Built-in Atom packages (83)
├── archive-view@0.46.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.46.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.40.0
├── autocomplete@0.44.0
├── autoflow@0.21.0
├── autosave@0.20.0
├── background-tips@0.22.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.71.0
├── command-palette@0.34.0
├── deprecation-cop@0.34.0
├── dev-live-reload@0.41.0
├── encoding-selector@0.17.0
├── exception-reporting@0.21.0
├── find-and-replace@0.156.0
├── fuzzy-finder@0.65.0
├── git-diff@0.50.0
├── go-to-line@0.30.0
├── grammar-selector@0.44.0
├── image-view@0.48.0
├── incompatible-packages@0.21.0
├── keybinding-resolver@0.27.0
├── language-c@0.38.0
├── language-clojure@0.10.0
├── language-coffee-script@0.39.0
├── language-css@0.26.0
├── language-gfm@0.63.0
├── language-git@0.10.0
├── language-go@0.21.0
├── language-html@0.28.0
├── language-hyperlink@0.12.2
├── language-java@0.14.0
├── language-javascript@0.56.0
├── language-json@0.11.0
├── language-less@0.24.0
├── language-make@0.13.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.10.0
├── language-php@0.20.0
├── language-property-list@0.8.0
├── language-python@0.30.0
├── language-ruby@0.47.0
├── language-ruby-on-rails@0.18.0
├── language-sass@0.31.0
├── language-shellscript@0.12.0
├── language-source@0.9.0
├── language-sql@0.14.0
├── language-text@0.6.0
├── language-todo@0.16.0
├── language-toml@0.15.0
├── language-xml@0.27.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.132.0
├── metrics@0.41.0
├── notifications@0.26.0
├── one-dark-syntax@0.2.0
├── one-dark-ui@0.2.0
├── one-light-syntax@0.2.0
├── one-light-ui@0.1.0
├── open-on-github@0.32.0
├── package-generator@0.37.0
├── release-notes@0.47.0
├── settings-view@0.174.0
├── snippets@0.72.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.54.0
├── status-bar@0.57.0
├── styleguide@0.43.0
├── symbols-view@0.81.0
├── tabs@0.64.0
├── timecop@0.28.0
├── tree-view@0.154.0
├── update-package-dependencies@0.7.0
├── welcome@0.21.0
├── whitespace@0.28.0
└── wrap-guide@0.31.0

C:\Users\Ajedi32\.atom\packages (8)
├── css-snippets@0.5.0
├── html-helper@0.2.3
├── linter@0.11.1
├── linter-csslint@0.0.11
├── linter-javac@0.1.3
├── preview-plus@1.1.19
├── web-browser@0.2.3
└── webbox-color@0.5.4
```

So I removed web-browser again:

```
Ajedi32@LAPTOP /c/Sites
$ apm uninstall web-browser
Uninstalling web-browser done
```

And reinstalled it from the Atom UI:

![Atom install web-browser v1.1.6](https://cloud.githubusercontent.com/assets/1876931/6108930/aa24fe1e-b03c-11e4-953e-9d2be1b2c109.png)

And *that* finally resulted in the correct version of web-browser being installed:

```
Ajedi32@LAPTOP /c/Sites
$ apm list
Built-in Atom packages (83)
├── archive-view@0.46.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.46.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.40.0
├── autocomplete@0.44.0
├── autoflow@0.21.0
├── autosave@0.20.0
├── background-tips@0.22.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.71.0
├── command-palette@0.34.0
├── deprecation-cop@0.34.0
├── dev-live-reload@0.41.0
├── encoding-selector@0.17.0
├── exception-reporting@0.21.0
├── find-and-replace@0.156.0
├── fuzzy-finder@0.65.0
├── git-diff@0.50.0
├── go-to-line@0.30.0
├── grammar-selector@0.44.0
├── image-view@0.48.0
├── incompatible-packages@0.21.0
├── keybinding-resolver@0.27.0
├── language-c@0.38.0
├── language-clojure@0.10.0
├── language-coffee-script@0.39.0
├── language-css@0.26.0
├── language-gfm@0.63.0
├── language-git@0.10.0
├── language-go@0.21.0
├── language-html@0.28.0
├── language-hyperlink@0.12.2
├── language-java@0.14.0
├── language-javascript@0.56.0
├── language-json@0.11.0
├── language-less@0.24.0
├── language-make@0.13.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.10.0
├── language-php@0.20.0
├── language-property-list@0.8.0
├── language-python@0.30.0
├── language-ruby@0.47.0
├── language-ruby-on-rails@0.18.0
├── language-sass@0.31.0
├── language-shellscript@0.12.0
├── language-source@0.9.0
├── language-sql@0.14.0
├── language-text@0.6.0
├── language-todo@0.16.0
├── language-toml@0.15.0
├── language-xml@0.27.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.132.0
├── metrics@0.41.0
├── notifications@0.26.0
├── one-dark-syntax@0.2.0
├── one-dark-ui@0.2.0
├── one-light-syntax@0.2.0
├── one-light-ui@0.1.0
├── open-on-github@0.32.0
├── package-generator@0.37.0
├── release-notes@0.47.0
├── settings-view@0.174.0
├── snippets@0.72.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.54.0
├── status-bar@0.57.0
├── styleguide@0.43.0
├── symbols-view@0.81.0
├── tabs@0.64.0
├── timecop@0.28.0
├── tree-view@0.154.0
├── update-package-dependencies@0.7.0
├── welcome@0.21.0
├── whitespace@0.28.0
└── wrap-guide@0.31.0

C:\Users\Ajedi32\.atom\packages (8)
├── css-snippets@0.5.0
├── html-helper@0.2.3
├── linter@0.11.1
├── linter-csslint@0.0.11
├── linter-javac@0.1.3
├── preview-plus@1.1.19
├── web-browser@1.1.6
└── webbox-color@0.5.4
```

Weird, huh? Anyone have any ideas on what's going wrong here? I am running:

- Atom v0.177.0
- APM v1.3.4
- Windows 8.1

[web-browser]: https://atom.io/packages/web-browser

**Comment by izuzak** [comment]
It seems that the package in question requires an Atom version _greater than_ 0.177.0 (and you have exactly that version):

https://github.com/mark-hahn/web-browser/blob/40b80b3287ba7d5e4bf26670f14571f15d61c09b/package.json#L10

For that reason (I'm guessing) apm is refusing to install that version, but the settings view UI is allowing to install the version (but not upgrade to it from an older version). I'd say that apm is doing the right thing here, and that it might be a good idea to open an issue on settings-view to not allow such versions to be installed (versions for which you require a more recent version of Atom which you have installed). Does that make sense?

See https://github.com/atom/atom/pull/5417 for a similar issue.

**Comment by Ajedi32** [comment]
Ah, okay that makes sense. Might this be a bug in the package in question, given that I seem to be using the latest version of Atom?

![image](https://cloud.githubusercontent.com/assets/1876931/6110694/086b53a4-b049-11e4-9a6e-42c4b97551d6.png)

**Comment by Ajedi32** [comment]
Also, why the inconsistent behavior between APM and Atom itself? Or are you saying that's been solved by #5417?

**Comment by izuzak** [comment]
> Ah, okay that makes sense. Might this be a bug in the package in question, given that I seem to be using the latest version of Atom?

Not sure, @Ajedi32. I'm using `0.178.0-c33b154` (that the version of the current master). You're using the latest released version, but you can get a more recent version by building yourself from source. 0.178.0 will be the next released version.

**Comment by izuzak** [comment]
> Also, why the inconsistent behavior between APM and Atom itself? 

Not sure, I'd say the Settings View could be improved in that aspect, so I suggested to open an issue on that package's issue tracker. (if you don't do it, I'll open one later today or tomorrow.)

> Or are you saying that's been solved by #5417?

No, I'm not saying that -- sorry for not explaining that reference well. That pull request references another issue in which a user noticed that he was able to install something via the Settings View but wasn't via apm: https://github.com/izuzak/atom-pdf-view/issues/45#issuecomment-72184095. In that sense, the problems are similar.

**Comment by Ajedi32** [comment]
> You're using the latest released version, but you can get a more recent version by building yourself from source. 0.178.0 will be the next released version.

Ah, okay. That's what I figured. I'll raise an issue on the `web-browser` repo, as I don't believe it was the maintainer's intention to require an unreleased version of Atom in order to use the plugin.

**Comment by 50Wliu** [comment]
@Ajedi32 I believe it was.  Web Browser depends on an unreleased fix in order to not crash, right @mark-hahn?

**Comment by Ajedi32** [comment]
Well, as I said Atom's Settings View allowed me to install the latest version of the package anyway, despite the requirement. It doesn't seem to be crashing for me, so I assume the requirement is unnecessary. I'll wait for Mark's response here though before opening that issue.

**Comment by Ajedi32** [comment]
> Not sure, I'd say the Settings View could be improved in that aspect, so I suggested to open an issue on that package's issue tracker.

Ah, okay. Now I understand what you were saying. I didn't realize the settings view was a package; I thought it was part of the core. I'll open a new issue there.
