### ISSUE TITLE
Overlay decorations don't overflow out of the editor

### ISSUE THREAD

**Issue by oclbdk** [atom/atom#5469]
It would be nice if overlay decorations could be positioned outside of the editor, such as for autocomplete. With additional type information, it would be great if we could keep suggestions lined up with what the user is typing.

![screen shot 2015-02-06 at 5 08 19 pm](https://cloud.githubusercontent.com/assets/136982/6114867/24a7bf46-b06f-11e4-8bcf-d6327d6a539a.png)

**Comment by benogle** [comment]
This has been fixed, and has been released. Sorry forgot to close this. Autocomplete-plus also defaults to displaying as shown in the image.
