### ISSUE TITLE
Tooltip "discovery" mode

### ISSUE THREAD

**Issue by simurai** [atom/atom#5476]
@ricardograca suggested https://github.com/atom/tabs/issues/117 to lower the delay for the tooltips of the tabs (already changed). But also:

> Even worse, is that if I jump from tab to tab, it takes another 2+ seconds for the next tooltip to appear. Usually I would expect the next tooltip to show up immediately if I move the cursor through the various tabs.

Might be worth to change it for all tooltips, not just for the tabs. Once a tooltip appears and there is no click, all other tooltips would appear almost instantly (`100s`) until you clicked somewhere. Useful for when you try to get more information of all the available options. Like hovering over all the buttons in Find + Replace.

**Comment by Fank** [comment]
:+1:

**Comment by simurai** [comment]
This got fixed with https://github.com/atom/atom/pull/13095.
