### ISSUE TITLE
Scroll past end no longer work

### ISSUE THREAD

**Issue by abe33** [atom/atom#5477]
I'm currently running Atom 0.178.0-89d5dd3 and the `Scroll Past End` setting is no longer effective. 
Deactivating and reactivating the setting doesn't do much.

I think the change occurred in the past few days.

OS: OSX 10.10.2

**Comment by lee-dohm** [comment]
I just confirmed this using Atom v0.178.0-89d5dd3 on Mac OS X 10.10.2. I believe that this was working until #5293 was merged.

/cc @nathansobo

**Comment by nathansobo** [comment]
Makes sense. I'll take a look in a bit.

**Comment by nathansobo** [comment]
Closed via 711f0a227c087fe5ce50b2f26b4be0cebca47f57.
