### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by andersennl** [atom/atom#5478]
Without any Atom update, suddenly every time I switch to Atom (with an file opened), Atom error panes occur. By the way, the `Create issue on atom/atom` button doesn't work.

```
[Enter steps to reproduce below:]

1. focus an .html.erb file

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/src/task.js:97

TypeError: undefined is not a function
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app/src/task.js:97:27)
  at Task.module.exports.Task.start (/Applications/Atom.app/Contents/Resources/app/src/task.js:88:12)
  at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app/src/task.js:21:18)
  at GitRepository.module.exports.GitRepository.refreshStatus (/Applications/Atom.app/Contents/Resources/app/src/git-repository.js:398:37)
  at /Applications/Atom.app/Contents/Resources/app/src/git-repository.js:81:26

```

### Commands

```
     -2:38.6 core:backspace (atom-text-editor.editor.autocomplete-active)
     -2:38.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.autocomplete-active)
  3x -2:37.5 core:move-left (atom-text-editor.editor.autocomplete-active)
     -2:36.0 core:save (atom-text-editor.editor.autocomplete-active)
     -1:14.1 core:move-right (atom-text-editor.editor.autocomplete-active)
     -1:13.2 core:move-left (atom-text-editor.editor.autocomplete-active)
     -1:04.4 editor:move-to-end-of-screen-line (atom-text-editor.editor.autocomplete-active)
  3x -1:04.2 core:move-left (atom-text-editor.editor.autocomplete-active)
     -1:03.6 core:backspace (atom-text-editor.editor.autocomplete-active)
 10x -1:03.2 editor:move-to-beginning-of-word (atom-text-editor.editor.autocomplete-active)
     -1:01.1 core:move-right (atom-text-editor.editor.autocomplete-active)
  2x -0:59.0 core:save (atom-text-editor.editor.autocomplete-active)
  4x -0:45.5 editor:select-to-beginning-of-word (atom-text-editor.editor.autocomplete-active)
  2x -0:44.8 core:select-left (atom-text-editor.editor.autocomplete-active)
     -0:44.3 core:backspace (atom-text-editor.editor.autocomplete-active)
  2x -0:44.0 core:save (atom-text-editor.editor.autocomplete-active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "RubyMotion",
      "git-log",
      "merge-conflicts"
    ]
  },
  "editor": {
    "fontSize": 15,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
ScssBundle, v0.4.0
angularjs, v0.1.0
atom-beautify, v0.21.3
atom-color-highlight, v3.0.6
atom-lint, v0.20.1
autoclose-html, v0.15.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.3
autocomplete-snippets, v1.0.1
better-handlebars, v0.1.1
case-switch, v0.5.0
coffee-lint, v0.7.3
cucumber, v0.4.1
dash, v1.0.2
file-icons, v1.4.9
gist-it, v0.6.4
git-history, v2.0.0
git-plus, v4.4.1
git-tab-status, v1.5.3
highlight-selected, v0.7.0
jshint, v1.2.0
language-coffee-script-angular, v2.2.0
language-ember-script, v0.1.0
language-emblem, v0.1.0
language-haml, v0.15.0
language-handlebars, v0.2.0
language-rspec, v0.3.0
language-ruby, v0.47.0
linter, v0.11.1
linter-coffeelint, v0.1.7
linter-csslint, v0.0.11
linter-erb, v0.0.3
linter-htmlhint, v0.0.8
linter-js-yaml, v0.1.3
linter-jshint, v0.1.0
linter-rubocop, v0.2.1
linter-ruby, v0.1.4
linter-shellcheck, v0.0.6
pretty-json, v0.3.2
project-manager, v1.15.5
refactor, v0.4.1
rspec-snippets, v0.4.0
ruby-block, v0.2.2
sassbeautify, v0.2.0
script, v2.16.0

# Dev
No dev packages
```

```

**Comment by izuzak** [comment]
Thanks for the report, @andersennl. Can you try running Atom in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode) and see if it helps? (I noticed that you have a lot of packages installed.)

Does this happen for all projects or only some?

**Comment by andersennl** [comment]
Thanks for your quick response @izuzak. The error doesn't appear in safe mode. Actually, after starting Atom in safe mode und starting again in "normal" mode, the error didn't appear again. Therefore I didn't test it in another project.

Sorry for the duplicate issue.

**Comment by izuzak** [comment]
That's interesting -- thanks for letting us know @andersennl. I'm going to close the issue and add a note to  #4775 about this. If you notice this again -- please leave a comment.

**Comment by philipgiuliani** [comment]
@andersennl The rubocop issue maybe has just solved because you ran atom from command-line instead of opening it directly.

The only thing that safe-mode does, is to don't load up your packages.

So to get rubocop working (in normal mode), just go into your project directory and start atom with `atom .`!

**Comment by andersennl** [comment]
I actually start atom quite often via command line @philipgiuliani but this time it seems to have fixed the issues. Interesting why it happened now, though :) What's the difference in opening atom (not from terminal and then opening the project via menu) and opening a project via `atom .` btw?
