### ISSUE TITLE
download link from the main website

### ISSUE THREAD

**Issue by dridk** [atom/atom#5479]
Could you add all download link on the main website atom.io. 
Both installer and portable version . 
Check http://www.sublimetext.com/2

**Comment by izuzak** [comment]
There is a download link on the website:

![screen shot 2015-02-10 at 15 17 52](https://cloud.githubusercontent.com/assets/38924/6128665/12db547a-b138-11e4-971f-08097ae077f9.png)

Can you share a screenshot of what you see and which OS you're using?

**Comment by dridk** [comment]
I saw it! But it provide me only an installer. What I want is the portable version, because I have access restriction and my computer doesn't allow me to install it ! 
From sublime text, I download the portable version. I wish to have the same for atom.

**Comment by dridk** [comment]
By the was, clicking on "other platform" doesn't redirect you to a list of download link. I cannot download a Mac version from windows

**Comment by izuzak** [comment]
For a portable version, check out https://github.com/atom/atom/issues/2939 and https://github.com/atom/atom/pull/5385.

>  clicking on "other platform" doesn't redirect you to a list of download link. I cannot download a Mac version from windows

I agree, see this other issue in which this was already reported: https://github.com/atom/apm/issues/266.
