### ISSUE TITLE
Node package exhibits odd, Windows-specific file system permissions issues when running inside Atom package

### ISSUE THREAD

**Issue by joeferraro** [atom/atom#5481]
My package has a dependency that does some file system interaction, in this case, streaming a base64 encoded zip file to the file system. I'm the author of the package dependency as well. The code below (from the Atom package dependency) passes in tests on Linux, Unix, and Windows and works fine when used by my Atom package in Linux and Unix. However, when running in Atom on Windows, this code produces an Administrator-owned, read-only zip file that I can't seem to delete, even via the UI. What's odd to me is `fs.removeSync` does not throw an exception. I'm posting here because I've spent a lot of time determining whether this is Atom-specific behavior and I've come to the conclusion that it seems to be. Any idea why this may be occurring?

```
var zipStream = new Stream();
zipStream.readable = true;
zipStream.emit('data', new Buffer(result.zipFile, 'base64'));
zipStream.emit('end');
```

```
zipStream.pipe(fstream.Writer('/path/to/zipfile.zip'))
  .on('close', function() {
    var zip = new AdmZip('/path/to/zipfile.zip');
    zip.extractAllTo('/path/to');
    fs.removeSync('/path/to/zipfile.zip');
    resolve();
  });
```

**Comment by venkatpolisetti** [comment]
@50Wliu @benogle Any movement on this bug? 

@joeferraro hope the atom team fixes this issue so that we can enjoy using your Salesforce atom plugin.

The last comment on this thread from atom team is in Feb. 

Thank you guys for a wonderful editor and @joeferraro for his mighty plugins.

Thanks.

**Comment by benogle** [comment]
I'm not sure. This seems like a node bug. Can you reproduce this outside of atom? Just a regular node script?

**Comment by venkatpolisetti** [comment]
@joeferraro Is it possible for your to reproduce this error out side atom as requested by @benogle? 

We are really looking forward to using atom and mavensmate from our win 7 environments.

Thanks.

**Comment by joeferraro** [comment]
@benogle that's the problem, we're unable to reproduce outside Atom. Our appveyor/circleci tests for the node dependency in question (https://github.com/joeferraro/MavensMate) pass with no issue and this library also powers our Sublime Text plugin without issue. 

It's also worth noting that the Atom `tree-view` has a rather odd impact on perms in Windows (https://github.com/atom/tree-view/issues/436#issuecomment-105624411). 

For the time being, we're moving certain operations that we deem to be file system "heavy lifting" (excuse the term, it's just that node has so many problems with windows that even renaming a directory becomes a cautionary tale) to the system shell in an effort to workaround these issues in Atom.

**Comment by joanbarros** [comment]
I think I just encountered this issue but Atom was not the one that created the folder. I had a folder that  was created by a gulp task (gulp-msbuild). I found that it said that I had no permissions to delete that folder until I closed Atom. Then it allowed me to delete the folder.

I'll compile a better detailed report on the specific case I'm seeing and hopefully a way to reproduce it.

**Comment by cnaccio** [comment]
Would love to start using Atom instead of Sublime for Salesforce/MavensMate development! Let me know if there's anything I can do to help. 

Additionally if there's a technical workaround I'm totally ok with that.

**Comment by pjcarly** [comment]
We're eagerly awaiting a fix for this issue, as we would very much like to switch our Salesforce development to Atom, away from Sublime.
