### ISSUE TITLE
Round trip write/read of string in UTF-8 encoding doesn't match

### ISSUE THREAD

**Issue by jessegrosjean** [atom/atom#5482]
In my Atom package I do:

```
  activate: (state) ->
    p = "/tmp/encodiningtext.txt"
    text = "<li>ê</li>"
    console.log text
    fs.writeFileSync(p, text, { encoding: 'utf8' })
    console.log fs.readFileSync(p, 'utf8')
```

And the console output is:

```
<li>ê</li>
<li>�</li>
```

https://discuss.atom.io/t/file-encoding-puzzel/14828

**Comment by jessegrosjean** [comment]
@benogle Hi, I see you added needs-reproduction label. Is that something that I can help with or is it just a not to yourself to try reproducing the problem. I've got a package the reproduces it in the latest 0.177.0 but seems I can't attach a zip here.

**Comment by benogle** [comment]
Yeah, we need to reproduce it. Can you make a public repo, and link to it?

**Comment by jessegrosjean** [comment]
Here's a dropbox link, hope that's OK:

https://dl.dropboxusercontent.com/u/153385/encoding-test.zip

If you really need a repo let me know. To reproduce just run the "toggle" command and you should see the output as described above.

**Comment by izuzak** [comment]
I'm able to reproduce this by just running the commands in the JS console:

![screen shot 2015-02-11 at 14 35 18](https://cloud.githubusercontent.com/assets/38924/6147795/3c34d332-b1fb-11e4-9a95-6f395154c983.png)

Commands for easy copy-pasting:

```
var fs = require("fs")
var p = "/Users/izuzak/foo.txt"
var text = "<li>ê</li>"
console.log(text)
fs.writeFileSync(p, text, { "encoding": 'utf8' })
console.log(fs.readFileSync(p, 'utf8'))
```

Here's the fun part. Try it _without_ the first `console.log` command:

```
var fs = require("fs")
var p = "/Users/izuzak/foo.txt"
var text = "<li>ê</li>"
fs.writeFileSync(p, text, { "encoding": 'utf8' })
console.log(fs.readFileSync(p, 'utf8'))
```

Here's what I see:

![screen shot 2015-02-11 at 15 25 47](https://cloud.githubusercontent.com/assets/38924/6148502/5914014c-b202-11e4-827c-55cde3ce73fb.png)

However, that happens only if I restart Atom. If I run the first block of commands and then the second block of commands immediately after -- then I see different behavior:

![screen shot 2015-02-11 at 15 38 12](https://cloud.githubusercontent.com/assets/38924/6148702/114da0f0-b204-11e4-85fb-77022db7b2bf.png)

Notice that the first block and the last block are exactly the same, but give different results. Not really sure what's trolling us here. :smile: I think @kevinsawicki enjoys a fun encoding-related problem :smile_cat:

**Comment by jessegrosjean** [comment]
Here's a related tidbit:

1. Create a new file with content:

```
<li>ê</li>
```

2. Save it, and it should save fine with proper encoding.

3. But now open the debugger and put a breakpoint at the start of:

```
pathwatcher/lib/File.prototype.writeFileSync
```

4. Save the file again. You should hit the breakpoint. You don't need to do anything, just continue, but notice that now the file is now in the wrong encoding and displays in Atom as:

```
<li>�</li>
```

I don't know if this means there's some timing issue in the interaction between the TextBuffer and the pathwatcher File or maybe it's just lower level weirdness like `console.log` above. But figured it was relevant.

**Comment by postcasio** [comment]
Definitely something to do with the web inspector/console. Running this in the console:

```
text = '<li>ê</li>'
require('fs').writeFileSync('/tmp/encoding-test.txt', text, {encoding: 'utf8'})
```

```
$ hexdump -C /tmp/encoding-test.txt
00000000  3c 6c 69 3e ea 3c 2f 6c  69 3e                    |<li>.</li>|
```

It's written as `0xea`. Putting the same code in my `init.coffee` and reloading Atom results in the correct `0xc3 0xaa`:

```
$ hexdump -C /tmp/encoding-test.txt
00000000  3c 6c 69 3e c3 aa 3c 2f  6c 69 3e                 |<li>..</li>|
```

However, if you change it to log to console first and reload Atom again:

```
text = '<li>ê</li>'
console.log text
require('fs').writeFileSync('/tmp/encoding-test.txt', text, {encoding: 'utf8'})
```
```
$ hexdump -C /tmp/encoding-test.txt
00000000  3c 6c 69 3e ea 3c 2f 6c  69 3e                    |<li>.</li>|
```

It's back to `0xea`. Just sending the string to the console seems to cause it to encode incorrectly in future.

**Comment by postcasio** [comment]
Correction, the first example does actually work. The `console.log` call is what causes it.
