### ISSUE TITLE
feature request: ability to style class-names and id-names differently in HTML source

### ISSUE THREAD

**Issue by chharvey** [atom/atom#5483]
Currently, all attributes are `span.entity.other.attribute-name.html` and their corresponding value is `span.string.quoted.double.html`. This means that all attribute names are styled exactly the same way, and the same is true about attribute values.

Inspired by NetBeans, there should be a way to style **class** names and **id** names differently from other attributes. This can make code more readable and it can make your workflow much faster. This is illustrated below:

![screen shot 2015-02-10 at 12 32 37](https://cloud.githubusercontent.com/assets/1362083/6132507/ef16b28a-b120-11e4-95f6-22699f8018d4.png)

**Comment by kevinsawicki** [comment]
Sounds good to me, mind reopening this on https://github.com/atom/language-html/issues/new since that is the grammar that needs to be modified to parse these cases using new scopes.
