### ISSUE TITLE
UX: many dialogs have no close button (X)

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#5486]
It is a pain to have to go to the keyboard to close the find/replace dialog and then back to the mouse, especially for those of us who use the mouse on the left.  Many other atom dialogs also have this non-standard UX.  I can't remember any dialogs in any other app that don't have close buttons.

**Comment by thedaniel** [comment]
Thanks for the feedback - if this is an issue with FnR you should open the issue on https://github.com/atom/find-and-replace.

**Comment by mark-hahn** [comment]
FnR was only an example of what appears to be a consistent problem in
Atom.  But I've posted there for now.
