### ISSUE TITLE
empty line shows different character from specific font

### ISSUE THREAD

**Issue by mpede** [atom/atom#5488]
Since the last update Atom is displaying what seems to be a control character on empty rows as well as in front of single row numbers. I am using this font in Atom for a long time and this only started showing recently / in the last version. Other fonts seem to have an empty symbol in place for this.

![styles_less_-__users_cschmidt_securemount_mp_dev_sabm-domo-tool_-_atom](https://cloud.githubusercontent.com/assets/4440614/6139416/b4d432ee-b18b-11e4-99d4-4ce1eccaf55c.png)

**Comment by kevinsawicki** [comment]
What Atom version are you on?

**Comment by mpede** [comment]
Version 0.177.0 (0.177.0)

**Comment by izuzak** [comment]
I'm able to reproduce this in Atom 0.179.0-090561e on OSX after installing that font:

![screen shot 2015-02-11 at 14 21 09](https://cloud.githubusercontent.com/assets/38924/6147572/658c8d08-b1f9-11e4-978a-15d2a1b886c8.png)

However, I'm able to reproduce this in Chrome as well. Here's a screenshot of a gist where I switched to that font:

![screen shot 2015-02-11 at 14 27 23](https://cloud.githubusercontent.com/assets/38924/6147662/2c4b0d98-b1fa-11e4-9206-805e5cd3d5d8.png)

This makes me think that this isn't a problem in Atom itself, but I'm not sure if it's a problem in the font or in Chrome.

**Comment by lee-dohm** [comment]
I just looked at the line numbers in the Inspect Element after enabling this font:

![screen shot 2015-02-10 at 8 53 50 am](https://cloud.githubusercontent.com/assets/1038121/6150023/a3b2f9f6-b1c1-11e4-95be-21cc1a8440ab.png)

Looks like that font uses that glyph for `&nbsp;`.

**Comment by izuzak** [comment]
@nathansobo maybe knows why this changed recently (maybe related to Chrome?) and if there's anything we can do about it in Atom.

**Comment by nathansobo** [comment]
@izuzak Yikes, that is brutal. We may be able to avoid padding line numbers with `&nbsp` and instead use align right in the gutter now that we're using absolute positioning. Not sure about lines but the same may be true there. If someone wants to give it a try, awesome. I'm not sure it's worth the distraction right this moment for one weird font. Can that font be edited?

**Comment by lee-dohm** [comment]
This is where I found the font for my tests:

http://www.spacerogue.net/wordpress/?p=356

Seems to say that the original author is MiA, so maybe?

**Comment by phphphp** [comment]
Add one to the queue, and it is specifically a problem with the "Glass TTY VT220" font.  I'd really like to keep using this font, as it's very comfortable.  Any suggestions?

**Comment by nathansobo** [comment]
@phphphp Maybe see if you can open the font in a font editor and fix that glyph? It's going to be a pain not to be able to use non-breaking spaces anywhere in Atom. Or maybe file a bug with Chromium? We can leave this open until you have a resolution, regardless.

**Comment by lee-dohm** [comment]
There's also a Discuss topic related to this:

https://discuss.atom.io/t/atom-displaying-weird-characters-mac/14854

**Comment by simurai** [comment]
Chromium bug: [&nbsp; in some fonts is displayed as symbol](https://code.google.com/p/chromium/issues/detail?id=454108)

**Comment by izuzak** [comment]
Great, thanks @simurai! :zap: Gonna mark this as wontfix for now, but keep it open so that we can keep track of the related Chromium issue.

**Comment by phphphp** [comment]
@nathansobo I deleted the offending character in FontForge and the problem went away, but I'll keep an eye on the Chromium bug just the same.  Thanks!

**Comment by mpede** [comment]
@nathansobo @phphphp fontforge solved the problem for me as well.

**Comment by v3ss0n** [comment]
Yes , i have those garbage characters in empty lines (and gutter) too.

**Comment by v3ss0n** [comment]
@phphphp what character you deleteD?

**Comment by izuzak** [comment]
The [related Chromium issue](https://code.google.com/p/chromium/issues/detail?id=454108) was marked as closed -- @nathansobo @simurai how do you feel about closing this one as well? I will take a bit for those changes from Chromium to propagate to Atom, but I'd be :+1: on closing this still.

**Comment by nathansobo** [comment]
It's really up to you. I can see leaving it open until an upgrade actually solves the problem, but if you think the benefits of reducing noise outweigh the value of matching reality, I'm fine closing it too.

**Comment by v3ss0n** [comment]
Electron is not merged yet right?

**Comment by izuzak** [comment]
> Electron is not merged yet right?

@v3ss0n I don't think the fix that was made to Chromium has even made it to Electron yet -- it was merged 2 days ago (see link above).

**Comment by lee-dohm** [comment]
We don't use `&nbsp;` for the gutter or empty lines in the editor anymore.
