### ISSUE TITLE
Inserting control characters

### ISSUE THREAD

**Issue by xfq** [atom/atom#5490]
To insert a control character:
- In GNU Emacs, I can precede the combination with `C-q` (`quoted-insert`).
- In Vim, I can precede the combination with `C-v`.
- In GNU nano, I can precede the combination with `M-v`.

But AFAIK there is no way to insert (and display, see #1839) control characters in Atom. The [GCS](https://www.gnu.org/prep/standards/standards.html#index-formfeed) uses formfeed characters (control-L) to divide programs into pages at logical places, but I have to use other editors to do the insertion.

**Comment by xfq** [comment]
I still think it's a useful feature to add. Unfortunately, nobody seems to care about it...

**Comment by schultzern** [comment]
I care! An option to both show and insert control characters would be great.

**Comment by pxbaker** [comment]
I also care. There are lots of files out there that use control characters. In NPP you just pop up a pad and the hex code goes in there.
So I still have to use NPP!! (other alternates are available)
