### ISSUE TITLE
Uncaught Error: ENOENT, open '/Users/projetmbc/.atom/packages/save-session/projects/undefined/project.json'

### ISSUE THREAD

**Issue by projetmbc** [atom/atom#5496]
Hello. I have safely reinstalled Atom after using a "dangerous" package named "sync-settings".

1. I have removed the folder `.atom` and the `atom` application. Maybe there are some other files to remove...
2. I have installed some starred package using `apm`.

## The error message

    **Atom Version**: 0.178.0
    **System**: Mac OS X 10.8.5
    **Thrown From**: Atom Core

    ### Stack Trace

    Uncaught Error: ENOENT, open '/Users/projetmbc/.atom/packages/save-session/projects/undefined/project.json'

    ```
    At fs.js:82

    Error: ENOENT, open '/Users/projetmbc/.atom/packages/save-session/projects/undefined/project.json'
      at Error (native)

    ```

    ### Commands

    ```
         -0:01.6 application:new-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
    ```

    ### Config

    ```json
    {
      "core": {
        "themes": [
          "atom-dark-ui",
          "atom-dark-syntax"
        ]
      },
      "editor": {
        "fontSize": 16
      }
    }
    ```

    ### Installed Packages

    ```coffee
    # User
    autocomplete-paths, v1.0.2
    autocomplete-plus, v2.1.4
    color-picker, v1.4.4
    emmet, v2.3.3
    file-icons, v1.4.9
    hex, v0.5.0
    html-entities, v0.3.1
    minimap, v4.1.4
    parcel, v0.0.3
    save-session, v0.11.5
    show-in-folder, v0.1.0
    symbols-tree-view, v0.5.2
    tree-view-open-files, v0.2.3

    # Dev
    No dev packages
    ```

**Comment by izuzak** [comment]
From the stack trace, it seems like a problem in the save-session package. Running Atom in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode) should confirm that and you might consider reporting an issue on that package's issue tracker:

https://github.com/mpeterson2/save-session/issues

**Comment by projetmbc** [comment]
Ok, thats has been done.
