### ISSUE TITLE
Auto-Updater not finding v178 (Windows)

### ISSUE THREAD

**Issue by batjko** [atom/atom#5500]
Hi guys,

Just tried "Check for updates" on my v177 installation. And it doesn't seem to recognize that there is a newer one out:
![image](https://cloud.githubusercontent.com/assets/7287076/6150953/6c1dc5f4-b20a-11e4-83aa-d86bbf2e4db5.png)

Not sure how to troubleshoot it, since I haven't paid much attention to how squirrel works. :angry: 

Win8.1 64bit.

**Comment by mark-hahn** [comment]
I have found that it takes several days to get a new version.  I'm still on
177 also.

**Comment by SympleKaos** [comment]
My atom is on 176 and is not seeing an update for even 177.
Windows 8.1 64bit as well.

**Comment by mnquintana** [comment]
I'm also noticing that the Atom icon in that dialog box looks reeeeally pixelated, which should've been resolved as part of #4811

**Comment by SympleKaos** [comment]
My atom is on 176 and is not seeing an update for even 177.
Windows 8.1 64bit as well.

**Comment by batjko** [comment]
I updated to 177 without a problem, but I indeed only checked several days after the release so I can't be sure if it would have sooner.

**Comment by thedaniel** [comment]
This might be related to the addition of delta updates - we'll take a look at the update server code today and hopefully that will help.

**Comment by kevinsawicki** [comment]
I just deployed the serving of delta packages to atom.io so 0.177 should now be able to upgrade to 0.178

This is the first release with binary delta packages so please report any download/install errors going from 0.177 to 0.178

**Comment by batjko** [comment]
@kevinsawicki Thanks, that seems to have done the trick.

I'm going to go ahead and close this ticket, assuming that any other 177->178 issues might not be strictly the same.
