### ISSUE TITLE
Icons missing for theme using atom:// protocol

### ISSUE THREAD

**Issue by ksmithut** [atom/atom#5501]
Some of the icons that I'm using seem to be missing when using the ATOM_HOME variable in my shell.

The theme doesn't seem to be the issue, it seems to be the way Atom is routing requests coming from the atom:// protocol.

I get the following errors in the console:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND    atom://seti-ui/stylesheets/_fonts/icomoon.woff 
Failed to load resource: net::ERR_FILE_NOT_FOUND    atom://seti-ui/stylesheets/_fonts/icomoon.ttf
```

Looking through the code, I found [this line](https://github.com/atom/atom/blob/44112f2ecd54eebe7496d1b581cac182e46ab0df/src/browser/atom-protocol-handler.coffee#L21) that may be pointing to the wrong directory, or rather, not respecting the ATOM_HOME variable.

Atom: 0.178.0
OS: Mac OS X Yosemite 10.10.2

**Comment by kevinsawicki** [comment]
Thanks so much for reporting this, it will be fixed in the next Atom release 0.179

**Comment by ksmithut** [comment]
That was fast! I was just looking into how I might be able to help. Great job

**Comment by kevinsawicki** [comment]
0.179 is now available.
