### ISSUE TITLE
ATOM_HOME does not affect default Chromium storage path

### ISSUE THREAD

**Issue by MarjanTomas** [atom/atom#5502]
hi

i'm on Win7 64bit and downloaded the newest
atom-windows.zip version 0.178.0 from
https://github.com/atom/atom/releases
to test the new ATOM_HOME env var feature.

i've set the env var ATOM_HOME to the path
D:\portable_programs\Atom\ATOM_HOME
and started atom.exe .
now in the folder
D:\portable_programs\Atom\ATOM_HOME
appeared only one dir "compile-cache" and
only one file "config.cson". it looks like
an incomplete part of the files and folders
that would normally be created on the first run
of atom.exe in the folder
C:\Users\ <user> \.atom
the content of "config.cson" looks different
than usual and contains the line
"exception-reporting"

the folder
C:\Users\ <user> \AppData\Roaming\Atom
was created in the same place, like without
a present ATOM_HOME env var. so for the folder
C:\Users\ <user> \AppData\Roaming\Atom
the redirection via ATOM_HOME does not
work in the actual Atom version 0.178.0 .

for the folder
C:\Users\ <user> \.atom
the redirection via ATOM_HOME env var
works partially and the files
.gitignore , init.coffee , keymap.cson ,
snippets.cson and styles.less and the
folder packages were not created, when
ATOM_HOME was set.

also i would expect that the files and folders of
C:\Users\ <user> \.atom
would be placed in the ATOM_HOME env var mode
in the same subfolder .atom like
<path in ATOM_HOME> \.atom
but they landed directly in
<path in ATOM_HOME> \

**Comment by kevinsawicki** [comment]
Did `D:\portable_programs\Atom\ATOM_HOME` exist before you launched Atom?

**Comment by kevinsawicki** [comment]
> C:\Users\ <user> \AppData\Roaming\Atom was created in the same place

This is expected, ATOM_HOME is for compile caches, installed packages & themes, local styles, config, snippets and keymaps.

`C:\Users\ <user> \AppData\Roaming\Atom` is where the browser's `localStorage` database is written to and other Chromium specific file.

**Comment by MarjanTomas** [comment]
> Did the D:\portable_programs\Atom\ATOM_HOME folder exist before you launched Atom?
yes, i've created the folder before i started atom.exe .

now i've deleted first the folder
D:\portable_programs\Atom\ATOM_HOME
and then started atom.exe and it worked fine now when
D:\portable_programs\Atom\ATOM_HOME
was created by atom.exe .
and all expected sub folders and files were present too.

somehow i thought that
C:\Users\ \<user\> \AppData\Roaming\Atom
would be redirect also.

many thanks for the fast respond and info !

**Comment by kevinsawicki** [comment]
> now i've deleted first the folder D:\portable_programs\Atom\ATOM_HOME

Yes, this folder is only populated by Atom with the template files when it doesn't already exist.

> somehow i thought that C:\Users\ <user> \AppData\Roaming\Atom would be redirect also.

Yes, I'll look into whether this can be added in, thanks for reporting this.

**Comment by darkmorpher** [comment]
@MarjanTomas Is this still reproducible?

CC @damieng to Tag `Windows` https://github.com/atom/atom/issues/3560#issuecomment-217263907
