### ISSUE TITLE
Atom keeps converting my spaces to tabs

### ISSUE THREAD

**Issue by lostinplace** [atom/atom#5505]
whenever I save a package.json, it converts all of my spaces to tabs.  This happens even though soft tabs is enabled.

**Comment by izuzak** [comment]
@lostinplace Can you share more [debugging information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)?

**Comment by lostinplace** [comment]
unfortunately no.  this was solved by deleting the file, creating a new package.json, pasting the old contents, using untabify and then changing one of the lines two '  '  I also changes the invisibles.tab in config.cson to '  '

I don't know what was happening, but it seems to be fixed
