### ISSUE TITLE
Command to close all tabs

### ISSUE THREAD

**Issue by vemv** [atom/atom#5511]
Any specific reason why such a common command across editors is not available in Atom?

I implemented it like this and it works just fine (respects other open projects a well as files with unsaved changes):

`atom.workspace.getPanes()[0].destroy()`

The keybinding from Textmate 1 (cmd-ctrl-w) is free by default.

Cheers - Victor

**Comment by mark-hahn** [comment]
> The keybinding from Textmate 1 (cmd-ctrl-w) is free by default.

Not that it matters, but virtually no keys are free.  77,457 users use it
for find-and-replace and 69, 060 users use it for emmet.  (shameless plug
for search-all-keybindings package).

**Comment by vemv** [comment]
Nice!

Still, I think a plugin keybinding would override a core one, so the only 'freeness' that would matter is the one in core.

**Comment by izuzak** [comment]
Looks like https://github.com/atom/tabs/issues/61, so closing this in favor of that issue.

**Comment by afeld** [comment]
For anyone else looking for a quick way to achieve this, you can add the following to your keymaps file (`~/.atom/keymap.cson`):

```coffeescript
'body':
  'cmd-ctrl-w': 'tabs:close-all-tabs'
```

**Comment by umpirsky** [comment]
`Ctrl+K Ctrl+W` worked for me.

**Comment by Bobobrien92** [comment]
Ctrl+K Ctrl+W only closes a single pane for me when I have two tabs setup horizontally.

**Comment by umpirsky** [comment]
@Bobobrien92 Try `Ctrl+K Ctrl+W` for each pane.

**Comment by Bobobrien92** [comment]
Yeah that works for each pane but it's not really a keyboard shortcut to close all tabs.  It's more of a shortcut to close all tabs in the active pane that I have to repeat x times for x panes I have opened.

**Comment by umpirsky** [comment]
¯\__(ツ)__/¯
