### ISSUE TITLE
~/.atom has to be created with permissions for all users on ubuntu 14.04

### ISSUE THREAD

**Issue by horvan** [atom/atom#5512]
I am not shure if this is an apm issue or an atom issue in general but here is what happens if 

``` Shell
~/.atom
```

is not set with rwrwrw

![result of compiling atom](https://cloud.githubusercontent.com/assets/5676367/6164795/b2e1869a-b2a2-11e4-9929-ee7206c8a3a6.PNG)

this is easy to fix by entering chmod 777 ~/.atom

but the directory should have this permissions right after building the editor or when installing the deb package to avoid this issue

---

This should be added to the trooubleshooting section of 

https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

**Comment by steelbrain** [comment]
@horvan Which version of Atom are you using? Can you upgrade to the latest version please?
And in case you want to fix permissions of the `/.atom` folder execute this in a terminal
```sh
chmod 755 ~/.atom
find ~/.atom -type d -print0 | xargs -0 chmod 0775
find ~/.atom -type f -print0 | xargs -0 chmod 0664
```

**Comment by horvan** [comment]
@steelbrain  I am using the latest one because this happens after grunt install is finished after building from the repo.

**Comment by horvan** [comment]
after some testing and trying the deb packge for ubuntu, too I figured out that the .atom folder in the users home directory should just be set to 755 when it i created . this solves the problem as well for the compiled version as for the deb package.

If grunt is able to set permissions this is a musthave.

**Comment by amayer5125** [comment]
I guess it wouldnt be a huge difference but if you want to focus on security I think the permissions should be something like `chmod 750 ~/.atom`. That way other users (excluding root) cant see your settings or packages.

**Comment by shelakel** [comment]
`sudo chown $USER /home/$USER/.atom` sorted it out for me on Lubuntu 15.10
