### ISSUE TITLE
Package: The tern dependency range in the package.json file is invalid:

### ISSUE THREAD

**Issue by tststs** [atom/atom#5513]
I used to get a dependency for a package i'm working on via
<code>"tern": "git://github.com/marijnh/tern.git"</code>

There seems to be no way since 0.177 to publish a package with this type of dependency.
<code>The tern dependency range in the package.json file is invalid: git://github.com/marijnh/tern</code>

Per design or issue?

thx
tststs

**Comment by izuzak** [comment]
Ahhh, I think I see what's causing problems for you -- as of [recently](https://github.com/atom/apm/pull/292), apm verifies that the semvers used in package.json are valid.

However, a dependency might be defined as a URL and a bunch of other things (I totally forgot about that):

https://docs.npmjs.com/files/package.json#dependencies

/cc @kevinsawicki

**Comment by izuzak** [comment]
This issue was moved to atom/apm#295
