### ISSUE TITLE
Ability to see the warning when build aborts

### ISSUE THREAD

**Issue by stramel** [atom/atom#5517]
It would be very useful for a user and probably to help debug for you guys to have the Warnings display in the terminal instead of just saying "Aborted due to warnings.". I then have to modify my build script to use `-v` so I can see the warning.

**Comment by kevinsawicki** [comment]
Running with the `--stack` option can also be helpful.

**Comment by stramel** [comment]
@kevinsawicki What all does the `--stack` flag show?

**Comment by kevinsawicki** [comment]
> What all does the --stack flag show?

The stack trace for any uncaught exceptions during the grunt tasks.

**Comment by kevinsawicki** [comment]
Closing this out since there is the `--stack` option and the `--no-quiet` option.

Also landing #7877 will increase the logging by default.
