### ISSUE TITLE
Uncaught Error: ENOTDIR, open '/Users/superherointj/Dev/sumicity/sumicity.js/deployment-config.json'

### ISSUE THREAD

**Issue by superherointj** [atom/atom#5521]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOTDIR, open '/Users/superherointj/Dev/sumicity/sumicity.js/deployment-config.json'

```
At fs.js:75

Error: ENOTDIR, open '/Users/superherointj/Dev/sumicity/sumicity.js/deployment-config.json'
  at Error (native)

```

### Commands

```
     -0:21.7 pane:reopen-closed-item (atom-text-editor.editor)
     -0:02.4 sftp-deployment:mapToRemote (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "secure-copy",
      "remote-edit",
      "remote-sync",
      "Remote-FTP"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v0.5.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
@superherointj It's a bug in SFTP-deployment package, you need to read it's README file and place your configuration file there [the path that this error indicates].

**Comment by benogle** [comment]
thanks @steelbrain

**Comment by superherointj** [comment]
It is not possible to set the configuration file there because the path has a file on it. But I agree it`s a SFTP-deployment bug probably.
