### ISSUE TITLE
List installed packages and themes

### ISSUE THREAD

**Issue by stela5** [atom/atom#5523]
I know Atom takes care of detecting pending updates for installed packages and themes and notifying me, but I can't seem to find where in the settings I can simply view all my installed packages and themes.  Can you point me in the right direction?

**Comment by DarkArc** [comment]
Just click the "Packages" or "Themes" tabs respectively :)

**Comment by lee-dohm** [comment]
You have to open the Settings View first by pressing <kbd>Cmd+,</kbd> on OS X or <kbd>Ctrl+,</kbd> on other platforms. Then yes, just click the Packages or Themes tabs. If you're a visual person, they're here:

![packages-and-themes](https://cloud.githubusercontent.com/assets/1038121/6176004/3ada5ea2-b2b0-11e4-8038-e2750ab73a6b.png)

Let us know if you need more help! You can always stop by [Discuss, the official Atom forum](https://discuss.atom.io) with questions like this too :grinning:

**Comment by stela5** [comment]
I should have mentioned I use the Windows version of Atom which doesn't seem to provide the number of installed packages like your screenshot above.  Either way, I figured out another method: "apm list"

![image](https://cloud.githubusercontent.com/assets/982679/6214071/25a74be8-b5b3-11e4-9297-7ffb45486b91.png)

![image](https://cloud.githubusercontent.com/assets/982679/6214085/45a2ab7c-b5b3-11e4-9266-538a2adacb82.png)

**Comment by 50Wliu** [comment]
@stela5 you seem to be running an outdated version of Atom.  If you upgrade to the latest version, you'll see that the Settings View has been improved and will appear like what it does in @lee-dohm's comment.

**Comment by stela5** [comment]
Thanks, everyone!  Chocolatey was the culprit.  I uninstalled chocolatey and then re-installed Atom via the AtomSetup.exe download and I'm now running the latest version.

![image](https://cloud.githubusercontent.com/assets/982679/6218253/b0dfcdf4-b5d9-11e4-96a8-f1fee5938635.png)
