### ISSUE TITLE
Pasting large amounts of text has gotten really slow

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#5529]
Here I'm pasting ~800 lines of text and it's taking about 100ms. Looks like we're spending a ton of time in `setIndentationForBufferRow`, probably because the presenter is doing more work synchronously in these cases. @maxbrunsfeld do you think we could auto-indent before inserting the text to avoid this? 

![screenshot 2015-02-12 13 31 12](https://cloud.githubusercontent.com/assets/1789/6176352/7cf95832-b2bb-11e4-8bad-cedddea054ab.png)

Sync vs async presenter updates is a tricky balancing act because async will be slower in extremely common cases such as inserting a character but faster in less common ones like indenting 800 lines. I may need to revisit my approach and do more of the presenter work async.

**Comment by 50Wliu** [comment]
Refs #5411.
