### ISSUE TITLE
Update.exe chewing CPU

### ISSUE THREAD

**Issue by pcolby** [atom/atom#5530]
Hi, it seems most mornings Atom's `Update.exe` process consumes a lot of CPU - up to 80%, for several minutes, before settling down to use ~5% for several minutes.  This seems like a lot when Atom is already up to date on my PC, so there are no updates to install / process.

Is this expected?  If not, I'll be a bit more attentive to its actual behaviour, and see if I can provide a more detailed report.

Thanks.

**Comment by thedaniel** [comment]
cc @paulcbetts - this issue might belong on the https://github.com/Squirrel/Squirrel.Windows repo (the update framework we use)

**Comment by paulcbetts** [comment]
@pcolby Can you attach the log? It's in `C:\Users\YOUR NAME\AppData\Local\atom\SquirrelSetup.log`

**Comment by pcolby** [comment]
Thanks for the very fast responses :)

`SquirrelSetup.log` attached below.  It's ~4MB, so I've zipped it.  Github doesn't accept `*.zip` or `*.log` files, so I've given it a faux `.jpg` extension.

![squirrelsetup zip](https://cloud.githubusercontent.com/assets/5195222/6178279/78ebde6c-b361-11e4-9eef-d2278a77e8c8.jpg)

Cheers.

**Comment by paulcbetts** [comment]
@pcolby I don't think that trick works. Can you host it on Dropbox or some other service?

**Comment by pcolby** [comment]
Right-click, save-as: https://cloud.githubusercontent.com/assets/5195222/6178279/78ebde6c-b361-11e4-9eef-d2278a77e8c8.jpg

Rename file to `*.zip`.  Extract.

Works for me :)

I'll email paul as suggested.

Cheers.

**Comment by paulcbetts** [comment]
This will be made much better once #5382 lands

**Comment by kevinsawicki** [comment]
Closing this out now that #5382 has landed and the update is much quicker and less CPU intensive since only a few files are unzipped instead of tens of thousands.
