### ISSUE TITLE
[PHP] Syntax highlighting for inline variables

### ISSUE THREAD

**Issue by Verox-** [atom/atom#5532]
![Issue example](http://i.imgur.com/lzUxSyj.png)

As shown in the image, OO style function calls surrounded by curly braces in strings doesn't format properly.

**Comment by 50Wliu** [comment]
Could you please report this to the [language-php](github.com/atom/language-php) repository?  Thanks.

**Comment by lee-dohm** [comment]
This issue was moved to atom/language-php#61

**Comment by lee-dohm** [comment]
I used https://github-issue-mover.appspot.com/ to do it. It's a pretty cool utility, found out about it from @izuzak, I believe.
