### ISSUE TITLE
Project::setPaths() can hose a project

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#5533]
If you use `Project::setPaths()` to change the tree in a project to the wrong folder and close atom, then that is serialized and every time you try to open the project you get that wrong tree loaded.  That folder is then unaccessible until you clear out `~/.atom/storage`.  This was very frustrating.  I had to work on that folder with notepad++ until @lee-dohm told me about the storage folder.

See https://github.com/JavascriptIsMagic/tree-view-git-projects/issues/2 and https://discuss.atom.io/t/atom-opening-wrong-folder/14882.

windows 8.1
atom 0.177.0 (and older)

FYI: This is not a new problem.

**Comment by mark-hahn** [comment]
P.S.  My suggested fix is to always check when opening a folder and make sure it is one of the paths.

**Comment by lee-dohm** [comment]
I can no longer reproduce this problem. It looks like the new system that stores the state based on a hash of the paths array resolved it :grinning:
