### ISSUE TITLE
Multiple processes spawn spontaneously.

### ISSUE THREAD

**Issue by conmarap** [atom/atom#5545]
I have caught a bug that will spawn multiple Atom processes mostly when the main window gains focus. Some are killed but there are more and more being added as time passes and it leads to a 100% CPU usage and more than 80% memory usage (about 8GB of RAM on my machine). In the screenshot below you can see what I mean (NOTE: There are more than 40 processes and was unable to include all in a single screenshot).

![image](https://cloud.githubusercontent.com/assets/939247/6189672/770c4d80-b36a-11e4-8e31-8970f7c8c7c8.png)

**Comment by lee-dohm** [comment]
Could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
* Can you supply repro steps?

**Comment by conmarap** [comment]
* Latet; I always keep it up to date.
* Windows 8.1, version/build `6.3.9600`
* Yes.
* I am not sure; I have noticed that the issue is more intense after entering `Ctrl` + `Shift` + `P` and running a command, any command.

**Comment by lee-dohm** [comment]
Giving the specific version number is helpful because then we don't have to track down the version number that was most likely available on the date that the issue was reported. I assume you mean v0.179.0?

**Comment by conmarap** [comment]
In that case I apologize. I'm referring to version 0.179.0, correct.

**Comment by jonathandelgado** [comment]
@conmarap Is this possibly plugin related?

**Comment by conmarap** [comment]
@jonathandelgado I am suspecting that might be the case, since I have a Git plugin that I've been running from time to time, but it never caused an issue till yesterday. But, even so, is Atom supposed to be spawning processes like that?

**Comment by jonathandelgado** [comment]
@conmarap If a plugin spawns a child process, it will also be an `atom.exe` - Can you reproduce this with said plugins disabled?

**Comment by steelbrain** [comment]
@conmarap @jonathandelgado `atom --safe` as suggested by @lee-dohm disables all plugins.
So if you're having the issue in safe mode too, then Atom is the cause for it, otherwise. It's one of your plugins.

**Comment by conmarap** [comment]
Thanks, I'll test that.

**Comment by conmarap** [comment]
So far I've only been able to get it to spawn 1 or 2 background processes. Typical commands such as "Open Keymap" will spawn 1 when the window regains focus, but the main background process will use up to 30% of the CPU for 2 to 3 seconds. I'll close for now.
