### ISSUE TITLE
Settings View not opening

### ISSUE THREAD

**Issue by stramel** [atom/atom#5546]
I am unable to open the settings through the command palette or using the keys `Ctrl-,`. Using the Menu however, I am able to access it through Edit > Preferences. 

I have verified this is still an issue in Atom's Safe Mode (`--safe`) and that there are no errors in the console. 

My setup:
**OS:** Ubuntu 14.04
**Atom:** 0.180.0-2dac7fd
**settings-view:** 0.181.0

**Comment by izuzak** [comment]
Thanks for the report, see https://github.com/atom/settings-view/issues/380
