### ISSUE TITLE
Renaming long filenames: scrollbar hides text

### ISSUE THREAD

**Issue by BrainCrumbz** [atom/atom#5548]
Steps:
1. Select a file to rename in treeview
1. Press F2
1. The small dialog to rename file shows up on the top

Here the filepath should be fully visibile. Instead, because the filename is wider than field width, the horizontal scrollbar shows up. But that overlaps and partially hides the filename itself (see screenshot).

HTH
Cheers

![image](https://cloud.githubusercontent.com/assets/3185573/6191547/a0e9f6f8-b3aa-11e4-96ef-f8a9cf938350.png)

**Comment by izuzak** [comment]
I'm seeing the same, possibly related to https://github.com/atom/atom/issues/5542? /cc @nathansobo

**Comment by disfinder** [comment]
Issue still reproduces, ubuntu, Atom 1.2.1
