### ISSUE TITLE
please implement 

### ISSUE THREAD

**Issue by LILNAZ** [atom/atom#5549]
When dividing the atom window in to multiple sections have a way to resize proportions.

ps: I'm new to Github

**Comment by m1ga** [comment]
https://github.com/atom/atom/issues/274

**Comment by izuzak** [comment]
Thanks @m1ga -- closing in favor of https://github.com/atom/atom/issues/274.

**Comment by LILNAZ** [comment]
thanks exactly what i was looking for.
