### ISSUE TITLE
Paste and Match Style not working on Mac

### ISSUE THREAD

**Issue by srinivasanv** [atom/atom#5550]
http://support.apple.com/en-us/HT201236

Command-Shift-Option-V (the default keyboard shortcut for Paste and Match Style) doesn't seem to work in Atom as a method to paste as plain text. 

Ideally, that keyboard shortcut would work the same way as it does in TextEdit (while TextEdit is in plain text mode).

Running Atom 0.179.0 on OSX 10.10.2

**Comment by mnquintana** [comment]
@srinivasanv So, all text pasted in Atom is pasted as plain text. Would it suffice to just map <kbd>Cmd-Shift-Opt-V</kbd> to the regular Paste command?
