### ISSUE TITLE
Atom 179 won't open on Windows

### ISSUE THREAD

**Issue by karai17** [atom/atom#5552]
I recently installed Atom 179 and it refuses to open new windows. I tried to close it and reopen it and now it's not opening at all. When I click my pinned taskbar icon a single atom process pops up in my taskbar then quickly disappears. If I open the exe manually from appdata, I don't even get that.

Reverting back to 177 works great, I immediately get 4 processes and Atom pops up as expected.

**Comment by kevinsawicki** [comment]
Can you run `atom -f` from the command prompt and see if any errors are logged to the console?

**Comment by karai17** [comment]
![](http://puu.sh/fSwWJ/184701b44d.png)

**Comment by kevinsawicki** [comment]
Looks like your Atom installation is corrupt, several files appear to be missing. I believe could also be why you are experiencing https://github.com/atom/notifications/issues/38 and https://github.com/atom/atom/issues/5551

Can you try deleting the `C:Users\Karai\AppData\Local\atom` folder, re-downloading from atom.io and rerunning the downloaded `AtomSetup.exe`?

**Comment by karai17** [comment]
I'll give it a try. I'd like to also note that the Atom updater is far too opaque. When Atom is updating, it simply says "updating" and gives no information like "1 minute remaining" or "85% downloaded" or anything... useful.

Sometimes when it updates it takes an indefinite amount of time and it doesn't actually finish until I restart it manually, which could explain why this time it became corrupt.

**Comment by karai17** [comment]
Deleting 179, running 177, and running update gave me an error saying 177 was up to date.

Doing exactly what you said and deleting the whole atom folder and then reinstalling worked fine. Perhaps I will open a new issue about update's transparency.

Thanks.
