### ISSUE TITLE
what do i do here

### ISSUE THREAD

**Issue by AnbuKakashi** [atom/atom#5553]
Uninstall everything or ?
Sorry for the noob question, but i am new to Atom and i just started messing around with web design.

![screenshot_1](https://cloud.githubusercontent.com/assets/10999416/6196193/7107225e-b3d6-11e4-901d-391213c4e010.png)

**Comment by AnbuKakashi** [comment]
Ok i deleted all of those on the picture, but i have still have one problem 
![screenshot_2](https://cloud.githubusercontent.com/assets/10999416/6196540/56303c10-b3d9-11e4-9c5e-a41e6597aad8.png)

**Comment by steelbrain** [comment]
It's there so that you may report to the Package authors that their packages need to be updated to use the v1.0 API
You can ignore it if you want. Won't affect your Atom experience at all.

**Comment by AnbuKakashi** [comment]
Thank you for your reply.
