### ISSUE TITLE
Memory error when setting ATOM_HOME and lauching atom

### ISSUE THREAD

**Issue by danwatco** [atom/atom#5556]
Running the .zip version of atom on a USB stick and trying to make it portable, I have found that to set the ATOM_HOME, I should create a script like this:
```
SET ATOM_HOME="E:\Web Stuff & Tools\Atom\.atom"
atom
```
Running that script creates the following error:
![image](https://cloud.githubusercontent.com/assets/6568235/6200090/e7bf9546-b45f-11e4-9b99-c7de4694b50c.png)

Any ideas why?

**Comment by kevinsawicki** [comment]
Just curious, if you try a path like `SET ATOM_HOME="E:\Atom\.atom"`, does it work then?

**Comment by danwatco** [comment]
@kevinsawicki Just tried that, still brings up the same error

**Comment by damieng** [comment]
Portable mode is now fully supported and documented in the flight manual at http://flight-manual.atom.io/getting-started/sections/installing-atom/ - no ATOM_HOME is necessary.

If you still run into this error please re-open this issue.
