### ISSUE TITLE
Unable to install plugins on Ubuntu 14.04

### ISSUE THREAD

**Issue by Queuecumber** [atom/atom#5557]
All of a sudden all of my plugin updates or installations fail with the following error log:

    npm ERR! addLocal Could not install /tmp/d-115114-13730-zx3j8u/package.tgz
    npm ERR! Linux 3.13.0-45-generic
    npm ERR! argv "/opt/atom/resources/app/apm/bin/node"     "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/opt/atom/resources/app/apm/.apmrc" "--userconfig" "/home/mehrlich/Seafile/dotfiles/.atom/.apmrc" "install" "/tmp/d-115114-13730-zx3j8u/package.tgz" "--target=0.21.0" "--arch=x64"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.3.0
    npm ERR! path /var/lib/jenkins
    npm ERR! code EACCES
    npm ERR! errno 3

    npm ERR! Error: EACCES, mkdir '/var/lib/jenkins'
    npm ERR!  { [Error: EACCES, mkdir '/var/lib/jenkins'] errno: 3, code: 'EACCES', path: '/var/lib/jenkins' }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /tmp/apm-install-dir-115114-13730-1ssxjoq/npm-debug.log

Is there something messed up with my configuration or is this a bug in atom? It's pretty troubling that it is trying to access the privileged directory `/var/lib`. Also note that ALL packages fail with `/var/lib/jenkins`, this path never changes.

**Comment by 50Wliu** [comment]
Please upgrade Atom to the latest version.  This was a bug with the CI server (which uses Jenkins).
See #5492 for more details.
