### ISSUE TITLE
Cursor is not rendering at the correct place

### ISSUE THREAD

**Issue by zero-** [atom/atom#5559]
![bloggif_54df8c6f07c24](https://cloud.githubusercontent.com/assets/1594723/6200504/e2ddb1ba-b483-11e4-96d8-f12225599a55.gif)
I've been experiencing this since 0.177.0 and the latest 0.179.0 didn't fix the issue.
Any ideas? 

*edit* Running Atom on OSX 10.10.1

*edit 2* I'm using Input Sans as my font. The problem is not happening with default font.

**Comment by steelbrain** [comment]
@zero- Are you sure that you don't have something like
```
text-rendering: optimizeLegibility;
```
in your styles.less

**Comment by benogle** [comment]
What don't are you using? What themes?

**Comment by zero-** [comment]
@steelbrain Good catch, it was ```text-rendering: optimizeLegibility;``` that was causing the problem. I removed that and now Input Sans works also.

Thanks guys!
