### ISSUE TITLE
Document a way to run commands (and from init.coffee)

### ISSUE THREAD

**Issue by vemv** [atom/atom#5564]
How to programatically run a command such as `core:cancel`? I had to figure it out since I failed to find how.

This works:

`$('atom-text-editor').dispatchEvent(new CustomEvent('core:cancel'))`

However it doesn't from init.coffee, because `$` is not defined there (I believe init.coffee should have the same environment as in the Developer Tools console, but that's a different issue).

I suggest to create a Docs page explaining commands, how to run them programatically, and in particular how to run them from init.coffee.

Thanks - VIctor

**Comment by sedabull** [comment]
I believe the canonical way is:
```coffeescript
atom.commands.dispatch(target, event)
```

see the API docs [here](https://atom.io/docs/api/v0.179.0/CommandRegistry)

**Comment by lee-dohm** [comment]
It's likely that you don't want to execute commands programmatically. Commands are essentially a way of tying UI features such as menu items, keybindings and such to bits of code in packages. They're a way for the user to trigger code. If you're doing things programmatically, you can just call the code itself.

If you're trying to execute commands programmatically for testing, you can use the [`atom.commands.dispatch` method](https://atom.io/docs/api/latest/CommandRegistry#instance-dispatch) as @sedabull mentioned.

**Comment by sedabull** [comment]
@lee-dohm, I agree that this won't come up often, but I did come across a non-testing use case for `atom.commands.dispatch` recently in my package `quantum-shell`. So perhaps it should be better documented, if only for the purpose of helping people write better tests.

**Comment by vemv** [comment]
* I stumbled upon `atom.commands.dispatch ` but ignored it since it said 'simulate', which I interpreted as 'to not actually perform'. I suggest to reword

* Using the suggested API works, but then again `$` is not reachable from init.coffee:
`atom.commands.dispatch($('atom-text-editor'), 'autocomplete:toggle')`

*Context* 

I'm trying to create a keybinding that calls `core:cancel` first and `autocomplete:toggle` second. Trying to programatically call commands by name seems reasonable here, since `"autocomplete:toggle"` doesn't change over time, while e.g. `whatever.autocomplete.toggle(args)` is fairly likely to change over time.

**Comment by lee-dohm** [comment]
The Atom team is specifically attempting to remove Atom's dependence on jQuery. But, like any other Node module, [you can import jQuery](https://atom.io/docs/latest/upgrading/upgrading-your-package#require-views-from-atom-space-pen-views) into your `init.coffee` by doing:

```coffee
{$} = require 'atom-space-pen-views'
```

Or, you can use the following to not need to import jQuery:

```coffee
editor = atom.workspace.getActiveTextEditor()
atom.commands.dispatch(atom.views.getView(editor), 'autocomplete:toggle')
```

The command names are considered internal to a package and aren't intended to be a public interface. They're just as likely to change over time as any other facet of a package's code. At least, as a package author, I don't worry about breaking other people's code by changing my packages' command names because the only code that should be depending on command names are my package's code.

What you're really looking for is the new [Services API](https://atom.io/docs/latest/creating-a-package#interacting-with-other-packages-via-services) that is a method where a package can create a public interface that is specifically intended to be unchanging over time (or at least versioned). It is brand new though and very few packages use it so far.

**Comment by envygeeks** [comment]
I think it becomes useful when people add in responsiveness to Atom editor (I guess this is one reason Atom beats other editors, it uses a webview) but I just wanted to chime in and say you don't need jQuery to do simple things like that since JavaScript explicitly includes these functions now:

```
atom.commands.dispatch(document.querySelector('atom-text-editor'), 'tree-view:toggle')
```

**Comment by omrihar** [comment]
I hope I'm not hijacking this discussion, but I came across it when I was looking for the best way to create a compound keybinding of more than one command using the `init.coffee` script. I've been trying to create a command that first runs `autoflow:reflow-selection` and then `vim-mode:reset-normal-mode` to reproduce the way `gq` works in vim. After some trial and error I used @lee-dohm's answer to get the `editor` instance and call the function on it but it was really unclear from the documentation how to do that. 

I think my use case might be more common than calling commands from a package, and perhaps it is worth documenting how to do that (or even better - simplyfing the task for performing compound keybindings, perhaps by supplying a list of keybindings in `keymap.cson`?). I think that especially for vim users that are used to simply creating maps with multiple commands this will be an attractive feature.

**Comment by UziTech** [comment]
> It's likely that you don't want to execute commands programmatically.

Is there a better way to run a `toggle` command when Atom opens?

I am using the [multirow-tabs](https://atom.io/packages/multirow-tabs) package which provides a `multirow-tabs:toggle` command to turn it on and off but it is always off by default when Atom first opens.

This seems to be fairly standard practice as there are 5 other packages I toggle on in my init script. Is this something the package creators should deal with by having an option to enable by default?

**Comment by lee-dohm** [comment]
@UziTech Yes, I'm pretty surprised that a package like multirow-tabs is off by default.

**Comment by a-laughlin** [comment]
Handy way to autocomplete and execute package commands from dev console:
```js
window.atomCommandShortcuts = {};
for (let temp in atom.packages.commandRegistry.registeredCommands){
  if(!atom.packages.commandRegistry.registeredCommands.hasOwnProperty(temp)){continue;}
  window.atomCommandShortcuts[temp.replace(/[:\-]/g,'_')] = ()=>{
    atom.commands.dispatch(atom.views.getView(atom.workspace.getActivePane().getActiveEditor()), temp);
  };
}

// window.atomCommandShortcuts.tree_view_toggle()
```

Depends on atom's internal structure. Use at your own risk.  I put it in my init.js file when developing, and comment out when not.

**Comment by CoderSquirrel** [comment]
Hi i was wondering, of making my package and how would i do, for exemplo, to run, in my project folder a command in the windows cmd?

ex. i have a project and when i toggle my package it supposed to run in prompt 'cordova plugins --save' ?

how could i do this?

**Comment by lee-dohm** [comment]
@CoderSquirrel There are a number of ways to do this using either the [Node standard library](https://nodejs.org/en/docs/) or the [Atom API](https://atom.io/docs/api/latest/). You may want to take a look at https://atom.io/docs/api/latest/BufferedProcess.

**Comment by lee-dohm** [comment]
Thanks everyone for the feedback.

While `atom.commands.dispatch` is an option, commands aren't intended to be and are poorly designed for being used this way, so we're hesitant to document this as an officially supported method. If people have other ideas or suggestions, please open a new issue on the Flight Manual repo: https://github.com/atom/flight-manual.atom.io.

Thanks again for everyone's help and enthusiasm!
