### ISSUE TITLE
First start: 4 atom apps running: --eval require('...source-maps')

### ISSUE THREAD

**Issue by m1ga** [atom/atom#5566]
When I start atom for the first time I have a very high disc io. I've started iotop and found 4 apps running:

```
2288 be/4 user      717.17 K/s    0.00 B/s  0.00 % 98.51 % atom --eval require('/usr/local/share/atom/resources/app/node_modules/coffee-cash/lib/~ee/source-maps');
 2291 be/4 user      679.23 K/s    0.00 B/s  0.00 % 97.91 % atom --eval require('/usr/local/share/atom/resources/app/node_modules/coffee-cash/lib/~ee/source-maps');
 2290 be/4 user      694.40 K/s    0.00 B/s  0.00 % 97.41 % atom --eval require('/usr/local/share/atom/resources/app/node_modules/coffee-cash/lib/~ee/source-maps');
 2289 be/4 user      599.54 K/s    0.00 B/s  0.00 % 96.19 % atom --eval require('/usr/local/share/atom/resources/app/node_modules/coffee-cash/lib/~ee/source-maps');
```

its running for about a minute with 4 times almos 100% disc write usage. After a minute they are finished and no disc io 

atom 0.180.0-ac7057b
Dell M4500 Notebook
Fedora 21

**Comment by lee-dohm** [comment]
Personally, I feel this is a duplicate of #2654 because Atom reads a ton of files on startup. (And reads more on startup the more packages you install.) Because of this, the Atom team has considered placing Atom itself into an asar archive, ref: https://github.com/atom/atom/issues/2654#issuecomment-71556059

**Comment by m1ga** [comment]
Ok, I'll have a look. 

Just one point which I think is different: 
in my case atom is up and I can use it (so not directly related to the startup time) but these tasks are running next to my atom instance.

**Comment by kevinsawicki** [comment]
I believe this is a duplicate of #5566 since these do look like the processes that Atom spawns at startup that were mentioned as well on that issue.

**Comment by m1ga** [comment]
which ticket are you referring to? You linked to this ticket again :) Just want to subscribe to the new one

**Comment by kevinsawicki** [comment]
> which ticket are you referring to? You linked to this ticket again :) Just want to subscribe to the new one

Whoops, sorry for the confusion, meant to leave that comment over on #6571, reopened this one.
