### ISSUE TITLE
How to enable retina device for osx travis-ci?

### ISSUE THREAD

**Issue by fundon** [atom/atom#5568]
My package need to dectct the `window.devicePixelRatio` attribute。
And the `window.devicePixelRatio` is always `1`.
How to change it in Travis-Ci?

**Comment by thomasjo** [comment]
Simple workaround is to create a function in your package somewhere (wherever makes most sense) that reads and returns `window.devicePixelRatio`, e.g.
```coffee
devicePixelRatio: ->
  window.devicePixelRatio
```

then from your Jasmine spec you can create a spy for that function and return whatever you need;
```coffee
it "supports HiDPI displays", ->
  spyOn(whatever, 'devicePixelRatio').andReturn(2)
  # ...
```

**Comment by thomasjo** [comment]
Closing since this strictly speaking isn't a problem related to Atom. In addition, the workaround I provided should be sufficient.

**Comment by fundon** [comment]
Thanks
