### ISSUE TITLE
Atom not cleaning up some temp files

### ISSUE THREAD

**Issue by karai17** [atom/atom#5570]
I am clearing out my temp files on Windows and I noticed that there are a whole bunch of folders prefixed with "npm" and "ssh" that I believe are from Atom (Node Package Manager?). Once a package is installed, Atom should probably clean out these temporary files. Between Atom and Squirrel, I've cleaned out nearly 3gb of temporary files from the past three weeks.

**Comment by envygeeks** [comment]
I wonder if this isn't actually a node bug because this happens to me a lot without Atom but my system know's what "temporary" means so it's never a big deal since our systems go up and down multiple times a day which renders them not cleaning up moot either way I think this might be a node bug.

**Comment by damieng** [comment]
Closing down old issue - we're going to rely on npm and other packages to do the right thing with their temp files rather than try and clean up behind them.
