### ISSUE TITLE
GitHub Flavored Markdown

### ISSUE THREAD

**Issue by lukejanicke** [atom/atom#5574]
The markdown preview window doesn’t render some GitHub Flavoured Markdown properly.

Roses are red
Violets are blue

In Atom, these lines don’t break, which is correct Markdown behaviour but not correct GitHub Flavoured Markdown behaviour.

Furthermore, references are not being auto-linked.

* SHA: a5c3785ed8d6a35868bc169f07e40e889087fd2e
* User@SHA: jlord@a5c3785ed8d6a35868bc169f07e40e889087fd2e
* User/Repository@SHA: jlord/sheetsee.js@a5c3785ed8d6a35868bc169f07e40e889087fd2e
* #Num: #26
* GH-Num: GH-26
* User#Num: jlord#26
* User/Repository#Num: jlord/sheetsee.js#26

**Comment by izuzak** [comment]
This issue was moved to atom/markdown-preview#201
