### ISSUE TITLE
Sort Keybindings by source

### ISSUE THREAD

**Issue by joesustaric** [atom/atom#5580]
Hi there,

I would love it if I could sort the keybindings by source type.

Just so I can easily check out what I might want to start using in the Core or Tree View sections etc.
Thanks!
Joe

**Comment by nicolasmccurdy** [comment]
:+1:

**Comment by izuzak** [comment]
This issue was moved to atom/settings-view#385

**Comment by izuzak** [comment]
@joesustaric Perhaps this helps: you can get a list of keybindings for a specific package by going to Settings View -> Packages and then click on the package you want (e.g. Tree View), and you should see a list of keybindings:

![screen shot 2015-02-17 at 15 47 21](https://cloud.githubusercontent.com/assets/38924/6229991/4aadaa0e-b6bc-11e4-9fb5-d679d430a5fd.png)

**Comment by joesustaric** [comment]
Hi @izuzak , thats does help indeed. Thank you!
So for Tree View etc it works, but when I search for 'Core' I don't seem to get all the core packages.

I guess this feature still may help though. Being able to do some filtering via the keybindings section thats a little more intuitive to the way the data is displayed is probably my main point. My first instinct was to click on the column headers to see if it would sort by source. The filtering box is good , but I wanted to browse to discover the keybindings I would have never ever though to search for to use. :eyes: 
Thanks again.
