### ISSUE TITLE
mysql Plugin

### ISSUE THREAD

**Issue by NicoTravassos** [atom/atom#5581]
Hi can you please add **mysql** Plugin (Syntax) I notice you only have **sql**

**Comment by postcasio** [comment]
The SQL grammar can be used for a bunch of different SQL dialects. Is there anything in particular that doesn't work when you use SQL highlighting for MySQL?

**Comment by izuzak** [comment]
@NicoTravassos you might consider trying this package: https://atom.io/packages/language-sql-mysql

**Comment by NicoTravassos** [comment]
:+1:
