### ISSUE TITLE
No "Open Quickly..." menu item

### ISSUE THREAD

**Issue by fulldecent** [atom/atom#5586]
How to I open the feature shown here?

![d17b682c-b50a-11e4-8aa7-77f407583779](https://cloud.githubusercontent.com/assets/382183/6230790/688df1d6-b690-11e4-9848-205e14376db0.png)

Was expecting this the be listed at File -> Open Quickly..., and for the keyboard shortcut to be shown there.

**Comment by izuzak** [comment]
@fulldecent You're looking for the Fuzzy Finder, I believe: https://github.com/atom/fuzzy-finder. It's a package.

**Comment by paulcbetts** [comment]
This isn't a terrible idea on OS X to add it as "Open Quickly" since it's basically the same feature

**Comment by fulldecent** [comment]
Even if I know it was called Fuzzy Find, this is how I would try to find the keyboard short cut:

![screen shot 2015-02-17 at 11 39 15 am](https://cloud.githubusercontent.com/assets/382183/6232393/ac5c4382-b699-11e4-843d-c8ea8cec1ae3.png)

**Comment by izuzak** [comment]
> This isn't a terrible idea on OS X to add it as "Open Quickly" since it's basically the same feature

@paulcbetts I definitely didn't know "Open Quickly" was a standard OSX thing -- thanks! I've been using OSX for about 2 years and never seen that option myself (just checked Sublime, Skitch and a few other apps which open files). I'm not :-1: on adding such an option -- but not sure what the best place would be to open a feature request for that. Perhaps the Fuzzy Finder package?

**Comment by fulldecent** [comment]
Ah, got it I can do that. And to be sure, Atom core would provide the ability to fuzzy find to create a menu item if it wanted, right?

**Comment by izuzak** [comment]
> Even if I know it was called Fuzzy Find, this is how I would try to find the keyboard short cut:

@fulldecent The recommended way is to use the [Command Palette](https://github.com/atom/command-palette) -- it's mentioned on the Welcome screen [when you start Atom for the first time](https://github.com/atom/welcome/blob/master/docs/darwin/welcome.md).

You can also find the option in the Help -> Search box by typing "find file".

**Comment by izuzak** [comment]
> And to be sure, Atom core would provide the ability to fuzzy find to create a menu item if it wanted, right?

Fuzzy finder already adds a few menu options, just not the ones you expected:

https://github.com/atom/fuzzy-finder/blob/master/menus/fuzzy-finder.cson

**Comment by fulldecent** [comment]
Find file is reasonable, I should have found that
