### ISSUE TITLE
Error building atom on Arch Linux using node.js v 0.12.0 / npm v2.5.1

### ISSUE THREAD

**Issue by franktopel** [atom/atom#5587]
Please do not just close this again by referencing it to #3385 as this issue is NOT solved yet.

```
[connexo@archgott atom]$ script/build 
Node: v0.12.0
npm: v2.5.1
Installing build modules...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/connexo/packages/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/connexo/packages/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/home/connexo/packages/atom/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:359:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by franktopel** [comment]
Also, doing a `script/clean` before `script/build` (as suggested in #3385) does not help at all.

**Comment by izuzak** [comment]
@franktopel The output shows that you are using a version of node which is not listed as supported in the docs. Can you try building with the version which is listed as supported in the docs?

https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#requirements

**Comment by izuzak** [comment]
From https://github.com/atom/atom/issues/3385#issuecomment-53447854:

> Try running script/clean, then script/build again ******using node 0.10.x*******

**Comment by franktopel** [comment]
Rather than making users downgrade their version of node, don't you think atom should be adjusted to work with the recent stable versions of its dependencies?

**Comment by izuzak** [comment]
@franktopel I do think that, but for now -- please follow the documented requirements. Ignoring advice and the documented requirements doesn't help with that.

**Comment by franktopel** [comment]
I am getting your point. But instead of downgrading stable versions of important software I'd rather wait for someone to get this fixed and go with Sublimetext 3 for the time being.

**Comment by benogle** [comment]
Closing in favor of #5591

**Comment by kevinsawicki** [comment]
@franktopel Atom should now be buildable with node 0.12 via #5628, please let me know if you still see issues.

**Comment by stephanfriedrich** [comment]
@kevinsawicki 
hi i got this the same error with latest apm.
npm: 2.10.1 and node v0.12.4
