### ISSUE TITLE
Mac version does not support scroll bouncing

### ISSUE THREAD

**Issue by fulldecent** [atom/atom#5588]
Chrome supports -- good

![kismac2build2](https://cloud.githubusercontent.com/assets/382183/6232359/69062bf2-b699-11e4-9fbd-e99a0af8dceb.gif)

Atom does not -- bad

![kismac2build](https://cloud.githubusercontent.com/assets/382183/6232368/6d4ccc66-b699-11e4-91a6-b2081a53765c.gif)

**Comment by izuzak** [comment]
@fulldecent Not sure, but this looks like a duplicate of https://github.com/atom/atom/issues/345. Mind taking a look?

**Comment by fulldecent** [comment]
Sorry, closing. Duplicate of #345
