### ISSUE TITLE
.gitignore hiding doesn't seem to honor negation

### ISSUE THREAD

**Issue by nevir** [atom/atom#5589]
Example `.gitignore`:
```sh
/components/
!/components/foo/
!/components/bar/
```

Ideally, only `components/foo` and `components/bar` would be visible in tree view when "Exclude VCS Ignored Paths" is enabled

**Comment by izuzak** [comment]
@nevir This looks like a duplicate of https://github.com/atom/tree-view/issues/196 (also, https://github.com/atom/fuzzy-finder/issues/65 is similar). I'm going to close this in favor of those two issues -- please subscribe there for updates.
