### ISSUE TITLE
Moving the window of an unsaved tab should not prompt to save the document

### ISSUE THREAD

**Issue by alex** [atom/atom#5590]
Say you have two atom windows open. In one of the windows you have a tab with unsaved content. Right if you drag that tab from one atom window to the other, atom will prompt you to save the file. There's no reason for it to do this, the file's not being closed, nothing is being lost.

**Comment by karloluis** [comment]
In my case the file tab dragging automatically saves the changes to the new window. Also found a new issue with crossing  tabs to other windows. (https://github.com/atom/atom/issues/5630)

Please let us know what OS, Atom version, and Atom theme (if not the default) you are using. This might come in handy.

**Comment by alex** [comment]
This was whatever the latest was yesterday 0.179 I think on OS X, One Dark theme with Base16 Tomorrow Dark for syntax.

**Comment by karloluis** [comment]
Windows seems to behave differently. I guess we are down to waiting for some of the Mac guys to replicate this.

**Comment by jbt** [comment]
Happening here too, Ubuntu 14.04, built off dd271aae960039b35ce20e2ecfcfc5bc751b42da

 * Have two atom windows open
 * Create a new file in one (or edit an existing file)
 * Edit it so it contains some unsaved changes
 * Try to drag tab to new window
 * Original window warns about unsaved changes

Clarifying gif:

![unsaved](https://cloud.githubusercontent.com/assets/120506/6830223/50183a66-d310-11e4-90ed-0d4979db800a.gif)

**Comment by Archivist214** [comment]
I reproduced this issue on my Chromebook running Ubuntu 14.04.03 and Kernel 3.10.18. Atom is at complete default, atom dark theme & syntax. 

Is there anything I can do to help try resolutions?

**Comment by damieng** [comment]
Confirmed does not ask on Windows.
