### ISSUE TITLE
"Hide Git Ignored Files" does not honor ~/.gitignore

### ISSUE THREAD

**Issue by fulldecent** [atom/atom#5592]
The setting is shown below. This is the great place where I put stuff like

 > .DS_Store
 > *~
 > *.swp

![screen shot 2015-02-17 at 2 55 54 pm](https://cloud.githubusercontent.com/assets/382183/6236065/4f193c7c-b6b5-11e4-8b77-779db4045ed9.png)

**Comment by steelbrain** [comment]
:open_mouth: I didn't even know there's a `Hide Git Ignored Files Option` I thought it's something hard-coded, Why is it even true by default?

**Comment by lee-dohm** [comment]
Duplicate of #4203 *et al*. If you mean that the files are showing in the tree view, there is a separate setting in the Tree View package settings called `Hide VCS Ignored Files`:

![screen shot 2014-11-16 at 9 25 26 am](https://cloud.githubusercontent.com/assets/69169/5062347/980ac00e-6d72-11e4-93e1-8f2b8b237375.png)

And strangely, I do not have the `Hide Git Ignored Files` setting that you're showing in the Core settings:

![screen shot 2015-02-17 at 8 06 10 pm](https://cloud.githubusercontent.com/assets/1038121/6242276/7ef3a6a0-b6e0-11e4-9898-4ce26dc5a7bf.png)

I have to assume that some misguided package put that there.

**Comment by izuzak** [comment]
Yeah, there's also an open issue to make it more obvious in Settings View that some options are available in package settings as well:

https://github.com/atom/settings-view/issues/378

@fulldecent Does this explain the behavior you observed?

**Comment by fulldecent** [comment]
Posted to https://github.com/atom/tree-view/issues/375 closing here

Atom is package city. Triage here must be a full time job!

**Comment by mark-hahn** [comment]
> Triage here must be a full time job!

There isn't any triage.  There is another thread about security that is
discussing this topic.

https://github.com/atom/atom/issues/1763
