### ISSUE TITLE
Ruby editor: typing #{ autocomplete annoying

### ISSUE THREAD

**Issue by fulldecent** [atom/atom#5595]
In general, all autocomplete functionality should obey this rule:

> Text automatically inserted in the current line is marked
> If the cursor is before a marked character and the marked character is entered, the cursor advances to the right one space and no further effect happens
> When leaving focus of the current line, all marking is lost

Following shows an example of a "helpful" autocomplete in Ruby becoming a pain:

![kismac2build2](https://cloud.githubusercontent.com/assets/382183/6238329/2b1903da-b6c8-11e4-82d5-8731b6255929.gif)

**Comment by nicolasmccurdy** [comment]
:+1:

**Comment by russlescai** [comment]
I noticed the same thing in a coffeescript file.

**Comment by lee-dohm** [comment]
This functionality is provided by the [bracket-matcher package](https://github.com/atom/bracket-matcher). Would you mind re-opening this issue on that repository?

**Comment by fulldecent** [comment]
Thank you, closing, moved https://github.com/atom/bracket-matcher/issues/109

**Comment by lee-dohm** [comment]
Thanks!
