### ISSUE TITLE
Atom Windows installer does not pin to Start menu in Windows 8+

### ISSUE THREAD

**Issue by jasoncavett** [atom/atom#5601]
**Atom Version**: 0.180.0
**Windows Version**: 8.1

**Issue**: Ran the Atom Windows installer. Everything installed correctly and it ran, however, no executable can be found in the Start Menu if I wanted to fire up the editor directly. I can always right click on a file and fire it up that way (via Open with Atom), but, when creating a new file, this seems lacking.

**Expected Behavior**: See Atom pinned in my Start Menu. The location for many of my shortcuts appear at *C:\ProgramData\Microsoft\Windows\Start Menu\Programs*. This is how Sublime, Notepad++, and other editors work during installation on Windows.
**Other Data**: I installed to a Windows 7 box, and this same problem does not seem to be occurring.

**Comment by kevinsawicki** [comment]
Did the desktop shortcut appear?

**Comment by jasoncavett** [comment]
@kevinsawicki No, the desktop shortcut did not appear either. I didn't even realize one should. (I typically always tell installers not to install the desktop shortcut.)

**Comment by paulcbetts** [comment]
No repro on my machine, Atom shows up on both the desktop and start menu. I'll try a clean install and see if it happens

**Comment by jasoncavett** [comment]
@paulcbetts I just fired up one of my VMs (Windows 7) and performed the installation there. It, too is not showing anything in the Start Menu or on the Desktop. I don't have access to another Windows 8 VM here, but I will try it out tonight as well.

Side note, I noticed the installer I just used installed 0.179.0 on the Windows 7 installation.

**Comment by kevinsawicki** [comment]
@paulcbetts I was able to reproduce on a clean install on my other VM, what debugging information would be helpful for this? The squirrel log is pretty empty, just the updating messages, no errors.

**Comment by paulcbetts** [comment]
@kevinsawicki If I bump grunt-atom-shell-installer to the latest version and build an installer, I seem to get shortcuts, not sure what's going on here

**Comment by kevinsawicki** [comment]
Yup, looks to be resolved by upgrading to Squirrel 0.8.5.

Fixed by https://github.com/atom/atom/commit/83b27fc93e55522187cb4464830d6ac13f7e80a3

**Comment by darkf** [comment]
I'm not seeing a desktop nor start menu shortcut on the latest stable version, with the installer.

**Comment by MoutazEltoomy** [comment]
Go to the location of atom at your system drive for me the path is "AppData\Local\atom\app-1.6.0"
then right click on the app launcher icon and from the shortcut menu select "pin to start menu".

**Comment by robertnicjoo** [comment]
@jasoncavett try to add icon shortcut in your desktop from here:

> C:\Users\"your user name"\AppData\Local\atom\app-1.5.4\atom.exe

**Comment by kapcom01** [comment]
@MoutazEltoomy @robertnicjoo is this the expected procedure?

I think this is a bug. I justs installed atom on Ubuntu and Windows 10, and there were no shortcuts/launchers added.

**Comment by darkf** [comment]
I'd agree that this is a bug. Nearly every other application properly installs a desktop shortcut; Atom flat out fails to.

**Comment by spayeur** [comment]
Still an issue with Windows 7 Pro SP1

**Comment by darkf** [comment]
Is this very basic feature really still an issue?

Come on, Atom.

**Comment by Ben3eeE** [comment]
Atom 1.10 introduced the new Systems tab in the settings-view for shell integrations. This caused some issues with shell integrations when upgrading to new versions. @damieng tracked down these issues in https://github.com/atom/atom/pull/12643. If you experience problems you can try re enabling the settings in the systems tab or wait for this fix to become available.

**Comment by damieng** [comment]
That bug should not have affected desktop or start menu shortcuts.

During a fresh install you should get a start-menu and a desktop shortcut.

During an upgrade it will attempt to change the path on;

1. the start-menu shortcut
2. the desktop short-cut only if it already exists (i.e. the user didn't delete it)
3. a pinned copy of Atom in the task bar

**Comment by baslie** [comment]
I'm using Windows 7 x64 and also didn't get any shortcuts on my machine: neither in start menu, nor on a desktop. So I had to create it manually from C:\Users\%username%\AppData\Local\atom\app-1.10.2. What I'm doing wrong?

**Comment by damieng** [comment]
Please post the squirrelsetup.log file from your atom folder.

**Comment by baslie** [comment]
@damieng, here it is: [https://gist.github.com/baslie/af85d90a7879b08ea0288496a9294072](gist.github.com/baslie/af85d90a7879b08ea0288496a9294072)

**Comment by damieng** [comment]
@baslie Are you running any anti-virus packages?  The log file indicates it was being denied access to its own files.

**Comment by baslie** [comment]
@damieng Yes... I've already found out there was a problem with my Dr.Web Anti-Virus. I will try to reinstall it. Thanks a lot!

**Comment by ilyaigpetrov** [comment]
Same problem with Avast antivirus, no notifications from Avast, no shortcut created. Install log: https://gist.github.com/anonymous/1ca66bef07a5245ed26311bfcd2369ae  

How to (re)create atom shortcut manually after this issue?

**Comment by damieng** [comment]
@ilyaigpetrov you can create a shortcut by right-dragging atom.exe from %localappdata%\atom-1.13.1\atom.exe to your desktop or start menu and then choosing *Create shortcut here*

**Comment by paulcbetts** [comment]
Run this:

```sh
%LocalAppData%\Atom\app-YOURVERSION\atom.exe --squirrel-install YOURVERSION
```

**Comment by madcowjay** [comment]
@paulcbetts FYI: this added an icon to my desktop, but not to my start menu in Windows 10.
