### ISSUE TITLE
--dev linked packages are undefined unless in --dev mode

### ISSUE THREAD

**Issue by sedabull** [atom/atom#5602]
Atom v-0.180.0
Ubuntu 14.04

See the last half of the discussion at #5492. Here are the highlights:
* git clone an atom package locally
* run apm install to bring in node_modules
* run apm link --dev
* open atom

In the settings view, you will see the package under the `development packages` section. However, you cannot adjust the settings, none of the activation events are available, and running `atom.packages.resolvePackagePath('my-package')` in the dev tools returns `undefined`. Instead a prompt to install the package is displayed (as in the install packages view). Running atom in dev mode behaves as expected. Here is a relevant screen shot on atom v-0.180.0:
![atom-dev-error](https://cloud.githubusercontent.com/assets/9311295/6241773/f22d45b2-b6f0-11e4-9d0c-2a7daa43e5a2.png)

cc @kevinsawicki @thedaniel

**Comment by lee-dohm** [comment]
As I commented on your pull request, packages in `~/.atom/dev/packages` are not supposed to be loaded *unless* you're in Dev Mode. So all of the behavior you mention like the activation events not being available, `atom.packages.resolvePath` not resolving, etc are expected if those packages are not also installed in the `~/.atom/packages` directory.

If you think that the "Development Packages" section should be hidden when not in Dev Mode, that might be reasonable, but it should be filed on the [settings-view package](https://github.com/atom/settings-view).

Please let me know if I've misunderstood your intent.

**Comment by sedabull** [comment]
If this is in fact the intended behavior, then I'm fine with both this issue and my related pull request being closed. But this has been open for almost a week, without any discussion, so I figured I'd look into it myself.

**Comment by lee-dohm** [comment]
Thank you for your tenacity in pushing for this to be resolved. I realize I'm a little late to the party and don't have the full context, I just wanted to give more information ... including for others that might stumble on this Issue or Pull Request later through searches :grinning:

**Comment by sedabull** [comment]
@lee-dohm, I'm happy to do whatever small things I can to help Atom succeed. I love this project, and the community behind it! Closing this in favor of an issue on atom/settings-view.
