### ISSUE TITLE
Add CORS headers for atom.io API usage

### ISSUE THREAD

**Issue by davidpett** [atom/atom#5603]
looking at the api, I would like to create an app to search themes and display them. The api endpoints are there, but I cannot consume them via ajax because of CORS.

Can you add a https://atom.io/crossdomain.xml to allow access?

**Comment by izuzak** [comment]
@davidpett Just to make sure we understand, would returning CORS headers instead of adding a crossdomain.xml file meet your needs (since that would allow you to make HTTP requests from client-side JS)? Or are you building a flash app?

**Comment by davidpett** [comment]
Oh my gosh, yes CORS headers is all I need, sorry.

That's embarrassing.

On Wednesday, February 18, 2015, Ivan Žužak <notifications@github.com>
wrote:

> @davidpett <https://github.com/davidpett> Just to make sure we
> understand, would returning CORS headers instead of adding a
> crossdomain.xml file meet your needs (since that would allow you to make
> HTTP requests from client-side JS)? Or are you building a flash app?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/5603#issuecomment-74858580>.
>


-- 

*-DP*

**Comment by izuzak** [comment]
Ha, thanks for clarifying :+1: :smile:.

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#19
