### ISSUE TITLE
Untitled file Version 0.180.0

### ISSUE THREAD

**Issue by svsudhir** [atom/atom#5607]
My Atom installation got updated to 0.180 today. I noticed an issue.  

When you start this version, it opens an "Untitled" file automatically. Now, you close Atom without editing anything at all. Open Atom again, now you will see 2 "Untitled" files. Close again and reopen, you will see 3 Untitled files. Looks like Atom keeps on adding more Untitled files if you exit without closing them.

Other issues as and when reported will be reported. Oh by the way, I like this editor better than Brackets for some reason :)

Thanks
Sudharshan

**Comment by pwaring** [comment]
I've noticed the same problem on 0.180 on a Mac, didn't exist in 0.179. I'm wondering if this is related to Atom remembering which files were open - I've noticed that as of 0.180 if I open a directory Atom now automatically opens all the files I had open when I quit with that directory in the left-hand pane.

**Comment by izuzak** [comment]
> When you start this version, it opens an "Untitled" file automatically. Now, you close Atom without editing anything at all. Open Atom again, now you will see 2 "Untitled" files. Close again and reopen, you will see 3 Untitled files. Looks like Atom keeps on adding more Untitled files if you exit without closing them.

I'm seeing this as well. Not really sure what might have triggered this, perhaps @maxbrunsfeld or @kevinsawicki have an :bulb:?

**Comment by svsudhir** [comment]
> @pwaring I've noticed that as of 0.180 if I open a directory Atom now automatically opens all the files I had open when I quit with that directory in the left-hand pane.

I noticed this too. Is there a config option that can be set to choose this new behaviour or continue with earlier behaviour? Such an option would be nice actually as we can choose how Atom must behave. I wonder what other surprises are present in this updated version.

**Comment by jonathandelgado** [comment]
+1

**Comment by mark-hahn** [comment]
This brings up the age-old question of whether there should be an untitled
tab.  I only use untitled when I'm bringing up an editor for a quick file
creation.  Since Atom has slow startup I use another editor for these
purposes.  I use Atom for programming only.
