### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidDestroy' of null

### ISSUE THREAD

**Issue by amisarca** [atom/atom#5609]
Every time I try to open a directory, I get this error:

**Atom Version**: 0.180.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidDestroy' of null

```
At /Applications/Atom.app/Contents/Resources/app/src/git-repository-provider.js:46

TypeError: Cannot read property 'onDidDestroy' of null
    at GitRepositoryProvider.module.exports.GitRepositoryProvider.repositoryForDirectorySync (/Applications/Atom.app/Contents/Resources/app/src/git-repository-provider.js:46:13)
    at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:275:89)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:39:25)
    at EventEmitter.emit (events.js:119:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "followSymlinks": true,
    "themes": [
      "space-ui",
      "base16-eighties-dark"
    ],
    "disabledPackages": [
      "deprecation-cop",
      "dev-live-reload"
    ]
  },
  "editor": {
    "fontFamily": "Monaco",
    "fontSize": 14,
    "lineHeight": 1.5,
    "showIndentGuide": true,
    "softWrap": true,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.0.10
autocomplete-snippets, v1.0.0
base16-eighties-dark, v2.1.1
color-picker, v1.4.4
file-icons, v1.4.8
language-haml, v0.15.0
language-mason, v2.0.0
language-perl, vundefined
language-ruby, vundefined
language-ruby-on-rails, vundefined
project-manager, v1.15.5
script, v2.16.0
space-ui, v0.6.3

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@amisarca Can you clarify what you mean by this: "Every time I try to open a directory"? How are you opening a directory exactly (from the terminal, from within Atom, ...)? Does this happen for every directory or only for some? Can you reproduce this for a repository on github.com, and if so -- can you share a link to that repository?

:wave: /cc @bolinfest because `git-repository-provider`. :smile:

**Comment by amisarca** [comment]
I tried various ways of opening the folder (through terminal, through project manager), and every time I was given the same error. The error was thrown for every folder I was trying to open (no matter if it was a git repository or not).

Hope that helps.

**Comment by gargleblaster** [comment]
I'm seeing the same thing.  The folder worked fine for months, but now, I get this every time I try to open it.  My preferred way to open it is by dragging the folder from Finder and dropping it on an Atom window, but it also happens from Atom's File > Open dialog box.  I believe it is related to the contents of the directory, because I am still able to open other folders.

**Comment by bradennapier** [comment]
I am also having this issue.  

From what I can tell, it has to do with having multiple projects with git repos open at the same time.  It would appear that atom looks at the very top root level for the.git and any .git folders in nested folders causes problems.  That is just my initial assessment 

```
29T17:47:52.800Z] [ERROR] installErrorReporter - Caught unhandled rejection Cannot read property 'on' of null
TypeError: Cannot read property 'on' of null
    at GitRepository.module.exports.GitRepository.onDidDestroy (/Applications/Atom.app/Contents/Resources/app/src/git-repository.js:130:32)
    at /Applications/Atom.app/Contents/Resources/app/src/project.js:211:28

Uncaught (in promise) TypeError: Cannot read property 'on' of null
    at GitRepository.module.exports.GitRepository.onDidDestroy (/Applications/Atom.app/Contents/Resources/app/src/git-repository.js:130:32)
    at /Applications/Atom.app/Contents/Resources/app/src/project.js:211:28
```
