### ISSUE TITLE
Atom helper high CPU on Mac

### ISSUE THREAD

**Issue by roboen** [atom/atom#5611]
Using 0.180.0 on Yosemite 10.10.2, I consistently the Atom Helper process run at 80%-100% CPU.

**Comment by izuzak** [comment]
Thanks for the report @roboen -- I'm closing this in favor of https://github.com/atom/atom/issues/3426. If you have any other details you'd like to add -- please add a comment to that issue.

**Comment by jomach** [comment]
Same problem here

**Comment by nicolazj** [comment]
replace /Applications/Atom.app/Contents/Resources/app/apm/bin/node with newer version, like 0.12.*

It works perfectly now

**Comment by lee-dohm** [comment]
As I mentioned in [my post on Discuss](https://discuss.atom.io/t/atomhelper-high-cpu-usage/2553/111?u=leedohm), replacing that copy of node doesn't change the version of node that Atom is running on.
