### ISSUE TITLE
atom.project.path === undefined

### ISSUE THREAD

**Issue by mgrenier** [atom/atom#5613]
Windows 8.1
Atom 0.180

Step to reproduce

1. Open Atom
2. Open Folder ...
3. Select a folder
4. Open Developer Tool `CTRL+ALT+I`
5. Type `atom.project.path` (Enter)

Output :
```
undefined
```

Expecting output from 0.179
```
D:\path\to\my\project
```

**Comment by bolinfest** [comment]
It was never a public field. Change to atom.project.getPath() for a quick
fix: that is deprecated but still supported.

Long term fix is to use atom.project.getPaths() because Atom is starting to
support multiple root folders. Note that can return an empty array.

**Comment by thomasjo** [comment]
What @bolinfest said. Closing this since it isn't a bug.

**Comment by mgrenier** [comment]
Thanks for your quick reply. Will make changes.

**Comment by MggMuggins** [comment]
atom.package.getPaths() is returning undefined for me. Any advice?
