### ISSUE TITLE
Open Folder always creates a new window (Atom 0.180.0)

### ISSUE THREAD

**Issue by jonathandelgado** [atom/atom#5615]
In Atom 0.180.0, if you go to `File -> Open Folder`, Atom always creates a new window, even if there isn't a folder for the current window.

To explain further, to open a folder:
- Open window one (with no folder/project specified)
- Click "Open Folder" on window one
- Window two opens
- Close window one
- Switch back to window two and start working

This is in contrast to the previous method which would add folders to the current window if none were already added.

I was able to replicate in safe mode.
Windows 7 x64
Atom 0.180.0

**Comment by m1ga** [comment]
I have the same on linux/KDE https://github.com/atom/atom/issues/4996  perhaps this could be fixed here too. But I had it in the previous versions too (and still have it with the latest version from git)

**Comment by jackmaney** [comment]
On OSX 10.9.5, I have a similar issue: clicking on the Atom icon in the dock always creates a new window, even if I have an Atom window open. Before 0.180.0, clicking on the Atom icon would just go back to a currently-opened Atom window.

**Comment by m1ga** [comment]
just did a new checkout and in linux its still the same (wrong) behavior

**Comment by jackmaney** [comment]
Just installed 0.181.0 on OS X, and it's working fine again.
