### ISSUE TITLE
[Windows:chocolatey] No packages search, Install Shell Commmands option 

### ISSUE THREAD

**Issue by dumle29** [atom/atom#5616]
So I installed atom via chocolatey, it installed to 

    [blah]\AppData\Local\atom\

which I assume is correct.

Now if I go to settings packages (clicking my way, or ctrl-), there's no option to search for uninstalled packages, only installed packages, As seen here: ![Image of package tab](http://i.imgur.com/nEjCVuz.png)

Going to the file tab, there's no Install Shell Commmands menu as seen here: ![No Install Shell Commmands option](http://i.imgur.com/1OgjTyQ.png)

apm is installed, and is found at

    [blah]\AppData\Local\atom\app-0.180.0\resources\app\apm\bin

Atom is run as admin.

Info:
* Windows 7 x64
* Atom 0.180.0
* Launched with: C:\Users\Mikkel\AppData\Local\atom\app-0.180.0\atom.exe (launching atom.cmd in local\atom\bin doesn't make a difference)

**Comment by kevinsawicki** [comment]
> Now if I go to settings packages (clicking my way, or ctrl-), there's no option to search for uninstalled packages, only installed packages

The Install section on the left side will give you the ability to search for and install packages and themes.

**Comment by kevinsawicki** [comment]
> Going to the file tab, there's no Install Shell Commmands menu as seen here: 

`atom` and `apm` shell commands are automatically installed by the installer so this option isn't needed on Windows.

**Comment by dumle29** [comment]
Ah thankyou, I also found [this](http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html) so yea

**Comment by mark-hahn** [comment]
Chocolatey has always been a problem with Atom.  You should use the
official installer instead.
