### ISSUE TITLE
Tree-view is broken on Windows 8.1 since 0.180.0

### ISSUE THREAD

**Issue by green-mdoerflinger** [atom/atom#5617]
Since Atom updated to 0.180.0 my tree-view only shows the content of the atom folder instead of the project/folder opened (see screenshot below). Opening a new folder does not help, tree-view still shows the content of the atom folder. 
I tried reinstalling Atom and i even removed all configuration etc that were left behind. For one session its fine, after restart of Atom is shows the wrong content again. I use Windows 8.1 as OS. 
Thanks for looking into it! 

![image](https://cloud.githubusercontent.com/assets/10849280/6253730/dea37df0-b7a3-11e4-863f-4d596f345636.png)

**Comment by kevinsawicki** [comment]
How are you opening Atom? From the command line? Start menu? Shortcut?

**Comment by ScuttleBird** [comment]
I am having the same issue on windows 7.

The file tree will only show my last opened file tree from version 0.179.0

When selecting a new folder with Open Folder, a new atom window opens with the same file tree. Same if I try to open a file with Open File, or use the context menu Open with Atom, the file opens, but the file tree doesn't change.

No matter what I do the file tree wont change.

I have opened atom through shortcut, start menu and .exe, no difference.

**Comment by Trudko** [comment]
I have same experience on Windows 8.

**Comment by ericwooley** [comment]
Seconded for windows 8. Sometimes it also opens the directory C:\Windows

All plugins disabled, using version 0.180.0

**Comment by kevinsawicki** [comment]
So if you have Atom completely closed, right click on a folder from the explorer, and select "Open With Atom", the correct folder doesn't get opened?

**Comment by ericwooley** [comment]
@kevinsawicki It does not,

**Comment by kevinsawicki** [comment]
> It does not,

What folder does appear in the tree view in that scenario?

**Comment by ericwooley** [comment]
C:\Users\<me>\AppData\Local\atom

**Comment by 50Wliu** [comment]
Refs #5212 and #4653.

**Comment by kevinsawicki** [comment]
0.181 is out now, could people try upgrading and see if this issue persists? Thanks :shipit:

**Comment by ScuttleBird** [comment]
Still the same issue for me, Windows 7, version 0.181.0

**Comment by kevinsawicki** [comment]
> Still the same issue for me, Windows 7, version 0.181.0

Can you try running the following from the Console tab in the dev tools (`ctrl-alt-I`):

```js
atom.project.getPaths()
atom.getLoadSettings().initialPaths
```

**Comment by ScuttleBird** [comment]
["c:\Users\<Hide-Path>\Work\Macfarlane\public_html", "C:\Users\<Hide-Path>\Work\HouseSender\public_html"]
["C:\Users\<Hide-Path>\Work\HouseSender\public_html"]

**Comment by maxbrunsfeld** [comment]
@ScuttleBird and in that case, how did you open Atom? Which directory did you open?

**Comment by ericwooley** [comment]
~~~
atom.project.getPaths()
["."]

atom.getLoadSettings().initialPaths
[]
~~~
still happening in 181, do you not have a windows box to test with?

**Comment by maxbrunsfeld** [comment]
@ScuttleBird @ericwooley can you try temporarily removing the contents of your `$ATOM_HOME/storage` directory and restarting Atom?

**Comment by maxbrunsfeld** [comment]
@ericwooley @ScuttleBird can you list your installed packages? @ScuttleBird does this happen if you start Atom with `atom --safe`?

**Comment by ScuttleBird** [comment]
Ok got it. It is working again as long as this plugin is turned off (https://atom.io/packages/save-session)

In version 0.180.0 I had turned this plugin off, but the file tree still would not update properly. In version 0.181.0 with this plugin off the file tree is working properly.

I had previously emptied the storage folder in version 0.180.0 and just now in 0.181.0, it didn't help in either case.

Thank you for the quick fix.

**Comment by maxbrunsfeld** [comment]
Ok that's good news. @green-mdoerflinger @Trudko can you report whether this problem persists in 0.181 with `atom --safe`?

**Comment by ericwooley** [comment]
Here is an ls of my packages folder
~~~
$ ls -l
total 21
-rw-r--r--    1 ewooley  Administ       61 Jan 16 14:37 README.md
drwxr-xr-x   19 ewooley  Administ     4096 Feb  9 09:11 atom-beautify
drwxr-xr-x    1 ewooley  Administ     4096 Feb  5 08:49 auto-reveal-in-sidebar
drwxr-xr-x    1 ewooley  Administ     4096 Feb 12 09:41 autocomplete-plus
drwxr-xr-x   12 ewooley  Administ     4096 Jan 20 09:08 docblockr
drwxr-xr-x   14 ewooley  Administ     4096 Feb  3 10:07 emmet
drwxr-xr-x   16 ewooley  Administ     4096 Feb  9 11:49 jshint
drwxr-xr-x    7 ewooley  Administ     4096 Jan 30 14:47 monokai
drwxr-xr-x    1 ewooley  Administ     4096 Feb  4 11:02 open-last-project
drwxr-xr-x   11 ewooley  Administ     4096 Jan 20 09:53 resize-panes
drwxr-xr-x   16 ewooley  Administ     4096 Feb 18 09:28 vim-mode
~~~
and here is my config.cson
~~~
"*":
  editor:
    fontSize: 14
    invisibles: {}
    useShadowDOM: false
    scrollPastEnd: true
    showIndentGuide: true
    preferredLineLength: 100
    tabLength: 4
  core:
    disabledPackages: [
      "linter-jshint"
      "open-last-project"
      "auto-reveal-in-sidebar"
      "vim-mode"
      "resize-panes"
      "jshint"
      "emmet"
      "docblockr"
      "autocomplete-plus"
      "atom-beautify"
    ]
    themes: [
      "atom-dark-ui"
      "monokai"
    ]
    autoHideMenuBar: true
  "exception-reporting":
    userId: "472b0049-6e81-a5f5-f3a4-fb69a5b7d170"
  welcome:
    showOnStartup: false
  "linter-jshint": {}
  "vim-mode":
    startInInsertMode: true
    useSmartcaseForSearch: true
  "word-jumper": {}
  "atom-beautify":
    _analyticsUserId: "1c700436-05e7-4f55-b8fc-f76d09215704"
    js_indent_size: 4
    js_max_preserve_newlines: 2
    js_jslint_happy: true
    js_break_chained_methods: true
    js_keep_array_indentation: true
  "autocomplete-plus-async":
    autoActivationDelay: 10
  jshint:
    supportLintingJsx: true
  "autocomplete-plus":
    confirmCompletion: "tab and enter"
  "tree-view":
    hideVcsIgnoredFiles: true
~~~

Everything seems to be working with no plugins installed, I am attempting to figure out the circumstances in which things get screwed up.

**Comment by ericwooley** [comment]
Its open-last-project that is screwing it up. Unloaded everything works well, as soon as it's enabled it attempts to load the last project and the tree loads C:\Windows\System32, then upon reloading atom (with the plugin installed) it loads up "C:\Users\ewooley\AppData\Local\atom\app-0.181.0"

**Comment by maxbrunsfeld** [comment]
The `open-last-project` package [uses a private property](https://github.com/danielmahon/atom-open-last-project/blob/master/lib/open-last-project.js#L13) `atom.project.path`, rather than the public method `atom.project.getPath()`. That property is gone as of Atom 0.180.

**Comment by ericwooley** [comment]
Cool, created and issue for it and referenced this, so it should be easy for them to solve.
https://github.com/danielmahon/atom-open-last-project/issues/25

**Comment by green-mdoerflinger** [comment]
Thanks for hunting it down!
