### ISSUE TITLE
Usability with git rebase, amend, etc

### ISSUE THREAD

**Issue by steveoh** [atom/atom#5620]
I have been using atom as my default editor when using git. One productivity issue I have is with the `--wait` command where you have to close the entire atom instance for waiting to be done. I know this sounds normal but when rebasing the atom instance needs to opened and closed many times and the load times on windows leave some time for thumb twiddling. My window load time is around 3-4 seconds.

It would be hot if atom could trigger the `--wait` completion when the tab is closed. I believe this is the behavior in sublime text. 

_My cursory search for this topic didn't show any results._

**Comment by 50Wliu** [comment]
#461?
