### ISSUE TITLE
GCC - Mingw C/Lua build workflow

### ISSUE THREAD

**Issue by Dany0** [atom/atom#5622]
Right now I have to have 3 cmd-line windows to debug the C/Lua project. One MSYS window to build the (Makefile) C source (if needed), another to launch the server and another to launch the client (SDL game).

I want to set up a better workflow with atom, a few build/run/debug profiles, a build and run server+client(optionally in gdb, even better if you could integrate gdb into atom), another to just run server+client(by server+client I mean, run the server, wait for it to initialize, run the client). It would even better if you could redirect the server terminal output to atom.

Is there any package that can help me do that? I tried all the build packages they don't do what I need. 

I can use the terminal package, but that's just what I was using before with fancy shortcuts :unamused: 

At least I can ditch Notepad ++ 

Sorry if this issue is worded badly, I asked in #atom and they told me to write it this way.

**Comment by Zireael07** [comment]
There's a linter package and two lua linting scripts. Maybe that's what you want?

**Comment by Dany0** [comment]
Please read my post, your suggestion is ridiculous of course I already have the linters. Also your avatar is astonishingly bad.

I assigned F12 to "compile" in atom-terminal-panel so I'm somewhat happy for now. It has no autocomplete but I can live with custom commands. It's also not a versatile solution. And also I hate atom with passion now.

**Comment by thomasjo** [comment]
Workflow and general package questions should go to [Discuss](https://discuss.atom.io/) and not here.

---
As a side note, adopting a slightly less hostile attitude against people trying to help you, is highly advisable. And if you hate Atom, maybe you should check out [CLion](https://www.jetbrains.com/clion/) which is a C/C++ IDE.
