### ISSUE TITLE
PackageState doesn't change when ProjectPath is changed programitcally

### ISSUE THREAD

**Issue by steelbrain** [atom/atom#5625]
```
console.log(atom.packages.packageStates) //<-- have a look at it
atom.project.setPaths(['/var/www']) // <-- change it to any other project
console.log(atom.packages.packageStates) //<-- same
```

**Comment by maxbrunsfeld** [comment]
The property `atom.packages.packageStates` isn't part of Atom's public API; it's for internal use only. Can you explain why you're using it? There might be a different way to achieve what you're going for.

**Comment by steelbrain** [comment]
I am using it in a package which re-opens the last opened project.
I wanted to use `atom.packages.packageStates` to get the serialized data I have for that project. Opened files for example.

Because I need Opened Files for the Project that I set myself, not the default one, the state I get on activation is useless.

**Comment by maxbrunsfeld** [comment]
You shouldn't use `atom.packages.packageStates` for this. It has nothing to do with the project paths. There's no reason for it to change when calling `project.setPaths`.
