### ISSUE TITLE
Extreme Performance issues after 0.180.0

### ISSUE THREAD

**Issue by bobber205** [atom/atom#5626]
First I'd like to say the new text parsing improvements are GREAT. :dancer:

But I can only guess that they've caused a memory leak or something. After opening a few large files in a couple different windows and letting an hour or so pass by, my computer was barely responding.

![image](https://cloud.githubusercontent.com/assets/5841107/6258331/9af9be7e-b77c-11e4-9034-b13d1b3a4c93.png)

That red spike is memory usage was Atom. Each process was taking about 200 megs or so. I think it's normally around 15mb?

If it happens again, please let me know what other details I can give.

**Comment by kevinsawicki** [comment]
What platform are you on? Is this happening consistently for you? If so, for all projects or only certain projects? If it occurs consistently for a specific project, could you share a link to its repository so I can try and reproduce?

**Comment by batjko** [comment]
Also, to cover the basics... Is it reproducible in safe mode (`atom --save`) and how many tabs / files do you have open while it happens?

**Comment by philipgiuliani** [comment]
I had today 4 atom processes with 1GB/each :o my pc has 16gb. After restarting atom everything was responsive again. :)

**Comment by benogle** [comment]
Closing in favor of https://github.com/atom/atom/issues/1827
