### ISSUE TITLE
Minor release naming request for linux

### ISSUE THREAD

**Issue by mehcode** [atom/atom#5629]
Could we get the version number in the *deb* file that is posted on the github downloads page. It's pretty straight forward for me to grab the next version every time its released but when I need to quickly rollback my folder has a bunch of `atom-amd64(N).deb` files.

Super minor and I'll no longer care once we get an offical PPA going but for the time being it'd be awesome.

**Comment by ricardograca** [comment]
Duplicate of #4044.

**Comment by mehcode** [comment]
@ricardograca Thank you.
