### ISSUE TITLE
Dragging files into a new window is not possible

### ISSUE THREAD

**Issue by karloluis** [atom/atom#5630]
I was trying to replicate the following issue (https://github.com/atom/atom/issues/5590) when I stumbled upon this one.

Dragging a file from window to another was not possible unless a previous file was already open. I had to open another (even if Untitled) file to be able to drag the tab onto the other window. The dragging symbol appeared, instead of the crossed circle for invalid, but after releasing the mouse button nothing changed.

I don't know if this might be caused by the Theme I currently (and forever, it's beautiful) use. If it is I'll refer it to the proper channels.

Win 7 64bit
Atom -v181
Seti-UI (theme)

**Comment by damieng** [comment]
This has been fixed at some point and seems to work just fine now. Please re-open if it doesn't for you on a newer build of Atom.
