### ISSUE TITLE
New window command creates new file when window has no project path

### ISSUE THREAD

**Issue by postcasio** [atom/atom#5631]
In 0.181.0 on OS X. Steps to reproduce:

1. `atom --safe`
2. `cmd-shift-n`
3. `cmd-shift-n` in the new window. A new file is created instead.

If you then open an existing file in the new window, giving it a project path, the new window command starts working again.

**Comment by izuzak** [comment]
I can reproduce this in `0.182.0-ea7cd51`. cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
Thanks for catching this @postcasio and @izuzak.
