### ISSUE TITLE
Uncaught SyntaxError: Unexpected string

### ISSUE THREAD

**Issue by dbrimeg** [atom/atom#5635]
[Enter steps to reproduce below:]

1. Just opened Atom this morning by clicking the icon in my windows taskbar

**Atom Version**: 0.180.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: Atom Core

### Stack Trace

Uncaught SyntaxError: Unexpected string

```
At file:///C:/Users/Daniel%20Brime/AppData/Local/atom/app-0.180.0/resources/app/static/index.html?loadSettings=%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5CDaniel%20Brime%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.180.0%5C%5Cresources%5C%5Capp%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CDaniel%20Brime%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.180.0%5C%5Cresources%5C%5Capp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.180.0%22%2C%22shellLoadTime%22%3A418%2C%22initialPaths%22%3A%5Bnull%5D%7D:1

SyntaxError: Unexpected string
    at Object.parse (native)
    at /C:/Users/Daniel%20Brime/.atom/packages/save-session/lib/files.coffee:20:30
    at fs.js:337:14
    at FSReqWrap.oncomplete (fs.js:100:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
save-session, v0.11.5

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Seems like a problem with the save-session package. Can you try updating to Atom 0.181.0 and report it over at https://github.com/mpeterson2/save-session/issues if you can still reproduce?

You shouldn't be seeing this if you quit Atom and restart in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode). Let me know if you do.

**Comment by dbrimeg** [comment]
I updated but was not able to reproduce.

It only happened once.
