### ISSUE TITLE
Programmable snippets

### ISSUE THREAD

**Issue by ZehCnaS34** [atom/atom#5636]
Just wondering if there is any way to make programmable snippets like in yasnippets for emacs.

Kinda like:
```javascript
var BrowserWindow = require('browser-window');
```

In this example, when typing `BrowserWindow` the text inside the require statement is converted from camel case `browser-window`

This would be awesome.

Anyway I could help?

**Comment by thomasjo** [comment]
Should be supported since Atom's snippets is based on TextMate's snippets. I haven't got time to verify, but check out the [relevant TextMate documentation regarding snippet transformations](http://manual.macromates.com/en/snippets#transformations).

**Comment by lee-dohm** [comment]
Yeah, I don't think the snippets mechanism in Atom is that advanced yet. In any case, this probably belongs on the [snippets package](https://github.com/atom/snippets). Would you mind moving it there @ZehCnaS34?

**Comment by ZehCnaS34** [comment]
No problem
