### ISSUE TITLE
Combining One UI Theme with Solarized Syntax Theme results in coloring Atom UI

### ISSUE THREAD

**Issue by krtek** [atom/atom#5637]
Selecting any of the **One** UI Themes together with **Solarized** syntax highlighting results in weird colored Atom UI:

![screen shot 2015-02-19 at 15 49 19](https://cloud.githubusercontent.com/assets/422139/6268718/2e331b68-b84f-11e4-841d-d9573a7b487b.png)

Other combinations looks normal: 
![screen shot 2015-02-19 at 15 56 23](https://cloud.githubusercontent.com/assets/422139/6268854/eca2ffaa-b84f-11e4-8d60-8adf1334fe62.png)

Atom version: 0.181.0@Mac OS X

**Comment by postcasio** [comment]
The One UI themes are designed to adapt to your current syntax theme. From the [README](https://github.com/atom/one-light-ui)...

> *Why do the colors change when I switch Syntax themes.* This UI theme uses the same background color as the choosen Syntax theme. In case that Syntax theme has a dark background color, it only uses its hue, but otherwise stays light. This lets you use light-dark combos.

**Comment by krtek** [comment]
Ooops. Sorry, I didn't realized that. Closing.
