### ISSUE TITLE
Module Version Mismatch Error At Startup

### ISSUE THREAD

**Issue by ibnesayeed** [atom/atom#5639]
On my computer, Atom is failing at startup and throwing errors as shown below. As a result I am unable to use it for last couple of weeks.

OS: Ubuntu 14.10
Atom: 0.181.0
Node: 0.11.15
NPM: 2.5.1

```
index.js:65 Error: Module version mismatch. Expected 17, got 41.
    at Error (native)
    at Object.module.(anonymous function) [as .node] (/opt/atom/resources/atom/common/lib/asar.js:422:20)
    at Module.load (module.js:363:32)
    at Function.Module._load (module.js:318:12)
    at Module.require (module.js:373:17)
    at require (module.js:392:17)
    at Object.<anonymous> (/opt/atom/resources/app/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/opt/atom/resources/app/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:468:26)
    at Object.loadFile [as .js] (/opt/atom/resources/app/src/6to5.js:138:21)index.js:65 window.onload

/opt/atom/resources/app/src/space-pen-extensions.js:64 Uncaught TypeError: Cannot read property 'dispatch' of null
```

**Comment by thomasjo** [comment]
Have you downloaded a pre-built distribution of Atom from atom.io, or are you building from source? If the latter, make sure you're using Node 0.10.x. Newer versions of Node are not officially supported, so you're likely to run into issues similar to what you've reported.

**Comment by ibnesayeed** [comment]
I am using [WebUpd8 PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/atom) to install and update my Atom. Which means I am not building it from source.

**Comment by thomasjo** [comment]
I guess they are building using an unsupported version of Node. In the past this usually didn't lead to issues like this, but recent changes in atom-shell (IIRC) now means it's important that Atom is built using Node 0.10.x. Instead of using WebUpd8 bits, [download the latest official .deb release](https://github.com/atom/atom/releases/latest).

**Comment by ibnesayeed** [comment]
I have purged my installation and installed from the released deb file. It is working fine now. Thanks for the help.

Is there any plan to have an official Atom PPA? It is very convenient to update Atom along with every other package on the system suing the repository instead of downloading deb file and installing manually every time a new version is released.

**Comment by lee-dohm** [comment]
#5628 has made Atom buildable by Node v0.12.x and IO.js v1.x on `master` now and should be available in the next release.

#2956 is tracking the desire to have an official PPA for v1.0. You can subscribe to that for updates.

**Comment by ibnesayeed** [comment]
Thanks for the pointers @lee-dohm.

**Comment by kevinsawicki** [comment]
Closing this out, this seems to be an issue with how the third-party PPA was built and/or needing to rebuild packages for different v8 headers when upgrading electron releases.

**Comment by domenkozar** [comment]
@ibnesayeed did you ever find a way to fix this?

**Comment by ibnesayeed** [comment]
@domenkozar I downloaded the the deb file from the the official Atom site and installed that manually which worked for me.
