### ISSUE TITLE
Copy paste of text aligned with spaces (e.g. asterisk-aligned PHPDoc) sometimes loses the alignment with soft tabs off

### ISSUE THREAD

**Issue by driskell** [atom/atom#5642]
Easiest to reproduce with PHP grammar, and the "doc_f" snippet. Soft tabs needs to be off (it's fine with it on.)

Create a new PHP file and use doc_f snippet. You'll get a PHPDoc block which uses the recommended formatting - the asterisks are aligned vertically using an additional leading space.

When copy and pasting... this space is lost if you paste on an already indented line. ANIGIF below shows the reproduction, and shows that on an empty line it pastes OK, but on pasting with indentation the spaces aligning the asterisks are lost.

![example](https://cloud.githubusercontent.com/assets/939815/6273202/41e81dbe-b865-11e4-8ea5-a5354bdbb50c.gif)

In case someone thinks aligning the asterisks is bad practice - it's actually customary for PHPDoc. See first glossary entry on the PHPDoc website:
http://www.phpdoc.org/docs/latest/glossary.html

**Edit: Removed the root cause bit - I've put it in the PR**

Thanks!

**Comment by driskell** [comment]
Any updates? Appreciate things are prioritised but I've not really heard anything in a while.

**Comment by nathansobo** [comment]
Taking a look at this now.

**Comment by nathansobo** [comment]
Hate to say this after all this time, but I'm having trouble reproducing this. @driskell is this still happening? Am I doing something wrong in the animation below?

![php-test](https://cloud.githubusercontent.com/assets/1789/8414982/440ff28a-1e61-11e5-96a2-d4db55a68152.gif)

**Comment by nathansobo** [comment]
Nevermind, I see what I was doing wrong now. Going to delete the above comment to reduce noise.

**Comment by nathansobo** [comment]
Closed via #7563
