### ISSUE TITLE
Can not start atom on Windows 7

### ISSUE THREAD

**Issue by miguelchico** [atom/atom#5646]
I just donwloaded atom and installed and an exception appears:

![captura](https://cloud.githubusercontent.com/assets/6106661/6283129/14d8f926-b8e0-11e4-8bda-ece442bdcaf9.PNG)

I have the same problem in safe mode

**Comment by kevinsawicki** [comment]
Can you include the text if you expand the arrow on the `Error` line?

**Comment by miguelchico** [comment]
I updated to version 0.182

**Comment by miguelchico** [comment]
Any news about this error?
Maybe any suggestion?

**Comment by batjko** [comment]
Something wrong with the theme that was used?

Does this still happen after uninstalling that older version and installing the latest one?

**Comment by miguelchico** [comment]
I still have exactly the same error... I don´t know what can I do

**Comment by batjko** [comment]
@miguelchico Did you completely uninstall (including the `C:\Users\[username]\.atom` folder) and re-install?

It's a bit of a sledge hammer, but since the issue was still present in safe mode, this should certainly work on any normal Windows 7 machine, unless there's something wrong with it in general.

**Comment by KamranMackey** [comment]
@miguelchico Try updating to build 187, as 182 is quite out of date.

**Comment by miguelchico** [comment]
@batjko Yes, I removed also the .atom folder and reinstalled and the problem still there. Maybe I installed som nmp packages before that are incompatible? How can I check it?

@KamranMackey I updated to build 188 and the problem is the same

**Comment by miguelchico** [comment]
I try the 188 version with a different user in the same pc and it works.. so I should have a problem with the user... but I do not what.

How can I find it?

**Comment by Zireael07** [comment]
Maybe the user doesn't have read/write privileges to AppData, although that'd be pretty weird.

**Comment by kevinsawicki** [comment]
Closing in favor of the newer https://github.com/atom/atom/issues/7774 which includes the text of the stack trace so it is easier to search for and discover.
