### ISSUE TITLE
Wrong project path shown

### ISSUE THREAD

**Issue by meventi-stephan** [atom/atom#5647]
After updating git-plus and open-last-project (versions are shown below) the wrong project path is shown (view image below). The path is shown now, where atom is installed. I can't change the folder also. This problem happens on 2 pc clients, where atom is installed.

 Image:
![atom](https://cloud.githubusercontent.com/assets/5426291/6283405/a9833862-b8e4-11e4-8eed-8373fd403429.png)

I use following packages at the moment
- emmet 2.3.3
- git-plus 4.4.8
- linter-php 0.0.11
- open-last-project 0.3.1
- project-manager 1.15.5

## Versions

* **Atom:**       0.181.0
* **Atom-Shell:** 0.21.0
* **OS:**         CZC92918LT
* **Misc**
    * apm  0.140.0
    * npm  2.5.1
    * node 0.10.35
    * python 
    * git 1.9.5.msysgit.0
    * visual studio

**Comment by 50Wliu** [comment]
Please upgrade `open-last-project` to the latest version.

**Comment by thomasjo** [comment]
This almost surely caused by a bug in either [project-manager](https://github.com/danielbrodin/atom-project-manager), [git-plus](https://github.com/akonwi/git-plus), or [open-last-project](https://github.com/danielmahon/atom-open-last-project). To double check, see if the problem goes away when launching Atom in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode).

---
@50Wliu He is using the latest version.

**Comment by steelbrain** [comment]
I am using the same version of `Open-Last-Project` and I can confirm that it's not a bug in that package.

**Comment by thomasjo** [comment]
@steelbrain Thanks for the info!

This means we've narrowed it down to either project-manager and/or git-plus being the culprit.

**Comment by meventi-stephan** [comment]
I opened atom in safe mode, but the problem still exists.

**Comment by meventi-stephan** [comment]
And i have already updated to latest version of all installed packages at the moment.

**Comment by 50Wliu** [comment]
Please try clearing your storage directory (`~./atom/storage`).

**Comment by meventi-stephan** [comment]
I cleaned my storage directory and started atom. But the bug still exists.

**Comment by maxbrunsfeld** [comment]
@meventi-stephan does this bug still occur if you clear your storage directory and then immediately open Atom with `atom --safe`?

**Comment by meventi-stephan** [comment]
@maxbrunsfeld: If i clear my storage directory and open atom with ```atom --safe``` it works normally again. And i can open for example another folder.

**Comment by maxbrunsfeld** [comment]
@meventi-stephan Ok that's good. If you're interested in helping further to track this down, it'd be great to get more facts about exactly *which* package (`open-last-project`, `project-manager`, etc) or combination of packages caused this, as a number of people have reported similar issues.

In any case, sorry for the trouble. We had to make a change to how we deal with project paths internally, but no public API should have been affected, so I'm curious exactly what happened with these packages.

**Comment by meventi-stephan** [comment]
@maxbrunsfeld: No problem. In my initial bug description i mentioned that after updating git-plus and open-last-project the wrong project path is shown (update time was 18/19 February 2015). I hope this can help you.

**Comment by meventi-stephan** [comment]
@maxbrunsfeld: Another info for you. A colleague uses Atom IDE with an Apple Laptop, but he hasn't got this problem at the moment. But he was wondering, why my Atom IDE versions on Windows are now 0.180 and 0.181 (i have two Atom IDE installations) and his Atom IDE version is still 0.179.

**Comment by maxbrunsfeld** [comment]
The Mac version should auto-update just like the windows one. You can force Atom to check for an update from the `Atom` menu.

**Comment by meventi-stephan** [comment]
@maxbrunsfeld: Now it is better, but the problem isn't still solved. If i open Atom 0.182 i see Atom IDE, which is looking like the image in the initial description. If i'm opening a folder, two projects (not one!!!) are now shown (see image below). Once the folder, where atom is installed (marked with 1 in image) and otherwise the folder is shown now, which I have openend (marked with 2 in image). If i close Atom IDE now and open it again, only the folder, where atom is installed, is shown again.

![atom](https://cloud.githubusercontent.com/assets/5426291/6318105/c19f5c64-ba7e-11e4-90a2-abf9991d18af.png)

**Comment by 50Wliu** [comment]
@meventi-stephan I believe the bug you are now describing is being partly tracked in #4653, except usually the install folder goes away when you restart Atom.
