### ISSUE TITLE
Can't create a new file

### ISSUE THREAD

**Issue by TouPye** [atom/atom#5648]
It seems I can't create a new file on the current Atom window, neither using `FIle > New file` nor `Ctrl+N`

I updated form 0.180.0 to 0.181.0 this morning. No other update nor package install.
After the update, I noticed  a problem with y tree-view (#5617), and re-opened my usual folder.

The only way I found to create a new file is to *open a folder* (wich creates a new Atom window according to #5615) **then** I can *create a new file*.

**Atom Version**: 0.181.0
**System**: Microsoft Windows 8.1
**User installed packages** (in case it may be a collision ?)

```coffee
autocomplete-plus, v2.1.6
color-picker, v1.4.4
column-select, v0.1.0
emmet, v2.3.3
file-icons, v1.4.11
flatland-dark-ui, v0.2.3
linter, v0.11.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-php, v0.0.11
open-last-project, v0.3.1
tomorrow-night-eighties, v0.4.0

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode? (ie. `atom --safe`)

**Comment by TouPye** [comment]
Nice point here @mnquintana : 
- when I launch Atom from the console (with or without safe mode) I can create a new file.
- when I launch Atom from my desktop shortcut, I can't create a new file.

**Comment by maxbrunsfeld** [comment]
@TouPye can you try removing the contents of your `$ATOM_HOME/storage` directory and restarting Atom?  Also, we've noticed problems with the `open-last-project` package after 0.180.0. An issue has been created for this: https://github.com/danielmahon/atom-open-last-project/issues/25.

**Comment by TouPye** [comment]
@maxbrunsfeld emptying `/storage` didn't change anything, but disabling `open-last-project` seems to fix it.

I guess the problem comes from `open-last-project` then. I'll follow the issue you linked.

**Comment by maxbrunsfeld** [comment]
Alright thanks for the report @TouPye.

**Comment by ryancha1205** [comment]
I got the same problem, and somehow I solved .. in weird way
go to Atom->Keymap and , I made my configuration into commitment ..
I mean command+/
and It solved the problem @pistou
