### ISSUE TITLE
Tree View "Hide Ignored Names" not working.

### ISSUE THREAD

**Issue by lexicalunit** [atom/atom#5651]
![nothidden](https://cloud.githubusercontent.com/assets/1903876/6301517/6ed4b86e-b8ec-11e4-86fe-19111dd53b81.png)

```
$ apm list | grep tree
├── tree-view@0.157.0
```

```
$ atom --version
0.180.0
```

```
$ cat ~/.gitignore_global | grep pyc
*.pyc
```

And from within the repository which is being displayed in the screen shot:

```
$ cat .gitignore | grep pyc
*.pyc
```

**Comment by lexicalunit** [comment]
Actually, let me open this ticket in the atom/tree-view project.

**Comment by steelbrain** [comment]
Finally someone who moved their issue themselves, Yayyyy! :smile:

**Comment by lexicalunit** [comment]
I feel bad for even having opened the ticket in the wrong project >.<
