### ISSUE TITLE
Latest release (0.182.0) includes old .nupkg downloads

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#5652]
![image](https://cloud.githubusercontent.com/assets/823545/6306554/68494abc-b902-11e4-8d03-6d88ea593783.png)

Not sure what happened with this build, but it's showing 0.181.0 `.nupkg` files in addition to the latest release's files.

**Comment by kevinsawicki** [comment]
Thanks so much for reporting this, I think the CI machines failed to delete these, I've removed them manually.
