### ISSUE TITLE
FSPathMakeRef(/Applications/Atom.app) failed with error -43.

### ISSUE THREAD

**Issue by calekennedy** [atom/atom#5653]
I suddenly started getting this error -- after using atom without issue for over a year.

I just completely uninstalled and reinstalled atom following these steps 
Delete the app from the Applications folder
rm -rf ~/.atom
rm /usr/local/bin/atom
rm /usr/local/bin/apm
rm ~/Library/Preferences/com.github.atom.plist
rm ~/Library/Application Support/com.github.atom.ShipIt
rm -rf ~/Library/Application Support/Atom/

Then I got the installer from atom.io, copied in into my Applications directory,  reinstalled the shell commands, and still got the follow error when running "atom" in the terminal.

I finally solved this issue by moving the Atom program from my 

~/Users/calekennedy/Applications

to 

~/Applications

I wanted to add this issue in case someone else encounters it in the future.

**Comment by matti** [comment]
same here. giving up with homebrew cask installation, eg: /usr/local/bin/atom -> /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/atom.sh)

**Comment by 50Wliu** [comment]
Could you please see if following some of the instructions in #5222 or #5380 help?

**Comment by calekennedy** [comment]
This problem occurred when migrating from Mavericks to Yosemite.

I had to completely uninstall everything related to atom, delete all of the files and folders, and then reinstall. 

I found a guide online at the time, but I cannot recall where it was.

**Comment by izuzak** [comment]
Closing this since we haven't seen any other reports recently. One of the two reports here is a problem that's covered by other issues (seems like a problem with homebrew cask installation) and the original report is no longer a problem so not something we can debug now.

If this happens again -- would be great if things are left as they are so that we can debug. Or at least provide more information, such as what was discussed in https://github.com/atom/atom/issues/5380#issuecomment-72731099.

**Comment by guokr321** [comment]
guokedeMacBook-Air:~ guoke$ subl
FSPathMakeRef(/Applications/Sublime Text 2.app) failed with error -43.
guokedeMacBook-Air:~ guoke$ which subl
guokedeMacBook-Air:~ guoke$ open /Applications/Sublime\ Text.app/Contents/
Info.plist      Resources/      _CodeSignature/ 
MacOS/          SharedSupport/  
guokedeMacBook-Air:~ guoke$ open /Applications/Sublime\ Text.app/Contents/
Info.plist      Resources/      _CodeSignature/ 
MacOS/          SharedSupport/  
guokedeMacBook-Air:~ guoke$ open /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl 
guokedeMacBook-Air:~ guoke$ 

I have this trouble, too. Before,  I have install subl 2, and recently, I replace it with the version 3. I make the soft links again, but the trouble comes and then I remove the soft links, and type which subl , really I deleted it. But when type subl , the FSPathMakeRef(/Applications/Sublime Text 2.app) failed with error -43 came again, I do not know if this is a bug of the file system of mac. My os is 10.11.5 (15F34)

**Comment by guokr321** [comment]
I think I partially fix it. For that the soft link such as subl is no longer can be used. I turn to another name such as sublime, and it works well
