### ISSUE TITLE
Atom Versioning Scheme will fall over in ~70 releases on Windows

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom#5654]
On Windows, every block of the version number (i.e. X.Y.A.B) is limited to the range [0-255]. Currently this number is a monotonically increasing number on the minor version on Windows, which will eventually fail once we hit 0.256.0. Plenty of time to fix this, but that's precisely why I wanted to bring it up *now* and not *later* :)

**Comment by kevinsawicki** [comment]
Thanks for the heads up :+1:

**Comment by thedaniel** [comment]
Windows is HILARIOUS.

**Comment by paulcbetts** [comment]
I think that shit goes all the way back to Windows 3.1 at least, probably earlier. Eight bits ought to be enough for anybody!

**Comment by kevinsawicki** [comment]
1.0 happened, closing this out.
