### ISSUE TITLE
Atom 0.180+ Detected as Malware via Comodo

### ISSUE THREAD

**Issue by mystickphoenix** [atom/atom#5655]
On install of the .deb package (from 0.180.0 on), Comodo determines that the following file is malware under the **Heur.Deual.Extensions@@4294967295** name.

    /tmp/temp-lintian-lab-EZeXThRA8O/pool/a/atom/atom_0.182.0_amd64_binary/unpacked/usr/share/atom/resources/app/node_modules/6to5-core/node_modules/core-js/src/core.log.js

**Comment by sebmck** [comment]
It's a false positive, see babel/babel#801.

**Comment by mystickphoenix** [comment]
Disabling Comodo temporarily allows install of Atom package.  Wish there was a better fix considering the pace of Atom releases...
