### ISSUE TITLE
File autoload and append a newline when disabling whitespace.ensureSingleTrailingNewline

### ISSUE THREAD

**Issue by fundon** [atom/atom#5656]
The `whitespace.ensureSingleTrailingNewline` was disabled.
But it still appends a newline.

My steps:

0. open `package.json` in Atom
0. exec command `$ npm i xx@latest --save` in Terminal

**Comment by 50Wliu** [comment]
Can you reproduce this using `atom --safe`?
What Atom version are you using?

**Comment by fundon** [comment]
The latest version v0.182.0.
And using `atom --safe`, it's also happend.

**Comment by 50Wliu** [comment]
This issue was moved to atom/whitespace#58
