### ISSUE TITLE
Different character widths in OS X and Linux

### ISSUE THREAD

**Issue by jeremy-engel** [atom/atom#5657]
Using Atom 0.182.0 in OS X and Mint 16 produces different results for the same file. In the screenshots below, the top figure is on the linux version and the bottom is in OS X. The width of the non-breaking hyphen (‑) differs, as you can see from the alignment towards the end of that row.

![screenshot from 2015-02-20 12 27 28](https://cloud.githubusercontent.com/assets/4955347/6308803/3b65c382-b8fc-11e4-9a95-e0386dae09a7.png)

![screen shot 2015-02-20 at 12 27 19 pmaaaaa](https://cloud.githubusercontent.com/assets/4955347/6308909/1e97ce48-b8fd-11e4-9e70-f61303a3ec65.png)

The font for both of these is Source Code Pro. The bottom figure is clearly the desired behavior.

I am pretty sure the linux behavior, where this character is more narrow than all others, was present in the OS X version until recently, but I just noticed that it changed today.

**Comment by lee-dohm** [comment]
Can you post the test file here or as a Gist?

**Comment by grizzilus** [comment]
This isn't the same file but it a nice simple example to make it clear.

```
‑|
 |
```

First line is non-breaking hyphen and a pipe. The second line is a space and a pipe. The pipes are just there so show the placement of the second column differs from the first line to the second (on linux).

**Comment by 50Wliu** [comment]
I can confirm on Atom 0.181.0, Ubuntu 14.10.

**Comment by grizzilus** [comment]
Just an update to this. In 0.189.0 (still on Mint 16), the non-breaking hyphen no longer renders. (But the width of the replacement character is correct, not that it is very helpful.) Here is a screenshot of the text posted above.
![screenshot from 2015-04-03 10 41 20](https://cloud.githubusercontent.com/assets/4955347/6986010/1b132ef4-d9ee-11e4-8c26-8932ba762720.png)


OS X is still fine; I can check Windows in the next 24 hours.

**Comment by grizzilus** [comment]
I assume this is something with chromium then since the version changed to 41 in 0.189 (I think).
