### ISSUE TITLE
Error: Could not locate the bindings file for pickle.node

### ISSUE THREAD

**Issue by mMerlin** [atom/atom#5661]
Environment 32 bit Fedora 21 3.18.7-200.fc21.i686
running as a guest VM in VirtualBox on Windows 7
atom repository tag v0.182.0

both .script/build and .script/grunt install finish with the "Done, without errors" message, but before that report:

```
Loading "index.js" tasks...ERROR
>> Error: Could not locate the bindings file. Tried:
>>  → {atom repo}/{pickle path}/build/pickle.node
>>  → {atom repo}/{pickle path}/build/Debug/pickle.node
>>  → {atom repo}/{pickle path}/build/Release/pickle.node
>>  → {atom repo}/{pickle path}/out/Debug/pickle.node
>>  → {atom repo}/{pickle path}/Debug/pickle.node
>>  → {atom repo}/{pickle path}/out/Release/pickle.node
>>  → {atom repo}/{pickle path}/Release/pickle.node
>>  → {atom repo}/{pickle path}/build/default/pickle.node
>>  → {atom repo}/{pickle path}/compiled/0.10.36/linux/ia32/pickle.node
```

where {pickle path} is build/node_modules/grunt-atom-shell-installer/node_modules/asar/node_modules/chromium-pickle

{pickle path} exists, but none of the referenced sub folders do.  pickle.node does not exist anywhere in the repo tree.  {pickle path} does contain a binding.gyp and node_modules/bindings/bindings.js.  If those are related.  Is a file missing someplace?  Or an entry to tell atom’s build to build this too?

See http://mmerlin.github.io/installation/2015/02/04/atom-install/ for details on how the initial environment setup and build was done.  This was just

```
git pull
git checkout v0.182.0
./script/build
```

**Comment by mnquintana** [comment]
I got this error building on OS X Yosemite too.

**OS:** OS X 10.10.2
**Atom:** master@3a819ea331949dfee89e281cd0b95ec89a7eca83
**Node:** v0.12.0
**npm:** v2.5.1

**Comment by izuzak** [comment]
@mnquintana Does this consistently happen for you? Can you paste the exact error you get? I've never seen that happen on OSX 10.10.2 myself.

```
$ npm -v
2.7.1

$ node -v
v0.10.21
```

**Comment by yashiro1899** [comment]
remove build/node_modules/grunt-atom-shell-installer/node_modules/asar/node_modules/chromium-pickle
and reinstall chromium-pickle

**Comment by Zolmeister** [comment]
Confirmed: @yashiro1899 's workaround. (remove build/node_modules)

**Comment by borisovg** [comment]
I also encountered this issue on Debian (Sid). The above workaround also resolved it for me.

````
pushd build/node_modules/grunt-atom-shell-installer/node_modules/asar
rm -r node_modules/chromium-pickle/
npm install
popd
````
