### ISSUE TITLE
Do we really need 3 dot releases in three days?

### ISSUE THREAD

**Issue by composer22** [atom/atom#5666]
How about a little temperament on the release cycle so we can actually work with the tool @ stability,  acceptance test it out, digest functional changes and the like, instead of continually having to sync builds?

End of Comment

**Comment by 50Wliu** [comment]
Those new releases were to improve stability and dramatically increase performance in certain areas.  In addition, unless you're on Linux, those new versions shouldn't be interrupting your workflow.

**Comment by composer22** [comment]
The point: Its sloppy development and deployment.  All the "improved stability and dramatically increased performance" should have been included in the original *official* build.  

If you are unsure about the stability or performance of a public release, release it with an alpha or beta designator so we can bypass our acceptance process and wait for something more rock solid.

**Comment by 50Wliu** [comment]
Atom *is* currently in alpha right now, hence `0.x.y`.
If this release cycle continues when it hits v1, then there's a problem.  But alpha/beta users should be prepared to be hit with many new versions as the product stabilizes.

**Comment by composer22** [comment]
I'm not using it as an alpha, but it's a fair-enough point and response.

Closing ticket.

**Comment by mark-hahn** [comment]
I don't understand what alpha and beta mean in the context of a programming
utility.  You are either using it or not.  It's not like it gets installed
on a server.

**Comment by composer22** [comment]
It's software, period, and by that token it needs a solid revision process - regardless of end use or platform. Plenty of utils and tools follow this dictum.

**Comment by paulcbetts** [comment]
@composer22 We intentionally designed both the Windows and OS X updater to be as silent and transparent to the user as possible - we don't *want* updates to be a Big Event that takes time out of your day. 

We want events to be quiet and never interrupt your work, like how a website updates and you never need to know about it. Because of that, we can ship far more updates than Traditional Software(tm) does.

**Comment by composer22** [comment]
""we don't want updates to be a Big Event that takes time out of your day."

Ahh, but thats the big post-modern lie here because you are by nature announcing releases and doing automatic updates down to the users platform not *your* own web platform. This is also typical of mobile apps as well, where users cannot keep up with the latest changes and become frustrated with recurrent new versions tying them up in downloads all the time.  And imagine if OSX or XCode was updated daily or what kind of hell that would be, or any other tool.  Yeah like Flash!  

To sum, this isn't an online application where continuous deployment (CD) is transparent to the end user because you are updating your own instances without client interaction.  Here you have a platform that the user is hosting and you are crucherinzing them with downloads.  We do notice.

Nay, we must put a stop to this misaligned transference of web development methodologies to customer based platforms.

**Comment by paulcbetts** [comment]
Thanks for your thoughts, but this wasn't really a point up for debate. Thanks though!

**Comment by bolinfest** [comment]
As someone who upstreams changes to Atom, I'm a big fan of the fast release
cycle.

**Comment by philipgiuliani** [comment]
I also like the current release cycle, but i always want to try everything out as fast as possible ;)

**Comment by composer22** [comment]
I don't mind the autoupdate feature, however, I would like the ability to selective choose which releases are automatically downloaded.  I would recommend an option for stable vs unstable release in the settings page and mark releases as such.  This is not an alpha release.  Its a BETA.
