### ISSUE TITLE
after update install directory is opened

### ISSUE THREAD

**Issue by russlescai** [atom/atom#5668]
Minor issue, but happened a few times, so I thought I would raise it.

Whenever an update is downloaded, the menu item "Install Update and Restart" appears.

When I do this, it reopens, with the treeview showing the newly installed application files (e.g. for windows:
C:\Users\AppData\Local\atom\app-0.181.0
After the restart, I would prefer it either reopen the treeview I had previously opened, or open none at all.

I raised this in discuss, and apparently this issue occurred and was fixed in a previous version. it looks like it has regressed.

https://github.com/atom/atom/issues/4653

**Comment by 50Wliu** [comment]
Welp, I just re-opened my old ticket as well :P.

**Comment by 50Wliu** [comment]
Going to close this and keep discussion over at #4653.

**Comment by russlescai** [comment]
sure thing :)
