### ISSUE TITLE
Win 8.1 atom 0.179.0 Check for Update missing 

### ISSUE THREAD

**Issue by csaket** [atom/atom#5672]
I am running atom 0.179.0 installed via choclatey on Win 8.1 64bit.
I am not getting any "check for update" option in the help menu.
Running atom -f does not give any errors.

C:\>atom -f
App load time: 521ms
[3164:0221/181955:INFO:renderer_main.cc(211)] Renderer process started
[192:0221/182000:INFO:CONSOLE(79)] "Window load time: 3744ms", source: file:///C
:/Users/asiddiqui/AppData/Local/atom/app-0.179.0/resources/app/static/index.js (
79)

Short of uninstalling and reinstalling, is there any other option?

Thanks

![image](https://cloud.githubusercontent.com/assets/1216526/6316698/514a5234-b9f7-11e4-9741-e7555fc1ce8e.png)

**Comment by mark-hahn** [comment]
Switch to the default installer.  You won't regret it.

**Comment by 50Wliu** [comment]
To add onto what @mark-hahn said:  Uninstalling and replacing your Chocolatey install with the new Squirrel installer is very worth it ;).  Atom cannot check for new versions under Chocolatey, only under the new installer.
Find out how [here](http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html).
