### ISSUE TITLE
Atom and packages aren't upgrading

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#5673]
I don't know if it started on an Atom upgrade but  my Atom version is stuck at 0.177.0 and `apm upgrade` always says zero.  This happened several days ago (just noticed).

windows 8.1
Atom 177
apm  0.140.0
npm  2.5.1
node 0.10.35
python 2.7.9
git 1.9.5.msysgit.0
visual studio 2013

**Comment by mark-hahn** [comment]
BTW, I erased what I could in `~/.atom` with no luck.

**Comment by mark-hahn** [comment]
BTW again, I recently moved all my packages to an external folder and put symlinks in the actual packages folder.  There are now only symlinks there.  Could this have something to do with it?

**Comment by mark-hahn** [comment]
Update: Sometime since the original post atom has upgraded from 177 to 182.  However `apm upgrade` is still broken.  It always returns zero when there are known packages to upgrade.

**Comment by lee-dohm** [comment]
Which packages are you wanting to upgrade? I once found an issue with a package that had a broken engine version specification and it was causing it to be unable to be upgraded.

**Comment by mark-hahn** [comment]
It would be quite hard for me to go through the 50 or so packages to find which need upgrading.  Would it be enough to say your `bug-report` is at 0.6.1 and atom.io says it is 0.6.2 and I just checked apm upgrade and got zero?

**Comment by lee-dohm** [comment]
What does `apm outdated --verbose bug-report` say?

**Comment by mark-hahn** [comment]
Package Updates Available (0)

**Comment by lee-dohm** [comment]
It doesn't have a bunch of spew before that about requests and responses?

**Comment by mark-hahn** [comment]
Nope.

**Comment by mark-hahn** [comment]
I guess I'll try a fresh install.

**Comment by izuzak** [comment]
As far as I can tell, packages which are symbolic links are intentionally skipped in `apm upgrade`:

https://github.com/atom/apm/blob/b1523b22d7422b5be637242f38e3acc47c74732f/src/upgrade.coffee#L59

> I recently moved all my packages to an external folder and put symlinks in the actual packages folder

Are those packages you are _using_ or packages you are _developing_? Here's my understanding of the recommended workflow for those two. 

If you are just using packages - you should be installing them with `apm install` or via the settings view and not moving them outside of `~/.atom/packages` after they've been installed. After that, you can upgrade them via `apm upgrade` and settings view.

If you are developing packages, then you should clone them to a folder outside of `~/.atom`, use `apm link` and `apm install` to set them up, and you shouldn't be updating them with `apm upgrade` or via the settings view -- you should update them by pulling the new version tag from a remote (e.g. GitHub) into your local clone and using `git checkout` to switch to that new version.

**Comment by mark-hahn** [comment]
In another thread dealing with folder names not matching the package.json
name I was told that it must be installed outside and linked to.  This may
be specific to installing directly from a repo.

https://github.com/atom/atom/issues/5608

I may be an idiot but this is all confusing.  I'm guessing these are the
rules ...

- If developing a package it should be outside with `npm link` used.
- If installed with `atom install` it should stay inside in order for `atom
upgrade` to work
- If a package is downloaded from a repo
  - Download to inside
  - Rename the folder to match package.json name

Where do I put projects that I'm going to do a PR?  If after a PR is
accepted then I need to delete that project and do a normal install?

Is this all correct?  These seems like hidden magic rules.  Surely it can
be simplified.

I will now go through all my packages and move ones I want upgraded back
inside.
