### ISSUE TITLE
'core:copy' does not work when it is assigned to another key

### ISSUE THREAD

**Issue by bouzuya** [atom/atom#5674]
I want to copy text and keep it in buffer. But 'core:copy' delete text from buffer.

Atom: 0.182.0
OS: Ubuntu 14.04
1. Change keymap

```
# keymap.cson
'atom-workspace':
  'y': 'core:copy'
```
1. Run Atom with safe option.

```
$ atom --safe
```
1. Input "foobar" and select all.

buffer:

```
foobar
```
1. Press "y" key (I want to copy "foobar" and **keep text in buffer**) .

buffer: 

```
y
```

Note: `ctrl-*` key mapping works well.

```
# keymap.cson
'atom-workspace':
  'ctrl-y': 'core:copy' # work!
```

**Comment by lee-dohm** [comment]
The reason mapping the <kbd>Y</kbd> key to `core:copy` doesn't work is because of specificity:

https://atom.io/docs/latest/advanced/keymaps#specificity-and-cascade-order

You're setting `core:copy` to <kbd>Y</kbd> on `atom-workspace`. But I'm pretty certain that `atom-text-editor` has the native key bindings set. Since, when you're in a text editor view, `atom-text-editor` is more specific than `atom-workspace` the native key bindings win out over your key mapping. If you use the following in your `keymap.cson` it will work:

```coffee
'atom-text-editor':
  'y': 'core:copy'
```

**Comment by bouzuya** [comment]
@lee-dohm 

I changed `keymap.cson`, but it does not work.

```
'atom-text-editor':
  'y': 'core:copy'
```

See "Key Binding Resolver" screenshot.

![2015-02-22-atom](https://cloud.githubusercontent.com/assets/1221346/6317812/a06f8132-baaf-11e4-955a-ccb4f8d77200.png)

**Comment by bouzuya** [comment]
It does not occur to be using the debugger... :cry:
I think the timing of dispatchEvent is causing .

I give it up and add `setTimeout` to `atom.commands.add ...` in `init.coffee`.

**Comment by lee-dohm** [comment]
That screenshot is showing that `core:copy` *is* being called. Did you have anything selected?

![goofy-keybinding](https://cloud.githubusercontent.com/assets/1038121/6319829/4743e6f4-ba80-11e4-8d06-3c79eaa120db.gif)

**Comment by bouzuya** [comment]
Yes, I did. The selected text was replaced by "y". 

![20150223_061518](https://cloud.githubusercontent.com/assets/1221346/6320530/90a3d950-bb23-11e4-87a0-be80fec1aeab.gif)

**Comment by bouzuya** [comment]
@lee-dohm Could you re-open this issue? I think this is a bug to be corrected.

**Comment by 50Wliu** [comment]
@bouzuya, I can't reproduce either on Atom 0.182.0 on Windows.  I'll try later on Ubuntu 14.10.

**Comment by bouzuya** [comment]
fmm... Maybe I will not reproduce in Mac OS X. I'll try today.

**Comment by lee-dohm** [comment]
Looks like it may be OS-specific. I'll re-open and tag with Linux.

**Comment by bouzuya** [comment]
I can't reproduce on Mac OS X 10.9.5. :cry:

**Comment by steelbrain** [comment]
Guys, a side question :stuck_out_tongue: How do you generate all those fancy gifs?

**Comment by lee-dohm** [comment]
@steelbrain There's a [FAQ on Discuss](https://discuss.atom.io/t/draft-faq-lets-improve-it-together/14981) that covers this, I use the tool recommended there, [LICEcap](http://www.cockos.com/licecap).

**Comment by 50Wliu** [comment]
I can reproduce on Ubuntu 14.10.  Pressing <kbd>y</kbd> to copy will copy the selected text but also delete said text and replace it with a `y`.
