### ISSUE TITLE
Uncaught Error: getaddrinfo ENOTFOUND circleci.com circleci.com:443

### ISSUE THREAD

**Issue by aridlehoover** [atom/atom#5676]
Steps to reproduce:

1. Launch Atom
2. Put computer to sleep
3. Wake computer and sign in

Note: I uninstalled the circle ci extension and am still receiving this error.

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: getaddrinfo ENOTFOUND circleci.com circleci.com:443

```
At events.js:94

Error: getaddrinfo ENOTFOUND circleci.com circleci.com:443
  at errnoException (dns.js:46:10)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:96:26)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autosave"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/Users/Alan/dev"
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-handlebars, v0.4.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.6
autocomplete-snippets, v1.0.1
language-rspec, v0.3.0
rspec-snippets, v0.4.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
> Note: I uninstalled the circle ci extension and am still receiving this error.

@aridlehoover This definitely seems to be related to the circle ci extension. I'm guessing that it didn't clean up after itself correctly, and you just need to restart Atom to make it go away. Let us know if you can reproduce this in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode), though!
