### ISSUE TITLE
Uncaught Error: ENOENT, open '/home/ipdfh/2_semester/AAV/Memory.md'

### ISSUE THREAD

**Issue by hdmi** [atom/atom#5680]
<h3>Explanation

This error always pops up when I try to convert some Markdown file to .pdf
It might be a bug or something because I have tried the conversion y two different operate systems and always happens the same. 

In both OS a new "user" folder is created out of the blue. As you can appreciate in the ENOENT appears a user ipdfh which is not mine.
* In linux the created path for the output is: '/home/ipdfh/....
* In Windows (with a totally different user from linux): C:/Users/ipdfh/....
<hr>
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.181.0
**System**: linux 3.13.0-45-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open '/home/ipdfh/2_semester/AAV/Memory.md'

```
At fs.js:82

Error: ENOENT, open '/home/ipdfh/2_semester/AAV/Memory.md'
  at Error (native)

```

### Commands

```
     -0:45.9 window:toggle-dev-tools (atom-text-editor.editor)
     -0:40.4 command-palette:toggle (atom-text-editor.editor)
     -0:24.8 core:confirm (atom-text-editor.editor.mini)
     -0:24.8 markdown-pdf:convert (atom-text-editor.editor)
  2x -0:14.9 core:backspace (atom-workspace.workspace.scrollbars-visible-always.theme-fizzy.theme-one-light-ui)
     -0:07.2 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-fizzy.theme-one-light-ui)
  2x -0:02.1 core:backspace (atom-text-editor.editor.mini)
     -0:00.9 core:confirm (atom-text-editor.editor.mini)
     -0:00.9 markdown-pdf:convert (atom-workspace.workspace.scrollbars-visible-always.theme-fizzy.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "fizzy"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 19
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.2.0
color-picker, v1.4.4
file-icons, v1.4.11
fizzy, v0.15.0
linter, v0.11.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-php, v0.0.11
markdown-format, v2.5.0
markdown-pdf, v1.3.3
pdf-view, v0.17.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This issue was moved to travs/markdown-pdf#43
