### ISSUE TITLE
Atom is so Heavy, blue screen when install it. 

### ISSUE THREAD

**Issue by semplon** [atom/atom#5683]
I'm using windows 8.1 and install Atom the latest version. Just open it and try to edit my code. But the application load is so heavy. There are some delays when accessing my files and even moving my pointers :( so sad. Notepad++ is still fast to load. And when installing Atom, it's consume more memory and make my laptop blue screen and need restart. 

It's a great editor, but i had to uninstall it.

**Comment by steelbrain** [comment]
Note: BSOD (Blue Screen of Death) not always appears because of low memory. It usually appears when something in windows's core crashes.

**Comment by batjko** [comment]
Agreed, Atom _is_ more resource-intensive than N++, but it certainly won't crash your system, unless something else is already very wrong with it. 

Delays can come from installed community packages (try running it without them: `atom --safe`), or from huge files which is a known limitation.

**Comment by semplon** [comment]
Okay, I'll try it again. I hope atom more more lighter.
So it can handle more more and more tabs like i always do.

**Comment by 50Wliu** [comment]
What version of Atom are you using?

**Comment by semplon** [comment]
version 0.182.0
I download it from atom.io website. 

and fyi, I'm using 64bit windows.

**Comment by ginus** [comment]
win 8.1 64 bit, works well.

**Comment by benogle** [comment]
This seems like one of the many performance issues we have. I'm going to close in favor of https://github.com/atom/atom/issues/1827 and friends

**Comment by paulcbetts** [comment]
BSODs on app launch are usually either video driver related or due to bad RAM. Check both
