### ISSUE TITLE
Uncaught Parse error in `.ftpconfig` JSON : SyntaxError: Unexpected token /

### ISSUE THREAD

**Issue by nubestra** [atom/atom#5684]
[Enter steps to reproduce below:]

1. First i created a proyect
2. Then i created a .ftpconfig file to connect via ftp with the ftp package 

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Parse error in `.ftpconfig` JSON : SyntaxError: Unexpected token /

```
At /Users/israelortiztop/.atom/packages/Remote-FTP/lib/client.js:78

undefined
```

### Commands

```
     -1:17.8 remote-ftp:create-ftp-config (atom-pane.pane.active)
  2x -0:38.1 core:paste (atom-text-editor.editor.is-focused)
  3x -0:07.1 core:save (atom-text-editor.editor.is-focused)
     -0:01.4 remote-ftp:connect (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 16
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.6.0
linter, v0.11.1

# Dev
No dev packages
```

**Comment by thedaniel** [comment]
I think that this issue belongs on the repo for the remote-FTP package: https://github.com/mgrenier/remote-ftp

**Comment by steelbrain** [comment]
@thedaniel Looking at the number of issues you guys have to route to package repositories, I think You guys should create a bot that checks the first line of the newly opened exception issues and matches `/packages/.*/` in the trace and then forwards that issue to that package's repo.
It'll make the moderation a lot easier for you guys.

**Comment by benogle** [comment]
@steelbrain in most cases it does. It checks the stack trace for the package. This one doesnt have a stack trace, and the `line` isnt parsed for package quite yet: https://github.com/atom/notifications/blob/master/lib/main.coffee#L38 

In most other cases it's from another package that we're not catching, the package is failing on some async method (like file operations) and providing no stack. 

I plan to check the commands and the line for 3rd party packages in the future, but havent gotten around to it yet.

**Comment by RobRoseKnows** [comment]
Post your .ftpconfig file. I was having the same bug until I noticed the line: `"secure": false,` was missing: `false,` which created an error when parsing the JSON file.
