### ISSUE TITLE
File tab not working

### ISSUE THREAD

**Issue by ludwighogstrom** [atom/atom#5686]
I have an issue/inconsistency with file tabs. Most files doesn't spawn a file tab (with the file name). Instead the tab of the current file stays. However, the content of the file shows.

It seems related to being able to open files with single / double click? Files that for some reason needs double click doesn't get a tab. Single click files works as expected.

Can't detect any pattern for file types. Just have normal files as *.js and *.html etc.

OS X 10.10.2
Atom 0.182.0

**Comment by postcasio** [comment]
What packages do you have installed? Does the problem occur in [safe mode](https://atom.io/docs/latest/debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by ludwighogstrom** [comment]
Ok! Works fine in safe mode (i.e. package error?). Noticed an error with linter. I guess I report the issue with them instead. Thanks for putting me in the right direction.


----
Could not resolve 'project-palette-finder' to a package path
/Users/ludwigh/.atom/packages/linter-csslint/lib/init.coffee:11 activate linter-csslint
/Users/ludwigh/.atom/packages/linter-htmlhint/lib/init.coffee:11 activate linter-htmlhint
/Users/ludwigh/.atom/packages/linter-jscs/lib/init.coffee:30 activate linter-jscs
/Users/ludwigh/.atom/packages/linter-php/lib/init.coffee:7 activate linter-php

**Comment by ludwighogstrom** [comment]
Just noticed: the first warning is still present when disabling all linter packages.

Could not resolve 'project-palette-finder' to a package path - /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:387

Could it be Atom core related anyway?

**Comment by postcasio** [comment]
Yeah, if it doesn't happen in safe mode (which only loads core packages), it's a problem with a third party package.

> Just noticed: the first warning is still present when disabling all linter packages.
> 
> Could not resolve 'project-palette-finder' to a package path - /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:387

This message is generated by `atom-color-highlight` but it's nothing to worry about. It attempts to load the `project-palette-finder` package to provide more features if you have it installed.

**Comment by ludwighogstrom** [comment]
Ok! Thanks!
