### ISSUE TITLE
Cursor blinking distracting in the inspector

### ISSUE THREAD

**Issue by silvenon** [atom/atom#5687]
When I open the Atom web inspector, the class `blink-off` is constantly being added and removed as the cursor blinks, which often pushes and pulls everything by one line. This makes inspecting very hard, is there a workaround?

![cursor](https://cloud.githubusercontent.com/assets/471278/6325806/8e9d96aa-bb4b-11e4-90ea-70b0a59bcbf3.gif)

**Comment by lee-dohm** [comment]
If you widen the view then it won't bounce like you're seeing in the above graphic. I agree it can be distracting, but the alternatives I can come up with are:

1. The inspector to not reflect reality
1. Stop cursor blinking when the inspector is open

Neither of which seem like a good solution.

**Comment by silvenon** [comment]
I tried widening before, but I guess I didn't widen enough, so I thought the width is locked somehow.

Widening is an acceptable workaround for me.

**Comment by silvenon** [comment]
What about making it blink with a repeating CSS animation?

**Comment by lee-dohm** [comment]
I can't find the reference but @probablycorey mentioned at one point that the CSS animation approach was tried, but had a noticeable negative impact to performance.

**Comment by silvenon** [comment]
Ok, that was probably the only alternative.
