### ISSUE TITLE
apm upgrade broken in linux deb

### ISSUE THREAD

**Issue by seangarner** [atom/atom#5690]
```
$ apm upgrade
Could not determine current Atom version installed
$ atom --version
61fff23
```

Version is 0.182.0 but I believe this broke with the switch to iojs.

**Comment by seangarner** [comment]
I've seen on discuss that last year this was happening because of the version number in `/usr/share/atom/resources/app/package.json` was the commit id, but my version in that file is `0.182.0`.

**Comment by kevinsawicki** [comment]
> $ atom --version
> 61fff23

This is troublesome, are you sure this `atom` is the one loading from `/usr/share/atom`?

**Comment by steelbrain** [comment]
`which atom` would be helpful.

**Comment by seangarner** [comment]
I'm guessing it's a local problem because I've just spun up a new ubuntu vm
and installed a fresh atom and it's working fine.  I don't have access to
that computer again until Wednesday so I'll report back later this week.

**Comment by seangarner** [comment]
Thanks @steelbrain for pointing me in the correct direction.
```
$ which atom
/usr/local/bin/atom
$ which apm
/usr/local/bin/apm
```

dpkg -S returned that they weren't installed by a deb so it must have been a hangover from when I tried compiling from source though I don't recall ever installing that way (always used opt myself).

Anyway, now `atom --version` returns the correct version and `apm upgrade` runs.

Apologies for what turned out to be a support ticket, and thanks again for your help.

**Comment by jamesmcq** [comment]
@seangarner I'm having this problem too - could you post what you did to resolve it? Thanks!

**Comment by seangarner** [comment]
@jamesmcq use `which atom` to find out what you're running then use `dpkg -S $(which atom)` to verify that it's not the one installed by the package.  Once you've confirmed then delete the bad one and repeat.  Next time `which atom` should point at the one installed by the package.

If you're redhat based then IIRC you should be able to use `yum provides $(which atom)`.

Don't forget to repeat for the `apm` executable too.

**Comment by jamesmcq** [comment]
awesome thanks! that got it working
