### ISSUE TITLE
nextAction called even in case of error

### ISSUE THREAD

**Issue by lloeki** [atom/atom#5693]
This contradicts the comment:

```
# * `nextAction` (optional) {Function} which will be called after the item is
#   successfully saved.
```

The call should probably be in the `else` clause of the `try` block, if CS supported that.

https://github.com/atom/atom/blob/dcbff35ef5dce9b69fdb7f6dd485dbdd6d22d6fe/src/pane.coffee#L488
https://github.com/atom/atom/blob/dcbff35ef5dce9b69fdb7f6dd485dbdd6d22d6fe/src/pane.coffee#L508

**Comment by izuzak** [comment]
cc @nathansobo @benogle for :eyes: -- is this a bug or should we change the docs?

**Comment by benogle** [comment]
I think it's a bug. We could just move that line into the try.
