### ISSUE TITLE
Finding a file (⌘+p or ctrl+p) doesn't work across multiple root directories

### ISSUE THREAD

**Issue by damonkreft** [atom/atom#5694]
Hey,

Attempting to take advantage of the new "Atom's tree-view can now contain multiple root directories" feature. When using ⌘+p or ctrl+p to find a file, it seems only the first open root directory is searched...

![image](https://cloud.githubusercontent.com/assets/4972683/6332539/0fb90e86-bb7e-11e4-8091-31a141b255bc.png)

I'm using Ubuntu 14.10 and Atom 0.182.0

**Comment by maxbrunsfeld** [comment]
This (as well as multi-folder support in the git-diff package) is implemented on master and will ship in Atom 0.183. Thanks!

**Comment by damonkreft** [comment]
Thank you sir :)
