### ISSUE TITLE
"Line removed" indicator duplicated on wrapped line

### ISSUE THREAD

**Issue by bblack** [atom/atom#5696]
In this example, a line has been removed after line 13:

![screen shot 2015-02-23 at 2 01 26 pm](https://cloud.githubusercontent.com/assets/1072131/6334722/862032d0-bb64-11e4-8404-45b71c9ec587.png)

**Comment by 50Wliu** [comment]
Hi, what version of Atom is this?  Can you reproduce it in safe mode (`atom --safe`)?

**Comment by bblack** [comment]
0.182.0, on Mac OSX Mavericks. behaves identically with `--safe`.

**Comment by izuzak** [comment]
I was able to reproduce this:

![double](https://cloud.githubusercontent.com/assets/38924/6376850/bb31991a-bd20-11e4-9233-746613a9eed2.gif)
