### ISSUE TITLE
`New File` doesn't work any more.

### ISSUE THREAD

**Issue by danielbayley** [atom/atom#5697]
For some reason I can't create a new file at all within Atom, only open existing ones.

Neither `⌘N` or clicking the menu item work. This behaviour started with the last couple of updates.

**Comment by izuzak** [comment]
Which version of Atom are you using and which OS? Can you reproduce the problem in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by mark-hahn** [comment]
This and other tree problems are happening to me also.  I've been jumping
out to notepad++ to manage files and folders.  I've been meaning to open
issue on `atom/tree-view`.

Windows 8.1
Atom 0.182.0

**Comment by 50Wliu** [comment]
I can't reproduce on Atom 0.182.0, Ubuntu 14.10.

**Comment by danielbayley** [comment]
Atom 0.182.0 (0.182.0)
OS X Yosemite 10.10.2 (14C109)

It works ok in safe mode, and I actually managed to narrow it down to the linter package thanks to that guide. So i'll create an issue on there. Thanks.

**Comment by mark-hahn** [comment]
Mine is also fixed in safe mode but I don't use linter.  Sorry for not
checking first.
