### ISSUE TITLE
Follow shortcut links (*.lnk) on Windows

### ISSUE THREAD

**Issue by 1j01** [atom/atom#5699]
Atom should support following the shortcuts/"shell links" Windows uses.
Currently when dragging a file to Atom, or when selecting a shortcut in the tree view, the binary file is opened directly. ([format ![msdn](http://bits.wikimedia.org/static-1.25wmf17/skins/Vector/images/external-link-ltr-icon.png?2015-02-11T19:35:00Z)](https://msdn.microsoft.com/en-us/library/dd891294.aspx))

**Comment by paulcbetts** [comment]
This is super inconsistent with what any other editor would do with .lnk files - I don't know of any editor that would try to follow the link.

**Comment by 1j01** [comment]
The current behavior is inconsistent with Windows applications. I'm not surprised if other editors have the same issue. Surely there's no argument for opening a binary file instead following the links, so I think this "inconsistency" would definitely be an improvement regardless.

**Comment by kevinsawicki** [comment]
I believe this is a duplicate of https://github.com/atom/atom/issues/2985
