### ISSUE TITLE
Uncaught Error: Atom can only handle files < 2MB for now.

### ISSUE THREAD

**Issue by jurgenmehja** [atom/atom#5700]
Uncaught Error: Atom can only handle files < 2MB for now.

**Atom Version**: 0.153.0
**System**: linux 3.13.0-45-generic
**Thrown From**: Atom Core

**Comment by 50Wliu** [comment]
Please update your Atom version (the latest is currently 0.182.0) and see #307 for more details.  Thanks.

**Comment by jurgenmehja** [comment]
Hello,
I am downloading it from https://atom.io/
Thank you
