### ISSUE TITLE
Open-Apple F should allow you to search packages list when viewing installed packages

### ISSUE THREAD

**Issue by benbalter** [atom/atom#5703]
I went to the packages list, looking to change a particular packages setting, and expected Command-F to allow me to search the list (thinking it was just an Atom view). Turns out that's not the case (I had to click into the search filter box, despite the native search dialog popping up).

It'd be awesome if either native search worked, or hitting Command-F hijacked the native functionality and dropped me in the filter dialog when listing installed plugins.

**Comment by 50Wliu** [comment]
I'd actually consider the find box popping up a bug (the best behavior would be to put focus into the filter dialog).

**Comment by izuzak** [comment]
This issue was moved to atom/settings-view#394
