### ISSUE TITLE
JavaScript files do not open new tab

### ISSUE THREAD

**Issue by Eagerestwolf** [atom/atom#5709]
I am running Version 0.182.0 of Atom on Mac OS X 10.10, and I have encountered a bug where opening a JavaScript file does not open the file in a new tab, which I would assume is the expected behavior. To the best of my knowledge, only JavaScript files with the .js extension are affected.

![screenshot 2015-02-24 04 46 39 copy](https://cloud.githubusercontent.com/assets/3085408/6346758/92626c30-bbe0-11e4-96d9-e81ea780568a.png)
![screenshot 2015-02-24 04 48 40](https://cloud.githubusercontent.com/assets/3085408/6346760/9264f860-bbe0-11e4-9193-d89a2abdccbf.png)
![screenshot 2015-02-24 04 48 49](https://cloud.githubusercontent.com/assets/3085408/6346759/9264ccb4-bbe0-11e4-8818-eb53d865caec.png)

**Comment by steelbrain** [comment]
@Eagerestwolf Listing the package you've installed would be very helpful.

**Comment by lee-dohm** [comment]
What would be most helpful is if you could include repro steps. Every way I've tried to open a JavaScript file has succeeded in opening it in a tab. Also, could you give the following information?

* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by Eagerestwolf** [comment]
@steelbrain 
### List of Packages installed
* Stylus
* linter
* linter-coffeelint
* linter-csslint
* linter-jscs
* linter-jshint
* linter-less
* linter-htmlhint (disabled)
* linter-scss-lint (disabled)
* linter-tidy (disabled)

@lee-dohm Opening the application in safe mode does open a new tab, I am therefore closing this as a package related bug.
