### ISSUE TITLE
Add selection above/below all the way

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#5713]
Keycodes `ctrl-alt-up/down` are linked to `editor:add-selection-above/below`, but is there also an editor command to add the selection above/below on all the lines all the way to the top/bottom? I've tried `ctrl-alt-pgup/pgdn/home/end` and had a look in the command pallette (`ctrl-shift-p`) but haven't found it.

[see also](https://discuss.atom.io/t/add-selection-above-below-all-the-way/14245)

**Comment by izuzak** [comment]
I don't think there's a command for that, @stijnsanders. I think that most of these commands were inspired by commands in SublimeText. Do you know if such a command exists in Sublime and what's it called? I haven't noticed it myself, but I'm definitely not a power-user. If you didn't either, did you notice it in a different editor? 

Also, this might be a neat idea to develop a package for -- would you consider creating a package for this or using a package some else creates? You could suggest that idea on the Packages section of the forum: https://discuss.atom.io/c/packages.

**Comment by stijnsanders** [comment]
I don't have experience with SublimeText, but with Notepad++. There you can switch to 'rectangular selection' with Shift, Alt and the arow keys. But also with Home, End, PgUp and PgDn, and their combinations with Ctrl (*). So there I could do Shift-Alt-Ctrl-End to 'rectangular select' all the way to the bottom.

In switching to Atom, it takes a bit of getting used to this different concept of 'adding to the selection' (or sometimes to the 'shape of the cursor', I noticed) and I missed these extra combinations. Also you're penalized with Ctrl-Alt-ArrowDown when you're a line too far because Ctrl-Alt-ArrowUp adds a line to the top, not remove a line at the bottom where you were watching...

(*: Hmm, had a quick check and that's not true, apparently I've been using Shift-Alt-PgDn and the Ctrl combo's don't work, but it would be great if they did. Come to think of it, if there's entirely no overlap whatsoever, Atom could do both! If there is overlap, perhaps a switch in the settings between 'additive selection' and 'rectangular selection'. But I'm nowhere near of working myself into the source to try this for myself...)
