### ISSUE TITLE
Atom won't start on Fedora

### ISSUE THREAD

**Issue by sryze** [atom/atom#5715]
I think I might have messed something up by installed a locally built RPM package of Atom on top of existing installation, but I'm not sure. Here's what I did:

1. Built Atom from git
2. Built an RPM package by running `script/grunt mkrpm`
3. Installed the package with `rpm -i`, at that time both official package and mine were installed
4. None on the two Atoms wanted to start, so I deleted both via yum
5. Re-installed the official RPM package

After I've done all that Atom still wouldn't start, neither in normal nor in safe mode. When I run Atom from terminal nothing happens - no errors or other messages.

OS: Fedora 21
Atom version: 0.182.0

**Comment by sryze** [comment]
Don't know what I did but it's working again :)

**Comment by gentunian** [comment]
It happened to me too. Installed the `rpm`, invoked `atom` in console an nothing happened. I'm trying to find out what is going on. This happened with atom 1.0.
