### ISSUE TITLE
Editor doesn't horizontally scroll

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#5716]
* Open this content in an editor:

```
'1':
  'name': 'support.type.property-name.css'
  'match': '(?<![-a-z])(-webkit-[-A-Za-z]+|-moz-[-A-Za-z]+|-o-[-A-Za-z]+|-ms-[-A-Za-z]+|-khtml-[-A-Za-z]+|zoom|z-index|y|x|wrap|word-wrap|word-spacing|word-break|word|width|widows|white-space-collapse|white-space|white|weight|volume|voice-volume|voice-stress|voice-rate|voice-pitch-range|voice-pitch|voice-family|voice-duration|voice-balance|voice|visibility|vertical-align|variant|user-select|up|unicode-bidi|unicode|trim|transition-timing-function|transition-property|transition-duration|transition-delay|transition|transform|top-width|top-style|top-right-radius|top-left-radius|top-color|top|timing-function|text-wrap|text-transform|text-shadow|text-replace|text-outline|text-justify|text-indent|text-height|text-emphasis|text-decoration|text-align-last|text-align|text|target-position|target-new|target-name|target|table-layout|tab-size|style-type|style-position|style-image|style|string-set|stretch|stress|stacking-strategy|stacking-shift|stacking-ruby|stacking|src|speed|speech-rate|speech|speak-punctuation|speak-numeral|speak-header|speak|span|spacing|space-collapse|space|sizing|size-adjust|size|shadow|respond-to|rule-width|rule-style|rule-color|rule|ruby-span|ruby-position|ruby-overhang|ruby-align|ruby|rows|rotation-point|rotation|role|right-width|right-style|right-color|right|richness|rest-before|rest-after|rest|resource|resize|reset|replace|repeat|rendering-intent|rate|radius|quotes|punctuation-trim|punctuation|property|profile|presentation-level|presentation|position|pointer-events|point|play-state|play-during|play-count|pitch-range|pitch|phonemes|pause-before|pause-after|pause|page-policy|page-break-inside|page-break-before|page-break-after|page|padding-top|padding-right|padding-left|padding-bottom|padding|pack|overhang|overflow-y|overflow-x|overflow-style|overflow|outline-width|outline-style|outline-offset|outline-color|outline|orphans|origin|orientation|orient|ordinal-group|opacity|offset|numeral|new|nav-up|nav-right|nav-left|nav-index|nav-down|nav|name|move-to|model|min-width|min-height|min|max-width|max-height|max|marquee-style|marquee-speed|marquee-play-count|marquee-direction|marquee|marks|mark-before|mark-after|mark|margin-top|margin-right|margin-left|margin-bottom|margin|mask-image|list-style-type|list-style-position|list-style-image|list-style|list|lines|line-stacking-strategy|line-stacking-shift|line-stacking-ruby|line-stacking|line-height|line|level|letter-spacing|length|left-width|left-style|left-color|left|label|justify|iteration-count|inline-box-align|initial-value|initial-size|initial-before-align|initial-before-adjust|initial-after-align|initial-after-adjust|index|indent|increment|image-resolution|image-orientation|image|icon|hyphens|hyphenate-resource|hyphenate-lines|hyphenate-character|hyphenate-before|hyphenate-after|hyphenate|height|header|hanging-punctuation|grid-rows|grid-columns|grid|gap|font-weight|font-variant|font-style|font-stretch|font-size-adjust|font-size|font-family|font|float-offset|float|flex-group|flex|fit-position|fit|fill|filter|family|empty-cells|emphasis|elevation|duration|drop-initial-value|drop-initial-size|drop-initial-before-align|drop-initial-before-adjust|drop-initial-after-align|drop-initial-after-adjust|drop|down|dominant-baseline|display-role|display-model|display|direction|delay|decoration-break|decoration|cursor|cue-before|cue-after|cue|crop|counter-reset|counter-increment|counter|count|content|columns|column-width|column-span|column-rule-width|column-rule-style|column-rule-color|column-rule|column-gap|column-fill|column-count|column-break-before|column-break-after|column|color-profile|color|collapse|clip|clear|character|caption-side|break-inside|break-before|break-after|break|box-sizing|box-shadow|box-pack|box-orient|box-ordinal-group|box-lines|box-flex-group|box-flex|box-direction|box-decoration-break|box-align|box|bottom-width|bottom-style|bottom-right-radius|bottom-left-radius|bottom-color|bottom|border-width|border-top-width|border-top-style|border-top-right-radius|border-top-left-radius|border-top-color|border-top|border-style|border-spacing|border-right-width|border-right-style|border-right-color|border-right|border-radius|border-length|border-left-width|border-left-style|border-left-color|border-left|border-image|border-color|border-collapse|border-bottom-width|border-bottom-style|border-bottom-right-radius|border-bottom-left-radius|border-bottom-color|border-bottom|border|bookmark-target|bookmark-level|bookmark-label|bookmark|binding|bidi|before|baseline-shift|baseline|balance|background-size|background-repeat|background-position|background-origin|background-image|background-color|background-clip|background-break|background-attachment|background|azimuth|attachment|appearance|animation-timing-function|animation-play-state|animation-name|animation-iteration-count|animation-duration|animation-direction|animation-delay|animation-fill-mode|animation|alignment-baseline|alignment-adjust|alignment|align-last|align|after|adjust|will-change)(?=\\s*)'
```

* Delete line 1 using `ctrl-shift-k`
* Editor no longer scrolls horizontally

**Comment by izuzak** [comment]
Strange, I can't seem to reproduce this. I'm on 0.183.0-3e439f3, here's a GIF:

![5](https://cloud.githubusercontent.com/assets/38924/6355466/91fd4faa-bc56-11e4-8587-97da00ac0387.gif)

**Comment by kevinsawicki** [comment]
@izuzak weird, I am in safe mode, using source code pro font at size 13 just for more context.

**Comment by nathansobo** [comment]
I can reproduce.

**Comment by dvdbrk** [comment]
I think you are safe to reopen this - I have just reproduced the issue with completely different file...

**Comment by rsese** [comment]
I can't reproduce the behavior described in this issue - can you create a new issue for the behavior you're seeing and fill out the issue template @dvdbrk?

**Comment by BlueSilverCat** [comment]
atom: 1.15.0
os: windows 10 64bit
font: default

```
１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
```
Horizontal scroll bar must fits the length of the first line, but it fits the length the second line.

**Comment by rsese** [comment]
@BlueSilverCat - thanks I can reproduce with that sample content on 1.15.0 on Windows 10 and macOS 10.12.3.  Can you open a new issue for that since I can't reproduce the original behavior described in this issue?

**Comment by BlueSilverCat** [comment]
Thank you for your response.
I create new issue #13983.

**Comment by KvalheimRacing** [comment]
Any news here? horizontal scrolling just stopped working. was working before, got the newest version of atom. Same mouse

**Comment by nathansobo** [comment]
@KvalheimRacing What version of Atom are you on? /cc @ungb

**Comment by KvalheimRacing** [comment]
1.18.0

**Comment by KvalheimRacing** [comment]
Remember having a older atom at one point, and never having an issue with horizontal scrolling. Don't know what that version was.

**Comment by KvalheimRacing** [comment]
I just bought a new logitech t630, it also has horizontal scrolling (in touch, not as a wheel). Tested everything now, simultanious as the MX Master,, having the same problems with the MX Master, but everything works with the t630. What do you guys think, is it a software problem with the logitech MX Master or is it atom because of different scrolling method?

**Comment by nathansobo** [comment]
It might be helpful to see the mouse events since I don't have your hardware. Maybe you could try running this in your console when attempting to horizontally scroll and then share the output in a new issue specific to this problem?

```js
window.addEventListener('mousewheel', (e) => { console.log(e) }, true)
```

**Comment by KvalheimRacing** [comment]
@nathansobo good idea.

When I run the horizontal scroll wheel up and down and it is **not** working; 

![image](https://user-images.githubusercontent.com/19176631/28212569-5d0f4992-68a2-11e7-8ca2-08698d00bfd2.png)

When it **is** working;

![image](https://user-images.githubusercontent.com/19176631/28212604-7ab6f7e2-68a2-11e7-8606-0a3fffa87f30.png)

Things seems to make sense. Not displaying any movement in X if it is not working, and displaying movement in X when it's working. Worth mentioning that now I had a harder time reproducing the error, suddenly I could go from every application and then to atom and it worked. And suddenly it didn't work (as you can se over).

**Comment by nathansobo** [comment]
This looks like a browser-level bug interacting with your hardware since we're getting 0 for the `deltaX` values. I'd be curious if you see the error in Chrome as well. If not, perhaps the next electron upgrade will solve it.

**Comment by KvalheimRacing** [comment]
What do you mean by in chrome?

**Comment by nathansobo** [comment]
The Chrome web browser... if you register an event listener in the dev tools console of the latest Chrome does it exhibit the same behavior of reporting 0 x deltas?

**Comment by KvalheimRacing** [comment]
Yes, it's the same error;
![image](https://user-images.githubusercontent.com/19176631/28388960-a5092d90-6cd4-11e7-8290-6cfda0b8a8b0.png)

**Comment by KvalheimRacing** [comment]
And then, suddenly it started working;

![image](https://user-images.githubusercontent.com/19176631/28389084-0f6aeac0-6cd5-11e7-89ad-91fb722da7f9.png)

**Comment by KvalheimRacing** [comment]
So unstable error...

**Comment by 50Wliu** [comment]
@KvalheimRacing ok since it's also happening in Chrome this would appear to be a Chrome bug.  You should check the Chromium bugtracker to see if it's already been reported.

**Comment by KvalheimRacing** [comment]
Ok thanks

**Comment by KvalheimRacing** [comment]
Just made a bug here https://bugs.chromium.org/p/chromium/issues/detail?id=746954, please star if you have the same issue.

**Comment by KvalheimRacing** [comment]
This should be merged with #12227 or something.

**Comment by ZeroG001** [comment]
I have the same problem. This isn't a really a solution but I open the **command palette** select **Editor: Toggle Soft Wrap** to turn it **on**. Then select **Editor: Toggle Soft Wrap** again to turn it **off**. Horizontal scrolling magically starts works after that

**Comment by ksuhiyp** [comment]
> My case:
> 
> Horizontal scrolling in Atom is resulting into a vertical scroll down wise on left-right ways, in general there is no problem in horizontal scrolling in chrome.

At the moment i finished typing above i switched to atom to test the issue again and its working fine !
