### ISSUE TITLE
reopen last item not working

### ISSUE THREAD

**Issue by mxa** [atom/atom#5718]
"reopen last item" from the menu is not working after a restart. There should be "recent files" in the menu.

**Comment by izuzak** [comment]
Hey @mxa,

> "reopen last item" from the menu is not working after a restart. 

Yeah, that reopen the last closed tab within an Atom session, not across session. See https://github.com/atom/atom/issues/3085 for a similar issue and a package suggestion.

> There should be "recent files" in the menu.

That would be neat, yeah -- there's already an open issue for this: https://github.com/atom/atom/issues/4241.

Does this answer your questions?

**Comment by mxa** [comment]
Yes, thanks!

**Comment by izuzak** [comment]
@mxa Cool, I'm going to close this out then. My recommendation would be to try some of the packages created by the community and see if one of those meets your needs for now.
