### ISSUE TITLE
Markdown Preview display error

### ISSUE THREAD

**Issue by fmsedrez** [atom/atom#5719]
# Markdown Preview display error

Markdown Preview windows does not display the last cell on last line if it is empty. 
View line **Show Available Snippets** in print screen.

* Ubuntu 14.10
* Atom 0.182.0
* [Markdown file] (https://github.com/fmsedrez/atom-keyboard-shortcuts/blob/master/README.md)

Atom: Code View and Markdown Preview             | GitHub Site View
:-------------------------:|:-------------------------:
 ![screenshot from 2015-02-24 16 19 22](https://cloud.githubusercontent.com/assets/1216898/6357330/6740c2ec-bc42-11e4-8aa8-dd4c04bd344a.png) | ![screenshot from 2015-02-24 16 31 29](https://cloud.githubusercontent.com/assets/1216898/6357352/9cbc10de-bc42-11e4-9560-9b5b952da256.png)

**Comment by izuzak** [comment]
This issue was moved to atom/markdown-preview#206
