### ISSUE TITLE
Investigate memory consumption with large files

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#5721]
I have some radical design changes in mind to support files of arbitrary size, but first we should perform a basic accounting of where memory is going and look for any quick wins.

**Comment by benogle** [comment]
:heart:

**Comment by nathansobo** [comment]
I spent some time exploring the heap snapshot with `benchmark/fixtures/huge.js`, a copy of jQuery with 9246 lines. The bulk of the memory is spent on objects that are allocated and stored in `DisplayBuffer` and `TokenizedBuffer`. As you can see below, the retained size of the `DisplayBuffer` alone is nearly 30mb just for `huge.js`, a 247kb file:

![screenshot 2015-02-24 15 44 53](https://cloud.githubusercontent.com/assets/1789/6361079/62e43662-bc3c-11e4-9fdf-41305d5116f9.png)

A comparison with the a snapshot taken with no editor open shows the kinds of objects we're wasting memory on:

![screenshot 2015-02-24 15 45 59](https://cloud.githubusercontent.com/assets/1789/6361121/bec75ebe-bc3c-11e4-948d-6323dccc5e43.png)

We have a lot of `(array)` objects, which seem to serve as book-keeping for other objects in v8 internals. Then there's objects we recognize, `Token`s, `Array`s, `String`s, and `TokenizedLine`s all consume considerable memory.

This confirms my suspicion that our approach to transforming the contents of the buffer for presentation on screen is way too naive and memory intensive. This gives me confidence that the next step is to radically reduce the memory footprint of the `DisplayBuffer` and `TokenizedBuffer` in the system. Stay tuned.
