### ISSUE TITLE
Atoms opens the union of the given paths and the paths specified by the project

### ISSUE THREAD

**Issue by wvanlint** [atom/atom#5724]
I normally start Atom using its icon which runs it without arguments under the home path.
I can then remove the home path as the root folder and add some other root folders that I am working on.
However, when I restart Atom, the home path will be re-added as a root folder which seems unexpected.

As far as I can tell from the code, projects/workspaces are uniquely identified under ~/.atom/storage by the paths that are given on the command line (the path that the command is executed from if there are no paths given). Is this correct?
Would only opening the project paths as root folders be suitable over also opening the given paths as root folders if and only if the project exists?
If the project path doesn't contain some of the given paths, that means the user has manually removed them, given the unique identifier of the project.

If there is interest in any changes, I would be excited to work on it @maxbrunsfeld  :)

**Comment by maxbrunsfeld** [comment]
> I normally start Atom using its icon which runs it without arguments under the home path.

@wvanlint Atom shouldn't be opening your home directory when you run it from the app icon; that's a bug either in Atom or some package. It seems related to a bug that a few people have reported (#5621, #5617).

What OS are you on? Also, does it happen if you clear your `~/.atom/storage` directory and open Atom with `atom --safe`?

**Comment by wvanlint** [comment]
I looked into it before, could it maybe be related to the following code at https://github.com/atom/atom/blob/master/src/browser/main.coffee#L136?
```
pathsToOpen = [executedFrom] if executedFrom and pathsToOpen.length is 0
```
I'm running Atom 0.182.0 on Ubuntu 14.04, it happens when clearing `~/.atom/storage` and running `atom --safe` too.
I can check if it happens from the latest commit later too.

So am I correct in that your state is saved by the hash of the given paths in `~/.atom/storage`?
If so, if you run `atom some-path` is it actually possible to remove `some-path` as root folder and add only for example `some-path/a` and `some-path/b` as root folders, or will `some-path` always be added back when you run `atom some-path` again?
If paths are used as project identifiers, I would think that the former would be the intended behavior.

**Comment by maxbrunsfeld** [comment]
> I looked into it before, could it maybe be related to the following code at https://github.com/atom/atom/blob/master/src/browser/main.coffee#L136?

I think that `executedFrom` should be undefined unless you're running the `atom` executable from the command-line.

**Comment by maxbrunsfeld** [comment]
> If paths are used as project identifiers, I would think that the former would be the intended behavior.

Currently, we don't yet have a concept of a 'project identifier' that is separate from a root folder. What we're working on currently is getting multi-folder support working consistently across all of Atom's built-in packages. But then, we may need to rethink our flows for working with multiple root folders. Maybe you can help us to think about the ideal flow.

I'd love it if you wanted to work on this area with me. I think first, we need to spend some time brainstorming about multi-folder workflows in Atom. I'm going to create an issue where we can discuss it with anyone who's interested.

**Comment by maxbrunsfeld** [comment]
@wvanlint see #5728. I'd like to consolidate our meta-level discussion about multi-folder UX there as much as possible.

**Comment by wvanlint** [comment]
It looks like I was indirectly calling the wrong executable through the Ubuntu Dash (the one that is also called from the command line).
Sorry but thanks for the help! I'll take a look at the other issue.
