### ISSUE TITLE
Using proxy server with Atom is very complex

### ISSUE THREAD

**Issue by alexjurkiewicz** [atom/atom#5725]
You can configure Atom (OSX) to use a HTTP proxy as follows:
1. Add proxy info to APM:
   
   ```
   apm config set proxy http://localhost:9999
   apm config set http-proxy http://localhost:9999
   apm config set strict-ssl false # only add if needed - may be required if your proxy uses a non-globally-accepted SSL cert
   ```
2. Run `HTTP_PROXY="http://127.0.0.1:9999" HTTPS_PROXY="http://127.0.0.1:9999" atom --proxy-server="http://127.0.0.1:9999"`
3. You can now update Atom & packages/themes from within Atom.

(sidenote: git clones still won't work and require proxy configuration in `$HOME/.gitconfig` or `$HOME/.ssh/config`.)

This is reallllllly complex, and AFAICT not documented anywhere. I cobbled together this information from:
- atom/atom-shell#584
- atom/atom#1807 (very helpful)
- atom/atom-shell#183

This ticket is about the following issues:
- Atom needs proxy config specified three ways (should only need to specify this data in once)
- There's no documentation of this process (steps should be mentioned in the manual)

**Comment by kevinsawicki** [comment]
> Edit $HOME/.atom/.apm/.apmrc and add:

Your `.apmrc` file should go in `$HOME/.atom/.apmrc`, `$HOME/.atom/.apm/.apmrc` is the path to the global file that is a fallback.

**Comment by alexjurkiewicz** [comment]
Ah, thanks, edited my original comment.

**Comment by alexjurkiewicz** [comment]
It appears the http_proxy/https_proxy env vars are used by whatever grabs the avatar icons, so you do need to specify those. Edited original comment again.

**Comment by phawxby** [comment]
+1
Also my system uses a .pac file for internet access meaning when I'm not on the corporate network everything still works. Having a fixed proxy means I need to keep adding and removing depending on where I am. It would be nice for it to fallback if the proxy servers fails to respond

**Comment by JPvRiel** [comment]
as far as I can tell, atom doesn't respect http_proxy nor https_proxy environment variables, and there other issues logged about it still open:
* Not using env: https://github.com/atom/apm/issues/398 and https://github.com/atom/atom/issues/1807
* Icons go missing: https://github.com/atom/atom/issues/9346
* Problem with custom corporate CA signing certs: https://github.com/atom/apm/issues/340 

https://github.com/atom/apm/pull/447 is a recent fix for getting the upper case HTTP_PROXY envrioment variables, but not sure about lowercase...

**Comment by foundatron** [comment]
I would love if Atom just worked worked with OSX's proxy auto discovery

**Comment by lee-dohm** [comment]
I believe the original issue is fixed based on the [latest documentation](https://github.com/atom/apm#behind-a-firewall). At least, I feel that the instructions for `apm config set` are much more understandable than hunting down a specific configuration file.

@alexjurkiewicz, do you agree?

**Comment by alexjurkiewicz** [comment]
@lee-dohm, I like the `apm config set` info, thanks for adding that. I'll edit the OP with the update. However as per OP I had to set proxy config in three places. The documentation you link to refers to just one.

#9346 shows that even with proxy added to APM config, some web resources fail to load. They work when the env vars and/or command-line option is used (I forget which).

I don't work in a proxied environment so I'll unsubscribe from this ticket soon, but IMO this issue is not fixed, for two reasons:
a) the current documentation is insufficient
b) even sufficient documentation still leaves my original complaint that "Using proxy server with Atom is very complex"

**Comment by lee-dohm** [comment]
Thanks for replying back and for updating the original description.

**Comment by victorng8** [comment]
@alexjurkiewicz I've tried doing the steps you mentioned for Windows 7 Enterprise Edition 64 bit. When trying to search and "Install packages", I get this error :
`tunneling socket could not be established, cause=socket hang up`

**Comment by alexjurkiewicz** [comment]
Sorry, I can't troubleshoot your setup. I suggest trying minimal changes as per the docs and only attempting what my post suggests if the official instructions fail.

**Comment by victorng8** [comment]
@alexjurkiewicz Nevermind. I have found a solution that worked for me over here :
http://stackoverflow.com/a/31174009/1186038

Summary: Configuring for `http-proxy` or `HTTPS_PROXY` did not do anything for me.
Only setting `proxy` and 'strict-ssl=false' did.

**Comment by Stibbons** [comment]
Still not working with the system's .pac file? Can it be done so it is more easier to work with Atom on a Windows environment inside a corporate?

**Comment by dsnellgrove** [comment]
To help move the focus of this away from narrow solutions such as environment variables, Firefox provides a great example of concise and complete connection settings options along with a sensible default (Use system proxy settings). An equivalent solution in Atom would be a fantastic resolution to this issue. 
![image](https://user-images.githubusercontent.com/3044831/29030814-4600c9c2-7b5a-11e7-846e-65528d6bd7bf.png)

**Comment by lee-dohm** [comment]
As of Atom v1.15, [it uses system proxy settings by default](https://github.com/atom/settings-view/pull/898). The proxy settings, if one needs to set them, [have been documented](http://flight-manual.atom.io/getting-started/sections/installing-atom/#behind-a-firewall) for quite a while now. So I believe everything from this issue has been covered. It is true that we don't have a GUI for editing proxy settings ... but that's not something we want to offer really when using the system settings should work for the vast majority of people.

**Comment by Stibbons** [comment]
I keep getting network error even though chrome works. i guess this comes from the fact proxy is configured from a tac file
