### ISSUE TITLE
`Add File` horizontal scrolling with long paths

### ISSUE THREAD

**Issue by CentaurWarchief** [atom/atom#5727]
Hi!
As yours guys and gals can see:

![screenshot from 2015-02-24 22 15 13](https://cloud.githubusercontent.com/assets/967317/6363069/a47a1e3a-bc72-11e4-9909-39f3b12374f5.png)

Maybe a bug?
Thanks.

**Comment by 50Wliu** [comment]
Fixed in the latest Atom version (currently 0.182.0), please update.

**Comment by CentaurWarchief** [comment]
@50Wliu Cool, I didn't see.

:beers:
