### ISSUE TITLE
Improve Atom's multi-folder workflow

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#5728]
Once all of Atom's bundled packages have basic support for multiple root folders, we should step back and consider how Atom's multi-folder support could be improved. Atom users, if you have observations or ideas about how we could better support working on multiple projects concurrently, please share them here.

Note that even basic multi-folder support isn't complete yet. To track that, see https://github.com/atom/atom/issues/770#issuecomment-75345186. Also, if you have anything to report that's obviously a bug, **please make a separate issue for it**.

/cc @atom/core @atom/non-github-maintainers

I'll summarize/dedupe the ideas we come up with:
- Rename tree-view commands to clarify `Add Folder` vs `Add Root Folder` - @50Wliu
- Persist combinations of root folders via an explicit project file, not based on which paths were originally opened - @wvanlint
- `atom path1 path2` should always result in both paths being added to the project, even if `path2` had previously been manually removed from the project last time Atom was opened with those paths - @D-side
- Project files should be strictly optional - @mark-hahn 
- Project files should be implemented in a way that would later allow storing project-specific settings - @lee-dohm.
- Multiple folders need to be sortable - @andyburke

**Comment by 50Wliu** [comment]
I was too late to comment on the original tree view PR, but I guess I'll do so now here.

Would the following naming changes 'flow' better?
* Renaming `Add root folder` to `Add folder`
* Renaming `Add folder` to `New folder` (and ditto with `Add file`)

`Add root folder` just sounds a bit scary to me ;P.

Also, I don't know if this is done in any other editors or even if it's possible, but I have a few projects that are completely identical in folder structure with only the files within the folders changing.  In those cases, would it somehow be possible to combine the folders and display them as one?

**Comment by maxbrunsfeld** [comment]
@50Wliu Yeah, I agree with your naming suggestions. The `New {File,Folder}` bit is already done, and `Add Root Folder` does kind of makes it sound like you're adding `/`.

**Comment by lee-dohm** [comment]
[Mentioned this on Discuss](https://discuss.atom.io/t/rfc-multiple-root-folders/15096).

**Comment by wvanlint** [comment]
This might only be tangentially related but when I was trying out multi-folders, I was surprised the following state got saved.

* Ran  `atom dir-a` and added another root folder `dir-b` and closed atom again.
* Ran `atom dir-a` again and it remembered the root folder that I added.

I wanted to figure out where it saved its state which led me to `~/.atom/storage` where there are files named by the hash of the path that you were trying to open.
That might be quite opaque to the user.
Also, it might get complicated when `atom dir-a dir-z` would open folders in the same window.

In comparison, Sublime will - as far as I can tell - do the following:
* Only save the state of the last window of the application globally, not per path.
* Save state as an explicit project file.

**Comment by KeitIG** [comment]
I noticed some bugs, not sure If I have to create a separate issue or if it is ok here.

```
|- myrootfolder-1
|---- ...
|
|- myrootfolder2
|---- myfile.js
```

- When I rename myfile.js to something else, it goes in myrootfolder-1 root.
- There is no find and replace per root folder (but I think this is already known)
- When you create a new root folder or when you start your editor, all root folders are expanding thelelves.

**Comment by nikolaydyankov** [comment]
@KeitIG 

I have experienced the first issue, but I can't figure out what exactly is happening.

**Comment by abe33** [comment]
@KeitIG @nikolaydyankov I believe it's because the rename operation may do something like `atom.project.getDirectories()[0]` to build the final path.

**Comment by D-side** [comment]
My suggestions are related to `atom` CLI helper:

* when multiple paths are given to `atom`, all of them should be opened in a single window (works for files so far, not for folders)
  * right now it reacts really weirdly: opens given files in an existing window and opens a new window for each given folder
  * it's not obvious how it should be affected by `--new-window` (if should be)
* when an external (for already open folders) file is opened using `atom`, its containing folder should not be added as a root folder, a folder can always be given explicitly, once the point above is implemented

**Comment by maxbrunsfeld** [comment]
@D-side I believe all of your suggestions are implemented in Atom's latest release.

**Comment by maxbrunsfeld** [comment]
> When I rename myfile.js to something else, it goes in myrootfolder-1 root.

@KeitIG Thanks for the report. This is fixed on master.

**Comment by D-side** [comment]
@maxbrunsfeld okay, just installed the latest build. Yeah, great!

One thing is missing though, if `--multi-folders` is given a file, its enclosing folder is added too. Sometimes. Sometimes not. Failing to find the cause of this so far. The only clue I currently have is that if I open the first folder in Atom for the first time, enclosing folder is added. 

---

UPD: hey, that's interesting. I may have found a bug. I was suspecting `remember-session` was messing up with this, but apparently not, I've disabled it... Okay, a sequence to reproduce:

1. `atom --multi-folder folder1 folder2/file`
  * got a window with `folder1` and `folder2` and opened `file`
2. Remove `folder1` from Atom
  * only `folder2` left
3. Close Atom
3. `atom --multi-folder folder1 folder2/file` (once again)
  * **expecting**: `folder1` and `folder2`
  * **getting**: only `folder2` (`folder1` is seemingly ignored since I removed it from Atom before)
  * **workaround**: remove *all* folders from root, close Atom, run that command again

**Comment by maxbrunsfeld** [comment]
Yeah @D-side I'm glad you brought that up. That's the current expected behavior, as our logic is currently very simple: window states are restored from the last window that was opened with the same combination of paths. I'd really like to get more people's feedback on this. Maybe there should be additional logic where we always make sure that all paths provided as arguments are added, even if they have been previously removed.

**Comment by mehcode** [comment]
> Persist combinations of root folders via an explicit project file, not based on which paths were originally opened

That would be amazing if all state was serialized into explicit project files (that could be implicitly created from the initial root folder).

**Comment by D-side** [comment]
CLI is expected to do what it's told to. Most of the time. If the state is saved, Atom should at least clarify, where.

+1 to @mehcode about explicit project files. That would at least make this behaviour controllable. The question is, where to put that project file.

Suggestion: don't save state implicitly, instead implement:

    atom --make-project <project_file_path> [<paths>...]

Alt. suggestion: make a project implicitly and output the path to newly created file to `stdout` with a hint like:

    $ atom --multi-folder something someotherthing
    Created project file: something/project.atom

![](http://i.imgur.com/xYeyVdv.png)

In general project files have a lot of potential. Storing project-specific data, for instance. Most of its applications can be easily worked around by third-party tools, but this is to be discussed by more people. I was initially thinking of build configurations, but switching to Guake is not that hard to make use of a `/M|R|C/akefile` or whatnot.

**Comment by mark-hahn** [comment]
> project files have a lot of potential.

As long as they are optional and the current behavior is still available.
One of my greatest likes about Atom when I first switched was not having to
deal with &$^& project files.

**Comment by mehcode** [comment]
IIRC you need to explicitly *save* a project in sublime. I'd be fine with that. And the current behavior otherwise.

**Comment by D-side** [comment]
> As long as they are optional and the current behavior is still available.

Yes, except for that implicit state-remembering. Agreed.

**Comment by batjko** [comment]
I agree with @mark-hahn as well.
One of the early tenets and remaimning strengths is of Atom is its hybrid nature, i.e. a text editor out of the box but with the potential to be a full-fledged IDE if one is so inclined.

Introducing Projects is a great thing for most developers, but if Atom is to continue to be a tool of text-editing convenience as well, opening individual files on the fly without having to configure or format any project woohaa, must remain the default behavior. Projects can be a a seamless but optional feature for those who want it.

**Comment by nathansobo** [comment]
@batjko @mark-hahn Absolutely 100% get what you are saying, and the philosophy of simplicity for simple use cases isn't going to change. Whatever we implement project-wise, it should never get in the way of getting work done if you don't want it.

**Comment by lee-dohm** [comment]
I like the idea of project files as a method of defining a complex root structure that can be shared across machines. Additionally, we have talked off and on about having "directory-specific" or "project-specific" settings. The project file would be a good place to put those settings as well.

**Comment by mark-hahn** [comment]
Couldn't these project features be implemented without having an actual project file? I haven't thought this through but it would be nice if was just a feature in settings.

**Comment by mehcode** [comment]
@mark-hahn You could technically just store the project files in `~/.atom` and boom, no project file in your repository.

My whole desire for the concept of projects is to enable what sublime has with its project hot-swap in the same window. I could have a couple "projects" that contains a few repositories (root folders) each and be able to swap between them in the same window (of course without losing untitled and/or unsaved buffers, but that's another task).

I'd just want to make sure that when we get to doing configuration syncing between computers (ala chrome) that we don't sync projects (or workspaces, etc.) -- though it could be an option I suppose (it doesn't make sense to me but maybe it would to someone else).

**Comment by mark-hahn** [comment]
> that we don't sync projects (or workspaces, etc.) 

This gets back to my main complaint with project files.  Having separated metadata gets confusing and there are different situations where you don't know what to do.  And you can get in the screwed-up state where you have the file without the project folder or vice versa.

I think @leedohm's and other's requirements can be met by just having relationships between projects/folders specified in settings.

**Comment by lee-dohm** [comment]
@mark-hahn I have different projects at work and at home. I don't want to have to scroll through work projects at home and vice versa. Since I sync my Atom general settings across both home and work machines, the solution of "just having relationships ... specified in settings" won't work for my purposes.

Here are my desired requirements:

> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt).

1. MUST be able to specify a project structure as a list of root directories
1. Root directories MUST be able to be specified using absolute or relative paths, with support for specifying the HOME directory as part of the path as a symbol, i.e. `~` or `$HOME`
1. SHOULD be able to specify project-specific settings (including scope-specific settings specific to the project)
1. SHOULD be able to easily move all of the above between machines as a single package, separate from other Atom configuration
1. The single package SHOULD be able to be stored wherever the user likes if stored in the filesystem

**Comment by greenhoe** [comment]
There are two issues I have seen, one is it won't allow to to add a root folder if a parent folder is already a root folder so for example

I have 

Folder 1
-- Folder 2
-- Folder 3
Folder 4

If I add Folder 1 as the root folder first it doesn't allow me to then add Folder 2 or 3, but if I add Folder 2 or 3, then Folder 1 as root folders it works.

**Comment by greenhoe** [comment]
It would also be very helpful it you can drag and drop the order of the root folders / rearrange them. In Sublime I could just rearrange the folders right within the tree view but it seems that which ever root folder you add first is always on the top.

**Comment by nathansobo** [comment]
@lee-dohm Loving the RFC terminology, and agree with your requirements. I think things can be kept convenient with sensible defaults.

* Project files SHOULD be automatically saved to a default location on disk with human-readable filenames (.e.g. `~/.atom/projects/atom+text-buffer+event-kit.atom-project`) if the user does not save the project to an alternate location.

I haven't read the RFC for the language... just riffing on your list. Anyway, if we automatically created a project file somewhere predictable, the user wouldn't need to care about the inner workings for everyday use. If they started to care, they could move projects wherever they want to or just version control the whole projects directory on disk.

Another idea:

* When opening a path, Atom should search upward through the opened path for the nearest `.atom-project` file. If it finds one, that project gets opened.

That means you could move your project file out of the `~/.atom/projects` directory and directly into your repository to start version controlling.

**Comment by lee-dohm** [comment]
Thanks @nathansobo. I agree with your additional requirements. I also thought of one more:

* Project roots SHOULD be able to specify the `core.projectHome` setting value as part of the path via a symbol, perhaps `$ATOM_PROJECT_HOME`

The basic gist of RFC 2119 is:

* MUST, SHALL or REQUIRED mean that it is an absolute *must have*
* SHOULD or RECOMMENDED mean that there may be good reasons to not offer this feature, but you should probably take your time to weigh options before you decide they're good reasons :grinning:
* MAY or OPTIONAL mean that the requirement is completely optional

There are negative versions too such as MUST NOT or SHOULD NOT, but they're less often used.

**Comment by TheChymera** [comment]
What I (and I suspect many other CLI-lovers) do most often is have terminals open for a number of repos, and type `atom whate.vs` to edit something. Normally you would expect a second instance to launch, but atom catches that and opens the file in the old window - leaving you to edit a file while having a mismatched tree on the left.

It would be great if in such a case the directory from which you launch atom (or the repo root to which it belongs) would be added as a root folder. Do this, it will be awesome!

**Comment by mehcode** [comment]
Open `file` in whatever atom instance has project `project-name` open (and if there isn't a window open with that project, open a new window).

```
atom --project project-name path/to/file
atom -P project-name path/to/file
```

------

On second thought I'm not sure I'd use the above very much. However the concept of passing `--project` to atom to alter behavior could be neat if explored further.

**Comment by albertdev** [comment]
[sambam asked for the following on the Atom forums](https://discuss.atom.io/t/how-to-work-with-projects/1043/63?u=albertdev):
> Right now Atom gives me ALL (10k+) files and directories, and I only want to view a filtered list as a 'project'. In my particular use case, I have three separate 'projects' (working tasks) that are rooted in the same top-level directory, but filter on different sets of mixed-source files. For instance, build related files, custom target-installed bash scripts, and package management scripts. These are easily managed by a simple filename filter in Kate's JSON project config.

I second his request for filters and wanted to get it listed here, unless people find that it should be treated as a separate feature request.

There's a bit more info when you click the link, BTW.

**Comment by thedaniel** [comment]
This definitely sounds like its own separate feature request.

**Comment by thomasthorsen** [comment]
A couple of additional requirement for the project feature:
 * For each project folder it SHOULD be possible to set
   * File Exclude Patterns: ignore files that match the pattern(s)
   * File Include Patterns: ignore files that do _not_ match the pattern(s)
   * Folder Exclude Patterns: ignore folders that match the pattern(s)
   * Folder Include Patterns: ignore folders that do _not_ match the pattern(s)
   * Follow Symlinks: if true, symlinks will be followed
 * The complete list of files in the project with any include/exclude patterns taken into consideration SHOULD be made available to plugins so that plugins do not have to deal with iterating the directory structure and applying the filtering patterns.
 * It SHOULD be possible to specify project specific external commands that can be executed and have the output captured and parsed with a specified regular expression that extract the file, line and column to enable quick navigation to build errors or other diagnostic output.

**Comment by xlaywan** [comment]
There is no possibility to add project folder which is subdirectory of already added folder.

**Comment by Ciantic** [comment]
Why this feature is called "Add Project Folder"? It imply's there is some sort of project support now builtin to Atom, isn't more accurate to call it "Add another Folder" or something such.

I'm using [atom project manager](https://github.com/danielbrodin/atom-project-manager) for actual project support (different settings between projects etc).

**Comment by nelson-liu** [comment]
i'd like the capability to integrate dragging and dropping of folders. Currently, if you drag and drop a folder into atom (osx) it will open a new atom window with that folder. Is there an option to just add that folder to the current window?

**Comment by mnquintana** [comment]
It would be great if adding a project folder from the tree-view scrolled to that folder. Currently it can be hard to tell if the Add Project Folder command worked properly, because you don't immediately see if the folder was added or not without the extra step of scrolling to it.

(I can make a separate issue for this too.)

**Comment by mrameezraja** [comment]
There should be a solution of projects like in Visual Studio. One solution can contain multiple projects and every project can have multiple root folders. 

- Project 1 ( This could be a config name, no need to create a real folder)
--- Project Root Folder (this is already implemented in atom, we can add multiple root folder inside a project)
----- Project Files
- Project 2 
--- Project Root Folder 1
--- Project Root Folder 2

**Comment by Ciantic** [comment]
@mrameezraja you can do that with https://github.com/danielbrodin/atom-project-manager you simply edit the project file and add multiple folders.

**Comment by mrameezraja** [comment]
@Ciantic  can i have multiple projects in same window ?

**Comment by mrameezraja** [comment]
@Ciantic  can i have multiple projects in one atom window using project-manager?

**Comment by Ciantic** [comment]
@mrameezraja the naming is confusing, project == solution in "Project manager", it is older than "Add Project folder" introduced in Atom itself. Try the thing.

**Comment by Ciantic** [comment]
@mrameezraja I think I may have misunderstood the sub-sub-root folder part, I'm not sure if that is possible. In essence you want to have 2-level virtual structure. Usually the project in VS is just one folder, so I misunderstood.

**Comment by mrameezraja** [comment]
@Ciantic  currently i am using atom's 'add project folder', but it is confusing in my scenario. I have three projects and they all have root folders with same name. atom is displaying them like 
<pre>
--www
--www
--www
</pre>
I want something like this
<pre>
-- Project 1 (this should not be a real folder.)
----www
-- Project 2
----www
-- Project 3
----www
</pre>

**Comment by Ciantic** [comment]
Oh right. Atom can't do that, but I can see that Atom should allow virtually naming the folders added to window.

**Comment by brendanfalkowski** [comment]
I'd wager multi-folder projects are the exception not the norm. I haven't needed it in any projects, so it's  wasting horizontal space with my whole tree view indented by one level (just to show the parent folder).

It would be nice if single-folder projects didn't show the parent folder, so the tree could hug the left edge.

My apps (Magento) have very deep trees so the sidebar takes quite a lot of space to see the files I'm working on. Would love to reclaim an extra 5mm for the code window when I'm traveling with a small laptop.

**Comment by pgnd** [comment]
Reading above, I _think_ this is a multi-folder use case that fits here ...

For a single folder tree
```
topA
├── foldA1
│   ├── foldA11
│   └── foldA12
└── foldA2
    ├── foldA21
    └── foldA22
topB
├── foldB1
│   ├── foldB11
│   └── foldB12
└── foldA2
    ├── foldB21
    └── foldB22
```

I'd like to add the 'top' *and* nested-subfolders as separate project folders to a single project.

Atm, this works:
```
	atom topA/ topB/foldB1/foldB11
```
where the 2nd item is NOT within the 1st's hierarchy.  Both folders are added to, and appear in, the project.

But, this does NOT work:
```
	atom topA/ topA/foldA1/foldA11
```
where the 2nd item IS within the 1st; it simply fails silently.

**Comment by andyburke** [comment]
Multiple folders need to be sortable, currently they are listed in the order they were added in. That's not intuitive, in my opinion. I think there should be two options:

1) Alphanumeric sorted (default)
2) User-sorted (drag/drop ordering persisted somewhere)

**Comment by jakealger** [comment]
@andyburke +1 - I completely agree. Just tried moving the folders around and came across the same 'complaint'. Other than that, love this editor :)

**Comment by icehawk1** [comment]
@andyburke  +1 I am working on a project were I have one folder per submodule. For certain reasons, they are scatered across multiple parent directories (no I can't move them). 

That means that every time I start working on a new submodule, I remove all the folders from atom, add the new folder and then readd the previously removed folders. Very annoying.

**Comment by paaljoachim** [comment]
Hey I am brand new to Atom. I just tried draging and dropping a folder into the Project view sidebar but that does not work. It seems natural to have something like this included.

**Comment by paaljoachim** [comment]
Regarding multiple folders and files from various places open at once.
I have 5 projects open and once having a way to identify which file belongs to which project is a must.
Some of the files will give a full absolute link. Other files will just say something like: lib/admin/wp-customize.php - not really helpful when I want to know which project it belonged to. If all the bottom urls showed absolute links that would be helpful.

**Comment by michaelbahr92** [comment]
In IntelliJ IDEA there is the feature that sub-directories get automatically until there is a file present. If there is no file in that tree, it's not automatically opened. 

Imagine two files in the following directory structure:

    - path/
    ---- my.txt
    ---- to/
    ------- my/
    ---------- deeply/
    ------------- hidden/
    ---------------- file.txt 

Upon opening `path` we see:

    - path
    ---- my.txt
    ---- to/

Opening `to` then expands the complete branch until `file.txt` is reached.
 
Would love to see that in atom too!

**Comment by thomasjo** [comment]
@michaelbahr92 That's not really related to this issue (which is concerned with multi-folder in the context of projects, i.e. multiple folders here means multiple project roots). However, there is an open PR on the tree-view package that implements (almost exactly) what you want:
https://github.com/atom/tree-view/pull/608

I suggest you subscribe to that PR for updates.

**Comment by tjkohli** [comment]
I second the comments about adding drag and drop of folders into a project.

**Comment by lokesh1729** [comment]
Hi,
I would like to suggest 'Close The Project' feature in atom. It would be like, clicking close the project,  project won't be removed from workspace. If you want to work on it again, just double click on it, it will open(like in eclipse). It is very important because for operations like search,replace etc.. if all projects were included, it would affect the speed and time. I don't find similar feature in atom. I know 'Remove Project Folder' option is there. But, I have to add again if I need it.
is this feature listed in this thread?

**Comment by redVi** [comment]
It would be cool to be able to swap the projects: first place on third, third on first place. I need it because [atom-stylefmt](https://github.com/1000ch/atom-stylefmt/issues) has an error associated with paths to the projects.

<img width="985" alt="multi-project-shift" src="https://cloud.githubusercontent.com/assets/2623486/19218220/ace0ce64-8e1e-11e6-89b1-152f12af35c2.png">

**Comment by grayghostvisuals** [comment]
I'd like to see what was said [here](https://github.com/atom/atom/issues/5728#issuecomment-76510069) but also allow project folders to be draggable into the atom editor at will

**Comment by Ben3eeE** [comment]
> It would also be very helpful it you can drag and drop the order of the root folders / rearrange them.

https://github.com/atom/tree-view/pull/525 just got merged which will allow you to rearrange project folders using drag and drop. Thanks to @forivall for this! 🎉 🎆

**Comment by grayghostvisuals** [comment]
Thanks @forivall

**Comment by moizrazakhtri** [comment]
Windows operating system practically provides a lame way to hide files and folders and that is not enough if you are serious about protecting your private data [Folder lock](https://www.microsoft.com/en-us/store/p/folder-lock-free/9nblggh3m5gq)
