### ISSUE TITLE
delete EOL: remove preceding whitespace of line

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#5734]
In the case where you have the cursor at the end of the line, and press delete to remove then EOL, any whitespace at the beginning of the following line should be removed before it is added to the line where the cursor is on. Perhaps only the bit of whitespace that matches with the start of the line the cursor is in (indentation).
This behaviour would act reversly of when enter is pressed and the newly created line is started with the (indentation) white-space of the preceding line.

**Comment by izuzak** [comment]
> any whitespace at the beginning of the following line should be removed before it is added to the line where the cursor is on.

Can you explain _why_ this should be done? I'm not seeing that behavior in SublimeText, for example, and I'm not sure I understand the motivation.

Also, would using a package which provides this feature be something you'd consider instead of making this a default for all users?

**Comment by 50Wliu** [comment]
No response, and this can be provided in a package, so closing.
