### ISSUE TITLE
Variable UI font-size

### ISSUE THREAD

**Issue by simurai** [atom/atom#5735]
This issue acts as the "umbrella" for everything related to a variable UI font-size. Other related issues: https://github.com/atom/styleguide/pull/25, #4342, #3792,  https://github.com/atom/settings-view/issues/307, https://github.com/atom/atom-dark-ui/issues/24

#### Problem:
Unlike the Syntax font size, there isn't an easy way to change the font size for the UI.

#### Current options:

__1. Styles.less__ Anything can be overridden in `styles.less`. Works great for tweaks in certain areas, but can't really be used to override all font sizes at once.

__2. Themes__ Themes that are based on the `rem/em` units can be scaled by only changing the root element like `html { font-size: 14px; }`. To my knowledge, currently only [isotope-ui](https://atom.io/themes/isotope-ui) supports that.

__3. Zoom__ It's possible to change the zoom level in `init.coffee`:

```coffee
require('web-frame').setZoomFactor(2)
```

[See this discussion](https://discuss.atom.io/t/how-to-set-the-font-for-the-settings-ui-and-the-command-browser/13498/4). Works for all themes, but could have some px rounding issues.

#### Possible improvements (future):

1. Add a way to override Less variables from `styles.less`, themes and in the settings. There was an attempt but needs to be investigated further: https://github.com/atom/atom/pull/4153#issuecomment-73980380 
2. Switch everything to `rem/em` based font units. But this won't happen for 1.0 since it might break existing themes, packages and people's `styles.less`. Maybe for 2.0 if overriding Less variables isn't possible till then.

**Comment by benogle** [comment]
Thanks for pulling all these things together it's definitely a problem. I think maybe we could have a ui font size config option. There are really 2 UI font sizes:

* UI text: tree-view, status-bar, fnr, tabs, etc.
* Pane item content: markdown preview, styleguide, settings view

Maybe we would set an option for one of them, say, UI text, and pane item content text is derivative of that option.

**Comment by simurai** [comment]
>  I think maybe we could have a ui font size config option.

That would be nice, but I think it's tricky to add. It works great for Syntax themes, but only because Syntax themes typically don't define any `font-size`. In UI themes there are many `@font-size`s sprinkled around and if they are set in `px`s, then they can't be easily changed just in one place. Core would have to override themes by inlining the font-size to tree-view, status-bar, tabs, panes etc. which would be kinda hard to maintain.

So maybe for now it still needs to be done either in themes and/or in `styles.less`. Reducing the hard coded `px`s wherever possible, should help a bit.

And then maybe one day it will be possible to override `@font-size` variables in themes, that could also be changed from the settings.

**Comment by simurai** [comment]
Changed the One themes to use `em` units: https://github.com/atom/one-light-ui/pull/10 It lets you target everything or also individual areas.

> There are really 2 UI font sizes:

So you could change them like this:

```less
.workspace { font-size: 12px; } // UI text: tree-view, status-bar, fnr, tabs, etc.
.pane-item { font-size: 14px; } // Pane item content: markdown preview, styleguide, settings view
```

Still have to see how far Core and Packages could be changed without breaking other themes.

**Comment by lee-dohm** [comment]
:tada: Awesome! I would *love* to see this in the original Atom-(Light|Dark) themes too, if possible.

**Comment by braver** [comment]
:+1: It's tricky though, will be watching this.

**Comment by simurai** [comment]
Yep, the Atom themes will probably be more tricky because they are a bit more complex. I might try one day, but no promise. :wink: It's also a bit a rabbit hole, once you start somewhere, you kinda have to change it everywhere.

Anyways.. I updated the description above. So currently people have 3 options, depending on their needs. And then there are 2 options that might happen in the future, but most likely not before 1.0.
