### ISSUE TITLE
Background CPU usage

### ISSUE THREAD

**Issue by mathie** [atom/atom#5736]
I'm running Atom 0.182.0 on Mac OS X 10.10.3. Atom is launched, and with a (Ruby on Rails) project open, but it's in the background while I'm doing something entirely unrelated to it, or the files that it currently has open. (I'm in Safari, submitting a new GitHub issue!) Yet Atom is still chewing through the CPU in the background. iStat Menus is reporting it at ~40% CPU usage on one of the cores.

This is suboptimal because it's reducing my battery life. Last night, sat in front of the TV, my laptop ran through the battery in a couple of hours, when it would normally have lasted much longer.

I realise this isn't a helpful bug report so far. What information can I give you to help turn it into a good bug report?

**Comment by izuzak** [comment]
Thanks for the report, @mathie!

There's already a similar issue about this: https://github.com/atom/atom/issues/3426. Could you share more details in that other issue in a comment? Specifically, is this happening consistently for you? If so, is it happening for all projects or only certain projects? If it occurs consistently for a specific project, could you share a link to its repository so we can try and reproduce? Can you reproduce the problem in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)? It's possible that one of the packages you installed is doing this.

**Comment by izuzak** [comment]
And please let me know if your report is different than that other one so that we can keep this open (and provide more details about in what way it's different). Thanks!
