### ISSUE TITLE
Change "Do you want to quit" buttons

### ISSUE THREAD

**Issue by Phorce** [atom/atom#5737]
Basically, this is quite annoying me. Whenever I go to quite an application the buttons are:

"Save", "Cancel", "Don't Save"

I am so used to having:

"Save", "Don't Save", "Cancel"

From switching from Text Sublime. This problem is slightly annoying as whenever I don't want to save, I end up clicking cancel and having to do the process again. 

Apologies if this has already been brought up!

![annoying](https://cloud.githubusercontent.com/assets/878780/6371609/6a03ad74-bcf5-11e4-8bfd-372e703c0608.png)

**Comment by izuzak** [comment]
@Phorce Changing the button order now might be equally confusing for all users of Atom that are used to the current behavior (and might have never used Sublime). Do you have any suggestions about minimizing impact for these users? 

Also, as far as I can tell, the button order is the same in Atom and Sublime on OSX.

Atom:

![screen shot 2015-02-25 at 15 39 52](https://cloud.githubusercontent.com/assets/38924/6372444/943481b8-bd04-11e4-9d48-74981266431b.png)

Sublime:

![screen shot 2015-02-25 at 15 40 24](https://cloud.githubusercontent.com/assets/38924/6372453/a545716a-bd04-11e4-8e82-ffcdf2f7e98f.png)

It seems that you're using Windows. Is the button order on Windows the same in other apps that you use as well? Could you share a few screenshots which shows these buttons for these other apps (including Sublime) -- that might be useful context in making a decision here. Thanks!

**Comment by Phorce** [comment]
@izuzak 

I've never really noticed it on other operating systems. At work I have to use Windows (Not through choice!) 

So in Microsoft Word (Windows):

![annoying2](https://cloud.githubusercontent.com/assets/878780/6372633/89d76d0e-bcfd-11e4-9f49-4ac7b73653a2.png)

In Notepad (Windows)

![annoying2](https://cloud.githubusercontent.com/assets/878780/6372688/cb4cf902-bcfd-11e4-8b45-ab24d76a23df.png)

There is a lot of application (I'm noticing) that use similar button layouts.

**Comment by izuzak** [comment]
Thanks, @Phorce. If this is the default in most other Windows apps (especially editors), I'd be :+1: on changing the behavior in Atom as well.

**Comment by Phorce** [comment]
@izuzak - Aha! Thanks. It was just that I was working on a project today and found it really annoying when I was just trying to click "Don't save"

**Comment by jimgraham** [comment]
This is an MS design pattern. For example https://msdn.microsoft.com/en-ca/library/windows/apps/hh738363.aspx

 > *  If not specified, the default is the leftmost button.
 > *  Put the safest, most conservative choice on the rightmost position. In the above example, "Block" is the rightmost choice as it is more conservative.

This is the opposite of the Mac.

**Comment by Phorce** [comment]
I think that it should be the same on a PC but obviously leave it for Mac
Linux etc..

I assume that you can edit, this anyway? I have not had chance to grab the
source as of yet but might look into it at the weekend!

**Comment by russlescai** [comment]
:+1: As a native Windows user (and never having used Sublime), I find the current Save,Cancel,Don't Save confusing.

I agree it should be switched to Save, Don't Save, Cancel for Windows.

**Comment by damieng** [comment]
We now use the system UI dialog for this, which appears like this:

![image](https://cloud.githubusercontent.com/assets/118951/15060945/8c00c8ee-12e4-11e6-93ca-28d49a350994.png)
