### ISSUE TITLE
Folding a soft-wrapped line un-soft-wraps the line

### ISSUE THREAD

**Issue by izuzak** [atom/atom#5740]
Taken from https://github.com/atom/atom/pull/5567#issuecomment-75758499.

![3](https://cloud.githubusercontent.com/assets/38924/6350291/c9cb4974-bc32-11e4-9f93-b02e6cc0abfd.gif)

Notice that the paragraphs are soft-wrapped, but after the fold -- the first paragraph is un-soft-wrapped.

**Comment by 50Wliu** [comment]
This appears to be fixed, at least with the editor rewrite.
