### ISSUE TITLE
Debugging JavaScript files by built in debugger

### ISSUE THREAD

**Issue by Trudko** [atom/atom#5742]
Hi :), 

I couldn't find a way how to debug any random javascript file in built in developer tool bar. It is possible to debug packages but not the any other files? What am I missing?

**Comment by Trudko** [comment]
PS: I am also curious if this isn't possible, are there any plans for it?

**Comment by kevinsawicki** [comment]
Currently you can only debug Atom's source code using the dev tools. Either by setting breakpoints or running the source version of Atom and using the `debugger` keyword.

The dev tools does have a pretty extensive API though so you could build a debugger into it and there may be packages that already do that for Atom.

Closing this out.
