### ISSUE TITLE
All scrollbars are missing in entire Atom app

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#5749]
All scrollbars are missing.  This happens even in safe mode.  Now I have to figure out how to go back to 182.

## Versions

* **Atom:**       0.183.0
* **Atom-Shell:** 0.21.0
* **OS:**         Microsoft Windows 8.1 Pro with Media Center
* **Misc**
    * apm  0.141.0
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.9
    * git 1.9.5.msysgit.0
    * visual studio 2013

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.6.2.</small>

**Comment by mark-hahn** [comment]
This also happens when I go back to 182.  I first noticed it last night.  I'll download and check 181.

**Comment by maxbrunsfeld** [comment]
I can't reproduce this on 0.183.

**Comment by mark-hahn** [comment]
OK, now I'm baffled.  It happens even in old versions.  It happens in safe mode.  It happens when storage folder is removed.  I guess I'll remove all of Atom and reinstall.

**Comment by maxbrunsfeld** [comment]
Maybe a package you installed?

**Comment by mark-hahn** [comment]
> I can't reproduce this on 0.183.

I figured as much.  Everyone would notice this quite quickly.  (grin)  Scrollbars work in all my other apps so it's not my windows.  And I tried rebooting.

> Maybe a package you installed?

I don't see how that could affect it with everything I've tried.  A fresh install should do it.

**Comment by kevinsawicki** [comment]
Nothing in your ~/.atom/styles.less file? That file still gets loaded in safe mode still I believe

**Comment by mark-hahn** [comment]
This looks suspicious but I haven't change the file since way before this problem ...

```
.scrollbars-visible-always /deep/ ::-webkit-scrollbar {
  width:17px;
}
```

**Comment by mark-hahn** [comment]
It works now.

I did a complete uninstall and a fresh install of 184.  When it started up squirrel said install failed but then a fresh atom started fine.  I loaded a largish file and the problem was still there I went to settings, changed the themes, and when I went back to the text file it was working.  After reloading Atom it still works.

My guess is that a rare chrome bug showed itself.  I can't think of any other possible cause.  I googled the symptoms but nothing came up.

A programmer friend of mine once said "once a fluke, twice a bug".  (grin)

Now t reload my config and packages and cross my fingers.

**Comment by mark-hahn** [comment]
Putting config files back in broke it.  At least I can now find out what is causing it by bisecting the config files.

**Comment by mark-hahn** [comment]
It turns out it was the style.less code after all.  Here it is again ...

```
.scrollbars-visible-always /deep/ ::-webkit-scrollbar {
  width:17px;
}
```
I don't see anything wrong with it.  Also it has been in there for weeks.  Oh well.

If anyone has any ideas it would be nice to know how setting the scrollbar's width could make them disappear.

**Comment by olsonpm** [comment]
I ran into this exact issue just now and resolved it by increasing the scrollbar container width.  From my testing you need to set the container to one pixel higher than the width of the scrollbar.  I wanted to set my scrollbar width to 16px so the below worked for me.

```less
.scroll-view > .vertical-scrollbar {
  width: 17px !important;

  > div {
    width: 17px !important;
  }
}

.scrollbars-visible-always ::-webkit-scrollbar {
  width: 16px;
}
```

**Comment by ilievZlatko** [comment]
This only happens on windows! I have it installed both on linux, mac and windows and the only system I have issues with atom is windows! I have the same packages on all the systems. My guess was that nuclide is causing the problem, after I uninstalled it, the problem is still there!
