### ISSUE TITLE
Files don't open from explorer after updating

### ISSUE THREAD

**Issue by ArtskydJ** [atom/atom#5752]
Using Atom 0.183.0 on Windows 7 x64.

After atom updates, I become unable to double click files and have them open. The command line still works fine.

To fix:

1. Open `regedit.exe`
2. Navigate to `HKEY_CLASSES_ROOT\Applications\atom.exe`
3. Right-click `(Default)`, click `Modify...`
4. Modify the text from `C:\Users\Michael\AppData\Local\atom\app-0.181.0\atom.exe` to `C:\Users\Michael\AppData\Local\atom\app-0.183.0\atom.exe`
5. Close `regedit.exe`
6. Close and reopen `explorer.exe`
7. Double clicking files works again!

Could this registry item be updated when atom is updated?

**Comment by 50Wliu** [comment]
Duplicate of #4893, please subscribe there for updates.
