### ISSUE TITLE
Atom 0.182.0 tree-view contain multiple root directories bugs.

### ISSUE THREAD

**Issue by summer1988** [atom/atom#5757]
Atom's tree-view can now contain multiple root directories,
But the other root directories can't be parsed like the first root directories,
They lost git features....

**Comment by 50Wliu** [comment]
This is most likely because packages have yet to update for the new behavior.
Could you please elaborate a bit on the bugs you're experiencing?  Do they still occur after you've updated all your packages (and Atom version to 0.184.0)?

**Comment by summer1988** [comment]
Thanks a lot!
I update to the newest version 0.184.0,
It's ok now.
