### ISSUE TITLE
Uncaught exception, complete crash (dumpfile attached)

### ISSUE THREAD

**Issue by simonjosefsson** [atom/atom#5761]
Atom 0.182.0 on win 8.1
I was deleting a file and think I managed to double tap the delete button.
Atom froze on the second(?) dialog window and crashed hard (took all 4 atom instances with it)

I was promted to open the debugger in Visual Studio but couldn't see much without the symbols.
Uploaded the dumpfile to my dropbox (250 mb), let me know if it's of any use.
I'll leave it here for a week or so: https://www.dropbox.com/s/8iurkz770qv1ha8/atom.dmp?dl=0

**Comment by benogle** [comment]
cc @zcbenz

**Comment by damieng** [comment]
Haven't seen any reports of this in the 1+ year since this was file and I'm not able to repro it. Closing but feel free to comment if you run into it.
