### ISSUE TITLE
Atom stuck indexing files

### ISSUE THREAD

**Issue by nathancooper** [atom/atom#5769]
I'm using Atom (0.184.0) on OS X (10.10.2). Since that update when I press CMD+T to open a file, Atom begins indexing the project and stops at 22,700, see screenshot. Since indexing hasn't finished I can't use the shortcut to open a file.
![atom indexing project](https://cloud.githubusercontent.com/assets/319205/6399216/ded7b040-bda5-11e4-9b36-74cc6c677009.png)

Edit: This happens even after disabling all community packages and restarting.

**Comment by maxbrunsfeld** [comment]
Can you report the output of this command in the console while this command is running?

```javascript
atom.project.getPaths()
```

**Comment by nathancooper** [comment]
The path:
["/Users/Nathan/Brightmd"]

Output:
25401

**Comment by maxbrunsfeld** [comment]
That's a lot of files. Does this happen for any directory, or just when you open your home directory?

**Comment by nathancooper** [comment]
It is just the home directory. I don't need to open the parent directory for project I'm working on, but I guess I've been doing so out of (bad) habit.

**Comment by izuzak** [comment]
Similar report: https://github.com/atom/fuzzy-finder/issues/76

**Comment by ylansegal** [comment]
It is also getting stuck for me at 2,700. 

```
$ find . -type f | wc -l
    3473
```

**Comment by ylansegal** [comment]
Ignore my previews comment... it's because of  .zeus.sock mentioned in https://github.com/atom/fuzzy-finder/issues/76

**Comment by izuzak** [comment]
@nathancooper Can you still reproduce this problem in Atom 0.186.0?

**Comment by nathancooper** [comment]
@izuzak No, it is working for me now, thanks.

**Comment by zcbenz** [comment]
I think it is still happening, steps to reproduce:

1. `git clone https://github.com/atom/atom-shell.git`
2. Open the folder and `Cmd+T`
3. Indexing stuck at 500.

**Comment by maxbrunsfeld** [comment]
:anguished: Fixed. Thanks @zcbenz.

**Comment by maherbeg** [comment]
This is happening to me on 0.191. Thoughts here?

**Comment by 50Wliu** [comment]
@maherbeg please try updating to 0.192.0.  There was an issue with symlinks that broke the fuzzy finder in 0.191.0.

**Comment by fishermand46** [comment]
Can confirm. I was having this problem on 0.191.0 and updating to 0.192.0 fixed it. Thanks @maherbeg!

**Comment by hraban** [comment]
in case anyone else stumbles upon this issue: I encountered it because I accidentally had "Volumes" (mac os x name for "this computer" sort of) in my project. It was indexing all drives.
