### ISSUE TITLE
Do something about UI pause when switching themes

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#5774]
Currently, when you switch themes in the settings view, there's no visual feedback and (at least in my case) the UI seems to briefly pause while it recomputes the styles. We could attack this a few ways, like;
- A spinner in the Themes section of the settings view
- A 30% opacity overlay  with a message over the _whole window_ while styles are recomputed (drastic, but changing the theme is a relatively drastic action that users won't do often)
- other?

**Comment by benogle** [comment]
A spinner wont work. It will lock up as it is on the same thread as the style recomputation. 

Some kind of overlay with a message might be nice though.

**Comment by mnquintana** [comment]
In addition to the ideas above, I think it would be a nice touch if there were a transition between themes (ie. some kind of animation) to make the changes less jarring and more smooth.
