### ISSUE TITLE
Why not "npm install -g atom" ?

### ISSUE THREAD

**Issue by naholyr** [atom/atom#5782]
I've not digged into build procedure yet, but it looks like depending only on node-related technologies, which is why I wonder why the build process is not a simple `npm install`.

What would we gain?

* `npm install -g atom` as an alternative way of installing, easier, maybe slower (gyp compilation being made at install time)
* for those who install from source, `npm link` from the source folder and *voila* your editor is installed globally and automatically updated when you rebuild your source folder

Is that something possible?

**Comment by batjko** [comment]
Well, it's a rich client application that people are supposed to be able to install without having node/npm installed as a prerequisite. 

However, for those who'd like this kind of thing... there's nothing to stop anyone from creating such an npm package, I suppose?

**Comment by naholyr** [comment]
Of course I think about this as an alternative install. I was about to install from source and I didn't understand why there was such steps as calling a "build" script from two distinct folders with `package.json`, it feels very weird but there may be a real reason for that. I'll take a look if noone confirms there is no way to do it ^^

**Comment by mark-hahn** [comment]
The node (ioJS) is customized so I don't see how this could work.

On Fri, Feb 27, 2015 at 3:14 AM, Nicolas Chambrier <notifications@github.com

**Comment by kevinsawicki** [comment]
This is definitely possible but not something we will currently pursue since the app automatically updates itself vs. having to manually update using `npm`.

So I'm going to close this out.
