### ISSUE TITLE
Close atom without save file, and keep change in file

### ISSUE THREAD

**Issue by NamPNQ** [atom/atom#5783]
How to close atom without save file like sublime text?

**Comment by lee-dohm** [comment]
If you open a directory in Atom, then when you exit Atom if you select Don't Save ... the next time you open Atom from that directory, the file will be there with the changes. This assumes that you use the standard Atom workflow. If you don't, then there are already issues covering this: #942 #4161 et al.

**Comment by mark-hahn** [comment]
Check out the package `saveallthetime`.

**Comment by NamPNQ** [comment]
#942 , the future i need, tks @lee-dohm
