### ISSUE TITLE
Feature Request: search history

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#5784]
What I miss in Atom which I remember from some other editor(s), is that the 'search' text box of the find dialog, has a drop-down-arrow (or combo-box or what to call it) with a list of the _x_ most recent entries you've searched for.

**Comment by batjko** [comment]
That's a neat idea.
Worthwhile adding this request to the [find-and-replace package](https://github.com/atom/find-and-replace/issues).

**Comment by stijnsanders** [comment]
Also I just found out you can scroll through this history by pressing up and down... So I can either cancel this issue, or stipulate that a visual display in list-form is missing.
