### ISSUE TITLE
Select all very slow when lots of folded content

### ISSUE THREAD

**Issue by mMerlin** [atom/atom#5791]
Doing &lt;ctrl>a to select the complete buffer, when most of the content is hidden in folded sections is very slow, and it unfolds everything.

I do not see why either of those should happen.

I do this regularly with some javascript files.  I start with everything folded, expand a small section, make changes, then select / copy the whole buffer to paste into jslint.com.  I have not gotten around to installing the jslint package.

**Comment by jt3k** [comment]
+1 code-mirror is very slowwwwwwwww

**Comment by izuzak** [comment]
I could reproduce this on ~half of [jQuery's source](http://code.jquery.com/jquery-1.11.2.js). Copy/pasted the top half into Atom, executed `Editor: fold all`, executed `Core: select all`. I think it took ~8 seconds for everything to get selected, and also all folds were unfolded. Executing `Core: select all` was instant with all folds unfolded. 

/cc @nathansobo @as-cii who are interested in these kinds of things :racehorse:
