### ISSUE TITLE
Feature Request -- Ability to open new files straight into a new pane

### ISSUE THREAD

**Issue by bobber205** [atom/atom#5792]
I really like having different panes but that aren't very friendly to the keyboard.

For example if I want to open a new file into a split right pane, I have to open an EXISTING file into the pane, have two copies of it open long enough for me to CLICK into the new file then open the file I want on the right side of my screen. Then I close the duplicate file that allowed me to have the pane open in the first place. 

Alot of effort.

I'd love the ability to open a new pane at least from the Fuzzy File Finder, something like maybe an alt-enter or command+1 for "Open in nth pane" would be such a huge improvement.

**Comment by benogle** [comment]
Here's what I do

```
cmd-t
...find file
ctrl-shift-\
```

Then move focus between panes with `cmd-option-up`

I also have https://github.com/santip/move-panes installed which is a huge help.
