### ISSUE TITLE
Failed to load config.cson / [stdin]:1:1 error: unexpected, config.cson filled with whitespaces

### ISSUE THREAD

**Issue by carstenhag** [atom/atom#5793]
![0](http://i.imgur.com/DqXICg5.png)

```
Windows 10 Build 9926
Atom version 0.182.0

Community Packages:
atom-lint
minimap
recent-files
recent-projects
```

The contents of the file are exactly 238 whitespaces. I have no idea why it's that, I didn't modify anything on my own.

**Comment by Moter8** [comment]
Fix: Remove the config.cson file and it gets generated again on startup.

**Comment by kevinsawicki** [comment]
Would it be possible to include the exact contents of the file in a comment here?

**Comment by kevinsawicki** [comment]
Was all the whitespace on the same line or broken across multiple lines?

**Comment by mark-hahn** [comment]
> Would it be possible to include the exact contents of the file in a comment here?

Off-topic:  I haven't been able to add file attachments to these issues.  Am I missing something?

**Comment by izuzak** [comment]
> Off-topic: I haven't been able to add file attachments to these issues. Am I missing something?

You're not -- currently, it's not possible to add file attachments on GitHub issues. You can only upload images. A workaround is to include the contents inline in a code block or create a gist and link to it.

**Comment by Moter8** [comment]
@kevinsawicki All the whitespace were in one line.

**Comment by Uter1007** [comment]
I tried to delete it but the error still occures. Can you provide a guilty config + instruction where to store the file ?

**Comment by pixelchutes** [comment]
Just installed Atom (v0.189.0) for the first time on this particular system (OS X 10.10.2), and with the very first launch, the first thing I see on Welcome Guide pane:

> Failed to load `config.cson`
>```
[stdin]:4:13: error: literal is not a function
  'themes': [
            ^
```

![welcome_guide_-_atom](https://cloud.githubusercontent.com/assets/352182/6957501/fa79bd10-d8b8-11e4-98b1-fdd6d1640fa9.jpg)

`Contents/Resources/app/dot-atom/config.cson`:
```coffee
'editor':
  'fontSize': 16
'core':
  'themes': [
    'one-dark-ui'
    'one-dark-syntax'
  ]
```

**Comment by Moter8** [comment]
@pixelchutes That is probably another bug. My Config got killed by something. Yours still exists.

**Comment by vector-web** [comment]
Close the atom. Open config.cson, for example, using notepad ++. Clear the contents of the file. Save. And open the atom.

**Comment by fanel** [comment]
I removed that file and restart Atom. Now all works fine. Atom generates a new one. Thx

**Comment by Huthaifah-kholi** [comment]
How we can remove it ?

**Comment by Zireael07** [comment]
The same way we can remove any other file from the computer.

**Comment by Huthaifah-kholi** [comment]
what is the directory for this file ?

**Comment by 50Wliu** [comment]
`~/.atom/config.cson` on Mac and Linux, `%USERPROFILE%\.atom\config.cson` on Windows.

**Comment by ericonetto** [comment]
<b>To developers, a suggestion:</b> Later with time would be great to have a self healing function. In this case for example, the tool would detect the error (code) and try to solve it by an automatic scritpt or something else that employs the solution deleting the file (in this case)

**Comment by go-oilers** [comment]
removed it i had two instances of the same file i deleted both and it fixed the problem.......thanks alot

**Comment by Tomgroot** [comment]
I have the feeling that this error comes up if Atom is closed too abrupt. My computer got a BSOD and since then I got this error.
