### ISSUE TITLE
Atom installer creates a ridiculous number of temporary files

### ISSUE THREAD

**Issue by Quantum64** [atom/atom#5797]
All of these files are 0 bytes in size, and lead to major system instability, as they pile up over time, and are never deleted.  After one install, there were 31,458 leftover temp files.

Install Log: https://gist.github.com/Quantum64/228eb1704fe7e83c4d1d

![c91a0cdf421753a27932ee0d216dad4e](https://cloud.githubusercontent.com/assets/3969183/6424631/e6c40662-bece-11e4-92ff-db9a171ece1a.png)

Running OS Windows 10 Build 9926

/cc @paulcbetts #5671

**Comment by Zireael07** [comment]
Can't you delete them manually or does it lead to problems?

Going to check if there are any on my Win7.

**Comment by 50Wliu** [comment]
Refs #5772.

**Comment by 50Wliu** [comment]
Refs #5767.

**Comment by Quantum64** [comment]
@Zireael07 It leads to major problems when too many files pile up, such as Atom not working, programs refusing to open files, some programs not working at all, and Windows update failing.

**Comment by paulcbetts** [comment]
I think this is because of NuGet's "OptimizedZipPackage" class. I think we just need to ditch that class and unzip the package ourselves, instead of trusting NuGet to not suck

**Comment by paulcbetts** [comment]
Note that this situation will *vastly* improve even with no changes to Squirrel, if/when Atom moves to ASAR

**Comment by Zireael07** [comment]
@Quantum64: I know what happens when too many files pile up. I was asking if they can be deleted safely.

Turns out they can - I had 6+ 0 KB files left after Atom install and two updates, deleted them and no problems occurred.

**Comment by Quantum64** [comment]
@Zireael07 They can be deleted, but they should be deleted automatically, and these kinds of problems can be hard to troubleshoot for general users.  Also several gigabytes of files are left in the temp/nuget folder.

**Comment by paulcbetts** [comment]
This bug should be fixed in the next release of Squirrel

**Comment by Quantum64** [comment]
Awesome, you can close this issue if you want then.

**Comment by paulcbetts** [comment]
@Quantum64 We'll make sure to get it into a release then we can kill it. Thanks for filing the bug

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/atom/commit/00023709d3a3652aafb96bcfb4803c735bed98df
