### ISSUE TITLE
Disorganised files relating to numbered file names regardless of windows folder organisation.

### ISSUE THREAD

**Issue by Schnarfengargle123** [atom/atom#5798]
The folder display on the left hand side of atom has a bug where files are not displayed properly in order of name. I have 10 files named 1-10 and where file 2 should be, the file named 10 is in it's place. I have added a file named 40 and the files are now displayed like this:

1
10
2
3
4
40
5
6
7
8
9

**Comment by 50Wliu** [comment]
I'm assuming you're on Windows?
I think Mac and Linux organize files by looking at the first letter, then the second, etc. while Windows does it alphanumerically-can someone confirm this?

**Comment by batjko** [comment]
I just tried it out and Windows Explorer sorts properly according to numeric values, if the filenames are just that:
![image](https://cloud.githubusercontent.com/assets/7287076/6427638/fb15c9d4-bf7d-11e4-9868-8448042fac14.png)

While Atom takes them as Strings:
![image](https://cloud.githubusercontent.com/assets/7287076/6427642/1a11c720-bf7e-11e4-89d2-09685ee196ea.png)

**Comment by lee-dohm** [comment]
This issue was moved to atom/tree-view#391
