### ISSUE TITLE
In RDP Session Text Cursor is not visible because it is black

### ISSUE THREAD

**Issue by meanbunny** [atom/atom#5799]
Hey All,

Just want to say that ATOM is awesome! I am having the following issue where I use ATOM in an RDP environment. When moving the mouse into the editor portion of ATOM it completely disappears, if you type some text into the editor and try to move the mouse over the text it is still visible, just black. Once you move the cursor up to the tabs, it shows up again as a white pointer. Is it possible to fix this?

Windows 8.1
RDP 7
ATOM - .184.0

Thanks!

**Comment by lee-dohm** [comment]
You might try my [white-cursor package](https://atom.io/packages/white-cursor) to see if it can fix this.

**Comment by mark-hahn** [comment]
I'm using it through RDP with a light theme with no problem.

**Comment by batjko** [comment]
Sounds more like a problem with the way your RDP session renders the window content. Is it on low color depth or low refresh rate by any chance?

**Comment by meanbunny** [comment]
@lee-dohm that fixed it!
