### ISSUE TITLE
Settings flash when checking/unchecking an option

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#5800]
Pretty sure this belongs here and not in settings-view.  Atom 0.184.0 safe mode on Ubuntu 14.10.

![flash](https://cloud.githubusercontent.com/assets/2766036/6429001/a6976cba-bf86-11e4-8c37-88a5f50d7adf.gif)

**Comment by lee-dohm** [comment]
Looks like it might be due to the menu bar changing state? On OS X, I don't have that setting and other settings don't repro the issue you're showing.

**Comment by 50Wliu** [comment]
It happens with any checkbox (and maybe even strings but I can't reproduce that right now).

**Comment by Zireael07** [comment]
I'm not seeing it with 0.184.0 in Win7 with a default (dark) UI theme.

**Comment by mnquintana** [comment]
Hmm, I can't reproduce this in Ubuntu 14.04.

**Comment by 50Wliu** [comment]
Still happening for me on 0.186.0 :(.  I wonder if it's something to do with my graphics card then?

**Comment by Zireael07** [comment]
What is your UI theme? Maybe the theme is bugged?

**Comment by 50Wliu** [comment]
One Light.

...and I can't reproduce it anymore.  Hopefully it won't come back.
