### ISSUE TITLE
atom need to add a command

### ISSUE THREAD

**Issue by netmou** [atom/atom#5807]
both treeveiw'popmenu and menu-file need to add "create(new) root folder"

**Comment by netmou** [comment]
rename "add root folder" to  "open root folder"  feel better

**Comment by izuzak** [comment]
> both treeveiw'popmenu and menu-file need to add "create(new) root folder"

@netmou Can you clarify what this command would do exactly?

> rename "add root folder" to "open root folder" feel better

I'm not sure. "Open root folder" might be interpreted as "open another root folder and replace the current root folder with the new one". The current wording makes it clear that something will be added, not replaced.

**Comment by thomasjo** [comment]
> both treeveiw'popmenu and menu-file need to add "create(new) root folder"
> @netmou Can you clarify what this command would do exactly?

Just guessing, but I'm assuming @netmou wants to create a new folder somewhere, and add it as a root folder to the project.

**Comment by mehcode** [comment]
> rename "add root folder" to "open root folder" feel better

That is being discussed over on #5728.
> Renaming Add root folder to Add folder
> Renaming Add folder to New folder (and ditto with Add file)

------------------

> both treeveiw'popmenu and menu-file need to add "create(new) root folder"

This sounds problematic (If I'm interpreting this as @thomasjo explains above); where does the new root folder get created? I'd rather rely on a "New Folder" command to be present in the "select a folder" OS dialog that comes up  when adding a root folder.

**Comment by netmou** [comment]
add a new project ,you must create a folder by OS command ,then use ''add root folder" to open  in Atom.why not  do this  in one step by a "create(new) root folder".

**Comment by izuzak** [comment]
> > rename "add root folder" to "open root folder" feel better

> That is being discussed over on #5728.

Thanks. @mehcode. Since it's already being discussed there, let's not discuss it in two places. @netmou -- please feel free to add a comment to that issue if you have any feedback.

> add a new project ,you must create a folder by OS command ,then use ''add root folder" to open in Atom.why not do this in one step by a "create(new) root folder".

If I understood your explanation correctly, this seems like it should be opened on the https://github.com/atom/tree-view package. Can you open an issue over there and clearly explain what the command should do, where it should be available and what the motivation for it is? Thanks, and let me know if I misunderstood anything.
