### ISSUE TITLE
copy multi line selection to external application

### ISSUE THREAD

**Issue by papermoon1978** [atom/atom#5808]
When copying a multi line selection to another application, the line breaks are removed. Is this intended?

![atom](https://cloud.githubusercontent.com/assets/4062007/6437266/8b7ded96-c0bc-11e4-9095-c28f3a8534e5.gif)

**Comment by papermoon1978** [comment]
Should have tested this more before submitting ... Well, the line breaks remain when I paste this into winword, pspad and vim but the line breaks are removed then I paste this into notepad. Really who used notepad? ;-)  But when I copy a multi line block selection from vim into notepad, the line breaks also remain.

**Comment by mark-hahn** [comment]
I assume it's a line ending problem.  You must be getting unix endings
which notepad cannot handle.

**Comment by papermoon1978** [comment]
Yes you are right. I'm getting LF

**Comment by 50Wliu** [comment]
In that case I'm going to close this.
The issue that's tracking the ability to convert line endings is at #2822 if you're interested.
