### ISSUE TITLE
Add method for packages to extend command-line interface

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#5810]
I see a lot of issues and suggestions around people wanting new command-line options. It would be great if people could write their own command-line option handler. Perhaps something like this:
- keymaps
- lib
- options
  - standalone.coffee
- spec
- styles

`standalone.coffee` contains:

``` coffee
module.exports = (arg) ->
  # Do something with the argument here
```

See: 
- https://github.com/atom/atom/issues/1433#issuecomment-76732628
- https://discuss.atom.io/t/add-z-command-line-option-to-ignore-next-parameter/13879

**Comment by izuzak** [comment]
@lee-dohm Could you share more details and add an example + motivation?

**Comment by lee-dohm** [comment]
Yeah, sorry ... I accidentally hit <kbd>ENTER</kbd> and was typing all that out :laughing:

**Comment by izuzak** [comment]
:+1: Thanks, should have guessed that :smile:
