### ISSUE TITLE
Multiple Atom instances

### ISSUE THREAD

**Issue by TheChymera** [atom/atom#5815]
I want to work on different repositories at the same time. I heard that the tree-view is displayed only for the active folder, which indeed seems to be the case. 

Given that behaviour, I can't browse outside the repository from which I launched atom in that atom instance. Instead, I tried to launch a new instance from another repo. This, however, simply adds that file to the already open instance, but does not give me tree-view for the second repo.

So, how can I:

* launch two parallel instances of atom
OR
* switch the tree-view along with the file I am editing within one instance.

If both are possible, which one would you recommend?

**Comment by 50Wliu** [comment]
Have you tried out the new "Add Root Folder" command?  After you open up the initial folder right-click on the tree view and try that.

**Comment by TheChymera** [comment]
Due to the webkit-hidpi bug, I cannot really see the entries when I right-click. Is there any shortcut key for this? As far as I can tell, right-clicking the tree view gives me a number of options, of which, the only one similar to the one you specified is called `Add Folder` - that one creates a subdirectory in my repository. This is not what I want, I want to be able to browse another already existing repository.

**Comment by mehcode** [comment]
@TheChymera Over here (on linux) "Add Root Folder" is the 13th option from the top, 7th from the bottom.

No short-cut for it but `Ctrl+Shift+P` and searching for "Add Root Folder" will find it.

**Comment by 50Wliu** [comment]
@TheChymera make sure you're on at least Atom 0.182.0.

**Comment by TheChymera** [comment]
ok, that was the issue, I was on `atom-0.177.0`. Now I updated to `0.184.0` and it works!

Still, it would be more seamless if atom did this automatically when I launched it a second time pointing at a file in another repo. Can you do this?

**Comment by 50Wliu** [comment]
@TheChymera could you please comment on #5728 about that?
Since this issue seems to be resolved I'm going to close this.
