### ISSUE TITLE
Select range for paired brackets on double click

### ISSUE THREAD

**Issue by KylePDavis** [atom/atom#5817]
It would be great if double-clicking a paired token (bracket, brace, paren, quote, back-ticks, slash, etc.) selected to the other associated token, inclusively.

Here are a couple of examples of things that do this that I use frequently:
* `Terminal.app` in Mac OS X
* [ACE](https://github.com/ajaxorg/ace/) editor

**Comment by izuzak** [comment]
This issue was moved to atom/bracket-matcher#114
