### ISSUE TITLE
Incorrect highlighting of corresponding start and end tags

### ISSUE THREAD

**Issue by turingmaechtig** [atom/atom#5819]
The following programming style is often used in systems like Wordpress:
![screen shot 2015-03-03 at 14 44 09](https://cloud.githubusercontent.com/assets/3964073/6463587/d2c45a4e-c1b3-11e4-8a14-877aed3f0191.png)
The opening php tag is directly after the HTML element name without a space. As you can see in the screenshot, this seams to confuse the highlighting mechanism. As a result the correct corresponding start tag of the last div is not highlighted:
![screen shot 2015-03-03 at 14 44 55](https://cloud.githubusercontent.com/assets/3964073/6463592/e7e379fa-c1b3-11e4-83c2-0bc1399b1e54.png)

**Comment by izuzak** [comment]
This issue was moved to atom/bracket-matcher#113
