### ISSUE TITLE
Close startup untitled buffer on opening another file

### ISSUE THREAD

**Issue by jazzpi** [atom/atom#5820]
When Atom is opened, an "untitled" buffer is created. This makes sense.

However, most of the time, after opening Atom, I then proceed to opening the files I want to edit. At this point, the "untitled" tab remains open even if I haven't changed anything in it.

This is slightly annoying, because it means I have to close a tab that I never wanted in the beginning.

**Comment by Zireael07** [comment]
Good point.

**Comment by 50Wliu** [comment]
This is exactly the behavior that I'd like :smile:.

Refs #4573.

**Comment by MatthewSteen** [comment]
+1 (as of v0.187)

**Comment by 50Wliu** [comment]
Fixed starting in 0.206.0 thanks to the new Use Preview Tabs option in the Tabs package.

>Atom now has built-in support for preview tabs. Check the `Use Preview Tabs` option from the **Tabs** package settings to enable. Tabs will be reused across opened files unless they are edited or double clicked. You can also run `tabs:keep-preview-tab` from the Command Palette to retain the tab.

**Comment by jazzpi** [comment]
Not sure if this is really a fix, since I don't want to enable Preview Tabs in general.
I'm sure there's some relatively easy fix to put in your init script with this though, so if I find one, I'll post it here.
