### ISSUE TITLE
Typo - Welcome guide -  Customize the styling - button

### ISSUE THREAD

**Issue by brantunger** [atom/atom#5822]
**Version:** Atom 0.184.0
**On:** Linux Ubuntu 14.10 64-bit
**Description:** There is a typo on the button label in the welcome guide.

Reproduce: 
  1. Open the welcome guide
  2. Expand 'Customize the Styling'
  3. Use your eyeballs to examine the button label

*'Open your Styleshet'* **should be** *'Open your Stylesheet'*

![untitled](https://cloud.githubusercontent.com/assets/6444186/6468274/3f1e1874-c191-11e4-897a-a35b811cd6a4.png)

**Comment by izuzak** [comment]
Thanks for the report! This was already fixed in https://github.com/atom/welcome/pull/25 -- you'll see it in Atom 0.185.0 (once it's released).
