### ISSUE TITLE
Quitting with an unsaved document doesn't allow you to refer back to the document

### ISSUE THREAD

**Issue by ttufts** [atom/atom#5823]
On OS X, if you quit Atom and have an unsaved untitled document, it will prompt you to save it. The 'Cancel' option does not stop the Quit, it just quits the application without letting you refer back to the document. There is no way to go back and look at the unsaved document so that you can save it appropriately. This forces me to save 'unknown.txt' to my desktop whenever this happens and then go and open the file, look at its contents, and then decide whether to keep it, rename it, or move it somewhere else.

**Comment by 50Wliu** [comment]
Sounds like a bug to me.  What version of Atom is this?  Can you reproduce in safe mode (`atom --safe`)?

**Comment by ttufts** [comment]
Just tested. Bug only exists in non-safe mode. Safe mode doesn't have this
issue.

**Comment by ttufts** [comment]
Version 0.184.0 (0.184.0)

**Comment by 50Wliu** [comment]
In that case, it's one of your packages causing the problem.  Try out @mark-hahn's [package-cop](https://atom.io/packages/package-cop) package to find out exactly which one is causing your problem.
