### ISSUE TITLE
Code zooming doesn't work if shortcut is pressed with very short gap

### ISSUE THREAD

**Issue by mebjas** [atom/atom#5827]
Not a very harmful bug, though worth mentioning:
Behavior: shortcut `cmd` + `+` /  `-` if pressed in very small timegap, it doesn't perform expected behavior. Text size remains same in such situation.

Expected behavior: whatever interval the gap be, the font size should decrease / increase corresponding to the key press.

Steps to reproduce: press `cmd` + `+` successively very fast
Tested on: OS X 10.10, atom `v0.184.0`

**Comment by izuzak** [comment]
I think you're describing this issue: https://github.com/atom/atom/issues/5771. Could you take a look and close this on if it's a duplicate? Thanks!

**Comment by mebjas** [comment]
Yeah its the same w/o animated gif..., this one can be closed!

**Comment by izuzak** [comment]
Cool, thanks!
