### ISSUE TITLE
"Close Tab" menu item is enabled when no tabs are open

### ISSUE THREAD

**Issue by oclbdk** [atom/atom#5840]
Steps to reproduce:
1. Open a project
2. Close all the tabs
3. Select the menu item File > Close Tab

Selecting the menu item does nothing. I expect it to be disabled.

**Comment by kumarrishav** [comment]
@oclbdk  I want to work on this issue. But i am a newbie contributor and this is my first bug. Can you help me on this like who to build the development atom for debugging perpose and where the code exist for this.

**Comment by benogle** [comment]
@kumarrishav The menu item is defined in [menus/darwin.cson](https://github.com/atom/atom/blob/master/menus/darwin.cson#L43), but menu items are not easy to hide and show. It's probably not a good first bug as this kind of thing is throughout atom and would require potentially some new APIs to handle menu manipulation. 

If you're looking for things to do, we have a [help wanted](https://github.com/atom/atom/labels/help%20wanted) label where we put things we may not get to for a while.
