### ISSUE TITLE
unexpected naming a copied file

### ISSUE THREAD

**Issue by kirrie** [atom/atom#5848]
in the tree menu on left window, i copied a file with ctrl + c / ctrl + v.

<b>a.js -> a0.js</b> is ok.
but, <b>a.b.js -> a0.b</b> is not what i expected. i expected 'a.b0.js'.

i'm using 0.186.0 version of atom.

**Comment by 50Wliu** [comment]
Confirmed.

**Comment by izuzak** [comment]
This issue was moved to atom/tree-view#397

**Comment by izuzak** [comment]
Seems related to [this part of Tree View](https://github.com/atom/tree-view/blob/0644f560d08d99c938176e0b684ef2cdacf8bbca/lib/tree-view.coffee#L573-L579), so moved it over there.
