### ISSUE TITLE
Uncaught Your ghci path is not valid

### ISSUE THREAD

**Issue by berglar** [atom/atom#5849]
[Enter steps to reproduce below:]

1. create tidal file by making a new file with .tidal
2. Packages > Tidal > boot tidal (on empty file)

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Your ghci path is not valid

```
At /Users/FatBoySlim/.atom/packages/tidal/lib/repl.coffee:38

undefined
```

### Commands

```
  2x -2:00.5 command-palette:toggle (atom-text-editor.editor)
 14x -1:52.1 core:backspace (atom-text-editor.editor.mini)
     -1:28.7 core:confirm (atom-text-editor.editor.mini)
     -0:44.8 core:save (atom-text-editor.editor.is-focused)
     -0:00.9 tidal:boot (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
tidal, v0.6.2

# Dev
No dev packages
```

**Comment by berglar** [comment]
addressed by switching ghcd path to usr/bin (as opposed to default set in atom). not usr/local because of my brew setup.

**Comment by thomasjo** [comment]
Closing since this seems have been resolved. Regardless, this should have been reported on https://github.com/seansay/atom-tidal.

**Comment by berglar** [comment]
@thomasjo I just posted the issue where Atom led me. It auto-created this issue so probably that link should be updated.

**Comment by thomasjo** [comment]
@berglar Agreed! Been seeing a lot of incorrectly targeted issues, and it's not the fault of the users reporting the bugs.

**Comment by benogle** [comment]
Hey Larisa! This particular case of misdirection should be handled in the
latest atom version. This error doesn't have a stack, so the notification
will now look in the origination url when there is no stack.

**Comment by berglar** [comment]
@benogle oh cool i will update :)
