### ISSUE TITLE
Saving problems.

### ISSUE THREAD

**Issue by peterbotta92** [atom/atom#5860]
I want to save my document, and nothing happens. Atom says, it's already saved (the little blue circle doesn't shown.) But if i check my file in cli with vim, i see the file wasn't saved.

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode (`atom --safe`)? What OS are you running?

**Comment by peterbotta92** [comment]
thanks, trying. Running on mac os x Yosemite

**Comment by mnquintana** [comment]
Did you manage to reproduce this in safe mode?

**Comment by mnquintana** [comment]
Gonna close this out - feel free to comment / reopen if you can reproduce this in safe mode with the latest version of Atom.
