### ISSUE TITLE
Error: Cannot find module '../build/Release/keyboard-layout-observer.node'

### ISSUE THREAD

**Issue by RainbowDashDC** [atom/atom#5865]
Version: b6d6fb4 (master)
OS: `Linux HP-NONE 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux`
NODE: `iojs v1.4.3`

Build:

```shell
PYTHON=/usr/bin/python2.7 script/build
sudo PYTHON=/usr/bin/python2.7 script/grunt install
```

Reproduce:

Launch Atom

What occurs:

```javascript
Error: Cannot find module '../build/Release/keyboard-layout-observer.node'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/usr/local/share/atom/resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/usr/local/share/atom/resources/app/node_modules/atom-keymap/node_modules/keyboard-layout/lib/keyboard-layout.js:6:28)
    at Object.<anonymous> (/usr/local/share/atom/resources/app/node_modules/atom-keymap/node_modules/keyboard-layout/lib/keyboard-layout.js:33:4)
    at Module._compile (module.js:475:26)
    at Object.loadFile [as .js] (/usr/local/share/atom/resources/app/src/babel.js:162:21)
    at Module.load (module.js:370:32)
/usr/local/share/atom/resources/app/src/space-pen-extensions.js:64 Uncaught TypeError: Cannot read property 'dispatch' of null
```

![screenshot from 2015-03-05 09 54 38](https://cloud.githubusercontent.com/assets/2391349/6510860/a5e8975e-c31d-11e4-932b-c92f55670065.png)

**Comment by naicode** [comment]
Hy,
I have the same problem running the same Linux version but `nodejs v0.12.0` so it's not a problem with `iojs`.

**Comment by naicode** [comment]
Yay, I reinstalled it a view minutes ago and now it works, bug seems to be fixed. 
Interestingly it seems there was no commit (on the used branch) since yesterday, so the bug probably was in some of the build dependency or similar.

**Comment by RainbowDashDC** [comment]
I can confirm it's fixed aswell.

**Comment by jhaubrich** [comment]
I'm encountering this regardless of atom version. Same operating system, and `nodejs v0.12.0`. I was able to compile on my other Arch system without any trouble.

I've tried building on `master`, `v0.194.0`, `v0.192.0`, and `v0.189.0`.

**Comment by jhaubrich** [comment]
Fixed: I deleted the repo, re-cloned, and built `master`. Perfect.

**Comment by 50Wliu** [comment]
In the future you might want to try `script/clean` before removing the repo.

**Comment by jhaubrich** [comment]
How embarrassing. I swear I looked for something like that. Even did a
`make clean` in a fleeting moment of desperation.


Wliu writes:

> In the future you might want to try `script/clean` before removing the repo.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/atom/atom/issues/5865#issuecomment-95328931

-- 
Sent with my mu4e
