### ISSUE TITLE
Close tab after split or Allow independent editing

### ISSUE THREAD

**Issue by tylerFowler** [atom/atom#5866]
Perhaps this was a conscious design choice, but I feel like it would be better to close a tab after you've split it to the right/left/whatever. So, for example, if I have `myfile.coffee` open and I choose 'Split Right' then the original one on the left should be closed.

#### OR

An alternate suggestion would be to just allow dual editing in the same file. In the current state of Atom, if you have the same file opened in two different tabs and they are scrolled to different positions, when you make a change in, say, the left one then the right one will automatically scroll to the position of the change. It's a somewhat common use case for me to reference the top of one file while editing the bottom of it (for things like say checking method signatures).

Thoughts?

**Comment by simurai** [comment]
> So, for example, if I have myfile.coffee open and I choose 'Split Right' then the original one on the left should be closed.

This is how I mostly use panes to edit two different files instead of the same in different areas. So splitting panes would be more a "move into new pane" instead of "clone into new pane". There is a package that adds support for moving panes: https://atom.io/packages/pain-split I mapped it to `f16` and `f19` keys for quick access.

> In the current state of Atom, if you have the same file opened in two different tabs and they are scrolled to different positions, when you make a change in, say, the left one then the right one will automatically scroll to the position of the change.

Hmm.. I can't reproduce this. If I have the same file open in two panes, making changes keeps scroll position.

**Comment by izuzak** [comment]
> In the current state of Atom, if you have the same file opened in two different tabs and they are scrolled to different positions, when you make a change in, say, the left one then the right one will automatically scroll to the position of the change.

Yeah, I can't reproduce that either. Can you reproduce this behavior in the latest version of Atom (0.186.0) in [safe mode](https://github.com/atom/atom/blob/master/docs/debugging.md#check-if-the-problem-shows-up-in-safe-mode)?

> Perhaps this was a conscious design choice, but I feel like it would be better to close a tab after you've split it to the right/left/whatever. So, for example, if I have myfile.coffee open and I choose 'Split Right' then the original one on the left should be closed.

There's already an issue to track this request: https://github.com/atom/atom/issues/4738. Can you add a comment to that issue and follow it for updates?

**Comment by tylerFowler** [comment]
Interesting, it seems that I can type on the panes separately now without one scrolling down. Sorry about that! I guess it was either already fixed/being caused by some package I don't have anymore. And thanks for redirect, will add my 2 cents on that issue.

**Comment by tylerFowler** [comment]
Actually, false alarm. I found what was causing the issue of another instance (i.e. tab) to scroll down when changed in another separate tab.

This happened just now when I hadn't saved a file (i.e. changes were pending) and right clicked on the tab -> split right. Then when I made a change on the left, the right pane of the same file would scroll down to where the change happened (so it was effectively an exact mirror of the left pane). However, after I saved the file in the left pane (though I'm not sure it mattered which tab I saved my changes in) then the tabs became independent.

Let me know if anyone else can reproduce this. To my knowledge no packages are causing this behavior.

**Comment by izuzak** [comment]
@tylerFowler Thanks for helping us investigate this :blue_heart:. I'm still having trouble reproducing this, and I tried 5-6 times by following your instructions. 

Can you reliably reproduce this in Atom 0.187.0 in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If so, could you record a short GIF which clearly demonstrates how to reproduce the problem? :pray:

**Comment by tylerFowler** [comment]
I can't seem to reproduce it at the moment.. interesting. I haven't uninstalled any packages lately. If/when it happens again I will be sure to try it in safe mode and then reopen this issue.
