### ISSUE TITLE
Can't open a folder which has dots in name [Windows] [0.186.0]

### ISSUE THREAD

**Issue by Zireael07** [atom/atom#5868]
I have a folder named XXXX.0.6.8.
I could open it as a folder fine up to 0.184.0, now I can't. I have to open the parent folder where it resides as a folder and only then can I browse this one.

I would prefer to avoid renaming it, as I have several shortcuts to it, as I both play the game and poke around its source code.

Any ideas what happened? Maybe it's the url exclusion code thinking it's a url?

**Comment by damieng** [comment]
Just tested this in 1.10.2 and it's working fine. Not sure when it was fixed.
