### ISSUE TITLE
Disabled keys show search bar/Change keybindings ctrl-alt-f

### ISSUE THREAD

**Issue by Samuell95** [atom/atom#5872]
Hello, i try change keybind for ctrl-alt-f and dont work. I using windows7 and latest version of Atom.

'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-f: 'editor:fold-selection'
i changed to
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-1: 'editor:fold-selection'

**Comment by VeeeneX** [comment]
This is duplicate of
https://github.com/atom/atom-keymap/issues/9
and https://discuss.atom.io/t/disable-default-keybindings/1077/29
```
'.workspace .editor':
  'ctrl-alt-f': 'null'
```

**Comment by Samuell95** [comment]
its working, but show search bar :/

'.workspace .editor':
  'ctrl-alt-f': 'unset!'
  'ctrl-alt-p': 'unset!'
'body .native-key-bindings':
  'ctrl-alt-f': 'native!'
  'ctrl-alt-p': 'native!'
'.platform-win32, .platform-linux':
  'ctrl-alt-f': 'native!'
  'ctrl-alt-p': 'native!'

**Comment by VeeeneX** [comment]
Could be fixed with overwriting:

```cofeescript
atom.commands.add 'atom-text-editor',
  'user:insert-brackets': (event) ->
    editor = @getModel()
    editor.insertText("[]")
```

```
'atom-workspace':
  'ctrl-alt-f': 'user:insert-brackets'
'.workspace .editor':
  'ctrl-alt-f': 'user:insert-brackets'
```

**Comment by Samuell95** [comment]
Thanks its working :+1:
