### ISSUE TITLE
OpenSuse needs nodejs-devel

### ISSUE THREAD

**Issue by murilo-ramos** [atom/atom#5876]
Hi

I've tried to install from source and using just the nodejs lib I couldn't. Was necessary to install nodejs-devel to get it working (and the other libs described in the link, of course).

Install steps: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

Is this package missing in the steps?

System: OpenSuse 13.2 32 bits

Any chance of having a x86 rpm package for it?

**Comment by kevinsawicki** [comment]
> Any chance of having a x86 rpm package for it?

No one on the team is working on this currently or planning on working on this soon, but a pull request that added support for it would be welcomed.

**Comment by kevinsawicki** [comment]
`nodejs-devel` added to the docs in https://github.com/atom/atom/pull/6578
