### ISSUE TITLE
Searching for new plugins issues

### ISSUE THREAD

**Issue by Enkouyami** [atom/atom#5877]
There are three issues (should I make 2-3 issues?) with searching for packages/themes to install from the settings menu.

1) Entering in a name and pressing pressing enter does not result in an automatic search for what was typed. It only begins searching when I switch it from packages to themes and back.

2) Whenever I make a new search before the results from the old search are completed, under the search bar says searching for it failed and *getaddrinfo ENOTFOUND*.

3) Sometimes when I search for packages that exist like *quippet*, it says the same thing as above.

**Atom Version**: 0.186.0
**System**: linux 3.13.0-37-generic
**OS**: Linux Mint 17.1 Cinnamon 64-bit

**Comment by 50Wliu** [comment]
Are you pressing enter after typing in what you want to search?

**Comment by Enkouyami** [comment]
@50Wliu Yes.

**Comment by 50Wliu** [comment]
Finally-can you replicate this behavior in safe mode (`atom --safe`)?  If so, I'll transfer this issue to the Tree View repo.

**Comment by Enkouyami** [comment]
@50Wliu I couldn't replicate that behavior in safe mode.

**Comment by 50Wliu** [comment]
All right, then it's a problem with one of your currently installed packages.  You might want to check out [package-cop](https://atom.io/packages/package-cop) to find out exactly which one is the troublemaker.
