### ISSUE TITLE
AtomSetup.exe - Installation has failed

### ISSUE THREAD

**Issue by GaryAYo** [atom/atom#5881]
Hello,

I'm experiencing this error when executing AtomSetup.exe on Win 8.1 x64.

Before executing, I uninstalled my previous version of atom (182.0), deleted /AppData/Local/atom as well as /Users/<name>/.atom and cleaned the atom registries.

 Anyone know what could be the issue?

![image](https://cloud.githubusercontent.com/assets/8942915/6520616/240d6cb2-c397-11e4-9d1a-5d098ca1b912.png)

https://gist.github.com/GaryAYo/80dc3a3cd51d462f57e9

**Comment by GaryAYo** [comment]
I was able to successfully install atom editor after running [ccleaner](http://www.piriform.com/ccleaner) and removing all unnecessary files.

This issue can be closed.

**Comment by jcs224** [comment]
I have this issue too. I ran CCleaner but no go for me. Windows 7 Pro 64-bit.

![atomnotworking](https://cloud.githubusercontent.com/assets/6226188/6579828/53d36d56-c712-11e4-8514-8fbaab8b7525.PNG)

**Comment by paulcbetts** [comment]
@jcs224 Can you hit that button and paste in the log?

**Comment by jcs224** [comment]
No log posted, just opens my Documents folder with nothing new in it. Should note that I am on a corporate machine with mandatory antivirus. I tried adding an exception for the installer but that didn't seem to work either.

**Comment by jcs224** [comment]
@paulcbetts The installation file doesn't work, but when I download the [latest zip](https://github.com/atom/atom/releases/tag/v0.187.0) it works fine. Thanks for your attention on this!

**Comment by jcs224** [comment]
Should probably move this to #4583, that is more pertinent to my actual issues. We can probably close this again.

**Comment by hakatashi** [comment]
I got the exactly same error message as OP and CCleaner saved my day too.

**Comment by paulcbetts** [comment]
This is fixed by https://github.com/atom/grunt-atom-shell-installer/pull/15

**Comment by ssamatar** [comment]
I have turned off my firewall whilst installing atom and it worked fine for me.

**Comment by Chromeninja** [comment]
Im getting the same error i have tried cclean, deleting every atom file i can find. Even tried a factory rest :/ 

Windows 10

http://pastebin.com/z1sdiryQ

**Comment by mrkeyboard** [comment]
Windows 10 here, same error- resolved after running CCleaner as suggested.

**Comment by lee-dohm** [comment]
For people running into Windows installation problems, please follow the instructions in the [Atom FAQ](https://discuss.atom.io/c/faq) here:

https://discuss.atom.io/t/having-windows-installation-problems/26498

Locking comments on this Issue to drive people to the standard instructions.
