### ISSUE TITLE
Join lines into one long line cases Atom slow or hangs

### ISSUE THREAD

**Issue by hokein** [atom/atom#5882]
Type `cmd+j` short-cut to join multiple lines into one line, and as the line gets longer, Atom will become slower, even hangs.

This happens on highlight-switch on, while I changed the file type to `txt` and repeated the same steps, Atom seems work much better. The test file is [here](https://gist.github.com/hokein/48a9ed680d69fbf25305).

This may also related to #979.

**Comment by izuzak** [comment]
Another observation: if soft wrap is turned on, then joining these lines takes forever (I waited for over a few minutes). However, if you turn off soft wrap, it's much faster. And if you turn on soft wrap after after joining lines -- it's instant.
