### ISSUE TITLE
hidden menu bar won't show when pressing `alt`

### ISSUE THREAD

**Issue by despairblue** [atom/atom#5884]
Tested with `atom --safe`. Key Binding Resolver shows no binding (none at all, so no package is swallowing the event or something like this).

**Versions:**
* **atom** 0.186.0
* **OS** ArchLinux

**Comment by izuzak** [comment]
Not sure which hidden menu bar you're referring to -- can you clarify that. Also, which keyboard layout are you using, @despairblue?

**Comment by 50Wliu** [comment]
I'm guessing he has the "Auto Hide Menu Bar" option (Windows/Linux only) enabled.  Alt is supposed to make it show.

**Comment by izuzak** [comment]
Thanks, @50Wliu! Were you able to reproduce this perhaps? Forgot which OS you're on :smile:

**Comment by 50Wliu** [comment]
I can't reproduce since my desktop is using Unity which hides all the menu bars inside the titlebar, therefore leaving nothing left for Atom to hide ;).

**Comment by despairblue** [comment]
@izuzak @50Wliu is right, I'm talking about the `Auto Hide Menu Bar` options. I'm using ArchLinux with just a window manager (i3), so there are not window decorations the menu bar could be merged with. Disabling `Auto Hide Menu Bar` shows the menu bar and pressing alt underlines the shortcut character (like `alt+v` for the view menu). Enabling `Auto Hide Menu Bar` hides the menu bar but pressing alt does not show it again.

**Comment by despairblue** [comment]
I can't make it work with any version going back 'till 0.178.0. So maybe that's only my setup that's broken, have to check my laptop at home.

**Comment by despairblue** [comment]
Closing this, since it simply works again. Must have been my configuration :confused:
