### ISSUE TITLE
Uncaught Error: ENOENT, open '/home/ftovaro/.atom/packages/save-session/projects/undefined/project.json'

### ISSUE THREAD

**Issue by Tovar12** [atom/atom#5885]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.186.0
**System**: linux 3.16.0-31-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open '/home/ftovaro/.atom/packages/save-session/projects/undefined/project.json'

```
At fs.js:82

Error: ENOENT, open '/home/ftovaro/.atom/packages/save-session/projects/undefined/project.json'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
save-session, v0.11.5

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
This is caused by a [bug](https://github.com/mpeterson2/save-session/issues/68) in the save-session package. Follow [that issue](https://github.com/mpeterson2/save-session/issues/68) for updates.
