### ISSUE TITLE
Backslashes disappear from "find in project"

### ISSUE THREAD

**Issue by bblack** [atom/atom#5887]
To reproduce:

1. Shift+command+f to bring up the 'find in project" pane
2. Ensure the regex option is selected
3. Search for a regex that includes a backslash (e.g. `console\.log`)
4. Click any result to go to the file in which it appears
5. Press shift+command+f again.

The backslash has disappeared from the input field. It now says `console.log`.

This has been present in atom for me for months, as long as I can remember. I just reproduced this with `--safe`.

Mac OSX, Atom 0.186.0

**Comment by mark-hahn** [comment]
Did you quote the backslash, i.e. `\\`

**Comment by bblack** [comment]
No.

**Comment by mark-hahn** [comment]
Did quoting the backslash fix it?

**Comment by izuzak** [comment]
I'm guessing that's because the current selection is used as the pattern when you hit `cmd-shift-f`. If you click somewhere else in the file (so that `console.log` is no longer selected) before you hit `cmd-shift-f` again -- it should use the old pattern with the backslash.

**Comment by bblack** [comment]
@mark-hahn No, that doesn't fix it - I'm trying to search for a regex, using `\b` as a character class. I'm not trying to search for a literal backslash.

@izuzak : it looks like you're right. It's a bit confusing though, since when you click a line in the 'find' results, it goes to the file and selects the matching string - but the 'find in project' pane remains open, with the regex still in the input field. doing cmd+shift+f puts focus on it, and only *then* does the selection get copied into that input.

**Comment by benogle** [comment]
Can you open an issue on find-and-replace repo about this?

**Comment by bblack** [comment]
@benogle done

**Comment by izuzak** [comment]
Closing in favor of https://github.com/atom/find-and-replace/issues/366.
