### ISSUE TITLE
On Ubuntu 64bit, atom's first launch is a 1x1px window.

### ISSUE THREAD

**Issue by robru** [atom/atom#5900]
I wanted to try out atom today, but it seemingly won't launch. I installed the 64bit Ubuntu deb, it installed ok, and when I run 'atom' in my terminal, the command returns immediately with no output, and no window starts. Atom is seeminly running:

    $ ps aux|grep atom
    robru    26233  0.0  0.0  16664  1672 pts/2    S    06:07   0:00 /bin/bash /usr/bin/atom
    robru    26235  0.8  0.6 1915900 108176 pts/2  Sl   06:07   0:01 /usr/share/atom/atom --executed-from=/media/robru/Vienna/Downloads --pid=26223
    robru    26240  0.0  0.2 321084 38456 pts/2    S    06:07   0:00 /usr/share/atom/atom --type=zygote --no-sandbox
    robru    26260  0.2  0.6 513336 109568 pts/2   Sl   06:07   0:00 /usr/share/atom/atom --type=gpu-process --channel=26235.0.1420432126 --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,12,14,39 --disable-accelerated-video-decode --gpu-vendor-id=0x8086 --gpu-device-id=0x0166 --gpu-driver-vendor --gpu-driver-version
    robru    26272  2.1  0.8 1070364 137720 pts/2  Sl   06:07   0:02 /usr/share/atom/atom --type=renderer --force-device-scale-factor=1 --js-flags=--harmony --no-sandbox --enable-deferred-image-decoding --lang=en-GB --node-integration=true --subpixel-font-scaling=false --enable-delegated-renderer --enable-impl-side-painting --num-raster-threads=1 --disable-accelerated-video-decode --channel=26235.1.1108578135
    robru    26372  2.3  0.8 1069340 135808 pts/2  Sl   06:08   0:02 /usr/share/atom/atom --type=renderer --force-device-scale-factor=1 --js-flags=--harmony --no-sandbox --enable-deferred-image-decoding --lang=en-GB --node-integration=true --subpixel-font-scaling=false --enable-delegated-renderer --enable-impl-side-painting --num-raster-threads=1 --disable-accelerated-video-decode --channel=26235.2.1864596157
    robru    26404  0.1  0.3 896024 53596 pts/2    Sl   06:08   0:00 /usr/share/atom/atom --eval require('/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js').setCacheDirectory('/home/robru/.atom/compile-cache/coffee'); require('/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js').register(); require('/usr/share/atom/resources/app/node_modules/coffeestack/index.js').setCacheDirectory('/home/robru/.atom/compile-cache/coffee/source-maps'); require('/usr/share/atom/resources/app/src/task-bootstrap.js');

But there just isn't any visual indication that anything has happened. `atom --help` reported some options, but `atom -n` failed to create a new window. Also the launcher icon that appeared doesn't open any windows either.

Help!

**Comment by robru** [comment]
Well, out of the corner of my eye, I managed to find a 1px by 1px window, and after resizing it... it was atom.

**Comment by stramel** [comment]
@robru What version of Ubuntu are you running as well as, which graphics drivers are you using? I'm running Ubuntu 14.04 64bit and not seeing any issues.

**Comment by robru** [comment]
I saw the same behavior on both Utopic and Vivid (on the same machine; I just upgraded while troubleshooting), graphics card is an Intel Ivybridge Mobile (driver=i915 according to lshw).

Now that I've resized the window it remembers my chosen size and launches correctly ever since, but it was a very confusing first couple of runs there...

**Comment by robru** [comment]
Also this is using Gnome Shell, not sure if that's relevant.

**Comment by robru** [comment]
Indeed, I'm not able to reproduce this in a fresh Trusty VM... I'll try again with a Utopic VM and see if I can't reproduce it.

**Comment by robru** [comment]
Right, well I'm not capable of reproducing this in a VM, neither in trusty, nor utopic, nor even with gnome-shell in utopic. Chalk this one up to "my dev box be messed up" I guess, sorry for the noise.
