### ISSUE TITLE
Make Windows shell integration opt-in via Settings

### ISSUE THREAD

**Issue by BrainCrumbz** [atom/atom#5901]
Hello all
we're on windows 7 64bits. After installing Atom, basically everywhere I right-click in windows explorer I see a "Open with Atom" item. We tried cleaning those many elements manually from registry, but at the next update of course they're back again.

How can we opt-out from the Winsows shell integration? Possibly at install time and, also, afterwards through some program preferences,

Thanks

**Comment by paulcbetts** [comment]
We don't need to do this at install time, we just need to have a setting that will enable / disable this

**Comment by BrainCrumbz** [comment]
Well, if you think about many program install wizards, they can show in one of their steps the option for (Windows?) shell integration, usually in the form of a pre-selected checkbox.

Just for completeness:  
Depending on the type of application, the wizard can have two install paths (default and custom): in such cases, the shell integration options shows up only in custom path. In default path integration is implicitly enabled.

Our 2 cents

**Comment by paulcbetts** [comment]
So, I'm suggesting a solution where anyone can change it whenever they want, and you're telling me, "No, no, make them choose at exactly one time, a time where they'll have no idea what to pick because they won't know the consequences of their decisions or how they'll feel about it later".

**Comment by BrainCrumbz** [comment]
Not at all, I was not clear enough. As said at the beginning, it would be nice to have both ways: at install time, and later on via preferences. The last comment ("*Well, if you think about many...*") was just a digression specific to the install-time feature, it was not meant to exlcude the preferences feature.

**Comment by art-ist** [comment]
+1: I just uninstalled Atom because it took at least 10-20 secs! to open any context-menu in Windows explorer since I installes Atom. That was unacceptable as I'm hevily using it.
After I now uninstalled Atom the context-menu pops up again.

**Comment by Zireael07** [comment]
I am not having any issues with context menus, but I would like an option to opt out, too.

**Comment by nguyenkinh** [comment]
I uninstalled and the menu is still there, only with a broken icon!!!

**Comment by MarkusRehberg** [comment]
Same here: I installed Atom and directly uninstalled it again (which is sad), because I found it extremely invasive to have this "integration" (on Win 8.1. 64 bit). Please allow to easily install atom without such surprises. Thanks!

**Comment by BramVanroy** [comment]
I'd like to get more attention to this issue. Also on Windows 10 I experienced this.

+1 for the option during install *and* in settings

**Comment by kulukimak** [comment]
This is a persisting issue and very bad practice. At the moment you can remove the context menu with the following .reg file:

    Windows Registry Editor Version 5.00
    
    ; Removes 'Open in Atom' from the context menu.
    
    ; windows-context-menu
    [-HKEY_CLASSES_ROOT\*\shell\Open File in Atom]
    [-HKEY_CLASSES_ROOT\Directory\shell\Open Folder in Atom]
    [-HKEY_CLASSES_ROOT\Directory\Background\shell\Open Folder in Atom]
    [-HKEY_CLASSES_ROOT\LibraryFolder\Background\shell\Open Folder in Atom]
    
    ; Chocolatey
    [-HKEY_CLASSES_ROOT\*\shell\Atom]
    [-HKEY_CLASSES_ROOT\Directory\shell\Atom]
    [-HKEY_CLASSES_ROOT\Directory\Background\shell\Atom]

**Comment by tgroff** [comment]
Thank you @kulukimak, I do not like this in my context menu, I appreciate the registry fix. Win10 x64. 

Dear Atom,io team, please make this an installer option to opt-out of the context menu addition.

**Comment by Reubend** [comment]
Thanks so much kulukimak! That worked perfectly.

**Comment by kirkouimet** [comment]
@kulukimak thanks! Wish there was an option in the app besides having to use the registry fix

**Comment by designedbymatt** [comment]
What is the progress on this? 
I'm sick of running a manual reg file every time it **adds itself without permission again** to the Windows context menu when it updates.

**Comment by paulcbetts** [comment]
@designedbymatt The progress on this is whenever you or another contributor decide to fix it, by putting a setting in the Settings pane

**Comment by BrainCrumbz** [comment]
@paulcbetts would it be useful if someone could post here (or somewhere else more appropriate) some details on where to look at in code? Actually even before that, maybe put up a short list of requirements to implement for this feature? (e.g. *an option should appear here, *installer should do this, etc.)

In this way, it would be easier for some *external* contributor to help. What do you think?

**Comment by paulcbetts** [comment]
@BrainCrumbz It should be pretty straightforward:

1. Add a checkbox to the Settings pane, "Enable Explorer integration in right-click menus"
1. Take [this function and its friend](https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee#L61) and put it into a separate module
1. Toggle the regkey when user clicks the checkbox

**Comment by BrainCrumbz** [comment]
Thanks for quick feedback. Where is the installer Settings pane defined?

**Comment by paulcbetts** [comment]
> Thanks for quick feedback. Where is the installer Settings pane defined?

There are no installer settings, I'm talking about the regular settings pane

**Comment by BrainCrumbz** [comment]
Ok, got that. Where does Atom define that pane? From a quick browsing I could not see any window, nor HTML nor something related to a UI.

**Comment by paulcbetts** [comment]
@BrainCrumbz Peep https://github.com/atom/settings-view

**Comment by BrainCrumbz** [comment]
Yeah, thank you, in the meantime eventually I saw that project. Is there any place where you guys describe how Atom defines a window/pane/whatever in UI? Is that done in CoffeeScript? Is there an example of that?

**Comment by BrainCrumbz** [comment]
Is that [here](https://github.com/atom/settings-view/blob/master/lib/settings-view.coffee)?

**Comment by Zireael07** [comment]
@ BrainCrumbz: Thanks for poking around!

**Comment by BrainCrumbz** [comment]
We don't have Atom installed at the moment (actually it has been like that for a while) and at the moment no Windows laptop around, so we're getting info only by asking and by browsing in code repo. Don't know if the screenshot in Settings-view home page is still actual w.r.t the code, hence don't know yet in which panel the checkbox should go (plus we never worked with CoffeeScript and this way of defining views).

**Comment by 50Wliu** [comment]
The screenshot on the Settings View readme is up-to-date.

**Comment by BrainCrumbz** [comment]
Thanks @50Wliu . The checkbox could go into that *Core Settings* pane. When some days ago I tried to look for that pane in code, I could not find which file defines it. Do you know where is that?

We tracked back from *lib/settings-view.coffee* with *GeneralPanel*, then to *lib/general-panel.coffee* with *new SettingsPanel('core')*, then to *lib/settings-panel.coffee*. Then there's no explanation on how to add & define a new option so that *SettingsPanel* will pick that up.

**Comment by paulcbetts** [comment]
> Checking that again, there's no explanation on how to add & define a new option so that SettingsPanel will pick that up.

So, if it were me, here's how I would do it:

1. Find a string in the settings page to search for
1. Find the file that has that string
1. Use `git blame` to see the commit that added that string
1. In the commit view on GitHub under the title, there'll be a link to the PR that added that commit
1. Read the PR that added that setting, and try to emulate what they did

**Comment by BrainCrumbz** [comment]
I'm glad that I took the same initial step as you. Couple of days ago, I looked up at the screenshot, "beep" seemed a good candidate, being maybe a not-so-frequent word. I searched for that into github repo and no result came up. That's why I started wondering whether the screenshot was up to date. And after confirmation, I asked for more info on how options are defined in order to be picked up by SettingsPanel.

[Just as a side note, it's kinda strange that most of this thread seems spent less on sharing actual & practical info on how/ where things are in the project, and more on the process of how to try to get those information] 

Thanks for the further steps on how to move on afterwards.

**Comment by paulcbetts** [comment]
> [Just as a side note, it's kinda strange that most of this thread seems spent less on sharing actual & practical info on how/ where things are in the project, and more on the process of how to try to get those information]

Sorry, I'm not trying to be intentionally vague / coy, I actually don't know how settings work in Atom either

**Comment by 50Wliu** [comment]
I don't believe the settings are created in settings-view; rather, they're created in atom/atom using `atom.config.get` and `atom.config.set` (https://atom.io/docs/api/v1.0.11/Config), and then populating https://github.com/atom/atom/blob/master/src/config-schema.coffee.  I'm not 100% on this though as I haven't added any settings to Atom before.

**Comment by mnquintana** [comment]
Atom's core and editor settings are defined as a [config schema](https://atom.io/docs/api/v1.0.11/Config#config-schemas) directly in https://github.com/atom/atom/blob/master/src/config-schema.coffee - package settings (e.g. settings for tabs, whitespace, find-and-replace, etc) are defined as schema objects in individual packages, generally in whatever the `main` file of the package is.

**Comment by BrainCrumbz** [comment]
@paulcbetts @50Wliu thanks both for clarification, much appreciated (the *Collaborator* tag can be misleading at times).

[config-schema.coffee](https://github.com/atom/atom/blob/master/src/config-schema.coffee) seems very much the *culprit*. It holds all the right properties, it is read by [atom.coffee](https://github.com/atom/atom/blob/f0e4da68affacbef6f64031ba52b1370f38da026/src/atom.coffee#L793) which in turns submits that to [config.coffee](https://github.com/atom/atom/blob/f0e4da68affacbef6f64031ba52b1370f38da026/src/config.coffee). BTW, this last one is also the source of that referenced API docs on Config. As the doc says
> An instance of this [Config] class is always available as the atom.config global. 

All that is in atom/atom project. Then, in atom/settings-view project, the same global is used in [settings-panel.coffee](https://github.com/atom/settings-view/blob/5a115f9e051da32e7af676daf6076d890d8d5e75/lib/settings-panel.coffee#L119) to get or set a property.

**Comment by raeesiqbal** [comment]
@BrainCrumbz I think this is what you're looking for
https://github.com/raeesiqbal/atom/blob/raeesiqbal-shell-context-menu/src/config-schema.coffee#L226

**Comment by BrainCrumbz** [comment]
Yep, agree, that is clear, thank you. Apart from adding the checkbox itself, we were browsing around to plan where the meat of changes should be done. Some preliminary ideas:

 1. As **paulcbetts** mentioned, move everything related to registry manipulation out of *squirrel-update.coffee* to a dedicated module/ file, e.g. some *win-registry.coffee*. Update references in *squirrel-update.coffee*
 1. Create a new module/ file, still in atom/atom project, responsible for listening to changes on settings checkbox, and for updating the registry accordingly. That would reference *win-registry.coffee* as well. Its name could be something like *win-shell-context-menu.config*.
 1. Not sure yet about which unit tests to add. Does it make sense to test *win-registry.coffee*, which probably is mostly a thin wrapper around spawning reg.exe? Maybe it make sense to test *win-shell-context-menu.config*.

At the moment spending time cloning the (huge) forked repo, then (long) building application as-is for the first time to check that everything's correct to start with. BTW does anyone know if building takes long everytime, or just the *first* time?

**Comment by 50Wliu** [comment]
Just the first time, thankfully :).  The first time it has to download and install all the Node modules, as well as every single Atom package.  Then those get cached so the build time speeds up tremendously once you start rebuilding.

**Comment by BrainCrumbz** [comment]
Ok, adding property in config-schema.coffee works, at least visually.
![option](https://cloud.githubusercontent.com/assets/3185573/9777853/43304568-5769-11e5-887f-660799a6042f.png)

**Comment by raeesiqbal** [comment]
Here is where the context menu entry is actually being added
https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee#L234
https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee#L240
and here is the function for it
https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee#L61

**Comment by raeesiqbal** [comment]
You can do a `::onDidChange` on your configuration option and call `installContextMenu` or `uninstallContextMenu` accordingly.

**Comment by Zireael07** [comment]
*bounce bounce* Thank you @BrainCrumbz for tackling this!

**Comment by BrainCrumbz** [comment]
:+1: :+1: Is there a way to run tests (*apm test*) only from some specific spec? We have something (our stupid mistake) failing on *squirrel-update.coffee* and it takes quite some time everytime to run all tests. I wish I could run just e.g. *spec/squirrel-update-spec.coffee*, but that does not seem to work.

**Comment by BrainCrumbz** [comment]
Please, could anyone give a look at [this commit](https://github.com/BrainCrumbz/atom/commit/68c83da65477a57bc05911e2e2fda4b0f4ebd82b) in *win-context-menu-option* branch? 

When running *apm test* (apart from a load of messages coming from other unrelated files) in the end it reports 3 failures, all related to *squirrel-update-spec.coffee*:

```
Windows squirrel updates
  it ignores errors spawning Squirrel
    Error: EBUSY
      at Object.<anonymous> (/my/path/atom/spec/squirrel-update-spec.coffee:30:54)
      at spawnUpdate (/my/path/atom/src/browser/squirrel-update.coffee:25:11)
      at createShortcuts (/my/path/atom/src/browser/squirrel-update.coffee:90:3)
      at Object.exports.handleStartupEvent (/my/path/atom/src/browser/squirrel-update.coffee:131:7)
      at [object Object].<anonymous> (/my/path/atom/spec/squirrel-update-spec.coffee:33:27)
  it quits the app on all squirrel events
    timeout: timed out after 5000 msec waiting for something to happen
  it keeps the desktop shortcut deleted on updates if it was previously deleted after install
    timeout: timed out after 5000 msec waiting for something to happen
```

**Comment by mnquintana** [comment]
> Is there a way to run tests (apm test) only from some specific spec?

[You can focus specific specs by prepending them with `f`.](https://atom.io/docs/latest/hacking-atom-writing-specs#running-specs) So if you have a `describe` block, you can run just the specs in that block by putting an `f` in front of it: `fdescribe ... etc` (Same with `it`)

> Please, could anyone give a look at this commit in win-context-menu-option branch?

It would actually be a whole lot easier to give feedback if you opened a PR for this, even if it's still work-in-progress. :smile:

**Comment by BrainCrumbz** [comment]
Right, didn't think about that (being WIP): there you go, PR #8744 . Thanks also for referencing the docs, I missed that part.

**Comment by paulcbetts** [comment]
> I'd just like to stress that at the moment we're running this on a Mac, so not sure if those tests strictly depend on platform. Of course we'll move on a Win machine as soon as we grab one, next week probably.

Well I mean, spawning Squirrel is deffo only going to work on Windows, I'd just skip the tests on Windows:

```coffee
return unless process.platform is 'win32'
```

**Comment by BrainCrumbz** [comment]
FWIW, now squirrel-update specs run fine as well (still on Mac). There were errors due to us extracting spawn and win-registry out of squirrel-update, and not changing unit tests accordingly by mocking the newly added dependencies.

... and this was just in preparation of the actual feature :O :)

**Comment by BrainCrumbz** [comment]
I think we're ready to submit a PR related to this issue. There's a doubt we have on where to import *CompositeDisposable* from, that srpung from (closed) PR #8749 . If anyone could shed a light on that, I guess we can proceed with PR. Thank you

**Comment by BrainCrumbz** [comment]
Just created PR #8780 , anyone interested please have a look at that. Thanks

**Comment by paulcbetts** [comment]
@BrainCrumbz Thanks for the great work on this!

**Comment by BrainCrumbz** [comment]
@paulcbetts thanks!
@ All : thanks for your time spent on this thread

**Comment by paulcbetts** [comment]
> Just walking our way up grunt-electron-windows-installer and squirrel to figure out if/how you can add a checkbox (with its own install step??) also during install

Squirrel installers don't have checkboxes or install steps, this is contrary to the [Squirrel Design Principles](https://github.com/squirrel/squirrel.windows#what-do-we-want)

**Comment by BrainCrumbz** [comment]
Got it. Wanting to respect the principles, is there a *supposed* way to allow for a first-time configuration after install. I was looking at [*--squirrel-firstrun* event](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/squirrel-events.md#getting-started) and thinking if app can show a custom config screen, but then:
1. don't really know if that could be useful/needed
1. I read somewhere about a 15sec time limit that Squirrel allows to app for running any of those hook, and this seems to go against a form open waiting for user to confirm

**Comment by paulcbetts** [comment]
@BrainCrumbz 15sec limit doesn't apply to `firstrun`, it's just a hint to the application that you should show a welcome screen. Atom actually already has a welcome screen, https://github.com/atom/welcome

**Comment by BrainCrumbz** [comment]
Thanks for the pointer, I completely forgot about that. Given the somehow "popular" requests related to this Windows shell integration, do you think it makes sense (for Windows platform) to add a checkbox in that welcome screen?

**Comment by paulcbetts** [comment]
@BrainCrumbz Nope, I think it should just be a setting and we should leave it at that

**Comment by BrainCrumbz** [comment]
Cool. Skipping to next thing coming to my mind: some people mentioned that after an Atom update, the context menu would be there again, even if they manually removed by editing the registry.

Looking at code, even the one from [our PR](https://github.com/BrainCrumbz/atom/blob/win-context-menu-option-squash/src/browser/squirrel-update.coffee#L138) it seems that nothing will change on that side:

```CoffeeScript
    when '--squirrel-updated'
      updateShortcuts ->
        WinRegistry.installContextMenu ->  ### <=====
          addCommandsToPath ->
            app.quit()
```

the context menu will be installed again no matter what's configured in settings. Should this behaviour change as well, and take into account current settings?

**Comment by mnquintana** [comment]
@BrainCrumbz Just a heads up - it might be more productive to move this conversation to your open PR, since then we can actually comment / discuss inline on the code.

**Comment by BrainCrumbz** [comment]
Hello all. Could anyone shed a light on PR #8780 ? Does it make sense to proceed with proposed changes? Thanks

**Comment by art-ist** [comment]
@BrainCrumbz: as #8780 is much about the technical implementation that I don't want to dig into too much, I'll answer here, where it's more on the usability perspective:
The abstract of an opt-out feature for the context menu reads great! (Exactly how I imagined a solution.)

As other tools (like VS Code, as far as I remember) have a simmilar issue, the main perf-problem could not come form having a menu option, but how it's implemented (e.g. having/finding the icon). The question is what does windows do to show the menu, when the item is present?

Still an opt-out option in a crowded menu is always welcome :-)

**Comment by QasimAshraf18** [comment]
ThankYou @kulukimak  :+1:

**Comment by Lausii** [comment]
I'm glad that this discussion is already ongoing. It is absurd that a text editor would integrate itself into EVERY Windows context menu. This attached image is from simply right-clicking the desktop or any folder for that matter.
![invasive](https://cloud.githubusercontent.com/assets/13384681/11992167/55a343f6-a9d7-11e5-961c-45deae6c1da5.png)

**Comment by Hrxn** [comment]
So how's the discussion going? :wink: 

Regardless of UI/UX considerations (I think a setting in the program preferences would be the right way), I don't see the problem that would require so many changes. All this big PR linked here, for what?

Without knowing really much about the subject, why not do exactly the same steps as the installer/uninstaller?

Here is the src:
https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee

Just reuse existing Squirrel events..

https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee#L244
```coffeeescript
when '--squirrel-uninstall'
      removeShortcuts ->
        uninstallContextMenu ->
          removeCommandsFromPath ->
            app.quit()
```

That's where the registry entries get removed when uninstalling.

And `uninstallContextMenu`does:
https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee#L120
```
# Uninstall the Open with Atom explorer context menu items via the registry.
uninstallContextMenu = (callback) ->
  deleteFromRegistry = (keyPath, callback) ->
    spawnReg(['delete', keyPath, '/f'], callback)

  deleteFromRegistry fileKeyPath, ->
    deleteFromRegistry directoryKeyPath, ->
      deleteFromRegistry(backgroundKeyPath, callback)
```

That is just using `deleteFromRegistry`, which in turn calls `spawnReg` with some args.

And `spawnReg`is
https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee#L47
```
# Spawn reg.exe and callback when it completes
spawnReg = (args, callback) ->
  spawn(regPath, args, callback)
```

Calls `spawn` with `regPath`

And `regPath` is
https://github.com/atom/atom/blob/master/src/browser/squirrel-update.coffee#L11
```
if process.env.SystemRoot
  system32Path = path.join(process.env.SystemRoot, 'System32')
  regPath = path.join(system32Path, 'reg.exe')
  setxPath = path.join(system32Path, 'setx.exe')
else
  regPath = 'reg.exe'
  setxPath = 'setx.exe'
```

This is just calling `reg.exe` with some options and params, like here: http://ss64.com/nt/reg.html

**Comment by BrainCrumbz** [comment]
Hello there. Please feel free to submit your PR targeting the issue, or if you wish comment right on pr #8780 where you see points of improvement (although we were having issues with Atom build environment, so I'm not sure when that will work again).

**Comment by Kallizm** [comment]
Hello, I'm entirely new to Atom but came across this thread while researching the same issue. It's unfortunate that no progress has been made yet. I'll keep my fingers crossed for an option to be added to the Settings window. If any other Windows users are looking for an easier way to disable the entry from all of your context menus, without touching the registry, then I'd suggest [NirSoft's ShellMenuView](http://www.nirsoft.net/utils/shell_menu_view.html)

It's completely free (no gimmicks or packaged adware) and incredibly easy to use. Just locate the two entries, right-click, and choose Disable Selected Item(s). Pic: http://prntscr.com/a751w5 

Here's to hoping it's not necessary soon, but until then...

**Comment by alexculea** [comment]
@Kallizm - used and can confirm it is elegant enough. Many thanks!

**Comment by patoezequiel** [comment]
@kulukimak Thank you very much, this solved the problem :)

**Comment by Kallizm** [comment]
Great to hear!

**Comment by rejhgadellaa** [comment]
+1. Also: "how is this still an issue" and "how hard can it be"? ;)

The solution seems obvious, people uninstall Atom because they don't like software that integrates itself in context menus, etc (I personnaly dropped dropbox since my upgrade to win10 because of this exact reason).

**Comment by anyong** [comment]
Just installed Atom for the first time on Win10x64. Terrible - doesn't install into Program Files, doesn't tell me where it installs to, and shows up in the context menu in Explorer (searching for that led me here).

This is a really, really bad design. =/ Hope the editor is better than the initial impressions...

**Comment by 50Wliu** [comment]
> doesn't work out of the box in cygwin

This one should be fixed in Atom 1.7.0.

**Comment by rornor** [comment]
Thanks @kulukimak

**Comment by calipark** [comment]
VERY ridiculous that I've discovered it's been over a year and you guys haven't fixed this. For some unknown reason even Microsoft's Autoruns program couldnt even find this shell extension. Removing it from regedit right now. Very disrespectful to not remove context menu upon uninstall...

**Comment by paulcbetts** [comment]
> Very disrespectful to not remove context menu upon uninstall...

This is a separate issue, can you file a bug?

**Comment by paulcbetts** [comment]
I think we have all the feedback we need on this issue. Unless you have something material to contribute (i.e. not just "You're right, I'm mad!"), please refrain from commenting on this bug.

**Comment by BrainCrumbz** [comment]
Sorry for not being able to actively contribute again: every time we come back and try to build/test on Windows we find a blocking issue. Will try again soon.

**Comment by paulcbetts** [comment]
> Sorry for not being able to actively contribute again: every time we come back and try to build/test on Windows we find a blocking issue. Will try again soon.

No worries, thanks for having a look at this and trying to fix it - jump in the Atom Slack chat room if you get stuck again

**Comment by ErikHumphrey** [comment]
++++++

**Comment by klonuo** [comment]
After applying @kulukimak solution on 1.68, then later on updating to 1.72 brings back this context menu item again, so I had to apply @kulukimak reg patch again.

Can't you guys blame the creator of this code, and discard the code?

Who'd want this context menu anyway?
I'd never use context menu to open file in Atom, as I (and I believe others) have better handlers then to open any file whole Atom browser, unless it's Atom project file or similar.

Does it look like fancy to you on insisting it's existence, or you just hate Windows users?

**Comment by BrainCrumbz** [comment]
There was already an open PR (#8780) related to this present issue. We decided to split that PR (and eventually close it) in a refactoring part (please see #11639) and then in a coming part strictly dedicated to the feature improvement.

The idea is to move onto the feature as soon as (if?) the refactoring gets merged.  
HTH

**Comment by ErikHumphrey** [comment]
should indeed be at both install time and later

**Comment by damieng** [comment]
Here are some thoughts.

## Settings

Explorer integration
- Show 'Open with Atom' for all folders
- Show 'Open with Atom' for all files
- Register as file handler for associating with extensions

I'd recommend the first two default to off as they are quite invasive and the third should default to on providing not running in portable mode.

## Should not have setting but dynamically read state of shell integration to show current checkbox
Two reasons for this:
1. Can't get out of sync
2. Grandfather in existing users while allowing new users defaults change 

## Additional notes
- Use the app name so that 'Atom Beta' can also do this independently

**Comment by damieng** [comment]
Might also want to provide an option to add to 'Send To' to allow multiple files to be opened in a single tab. Would need to write a shortcut as described here https://github.com/atom/atom/issues/8222#issuecomment-218506922

**Comment by damieng** [comment]
Given the workaround is good and we'll try and add it with the improved shell integration I'm going to go ahead and close this issue.

**Comment by BrainCrumbz** [comment]
Won't you lose references and/or info on the topic if you close this issue? Or there's another one tracking features, progress, etc. ?

**Comment by damieng** [comment]
Sorry that reply and close was meant for the other references issue. To many tabs.

**Comment by Fironet** [comment]
This needs to happen. And agreed with anyong the auto install is annoying for a program that isn't intended for basic end users.

**Comment by damieng** [comment]
![image](https://cloud.githubusercontent.com/assets/118951/16825323/a28e38ec-4928-11e6-8b1f-3b324875beba.png)

**Comment by Fironet** [comment]
@damieng you're a champ.

**Comment by damieng** [comment]
Now merged in, should be in next major release.

**Comment by 50Wliu** [comment]
To clarify, this should be available starting in Atom 1.10.0.

**Comment by derrickb** [comment]
I'm uninstalling Atom and will check back on this (really cool looking) editor at a later date when it's more matured... I hate programs that add bloat into the OS like this, far too many programs do it so my patience is incredible thin.

**Comment by damieng** [comment]
Just to clarify - there is zero Atom code running when "Open in Atom" is on the context menus. It is not a shell extension and there is nothing running in background.

It is a few registry entries telling Explorer what text to display (Open in Atom) what the command-line to run is if it's clicked and the location of an icon to draw next to it.

There is no performance penalty having this switched on.

It is now however optional (and off by default) because it is quite visually intrusive.

**Comment by rejhgadellaa** [comment]
> There is no performance penalty having this switched on.

It's just super annoying and adds cognitive load because the menu gets really cluttered (not by this one thing, but if every app would use that reasoning we'd have a context menu that doesn't fit the screen anymore :P), causing searching for that option you DO want to use. But I guess it's solved now so that's great news!

**Comment by chandujr** [comment]
I can't find an option shown in the screenshot posted by @damieng in my Atom. This is the core settings in mine (v1.9.0):

![atom_ss_03102016](https://cloud.githubusercontent.com/assets/14921501/19030141/721d3b5a-8969-11e6-8a90-aa99582b1312.png)

**Comment by savef** [comment]
@chandujr, it's in [v1.10.0](https://github.com/atom/atom/releases/tag/v1.10.0).

**Comment by chandujr** [comment]
@savef Oh okay. Thank you.

**Comment by chandujr** [comment]
Also I would like to mention that even if you have an older version, you can remove the context menu leftover using CCleaner **Registry Cleaner**.

**Comment by Pandazane** [comment]
Delete HKEY_CLASSES_ROOT\Directory\Background\shell\Atom
