### ISSUE TITLE
Configurable stylesheets through user-variables.less

### ISSUE THREAD

**Issue by braver** [atom/atom#5903]
We were having [this discussion](https://discuss.atom.io/t/how-to-allow-users-to-override-my-packages-less-variables/15243/7?u=braver) and jessegrosjean came up with the idea of a `user-variables.less` file.

There have been attempts to set Less variables through config and they have failed for various reasons. While config would be preferable for discovery and ease of use, if it doesn't work perhaps there is a another way.

Users can now overrule styles with their own stylesheet, but that's very limited. It's impossible to change the overall hue of let's say one-dark-ui because those colors are everywhere throughout the stylesheet and the selectors would just be insane. If you can change the variable however, it's just a single number.

The idea would be to have a user-variables.less file in addition to the syntax-variables and the ui-variables. Theme and package authors can choose where to place the import, thereby maintaining control over which variables can be changed by the user. What can be changed can be communicated in the package's readme. This doesn't change the user stylesheet behaviour and would be added in addition to that stylesheet.

So while I think we can agree this is not the ideal solution, the ideal solution being unavailable this could be a brilliant compromise that opens up a lot of options.

**Comment by simurai** [comment]
I really like this as a "plan B". I talked to @kevinsawicki about it. Some points to think about:

1. Once a `user-variables.less` file gets added, it needs to be supported at least till a 2.0.
2. The word "user" in `user-variables.less` could have some "negative" touch. Google "don't call it user"

Personally I think:

1. There is always a cost in adding something, but the chance that overwriting variables from the settings or that native CSS variables are gonna land in Chromium anytime soon, isn't that high. So having this option would be nice.
2. Maybe not a too big issue. There is already the term "User Styles" to customize the browser, so it should make it clearer what "user variables" meaning is. An alternative: Just `variables.less` would go well with `styles.less` but less with `ui-variables.less` and `syntax-variables.less`. Or maybe `override-variables.less`? But I think `user-variables.less` still fit the best.

**Comment by braver** [comment]
> Once a user-variables.less file gets added, it needs to be supported at least till a 2.0.
> There is always a cost in adding something

This is true. However, I think this feature goes along with this being a hackable editor. It goes way beyond what any other piece of software out there is offering and some packages will do awesome stuff with it. There will be effort involved, also with handling this from the packages and themes. But as you say, Chromium or CSS-native alternatives are just a speck on the horizon. To me it feels like the cost is pretty reasonable.
I don't feel like it fixes a problem and Atom (and life in general) is already pretty great without this, so I can see how you could opt to not do it. However, nothing else will come along for years either and this is the best shot at this feature that we're going to get for quite a while.

> The word "user" in user-variables.less could have some "negative" touch. Google "don't call it user"

I am aware of that, Don Norman also once said that the only other place they call people "users" is with drug addicts. And I don't disagree. If you always talk about the people that use your product as "users", that creates a distance between you and them, which can make it feel more ok to pick non-user-friendly solutions. However, the role of the people in this system is very much that of a "user", and as jargon in that sense is expected and there is nothing wrong with it. "User account", "user preferences", etc. are all clear and consistent labels for stuff that is specific to a user.

**Comment by coopermaruyama** [comment]
hey just to let you guys know I was able to work around this by using `fs.writeSync` to write to a file within my package, and updating it any time the user updates their config. I wrote about it here: https://discuss.atom.io/t/set-less-variables-from-package-settings/10481/4?u=cooperm

I know it's very hacky, but it does work. The only issue I noticed is if other packages are depending on these custom variables, changing it in the settings won't change it for the dependent packages right away - you need to do a live reload first.

**Comment by simurai** [comment]
:+1: Seems to work great. Yeah, having to reload Atom isn't that elegant, but a "user-variables.less" file wouldn't solve that either.

**Comment by thedaniel** [comment]
I ran into this while helping someone style their editor - the One themes derive a lot of their styles from base variables, and being able to alter one or two values rather than all the computed rules would be really nice.

**Comment by wdanilo** [comment]
Is there any progress regarding this issue? I would love ot create a UI-theme and be able to access the config variables from within less files (to allow for example setting some accent color from within ui-theme config and being able to use it in different placess in less, probably darkening or lighting it somewhere). Writing config to file and including it in less requires "users" to reload atom, which a little ugly.

**Comment by NicolasNarvaez** [comment]
Please, some update on this?, cant find a new issue about it
