### ISSUE TITLE
Add support for syntax: Line Delimited JSON

### ISSUE THREAD

**Issue by stevemao** [atom/atom#5909]
http://jsonlines.org/
http://en.wikipedia.org/wiki/Line_Delimited_JSON

Similar to JSON so it should be easy.

**Comment by izuzak** [comment]
If you try opening a line delimited JSON file and manually set the syntax to "JSON" using the grammar selector (`ctrl-shift-L`), you should see the file syntax highlighted correctly. So, as far as I can tell, the only thing that would need to happen here is that [`.jsonl` files are parsed with the JSON grammar by default](https://github.com/atom/language-json/blob/d9fe361c60a7d188e843d61076f9c1daf7250343/grammars/json.cson#L1-L9). If you agree, then consider opening an issue over at https://github.com/atom/language-json to make that happen (or even better, a pull request). If you disagree, consider creating a new package for line delimited JSON support, similar to other packages for language support.

**Comment by stevemao** [comment]
:+1:
