### ISSUE TITLE
Startup from atom doesn't work

### ISSUE THREAD

**Issue by meventi-stephan** [atom/atom#5911]
I use Atom Version 0.186 (newest version after update) in Windows 7 with following plugins:
- emmet 2.3.4 (newest version after update)
- git-plus 4.4.8 (newest version after update)
- linter 0.12.0 (newest version after update)
- linter 0.0.11 (newest version after update)
- merge-conflicts 1.2.10 (newest version after update)
- open-last-project 0.3.4 (newest version after update)
- project-manager 1.15.5 (newest version after update)

But after startup an error message occurs:
 ![atom](https://cloud.githubusercontent.com/assets/5426291/6564107/6fb94c8c-c6a6-11e4-977a-015ff6f30e84.jpg)

If i starts atom with ```atom --safe``` atom starts normally. Can you help me?

**Comment by 50Wliu** [comment]
Please rename `~./atom` (default `%userprofile%/.atom`) to something like `~./atom-backup`.  One of your packages (or a combination of them) is crashing Atom.

**Comment by senyorails** [comment]
console shows that error is being thrown
from index.js:64
![screen shot 2015-03-09 at 7 58 47 pm](https://cloud.githubusercontent.com/assets/3177543/6567524/c1281dec-c696-11e4-9f69-75b321ebf60b.png)

**Comment by izuzak** [comment]
> If i starts atom with atom --safe atom starts normally. Can you help me?

When you start Atom in safe mode, it runs without the packages you installed. So, this sounds like a problem in one of the packages you installed. You could try figuring out which one it is by uninstall them one-by-one (e.g. with `apm uninstall`) and then open an issue on that package's repository.
