### ISSUE TITLE
Menu bar aligned right and randomly disappears on a RTL Windows 7 version

### ISSUE THREAD

**Issue by sapiraz** [atom/atom#5915]
Windows 7 64-Bit SP1 (Hebrew)
Atom version: 0.186.0

![atom1](https://cloud.githubusercontent.com/assets/5664685/6571245/b7688634-c70e-11e4-98e6-c9e711860489.PNG)

**Comment by Raz-Girit** [comment]
Still happening on v.1.0.11.

**Comment by damieng** [comment]
The menu bar is in fact entirely drawn by Electron.  We have recently upgraded to a new version of Electron and do not have a RTL version of Windows to hand.  Please let us know if this issue is solved or not with the upgrade e.g. in Atom 1.10.x or later.

**Comment by ido1990** [comment]
Still the same on 1.18.0
![default](https://user-images.githubusercontent.com/16368652/28911207-82fbdac6-7838-11e7-91ae-1ceb04c2cba5.png)
