### ISSUE TITLE
Failed to activate the notebook package

### ISSUE THREAD

**Issue by Heintzsight** [atom/atom#5919]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the notebook package

```
At undefined

- Notebook is active

**Comment by claui** [comment]
Starting a few days ago, a similar error keeps popping up to me too whenever I start up Atom.  
Appending my error logs here because Atom keeps referring me to this existing issue.

**Comment by claui** [comment]
**Atom Version**: 0.187.0
**System**: *machine name redacted* (it is a PC running Windows 7 Enterprise)
**Thrown From**: Atom Core
 
### Stack Trace
 
Failed to activate the notebook package
 
```
At undefined
 
- Notebook is active & functional only with a valid project open
```
 
### Commands
 
```
```
 
### Config
 
```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "audioBeep": false
  },
  "editor": {
    "showInvisibles": true,
    "invisibles": {},
    "zoomFontWhenCtrlScrolling": false
  }
}
```
 
### Installed Packages
 
```coffee
# User
atom-compare-files-0.3.1, v0.3.1
atom-sublime-select-1.2.2, v1.2.2
compare-files, v0.4.1
notebook, v0.4.0
Sublime-Style-Column-Selection, v1.2.3
 
# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
This issue was moved to skulled/notebook#7
