### ISSUE TITLE
Add "New Window" on dock context menu on OS X.

### ISSUE THREAD

**Issue by jtkiley** [atom/atom#5921]
Please consider adding a "New Window" option on the dock context menu for Atom. This change would make working with many spaces much more pleasant.

Post-change:

1. Change to intended space for new window.
2. Click and hold (or Ctrl-click, or right/two-finger click) on the Atom icon.
3. Select "New Window".
4. Work.

Currently:

1. Change to intended space for new window.
2. Click and hold (or Ctrl-click, or right/two-finger click) on the Atom icon.
3. Curse because there's no "New Window" option, using an irreverent compound "swearword" with another swearword added (and presumably set off by hyphens) in the middle.
4. Click the Atom icon and watch transition to another space.
5. Press Shift-Cmd-N (or use the menu).
6. Use the Mission Control gesture (three finger upward swipe).
7. Drag the new window to the intended space.
8. Click the intended space.
9. Work.

I'm having a little bit of fun with the procedure above, but the change would be really helpful.

Examples of current behavior and the context menu option in Safari:

![screen shot 2015-03-10 at 12 35 58 pm](https://cloud.githubusercontent.com/assets/3935135/6579687/22f65e40-c722-11e4-9d05-2e5c3837528d.png)
![screen shot 2015-03-10 at 12 36 32 pm](https://cloud.githubusercontent.com/assets/3935135/6579688/2305ce52-c722-11e4-84b5-760d5c4256b3.png)

**Comment by mnquintana** [comment]
Related to #3935, #4241, and https://discuss.atom.io/t/new-file-or-new-window-option-in-os-x-dock-application-context-menu/12173

**Comment by jmarchello** [comment]
+1, I need this feature every day.

**Comment by borgand** [comment]
+1

In the meantime I wrote a small AppleScript that you can use to quickly open new Atom window in current space.

http://wp.me/p5KvGQ-au

**Comment by tkent** [comment]
+1

**Comment by DouweM** [comment]
Implemented in #9606!

**Comment by lee-dohm** [comment]
Since #9606 has been merged, I'm going to go ahead and close this. It's available in `master` now and should be available in the next version of Beta.
