### ISSUE TITLE
BufferedProcess throws error with stdio: 'inherit' option

### ISSUE THREAD

**Issue by nathanjohnson320** [atom/atom#5922]
When passing the following options object into the BufferedProcess constructor I get an error:

```
 options: {
    cwd: "/Users/najohnson/github/run-command",
    stdio: "inherit"
  }
```

Uncaught TypeError: Cannot read property 'setEncoding' of null
/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:126

If I take out the "stdio: inherit" the error goes away

**Comment by jyprksh001** [comment]
@nathanjohnson320  how did you fix this error
