### ISSUE TITLE
Consistent crash on file containing UTF characters (works fine in Sublime Text)

### ISSUE THREAD

**Issue by ohwhen** [atom/atom#5928]
Whenever I open this file, the editor crashes 10/10 (latest build 0.186)

(Couldn't attach a JSON file so using Pastebin, save and open in Atom)

http://pastebin.com/nQbCTzD7

**Comment by 50Wliu** [comment]
I cannot reproduce-Atom opens the file just fine.  What OS is this?  Can you reproduce in safe mode (`atom --safe`)?

**Comment by ohwhen** [comment]
Yes, can reproduce...

Uploaded file here https://github.com/ohwhen/Atom-Crash-5928/blob/master/language-menu.json

**Comment by totallyuneekname** [comment]
I was also able to reproduce this, with all community packages disabled.

I am using Mac OS X 10.9.5 running Atom 0.187.0

**Comment by izuzak** [comment]
Visiting that link (http://pastebin.com/nQbCTzD7) crashes the Chrome tab for me. So I saved the file with Firefox and opened it with Atom, but Atom didn't crash -- I can edit the file just fine. 

Atom 0.187.0, OSX 10.10.2

@ohwhen Which Atom version and which OS are you using?

Can anyone else reproduce this?

**Comment by ohwhen** [comment]
@izuzak using OS X 10.9.5 and Atom 0.187

Note that the same file opens without any error on Sublime (clone the repo above and open the file in both editors)

**Comment by izuzak** [comment]
Thanks, @ohwhen. :tophat: That file opens just fine for me in Atom after I clone the repository:

![screen shot 2015-03-24 at 09 12 17](https://cloud.githubusercontent.com/assets/38924/6797739/e956e404-d205-11e4-9414-e9e6c0f47c98.png)

@ohwhen Anything in your config files (init.coffee, for example)? Also, which font are you using in Atom? Just trying to figure out what the difference might be between our setups.

Also, so far only folks on OSX 10.9.5 have reported the issue, wondering if that's related somehow. :thought_balloon:

**Comment by ohwhen** [comment]
@izuzak can you please try scrolling down, the editor crashes in the bottom halve of the file for me

using the atom dark theme, not sure which font it is

**Comment by izuzak** [comment]
@ohwhen Sure. Still works and does not crash:

![crashnot](https://cloud.githubusercontent.com/assets/38924/6798895/d2d5881e-d211-11e4-821e-33189387ba1e.gif)

**Comment by ohwhen** [comment]
@izuzak cheers, this is really weird. I'll have some machines in the office running 10.8 and 10.10 will try and see if I can replicate.

**Comment by lee-dohm** [comment]
I just tried to reproduce and didn't run into a problem. This appears to be fixed 👍
