### ISSUE TITLE
It would be great to have a packages.cson for the apm packages

### ISSUE THREAD

**Issue by misaxi** [atom/atom#5929]
The benefit of keeping packages information in a separate file like packages.cson, is that we can easier to create a portable environment.

So basically (and ideally), I can just need to sync these files to setup up a new atom environment
- config.cson
- keymap.cson
- snippets.cson
- init.coffee
- styles.less
- packages.cson (new)

**Comment by thomasjo** [comment]
I disagree; this is not a configuration concern, this is an installation step. Besides, what you want can be (partially) achieved already.

To persist installed (community) packages execute
``` bash
$ apm list --bare --installed --dev false > packages.txt
```

and then to later install the persisted packages on some other system, simply do
``` bash
$ apm install --packages-file packages.txt
```

**Comment by misaxi** [comment]
Thanks, good to know that I can export it this way. Having said that, I
still would like to see this happening automatically.

As a user, I can see the community packages listed in the settings page.
Why not there is a physical file sitting behind the scenes? So in this
case, sorry, but I would disagree with you. I reckon it is a configuration
concern.

I'm hoping there will be a feature like this. The implementation details
could be totally different.

It is very practical to the users who uses multiple machines (I believe
most people do office/home, laptop/desktop) who wants to sync the
configurations easily.

**Comment by postcasio** [comment]
@misaxi I like to keep my installed packages in a file too so I can version control it. While not automatic, the [http://github.com/lee-dohm/package-sync](package-sync) package can generate a `packages.cson` file for you, and install any missing packages from the file.

**Comment by nnjpp** [comment]
Thanks, @postcasio 

Many of us are coming from other editors where keeping a config repo in github containing the entire editor's configuration is pretty standard and it makes switching from computer to computer pretty seamless. This could be easier in Atom, but I think I'm starting to get the hang of it and package-sync will kind of complete it for me.

**Comment by jammerware** [comment]
I'd really love this feature, too. I'm sort of somewhat new to the open source universe, but the workflow of version-controlling a set of configuration files and pushing them and pulling them to a git repo to keep machines in sync is very intuitive to me. I was actually kind of surprised to find that Atom doesn't maintain the package info in some file this way - does it just crawl the ~/.atom/packages folder to see what you've got installed on launch?
