### ISSUE TITLE
Pasting puts the content at the beginning of the line

### ISSUE THREAD

**Issue by kdelmonte** [atom/atom#5930]
When I paste anything it puts my content on column one even if I wasn't on it. Any way to fix this in the settings?

**Comment by izuzak** [comment]
@keithduncan Does toggling the "Auto indent on paste" option in settings change the behavior for you? Also, a friendly reminder -- it's always helpful if you could [include more details with your issues](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues). :v:

**Comment by keithduncan** [comment]
I think you mean @kdelmonte :wink:

**Comment by kdelmonte** [comment]
Yeah he did... Thanks @izuzak, I'll give it a shot; I thought I was clear enough.

**Comment by izuzak** [comment]
Ahhh, sorry @keithduncan :grimacing: Need to get my :eyes: checked.

> I thought I was clear enough.

@kdelmonte It's always helpful to know which version of Atom you're using (a bug you might be seeing might have already been fixed) and if going through the [debugging steps](https://github.com/atom/atom/blob/master/docs/debugging.md) helped.

**Comment by izuzak** [comment]
Hey @kdelmonte :wave. Wondering if you're able to reproduce this problem in Atom 1.0.11 in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If so, could you share a GIF which clearly demonstrates the problem and let us know which OS you're on, and also paste your config.cson file here?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/5930#issuecomment-139620179. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
