### ISSUE TITLE
Uninstalling Atom does not remove Windows shell integration

### ISSUE THREAD

**Issue by frankhale** [atom/atom#5932]
Uninstalling Atom does not remove the Windows shell integration. When I right click on files I can still see "Open with Atom". 

NOTE: The version I uninstalled was 0.179, on Windows 8.1 x64. I did this for another issue where the updater would constantly be in a downloading Atom state but never finish. I plan on manually installing the latest version of Atom today.

**Comment by frankhale** [comment]
I'm going to try this on another machine in a few minutes to see if its
reproducible. It could be something gone wrong on my home machine and not
Atoms fault.

**Comment by frankhale** [comment]
I think this is an isolated case. I tried on another machine and the shell integration is removed when uninstalling Atom.

**Comment by panfeng** [comment]
https://discuss.atom.io/t/uninstall-on-windows-leaves-context-menu-items/12818

I fixed by removing the "Atom" folder from registry.
