### ISSUE TITLE
Show invisibles breaks auto indent

### ISSUE THREAD

**Issue by kmorey** [atom/atom#5934]
When show invisibles is enabled, the auto indent doesn't handle decrementing indent properly. Seems to happen to me in all grammars. No errors in dev console.

OS X Yosemite 10.10.2 (14C109)
Atom Version 0.187.0 (0.187.0)

![autoindent](https://cloud.githubusercontent.com/assets/48562/6597108/2a12a64c-c7c8-11e4-9006-0f5cad06d75b.gif)

**Comment by kyriacos** [comment]
Glad i searched through the Github issues. 
It wasn't so obvious to me that Show invisibles was causing this.

Thanks. 

:+1:  for a fix experiencing the same problem

**Comment by nathansobo** [comment]
This appears to be fixed on the latest release.
