### ISSUE TITLE
Check for updates not working from Win7 atom 0.182

### ISSUE THREAD

**Issue by jimgraham** [atom/atom#5935]
Windows 7 SP1 x64, Atom 0.182.0

The check for updates fails on one of my machines (even though I know 0.187 is available). The check eventually times out. On startup, the menu changes from "Checking for update" (disabled) to "Check for update" (enabled). If I manually select "Check for update" the check times out and shows the "No update available. Version 0.182.0 is the latest version." message dialog

Is there any kind of Fiddler magic I can provide to attempt to debug this issue?

Thanks.

**Comment by benplumley** [comment]
I only noticed this in 182 but it possibly started earlier: the install directory is no longer program files, but appdata (for some reason). When a new version is installed, it installs to a new directory, but all your shortcuts still point to the old directory. Look in AppData\Local\atom\ and see if you have more recent versions. It's a horrible way of updating and you'll have to manually change your shortcuts (or do some voodoo with batch files) but I found that I actually do have 187, it's just that my shortcuts still all pointed to 182.

**Comment by mark-hahn** [comment]
This is probably a symptom of not clearing out old install methods (maybe
chocolatey?) before switching to the current official installer.  Do a
remove from windows software and manually remove everything else you can
find.  Then a fresh install from the atom.io home page should fix you up.

**Comment by Zireael07** [comment]
I have 180, 182, 184 and 187 all languishing on my HDD.

**Comment by 50Wliu** [comment]
@Zireael07 That sounds like a different issue.  Are you sure you removed all instances of Chocolatey?

**Comment by Zireael07** [comment]
Atom was auto-updated. It should remove all old instances of itself when updating. If that's not the case, then it's a bug.

Now I'm afraid to touch anything in Add/Remove Programs because I don't know which one is which.

**Comment by paulcbetts** [comment]
@Zireael07 Uninstall doesn't remove `~/.atom` (i.e. your settings), so uninstalling both and reinstalling is probably the easiest thing to do

**Comment by benplumley** [comment]
@mark-hahn I have never used chocolatey, I manually installed until the auto-updater was added. I have tried reinstalling to fix this issue. As far as I'm concerned, as long as Squirrel is the updater, I'm better off fixing the various issues by hand than trying to get them resolved.

**Comment by mark-hahn** [comment]
>  I manually installed

That probably also left things in locations not supported by the new
installer.

>  It should remove all old instances of itself when updating

It does, but only ones it created. You can't expect the squirrel updater to
be responsible for removing things installed with other methods.

**Comment by Zireael07** [comment]
@mark-hahn: I never installed manually, I always had the squirrel installer.

**Comment by 50Wliu** [comment]
@Zireael07 what's in the old folders?  I had an issue recently where a folder inside `atom-0.1xx.0` randomly decided to not delete itself which left the entire folder structure intact (but with no actual files inside).

**Comment by paulcbetts** [comment]
Are we shipping update.exe in the manual Atom folder and checking for updates? That is almost sure to cause Weird Stuff to happen

**Comment by Zireael07** [comment]
@Wliu: 180 & 182 disappeared in the meantime.
184 only has the remnants of the resources folder.
186 is complete and usable, to the point of me having to fix a shortcut or two.

Of course, there's also 187 :D

**Comment by 50Wliu** [comment]
@Zireael07 my name is @50Wliu (only because Wliu was already taken)-I've already gotten berated a few times from the real Wliu for people who've accidentally left out the 50 when referencing me ;P.

186 is supposed to be there.  Squirrel keeps an old version just in case bad things happen to the newest version.  You can remove 184-it's probably the bug I said earlier (which is tracked at Squirrel/Squirrel.Windows#239).

**Comment by paulcbetts** [comment]
In new versions of Squirrel, we mark these folders as "Dead", so that even if we can't delete them (though we'll keep trying), we stop trying to execute any code in them

**Comment by oldsharp** [comment]
@jimgraham same platform & same issue with yours, except my atom version is lower (0.176.0).
Looking for solutions...

**Comment by jimgraham** [comment]
I had Chocolatey, but the really old Atom is removed from there. I figure I will just reinstall the latest and see if that starts updating. I guess most updating works for most people on later versions.

**Comment by paulcbetts** [comment]
@oldsharp Just delete `%LocalAppData%\Atom`, download the latest installer and run it, you'll be all set

**Comment by oldsharp** [comment]
@paulcbetts Tried and it works well. Thanks.

**Comment by benogle** [comment]
This seems like it was resolved. Closing
