### ISSUE TITLE
Window resizes to 1px wide sometimes - Usability Issue

### ISSUE THREAD

**Issue by lkarthee** [atom/atom#5938]
It is not consistently reproducible - happens randomly. I have first noticed in 0.186.0 build and seen in 0.187.0 build. I am using Ubuntu 14.04 LTS. 

Did some trial and error when this happens: 
- if i try to open another window from command line like another folder using `atom` the new window opens normally.
-  If try to quit it will close normally. 
-  If i reopen the folder whose window is like 1px wide it will open with same dimension 1px wide. 
  Uploading a screenshot.

![screenshot from 2015-03-11 17 09 30](https://cloud.githubusercontent.com/assets/2712395/6595702/a17d2db6-c812-11e4-9e39-ea46fdbf7013.png)

I feel the user able to minimize window(or because of bug) to such small size is a usability issue as the 1px wide window is difficult to locate and causes confusion to user.

**Comment by tpoisot** [comment]
I've seen that happen to, seemingly at random. In Unity only -- using gnome shell is fine.

**Comment by tkolsen** [comment]
Just had the same problem on Ubuntu 14.10 64-bit.
I had the window up, covering half the screen. When i then tried to press maximize it disappeared. When closing and restarting it started like a 1px wide window that was almost impossible to see.

**Comment by 50Wliu** [comment]
I've hit this maybe once on Ubuntu.

**Comment by robeerob** [comment]
Can not reproduce [my own reported issue](https://github.com/atom/atom/issues/6201#issuecomment-246975869) anymore.

Seems to work for me now, but I have since upgraded to Ubuntu 16.10 and Atom is 1.14.4. Anyone else experiencing this bug on latest Atom, or can the issue be closed?
