### ISSUE TITLE
Add published date to Atom.io

### ISSUE THREAD

**Issue by zephraph** [atom/atom#5946]
It would be useful to have the last publish date presented in a package view on Atom.io. There are some packages out there that were really popular but haven't been updated in a long while. This would give some visibility that a package may potentially or definitely not work with your current install of Atom. 

This would be used for [this](https://github.com/atom/settings-view/issues/424) issue as well.

**Comment by mnquintana** [comment]
Duplicate of atom/apm#277 (it's in apm and not here at @kevinsawicki's [recommendation](https://discuss.atom.io/t/is-atom-io-atoms-website-open-sourced/14197/11), but if it does make more sense here I'd be happy to close the other one)

**Comment by zephraph** [comment]
Closing this in favor of atom/apm#277.
