### ISSUE TITLE
Do not force the installer's splash window above other programs

### ISSUE THREAD

**Issue by oheard** [atom/atom#5955]
I'd like to be able to continue working while Atom installs. It's currently blocking the center 1/6th of my display.

I'm currently trying to fix a VM in XenCenter using the remaining space to the right of the splash window, which has been there since before I started writing this comment.

Appreciate that Atom is cool, but it's not cool enough to prevent users doing anything else with their computers. (It's still there, btw).

**Comment by oheard** [comment]
Update: The splash page has now disappeared and Atom is installed. Back to work.

**Comment by 50Wliu** [comment]
Newer versions of Atom that ship with newer versions of Squirrel.Windows (the installer) will only show the GIF for ~5 seconds before disappearing.  If you still have an issue with that, please open up an issue on the [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) repo.
