### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive:

### ISSUE THREAD

**Issue by basarat** [atom/atom#5957]
This will happen if something calls createIterator in lodash as shown:

![image](https://cloud.githubusercontent.com/assets/874898/6633451/d5082a10-c99c-11e4-8601-0a3a22eec845.png)

In my case I am trying to run gaze https://www.npmjs.com/package/gaze (which in turn depends on lodash)

**Comment by postcasio** [comment]
The usual way around this is to use [https://github.com/atom/loophole](loophole), but in this case I think the call is async, so I don't think it will work :(

**Comment by lee-dohm** [comment]
Closing this since the question was answered.
