### ISSUE TITLE
Can you add a keyboard shortcut for "Toggle Soft Wrap"

### ISSUE THREAD

**Issue by jeffwidman** [atom/atom#5962]
A keyboard shortcut for "Toggle Soft Wrap" would be extremely convenient

**Comment by maxbrunsfeld** [comment]
Add the following to your `keymap.cson`:

```coffee
'atom-text-editor':
  'f10': 'editor:toggle-soft-wrap'
```

**Comment by mark-hahn** [comment]
'.workspace .editor:not(.mini)':
  'ctrl-shift-W': 'editor:toggle-soft-wrap'

**Comment by jeffwidman** [comment]
Thanks!

**Comment by ftcosta** [comment]
Hi,

I'd like too see a default shortcut for soft wrap. Meanwhile, `alt-v···w` looks better than using one of these hacks to me.

- `alt-v` drops the view menu
- `w` toggles wrap

**Comment by TheCopartnery** [comment]
+1

**Comment by msolorzano** [comment]
+1 @ftcosta

**Comment by skapeyi** [comment]
Spent a lot of time trying to turn on soft wrap by default. Was doing `softwrap: true` instead of `softWrap: true`.

**Comment by gismatthew** [comment]
@ftcosta In my Atom 1.19 I have to use curly braces like so:
``` js
editor: {
    softWrap: true
  }
```
The curly braces are there by default. Not sure if it's not necessary but it works for me. Thank you very much. I've been annoyed by this issue for a long time till i found your awesome fix!
