### ISSUE TITLE
Paragraphs selection misses nonempty lines

### ISSUE THREAD

**Issue by yaxu** [atom/atom#5963]
rowRangeForParagraphAtBufferRow misses nonempty lines

From the comment "Right now, a paragraph is a block of text bounded by and empty line or a block of text that is not the same type (comments next to source code)."

But the code will not match lines which contain non-word characters such as punctuation.

https://github.com/atom/atom/blob/f7bb8aab9e33090cc8455cfdf045efe6257568d9/src/app/language-mode.coffee#L183

This means that blocks of code are incorrectly selected if there is for example a trailing bracket on its own line.

**Comment by seansay** [comment]
related https://github.com/seansay/atom-tidal/issues/11
