### ISSUE TITLE
Opening multiple root folders in a single window, from the command line

### ISSUE THREAD

**Issue by brianwestphal** [atom/atom#5964]
It would be great if there were an option to open multiple root folders in a single window, from the command line.  Right now, it opens a separate window for each passed folder.

Atom: 0.187.0

**Comment by 50Wliu** [comment]
This will be in 0.188.0 :smile:.
While we wait for that to be released I believe the `--multi-folder` option will do what you need.

**Comment by brianwestphal** [comment]
Amazing :)  Thanks!
