### ISSUE TITLE
Difficulty building atom on Debian-like system

### ISSUE THREAD

**Issue by drbsci** [atom/atom#5966]
Ran script/build using latest version of atom.  Build failed with output:

Node: v0.10.35
npm: v2.1.17
Installing build modules...
Installing apm...
Installing modules â
> scrollbar-style@2.0.0 install /media/lin/atom/node_modules/scrollbar-style
> node-gyp rebuild

> keyboard-layout@0.10.0 install /media/lin/atom/node_modules/atom-keymap/node_modules/keyboard-layout
> node-gyp rebuild

> nslog@2.0.0 install /media/lin/atom/node_modules/nslog
> node-gyp rebuild

> runas@2.0.0 install /media/lin/atom/node_modules/runas
> node-gyp rebuild

> pathwatcher@3.3.3 install /media/lin/atom/node_modules/pathwatcher
> node-gyp rebuild

> oniguruma@4.0.0 install /media/lin/atom/node_modules/oniguruma
> node-gyp rebuild

> git-utils@3.0.0 install /media/lin/atom/node_modules/git-utils
> node-gyp rebuild

npm WARN cannot run in wd atom@0.188.0 node -e 'process.exit(0)' (wd=/media/lin/atom)
npm WARN engine specificity@0.1.3: wanted: {"node":"~0.8.x"} (current: {"node":"0.10.35","npm":"2.5.1"})
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.21.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/media/lin/atom/node_modules/scrollbar-style/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Linux 3.9-1-mepis64
gyp ERR! command "node" "/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/lin/atom/node_modules/scrollbar-style
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.21.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/media/lin/atom/node_modules/atom-keymap/node_modules/keyboard-layout/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Linux 3.9-1-mepis64
gyp ERR! command "node" "/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/lin/atom/node_modules/atom-keymap/node_modules/keyboard-layout
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.21.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/media/lin/atom/node_modules/nslog/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Linux 3.9-1-mepis64
gyp ERR! command "node" "/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/lin/atom/node_modules/nslog
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.21.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/media/lin/atom/node_modules/runas/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Linux 3.9-1-mepis64
gyp ERR! command "node" "/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/lin/atom/node_modules/runas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.21.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/media/lin/atom/node_modules/pathwatcher/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Linux 3.9-1-mepis64
gyp ERR! command "node" "/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/lin/atom/node_modules/pathwatcher
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.21.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/media/lin/atom/node_modules/oniguruma/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Linux 3.9-1-mepis64
gyp ERR! command "node" "/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/lin/atom/node_modules/oniguruma
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.21.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/media/lin/atom/node_modules/git-utils/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/request/request.js:1176:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1693:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1588:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Linux 3.9-1-mepis64
gyp ERR! command "node" "/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /media/lin/atom/node_modules/git-utils
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.9-1-mepis64
npm ERR! argv "/media/lin/atom/apm/node_modules/atom-package-manager/bin/node" "/media/lin/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/root/.atom/.apm/.apmrc" "--userconfig" "/root/.atom/.apmrc" "install" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! scrollbar-style@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!

**Comment by kevinsawicki** [comment]
This looks like it was a permissions issue with the build folders: `EACCES user "root" does not have permission to access the dev dir "/root/.atom/.node-gyp/.node-gyp/0.21.0"`

You can clean all build folders and reset the permissions using `script/clean`. You can also customize the build directory using the `--build-dir` option to `script/build` to build in a custom location.

Closing this out.
