### ISSUE TITLE
Three finger tap for definitions doesn't work on OS X 

### ISSUE THREAD

**Issue by barksten** [atom/atom#5967]
In a Mac text view or web view, when you three finger tap a word it becomes yellow and a popover window with definitions (from country specific dictionaries and wikipedia) appears. Not so in atom.
I find this very annoying since I use that feature a lot. I'm not sure if this is a bug or a feature request since it is standard in all (not strictly) other similar apps.

**Comment by barksten** [comment]
This is tested on latest mac build 0.187.0

**Comment by mnquintana** [comment]
Looking into this, it looks like it does work in Settings and rendered Markdown, but not in an editor or mini-editor.

**Comment by mathiasvr** [comment]
This seems to be because of the `-webkit-user-select: none;` property in the `editor-contents` and `editor-contents--private` selector.

**Comment by huanzhang** [comment]
When will we fix this?

**Comment by a7744hsc** [comment]
If it is because of -webkit-user-select: none; property in the editor-contents and editor-contents--private selector(As mathiasvr has metioned)? If so, where can I change it by myself? Or I just need edit the source code and compile it ?

**Comment by benogle** [comment]
> -webkit-user-select: none;

Selections are just divs in atom. We'll likely need to do something explicit like https://github.com/kohkimakimoto/atom-dictionary/blob/master/lib/dictionary.coffee to make this work in the editor.

**Comment by ToruHagihara** [comment]
Thanks for your suggestions.

The definitions popup window is very useful because of It's quickness.
the popup window is shown very quickly and hidden by just ESC key.  

already I showed dozen of popup windows while writing this comment. 
I hope there is a solution for this issue.

---
I found a document. Is this has some relations?
In Cocoa application, `showDefinitionForAttributedString()` provides this popup dictionary feature.([document)](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSView_Class/#//apple_ref/occ/instm/NSView/showDefinitionForAttributedString:atPoint:)

**Comment by jerryling315** [comment]
How is this issue going?

**Comment by thedaniel** [comment]
@jerryling315 It's not currently being worked on. From what Ben said above it seems like there isn't a good way for us to integrate with the native OS X popups without changing how selection works entirely in atom, if disabling webkit-user-select is indeed the issue. Alternatively providing an API in Electron for `showDefinitionForAttributedString()` and using it in Atom might work, but only if we could detect the 3-finger-tap in Javascript.

**Comment by ToruHagihara** [comment]
#441 should be same matter and  some suggestions are shown.

**Comment by kklot** [comment]
Still nothing changes.

**Comment by mlg556** [comment]
Just wanted to add that the lack of this makes Atom pretty much unusable to me in English text editing; since I also frequently use the three-tap popup all the time -especially for synonyms-; and synonym plugins for Atom just don't work properly.

**Comment by mmarras** [comment]
I am missing this too.
