### ISSUE TITLE
Select option in autocomplete

### ISSUE THREAD

**Issue by corporatepiyush** [atom/atom#5968]
its very weird to select option shown in autocomplete only my mouse. what key do i need to make use of to select option suggested. i am making use of "enter" key, but it does not work. is it expected behaviour or caused by some external community plugin ?

**Comment by nathanjohnson320** [comment]
Normally you use either tab or enter to select an option.
In the keymap file they're set like this:
```
'.autocomplete atom-text-editor[mini]':
  'enter': 'core:confirm'
  'tab': 'core:confirm'
```

**Comment by corporatepiyush** [comment]
that works for me :+1: 

Thanks Nathan

**Comment by izuzak** [comment]
@corporatepiyush It's strange that enter doesn't work for you. Can you try running Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) and see if that helps? If it doesn't can you share more information, e.g. which version of Atom you're using, which OS, and what the [keybinding resolver shows](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings)?

**Comment by corporatepiyush** [comment]
It works pretty good for me on my personal Mac Pro. But i were having some trouble on Win 7. 
I installed Atom editor 1 month back on Win 7.
