### ISSUE TITLE
Appmenu / Global menu does not work on Kubuntu 14.04

### ISSUE THREAD

**Issue by jonathanverner** [atom/atom#5970]
When running atom (version 0.186.0) in KDE  (4.14.2 from Kubuntu 14.04) with the global menubar enabled, the menu is displayed, but does not work - clicking on any item does nothing, e.g. selecting 'Open File' from the 'File' menu does nothing. 

Moreover, when I quit atom, the plasma-desktop (the main KDE desktop process) crashes. 
This might indicate, that it is a bug in KDE, but I don't know how to figure this out.

Atom version: 0.186.0
OS: Kubuntu 14.04
KDE: 4.14.2

**Comment by jonathanverner** [comment]
This is probably the same Issue as Issue #6255

**Comment by lee-dohm** [comment]
It does sound like a duplicate. I'll close this one since the other has more information. Please subscribe there for updates.
