### ISSUE TITLE
Don't deselect text when searching "Only in selection" if nothing is found, please!

### ISSUE THREAD

**Issue by caitp** [atom/atom#5971]
Repro: highlight some text, search for something which is not found within the text, and become frustrated when you have to re-highlight a potentially very long set of lines to try searching for something slightly different!

Ideally, the selection wouldn't change even if it __did__ find something, but it would just highlight the found items in some way instead.

**Comment by 50Wliu** [comment]
I can't reproduce this.  If nothing is found when searching in a selection the text stays highlighted.

**Comment by 50Wliu** [comment]
This issue was moved to atom/find-and-replace#365
