### ISSUE TITLE
Improve brace matching

### ISSUE THREAD

**Issue by mindplay-dk** [atom/atom#5973]
Brace matching in ATOM is like this:

![image](https://cloud.githubusercontent.com/assets/103348/6656256/f2c59dde-cb23-11e4-9d61-16c3cc9c43e3.png)

In e.g. Php Storm, brace matching prioritizes parens based on their direction - like this:

![image](https://cloud.githubusercontent.com/assets/103348/6656258/15b2e4dc-cb24-11e4-9617-a81e7ba765dc.png)

Why this is better: because, regardless of whether the cursor is over an opening or closing brace, it's matched in such a way that you're typing *outside* the matching parens - consistently.

The way it works in ATOM currently, if I start typing in the first example, I'm typing on the outside of the matched parens - but if I start typing in the second example, I'm typing inside the matched parens. 

Having to cursor right before you start typing after a closing brace, and then having the "wrong" parens highlight when you do, is really confusing.

**Comment by 50Wliu** [comment]
This issue was moved to atom/bracket-matcher#116
