### ISSUE TITLE
Disappearing package option

### ISSUE THREAD

**Issue by pohmelie** [atom/atom#5980]
I've discovered this issue with [atom-terminal](https://github.com/karan/atom-terminal) package. When package option (args, for example) is empty, then in config.cson we see no "args" parameter. After atom restart we will not see "Args" parameter at all. If whe write something like "foo" for this parameter, then line "args: 'foo'" appears in config.cson. So, I think it's about dealing with empty parameters or something like this.
So, before:
![screenshot - 16 03 2015 - 14 21 10](https://cloud.githubusercontent.com/assets/2385765/6665254/4a82744c-cbe8-11e4-8e5b-2c73e69543a0.png)
![screenshot - 16 03 2015 - 14 22 05](https://cloud.githubusercontent.com/assets/2385765/6665253/4a812902-cbe8-11e4-8546-df85825a0b18.png)
After:
![screenshot - 16 03 2015 - 14 22 42](https://cloud.githubusercontent.com/assets/2385765/6665255/4a861ec6-cbe8-11e4-8ab5-3846273e9843.png)
![screenshot - 16 03 2015 - 14 24 03](https://cloud.githubusercontent.com/assets/2385765/6665257/4a88e2a0-cbe8-11e4-98b1-ad4e59809aa6.png)
After restart:
![screenshot - 16 03 2015 - 14 25 00](https://cloud.githubusercontent.com/assets/2385765/6665256/4a879d14-cbe8-11e4-9d16-42f0d28cfa90.png)

**Comment by benogle** [comment]
`atom-terminal` should upgrade [`configDefaults`](https://github.com/karan/atom-terminal/blob/97a70b0acf6c11d3b720b0128b88b72c906dae1a/lib/atom-terminal.coffee#L59-L64) to `config`. See the `defining settings for your package` section of https://atom.io/docs/api/v0.187.0/Config
