### ISSUE TITLE
Lint package builds on Travis

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#5982]
We currently have coffee linting set up to run on core CI builds but package CI builds don't have this.

This causes problems where green PRs get merged on packages but they fail when updated in core since the lint task fails.

**Comment by mnquintana** [comment]
![image](http://www.quickmeme.com/img/d4/d4a888dd9facf35543ae429f296cda146c8239223681279804642557db0fa75c.jpg)

I should've gotten everything – feel free to reopen / ping me if I missed anything @atom/feedback!

**Comment by kevinsawicki** [comment]
:blue_heart: :boat:
