### ISSUE TITLE
:bug: Disable singleTrailingNewline doesn't work

### ISSUE THREAD

**Issue by yordis** [atom/atom#5984]
I added the configuration like was explain it in #399 for disable that configuration but doesn't work.

***Atom version: 0.187.0***

***P.S:*** I didn't change any configuration of Atom.

![screen shot 2015-03-16 at 2 14 27 pm](https://cloud.githubusercontent.com/assets/4237280/6673168/85ec6d4a-cbe7-11e4-9d48-738941fa7313.png)

**Comment by postcasio** [comment]
This setting has moved to the `whitespace` package. You can modify it in the settings for that package.

The setting in `config.cson` is now:

```cson
  whitespace:
    ensureSingleTrailingNewline: false
```

**Comment by wangchi** [comment]
Good!
