### ISSUE TITLE
Keyboard friendly modals when close tab

### ISSUE THREAD

**Issue by bichotll** [atom/atom#5985]
Is there any chance to do this keyboard friendly?

I don't see anyway to close it or change the focus of the buttons with the keyboard.

![screen shot 2015-03-16 at 19 22 27](https://cloud.githubusercontent.com/assets/643359/6673322/6da2f116-cc12-11e4-8148-e33313a5d871.png)

Thanks,
jaume

**Comment by mnquintana** [comment]
@bichotll You can, but it's a system setting, not an Atom setting:

![keyboard_and_keyboard_friendly_modals_when_close_tab_ _issue__5985_ _atom_atom](https://cloud.githubusercontent.com/assets/823545/6673471/c4236f12-cbe9-11e4-99ab-16b84abcd3fd.png)
System Preferences > Keyboard > Shortcuts

Then you can change focus by pressing <kbd>Tab</kbd>.

**Comment by bichotll** [comment]
That's awesome! 
I thought it was app issue...
*I'm new on mac ;)
