### ISSUE TITLE
Support HTML-first workflow

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#5986]
Google Polymer takes an "HTML-first" approach to defining custom elements. Rather than calling a JavaScript method to register an element, you instead use a custom `<polymer-element>` tag to declare elements. The Polymer team had difficulty using this approach in Atom for a couple of reasons.
### Issues running inline scripts due to our content-security policy

This is the biggest hurdle. There's currently no way to white-list script tags in an imported HTML document. A content security policy can be associated with a nonce value that can be inserted into scripts to indicate they are runnable, and it would be nice if we could cascade this nonce through an HTML import to script tags in the imported content.
### Needing to manually insert HTML-imports into the `<head>`

This is easily solvable via a service that presents a function like `loadHTMLDocument(fullPath)`. I'd rather do it with `require`, but Node-style requires are expected to be synchronous and waiting for the imported content to load is async. This would therefore still require a tiny bit of boilerplate in `activate` to interact with the service and load the package's main document.

**Comment by philipgiuliani** [comment]
What you/they mean with "HTML-first"? I googled it and the only thing i find is this issue :D

**Comment by batjko** [comment]
Yea what kind of 'workflow' are we talking about here? What do the Polymer guys do that currently isn't supporting well?

**Comment by nathansobo** [comment]
I updated the body of the issue with more explanation.

**Comment by batjko** [comment]
Makes sense. 
I suppose this is the kind of thing that is best served by a package though, given how you'd circumvent standard policies for a special use case?

**Comment by thomasjo** [comment]
@batjko This wouldn't be possible to solve as a package. This requires changes in Atom core (and maybe Atom Shell?).

---
*Assuming I'm not being ~~an idiot~~ too tired right now*.

**Comment by nathansobo** [comment]
Yeah, we would need to add a `require` handler. I'm thinking we can use the nonce feature with the content security policy to selectively enable inline scripts, but it needs exploration.

**Comment by peterwmwong** [comment]
+1

**Comment by justinfagnani** [comment]
I really like this approach!

It's nearly identical to some experiments we've done in Polymer with integrating HTML imports and JS module definition - requiring a .html document returns the document object from the import. In this way an .html file can be used as a "HTML module".

An extension to this is to allow the .html file to customize its exports, either via `id` attributes, a new `export` attribute, or by explicitly exporting in a JS module:

This uses AMD-style, which we used in our registry, but you could substitute CommonJS, or have the loader adapt.
```
<template id="foo">...</template>
<script>
define(['document'], function(doc) {
  return {
    activate: function() { ... },
    foo: document.querySelector('#foo'),
  };
});
</script>
```

One thing we discussed which I still think would be incredibly nice was to allow extensions to just /be/ custom elements, with the Atom lifecycle methods mapping to custom element lifecycle methods: `activate()` (with no args) would map to `createdCallback()` or `attachedCallback()`, `deactivate()` would map to `detachedCallback()`. Serialization would have to be a separate API.

What's interesting there is that extensions end up with essentially the same API as UI elements. It's all the same "stuff". Custom element extensions could be added to a `<atom-extensions>` element in `<head>`. Simply adding the element would activate the extension.

Going further, serializing `index.html` page would then save the set of activated extensions. Each user could have their own `index.html`, and edit it for customization. If the UI is also set up in HTML, then a user could very easily add or replace parts of the UI by editing their personal `index.html`.

**Comment by paulcbetts** [comment]
How do you handle loading the document asynchronously though? We've taken a similar approach in the Slack app (though ours always starts with JS => HTML + CSS Import), and one thing that has complicated the issue is that the HTML Imports API is asynchronous, so we have to create a Promise (actually an Observable) representing when the content is ready.

**Comment by justinfagnani** [comment]
You only have to wait for the import if it's dynamically inserted by `require()`. I've usually had the import already present in my static files. This would be the case if `index.html` served as the configuration. If the import is added dynamically, then yes, you have to wait for it. With AMD, this is easy. With CommonJS, perhaps you do as you say and `require('foo.html')` returns a `Promise<Document>`.

**Comment by justinfagnani** [comment]
@paulcbetts your link 404'ed for me

**Comment by paulcbetts** [comment]
@justinfagnani hwhoops, copy paste fail, try again

**Comment by nevir** [comment]
> How do you handle loading the document asynchronously though? 

Is Atom performing any async loading under the covers to make CommonJS work in the browser context? (and generally, how is `require` being managed?)

If so, there's also the option of making the loader aware of imports, which turns out [not to be all that bad](https://github.com/nevir/html-exports) (except for when you're targeting the ever-changing loader spec :P)

**Comment by nevir** [comment]
A related concern I have here:

We're going to want to be able to depend on Polymer across multiple atom packages. We can use [APD](https://www.npmjs.com/package/atom-package-dependencies) to express that dependency in order to get an `atom-polymer` installed.

But, in order to force the polymer package to load before us, we'd need to also be able to kick off an `apd.install()` to force the sync load of it, I think? (and then, once we know the package has loaded, stick the `<link rel="import">` in there?)

**Comment by justinfagnani** [comment]
I don't think APD is the right answer, because de-duping custom element dependencies is a pretty hard requirement given the global element registration, so shared packages should really be built in.

**Comment by nathansobo** [comment]
@justinfagnani We'll probably start just with `require` for now, though you could of course define custom elements to interoperate with our existing API however you want.

It *is* concerning that the import API is asynchronous because that was my plan for implementing the require semantics. Require definitely needs to be synchronous, so this may sink my plan. I wish Chromium had an API for creating and populating a new document context that I could just interact with rather than needing to insert an import. Any ideas on that?

**Comment by nevir** [comment]
[`document.implementation.createHTMLDocument`](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementation/createHTMLDocument) gets you part of the way (which we [use in the imports polyfill](https://github.com/webcomponents/webcomponentsjs/blob/4c5f21610c6cea02c74beaa3a25cd8075807ce31/src/HTMLImports/importer.js#L126-153)) - but that just gives you an inert document. Resource loading has to either be done manually, or by stuffing the document in an iframe.

Might be possible to synchronously load some resources given a document (scan for `<link>`, `<style>`, `<script>` elements), but I suspect re-implementing imports like that is going to be very, very thorny.

**Comment by justinfagnani** [comment]
Asynchronous loading might be an issue if you want to directly `require` an `.html` file, but if an extension defines a `.html` file as it's `main`, then I don't immediately see that async is a problem. The extension will have all of its dependencies loaded and run by the time its script(s) runs, and any `require`s it performs can be synchronous.

The system that injects the import would still have to wait for the load, but it shouldn't require any changes to `require`.

**Comment by nathansobo** [comment]
@nevir @justinfagnani What am I to make of the "Imports Block Rendering" section of this [article](http://www.html5rocks.com/en/tutorials/webcomponents/imports/) on HTML 5 Rocks? Is that only for imports that are present at the time of page parsing?

**Comment by nevir** [comment]
Yeah, dynamically inserted `<link rel="import">`s are purely asynchronous and do not block the parser (the file being imported, however, will continue to follow the parser blocking logic)

**Comment by nevir** [comment]
(that's glossing over it a bit; Eric's explanation in that article is correct)

**Comment by nathansobo** [comment]
I would like to insert an HTML import (`<link rel="import">`) tag into the `head`, but the content security policy is getting applied to the imported document and ruling out inline script tags. Even when I assign a nonce to the security policy directive and supply the nonce on the import, the nonce isn't propagated to the `script` tags the imported document, which I suppose makes sense. It would be great if I could do an import where the nonce automatically cascaded to inline scripts that were present at the time of import. 

@zcbenz do you think we could implement a feature like this? One thought is to do a custom protocol handler that dynamically inserts a nonce into script tags in the imported document, but that seems pretty Rube-Goldberg-esque.

**Comment by nathansobo** [comment]
@justinfagnani Do you have any contacts on the Chrome team that would be interested in a better interaction between content security policies and HTML imports? I'd like to be able to cascade CSP nonces from an attribute on the link tag through to script tags present in the imported document at the time of import. Maybe someone could at least provide some guidance on how this behavior could be patched in until something more permanent is worked out? I'd love to get Atom working for you guys but we can't just throw away this security measure entirely.

**Comment by nevir** [comment]
@nathansobo you might want to chime in on https://code.google.com/p/chromium/issues/detail?id=393307 too

**Comment by justinfagnani** [comment]
I think that bug is the best best right now. I'll ask around.

**Comment by metromoxie** [comment]
Hi all. Joel from Chrome Security here. @justinfagnani brought this thread to my attention. The short answer is, yes, we are very interested in making CSP work better with HTML Imports. The long answer is, "it's hard" :-) I've started a thread on the W3C WebAppSec mailing list, which is where we generally discuss CSP (https://lists.w3.org/Archives/Public/public-webappsec/2015Mar/0179.html), to talk about this issue. We'd love to get your thoughts on the ideas floating around there, since you're at the center of this issue. Additionally, if you just have questions for me, feel free to message me.

**Comment by lee-dohm** [comment]
:clap: @metromoxie

**Comment by nathansobo** [comment]
Thanks @metromoxie! Here's a copy to the email I sent to that list for reference:

> Nathan Sobo from the Atom core team here.
> 
> For us, the most intuitive solution would be to allow a nonce attribute to be specified on an import, similar to how a nonce can be applied to an inline script. When applied to an import, the nonce would apply transitively to all script tags in all imported documents. It would only apply for inline scripts present at the time of import. Script tags added to imported documents *after* the fact would not have a nonce automatically applied.
> 
> We use a CSP in Atom to prevent package authors from accidentally inserting script tags into the document, for example, when previewing a markdown document. However, if they're explicitly asking to do an HTML import, then their intent is clear, and we'd like them to be able to run imported scripts if they have access to the current CSP nonce.
> 
> Can anyone articulate to me anything I might be missing here? Would this be a workable solution from a security perspective?

**Comment by nathansobo** [comment]
@justinfagnani Would a `--disable-csp` flag make any difference for you in developing your package before this issue gets figured out at the platform level? It could serve as a stopgap and enable internal usage, but we'd have to get this resolved in order to ship to a general population.

**Comment by justinfagnani** [comment]
I guess, but my stopgap was to edit index.html and just remove the CSP :)

**Comment by nathansobo** [comment]
> I guess, but my stopgap was to edit index.html and just remove the CSP :)

And presumably a flag would be no better then? If finding away around the obstacle is the difference maker for you implementing on Atom, then I want to do what it takes to solve it.

How seriously are you considering Atom? Was it just an experiment, or have you moved further forward? If and when you're a few weeks out from shipping to a general population I can do some crazy antics with custom protocols if it hasn't been fixed in the platform yet.

**Comment by justinfagnani** [comment]
I'm quite seriously considering it, planning on it even, but haven't put a lot of work into it recently. I don't think CSP is a technical blocker for development - a flag or editing the index.html are roughly equivalent for now. Once I want people to try something the flag will be more palatable.

Rather than any antics it'd be better to get the right fix. Another related issue that could be worked on independently of CSP is shared packages. With one global custom element namespace we need to make sure that elements aren't registered twice. This is also fine during development for now, but once there's more than one package using the same widget set it'll be an issue.

**Comment by BLamy** [comment]
:+1:  to this. I'm really not a huge fan of space pen. I really wish I could just create my lib in polymer. Bonus points if the atom API worked with databinding.

**Comment by paulcbetts** [comment]
cc #8697
