### ISSUE TITLE
Clipboard shortcuts on Windows are from DOS 6.x

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom#5989]
Copy / Cut / Paste should be Ctrl-C/X/V, the current shortcuts are the super-old DOS shortcuts for these operations (which should also work, but the above ones definitely should too)

**Comment by postcasio** [comment]
This is just a display issue, and both sets of shortcuts do work, right? But Atom will only show the last defined shortcut in the keymap in menus.

**Comment by paulcbetts** [comment]
Hm, copy-paste *is* broken on my machine using Ctrl-C/Ctrl-V, but I suspect the Vim bindings are at fault here, because it's not _completely_ broken

**Comment by postcasio** [comment]
I would have expected a lot more complaints if they were broken for everyone. All shortcuts are defined in the keymap, but the old style shortcuts are defined last: https://github.com/atom/atom/blob/dccf88063bf9241d83250554a8427ceb4b437389/keymaps/win32.cson#L40

I'm on OS X atm, but at least on that, only the last shortcut is shown on the menu when there are multiple shortcuts for the same command. So this might just be a case of rearranging the keymap.

**Comment by paulcbetts** [comment]
@postcasio I think you're right, this bug is way less bad than I originally imagined.
