### ISSUE TITLE
Why is there no setTextInScreenRange TextEditor API method ?

### ISSUE THREAD

**Issue by postal2600** [atom/atom#5991]
Hope this is the right place for this issue. :sweat_smile:

If there is an [TextEditor API](https://atom.io/docs/api/v0.187.0/TextEditor) method usually comes in both the screen and the buffer "falvor", but for [setTextInBufferRange](https://atom.io/docs/api/v0.187.0/TextEditor#instance-setTextInBufferRange) there is only the buffer version. 

Because of this, I have to convert all my coordinates to buffer coordinates, whereas editor coordinates made more sense and it was more convenient in this case.

Why is there no setTextInScreenRange ? Is the documentation incomplete? Is there a reason behind this ? Or will this probably be added later on ? 

Thank you!

**Comment by mark-hahn** [comment]
>  editor coordinates made more sense and it was more convenient in this
case.

That is unusual.  It is usually easiest to do everything in buffer
coordinates.  Screen coordinates change all the time.
