### ISSUE TITLE
Running "atom <path>" opens folder twice in tree view

### ISSUE THREAD

**Issue by gbrayut** [atom/atom#5992]
When I use `atom <path>` from the command line to open a folder in a new atom window it shows two instances of that folder in the tree view. Example: `atom C:\Code\Go\src\bosun.org` starts a new atom window with two bosun.org folders in the tree view:

![image](https://cloud.githubusercontent.com/assets/304401/6677181/3334fa34-cbf3-11e4-9275-94e91798ecce.png)

Tested on Windows 8.1 using Atom 0.183.0

**Comment by mnquintana** [comment]
You're running an old version of Atom that had some multi-folder bugs – can you try updating to the latest version (0.187.0) and see if you still experience the issue?

**Comment by gbrayut** [comment]
Hmm... thought it was set to auto update but looks like that wasn't working. Uninstalled atom 0.183, deleted temp files in %temp%, and re-installed from https://atom.io/ and now it is working as expected. Thanks!
