### ISSUE TITLE
Soft wrap inserts blank line if no obvious place to break

### ISSUE THREAD

**Issue by ioquatix** [atom/atom#5995]
There is a bug when the line has no obvious point to break:

![image](https://cloud.githubusercontent.com/assets/30030/6678452/dc882384-cc9f-11e4-84ee-27dad2bcebe5.png)

This relates to PR #5567

**Comment by izuzak** [comment]
Interesting, seems to happen only with hard tabs -- it doesn't happen with soft tabs. Thanks for the report! 

@as-cii @nathansobo I was able to reproduce this in Atom 0.183.0 (before #5567) was merged so I'm pretty sure #5567 isn't to blame here. I wouldn't call this issue a priority, but wanted to cc you both :tophat: :tophat: for visibility.
