### ISSUE TITLE
Atom doesn't use snippets in the snippets folder ~/.atom/snippets

### ISSUE THREAD

**Issue by Enkouyami** [atom/atom#6006]
I moved working snippets from the *~/.atom/snippets.cson* file to new individual cson files in the snippets folder in *~/.atom/snippets* (which I had to create) and they stopped working.

**Atom Version**: 0.187.0

**Comment by mnquintana** [comment]
Is this a feature request? I'm pretty sure that Atom only supports a snippets.cson file and not a snippets folder right now.

**Comment by izuzak** [comment]
@Enkouyami Can you explain your motivation -- why would you like to move the snippets.cson file to a different location? Atom expects the snippets.cson file to be where it is now, it can't really know where the file is if you move it around like that.

**Comment by Enkouyami** [comment]
Based on [this latest doc for using snippets](https://atom.io/docs/latest/using-atom-snippets#creating-your-own-snippets) and [this v0.187 doc for snippets](https://atom.io/docs/v0.187.0/using-atom-snippets), "There is also a directory called ~/.atom/snippets that you can fill with multiple json or cson files in the snippets format if you want to organize your snippets in a more coherent way."

**Comment by thomasjo** [comment]
I think the documentation is wrong. The `snippets` folder concept only applies to packages as far as I know. Had a very quick glance over [the relevant code](https://github.com/atom/snippets/blob/master/lib/snippets.coffee#L60-L90) and it seems to confirm my suspicion. Although I might be wrong.

/cc @schacon

**Comment by izuzak** [comment]
Thanks for the :eyes:, @thomasjo! I was looking at the code myself yesterday and forgot to add a comment :grimacing: -- I didn't see anything in there about a `snippets/` folder either. I'm going to close this and open an issue on the docs repository: https://github.com/atom/docs/issues/30

@Enkouyami sorry for the confusion here and thanks for pointing this out. :+1:

**Comment by danielbayley** [comment]
I just published [_modular-snippets_](https://atom.io/packages/modular-snippets). See also https://github.com/atom/snippets/issues/124.
`apm install modular-snippets`
