### ISSUE TITLE
Atom causes SourceTree to crash

### ISSUE THREAD

**Issue by davidgilbertson** [atom/atom#6014]
There is an issue on the SourceTree forums where Atom has been found to be the common factor in a crash on Windows:

https://jira.atlassian.com/browse/SRCTREEWIN-3040

It's also been mentioned in the squirrel repo which appears to be the real cause: https://github.com/Squirrel/Squirrel.Windows/pull/273

Apologies if this doesn't belong here as an issue.

**Comment by paulcbetts** [comment]
Wontfix, Atom is doing you a favor in this instance, that app is a dumpster fire :P

(Also, fixed in https://github.com/atom/atom/commit/3296a3f9e841712b1803f89f1f993264d3bace4f, sorry about the bug, etc etc etc)
