### ISSUE TITLE
Unable to use atom as git commit editor on windows when an instance of atom is already running

### ISSUE THREAD

**Issue by sivapvarma** [atom/atom#6018]
Setting atom as git editor on windows 7 works when I dont have an instance of atom running
```
> git config --global core.editor "atom --wait"
```
But when I am editing a file in atom and do a commit, I get below message even though the commit message tmp file opens in a new tab in current atom window.
```
> git commit
Aborting commit due to empty commit message.
>
```

**Comment by thomasjo** [comment]
Duplicate of https://github.com/atom/atom/issues/3074.
