### ISSUE TITLE
per-buffer configuration

### ISSUE THREAD

**Issue by slang800** [atom/atom#6022]
The editorconfig project uses file-path based rules to manage editor settings, but atom only has language-scoped settings. So, editorconfig can't manage settings like [trim_trailing_whitespace](https://github.com/sindresorhus/atom-editorconfig/issues/3) or [insert_final_newline](https://github.com/sindresorhus/atom-editorconfig/issues/4).

**Comment by caleb531** [comment]
+1

**Comment by vasman** [comment]
+1

**Comment by sindresorhus** [comment]
:+1: Per-buffer config is supported in Sublime btw.

**Comment by wonderbeyond** [comment]
:+1:  for per-buffer settings

**Comment by jacmoe** [comment]
Nothing has happened?

**Comment by florianb** [comment]
This is already solved with the [atom-editorconfig](https://atom.io/packages/editorconfig) package.
