### ISSUE TITLE
Cannot set syntax from command prompt.

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#6023]
I would imagine that pressing `cmd-shift-P`/`Ctrl+Shift+P` would allow me to set the current file's syntax directly by typing e.g. `javascript`. Or at least `cmd-shift-P`/`Ctrl+Shift+P`, then `syntax` or `language`, then `javascript`. But instead, it's hidden in `Ctrl+Shift+L`. Syntax changing should be accessible from the command palette.

**Comment by izuzak** [comment]
It's accessible from the Command Palette, but you need to trigger the "Grammar Selector: Show" command first, and then select the language. Also, there's another package you can install to add this directly to the Command Palette: https://atom.io/packages/set-syntax. Does that help?

**Comment by alexchandel** [comment]
That helps, I was thinking `syntax` or `language` would work instead of `grammar`, since the packages that install them are called variations of `language-*`.

**Comment by izuzak** [comment]
I agree. There's already an open issue for that https://github.com/atom/command-palette/issues/11, so I'm closing this out. Thanks for the feedback! :bow:
