### ISSUE TITLE
HTML Nested Comments

### ISSUE THREAD

**Issue by philsinatra** [atom/atom#6024]
Is there any setting or package out there that can help with nested comments in HTML? 

```html
<div class="container">
  <div class="main">
    <div class="content"></div>
    <!-- /.content -->
    <aside></aside>
  </div>
  <!-- /.main -->
</div>
<!-- /.container -->
```

I want to quickly comment out everything, including the existing comments that mark the end of the divs:

```html
<!--  <div class="container">
    <div class="main">
      <div class="content"></div>
      <!~~ /.content ~~>
      <aside></aside>
    </div>
    <!~~ /.main ~~>
  </div>
  <!~~ /.container ~~>
-->
```

I had to create a [package](https://github.com/philsinatra/HTML-Nest-Comments) for this functionality in Sublime Text. Using the ~~ is not a requirement (I borrowed the idea from BBEdit which supports this natively). 

I teach at Drexel University and we try to get our beginners in the habit of using comments frequently in their code, but we definitely don't want to waste time when we need to block comment something that already has comments. Any insight is greatly appreciated.

**Comment by izuzak** [comment]
@philsinatra Yeah, that sounds like something you'd be creating a package for in Atom as well, I don't think I've seen such a package myself. Check out [the docs](https://atom.io/docs/latest/), and if you have any questions -- asking on [the forum](https://discuss.atom.io/c/packages) should get you some answers. The forum is also a good place to ask if some package exists (if you don't find it yourself in [the registry](https://atom.io/packages)).

**Comment by philsinatra** [comment]
Done. [HTML Nested Comments](https://atom.io/packages/html-nested-comments)

**Comment by izuzak** [comment]
Nice work :sparkles: Just gave it a try and seems to work well. :+1: Gonna close this out since we now have a package for this.
