### ISSUE TITLE
Windows 8.1 - does not open files on double-click

### ISSUE THREAD

**Issue by ttajic** [atom/atom#6029]
If I try to open files (double-click) associated with Atom in Windows Explorer and Atom is not running yet, it does not start Atom at all.

**Comment by 50Wliu** [comment]
What Atom version is this?  Are you using Chocolatey or the new installer?

**Comment by Gethe** [comment]
I'm getting this too using the installer. It seems like Atom was disassociated with the file type, and the app no longer is listed as an option to open the file.

**Comment by ttajic** [comment]
Hi!

I am using

version: 0.184.0.

Installer based installation.

Regards,
Tom




2015-03-19 16:33 GMT+01:00 Gethe <notifications@github.com>:

**Comment by felipekm** [comment]
That's not happening on version: ```0.188.0```

**Comment by varunagrawal** [comment]
Is this still a valid bug?

**Comment by sryze** [comment]
I'm having the same problem on WIndows 8.1 with Atom 0.207.0, files open ok from the command line but not from within explorer.

**Comment by Nom4d3** [comment]
Yesterday it was working perfect. After the update to the 1.0.3 version, I've started to have this issue.

Then I did what @sryze said and find/replace every entry related to Atom and replace the old versions to 1.0.3. Now it's working again.

**Comment by jonmlevett** [comment]
Same issue with Windows 8.1 and Atom v 1.0.4. although this has been affecting me since before 1.0.0 was released.

Right clicking the file and going to Open in Atom works although is inconvenient.

**Comment by sryze** [comment]
Can atom not include its version in install path? That seems to totally mess up file associations.

BTW I came across this bug again with Atom 1.0.5. I also found paths to Atom 0.187.0 (!) installation in the Windows registry, I'm not sure if they are supposed to be updated during install. For example:

```
[HKEY_CLASSES_ROOT\jshintrc_auto_file\shell\open\command]
@="C:\\Users\\szx\\AppData\\Local\\atom\\app-0.187.0\\atom.exe \"%1\""
```

**Comment by damieng** [comment]
Hi.  As of 1.7.0 Atom's installer and updater will correctly register with Windows as an application that can be associated with files (you still have to choose Open With the first time to associate that type but Atom will appear in the list and the path will be correctly updated with each update)

Screenshots over at https://github.com/atom/atom/pull/10818
