### ISSUE TITLE
Update should disable the package in all open atom windows

### ISSUE THREAD

**Issue by basarat** [atom/atom#6032]
Currently it only disables it _only_ in the window where you click the update button. 
# Motivation

Atom-TypeScript runs a separate atom instance (as node) in the background to do the heavy lifting away from the UI thread. We kill this background worker if we get deactivated. 
- _The happy case:_ This means if you only have one atom window open, and run update : the worker is stopped and the files can be deleted and updated by apm. 
- **The issue:** If you have two atom windows open we will have two workers (one with each atom instance). If you start an update in one atom window, the worker will still be running for the other atom window and therefore apm will fail to delete the directory. Furthermore it will delete just enough to leave the whole plugin unusable. 

refs https://github.com/TypeStrong/atom-typescript/issues/195

**Comment by semperos** [comment]
I have reproduced this behavior with the following system setup:

 * Windows 10
 * Atom 1.0.19
 * APM 1.0.5
 * Node 0.12.2
 * NPM 2.13.3

It happened while I tried to update atom-typescript from the Atom UI. I had to uninstall and reinstall the plugin.

**Comment by basarat** [comment]
I see it is tagged as `needs-reproduction`. Here is the repro: 

# Repro 

on windows: 

* If you have two atom windows open, both with some package active.
* If you start an update on the package in one atom window (using settings view), the package is deactivated only in that window. 

This is an issue for atom-typescript that runs a process externally using a javascript file in the code base. Since this `.js` file is locked by windows (because its executing), atom will only manage to delete some files and leave the package unusable. 

Please let me know if there is still some ambiguity :rose:
