### ISSUE TITLE
Can not override or disable the default key 'Alt'

### ISSUE THREAD

**Issue by mengzyou** [atom/atom#6037]
I customize `Alt-m` key binding to toggle menu-bar display/hide.  
> 'body':
> 'alt-m': 'window:toggle-menu-bar'

But, the defalut key `Alt` is still available.  

This always cause the menu-bar display/hide actions when I use `Alt` key for others.  
So, hope to disable or override the default `Alt` keymap.

-------------------------------------
Version: 0.187.0
OS: Linux

**Comment by opsr** [comment]
I also need this. I use alt + left/right to switch windows and whenever I get to atom and release alt, the menu bar will pop.

**Comment by dwelle** [comment]
I second that. I use custom `alt-i/j/k/l` for caret movement. Didn't notice this until I made the menu bar to auto-hide (although it's not surprising behavior).

**Comment by joerideg** [comment]
+1

**Comment by giyyapan** [comment]
Same issue.
Trying to map `alt-f` to emacs-like move-to-end-of-word, but aways trigger `File` tab in menubar.

I'm using Ubuntu 14.10

**Comment by uptownhr** [comment]
so any progress here? Can't use emacs bindings because of this.

**Comment by giyyapan** [comment]
@uptownhr 
try this:
```coffee-script
# in your init.coffee
atom.menu.template.forEach (t) ->
  t.label = t.label.replace("&", "")
atom.menu.update()
```
got this method from here https://discuss.atom.io/t/alt-key-menu-bar-interaction-overrides-shortuts/9192/7?u=giyyapan
BTW, I'm using Ubuntu

**Comment by LoLei** [comment]
@giyyapan Sadly didn't work, `alt` still opens the menu bar with this.

**Comment by giyyapan** [comment]
@LoLei  Well, I've got no other idea then. 
Sorry :cry:

**Comment by uptownhr** [comment]
@giyyapan that worked for me. I'm on ubuntu 14.04.

**Comment by LoLei** [comment]
@giyyapan It's okay, thanks for the effort!

**Comment by VoronaPavel** [comment]
This is also happening to me.
Windows 10, Windows 7

**Comment by angelojulioth** [comment]
I hope they could fix this soon...I don't like to have a menu or window decorations, a lot of the hotkeys I use with my OS use the alt key so this is very obnoxious.

**Comment by angelojulioth** [comment]
This worked for me, I'm using Ubuntu with i3wm and OpenBox
Add this to your keymap.cson
'atom-text-editor':
    'alt': ' '

I hope this works for you guys :) ...this was driving me crazy.

**Comment by hobofan** [comment]
@angelojulioth Thank you, worked like a charm!

**Comment by LoLei** [comment]
@angelojulioth Thanks so much, that did the trick.

To rebind it to another key, you can add something like this in the keymap file:

```
'.platform-win32, .platform-linux':
  'ctrl-q': 'window:toggle-menu-bar'
```

Although that makes the info popup window open everytime...

**Comment by kankaristo** [comment]
The below fixed this completely for me (on Ubuntu):
```
'.platform-win32, .platform-linux':
  'alt': 'abort!'
  'alt-f1': 'window:toggle-menu-bar'
```

This actually works for disabling the default `Alt` binding as well!

It behaves a little differently than `Alt`, because the menu bar stays visible until you toggle it back off (and there's the popup, like @LoLei mentioned). I don't mind the "permanent" toggle, I actually prefer it that way.

**Comment by VoronaPavel** [comment]
@kankaristo that worked for me

**Comment by mengzdsd** [comment]
@kankaristo Yes, it works, thank you!

**Comment by angelojulioth** [comment]
@LoLei  Your rebinding idea was great, It worked...but now that I'm using Arch Linux the '.platform-win32, .platform-linux': line doesn't work anymore, I don't know why, but my solution works great, and I can still toggle menu from the settings window(if I ever need it), so If there's any other Linux user here using any other distro than Ubuntu and reading this, they can still bind alt key to nothing and rebind to other keys if they want to. You should already close this issue @mengzdsd :)

**Comment by leonardoarroyo** [comment]
@kankaristo fix works. Thanks! +1

**Comment by pcnate** [comment]
@kankaristo This works. However this now pops up a notification about the menu bar getting hidden.

**Comment by mengzyou** [comment]
```
'.platform-win32, .platform-linux':
  'alt': 'abort!'
  'alt-f1': 'window:toggle-menu-bar'
```

With @kankaristo 's solution, this issue can be closed.
