### ISSUE TITLE
For the love of baby Jesus, fix the autocompletion.

### ISSUE THREAD

**Issue by youssefdetovernickr** [atom/atom#6043]
It's so bad compared to concurrents like Brackets.io, especially in HTML code. 

As example: if you type in '<d' the first thing that comes up at the autocompletion is everything except <div>. If you type anything in JavaScript it doesn't even come up with autocompletion. 

Now compare it to Brackets.io, if you type anything in JavaScript it actually autocompletes it, and even shows linting errors. It even shows your custom functions, and if you document your functions it even shows in the autocompletion! 

Please take an example from this, or something like PHPStorm. This is one of the reasons a lot of people don't want to switch over to Atom (yet).

**Comment by benogle** [comment]
Working on it as we speak. Closing in favor of #4364
