### ISSUE TITLE
Uncaught Error: ioctl(2) failed.

### ISSUE THREAD

**Issue by beoran** [atom/atom#6054]
[Enter steps to reproduce below:]

1. Turn on "Auto Hide Menu Bar" in the core settings
2. Press Alt

**Atom Version**: 0.187.0
**System**: linux 3.13.0-45-generic
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ioctl(2) failed.

```
At /home/bjorn/.atom/packages/term/node_modules/pty.js/lib/pty.js:331

Error: ioctl(2) failed.
  at Error (native)
  at Terminal.resize (/home/bjorn/.atom/packages/term/node_modules/pty.js/lib/pty.js:331:7)
  at TermView.resizeToPane (/home/bjorn/.atom/packages/term/lib/TermView.js:115:12)
  at delayed (/home/bjorn/.atom/packages/term/node_modules/debounce/index.js:19:14)

```

### Commands

```
  4x -8:36.8 core:backspace (atom-text-editor.editor.mini)
  9x -8:33.5 core:confirm (atom-text-editor.editor.mini)
 14x -8:20.3 core:backspace (atom-text-editor.editor.mini)
  4x -8:14.9 core:confirm (atom-text-editor.editor.mini)
  6x -4:54.6 core:backspace (atom-text-editor.editor.mini)
  3x -4:47.6 core:confirm (atom-text-editor.editor.mini)
 32x -2:27.8 core:move-down (atom-text-editor.editor)
  9x -2:25.6 core:move-up (atom-text-editor.editor)
 18x -2:24.6 core:move-down (atom-text-editor.editor)
  3x -2:23.1 core:move-up (atom-text-editor.editor)
  2x -1:21.6 core:move-down (atom-text-editor#editor.fontSize.editor.mini)
  2x -1:20.9 core:move-right (atom-text-editor#editor.fontSize.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-terminal-panel",
      "terminal-panel",
      "terminal-status"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "softWrap": true,
    "softWrapAtPreferredLineLength": true,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
language-cmake, v0.1.1
minimap, v4.6.0
term2, v0.9.4

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Please report this to the term2 package.

**Comment by beoran** [comment]
It seem like many, if not most atom plugins are now in various states of being unusable due to the deprecation of the previous API. I don' t have the time now to hunt down or even report all these bugs. I only reported this one because it went automatically. I'll wait until atom hits 1.0 and try again then, hopefully I'll be less disappointed then.

**Comment by 50Wliu** [comment]
Deprecated APIs still work (I believe they just call the updated methods instead).  Bugs like these indicate that the package itself is doing something wrong, not because they're relying on deprecated methods (those get reported to the `deprecation-cop` repo).
