### ISSUE TITLE
Converting spaces <-> tabs should only apply to a selection when one exists

### ISSUE THREAD

**Issue by dantman** [atom/atom#6056]
When the user has made a selection, the convert spaces to tabs and convert tabs to spaces options should only apply to the selected lines.
((If you have some reason to dislike this behaviour, please at least make it a preference))

I had the unexpected experience of trying to correct the spaces in a small spot of a file and finding that not only were the leading spaces elsewhere in that file converted, but spaces in the middle of the line that were used for `=>` alignment were converted into tabs (and into the wrong number of tabs).

**Comment by izuzak** [comment]
Surprise -- this is implemented in a package as well. :smile: https://github.com/atom/whitespace

Mind reopening this on that package's issue tracker?

**Comment by izuzak** [comment]
For reference, the issue was re-opened here: https://github.com/atom/whitespace/issues/63
