### ISSUE TITLE
Indicator to control per-document indentation options

### ISSUE THREAD

**Issue by dantman** [atom/atom#6057]
Atom needs an indicator in the lower right displaying the current spaces/tabs setting for the document. Which should also give access to options that control the per-document indentation settings.

Attempting to auto detect indentation is fine. But for a developer that works on projects all over, indentation practices are anything but reliable. User, syntax, and project settings just don't cut it for picking up a random library, making a small tweak, and then submitting it. Changing the per-document settings should be a few quick clicks.

This is standard in other editors like Atom. And I find it is used even more often than the encoding indicator Atom has already added.

**Comment by izuzak** [comment]
For now, you might consider building or using an existing package for this. Here are two related packages I found (haven't tried them out, though): 

https://atom.io/packages/resize-indent

https://atom.io/packages/indentation-indicator
