### ISSUE TITLE
Incremental find

### ISSUE THREAD

**Issue by dantman** [atom/atom#6058]
Here's another Sublime Text feature Atom doesn't have that Sublime users may miss.

{`Cmd`,`Ctrl`} + `i` starts an incremental find, which works like {`Cmd`,`Ctrl`} + `f` but jumps to the first match as you type and closes when you hit enter.

It's great for quickly getting to a different part of the file.

**Comment by izuzak** [comment]
Thanks for the feedback, @dantman. The find/replace functionality is not a part of Atom's core, it's implemented in a package which ships with Atom by default: https://github.com/atom/find-and-replace. To make package-related issues/requests easier to find, could you re-open this issue on that package's issue tracker? :pray:

Also, a few interesting bits:
* It seems that someone started working on this a year ago: https://github.com/atom/find-and-replace/pull/178
* There's a community package which seems to provide that ability, so you might want to try that out: https://atom.io/packages/incremental-search.
