### ISSUE TITLE
Failed to load the angularjs-helper package

### ISSUE THREAD

**Issue by teslavsedison** [atom/atom#6060]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Failed to load the angularjs-helper package

```
At reserved word "function"

[stdin]:1:33: error: reserved word "function"
service('fileUpload', ['$http', function ($http) {
                                ^
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "editor": {
    "fontSize": 23,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-angularjs, v0.1.2
atom-django, v0.2.1
autoclose-html, v0.15.0
autocomplete-plus, v2.6.0
color-picker, v1.5.0
language-arduino, v0.2.1
language-csharp, v0.5.0
language-cshtml, v0.1.0
linter, v0.12.0
linter-cpplint, v0.1.3
linter-htmlhint, v0.0.8
linter-jshint, v0.1.0
minimap, v4.6.0
pretty-json, v0.3.2

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Seems like a problem with the https://github.com/orlaqp/angularjs-helper package or how you were using it. If you can reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) -- let us know. If you can reproduce this with that package -- open an issue on the package's issue tracker.
