### ISSUE TITLE
Question: How to open it again?

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [atom/atom#6064]
I installed normally, now, i cant find any atom  folder/shortcut, anything, i opened 1 time, and now i cant open it again. Tried to install again but the installer just "autocloses" .

**Comment by mnquintana** [comment]
What OS?

**Comment by Nitrogen-Dioxide** [comment]
Windows 7 64 bits.

**Comment by Rhywun** [comment]
I have the same issue on Windows 7 32-bit.  The Windows installer does not add shortcuts to the desktop or start menu, nor does it install the command line tools.  From using the chocolatey version in the past, I know the app is installed in a very non-obvious place, in my case:

%localappdata%\atom\app-0.188.0\atom.exe

But it is frustrating to have to create my own shortcuts.

The chocolatey version does install everything but I had deleted everything I could find before trying the Windows installer, including %localappdata%\atom and ~\.atom.

It looks like the chocolatey version is still the way to go for now.

**Comment by kevinsawicki** [comment]
This looks like a possible intermittent issue with the auto updater library, Squirrel, that is use by both the installer and chocolatey.

Hopefully this has been resolved in recent upgrades and should no longer happen, so I'm going to close this out.
