### ISSUE TITLE
[Not a bug] Metrics plugin: Proper way to tell user that the metrics are collected

### ISSUE THREAD

**Issue by squarerootfury** [atom/atom#6067]
Hello,

I found out that Atom collects analytic data to improve the program. There is nothing bad about this idea. But I think, it would be a better way to ask the user to Opt-In this analytics.

Currently, the user has to disable the metrics plugin (= do an Opt-Out), but I think there should be at least a clear information at the first run to tell the user that data is collected and if he/ she wants to allow the collection of this data. 

Otherwise, this situation could cause maybe sooner or later problems in countries with stricter data privacy laws, e. g. Germany. And nobody wants that.

Please correct me if I just over read an info about this topic or this issue is a duplicate.

Kind regards
squarerootfury

**Comment by mark-hahn** [comment]
Dup of https://github.com/atom/atom/issues/5669

**Comment by squarerootfury** [comment]
Thanks for the info. I'm closing this to prevent further redundand comments on my issue
