### ISSUE TITLE
Font wont change in Linux

### ISSUE THREAD

**Issue by 2bdkid** [atom/atom#6069]
I have Atom 0.187 installed on Fedora 21 and when I set the font to something like DejaVuSansMono or DroidSansMono nothing happens. It defaults to some other font.

I tested DejaVuSansMono in Windows 8 on 0.187 and it worked fine.

**Comment by mnquintana** [comment]
Is that the exact font file name on your Linux box? e.g. `DejaVuSansMono` with no spaces? If it doesn't match exactly it won't find and apply the font.

**Comment by 2bdkid** [comment]
It's /usr/share/fonts/dejavu/DejaVuSansMono.ttf

**Comment by 2bdkid** [comment]
I found what was wrong, it should be "DejaVu Sans Mono" rather than "DejaVuSansMono".
