### ISSUE TITLE
Show the unsaved file while displaying the 'unsaved changes' alert at closing.

### ISSUE THREAD

**Issue by botverse** [atom/atom#6070]
If you have several files with unsaved changes, when you try to exit the application you will only see the current open buffer when clicking discard. Atom should show you the particular buffer about to be saved or discarded.

I have atom 0.144.0 on an ubuntu 14.04

Similar problem here: #5823

**Comment by mnquintana** [comment]
You're running an extremely old version - can you update to the latest version of Atom first (0.187.0)?

**Comment by botverse** [comment]
0.187.0 did the same thing
