### ISSUE TITLE
Clipboard cleared when deleting line with Shift+Del after cuting content

### ISSUE THREAD

**Issue by juanstiza** [atom/atom#6073]
When selecting a line and pressing Shift+Del, if I previously had cut some content, it gets removed from the clipboard.

**Comment by 50Wliu** [comment]
I might be understanding this wrong, but it seems like <kbd>Shift+Del</kbd> is mapped to `core:cut` on Linux and Windows(?), which means that stuff in your clipboard should be replaced by the newly cut text.

**Comment by juanstiza** [comment]
Ha! didn't notice that on Windows, but I'm on Linux right now and it makes perfect sense... Did not know it was default behaviour on Linux. Thanks!
