### ISSUE TITLE
Using "use babel"

### ISSUE THREAD

**Issue by robhicks** [atom/atom#6076]
How does the built-in babel support work? 
In the babel docs, it identifies various ways to use babel in build systems. 
If I have an a file named foo.js with uses the "use babel" pragma where does the file get transpiled to? Obviously, it can't/shouldn't overwrite foo.js.

**Comment by kevinsawicki** [comment]
> If I have an a file named foo.js with uses the "use babel" pragma where does the file get transpiled to? 

It gets transpiled on the fly and cached in a separate location.  So the file will not be overridden but instead be written via a cache id which is the SHA-1 of the contents of the file.

**Comment by robhicks** [comment]
@kevinsawicki Thanks for the answer. 

That helps but what I want to know is then how to I work with the transpiled files? With CoffeeScript, my .coffee files get transpiled to .js files.

**Comment by kevinsawicki** [comment]
> That helps but what I want to know is then how to I work with the transpiled files?

Any files you require that start with `use 'babel'` will be transpiled on demand when they are required, so things should just work and you shouldn't need to do anything past setting the `use 'babel'` line at any files you want transpiled.

**Comment by robhicks** [comment]
I'm still confused. How do I get output suitable for running on say node, or in a browser? Can you point me to an example?

**Comment by kevinsawicki** [comment]
The built-in babel support is only for developing Atom packages, it isn't for developing node or browser apps.

**Comment by robhicks** [comment]
Ah, too bad. Thanks!

**Comment by piotr-cz** [comment]
I think it should be mentioned in bold in the [blogpost anouncing Babel/ 6to5 support](http://blog.atom.io/2015/02/04/built-in-6to5.html): _Atom packages_ instead of just _packages_.
