### ISSUE TITLE
syntax highlighting bug on objective c file

### ISSUE THREAD

**Issue by scgaw2000** [atom/atom#6080]
The double quotation mark after a backslash is not the end of NSString construction. As a result, the following code should be highlighted as 

```objective-c++
if (![string isEqualToString:@"\t\n\"123") {
	// do somthing
}
```

but not
![screen shot 2015-03-24 at 13 27 02](https://cloud.githubusercontent.com/assets/3814422/6796279/05410c06-d22b-11e4-8458-b9462ad1933d.png)

Using version 0.187.0 (0.187.0) on OS X 10.0.3 beta

**Comment by izuzak** [comment]
This issue was moved to atom/language-objective-c#7
