### ISSUE TITLE
project not index properly

### ISSUE THREAD

**Issue by seansay** [atom/atom#6081]
![screen shot 2015-03-24 at 7 41 10 pm](https://cloud.githubusercontent.com/assets/349342/6800982/a57dae9e-d25e-11e4-9911-2842e58de6dc.png)

not sure when did this start happen, but serveral of my python project stop index properly, anybody have this issue?

**Comment by izuzak** [comment]
Can you please reopen this on the [fuzzy-finder repository](https://github.com/atom/fuzzy-finder) and provide a bit more [information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)? Thanks! :apple:

**Comment by seansay** [comment]
thx for direct me here, looking for similar issue and saw `Follow symlinks` optiom, solve my problem! thanks
