### ISSUE TITLE
Atom should save new files where the last opened/saved file was

### ISSUE THREAD

**Issue by rbu** [atom/atom#6088]
When you create a new buffer and hit save, Atom will present me with a save dialog and the default selected folder is the project root. That's almost never the place I want to put a file.

Sublime Text was a lot smarter with this -- although I do not remember the exact heuristics. For example, it would propose saving the file in the same location where the file you last had opened was. This worked really well for me: Usually I create a new file by splitting an existing file, creating a test for a module (and those two are in directly adjacent directories) or similar.

Even if I want to save to the root directory, which is the current behavior, navigating upwards in the file save dialog is really simple.

PS: I am using Atom 0.187.0

**Comment by mark-hahn** [comment]
>  it would propose saving the file in the same location where the file you
last had opened

Every app, not just editors, does this.

**Comment by vrinek** [comment]
I agree that Sublime's heuristics for choosing where a new file should be create worked really well for me too :+1:

**Comment by mnquintana** [comment]
I'm going to close this in favor of https://github.com/atom/atom/issues/7110, which more accurately describes Sublime's heuristics for opening file system dialogs.

**Comment by entozoon** [comment]
This issue should be re-opened because the other topic dealt with, and added, the feature only for opening a file not saving.
The feature request in question here is that, when you open a new file and save it - the default location should be that of the last opened file rather than project root.
(as sublime does, and is brilliant)

**Comment by pbeshai** [comment]
Please re-open this. It's very surprising to have the save dialog open at the project's root directory, and somewhat frustrating to have to re-navigate to the folder I was just in.

**Comment by humanfactors** [comment]
I agree, it's a usability issue, an extension would be super useful. I find myself using nvatom a lot to take quick notes, I wish atom allowed a command - N to automatically create a new file relative to project root as per [notebook](https://atom.io/packages/notebook)

**Comment by AlexisJackson** [comment]
I jump from project to project in my company, and find myself having to re-path in the Save window to the current directory I'm in. I may be wrong, but this feels like a new thing. Did Atom never at least use the directory you have open in Atom to save in? That definitely is not the case for me currently.

**Comment by 50Wliu** [comment]
@AlexisJackson You might be running into #13978.

**Comment by rbu** [comment]
@50Wliu, would you mind reopening this issue as this is still not fixed. #7110 addressed the default open directory (CTRL+O), while this issue is about the default save directory (CT.

**Comment by 50Wliu** [comment]
Can you please read the issue I linked above and see if that is what you are experiencing?

**Comment by rbu** [comment]
In 2015 when I reported this bug, "File Save" would go to the project directory that was active when Atom was started. My proposal was to use the the directory of the last opened file. You are correct, currently I am experiencing #13978, i.e. "File Save" goes to a random directory.
However, this issue here was not about bringing back the "2016" behavior, but actually improving the heuristics (just like with "File Open"). I'm also happy if that is where #13978 is going.

**Comment by mrbrahman** [comment]
If there is a vote on the most wanted features, I would do a +1 for this one! Really missing this in Atom :-)

**Comment by erinata** [comment]
The issue is closed for so many times but Atom is still saving new files at the root of the project. I still do not get why "last opened file location" is not the default but I think this package can mimic the behaviour of sublime text.

https://atom.io/packages/smart-save

**Comment by davepile** [comment]
Smart Save doesnt work for me either. Windows 10 Atom 1.31.1 x64

This is very annoying behaviour

**Comment by valkalon** [comment]
Hello Guys, I was also facing this situation, I tried Smart Save which didn't work either for me. 

I created a package and confirm the feature works (Ubuntu 16.04 Atom 1.31).

Please give it a try, I'll be happy to receive your feedback and to update it if needed.

package name: 

**save-where-last-buffer-was**


https://atom.io/packages/save-where-last-buffer-was

**Comment by dos09** [comment]
Such basic feature is still missing (this issues is from March 25, 2015)

**Comment by valkalon** [comment]
@dos09 Does my plugin solve the problem for you?

**Comment by dos09** [comment]
@valkalon It's not working for me, still opens the root directory (I'm using Atom 1.38.2 x64 on Linux Mint)

**Comment by valkalon** [comment]
Ok, I will investigate and check how to solve it by the end of the month.
