### ISSUE TITLE
Failed to activate the punchclock package

### ISSUE THREAD

**Issue by stevenazari** [atom/atom#6090]
[Enter steps to reproduce below:]

1. ... Install punchclock
2. ...reload atom

Error: [Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.13.0-46-generic
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the punchclock package

```
At undefined

- Timekeeper is active & functional only with a valid project open
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "followSymlinks": true
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.5.0
linter, v0.12.0
linter-php, v0.0.11
minimap, v4.6.0
punchclock, v0.5.0
wakatime, v4.0.1

# Dev
No dev packages
```

**Atom Version**: 0.188.0
**System**: linux 3.13.0-46-generic
**Thrown From**: Atom Core

### Stack Trace

Failed to activate the punchclock package

```
At undefined

- Timekeeper is active

**Comment by thomasjo** [comment]
You need to re-open this issue on the [punclock repo](https://github.com/queenp/punchclock/issues/new).

---
The offending line is https://github.com/queenp/punchclock/blob/master/lib/timer.coffee#L79, which is not properly handled in the `initialize` function in `punchclock.coffee`.

**Comment by thomasjo** [comment]
Nevermind, I see you've already opened [an issue there](https://github.com/queenp/punchclock/issues/1), so I'm closing this.
