### ISSUE TITLE
Allow Command+W to close windows, not just tabs

### ISSUE THREAD

**Issue by mcandre** [atom/atom#6092]
On Mac OS X, many applications allow users to close tabs and windows with the same hotkey, `Command + w`. Could Atom respect this convention as well?

**Comment by mnquintana** [comment]
Do you mean that <kbd>Cmd+W</kbd> should also close the window if there are no tabs open?

**Comment by mcandre** [comment]
Aye.

**Comment by izuzak** [comment]
I believe this is a duplicate of https://github.com/atom/atom/issues/863.
