### ISSUE TITLE
Default Settings tab to Install section

### ISSUE THREAD

**Issue by mcandre** [atom/atom#6093]
Most of the time when I visit Settings, I intend to install something. If other users feel this way, could we have the Settings tab to open the *Install* section by default, for speed?

**Comment by thomasjo** [comment]
This is unlikely a sensible default to most users, but you can easily make this the default behavior on your machines by adding something like this to your `~/.atom/keymap.cson` file

``` coffeescript
'atom-workspace':
  'cmd-,': 'settings-view:install-packages-and-themes'
```
