### ISSUE TITLE
Failed to load the supercopair package

### ISSUE THREAD

**Issue by loudowl** [atom/atom#6096]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Failed to load the supercopair package

```
At unmatched }

[stdin]:9:101: error: unmatched }
    'SupercoPair: Broadcast cmd-period exclusively', 'supercopair:broadcast-cmd-period-exclusively' },
                                                                                                    ^
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "editor": {
    "fontSize": 11,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-pair, v0.37.0
autocomplete-plus, v2.3.0
color-picker, v1.4.4
git-log, v0.3.0
highlight-selected, v0.9.1
language-ejs, v0.1.0
linter, v0.12.0
minimap, v4.4.0
monokai, v0.12.0
preview-tabs, v0.1.2
vim-mode, v0.34.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@loudowl This seems to be a problem with the supercopair package -- I'd suggest re-opening the issue over at https://github.com/deusanyjunior/atom-supercopair, but it seems that project has issues disabled. Still, this doesn't seem to be a problem in Atom so I'm closing the issue. Atom's mechanism for detecting where an issue should be opened needs some tweaking to cover these cases, it seems.

**Comment by izuzak** [comment]
@kevinsawicki was this supposed to be detected by https://github.com/atom/atom/pull/6078 or is this another special case?
