### ISSUE TITLE
Dumped core

### ISSUE THREAD

**Issue by ghost** [atom/atom#6105]
Hello github,

After reading couple reviews in internet regarding your text editor decided to give it a shot.

Your text editor is outstanding, but what worries me is that it is trying to connect to some ip and my firewall is set to deny unauthorized (in/out) connections. 

I've used the latest build on archlinux.

Shortly after it is started the whole editor just disappears, and **dmesg** , **journalctl --catalog --lines --priority=0..3** , **coredumpctl info** reveal additional information. **gdb** helps even further with:

```
coredumpctl gdb 1894
           PID: 1894 (atom)
           UID: 1000 (frost)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Thu 2015-03-26 01:41:29 EET (26min ago)
  Command Line: /usr/share/atom/atom --type=gpu-process --channel=1869.0.606562709 --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,24,36,39 --disable-accelerated-video-decode --gpu-vendor-id=0x1002 --gpu-device-id=0x9616 --gpu-driver-vendor --gpu-driver-versio
    Executable: /usr/share/atom/atom
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (frost)
       Boot ID: 938648a15754441ab3f28968d36a1772
    Machine ID: 1a9fbe7f4dd94e12b4f7add871bf1f29
      Hostname: localhost
      Coredump: /var/lib/systemd/coredump/core.atom.1000.938648a15754441ab3f28968d36a1772.1894.1427326889000000.lz4
       Message: Process 1894 (atom) of user 1000 dumped core.

/usr/share/atom/atom: No such file or directory.
[New LWP 1894]
[New LWP 1898]
Core was generated by `/usr/share/atom/atom --type=gpu-process --channel=1869.0.606562709 --no-sandbox'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fac53772e2c in ?? ()
```

I've taken a picture, but for some reason I'm not allowed to attach pictures, so here it is as external link - https://i.imgur.com/KSTbOgT.png

edit: If you want me to attach the compressed coredump archives just let me know.

Cheers

**Comment by DavidLGoldberg** [comment]
I'm not a core dev, but I do believe Atom has a stats package.  Also, I'd like to think that's not causing the crash.

**Comment by nathansobo** [comment]
@wifiextender You can disable the metrics package in the settings view. Its source is open and you can see it isn't collecting anything sensitive, but you're also welcome to turn it off. I'll leave this open so we can investigate the crash.

**Comment by wifiextender** [comment]
Hello David and Nathan,

The text editor closes itself shortly after it is started. I can barely see the welcome page and then it disappears without any notice or segfault reported back to me.

I saw that there was "Atom Crash" folder in my **/tmp** directory but the folder was empty, that is why I had to use gdb, dmesg and coredumpctl to find out why it disappeared without any notice that something has happened in the background.

[These](https://github.com/wifiextender/dotfiles/blob/master/archlinux-openbsd/home/frost/OPEN_ME/installed_packages.txt) are the packages installed on my system, and [that](http://wifiextender.github.io/img/file/my-pc/final-result.jpg) is my primary computer hardware, and [here](http://wifiextender.github.io/img/file/openbox-2-dwm.jpg) it is a screenshot.

Thank you for the tips guys.

Cheers
