### ISSUE TITLE
Pane focus (left, right) doesn't work

### ISSUE THREAD

**Issue by andersennl** [atom/atom#6107]
Hi, I hope I'm not mistaken by posting here and the panes are part of Atom's core. I'm using these keybindings to move between different panes.

```cson
'body':
  'ctrl-alt-left': 'window:focus-pane-on-left' # works
  'ctrl-alt-right': 'window:focus-pane-on-right' # works
  'ctrl-alt-up': 'window:focus-pane-on-above' # doesn't work
  'ctrl-alt-down': 'window:focus-pane-on-below' # doesn't work
```
The problem is, the last two don't work. The first two do. All of them map to the correct commands in Atom (the key binding resolver shows the correct mapping for all of them in green). 

There are no logs in the dev-tools console nor the OSX Console.app. The problem as well occurs in safe mode. Thanks for your help.

I'm using OSX version: 10.10.2 (14C109) and Atom version: 0.188.0.

**Comment by postcasio** [comment]
The commands should be `window:focus-pane-above` and `window:focus-pane-below` as in the [builtin keymap](https://github.com/atom/atom/blob/c46088e89ab8a36fd4b9858c0bbbf2c2162f49d5/keymaps/darwin.cson#L91)

**Comment by andersennl** [comment]
Ahh, thanks a lot! But why do I get a "matching" green line in the keybinding resolver if the command doesn't exist?
