### ISSUE TITLE
Rename / Disable "Reopen Last Item"

### ISSUE THREAD

**Issue by aaronshekey** [atom/atom#6111]
Suggestions:

1. Disable "Reopen Last Item" until a document has been closed.
2. Rename "Reopen Last Item" to "Reopen Closed Document"

Justification:
In the absence of a "Open Recent...", the wording of the "Reopen Last Item" menu option is confusing. Nearly every time I use Atom as a new user, I launch Atom and go to File > Reopen Last Item. It doesn't do anything. See #5718.

As I understand it, it seems to actually be more similar to a browser's "Reopen Closed Tab", no? Chrome has "Reopen Closed Tab". Until this is made moot by #4241, we should rename that menu item to "Reopen Closed Document" or something to that effect.

Part of the confusion is that "Reopen Last Item" has the same placement as the standard "Open Recent..." menu option, but they don't operate the same way. We should disable it until Atom is in a state where the menu item actually does anything.

**Comment by Zireael07** [comment]
Agreed. I thought it worked like Open Recent, too.

**Comment by 50Wliu** [comment]
:+1:  I tried getting it to open my last folder at first :P.
