### ISSUE TITLE
75% of the Atom window is not used.  

### ISSUE THREAD

**Issue by R1V3R5** [atom/atom#6123]
This is how the window appears in whatever size window it is.  No way to close/hide/do anything with it.
![screen shot 2015-03-27 at 9 28 35 am](https://cloud.githubusercontent.com/assets/7141481/6868682/ffca8172-d463-11e4-8c13-731d0bccefba.png)

**Comment by mnquintana** [comment]
What version of Atom are you running? This looks like a very old version to me – please update to the latest version (0.188.0)

**Comment by abe33** [comment]
What is that gradient in the left bottom corner? Have you tried inspecting it or the empty space at the bottom using the devtools?

**Comment by postcasio** [comment]
It looks like [color-picker](https://atom.io/packages/color-picker), which did have display problems similar to this after an update a while back I think. Updating should fix it.

**Comment by batjko** [comment]
So yea, as per the [debugging instructions](https://atom.io/docs/v0.188.0/hacking-atom-debugging), let's start with updating the app and all packages, then start in safe mode (`atom --save`) and see what's left after that.

**Comment by mnquintana** [comment]
This was an issue with [color-picker](https://atom.io/packages/color-picker) - please update to the latest versions of both color-picker and Atom.
