### ISSUE TITLE
Manually set Syntax Highlighting

### ISSUE THREAD

**Issue by arivazhagan** [atom/atom#6124]
I am a Sublime user now i moved to Atom, How can i choose Syntax highlighting for a selected text? IN Sublime View ->Syntax ->HTML. Do we have something similar?

**Comment by Zireael07** [comment]
Look in the lower right corner, you should have Plain Text if nothing was detected or Lua/HTML/JS whatever your file is.

**Comment by tigrex22** [comment]
Or you just press ctrl+shift+L

**Comment by lee-dohm** [comment]
See the documentation: https://atom.io/docs/latest/using-atom-grammar

**Comment by arivazhagan** [comment]
Thanks alot people, You made my day!
