### ISSUE TITLE
Conflict ignored when changing file outside of Atom when it has unsaved changes in Atom.

### ISSUE THREAD

**Issue by bolinfest** [atom/atom#6128]
I have a clean local file `foo` open in Atom, and I modify the file outside Atom. Atom reloads the file, which is fine. But if I have unsaved changes in file `foo` in Atom, and `foo` gets modified externally, Atom does not tell me about external changes, even when I try to save the file.

**Comment by kevinsawicki** [comment]
@bolinfest just to confirm, was this something that previously behaved differently and has regressed? Or has this always been this way?

I just want to make sure nothing broke with the recent pathwatcher upgrade regarding this.

**Comment by thomasjo** [comment]
AFAIK it has always been like this. I just always assumed it was a known issue that would get fixed eventually.

**Comment by maxbrunsfeld** [comment]
Yeah, I believe that though `TextEditor` has an `onDidConflict` method, that method is not used anywhere in Atom core.
