### ISSUE TITLE
Folding toggle command

### ISSUE THREAD

**Issue by 6D65** [atom/atom#6129]
Hi,

Currently Atom has 2 different commands for folding/unfolding the current row: 
1. editor:fold-current-row 
2. editor:unfold-current-row

But it seems more logical to have just one row folding toggle command, and use to fold/unfold a block.

This is more like a feature request, it seems that both Atom and SublimeText are missing this, and Visual Studio gets it right. The fold all behaviour of Atom is much better than Sublime's though.

Thank you.

**Comment by monokrome** [comment]
+1

**Comment by thefotios** [comment]
+1

This would put this more inline with `vim` [functionality][1]. Personally, I almost always just use the toggle `z a` and the `vim` docs even recommend that as an easier approach.

[1]: http://vim.wikia.com/wiki/Folding#Opening_and_closing_folds

**Comment by monokrome** [comment]
I always have a keybind mapping `<space>` to the fold, so not being able to do this was a big deterrent.

**Comment by calebmeyer** [comment]
If you can't wait, you can put this into your init script:
```coffee
# toggle the folding state of the row under the cursor
atom.commands.add 'atom-text-editor', 'editor:toggle-current-row-folding': (event) ->
    editor = @getModel()
    bufferRow = editor.bufferPositionForScreenPosition(editor.getCursorScreenPosition()).row
    if editor.isFoldedAtBufferRow(bufferRow)
      editor.unfoldBufferRow(bufferRow)
    else
      editor.foldBufferRow(bufferRow)
```

You can map space to fold toggle (in normal mode) via:
```cson
'.editor.vim-mode.normal-mode':
  'space': 'editor:toggle-current-row-folding'
```

Note that I can't take credit for this, as I got it from Kai Schaper on this thread: https://discuss.atom.io/t/how-to-toggle-current-fold-in-editor-view/11094/4

**Comment by ChristopherChudzicki** [comment]
Folding toggle would be great!

**Comment by valkalon** [comment]
Same here, I would personnaly enjoy a fold toggle command : 
- it saves one keyboard shortcut
- From personal experience, toggling is easier from a cognitive point of view.
