### ISSUE TITLE
Multiple keys keybindings interfering with the built in ones

### ISSUE THREAD

**Issue by 6D65** [atom/atom#6130]
Hi,

It seems like when assigning a keybinding like **ctrl + m + o** triggers the **ctrl + o** keybinding.
Is this expected?

```cson
// Example config that won't work
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-m o': 'editor:fold-all'
```

Thanks

**Comment by lee-dohm** [comment]
I added the following to my `keymap.cson`:

```coffee
'atom-text-editor':
  'ctrl-m o': 'editor:fold-all'
```

And everything worked fine:

![multi-step-key](https://cloud.githubusercontent.com/assets/1038121/6875426/a8768246-d47b-11e4-9b0b-6e36662e2c92.gif)

Do you perhaps more than one entry matching `atom-workspace atom-text-editor:not([mini])`?

**Comment by 6D65** [comment]
Nope, 

Fresh Atom install, first 2 keymaps added. I've changed them following your example. Still the Open-File and Search Project commands are triggered. 

I'm wondering if it may be because of the vim extension installed, also it might also be just a windows issue.


```json
# Your keymap
#
# Atom keymaps work similarly to stylesheets. Just as stylesheets use selectors
# to apply styles to elements, Atom keymaps use selectors to associate
# keystrokes with events in specific contexts.
#
# You can create a new keybinding in this file by typing "key" and then hitting
# tab.
#
# Here's an example taken from Atom's built-in keymap:
#
# '.editor':
#   'enter': 'editor:newline'
#
# '.workspace':
#   'ctrl-P': 'core:move-up'
#   'ctrl-p': 'core:move-down'
#
'atom-text-editor':
  'ctrl-m o': 'editor:fold-all'

'atom-text-editor':
  'ctrl-m p': 'editor:unfold-all'
```

The screenshot of key resolver:
![image](https://cloud.githubusercontent.com/assets/1144767/6875968/f7423816-d4cb-11e4-9f7c-a62f5b6d6b5e.png)

**Comment by lee-dohm** [comment]
Ok, I see the issue ... thanks for posting your keymap file. If you change it to this, they should both work:

```coffee
'atom-text-editor':
  'ctrl-m o': 'editor:fold-all'
  'ctrl-m p': 'editor:unfold-all'
```

Here's why: CSON is an acronym for CoffeeScript Object Notation, much like JSON (JavaScript Object Notation). This means that if you declare a key twice, the second declaration *overwrites* the first. Your version of the keymap is equivalent to:

```coffee
'atom-text-editor':
  'ctrl-m p': 'editor:unfold-all'
```

**Comment by 6D65** [comment]
Silly me, everything works now.

Thank you @lee-dohm and sorry for the wasted time.

**Comment by lee-dohm** [comment]
Not a waste at all :grinning: I'm glad I could help!
