### ISSUE TITLE
Symantec Endpoint Protection reported Atom as trying to edit the hosts file

### ISSUE THREAD

**Issue by kfechter** [atom/atom#6133]
Windows 7
Atom Version 0.188.0

When I opened atom, My endpoint protection popped up a threat detection alert saying that atom was attempting to edit my hosts file. then stopped the app from running.

**Comment by lee-dohm** [comment]
That's interesting. Does it do this every time? Does it do it if you launch Atom via `atom --safe`?

**Comment by kfechter** [comment]
Since I encountered this at work, I removed it from the computer as soon as I got the message, since its a security concern. I will try and reproduce again.

**Comment by lee-dohm** [comment]
To my knowledge, nothing in the default installation of Atom edits your hosts file.

**Comment by batjko** [comment]
Can you confirm from which folder you're opening Atom? Is it C:\ or C:\Windows etc?

**Comment by kfechter** [comment]
the path was in C:\Users\<username>\AppData\Local

**Comment by kfechter** [comment]
I was running a few plugins. I will build an installation that mirrors the environment, since I can't do it on my work computer again.

**Comment by kfechter** [comment]
Could not reproduce it :/ I think something else may have been causing it.
