### ISSUE TITLE
"Search in Directory" not working when root directory name contains a period

### ISSUE THREAD

**Issue by damonkreft** [atom/atom#6134]
The `Search in Directory` command does not seem to work properly when there are multiple root folders (as below illustrates), but works as expected with a single root folder.

![out2](https://cloud.githubusercontent.com/assets/4972683/6877472/28c9901c-d4c9-11e4-8a38-43f743cbcf35.gif)

I'm on Ubuntu 14.10 and v0.188.0 of Atom.

**Comment by mathiasvr** [comment]
Does it work if you add a slash to the search path? making it `mands.portal-ui/src/`
For me this seems to be the only way to do recursive search, in folders other than root.

**Comment by damonkreft** [comment]
Adding the forward slash does work @mathiasvr

**Comment by bencooling** [comment]
Getting exact same behaviour as @damonkreft but forward slash not working for me.

**Comment by maxbrunsfeld** [comment]
I can't reproduce this bug. For me, recursive directory searches work, with or without a trailing `/`. @izuzak have you seen anything like this?

@bencooling What OS are you using?

@bencooling, @damonkreft Does this happen for all folders, or only certain folders?

**Comment by bencooling** [comment]
@maxbrunsfeld I'm using Atom: 0.198.0 on OSX: 10.10.3.

**Comment by izuzak** [comment]
Haven't seen this happen before -- jsut tried it in OSX 10.10.3 and Windows 8.1

@bencooling @damonkreft Would you be willing to provide _exact_ written steps to reproduce this, starting with `git clone` commands which close two Git repositories with which you are able to reproduce this? Getting us as close as possible to the same environment for reproducing this would be helpful. Thanks for your help!

**Comment by jsg2021** [comment]
I reproduce this every day. Very annoying.  If I remove the path from the third line it works, but across all my projects. If I do as @damonkreft says and add a trailing slash, it works as expected.

MacOS 10.10.3
Atom 0.200

 1. Open Atom, 
 2. Add more than one project/root to the tree.
 3. Context-Click any folder and select "Search in Directory"
 4. Notice the bottom search drawer opens with 3 rows (search, replace, path) with the third row populated with the Atom relative path to the folder you selected.
 5. Type something you know should hit in that path into the search field and hit enter.
 6. Notice, empty results.

**Comment by maxbrunsfeld** [comment]
I just fixed a find-and-replace bug (https://github.com/atom/find-and-replace/pull/392) that relates to the `Search in Directory` context menu item. It doesn't really seem related to this; it has nothing to do with the presence of a `/` in the directory name, and it would actually cause an exception to be thrown in some cases, but I thought I'd mention it here because right now I don't have any ideas about what could be happening in your case.

@jsg2021 Thanks for sharing these steps, but I still can't reproduce this bug. We're thinking the bug may have to do with some property of the directories that you're searching. Could you provide steps that describe *exactly* what directories you are searching (i.e. either clone some public projects using `git clone` or share your directory structure using the [`tree`](http://mama.indstate.edu/users/ice/tree/) command).

**Comment by maxbrunsfeld** [comment]
Also, if anyone experiencing the bug is willing to build atom from source, the fix that I mentioned above is on the master branch of Atom. It'd be nice to find out if it fixes the issue for you (though I'm not too confident that it will, to be honest).

**Comment by jsg2021** [comment]
Its definitely my project... just tried it with other public projects and random folders and it works as expected. :/ My directory tree is kind of large (at least in line length) is there a way I can attach it? (without inlining it)

**Comment by maxbrunsfeld** [comment]
Maybe you could paste the output of `tree` in your directory into a gist, and link to that here?

**Comment by maxbrunsfeld** [comment]
@jsg2021 Also, is there anything *exotic* in your project, like symlink cycles, or files and folders with the same case-insensitive name?

**Comment by jsg2021** [comment]
@maxbrunsfeld I don't think so. A fresh clone of my project reproduces this issue when I add any other root folder to atom.  I think it's the root folder name. Mine has periods, and from the look of the gif from @damonkreft so does his project.

I renamed my project folder from "nti.web.mobile" to just "mobile" and my searches worked w/o fail.

**Comment by Zireael07** [comment]
@jsg2021: Sounds like an issue I had with 0.193.0. I'd have sworn I'd reported it, but I can't find it on GitHub. I had to use the higher level folder which had no periods in it as root folder - then it worked normally.
So I used Incursion instead of Incursion/Incursion-0.9.8 as root and it solved the problem.

**Comment by maxbrunsfeld** [comment]
> I think it's the root folder name. Mine has periods, and from the look of the gif from @damonkreft so does his project.

@jsg2021 Thanks so much for investigating. We should be able to fix this now.

**Comment by splendido** [comment]
Same problem for me, on Ubuntu 14.04
the path you get from the context menu has no trailing '/' and the result tab says '0 path searched' and no results...
...but if I add the trailing '/', even without manually opening any files, all expected results pop up as expected.

**Comment by Zireael07** [comment]
@splendido: Does your folder have periods in its name?

**Comment by splendido** [comment]
@Zireael07: no!
it happens regularly on every path :(

**Comment by Zireael07** [comment]
Create another issue then, this is for directories with periods in their names.

**Comment by timmickey** [comment]
I'm on Mac OS X 10.10.3 using Atom 1.0.2. Any directory that has a "." in its name will not be searchable. Adding the trailing slash to the end of the directory in search fixes this for me!! (Thank you @splendido - I've been switching over to Sublime Text to do searches.) My project directory does not contain a ".", but a sub directory does. 

To reproduce
- Open project without a "." in name. 
- Create directory named "i.o"
- add file `index.html` with contents `<html></html>`
- right click "i.o" directory and choose "Search in directory"
- search for 'html'
- no results found.
