### ISSUE TITLE
utf markdown html mangled

### ISSUE THREAD

**Issue by m4b** [atom/atom#6136]
It seems like utf-8 symbols are mangled when saving a markdown file as html (on OSX Yosemite).

For example:

>#Example
>
>The More You Know™
>
>ಠ_ಠ

is rendered as the following html:

>Example
>
>The More You Knowâ„¢
>
>à² _à² 

It shows up fine using the built-in Markdown Preview.

**Comment by 50Wliu** [comment]
This issue was moved to atom/markdown-preview#226
