### ISSUE TITLE
One Dark syntax theme colors all Java code yellow

### ISSUE THREAD

**Issue by mc10** [atom/atom#6141]
Here's a screenshot of the issue:
![Screenshot](https://i.imgur.com/sYIOndC.png)
I've seen the same issue in Sublime themes as well but I never quite figured out the problem.

**Comment by batjko** [comment]
I'm not sure it's a bug. Just a bad design choice. 
I noticed that as well with Java files and the theme just doesn't work very well with those files.

If you wish to change this, open an issue on the theme's repository, or create a PR with something more pleasing, maybe?

**Comment by simurai** [comment]
I'll move this over to the One dark syntax theme: https://github.com/atom/one-dark-syntax/issues/21
