### ISSUE TITLE
Find in Project result count out of sync with hits displayed

### ISSUE THREAD

**Issue by Cangit** [atom/atom#6147]
How to reproduce:

 - Search for something with `Find in Project` wait until search is done.
 - Go into one file that has a hit, remove the line that had the hit.
 - Result count should now correctly go -1, while the entry should be removed from the search page.
 - Re add the line, in the same file or another file.
 - Result count should now correctly go +1 back to the original count (*nice!*), but the entry is *not* added to the search page (*sad!*).

I think the best options here would be
 - (**sub optimal**) To not make the result count go +1.
 - (**optimal**) Keep the result count go +1 and add the new result to the search page without having to do a new search. 

Added screenshot showing 3 results in count, but only showing two.
![screen shot 2015-03-28 at 18 23 58](https://cloud.githubusercontent.com/assets/1426157/6882023/c2daed5a-d577-11e4-82de-3b0c9daf0c4e.png)

**Comment by 50Wliu** [comment]
This issue was moved to atom/find-and-replace#372
