### ISSUE TITLE
Failed to load the atom-html-preview package

### ISSUE THREAD

**Issue by 119Kaiser** [atom/atom#6149]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Failed to load the atom-html-preview package

```
At unexpected .

[stdin]:1:1: error: unexpected .
.workspace:
^
```

### Commands

```
     -0:01.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.1.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
This sounds like a problem in the atom-html-preview package. Can you open an issue there if you can reproduce this in the latest version of Atom and that package? 

https://github.com/webBoxio/atom-html-preview/issues
