### ISSUE TITLE
Failed to load the autocomplete-jedi package

### ISSUE THREAD

**Issue by haznav** [atom/atom#6151]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.16.0-33-generic
**Thrown From**: Atom Core

### Stack Trace

Failed to load the autocomplete-jedi package

```
At unexpected newline

[stdin]:4:27: error: unexpected newline
'.atom-text-editor[mini]':
                          ^
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "autocomplete-plus-jedi"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 18,
    "showIndentGuide": true,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.0
linter-flake8, v1.3.0

# Dev
No dev packages
```

**Comment by benogle** [comment]
Autocomplete-jedi might be broken for the current environment, and it reimplements things that autocomplete-plus implements. You might want to try autocomplete-plus and https://atom.io/packages/autocomplete-plus-jedi

**Comment by haznav** [comment]
Thanks
