### ISSUE TITLE
Uncaught Error: ENOENT

### ISSUE THREAD

**Issue by Hurtak** [atom/atom#6153]
[Enter steps to reproduce below:]

1. Open folder with atom

**Atom Version**: 0.188.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'C:\Petr\Projects\#Sandbox\compiled.js'

```
At events.js:94

Error: ENOENT, open 'C:\Petr\Projects\#Sandbox\compiled.js'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoflow",
      "metrics",
      "styleguide",
      "remember-session",
      "bookmarks",
      "exception-reporting"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "destroyEmptyPanes": false,
    "followSymlinks": true
  },
  "editor": {
    "scrollSensitivity": 80,
    "scrollPastEnd": true,
    "invisibles": {},
    "softWrap": true,
    "fontSize": 17,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autocomplete-css, v0.6.0
block-travel, v1.0.2
color-picker, v1.5.0
docblockr, v0.6.3
emmet, v2.3.4
last-cursor-position, v0.7.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-htmlhint, v0.0.9
linter-jscs, v1.9.0
linter-jshint, v0.1.0
linter-jsonlint, v0.1.2
monokai, v0.13.0
open-last-project, v0.3.5
pretty-json, v0.3.2

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@Hurtak Does this happen for every folder or only some folders? Does it happen in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by Hurtak** [comment]
I think this might be related to open-last-project package since it tried to reopen 'C:\Petr\Projects\#Sandbox\compiled.js' file which was deleted. Also this happens on start up. Outside of this situation where it is trying to open deleted file, error doesn't show up.

**Comment by Hurtak** [comment]
Closing in favor of #6210.
