### ISSUE TITLE
Stragne editor scrolling when selecting rows

### ISSUE THREAD

**Issue by m1ga** [atom/atom#6154]
![atom2](https://cloud.githubusercontent.com/assets/4334997/6886281/66780168-d637-11e4-83f6-efe2b13f5d44.gif)

* first row selected
* scrolling down
* clicking on row 34
* window is scrolling up again

Atom 0.189.0-296a986
Linux / Fedora

**Comment by 50Wliu** [comment]
I think this was fixed in ca39bde4cdf1a50e97c01dfef3b6036fb6aa0395 :wink:.

**Comment by m1ga** [comment]
have to do a pull before I file bugs :) Thanks was two day behind with pulls
