### ISSUE TITLE
Support `block` as a decoration type for TextEditor.

### ISSUE THREAD

**Issue by bolinfest** [atom/atom#6156]
There should be a `block` decoration type that can span the entire width of the editor, appearing below a line and forcing subsequent lines to appear below it. This could be used to display UI for things like inline comments, as you can in a GitHub pull request.

**Comment by thomasjo** [comment]
I really like this idea!

**Comment by bolinfest** [comment]
I believe that @nathansobo is on board, but it's not clear that anyone on the Atom core team has the bandwidth to do this before the 1.0 release, so a solution will likely have to come from the community.

**Comment by mark-hahn** [comment]
>  forcing subsequent lines to appear below it.

I'm a bit dense here.  To me "subsequent line" always appear after
something as that is what "subsequent" means.  Do you mean that any new
lines entered in the editor will be added below that line?  What happens if
you type above that line?

**Comment by lee-dohm** [comment]
There is now an `inline` decoration type that works in the way described.

**Comment by nathansobo** [comment]
@lee-dohm are you referring to `text` decorations? They're not yet merged to master but coming in a couple weeks.

**Comment by lee-dohm** [comment]
Sorry, I mean these: http://blog.atom.io/2016/02/03/introducing-block-decorations.html

**Comment by nathansobo** [comment]
Ahhh, `{type: 'block'}`
