### ISSUE TITLE
Move from CoffeeScript to ES6+

### ISSUE THREAD

**Issue by chicoxyzzy** [atom/atom#6157]
There are some disadvantages of using CoffeeScript when writing stuff (better described [here](https://discuss.bevry.me/t/move-from-coffeescript-to-es6/30)). Till Atom cares of performance and contributions (JS is definitely more popular and widely known language than CoffeeScript) switch to ES6+ looks fair enough and future-proof. Also Atom already uses io.js which supports some ES6 features too. So using let/const, typed arrays and other features should improve performance

**Comment by paulcbetts** [comment]
To be honest, none of those things were particularly compelling to us, but what _was_ compelling, is that the JSHint linter in ES6 mode is *much* better than Coffeelint. ES6 linter will actually catch interesting mistakes like saving over variables (`path` anyone?).

**Comment by mark-hahn** [comment]
> Till Atom cares of performance and contributions

So you are saying Atom doesn't care about performance or contributions?
That is silly.


>  switch to ES6+ looks fair enough and future-proof.

Please please don't.  The noise in JS is a serious readability issue that
JS will never solve by itself.  Performance is rarely an issue and when it
is you can always drop down into ES6 using the back-ticks.

**Comment by chicoxyzzy** [comment]
> So you are saying Atom doesn't care about performance or contributions?

Sorry English is not my native language. I mean that Atom cares about performance because it is critical for such application.

**Comment by mnquintana** [comment]
I'd recommend reading this thread: https://discuss.atom.io/t/why-coffeescript/131

This has been covered quite a lot before.

**Comment by chicoxyzzy** [comment]
I want to believe that people who vote for cs understand that it will dye because of two things: it is not "just javascript" anymore (after ES5.1) and cs is not standard nor the language of web. it can't compete with js. one day you'll have to rewrite cs code to js or your projects will not be able to get benefits js engines will bring to web.

**Comment by mark-hahn** [comment]
I am dying to reply to this because I disagree with almost everything you
said but we need to move to https://discuss.atom.io/t/why-coffeescript/131.

**Comment by chicoxyzzy** [comment]
> we need to move to https://discuss.atom.io/t/why-coffeescript/131.
this topic is closed

**Comment by mark-hahn** [comment]
That was closed because ES6 is now supported in Atom.  So there is no need for us to hash out our religious beliefs here.  You could take it to the coffeescript google group if you wish.  

Please close this thread before hell breaks loose again.

**Comment by paulcbetts** [comment]
Let's nip this one in the bud, this isn't going anywhere useful
