### ISSUE TITLE
sometimes  a chinese-char become '���'  in atom

### ISSUE THREAD

**Issue by netmou** [atom/atom#6160]
sometimes a chinese-char become '���',(as we all know that in charset utf-8, a chinese-char need 3 byte )

**Comment by izuzak** [comment]
@netmou Can you please provide a bit more information? Which version of Atom are you using and which OS? Can you provide examples of situations when this happens? Does it happen all by itself why you're watching the screen or while you're typing or in some other situations?

**Comment by netmou** [comment]
It happens randomly.
atom v0.188 win7x64

**Comment by izuzak** [comment]
@netmou Which font are you using and does using a different font help?

**Comment by 50Wliu** [comment]
Should be fixed since Atom 1.0.12.

**Comment by netmou** [comment]
I have not encountered this problem for a long time
