### ISSUE TITLE
Atom doesn't want to update

### ISSUE THREAD

**Issue by pistou** [atom/atom#6162]
I'm on windows 8.1, using Atom 0.186.0 currently.
I'm trying to update but it doesn't want to.

When Atom starts, it tries to update, then nothing. And when I click `Help > Check for update` it says me that 0.186.0 is the last version.

I tried to empty the `package`folder which was containing only one file (`atom-0.188.0-full.nupkg`) in case it was corrupted or something, but nothing changed.

Here is the `SquirrelUpdate.log` file content: 
>Program: Starting Squirrel Updater: --download https://atom.io/api/updates
Program: Fetching update information, downloading from https://atom.io/api/updates
CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.FileNotFoundException: Could not find file 'C:\Users\Pierre\AppData\Local\atom\packages\RELEASES'.
File name: 'C:\Users\Pierre\AppData\Local\atom\packages\RELEASES'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__28.MoveNext()
CheckForUpdateImpl: Downloading RELEASES file from https://atom.io/api/updates
FileDownloader: Downloading url: https://atom.io/api/updates/RELEASES
CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
FileDownloader: Downloading file: https://atom.io/api/updates/atom-0.188.0-full.nupkg
UpdateInfo: Couldn't get release notes for:atom-0.188.0-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\Pierre\AppData\Local\atom\..\atom\packages\atom-0.188.0-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__2(ReleaseEntry x)

**Comment by 50Wliu** [comment]
@paulcbetts
`C:\Users\Pierre\AppData\Local\atom..\atom\packages\atom-0.188.0-full.nupkg`
That `atom..` seems a bit interesting.

**Comment by TouPye** [comment]
The only solution I found was to unistall an reinstall Atom. 
It seems to work well so far !

**Comment by fengmk2** [comment]
Is any way to change update url https://atom.io/api/updates/atom-0.198.0-full.nupkg to a mirrors url like http://cnpmjs.org/mirrors/atom/0.198.0/atom-0.198.0-full.nupkg?

**Comment by paulcbetts** [comment]
@fengmk2 afaik there should be an environment variable that you can set. That being said, using Squirrel with a non-HTTPS URL is a very bad idea from a security standpoint (I know that in China it's not so popular to use HTTPS, but still)

**Comment by batjko** [comment]
@pistou Is this still an issue or can it be closed?

**Comment by pistou** [comment]
@batjko As I said on April 8th, I have re-installed Atom and it works now. I have no more issue, but I don't know if the source of the issue has been solved..
I guess it can be closed since no one had the same issue.

**Comment by batjko** [comment]
Ok thanks.
What I meant was whether you still get update problems, even though you're on a newer version now.
Glad you aren't seeing this anymore.
