### ISSUE TITLE
ghc-modi

### ISSUE THREAD

**Issue by sneiman** [atom/atom#6169]
getting this error msg when I open a haskell src file:

'ghc-modi' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

ghc-modi is installed and is in the current path.

**Comment by izuzak** [comment]
As mentioned in the error message:

> please open an issue on the package spawning the process.

Open an issue here: https://github.com/lierdakil/haskell-ghc-mod

**Comment by sneiman** [comment]
oops
