### ISSUE TITLE
Failed to load the html-helper package

### ISSUE THREAD

**Issue by SketchNI** [atom/atom#6171]
1. Booted Atom
2. Received error.

**Atom Version**: 0.188.0
**System**: Microsoft Windows 7 Home Premium 
**Thrown From**: Atom Core

### Stack Trace

Failed to load the html-helper package

```
At missing '

[stdin]:11:44: error: missing '
  'ctrl-shift-\': 'html-helper:closeElement'
                                           ^
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "preferredLineLength": 200,
    "tabLength": 4,
    "showIndentGuide": true,
    "normalizeIndentOnPaste": false,
    "invisibles": {},
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.5.0
html-helper, v0.2.3

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Can you post your `snippets.cson`? It looks to me like you set an invalid custom keybinding – in CSON, backslashes (`\`) have to be escaped because they are the escape character, so the keybinding should look like:

```cson
'ctrl-shift-\\': 'html-helper:closeElement'
```

**Comment by SketchNI** [comment]
That was a package I had added (I think). I haven't used Atom in quite a while.

However, I found the keymap and added the second backslash and restarted Atom. The error has disappeared, so thank you for your help!
