### ISSUE TITLE
Atom does not open file when a file is clicked in the side bar

### ISSUE THREAD

**Issue by ammark** [atom/atom#6172]
I am using atom version 0.188 on OS X. I have loaded all my project files in atom editor. All the files tend to appear in the sidebar just fine but when i double click on a file, the file opens in the same tab, and the files tab name is not updated, although the atom bar on the top does update the name. 

So i can open multiple files in atom editor. Is this a bug because i really want to use atom but this is really irritating.

Thanks

**Comment by ammark** [comment]
![screen shot 2015-03-30 at 3 35 13 pm](https://cloud.githubusercontent.com/assets/687976/6904962/70885944-d6f2-11e4-873b-1ed380c6d719.png)
![screen shot 2015-03-30 at 3 34 58 pm](https://cloud.githubusercontent.com/assets/687976/6904966/73df7c9e-d6f2-11e4-9d1c-b086f5a88abd.png)


Here is a screenshot.

**Comment by mnquintana** [comment]
Does this happen if you run Atom in safe mode (`atom --safe`)? Can you post the list of your installed packages? (`apm list --installed`)

**Comment by ammark** [comment]
i tried running in the safe mode, and it works perfectly fine. Thanks

This packages commands gives me an error in the terminal
-bash: atm: command not found

I have a feeling that i am running it properly in the commands line. Any help?

**Comment by mnquintana** [comment]
Looks you had a typo there – try `apm`

**Comment by ammark** [comment]
Aha! got it sorry about that. These are the list of packages:

── Atom-Syntax-highlighting-for-Sass@0.5.0
├── Zen@0.11.2
├── angularjs@0.2.0
├── atom-alignment@0.12.0
├── atom-beautify@0.23.1
├── atom-bootstrap3@1.2.0
├── atom-spotify@1.2.0
├── atom-terminal@0.7.0
├── atom-typescript@1.12.0
├── autocomplete-paths@1.0.2
├── autocomplete-plus@2.7.0
├── color-picker@1.5.0
├── emmet@2.3.4
├── file-icons@1.5.2
├── ide-flow@0.2.0
├── jekyll@0.4.3
├── jshint@1.3.0
├── language-jsx@0.1.4
├── language-typescript@0.15.0
├── linter@0.12.0
├── markdown-format@2.5.0
├── markdown-writer@1.1.1
├── minimap@4.6.0
├── monokai@0.13.0
├── open-in-browser@0.4.3
├── project-manager@1.15.5
├── react@0.10.1
├── seti-syntax@0.3.3
├── seti-ui@0.6.3
├── shiny-ui@0.33.0
├── unity-ui@2.0.5
├── vim-mode@0.41.0
└── yosemite-unity-ui@0.3.13

**Comment by mnquintana** [comment]
Can you try disabling project-manager and see if you still experience this? It's definitely one of these packages that's causing the issue, and that seems like the most likely culprit right now.

**Comment by ammark** [comment]
okay. Let me try. By the way, atom was working perfectly fine with project manager but i installed few react/flow plugins recently so i guess they might be malfunctioning.

**Comment by ammark** [comment]
Uninstalled flow language package, and couple of other packages like angular and now its working fine. Thanks. Cheers

**Comment by mnquintana** [comment]
Good to hear! Might be worth opening issues on the repos for those packages instead now (and closing this one). (You should be able to find them quickly either in Settings or by running `apm home <package name>`

**Comment by ammark** [comment]
Okay great! i have opened an issue in the flow package. Thanks
