### ISSUE TITLE
Setting Atom as my default editor in Cyberduck

### ISSUE THREAD

**Issue by TafariD** [atom/atom#6177]
So when Atom installed itself, I have no idea where it placed its files... 
I've been trying to set Atom as my default editor in Cyberduck, the issue is, I can't find the "Atom" file in my computer to select in the file window.

I tried selecting the Atom shortcut that was installed on my desktop, but Cyberduck claims it points to a file called "update" and then refuses to work. I was able to set Cyberduck to work with Sublime, but I can't figure out how to set Atom as my default editor...

Does anyone know how to fix this?

![where](https://cloud.githubusercontent.com/assets/10626101/6910174/7ab7866c-d71d-11e4-9735-bdd18a6321a7.png)

**Comment by nramin** [comment]
I'm having the same problem. Anyone know?

**Comment by batjko** [comment]
There is a `.cmd` file for atom (next to one for apm) that your link should use as a target in:
`C:\Users\[username]\AppData\Local\atom\bin`

![image](https://cloud.githubusercontent.com/assets/7287076/6996306/43301df8-db78-11e4-87ed-be2b04e787cc.png)

**Comment by TafariD** [comment]
It doesn't work. The edit tab in Cyber Duck is still greyed out,  and I can't open files with Atom.

On Sun, Apr 05, 2015 at 4:45 AM, batjko <notifications@github.com<mailto:notifications@github.com>> wrote:


There is a .cmd file for atom (next to one for apm) that your link should use as a target in:
C:\Users\[username]\AppData\Local\atom\bin

[image]<https://cloud.githubusercontent.com/assets/7287076/6996306/43301df8-db78-11e4-87ed-be2b04e787cc.png>

**Comment by batjko** [comment]
I don't know at all what your CyberDuck's requirements are for declaring editors. 

Maybe it needs to be the actual executable, which theoretically you could get by going directly into the latest version's `bin` folder. But then you'd have to manually change it every time an update comes out.

**Comment by damieng** [comment]
Atom is now registered as an application for association with files.

Cyberduck however still has Edit With grayed out and I wasn't even able to get that working with Notepad. I suspect there is either an issue their end or they are expecting the application to be able to open url's.  Atom worked fine from the open command on the transfer window.

I think our part of the work here is done and you might want to follow up with Cyberduck - I found issues on their tracker relating to Edit With not working but they were all OS X related and subsequently fixed.

If you can get Cyberduck Edit With working with another app please post back so we can find out what the difference is.

**Comment by pentracode** [comment]
You can make atom a default editor right in atom. goto settings and click editor. Read through and check all the places that integrates atom to open with options
