### ISSUE TITLE
Predictive Text

### ISSUE THREAD

**Issue by TafariD** [atom/atom#6178]
I'm not sure if this is even a feature, but I wanted to check and see if Atom can do predictive text.

For example, in Sublime, you it guesses what your going to type and allows you to fill in the rest of a long word or phrase by pressing tab. Also (this could be an eclipse feature only, I forget) when I enter a variable name and then hit . or ->  (I'm coding in C) it sometimes knows what types of that variable are and suggests them. Can Atom do this?

I can provide pictures if needed.

**Comment by thedaniel** [comment]
@TafariD currently you can trigger this (autocomplete) by pressing Ctrl+Space. Soon we'll be moving to a new autocomplete system that you can set up to show completions automatically as well, based on the package [autocomplete-plus](https://atom.io/packages/autocomplete-plus) - you can install this package today if you want that behavior.
