### ISSUE TITLE
Couldn't open tree view

### ISSUE THREAD

**Issue by cyang05** [atom/atom#6179]
Both the shortcut and the menu couldn't open the tree view.
Ubuntu 14.04.2, atom 0.188.0 3/24/2015, 6:05:58 PM

**Comment by mark-hahn** [comment]
That usually happens when you are not in a folder.  How did you open Atom?
You either have to use the file menu to open a folder or you need to start
atom in a command line.

**Comment by cyang05** [comment]
I opened the atom from launcher. I will check it again after I get back home.

**Comment by mark-hahn** [comment]
> I opened the atom from launcher.

That is the expected behavior.  You have to open a root folder.

**Comment by izuzak** [comment]
Yep, you can only toggle the tree view if it has a project/folder for context. See https://github.com/atom/tree-view/issues/68 which is an issue requesting that the tree view can always be shown.

**Comment by mnquintana** [comment]
@izuzak I wonder if it would be worth showing a notification if you try opening the tree view with no root folder?

**Comment by izuzak** [comment]
@mnquintana Maybe. I think we should mention this in atom/tree-view#68, which is used to track this problem.

**Comment by sxss** [comment]
I use Ubuntu 14.04. and Tree View works perfect. Only the shortcut STRG+Backslash doesn't work at all (launcher/open folder).
