### ISSUE TITLE
Highlighting YAML blocks in Pandoc Markdown files

### ISSUE THREAD

**Issue by juh2** [atom/atom#6182]
Hi,

pandoc parses a YAML block in markdown files to set metadata and template variables. Highlighting in Github Markdown does not work correctly, when I use a YAML block with a multiline entry. The attached screenshots show the behaviour.

In One Light all the rest of the text gets green. I am using Atom 0.188.0

![correct-highlighting](https://cloud.githubusercontent.com/assets/1416069/6913899/cf4413c2-d785-11e4-8695-e2dbdab03d5d.png)
![wrong-hightlighting](https://cloud.githubusercontent.com/assets/1416069/6913934/0a699a80-d786-11e4-8b54-4d6bb7201960.png)

**Comment by izuzak** [comment]
This issue was moved to atom/language-gfm#83
