### ISSUE TITLE
Issues when editing .reg files

### ISSUE THREAD

**Issue by JPTigr** [atom/atom#6185]
When editing a .reg file, you have to press the **del** key twice to delete a key. This is the same with **backspace**.

Also, when you highlight text, the amount highlighted is half the position of the cursor.

For example, trying to highlight *I am using Atom to edit text*, would only highlight *I am using At*.

Note that typed text after opening the file and before saving isn't affected by this issue.

**Comment by mnquintana** [comment]
Do you only experience this with .reg files? Can you post a list of your installed packages (`apm list --installed`)?

**Comment by JPTigr** [comment]
I have only seen this with .reg files. I also have no additional packages:
![atom packages](https://cloud.githubusercontent.com/assets/8000673/7047048/f8e40eda-de01-11e4-8da7-4485250fe849.png)

**Comment by izuzak** [comment]
@JPTigr I'm having trouble reproducing this. Could you share a link to one such .reg file so that we can try and reproduce? Also, which version of Atom are you using and can you share a GIF which clearly demonstrates the problem? Thanks.

**Comment by AluisioASG** [comment]
Could it be due to encoding?  .reg files use UTF-16 IIRC.

**Comment by JPTigr** [comment]
That fixed it Aluisio! Thanks :). Atom seems to not auto select the correct character set when opening a reg file. I'll see if there is a way to automatically set a .reg file with the UTF-16 LE encoding.

Thanks again everyone!

**Comment by JPTigr** [comment]
The editor-settings package seems to do what I need: https://atom.io/packages/editor-settings.

Issue closed.
