### ISSUE TITLE
Help menu doesn't work if no browser is installed

### ISSUE THREAD

**Issue by marklakata** [atom/atom#6187]
None of the Help menu items (except for Release Notes) works if the user does not have a web browser installed. The default on CentOS 7 is not to have a browser. It wouldn't be so bad if at least an error message popped up informing that the user needs a browser. As it is right now, there is no error message, no help, no nothing. It would be nicer if the help was not 100% dependent on an external browser.

**Comment by jazzpi** [comment]
:+1: Since `atom-shell` is based off of Chromium, can't the help pages simply be opened in Atom itself without too much work?

**Comment by mark-hahn** [comment]
Install the `web-browser` package.

**Comment by mark-hahn** [comment]
Install the `web-browser` package.

**Comment by jazzpi** [comment]
*/shameless plug* :wink: 
But even with `web-browser` installed, if you click on any of the items in the Help menu, they get opened in the default browser.

**Comment by mark-hahn** [comment]
*> /shameless plug* [image: :wink:]

So I have to take the trouble to type that every time I mention one of my
packages?  Bummer

> But even with web-browser installed, if you click on any of the items in
the Help menu, they get opened in the default browser.

That is effectively a bug.   I catch all `http*` urls in the workspace
open.  Help menu should be calling that.  I'll put an issue in.
