### ISSUE TITLE
Multiple cursors shuffle order on paste when selecting characters on more than 7 lines

### ISSUE THREAD

**Issue by Bitjuggler** [atom/atom#6190]
![atom-mult-cursor-bug](https://cloud.githubusercontent.com/assets/545359/6927209/31fb9628-d7ec-11e4-9f4a-1665f630864f.gif)
Hi! 
I noticed a bug when selecting 7 or more lines with multiple cursors. In the gif above, I press ctrl-alt-down 7 times, then once shift-right to select the numbers, then ctrl-c to copy, then esc to go back to 1 cursor. When I press ctrl-v on an empty line, the just copied numbers are shuffled.

**Comment by 50Wliu** [comment]
What Atom version is this?

**Comment by Bitjuggler** [comment]
Its Atom 0.188.0 on Windows 7.
