### ISSUE TITLE
Stop polling the DOM when the editor does not have focus

### ISSUE THREAD

**Issue by benogle** [atom/atom#6195]
it continues to poll even when the editor window is not focused. This contributes to a constant 1 - 3% CPU on my machine.

**Comment by yaroshevych** [comment]
Not sure if it's related to the DOM, but Atom uses CPU even when app is hidden:

![screen shot 2015-04-02 at 13 20 30](https://cloud.githubusercontent.com/assets/564246/6962251/7b18bffc-d93b-11e4-8985-a31904f710a9.png)

![screen shot 2015-04-02 at 13 22 42](https://cloud.githubusercontent.com/assets/564246/6962255/898bc912-d93b-11e4-85cc-bafd0e64219d.png)

Atom Version 0.188.0 (0.188.0), OSX 10.10.2.

**Comment by detj** [comment]
:+1:

**Comment by benogle** [comment]
This is fixed I think. cc @nathansobo

**Comment by nathansobo** [comment]
👍🏻
