### ISSUE TITLE
Rename of directory does not reopen saved file in new directory

### ISSUE THREAD

**Issue by hkskoglund** [atom/atom#6198]
I've noticed that when renaming a directory and having a saved file open in a tab, does not update the file reference, it still points to the old directory? 

Steps to reproduce:

```
mkdir d1
cd d1
touch f1 f2 f3
(open f1 from tree-view)
cd ..
mv d1 d2
```

Result: f1 points to d1

I am on; atom 0.188.0, linux fedora 21

**Comment by iclanzan** [comment]
I’ve been bitten by this so many times. It is still happening in Atom 0.208. I’m on OS X.

**Comment by balexand** [comment]
This sounds like a duplicate of https://github.com/atom/autosave/issues/9. @hkskoglund @iclanzan Do you have the `autosave` module enabled? If so, please try disabling it and see if you can still reproduce the bug.

**Comment by iclanzan** [comment]
The `autosave` module is disabled. The bug can be easily reproduced using the steps provided by the op.
