### ISSUE TITLE
Uncaught JS-YAML: missed comma between flow collection entries at line 4, column 12:      "version": "1.0.12",               ^

### ISSUE THREAD

**Issue by ruffle1986** [atom/atom#6204]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught JS-YAML: missed comma between flow collection entries at line 4, column 12:
      "version": "1.0.12",
               ^

```
At /Users/tamasfodor/Work/wlp/enjora-securion-forms/node_modules/eslint/lib/config.js:60

undefined
```

### Commands

```
     -0:22.6 find-and-replace:show (atom-text-editor.editor)
     -0:20.9 core:confirm (atom-text-editor.editor.mini)
     -0:19.3 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:19.3 core:cancel (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "fontSize": 14,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.1.0
linter, v0.12.0
linter-eslint, v0.5.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
My guess is that you were using a linter package (perhaps https://github.com/AtomLinter/linter-js-yaml ?) and it threw an error. Suggestion: open an issue on that package's issue tracker. If you believe this is an error in Atom -- please provide steps to reproduce this and more details.
