### ISSUE TITLE
Modifying files outside of Atom creates ENOENT errors

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#6210]
Some repro steps that I gathered from the existing issues:
1. Have a file open in branch `something` that doesn't exist in branch `atom`
2. `git checkout atom`
3. ENOENT :boom: 
OR
1. Have a file open in Atom that will be affected by `git rebase`
2. `git rebase`
3. ENOENT :-1:
OR
Just simply rename a file outside of Atom that's currently open inside of Atom.

**Comment by benogle** [comment]
Are you able to reproduce these?

**Comment by 50Wliu** [comment]
No on latest master.
My steps:
`mkdir gittest`
`git init`
`nano test` (input `test` into it, then save and close)
`git add test`
`git commit -m "Initial commit"`
Open `test` up in Atom
`git checkout -b test`
`rm test`
`git add test`
`git commit -m "Remove test"`
`git checkout master`
Nothing happened, though I did notice that the close icon doesn't change into the "unsaved changes" icon until you make a change within the file.

**Comment by 50Wliu** [comment]
Just updated the title and description to better describe what's happening.
I still can't reproduce this though even with the new steps provided in #6361.

**Comment by iclanzan** [comment]
Man, this issue is annoying me. Whenever I want to switch branches, I first have to close all open files in atom to work around it.

**Comment by iclanzan** [comment]
I tried to build a reduced test case like the one you described above, but can’t reproduce the bug, yet it is happening in all my projects.

**Comment by benogle** [comment]
:( What system? I still have never seen this

**Comment by iclanzan** [comment]
I’m on OS X Yosemite (10.10.3).

**Comment by 50Wliu** [comment]
Repro steps from @halhenke (haven't tested these):
1 Open a new tab in a window associated with a saved project
2 Save the contents as a new file
3 Leave the tab open & close the window/project (you can leave Atom itself running)
4 Delete the file (its importnant that you close the window/project first - otherwise Atom keeps track of the files relocation to the Trash).
5 Reopen the project. You should have errors about the file being missing.

**Comment by iclanzan** [comment]
@50Wliu I have tried the above steps and they indeed trigger the error.

**Comment by mattcollier** [comment]
I'm needing to 'git rebase' regularly in order to squash commits.  Having files open in Atom during that process results in Atom and/or the git-diff package getting very confused resulting in an inaccurate representation of changes.

**Comment by 50Wliu** [comment]
This seems to have been fixed as there haven't been any more reports.

If anyone is still experiencing this issue please comment here.

**Comment by eboujlal** [comment]
Same issue
