### ISSUE TITLE
ctrl-shift-left and ctrl-shift-right do not work on linux

### ISSUE THREAD

**Issue by Siecje** [atom/atom#6211]
On a fresh install of Ubuntu 14.04 64-bit I installed the .deb from http://atom.io and ctrl-shift-left and ctrl-shift-right do not select 'words'.

I tried adding the to copy the body lines from the Windows keymap with ctrl-shift-left and ctrl-shift-right.

**Comment by 50Wliu** [comment]
I can't reproduce on Ubuntu 14.10.  Can you please enable the keybinding resolver (<kbd>Ctrl</kbd>+<kbd>.</kbd>) and try doing the command again and reporting what the keybinding resolver shows?  Thanks.

**Comment by Siecje** [comment]
The issue was because right control was being consumed by VirtualBox.
