### ISSUE TITLE
Don't show deprecation cop warnings in Atom

### ISSUE THREAD

**Issue by tylerFowler** [atom/atom#6212]
I don't know about anyone else, but I find the little orange triangle with the Deprecation Cop warnings kind of annoying. Especially if I'm not working on a package it really doesn't add anything, plus some lint packages (Rubocop for example) uses the same icon to indicate warnings in code. I feel like this should be an option to show, but not default.

**Comment by 50Wliu** [comment]
Open Settings (<kbd>Ctrl</kbd>+<kbd>,</kbd>), navigate to Packages on the left-side hand, search for "Deprecation Cop", and then disable the package.

**Comment by irenapopova** [comment]
hi 
i have the same orange triangle warning , it is annoying,,,

**Comment by Aerijo** [comment]
@irenapopova The solution hasn't changed. If you don't want `deprecation-cop` to do it's job, just disable it.

I'd be more concerned about why it's triggering in the first place though. You may want to work out which package is causing it, and raise an issue on it's repo (if not already done by someone).

**Comment by irenapopova** [comment]
@Aerijo,
thanks , i am trying to upload my repo, but i faced a problem with gitignore file..
