### ISSUE TITLE
Build error on OS-X

### ISSUE THREAD

**Issue by jhetherly** [atom/atom#6217]
I've cloned the repository on OS-X 10.9.5 and tried compiling with clang 3.7.0. I get the following error:

/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h:16:45: error: expected '}' before '__attribute__'

I have the '.../atom/build/npm-debug.log' file but I don't see a way to upload it.

**Comment by izuzak** [comment]
Which command did you run to build Atom? Does your system satisfy the listed [requirements](https://github.com/atom/atom/blob/master/docs/build-instructions/os-x.md#requirements)? You can upload the debug log into a gist and post a link here.

**Comment by jhetherly** [comment]
I used the recommended command for OS-X:
script/build
Yes, my system meets the requirements. The version of node.js I'm using is (via MacPorts):
nodejs @0.12.0_0+python27+ssl
Here is the error:
https://gist.github.com/63548782f43fadc84a66.git

**Comment by kevinsawicki** [comment]
I don't think this is an Atom issue, looks like a core library file `/System/Library/Frameworks/Foundation.framework/Headers/NSUserNotification.h` is corrupt somehow or was misconfigured, closing this out.
