### ISSUE TITLE
Seems that atom don't follow my mouse move

### ISSUE THREAD

**Issue by gossel-j** [atom/atom#6219]
I run on ArchLinux with the package atom-editor-bin (precompiled version of atom-editor)
Everything seem to work fine and I updated from 0.188.0 to 0.189.0 today and now I can't select text with mouse (the text cursor just stay at the beginning of my grab), I can't use the scrollbar with mouse too
Seems that mouse is updated only when there is another event (keyboard, mouse click, mouse wheel) but not when mouse move

**Comment by mohoff** [comment]
Same problem here with same update process. Also the addon "minimap" isn't draggable anymore.

**Comment by gossel-j** [comment]
I compiled myself atom with the package atom-editor at v.0.189.0 and same problem, then i compiled from github tag v0.188.0 and no problem, the problem is only with v0.189.0

**Comment by gossel-j** [comment]
I found the problem, it is the atom-shell version
At version 0.21.3 everything works fine, I found this by doing a simple hello world app with atom-shell and test to select some text, at 0.21.3 everything works fine but since 0.22.1 (I can't start 0.22.0, segfault or something like that) the cursor stay a normal mouse (not the text selecting cursor) and i cant select text.

**Comment by paulcbetts** [comment]
@mohoff Are you using a virtual machine? What is the output of xinput?

**Comment by mohoff** [comment]
Hi, yes I am working on a Ubuntu guest. This is my `xinput list` output. I am not familiar with xinput, so please let me know if you need different outputs. Thanks.

xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ VirtualBox mouse integration            	id=9	[slave  pointer  (2)]
⎜   ↳ VirtualBox USB Tablet                   	id=10	[slave  pointer  (2)]
⎜   ↳ ImExPS/2 Generic Explorer Mouse         	id=12	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=11	[slave  keyboard (3)]

**Comment by paulcbetts** [comment]
This is #6243

**Comment by gossel-j** [comment]
I use a VM too
```
% xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ VirtualBox mouse integration            	id=9	[slave  pointer  (2)]
⎜   ↳ VirtualBox USB Tablet                   	id=10	[slave  pointer  (2)]
⎜   ↳ VirtualBox USB Multi-Touch              	id=11	[slave  pointer  (2)]
⎜   ↳ ImExPS/2 Generic Explorer Mouse         	id=13	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
```

**Comment by izuzak** [comment]
Also /cc https://github.com/atom/atom-shell/issues/1352

**Comment by mohoff** [comment]
Any update on this? This makes Atom unusable for me since version 0.189. Thanks!

**Comment by gossel-j** [comment]
I think chromium said that this bug will be fixed for next version (43)
