### ISSUE TITLE
Make TextEditor::getBuffer public?

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#6224]
See: https://discuss.atom.io/t/how-to-get-cursor-position-as-buffer-offset-one-dimensional-in-chars/15892

Shall we make the [`TextEditor::getBuffer` method](https://discuss.atom.io/t/how-to-get-cursor-position-as-buffer-offset-one-dimensional-in-chars/15892) a public API?

/cc @abe33 @kevinsawicki

**Comment by hedefalk** [comment]
My only input is that I really do need it :) I need the offset of the cursor and I can't find any other way than:

```
    editor = atom.workspace.getActiveTextEditor()
    textBuffer = editor.getBuffer()
    pos = editor.getCursorBufferPosition()
    offset = textBuffer.characterIndexForPosition(pos)
```
