### ISSUE TITLE
Failed to load config.cson / [stdin]:4:13: error: literal is not a function 'themes': [

### ISSUE THREAD

**Issue by pixelchutes** [atom/atom#6226]
1. Downloaded and installed latest Atom for OS X (very first time)
2. First time opening Atom was by running `atom` from CLI
3. Error thrown

![welcome_guide_-_atom](https://cloud.githubusercontent.com/assets/352182/6957501/fa79bd10-d8b8-11e4-98b1-fdd6d1640fa9.jpg)

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2

Just installed Atom (v0.189.0) for the first time on this particular system (OS X 10.10.2), and with the very first launch I was greeted with the following error:

> Failed to load `config.cson`
>```
[stdin]:4:13: error: literal is not a function
  'themes': [
            ^
```

`~/.atom/config.cson`: *(after first launch)*
```coffee
'editor':
  'fontSize': 16
'core':
  'themes': [
    'one-dark-ui'
    'one-dark-syntax'
  ]
   showOnStartup: false
```

`~/.atom/config.cson`: *(after delete + relaunch -- no more error)*
```coffee
"*":
  "exception-reporting":
    userId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  welcome:
    showOnStartup: false
```

`~/.atom/config.cson`: *(after changing theme)*
```coffee
"*":
  "exception-reporting":
    userId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  welcome:
    showOnStartup: false
  core:
    themes: [
      "one-dark-ui"
      "monokai"
    ]
  editor:
    invisibles: {}
```

**Comment by francoislaberge** [comment]
Same here

**Comment by lee-dohm** [comment]
I noticed in the *after first launch* `config.cson` there is a spacing issue. I was able to replicate the error message by replicating the spacing issue in my `config.cson`:

![napkin 04-02-15 3 00 14 pm](https://cloud.githubusercontent.com/assets/1038121/6974607/f9347716-d948-11e4-8317-23822e92580c.png)

**Comment by vlkosinov** [comment]
same issue on new computer

**Comment by pmagwene** [comment]
Fix is to delete stray space before `showOnStartup: false`

**Comment by francoislaberge** [comment]
@pmagwene In which file do we do that? Or is there a patch coming?

**Comment by francoislaberge** [comment]
Oh for what it's worth this went away for me, when I deleted my ```~/.atom``` folder, I did this for debugging another issue and just noticed that it went away. So I assume you mean ```~/.atom/config.json``` got corrupted somehow.

**Comment by pmagwene** [comment]
It's actually the default `~/.atom/config.cson`

**Comment by francoislaberge** [comment]
@pmagwene :+1:

**Comment by tec1** [comment]
To open file the corrupted file:
        Atom -> Open Your Config

**Comment by francoislaberge** [comment]
Does anyone know how this file is generated so someone can submit a patch with a fix for this?

**Comment by kevinsawicki** [comment]
Sorry about this one, should be fixed in the next Atom release, 0.190

**Comment by abdobelk** [comment]
Hello,

I updated Atom to v0.190.0 but still got that annoying issue. I managed to fix it:

1 - Atom -> Open Your Config
2 - In the config file, remove a whitespace before: **showOnStartup: false**
3 - Save the config file and restart Atom

That fixed the problem for me.

**Comment by itsSaad** [comment]
@abdobelk 's solution works.

**Comment by kyle-rader** [comment]
@abdobelk That's 2 for removing white space :). Thank you!

**Comment by iongion** [comment]
Even better one as I have no Idea what **showOnStartup: false** is, I just changed order, that statement is now before the themes section, no more issues, I still have no idea what they do, but no more red dialog.
```
'editor':
  'fontSize': 16
'core':
   showOnStartup: true
  'themes': [
    'one-dark-ui'
    'one-dark-syntax'
  ]
```
