### ISSUE TITLE
Single quote in html comment section should be ignored

### ISSUE THREAD

**Issue by brennanMKE** [atom/atom#6229]
I just generated a sample project using using the Ionic Framework and has an html file which has a line of text enclosed as a comment. You can see from the screenshot that it colors the code incorrectly as it thinks the single quote, uses as an apostrophe, is not handled properly.

I am running version 0.188.0 of the Atom editor.

![screen shot 2015-04-02 at 3 56 02 pm](https://cloud.githubusercontent.com/assets/277419/6975414/d76b8838-d950-11e4-9b48-abde840bc36a.png)

**Comment by mathiasvr** [comment]
I cannot replicate this, what theme are you using?

**Comment by izuzak** [comment]
@brennanMKE Please reopen this over at https://github.com/atom/language-html and include a link to the file in question (I'm having trouble reproducing this).

**Comment by brennanMKE** [comment]
Done.
