### ISSUE TITLE
crash when I copy text from atom 0.189.0 

### ISSUE THREAD

**Issue by mingjunyang** [atom/atom#6234]
0.189.0  crash often......
when I copy text

**Comment by brunobord** [comment]
I agree: 0.189.0 makes copy-pasting troublesome. When atom editor is running, it becomes impossible to perform regular copy-paste functions in other application (e.g.: gnome-terminal).

**Comment by mingjunyang** [comment]
My OS is openSUSE 13.2 (Harlequin) (x86_64) 64 位,desktop is gnome 3.14.2.

**Comment by mnquintana** [comment]
Related to #6231, #6221

**Comment by stainsby** [comment]
Middle mouse button paste now crashes for me (version 0.189).

**Comment by jacobmischka** [comment]
Middle mouse button paste is the only thing that I can use in atom without everything breaking, it seems to be working fine for me.

**Comment by zcbenz** [comment]
This is a duplicate of #6221.
