### ISSUE TITLE
Multiple String selection bottleneck

### ISSUE THREAD

**Issue by TeckniX** [atom/atom#6241]
Although perhaps uncommon to most, I use the Multiple String selection quite a bit and noticed that it can choke quite easily/quickly when the same string is used multiple times. 

For example take the following CSV:
https://gist.github.com/TeckniX/ddcacc78ce235d7702c0

Trying to do a multiple string selection on `,` and then typing out changes will be un-bearably slow (aka lagg and app seems frozen). Using the same file, Sublime barely breaks a sweat, yet the technique is the same.

**Comment by maxbrunsfeld** [comment]
I believe this is covered by #5025. Also, we think that multi-cursor editing performance will be improved by the refactoring going on as part of #307. Thanks!
