### ISSUE TITLE
Crash while editing markdown files

### ISSUE THREAD

**Issue by ringanta** [atom/atom#6247]
Atom crashed multiple times while editing markdown files with markdown preview plugin.
I am using OS X Yosemite 10.10.2 and Atom version 0.189.0

**Comment by izuzak** [comment]
Can you provide the crash reports for those crashes? You should be able to find them in Console.app. Also, if you can reliably reproduce this -- can you share the file you were editing and which steps reproduce this?

**Comment by ringanta** [comment]
I'll try to reproduce this and get back to you.

**Comment by kevinsawicki** [comment]
Closing this out since no further updates were provided on the crash, please comment if you have more details on the issue.
