### ISSUE TITLE
Multiple file requesters on File -> Open File on v0.189.0

### ISSUE THREAD

**Issue by mattcollier** [atom/atom#6257]
I'm using Debian 64 bit.  I just discovered that one can go to the file menu and choose Open File and a file requester opens.  One can leave that requester open and go back to the file menu and choose Open File again, and another file requester will open **behind** the first one.  This can be especially problematic because the the first file requester (including the cancel button) is non-responsive.

**Comment by mathiasvr** [comment]
Just tried this in OS X, the menu's are disabled during the open dialog, however you can still press cmd-o  and open multiple dialogs.

**Comment by damieng** [comment]
Not able to reproduce on Windows - is this still an issue in 1.7 on Mac or Linux?

**Comment by mattcollier** [comment]
@damieng yes, on Debian Stretch 64 Gnome with Atom Editor v1.7.3 behavior is still as described in the original post.

**Comment by mathiasvr** [comment]
Atom v1.7.3, Mac OS X 10.11.4
@damieng I as well see the same behavior as previously described.
