### ISSUE TITLE
UTF - 8 Plain Text Character Fails

### ISSUE THREAD

**Issue by ugurozturk** [atom/atom#6259]
It is not always does like this. But some of txt files fails. Plus, if i copy all types from NotePad and past it Atom it will be fixed. 

![atom issue](https://cloud.githubusercontent.com/assets/7994408/6997882/8d3654c2-dbd6-11e4-9a8e-908b32ae9e3e.PNG)

after copy all from NotePad
![fixed](https://cloud.githubusercontent.com/assets/7994408/6997895/ff18af86-dbd6-11e4-857e-147d997ff387.PNG)

Atom : 0.189.0 | 02.04.2015 00:44:55

**Comment by gabriel-tessier** [comment]
Have the same problem display small square for all Japanese text but the text is correctly saved when I type, it's more like a display problem.

**Comment by izuzak** [comment]
I think this is a duplicate of https://github.com/atom/atom/issues/6160 (and possibly https://github.com/atom/atom/issues/6214). Can you add your feedback to that issue or just subscribe for updates? Let me know if you believe this is not the same issue and please provide more information.

**Comment by gabriel-tessier** [comment]
Form me it's duplicate I try to set different Font Family (tried monaco, arial...) it doesn't change, the empty square are still here.
I also try the ugurozturk to copy paste text copying to Kate display correctly but paste back in atom still display square.
I think you can easily reproduce it by copying this 
---> full_width_numbers = u"""０１２３４５６７８９""" <----
The number gonna change to square like describe in the other issues you list.
in atom, previous version display correctly (my version: 0.189 on Kubuntu).

Hope it can help.
