### ISSUE TITLE
Atom doesn't work! [0.189.0, OSX 10.10.3]

### ISSUE THREAD

**Issue by evlogii** [atom/atom#6261]
I download and open latest version of Atom.app and got this!

![screenshot 2015-04-06 05 26 55](https://cloud.githubusercontent.com/assets/1588402/6999825/08aac236-dc1e-11e4-9bf9-f12816bad020.png)

I trying to delete Atom.app w/ CleanMyMac 2 but it doesn't help.
I also trying earlier versions (0.188.0 and 0.187.0) – got same problem.

What I can do to fix this?

**UPD:**
console logs
![screenshot 2015-04-06 06 05 12](https://cloud.githubusercontent.com/assets/1588402/7000088/e7c2a908-dc22-11e4-8aa4-5b09d3651307.png)

**Comment by mark-hahn** [comment]
It looks OK.  The dev inspector is open.  You can close that with
ctrl-alt-I.  You need to open a folder or file to see anything else.

**Comment by paulcbetts** [comment]
Delete your `.atom` folder and try again

**Comment by evlogii** [comment]
*Thanks.*

For those who have same problem – full path to **.atom** is `/Users/*username*/.atom`.
