### ISSUE TITLE
After installing on Win 7 Atom app cannot access external resources

### ISSUE THREAD

**Issue by tuhuw** [atom/atom#6266]
After installing Atom it is unable to find any external resources such as Packages, Themes or Updates. All of the dropdowns for these resources under settings simply say "Loading xxx ..." e.g. "Loading Packages ..." but the dropdown never populates.

I have tried uninstalling and re-installing but the problem remains.

Is there any means of diagnosing this issue? e.g using console commands or error logs?

This is a fresh installation of Atom 0.189.0 on Win 7 Pro SP1 (x64).
Node v0.12.2
npm v2.7.4
Chrome Version 41.0.2272.118 m

Please let me know if you need any further info.

Thanks
Huw

**Comment by izuzak** [comment]
Does Atom work normally besides that? Do you connect to the internet through a proxy? Do you see any errors in the Developer Tools console? (View -> Developer -> Toggle Developer Tools)

**Comment by tuhuw** [comment]
Hi Ivan, and thanks for the quick response. 

The editor does appear to work OK locally, and no I don't have a proxy, it's just a standard home ADSL connection direct to the internet. If I go to "Help -> Check for Update" then that seems to work OK and comes back with a message in a seconds or two to say that I'm up to date.

I turned on the developer tools but didn't see any errors in the console (or much activity at all to be honest).

Once I'd found that Developer menu I tried to run the Atom Specs, but that didn't go particularly well! It seemed to run through the 1618 Core Specs (with quite a few errors) but when it got part way through the 1392 Bundled Package Specs almost all of them seem to fail and eventually the whole app just falls over and says 'close window and report as an issue'. Trouble is when it does that I don't have any of the output in the window to send to you. Does it write these to a log somewhere that I can attach to this ticket?

Thanks
Huw

**Comment by tuhuw** [comment]
Have uninstalled again, then cleared all traces of atom from my profile, then re-installed ... same problem (it's now on v0.190.0, btw). When I looked in the Squirrel install logs there were no errors.

When I try apm from the command line it all seems to work OK; I can list, search remote repository and install packages.

I have found the Atom debugging page and tried to follow that with no joy or progress. The same issue happens in Safe mode and there's nothing logged to the Dev Tools console.

I saw somewhere there may be some issue with the version of node bundled with atom clashing in some way with an existing installation of node, so I tried taking the existing node and npm dirs off the path, but that didn't help either.

If someone could let me know how to trace the inner workings of atom to a log file somehow then I'd be most grateful.

Thanks
Huw

**Comment by izuzak** [comment]
Thanks for the additional information, @tuhuw. You said:

> When I try apm from the command line it all seems to work OK; I can list, search remote repository and install packages.

That's good -- that at least gives you a way to install packages (not a very elegant way, but still a way). Also, it makes me wonder if there might be a problem with calling apm from within Atom (which happens when you look at the list of packages in Settings View, for example). I'm not sure why that would be a problem, though, so I'm :phone: for backup -- @thedaniel @kevinsawicki, have you seen something like this happen before?

@tuhuw Also, if you open the Developer Tools consoler and run `atom.packages.getApmPath()`, what do you get back?

**Comment by tuhuw** [comment]
Thanks for the suggestion of the command to run in the console.

That command seems fine in Dev Tools console:

  atom.packages.getApmPath()
  "C:\Users\HuwNolan\AppData\Local\atom\app-0.190.0\resources\app\apm\bin\apm.cmd"

I can also get a list of all package names:

atom.packages.getAvailablePackageNames()
["atom-dark-syntax", "atom-dark-ui", "atom-light-syntax", "atom-light-ui", "base16-tomorrow-dark-theme", "base16-tomorrow-light-theme", "one-dark-ui", "one-dark-syntax", "one-light-syntax", "one-light-ui", "solarized-dark-syntax", "solarized-light-syntax", "archive-view", "autocomplete", "autoflow", "autosave", "background-tips", "bookmarks", "bracket-matcher", "command-palette", "deprecation-cop", "dev-live-reload", "encoding-selector", "exception-reporting", "feedback", "find-and-replace", "fuzzy-finder", "git-diff", "go-to-line", "grammar-selector", "image-view", "incompatible-packages", "keybinding-resolver", "link", "markdown-preview", "metrics", "notifications", "open-on-github", "package-generator", "release-notes", "settings-view", "snippets", "spell-check", "status-bar", "styleguide", "symbols-view", "tabs", "timecop", "tree-view", "update-package-dependencies", "welcome", "whitespace", "wrap-guide", "language-c", "language-clojure", "language-coffee-script", "language-csharp", "language-css", "language-gfm", "language-git", "language-go", "language-html", "language-hyperlink", "language-java", "language-javascript", "language-json", "language-less", "language-make", "language-mustache", "language-objective-c", "language-perl", "language-php", "language-property-list", "language-python", "language-ruby", "language-ruby-on-rails", "language-sass", "language-shellscript", "language-source", "language-sql", "language-text", "language-todo", "language-toml", "language-xml", "language-yaml"]

It just seems to be the Settings UI that fails to invoke the underlying commands for some reason?

**Comment by tuhuw** [comment]
Not sure if this is relevant or connected in any way, but if I do Ctrl + R in a file (JavaScript grammar) then I get the Symbols popup pane, but it doesn't populate. It sits there with the hourglass icon saying "Generating symbols".

**Comment by xlaywan** [comment]
I have the same issue, after updating from 0.188 to 0.190. Reinstall didn't help. Console is clear and have no AJAX requests.
Win10 x64.

**Comment by xlaywan** [comment]
After installing Windows 10 TP build 10049 it worked for me.

**Comment by tuhuw** [comment]
Running 0.191 now, but same problem failing to load any dropdown lists for Packages, Themes, Updates, and even Symbols.

Have tried disabling AntiVirus (Kaspersky Internet Security 2014), but made no difference.

Can anyone suggest any further diagnostics I can try, or actions I can take?

**Comment by kmyl** [comment]
Hi, 
This could help,

When i install the last official release 0.196.0 for windows, everything works fine,
But when i install atom from my own-build  installer for windows, the symptoms are the same described here.


Any suggestion?

Thanks

**Comment by kmyl** [comment]
I have discovered that, 

with my self-builded atom installation,

atom.packages.getApmPath();  gives:
"C:\Users\kmyl\AppData\Local\atom\app-0.197.0\resources\app\apm\node_modules\atom-package-manager\bin\apm.cmd"

but the directory " apm" doesn't exist  in "app"

On the other hand,
a directory "new-app\apm"  was created in "resources".

**Comment by benogle** [comment]
Is this still an issue?

**Comment by tuhuw** [comment]
Hi there,

Thanks for asking about this. Yes, it is still an issue on my work laptop; any fields on the settings screen which should populate a list of values simply do nothing. Every field sits there with the initial "xxx is loading ..." message and the hourglass icon. See screenshot for an example of the packages screen.

![atom package screen](https://cloud.githubusercontent.com/assets/1635995/10411024/7dce566c-6f4f-11e5-81d7-31e90e09689c.png)

Atom is now at v1.0.19.
Laptop is running Win 7 Pro SP1 64-bit

Atom is working fine on my home desktop PC (Win 7 Home SP1 64-bit) so I accept that it is probably something environmental on the work laptop that's causing this. 

What would really help are some pointers on how I could begin to diagnose the cause of this issue
- Any debug logging I could turn on?
- Any chrome console commends I could try?
- Any commands I could try on the command line?

Yours hopefully,
Huw

**Comment by damieng** [comment]
If you type these commands on the command line do you get anything?

```
apm list
apm search a
```

**Comment by damieng** [comment]
No response, I think the most recent incident of this is likely proxy related and not the same as the original cause.
