### ISSUE TITLE
atom copy paste event cause ubuntu 14.04 freeze

### ISSUE THREAD

**Issue by nvcken** [atom/atom#6267]
Sometime copy paste hightlighted text from Atom to other app likes browser , skype ... or reversed cause ubuntu 14.04 freeze keyboard , mouse move super slow/lag then whole system hang up need to hold power button to turn off

**Comment by rootStar-lock** [comment]
+1. I got the same on Debian 8. After downgrade Atom to 0.188.0 the problem was fixed.

**Comment by m1ga** [comment]
duplicate: https://github.com/atom/atom/issues/6221

**Comment by benogle** [comment]
Closing in favor of #6221
