### ISSUE TITLE
Reloading on an external monitor moves the window back to the primary monitor

### ISSUE THREAD

**Issue by oclbdk** [atom/atom#6268]
Steps to repro:
1. Open Atom in the primary monitor
2. Move the window to an external monitor
3. Reload

I expect the window to stay on the external monitor, but it jumps back to the primary monitor.

**Comment by mnquintana** [comment]
What OS and Atom version?

**Comment by izuzak** [comment]
Can't reproduce this on OSX 10.10.2, Atom 0.190.0-bbd308b.

**Comment by mnquintana** [comment]
I was able to reproduce this just now in safe mode with Atom 0.189.0 and OS X 10.10.2

**Comment by izuzak** [comment]
@mnquintana Interesting -- thanks for helping investigate this. Can you share the steps you performed? The steps above don't trigger the problem for me. :confused:

**Comment by mnquintana** [comment]
Alright, so this is my setup:

- 1 external monitor
- MacBook Air with display on

The external monitor is configured to be the default (ie. in System Preferences > Displays > Arrangement I dragged the menu bar to the external monitor), although I'm not sure if this makes a difference.

1. Open folder with `atom --safe`
2. Drag window to non-primary monitor (ie. MacBook Air display)
3. Open Command Palette > Window: Reload
4. As the window is reloading, it pops back over to the primary display (the external monitor).

**Comment by izuzak** [comment]
Thanks, @mnquintana -- that reproduces it for me as well. :bow:

**Comment by lpommers** [comment]
:+1: I experience this frequently

**Comment by benogle** [comment]
cc @zcbenz is this an electron thing?

**Comment by zcbenz** [comment]
Atom saves and restores window dimensions when reloading the window, it seems that Atom saves the dimensions relatively to current monitor, and restores the dimensions by treating them as absolute ones.
