### ISSUE TITLE
Allow a location option when adding menu items

### ISSUE THREAD

**Issue by jessegrosjean** [atom/atom#6270]
Right now when you add menu items they get inserted at the bottom of the specified menu. I would like to have some optional way to the specify a location when inserting menu items. From what I can tell this isn't possible now. Is anyone working on this already? If not and I create a solution what are the chances that I can get it merged into Atom?

My basic design would follow how I think Eclipse solves this problem. Haven't actually used Eclipse for years, but I think the basic idea is: Give each item an optional "location" attribute that's used to determine where the item is inserted relative to existing item IDs in the menu.

The ID of existing menu items would be an "ID" attribute if found, otherwise it would fallback to using "label", though that's problematic if menus will ever be localized.

The set of locations specifiers would be:

`location="top"` - The item will be inserted at the top of the menu.

`location="bottom"` - The item will be inserted at the bottom of the menu.

`location="before:id"` - The item will be inserted before the existing item with matching ID.

`location="after:id"` - The item will be inserted after the existing item with matching ID.

`location="endof:id"` - The item will be inserted at the end of the separator group with matching ID. (this means it will be inserted right before the next separator group starts.

**Comment by jessegrosjean** [comment]
I've created a pull request in Atom Shell to get this started:

https://github.com/atom/atom-shell/pull/1373

Once that's in place then I think the next changes would be to define ids for existing Atom menus and to update menu-helpers.coffee to include ids and positions attributes when merging templates. Feedback still welcome of course.

**Comment by mnquintana** [comment]
For anyone else following this, see https://discuss.atom.io/t/is-there-a-way-to-specify-menu-item-order-when-inserting-menu-items/14937 for more design discussion.

**Comment by mnquintana** [comment]
@jessegrosjean Looking at the API you implemented in atom/electron#1373, I think rather than a string, I'd rather see it implemented as object properties, so something like:

```cson
  'atom-pane[data-active-item-path] .item-views': [
    {
      'label': 'Reveal in Tree View', 
      'command': 'tree-view:reveal-active-file', 
      'position': {
        'endof': 'tree-view:show-in-file-manager'
      }
    }
  ]
```

Instead of:

```cson
  'atom-pane[data-active-item-path] .item-views': [
    {
      'label': 'Reveal in Tree View', 
      'command': 'tree-view:reveal-active-file', 
      'position': 'endof=tree-view:show-in-file-manager'
    }
  ]
```

What do you think?

**Comment by jessegrosjean** [comment]
@mnquintana Yeah that looks good to me, though I don't have a strong preference.

I'm in waiting mode here. Hoping to get direction from a core Atom committer who can actually merge the pull request before I spend time on the implementation. It does seems like the underlying implementation is solidly accepted into electron, but I'm not sure if it's wanted in Atom or not.

Jesse

**Comment by millermedeiros** [comment]
any updates on this issue? what else is needed to get this working inside Atom?

I tried the examples found on [electron menu documentation](https://github.com/atom/electron/blob/master/docs/api/menu.md#menu-item-position) but it did not work for both `menu` and `context-menu`.

I like the `position: 'endof=tree-view:show-in-file-manager'` syntax, makes more sense than `position: { endof: 'tree-view:show-in-file-manager' }` because an item can't be in two places at the same time there is no need to have an object for `position`.

**Comment by jessegrosjean** [comment]
I haven't done anything more on this and probably won't work on it for the foreseeable future. I'm afraid someone else needs to push this forward if it's going to go anywhere.

**Comment by captbaritone** [comment]
I have a PR open to address this here: https://github.com/atom/atom/pull/16661

**Comment by Ben3eeE** [comment]
Thanks @captbaritone :bowing_man:
