### ISSUE TITLE
2 Deprecated Calls | Atom Core

### ISSUE THREAD

**Issue by mattlovaglio** [atom/atom#6278]
Since the last update, Deprecation Cop lists 2 issues. 
Running OS X Yosemite 10.10.2
Atom Version 0.189.0 (0.189.0)

Once my JavaScript knowledge is up to par, I hope to help fix these things myself. Is this the type of notification I should be shedding light on?

![example-screen-shot](https://cloud.githubusercontent.com/assets/10821303/7016812/6aa922b0-dcba-11e4-9ebb-b56963c9800f.jpeg)

**Comment by izuzak** [comment]
Thanks for the report. That's strange -- I'm not seeing this in 0.189.0 which I just downloaded. May I ask how you installed Atom exactly? 

/cc @kevinsawicki in case he has any :thought_balloon: about this

**Comment by mattlovaglio** [comment]
@izuzak I originally installed it from the atom.io website. If it's just my instance, which seems to be the case, I'll uninstall it right now and reinstall. Let's see what happens when I do that. I'll throw another comment up here when I'm done.

**Comment by mattlovaglio** [comment]
@izuzak @kevinsawicki I just got done uninstalling Atom and reinstalling it. The same 2 warnings appear. When I was backing up my snippets file (just copying and pasting what I had put there) it threw a 3rd error, as illustrated below. 

![dep-cop-3-warnings](https://cloud.githubusercontent.com/assets/10821303/7028314/1b02bea6-dd23-11e4-9db2-baefb38e33f5.jpeg)

Here are some things I noticed. I used the mac app APP CLEANER to uninstall Atom, that way it got uninstalled as cleanly as possible. When I reinstalled the application it remembered all of my settings and kept all of my community packages. Should I try uninstalling it in a way that it is a total reset? If so, how might I go about doing that.

In case there are any packages causing this, here is a screenshot of all my community packages:

![installed-packages](https://cloud.githubusercontent.com/assets/10821303/7028387/989b93d8-dd23-11e4-9f9e-47640bbfe5fe.jpeg)

Let me know If I can help along in any way. Thanks.

**Comment by 50Wliu** [comment]
To get rid of all your settings you can just rename `~/.atom` to something like `~/.atom-backup`.

**Comment by izuzak** [comment]
:+1: to @50Wliu's idea. I'm wondering if this is somehow getting attributed to Atom core but is coming from a package? Running Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) or temporarily renaming the `~/.atom` folder should confirm that (remember to quit and restart Atom).

**Comment by mattlovaglio** [comment]
Update! @izuzak @50Wliu I ran Atom in safe mode as suggested. Deprecation Cop said it was all clear, no issues. I went through and manually disabled each community package (that wasn't authored by the core atom team) and found two packages that threw one error each.

The first was **Atom Alignment ** https://github.com/Freyskeyd/atom-alignment

And the second was **Autoclose HTML** https://github.com/mattberkowitz/autoclose-html

I'll open a ticket for those two packages explaining the issue and reference this thread. Thanks for the help! :)

**Comment by theplotlessplot** [comment]
Had the exact same problem. The packages causing the Deprecation Cop warning were, in my case, **autoclose-html** and **color-picker**.

**Comment by mattlovaglio** [comment]
@theplotlessplot When Atom hits 1.0, packages that use deprecated API's won't be able to run in Atom at all, according to today's blog post: http://blog.atom.io/2015/04/07/project-updates.html

**Comment by ttaranto** [comment]
+1

**Comment by idan** [comment]
Crossposting from #6310, seeing this in:

- Emmet: [https://github.com/emmetio/emmet-atom/issues/257]
- sublime-style-column-selection: [https://github.com/bigfive/atom-sublime-select/issues/42]
- linter-jshint: [https://github.com/AtomLinter/linter-jshint/issues/60]
- linter-jsonlint: [https://github.com/AtomLinter/linter-jsonlint/issues/8]
- redacted: [https://github.com/ymendel/atom-redacted/issues/2]

Is there a canonical place for tracking the work to bubble up the proper source of the deprecation warnings? As opposed to them (spuriously) appearing to emanate from atom-core.

**Comment by izuzak** [comment]
@idan I've opened https://github.com/atom/deprecation-cop/issues/36 to track this problem of reporting the wrong origin of a deprecated call.
