### ISSUE TITLE
Tab resize should be delayed

### ISSUE THREAD

**Issue by karai17** [atom/atom#6287]
If I have a lot of tabs open and I want to close several of them, it can be a little annoying to have to continue adjusting the mouse when I am trying to close tabs as they resize. Chrome does a good job at this: When you close a tab, the other tabs shift to fill the space but they do not resize to fill space for a second or two, giving you the ability to close several tabs in a row quickly without having to move your mouse.

**Comment by mnquintana** [comment]
:+1: I really like this idea!

**Comment by philipgiuliani** [comment]
Chrome isn't delaying the tab-resize, they are doing it as soon as you remove the mouse from the tabbar. I also would like to see this nice feature :)

For now, just use `CMD + W`.

**Comment by izuzak** [comment]
This issue was moved to atom/tabs#129

**Comment by izuzak** [comment]
@karai17 I like the idea as well, but as @philipgiuliani mentioned -- it should be in the issue tracker for the tabs package. I just moved it over there, so feel free to continue the discussion in that issue. :+1:
