### ISSUE TITLE
Different menu items in menu bar on different OS?

### ISSUE THREAD

**Issue by asantos3** [atom/atom#6288]
Why is the menu bar different in Linux and Windows?

Here are the differences side by side:

* [Screenshot of File](https://cloud.githubusercontent.com/assets/1958425/7028920/378f9cd2-dd51-11e4-9f2a-14c0906fcda6.png)
* [Screenshot of Edit](https://cloud.githubusercontent.com/assets/1958425/7028921/3791401e-dd51-11e4-849a-4aa4ba6f4132.png)
* [Screenshot of View](https://cloud.githubusercontent.com/assets/1958425/7028919/378f4732-dd51-11e4-8e95-0a6e7a094038.png)

Notice the Settings and Open Your * in File on Ubuntu and on Windows in Edit with Settings renamed to Preferences. Shouldn't they always be on Edit with Settings instead of Preferences?

Also, on Windows there's that Panes sub-menu, why is it removed on Ubuntu?

**Comment by 50Wliu** [comment]
Typically Linux applications have Settings in the Edit menu, which includes stuff like opening the keymap.  On Windows those things are generally in Tools or File.

I think the Pane stuff is being tracked in a different issue.

**Comment by asantos3** [comment]
That makes sense, thanks ;)

I'm closing this because the pane stuff is #1897
