### ISSUE TITLE
how to change variable colours 

### ISSUE THREAD

**Issue by jsjain007** [atom/atom#6290]
i want to change text color variable color to make the code more attractive but i cant find any such settings to do so i.e. where can i edit the color code of the syntax .
can anyone please guide me the process to do so .

**Comment by simurai** [comment]
Do you mean changing a Less variables a the syntax theme? That's currently not possible. Maybe part of #5903.

What you __can__ do is override the syntax highlighting in your `styles.less`. Like

```css
atom-text-editor::shadow . comment {
  color: black;
}
```

makes the "comments" black. Or if you meant to change syntax highlighting of "variables" in your code, it would be this:

```css
atom-text-editor::shadow .variable {
  color: blue;
}
```

**Comment by jsjain007** [comment]
yes i want to change the colour in similar way but to be precise like this in image
as in notepad ++  (on left side)
i tried to change but but cant find out how to change register's colors i.e. ah , bh, etc in assembly language , (as in image on right side) if any one knows please help me out thanks in advanve .
![capture](https://cloud.githubusercontent.com/assets/6463002/7074436/0de07ece-df18-11e4-8798-b3e395908809.PNG)

**Comment by simurai** [comment]
You'd have to check what the CSS selector is called. Either by using the Dev Tools and inspect the element.

Or from this [discussion](https://discuss.atom.io/t/how-to-see-what-syntax-markup-is-being-used/14172/3) you can use the `Cmd+Alt+P` shortcut that shows a notification with the selectors used.

![screen shot 2015-04-10 at 11 56 48 am](https://cloud.githubusercontent.com/assets/378023/7081157/ba4aa120-df78-11e4-9133-0222fba766d3.png)


In that case you would add this:

```css
atom-text-editor::shadow .variable.registers.x86.assembly {
  color: orange;
}
```

to your `styles.less` file and that makes the `ah` orange instead of red.

**Comment by jsjain007** [comment]
i tried editing my styles.less file but i cant see any change in he color code i restarted my editor also can you be please a little more specific what exactly i have to do and can i get all these code documentation like .variable.register.x86... so that i can edit my colors on my own and can make on theme on my own .

**Comment by simurai** [comment]
When you move your cursor to the code you want to change the color and press `Cmd+Alt+P`.. what does it say in the popup?

**Comment by jsjain007** [comment]
when i press cmd+alt+p it opens specs suite

**Comment by 50Wliu** [comment]
@jsjain007 are you using a Mac or Linux/Windows?  If you're not on a Mac then the keybinding is <kbd>Ctrl+Alt+Shift+P</kbd>.

**Comment by simurai** [comment]
Alternatively, you can also use the Dev Tools.

1. Open from the menu.
![screen shot 2015-04-11 at 9 09 15 am](https://cloud.githubusercontent.com/assets/378023/7099339/2d8b9d62-e02b-11e4-90f1-2f3338dfbf43.png)

2. Click the magnifying glass (top right corner), then click on the code you want to inspect.
![screen shot 2015-04-11 at 9 12 45 am](https://cloud.githubusercontent.com/assets/378023/7099346/5aaa5d9c-e02b-11e4-9411-95c1b9ed0120.png)

3. Then you should see what CSS selector is used. For example in the screenshot above, it would be `.variable.registers.x86.assembly`. So in `styles.less` you have to add `atom-text-editor::shadow` in front to "reach" into the editor. Together it would look like this:

```css
atom-text-editor::shadow .variable.registers.x86.assembly {
  color: orange;
}
```

**Comment by jsjain007** [comment]
i would like to add something that my assembly files are not .s instead they are .asm so as to compile them in masm11 and for me css selctor is showing 
![image](https://cloud.githubusercontent.com/assets/6463002/7104919/13359074-e11d-11e4-982f-f3eaba59e28a.png)

so i suppose 
atom-text-editor::shadow .storage.registers {
  color: orange;
}
will be correct  ?

**Comment by jsjain007** [comment]
yep thanks a lot it worked like a charm could you also tell me to to change font size for a particular set of words like for storage,registers only ?

atom-text-editor::shadow .keyword.mnemonic {
        color: #12167f;
       font: bold;
}

something like this it doesn't seems to work is it even possible ?

**Comment by jsjain007** [comment]
yep thanks a lot it worked like a charm could you also tell me to to change font size for a particular set of words like for storage,registers only ?

atom-text-editor::shadow .keyword.mnemonic {
        color: #12167f;
       font: bold;
}

something like this it doesn't seems to work is it even possible ?

**Comment by jsjain007** [comment]
yep thanks a lot it worked like a charm could you also tell me to to change font size for a particular set of words like for storage,registers only ?

atom-text-editor::shadow .keyword.mnemonic {
        color: #12167f;
       font: bold;
}

something like this it doesn't seems to work is it even possible ?

**Comment by 50Wliu** [comment]
Hi @jsjain007 I've deleted two duplicate comments of yours (just a heads-up).

**Comment by jsjain007** [comment]
sorry i think that time some problem was there with my internet connectivity so i didnt knew how many times it was posted i never intended to do so .

**Comment by simurai** [comment]
>  could you also tell me to to change font size

The font size is set by the user in the settings and shouldn't be overridden. So using `font` would change that. If you only want to make it bold, you could use `font-weight` instead:

```css
atom-text-editor::shadow .keyword.mnemonic {
  color: #12167f;
  font-weight: bold;
}
```

**Comment by kevinsawicki** [comment]
Closing this out since all the questions were answered it appears.

**Comment by WiliTest** [comment]
`::shadow` seems depreciated. New syntax:
 // commments color
`atom-text-editor { .syntax--comment { color: rgb(93, 228, 19);}}`
