### ISSUE TITLE
Disk defragmentation can't move apm files on Windows

### ISSUE THREAD

**Issue by onbjerg** [atom/atom#6293]
Hello!

I am currently in the process of installing Linux on one of my drives, and in order to do that I freed around 200 gigabytes worth of space. The next step would be to shrink the partition on the drive to make more room for a new partition.

I can only shrink the volume by 2GB, though. I checked the logs, and the culprit is an immovable file in one of my Atom packages.

``Users\Oliver\.atom\.node-gyp\.atom\.apm\esmangle\1.0.1\package\lib\pass::$SECURITY_DESCRIPTOR``

What to do, what to do?

Thanks!

**Comment by onbjerg** [comment]
Extra! It probably is because the path to the file is too long. I tried to delete the file manually (as this is from an old installation, so it's a-ok), and it wouldn't because the path was too long.

Any thoughts on this? Is this a common problem?

**Comment by 50Wliu** [comment]
Long file paths strike again :(
@zcbenz @kevinsawicki @paulcbetts

**Comment by onbjerg** [comment]
Oh, yeah. Final update. I deleted a bunch of node modules and apm modules for an old installation of Atom on an old drive, and I was able to use all of my free space for a sweet Arch Linux setup!

So, yeah, basically long file paths.

**Comment by damieng** [comment]
Long paths on Windows will continue to be an issue until NPM 3 migration happens, sorry.
