### ISSUE TITLE
0.190.0 windows installer does not setup correctly.

### ISSUE THREAD

**Issue by xpol** [atom/atom#6300]
* With an upgrade install, the `Open with Atom` shell menu and `apm` command tool are bot not upgrade (still pointed to older version).

* remove atom and setup again, the  `Open with Atom` shell menu and `apm` command tool are both gone

**Comment by Zireael07** [comment]
What version of Windows? Is there apm tool on Windows?

**Comment by xpol** [comment]
Windows 7 64 bit

**Comment by xpol** [comment]
Still not working in 0.192.0.

**Comment by kevinsawicki** [comment]
Closing this out since this seems like an intermittent auto-update bug that is hopefully fixed by upgrading to a newer version.

You can uninstall and reinstall to get the explorer context menus back, sorry about this.
