### ISSUE TITLE
Markdown Preview Chinese,So terrible！

### ISSUE THREAD

**Issue by mingjunyang** [atom/atom#6302]
```markdown
#ymsWebClient



###build dist
 1. 手工删当前的额dist文件夹

 2. 项目根目录下执行命令
  `
  gulp build
  `

```
```html
<h1 id="ymswebclient">ymsWebClient</h1>
<h3 id="build-dist">build dist</h3>
<ol>
<li><p>手工删当前的额dist文件夹</p>
</li>
<li><p>项目根目录下执行命令
<code style="font-family: DejaVu Sans Mono,Source Code Pro,WenQuanYi Micro Hei;">gulp build</code></p>
</li>
</ol>
```

But privew is ![iamge][privew]

[privew]:https://github.com/mingjunyang/myvimconf4c/blob/master/2015-04-08.png "why it is url?"

**Comment by izuzak** [comment]
That works for me:

![screen shot 2015-04-08 at 15 13 30](https://cloud.githubusercontent.com/assets/38924/7045835/e08c0be4-de01-11e4-9a35-33b8bd504cd3.png)

Please reopen the issue on the [package's issue tracker](https://github.com/atom/markdown-preview) and provide more information (e.g. which version of Atom and which OS are you using, your config.json file and which encoding the file is using, can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)).

**Comment by mingjunyang** [comment]
after 0.189.0,chinese so terrible.
