### ISSUE TITLE
jquery.min.js cause hangs

### ISSUE THREAD

**Issue by fiftin** [atom/atom#6304]
I have selected jquery.min.js (84Kb) in Tree View and Atom is hangs. But jquery.mobile.min.css (1 line 200Kb) does not cause hangs.
Version: 0.188.0

**Comment by mnquintana** [comment]
Duplicate of #979

**Comment by izuzak** [comment]
Thanks, @mnquintana. :bow: 

@fiftin Please subscribe to https://github.com/atom/atom/issues/979 for updates on this issue.

**Comment by fiftin** [comment]
Ok, thanks
