### ISSUE TITLE
Ctrl+Comma stopped working in 0.190

### ISSUE THREAD

**Issue by medowlock** [atom/atom#6305]
What more is there to say ... :)

**Comment by mnquintana** [comment]
What OS? Does this happen in safe mode? (`atom --safe`)

**Comment by izuzak** [comment]
@medowlock `ctrl-,` is still [bound to the command for showing the settings view](https://github.com/atom/settings-view/blob/ed8c548f6bf54b19d67c17c943a31a0033b17886/keymaps/settings-view.cson#L5). Is that not happening for you? Can you take a screenshot of what you see in the [keybinding resolver](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings) when you hit `ctrl-,`? Also, try running Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) as @mnquintana suggested and let us know if that helps.

**Comment by medowlock** [comment]
OS is Windows 8.1, does not happen in safe mode.

@izuzak Using the keybinding resolver, it looks like the "emmet" package was the one that broke this shortcut. Removing it fixed the issue.

Thanks! Keep up the good work ! :)
