### ISSUE TITLE
Random lockups on Win 8.1 Pro 64bit

### ISSUE THREAD

**Issue by JohnMurga** [atom/atom#6308]
After build 188 I am getting random lockups on Win 8.1 Pro 64bit.
Editor is not responding (freeze, no CPU use).

On one occasion I just started Atom 190, CTRL-SHIFT-P -> Settings -> Plugins -> Type something into the "Filter packages by name" field (freeze).

None of the builds over the few months have exhibited this behavior ...
188 works fine although I stick with 187 for day to day use because of the "undo" regressions.

I do have a lot of plugins ... Some of which upgrade to newer versions with build 190 ...
What is the best way for me to diagnose this ?

**Comment by izuzak** [comment]
@JohnMurga A good way to start is to run Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) and see if that helps. If it does, then it's probably one of the packages causing problems and you can try disabling them one-by-one to see which one it is.

**Comment by JohnMurga** [comment]
Whatever it was appears to be fixed in 191
