### ISSUE TITLE
Building fails on Arch Linux (AUR package atom-editor)

### ISSUE THREAD

**Issue by jplatte** [atom/atom#6314]
I'm trying to build Atom on arch linux ([this package](https://aur.archlinux.org/packages/atom-editor/)), and I'm getting an error because of a missing "node" executable. This is the full build output:

    ==> Making package: atom-editor 0.190.0-1 (Thu Apr  9 03:15:22 CEST 2015)
    ==> Checking runtime dependencies...
    ==> Checking buildtime dependencies...
    ==> Retrieving sources...
      -> Found v0.190.0.tar.gz
      -> Found atom-python.patch
    ==> Validating source files with sha256sums...
        v0.190.0.tar.gz ... Passed
        atom-python.patch ... Passed
    ==> Extracting sources...
      -> Extracting v0.190.0.tar.gz with bsdtar
    ==> Starting prepare()...
    patching file atom.sh
    ==> Removing existing $pkgdir/ directory...
    ==> Starting build()...
    Node: v0.12.2
    npm: v2.5.1
    Installing build modules...
    Installing apm...
    /home/jonas/atom-editor/src/atom-0.190.0/apm/node_modules/atom-package-manager/bin/apm: line 40: /home/jonas/atom-editor/src/atom-0.190.0/apm/node_modules/atom-package-manager/bin/node: No such file or directory
    ==> ERROR: A failure occurred in build().
        Aborting...

I searched my pacman logs and found that between the last build and now nodejs was updated from 0.12.2-1 to 0.12.2-2. The previously built version was 0.189.0, and there I didn't have this problem. Due to the only nodejs change from the last successful build being pkgrel, I guess it's not a problem with that, but maybe it is interesting.

**Comment by OscarOrSomething** [comment]
From the AUR:

```
@Kavachaj

To install this package, I installed npm manually(it is going with nodejs package), and then deleted 'npm' in 'makepepends=' line in PKGBUILD. Dear maintainer, please fix the PKGBUILD file, as 'npm' package in makedepends causes an build error since it doesn't exists in AUR.
```

Try this if you are still getting errors?

**Comment by jplatte** [comment]
Oh, sorry for not closing this earlier. This problem already disappeared quite some time ago.

**Comment by kyp0717** [comment]
can you tell us how you solve this issue?

**Comment by jplatte** [comment]
I didn't solve this issue at all, it just disappeared a few releases after I opened this issue. If you're having problems with the current version, you're probably better of opening a new one.

**Comment by roosemberth** [comment]
Successfully built from AUR: http://txt.do/anotv
