### ISSUE TITLE
Copy and Pasting from Chrome browser crash the atom 

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#6316]
When i copy paste code from chrome or copy pasting to chrome make atom unresponsive and crash.

tested on 189

**Comment by izuzak** [comment]
Should be fixed in 0.190.0, see https://github.com/atom/atom/issues/6221 for more information. Let us know if you can still reproduce in 0.190.0.

**Comment by v3ss0n** [comment]
Thanks , i didn't realize that 0.190 released
