### ISSUE TITLE
Atom 0.189.0 won't start on Ubuntu 14.10 anymore

### ISSUE THREAD

**Issue by jurgenhaas** [atom/atom#6317]
Atom version:
Tested on 0.189.0 and today also on 0.190.0

Environment:
Ubuntu 14.10 with all updates
16GB RAM, 64 Bit, Intel Core i5, Intel Ivybridge Mobile

Steps:
Try to start atom from the shell and wait for a few seconds, Ubuntu will show an error message and close the process.

In ~/.atom/nohup.out there is the following error message:

```
[30153:0409/093929:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDS
andboxDevelopment for more information on developing with the sandbox on.
LaunchProcess: failed to execvp:
/proc/self/exe
App load time: 179ms
```

**Comment by jurgenhaas** [comment]
In addition to the error message in nohup.out the crash report from Ubuntu displays the crash with the following title: "atom crashed with SIGSERV in atom::api::WebContents::GetURL()"

**Comment by AvinashKrSharma** [comment]
I am also facing the same issue from some time.

**Comment by mnquintana** [comment]
Does this only happen when starting from the command line? Does it open normally when you start it from Launcher?

**Comment by jurgenhaas** [comment]
It's the same in both cases.

**Comment by mnquintana** [comment]
Hmm, I can't seem to reproduce this with Atom 0.190.0 and Ubuntu 14.10.

How did you install Atom? Was it from the pre-built .deb file, the unofficial PPA, or built from source?

Do you get the same error if you run Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) (`atom --safe`)?

**Comment by jurgenhaas** [comment]
I have installed it via ```apt-get install atom``` and yes, I do get the same error in sage mode

**Comment by izuzak** [comment]
@jurgenhaas do you see the same problem if you uninstall Atom and install it again by following [these instructions](https://github.com/atom/atom#debian-linux-ubuntu)?

**Comment by jurgenhaas** [comment]
@izuzak unfortunately that doesn't make any difference.

**Comment by jurgenhaas** [comment]
Some more information, after I have deleted my ~/.atom directory and started again, the nohup.out contained a couple more lines which may probably help:

```
[27935:0413/083630:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for
 more information on developing with the sandbox on.
LaunchProcess: failed to execvp:
/proc/self/exe
App load time: 175ms
LaunchProcess: failed to execvp:
/proc/self/exe
[27935:0413/083631:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1
[27935:0413/083631:ERROR:channel.cc(305)] RawChannel read error (connection broken)
```

**Comment by mnquintana** [comment]
@jurgenhaas I suspect that it's an issue with the build on the unofficial Atom PPA. There currently is no official PPA for Atom (you can track #2956 for updates on that), so if you installed via `apt-get` then it was likely from `ppa:webupd8team/atom`. 

I'm going to try installing this from that PPA on my VM to confirm, but in the meantime would you also mind trying to install from the [official `.deb` release](https://github.com/atom/atom/releases/tag/v0.190.0) and see if you run into the same issue?

**Comment by jurgenhaas** [comment]
@mnquintana, isn't that what @izuzak suggested already before? I've done that (installing the .deb release) and that made no difference.

**Comment by mnquintana** [comment]
@jurgenhaas Ah sorry, I misread that. I'll try to see if I can reproduce this locally later.

**Comment by jurgenhaas** [comment]
@mnquintana have you had a chance to reproduce this yet?

**Comment by yaph** [comment]
I have the same issue on Ubuntu 15.04. I tried releases from 0.188 up to the latest. With none of them atom can be started.

**Comment by jurgenhaas** [comment]
Meanwhile I've also updated to Ubuntu 15.04 as well and still can't use Atom anymore.

**Comment by mnquintana** [comment]
Hmm, I still haven't been able to reproduce this on Ubuntu 14.04 or 14.10. I think I'll try spinning up a new 15.04 VM and see what happens - I'll keep you all posted!

**Comment by 50Wliu** [comment]
No problems here on 15.04.

**Comment by yaph** [comment]
I did a fresh install of Ubuntu 15.04, before I had done several distribution upgrades, and can start atom on the freshly installed system.

**Comment by simeon-walker** [comment]
I have just seen this issue in Ubuntu 15.04. I too was using the webupd8 package but this package/OS combo was working last week. Since another reply suggested the official package didn't work either I decided to remove recent OS updates (not security updates) to see if that made any difference.

Using synaptic I remove the vivid-updates repo and downgraded all packages back to those delivered with 15.04. Many of these were related to systemd and udev. I rebooted and Atom now starts.

So far I don't know exactly which package caused the problem as a partial downgrade of systemd stuff could easily leave me with an unbootable system. I fresh install in a VM and then a one by one upgrade of packages might find the problem.

**Comment by jurgenhaas** [comment]
Looks like this is a problem with Chrome/Chromium. The reason I'm saying this is that I wasn't able to install new extensions and completely re-installed Chrome. I started it from the terminal and still can't install any extension. On the console I see a lot of these messages:

```
LaunchProcess: failed to execvp:
/proc/self/exe
```

and also this:

```
[8915:8950:0514/095423:ERROR:channel.cc(299)] RawChannel read error (connection broken)
```

Those are the same errors that I see with atom and hence I guess there must be a relation between the two. Will investigate further.

**Comment by jurgenhaas** [comment]
Looks like reproducing this on new installs isn't possible or at least very hard. Is there any thing else we could do to dig deeper with logs or debugging information that I'd be willing to provide if I got guidance on how to produce any of them?

**Comment by w1748587889** [comment]
environment:ubuntu14.10 64bits(zh_cn) 4G RAM  with all updates, Intel Core i5-3230 2.6GHz, Intel Ivybridge Mobile.
I'm facing the same issue some time,too.

**Comment by WillFrew** [comment]
Just to add to my 2c, I get this problem every so often on Arch Linux, having installed via the AUR.
It seems that I get this issue after almost every restart but after running `killall atom`, atom will happily start and is fine thereafter.

**Comment by jurgenhaas** [comment]
No luck here. Just removed everything from my pc related to Atom and downloaded the 1.0 deb from atom.io, installed it and tried every trick mentioned in this issue. Nothing helps to get started with Atom again. What a shame, I'm missing this great tool a lot.

**Comment by sl45sms** [comment]
+1
same issue for me... 

atom -v
1.0.0
atom -t
[18146:0629/140811:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
LaunchProcess: failed to execvp:
/proc/self/exe
[18146:0629/140812:ERROR:nss_util.cc(819)] After loading Root Certs, loaded==false: NSS error code: -8018
LaunchProcess: failed to execvp:
/proc/self/exe
[18146:0629/140812:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1

uname
3.5.0-18-generic #29-Ubuntu SMP Thu Oct 25 07:26:14 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/issue
Ubuntu 12.04.5 LTS \n \l

**Comment by michaelgibson** [comment]
+1

atom -v
1.0.2

atom -t
[23169:0723/144624:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
LaunchProcess: failed to execvp:
/proc/self/exe
LaunchProcess: failed to execvp:
/proc/self/exe
[23169:0723/144624:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1

cat /etc/issue
Linux Mint 15 Olivia

uname -a
 3.8.0-19-generic #29-Ubuntu SMP Wed Apr 17 18:16:28 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by theGreatHeisenberg** [comment]
I too faced the similar issue. Then I remembered I had upgraded my kernel for some device driver sorcery. Just to check, I rebooted with older kernel and it worked. 

my conclusion - upgrading to newer kernel version caused chromium to stop and Atom doesn't work because of that.

**Comment by bulak** [comment]
I had the same issue. Solved it by killing some unresponsive processes from Chrome. Specifically:
```
ps -A | grep Chrome
21511 ?        00:06:49 Chrome_ProcessL
```
After killing the process with `-KILL` option, I was able to fire up atom (both in normal and safe mode).

**Comment by lyhongpon** [comment]
It works after I change owner of folder atom located at /usr/share/atom. Try it.

**Comment by fabian-breuninger** [comment]
for me it works after I clean the ~/.atom directory

**Comment by jingpengwu** [comment]
+1

I tried both atom and atom-beta. remove ~/.atom; change owner of /usr/share/atom-beta; 

I don't see anything using this:
    ps -A | grep Chrome

**Comment by nengxu** [comment]
After upgrading from Atom 1.8.0, none of the newer versions, up to 1.9.8, worked on Lubuntu 16.04

Remove ~/.atom, and ~/config/Atom. No effect.

Even remove the atom package and reinstall, no use. I'm using the webupd8team PPA.

**Comment by jingpengwu** [comment]
Just find that the little black bar could be dragged and extended to a full screen! My atom works fine now.

**Comment by nengxu** [comment]
I just installed Microsoft Visual Studio Code on the same Ubuntu VM. And it showed the same kind of result: an black window. So I think that it may be related to Chrome on Ubuntu.

**Comment by mfrederickson** [comment]
I was having a similar issue-- it used to launch, updated atom, then it no longer launched (except from the terminal).  All I had to do to fix it was remove the old "personalized" desktop file so it would use the one supplied with the newer version.

```
rm ~/.local/share/applications/atom.desktop
```
Then I removed the old icon that was locked to my launch bar, ran it from unity's search, locked it back to my bar and it is launching just fine now.

**Comment by canercidam** [comment]
I had the same problem for no obvious reason at all. After reinstalling via .deb package, it didn't work again.

So I navigated to ~/.config and did
```
sudo rm -r Atom
```
and the problem is gone.

**Comment by nengxu** [comment]
@canercidam This was one of the first things I tried. Did not work.

**Comment by Keerti-Gautam** [comment]
I installed atom today and it suddenly stopped responding after which I had to force close it. It hasn't been opening since then. Shows no error message, the editor loads and then suddenly disappears. Can someone help? Using Ubuntu 16.04.2 LTS

**Comment by rsese** [comment]
@Keerti-Gautam - can you open a new issue and completely fill out the issue template so we can take a look?  In particular, there have been a few recently identified issues with the GitHub package:

https://github.com/atom/atom/issues/14806#issuecomment-309077338

So one quick test I'd suggest is to temporarily disable the GitHub package and see if that helps.

**Comment by atongsa** [comment]
- ls ~/.atom

- vim config.cson

- comment the line that i added 

- it works for me

**Comment by lincoln96** [comment]
Every time I open Atom I need to press F11 to see the interface
