### ISSUE TITLE
Blocking file system access 

### ISSUE THREAD

**Issue by jarkonik** [atom/atom#6318]
I'm using atom editor to edit files on remote file systems using sshfs and i deal with frequent hangs and crashes of atom due to network performance - I suspect it happens due to synchronous file system calls. Would it be possible to introduce some improvements to that( asynchronous calls or something?) ? I can try contributing if anyone thinks it is possible.

**Comment by mark-hahn** [comment]
> I suspect it happens due to synchronous file system calls.

That doesn't seem right.  The file operations are only synchronous with
respect to the JS code.  The file operations and the net IO happen in the
background in all cases.
