### ISSUE TITLE
Installing apm......   <===== it seems to be frozen been like that for over an hour now

### ISSUE THREAD

**Issue by cre84j** [atom/atom#6319]
gregory@gregory-UX303LA:~$ npm -v
2.7.5
gregory@gregory-UX303LA:~$ cd atom
gregory@gregory-UX303LA:~/atom$ script/build
Node: v0.10.25
npm: v2.7.5
Installing build modules...
Installing apm....

Something tells me this isn't the first time this has happened. I don't know if it is normal. There is nothing there telling me that there is anything happening at all even the curser has stoped flickering.
Can anybody tell me whats happening? Does anybody know what the nest step is from here?
I'm ok to sit and wait I can put a movie on or do some reading on atom but would like to know if this is going ok.

**Comment by cre84j** [comment]
Exited that builid it just wasn't happening. uninstalled nodejs. Starting over again.
Would like to know what was happening there and why. Can anyone comment on this please?

Decided to try to bu

**Comment by cre84j** [comment]
Build node from source it's a newer version. 0.12.2

**Comment by kevinsawicki** [comment]
You can run `script/build --no-quiet` to get more output.

The first build does download lots of libraries and packages so it may take awhile, subsequent rebuilds should be much quicker, closing this out.
