### ISSUE TITLE
Atom-0.190.0 won't start

### ISSUE THREAD

**Issue by TheChymera** [atom/atom#6322]
Hi, in response to issue #6296 I updatd to atom 0.190.0, which however, will not launch. How can I debug this?

**Comment by kevinsawicki** [comment]
Are you running `atom` from the terminal?

First check that there are no atom processes running and then run `atom -f` at the command line and see if any errors are logged to the terminal.

**Comment by piranna** [comment]
Thanks @kevinsawicki, that worked for me, problem was I had an old Atom instance running :-)

**Comment by JinLingChristopher** [comment]
I met the same problem today suddenly ,but i dont know why.the problem show me like this 
![qq 20150412212744](https://cloud.githubusercontent.com/assets/7138436/7105749/e462b1e4-e15a-11e4-92d5-e88f475ad0e8.png)
I dont know how to solve it ,all the processing was killed before run the atom -f.
please help me .!

**Comment by TheChymera** [comment]
No idea what the issue was, I solved it by updating to the live build. I will try to keep the `atom -f` tip on hand, though.

**Comment by kevinsawicki** [comment]
Closing this out, please comment if you are still seeing it in Atom 1.0.3+ and if `atom -f` should any errors when the Atom launches but does not show up.
