### ISSUE TITLE
Project.getRepositoryForPath(path)?

### ISSUE THREAD

**Issue by edrex** [atom/atom#6324]
Should the Project API, now that it can return multiple repositories (#3691), have a convenience function to return the repository for a given path?

Use case is https://github.com/diiq/atomatigit/issues/75, which needs to figure out which repo to target based on current tab.

**Comment by izuzak** [comment]
cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
@edrex I think that [`Project::repositoryForDirectory`](https://atom.io/docs/api/v0.190.0/Project#instance-repositoryForDirectory) should work for your use case. If you have a file path, you'll need to instantiate a `Directory` with that file path. The `Directory` class will be public in the next release of Atom. Then you'll be able to do this:

```coffee
{Directory} = require "atom"

atom.project.repositoryForDirectory(new Directory(myPath)).then (repository) ->
  console.log "The repository", repository
```

Until then, you can get a `Directory` instance using [`Project::getDirectories`](https://atom.io/docs/api/v0.190.0/Project#instance-getDirectories):

```coffee
myDirectory = null
for directory in atom.project.getDirectories()
  if directory.contains(myPath)
    myDirectory = directory
    break

atom.project.repositoryForDirectory(myDirectory).then (repository) ->
  console.log "The repository", repository
```

**Comment by edrex** [comment]
Thanks @izuzak and @maxbrunsfeld for your support. 

I guess I missed Project::repositoryForDirectory, seems straightforward enough.

I don't envy you your tracker with &gt;1000 open issues.
