### ISSUE TITLE
Have a way to find which plugin is causing problems.

### ISSUE THREAD

**Issue by DiThi** [atom/atom#6325]
Enter key doesn't work in editor after upgrading to 0.190, and I found it's the "refactor" package. Sometimes it hasn't been this easy, esp with performance problems.

I suggest to add a way to temporally disable packages below a line in the package list, to move it "git bisect" style until the cause is found. I don't want to click many "disable" buttons, having to remember later which ones I already had disabled.

**Comment by 50Wliu** [comment]
There's already an issue tracking this, please see #2357.
@mark-hahn has already created a package called [package-cop](https://atom.io/packages/package-cop) that should serve your needs until this is implemented into Atom.
