### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'D:\GitRepos\Reference-Web-App\gulp\tasks\clean.tasks.js'

### ISSUE THREAD

**Issue by tgoyer** [atom/atom#6326]
[Enter steps to reproduce below:]

1. Open a file from the directory tree view.
2. Delete the file while the file is open in the editor.

**Atom Version**: 0.190.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'D:\GitRepos\Reference-Web-App\gulp\tasks\clean.tasks.js'

```
At events.js:141

Error: ENOENT: no such file or directory, open 'D:\GitRepos\Reference-Web-App\gulp\tasks\clean.tasks.js'
  at Error (native)

```

### Commands

```
  5x -0:32.2 core:move-down (atom-text-editor.editor)
  4x -0:26.9 core:move-up (atom-text-editor.editor)
     -0:25.2 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -0:24.3 editor:newline (atom-text-editor.editor)
     -0:24.0 core:move-up (atom-text-editor.editor)
  3x -0:20.2 core:backspace (atom-text-editor.editor)
     -0:17.2 editor:move-to-end-of-screen-line (atom-text-editor.editor)
     -0:15.8 core:move-right (atom-text-editor.editor)
     -0:15.6 core:move-down (atom-text-editor.editor)
     -0:15.3 core:move-up (atom-text-editor.editor)
     -0:14.4 editor:newline (atom-text-editor.editor)
  2x -0:11.9 core:move-down (atom-text-editor.editor)
  2x -0:11.2 core:move-up (atom-text-editor.editor)
  4x -0:10.5 core:move-right (atom-text-editor.editor)
  3x -0:08.8 core:move-down (atom-text-editor.editor)
     -0:08.2 core:move-up (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs-styleguide-snippets, v0.6.0
editorconfig, v0.3.3
linter, v0.12.0
linter-jshint, v0.1.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Thanks a lot for the reproduction steps!  Most ENOENT issues we get now don't come with any repro steps, so this helps a lot :smile:.

**Comment by tgoyer** [comment]
You're welcome.

On a side note, I also noticed that I get that error during start up.  It looks like Atom tries to re-open files that were opened when Atom was closed.  If those files were deleted,  Atom still tries to open them and throws that error.

1. Open file in Atom
2. Close Atom
3. Delete file
4. Reopen Atom 
5. When Atom tries to re-open file, it throws an exception.
