### ISSUE TITLE
Search with a new thing should clear the replace box

### ISSUE THREAD

**Issue by eddiemonge** [atom/atom#6331]
I search for something and the old replace value is still there making it confusing and harder to search. The replace box should get cleared out or have an option to specify that.

**Comment by envygeeks** [comment]
It's pretty much standard practice in most IDE's to leave it there.

**Comment by mark-hahn** [comment]
> It's pretty much standard practice in most IDE's to leave it there.

In other IDEs it doesn't make the results hard to read.  It is very
annoying.  In general the Atom find/replace is trying too hard to be
concise.  Having one button do different things depending on the phase of
the moon is a PITA.  What is wrong with a lot of buttons?

**Comment by benogle** [comment]
@eddiemonge is this in the project find? Buffer find? Or both?

I bump up against this too with the project find replace box.

> Having one button do different things depending on the phase of the moon is a PITA.

I'm not following, which button is this?

**Comment by mark-hahn** [comment]
> I'm not following, which button is this?

Sorry, I meant the enter key.

**Comment by eddiemonge** [comment]
project find box. I do a new search in all files and the results have the previous replace and shows in the results making it hard to read without deleting the contents (which i do almost 98% of the time for new searches)

**Comment by thedaniel** [comment]
I also regularly find this annoying in 'find in project' - Leaving it in the input makes sense, but there are definitely readability issues with the side-by-side display in results.

**Comment by andya9** [comment]
:+1:  for clearing both find and replace; 
if we want to search again using the same pattern, we already have history with arrow keys

**Comment by eddiemonge** [comment]
This isn't stale. Its an enhancement that is waiting for implementation. Please reopen.

**Comment by 50Wliu** [comment]
Sorry @eddiemonge - there was a bug with probot where some issues targeted in the initial pass wouldn't get the warning comment before being closed.  However, it looks like this is a find-and-replace issue, which means that it should instead be opened on the [atom/find-and-replace](https://github.com/atom/find-and-replace) repository if an issue doesn't already exist.
