### ISSUE TITLE
Error: EEXIST on launch from shell as non-root

### ISSUE THREAD

**Issue by mhoc** [atom/atom#6334]
OSX 10.10.3
Atom 0.190.0

When launching atom as a non-root user from the shell (for example: `atom app.js`), Atom crashes with an uncaught error `EEXIST: file already exists, mkdir '/usr/local/bin/atom'`. A picture of the full stacktrace is included below.

![Error Image](http://i.imgur.com/3qcihxe.png)

Atom works fine if launched any other way. It also works fine if launched from the shell as a root user. `atom -f` only outputs the error included in the picture above and nothing else. This problem persists between Atom installs and full removals of my local atom configuration. 

My guess is there's a misconfigured permission somewhere which is obviously specific to my system, and I'd love some help tracking it down. Thanks!

**Comment by izuzak** [comment]
Sorry for the delay in getting back to you on this, @mhoc. Just wondering if you're still seeing this or if you were able to figure things out?

Seems like that error is being thrown from [here](https://github.com/atom/atom/blob/6f5e7cdd5c6dfd10e5d8ce740e9587f90c33fd2f/src/config.coffee#L764).

**Comment by mhoc** [comment]
Unfortunately I wasn't able to figure out and I've since then did a clean install of OSX and am not seeing the problem on the new install. It was probably something weird with my configuration so I'm fine with closing this as the problem appears to be pretty unique.

**Comment by 50Wliu** [comment]
Glad to see that you resolved it :smile:.
