### ISSUE TITLE
Links do not work in v189+

### ISSUE THREAD

**Issue by jravetch** [atom/atom#6335]
After upgrading to Atom 189, links no longer open a new tab in Chrome.  For example, clicking on any of the release notes links does nothing.  Upgrading to 190 didn't solve this issue.

**Comment by mnquintana** [comment]
What OS? Do you experience this issue in [safe mode](https://atom.io/docs/v0.190.0/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) (`atom --safe`)?

**Comment by jravetch** [comment]
Ubuntu 14.10 x64.  Safe mode is the same.

**Comment by paulcbetts** [comment]
We've seen this in the Slack app, only with Chrome - switching your default browser to IE and back will usually fix it

**Comment by jravetch** [comment]
@paulcbetts Haha, no IE in Ubuntu ;)  Tried switching the default browser to Firefox then back to Chrome, now any link I click in Atom opens the Ubuntu Tour App in Firefox.  Curiouser and curiouser...

**Comment by jravetch** [comment]
@mnquintana @paulcbetts I made sure that the system default browser was set to Chrome in Gnome System Panel, now nothing happens when I clink on any link in Atom.

**Comment by jravetch** [comment]
Just upgraded to 191 and now links work.  My system chrome is also upgraded to 42.0.2311.90 (64-bit)

**Comment by Wikunia** [comment]
I am using v0.199 on ArchLinux and have the same problem. My standard browser is Chrome v. 42.0.2311.152

**Comment by varemenos** [comment]
This happens in v0.199, v0.200 and v0.201 on Arch. Chrome version:
> Version 43.0.2357.65 (64-bit)

**Comment by kankaristo** [comment]
This also started happening for me, around v0.189. The links still don't work on v0.204.

I'm running Ubuntu 14.04.2 LTS and Chromium 41.0.2272.76 (64-bit).

**Comment by kankaristo** [comment]
The links are working in Chrome 43.0.2357.81, but not in Chromium 41.0.2272.76.

I guess I'll switch to Chrome...

**Comment by nikmartin** [comment]
I'm running Chromium on Arch Linux and links do not work in Atom 0.201-6adbdee

**Comment by kankaristo** [comment]
Huh, on my work computer with the *exact* same version of Chromium (41.0.2272.76) and the same version of Ubuntu (14.04.2 LTS), the links are working.

This is on Atom 0.208.0.

I'm using [sync-settings](https://atom.io/packages/sync-settings), so Atom's config and installed packages should be pretty much the same, but I'll take a closer look later today.

The only difference I can think of is that my work computer only has Chromium, but my home computer (where the links are broken in Chromium, but not Chrome) has both Chrome and Chromium installed.

**Comment by sztosz** [comment]
Arch Linux Chromium Version 43.0.2357.125 (64-bit), latest Atom, process spawns, but website does not open. Works ok in Firefox

**Comment by varemenos** [comment]
I'm now on Arch Linux with Atom v1 and Chrome 43.0.2357.130 (64-bit) and it still occurs.
Don't have Chromium installed

**Comment by varemenos** [comment]
Can we please do something about this issue?

I don't see how anyone can consider Atom Editor stable when some of it's users can't click any anchor tags even in `--safe` mode

**Comment by varemenos** [comment]
Can we please do something about this issue?

I don't see how anyone can consider Atom Editor stable when some of it's users can't click any anchor tags even in --safe mode

**Comment by 50Wliu** [comment]
> Can we please do something about this issue?

Please see #7877 which will fix this.

**Comment by rhinoceraptor** [comment]
I just built the tj-electron-29 branch, it does fix the URL bug under Arch Linux and Chromium 43.0.2357.134.
