### ISSUE TITLE
Issues with Atom on Windows tablet

### ISSUE THREAD

**Issue by TMiguelT** [atom/atom#6336]
Sometimes I want to use atom on my Windows tablet, and I've noticed two annoying issues.

Firstly, whenever you click anywhere on the editor, it opens the software keyboard. This would be fine, except that it does so even if you have a hardware/bluetooth keyboard attached. I'm not sure if Windows provides a way to tell if there is a physical keyboard attached, but if not, could you provide an option to not open the software keyboard ever? 

The other issue is with scrolling. With apps designed for touch screens, you can drag down from the top of the editor and it scrolls down. However this doesn't seem to work with atom, and you have to grab the very thin scrollbar on the side on order to scroll down. Would it be possible to allow drag-scrolling?

Thanks so much, I love the editor!

**Comment by batjko** [comment]
I think this may be a Windows issue, rather than atom.
I know that on touch-enabled screens, Windows automatically opens the on-screen keyboard if you tap into an editable field of some kind.

Maybe not always, but way too often. And I'm not sure where, but there must be a setting somewhere to turn that off in Windows.


I'd recommend opening a second issue for the scrolling thing, so it can be dealt with properly.

**Comment by paulcbetts** [comment]
> Firstly, whenever you click anywhere on the editor, it opens the software keyboard. This would be fine, except that it does so even if you have a hardware/bluetooth keyboard attached.

Can you file an Atom Shell bug for this and link it here?

**Comment by TMiguelT** [comment]
It *may* be default behaviour to open the software keyboard whenever you click on an editor field, but it certainly can be disabled because notepad++ doesn't ever open it, which honestly I prefer because I always use my bluetooth keyboard. I suspect the windows API will provide some way of disabling the keyboard for an input/app. I also don't necessarily want to disable the keyboard OS-wide because I sometimes use the touch keyboard for other apps. Also this seems more of an atom issue than atom-shell, because other atom-shell apps may want to do different things with the keyboard, no?

**Comment by paulcbetts** [comment]
>  Also this seems more of an atom issue than atom-shell, because other atom-shell apps may want to do different things with the keyboard, no?

No because the Slack Windows app has this issue too, input boxes incorrectly pop up the SIP keyboard when they shouldn't

**Comment by TMiguelT** [comment]
Okay if I do that, is the scrolling issue an atom or atom-shell bug? I haven't used any other atom-shell apps to know if you can drag-scroll on them or if it's just an atom issue.

**Comment by paulcbetts** [comment]
> Okay if I do that, is the scrolling issue an atom or atom-shell bug? 

Could be either? I'm not sure about that one, would have to do more investigation

**Comment by russlescai** [comment]
FYI - I have a basic touch-scrolling work around you can put in your init.coffee. It works on my Surface Pro 2.

You can find it here: https://github.com/atom/atom/issues/6724

As for the on screen keyboard issue, I don't get it using mouse/keyboard, just when I touch the screen.  

Part of implementing touch events would include preventing bubbling up of some events to enable touch behaviour and navigation.

**Comment by russlescai** [comment]
There is now a package to handle touch events within Atom https://atom.io/packages/atom-touch-events

It currently supports swipe events, and allows scrolling by swiping up and down.

I plan to implement tap and pinch gestures to zoom and select correctly.

Hopefully you find it useful.

**Comment by russlescai** [comment]
The https://atom.io/packages/atom-touch-events package now supports pinch to zoom gestures, and handles tap events by setting the cursor instead of opening the soft keyboard.

**Comment by adamncasey** [comment]
Is it possible to get the atom-touch-events functionality added to the default editor? On touch screen Windows laptops the default behaviour is pretty unintuitive.

**Comment by damieng** [comment]
The software keyboard issue has been resolved.

The atom-touch-events package works well for people that need it. We wouldn't include functionality at this time while it is only applicable to a small subset of users - namely those on Windows with touch-enabled screens.
