### ISSUE TITLE
Save and Save As buttons on Menu - Doesn't work

### ISSUE THREAD

**Issue by vmahadev** [atom/atom#6337]
Hi

I have downloaded Windows (8.1) version of Atom from the link provided on the home page.

After installation and adding some of the packages In the first run when I tried to save the file using menu "File/Save" as well as "File/Save As" did not work but CTRL+S worked.

Regards
Dev

**Comment by vmahadev** [comment]
Hi

To reproduce this bug follow these steps

1. Download the build from the home page link.
2. Install
3. Run the App 
4. Use configuration to add some packages
5. Edit a file try saving it using Save and Save As 
6. It doesn't work but when you hit CTRL+S it works

After restarting both menu options works fine

Regards
Dev

**Comment by mnquintana** [comment]
Can you post a list of your installed packages (e.g. the output of `apm list --installed`)? Do you experience this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) (`atom --safe`)?

**Comment by vmahadev** [comment]
![packages](https://cloud.githubusercontent.com/assets/1321782/7111497/1be93f42-e1de-11e4-9f63-72863af57230.png)
![apmcmdresult](https://cloud.githubusercontent.com/assets/1321782/7111531/65b37f20-e1de-11e4-9f34-db96fa715d41.png)

**Comment by vmahadev** [comment]
I experienced it only the first time hence reported the bug 
(hence no point in checking in safe mode) If you want me to sure I can check because it is working in normal mode as I have said in my report
****** After restarting both menu options works fine ******

**Comment by lee-dohm** [comment]
Since this hasn't gotten any other reports in over a year, I'm going to close it. Please let us know if anyone runs into this!
