### ISSUE TITLE
Copy and paste

### ISSUE THREAD

**Issue by mohamed-moanis** [atom/atom#6344]
When ever I make a paste from chrome or any other text editor, atom crashes.
Also when making a copy from it to chrome, the page in chrome freezes.
I am using atom on Ubuntu 14

**Comment by izuzak** [comment]
I'm guessing you're on Atom 0.189.0 version (or a previous version)? Try updating to version 0.190.0 -- this sounds like https://github.com/atom/atom/issues/6221, which should be fixed in 0.190.0. Let us know if it doesn't help.
