### ISSUE TITLE
ATOM_HOME on Windows should follow Windows conventions, not Linux conventions.

### ISSUE THREAD

**Issue by Zoltu** [atom/atom#6345]
In the Linux world, the convention is to put user-specific application configuration in `~/.folder` or `~/.file`.  In the Windows world, this is not the case.  User-specific settings have a well defined place they should go which is `~/AppData/(Local|Roaming|LocalLow)`.

Details on exactly which of the three folders to use can be found here: http://windows.microsoft.com/en-us/windows-8/what-appdata-folder

Additional information about how to access the different paths can be found here (a bit old, but still valuable):
http://blogs.msdn.com/b/patricka/archive/2010/03/18/where-should-i-store-my-data-and-configuration-files-if-i-target-multiple-os-versions.aspx

Reasoning: `~/.(file|folder)` is not hidden on Windows and it is not the place an experienced Windows developer would look for user settings.  It also pollutes the user directory which is meant to be the place for user documents and files that they interact with directly (word document, photos, videos, downloads, etc.).

**Comment by damieng** [comment]
I'm not sure I agree with this - it is very common for developer tools to place settings and caches directly in the home folder with a dot prefix these days, here are some examples from my current machine:

- .aws (Amazon AWS command-line tools)
- .dnx (Latest version of .NET framework)
- .docker (Docker machine management system)
- .IntelliJidea15 (JetBrains Intelli-J IDE)
- .nuget (Microsoft .NET packaging system)
- .ssh (SSH keys used by various git tools etc)

**Comment by damieng** [comment]
There was also a previous discussion about this here https://github.com/atom/atom/pull/6346 which was closed.

**Comment by lee-dohm** [comment]
Thanks for pointing this out @damieng.

While we're not planning on making any changes of this kind for v1.x, we are tracking these kinds of things as a potential change for a later major release here: https://github.com/atom/atom/issues/8281. You may want to subscribe to that issue for updates.
