### ISSUE TITLE
Ubuntu 14.04 , Atom 0.190.0 don't support chinese.

### ISSUE THREAD

**Issue by CCCzKen** [atom/atom#6354]
I install many versions, when I try the version more than 0.187.0 ,it can't display chinese normal. I have read former Issues, many people say I can't try to change the font-family , but it doesn't work.

**Comment by CCCzKen** [comment]
![1](https://cloud.githubusercontent.com/assets/7587093/7111069/853bcd98-e1ed-11e4-8253-cb1f9ba24c75.png)

The same situation as other developers.

**Comment by mnquintana** [comment]
Duplicate of #6214

**Comment by CCCzKen** [comment]
OK，Thank you . When I try `Droid Sans Mono, Droid Sans Fallback` Chinese display normal .

**Comment by zacchen** [comment]
It's very helpful,i just solved my problem too.Thanks very much.

**Comment by AtekiRyu** [comment]
helpful ,Thank you very much

**Comment by Jess-Yuan** [comment]
Thank you, It works!!!
