### ISSUE TITLE
whitespace stays when the cursor is at it upon saving

### ISSUE THREAD

**Issue by mrtnbroder** [atom/atom#6357]
Upon saving, any whitespace before the cursor should get removed (if given option is activated). However, this is not the case currently.

E.g. it should work like on Sublime (upon save):

http://inft.ly/35tktDb

**Comment by 50Wliu** [comment]
This can be configured in the whitespace package.
Open Settings View (<kbd>Ctrl+,</kbd> or <kbd>Cmd+,</kbd>), navigate to Packages, then to the Whitespace package, and finally change "Ignore whitespace on current line" to false.
