### ISSUE TITLE
Outdenting should keep the same lines selected

### ISSUE THREAD

**Issue by 1j01** [atom/atom#6362]
Unindenting/outdenting/dedenting a block of code can leave you with a selection without one of the lines that you outdented, so continuing to outdent leaves that line behind.

![doublebugger](https://cloud.githubusercontent.com/assets/3630663/7127253/5f86888c-e20f-11e4-8dff-18dce68689c6.gif)
~~_Also demonstrated in this gif: [gutter highlight stays behind](https://github.com/atom/atom/issues/6363)_~~

Instead, it should keep part of the selection on that line. Actually, I think it should select the entire line.
If it kept only a single character selected it would be weird especially if using spaces, and if it kept only the leading whitespace selected, it would still have the problem if you dedent all the way.

_Did I miss any keywords? unindent unindented dedented dedent indentation_

**Comment by 50Wliu** [comment]
I can confirm on latest master.

**Comment by 1j01** [comment]
This is still a problem 😕
