### ISSUE TITLE
Gutter highlight stays behind

### ISSUE THREAD

**Issue by 1j01** [atom/atom#6363]
![doublebugger](https://cloud.githubusercontent.com/assets/3630663/7127253/5f86888c-e20f-11e4-8dff-18dce68689c6.gif)
*Also demonstrated in this gif: https://github.com/atom/atom/issues/6362*

To reproduce:
* Unindent some lines
* Move cursor down
* Undo
* Move cursor down

**Comment by 50Wliu** [comment]
I can't seem to reproduce this.  What Atom version are you using?  Can you reproduce this in safe mode (`atom --safe`)?

**Comment by 1j01** [comment]
On Windows 8.1 in safe mode, I'm able to reproduce this every time by undoing or redoing an indent or dedent of several lines from a state where there is no selection and then moving the cursor in any direction.

Wait, I'm on version 0.182 for some reason, and it won't update.

At any rate, I see some things that could be related in the release notes:
* Fixed a regression where the cursor position was not being restored after undo in some cases
* Fixed issues adding selections above and below in the presence of hard tabs or soft-wrapped lines.
* Fixed issues soft-wrapping lines that contained tabs in their leading whitespace.

And since you can't reproduce this, I'll presume that it's fixed.
