### ISSUE TITLE
Soft Wrap Hanging Indent not working

### ISSUE THREAD

**Issue by LandonSchropp** [atom/atom#6369]
I'm trying to enable the `softWrapHangingIndent` setting. It was added in #6003, but it doesn't seem to be working for me. Here's what my wrapping settings look like:

![screen shot 2015-04-13 at 9 14 36 pm](https://cloud.githubusercontent.com/assets/361591/7130273/1f362bf8-e222-11e4-95e0-67a64e1f8e70.png)

With these settings enabled, here's some HTML I pulled from Hipster Ipsum:

![screen shot 2015-04-13 at 9 13 52 pm](https://cloud.githubusercontent.com/assets/361591/7130276/2d8ec12e-e222-11e4-814b-fe9757932ef2.png)

This is what I expect it to look like:

![screen shot 2015-04-13 at 9 16 35 pm](https://cloud.githubusercontent.com/assets/361591/7130287/69f1e9ca-e222-11e4-9d13-ee785e640834.png)

Am I missing something? Thanks in advance!

**Comment by izuzak** [comment]
@LandonSchropp That works for me:

![screen shot 2015-04-14 at 10 55 58](https://cloud.githubusercontent.com/assets/38924/7133563/e2410e20-e294-11e4-95f8-0cd770d9129a.png)

Can you reliably reproduce this? If so, can you post the exact instructions which reproduce this for you? Also, which version of Atom and OS are you using, and can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by LandonSchropp** [comment]
I was able to reproduce this on 0.182 in safe mode on OS X 10.10.2, but I installed the update and the problem seems to be fixed. Thanks for the help!
