### ISSUE TITLE
Link with parentheses are not correctly rendered in Markdown preview

### ISSUE THREAD

**Issue by MGaetan89** [atom/atom#6371]
In the Markdown preview pane, the link containing parentheses are not correctly rendered.

Here is a screenshot of the preview in Atom:
![Atom preview](https://cloud.githubusercontent.com/assets/1009664/7131556/ffe2fd58-e280-11e4-86d9-d6929778b934.png)

And here is a screenshot of the preview on GitHub:
![capture du 2015-04-14 08 33 03](https://cloud.githubusercontent.com/assets/1009664/7131575/2692c0be-e281-11e4-9059-6aaae29859ad.png)

Finally, the Markdown I used in both cases:

```markdown
You need to override the [`onCreate(Bundle)`](http://developer.android.com/reference/android/app/Activity.html#onCreate(android.os.Bundle)) method on your [`Activity`](http://developer.android.com/reference/android/app/Activity.html).
```

I am using Atom 0.190 .0 on Ubuntu 14.04.

**Comment by izuzak** [comment]
This issue was moved to atom/markdown-preview#242
