### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/arve/Projects/gradlehub/Dockerfile'

### ISSUE THREAD

**Issue by aknuds1** [atom/atom#6372]
[Enter steps to reproduce below:]

1. Invoke atom for non-existent file: `atom Dockerfile`

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/arve/Projects/gradlehub/Dockerfile'

```
At events.js:141

Error: ENOENT: no such file or directory, open '/Users/arve/Projects/gradlehub/Dockerfile'
  at Error (native)

```

### Commands

```
     -0:00.5 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "preferredLineLength": 110,
    "tabLength": 4,
    "softWrapAtPreferredLineLength": true,
    "invisibles": {},
    "fontSize": 15
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v0.7.0
atom-lint, v0.20.1
auto-reveal-in-sidebar, v0.4.0
coffee-refactor, v0.6.2
editorconfig, v0.3.3
language-clojure, v0.14.0
language-docker, v1.1.3
language-gradle, v0.0.3
language-haskell, v1.0.0
language-scala, v1.1.0
refactor, v0.4.1
tabs-to-spaces, v0.9.2

# Dev
No dev packages
```

**Comment by halhenke** [comment]
Yeah I get this when re-opening a project that has a tab open associated with a file that no longer exists.

**Comment by 50Wliu** [comment]
I can't reproduce this :frowning:.
My steps on Ubuntu 14.10 and the latest Atom master (in `--safe` mode):
1. Make sure `nonexistent-file` doesn't exist
2. `atom --safe nonexistent-file`
3. Expected and actual: Atom opens up a blank file called `nonexistent-file`

That said, however, I'm not trying to disqualify your bug report.  We've had a bunch of these errors but no one from the Atom team has been able to reproduce them yet.

**Comment by aknuds1** [comment]
It seems I can't reproduce when `--safe` is enabled either. Is there any way to tell which plugin is eventually involved?

**Comment by 50Wliu** [comment]
You can try using @mark-hahn's [package-cop](atom.io/packages/package-cop) package.

**Comment by aknuds1** [comment]
@50Wliu Ugh, even package-cop fails due to a bug (already reported, though) :(

**Comment by halhenke** [comment]
@50Wliu I cant reproduce it with that method but i can reproduce it by re-opening a project that references a deleted file

1 Open a new tab in a window associated with a saved project
2 Save the contents as a new file
3 Leave the tab open & close the window/project (you can leave Atom itself running)
4 Delete the file (its importnant that you close the window/project first - otherwise Atom keeps track of the files relocation to the Trash).
5 Reopen the project. You should have errors about the file being missing.

**Comment by 50Wliu** [comment]
@halhenke please see #6210 then.
