### ISSUE TITLE
Add support for specifying human-readable command labels

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#6373]
Refs https://github.com/atom/command-palette/issues/36#issuecomment-92618828

Currently, there is no way to specify a human-readable label for a command – when you add a command, you can only specify the command name (/identifier), and Atom will ["humanize" this name](https://github.com/atom/atom/blob/master/src/command-registry.coffee#L153) (in the Command Palette for instance), but you can't specify a different human-readable name. It would be extremely useful to be able to specify a human-readable name when creating a command.

We already define `displayName` [here](https://github.com/atom/atom/blob/master/src/command-registry.coffee#L153) – it could just be a matter of allowing this to be specified on command`::add`.

**Comment by 50Wliu** [comment]
This was added in #15383.
