### ISSUE TITLE
CommandRegistry::add docs are missing parameter info

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#6374]
Not sure what we did with our atomdoc here, but [the parameter info for `CommandRegistry::add`](https://atom.io/docs/api/v0.190.0/CommandRegistry#instance-add) has been missing [since at least 0.154.0](https://atom.io/docs/api/v0.154.0/CommandRegistry#instance-add), despite being [in the code comments](https://github.com/atom/atom/blob/v0.190.0/src/command-registry.coffee#L55-L82).

**Comment by benogle** [comment]
This is probably a bug with atomdoc handling the multiple arg sections. Atomdoc [should handle](https://github.com/atom/atomdoc/blob/f416a9030a3dfd1a8d2bd63d934d52f5d0521862/spec/parser-spec.coffee#L446) this case, but apparently it's not.

**Comment by benogle** [comment]
Actually, the issue may be in atom.io in the consumption of the json.

**Comment by benogle** [comment]
I had a PR on atom.io a few months ago fixing this. It should look like this: 

![abd006e2-7b16-11e4-9ef2-b919f0de2ce3](https://cloud.githubusercontent.com/assets/69169/7162942/3e6ddb9e-e34c-11e4-9377-453d7599125a.png)

But nope. Looking into it...

**Comment by mnquintana** [comment]
@benogle It's definitely atomdoc - check out the `CommandRegistry::add` entry in atom-api.json - there is no `arguments` property.
