### ISSUE TITLE
Not able to uninstall on Windows

### ISSUE THREAD

**Issue by philshem** [atom/atom#6378]
I installed Atom with the Windows Installer (not Chocolatey). When I wanted to uninstall, I did the standard Windows thing: Add or Remove Programs, right-click on Atom, click Uninstall.

This was the error message: "An error occurred while trying to uninstall Atom. It may have already been uninstalled."

![uninstall error](https://cloud.githubusercontent.com/assets/4997607/7144890/cd8e5cc2-e2e8-11e4-87de-caf354873d38.png)

To then uninstall I manually deleted files and shortcuts, and also entries in the registry. I also wrote the steps in this [Stackoverflow answer](http://stackoverflow.com/a/29606892/2327328) in case other people have the same issue.

(Windows 8.1 pro)

**Comment by damieng** [comment]
It looks like Atom got removed without using the uninstaller somehow.

One way to ensure cleanup is to install then uninstall again.
