### ISSUE TITLE
Keybinding Copy not working - v 0.191.0 

### ISSUE THREAD

**Issue by Mayccoll** [atom/atom#6382]
Linux Mint 17.1
Atom - 0.191.0

Safe Mode
- works fine.

No safe mode:
- Don't work on new or open files
- Works on Release Notes page
- Paste works fine.

**Comment by mnquintana** [comment]
Can you post a list of your installed packages (e.g. the output of `apm list --installed`)?

**Comment by kevinsawicki** [comment]
Also, can you open the keybinding resolver (`ctrl-.`) and see what it display when you press that keybinding?

**Comment by kevinsawicki** [comment]
Also, was it working properly in 0.190 and broke in 0.191? Thanks!

**Comment by Mayccoll** [comment]
Was working fine in 0.190, broke on 0.191

├── Remote-FTP@0.6.2
├── aligner@0.11.0
├── aligner-css@1.2.0
├── atom-alignment@0.12.0
├── atom-beautify@0.24.0
├── atom-color-highlight@3.0.8
├── atom-csscomb@0.4.0
├── atom-lint@0.20.1
├── autocomplete-css@0.6.0
├── autocomplete-plus@2.9.0
├── autoprefixer@2.2.2
├── color-gutter@0.4.1
├── color-picker@1.6.0
├── colorpicker@0.3.0
├── css-comb@2.0.4
├── css-snippets@0.5.0
├── emmet@2.3.7
├── file-icons@1.5.4
├── git-blame@0.4.0
├── git-control@0.1.9
├── git-history@2.5.0
├── git-plus@4.4.13
├── gulp-control@0.3.3
├── gulp-snippets@0.6.1
├── highlight-selected@0.9.1
├── indent-guide-improved@1.1.1
├── indent-helper@0.1.1
├── language-ansible@0.1.0
├── language-docker@1.1.3
├── language-puppet@0.11.0
├── less-autocompile@1.0.0
├── linter@0.12.0
├── linter-less@0.3.1
├── linter-puppet@0.1.0
├── linter-ruby@0.1.4
├── merge-conflicts@1.3.1
├── minimap@4.7.6
├── monokai@0.14.0
├── oceanic-next@0.1.1
├── oceanic-theme@0.1.2
├── remote-atom@1.2.0
├── resize-indent@0.2.1
├── sort-lines@0.10.0
├── toolbar@0.0.12
├── toolbar-main@0.0.5
├── unity-ui@2.0.5
└── wp-snippets@0.2.9

![atomissue](https://cloud.githubusercontent.com/assets/2009698/7149754/477dd042-e2d7-11e4-9eec-88087fc5c4d5.png)

**Comment by kevinsawicki** [comment]
> Also, can you open the keybinding resolver (ctrl-.) and see what it display when you press that keybinding?

Sorry, I should have said, what does this view show when you press `ctrl-c` not in safe mode?

**Comment by kevinsawicki** [comment]
Also, when not in safe mode, can you open the settings view (`ctrl-,`), go to the Keybindings panel, and type `ctrl-c` in the filter box and take a screenshot of what displays?

Thanks!

**Comment by Mayccoll** [comment]
ohh ok, now i understand how its work.
Next time i can review a better bug report, sorry :)

I found atom-csscomb was the one making the bad behavior.

Report:

- **Safe Mode**

![safe-mode](https://cloud.githubusercontent.com/assets/2009698/7164698/b5f069fa-e367-11e4-92fb-0bfdb975428d.png)

- **No safe mode**

![no-safe](https://cloud.githubusercontent.com/assets/2009698/7164705/c028f856-e367-11e4-827b-9fb392e63281.png)

- **Disable Atom-csscomb WORKS fine**

![csscomb](https://cloud.githubusercontent.com/assets/2009698/7164733/f89367b2-e367-11e4-918c-f3fa53c67313.png)

- Enable atom-csscomb and Adding the keybinding   ```'ctrl-c': 'core:copy'``` to the file ```keymap.cson``` WORKS fine.

- Already notify  to atom-csscomb

Tnks

**Comment by kevinsawicki** [comment]
Did you recently install `atom-csscomb`?

I just wanted to make sure nothing regressed in Atom that changed regarding the keybinding precedences.

**Comment by Mayccoll** [comment]
yes, recently install.

**Comment by kevinsawicki** [comment]
@Mayccoll do you know if you installed `atom-cssbomb` before or after you upgraded to Atom 0.191?

**Comment by Mayccoll** [comment]
I'm not sure because these days install a few plugins and do not remember what they were.

**Comment by kevinsawicki** [comment]
Okay, I'm going to close this out here then since you have an issue opened now on the package repo.
