### ISSUE TITLE
Menus appear on the wrong monitor on Windows

### ISSUE THREAD

**Issue by onovotny** [atom/atom#6387]
![2015-04-15_9-07-19](https://cloud.githubusercontent.com/assets/1427284/7159309/3d6cefc0-e34f-11e4-88e7-3d6487b8e43c.png)

Monitor 1 is the left, 2 is the right. They're both 4k monitors.

**Comment by batjko** [comment]
Dupledidupe.
#3415

**Comment by mnquintana** [comment]
Closing as duplicate – please subscribe to #3415 for updates. Thanks!
