### ISSUE TITLE
Suddenly unable to search certain directories since 191

### ISSUE THREAD

**Issue by bobber205** [atom/atom#6390]
Some folders/projects, even in safe mode,  just search forever and ever. Other folders work just fine since
Started happening with 0.191

What can I provide for more info?
![ingest - atom 2015-04-15 09-29-24](https://cloud.githubusercontent.com/assets/5841107/7163955/eb288d2a-e351-11e4-81ac-fbe6db8323fc.png)

**Comment by kevinsawicki** [comment]
Are any errors displaying in the dev tools? `cmd-alt-I`

**Comment by bobber205** [comment]
ENOENT: no such file or directory, stat '/Users/alexwait/chirpify/ingest/.env' Error: ENOENT: no such file or directory, stat '/Users/alexwait/chirpify/ingest/.env'

**Comment by bobber205** [comment]
Looks like its failing to search symlinked files.

```
lrwxr-xr-x   1 alexwait  staff      26 Dec 18 14:11 .env -> /etc/profile.d/variables.sh
```

**Comment by kevinsawicki** [comment]
Okay, thanks for the details, this looks like a duplicate of https://github.com/atom/scandal/issues/22 will publish a new Atom release very soon with the fix.

**Comment by bobber205** [comment]
Thanks so much!

**Comment by kevinsawicki** [comment]
0.192 is out now
