### ISSUE TITLE
Atom wiping contents of txt files

### ISSUE THREAD

**Issue by Zakkai** [atom/atom#6391]
Other file extensions are fine but when I save and close a .txt file created in Atom, it registers as 0 bytes and is empty when I go to open it.

At first I thought this might be the same issue as https://github.com/atom/atom/issues/3158 , but I don't think it is, because my disk isn't full. However, I am using a diskless client, so it's possible that Atom is being confused by that.

**Comment by maxbrunsfeld** [comment]
@Zakkai is this happening in `--safe` mode? Could you share what packages you have installed (`apm list`)?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/6391#issuecomment-93587467. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
