### ISSUE TITLE
Errors for days (seems like all plugins) on 192

### ISSUE THREAD

**Issue by bobber205** [atom/atom#6393]
![untitled - atom 2015-04-15 11-26-54](https://cloud.githubusercontent.com/assets/5841107/7166379/6098b912-e362-11e4-8233-5265b9c78baf.png)
![developer tools 2015-04-15 11-27-27](https://cloud.githubusercontent.com/assets/5841107/7166386/69241252-e362-11e4-8b19-a59ccef2f49f.png)

Not happening in safe mode.

**Comment by kevinsawicki** [comment]
What does the stack trace show?

**Comment by kevinsawicki** [comment]
Does the `Show Stack Trace` link show the full error?

**Comment by kevinsawicki** [comment]
Did you start Atom with the `--one` or `-1` flags?

**Comment by bobber205** [comment]
Didn't start atom with any flags. 
Seems to have went away after using safe mode.

**Comment by kevinsawicki** [comment]
So did you download 0.192 directly from atom.io before running it? And only on that very first launch is when you saw these errors?

**Comment by kevinsawicki** [comment]
This can now be closed since 1.0 API is out and the flag is no longer applicable that was causing this issue.
