### ISSUE TITLE
Preserve last focused window when reopening Atom w/ no arguments

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#6396]
Repro:
1. Open two atom windows
2. Quit Atom
3. Open Atom w/ no arguments (e.g. from spotlight on OSX)
4. **Expected behavior**: The previously focused Atom window is focused. **Current behavior**: Some other Atom window is focused.

Refs https://github.com/atom/atom/pull/6380#issuecomment-93595925

**Comment by asantos3** [comment]
I don't know if it's a bit too much but how about getting the cursor in the same location?

**Comment by maxbrunsfeld** [comment]
@asantos3 that behavior is actually implemented already. Are you seeing your cursor location get reset when you reload Atom?

**Comment by asantos3** [comment]
Oh, hadn't noticed it until now and didn't see if did before commenting, keep up the awesome work ;)
