### ISSUE TITLE
ShipIt service crashes

### ISSUE THREAD

**Issue by AdilHindistan** [atom/atom#6397]
I have Atom 0.138.0 on Mac OS X 10.10.3
When I launch it, it downloads a newer version, prompts me to provide admin password to add a new helper. Then I start seeing the service errors non-stop at Mac Console (please see below). It seems that update does not succeed.

4/15/15 9:21:37.153 PM Atom[66263]: Download completed to: file:///Users/adil/Library/Application%20Support/com.github.atom.ShipIt/update.e0Ofe6m/download
4/15/15 9:21:42.735 PM com.apple.SecurityServer[86]: Killing auth hosts
4/15/15 9:21:42.735 PM com.apple.SecurityServer[86]: Session 100166 destroyed
4/15/15 9:21:53.705 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt) The Debug key is no longer respected. Please remove it.
4/15/15 9:21:53.731 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt[66283]) Service exited with abnormal code: 1
4/15/15 9:21:53.731 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
4/15/15 9:21:55.750 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt[66284]) Service exited with abnormal code: 1
4/15/15 9:21:55.750 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
4/15/15 9:21:57.768 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt[66285]) Service exited with abnormal code: 1
4/15/15 9:21:57.768 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
4/15/15 9:21:59.791 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt[66286]) Service exited with abnormal code: 1
4/15/15 9:21:59.791 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
4/15/15 9:22:01.811 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt[66287]) Service exited with abnormal code: 1
4/15/15 9:22:01.811 PM com.apple.xpc.launchd[1]: (com.github.atom.ShipIt) Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
4/15/15 9:22:01.949 PM sudo[66288]:     adil : TTY=ttys000 ; PWD=/Users/adil/Library/Application Support/com.github.atom.ShipIt ; USER=root ; COMMAND=/bin/launchctl stop com.github.atom.ShipIt

*\* Also from ShipIt_stderr.log **:
2015-04-15 21:21:53.729 ShipIt[66283:5623798] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo=0x7fb2aa609110 {NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fb2aa606fc0 "The file “ShipItState.plist” couldn’t be opened because there is no such file."}
2015-04-15 21:21:53.729 ShipIt[66283:5623798] ShipIt quitting

**Comment by mnquintana** [comment]
@AdilHindistan Since you're running an extremely old version of Atom and are having trouble updating it within the app, I would recommend uninstalling it and downloading the latest version (0.192.0) from https://atom.io/

**Comment by AdilHindistan** [comment]
I actually did that but as soon as I installed the new version, ShipIt errors started to bombard Console again.

**Comment by AdilHindistan** [comment]
Anyway I can help troubleshooting this?
This is what I see repeating in system logs after installation:
Apr 24 21:11:13 adil-imac-1 ShipIt[24376]: Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo=0x7ffe12803e40 {NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7ffe1280bd90 "The file “ShipItState.plist” couldn’t be opened because there is no such file."}
Apr 24 21:11:13 adil-imac-1 ShipIt[24376]: ShipIt quitting
Apr 24 21:11:13 adil-imac-1 com.apple.xpc.launchd[1] (com.github.atom.ShipIt[24376]): Service exited with abnormal code: 1
Apr 24 21:11:13 adil-imac-1 com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.

**Comment by APahne** [comment]
I have the very same issue. 
Atom 0.194.0
Mac OS X Yosemite

**Comment by jspahrsummers** [comment]
Can you try deleting `~/Library/Application Support/com.github.atom.ShipIt/` entirely, and then attempting to update again?

**Comment by AdilHindistan** [comment]
I am sorry, I thought I responded earlier. I did that, however, issue returned after ~15secs.

**Comment by AdilHindistan** [comment]
I also saw the comments here: https://github.com/atom/atom/issues/2860#issuecomment-59517219
also pointing to https://github.com/Squirrel/Squirrel.Mac/issues/131

**Comment by AdilHindistan** [comment]
I noticed that the permissions for ~/Library/Application Support/com.github.atom.ShipIt were off. Owner was root:staff 
I deleted it again, and it came back with those permissions on 0.196, so I changed owner to myself:staff. Deleted all the files and restarted atom
It downloaded files and Atom menu changed to "Restart and Install Update"
I quit Atom and checked the files:

adil-imac-1:com.github.atom.ShipIt adil$ cat ShipIt_stderr.log 
2015-05-15 14:58:10.025 ShipIt[77074:11763345] Beginning installation
2015-05-15 14:58:13.841 ShipIt[77074:11763354] Moved bundle from file:///Applications/Atom.app to file:///var/folders/z2/330xt59565nfbpk62ymwrwxc0000gq/T/com.github.atom.ShipIt.5moTsaTs/Atom.app
2015-05-15 14:58:13.842 ShipIt[77074:11763354] Moved bundle from file:///var/folders/z2/330xt59565nfbpk62ymwrwxc0000gq/T/com.github.atom.ShipIt.L0Mqp07m/Atom.app to file:///Applications/Atom.app
2015-05-15 14:58:14.470 ShipIt[77074:11763354] Couldn't remove owned bundle at location file:///var/folders/z2/330xt59565nfbpk62ymwrwxc0000gq/T/com.github.atom.ShipIt.L0Mqp07m/Atom.app, error NSError { domain: NSCocoaErrorDomain, code: 4, description: "“Atom.app” couldn’t be removed.", failureReason: "The file doesn’t exist.", underlying error: NSError { domain: NSPOSIXErrorDomain, code: 2, description: "The operation couldn’t be completed. No such file or directory" }, userInfo: {
    NSFilePath = "/var/folders/z2/330xt59565nfbpk62ymwrwxc0000gq/T/com.github.atom.ShipIt.L0Mqp07m/Atom.app";
    NSUserStringVariant =     (
        Remove
    );
} }
2015-05-15 14:58:15.174 ShipIt[77074:11763354] Installation completed successfully
2015-05-15 14:58:15.174 ShipIt[77074:11763354] ShipIt quitting

When I relaunched atom, it was 0.199

**Comment by scv119** [comment]
@50Wliu I could constantly reproduce this by `chown -R root /Applications/Atom.app` and open Atom.app.

**Comment by scottcc** [comment]
I've reproduced this on Atom 1.7.3. I have a couple of different user logins on the machine, and some confluence of using a different user than the original one who installed it seems to have an impact. Even though the application was not owned by root, I saw launchd failures `/var/log/system.out`, and these lines in ShipIt_stderr.log:

    UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7f9188c116d0 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Application Support/com.github.atom.ShipIt/ShipItState.plist, NSUnderlyingError=0x7f9188c0f800 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}

**Comment by xurizaemon** [comment]
I'm seeing this also, on Atom 1.7.4. Atom.app is owned by my user. ShipIt is complaining about not finding ShipItState.plist in `/var/root/Library/Application Support/com.github.atom.ShipIt/ShipItState.plist` but this file does exist in ~/Library.

Atom owned by root:

    $ ls -lAF /Applications/ | grep Atom.app
    drwxr-xr-x@  3 chris  admin    102 22 May 21:39 Atom.app/

No ShipItState.plist in /var/root

    $ find ~/Library/ -name ShipItState.plist
    /Users/chris/Library/Application Support/com.github.atom.ShipIt/ShipItState.plist
    /Users/chris/Library/Application Support/com.github.GitHub.ShipIt/ShipItState.plist

This message fills syslog (pretty much constantly):

    May 24 14:09:28 nine ShipIt: Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7fd961e0ac40 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Application Support/com.github.atom.ShipIt/ShipItState.plist, NSUnderlyingError=0x7fd961e0a600 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
    May 24 14:09:28 nine ShipIt: ShipIt quitting

To experiment I've symlinked from the /var/root location to my homedir's Application Support.

There was a 750MB file in `~/Library/Application Support/com.github.atom.ShipIt/ShipIt_stderr.log`

**Comment by alomvar** [comment]
Having the same problem with Atom 1.7.3 on OS X 10.11.5. I originally installed Atom with a different user account having administrator privileges. Now I am using Atom on a different user account but also with administrator privileges.

**Comment by scottcc** [comment]
Yes - it's clearly something to do with using more than one user (both of my users are administrators too). I've resorted to a quick check of the log, followed by a `sudo launchctl stop com.github.atom.ShipIt` fwiw.

**Comment by AndreaGriffiths11** [comment]
I am able to reproduce this using Atom v1.13.1 on Mac OS X 10.12.3

**Comment by jinwoo** [comment]
This still happens with Atom 1.19.1 on macOS 10.12.6.

**Comment by working-name** [comment]
Still happens with 10.12.6, with Atom 1.19.2
```
2017-08-27 15:05:15.096 ShipIt[46450:20994047] Installation error: Error Domain=SQRLShipItRequestErrorDomain Code=2 "Could not read update request" UserInfo={NSLocalizedDescription=Could not read update request, NSUnderlyingError=0x7f85f3e03b70 {Error Domain=NSCocoaErrorDomain Code=260 "The file “ShipItState.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/var/root/Library/Caches/com.github.atom.ShipIt/ShipItState.plist, NSUnderlyingError=0x7f85f3e03530 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}
2017-08-27 15:05:15.097 ShipIt[46450:20994047] ShipIt quitting
```

**Comment by markovicpp** [comment]
@working-name You can see the process triggered by the `launchctl` tool:
`launchctl list | grep ShipIt`
`> -	78	com.github.atom.ShipIt`

To remove it call:
`launchctl remove com.github.atom.ShipIt`

**Comment by ronguest** [comment]
I'm faced with the nonstop "Service exited..." message in my log as well. I tried removing it with launchctl as noted above. Although no error is reported the errors continue to show in the log and if I do a launchctl list it is still there. 

Any other solutions? I have uninstalled and re-installed Atom several times to no avail.

**Comment by twandrew** [comment]
Clean install of Atom 1.29.0 on macOS 10.13.4 receiving log messages ever two seconds:

Aug  3 10:54:41 hostname com.apple.xpc.launchd[1] (com.github.atom.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds. 
Aug  3 10:54:43 hostname com.apple.xpc.launchd[1] (com.github.atom.ShipIt[80825]): Service exited with abnormal code: 1

Couldn't find a solution so I uninstalled it.
