### ISSUE TITLE
Insert File Header/ Copyright Feature in Atom.io

### ISSUE THREAD

**Issue by nipunarora** [atom/atom#6399]
I wonder if it is possible to create a package in Atom for creating headers for different programming languages? With information like :

- Author Name
- Date Created
- Date Modified
- Copyright
- FileName
- Details/Description

Several existing editors have similar packages, for example sublime has - https://packagecontrol.io/packages/FileHeader, and emacs which I commonly use has the make-headers package, which is quite complete.

**Comment by thomasjo** [comment]
Yes, it's possible. You can create one yourself, or ask on https://discuss.atom.io/.
See [comment-headers](https://github.com/envygeeks/atom-comment-headers) for inspiration/starting point.

**Comment by bedge** [comment]
None of the examples or current pacakges match the feature set provided by the https://packagecontrol.io/packages/FileHeader sample. 
I'd consider this still an open request.

**Comment by guiguan** [comment]
I just wrote a FileHeader for Atom. I think it solves your problem. Check it out! :smiley: https://atom.io/packages/file-header

**Comment by bedge** [comment]
Nice!! - thank you
