### ISSUE TITLE
Updating Atom on Windows fails to update "Open with Atom" context menu shortcut for directories

### ISSUE THREAD

**Issue by Wenzil** [atom/atom#6400]
The "Open with Atom" directory context menu shortcut stops working after every Atom update because the auto installer fails to update the appropriate windows registry keys. The path for the context menu command becomes outdated. In theory that means that "Open with Atom" should open the old Atom version on that directory, but in practice it just doesn't open anything which is just as bad.

Say Atom auto updates to version 0.192.0, the Atom registry keys should be updated to point to the appropriate executable: ``%USERPROFILE%\AppData\Local\atom\app-0.192.0\atom.exe``. The issue is that they aren't.

The registry key locations are:

HKEY_CLASSES_ROOT\Directory\Background\shell\Atom
HKEY_CLASSES_ROOT\Directory\Background\shell\Atom\command
HKEY_CLASSES_ROOT\Directory\shell\Atom
HKEY_CLASSES_ROOT\Directory\shell\Atom\command

The problem only occurs when "Open with Atom" is used on a directory (as opposed to a file).

**Comment by paulcbetts** [comment]
This is all managed by Atom afaik, it _could_ be that somehow we're deciding to not run Squirrel updates, but it's more likely that Atom is somehow not writing those regkeys on update (though I had a look at the code and it seems like it is)

**Comment by christophfroehlich** [comment]
I have a similar though different problem: after an update, files associated with atom cannot be opened out of the explorer by double-click, only by rightclick/open with atom.
After updating the path in `HKEY_USERS\blabla\Software\Classes\Applications\atom.exe\shell\open\command` it works again.

**Comment by Wenzil** [comment]
0.198.0 update seems to have fixed this. I didn't need to update the registry. Cool beans!

**Comment by christophfroehlich** [comment]
here it works, too. thx! :)

**Comment by christophfroehlich** [comment]
0.199.0
Again it doesn't work without manual changing of the registry!

**Comment by robmccullough** [comment]
Please tweak the fix to wrap the Atom path in quotes so it works correctly for paths with spaces in them (e.g., a user name with first and last name).  I have modified the keys to fix the quoted path issue but It is still breaking with every update.

**Comment by gauravmak** [comment]
Facing same problem. Windows cant find executable after I updated 'color picker' to 2.1.0 today morning.

**Comment by dsbert** [comment]
The last two beta release updates did not properly update the context menu (1.10.0-beta1 => 1.10.0-beta3). This is still an issue.

**Comment by roeltz** [comment]
I have been experiencing this problem with every update since I started using Atom (early 1.x versions). Surprisingly, removing registry keys and reinstalling does not solve the issue.

**Comment by rajush** [comment]
@roeltz Did you check under the Settings > System ? There should be 3 check-boxes where you should be able to enable and disable on how it interacts with your OS. 
I hope this works for you as well. I just noticed that on version 1.10.1.

**Comment by Flonker** [comment]
@rajush That fixed it for me. Hadn't noticed the new checkboxes. Thanks for being perceptive!  :) :+1:

**Comment by idbartosz** [comment]
I hade the same problem. You can fix it in three ways:

1. 'Regular user:' run **Atom** and press `ctrl + ,` navigate to "System Settings" tab and uncheck and check again integrity checkboxes you prefer.

2. 'Pro user' run **regedit** and update path in registry keys located in:  `HKEY_USERS\ ... S-1-5-21-2712726677 ... \SOFTWARE\Classes\Directory\Background\`

3. 'Shell user'* run **cmd** as admin and type:
`mklink /J "C:\Users\USER_NAME\AppData\Local\atom\app-1.9.9" "C:\Users\USER_NAME\AppData\Local\atom\app-1.10.2"`

  _*there's a problem with icon in context menu_

**Comment by roeltz** [comment]
@rajush @idbartosz Thanks. I had not seen that settings panel before. That solved it :)

**Comment by koperkiewicz** [comment]
Thanks @idbartosz

**Comment by BWBuchanan7** [comment]
@idbartosz many thanks. I was unaware that this was a simple setting. It seems after a squirrel update my settings for "Show in file context menus" had become unchecked, leaving "Open with Atom" as an option nonetheless, however with a broken icon and it of course didn't work any longer.

Checking this setting again solved the problem for me.

Not really sure how or why that had happened..

**Comment by 50Wliu** [comment]
I'm pretty sure there was an issue with the preferences migrator that should be fixed starting in Atom 1.11.0, or the next 1.10.x version.

**Comment by dbledayr** [comment]
@idbartosz Thank you for that.

**Comment by juschu** [comment]
I don't think this has anything to do with settings that were not migrated to the new version.
I have the version 1.11.2 and the checkboxes were still checked but the paths in the registry were pointing to a file that didn't exist anymore. After I updated all the paths manually it worked again.
So unchecking and checking again those checkboxes is just a workaround. When you ckeck those checkboxes you're telling Atom "Okay Atom, activate this function in the registry" and aparently when Atom is doing this it is using the current version number for the path.

**Comment by manjurulhoque** [comment]
@idbartosz Thanks a lot. Number 1 works for me.

**Comment by appbugs** [comment]
Atom editor is broken for this feature now and then. Have to change it from Settings -> System manually every time.
