### ISSUE TITLE
Red text in comboboxes with One Dark/Light theme

### ISSUE THREAD

**Issue by sryze** [atom/atom#6401]
If I set the UI theme to One Light or One Dark the text color of combobox items becomes red:

![atom-red-text](https://cloud.githubusercontent.com/assets/4525736/7175914/51ae4f64-e43b-11e4-8d49-8d6770f42f4f.png)

Atom version: 0.192.0

**Comment by simurai** [comment]
@sryze Oops sorry. That sneaked in while testing if the dropdown can be customized. Will be removed in the next release.
