### ISSUE TITLE
View -> Toggle Menu Bar changes the Auto Hide Menu Bar option

### ISSUE THREAD

**Issue by bedekelly** [atom/atom#6402]
Using version 0.189.0 (latest version in repositories) on Ubuntu 14.04. Since I use the Alt key for switching desktops in my WM, I don't want it to toggle the menu bar in Atom. However, using the Settings View to turn the Auto Hide Menu Bar option off causes the menu bar to appear. When I click View -> Toggle Menu Bar in the menu bar, the menu bar disappears as intended - but the Auto Hide Menu Bar setting toggles back on in the Settings View, meaning the Alt key still toggles the menu bar.

Is this intended behaviour? If so, is there some workaround to disable the Alt key?

**Comment by bedekelly** [comment]
For clarification, this is the behaviour described above - using "atom --safe" as I've seen suggested elsewhere does not resolve this issue.

![recorded](https://cloud.githubusercontent.com/assets/731851/7244488/3ae8faf8-e7d4-11e4-8df8-28d2c459d99d.gif)

**Comment by alectic** [comment]
I'm interested in this as well, as alt is a very used key with tilling window managers and it's hard to not get distracted and annoyed.

**Comment by bedekelly** [comment]
I'm not sure why this is listed as a 'question', seems like a bug to me.

**Comment by christopherpoole** [comment]
If you would like to hide the menu and disable the ALT key from toggling its visibility, select "Auto Hide Menu Bar" in Core Settings, and try this in `keymap.cson`:

    'atom-text-editor':
      'alt': ' '

This is working for me in v1.1.0, and stopping interference with xmonad key bindings.

Note that it only has an effect when the editing area or project tree has focus. If you click in the tab bar, ALT will toggle the menu.

**Comment by maxbrunsfeld** [comment]
@bedekelly @alectic Are you still seeing this on the latest version of Atom?

**Comment by alectic** [comment]
@maxbrunsfeld yes, pressing the alt key in atom 1.2.2 still toggles the menu bar. I haven't tried it on 1.3.0-beta4.

**Comment by luixal** [comment]
@maxbrunsfeld @alexdreptu i'm using `1.13.0 ia32` and just got here so... this bugs persists.

**Comment by joadr** [comment]
Fixed by adding these lines to the keymap.cson

`
'atom-text-editor':
  'alt': ' '
  'ctrl-alt': ' '
`
