### ISSUE TITLE
suppressing autoscroll, or saving/restoring current scroll position

### ISSUE THREAD

**Issue by jacekkopecky** [atom/atom#6403]
In ae4f7f6170da83c786ba06235f0997e52e806b10, a global autoscroll suppression mechanism was removed in favour of a per-call `autoscroll` option.

In vim-mode, motions get combined with operations, and the _yank_ operation which copies text into clipboard should not always scroll around. However, there currently seems to be no way of preventing generic cursor movements from autoscrolling.

@nathansobo suggested adding the `autoscroll` option in the various movement methods, so I'm looking at this. It seems it will require that every method that may move the cursors to accept and pass through an options parameter; that feels like an unnecessarily wide-reaching contract, which affects not only methods in Atom core, but also in any package that has actions that can move the cursor.

Further, some methods like `Selection.selectLine` and `Selection.insertText` currently simply assume `autoscroll` should be true, and all places like this would need to be revisited.

@nathansobo and @maxbrunsfeld - there was a `Editor.suppressAutoscroll` option in the code, introduced in 99c437ccecff469d2fc4ba70ff3ff9a0f694f9e6 and removed again in ae4f7f6170da83c786ba06235f0997e52e806b10 - can you please clarify the reasoning there? I'm sure I'm missing something.

Alternatively, is there a public API for getting and setting the current scroll position of the window? If so, vim-mode's _yank_ operation could use that.

**Comment by nathansobo** [comment]
We added the `suppressAutoscroll` flag because our previous approach to autoscrolling depended on a fairly indirect mechanism where we responded to the marker moving. When we moved to a more direct approach it was no longer needed. What I was assuming with this option is that `autoscroll` would default to `true` in all these cases. You would only need to specify the option when you wanted to suppress it, in which case you would pass `false`.

**Comment by jacekkopecky** [comment]
In [this diff](https://github.com/atom/vim-mode/pull/591/files#diff-b60bce4a3547b0c210a27cd1dce95900R188), I've now avoided trying to prevent autoscrolling, instead I use `Editor.getScrollTop` and `setScrollTop` (and `*Left`) to save the scroll location before cursor motions, and restore if afterwards. Is this OK?

**Comment by nathansobo** [comment]
I'd really prefer to add the ability to suppress it in the movement calls so we can avoid keeping additional state. I understand the reticence to open a PR on core, however. I've added this issue to our agenda for discussion on Monday.

**Comment by jacekkopecky** [comment]
Thank you. 8-)

**Comment by nathansobo** [comment]
We talked about this today and most likely don't really have the bandwidth on the core team to do it before 1.0. I encourage anyone whose interested to give it a try. If not, we'll get to it post 1.0.

**Comment by jacekkopecky** [comment]
OK, no worries.

**Comment by jacekkopecky** [comment]
Yes, this is stale; vim-mode has been deprecated and I don't know how vim-mode-plus handles things.
