### ISSUE TITLE
Overriding a grammars filetype association

### ISSUE THREAD

**Issue by MaxGiting** [atom/atom#6406]
I wan't to have .tpl files associated with a Smarty grammar, but the default html grammar already specifies .tpl in its file type. Is there a way around this. I have seen the [File Types](https://github.com/execjosh/atom-file-types) package but this specifically says at the bottom of the read me `You probably don't want to assign the same file type to multiple languages...`

Is there any way other than editing the HTML language package and removing the .tpl association to override that? I can't see that would be great though as if you have two packages trying to override, which would be used?

**Comment by izuzak** [comment]
As far as I know -- that's not possible currently, but I agree it would be helpful. There's already an open issue to support that: https://github.com/atom/atom/issues/1718. I'm going to close this in favor of that issue, but let me know if I misunderstood and this isn't a duplicate. Thanks for the feedback! :+1:
