### ISSUE TITLE
Creating a non-text editor Pane. Input forms don't respond to input, or have just limited keyboard input

### ISSUE THREAD

**Issue by jonathanjibo** [atom/atom#6408]
In my editor, <input> elements don't change value.

`<input type="number" value="500" />`
Up and down arrows are active but don't change the value in the input element

`<input type='text' value="Hello" />`
Typing anything in the field moves the cursor to the end of "Hello". Delete and backspace don't work either. Arrow keys don't do anything.

I've also embedded Ace editor. This seems to work, except for the "enter" key. In order to create a newline I have to press "shift-enter".

Is Atom intercepting keyboard input somehow? I'm not sure what's going on here.

Thanks

**Comment by mark-hahn** [comment]
Research `native-key-bindings`.  Things are improved but not perfect.

**Comment by lee-dohm** [comment]
Whoops! This should have been closed a while back :blush:
