### ISSUE TITLE
Cannot indicate git on OSX

### ISSUE THREAD

**Issue by XinwenCheng** [atom/atom#6410]
I'm using Atom V0.191.0, and React plugin needs to be upgraded from 0.9.10 to 0.11.4, but Atom cannot indicate git from my OSX, but actually git works in command line.
![screen shot 2015-04-17 at 10 02 51 am](https://cloud.githubusercontent.com/assets/795334/7194871/62b9f566-e4e9-11e4-9653-f3322dc3631c.png)

**Comment by thomasjo** [comment]
What does `type -p git` produce when executed from your terminal?

**Comment by XinwenCheng** [comment]
@thomasjo here it is.
![screen shot 2015-04-20 at 9 19 10 am](https://cloud.githubusercontent.com/assets/795334/7222332/890b94a2-e73e-11e4-85a8-468990701701.png)

**Comment by izuzak** [comment]
@XinwenCheng is this still a problem for you (in Atom 1.0.11) or did you manage to fix things?

**Comment by XinwenCheng** [comment]
@izuzak Hi, sorry I just noticed your comment. It works in V1.0.11, no problem now, thanks!
