### ISSUE TITLE
Failed to load the jibo-atom package

### ISSUE THREAD

**Issue by jonathanjibo** [atom/atom#6411]
I added a 'native!' binding to one of my keymaps/*.cson to get native key input for an `<input>` element as described [here](https://atom.io/docs/v0.95.0/advanced/keymaps)

[Enter steps to reproduce below:]

 Added  
```
'.my-native-key-bindings':
  'enter': 'native!'
```
to `keymaps/main.cson`

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the test-atom-package package

```
At reserved word "native"

[stdin]:7:13: error: reserved word "native"
  'enter': 'native!'
            ^
```

### Commands

```
```

### Config

```json
{
  "core": {
    "showOnStartup": false,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
test-atom-package, v1.0.1

# Dev
test-atom-package, v1.0.1
```

**Comment by izuzak** [comment]
Thanks for the report, @jonathanjibo. I'm having trouble reproducing this, though -- I just added the same snippet to one of my packages and it didn't throw an error. Can you reliably reproduce this? If so, can you post your full package (in a state in which it throws the exception) into a GitHub repository and send us a link to that repository?

**Comment by jonathanjibo** [comment]
That's the strangest thing! I cannot reproduce this anymore. If it happens
again I'll post the package to github.
