### ISSUE TITLE
attaching the '.native-key-bindings' class to an <input> element has no effect on keyboard input

### ISSUE THREAD

**Issue by jonathanjibo** [atom/atom#6412]
When creating an input element with class native-key-bindings `<input class="native-key-bindings"...` of type `text` or `number`, the key bindings don't act natively.

For anyone else that's run into this problem, I've gotten around this by not using input types that require keyboard input and instead, use a div with the contenteditable attribute and some styling. For example
HTML:
```
<div class="input-div native-key-bindings" contenteditable>Hello Foo</div>
```
CSS to make it look like a native input text field:
```
.input-div {
  background-color: white;
  border: 1px solid darkgray;
  box-shadow: 1px 1px 1px 0 lightgray inset;
  font: -moz-field;
  margin-top: 5px;
  padding: 2px 3px;
  width: 100%;
  height: 25px;
}
```

To make it a single line field add
```
[contenteditable="true"].input-div {
  white-space: nowrap;
  overflow: hidden;
}
[contenteditable="true"].input-div br {
  display:none;

}
[contenteditable="true"].input-div * {
  display:inline;
  white-space:nowrap;
}
```

It would be great to be able to support input elements.

**Comment by mnquintana** [comment]
Just out of curiosity, did you try applying `.native-key-bindings` to a parent element?

**Comment by jonathanjibo** [comment]
I ended up using the native atom editor with mini attribute. But `<input type="number" />` does not work at all. I did try placing "native-key-bindings" to the parent element as well to no avail.

**Comment by lee-dohm** [comment]
I'm pretty sure that it requires both `class='.native-key-bindings'` and `tabindex=-1`:

https://discuss.atom.io/t/simple-way-to-get-copy-working-on-my-own-pane-item/16131/7?u=leedohm

**Comment by jonathanjibo** [comment]
Ok this was my fault. Using react and there's weirdness with react input forms. Nothing to do with atom. With tabindex=-1, native-key-bindings, and force rerendering after input change it all works.

Thanks for the help.

**Comment by lee-dohm** [comment]
You're welcome. Glad we could help :grinning:
