### ISSUE TITLE
Idea: Remote atom development server

### ISSUE THREAD

**Issue by Bjoernsen** [atom/atom#6414]
Hi,
I wonder if there is a way to run different atom instances for different users on one linux server and enable the access through Apache or NginX using e.g. different sub domains?

The Idea is that (windows) users could develop remotely (linux) applications using their Chrome, or Firefox without installing all dependencies locally. Like https://www.nitrous.io.
Or is this idea rubbish?

**Comment by kaizhang** [comment]
+1 for this feature. I must perform data analysis on a remote machine, so it would be nice to have atom installed on the server, and run it through a desktop.

**Comment by paulcbetts** [comment]
I believe what you're describing is super similar to Nuclide's remote-folders workflow (a set of Atom packages developed by Facebook), check it out: http://nuclide.io/docs/remote/

**Comment by kaizhang** [comment]
@paulcbetts Very nice! It does what I want. I think this feature should be merged to tree-view.
