### ISSUE TITLE
Cannot find atom-shell v0.22.3 from GitHub [Error: Not Found]

### ISSUE THREAD

**Issue by gevero** [atom/atom#6415]
Building atom from source
 My system:
```
manjaro-linux 3.16.7.9-1-MANJARO
Node: v0.12.2
npm: v2.7.5
```
when running script/build I get:
```
Cannot find atom-shell v0.22.3 from GitHub [Error: Not Found]
Aborted due to warnings."
```
The install procedure always worked fine, but not today.

**Comment by YuriSolovyov** [comment]
could be caused by [renaming atom-shell to electron](https://github.com/atom/electron/pull/1389)

**Comment by gevero** [comment]
So I guess that [grunt-download-atom-shell](https://github.com/atom/grunt-download-atom-shell) should be modified?

**Comment by YuriSolovyov** [comment]
@gevero maybe [this line](https://github.com/atom/grunt-download-atom-shell/blob/master/tasks/download-atom-shell-task.coffee#L129) ?

**Comment by sclausen** [comment]
+1

**Comment by slackmoehrle** [comment]
+1

**Comment by 50Wliu** [comment]
This is being worked on in atom/grunt-download-atom-shell#23, no need to panic :wink:.

**Comment by ioquatix** [comment]
+1

**Comment by sclausen** [comment]
@50Wliu maybe we're a bit impatient, but nothing happens... so: PANIC!!!!!!

**Comment by slackmoehrle** [comment]
And where is the testing? I understand things happen, but some of us rely on building versus having to update releases by downloading a binary. For me, using the build in update never works.

**Comment by Morgan-Leon** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8945216/7217831/bd922756-e679-11e4-8eeb-4bb0cbe83e62.png)
IOS 10.10.2 has the same problem.

**Comment by slackmoehrle** [comment]
What app is that behind the terminal?  @Morgan-Leon

**Comment by ioquatix** [comment]
Hey guys, I found a quick fix for arch users

```
pacman -R atom-editor
yaourt -S atom-editor-bin
```

Worked for me just fine.

**Comment by JordiOrlando** [comment]
Can confirm @ioquatix's workaround worked for me on Arch

**Comment by auxiliary** [comment]
@ioquatix's workaround worked for me on Arch too.

**Comment by tosmarcel** [comment]
@ioquatix's method worked for me on Arch too. Thx!

**Comment by sashka** [comment]
```
Running "download-atom-shell" task
>> Cannot find atom-shell v0.22.3 from GitHub [Error: Not Found]
Aborted due to warnings.
```
+1

**Comment by aruscher** [comment]
should be fixed in the current master release 46f90f09841e220b28a81a5c207421c63c9bc573

**Comment by SergioScabuzzo** [comment]
Node: v0.12.2
npm: v2.7.4


After latest update, now getting past:
 Running "download-atom-shell" task

But fails at next step:
Running "download-atom-shell-chromedriver" task
>> Cannot find atom-shell v0.22.0 from GitHub [Error: Not Found]
Aborted due to warnings.

**Comment by kevinsawicki** [comment]
@SergioScabuzzo what command did you run?

**Comment by SergioScabuzzo** [comment]
@kevinsawicki  sudo script/build
Followed the build instructions for linux.

**Comment by kevinsawicki** [comment]
@SergioScabuzzo what is the SHA-1 of the commit you are trying to build?

**Comment by SergioScabuzzo** [comment]
Sorry if I'm kinda dense. 
I think this is it 9a0c3f9

**Comment by SergioScabuzzo** [comment]
@kevinsawicki Never mind... I checked out 46f90f0 and it worked fine. Should have done my due dilligence. 

Thanks
