### ISSUE TITLE
Keymaps - how to identify the key pressed 

### ISSUE THREAD

**Issue by skandasoft** [atom/atom#6421]
this is for the custom package and the requirement is to identify programatically the key pressed. if there are multiple keymaps to the same package method..when the method is called, the arguments passed has jquery.Event but it doesn't have the keyPress/which to identify which key combination was pressed to get to the method
The use case is when multiple keymaps are associated with one method is there a way to identify which key combination was pressed to get to the method.
Is it possible to pass the key press identifier/which to the jquery.Event object

or 

is it possible to pass the parameters to the key maps maintained

**Comment by mark-hahn** [comment]
jQuery is being deprecated so this is probably not a good solution.  Look
into doing something with native events.

**Comment by skandasoft** [comment]
I think it has evt parameter has the details..thanks for chipping in..
