### ISSUE TITLE
keybindings to switch Atom windows

### ISSUE THREAD

**Issue by kolohelios** [atom/atom#6422]
When multiple Atom windows are open (at least on the Mac), one has to use Exposé to switch Atom instances. Cmd-Tab won't allow switching to a different Atom instance. Adding Key Bindings to the Window menu to either rotate through open windows or pick a specific window would allow one's hands to stay on the keyboard. It's also not always obvious that there is more than one Atom window open at any time.

**Comment by lee-dohm** [comment]
You should be able to use <kbd>Cmd+`</kbd> to rotate through Atom windows.

**Comment by kolohelios** [comment]
Thanks! That does the trick.
