### ISSUE TITLE
No keybinding for editor:split-selections-into-lines on Linux and Windows

### ISSUE THREAD

**Issue by Faelian** [atom/atom#6427]
I guess that a lot of atom users are coming from sublime, and we tend to expect some keyboard shortcut like the split-selections-into-lines.

On mac os it's the same keybinding than sublime for split-selections-into-lines, but not on Linux and nor Windows.

I had to add the following lines to my `keymap.cson`:

``` cson
'.platform-linux atom-text-editor':
  'ctrl-shift-L': 'editor:split-selections-into-lines'
```

**Comment by izuzak** [comment]
@Faelian There's already a command bound to that keystroke on Linux and Windows, as far as I can tell. The Grammar Selector core package [uses `ctrl-shift-l` on all OSes to toggle the grammar selector view](https://github.com/atom/grammar-selector/blob/9c5fffe592f8158869ae74569342f82b29c83449/keymaps/grammar-selector.cson).

**Comment by izuzak** [comment]
I changed the title to `No keybinding for editor:split-selections-into-lines on Linux and Windows` and added the enhancement label.

**Comment by chris-peerman** [comment]
I added the following to my keymap.json file which seemed to work, the 'atom-text-editor' doesn't appear to be needed:
<pre>
'.platform-win32 atom-text-editor':
    'ctrl-shift-l': 'editor:split-selections-into-lines'

'atom-text-editor':
    'ctrl-shift-l': 'editor:split-selections-into-lines'
</pre>

**Comment by fjmarcelo** [comment]
Thanks a lot!!

It works very fine!!

**Comment by thewebists** [comment]
The custom mapping works for me too.

Saying that, it would be nice for the `ctrl-shift-l` shortcut to be mapped to spit lines by default, to be consistent with the Sublime mapping. For my part at least, I use this shortcut on a regular basis, while I've always opted for `ctrl-shift-p` to change syntax/grammar and don't feel a need for a dedicated shortcut for that.

**Comment by ChrisAntaki** [comment]
@thewebists :+1:

**Comment by Vaggos** [comment]
I managed to do it with the following in Windows 7:
`'.editor:not(.mini)':
  'ctrl-shift-l': 'editor:split-selections-into-lines'`
And I aggre with @thewebists. The the `ctrl-shift-l` shortcut would be nice to be mapped to spit lines by default

**Comment by sergio-bobillier** [comment]
I would like to suggest that in Linux/Windows `ctrl-shift-L` be left as the shortcut for Split Selection into Lines and `ctrl-shift-J` became the Grammar Selection shortcut.

**Comment by Esteban-Rocha** [comment]
This setup worked for me.


```css
'.platform-linux atom-text-editor':
  'ctrl-shift-L': 'editor:split-selections-into-lines'
```

OR

```css
'.platform-win32 atom-text-editor':
    'ctrl-alt-l': 'editor:split-selections-into-lines'
```

**Comment by pacharanero** [comment]
+1 for this ctrl+shift+L being the default split into lines and shifting the grammer selection to another shortcut eg ctrl+shift+J as suggested by @sergio-bobillier

**Comment by route** [comment]
It's not stale, latest Atom 1.26.1 still missing these key bindings please reopen someone @izuzak
