### ISSUE TITLE
Open in dev mode broken?

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#6430]
The `cmd-shift-O` binding still presents a dialog, but at least on my latest master build it never opens a new window.

Followup: looks like this has something to do with `cmd-shift-O` being bound to add project folder?

**Comment by thomasjo** [comment]
This is not a bug. It was explicitly changed in https://github.com/atom/atom/pull/6292.

**Comment by nathansobo** [comment]
Thanks sorry for the noise.
