### ISSUE TITLE
C highlighting broken for strfdate

### ISSUE THREAD

**Issue by rumpelsepp** [atom/atom#6432]
When using strftime-style strings the highlighting for C is broken:

``` c
t = time(NULL);
tmp = localtime(&t);
strftime(timestr, sizeof(timestr), "%Y-%m-%d %H:%M:%s", tmp);
```

![screenshot from 2015-04-18 19-39-59](https://cloud.githubusercontent.com/assets/1961699/7216523/b726aab2-e602-11e4-8a3c-7c9e53052407.png)

**Comment by izuzak** [comment]
Please reopen in https://github.com/atom/language-c. Thanks for the report!

**Comment by rumpelsepp** [comment]
Oh sorry.
