### ISSUE TITLE
Uncaught Error: UNKNOWN: unknown error, open 'C:\Users\msafra\.atom\packages\save-session\projects\C\Users\msafra\Desktop\meeting mgt\project.json'

### ISSUE THREAD

**Issue by mohasafra** [atom/atom#6434]
[Enter steps to reproduce below:]

1. error showing constantly without my interaction

**Atom Version**: 0.192.0
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: UNKNOWN: unknown error, open 'C:\Users\msafra\.atom\packages\save-session\projects\C\Users\msafra\Desktop\meeting mgt\project.json'

```
At fs.js:55

Error: UNKNOWN: unknown error, open 'C:\Users\msafra\.atom\packages\save-session\projects\C\Users\msafra\Desktop\meeting mgt\project.json'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "flatui"
    ],
    "disabledPackages": [
      "remember-session"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
autoclose-html, v0.15.0
autocomplete-plus, v2.10.0
emmet, v2.3.7
file-icons, v1.5.4
flatui, v0.4.0
highlight-line, v0.10.1
highlight-selected, v0.9.1
linter-bootlint, v0.0.5
linter-csslint, v0.0.11
linter-htmlhint, v0.0.13
linter-jshint, v0.1.2
save-session, v0.13.5
Sublime-Style-Column-Selection, v1.2.3

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@mohasafra Does the problem happen if you run Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? The stack trace indicates that the `save-session` package is involved. If running in safe mode helps, try disabling that package and running Atom normally again and see if that resolves the problem.

**Comment by 50Wliu** [comment]
This looks fairly certain to be a `save-session` bug to me, so I'm going to close this.  @mohasafra, if you can reproduce this using @izuzak's instructions, please comment here!

**Comment by mohasafra** [comment]
yeah it works fine in safe mode so i guess it is a save-session bug thanks guy i'll report it to save-session
