### ISSUE TITLE
Use js-git, libgit2 or GitHub API instead of git.exe for apm publish.

### ISSUE THREAD

**Issue by Zoltu** [atom/atom#6442]
Currently, apm publish appears to use the command-line git for publishing a new package.  This is problematic for users who do not use command-line git for interacting with git.  There are many tools on the market that allow git interaction without the command line (GitHub for Windows and Visual Studio to name a couple big ones) so not all users have git.exe installed.  For those that do have it insalled, they may be interacting with it through a front-end (git extensions) so they may not have git on the path and/or setup to work from the command line.

For such users, publishing is a bit of a headache.  I recommend switching to js-git, libgit2 or the GitHub API when interacting with GitHub for publishing.  This would make it easier for non-git-command-line users to publish packages.

**Comment by lee-dohm** [comment]
This issue was moved to atom/apm#341
