### ISSUE TITLE
Disable Context Menu

### ISSUE THREAD

**Issue by francoislaberge** [atom/atom#6443]
hi,

I'm working on a non text editor and would like to use right mouse down dragging to do something (pan a 3D camera), this works but is awkward because the context menu always pops up. I haven't been able to find a way to disable the context menu for pane. Am I just fighting an uphill battle?

Francois

**Comment by kevinsawicki** [comment]
You can listen for the `contextmenu` event on all element and act accordingly with the event provided.

You can see how Atom implements it here: https://github.com/atom/atom/blob/c039c820a42ff1e2210d31771c2b4cdf812e8956/src/window-event-handler.coffee#L111-L113
