### ISSUE TITLE
Command Palette disapears when plugin loads (external) bootstrap

### ISSUE THREAD

**Issue by kans** [atom/atom#6448]
My plugin was previously loading bootstrap.less via an import statement like so:

``` css
@import "bootstrap.less";
```

I updated to 0.192 and this behavior was broken - bootstrap.less could not be found.  I implemented a quick hack by depending on bootstrap in my package.json and importing bootstrap.less the stupid way:

``` css
@import "../node_modules/bootstrap/less/bootstrap.less";
```

Less was built, but the command palette was gone about half the time.  

Including a different/external version of bootstrap may not be supported behavior, but relying on the bootstrap atom ships is problematic.  For that matter, if it is not supported, an error, warning, or documentation would be helpful.

**Comment by kevinsawicki** [comment]
Just curious, why do you need to import bootstrap?

**Comment by kans** [comment]
@kevinsawicki 
The first pass for our plugin was a direct dump of our website.  We took code from our real time collaborative editor and also quite a bit of UI stuff from the rest of the website.  The UI stuff includes forms for signing up/logging in, modals for general error reporting/trouble shooting, and WebRTC widgets.  I would say that about 60-75% of the work for our plugin is actually in the UI (real time collaborative editing is comparatively simple to implement since we already have the backend).  We would throw out WebRTC in particular if it didn't work as is. 

Honestly, building the plugin (collaborative editing) was about as good of an experience as I could hope for while building the UI has been an absolute train wreck.

**Comment by kevinsawicki** [comment]
So bootstrap is bundled with Atom and always loaded at startup.

What changed recently was that the version bundled with Atom was no longer on the Less import path since it was precompiled to a `.css` file to speed up startup time. #6333

**Comment by kans** [comment]
Thanks for the explanation.

On our end, we will probably move the major components to live inside webviews for isolation... a React Element inside of a webview inside a custom HTML component inside of a space pen view that duck types an Atom Pane.

**Comment by lee-dohm** [comment]
Looks like this should have been closed a while back :blush:
