### ISSUE TITLE
Atom will not launch from a USB flash drive when setting `ATOM_HOME`

### ISSUE THREAD

**Issue by James-Parsons** [atom/atom#6452]
Most of the details can be found at this post:
https://discuss.atom.io/t/starting-atom-via-command-line-does-not-launch-it-correctly/16279/2

I recently tried to run atom portable. I would like to keep all my themes and packages on the drive as well, so I created a .atom folder on my flash drive using `md .atom`. After that, I extracted the latest zip distribution of Atom into an `Atom` folder on my flash drive. To set `ATOM_HOME` and launch atom, I used the following script:

    @echo off
    set ATOM_HOME= "E:/.atom"
    start E:/Atom/atom.exe --safe
    echo ATOM_HOME currently at %ATOM_HOME%
    echo.
    pause

When trying to run this script, I got

    [4924:0421/080402:INFO:CONSOLE(67)] "RangeError: Maximum call stack size exceeded

The rest of the stack trace can be found at the above link. Oddly, after I `REM`ed out the `set ATOM_HOME= "E:/.atom"`, atom launched fine from the flash drive. Is there anyway this can be fixed?

**Comment by lee-dohm** [comment]
What was your current working directory when you ran this script and you got the error?

**Comment by James-Parsons** [comment]
Should be `E:/Atom`

**Comment by Thierdox** [comment]
You are setting the environment variable wrong. When you surround the path name with " windows will interpret that as being part of the name. So essentially you set the path to

    " "E:/.atom""

Try using this instead

    @echo off
    set ATOM_HOME=E:/.atom
    start "Dummy Title" E:/Atom/atom.exe --safe

**Comment by darkmorpher** [comment]
CC @damieng to close :dango:

**Comment by damieng** [comment]
Additionally it should be `e:\.atom` - paths are backslashes on Windows not forward-slashes. Some things work with them as forward-slashes but a whole bunch of other things get confused. 

Please re-open if this is still a problem with Atom 1.7 or later.

**Comment by namelus** [comment]
@damieng - I don't think you can set environment variables in Windows 7 if you aren't the admin. Can we look for a portable solution that is self-contained on the USB that would work for both admin and non-admin Windows 7 users?

**Comment by damieng** [comment]
The SET command does not require admin privileges as it is not permanent - it just applies to the current command Window.  It therefore works for both admin and non-admin.

**Comment by namelus** [comment]
Thanks for the quick response.

According to my research you get prompted for the Admin credentials. See
here:
http://superuser.com/questions/165909/how-can-i-set-user-environmental-variables-such-as-path-from-a-non-administrat

I could be wrong / misunderstanding...

**Comment by damieng** [comment]
That is talking about using the UI to set a permanent environment variable. That will require admin permissions if setting machine-wide or may require admin permissions for user-wide if your group policy has been set for that.

This solution is talking about the ```SET``` command which is a temporary non-administrator for-this-command-windows-life-only duration.

**Comment by namelus** [comment]
Ok, great news! I'll give it a go once I am in at a PC where I am a non-admin. 

I'm also curious about getting a package such as Atom-Runner working in a portable setting. Any tips on that?
