### ISSUE TITLE
Uploading to local file system

### ISSUE THREAD

**Issue by kupoback** [atom/atom#6453]
At my webfirm, we host sites on our servers. We have access to it via out Network tab. However no one has ever needed to FTP to the server.

Is there a way to use Atom to connect to a File System? The Target Location is something like this

    \\Server\www\domain.dev.com

While I can just work off the server, we use bitbucket to keep a history of changes in the repo, so working off the server isn't really an option. 

Any suggestions? I am using SFTP for our wordpress sites which we use Media Temple for, so I have no issues there. I'm just not a fan of Visual Studio to work on our hosted sites.

**Comment by damieng** [comment]
Atom can open files directly on that share, or integrate with a source control system to commit them.

It does not include any kind of push mechanism by default and those would be provided by additional packages.
