### ISSUE TITLE
Global search different than on buffer search

### ISSUE THREAD

**Issue by eddiemonge** [atom/atom#6460]
If I do a search in page for `\n\s+href="\#"` it finds a couple of results. If I then do a global search for the same thing, there are no results. The options are the same: regex, case insensitive.

**Comment by 50Wliu** [comment]
Duplicate of atom/find-and-replace#218, please subscribe there for updates.

**Comment by eddiemonge** [comment]
Thanks @50Wliu for pointing me in the right direction.
