### ISSUE TITLE
triple-click+scroll doesn't work properly

### ISSUE THREAD

**Issue by vincentisambart** [atom/atom#6462]
On Atom 0.193, OSX 10.10.3
Triple-clicking (to fully select a line), then letting the left mouse button pressed and scrolling (with mouse wheel or two-finger swipe on the trackpad) doesn't work properly: it should scroll and expand the selection, but the scroll jumps back to where it was.

**Comment by 1j01** [comment]
:+1: And triple-clicking and moving the mouse to the top/bottom of the view doesn't scroll
