### ISSUE TITLE
Reopening windows feature from 193 not working

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#6466]
Does the Desktop shortcut on Windows need updating for this to work, maybe? Because it does not work for me atm, see video: https://youtu.be/SETJog-VnkY

**Comment by brettle** [comment]
This is also broken on Fedora 21. The atom.desktop file executes "atom" which is the /usr/bin/atom bash script. That script passes --executed-from=$(cwd) to /usr/share/atom/atom. That argument causes atom to bypass the reopening windows feature and just open a window on the current working directory.

Proposed fix: change the atom.desktop generated for the RPM to execute /usr/share/atom/atom instead. That appears to be what the atom.desktop generated for the DEB does already.

**Comment by 50Wliu** [comment]
Refs to #6464.

**Comment by 50Wliu** [comment]
Closed by #6470.

**Comment by 50Wliu** [comment]
Never mind, this is only a fix for Fedora, not Windows.

**Comment by Malcolm** [comment]
ALT+F4 and closing the window by click the "X" causes the session to not save.  Going "File" to "Exit" gives expected behaivour.

Video displaying the issue:
http://youtu.be/U4YmkezSMzg

**Comment by Xel-X** [comment]
Same on Ubuntu:
Only  closing via ```File``` -> ```Quit``` saves the session.
Any other close or any crash results in a blank session after reopening.

**Comment by pierretusseau** [comment]
Doesn't work with Task Manager either.

**Comment by bob-v-t** [comment]
+1

**Comment by xlaywan** [comment]
+1

**Comment by Zireael07** [comment]
0.196.0, doesn't reopen my project either. I thought it was because I opened it via Project Manager...

**Comment by Zireael07** [comment]
0.196.0, exiting atom via X or Alt-F4 causes this not to work. File-> Exit works, though.

**Comment by escolhatecnologia** [comment]
+1   0.196.0, exiting atom via X or Alt-F4 causes this not to work. File-> Exit works
Ubuntu  15.02

**Comment by escolhatecnologia** [comment]
+1      
Reopening windows feature from not working.
Atom  0.196.0 
Linux

**Comment by escolhatecnologia** [comment]
+1

Reopening windows feature  not working.
Atom 0.196.0 
Linux

**Comment by 50Wliu** [comment]
Re-adding Linux to this bug.

**Comment by rebornishard** [comment]
@Zireael07  @pierretusseau  same here on windows 7 x64

**Comment by Zireael07** [comment]
@rebornishard I'm on Win7 64, too.

**Comment by izuzak** [comment]
> Only closing via File -> Quit saves the session.
> Any other close or any crash results in a blank session after reopening.

I'm seeing the same behavior on Windows 8. /cc @maxbrunsfeld -- I'm pretty sure you noticed this issue, but wanted to ping you just in case. :bowtie: 

There seems to be a different between Windows and OSX -- if I close the last Atom window on OSX (using the "x" button), there's still an Atom process showing up in Activity monitor. Only if I quit Atom with cmd-q or with Atom > Quit does Atom quit completely. On Windows it seems that closing the last Window with "x" also closes all other processes. However, the session-restore feature only works if Atom was completely exited through File -> Quit.

**Comment by fedelibre** [comment]
I agree with previous comments.
Debian Linux here

**Comment by pierretusseau** [comment]
From what @izuzak said, I think an additional solution could be to keep background task Atom (like chrome, wamp, etc...) and the "X" from windows would just shutdown the window, but not the task, and all relatives.

**Comment by Yajo** [comment]
No matter how I close Atom, it always starts in `$HOME`.

```
$ rpm -q atom
atom-0.196.0-0.1.fc21.x86_64
$ cat /etc/redhat-release 
Fedora release 21 (Twenty One)
```

**Comment by 50Wliu** [comment]
@Yajo currently starting Atom using the shell script (aka just invoking `atom`) will start Atom in whatever directory you're currently in.  If you're using a desktop shortcut/icon/etc. make sure it's pointing to `/usr/share/local/atom/atom`.

**Comment by Yajo** [comment]
I'm using the atom.desktop file provided by the RPM package:

```
$ grep Exec /usr/share/applications/atom.desktop
Exec=/usr/share/atom/atom %U
```

Should I change that?

**Comment by 50Wliu** [comment]
Oh, then I'm pretty sure you don't need to change that.

**Comment by tedyun** [comment]
+1 on Windows 7 64-bit.

Restore-session feature does work if Atom is closed with File -> Exit. Does not work if closed with "X" button.

**Comment by ganileni** [comment]
+1 same problem on ubuntu 14.04

**Comment by rkingsbury** [comment]
+1 on Linux Mint 17.1

**Comment by MtDalPizzol** [comment]
+1 Ubuntu 14.04 only saves by File -> Quit.

**Comment by brettle** [comment]
PR #6489 should fix this, if anyone wants to give it a try. If it needs more work to get merged, just let me know. Otherwise, I'm assuming the maintainers just haven't had time to review and merge it yet.

**Comment by maxbrunsfeld** [comment]
I believe this is fixed by #6684. I have only tested it on Ubuntu 14.04, and not Windows, but I think the problem was the same on both of those platforms. I'll reopen this issue if the problem persists for anyone after upgrading to 0.199, which should be released by the end of the week.

**Comment by xlaywan** [comment]
Still not working for me(win10, atom 0.199)

**Comment by rkingsbury** [comment]
Fixed for me on Linux Mint 17.1. Thanks!

**Comment by Malcolm** [comment]
Fixed for me on Windows 8.1; File->Exit, Alt+F4, "X" chrome button and even killing the task in task manager keeps the window state when re-opening.

Thanks!

**Comment by fifovillage** [comment]
still doesn't work for me in windows 7 atom 0.209.0

**Comment by Malcolm** [comment]
+1

Alt-F4, closing using the X and even file -> exit no longer restore the previously opened folders or documents.

Looks like the it wasn't fixed upstream ;)

**Comment by tedyun** [comment]
+1 Windows 7 x64 SP1, Atom 0.209.

This issue was fixed for a while, then it re-appeared in ver 0.209. Please reopen this issue.

**Comment by 50Wliu** [comment]
This issue is not going to be reopened.  Instead, please subscribe to #7231 if you're experiencing windows not reopening on 0.209.0.

**Comment by jlbooker** [comment]
+1 on Fedora 20, Atom version 0.209.0

Tried launching with `atom` and `atom --safe`. Neither remembers the project folders and open files from the last execution.

And worse, it seems the `save-session` package no longer implements this feature. It expects the core functionality to support this instead. So frustrating.
