### ISSUE TITLE
Option to load entire file into memory.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#6467]
There are times (like when we use Nautilus to edit files on our server) that it would be nice to load the entire file into memory to prevent any kind of lag (such as the lag we often receive with Atom Editor when editing these files.)

Can we please get an option (or detection) that allows us to load remote files into memory for efficiency?

**Comment by mark-hahn** [comment]
All files are loaded into memory right now.  Correct me if I'm wrong.

**Comment by envygeeks** [comment]
It could be, which means there might be a problem in another spot with the buffer.

**Comment by philipgiuliani** [comment]
Yes, currently the whole file should be in the memory what i know. Maybe this is also an issue which may be related https://github.com/atom/atom/issues/1766. Its maybe only lagging on a save?

@nathansobo @maxbrunsfeld :
Since you are currently developing https://github.com/atom/text-document where you will only load chunks into the memory, will this have a performance impact when working on a slow drive? (Network drive for example)? Than maybe an option to load the whole file would be great!

**Comment by envygeeks** [comment]
@philipgiuliani  There is no lag on our servers in SSH or GVFS so I don't believe it's that.  That aside it's not even saving when it's getting the lag, it's simply navigating the file, which is what led me to believe this is a buffer issue.

To add an extra note: Atom is using the same GVFS volume that Nautilus/Files (Ubuntu) is using the one that has no lag in Natuilus/Files but does in Atom, but this could very well somehow be a GVFS issue since it's not known to be the most friendly tbh.

**Comment by envygeeks** [comment]
To add a second extra note: It actually saves instantly when I do save.

**Comment by maxbrunsfeld** [comment]
Currently, we do load the entire file into memory. In the future, our plan is to avoid loading entire files into memory, but only if for very large files. And even then, we'll need to copy the file to a local tempfile to ensure that the editing experience remains consistent in the event that the file is modified outside of Atom.

@envygeeks If you get a chance, could you record a CPU profile (`Profiles > Collect CPU Profile` in the dev tools) when you're experiencing this lag? If you can find the function that's taking a long time to run, or upload a screenshot of your flame graph, we'll be able to track the problem down.

**Comment by envygeeks** [comment]
@maxbrunsfeld I like that idea, as long as we can modify where the file buffers too!  That said I'll do a profile later tonight since we have a bunch of remote configs that we need to edit.

**Comment by envygeeks** [comment]
This issue is no longer relevent to me so if nobody wants it open I'll close it, we just built an addon but I still think it might be an issue for other people who do not know JavaScript or do not trust other SFTP addon's that are not core [I know I didn't that's why I built my own.]

If you guys do not wish to resolve this I'll close it.

**Comment by maxbrunsfeld** [comment]
Ok. I'm still curious what was causing the lag you experienced, but I'm ok closing this for now too.

**Comment by envygeeks** [comment]
I'll attach myself to an sftp node later tonight on Fuse and track every call that Atom makes and post it.

**Comment by maxbrunsfeld** [comment]
:+1: Thanks @envygeeks!
