### ISSUE TITLE
CPU is constantly using about 4-5% , it was around 1-2% back in 0.192

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#6471]
After upgrade to 194 today , i found CPU usage increased during idle .  
I have tested using atom --safe .
I think it has to do with Cursor blinking not rendered using GPU ?
It is more evident especially using atom-block-cursor: https://github.com/olmokramer/atom-block-cursor/issues/15 , cpu usage jumps to 10-12 % 
Back in 0192 , even with atom-block-cursor pulsating (easing) animation of cursor , cpu do not consume more than 5%, averaging around 2%

**Comment by deepsweet** [comment]
same here, 5-6%.

**Comment by v3ss0n** [comment]
@deepsweet  thats without atom-block-cursor right?

**Comment by deepsweet** [comment]
right.

**Comment by as-cii** [comment]
Cursors are now on their own layer and #8009 should have decreased CPU usage as well.

Are you still observing this? If not, do you think we can close it? :sparkles:

**Comment by benogle** [comment]
Closing as there have been several improvements related to this. If this is still an issue please comment.
