### ISSUE TITLE
Change sidebar in Right 

### ISSUE THREAD

**Issue by tanvirraj** [atom/atom#6483]
i want to change sidebar from left to right 
 where all the files are open , 
how can i do that

**Comment by mnquintana** [comment]
1. Go to Settings
2. Click Packages
3. Search for `tree-view`
4. Click "Show on Right Side"

Hope that helps!

**Comment by tanvirraj** [comment]
Thanks man !!

**Comment by martinbuezas** [comment]
At some update the _Show on Right Side_ option was removed - but you can just drag it now.
