### ISSUE TITLE
Selecting text with option + shift + arrow behaves differently to other Mac apps

### ISSUE THREAD

**Issue by gregplaysguitar** [atom/atom#6485]
Atom doesn't seem to follow Mac convention in certain cases. To reproduce:
1. Double click to highlight a word
2. Option + shift + left arrow
- In other apps, both words are now selected.
- In atom, the selection is cleared and the cursor is now at the start of the original word.

Similarly, if the 2. is replaced with command + shift + left arrow, in Atom the extended selection doesn't include the originally selected word as it would in other apps.

(This is clearly a minor issue; but it's frustrating if you're used to this pattern. Atom is fantastic overall!)

**Comment by gregplaysguitar** [comment]
On further thought, I think the underlying issue is that when you add to a selection on other Mac editors, it's always assumed that the selection should get bigger not smaller. Atom assumes the cursor is at the start of the selection though, so if trying to select text before the original selection, the original selection disappears. Another manifestation:

1. Triple click a line 
2. Shift + up arrow

- In other apps, two lines are now selected - the original and the one above
- In Atom, nothing is selected, and the cursor is at the start of the originally selected line

**Comment by izuzak** [comment]
Just wanted to mention that there's a similar discussion about this over at https://github.com/atom/atom/issues/6928#issuecomment-104998517 (issue which I just closed in favor of this one).

**Comment by nathansobo** [comment]
I'll add this to the quality initiative. Selection behavior should conform to expectations. We also have some subtle differences when double-click-dragging between words.

**Comment by jaepage** [comment]
+1 for fixing this please. 

No clicking is required as described by OP above. Default Mac OS behavior is that <kbd>option</kbd><kbd>arrow-key</kbd> will move the cursor by words rather than characters, and that adding <kbd>shift</kbd> will highlight by words rather than characters. 

So what is Atom trying to do instead, and can this be fixed immediately via app prefs or app keymap?

Thank you.

**Comment by jaepage** [comment]
Could this issue also be labelled as a bug rather than an enhancement, since it breaks OS convention?

**Comment by jaepage** [comment]
I'll delete my two comments above, as it seems the bug I was experience can be resolved by disabling `es-identifier-highlight` package. Thank you.

**Comment by bronson** [comment]
That's too bad.  This really does seem like something that should be fixed.

**Comment by jaepage** [comment]
I've since given up on Atom. Unsubbing. Good luck.

**Comment by nathanielperales** [comment]
I second this issue. I use alt + shift + left arrow & right arrow all the time to extend the selection by word. I definitely think this should be fixed. Or maybe someone can explain how to enable this in the settings or create a plugin. Thanks!

**Comment by chrisjshull** [comment]
Triple-clicking and "Select Line" also work "incorrectly" for a Mac app. For both, the selection should not include the newline char at the end of the line (cursor should be at the very end of the selected line).
(Would it be better to file a separate ticket, or lump Mac selection bugs together here?)

**Comment by bronson** [comment]
triple-clicking sounds like a separate issue.

**Comment by brettz9** [comment]
This issue is really big for Mac users--being able to select whole words at a time (without the whole line) is very useful...
