### ISSUE TITLE
Crystal support

### ISSUE THREAD

**Issue by Ap0ph1s** [atom/atom#6486]
What do you guys think on adding Crystal syntax highlighting support for Atom?

http://crystal-lang.org/

Maybe the sublime text lib might help? https://github.com/manastech/sublime-crystal

**Comment by thedaniel** [comment]
It probably isn't used widely enough to be included in core, but it looks like there are [two different crystal language packages](https://atom.io/packages/search?q=crystal) on atom.io

**Comment by Ap0ph1s** [comment]
Thanks! didn't seem them :P

**Comment by k2b6s9j** [comment]
I wrote the language-crystal-actual package, it's a little buggy but it's mostly trivial things. The thing that counts is that it's better than using the Ruby language for Crystal.

The real reason I dropped in here is to alert anyone looking for Crystal support in Atom. The language-crystal package you will initially find has been abandoned by the author, who never removed his package from the package manager.
