### ISSUE TITLE
"Unhandled promise rejection" no longer shows up in the console.

### ISSUE THREAD

**Issue by bolinfest** [atom/atom#6488]
This is a regression. Up to and including Atom v0.188.0, if you had code like:

```coffee
setTimeout(
  () -> Promise.reject('haha rejected'),
  0)
```
you would discover your error via the following in the console:

```
Unhandled promise rejection Promise
     __proto__: Promise
    [[PromiseStatus]]: "rejected"
    [[PromiseValue]]: "haha rejected"
```

which you could use to help debug your issue.

As of Atom v0.189.0, you see nothing. You can have chains and chains of `Promise.then()`, and if there is a failure in the middle, you now have no idea and have to start adding `.catch()` calls everywhere. It's madness.

I don't know what specifically causes the change, but here's what I have discovered thus far:
* Atom v0.189.0 (Apr 1) is built on atom-shell v0.22.3 (Mar 29) whereas Atom v0.188.0 (Mar 24) is built on atom-shell v0.21.3 (Mar 3).
* atom-shell v0.22.0 mentions **Upgrade to Chrome 41** in its release notes.
* https://github.com/iojs/io.js/pull/758 is a PR with a massive history, which I will not even to pretend to have read, but I believe it was closed on Feb 24 and it includes the following text in its initial comment:

> Implement unhandled rejection tracking for promises as
> specified in https://gist.github.com/benjamingr/0237932cee84712951a2
>
> Fixes https://github.com/iojs/io.js/issues/256
>
> Note that I did not implement any default action - so errors are still
> swallowed by default and many developers are therefore not going
> to discover the hooks.

Seems suspicious.

**Comment by thomasjo** [comment]
Seems like the logging of these messages might need to be specifically handled now:
https://github.com/iojs/io.js/blob/10e31ba56c676bdcad39ccad22ea9117733b8eb5/doc/api/process.markdown#event-unhandledrejection

> Here is an example that logs every unhandled rejection to the console
```
process.on('unhandledRejection', function(reason, p) {
    console.log("Unhandled Rejection at: Promise ", p, " reason: ", reason);
    // application specific logging, throwing an error, or other logic here
});

Unsure whether this should be handled in Atom or Electron though. Thoughts?

**Comment by paulcbetts** [comment]
This should be in Electron so that we are consistent with what Chrome does

**Comment by bolinfest** [comment]
The original behavior even had some semblance of a stacktrace that could aid in your debugging. I'm pretty sure the only reason you don't see one in my example because it was spawned from a `setTimeout()`.

Assuming I'm not making things up about the stacktrace, it would be great if we could preserve that behavior. I'm not sure what the actual API we have for handling this is.

**Comment by paulcbetts** [comment]
@bolinfest `chrome.error(e)` will do it

**Comment by bolinfest** [comment]
@paulcbetts Yes, but I don't see an `Error` object in the example that was posted:

```
process.on('unhandledRejection', function(reason, p) {
    console.log("Unhandled Rejection at: Promise ", p, " reason: ", reason);
    // application specific logging, throwing an error, or other logic here
});
```

**Comment by paulcbetts** [comment]
@bolinfest Isn't `reason` of type `Error`?

**Comment by bolinfest** [comment]
@paulcbetts Oh, perhaps it is! I'm pretty sure I have never named a JavaScript `Error` anything other than `e`, `err`, or `error`. To me, `reason` implies that it's a string. Bad assumption on my part.

**Comment by bolinfest** [comment]
OK, I just sent out a PR: https://github.com/atom/atom/pull/6497

I manually verified that this works.

**Comment by bolinfest** [comment]
Closed by https://github.com/atom/atom/pull/6497
