### ISSUE TITLE
double pointer a few lines apart with duplicate editing

### ISSUE THREAD

**Issue by evanx** [atom/atom#6490]
![atom-double-pointer](https://cloud.githubusercontent.com/assets/899558/7293793/24f0cde0-e9a8-11e4-827f-d41edbf6b10d.png)

somehow a double pointer gets created e.g. 12 lines below the line i am editing - e.g. see lines 89 and 101 in attached screenshot

the effect is that editing actions you are doing on one line, are repeated in the other line

this happens two or three times a week

Atom 0.192.0
Ubuntu 14.04.2 LTS

**Comment by Tribex** [comment]
@evanx This is a feature, not a bug, it happens when you CTRL+Click.

There are some pretty neat things such a feature can do!

**Comment by evanx** [comment]
oh, ok - thanks!
