### ISSUE TITLE
Support OSX's 'Option + Command + Q' to quit the app without saving the application state

### ISSUE THREAD

**Issue by lukehefson** [atom/atom#6495]
I loved https://github.com/atom/atom/issues/1603! Thank you so much for adding it!

However, as far as I can tell, there is now currently no way to quit the Atom _without_ saving the application state.

Most OSX apps support the native menubar/shortcut for `Quit and Close All Windows` (hold down option to see it in the menubar):

![untitled](https://cloud.githubusercontent.com/assets/1469659/7299076/9374b07e-e9cb-11e4-883d-10dedb4bcd77.png)

It would be great if Atom supported it too! This way, if I know that I don't want to open the same project next time I can just `⌥ ⌘ Q` out of it.

**Comment by mnquintana** [comment]
Huh, I see the opposite command when holding <kbd>Option</kbd>:

![_and_menubar](https://cloud.githubusercontent.com/assets/823545/7300004/3c2cb8ee-e9a7-11e4-9467-f39edc0fb5bc.png)

Nonetheless, I still think this would be a useful enhancement. :+1:

**Comment by lukehefson** [comment]
@mnquintana it sounds as though you probably have the 'Close windows when quitting as app' pref selected already then:

![screen shot 2015-04-23 at 16 05 11](https://cloud.githubusercontent.com/assets/1469659/7300195/b507bb8a-e9d2-11e4-9be0-4e9986b911d8.png)

**Comment by lee-dohm** [comment]
There are now a couple ways to achieve this general type of thing in a cross platform way:

* The setting to disable restoring the last session
* The `--clear-window-state` option when starting the application

Because of this, we're not going to be adding this feature anytime soon. We might revisit it in the future though.
