### ISSUE TITLE
Atom crashes with C-v C-p copy paste from/to other apps in Ubuntu 14.10

### ISSUE THREAD

**Issue by ddaza** [atom/atom#6504]
I recently updated to the newest atom 0.194 and the clipboard works with right click copy/paste but the keyboard shortcuts are not working correctly, and make atom crash.

Included is the crash stack trace: 
```
ProblemType: Crash
Architecture: amd64
CrashCounter: 1
CurrentDesktop: Unity
Date: Thu Apr 23 22:14:16 2015
DistroRelease: Ubuntu 14.10
ExecutablePath: /usr/share/atom/atom
ExecutableTimestamp: 1429668090
ProcCmdline:
 /usr/share/atom/atom --eval require('/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js').setCacheDirectory('/home/myuser/.atom/compile-cache/coffee');
 require('/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js').register();
 require('/usr/share/atom/resources/app.asar/node_modules/coffeestack/index.js').setCacheDirectory('/home/myuser/.atom/compile-cache/coffee/source-maps');
 require('/usr/share/atom/resources/app.asar/src/task-bootstrap.js');
ProcCwd: /home/myuser
ProcEnviron:
 LANGUAGE=en_US
 TERM=xterm-color
 PATH=(custom, no user)
 XDG_RUNTIME_DIR=<set>
 LANG=en_US.UTF-8
 SHELL=/bin/bash
```

**Comment by envygeeks** [comment]
Any status update on this because we were about to update our Atom images and our build server flagged this issue as a possible regression for me to look at and refused to build.  So I just wanted to double check it's a potential problem.

**Comment by zcbenz** [comment]
This is weird, copy-pasting with keyboard and context menu should call the same code.

**Comment by ddaza** [comment]
That makes sense. Maybe is the fact that with keyboard shortcuts you can fire the process multiple times and faster than the context menu. 
![screenshot from 2015-04-28 21 51 39](https://cloud.githubusercontent.com/assets/290254/7384119/ae8d0184-edf1-11e4-8222-92c0ef6b2822.png)

For extra info I have added the screenshot of the crash. Notice it mentions hunspell. 
This only happens when I paste/copy multiple times in a short amount of time.

**Comment by zcbenz** [comment]
@ddaza Is the editor window still running after the crash dialog?

**Comment by ddaza** [comment]
@zcbenz  Technically, yes it still runs. 
But, sometimes it becomes unresponsive and sluggish.

**Comment by envygeeks** [comment]
Could this be a regression of what happened last time?
