### ISSUE TITLE
Atom displays two Icons in the taskbar under Windows 10

### ISSUE THREAD

**Issue by skeleten** [atom/atom#6506]
Windows Version 10.0.10041
Atom Version 0.147.0

Atom currently displajys two taskbar Icons. They both behave normally and in the same way.
I did not notice this behaviour in any other editor (such as gVim, emacs, notepad++, etc.) or in any other program yet.

[Screenshot](http://i.imgur.com/3i3TNPe.png)

**Comment by mnquintana** [comment]
You're running an extremely old version of Atom – would you mind updating to the latest version (0.194.0) and see if you still experience this issue? You may need to uninstall your existing version first and reinstall with the latest installer.

**Comment by skeleten** [comment]
It was inconsistent with the version I was using also, it seemed to appear randomly. I've updated for now and will comments once I get it to reproduce again

**Comment by paulcbetts** [comment]
We fixed this bug in Squirrel a looooong time ago, this should be good. Reopen if you see it on the latest version.
