### ISSUE TITLE
Crashing on Windows 8.1 -- on paste

### ISSUE THREAD

**Issue by Davidx7** [atom/atom#6507]
Big bug, simple to replicate.
Open a folder, create a new JS file, and paste a relatively large amount of code in it, in 1 single paste. 
I pasted mathjs.js lib, ctrl + c raw from the website and ctrl + v in atom and it spikes up the CPU usage and eventually crashes. 

Also tried running it in Admin mode, same thing, no difference.

Update :: 
And on opening any large JS files, same thing. CPU usage goes up, editor freezes and eventually Atom crashes.
I tested also with a simple version of Atom, no plugins, just default install, same thing.

**Comment by kevinsawicki** [comment]
What version of Atom are you using?

**Comment by kevinsawicki** [comment]
Closing this out as something that was most likely fixed by the many performance optimizations done leading up to Atom 1.0 last month.

Please comment if you still see this happening on Atom 1.0.3+.
