### ISSUE TITLE
Running "download-atom-shell" task never completes

### ISSUE THREAD

**Issue by slackmoehrle** [atom/atom#6508]
OS X 10.10.3, latest atom from GitHub. Stalls.......I let it sit for 8 hours..

$ script/build
Node: v0.12.2
npm: v2.5.1
Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓
Running "download-atom-shell" task
^C

**Comment by izuzak** [comment]
@slackmoehrle Strange, I'm not seeing that problem on OSX 10.10.3, same version of node and npm, latest master version of Atom (14161a6). Can you confirm which version of Atom you're trying to build exactly (commit sha)? Also, are you still seeing this problem -- might have been something temporary?

**Comment by slackmoehrle** [comment]
I pulled again this morning and it built after 52 mins.

**Comment by mnquintana** [comment]
@slackmoehrle Were you having any internet connectivity issues? It sounds like it might've just been a really slow download.

**Comment by slackmoehrle** [comment]
Not that I know of. Other things were going just fine. I can try the whole build again and see. I'd consider this closed for now.

**Comment by izuzak** [comment]
Cool, thanks for letting us know, @slackmoehrle.
