### ISSUE TITLE
A Javascript error occured in browser process - window 7 

### ISSUE THREAD

**Issue by skandasoft** [atom/atom#6512]
![image](https://cloud.githubusercontent.com/assets/9875379/7329857/698562d8-eaaa-11e4-969d-9f204eac2b9c.png)

**Comment by skandasoft** [comment]
I cannot open atom. I was uninstalling a package while I was in that folder. It Uninstallion incomplete. I restarted. I started getting this error.  Removed the entire atom folder and tried reinstall. While install also I am getting the same error

**Comment by skandasoft** [comment]
It happens even if tried to install using chocoloatey..is there a cache some place.because i delete all the atom from appdata/loca and appdata/roaming..and the temp folder and the .atom folder..

**Comment by 50Wliu** [comment]
@skandasoft is your Windows username `Administrator`?  Just want to make sure Squirrel isn't doing something weird.

**Comment by 50Wliu** [comment]
No response, closing until more information can be provided.
