### ISSUE TITLE
No scrolling on Linux Mint

### ISSUE THREAD

**Issue by shotlom** [atom/atom#6513]
I can't get any of my scroll bars to work on Linux mint so I have to use my cursor to move up and down a document ... old school.

**Comment by 50Wliu** [comment]
Hi @shotlom, some quick questions for you: what Atom version is this?  Can you reproduce this in safe mode (`atom --safe`)?  If not, please paste the output of `apm list --installed`.  Thanks! :smile:

**Comment by shotlom** [comment]
v: 0.194.0

'atom --safe': killed my vm

apm list --installed
/home/adminuser/.atom/packages (14)
├── Stylus@1.0.0
├── color-picker@1.7.0
├── fixmyjs@1.3.2
├── git-projects@1.13.0
├── jscs-fixer@0.3.0
├── jshint@1.3.4
├── linter@0.12.1
├── linter-cpplint@0.1.4
├── linter-jscs@1.10.0
├── merge-conflicts@1.3.1
├── minimap@4.7.6
├── minimap-git-diff@4.1.2
├── pandoc@0.1.3
└── terminal-panel@1.10.0


On Sat, Apr 25, 2015 at 11:00 AM, Wliu <notifications@github.com> wrote:

> Hi @shotlom <https://github.com/shotlom>, some quick questions for you:
> what Atom version is this? Can you reproduce this in safe mode (atom
> --safe)? If not, please paste the output of apm list --installed. Thanks! [image:
> :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/6513#issuecomment-96113870>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by kevinsawicki** [comment]
@shotlom are you still experiencing this on Atom 1.0.3+?

**Comment by shotlom** [comment]
I've ditched Atom for sublime text2 because of this issue and a few other
performance issues which made Atom slow.

On Thu, Jul 30, 2015 at 3:02 AM, Kevin Sawicki <notifications@github.com>
wrote:

> @shotlom <https://github.com/shotlom> are you still experiencing this on
> Atom 1.0.3+?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/6513#issuecomment-126018987>.
>



-- 
Mr Sholto Maud

mobile: +61 (0) 424 094 227
email: sholto.maud@gmail.com
skype: sholtomaud

**Comment by charleswhchan** [comment]
I am using Atom 1.0.8 on Linux Mint 17.1 Rebecca in a VirtualBox VM:
* scrollbar *doesn't* work if "Mouse Integration" is enabled
* scrollbar *does* work if "Mouse Integration" is disabled

(maybe related to issue #6219)

**Comment by mnquintana** [comment]
Thanks for the update! This seems like another Electron + VMs issue that should be resolved when https://github.com/atom/atom/pull/7877 is merged.

**Comment by charleswhchan** [comment]
Thanks for the info! I use Atom in VM all the time, so I am definitely looking forward to the upgrade!

**Comment by petebachant** [comment]
I am having the same issue on Linux Mint in a VirtualBox VM, except highlighting text is also not possible.

**Comment by charleswhchan** [comment]
@petebachant yes, there are problems with text selection inside VM. See #6513, #7704
