### ISSUE TITLE
[feature] Hide *.js files from sidebar if it's *.coffee source exists

### ISSUE THREAD

**Issue by f1nnix** [atom/atom#6515]
I'm using [coffee-compile](https://atom.io/packages/coffee-compile) plugin to compile *.coffee files on save. Unfortunately, it does not provide options to choose where to store compiled files. It just creates *.js file near the original coffee one. If directory has over 10 coffee files, sidebar will be messed with 20 files (10 pairs, 1 coffee and 1 js for each pair), that may disturb the developer.

It would be nice if Atom has option to hide *.js file if there's *.coffee file with the same name. It may look like coffee file with dropdown arrow, js file is shown as subtree by click. It works the same way in JetBrains WebStorm.

![screen shot 2015-04-25 at 14 38 10](https://cloud.githubusercontent.com/assets/3099788/7332802/b9eb46d2-eb5b-11e4-9747-41c155c41150.png)

Another approach is to use `coffee-script` tool directly, compiling app to separate directory `./build`, but it has two major issues:

* you always need to have another terminal session started
* this ruins one-window Atom workflow

So, is there any exiting plugin that may do the trick?

Thank you!

**Comment by lee-dohm** [comment]
This issue was moved to atom/tree-view#431
