### ISSUE TITLE
Crash when deleting a file

### ISSUE THREAD

**Issue by 1j01** [atom/atom#6520]
After I delete a file, sometimes the dialogue doesn't go away.
Further interaction causes atom to crash.

One or two times it froze (i.e. not responding):
![atom crashed](https://cloud.githubusercontent.com/assets/3630663/7339054/d8713638-ec2e-11e4-9578-8a2bc77d4c2e.png)
But usually it just closes instantly:
![sircrashalot](https://cloud.githubusercontent.com/assets/3630663/7339050/c9277782-ec2e-11e4-9c96-2d28e10c6ee0.gif)
![sircrashalotthethird](https://cloud.githubusercontent.com/assets/3630663/7339051/c9297ffa-ec2e-11e4-9647-b71424af3872.gif)

**Comment by izuzak** [comment]
@1j01 Thanks for the report. May I ask which version of Atom you're using exactly, which version of Windows, and if you can reproduce this problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Also, did this problem start happening recently or have things always been like this? Did you notice any other patterns related to this problem which might help us investigate? (E.g. it only happens for large files)

**Comment by 1j01** [comment]
There's no `atom.VERSION` or `atom.version`, **Application: About** does nothing, **Window: Update Available** does nothing, and **Application: Install Update** closes Atom, so I have to reopen everything...

Here's `process.versions`:
```yaml
atom-shell: "0.21.0"
chrome: "40.0.2214.91"
http_parser: "2.3"
modules: "41"
node: "1.0.0-pre"
openssl: "1.0.1j"
uv: "1.2.0"
v8: "3.30.33.15"
zlib: "1.2.8"
```

I'm on Windows 8.1. I guess it started happening semi-recently.
Here's a similar issue: https://github.com/atom/atom/issues/3198

...Oh! **Release Notes: Show** shows that I'm (probably?) on version 0.182.0 (it still doesn't explicitly say so, that's just the first listed version)

Why am I not on the latest version?

**Comment by 1j01** [comment]
At any rate, I see some things that could possibly be related in the release notes:
* Fixed a regression where the cursor position was not being restored after undo in some cases
* Fixed issues adding selections above and below in the presence of hard tabs or soft-wrapped lines.
* Fixed issues soft-wrapping lines that contained tabs in their leading whitespace.

And since you can't reproduce it I'll presume this is fixed.

**Comment by lee-dohm** [comment]
@1j01 You should be able to find out the version you are actually running by running `atom --version` from the command line. Also, if it turns out that you are running a more recent version than v0.182.0, you might check out [this topic](https://discuss.atom.io/t/atom-auto-updater-not-working/16375) on Discuss for ideas on how to fix it.

**Comment by 1j01** [comment]
```
C:\Users\Isaiah>atom --version
[5276:0428/004459:INFO:CONSOLE(0)] 0.182.0
```
So, any idea why it's not updating/finding updates?

**Comment by lee-dohm** [comment]
I would have guessed that it might be due to this:

http://blog.atom.io/2014/12/10/a-windows-installer-and-updater.html

Note the uninstalling Chocolatey part, if you are or were using Chocolatey for your Atom install. But that was back in December when it was released and 0.182.0 was released in February.

/cc @paulcbetts

**Comment by 1j01** [comment]
I installed it with the nice installer on this machine, so I don't have chocolately installed.
Should I just reinstall? Or should I wait and perhaps perform some diagnostics?

**Comment by 50Wliu** [comment]
I don't think `[5276:0428/004459:INFO:CONSOLE(0)]` should be included in the output-I don't remember seeing that whenever I tried `atom --version`, even on Windows.

**Comment by 50Wliu** [comment]
@1j01 Can you still reproduce this on Atom 1.7.3?

**Comment by 1j01** [comment]
@50Wliu I don't think so. (I think I'll try using atom again.)
