### ISSUE TITLE
Ctrl+Shift+M does not work in GNOME 3

### ISSUE THREAD

**Issue by crazyh** [atom/atom#6532]
Ctrl+Shift+M shortcut (Markdown Preview: Toggle) does not work in GNOME (3.16, Arch Linux, Logitech keyboard).

How to reproduce:

1. Install Arch Linux
2. Install full GNOME with GNOME Shell
3. Run Atom and open any MD file
4. Press Ctrl+Shift+M

=> Nothing happens

**Comment by izuzak** [comment]
Which version of Atom are you using? What do you see in the [keybinding resolver](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings) when you press ctrl-shift-m (please provide a screenshot)?

**Comment by crazyh** [comment]
@izuzak Atom 0.194.0

Well, I discovered that Emmet package uses the same keybinding. Thank you for pointing to  keybinding resolver. =)
