### ISSUE TITLE
UX - Cannot drag project folder into tree-view

### ISSUE THREAD

**Issue by jsphstls** [atom/atom#6535]
**To reproduce:**
Open Atom and clear any project folders or open files.
Open Finder and drag then drop a folder into the Atom tree-view.

**Current result:**
Project folder will not be added to tree-view.

**Expected result:**
Project folder would be added to tree-view.

**Suggested change:**
Allow project folders to be dragged into tree-view.

It is odd that you cannot add a project folder this way since the tree-view is where project folders are navigated. Instead, you can drag a folder into an editor pane, which is where individual files are edited.

**Comment by andrewrothman** [comment]
I also find this odd. Definitely tried it a few times with frustration before realizing it couldn't be done.

**Comment by mnquintana** [comment]
This issue was moved to atom/tree-view#480
