### ISSUE TITLE
Feature request: Create multiple files at once

### ISSUE THREAD

**Issue by mkoske** [atom/atom#6537]
Hello, and thanks for the great editor. I just thought that it would be nice to allow user to create multiple files at once, like typing {one,two,three}.txt into create file "dialog" and it would create one.txt, two.txt and three.txt

Thanks,
Miika

**Comment by sedabull** [comment]
@mkoske, I took an interest in this idea about a week ago and have just finished a new package called `new-file-plus` that supports exactly this. Check it out and let me know what you think!

**Comment by mkoske** [comment]
Hello, and thanks! It seems to work. One suggestion though... attach it to context menu "New file" too. I mean, when you click "New file" on file browser panel, it is the default "New file", not the extension you wrote.

Thanks,
Miika

**Comment by sedabull** [comment]
On my system (Ubuntu 14.04) navigating to `File>New File` opens `new-file-plus`. Could you try completely closing and reopening Atom to see if that fixes it? If it doesn't could you open an issue [here](http://github.com/sedabull/new-file-plus/issues) with your OS, atom version, etc?

**Comment by mkoske** [comment]
Hello, yes it works. But I meant that when you have file tree on the left side of Atom window, and when you right click there, in the file  tree, and get the context menu, choose "New file" from there, you get the normal new file, not `new-file-plus`.

**Comment by sedabull** [comment]
Aww, i see. i will look into that later tonight



—

**Comment by sedabull** [comment]
@mkoske, I was unable to completely overwrite the `New File` and `New Folder` commands, however I have added my own `New File(+)` and `New Folder(+)` commands that should work as expected. Let me know if you have any problems.

**Comment by batjko** [comment]
Is it worth keeping the issue open as request for Atom core, or does @sedabull's package satisfy the request?

I think it would make sense as an enhancement to the default file and folder creation logic, but the core devs may see that differently.
