### ISSUE TITLE
LICENSE.md is user-editable and saveable

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#6552]
So, currently LICENSE.md opens as a regular text buffer, but as a result of this, it's editable and even saveable just like any other regular text buffer. Sure, it'll be wiped on upgrades (I would think), but it does seem a little strange that Atom makes it so easy to edit the contents of all of its licenses. Not sure about the best way to handle this - maybe just opening the Markdown Preview version (assuming it's not disabled), and falling back to a buffer if it is disabled? Is there another way we can prevent saves?

**Comment by mark-hahn** [comment]
A contract isn't changed if you change the document unilaterally.  Any
change has to be agreed to by both parties.  If you change a license
document it means nothing.  You are on your own.

**Comment by izuzak** [comment]
@mnquintana Can you explain what problems exactly this ability to edit the license might cause? What @mark-hahn said makes sense to me, but I noticed that you didn't clarify why you thought this was a problem in your issue report and would love to hear that (especially related to what @mark-hahn said). Also, would you consider this a problem if you download Atom's source, change the LICENSE, and then build it? If not, what's the difference?

**Comment by mehcode** [comment]
I agree with @mnquintana. My reasoning is that atom should be presenting what most of the users are after most of the time. 9 times out of 10 if I open the `LICENSE.md` file it is to read it (not edit). The other time is to update the year on the copyright.

**Comment by mark-hahn** [comment]
> atom should be presenting what most of the users are after most of the time

So are you suggesting it should not be possible to edit a license file because you usually don't edit it?  What about the times you *do* need to edit it?  Also, how can Atom know what files are license files?

**Comment by thomasjo** [comment]
I'm massively :-1: on this proposal. We should not be treating some files, ultimately plain text files, differently just because they happen to be a license document. This is a slippery slope, and will also cause confusion.

**Comment by mehcode** [comment]
I'm not saying atom should block editing. That'd be strange. 

I'm just suggesting a "LICENSE editor" that by default just renders the markdown with some way to toggle back/forth between the render and the plain text version (to edit it). Another feature of this license editor is it could compare the license to a bunch of different licenses and say if its boilerplate MIT / GPL / BSD / etc. Of course all this could be a package.

**Comment by mark-hahn** [comment]
> Of course all this could be a package.

Yes.  I doubt many people care, or even agree with the concept.  Most users
never read licenses.

**Comment by paulcbetts** [comment]
> I'm massively :-1: on this proposal. We should not be treating some files, ultimately plain text files, differently just because they happen to be a license document. This is a slippery slope, and will also cause confusion.

^^ This

**Comment by mnquintana** [comment]
Incidentally, https://github.com/atom/atom/issues/6880 is exactly what I had in mind here – just set the editor to read-only mode for the LICENSE.

**Comment by thomasjo** [comment]
![image](https://cloud.githubusercontent.com/assets/3622/7779592/2bbb081c-00d6-11e5-94c1-5893d7ce557a.png)

I'm still :-1: on this. Sorry.

**Comment by bronson** [comment]
I would be absolutely infuriated if my text editor refused to edit some text files.  And, if accidental edits are your concern, I'd be a lot more worried about code files than license files.  A LOT more worried.

I agree with @mehcode, make it a package.  People might like it.

**Comment by mnquintana** [comment]
Alright, I think I've gotten enough feedback on this now to call it not worth it. :see_no_evil:
