### ISSUE TITLE
Windows Dev Tools - Scripts no longer organized

### ISSUE THREAD

**Issue by sgwill** [atom/atom#6553]
I'm on Windows 8.1 pro, using Atom 0.194. The Dev Tools / Scripts section no longer organizes the scripts by package, which means finding and debugging packages is more difficult.

Here's a screenshot: http://i.imgur.com/Fi4NEZJ.png

I did try completely uninstalling and re-installing, without adding any of the packages I'd installed, just to see if that would clear the issue. It did not.

The Dev Tools works as expected on my mac, and worked as expected on Windows in earlier versions of Atom.

**Comment by lee-dohm** [comment]
It looks like they're organized by package to me. All those files except the first one all are in the `atom-typescript` package it looks like. What is missing?

**Comment by izuzak** [comment]
Ha, beat me to it, @lee-dohm. :speedboat: They look organized by package to me as well. I'm also not seeing anything weird on my Win 8.1 install of Atom.

**Comment by sgwill** [comment]
That's actually one long list of all files, alphabetically. The screenshot only shows `atom-typescript`, but the list includes all packages, plus Atom files. I'll grab a screenshot of my mac version to show the difference...

**Comment by sgwill** [comment]
Here's a screenshot of my Mac. I have the same packages installed, and I'm working on the two that appear listed.

![screen shot 2015-04-28 at 9 44 17 pm](https://cloud.githubusercontent.com/assets/1507077/7383579/ecd027b6-edef-11e4-8830-b9464726fae8.png)

Perhaps a better question is, why do those appear in a nice tree on my mac, but not on my windows box. I checked another friend's windows box, and his didn't show them either.

**Comment by lee-dohm** [comment]
I don't have a Windows machine available to try to reproduce this in other places, but maybe you could go to https://discuss.atom.io on Windows and look at the Sources to see if you get something like this?

![screen shot 2015-04-29 at 7 25 25 am](https://cloud.githubusercontent.com/assets/1038121/7393147/09f217cc-ee41-11e4-8175-8a4054368cb9.png)

I don't think Atom customizes the Chromium Developer Tools at all, so I strongly suspect this is just a platform difference from there. But I could be wrong too :grinning:

**Comment by sgwill** [comment]
Yep, I get that same tree on Windows:

![untitled](https://cloud.githubusercontent.com/assets/1507077/7397073/f8dafd68-ee73-11e4-8ee9-db782c945328.png)

**Comment by izuzak** [comment]
Ahh, thanks for clarifying, @sgwill -- I misunderstood what you meant by "organized" (I assumed sorted, you meant shown in different "folders"). 

I see the package-related files in Windows, but only for packages which are linked into Atom (using `apm link`, not the ones which we're installed with `apm install` or through Settings View. I see the same behavior on OSX. 

![screen shot 2015-04-30 at 17 18 33](https://cloud.githubusercontent.com/assets/38924/7416326/cd86d6c8-ef5e-11e4-81af-4d9890b59fcf.png)


Is that perhaps the behavior you're seeing as well? Can you perhaps try linking some packages and see if that changes anything (use git clone to create a local clone, then `apm install` to install dependencies and then `apm link` to link the package).

**Comment by sgwill** [comment]
I tried that: removed `atom-yeoman`, re-cloned, `apm install`, and then `apm link`. Still no dice. The packages work, but they're still in one folder.

Now at least it's closer. Instead of being just in the (no domain) folder, they're in the `file://` folder, But, still in one long list. Nevertheless, that's better. I can still use `ctrl-o` to find the file fast enough.

![43f157ca3d0fb0792a2db576b962ab82](https://cloud.githubusercontent.com/assets/1507077/7416826/0cbffe0c-ef30-11e4-98f9-4df801d3faf6.gif)

Since Atom doesn't mess with the dev tools, is this better asked in Electron? Or, even, Chromium?

**Comment by izuzak** [comment]
@sgwill Interesting -- I tried linking two packages and both were in separate folders on Windows:

![screen shot 2015-04-30 at 18 22 54](https://cloud.githubusercontent.com/assets/38924/7417422/3aefd6fe-ef66-11e4-9e9e-0fdb802c3b23.png)

Where are you cloning packages to? From that GIF above, it _seems_ as if you are cloning them to the .atom/packages folder where other packages are installed normally as well. Can you try cloning to a different location (e.g. just your Users/username folder)?

Also, I'm definitely not sure how devtools behave and if any of this is expected behavior or not, so I'm gonna :pager: @zcbenz and @kevinsawicki just in case they know if anything changed and such.

**Comment by sgwill** [comment]
They're not actually in the ~/.atom/packages folder. Or, at least, `apm link` adds a linked folder to the packages folder.

![2015-04-30_1246](https://cloud.githubusercontent.com/assets/1507077/7417851/0e51f3c2-ef37-11e4-8535-298ba5c4789c.png)

**Comment by izuzak** [comment]
Okay, thanks for confirming. I'm surprised by these differences -- devtools shows linked folders separately for me (and with their real location). :confused:

**Comment by damieng** [comment]
The folders changed a lot recently with changes to npm, pre-building, snapshotting and embedded source maps.  The new layout should be much better.
