### ISSUE TITLE
Uncaught Error: spawn /Applications/Atom.app/Contents/Resources/app/apm/bin/apm EAGAIN

### ISSUE THREAD

**Issue by btm1** [atom/atom#6556]
[Enter steps to reproduce below:]

1. open atom
2. it hangs for a second and then it gives me a wall of errors file: child_process.js:747
3. then the editor crashes
4. it happens over and over again

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: spawn /Applications/Atom.app/Contents/Resources/app/apm/bin/apm EAGAIN

```
At events.js:141

Error: spawn /Applications/Atom.app/Contents/Resources/app/apm/bin/apm EAGAIN
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ],
    "disabledPackages": [
      "open-last-project"
    ],
    "followSymlinks": true
  },
  "editor": {
    "fontSize": 14,
    "fontFamily": "INCONSOLATA",
    "showIndentGuide": true,
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
angularjs-snippets, v0.10.2
atom-angularjs, v0.1.2
atom-grails, v0.1.0
atom-lint, v0.20.1
auto-update-packages, v0.2.2
autocomplete-plus, v2.12.0
autocomplete-snippets, v1.2.0
browser-refresh, v0.8.3
color-picker, v1.7.0
emmet, v2.3.8
jshint, v1.3.5
language-gitignore, v0.2.0
less-autocompile, v1.0.0
linter, v0.12.1
minimap, v4.7.6
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-selection, v4.2.0
monokai-seti, v0.7.0
project-manager, v1.15.5
save-session, v0.14.0
seti-ui, v0.6.3
slash-closer, v0.7.1
terminal-status, v1.6.6
tualo-git-context, v0.5.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Does it happen if you start Atom with the `--safe` command line option?

**Comment by btm1** [comment]
@kevinsawicki how do i do that?

**Comment by mnquintana** [comment]
@btm1 You can open Atom in safe mode by running `atom --safe` from the command line.

**Comment by btm1** [comment]
oh ok let me try that. Although honestly I'm not sure what has changed or how this could have happened. Everything was working fine yesterday.

![screen shot 2015-04-28 at 10 57 58 am](https://cloud.githubusercontent.com/assets/4110944/7376569/7f01398c-ed95-11e4-9f67-00cbd71f1003.png)

**Comment by btm1** [comment]
It doesn't seem to happen in safe mode.... is there any way of narrowing down what package is causing this? Or do i literally need to turn them all of and then sit there and turn them back on one by one?

**Comment by kevinsawicki** [comment]
Maybe start with `tualo-git-context` since it is in the first notification message.

**Comment by btm1** [comment]
yep it was indeed that package...

**Comment by btm1** [comment]
thanks for you help

**Comment by kevinsawicki** [comment]
Would it be possible for you to re-enable this package and click the Show Stack Trace link for the error that says "Uncaught Error: spawn /usr/libexec/PlistBuddy"?

That error does seem to be a bug in core Atom, can you take a screenshot and/or copy the stack trace displayed?
