### ISSUE TITLE
Atom crashes my system due to linux nVidia drivers

### ISSUE THREAD

**Issue by ronjouch** [atom/atom#6557]
_I originally asked this question in PR https://github.com/atom/atom/pull/2789 , but since I've been told on [atom-discuss/#13975](https://discuss.atom.io/t/disable-gpu-acceleration/13975) that `editor.useHardwareAcceleration` is deprecated, here's an issue._

I'm in a nVidia driver hell since upgrading to Ubuntu 15.04, and though Chrome's `--disable-gpu` does prevent it from crashing my whole system, Atom's (0.196) `editor.useHardwareAcceleration` doesn't, ending in a rather painful way: cursor jitter, screen flickering, regular keyboard/mouse input loss, impossible to switch to a non-X tty → restart with [REISUB](https://en.wikipedia.org/wiki/Magic_SysRq_key).

Is there a workaround or a way to be more drastic about disabling gpu acceleration like the Chrome flag does? Or is it too antagonistic to improving performance?

~~I'll be glad to provide debug info.~~ EDIT I no longer have access to the nVidia machine and can no longer help, unsubscribing from this issue I created.

**Comment by driehuis** [comment]
I'm having render artifacts with Atom. This is one of the manifestations of a bug in several Linux distro's, regarding compositing, that affects Chrome. This log winded bug report gives some background:
  https://code.google.com/p/chromium/issues/detail?id=370022

Seeing that Atom is built on top of Chrome, it comes as no surprise that this issue affects Atom as well.

RFE: Atom should expose Chrome's "Use hardware acceleration where available" setting.

**Comment by oraculus** [comment]
having the same problem, but with AMD driver (fglrx) on Kubuntu 15.04.
It happens randomly and I had the same issue with Brakets.io and Chromium Browser.
Arrived here searching for a way to disable hardware acceleration, as that fixed the bug on Chromium.

Please, please, please... make it possible to disable hardware acceleration.

**Comment by ronjouch** [comment]
Also, if anyone here has suggestions to find relevant logs and maybe report a bug to the distro / gpu vendor, I'm interested. I grepped my syslog/x11 logs unsuccessfully.

**Comment by oraculus** [comment]
I’m not really sure where we have to fill the bug, probably is a bug on Chromium as affects multiple distros, multiple GPUs and drivers (nvidia in your case, AMD in mine) and multiple applications but all have in common that are build using Chromium.

In my case the bug is not as catastrophic as in yours, my system don’t crash, is just the individual application that it gets so slow to the point that is unusable, for the symptoms I’m getting I would guess that has something to do with a bad vsync when using hardware acceleration. Closing and opening again Atom fixes the issue for a while. Maybe is a related but not the same bug (?)

**Comment by blufor** [comment]
Is there currently any way how to fiddle with settings usually accessible in chrome via chrome://flags/ ?

I'm running on i915 (2 hosts) and those glitches are really bugging me :/ 

**This really needs to be fixed somehow**, I've already dealt with saying goodbye to Terminus bitmap font ;)

**Comment by blufor** [comment]
...please :)

**Comment by driehuis** [comment]
I think this issue is getting less attention than it deserves because it has the label "question" attached to it. It should have the label RFE, but I think only the maintainers can add or remove labels. Maybe I should open a fresh issue with just the RFE oneliner from my comment above in it:

RFE: Atom should expose Chrome's "Use hardware acceleration where available" setting.

**Comment by blufor** [comment]
@driehuis Either RFE for that, or directly a bug for the glitch issue (but that's probably for the chrome devs, I guess :/)

**Comment by nahuel** [comment]
So, there is a way to pass "--disable-gpu" to the underliying chrome engine in Atom 1.0.7?

**Comment by oraculus** [comment]
Although is not the ideal solution, disabling the compositor at startup it seems to do the trick. At least if you use KDE, go to **System Settings > Display > Compositor** and uncheck the checkbox
 
![Disable Compositor](http://i.imgur.com/D4FrAsu.png)

**Comment by circunspecter** [comment]
In the issue linked by @driehuis, a user has posted a possible [solution/workaround for Intel graphics](https://code.google.com/p/chromium/issues/detail?id=370022#c83) users by changing the acceleration method.

I had the "redrawing" problem and, for the moment, has been fixed. A "Disable hardware acceleration" option would be ideal, anyway.

**Comment by jrmedd** [comment]
@circunspecter I used the potential solution in that Chromium issue ("AccelMethod" "UXA") to no avail. Only experience it on an older machine with integrated graphics (X3100): a brief hang followed by a total crash.

**Comment by xserrat** [comment]
You could try @jrmedd's solution at https://github.com/atom/atom/issues/8708#issuecomment-139183263. It worked for me :smile:

**Comment by Tectract** [comment]
I don't have time to spend all day trying to change out the graphics drivers on my machine, which may leave my machine in a quasi-bootable state, in order to get atom IDE running. Can we just get a flag to disable hardware acceleration instead?

**Comment by Tawreh** [comment]
Chiming in with nVidia graphics in a laptop with a Displaylink dock. I have no problems on my laptop but when I plug in the dock with external displays I get constant flickering. Atom is by far and away the best editor for the work I'm doing currently but it's starting to give me headaches! 

Running `atom --disable-gpu` works - it would be nice to see this as a config item in the program itself.
