### ISSUE TITLE
Creating a new file from the terminal helper throws a ENOENT exception

### ISSUE THREAD

**Issue by jbergstroem** [atom/atom#6559]
(sorry if this is a dup, hard to narrow down the search of open issues -- a bunch of ENOENT cases)

If I want to create a new file with the atom helper, an exception is thrown:
```bash
~/Work/iojs-build ±master $ atom mynewfile
```

..throws:
```
events.js:141
Hide Stack Trace
Error: ENOENT: no such file or directory, open '/Users/jbergstroem/Work/iojs-build/mynewfile'
  at Error (native)
```

**Comment by mnquintana** [comment]
I can't seem to reproduce this with Atom 0.195.0-910cc50 on OS X 10.10.3 - what version of Atom is this? What OS?

**Comment by jbergstroem** [comment]
@mnquintana 0.194.0 on OS X 10.10.3. If I wasn't clear enough, "mynewfile" doesn't exist. I can reproduce this on every attempt.

**Comment by mnquintana** [comment]
Can you try running `atom --safe filethatdoesntexist` and see if you get the same error?

**Comment by jbergstroem** [comment]
@mnquintana can't reproduce any longer. Means I need to triage addons, I guess?

**Comment by mnquintana** [comment]
@jbergstroem Pretty much - can you post a list of your installed packages (`apm list --installed`)?

**Comment by jbergstroem** [comment]
@mnquintana ran through them all. After disabling statusbar (from core) I could no longer reproduce. I was hoping for some kind of combination with another package, but status bar was one of the last 5 I disabled.

**Comment by 50Wliu** [comment]
This is a duplicate of #6372 but I'll keep this open until you find the offending package combination :).

**Comment by jbergstroem** [comment]
@50Wliu Ok.

I find triaging very cumbersome. I'm in a position where I'm able to reproduce it, disable a package, try opening a non-existent file and essentially rinse and repeat. Once I hit a package I then enable it again, followed by the next package I disabled - but now everything works. Is there some caching or similar I'm not aware of although I open/close atom between testing?

**Comment by kevinsawicki** [comment]
> but now everything works. Is there some caching or similar I'm not aware of although I open/close atom between testing

Some packages may not properly implement activate/deactivate so enabling/disabling them without reloading may not highlight the problem.

You might want to open `~/.atom/packages` in Atom and then do a search for `fs.open `, `fs.open(`, `fs.readFile `, and `fs.readFile(` and see what packages use that API, that could help narrowing things down.
