### ISSUE TITLE
Ignored files and folders not showing up anymore

### ISSUE THREAD

**Issue by olivierlesnicki** [atom/atom#6568]
Files and folders in the .gitignore file used to show up greyed out.
They do not show up anymore.

**Comment by izuzak** [comment]
@olivierlesnicki Can you go to Settings > Packages > Tree View and see if the "Hide VCS ignored files" config option is checked? Also, which version of Atom are you using exactly?

**Comment by olivierlesnicki** [comment]
0.194.0
Exclude VCS ignored paths is not checked.

Checking it and restarting Atom doesn't change anything.

**Comment by izuzak** [comment]
Does running Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) help? Which OS are you on? Does this happen for every project or only some?

**Comment by olivierlesnicki** [comment]
OS X Yosemite
10.10

Does it for all of them.
Let me check safe mode.

**Comment by olivierlesnicki** [comment]
Probably linked:
When doing a file search, atom goes through all the files in the directory even the one listed in the .gitignore.

**Comment by izuzak** [comment]
> Let me check safe mode.

Have you checked this?

**Comment by olivierlesnicki** [comment]
Yes! no changes.

**Comment by olivierlesnicki** [comment]
(sorry i had forgot to reply).
safe mode doesn't change behaviour

**Comment by izuzak** [comment]
Can you try moving your `~/.atom` folder somewhere else temporarily, and restart Atom and see if it helps? After that you can move the folder back.

**Comment by olivierlesnicki** [comment]
This solved it :)

**Comment by izuzak** [comment]
@olivierlesnicki That's interesting. Can you share the contents of the config.cson, init.coffee and styles.less files from the folder you moved? If running in safe mode didn't fix the problem for you (which disables non-core packages), then there's possibly something in your config files messing things up. 

I'm going to close this since removing local data fixed the problem for you. Happy to help you dig into this more if you'd like.

**Comment by olivierlesnicki** [comment]
`config.cson`
``
"*":
  "exception-reporting":
    userId: "*******-****-****-****-********22a7"
  welcome:
    showOnStartup: false
  core:
    excludeVcsIgnoredPaths: false
  editor:
    invisibles: {}
  "tree-view":
    hideVcsIgnoredFiles: true
  "linter-jshint": {}
  linter: {}
```
`init.coffee`
``
# Your init script
#
# Atom will evaluate this file each time a new window is opened. It is run
# after packages are loaded/activated and after the previous editor state
# has been restored.
#
# An example hack to log to the console when each text editor is saved.
#
# atom.workspace.observeTextEditors (editor) ->
#   editor.onDidSave ->
#     console.log "Saved! #{editor.getPath()}"

``
`styles.less`
```
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

// style the background and foreground colors on the atom-text-editor-element
// itself
atom-text-editor {

}

// To style other content in the text editor's shadow DOM, use the ::shadow
// expression
atom-text-editor::shadow .cursor {

}
```

**Comment by olivierlesnicki** [comment]
I've intentionally blanked the userId in config.cson before pasting the code here.

**Comment by mnquintana** [comment]
It seems like you weren't seeing ignored files because `tree-view.hideVcsIgnoredFiles` was set to `true`, so Git-ignored files would be hidden.

**Comment by izuzak** [comment]
Notice this in your config file:

```
"tree-view":
    hideVcsIgnoredFiles: true
```

In https://github.com/atom/atom/issues/6568#issuecomment-97390643 I asked you to see if that config option was checked, so that you could uncheck it if it was. 

You said that it wasn't checked and then you checked it to confirm it changes nothing. That config option is responsible for hiding gitignored files in the tree view. Can you try moving the folder back and toggling the option back so that it's not checked?

**Comment by olivierlesnicki** [comment]
@izuzak @mnquintana sorry guys for waisting your time!
I was actually toggling:
```
Settings > Core Settings > Exclude VCS Ignored Path
```
Instead of
```
Settings > Packages > Tree View > Hide VCS ignored files
```
This is completely due to me working on 10,000 things at the same time and failing to pay full focus to @izuzak instructions in his first comment :)
Thanks for the patience though.

**Comment by olivierlesnicki** [comment]
Although I did mention in comment https://github.com/atom/atom/issues/6568#issuecomment-97391684 that I was actually toggling Exclude VCS... XD

**Comment by izuzak** [comment]
@olivierlesnicki Haha, well it seems that both of us need :eyeglasses:! :smile: Happy that we were able to figure things out.

**Comment by mr-bobz** [comment]
I ran into the same too, so looks like the default behaviour of "tree-view" package changed in an upgrade?! Glad I found this thread :-)

**Comment by rsweetland** [comment]
Just made the same mistake! For a setting that has so much impact on the editor experience, I assumed the setting would be front and center. A mention / link in the ```Exclude VCS Ignored Paths``` setting text might be helpful to others.

**Comment by mindtonic** [comment]
+1 for this thread. -1 for the "tree-view" change.
