### ISSUE TITLE
Extra quote is added when backslash is present in a string

### ISSUE THREAD

**Issue by yihangho** [atom/atom#6569]
Not sure how to actually put this in words, but see this:

![Animated GIF](http://i.imgur.com/DaZkgtj.gif)

On each line, right before the (original) last quote, I pressed on the key to insert a quote. A quote should not be added for lines 2 and 3, just like line 1, no?

**Comment by mnquintana** [comment]
I can reproduce this on `master` (Atom 0.195.0-df2b066) with any grammar (or Plain Text).

**Comment by mnquintana** [comment]
Duplicate of atom/bracket-matcher#80 - please subscribe there for updates.
