### ISSUE TITLE
Scroll veneer + selection = odd behavior

### ISSUE THREAD

**Issue by irrationalistic** [atom/atom#6573]
I posted about this on the discussion boards (https://discuss.atom.io/t/automatic-scroll-disable/16460).

It has been reproduced in `--safe`!
1. Start a new file and add enough text to allow for scrolling vertically.
2. Scroll to the very top of the file.
3. Try to select the last two lines on the screen.

It appears that the scroll veneer takes over and starts to move the screen into view. But because you are still down there, it continues to apply and selects while scrolling rapidly, which is hard to control. This also happens at the top of the screen and must be within the 3 edge lines for the issue to happen.

**Comment by jerone** [comment]
Something like this?:

![Atom scroll](https://cloud.githubusercontent.com/assets/55841/7554474/7cd0dcf0-f72a-11e4-8ebb-36b2cd58da4d.gif)

Windows 7 64-bits
Atom 0.198.0

**Comment by irrationalistic** [comment]
Not quite, though that is some strange behavior!

If you are scrolled to the top of the file, try selecting the two bottom visible lines with the mouse.

**Comment by citosid** [comment]
Was this ever fixed? I'm having it with Atom 1.11.0-beta5

**Comment by citosid** [comment]
@irrationalistic never mind... I found the case for my issue:

https://discuss.atom.io/t/typewriter-scrolling-mode/11018/7

It is a setting in Zen plugin call typewriter scrolling...
