### ISSUE TITLE
Deleting A File or Folder Does Not Refresh/Update Tree View

### ISSUE THREAD

**Issue by WadeShuler** [atom/atom#6581]
This should be a simple bug fix.

When deleting a file, or folder,in Atom it appears to not do anything. You still see the file, or folder, sitting there. What you have to do to update the change, is close the parent folder, and open it back up to refresh the changes.

    projectname
    - images
       - image1.png
       - image2.png

If you delete for example 'image2.png', it stays there. Click the arrow on the 'images' folder to collapse the folder in the tree view, and again to expand it, and it will show the file is now gone.

When you delete a file, it should call the same refresh action as expanding does, to reflect the changes immediately.

This happens when deleting both files and folders. You have to manually close and open the parent folder to reflect the changes.

**Comment by sanicki** [comment]
What version of Atom are you using and on which platform?

I am attempting to reproduce the issue but find in v0.196.0 on OS X that files disappear from tree view when the file is deleted from Atom or elsewhere.

**Comment by WadeShuler** [comment]
I'm not home atm but it's windows 8.1 64 bit. I do the updates as they come so I assume it's the latest version.

**Comment by izuzak** [comment]
@WadeShuler I just gave this a try on Windows 8.1 and I couldn't reproduce. Can you confirm the version of Atom you're using (you can see it in the Help menu) and if you can reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

Here's a video of what I'm doing:

![remove](https://cloud.githubusercontent.com/assets/38924/7458030/5a981da8-f291-11e4-901a-6292af8d5354.gif)

Is that what you're doing as well?

**Comment by WadeShuler** [comment]
Version is 0.196.0 - I know I had a large project open, but I can't
reproduce it now... It seems to magically be working now. I tried it like
10 times before posting this issue, and it wasn't working. I had to toggle
the parent folder to get it to refresh. I just opened another large
project, deleted a file, deleted a folder, all refreshed instantly. So I
guess unless others are still experiencing this, this is closed.

**Comment by izuzak** [comment]
:cool: Thanks for letting us know -- if you notice this again, please leave a comment. :cocktail:

**Comment by niccolox** [comment]
I am getting the same effect on Trusty Atom 0.196.0 after adding git submodules from zsh

**Comment by niccolox** [comment]
works fine now after trying atom -safe

**Comment by leoselig** [comment]
Same issue here, appears on any occasion where I delete a file/directory via context menu in the tree view

**Comment by ryanshawty** [comment]
It only happens to me when working in very large directory trees.

OSX Yosemite
Atom 1.0.7

**Comment by leoselig** [comment]
We have a really large directoy structure as well, if it's of any help

**Comment by Billybobbonnet** [comment]
Same here, large directory tree, and no refresh to the treeview after a file/folder deletion or creation.

**Comment by sjatkins** [comment]
I have a not very large directory on ubuntu 15.04 and it is not removing the files form the pane or really deleting them.  Very annoying.  I am on 1.0.9.

**Comment by aehven** [comment]
FWIW, I can make this happen by renaming a file in the tree, then using git to undo the renaming.  The original name never returns to the tree.  I'm on Atom 1.4.1 on a Mac.

**Comment by KrisSiegel** [comment]
I'm currently experiencing the same behavior even when adding / renaming files inside of Atom. Windows 10 Atom 1.5.3. This is the closest thread I could find relating to the issue so thought I'd post in here.

If I collapse then reopen any folder that's the parent of the file I want to see it fixes itself.

**Comment by infojunkie** [comment]
I am experiencing this behaviour too on Atom 1.5.3 Ubuntu 14.04. I am deleting a subfolder from the terminal and recreating it with new files. I expect the subfolder to refresh itself in the tree view.

**Comment by KrisSiegel** [comment]
For what it's worth after I restarted my computer it began working fine. Closing and re-opening Atom had no affect but restarting Windows and now it works properly. Not sure why.

**Comment by aehven** [comment]
I think this is all a bit of a moot point, for me, at least.  I have seen too many bugs in too many versions of this (Nitrous) and other syncing mechanisms. At the very least, there's always a bit of an annoying delay and you have to wait for it before seeing the change on the server.

I've moved on to a better way.  I mount my Nitrous disk using SSHFS (on a Mac, at least, that's easy) and then I use a local editor.  The problem with this method is that file changes initiated on the server don't show up in the editor, but that's not been a problem for the way I work.  At least I know that anything I do in the editor happens immediately on the server, and this is by far more important to me and 100% reliable.

I noticed doing things this way that TextMate is particularly slow using the SSHFS mounts, but Atom is lightning fast with them, as fast as a local disk for all intents and purposes.  I don't know why this should be, perhaps TextMate is trying to do a lot of other stuff after stating a file or directory.  Would be interesting to try other editors, but I'm fine for now knowing that Atom works great in this scenario.  I did uninstall the Nitrous package for Atom to make sure I'm not doing double the network traffic.

**Comment by Huanzhang89** [comment]
Would adding a way to manually trigger the refresh task not solve this problem? Sublime Text has that feature.

**Comment by shrinidhimi** [comment]
Please fix this. its irritating to not have a basic  feature which even the kde kate text editor has!!! closing and reopening is NOT a solution!!!

**Comment by AshtonMeuser** [comment]
:+1:

**Comment by LouieK22** [comment]
Same issue, effects file creation as well though.

**Comment by aehven** [comment]
I would like to reiterate my comment from March, in which I point out a pretty good work-around:

> I think this is all a bit of a moot point, for me, at least. I have seen too many bugs in too many versions of this (Nitrous) and other syncing mechanisms. At the very least, there's always a bit of an annoying delay and you have to wait for it before seeing the change on the server.

> I've moved on to a better way. I mount my Nitrous disk using SSHFS (on a Mac, at least, that's easy) and then I use a local editor. The problem with this method is that file changes initiated on the server don't show up in the editor, but that's not been a problem for the way I work. At least I know that anything I do in the editor happens immediately on the server, and this is by far more important to me and 100% reliable.

> I noticed doing things this way that TextMate is particularly slow using the SSHFS mounts, but Atom is lightning fast with them, as fast as a local disk for all intents and purposes. I don't know why this should be, perhaps TextMate is trying to do a lot of other stuff after stating a file or directory. Would be interesting to try other editors, but I'm fine for now knowing that Atom works great in this scenario. I did uninstall the Nitrous package for Atom to make sure I'm not doing double the network traffic.

**Comment by tobia** [comment]
I have the same development setup as @aehven, SSHFS from a Mac client to a Linux server.

@izuzak I would like to see this bug reopened, because at least on SSHFS on Mac OS X (and probably other FS / OS combinations) it's not intermittent, but always reproducible. Delete something on the server and it is never updated on the folder list, ever.

I understand that having this work automatically on all sorts of file systems, including plugin ones such as SSHFS, is a Hard Problem. In fact, no editor get its 100% right on all OS. But a manual command to reload of the folder tree would go a long way to alleviate the problem. Sublime has it (Project > Refresh Folders) and it's very useful.

The only solution I have found is to reload the entire Atom window when I make a change on the server, but that's obviously sub-optimal.

**Comment by pacMakaveli** [comment]
I don't know if this's been mentioned or not. But when I run Grunt, or any other commands that delete/creates modifies folders not from the Atom editor, my tree view doesn't update.

**Comment by dacz** [comment]
Same problem here. Large project, a lot of files.

Files created as "Duplicate" in context menu and saved with different name in the same directory doesn't appear in the tree view, but they exists. When I'm trying to create another file and try to save it with the same name as duplicated (but not visible in tree view) throw an error - file already exists. To Atom know that it's there but doesn't show it in the tree view.

Atom update & restart didn't help.
Atom 1.11.2, OSX ElCaptain.

**Comment by MicroDroid** [comment]
I use PHP's Laravel framework and files created by Artisan are not appearing in the file tree.
This is purely an issue, it needs to be reopened

**Comment by ivnmaksimovic** [comment]
Same as @pacMakaveli. Tree view doesn't show Files / Folders generated by Grunt.

**Comment by andyl** [comment]
Same problem.  Is there a way to manually force a refresh ?

**Comment by n1k0** [comment]
Same problem. This should be addressed as it makes using Atom really difficult when it happens.

**Comment by bisinakeshara** [comment]
I just tried this with a fresh atom install on Windows 10, Tree-view dose not  refresh

**Comment by mikkeschiren** [comment]
Latest atom on Ubuntu, same problem.

**Comment by JockVanDallas** [comment]
Have the same problem
Atom 1.17.2
OSX 10.12.5

**Comment by mansisce** [comment]
Not able to see the chnages and refresh the folder tree on right
 Atom    : 1.17.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by nguyenbathanh** [comment]
Any update on this?

**Comment by sunilkumarmohanty** [comment]
I noticed the same problem

**Comment by animalphase** [comment]
I am getting this error (or similar) after a new directory was added via a compile process that was run in Terminal. The process added a new sub-directory inside of my current working directory called "compiled".

My directory looks like this:

```
Project/
    //…lots of directories…
    current-stuff/
        compiled/ (the new directory)
            compiled.js
            compiled.css
        my-file.js
        my-file.scss
        …etc…
    //…lots more directories…
```

The new `compiled` directory does not show up in Atom's tree view, even after reloading the window and after quitting the app and re-launching. The files within the directory do not appear to show up as results in the cmd+p search for files menu. However, if I right-click on the `current-stuff`, and choose **Search in Directory**, it *does* search the contents of these files.

This is in a very large project directory.

**Comment by mwandy** [comment]
I was just having this same error for files that were being compiled via Grunt. It just popped up about a week ago and was trying to figure out what was going on. It turns out in the Tree-View package settings, the Hide VCS Ignored Files option had become checked and was hiding everything. 

Settings/Packages/Tree View

![image](https://user-images.githubusercontent.com/2396132/37467389-79b3a724-2836-11e8-886f-5b8943043423.png)

That should be your first step if you are having this same problem.
