### ISSUE TITLE
0.195.0 made the editor unsuable for php files

### ISSUE THREAD

**Issue by Cipa** [atom/atom#6584]
Recent update to .195 doesn't let me edit php files. It hangs and after a while displays the "Keep waiting" or "Close" message

I started in safe mode to make sure it's not some plugin. Let me know how I can help to debug

**Comment by Cipa** [comment]
The editor shows the file but I think it fails at "colorizing" the text

**Comment by kevinsawicki** [comment]
Does it hang with other files or only php files?

**Comment by kevinsawicki** [comment]
Can you include a link to or content of a file that is freezes with?

**Comment by Cipa** [comment]
Doesn't look like it.
Tested with html, .htaccess, .sql, .tpl, .js

**Comment by Cipa** [comment]
Any of the 2 php files here should do it
https://github.com/ClipperCMS/ClipperCMS

**Comment by thedavidprice** [comment]
Experiencing same issue here with .php files. Editor hangs and does not respond. Happened immediately after updating to .195

**Comment by Cipa** [comment]
Weird, seems to work for new created file test.php with this code in it, but not for other php files
```
<php?
echo 'aaaa';
?>
```

**Comment by kevinsawicki** [comment]
I believe this was do to some changes in the language-html package, I've rolled back the version Atom ships with in https://github.com/atom/atom/commit/cf9b00cc8c67b6884487cc9b9bb82c5821fc1922 and will cut a release once the builds finish.

**Comment by Cipa** [comment]
Disabling language-html fixed the problem, so it must be that one

**Comment by kevinsawicki** [comment]
0.196 has been released, thanks for reporting this so quickly, you probably saved a lot of other people from experiencing these freezes :blue_heart:

**Comment by cjsaylor** [comment]
Thanks @kevinsawicki @benogle.
