### ISSUE TITLE
grammarForScopeName problem

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#6586]
When I open a file called `x.sh` it has the grammar `Shell Script`.  But when I call `atom.grammars.grammarForScopeName 'x.sh'` I get nothing.  Am I using it correctly?

If needed I can make a sample package to show the problem.

## Versions

* **Atom:**       0.194.0
* **Atom-Shell:** 0.22.3
* **OS:**         linux 3.14.0
* **Misc**
    * apm  0.161.0
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.3
    * git 1.7.9.5

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.6.3.</small>

**Comment by kevinsawicki** [comment]
Scope name is the value inside the grammar, so for shell script it is `source.shell`.

https://github.com/atom/language-shellscript/blob/abf186b46f972b5b8491069d8f8c8ef5efe6ff15/grammars/shell-unix-bash.cson#L984

If you want to get a grammar for a file name or path use `atom.grammars.selectGrammar('x.sh')`

**Comment by kevinsawicki** [comment]
So to get the shell directly use `atom.grammars.grammarForScopeName('source.shell')`

**Comment by mark-hahn** [comment]
thanks.  BTW, the example in the api docs is wrong.

```
::grammarForScopeName(scopeName) 

Get a grammar with the given scope name.
  Argument	Description
    scopeName	
      A String such as "source.js".
  Return values
    Returns a Grammar or .
```

**Comment by kevinsawicki** [comment]
> thanks. BTW, the example in the api docs is wrong.

Reading it over I'm unclear on what is wrong with it? `source.js` is the scopeName and it does return a `Grammar`.

**Comment by mark-hahn** [comment]
Oh, `source.js` looks like a javascript filename being used like `x.sh`.

BTW,  `x.sh` is not a real filename.  I'm doing a package that lets an atom user put a comment in their file telling what grammar to use.  Right now I'm letting them specify an extension like this ...
```
# -*- grammar-ext: sh -*-
```
I'm just adding `x.` to the front of the extension and looking up the grammar.  Can you think of a better way for them to specify it?

**Comment by kevinsawicki** [comment]
> Can you think of a better way for them to specify it?

The grammars could include this themselves in the `firstLineMatch` property.

This was recently added in https://github.com/atom/language-ruby/pull/90 for

**Comment by mark-hahn** [comment]
Sigh.  When I call this ...

```
atom.grammars.selectGrammar 'x.sh'
```
I'm getting the null grammar.  I know that making a file called `x.sh` is
considered a Shell Script.

**Comment by kevinsawicki** [comment]
>  When I call this

When are you calling it? The grammars do load asynchronously at startup.

![screen shot 2015-04-30 at 3 43 44 pm](https://cloud.githubusercontent.com/assets/671378/7423887/b7d75820-ef4f-11e4-9831-f3385fe1dbc8.png)

**Comment by mark-hahn** [comment]
> The grammars could include this themselves in the firstLineMatch property.

That would require changing the grammar files, right?  I am not working on anything relating to the grammar files.  I'm letting the user specify what grammar a source file should use by adding a comment to that source file.  This is needed on files with no extensions or files that start with one language but then are mostly another language (like riot.js tag files).

**Comment by kevinsawicki** [comment]
> That would require changing the grammar files, right?

Yup

**Comment by mark-hahn** [comment]
> When are you calling it? 

I'm calling it in a `atom.workspace.observeTextEditors (editor) =>  callback`.  

> The grammars do load asynchronously at startup.

Not all of them.  I have found that grammars are only loaded in the registry for files already in the project and known.  Since no files loading are considered shell files the registry doesn't include the shell grammar.  I was hoping there was a call that would give me a grammar when I specify something like `sh` or `Shell Script`.

**Comment by mark-hahn** [comment]
Never mind.  I was wrong about only some loading.  When I put my observeTextEditors call with a 3 second delay, everything worked.  So there may be a visible switch of the file type I don't think this will be  problem.  Is there a way to find out when all grammars are loaded?

Thanks for explaining all this.

**Comment by kevinsawicki** [comment]
> Is there a way to find out when all grammars are loaded?

There isn't a final event but there is the following:

* `atom.grammars.onDidAddGrammar`
* `atom.grammars.onDidUpdateGrammar`
* `TextEditor::observeGrammar`

So you can know when grammars are added or updated and also when an editor's grammar changes in response to a grammar being loaded or manually changed from the status bar.

**Comment by mark-hahn** [comment]
Hmm.  I got a bit of a problem.  I can look for the grammar by listening to every onDidAddGrammar event but I'll never know when to give up and tell the user I can't find his grammar.

I'll put in a timeout before giving the error but the ux isn't going to be wonderful.  Consider this issue a request for some way to search all grammars.

-- Wait, there is a feature to switch the grammar in the status bar.  How does this know what all the grammars are?

**Comment by kevinsawicki** [comment]
>  Wait, there is a feature to switch the grammar in the status bar.

Yup, the `Coffee Script` link in the screenshot:

![screen shot 2015-04-30 at 4 11 43 pm](https://cloud.githubusercontent.com/assets/671378/7424217/a3135282-ef53-11e4-9ac8-f721f54eb295.png)

> How does this know what all the grammars are?

It uses `atom.grammars.getGrammars()` to populate the list when it is clicked:

https://github.com/atom/grammar-selector/blob/9c5fffe592f8158869ae74569342f82b29c83449/lib/grammar-list-view.coffee#L56

**Comment by mark-hahn** [comment]
> It uses atom.grammars.getGrammars() to populate the list when it is clicked:

That's the first thing I tried but the list wasn't complete when the texteditor loaded.  Hence the origin of my whole problem.

**Comment by mark-hahn** [comment]
I'll put in a low-priority request for an event when all grammars are loaded.  I don't know if there is any other use case for this but I think this feature of having the grammar specified in the file to be a serious use case.  There is no other way to fully control what grammar is used for a file.  I don't consider making all grammar writers add the feature, like the one for ruby, to be a solution.

For now I'll use a timeout.  It won't kill the user to see the grammar switch after a few seconds.
