### ISSUE TITLE
Disable application menu items when they don't apply to the focused element

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#6588]
Currently, all application menu items are enabled no matter what element is focused, even if their commands aren't bound to that element or its parents. This can contribute to strange behavior / bugs like #6587. If a command isn't bound to a focused element or its parent elements, then it should be disabled (and maybe also removed from the Command Palette? I think that might be better off in another issue though).

**Comment by lee-dohm** [comment]
Thanks for the contribution. We agree that this is still an issue. However, since it isn't something that we intend to take on in the near future, we're going to close this.
