### ISSUE TITLE
Needed: an event when all grammars are loaded

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#6591]
I'm writing a package to let the author of a source file put in a comment to force the file to use a certain grammar (aka "mode" in EMACS). This was the goal of the existing package `file-mode` but that package is severely broken and a total rewrite is needed.  The ruby grammar already has this feature [built-in] (https://github.com/atom/language-ruby/pull/90) but my package will work for all grammars.

I have a problem that the grammars are loaded asynchronously and a texteditor can be loaded before all the grammars are loaded.  See my issue #6586.  I can find the mode comment when the texteditor is loaded but there is no way to look up the grammar.

For now I'll kludge it and not look for the grammar list until after a time delay but this will cause the user to see the grammar switch after that delay which is not a good UX.

To finally get to the point, I need an event telling me when the grammars are loaded.  I'll wait until then to look in all the files for the mode comments.

**Comment by mark-hahn** [comment]
Wait a minute.  Someone is cheating.  I put a breakpoint on the first grammar load event and my coffeescript files are already colored at that point.  How can this be?

I've discovered that it takes up to 3 seconds after the files are loaded before all grammars are loaded.  The first grammar load doesn't even happen until after the last editor file loads.  That means that even if I set the file grammar right after the last grammar load then my coloring will take 3 seconds more than the coffeescript files.

I'm just confused.

**Comment by kevinsawicki** [comment]
> How can this be?

Some grammars are loaded synchronously at startup so that editors automatically opened at startup are colorized.

**Comment by mark-hahn** [comment]
> Some grammars are loaded synchronously at startup so that editors automatically opened at startup are colorized.

Aha, so it *is* cheating.  (grin)

I guess mode comments will have to suffer this delay forever.  Oh well, in that case I'll rescind this request.  Having the event won't make a significant difference.
