### ISSUE TITLE
Missing icon in Linux

### ISSUE THREAD

**Issue by nlaplante** [atom/atom#6598]
After doing

```
script/grunt install --installdir=/usr/local
```

there are no icons for the atom launcher.

The .desktop file **/usr/local/share/applications/atom.desktop** references the icon at **/usr/local/share/atom/resources/app/resources/atom.png** but the folder **app/resources** does not exist.

**Comment by 50Wliu** [comment]
Duplicate of #6523, please subscribe there for updates.
