### ISSUE TITLE
ENOENT opening app.asar

### ISSUE THREAD

**Issue by agrosner** [atom/atom#6604]
[Enter steps to reproduce below:]
1. Open editor from command line using git with it as default commit editor.

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core
### Stack Trace

Failed to load the exception-reporting package

```
At ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app.asar'

Error: ENOENT: no such file or directory, open '/Applications/Atom.app/Contents/Resources/app.asar'
    at Error (native)
    at fs.openSync (fs.js:544:18)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:402:12)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:138:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:691:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:28
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 15
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by virtuoushub** [comment]
I ran into this issue in https://github.com/atom/apm/pull/745, see my [comment](https://github.com/atom/apm/pull/745#discussion_r141298972). I quote it below for higher visibility, and to avoid having to click through to read the comment. 

> I ran into it while testing. For whatever reason `app.asar` does not exist on my machine.
> 
> ```shell
> ~ ❯❯❯ sw_vers
> ProductName:	Mac OS X
> ProductVersion:	10.11.6
> BuildVersion:	15G1611
> ```
> ```shell
> ~/D/p/apm ❯❯❯ ls /Applications/Atom.app/Contents/Resources/                                                                                                                                    atom-version
> LICENSE.md    bg.lproj      de.lproj      en_GB.lproj   fi.lproj      he.lproj      it.lproj      lv.lproj      nl.lproj      ru.lproj      sw.lproj      uk.lproj
> am.lproj      bn.lproj      el.lproj      es.lproj      fil.lproj     hi.lproj      ja.lproj      ml.lproj      pl.lproj      sk.lproj      ta.lproj      vi.lproj
> app           ca.lproj      electron.asar es_419.lproj  file.icns     hr.lproj      kn.lproj      mr.lproj      pt_BR.lproj   sl.lproj      te.lproj      zh_CN.lproj
> ar.lproj      cs.lproj      electron.icns et.lproj      fr.lproj      hu.lproj      ko.lproj      ms.lproj      pt_PT.lproj   sr.lproj      th.lproj      zh_TW.lproj
> atom.icns     da.lproj      en.lproj      fa.lproj      gu.lproj      id.lproj      lt.lproj      nb.lproj      ro.lproj      sv.lproj      tr.lproj
> ```
> 
> ```shell
> ~/D/p/apm ❯❯❯ apm --version                                                                                                                                                                    atom-version
> apm  1.18.4
> npm  3.10.10
> node 6.9.5 x64
> python 2.7.10
> git 2.14.2
> ```
> 
> ```shell
> ~/D/p/apm ❯❯❯ atom --version                                                                                                                                                                   atom-version
> Atom    : 1.20.1
> Electron: 1.6.9
> Chrome  : 56.0.2924.87
> Node    : 7.4.0
> ```
