### ISSUE TITLE
Add setting to disable restoring last session

### ISSUE THREAD

**Issue by dominicbarnes** [atom/atom#6605]
It's useful that atom can remember the files/folders you had open last time and then re-open them next time you start atom. I can't seem to figure out how to turn off this behavior though, I generally _want_ to start clean each time I open atom.

Is there a config option to enable/disable this feature? Or could we implement a dialog box when closing atom that asks if you want it to remember what you had open?

**Comment by andya9** [comment]
:+1: 

but maybe it would be better (popups at closing are annoying!) to implement a command  "close-without-saving-session" that we can bind to a keyboard shortcut

**Comment by izuzak** [comment]
> Is there a config option to enable/disable this feature? 

As far as I know, there's no such option currently. /cc @maxbrunsfeld 

> Or could we implement a dialog box when closing atom that asks if you want it to remember what you had open?

That's an interesting idea as well. Personally, I think a config option might be less annoying than a dialog which pops up every time you close Atom. Or even a new command, as @andya9 suggested. :musical_keyboard:

**Comment by mnquintana** [comment]
Related to https://github.com/atom/atom/issues/6495

(:+1: for the command suggestion)

I think a config setting to enable / disable this might not be a bad idea – to be fair, Sublime has a config setting for their equivalent of this feature (`hot_exit`).

**Comment by samis** [comment]
I also find this behaviour unneeded. It's not a bad thing to have, but I'd prefer it to start clean. Make it a setting, preferably. I shouldn't have to remember to type a specific command or keybbnd. if I want Atom to close the way I desire. :+1:

**Comment by jonathandelgado** [comment]
+1 for setting to disable

**Comment by chloerei** [comment]
+1 I want to disable this feature.

**Comment by piranna** [comment]
I think this should be disable by default and "restore last session instead of open current folder" being a config opt-in, not an opt-out.

**Comment by motam** [comment]
+1 for the previous behavior, "latest" should be an option.

**Comment by maxbrunsfeld** [comment]
Some other discussion of this happened here: https://github.com/atom/atom/issues/6873.

**Comment by th01** [comment]
:+1:

**Comment by James-Ko** [comment]
+1, this should be made an option in the config files.

**Comment by ffflorian** [comment]
+1

**Comment by m1ga** [comment]
:+1:  for an option to disable "restore session" globally

**Comment by nekuneko** [comment]
From @olmokramer:

You can put this in your init.coffee:

process.nextTick ->
  atom.workspace.getPaneItems().forEach ->
    atom.workspace.destroyActivePaneItem()

It closes all pane items after Atom started.

At: https://discuss.atom.io/t/dont-open-previously-opened-files-on-new-start/5959/8

Plase, implement this behaviour by default :'(

**Comment by hho** [comment]
:+1: +1 for an opt-in feature. Pretty please.

**Comment by azerupi** [comment]
Is it possible to hook in atom with a plugin before it loads the last session? 
If yes someone could make a splash-screen plugin for this problem, is that possible?

**Comment by albertgasset** [comment]
An simpler workaround for Linux is to make `application.json` a symbolic link to `/dev/null`:

    ln -sf /dev/null ~/.atom/storage/application.json

**Comment by code-tree** [comment]
Thanks for the suggestion @albertgasset, but didn't work for me. Gave me an idea though, and this works for me instead:

Remove the storage dir, and replace with an empty file with same name.

**Comment by mikeobrien** [comment]
:+1:

**Comment by gnomed** [comment]
+1 on this feature. 

Seems a tad presumptuous to expect everyone to want to re-open their old files. 

This is supposed to be a basic lightweight text editor. Not a full blown IDE. So you need to either stop calling it a text editor everywhere on the atom website, or you need to stop adding massive scope creep features like session preservation to something that was never intended to be a heavyweight IDE in the first place.

I was about 2 seconds from abandoning atom altogether until I saw the suggestion to replace the storage folder with a file of the same name. That doesn't get me out of the fact that this issue has already wasted hours of my time. Meanwhile I struggle to imagine anyone with a **clear vision** for this product would add such a random feature and do such a half-assed job of implementation when it clearly does not fit with the concept of "lightweight" and is shoehorning every single user in a use case they may not be happy with. Kind of expected better from "the people behind github" so I dunno, maybe this is just the less talented people behind github working on atom. What else could explain the lack of foresight in adding such a divisive and heavyweight feature without making it configurable?

**Comment by maxbrunsfeld** [comment]
> stop adding massive scope creep features like session preservation to something that was never intended to be a heavyweight IDE in the first place

The most common requests for the session restoration feature were from users of `TextMate` and `Sublime Text`. Both of these programs have this behavior, and they are not IDEs; they are text editors. If you want to open a specific directory, and not the directories that you had opened previously, simply type this:

```
atom .
```

It's lightweight!

**Comment by maxbrunsfeld** [comment]
That said, we're not opposed to adding a configuration setting for this. As usual, we'd love to merge a PR adding this feature, if it works and has good tests.

**Comment by andreaferretti** [comment]
+1

**Comment by tgharib** [comment]
albertgasset and code-tree provided working work-arounds but unfortunately, it seems that if you use their method, Atom no longer remembers the "Toggle Tree View" setting which means that I would have to manually toggle the tree view every time I launch Atom in order to hide the side pane that displays the directory tree. Another work-around to disabling the last session restoration without breaking Atom's ability to remember the "Toggle Tree View" setting is to modify the permissions so that ~/.atom/storage/application.json is in read-only mode.

![image](https://cloud.githubusercontent.com/assets/6457015/10121051/24d704ac-64a8-11e5-8513-13f91e60d88f.png)

**Comment by thedaniel** [comment]
If we're going to add this, I'd love to start with a config-file-only setting rather than adding a checkbox to core settings. I think that there should be a high bar to adding more settings controls for usability reasons, and shipping it without UI first & doing some analytics on uptake seems like a good way to be cautious in cases like this.

**Comment by winterflags** [comment]
+1 Would like to be able to toggle this behaviour.

I'm frequently working with a package that adds a custom menu pane to Atom, and this causes significant loadup overhead if I had it open when I last closed Atom. It takes up to 5-6 seconds to load, so I would prefer to have no tabs open when I start Atom.

**Comment by johny-mnemonic** [comment]
I have different issue with application.json.
It seems like this file is constantly being updated. At least whenever I switch between Atom windows.
What about updating this file only when there is a change i.e. when you open/close Atom window, or when you close whole Atom editor?

**Comment by jenkstom** [comment]
Softlinking /dev/null to ~/.atom/storage/application.json gives me exactly the behavior I want: no previous file and a new blank text file named "Untitled".

**Comment by jpettersson** [comment]
@jenkstom Nice workaround!

Atom is still pretty slow to start.. always opening several windows makes this worse. I work on many different projects in a day and prefer a clean slate when I start atom. Hoping this becomes a setting eventually.

**Comment by patrickburke** [comment]
:+1: for adding that setting!

And thanks @jenkstom for the workaround!

**Comment by winterflags** [comment]
@jenkstom What is the command you used?

**Comment by jenkstom** [comment]
mv ~/.atom/storage/application.json ~/.atom/storage/application.json.backup
ln -s /dev/null ~/.atom/storage/application.json

**Comment by winterflags** [comment]
@jenkstom @albertgasset 

Thanks for the tip, I've implemented it now :)

If I want to restore the original state, I only need to do this right?

`~/.atom/storage/application.json
mv ~/.atom/storage/application.json.backup ~/.atom/storage/application.json`

**Comment by jenkstom** [comment]
Yes, that should put it back. Or you can just delete the soft link to save state on the next session.

**Comment by marek1545** [comment]
Thanks. File permission works for me.

**Comment by Manny-MADE** [comment]
+1 here.. strongly dislike having random projects open when i start the ediotr

**Comment by docrinehart** [comment]
+1 to make this configurable

**Comment by sho-87** [comment]
+1 would love to see this option

I have my atom config synced through dropbox across a windows desktop and a osx laptop, and of course the path to the last opened file is going to be different across the 2 platforms, so its really annoying to have atom try to open C:/Users/..... on my mac

**Comment by freeatnet** [comment]
I've gone through the code to investigate what can be done to implement this feature. There is an `AtomEnvironment` instance variable `enablePersistence` that controls saving current session's data. Unfortunately, it is also passed to `Config` class, where it controls Atom storing / reading user settings. The latter appears to have been added by @nathansobo in dc44d11a2cee008a0b1ff4ed6784420e125cd4fc.

@nathansobo, could you give some guidance on how you'd expect this feature to be implemented?

**Comment by maxbrunsfeld** [comment]
@freeatnet See this in-progress PR: https://github.com/atom/atom/pull/9042

**Comment by freeatnet** [comment]
@maxbrunsfeld Awesome, thank you!

**Comment by crlc** [comment]
+1 This causes unwanted issues and delays with virtual directories.

**Comment by as-cii** [comment]
This was implemented in #11324/#9042 and will be out in Atom 1.8.0-beta0.

**Comment by code-tree** [comment]
Could this please be reopened? As I was disappointed to discover the following:
> This only applies to opening Atom without a path argument.

:(

I don't see the rational for this. If people don't want session restored, then they don't want session restored...

(still appreciate the partial implementation though, so thanks)

**Comment by hho** [comment]
Also, you now lose your editor contents on close (even if session restore disabled, Atom does not ask me to save untitled editors).

**Comment by fulldecent** [comment]
I am using Atom 1.9.9 and do not see this feature. Please reopen.

**Comment by ShyPixie** [comment]
Same here

**Comment by tschf** [comment]
There was [a](https://github.com/atom/atom/pull/9042#issuecomment-145362846) [comment](https://github.com/atom/atom/pull/9042#issuecomment-146297378) a while ago about not needing a UI for this config yet. You can add the setting to your config.cson

```
core:
    restorePreviousWindowsOnStart: false
```

Working for me on 1.10

**Comment by fulldecent** [comment]
@tschf Thank you, startup is now much faster for me!

**Comment by nuddik** [comment]
@tschf Thanks, that works for me. So much better for me...

**Comment by nathansobo** [comment]
@maxbrunsfeld Do you think we could add this to the schema so people see it in settings?

**Comment by Ben3eeE** [comment]
Combine that with rewording the`Open Empty Editor On Start` setting. https://github.com/atom/atom/issues/10623

**Comment by andreaferretti** [comment]
@tschf I added that setting. It works for me when opening Atom without specifying a folder. But when I open Atom in a folder (`atom some/dir`) I still see the open files from the previous session. Since I almost never open Atom without specifying a folder, the issue remains for me

**Comment by Lewiscowles1986** [comment]
The issue remains, but @tschf comment stands and worked for me. I had a problem where I opened a webdav file (atom took a very long time to launch, and then kept crashing), so editing config.cson seemed to me at least a very minor price to pay.

**Comment by JamesVG1** [comment]
I opened bootstrap.css.map. and now every time i open Atom, it opens it automatically and freezes.
this feature should really be able to turn off!

**Comment by nathansobo** [comment]
Use `--clear-window-state` for the time being.

**Comment by 50Wliu** [comment]
Don't forget about the `restorePreviousWindowsOnStart` option (which is why this issue has been closed).

**Comment by martinosorb** [comment]
+1,  this annoys me a lot...

**Comment by 50Wliu** [comment]
@martinosorb can you please elaborate?  What annoys you a lot?  If the lack of a setting to disable restoring the last session is what is annoying you, please be aware that the `restorePreviousWindowsOnStart` option will prevent restoring the last session.

**Comment by martinosorb** [comment]
That seems to work only in the case of atom being opened without a path specification, am I wrong?

**Comment by 50Wliu** [comment]
@martinosorb Ah, good point.  Would you mind opening a new issue for that if one doesn't already exist?

**Comment by martinosorb** [comment]
Somebody above was proposing to reopen this one because of that issue.

**Comment by 50Wliu** [comment]
I think it's best to open a new issue so as to not confuse the two (no setting to disable restoring state vs. setting not applying when explicitly giving a path argument).

**Comment by Aleksandern** [comment]
Just in case
[https://discuss.atom.io/t/remember-open-projects-when-reopening-atom/7053/37](url)
