### ISSUE TITLE
Minor oddity: installed in the future?

### ISSUE THREAD

**Issue by richarddewit** [atom/atom#6606]
![image](https://cloud.githubusercontent.com/assets/7933750/7436375/732afd9a-f04d-11e4-993f-941ecc7be02c.png)

When I wanted to remove a recently installed program, I encountered this. 
`Start` > `Control Panel` > `Remove a program` then sorted on date ascending.

It says it's installed on October 1st this year (Dutch date notation is `dd-mm-yyyy`). That's in the future, cause it's May 1st today. I installed it a couple of weeks ago (April 15th).

>Windows 7 64bits
 >Atom 0.196.0

**Comment by thomasjo** [comment]
Installation time is handled entirely by Windows, right? Unless there's some way to override that from an installer, I don't understand how this could be caused by Atom (or Squirrel). Weird.

**Comment by paulcbetts** [comment]
It is caused by Squirrel, MSDN docs don't describe that weirdo date field as being localized but it is. It's been on my TODO list but I keep forgetting about it

**Comment by ismyrnow** [comment]
@paulcbetts: Looked over the code. Your string formatting is grabbing minutes instead of months.

That is: `DateTime.Now.ToString("yyyymmdd")` should be `DateTime.Now.ToString("yyyyMMdd")`. MSDN docs for date string formatting can be found [here](https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx).

**Comment by paulcbetts** [comment]
@ismyrnow Ooh! Wanna submit a PR for that?

**Comment by ismyrnow** [comment]
Will do. Are there any related tests to update?

**Comment by paulcbetts** [comment]
@ismyrnow No tests for setting the regkey

**Comment by jerone** [comment]
Ref issue: https://github.com/Squirrel/Squirrel.Windows/issues/374

**Comment by damieng** [comment]
Got this fix when we updated Squirrel.
