### ISSUE TITLE
Can't override alt-delete/alt-backspace

### ISSUE THREAD

**Issue by CaptSaltyJack** [atom/atom#6608]
Adding this to my keymap.cson file has no effect:

```cson
'atom-text-editor':
  'alt-delete': 'editor:delete-to-next-word-boundary'
  'alt-backspace': 'editor:delete-to-previous-word-boundary'
```

When I hit alt-delete, it still does the default `editor:delete-to-end-of-word`.

**Comment by kevinsawicki** [comment]
What does the keybinding resolve display when you press that keybinding?

You can bring it up using `cmd-.` and then press `alt-delete` in the editor.

**Comment by CaptSaltyJack** [comment]
`editor:delete-to-end-of-word`

**Comment by kevinsawicki** [comment]
Can you include the entire contents of your `keymap.cson` file?

**Comment by CaptSaltyJack** [comment]
Sure. Comments excluded.

```cson
'atom-text-editor':
  'alt-delete': 'editor:delete-to-next-word-boundary'
  'alt-backspace': 'editor:delete-to-previous-word-boundary'
'.platform-darwin .editor':
  'shift-cmd-b': 'bookmarks:toggle-bookmark'
'.editor':
  'ctrl-b': 'bookmarks:view-all'
'atom-text-editor':
  'cmd-;': 'autocomplete:toggle'
```

**Comment by kevinsawicki** [comment]
CSON and JSON don't support multiple keys with the same value in the same object, looks like you have multiple `atom-text-editor` keys and only the last one is used according to `JSON.parse`.

Try:

```cson
'atom-text-editor':
  'alt-delete': 'editor:delete-to-next-word-boundary'
  'alt-backspace': 'editor:delete-to-previous-word-boundary'
  'cmd-;': 'autocomplete:toggle'
'.platform-darwin .editor':
  'shift-cmd-b': 'bookmarks:toggle-bookmark'
'.editor':
  'ctrl-b': 'bookmarks:view-all'  
```

**Comment by CaptSaltyJack** [comment]
Aha! That did it. Thanks. I wasn't thinking in terms of JSON data for some reason.. duh.

**Comment by kevinsawicki** [comment]
> Aha! That did it.

Awesome, closing this out.
