### ISSUE TITLE
Built in reopen function not working with project manager

### ISSUE THREAD

**Issue by Zireael07** [atom/atom#6610]
As the topic says. In contrast, the community package reopen-last-project does open the project I was last working on.
The project manager uses full path, not relative, so I have no idea why the difference.

**Comment by thomasjo** [comment]
If you are referring to `open-last-project`, you should uninstall it immediately—it's been deprecated:
https://github.com/danielmahon/atom-open-last-project

> Deprecated as of Atom 0.193.0, as this functionality has been added to Atom core and will continue to be refined until 1.0

Same goes for the other, similar packages.
