### ISSUE TITLE
[Windows] Restart and Update does not work

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#6612]
all it does is close and update, never restarts for me.

Tested with .193 => .196

**Comment by jerone** [comment]
Do you the menu item in the Help menu or the (green) <kbd>Restart and update</kbd>-button that sometimes shows up in the release notes window? 

Because that last one happens to me too. It won't restart, only close.

Windows 7 64-bits
Atom 0.198.0

**Comment by Zireael07** [comment]
@jerone: Me too, 0.198.0. 0.196.0 and earlier were fine.

**Comment by paulcbetts** [comment]
This is fixed in the release I'm about to finish - the update works, it's just the restart that fails

**Comment by Stanzilla** [comment]
Yeah that was what I was trying to say, thanks though :)

**Comment by Eschon** [comment]
I had similar issues for the last few versions of Atom on OS X 10.10.3
The behaviour when I click the restart and update button on the release notes window is very inconsistent. Sometimes it restarts sometimes it doesn't but the most unpleasant part is that I usually have to redo it at least 5 times till it actually updates Atom.

**Comment by Stanzilla** [comment]
Restart did not work from 201 => 202

**Comment by Stanzilla** [comment]
202 => 204 restart worked

**Comment by Eschon** [comment]
From 202 to 204 I encountered yet another strange behaviour. I saw that an update was available and as I had multiple instances of atom open I thought that maybe it would be a good idea to close everything to close everything before attempting an update. So I made sure that no atom process was left and then started it again.

When I opened the release notes I was astonished to see that the restart and update button was gone. So I went back to my console window and ran `atom -v` and got `0.204.0`.
Somehow atom updated itself with out my consent.

**Comment by Stanzilla** [comment]
@Eschon That is actually intended behaviour.

**Comment by Eschon** [comment]
@Stanzilla ah ok, I didn't know that.
So could it be that my previous problems with updating happened because atom somehow failed to close itself correctly?

**Comment by Stanzilla** [comment]
204 => 205 restart did not work.

@Eschon I don't know :o:

**Comment by paulcbetts** [comment]
This is fixed in Squirrel, but it'll take a bit to take effect, since it'll be the release _after_ the one where we fix the bug where it finally works again

**Comment by Stanzilla** [comment]
@paulcbetts is that Squirrel version already used in the recent Atom releases? If so, since which version?

206 => 207 restart did not work btw.

**Comment by Stanzilla** [comment]
Found out via Slack that Atom currently uses 0.9.3 which is pretty old, so waiting it is!

**Comment by mnquintana** [comment]
I think this is a duplicate of https://github.com/atom/atom/issues/5692 – closing in favor of that issue.

**Comment by Stanzilla** [comment]
I tend to disagree but we will see when 1.0.5 comes out as 1.0.4 now uses an up to date Squirrel version and @paulcbetts that should fix it.

**Comment by Stanzilla** [comment]
@mnquintana Can we please reopen this? It still does not work and it is no duplicate of #5692 imo because it doesn't work from the `Help` menu either.

**Comment by Stanzilla** [comment]
@mnquintana @50Wliu nope, not fixed in 1.7, just tested it with today's update. It only closes, never re-opens.

**Comment by Stanzilla** [comment]
Wellll, now it worked <.<

**Comment by Stanzilla** [comment]
Still broken in 1.19.0-beta6

**Comment by Stanzilla** [comment]
This is still an issue. I noticed the process is never killed when you hit "restart" so I guess that prevents it from starting again. I uploaded a process dump of that ghost process: https://www.dropbox.com/s/tsnzljjprbp2ws5/atom.zip?dl=0

**Comment by MorganMarshall** [comment]
It appears this could be an issue spanning over 2 years or more and still isn't working, why are all these issues being closed or abandoned. This is an in your face issue and confidence breaking for new users.

**Comment by Stanzilla** [comment]
The problem is mainly that most of the devs are macOS users, I think.

**Comment by ewolfe** [comment]
I just experienced this issue on macOS as well. After force quitting the app a few times it finally upgraded to 1.24.0.

**Comment by TylerDelRosario** [comment]
I've also been experiencing this issue on Windows, but as ewolfe said, force restarting it seems to fix the problem.

**Comment by Stanzilla** [comment]
I gave up on Atom a long while ago so closing is fine.
