### ISSUE TITLE
[Windows] Squirrel icon stays up after reading changelog

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#6613]
Did I understand it correctly that the Squirrel icon in the status bar should go away after you read the changelog after updating? 

If so, the icon stays up even through me reading the changelog a few times, closing it's tab and reopening it from the icon.

If not, maybe it should go away after you read it once.

**Comment by YuriSolovyov** [comment]
Confirmed, pretty confusing

**Comment by izuzak** [comment]
This issue was moved to atom/release-notes#36
