### ISSUE TITLE
No results when searching rvm gems directory (multi-user install)

### ISSUE THREAD

**Issue by glampr** [atom/atom#6615]
I have install rvm (doing a multi-user install) into /usr/local.
Then I created gemsets for each of my projects.

When opening a gem's directory with atom
```EDITOR=atom bundle open [gem_name]``` and try to search something with cmd+shift+f nothing ever shows up in the results even though the search term exists in several files.

Could this be an issue with file/directory permissions due to the multi-user install?
Any ideas how to debug/fix?

**Comment by izuzak** [comment]
Hey @glampr :wave: 

> Any ideas how to debug/fix?

1. Provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) :newspaper: 
2. See if you can [debug this yourself](https://atom.io/docs/latest/hacking-atom-debugging) :fishing_pole_and_fish: 
3. If not, try reproducing the problem in other projects/folders -- do you see the same problem there? If so, can you provide more specific steps to reproduce this on a simpler example? 
4. Can you clarify why you're using `atom bundle open [gem_name]` to open a folder, and not just `atom [gem_name]`?

**Comment by glampr** [comment]
4. ```bundle open [gem_name]``` open the gem's directory without having to specify the full path.
eg. ```EDITOR=atom bundle open rgeo``` is the same as writing ```atom /usr/local/rvm/gems/ruby-2.2.0@project/gems/rgeo-0.3.20``` (bundle knows wher the rgeo gem is installed to).

3. Moving the same folder to e.g. my desktop solves the issue.
When opening the folder at ```/usr/local/rvm/gems/ruby-2.2.0@project/gems/rgeo-0.3.20``` the filenames are displayed grayed out. I'm guessing this is an indication for something gone wrong, although clicking on a filename displays the contents of the file.

![screen shot 2015-06-01 at 16 41 43](https://cloud.githubusercontent.com/assets/470610/7922887/356778ec-087d-11e5-95a5-a6b4469fc15f.png)

Moving the folder to my desktop and opening it works ok.

![screen shot 2015-06-01 at 16 43 37](https://cloud.githubusercontent.com/assets/470610/7922931/8d2146b2-087d-11e5-8492-5f2ea167ada7.png)

Both folders have the same permissions:
```drwxrwsr-x   5 root    rvm     306B Apr 15 19:14 rgeo-0.3.20```
and my account is part of the rvm group.

1. Using the latest version 0.240 on Mac OS X Yosemite 10.10.3

**Comment by lee-dohm** [comment]
It appears that `bundle open [gem name]` doesn't respect environment variables passed on the command line. I have `EDITOR` set to `atom --wait` in my profile and tried, `EDITOR=vi bundle open [gem name]` and the Gem I listed opened in Atom.

**Comment by lee-dohm** [comment]
I also just tried this:

```bash
$ EDITOR=vi
$ echo $EDITOR
vi
$ bundle open pry
```

And pry opened in Atom. So perhaps it launches a copy of your shell without inheriting the local environment and opens that?

**Comment by glampr** [comment]
@lee-dohm this seems irrelevant with the issue I'm having, but could it be that you have the env variable ```BUNDLER_EDITOR``` set to atom?

**Comment by lee-dohm** [comment]
No, `BUNDLER_EDITOR` is empty.

I was simply trying to follow what I understood to be the steps to reproduce your issue. If you can provide us with simplified repro steps that isolate your exact issue, I would be happy to try those.

> the filenames are displayed grayed out. I'm guessing this is an indication for something gone wrong,

It is an indication that the files/folders are ignored by the `.gitignore` file that applies to them. This could also be why trying to do a Project Find on those files isn't working. Try unchecking "Exclude VCS Ignored Paths" in the basic Settings View and see if that fixes it:

![exclude-vcs-ignored-paths](https://cloud.githubusercontent.com/assets/1038121/7926864/33843794-088d-11e5-9ffe-29445d35cfbb.png)

**Comment by glampr** [comment]
You are right! That options was causing this! When it is unchecked searching works as expected!!
Thank you!

**Comment by glampr** [comment]
Maybe it should say "Exclude VCS Ignored Paths from search results" ?

**Comment by lee-dohm** [comment]
It excludes ignored paths from more than just the search results. It's kind of a catch-all for search results, fuzzy-finder and I think one more thing. It could use a description that makes it more clear.

**Comment by tony-h** [comment]
This seems to be a hidden and vague setting and I'm glad I came across this page. As soon as I unchecked the ''Exclude VCS Ignored Paths'', the results showed up. I'm running Win8 and working in the active git directory (i.e. not searching for items in the excludes list, in the .git folder, or searching outside of the project directory). Why this works or this does is beyond me. I’m not searching the .git (ignored paths) directory, so it is baffling why this should be unchecked. Providing a tooltip/description for this setting or renaming it so it is clear could be helpful for future users.

**Comment by lazyatom** [comment]
This behaviour makes Atom far less useful when used in combination with commands like `bundle open`; searching within a bundled gem is basically impossible unless this value is toggled.

The behaviour I'd expect is for Atom to respect `.gitignore` if it's present at the root of the current project/tree-view, but not to search upwards if I've explicitly opened Atom with a root directory that's within an ignored path. Does that make sense?

**Comment by hooverlunch** [comment]
Agreed. In my case, atom is searching all the way up to the .rbenv directory which is under git version control.
