### ISSUE TITLE
An idea for easing the coming deprecation apocolypse

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#6617]
I have an idea for reducing the number of deprecations that make it to June 1.  See this [thread](https://discuss.atom.io/t/deprecated-atom-apis-will-be-removed-on-june-1st/16526).

I am considering gathering a list of all deprecated method names and then writing a utility that scans the source of a package for remaining deprecations.  This would find all of them instead of the current process that misses ones not hit during testing.

This idea gets kind of weird.  I'm considering running it automatically on *all* published packages and emailing the authors who still have offending code.  The email would contain an easy-to-use list of offenses with file-names/line-numbers and some surrounding lines of code.

Comments?  Should I do this?

**Comment by thedaniel** [comment]
> I'm considering running it automatically on all published packages and emailing the authors who still have offending code. 

Absolutely do not send anyone unsolicited email.

**Comment by izuzak** [comment]
I :clap: your motivation to help other package authors, @mark-hahn :heart: 

> ... and emailing the authors who still have offending code

I'd discourage this approach. There are two reasons: 
* you will not find an email address for all users (not all users have a public email address)
* most users will not be happy about unsolicited emails

Instead, you might consider a different approach: 
* run your script on packages and collect the data on deprecated calls
* create a list of packages and deprecated calls you found
* annotate the list with existing issues for deprecated calls created in the GitHub repositories for each package in which you found deprecated calls
* order the list in a helpful way (e.g. by number of stars or downloads)
* publish the list somewhere (e.g. in a gist and put the link on https://discuss.atom.io/) and invite the community to contribute pull requests to those packages to fix those deprecated calls. 

That way, you use :computer: to automate most things, but leave the communication and interaction part to humans :family:, which should be a much better experience.

**Comment by mark-hahn** [comment]
> annotate the list with existing issues for deprecated calls created in
the GitHub repositories for each package in which you found deprecated calls

I don't know how to automate this.  I wasn't offering to do manual labor.
 (grin)

> publish the list somewhere

My experience with packages is that getting word out to users about useful
things like this is nearly impossible.  That is why I considered emailing
them.  I personally don't think getting a single useful email is a problem
but I'll defer to your judgement.

Lacking some way to disseminate the info, I'll probably shelve the idea.
If there was some assurance the word would get out I'd consider this.
Maybe a blog entry.

**Comment by izuzak** [comment]
> >  annotate the list with existing issues for deprecated calls created in

> I don't know how to automate this.

You could look at how the [Notifications package](https://github.com/atom/notifications) figures out if there's an existing issue before showing you a button to create a new issue when an exception is thrown. (Spoiler alert: it uses the [GitHub API](https://developer.github.com/v3/)).

> I personally don't think getting a single useful email is a problem but I'll defer to your judgement.

It's a judgement based on experience from working in GitHub support, just to make that clear. 

> If there was some assurance the word would get out I'd consider this. Maybe a blog entry.

We can't offer that assurance.
