### ISSUE TITLE
Atom crashed with SIGSEGV in Hunspell::spell()

### ISSUE THREAD

**Issue by vladzzag** [atom/atom#6621]
Sometimes Atom is crashing at the startup.
# Basic information:
- Atom version: 0.194.0
- OS: Ubuntu 15.04 x64
- Desktop environment: Unity

# Apport info:
- Title: Atom crashed with SIGSEGV in Hunspell::spell()
- SegvAnalysis:
```
 Segfault happened at: 0x7fb4e3da82de <_ZN8Hunspell5spellEPKcPiPPc.part.5+62>:	mov    0xd4(%r12),%r8d
 PC (0x7fb4e3da82de) ok
 source "0xd4(%r12)" (0x000000d4) not located in a known VMA region (needed readable region)!
 destination "%r8d" ok
```
- SegvReason: reading NULL VMA
- Stacktrace:
```
 #0  0x00007fb4e3da82de in Hunspell::spell(char const*, int*, char**) [clone .part.5] () from /usr/share/atom/resources/app.asar.unpacked/node_modules/spell-check/node_modules/spellchecker/build/Release/spellchecker.node
 No symbol table info available.
 #1  0x00007fb4e3da5f34 in spellchecker::HunspellSpellchecker::IsMisspelled(std::string const&) () from /usr/share/atom/resources/app.asar.unpacked/node_modules/spell-check/node_modules/spellchecker/build/Release/spellchecker.node
 No symbol table info available.
 #2  0x00007fb4e3da5721 in (anonymous namespace)::Spellchecker::IsMisspelled(v8::FunctionCallbackInfo<v8::Value> const&) () from /usr/share/atom/resources/app.asar.unpacked/node_modules/spell-check/node_modules/spellchecker/build/Release/spellchecker.node
 No symbol table info available.
 #3  0x00007fb4f28557e1 in ?? () from /usr/share/atom/libchromiumcontent.so
 No symbol table info available.
 #4  0x00007fb4f287ad4b in ?? () from /usr/share/atom/libchromiumcontent.so
 No symbol table info available.
 #5  0x00003b7478b071bb in ?? ()
 [......]
```

**Comment by aboulch** [comment]
Hi,
Same crash for me on :
- Ubuntu 15.04 x64
- Desktop Unity

**Comment by klaszlo** [comment]
Same on Ubuntu 14.10 with Desktop unity.

How to temporary disable hunspell in atom?

**Comment by Fank** [comment]
Duplicate with some information: #6639

**Comment by izuzak** [comment]
cc @kevinsawicki @zcbenz for :eyes: on these crash reports which seem to be caused by the spellchecker

**Comment by Fank** [comment]
Maybe related to #6504

**Comment by bilderbuchi** [comment]
getting the same thing. probably, the "linux" label should be added to this issue?

**Comment by bsmr** [comment]
I have the same, or similiar problem on various Ubuntu 14.04 64bit boxes (at home, and at work).

It is not the same problem, because I observed that the core dump is not necessarily generated on startup. It looks like it happens only if a certain class of files is opened. For example I didn't get any core dumps opening Elixir or Erlang source files.

The "at startup problem" may be only the cause of the files being reopened that were opened in the previous atom session.

As I am pretty new to atom: is the spellchecker always activated when opening a file, or only on special file types?

**Comment by winnieXY** [comment]
I've can confirm a segfault opening .tex files:

 segfault at d4 ip 00007f92fbf82358 sp 00007fff75e4c900 error 4 in spellchecker.node[7f92fbf74000+53000]

Any hints how to debug this for more helpful informations?
