### ISSUE TITLE
Some dropdown menus in the settings page appear at wrong place

### ISSUE THREAD

**Issue by vramana** [atom/atom#6622]
I am using atom 194.0 on Ubuntu 14.04 I have seen this bug in a past few versions of atom.  It occurs sporadically. When I change the theme of UI, today it didn't occur. But sometime back when I reloaded atom, the bug was still there. I checked my console there are no errors. Regarding this.

![lkvm9yg](https://cloud.githubusercontent.com/assets/3112509/7445103/7b83dacc-f1c2-11e4-9d03-52fb0618d394.png)

**Comment by mnquintana** [comment]
Can you try updating to the latest version of Atom (0.196.0) and see if you still experience this issue?

**Comment by vramana** [comment]
@mnquintana I am using webupd8 ppa for Atom. They didn't update to 0.196.0 yet. Let me install atom manually. I'll report it, if I see anything.

**Comment by vramana** [comment]
I have upgraded to latest version. Everything is working well.

**Comment by mnquintana** [comment]
Thanks for the update @vramana!

**Comment by vramana** [comment]
@mnquintana I saw the problem again. Attaching the screenshot.

![screenshot from 2015-05-05 12 50 02](https://cloud.githubusercontent.com/assets/3112509/7468383/8186fdc8-f325-11e4-9004-a466115a5761.png)

**Comment by mehcode** [comment]
I can reproduce this (on the latest version) on ubuntu / unity if I close a fully maximized atom and then re-open. Drop-down on settings are all mis-aligned. Closing a non-maximized atom and then re-opening doesn't cause this problem to appear.

This is with `atom --safe` as well.

**Comment by vramana** [comment]
@mnquintana The same type of bug is happening with this dropdown as well  
![screenshot from 2015-05-17 10 53 02](https://cloud.githubusercontent.com/assets/3112509/7669202/0ab7493e-fc83-11e4-89a8-3c469707da76.png)

**Comment by jlbooker** [comment]
I installed v1.1.0 from RPM today, and now I'm noticing this on the 'Tab Length' and 'Tab Type' fields. I'm running Fedora 20. The screenshot below is what happens when I click on the Tab Length dropdown.
![atom-settings-drowndown-position-bug](https://cloud.githubusercontent.com/assets/3429673/10891400/cec57dd8-816b-11e5-87db-cd3cab9db383.png)

**Comment by krrg** [comment]
I have been able to consistently reproduce this issue on Fedora 22 and 23 with Gnome 3.18.

If I open atom from the terminal (by running `atom .` or `atom`), and it opens up already maximized, then all the dropdowns are misaligned.  If however, I un-maximize, then remaximize the window, then magically the dropdowns are fixed.

![screenshot from 2016-01-23 13-22-20](https://cloud.githubusercontent.com/assets/8496492/12532586/ead2bb22-c1d4-11e5-91d2-74149ca5eb29.png)
![screenshot from 2016-01-23 13-22-39](https://cloud.githubusercontent.com/assets/8496492/12532587/f213d70e-c1d4-11e5-920f-8970c6727850.png)



If I had to guess, when Atom first starts up, it makes some default assumptions about the window geometry that end up not being true when the window is maximized.  If I close Atom with the window *not* maximized, then it will reopen not-maximized, and most importantly, with the drop down menus all aligned correctly.  

So for me, this is only happening with the window being maximized.

At any rate, I have reproduced this on three different machines on three different fresh installs of Atom.  Therefore, I am fairly certain this behavior can be reproduced.

**Comment by albertocalmeida** [comment]
I was about to post this issue but it happens exactly as described by @krrg. 

![captura de ecra de 2016-03-30 15-28-13](https://cloud.githubusercontent.com/assets/8570590/14145824/354694b6-f68d-11e5-99ca-90d48fb881cf.png)
![captura de ecra de 2016-03-30 15-28-52](https://cloud.githubusercontent.com/assets/8570590/14145832/3a7bc744-f68d-11e5-849f-63ddbedf4d37.png)

Running Atom 1.6.0 on Ubuntu 15.10.
