### ISSUE TITLE
Atom.io pages should have dynamic page titles

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#6624]
![atom page titles](https://cloud.githubusercontent.com/assets/823545/7445686/708f4458-f18b-11e4-82bb-b6385950ef96.png)

Those are all different pages on atom.io – no idea which is which. Pages on atom.io should have dynamic titles to reflect their content to avoid this kind of tab hell.

**Comment by 50Wliu** [comment]
:+1:

**Comment by RodrigoEspinosa** [comment]
:+1:

**Comment by 50Wliu** [comment]
For clarification, this only seems to happen on the API pages, not the flight manual, release notes, etc.

**Comment by mnquintana** [comment]
It does happen with the [Flight Manual's Table of Contents page](https://atom.io/docs/v0.196.0/) and can happen with the Flight Manual's other pages too if navigated to from the Table of Contents (my guess is because the pages are loaded with pjax, which isn't pushing the new page title - a reload does load the correct page title).

This (all in all) applies to:
- API Docs
- Flight Manual (if navigating from Table of Contents)
- Roadmap

**Comment by dorian-marchal** [comment]
In the meantime, here is a tiny userscript to fix that : 
https://gist.github.com/dorian-marchal/d9352bb20ca4fb915fd7

I only tested it on the main pages of the API, so it might need some fixes.

To install it, you'll need [GreaseMonkey](https://addons.mozilla.org/fr/firefox/addon/greasemonkey/) (Firefox) or [TamperMonkey](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo) (Chrome).

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#17
