### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientWidth' of null

### ISSUE THREAD

**Issue by element15** [atom/atom#6630]
[Enter steps to reproduce below:]

1. Widen navigation pane beyond a certain point

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'clientWidth' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane-resize-handle-element.js:72

TypeError: Cannot read property 'clientWidth' of null
  at atom-pane-resize-handle.PaneResizeHandleElement.resizePane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-resize-handle-element.js:72:42)

```

### Commands

```
     -2:09.5.0 application:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:54.6.0 pane:close (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontFamily": "Menlo",
    "scrollPastEnd": true,
    "tabLength": 4,
    "fontSize": 12
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.1
minimap, v4.8.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
> Widen navigation pane beyond a certain point

Thanks for the report, @element15. Can you clarify what this means exactly? I've tried resizing different parts of Atom and Atom itself several times and wasn't able to trigger the problem. If you can reliably reproduce this -- could you include a short GIF which demonstrates how to reproduce the problem? There's a nice little utility I use for recording GIFs: http://www.cockos.com/licecap/. 

Also cc @liuxiong332 who worked on pane resizing (seems like that's where things are :boom:), and @nathansobo who might have thoughts.

**Comment by element15** [comment]
My apologies, but I have not been able to reproduce the problem. I thought the information provided by Atom would be better than nothing. All I know is that I went to resize the navigation pane with a project open, and once I reached a certain point the error occurred. The same error was thrown when I attempted to resize the pane.

I restarted and all has been well sense, I have tried everything I can think of to reproduce this, and will try to provide more detail if it happens again. I was in fullscreen, and had the same instance of a file open in three panes in addition to the navigation pane at the time. No packages were enabled.

I'm rather new to the issue tracker on Github, and I found nothing to add other users to a thread, so I assume mentioning a user is what you meant.

cc: @nathansobo @liuxiong332

**Comment by izuzak** [comment]
@element15 Thanks for the details! Just to make sure I understand -- what are you referring to exactly when you say "navigation pane"? Is that the [tree view](https://github.com/atom/tree-view) on the left side or something else?

> I'm rather new to the issue tracker on Github, and I found nothing to add other users to a thread, so I assume mentioning a user is what you meant.

Oh, nice -- welcome! :wave: :smile: When you @-mention a GitHub user, that causes two things: 1) these users get [notified](https://github.com/settings/notifications) of your message and 2) they are subscribed to the thread in which they are @-mentioned so they receive notifications of all new comments on that thread. Basically, it's a way to address someone and automatically subscribed for updates on that thread.   So, once they've been mentioned -- no need to mention them again, except if you want to address a question to them directly (e.g. multiple users have left comments, and you want to make sure the right user knows you are addressing them with a question).

**Comment by element15** [comment]
Yes, I was referring to tree view. 

Thanks for taking the time you have to address this seemingly minor issue. I'm glad to have found this project, it's clean, well put together, and I am free to use it as I please with all of the packages. Keep up the excellent work. :)
