### ISSUE TITLE
Uncaught Error: UnknownSystemError: Unknown system error, uv_pipe_open

### ISSUE THREAD

**Issue by jhong2023** [atom/atom#6632]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: UnknownSystemError: Unknown system error, uv_pipe_open

```
At net.js:137

Error: UnknownSystemError: Unknown system error, uv_pipe_open
  at Error (native)
  at new Socket (net.js:137:18)
  at createWritableStdioStream (node.js:519:18)
  at process.stdout (node.js:558:16)
  at ReadStream.Readable.pipe (_stream_readable.js:470:31)
  at /Users/hj/tools/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:281:29
  at /Users/hj/tools/Atom.app/Contents/Resources/app.asar/node_modules/fs-plus/node_modules/mkdirp/index.js:38:26
  at FSReqWrap.oncomplete (fs.js:77:15)

```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Just noticed https://github.com/atom/electron/issues/1429#issuecomment-94387004 from @zcbenz:

> The UnknownSystemError means something between OS X and Electron has interrupted the system call, it could be virus scanner or firewall software.

@kevinsawicki @zcbenz Should we be catching this in Atom somehow or is this a wontfix?

**Comment by mattfrey** [comment]
Hello, I am also getting this error having moved to the latest build of electron. For me it appears to be tied to trying to spawn a child process.

 All versions of electron produce this error reliably upon calling spawnChild(), and the most recent atom-shell as well. 

Going back to a binary release of atom shell (atom-shell-v0.21.2-darwin-x64) which I had been using before corrects the issue.

Interesting note is my colleague is running Yosemite and has no issues at all with the same code, while I am on Mavericks and have this problem. We don't know of any other variance in environment besides this.

**Comment by mattfrey** [comment]
I've verified that the issue appears starting in version 0.22.0 of atom-shell, 0.21.3 and prior do not have this problem.

**Comment by kevinsawicki** [comment]
> Should we be catching this in Atom somehow or is this a wontfix?

Probably be catching it, though the stack trace makes it difficult to know where in atom/atom it came from.

**Comment by Ivshti** [comment]
I can confirm that Mavericks has this while Yosemite does not. It's also pretty critical JS stops executing on this exception. I tried catching uncaughtException and it still doesn't help.

**Comment by Ivshti** [comment]
@zcbenz and everyone in the thread: it seems that the issue, at least for me, is induced by opening sockets with node.js net in the main app process. Particularly the single-instance pattern.

Without that, everything works fine.

**Comment by mattfrey** [comment]
I am also launching a new child process from main.js when the app launches

**Comment by Ivshti** [comment]
It's definitely related to using node.js system I/O functionalities in the main process. Weird that it's Mavericks only (at least that we know of)

**Comment by ZECTBynmo** [comment]
+1

**Comment by justinmchase** [comment]
:+1: 

I am also hitting this. I have a debugged it down to a specific line of code:

![screen shot 2015-07-23 at 3 29 04 pm](https://cloud.githubusercontent.com/assets/10974/8861480/2e97e208-3150-11e5-963e-1db7c1c610a3.png)

I am using the `remote` module in this second window to communicate via ilc with another window. This same code does work in windows I can confirm. This appears to blowing up when attempting to create a pipe, I'm not sure to where.

```
$ electron --version
v0.29.2
$ uname -a
Darwin Macintosh.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
```

Does anyone have a workaround?

**Comment by spprasad** [comment]
+1
