### ISSUE TITLE
Resize Side Panel

### ISSUE THREAD

**Issue by NicoTravassos** [atom/atom#6634]
Hey guys please see image below can you maybe auto re-size this panel you will understand what i mean if you see Image.

![capture](https://cloud.githubusercontent.com/assets/7794777/7450417/d77d3b66-f244-11e4-967d-85d912146d04.PNG)

**Comment by mehcode** [comment]
This sounds like you could really benefit from https://github.com/atom/tree-view/issues/125

**Comment by mnquintana** [comment]
Closing this in favor of atom/tree-view#125 - please subscribe there for updates.

In the meantime, you can double-click on the resize handle to make the Tree View fit its contents.
