### ISSUE TITLE
I save the file, but the view table is tips I did not save. 保存文件之后table上依然提示处于未保存的状态。

### ISSUE THREAD

**Issue by mingjunyang** [atom/atom#6635]
My atom is 0.196.0,openSUSE13.2 & Gnome 3.14.2.

I save file  use ```CTRL + S```.but the view table is tips the file is not save.
use command ```core:save``` is also.

![file](https://raw.githubusercontent.com/mingjunyang/myvimconf4c/master/file-do-not-save.png)

**Comment by izuzak** [comment]
@mingjunyang Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If so, can you share a screenshot which shows what the [keybinding resolver shows when you hit CTRL+S](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings)?

**Comment by mingjunyang** [comment]
okay.
I try ```atom --safe```, this problem disappear. 

I disable the ```atom-beautify```[atom-beautify](https://atom.io/packages/atom-beautify), problem disappear toooooo.

I use auto format  ```atom-beautify```. Perhaps I could see see  atom-beautify pages.

```python
 "atom-beautify":
    _analyticsUserId: "9821831b-a2aa-4903-a52f-3599aea0f6c0"
    js_keep_function_indentation: true
    css_newline_between_rules: true
    css_selector_separator_newline: true
    beautifyOnSave: true
```
 thank you!
