### ISSUE TITLE
spawn autopep8 ENOENT

### ISSUE THREAD

**Issue by curinir** [atom/atom#6636]
[Enter steps to reproduce below:]

1. Open Python file
2. Open Command Palette
3. Type in 'beautify'
4. Select 'Beautify' from list and hit 'Enter'

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

spawn autopep8 ENOENT

```
At spawn autopep8 ENOENT

Error: spawn autopep8 ENOENT
  at exports._errnoException (util.js:734:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -0:12.8.0 application:open (atom-pane.pane.active)
     -0:08.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.0 core:confirm (atom-text-editor.editor.mini)
     -0:02.1.0 beautify:beautify-editor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.26.4
autocomplete-plus, v2.12.1
autocomplete-plus-jedi, v0.0.9
go-plus, v3.3.9
hex, v0.6.1
jslint, v1.3.1
linter, v0.12.1
linter-csslint, v0.0.12
linter-pylama, v0.0.17

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@curinir Do you have autopep8 installed, as mentioned in the README for atom-beautify? https://github.com/Glavin001/atom-beautify#language-support

**Comment by benogle** [comment]
Closing in favor of https://github.com/Glavin001/atom-beautify/issues/311

**Comment by curinir** [comment]
I did not have autopep8 installed. I agree with the suggestion of making the error message cleaner though.

**Comment by fd** [comment]
I'm still seeing this error (I do have autopep8 installed)

**Comment by izuzak** [comment]
@fd Can you add a comment to the issue in  Glavin001/atom-beautify linked to above? You might also clarify in that comment how this is different from you previous report about things not working (which you were able to resolve): https://github.com/Glavin001/atom-beautify/issues/274#issuecomment-96967864

**Comment by Glavin001** [comment]
Thank you @izuzak and @benogle for receiving this issue and courteously dealing with it thus far.

@curinir and @fd, please send your Atom Beautify related issues to me at https://github.com/Glavin001/atom-beautify/issues and hopefully we can resolve them both. Thank you.

**Comment by curinir** [comment]
@Glavin001 My issue went away when I followed the instructions (i.e. install autopep8), so nothing more is required from me. I think it'd be beneficial to have an easy to understand message in that case though.

**Comment by Glavin001** [comment]
Great to hear, @curinir! 

I definitely want to make those messages clearer. See https://github.com/Glavin001/atom-beautify/issues/311 and https://github.com/Glavin001/atom-beautify/issues/165
