### ISSUE TITLE
zh_CN.utf8 cannot show

### ISSUE THREAD

**Issue by playaround88** [atom/atom#6637]
hi admin
i am a new atom user, i use atom as a node/less editor.
My system $LANG=zh_CN.UTF-8
i have set the file encoding and atom perferences encoding to utf8.
when i write an html test file(include chinese charactors), the atom pane show a square, but in the browser is right.
I guess maybe atom lack fonts to show chinese charactors.
thank you for your help!

**Comment by fcharlie** [comment]
@playaround88 This problem has been around for a long time but has not been resolved
