### ISSUE TITLE
Install task leads to undefined symbol: node_module_register

### ISSUE THREAD

**Issue by xasx** [atom/atom#6638]
After building Atom using
```
script/clean && script/build
```
I usually install Atom using
```
sudo script/grunt install
```

Which obviously succeeds, but logs a worrying error:

```
Loading "index.js" tasks...ERROR
>> Error: /mnt/vmstor/git/atom/build/node_modules/grunt-atom-shell-installer/node_modules/asar/node_modules/chromium-pickle/build/Release/pickle.node: undefined symbol: node_module_register

Running "install" task
Done, without errors.
```

Is there anything that can be done about this?
How can I be sure that my installation is not corrupted/incomplete in the end?

See also https://gist.github.com/xasx/91cde029a06c3f4bc4f3

**Comment by rustedwolf** [comment]
I same error installing ver. 0.200.0-e2f757e. Install went ok, but if there's an error, that means something went wrong.

**Comment by kevinsawicki** [comment]
I believe this has been fixed by https://github.com/atom/atom/commit/bd5403fe074ebd3f98bbf697edf3c1160e8a329e
