### ISSUE TITLE
Feature request: Option for max file-size for syntax highlighting

### ISSUE THREAD

**Issue by kylehotchkiss** [atom/atom#6642]
Hello!

I am a web developer so I sometimes need to handle concatinated files within my editor. This often locks atom from a few seconds to up to a minute, which is pretty hard on my workflow. Would it be possible for you guys to add an option for max-file size for syntax highlighting?

Problem files are often concatinated JS/CSS. Try [pasting this into Atom](https://raw.githubusercontent.com/misoproject/dataset/master/dist/miso.ds.deps.min.0.4.1.js). If you paste into new tab with no syntax highlighting it's fine. When you try to save as JS it locks up the editor.

Thanks!

**Comment by izuzak** [comment]
@kylehotchkiss Thanks for the feedback. I can't say if/when this might be added (I wouldn't expect that to be added to Atom in the near future by the core team), but just wanted to link to another issue which you're probably hitting: https://github.com/atom/atom/issues/979. Atom also has problems with very long lines, which seems to be the case with the file you linked. The "main" issue for large file support is here: https://github.com/atom/atom/issues/307.

**Comment by simurai** [comment]
Closing since this seems to be added in https://github.com/atom/atom/pull/7130.
