### ISSUE TITLE
Atom window can get stuck in "dev mode"

### ISSUE THREAD

**Issue by jessegrosjean** [atom/atom#6644]
- Atom will now restore your previous window state on restart.
- The serialization of the Atom window includes the "dev mode" flag.
- When you create a new window the "dev mode" flag is taken from any existing window. 

Together these things can have the effect of locking a user who doesn't know what's happening into dev mode.

https://discuss.atom.io/t/tip-how-to-stop-atom-from-always-opening-in-dev-mode/16576

**Comment by damieng** [comment]
This no longer seems to be the case - I am unsure when it got fixed.
