### ISSUE TITLE
Add Language-PowerShell to Atom Core?

### ISSUE THREAD

**Issue by russlescai** [atom/atom#6647]
I often use Atom to work with PowerShell files. It would be great if the Language-PoweShell package could be shipped with Atom core.

https://atom.io/packages/language-powershell

I understand a line has to be drawn somewhere, but I wanted to ask anyway to see if it was practical.

The main reason I would like it to be in core, is I sometimes want to edit them on servers, where setting  up apm is painful (authenticated proxies etc.) and not worth the hassle.

Thanks in advance :smile:

**Comment by damieng** [comment]
We are trying to limit the amount of included packages as the current list is very large. We have no plans to include PowerShell in the box at this time.
