### ISSUE TITLE
Focus of atom after opening file (Windows 7) 

### ISSUE THREAD

**Issue by christophfroehlich** [atom/atom#6649]
Windows 7, atom already opened with the window in the background. 
When I open a file via the explorer, the symbol in the task bar is blinking but atom doesn't come to the front.
Is this a wanted behavior? 

(I couldn't find any existing issue. If this is the case, please let me know)

**Comment by mnquintana** [comment]
Duplicate of #6614 – please subscribe there for updates.

**Comment by christophfroehlich** [comment]
Thanks!
