### ISSUE TITLE
Mini editors highlight injected grammars

### ISSUE THREAD

**Issue by postcasio** [atom/atom#6650]
When typing in a mini editor, any grammars that inject into `text.plain` (for example `language-todo`) are highlighted. This is a bit weird, I'd expect no highlighting at all in mini editors.

![screen shot 2015-05-05 at 12 53 30](https://cloud.githubusercontent.com/assets/1759837/7472014/de26dcc4-f325-11e4-9362-c522c758ad5a.png)

Maybe mini editors should use some other scope to prevent this.

**Comment by izuzak** [comment]
@postcasio I think this is a generalization of https://github.com/atom/language-todo/issues/11, right? Can you :pray: link to this issue from that issue, if I'm not misunderstanding this? Thanks! :heart_decoration:

**Comment by lee-dohm** [comment]
Somewhere in the intervening time this was fixed :+1:
