### ISSUE TITLE
Cursor position forgotten between tabs

### ISSUE THREAD

**Issue by AdamBuczynski** [atom/atom#6662]
When you are working in multiple files and going back and forth between the file tabs, the cursor position for that tab is forgotten and you can't type text right away.

This is rather frustrating behaviour, as it forces you to grab your mouse and click somewhere in the code before you can start typing.

Sublime remembers the cursor position per tab/file, so that when you go back to a tab, the cursor is at the position where you left off, and you can start typing right away.

Can this be enabled for Atom as well? I couldn't find a package that does it.

**Comment by veloxy** [comment]
:+1: 

I just switched to atom and I agree that it is very annoying that the cursor isn't remembered when switching tabs. (OSX)

**Comment by lee-dohm** [comment]
I can't reproduce this behavior using Atom v0.197.0-3c6e6e4 on Mac OS X 10.10.3. I have four tabs open (each with a cursor at a specific different position) and when I use <kbd>Ctrl+Tab</kbd> to switch between them, the cursor is always in the position where I left it for that tab.

Can you give a specific set of steps to reproduce the issue?

**Comment by mnquintana** [comment]
I can reproduce this in Atom 0.197.0-3c6e6e4 in safe mode on OS X 10.10.3 – basically, when you switch between tabs, the row where you left your cursor will be highlighted, but there will be no visible cursor, and trying to move the cursor with the arrow keys won't work.

I think this might actually be a fairly straightforward fix – looks like it's because switching tabs doesn't refocus the editor element.

**Comment by veloxy** [comment]
@mnquintana That is the issue I have, except it occurs when clicking the tabs, ctrl+tab works fine. (OSX 10.10.3, Atom 0.196.0)

![6jjjs6qgnd](https://cloud.githubusercontent.com/assets/491675/7492711/1bd771b6-f3fb-11e4-8ea8-19a781174399.gif)

**Comment by andya9** [comment]
I can confirm the bug as it happens to @veloxy (i.e. it only occurs when clicking, not when ctrl-tabbing)

**Comment by mnquintana** [comment]
@veloxy or @andya9 Would you mind posting a screencap with <kbd>Ctrl-Tab</kbd>? I do get the same issue with <kbd>Ctrl-Tab</kbd> so I want to get a better idea of what it looks like for you.

**Comment by veloxy** [comment]
This is the behavior with <kbd>Ctrl-Tab</kbd>, the cursor keeps its position and i can just start typing after ctrl-tabbing to a different tab.

![atom-ctrl-tab](https://cloud.githubusercontent.com/assets/491675/7499521/81c1d14c-f428-11e4-82e9-1cae02612104.gif)

The issue with clicking also occurs on Windows 8.1

**Comment by AdamBuczynski** [comment]
I can confirm that using ctrl-tab does not have this problem, just clicking on the tabs seems to trigger it (max os x).

**Comment by andya9** [comment]
I am on linux, so it seems to affect every os

**Comment by KeitIG** [comment]
as @izuzak noticed, it is due to tabs#124

**Comment by nathansobo** [comment]
Will be fixed in 0.209.0. Sorry for the hassle on this one everybody.

**Comment by AdamBuczynski** [comment]
Cheers thanks

**Comment by deeperx** [comment]
@nathansobo is it fixed? still continues here with os x el capitan.

**Comment by adambuczynski** [comment]
@deeperx Since this was fixed last year, I haven't run into this issue anymore.
Not experiencing it now either, on OS X 10.11.5 with Atom 1.9.0-dev-7253514

**Comment by pcnate** [comment]
I just upgraded 1.9 on Debian 8.5 and I have been having the issue.... Did not seem to have the issue on Win 7 at work today on atom 1.9.

**Comment by rmbaad** [comment]
I have this issue on OSX El Capitan and Atom 1.14.3

**Comment by laradevitt** [comment]
@rmbaad - Works for me on OSX El Capitan and Atom 1.14.4 (just installed today). I can cycle through tabs by clicking or CMD-SHIFT-] or CMD-SHIFT-[ and the cursor position is remembered and in focus. If I could test CTRL-TAB I would but I have so far been unable to get this shortcut working for me. :(

**Comment by inancgumus** [comment]
Looks like it's been fixed. At least I see the correct behaviour in Atom 1.12.8 and OS X 10.12.3 (Sierra).

**Comment by adamreisnz** [comment]
Still working for me in Atom 1.16.0

**Comment by ContentLabs** [comment]
Still not working for me: When clicking on tabs the cursor position is kept, using the keyboard, the fosus is set on the tree view. Atom 1.15 on Windows 10.

**Comment by Ben3eeE** [comment]
@ContentLabs That can be a different issue https://github.com/atom/tree-view/issues/858. Try disabling `Focus On Reveal` in the `tree-view` package settings.

**Comment by ContentLabs** [comment]
@Ben3eeE Wow, thank you, that fixed it for me!

**Comment by lonelyelk** [comment]
This bug still exists in atom 1.18.0 x64 macOS Sierra 10.12.5 if another pane is cursor-less. For example, open a text file to edit and then open Atom > About Atom pane. Switching from text file to the "About" pane with keyboard Cmd-Shift-[ or Cmd-Alt-Arrow looses cursor position. Switching with mouse click on the pane name doesn't.

**Comment by lee-dohm** [comment]
@lonelyelk Please open a new issue and fill in all of the required information.
