### ISSUE TITLE
Option-Click on code fold arrow (bug/enhancement)

### ISSUE THREAD

**Issue by whoughton** [atom/atom#6663]
When option-clicking an arrow in the gutter for code folding I expect it to do a recursive fold at that level, as of right now that functionality is not implemented. As an example if I am at the root of a class with methods and I option click on the class-level arrow I would expect it to act as the "Fold All" command. But if I were to only option-click on the private label (in say a ruby class) I would expect it to fold the entire private section AND all underlying methods.

Unsure if this would be a bug or enhancement, assuming the latter.

**Comment by lee-dohm** [comment]
This is something that we think would be a useful feature. Unfortunately, we have other higher priority things to work on at this point. We would definitely be interested in a well-written pull request addressing this, so I'll mark it `help-wanted` so it is easy for people wanting to contribute to find.

Thanks for the suggestion!
