### ISSUE TITLE
build error on Windows7 64bits. (gyp error)

### ISSUE THREAD

**Issue by uropsm** [atom/atom#6667]
Hello, 

I read the same issue report that saying it's already solved. (#6436)
I tried to build on the latest version. But the same error happens to me.
Please help.
Thank you. 

------------- build log --------------
Node: v0.12.2
npm: v2.5.1
Python: v2.7.0
Installing build modules...
child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\test\atom\build\node_modules\npm\n
ode_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\test\\atom\\build\\node_modules\\npm\\node_modules\
\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\test\atom\build\node_modules\minidump
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\test\atom\build\node_modules\npm\n
ode_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\test\\atom\\build\\node_modules\\npm\\node_modules\
\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\test\atom\build\node_modules\runas
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\test\atom\build\node_modules\npm\n
ode_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "D:\\test\\atom\\build\\node_modules\\npm\\node_modules\
\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\test\atom\build\node_modules\grunt-atom-shell-installer\node_mod
ules\asar\node_modules\chromium-pickle
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "D:\\test\\atom\\build\\node_modules\\npm\\bin\\npm-cli.js"
 "--userconfig=D:\\test\\atom\\build\\.npmrc" "install" "--loglevel" "error"
npm ERR! node v0.12.2
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! minidump@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the minidump@0.8.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the minidump package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls minidump
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\test\atom\build\npm-debug.log

**Comment by uropsm** [comment]
The problem seems to be from minidump.
Please let me know what more information should I bring.

**Comment by 50Wliu** [comment]
@zcbenz

**Comment by zcbenz** [comment]
Can you paste the content of `npm-debug.log`?

**Comment by uropsm** [comment]
Thank you for reply.
I tried to change python version. It gave all different error log by each version.
below logs is from python 2.7.6.

the build log is below
https://www.dropbox.com/s/eqt1gqjt802ftns/build_log.txt.txt?dl=0

and It's npm-debug.log
https://www.dropbox.com/s/yipqt9tf0msbler/npm-debug.log?dl=0

I also tried VS2013 (I used 2010)
installed VS2013 and did $env:GYP_MSVS_VERSION=2013.
the build has passed much compared to before. finally build failed though.
https://www.dropbox.com/s/eoeflbvvmy93ap2/buildlog_with2013.txt?dl=0
when trying ./script/build --stack
https://www.dropbox.com/s/1pcrnpbfef6g9dw/buildlog_with2013-2.txt?dl=0

Is there a correct versions of all environment for current version?
I think I need to clean my win7 environment and re-install everything correctly.

**Comment by uropsm** [comment]
I solved it.

What i did.
- uninstall VS2010, and re-install Window sdk 7.1 and sdk update. 
It seems that pre-installed VS2010 blocks correct SDK installation.
SDK must be installed in advance.

- build with VS2013
VS2013 is needed for win7 64bits (Guide says 2010 though)

my environment is dirty now, i'm not sure the correct sequence
i'll try agiain later with clear win7.
Thank  you.

**Comment by batjko** [comment]
> build with VS2013
> VS2013 is needed for win7 64bits (Guide says 2010 though)

Were you able to replicate these steps after cleaning your environment?
If so, we might want to update the instructions if necessary.

**Comment by one-more-minute** [comment]
I appear to be having the same issue on Windows 10 x64. Going into `build/` and running `npm install` yields a more specific error: 

> C:\Users\Mike\Documents\GitHub\atom\build\node_modules\minidump\build\minidump.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The `V110` folder exists but the specified file does not. Any idea where it should have come from? I will try playing around with my Visual Studio installation to see if I can get it.

**Comment by one-more-minute** [comment]
Fiddling around with my Visual Studio installation, it seems like the C++ tools are not installed by default. Enabling the Windows 8 SDKs seems to make the V110 folder appear properly and fixes the above error but the build still fails. This is also reproducible by cloning node-minidump and running `npm install`, so I will open an issue over there.
