### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/home/yajo/Documentos/devel/docker/odoo-grupoesoc/addons/odoo-grupoesoc-addons/event_seats_per_regsitration/models.py'

### ISSUE THREAD

**Issue by Yajo** [atom/atom#6670]
[Enter steps to reproduce below:]

1. cd /home/yajo/Documentos/devel/ && atom

**Atom Version**: 0.196.0
**System**: linux 3.19.1-201.fc21.x86_64
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/yajo/Documentos/devel/docker/odoo-grupoesoc/addons/odoo-grupoesoc-addons/event_seats_per_regsitration/models.py'

```
At events.js:141

Error: ENOENT: no such file or directory, open '/home/yajo/Documentos/devel/docker/odoo-grupoesoc/addons/odoo-grupoesoc-addons/event_seats_per_regsitration/models.py'
    at Error (native)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  },
  "editor": {
    "softWrap": true,
    "fontSize": 14,
    "tabLength": 4,
    "showIndentGuide": true,
    "invisibles": {},
    "preferredLineLength": 79
  }
}
```

### Installed Packages

```coffee
# User
linter, v0.12.1
linter-flake8, v1.4.0
linter-xmllint, v0.0.5
minimap, v4.8.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.1
minimap-selection, v4.2.0
sync-settings, v0.2.2

# Dev
No dev packages
```

**Comment by Yajo** [comment]
The fun thing is that the file exists.

**Comment by thomasjo** [comment]
Are you able to reproduce in [safe mode](https://atom.io/docs/v0.196.0/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by Yajo** [comment]
Not, and after that, neither without safe mode... Weird.

**Comment by thomasjo** [comment]
OK, then I'll close it for now. If you're able to (reliably) reproduce the problem, please re-open the issue.
