### ISSUE TITLE
Auto Indent isn't idempotent

### ISSUE THREAD

**Issue by AsaAyers** [atom/atom#6671]
I'm using Atom 0.196.0 on Ubuntu. I thought it might have been a plugin causing the problem, but you can see from the video below that the bug exists in safe mode too.

It seems like I can pretty reliably get Auto Indent to do the right thing if I strip all indentation before triggering it. I know this was working in 0.188, but because you don't [provide a PPA](https://github.com/atom/atom/issues/2956) or any other [automated update mechanism](https://github.com/atom/atom#debian-linux-ubuntu) I don't get every version.

![autoindent](https://cloud.githubusercontent.com/assets/324999/7495413/c71c54ee-f3db-11e4-9ae1-015be3e722f8.gif)

**Comment by muppetjones** [comment]
Continuation of an ongoing indentation problem: [here](https://github.com/atom/atom/issues/6655)
