### ISSUE TITLE
scrolling behavior while mouse-selecting whole lines of text is hard to control

### ISSUE THREAD

**Issue by ntuckerxx** [atom/atom#6675]
Atom v.0.196.0
Mac OS X 10.10.3

Trying to select text that spans more than just the visible scroll region is much more difficult in Atom than in other editors when selecting entire lines because of the auto-scrolling behavior.  When you stretch a selection past the edge of the scroll region, the editor scrolls to accommodate you, but once you overshoot your destination, pulling back starts scrolling back in the other direction even though it's not necessary.  Most other editors will only scroll when necessary.

Steps:
1. open a file that is at least twice as long as what you can display in your window
2. make sure you're scrolled to the top
3. triple-click and hold somewhere to begin selecting entire lines
4. drag down just past the bottom of the window, causing the window to scroll
5. once you've scrolled all the way to the bottom (it's important here that you scroll at least past the point where the top of the selection scrolls out of the window), pretend you overshot the bottom of what you wanted selected by a few lines and you actually want the selection to end at the 10th line from the bottom of the file.  continue to hold the mouse button down while you move your mouse back up to that line.
6. observe that if you move your mouse up past about the 4th line from the bottom of the window, it actually starts scrolling back up and will keep going until the top of your selection is visible.  This makes it difficult to get the selection to stop on a specific line because you have to time the scrolling to get your target line within 4 lines of the bottom of the window.

Expected: after mouse movement downward causes a scroll, moving the mouse back up into the window should not cause scrolling back in the other direction unless you attempt to move the end of the selection past the top of the visible part of the file.

**Comment by thomaslindstrom** [comment]
:+1: I'm having this issue too. http://cl.ly/1T3G1C42173m/atom-weird-scroll-behaviour.mov

**Comment by WoodyWoodsta** [comment]
I'm having this issue on Atom 1.0.0 (Windows 8.1). Referenced issue #6722 is not the same bug. This particular bug prevents one from selecting code that is more than a page/screen long.

**Comment by nathansobo** [comment]
This will be fixed in `1.0.4`.
