### ISSUE TITLE
excludeVcsIgnoredPaths: false seems to be ignored

### ISSUE THREAD

**Issue by ascariandrea** [atom/atom#6677]
Hi all,
first of all I would make my congrats for your project.
I leave SBT3 for your editor and I'm proud of my choice.
However i'm experiencing a bug on `excludeVcsIgnoredPaths` setting in config file.
The problem is that even if is set to false the project tree doesn't show the ignored files and folders in the root directory.
I tried to close and reopen the project but it didn't work.
My Atom version is 0.196.0.

I hope this help you solving the problem,
thanks in advantage.

Have a nice coding day.

**Comment by 50Wliu** [comment]
Could you please see if Settings->Packages->Tree View->"Hide VCS Ignored Files" is checked?

**Comment by ascariandrea** [comment]
Ok, that was the mistake.
Sorry for the issue, but I didn't find that setting before.
