### ISSUE TITLE
Change open buffer file path when cutting and pasting files #feature

### ISSUE THREAD

**Issue by dvc94ch** [atom/atom#6679]
At the moment when you cut and paste from within the atom ui, open buffers still point to the old location. When you save it recreates the old file, even if you didn't actually change the contents of the buffer. I think this would be very useful since 1. it's common to check the content of a file before moving it. 2. When you select the file to cut/paste it opens a buffer anyway, before you right click cut.

**Comment by lee-dohm** [comment]
Should this be on the [tree-view package](https://github.com/atom/tree-view)? I assume you're talking about cutting and pasting files listed in the tree-view?

**Comment by izuzak** [comment]
@lee-dohm Yeah, I think it should be on the tree view package, based on the provided information. But before we move it, I'd like to ask @dvc94ch to clarify a few things. :smile: 

@dvc94ch I'm having trouble reproducing this behavior. Can you please provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) -- the Atom version and OS you're using? Also, can you check if you can reproduce this behavior after you disable the Autosave package in Settings View?

**Comment by dvc94ch** [comment]
OS: Fedora 21 Kernel 3.19.5-200.fc21.x86_64 Atom: 0.196.0
It does close the buffer after cutting and pasting, unless you haven't saved it yet.

**Comment by izuzak** [comment]
> It does close the buffer after cutting and pasting, unless you haven't saved it yet.

I'm sorry, I'm not sure I'm following -- is that the behavior you see when you disable the Autosave package? Here's what I'm seeing when I cut and paste a file in Atom:

![move](https://cloud.githubusercontent.com/assets/38924/7524162/66f6f77e-f500-11e4-9c4f-04af5fd31102.gif)

Notice that I cut/paste the file, edit it and save it, and it's still at the new location. Same happens if the file has changes which haven't been saved yet. 

Can you record a similar GIF which clearly demonstrates the problematic behavior?  Thanks

**Comment by dvc94ch** [comment]
I have autosave disabled. After pasting it closes the buffer.

![screencast from 07 05 2015 21-57-07](https://cloud.githubusercontent.com/assets/741807/7524773/a6df1a2a-f504-11e4-8d2a-ca2d20f147c8.gif)

**Comment by dvc94ch** [comment]
Here is one were after saving I have to files in different directories.

![screencast from 07 05 2015 21-54-02](https://cloud.githubusercontent.com/assets/741807/7525047/9cf48304-f506-11e4-83a2-0cdb47ef3dbc.gif)

So something weird is going on? I disabled all community plugins and autosave, and it's still doing this.

**Comment by dvc94ch** [comment]
Just as an update, I'm still having weird behaviour in atom 0.210.0. Now it includes having to close the buffer on generated files and reopening to see changes...

**Comment by dvc94ch** [comment]
I guess this can be closed, I'm on a different distro, someone can reopen it if necessary.
