### ISSUE TITLE
Font rendering

### ISSUE THREAD

**Issue by kupoback** [atom/atom#6681]
I'm having an issue on Windows 8.1

When I am coding, the font is not as clear as other text editors. 

![Here is what I see](http://i.imgur.com/xLhktNt.png) 

Compared to

![Brackets](http://i.imgur.com/yZRPXx1.png)

Before anyone says, well why not use the other, or anything along the lines of that, I can't use grunt on Brackets. It simply does not work. I like Atom as well, over Brackets. However, the font rendering is really hurting my eyes. I like my text around 11-12px but have to increase the size, just to go easier on my eyes.

Is there any CSS to help? I've tried 

    -webkit-font-smoothing: antialiased;

    -webkit-font-smoothing: none;

    -webkit-font-smoothing: none/antialiased/subpixel-antialiased;

but none of them make a difference. I am using Source Code Pro, but even Ubuntu, or Droid Sans, there's no difference.

**Comment by coopermaruyama** [comment]
I've been using this to get a similar effect: 	`-webkit-text-stroke: .02em;`

**Comment by kupoback** [comment]
Unfortunately that made it worse for me. I'll keep digging around.

**Comment by kupoback** [comment]
This is my current setup 

    `atom-text-editor {
   font-size: @font-size;
   text-rendering: optimizeSpeed;
   -webkit-font-smoothing: antialiased;`

**Comment by coopermaruyama** [comment]
Hmm, Is it at least adding thickness to the font?  Have you inspected to make sure the styles are applying? Maybe try adding `!important`? It definitely makes a significant difference for me.

**Comment by kupoback** [comment]
![Atom Before Adding Stroke](http://i.imgur.com/8q3SvVj.png)
![Atom After Adding In Stroke](http://i.imgur.com/STLUf28.png)

**Comment by coopermaruyama** [comment]
It's hard to tell but if you look at the comments you can see that it is working a little bit. Try going higher like .04em if you still want it to pop more. You can also add this as well: `text-shadow: 0 0 1px black`

**Comment by kupoback** [comment]
I tried text-shadow and playing with the text-stroke, just makes it a little more blurry and the text-shadow, after playing with the color, just looks way off. Thanks for those suggestions though.

**Comment by ozra** [comment]
I read somewhere that `-webkit-font-smoothing:` has been removed from chrome because it won't be in the css standard? I can't for the life of me get it to work. 
the result I want is the exact opposite to above; I want to remove anti-aliasing - it just looks blurry.
The fonts I use are very small and I want super crisp letters. It works in my terminals, and everywhere with fontconfig xml rules. But I don't know how to get it to work in Atom.
I love Atom - but this is a deal breaker. Is there any solution? I run Ubuntu 14.04 64b.

**Comment by coopermaruyama** [comment]
@ozra  I have spent lots and lots of time playing with font-smoothing as I had the same issue as you and have found that what works the best depends whether you have light bg or dark bg. 

With a dark bg and light text use `subpixel-antialiased` and with dark text on light bg either just default or `antialiased`. If you find it looks blurry, you can recreate the same thing by using `text-shadow: 1px 1px 1px rgba(0,0,0,0.004);`. This was for a dark background and I combine it with subpixel antialiasing and have found it to look ok. Maybe try that and play with the color value to be a bit darker than what your bg color is. I use source sans pro which is pretty thin at smaller fonts. Also try playing with `-webkit-text-stroke-width` and `-webkit-text-stroke-color` which strokes the edges both inside and out and use a bit darker color to get a more bold look without thickening the font. Here's a screenshot too of my setup, hopefully this is what you're going for:

![screenshot](https://s3.amazonaws.com/f.cl.ly/items/2M1J1r0K0O0E1g114617/Image%202015-05-23%20at%203.58.35%20PM.png)

**Comment by paulcbetts** [comment]
The problem is that Atom is applying a CSS transform effect to the buffer, which on OS X doesn't have a huge effect on text quality, but on Windows it makes everything into a blurry mess

**Comment by ozra** [comment]
@coopermaruyama - Hi. Figured I'd hop in here again. 
The thing is, as I've already stated, _I want to **remove** antialiasing_ - it works in **almost all apps in linux** but not in Atom, because of the webkit front. 

I assume the only way to get it working in Atom is if webkit re-implements `-webkit-font-smoothing: none`. But as it is now, Atom is un-usable for me. It doesn't matter how many wonderful features it has if it can't display text correctly on my system :-(
So now I'm using Sublime, which obeys the fontrules in linux perfectly. The fonts are super sharp - just as I've configured the system.

Until this is resolved, I'll have to stick with Sublime or other editors :-(

Keep up the good work. Aside from this it's a great project! I will look in again in the future and see if the bug is fixed.

**Comment by DarkNami** [comment]
Atom is more blurry after update to v0.206 (from v0.204) in my PC (Windows 7).

![blurry](https://cloud.githubusercontent.com/assets/5100919/8006570/cc9bf9b6-0bc7-11e5-93ea-a9b960ffdb9c.png)

**Comment by paulcbetts** [comment]
@nathansobo I believe you own this piece, can you have a look at this? This is really bad on Windows High DPI displays. It seems like https://github.com/atom/atom/issues/6681#issuecomment-104954287 is the root cause, removing it cleans up everything (but obviously breaks scrolling)

**Comment by kupoback** [comment]
I am running on a 1080p ViewSonic and loaded up Atom again, as I really need port 2222 support and grunt. 

Brackets lack support for 2222 and grunt doesn't work at all. However, the blurriness is even worse!

Here is Atom under Brackets...

![text blurriness](http://i.imgur.com/ZWTDyry.png)

**Comment by nathansobo** [comment]
@kupoback In 0.206 it got even worse. 0.207 should correct that. @paulcbetts is investigating a potential solution to blurriness in general. @as-cii We may need to reintroduce the option to disable GPU acceleration (which was never removed from settings :grimacing:) if we can't figure this out on Windows.

**Comment by kupoback** [comment]
I am up to date, running 0.2070.0 however nothings changed for me. I've cleared everything and installed fresh.

**Comment by nathansobo** [comment]
@kupoback My sincere apologies for wasting your time with a typo. I meant 0.208, which isn't out yet.

**Comment by kupoback** [comment]
Ooooh, @nathansobo you're far from wasting my time. Just thought I'd help give some feedback and see if there are some temporary solutions I can provide or we can come up with.

**Comment by kupoback** [comment]
Just wanted to comment that this update 0.208.0, font-rendering looks great! Thank you!

**Comment by skeyl** [comment]
I was on 1.x latest; updated to 1.2 beta and this bug is back on Linux.

**Comment by Costallat** [comment]
1.1 was okay, but 1.2 was like this
![snapshot1](https://cloud.githubusercontent.com/assets/1304176/11171543/eccc88c6-8bd9-11e5-86f5-0e9d0754aaca.png)

**Comment by benogle** [comment]
refs #9454

**Comment by ozra** [comment]
Ping. Revisits this. Trying out Atom again, and on Ubuntu 18.04 at least, fonts still look like mud. `-webkit-font-smoothing` still has no effect. Am i missing some over-ruling option or such? I _really_, _really_, would like to get rid of the anti-alias completely and entirely, like in all other apps!
