### ISSUE TITLE
Status bar requires two scrollbars -- introduced with 0.197

### ISSUE THREAD

**Issue by maletor** [atom/atom#6685]
![screenshot 2015-05-07 10 58 07](https://cloud.githubusercontent.com/assets/138785/7522136/14dbb3ce-f4a8-11e4-8749-1fd3fc3a39f0.png)

**Comment by izuzak** [comment]
@maletor Interesting, I'm not seeing that. Which OS are you on and which theme are you using? Do you see the same in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Thanks for the report

**Comment by izuzak** [comment]
Also /cc @simurai

**Comment by maletor** [comment]
No, it's not there in safe mode. I guess that means it's either linter or deprecation code? Would that be the only difference? 

OS X by the way.

**Comment by izuzak** [comment]
Thanks for checking. The difference would be that in safe mode Atom loads only with the packages included in Atom by default -- it doesn't load packages you installed in addition to that. So, one of the packages you've installed is triggering this behavior. You could try and figure out which one by disabling packages one-by-one (and reloading Atom between each change).

If you can reproduce the problem in safe mode -- please let us know.

**Comment by maletor** [comment]
Definitely looks like the "linter" package. I'll follow up over there.
