### ISSUE TITLE
Indent rendering - soft wrap

### ISSUE THREAD

**Issue by Mayccoll** [atom/atom#6689]
Atom 0.198.0
Linux mint 17.1

This is how looks like the same file in sublime and atom.
I open the file using ```atom .zshrc --save```

![fortat](https://cloud.githubusercontent.com/assets/2009698/7522728/aab775a4-f4bc-11e4-86ea-cb10a9a9f920.png)

**Comment by izuzak** [comment]
@Mayccoll Do you see the same behavior in Atom if you start it in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If so, can you share a link to the file in question? Also, what's that `--save` option about? Atom doesn't have such an option as far as I know. Was that supposed to be `--safe`?

**Comment by Mayccoll** [comment]
jejeje safe ... yea .. sorry i was hungry when i made the issue jejejeje.
same behavior

![at](https://cloud.githubusercontent.com/assets/2009698/7523636/7a75da88-f4c2-11e4-8ebc-61083dbe9067.png)

**Comment by izuzak** [comment]
@Mayccoll Thanks. Can you share a link to that file?

**Comment by Mayccoll** [comment]
sure
http://curl.io/get/8xghggvc/768fe113941feee449566e2c1aea7b82d233c54f

**Comment by Mayccoll** [comment]
No longer an issue
0.199.0 :ok_hand:
