### ISSUE TITLE
Auto indent not working for open curly brackets in next line

### ISSUE THREAD

**Issue by darkdragon-001** [atom/atom#6691]
already perfect result:

``` c++
if (true)
{
  foo();
  bar();
}
else
{
  foo();
  bar();
}
```

results in:

``` c++
if (true)
  {
    foo();
    bar();
  }
  else
    {
      foo();
      bar();
    }
```

**and**

``` c++
if (true)
  foo();
else
  bar();
```

results in:

``` c++
if (true)
  foo();
  else
    bar();
```

**Comment by muppetjones** [comment]
Continuation of an ongoing indentation problem: [here](https://github.com/atom/atom/issues/6655)

**Comment by JulianLeviston** [comment]
Ah I think this is an issue in clojure, too: https://github.com/atom/language-clojure/issues/23

That is, if a paren is open, enter should start indent at the end of the previous line, but it currently has a single-indent from the *beginning* of the last line.
