### ISSUE TITLE
The overlay decorator misplaced to be on the right bottom corner of the given range.

### ISSUE THREAD

**Issue by mostafaeweda** [atom/atom#6695]
![screenshot 2015-05-07 14 03 09](https://cloud.githubusercontent.com/assets/264320/7526663/879a5080-f4c8-11e4-9182-ca00587cd476.png)

Here is the code showing the highlight decorator correctly placed, but not overlay decorator placed:

``` js
var someDiv = document.createElement('div');
var range = new Range([1, 1], [1, 10]);
var marker = editor.markBufferRange(range);
someDiv.textContent = "IViewerContext";
editor.decorateMarker(marker, {type: 'overlay', position: 'head', item: someDiv});
editor.decorateMarker(marker, {type: 'highlight', class: 'linter-error'});
```

To position my hint above the text, I had to do:

```
var expressionLength = range.end.column - range.start.column;
someDiv.style.position = 'relative';
someDiv.style.left = - (expressionLength * editor.getDefaultCharWidth()) +  'px';
someDiv.style.top = - (2 * editor.getLineHeightInPixels()) + 'px';
```

Unexpectedly, setting `position: 'tail'` adjusts the start of the range!
Also, it still starts rendering from below the range's given row.

/cc @bolinfest @maxbrunsfeld @benogle

**Comment by banacorn** [comment]
+1

Also, [the document](https://atom.io/docs/api/v0.201.0/TextEditor#instance-decorateMarker) tells nothing about how to use the overlay decorator, e.g. the necessity of the `item` field.

**Comment by 38leinaD** [comment]
this is still happening in 1.17.2. any update?

**Comment by euvl** [comment]
Facing the same issue.

<img width="229" alt="screen shot 2017-08-11 at 11 56 40" src="https://user-images.githubusercontent.com/1577802/29210578-291d73a2-7e8c-11e7-8495-d1a392dd07a8.png">
