### ISSUE TITLE
Issue while opening atom.

### ISSUE THREAD

**Issue by errakeshpd** [atom/atom#6699]
![issue_atom](https://cloud.githubusercontent.com/assets/5379778/7532270/8aa39150-f582-11e4-9bd7-86d95554d0fc.png)
![atom_issue2](https://cloud.githubusercontent.com/assets/5379778/7532527/7b3b8936-f585-11e4-91b3-8ff6fb7f5fc5.png)

**Comment by thomasjo** [comment]
Looks like the [`terminal-status` package](https://github.com/guileen/terminal-status) might be having some issues. See if you can reproduce the problem in [safe mode](https://atom.io/docs/v0.198.0/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode).

**Comment by 50Wliu** [comment]
No response, closing until more information is provided.
