### ISSUE TITLE
stablize menu item order

### ISSUE THREAD

**Issue by terrywh** [atom/atom#6700]
as show below:
![1](https://cloud.githubusercontent.com/assets/968222/7532257/74a4a7c6-f597-11e4-9503-d75cb700590d.jpg)
![2](https://cloud.githubusercontent.com/assets/968222/7532262/7786552a-f597-11e4-918a-dc0fa24fac25.jpg)
can the context menu keep those items in the same order at both locations ?

**Comment by mnquintana** [comment]
Closing in favor of #6270 - please subscribe there for updates.
