### ISSUE TITLE
Uncaught JS-YAML: missed comma between flow collection entries at line 29, column 3:      "plugins": [      ^

### ISSUE THREAD

**Issue by Giaco9** [atom/atom#6708]
[Enter steps to reproduce below:]

1. open terminal on my project
2. type npm i --save-dev eslint
3. open my project in atom

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught JS-YAML: missed comma between flow collection entries at line 29, column 3:
      "plugins": [
      ^

```
At /Users/MY_FOLDER/babel/node_modules/eslint/lib/config.js:60

undefined
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontFamily": "Inconsolata",
    "fontSize": 14,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.1.0
linter, v0.12.1
linter-coffeelint, v0.2.3
linter-eslint, v0.5.3
linter-jshint, v0.1.2
linter-less, v0.4.0

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
I think this is the same issue as https://github.com/atom/atom/issues/6739 (a syntax error in your `.eslintrc` file that linter-eslint isn't catching) - please feel free to reopen if I'm not getting that right, and feel free to subscribe to https://github.com/AtomLinter/linter-eslint/issues/65 for updates.
