### ISSUE TITLE
PHP syntax highlighting breaks on the string `><?php`

### ISSUE THREAD

**Issue by AlexanderOMara** [atom/atom#6709]
I just updated to Atom version 0.198.0 and I've noticed an issue I didn't have yesterday.

The PHP syntax highlighting breaks on the following code:

```php
<?php
$highlighted = true;
?><p>test</p><?php
$highlighted = false;
```
![without space](https://i.imgur.com/hFs0mpi.png)

I've narrowed it down to this sequence of characters that is tripping it up.

    ><?php

Plus the short-hand variation.

    ><?

If I change the code to have a space in between it works.

```php
<?php
$highlighted = true;
?><p>test</p> <?php
$highlighted = false;
```

![with space](https://i.imgur.com/92QlATM.png)

I'm guessing this is related to the recent PHP-related changes listed in the change log.

**Comment by 50Wliu** [comment]
Could you please report this over to the [language-html](https://github.com/atom/language-html) repository?  Thanks.

**Comment by AlexanderOMara** [comment]
[Looks like someone else already did](https://github.com/atom/language-html/issues/60), but I've added my details there.
