### ISSUE TITLE
Failed to load the turbo-javascript package

### ISSUE THREAD

**Issue by vfxdomain** [atom/atom#6711]
[Enter steps to reproduce below:]

1. Install latest Atom from GitHub (1.0.198)
2. Start the program

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Failed to load the turbo-javascript package

```
At unexpected newline

[stdin]:2:16: error: unexpected newline
'context-menu':
               ^
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "solarized-dark-ui",
      "solarized-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [],
    "projectHome": "/Users/izaslavs/Projects/github"
  },
  "editor": {
    "fontSize": 14,
    "tabLength": 4
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.5.0
color-picker, v0.14.3
script, v2.3.1
solarized-dark-syntax, v0.14.0
solarized-dark-ui, v0.2.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@vfxdomain I can't seem to reproduce this -- are you able to reliably reproduce the problem? Did the problem go away after you restarted Atom perhaps? If not, are you able to reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by 50Wliu** [comment]
Looks like the `menu.cson` file was removed more than a year ago, so I'm going to assume that either @vfxdomain was on a really, really old version of `turbo-javascript`.
