### ISSUE TITLE
View > Increase Font Size doesn't show keybinding

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#6713]
![screenshot 2015-05-09 15 49 58](https://cloud.githubusercontent.com/assets/823545/7551762/239ec7fe-f663-11e4-8d6c-01703dd48090.png)

Atom 0.197.0-a79a8fa in safe mode, OS X 10.10.3

Can anyone on Linux or Windows confirm?

**Comment by 50Wliu** [comment]
Can confirm on Ubuntu 15.04, Atom 0.199.0-f1f8c3d

**Comment by jerone** [comment]
Confirm Windows 7 64-bits, Atom 0.196.0.
