### ISSUE TITLE
Document public properties in addition to methods

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#6714]
Currently, only public methods are documented in the API, but many classes (`Point`, for example) have de facto public properties as well (e.g. `row`, `column`). These public properties should be documented for public consumption.

/cc @atom/feedback

**Comment by lee-dohm** [comment]
:+1: I think this is a great idea.

**Comment by lee-dohm** [comment]
Looks like this was fixed in https://github.com/atom/text-buffer/pull/60 😀
