### ISSUE TITLE
Default key bindings interfere with special characters on non-standard keyboard layouts

### ISSUE THREAD

**Issue by tjanson** [atom/atom#6716]
I’m using the German ergonomic keyboard mapping [Neo](http://neo-layout.org/) and Mac OS.

By default, Atom has several key bindings of the form `Alt+X` (`X` being a letter). These correspond to special characters on my keyboard map, e.g., `Alt+F` (or, in Apple terms `Option F`) is `=`.

Expected behaviour:
* The symbol is inserted.

Actual behaviour:
* The key binding is triggered.

I suppose you could argue that this behaviour is not a bug; in this case I urge you to reconsider the default bindings, since the current default effectively blocks me (and other non-English keyboard users) from entering various special characters.

**Comment by lee-dohm** [comment]
You can disable any key binding in Atom by using the `keymap.cson` to map that key to `unset!`. For example, if I want to disable the <kbd>Alt+F</kbd> keybinding, I can:

1. Open the Settings View
1. Click the Keybindings tab
1. Search for <kbd>Alt+F</kbd> in the search box
1. Click the clipboard icon to the left of the keybinding to copy it to the clipboard
1. Select the "Atom > Open Your Keymap" menu item
1. Paste in the keybinding
1. Change the command from `editor:move-to-end-of-word` to `unset!`

Then your normal keyboard behavior should take precedence.

Let us know if you have any other questions!

**Comment by tjanson** [comment]
I understand that this can be changed, but I still consider it a bug that Atom ships with a config that breaks basic keyboard functionality for a significant number of users.

However, I now see that this is a direct duplicate of #4680 and more broadly of https://github.com/atom/atom-keymap/issues/37 and https://github.com/atom/atom-keymap/issues/35, sorry for that.

**Comment by tjanson** [comment]
Possible solution, for those affected: https://github.com/andischerer/atom-keyboard-localization

**Comment by Zireael07** [comment]
Thanks for the link - I'm on the PL_Programmer layout :)
