### ISSUE TITLE
Failed at the git-utils@3.0.0 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by tkorays** [atom/atom#6719]
Node: v0.10.26
npm: v2.5.1
Python: v2.7.9
Installing build modules...
Installing apm...
gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "node" "C:\\Users\\Administrator\\Desktop\\atom\\build\\node_modules\\npm\\bin\\npm-cl
C:\\Users\\Administrator\\Desktop\\atom\\build\\.npmrc" "--target=0.10.35" "install" "--loglevel" "e
npm ERR! node v0.10.26
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! git-utils@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the git-utils@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the git-utils package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls git-utils
npm ERR! There is likely additional logging output above.

**Comment by mnquintana** [comment]
Have you tried upgrading your system's version of node to 0.10.35?

**Comment by mark-hahn** [comment]
Git has to be able to run from a command line.  What happens when you type
`git  --version`?

**Comment by tkorays** [comment]
git version 1.8.4.msysgit.0

when I tried to install git-utils alone, it fails.
