### ISSUE TITLE
Atom not honoring Exclude VCS Ignored Paths

### ISSUE THREAD

**Issue by mcdonnelldean** [atom/atom#6720]
I've updated Atom recently and notice no matter what I set `Exclude VCS Ignored Paths` to I can never see my `/node_modules` folder, if it is in my git ignore.

__OS:__ OSX (yosemite)
__Atom Version:__ 0.198.0

**Comment by 50Wliu** [comment]
Please make sure Settings-->Packages-->Tree View-->`Hide VCS Ignored Files` is not checked.

**Comment by mcdonnelldean** [comment]
@50Wliu Awesome! That was it, I must have changed it when rooting around in the settings. I was full sure it was the `Exclude VCS Ignored Paths` that controlled this.

Thanks for the quick response :+1:
