### ISSUE TITLE
Handle Touch Events

### ISSUE THREAD

**Issue by russlescai** [atom/atom#6724]
I am looking to implement some basic touch events:
* down/up gesture scrolls
* pinch in/out zooms by modifying text size (if possible)

I have read about the basic touch events http://www.w3.org/TR/touch-events/ here.
Also, I can see in atom dev console, the touch breakpoints can be selected.

How would I add a handler to the active editor to listen for these events?

**Comment by mark-hahn** [comment]
Get the element ...

```editorEle = atom.views.getView atom.workspace.::getActiveTextEditor()```

and then add the listener ...

```editorEle.addEventListener 'touchsomething', (event) -> blah blah blah```

**Comment by russlescai** [comment]
awesome, thanks @mark-hahn , watch this space for a PR :)

**Comment by mark-hahn** [comment]
> watch this space for a PR :)

I definitely will.  I'm running with a touchscreen also, on a chromebook.
If you need any help let me know.

**Comment by russlescai** [comment]
I've got it basically working in my init.coffee. Using some arbitary range limits, but it essentially allows you to scroll up and down using touch events.

<pre>
atom.workspace.observeTextEditors (editor) ->
  view = atom.views.getView editor

  view.initialiseTouchPoints = (args) ->
      @startY = args.touches[0].screenY
      @startX = args.touches[0].screenX

  view.getTouchDelta = (args) ->
      deltaX = args.touches[0].screenY - @startY
      deltaY = args.touches[0].screenX - @startX

      @startY = args.touches[0].screenY
      @startX = args.touches[0].screenX

      {deltaX: deltaX, deltaY: deltaY}

  view.touchScroll = (args) ->
    {deltaX, deltaY} = @getTouchDelta args

    minRangeForScroll = 20

    isLeft = Math.abs(deltaX) < minRangeForScroll and deltaY < 0
    isRight = Math.abs(deltaX) < minRangeForScroll and deltaY > 0
    isUp = Math.abs(deltaY) < minRangeForScroll and deltaX < 0
    isDown = Math.abs(deltaY) < minRangeForScroll and deltaX > 0

    amount = Math.abs(deltaY) * 5

    editor = @getModel()

    if isDown
      editor.setScrollTop(editor.getScrollTop() - amount)
      args.preventDefault()
    else if isUp
      editor.setScrollTop(editor.getScrollTop() + amount)
      args.preventDefault()

  view.addEventListener 'touchstart', (args) =>
    view.initialiseTouchPoints args

  view.addEventListener 'touchmove', (args) =>
    view.touchScroll args
</pre>

**Comment by russlescai** [comment]
There is a lot to do with this,

**Comment by mark-hahn** [comment]
You should start a package for this, post the github address here, and we
can discuss it there.

**Comment by russlescai** [comment]
sounds good, will do.

**Comment by russlescai** [comment]
I've created a package: https://atom.io/packages/atom-touch-events.

It currently provides 4 swipe events, and allows text editors to scroll by swiping up and down.

**Comment by russlescai** [comment]
@mark-Hahn Let me know how you find the package and if it works ok for you too.

It's a start, but we have to start somewhere :)

**Comment by dovrosenberg** [comment]
Just wanted to let you know this is working great on a Suface Pro 3... seems like it should be part of the core.  Thanks @russlescai
