### ISSUE TITLE
Went to load a package while still testing it, atom broke

### ISSUE THREAD

**Issue by LTGLambChops** [atom/atom#6726]
I am writing some code for a compiler for java, so that my friend doesn't have to compile it using cmd/terminal; anyways, the compiler is written in java and I'm using javascript as a pathway to running the java method. I called the method as so: command.compile(atom.workspace.getActiveTextEditor()); I know that getActiveTextEditor() returns a string, so Java is waiting for String-based input. The class file is called command and the method name is compile, so those are also correct.

Side-note: I still have yet to actually rename anything to being java-compiler, but that's on my to do list prior to posting it to github.

Basically what'd happened was that I reloaded Atom and atom threw a stackTrace saying that the getActiveTextEditor() command was null and simply refused to launch the package.

**Atom Version**: 0.198.0
**System**: Microsoft Windows 8.1
**Thrown From**: Atom Core

### Stack Trace

Failed to load the my-package package

```
At Cannot read property 'getActiveTextEditor' of null

TypeError: Cannot read property 'getActiveTextEditor' of null
    at Compile (C:\Users\Austin\github\my-package\lib\javacompiler.js:16:19)
    at Object.<anonymous> (C:\Users\Austin\github\my-package\lib\javacompiler.js:30:30)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\Austin\AppData\Local\atom\app-0.198.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\Austin\AppData\Local\atom\app-0.198.0\resources\app.asar\src\package.js:711:34)
    at C:\Users\Austin\AppData\Local\atom\app-0.198.0\resources\app.asar\src\package.js:190:28
```

### Config

```json
{
  "core": {
    "audioBeep": false
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 90,
    "tabLength": 4,
    "softWrap": true,
    "softTabs": false
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.7.0
my-package, v1.0.0

**Comment by lee-dohm** [comment]
`atom.workspace.getActiveTextEditor()` doesn't return a String, it returns a `TextEditor`:

https://atom.io/docs/api/latest/Workspace#instance-getActiveTextEditor

Also, `getActiveTextEditor()` can return `undefined` if there isn't an active text editor.

**Comment by LTGLambChops** [comment]
Oh, well that would've been a bit more insight to have seen that it wasn't a String. Thanks for that! Might you happen to know how to get the location of the file then, if not at least to URI or URL form from the active window?

**Comment by mark-hahn** [comment]
https://atom.io/docs/api/v0.198.0/TextEditor#instance-getPath

You should spend some time browsing the api.  It will be worth it in the
long run.

**Comment by LTGLambChops** [comment]
I literally just found that, Thanks though! I mostly program in Java, so I'm surprised I didn't even think that there was an API until I got the link from lee-dohm.

**Comment by lee-dohm** [comment]
Thanks @mark-hahn, I probably should have been a little more helpful :grinning:
