### ISSUE TITLE
Crashed Atom by changing theme!

### ISSUE THREAD

**Issue by ShashankaNataraj** [atom/atom#6727]
I changed my theme to Monokai and then to solarized dark. This is what my screen looked like, please look at the status bar:

![status barbug](https://cloud.githubusercontent.com/assets/650317/7559212/a4fe801e-f7d0-11e4-8881-a5380357c27f.png)

5 seconds after this, I got the usual "Atom is not responding ___ " message, and I chose to kill it.

UPDATE 1: Restarted Atom, still no change. Changed theme to Atom Dark and restarted, UI is back to normal now.

**Comment by mark-hahn** [comment]
Is this repeatable?  Did you have any add-on packages enabled?

**Comment by ShashankaNataraj** [comment]
Hi, 

This is repeatable. I just changed back to solarized-dark and can see this issue again!

After this, I just disabled all my custom installed packages and restarted atom, I can still see this happening.

**Comment by thomasjo** [comment]
I'm unable to reproduce this. Can you please provide details such as Atom version, OS version, and the output of `apm list`?

In addition, check if you're able to reproduce the problem in [safe mode](https://atom.io/docs/v0.198.0/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode).

**Comment by ShashankaNataraj** [comment]
1. Im on atom v 0.198.0 .
2. This issue doesnt occur with atom --safe
3. APM List directory has the following content:

05/11/2015  02:59 PM               242 .apmrc
03/03/2015  11:16 AM    <DIR>          abbrev
03/03/2015  11:17 AM    <DIR>          agent-base
03/03/2015  11:17 AM    <DIR>          alter
03/03/2015  11:17 AM    <DIR>          amdefine
05/11/2015  11:22 AM    <DIR>          analytics-node
05/11/2015  11:22 AM    <DIR>          argparse
05/11/2015  11:11 AM    <DIR>          assertion-error
03/03/2015  11:17 AM    <DIR>          ast-traverse
05/11/2015  11:22 AM    <DIR>          ast-types
05/11/2015  11:12 AM    <DIR>          async
05/11/2015  11:22 AM    <DIR>          atom-beautify
05/11/2015  11:11 AM    <DIR>          atom-message-panel
05/11/2015  11:11 AM    <DIR>          atom-space-pen-views
05/11/2015  11:42 AM    <DIR>          atom-terminal
05/11/2015  11:11 AM    <DIR>          balanced-match
05/11/2015  11:22 AM    <DIR>          bluebird
05/11/2015  11:11 AM    <DIR>          brace-expansion
03/03/2015  11:17 AM    <DIR>          breakable
05/11/2015  11:11 AM    <DIR>          chai
05/11/2015  11:11 AM    <DIR>          cli
03/03/2015  11:16 AM    <DIR>          clone
03/03/2015  11:17 AM    <DIR>          co
05/11/2015  11:22 AM    <DIR>          coffee-fmt
05/11/2015  11:22 AM    <DIR>          coffee-formatter
05/11/2015  11:12 AM    <DIR>          coffee-script
05/11/2015  11:11 AM    <DIR>          coffeestack
05/11/2015  11:22 AM    <DIR>          colors
03/03/2015  11:17 AM    <DIR>          combined-stream
05/11/2015  11:22 AM    <DIR>          commander
03/03/2015  11:17 AM    <DIR>          commoner
03/03/2015  11:16 AM    <DIR>          component-emitter
03/03/2015  11:16 AM    <DIR>          component-type
05/11/2015  11:11 AM    <DIR>          concat-map
03/03/2015  11:16 AM    <DIR>          config-chain
05/11/2015  11:11 AM    <DIR>          console-browserify
03/03/2015  11:16 AM    <DIR>          cookiejar
03/03/2015  11:17 AM    <DIR>          core-util-is
05/11/2015  11:22 AM    <DIR>          csscomb
05/11/2015  11:22 AM    <DIR>          csscomb-core
05/11/2015  11:22 AM    <DIR>          cycle
03/03/2015  11:16 AM    <DIR>          d
03/03/2015  11:17 AM    <DIR>          data-uri-to-buffer
05/11/2015  11:11 AM    <DIR>          date-now
05/11/2015  11:12 AM    <DIR>          dateformat
05/11/2015  11:11 AM    <DIR>          debug
05/11/2015  11:11 AM    <DIR>          deep-eql
03/03/2015  11:17 AM    <DIR>          defs
05/11/2015  11:22 AM    <DIR>          degenerator
03/03/2015  11:17 AM    <DIR>          delayed-stream
05/11/2015  11:22 AM    <DIR>          diff
05/11/2015  11:12 AM    <DIR>          dom-serializer
05/11/2015  11:12 AM    <DIR>          domelementtype
05/11/2015  11:11 AM    <DIR>          domhandler
05/11/2015  11:11 AM    <DIR>          domutils
03/03/2015  11:16 AM    <DIR>          editorconfig
03/03/2015  11:16 AM    <DIR>          emissary
05/11/2015  11:12 AM    <DIR>          entities
05/11/2015  11:11 AM    <DIR>          es5-ext
03/03/2015  11:16 AM    <DIR>          es6-iterator
03/03/2015  11:16 AM    <DIR>          es6-symbol
05/11/2015  11:11 AM    <DIR>          es6-weak-map
03/03/2015  11:17 AM    <DIR>          escodegen
05/11/2015  11:11 AM    <DIR>          esformatter
05/11/2015  11:11 AM    <DIR>          esformatter-braces
05/11/2015  11:11 AM    <DIR>          esformatter-dot-notation
05/11/2015  11:11 AM    <DIR>          esformatter-literal-notation
05/11/2015  11:11 AM    <DIR>          esformatter-parseint
05/11/2015  11:11 AM    <DIR>          esformatter-quotes
05/11/2015  11:11 AM    <DIR>          esformatter-semicolons
05/11/2015  11:11 AM    <DIR>          esformatter-var-each
05/11/2015  11:11 AM    <DIR>          esprima
05/11/2015  11:22 AM    <DIR>          esprima-fb
03/03/2015  11:19 AM    <DIR>          estraverse
03/03/2015  11:19 AM    <DIR>          esutils
05/11/2015  11:22 AM    <DIR>          event-kit
05/11/2015  11:12 AM    <DIR>          eventemitter2
05/11/2015  11:11 AM    <DIR>          exit
05/11/2015  11:22 AM    <DIR>          expand-home-dir
03/03/2015  11:16 AM    <DIR>          extend
05/11/2015  11:22 AM    <DIR>          eyes
05/11/2015  11:22 AM    <DIR>          file-icons
03/03/2015  11:17 AM    <DIR>          file-uri-to-path
05/11/2015  11:12 AM    <DIR>          findup-sync
03/03/2015  11:16 AM    <DIR>          form-data
05/11/2015  11:11 AM    <DIR>          formatio
03/03/2015  11:16 AM    <DIR>          formidable
05/11/2015  11:22 AM    <DIR>          front-matter
05/11/2015  11:11 AM    <DIR>          fs-plus
05/11/2015  11:22 AM    <DIR>          ftp
05/11/2015  11:24 AM    <DIR>          fuzzaldrin
03/03/2015  11:17 AM    <DIR>          get-uri
05/11/2015  11:12 AM    <DIR>          getobject
05/11/2015  11:24 AM    <DIR>          git-plus
05/11/2015  11:22 AM    <DIR>          glob
05/11/2015  11:22 AM    <DIR>          gonzales-pe
05/11/2015  11:22 AM    <DIR>          graceful-fs
05/11/2015  11:11 AM    <DIR>          grim
05/11/2015  11:12 AM    <DIR>          grunt
05/11/2015  11:12 AM    <DIR>          grunt-legacy-log
05/11/2015  11:12 AM    <DIR>          grunt-legacy-util
05/11/2015  11:11 AM    <DIR>          grunt-runner
05/11/2015  11:12 AM    <DIR>          hooker
05/11/2015  11:22 AM    <DIR>          html-entities
05/11/2015  11:11 AM    <DIR>          htmlparser2
03/03/2015  11:16 AM    <DIR>          http-proxy-agent
03/03/2015  11:16 AM    <DIR>          https-proxy-agent
05/11/2015  11:22 AM    <DIR>          iconv-lite
05/11/2015  11:22 AM    <DIR>          indent
03/03/2015  11:17 AM    <DIR>          inflight
05/11/2015  11:12 AM    <DIR>          inherits
03/03/2015  11:16 AM    <DIR>          ini
03/03/2015  11:17 AM    <DIR>          install
05/11/2015  11:11 AM    <DIR>          is-absolute
03/03/2015  11:16 AM    <DIR>          is-browser
05/11/2015  11:11 AM    <DIR>          is-relative
03/03/2015  11:17 AM    <DIR>          isarray
05/11/2015  11:22 AM    <DIR>          isstream
03/03/2015  11:16 AM    <DIR>          join-component
05/11/2015  11:11 AM    <DIR>          jquery
05/11/2015  11:11 AM    <DIR>          js-beautify
05/11/2015  11:22 AM    <DIR>          js-yaml
05/11/2015  11:11 AM    <DIR>          jsformat
05/11/2015  11:11 AM    <DIR>          jshint
03/03/2015  11:16 AM    <DIR>          keypress
05/11/2015  11:11 AM    <DIR>          language-javascript-better
03/03/2015  11:16 AM    <DIR>          lazy
05/11/2015  11:11 AM    <DIR>          linter
05/11/2015  11:22 AM    <DIR>          lodash
05/11/2015  11:11 AM    <DIR>          lolex
03/03/2015  11:16 AM    <DIR>          loophole
05/11/2015  11:22 AM    <DIR>          lru-cache
05/11/2015  11:22 AM    <DIR>          marked
03/03/2015  11:16 AM    <DIR>          methods
03/03/2015  11:16 AM    <DIR>          mime
05/11/2015  11:22 AM    <DIR>          minimatch
05/11/2015  11:11 AM    <DIR>          minimist
03/03/2015  11:16 AM    <DIR>          mixto
03/03/2015  11:16 AM    <DIR>          mkdirp
05/11/2015  11:17 AM    <DIR>          monokai
05/11/2015  11:11 AM    <DIR>          mout
05/11/2015  11:11 AM    <DIR>          ms
03/03/2015  11:17 AM    <DIR>          netmask
05/11/2015  11:22 AM    <DIR>          node-dir
05/11/2015  11:22 AM    <DIR>          node-uuid
05/11/2015  11:12 AM    <DIR>          nopt
05/11/2015  11:11 AM    <DIR>          npm-path
05/11/2015  11:11 AM    <DIR>          npm-run
05/11/2015  11:11 AM    <DIR>          once
05/11/2015  11:11 AM    <DIR>          optimist
03/03/2015  11:16 AM    <DIR>          pac-proxy-agent
03/03/2015  11:17 AM    <DIR>          pac-resolver
05/11/2015  11:22 AM    <DIR>          pad
05/11/2015  11:22 AM    <DIR>          pkginfo
05/11/2015  11:22 AM    <DIR>          prettydiff
03/03/2015  11:17 AM    <DIR>          private
03/03/2015  11:16 AM    <DIR>          property-accessors
03/03/2015  11:16 AM    <DIR>          proto-list
05/11/2015  11:11 AM    <DIR>          protochain
03/03/2015  11:16 AM    <DIR>          proxy-agent
03/03/2015  11:17 AM    <DIR>          q
03/03/2015  11:16 AM    <DIR>          qs
03/03/2015  11:16 AM    <DIR>          rainbowsocks
03/03/2015  11:17 AM    <DIR>          readable-stream
05/11/2015  11:22 AM    <DIR>          recast
03/03/2015  11:16 AM    <DIR>          reduce-component
05/11/2015  11:22 AM    <DIR>          regenerator
05/11/2015  11:22 AM    <DIR>          registry.npmjs.org
05/11/2015  11:11 AM    <DIR>          repeat-string
05/11/2015  11:11 AM    <DIR>          resolve
05/11/2015  11:11 AM    <DIR>          rimraf
05/11/2015  11:11 AM    <DIR>          rocambole
05/11/2015  11:11 AM    <DIR>          rocambole-indent
05/11/2015  11:11 AM    <DIR>          rocambole-linebreak
05/11/2015  11:11 AM    <DIR>          rocambole-node
05/11/2015  11:11 AM    <DIR>          rocambole-token
05/11/2015  11:11 AM    <DIR>          rocambole-whitespace
05/11/2015  11:11 AM    <DIR>          samsam
05/11/2015  11:11 AM    <DIR>          semver
05/11/2015  11:11 AM    <DIR>          serializerr
05/11/2015  11:17 AM    <DIR>          seti-ui
05/11/2015  11:11 AM    <DIR>          shelljs
03/03/2015  11:16 AM    <DIR>          sigmund
03/03/2015  11:17 AM    <DIR>          simple-fmt
03/03/2015  11:17 AM    <DIR>          simple-is
05/11/2015  11:11 AM    <DIR>          sinon
03/03/2015  11:16 AM    <DIR>          socks-proxy-agent
03/03/2015  11:13 AM    <DIR>          solarized-dark-ui
05/11/2015  11:22 AM    <DIR>          source-map
03/03/2015  11:16 AM    <DIR>          space-pen
03/03/2015  11:16 AM    <DIR>          sprintf-js
03/03/2015  11:17 AM    <DIR>          stable
05/11/2015  11:22 AM    <DIR>          stack-trace
05/11/2015  11:11 AM    <DIR>          stdin
03/03/2015  11:17 AM    <DIR>          stream-to-array
03/03/2015  11:17 AM    <DIR>          stringmap
03/03/2015  11:17 AM    <DIR>          stringset
03/03/2015  11:17 AM    <DIR>          string_decoder
05/11/2015  11:11 AM    <DIR>          strip-json-comments
03/03/2015  11:16 AM    <DIR>          superagent
03/03/2015  11:16 AM    <DIR>          superagent-proxy
03/03/2015  11:16 AM    <DIR>          superagent-retry
05/11/2015  11:11 AM    <DIR>          sync-exec
03/03/2015  11:16 AM    <DIR>          temp
05/11/2015  11:22 AM    <DIR>          through
03/03/2015  11:17 AM    <DIR>          thunkify
05/11/2015  11:22 AM    <DIR>          tidy-markdown
03/03/2015  11:17 AM    <DIR>          tryor
05/11/2015  11:10 AM    <DIR>          turbo-javascript
05/11/2015  11:11 AM    <DIR>          type-detect
03/03/2015  11:16 AM    <DIR>          typescript-formatter
03/03/2015  11:16 AM    <DIR>          uid
05/11/2015  11:12 AM    <DIR>          underscore
03/03/2015  11:16 AM    <DIR>          underscore-plus
05/11/2015  11:12 AM    <DIR>          underscore.string
05/11/2015  11:11 AM    <DIR>          unquoted-property-validator
05/11/2015  11:11 AM    <DIR>          util
05/11/2015  11:22 AM    <DIR>          vow
05/11/2015  11:22 AM    <DIR>          vow-fs
05/11/2015  11:22 AM    <DIR>          vow-queue
05/11/2015  11:12 AM    <DIR>          which
05/11/2015  11:22 AM    <DIR>          winston
05/11/2015  11:11 AM    <DIR>          wordwrap
03/03/2015  11:17 AM    <DIR>          wrappy
03/03/2015  11:17 AM    <DIR>          xregexp
03/03/2015  11:16 AM    <DIR>          yaml-front-matter
05/11/2015  11:22 AM    <DIR>          yaml-js
03/03/2015  11:17 AM    <DIR>          yargs
05/11/2015  11:22 AM    <DIR>          _git-remotes
05/11/2015  11:42 AM    <DIR>          _locks

**Comment by thomasjo** [comment]
You need to execute the command `apm list`. It should produce output similar to [this](https://gist.github.com/thomasjo/9f2a0e2f93c61e75f275).

Since the problem does not occur in safe mode, the problem is (almost certainly) caused by one of your installed community packages. Hence the need for the package list to help narrow down the offending package.

**Comment by ShashankaNataraj** [comment]
Oops, sorry. Ran apm list and the output is as below, disabled all installed community packages and im still able to reproduce this issue. How come safe mode doesnt have an issue but disabling packages manually still reproduces this issue? Does safe mode do something extra?

Built-in Atom packages (85)
├── archive-view@0.56.0
├── atom-dark-syntax@0.26.0
├── atom-dark-ui@0.49.0
├── atom-light-syntax@0.26.0
├── atom-light-ui@0.41.0
├── autocomplete@0.46.0
├── autoflow@0.22.0
├── autosave@0.20.0
├── background-tips@0.24.0
├── base16-tomorrow-dark-theme@0.25.0
├── base16-tomorrow-light-theme@0.8.0
├── bookmarks@0.35.0
├── bracket-matcher@0.74.0
├── command-palette@0.35.0
├── deprecation-cop@0.43.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.20.0
├── exception-reporting@0.24.0
├── feedback@0.38.0
├── find-and-replace@0.161.0
├── fuzzy-finder@0.83.0
├── git-diff@0.55.0
├── go-to-line@0.30.0
├── grammar-selector@0.46.0
├── image-view@0.54.0
├── incompatible-packages@0.24.0
├── keybinding-resolver@0.32.0
├── language-c@0.44.0
├── language-clojure@0.14.0
├── language-coffee-script@0.40.0
├── language-csharp@0.5.0
├── language-css@0.29.0
├── language-gfm@0.71.0
├── language-git@0.10.0
├── language-go@0.25.0
├── language-html@0.37.0
├── language-hyperlink@0.13.0
├── language-java@0.15.0
├── language-javascript@0.77.0
├── language-json@0.14.0
├── language-less@0.27.0
├── language-make@0.14.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.23.0
├── language-php@0.22.0
├── language-property-list@0.8.0
├── language-python@0.34.0
├── language-ruby@0.52.0
├── language-ruby-on-rails@0.21.0
├── language-sass@0.37.0
├── language-shellscript@0.14.0
├── language-source@0.9.0
├── language-sql@0.15.0
├── language-text@0.6.0
├── language-todo@0.19.0
├── language-toml@0.15.0
├── language-xml@0.28.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.148.0
├── metrics@0.45.0
├── notifications@0.43.0
├── one-dark-syntax@0.4.0
├── one-dark-ui@0.8.1
├── one-light-syntax@0.5.0
├── one-light-ui@0.8.1
├── open-on-github@0.36.0
├── package-generator@0.38.0
├── release-notes@0.52.0
├── settings-view@0.197.0
├── snippets@0.89.0
├── solarized-dark-syntax@0.32.0
├── solarized-light-syntax@0.19.0
├── spell-check@0.56.0
├── status-bar@0.69.0
├── styleguide@0.44.0
├── symbols-view@0.96.0
├── tabs@0.68.0
├── timecop@0.31.0
├── tree-view@0.171.0
├── update-package-dependencies@0.9.0
├── welcome@0.27.0
├── whitespace@0.29.0
└── wrap-guide@0.32.0

C:\Users\shashann\.atom\packages (12)
├── atom-beautify@0.27.1
├── atom-terminal@0.7.0
├── file-icons@1.5.5
├── git-plus@4.5.0
├── grunt-runner@0.9.0
├── jsformat@0.8.0
├── language-javascript-better@1.5.0
├── linter@0.12.2
├── monokai@0.14.0
├── seti-ui@0.7.1
├── solarized-dark-ui@0.3.0
└── turbo-javascript@0.0.8

**Comment by lee-dohm** [comment]
Well, one thing that Safe Mode does is it forces you to restart the application in a new session. Some packages don't completely remove themselves when disabled, so if you really want to simulate Safe Mode without actually doing it you have to:

1. Disable all third-party packages
1. Set your themes to default-installed themes
1. Completely exit Atom
1. Start Atom again

**Comment by 50Wliu** [comment]
Looks like this was solved.
