### ISSUE TITLE
No respond for Ctrl-l

### ISSUE THREAD

**Issue by w5s5j** [atom/atom#6729]
Hi,

I am using Mac OSX 10.10.3 with version 0.198.0 of Atom. I try to map Ctrl-l into core:move-right, but I find it doesn't work. Then I look into the key binding resolver, when I press Ctrl-l, there is only a Ctrl instead of a Ctrl-l. I try to map other keys start with Ctrl into core:move-right and all of them work as expected. So I suspect there might be some problems for handling Ctrl-l. 

Thank you all in advanced. I am happy to provide other information if it helps.

**Comment by izuzak** [comment]
Hi, @w5s5j :wave: 

Mapping `Ctrl-l` to `core:move-right` works just fine for me on OSX 10.10.3. Here's a screenshot of the keybinding resolver:

![screen shot 2015-05-11 at 11 14 26](https://cloud.githubusercontent.com/assets/38924/7561788/21631144-f7cf-11e4-98c4-c1e09f29d703.png)

Can you share the contents of your keymap.cson file where the keybinding is defined? Also, do you perhaps have this keybinding mapped to some other command in other programs you use or at the OSX level? And which keyboard layout are you using?

**Comment by w5s5j** [comment]
I am sorry about it. I just figure out that I have mapped this keybinding in other programs at system level. So I am close it. Thanks again for your help!
