### ISSUE TITLE
Tab Bar: Tabs are hidden if too many tabs opened.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#6730]
atom 198 behanvior make tabs more readable but when too many tabs are opened , new ones are hidden. Previously atleast an icon width is still shown.

I propose a solution to add a Next/Back icon at the side of tab strip if too many tabs are opened like in firefox , with additional tablist button.

![](https://support.cdn.mozilla.net/media/uploads/images/2012-12-11-13-13-16-cf2909.png)

If i am good with coffeescript i can help.

**Comment by izuzak** [comment]
This issue was moved to atom/tabs#136
