### ISSUE TITLE
Invalid characters are shown as correct

### ISSUE THREAD

**Issue by TheLastProject** [atom/atom#6731]
EDIT: This happened on Linux (Trisquel 7) in case that's relevant.

Today, I copied some text out of a .docx document, which seemingly contained a few malformed characters.

Atom displays it as if it's correct:
![atom](https://cloud.githubusercontent.com/assets/1885159/7560943/39272b14-f7c8-11e4-9b74-1f8295d78e33.png)

Vim, however, does show there is something wrong:
![vim](https://cloud.githubusercontent.com/assets/1885159/7560951/4d0a9b02-f7c8-11e4-8217-74d51abfe34b.png)

Firefox shows issues too on the raw gist:
![firefox_gist_raw](https://cloud.githubusercontent.com/assets/1885159/7561032/11231352-f7c9-11e4-9b67-8071684413f4.png)

Atom's behaviour, in this case, is problematic, as this XML document will have issues validating to the schema with very weird errors, but looking at it in Atom shows no hint, whatsoever, as to why.

The XML file in question: https://gist.github.com/TheLastProject/20600c9c4071fc8d8a2b

**Comment by izuzak** [comment]
@TheLastProject Strange. I just tried downloading that file in the gist and opening it with vim, and I see the same thing as in Atom:

![screen shot 2015-05-11 at 10 35 36](https://cloud.githubusercontent.com/assets/38924/7561091/9a60ef04-f7c9-11e4-84a0-7a7ea4d88ee8.png)

Do you see the same if you download the raw gist and then open in vim?

**Comment by TheLastProject** [comment]
The raw gists opens broken in vim too, showing exactly the same for me. The way it is displayed seems to depend on the system in question then, interesting.

To show that there are indeed broken characters, when combined with the following XSD: https://gist.github.com/TheLastProject/3ec9ed15294bcad0c312, it should fail to validate on http://www.utilities-online.info/xsdvalidation/.

The fixed XML version, with correct characters, should validate to the XSD: https://gist.github.com/TheLastProject/1cf7a9d2447f176a52a6.

**Comment by izuzak** [comment]
@TheLastProject And when you open the raw gist file in Chrome and Firefox, what do you see there? (the one with "incorrect" characters)?

Also, if you tell Atom to auto-detect the encoding of the file (use the option in the bottom right corner) -- what happens then?

**Comment by TheLastProject** [comment]
As I added to the original post, it shows in Firefox broken too for me:
![firefox_raw_gist](https://cloud.githubusercontent.com/assets/1885159/7561730/a0bd9960-f7ce-11e4-9d52-490f30135745.png)

When I choose Auto Detect, it switches back to the current encoding. If I was using UTF-8, Auto Detect simply immediately goes back to UTF-8.

However, when I choose Windows 1252 (in which case Auto Detect switches back to Windows 1252), I start seeing the same as in Firefox:
![windows_1252](https://cloud.githubusercontent.com/assets/1885159/7561789/217fae1c-f7cf-11e4-907e-748910ed7fe9.png)

**Comment by izuzak** [comment]
> As I added to the original post, it shows in Firefox broken too for me:

What does Chrome show?

> However, when I choose Windows 1252 (in which case Auto Detect switches back to Windows 1252), I start seeing the same as in Firefox:

I see the same behavior as well. However, when I tell Atom to auto-detect the encoding -- it switches to Windows 1252 automatically (not to utf-8). Also, when I open the file in Vim, SublimeText and TextMate -- I see the same behavior as in Atom. Only if I change the encoding manually do I see the "broken" characters. I'm on OSX.

**Comment by TheLastProject** [comment]
Chromium (latest build, who knows how buggy it may be) refuses to render:
![chromium](https://cloud.githubusercontent.com/assets/1885159/7562179/a89d7520-f7d2-11e4-91ea-b82546d1869e.png)

But displays it correct in view-source:
![chromium_source](https://cloud.githubusercontent.com/assets/1885159/7562184/b91bd6b2-f7d2-11e4-84fb-91e1a2678f17.png)

**Comment by thomasjo** [comment]
I fail to understand why this is an Atom issue; the file in question violates the XML specification because the encoding declaration [violates the spec](http://www.w3.org/TR/REC-xml/#NT-EncodingDecl). The problem character is **not** a hyphen (I haven't checked the exact char, but most likely an *en-dash*). The file does not contain a BOM indicating it's UTF-8, so the default in (almost every) browser is to assume default encoding is ASCII/Windows-1252, whereas Atom by default assumes (the more sensible) UTF-8.

Again, I fail to see how this is a problem with Atom. Maybe someone can explain?

**Comment by mnquintana** [comment]
I agree with @thomasjo here - this is not an Atom issue, because the characters *are* valid in UTF-8, which is what Atom assumes by default. If you want to simulate the "broken" characters, just manually change the encoding to Windows 1252.

**Comment by izuzak** [comment]
@thomasjo @mnquintana Thanks for jumping in, I do agree with you. :bow: Still, I also found the difference in how the "Auto Detect" encoding feature worked interesting (it always selects Windows-1252 for me on OSX, which is not the behavior @TheLastProject observed on Linux). Also, the fact that Atom auto-detected a different encoding than the default one might have been useful information to the user in this case. I guess I was just exploring the problem to see if there's anything to improve here (regardless of the initial report).

**Comment by TheLastProject** [comment]
Fair point. I initially assumed the character was invalid, due to how vim and Firefox showed it. I apologize for the incorrect report, and thank you for the prompt replies. At least I learned some valuable things about encoding and now know how to properly deal with these issues on my end :)

On 11 May 2015 12:48:45 CEST, "Machisté N. Quintana" <notifications@github.com> wrote:
>I agree with @thomasjo here - this is not an Atom issue, because the
>characters *are* valid in UTF-8, which is what Atom assumes by default.
>If you want to simulate the "broken" characters, just manually change
>the encoding to Windows 1252.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/atom/atom/issues/6731#issuecomment-100867018

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
