### ISSUE TITLE
git repository packfiles kept open

### ISSUE THREAD

**Issue by linquize** [atom/atom#6736]
Atom uses libgit2 to read git repository.
However, if the repository has packfiles, the packfiles are kept open.
This makes `git gc` fail to delete the packfiles.

```
$ git gc
Counting objects: 53635, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (8149/8149), done.
Writing objects: 100% (53635/53635), done.
Total 53635 (delta 30114), reused 53218 (delta 29697)
Unlink of file '.git/objects/pack/pack-0edf695bcfc5349ac8940012a80521b3cba76437.pack' failed. Should I try again? (y/n)
```

**Comment by linquize** [comment]
To reproduce, 
On Win 7,
Drag a directory with .git folder into Atom
Then run `git gc`

If you look at Process Explorer, one of the atom.exe is opening files that are git packfiles of that repository.

**Comment by halfdan** [comment]
Not only that - it also slows down console interaction with the git repository to the point where I have to close atom, run git gc, reopen it to continue working.

**Comment by sirlancelot** [comment]
On Atom 1.3.2 and this is still happening. Same reproduce steps as @linquize.

1. Be on Windows 7
2. Open a folder containing a Git repository in Atom.
3. In a separate terminal window, run `git gc`.
4. During the cleanup process, I get "Unlink of file '.git/objects/pack/pack-abcdef' failed."
5. Click yes to try again, it fails with the same popup.
6. Close Atom, then click Yes. It completes successfully.

![screenshot 2015-12-17 11 12 27](https://cloud.githubusercontent.com/assets/71916/11879273/375308dc-a4af-11e5-93a4-4770d3e17682.png)

**Comment by damieng** [comment]
It looks like libgit2 intentionally keeps many packfiles open at once presumably for performance. More investigation is needed.
