### ISSUE TITLE
Uncaught JS-YAML: end of the stream or a document separator is expected at line 1, column 26:    "parser" : "babel-eslint",                             ^

### ISSUE THREAD

**Issue by bucaran** [atom/atom#6739]
[Enter steps to reproduce below:]

1. Be naive.
2. Open atom full of expectation and anticipation

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught JS-YAML: end of the stream or a document separator is expected at line 1, column 26:
    "parser" : "babel-eslint",
                             ^

```
At /Users/b/.d/den/node_modules/<PROJECT_NAME>/node_modules/parsec/node_modules/eslint/lib/config.js:76

undefined
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".CFUserTextEncoding",
      ".Trash",
      "Movies",
      "Music",
      "Pictures",
      "Public",
      "Documents",
      "Downloads",
      "Dropbox",
      "Desktop"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "emmet"
    ],
    "themes": [
      "one-dark-ui",
      "seti-monokai"
    ]
  },
  "editor": {
    "invisibles": {},
    "showInvisibles": true,
    "showIndentGuide": true,
    "fontFamily": "Anonymous Pro for Powerline",
    "fontSize": 21,
    "scrollPastEnd": true
  }
}
```

### Installed Packages

```coffee
# User
language-apache, v1.3.0
language-docker, v1.1.3
language-ejs, v0.1.0
language-fish-shell, v1.0.2
language-viml, v0.2.0
linter, v0.12.1
linter-eslint, v0.5.3
linter-jsxhint, v0.1.1
minimap, v4.8.0
minimap-git-diff, v4.1.2
react, v0.11.8
seti-monokai, v0.3.1

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
Are you working on a project with a `.eslintrc` file in it?

**Comment by bucaran** [comment]
Yes.

**Comment by mnquintana** [comment]
I think this is a syntax error in your `.eslintrc` file, which linter-eslint isn't catching correctly. Do you get this error consistently when you open a JS file in the project?

**Comment by bucaran** [comment]
Yup.

```
"parser" : "babel-eslint",
  "env" : {
    "node" : true,
    "es6" : true
  },
  "rules" : {
    "semi" : false,
    "no-use-before-define" : false,
    "strict" : false ,
    "no-var" : 2,
    "no-unused-expressions" : false,
    "no-shadow" : false
  }
}
```

**Comment by mnquintana** [comment]
Can you try disabling linter-eslint and see if you can reproduce this?

**Comment by bucaran** [comment]
Of course, that's how I am currently working on this project, but I _wanted_ to use ESLint.

**Comment by mnquintana** [comment]
If that's the full contents of your `.eslintrc`, then it is indeed a syntax error - you're missing the opening curly brace:

```json
{
  "parser" : "babel-eslint",
  "env" : {
    "node" : true,
    "es6" : true
  },
  "rules" : {
    "semi" : false,
    "no-use-before-define" : false,
    "strict" : false ,
    "no-var" : 2,
    "no-unused-expressions" : false,
    "no-shadow" : false
  }
}
```

**Comment by bucaran** [comment]
Good call! Thanks.

**Comment by mnquintana** [comment]
The error eslint via linter-eslint is throwing is valid, but linter-eslint isn't catching it properly - you can subscribe to https://github.com/AtomLinter/linter-eslint/issues/65 for updates on that. Thanks for the updates on this!
