### ISSUE TITLE
bracket-matcher:close-tag problems with TH tag

### ISSUE THREAD

**Issue by Instagit** [atom/atom#6740]
Atom Version: 0.196

Keybinding:
````
'.platform-linux atom-text-editor':
  'alt-.': 'bracket-matcher:close-tag'
````

Closing this ````<th>```` tag doesn't work:

````
<table>
  <thead>
    <tr>
      <th>
    </tr>
  </thead>
</table>
````

It works with ````<td>````, if you omit only the closing ````</thead>```` or if you remove the ````<thead>```` tags completely.

According to the HTML5 specification it doesn't need to be closed, but the behaviour is inconsistent.

**Comment by mnquintana** [comment]
This issue was moved to atom/bracket-matcher#133
