### ISSUE TITLE
Very slow and frequent project indexing

### ISSUE THREAD

**Issue by captainbrosset** [atom/atom#6748]
OS: MacOS Yosemite.
Atom version: 0.198.0

I work on a large codebase (mozilla project) and so my preferred way of navigating the code is by using the cmd-P shortcut.
I'm originally a ST2 user and just love this quick-jump to file/line way to navigate files.

Using Atom, I find this to be really slow.
Several things here:

* The first time I open the project and press cmd-P, it says "indexing project ...", which I can understand. It takes some time, but I'm prepared to wait if I know that it's only going to do that the first time.
* When it's done and I use the auto-complete to find files, the experience is really janky (but that's probably another bug).
* It seems to want to re-index every now and then when I later use cmd-P again, even though nothing has changed in the project. It shows a "re-indexing" message, but that doesn't prevent me from using the auto-complete, so it's kind of ok, but weird that it does it anyway.
* If I close and then re-open Atom and press cmd-P again, it says "indexing project ..." again, and I can't use the auto-complete to find files for a while again.

Also, probably related to this, I can hear my laptop fan spin pretty much all the time when using Atom.
As a comparison, I never experience these slow-downs, high CPU usage and frequent re-indexing with ST2.

![atom-indexing](https://cloud.githubusercontent.com/assets/1152698/7583767/baf7cf10-f898-11e4-9b79-b8064af8d424.gif)

For info, the mozilla project codebase is probably more than 500.000 files.

**Comment by izuzak** [comment]
@captainbrosset Thanks for the detailed feedback. Can you re-open this on fuzzy-finder's issue triacker please? https://github.com/atom/fuzzy-finder 

Also, can you check some of the existing issues over there and see if something matches the problem you're seeing? If so, please leave a comment there with the details you listed here (+ bonus points for exact steps to reproduce which include a link to a git repository you can reliably reproduce this with, whether you can reproduce in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) and stuff like that).

**Comment by qcq** [comment]
I also find this problem, When I re-open the same project, Atom will indexing the project, which not happened to sublime. Please fix this, it is really weried. Thanks for your hard work.

**Comment by sreevisakh** [comment]
+1

**Comment by nialbima** [comment]
+1

**Comment by Creativelair** [comment]
+1

**Comment by Monsieur-Burns** [comment]
+1

**Comment by rx2130** [comment]
+1

**Comment by ruler88** [comment]
+1

**Comment by tomsihap** [comment]
+1
I don't know if it is any related but I think it did it for me since I was trying to open an odd big .js.map file located into my project folder. Since then, it frequently stuck on indexing.

**Comment by jshrt** [comment]
+1

**Comment by desmond1303** [comment]
+1

**Comment by gmassman** [comment]
+1

**Comment by nsnsoft** [comment]
:+1:

**Comment by vnhnhm** [comment]
+1

**Comment by rahulsukla** [comment]
+1

**Comment by phthhieu** [comment]
+1

**Comment by nekromant** [comment]
+1

**Comment by jonodonovan** [comment]
+1

**Comment by 50Wliu** [comment]
The +1 comments are doing nothing as this issue is on the wrong repository.  As such, I am locking this issue.  Please feel free to open an issue on [atom/fuzzy-finder](https://github.com/atom/fuzzy-finder) if you're experiencing a similar issue.
