### ISSUE TITLE
Editor not responding when adding quote mark

### ISSUE THREAD

**Issue by loboolsson** [atom/atom#6751]
![atom](https://cloud.githubusercontent.com/assets/1582795/7587184/c66b9bc6-f8b4-11e4-9873-f1a1c53e9d92.png)

When adding a quote mark as seen in the attached file the entire GUI freezes and I'm forced to kill the process. I've replicated this multiple times in 2 different projects. It only occurs in .js files or files that have explicitly been defined as JavaScript grammar. I can replicate the problem with just the one row of code where the quote is added

Expected behavior: Add single-quote
Experienced behavior: Added single quote. Application hangs
Replication steps: 
1. Create a new file and define it as JavaScript or edit a .js file
2. Enter        ` template:'<img ng-class="{{ng-class}}"`
3. Put a single quote before the ng-class `template:'<img 'ng-class="{{ng-class}}"`

Experienced in Atom 0.198.0 Running on Windows 8.1

**Comment by izuzak** [comment]
I can't reproduce this. Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode), @loboolsson?

**Comment by loboolsson** [comment]
This seems to have been some kind of fluke. I have not been able to reproduce it myself now despite being able to reproduce it consistently when i reported the issue.

**Comment by izuzak** [comment]
@loboolsson Interesting indeed. I'll close this for now, and please feel free to reopen if you can reproduce this safe mode. :bow:
