### ISSUE TITLE
Support for liquid markup

### ISSUE THREAD

**Issue by namrodbui** [atom/atom#6752]
Would be cool to have a template for liquid.

**Comment by mnquintana** [comment]
@namrodbui What do you mean by a template? Do you mean snippets?

**Comment by namrodbui** [comment]
Oh. That was fast!

More of a color scheme for the global variables in liquid.

There are a couple out there for sublime text.

https://github.com/siteleaf/liquid-syntax-mode

I really like atom.io a lot. Faster and crisper than Sublime. My buddy just
started at github last week, and he was telling me about atom.io. I've got
my whole team trying it out this week. Very impressed.

Kind Regards,

Brian Nam Bui
Look-Listen

678.386.8011 Mobile
+1 770 818 5654 Fax
nam@look-listen.com

**Comment by mnquintana** [comment]
It doesn't ship with Atom, but you can check out https://atom.io/packages/language-liquid - you can install it by opening Preferences / Settings in Atom, going to the Install section, and searching for `language-liquid`. That'll enable syntax highlighting and snippets for Liquid. Hope that helps!

**Comment by namrodbui** [comment]
Oh you already have it. Nice.
