### ISSUE TITLE
Atom freezes after copy paste and language selection

### ISSUE THREAD

**Issue by binaryanomaly** [atom/atom#6756]
Hello

I notice atom freezing for seconds on linux and osx when I do the following:
1. Copy about 190'000 chars javascript code into new tab in atom (still ok)
2. Select javascript language
--> Atom freezes for ~20secs and causes high cpu load, it seems to recover afterwards

**Comment by Zireael07** [comment]
You mean it freezes while doing the highlighting for the language?
In my case, sometimes in longer files it doesn't finish highlighting everything and the last part (25% or so) of the file stays grey until I scroll to it/edit it. (btw my files are lua, so it's not language-related)

**Comment by binaryanomaly** [comment]
Yep, it does finish though.

**Comment by 50Wliu** [comment]
There have been some improvements to file tokenization performance lately.  Closing.
