### ISSUE TITLE
Snippet dotfile request.

### ISSUE THREAD

**Issue by toddmbloom** [atom/atom#6768]
I was just thinking that it would be nice for Atom to support a folder level snippet file, which would be used to extend the snippets.cson file in the Atom configuration directory. 

A use case I could think of is if you have a team of people working on the same project and, instead of having to send around a snippets.cson, every time it's modified, you could just simply check it into version control and Atom could read it in cascading order:

| <uses ~/.atom/snippets.cson
|-- 
|---- <.snippets(?) file found, import>

I'm not sure if this makes sense but it was just something I was kicking around today.

**Comment by lee-dohm** [comment]
This issue was moved to atom/snippets#136
