### ISSUE TITLE
Snippet.cson request

### ISSUE THREAD

**Issue by toddmbloom** [atom/atom#6769]
Currently snippets are defined as such:

```
'.source.<extension>':
  '<description>':
    'prefix': '<prefix>'
    'body': '<body>'
```

Which is good, but leaves a lot to be desired when it comes to reusability. What if the following format was used instead?

```
'<description>':
  'prefix': '<prefix>'
  'body': '<body>'
  'sources': ['css','html','js']
```

**Comment by lee-dohm** [comment]
This issue was moved to atom/snippets#137
