### ISSUE TITLE
Canceling "unsaved changes" warning closes window anyway

### ISSUE THREAD

**Issue by devios1337** [atom/atom#6770]
I've encountered a very severe bug (Atom 0.198.0) where if you attempt to close a window with tabs with unsaved changes, and you hit cancel in the warning dialog that appears, it closes the window anyway (presumably *without* saving).

**Comment by mnquintana** [comment]
Thanks for the report! What OS are you running? Can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) (`atom --safe`)?

**Comment by 50Wliu** [comment]
This is a duplicate of #4092, please subscribe there for updates (and also comment there with your OS and `atom --safe` results).
