### ISSUE TITLE
Atom should specify which incompatible native module caused `require` to fail

### ISSUE THREAD

**Issue by thedaniel** [atom/atom#6771]
It would be nice in a package with many native modules, if the logged message in the console was not:

> Failed to require the main module of 'git' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.

but was instead:

> Failed to require the main module of 'git' because it requires 'module-name', an incompatible native module.
Run `apm rebuild` in the package directory to resolve.

**Comment by audrummer15** [comment]
+1

**Comment by antono** [comment]
:+1:

**Comment by brunetton** [comment]
While we are in the subject : 
It should be :

> Failed to require the main module of 'git' because it requires 'module-name', an incompatible native module.
> Run apm rebuild in the package directory, **and restart Atom** to resolve.

**Comment by Glavin001** [comment]
+1 absolutely agree.

For those interested in making a Pull Request, this looks like the applicable section of code: https://github.com/atom/atom/blob/f48069c5f848b5ae624b110a1df7800e919eb142/src/package.coffee#L425-L431

**Comment by Glavin001** [comment]
I submitted a quick Pull Request to get things rolling: https://github.com/atom/atom/pull/12086
