### ISSUE TITLE
Overflow CSS property in `.status-bar-right` causes unnecessary scroll bars

### ISSUE THREAD

**Issue by tylerFowler** [atom/atom#6772]
Since about a version or two ago (that I noticed anyway, I'm on 0.198.0) I noticed that the bottom right section of the status bar has been adding unnecessary scroll bars. And ironically ends up hiding some of the data since the scroll bars take up space.

Setting the `overflow` CSS property of the class `status-bar .status-bar-right` from `auto` to `hidden` fixes the issue, but I'm not sure if this rule serves some other purpose. The theme I'm using is the One Light UI but it might carry over to others as well.

**Comment by 50Wliu** [comment]
This will be fixed by 0.199.0 which should be out this week.

**Comment by simurai** [comment]
I can reproduce it by changing "Show scrollbars" to "Always" in the OS X settings. And I think they are shown on Windows by default.

I'll reopen this and try to fix it till next release.
