### ISSUE TITLE
Can't build atom on 32-bit Ubuntu 15.04

### ISSUE THREAD

**Issue by fusion809** [atom/atom#6774]
I've been following the instructions on my linux.md file; there were no problems mentioned in after running these pieces of code therein (numbered to make them easier to refer to, if need be)
1. `sudo apt-get install build-essential git libgnome-keyring-dev fakeroot`
2. `node`
3. `which node`
(gave the output `/usr/sbin/node`)
4. `sudo update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10`
5. `git clone https://github.com/atom/atom cd atom`
6. `git fetch -p`
7. `git checkout $(git describe --tags `git rev-list --tags --max-count=1`)`
8. `script/build`
9. `sudo script/grunt install`
10. `sh script/grunt mkdeb`

(10) was meant to create a debian file as I understand it, in my `/tmp/atom-build` directory but this directory didn't even exist after I had finished running these commands. As I understand it the `atom.sh` file in my `~/atom` directory should be an executable shell file, executable from terminal via running `./atom.sh` so I ran it from the terminal, to receive the error:
`nohup: failed to run command ‘/tmp/atom-build/Atom/atom’: No such file or directory`

**Comment by paulcbetts** [comment]
You left out `script/bootstrap`

**Comment by fusion809** [comment]
Ah, I suggest those responsible for maintaining the markdown docs keeps this in mind before the next release as it wasn't in my md file. Where does this line go in my numbering scheme?

**Comment by paulcbetts** [comment]
At the moment, it should be #7.5 (i.e. after checkout before build)

**Comment by paulcbetts** [comment]
-cc #6775

**Comment by fusion809** [comment]
Ah I'm afraid still no deb file in sight and still receiving the same error after running `./atom.sh`

**Comment by thomasjo** [comment]
> You left out script/bootstrap, should be right before script/build

Just updating this thread to let folks know that manually invoking `script/bootstrap` is not necessary since `script/build` invokes it for you.

@fusion809 You mentioned no problems/errors. What gets printed to your console (last few lines) when you run `script/build`?

**Comment by fusion809** [comment]
@thomasjo Nothing, absolutely nothing. It just goes to the next input line.

**Comment by paulcbetts** [comment]
You've got something weird going on in your environment, there should be lots of stuff printed. Is it possible that you're trying to build Atom in a mountpoint that has noexec turned on or something?

**Comment by 50Wliu** [comment]
Hey @fusion809, since your other issue has been closed, is this one resolved as well?
