### ISSUE TITLE
Uploading using Remote Desktop Protocol (RDP)?

### ISSUE THREAD

**Issue by kupoback** [atom/atom#6784]
Is there a way, or does anyone know of an extension beyond SFTP/FTP that will allow me to upload a file to an RDP? I cannot connect to our virtual machine via ftp to upload files, so I have to resort to manually dragging and dropping. This is due to us using bitbucket.

**Comment by batjko** [comment]
If I remember correctly, RDP is not meant as a standalone file transfer protocol. It's for streaming desktops. Although a mapping to the remote machine's file system does get created during those sessions, I haven't heard of anyone using that feature by itself programmatically.

**Comment by damieng** [comment]
Believe there is no solution to this - certainly nothing Atom specific.
