### ISSUE TITLE
Atom crashes listing the contents of a directory with a large number of files

### ISSUE THREAD

**Issue by benbalter** [atom/atom#6786]
I'm not sure if it's possible to add in some sort of guard or max-file listing, but clicking expand on a folder with a large number of files and subfolders in it (1000s), renders Atom unresponsive. 

The unresponsiveness persists through a restart, as Atom tries to resume the previous state on load (thus expanding the folder again). I resolved the issue by deleting my `~/.atom/storage` folder, restarting, and resisting the urge to click the folder again.

### Steps to reproduce 

I don't know the exact number of files necessary, but here's an example of how to reproduce it:

1. Run [this script](https://github.com/benbalter/gman/blob/master/script/vendor-nl), which will wget a large website, creating a bunch of subdirectories
2. Open the parent folder in Atom
3. After a few moments (you don't need to wait for the script to stop)
4. Click the folder to expand it

## Expected

The folder would load displaying the sub tree, or at least part of it

## Actual

Editor has become unresponsive error

**Comment by 50Wliu** [comment]
This issue was moved to atom/tree-view#449
