### ISSUE TITLE
Alt codes are difficult with multiple files open

### ISSUE THREAD

**Issue by ArtskydJ** [atom/atom#6788]
Pressing <kbd>alt</kbd>+<kbd>1</kbd> through <kbd>alt</kbd>+<kbd>9</kbd> will attempt to switch tabs. [See code here](https://github.com/atom/atom/blob/44db3e7d2b56cc4ca32b24d47d3964e60ff761ab/keymaps/win32.cson#L80-L88)

When entering an alt code, the tabs switch. It's hard to enter alt codes.

**Workaround:** Open a file in a separate pane, and enter alt codes there.

**Comment by 50Wliu** [comment]
For those who might not know what "alt codes" are: on Windows, holding Alt while pressing a three-number combination on the keypad will produce a symbol (see http://www.alt-codes.net/).

**Comment by ArtskydJ** [comment]
As another workaround, you can add this to your keymap.cson:

```cson

'body':
	'alt-1': null
	'alt-2': null
	'alt-3': null
	'alt-4': null
	'alt-5': null
	'alt-6': null
	'alt-7': null
	'alt-8': null
	'alt-9': null
```

**Comment by mattecapu** [comment]
This doesn't work. Neither mapping to `''`.
Any other suggestion?

**Comment by lee-dohm** [comment]
When needing to unset a keybinding, you should use the `unset!` directive as described here:

https://atom.io/docs/latest/behind-atom-keymaps-in-depth#removing-bindings

**Comment by ArtskydJ** [comment]
The right way to fix this, IMO, is to do what sublime does, which is this:
If you hit <kbd>Alt</kbd>+<kbd>[Number-row] 1</kbd> then it switches tabs
If you hit <kbd>Alt</kbd>+<kbd>Numpad 1</kbd>, then it enters an alt code.

**Comment by Ben3eeE** [comment]
@ArtskydJ This was fixed in a recent version of Atom. If you have num lock on the numeric keys resolve to, for example, `numpad0` instead of `0` which means that it will no longer switch tabs.

If you still experience problems when using the latest stable release of Atom (Currently 1.20.0) then please let us know and we can reopen.

**Comment by ArtskydJ** [comment]
I've since switched away, but I'm glad to hear this is fixed.
