### ISSUE TITLE
Toggle Find in Buffer with Command-F

### ISSUE THREAD

**Issue by jaredpetersen** [atom/atom#6790]
OS: Mac OS X Yosemite 10.10.3
Atom Version: 0.199.0

Hitting the Command-F keys brings up the Find in Buffer dialog box, which is great. However, whenever I want to close that box, I have to go up to the menu bar and toggle it off that way. Most users are used to being able to toggle search functionality via hitting the same command combination again. It's a little annoying to have to go to the extra step.

![screen shot 2015-05-14 at 4 16 49 pm](https://cloud.githubusercontent.com/assets/8802128/7644086/d2f4f7ba-fa54-11e4-8272-c39ed008bfb3.png)

**Comment by mnquintana** [comment]
You can close the Find in Buffer panel with the <kbd>Escape</kbd> key - it actually says it right in that screenshot. The Find in Buffer keybinding refocuses the search input.

**Comment by rodrigoruiz** [comment]
I'm having this problem.
esc key doesn't work.

**Comment by krishkumar** [comment]
@rodrigoruiz check with the keybinding resolver on if esc is being hijacked by any of your installed packages. I had this problem and turns out the git-diff-details package had taken over my esc key.

**Comment by rodrigoruiz** [comment]
Even if I disable all community packages esc still doesn't work

**Comment by rodrigoruiz** [comment]
Did anyone find a solution for this?

**Comment by zolaemil** [comment]
for the record I also had `git-diff-details` plugin running, updating it to 1.4.0 solved the problem.
