### ISSUE TITLE
Atom slow to open + tabs broken (0.199.0 Mac)

### ISSUE THREAD

**Issue by willdady** [atom/atom#6791]
Atom now seems much slower to open after installing the latest version (0.199.0). There's a definite delay of a few seconds from when the window appears until something is shown (Tree view, panes etc.). Oddly this release claims:

'Opening editors is now significantly faster than previously releases'

**And worse**. Opening a file by clicking on it in the tree view no longer opens the file. The tab for it appears at the top of the window but there's no content shown under it. It still shows the rotating help text you normally see when there's no file open.

**Comment by kevinsawicki** [comment]
What platform are you on?

If this happening for all files clicked from the tree view or only certain files? 

Can you reproduce it still if you quit Atom and then launch it via `atom --safe`?

**Comment by willdady** [comment]
@kevinsawicki I've since gone and removed some packages I was no longer using. I also disabled the highlight-selected package which was now throwing an exception after installing this release (richrace/highlight-selected#67). The tab issue seems to have gone away. I noticed it was happening when trying to open the settings screen. The tab would appear but no content.

I do however feel the initial launch of Atom is slower than the previous release.

I'm on OSX 10.10.3

**Comment by kevinsawicki** [comment]
So in this release the window is shown sooner to provide some feedback that Atom has started loading, before the window wasn't shown until Atom has completely loaded.

If you open Timecop from the command palette via `cmd-shift-P` you will see the window and package load times. If you then tried running 0.198 again and opened up Timecop there as well you could then compare the difference in load times.

> Opening editors is now significantly faster than previously releases

This referred to the opening files speedup in https://github.com/atom/atom/pull/6777

**Comment by willdady** [comment]
Ok thanks. I figured the speed up was with opening files. Makes sense.

I guess the side effect of the initial window opening sooner is it (ironically) feels slower because you're left looking at a blank screen momentarily. It would be really great if this screen showed an animation or some text saying the atom was initialising.

Will close. Thanks for your help.

**Comment by erikanderson** [comment]
I am on OSX 10.10.3 and there is like half a second where you are just looking at a blank screen

**Comment by mnquintana** [comment]
@erikanderson That's intended behavior - the window now opens instantly and then loads (see https://github.com/atom/atom/pull/6759). It could maybe be made more clear with a loading screen / indicator, though.

**Comment by erikanderson** [comment]
ok, hopefully it can be sped up more in the coming releases to be as quick/quicker than ST
