### ISSUE TITLE
Show function parameter names on autocompletion

### ISSUE THREAD

**Issue by TiagoMarinho** [atom/atom#6793]
I don't really know if this issue belongs here, but since I like a lot how WebStorm autocompletes code, I think it would be a great idea to implement a code hint that shows functions parameter names. Here's a gif example showing how WebStorm handles this:

![WebStorm parameter hinting](http://i.imgur.com/ikHBaVB.gif)

This feature helps a lot when I don't know exactly how many arguments a function is supposed to handle.

**Comment by mnquintana** [comment]
This issue was moved to atom/autocomplete-plus#455
