### ISSUE TITLE
[0.199.0] All .js files will not open

### ISSUE THREAD

**Issue by gsklee** [atom/atom#6795]
The editor auto-update to 0.199.0 from 0.198.0 and now all files with an `.js` extension will not open properly; sometimes it outright refuse to open while sometimes the file content will load but the corresponding tab will not appear.

**Comment by mnquintana** [comment]
What OS are you running? Can you reproduce this in safe mode (`atom --safe`)?

**Comment by gsklee** [comment]
@mnquintana 
(1) MacOSX Yosemite
(2) `$ atom --safe` works, `$ atom` doesn't, opening from GUI doesn't either

**Comment by mnquintana** [comment]
@gsklee That means one of your installed packages is causing this issue – you can find the culprit either by trying https://atom.io/packages/package-cop or manually disabling / enabling packages. Can you post the list of your installed packages (`apm list --installed`)?

**Comment by gsklee** [comment]
@mnquintana 
```
/Users/kaylee/.atom/packages (5)
├── editorconfig@1.0.0
├── linter@0.12.2
├── linter-js-standard@0.2.4
├── oceanic-next@0.1.1
└── react@0.11.8
```

**Comment by saschagehlich** [comment]
@gsklee `linter-js-standard` is the issue here. It was accessing the accidentally global `path` module which was made non-global with 0.199.0. I just created a PR which got merged and published. Update that package and the bug is gone :)

**Comment by mnquintana** [comment]
@saschagehlich Thanks for the update! I wonder how many other packages have been accessing that accidental global `path` module (/cc @kevinsawicki)

**Comment by gsklee** [comment]
@saschagehlich That's a lifesaver -- thanks! :+1:
