### ISSUE TITLE
Error compiling Less stylesheet

### ISSUE THREAD

**Issue by victorlcampos** [atom/atom#6797]
Hi,
Everytime when I open atom, I get the error:

Error compiling Less stylesheet: /home/victor/.atom/styles.less
Line number: 1
Unrecognised input

I'm using ubuntu and I have other pc with the same config files that the error don't happens.
Someone knows how to help me?

**Comment by 50Wliu** [comment]
Could you please share your styles.less file here?

**Comment by victorlcampos** [comment]
# keymap file

**Comment by lee-dohm** [comment]
What are the contents of the file `/home/victor/.atom/styles.less`?

**Comment by kevinsawicki** [comment]
Closing this out since the contents were not provided, please comment if this is still an issue.

**Comment by lstep** [comment]
I have the same issue (also on Ubuntu).  I got the error after updating several plugins. @kevinsawicki the `styles.less` has been shared by @victorlcampos, on 19 may, I see it in the thread. Mine (`~/.atom/styles.less`) is exactly the same:
```
# keymap file
```

**Comment by victorlcampos** [comment]
I think the problem is atom-sync-settings plugin
