### ISSUE TITLE
(SOLUTION) Session restore on windows still failing with build 1.99.0 on latest win10 preview

### ISSUE THREAD

**Issue by jonseppanen** [atom/atom#6798]
Windows 10 insider preview 10074 / Atom 1.99.0

Editor file saved in storage dir is being saved with a long string of hex in the filename (editor-ac42cf437b339099db1a29.......) and not being read by atom on startup.
Each startup makes a new file.

Renaming one file to simply "editor" allows atom to open and restore my previous session.

Hope this helps.

**Comment by 50Wliu** [comment]
cc @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
@jonseppanen After quitting Atom with one or more editor windows open, what is the contents of the `application.json` file in your `storage` directory?

**Comment by jonseppanen** [comment]
Application.json shows:

[{"initialPaths":["C:\\Users\\xxxxxxxx\\OneDrive\\Dev\\ww\\public_html\\css"]}]

This opens up when I open atom.

Strangely, after having multiple windows open it seems to be working now as it should - previous session is now always restored.

Is anyone else seeing this on this configuration?

**Comment by maxbrunsfeld** [comment]
@jonseppanen so is everything working for you?

**Comment by izuzak** [comment]
@jonseppanen Let us know if you can still reproduce this problem in the latest version of Atom (0.201.0) and in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) -- closing this for now.
