### ISSUE TITLE
Complete malfunction even in safe mode

### ISSUE THREAD

**Issue by gsklee** [atom/atom#6803]
![1](http://i.imgur.com/37PO32t.png)
![2](http://i.imgur.com/Jb8h47t.png)

Might related to #6795, but basically I cannot do anything with the editor now.

**Comment by gsklee** [comment]
Or maybe #6794, really no idea.

**Comment by gsklee** [comment]
My guess is it's trying to access directories that I've just deleted.

**Comment by saschagehlich** [comment]
Which packages do you have installed? This might as well be related to a buggy community package

**Comment by 50Wliu** [comment]
Please try renaming `~./atom` to something like `~./atom-backup` and see if that helps.

**Comment by kevinsawicki** [comment]
@gsklee what version of Atom are you using?

**Comment by kevinsawicki** [comment]
@gsklee Also, would it be possible for you to copy the entire stack trace here? It would be great to see the lines below the fold right now.

**Comment by gsklee** [comment]
(a) 0.199.0

(b) The issue has ceased to exist for me and I've got a clear idea on what happened:
- My projects are inside a Linux box which I mounted to my Mac through SSHFS
- I open up the project folder `project-x` and do some editing, then delivered my codes, then closed Atom
- I deleted the project folder with `rm -r project-x`, then rename another project folder to the exact name with `mv whatever project-x`
- When I tried to open up the folder that's been newly renamed to `project-x`, the editor attempted to reload last opened project windows then proceeded to explode as shown inside the screenshots
- I fixed the situation by unmounting my SSHFS drive then remounting it

**Comment by gsklee** [comment]
So yeah, it's related with #6794

**Comment by gsklee** [comment]
So yeah, it's related with #6794 and #6605

**Comment by lee-dohm** [comment]
Actually, this sounds like a regression of #4939.

**Comment by nathansobo** [comment]
Sorry. The reference was a typo.
