### ISSUE TITLE
Avatars in package view sometimes do not render

### ISSUE THREAD

**Issue by xPaw** [atom/atom#6806]
In console there's this line:
> Resource interpreted as Image but transferred with MIME type text/plain: "file:///C:/[snip]/Atom/Cache/settings-view/atom-1431701305839".

And looking up that file shows that's its a empty 0kb file.

Perhaps it should check if the cached file can actually be used before using it, and why did it cache an empty file in first place.

**Comment by 50Wliu** [comment]
Actually, @xPaw, could you please move this to the [settings-view](github.com/atom/settings-view) repo?  Thanks.

**Comment by xPaw** [comment]
Looks like there's already an issue atom/settings-view#327.
