### ISSUE TITLE
Atom v0.199.0 Closes when pressing any menu Option

### ISSUE THREAD

**Issue by pablocrivella** [atom/atom#6807]
After upgrading to version v0.199.0 Atom closes on OS X Yosemite when pressing any menu option like ```atom, file, edit``` etc.

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode (`atom --safe`)?

**Comment by pablocrivella** [comment]
Same issue runnning ```atom --safe```

**Comment by mnquintana** [comment]
Do you get a crash report? Or does it just quit outright? Or does the window close, but Atom doesn't quit?

**Comment by pablocrivella** [comment]
No crash report, the window closes immediately when i press one of those menu options and there's no atom process running after that.

**Comment by kevinsawicki** [comment]
@pablocrivella could you check the `Console.app` for any Atom related reports or logging?

**Comment by pablocrivella** [comment]
Is this useful?

https://gist.github.com/pablocrivella/49d1fc32958d4ac03b61

**Comment by pablocrivella** [comment]
The problem was on my mac apparently, i restarted it and it's atom working fine. :sweat_smile:
