### ISSUE TITLE
Atom as a Chrome OS App

### ISSUE THREAD

**Issue by gxela** [atom/atom#6809]
Atom is mostly all written in coffee, and Google Chrome Apps are JS based(would have to package all assets and resources for the app). 

Would it be possible to turn Atom into a Google Chrome App? 

I am thinking if I should invest time to to making it happen, because I recently bought a Chrome Book and would really like to have Atom as a Google App.

**Comment by thomasjo** [comment]
Atom is built on Electron which is built on Chromium and Node. The latter is where the problem lies. There are also a fair amount of native modules in used that will not run on a proper Chromebook. Getting everything in place for your request to happen will most likely require gargantuan efforts.

**Comment by gxela** [comment]
thanks

**Comment by mark-hahn** [comment]
This may help:
https://discuss.atom.io/t/atom-on-chromebook-was-lets-talk-chromeos-resolved/8644/74

**Comment by viniciuscr** [comment]
install node on chromeos won't help?
it's quite easy to do it.

**Comment by lee-dohm** [comment]
The Atom team has no plans to expand Atom to Chrome OS.

**Comment by gxela** [comment]
That is too bad really. I don't use ChromeOS that often nowadays but if it was all I had I would be sad about no Atom on ChromeOS.

**Comment by mark-hahn** [comment]
I use nothing but a chromebook and I run Atom on it all day long.  Crouton is your friend.

**Comment by mhsjlw** [comment]
It is possible to use both `node` and `npm` on chromeOS using https://github.com/skycocker/chromebrew

**Comment by viniciuscr** [comment]
I've tried crouton, but a chromebook with very limited disk space and 1 GB ram crouton is a waste of space and memory. Also, sometimes it just won't open atom. I have to try and try 10x before it open.

I remember that I have used chromebrew, but it was a very limited. Nowdays it looks more mature, I will give it a try.

**Comment by mhsjlw** [comment]
Chromeos doesn't have an API for the desktop in my knowledge, so I'm not sure how you'd draw with Gtk
