### ISSUE TITLE
`cmd + shift + click` to add mutliple extra cursors in one go

### ISSUE THREAD

**Issue by jedesah** [atom/atom#6812]
`cmd + click` adds an extra cursor in the editor.

`cmd + shift + click` currently behaves in a weird way that does not appear to be intended. My expectation was for `cmd + shift + click` to add multiple cursors on the lines between the last added cursor and the click position (on the same column as the click).

Does this sound like a good idea? I know I would find it rather useful.

**Comment by lee-dohm** [comment]
Sounds like an interesting idea for a package :grinning:

**Comment by jedesah** [comment]
@lee-dohm Yes, good point. To be fair I did find a pretty good work around for what I was trying to achieve.

It is possible to simply select a portion of the file and then use the "Selection" > "Split into lines" and then press one of the arrow keys in order to quickly create many cursors over a certain region of text.

Note however, that this is not practical over large selections of texts (> 1000 lines) as the editor becomes unresponsive. Might be worth filing a bug against that.

**Comment by lee-dohm** [comment]
Actually, there's lots of work going on for performance under large sets of markers :grinning:

**Comment by jedesah** [comment]
Oh, awesome! :-)

**Comment by mnquintana** [comment]
This is actually a duplicate of https://github.com/atom/atom/issues/2306 – please subscribe there for updates.
