### ISSUE TITLE
Unable to auto-update from 0.198.0 to 0.199.0 on Windows

### ISSUE THREAD

**Issue by kohenkatz** [atom/atom#6815]
Refs: https://discuss.atom.io/t/unable-to-auto-update-from-0-181-0/16896/

I was initially having issues upgrading from Atom 0.181.0 to the new 0.199.0, but then I updated manually to 0.198.0 and still had the problem trying to update to 0.199.0.  I cleared out the Squirrel log from all the old tries, cleared out the package cache, and got the following error:

```
UpdateInfo: Couldn't get release notes for:atom-0.199.0-full.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\moshe\AppData\Local\atom\..\atom\packages\atom-0.199.0-full.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__2(ReleaseEntry x)
```

What's wrong here?

Was the `nupkg` file just generated wrong?

**Comment by incyi** [comment]
Some problem here on Mac OS X Yosemite 10.10.

**Comment by paulcbetts** [comment]
That isn't an error, it's just a warning, your princess is in another castle

**Comment by kohenkatz** [comment]
@paulcbetts OK, but there's nothing else in the Squirrel log.

**Comment by paulcbetts** [comment]
No idea, who writes this crap anyways? Can you give a full (i.e. recursive) listing of your `%LocalAppData%\Atom` directory? I believe you can use the `tree` command to do this

**Comment by kohenkatz** [comment]
Here's my directory listing: https://gist.github.com/kohenkatz/5d36bad2fd96d4ed3b37 (4MB txt file)

There are only two things that I have touched in there:

 - When the update failed the first time, I deleted the `nupkg` files from the packages directory just in case they were corrupted while downloading.
 - I manually unzipped 0.198.0 downloaded from the Releases page into the folder with that version number and updated the `.cmd` (and shell) files to point to that version.

**Comment by paulcbetts** [comment]
@kohenkatz You are somehow stuck on a hella old 0.179.0. Uninstall and reinstall

**Comment by kohenkatz** [comment]
@paulcbetts No I'm not. I'm running 0.198.0.  Just because I had previously been on 0.179.0 and the files are still there, doesn't mean that's the version that's running.

Here are all of the versions that I currently have listed:

 - 179
 - 181
 - 184
 - 187
 - 194
 - 196
 - 198

All shortcut links and the `cmd` files point to 198.

**Comment by paulcbetts** [comment]
If you have > 2 of those, something pear-shaped has happened (my guess would be that your version of Update.exe is super old and didn't get updated somehow)

**Comment by Zireael07** [comment]
My suggestion would be to delete all the old versions and try again.

**Comment by paulcbetts** [comment]
> My suggestion would be to delete all the old versions and try again.

This probably won't help because you'll still have the old Update.exe. Uninstalling and reinstalling will 100% solve this, and you won't lose any of your data or settings. It's a very painless, easy fix!

**Comment by emcek** [comment]
![image](https://cloud.githubusercontent.com/assets/475312/7883061/d9240872-0613-11e5-97d9-01a87b258f33.png)
it happend in 0.201 I can't upgrade and when I try install manually by downloading atom.204.exe file
![image](https://cloud.githubusercontent.com/assets/475312/7883089/14bc83d2-0614-11e5-8632-28ab40a296d2.png)

**Comment by emcek** [comment]
![untitled](https://cloud.githubusercontent.com/assets/475312/7883162/99c2e3c8-0614-11e5-8527-0812a440cf2c.png)

it happend in 0.201 I can't upgrade and when I try install manually by downloading atom.204.exe file

![untitled1](https://cloud.githubusercontent.com/assets/475312/7883164/9fee77b2-0614-11e5-8e0a-48560549350e.png)

**Comment by emcek** [comment]
uninstaling do not help! where a setup log is?

**Comment by benogle** [comment]
Closing. If this is still an issue, please comment and I'll reopen.
