### ISSUE TITLE
Create a viewer API

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#6817]
We already have Markdown and ASCIIDoc files that have their respective viewers for the rendered version of the document. We have viewers for images and there is a package for "viewing" audio files. And then I saw the [perldoc package](https://atom.io/packages/perldoc) today, which extracts the documentation from the current file, renders it and views it.

We should have one API with, most importantly, **one** keybinding to be used to view or preview _any_ file type. So no matter what the active file is, if I hit <kbd>Ctrl+Alt+P</kbd> (for example) the registered viewer for that file type opens up in a new pane. If more than one viewer for that file type is registered, you can select the default one ... or press, for example, <kbd>Shift+Ctrl+Alt+P</kbd> to bring up a viewer list and select one.
## Requirements

> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt).
- **MUST** allow packages to register viewers by scope name using the services API
- **MUST** offer a command `file-viewer:open` to open the single (or default) registered viewer for the file in the active editor (or selected file in the tree-view)
- **MUST** offer a command `file-viewer:listViewers` to open the list of registered viewers for the file in the active editor (or selected file in the tree-view)
- **SHOULD** allow the single (or default) registered viewer to be opened for files that do not have an "opener" registered, such as image, archive or audio types
- **OPTIONAL** offer a hex viewer as an option for all file types (see the [hex package](https://atom.io/packages/hex) for an awesome example)
## Questions
- When preview tabs are enabled, how should viewer tabs behave?
  - Should they be preview tabs? Only sticking around permanently if the tab title is double-clicked?
  - Should they be permanent tabs?
  - Should they be preview tabs, but of their own class so only other preview tabs override them?

**Comment by rgbkrk** [comment]
With something like that, I'd be more happy with providing a viewer for IPython/Jupyter notebooks right inline (instead of just the language package add on).

The hex package is pretty great. Going beyond that, I'm still hoping for a solid hex editor within Atom.

**Comment by claman** [comment]
I really like this idea

**Comment by Evpok** [comment]
Could also work with the pdf viewer, e.g. for LaTeX files. It would also be great if it worked together with https://github.com/atom/atom/issues/3525

**Comment by 7hibault** [comment]
I really like this idea, is there anything new on that matter?
