### ISSUE TITLE
After Updating the Atom  to latest Version of Atom 0.199 on Ubuntu 14.04

### ISSUE THREAD

**Issue by mohdalam** [atom/atom#6818]
When launch the Atom a blank white Screen is shown and Chrome Dev tools Opens automatically on my Ubuntu 14.04 Operating System. Image of that Issue and i re installed the editor more than 4 times. But the Same Issue occurring all the time.

![bug](https://cloud.githubusercontent.com/assets/7526000/7664892/ad3878bc-fbbc-11e4-94c7-c092ef6c918e.png)

**Comment by lee-dohm** [comment]
Try the following:

1. Close all instances of Atom
1. Rename `~/.atom/storage` to `~/.atom/storage-backup`
1. Start Atom again

Let us know if that helps.

**Comment by mohdalam** [comment]
Again the Same Problem 
![again](https://cloud.githubusercontent.com/assets/7526000/7664952/a80b8228-fbbf-11e4-8560-99bb1425c1de.png)

**Comment by mohdalam** [comment]
should i remove the .atom directory

**Comment by lee-dohm** [comment]
Try closing all instances of Atom and start it using `atom --safe`.

**Comment by mohdalam** [comment]
@lee-dohm  Thanks i just removed the .atom directory it start working again Thanks For help.

**Comment by mohdalam** [comment]
![screenshot from 2015-05-16 11 39 12](https://cloud.githubusercontent.com/assets/7526000/7664969/31d44454-fbc0-11e4-8424-88f82290f60f.png)

**Comment by lee-dohm** [comment]
You're welcome. I'm glad I could help!

**Comment by tmmgarcia** [comment]
Just if anyone comes to this issue in the future. Removing `.atom` folder resets atom configurations including plugins and configurations
