### ISSUE TITLE
Preferences don't open

### ISSUE THREAD

**Issue by rm-code** [atom/atom#6819]
When all windows are closed and only the atom header is visible on OSX you can't open the preferences directly. When you press _⌘ ,_ or select the Preferences item from the dropdown menu Atom will only open a new window with a new _untitled_ tab.

Atom 0.199.0

**Comment by lee-dohm** [comment]
Duplicate of atom/settings-view#503. Please subscribe there for updates.

Thanks for reporting!

**Comment by rm-code** [comment]
> Duplicate of atom/settings-view#503. Please subscribe there for updates.

Ah sorry, my bad! I only did a quick search for _preferences_.
