### ISSUE TITLE
Include atom-tree-view-breadcrumb in core?

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#6823]
I was browsing Atom's available packages and I discovered [this](https://github.com/abe33/atom-tree-view-breadcrumb) one. It's not adding (almost) any performance penalties and improves greatly the usability of the tree sidebar with big sub-folders structures, so I thought maybe it could get included in Atom's default packages?

**Comment by thomasjo** [comment]
While it's a cool package, I hardly think it provides essential functionality. I don't understand why it needs to be a core package. I'm :-1: on this.

**Comment by alexandernst** [comment]
@thedaniel While it's not an essential functionality, it does provide that feeling of well polished details and it certainly helps when you're browsing a project with lots of subfolders. And because it doesn't add any extra performance penalties I thought you'd want to add it to the list of default packages. It was just a suggestion anyways, it's up to you ;)

**Comment by Zireael07** [comment]
I looked at the package page and I like it - I work on multiple folders at once, and they have loads of subfolders, so any functionality which makes it easier to realize I have X/data/blah/objects open and not Y/data/blah/objects or Z/data/blah/objects is VERY welcome!

**Comment by mehcode** [comment]
I'm :+1: on putting this in tree-view proper. This is one of those polish things that I had no idea I wanted until I saw it.

**Comment by alexandernst** [comment]
Tie, 1 vs 1 (+1 for me). Somebody else?

**Comment by alexandernst** [comment]
I'm closing this as voting will probably reveal a "no".
