### ISSUE TITLE
Doesn't Scope Whitespace Between Words

### ISSUE THREAD

**Issue by bobrocke** [atom/atom#6824]
That means that show invisibles won't show spaces in lines of text.

See also https://github.com/atom/whitespace/issues/50

**Comment by c0d3h4x0r** [comment]
Please reactivate this issue.  This is a huge annoyance after coming from Notepad++.  When I say "Show Invisibles", I expect ALL invisibles to be shown, including spaces between words within a single line.

**Comment by Arcanemagus** [comment]
@c0d3h4x0r Please follow https://github.com/atom/atom/issues/12157 for further information on the state of invisibles within Atom.
