### ISSUE TITLE
atom command line doesn't launch the current folder without arguments

### ISSUE THREAD

**Issue by edwardloveall** [atom/atom#6825]
Pre **v0.199.0** just typing `atom` from the terminal would open the current working directory. It was the equivalent of `atom .` but now it just launches the app with no directory. Is this change intentional or is it a bug?

**Comment by 50Wliu** [comment]
Intentional.
From the release notes:
>Running `atom` with no arguments from the command line now re-opens the previously-opened windows. Use `atom .` to open the current working directory
