### ISSUE TITLE
Unable to re-install disabled packages

### ISSUE THREAD

**Issue by HitomiTenshi** [atom/atom#6826]
How to reproduce:
- Go to settings -> Install
- Find a package you have installed at the moment
- Press disable and after that click on uninstall
- Restart atom
- Search for your disabled/uninstalled package

You will now see that it is uninstalled AND disabled, but it can't be enabled anymore.
To circumvent this bug you have to use apm through the console in order to re-install that package.

Atom version: ~~0.119.0~~ 0.199.0
OS: Windows 8.1 Pro 64 bit

**Comment by 50Wliu** [comment]
Hi @HitomiTenshi, you're on an extremely old version of Atom.  If the problem still occurs under 0.199.0 (which you can install using the new Squirrel installer), please comment here and I'll reopen the issue.

**Comment by HitomiTenshi** [comment]
oh sorry! it was a typo, I'm on 0.199.0
I'm really sorry!

**Comment by HitomiTenshi** [comment]
I made a video that demonstrates this bug.
You can view it here: http://a.pomf.se/jbedor.webm

I found this issue by accident. I accidently clicked on disable instead of uninstall and after that didn't think anything bad would happen if I click on uninstall afterwards.

**Comment by mnquintana** [comment]
This issue was moved to atom/settings-view#507
