### ISSUE TITLE
Annoying behavior: Atom steals window focus during startup

### ISSUE THREAD

**Issue by haggen** [atom/atom#6828]
Here's a GIF: http://g.recordit.co/XVdFRbpFRV.gif

After launching Atom from terminal, I clicked on the terminal window to maintain focus, but while Atom was starting, it stole focus (as in the current active window) many times.

It's specially annoying since Atom is slow and I want to use the time it takes to be ready in other activities.

Atom is `0.199.0` on OS X Yosemite.

**Comment by soygul** [comment]
Came here just to report this! Grabs focus for 4 times on my machine with the same specs. Plugins might be contributing to this also.

**Comment by haggen** [comment]
Just made a test with a fresh `.atom` directory; Atom took focus for itself 2 times during load.

**Comment by mnquintana** [comment]
I can reproduce this on OS X 10.10.3 and Atom 0.200.0-6431807 – it steals focus twice during window startup (in safe mode).

**Comment by mnquintana** [comment]
Not only does Atom steal focus from other applications during window startup, but Atom windows actually steal focus *from each other* during window startup (ie. if you quit Atom with multiple windows open and then opened Atom again from the Dock) – the focused window changes multiple times.

![screencap1](https://cloud.githubusercontent.com/assets/823545/7691558/6afa04ce-fd89-11e4-85a3-da945b2bb2ff.gif)

**Comment by kevinsawicki** [comment]
I'm guessing this might be related to #6759 since it shows the window, the loads, then focuses it.

**Comment by Zireael07** [comment]
It steals focus on Windows, too.

**Comment by joseramonc** [comment]
Also feel annoyed by this, It steals the focus 3 times when I turn on my computer.
