### ISSUE TITLE
shell command `atom` not opening the current directory

### ISSUE THREAD

**Issue by sungwoncho** [atom/atom#6829]
Normally when I type `atom` in an OSX terminal, Atom opens the current directory with tree view enabled. However, when I upgraded to 0.199.0, it just opens up a blank project with `untitled` tab.

I've tried `Install shell commands` menu under `Atom` tab with no success. Anyone else experiencing this?

Using OSX Yosemite 10.10.3. Happening on both Terminal 2.5.3 (343.7), and iTerm2 Build 2.1.1.

**Comment by lee-dohm** [comment]
This was a deliberate change in v0.199.0, see the [release notes](https://github.com/atom/atom/releases/tag/v0.199.0). You can use `atom .` to open the current directory in Atom.
