### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/pipo/Nourish Care/organization_app/organisations/app/controllers/clients_controller.rb'

### ISSUE THREAD

**Issue by JFilipeG** [atom/atom#6838]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/pipo/Nourish Care/organization_app/organisations/app/controllers/clients_controller.rb'

```
At events.js:141

Error: ENOENT: no such file or directory, open '/Users/pipo/Nourish Care/organization_app/organisations/app/controllers/clients_controller.rb'
    at Error (native)
```

### Commands

```
     -9:53.6.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -9:53 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -9:51.5.0 color-picker:open (atom-text-editor.editor.is-focused)
     -9:46.1.0 core:save (atom-text-editor.editor.is-focused)
     -7:32.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:30 core:save (atom-text-editor.editor.is-focused)
  2x -7:29.3.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "autocomplete-plus",
      "vim-mode",
      "linter"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "fontSize": 12,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v1.5.0
color-picker, v1.7.0
css-color-highlighting, v0.2.4
csslint, v1.1.3
editorconfig, v1.0.0
emmet, v2.3.9
javascript-snippets, v1.0.0
minimap, v4.9.0
monokai, v0.14.0
travis-ci-status, v0.14.1

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @JFilipeG, could you please share what you were doing when this happened?  Did it perhaps involve a git operation or a deletion of the file outside Atom?

**Comment by JFilipeG** [comment]
I was recently using sublime text instead of atom, and when I first opened a project on atom after updating to version 0.199 it just showed the error. But I was still able to use atom normally.

**Comment by mnquintana** [comment]
@JFilipeG In the time that you weren't using Atom, did you change to a branch in your project that didn't have the `organization_app/organisations/app/controllers/clients_controller.rb` file?

**Comment by JFilipeG** [comment]
Definitely no...

**Comment by mnquintana** [comment]
Did you rename, move, or delete any of the folders in that path?

**Comment by JFilipeG** [comment]
No... But I've been able to use atom with no problems and no error messages.

**Comment by kevinsawicki** [comment]
I believe this was fixed by https://github.com/atom/notifications/pull/62 and released.
