### ISSUE TITLE
Making sublime-tabs ready for release

### ISSUE THREAD

**Issue by ddavison** [atom/atom#6842]
Hey guys,

I'm the author of the [sublime-tabs](https://github.com/ddavison/sublime-tabs) [package](https://atom.io/packages/sublime-tabs) and I'll need some help migrating the package.

Right now, there are thousands of people using this package, and the sublime-tabs package relies on the deprecated API to this day with a total count of 29 deprecations. (https://github.com/ddavison/sublime-tabs/issues/53).

@ConnorVG gave this a shot, but was unsuccessful in his attempts.  I've also attempted to fix these deprecations, but I, as well as others, have failed with errors like "undefined is not a function" trying to use `atom.views.getView(atom.workspace).command` etc etc.

### So the question...
Is there a plan to have this implemented in core?  and if not, is there somebody that uses sublime-tabs, and can assist me with removing all these deprecations so sublime-tabs will still work in Atom v1?

Reference Material:
https://github.com/atom/atom/pull/2205
https://github.com/ddavison/sublime-tabs/issues/43
https://github.com/atom/tree-view/issues/3

*(fyi, i'm opening this issue per the [blog post](http://blog.atom.io/2015/05/01/removing-deprecated-apis.html) stating we can open a help issue here)*

**Comment by lee-dohm** [comment]
#3683 is still marked as v1.0 roadmap, so I would say that indicates that there still is a plan to have this implemented in core ... but I'm not an Atom Core team member, so I should probably let them speak to that :grinning:

/cc @atom/owners

**Comment by benogle** [comment]
We can help upgrade. One of us will look at it this week. We honestly probably wont get to the non-performance, and non-deprecation related things on the roadmap before 1.0.

**Comment by ConnorVG** [comment]
@benogle :kiss:

**Comment by v3ss0n** [comment]
Sublime functionality indeed need to be in core. Please consider. @izuzak .

**Comment by iamstarkov** [comment]
any news? do you still need help? if so, what directions are not already taken?

**Comment by ddavison** [comment]
an update - there is an individual working on getting this implemented to core, and has a PR!  https://github.com/atom/tabs/pull/145

**Comment by iamstarkov** [comment]
okie, thx

**Comment by 50Wliu** [comment]
Hi @ddavison since this atom/tabs#145 has been merged, I'm going to close this.
If you still want this open just leave a :speech_balloon:!

**Comment by ddavison** [comment]
yep!  i'm so glad.  I am now closing all my issues in reference to that PR

**Comment by jglovier** [comment]
![dance](https://cloud.githubusercontent.com/assets/1319791/7963354/47b864e8-09e0-11e5-8bec-77799628efda.gif)
