### ISSUE TITLE
Highlighting error in Github Markdown

### ISSUE THREAD

**Issue by juh2** [atom/atom#6845]
I am using Atom to write Markdown files for processing with Pandoc. Citations are done like this:
[@foo_bar_2013]

If the citation key contains a dot highlighting is garbled. See attached screenshot.

![bildschirmfoto vom 2015-05-18 19 04 40](https://cloud.githubusercontent.com/assets/1416069/7685843/9624e90e-fd91-11e4-97e4-fd111dc55981.png)

**Comment by mnquintana** [comment]
This issue was moved to atom/language-gfm#103
