### ISSUE TITLE
A quick way to toggle packages

### ISSUE THREAD

**Issue by stevemao** [atom/atom#6850]
https://github.com/sindresorhus/atom-jshint/issues/70
I was hoping to toggle packages in command + shift + p menu because its handy and easy. Maybe adding a quick package menu using a different hotkey just to toggle them?

**Comment by mnquintana** [comment]
This looks like a duplicate of https://github.com/atom/settings-view/issues/464 – is that more or less what you're looking for?

**Comment by stevemao** [comment]
I think so :smile:

**Comment by mark-hahn** [comment]
<advertisement>

Check out my package `package-list`.  It shows all packages in one page and
you can toggle them on and off with a single click.

If you are doing this to find out which package is causing some behavior,
check out my `package-cop`.  It is complex but it can do a bisect operation.

</advertisement>
