### ISSUE TITLE
command-line help?

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#6852]
Is there a command-line argument to show help?  I've tried ...

- `atom -h`
- `atom --help`
- `atom -H`

IMHO any of the above should show a help display.

atom 199
ubuntu 14.0.4
apm  0.167.0
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.9.1

**Comment by lee-dohm** [comment]
`atom --help` works for me using Atom v0.200.0-adb4988 on Mac OS X 10.10.3. Looks like it might be a Windows-specific issue.

**Comment by mark-hahn** [comment]
> it might be a Windows-specific issue.

I wouldn't know since I run linux.  (big grin) 

It isn't a real problem though.  I had forgotten that I was starting it with nohup and the help was appearing in `nohup.out`.  Sorry to bother everyone.
