### ISSUE TITLE
Display release note when atom updating done

### ISSUE THREAD

**Issue by huanzhang** [atom/atom#6853]
Release v0.199.0 has some notable changes that impact my habits of use atom. For example, opening current working directory need to run command "atom ." instead of just "atom".

To improve Atom's user experience, I think this is necessary.

**Comment by Zireael07** [comment]
Release notes are already automatically opened once you open Atom after update.

**Comment by lee-dohm** [comment]
@Zireael07 is correct, the release notes already automatically open after Atom is updated. Also, could you let us know which OS and version you are running? And if you installed Atom or built it?

**Comment by mark-hahn** [comment]
I have never seen release notes appear at any time ...

ubuntu 14.04
atom 199
apm 0.167.0
npm 2.5.1
node 0.10.35
python 2.7.6
git 1.9.1


On Tue, May 19, 2015 at 9:03 AM, Lee Dohm <notifications@github.com> wrote:
>
> @Zireael07 is correct, the release notes already automatically open after
Atom is updated. Also, could you let us know which OS and version you are
running? And if you installed Atom or built it?

**Comment by mnquintana** [comment]
@mark-hahn Release Notes will never appear after an update if you're reinstalling from scratch each time (which you have to on Linux if you're not using the unofficial PPA or similar)

**Comment by huanzhang** [comment]
@lee-dohm
➜  ~  sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D136
➜  ~  atom -v
0.199.0

**Comment by TouPye** [comment]
Never seen any *auto release note* after an update
Currently on Windows 8.1 - Atom 0.200.0 (installed version)

**Comment by mehcode** [comment]
Likewise. I've never seen this either. On Ubuntu and I'm using the unofficial ppa on one computer and installing new `.deb` directly after each release on another.

---

I would *love* this though. None of my employees get the automatic release notes and they all use the unofficial ppa. The switch from `atom` to `atom .` caused a bit of confusion for a few minutes that could have been avoided.

**Comment by 50Wliu** [comment]
The release-notes package is no longer bundled with Atom.
