### ISSUE TITLE
Find in project when using symbolic links

### ISSUE THREAD

**Issue by andreialecu** [atom/atom#6854]
I have a project that has a `project/test-app` folder in it in which `project/test-app/node_modules/depmodule` is sym linked to the root `project` folder

This creates an infinite path depth in the path of: `test-app/node_modules/depmodule/test-app/node_modules/depmodule/...`

The find function in Atom will recurse this forever. An useful feature would be to be able to specify a max path depth.

**Comment by lee-dohm** [comment]
Or to simply detect loops.

**Comment by pauldowman** [comment]
I have the same problem. I think it should actually just not follow symlinks, which is a much simpler solution. It could be an option too if that's controversial.

**Comment by lee-dohm** [comment]
@pauldowman have you unchecked "Follow Symlinks" in the Settings View?

<img width="656" alt="screen shot 2015-11-26 at 10 49 03 am" src="https://cloud.githubusercontent.com/assets/1038121/11429327/56573f3a-942b-11e5-8caf-5384ff28b9f9.png">

**Comment by pauldowman** [comment]
@lee-dohm Doh! Thanks. That's good enough for me.
