### ISSUE TITLE
Unable to set atom as default program to open files

### ISSUE THREAD

**Issue by cytsunny** [atom/atom#6860]
I am using atom on Windows 7. After the recent update to version 0.200.0, I am not able to set atom as my default program to open files. 

Before the (auto)update, atom is set as my default program to open .js, .php, .blade.php, .json and .html files. However, after the update, the system is unable to find atom on the default program list and therefore ask me for a default program again. I am able to find and select atom when browsing the file system when asked to set the default program, but when I click open, it fails to set as default.

![atom_error](https://cloud.githubusercontent.com/assets/3927120/7718471/6130ce68-fee3-11e4-8f76-40b0da233adb.png)

As shown above, it can be found but when I click open, nothing happens.

The atom runs smoothly with no error message shown.

**Comment by TouPye** [comment]
Did you try to reboot your computer after the update? 
I know that WIndows sometimes has weird issues after some program updates..

**Comment by 50Wliu** [comment]
Related to #4893.

**Comment by cytsunny** [comment]
I have tried rebooting the computer after the udpate. (or to be exact, I turned off my computer when I left office yesterday and turn it on again today) The problem still exists.

**Comment by kokuou** [comment]
I have the same issue. Using the executable in the newest update as the default program will not launch Atom or open the file. The atom.cmd in the bin folder will work, but then you get an ugly icon and a flash of a command prompt before opening every file.

**Comment by cytsunny** [comment]
Thanks @kokuou  your feedback Your feedback helps me at least being able to set atom as default program, so now I am having the same problem as you. A falsh of a command prompt is not a big problem to me, but the icon is really ugly.

Yet at least it is not a big deal now and the atom team can lower the priority a bit.

**Comment by dmase44** [comment]
I have the same issue on Win7. Previous to the 1.2.0 update my file association were working fine and the atom.ico was present in default programs. Now every workaround I have tried does not work. Most end up pointing to Update.exe witch does nothing. The atom/app-1.2.0/atom.exe does open atom but doesn't show in the default programs to select for file associations even after setting it in the variable path. This is a shame having to right click on a Brackets icon to open with Atom.

**Comment by jotun-from-muspelheim** [comment]
+1, same issue.

**Comment by damieng** [comment]
Fix checked in to master. Will now appear in the list of apps from "Open With..." and the update will take care of updating/correcting the exe path.

**Comment by DingBEN** [comment]
NOPE... first install on WIN 7 total ZERO... no shortcuts, and all the other problems listed...
must search file system to see where installed and will only com up if create a shortcut that points to the 1.8.0 folder and I posted details in another thread and it appears someone deleted it! whateva!

**Comment by damieng** [comment]
"Atom installation on Windows 7 produced no shortcut or OS integration" 

I'll remove the messages from this thread as it was about a very specific part of the install and yours seems to be a much wider issue.
