### ISSUE TITLE
how to tell whether --one is working?

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#6861]
I rebooted to make sure nothing was running and then started atom with the --one option.  I got 14 deprecation warnings and the only message in the console was `Window load time: 3281ms`.  

Is there some way to tell when atom thinks it is in this mode?  Can I query some variable in the console?

atom 199
ubuntu 14.0.4
apm 0.167.0
npm 2.5.1
node 0.10.35
python 2.7.6
git 1.9.1

**Edit:** @leedohm just explained that a lot of deprecations don't cause crashes.  This may explain what I'm seeing.  I'd still like to know some way to verify `--one` is working.

**Comment by izuzak** [comment]
> I rebooted to make sure nothing was running and then started atom with the --one option. I got 14 deprecation warnings and the only message in the console was Window load time: 3281ms.

Can you share a screenshot of the deprecations shown in deprecation cop? I'm guessing those will be deprecated selectors, not deprecated API calls.

 > I'd still like to know some way to verify --one is working.

Open the devtools console and type this:

```
atom.getLoadSettings().apiPreviewMode
```

If `--one` is working, that will return `true`. If it's not working, it will return `false`.

**Comment by izuzak** [comment]
Also, since I think this answers your question, I'll close this. Let us know if there's anything else.
