### ISSUE TITLE
Mac with weird E

### ISSUE THREAD

**Issue by Pwhitcomb** [atom/atom#6862]
Now I know that this isn't by an standards an officail problem, I just don't know what to do.
I can't seem to find the setting to turn off the weird E thing that appears in all the empty fields.
![screen shot 2015-05-20 at 12 13 31 am](https://cloud.githubusercontent.com/assets/5994321/7720694/1b65e1ce-fe85-11e4-863e-e83c7b89b7fd.png)

**Comment by mark-hahn** [comment]
Try a different UI theme.

**Comment by Pwhitcomb** [comment]
Even when changing both the UI Theme and the Syntax Theme, the character still persists

**Comment by thomasjo** [comment]
Does it happen in safe mode?

**Comment by lee-dohm** [comment]
I suspect that somehow your `config.cson` got saved with an encoding other than UTF-8.

**Comment by Pwhitcomb** [comment]
@thomasjo The character is still there in safe mode

**Comment by Pwhitcomb** [comment]
@lee-dohm This is my config.cson file, The problem also appears to be in the line numbers as well.
![screen shot 2015-05-20 at 7 42 20 pm](https://cloud.githubusercontent.com/assets/5994321/7740608/146bd87a-ff29-11e4-8ebe-171930187b2c.png)

**Comment by lee-dohm** [comment]
I'm pretty sure we've seen this line number thing before and, if I recall correctly, it was a somewhat simple fix.

**Comment by lee-dohm** [comment]
Here it is: https://github.com/atom/atom/issues/5488

**Comment by Pwhitcomb** [comment]
@lee-dohm Thank you very much. My Font Family field was left blank, however when I entered Times New Roman it seemed to have fixed itself
