### ISSUE TITLE
Wrong indentation in deprecation cop

### ISSUE THREAD

**Issue by goffreder** [atom/atom#6863]
In the list of the "Deprecated selectors", if you expand one row, the next one becomes indented as it's part of the row above. See screenshot.

![schermata 2015-05-20 alle 09 33 47](https://cloud.githubusercontent.com/assets/156642/7720996/722c5896-fed3-11e4-9932-13d86aa7e9af.png)

**Comment by izuzak** [comment]
This issue was moved to atom/deprecation-cop#49
