### ISSUE TITLE
Atom::getCurrentWindow() is public but not displayed in API docs

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#6864]
[`Atom::getCurrentWindow()` is a public method](https://github.com/atom/atom/blob/v0.200.0/src/atom.coffee#L450), but it's [nowhere to be found](https://atom.io/docs/api/v0.200.0/Atom#instance-center) in the current API docs, which is kind of strange.

**Comment by mnquintana** [comment]
The only difference I could find in the atomdoc markup is that it's the only method without punctuation at the end here: https://github.com/atom/atom/blob/v0.200.0/src/atom.coffee#L449

Would that really be enough to break it?

/cc @benogle

**Comment by lee-dohm** [comment]
Let me try running Endokken over it.

**Comment by lee-dohm** [comment]
Oh, I think I see what the problem is ... there is a `@getCurrentWindow` *and* a `getCurrentWindow`. And this is covered in atom/donna#3

**Comment by 50Wliu** [comment]
Seems to exist now! https://atom.io/docs/api/v1.27.0/AtomEnvironment#instance-getCurrentWindow
Probably thanks to the JS conversion.
