### ISSUE TITLE
Not openning folder nor tree view

### ISSUE THREAD

**Issue by piranna** [atom/atom#6865]
When executing v 0.200.0 from command line, Atom open an empty untittled file instead the ones from that directory, and in fact the tree view don't get open both with the shortcut or the menu option. Other tabs like preference are working. After executing ```atom .``` the tree view gets shown and it works normally, and also now it gets shown when launching it without arguments too as it should do.

**Comment by izuzak** [comment]
@piranna Yeah, that's expected behavior -- there's been a change to how the `atom` command works if you run it without arguments: https://github.com/atom/atom/pull/6690. Hope this explains things.

**Comment by piranna** [comment]
Definitely NOT what I wanted. If I exec a command without arguments, it must to launch from the current directory, not one-whatever-the-hell-the-latest-execution-was. This should be done (if so!) by a ```--latest-session``` flag or similar. KISS.

If open the latest session is the new expected behaviour when no arguments is given, a big -1 for Atom although it's not too difficult to exec ```atom .``` instead, but that's not the point... What's the reasoning behind that?

**Comment by izuzak** [comment]
> What's the reasoning behind that?

The pull request I linked to links to the issue it closed, I hope that provides some context.

**Comment by piranna** [comment]
I've read both the pull-request and the issue it closed, and the reasons given to do it that way are a bad joke, it totally goes against usability and the expected behaviour of any UNIX command. The "open last window" should be behind a flag and not to be the default behaviour, specially if the main reason given is that "I'm too lazy"... WTF?!?!

I have several projects open at the same time and several terminals, both personals and for work, and when I go to a different one I just type ```atom``` to move to the desired editor or open a new one. With the new behaviour this becames useless since it will always open the last one.

**Comment by izuzak** [comment]
Thanks for the feedback, @piranna. You might also be interested in https://github.com/atom/atom/issues/6605 which requests a way to disable this behavior.

**Comment by piranna** [comment]
> Thanks for the feedback, @piranna. You might also be interested in #6605 which requests a way to disable this behavior.

Yes, thank you for pointing me to that another issue.

Sorry for being a little angry, although that feature could be useful in some contexts, I think it should be an opt-in instead of an opt-out. In fact, that's how they do it in Chrome and Firefox and I use them because I want to continue with my surfing session, but on my editor, I use to have several editing sessions at the same time and this feature would made it more difficult withour a really valid reason more than some personal preferences and use cases...
