### ISSUE TITLE
Tabbing between snippet areas broken in 0.200.0

### ISSUE THREAD

**Issue by balexand** [atom/atom#6868]
In Atom 0.199.0 and other recent versions, I was able to tab between the areas in a snippet. For example, in Ruby I could type `do<tab><backspace><tab>stuff_that_goes_in_block` to create code like:

```ruby
do
  stuff_that_goes_in_block
end
```

Here is a gif showing this in action in 0.198.0 (also worked in 0.199.0):

![atom198](https://cloud.githubusercontent.com/assets/181187/7730508/0c405eba-fed8-11e4-9f8f-c5bd516c22cf.gif)

Here's a gif showing what happens in 0.200.0, which is very annoying:

![atom200](https://cloud.githubusercontent.com/assets/181187/7730523/1f57d97e-fed8-11e4-8b7a-8c618947f8cd.gif)

Also, this is not the first time I've seen this regression in Atom. I don't remember the version numbers, but this bug has been introduced then fixed before.

**Comment by 50Wliu** [comment]
Could you please move this to the [snippets](https://github.com/atom/snippets) repsitory?  Thanks.

**Comment by balexand** [comment]
Moved to https://github.com/atom/snippets/issues/139
