### ISSUE TITLE
Deprecated selector warning for unmodified styles.less file

### ISSUE THREAD

**Issue by tylersticka** [atom/atom#6869]
Howdy!

This issue cropped up (or at least I noticed it) around 0.199, but it remains in 0.200.

I have one deprecation warning (which sticks around even in safe mode):

```
your local styles.less file
  /Users/tylersticka/Dropbox (Personal)/Atom/styles.less
  Style elements within text editors using the atom-text-editor::shadow selector or the .atom-text-editor.less file extension. If you want to target overlay elements, target them directly or as descendants of atom-overlay elements.
```

If I click that error, I am taken to what appears to be an empty file:

![screen shot 2015-05-20 at 9 49 07 am](https://cloud.githubusercontent.com/assets/69633/7731460/7ba50650-fed5-11e4-9929-3354acc7043a.png)

If I go to the Atom menu and select "Open Your Stylesheet," this is what it looks like:

``` less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

atom-text-editor {

}

atom-text-editor .cursor {

}
```

I thought maybe I had _inherited_ this stylesheet from an older version, so I tried commenting out everything within it... but the deprecation warning remains.

(Apologies if this issue is duplicated, I swear I searched for it before creating a this one!)

**Edit:** I should also mention that I have my `.atom` directory symbolically linked to Dropbox (if you're wondering why my paths aren't simply `/Users/tylersticka/.atom`).

**Comment by 50Wliu** [comment]
Looks like the problem here is that it's including the `%20` in the path instead of changing it to a space.

**Comment by ajgreenb** [comment]
I'm having this issue as well, and I don't have a `%20` in my path:
![screen shot 2015-05-20 at 2 51 27 pm](https://cloud.githubusercontent.com/assets/8922554/7734984/c2b5fc96-feff-11e4-973c-a41a335586b0.png)
![screen shot 2015-05-20 at 2 51 33 pm](https://cloud.githubusercontent.com/assets/8922554/7734989/c8486afe-feff-11e4-9019-91b683454c9e.png)

**Comment by ajgreenb** [comment]
Actually, what fixed this for me was adding `::shadow` after the second `atom-text-editor` selector. With that update, your stylesheet should look like [the new default that ships with Atom](https://github.com/atom/atom/blob/master/dot-atom/styles.less).

**Comment by tylersticka** [comment]
Pasting the raw stylesheet @ajgreenb into my personal `styles.less` resolves the deprecation warning (at least for me). (Though I'm still confused why commenting the styles out entirely didn't do the same!)

**Comment by ajgreenb** [comment]
Yeah, commenting out didn't work for me either. Weird!

**Comment by kdemarest** [comment]
For those seeing this June 5, 2015 and after, here is a valid styles.less file. If anyone knows a better solution, please contribute!

```
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

.atom-text-editor::shadow {

}

.atom-text-editor .cursor {

}
```

**Comment by azat-co** [comment]
This worked for me

```
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

.atom-text-editor {

}

atom-text-editor::shadow .cursor {

}
```

**Comment by 50Wliu** [comment]
Please use `atom-text-editor`, not `.atom-text-editor`.

**Comment by ptibbetts** [comment]
I've just updated to version 1.0.0 and this is still happening.

```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

atom-text-editor::shadow {

}

atom-text-editor .cursor {

}
```

and

```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

.atom-text-editor {

}

atom-text-editor::shadow .cursor {

}
```

both work for me.

**Comment by kdemarest** [comment]
Dear Atom Developers,

Nobody should have to tweak their install simply to upgrade. This is a serious issue. I'm not sure why you aren't giving it priority. Perhaps it is super rare?

Ken

**Comment by globexdesigns** [comment]
I just installed Atom for the first time (never had it before) and I have these messages as well on a clean install of 1.0.

**Comment by benogle** [comment]
@globexdesigns can you paste in your styles.less? The styles.less generated from the current master seems to have the correct selectors.

> Nobody should have to tweak their install simply to upgrade. 

What do you propose? Should we rewrite the styles.less, risking getting it wrong?

**Comment by kdemarest** [comment]
I'll confess that I only poorly understand the problem, but I was imagining something happening at install time like "does styles.less contain certain required elements?  If not, make them." but I could be way off base.

**Comment by benogle** [comment]
Basically what happened is this:

The editor contents are now beneath the [shadow-dom](http://www.html5rocks.com/en/tutorials/webcomponents/shadowdom/) to avoid pollution from the ui. So things like `atom-text-editor .cursor` no longer work because `.cursor` is not a child of atom-text-editor; it's in the shadow dom.

People who downloaded atom before the shadow dom conversion have selectors targeting the non-shadow-dom editor in their styles.less, but of course, they no longer work in the shadow-dom world.

So we wrote a [selector linter](https://github.com/atom/atom-selector-linter/blob/master/src/selector-linter.coffee) to catch the cases where these selectors will not work, and they are reported in the status bar by deprecation cop.

This warning is not fatal. The worst thing that happens is that your user styles that modify things in the editor do not work. In the case here where everyone's user styles are empty, it's a non issue.

Also note the correct form is this:

```less
.tree-view {
}

atom-text-editor {
}

atom-text-editor::shadow .cursor {
}
```

`::shadow` is only necessary when you are breaking through the shadow boundary and styling something inside the editor (cursors, selections, decorations, etc).

**Comment by Ehekatl** [comment]
+1,
This happens on windows if the user name contain space ( and it will be replace to %20)
