### ISSUE TITLE
How do I make atom open the working directory by default?

### ISSUE THREAD

**Issue by CharlesSocial** [atom/atom#6873]
Recently atom has changed to require `atom .` instead of just `atom` to open the working directory. This has been a really frustrating change. How do I make atom open the working directory without the `.` argument?

**Comment by mnquintana** [comment]
You could always make a shell alias and add it to your `~/.bashrc` or `~/.bash_profile`:

```bash
alias atom="atom ."
```

**Comment by jrjohnson** [comment]
:+1: Using an alias doesn't work because I also do ```atom /foo/somefile.txt ```

**Comment by maxbrunsfeld** [comment]
> make a shell alias and add it to your ~/.bashrc or ~/.bash_profile

Yeah, this is the solution that I recommend for people who prefer the old behavior.

I'm sorry for changing the shell command's behavior out from under you @CharlesSocial. The reasons that we felt it was right to make this change before Atom 1.0 are:

* It makes a commonly-desired behavior available from the command-line
* The old behavior is still very easy to achieve, using `atom .`
* It matches the behavior of other popular editors: Sublime Text and TextMate

**Comment by maxbrunsfeld** [comment]
@jrjohnson To support your desired behavior, you might want to make a shell script like this:

```sh
#!/bin/bash

if [ "$#" -eq 0 ]; then
  \atom .
else
  \atom $@
fi
```

**Comment by chloerei** [comment]
`vim` will open in current directory. I think it's annoying if I have to enter `ls .` instead of `ls`.

I set `alias a='atom .'` that I can use original command if necessary.

**Comment by mark-hahn** [comment]
>  I think it's annoying if I have to enter ls . instead of ls.

How does vim re-open the same setup?

**Comment by chloerei** [comment]
@mark-hahn vim has a `mksession` command to store and `source` to restore, but I'm not use this function, I like open with a clean workspase. http://stackoverflow.com/questions/1642611/how-to-save-a-session-in-vim

**Comment by motam** [comment]
See #6605 as well.

**Comment by CharlesSocial** [comment]
What do you guys mean by "open the previous setup"? Right now `atom` always open a new file. I'm not sure I understand the decision because this seems much less convenient than open the working directory.

**Comment by piranna** [comment]
Maybe other editors wotk this way, but it's a bad decission. It would make sense to restore the last session when executing from an app launcher like Gnome Menu, but from command line, common sense dictates that by default it will open on the current directory. The best approach to this is to add a "restore session" command line argument and launch Atom from Gnome Menu with it.

**Comment by CharlesSocial** [comment]
Honestly the alias doesn't work well at all, and setting up a bash script is fine, but feels a little ridiculous.. If there are people on both sides of the fence then this should be a checkbox setting.

**Comment by ricardograca** [comment]
Any ideas why this behaviour is happening even when using `atom .`? I mean, even with the `.` it's still opening the last session instead of the current directory.

Atom 0.200, Ubuntu 15.04.
