### ISSUE TITLE
Searching for Packages error

### ISSUE THREAD

**Issue by borovez** [atom/atom#6874]
Hello, I recently installed Atom on my new PC and I am having this error when I go to settings > packages:

Fetching featured packages failed.
Requesting packages failed: Application error

It does not want to load the features packages, and searching for packages does not do anything.

Can anyone tell me what im missing here? (I have version 2.000)

Thanks!

**Comment by natecox** [comment]
I'm having the same issue. Can search for packages and update existing packages, but fails to find _featured_ packages and themes.

**Comment by 50Wliu** [comment]
Ditto, on Windows 7 Atom 0.200.0, Ubuntu 15.04 Atom 0.200.0, and also on a friend's Fedora with an Atom version of at least 0.198.0.

@natecox what system and Atom version are you using?

**Comment by 50Wliu** [comment]
This issue was moved to atom/settings-view#514

**Comment by borovez** [comment]
btw I am using Windows 7 x64 - Atom 2.000
