### ISSUE TITLE
API request: file created event

### ISSUE THREAD

**Issue by paulpflug** [atom/atom#6875]
Hi,

I have created a function to watch changes in the project by a given pattern.
Due to the usage of patterns, I'm forced to use the `::onDidChange` of the individual files. 
The problem is, that I'm not able to fetch the file created events this way.
I could watch the directory and refresh all watchers on each change, but I would prefer
either a own event like `::onFileCreated` or some parameters passed to the callback of `::onDidChange`, so I can filter the created events

This is far from high priority, but maybe it is easy to implement?
I have looked into the `PathWatcher` and I think this feature could be implemented in this [line](https://github.com/atom/node-pathwatcher/blob/v4.4.0/src/main.coffee#L96) ?

thanks

**Comment by mattapperson** [comment]
+1

**Comment by Swissa** [comment]
+1
