### ISSUE TITLE
More flexible open path location parameters?

### ISSUE THREAD

**Issue by jessegrosjean** [atom/atom#6876]
When you open an Atom path you can optional include an initialLine and initialColumn using the following syntax:

```
/my/path/to/open/test.txt:<line>:<column>
```

During the opening process those line,column values are stripped off the path and provided as metadata to the workspace opener handler. This is useful, but the problem is that the syntax is fixed, no other values can be passed in other then line, column.

I would like Atom to also read in URL query parameter syntax and send those values through as options to the workspace opener. I don't mean we should break the existing syntax for line column, but instead provide an alternative syntax using query parameter syntax.

For example these would all be equivalent:

```
/my/path/to/open/test.txt:10:1
/my/path/to/open/test.txt:10?initialColumn=1
/my/path/to/open/test.txt?initialLine=10&initialColumn=1
```

The reason for making this change is because then other workspace openers could could read in similar values that apply to them. For example I have an outliner editor (https://atom.io/packages/foldingtext-for-atom) that can filter the outline view with a search. I would like the option to provide an initial search value when opening an outline file, similar to how initial line and column is now provided to the default editor. If query parameter options were available in Atom I could then open a path like this:

```
/my/path/to/open/test.ftml?search=stuff
```

And `search: stuff` would get passed through to my opener as an option.

The implementation would be pretty strait forward:

1. In `atom-application.coffee::locationForPathToOpen` strip and store query parameters key values from the path right before the code that does: `pathToOpen = pathToOpen.replace(/[:\s]+$/, '')`.

2. Include those key values along with the initialLine and initialColumn key values that are being returned.

3. In `window-event-handler.coffee` process the `open-locations` handler a bit differently so that all location metadata gets passed through to `atom.workspace.open` instead of just the line and column.

**Comment by lee-dohm** [comment]
I feel like we shouldn't go half-way. If we want query parameter syntax, then why shouldn't Atom just accept a `file://` URL? This way we have two distinct syntaxes, which can be easily and unambiguously validated.

**Comment by mnquintana** [comment]
@lee-dohm How would that work in the command-line? Or would the two syntaxes be command-line and `file://` URL?

**Comment by lee-dohm** [comment]
I was thinking something like `atom "file://README.md?initialLine=5&initialColumn=5"`? Yes, it is cumbersome, but I think that trying to tack on query parameter syntax onto standard Unix/Windows file paths is going to be problematic to say the least.

**Comment by jessegrosjean** [comment]
> I was thinking something like atom "file://README.md?initialLine=5&initialColumn=5"?

That looks like it would suite my use case.

Few more thoughts:

1. Maybe obvious, but allowing for this sort of syntax would provide some benefit to Atom core. Right now you can only pass line/column options in when opening an editor, with this change you could pass in any of the other editor options listed at [workspace.open](https://atom.io/docs/api/v0.200.0/Workspace#instance-open)

2. The underlying issue (why Atom needs to do this work and package can't) is that Atom uses the URI as an identifier for the pane that represents the URI. But we don't want the :line:colum (in case of normal paths) or the query parameters in case of URLs to be part of that identifier. So Atom needs to parse and remove those values before it starts using the URI as an identifier, and then pass those removed values into the opener as options.

3. What do you think the final URI that gets passed into `workspace.open` should be for `file://README.md?initialLine=5&initialColumn=5`. I think the options are:

    - file://README.md?initialLine=5&initialColumn=5
    - file://README.md
    - README.md

I think it's the third option that we want?

**Comment by lee-dohm** [comment]
I think option 2 and option 3 are essentially equivalent and option 1 is potentially equivalent if nothing inside of `workspace.open` tries to interpret the query parameters.

**Comment by jessegrosjean** [comment]
> I think option 2 and option 3 are essentially equivalent and option 1 is potentially equivalent if nothing inside of workspace.open tries to interpret the query parameters.

At some point Atom needs to decide the exact string to use for things like: `workspace.paneForURI`, `editor.getURI`. For example now when you do this on the command line:

```
atom README.md
atom README.md:1
atom README.md:1:2
```

They all resolve to the same Atom window and editor pane. Following from that it seems to me that these paths should also all resolve to the same Atom window and editor pane.

```
atom README.md:10
atom file://README.md
atom file://README.md?searchAllPanes=true
```

But for that to happen then Atom needs to decide on what the part of `file://README.md?searchAllPanes=true` to use as the URI identifier within the workspace.

## I think a design that could solve these issues would be:

1. When Atom opens a URI it is immediately converted to a `file://` URL if it doesn't already have a protocol defined. In that case any trailing :line:column is also converted to URL query parameters.

2. Next (using `require('url')` terminology) Atom strips the URL of the search and hash strings and stores those values in the options object that's passed into the `workspace.addOpener` callback. Instead of passing a generic URI into the opener a URL is passed constructed from the `protocol + pathname` components of the original URL. URLs minus search and hash become the unique identifiers for opened items in the workspace.

3. `workspace.paneForURI` and `editor.getURI` would become `workspace.paneForURL` and `editor.getURL` since the open process would convert everything to URLs. I guess the API names wouldn't have to change since URLs are URIs, but it would be more specific to rename to URL.

I think these changes would make for a more consistent and extensible system.

## More motivation cases:

- `atom file://README.md?find=text` – Open the find panel with the given text along with the buffer.
- `atom file://README.md?encoding=celtic`  – Override the default encoding.
- `atom file://README?grammar=markdown` – Override the default grammar.
- `atom file://README?softwrap=true` 
- etc

Does this make sense, or not worth the effort?

**Comment by lee-dohm** [comment]
Regarding the `workspace.paneForURI` and `editor.getURI` commands, I would expect `workspace.paneForURI` to be able to accept any URI and to treat `file://README.md` and `file://README.md?searchAllPanes=true` as equivalent. I would also expect `editor.getURI` to return the "normalized" URI, whatever that is defined to be.

On the other hand, since custom openers can be added, I would expect the *opener* to decide what is important as a unique identifier or not. This means that I would expect step 2 to leave the URI alone and pass it unchanged to the opener.

For example, there was a recent question about whether one could open a second Find Results pane. Let's say that one could. (I haven't looked at the implementation of the Find Results window, so the following is all just made up for illustration.) Let's say that the URI would follow the format `find-in-project:searchText?caseSensitive=true&regex=false`. I would say that it should be up to the Find Results opener to determine if the query parameters are an important part of determining an unique window or not.

I think it makes sense. As to whether it is worth the effort, I don't know (and I mean that literally, not in a "I'm going to say I don't know rather than tell you no outright" sense). So far, your proposed change would be the only client of the enhanced feature.

**Comment by jessegrosjean** [comment]
@lee-dohm Thanks again for your help.

Here's a solution that's working pretty well for me.

It's an opener that works by parsing the incoming `filePath` as a URL. If the filePath isn't normalized (i.e. the incoming filePath doesn't match the parsedURL.pathName) then it moves the URL query variables into the options and passes the now normalized URL back through `atom.workspace.open`.

This solves almost all of my needs. I still think it would be a bit nicer and more consistent if Atom were doing this for me as it already handles :line:column path metadata. There is for example some browser process logic about which window paths should be opened in that my paths miss out on. But generally this solution is good enough for me.

I'm going to close this issue, but I'll also post to the discussion forums so the idea doesn't get lost in case down the road someone wants to take this back up.

```coffeescript
atom.workspace.addOpener (filePath, options) ->
  parsedURL = url.parse(filePath, true)
  if parsedURL.protocol is 'file:' or not parsedURL.protocol
    unless path.extname(parsedURL.pathname) is '.toml'
      return

    if filePath isnt parsedURL.pathname
      options.hash ?= parsedURL.hash
      options[key] ?= value for key, value of parsedURL.query
      atom.workspace.open(parsedURL.pathname, options)
    else
      new TomlEditor(filePath, options)
```
