### ISSUE TITLE
TextEditor should have a setReadOnly function

### ISSUE THREAD

**Issue by mostafaeweda** [atom/atom#6880]
The current way to set an editor to read only mode is:

``` js
var editor = atom.views.getView(editor);
// set it to read only mode.
editorView.removeAttribute('tabindex');
// remove the cursor line decoration.
editor.getDecorations({class: 'cursor-line', type: 'line'})[0].destroy();
```

There should be a better way to do that.

/cc @maxbrunsfeld @nathansobo @benogle @bolinfest

**Comment by nathansobo** [comment]
Definitely :+1: with this, but don't have time just now to implement it. We basically want to remove cursors/selections entirely from the editor. Not sure what other UI changes would be required after that.
