### ISSUE TITLE
Middle mouse button scrolling in the text editor

### ISSUE THREAD

**Issue by ncreep** [atom/atom#6884]
Hi,

Is it possible to enable middle mouse button scrolling on the text editor?

I see that middle button scrolling is possible in various places, e.g. in the `tree-view` component,  so I'm guessing that this default behavior (at least on Windows) was somehow blocked on the text editor. From what I've managed to understand so far, [this](https://github.com/atom/atom/blob/75d02cdbc92b4ed5ef0139a4abe24fddd8d0e397/src/text-editor-component.coffee#L369) is the line responsible for it. Is there any way to override this behavior as a plugin?

Thanks.

**Comment by blah238** [comment]
:+1:

**Comment by samuelms1** [comment]
Would love to use this feature.  I use a 3m mouse at home that has no scroll wheel (see http://www.amazon.com/3M-Wireless-Ergonomic-Mouse-EM550GPS/dp/B001P23Z36).  With a 3m mouse, the only way to scroll is to middle click to pan or to grab the scroll bars.  The middle click support is awesome when it's there.

**Comment by klingel** [comment]
:+1:

**Comment by qlum** [comment]
I'd very much like this option, for me at least its by far the fastest most accurate way to scroll through long documents.

**Comment by ncreep** [comment]
I've managed to come up with a hack that provides a partial solution to this issue. It can be implemented by adding the code in [this gist](https://gist.github.com/ncreep/a87f127abd962d3cec56) to `init.coffee` and `style.css`.

What this achieves is the ability to scroll while holding the middle button down. It doesn't support the ability to scroll by clicking the middle button and letting go (though the scroll icon remains visible, and one has to click something to make it go away).

It's a terrible hack, and will probably get broken by some future release. But for the moment, it seems to be working reasonably well.

**Comment by ChrisPetr0** [comment]
Just switch to atom, would love this functionality

**Comment by Frozen-byte** [comment]
I would prefer the same behavior like the Firefox "autoscroll" feature.

**Comment by mirkea** [comment]
@ncreep your solution works perfectly, except when I split the panes

**Comment by ncreep** [comment]
@mirkea: glad that it helps, if someone could come up with alternative to the deprecated `Object.observe` call, then the splitting issue should be solved as well.

**Comment by ncreep** [comment]
@mirkea: I've update the gist, it now supports moving/splitting tabs between panes.

**Comment by mirkea** [comment]
@ncreep Excellent. Thanks a lot

**Comment by jcaudle** [comment]
The gist seems really useful. Is there a reason it wouldn't work as a PR to the project @ncreep?

**Comment by ncreep** [comment]
@jcaudle: It seems to me that the scrolling behavior was blocked on purpose (like in the link in this issue's description and also in some CSS directives). Currently, Atom even emits a warning when the scrolling override happens. So I would not want to override this behavior without input from someone more knowledgeable about Atom's innards.

Also, the gist is a complete hack, it just piggybacks on the scroll icon to do the scrolling, it's not Atom's native scrolling behavior (which is the reason why it can't scroll with a single middle-button click).

**Comment by UziTech** [comment]
I created a package that does this [scroll-editor-on-middle-click](https://atom.io/packages/scroll-editor-on-middle-click)

![scrollonmiddle](https://user-images.githubusercontent.com/97994/32377094-9a0a5e48-c074-11e7-80a7-8aa62d44c3ed.gif)

**Comment by ashthespy** [comment]
Any updates on this? Was wondering for a while why my code didn't compile only to realise that I had inadvertently pasted something instead of scrolling as expected.

**Comment by UziTech** [comment]
@ashthespy install the package [scroll-editor-on-middle-click](https://atom.io/packages/scroll-editor-on-middle-click) to get this functionality back
