### ISSUE TITLE
Not possible to move cursor within last screen line of soft wrapped line

### ISSUE THREAD

**Issue by izuzak** [atom/atom#6885]
Steps to reproduce:

1. open new tab
2. enable soft wrapping
3. trigger the `lorem` snippet (type `lorem` and press `tab`)
4. try to click somewhere within the last line of the wrapped paragraph, and notice that the cursor will always be placed at the end of the line. It's possible to delete characters from the end of that line using backspace, but not move the cursor within it.

Here's a gif where I try to position the cursor within the last line, but it always ends up at the end of the line (and when I press `left` with the cursor at the end of that last line -- the cursor doesn't move):

![](https://cloud.githubusercontent.com/assets/38924/7743436/1596be28-ff9b-11e4-83bb-e6ad167b7a8e.gif)

cc @nathansobo any chance some of your recent changes affected this somehow? :thought_balloon:

**Comment by izuzak** [comment]
Forgot to mention I'm on the latest master version: 

```
$ atom -v
0.201.0-75d02cd
```

**Comment by lee-dohm** [comment]
:+1: Beat me to it by 38 minutes :laughing:

**Comment by abe33** [comment]
Some more information about this issue: 

* It only occurs is the line is wrapped more than one time:  ![wrap-issue](https://cloud.githubusercontent.com/assets/247140/7744732/09c498bc-ffa6-11e4-9786-79962638538e.gif)
* When clicking in the last wrapped line screen line it's possible to insert text at the clicked position: 
![wrap-issue-2](https://cloud.githubusercontent.com/assets/247140/7744847/d21c1c9a-ffa6-11e4-9918-c392b5029de8.gif)
* But it seems to also select all the text from the clicked position til the end of the line, here I'm just pressing the backspace key after a click: ![wrap-issue-3](https://cloud.githubusercontent.com/assets/247140/7744863/eab79374-ffa6-11e4-87da-67fe8aaf162f.gif)

I'm running the same version as @izuzak  on OSX 10.10.3.

**Comment by nathansobo** [comment]
Can you guys give this a try again on master? I reverted the memory savings pull request which I definitely suspect in causing this. I'll try to get to the bottom of this and another issue today and maybe try to merge again tomorrow. Thanks!

**Comment by izuzak** [comment]
Yep, that fixes things -- thanks, @nathansobo. :+1:
