### ISSUE TITLE
the '[' character doesn't work in editor but does in settings view

### ISSUE THREAD

**Issue by Vincentdc94** [atom/atom#6886]
I only have this error in windows. In linux it works fine.

When I type the character in settings view it does work. In the editor if I do "alt gr + [" it doesn't print the character. Instead it prints nothing at all.

**Comment by 50Wliu** [comment]
This seems like a duplicate of atom/atom-keymap#35-can you check that out please and see if that's what your issue is talking about?

**Comment by Vincentdc94** [comment]
Yes indeed installing keyboard-localization solved the problem. My bad, but please fix it out of the box on final release. It's confusing for new users.

Thanks for the help!

**Comment by 50Wliu** [comment]
@Vincentdc94 it'll hopefully get fixed as part of Google's Summer of Code :smile:.  Glad to hear that you fixed your issue, though!
