### ISSUE TITLE
editor.fontSize has no effect

### ISSUE THREAD

**Issue by lexicalunit** [atom/atom#6895]
No matter what I set `editor.fontSize` to in my `config.cson`, it does not change the font size in the editor at all. I can sit here and hit the increase and decrease font hot keys, with my `config.cson` file open, and watch the value go up and down as Atom reloads the file as it changes. And yet, my font never changes.
![screen shot 2015-05-21 at 4 02 12 pm](https://cloud.githubusercontent.com/assets/1903876/7758901/c4e96e02-ffd2-11e4-9bbd-1becbb73e3a4.png)
![screen shot 2015-05-21 at 4 02 02 pm](https://cloud.githubusercontent.com/assets/1903876/7758909/c9807a96-ffd2-11e4-9f45-54ec29cda613.png)
The setting simply doesn't do anything. Ever. Starting atom with `atom --safe` makes no deference.

```shell
$ atom --version
0.200.0
```

**Comment by mnquintana** [comment]
Can you reproduce this if you try changing the font size in the settings UI? Can you paste the contents of your `config.cson`?

**Comment by benogle** [comment]
Also please paste in the contents of your `styles.less`.

**Comment by lexicalunit** [comment]
That was it. Somehow a `font-size` property got in there for the selector `atom-text-editor`. Ignore me!
