### ISSUE TITLE
Buffer changed event doesn't handle line endings correctly

### ISSUE THREAD

**Issue by basarat** [atom/atom#6896]
Tested on windows. 

# Test
Open the console when a text file is active and run the following: 

```
ed = atom.workspace.getActiveEditor()
ed.setText("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n");
ed.buffer.onDidChange(function(diff){ console.log(JSON.stringify({ oldText: diff.oldText, newText: diff.newText })) });
```

Now make the text file active and `press enter`. 

# Errors
What is actually inserted : `\r\n`
What is reported by the buffer : `\n`. 

# Refs
Refs : https://github.com/TypeStrong/atom-typescript/issues/354

**Comment by izuzak** [comment]
Thanks for the report, @basarat. I'm seeing the same on OSX. /cc @nathansobo @maxbrunsfeld

**Comment by lee-dohm** [comment]
Actually, I don't believe this is a bug ...

I followed the instructions above and then viewed the file with the [hex package](https://atom.io/packages/hex):

![screen shot 2015-05-22 at 8 01 12 am](https://cloud.githubusercontent.com/assets/1038121/7773341/bf94e2de-0058-11e5-9236-4aaa21b50909.png)

Unless you're expecting to see `0x0D 0x0D 0x0A`?

**Comment by izuzak** [comment]
@lee-dohm What did you see in the devtools console as the output?

**Comment by lee-dohm** [comment]
I saw the output reporting that `\n` was inserted, as I expected because that's what `0x0D 0x0A` equals in Windows newline mode.

**Comment by izuzak** [comment]
@lee-dohm The part that's confusing me is that when I execute `ed.getText()` after running the snippet -- I see that a `\r\n` was added at the end, but the `console.log` from the snipped above wrote `{"oldText":"","newText":"\n"}` to the console.

**Comment by lee-dohm** [comment]
Yes, this is Atom detecting the line endings to use based on the other line endings in the file. Unix uses just `0x0A` to mean `\n`, but Windows uses `0x0D 0x0A` to mean `\n`. So if I insert `\r\n` into a file that uses Unix line endings, I would expect the changed event to tell me that `\r\n` was inserted. But if I insert `\r\n` into a file that uses Windows line endings (like the example above), I would expect the changed event to tell me that `\n` was inserted.

**Comment by lee-dohm** [comment]
Of course, I would also expect that if I inserted `\n` into a file with Windows line endings that `0x0D 0x0A` would be inserted into the file and that the changed event would still tell me that `\n` was inserted.

**Comment by lee-dohm** [comment]
And that's exactly what happens:

```
> editor.insertText("\n")
{"oldText":"","newText":"\n"}
```

**Comment by izuzak** [comment]
> But if I insert `\r\n` into a file that uses Windows line endings (like the example above), I would expect the changed event to tell me that `\n` was inserted.

Interesting, I'm not sure I would have expected that -- I kind of expected to see the raw text changes which were applied to the file. However, line ending confuse me almost as much as encodings and timezones, so I'm going to politely :runner:  away from this one. :smile_cat: 

Just in case that's helpful, I'm seeing:

```coffee
ed.insertText("\r\n")
{"oldText":"","newText":"\r\n"}

ed.insertText("\n")
{"oldText":"","newText":"\n"}
```

And when I just press `enter` in the editor:

```coffee
{"oldText":"","newText":"\n"}
```

**Comment by maxbrunsfeld** [comment]
> > But if I insert \r\n into a file that uses Windows line endings (like the example above), I would expect the 
> > changed event to tell me that \n was inserted.
>
> Interesting, I'm not sure I would have expected that -- I kind of expected to see the raw text changes
> which were applied to the file.

Yeah, this is a `text-buffer` bug. Though windows and unix *display* the `\n` and `\r` characters differently, the string `\r\n` is two characters regardless of your platform. We just made a simple error in [this code](https://github.com/atom/text-buffer/blob/master/src/text-buffer.coffee#L605): we define the event before we normalize the line endings.

**Comment by maxbrunsfeld** [comment]
By the way thanks a lot for the report @basarat.

**Comment by maxbrunsfeld** [comment]
The fix will be in Atom 0.202.

**Comment by izuzak** [comment]
Thanks, @maxbrunsfeld :zap:

**Comment by basarat** [comment]
Thanks ! :rose:
