### ISSUE TITLE
Atom asks twice for deletion of file

### ISSUE THREAD

**Issue by OldrichKruchna** [atom/atom#6900]
When I click with right button on some file or folder in treeview, Atom ask if I want to delete file which is currently open and then it asks once more correctly for file of folder which was clicked. It's really confusing and I've already deleted some files by mistake.

**Comment by izuzak** [comment]
I'm unable to reproduce this behavior, @OldrichKruchna. Can you provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) and check if the advice in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging) helps, especially running Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by OldrichKruchna** [comment]
In the safe mode I also wasn't able to reproduce it. It has to be caused by some package, I will try to find which one and open issue for it there. But for Atom I will closed it. Thanks!
