### ISSUE TITLE
APM update and getaddrinfo ESRCH errors

### ISSUE THREAD

**Issue by fusion809** [atom/atom#6903]
I am trying to update my Atom packages using: 
`apm update`
but I get the error:
`Request for package information failed: getaddrinfo ESRCH`
Updating them via the GUI package manager fails too. 

| Specification name | Value                                                               |
| ------------------------- | ------------------------------------------------------------:|
| Operating system   | 32-bit Ubuntu 15.04                                         |
| RAM                       | 3.8 GB                                                              |
| Processor               | Intel® Core™ i5 CPU M 460 @ 2.53GHz × 4  |
| Graphics                 | Intel® Ironlake Mobile x86/MMX/SSE2            |

**Comment by izuzak** [comment]
Sounds like a proxy/network problem, not anything specific to apm. See https://github.com/npm/npm/issues/6335 for a similar issue in npm.
