### ISSUE TITLE
Fail to syntax highlight sometimes.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#6905]
Atom fail to syntax highlight ramdomly at : https://github.com/atom/atom/commit/0b34de005cfbff82c972830aa3bbe3938c7bec4f

Tested with javascript and python. 

Had to switch other language highlight and back to fix that.

**Comment by izuzak** [comment]
Can you please provide 1) a snippet of javascript in which syntax highlighting is not applied correctly, 2) a screenshot of what you see, and 3) clarify which part in the screenshot isn't highlighted correctly?

**Comment by v3ss0n** [comment]
i reloaded them , i will test around and send, haven't tried using --safe.

**Comment by izuzak** [comment]
Let us know when you can provide more detailed information, and please follow the [submission guidelines](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) in the future.
