### ISSUE TITLE
UI (status bar and tab bar) becomes too large when maximizing the Atom window

### ISSUE THREAD

**Issue by Dragynfyre** [atom/atom#6911]
I noticed that in the 0.201 release Atom now scales the size of its status bar and tab bar according to the size of the Atom window. This makes the status bar and tab bar too big when you maximize Atom. Could it be related to the Bootstrap 3.3.4 addition in 0.201? The scaling behaviour matches what you would get from a Bootstrap enabled responsive web site.

**Comment by thomasjo** [comment]
This was an intentional change in the "One" UI themes. See https://github.com/atom/one-dark-ui/pull/58.
Just go to your UI theme (dark or light) settings view, and it to compact mode.

![image](https://cloud.githubusercontent.com/assets/3622/7780653/07cd8c16-00e2-11e5-8e01-c0826a6b929b.png)

**Comment by simurai** [comment]
An option would be to split the layout mode with the "responsive" font-size. Then you could turn on/off either. See https://github.com/atom/one-dark-ui/issues/62
