### ISSUE TITLE
Opening projects via Atom command

### ISSUE THREAD

**Issue by yzaguirre** [atom/atom#6913]
Opening a project under the working directory, the following would suffice.
```bash
cd ~/project100
atom
```
When I run `atom` on a second project under the working directory
```bash
cd ~/project101
atom
```
the editor does not open that project (no tree view of project101 folder), but a clean atom instance. 
I noticed this change since 0.199 release.

**Comment by 50Wliu** [comment]
Use `atom .` instead - this is an intended change.  Running `atom` now opens up the last saved instance of Atom (in other words, if you close Atom with `sfsdf.txt` open, then call `atom`, it'll re-open with `sfsdf.txt` open).

**Comment by yzaguirre** [comment]
I'll have an alias for `atom .` even though it can alter `atom /absolute/path`, I don't use the latter.
