### ISSUE TITLE
Atom does not remember session

### ISSUE THREAD

**Issue by russlescai** [atom/atom#6917]
I have a root project folder, but when I remove it (or add other project folders), it forgets the changes and always goes back to the previous project folder.

This is version 0.201.0 (and previous versions), Windows 8.1, and happens in Safe Mode as well.

**Comment by izuzak** [comment]
@russlescai Could you perhaps provide the _exact_ steps for reproducing this problem (starting from when you open a terminal session), so that we can try and reproduce it? Having exact steps would help us understand what exactly you're doing and what your expectations are. Thanks!

**Comment by russlescai** [comment]
Yeah sure,@izuzak, I am not really sure what the correct behaviour should be, just it doesn't feel right the way it is (on Windows).  

First off, this doesn't involve opening atom from the terminal at all, it is opening from the desktop icon, and opening using windows explorer "Open in Atom."

1. Open folder in Windows Explorer
2. Right click on Open in Atom
3. Select a file to read in Atom
4. Click the "X" on the top right of the atom window, to close it
5. Double click the Atom desktop icon. 
6. The folder from (1) should be open correctly (this part works well)
7. In Treeview, remove the folder, and add a different folder (using right click, add/remove project root)
8. Select a file to read in atom
9. Click the "X" on the top right of the atom window, to close it
10. Double click the Atom desktop icon.
11. The previous folder (from (1)) is displayed, not the updated folder from (6). Also the previous file is open (from (3)), not the file from (8)).

As I said, I know there are 101 ways to open atom and select projects, please let me know if I'm doing it wrong. :)

Thanks :)

**Comment by izuzak** [comment]
Thanks for the detailed steps, @russlescai :blue_heart:. I just tried following them, and wasn't able to reproduce the exact behavior you described in Windows 8.1. After step 10, I get a new Atom window, no root folders in the tree view, and an untitled tab. Not what I expected, to be honest. And I do see that if I add/remove root folders that they are _sometimes_ not restored after I exit and restart Atom by double-clicking the Atom icon on the Desktop (but sometimes they are :confused:).

@maxbrunsfeld -- wondering if you're seeing the same on Windows? Are there any conditions under which a root folder which was added will be restored when Atom is exited and restarted as described above?

**Comment by maxbrunsfeld** [comment]
@russlescai You're right; this is a deficiency in Atom's current logic for saving sessions; we save the state every time a window is added, removed, or loses focus, but not while the app is exiting. So if you change the path of an existing window and then quit, we fail to to save. We'll fix this.

**Comment by russlescai** [comment]
awesome, thanks @maxbrunsfeld for the fix, and thanks @izuzak for following up. :)
