### ISSUE TITLE
Atom rendering/cursor position completely broken with ligatures

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#6921]
Lately I have been playing with fonts with ligatures like PragmataPro, Fira Code, Hasklig, etc...

The only way I have found to make Atom to actually render any ligature is by adding `text-rendering: optimizeLegibility` to my style config. Anyways, this completely breaks pretty much the entire editor. Cursor position stops working correctly (a single ligature requires 2 or 3 left/right arrow clicks for the cursor to move back/forwards), the delete key acts really funny, etc...

Even more, after commenting `text-rendering: optimizeLegibility`, Atom keeps doing funny stuff until I restart it.

Those type of fonts are getting more and more common; it would be really nice if Atom could handle them correctly.

Btw, PragmataPro works just fine in Chrome, test it here: http://typecast.com/preview/myfonts/113975  (be sure to add `text-rendering: optimizeLegibility` to the textbox you'll be testing.

**Comment by mnquintana** [comment]
This seems like a possible duplicate of https://github.com/atom/atom/issues/3821 – does that about cover what you're describing?

I think this is the kind of issue it would take https://github.com/atom/atom/issues/6055 to resolve.

**Comment by alexandernst** [comment]
It does sound like the issue I'm getting. I'd say it is the same issue, or a really similar one. In any case, you're right, it seems like #6055 should be fixed.
