### ISSUE TITLE
The update squirrel should not be colored for release notes

### ISSUE THREAD

**Issue by albertorestifo** [atom/atom#6922]
The little squirrel icon that appears when there is an update it's perfect.

But it's coloured even when there is no update but just to point you to the release notes. I find this behaviour confusing.

I think it should act as follows:

- Coloured when there is an update to install
- Gray when it's there to point you to the release notes

**Comment by benogle** [comment]
This makes a lot of sense.

**Comment by albertorestifo** [comment]
It should be a very simple addition, but CoffeeScript gives me headaches :)

**Comment by brendanfalkowski** [comment]
Closed my other issue. The squirrel showing blue after installing updates bugs me too.

I think it only needs the blue state to get you to update (no gray). I'm going to read the release notes when clicking install + restart, so I wouldn't want the icon always present (less UI distraction). You can always access them from the "help" menu.

**Comment by efx** [comment]
+1

**Comment by adambuczynski** [comment]
Agreed with the above, the blue squirrel is distracting when it only points to release notes (which I've already read anyway).

**Comment by bj7** [comment]
Out of curiosity, would this squirrel be in the main Atom repo or would it be under the status-bar repo? I'm guessing the update logic is in the Atom repo, with an interface to update the status-bar? 

I'm curious to try working on this. Thanks!

**Comment by lee-dohm** [comment]
@bj7 Actually, the squirrel icon control is in the [about package](https://github.com/atom/about). But we don't display the release notes in Atom anymore. We link out to the latest release on GitHub in the About view. Ultimately, this Issue has been fixed.

**Comment by bj7** [comment]
Oh ok then. Thank you for the info!

**Comment by lee-dohm** [comment]
@bj7 You're welcome! Sorry to snipe something interesting out from under you. If you need help finding something interesting to contribute with, feel free to message me on the [Atom Slack](http://atom-slack.herokuapp.com/).

**Comment by bj7** [comment]
Ok thanks!

**Comment by Yanpas** [comment]
I'm curious why does atom use squirrel? Does it mean something ? :)

**Comment by lee-dohm** [comment]
@Yanpas From https://www.quora.com/GitHub-What-is-the-significance-of-the-Ship-It-squirrel by @jglovier:

> Shipping is central to the work culture at GitHub. Everything in our workflow is focused around shipping early, and shipping often. We literally deploy http://github.com the website dozens of times a day. Shipping is the point of everything we do. 
>
> We also like to have fun with everything we do, so the Ship It Squirrel is just an extension of that attitude. We use the :shipit: emoji in Pull Request threads to signify support for someone's pull request when we feel it's ready to ship, or in other internal communication to indicate support for getting a feature staff shipped or into production.
