### ISSUE TITLE
Bootstrap upgrade renders Command Palette keybindings white on light UI themes

### ISSUE THREAD

**Issue by p-** [atom/atom#6923]
Since the Bootstrap update with Atom Version 0.201.0 the keybindings displayed in the Command Palette are not readable anymore when using a light UI theme like One Light or Atom Light.

![onelightkeybindings](https://cloud.githubusercontent.com/assets/176818/7784782/33eb840c-0172-11e5-90c9-43073e3c26a7.png)
The new bootstrap now sets a white color for the `kbd` tag.

**Comment by thomasjo** [comment]
Thanks for the report. I'm unsure whether we should move this to the bundled light themes, or leave it here for the time being. 

/cc @simurai

**Comment by lee-dohm** [comment]
Confirmed on both Atom Light and One Light UI using Atom v0.202.0-ec5b807 on Mac OS X 10.10.3.

**Comment by nicolasmccurdy** [comment]
I can confirm this with One Light in safe mode.

**Comment by 50Wliu** [comment]
@nicolasmccurdy this has already been fixed and will be in 0.202.0.
