### ISSUE TITLE
many deprecation replacements not in docs

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#6925]
I've run into several cases where the deprecation notice says to use xyz instead of abc but the api docs still say to use abc.  And zyz will often not be in the docs at all.  Also there are a lot of deprecated things like TextEditorView referenced.

I don't think it's fair to give a deadline for packages to be upgraded to 1.0 when the docs aren't.

**Comment by benogle** [comment]
Can you give us specific examples? We should definitely fix these things.

**Comment by mark-hahn** [comment]
The one that triggered this issue was TextEditorElement.  I'll go back through my recent changes to find others.

**Comment by mark-hahn** [comment]
Now that I go back I see that the ones I've been running into recently are related to the TextEditor.  If you want I can spend more time looking back by going through my repo changes.  I can also add them to this list as I run into new ones. 

- onDidChangeScrollTop
- pixelPositionForScreenPosition

I find them at about the rate of one per project.  So far I've gone through four or five projects.  I know, I shouldn't wait until the last minute.

**Comment by mark-hahn** [comment]
I changed the issue label because I had it backwards.  Most problems are things mentioned in deprecations that aren't documented.  The only reference I can find right now to a deprecation still in the docs is `TextEditorView` at the top of the `TextEditor` page.

**Comment by thomasjo** [comment]
It would be **really** helpful if you could let us know exactly where you find the problems—link to the exact page in the docs (or the source code). Thanks!

**Comment by mnquintana** [comment]
`TextEditorElement` in particular needs to be made public (@nathansobo is it ready to be made public now?)

**Comment by mark-hahn** [comment]
> link to the exact page in the docs

That would be kind of hard since they aren't in the docs.  As for the
source, just do a search.  I'm sorry but I don't have time to do PRs for
docs.  I'm trying to get 21 packages ready for the package apocolypse.

**Comment by mark-hahn** [comment]
What "more information" is needed?

**Comment by nathansobo** [comment]
@mnquintana The `TextEditorElement` can probably be made public at this point. There's one method, `getDefaultCharacterWidth` that needs to be renamed to `getBaseCharacterWidth`. There may be code relying on it though so we could just make it private for now.

**Comment by PBartrina** [comment]
Any news on this?
I am building a package which contains several UI elements and I would love to avoid using deprecated libraries/elements like `atom-space-pen-views`
