### ISSUE TITLE
Sometimes Reload shortcut doesn't work

### ISSUE THREAD

**Issue by vramana** [atom/atom#6927]
I had saw this bug for a while on atom. I was a little lazy to report at that time. Sorry !!  I first saw this issue in the 190 releases series at the least.  I reproduced this on 0.194.0.  by clicking `ctrl-alt-r` multiple times. I saw the console errors appear sometimes only. Here is a screenshot   

![mzz5lmm](https://cloud.githubusercontent.com/assets/3112509/7786854/74427b76-0205-11e5-906f-b3021fc3bd23.png)

Info:
- Ubuntu 14.04
- Atom 0.201.0

I think after atom 0.200.0 I stopped see the console errors. Due this I guess

```
Atom no longer displays error notifications for errors where the stack trace 
cannot be accurately attributed to a package or core source file
```

**Comment by lee-dohm** [comment]
Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by vramana** [comment]
@lee-dohm No `atom --safe` doesn't seem to have this issue... Both on the current version (0.201.0) as well as (0.194.0).

**Comment by thomasjo** [comment]
@vramana That means the problem is caused by one of your installed packages. Can you provide us with a list of installed packages? Just show us the result of executing `apm list --installed --bare`.

**Comment by vramana** [comment]
- atom-alignment@0.12.1
- atom-ternjs@0.6.2
- color-picker@1.7.0
- editor-settings@0.5.3
- editor-stats@0.17.0
- file-icons@1.5.5
- language-babel@0.5.6
- linter@0.12.6
- linter-coffeelint@0.2.3
- linter-eslint@0.5.8
- linter-scss-lint@1.0.4
- script@2.23.0

**Comment by vramana** [comment]
Got it! The problem was with atom-ternjs. It has `ctrl-alt-r` as keyboard shortcut. So, I think we can close this issue.  It is even apparent in the console log error. i didn't check it thoroughly. Wouldn't it be nice for packages developers to get a warning when they use default keyboard shortcuts in their packages?? @lee-dohm @thomasjo Any thoughts ??
