### ISSUE TITLE
Tabs are hidden in split mode

### ISSUE THREAD

**Issue by warpdesign** [atom/atom#6937]
When enough tabs are opened and editor is splitted horizontaly, some tabs may get hidden.

It happens with Atom version 0.201.0 - Windows Build.

![atomtabs](https://cloud.githubusercontent.com/assets/199648/7795547/5be60666-02d6-11e5-96e5-acb3492a91b4.gif)

**Comment by izuzak** [comment]
> When enough tabs are opened and editor is splitted horizontaly, some tabs may get hidden.

Yeah, totally possible. Good news: you can scroll the tab bar to view the "hidden" tabs. Does that help? 

You might also be interested in: https://github.com/atom/tabs/issues/136

**Comment by warpdesign** [comment]
Does this work with current build ? Because this doesn't seem to work on Windows. And there is no hint of the possibility to scroll: no arrow,...

**Comment by izuzak** [comment]
> Does this work with current build ? Because this doesn't seem to work on Windows: I tried the mousewheel when over the tabs, nothing happened.

Works for me on Windows. Have you tried holding down `shift` while scrolling with the mousewheel? The mousewheel scrolls vertically by default, and you need a horizontal scroll.

**Comment by warpdesign** [comment]
It works when holding down shift. But this action really needs some kind of hint.

**Comment by izuzak** [comment]
> It works when holding down shift. But this action really needs some kind of hint.

How would you scroll a webpage (or part of webpage) horizontally with the mousewheel in Chrome? It's the same action.

**Comment by warpdesign** [comment]
When scrolling a webpage, you usually see the scrollbar which indicates you make scroll. Plus if you don't know shift should be used, you may grab the scroll bar.

If there is no scrollbar, there has to be some hint (an arrow ?) that indicates there are more content, and how to access it. The problem is that right now, there is no visual difference between "enough tabs, no need to scroll", and "more tabs, some are hidden".

That's my two cents :)

**Comment by izuzak** [comment]
I'd recommend copy/pasting those two cents over at atom/tabs#136 as well. :) Thanks for explaining.

**Comment by warpdesign** [comment]
Done :) Thanks for listening :)
