### ISSUE TITLE
Resource interpreted as Image but transferred with MIME type text/html

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#6944]
I've been getting annoying messages like this for some time in the dev tools inspector.  I usually get several each reload and then at times like loading settings.

```
Resource interpreted as Image but transferred with MIME type text/html: "file:///root/.config/Atom/Cache/settings-view/-1432574903014".
```

atom 201
ubuntu 14.0.4
apm 0.168.0
npm 2.5.1
node 0.10.35
python 2.7.6
git 1.9.1

**Comment by 50Wliu** [comment]
Refs atom/settings-view#327.

**Comment by mark-hahn** [comment]
This isn't the same as #327.  This is just an annoyance clogging up my inspector.  How can I move this issue to settings-view?

**Comment by 50Wliu** [comment]
@mark-hahn sorry for not clarifying; one of the issues linked there mention something very similar to your report (the only difference being `MIME type text/plain` instead of `/html`).
