### ISSUE TITLE
Crash related to screen change?

### ISSUE THREAD

**Issue by BruceFletcher** [atom/atom#6948]
Software versions:
- Mac OS X 10.10.3
- Atom 0.201.0
- atom-terminal 0.8.0
- build 0.35.0
- language-lua 0.9.3
- term2 0.9.8

Atom crashed on me twice today, and I think there might be some connection to a change in screen size or multi-monitor setup.

I keep Atom running as I carry my laptop around. When I plugged into an external monitor it was fine, until I dragged the window out larger. Atom crashed before it could render the larger window area. Later, I hid Atom, disconnected the external monitor and put the laptop to sleep. Shortly after waking it up I unhid Atom, and it immediately crashed again.

I can't seem to cause a crash by changing resolution on my laptop screen or playing with the window size and don't have an external monitor handy to play with at the moment. I'll play with that a bit if I get the chance tomorrow.

Both crashes had the same thread and exception type:

```
Crashed Thread:        0  CrRendererMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
```

They also had remarkably large "Memory Tag 255" segments; 2.0G and 1.9G respectively. I can provide the full crash reports if that helps.

**Comment by izuzak** [comment]
Thanks for the report, @BruceFletcher. Can you put the full crash report into a gist and link to it here, or just edit your original issue and put the full crash report there?

**Comment by BruceFletcher** [comment]
[First crash](https://gist.github.com/BruceFletcher/b20916956ce0b1bd7615), after waking laptop, attaching to external monitor, and un-hiding Atom.

[Second crash](https://gist.github.com/BruceFletcher/96873be3b96faca69ab9), after waking laptop without external monitor and un-hiding Atom.

and a bonus!

[Third crash](https://gist.github.com/BruceFletcher/7d640b343c19e11d7e92), again after waking laptop without external monitor and un-hiding Atom.

That third one indicates that the external monitor isn't involved, because it was never connected between the times of the 2nd and 3rd crashes. So maybe something about sleep/wake, hiding/un-hiding or moon phases and obscure incantations by unknown actors.
