### ISSUE TITLE
Compatibility with smartgit.

### ISSUE THREAD

**Issue by josemadev** [atom/atom#6951]
When I try pull in smartgit(I think that smagit try delete that y create new one archive when it have changes) and i have atom opened with this archive without saved, atom doesn´t allow permise that. 
(permise denied)

**Comment by lee-dohm** [comment]
I'm not familiar with smartgit. Can you provide a link?

Also, can you provide more detailed repro steps including exactly what you did, what actually happened and what you expected to happen?

**Comment by josemadev** [comment]
not problems now :) i close all tabs before sincro and no problems. i had problems when i not save a file and http://www.syntevo.com/smartgit/ try modify this file. thanks :)
