### ISSUE TITLE
Feature Request: Disable autocomplete in comments

### ISSUE THREAD

**Issue by joshvickerson** [atom/atom#6954]
Comments are generally treated as plaintext. While autocomplete can be helpful in comments at times, at the moment it's really annoying for autocomplete to suggest the word "if" when I want to write "it" in a comment. Occasionally it will suggest the word I want but with different casing. If I hit enter for a new line, autocomplete may select that differently cased word instead of adding a new line as I expect.

Disabling autocomplete in comments seems like a sensible solution to me, but perhaps some discussion is necessary.

![screen shot 2015-05-26 at 10 46 10 am](https://cloud.githubusercontent.com/assets/2325487/7815156/b8722d92-0394-11e5-86d9-78b216a6fe16.png)

**Comment by mnquintana** [comment]
Would you mind moving this to the https://github.com/atom/autocomplete-plus repo?

**Comment by joshvickerson** [comment]
Looks like there's some discussion on this happening there already: https://github.com/atom/autocomplete-plus/issues/377
