### ISSUE TITLE
Don't know what packages are linked with flag --dev

### ISSUE THREAD

**Issue by joseramonc** [atom/atom#6959]
When I start atom with flag `--dev` It correctly shows me the red square that means I'm developing a package.

But I can't find a way through atom to know what packages where loaded for this dev window. 

I was wondering if it's possible to click on the square, and see a list of the developing packages.

**Comment by mnquintana** [comment]
> I was wondering if it's possible to click on the square, and see a list of the developing packages.

That would be pretty nice.

Right now though you can find out what dev packages are being loaded by running `apm links -d`

**Comment by lee-dohm** [comment]
If you go to "Settings View > Packages" the list of packages will have a section for "Development Packages" at the end:

![screen shot 2015-05-26 at 7 08 07 pm](https://cloud.githubusercontent.com/assets/1038121/7827314/a6d300d4-03da-11e5-9af8-f720b44e91fa.png)

That section is there even when you're not in Dev Mode, but it is an indicator of the packages that are configured for development. It is the same information that you would get from `apm links -d` and just as much information as you get from non-development packages that are loaded by Atom.

**Comment by joseramonc** [comment]
@lee-dohm thank you, I never scrolled to the end of the packages list :disappointed:.

**Comment by lee-dohm** [comment]
You're welcome :grinning: Is this sufficient to close the Issue then?

**Comment by joseramonc** [comment]
Yes, I think it's enough. Now I know where I can find my dev-packages.
