### ISSUE TITLE
Where is Atom installed on Windows 8?

### ISSUE THREAD

**Issue by Amakaruk** [atom/atom#6962]
I simply want to make Atom my default IDE, but I can't locate the directory where its installed. Please help. Thanks!

**Comment by paulcbetts** [comment]
`%LocalAppData%\Atom\app-VERSION\atom.exe`

**Comment by Amakaruk** [comment]
Thank you!

**Comment by lee-dohm** [comment]
From your response I believe this answered your question? I'm going to assume so and close this issue. If this doesn't fully answer your question please let us know! :grinning:
