### ISSUE TITLE
Horizontal scrolling 'bedind' the vertical scroll bar

### ISSUE THREAD

**Issue by tinloaf** [atom/atom#6967]
Hi. I experience this behavior:

I start typing and type until I hit the end of my (horizontal) screen space. Now, with the next keystroke, the line should wrap. But instead, I get a horizontal scroll bar and the text editor scrolls to the right as I type, for about 1-2 characters. After that, the line wraps, the editor scrolls all the way back to the left.

I suspect what's happening here is that the text pane does not take into account the space taken up by the horizontal scroll bar and extends 'behind' it. Below you can find a screen shot. The words are 'of' and 'close', so they just fit behind that scroll bar..

![2015-05-27-133332_1920x1200_scrot](https://cloud.githubusercontent.com/assets/442687/7834953/2eb17a5e-0475-11e5-8266-4b305d57c05a.png)

**Comment by 50Wliu** [comment]
Hi @tinloaf, what Atom version is this?  Can you reproduce this in safe mode (`atom --safe`)?

**Comment by tinloaf** [comment]
I'm running 0.202.0-60fbb1d straight from master, but I've had that behaviour for some time now. Interestingly, the behaviour with --safe is a little different: It starts scrolling sideways for a few pixels *before* the right edge is reached and then wraps at what would have been the correct point if it had not scrolled... Let me try to find some software to do a screen cast...

**Comment by 50Wliu** [comment]
@tinloaf Can you still reproduce this on Atom 1.7.3?

**Comment by tinloaf** [comment]
Nope, looking good now!
