### ISSUE TITLE
Some menu commands are no longer working

### ISSUE THREAD

**Issue by izuzak** [atom/atom#6968]
As far as I can tell, the following menu commands are no longer working on latest master (0.202.0-60fbb1d) -- clicking them has no effect:

![screen shot 2015-05-27 at 14 09 45](https://cloud.githubusercontent.com/assets/38924/7835538/13644862-047a-11e5-964a-31e90c61d0ae.png)

Other menu commands seem to be working.

@maxbrunsfeld @kevinsawicki @mostafaeweda: my :8ball: says that https://github.com/atom/atom/pull/6813 _might_ be involved -- the menu commands are working for me at 2953d67, but not working at 8dff5bb (which was merged right after 2953d67).

**Comment by mnquintana** [comment]
Confirmed on Atom 0.202.0-8dff5bb and OS X 10.10.3

**Comment by maxbrunsfeld** [comment]
Thanks @izuzak, @mnquintana!
