### ISSUE TITLE
Uncaught TypeError: Parameter 'url' must be a string, not undefined

### ISSUE THREAD

**Issue by izuzak** [atom/atom#6969]
Steps to reproduce:

1. Hit `cmd-n` to create a new tab with empty text editor.

**Atom Version**: 0.202.0-60fbb1d
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Parameter 'url' must be a string, not undefined

```
At url.js:90

TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:90:11)
    at Object.urlParse [as parse] (url.js:84:5)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:46:30)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:00.6.0 application:new-file (atom-pane.pane.active)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 20,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

cc @maxbrunsfeld @kevinsawicki, in case it's related to https://github.com/atom/atom/issues/6968

**Comment by izuzak** [comment]
Looks related to #6813 again -- working for me at 2953d67, but not working at 8dff5bb (throws this exception). cc @mostafaeweda

**Comment by maxbrunsfeld** [comment]
Thanks for catching this @izuzak!
