### ISSUE TITLE
Node process using 100% of a processor that come from Atom helper

### ISSUE THREAD

**Issue by Uhsac** [atom/atom#6970]
Hi,
I have a problem with Atom, sometimes when I using it my computer starting to be very hot and when I checked the process that run I saw a node process that use 100% of a processor and if I stop this process the temperature of my computer decrease.
I'm running atom v0.201.0 on a MacBook Pro with OS X v10.10.3
I'm using only 2 packages : linter and linter-jshint

I don't know which information I can give to you so I will put everything I have here.
![atom_node](https://cloud.githubusercontent.com/assets/6172122/7836297/79bbb3ac-047f-11e5-9202-3633ddb99639.png)
![sans titre](https://cloud.githubusercontent.com/assets/6172122/7836342/c42ab9c4-047f-11e5-8129-abb7d130d025.png)

I did a profiling using the dev tools, you can find it here : https://transfer.sh/AVosQ/atom.cpuprofile

If I can do anything else to help ask me and I help respond as fast as I can.

**Comment by benogle** [comment]
If you disable the linters does it still happen? Try `atom --safe`

**Comment by Uhsac** [comment]
The problem come from linter-jshint I think. Other person have the same issue : AtomLinter/linter-jshint#95
