### ISSUE TITLE
Atom's "Generate Syntax Theme" not working (even after reading docs)

### ISSUE THREAD

**Issue by DonaldKellett** [atom/atom#6972]
Hello,

I was just studying how to create a custom theme by reading https://atom.io/docs/v0.201.0/hacking-atom-creating-a-theme because I wanted to try out my own theme.

However, when I followed the instructions, it did not seem to work as expected.

At first, I pressed `cmd-shift-P` as stated in the docs and searched for "Generate Syntax Theme":

![screen shot 2015-05-27 at 11 13 46 pm](https://cloud.githubusercontent.com/assets/7777884/7839778/d726d0d4-04c6-11e5-8ef4-5f9524c36f42.png)

I then pressed "Enter", so it asked me to enter the path file:

![screen shot 2015-05-27 at 11 14 00 pm](https://cloud.githubusercontent.com/assets/7777884/7839810/fd517476-04c6-11e5-8c28-6d9f41013191.png)

However, after I entered the path, I could not find a way to submit the path (I tried pressing the "Enter" button, but it did not work) and when I clicked somewhere else, it just disappeared and I had to do it all over again.  Can someone please tell me what button I should press after I enter the file path to start generating the theme?

Thank you very much!

Yours sincerely,
DonaldKellett (Donald at Kellett)

**Comment by izuzak** [comment]
@DonaldKellett Pressing `enter` should work -- I just tried it on OSX and it worked for me. Can you provide a bit more [information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) and check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?

**Comment by DonaldKellett** [comment]
I haven't upgraded to Mac OSX *Yosemite* yet.  Does that matter?

And if I type an invalid path, will it still allow me to create a theme after I press ```enter``` (although I'm fairly certain I have typed in a valid path)?

Thank you very much.

DonaldKellett

**Comment by izuzak** [comment]
> I haven't upgraded to Mac OSX Yosemite yet. Does that matter?

I don't know -- I don't have a machine with Mavericks to confirm.

> And if I type an invalid path, will it still allow me to create a theme after I press enter (although I'm fairly certain I have typed in a valid path)?

What kind of invalid path do you have in mind? That path you entered looks valid to me.

Does pressing enter work in other similar panels, e.g. when you try to add a file in the tree view? (Open a folder with Atom, then in the tree view select a file, right click it, and select "New File". You'll be shown a similar panel to enter the file's name.)

Do you see any errors in the devtools console?

**Comment by DonaldKellett** [comment]
Sorry, I don't know (I'm quite new to Atom, but I read the first 2 main sections of the Atom Documentation and I think I understand most of the content).

Do I have to create an empty file beforehand, or does Atom help me generate the file when I enter the path?

For example, should I create a folder named ```motif-syntax``` on my Desktop before I generate a theme and type in the file path /Users/<username>/Desktop/motif-syntax or should I simply type in that path to create the theme?  Anyway, either way (I tried both ways already), it doesn't seem to work and I'm certain I have all Core packages enabled.

Thank you very much!

Yours sincerely,
DonaldKellett [Donald Leung (Kellett)]

**Comment by Huaraz2** [comment]
Open up the .atom folder in atom in dev mode then try again, this is how I
made mine.

Only thing I don't know how to do is how I go about publishing it.

Hope this helps

**Comment by izuzak** [comment]
> Do I have to create an empty file beforehand, or does Atom help me generate the file when I enter the path?

@DonaldKellett You shouldn't need to create anything yourself. 

Can you answer the two questions I asked in a previous comment? Here they are again:

> Does pressing enter work in other similar panels, e.g. when you try to add a file in the tree view? (Open a folder with Atom, then in the tree view select a file, right click it, and select "New File". You'll be shown a similar panel to enter the file's name.)

> Do you see any errors in the devtools console?

Also, can you try generating a package instead of a theme and see if that works? (Using the "Generate package" command).

Thanks for the help in investigating this.

**Comment by izuzak** [comment]
> Only thing I don't know how to do is how I go about publishing it.

@Huaraz2 You need to use the [apm publish](https://github.com/atom/apm#using) command for that.
