### ISSUE TITLE
Atom editor crashes with external change to network share

### ISSUE THREAD

**Issue by Arcanemagus** [atom/atom#6974]
It seems that Atom.io has issues with monitoring network shares on Windows. When an external change is made to the directory structure (new / deleted file) Atom's editor crashes.

OS: Windows 7 x64 Enterprise
Atom: 0.201.0

Running atom with the --safe option still exhibits this behavior.
No errors are logged to the console, although it is still responsive.

![image](https://cloud.githubusercontent.com/assets/427137/7841940/d50017b0-0454-11e5-8405-3bd6ca194e9e.png)

Clicking Reload on the dialog makes the editor work perfectly fine, until another change is made to the directory :wink:.

A Process Monitor log of the application while crashing, as well as Atom's .dmp output can be found here:
https://drive.google.com/folderview?id=0BwNHIQX2XG-lfmNmY2s5aDdvY2RVblpCa2k4WjlqRDRXYTNrbzFOdXphb2cyYnZETl9XRW8&usp=sharing

Occasionally Atom will not crash, but when this happens it seems it is no longer monitoring the network share as changes are not shown in the tree and new files created within Atom do not even show up in the tree.

If there is any further debugging information or steps you would like me to take please let me know.

**Comment by patrickurban** [comment]
I have the same problem and I looked a little bit more into it, I hope this information helps (and is relevant):

OS: Windows 7 x64 Enterprise
Atom: 1.0.7

Activating 'Pause On Caught Expression' catches an error while trying to save the file 'some.txt' in Z:\some\folder (Z:\ is a network share):

> \<exception>: Error: EEXIST: file already exists, mkdir 'Z:\some\folder'
> code: "EEXIST"
> errno: -4075
> message: "EEXIST: file already exists, mkdir 'Z:\some\folder'"
> path: "Z:\some\folder"
> stack: (...)
> \> get stack: function () { [native code] }
> \> set stack: function () { [native code] }
> syscall: "mkdir"

and the call stack at this point is:

> fs.mkdirSync (fs.js:791)
> sync (…us\node_mo…:55)
> fsPlus.writeFileSync (…s\lib\fs-…:278)
> module.exports.File.writeFileSync (…tcher\lib…:273)
> module.exports.File.writeFileWithPrivilegeEscalationSync (…tcher\lib…:371)
> module.exports.File.writeSync (…tcher\lib…:345)
> module.exports.TextBuffer.saveAs (…ffer\lib…:1011)
> module.exports.TextBuffer.save (…uffer\lib…:992)
> module.exports.TextEditor.save (…-editor.js:579)
> module.exports.Pane.saveItem (…rc\pane.js:539)
> module.exports.Pane.saveActiveItem (…rc\pane.js:522)
> module.exports.Workspace.saveActivePaneItem (…rkspace.js:609)
> atom.commands.add.core:save (…element.js:293)
> module.exports.CommandRegistry.handleCommandEvent (…egistry.js:241)
> (anonymous function) (…-registry.js:3)
> module.exports.KeymapManager.dispatchCommandEvent (…eymap\lib…:524)
> module.exports.KeymapManager.handleKeyboardEvent (…eymap\lib…:347)
> module.exports.WindowEventHandler.onKeydown (…handler.js:177)

It seems like the error should be caught in the path-watcher module at writeFileWithPrivilegeEscalationSync but is not processed and therefore thrown again.

Please let me know if you need any more information!

**Comment by irishxpride** [comment]
Having the same issue occurs with or without the --safe flag.

OS: Windows 7 x64 Enterprise
Atom: 1.0.11

what information can I provide to assist?

**Comment by cliberatore** [comment]
I'm getting precisely the same thing on my work machine. Windows 7 x64 Enterprise, Atom 1.0.11. Editor crashes when saving to a mapped network drive.

**Comment by Arcanemagus** [comment]
@patrickurban @irishxpride @cliberatore Although the root cause is probably in the same area, this isn't an issue about saving files on a network share, but rather changes to the contents of the share external to Atom causing Atom to crash. (Like creating a new file in your file browser.)

Since #8355 mentioned that there is different behaviour based on the server of the share (works on Windows and "Linux", crashes on OS X Samba share), I feel I should mention that this happens on a Dell Compellent backed share. I'm pretty sure I noticed this on my FreeNAS backed share at home as well, but can test again if needed.

I have absolutely no experience with the core Atom code so I'm not even sure where to look to try to debug this further myself :disappointed:.

**Comment by irishxpride** [comment]
I believe this may yet be related. Atom does not crash the first time I save a newly created file, only when i save changes to an existing file. I did not think to test this until your comment.

**Comment by patrickurban** [comment]
@Arcanemagus I think you are right. Atom doesn't actually crash on the caught expression (at least not immediately).
I also found an interesting bit of information in the node.js documentation (more precisely in the [documentation for the fs module](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener)):

> The `fs.watch` API is not 100% consistent across platforms, and is unavailable in some situations.
> (...)
> On Windows systems, this feature depends on `ReadDirectoryChangesW.`
>
> If the underlying functionality is not available for some reason, then fs.watch will not be able to function. For example, watching files or directories on network file systems (NFS, SMB, etc.) often doesn't work reliably or at all.

node-pathwatcher seems to do similar things (see [here](https://github.com/atom/node-pathwatcher/blob/0e1b0da85b3a0bb18f2ab6e59f02d3cdc9dcf9e6/src/pathwatcher_win.cc#L82))
If that is the case, then this is probably hard to fix.

There is a mention in node's fs api to use `fs.watchfile` instead of `fs.watch`, since it doesn't use platform-specific tools, but there seem to be some drawbacks as well and I would guess it would be hard to change anyway. :disappointed:

**Comment by leftdevel** [comment]
Happening to me on Mac OSX (Yosemite) + vagrant box. I can't even open a file. No matter what, Atom will crash :(

**Comment by lafener** [comment]
Always crash when I try to open a file in the network share.

**Comment by Arcanemagus** [comment]
@leftdevel @lafener although the code causing the issues are probably related, it doesn't sound like you are seeing the same thing. This issue is about an external program editing a file on a network share that is already open in Atom, which causes it to crash on Windows.

**Comment by stewhouston** [comment]
Happening to me while using a shared/mounted directory on a local linux VM. It crashes about once every 15 minutes, always when clicking or editing in the file tree.

**Comment by cloim** [comment]
Happening to me on Mac OS X (El Capitan) SMB + Windows 10 Network Drive Share. When I change OS X's folders or files, It's crash on windows. Reload Dialog is show up, But, It's not work sometimes. So, I just close Atom and relaunch.

**Comment by Arcanemagus** [comment]
@cloim What version of Atom are you using? I just tried to reproduce on v1.6.0-beta5 and was unable to.

**Comment by stewhouston** [comment]
Just wanted to chime in; not sure if there have been any patches released recently or something small has changed on my end, but the editor has been completely stable for the past few weeks. (Windows fs share on a Ubuntu VM.)

**Comment by cloim** [comment]
@Arcanemagus It's 1.5.3

**Comment by stelcheck** [comment]
Same for me, Windows 10 mounting an OS X shared samba. Additionally, I noticed that trying to delete files from the explorer would fail, which I assume must have something to do with the current issue.

**Comment by Makeshift** [comment]
Still an active problem for me running Win10 x64, atom 1.6.2 with a samba share from an ubuntu host. It most obviously crashes when I change network (and the share swaps into offline mode) but also seems to crash when Windows is trying to back up that location.

**Comment by CarraJack** [comment]
Same problem for me. I'm running Atom 1.6.2 on Windows10 and Yosemite OSX on the server. I use an ssh connection between client and server. When I change something in my file browser, Atom crashes and I have always to reload it. Then it works fine until I made a new change.

**Comment by barchstien** [comment]
same for me Atom 1.7.2, often crashes, or does not load changes done outside Atom for network mounted folders. Loading very short documents takes also a long time
Using Ubuntu 16.04, folder mounted is on a Ubuntu 14.04 machine

**Comment by parhs** [comment]
Using latest I cant even open . Before had issues with files not updating but I could work. Now nothing

**Comment by matjam** [comment]
1.14.3 still crashing. Windows 10 mounting OS X smb share.

**Comment by maxwellsmart84** [comment]
This is still happening to me as well - I am sharing the file on macOS 10.12.3 and accessing over SMB from Windows 10

**Comment by matjam** [comment]
The only workaround that works for me is to disable the git plugin in Atom. Seems to help.

**Comment by marthongt** [comment]
kinda similar issue here
Windows 10 Enterprise accessing files on Novell share with atom 1.16.0

The odd part is that I can open a file amend it and if I try to save the changes with the shortcut (ctrl+s) than atom is crashing. But if I save the file by clicking on File > Save or even Save As... than it works.

I do use additional atom packages and none them have been disabled
sadly ctrl+s is muscle memory for me so it's more like an annoyance and not an issue

**Comment by Arcanemagus** [comment]
Closing this issue as I can no longer reproduce this. If anyone is seeing similar behavior please file a **new** issue, and include which filesystem watcher you are using in Atom when filing the issue, thanks!
