### ISSUE TITLE
removing keybinding via 'unset!' doesn't stop key sequence lookup

### ISSUE THREAD

**Issue by yejianye** [atom/atom#6975]
It's probably easier to explain this issue by an example. 

I have term2 plugin installed, so by default, the following keys are binded.
- ctrl-k t up
- ctrl-k t down
- ctrl-k t left
- ctrl-k t right
- ctrl-k t t

And I've binded `ctrl-k` key to a user-defined command. When I enter `ctrl-k`, there will be delay before the command gets exectued. I believe that's because atom is waiting for the next key. If I disable term2 plugin, the command will get executed right away.

Since I still want to use term2, in my `keymaps.cson`, I added the following section
```
'atom-text-editor':
    'ctrl-k t down': 'unset!'
    'ctrl-k t up': 'unset!'
    'ctrl-k t left': 'unset!'
    'ctrl-k t right': 'unset!'
    'ctrl-k t t': 'unset!'
```
After reload, I now see all keybindings for term2 are unset and there's no keymap prefix with `ctrl-k`, but I still get lag when entering `ctrl-k`. 

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3

**Comment by aki77** [comment]
I have the same problem.
I implemented a [package](https://atom.io/packages/disable-keybindings).

**Comment by izuzak** [comment]
Thanks for the feedback, @yejianye.

> After reload, I now see all keybindings for term2 are unset and there's no keymap prefix with ctrl-k, but I still get lag when entering ctrl-k.

Yeah, I think there's already an open issue to improve this situation, see: https://github.com/atom/atom-keymap/issues/78. I'm going to close this in favor of that issue but let me know if I misunderstood.
