### ISSUE TITLE
Can't find gitignored files even when 'Exclude VCS Ignored Paths' is unchecked

### ISSUE THREAD

**Issue by robbyemmert** [atom/atom#6980]
Any gitignored files don't show up in the file tree.

**Comment by robbyemmert** [comment]
Found the issue.  The file tree has it's own setting as explained here: https://github.com/atom/atom/issues/5423.

Can you phrase the 'Exclude VCS Ignored Paths' setting differently to be more explicit about what those paths will be excluded from? 

Example:
'Exclude VCS Ignored Paths From Search Index'.  That way people don't expect it to apply to the file tree as well.

Thanks!

**Comment by hypnoboutique** [comment]
I agree; it's very confusing!

#8276 gets to the crux of the issue (that it's a design fault), so maybe worth closing this and continuing there.

**Comment by 50Wliu** [comment]
Thanks @hypnoboutique.
