### ISSUE TITLE
Atom terribly slow after .202

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#6981]
I got the last update (.202, Linux) and something is terribly broken. Atom never shined for it's speed, but it got completely slow after the last update.

Just scrolling (with `--safe`) on a ~8.000 lines CSS file hits the 100% usage of 1 of the cores of my CPU. Also, memory usage keeps increasing after every ~500 scrolled lines.

**Comment by 50Wliu** [comment]
Does this happen with every file?

/cc @nathansobo

**Comment by alexandernst** [comment]
Also, doing that same thing without `--safe`, with the minimap, feels completely laggy and memory usage gets even bigger.

All this is on  Debian 8, x64, 64gb RAM, 8 cores CPU@3,7Ghz.

Answering your question: Yes, this happens with all files bigger than ~1500 lines (fast scrolling). Even with a composer.lock file that didn't even got color-highlighted (plain-text was selected, instead of JSON)

**Comment by nathansobo** [comment]
Would you be willing to capture a CPU profile and/or share the file in question?

**Comment by alexandernst** [comment]
@nathansobo Sure, I can do both things, just tell me how

**Comment by nathansobo** [comment]
@alexandernst To capture a CPU profile, open the dev tools with `ctrl-alt-i` or `View > Developer > Toggle Dev Tools`. Then go to the `Profiles` tab. With `Collect JavaScript CPU Profile` selected, click start. Then do your scrolling. It will be even slower now because we're measuring. Then click stop. You should now see the profile appear at the left and you can save it.

Email that and the file in question to me at `nathan@github.com`. Not sure if I'll be able to reproduce but I can at least see if we're doing something crazy CPU wise on the UI thread.

**Comment by nathansobo** [comment]
Another thing you could capture is a timeline of scrolling. After capturing it you can right click and choose `Save Timeline Data...`.

**Comment by alexandernst** [comment]
There seems to be a bug with Chrome. When I try to save the timeline or the cpu profile record, I get the "Save as..." dialog, I select the file/folder where I want the files to be saved, the files get created, but they're empty. (I'm running Atom with `--safe`, should I run it in normal mode?)

**Comment by nathansobo** [comment]
No, that must be an issue with Electron on Linux because it works for me on Mac. Any interesting pieces of the timeline you could at least screenshot?

**Comment by alexandernst** [comment]
http://ibin.co/23E0PfdEGeYl

**Comment by nathansobo** [comment]
@alexandernst Thanks... can you switch to the "Chart" view and show me one frame's worth?

**Comment by alexandernst** [comment]
Not sure if that is what you're asking for: http://ibin.co/23E1wtfuS7f2 ?

**Comment by nathansobo** [comment]
That looks pretty bad, but I'll need it from the profile tab rather than the timeline to get more detail on what is happening...

![screenshot_2015-05-28_02_26_41](https://cloud.githubusercontent.com/assets/1789/7850332/12ffd640-04e1-11e5-9038-098c75730286.png)

**Comment by nathansobo** [comment]
Also, I'd be interested in a comparison of the timeline on 0.202.0 with 0.201.0. From the timeline performance doesn't look *fantastic* but it also doesn't seem too bad except for a couple of frames. Like roughly 30 FPS for the most part. But it's all relative depending on hardware. I'm curious about the performance *degrading* from the previous release and it would be nice to see a picture of that happening.

**Comment by alexandernst** [comment]
http://ibin.co/23E4NhMAR1zy

**Comment by alexandernst** [comment]
Ok, I can provide you with screenshots of .201 later today, I must go now.

**Comment by nathansobo** [comment]
Thanks very much for your time! It's tough to get a handle on some of these performance issues from a distance so this kind of information really helps.

**Comment by alexandernst** [comment]
I switched back to .201 and after some more tests, I must say that *on numbers* .202 is better than .201. Both the CPU usage and the memory usage in .202 is (a tinny bit) lower. Nevertheless .202 feels slower. It may be because something is blocking the UI for more time, perhaps.

**Comment by nathansobo** [comment]
Are there any outlier frames, perhaps where we're doing garbage collection, where 0.202 is worse?

**Comment by nathansobo** [comment]
Also, is it just scrolling, or other things too?

**Comment by alexandernst** [comment]
Have a look at this: http://ibin.co/23GKK7u3mDhA
Atom (.201) is spending considerably less time "Scripting"

**Comment by alexandernst** [comment]
Also, overall, .201 is rendering 99% of the frames at 60FPS, while .202 is having trouble keeping the FPS on 30.

More tips: I have the [Logitech MX](http://www.logitech.com/assets/19678/19678.png) and I'm scrolling with the scroll wheel while unlocked (the scroll wheel doesn't make the "click" noise)

**Comment by nathansobo** [comment]
Seems we are spending a *bit* more time building the lines up in my tests. Here's a 2 second summary of 0.201 scrolling hard in huge.js:

![screenshot 2015-05-28 21 58 18](https://cloud.githubusercontent.com/assets/1789/7869709/d43a5f4e-0584-11e5-8e4c-f7a350058abd.png)

Here's a 2 second summary from master:

![screenshot 2015-05-28 21 58 25](https://cloud.githubusercontent.com/assets/1789/7869720/f2086354-0584-11e5-9db9-88fbebabe0b5.png)

Strange thing is there's *more* total time *idle* in the new implementation. I believe you that it feels slower, but I'm having trouble reproducing it. There's a PR that will land very soon that should boost scrolling paint performance that may make this better again. Perhaps we can pick this up once that lands next week.

**Comment by alexandernst** [comment]
Ok, I'll keep an eye on Atom updates and keep posting my findings here. Ping me when the patch is merged and released, please :)

**Comment by nathansobo** [comment]
Also, the more detailed information you can give me on what's slow based on these profiles, the better I'll be able to address it. I realize it's a time suck though. Thanks for your time!

**Comment by alexandernst** [comment]
Can you give me some general tips about what exactly should I be looking for? Can you show me a screenshot of a profile dump with a function that is *slow*?

**Comment by nathansobo** [comment]
It's all relative really. In your case we're taking too long to generate a frame when scrolling. So you perform scrolling and then take a look at that frame. Maybe do that in 0.201 and latest and compare them. How do they look different? Is there something that's taking way longer in one frame than the other.  Here's an example of me zoomed in on a frame. Compared with the version where it was faster, is anything worse? Not sure how realistic a path this is without me being able to look directly, but if I can get a good view of something clearly taking way longer, it could help. We need to get snapshot saving fixed on Linux.

![screenshot 2015-05-28 23 32 12](https://cloud.githubusercontent.com/assets/1789/7871686/c88d5ffe-0591-11e5-8811-2af148bb974d.png)

**Comment by as-cii** [comment]
@alexandernst: do you still notice significant lags while scrolling or #6733 did by any chance help with this issue? Also, #7101 is going to further improve performance, so you may want to have a look at that as well.

Any information or update on this would be very welcome: thank you! :bow:

**Comment by alexandernst** [comment]
@as-cii I'm waiting for a new release to test the changes. Will report as soon as a new release is available.

**Comment by alexandernst** [comment]
I'm closing this as this got fixed somewhere between .203 and .208
