### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by dxue2012** [atom/atom#6982]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.202.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-line.js:89

TypeError: Cannot read property '0' of undefined
    at TokenizedLine.module.exports.TokenizedLine.transformContent (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-line.js:89:38)
    at new TokenizedLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-line.js:71:12)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:521:14)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:506:19)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:286:43)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:263:26
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-glsl",
      "autocomplete-glsl",
      "symbols-view",
      "symbols-tree-view",
      "theme-switcher",
      "atom-typescript-tools",
      "language-typescript",
      "atom-django",
      "script",
      "linter-tslint",
      "minimap-highlight-selected",
      "minimap"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-ctags, v3.2.0
atom-html-preview, v0.1.6
atom-ternjs, v0.6.3
atom-typescript, v4.5.2
autoclose-html, v0.17.0
autocomplete-paths, v1.0.2
color-picker, v1.7.0
git-log, v0.3.0
git-projects, v1.13.0
highlight-selected, v0.9.1
less-autocompile, v1.0.0
linter, v0.12.6
linter-less, v0.4.0
save-session, v0.15.3
vim-mode, v0.49.0
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by basarat** [comment]
I believe my custom grammar stuff for `atom-typescript` is the issue. Investigating. 

@dxue2012 did you have a `.ts` file open by chance?

**Comment by dxue2012** [comment]
@basarat Yes I did. 

In fact I don't recall this issue being present before I updated `atom-typescript` to `v4.5.2`. Thank you for investigating!

**Comment by basarat** [comment]
> before I updated atom-typescript to v4.5.2

Worth mentioning: its not atom-typescript that's changed. Its atom that's changed that broken this < not blaming ... just pointing the path of investigation for those interested :rose:

**Comment by basarat** [comment]
Its because of addition of `tags`. Still going through the code. For anybody interested this is my code : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/typescriptGrammar.ts#L181-L227 

Tags where added to firstmate  : https://github.com/atom/first-mate/blob/94604652a81cfebb5eae57e7d7c666905912f19f/src/grammar.coffee#L93-L96 

Investigating what I should be returning (and functions I should be calling) from my custom `tokenizeLine`.

**Comment by nathansobo** [comment]
@basarat So you're constructing `TokenizedLines` on your own?

**Comment by basarat** [comment]
@nathansobo yes

**Comment by basarat** [comment]
@nathansobo by overriding `tokenizeLine` : https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atom/typescriptGrammar.ts#L38-L85

**Comment by nathansobo** [comment]
Ah yes, I see now. I describe the new encoding here: https://github.com/atom/atom/pull/6757

It's for memory savings purposes. Basically I'm interleaving scope starts/stops (represented by negative integers) with positive integers representing tokens (by their length). You'll need to interact with methods on the grammar registry to translate scopes to numeric ids, but it should be doable.

**Comment by basarat** [comment]
@nathansobo cool. That helps a lot. I'll make a hotfix to move back to `cson` driven grammar so people can still use and investigate the rest later tonight :rose:

**Comment by basarat** [comment]
Thanks for the guidance. Published `atom-typescript`:`v4.5.3` with hotfix :rose:

FWIW the other package I know that uses similar custom grammar code is by @p-e-w https://github.com/p-e-w/language-javascript-semantic

**Comment by JonathanMEdwards** [comment]
I'm getting same trap on .ts files with with atom 0.204.0 and atom-typescript 4.5.5

**Comment by nathansobo** [comment]
@basarat you shouldn't be overriding the grammar in this new version right? Hard to explain how this error could happen otherwise. @JonathanMEdwards are you sure you're upgraded? You may need to reload your editor as we don't yet reload code properly after upgrades due to module caching issues.

**Comment by JonathanMEdwards** [comment]
Duh - yeah restart fixes.

**Comment by nathansobo** [comment]
It's not obvious a restart should be required and we need to fix it, but yeah, glad it worked.

**Comment by nathansobo** [comment]
Going to close this out as it's a package erroring on a private API. I definitely wouldn't discourage this kind of hacking but also can't guarantee things won't break. @basarat I'd love to see you keep experimenting with this approach. It might inform how we could give you a better official interface to hook into your own parser someday.

**Comment by wcandillon** [comment]
@nathansobo I appear to have the same issue in my plugin. What is the private API that causes this issue? Here's my plugin: https://github.com/wcandillon/language-jsoniq/blob/master/lib/jsoniq-grammar.js

**Comment by wcandillon** [comment]
@nathansobo my `tokenizeLine` implementation used to return the following format:
```json
[
  {
    "start": "source.jq"
  },
  {
    "value": "import module namespace",
    "scopes": [
      "source.jq.keyword"
    ],
    "bufferDelta": 23,
    "firstNonWhitespaceIndex": null,
    "firstTrailingWhitespaceIndex": null,
    "screenDelta": 23
  },
  {
    "value": " ",
    "scopes": [
      "source.jq.text"
    ],
    "bufferDelta": 1,
    "firstNonWhitespaceIndex": null,
    "firstTrailingWhitespaceIndex": null,
    "screenDelta": 1
  },
  {
    "value": "xmldb",
    "scopes": [
      "source.jq.text"
    ],
    "bufferDelta": 5,
    "firstNonWhitespaceIndex": null,
    "firstTrailingWhitespaceIndex": null,
    "screenDelta": 5
  },
  {
    "value": "=",
    "scopes": [
      "source.jq.keyword.operator"
    ],
    "bufferDelta": 1,
    "firstNonWhitespaceIndex": null,
    "firstTrailingWhitespaceIndex": null,
    "screenDelta": 1
  },
  {
    "value": "\"",
    "scopes": [
      "source.jq.string"
    ],
    "bufferDelta": 1,
    "firstNonWhitespaceIndex": null,
    "firstTrailingWhitespaceIndex": null,
    "screenDelta": 1
  },
  {
    "value": "http://28.io/modules/exist-db",
    "scopes": [
      "source.jq.string"
    ],
    "bufferDelta": 29,
    "firstNonWhitespaceIndex": null,
    "firstTrailingWhitespaceIndex": null,
    "screenDelta": 29
  },
  {
    "value": "\"",
    "scopes": [
      "source.jq.string"
    ],
    "bufferDelta": 1,
    "firstNonWhitespaceIndex": null,
    "firstTrailingWhitespaceIndex": null,
    "screenDelta": 1
  },
  {
    "value": ";",
    "scopes": [
      "source.jq.text"
    ],
    "bufferDelta": 1,
    "firstNonWhitespaceIndex": null,
    "firstTrailingWhitespaceIndex": null,
    "screenDelta": 1
  },
  {
    "value": "",
    "scopes": [
      "source.jq"
    ],
    "bufferDelta": 0,
    "firstNonWhitespaceIndex": null,
    "firstTrailingWhitespaceIndex": null,
    "screenDelta": 0
  }
]
```

I modified the implementation to return the following:
```json
[
  {
    "start": "source.jq"
  },
  {
    "start": "keyword"
  },
  "import module namespace",
  {
    "end": "keyword"
  },
  {
    "start": "text"
  },
  " ",
  {
    "end": "text"
  },
  {
    "start": "text"
  },
  "xmldb",
  {
    "end": "text"
  },
  {
    "start": "keyword.operator"
  },
  "=",
  {
    "end": "keyword.operator"
  },
  {
    "start": "string"
  },
  "\"",
  {
    "end": "string"
  },
  {
    "start": "string"
  },
  "http://28.io/modules/exist-db",
  {
    "end": "string"
  },
  {
    "start": "string"
  },
  "\"",
  {
    "end": "string"
  },
  {
    "start": "text"
  },
  ";",
  {
    "end": "text"
  }
]
```
Does this new output format look good? It doesn't appear to work.

**Comment by nathansobo** [comment]
You're on the right track. Read lower in that explanation and you'll find the true format that more efficiently represent the same concept, with integers. It's pretty cryptic but the other representations ate too much memory.

**Comment by basarat** [comment]
@wcandillon tip (not related to the issue though) ... no need to override `tokenizeLine**s**` as the default implementation is similar to what you came up with : https://github.com/atom/first-mate/blob/1c2b006ed2bf119f2662e87f64a3b21beca481e9/src/grammar.coffee#L73-L80 (as far as I can see).

**Comment by michaelkrog** [comment]
+1

**Comment by nathansobo** [comment]
May I ask why you're +1-ing this issue? The author has fixed the problem in a subsequent release. If you upgrade and reload Atom, the issue should disappear.

**Comment by p-e-w** [comment]
@basarat, @wcandillon: With some key hints from @nathansobo in https://github.com/atom/atom/issues/7124, I managed to port my package [language-javascript-semantic](https://github.com/p-e-w/language-javascript-semantic) to the new format and it now features a working CoffeeScript-provided grammar again. The relevant code is [here](https://github.com/p-e-w/language-javascript-semantic/blob/master/lib/javascript-semantic-grammar.coffee#L92).

**Comment by basarat** [comment]
@p-e-w thanks a lot. Stable link for when I get the time : https://github.com/p-e-w/language-javascript-semantic/blob/b7b61524b0c9cf27fb978a5021da723b4c3a0ea3/lib/javascript-semantic-grammar.coffee#L92
