### ISSUE TITLE
Feature Request: Add a method to the API to switch the active project

### ISSUE THREAD

**Issue by mehcode** [atom/atom#6984]
```
atom.project.replace(["path", "path"])
```

Something similar to the above. 

Here is what I have hacked together:
https://github.com/mehcode/atom-git-projects/blob/master/lib/git-projects.coffee#L93-L140

**Comment by mehcode** [comment]
For anyone that is interested in this -- I've put together a package that implements this with correct behavior.
https://github.com/mehcode/atom-project-plus

**Comment by Fire-Dragon-DoL** [comment]
@mehcode **Thanks** I was waiting for something like that since ages... finally I'll be able to use Atom!
