### ISSUE TITLE
env: bash: No such file or directory on Mac

### ISSUE THREAD

**Issue by DavidAwad** [atom/atom#6985]
atom keeps telling me it can't update itself or find new packages. 

The error I keep getting is `env: bash: No such file or directory`.  

I'm not sure what the problem actually is. I've used brew to install nodejs. 
```sh
➜  ~  brew install node
Warning: node-0.10.36 already installed
➜  ~  which node
/usr/local/bin/node
```

**Comment by erwald** [comment]
Yes, I have the same problem. Used to work just fine, but some days ago I suddenly started getting this error. Also with version 0.202.0.

**Comment by izuzak** [comment]
@DavidAwad @erwald Which OS are you on? Does the problem happen in Atom 0.204.0 as well? Does it happen in an older version (e.g. 0.198.0)? You mentioned that this started happening recently, so I'm wondering if you could help us figure out which is the last version that worked for you.

**Comment by mnquintana** [comment]
This seems like it could be related to https://github.com/atom/atom/pull/6735 – it's kind of strange though that bash isn't in your PATH. Can you try running `env bash` just to confirm?

**Comment by erwald** [comment]
@izuzak I'm on Yosemite, 10.10.3. I just tried updating to 0.204.0 and still the same problem. The problem started before I updated to 0.202.0, too. As I recall it, it didn't start with a new update, but I cannot be absolutely sure of that.

@mnquintana What, in the Terminal? There, `env bash` works just fine. Or do you mean in within Atom somehow?

I have also tried opening Atom from the Terminal, but still the same problem.

**Comment by izuzak** [comment]
@erwald Thanks. Does the problem happen in v0.198.0? You can download it here: https://github.com/atom/atom/releases

**Comment by erwald** [comment]
@izuzak In 0.198.0 the problem doesn't appear.

**Comment by mnquintana** [comment]
@erwald Can you try running `/usr/bin/env bash` in the Terminal?

**Comment by erwald** [comment]
@mnquintana Works just fine.

**Comment by izuzak** [comment]
@mnquintana Since the PR you linked to was introduced in 0.199.0, this makes me think that you're right about that PR causing problems here.

**Comment by mnquintana** [comment]
@izuzak Do you have any ideas why it would be? I'm sort of baffled since both `env` and `bash` are on @erwald's `PATH` here.

**Comment by izuzak** [comment]
@mnquintana No sure, but I do remember some other problems with similar "keywords", e.g. https://github.com/atom/atom/issues/6956, https://github.com/atom/atom/issues/3018

**Comment by mnquintana** [comment]
@erwald Do you get this error only if you launch Atom from the dock / Finder? Or do you also get it if you launch Atom from the command line?

**Comment by erwald** [comment]
@mnquintana As I mentioned above, the problem remains when launching Atom from the command line.

**Comment by mnquintana** [comment]
@erwald Is `env: bash: No such file or directory` the full error? Or is there more?

**Comment by erwald** [comment]
@mnquintana Yes. In Updates, I get the following:

```
Fetching outdated packages and themes failed. Hide output…

env: bash: No such file or directory
```

And when trying to search something in Install:

```
Searching for “test” failed. Hide output…

env: bash: No such file or directory
```

**Comment by DavidAwad** [comment]
Didn't see this until now, I'm using a MacBook Air, newest OSX, but I'm using Zsh with Oh My Zsh. 

Might be a shell problem for me but it doesn't seem like it as it was this last update that broke atom for me.

**Comment by mnquintana** [comment]
@erwald @DavidAwad Can you open the DevTools in Atom <kbd>Cmd-Alt-I</kbd> and run `process.env.PATH` in the console and paste the output here?

Also, can you run `ls /bin/bash` in Terminal and let me know what you get?

**Comment by erwald** [comment]
@mnquintana For the first one:

```
"/usr/bin:/usr/local/bin:/Users/erichgrunewald/.rbenv/shims:/Users/erichgrunewald/.rbenv/bin"
```

Second one:

```
/bin/bash
```

**Comment by mnquintana** [comment]
@erwald Actually, can you quit Atom first, then open it from the Dock or Finder, and then run `process.env.PATH`?

**Comment by erwald** [comment]
@mnquintana I get the same result (the first one above).

**Comment by DavidAwad** [comment]
in the dev tools there's a JS error. 
```Javascript
(node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.events.js:232 addListener
```
```Javascript
process.env.PATH
"/usr/bin:/usr/local/bin"
```

and lastly 
```bash
➜  ~  ls /bin/bash
/bin/bash
```

Doesn't seem like zsh is messing with this but I'm not entirely sure.

**Comment by pusateri** [comment]
Seems like /bin should be in your path. If you have changed your path in .profile or .bashrc, you might want to add /bin and see if it fixes your problem.

**Comment by DavidAwad** [comment]
That didn't seem to work.

**Comment by lee-dohm** [comment]
There are a number of places where the default `PATH` can be set on OS X. (See [this StackExchange entry for more information](http://apple.stackexchange.com/questions/106355/setting-the-system-wide-path-environment-variable-in-mavericks).) To my knowledge, the OS default is `/usr/bin:/bin:/usr/sbin:/sbin` and is provided by the `/etc/paths` file. That is where I would check first to correct this @DavidAwad.

**Comment by DavidAwad** [comment]
This is what my `/etc/paths` file looks like. Seems to have everything. Unless `/usr/local/bin` is the problem but that's a brew thing. 
```bash
➜  ~  cat /etc/paths
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by lee-dohm** [comment]
I have the `/usr/local/bin` entry too because of Homebrew. So that isn't the issue. Curious then that some other system removes those entries for you.

**Comment by DavidAwad** [comment]
Any other ideas? I really love this editor : (

**Comment by mnquintana** [comment]
@DavidAwad There is definitely something weird going on with your `PATH` (it's quite strange that it's missing `/bin`), but I'll fix this shortly.

**Comment by DavidAwad** [comment]
That seems to have fixed it! Thanks!

**Comment by pusateri** [comment]
While restoring this may have fixed your problem, there was a reason it was changed in the first place. Not every operating system ships bash in /bin. So this change was part of an effort to make the code more portable. We really need to figure out why this didn't work for you so we can restore this patch.

**Comment by mnquintana** [comment]
I agree, this was meant as a temporary fix while we sort this out. @DavidAwad Have you edited your `PATH` yourself manually? (ie. in `.bash_profile` or `.bashrc`) If not, I'm wondering what could've edited your `PATH`. It's especially weird that there's no `/bin` in the `PATH` when loading Atom from the Dock / Finder – that likely means something's gone wrong with your OS X installation, because that shouldn't be the case.

**Comment by pusateri** [comment]
One thing @DavidAwad could try is to go to System Preferences / Users & Groups and create a new user with the plus sign on the bottom left. Then log in as that user, try the version of Atom that was broken for you and see if it works under the new user.

**Comment by yonas** [comment]
We reverted this fix a few months ago and it seems we haven't made any progress since.

If no one who has the issue is willing to help fix it, then we should proceed with reapplying the patch.

**Comment by tomck** [comment]
I'm on 1.4.0 with the same issue, on the latest OS X.11.

From Dock:
process.env.PATH
"/usr/bin:/usr/local/bin"

From "atom" in Terminal:
process.env.PATH
"/usr/bin:/usr/local/bin"

I checked my $PATH and it does contain /bin, so, I don't know why I'm getting this error, but I only noticed it after installing linter-rubocop.

Error: env: bash: No such file or directory
    at /Users/ME/.atom/packages/linter-rubocop/index.coffee:30:15

**Comment by CoreySwish** [comment]
This issue just popped up for me after upgrading from Yosemite to El Capitan 0.11.2 (15C50) on Atom 1.4.0. Anytime I save, create, or delete a file I get the following output:

```
Error: env: node: No such file or directory
Error: env: node: No such file or directory
    at parameters.exit (/Users/csb/.atom/packages/linter-bootlint/node_modules/atom-linter/lib/helpers.js:77:20)
    at triggerExitCallback (/Applications/Atom 2.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom 2.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Applications/Atom 2.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by CoreySwish** [comment]
> Do you get this error only if you launch Atom from the dock / Finder? Or do you also get it if you launch Atom from the command line? @mnquintana 

Just noticed (over the last 15 mins of testing)  that this only happens if I launch Atom 2 from the dock or from Alfred (similar to Spotlight). If I open finder>applications>atom2 no errors or open from command line also no errors. Seems weird. I've done this 6 times all fitting my description above.

**Comment by CoreySwish** [comment]
found the answer -> https://github.com/AtomLinter/linter-bootlint/issues/16

**Comment by thSoft** [comment]
A workaround is to add `/usr/local/bin` (where node is installed) to `PATH` with [this method](http://stackoverflow.com/a/26586170/90874).

**Comment by pcwa-ahendricks** [comment]
I was getting the same issue when using certain packages, namely [git-plus](https://atom.io/packages/git-plus).  Adding [this Atom init script](https://gist.github.com/dustinblackman/db56445e5d649ccbd2b2) resolved my issue since it was likely related to using zsh.
