### ISSUE TITLE
 unset! not working anymore (0.202.0), impossible to type curly braces!!

### ISSUE THREAD

**Issue by joseroux** [atom/atom#6990]
Atom is the first code editor in the world that prevent me typing curly braces b/c of a default key binding! So I had to search around and I found that I had to prevent that binding with: 
   ` 'ctrl-alt-[': 'unset!'` and `'ctrl-alt-]': 'unset!'` in the file: *keymap.cson*.

But that's broken in the latest version... that makes Atom useless, for me at least!

**Comment by joseroux** [comment]
More infos:
The unset! prevent the default binding action (un/fold-current-row) but it doesn't pass the event to windows it seems...
There's nothing else going on when I look to the key binding resolver:
![key-binding-resolver](https://cloud.githubusercontent.com/assets/5633182/7864162/76e7adfc-052e-11e5-90dc-3b2a64bcaedb.png)

I'm on Windows 7 64 bit.

**Comment by kevinsawicki** [comment]
Thanks so much for reporting this and apologies that this regressed.

I just deployed the `0.204.0` Atom release with this fixed, please let me know if you still see issues with it after upgrading to that version.

**Comment by joseroux** [comment]
Thanks, it works fine now in 0.204.0
