### ISSUE TITLE
Closing code blocks within an open file is buggy 

### ISSUE THREAD

**Issue by Protosac** [atom/atom#6992]
OS: Ubuntu 14.10
Atom: 0.198.0

I have no better way to describe this, sorry. If I have 3 nested code blocks and I try to close just the 3rd nested block, it closes the main block. If I open the main block I'll find the third block closed. It's an annoying little thing, but this makes it so I have to close/open things two times just to get the view I want.

Example, trying to close the list item at L37: 
![atom-1](https://cloud.githubusercontent.com/assets/6880594/7867104/d36ae0cc-0528-11e5-86fa-2cfa613e4864.png)

After closing list item at L37:
![atom-2](https://cloud.githubusercontent.com/assets/6880594/7867108/ddd64aa6-0528-11e5-84e5-5fea78858775.png)

**Comment by mnquintana** [comment]
You're using an old version of Atom – can you update to the latest version (0.204.0) and see if you can reproduce this?

**Comment by izuzak** [comment]
@Protosac Can you still reproduce this problem in Atom 1.0.11 in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If so, could you please post more details about how to reproduce this? A example file with step-by-step instructions would be helpful.

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/6992#issuecomment-139302691. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
