### ISSUE TITLE
Blue squirrel still shows after updates until second restart

### ISSUE THREAD

**Issue by brendanfalkowski** [atom/atom#6993]
After installing an Atom update and restarting, the blue squirrel stays present until I restart again. If you have OCPD or FOMO it's hard to ignore that squirrel, but also annoying to re-open all the windows/files as they were.

It'd be great if installing an update hid him immediately.

Sorry if this is the wrong repo to create the issue. I didn't see a sub-package that seemed responsible for handling updates.

**Comment by mnquintana** [comment]
This seems like a duplicate of https://github.com/atom/atom/issues/6922 – does that one more or less cover this?

**Comment by brendanfalkowski** [comment]
Yup, I'll close this one and comment there.
