### ISSUE TITLE
Wild memory consuming and 100% CPU usage while editing a small file.

### ISSUE THREAD

**Issue by stevendobay** [atom/atom#7000]
It allocates the memory until there's nothing left. No time to terminate.
Platform: Ubuntu 14.04, Mint 17.1, Gnome-shell 3.10.4

**Comment by 50Wliu** [comment]
What Atom version are you using?  Does this happen in safe mode (`atom --safe`)?  If so, it would be awesome if you could share the file you're editing.

**Comment by stevendobay** [comment]
Version: 0.201. Yes, it happens with safe mode and with or without plugins. The file is a starter Scala source(hello world for further editing).

**Comment by 50Wliu** [comment]
Is the file by any chance in your home directory?
(Also, if you update to Atom 0.204.0, there's been a large performance improvement that may help your issue)

**Comment by stevendobay** [comment]
No, in my "Workspace" folder. I'll install the new version.

**Comment by 50Wliu** [comment]
Just to make sure: is this the file you're editing?
```scala
object HelloWorld {
  def main(args: Array[String]) {
    println("Hello, world!")
  }
}
```

I copy/pasted that into Atom (Ubuntu 15.04) and tried randomly typing letters, inserting newlines, deleting, undoing, etc. but memory usage stayed constant.

**Comment by stevendobay** [comment]
Something similar(Main == HelloWorld). I don't need to do anything for it to be frozen. Not even touching Atom.

**Comment by stevendobay** [comment]
I can't install the new one because it requires npm1.4 and I've 1.3.10. When installing the latest with the official site's instructions it fails.

**Comment by stevendobay** [comment]
Can't reproduce it with version 0.205.0-5389156.

**Comment by 50Wliu** [comment]
All right, that's good to know :smile:.  Glad upgrading fixed your issue!

**Comment by stevendobay** [comment]
Thanks for helping!
