### ISSUE TITLE
Soft wrap not work well

### ISSUE THREAD

**Issue by loveai88** [atom/atom#7003]
I checked `Soft Wrap` and `Soft Wrap At Preferred Line Length`，and my line length is 120.
But when I use a small screen ,I can not see the wrap content

**Comment by izuzak** [comment]
Can you provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) and also check the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?

**Comment by kevinsawicki** [comment]
Closing this out since more information was never provided.

Please comment back if you have more details to share using the links provided by @izuzak
