### ISSUE TITLE
Support bazaar as VCS

### ISSUE THREAD

**Issue by rpadovani** [atom/atom#7007]
I love your editor guys!
One of the feature I like more is the git support, with highlights of lines/files changed.

Unfortunately, I don't use only git, but also [bazaar](http://bazaar.canonical.com/en/). Could be possible to add a (basic) support for it?

**Comment by mnquintana** [comment]
Thanks for the suggestion! This is a duplicate of https://github.com/atom/atom/issues/4138 – please subscribe there for updates.
