### ISSUE TITLE
Feature request : floating tab like chrome

### ISSUE THREAD

**Issue by BenUnikal** [atom/atom#7009]
It would be nice if we could detach and group tabs like we can do in chrome. It will be better if we can manage tabs like in Visual Studio.

**Comment by mnquintana** [comment]
@BenUnikal I'm not sure what feature you're referring to – do you mean the ability to drag and drop tabs from one window to another, and drag tabs away from a window to create a new window?

**Comment by BenUnikal** [comment]
I'm talking about those two features. It will be nice to have the same behavior as chrome has.

**Comment by mnquintana** [comment]
You can already drag and drop tabs from one window to another, and dragging tabs away from a window to create a new window is being tracked here: https://github.com/atom/tabs/issues/39

Closing this as a duplicate.
