### ISSUE TITLE
Distorted Tree View

### ISSUE THREAD

**Issue by mcmorgan** [atom/atom#7010]
Atom 0.202.0
OS: OS X Yosemite

I have seen this across all versions I have used. It does not show up all the time, just at weird moments.

![screenshot 2015-05-29 09 05 23](https://cloud.githubusercontent.com/assets/371739/7884326/88b08036-05e2-11e5-9535-bb80e52455c3.png)

Any help on this would be greatly appreciated.

**Comment by izuzak** [comment]
Yeah, it's a known issue -- see https://github.com/atom/atom/issues/4924. Closing this in favor of that issue.

**Comment by mcmorgan** [comment]
Thank you @izuzak. I did not realize.
