### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -27, expected to pop -45.

### ISSUE THREAD

**Issue by martinerk0** [atom/atom#7012]
[Enter steps to reproduce below:]

1. I opened it week after I wrote this, and its  crashing when I set syntax highlight to shell

2. file ist just a awk+shell

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.2
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -27, expected to pop -45.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:573

Error: Encountered an invalid scope end id. Popped -27, expected to pop -45.
  at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:573:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:555:21)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:286:105)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:263:26
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
  3x -0:22.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.2.0 application:open (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 13,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.2
ide-haskell, v0.5.6
language-glsl, v2.0.0
language-haskell, v1.0.0

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@martinerk0 Can you reproduce this in safe mode (`atom --safe`)?  If so, is there any chance you can share the file you were editing here?  Thanks.

/cc @nathansobo

**Comment by martinerk0** [comment]
#!/bin/bash
# Martin Cerven 2015
# Turing Machine simulator


inputName="input.txt"  # path to file with rules

# parameters: current state , current symbol on the tape
# execute next step based on current configuation



function nextStep {
  # parameters: current state , current symbol on the tape, path to transitions

  trap 'running="false"' INT
  trap 'exit' QUIT

  delta="d("$1","$2")"
  # echo "<nextStep>_"$delta"_<\nextStep>"
  var=$(( grep "$delta" "$inputName" || echo $? ) | cut -d= -f2 )

    if [[ var -eq 1 ]]; then
      echo 42
      # return 42
      return
    else
      printf $var     # return value
    fi

}
function currentSymbol {
  # finds current state on tape, head consist of: '<'+'currentstate'+'>'
  trap 'running="false"' INT
  trap 'exit' QUIT

  echo $1 | awk  'END{   lengthStart=index($0,"<");  width=index($0,">")-lengthStart; print substr($0, lengthStart+1,width-1 ) }'

}
function executeStep {
	# args:  $1=next symbol, $2=next move


		# head movement

    trap 'running="false"' INT
    trap 'exit' QUIT


		if [[ "$2" = "R" ]]; then
			# echo "R"
			tape=$(echo "$tape" | awk -v rep=$1 '{

			  for (i=1;i<=NF;i++){
			   if($i ~/<.*>/){

						$i=rep;
			      $(i+1)="<"$(i+1)">";   											# move it to right
			      break;   																		# important, otherwise infinite-loop

			    }
			  }
			}
			END {print $0}'
			)

		elif [[ "$2" = "L" ]]; then
			# echo "L"
			tape=$(echo "$tape" | awk -v rep=$1 '{

				for (i=1;i<=NF;i++){
				if($i ~/<.*>/){

						$i=rep                    #replace symbol under head
						$(i-1)="<"$(i-1)">";      # move it to right
						break;                    # important, otherwise infinite-loop

					}
				}
			}
			END {print $0}'
			)
		else
      printf "magnanimous ERROR \n arg: %s"
      read kext
      exit
		fi

    # echo "</executeStep>"
}
function main {
  # args:  tape, start state, final state

  running=1
  count=1
  halt=false
  # echo $1

  # cS=$1
  # firstArgIsTape=$1
  currentState=$2
  maxSteps=2000           #safety cap(debug-only)
  running="false"


  echo $tape




  while [[ !$halt   ]]; do




    if [[ $running = "false" ]]; then
      read keyPressed
    fi

    if [[ $keyPressed = "r" ]]; then
      running="true"
    fi




    cS=$( currentSymbol "$tape" )                          # scan tape
    nS=$( nextStep "$currentState" "$cS" )                  # next transition

    if [[ $nS -eq 42 ]]; then                               # if no transition is found
      echo "No rule found HALT!"
      exit
    fi

    nextState=$( echo  $nS | cut -d'(' -f2 | cut -d, -f1 )  # set next state
    nextSymbol=$( echo  $nS | cut -d'(' -f2 | cut -d, -f2 ) # set next symbol
    nextMovement=$( echo  $nS | cut -d'(' -f2 | cut -d, -f3 | cut -d')' -f1 ) # set next movement



    if [[ $nextState = "$3" ]]; then            # accepting State
      echo "Accept-halt!"
      break

    elif [ $# -eq 4 ] && [ $nextState = "$4"  ]; then            # rejecting State
      echo "Reject-halt!"
      break


    elif [[ $count -gt $maxSteps ]]; then
      echo "max number of steps"
      break
    fi


    # printf "no. %s | d(%s,%s)=(%s,%s,%s) \n" "$count" "$currentState"  "$cS" "$nextState" "$nextSymbol" "$nextMovement"


    executeStep  "$nextSymbol" "$nextMovement"      # execute next step of TM
    echo $tape

    count=$((count + 1))          # increase count (debugging-only)
    currentState=$nextState       # update state

    # printf "currentState: %s | currentSymbol: %s  \n" $currentState $cS


    trap 'running="false"' INT
    trap 'exit' QUIT


  done
}




tape=$1
tape="b b b b ""$1"" b b b b"             # just put some blanks at the beggining and end
startState=$( head -n3  $inputName | tail -n 1 | cut -d{ -f2 | cut -d} -f1)   # final state
acceptingState=$( head -n 4 $inputName | tail -n 1 | cut -d{ -f2| cut -d} -f1)     # final state


main "$tape" "$startState" "$acceptingState" "$rejectingState"  #  entry point


# #-----------------------------------------------
#
# #uncomment this for another language !
#
#
# accept language L= { 0^2^n | n > 0 }
# nameTransitionFile="transitions2.txt"
# statesS="q1 q2 q3 q4 q5 qA qR"
# tapeSymbolsS="0 x b "
# # tape="<0> 0 0 0  b b b b b"    # global tape variable
# tape="<0> 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1  b b b b b"  # 32 0's
# startState="q1"         # initial state
# acceptingState="qA"     # final state
# rejectingState="qF"     # rejectingState is optional with other TMs
# main "$tape" "$startState" "$acceptingState" "$rejectingState"  #  entry point
#
# #and put below this into input.txt
# #this are rules for language of 0^2^n
# Q={q1,q2,q3,q4,q5,qA,qR}
# G={0,x,b}
# s={q1}
# F={qA}
# d(q1,0)=(q2,b,R)
# d(q1,b)=(qR,b,R)
# d(q1,x)=(qR,x,R)
# d(q2,x)=(q2,x,R)
# d(q2,0)=(q3,x,R)
# d(q2,b)=(qA,b,R)
# d(q3,x)=(q3,x,R)
# d(q3,b)=(q5,b,L)
# d(q3,0)=(q4,0,R)
# d(q4,x)=(q4,x,R)
# d(q4,0)=(q3,x,R)
# d(q4,b)=(qR,b,R)
# d(q5,0)=(q5,0,L)
# d(q5,x)=(q5,x,L)
# d(q5,b)=(q2,b,R)

**Comment by mnquintana** [comment]
@martinerk0 Can you put that in a gist?

**Comment by martinerk0** [comment]
So? What was the cause? Btw, I saw that awk code in that script is not highlighted, but separately it is. Is it hard to program "highlighter" for recursive languages or it is just not implemented? ( Or is it bug? )

**Comment by nathansobo** [comment]
It was almost certainly caused by a change I made to the representation of syntactic scopes to save memory. This is an edge case and I'm working on fixing it now.

**Comment by nathansobo** [comment]
Thanks for the report and my apologies for missing this corner case. A fix is on master and will be out with the next release.
