### ISSUE TITLE
Multi-character invisibles break editor

### ISSUE THREAD

**Issue by 1j01** [atom/atom#7014]
Upon restarting in 0.204.0 (from 0.201.0; I suspect 0.203.0), everything is screwed up. The tokens appear to be shifted from where they should land, and lines are cut off at the ends. This is happening to all files. After reloading the window, it still occurs.
![broken editor](https://cloud.githubusercontent.com/assets/3630663/7875865/cf3e93b4-0590-11e5-9404-645d66e3b62e.png)
Here's a colon that should be highlighted:
![broken editor 2](https://cloud.githubusercontent.com/assets/3630663/7875867/d38efeea-0590-11e5-8a11-e848ad7fc591.png)
Here's a gif of me pressing <kbd>Backspace</kbd> <kbd>Backspace</kbd> <kbd>Space</kbd> <kbd>Space</kbd>:
![spspbsbs](https://cloud.githubusercontent.com/assets/3630663/7876021/d6e8a788-0592-11e5-8896-834fda95eb83.gif)
So yeah, I no longer have an editor...

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode? (`atom --safe`)

**Comment by 1j01** [comment]
Yes.

**Comment by 1j01** [comment]
...It works with spaces, but fails with tabs.
![broken editor 6](https://cloud.githubusercontent.com/assets/3630663/7886994/decaae88-05fb-11e5-85d9-1c70c5a0d539.png)
(Tabs are set to 2 here, and there's no character between the tab and the `a`)

**Comment by benogle** [comment]
Crazy. Can you paste the file in a gist and link to it here?

**Comment by maxbrunsfeld** [comment]
Can you also share the content of your `~/.atom/config.cson` in a gist?

**Comment by nathansobo** [comment]
For now you can fall back to 0.201.0. https://github.com/atom/atom/releases/tag/v0.201.0

Fixing this is my top priority, but I still can't reproduce it. Providing any of the artifacts requested would be very helpful. I'm very sorry for this.

**Comment by thomasjo** [comment]
Would you mind temporarily moving/renaming your `~/.atom` folder, and see if you're able to reproduce then? Just do e.g. `mv ~/.atom ~/.atom-backup`.

**Comment by thomasjo** [comment]
In addition, what OS are you running? @lee-dohm proposed a hypothesis that this might be related to line endings, which is affected by platform. Thanks in advance!

**Comment by nathansobo** [comment]
Would also be good to know what encoding you're using on this file.

**Comment by nathansobo** [comment]
@1j01 Do you by chance have an `editor.invisibles.tab` setting that contains more than one character? I was able to reproduce similar behavior with such a character (and it isn't supported). I'm going to change the system to disallow this regardless.

![screenshot 2015-05-29 21 16 10](https://cloud.githubusercontent.com/assets/1789/7890712/f22634ba-0647-11e5-8ff7-4af077622e67.png)

**Comment by 1j01** [comment]
Okay, I changed my tab setting to a single character, which fixes it. This worked completely before.

**Comment by nathansobo** [comment]
If it did, it was accidental. From the look of your screenshots a single `>` should work just fine, combined with a tab length setting.

**Comment by 1j01** [comment]
@nathansobo Yes, that is what I have changed it to.
