### ISSUE TITLE
Creating New Atom Launcher Icon In Ubuntu 14.04

### ISSUE THREAD

**Issue by prio101** [atom/atom#7015]
# Atom Launcher

I installed atom editor from the source , in the ubuntu 14.04 .

The Installation Guide in Github Repository of Atom is quite fun . But I want to create a launcher in desktop . Is there any way to do that . Or are you people thinking of writing it down in installation guide ? please , let me know...

**Comment by aaronhalford** [comment]
Sample setup as you with Atom installed from source on Ubuntu 14.04. My system does have an application launcher for Atom. Current builds Atom do not properly generate a Ubuntu desktop icon.


Assuming you cloned the Atom repo to `~/atom`, run the following in terminal to fix the icon issue:

``` bash
cd ~/atom
sudo cp --parents resources/atom.png /usr/local/share/atom/resources/app/
```

**Comment by prio101** [comment]
Thanks , This solved my problems ....
