### ISSUE TITLE
Setting toggle for default atom command line behavior

### ISSUE THREAD

**Issue by CharlesSocial** [atom/atom#7017]
Atom's default `atom` command behavior isn't going well with my workflow. From the discussions I've seen, a lot of people want the old behavior and some people enjoy the new behavior, making it the perfect candidate for a toggle setting. The behavior can be worked around by hacking a bash script, but I don't think that's a good user experience for a common workflow.

Before the implementation I'd like to get some input on where the setting should live. My thought is the setting doesn't have a good place on the GUI settings page, so maybe just a field in the config file will work for now.

**Comment by benogle** [comment]
So typing `atom .` is too much?

**Comment by CharlesSocial** [comment]
Haha, you'd be surprised how often the `.` is left off by accident, which creates a hiccup in the flow.

I work with a bunch of different apps, so I'm often changing directories between projects and opening atom in all of them. Here's the situation I'm often having:

- "Okay, I need to open three projects to get this feature implemented"
- `cd project_1 atom .`
- `cd project_2 atom`
- "what? Oh, damnit atom."
- close the new window
- `atom .`
- "what was the third project? Oh yeah." `cd project_3`
- `atom .`

The problem is not that typing the `.` is hard, typing it is easy, but it's also easy to not type. When you make the easy mistake of not typing it, the default behavior works against you.

**Comment by frxstrem** [comment]
The first thing I did when noticing the new behavior was look for a setting to disable it, and I'm quite surprised that this hasn't been implemented yet. Running `atom .` doesn't always work, especially when I want to start in a clean workspace, such as when opening Atom from its application shortcut or my custom keyboard shortcut (bound to `/usr/share/atom/atom` which used to open a clean workspace but doesn't anymore).

I don't mind the default behavior being changed, but I expected the change to be optional, so I very much agree that a toggle for this is needed.

**Comment by cooperia** [comment]
Charles' example is pretty much spot on. The number of 'what? Oh, damnit atom.'s flying around our office is too damn high.
