### ISSUE TITLE
Restoring session doesn't work for Term2 tab

### ISSUE THREAD

**Issue by szatkus** [atom/atom#7018]
1. Install https://github.com/webBoxio/atom-term2
2. Open Term2 tab (CTRL+SHIFT+T)
3. Close Atom
4. Open Atom without arguments

Excepted behavior: All tabs are restored.

Current behavior: A tab with terminal doesn't appear.

I'm not sure if it's Atom's bug or Term2's bug.

**Comment by maxbrunsfeld** [comment]
Unless you've seen that this feature worked on an earlier version of Atom and is now broken, I believe this is a bug (or maybe just an unimplemented feature) in Term2. Could you open an issue there first?
