### ISSUE TITLE
Atom is being treated as malware by antivirus programs on Windows.

### ISSUE THREAD

**Issue by vkbansal** [atom/atom#7029]
I had this issue on several machines running Windows 8.1 x64. `atom.exe` is flagged due to suspicious activities.

The antivirus programs tried:
- Avast
- Bitdefender

**Comment by batjko** [comment]
Can you post the details of *what* it is recognized as?

**Comment by 50Wliu** [comment]
I'm going to close this as a duplicate of #3927.  @vkbansal, it would be great if you could post what it's being detected as on that issue (like @batjko said).
