### ISSUE TITLE
Indentation glitch in certain scopes but not others.

### ISSUE THREAD

**Issue by phyllisstein** [atom/atom#7030]
Hey there! I've just noticed a somewhat strange glitch in how Atom responds to <kbd>Tab</kbd> in certain scopes---in particular Markdown, but I haven't cycled through them all yet. Setting the tab length to four spaces, either in `.gfm.source` or globally, causes Atom to insert four spaces but visually snap the cursor back to the middle of the tabstop, roughly two spaces in. From there, typing causes the cursor to jump back and insert text at the expected position about half of the time, and about half the time to drop text right where it appears to be, with two spaces before the insertion and two spaces trailing it. This also happens when I type four spaces the old-fashioned way.

I dropped a quick screencast demonstrating the hiccup at <https://cloudup.com/cUq4wn72BsS>. It was recorded with a brand-new, untampered-with Atom setup: I reinstalled the binary to be safe, and moved my `~/.atom` folder out of `$HOME`. The same behavior occurred, both without any third-party packages present and in safe mode.

So far I can attest that this _doesn't_ happen in plain-text mode, in Python, or with the scopes created by the `language-latex` package, but I can't generalize beyond that yet.

Please let me know if I can provide any more or any better information about the problem! And thanks in advance for your help.

**Comment by 50Wliu** [comment]
I can partially reproduce this on Atom 0.205.0-adc08d3, Ubuntu 15.04.  I could only reproduce the "typing causes the cursor to jump back and insert text at the expected position" result (maybe because I only tried indenting a few lines).

**Comment by 50Wliu** [comment]
Hey there @phyllisstein, a new issue was created recently about this same issue that got a bit more attention than this one.  For the sake of keeping discussion in one place, could you please go state your findings at #7160 please?  Thanks.
