### ISSUE TITLE
Auto update didn't work (twice) release notes is stuck at 0.196.0

### ISSUE THREAD

**Issue by Ciantic** [atom/atom#7031]
I installed 0.201 weeks ago, the auto update didn't work I had to use installer. Today I noticed auto updating once again didn't work. I ran uninstaller, and installed a new one.

Now the Help menu says my version is 0.204.0 but the *release notes* are stuck at 0.196.0. Also showing "Restart and update" button, yet my version is just downloaded.

I think I have to delete `.atom`, uninstall the whole thing. Somehow some parts, like release notes are stuck in the past.

Using Windows 8.1, 64 bit.

**Comment by batjko** [comment]
@Ciantic Which version are you on right now? Is this still an issue?

**Comment by Ciantic** [comment]
@batjko it is not an issue anymore, I deleted all cache directories I could find and it started to work again. I was wondering if many more had similar problems so I opened an issue. Perhaps it was not a bigger problem, closing this.

**Comment by batjko** [comment]
I still see some issues opened for this on occasion, but it is still a rare occurrence, it seems.
