### ISSUE TITLE
Atom Editor Memory Leak... 202 didn't decrease memory usage, it increase it by 4x.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#7033]
The recent 202 release increase the memory usage of Atom on my system with sparse editing by 4x+ in that I used to max out at about 1gb over a few days of editing files (I don't normally close my editor.) However, with the recent 202 release my memory usage creeped up to over 4gb plus, for some reason it seems to be swap thrashing (a problem we solved by simply denying swap access to Atom.) 

On a side/potentially-related note, I also get tons of messages like this in my console now:

```
events.js:232 (node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.events.js:232 addListener
events.js:236 console.trace()events.js:236 addListener
events.js:232 (node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.
events.js:236 console.trace()events.js:236 addListener
```

**Comment by mnquintana** [comment]
Can you update to the latest version of Atom (0.204.0) first and see if you can still reproduce this issue?

**Comment by envygeeks** [comment]
Unless your release logs are extensively horrible I don't see how that would help?

**Comment by envygeeks** [comment]
In that I already checked every release after to see any mention of this problem before even filing and concluded that it would be prudent to stay on this release to debug the problem, but if you absolutely need me to do Windows style debugging I'll upgrade.

**Comment by envygeeks** [comment]
Ok, I've updated and I'll let this ticket sit for a few days and update after i've got some heavy usage.

**Comment by thomasjo** [comment]
Are you able to reproduce the problem in [safe mode](https://atom.io/docs/v0.204.0/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by envygeeks** [comment]
I was able to reproduce it and still am able to reproduce it if I leave it open for extended periods.

**Comment by mnquintana** [comment]
Do you see this with any specific project or file, or is it with everything?

**Comment by kevinsawicki** [comment]
I was able to reproduce the leak console message caused by the `Task` class not cleaning up stdout/stderr listeners.

This was introduced in https://github.com/atom/atom/pull/5382 so it has been part of Atom since 0.190

**Comment by v3ss0n** [comment]
I was able to produce memory leak , over 100k+ every 4-5 secs. at atom 7c96854

**Comment by envygeeks** [comment]
For me this is fixed on my Linux system.  If @v3ss0n can confirm it's fixed in the latest version I'll close.

**Comment by v3ss0n** [comment]
I forgot to report here , memory problems are gone since v.206-207 so yeah , we can shut this down!

**Comment by envygeeks** [comment]
Thanks!

**Comment by Etienne13** [comment]
Hi,

First things first, I am not familiar with your development process and the way you name releases. Sorry for that.

After installing the v1.0.19 release, I observe a memory leak when using Atom. I noticed it appears on Linux but I am not observing this leak on Mac OS.

In this issue, you refer to fixes in release 206-207. However I did not find releases corresponding to these identifiers. Could you please explain me (or point to some link) how to install release 207?

Thanks,
Etienne.

**Comment by thomasjo** [comment]
@Etienne13 Please open a new issue with all essential details. This is an old, resolved issue. Thanks :bow:

**Comment by Etienne13** [comment]
Correct; sorry for that. Just found out that 207 is a much older release than 1.0.19.
