### ISSUE TITLE
Running `atom` command from terminal won't work

### ISSUE THREAD

**Issue by asinode** [atom/atom#7037]
I just installed the **`atom-amd64.deb`** using the instructions given in the [atom documentation](https://atom.io/docs/v0.204.0/getting-started-installing-atom). But the command `atom` is not working and throws the following error. 

But atom got installed! I can launch it like any other app from GUI. I use Ubuntu 14.04.

Please help!

```
$ atom
$ nohup: failed to run command ‘/tmp/atom-build/Atom/atom’: No such file or directory

```

**Comment by SurAnand** [comment]
As said above in the last issue #7037, I also have another error popping up if I launched Atom from GUI. Below is the error (bug).

## Failed to load the gitter package

```
ENOENT: no such file or directory, open '/home/anand/.atom/packages/gitter/node_modules/emojify.js/dist/js/emojify.js'
Hide Stack Trace
Error: ENOENT: no such file or directory, open '/home/anand/.atom/packages/gitter/node_modules/emojify.js/dist/js/emojify.js'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at module.exports (/home/anand/.atom/packages/gitter/lib/execFile.coffee:10:15)
    at /home/anand/.atom/packages/gitter/lib/emojify.coffee:10:12
    at Object.<anonymous> (/home/anand/.atom/packages/gitter/lib/emojify.coffee:11:5)
    at Object.<anonymous> (/home/anand/.atom/packages/gitter/lib/emojify.coffee:13:4)
    at Module._compile (module.js:452:26)
```

**Comment by SurAnand** [comment]
When I open Atom from Applications Menu at the top left corner in Gnome Shell of my Ubuntu 14.04, Atom does not show the expected Welcome Page. 

Atom instead opens along with a Red color box popping on the right side with the heading, __Failed to load the gitter package__ and the content is as shown above.

At the bottom of the box, there is clickable option saying, `Create issue on the gitter package`, I tried to click on it, but it didn't do anything. So, I used the small 'copy to clipboard' icon next to it, and pasted in my previous comment box above.

Also, at the bottom status bar, Atom shows __7 deprecations__ and when I clicked on it, third image below is what I see. I found online an advice to update packages using `apm upgrade`, I tried and below is the result

```
$ apm upgrade
Package Updates Available (0)
└── (empty)
```

I also tried the below step, but it did not make any difference in the issue I posted so far.
```
$ apm install gitter
Installing gitter to /home/anand/.atom/packages ✓
```
Hope the screenshots below helps.

![screenshot from 2015-05-31 20 30 41](https://cloud.githubusercontent.com/assets/7060963/7902328/f50abeca-07d3-11e5-90da-b16a5155913e.png)

![screenshot from 2015-05-31 20 31 58](https://cloud.githubusercontent.com/assets/7060963/7902336/1cb46f70-07d4-11e5-8b7b-ff5ee9d0d04f.png)

![screenshot from 2015-05-31 20 33 44](https://cloud.githubusercontent.com/assets/7060963/7902342/5a660afe-07d4-11e5-85e0-ed145d1bfd27.png)

**Comment by rsese** [comment]
Trying to go through and cleanup some older issues - it's been a while since this report and Atom is currently at release version 1.14.4. I'll go ahead and close the issue for now but if you're still seeing an error with the latest release version of Atom, please feel free to open a new issue and fill out the issue template @asinode ✌️
