### ISSUE TITLE
Invalid Bracket Matching

### ISSUE THREAD

**Issue by cynecx** [atom/atom#7038]
Hello :smile:,

So I've been working with Atom quite a while now and noticed a bug when Atom matches curly brackets. The main issue here is that brackets in special scopes/context should be ignored like in comments or regex objects (eg. Javascript).

![invalidbm](https://cloud.githubusercontent.com/assets/5961244/7902279/de8d894e-07b4-11e5-8c9f-131173e037ef.png)

Atom 0.204.0 on Windows 7 x64.

**Comment by izuzak** [comment]
Thanks for the report -- there's already an issue tracking that problem: https://github.com/atom/bracket-matcher/issues/78. Gonna close this in favor of that.
