### ISSUE TITLE
Atom does'n handle corectly the [ sybol

### ISSUE THREAD

**Issue by reirep** [atom/atom#7040]
Same kind of issue already reported, I can't type the [ symbol in atom editor (atl Gr+^ on a Belgian keyboard). Atom accept the [ symbol when I type anywhere else than into the editor (setup, ...).
![github](https://cloud.githubusercontent.com/assets/9026252/7902752/0f331d7a-07c4-11e5-9a5d-5a5cd5dff59e.png)

**Comment by izuzak** [comment]
Thanks for the report, @reirep  -- you're hitting a known issue, which you can read about and subscribe for updates here: https://github.com/atom/atom-keymap/issues/35.
