### ISSUE TITLE
Support copy with Keyboard shortcut when the Preview Window is focused

### ISSUE THREAD

**Issue by rgl** [atom/atom#7041]
When we open the Preview Window, say when editing a `.md` file, let us press `Ctrl+C` to copy the selected text. Currently that only works from the context menu.

Please note that copying from a normal paragraph works, BUT if you select the text from a `Fenced code block` it wont work. I'm using Atom 0.204.0.

**Comment by lee-dohm** [comment]
This belongs on the [markdown-preview package](https://github.com/atom/markdown-preview). Would you mind reopening the Issue there?

**Comment by mnquintana** [comment]
This issue was moved to atom/markdown-preview#259
