### ISSUE TITLE
Screenshot on atom.io homepage shows old theme

### ISSUE THREAD

**Issue by russlescai** [atom/atom#7043]
I know this is minor in the scheme of things, but I noticed the homepage for https://atom.io still has the Atom Dark theme, not the One Dark UI theme as the screenshot.

**Comment by mnquintana** [comment]
This might not get updated till 1.0 lands, but I'm not really sure.

**Comment by russlescai** [comment]
no biggy more an observation. :)

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#16
