### ISSUE TITLE
Cmd+t menu allows opening new file in same tab by using shift+enter or shift+click.

### ISSUE THREAD

**Issue by maletor** [atom/atom#7044]
Discussed over on https://github.com/atom/tabs/pull/145, but giving it a little more light here.

**Comment by lee-dohm** [comment]
This should probably be opened on the [fuzzy-finder package](https://github.com/atom/fuzzy-finder) which provides the <kbd>Cmd+T</kbd> menu.

**Comment by maletor** [comment]
Moved to https://github.com/atom/fuzzy-finder/issues/107.
