### ISSUE TITLE
Ellipsis character not recognized as punctuation when double clicking words to select

### ISSUE THREAD

**Issue by xPaw** [atom/atom#7047]
When trying to select `test…` it will select both `test` and `…`, but if the text is `text...` *(with normal dots)*, it will only select `test`.

**Comment by herkyl** [comment]
Chrome also doesn't select ellipsis (or 3 dots), I think it makes sense this way.

**Comment by thedaniel** [comment]
Fixed in #7458, and will go out in the next release.
