### ISSUE TITLE
 [Survey] A better keybinding for toggle-bookmark?

### ISSUE THREAD

**Issue by grandsong** [atom/atom#7048]
## What happens?

[Some users find the **default** keybinding to toggle bookmarks **isn't working**](https://github.com/atom/atom/issues/3930), probably due to conflicts with the keyboard bindings of Intel Graphics (installed as a driver), which is **very common for Windows users**.

Even when that `ctrl-alt-f2` does work, I feel it **really hard to hit**, either with one (left) hand of mine or with both.

## My solution

So far, none of the packages in my Atom occupies the key `f1`.

Hence, I added a line into my "keymap.cson":

```
'f1': 'bookmarks:toggle-bookmark'
```

I am happy.

## What to survey

I wonder:

1. If `ctrl-alt-f2` works for you, do you feel it easy enough to hit?

2. If you agree to change the default keybinding of toggle-bookmark, what keymap will you prefer, and **why**?

**Comment by lee-dohm** [comment]
I don't use bookmarks, so this survey doesn't apply to me. On the other hand, `f1` is listed in the [Windows Developer Guidelines](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646335%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) as a "system-wide" assignment for Help. We should probably avoid clobbering that.

**Comment by mehcode** [comment]
We have bookmarks? I suppose these are per state box / project. Honestly never used them before. I'll give them a try later. Might be one of those things you don't know you want till you have it.

----

First question I'd ask here is why are our shortcuts different than what sublime has?

https://github.com/atom/bookmarks/blob/master/keymaps/bookmarks.cson

```
{ "keys": ["f2"], "command": "next_bookmark" },
{ "keys": ["shift+f2"], "command": "prev_bookmark" },
{ "keys": ["ctrl+f2"], "command": "toggle_bookmark" },
{ "keys": ["ctrl+shift+f2"], "command": "clear_bookmarks" },
{ "keys": ["alt+f2"], "command": "select_all_bookmarks" },
```

**Comment by lee-dohm** [comment]
This survey also probably belongs on the [bookmarks package](https://github.com/atom/bookmarks).

**Comment by grandsong** [comment]
I am surprised when @lee-dohm said he don't use bookmarks and @mehcode has not used.

Therefore, bookmark is not as commonly useful as I assumed.

**Withour bookmark, how do you go and come back to some key lines quickly?**

Or, do you often edit one identical file in two panes and switching between the panes makes an effective alternative?

If I learn from you, probably I will depend on bookmark less.

---

@mehcode:

A difference between Atom and Sublime Text is that in the former there is one more keybinding about bookmark, which is `ctrl-f2` for a palette of list of bookmarks. 

Then, somehow, Atom team, at least those who are responsible for the bookmark package, seem to have suffered chaos when trying to reshuffle.

I agree that all the keymaps needs to be reconsidered.

There can hardly be many bookmarks, because they are less frequently used and each requires manually toggling. So, I think the palette of list of bookmarks is **not important enough** to take `ctrl-f2`.

Or, perhaps we can just forget about this unique yet unimportant feature and **set all the keybindings exactly the same as those in Sublime Text**.

---

@lee-dohm:

Yes, f1 is always for help in tradition. I also feel it not good to occupy f1.

But Atom has no contextual help at all. And I don't think it will someday. As to general help, one key is never enough and therefore there is a menu of Help in the toolbar.

I keep most default keybindings about bookmark which use f2 in common. While f3 is heavily occupied too, I find f1 the best candidate so far.

Anyway, I wonder about better solutions.

---

Yes, the bookmarks package. I will post an issue there when I am ready.

However, I suspect that is not a good place to do a survey, for there are not many users watching. Actually, just 17. In contrast, here, 1072.

**Comment by lee-dohm** [comment]
I don't use bookmarks because most of the time I use Goto Line <kbd>Ctrl+G</kbd> or Goto Symbol <kbd>Cmd+R</kbd>. I'd rather use Sublime-compatible key bindings than to use <kbd>F1</kbd>.

**Comment by grandsong** [comment]
If the file (buffer) is just a few screens tall, I prefer scrolling to any goto operation. If it is large, however, there are usually many symbols and thus navigating among them is not quick. Then, I prefer bookmarks.

Is this just me, or do some others also feel the same?

**Comment by mark-hahn** [comment]
>  If it is large, however

That's your first problem.  All files should be a few screens tall (grin). Having said that I do get lazy and make long files myself.  I only use bookmarks when I find I'm already hopping between two or three places.

If the bookmark keybindings need to change then they should match sublime.

**Comment by grandsong** [comment]
@mark-hahn you have a good point.

I myself is still in the progress of breaking codes into smaller and smaller pieces. But as I foresee, a better ecosystem (sorry, I don't how to call that concept precisely) is required to fulfill the goal. Otherwise, the overall efficiency will be down due to cost of switching among different pieces.

At present, I still have to deal with large files often.

**Comment by grandsong** [comment]
I have applied the Sublime keystroke patterns by adding the below into my keymap.cson:

```
'.platform-win32 atom-text-editor':
  'ctrl-f2': 'bookmarks:toggle-bookmark'
  'alt-f2': 'bookmarks:view-all'
  # 'ctrl-shift-f2': 'bookmarks:clear-bookmarks'
  # 'f2': 'bookmarks:jump-to-next-bookmark'
  # 'shift-f2': 'bookmarks:jump-to-previous-bookmark'
```

Note:

Those 3 unchanged are commented. If you want change them, uncomment them first.

'.platform-win32' means for Windows. You can remove it if you like. And replace `ctrl` with `cmd` if the form doesn't exit in your keyboard.

**Comment by Zireael07** [comment]
I'd say ctrl+shift+f2 is clumsy, Sublime shortcuts are better. That said, I use Ctrl+G or search for whatever I need, or scroll down to wherever I expect the relevant bit to be (I use minimap :) )

**Comment by mehcode** [comment]
> Withour bookmark, how do you go and come back to some key lines quickly?

Honestly, I remember the line number, function, or symbol name. `ctrl-p` can do `goto-file`, `goto-line`, but not `goto-symbol` (yet, there is `ctrl-r` for that). 

---

Just for the record. BBEdit uses `shift-cmd-j` for add bookmark and Visual Studio uses `ctrl-k`.

---

Still, I think bookmarks would be nice to use (on that occasion where you have a 5,000 line file). Here are some ideas on improving them:

 - Name them (optional but after research people seem to like it)
 - *Add*/*Remove* them (not *toggle*; I'm not a fan of the wording)
 - Generate them (from a search; I've seen magic where in some editors you could generate a huge list of bookmarks -- think of this like saving find results)
 - Search through them (by name and/or line content)
 - View them (on a tab similar to find results)
 - Jump to a specific bookmark
 - Undo cursor jump (command to go back to where I was before the jump to a specific bookmark; this feature could also help with other commands like `goto-anything`)
 - Move forward/backward through bookmark selections (we have that)

**Comment by Zireael07** [comment]
+1 to all those ideas.

**Comment by grandsong** [comment]
You guys are so used to `ctrl-g` (goto line).

Good at remembering line numbers? Is that a habit you have developped during your uses of old-fashioned editors?

@Zireael07: Oh, I forgot to install minimap! Thanks for reminder.

@mehcode:

You really thought a lot about bookmarks.

Hey, was there a research?

With regard to naming bookmarks and generating them, as what I can imagine, they will not be very easy/friendly to use, I am afraid.

I don't get the point of "a huge list of bookmarks". I use bookmarks to location only several key lines, which can change depending on what is my current focus need of editing. I won't keep bookmarks I think can be no longer useful.

I don't know what the magic of generating is like. A thing close to that is Symbols in Atom. `ctrl-r` is OK. And a package "Symbols Tree View" makes symbols more helpful. It is actually a in-file navigation sidebar.

"Add/Remove" is better than the generic word "toggle", I agree.

Some one might create a package to "search through them (by ... line content)". But I wonder if there is great demand.

Atom already has a command to "View them".

```
  'alt-f2': 'bookmarks:view-all'
```

"Undo cursor jump" is a signficant feature in Sublime Text 3. Not only about jumps to bookmark. You can undo moves of cursor as easily as you undo your changes of text.

**Comment by mehcode** [comment]
> Good at remembering line numbers? Is that a habit you have developped during your uses of old-fashioned editors?

Mainly function and symbol names. It's rare that I want to go to a specific line number but it happens. In an office, sometimes its easier to say "go to X line" when you want to show somebody something. Do that enough and you remember that some horrific hackfix was added around line X.

---

> Hey, was there a research?

Surveyed how bookmarks work in Sublime, Visual Studio, BBEdit, vim, and emacs. Also some additional plugins/packages of the aforementioned editors.

---

> With regard to naming bookmarks and generating them, as what I can imagine, they will not be very easy/friendly to use, I am afraid.

You're probably right. I was trying to think of a way to better organize/filter bookmarks. And a name would have to be entered. Which means an input box somewhere in the process of adding the bookmark (or a way to edit a bookmark later). We could have two commands, `bookmark-add` and `bookmark-add-with-name`.

> I don't get the point of "a huge list of bookmarks". I use bookmarks to location only several key lines, which can change depending on what is my current focus need of editing. I won't keep bookmarks I think can be no longer useful.

Thinking about this and "generating"; I believe we could make a couple improvements to "find results" to do what I want here. I would like to be able to find all occurrences of an expression and "iterate through them" (with a next/prev result shortcut). I'd be interesting to be able to save "find results markers" as bookmarks but that probably has a much smaller audience.

> Some one might create a package to "search through them (by ... line content)". But I wonder if there is great demand.

First thing (after keyboard shortcut weirdness) when trying to use bookmarks in atom that frustrated me. When I open the "view all bookmarks" it looks like I *can* search through them (and you can't, any text entered just clears the list). I think keeping it how it is and just allowing search through the line content would be a nice usability addition.

> Atom already has a command to "View them".

Ha. Just on a roll listing.

> "Undo cursor jump" is a signficant feature in Sublime Text 3. Not only about jumps to bookmark. You can undo moves of cursor as easily as you undo your changes of text.

Yeah. And that probably needs to be rooted directly into atom. Remembering where the cursor has been and all that.

**Comment by grandsong** [comment]
I think it is a good idea to "save find results markers".

The finder of Atom is as good as those of other editors but we can push boundaries.

There are quite a few potential features out there.

For example, tabs for different Find/Replace jobs. So, you can simply switch between jobs instead of deleting and re-typing expressions or check/uncheck options.

And I'd like to try to create a package "Enhanced Find And Replace".

**Comment by 190n** [comment]
On Debian-based Linux distros, Ctrl-Alt-F(1-6) will toggle to tty(1-6), and applications can't override that.

**Comment by Lvtran1987** [comment]
Has there been a solution found to this issue? I'm encountering the problem myself right now using Sublime. I could DL atom but I just feel like it should work so shouldn't have to. Haha

**Comment by bklooste** [comment]
contrl alt f2  is often used to switch console , I Like VS here ^BT  for toggle ^BN for Next

**Comment by lee-dohm** [comment]
Sorry @grandsong that I missed your request to close this issue.

For others, it is unlikely at this point that we are going to change the default keybinding for bookmarks. People can always remap the key to whatever they like using Atom's [Keybinding support](https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings).

**Comment by victusmortuus** [comment]
Ctrl+F2 is a standard for toggle bookmarks - Visual Studio, Sublime, Notepad++, SciTe and more.  Yeap, you can rebind but why choose non-standard key combination for any action. Maybe you consider this small change. Do  you want pull request?

**Comment by lee-dohm** [comment]
Thank you for the feedback @victusmortuus. We're still not willing to change the default keybindings.

**Comment by q2apro** [comment]
+1 for @grandsong's post and the idea of using `F1`, saved me. 

+1 for @victusmortuus - yes, other editors use `F2` and `CTRL+F2` which can be regarded as standard.

Please change it.
