### ISSUE TITLE
Incorrect line width calculation when cyrillic symbols is used and soft wrap is enabled

### ISSUE THREAD

**Issue by seleckis** [atom/atom#7050]
Annoying horizontal scrollbar appears.

Look at the screenshot:
![screen shot 2015-06-01 at 22 05 51](https://cloud.githubusercontent.com/assets/988504/7920903/6ecee6ba-08aa-11e5-9c8e-7fd77d5e354e.png)
OS X

**Comment by benogle** [comment]
@as-cii will the new text measurement bits fix this?

**Comment by as-cii** [comment]
@benogle: similarly to https://github.com/atom/atom/issues/1894#issuecomment-146770484, this incorrect behavior originates in how we handle soft-wrapping (i.e. we use the wrapping column). This will be fixed as soon as we switch to a technique that relies on actual text width.
