### ISSUE TITLE
French accents, broken word-wrap, text goes crazy

### ISSUE THREAD

**Issue by Ohmnivore** [atom/atom#7057]
It happens when I type a tag in an HTML document (if the line has a character with a french accent preceding the tag). It doesn't matter if it's an opening/closed/mismatched tag.

Before tag:
![screenshot from 2015-06-01 22 15 08](https://cloud.githubusercontent.com/assets/3769354/7927256/9e940820-08ab-11e5-9794-6bb7a72e7273.png)

As I add "<b" to the line, it goes crazy (duplicated letters appear):
![screenshot from 2015-06-01 22 15 15](https://cloud.githubusercontent.com/assets/3769354/7927266/bb604d10-08ab-11e5-866b-7fe64d7db235.png)

This happens consistently, so I avoid the issue by putting any subsequent tags on a new line.

I'm using version 0.198.0 on Debian, the French keyboard locale is "ca(multi)". I use both the standard "us" and "ca(multi)" layout in my files, maybe it has something to do with the issue.

**Comment by benogle** [comment]
cc @nathansobo

**Comment by nathansobo** [comment]
@Ohmnivore Can you reproduce this in safe mode (started with `atom --safe`) on the latest version?

Can anyone reproduce this? I'm having trouble.

**Comment by Ohmnivore** [comment]
Still happens in safe mode

**Comment by Ohmnivore** [comment]
Paste this character (é) on a new line, then type "<b" immediately following it

**Comment by 50Wliu** [comment]
I can't reproduce this either.  @Ohmnivore, could you please try updating to 0.205.0 and see if it still happens?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/7057#issuecomment-108082630. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
