### ISSUE TITLE
Atom is trying to add a new helper tool?

### ISSUE THREAD

**Issue by sebhoss** [atom/atom#7058]
hey there,

everytime i open atom, i'm asked to enter my password in order to let atom install a new helper tool. After entering my password, i don't see any change or any new tool, yet the same popup appears again the next time i open atom. As you can see in the attached screenshot, all my packages are up to date.

Any idea what's causing this?

![image](https://cloud.githubusercontent.com/assets/44168/7930730/3f332e78-090b-11e5-8ca6-eb7c8e7c85fe.png)

**Comment by benogle** [comment]
Can you try starting atom with `atom --safe`. Does it still happen?

**Comment by sebhoss** [comment]
yep seems to happen even with `--safe`

![atom update 2](https://cloud.githubusercontent.com/assets/44168/7959770/291f4206-09fc-11e5-94bd-4b5813423fd8.png)

**Comment by mnquintana** [comment]
Did this start after a recent update? What version of Atom are you running? Did you install Atom from atom.io or from Homebrew Cask?

**Comment by sebhoss** [comment]
Yes, i would say it started recently but i can't pin point it to a specific version. Currently running version 0.198.0 here which i must have gotten from atom.io. `brew list` does not include atom or atom.io

**Comment by mnquintana** [comment]
Can you try updating to the latest version (Atom 0.205.0) first and see if you still experience this issue?

**Comment by sebhoss** [comment]
just downloaded the app again from atom.io - the version is the same as i had previously, but now i'm seeing "Downloading Update" in the application menu. After a few seconds, the usual popup appears. Entering my password and restarting the application to complete the installation of the update(?) does not seem to install it (correctly?). Is there any way to get some kind of debug output?

![image](https://cloud.githubusercontent.com/assets/44168/7960119/51278b94-09fe-11e5-9f97-12db4981e3c0.png)

**Comment by sebhoss** [comment]
Ok maybe that's my problem? I have an old version lingering around somewhere ... lets see how to purge it ;-)

**Comment by sebhoss** [comment]
updating within the application did not work for me, but at this point i'm guessing that somehow my installation got broken. i ended up doing `rm -rf .atom/` and then move the app inside the application folder. Seems that i'm now running the latest version and i don't get to see this popup anymore. 

Thanks for the help & sorry for the trouble :-)

![image](https://cloud.githubusercontent.com/assets/44168/7960264/7516995e-09ff-11e5-8e68-839216c80601.png)

**Comment by kherrera-ebsco** [comment]
I know this issue was closed long ago, but I wanted to pitch in my solution when I encountered this issue. It was one related to permissions. I had installed this app under a separate account, but in the shared `/Applications` directory. When I changed its ownership to the account that I switched to, I didn't get this popup again and I was able to install the update just fine.

**Comment by fxrhxn** [comment]
@kherrera-ebsco How did you transfer ownership? I think I am having the same exact problem.

**Comment by kherrera-ebsco** [comment]
@fxrhxn I used the `chown` command. If you're not familiar with the command, it may be easier to simply delete the app and re-install it.

**Comment by fxrhxn** [comment]
Ok, reinstalling the app. Thanks for the quick reply. @kherrera-ebsco

**Comment by orangenagy** [comment]
So does Atom not support multiple users?

I've just chowned the app to the user I'm currently using - hoping it makes the popup go away.

**Comment by gorham335** [comment]
If you're unfamiliar with `chown` and need an OSX change-owner solution, visit: http://osxdaily.com/2013/04/23/change-file-ownership-mac-os-x/

(Worked for me running OSX 10.12.5 and Atom 1.17.2.)

**Comment by s2t2** [comment]
I installed Atom via Brew Cask and am running into this issue. FYI for me, `~/Applications/Atom.app` is owned by `root`, with group `wheel`.
