### ISSUE TITLE
Workspace.open() should support splitting up / down

### ISSUE THREAD

**Issue by walles** [atom/atom#7059]
The docs here...
https://atom.io/docs/api/v0.204.0/Workspace#instance-open
... says that `Workspace.open` supports the `split` option with arguments `left` or `right`.

In addition to this, I would like `Workspace.open` to support splitting `up` and `down` as well.

Needed by the Markdown preview pane for example:
https://github.com/atom/markdown-preview/issues/99

Regards /Johan

**Comment by walles** [comment]
Here's the code that needs updating:
https://github.com/atom/atom/blob/ac1b7d4fae0443f5a423446c6bcb408a2da59636/src/workspace.coffee#L362

**Comment by batjko** [comment]
Agreed. Even just to have consistency.

**Comment by lee-dohm** [comment]
This has been [available since v1.2.0](https://github.com/atom/atom/commit/1b0d72b232234cbcaf0faaf3a66c29047e594696). Sorry for missing closing this :blush:
