### ISSUE TITLE
Uncaught Error: Encountered an invalid scope end id. Popped -33, expected to pop -43.

### ISSUE THREAD

**Issue by jrwiegand** [atom/atom#7063]
1. Open a *.jsp file in Atom editor.
2. Delete the file in Finder (Mac OS X)

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: Encountered an invalid scope end id. Popped -33, expected to pop -43.

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:573

Error: Encountered an invalid scope end id. Popped -33, expected to pop -43.
    at TokenizedBuffer.module.exports.TokenizedBuffer.scopesFromTags (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:573:21)
    at TokenizedBuffer.module.exports.TokenizedBuffer.openScopesForRow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:555:21)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:286:105)
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:263:26
    at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "fontFamily": "source code pro",
    "fontSize": 13
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by izuzak** [comment]
@jrwiegand Can you still reproduce this problem in Atom 0.207.0? I just tried opening and deleting a jsp file as you described and wasn't able to trigger the exception. If you can still reproduce, could record a short GIF which demonstrates how you're reproducing this, and share a link to the file in question? Thanks!

**Comment by jrwiegand** [comment]
Nope. I cannot seem to reproduce the error. I think there was a long time between opening the file, then deleting and then viewing it again. I am not entirely sure how this error occurred. I also tried various things like locking/sleeping the computer but I cannot seem to get it to happen again. If the error should happen I will be sure to watch more closely next time.

**Comment by nathansobo** [comment]
This is probably happening with a particular grammar in a particular situation. If it happens again, would love to know the grammar and the content of the file that triggers it. Thanks, and sorry for the exception.

**Comment by jrwiegand** [comment]
No problem. Thanks you the quick response. Really enjoying the project. Should I just close this thing?

**Comment by nathansobo** [comment]
It should definitely stay open since this bug is still lurking in the darkness somewhere.

**Comment by jrwiegand** [comment]
"Night gathers, and now my watch begins..." ;-)

**Comment by nathansobo** [comment]
@jrwiegand Seen this again?

**Comment by jrwiegand** [comment]
@nathansobo  I have not seen a thing. Very weird. I am really liking the 1.0 release though.

**Comment by nathansobo** [comment]
:bow: Thanks!
