### ISSUE TITLE
ES6 template string syntax highlighting colors next line sometimes

### ISSUE THREAD

**Issue by AgentME** [atom/atom#7068]
Inside an ES6 template string, if a '}' is the last character on a line before the word wrap, then the next line is colored red like the curly braces usually are.

Here's a sequence of screenshots showing me slowly expanding an Atom window. The issue is visible in the second screenshot.

![screen shot 2015-06-02 at 1 49 06 pm](https://cloud.githubusercontent.com/assets/577345/7946908/744659aa-092e-11e5-976a-f347d453a89a.png)
![screen shot 2015-06-02 at 1 49 03 pm](https://cloud.githubusercontent.com/assets/577345/7946909/7447754c-092e-11e5-9a74-74cd700c2b47.png)
![screen shot 2015-06-02 at 1 48 56 pm](https://cloud.githubusercontent.com/assets/577345/7946910/74487000-092e-11e5-840b-bddda59d00ef.png)

**Comment by AgentME** [comment]
Reproducing this should be as simple as putting something like this in a javascript tab and resizing the window:

    var foo = `aaaaa${5+6}bbbbbbbbb`;

I just checked that it works with a fresh Atom profile.

**Comment by izuzak** [comment]
Thanks for the report, @AgentME. :bow:

@nathansobo Do you want to :eyes: this one maybe? I was able to reproduce it on the latest master just now.

**Comment by nathansobo** [comment]
Ah yes, I think I have a sense of why this is happening. I'll take a look soon once I make some more progress on large files. Getting close on that front.
