### ISSUE TITLE
Dev Tools debugger doesn't halt on breakpoint

### ISSUE THREAD

**Issue by bobrocke** [atom/atom#7069]
I'm debugging an extension. I first execute a command from the extension so that its file loads. When I open the Dev Tools Sources pane, my source file is already open. Clever! I don't know how it could know.

I can set a breakpoint, but when I execute a command that will lead to the breakpoint, the extension does not halt execution at all, even though I can see the breakpoint is set.

Am I debugging wrong? Did I miss a step?

**Comment by lee-dohm** [comment]
I was able to make it work:

1. Ran `apm link --dev` in my `tabs-to-spaces` package source directory
1. Launched Atom using `atom --dev` (to ensure that the one from my source directory was the one executing)
1. Opened the Developer Tools
1. Switched to the Sources tab
1. Executed the `tabify` command to ensure the package was loaded
1. Found the `tabs-to-spaces.coffee` file in the list of sources (it was under "(no domain)" rather than in a folder and such)
1. Set a breakpoint in the `tabify` command
1. Executed the `tabify` command

It stopped at the breakpoint, as expected.

**Comment by izuzak** [comment]
@bobrocke Can you include exact steps to reproduce the problem [with your reports](https://github.com/atom/atom/issues/6938#issuecomment-105218664)? (Starting with a command which creates a local clone of a project you can reproduce this with.) Happy to reopen this when you do.

> When I open the Dev Tools Sources pane, my source file is already open. Clever! I don't know how it could know.

I believe it remembers the files you had open the last time (try quitting Atom, restarting, and open the Sources panel without doing anything -- you should see the same files open which were open before quitting).

**Comment by bobrocke** [comment]
@lee-dohm Is the `apm link --dev` necessary for packages within `~/.atom`?

I'll try those things and see...

**Comment by bobrocke** [comment]
@lee-dohm That still didn't fix it for me.

1) I downloaded the package from https://github.com/bobrocke/open-a-terminal
2) Ran `apm link --dev` in the source folder
3) Launched Atom with `atom --dev`
4) Opened Dev Tools
5) Switched to Sources tab
6) Executed the `open terminal here` command from the context menu with a file selected in tree view
7) Found `open-a-terminal.js` in the sources list
8) Set a breakpoint in the `open here` command
9) Executed the `open terminal here` command from the context menu with a file selected in tree view

The command ran, the terminal opened, but the breakpoint didn't halt execution.

**Comment by izuzak** [comment]
Thanks for the detailed steps.

> 9) Executed the open terminal here command from the context menu with a file selected in tree view

I'm seeing some really funky behavior after this step -- the debugger stops at my breakpoint (I put it at the first console.log line in that function), but Atom's editor window actually stops refreshing, e.g. I can't select anything in it (but other parts of Atom are fine, e.g. the tree view). However, if I run the `open terminal here` command from the command palette and not from the context menu -- everything works fine.

Are you seeing the same, @bobrocke?

**Comment by bobrocke** [comment]
@izuzak I have seen the freeze behavior from time to time, but can't reliably reproduce.

Executing from the context menu or the command palette do the same for me - the command completes, but doesn't halt at the breakpoint.

**Comment by izuzak** [comment]
@bobrocke Which line are you setting the breakpoint at _exactly_? Does setting the breakpoint on different lines change anything? (But please restart Atom every time after you go through all the 9 steps you listed.)

**Comment by izuzak** [comment]
@kevinsawicki Could you take a look at this -- wondering if you have any ideas?

**Comment by bobrocke** [comment]
My breakpoint is on line 49: `console.log('Open A Terminal Here command fired!');`.

Setting the breakpoint elsewhere makes no difference.

This time, I can open the command palette, but not type into it's search box. But when I scrolled to and selected the `open terminal here` command from the command palette, execution stopped at the breakpoint. When I continued, the command completed and then the editor pane was unresponsive. The tree view still worked.

**Comment by bobrocke** [comment]
Can anyone think of something else I should be trying? This is frustrating - I figured if the debugger had the file open with a breakpoint set, that should be the end of it. But I've missed something...

**Comment by benogle** [comment]
Can you insert a `debugger` statement? Does that stop it? Does the `debugger` statement show up in the dev tools code sample?

**Comment by bobrocke** [comment]
Here's what I see after setting the breakpoint and selecting the command:

![open-a-terminal - atom](https://cloud.githubusercontent.com/assets/2962426/7970915/30c4d328-0a0f-11e5-8991-583a584763fa.jpg)

**Comment by bobrocke** [comment]
@benogle Uncommenting the debugger made execution stop on the debugger statement and skipped right over the breakpoint.

**Comment by benogle** [comment]
Did the `debugger` statement stop it? Are you totally sure that the package is linked, and that code file is pointing to the file you're editing?

**Comment by bobrocke** [comment]
Yes, the debugger statement stop it. So I assume I'm running the file I'm seeing in the debugger.

**Comment by benogle** [comment]
Ok, so the debugger statement stopped it, and it acted like a breakpoint? Could you step through things? When debugging, the editor will be unresponsive until you hit the play button to resume execution.

**Comment by bobrocke** [comment]
I get this:

![open-a-terminal - atom](https://cloud.githubusercontent.com/assets/2962426/7971052/1545c39a-0a10-11e5-9b59-c3faf738c2a9.jpg)

**Comment by bobrocke** [comment]
Resuming execution completes the command and freezes the editor.

**Comment by benogle** [comment]
That looks right. Does the command freeze the editor without the debugger statement?

Not sure why breakpoints are not working. They definitely work for me.

**Comment by bobrocke** [comment]
Without the debugger statement the code runs though without stopping and the editor is not frozen.

**Comment by bobrocke** [comment]
Should I download a fresh, up-to-date, copy of Atom and reinstall it? Maybe all the patches have messed it up for me somehow?

**Comment by bobrocke** [comment]
If I try it in safe mode, to check for package interferences, my package won't load either. Is there a manual way around?

**Comment by benogle** [comment]
Can you try breaking on something in the atom code? open in `atom --safe`, then pick some code in atom's source, maybe an activate method on some package. Set a breakpoint and see if it stops.

**Comment by bobrocke** [comment]
Yes, I can get Atom to stop on a breakpoint somewhere in the core source.

**Comment by benogle** [comment]
Ok cool, does it happen not in safe mode on the same line? In your code, can you get it to stop at package activate method e.g. set the breakpoint then reload?

**Comment by bobrocke** [comment]
In safe mode (which I though disabled packages, but I guess not), It still skips my breakpoint but does stop on the debugger statement.

In safe mode, I think it's breaking on the breakpoint. I need to try it again a couple more times.

But if it's safe mode that allows it, what does that tell me?

**Comment by bobrocke** [comment]
But it still freezes the editor pane on continue.

**Comment by mark-hahn** [comment]
> But if it's safe mode that allows it, what does that tell me?

It says some package is breaking Atom.  Try removing packages you don't
need.  My package `package-cop` can help you do that (if you can get past
the horrible UI).

**Comment by bobrocke** [comment]
OK, I must have gotten confused somewhere. In safe mode I can break on breakpoints, and continue without freezing, in Atom's core code. But in safe mode, my package is not available (I don't know what I did before).

So, can I test my package in safe mode somehow?

Or must we conclude the problem is a package that I have to find and get ride of?

**Comment by bobrocke** [comment]
I back-tracked.

Now I have my package files in a folder that is sym-linked into ~/.atom/packages. So there should be only one .js file.

Now I:
Opened Atom in normal mode
Selected the "open here" command from the contextual menu to load the file
The command executed as normal
Opened the Dev Tools to sources and cmd-P searched for and open my .js file
Set a break point in the "open here" command
Selected the "open here" command from the contextual menu
The debugger stopped on the debugger statement and jumped over the breakpoint.

It looked like this:

![](https://virtual-host-discourse.global.ssl.fastly.net/uploads/github_atom/original/3X/0/b/0bd643b487b580e11e0bc08c8b13a6653c463508.jpg)
![open-a-terminal - atom](https://cloud.githubusercontent.com/assets/2962426/7972366/c17a90a6-0a19-11e5-81ca-a6a07dd4f9c4.jpg)

When I continued, the command completed and the editor was frozen.

**Comment by bobrocke** [comment]
OK, I've got to get back into this and figure out what's wrong. Not being able to properly use the debugger is a showstopper for me. This is Atom 0.208.0 running on Mac OS X 10.3.3.

If I disable all my packages, what, within Atom, would make a good test target for the debugger?

**Comment by mnquintana** [comment]
@bobrocke Maybe a core package like settings-view or tabs?

**Comment by bobrocke** [comment]
So, I went back to square one and used the package-cop to disable all my packages except @lee-dohm's Tabs-to-Spaces package and the package-cop. I quit Atom and then:

- Launched Atom using atom --dev
- Opened the Developer Tools
- Switched to the Sources tab
- Executed the tabify command to ensure the package was loaded
- Found the tabs-to-spaces.coffee file by searching in the list after Cmd+P
- Set a breakpoint in the tabify command on line 13: `this.editor = editor != null ? editor : atom.workspace.getActiveTextEditor();`
- Executed the tabify command from the context menu in the editor pane

There was a "flash" in the debugger, but execution did not halt. The editor pane froze with the cursor not blinking and unresponsive to clicks. The tree view and debugger panes still accepted clicks.

What could be going on here?

**Comment by bobrocke** [comment]
I'm still having the debugger problem even with v1.0.0. Dang!

**Comment by pamtbaau** [comment]
And you're not the only one. Debugger doesn't break at breakpoints and editor freezes. (v1.2.4)

Have you been able to solve the issue in the meantime?

**Comment by bobrocke** [comment]
@pamtbaau I still have the problem. The irritating thing is I can't build a clear enough test case to definitively replicate the problem for the developers. :(

**Comment by pamtbaau** [comment]
@bobrocke Just played some more with the debugger. Ticked the `Pause on Exceptions` to see if any exception might happen in my code. Guess what...

If I `View/Reload`, tick the `Pause on Exceptions` and start my package, the debugger will kick in on some exception and after that, my breakpoints are hit too...

**Comment by bobrocke** [comment]
@pamtbaau I've been using the debugging tools in PhpStorm for my project. If I work on any more Atom packages, I guess I'll see if it's fixed, then.
