### ISSUE TITLE
Sometimes Japanese file (UTF-8) gets garbled

### ISSUE THREAD

**Issue by kyoh86** [atom/atom#7076]
Sometimes, Japanese file (UTF-8) gets garbled.
Maybe that arises when I replace strings that contains Japanese charactors.

ref:
http://yogoma.hatenablog.com/entry/2015/04/20/043907 (JP)

"���"

**Comment by freed00m** [comment]
I have no jap charakters also in UTF-8.

I didn't choose any font family in settings.

![screenshot](https://cloud.githubusercontent.com/assets/9461698/8187455/11ce610a-1450-11e5-8b05-4bbc9e8ded53.png)

for example this 
"TITLE_LOST_NEW": "新遺失",
"TITLE_LOST_EDIT": "遺失修正",
"TITLE_LOST_DETAIL": "遺失詳細",
"TITLE_LOSTS_PAIRS": "対で遺失",
"TITLE_LOSTS_MY": "個人の遺失",
"TITLE_LOSTS": "遺失",

**Comment by ginlime** [comment]
I encountered the same issue.
This problem makes me so irritated when many files gets garbled.

**Comment by izuzak** [comment]
@kyoh86 This sounds like a duplicate of https://github.com/atom/atom/issues/6160 and https://github.com/atom/atom/issues/6214. Can you check those issues, especially the advice on changing the font?

@freed00m Not sure if that's the same problem. Can you open a new issue and provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues), and also check if you can reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
