### ISSUE TITLE
Enable packages to intercept click events on the editor

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#7082]
Currently, we don't have a good story for enabling packages to handle click events in the editor, that I know of. How should we do this?
- One idea is to enable packages to register click event handlers for the lines and the gutters. For every click, their handler would be invoked. They would need a way to tell us not to continue processing the event. Do they call `stopImmediatePropagation` on the event? Return a boolean from their handler?
- @maxbrunsfeld mentioned in #6843 something even more general based on commands. Max if you have more thoughts on that maybe you could edit this and add them here?

**Comment by jssln** [comment]
One thing to add is it would be nice to expose some methods for translating clicks to Atom-specific information. For example, translating the mouse coordinates to a screen line number.

**Comment by russlescai** [comment]
I agree, a function to translate pixel position into a cursor position would be very useful for my atom-touch-events package.

I am still yet to work out how to do that accurately.

**Comment by nathansobo** [comment]
@jssln There's a private method, `screenPositionForPixelPosition` on `TextEditor`. I don't want it to be public on the model because it shouldn't be called when the editor isn't on screen. But we could add a public method to the view that delegates to it. If you want to open a PR with that, would be an easy merge.

**Comment by jssln** [comment]
cool, https://github.com/atom/atom/pull/7144

**Comment by jssln** [comment]
It seems `screenPositionForMouseEvent` (https://github.com/atom/atom/blob/dac39bdcd5a14cc227d89f1ecc63d4dad8306fe0/src/text-editor-component.coffee#L763) would be more convenient to use. Thoughts on exposing that?

**Comment by russlescai** [comment]
Yeah I use screenpositionformouseevent when handling tap events using atom-touch-events package.

It would be great to be exposed publicly.

**Comment by russlescai** [comment]
I could create a PR to create a public TextEditorView.screenPositionForEventPixelPosition which converts a clientX/Y to a Point row/column.

Would that be an option?

**Comment by nathansobo** [comment]
@jssln @russlescai I'm definitely on board for adding a public method like this. Struggling a bit with the name. The existing name (and the concept expressed in the method itself) feels a little weird.

I like where @russlescai is going with the "event pixel position" idea. What about  `TextEditorElement::screenPositionForClientPixelPosition`. It would take a hash with `top` and `left` values and assume the need to normalize relative to the scroll position like `screenPositionForMouseEvent` does.

Come to think of it, with tiled rendering I wonder how much sense the existing `pixelPositionForScreenPosition` method makes anymore. We no longer scroll the entire content as a single GPU layer, making absolute pixel positioning relative to the global content quite a bit less useful.
