### ISSUE TITLE
Require just lsb-core in rpm specfile, not whole lsb

### ISSUE THREAD

**Issue by kparal** [atom/atom#7096]
In #6988 the rpm spec file got changed to:
```
Requires: lsb 
```
However, that pulls the *whole* lsb package, including all submodules. On Fedora 21, this pulls:
```
redhat-lsb                   
redhat-lsb-core              
redhat-lsb-cxx               
redhat-lsb-desktop           
redhat-lsb-languages         
redhat-lsb-printing          
redhat-lsb-submod-multimedia 
redhat-lsb-submod-security   
```
and those packages in turn pull a lot of other dependencies. That seems to be completely unnecessary. IIUIC, you just need `lsb_release` to be present, nothing else, so just the lsb core module.

Please adjust this to:
```
Requires: lsb-core-noarch
```
That should ensure that only lsb core module is required, nothing else. I tested this in Fedora 21 (`sudo yum install 'lsb-core-noarch'`) and in OpenSUSE 13.2 (`sudo zypper install 'lsb-core-noarch'`) and it seems to work just fine.

Thank you.

**Comment by mnquintana** [comment]
Thanks for the heads up! I'll change this shortly.

**Comment by kparal** [comment]
Thanks, I'll try the next build :-)

**Comment by kparal** [comment]
Looks great, atom dependencies are no longer excessive.
