### ISSUE TITLE
"Atom quit unexpectedly."

### ISSUE THREAD

**Issue by alex** [atom/atom#7097]
I just upgraded Atom to "v0.205.0", and now every time it starts up it crashes. This is OS X. 

I'm not sure how to get better logging or tracebacks.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* What version of OS X are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by alex** [comment]
`atom --safe` produces the same issue, OS X 10.9.5. I'll review teh Debugging document now.

**Comment by alex** [comment]
The Debugging document seems to refer primarily to graphical tools, this crash occurs before any UI elements are visible.

**Comment by alex** [comment]
https://gist.github.com/alex/f93000ef7b3624798f31 is the crash log

**Comment by ashrayjain** [comment]
Facing the same issue with 0.206.0 on OS X 10.10.3

**Comment by ashrayjain** [comment]
I downloaded the v0.206.0 release and replaced my Atom.app with the new one. Atom seems to be back to normal after this.

**Comment by damieng** [comment]
v0.206 is off the radar now. If you have upgrade issues with newer builds please file new bugs with those version details.
