### ISSUE TITLE
Toggle Soft Wrap fails without text cursor in editor

### ISSUE THREAD

**Issue by nscaife** [atom/atom#7098]
Steps to reproduce:  Atom 0.205.0, Windows 8.1
1. Open a document but do not click inside the editor
2. Select View->Toggle Soft Wrap

Expected behavior: Soft wrap enables for the active document
Actual behavior: Nothing happens and no indication is given that the operation failed

This problem also occurs when changing tabs if you don't click inside the editor before selecting Toggle Soft Wrap.

**Comment by lpommers** [comment]
What would the expected behavior be if you have many editors open in split panes, but none are selected and you Toggle Soft Wrap? That none would be effected? Or the most recently active editor? Or all open editors?

**Comment by nscaife** [comment]
If the action is ambiguous, I think the menu option should be greyed out.  The main problem is that the option is there, clickable, but nothing happens.

**Comment by nscaife** [comment]
On opening a document, shouldn't that document be the active document?

**Comment by lpommers** [comment]
I agree with you for the most part.

I'm thinking that Toggle Soft Wrap should always soft wrap the active text editor (even if there is no cursor, it's the active editor) no matter how many panes are open, otherwise it should be greyed out (e.g. if the settings are open).

**Comment by Moisan** [comment]
Same thing happens if the cursor is in the "Find text" region. In this case, the active document is clearly the one already opened.
