### ISSUE TITLE
Linux Zip

### ISSUE THREAD

**Issue by jamesward** [atom/atom#7102]
Please add a Linux zip distribution to the releases.  This will allow Atom to be distributed like the Windows & Mac versions... Just download a zip, extract, and run.

**Comment by v3ss0n** [comment]
:+1:  general linux zip would be cool.

**Comment by Calinou** [comment]
:+1:, most useful for obscure distributions or installing without admin rights, in case you already have the dependencies installed (or we could make a statically linked version?).

However, consider using .tar.xz for smaller file size.

**Comment by w1748587889** [comment]
right

**Comment by matdecac** [comment]
+1

**Comment by v3ss0n** [comment]
yes , Distro specific packages aren't linux :)

**Comment by 120011676** [comment]
+1
