### ISSUE TITLE
'copy' keyboard shortcut should not copy empty space

### ISSUE THREAD

**Issue by DavidAwad** [atom/atom#7103]
It's too frequent that someone might accidentally hit the 'c' key instead of the 'v' key when pasting in atom. 

instead of copying empty space, the copy shortcut should simply not do anything. 

I can write the pull request myself if someone can point me in the right direction, either way if we could  improve this very annoying problem it would be great!

**Comment by benogle** [comment]
This was a deliberate decision. cc @maxbrunsfeld. I admit, I dislike it as well, but many people wanted this behavior.

**Comment by mnquintana** [comment]
@benogle This seems like an ideal candidate for a config option though

**Comment by DavidAwad** [comment]
A config option would be perfect!

**Comment by maxbrunsfeld** [comment]
Just to clarify, in general it copies the line under the cursor, not empty space. I'd be ok w/ a config option.

**Comment by DavidAwad** [comment]
So how would I implement this? I have no problem submitting a PR for it, it seems like a simple request.

**Comment by vemv-kantox** [comment]
I second this issue. People actually leveraging the current behavior may like a similiar but different key-binding: `command-shift-c` (free by default) could copy the current line regardless of selection.

**Comment by maxbrunsfeld** [comment]
> People actually leveraging the current behavior may like a similar but different key-binding.

This is good idea. @DavidAwad I think that the best way to do this would be to add a new command, `editor:copy-selection` that would write to the clipboard *only* if text were selected. That way, users who prefer that behavior could simply add this to their keymap:

```coffee
'atom-text-editor':
  `command-c`: `editor:copy-selection` # mac os
  `ctrl-c`: `editor:copy-selection`    # linux and windows
```

**Comment by lpommers** [comment]
I've playing with this locally and just looking for some input. For me I think it would be nice if copy didn't work unless something was selected *or* the cursor is at the beginning of the line. In that case I think I would find it useful if `copy` copied the line. Any thoughts?

**Comment by jschroeder9000** [comment]
For me, I would prefer copy to do nothing if nothing is selected, even if the cursor is at the beginning of the line.  If I accidentally hit ^c instead of ^v, I don't want it to blow away my clipboard contents, even if the cursor is at the beginning of the line.  Nothing selected => nothing to do.

**Comment by MichaelJCole** [comment]
Thanks so much!  This drove me mad.  Here's how to implement it:

Edit -> Preferences -> Keybindings -> Click link at very top "your keymap file"
This should open a file in the editor.

Paste this:
```
'body':
  'ctrl-c': 'editor:copy-selection'
```

Close and open Atom.

**Comment by MichaelJCole** [comment]
Unfortunately, this seems to have stopped working.  The command pastes at the beginning of the line, instead of the cursor.

**Comment by sinisarudan** [comment]
Still not solved?? :( Not by a simple config option as suggested here ...?
This
```
'atom-text-editor':
  'ctrl-c': 'editor:copy-selection'    # linux and windows

```
solution doesn't seem to work any more (ver 1.22.1), as worked before

**Comment by sinisarudan** [comment]
the suggested solution doesn't work in newer versions (e.g. ver 1.22.1), as worked before, because of different coding of the `keymap.cson` file:
but these steps work:

Atom -> Preferences -> Keybindings -> Click link at very top "your keymap file"
This should open a `keymap.cson` file in the editor.

Paste this:
```
'body':
  'cmd-c': 'editor:copy-selection' # mac os
  'ctrl-c': 'editor:copy-selection'    # linux and windows

```
(I tested it on Mac, if it doesn't work on Win, you might need to adjust 'ctrl-c' code)

P.S. if the internal coding of the `keymap.cson` file changes over time, you can go to 
Atom -> Preferences -> Keybindings
and then you find there an entry with 'Keystroke' equal to 'cmd-c' and Selector equal to 'body'.
You should copy the code of this settting by clicking on the icon on the left of that entry-row, and use it as a model for your entry in  `keymap.cson`

Here is screenshot (for Mac) of the above-writen:
<img width="575" alt="screen shot 2017-11-20 at 11 36 25" src="https://user-images.githubusercontent.com/1769627/33014283-1f5f0ff6-cde7-11e7-9fe2-e1e63ba06572.png">

**Comment by vlad1777d** [comment]
I think, that there's no any use case for copying empty lines.
If somebody needs empty line - he could just press enter. It's much simpler than copying empty line than pasting it.

Also empty line is often copied by mistake, when wanted to press "ctrl + v".
So such behaviour is not just neuter, but harmful.

And modifying this in settings... Strange decision. Probably it would be better to leave old behaviour by default and such strange option may be turned on only by need.

**Comment by MichaelJCole** [comment]
Hey @vlad1777d this issue is closed, so won't get any traction.  You might have more luck if you open a new issue and reference this one...
