### ISSUE TITLE
Automatic build of 32 bit RPM

### ISSUE THREAD

**Issue by fusion809** [atom/atom#7107]
Hi, I've asked David Hengeveld (who wrote the [blog post][1] on Linux builds of Atom) about 32 bit Atom RPMs for Fedora and he said that it should be fairly simple for you's to automate the generation of 32 bit RPM builds for each new Atom release, as he pointed to this [coffee script][2] that is presently used to make 64 bit RPM builds for Atom. So I'm here to ask you's when you get the time. 

[1]: http://blog.atom.io/2014/11/05/linux-packages.html
[2]: https://github.com/atom/atom/blob/f585b5bb126056b16e9534864df45e90b7f7d50a/build/tasks/mkrpm-task.coffee#L19-L22

**Comment by 50Wliu** [comment]
See also #6252.

**Comment by mnquintana** [comment]
Closing in favor of https://github.com/atom/atom/issues/6252 – feel free to subscribe there for updates!
