### ISSUE TITLE
auto close html elements

### ISSUE THREAD

**Issue by lilnate22** [atom/atom#7108]
as a nice HTML editor, it would be nice if atom could auto close nested HTML elements

i.e:

```
<div>
  <span></span>
```

when user types "</ "

it will auto close `<div>`

This is very useful for angular dev, when adding directives.

Similar functionality to Brackets.io

**Comment by Tribex** [comment]
There are a myriad of plugins that perform this function, just so you know. This issue is still valid if the devs want to add the feature to the core. :)

**Comment by lilnate22** [comment]
@Tribex , the only one I have seen is autoclose-html:
https://atom.io/packages/autoclose-html

but this only does it inline, i.e <div> </div>

it will not handle nested (like brackets does):

<div>
    <span></span>

</  


will not be completed

**Comment by izuzak** [comment]
The bracket matcher package implements something very similar -- a "Close Tag" command which auto closes the right tag at the place where your cursor is (even has a keybinding).

Here's it is in action:

![closetag](https://cloud.githubusercontent.com/assets/38924/8007220/a8e55602-0b9a-11e5-8653-cf3f61231e66.gif)

Does that help with auto-closing tags? If you'd still like the exact behavior you described in the issue -- I suggest you use a community package (and open an issue in one of those) or open an issue on the bracket matcher package for that feature.
