### ISSUE TITLE
Invalid auto indentation of HTML after pasting when no closing tags present

### ISSUE THREAD

**Issue by adambuczynski** [atom/atom#7109]
Consider several lines of plain text which you want to encapsulate with `<p>` tags. If you start with the first line, add a `<p>`, then copy paste it and go forward line by line, the following happens:

![Indentation](http://zippy.gfycat.com/AdorableLeadingAmericanindianhorse.gif)

Presumably this is because Atom thinks the next `<p>` tag should be indented for some reason, if there are no closing `</p>` tags yet. 

When I add in the closing `</p>` tags first, this doesn't happen. It also doesn't happen when I paste non-HTML onto the lines. 

Can this behavior be turned off somehow without turning off auto indentation on paste?

This is with Atom version 0.206.0.

**Comment by Tribex** [comment]
Same happens with Jade, not sure if its an internal issue or not.

**Comment by adambuczynski** [comment]
Seems to be fixed now
