### ISSUE TITLE
The atom window remains transparent on opening

### ISSUE THREAD

**Issue by auag92** [atom/atom#7112]
![atom_2](https://cloud.githubusercontent.com/assets/10386906/8000393/a4f09714-0b77-11e5-8c93-564cdf6fc513.png)

I recently installed atom on my ubuntu 14.04 system. On starting atom the window remains transparent.

**Comment by izuzak** [comment]
@auag92 Can you clarify how _exactly_ you installed Atom and which version of Atom you installed? Can you try downloading the official package from https://github.com/atom/atom/releases/tag/v0.206.0 and using that to install (after removing the previous installation)?

**Comment by vramana** [comment]
@izuzak I am @auag92 's friend. He had the same problem with with a much oder version of atom. I asked him to remove atom using `dpkg -r` and remove `.apm` folder. Then I made him do a clean install of Atom v0.206.0.

**Comment by izuzak** [comment]
> Then I made him do a clean install of Atom v0.206.0.

@vramana And how exactly did you install that version Atom?

**Comment by vramana** [comment]
Downloaded the `.deb` file from latest releases page and `dpkg -i`

**Comment by 50Wliu** [comment]
Are you sure the Atom window isn't just a 1x1 window or something?  That has happened before and it looks like there's a very thin vertical bar going down the terminal in the image.

**Comment by mehcode** [comment]
Directly after opening your invisible atom; try hitting <kbd>Ctrl-Alt-Numpad 5</kbd> or <kbd>Ctrl-Super-Up Arrow</kbd>

**Comment by auag92** [comment]
The ctrl-Alt-Numpad 5 option works. Thanks

**Comment by izuzak** [comment]
Thanks for the assist, @50Wliu and @mehcode -- closing this in favor of https://github.com/atom/atom/issues/5938. :dancers:
