### ISSUE TITLE
"Create issue on the xyz package" and "Copy to clipboard" not working

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#7113]
When I get an error (that red warning that shows on the upper right side of Atom) and I try to interact with it by either clicking on the "Copy to clipboard" or the "Create issue on the xyz package" buttons, nothing happens.

**Comment by mnquintana** [comment]
Thanks for the report! This is a duplicate of https://github.com/atom/notifications/issues/70 – please subscribe there for updates.
