### ISSUE TITLE
Do you know how to set syntax of file without saving it?

### ISSUE THREAD

**Issue by vdzundza** [atom/atom#7115]
I want to save code syntax for highlighting by key shortcut? How can I do it?

**Comment by izuzak** [comment]
You can do that with the `grammar-selector:show` command, which is [bound to `ctrl-L` by default](https://github.com/atom/grammar-selector/blob/master/keymaps/grammar-selector.cson).

Let me know if I misunderstood your question, and please provide more details about what you want to do exactly.

**Comment by 50Wliu** [comment]
All this time I've been using <kbd>Ctrl+Shift+L</kbd> thinking that was how to enable it...whoops :grimacing:.
