### ISSUE TITLE
Switch tab: focus editor

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#7116]
If I click a tab to switch between files, I would like the keyboard focus to be set into the editor with the file open, preferrably with the cursor where I left it before leaving.

A click on the tab now sets focus on the tab. (Though there's nothing much to do with keyboard input there...)

**Comment by stijnsanders** [comment]
For your information: I've seen a blog post somewhere in the wild advising to use a sequence of <kbd>Ctrl-Z</kbd> and <kbd>Ctrl-Y</kbd> to have the cursor jump to the previous location. With a presumed click in the editor window, that's a three-step operation to circumvent missing behaviour!

**Comment by izuzak** [comment]
Yeah, this is a known problem -- see https://github.com/atom/atom/issues/6662. Closing this in favor of that, thanks for the report. :+1:
