### ISSUE TITLE
FTP Package 

### ISSUE THREAD

**Issue by di48l069** [atom/atom#7117]
Hi there can you guys bring out a package where you can connect to FTP and on save it will update your files.

I know there are already 3 packages out there but i'm not a big fan of them i wondering can atom team create this package?

**Comment by batjko** [comment]
I don't know what the problems with those are, but have you opened an issue on any of the existing packages to try and improve them first?

**Comment by di48l069** [comment]
@batjko Never mind found a great one :+1:
