### ISSUE TITLE
Error opening new windows

### ISSUE THREAD

**Issue by djmtype** [atom/atom#7121]
Sorry if this is a duplicated entry… 

Each time I open a new window, I receive: 

```
Failed to load /Users/me/.atom/init.coffee
Cannot read property 'eachEditorView' of undefined
```

Atom Version 0.206.0
No 3rd party packages active, default Atom theme.

**Comment by mnquintana** [comment]
It looks like there's an error in your Init File – if you comment it out, that should resolve this error. Let me know if that doesn't work for you!

**Comment by djmtype** [comment]
@mnquintana thanks!
For some reason, it didn't like this function in my Init file. I've had Atom installed for awhile now, checking on its progress. I don't recall if this came with Atom or was added by me based on some post or comment I read. I'm not sure what it does exactly (ha!). It looks like it sets the workspace to `inline-block`, otherwise it displays as `block` after a 50ms timeout…? 

```
atom.workspaceView.eachEditorView () ->
el = document.getElementsByClassName("workspace")[0];
el.style.display = "inline-block";
setTimeout( ->
el.style.display = "block";
, 50)
```
