### ISSUE TITLE
Pane with code Greyed out

### ISSUE THREAD

**Issue by Stevo5o** [atom/atom#7122]
Not sure what I have done wrong here, any help would be great.

![atomerror](https://cloud.githubusercontent.com/assets/3177131/8008973/6af00286-0b9d-11e5-8a05-98329ac2cbc5.jpg)

**Comment by Stevo5o** [comment]
More info: I open Atom and this is what I see. 
Is it maybe a setting that I have accidental set?

I can select the text and edit it but it's just very hard to read, as you can see from the screen.

**Comment by mnquintana** [comment]
Have you followed the steps in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)? Can you reproduce this in safe mode? (`atom --safe`)

**Comment by Stevo5o** [comment]
Nope will try now, thanks.

**Comment by J4G-** [comment]
I have this same problem! It appeared after a crash! I tried reinstalling, restarting, all of it. No luck. :(

**Comment by maxbrunsfeld** [comment]
@J4G- can you list your installed packages?

@J4G- @Stevo5o You might try selectively disabling packages to narrow down the list of packages that could be causing this.

**Comment by J4G-** [comment]
I've disabled all of my packages without success.

-----Original Message-----

**Comment by maxbrunsfeld** [comment]
@J4G- so you're seeing this when you run `atom --safe`? Can you try temporarily getting rid of your Atom storage directory?

```
mv ~/.atom/storage ~/.atom/storage.bak
```

**Comment by J4G-** [comment]
I'm actually not seeing the problem with atom --safe either, but disabling all of my community-installed packages with a regular open doesn't help.

I'm on Windows and can't find the Atom storage directory in AppData/Local/ where the binary is.

**Comment by mnquintana** [comment]
@J4G- It could be that a community package isn't properly deactivating itself when you disable it – have you tried restarting after disabling all your community packages?

**Comment by chuckcarpenter** [comment]
I'm having this in both 0.206 and 0.207. I uninstalled all my community packages and themes, but still get 
```
Failed to load /Users/ccarpent/.atom/init.coffee
Cannot read property 'eachEditorView' of undefined
```

**Comment by mnquintana** [comment]
@chuckcarpenter `init.coffee` is your custom Init File – it means you added something to it that uses a deprecated Atom API that was removed in 0.206.0. If you want to play it extra safe you can comment out the whole Init File; otherwise, you can search for the line(s) that use `eachEditorView`.

@J4G- @Stevo5o Do you have anything in your `init.coffee`?

**Comment by chuckcarpenter** [comment]
@mnquintana thanks! That was the magic.

**Comment by J4G-** [comment]
@mnquintana The issue was resolved after I disabled seti-monokai, which has deprecated selectors, per my edit above. Thanks for your help. :)

**Comment by Stevo5o** [comment]
Thanks guys for the help here. I am changing over to Visual Studio Code as of today. I might come back to Atom when it's a bit more stable. I still really like Atom but..

**Comment by mnquintana** [comment]
@Stevo5o To be clear, this was *not* a problem with Atom core, but a problem with a community package you had installed. That in no way means that Atom is less mature. VS Code would face similar challenges if it had the capacity for community extensions, which it currently does not.

**Comment by Stevo5o** [comment]
OK Sorry your right, will edit my comment now.
