### ISSUE TITLE
[Windows] Update mechanism menu text

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#7128]
The dropdown menu entry stays at "Checking for Update" and then switches to "Restart to Update" never showing "Downloading Update" in between.

**Comment by 50Wliu** [comment]
This was definitely fixed before - perhaps it regressed?

**Comment by 50Wliu** [comment]
Never mind: the previous bug was that it would only show "Downloading Update" :frowning:.

**Comment by 50Wliu** [comment]
Not too sure, but it looks like [this line](https://github.com/atom/atom/blob/11d1823a37a6eeb2747756ede9dab8d075631cd7/src/browser/auto-updater-win32.coffee#L59) might belong [here](https://github.com/atom/atom/blob/11d1823a37a6eeb2747756ede9dab8d075631cd7/src/browser/auto-updater-win32.coffee#L16) or [here](https://github.com/atom/atom/blob/11d1823a37a6eeb2747756ede9dab8d075631cd7/src/browser/auto-updater-win32.coffee#L53) instead.
