### ISSUE TITLE
Selection no longer visible

### ISSUE THREAD

**Issue by warethis-dev** [atom/atom#7131]
Atom 0.206.0 knows that a selection is made, shown by the character count at the bottom of the window, however there's no visible highlighting - I tried a number of syntax themes - to show what is selected. I'm using Linux Mint 17.1 with Cinnamon, 32-bit.

**Comment by nathansobo** [comment]
If you have time and interest, could you try building #7127? There's a bug on that branch still but I'm curious if it restores your selections. I think it might.

**Comment by warethis-dev** [comment]
I'll give it a shot this evening and let you know how it goes

**Comment by warethis-dev** [comment]
Sorry, I gave it a look but I have no idea how to do that.

**Comment by nathansobo** [comment]
That's okay. Can you fall back to a previous release for a bit and I'll ping you on this issue when a new release is out with what I hope will be a fix? If it isn't then we can go deeper and figure it out.

**Comment by warethis-dev** [comment]
ok thanks

**Comment by warethis-dev** [comment]
I was never able to find a previous release for my 32-bit linux mint. I was hopeful when I got notified of the 0.207 update this morning but no joy.

**Comment by stefan-kern** [comment]
i have the same issue, selection highlight is invisible but otherwise still functional.
it doesnt work for several themes e.g. "spacegray light" but does work for "one light"
i'm wondering if its a theming issue, but i dont know what selectors i can try on my stylesheet to see if i can fix it.
help is much appreciated

**Comment by warethis-dev** [comment]
YES! Thank you for replying here @stefan-kern! I use Xeta syntax theme 
and with 0.206 I had switched around to about 13 different syntax themes 
to see if one worked, none did. Now, with 0.207 still no highlighting 
with Xeta but it works with One Light and One Dark and possibly others 
so there's hope! This has been slowing me down for days, thanks again!

**Comment by stefan-kern** [comment]
if it helps: i'm using Ubuntu 14.04 with unity. atom v0.207

**Comment by warethis-dev** [comment]
I've now gone through 20 different syntax themes, most of which work with 0.207 but didn't with 0.206. I'm going to close this issue now as it seems more an issue with the theme packages than the editor.
