### ISSUE TITLE
The effect of Ctrl+k takes 1 or 2 seconds to appear

### ISSUE THREAD

**Issue by vincentisambart** [atom/atom#7136]
Running Atom 0.207.0 on OSX Yosemite.

Ctrl+k cuts the text from the caret to the end of the line (or the end of the line itself if you are already at the end of the line).

However, with the current Atom 0.207.0, when cutting text with Ctrl+k, the text takes 1 or 2 seconds to disappear from the screen. I would expect it to be instantaneous (like when you select text to the end of the line and cut it).

**Comment by 50Wliu** [comment]
Please open the Keybinding Resolver (<kbd>Cmd+.</kbd>) and see what it picks up when you type <kbd>Ctrl+K</kbd>.  Thanks!

**Comment by vincentisambart** [comment]
Oops indeed no problem indeed when in safe mode.
The binding resolver seems to say it's because of term2.
