### ISSUE TITLE
Running Atom from shell fails on Windows

### ISSUE THREAD

**Issue by James-Ko** [atom/atom#7141]
**Version:** Atom v0.207
**OS:** Windows 8.1

Hello. Recently, when I tried to run `atom somefile.txt` from [Git for Windows](https://github.com/git-for-windows/git/releases), I got an error in the `atom` script that said `No such file or directory`. When I opened the `atom` script file, I saw this:

    "$0/../../app-0.204.0/resources/cli/atom.sh" "$@"

Realizing that `$0` should instead have been `$(dirname $0)` instead, I replaced it and tried again. I also found this problem in the script it pointed to (atom.sh).

The problem is that **when Atom updates it erases the fix**, which is why I filed this bug report.

As someone [in the forums](https://discuss.atom.io/t/running-atom-from-shell-doesnt-work-on-windows/17496) noted, `atom.cmd` works fine.

Image:

![bug](https://cloud.githubusercontent.com/assets/9159214/8021375/8a9ab616-0c6b-11e5-9efc-c7b1511a5f7b.png)

**NOTE: This applies to apm and the script it points to, as well.**

**Comment by kevinsawicki** [comment]
I believe this has been fixed on master now and will be included in the next Atom release, 0.209, thanks for reporting it.

**Comment by brutalcrozt** [comment]
I had same issue.
Windows 8 64bit, atom v 1.4.2.
