### ISSUE TITLE
  -webkit-font-feature-settings: "calt" on, stopped working

### ISSUE THREAD

**Issue by larsenwork** [atom/atom#7142]
Any recent code change that could explain this? The font with contextual alternates continues to work fine in other programs and worked fine i Atom just a couple of hours ago.

**Comment by larsenwork** [comment]
I'm using contextual alternates for the ligatures in https://github.com/larsenwork/monoid

**Comment by izuzak** [comment]
cc @nathansobo @as-cii

**Comment by as-cii** [comment]
That's interesting. Thank you for reporting this, @larsenwork!

As far as I understand, this shouldn't be related to the recent legibility issue: @larsenwork, would you be willing to check out if this actually broke in `0.207` (e.g. simply download the previous version and confirm it was working)? Also, you may want to rebuild **master** now that #7127 was merged: I don't think it's related but it may be worth giving that a try.

@nathansobo: could this be caused by a theme (or any CSS for that matter) which explicitly opts out contextual alternates?

I'll try to investigate what's causing this problem in the meantime and report what I find out here (probably the next week, as my schedule is quite busy as of this one).

Thanks! :bow:

**Comment by larsenwork** [comment]
@as-cii thanks for the detailed reply - I will try previous version and report back on my findings:)

**Comment by larsenwork** [comment]
Ok this is weird - without changing the font: 
207 -> not working -> delete 207 -> install 206 -> works -> press install update and relaunch in the menu -> still works

I haven't changed anything else (themes etc.)

So I can't reproduce the error and since it's currently working I'm closing this. Will reopen should the problem reappear.

**Comment by larsenwork** [comment]
Hmm...that was too quick I'm afraid. Didn't work again this morning when I started atom again and reverting to 206 didn't fix it this time around. For anyone else who wants to try

styles.less
```
*{
  -webkit-font-smoothing:antialiased;
  -webkit-font-feature-settings: "calt" on, "liga" on;
}
```
font: http://larsen.work/monoid/

try typing e.g.
```
{5<=x&&y!==2}
```
it should look like this (from textedit on mac)
![screen shot 2015-06-09 at 09 47 18](https://cloud.githubusercontent.com/assets/3859425/8052978/aafb4e34-0e8c-11e5-9a70-962373228719.png)

**Comment by larsenwork** [comment]
I also disabled all community packages to ensure they weren't the culprit.

**Comment by izuzak** [comment]
Thanks for the additional details, @larsenwork. In your description of the issue you mentioned this:

>  worked fine in Atom just a couple of hours ago.

Would you be willing to try the last few versions of Atom and see which is the last version that works for you as expected? You already tested 0.207 and 0.206, so I think testing 0.205/4/3/2/1 would be enough. Version 0.200 was released 21 days ago, so it's probably a good place to draw the line?

**Comment by larsenwork** [comment]
@izuzak I'm not sure how testing older versions will help narrow down the problem as it worked yesterday with both 206 and 207 so the issue is more that it works very unreliably in current versions (I've tried reinstalling, disabling packages etc. to no avail). 

I only switched to Atom recently and began using contextual alternates a couple of days ago so I can't vouch for stability in the past.

**Comment by izuzak** [comment]
> I only switched to Atom recently and began using contextual alternates a couple of days ago so I can't vouch for stability in the past.

That was the context I was missing -- from your original issue description it sounded like this started happening recently, and you've been using Atom for a while.

**Comment by larsenwork** [comment]
Ah, yeah I've only used it a couple of weeks and the `calt` feature a couple of days - but it worked without problem in the beginning but now I can't even make it work. I'm sorry I can't provide a more detailed description than that:)

**Comment by larsenwork** [comment]
@as-cii any updates on this? I still can't seem to make it work - just tested the contextual alternates in chrome browser where it worked perfectly.

**Comment by simurai** [comment]
I tried to reproduce it like described in this comment: https://github.com/atom/atom/issues/7142#issuecomment-110263393

And in my case it seems to work fine:

![monoid](https://cloud.githubusercontent.com/assets/378023/8667010/4a8f0b94-2a34-11e5-9b17-df11e01e536c.gif)

Maybe platform related? I'm on OS X `10.10.4`, Atom `1.0.3(-6efb48d)`.

**Comment by larsenwork** [comment]
@simurai This is weird - it didn't work yesterday for me on 10.10.4 and 1.0.2 but now it does. Oh well, sorry for the misreport. Closing this :smile:
