### ISSUE TITLE
[Feature Request] A way to diagnose freezes

### ISSUE THREAD

**Issue by Stanzilla** [atom/atom#7148]
Similiar to timecop, I'd like something to diagnose and log the random freezes and lag problems that have been happening to me and a few friends on a random basis. If there is already something like that in place, please excuse and close me :)

**Comment by benogle** [comment]
There is nothing like that currently. It would be awesome to have. Not sure if it could be done in the application code. Maybe the browser process can watch the renderer processes for hangs?

**Comment by izuzak** [comment]
For diagnosing performance problems, check out [these docs](https://atom.io/docs/latest/hacking-atom-debugging#diagnose-performance-problems-with-the-dev-tools-cpu-profiler).

**Comment by Stanzilla** [comment]
@izuzak the problem with that is that you have to have something reproduceable to get anything out of CPU profiling. You could probably run with it enabled all the time but that's not really a solution. Most of the current hangs/freezes are totally random, that's why I suggested something like a watcher/cop feature that actively watches for hangs and records what happens at that moment.

**Comment by izuzak** [comment]
@Stanzilla Thanks for clarifying -- I was pointing out something you can use if the random lag is happening when you perform certain actions (e.g. they happen randomly when you scroll  or type, or happen every 5 minutes). If that's the case, you might try to force the problem by executing that action several time and take a snapshot. If they happen totally randomly and you noticed no patterns whatsoever, then the chances are lower that you'll be able to trigger the behavior while you're taking a snapshot.

**Comment by peterhal** [comment]
We are experiencing Atom hanging as well. Being able to get a JS stack on a hung Atom process would be extremely valuable.

**Comment by Stanzilla** [comment]
Still valid
