### ISSUE TITLE
C source code highlighting not functioning after macro definition containing > and parentheses

### ISSUE THREAD

**Issue by Sleepwalking** [atom/atom#7151]
Atom (and even github's markdown) only highlights the first line but not the second line for the following C code:
```c
#define a >b()
int c;
int d;
``` 
And after the second line everything is fine again.

Here's a more realistic senario:
```c
#define fmax(f, a, b) (f(a) > f(b) ? f(a) : f(b))
int c;
int d;
```

This bug only happens when there is one or more letter between `>` and `(`, including spaces but excluding tokens begining with numbers. For example these are going to trigger the bug:
```c
#define a > a b c d ()
int e;
int f;
#define a > a b12 c34 d56 ()
int e;
int f;
```
This is not going to trigger the bug:
```c
#define a > a b c 1d ()
int e;
int f;
```

Square brackets instead of parentheses would not trigger the bug:
```c
#define a > a b c d []
int e;
int f;
#define a > a b12 c34 d56 []
int e;
int f;
```

![issue](https://cloud.githubusercontent.com/assets/4531595/8023260/ba50b0a2-0d35-11e5-95f9-e9ae405ee21b.png)

Version of Atom editor: 0.204.0 on both Ubuntu 14 and Windows 7
This bug occurs even if all packages except core packages are disabled.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/language-c?

**Comment by Sleepwalking** [comment]
No, please move it. Thanks.

**Comment by mnquintana** [comment]
Yes that's what I meant – just close this and reopen it at atom/language-c. Thanks!
