### ISSUE TITLE
Tree view displays file as folder

### ISSUE THREAD

**Issue by GameplayJDK** [atom/atom#7152]
I just updated to version `0.207.0` and found this:

![screenshot_1](https://cloud.githubusercontent.com/assets/4069263/8023532/7f8e30fa-0d0f-11e5-829f-be2c20a013c5.png)

Somehow the `LAST_TODO` file (which is a file without an extension) is hows as a folder in my tree view. As such, I can't open it from there and need to use "File -> Open File..." to do so.
This also happens to other files (with extensions), as shown below:

![screenshot_1](https://cloud.githubusercontent.com/assets/4069263/8023552/8f29bccc-0d10-11e5-8f11-3d7b0583bf76.png)

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/tree-view?

**Comment by mnquintana** [comment]
This issue was moved to atom/tree-view#471
