### ISSUE TITLE
Little things missing from Vim ?

### ISSUE THREAD

**Issue by rififi** [atom/atom#7154]
HI !

First of all, I'm new to Atom. I discovered it yesterday. I would like to give it a chance, because it seems to be a wonderful tool.

For now, I'm trying to get back the stuff is set up over the years with Vim. I see 2 things for now:

 - The template ability: in Vim, you can set up a template for each type file. Ex: you can set up a template for python files. When you create a file with the command ```vim test.py```, test.py comes with some basic lines inside, like the shebang and the encoding. I've been looking around (maybe not enough), I found nothing about a similar stuff

- The sidebar: is it possible to display something else than a filebrowser in the sidebar ? Like a list of methods, the class, the attributes, etc ?

Anyway, congrats for developping such a great tool !

**Comment by 50Wliu** [comment]
For point 1: After opening a Python file you can type `env`, then <kbd>Tab</kbd> and the shebang should automatically show up.  Same thing with the encoding, except the snippet would be `enc`.

**Comment by rififi** [comment]
Yeah, ok...But I always import some important modules and paths, and add the "__main__" condition.

**Comment by andya9** [comment]
@rififi for number 1 there’s a package for this, it’s called [file-templates](https://atom.io/packages/file-templates)... but I prefer creating a custom snippet, so that when I press !+Tab my custom header is expanded with the cursor where i want it

for number 2, i think you are looking for [symbols-tree-view](https://atom.io/packages/symbols-tree-view); many other packages witch enance the tree view are available in the official repo

**Comment by izuzak** [comment]
Thanks for the suggestions, @rififi. I'd definitely recommend checking out the packages which @andya9 linked to, and other packages in the registry: https://atom.io/packages. If you have suggestions for one of the existing packages you'd consider using -- opening an issue on that package's issue tracker is the best way to start that discussion. :flags:

**Comment by rififi** [comment]
Ok, thanks everyone. I found almost everything I needed, now I'll be using Atom for a few days and see if it's a good replacement. Thank you :)
