### ISSUE TITLE
Restore session after install upgrade and relaunch

### ISSUE THREAD

**Issue by liuok** [atom/atom#7156]
When 'install upgrade and relaunch' atom can reload all opened files before.

Liu Jiang.

**Comment by freemanoid** [comment]
I've just tried to upgrade from 205 to 207 and after restart Atom haven't opened my 2 previous folders. I'm not sure whether it reopened any tabs/folders before though.

mac os

**Comment by petewalker** [comment]
Not sure the issue title is the most descriptive here.

I'm experiencing the same issue, though: After an update + relaunch, Atom doesn't restore your open windows / files.

Using Mac OS X 10.10.3 - just updated 207-208.

**Comment by mnquintana** [comment]
:+1: I have noticed this with Atom 0.207.0-0.208.0 too, although I've noticed it with a lot of previous version upgrades too.

**Comment by freemanoid** [comment]
> I have noticed this with Atom 0.207.0-0.208.0 too, although I've noticed it with a lot of previous version upgrades too.

I confirm the same incorrect behaviour.

Mac OS 10.10.3 , each upgrade between 0.193 - 0.208
