### ISSUE TITLE
Atom confuses "" and “” since last update

### ISSUE THREAD

**Issue by dyedgreen** [atom/atom#7161]
I had some issues with "" and “” since the last update. In some places Atom generated “” instead of "".

**Comment by thomasjo** [comment]
Are you able to reproduce in safe mode? Also, are you using OS X 10.10 (Yosemite) by any chance?

**Comment by dyedgreen** [comment]
Actually I am using OS X 10.10 (Yosemite)

**Comment by thomasjo** [comment]
Yosemite has this extremely annoying text substitution feature. It shouldn't really be active in Atom (I'm not affected by it). But it might be worth seeing if disabling *Use smart quotes and dashes* resolves the problem
![image](https://cloud.githubusercontent.com/assets/3622/8025757/95bd7c12-0d61-11e5-9b51-96fad80a0dd6.png)

I do believe the text substitution feature is not affected by that setting, but I'm not sure how to disable the problematic feature, per app (or globally).

**Comment by dyedgreen** [comment]
Okay, going to disable it :) Thanks!
