### ISSUE TITLE
Failed to save config.cson

### ISSUE THREAD

**Issue by juanscv** [atom/atom#7165]
Everytime i try to modify the editor UI like switch them or increase the font i get:

`EPERM: operation not permitted, open 'C:\Users\juan\.atom\config.cson'`

**Comment by 50Wliu** [comment]
Please make sure you have the correct permissions in the `C:\Users\juan\.atom` folder and `config.cson` (in other words, you can access them through Windows Explorer without entering a password, etc).

**Comment by juanscv** [comment]
So far I've attempted to zoom in/out and change syntax theme. Each attempt i get and everytime, I get
````
Failed to save config.cson
EPERM: operation not permitted, open 'C:\Users\juan\.atom\config.cson'
````

**Comment by batjko** [comment]
Try to rename the `.atom` folder (say '.atom_backup'), start atom, close it, then copy your old .atom content into your newly created `.atom` folder, and restart/reload.

Just a wild guess. But if something's wrong with your `.atom` folder, let's see if getting rid of it solves your issue.

**Comment by izuzak** [comment]
> Apparently the folder cannot be hidden on Windows, it was the only thing that I changed and worked.

@juanscv Was the folder hidden initially for you or did you hide it yourself? And does that mean that you're no longer having this problem? It seems like you aren't so I'm going to close this issue, but please let me know if that's not the case.

Also, have you tried the suggestion from the previous comment? Here it is again:

> Try to rename the .atom folder (say '.atom_backup'), start atom, close it, then copy your old .atom content into your newly created .atom folder, and restart/reload.

**Comment by juanscv** [comment]
I'm not having it again.

Yes, i hid it myself. Had to unhide it.

**Comment by syserss** [comment]
I had the same problem and I had to unhide it to resolve the issue as well.  I do not recall hiding the folder, although I cannot say for sure.

**Comment by georgebrindeiro** [comment]
Same here, I started having the issue after I hid the folder.

**Comment by yanzhuIT** [comment]
Cancel hidden and read-only options of .atom folder, done!

**Comment by OctoPenguin** [comment]
Maybe you guys could fix it?
