### ISSUE TITLE
Ending HTML comments in 3 dashes breaks highlight

### ISSUE THREAD

**Issue by surdu** [atom/atom#7167]
I have the following piece of snippet:

```html
<html>
  <body>
    <!-- some comment --->
  </body>
</html>
```

As you can see even in GitHub (like GitHub is being developed by the same guys as Atom :grin: ) the `body` and `html` appear commented, although they really aren't, because of the extra dash in the comment.

Chrome doesn't complain about this. Are there any browsers that do or why do you guys parse it like this ?

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/language-html?

**Comment by surdu** [comment]
Surely, my bad
