### ISSUE TITLE
Enable/disable depends on package directory name, not `name` from package.json

### ISSUE THREAD

**Issue by oclbdk** [atom/atom#7174]
We have some packages whose directory names do not correspond to their package name (e.g. `nuclide/file-tree` for `nuclide-file-tree`, `nuclide/hack` for `nuclide-hack`), and I noticed that the Package Manager (i.e. Settings > Packages) doesn't allow me to enable/disable them.

I looked at `~/.atom/config.cson`, and it seems like just the base name of the directory is being written into the `core.disabledPackages` config. I believe it needs to be the `name` field from the `package.json` for it to work properly.

**Comment by oclbdk** [comment]
Using Atom v0.206.0 on Mac, let me know what other info you'd like to see

**Comment by mnquintana** [comment]
According to https://github.com/atom/atom/blob/master/src/package.coffee#L78, it does depend on `name` from package.json, but it falls back to the directory name if the metadata is ~null. It's a bit hard to tell without seeing the package.json for the affected packages, but it seems like some of the package metadata might be invalid?

**Comment by kevinsawicki** [comment]
I think this might be impacting it: https://github.com/atom/atom/blob/c06d62e607411e4e42c451daf98aa54106f8477e/src/package.coffee#L48
