### ISSUE TITLE
Resize pane cursor is inconsistent with tree view cursor

### ISSUE THREAD

**Issue by rmartin** [atom/atom#7178]
As noted by @trkoch in the https://github.com/atom/atom/pull/5902#issuecomment-95063910 thread, the resize pane cursor is inconsistent with the resize cursor. Specifically the tree view cursor uses the col-resize cursor where the resize panes use the ew-resize for horizontal and ns-resize for vertically split panes. This should be updated to using the split panes leverage col-resize cursor for horizontal and row-resize for vertically split panes.

The following screen capture highlights the issue:
![atomresizepanecursorbug](https://cloud.githubusercontent.com/assets/119151/8053169/e7d78bbe-0e42-11e5-9048-00cccbd61ca8.gif)

**Comment by mnquintana** [comment]
Added in https://github.com/atom/atom/pull/7179
