### ISSUE TITLE
Package search input desn't respond to Return key

### ISSUE THREAD

**Issue by rustedwolf** [atom/atom#7181]
Appears in "Install" section:
While typing the package name - nothing happens, after pressing <kbd>Enter</kbd> nothing happens as well. To initiate the package search I have to press "themes" button and then go back to "packages".

Does anyone has the same problem?

Atom: 0.207
OS: Linux Mint 17.1

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/settings-view?
