### ISSUE TITLE
Package installer search field broken

### ISSUE THREAD

**Issue by davidlormor** [atom/atom#7189]
In the "Install" tab under "Settings", the search box is no longer searching when the enter key is pressed.  In order to search I have to click on the inactive button in the button group with "Packages/Themes", then click back to the category that I actually want to search.  I'm on a new MacBook running OS X 10.10 with Atom v0.206.0.

**Comment by mehcode** [comment]
I can reproduce this on Ubuntu 15.04 with atom v0.207.0

I can only search for one package per time I open atom.

**Comment by afinne** [comment]
Yup, I can reproduce it on v0.208.0 too.

**Comment by mnquintana** [comment]
This seems like a duplicate of https://github.com/atom/settings-view/issues/535 – let's move the discussion to that issue.
