### ISSUE TITLE
Atom under Windows keeps lagging

### ISSUE THREAD

**Issue by visualcookie** [atom/atom#7191]
Hi,

first, great changes so far... but after the upgrade to v2.0 it keeps on lagging for me as a Windows user. Especially when I click on a Package in my list or just go right to the settings.

Before Atom worked completly fine. Something is broken.

**Comment by mnquintana** [comment]
What version did you update to? (There is no v2.0 yet... :laughing:) Have you followed the steps in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)?

**Comment by Zireael07** [comment]
There is no v. 2.0 yet, Atom is not even at 1.0

EDIT: lol ninja'd

**Comment by nycdotnet** [comment]
I agree - the Settings panel often feels laggy on Windows.  I just followed the debugging guide for Atom to set up CPU profiling and I was able to get Atom to freeze by clicking around the different pages on the settings panel.  Atom froze up and became unresponsive altogether for quite a while (perhaps 27 seconds, though I didn't actually time it) and then came back like everything was fine.  This is pretty easy to repro.

![highcpuatom](https://cloud.githubusercontent.com/assets/3755379/8069386/32cad146-0ec8-11e5-984d-acb66c63a80f.PNG)

**Comment by visualcookie** [comment]
@mnquintana @Zireael07 In my eyes there's a version 2 :smile:
I'm referring to the latest: **0.208.0**

@nycdotnet Thanks for the tests. Didn't found that.

**Comment by JohnMurga** [comment]
@nycdotnet, I see the same behavior in the same place also (only setting pages and only on Windows)
Will freeze fairly regularly on the TLS stuff for anything from 10-30 secs (shouldn't it be async?)
This is Windows 8.1 64Bit and every version of atom since 18x to 208

**Comment by mnquintana** [comment]
@visualcookie @nycdotnet So far, it seems like you're only talking about the Settings View lagging – am I following correctly?

**Comment by JohnMurga** [comment]
@mnquintana sorry ... I know you didn't ask me but I thought I would provide more info ...
The "Editor Window is not responding" message will come up once during a freeze.
The freeze is total, i.e. window does not redraw on resize or anything.
It occurs after a few seconds on the Settings View, and in fact it is possible to go to settings view, close quickly, then go back to editor view and experience the freeze there, but (for me), only if I just closed the settings view a couple of seconds back.
I also noticed that on a fresh install with only a couple of packages on the same machine I was not experiencing this, and I also believe that if I am disconnected from the network I don't either.
I am not sure I would call it lag.
My workaround is to use APM directly and search for packages on the web-site :-P

**Comment by nycdotnet** [comment]
@mnquintana Hi - yes.  @JohnMurga is correct - I suppose lag is the wrong term.  "Lock up" or "freeze" is perhaps better.  When using the settings screen on Windows, Atom will often become unresponsive for 20-30 seconds.  It's very easy to repro by just clicking around on the various tabs.  I can repro this on Windows 7 x64, Windows 8.1 x64, and Windows 10 Pro build 10130 x64 all on different machines.  I have atom-typescript and linter installed, but I don't know if this is relevant or not.

Sorry for not reporting this earlier.  It's so bad that I figured you were aware of it, but perhaps you don't use Windows much.

**Comment by visualcookie** [comment]
@mnquintana Correct. It just freezes for about that time the others wrote. Using Windows 8.1 x64. Sometimes I got similar issues while coding... but Atom will not freeze there, it just closes, which is kinda frustrating, when you're in a live coding session.

**Comment by JohnMurga** [comment]
@nycdotnet got me thinking ... I use the linter and atom-typescript packages ...
But I thought it may have to do with the number of packages I had as opposed to specific ones.
I will try taking those out of the equation later and reproducing.

**Comment by JohnMurga** [comment]
@visualcookie never had it close on me, and I do some very long sessions ...
That sounds like a different issue

**Comment by nycdotnet** [comment]
I feel that this is definitely something having to do with doing the HTTP requests.  I just uninstalled all add-ons and then quit out of Atom, when I went back in, everything was fine on the settings page and I couldn't get it to freeze.  I then figured I'd install a popular add-on that I didn't previously have.  So I looked on atom.io and noticed that color-picker was popular (and I'm assuming unlikely to have major performance issues).  So just as I went to try to install color-picker, I got the freeze.  Once it cleared, everything was fine and the add-on got installed.

I then quit out, and went back in to Atom and I then I couldn't get it to happen again, so I tried to install minimap and as I hit enter, it locked up again.  There's definitely something unusual going on here with Atom and it has to do with searching for updates or add-ins on Windows.

**Comment by JohnMurga** [comment]
I seem to have alleviated the issue moving apm's npm to the latest official :
+ Make sure you are on NodeJs v10.x
+ `cd atom/App/Atom/resources/app/apm`
+ `npm install npm@latest`
I got a warning on upgrading, but it seems to have improved things.
Lockups are less frequent and much shorter.

Can someone confirm/verify ?

**Comment by filipesilva** [comment]
This happens to me, and I also have linter and typescript installed on atom. I'm still partial to thinking it's probably related to fetching package info though. 

I've tried installing the latest npm, let's see if it helps.

**Comment by mnquintana** [comment]
@JohnMurga That's interesting - if latest npm resolves this issue then https://github.com/atom/apm/pull/374 should fix this.

**Comment by JohnMurga** [comment]
@mnquintana it doesn't totally eliminate the problem, as I have managed to force a couple of 5 second freezes, but at least for me it it dramatically improves the situation.

**Comment by nycdotnet** [comment]
In my `C:\Users\steve\AppData\Local\atom\app-0.208.0\resources\app\apm` folder, I ran `npm install npm@latest --save`.  According to `package.json`, this updated npm from `2.5.1` to `^2.11.2`.  I was still able to get atom to freeze by clicking around the tabs on the settings screen.  This is on Windows 7 SP1 x64, fully patched.  In fact, now the freezes were long enough for the "We think the editor crashed" (I forget the exact text) dialog to come up and I had to click "Keep waiting".

So unfortunately, at least for me, the npm upgrade didn't fix it.

**Comment by JohnMurga** [comment]
@nycdotnet can you try opening dev tools and typing `process.features.tls_sni = false;`
It's a long shot, but it might work

**Comment by JohnMurga** [comment]
Disabling SNI seems to have resolved what freezing issues I had left, picked up some more infor here : https://groups.google.com/forum/#!topic/nodejs/oIEzPGlpXDU

**Comment by JohnMurga** [comment]
This bug is still present on 211.
I still see the "more-information-needed" tag on this issue despite the info provided.
A common pattern for a lot of Windows issues (along with the "needs-reproduction" tag).
And 1.0.0 is being prepared despite the fact that every internet connected Windows user I know can reproduce this particular issue easily and consistently.
For me it is not a problem as I tend to use APM directly, and run on Mint half the time ...
But it sucks for those who enthusiastically try Atom out on Windows.
What we can do to try and help resolve this ?

**Comment by gyf304** [comment]
I can confirm this problem still exists on version 1.0.0, Windows 8.1

**Comment by bjornregnell** [comment]
I can confirm that this problem still exists on version 1.0.2, Windows 7

**Comment by jacek-dargiel** [comment]
I'm having the same issue, and I have a theory. I'm using the mingw32 git shell. The git task in this package is known to be slow, to the level where a simple `git status` can take up to several seconds. It has something to do with UAC access control AFAIR. Since packages in atom are installed using apm, which uses npm, which uses git, can this be the reason why the settings screen hangs when checking for package updates?

**Comment by oande** [comment]
Also having this issue on WIndows 7, Atom version 1.0.7. Opening the package list freezes and sometimes crashes the editor (with 6 community packages installed).

**Comment by Zireael07** [comment]
1.0.6, 1.0.7. both sometimes freezing on the package list.

**Comment by JohnMurga** [comment]
This only happens to me when connected to the internet, so I built a little proxy server into my Atom workarounds plugin. I have set `proxy = http://localhost:33133` in my `.apmrc`, and toggle the build in proxy on and off when I want to update or install packages. It's made my setup much more stable, and the proxy setting only seems to affect APM (which suggests it's a problem with the APM calls).

**Comment by globexdesigns** [comment]
+1. I have a lot of freezing/hangs in the Settings panel on Windows, Mac and Linux. Installing/Uninstalling packages has always been a massive pain requiring me to force quit the editor.

**Comment by markusjohnsson** [comment]
I'm also using git bash to launch atom, I found some tips here: http://stackoverflow.com/questions/4485059/git-bash-is-extremely-slow-in-windows-7-x64

I did this:

    git config --global core.fscache true

> `core.fscache` fixes UAC issues (don't need to run git as admin)

And this: remove `__git_ps1` from `$PS1` (in `/etc/bash.bashrc`). This will remove the current branch name from the shell prompt (useful but slow). 

Restart git bash and relaunch atom.

I think things are faster now.

**Comment by JohnMurga** [comment]
These issues I was having seem to have been fixed with the move to Electron v0.30.6 in 1.0.12
I have not been able to reproduce the freezes with 1.0.12 and subsequent versions for the last 3 days
Well done guys, and thank you :+1:  :clap:

**Comment by 50Wliu** [comment]
Can someone else confirm that this no longer happens on Atom 1.0.12 and above?

**Comment by visualcookie** [comment]
@50Wliu Seems to be fixed.

**Comment by mnquintana** [comment]
Sweet, thanks for the update @visualcookie! I'm gonna close this out now.

**Comment by nickfmc** [comment]
Mine also wont lockup now but if I go to my settings and Updates or install and wait for about 5 mins I get the following.  wanted to make sure other people aren't having that issue as this package fetching seamed to be the cause of the freezing. 

![socket](https://cloud.githubusercontent.com/assets/8106386/9981867/60c25752-5f7e-11e5-9072-395af7d025a8.png)

**Comment by filipesilva** [comment]
I waited a couple of days to confirm, and so far I haven't had any of the lag/freezes either.

**Comment by cakenggt** [comment]
My atom is still hanging up on the `Packages` settings view in version 1.0.19 with a fresh install. My javascript profile during the freeze is exactly the same as @nycdotnet posted, with a freeze time of 1.6 minutes.

**Comment by nmccready** [comment]
@cakenggt I am seeing this exact same issue on OSX 10.10.5

**Comment by visualcookie** [comment]
Aaand it's bag again. Nice. You fixed several issues and this and it's back on the road again. Not awesome.

**Comment by braco** [comment]
+1, getting this on OSX like @nmccready

**Comment by nmccready** [comment]
Do you guys operate on milestones (which can be added to github)? That way we can have some estimated time when 1.1.0 or 1.0.20 will be out?

**Comment by paulyoung** [comment]
I've also been experiencing this issue for a whiel

**Comment by peterfraedrich** [comment]
Having this issue on Windows 7 Enterprise x64 with `strict-ssl = false` in my .apmrc on Atom 1.1.0. I get the "editor crashed" error every time it tries to list installed or community packages (basically any time apm is called, howerver apm via CLI works fine).

**Comment by paulyoung** [comment]
I was having this problem even in safe mode, and Atom became basically unusable as a text editor so I ended up creating a new `~/.atom` directory and re-installing the few packages I need.

**Comment by nickytonline** [comment]
I'm on Windows Server 2012, node 0.12.9 with atom 1.6.0. Installing apm globally seems to have fixed the huge lag issue I was having. I went from 30-45 seconds down to 5 seconds.

**Comment by rebornishard** [comment]
I'm in atom 1.6.0 windows 10 x64
atom hang, and now i reinstalling using 1.7.3
how to do atom upgrade without uninstalling ?

thanks

**Comment by abeltensor** [comment]
Was still having these problems on windows 10.  I just deleted all of my plugins and reinstalled atom, git, visual studio, npm, node and python will update if things change.

**Comment by simonchan2013** [comment]
@nmccready  hello,  I have the same problem everytime I visit the Preferences > Packages. Have you got any solution? With your response

**Comment by nmccready** [comment]
> @nmccready hello, I have the same problem everytime I visit the Preferences > Packages. Have you got any solution? With your response

sadly no, I had kill atom and start from scratch.

**Comment by simonchan2013** [comment]
It work well after I uninstall all package, and now I try to install those package again...  @nmccready

**Comment by noseGoblin** [comment]
I am on Atom 1.9.0-beta1, after trying the newest stable through several versions and cannot get away from this issue. The lag/freeze happens everywhere in my experience: live coding, settings, packages (install/browse/etc) and pretty much every page you can think of.

I'd really love to see a solution, as uninstalling popular packages is not a good option. In all reality, the packages I use are what make atom a leg up from sublime text. I love atom & don't want to go back, but this freezing happens A LOT and it's driving my workflow to a grind. I'm going to try safe mode and see if it still happens, hopefully another round of debugging will produce some results

**Comment by 50Wliu** [comment]
> I'd really love to see a solution, as uninstalling popular packages is not a good option.

I agree!  You should be able to use whatever packages you want.  So if you notice that some packages are causing slowdowns, you should definitely report that to the package repositories so that they can fix it :).

(Also, your first sentence was a bit unclear, so just in case: the latest version of Atom is currently Atom 1.12.6.)

**Comment by hubmartin** [comment]
The solution for my Windows 7 PC was to turn off the Avast antivirus. The 3 second lag was immediatelly gone. By enabling the Avast again the 3 second lag was back. Not sure what to do without antivirus :)

**Comment by 50Wliu** [comment]
@hubmartin In Avast's settings, you can specify paths to exclude in the regular AV scanning.  Based on previous experience I would recommend `%userprofile%\.atom` as well as `%localappdata%\Atom`.
