### ISSUE TITLE
Atom 0.208 won't open files larger than 2MB

### ISSUE THREAD

**Issue by FlyingPumba** [atom/atom#7195]
The [Release Notes page](https://atom.io/releases) says that now Atom can open files larger than 2MB, but for some reason, Atom 0.208 behaves exactly as 0.207, and displays the same yellow message when trying to open files larger than 2MB.
My OS is Ubuntu 14.04

**Comment by maxbrunsfeld** [comment]
@FlyingPumba could you run `atom.getVersion()` in the console and report the output?

**Comment by FlyingPumba** [comment]
Sure, output is: ```0.202.0-ec5b807```
Does it mean that I have an older version than 208 ? I usually update Atom by downloading the new .deb file and running ```dpkg -i atom-amd64.deb```

**Comment by maxbrunsfeld** [comment]
Yeah, you're running version 0.202. What's the output of `which atom` for you? Depending on your configuration, you may need to run `dpkg -i` with `sudo`.

**Comment by FlyingPumba** [comment]
Output for ```which atom``` is: ```/usr/local/bin/atom```. I always run ```dpkg -i``` with sudo.
Is there a way to _really_ update Atom ? I have several packages installed and configured, and I wouldn't like to reinstall them all.

**Comment by maxbrunsfeld** [comment]
Yeah, you definitely don't need to reinstall your packages or touch your configuration. I'm not sure why your install is failing. Is there any output from `dpkg`?

**Comment by mnquintana** [comment]
@FlyingPumba Did you build from source for version 0.202.0? The version number seems to suggest that.

**Comment by FlyingPumba** [comment]
@maxbrunsfeld ```dpkg``` installation seems successful, no error messages.
@mnquintana Now that you mention, I did compiled and installed from source a few versions ago, I thought I had uninstalled it, though. Maybe ```/usr/local/bin/atom``` is the compiled Atom for version 0.202. Shouldn't it be overwritten when installing with ```dpkg``` ?
Another weird stuff, is that when installing a new version with  ```dpkg``` it shows which is the number of the new version and which is the number of the current installed version, and it seems okey. (i.e: today I installed the new version and the older version was 0.207, not 0.202). So it's being installed somewhere, I think.

**Comment by mnquintana** [comment]
@FlyingPumba The `.deb` installs to `/usr/bin/atom` by default, so chances are that if `/usr/local/bin/` comes first in your `PATH`, then at the very least launching from the command line would always open the version you compiled. Do you get the correct version if you launch from Unity's Launcher?

**Comment by FlyingPumba** [comment]
@mnquintana That's it !! Sadly, launching Atom from Unity's Launcher launches the same version. But you gave me the idea:
```/usr/local/bin/atom --version``` outputs: ```0.202.0-ec5b807```
While
```/usr/bin/atom --version``` outputs: ```0.208.0```
Now I just need to "uninstall" the atom in /usr/local/bin (probably installed running ```script/grunt install```). Do you know if it's safe to just delete ? Or is there a commando to uninstall it ?

**Comment by kevinsawicki** [comment]
> Do you know if it's safe to just delete ?

Yup, safe to delete

> Or is there a commando to uninstall it ?

There isn't one currently.

**Comment by FlyingPumba** [comment]
Okey, working now. Thanks for the help guys ! :+1:
