### ISSUE TITLE
Atom not opening

### ISSUE THREAD

**Issue by TildaUser** [atom/atom#7201]
I'm running Ubuntu 12.04 in Virtualbox. I've downloaded and installed the latest .deb file from the Atom repo. The install went fine. I launch Atom and the processes starts, but Atom does not open. 

Any ideas?

**Comment by TildaUser** [comment]
Here's an error I got from trying to just download the code and run atom...
![image](https://cloud.githubusercontent.com/assets/12589730/8074455/5b2688b2-0ef8-11e5-9fb5-56fe440fb5d9.png)

**Comment by TildaUser** [comment]
Okay, tested it out on another computer. I got the same error trying to download the code and run atom, but when I installed the deb, it worked fine...weird.

**Comment by jenshnielsen** [comment]
I'm seeing this too on Ubuntu 15.04  Started following the upgrade to 0.208

**Comment by cristianmtr** [comment]
Maybe this is relevant: http://stackoverflow.com/questions/24464690/bash-scripting-unexpected-operator

```
if [ "a" == "a" ] should be if [ "a" = "a" ].
bash accepts == instead of =, but your /bin/sh probably isn't bash.
So either change the == to =, or your shebang to #!/bin/bash
```
