### ISSUE TITLE
'Copy' command when nothing selected should do nothing

### ISSUE THREAD

**Issue by vemv-kantox** [atom/atom#7206]
Behavior in the vast majority of editors/programs is that if you execute the 'Copy' command (Control/Command + C) when no text is selected is that nothing happens.

Atom instead copies the current line. There's already a nice duplicate-line command, making the behavior not quite necessary.

The real annoyance is that many, many times I mean to press Ctrl-V but I press Ctrl-C instead. So I lose my selection and have to go copy the original text again.

**Comment by mnquintana** [comment]
This is a duplicate of https://github.com/atom/atom/issues/7103 - please subscribe there for updates.
