### ISSUE TITLE
have a problem for install package

### ISSUE THREAD

**Issue by vrigan** [atom/atom#7207]
error info
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at createHangUpError (http.js:1477:15)
gyp ERR! stack     at Socket.socketOnEnd (http.js:1573:23)
gyp ERR! stack     at Socket.g (events.js:180:16)
gyp ERR! stack     at Socket.emit (events.js:92:17)
gyp ERR! stack     at _stream_readable.js:944:16
gyp ERR! stack     at process._tickCallback (node.js:442:13)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.22.0" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure" "--proxy=http://localhost:8087/"
gyp ERR! cwd /Users/yan/.atom
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

and i use #5725 set my proxy
proxy = http://localhost:8087
strict-ssl = false

my python version:Python 2.7.6.
os version:osx 10.10.3

any one can help me.

**Comment by mnquintana** [comment]
What were you trying to do exactly? Install a package through the Settings View UI? On the command line with `apm install`? Or were you trying to build Atom from source?

**Comment by vrigan** [comment]
i installed ATom Version 0.208.0;Then i want install some package;such as file-icons or other;but china have gfw,so i must use proxy;when i used the proxy for download,This error occurred;Sorry my poor English

**Comment by vrigan** [comment]
problem closed;
when i use vpn download the node-v0.22.0.tar.gz;it's ok,does't exist problem;maybe my proxy download big file have problem;
now i closed vpn;use proxy to download small package;all is well!
