### ISSUE TITLE
Cursor position not respected with auto indentation on paste

### ISSUE THREAD

**Issue by AdamBuczynski** [atom/atom#7216]
I love auto indentation on paste, and it's a a very useful feature. However, currently in Atom it seems to be a little bit too smart, and taking control away from the coder.

The problem I have with it is that It doesn't respect where you put your cursor before pasting:

![ex1](https://www.dropbox.com/s/tcun18tsprgszw2/cursor%20position%20not%20respected.gif?dl=1)

In my opinion, the cursor position should be used as a baseline for the pasting operation, *not* whatever Atom thinks is the baseline based on surrounding code.

If I want to paste something starting at a certain indentation, I would like Atom to respect that, even if Atom thinks the proper indentation is different. Right now, it's just causing frustration, because I have to paste something and then correct the auto indentation, fighting against the editor, rather than having the editor do the work for me.

Sublime does this well (reinstalled it just to record this):

![ex2](https://www.dropbox.com/s/uokpiuri56pxgtn/cursor%20position%20respected%20in%20sublime.gif?dl=1)

Is it possible to update Atom's behaviour to respect the cursor position on paste, or at least provide an option to enable/disable this behaviour?

**Comment by maxbrunsfeld** [comment]
So I believe the difference is that Sublime does not auto-indent on paste. There is already a setting to disable auto-indent-on-paste on a per-language basis. Can you explain in a little more detail what you mean when you say that you like auto-indent-on-paste, but want the cursor position to be respected?

**Comment by AdamBuczynski** [comment]
I believe you are right. I was under the impression that auto-indent-on-paste had to do with proper indentation for pasting more complex pieces of code, but it seems that turning off this setting indeed provides me with the desired functionality.

Thanks, sorry for raising the issue.

**Comment by maxbrunsfeld** [comment]
No worries! For a while, the situation was a little more confusing in Atom because we had a third setting called `normalize-indent-on-paste`. That setting is now gone, and we always preserve the relative indentation of pasted lines, so things are back to being reasonably simple again.

**Comment by AdamBuczynski** [comment]
Ah yes, I remember that setting in one of the earlier atom versions, and I remember being confused as to what's what ;)

Cheers.
