### ISSUE TITLE
Windows failure to start atom

### ISSUE THREAD

**Issue by freakypie** [atom/atom#7221]
I dragged a file onto the atom editor and it immediately crashed.

The program will start but will crash again before the UI shows up. There is no useful output on the command line.

I suspect that the file is somehow causing this, and every time it loads it tries to get this bad file.

C:\Users\John\Dropbox\salsa>atom --version
[4764:0611/000926:INFO:CONSOLE(0)] 0.208.0

**Comment by batjko** [comment]
Can you clarify whether you're dragging your file onto a link (or taskbar pin), or into an already opened Atom window?

Which Windows version is this on?

Do you get any window or erroneous output you could take a screenshot of?

**Comment by freakypie** [comment]
hasn't ever happened again
