### ISSUE TITLE
Issue with syntax coloring/leading spaces (in XML)

### ISSUE THREAD

**Issue by pgkos** [atom/atom#7223]
There is a small issue with syntax coloring which I have observed in XML files (I am not sure if it occurs with other syntaxes). I think the issue did not occur in previous versions of Atom.
![xml_coloring_bug](https://cloud.githubusercontent.com/assets/11692818/8103109/30118bac-1026-11e5-8e36-1e18279269da.png)
As you can see, the color spans are moved by one character forward on the lines which only contain an XML attribute. The issue occurs only if the number of leading spaces on these lines is even.
(Atom 0.207.0, Ubuntu 14.04 64-bit)

**Comment by batjko** [comment]
Might potentially be better placed on the [language-xml repo](https://github.com/atom/language-xml/issues)?

**Comment by mnquintana** [comment]
> Might potentially be better placed on the language-xml repo?

Yup, would you mind moving this to [atom/language-xml](https://github.com/atom/language-xml)?

**Comment by pgkos** [comment]
Ok, I'm moving it.
