### ISSUE TITLE
Saving a file takes too long.

### ISSUE THREAD

**Issue by lczech** [atom/atom#7226]
When editing a file, saving sometimes takes about 2sec (not actually measured, just a feeling). This leads to workflow problems for me, because doing the following commands sometimes takes less than the time that atom needs for saving the file:

* Edit a source file
* Save it
* Switch to terminal
* Run something that uses the file
* BOOM!

I don't know too much about the internals of atom, but it looks like the document needs to be stripped of all its html markup before being saved, which takes time of course. Maybe, a plain text copy of the content could be stored in memory, which is used for quickly saving the content.

**Comment by benogle** [comment]
Does the editor freeze up for a sec? Did you try in safe mode? `atom --safe .` Check out the [debugging document](https://atom.io/docs/latest/debugging)

**Comment by andya9** [comment]
@benogle I too experienced this when saving xml files with lot of nodes; the editor will freeze for far more than a sec... sometimes it will even crash; probably it will be dealt with when support for large files is completed?

It doesn’t happen when using safe mode by the way.

A sample document: http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng
Just delete a **large** chunk of text and try to save, atom should freeze if not in safe mode

**Comment by mnquintana** [comment]
> It doesn’t happen when using safe mode by the way.

Then this is caused by a community package, not Atom core. What's your list of installed packages? (`apm list --installed`)

**Comment by andya9** [comment]
@mnquintana 
├── atom-terminal@0.8.0
├── emmet@2.3.10
├── file-icons@1.5.7
├── language-generic-config@0.2.0
├── linter@0.12.7
├── linter-flake8@1.4.2
├── linter-tidy@1.0.1
├── linter-xmllint@0.0.6
├── merge-conflicts@1.3.2
├── open-in-browser@0.4.6
├── pdf-view@0.22.0
├── sort-lines@0.11.0
└── tabs-to-spaces@0.11
I’ll try to disable everything to find the culprit

**Comment by andya9** [comment]
Found! It’s tabs-to-spaces when set to "untabify on save"

**Comment by lczech** [comment]
Yep, thanks @andya9, I can confirm it is tabs-to-spaces. The freezing doesn't happen in safe mode, and also not with this package disabled.

Oh, just saw your update now. Thanks also for forwarding to the package issue thread. I think this issue can be closed now, as it is not atom internal.

**Comment by andya9** [comment]
@lczech I’m glad we could find why it was happening

Thanks @mnquintana for pointing towards the solution!
