### ISSUE TITLE
Mini atom-text-editor doesn't handle horizontal overflow unless a space is used

### ISSUE THREAD

**Issue by acusti** [atom/atom#7228]
Here’s an illustration of the issue:

![texteditor mini horizontal overflow](https://cloud.githubusercontent.com/assets/517889/8112251/a813a3d4-1034-11e5-97eb-392c4c7bdad9.gif)

Basically, the text you’re typing becomes invisible until you type a space. This is particularly problematic if the mini TextEditor is being used for something like a long URL, which you wouldn’t expect to have spaces.

Using Atom v0.208.0 on Mac OS 10.10.3

**Comment by v3ss0n** [comment]
Reproducible .

**Comment by ollpu** [comment]
This issue is not occurring for me. (Atom 0.209, Ubuntu 15.04)

**Comment by lee-dohm** [comment]
I was unable to reproduce this using Atom v0.211.0-fc4f2a1 on Mac OS X 10.10.3 using Safe Mode:

![to-scroll-or-not-to-scroll](https://cloud.githubusercontent.com/assets/1038121/8272379/b474fb2e-17f4-11e5-9601-32489ff1683c.gif)

Have you tried using Safe Mode? Are you using one of the standard themes?

**Comment by simurai** [comment]
Have you tried toggling "Soft Wrap" in the settings?

It looks like the same "Soft Wrap" issue, see @izuzak's comment: https://github.com/atom/tree-view/issues/473

**Comment by acusti** [comment]
Definitely a duplicate (exact same issues), thanks @simurai. I’ll close this one.
