### ISSUE TITLE
Close All is not available from the command pallette

### ISSUE THREAD

**Issue by arv** [atom/atom#7229]
Steps to reproduce

1. Press Ctrl-Shift-P.
2. Type "close all".
3. No matches found.

Expected result.

The command for close all should be shown. I know there is such a command because I can get to it by right clicking on a tab.

**Comment by mnquintana** [comment]
It is available in the Command Palette, but only if you have the editor focused.

**Comment by arv** [comment]
I don't see it. Did it change recently?

**Comment by mnquintana** [comment]
@arv Do you have an editor focused when you open the Command Palette? (e.g. is the cursor blinking in an open editor?)

**Comment by arv** [comment]
Pressing Ctrl-Shift-P moves the focus to the text field of the command palette.

**Comment by mnquintana** [comment]
Right, I mean is an editor focused right before you open the Command Palette?

**Comment by arv** [comment]
Yes.

I see other items if I only type "close", such as "Pane: Close", "Window: Close", "Core: Close" but no "Close All"

**Comment by mnquintana** [comment]
Can you post a screen capture of this?

**Comment by arv** [comment]
No. Because I just updated (from 0.204 to 0.209) and now I see "Tabs: Close All Tabs"

Sorry for wasting your time.
