### ISSUE TITLE
Syntax mode is not available from command palette

### ISSUE THREAD

**Issue by arv** [atom/atom#7230]
Steps to reproduce:

1. Press Ctrl-Shift-P.
2. Type "syntax javascript".
3. No matches found.

Expected result:

The syntax mode menu should be reachable from the command palette.

A similar issue exists with the encoding menu.

**Comment by mnquintana** [comment]
The "syntax chooser" is called grammar-selector, and that *is* available in the command palette. The "encoding chooser" is called encoding-selector, and is also available in the command palette. However, you must have an editor focused for both. Hope that helps!
