### ISSUE TITLE
Feature Request: "Match Quotes" option in finder

### ISSUE THREAD

**Issue by colllin** [atom/atom#7232]
Similar to "Match Case" (and turned off by default).

When disabled, typing `'` or `"` in the finder query would essentially match the regexp `['"]`.

![image](https://cloud.githubusercontent.com/assets/185923/8115047/124b56c4-1036-11e5-943b-f42f41edb311.png)

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/find-and-replace?

**Comment by colllin** [comment]
No problem.  Thanks for pointing me in the right direction.
