### ISSUE TITLE
Un-styled scrollbars appear after waking from sleep if external mouse is plugged in

### ISSUE THREAD

**Issue by mnquintana** [atom/atom#7236]
Steps to reproduce:
1. Ensure that no external mouse is plugged in
2. Put computer to sleep
3. Plug in external mouse (preferably a non-Apple mouse with a scroll wheel)
4. Wake computer from sleep
5. Atom will have un-styled scrollbars
- OS X 10.10.3
  - System Preferences > General > Show scroll bars > Automatically based on mouse or trackpad
- Atom 0.209.0 (but I've noticed this for many versions now)

Can anyone else reproduce this? (@atom/feedback?)

**Comment by mnquintana** [comment]
This actually only happens with the most-recently focused window, as it turns out.

**Comment by steelbrain** [comment]
@mnquintana I also able to occasionally repro this on linux

**Comment by Stanzilla** [comment]
In https://github.com/atom-community/linter/issues/786 I noted that I was only able to get the somehow glitched scrollbars when the last thing I had open/focussed in Atom before I closed it was settings-view. So when you start Atom again, settings-view is the first thing it shows, if you tab away from it once, the bug disappears.

**Comment by msokk** [comment]
This happens to me almost every time after sleep.
I'm using OSX 10.10.5, Atom 1.0.9 and Magic Mouse.

**Comment by nkovacs** [comment]
This happens to me on linux with atom 1.2.0 every time I start atom and it reopens a file. Once I switch to another file and back, it fixes itself.
I did not have this problem with atom 1.0

**Comment by 50Wliu** [comment]
@nkovacs That is a different bug that has been resolved in 1.3.0-beta2 which should be out soon.
