### ISSUE TITLE
Do not include redundant closing quote when valid quote already exists on same line

### ISSUE THREAD

**Issue by AdamBuczynski** [atom/atom#7240]
See the following example:

![ex1](https://www.dropbox.com/s/8ciiou7liutx4mo/quote%20replacement.gif?dl=1)

When a valid matching closing quote already exists on the same line, Atom should not auto include a redundant closing quote.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/bracket-matcher?

**Comment by AdamBuczynski** [comment]
Ok, sure thing.
