### ISSUE TITLE
Auto indent keybinding not working after 0.208.0

### ISSUE THREAD

**Issue by zero-** [atom/atom#7244]
I had keymap defined for auto indent but it stopped working after 0.208.0. There was some deprecation with ```editor``` classes, tried to fix it but still doesn't work. I verified with keybinding resolver that it triggers the rule so that shouldn't be the problem but instead the problem seems to be with the command it's trying to run. Both outdent and indent work properly.

My keymap looks like this:
```
'.atom-workspace .atom-text-editor:not(.mini)':
  'ctrl-alt-left': 'atom-editor:auto-indent'
  'ctrl-alt-8': 'atom-editor:outdent-selected-rows'
  'ctrl-alt-9': 'atom-editor:indent'
```

**Comment by maxbrunsfeld** [comment]
`atom-workspace` and `atom-text-editor` are actually *tag names* (like `div`, `li`, etc) not class names, so you don't prefix them with a dot in a CSS selector.

I think this should work:

```
'atom-workspace atom-text-editor:not(.mini)':
  'ctrl-alt-left': 'atom-editor:auto-indent'
  'ctrl-alt-8': 'atom-editor:outdent-selected-rows'
  'ctrl-alt-9': 'atom-editor:indent'
```

Let us know if you have any further problems with this.

**Comment by zero-** [comment]
Tried your version but it still doesn't work - recognises it but doesn't actually do the indentation. I updated to 0.209.0 but nope. Did you test the auto indent?

![image](https://cloud.githubusercontent.com/assets/1594723/8142974/799d277c-119d-11e5-8696-60a3bb4717b7.png)

**Comment by zero-** [comment]
Found the problem. Correct is ```editor:auto-indent```, not ```'atom-editor:auto-indent```.
