### ISSUE TITLE
In semi-transparent themes , tilerendering Colors the Tile area and Lines area , differently from the atom-editor.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#7246]
In transparent themes , tile rendering applies colors differently. Observable in my theme :

![image](https://cloud.githubusercontent.com/assets/419606/8125580/dcb46c58-110c-11e5-9761-8a2dc2946b14.png)

If it is not a bug , what would be recommended way for theme developers to theme those tiles ?

**Comment by as-cii** [comment]
Hey @v3ss0n! Would you mind updating this issue with the recent conversation we had on Slack?

Not sure if that actually solved your problem, but it would be nice to include the gist of it here for posterity.

Thank you! :pray:

**Comment by v3ss0n** [comment]
I am still trying to make it so , color looks uniform between tiles and background.
So far , Setting transparent is only way working properly .
