### ISSUE TITLE
Can't uninstall deprecated package

### ISSUE THREAD

**Issue by AgentME** [atom/atom#7247]
I have the language-typescript package installed. Apparently it's deprecated and superseded by atom-typescript, but I'm not interested in keeping it around and would prefer to just uninstall it, but that option is missing for this package specifically.

![screenshot from 2015-06-12 01 07 00](https://cloud.githubusercontent.com/assets/577345/8126009/b6611596-109f-11e5-896c-cd6031f5846b.png)

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/settings-view?

**Comment by AgentME** [comment]
Moved to https://github.com/atom/settings-view/issues/545
