### ISSUE TITLE
Javascript files saved as binary

### ISSUE THREAD

**Issue by callbacknull** [atom/atom#7250]
Hello,

Yesterday I had shut down my laptop after working on some javascript files. When I started it up this morning 3 of those files were in a binary format. I have no idea what had happened as the only thing I would have done last night was save them and alt+f4 atom.

I'm on: 
Ubuntu 14.04 x86-64
3.18.4-031804-generic
atom io version 0.208.0

Not too sure what logs might help to figure this out. If anyone has recommendations for what to do that be fantastic. Even better if you have a suggestion for how I might be able to get my work back :(

**Comment by mnquintana** [comment]
Have you followed the steps in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)? Any chance you could reproduce this in safe mode? (`atom --safe`) Can you post a list of your installed packages? (`apm list --installed`)

**Comment by ambbell** [comment]
I have not but I'll go through that now. I'll try to reproduce it but I don't remember anything out of the ordinary that I did last night. 

Packages:
```
~/.atom/packages (27)
├── angularjs@0.3.0
├── atom-angularjs@0.1.2
├── atom-beautify@0.27.10
├── atom-prettify@0.1.1
├── autoclose-html@0.17.0
├── autocomplete-paths@1.0.2
├── copy-to-hipchat@0.1.0
├── file-types@0.3.0
├── git-blame@0.4.4
├── git-diff-details@0.18.0
├── git-diff-popup@0.1.8
├── git-log@0.4.1
├── js-refactor@0.3.0
├── jsdoc@0.9.0
├── linter@0.12.6
├── linter-jscs@1.12.0
├── linter-jshint@0.1.5
├── merge-conflicts@1.3.2
├── meteor-api@2.19.0
├── meteor-helper@0.25.0
├── mocha@0.0.5
├── pretty-json@0.3.3
├── refactor@0.4.1
├── seti-syntax@0.4.0
├── seti-ui@0.7.1
├── terminal-panel@1.14.1
└── web-browser@1.5.0
```

**Comment by ambbell** [comment]
Also, started atom in safe mode and the files are still binary - as they are also when I open the files in vim.

**Comment by maxbrunsfeld** [comment]
Is it possible that while closing Atom, you accidentally opened the encoding selector `ctrl-shift-u` and selected an encoding other than utf8? You could try opening the file and trying different encodings.

**Comment by callbacknull** [comment]
Unlikely - I type in dvorak and `ctrl-shift-u` is a bit awkward sequence to press since it's all with my left hand(the `u` is the qwerty's `f`). I probably wont be able provide any further information on this as I switched to webstorm shortly after.
