### ISSUE TITLE
Include minimap

### ISSUE THREAD

**Issue by 190n** [atom/atom#7251]
Has anyone ever considered including the [Minimap](https://atom.io/packages/minimap) package in the core Atom build? It has over 350,000 downloads, it seems like almost everyone is using it and I think it should be included out of the box.

**Comment by mehcode** [comment]
![screenshot from 2015-06-12 10 08 43](https://cloud.githubusercontent.com/assets/753919/8135289/06b6232e-10eb-11e5-82c8-61f5ee991a9e.png)

---

**Minimap** quite literally has the **most** downloads, period, apart from core packages. I think every once in a while the atom team should evaluate the top-downloaded non-core package and determine if it makes sense to include. I vote :+1: for **minimap**.

**Comment by 190n** [comment]
Minimap also has the most stars.

**Comment by thedaniel** [comment]
Not saying no, but if we add the most-downloaded package to core every few months Atom will become a monster IDE with attendant maintenance and startup time issues ;)

The power of Atom is how customizable it is, it's OK to have highly in-demand packages not shipped with core.

**Comment by 190n** [comment]
@thedaniel That's a good point, but I think problems like that can be avoided if you're smart about which packages to include. For instance, the [linter-jshint](https://atom.io/packages/linter-jshint) package is in the top 10 most downloaded, but it's not really applicable to a lot of developers, so I wouldn't include it out of the box.

**Comment by 190n** [comment]
Sublime Text also has a minimap.

**Comment by freemanoid** [comment]
Minimap is the first thing I turned off when begun to use sublime text.

**Comment by mehcode** [comment]
Eh. Re-thinking this: there are a non-immaterial amount of people that want to *not* use minimap. As opposed to the *tabs* package, for instance.

Atom (or [someone else](https://github.com/mehcode/awesome-atom)) could just maintain a list of packages that are "recommended" as opposed to included-by-default. 

Something like the minimap is a thing that if I didn't know existed I wouldn't want; but after seeing that it exists I can't live without it because it is that awesome (to me, of course).

**Comment by alexandernst** [comment]
I'm +1 for either including some of the most downloaded packages (not every month as @thedaniel said, but once every major release, or something like that) or making a big green button that says "We think you'd like some extra packages. Click here to get them all".

**Comment by 190n** [comment]
@alexandernst Good idea, seems like a smart compromise between including it and not including it.

**Comment by thedaniel** [comment]
> Atom (or someone else) could just maintain a list of packages that are "recommended" as opposed to included-by-default.

Isn't that list the package index sorted by downloads that you posted a screenshot of above? In this case, the 'someone else' maintaining the list is the entire community. Seems to be working pretty well, as thousands of people were able to find and install minimap.

**Comment by 190n** [comment]
Maybe you could remove the "Featured Packages" section - it doesn't seem like it's been updated in a while - and replace it with a list of the top 10 most downloaded non-core packages.

Or trending packages, or most starred packages...

**Comment by Samcfuchs** [comment]
I sometimes use minimap. Much of the time, my code is short enough that it doesn't help, so I turn it off. But it is invaluable on the whole. I agree with 190n -- there should be a [featured, favorites, verified, trending, best] section that shows up on the welcome page, so new users know what packages they should install or would like.

**Comment by Zireael07** [comment]
Featured/best/favorited sections sounds like a good idea.

**Comment by 190n** [comment]
Atom team, are you listening? This issue has sort of changed focus from when I opened it.

**Comment by 190n** [comment]
Continued in atom/settings-view#558.
