### ISSUE TITLE
Problem with killing children processes

### ISSUE THREAD

**Issue by davewv31** [atom/atom#7252]
Hi there. I seem to be running into a problem using the atom-script editor, you can see it here: rgbkrk/atom-script#453

Basically, atom-script runs go, which in turn starts up a server. Killing the process with a control-c kills off the child process, but not the child of the child. 

```
13:53|~/go/src/github.com/davewv31/helloworld/helloworld% ps ax | grep helloworld
84187   ??  S      0:00.22 go run /Users/dave/go/src/github.com/davewv31/helloworld/helloworld/helloworld.go
84218   ??  S      0:00.22 /var/folders/2v/53vdc3j9187f6zj1ljjfc10h0000gn/T/go-build234219847/command-line-arguments/_obj/exe/helloworld
```

After control-c in atom:

```
13:53|~/go/src/github.com/davewv31/helloworld/helloworld% ps ax | grep helloworld
84218   ??  S      0:00.22 /var/folders/2v/53vdc3j9187f6zj1ljjfc10h0000gn/T/go-build234219847/command-line-arguments/_obj/exe/helloworld
```

In buffered-process.coffee, the windows and non-windows terminations seem to be different. Windows seems to kill children of children, non-windows seems to just kill the child. 

```
  killProcess: ->
    @process?.kill()
    @process = null
```

So I guess what this comes down to is what should the expected behavior of BufferedProcess.kill be? It does just wrap child_process, but doesn't allow a full process group kill (which I want) or a signal type to be sent(which I'm not sure would work). 

Thanks!

**Comment by jbtule** [comment]
Since June?!

Since there is code to kill all child processes in windows, can't we assume that is the intended behavior. Thus this is indeed a bug on Mac.

**Comment by acburdine** [comment]
@jbtule it's not necessarily a bug with Apple itself, afaik. It probably occurs on all *nix systems. Just added some code that should in theory kill all child processes of a child process on those systems.

**Comment by jbtule** [comment]
@acburdine thank you!!!

**Comment by XaserAcheron** [comment]
Dunno if it helps much to bump & monkeywrench this, but I'm still running into the same issue in Windows (w/ Atom 1.7.1) despite the behavioral difference.

I'm specifically seeing this issue with [ember-cli-helper](https://github.com/apprentus/atom-ember-cli-helper), but I don't _think_ it's the fault of the package since it's not doing anything fancier than calling `BufferedProcess.kill()`, unless there's something weird going on with `ember-cli` invoking a child `node` process. Worth mentioning at least.

**Comment by psywolf** [comment]
> It probably occurs on all *nix systems.

@acburdine is correct on this.  I can reproduce this issue on linux (Ubuntu 14.04).
