### ISSUE TITLE
High CPU usage when updating multiple packages.

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#7253]
Atom takes 40% CPU when updating multiple packages.
Doing it one by one do not increase CPU usage but when clicking multiple updates at once , atom raise to 40% cpu and never finishes.

Tested at : 
atom version v0.209.0-33accdf
Linux 64bit.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/settings-view?

**Comment by mnquintana** [comment]
This issue was moved to atom/settings-view#546
