### ISSUE TITLE
Command Pallete ignores custom keymap

### ISSUE THREAD

**Issue by jwkicklighter** [atom/atom#7257]
I'm a user of IntelliJ, so I like using ctrl-shift-a for "actions," rather than the default ctrl-shift-p for "palette." I've changed my keymap so that ctrl-shift-a should toggle the command palette (and this is reflected in the Packages > Command Palette menu) but it seems stuck on the old keymap. And yes, I've restarted Atom.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/command-palette?

**Comment by jwkicklighter** [comment]
@mnquintana Sure, that should have been obvious... Sorry!

Is there a way to move an actual issue to another repo, or do I just need to open a new ticket over there?

**Comment by mnquintana** [comment]
@jwkicklighter You can just close this and open a new issue in the other repo. Thanks!

**Comment by jwkicklighter** [comment]
Closing, moved issue to command-pallet: https://github.com/atom/command-palette/issues/49
