### ISSUE TITLE
Fetching featured packages failed cause of node bad option

### ISSUE THREAD

**Issue by tychotatitscheff** [atom/atom#7259]
Fetching featured packages failed.
/usr/share/atom/resources/app/apm/bin/node: bad option: --harmony_collections

Im quite surprised to be the first to report this (or I just cant search).
Anyway, if using iojs, --harmony should be enough no ?

Atom version : 0.208.0 (cant' update with apm update :: same error)
Iojs verion : 2.2.1

**Comment by kevinsawicki** [comment]
Can you run `/usr/share/atom/resources/app/apm/bin/node -v` and include the output here?

**Comment by reinei** [comment]
As this issue is still pertaining for me as well I am going to post my output here:
`/usr/share/atom/resources/app/apm/bin/node -v` outputs `v3.0.0` for me on atom 1.0.6.
`iojs --version` outputs `v3.0.0` as well (as expected)

**Comment by voor** [comment]
This issue is still happening with `node -v` returning `v4.1.1`

**Comment by 50Wliu** [comment]
This should be fixed in the next version of Atom.  See atom/apm#449 for more details and the fix.
