### ISSUE TITLE
Upgrade to chrome 43 (atom/electron)

### ISSUE THREAD

**Issue by bpmarinho** [atom/atom#7264]
Hello,

Can you please consider updating atom/electron module due to an issue with Chrome prior to 43? Check issues atom/electron#1955 and atom/electron#1478 for more detail.

Thank you,

Bruno

**Comment by mnquintana** [comment]
Thanks for opening this! This is definitely going to happen though, but only when it's ready and only when several show-stopping bugs have been fixed, and no sooner, unfortunately. You can check out https://github.com/atom/atom/pull/6877 for some context.
