### ISSUE TITLE
Themes won't uninstall

### ISSUE THREAD

**Issue by PierBover** [atom/atom#7265]
When I click 'uninstall' nothing happens. Neither the community nor the core themes. The console doesn't throw anything either.

Does anyone else experience this?

I'm 0.209.0

**Comment by izuzak** [comment]
@PierBover Yeah, I'm seeing that as well -- when you click uninstall, nothing happens. However, if you reload Atom -- the themes should be uninstalled. Are you seeing that behavior?

Also, you can't uninstall core themes, I believe -- the settings button for core packages and themes should now be shown, but it is currently (which is a bug https://github.com/atom/settings-view/issues/252).

**Comment by izuzak** [comment]
Also, there's something similar reported over at https://github.com/atom/settings-view/issues/529 -- I'll add a comment there about this and close this out. Thanks for the report!

**Comment by PierBover** [comment]
@izuzak Yes, when I reload Atom the themes are gone.
