### ISSUE TITLE
feature request: back button

### ISSUE THREAD

**Issue by Billybobbonnet** [atom/atom#7266]
Hey,

Either natively or using a plug-in, I would love to have a back button showing in top left corner, when mouse is hovering the file tree-view, in order to go back to the last focused file. Or is there a way to set a shortcut on it in the keymap?

I owe you some sweet words too: I love atom, please folks, keep up the good work.

**Comment by esam091** [comment]
@Billybobbonnet does [this one] (https://atom.io/packages/tab-history) do what you need? Or do you want the navigation to be specific to the tree view?

**Comment by Billybobbonnet** [comment]
It seems to be what I need, but the package is deprecated, so I can't test it. Nothing specific to the tree view, I am looking for a way to browse the most recently used/focused file (ideally browser button style + shortcut).

**Comment by batjko** [comment]
If the package is what you need, here's a good chance for you to either try and fix the deprecation yourself and submitting a pull request to that repo... or simply open an issue on it for the maintainer to have a look at it.


Note, it happens on occasion that packages get abandoned. So a step further would be to fork that repo and create your own from it.

**Comment by 1vasari** [comment]
Ctrl + Shift + T will open the last closed tab exactly the way Google Chrome does.

**Comment by lee-dohm** [comment]
We discussed this and we do think this could be pretty cool. We're going to leave this open as something that we would like to do at some point in the future. We don't know when that would be though, so we encourage members of the community to build their own thing that covers this need.

**Comment by nskitchgriddynamics** [comment]
please add +1

**Comment by chemitaxis** [comment]
The best behaviour is work like VSCode with Go->Back and Go->Forward ;)
