### ISSUE TITLE
Opening settings->packages sometimes crashes the editor

### ISSUE THREAD

**Issue by filipesilva** [atom/atom#7267]
Sometimes when I open settings, go to packages and scroll down the editor hangs and after some seconds I get the 'editor is not responding' dialog. 

I've noticed that the package list seems to be loading asynchronously and wonder if it is related. Anything I can provide that would help in replicating this?

Currently I am on windows 8 and atom 0.209.0.

**Comment by izuzak** [comment]
@filipesilva How often does this happen? Did this start happening recently or has it always been like this for you? Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by JohnMurga** [comment]
Has been happening for a few months now ...
If you follow the thread it is a dupe of this one : https://github.com/atom/atom/issues/7191
Easily reproducible by anyone running on Windows with more than a couple of packages.

**Comment by filipesilva** [comment]
You're right @JohnMurga, this is a dupe from that one. I'll close this one.
