### ISSUE TITLE
Better indicate preview tab

### ISSUE THREAD

**Issue by linquize** [atom/atom#7273]
It would be clearer to indicate preview tab by adding some visual effects.
This allows user to easily distinguish from normal tabs.
e.g. A different background color, text color or adding a special symbol.

**Comment by YuriSolovyov** [comment]
sublime does it using italic font for tab title

**Comment by linquize** [comment]
Visual Studio uses different background color and border.

**Comment by freemanoid** [comment]
> sublime does it using italic font for tab title

Atom works the same now.

**Comment by linquize** [comment]
I notice that: Italic font, like sublime

**Comment by mnquintana** [comment]
This issue was moved to atom/tabs#180
