### ISSUE TITLE
Filename highlighting is causing scrambled text

### ISSUE THREAD

**Issue by daveyjones** [atom/atom#7274]
I'm working on figuring out how to reproduce this consistently, but thought I would go ahead and get the issue started. All of the scrambled filenames are `.less` and `.css` files, which makes me think it has something to do with the `atom-compile-less` package, which compiles `.less` files into `.css` files automatically upon save.

![screenshot](https://cloud.githubusercontent.com/assets/2852617/8149540/44c793c8-127b-11e5-87b4-02be53ff02aa.png)

**Comment by mnquintana** [comment]
Thanks for the report! This is a duplicate of https://github.com/atom/atom/issues/4924 – please subscribe there for updates.
