### ISSUE TITLE
Frequent recurring freezing on Windows

### ISSUE THREAD

**Issue by remcopeereboom** [atom/atom#7275]
I am getting random freezes and crashes on Windows 7. I am using Atom version 0.209.0.

Freezing occurs randomly (i.e. not all the time) when:
- changing values in the settings window.
- opening files (infrequent, big files seem to cause crashes more often).
- installing packages
- uninstalling packages
- closing tabs

I can't find any log files to get more information. The program is completely unresponsive and devtools console is not updated.

**Comment by Stanzilla** [comment]
The freezes happen very often when installing/uninstalling packages for me, but I guess that is to be expected because everything has to update?

**Comment by remcopeereboom** [comment]
@Stanzilla Thanks for the rapid feedback.

The updating itself does not _appear_ to be a problem:

1.  I tried reinstalling Atom a few times and packages randomly freeze on some vanilla installs, but not on others. Maybe there is an order dependency, but if there is, I have yet to find it.
2. The freezes seem to be permanent (There were a few times where I let the program be for a long time).
3. I have an atom-typescript package installed which takes a whopping 1544 ms to load and as I recall it took quite a long time to install as well (and crashed the first time), but other than that all packages either install fairly rapid or freeze ad hoc.

Perhaps I should start logging the phase of the moon when working with Atom.

**Comment by nycdotnet** [comment]
See #7191.  You may be having that problem plus some other one.

**Comment by remcopeereboom** [comment]
@nycdotnet I do have the same problem. Last two tries of clicking around in the setting windows gave me lags of 21s and 24s respectively. The program did not freeze, however! Its very likely that I am misinterpreting the issue you are describing with the issue when opening and closing of large files and the issue when installing or uninstalling packages. Should I close this issue and wait for the other to resolve?

**Comment by joshburgess** [comment]
This is happening to me on Windows 8 too. Constant freezing during and sometimes after package installations. It is extremely annoying.

**Comment by benogle** [comment]
Can you guys try safe mode? Quit atom and run `atom --safe .`

**Comment by remcopeereboom** [comment]
@benogle I will try that. Might be a while before I get a chance to try though (summer holidays)...

**Comment by nycdotnet** [comment]
I can reproduce it with `atom --safe` on Windows 7 x64 (fully patched).  I clicked around between the packages, updates, and install tabs on the settings panel and did a search for "handlebars" on the install tab.

**Comment by Stanzilla** [comment]
Can probably remove the "7" from the issue title, lots of people having it on 8.x, too.

**Comment by nycdotnet** [comment]
@remcopeereboom and @Stanzilla are you behind a corporate proxy server?  I've been trying to reproduce this tonight at home (Windows 8.1 x64) and have been unable to when using no proxy and when using Fiddler as a local proxy.  I was able to reproduce the issue this week on my work computer (Windows 7 x64 on corporate LAN with proxy).  I was also experiencing this issue previously on my home PC, but I can't seem to get it to happen anymore.

**Comment by jpeddicord** [comment]
I can reproduce it on 8.1 x64 at home with no proxy. Just launched a fresh Atom session, went to settings > packages, and tried to search for "racer" -- it froze up for about 10 seconds with just an "r" in the textbox. Total hard freezes are less common, but still often enough to be annoying.

**Comment by gyf304** [comment]
Can confirm on Windows 8.1

**Comment by remcopeereboom** [comment]
Can confirm the freeze on Windows 8.1 as well. Also tried `--safe` flag. Freezes remain.

**Comment by nycdotnet** [comment]
OK it seems I can reproduce this again.  It seems that perhaps the freeze only happens when there are actually package updates waiting to be downloaded.  When I commented 6 days ago, there were no updates available and I wasn't able to repro.

**Comment by joshburgess** [comment]
I'm having a worse issue now. If I click to view the package updates, Atom crashes 1-3 seconds after loading the list of packages with updates available (not even actually updating anything yet). I tried several times, and it happened every time. It seems Atom just does not play nicely with Windows at all...

**Comment by joshburgess** [comment]
Just an update on this: I'm on OSX on the exact same hardware now and none of these issues exist. Atom is much, much better on OSX. So, it definitely seems to be a Windows-specific issue.

**Comment by jonathandelgado** [comment]
+1, seems like it's getting gradually worse lately.

**Comment by gyf304** [comment]
It seems to be a timer-triggered GC event that freezes the entire window (for around 30 seconds). I captured one but failed to dumped it since chromium immediately crashed when I tried.

**Comment by gyf304** [comment]
![capture](https://cloud.githubusercontent.com/assets/7296537/8865407/c4c7c82a-317c-11e5-903f-f832bba01d5a.PNG)
I started a capture after the window freezed. This problem is hard to reproduce. I will update if I can capture one again.

**Comment by gyf304** [comment]
Caught one. 
![capture2](https://cloud.githubusercontent.com/assets/7296537/8865483/c7883e7c-317d-11e5-8c56-d18cfdc72121.PNG)
Failed to dump it. Atom crashed right away when I tried to export raw data.

**Comment by Stanzilla** [comment]
@nycdotnet nope, no proxies.

**Comment by jonathandelgado** [comment]
Yeah, I can confirm @gyf304's findings

**Comment by gyf304** [comment]
I suspect that the reason why Mac users does not report this problem is the fact that the OSX version of atom uses 64bit version of chromium instead of 32bit in windows version. The 32bit version of v8 engine has a memory limit of ~700MB, while 64bit has a ~1400MB one. (https://code.google.com/p/v8/issues/detail?id=847) Thus more memory pressure on windows machines, and therefore more likely to trigger GCs. Just giving some ideas.

Nevertheless, the huge pile of GC events is just not normal. (memory leak in settings page?)

**Comment by vorou** [comment]
Can confirm the problem, Windows 8.1 x64, Atom 1.0.2.

I've just got "Editor not responding" dialog when I clicked "Settings" on core's autosave package. Happens all the time in other places, sometimes I see "Editor not responding", sometimes it just comes back to normal after a few seconds.

**Comment by poci-hu** [comment]
Freezes occur to me as well, tried on windows 8.1 64bit (2 different computers), Windows 10 64bit (2 different computers)

**Comment by Zireael07** [comment]
Just had Atom 1.0.3. freeze on me when I went into Settings (I wanted to disable metrics).

Scroll down a bit, freeze.

**Comment by rwese** [comment]
Updated and did my weekly freeze-testing:
Now Atom 1.0.4, just by jumping around in the settings it will freeze up for a brief period.
Windows 7, 8G Ram, no other Apps running

**Comment by blah238** [comment]
Can confirm that my settings view gets frequent freezes on my Windows 7 Enterprise SP1 64-bit desktop as well as my Windows 10 Pro 64-bit Surface Pro 3. It will usually prompt me with the Editor not responding dialog, and if I tell it to wait, it will eventually unfreeze. But it is very annoying. Please fix this!

**Comment by Sukumi** [comment]
Version 0.202 - 1.07: Same for me. Hanging...freezing...not a workable product. I did my smokey test on a Win 7, 64 bit machine, 8 cores, 32GB RAM. The crash likelihood is higher on pre 1.00 releases.
So, my advice here: Fire your windows test crew! And maybe increase your realease cycles by more thoroughly testing for the windows env. Is ther a windows test bed at all. Beside, I cannot find your unit tests neither in code nor with travis setup. Maybe you can guide me here. Travis setup includes anyway only a linux setup. ANNOYING...when I read that marketing blabla on your site. Sorry for my rude message but with my over 20 years background in SE. i allways get annoyed when i see these well known engineering anti-patterns more and more in many ambitious open source projects.
Maybe I had to much of that in the last year....ahhahhaha. 
Besides for me its looks like an issue of dealing properly with the well known (node.js) Javascript Event Loop constraints but you are the experts...
Everything gets solved sometimes...

![atom-0 211-win7-32gb-ram-8core](https://cloud.githubusercontent.com/assets/13113872/9293779/6e805daa-4438-11e5-8ba4-10d787a0c320.PNG)
![atom-1 0 7-win7-32gb-ram-8core](https://cloud.githubusercontent.com/assets/13113872/9293780/6e80fd6e-4438-11e5-90f4-0e4891d2d5be.PNG)

**Comment by Sukumi** [comment]
To stress this: I have tested the behavior on all versions since 0.202.....!!!!!

**Comment by gyf304** [comment]
I suggest changing the title of this issue to "Frequent recurring freezing on Windows". Since the issue is neither non-reproducible nor limited to Windows 7. @remcopeereboom Also I would like to see someone assigned to this problem asap. I encounter this bug on daily basis.

**Comment by rugk** [comment]
I already encountered this issue (see https://github.com/atom/atom/issues/8458) but it's not really good to reproduce.
And at least in my case it's just some seconds I have to wait while installing packages.

> I suspect that the reason why Mac users do not report this problem is the fact that the OSX version of atom uses 64bit version of chromium instead of 32bit in windows version. The 32bit version of v8 engine has a memory limit of ~700MB, while 64bit has a ~1400MB one.

This could indeed be as Atom regularly uses 600 MB RAM in all processes. (at least this is how much it uses now...)

**Comment by rugk** [comment]
After installing [language-ini](https://atom.io/packages/language-ini) Atom again froze. But this time the 25% CPU usage stayed the same even after Atom wasn't freezing any more.

As you can see also the RAM usage got higher. (2nd graph)
![atomcpu](https://cloud.githubusercontent.com/assets/11966684/9423590/31186b56-48ca-11e5-8256-b821d2c60be6.PNG)

The process which caused this was the one executed with this commando line:

    "C:\Users\%username%\AppData\Local\atom\app-1.0.7\atom.exe" --type=renderer --js-flags=--harmony --no-sandbox --enable-deferred-image-decoding --lang=de --node-integration=true --subpixel-font-scaling=false --device-scale-factor=1 --font-cache-shared-mem-suffix=6964 --enable-pinch-virtual-viewport --enable-delegated-renderer --num-raster-threads=2 --channel="6964.1.1211932576\764416573" /prefetch:673131151

Here is a JS CPU profile: https://gist.github.com/rugk/dd3d92f7c2f35382e8bb
I also tried to create a JS profile (in tab 'timeline') and it showed me the graph, but when I tried to save the JSON Atom crashed.

Additionally I've created a dump of the process (> 1 GB) which was causing this, so if anyone of the collaborators wants it I can send it.

**Comment by rolyataylor2** [comment]
I don't have any specs to contribute but just my experience with this issue..

I did a clean install of windows 10 on my PC and did a clean install of the latest as of last week atom non-development release on it and it freezes and needs to be closed whenever I am in the package management section. 

It seems to happen more when installing packages, But it also happens when just loading the information about the packages. It also happens a lot when minimizing atom and switching to other windows. The load time of the package list is really really slow too. It takes 20-30 seconds to get the installed package list to come up.

Windows 10 64bit Home - 8GB Ram - ATI graphics card - Firewall with only port 80 open

**Comment by rugk** [comment]
So maybe this is more related to https://github.com/atom/settings-view/ as it often seems to be only if you interact with the packages?
So e.g. when editing text Atom doesn't freeze?

**Comment by gyf304** [comment]
@rugk It still does in my case, though much less likely to happen.

**Comment by rolyataylor2** [comment]
Once I got my packages and settings set I have been staying out of the settings menu. I had the editor freeze once outside the settings-view but it was able to come back without needing to be closed.

**Comment by rolyataylor2** [comment]
I found a sure fire way to trigger the problem on my machine at least:

Windows 10 Home x64
-- Open Atom and Task Manager
-- Open the install package section with the search
-- Wait for everything to load
-- Start a search for a package
-- Quickly minimize Atom to the taskbar and bring focus onto the task manager (before the search completes)
-- Wait for node.exe to finish and the process to dissappear
-- Unminimize Atom and it will be frozen and you will have to close it through the popup "Editor is not responding"

I think this is related to other poor performance in windows when opening big files and such. Whatever callback is being made from node or to receive info from node is not always making it back to the Atom process.

**Comment by 50Wliu** [comment]
I just hit this while trying to repro what @rolyataylor2 reported.  In my case the first freeze happened when I tried to start typing in the Install box, and the second one happened when I tried to select all inside the text box.  Both times one of the renderer atom.exe's jumped up to ~40% CPU.

**Comment by Stanzilla** [comment]
For me it just insta freezes when I click on `Packages` and it starts loading them..

**Comment by polarathene** [comment]
Have been experiencing this issue for months. Just had it occur when I was in the browser and switched to Atom via the taskbar, tried to right click to rename a file and Atom was unresponsive, checked task manager, CPU usage was about 22%-25%(quad core) by an Atom process. When it finally became responsive again I had a pop up stating Atom was being unresponsive prompting "wait/close", bit late for that :P

**Comment by batjko** [comment]
Yes it's definitely on ongoing issue, which, to be honest, is creating a ton of frustration if one is trying to get work done over a few hours.

Notably, package management seems to be at the core of this for most people, i.e. when listing, installing, updating them, some of which happens without having the Settings View open of course, so it may all boil down to that.

I think the resource consumption, while an important detail, is a bit of a red herring, when it comes to just stopping the freezing. 
Programs don't freeze just because CPU levels are high (as long as they are not at absolute capacity), but rather when they are waiting for something to happen.
It's that waiting process that needs to be identified and addressed first.

**Comment by remcopeereboom** [comment]
@gyf304
> I suggest changing the title of this issue to "Frequent recurring freezing on Windows". Since the issue is neither non-reproducible nor limited to Windows 7. @remcopeereboom Also I would like to see someone assigned to this problem asap. I encounter this bug on daily basis.

How would I go about doing that?

**Comment by jonathandelgado** [comment]
@remcopeereboom Go to the top of the issue and click on the `Edit` button, should be on the right side next to a green `New Issue` button :smile:

**Comment by remcopeereboom** [comment]
@jonathandelgado DOH! I misread the question...

**Comment by cyrilchaponeverysens** [comment]
@polarathene is accurate on those further precisions. There are more cases than just "settings" view. `F2` on some file is a failing test-case too.

```
Have been experiencing this issue for months. Just had it occur when I was in the browser and switched to Atom via the taskbar, tried to right click to rename a file and Atom was unresponsive
```

Confirmed on a fresh W10 & ATOM installation.

**Comment by musocrat** [comment]
Yeah, this one is beyond frustrating. I use sync-settings and as such have the same packages on all my machines. Yet on a Ubuntu VM updates happen within a minute or so, on the machine hosting that (Win 7) the same updates may take 5 minutes (8-core, 32GB Ram). 

Worse yet, my personal PC (i5/ultrabook/Win10) just took over 30 minutes to update 8 packages (just updated a few days ago), the entire time my CPU was pegged at 100% and my PC was unusable for anything else.

It seems lot's of CPU profiles and debugging info have been provided here but if it would help for me to gather any of that I will.

**Comment by lordgiotto** [comment]
This bug affect me too on W10, every package related task freeze Atom and ends with a force close.

**Comment by musocrat** [comment]
Is anyone else seeing that Windows Defender (MsMpEng.exe) runs wild when this is happening? That seems to be the case for me. I've tried excluding the .atom folder but that doesn't help. Just curious if this may be big part of the problem.

**Comment by KillerJK** [comment]
My windows defender is disabled. I am experiencing frequent freezes when i'm working normally, when I move lines, select text etc. The settings window is problematic, but not the only place with problems.

I disabled all my packages (which should be the same as using safe mode?) and I *think* it still happens (I'm trying to verify this). When it's frozen I click o pause in the developer menu, but nothing is displayed in the debugger. If I wait, a minute or more, I can click on continue and keep working. Sometimes it takes so long that I have to kill the editor.
I also disabled gulp, in case it was the build system watching for files being modified and there was a deadlock somewhere, but it didn't help.

I am using windows 10 professional x64, but the same thing happened in windows 8.1

**Comment by devlinjd** [comment]
Also seeing this on Win 7 + 8.1 and reproducible ~100% of the time. To echo @rolyataylor2...

>Once I got my packages and settings set I have been staying out of the settings menu

We stay out of the Settings menu here too, especially after sundown.

**Comment by looterz** [comment]
Same issue here on Win10 x64. Opening large files, opening files not in an atom instances current working directory, managing or viewing packages all consistently freeze Atom even in safe mode. It also seems to freeze randomly sometimes for a few seconds.

**Comment by mnquintana** [comment]
Are people still experiencing this with Atom 1.0.15?

**Comment by blah238** [comment]
@mnquintana So far so good here.

**Comment by AWTrost** [comment]
still happening for me.  atom 1.0.15 and mac os x 10.10.5.  every time i open settings view and select packages/themes/install it freezes the editor, even if i switch to a separate tab.  Atom-helper cpu usage spikes as well.  FWIW this seems to only be a problem the first time i try settings view after starting atom

**Comment by 50Wliu** [comment]
> mac os x 10.10.5.

@AWTrost This issue is mainly for Windows users - can you please see if #3426 covers your problem?

**Comment by AWTrost** [comment]
will do thx.  was linked here from a separate issue that was OS agnostic, my bad.

**Comment by Stanzilla** [comment]
I still get hangs but not when interacting with the package list anymore, so I guess that was fixed. Now it's when just using the editor normally, editing blade.php files, so I can probably blame the language-blade pack for that?

**Comment by jonathandelgado** [comment]
@mnquintana Seems resolved for me. Haven't noticed an issue in a while. Had some other hangs, but due to plugins running synchronously.

**Comment by mnquintana** [comment]
Alright, I'm gonna close this out then - feel free to comment if you're still experiencing this with the latest version of Atom.

**Comment by neal-morgansolar** [comment]
This issue is still occurring for me. Version 1.0.19, Win 7 x64, I have no extensions installed other than the defaults and minimap. It's been happening when switching tabs in the editor.

**Comment by 50Wliu** [comment]
@neal-morgansolar can you still reproduce this in safe mode (`atom --safe`)?

**Comment by neal-morgansolar** [comment]
@50Wliu I'll try using it in safe mode and report back. My issues with freezing have been pretty sporadic and difficult to reproduce though, sometimes it works fine for a whole day and other times it freezes constantly.

**Comment by benogle** [comment]
Reopening so we can investigate this. Seems network access is the core issue.

**Comment by Sukumi** [comment]
A thouroughly created performance profiling of the application should be the first thing do. 
Sporadic is only the occurrence of the peak values....The Editor sucks!!! Stop guessing.....setup a constraint environment, collect data (the rigth one), eval and make your  decision on that.

Setup a professional profiling toolchain instead of giving the user some profiling tools which are still not working correctly and most of the people anyway dont know how to use. 

Better..change the technology and select a more robust one which hides the developer inabilities better or change your way to solve problems and reduce complexity.

Anyway I admire the guys for selecting Java Script here and not selecting a more robust and reliable Multi-Process approach to handle concurrency....your selected approach is for sure not appropriate at least not with the java script constraints given.....

**Comment by devlinjd** [comment]
@Sukumi As a happy Atom user I gotta take offense on you beating up on our Atom devs and community! : ) Sounds like you have some strong opinions on profiling, due diligence, testing, and the like. That's good, but the rudeness is uncalled for in this channel. And if you're going to criticize a project for lack of due diligence, profiling, or hard data, it's probably a good idea to provide a single scrap of due diligence, profiling results, or hard data yourself.

**Comment by glennmate** [comment]
Windows 7 x64 user here. Have reinstalled Atom many times. Freezing when moving between tabs, editor hangs for 20 minutes+ or more. I can use all bars across the top (File, Edit View) but nothing else is responsive. I lose all unsaved work in my tabs. Very frustrating. Has happened at least a dozen times in the last month (I've been an Atom user for about 3 months). If the issue is not resolved I will be forced to move to another text editor as I can't afford to continue to lose work.

**Comment by jms19** [comment]
I have 1.1.0 on Windows 7 x64 and a VPN to work and am trying to edit files but get constant a lot of whirling circle and occasionally a dialogue from windows asking whether I should wait for it.

Using Process Monitor and filtering on Duration of more than about a millisecond it appears the thing keeps scanning the same remote directories time and time again whenever I move the pointer around.

I see lots of QueryDirectory and CreateFile on directories.

It does not have the sense to realise that the time taken to do this corresponds to the frequency with which it tries.

**Comment by phoenixjun** [comment]
It is happening for me as well on v1.4.1 on windows 7 64bit.

And it happens very often when I try to install a package

**Comment by PD75** [comment]
I have the problem consistently a moment after I paste a Url. Especially annoying when writing readme in markup, but also in js files. Once it has frozen then the presens of Url do not affect it.

**Comment by VandeurenGlenn** [comment]
Maybe not related... had freezes when changing values & switching tabs every 10 a 20 min.
yesterday I disabled 'polymer-atom' & 'linter-scss-lint', no freezes for 4 hours now :+1:

I'm running windows 10 64 bit

**Comment by megalofauna** [comment]
Like PD75, I'm having recurrent freezing when pasting URLs as well. Additionally, any edits to a block containing a URL also triggers a freeze. It's making Atom virtually unusable for me.

**Comment by megalofauna** [comment]
![2016-02-22_17-47-22](https://cloud.githubusercontent.com/assets/8394554/13236814/8499c286-d98c-11e5-820c-320cd86327ef.png)

**Comment by PD75** [comment]
As workaround I just split the url into two parts: e.g. 

`var x = 'https://'+'github.com/atom/atom/issues/7275#issuecomment-187439221'`;

Then it works fine.

**Comment by HerneWyldwood** [comment]
Freezes occur on both my machines, win10 64

**Comment by pratham2003** [comment]
I had quite a similar issue on one of my Windows PC. I found a fix which worked for me. It was to simply add atom's working directory to your anti-virus' exclusion list.
https://discuss.atom.io/t/possible-temp-fix-windows-freeze-when-switching-back-to-atom/26563

**Comment by deathgaze** [comment]
This is happening on my Mac as well. I'm running with ONE minor addon and Atom freezes like crazy. This isn't just a Windows issue.

**Comment by KeitIG** [comment]
@pratham2003 's answer definetly solved it. Add Atom to your exception list, otherwise this may happens with large projects with large .git

**Comment by rjayako** [comment]
Anyone getting this on Windows 7?

![2016-05-11 11_31_34-atom](https://cloud.githubusercontent.com/assets/398364/15187002/48ea0fec-176d-11e6-90bb-76ab8c240ca6.png)

This happens both on Stable and Beta for me. Wondering if anyone know what the issue here is? and a possible work around.

**Comment by sparcut** [comment]
@pratham2003, thanks so much! I've been pulling my hair out for the last couple of days... even went back to sublime for a little.

I'm running 1.8.0 stable, on Windows 10.

Are you still having this problem? Thread seems dead, so I'm not sure what's happened.

**Comment by pratham2003** [comment]
Cool, glad this helped :)
I haven't had the issue ever since I added atom's directory to my to my anti-virus's exception list.

**Comment by TeemuKoivisto** [comment]
I do not understand how this problem is not a top-priority for the Atom dev-team to solve. It is outrageous that I have to switch to a different editor after I accidentally open a file too big for Atom to handle which causes it to freeze. I recently switched to Sublime just because of this issue but decided to come back to see if upgrading to Windows 10 solved the issue. Nope, still freezes. And to fix it I have to reboot the whole screen. Unacceptable and makes the whole editor unusable for me.

To be fair I think the problem is partly (or mainly, idk) because of Electron that I believe Atom is based on. While beautiful idea to have JS app ported to all platforms it just still doesn't work good enough for at least Windows desktop applications (in this case particular.) While I myself am JS-enthusiastic I do believe that any good Windows app which needs to be high-performance has to be coded in some C-language. Look at Notepad++, that editor is swift as hell and I switched from it only because of lack of advanced tools.

Sigh, just please guys. Fix this issue so I might return to Atom. In mean time I guess it's Sublime for me though it lacks the small, but important details that I so like about Atom.

And no, in my case it's not because of anti-virus or anything. I've had them disabled for ages because they were only soaking all my memory while providing nothing for 99.99% of the time.

**Comment by pratham2003** [comment]
Opening up large files is a different problem.. I know, its annoying. I wonder if its go to do something with Chromium. (Same issue when I tried opening up large text files in chrome's text area..)

The problem most of the people in this thread were facing is different a bit different and was solved by adding an exception for Atom in the AV.. Btw, if you are windows 10 have you disabled windows defender? I've never used it so I'm not sure if it does affect Atom. I had Avast AV, which did affect atom.

**Comment by polarathene** [comment]
You might not like this alternative, but Atom works pretty well on OSX/Linux, I used to use Windows and remember this issue being a big pain. If staying on windows you could probably get virtual box, install linux on it and run atom with a shared folder on windows that the virtual machine uses. I think virtual box also has feature to make the atom app look native by appearing in your start bar too(if not vmware has it).

**Comment by pratham2003** [comment]
@polarathene Does opening large files or (single line minified js files) not cause a problem on OSX/Linux?

I haven't tried that yet, but on Windows sublime is able to handle opening such large files / minified files much better than Atom.

**Comment by TeemuKoivisto** [comment]
I have dual boot with Ubuntu but there's too many bugs with it that annoy me plus I have all the games with Windows and with Node.js it's not that mandatory to do development with Unix-based OS. And first thing I did was disable all the crap of Windows 10. Though it seems you can't stop Windows Update from updating automatically anymore. Also now that Windows 10 has bash I could possibly do ssh'ing without too much pain.

Shame though that only solution is to either switch OS or use different editor. I'm not a fan of Windows (or Microsoft for that matter) but Windows is too convenient for me and it's too much trouble to always reboot when I want to do some coding.

**Comment by polarathene** [comment]
@pratham2003 Atom doesn't have the recurring freeze problem which this issue is about on OSX/Linux in my experience, nothing like when I used Windows. The work I do with Atom rarely need to edit large files, it still have some trouble with large files I think. I remember 15k+ lines and use regex cause some problem. Discussing further is off topic for this issue.

@TeemuKoivisto You could still try the virtual box vm method I suggested earlier while using windows as host.

**Comment by joshburgess** [comment]
@TeemuKoivisto It's worth noting that Visual Studio Code also uses Electron and has none of these problems. It might not be quite as quick as Sublime, but it's quite fast and runs much better than Atom. While Atom does run better on OSX/Linux, it's still quite slow and does run into these freezing/crashing issues at times.

**Comment by Multi-Thinker** [comment]
Still not resolved. I've same issue.. even with `--safe` it is still freezes..

**Comment by TeemuKoivisto** [comment]
@Multi-Thinker I actually saw some improvement when I did reinstall&update of Atom. Now it runs much smoother and has crashed much more infrequently. Dunno why but I'm happy 😄. And last week I bought a new laptop from which I'm using it so maybe the extra RAM and cores help too. Probably it was/is something about Electron where the problem lies and issuing the problem here doesn't do much except show the symptoms

**Comment by Multi-Thinker** [comment]
@TeemuKoivisto I've tried to reinstall and update, I've also tried removing my packages to improve performance, the thing is my project folder is about 1.88 GB in size, may be atom can't handle this size.. anyway I just moved to Visual Studio Code, everything is running smoother in it. atom used to be a great editor.

**Comment by sumurthy** [comment]
I tried several times and gave up on atom editor on Win10. The Mac version works just fine; but desktop version seems to be below par in terms of quality.

**Comment by hellofedorov** [comment]
Atom edit freezes on Win10. I already had tried to run edit in safe mode. I Tried to uninstall all packages. But it don't help me. I write a HTML (fizesize=60kb) with scripts into code. And when I write quotes (""), editor freezes. How I can send log for you? How I can decide this issue?

**Comment by TeemuKoivisto** [comment]
@Multi-Thinker Well I have to say I was positively surprised by the Visual Code's robustness and its core features such as [IntelliSense](https://code.visualstudio.com/docs/editor/intellisense) which makes JavaScript programming less painful. I'm currently testing it out and seeing if it's good enough for my needs which it as of now seems to be doing. Maybe having support for multiple project folders open in same window would be nice but oh well. It definitely has less packages but I don't really need that much.

Also I apparently forgot that VS is also made with Electron as josh pointed out and they have implemented properly working file reader for Windows compared to Atom. Maybe someone with time on their hands could locate how VS' does it differently and copy it to Atom from their [GitHub repo](https://github.com/Microsoft/vscode)

**Comment by alex7egli** [comment]
Same issue here. Atom freezes when I open it and it is unusable. On Windows 10. It was working fine yesterday and I haven't made any changes since yesterday, but this morning it freezes when I open it. This happened a couple days ago too but I remember cleaning some sort of atom cache and it fixed it. I'm switching back to visual studio since atom just isn't usable on windows.

**Comment by GrahamHannington** [comment]
Atom (I'm currently at 1.12.9) on Windows 10 frequently crashes. I'm only editing small files (maximum of a few hundred lines).

**Comment by pcj** [comment]
Seeing same behavior (frequent freeze) Windows 10, Atom 1.12.9.  Often takes multiple tries to re-open as document restore sometimes freezes also.

**Comment by capey0** [comment]
I am getting the same issues. 
Windows 7 64 bit
Atom 1.13.0 ia32
Chrome 55.0.2883.87 m (64-bit)

Sometimes it freezes permanently, other times the file menu remains "usable" and selecting "File =>Exit", it will remain open for quite a while then close.

Weird

**Comment by nopm** [comment]
Windows 10 64 bit, same issues.
For me, when I alt-tab into Atom, it freezes for a second, and then goes back to normal, until I repeat.
I looked at my task manager, and, whenever I alt-tab, it closes one process and opens it again. I don't know if this is 100% related, but it's really painful to use Atom right now. Version 1.14.3.

**Comment by 50Wliu** [comment]
@nopm your issue is most likely #9544.

**Comment by nopm** [comment]
Thanks @50Wliu

**Comment by eduardomart** [comment]
Same here, now my projects won't even open after latest freeze

MacOS 10.12.4
Atom 1.16.0

**Comment by 50Wliu** [comment]
@eduardomart This bug is specific to Windows.  Please open a new issue.

**Comment by Multi-Thinker** [comment]
It's a shame for atom developers if they feel. not only they are lazy to fix this, they are not brave enough to point out this issue and admit their faults. I've submitted my comment on this loooong time ago, and still atom behavior is the same. 

Shame.

**Comment by lee-dohm** [comment]
@Multi-Thinker your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by Multi-Thinker** [comment]
@lee-dohm I was not expecting this, instead of considering that an insult please consider that a feedback from a frustrated user who is mainly watching this thread for solutions to the problem he reported months ago. anyway, don't worry I'm not watching or using atom anymore. so, I won't bother you anymore.

**Comment by megalofauna** [comment]
Several months ago, I posted this (you can find it above): 

"Like PD75, I'm having recurrent freezing when pasting URLs as well. Additionally, any edits to a block containing a URL also triggers a freeze. It's making Atom virtually unusable for me. 

Atom is up to date.

I'm on Windows 10 64-bit. "

I don't recall what release mitigated this issue, but I'm not having nearly the trouble I once was with edits to a block containing a URL. For example: typing "http://placehold.it/500x500" into the `href` of an anchor tag back then would have frozen Atom for 10-15 seconds. 

Now it freezes for 1.5-3 seconds. 

Not awesome, but acceptable to me. 

Again, don't know what release reduced this lag, but grateful for it and wanted to comment.

**Comment by 50Wliu** [comment]
@megalofauna I just took a look at the profile you captured and it seems like the culprit is one of the autocomplete providers that you have installed.  You can find the list of packages you've installed using `apm list --installed`, or you can try using the [package-cop](https://atom.io/packages/package-cop) package to determine which package is causing the slowdown.

**Comment by Stanzilla** [comment]
filepaths one is super outdated and caused that for me back in the day

**Comment by megalofauna** [comment]
Thank you @50Wliu and @Stanzilla! Disabled autocomplete-paths and the problem is, indeed, gone.

**Comment by MileanCo** [comment]
My latest Atom v1.19.0-beta2  on Windows 10 freezes constantly (every 5 seconds), it's totally unusable. I cant write code. It used to work pretty well a few months ago.
My computer is running fine, CPU usage around 10%, disk ~2%, memory ~40%. 

I'm uninstalling Atom from my computer until this is fixed. UNACCEPTABLE.

**Comment by thomasfrobieter** [comment]
I'm on Windows 10 with Atom 1.18.0 x64 (tried the current beta release also). As @MileanCo say's, productiv work isn't possible anymore. Starting in safe mode does not solve the issue.

Let me know if i can provide some more informations.

**Comment by xlog2x** [comment]
On a Windows 8.1 x64-  Intel i7 
AtomSetup-x64.exe  FREEZES windows at double click for install and hard shutdown required.
UNABLE TO INSTALL.

**Comment by 50Wliu** [comment]
@MileanCo, @thomasfrobieter make sure you don't have a `.git` folder in your home directory.  If you do, try temporarily renaming it to `.git-backup` (`.git-backup.` on Windows).

**Comment by thomasfrobieter** [comment]
@50Wliu Thank you for the hint, but in my case it's clearly related to our SFTP software WinSCP. In other word's: While editing local files everything is working fine. But if i try to edit files by open them "directly from an ftp source" (WinSCP copy them to the Windows temp folder) Atom freezes every 5 seconds or so.. No problems using Visual Studio Code.

**Comment by download13** [comment]
@thomasfrobieter I wonder if it has something to do with monitoring files for changes.

**Comment by JPustkuchen** [comment]
For me the issue appeared after updating to 1.19.2. The file name was always flickering when opening files through WinSCP directly which are located in the windows TEMP directory.

For me it was this project causing the issue: https://atom.io/packages/tree-view-git-projects
If someone can confirm that, we should create a new issue there and link it!

**Comment by JPustkuchen** [comment]
I created https://github.com/JavascriptIsMagic/tree-view-git-projects/issues/13 as followup to my comment above.

**Comment by kimolatino** [comment]
Same problem on windows 10 with xps 13 ,16 gb and ssd
I am going to uninstall it

**Comment by JRudransh** [comment]
I am using Atom Beta in Kali Linux. It stopped working when i open a project folder. How to fix it?

**Comment by JRudransh** [comment]
# I solved this..
>### I just uninstall atom and remove the folder .atom and reinstall it.
# My problem is gone.

**Comment by JRudransh** [comment]
# I figure out the real problem.
>### When you install the package `Pigments`, This error occurs.
## Basic solution is just remove the package `Pigments`.

> # I solved this..
> 
> > ### I just uninstall atom and remove the folder .atom and reinstall atom editor.
> 
> # My problem is gone.

**Comment by JRudransh** [comment]
# I figure out the real problem.
>### When you install the package `Pigments`, This error occurs.
## Basic solution is just remove the package `Pigments`.
