### ISSUE TITLE
Atom crashes if CIFS drive is remounted on Mac OS

### ISSUE THREAD

**Issue by abdulla** [atom/atom#7276]
Atom crashes if the underlying CIFS drive is unmounted and then remounted. This happens often if I lose a network connection.

**Comment by 50Wliu** [comment]
Hi @abdulla, what Atom version is this?  Can you reproduce your crash in safe mode (`atom --safe`)?

**Comment by abdulla** [comment]
Hi @50Wliu, it's version 0.209.0. It does not seem to happen in safe mode.

**Comment by 50Wliu** [comment]
In that case, one of your installed packages is most likely causing the crash.
You can try using the [package-cop](https://atom.io/packages/package-cop) package by @mark-hahn to try to figure out which one is causing it.

**Comment by abdulla** [comment]
Hi @50Wliu, how do I debug this on crash? It takes out the whole editor, and I'd just like to see a stack trace so I can figure out what's going on. It seems when Atom crashes, I can't open the dev tools. This is driving me nuts, as it happens multiple times each day, and takes out the whole editor. On restart, the editor has lost all state.

**Comment by 50Wliu** [comment]
Is this still happening on Atom 1.0.19, and have you tried disabling individual packages to see which one is causing the issue?
