### ISSUE TITLE
Crash: Copy-Paste and Save As Javascript File

### ISSUE THREAD

**Issue by xErik** [atom/atom#7279]
(0. Generate Syntax Theme)
1. Copy Javascript from Sublime 3.
2. Paste Javascript into Atom.
3. Save as example.js

Atom freezes at step 3 and CPU is at 100%.
Issue is independent of selected theme.
Sometimes it works as expected, sometimes not.

Atom 0.209.0
Yosemite 10.10.3

**Comment by mnquintana** [comment]
Have you followed the steps in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)? Can you reproduce this in safe mode? (`atom --safe`)

**Comment by xErik** [comment]
My best guess it that it was related to the theme I was writing. 
After a second problem came up I completely reinstalled Atom and this, the first problem is not reproducible any more, although it was before.
Therefore, I close this issue.
