### ISSUE TITLE
Defaults aren't customizable

### ISSUE THREAD

**Issue by evandentremont** [atom/atom#7287]
Running into issues with line endings and tabs/spaces, I have to collaborate with users using jEdit and they *absolutely* require tabs / no spaces, and unix line endings. 

I can't configure this in Atom and my only options are plugins that need run manually; I have to change editor at work if these aren't configurable!

**Comment by maxbrunsfeld** [comment]
Soft tabs are configurable via the setting `editor.softTabs`, or via the `Soft Tabs` checkbox in the `Editor` section of the settings view.

Line endings should be selected based on the existing contents of the file. Could you describe exactly the situation in which case you're seeing the wrong newline style?

**Comment by evandentremont** [comment]
Soft tabs setting literally does nothing for me. Still tries to default to
spaces if any in the file are spaces.

Same with new lines, every time I open a file, and save it, I end up with
600 lines changed causing issues with our diffs.

I'm simply opening a file from the local machine or through remote-ftp
plugin, same issue on both.

**Comment by maxbrunsfeld** [comment]
> Soft tabs setting literally does nothing for me. Still tries to default to spaces if any in the file are spaces.

I can't reproduce this. If I open a file that uses tabs for indentation (e.g. [a part of jquery](https://raw.githubusercontent.com/jquery/jquery/master/src/core.js)), the editor automatically detects that it does not use smart tabs. From the console:

```js
atom.workspace.getActiveTextEditor().usesSoftTabs()
// false
```

When I type `Tab` at the beginning of the line, it inserts a tab (not two spaces). Can you reproduce this using `atom --safe`?

**Comment by evandentremont** [comment]
The newline issue was the whitespace plugin mangling empty lines, by design unfortunately. After disabling the entire plugin I don't seem to have the tabs issues either not sure whats up there.
