### ISSUE TITLE
Atom using a lot of memory

### ISSUE THREAD

**Issue by FlyingPumba** [atom/atom#7291]
Hi there, I'm running Atom version 0.209 on Ubuntu 14.04 and it's very laggy.
I have 8GB of RAM, but `htop` shows that Atom itself is eating 2GB (not counting the virtualized memory: 7.5GB).
Right now I'm ruinning 2 windows of Atom, with several files opened in each one.
Is this normal ? Is it just me or the OS I'm running ? Is there a way to make it consume less memory ?

**Comment by benogle** [comment]
Does it happen in safe mode? Check out the [debugging document](https://atom.io/docs/latest/hacking-atom-debugging) for more info.

What specifically is laggy?

**Comment by FlyingPumba** [comment]
@benogle I didn't know about the safe mode. Just closed and opened again with safe mode.
Now it's working fine (although It's been opened for a few minutes, while before I had been working for several hours), ```htop``` shows Atom is comsuing only 220 MB of RAM.
It was laggy when I typed and when I moved the cursor within the text.
MIght it be that the Atom packages I use are causing the RAM eating as showed before ?

**Comment by benogle** [comment]
> MIght it be that the Atom packages I use are causing the RAM eating as showed before

Yeah, if it's fast in safe mode, then a package is causing the slowdown. Can you paste in the packages section from the result of `apm list`? Maybe one of them will jump out as the culprit.

**Comment by batjko** [comment]
Also, out of interest, did you have the same files open as before, when you ran it in safe mode?

**Comment by FlyingPumba** [comment]
@benogle Here it goes:
```
/home/user/.atom/packages (10)
├── git-control@0.3.0
├── git-plus@5.1.2
├── git-tab-status@1.9.2
├── language-latex@0.6.1
├── language-x86@0.1.0
├── latex@0.24.1
├── latexer@0.2.3
├── merge-conflicts@1.3.2
├── pdf-view@0.22.0
└── tualo-git-context@0.6.9
```
@batjko Yes, same files.
I also tried one more thing. I opened 2 Atom windows with the same files (but w/o the safe mode) and instead of using 220 MB RAM, it uses 555 MB right from the beginning. It's not the 2GB from before, but it sure is more than in safe mode.

**Comment by maxbrunsfeld** [comment]
@FlyingPumba if you're interested in helping narrow it down, here's something you could try.

1. Disable all of your third-party packages (add this to your `config.cson`)

  ```coffee
  '*':
    'core':
      'disabledPackages': [
        'git-control'
        'git-plus'
        'git-tab-status'
        'language-latex'
        'language-x86'
        'latex'
        'latexer'
        'merge-conflicts'
        'pdf-view'
        'tualo-git-context'
      ]
  ```

2. Start Atom with the same files that you mentioned.
3. Take a heap snapshot (`Profiles > Take Heap Snapshot` in the dev-tools)
4. In the console, run this:

  ```js
  for (var name of atom.config.get("core.disabledPackages"))
    atom.packages.activatePackage(name);
  ```

5. Take a second heap snapshot
6. View the difference between the two snapshots (Select `Comparison` instead of `Summary` from the drop-down menu).

You can sort by `Retained Size` to see what is taking up so much memory.

**Comment by FlyingPumba** [comment]
@maxbrunsfeld Thank you for the detailed instructions ! i'm really interested in helping to make Atom better. I did as you told me:
The function that seems to be the Retainer of some huge chunks is something called ```Symbol Provider```. There is a huge amount of symbols (strings) in what looks like an array.
I wish I could share the heap snapshots with you, but the save function seems to be broken (0 Kb files produced after saving). Is there a way to workaround this in order to share the information ?
If you need more info, please don't hesitate in asking.

**Comment by maxbrunsfeld** [comment]
> The function that seems to be the Retainer of some huge chunks is something called Symbol Provider. 

Interesting. That object is part of the `autocomplete-plus` package, so I would think that it would use a similar amount of memory whether the 3rd-party packages were enabled or not. So just to double check: you were seeing the `SymbolProvider` use a lot of memory in the `Comparison` between the two snapshots?

**Comment by FlyingPumba** [comment]
@maxbrunsfeld Sorry for the delay, that's correct.

**Comment by maxbrunsfeld** [comment]
> I wish I could share the heap snapshots with you, but the save function seems to be broken (0 Kb files produced after saving). Is there a way to workaround this in order to share the information ?

It seems that this is a known electron bug on Linux: https://github.com/atom/electron/issues/1795.
