### ISSUE TITLE
um, reloaded Atom and now its stuck being chrome?

### ISSUE THREAD

**Issue by mcansh** [atom/atom#7292]
reinstall doesnt do anything, and deleted every file that has any relation to atom doesnt fix. will post more info if you need it
![screen shot 2015-06-16 at 2 48 47 am](https://cloud.githubusercontent.com/assets/11698668/8177392/4ffc43f8-13d2-11e5-9d0c-48eaed193dcb.png)

**Comment by mnquintana** [comment]
> deleted every file that has any relation to atom doesnt fix

What files did you delete, exactly? Have you tried following the steps in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)? Can you reproduce this in safe mode? (`atom --safe`)

**Comment by batjko** [comment]
Essentially, you're opening Electron, which is then trying, but unable to open the Atom app.

Quite often, that's a permissions thing. Either on the application folders or the .atom folder where the settings and packages are saved.

**Comment by mcansh** [comment]
@mnquintana deleted atom with appcleaner to remove files.

**Comment by mnquintana** [comment]
@mcansh I suspect that AppCleaner didn't find the `~/.atom` config directory, and that there's something in there causing this. Can you post the error from the console?

**Comment by mcansh** [comment]
um yeah deleted a theme that was left behind and its well fixed ¯\_(ツ)_/¯
