### ISSUE TITLE
Crash Atom after opening a project soon

### ISSUE THREAD

**Issue by pastak** [atom/atom#7293]
Atom crashed after opening a project. I can open other project with Atom.

Atom: Version 0.209.0 (0.209.0)
MacOSX: 10.10.3

Atom Helper crash log is here: https://gist.github.com/pastak/86fed366ae83cf3763f2

**Comment by mnquintana** [comment]
Does it crash consistently with this particular project? Or was it a one time thing? If it does crash consistently, can you reproduce this in safe mode? (`atom --safe`)

**Comment by pastak** [comment]
@mnquintana 

Thanks for your response.

> Does it crash consistently with this particular project?

I reproduce this project every time.

> can you reproduce this in safe mode? 

I can open this project in safe mode.

**Comment by mnquintana** [comment]
@pastak Thanks for the update! If you can't reproduce this in safe mode, then it's being caused by a community package. Can you post a list of your installed packages? (`apm list --installed`)

**Comment by pastak** [comment]
My installed packages list is here 
```
% apm list --installed
/Users/pastak/.atom/packages (32)
├── CoffeeCompile@0.5.1
├── Zen@0.14.0
├── atom-ctags@4.1.2
├── atom-html-preview@0.1.8
├── atom-template-engine@0.2.2
├── auto-indent@0.5.0
├── autoclose-html@0.18.0
├── background-matrix@0.0.2
├── background-utils@0.0.0
├── cakephp-snippets@0.6.1
├── color-picker@2.0.4
├── git-difftool@0.2.6
├── git-log@0.4.1
├── git-plus@5.1.2
├── git-show@0.0.3
├── go-plus@3.3.11
├── html-id-class-snippets@1.4.1
├── indent-guide-ext@0.2.1
├── jsonpp@0.0.10
├── linter@0.12.7
├── linter-rubocop@0.2.7
├── merge-conflicts@1.3.2
├── nippo@0.1.1
├── pdf-view@0.22.0
├── pigments@0.7.2
├── project-manager@1.15.10
├── quickrun@0.3.0
├── sort-lines@0.11.0
├── test-package@0.0.0
├── vim-mode@0.53.0
├── visual-bell@1.0.0
└── web-view@0.3.0
```

**Comment by pastak** [comment]
I can open this project after removing `.ctags` files.

And I find out same issue on yongkangchen/atom-ctags https://github.com/yongkangchen/atom-ctags/issues/107 .

Thanks for your supports!
