### ISSUE TITLE
language-xml upgrade: missing information in GUI

### ISSUE THREAD

**Issue by kgrossjo** [atom/atom#7297]
When I start Atom and search for upgrades, I see that a new version is available:

![atom upgrade language-xml](https://cloud.githubusercontent.com/assets/211020/8182915/61f5179e-1434-11e5-90e4-bdffbc301d19.png)

When I then click update, I see that it downloads stuff and then it claims success:

![atom upgrade fake success](https://cloud.githubusercontent.com/assets/211020/8182940/8be81ae2-1434-11e5-9278-7c4fc229ca35.png)

But the next time I start Atom, I'm back at square one.

Only the `apm` command gives me the full story:

![atom apm upgrade message](https://cloud.githubusercontent.com/assets/211020/8182960/bb302542-1434-11e5-98a3-ee743a117632.png)

The issue is that this message from the command line should also be represented in the UI in some way.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/settings-view?

**Comment by kgrossjo** [comment]
Thank you, @mnquintana.  This is now https://github.com/atom/settings-view/issues/548.  I am closing this ticket.
