### ISSUE TITLE
HTML script tag comment issue

### ISSUE THREAD

**Issue by mixmatch** [atom/atom#7298]
Atom attempts to comment HTML script tags with JavaScript comments:

Example Code: 
```html
<script src="script.js"></script>
```

First toggle comment (Edit > Toggle Comments/ ctrl+/)
```html
// <script src="script.js"></script>
```

Second toggle comment (Edit > Toggle Comments/ ctrl+/)
```html
<!-- // <script src="script.js"></script> -->
```

**Comment by mixmatch** [comment]
Only happens if there is an indent before the tag as well.

**Comment by mnquintana** [comment]
This is a duplicate of https://github.com/atom/language-html/issues/4 – please subscribe there for updates.
