### ISSUE TITLE
Clicking "Move to Trash" again before operation is complete crashes Atom

### ISSUE THREAD

**Issue by harangue** [atom/atom#7301]
If I am deleting a file via the tree view in Atom, (right-click, "Delete") and I click the Move to Trash button twice, Atom crashes.

**Comment by mnquintana** [comment]
What OS are you using? What version of Atom?

**Comment by J4G-** [comment]
Windows 8.1 64 bit, 0.209.0

**Comment by damieng** [comment]
Not able to repro - might have been fixed by the many changes since Atom 0.2.
