### ISSUE TITLE
changing pane focus key bindings

### ISSUE THREAD

**Issue by PierBover** [atom/atom#7302]
For some reason I can't change both keybindings for `window:focus-previous-pane` and `window:focus-next-pane`. Only the one that comes later in my `keymap.cson` gets mapped, and the one that comes first doesn't get mapped.

In this case only `window:focus-next-pane` gets mapped correctly.

    'body':
      'ctrl-alt-cmd-left': 'window:focus-previous-pane'
    
    'body':
      'ctrl-alt-cmd-right': 'window:focus-next-pane'

I'm on version 0.209.0

**Comment by mnquintana** [comment]
Atom's config files (including `keymap.cson`) are a simple key-value format just like JSON (but CSON), which means that keys must always be unique. If you repeat keys, then only one of those values will actually be registered. In your example above, `'body':` is the key which must be unique, but it's repeating twice. This should fix it:

```cson
'body':
  'ctrl-alt-cmd-left': 'window:focus-previous-pane'
  'ctrl-alt-cmd-right': 'window:focus-next-pane'
```

**Comment by PierBover** [comment]
Oh that makes sense :P
