### ISSUE TITLE
Highlights don't display when empty

### ISSUE THREAD

**Issue by Veedrac** [atom/atom#7311]
Currently empty highlights are filtered out [(text-editor-presenter.coffee#L1265)](https://github.com/atom/atom/blob/ebc5758d79e421f61f2b6669a886a27ee7283816/src/text-editor-presenter.coffee#L1265). This is often not appropriate.

The most trivial instance would be that 0-width searches don't show up. I've also attempted to port some Sublime Text extensions to Atom over the past couple of days ([APNG example for Firefox users](https://camo.githubusercontent.com/97b96893061473f506d82956066c4de860595e9f/687474703a2f2f692e696d6775722e636f6d2f636b6d386c356f2e706e67), and [a second for good measure](https://camo.githubusercontent.com/13fcea428dc0584ff4fd4ec703b8551215c116c0/687474703a2f2f692e696d6775722e636f6d2f667550796547362e706e67)) which also wanted this functionality. This is because they use markers to emulate "stored" cursors, which naturally includes empty cursors.

One related misfeature is that edits that touch the edge of a region are added to the region. In Sublime, they are not, which means that empty regions will stay empty. It's also a more useful behaviour generally. If empty highlights are added to Atom, it's imperative that they (at least optionally) not grow when the text to their side is edited.

**Comment by maxbrunsfeld** [comment]
> One related misfeature is that edits that touch the edge of a region are added to the region. In Sublime, they are not, which means that empty regions will stay empty.

This depends on whether or not the marker currently has a 'tail'. See [the marker docs](https://atom.io/docs/api/v0.209.0/Marker#), specifically `::markPosition` vs `::markRange`, and `::clearTail` and `::plainTail`.
