### ISSUE TITLE
Renaming a file closes it

### ISSUE THREAD

**Issue by p2kmgcl** [atom/atom#7315]
- **Behaviour expected**: renaming a file keeps the file with it's new name opened.
- **Behaviour found**: the file is closed and you have to open it manually.
- **Main problem**: if you have not an opened project you have to search again for the file in order to open it.
- **Errors**: no error found at developer tools or running Atom from console.
- **Tested on**: Atom 0.209.0 installed on Archlinux from Aur.

Use case:
![Renaming file closes it](https://cloud.githubusercontent.com/assets/800645/8200424/1ed8fbce-14c5-11e5-9539-921e50ebfa10.jpg)

**Comment by batjko** [comment]
Interesting.
I cannot reproduce this on Windows. It renames my file just fine and keeps it open in the current window.

Could it be a permissions issue on the file itself?

I don't have access to my Linux machine right now, but I'll try that later today.

**Comment by dteskera** [comment]
i'm having the same problem on debian testing.
just upgraded to 0.210.0 problem still exists.

P.S. safe mode doesn't help.

**Comment by andya9** [comment]
I can confirm this too on archlinux, atom 210

**Comment by mnquintana** [comment]
Can you post your config.cson here?

**Comment by andya9** [comment]
@mnquintana Here:

"*":
  "exception-reporting":
    userId: "a30036e2-8df4-c5f1-1a9b-070f29c48c29"
  welcome:
    showOnStartup: false
  core:
    audioBeep: false
    autoHideMenuBar: true
    projectHome: "/data"
    disabledPackages: [
      "language-make"
      "autocomplete-css"
      "autocomplete-html"
      "autocomplete-plus"
      "autocomplete-snippets"
      "autosave"
      "autoflow"
      "background-tips"
      "deprecation-cop"
      "incompatible-packages"
      "language-c"
      "language-clojure"
      "language-csharp"
      "language-gfm"
      "language-go"
      "language-java"
      "autocomplete-atom-api"
      "language-mustache"
      "language-objective-c"
      "language-perl"
      "language-property-list"
      "language-ruby"
      "language-ruby-on-rails"
      "language-sql"
      "language-toml"
      "language-yaml"
      "markdown-preview"
      "open-on-github"
      "package-generator"
      "spell-check"
      "timecop"
      "welcome"
    ]
  editor:
    invisibles: {}
    fontFamily: "DejaVu Sans Mono"
    softWrap: true
    softWrapAtPreferredLineLength: true
    zoomFontWhenCtrlScrolling: false
    showInvisibles: true
    fontSize: 18
  "tree-view":
    showOnRightSide: true
    hideVcsIgnoredFiles: true
  "bracket-matcher":
    autocompleteBrackets: false
    autocompleteSmartQuotes: false
    wrapSelectionsInBrackets: false
  "atom-terminal":
    app: "xterm"
  "atom-beautify":
    html_wrap_line_length: 0
    analytics: false
  "one-dark-ui":
    fontSize: 11
  linter:
    ignoredLinterErrors: [
      "tidy"
    ]
  emmet:
    extensionsPath: "~/.config/atom/emmet"
  "linter-tidy":
    tidyExecutablePath: "/usr/bin/tidy5"
  "tabs-to-spaces": {}
  tabs:
    tabScrolling: false
    usePreviewTabs: true
    enableVcsColoring: true
  minimap:
    charHeight: 3
    charWidth: 2
    plugins:
      "minimap-autohide": true
      "find-and-replace": true

**Comment by andya9** [comment]
One more thing I noticed: tree-view will not update to new name

**Comment by p2kmgcl** [comment]
@mnquintana do you one mine too? It's almost the same (maybe less long).
I've checked file permissions and nothing weird happens: everything is writable and made by the user running atom.

**Comment by andya9** [comment]
@mnquintana 
It happens also with this minimal config.cson:

"*":
  linter: {}
  minimap:
    plugins:
      "minimap-autohide": true
  "exception-reporting":
    userId: "244aebb4-8953-f482-c1a3-094e88ca055b"
  welcome:
    showOnStartup: false

By the way, what I said in my previous comment about tree-view (tree-view will not update to new name) will only happen when launching from a symlinked folder, so I think it’s related to atom/tree-view#482, not to this

**Comment by Motardo** [comment]
I have the same issue on Ubuntu 15.04 atom 0.209.0 --safe mode.
The tree-view updates with the new name, but the file gets closed.

**Comment by 50Wliu** [comment]
Yeah, I can reproduce this as well on Atom 0.211.0-ca146c9, Ubuntu 15.04.  For me the Tree View also updates to the new name.

**Comment by 50Wliu** [comment]
Ok, so after investigating a related text-buffer failure I think I have an idea of what's going on here:
* Tabs rely on the `onDidChangePath()` event to figure out where its file went.  If that event doesn't get fired, and the original file doesn't exist anymore, then the tab will automatically disappear (I'm not actually sure about this part, but it seems reasonable).
* Atom's "Rename" command uses `fs.moveSync()` internally to move the file to the renamed destination
* For whatever reason, and this seems to be the bug, `onDidChangePath()` is not fired after a `moveSync()` on Linux
* Tab suddenly realizes its file is gone and has no idea where it went, so poof.

**Comment by edjroot** [comment]
Just confirming the same issue on Ubuntu 16.04.

**Comment by pabloab** [comment]
Two years suffering this very annoying bug. Sorry to realize Linux is not used as much as Mac... @50Wliu there is something I can do? Maybe try a patch...
Ubuntu: 16.04.2 LTS, Atom: 1.13.1, Electron: 1.3.13, Chrome: 52.0.2743.82, Node: 6.5.0

**Comment by 50Wliu** [comment]
@pabloab First, try updating to the latest beta version, currently Atom 1.19.0-beta1.  Then, if you can still reproduce the issue, then try your hand at fixing https://github.com/atom/node-pathwatcher/issues/92.

**Comment by pabloab** [comment]
@50Wliu somehow seems solved now with Atom: 1.18.0, Electron: 1.3.15, Chrome: 52.0.2743.82, Node: 6.5.0.
