### ISSUE TITLE
Some text within code loses boldness

### ISSUE THREAD

**Issue by karai17** [atom/atom#7316]
![](http://puu.sh/irX8f/f334825539.png)

You'll note that some of the keywords are not bold while others are. This seems to occur frequently and arbitrarily. If I scroll the non-bold text out of view and bring it back, the bold comes back.

**Comment by izuzak** [comment]
@karai17 Can you include [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) with your reports and check the [debugging docs](https://atom.io/docs/latest/hacking-atom-debugging)? Also, please clarify which theme you are using and which types of files this occurs for you.

**Comment by karai17** [comment]
* Atom: 209
* OS: Windows 7

I feel like this issue is a regression, I only recall seeing this on recent versions of Atom.

I am writing code almost exclusively in Lua and I use the [*language-lua*](https://atom.io/packages/language-lua) package to highlight.

I am using the [*Monokai*](https://atom.io/packages/monokai) theme to highlight all of my code and the default *Atom Dark* theme for the UI.

**Comment by Zireael07** [comment]
Happens to me, too.
Using the same package-theme combo.

**Comment by izuzak** [comment]
Hmm, strange -- I'm having trouble reproducing this on OSX with the same themes.

@Zireael07 are you on Windows as well?

@nathansobo @as-cii do this ring any :bell: for you? Just wondering if I'm asking the wrong questions here and you know what this might be about.

**Comment by karai17** [comment]
Might this be a big with language-lua instead of Atom proper? Have you tested this on OS X with language-lua while writing out some Lua code?

**Comment by izuzak** [comment]
> Have you tested this on OS X with language-lua while writing out some Lua code?

@karai17 I have, but no luck. Can you share more details about how you're reproducing this? E.g. are you typing text, just scrolling, something else?

Also, you said that you think this is a regression. Would you be willing to try a few of the last versions and see which version is the last one that doesn't have this problem?

**Comment by karai17** [comment]
This seems to occur as I am typing out code. I notice this most when I am writing loops where I read the header of the loop, double-tap enter to write out the foot, then return to fill in the body

```lua
for k, v in ipairs(t) do -- 1
    print(k, v) -- 3
end -- 2
```

You will also notice that it seems to occur on whole lines, not individual keywords. That is to say, if "for" is drawing oddly, "do" will always draw oddly with it. "end" doesn't necessarily draw oddly since it is on a separate line.

I don't have time right now to test previous builds, but I may be able to tomorrow if @nathansobo or @as-cii don't come up with anything before then.

**Comment by as-cii** [comment]
Hey everyone! Thanks for reporting this issue! :bow: 

@izuzak: I think this is actually related to `monokai`, which for some reason breaks sub pixel antialiasing with its styling. I need to investigate that, but [a similar issue was reported on discuss.atom.io](https://discuss.atom.io/t/text-rendering-seems-blurry-compared-to-other-editors/13927/22) and, apparently, there's some transparent background or something similar which prevents Chromium from *correctly* painting text.

I am going to have a look later today and report what I find out here. @karai17, @Zireael07: I understand this is quite annoying. Would it be reasonable to switch to another theme (maybe one of the default ones) in the meantime this gets fixed? Thanks! :bow:

**Comment by karai17** [comment]
Whoa, that was a quick response, haha. It's annoying, but extremely minor. I'd much prefer to work with Monokai acting a little funny than switch to another theme, so don't feel like you need to rush or anything; I just wanted to let it be known as I noticed it's been happening for a couple weeks now.
