### ISSUE TITLE
Atom is messing the indent when pasting

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#7317]
A simple copy/paste operation will mess the indent level of all affected lines. 

Video: http://youtu.be/iR2YjQja_mE
Steps to reproduce: https://github.com/atom/atom/issues/7317#issuecomment-112744126

Also, there are situations in which Atom will completely refuse to paste.

Video: http://youtu.be/uVpGAkxB3EY
Steps to reproduce: https://github.com/atom/atom/issues/7319#issuecomment-112745383

**Comment by alexandernst** [comment]
Actually, this doesn't even need to be multicursor. Atom's paste is just completely broken whenever I try to replace 4 spaces by selecting them and pasting a tab character.

**Comment by izuzak** [comment]
@alexandernst Thanks for you enthusiasm in reporting problems. Could you please start including more information with your reports, as per the [guidelines for submitting issues](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)? For example, it's not clear which version of Atom you're using, which OS, which packages you have installed, whether you can reproduce the behavior in safe mode, or what your config settings are (e.g. do you have "Auto-indent on paste" enabled an whether changing that option makes a difference for you). Providing this information up front, with exact steps to reproduce the problem on a minimal example, reduces the back-and-forth and in some cases you might discover that you can fix problems yourself (e.g. by disabling a package you've installed). 

Can you provide the above information for this report, and any other relevant details?

**Comment by alexandernst** [comment]
Complete steps to reproduce this:

This is Atom .209 on Linux. `Soft tabs`, `Auto-indent` and `Auto-indent on Paste` are on. The `Tab length` is 4.

1. Open Atom (`--safe`)
2. Paste this:

```
<div>
    test
</div>
```

.3. Switch from `Plain text` to `HTML`
4. Select all and hit `TAB` 3 times.
5. Use multicursor to select the beginning of each line and then copy the first indent level of each line (4 spaces per line)
6. Convert from `Spaces` to `Tabs` (using `ctrl + alt + p -> convert from spaces to tabs`)
7. Place the multicursor at the beginning of the lines and paste the 4 spaces per line you copied in step 5.

**Comment by izuzak** [comment]
Can you also provide an answer for the second part of this question from my previous comment?

> (e.g. do you have "Auto-indent on paste" enabled and **whether changing that option makes a difference for you**).

**Comment by alexandernst** [comment]
@izuzak Yes, turning `Auto-indent` off fixes the problem.

**Comment by alexandernst** [comment]
@izuzak Do yoo need any more information? I'm wondering because the tag is still there.

**Comment by maxbrunsfeld** [comment]
This fix will be in Atom 0.210.

**Comment by alexandernst** [comment]
@maxbrunsfeld Don't forget that this issue has 2 parts. Is this commit fixing both?

**Comment by maxbrunsfeld** [comment]
Like I said on your other issue (https://github.com/atom/atom/issues/7319#issuecomment-112874972), I believe that both issues reflected the same underlying problem. I believe I tested that both behaviors you reported were fixed. We can definitely reopen either issue if you find that the bugs persist.
