### ISSUE TITLE
Delete broken

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#7318]
Trying to delete 1 of 4 contiguous spaces is broken. 

Video: http://youtu.be/QwdWfXUlxTQ

**Comment by izuzak** [comment]
There's already a discussion on this -- please add a comment there: https://github.com/atom/atom/issues/6048

**Comment by alexandernst** [comment]
@izuzak The issue you're pointing to is closed. This is an unaddressed genuine bug, I'd say. Either re-open this or #6048

**Comment by izuzak** [comment]
@alexandernst The fact that the existing issue is closed doesn't really matter -- please add a comment there or to #3174. This issue will not be reopened -- the current behavior is intended for now (see https://github.com/atom/atom/issues/3174), and if you'd like to leave some feedback about that -- the best way to do that is to leave a comment in the issue which already has lots of feedback about that.
