### ISSUE TITLE
Atom refuses to paste

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#7319]
Pasting 4 spaces is absolutely broken. Atom is trying to preserve the indent and thus refusing to paste.

Video: http://youtu.be/uVpGAkxB3EY

**Comment by izuzak** [comment]
Please see my comment here: https://github.com/atom/atom/issues/7317#issuecomment-112741748.

Also, can you clearly explain the difference between this issue and that one?

**Comment by batjko** [comment]
There isn't one. I think this should be closed as a duplicate.

**Comment by izuzak** [comment]
@batjko Thanks for taking a look. :bow: That was my gut reaction as well, but would love to hear from @alexandernst just in case. It seems he's been poking at various tabs/spaces problems and it's possible he's trying to report a different issue.

**Comment by alexandernst** [comment]
@izuzak @batjko The other issue is about Atom messing the indent level when pasting. This one is about Atom refusing to paste anything at all. Will write steps to repro in a moment.

**Comment by izuzak** [comment]
@alexandernst It would be helpful if the title and descriptions of your issues reflects problems you are reporting more clearly. For example, the title of these two issues are: "Paste is broken" and "Copy/Paste broken". Could you update the titles so that they are clearer as well? Thanks.

**Comment by alexandernst** [comment]
Steps to repro:

Tthis is Atom .209 on Linux. `Soft tabs`, `Auto-indent` and `Auto-indent on Paste` are on. The `Tab length` is 4.

1. Open Atom (--safe)
2. Paste this:

```
<div>
    test
</div>
```

.3. Switch from Plain text to HTML
4. Select the 4 spaces that are behind `test` and copy them.
5. Place the cursor right before `test` and try to paste the 4 spaces.

**Comment by alexandernst** [comment]
Turning `Auto-indent on Paste` off fixes the problem.

**Comment by batjko** [comment]
So looks like this is also about the indent issue after all.
I agree that this may not have been clear from the beginning though.

**Comment by alexandernst** [comment]
@izuzak Do yoo need any more information? I'm wondering because the tag is still there.

**Comment by maxbrunsfeld** [comment]
Hey @alexandernst. Thanks for reporting this, and providing these detailed facts. I just reproduced the issue, and I'd like to combine this with your other recent issue, #7317, because I believe they have are two symptoms of the same underlying problem: our auto-indent-on-paste functionality is overly-aggressive. If we later find that we need to treat them separately, we can reopen this one. :+1:

**Comment by alexandernst** [comment]
@maxbrunsfeld I moved the description of this problem to the other issue ;)
