### ISSUE TITLE
Uninstalling on Windows "forgets" to remove Explorer context menu item.

### ISSUE THREAD

**Issue by cromoteca** [atom/atom#7326]
I used your official installer, downloaded yesterday. I uninstalled today, rebooted, but the "Open with Atom" context menu item is still there.

Please provide detailed instructions on how to remove it, fix your uninstaller and let me know if there is other stuff left around that must be removed manually.

I find this kind of issue particularly annoying: if all programs would do the same, the Explorer context menu would need three monitors stacked vertically to be displayed.

**Comment by cromoteca** [comment]
Even the start menu icon is left behind :(

**Comment by 50Wliu** [comment]
@paulcbetts

**Comment by paulcbetts** [comment]
@cromoteca Reinstall then uninstall, not sure what happened but the uninstaller definitely removes its files - sounds like something went pear-shaped on your machine.

**Comment by cromoteca** [comment]
Yes it worked today. I don't know what happened last week. I used it for a short time and uninstalled it through the control panel. Unfortunately I can't provide any useful info to replicate the issue, so I close it.

**Comment by jasoncavett** [comment]
If someone else runs across this issue, I recently did.

I had (latest) version of Atom installed (though, I had installed it quite some time ago using an older version of the installer). I then received the upgrade to go to Windows 10. After it upgrade, I uninstalled Atom and the context menus remained. Had to remove them manually from the registry to clear them out.
