### ISSUE TITLE
Show Install Error message in Install Tab

### ISSUE THREAD

**Issue by S-ed** [atom/atom#7328]
I've tried to install ```seti-monokai``` theme from install tab by clicking ```install``` button and was confused by Atom's behavior (nothing happened).
After 5 clicks I've decided that something wrong and opened Themes tab, there were 5 messages
```
Installing "seti-monokai@0.3.1" failed. Show output...
```
Would be nice to have those messages in install tab.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/settings-view?

**Comment by S-ed** [comment]
Oh. ```Install``` is in Settings-view. But errors pops up in ```themes```(for themes) not in ```install```. 
You cold try it, ```seti-monokai```'s repo unaccessible so it'll thow an error.
![screenshot_1434626822](https://cloud.githubusercontent.com/assets/3008353/8230151/1bea7a3a-15c6-11e5-869f-786da041ed9b.png)

**Comment by mnquintana** [comment]
It's all part of settings-view, so it would be great if you could move this issue there - atom/atom is meant for issues with Atom core only.

**Comment by S-ed** [comment]
oh, sorry =)

**Comment by S-ed** [comment]
Seems like there is same issue already.
