### ISSUE TITLE
Fatal error, see debug.log

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#7330]
I've installed 0.10.2, but on an existing wallet.dat. It started loading the transaction chain, but at 49 weeks behind, I got an error 'fatal error, see debog.log for details'. The last line of debug.log was:

    *** System error while flushing: CDB : Error -30974, can't open database

If I close and re-open bitcoin-qt, it works for a while before throwing this error again.

**Comment by batjko** [comment]
My friend... are you sure you're on the right repository here?

**Comment by maxbrunsfeld** [comment]
@stijnsanders I'm going to close this for now, since it doesn't seem like you're talking about Atom. Let me know if this is actually Atom-related.

**Comment by stijnsanders** [comment]
oh yes, completely the wrong repo (things so great you have to name them twice (in the URL): atom, bitcoin..)
