### ISSUE TITLE
The text cursor doesn't display when it's on the 80 column line.

### ISSUE THREAD

**Issue by AustP** [atom/atom#7331]
![recorded](https://cloud.githubusercontent.com/assets/2007045/8235586/05791f84-15a0-11e5-8a27-4601a6af6af5.gif)

Notice after typing `Loo` the text cursor goes away. It comes back again when I type `k`.  (v 0.210.0)

**Comment by maxbrunsfeld** [comment]
@AustP What theme are you using? I can't reproduce this with `One Dark`, `One Light`, `Atom Dark` or `Atom Light`.

**Comment by AustP** [comment]
Sure enough it was a theme issue. I was using a custom theme created from `Package Generator: Generate Syntax Theme` from ~ v0.150.0.

**Comment by gunn** [comment]
I get this with the Base16 Tomorrow Dark "core theme":
https://github.com/atom/base16-tomorrow-dark-theme
