### ISSUE TITLE
Add Resize - Panel Keyboard Commands

### ISSUE THREAD

**Issue by chrishough** [atom/atom#7332]
References: https://github.com/santip/resize-panes/issues/21#issuecomment-113251749 

Before the resize-pane project was consumed by core it had shortcuts for resizing the panes. I know many people here use the mouse to resize, but this was a **key** feature for those of us who love the speed of the keyboard. 

Can we add this back somehow? 

@mnquintana

**Comment by izuzak** [comment]
> Can we add this back somehow?

@chrishough I like that idea, but the core Atom team probably won't have time to tackle this in the near future. If someone from the community wants to submit a pull request to add this ability (similar to how @liuxiong332 added the resizing ability in https://github.com/atom/atom/pull/5902), the core team would be happy to help by reviewing that PR. Does that sound good?

**Comment by chrishough** [comment]
While I would not have the skill set to pull that off just yet, I would toss a git-tip for that feature if someone would be game to build it in. @liuxiong332

**Comment by liuxiong332** [comment]
Ok, I have added the resize commands #7354 and expect to be merged.

**Comment by chrishough** [comment]
@liuxiong332 damn, that was fast.  Thank you so much, I truly appreciate it.  This feature from the old plugin for us keyboard junkies was crucial.  It was driving me crazy not having it.

**Comment by liuxiong332** [comment]
reply so fast!

**Comment by chrishough** [comment]
lol, always online! basically a robot :fireworks:
