### ISSUE TITLE
Don't display warnings for disabled plugins

### ISSUE THREAD

**Issue by DavidAwad** [atom/atom#7333]
Atom will consistently stack errors about missing path variables on top of each other. 

If it's not working, display the error on launch, don't stack it on top of itself continuously.

**Comment by izuzak** [comment]
@DavidAwad Can you share a bit more details about what's going on, a screenshot, and steps to reproduce? I'm not sure I understand which behavior exactly you're referring to with disabled packages. Thanks!

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/7333#issuecomment-113486050. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
