### ISSUE TITLE
Autocomplete not working with multicursor

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#7334]
Autocomplete is not working when multicursor in used.

Steps to reproduce:

1. Open a new empty file
2. Change type to JavaScript
3. Hit enter a few times to create a few new lines
4. Select a few lines using multicursor
5. Type `(`

Expected result:

`()` should appear on each line.

Actual result:

`(` appears on each line.

**Comment by 50Wliu** [comment]
Could you please move this to the [atom/bracket-matcher](https://github.com/atom/bracket-matcher) repository please?

**Comment by alexandernst** [comment]
Sure
