### ISSUE TITLE
Could not resolve 'X' to a package 

### ISSUE THREAD

**Issue by DavidAwad** [atom/atom#7335]
It seems that there was package lag and I his the disable button too many times for a particular package. 

Anyway It looks like I cant enable, install, or uninstall packages anymore. 

Here's the console output. 

``` JS
Linter-Pylint: package loaded, ready to get initialized by AtomLinter.
/Users/davidawad/Desktop/Atom.app/Contents/Resources/app.asar/src/package-manager.js:377 Could not resolve 'highlight-selected' to a package path
index.js:56 Window load time: 780ms
index.js:14 Unhandled promise rejection Promise__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: Array[1] with error: Array[1]index.js:14 (anonymous function)
/Users/davidawad/Desktop/Atom.app/Contents/Resources/app.asar/src/package-manager.js:377 Could not resolve 'linter-shellcheck' to a package path
/Users/davidawad/Desktop/Atom.app/Contents/Resources/app.asar/src/package-manager.js:377 Could not resolve 'file-type-icons' to a package path
```

**Comment by maxbrunsfeld** [comment]
@DavidAwad can you share the contents of your `config.cson` and the output of `apm list --installed`?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/7335#issuecomment-119259656. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
