### ISSUE TITLE
Wrong Folding Operation

### ISSUE THREAD

**Issue by as-cii** [atom/atom#7337]
Originally reported by @maxbrunsfeld:

> I'm seeing another weird gutter behavior, and I'm wondering if you think it's the same bug. Occasionally the fold buttons in the gutter cause incorrect fold operations:
> 
> ![fold-bug](https://cloud.githubusercontent.com/assets/326587/8244236/4c4d7c6a-15d3-11e5-8876-10ecb7d95a8e.gif)
> 
> Unfolding works as expected, but when I click the fold icon next to line 9 to create a fold, instead of creating a fold at line 9, it scrolls the editor slightly, and then creates a fold at line 6.
> 
> Creating folds from the keyboard (via editor:fold-current-row) works correctly, so the problem seems to be related to the gutter.
> 
> This only happens to me intermittently. Is there any code that I can run when I get into this state to verify whether or not it's the same bug?

I am able to reproduce this similarly to the bug we had in #7306:

* Write a few paragraphs of text (ensure it enables vertical scrolling).
* Scroll to the very bottom.
* Split the pane (I split it right, but I think left or anything else will do).
* Ensure that splitting the pane has caused the editor on the left to scroll up.
* Scroll the left panel again to the very bottom.
* Close the right panel.
* Fold any line.
* The wrong line was folded. :boom:

**Comment by as-cii** [comment]
My suspect is that this is being caused by multiple event handlers attached to the same DOM node (https://github.com/atom/atom/blob/as-odd-tiles/src/line-number-gutter-component.coffee#L18-L19): since such node gets recycled amongst instances of `LineNumberGutter`, the same events get reattached over and over, causing one or more of them to apply a fold operation for the same `TextEditor`.

I am going to verify this and submit a fix soon, although we should really considerate the possibility of keeping the same `TextEditorComponent` alive when the related `TextEditorElement` is detached.

/cc: @jssln @nathansobo

**Comment by maxbrunsfeld** [comment]
> * Write a few paragraphs of text (ensure it enables vertical scrolling).
* Scroll to the very bottom.
* Split the pane (I split it right, but I think left or anything else will do).
* Ensure that splitting the pane has caused the editor on the left to scroll up.
* Scroll the left panel again to the very bottom.
* Close the right panel.
* Fold any line.
* The wrong line was folded. :boom:

:+1: I just reproduced the bug on master with these steps. After building this branch, I cannot reproduce the bug. :ship:
