### ISSUE TITLE
Keybindings: key chord support

### ISSUE THREAD

**Issue by dvorobiov** [atom/atom#7343]
In Emacs and Vim you can have proper key chord support http://www.emacswiki.org/emacs/KeyChord
I am using vim mode in atom and it does not work properly in the following scenario:

I am in insert mode and assign the combination 'f d' to switch to command mode. The switching works, but now to print an 'f' symbol I have to press the key twice as on the first pressing atom does nothing expecting the command. 

Can it be implemented via a scheduler? Atom prints 'f' on the key pressing, but it within a very short time period 'd' follows it removes 'f' and executes the command 'f d'?

Thank you!

**Comment by izuzak** [comment]
Yep, that would be neat. There's already an issue to track that request, so make sure you follow along there: https://github.com/atom/atom-keymap/issues/17. Closing this in favor of that issue. :v:
