### ISSUE TITLE
Windows uninstall doesn't remove .atom folder

### ISSUE THREAD

**Issue by tomByrer** [atom/atom#7346]
Uninstalled Atom via Win7 `Programs and Features`.  It failed to remove `C:\Users\<user>\.atom`, which caused [old packages](https://github.com/atom/atom/issues/7270) to stay installed without warning.

Update: Manually deleted `.atom` folder after uninstalling.  Ran `AtomSetup.exe` for v0.210.0.  Installed package inside Atom.  Uninstalled Atom, `.atom` folder remained, along with the package I installed.

**Comment by 50Wliu** [comment]
@paulcbetts looks like we're getting more than a few of these reports.

**Comment by paulcbetts** [comment]
This is by-design not an uninstaller issue, settings don't get removed on uninstall.

**Comment by ollpu** [comment]
Perhaps there should be an option to also remove the configuration on uninstall?

**Comment by tomByrer** [comment]
> Perhaps there should be an option to also remove the configuration on uninstall?

I agree; & should be shown by the uninstaller & on by default.  Most people expect to uninstall a program when they uninstall, not remove half the files & have the other half abandoned on their HD, unknowingly eating up space & adding confusion.  

Current behavior goes beyond leaving 'settings' (an init.ini); your leaving in entire GH repos (packages) in a system folder.  `C:\Users\<user>\.atom` can be 40Mb to several Gb.

**Comment by paulcbetts** [comment]
Squirrel uninstallers have no UI, so this isn't possible. It _is_ possible for Atom to delete `~/.atom` on exit,  but that'd have to be something the Atom core team would decide to do / not do. This folder isn't deleted on Mac or Linux on uninstall, so my personal vote is to leave this folder, as it represents user settings / content

**Comment by tomByrer** [comment]
> Squirrel uninstallers have no UI

There are other more flexable & mature installers around.

I can see leaving user settings when the client was flaky & uninstalls/reinstalls were frequent.
But now Atom itself & the updater seems more stable, so I'm assuming people will update without uninstalling.
Does it seem reasonable that when people want to uninstall Atom now, they actually want to uninstall?

**Comment by mark-hahn** [comment]
You aren't suggesting it defaulting to removing the folder, are you?  That
would be dangerous.  If it can't have a setting then it has to leave the
folder.  All the personal setup is in there.

**Comment by tomByrer** [comment]
Dangerous to whom please @mark-hahn ?  Those who don't know what uninstall means?  I would think Atom users are a bit above a run-of-the-mill computer user.  It is also dangerous to leave files without warning, esp when they could contain personal information.

Though I'd prefer a warning either way of course.

**Comment by 50Wliu** [comment]
My thoughts on this:
I'd expect an uninstall to remove everything, unless something says otherwise (such as the uninstaller UI prompting you what to uninstall).  This also prevents outdated/broken packages from causing a problem if you decide to reinstall later.

**Comment by joshery420** [comment]
@50Wliu Second this opinion. Leaving user settings/configuration and such when uninstalling is fine if it's optional during uninstall, but if it's all or nothing, I don't think uninstalling should leave extra data around. The only reason I can see leaving the .atom file by default is if if you NEED to use that uninstall method during the built-in update process.

**Comment by mark-hahn** [comment]
> The only reason I can see leaving the .atom file by default is if if you
NEED to use that uninstall method during the built-in update process.

I can think of several other reasons.  You might delete Atom and then move
the folder to another computer.  You might uninstall and later change your
mind.  You might forget to copy your custom files before uninstalling.
Removing custom settings files without warning is definitely a no-no.

**Comment by joshery420** [comment]
@mark-hahn Fair enough, I guess I just have a personal aversion to so many programs I don't use anymore leaving config folders around everywhere. My personal preference is 100% a checkbox or something during uninstall so the user can make the decision themselves.

**Comment by Stanzilla** [comment]
It should be a setting. Probably goes inline with https://github.com/atom/atom/issues/7445

**Comment by Ivoz** [comment]
I'd highly like there to be an option / dialogue to ask whether you'd like to keep user data or not. This is extremely common among Windows applications at the very least.

I just tried uninstalling atom to get a "clean state" fresh install. Very surprised when I re-installed it again, and everything goes back to the way it was, all packages still there... confusing.

**Comment by paulcbetts** [comment]
Squirrel installers / uninstallers will never have dialogs

**Comment by Ivoz** [comment]
...*never?* Isn't that a bit absolute and/or inflexible, as well as unintuitive?

**Comment by tomByrer** [comment]
> I just tried uninstalling atom to get a "clean state" fresh install. Very surprised when I re-installed it again, and everything goes back to the way it was, all packages still there... confusing. 

Yes, exactly why I opened this bug.  :)  Not only to save space, but also to debug with a fresh install.

**Comment by paulcbetts** [comment]
>  ...never? Isn't that a bit absolute and inflexible, as well as unintuitive?

Nope! When you ask to uninstall an app, literally the only thing we should do is uninstall it. 

And since Squirrel apps intentionally install and uninstall **so fast** that you don't even mind that you accidentally uninstalled, it would then extend that we probably _shouldn't_ remove `~/.atom`, since recreating it is fairly annoying and expensive in terms of user time.

**Comment by tomByrer** [comment]
> When you ask to uninstall an app, literally the only thing we should do is uninstall it.

So what you're saying is the `.atom` folder has *nothing* to do with the Atom editor?  What else is it used for please?  Is it left over for my harddrive gnomes to throw a party in?

Leaving the folder without warning is annoying to users also.

**Comment by Ivoz** [comment]
> it would then extend that we probably shouldn't remove ~/.atom, since recreating it is fairly annoying and expensive in terms of user time.

I couldn't think of something less annoying than spending an extra second at install time, especially when I've spent over a minute waiting for the installer to download. And install time only happens once. Atom still takes [3-4](http://i.imgur.com/roqFfw1.png) seconds for me to start up.

**Comment by PBranco86** [comment]
Hi, you can remove folder (.atom) in documents folder if you rename almost every folder. First of all you must delete all the folders you can, go at the end of "tree", then you start to rename the folders to 1, and you can delete all the stuff in there. It works for me, a little work, but is effective.

Hope it helps someone, and i'm sorry for my English.

**Comment by julianxhokaxhiu** [comment]
Surprising how your method worked @PBranco86! Thanks for the suggestion. I was just clearing out `.atom` folder today after I installed v1.7.0 and I was wondering what was wrong with my Windows installation.

@Atom guys: please, take a note of this issue, it's not nice to create so deep innested folders. Consider flattening the `node_modules` folder please...

**Comment by 50Wliu** [comment]
> Consider flattening the node_modules folder please...

This won't be happening until Atom upgrades to npm@3, which will take a while because of the number of breaking changes that will need to be addressed.

**Comment by Qrokqt** [comment]
This is ridiculous. The standard that I've seen uninstallers do is to give the option to delete config files, or leave them if you're planning on reinstalling. Definitely NOT just silently leaving garbage all over my HD.

**Comment by joshburgess** [comment]
This is pretty annoying. I had old Nuclide packages I was trying to remove that absolutely would not uninstall through the Settings view in the editor. Ended up uninstalling atom from the system hoping I could start over with a fresh install only to continue to have the same issue upon reinstall. Uninstallers typically prompt the user to make a decision about removing or keeping their local settings/packages/etc. when they go to uninstall. Would be nice to have that option.

**Comment by jerone** [comment]
> It is possible for Atom to delete ~/.atom on exit

@paulcbetts, does that mean there's an event from Squirrel where Atom can hook into, just before Squirrel runs it's uninstaller?

**Comment by paulcbetts** [comment]
@jerone Correct

**Comment by Ivoz** [comment]
Still relevant

**Comment by julianxhokaxhiu** [comment]
If I am not wrong, this was relevant when `apm` was using NPM 2.x, but since now it uses NPM 3.x ( which has the tree flatten ) on Windows it should be safe to delete this folder, whichever way it is chosen.

Right?

**Comment by carpben** [comment]
I recently uninstalled and reinstalled Atom (to solve some bugs). I was surprised to see that the packages I had installed persisted. Obviously as a user I wanted to start with a clean installation. Platform: Windows10. Pretty sure I had the latest version of Atom.

**Comment by julianxhokaxhiu** [comment]
Would be nice if the uninstaller prompts with a checkbox to delete also user data. This would make everyone happy.

**Comment by cutmeat** [comment]
I also agree though that the expected behaviour for me when I use an uninstaller on Windows is, that it either asks what I want to keep or silently get rid of the whole application including settings.
The most common scenarios for uninstalling in general for me are:
A. I'm not using this software anymore, and won't in the the future. Files left over by it have no value to me.
B. Something isn't working, and I need to start with a clean slate. In this case, files left over by a previous installation are actively hindering me from achieving what I need to do.

The only scenario where I'd want to keep my settings when uninstalling, is when updating to a different version of the software, and it would be necessary to uninstall for that.

Either way, deleting everything including registry entires should be an OPTION. I don't see how the argument that "it installs so fast that you won't mind whether you uninstalled by accident" is connected to this. Clicking a checkbox on uninstall is a time investment of 1.5 seconds. Googling why I find my old settings after reinstallation, finding out that that is intended behaviour, then finding out that I have to manually delete some files and registry entires myself and what they are and then doing it takes a LOT longer than that, and I'm left with the feeling that I probably missed something.
That is a task that could've been automated easily.
