### ISSUE TITLE
'Home' and 'End' keys do not function as expected on OSX

### ISSUE THREAD

**Issue by dhowe** [atom/atom#7349]
Expected behavior in a text-editor on OSX is for the 'home' key and 'end' key to move the cursor to the first and last line of the current file, rather than having no function as is current behavior. I am guessing this is the [relevant file](https://github.com/atom/atom/blob/master/keymaps/darwin.cson)...

Version 0.204.0 (0.204.0), OSX 10.10

**Comment by lee-dohm** [comment]
You can redefine them to act the way you are suggesting by adding the following to your `keymap.cson`:

```coffee
'atom-text-editor':
  'home': 'core:move-to-top'
  'end': 'core:move-to-bottom'
```

If you're suggesting that the way you're suggesting should be the default behavior, I would disagree. TextMate 2, TextEdit and Pages scroll the viewport to the top and bottom of the document *without* moving the cursor, even if the cursor would end up outside the viewport. Behaving as other native OS X text editors would be the way that I would expect things to act by default.

Currently, the keys execute the following commands:

* <kbd>Home</kbd> &mdash; `editor:move-to-first-character-of-line`
* <kbd>End</kbd> &mdash; `editor:move-to-end-of-screen-line`

You can find the definitions for them here: https://github.com/atom/atom/blob/master/keymaps/base.cson#L1-L4.

**Comment by dhowe** [comment]
That works great -- thanks for the info. I'd thought this was default behavior on OS X, but apparently it varies...

**Comment by lee-dohm** [comment]
You're welcome, @dhowe. I'm glad I could help :grinning: Can this be closed?

**Comment by dhowe** [comment]
ok by me :)

**Comment by lee-dohm** [comment]
Awesome, thanks!

**Comment by devios1337** [comment]
This should not be closed. Expected behavior is expected behavior.

**Comment by jcollum** [comment]
I agree with @devios1 . Editors should always conform to the conventions of the system they are installed on. Finding out what those conventions **are** is part of the dev process, not something for users to do after the fact. 

Tons of programs fail to do this though.

**Comment by chrisjshull** [comment]
Can this please be reopened? Consistency with the OS is a key factor in following the principle of least astonishment.
