### ISSUE TITLE
Code snippets inside tag attributes

### ISSUE THREAD

**Issue by jgibba** [atom/atom#7356]
It would be awesome to allow code snippet hints to work inside of <tag> attributes.

Currently mytag src = "my_code_snippet_hint_here" will not render code snippet autocomplete options inside tag attribute quotes.

This editor is amazing! Thanks!

Jon

**Comment by k2b6s9j** [comment]
You would have better luck reporting this to [atom/autocomplete-plus](https://github.com/atom/autocomplete-plus).

**Comment by izuzak** [comment]
Closing in favor of https://github.com/atom/autocomplete-plus/issues/509.
