### ISSUE TITLE
Searching for installed package returns nothing

### ISSUE THREAD

**Issue by v3ss0n** [atom/atom#7357]
version : https://github.com/atom/atom/commit/852456fafef5ef7b6502a16f95219ed0a094809d
Steps: 
- Install new package
- Click packages and then search for it
- Nothing returns.

Restarting atom makes it work again but after a few search on installed packages happens again.

**Comment by izuzak** [comment]
@v3ss0n Please re-open this on the https://github.com/atom/settings-view issue tracker, if none of the already open issues don't match your report. There's a few that seems very similar.
