### ISSUE TITLE
npm license has expired : coffeestack

### ISSUE THREAD

**Issue by lexicalunit** [atom/atom#7358]
1. Download https://github.com/atom/atom/releases/download/v0.210.0/atom-windows.zip and extract it.
2. `SET PATH=C:\path\to\extracted\Atom;C:\path\to\extracted\Atom\resources\app\apm\bin;%PATH%`
3. `cd C:\path\to\any\atom\package\it\does\not\matter`
4. Run `npm install`

Results:

```
Installing modules failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\foolbox\\poo\\Atom\\resources\\app\\apm\\bin\\\\node.e
xe" "C:\\Users\\foolbox\\poo\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\
\npm-cli.js" "--globalconfig" "C:\\Users\\foolbox\\.atom\\.apm\\.apmrc" "--userc
onfig" "C:\\Users\\foolbox\\.atom\\.apmrc" "install" "--target=0.22.0" "--arch=i
a32"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code E402

npm ERR! npm license has expired : coffeestack
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

I think maybe step 3, above, might only apply to packages which have dependencies to install but I haven't checked.

**Comment by taiyaei** [comment]
Looks like this is an npm issue? https://github.com/npm/npm/issues/8631

Getting the same with even updating bower for chmodr, so looks like it's not atom-specific.

**Comment by lee-dohm** [comment]
Why are you running `npm install` in an Atom package? If you want to install the package dependencies for an Atom package, you should run `apm install`.

**Comment by thedaniel** [comment]
npm had some kind of issue with their servers / accidentally crossed the streams with their enterprise product apparently, but they have closed the issue on their end so I'm going to close this out. Let us know if this crops up again. https://github.com/npm/npm/issues/8631#issuecomment-113970885
