### ISSUE TITLE
On first open of Atom cannot install any packages or updates.

### ISSUE THREAD

**Issue by samjohn** [atom/atom#7359]
On first open, Atom was unable to download any packages or updates. 

I got this error: /Users/samanthajohn/downloads/Atom.app/Contents/Resources/app/apm/bin/apm ENOENT

After some hair-pulling, I closed and reopened Atom after which it worked fine. It was quite a frustrating first experience, plus I imagine this shouldn't be too hard to fix.

**Comment by samjohn** [comment]
Update: I tried this on another computer and did not get the error. I'm not totally sure what went wrong but it's probably worth trying to reproduce to see if it might be an intermittent problem.

**Comment by lee-dohm** [comment]
When you tried on the other computer, had you placed the `Atom.app` in `/Applications`?

**Comment by samjohn** [comment]
No, it was still in downloads.
