### ISSUE TITLE
License issue with jschardet dependency

### ISSUE THREAD

**Issue by thomasjo** [atom/atom#7366]
The newest version of [jschardet](https://github.com/aadsm/jschardet) (v1.2.0) is using a "bad" license, which is being flagged as non-permissive and as such failing our `check-licenses` CI step/task.

The way I see it, we have three options;
 1. Get this fixed upstream.
 2. Fix the version of jschardet to v1.1.1.
 3. Replace the dependency.

/cc @atom/feedback

**Comment by mnquintana** [comment]
It was added in this commit: https://github.com/aadsm/jschardet/commit/eaded690f7ff68454a2fa78b13a3f0cc99484580

Apparently it didn't have a license at all before. :grimacing:

**Comment by mnquintana** [comment]
I think we can safely pin the version to 1.1.1 right now as a quick fix, because [all that was changed in this recent version was capitalizing `utf-8`](https://github.com/aadsm/jschardet/pull/15). But I think we should try to fix this upstream.

**Comment by thomasjo** [comment]
It has had a [license of a while](https://github.com/aadsm/jschardet/commit/8497eab797a5b7f7e74179cebdd44ec614a255b8), it was just missing from `package.json`. There's also a [license override](https://github.com/atom/atom/blob/414b82f05ec60562563b9b94fa9cea42ac9a53d9/build/tasks/license-overrides.coffee#L68-L81) in place for v1.1.1.

Problem seems to be partially in how licenses are being handled in [legal-eagle](https://github.com/atom/legal-eagle). It doesn't properly support SPDX license spec.

**Comment by thomasjo** [comment]
With that being said, the license format used in jschardet has been deprecated:
https://spdx.org/licenses/LGPL-2.1+

**Comment by kevinsawicki** [comment]
Yeah, this looks like a legal-eagle issue, testing out a fix now...

**Comment by kevinsawicki** [comment]
legal-eagle wasn't properly detecting `LGPL` when referenced from the `package.json` `license` field, should be fixed now on master, thanks for reporting this :lock_with_ink_pen:
