### ISSUE TITLE
can't fold code in split screen mode

### ISSUE THREAD

**Issue by hawsome** [atom/atom#7367]
This happens every so often. Often enough to drive me crazy!

![Image of Bug](http://i.imgur.com/tdCA9tB.gif?1)

**Comment by as-cii** [comment]
Hey @hawsome, I think that what you’re experiencing is similar to #7337. I am sorry this is causing you headaches: a fix for that bug has already landed on master and it will ship with `0.211.0` (which hasn’t been released yet). :rocket: 

I am pretty confident you won’t notice that pesky bug anymore as soon as the new version will be released, but in the meantime you may want to build Atom from master and give it a shot (please, have a look at https://github.com/atom/atom/tree/master/docs/build-instructions to know how the building process works on your platform).

By the way, the new version shouldn’t take long to be released and you may want to just wait for it. :smile_cat: 

Thanks for your feedback! :bow:

**Comment by hawsome** [comment]
Hi @as-cii, thank you for your reply!

I know I experienced the bug you referenced, but this one seems like a slightly differentiated one. It doesn't fold it at all and jumps up.

Hopefully those are the same issues though, crossing my fingers!

Thank you guys for being so quick on bug fixes and updates! I literally see one almost every day. Props to everyone!

**Comment by yishn** [comment]
I think it also jumps if you click on the gutter to select the line. This drives me crazy as well... :smile:

**Comment by maxbrunsfeld** [comment]
@hawsome 0.211 was just released, containing the fix that @as-cii mentioned above. Can you check if this bug is still happening?

**Comment by hawsome** [comment]
I wish I could!

![error](http://i.imgur.com/9Y426JK.png)

**Comment by hawsome** [comment]
Looking good! Thank you!!!!! :smile:
