### ISSUE TITLE
Scrolling through Autocomplete breaks App's UI

### ISSUE THREAD

**Issue by silvestreh** [atom/atom#7372]
Kind of a strange bug. At first I thought my theme was at fault, but then I switched to One Dark UI and the bug was still there.

The reproduction steps are pretty easy. Open the autocomplete menu, then scroll it using the arrow keys. The entire UI will "move" up, making the top parts of the app (tabs, for example) non accesible.

Here, I made a GIF to explain myself better.

![atombug](https://cloud.githubusercontent.com/assets/1133339/8290257/2979bf0a-18f8-11e5-8ef9-0799115467bd.gif)

I tried searching through the issues but couldn't find a related issue (maybe my searching keywords sucked)

###### EDIT with actual information

Atom is version `0.211.0`
OS is `Mac OS X 10.10.3`

The expected behavior is for the rest of the UI not to move while scrolling an autocomplete list. The console on Dev tools doesn't print any errors.

**Comment by izuzak** [comment]
This issue was moved to atom/autocomplete-plus#511
