### ISSUE TITLE
I can't load my package to find deprecation.

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#7375]
I am getting a deprecation message on my package `view-tail-large-files` and Atom won't load my package, even in dev mode.  I see no deprecation problem.  Deprecation cop finds nothing because it won't load.

How do I solve this catch-22?

P.S.  I cleaned out all my deprecations before June so somebody slipped a new one in, which isn't quite fair.

**Comment by kevinsawicki** [comment]
Does it load if you run `atom --dev --include-deprecated-apis`?

**Comment by mark-hahn** [comment]
Thanks.  I didn't know about that.

**Comment by mark-hahn** [comment]
OK, I've loaded my package and exercised it but I'm not getting anything in the deprecation cop.  How does Atom determine there is a deprecation?  Is there any way for Atom to report what deprecation is being detected?

**Comment by kevinsawicki** [comment]
>  Is there any way for Atom to report what deprecation is being detected?

From the Console tab of the dev tools you could run `require('grim').getDeprecations()` to see the raw deprecations

**Comment by mark-hahn** [comment]
I could have sworn I posted this already, but here it is again ...

I found out that the deprecation was being reported as coming from Atom Core.  So I can see it now.  Is there already an issue to improve the detection of what package is at fault?

BTW, FWIW, Atom is misusing the word "deprecation".  It specifically means "to express disapproval of".  Atom has gone way beyond that and banned the usages.  It should just be "removed" or something like that.

**Comment by benogle** [comment]
You can search for your package in this: https://gist3.github.com/benogle/6d09e295c84b717ef9b4

Which will tell you the deprecations it's emitting. This list is compiled from metrics. So they are deprecations people actually hit.

**Comment by mark-hahn** [comment]
https://gist3.github.com/benogle/6d09e295c84b717ef9b4 gave me a 404.

This issue doesn't matter for me anymore because I've decided `view-tail-large-files` isn't needed since Atom supports larger files.  

I will publish a new package that offers tailing by itself.

**Comment by benogle** [comment]
Right, sorry, it's a dumb internal redirect. I've changed it to gist
