### ISSUE TITLE
Building Atom on 32 bit Ubuntu 15.04: missing dependencies

### ISSUE THREAD

**Issue by fusion809** [atom/atom#7378]
Hi, while the deb packages provided by the webup8team ppa are great sometimes they lag a wee bit behind so I'm attempting to figure out how to build Atom on Ubuntu from the GitHub source. I followed the [build instructions for Linux](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md) but as with my [previous attempt](https://github.com/atom/atom/issues/6774) issues where encountered at the `script/build` line. I looked at the [package.json](https://github.com/atom/atom/blob/master/package.json) file to look for dependencies I might be missing, but many of these packages are either not available on Ubuntu or are differently named in the Ubuntu repositories. 

I was wondering if anyone here might know what they are all called on Ubuntu as I suspect that not having all the build dependencies may be why I can't seem to build Atom on Ubuntu from source.

**Comment by 50Wliu** [comment]
What dependencies are you missing?  Is this the same issue as the one you linked (#6774)?
The dependencies in `package.json` are unrelated to Ubuntu dependencies.  You can find those [here](https://github.com/atom/atom/blob/master/resources/linux/debian/control.in).

**Comment by fusion809** [comment]
OK, well I have all those dependencies but the build still fails. What do you need for me to tell you in order for you or others to help me? Because I assume that more-information-needed tag is meant to get me to give you some info you want.

**Comment by mnquintana** [comment]
Pasting the exact output you get when the build fails would be helpful.

**Comment by fusion809** [comment]
I get no output (i.e., it skips straight to the next bash input line) at the command line at all, that's why I don't mention it.

**Comment by fusion809** [comment]
Both lines `script/build` and `sudo script/grunt install` return no output. But if I then run `atom` from the bash command line I get `bash: /usr/bin/atom: No such file or directory`.

**Comment by kubetz** [comment]
I woud suggest these experiments:
* Try starting `node` manually to see if REPL starts.
* Run some simple script (e.g. [hello console](http://howtonode.org/hello-node))
* Try the same script, but make it executable and put `#!/usr/bin/env node` at the top.
* Try running script/build using `node script/build`.

**Comment by fusion809** [comment]
By starting node manually do you mean running `node` from terminal? If so I did and it generates no output, just goes to the next bash input line.

**Comment by fusion809** [comment]
Running `nodejs` takes me into some CLI for nodejs.

**Comment by fusion809** [comment]
Running:
`console.log("Hello World");`
in this nodejs CLI gives:
`Hello World
undefined`

**Comment by kubetz** [comment]
The problem is that `node` on your system is not node.js and build scripts are trying to use it to execute javascript files. 

There are several ways how to solve this - have a look [here](http://askubuntu.com/questions/235655/node-js-conflicts-sbin-node-vs-usr-bin-node/320271#320271).

I personally installed node.js on my Ubuntu 15.04 machine [this way](http://askubuntu.com/a/635469/30410) and had no issues.

**Comment by fusion809** [comment]
I did this:
`sudo apt-get install curl
curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
sudo apt-get install nodejs`
but running `script/build` gives this output: 
`Node: v0.12.4
npm: v2.10.1
Installing build modules...
Installing apm...
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo EAI_AGAIN
gyp ERR! stack     at Object.exports._errnoException (util.js:746:11)
gyp ERR! stack     at errnoException (dns.js:49:15)
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
gyp ERR! System Linux 3.19.0-21-generic
gyp ERR! command "node" "/home/fusion809/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fusion809/atom/apm/node_modules/atom-package-manager/node_modules/keytar
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
npm ERR! Linux 3.19.0-21-generic
npm ERR! argv "node" "/home/fusion809/atom/build/node_modules/.bin/npm" "--userconfig=/home/fusion809/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
npm ERR! node v0.12.4
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! keytar@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fusion809/atom/apm/npm-debug.log`

`npm-debug.log` is [here](https://drive.google.com/file/d/0B1_sXH68hMWBOWVXamthOVlOeGs/view?usp=sharing)

**Comment by fusion809** [comment]
If relevant I gitted atom into my home directory, `/home/fusion809`.

**Comment by kubetz** [comment]
To build keytar you need to have g++ and gnome-keyring installed:

`sudo apt-get install g++ libgnome-keyring-dev`

Also make sure you have python2.

**Comment by mnquintana** [comment]
@fusion809 It seems like you didn't actually follow the [build instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#ubuntu--debian) – rather than presuming you have all of the dependencies, you should actually run the install command the build instructions prescribe and follow the instructions for installing Node.js they link to. We can't really help you unless you follow the build instructions first.

**Comment by fusion809** [comment]
@mnquintana This Ubuntu machine of mine has been wiped and reinstalled over and over, I had run the sudo command for installing the dependencies before the last reinstall, so I had unintentionally assumed it was already installed. I had experienced the same error I started this discussion with (where `script/build` produced no output) before when I had installed the dependencies before attempting the build, so the major problem has been node which kubetz has figured out for me. So I suggest that the developers of Atom add the line:

    sudo apt-get install curl
    curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
    sudo apt-get install nodejs

to the building of dependencies section of [linux.md](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md). Plus a minor point, as it doesn't seem to stop me from successfully building atom I keep getting:

    child_process: customFds option is deprecated, use stdio instead.

output at the `Installing apm...` stage. I'm guessing there's a line of code in the Atom source code where `customFds` is being used when `stdio` should be used instead. 

Installation successfully complete, thanks a million kubetz.

**Comment by kubetz** [comment]
Glad to read that you were able to build atom, great job! :+1: 

That `child_process ...` messages you are getting are popping because you are using node.js v0.12 where `customFds` is deprecated. Don't worry about it.

**Comment by fusion809** [comment]
Oh one more thing, kubetz, how do I update this source installation? As it's from git I'd assume that something like running `git submodule init && git submodule update` from the atom directory on my PC (i.e. ~/atom) where I ran the `script/build` command and such, would update the directory and then I'd just re-run `script/build` and `sudo script/grunt install` from there?

**Comment by kubetz** [comment]
If you want to get up-to-date sources of atom and you cloned directly from `https://github.com/atom/atom` use `git pull` and then `script/build`.

If you forked the repository and cloned your fork read [this](https://help.github.com/articles/syncing-a-fork/).

**Comment by fusion809** [comment]
@kubetz I ran `git pull` from the directory (which I did in fact clone from the master repo, i.e., https://github.com/atom/atom) to receive the error: `Cannot pull with rebase: You have unstaged changes. Please commit or stash them.`

**Comment by kubetz** [comment]
If you google the messages git throws at you there is a very high chance you will something uself :+1: .

http://stackoverflow.com/a/23517643/1011582

**Comment by razvanc87** [comment]
Hi, I'm having a slightly different problem. I want to build atom on a linux machine (KDE based) where I don't have root access so it's impossible for me to easily get this `libgnome-keyring-dev` package from a package manager. What are my options here then?... thanks

**Comment by mnquintana** [comment]
@razvanc87 Hmmm I'm not really sure what you can do there. You need to have the dependencies installed somehow, and installing them would require root access. Sorry :confused:
