### ISSUE TITLE
When I expand a directory with a lot of files in it (200+) Atom takes a while to display the files.

### ISSUE THREAD

**Issue by john-sparwasser** [atom/atom#7386]
Looking at the profiler it looks like the file names may be hitting an edge case in the naturalSort function. The directory that is giving me problems is my database migrations folder, and all of the filenames start with a snakecase date, a unique identifier, then the name of the migration, eg: 2015_06_23_123456_create_users_table.php

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/tree-view?

**Comment by john-sparwasser** [comment]
This issue is now here: https://github.com/atom/tree-view/issues/491
