### ISSUE TITLE
Collapsing a function sometimes doesn't work correctly

### ISSUE THREAD

**Issue by pgkos** [atom/atom#7393]
Steps to reproduce:
1 . Open a new file.
2 . Write (note the indentation):
```javascript
function foo()
    {
// comment
    }
```
3 . Set the syntax to JavaScript (this bug also affects other languages).
4 . Try to collapse the function.

**Comment by 50Wliu** [comment]
Yeah, folding in Atom is currently solely indentation-based.  Please see atom/atom#3442 for more details.
