### ISSUE TITLE
0.211.0 crashes on Windows 8.1

### ISSUE THREAD

**Issue by flaviolaino** [atom/atom#7401]
I can't use anymore Atom at 0.211.0 version because of it closes few istants after the launch.
At the moment I use prev version 0.210.0

**Comment by flaviolaino** [comment]
It seems crash when mouse over

**Comment by kubetz** [comment]
Is atom crashing [in safe mode](https://atom.io/docs/v0.186.0/debugging#check-if-the-problem-shows-up-in-safe-mode)?

`atom --safe`

**Comment by flaviolaino** [comment]
Yes, also in safe mode.

**Comment by kubetz** [comment]
Other ideas:
* run atom from terminal using `atom -w` and look for error messages
* try to temporarily rename your `.atom` directory and start atom afterwards

Hopefully it helps getting more information until someone more experienced notices this issue :sweat_smile:.

**Comment by batjko** [comment]
Cant replicate that. I'm running 211 on Win8.1 64bit just fine, no crashing.

Temporarily eliminating the .atom folder, as @flaviolaino suggests, would be next step as well. Again in safe mode, just to be sure.

**Comment by flaviolaino** [comment]
running atom -w:
```
C:\Users\flaviolaino>atom -w
App load time: 1140ms
[6180:0625/091837:INFO:renderer_main.cc(212)] Renderer process started
[5888:0625/091839:INFO:CONSOLE(108)] "UsefulContextMenu was toggled!", source: C:\Users\flaviolaino\.atom\packages\useful-context-menu\lib\useful-context-menu.coffee (108)
[5888:0625/091839:INFO:CONSOLE(56)] "Window load time: 2047ms", source: file:///C:/Users/flaviolaino/AppData/Local/atom/app-0.211.0/resources/app.asar/static/index.js (56)

C:\Users\flaviolaino>
```

Where is `.atom` folder?
You mean `AppData/Local/atom/`?

Thank you

**Comment by flaviolaino** [comment]
Ok I found .atom folder and I move it to another position, then I launch atom in safe mode, with the same result: it closes when I perform any input on it (mouse hover, key down).

**Comment by batjko** [comment]
Ah, yes the .atom folder is under `C:\Users\[username]\.atom`, I assume that's the one you moved?

**Comment by batjko** [comment]
Another thing, are you using Atom on a virtual machine by any chance? We know there are sometimes issues with mouse and other input via a VM.

**Comment by flaviolaino** [comment]
Yeah, I moved that one.
No, I haven't a virtual machine.

**Comment by flaviolaino** [comment]
Update: my laptop crashes and auto restarts.
Now 0.211.0 works...!

**Comment by batjko** [comment]
lol... so we can safely blame your laptop then. Love it!

**Comment by mnquintana** [comment]
Gotta love the ol' restart. If it's resolved now, can we close this out @flaviolaino?

**Comment by flaviolaino** [comment]
Yes, it's resolved for me (for now).
Thank you all.
