### ISSUE TITLE
Requiring a custom node_modules dependency in inspector

### ISSUE THREAD

**Issue by yamsellem** [atom/atom#7402]
I've just noticed that npm common modules are available in atom inspector with `require('util')`.
This is great!

I was wondering if we can expect requiring our own `node_modules` in there?
Like `require('moment')` looking at `node_modules` and resolving the import.

_ps. since when the require is supported in the inspector, I don't find the info anywhere in the [release notes](https://atom.io/releases)_?

**Comment by kevinsawicki** [comment]
Are you asking about requiring modules from your own packages in the dev tools?

You can use an absolute path for this case, such as the following for a package such as `vim-mode`:

```js
require(require('path').join(atom.packages.getLoadedPackage('vim-mode').path, 'node_modules', 'event-kit'))
```

This will require the version of the `event-kit` library from the `vim-mode` package.

Closing this out, hope this answers your question, please comment if it doesn't.

**Comment by yamsellem** [comment]
Thanks for your answer.
The syntax is hardcore to remember; using `require('moment')` would be awesome, and, if I may, natural.

**Comment by mnquintana** [comment]
> using require('moment') would be awesome, and, if I may, feels right.

@yamsellem I don't think that would really be possible – say you have two packages, A and B, with two different versions of moment. If you just run `require('moment')`, which version would you expect it to load? You need some way of unambiguously specifying the exact dependency, which is only possible if you require a module from an absolute path.

**Comment by yamsellem** [comment]
@mnquintana requiring dependency's dependencies may be difficult. But I was not meaning something like that, just requiring the `node_modules` dependencies at the root of the tree structure (and, may be, configuring where this folder is in a second time). Just one `node_modules` folder. 

And if someone needs to test a dependency in atom inspector, adding it to its `package.json` will do the trick.
