### ISSUE TITLE
Feature request: Auto updating atom in Linux

### ISSUE THREAD

**Issue by meghprkh** [atom/atom#7410]
Can auto update in atom (from within atom) on linux, please be worked upon?

If possible it should have delta updates.

**Comment by ollpu** [comment]
Would be very useful :+1:

**Comment by whatasunnyday** [comment]
I agree entirely but a discussion for that is going on over here: https://github.com/atom/atom/issues/2956. It might be useful to rename the previous issue to better reflect the discussion. Not sure if this issue needs to stay open.

**Comment by whatasunnyday** [comment]
Also, in case you need to update your current atom installation for the 1.0 release, I recommend you try a variant of this script:

```bash
#!/bin/bash

cd /tmp
wget https://atom.io/download/deb -O atom.deb
sudo dpkg -i atom.deb
```

credit to @AsaAyers.

**Comment by mnquintana** [comment]
Thanks for the suggestion! As far as I know, the plan is to support native distro package managers for updates, rather than adding auto-update to Atom directly. Either way, let's keep the discussion in https://github.com/atom/atom/issues/2956 (now renamed to be more general).
