### ISSUE TITLE
Searching packages aways fails 

### ISSUE THREAD

**Issue by dave7802** [atom/atom#7414]
Getting really wound up by the latest update. 
Appears it just HANGS are various points like when trying to search for a package. Install, Select a option
You have no idea if its accepted your response or just frozen. 

Its taken over 30 attempts to load the packages to install 1 package.... Really. 

Thinking of going back to PHPEd after this, seriously messed up my day!!
This may be a irrelivent Issue to track, But i wanted to provide my feedback to why i am now leaving Atom. 

Its not ideal for someone trying to do alot of work under tight deadlines.

**Comment by dave7802** [comment]
I take that back, it never even installed the package after all that!!! Geezzz

**Comment by balzathor** [comment]
Works just fine for me, Where does it get stuck for you?

**Comment by mnquintana** [comment]
@dave7802 atom.io is under heavy load right now (since the 1.0 announcement :stuck_out_tongue_closed_eyes:)  - a fix is in the works though!

**Comment by dave7802** [comment]
Loading packages, 
Searching packages for "XXXXXX" Always returns. 
Searching packages failed: atom.io is temporarily unavailable, please try again later.

Thanks for the response,

**Comment by SirEdges** [comment]
Hi, i know its 2017...just started learning to program and i liked the way atom's UI looks and the support of many features... but i have been experiencing difficulty from day 1 installing THEMES and PLUGINS... displaying errors: Fetching local packages failed.Hide output…spawn C:\WINDOWS\system32\cmd.exe;C:\Program Files (x86)\Java\jdk1.7.0_07\bin;C:\Users\<username>\AppData\Local\atom\app-1.18.0\resources\app\apm\bin ENOENT 

UPDATE:
![image](https://user-images.githubusercontent.com/29626299/27428992-405cb94a-5733-11e7-88a4-2a1a14b23401.png)


THEME:
![image](https://user-images.githubusercontent.com/29626299/27429053-63febae2-5733-11e7-8b5d-3c0dabc6b217.png)


PACKAGES:
![image](https://user-images.githubusercontent.com/29626299/27429079-85b5c2a2-5733-11e7-84f2-ca99f0103be8.png)

**Comment by vamshi9666** [comment]
i still face this issue
how did you guys close this issue?
