### ISSUE TITLE
Theme name 

### ISSUE THREAD

**Issue by tanvirraj** [atom/atom#7416]
what is theme name that show in atom.io homepage 
![screen shot 2015-06-25 at 10 59 14 pm](https://cloud.githubusercontent.com/assets/3768120/8360627/bbb80522-1b8f-11e5-8982-3eb47717804d.png)

**Comment by mnquintana** [comment]
That's One Dark UI and One Dark Syntax - they ship with Atom and have been the default themes since [0.188.0](https://github.com/atom/atom/releases/tag/v0.188.0).

**Comment by thomasjo** [comment]
I believe those screenshots might be based on the special [high contrast branch](https://github.com/atom/one-dark-syntax/tree/sm-high-contrast).

For future reference, please consider using either https://discuss.atom.io/ or [Slack](https://atomio.slack.com/) for these types of questions :bow:
