### ISSUE TITLE
Markdown syntax highlighter doesn't ignore code block's asterisks

### ISSUE THREAD

**Issue by cbowns** [atom/atom#7422]
Markdown parser reads italics from "*" in code blocks but shouldn't.

My Markdown READMEs are mostly italicized these days:

![](https://cloudup.com/files/iWKHthnh4-w/download)

Even though this is a code block (indented by a tab or four spaces), the in-file syntax highlighter doesn't know it.

## Repro Steps

1. Put some code with a "*" in a markdown file. Here's some simple Markdown for you:

```
Hello everyone! Here's some code:

    NSString *title = [NSString stringWithString:@"Hi"];

Anyways, hope your text looks normal!
```

2. Open this in Atom.

## Versions

* **Atom:**       1.0.0
* **Atom-Shell:** 0.22.3
* **OS:**         Mac OS X 10.10.3

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by cbowns** [comment]
(This doesn't happen for "```" based GFM code blocks, but it does for indentation-based ones.)

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/markdown-preview?

**Comment by cbowns** [comment]
Done! Didn't know that existed, thanks.
