### ISSUE TITLE
Markdown preview doesn't have a scrollbar

### ISSUE THREAD

**Issue by cbowns** [atom/atom#7423]
On my Mac, a sample Markdown file that's more than one page:

![screen shot 2015-06-25 at 3 17 14 pm](https://cloud.githubusercontent.com/assets/474/8366825/51ba21ec-1b4d-11e5-9141-a5163d34e32b.png)
![screen shot 2015-06-25 at 3 17 16 pm](https://cloud.githubusercontent.com/assets/474/8366824/51b8b0c8-1b4d-11e5-814a-17dffe705cc5.png)

Doesn't render with a scrollbar in the preview.

![screen shot 2015-06-25 at 3 17 22 pm](https://cloud.githubusercontent.com/assets/474/8366822/519f079a-1b4d-11e5-921d-440b67d83706.png)
![screen shot 2015-06-25 at 3 17 21 pm](https://cloud.githubusercontent.com/assets/474/8366823/51b8c3e2-1b4d-11e5-9ab3-33e4785f6a0a.png)

A tiny movie: https://cloudup.com/cHaasRuYJoX

Versions:
- **Atom:**       1.0.0
- **Atom-Shell:** 0.22.3
- **OS:**         Mac OS X 10.10.3

**Comment by The-Compiler** [comment]
FWIW I see a scrollbar in the preview with Atom 1.0.19 on Linux.

**Comment by cbowns** [comment]
Word. I still don't on 1.0.19 on OS X El Cap (10.11.1.)

**Comment by cbowns** [comment]
Cool, fixed as of 1.19.2 on OS X
