### ISSUE TITLE
cmd+n should default to cmd+shift+n when no windows are open on OS X

### ISSUE THREAD

**Issue by void-validation** [atom/atom#7428]
Atom: 1.0
Mac OS X: 10.10.3

On OS X, if you close all windows so only the menubar is active, cmd+n does nothing at all. It should default to cmd+shift+n if no windows are open in Atom.app.

Apple mention suggestions for default keys here: http://support.apple.com/kb/HT1343

**Comment by dominikwilkowski** [comment]
:+1:

**Comment by cesarandreu** [comment]
Similarly, when you no longer have open tabs, I would expect pressing Command-W to close the front window and focus the next window in the stack unless the window is minimized. I'm on OS X 10.10.4 and Atom 1.0.

This is how Sublime Text 3 behaves. Google Chrome also behaves similarly, except that they do it when you have a single open tab. Pressing Command-W when you have a single open tab will close the window and shift focus to the next open window unless it's minimized.

Should I create a separate issue for this or piggyback on this one?

**Comment by lee-dohm** [comment]
@cesarandreu it's generally best to keep one item per Issue. This way there is no confusion as to when to close it.

**Comment by jacekkopecky** [comment]
To get the described behaviour, what works for me is to put the following in `.atom/keymap.cson`:
```
'body':
  'cmd-n': 'application:new-window'
'atom-workspace':
  'cmd-n': 'application:new-file'
```
Except now the File menu shows `cmd-N` for both commands, but what the heck, nobody ever looks.

**Comment by joshaber** [comment]
Fixed by https://github.com/atom/atom/pull/10233.
