### ISSUE TITLE
Atom not launching

### ISSUE THREAD

**Issue by kumar91gopi** [atom/atom#7429]
i tried uninstalling and installing again but its not launching again.
There is no error message shown , i tried to launch it through cmd as well but its still not launching

**Comment by kubetz** [comment]
What is your OS?
So nothing is shown at all even for a split second?
Does installing older version works for you?

These steps can help providing at least more information:
* Run atom in safe mode: `atom --safe`
* Temporarily remove/rename your `.atom` folder and try to run atom.
* Run atom from terminal using `atom -w` and watch if you at least get some output.

**Comment by mluu-stratusee** [comment]
I've got the same issue running on ubuntu 12.04 64bit. Here is the error message

[5273:0626/102420:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
LaunchProcess: failed to execvp:
/proc/self/exe
App load time: 160ms
LaunchProcess: failed to execvp:
/proc/self/exe
[5787:0626/103902:WARNING:file_descriptor_set_posix.cc(30)] FileDescriptorSet destroyed with unconsumed descriptors: 0/1

**Comment by kumar91gopi** [comment]
Problem fixed. Dont know what the problem was but i tried re-installling after restart and atom worked this time but now my php cs fixer not working :(

**Comment by izuzak** [comment]
> Problem fixed. Dont know what the problem was but i tried re-installling after restart and atom worked this time but now my php cs fixer not working :(

@kumar91gopi Thanks for letting us know. I'll close this and let us know if you notice this again.

> I've got the same issue running on ubuntu 12.04 64bit. Here is the error message

> [5273:0626/102420:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox!

@mluu-stratusee -- I don't think this is the same problem that's described here. Still, I think I've noticed a bunch of other issues with that message, so I recommend you search through the issues in this repository to find those.
