### ISSUE TITLE
Clicking URLs in Package and Theme views cause unresponsiveness

### ISSUE THREAD

**Issue by SamSchlegel** [atom/atom#7430]
Clicking URLs in the Package and Theme views such as Package/Theme names and authors causes the main WebView to go unresponsive. No exception is thrown that the Developer Tool can catch and pausing has no effect, so it's probably at a deeper level. Currently trying to step through and find the exact code that causes the crash.

**Atom Version:** 1.0.0 built from commit 3874576
**System:** Arch Linux

**Comment by SamSchlegel** [comment]
I've narrowed it down to calling `shell.openExternal` causing the unresponsiveness. Looking into it further.

**Comment by SamSchlegel** [comment]
Strange...it seems to work when called from menu entries in atom: `browser/atom-application.coffee:178`. Will make a ticket on `atom/settings-view` since it seems to only be happening in that view.

**Comment by SamSchlegel** [comment]
Seems like it might be related to https://github.com/atom/electron/issues/1348. However that it works when called from core atom, but not `settings-view` might be worth noting

**Comment by SamSchlegel** [comment]
Seems as this is the culprit https://github.com/atom/atom/issues/5388#issuecomment-106653179

**Comment by lee-dohm** [comment]
I agree that this is most likely a duplicate. Closing per request.
