### ISSUE TITLE
path balloon is not refreshed after "Save As..." operation

### ISSUE THREAD

**Issue by thinklog** [atom/atom#7436]
Moved to Issues at Atom/Tabs

**Comment by mnquintana** [comment]
Thanks for the report! Would you mind moving this to https://github.com/atom/tabs?

**Comment by thinklog** [comment]
I'll be happy to comply. But how do I move it?

**Comment by 50Wliu** [comment]
You can just copy/paste your issue contents over (or, alternatively, use github-issue-mover.appspot.com).

**Comment by bradleyflood** [comment]
Ran into the same issue today. @thinklog has created the following ticket in the atom/tabs repo so this issue can be closed.
See https://github.com/atom/tabs/issues/189
