### ISSUE TITLE
Atom 1.0 will consume 100% CPU when managing packages

### ISSUE THREAD

**Issue by lovio** [atom/atom#7438]
No matter installing or uninstalling packages, `Atom Helper` will comsume over 100% CPU.

**Comment by hax** [comment]
me 2. `atom --safe` doesn't help.

**Comment by jellymann** [comment]
I am using Atom 1.0 on OS X, and the Atom Helper process is using a maximum of 40% CPU during package updates.

What is your system information?

My system:
 * OS X 10.10.2
 * 2012 Retina MBP 
 * CPU: 2,7 GHz Intel Core i7

**Comment by hax** [comment]
Seems the problem of nuclide.

**Comment by bsbhro** [comment]
Other processes consume over 100% too. My terminal gave a hint: X-Window error (Ubuntu1504). Often the error message with "Keep Waiting", but the high memory consuming remains. I can't work with this version...

**Comment by samueloph** [comment]
This is happening to me too, since v0.211.0.

Running Debian Stretch here.

When I try to check for package's updates, some atom process starts eating all the memory.

**Comment by mnquintana** [comment]
This issue was moved to atom/settings-view#555
