### ISSUE TITLE
Available Updates still shows Atom 1.0 deprecation warning in Atom 1.0

### ISSUE THREAD

**Issue by jellymann** [atom/atom#7441]
When viewing "Available Updates" in Atom 1.0, the deprecation warning is still visible.

![monosnap 2015-06-26 09-47-07](https://cloud.githubusercontent.com/assets/1171825/8372937/575db654-1be8-11e5-9aaa-4f92f8a56194.png)

I believe this message should not exist in Atom 1.0, or should at least be rephrased, as "when Atom 1.0 is released in June" is an event that has now already come to pass.

Atom Version: 1.0
OS X: 10.10.2

**Comment by thomasjo** [comment]
Thanks for reporting this; the problem was resolved in https://github.com/atom/settings-view/pull/552. The next (minor, or patch) release of Atom will contain the fix.
