### ISSUE TITLE
Windows uninstallation is too silent

### ISSUE THREAD

**Issue by chrullrich** [atom/atom#7445]
When uninstalling Atom from the Windows control panel, after clicking "uninstall", absolutely nothing appears to happen. Then, several seconds later, the "Atom" entry suddenly disappears from the list of installed packages. This total lack of feedback is not very user-friendly, IMO.

**Comment by Gheoan** [comment]
:+1:

**Comment by marcsoler** [comment]
Same here. Found it too weird. Win 7

**Comment by paulcbetts** [comment]
Uninstall will never do anything other than uninstall the app, sorry!

**Comment by ChristianGrech** [comment]
+1

**Comment by marcsoler** [comment]
I solved this by installing it via Administration rights

**Comment by damieng** [comment]
No plans to change this behavior.
