### ISSUE TITLE
The .python-version file causes build failure when using pyenv

### ISSUE THREAD

**Issue by konradstrack** [atom/atom#7450]
The `.python-version` file was added with pull request #4454. 

When building Atom (any version) on Arch Linux (using AUR package: https://aur.archlinux.org/packages/atom-editor/) with pyenv installed (https://github.com/yyuu/pyenv), this is what happens:

```
Node: v0.12.5
npm: v2.11.3
Installing build modules...
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: python2 -c import platform; print(platform.python_version());
gyp ERR! stack pyenv: version `2.7.6' is not installed
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:751:12)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at maybeClose (child_process.js:1015:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
gyp ERR! stack     at Socket.emit (events.js:107:17)
gyp ERR! stack     at Pipe.close (net.js:485:12)
gyp ERR! System Linux 4.0.5-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
(...)
```

After digging deeper with PYENV_DEBUG=1, we can see that pyenv tries to use Python 2.7.6 as specified in `.python-version` present in Atom's source:

```
gyp ERR! stack + [pyenv:108] exec /home/ancestor/.pyenv/libexec/pyenv-exec python2 -c 'import platform; print(platform.python_version());'
gyp ERR! stack + [pyenv-exec:20] '[' python2 = --complete ']'
gyp ERR! stack ++ [pyenv-exec:24] pyenv-version-name
gyp ERR! stack + [pyenv-version-name:6] '[' -z '' ']'
gyp ERR! stack ++ [pyenv-version-name:7] pyenv-version-file
gyp ERR! stack + [pyenv-version-file:21] find_local_version_file /tmp/pacaurtmp-ancestor/atom-editor/src/atom-1.0.0/build/node_modules/runas
(...)
gyp ERR! stack + [pyenv-version-file:10] echo /tmp/pacaurtmp-ancestor/atom-editor/src/atom-1.0.0/.python-version
gyp ERR! stack + [pyenv-version-file:11] exit
gyp ERR! stack + [pyenv-version-name:7] PYENV_VERSION_FILE=/tmp/pacaurtmp-ancestor/atom-editor/src/atom-1.0.0/.python-version
gyp ERR! stack ++ [pyenv-version-name:8] pyenv-version-file-read /tmp/pacaurtmp-ancestor/atom-editor/src/atom-1.0.0/.python-version
gyp ERR! stack + [pyenv-version-file-read:6] VERSION_FILE=/tmp/pacaurtmp-ancestor/atom-editor/src/atom-1.0.0/.python-version
gyp ERR! stack + [pyenv-version-file-read:8] '[' -e /tmp/pacaurtmp-ancestor/atom-editor/src/atom-1.0.0/.python-version ']'
gyp ERR! stack + [pyenv-version-file-read:11] IFS='     
'yp ERR! stack 
gyp ERR! stack + [pyenv-version-file-read:12] words=($(cut -b 1-1024 "$VERSION_FILE" | sed 's/^\s*\(\S\+\).*/\1/'))
gyp ERR! stack ++ [pyenv-version-file-read:12] cut -b 1-1024 /tmp/pacaurtmp-ancestor/atom-editor/src/atom-1.0.0/.python-version
gyp ERR! stack ++ [pyenv-version-file-read:12] sed 's/^\s*\(\S\+\).*/\1/'
gyp ERR! stack + [pyenv-version-file-read:13] versions=("${words[@]}")
gyp ERR! stack + [pyenv-version-file-read:15] '[' -n 2.7.6 ']'
gyp ERR! stack + [pyenv-version-file-read:16] IFS=:
gyp ERR! stack + [pyenv-version-file-read:17] echo 2.7.6
gyp ERR! stack + [pyenv-version-file-read:18] exit
gyp ERR! stack + [pyenv-version-name:8] PYENV_VERSION=2.7.6
gyp ERR! stack + [pyenv-version-name:11] '[' -z 2.7.6 ']'
gyp ERR! stack + [pyenv-version-name:11] '[' 2.7.6 = system ']'
gyp ERR! stack + [pyenv-version-name:21] versions=()
```

It is Is there any reason for this file to actually be in the repository? Unless there is anything in Atom that requires Python version to be exactly 2.7.6 and pyenv for building it, the only effect this file would have is enforcing an old Python version on pyenv users.

There is a workaround, by overriding Python version with `pyenv shell`, but maybe the file could just be removed to avoid using this workaround for each build?

**Comment by thomasjo** [comment]
Python is required due to node-gyp which relies on Python 2.7. Whether it needs the exact version (2.7.6) is unknown to me. Since you're using pyenv, why not simply type `pyenv install` from the repo dir?

If you (or someone else) can verify that there are no issues with 2.7.10, we can bump the version.

**Comment by konradstrack** [comment]
Yes, I understand the requirement of Python 2.7 for node-gyp (its README recommends v2.7 on Unix and v2.7.3 on Windows). However, `.python-version` enforces 2.7.6 only for Linux and OS X users with pyenv installed, and pyenv is neither a requirement for the build process, nor Atom's dependency.

In other words, I think that this file is redundant, because both Atom and node-gyp have their own checks in place to determine whether Python 2 is available, but it breaks the build process on some particular configurations. Moreover, "Also, I see you need python 2 so I used python 2.7.6 and it worked." in #4454 suggests that it may have been an arbitrary decision.

But I'm not insisting - I can use one of the available workarounds (including `pyenv install 2.7.6`), and it also builds correctly for me with 2.7.10.

**Comment by kevinsawicki** [comment]
@konradstrack do you know if pyenv supports a version range in the file instead of a pinned version?

**Comment by thomasjo** [comment]
It does not, sadly.
https://github.com/yyuu/pyenv/wiki

**Comment by aviraldg** [comment]
This is still an issue with the current version of the AUR package. It'd probably be a better idea to get rid of it entirely, if @konradstrack is correct.

**Comment by thomasjo** [comment]
> This is still an issue with the current version of the AUR package. It'd probably be a better idea to get rid of it entirely, if @konradstrack is correct.

Removing it is not really an option either; if someone is using pyenv and their (global) pyenv Python is mapped to e.g. `3.5.0`, and the system does not have a `python2` executable (symlinked or whatever), an error will be produced because there is nothing being mapped to the `python2` shim created by pyenv.

So while this might "fix" your problem in Arch, it breaks building on OS X. 

```
$ pyenv shell 3.5.0
$ pyenv which python2
pyenv: python2: command not found

The `python2' command exists in these Python versions:
  2.7.10
  2.7.6
```

I'll happily bump the version in `.python-version` to `2.7.10`, but I'm :-1: on deleting the file.
