### ISSUE TITLE
unable to install in windows7

### ISSUE THREAD

**Issue by Macoop** [atom/atom#7451]
I try to install "Atom" by installer, AtomSetup.exe.
However, I can not install and it pop up that error message, "Unable to wright to C:\users\name\appdata\local\squirreltemp - IT policies may be restricting access to this folder"
and do not emit error log-text.

I never have installed atom in my computer, and I prepare the /squirreltemp folder before execute "AtomSetup.exe", and emitting the message, "Failed to extract installer".  and do not emit log as with above.

**Comment by Macoop** [comment]
I never have installed atom in my computer, and I prepare the /squirreltemp folder before execute "AtomSetup.exe", and emitting the message, "Failed to extract installer".

**Comment by batjko** [comment]
You do not need to "prepare" any temp folders. There seems to be a permissions issue, so maybe double-check that there is no problem accessing the path described by the error under your user account?

**Comment by Macoop** [comment]
@batjko 
Thank you for replying :)
So, I try also execute .exe file as Administrator role, but I can not.
Just maybe, there are another way to remove access restriction... I do not know...

**Comment by batjko** [comment]
Ok, running as Administrator should also not be necessary, as most people install it fine under their normal accounts.

But firewall or proxy settings could be an issue. Any chance you are behind one of those?

**Comment by Macoop** [comment]
@batjko 
I try to install canceling the firewall one time, So I think that there are the problems of setting proxy.
Are there pre-setting of proxy to install?

**Comment by Macoop** [comment]
I can solve this problem myself just now. 
I can install the process that I move AtomSetup.exe file into "c:/users/<name>/appdata/local/squirreltemp/" and execute this.
If there is no "squirreltemp", you make the name's directory.

Thanks @batjko and so on : )

**Comment by batjko** [comment]
Hm, alright. Glad you got it to work then! :+1:

**Comment by noogoom** [comment]
If anyone else has this issue as well (I have Windows 8, 64 bit, tried cc cleaner, deactivating the firewall, the workaround above) - for me nothing seemed to work either, so I simply downloaded the 

atom-windows.zip

from here
https://github.com/atom/atom/releases/tag/v1.12.3

And voilà, everything worked quickly and perfecto.
