### ISSUE TITLE
atom.workspace.openSync calls the undefined atom.project.openSync

### ISSUE THREAD

**Issue by vellerefond** [atom/atom#7452]
Atom version: 1.0.0
OS: Any

Calling atom.workspace.openSync calls the undefined atom.project.openSync method.

**Comment by mnquintana** [comment]
Any reason why you're trying to call `atom.worskpace.openSync`? [It's not in the public API for Workspace, so it's technically not supported.](https://atom.io/docs/api/v1.0.0/Workspace#instance-open)

**Comment by vellerefond** [comment]
I am working towards providing a pane save/restore feature for my package (project-ring) so I though I needed it to properly (synchronously) open files while recreating the panes layout. It seems that atom.workspace.open does the job well (in contrast to the asynchronous atom.open so I don't actually need it. As such, I reported this because I thought this was something forgotten during the clean up of the API. If it's deliberate please ignore/close this issue.
