### ISSUE TITLE
Long waiting times when opening minified js file.

### ISSUE THREAD

**Issue by dominikwilkowski** [atom/atom#7453]
Hey there,

I am not sure this has been reported yet and it could very well be related to this #979 issue.

When I open a minified file (in my case a default jquery v1.11.2) I get the `Keep Waiting or Close` dialog.

I can reproduce that 100% every time. Now I opened the file in dev mode and recorded the timeline and get the below:

![screen shot 2015-06-26 at 9 48 48 pm](https://cloud.githubusercontent.com/assets/1266923/8376688/2cba85e8-1c4d-11e5-8f42-af33b9dee451.png)

Hope this helps

Atom: 1.0.0
OS: Mac 10.10.3

**Comment by izuzak** [comment]
Thanks for the report.

> it could very well be related to this #979 issue.

It's very likely that it is, so I'm closing this in favor of that issue. Please follow along there :bow:
