### ISSUE TITLE
plugins search can't work at 1.0 release

### ISSUE THREAD

**Issue by foxmuldercp** [atom/atom#7454]
Use case:
Open Packages -> Settings view -> Install packages, then enter some text in search field, but nothing doing.
for get result I must change Packages button to Themes and switch again for a get search result.
No 'Enter' key action here too

**Comment by batjko** [comment]
This is a known issue, but I seem to be unable to find an open ticket for it. Can you please re-open this on the [Settings-View repository](https://github.com/atom/settings-view/issues)?
