### ISSUE TITLE
Atom package issue: Linter-clang

### ISSUE THREAD

**Issue by FatManiac** [atom/atom#7456]
Hi,

i've installed atom, and i try to intall a linter-clang package but the instalaltion fail, they told me to send you a file but i don't find it on the following path (/tmp/apm-install-dir-115526-8646-d09wkj/npm-debug.log)

**Comment by batjko** [comment]
Can you clarify who is "they"? The package authors?
Have you raise the problem on the [Linter-clang package's repository](https://github.com/AtomLinter/linter-clang/issues) first?

**Comment by FatManiac** [comment]
I got this :

**Comment by FatManiac** [comment]
I got this

npm ERR! git clone git://github.com/AtomLinter/Linter.git Clonage dans le dépôt nu '/home/maniac/.atom/.apm/_git-remotes/git-github-com-AtomLinter-Linter-git-852cc1e4'
npm ERR! git clone git://github.com/AtomLinter/Linter.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/AtomLinter/Linter.git github.com[0: 192.30.252.128]: errno=Connexion terminée par expiration du délai d'attente
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/maniac/.atom/.apm/.apmrc" "--userconfig" "/home/maniac/.atom/.apmrc" "install" "/tmp/d-115526-11473-rv17ig/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: Clonage dans le dépôt nu '/home/maniac/.atom/.apm/_git-remotes/git-github-com-AtomLinter-Linter-git-852cc1e4'
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=Connexion terminée par expiration du délai d'attente
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115526-11473-66omcx/npm-debug.log

**Comment by thomasjo** [comment]
Are you behind a firewall/proxy?

**Comment by FatManiac** [comment]
yes, but i don't have any problem to install any other package

**Comment by thomasjo** [comment]
Have you tried pinging the IP listed? `ping -c 3 192.30.252.128`. It's reachable from here.
This is seemingly a connection problem on your end, why else would npm report that it's unable to connect?

Just because other packages install fine, doesn't mean it should in this case because *Linter-clang* is doing silly stuff like [depending on *Linter*](https://github.com/AtomLinter/linter-clang/blob/master/package.json#L16) (which is the problematic endpoint mentioned in your npm log).

**Comment by FatManiac** [comment]
i ping it well

**Comment by thomasjo** [comment]
OK, and if you try to clone the repo?

``` bash
$ git clone git://github.com/AtomLinter/Linter.git
```

**Comment by FatManiac** [comment]
unable to connect

**Comment by thomasjo** [comment]
Then that's your problem. Your proxy/firewall is blocking the connection. I would advise you to open an issue on the [Linter-clang repo](https://github.com/AtomLinter/linter-clang/issues) and get them to switch from `git://` schema to `https://`.
