### ISSUE TITLE
Projects lost on closing ATOM

### ISSUE THREAD

**Issue by gs-akhan** [atom/atom#7462]
Hi,
I loose all my projects on closing ATOM and reopening it. :( Is there a setting for this to retain them on close..
Thanks

**Comment by kubetz** [comment]
Do you mean "lost" as deleted or the projects were still on the disk, but atom didn't open them automatically upon startup?

If they were not reopened automatically are you running newest version? Because this was a bug that got fixed several weeks ago.

**Comment by mnquintana** [comment]
What version of Atom are you using @gs-akhan? What OS?

**Comment by gs-akhan** [comment]
@kubetz , lost in the sense they are no longer in projects inside ATOM. I have to add project again. 
No they are not lost from disk.

@mnquintana I am on v1.0 on Mac.  btw how do I know which version I am on. I am checking the release notes under help tab.. 

Thanks

**Comment by thomasjo** [comment]
![_and_menubar](https://cloud.githubusercontent.com/assets/3622/8393506/a4edaa2a-1d12-11e5-9edb-02024e62aa7b.png)

**Comment by mnquintana** [comment]
@gs-akhan How are you reopening Atom?

**Comment by gs-akhan** [comment]
I am running 1.0.
So When I close the ATOM using "x" or close icon on header and reopen ATOM from tray - the projects disappear from sidebar. 
However when I do Atom -> Quit.  and then reopen - project folders are retained.

:) Thanks

**Comment by mnquintana** [comment]
Ah, in that case, see https://github.com/atom/atom/issues/1603#issuecomment-116083606:

> That is intended behavior, and is how all OS X applications that save sessions work. Otherwise it would be impossible to remove windows from the saved session - you could only add windows and never remove them without resetting the entire saved session.

To make Atom remember your open projects, you have to actually *quit* Atom by going to Atom > Quit or quitting with <kbd>Cmd-Q</kbd>.

**Comment by a7madgamal** [comment]
@mnquintana as a relatively new mac user, I didn't know about mac sessions and how they work.
I did think it was a bug and I installed a package just to solve this
Your last comment was very informative and clear (thanks!) 

However, I think it would be best if Atom displays a warning when closing any open windows using (x) and ask if you want to remove the window from session or just close it for now
OR if that's not possible just show you comment in an alert with default answer or something!

**Comment by 42piratas** [comment]
@mnquintana Is there any way to change that behavior in a way that even if I close Atom using the 'x' button it still keeps the project folders when I reopen it? Thanks!

**Comment by lee-dohm** [comment]
@42piratas It _might_ be possible to build a community package to offer something like that, I haven't looked to see if there's an easy API hook for it. We don't have any plans to offer the feature you're describing, though, so this will remain closed. And since it is such an old issue, I'm going to lock this to direct people to the explanation that @mnquintana gave above:

> That is intended behavior, and is how all OS X applications that save sessions work. Otherwise it would be impossible to remove windows from the saved session - you could only add windows and never remove them without resetting the entire saved session.

We don't have any plans to change this behavior.
