### ISSUE TITLE
Atom and Git

### ISSUE THREAD

**Issue by Nelidon** [atom/atom#7463]
Hello,

There is an issue with Atom when we work with git.
If I add lines in a file (php in my case) the git gui show that I added a lot of space in my file 

Screenshots:
Atom editor: http://puu.sh/iDuSA/554e6e4446.png
Git result: http://puu.sh/iDuVq/fbc4167856.png

Windows 8.1
Version 1.0.0.

**Comment by batjko** [comment]
Those screenshots are a little confusing.
Where exactly is all that extra space being added?

Can you replicate this behavior if you start atom in safe mode (`atom --safe`)?

**Comment by thomasjo** [comment]
I'm guessing this is an issue of mixed soft and hard tabs. Looks like those "spaces" are actually tab stops, which would look differently in a terminal than in Atom.

**Comment by Nelidon** [comment]
Still the same issue with <code> atom --safe </code>
@thomasjo : you are right, if I open my file with Sublime Text 2, the "spaces" added by Atom are in reality tabs.

**Comment by thomasjo** [comment]
Does the file have tabs for indentation near the beginning of the file? Atom tries to detect whether a file is using soft or hard tabs, per file, and switches to whatever it thinks is the best choice. Outside of packages, there's currently no way to force soft or hard tabs.

**Comment by Nelidon** [comment]
I convert my file to spaces instead of tabs indentation and Atom works fine.

**Comment by damieng** [comment]
Was an issue of tabs vs spaces.
