### ISSUE TITLE
Touch version of Atom

### ISSUE THREAD

**Issue by scj643** [atom/atom#7466]
A touch version of atom with builds for jail broken iOS devices and Android devices.

This will probably take a lot of work to get done but would be worth it. Since atom is a web technology based in nature just making it touch capable would be the only thing needed.

This could be done as a separate branch of Atom and also a version that doesn't have as much of the hack ability as the regular version for release on the iOS App Store.

The iOS version would have to support x-callback-urls for compatibility with coding apps that have them like an app called Working Copy which is a great Git client for iOS.

**Comment by batjko** [comment]
It may not have everything you need, but have you tried this package:
https://atom.io/packages/atom-touch-events


Otherwise, the related open issue could be seen as the original request I suppose, so I would close this one as a duplicate and comment on the latter to progress:
https://github.com/atom/atom/issues/6724

**Comment by mnquintana** [comment]
Just to clarify - are you looking for mobile support or just support for touch events on any platform (possibly including iOS and Android in addition to desktop)?

**Comment by thomasjo** [comment]
I'm pretty sure Node.js does not run on iOS devices. Same goes for Android. Long story short, Atom will not run on iOS or Android devices. 

@mnquintana this is basically a duplicate, but I'm on a train on my mobile so I can't find the issue.

**Comment by batjko** [comment]
@thomasjo The one I mentioned above?

**Comment by thomasjo** [comment]
@batjko No I was thinking about the "make a web version of Atom" issue. Not specific to touch. Yours is still a good reference though!

**Comment by batjko** [comment]
Ah got it.

**Comment by scj643** [comment]
https://github.com/node-app take a look at that.
Node JS for iOS. This is for mobile support since most of the text editors I've seen for mobile are too basic or pricy.

**Comment by davecarlson** [comment]
Now that the iPad Pro exists, an iOS version of atom would be KILLER

**Comment by Envo** [comment]
+1

**Comment by braco** [comment]
+1, this would be game changing

**Comment by timofonic** [comment]
Please make it happen! :dart: 

BTW, I wrote an issue about Electron framework [here](https://github.com/atom/electron/issues/3438).

**Comment by thedaniel** [comment]
Given that Atom is currently built with Electron and depends on our custom fork of libchromiumcontent, this would be a huge effort with limited payoff, and likely impossible without drastically changing the architecture of the editor. We'd prefer to focus on making Atom and Electron better on OS X, Windows and Linux. 

Maybe in the future, mobile OSes will provide tooling to let Electron apps be compiled without much modification, but we won't be rewriting the editor to run on the iOS and Android of today.

For touch events in general, here are a few issues related to supporting Windows touch events - it's far from the stated desire of this issue, but working with any kind of touch UI is a necessary very early first step to running on some specific touch hardware:  https://github.com/atom/atom/issues/6336  https://github.com/atom/atom/issues/2209

**Comment by padster2015** [comment]
if the code was running on a Linux box, could a UI be written to hit Thai an service so the server?
