### ISSUE TITLE
Not possible to write ">" using "Alt-Gr" + "."

### ISSUE THREAD

**Issue by pssgcsim** [atom/atom#7468]
Hi,
I'm having trouble to write character ">" using keys "Alt-Gr" + ".". I think it might be a bug.
(Using Czech keyboard if it has any affect on this)

**Comment by mnquintana** [comment]
Thanks for the report! This is a duplicate of https://github.com/atom/atom-keymap/issues/35 and/or https://github.com/atom/atom-keymap/issues/37 – please subscribe there for updates.
