### ISSUE TITLE
Missing 32bit builds for Linux (debian)

### ISSUE THREAD

**Issue by alinex** [atom/atom#7469]
Do you have any plan on making a debian 32 package in the next days?

**Comment by Maslor** [comment]
:+1: 
I'm also interested in the answer. I hope there'll be one since I really want to install it on my raspberry pi 2 and its architecture isn't compatible with the 64 bit version :astonished:

**Comment by batjko** [comment]
I'm not sure Atom is slim enough for a Raspberry Pi. It does require a fair amount of memory etc.

**Comment by ma-santamaria** [comment]
In the meantime you could use the deb package at https://launchpad.net/~webupd8team/+archive/ubuntu/atom

**Comment by Maslor** [comment]
I know @batjko, you're right, but it would be really cool if a slimmer, raspberry-compatible versions was available. :smile:

**Comment by Maslor** [comment]
I'll try that build out, @ma-santamaria. Thanks! :wink:

**Comment by mnquintana** [comment]
I'm going to close this in favor of https://github.com/atom/atom/issues/6252 – please subscribe there for updates.
