### ISSUE TITLE
Hitting Return key twice deletes the text when using Find feature

### ISSUE THREAD

**Issue by sinisa-medic** [atom/atom#7470]
##### Steps to Reproduce:
1. Open a plain text file containing a lot of content using Atom
2. Hit Command+F key to search for all instances of a particular text
3. Hit Return key once and the app will focus on the first instance of found text
4. Hit Return again and the instance of the text that was found in a previous step will get deleted

##### Expected Result:
* I would expect that hitting Return key would focus on the next instance of found text when using Find feature.  This is how most editors behave.  I am suspecting this to be a bug on the Mac OS X platform as my co-worker that is using Linux does not have the same issue.

##### Actual Result:
* Hitting Return or Enter key delete the first instance of the search text.

**Comment by benogle** [comment]
What version of atom? Can you open the find and replace settings and tell me what this setting is set to?

![screen shot 2015-06-30 at 12 09 58 pm](https://cloud.githubusercontent.com/assets/69169/8439421/f3fe20c6-1f20-11e5-97bc-3ae811ce6c42.png)

If it is checked, you can uncheck it to get what you are looking for.

**Comment by sinisa-medic** [comment]
I am using 1.0.0 version.  I actually do not see "Focus Editor After Search" configuration on the Settings tab.  Is there some package that I am missing?

**Comment by mnquintana** [comment]
@sinisa-medic In Settings, go to the Packages tab and then search for Find and Replace and click it - you should find that setting there.

**Comment by sinisa-medic** [comment]
Thank you.  That fixed it for me.

**Comment by sinisa-medic** [comment]
The only thing that I wonder if there is a discrepancy for the default value for this config between different platforms?  My co-worker is using Atom on Linux, but I am on OS X, and neither one of us remember changing this config after installing Atom.

**Comment by benogle** [comment]
The default is unchecked in all platforms.
