### ISSUE TITLE
'Toggle Developer Tools' doesn't toggle if opened in separate window

### ISSUE THREAD

**Issue by bronson** [atom/atom#7472]
Typing cmd-alt-I or selecting View -> Developer -> Toggle Developer Tools displays the developer tools just fine.  But it doesn't hide them.

**Comment by bronson** [comment]
Aha...  If I return focus to the Atom window and hit cmd-alt-I, it toggles as expected.  So, to reproduce this:

- Open the devtools window, undock it into a separate window.
- Ensure the devtools window is frontmost.
- Hit cmd-alt-I to try to close it.  Ignored!

It would be nice if the "Toggle Developer Tools" menu item worked even when the developer tools are frontmost.

**Comment by Njanderson** [comment]
I want to complete this. Should I just add a keyboard listener to whatever the toggle developer tools is (default is cmd-alt-i-) after the developer tools are toggled?
