### ISSUE TITLE
ARMv7 incompatible

### ISSUE THREAD

**Issue by Maslor** [atom/atom#7473]
When trying to install atom on my raspberry pi, I get this architecture incompatibility error:
![sem titulo](https://cloud.githubusercontent.com/assets/9674408/8388685/102fd742-1c5d-11e5-9f18-229a3c13a4f7.png)

**Comment by Starsam80** [comment]
the deb you got was for amd64, not for armv7. try compiling from source

**Comment by k4li** [comment]
I can't make .deb on my raspberry pi 2. When i run script/mkdeb it finishes but I cant find it(the .deb package).
Any help, please???
