### ISSUE TITLE
Can't delete pre-installed themes

### ISSUE THREAD

**Issue by bebaps** [atom/atom#7474]
Downloaded a fresh copy of Atom 1.0, and the very first thing I attempted to do was to delete some of the pre-installed themes in the settings. Clicking the uninstall button doesn't appear to do anything at all. I have tried with other themes, all with the same result.

![screen shot 2015-06-26 at 4 11 33 pm](https://cloud.githubusercontent.com/assets/5995907/8388980/4ef3624e-1c1e-11e5-82a5-a077e35501e6.png)

**Comment by batjko** [comment]
Bundled packages and themes cannot be uninstalled (there shouldn't be a button for that in these cases).

In the case of themes it shouldn't really matter given that they are not doing anything until you activate them. But packages you can always disable if you want to.

**Comment by izuzak** [comment]
Yeah, this is a bug -- the uninstall button shouldn't be shown for bundled packages or themes. Closing in favor of https://github.com/atom/settings-view/issues/252 which is already tracking this problem. You can just disable those packages if you want.

**Comment by bebaps** [comment]
@batjko @izuzak thanks for the heads up!
