### ISSUE TITLE
"Issue has already been reported" is not always true

### ISSUE THREAD

**Issue by sedabull** [atom/atom#7475]
I've noticed this recently, and I can't find any related open issues (but forgive me if there is one). Sometimes while I'm developing something brand new on `quantum-shell` I'll run into an `Uncaught TypeError` and Atom will tell me that the issue has already been reported at `sedabull/quantum-shell/issues` and ask me if I would like to view it. This is obviously ridiculous, but not really a major issue. The reason I'm reporting it now is because I recently had a user open an issue (sedabull/quantum-shell#17) that he believed was a repeat, but was in fact completely unrelated to the first two issues he mentioned. I understand this feature is meant to deter many people from reopening the same issue over and over, but as it stands now it may actually deter users from reporting an issue they believe is already being worked on. Let me know if there's anything I can do to help resolve this.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/notifications?

**Comment by sedabull** [comment]
I will do that tonight



—

**Comment by sedabull** [comment]
moved to atom/notifications#82
