### ISSUE TITLE
[MINOR BUG] Uninstall/Disable button continue to show after uninstalling package

### ISSUE THREAD

**Issue by tabarra** [atom/atom#7479]
In settings > install > [package], after you uninstall the package, the option doesn't disappear.

**Comment by izuzak** [comment]
Please re-open this issue on the [Settings View package](https://github.com/atom/settings-view), and before that check if the issue has already been reported:

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues
