### ISSUE TITLE
Hide .gitignore'd files when launching Atom in subfolders

### ISSUE THREAD

**Issue by monocasual** [atom/atom#7480]
When I open Atom (1.0.0 on Ubuntu 14.04) on a project subfolder, i.e. not the precise location where the .gitignore file resides, I am still able to see the ignored files, except that they are greyed out. Is it possible to hide them completely?

**Comment by mnquintana** [comment]
Go to Settings > Packages > Tree View > Hide VCS Ignored Files.

For future reference, the file tree is provided by [atom/tree-view](https://github.com/atom/tree-view), not Atom core ([atom/atom](https://github.com/atom/atom)).
