### ISSUE TITLE
auto add blank space when save js file

### ISSUE THREAD

**Issue by lenxeon** [atom/atom#7482]
before save code is
```
React.render(
  <TodoApp /> ,
  document.getElementById('todoapp')
);
```
after save code change to
```
React.render( < TodoApp / > ,
  document.getElementById('todoapp')
);
```
how to disable it

**Comment by batjko** [comment]
Can you try and run atom in safe mode (`atom --safe`) and see if this still happens?

I think you have a package installed that does this upon saving, for example atom-beautify or some such thing.
