### ISSUE TITLE
Python version error on Arch despite exporting python=/usr/bin/python2

### ISSUE THREAD

**Issue by cathalgarvey** [atom/atom#7484]
Hi all, I'm failing to build atom v1.0.0 when I [follow the instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md) for Arch. Whether I do:

    export python=/usr/bin/python2
    script/build

..or:

    python=/usr/bin/python2 script/build

..the result is the same:

    Node: v0.12.5
    npm: v2.11.3
    Installing build modules...
    Installing apm...
    gyp ERR! configure error 
    gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
    gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
    gyp ERR! stack     at failPythonVersion (/home/cathal/locallib/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
    gyp ERR! stack     at /home/cathal/locallib/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at maybeClose (child_process.js:1015:16)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    gyp ERR! System Linux 4.0.6-1-ARCH
    gyp ERR! command "node" "/home/cathal/locallib/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/cathal/locallib/atom/apm/node_modules/atom-package-manager/node_modules/keytar
    gyp ERR! node -v v0.12.5
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    gyp ERR! configure error 
    gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
    gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
    gyp ERR! stack     at failPythonVersion (/home/cathal/locallib/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
    gyp ERR! stack     at /home/cathal/locallib/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at maybeClose (child_process.js:1015:16)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
    gyp ERR! System Linux 4.0.6-1-ARCH
    gyp ERR! command "node" "/home/cathal/locallib/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/cathal/locallib/atom/apm/node_modules/atom-package-manager/node_modules/git-utils
    gyp ERR! node -v v0.12.5
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    gyp ERR! configure error 
    gyp ERR! stack Error: Python executable "python" is v3.4.3, which is not supported by gyp.
    gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
    gyp ERR! stack     at failPythonVersion (/home/cathal/locallib/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
    gyp ERR! stack     at /home/cathal/locallib/atom/build/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:742:7)
    gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
    gyp ERR! stack     at maybeClose (child_process.js:1015:16)
    gyp ERR! stack     at Socket.<anonymous> (child_process.js:1183:11)
    gyp ERR! stack     at Socket.emit (events.js:107:17)
    gyp ERR! stack     at Pipe.close (net.js:485:12)
    gyp ERR! System Linux 4.0.6-1-ARCH
    gyp ERR! command "node" "/home/cathal/locallib/atom/build/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/cathal/locallib/atom/apm/node_modules/atom-package-manager/node_modules/first-mate/node_modules/oniguruma
    gyp ERR! node -v v0.12.5
    gyp ERR! node-gyp -v v1.0.2
    gyp ERR! not ok 
    npm ERR! Linux 4.0.6-1-ARCH
    npm ERR! argv "node" "/home/cathal/locallib/atom/build/node_modules/.bin/npm" "--userconfig=/home/cathal/locallib/atom/build/.npmrc" "--target=0.10.35" "install" "--loglevel" "error"
    npm ERR! node v0.12.5
    npm ERR! npm  v2.5.1
    npm ERR! code ELIFECYCLE

    npm ERR! keytar@2.1.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the keytar@2.1.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the keytar package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls keytar
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/cathal/locallib/atom/apm/npm-debug.log

**Comment by cathalgarvey** [comment]
Changing `/usr/bin/python` to point to a legacy version like 2.7 fixes build, but if the `$python` environment var is supposed to be all that's needed here then the issue is some code directly shelling to `python` by accident.

**Comment by thomasjo** [comment]
The environment variable needs to be uppercase; try `export PYTHON=/usr/bin/python2`.

**Comment by cathalgarvey** [comment]
Ah, derp. Thanks for pointing out that obvious error. :)
