### ISSUE TITLE
How can I execute custom javascript code in a find/replace task?

### ISSUE THREAD

**Issue by Billybobbonnet** [atom/atom#7486]
Hello,

My issue is quite simple, but I don't know if atom provides a way to achieve what I want.

I have a list of countries in  ISO 3166-1 alpha-2 format. here is how it looks:
```json
{
  "name": "Afghanistan",
  "code": "AF",
  "country-code": "004"
}, {
  "name": "Åland Islands",
  "code": "AX",
  "country-code": "248"
}, {
  "name": "Albania",
  "code": "AL",
  "country-code": "008"
},
```

I want to change all the codes to their lowercase equivalent. I can select them using a simple regex find string `"[A-Z]{2}"` 

Is there any way to apply a `matchingString.toLowerCase()` on every string matched by my regex? Maybe something like `this.toLowerCase();`

Thanks!

**Comment by batjko** [comment]
I don't think so.
But if you could move your issue over to the [Find-And-Replace](https://github.com/atom/find-and-replace/issues) package, as an enhancement request, the core team might consider working on a feature like this.

**Comment by Billybobbonnet** [comment]
posted in find-and-replace package's repo. Thanks for your feedback.

**Comment by jpillora** [comment]
For those wanting to track this issue, it's here https://github.com/atom/find-and-replace/issues/417
