### ISSUE TITLE
Atom does not behave like a Windows application

### ISSUE THREAD

**Issue by metrip** [atom/atom#7487]
Atom feels like a very alien program when running on Windows. Its behaviour does not match users' expectations.

Installation problems:
- Not present in Start menu at all (can't press start, type "atom" to run)
- Shortcut installed only on user's desktop (no option given to not clutter the desktop)
- No proper way to launch if the desktop shortcut pointing to `atom\update.exe --processStart atom.exe` is removed
- No proper way to find the application for Explorer's Open with... functionality
  - navigation to %LOCALAPPDATA%/Atom difficult to figure out and perform
  - impossible to know what to select once there -> Can't be set as a default text editor
  - related: #7205 

Behaviour:
- Pinning to taskbar does not work like Windows applications work
  - a new icon is produced when Atom is launched from taskbar (related: #7374)
  - update check probably not run in this case either?
- Does not use OS mouse wheel scroll configuration (lines scrolled per wheel turn)

Windows 10 Pro x64 insider preview build 10130

**Comment by paulcbetts** [comment]
> Not present in Start menu at all (can't press start, type "atom" to run)

This sounds like there was a bug, it should definitely be in the start menu.

> Pinning to taskbar does not work like Windows applications work

This is a Win10-only bug. We'll fix it if it's still there on RTM

**Comment by metrip** [comment]
Curiously, the Start menu shortcut seems to be in its correct place, `%APPDATA%\Microsoft\Windows\Start Menu\Programs\GitHub, Inc`, but the folder or the Atom shortcut do not show in the start menu. Something Windows 10 specific maybe?

**Comment by gemal** [comment]
I'm on Windows 7 and I don't see any start menu items either

**Comment by paulcbetts** [comment]
@kevinsawicki Can we get Atom up to the current version of Squirrel so that we can verify if these are current bugs? Atom is way behind where Squirrel is now

**Comment by kevinsawicki** [comment]
> Can we get Atom up to the current version of Squirrel so that we can verify if these are current bugs?

Yeah, sounds good.

**Comment by johnsonz** [comment]
I also met this problem. I can't find any shortcut on desk and start menu after first installed. So I uninstalled it from Control Panel. Curiously, I re-installed it. It works. It's showed under GitHub folder.
win 7 professional 64 bit

**Comment by jonegerton** [comment]
@paulcbetts: re pinning: There are also issues with pinning in windows 8.1. I've described it in a comment on the linked issue.

**Comment by adelarsq** [comment]
On Windows 7 the update.exe file (```C:\Users\PC11\AppData\Local\atom\update.exe```) is being removed sometime after the install. Still occurs on last version.

**Comment by judgej** [comment]
Windows 7 (32bit unfortunately), Atom 1.0.2 - same issue for me. No launch icons anywhere. Only saw the editor once, when first installing, and that locked up after ten minutes and have not been able to find out how to get back into it since. Have not tried reinstalling yet, as that eats up 2Gbytes of memory and locks up my PC for half an hour.

**Comment by Stanzilla** [comment]
You can set Atom as default for certain file types on Windows, you just have to do it manually, pointing it to the exe. Something that should be changed is that Atom is not included in the suggestions of programs to open this file type with when you click them. I guess Atom just does not register itself for them?

**Comment by stanly-johnson** [comment]
I am using Windows 8 and atom appears in start menu just like all other applications. Although you have to manually set it as the default text editor.

**Comment by Stanzilla** [comment]
I meant the "Open with.." menu, which shows all installed applications that registered to be able to handle this filetype.

**Comment by kapsiR** [comment]
@Stanzilla: Yes, you can do that, but Atom changes the directory every update and you have to manually change the path to the atom.exe again... so that's really bad for user experience, see #7205

**Comment by Stanzilla** [comment]
I am aware that you can do that, my original point still stands though that Atom does not register itself for the file types..

**Comment by paulcbetts** [comment]
Gonna close this out, please file bugs for these issues individually

**Comment by littlebirdcodes** [comment]
This is the shortcut I found! C:\Users\(Administrator Account)\AppData\Local\atom\app-1.13.0\atom.exe
I hope it helps!

**Comment by Scuodde** [comment]
The application is inside "local" folder of app_data and app_data is hidden, so you have unhide this folder first.

**Comment by nazmul202101** [comment]
Same here.

**Comment by Derick8** [comment]
atom just vanished

**Comment by ChildishGiant** [comment]
I can't set defaults to Atom since it doesn't show up in the list of apps to set defaults for.
![image](https://user-images.githubusercontent.com/13716824/30078313-bf6bac06-9274-11e7-8a8b-f2e28377750f.png)

**Comment by ChildishGiant** [comment]
I had to tick "Register as file handler". All three were unticked
![image](https://user-images.githubusercontent.com/13716824/30078603-a86a3382-9275-11e7-9006-7553ea28fea1.png)
