### ISSUE TITLE
Can't enter a " ] " --- Alt Gr + " ) " shortcut

### ISSUE THREAD

**Issue by n457** [atom/atom#7490]
**Atom 1.0.0, Windows 8.1 64bit**

Hello,
I can't enter a **]** in any file (**Alt Gr + )** ), it results in a code "compression", like this :
![image](https://cloud.githubusercontent.com/assets/11824581/8393057/c3cd2efc-1cfe-11e5-9c01-cac7d4a0b20a.png)
This is probably because of a shortcut (I didn't change shortcuts).
AZERTY / QWERTY mode doesn't affect the problem.

**Comment by batjko** [comment]
Foreign keyboard layouts, especially keys like `Alt-Gr` are not fully supported yet.
Please follow this open issue for updates: https://github.com/atom/atom-keymap/issues/35
