### ISSUE TITLE
Slow regexp

### ISSUE THREAD

**Issue by sergeyklay** [atom/atom#7491]
File for test: https://github.com/stibiumz/incubator/blob/24d8b32ecfb6596b9e6862b3a62d2697e5c53228/tests/Phalcon/Mvc/Model/EagerLoading/resources/Models/Robot.php

Result: 
![selection_027](https://cloud.githubusercontent.com/assets/1256298/8393146/90b12f9e-1d0a-11e5-8f62-ebec003ad282.png)

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/find-and-replace?

**Comment by sergeyklay** [comment]
I'm sorry
