### ISSUE TITLE
I can't set the editor's default encoding format

### ISSUE THREAD

**Issue by MaskClown** [atom/atom#7492]
Atom is very good, but with sublime does have a fatal problem: coding issues. I can't to save file by default for Unix/utf-8, even if is to set the default utf-8 format, but with other editor such as notepad + + is open you will find that the coding format DOS/ANSI!!!!!!!!!!!

**Comment by batjko** [comment]
Sorry, could you clarfy, which encoding format you want to use, the DOS/ANSI one or utf8?

You know you can change the encoding in the Settings, right:
![image](https://cloud.githubusercontent.com/assets/7287076/8393236/1d034b1e-1cff-11e5-9ff4-69a772968882.png)

**Comment by MaskClown** [comment]
I want  to use utf8. But the editor is not saved in a format real utf8.

**Comment by MaskClown** [comment]
I want  to use utf8. But the editor is not saved in a format real utf8.

**Comment by MaskClown** [comment]
I want to use utf8. But the editor is not saved in a format real utf8.

**Comment by mnquintana** [comment]
You can search the Command Palette for Encoding Selector:

![screenshot 2015-06-27 22 17 15](https://cloud.githubusercontent.com/assets/823545/8394879/5864a340-1d1a-11e5-84a1-ed0405770453.png)

**Comment by mnquintana** [comment]
@MaskClown What you're describing is covered by the setting @batjko recommended. Just change that setting to change the default encoding.

**Comment by MaskClown** [comment]
@mnquintana Is my expression problem or you don't understand? I have clear said it didn't work

**Comment by MaskClown** [comment]
I want to know why the default utf8 format file is not utf8 format
![1st](https://cloud.githubusercontent.com/assets/13079200/8435768/c5f70f84-1f85-11e5-89d3-8e16e826e2f4.png)
![2nd](https://cloud.githubusercontent.com/assets/13079200/8435829/5bf832a6-1f86-11e5-84ed-45118343ee58.png)

**Comment by batjko** [comment]
@MaskClown I'm not sure what you mean.
The encoding you set in Atom is used only by Atom. It does not affect other programs.

**Comment by MaskClown** [comment]
......
Can you create a new file by Atom, then open it in another editor and view the encoding?

**Comment by batjko** [comment]
Of course you can. You should be able to confirm that the encoding of the Atom-created file is what you set it to.

**Comment by lee-dohm** [comment]
Some things to know about text file encodings ...

1. If you create an empty text file, there is no way to detect what text encoding it is using (not even UTF-16 because usage of the BOM is not required)
1. If you create a UTF-8 text file and only store "abcd" in it, there is no way to detect whether that is a UTF-8 file or any one of a bazillion ANSI code pages because from ASCII 0 through ASCII 127, they look identical

So depending on what the text is that you put in the file, it could very well be UTF-8 encoded ... but Notepad++ may *assume* that it is [CP-1252](https://en.wikipedia.org/wiki/Windows-1252) and display what you're seeing.

**Comment by lee-dohm** [comment]
An excellent article on the subject: [The Absolute Minimum Every Software Developer Absolutely, Positively Must Know About Unicode and Character Sets](http://www.joelonsoftware.com/articles/Unicode.html)

**Comment by batjko** [comment]
You had me at "the absolute minimum".

**Comment by MaskClown** [comment]
@lee-dohm  @batjko  @mnquintana  Thanks
