### ISSUE TITLE
Freeze when changing file encoding

### ISSUE THREAD

**Issue by ertanden** [atom/atom#7493]
I opened a subtitle file with Turkish (Windows 1254) encoding in Atom, and it opened it as UTF-8 by default.

Then I tried changing the encoding to Turkish (Windows 1254), but the editor froze and even displayed a dialog saying that it's not responding. I pressed on "Keep waiting" and after a while the file was re-loaded with my selected encoding.

It's very very slow... not even usable. 

Atom 1.0.0
Machine: Intel i7 4790K with 16GB RAM.
OS: Mac OS X 10.10.3

Sample file to reproduce:
http://www.filedropper.com/dannycollins2015720pweb-dldd51h264-playnow

**Comment by ertanden** [comment]
Re-sharing file to reproduce:
http://www.mediafire.com/download/323t81budnnk873/Danny.Collins.2015.720p.WEB-DL.DD5.1.H.264-PLAYNOW.srt

**Comment by Fank** [comment]
I can reproduce this issue on ubuntu 15.04 with atom 1.0.0 .
Here the profile while its changing the encoding:
![screenshot from 2015-07-02 16 10 29](https://cloud.githubusercontent.com/assets/1900106/8478950/e1486e7c-20d4-11e5-9931-ea0b4685086f.png)

**Comment by alexchandel** [comment]
Confirmed on Atom 1.7.3, OSX 10.11.4 and Windows 10 x64. Reproduction steps:

1. Ensure Atom opens files as UTF-8 by default.
2. Open a 2-line, 500kB XML file that is encoded UTF-16 LE and that is at least 40% Chinese characters.
3. With much lag, Atom opens it as UTF-8.
4. Change Encoding to UTF-16 LE.
5. Atom hangs forever -> `Editor is not responding`
