### ISSUE TITLE
Trying to install Atom Editor

### ISSUE THREAD

**Issue by StefanoBelli** [atom/atom#7495]
Hello boys (and girls)
I am trying to install the awesome Atom editor on my Arch Linux system but something is going wrong. 
I am trying to execute atom/script/build to build the dependencies and modules using this command:

--> ./script/build 
Node: v0.12.4
npm: v2.5.1
Installing build modules...
Installing apm...
/home/stefanozzz123/.sources/atom/apm/node_modules/atom-package-manager/bin/apm: line 28: /home/stefanozzz123/.sources/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory

I checked everything as the Build markdown file says. Thanks :)

**Comment by zaz** [comment]
I'm having the same issue. I followed the [build instructions][0] exactly, except for checking out `v1.0.0` instead of the latest version:

    git fetch
    git checkout v2.0.0
    sudo pacman -S --asdeps gconf base-devel git nodejs libgnome-keyring python2
    export PYTHON=/usr/bin/python2 
    script/build

Here's the output:

    $ script/build                                    
    Node: v0.12.5
    npm: v2.5.1
    Installing build modules...
    Installing apm...
    /home/zaz/Code/zzzGeneric/atom/apm/node_modules/atom-package-manager/bin/apm: line 28: /home/zaz/Code/zzzGeneric/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory

`apm/node_modules/atom-package-manager/bin/node` does not exist.

I'm running Arch Linux, node `v0.12.5`.

  [0]: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

**Comment by nkoster** [comment]
For me, this worked: [script/clean](https://github.com/atom/atom/issues/3918)
```
0007 niels@niels-GT60:~/src/atom$ script/clean 
0007 niels@niels-GT60:~/src/atom$ script/build
Node: v0.10.25
npm: v2.13.0
Installing build modules...
Installing apm...
Installing modules ✓
Installing atom-dark-syntax@0.27.0 ✓
Installing atom-dark-ui@0.49.0 ✓
Installing atom-light-syntax@0.28.0 ✓
...
```

**Comment by zaz** [comment]
Thanks! That works for me as well:

	$ script/clean
	$ script/build
	Node: v0.12.5
	npm: v2.12.0
	Installing build modules...
	Installing apm...
	child_process: customFds option is deprecated, use stdio instead.
	child_process: customFds option is deprecated, use stdio instead.
	child_process: customFds option is deprecated, use stdio instead.
	Installing modules ✓
	Installing atom-dark-syntax@0.27.0 ✓
	Installing atom-dark-ui@0.49.0 ✓
	Installing atom-light-syntax@0.28.0 ✓
	...
	Deduping modules ✓
	Running "download-atom-shell" task
	Running "download-atom-shell-chromedriver" task
	Running "build" task
	Running "coffee:glob_to_multiple" (coffee) task
	>> 334 files created.
	Running "prebuild-less:src" (prebuild-less) task
	Running "cson:glob_to_multiple" (cson) task
	>> 170 files compiled to JSON.
	Running "peg:glob_to_multiple" (peg) task
	Running "generate-license:save" (generate-license) task
	Running "generate-module-cache" task
	Running "compile-packages-slug" task
	Running "set-version" task
	Running "generate-asar" task
	Done, without errors.

*(empty lines trimmed, cut out full list of packages installed)*

**Comment by Lucbug** [comment]
Hi, I'm having the same issue on Debian 8.2.

Except when I do `script/clean`. After that, `script/build` just hangs on `Installing build modules...`

Any thoughts ?

**Comment by eklavyaa** [comment]
Hello Guys,
I am trying to build the atom app refering the instructions given here,but as I run

sudo script/build --install-dir /Users/gautamsingh/Documents/builds_new/atom/atom.app --verbose

I get following error:-

Node: v5.3.0
npm: v2.13.3
Installing build modules...
Installing apm...
/Users/gautamsingh/repo/atom/atom/apm/node_modules/atom-package-manager/bin/apm: line 28: /Users/gautamsingh/repo/atom/atom/apm/node_modules/atom-package-manager/bin/node: No such file or directory

I have tried symlink the output of "Which node" like this:-

sudo ln -s /usr/local/bin/node /usr/bin/node

but didn't help

PS: using OSX 10.11.1 El Capitan
