### ISSUE TITLE
allow to choose syntax without having to save file

### ISSUE THREAD

**Issue by vach** [atom/atom#7497]
With sublime i could create a new tab put some code and choose the syntax i wanted for that particular tab, with atom currently it is activating only when i save the file, and figures out correct syntax with file extension...

**Comment by mnquintana** [comment]
You can do this with Atom - search for Grammar Selector in the Command Palette:

![screenshot 2015-06-27 21 54 15](https://cloud.githubusercontent.com/assets/823545/8395067/5fee3002-1d26-11e5-8db9-dd34222e3a61.png)
