### ISSUE TITLE
Atom 1.0 does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by photino** [atom/atom#7500]
I am trying to install Atom 1.0 on my Ubuntu 14.04 using [atom-amd64.deb](https://github.com/atom/atom/releases/download/v1.0.0/atom-amd64.deb) or `sudo add-apt-repository ppa:webupd8team/atom`. However, an error happened when I start atom (see the snapshot) and it cannot open any files.

![error](https://cloud.githubusercontent.com/assets/3446306/8395182/9e06233c-1d93-11e5-97e7-b310ce0b31a1.png)

Then I removed this package with `apm remove recent-files`, but the editor still cannot work.

My Node.js environment is:
```shell
$ node -v
v0.12.5
$ npm -v
2.11.2
```

**Comment by mark-hahn** [comment]
Did you get the deb package from the home page, atom.io?  I run ubuntu
14.04 and install that one and I've never had a problem.

I don't think any ppa is officially supported.

**Comment by photino** [comment]
@mark-hahn I get the atom-amd64.deb from the GitHub releases. After I removed all the files in `~/.atom`, the problem is solved. It works!

**Comment by mnquintana** [comment]
It looks like it was at least one of your installed packages throwing this error. Glad you fixed it! :+1:
