### ISSUE TITLE
instructions how to make sysctl permissions permenent in linux build manual wrong

### ISSUE THREAD

**Issue by korc** [atom/atom#7501]
Document in question: [docs/build-instructions/linux.md](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md)

Currently:   `echo 32768 | sudo tee -a /proc/sys/fs/inotify/max_user_watches`

I fail to see how writing to /proc would make settings any more permanent than just sysctl'ing them.

I believe it is meant to be:
`echo fs.inotify.max_user_watches=32768 | sudo tee -a /etc/sysctl.d/local.conf`

**Comment by mehcode** [comment]
https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
