### ISSUE TITLE
Deb install error on 64-bit Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by davesgonechina** [atom/atom#7505]
> cannot copy extracted data for './usr/share/doc/atom/copyright' to '/usr/share/doc/atom/copyright.dpkg-new': unexpected end of file or stream

Downloaded a couple of times from github/atom.io but doesn't seem to be a corrupt file.

sudo apt-get clean didn't help.

UPDATE: Successfully installed using webupd8team PPA. Deb issue unresolved.

**Comment by arturlicks** [comment]
Just installed correctly from the deb package in a 14.4.5 fresh installed.

**Comment by Ben3eeE** [comment]
Thanks @arturlicks 

@davesgonechina If you still have problems installing on Ubuntu 14.04 please open a new issue and fill out the issue template.
