### ISSUE TITLE
Crashes with Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by patrickhofer** [atom/atom#7506]
![selection_002](https://cloud.githubusercontent.com/assets/11354982/8396205/d611ed02-1d9c-11e5-98f5-50b72147d70f.png)

**Comment by spongecattle** [comment]
So it dosen't work with Ubuntu 14.04 LTS? I have that OS and It works fine!

**Comment by patrickhofer** [comment]
Well it worked well for a day or so, but now it's impossible to open atom at all.

**Comment by mnquintana** [comment]
Have you tried following the steps in the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging)? Can you reproduce this in safe mode? (`atom --safe`)

**Comment by spongecattle** [comment]
Huh this might help if it won't work on my computer in the future

**Comment by spongecattle** [comment]
thx mnquintana

**Comment by patrickhofer** [comment]
![ubuntu_004](https://cloud.githubusercontent.com/assets/11354982/8397292/29309608-1dc7-11e5-9441-820006391a23.png) 

Thanks mnquintana

**Comment by patrickhofer** [comment]
Does somebody know why it  crashes? Should i post more information?

**Comment by mnquintana** [comment]
Was that crash in safe mode?

**Comment by patrickhofer** [comment]
@mnquintana yes this was the safe mode crash.

**Comment by izuzak** [comment]
@zcbenz What other information would be helpful to investigate this crash?

**Comment by kemal-atila** [comment]
Atom crash on Ubuntu every time, also too many ram usage.
