### ISSUE TITLE
Hide search pane

### ISSUE THREAD

**Issue by BramVanroy** [atom/atom#7507]
I've searched the ten first pages of issues with the term "search" but couldn't find this issue.

I can toggle search by pressing CTRL+F, as it should. However, I can't find any way to close that pane. Maybe an <kbd>x</kbd> would be nice or at least a notion of the search pane in `View`?

It doesn't seem like a good idea to be able to toggle it with CTRL+F. That one should only be used for opening the search box. That way you can't accidentally close the search box when it's already open.

**Comment by mnquintana** [comment]
![screenshot_2015-06-28_08_30_43](https://cloud.githubusercontent.com/assets/823545/8396373/28378bfa-1d70-11e5-8705-18ce0b1bc777.png)

Hope that helps!

**Comment by BramVanroy** [comment]
Strange, I don't remember getting that notification. It does seem to me that this is a bad idea. The <kbd>ESC</kbd> seems like such a global key that it shouldn't be used for closing a pane inside the programme. But I now realise that that there's a find-and-replace package, so I'll file an issue/feature request there. Thanks for the pointer!
