### ISSUE TITLE
OSX: `atom` shell command always moves one desktop to the left

### ISSUE THREAD

**Issue by aleclarson** [atom/atom#7510]
``` sh
atom ~/.bashrc
```

Instead of focusing on the Atom editor (as expected), it always focuses on the desktop to the left of the selected desktop (even if Atom isn't on that desktop).

Has anyone else experienced this? It's quite annoying having to four-finger-swipe to the desktop Atom is on every time I open a file thru the terminal.

**EDIT:** If the file is not yet open, the Atom editor **will** be focused. But if it's already open, I'm moved a desktop to the left and then nothing happens.

**EDIT 2:** I'm on OSX 10.10.2

**Comment by csvoss** [comment]
I am also experiencing this.
