### ISSUE TITLE
Incorrect Arch Linux installation instructions

### ISSUE THREAD

**Issue by fusion809** [atom/atom#7511]
Hi, 

I know I could go about this with a pull request but it's only a single word addition to the Linux.md file so I felt a developer with write permissions to the GitHub repo could just read this and make the change. At the moment the Linux.md file reads this in its Arch Linux dependency installation instructions:

> * `sudo pacman -S gconf base-devel git nodejs libgnome-keyring python2`
> * `export PYTHON=/usr/bin/python2` before building Atom.

The amendment I propose is to add `npm` after `nodejs` in the first of these lines, in accordance with the [official Nodejs Wiki installation instructions](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#arch-linux). I have tested this on a 32 bit Manjaro Linux Virtual Machine (which is as close to Arch that I can effectively work with-- Arch is over my head): without `npm` in this line, later during the actual build `script/build` generated errors stating that it could not find npm. 

I hope this helps,
Brenton

**Comment by Narrat** [comment]
As this particular problem got fixed with #8101, shouldn't this be closed?

**Comment by 50Wliu** [comment]
Thanks @Narrat :).
