### ISSUE TITLE
Could not resolve 'jshint' to a package path: Atom 1.0.0

### ISSUE THREAD

**Issue by trevithj** [atom/atom#7518]
#### Steps:

This is running in safe mode, with developer console open.
1. Settings > Install, search for 'linter'
2. click Themes, then click Packages (needed to actually show search results ??)
3. Find jshint (1.3.8) and click Install.

After a pause, console shows:

```
C:\Users\[me]\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:377
Could not resolve 'jshint' to a package path
```

Ditto with `atom-jshint` (2.0.0), `wl-jshinter` (0.3.3), `optional-jshint` (3.0.0).
#### OS: Windows 7

Issue search found https://github.com/atom/atom/issues/4721 but this seems to relate to an earlier version of Atom. Didn't find anything related to 1.0.
(Correction - possibly related to https://github.com/atom/atom/issues/7335)

**Comment by benogle** [comment]
cc @maxbrunsfeld as it seems like you dealt with this over at #4721

**Comment by trevithj** [comment]
Note: for those who need to get linting up and running, see: https://atom.io/packages/linter
I now have *linter-jshint* and *linter-php* working, no errors.

**Comment by maxbrunsfeld** [comment]
@trevithj can you share your list of installed packages (`apm list --installed`) and the contents of your `config.cson`?

**Comment by trevithj** [comment]
Hi Max. As of now the requested info is:
>apm list --installed

�u�w�w linter@1.1.0
�u�w�w linter-jshint@0.1.7
�|�w�w linter-php@0.0.15

config.cson:
"*":
  "exception-reporting":
    userId: "a2a50d50-c51f-30fb-e415-cc7fd751e310"
  welcome:
    showOnStartup: false
  core:
    themes: [
      "atom-light-ui"
      "base16-tomorrow-dark-theme"
    ]
    disabledPackages: [
      "language-c"
      "language-csharp"
      "language-go"
      "language-make"
      "language-objective-c"
      "language-perl"
      "language-python"
      "language-ruby"
      "language-ruby-on-rails"
      "language-toml"
      "atom-jshint"
    ]
  editor:
    invisibles: {}
    tabLength: 4
    fontSize: 13
    softTabs: false
    showInvisibles: true
    softWrapAtPreferredLineLength: true
  "atom-jshint": {}
  linter: {}

________________________________________
