### ISSUE TITLE
Does not follow file after an "atomic save" by other text editors

### ISSUE THREAD

**Issue by forivall** [atom/atom#7519]
For a given file open in atom, after an "atomic save" is perfomed by a different application, atom will no longer have the "real" file open, instead it will have the old version of the file left open. When the tab is closed, the message will read 

> 'README.md~' has changes, do you want to save them? Your changes will be lost if you close this item without saving

And then the user has to go back to their tree view and re-open the original file.

For reference, an atomic save is one where, instead of simply rewriting the contents of a file, the original file is moved (like `README.md` -> `README.md~`), and then a new file is written in the original location. Applications such as vim, gedit and qtcreator do this when saving files. In my case, with qtcreator, there is no option to turn this behaviour off. It's even [considered a bug to some Sublime Text users](https://github.com/SublimeTextIssues/Core/issues/379).

Currently on Windows, Atom 1.0.0. Occurs in safe mode.

This bug can probably be addressed in `node-pathwatcher`.

**Comment by forivall** [comment]
The code that qt creator uses to perform this operation is at http://code.qt.io/cgit/qt-creator/qt-creator.git/tree/src/libs/utils/savefile.cpp?h=v3.4.1#n95

**Comment by CodingAnarchy** [comment]
I've noticed this same behavior on Linux (Fedora 22), where the file must be closed without saving and then reopened from the tree view.  By contrast, at work where I'm stuck with basic and old tools like nedit or gedit, I get a popup warning me that the file has changed on disk and asking if I want to refresh from disk or not.

This is particularly useful when looking at running logs in some debug cases, but it helps to be aware even if it was just as simple as having the file open in two different windows.
