### ISSUE TITLE
On some folder, Cmd+T always tells me "Project is empty"

### ISSUE THREAD

**Issue by vincentisambart** [atom/atom#7520]
As you can see on the screenshot below:
![screen shot 2015-06-29 at 08 07 54](https://cloud.githubusercontent.com/assets/34704/8398733/0b060ac2-1e36-11e5-95a5-ef1c396f1a06.png)

Atom was started with `atom --safe <directoryname>`.
OS X 10.10.3, Atom 1.0.
Other folders work well.

**Comment by mnquintana** [comment]
Would you mind closing this and reopening on https://github.com/atom/fuzzy-finder?

**Comment by vincentisambart** [comment]
Sure
