### ISSUE TITLE
urls comment out lines improperly in CSS

### ISSUE THREAD

**Issue by hawsome** [atom/atom#7524]
![Imgur](http://i.imgur.com/06w5XtT.png) 
:cry: everything after `//www ...` in the url is commented out

**Comment by mnquintana** [comment]
Would you mind closing this and reopening on https://github.com/atom/language-css?

**Comment by izuzak** [comment]
I don't think it's commented out -- it's just colored with that color. As @mnquintana said -- please open an issue on https://github.com/atom/language-css and provide [more details](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) and also clarify which themes you're using.
