### ISSUE TITLE
Cannot drag inactive tabs without focusing them first.

### ISSUE THREAD

**Issue by matthewmorek** [atom/atom#7527]
You have to make a tab/pane active first, before you are able to click-drag it, to reorder, or move across to another pane.

#### Steps to reproduce:
1. Open up a file in Atom.
2. Split the panes in whichever way you want.
3. Click on either pane/tab to make it active/bring it to focus.
4. Try click-dragging the other file into the opposite pane.

**Comment by mnquintana** [comment]
Would you mind moving this to [atom/tabs](https://github.com/atom/tabs)?

**Comment by matthewmorek** [comment]
Done. Moved to: [atom/tabs/issues/190](https://github.com/atom/tabs/issues/190).
