### ISSUE TITLE
Malformed urls in package search

### ISSUE THREAD

**Issue by Krinkle** [atom/atom#7531]
* Avatar broken.
* Username is missing first character.
* User link points to 404 Not Found: https://atom.io/users/
* Clicking "Report issues" triggers a dialog about invalid URL with `%@`.

![screen shot](https://cloud.githubusercontent.com/assets/156867/8402616/90a6edf6-1e34-11e5-817b-b6c9658405c3.png)

**Comment by thomasjo** [comment]
Are you able to reproduce this in safe mode? `atom --safe`
In addition, what version of OS X are you using?

**Comment by izuzak** [comment]
Sounds like a duplicate of https://github.com/atom/settings-view/issues/543
