### ISSUE TITLE
Possible to accept commands/key bindings without Atom window?

### ISSUE THREAD

**Issue by adamreisnz** [atom/atom#7532]
For example when using the [Atom project manager](https://github.com/danielbrodin/atom-project-manager), it's very inconvenient that when you've closed all your windows and want to open a new project, you have to open a new Atom window first before the command to open a new project can be used.

Seeing how this command is more of a "global" command, and shouldn't really need a window, is it possible for Atom to somehow accept such commands without window (but with the app itself having focus) and just open a new window as needed?

The work around now is to either remember not to close your last project window, open a new project, and then switch back to close the last one, or close all of them, open a new window, and then open a new project. Since opening a new window takes quite a bit of time to load, it's a bit of a hassle whichever way you do it, and it would be much more optimal if you could just open an existing project, and for that command to open the new window for you.

**Comment by aaronwolen** [comment]
:+1:  This trips me up every day.

**Comment by adamreisnz** [comment]
Still an issue
