### ISSUE TITLE
Altgr (ctrl-alt) doesn’t work correctly on Linux

### ISSUE THREAD

**Issue by phaazon** [atom/atom#7535]
I’m using a [bépo](http://bepo.fr/wiki/Accueil) keyboard layout. On Windows, when hitting *AltGr*, I get it translated to `ctrl-alt`. On Linux, I get it translated to… `á`, which is very weird and wrong.

**Comment by mnquintana** [comment]
This is a duplicate of https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37 – please subscribe there for updates.

**Comment by phaazon** [comment]
Thanks.
