### ISSUE TITLE
help

### ISSUE THREAD

**Issue by fuckdagamz** [atom/atom#7537]
,,,,,,

0

@ ok

M??ll Iloilog 
 Polo ttseahe your t

Can someone please explain to me what this means

**Comment by batjko** [comment]
Can you add some more information, as to where this comes from and whether or not this relates to an issue with Atom?

**Comment by fuckdagamz** [comment]
I have no idea what an atom is even about to be honest, but it was from a spoofed number and came back to back in like 4 text

**Comment by mark-hahn** [comment]
> I have no idea what an atom is even about to be honest
