### ISSUE TITLE
charset error  , can't see correct chinese in atom

### ISSUE THREAD

**Issue by airclear** [atom/atom#7544]
I use ubuntu 14.04, atom version 1.0

file charset is utf-8  .

when i open the file with atom,  I just don't show correct ..  

try type this word:
```
我爱中国
```

**Comment by batjko** [comment]
Seems to work fine if I copy/paste your String into a new window:
![image](https://cloud.githubusercontent.com/assets/7287076/8407402/276e5b92-1e5e-11e5-9a12-c9700d5fc460.png)

However, I haven't tried it on Linux yet.

**Comment by izuzak** [comment]
@airclear Can you share a screenshot of what you see?

**Comment by airclear** [comment]
@izuzak 

![deepinscrot-0126](https://cloud.githubusercontent.com/assets/4103690/8449218/1ac1b0ce-2002-11e5-96bd-970c53bcc908.png)

**Comment by izuzak** [comment]
Thanks, @airclear -- that sounds very similar to https://github.com/atom/atom/issues/6214, so I'm closing this in favor of that issue. Let me know if I misunderstood, though.
