### ISSUE TITLE
Ctrl+<arrow> move of line should update its indentation

### ISSUE THREAD

**Issue by NDavidBrown** [atom/atom#7546]
Being able to move a line with Ctrl+arrow is very useful.

I suggest this feature be improved so the line matches the indentation in its new scope, e.g. being "unindented" if moving out of a FOR loop.

**Comment by batjko** [comment]
:+1: Makes total sense to me.

**Comment by eddiemonge** [comment]
merged in https://github.com/atom/atom/pull/9104 but perhaps not the best solution

**Comment by 50Wliu** [comment]
Ok, I'm going to close this then.  If the above PR is reverted then I'll re-open this.
