### ISSUE TITLE
Problems overriding alt-up + alt-down in keymap.cson

### ISSUE THREAD

**Issue by arahlf** [atom/atom#7552]
I'm trying to override alt-up + alt-down to move a line up/down.  Using the Settings helper, I copied the bindings as a template and then added the following to my keymap.cson file:

    'atom-workspace atom-text-editor':
      'alt-up': 'editor:move-line-up'

    'atom-workspace atom-text-editor':
      'alt-down': 'editor:move-line-down'

I can now use alt-down to move a line down, but the binding for alt-up isn't getting picked up.  If I swap the order of them, so that the line-down block is before the line-up block, then line-up works but line-down does not.

Any ideas on what I'm doing wrong?

**Comment by mnquintana** [comment]
See https://github.com/atom/atom/issues/7302#issuecomment-112564548

> Atom's config files (including keymap.cson) are a simple key-value format just like JSON (but CSON), which means that keys must always be unique. If you repeat keys, then only one of those values will actually be registered.

In your example above, you repeat the `'atom-workspace atom-text-editor'` key, so only one of them is registered. It should be:

```cson
'atom-workspace atom-text-editor':
  'alt-up': 'editor:move-line-up'
  'alt-down': 'editor:move-line-down'
```

**Comment by arahlf** [comment]
Ahh ok that makes sense now, thanks!

Might be worth specifically calling that out or something in the comments of that file at some or providing a validation warning/error, because the phrase:

> Just as style sheets use selectors to apply styles to elements, Atom keymaps use selectors to associate keystrokes with events in specific contexts.

kinda makes it sound like you can repeat selectors (at least to someone just getting started).
