### ISSUE TITLE
Unable to remap "cmd+d" keys

### ISSUE THREAD

**Issue by EvHaus** [atom/atom#7554]
Mac OS, Atom 1.0

I'd like "cmd+d" to duplicate the currently line. This is more natural to me than the default "cmd+shift+d" command.

I went into "Atom > Open Your Keymap" and set it to:

```
'.atom-text-editor':
   'cmd-d': 'editor:duplicate-lines'
```

However, this seems to have no effect. cmd+d still selects the previous character instead of duplicating the line.

Based on everything I've seen in the docs - this should work. Any ideas what I'm doing wrong?

**Comment by mnquintana** [comment]
There is no `.atom-text-editor` class - it's a custom element, not a class, so it should be:

```cson
'.atom-text-editor':
   'cmd-d': 'editor:duplicate-lines'
```

Was there a specific doc you were looking at that had `.atom-text-editor`?

**Comment by globexdesigns** [comment]
No doc. That was my mistake. However, changing it didn't help. The command still doesn't work as expected. It's selecting the word at the cursor's position instead of duplicating the line.

**Comment by envygeeks** [comment]
@globexdesigns because it doesn't technically sit under 'atom-text-editor' directly, it has a platform selector before it, type 'ctrl + .' to find out what the selector is so you can hit it directly, for example on mine it's: '.platform-linux atom-text-editor'

**Comment by globexdesigns** [comment]
@envygeeks Thanks. I've changed my keymap to:

```
'.platform-darwin atom-text-editor':
   'cmd-d': 'editor:duplicate-lines'
```

And now it works.

I'd like to keep this bug open so that the documentation at https://atom.io/docs/latest/advanced/keymaps can be updated as it makes no mention of requiring a platform prefix on keymaps.
