### ISSUE TITLE
Window position not remembered after Reload

### ISSUE THREAD

**Issue by globexdesigns** [atom/atom#7555]
Atom 1.0, Mac OS 10.10.

Steps to reproduce:
- Launch Atom
- Move the Atom window to a secondary monitor and resize the Atom window
- Go to View > Reload
- (BUG) When Atom is reloaded it's moved back to it's original position and size

Expected behaviour:
- Atom should remember where the user can moved the window and what size it was between reloads

This is not an issue on Windows (where the window reloads in the correct location). Not sure if this is Atom-specific or an issue with Electron.

**Comment by arielpontes** [comment]
Same problem here. Atom 1.0.5 on Yosemite (10.10.4) doesn't remember its previous position when it was in a secondary monitor. It always opens in the main monitor.

**Comment by lpommers** [comment]
I also see experience this very often (Atom 1.07 Yosemite (10.10.5))

**Comment by darwin** [comment]
You guys are lucky that they just delivered me a second external display today and I have placed it on the left ;)

**Comment by garu57** [comment]
This very same problem is present in Windows release of Atom 1.0.19.
Can you address this too here or do you need another bug?

**Comment by garu57** [comment]
same with  1.1.0-beta1.
Discovered just now that if the window is closed when maximized, its position and size is remembered on both screens.
Although, if i click restore down after reopening it, the window borders are pushed out of screen margins.
I guess that for the right behavior also the pre-maximize size and position should be saved.

**Comment by darwin** [comment]
I'm not going to address this in Windows. That's a work for someone else. Also I quite doubt it is the same issue.

**Comment by alexfedoseev** [comment]
Same here, always opens on main display, even it was moved and closed on second display (in common & in full screen modes).

Atom 1.3.2, MacOS X 10.11.2

**Comment by globexdesigns** [comment]
This is now better in 1.6.0-beta0. The window position is on the right monitor, but always about 50px or so lower than where it was when closed.

**Comment by joshaber** [comment]
We're actually tracking this in #10648 now.

**Comment by EvNaverniouk** [comment]
Yay, this appears to be fixed in 1.9.0-beta!

**Comment by Drwalnik** [comment]
Nope, not fixed.

**Comment by EvNaverniouk** [comment]
Yeah, it broke again.
