### ISSUE TITLE
"Save" or "Save All" on unmodified, opened files results in "Unable to save file: permission denied" error

### ISSUE THREAD

**Issue by sergiom-sf** [atom/atom#7566]
When working with a project under Perforce revision control, it is normal for unmodified files to be read-only on the file system.  Currently, I get several errors when I do "Save All" when I have several unmodified files open.  It would be nice to not get the error when the files are unmodified.  There are cases where there be several opened files, some modified and some not.  "Save all" would only have to save the modified files.  Of course, if the modified files are still read-only, it makes sense to report the "Unable to save file" error.

**Comment by benogle** [comment]
A couple options for solving this:

1. text buffer checks if read only, and doesnt save if modified
1. we create a setting to save only when modified

**Comment by sergiom-sf** [comment]
The behavior of a couple other editors (gedit and Eclipse) are in line with option #1.  Both editors grey out the "Save" option on the UI when the file is not modified.  Using the save shortcut results in no error/warning popup.

**Comment by mehcode** [comment]
@sergiom-sf The problem here is that atom explicitly saves files that have not been modified when asked to save in order to fire a browser reload (for instance when used in conjunction with livereload).

:+1: for number 2. 

I don't like the hard drive thrashing that happens if I have 30 tabs open and hit "Save All" when I've only modified 3 things.

**Comment by sergiom-sf** [comment]
@mehcode I think the livereload case you bring up involves an unmodified file which is writeable on the file system.  The cases that I brought up involved a unmodified file which is read-only on the file system.

The current behavior of re-writing an unmodified file when the file is writable may be useful in the livereload case, but it is not useful in simple makefile C/C++ cases.  If you have a header file open and it's unmodified, a "Save" or "Save all" will trigger a rebuild of all source files which include that header.  I think it would be nice to not re-write unmodified files by default.  It will be annoying for C/C++ developers to have to close files to avoid having them re-written on Save / Save All.

Perhaps the behavior could be like this:

* Unmodified, read-only file -> no save and no error reported.
* Modified, ready-only file -> no save and report permission error
* Unmodified, writeable file -> no save by default, add option to enable for liverecord-like cases.
* Modified, writeable file -> simply save the file.

**Comment by mehcode** [comment]
> - Unmodified, read-only file -> no save and no error reported.
> - Modified, read-only file -> no save and report permission error
> - Unmodified, writeable file -> no save by default, add option to enable for liverecord-like cases.
> - Modified, writeable file -> simply save the file.

Agreed :100: 

---

I'd also ask for an authentication prompt when trying to save a file that is read-only at a permission level (rather than a mount level).

**Comment by TrondKjeldas** [comment]
This is the same issue as reported in #2871, I think.

As already mentioned in comments above, this is particularly anoying when working on large C/C++ projects, where saving an unchanged header file may trigger massive rebuilds.

**Comment by jamesgpearce** [comment]
See also https://github.com/atom/text-buffer/pull/94
