### ISSUE TITLE
powerline: 400 Bad Request Repository inaccessible

### ISSUE THREAD

**Issue by blaisck** [atom/atom#7567]
Installing “powerline@0.1.0” failed.Hide output…
Unable to download https://www.atom.io/api/packages/powerline/versions/0.1.0/tarball: 400 Bad Request Repository inaccessible

**Comment by kevinsawicki** [comment]
I can definitely reproduce this.

@thedaniel should this package be removed since the repository is gone?

**Comment by blaisck** [comment]
Or I should use this https://github.com/BoJlod9I/atom-powerline

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#15
