### ISSUE TITLE
Opening settings view rewrites newline values in config.cson

### ISSUE THREAD

**Issue by evanwarner** [atom/atom#7569]
**General issue:**
I have a few key:value pairs in my config.cson file that have "\n" as the value. If I open Atom's settings view, those values get immediately overwritten with triple quotes surrounding blank lines of indentation.

So for example:
```
    "space-after-opening-brace": "\n"
```
becomes
```
    "space-after-opening-brace": '''
            
            
    '''
```

The issue is recreatable in safe mode, and no errors appear in the dev tools.

**Specific details:**
If I leave Atom open and edit the config file back to the correct "\n" values, I can toggle back and forth to settings and it will stay correct. However, if I change any settings or enable/disable a package, the config file is overwritten again.

![bug](https://cloud.githubusercontent.com/assets/6453842/8423840/cfdd90fe-1ebd-11e5-8f4e-3e3e2edbe55e.gif)

Atom v1.0.0 on OS X 10.9.5

**Comment by mnquintana** [comment]
Would you mind closing this and reopening on https://github.com/atom/settings-view?
