### ISSUE TITLE
Rubocop command is not found.

### ISSUE THREAD

**Issue by Arunk1390** [atom/atom#7571]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Linux Mint
**Thrown From**: Atom Core

### Stack Trace

Rubocop command is not found.

```
At When you don't install rubocop yet, Run `gem install rubocop` first.

If you already installed rubocop, Please check package setting at `Rubocop Command Path`.

undefined
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "ruby-slim",
      "ruby-slim",
      "ruby-slim",
      "linter"
    ]
  },
  "editor": {
    "invisibles": {},
    "showIndentGuide": true,
    "showInvisibles": true,
    "softWrap": true,
    "softWrapAtPreferredLineLength": true
  }
}
```

### Installed Packages

```coffee
# User
linter-rubocop, v0.2.7
linter-ruby, v0.1.6
rubocop-auto-correct, v1.0.0

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
Please re-open this issue in the [linter-rubocop repo](https://github.com/AtomLinter/linter-rubocop/issues).

**Comment by mnquintana** [comment]
Hmmm, it's weird that this was thrown from Atom core though. @izuzak @kevinsawicki

**Comment by izuzak** [comment]
@mnquintana Yep, already added it to https://github.com/atom/notifications/issues/66. Thanks for the :bell:

**Comment by benogle** [comment]
The stack is weird. Not sure by it's their message. Because the stack doesnt have any paths in it, there is incorrect attribution.

**Comment by askl56** [comment]
Issue still occuring now.

**Comment by otavioschwanck** [comment]
#2 Have issue two.  Same Operational System
