### ISSUE TITLE
Can we put a copy on http://sourceforge.net/

### ISSUE THREAD

**Issue by kenchowcn** [atom/atom#7575]
Dear ATOM developers:

Considering some users are living in China, which have a restricted networking, the ATOM app's download server is on Amazon at present, we really hard to get the APP in here, can we put a copy on http://sourceforge.net/

Thank you!
Ken.

**Comment by Ciantic** [comment]
@kenchowcn are you aware that Sourceforge has gone to toilet? They've added adware to executables etc. "hijacked" projects, added fake download buttons etc. Just look [at the last year of HN entries.](https://hn.algolia.com/?query=sourceforge&sort=byPopularity&prefix&page=0&dateRange=pastYear&type=story)

**Comment by benogle** [comment]
cc @zcbenz can we do something to make Atom more available to people in china. 

I agree that sourceforge is not the right choice.

**Comment by kevinsawicki** [comment]
@kenchowcn are you able to download Atom from https://github.com/atom/atom/releases ?

**Comment by zcbenz** [comment]
@fengmk2 has set up an mirror for Atom: http://cnpmjs.org/mirrors/atom/.

**Comment by izuzak** [comment]
@kenchowcn Does http://cnpmjs.org/mirrors/atom/ help, or is there something else you'd like to see?

**Comment by abdul** [comment]
@izuzak @zcbenz http://cnpmjs.org/mirrors/atom/ is working fine. Thank you for sharing it.

**Comment by Tribex** [comment]
Thank you all (particularly @fengmk2) very much, I was just about to set up a mirror on a tiny VPS to solve this problem!

**Comment by haiy** [comment]
Great, thanks!

**Comment by izuzak** [comment]
> Can we add the url of the mirror to the README.md @izuzak ?

@haiy That's not an officially supported mirror, so I'm not enthusiastic about that idea. We can refer users to this issue or you could add a post on the forum: https://discuss.atom.io/.

**Comment by lee-dohm** [comment]
@izuzak I created a FAQ entry for this on Discuss here:

https://discuss.atom.io/t/are-there-alternate-download-locations-for-users-in-china/18604

Let me know if any of it should be reworded.

**Comment by izuzak** [comment]
Thanks, @lee-dohm. I'm not sure I'd say that "the Atom team has added an alternate download location" -- as, @zcbenz [mentioned](https://github.com/atom/atom/issues/7575#issuecomment-117860203), that was done by someone else.

**Comment by batjko** [comment]
Either way, this issue can probably be closed with that, unless there are concrete plans to add an *official* mirror sometime soon?

**Comment by thomasjo** [comment]
Agreed. Closing this for the time being.

**Comment by lee-dohm** [comment]
Ah, thanks @izuzak! Changed it to:

> For users in China, getting to the normal Atom download locations is hard and time consuming. To help make this easier, an alternate download location was set up by a volunteer:

**Comment by kenchowcn** [comment]
@izuzak Yes, It works, sorry for my delaying response.
