### ISSUE TITLE
Settings tab always visible when starting Atom

### ISSUE THREAD

**Issue by Dangthrimble** [atom/atom#7576]
I'm new to Atom and have just had a quick play, but am confused as to why, having once looked at the Settings, the Settings tab opens every time I open Atom, whether I had previously closed it or not. Is this intended behaviour?

I am running Atom 1.0.0 on Win7 Pro SP1 (64-bit).

Thanks

**Comment by benogle** [comment]
Not intended. Can you quit atom and run `atom --safe .` from the command line? After a couple quits and restarts is the issue still there? I wonder if a package failing in the deactivate method is messing up setialization.

**Comment by Dangthrimble** [comment]
Ran `atom --safe .` from the command line a couple of times then started it normally. Atom started as it had when run from the command line, i.e. no Settings tab. Opened then closed Settings, restarted Atom and the Settings tab was not there. Opened Settings, restarted Atom, closed Settings, restarted Atom and the Settings tab was still not there. 

Uninstalled Atom and deleted `%appdata%\Atom` and `%localappdata%\atom`. Reinstalled Atom. Opened Settings, restarted Atom, closed Settings, restarted Atom and the Settings tab was still not there. 

Restarted Atom, opened a file and opened Settings. Restarted Atom, closed Settings and restarted Atom. Still no Settings.

Looks like an "unable to reproduce". Will have a look on my other PC at home.

**Comment by benogle** [comment]
Ok, so it seems like things are fine, right? Or am I reading incorrectly?

**Comment by Dangthrimble** [comment]
Just checked on my home PC and everything seems OK. Can't tell if this is an "unable to reproduce" or just me having a funny five minutes!

**Comment by Meligy** [comment]
I'm still having this. `--safe` doesn't help. I'm on latest Mac (not Windows) and latest Atom.

**Comment by Dangthrimble** [comment]
It's weird, I had the same problem on two PCs, but `--safe` seemed to work for both. It would appear there are two issues, the initial problem causing the Settings window to stick on and the fact that `--safe` doesn't fix it for Macs. Also odd that not many people seem to be reporting it.

**Comment by simzdk** [comment]
Having the problem as well. Windows 10. --safe not working.

**Comment by maxbrunsfeld** [comment]
@simzdk, @Dangthrimble Can you report the output of `atom.project.getPaths()` from the javascript console?

**Comment by Dangthrimble** [comment]
@maxbrunsfeld I no longer have this problem. Do you still want me to report the output? If so, how do you open the javascript console?

**Comment by simzdk** [comment]
@maxbrunsfeld , I deleted the .storage folder at it seems to help. However I have used that solution 3 times the last week, as Atom from time to time insist of opening settings files.

**Comment by jsejcksn** [comment]
I'm experiencing the same issue on my Windows installation, but not on OS X. I'm running Win 10 Pro x64 and Atom 1.0.11. @maxbrunsfeld The result of running `atom.project.getPaths()` for me is `["atom://config"]`. The issue persists even when starting via `atom --safe`.

**Comment by vaindil** [comment]
Same issue here, Windows 10 x64, Atom 1.0.11. Once Atom is initialized the title bar _always_ says `<filename> - atom://config - Atom`. Output from `atom.project.getPaths()` is `["atom://config"]`. `atom --safe` had no effect. Deleting `storage` fixes the problem (the title bar is correct and Settings doesn't open), but once Settings is opened again the problem begins again and persists through program restarts, regardless of whether the Settings tab was closed before restarting the program.

Not sure if it's related to #8227, but I do have that problem as well--any time I open the Settings menu that `config` folder is added to the tree view indefinitely (it appears under the same circumstances that cause the Settings menu to open).

**Comment by benjaminalt** [comment]
This is still a problem on Windows 10 with Atom 1.2.4.

**Comment by jsejcksn** [comment]
This is still a problem for me on Win 10, Atom 1.3.2. But now it is opening the last open file (even if it is no longer in the filesystem), even if I close the file first before closing the Atom window.

**Comment by kristaps** [comment]
Seeing this on OS X, Atom 1.4.0

**Comment by ammichael** [comment]
I still got the problem in OS X, Atom 1.6.2.

Maybe good to notice that it began after installing Nuclide.

**Comment by maxbrunsfeld** [comment]
I'm going to close this out for now, as I believe the original bug has been fixed. Please let me know if this is still happening.
