### ISSUE TITLE
resize pane not work when atom running under guest OS under virtualbox with mouse intergration on

### ISSUE THREAD

**Issue by tsing80** [atom/atom#7578]
Host OS: WIndows 7
Guest OS: Ubuntu LInux

WHen running atom under the guest os , the resize icon is not display when the mouse cursor is between two pane. Trying to drag it to resize  does not work. Disable mouse intergration will solve the problem.
Probably due to mouse over event is not send to the editor when mouse integration is on

**Comment by batjko** [comment]
Could be the same as this issue: https://github.com/atom/atom/issues/6306
Can you confirm?

Generally there seem to be problems running Atom on VMs, most often with mouse events.

**Comment by tsing80** [comment]
Confirm that using the binary in 'ks-electron-chrome-42' branch mention in #6306 fixed the issue.

**Comment by 50Wliu** [comment]
Closing this as a duplicate then.
