### ISSUE TITLE
Hijacking keyboard and mouse?

### ISSUE THREAD

**Issue by ammeep** [atom/atom#7579]
:wave: Hi folks,

I'm going to have to say sorry in advance for what is going to be a very vague bug report. I'll do everything I can to help you dig up the details you need though

After I updated to 1.0 :tada: I noticed that on occasion my machine would stop being responsive to the keyboard and mouse - sort of. Making mouse movements seemed delayed, text input basically stopped working. While this was occurring, it was very difficult for me to even open activity monitor to check which app was causing the problem. Atom was one of the few apps open in the doc, I managed to force quit the app and every suddenly returned to normal.

Tonight it happened again, only worse. Atom seemed to be on auto pilot, deleting line by line what I was working on. My mouse and keyboard would take no input. The only way I could record what was happening was with my ipad - [here is my shaky recording](https://www.dropbox.com/s/2texc0ral95t84p/atom%20bug.mov?dl=0). I had to hard reset my machine. 

Let me know what other information I can get which will make this easier to pin point.

**Comment by mnquintana** [comment]
Whoa, that is super weird. Does this happen in safe mode as well? (`atom --safe`) What OS are you on? Have you seen anything like this in other apps?

**Comment by ammeep** [comment]
I'm running on Yosemite. I have not seen this with other apps before. 

I'll try running in safe mode for a time and see if it occurs again.

**Comment by hedefalk** [comment]
I've had similar issues at a few points in time. Computer coming to a crawl and I couldn't get the activity monitor up, but force quit Atom and computer snappy again in a second. Yosemity too.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions about safe mode in our comment https://github.com/atom/atom/issues/7579#issuecomment-117150927. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
