### ISSUE TITLE
Editor is not responding when open file

### ISSUE THREAD

**Issue by tinymins** [atom/atom#7581]
Editor is not responding when open this source code file.
I've tried safe mode, and it still went into no responding status.
![qq 20150630184539](https://cloud.githubusercontent.com/assets/1808990/8429260/8b0da946-1f58-11e5-983f-5783db948ef8.png)
[Click to download file string.7z](http://zhaiyiming.com/file/string.7z)

**Comment by batjko** [comment]
So this lua file has roughly 7k lines, with a bunch of special chars (what's the encoding?).

I can't replicate this when I open the file (Win8, 64bit, Atom v1.0.0):
![image](https://cloud.githubusercontent.com/assets/7287076/8430291/03a42186-1f28-11e5-8f5e-1a54f3f43c1a.png)

Can you try and run atom in safe mode (`atom --safe`), and see if this still happens?
If it does not, there will be a community package installed that can't handle the file.

**Comment by tinymins** [comment]
I've tried safe mode and it still happened.
The encoding of this file is GBK.

Win7 x64 Atom v1.0.0

**Comment by tinymins** [comment]
I find that when I start Atom with `atom --safe`, I can still see all my packages.
Is the any problem?
![qq 20150630200907](https://cloud.githubusercontent.com/assets/1808990/8430433/29a1693e-1f64-11e5-9158-f73c5c34877c.png)

**Comment by batjko** [comment]
No, that's not normal. All your community packages should be disabled. :confused: 
Not sure about that one. Likely an unrelated problem... 

However, I can replicate this main issue by switching to the GBK encoding.
 1. Open file in utf8 (takes a moment to open, but all still fine)
 2. Click encoding link in status bar and switch to GBK
 3. Observe Atom freezing up.

**Comment by mnquintana** [comment]
@tinymins If Atom started with just an unsaved buffer (untitled) and you then ran `atom --safe`, then it adds the folder to the existing window rather than opening a new one in safe mode. To ensure that Atom opens it in safe mode, quit Atom first and then run `atom --safe`.

**Comment by tinymins** [comment]
I find if I set default encoding to UTF-8, Atom will not freezing up.
But actually the encoding is not correct.
When switching encoding `(ctrl+shift+l)` to GBK, it freezing up.
So the problem caused by decoding GBK?

**Comment by tinymins** [comment]
I tried to split that file `string.lua` into several files and open each, Atom works well.
That's strange, so the problem is not with the GBK decoding?

**Comment by tinymins** [comment]
Just now atom crashed with this infomation and won't start again.
Crashing:
![qq 20150630223252](https://cloud.githubusercontent.com/assets/1808990/8433439/5c342c6a-1f78-11e5-8b33-f8b33c4d81ad.png)
Restart atom after crashed:
![qq 20150630223556](https://cloud.githubusercontent.com/assets/1808990/8433484/a74212ee-1f78-11e5-9460-ea8c45f1eeaf.png)

**Comment by batjko** [comment]
Yes so this will be to do with the way the GBK encoding works on large files. Perhaps it's more resource-intensive or something. I'm not sure.

**Comment by cjwelborn** [comment]
Atom is hanging up on large files for me. I opened a 13MB (android bug capture report), and it freezes. This file has 180000+ lines, a few are at least 1200 characters long. 
I eventually get the "force close" dialog. Running with `--safe` does not change anything. I can grab more info if needed.

**Comment by laurisb** [comment]
@cjwelborn Same for me, Atom freezes when opening "large" (1 - 2 MB) files, for example, PHP libraries - TCPDF, MPDF. I'm using Windows 7 and Atom 1.0.2.

**Comment by cyvoit** [comment]
Same for me. Atom freezes when opening `coffee-script.js` (159KB). I'm using Mac OS X 10.10.4 and Atom 1.0.3.

**Comment by batjko** [comment]
Since encoding seems to be a contributing factor, can you guys add which encoding you are using and also confirm if you see the same behavior after switching to UTF8, if applicable?

**Comment by laurisb** [comment]
File encoding was always UTF-8, never tried with different encoding.

**Comment by jonassdp** [comment]
Same problem here, opening a xml file of 185k lines and 3.2mb size.

Encoding is iso-8859-1 but changing to utf-8 seems not make any diference.

**Comment by JuliusMalisauskasDB** [comment]
Same here - I cant start Atom on my project folder, I am getting the same "not responding window" (running on win7 x64 v1.2.1).
It shows "react-mobiscroll.js" in the tittle. So I guess it has problems loading it. That file is 282KB.
How do I reset files which will be opened on project startup?

**Comment by JuliusMalisauskasDB** [comment]
I renamed folder "C:\Users\<user name>\.atom\storage" -> "storage_" and no files was loaded on startup. Worked like a charm.

**Comment by dkelsey** [comment]
I had the same issue this morning.  renaming `~/.atom/storage` did the trick.

**Comment by marcelozarate** [comment]
Thanks! Same problem here, renaming `~/.atom/storage` worked for me.

**Comment by imziyang** [comment]
Thanks! I delete all files in `~/.atom/storage`, and it's work

**Comment by nsrau** [comment]
I also deleted the files `~/.atom/storage` and it worked!

**Comment by tinymins** [comment]
Delete all file except `application.json` in `.atom/storage` alse works for me!

**Comment by lee-dohm** [comment]
It sounds like this is now working? Please let us know if this is not the case :grinning:

**Comment by MarleneD** [comment]
The same on my side!
After deleting storage everything works perfect, THANKS!

**Comment by Alexniver** [comment]
deleting storage works for me too! thanks !

**Comment by samriddhap** [comment]
deleting the storage file did worked for me :) thnaks :100:
