### ISSUE TITLE
Problem saving file?

### ISSUE THREAD

**Issue by NCroke221** [atom/atom#7584]
![problem](https://cloud.githubusercontent.com/assets/13117670/8429689/053abd12-1f22-11e5-80ca-b505c4542fc0.PNG)

Some reason occasionally this message pops up saying i cannot save the file.

Any help would be greatly appreciated.
Thanks,
Niall Croke

(I do however love the software)

**Comment by batjko** [comment]
Looks like you're editing a file over a network share, correct?

There have been other issues logged about doing this:
https://github.com/atom/atom/issues/5199

**Comment by NCroke221** [comment]
That is correct, I am curently on a shared network, 

I'm glad im not the only one encountering this issue, Would it be a case i have to edit the drives over from a local drive then save that file onto the network drive? Would that be a way around this?

It doesn't seem like there is a solutions as of yet from what i was reading

**Comment by batjko** [comment]
Yes, copying the file locally will probably alleviate your problem.
It's not ideal, but it is a way around it for the time being.

As you can see the other tickets have been open for a long time, so we can't be sure when this will be fixed for good.

**Comment by robneville73** [comment]
+1 same problem. performance is also really bad. For me this is on OS X and I'm opening a folder on a mounted share to a local Centos VM, so there's really not network latency at all. Copying files locally is not really a realistic option here.
