### ISSUE TITLE
where are notes saved?

### ISSUE THREAD

**Issue by RavenSong** [atom/atom#7585]
After the update all my notes that I see when I open atom were gone. The normal split screen is black and show only one note called untitled?

Where did all my files go?

**Comment by batjko** [comment]
By notes presumably you mean the panels with code/text?
Looks related to one of these:
https://github.com/atom/atom/issues/1603
https://github.com/atom/atom/issues/4653

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/7585#issuecomment-117147700. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
