### ISSUE TITLE
Folder git status colour doesn't update after delete

### ISSUE THREAD

**Issue by MaxGiting** [atom/atom#7589]
Create a new file and the directory hierarchy above will change to be green. If you then delete the file the folder colours do not revert to their original even if no other files have been amended or added.

**Comment by rm-code** [comment]
Just wanted, to report the same issue.

It only seems to update if you tab out and back to Atom.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tree-view?

**Comment by rm-code** [comment]
Done @mnquintana @MaxGiting https://github.com/atom/tree-view/issues/498
