### ISSUE TITLE
Packages and Themes does not search automatically

### ISSUE THREAD

**Issue by sw3dish** [atom/atom#7590]
To search for a package / theme in the settings tab, I have to type in the search query then click (if looking for a package) the themes button, then the package button to have Atom search for a package matching that string.

**Comment by mnquintana** [comment]
This is a duplicate of https://github.com/atom/settings-view/issues/559 – please subscribe there for updats.

(Also for future reference, Atom's settings view is handled by atom/settings-view, not atom/atom.)

**Comment by simurai** [comment]
I made a new issue https://github.com/atom/settings-view/issues/562 since #559 got slightly changed (UX -> bug).
