### ISSUE TITLE
Code Folding / Unfolding - Ignore Level 1

### ISSUE THREAD

**Issue by markadrake** [atom/atom#7592]
I write a lot of JavaScript widgets where the first line defines the widget. [The shortcuts to fold and unfold code](https://atom.io/docs/latest/using-atom-folding) don't help me much because I can't ignore the first level. 

![image](https://cloud.githubusercontent.com/assets/713355/8432666/6d75dbcc-1f0f-11e5-8e37-f7e1caea7723.png)

Folding as it works currently:

![image](https://cloud.githubusercontent.com/assets/713355/8432685/83e47080-1f0f-11e5-9426-54b9fd7a460f.png)

The result I would like:

![image](https://cloud.githubusercontent.com/assets/713355/8432695/961e38a8-1f0f-11e5-9c4c-08f7b4505b5b.png)

How is everyone else's experience with this?

**Comment by markadrake** [comment]
I think a generic rule could be applied that if only one fold-able block (top most) is found that it ignores the first level. I'll check out the source code and make a commit if people agree with this approach.

**Comment by benogle** [comment]
You can use `cmd-k cmd-$n` where $n is the indentation level. So hold down cmd, then press k, then 2, and it should fold like your 2nd image indicates.

**Comment by markadrake** [comment]
Ben, thanks for the shortcut. That indeed resolves my problem in particular. I'd still like to know if this is the expected functionality coming from other people using Atom. In what scenario would collapsing an entire file down to 1 line help anyone? I think it's worthwhile to explore. Similar things happen in HTML documents - I'd never expect the body to collapse and hide the contents within, only the child elements within. Standard default functionality like this is something VS implements with it's shortcuts to folding code.

Thanks for your feedback and quick reply.

**Comment by benogle** [comment]
You might have other things at the root, and the current shortcuts allow you to fold as you see fit. I use them all the time in specs, folding at the 3rd indentation level.
