### ISSUE TITLE
Atom crashes when manually changing font size in settings page

### ISSUE THREAD

**Issue by danielepantaleone** [atom/atom#7598]
Screenshot: http://i.imgur.com/UrqsJ5K.png
OS: Win 8.1
Steps to reproduce: open Atom, click on File >> Settings, change the font size entering a value in the field, press Enter: Atom hangs for a while then the dialog shown in the screenshot appears.

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode? (`atom --safe`)

**Comment by danielepantaleone** [comment]
With the `--safe` flag Atom doesn't crash. More over, now I see the value I was trying to enter as font-size (while if I start Atom not using the safe mode it's still displayed the `default = 14` placeholder.

**Comment by mnquintana** [comment]
Thanks for the update! That's still kind of strange though. What value were you trying to enter exactly? (Copy and paste it here if you can.) Can you post a list of your installed packages? (`apm list --installed`) Do you have anything in your [Init Script](https://atom.io/docs/latest/hacking-atom-the-init-file)?

**Comment by danielepantaleone** [comment]
I tried to enter just `12`. I didn't install any package (I experienced the crash like 10 seconds after the install process completed): I just downloaded, launched the setup, which when completed opened Atom, and since the font was too big I wanted to reduce it :smile:

**Comment by mnquintana** [comment]
Did you have a large file open at the time? I noticed from the screenshot that you had some kind of log file open.

**Comment by danielepantaleone** [comment]
Yes it's a log file but no more than 300 lines

**Comment by nathansobo** [comment]
@mnquintana That's an Electron-level crash, so we should really submit a crash report to https://github.com/atom/electron. Not sure how to obtain one on the Windows platform.

**Comment by batjko** [comment]
Squirrel log presumably? Somewhere under `C:\Users\[username]\appdata\local\atom`, if I remember correctly.

**Comment by lee-dohm** [comment]
Has this ever been reproduced? @danielepantaleone are you still experiencing this issue?

**Comment by danielepantaleone** [comment]
@lee-dohm I've switched over another text editor since then, so no (I guess)

**Comment by 50Wliu** [comment]
Ok.  As there have been no more reports of this, and we're on a far-newer Electron version now, I'm closing this.
