### ISSUE TITLE
cmd+/ always injects HTML comments now, instead of context-aware comments

### ISSUE THREAD

**Issue by ryedin** [atom/atom#7600]
Atom v1.0.0 (Mac)

Even when inside a .js file, using the keyboard shortcut `cmd /` always results in `<!-- -->` (HTML) comments instead of the previous behavior of proper `//` comments. 

Same result when in a .sh file (previous behavior properly inserted `#` comments, but now uses `<!-- -->`.

**Comment by benogle** [comment]
Can you paste in your config.cson and the file contents? Does this happen in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by smashwilson** [comment]
Also, check to see if you have Emmet installed; I've seen a few people see that behavior and the emmet package was the culprit.

**Comment by ryedin** [comment]
Thank you, guys. Confirmed that the behavior is as expected both in safe mode, and after disabling emmet.

I will look into filing a similar issue over in emmet's repo (if it hasn't already been reported). Shame, that's an awesome package I don't want to have disabled.

Thanks for the troubleshooting help and sorry for not having found the culprit myself.

**Comment by ryedin** [comment]
Quick update for anyone else stumbling upon this and being confused... 

The emmet package settings apparently allows disabling emmet comments and using native Atom comments. Turns out in the end this is all user error (although I'm fairly certain this was a newly introduced default behavior of emmet, which led to my confusion, as the comments worked seamlessly for me up until <some recent update within the last week or so>)

**Comment by curtisblackwell** [comment]
Thanks for updating the thread @ryedin.
