### ISSUE TITLE
Strange SourceTree tracking issue

### ISSUE THREAD

**Issue by usabillla** [atom/atom#7601]
Hey, i've notice that my SourceTree following changes after i open some SCSS file, he track and see changes i haven't done and anyway it doesn't change anything. 
Atom v1.0.0 on Yosemite. 
![2015-06-30 22 20 12](https://cloud.githubusercontent.com/assets/11925657/8439688/4c203b2c-1f76-11e5-8d04-432b2de1d7ed.png)

**Comment by batjko** [comment]
I'm not sure how this is related to Atom.
Are you saying that this file, after saving it in Atom, has changes that aren't really changes when you open it in Sourcetree?

**Comment by usabillla** [comment]
It appears after i open SCSS file in ATOM. 
And this start happen after i switch from Sublime.

**Comment by benogle** [comment]
I think this probably has to do with the whitespace package. You can disable the removal of trailing whitespace by looking up the settings of the whitespace package and disabling this:

![whitespace](https://cloud.githubusercontent.com/assets/69169/8442289/f9a93a8a-1f32-11e5-88e1-932728fb3842.jpg)

**Comment by batjko** [comment]
One would have thought that Sourcetree highlights whitespace properly, similar to how Github does it. It's kind of significant for a lot of code files.

**Comment by mnquintana** [comment]
I'm gonna close this out – feel free to reopen if we misunderstood the issue.
