### ISSUE TITLE
Fullscreen messes up editor size

### ISSUE THREAD

**Issue by samuela** [atom/atom#7604]
Upon entering fullscreen I got this effect: 
![captura de pantalla 2015-06-30 a la s 4 58 33 pm](https://cloud.githubusercontent.com/assets/226872/8441937/9064edc8-1f49-11e5-95ad-a0a4be71fd83.png)

and then exiting fullscreen left me with

![captura de pantalla 2015-06-30 a la s 4 58 41 pm](https://cloud.githubusercontent.com/assets/226872/8441944/9cf8046c-1f49-11e5-9321-efc32780166e.png)

**Comment by batjko** [comment]
Can you try it in safe mode (`atom --safe`).
If this won't happen anymore, your culprit is a community package that needs fixin'.

**Comment by samuela** [comment]
Looks like it's minimap. Thanks!
