### ISSUE TITLE
Toggle Soft Tabs fails from Atom Preferences

### ISSUE THREAD

**Issue by jkarimi91** [atom/atom#7605]
Toggling Atom's Soft Tabs setting from Preferences\Settings\Editor Settings has no effect.
The only way to toggle the setting is using Editor: Toggle Soft Tabs from the Command Palette

**Comment by mnquintana** [comment]
I think this is a duplicate of https://github.com/atom/atom/issues/6203 - let me know if I'm misunderstanding though!
