### ISSUE TITLE
Community Packages & Themes Broken?

### ISSUE THREAD

**Issue by spencerthayer** [atom/atom#7609]
It seems as if my install of Atom cannot connect and get packages.

![screen shot 2015-06-30 at 9 00 56 pm](https://cloud.githubusercontent.com/assets/1019815/8446119/320d6a30-1f6b-11e5-923c-19e8eb29b392.png)
![screen shot 2015-06-30 at 9 00 34 pm](https://cloud.githubusercontent.com/assets/1019815/8446120/3212130a-1f6b-11e5-83d5-47ee24d3230d.png)

Any ideas?

**Comment by 50Wliu** [comment]
You can install new packages/themes from the `Install` sidebar.
If that doesn't work, please open an issue on [atom/settings-view](https://github.com/atom/settings-view).  Thanks!
