### ISSUE TITLE
weird xml tag matching behaviour

### ISSUE THREAD

**Issue by ttwd80** [atom/atom#7611]
here is a sample xml code
```    
<?xml version="1.0" encoding="UTF-8"?>
<div>
  <span>
    <span id="content"/>
  </span>
</div>
```
test 1: if i go to closing of "div" tag on line 6, then opening tag on line 2 is highlighted.
expected: line 2 is highlighted.
actual: line 2 is highlighted

test 2: if i go to closing of "span" tag on line 5, then opening tag on line 3 is highlighted.
expected: line 3 is highlighted.
actual: line 4 is highlighted
weird behaviour.

however if i remove the attribute and change line 5 to 
```
<span/>
```
test 2 passes

but if i add a space or an attribute
```
<span />
```
then test 2 fails

**Comment by izuzak** [comment]
Thanks for the report -- this sounds very similar to https://github.com/atom/bracket-matcher/issues/115. Could you add your findings to that issue in a comment please?
