### ISSUE TITLE
Path doesn't update in title bar when current working directory changes

### ISSUE THREAD

**Issue by funkytaco** [atom/atom#7614]
Tested on OS X Yosemite:

The path shown in Atom's title bar when current working directory changes. For example:

```
mkdir TestDeletion
atom TestDeletion
```

Then move the `TestDeletion` directory to the trash.

I would also recommend somehow indicating it is in the .Trash, but I'm not gonna put that in as an issue.

I also had an issue deleting a directory once (as some .pack and .idx files were open?), but I haven't been able to duplicate that yet.

**Comment by Motardo** [comment]
The root folder can not be moved, renamed, or deleted from within atom ([Tree view issue 179](https://github.com/atom/tree-view/issues/179)). You can move the root folder externally (using the file manager or shell), but atom doesn't seem to know how to deal with this. I can confirm this behavior on Ubuntu 15.04 atom 1.0.0
