### ISSUE TITLE
Projects deleted when I restart the computer

### ISSUE THREAD

**Issue by distriker** [atom/atom#7616]
Hi everyone, **Atom** is an awesome tool to work, but I am having a problem. It have happened to me two or three times.

On a day, I can set different project to work in theirs on Atom. But when I restart the computer (one day to another), I open Atom and I haven't got the projects. I don't know if there is an Atom's error or if Atom isn't configured for storage the projects list.

I wait your answer. Thanks in advance.

Regards, _Iván_

**Comment by rm-code** [comment]
Hello @distriker,

if I understand your problem correctly, [this package](https://github.com/danielbrodin/atom-project-manager) might be what you are looking for.

Best wishes,
Robert

**Comment by benogle** [comment]
So is the atom window empty? What if you start atom in safe mode? Completely quit atom and run `atom --safe .` Do the projects come back after quitting and reopening?

**Comment by distriker** [comment]
Hi @rm-code,
it seems a very interesting package and option to apply and improve the productivy with Atom. I am going to try it!

Hi @benogle,
it is very strange, sometimes I quit and reopen and everything have dissapear and I have to open projects again, and another times (like today!) everything seems normal and like when I close the last time that I use Atom.

The next time that it happens to me I will start Atom in safe mode and what happens I will tell here.

Thank you both for your help. I keep it updated like I said.

Regards, *Iván*

**Comment by csholmq** [comment]
+1 on this.

If I close and restart Atom, it correctly remembers open files and added projects. If I close and then "Open with Atom", it only opens that file and forgets all other open files/projects.
