### ISSUE TITLE
Dead Keys stop working when Atom looses focus (OS X)

### ISSUE THREAD

**Issue by pbihler** [atom/atom#7620]
When atom looses the focus (e.g. switching to another application), the dead keys (e.g. <kbd>~</kbd>, <kbd>´</kbd>, <kbd>`</kbd>) stop working in the active editor, so there is no (preliminary) input when pressing the key. It does not affect the other editors of the window.

If you activate another editor and then switch back to the previous one, the dead keys are working again...

**Comment by mnquintana** [comment]
Hmmm I can't reproduce this with Atom 1.0.0 and OS X 10.10.3. What version of Atom are you using? What OS X version? Can you reproduce this in safe mode? (`atom --safe`)

**Comment by pbihler** [comment]
It seems to be te issue of one of the many plugins, I'll investigate :)
