### ISSUE TITLE
Reflow selection breaks indentation

### ISSUE THREAD

**Issue by danbim** [atom/atom#7621]
If I have a block of text indented and I use the "reflow selection" command (cmd+alt+q on Mac) the resulting text block will only keep the intended indentation in the first line but lose it in the following lines. While for some file types this might be the correct behaviour, IMO for many others it's not. Therefore "reflow selection" is unusable for my source code.

![screen shot 2015-07-01 at 11 57 20](https://cloud.githubusercontent.com/assets/300638/8452143/ced99d34-1fe8-11e5-910e-b9e79629aa2a.png)

If the current behaviour is still to be supported I suggest to make this a customizable behaviour, e.g., depending on file type.

**Comment by izuzak** [comment]
This issue was moved to atom/autoflow#31
