### ISSUE TITLE
Cannot find certain text

### ISSUE THREAD

**Issue by clicktravel-martindimitrov** [atom/atom#7622]
To reproduce:
1. Open a new file
2. Paste the following:
``` ho+8qEwxQSKZk2/h/ZS5/A== ```
3.  CMD+F on MAC to open the find text panel
4. Paste the same
5. Try to find it
6. Cry

**Comment by izuzak** [comment]
Works for me:

![screen shot 2015-07-01 at 13 54 45](https://cloud.githubusercontent.com/assets/38924/8453846/b91f8084-1ff8-11e5-960f-9161e11b6a08.png)

If you'd like to provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues), please reopen the issue at https://github.com/atom/find-and-replace.

**Comment by clicktravel-martindimitrov** [comment]
Ah, nvm. I had the ```whole word``` filter on. Now it found it.
Thanks!
