### ISSUE TITLE
Folder won't reopen folder after close on windows

### ISSUE THREAD

**Issue by vernak2539** [atom/atom#7625]
```
version: [6712:0701/134739:INFO:CONSOLE(0)] 1.0.0
devtool errors: none
os: windows 8
```

I am having a problem on windows with reopening folders. Here's usually what happens.
1. Get an issue with Atom locking files from git via cmd (usually permission error due to atom or file is locked for some reason)
2. Close Atom
3. Perform git actions
4. Open atom
   - have tried via cmd and via icon
5. If not tried from cmd, "open folder" and select folder that was previously opened before close

**Expected** atom to open folder selected from dialog or folder 'atom' was run from in cmd
**Actual** folder is never opened. It seems to unfocus on atom completely. It won't even load files from that folder when selected from "open file" or dragged into atom.

_Workaround_ is to restart your PC. 

Not sure what is going on here, and it's not the easiest to reproduce. I've tired safe mode and looked everywhere for possible errors. Would love not to restart my computer every time this happens, which is often. 

Not sure when this was last working, as it was still and issue for me prior to v1.0.0, but didn't happen as often.

Please let me know if there's any other information I can provide.

**Comment by vernak2539** [comment]
No word on this? Having to switch back to Sublime Text :-1:

**Comment by vernak2539** [comment]
@mnquintana when I do get to this state again, what can I do in order to retrieve the necessary information required for this bug?

**Comment by lee-dohm** [comment]
What command are you running in Git when you get these permissions errors? What files are showing the permissions errors? What folders are you trying to open after you receive these errors?

**Comment by vernak2539** [comment]
>What command are you running in Git when you get these permissions errors?

Merge or rebase

>What files are showing the permissions errors?

1. Files that are open in the editor. 
2. Files that have been previously opened in the editor, but are now closed

>What folders are you trying to open after you receive these errors?

I try to open the top level folder of the project (where .git is located). I then try to open folders the reside in that folder, but they won't open either

**Comment by lee-dohm** [comment]
Appears related: https://github.com/atom/atom/issues/6736

**Comment by vernak2539** [comment]
Just had this pop up again. Seems that there were background processes that hadn't terminated on close. Once these were closed via Task Manager and atom was restarted, the folder opened fine

**Comment by damieng** [comment]
Is this still an issue?

**Comment by vernak2539** [comment]
stopped using windows, so not sure tbh
