### ISSUE TITLE
Diff inline highlighting selects too much text; highlights incorrectly

### ISSUE THREAD

**Issue by nixxquality** [atom/atom#7626]
Here is an example where you can see the error occuring:
![example](http://i.imgur.com/kst1f3Q.png)

I assume that the opening `[-` starts matching until the last `-]` found, when it should be searching for the first `-]` found.

As a result, `{+embargo_efficiency+}` is incorrectly coloured red and ` = ` is also incorrectly highlighted, even though it shouldn't be coloured at all.

**Comment by thomasjo** [comment]
Can you provide some information as to how you're viewing that diff? Are you seeing it as part of a Git commit? Atom doesn't come bundled with any other package that handles diff or patch content.

If you're using the [`language-diff`](https://atom.io/packages/language-diff) package, please close this issue and re-open an [issue on its repo](https://github.com/miketheman/language-diff/issues).

**Comment by nixxquality** [comment]
Oh, is that so? I wasn't aware, sorry! This is an issue with git-plus, then.
