### ISSUE TITLE
Crash [Win 8.1]

### ISSUE THREAD

**Issue by Maslor** [atom/atom#7628]
After I launch atom, as soon as I click the tree dependency menu [1], it freezes and crashes into an error message [2]:

[1] 
![image](https://cloud.githubusercontent.com/assets/9674408/8456454/72e44edc-2003-11e5-9ae9-8dcff1503df3.png)

[2] 
![atom](https://cloud.githubusercontent.com/assets/9674408/8456368/d7da6476-2002-11e5-953a-6122e4b71be8.png)

Doesn't happen every time and reloading seems to fix the problem when it happens.
OS: Windows 8.1

**Comment by batjko** [comment]
Does it still happen if you open atom in safe mode (`atom --safe`)?

Do you see this every time, or only on occasion?
Does it happen only with this specific folder or also all kinds of other ones?

**Comment by Maslor** [comment]
It's on occasion, I only managed to repeat the error once purposely, it happened 3 times in total. 
I haven't yet had this issue with other folders but I don't think it's a specific folder problem since the crash happened without opening any of the folders. Clicking the area that I included in the red square was enough to crash.

**Comment by batjko** [comment]
Clicking the area that I included in the red square was enough to crash.

I think this may be significant.
I don't know what the tree view does when it gets focused, but we know it generally scans the project folder and some people have reported issues with very large and deep folder trees.

**Comment by damieng** [comment]
Are you still running into this issue on newer builds? If so, please re-open.
