### ISSUE TITLE
Add project folders starting with dot

### ISSUE THREAD

**Issue by osxtra** [atom/atom#7630]
Atom 1.0.0, running on Yosemite.

Tree View will not allow you to add a project folder if the folder name begins with a dot.

Core package Tree-view's "Hide Ignored Names" is NOT checked.

OS is set to show hidden folders in Finder, and will show those starting with a dot.

Treeview will show dot folders under the root of a project folder, but they don't get displayed in the "Add Project Folder" dialog, so there's no way to select them.

Example:  "/Users/myUser/mySubFolder1/.myDotFolder" does not get displayed in the "Add Project Folder" dialog.

However, if "/Users/myUser/mySubFolder1" is selected as a project folder, then ".myDotFolder" will show up under it in the tree view.

**Comment by lee-dohm** [comment]
On OS X, you can press <kbd>Cmd+Shift+.</kbd> in any standard File Open dialog to have it show hidden files (like those starting with a dot), including the Add Project Folder dialog.

Please let us know if there is more information you need.

**Comment by osxtra** [comment]
Lee-dohm, thanks for that tip, had never used that key-combo.  Thought it was something wrong with  Atom as its open dialog would not by default show the dot folders even though regular finder windows do show them.

Good day!
