### ISSUE TITLE
[Windows] Install to Program Files rather then the user profile

### ISSUE THREAD

**Issue by matt40k** [atom/atom#7636]
It appears the Windows Installer will install Atom to the user profile rather then to the machine program directory - normally c:\program files\. This makes things messy in a enterprise environment. Perhaps create a MSI installer that creates a machine based install using WiX. Any machine based config should be stored in c:\programdata and only user defined settings should live in the user profile - c:\users\%username%\

**Comment by kubetz** [comment]
@matt40k Try to install Atom with parameter `--machine`. See https://github.com/Squirrel/Squirrel.Windows/pull/337 .

**Comment by thomasjo** [comment]
That should work eventually, but Atom is quite out of date with Squirrel at the moment.

**Comment by paulcbetts** [comment]
Yep, you can install Atom to every user profile on the machine with `--machine` (eventually); it's pretty easy to remote install via PSExec

**Comment by matt40k** [comment]
Mmm, that wouldn't be ideal, normally you'd have a msi as you could deploy via GPO. Also having a none standard switch is rather annoying, really you just want to throw the url at the desktop team for deployment via SCCM and walk away. I'm not sure why you wouldn't want to use the OS built in installer - ie Windows Installer \ MSI, it seems like a lot of extra work. Normally enterprises block user installs and force machine installs as it has to go via SCCM which means it goes via the ITIL process, benefit to the end-user (ie the developer) you don't have to worry about patching which is absolute pain.

**Comment by allanrsmith** [comment]
What was the downside of having 'Squirrel machine install' copy files to Program Files\application and change the ACL's on the application folder to allow all users to create files/folders?  This way there is no quirky update logic, or a messy(non-existent) machine uninstall.  I feel like it may be too obvious, and you have a very good reason not to do it, I just can't think of it right now.

**Comment by paulcbetts** [comment]
Squirrel will now generate MSIs in the next version, watch for them!

**Comment by 50Wliu** [comment]
> Squirrel will now generate MSIs in the next version, watch for them!

Awesome!

**Comment by iouri-s** [comment]
This issue is closed now; however, the installer for Atom 1.2.4 still does not support the --machine option. I guess that is because Atom did not adopt the latest Squirrel version. Shouldn't an issue be closed only after it is resolved?
