### ISSUE TITLE
A Javascript error occured in browser process - windows 8.1

### ISSUE THREAD

**Issue by Sylerr** [atom/atom#7639]
![default](https://cloud.githubusercontent.com/assets/11138294/8464606/22f1fa02-204c-11e5-8f6a-4d7667a06a53.png)

can not open atom:(
I will be grateful if somebody explain how to fix it.

**Comment by mnquintana** [comment]
Does this also happen in safe mode? (`atom --safe`)

**Comment by kubetz** [comment]
I had a look what line is throwing TypeError and here is the code from `init.js` for version 0.211.0:

```javascript
48  app = require('app');
49
50  app.on('quit', function() {  // <---
51    return process.emit('exit');
52  });
```
So hopefully it will save some time for someone experienced to figure out what is going on.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/7639#issuecomment-117826743. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
