### ISSUE TITLE
Atom Opening Folder With 5MB tags file - repeatedly crashed

### ISSUE THREAD

**Issue by halhenke** [atom/atom#7641]
Not sure how I got such a large .tags file but whenever i would open this Project/Folder the Atom Window would repeatedly crash. Took awhile to figure out.

**Comment by benogle** [comment]
Can you make a gist for the tags file and paste the link in here?

**Comment by halhenke** [comment]
Managed to rescue it from the trash :+1: 

https://gist.github.com/halhenke/3ecf3960868ed6cda49b

**Comment by benogle** [comment]
cc @nathansobo @maxbrunsfeld
