### ISSUE TITLE
New line Added upon Save File

### ISSUE THREAD

**Issue by sealview** [atom/atom#7645]
Hello guys,

First I need to thank you for the great Editor.

It seems like the App it's adding a new line in the bottom of the file each time I save the document.
 I use it for PHP/WEB applications and it is annoying, mostly when you need to call variables/values from file_content, when during the fact that Atom adds new lines in the bottom, the PHP interprets it as space behind the value and throws Fatal Errors. 
If I edit the file outside the Atom and remove that spare line, everything goes well.

I tried looking for an option in this matter in the Settings of Atom and couldn't find any concludent, so if you thing this report comes in an error manner (mine especially), please feel free to announce me in any way.

Thank you guys.

**Comment by thomasjo** [comment]
This is controlled by the whitespace package. Go to the *Packages* screen and click on the *Settings* button (or the panel itself) for the *whitespace* package. There you'll see these options

![settings_-_atom](https://cloud.githubusercontent.com/assets/3622/8471472/d7d85906-2098-11e5-8345-aa9bea06ca66.png)

**Comment by sealview** [comment]
Thank you very much.

Probably I had to take more time to read about it before jump... :+1:
