### ISSUE TITLE
naming the packages

### ISSUE THREAD

**Issue by a-atalla** [atom/atom#7646]
All the downloadable packages are named   "atom.x86_64.rpm" , could you please specify the  version in the package names , it will be so helpful

Thank you

**Comment by batjko** [comment]
I'd agree with that. It's worthwhile for people who want to keep installers for several versions around.

**Comment by mnquintana** [comment]
Thanks for the suggestion! This looks like a duplicate of https://github.com/atom/atom/issues/4044 – please subscribe there for updates.
