### ISSUE TITLE
Do not search big files automatically

### ISSUE THREAD

**Issue by itay-grudev** [atom/atom#7652]
Big files are a nightmare to search in because the IDE starts searching automatically as soon as you enter a letter.

Which crashes the IDE. Which makes you restart it or wait for 5 minutes.

This happened on a Core i7, not a Commodore.

Disable automatic search on big files please!

**Comment by visualcookie** [comment]
What big files do you got? Like node_modules or something?

You can ignore them by default in the Editor's settings.

**Comment by itay-grudev** [comment]
A huge text file I needed to search in. Just make it so by default it is disabled for big files even if automatic search is enabled.

**Comment by 50Wliu** [comment]
I'm going to close this in favor of atom/find-and-replace#145.
