### ISSUE TITLE
Ignored Names still show up in tree-view

### ISSUE THREAD

**Issue by Soleone** [atom/atom#7661]
I am not sure if this is a new issue, if I'm doing something wrong or if this is supposed to work this way. But I was pretty sure that when I first added some files into the `Ignored Names` area that they did properly get hidden in the `tree-view`.

![image](https://cloud.githubusercontent.com/assets/2923/8487380/b760f246-20d9-11e5-9b39-a524a1eeb909.png)

The only thing I recently did was to collapse the whole project folder. When I then uncollapsed it is the first time I noticed the hidden files and folders showing. And now I can't get rid of them. I tried restarting atom as well as editing the `Ignored Files` section again.

**Comment by mnquintana** [comment]
You need to change the setting in tree-view:

![screenshot_2015-07-02_17_00_45](https://cloud.githubusercontent.com/assets/823545/8487760/0c4a4d6e-20dc-11e5-9ee3-115d2aa2aad8.png)

**Comment by Soleone** [comment]
awesome thanks, sorry for the noise. i guess it might be a bit confusing that there's two settings on in atom and one in tree-view. might be worth adding a little description to the atom setting of `Ignored Names` what that field does for you.
