### ISSUE TITLE
Atom continuously crashing on Mac OS X

### ISSUE THREAD

**Issue by zfisher91** [atom/atom#7666]
Running Mac OS X Yosemite. Trying to edit any files, atom freezes up, then is not responding, then has to be force quit. Restarting app/Force quitting not solving issue.

**Comment by zfisher91** [comment]
I had installed minimap plugin and atom-beautify plugins. Uninstalled both, problem persisted after each uninstall.

**Comment by darezik** [comment]
Does the problem persist if Atom is run in safe mode? '(atom --safe)'

**Comment by izuzak** [comment]
@zfisher91 Also, is Atom crashing or is it just freezing (unresponsive), and which version of Atom are you using?

**Comment by JonForest** [comment]
I'm having something very similar.  In my case it becomes unresponsive requiring a force quite.  Occasionally OSX will report 'Atom closed unexpectedly'.

**Comment by lee-dohm** [comment]
@JonForest would you mind opening a new Issue? I'm not sure your situation is related and since this has gone for so long without a response, I'm going to close this.

If you have any questions, please let me know!
