### ISSUE TITLE
Soft wraps not working by default

### ISSUE THREAD

**Issue by Sogl** [atom/atom#7668]
Hi!

I use Atom 1.0 on Windows 7 x64 (also on Windows 8.1 x64).

Two problems:
1. I can't found how to enable soft wraps option to all opened files, not per file.
2. I can't see checkbox or something that show the state of soft wraps in **View -> Toggle Soft Wrap** 

Also described here:
https://discuss.atom.io/t/turn-on-line-wrap/1627

**Comment by batjko** [comment]
Have a look at this one, which is aimed at fixing it all: #3719

I'd recommend closing this issue and following that one for updates.

**Comment by 50Wliu** [comment]
@batjko it looks like this issue is about soft *wrap*, not soft *tabs*.

**Comment by batjko** [comment]
Dammit, I had several different issues open and commented on too many at the same time. Issue multi-tasking is not working for me.

**Comment by lifeBalance** [comment]
@Sogl If you go to `Atom>Preferences`, scroll down and you'll see an option called `Soft Wrap`,  mark it, and by default all files you open are soft wrapped.

**Comment by Sogl** [comment]
> If you go to Atom>Preferences
`File->Settings` on Windows. Thx for your help, it works now that it should!

**Comment by s2t2** [comment]
The "Soft Wrap" setting does not work in Atom v 1.1.0 on Mac OS. Even when this setting is checked, documents are not wrapped.

My goal is to enable soft wrap on all documents by default, and to avoid checking the "toggle soft wrap" option each time I open each file.

Thank you for your help in resolving this issue.

**Comment by jhabdas** [comment]
To enable Soft Wrap by default navigate to _Settings_ → _Editor_ and check _Soft Wrap_.

![](https://i.supload.com/H1g7S5XFcZ.png)
