### ISSUE TITLE
Toggle Soft Tabs command: tweaks for improved user experience

### ISSUE THREAD

**Issue by longears** [atom/atom#7670]
When toggling soft tabs through the command palette, there's no UI feedback about if it worked and what the new state is.  The only way to tell is to turn on invisible characters and try hitting tab.

Suggestions:
- emit a notification which displays the new state of the setting
- add two new commands "Enable soft tabs" and "Disable soft tabs" to avoid this issue altogether
- an icon in the status bar showing softness of tabs?

Also, the command could be named "Toggle Soft Tabs **In Current Editor**" since this local behavior may be surprising -- the soft tabs checkbox in settings is a global setting.

**Comment by batjko** [comment]
Have a look at this one, which is aimed at fixing it all: https://github.com/atom/atom/issues/3719

I'd recommend closing this issue and following that one for updates.

**Comment by longears** [comment]
That issue is about actual tab behavior and this issue is about UI feedback when changing settings, so I think they're orthogonal.

**Comment by batjko** [comment]
True. I saw a second ticket that looked identical to yours and I just copied my comment there to this one, my apologies.
I have amended it above.
