### ISSUE TITLE
Grey not properly syntax hilighted

### ISSUE THREAD

**Issue by erickramirez** [atom/atom#7671]
This is super small, but *grey* isn't properly syntax highlighted / recognized as a valid color value ([which it is](http://www.w3.org/TR/css3-color/#grey)).

I don't think it's super relevant, but I am using Atom 1.0 on Windows 8.

![error](https://cloud.githubusercontent.com/assets/4407518/8491579/c29d4a9e-2109-11e5-84e1-bbd84845a270.png)

**Comment by thomasjo** [comment]
Please reopen this on the [language-css repository](https://github.com/atom/language-css).
