### ISSUE TITLE
xml grammar follow brackets in comment

### ISSUE THREAD

**Issue by TermeHansen** [atom/atom#7679]
Hi All

I'm new to Atom (long time gedit user, but I think this is my new editor :) ).

I think there's a bug in the grammar for xml, when at closing bracket is seen in a comment the grammar colouring follows that?
```XML
<?xml version='1.0' encoding='UTF-8' ?>

<!DOCTYPE root [
  <!ENTITY Temp_0 '127.0' >        <!-- Target temperature -->
  <!ENTITY Temp_400 '107.55' >	<!-- [degree C]-->
  <!ENTITY Temp_600 '107.6'>	<!-- [degree C] -->
]>
```
hehe the same happens here when using the colouring possibility :) Why this issue? Gedit highlight fine passing the comment parts...

**Comment by izuzak** [comment]
Thanks for the report -- can you please reopen this at https://github.com/atom/language-xml ?
