### ISSUE TITLE
Multiple folders in projects

### ISSUE THREAD

**Issue by cameronmcefee** [atom/atom#770]
In Sublime I can have multiple folders in the side bar. If Atom already has this, I haven't been able to figure out how to do it.

![screen shot 2013-08-29 at 10 17 32 am](https://f.cloud.github.com/assets/72919/1051652/e900f5de-10ce-11e3-9429-3d6168ebc4a3.png)

**Comment by flowlo** [comment]
+1

**Comment by nanorepublica** [comment]
+1

**Comment by sebastiankliem** [comment]
:+1:

**Comment by chrisxue815** [comment]
+1

**Comment by morekid** [comment]
+1

**Comment by thedaniel** [comment]
This is already on the Atom 1.0 hit list and will be worked on, no need for more +1 comments ;)

**Comment by demisx** [comment]
@thedaniel How about linking this issue to 1.0 milestone, so everyone knows it's being planned for? I think currently it appears not to be targeted for any particular milestones and this is why there are so many +1's. Just a thought.

**Comment by privilegue** [comment]
+1 very useful feature addition indeed - this is the one thing that keeps me from using ATOM in production right now. I usually work in multiple document roots while working with interlinked projects. (multiple root folders) (e.g. APIs that have been designed to work with each other. "switching projects for this is nonsense and tedious") - So until addition I'll stick to good'ol sublime.

**Comment by maxbrunsfeld** [comment]
@atom/core I'm thinking that running `atom directory-1 directory-2` should open both directories in the same window, like Sublime does. Do you agree?

**Comment by nathansobo** [comment]
👍 Makes sense.

**Comment by InternetFarmer** [comment]
I hope to see that feature asap.👍

**Comment by jfhenriques** [comment]
+1

**Comment by camilonova** [comment]
+1

**Comment by LoicMahieu** [comment]
:+1:

**Comment by mengzyou** [comment]
+1 want this featrue.

**Comment by martamius** [comment]
Was just wishing for this. Thanks @maxbrunsfeld!

**Comment by maxbrunsfeld** [comment]
* [x] Tree view
* [x] Fuzzy finder
* [x] Git diff
* [ ] Find and Replace (`atom.workspace.scan`)
* [ ] Open on GitHub

**Comment by TreyTaylor** [comment]
https://discuss.atom.io/t/multiple-root-folders/15033?u=treytaylor

^This guy has sussed it!

**Comment by ricsdeol** [comment]
After last update are not showing unversioned files by git, example database.yml
![screenshot from 2015-02-23 13 26 03](https://cloud.githubusercontent.com/assets/719970/6331777/013cb920-bb60-11e4-82be-14e1366300d8.png)

**Comment by maxbrunsfeld** [comment]
@ricsdeol Can you open a separate issue for this, and explain a little more?

**Comment by ricsdeol** [comment]
@maxbrunsfeld Ok Thks!!!

**Comment by maxbrunsfeld** [comment]
Everyone, now that some multi-folder support is shipped, if you want to talk about how we can improve Atom's multi-folder UX, please comment on this issue: #5728.

**Comment by Tareck117** [comment]
:+1:

**Comment by 50Wliu** [comment]
:clap:

**Comment by izuzak** [comment]
:tada: Great work, @maxbrunsfeld!

**Comment by nathansobo** [comment]
:fireworks:

**Comment by kimegede** [comment]
:+1:

**Comment by kenglxn** [comment]
If all the project folders are located under a directory then to get one project folder per subdirectory do:

For example:
```
├── projects
│   ├── someProject
│   ├── anotherProject
│   └── AndSoOn
 ```
```bash
$ atom projects/*
```

![screen shot 2015-11-20 at 11 44 19](https://cloud.githubusercontent.com/assets/189395/11297975/1bc78798-8f7c-11e5-9528-5656f950758a.png)
