### ISSUE TITLE
Something is putting garbage in my package.json folder.

### ISSUE THREAD

**Issue by mark-hahn** [atom/atom#7700]
Something is frequently putting garbage json in my `package.json` file.  This mess makes editing `package.json` harder and causes me work to delete it.

In general package.json is *my* configuration file and something messing with my file really bothers me.  And storing data in an `ini` type file violates many principles including separation of concerns.

I'm posting this issue here because I have a vague memory of discussion here about putting something in `package.json`.

**Comment by batjko** [comment]
Out of interest, what kind of garbage is being added actually?

**Comment by mark-hahn** [comment]
The next time it happens I'll post it here.  It is legal json with a lot of
mentions of atom type stuff.

**Comment by izuzak** [comment]
> The next time it happens I'll post it here. 

That sounds like a good idea, @mark-hahn  -- please provide as many specific details as possible when you do (for example, which package.json file are you referring to exactly here). Until then -- I'm going to close this.

**Comment by VictorQueiroz** [comment]
It happens to me when I save my package.json with invalid JSON inside it, then I receive a error message "Invalid JSON content" and when I open the package.json file again I got a big object with alot of random keys.
