### ISSUE TITLE
Cache in wrong directory in Linux(?)

### ISSUE THREAD

**Issue by jschneider** [atom/atom#7701]
Atom seems to store its cache under ~/.config/Atom/Cache
I think that might not be the "best" or correct place. I think caches should be placed under ~/.cache/Atom

**Comment by andya9** [comment]
I too think it would be more consistent ~/.cache/atom

**Comment by JamenMarz** [comment]
+1.  (I also think it should be lower case to keep it more uniform, for some reason the capital "A" bugs me)

**Comment by andya9** [comment]
:+1: for lowercase too

**Comment by rumpelsepp** [comment]
According to XDG, I think `~/.cache/atom` makes sense: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by maxbrunsfeld** [comment]
Closing this out in favor of the more comprehensive #8281. Please subscribe to that issue for updates.
