### ISSUE TITLE
It's really slow to download the package.

### ISSUE THREAD

**Issue by haiy** [atom/atom#7703]
Hi, it's really slow to download the package from amzonaws in China, almost 20kb/s,but my bandwidth is 50M. Is it possible to build some mirrors for downloading?Thanks

**Comment by Tribex** [comment]
@haly Indeed, I experience this too. Even worse, the connection to amazonaws here is patchy. +1

**Comment by izuzak** [comment]
See https://github.com/atom/atom/issues/7575#issuecomment-117860203, and please add comments to that issue if the advice doesn't help.

**Comment by abdul** [comment]
Downloading atom or any of packages is really slow today.

**Comment by kousthubraja** [comment]
I have the same issue. Download speed is around 10KB/s on my high speed network.

**Comment by mvk** [comment]
This is a show stopper. 128MB at the speed of 50kB per second. Are we in 1999 again?
