### ISSUE TITLE
Click and drag to highlight characters on Linux

### ISSUE THREAD

**Issue by npezza93** [atom/atom#7707]
On linux, clicking and dragging doesn't highlight any characters. Double clicking a word highlights a word and a triple click highlights the line. Should you be able to click and drag to highlight character by character or not?

**Comment by JamenMarz** [comment]
I'm not sure what you mean.  I use Linux and I can click + drag to select text just fine.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by mnquintana** [comment]
Are you running Linux in a VM?

**Comment by npezza93** [comment]
I am using Atom 1.0 on Mint 17.2 as a VM. I do not have Emmet installed and I could reproduce it  using ```atom --safe```

**Comment by JamenMarz** [comment]
I'm running Atom 1.0.0 on Linux Mint 17.1, and I do not have this problem.  Perhaps it's some software separate from Atom creating this issue.

**Comment by mnquintana** [comment]
@npezza93 More specifically, are you running it in VirtualBox?

**Comment by npezza93** [comment]
@mnquintana I am running it in VirtualBox. Does VirtualBox mess up highlighting stuff?

**Comment by 50Wliu** [comment]
There's currently a few problems with Atom (more specifically, Chrome <43) wrongly detecting Virtualbox as a touchscreen interface: see #6306, #6243, and #6219 for more information.
