### ISSUE TITLE
Disabling a package doesn't completely disable it

### ISSUE THREAD

**Issue by bronson** [atom/atom#7710]
It appears that, even if a package is disabled, other packages can still reach into it and use it.  For example, if I disable vim-mode, vim-surround can still require vim-mode's files and bring its functionality into the editor.  This can lead to some pretty profound surprises.  ("but wait...  I _disabled_ vim-mode!")

I would expect that, if a package is disabled, then it's completely unavailable.

From https://github.com/gepoch/vim-surround/issues/21#issuecomment-118548512

**Comment by bronson** [comment]
Maybe `resolvePackagePath` should take enable/disable status into account?  Or is there an even lower level that could work?

**Comment by SKGrimes** [comment]
+1. To add to @bronson 's inquiry, it would be nice if packages were grouped in a `Disabled Packages` section. Where they could be found to be reenabled, or otherwise confirm they were not disabled as noted above.

**Comment by lee-dohm** [comment]
@SKGrimes please open a separate Issue for that request if you want it considered. I don't want to see a valid request lost in the shuffle :grinning:
