### ISSUE TITLE
Cursor placement when code is folded

### ISSUE THREAD

**Issue by montogeek** [atom/atom#7715]
Hi!

If you click in the first line of a folded code, the cursor is placed at the start of the line, if you type that line is moved.
The cursor should be placed at the end of the line and if you type, the line shouldn't be moved.

**Comment by twhy** [comment]
@montogeek What version of Atom are you using? I'm using Atom 1.0 on OS X 10.10.4. I try click in the first line of a folded code, and the cursor is placed at the start of that line, and if I start typing, the folded code unfolds.

**Comment by montogeek** [comment]
This is the actual behavior, when you click and the end of the line the cursor is placed at the start of the line:
![atomcodefolded](https://cloud.githubusercontent.com/assets/1002461/8527845/a317d39c-23d4-11e5-868f-c9b545f3b769.gif)

This is how it works on ST3
![sublimecodefolded](https://cloud.githubusercontent.com/assets/1002461/8527846/a318fed4-23d4-11e5-8857-239097ea3ffd.gif)

**Comment by twhy** [comment]
Submline and Textmate folds the content inside a block, but Atom folds the entire block.
I prefer the Textmate style, and I think it should be an enhancement.
<img width="390" alt="texmate-fold" src="https://cloud.githubusercontent.com/assets/7459812/8562138/113cb256-2561-11e5-9059-5ecb2955f6d6.png">
