### ISSUE TITLE
Improve Atom Flight Manual: 3.3 Package: Word Count

### ISSUE THREAD

**Issue by dalinaum** [atom/atom#7716]
Someone generate package as `wordcount`, his or her package will be shown as a deprecated package.

Because many names look like `lib/wordcount.coffee` and `keymaps/wordcount.cson`, many os use can name their packages `wordcount` and will get deprecated messages.

**Comment by lee-dohm** [comment]
This is a duplicate of atom/docs#85. Please subscribe there for updates.
