### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by amaladolcevita** [atom/atom#7720]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:34:15)
    at GutterContainer.module.exports.GutterContainer.onDidAddGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/gutter-container.js:78:27)
    at TextEditor.module.exports.TextEditor.onDidAddGutter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:509:35)
    at TextEditorPresenter.module.exports.TextEditorPresenter.observeModel (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:251:39)
    at new TextEditorPresenter (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:48:12)
    at new TextEditorComponent (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:105:24)
    at atom-text-editor.TextEditorElement.mountComponent (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:166:24)
    at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:95:14)
    at atom-pane-container.module.exports.PaneContainerElement.rootChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container-element.js:53:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
```
### Commands

```
     -2:45.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:45.1.0 editor:newline (atom-text-editor.editor.is-focused)
 20x -2:43.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:08.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 11x -2:01.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:41.9.0 editor:newline (atom-text-editor.editor.is-focused)
 11x -1:37.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:17.9.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -1:16.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:14.3.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -1:13.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:10.6.0 editor:newline (atom-text-editor.editor.is-focused)
  6x -1:10.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:08.6.0 editor:newline (atom-text-editor.editor.is-focused)
 27x -1:07.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.8.0 markdown-preview:toggle (div.markdown-preview.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 13,
    "softWrap": true
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @amaladolcevita, what were you doing when this error occured?

**Comment by amaladolcevita** [comment]
Hi Wliu! I was editing a Markdown file and went to try and view the
Markdown preview when the error occurred. It's happened a few times today
when trying to view the markdown preview.

Thanks!

**Comment by benogle** [comment]
Does the markdown file have code blocks? Can you share the markdown doc? Is this consistently reproducible? I'm wondering if this is from an editor rendered in markdown preview.

**Comment by jmarlena** [comment]
Hey, I also got this error while editing the articles below in a local instance of GitHub's help-docs (they do have some code snippets): 

[Tips for configuring a CNAME record with your DNS provider](https://github.com/github/help-docs/blob/gh-pages/_dotcom_source/articles/tips-for-configuring-a-cname-record-with-your-dns-provider.md)

[Tips for configuring an a record with your DNS provider](https://github.com/github/help-docs/blob/gh-pages/_dotcom_source/articles/tips-for-configuring-an-a-record-with-your-dns-provider.md)

I changed the title of these articles on a different branch and then launched Atom from the terminal after creating a new branch.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/7720#issuecomment-118937275. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by mikeerickson** [comment]
FWIW, I can reproduce this issue 100% of the time.

1. select `Atom -> View License`
2. I receive the typical `Not Responding` dialog 
3. Clicking `Abort` throws the error in question

![image](https://cloud.githubusercontent.com/assets/183153/22318161/3aa88f08-e32d-11e6-88a5-f31ec83eee7e.png)

**Comment by mikeerickson** [comment]
@50Wliu See above (forgot to tag you)

FWIW, I also get this `Not Responding` error whenever I close a window (quite annoying)  Just upgraded 1.13.1 today so we shall see if that improves

**Comment by 50Wliu** [comment]
Yeah, it looks from a glance like you're running an old version of Atom.  The warning message now reads `Atom will be unresponsive during the loading of very large files.`  If you see this again, please open a new issue!

**Comment by mikeerickson** [comment]
An old version? I just installed the latest release version (v1.13.1) today

**Comment by mikeerickson** [comment]
The above issue appears consistently when I select Atom -> License

**Comment by 50Wliu** [comment]
Like I said, can you please open a new issue?  This issue seemed related to markdown-preview.

**Comment by mikeerickson** [comment]
Yes, I can surely do that.  My primary reason for extended reply was to state I AM using the latest version (you stated I was using an old version).  I am not trying to get my issue reviewed under this issue

**Comment by 50Wliu** [comment]
Sorry about that part, I was a bit confused when you said that you "just upgraded", which I took as meaning that your screenshot was from a prior version.
