### ISSUE TITLE
Run Package Specs In Headless Mode

### ISSUE THREAD

**Issue by joefitzgerald** [atom/atom#7722]
I am writing a package (https://atom.io/packages/tester) that will be to testers what linter is to linters and ac+ is to autocomplete engines.

I would like to bundle a built-in tester that:

* Runs package specs for the currently active project
* Collects the results
* Displays the test results to the user, in a panel
* Highlights failed specs in-line, like linter does with lint errors

In order to do this, I need to figure out how to run atom's spec runner heedlessly, without showing the spec runner.

* The meat of the current `run-package-specs` behavior: https://github.com/atom/atom/blob/259d42d2852fea9700fbcf85cb96a0aa9ebf9865/src/browser/atom-application.coffee#L499-L511
* `apm` runs things by spawning `atom` itself: https://github.com/atom/apm/blob/f18c91d2c0f41cf5d063e5127b322a51478cd50e/src/test.coffee#L39-L65
* `atom-application` does stuff with the `test` flag: https://github.com/atom/atom/blob/259d42d2852fea9700fbcf85cb96a0aa9ebf9865/src/browser/atom-application.coffee#L90-L91, which calls back into https://github.com/atom/atom/blob/259d42d2852fea9700fbcf85cb96a0aa9ebf9865/src/browser/atom-application.coffee#L499-L511

So, @maxbrunsfeld, @nathansobo, @mnquintana et al. Is this doable? And to really stretch my luck, what are the chances of getting structured spec output (i.e. `json`?) instead of text output as the current formatter provides?

**Comment by batjko** [comment]
I'm immediately reminded of Velocity, Meteor's testing framework.
It provides an icon in the corner of the UI, that turns red if tests start failing or goes green if your latest change has resulted in all tests passing.

And if you click it, a view comes sliding out that shows all the details.

**Comment by joefitzgerald** [comment]
Bundling this into core is orthogonal to actually having a functional package that does this.
