### ISSUE TITLE
Limit to Snippet Variables?

### ISSUE THREAD

**Issue by shadowlightwolf89** [atom/atom#7723]
Is there a limit to how many variables can be in a single snippet, and if so, what is that limit? I tried to create a boilerplate snippet that had 9 variables, and it only worked for the first 6 of them. But I'm not sure if that was simply due to a mistype or not...

**Comment by 50Wliu** [comment]
Hi @shadowlightwolf89, can you please move this over to [atom/snippets](https://github.com/atom/snippets) and then share the snippet in question?  Thanks.

**Comment by mnquintana** [comment]
This issue was moved to atom/snippets#158
