### ISSUE TITLE
Find/replace not working with PHP vars (whole word)

### ISSUE THREAD

**Issue by Sogl** [atom/atom#7724]
Hi!

I use Atom 1.0 on Windows 7 x64.

Whole word option is enabled.
If I try to replace some variables in PHP with `$`, replace doesn't work. Works only without `$`. 
Also find don't working with `$`.

**Comment by kubetz** [comment]
Don't you have Regex option turned on? Because without Regex it seems to be working for me, but with Regex it won't work as you may expect as $ is a special symbol matching the end of a string.

**Comment by Sogl** [comment]
>Don't you have Regex option turned on?
Nope.

**Comment by kubetz** [comment]
1) When you run atom in safe mode using `atom --safe` are you still getting this strange behavior?
2) Can you show example when this is hapenning? I did simple search / replace for `$variable` and it worked for me :confused: .

**Comment by Sogl** [comment]
>1) When you run atom in safe mode using atom --safe are you still getting this strange behavior?

How to do this on Windows?
If I type "atom" im command line, I see error:
```
"atom" is not an internal or external
command, operable program or batch file.
```

Maybe some PATH missing?

**Comment by kubetz** [comment]
Strange, Atom installer should add the installation directory to PATH environment variable.

Go to `C:\Users\<name>\AppData\Local\atom\app-1.0.0`. There should be the executable and you should be able to run `atom --safe`.

**Comment by Sogl** [comment]
>Go to C:\Users\<name>\AppData\Local\atom\app-1.0.0. There should be the executable and you should be able to run atom --safe.

Same in safe mode.

See:
![atom](https://cloud.githubusercontent.com/assets/7556290/8514223/39c5c194-23cd-11e5-8e02-804099ca27c1.png)

**Comment by kubetz** [comment]
Eh, now I realized that this is the wrong repo :blush:. Can you please reopen this issue in https://github.com/atom/find-and-replace before we continue?

**Comment by Sogl** [comment]
>Can you please reopen this issue in https://github.com/atom/find-and-replace before we continue?

Done.

p.s. I didn't think that the search and replace function in Atom has its own repository.
So I created an issue here :relaxed:
