### ISSUE TITLE
.atom-text-editor class not working

### ISSUE THREAD

**Issue by Siecje** [atom/atom#7725]
I would like to use F1 to toggle the tree.

I am currently using ```.editor``` which is deprecated in favour of ```.atom-text-editor```. However the new class doesn't seem to work.

keymap.cson
```
'.editor':
  'f1': 'tree-view:toggle'

'.atom-workspace':
  'f1': 'tree-view:toggle'
```

**Comment by 50Wliu** [comment]
`atom-text-editor` and `atom-workspace` are custom elements and not classes, so you should reference them as `'atom-text-editor':` and `'atom-workspace':` without the `.` class prefix.
