### ISSUE TITLE
rename in file tree,  old-file remains

### ISSUE THREAD

**Issue by Bruce313** [atom/atom#7730]
hi, I`m new.

when I rename file in file tree with GUI while this file  opened in tabs, the tab of this file remain opened, and the name did not changed.
Is this designed to be so or an bug?

And, delete file in file tree and click "Move to trash" did not work for me.
PS.  I install atom on centos 7 using atom.rpm with lastest version.

**Comment by 50Wliu** [comment]
Hi @Bruce313, can you please move this to [atom/tree-view](https://github.com/atom/tree-view) and then close this issue?  Thanks!
