### ISSUE TITLE
The async repositoryForDirectory calls directory.getRealPathSync()

### ISSUE THREAD

**Issue by mostafaeweda** [atom/atom#7735]
There should be an async `getRealPath()` in https://github.com/atom/node-pathwatcher/blob/master/src/directory.coffee and that be called here instead.

https://github.com/atom/atom/blob/645139f452a7a261a77c6413ec4c1fe9cfee6cf5/src/project.coffee#L144

This doesn't work for the remote development use case, because you can't get the real path of a directory synchronously (could be a symlink).

/cc @maxbrunsfeld @bolinfest

**Comment by maxbrunsfeld** [comment]
:+1: I agree. Would you like to submit a pathwatcher PR adding that method and bumping the minor version number? You could then do a PR on atom/atom in which you upgrade pathwatcher and use `::getRealPath()` instead of `::getRealPathSync()`.
