### ISSUE TITLE
Feature Request: Pressing `esc` on multiple cursors returns you to original cursor location.

### ISSUE THREAD

**Issue by colllin** [atom/atom#7738]
After selecting multiple words by pressing `cmd-d` multiple times, then pressing `esc` key to go back to a single cursor, it seems to place the single cursor at the position of the last cursor that was added.  I would like it to place the single cursor at the original selection.

Explanation:
I got used to Sublime positioning the single cursor at the original cursor location.  At first, I thought it was an arbitrary decision and that I would adjust to atom's way of doing it.  Now I've decided that it's not entirely subjective.  In many cases, my original cursor was intentionally placed at the original position, and that's where I would like it to return to.  For example, maybe I was editing something in-line and thought that this particular word (variable name) I was editing should be edited in a few places at the same time.  After doing this, I would like to return to my original train of thought - editing that line that I was on before creating multiple selections.  I would also think that in any cases where I didn't intentionally place my cursor on a particular instance, the decision is arbitrary whether it takes me to the original or final cursor upon pressing `esc`, so this might be a safe change to make for all use cases.  At least an option for altering this behavior would be much-appreciated.

**Comment by jazzdragon** [comment]
+1

**Comment by colllin** [comment]
:clap: Thank you @lpommers !

**Comment by arxpoetica** [comment]
Just for the sake of a paper trail (honestly not trying to be obtuse/cause a riot), I'm confused about the changes made for the sake of "matching" Sublime Text. That text editor (as far as I can tell) doesn't behave as described above. Here's a fresh install of SublimeText 3 and multi select behavior:

![Different than described.](http://g.recordit.co/jx0vfTz9Jy.gif)

Again, not trying to make a stink. I'm satisfied with the help I've received on issue #9417, but thought this might help anyone else who might be confused.

**Comment by colllin** [comment]
So you found a bug / edge case in sublime. 




I made more meaningful arguments than "do what sublime does". Sublime's typical use case was only inspiration. Can you explain why another way might be better?

**Comment by arxpoetica** [comment]
Hi @colllin, nice to meet you. Not trying to start a spat. Thanks. :)

**Comment by lpommers** [comment]
yeah, from my own perspective - it had less to do with matching Sublime as it just seemed like good user-experience/ use case. I agree with @colllin that the first cursor is placed with certainty/intention and seems like an appropriate place to return to.
> In many cases, my original cursor was intentionally placed at the original position, and that's where I would like it to return to
