### ISSUE TITLE
Uncaught exception round up

### ISSUE THREAD

**Issue by kevinsawicki** [atom/atom#7740]
I took a look at the reported [uncaught exceptions](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Aatom+is%3Apublic+label%3Auncaught-exception) and broke them down into a couple categories.
# Add Guards

_These are ones that looked like they weren't guarding adequately for different inputs that could happen. These appear to the easiest to fix at first glance._
## Core
- [x] https://github.com/atom/atom/issues/4957
- [x] https://github.com/atom/atom/issues/5468
- [x] https://github.com/atom/atom/issues/5593
- [x] https://github.com/atom/atom/issues/6587
- [ ] https://github.com/atom/atom/issues/7282
- [x] https://github.com/atom/atom/issues/7714
## Packages
- [x] https://github.com/atom/autocomplete-plus/issues/353
- [x] https://github.com/atom/autocomplete-plus/issues/475
- [x] https://github.com/atom/autocomplete-plus/issues/480 (affecting 555 people)
- [x] https://github.com/atom/autocomplete-plus/issues/488
- [x] https://github.com/atom/find-and-replace/issues/402
- [ ] https://github.com/atom/fuzzy-finder/issues/86
- [ ] https://github.com/atom/fuzzy-finder/issues/110
- [x] https://github.com/atom/encoding-selector/issues/23
- [ ] https://github.com/atom/markdown-preview/issues/264
- [x] https://github.com/atom/markdown-preview/issues/270
- [x] https://github.com/atom/notifications/issues/42
- [x] https://github.com/atom/notifications/issues/79
- [x] https://github.com/atom/settings-view/issues/536
- [x] https://github.com/atom/tabs/issues/151
- [ ] https://github.com/atom/tabs/issues/183 (affecting 535 people)
# Text Editor

_These seem to originate from either the model or view for the text editor._
## Core
- [ ] https://github.com/atom/atom/issues/5311
- [ ] https://github.com/atom/atom/issues/5905
- [ ] https://github.com/atom/atom/issues/5997
- [ ] https://github.com/atom/atom/issues/6117
- [ ] https://github.com/atom/atom/issues/6118
- [x] https://github.com/atom/atom/issues/6119
- [ ] https://github.com/atom/atom/issues/6831
- [ ] https://github.com/atom/atom/issues/6973
- [ ] https://github.com/atom/atom/issues/7063
- [ ] https://github.com/atom/atom/issues/7070
- [ ] https://github.com/atom/atom/issues/7198
- [ ] https://github.com/atom/atom/issues/7248
- [ ] https://github.com/atom/atom/issues/7465
- [ ] https://github.com/atom/atom/issues/7582
- [ ] https://github.com/atom/atom/issues/7720
## Packages
- [ ] https://github.com/atom/bracket-matcher/issues/119
- [ ] https://github.com/atom/bracket-matcher/issues/136
- [ ] https://github.com/atom/bracket-matcher/issues/144
- [ ] https://github.com/atom/find-and-replace/issues/343
- [ ] https://github.com/atom/git-diff/issues/57
- [ ] https://github.com/atom/tabs/issues/122
- [ ] https://github.com/atom/whitespace/issues/71
# Text Buffer

_These appear to originate from errors within the text-buffer repository._
## Core
- [ ] https://github.com/atom/atom/issues/6753
- [x] https://github.com/atom/atom/issues/7352
- [x] https://github.com/atom/atom/issues/7398
- [ ] https://github.com/atom/atom/issues/7409
- [x] https://github.com/atom/atom/issues/7672 (affecting 140 people)
- [x] https://github.com/atom/atom/issues/7678
## Packages
- [ ] https://github.com/atom/atom-dark-syntax/issues/11
- [ ] https://github.com/atom/bracket-matcher/issues/142
- [x] https://github.com/atom/go-to-line/issues/22 (affecting 140 people)
- [x] https://github.com/atom/go-to-line/issues/23
# Process/Task

_These appear to be from spawning processes or tasks_
## Core
- [x] https://github.com/atom/atom/issues/4775
- [x] https://github.com/atom/atom/issues/7459 (affecting 600 people)
- [ ] https://github.com/atom/atom/issues/7594
## Packages
- [x] https://github.com/atom/tree-view/issues/495
# 3rd party packages

_These appear to be from third-party packages and not fixable from within Atom. These might be closeable with just a comment._
- [x] https://github.com/atom/atom/issues/7721
- [ ] https://github.com/atom/status-bar/issues/86
# Invalid cases

_These appear to be errors from corrupted models and other conditions that should never happen._
- [ ] https://github.com/atom/atom/issues/6235
- [ ] https://github.com/atom/snippets/issues/103
- [ ] https://github.com/atom/whitespace/issues/79
# Require errors

_These appear to be errors from calling require._
## Core
- [x] https://github.com/atom/atom/issues/6276
- [x] https://github.com/atom/atom/issues/7591
## Packages
- [x] https://github.com/atom/tabs/issues/192
- [x] https://github.com/atom/tree-view/issues/399
# File I/O

_These appear to be errors from reading or writing files._
## Core
- [ ] https://github.com/atom/atom/issues/2539
- [x] https://github.com/atom/atom/issues/4467
- [x] https://github.com/atom/atom/issues/5307
- [x] https://github.com/atom/atom/issues/5640
- [ ] https://github.com/atom/atom/issues/5999
- [x] https://github.com/atom/atom/issues/6046
- [ ] https://github.com/atom/atom/issues/6140
- [x] https://github.com/atom/atom/issues/6348
- [x] https://github.com/atom/atom/issues/6799
- [x] https://github.com/atom/atom/issues/6838
- [ ] https://github.com/atom/atom/issues/7133
- [x] https://github.com/atom/atom/issues/7321
- [x] https://github.com/atom/atom/issues/7651
## Packages
- [x] https://github.com/atom/autosave/issues/29
- [x] https://github.com/atom/autosave/issues/33
- [x] https://github.com/atom/autosave/issues/36
- [ ] https://github.com/atom/settings-view/issues/523
- [x] https://github.com/atom/tree-view/issues/412
- [x] https://github.com/atom/tree-view/issues/416
- [x] https://github.com/atom/tree-view/issues/419
- [x] https://github.com/atom/tree-view/issues/425
- [x] https://github.com/atom/tree-view/issues/436
- [x] https://github.com/atom/tree-view/issues/448
- [x] https://github.com/atom/tree-view/issues/465
- [x] https://github.com/atom/tree-view/issues/470
- [x] https://github.com/atom/tree-view/issues/409
# No Idea

_These are real head scratchers. Any insight appreciated._
## Core
- [ ] https://github.com/atom/atom/issues/4792
- [ ] https://github.com/atom/atom/issues/6089
- [ ] https://github.com/atom/atom/issues/6102
- [ ] https://github.com/atom/atom/issues/6632
- [ ] https://github.com/atom/atom/issues/7155
- [ ] https://github.com/atom/atom/issues/7203
- [ ] https://github.com/atom/atom/issues/7210
- [ ] https://github.com/atom/atom/issues/7307
- [ ] https://github.com/atom/atom/issues/7399
## Packages
- [x] https://github.com/atom/autocomplete-atom-api/issues/6
- [x] https://github.com/atom/autocomplete-atom-api/issues/7
- [ ] https://github.com/atom/command-palette/issues/47
- [ ] https://github.com/atom/markdown-preview/issues/236
- [ ] https://github.com/atom/symbols-view/issues/110
- [ ] https://github.com/atom/tabs/issues/108
- [ ] https://github.com/atom/tree-view/issues/408

**Comment by kevinsawicki** [comment]
Feel free to edit the above list, it isn't inclusive of all the uncaught exceptions, just a first pass at the most recent ones.

**Comment by kevinsawicki** [comment]
Added number of people impacted to a few of these by pulling from bugsnag

**Comment by 50Wliu** [comment]
#6210 should probably be added, but I'm not sure what category to put it under (though there haven't been any reports of it lately, so hopefully it's been fixed?).

**Comment by kubetz** [comment]
#7210 (No Idea → Core) seems to be caused by the V8 which has limits for single string allocation.

More details are [here](https://github.com/atom/atom/issues/7417#issuecomment-115455506).

**Comment by swrobel** [comment]
Any progress on the Theme-related issue #7282? It just struck me and it's rather frustrating.
