### ISSUE TITLE
Fedora 22 installation error

### ISSUE THREAD

**Issue by LittleBuster** [atom/atom#7743]
After running installation of RPM:

http://s019.radikal.ru/i639/1507/94/69097292ed43.png

**Comment by mnquintana** [comment]
It looks like you have Python 3 installed, which can't be used to build Atom. Did you follow the steps in [the Requirements section of the build instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#requirements)?

**Comment by paulcbetts** [comment]
@mnquintana Should he need Python 2.x in order to just install the RPM though?

**Comment by LittleBuster** [comment]
Python2 and Python3 installed, "npm config set python /usr/bin/python2 -g" writed...

**Comment by LittleBuster** [comment]
I open your RMP from site by archiver and manually moving bin and share folders to my system. Atom is working.
But problem with RPM installation not solved.

**Comment by immanetize** [comment]
I can't reproduce this with either dnf-2 or dnf-3 (dnf-1.0.1-2.fc22.noarch, atom-1.0.0-0.1.fc21.x86_64).

@LittleBuster is your system up to date? Does `rpm -V $(rpm -qa *dnf*)` return anything?

**Comment by LittleBuster** [comment]
nothing

**Comment by immanetize** [comment]
On Wed, Jul 8, 2015 at 12:56 PM, Sergey Denisov <notifications@github.com>
wrote:

> nothing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/7743#issuecomment-119677690>.
>

Nothing means that all the RPMs with "*dnf*" in the name have been
successfully verified, that's good.  Make sure your system is up to date
and try installing the atom RPM again.  The spec does not call any python,
so the error doesn't make sense to me.

--Pete

**Comment by LittleBuster** [comment]
My system is up to date!
