### ISSUE TITLE
Keyboard shortcut for switching between open windows on Mac OS X (CMD+`)

### ISSUE THREAD

**Issue by abdobelk** [atom/atom#7749]
Hello,
On Mac OS X, the default keyboard shortcut to switch between open windows in the app is [CMD+`], I tried this shortcut on a bunch of apps (Safari, Google Chrome..) and it works, but on Atom it doesn't.

Can you please add this functionality to Atom on Mac OS X?

Thanks

**Comment by mnquintana** [comment]
This works for me on OS X 10.10.4. What version of Atom and OS X are you using? Can you reproduce this in safe mode? (`atom --safe`) My guess is that you have a community package installed that's overriding the <kbd>Cmd-`</kbd> keyboard shortcut.

**Comment by darezik** [comment]
Can confirm, it works for me too on OS X10.10.4,with atom 1.0.0.

**Comment by izuzak** [comment]
@abdobelk Also, when you hit <kbd>cmd-`</kbd> -- what does happen in Atom if switching windows doesn't happen? Does Atom do anything? 

Can you share a screenshot of the [keybinding resolver](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings) when you hit <kbd>cmd-`</kbd> ?

**Comment by utiq** [comment]
I have the same issue, this happen:
![screen shot 2015-07-08 at 12 35 13 am](https://cloud.githubusercontent.com/assets/1144196/8563126/3b41ed12-2509-11e5-805e-e4c256a21486.png)

**Comment by izuzak** [comment]
@utiq Sorry for not replying to this sooner. In my previous comment I asked if you can share a screenshot of the [keybinding resolver](https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings) when you hit <kbd>cmd-`</kbd>. Could you provide such a screenshot? Also, can you let us know which input language you're using (US or something else)?

**Comment by abdobelk** [comment]
Hello,
@izuzak, it wasn't working back then when I reported this issue, but now it's working, I didn't add/remove any packages, I'm on Mac OS X 10.10.4 using Atom 1.0.3.
Thank you for checking, I'm sorry for the late answer
