### ISSUE TITLE
Windows: With focus in editor window 'Alt' key doesn't toggle Menu bar

### ISSUE THREAD

**Issue by dougireton** [atom/atom#7750]
Windows: With focus in editor window 'Alt' key doesn't toggle Menu bar. With focus in the file browser pane, 'Alt' key *does* toggle the menu bar. This bug is new to Atom 1.0.

**Comment by moimael** [comment]
Same in Linux, works also on the settings page, but not elsewhere.

**Comment by ankitaggarwal011** [comment]
I am using Atom pre-built zip package on Windows 7. I am able to toggle menu bar after selecting Toggle Menu Bar option in view.

I couldn't understand your issue. I am missing something?

**Comment by moimael** [comment]
I use RPM package. Toggle work when you are in certain part of the app but not always. For example when you are on a code file, are you able to toggle menu bar ? I can toggle menu bar only when i am on the settings page or focusing the file browser sidebar. Try to focus code editor, it won't work.

**Comment by ankitaggarwal011** [comment]
I am able to satisfactorily toggle the menubar in all parts of the application in all cases without any problem.
I don't have any third-party packages installed.

**Comment by moimael** [comment]
Disabling all third party package solved the problem, nice intuition :) I will test them one by one to find the culprit. One package must intercept alt keypress before atom.

**Comment by moimael** [comment]
Ok the linter package is the culprit, so a lot of people must have the same issue

**Comment by ankitaggarwal011** [comment]
Great, problem solved :+1:. If the OP can confirm the same, I guess the issue could be closed.

**Comment by dougireton** [comment]
I'll check this morning.

On Tuesday, July 7, 2015, Ankit Aggarwal <notifications@github.com> wrote:

> Great, problem solved [image: :+1:]. If the OP can confirm the same, I
> guess the issue could be closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/7750#issuecomment-119180398>.
>


-- 

Thanks,

Doug Ireton

**Comment by dougireton** [comment]
This is a bug in the linter plugin: https://github.com/AtomLinter/Linter/issues/648.
