### ISSUE TITLE
On restart, Project folder persists in Tree view even after it is removed before closing application.

### ISSUE THREAD

**Issue by ankitaggarwal011** [atom/atom#7756]
**Configuration**
* System: Windows 7 (x64).
* Atom: 1.0.0 (Pre-built zipped package).
* No third-party packages.
* The same issue happens with atom --safe (Safe mode).

**Steps to reproduce**
* Open any project folder in Atom.
* Remove the project folder from tree view.
* Close the Atom application.
* Reopen the Atom application.

The removed Project folder in the Tree view persists even after it was removed before the Atom application was closed.

Since, after the project is removed from tree view, it is not supposed to come up again without specifying, I doubt that this is by design.

Can anybody confirm this behavior? Thanks!

**Comment by mnquintana** [comment]
Would you mind closing this and reopening on https://github.com/atom/tree-view?

**Comment by ankitaggarwal011** [comment]
Sure, sorry, I wasn't aware that the tree-view is built into atom with a separate repository. I will open the same issue there and close this open.
