### ISSUE TITLE
Coping folder content to one of its sub-folders

### ISSUE THREAD

**Issue by mhsallam** [atom/atom#7759]
In the Files Tree View, when coping folder "A" into one of its sub-folders "A/B"; Atom gets into an infinity loop in which the same content  of the main folder "A" will be duplicated in the target sub-folder "A/B/A" (the first time is as desired) then again copies itself into the newly created sub-sub-folder (A/B/A/"B").. and goes on and on...

E.g: Coping folder FONTS/ into FONTS/FA will produce: "FONTS/FA/FONTS/FA/FONTS/FA/FONTS/FA/FONTS/FA/..." and will not stop until you close Atom.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/tree-view?
