### ISSUE TITLE
Preserve CSON formatting

### ISSUE THREAD

**Issue by smaili** [atom/atom#7763]
This one may be a long shot, but I'd still like to mention it.  Is there any way to preserve the formatting of a CSON configuration file whenever Atom needs to write and save to it?

The reason I mention it, is because I'm a big fan of having comments in config files so I know what each config does, and it also helps with organization and readability.

Say this is my `config.cson`

``` cson
#
# Config
#

'*':
    # --- MAIN ---

    # WELCOME
    welcome:
        showOnStartup: false

    # CORE
    core:
        disabledPackages: [
            'autocomplete-plus'
            'wrap-guide'
        ]
        themes: [
            'one-dark-ui'
            'solarized-dark-syntax'
        ]

    # EDITOR
    editor:
        invisibles: {}
        tabLength: 4


    # --- PACKAGES ---

    # REPORTING
    'exception-reporting':
        userId: 'ddaafd07-dffd-b252-48db-612909a97759'

    # BRACKET MATCHER
    'bracket-matcher':
        autocompleteBrackets: false
        autocompleteSmartQuotes: false

    # WHITESPACE
    whitespace:
        ensureSingleTrailingNewline: false
```

Once Atom saves it, it's changed to this:

``` cson
"*":
  welcome:
    showOnStartup: false
  core:
    disabledPackages: [
      "autocomplete-plus"
      "wrap-guide"
    ]
    themes: [
      "one-dark-ui"
      "solarized-dark-syntax"
    ]
  editor:
    invisibles: {}
    tabLength: 4
  "exception-reporting":
    userId: "ddaafd07-dffd-b252-48db-612909a97759"
  "bracket-matcher":
    autocompleteBrackets: false
    autocompleteSmartQuotes: false
  whitespace:
    ensureSingleTrailingNewline: false
```

I completely understand the reason for why it happens, which is why I said it's a long shot.  But I think one of the nice things about having our own custom configs is being able to organize it the way we want, so if there could be any way to preserve it that would be great.

**Comment by martinheidegger** [comment]
+1

**Comment by nycdotnet** [comment]
+1
Comments are always removed - this is quite frustrating when trying to switch back and forth between values - it'd be easier to comment/uncomment the lines.

**Comment by danielbayley** [comment]
+1

**Comment by art-solopov** [comment]
+1

**Comment by danielbayley** [comment]
Atom uses _[season](https://github.com/atom/season)_ to handle CSON, (which in turn uses [_cson-parser_](https://github.com/groupon/cson-parser))… so maybe this issue should be raised upstream in one of those repos.
