### ISSUE TITLE
Overriding core keybindings

### ISSUE THREAD

**Issue by msmaili** [atom/atom#7766]
I'm trying to add the following keybindings but they don't seem to work:

```
'atom-workspace atom-text-editor:not([mini])':
    'cmd-T': 'application:new-file'
    'cmd-N': 'application:new-window'
```

According to this answer - https://discuss.atom.io/t/overriding-core-keybindings/10180/7, it may be related to the weight of the selector but I'm not really sure what specificity can help make it stronger.

On a side note, since this is CSS-inspired, what about adding the `!important` keyword?  That way it will override no matter how weak the specificity of the selector is.

**Comment by izuzak** [comment]
Can you provide a screenshot of the keybinding resolver when you hit `cmd-T`?

https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings

I just tried using those in my keymap.cson and pressing `cmd-T` opens a new file as expected. The other keybinding works as well. Also, please provide more information with you reports, as suggested here:

https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues

**Comment by msmaili** [comment]
You're absolutely right, it works!  I didn't realize my keymap was using uppercase characters.

Closing.
