### ISSUE TITLE
How to use Split Up/Down/Left/Right Commands?

### ISSUE THREAD

**Issue by bobber205** [atom/atom#7771]
![ingest - atom 2015-07-07 13-38-31](https://cloud.githubusercontent.com/assets/5841107/8556685/77f3660c-24ad-11e5-9bdd-a0c8b579bbc8.png)

I can't for the life of me reliably trigger this. At all. I assume this means to press Command + K + Right arrow at the same time? That's what feels natural to me anyway. Plus other arrow keys for other split orientations.

I can spam the combination and it works most of the time.

What's up?

**Comment by mark-hahn** [comment]
>  I assume this means to press Command + K + Right arrow at the same time?

No.  It is one and then the other.

**Comment by mnquintana** [comment]
> No.  It is one and then the other.

Yup. Also make sure you let go completely of the first keyboard combination for pressing the next one (ie. don't hold down <kbd>Cmd</kbd> for both).

**Comment by bobber205** [comment]
omg that's totally it. Thanks! 
(How was I supposed to know this btw)

**Comment by 50Wliu** [comment]
@bobber205 there's actually a space between the `K` and the right arrow, though it is *really* hard to notice.
#2594 contains a lot of discussion about this.
