### ISSUE TITLE
Subpixel antialiasing isn't consistently applied to all text in document

### ISSUE THREAD

**Issue by w1res** [atom/atom#7772]
* Using Atom 1.0.0.
* Using Windows 7.
* The effect seems to happen on both of my monitors:
 * Primary monitor is 1920 x 1200 resolution.
 * Secondary monitor is 1280 x 1024 resolution.
* Using One Light for both UI Theme and Syntax Theme, but it also happens if I use Atom Light on both.
* Running atom --safe didn't make any difference (still has the same alternating blurry).

It seems that when editing some files, that subpixel antialiasing works for a couple lines, then doesn't work for a couple lines, then works for a few lines, then doesn't ...

![capture](https://cloud.githubusercontent.com/assets/2823875/8557202/d571b2b8-24c9-11e5-99bf-943a2534d034.PNG)

When you zoom in, you can see that lines 34-36 are working properly, but then line 37 doesn't have subpixel antialiasing applied.

![zoom](https://cloud.githubusercontent.com/assets/2823875/8557209/e045b1e4-24c9-11e5-9091-ad139468970c.PNG)

The strange thing is that if I make a document of all "a" characters, for example, it *all* looks blurry, but at least it is consistent.

![all_blurry](https://cloud.githubusercontent.com/assets/2823875/8557246/0fb76292-24ca-11e5-8ea5-ba900a1b890b.PNG)

If I fill the document with all "0" characters, it looks like the top few lines are blurry, but the rest renders correctly.

**Comment by 50Wliu** [comment]
@as-cii this seems like your territory :).

**Comment by as-cii** [comment]
Hey @w1res, thanks for reporting this issue.

Other Windows users have been experiencing a similar problem (https://github.com/atom/atom/issues/3869#issuecomment-116783518) but found out it was related to the DPI settings. Would you be willing to check that setting out in your Windows configuration?

Thank you!

**Comment by w1res** [comment]
I'm getting a value of `1` for `window.devicePixelValue` (from within the Atom console).

I haven't read too much about using Atom (so this might not be the right way to change it), but I added `window.devicePixelRatio = 1.5;` to `init.coffee` and restarted Atom. It didn't seem to make any change in appearance. Is that the right place to change it?

**Comment by as-cii** [comment]
Thanks @w1res, sorry for letting you wait so long! :pray: 

> I'm getting a value of 1 for window.devicePixelValue (from within the Atom console).

I assume you are talking about `window.devicePixelRatio` here. If yes, then DPI settings are definitely not the culprit here but it rather seems like something is screwing up subpixel anti-aliasing. I am starting to think this may actually be caused by highlight decorations.

Have you been able to reproduce this since you first reported? I have just noticed you had the `spell-check` package enabled in the second screenshot you posted. Could you try disabling it and see if it helps in a similar document (e.g. a document made of `a` characters only)?

**Comment by 50Wliu** [comment]
I may be hitting this as well; will try to write up some repro steps later on.

**Comment by w1res** [comment]
@as-cii I disabled off spell-check and now everything looks uniformly sharp across all lines. It seems like you were correct in guessing that it might be related.

In fact, I can have the Settings open in one tab, and the file open in the other, and when I enable/disable (and go back and forth between the tabs), I can see the issue return, and then go away.
