### ISSUE TITLE
Hitting Enter on html attribute doesent make autocomplete.

### ISSUE THREAD

**Issue by abdelouahabb** [atom/atom#7775]
When I try to choose the html attribute, I have to click on it, and not hit Tab or Enter.

Other editors do that by just hitting Enter.

![sans titre](https://cloud.githubusercontent.com/assets/2527234/8558535/bb6ffac2-24fc-11e5-9a29-5064525502a8.png)

**Comment by thomasjo** [comment]
Are you able to reproduce this in safe mode? `atom --safe`
I'm reasonably sure one of your installed packages is interfering, possibly `emmet` if you have that installed.

In addition, after you toggle the *Keybinding Resolver*, what it shown when you press <kbd>enter</kbd> when the autocompletion list is active like in your screenshot?

**Comment by batjko** [comment]
Works fine for me, using tab (Win8, 64bit, v1.0.0):
![http://i.imgur.com/K231kxQ.gif](http://i.imgur.com/K231kxQ.gif)

**Comment by mnquintana** [comment]
This issue was moved to atom/autocomplete-plus#527

**Comment by abdelouahabb** [comment]
the problem was from `emmet`, using `safe mode` worked, so I need to rebind the keys.

Thank you.
