### ISSUE TITLE
Fuzzy finder should prefer changed files when other factors are equal

### ISSUE THREAD

**Issue by Valve** [atom/atom#7784]
When searching for a file, fuzzy finder returns a list of suggestions.
When all factors from 2 files match, fuzzy finder should always return the file with recent edits/uncommited changes first.

**Comment by thomasjo** [comment]
Please re-open this on the [fuzzy-finder repo](https://github.com/atom/fuzzy-finder/issues).

**Comment by Valve** [comment]
Done, thanks.

https://github.com/atom/fuzzy-finder/issues/116
