### ISSUE TITLE
Opening single file when Atom is not open – existing projects and open files are closed/removed

### ISSUE THREAD

**Issue by jancborchardt** [atom/atom#7786]
1. Have some project folders in the sidebar and some open files. When you start Atom by itself, these are always restored.
2. Close Atom
3. Open a single txt file

**Expected:** The project folders and open files from last time are restored, and the new single file is open in a new, now focused tab. Exactly what happens when you open a single file while Atom is already open.

**What actually happens:** The project folders are wiped, as are the open files. The sidebar just shows the parent folder tree of the newly opened file, and only a single tab for said file.

**Comment by thomasjo** [comment]
The expected behavior is somewhat confusing in my opinion, but we could perhaps implement this via a command line argument? `--reuse-last-project`, `--no-project` or any other variant.

/cc @atom/feedback

**Comment by jancborchardt** [comment]
@thomasjo why is the expected behavior confusing, can you elaborate? It certainly is more confusing when your last used files and projects are simply gone. ;)
Regardless if there’s going to be an option or whatnot, I’m talking about changing the default.

**Comment by csholmq** [comment]
+1

**Comment by oczkers** [comment]
+1

**Comment by adiachenko** [comment]
+1. This behavior is too weird. Please, see how Sublime does it. 

When you open a single file, you should see this exact file, not a whole new project instantiated in the current directory.

**Comment by nabaxo** [comment]
+1

**Comment by adiachenko** [comment]
Wow, I thought this has been fixed long ago.

Even Visual Studio Code is smart enough to open file in the current workspace (unless there is `.vscode` directory in the root). And it's built with your own damn framework. The irony, heh.

P.S. Yes, I moved away from Atom and the main deal breaker besides performance issues was this utterly convoluted behavior.

**Comment by miko007** [comment]
the expected behavior is pretty much the actual behavior. the issue should be closed.

**Comment by jancborchardt** [comment]
I can confirm this is fixed at least with the current version (1.19.3). Thanks for the fix whoever did it! :)

@adiachenko no open source developer (or any human) likes to read sarcastic remarks aimed at their work, and it usually doesn’t help fixing the issue at all. Your last comment was unnecessary.

**Comment by Sachka** [comment]
@jancborchardt How is this fixed? I currently use version 1.21.0 and my projects are wiped every time I open a different file with atom closed.

**Comment by jancborchardt** [comment]
@Sachka I can only state that it seems fixed from my view. I can’t reproduce the issue anymore on my setup (Ubuntu 16.04, Atom 1.19.3). If you can still reproduce, best check if it’s reproducible and then submit more info.

**Comment by Ben3eeE** [comment]
@Sachka There is a setting for this in the `settings-view` that we added recently. You can find it under the `Core` tab called `Restore Previous Windows On Start`. With this set to `Always` the previous windows should be restored.

If this is not working for you then please open a new issue and completely fill out the required issue template.

---

@jancborchardt Thank you :bowing_man:

**Comment by Sachka** [comment]
@Ben3eeE Thanks, it fixes this issue when selecting "Always"
