### ISSUE TITLE
only keep tab open if editing

### ISSUE THREAD

**Issue by masedesign** [atom/atom#7788]
One of the things I liked about sublime is that you can click around files in the sidebar without accumulating a ton of tabs. This is especially helpful if you're looking for something and are not quite sure where it might be. Unless you double click the file in the left pane or start editing the file, it closes it when you click another file. Almost like a quick preview, sort of. Is this functionality built in or might there be a package for this?

**Comment by mnquintana** [comment]
Atom already has this feature - open Settings > Packages > tabs > enable Use Preview Tabs
