### ISSUE TITLE
Weight Capitol Letters More in Fuzzy Search

### ISSUE THREAD

**Issue by steveoh** [atom/atom#7791]
It seems that Sublime and possibly the chrome dev tools give a higher priority to capitol letters when searching. This makes finding the file `MyFileName.ext` much easier since you can type `MFN` and not be bothered with having to spell it out. I think this is a great productivity feature since with current atom, i have to try to spell out the file the way it is which introduces many more errors.

**Comment by lee-dohm** [comment]
Would you mind moving this to the [fuzzaldrin package](https://github.com/atom/fuzzaldrin)? That is where the algorithm for the fuzzy searching is defined?

Thanks.

**Comment by steveoh** [comment]
thanks, the modularity makes that type of discovery difficult.

**Comment by lee-dohm** [comment]
:bow: I understand completely. It took me a while to figure out where most things were too.
