### ISSUE TITLE
Not able to install atom on windows 8.1

### ISSUE THREAD

**Issue by kishanj918** [atom/atom#7792]
![screenshot 5](https://cloud.githubusercontent.com/assets/3994657/8573844/8a057948-2548-11e5-91d3-cd0069a06a18.png)

**Comment by paulcbetts** [comment]
This is usually caused by crappy antivirus

**Comment by batjko** [comment]
In other words, @kishanj918 Do you have any anti-virus software running, and if so, can you disable it temporarily, before trying the installer again?

**Comment by kishanj918** [comment]
@paulcbetts @batjko  thank you guys.. You are the saviour.. :)
