### ISSUE TITLE
`BufferedProcess` doesn't yield an error running a not existing command on Windows

### ISSUE THREAD

**Issue by b52** [atom/atom#7793]
According to this [spec](https://github.com/atom/atom/blob/master/spec/buffered-process-spec.coffee#L15-L31) `BufferedProcess` should call the handler defined using `onWillThrowError` if the spawned command doesn't exist. However, this is not the case on my Windows box.

Since the command is spawned in a sub-shell `cmd.exe` (which is an aweful default setup, this should be optional), the handler is never called but the default error message of `cmd.exe` is logged on `stderr` and the process (in this case `cmd.exe`) exits with status code `1`. This means the above mentioned spec should fail running on Windows, which seems to me like a bug in `BufferedProcess`.

**Comment by b52** [comment]
I just verified by building Atom on Windows and running the Atom specs. Indeed, as I assumed it the corresponding `BufferedProcess` sepcs fail:

![error](https://cloud.githubusercontent.com/assets/23704/8697432/389f6be2-2af5-11e5-9142-a5483c19d6d1.png)

**Comment by damieng** [comment]
You can now avoid this (in master) by specifying `options.shell: false ` in your call to BufferedProcess.

Bear in mind that doing this means you can not run .bat or .cmd files with options.shell: false.

Do not use `options.shell: true` at this time - that setting is reserved for Node 5.7 compatibility and will behave like false until then.
