### ISSUE TITLE
Autocomplete attempts to add CSS property after commas

### ISSUE THREAD

**Issue by geebru** [atom/atom#7799]
See small screencast - http://cl.ly/3V1R3d0r1F3v

Mac OSX 10.10.4 - Atom 1.0.1 - No errors / crashes.

I've noticed when attempting to chain CSS selectors (in SCSS) the autocomplete pop-up will appear after I've typed the comma, meaning when I try to hit Return to go to the next line, I get width: width; instead of a new line.

I changed my settings from autocomplete on Tab to autocomplete on Enter after installing Emmet so it's well within my capabilities to circumvent the issue currently but curious as to why it pulls up this prompt when typing commas in CSS (SCSS)?

**Comment by benogle** [comment]
This issue was moved to atom/autocomplete-css#21
