### ISSUE TITLE
Version control modification counter causes overlapping text on the bottom toolbar

### ISSUE THREAD

**Issue by AnotherJoSmith** [atom/atom#7800]
Here is what my bottom toolbar looks like when a file with no modifications is open:
<img width="721" alt="screen shot 2015-07-08 at 3 51 53 pm" src="https://cloud.githubusercontent.com/assets/3300109/8580624/9ef4e244-2589-11e5-8ee2-c53775b5ecf4.png">

But when I open a file with modified lines and the version control modification widget is displayed, it looks like this:
<img width="724" alt="screen shot 2015-07-08 at 3 52 08 pm" src="https://cloud.githubusercontent.com/assets/3300109/8580636/b4eef18e-2589-11e5-9ce2-4b8ee6fe2cd2.png">

I did the same test with the linter package disabled, it is not caused by that plugin.

This is on Atom 1.0 running on OS X.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/status-bar? Thanks!

**Comment by AnotherJoSmith** [comment]
Here is is: https://github.com/atom/status-bar/issues/92
