### ISSUE TITLE
Atom (linter-pylint?) bogging down CPU with spike of Python processes

### ISSUE THREAD

**Issue by jwarner112** [atom/atom#7801]
Hello,

I've got a large (~500 line) script that I'm writing that just comes to a *crawl* whenever I'm typing. I've watched the task monitor and determined it's a spike in Python processes that have a high cycle usage. This problem becomes worse for the duration of typing and then resolves itself slowly over the next few minutes. It's quite frustrating, but I can't be sure if this is the way Atom's handling it or an issue with PyLint or what?

Here's the task manager prior to typing in the file:

![1](https://cloud.githubusercontent.com/assets/2992409/8580970/a7200d98-258b-11e5-88f7-d36cc76c02d8.png)
![2](https://cloud.githubusercontent.com/assets/2992409/8580971/a722f544-258b-11e5-8d5a-60b874d71548.png)

Here they are shortly after typing a block of text with multiple lines:

![3](https://cloud.githubusercontent.com/assets/2992409/8581007/ed50f854-258b-11e5-9236-c98c66dee5a6.png)
![4](https://cloud.githubusercontent.com/assets/2992409/8581006/ed4df58c-258b-11e5-8a25-8058fb221596.png)

I'm not sure what else to make of it. If this isn't an ATOM Issue, does anyone have an idea what it might be?

Thanks!

**Comment by thedaniel** [comment]
This sounds like an issue to file on the repo for the linter package that you are using. Atom doesn't fire off python processes itself.

**Comment by jwarner112** [comment]
Moreso, it has to be pylint itself. The problem was reproducible on
Sublime-Text until I disabled pylint on both.

So strange. So saddening.
