### ISSUE TITLE
Uncaught [object Object]

### ISSUE THREAD

**Issue by bboczeng** [atom/atom#7803]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.12703481
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

Uncaught [object Object]

```
At /Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-analytics/lib/fb/analytics.js:12

undefined
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "tree-view"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by benogle** [comment]
cc @bolinfest

**Comment by kevinsawicki** [comment]
Whoa, really weird Atom version reported

**Comment by benogle** [comment]
> Whoa, really weird Atom version reported

Any pattern in it? Maybe the aliens are trying to tell us something. Movies start like this, man.

**Comment by kevinsawicki** [comment]
> Any pattern in it? Maybe the aliens are trying to tell us something. Movies start like this, man.

`1.0.12703481` :arrow_right:  (101) 270-3481, I called it, no one picked up, will call back later.

**Comment by bolinfest** [comment]
This seems like, ahem, and internal matter...will close and assume we'll take care of it.
