### ISSUE TITLE
Annoying line going through the middle of atom.

### ISSUE THREAD

**Issue by mathwhiz1212** [atom/atom#7807]
I'm running atom v1.0.2 on linux mint 17.2.
I have an annoying line going through the middle of atom:
![atom](https://cloud.githubusercontent.com/assets/11021683/8584795/bab00be0-2597-11e5-9f31-2bb98ec3e06b.png)
Should I compile from source?

**Comment by kevinsawicki** [comment]
That looks like the wrap guide which defaults to 80 characters, you can disable the `wrap-guide` package from the Settings view to remove it.

**Comment by mathwhiz1212** [comment]
Thank you.
