### ISSUE TITLE
Update message

### ISSUE THREAD

**Issue by yohanesu** [atom/atom#7812]
Hi and thanks for a great tool! 

I was just thinking, it would be nice if there was an update message on the "Updates" page in settings so that one can see what has changed since last version and decide to update that package or not.. I guess that also means that the package developers has to take the time to write this message. It's kind of scary to update packages without having any clue to what will change...

Keep up the good work!

**Comment by batjko** [comment]
This has been requested previously, check out this open issue on the Settings View:
https://github.com/atom/settings-view/issues/282

**Comment by yohanesu** [comment]
Ah, thank you. I figured so and search for it but couldn't find.. Should we close this?

**Comment by kubetz** [comment]
> Ah, thank you. I figured so and search for it but couldn't find.. Should we close this?

@yohanesu  Yes, please.  Close this here and subscribe to the issue linked by @batjko for updates :+1:.
