### ISSUE TITLE
Fuzzy Finder does not respect "Ignored Names"

### ISSUE THREAD

**Issue by csholmq** [atom/atom#7815]
Unlike "Find->Find in Project" which respects "Core Settings->Ignored Names", "Find->Find FIle" does not but presents all files in the open projects.

**Comment by mnquintana** [comment]
Fuzzy Finder has its own Ignored Names setting: 

<img width="771" alt="settings_-__users_machistequintana_code_campus-map_-_atom" src="https://cloud.githubusercontent.com/assets/823545/8594508/5362a98e-260f-11e5-89f7-818ed173fa4e.png">

Also for future reference Atom's Fuzzy Finder is provided by [atom/fuzzy-finder](https://github.com/atom/fuzzy-finder), not atom/atom.

**Comment by csholmq** [comment]
Ah, ok my bad! That makes sense now that you mention it. Thanks for clarification!
