### ISSUE TITLE
Atom window closes but processes still running

### ISSUE THREAD

**Issue by blackjack4494** [atom/atom#7816]
Hey,
I do not know what happened. I used some shortcuts and then atom closed itself. When I tried to open it nothing happened so I had a look at processes. And Atom was still running. I closed all of them and started Atom again. I could see the window for 1-2 seconds but the window closed again and the processes are still running. I would like to restart my computer but i can't right now because I got some important programs running right now.
Is there a way to reset the settings or something else so that I do not have to install everything again?

Update1:
So I reinstalled Atom. Still cannot use it. Always closing itself :(

Update2:
So, I could "fix" it the hard way. I deleted all installed Packages. the whole caches etc.
This mean:
C:\Users\xxx.atom\storage
C:\Users\xxx.atom\packages
C:\Users\xxx.atom\compile-cache
C:\Users\xxx\AppData\Roaming\Atom

There need to be some tool that directly clear the cache etc. if something like this happens. Would be cool if you can use it like this 
C:\Users\xxx\AppData\Local\atom\update.exe --clear-cache [--processStart] atom.exe

**Comment by batjko** [comment]
If you want to start Atom with a clean slate after issues like this, there are two things you can do:

 1. Rename/move the `.atom` folder (as you did)
 2. Then start atom in safe mode (`atom --safe`)

This will ensure, no community packages are loaded and any previous settings are gone.
