### ISSUE TITLE
Reloading the window when project folders are open fails

### ISSUE THREAD

**Issue by Nickersoft** [atom/atom#7818]
Running version 1.0.2 I realized that reloading Atom in full screen mode causes the application to just remain black. Reload only works if the app is taken out of full screen mode first. Is this behavior expected?

**Comment by izuzak** [comment]
@Nickersoft I'm having trouble reproducing that on OSX. Can you share [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/7818#issuecomment-120438259. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
