### ISSUE TITLE
Atom package documentation web page should handle relative image URLs.

### ISSUE THREAD

**Issue by peterhal** [atom/atom#7819]
Github supports relative URLs for things like images in markdown files. The Atom generated package docs do not.

For example compare these:

https://atom.io/packages/nuclide-flow

And:

https://github.com/facebook/nuclide/tree/master/pkg/nuclide/flow

The relative image URLs work in the github page, but not the Atom page.

**Comment by peterhal** [comment]
@thedaniel Thanks for taking a look

**Comment by thedaniel** [comment]
I filed an issue on the repo for the site, will close this when it's fixed.

**Comment by batjko** [comment]
Yea that one's been a trip-up for many a newbie package developer since the start.

**Comment by thedaniel** [comment]
This issue was moved to atom/atom.io#14
