### ISSUE TITLE
Editor area is resized incorrectly relative to the window size

### ISSUE THREAD

**Issue by keyshooter** [atom/atom#7820]
![untitled](https://cloud.githubusercontent.com/assets/5885379/8606613/fc611a68-2649-11e5-9fda-64ac8659d22d.png)

**Comment by benogle** [comment]
Can you give more information? Was autocomplete involved? Was it this issue? https://github.com/atom/autocomplete-plus/issues/511

**Comment by keyshooter** [comment]
I don't know, i was coding and then, pum! the whole thing was just like the pic, restart de atom fixed
Date: Thu, 9 Jul 2015 14:02:56 -0700

**Comment by benogle** [comment]
I'm closing as a duplicate of atom/autocomplete-plus#511 It should be fixed in the next atom release

**Comment by keyshooter** [comment]
ThanksDate: Thu, 9 Jul 2015 19:42:25 -0700
