### ISSUE TITLE
Keyboard doesn't work on dialogs

### ISSUE THREAD

**Issue by Navmed** [atom/atom#7823]
When I close Atom, it presents me a dialog asking me to save the file. Pressing 'S', 'C' or 'N' on the keyboard does nothing. I'm using Windows 7.

**Comment by ankitaggarwal011** [comment]
I can confirm this on Windows 7 (x64) and Atom 1.0.0.

**Comment by mryellow** [comment]
Debian KDE, `N` key not selecting "Don't save".

**Comment by oh-ren** [comment]
Also discussed here #2928

**Comment by 50Wliu** [comment]
Closing in favor of #2928 - feel free to subscribe there for updates.
