### ISSUE TITLE
Atom 1.0.2 - OS X - Not showing images for packages that have updates.

### ISSUE THREAD

**Issue by resistdesign** [atom/atom#7824]
Atom 1.0.2 - OS X - Not showing images for packages that have updates.

![screen shot 2015-07-09 at 10 11 34 pm](https://cloud.githubusercontent.com/assets/356375/8610986/dc1f57f4-2687-11e5-819b-f18b83528c1e.png)

**Comment by mnquintana** [comment]
Can you reopen this on https://github.com/atom/settings-view? Thanks!
