### ISSUE TITLE
decode and highlight issue

### ISSUE THREAD

**Issue by zhanglongqi** [atom/atom#7826]
Atom 1.0.2

#### Color lost after toggle soft wrap
<img width="1356" alt="qq20150710-1 2x" src="https://cloud.githubusercontent.com/assets/956693/8614672/9a249566-271e-11e5-986a-e95e68e4d7db.png">

this is the original file https://www.dropbox.com/s/n13t629k7detkaj/net-internals-log.json?dl=0

**Comment by izuzak** [comment]
The second issue is already reported: https://github.com/atom/atom/issues/1667 (syntax highlighting breaks on long lines).

Can you clarify what the problem is with Chinese characters? Have you searched existing issues to see if the problem is already reported?

**Comment by izuzak** [comment]
Also, this is what I see:

![screen shot 2015-07-10 at 14 26 04](https://cloud.githubusercontent.com/assets/38924/8618526/a7ca7834-270f-11e5-81f7-51c1f3915541.png)

**Comment by zhanglongqi** [comment]
it  seems works fine on your side. I am using mac osx Darwin LQMacPro.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
but VS is OK, so I should have the Chinese fonts. it should be  the problem of atom font setting.

**Comment by zhanglongqi** [comment]
Some of the others also have the same problem, but it is for old release.
it show some characters means it have the font but not the decode, it may be GB2312 or GBK or UTF-8.

**Comment by izuzak** [comment]
> it should be the problem of atom font setting.

Which font are you using? Does changing the font in Atom's settings help?

> Some of the others also have the same problem, but it is for old release 

Who are the others you are referring to and which old release?

**Comment by zhanglongqi** [comment]
i find the problem. when I open it show the right Chinese characters and almost one second later it change back to unknown characters I notice the right bottom corner is GBK, i change it to UTF-8 then everything OK. The problem should be the code detection problem. Is it clear? Sorry for my bad expression.

**Comment by izuzak** [comment]
Sorry, not clear. :) Can you record a short GIF which clearly demonstrates the problem where the characters change on their own in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

Also, when you go to the settings, what's the file encoding that's defined as the default encoding?

![screen shot 2015-07-10 at 15 08 02](https://cloud.githubusercontent.com/assets/38924/8619250/aa4cb83c-2715-11e5-8596-3287a379dbac.png)

**Comment by zhanglongqi** [comment]
it's GBK. Is it possible to set it as auto detect mode? I did not find the auto option in the file encoding.

**Comment by izuzak** [comment]
> Is it possible to set it as auto detect mode? I did not find the auto option in the file encoding.

Not possible currently: https://github.com/atom/encoding-selector/issues/24
