### ISSUE TITLE
atom automatically remove the blank space and blank line

### ISSUE THREAD

**Issue by wanghaisheng** [atom/atom#7827]
when I try to add blank space to end of a line  or  blank line to end of a file,atom editor will remove them automatically,how to disable this function

**Comment by batisteo** [comment]
If you have this behaviour after save, this is because of the default package [whitespace](https://atom.io/packages/whitespace).
I had to disable it, but you can what you don't need in the package settings.
Hope it helped.

**Comment by wanghaisheng** [comment]
thx a  lot @batisteo

**Comment by batisteo** [comment]
One more link: https://atom.io/docs/v1.0.2/using-atom-editing-and-deleting-text#whitespace
