### ISSUE TITLE
Atom hangs after startup

### ISSUE THREAD

**Issue by kimkulling** [atom/atom#7829]
When starting Atom on Windows7 - 65 bit without having a windows I can see the icon in my task bar. Unfortunately I cannot open the Atom-Window. INstead of this I see the waiting cursor from Windows and nothing happens. 
Preview-Windows from window when hovering over task-icon shows me the preview of the Atom-window. 

We are using a proxy, but I haven't configured it right now. Maybe Atom waits for any kind of timeout?

What can I do? I am using version 0.22.3.0.

**Comment by mnquintana** [comment]
If you mean version 0.223.0, you're using an extremely old version of Atom - please update to the latest version (1.0.2). Feel free to reopen this if you still experience this after successfully updating to 1.0.2.

**Comment by kimkulling** [comment]
I used the latest version 1.0.2, but when taking a look into the pocesses with the Process-Explorer is seems to show a deprecated version of atom ( the one I noted above 0.22.3.0 ). 
I checked the sources but I am not sure if this version is set only for the installer or the installer is using a version string rom the atom sources.

**Comment by kimkulling** [comment]
I am not allowed to reopen the issue, but it is still there with the latest version. Let me know if I can help you investigating this issue.

**Comment by 50Wliu** [comment]
For some reason your process explorer seems to be detecting the Atom Shell version instead of the Atom version.

**Comment by damieng** [comment]
Hil kimkulling are you still experiencing this problem?

**Comment by damieng** [comment]
No response, closing issue. Please re-open if issue still exists.
