### ISSUE TITLE
Ask before loading previous project

### ISSUE THREAD

**Issue by azerupi** [atom/atom#7830]
Hi

At the moment, Atom loads the last project worked on when you launch it. Which is great, except when you want to work on something else and your previous project has a substantial size. It takes some time to load, then you have to open a new window via the menu and close the old one. 

It would be really awesome if we could get some splash to choose what we want to open:

- Last project
- Recent projects
- New project
- Open folder / file

Because for people who switch between multiple projects it's frustrating to have to wait for project X to load before you can close it and begin to load project Y.

**Comment by mnquintana** [comment]
This looks like a duplicate of https://github.com/atom/atom/issues/6605 – please subscribe there for updates. We probably won't add a dialog on opening because it would be quite obtrusive - however someone could write a package to do this.

**Comment by azerupi** [comment]
My bad, I apologize. Thank you for the link :)
