### ISSUE TITLE
Opening multiple files using Context Menu in Windows Explorer opens multiple instances

### ISSUE THREAD

**Issue by Navmed** [atom/atom#7837]
Opening multiple files using Context Menu in Windows Explorer opens multiple instances of Atom instead of opening all the files as tabs in the same instance. (Windows 7 x64)

**Comment by JulienSambre** [comment]
Same issue on same Windows version.

**Comment by damieng** [comment]
Just tried this and it is now working fine - not sure when it was fixed however.
