### ISSUE TITLE
Can't type backslash with Latam (Spanish) keyboard.

### ISSUE THREAD

**Issue by Alewex** [atom/atom#7838]
While I was giving atom a try today, unfortunately I found it impossible to write down a single backslash with my current keyboard layout (Latam/Spanish).

I was trying to write down PHP namespaces but it was not possible unless I changed my keyboard to the English layout.

![latam-setting-backslash](https://cloud.githubusercontent.com/assets/6007059/8632103/8235ad76-2752-11e5-9d8a-ad5b4a4db813.png)

**Comment by taiyaei** [comment]
Guessing this is https://github.com/atom/atom-keymap/issues/35 ?

**Comment by Alewex** [comment]
This is what I was looking for, thanks :+1:
