### ISSUE TITLE
Dialog Box Inconsistency on Ubuntu

### ISSUE THREAD

**Issue by tuhinkarmakar** [atom/atom#7844]
**Atom 1.0.0** on _Ubuntu 14.04.2_
### The dialog box asking to save unsaved changes is not consistent with the rest of the system.
1. The dialog box doesn't highlight the header part, where the close icon ('x')
   is displayed.
2. The close icon ('x') is shown on the upper right corner. Whereas on Ubuntu
   these icons are generally shown on the upper left corner.
3. On Ubuntu, the affirmative actions (save, authenticate, yes) are shown on the
   right side of the dialog box. But Atom shows it on the left side.
4. The dialog box doesn't highlight the 'save' button with a different color.

![dialog-box-atom](https://cloud.githubusercontent.com/assets/11135104/8634115/1dd3ca86-2809-11e5-9e89-2c88e340b781.png)
###### Dialog Box in Atom

![dialog-box-gedit](https://cloud.githubusercontent.com/assets/11135104/8634119/294ae00c-2809-11e5-8e20-738691636640.png)

**Comment by dpanter** [comment]
Would be a real good idea to fix this. Version 1.0.11 still going rogue with the dialogues...

![save_dialog_inconsistency_atom](https://cloud.githubusercontent.com/assets/14197392/9770289/b5b8d0b2-572f-11e5-8e76-68fc202c2305.png)

**Comment by dpanter** [comment]
Addition: tested all core themes in Atom, no difference in the dialog box appearance.

**Comment by tuhinkarmakar** [comment]
This is how **Sublime Text 3** looks on my system.

![sublime](https://cloud.githubusercontent.com/assets/11135104/9835841/f3c7dad0-5a1b-11e5-97ac-7ddc4cc7393d.png)

**Comment by dpanter** [comment]
Well two years later, it's **still not fixed**... it makes me unhappy, so I'm gonna attach a new picture showing that it's still borked. Plz someone fix ^_^ (I'm no good for fixing code but I'm good at complaining)

![atom_save_dialog_still_borked](https://user-images.githubusercontent.com/14197392/29840008-b492a2c2-8d00-11e7-9121-8abc5335cf06.png)

To paraphrase myself, "please make buttons conform to system-wide standard"
