### ISSUE TITLE
git status column not updated after partial staging

### ISSUE THREAD

**Issue by zonque** [atom/atom#7845]
When staging and commiting some individual hunks of a file only, the git status in the line number column is not updated correctly. Closing and re-opening the file fixes the problem.

I'm using Atom 1.0.2 on Linux.

**Comment by mark-hahn** [comment]
I have not seen the git status column change after committing, for some
time in any situation.  I either leave it wrong or reload.

Ubuntu 14.0.4
Problem since pre 1.x.x versions of Atom.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/git-diff?
