### ISSUE TITLE
Package search doesn't find rest-client even though it should

### ISSUE THREAD

**Issue by mrdanimal** [atom/atom#7847]
With Atom 1.0.2 on OS X Yosemite.
I'm trying to install [rest-client](https://atom.io/packages/rest-client) but when I search for 'rest-client' in the settings pane or using apm it doesn't find the package. Trying to install directly with apm returns an error:

```
No available version compatible with the installed Atom version: 1.0.2
```

rest-client's package.json says it's compatible:

```
  "engines": {
    "atom": ">0.50.0"
  },
```

**Comment by benogle** [comment]
This package has several deprecations that would not allow it to work. https://github.com/ddavison/rest-client/issues/18

The messaging should definitely be better from `apm`.

**Comment by mrdanimal** [comment]
D'oh. Didn't think of looking in the issues. Thanks for the info!
