### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by bucaran** [atom/atom#7848]
After updating to 1.0.2 I am getting this error, despite ESLint being listed under `node_modules`.

> [Linter-ESLint] Local/Global ESLint binary not found. Fallback to packaged one. Set binary in preferences.

**Comment by nabana** [comment]
Same issue here...

**Comment by mnquintana** [comment]
This is not an issue with Atom core - please reopen this on https://github.com/atomlinter/linter-eslint.
