### ISSUE TITLE
Opening nonexistent file should provide feedback to the user

### ISSUE THREAD

**Issue by multiwebinc** [atom/atom#7851]
Exactly as the title says, when the user tries to open a file that doesn't exist, they should be presented with some sort of warning message / feedback that it is a new file. If the file name was misspelled, the user could have the false assumption that the file contents were emptied.

Steps to reproduce:
1. File > Open
2. Type random text as the file name and click "Open"
3. Bask in the silence

**Comment by izuzak** [comment]
That's an interesting idea, @multiwebinc. Can you share some ideas on the type of feedback you'd like to see or have you perhaps seen something similar in other editors?

**Comment by multiwebinc** [comment]
I just did a quick little survey of all of the text editors I could find. Here are the results:

Kate on KDE 4.13
-
A small "New file" notice is displayed
![kate](https://cloud.githubusercontent.com/assets/901732/8862996/3d5d6a86-3152-11e5-977d-2cf76b5719c8.png)

Kate on KDE Plasma 5
-
Unlike KDE 4.13, you are unable to open a nonexistent file from the menu.
![kate_plasma_5](https://cloud.githubusercontent.com/assets/901732/8862997/3d5e2b56-3152-11e5-970d-be13d72f0f6f.png)

KWrite on KDE Plasma 5
-
However for both KWrite and Kate on plasma you can open a nonexistent file from the command line and you are presented with a similar message to KDE 4.13
![kwrite](https://cloud.githubusercontent.com/assets/901732/8862998/3d62710c-3152-11e5-9a93-c140f41d5833.png)

Geany
-
While technically an IDE, the status message indicates it is a new file
![geany](https://cloud.githubusercontent.com/assets/901732/8863005/3d8b82b8-3152-11e5-8849-13858bb5dfa3.png)

Medit
-
The text `[new file]` is appended to the title
![medit](https://cloud.githubusercontent.com/assets/901732/8863000/3d7518a2-3152-11e5-8b5b-3a97fda1cfb2.png)

Nano
-
The text `[ New File ]` appears highlighted at the bottom of the screen
![nano](https://cloud.githubusercontent.com/assets/901732/8863001/3d77e23a-3152-11e5-8fbf-9edb5e025508.png)

Vim
-
The text `[New File]` appears highlighted at the bottom of the screen
![vi](https://cloud.githubusercontent.com/assets/901732/8863002/3d78bc8c-3152-11e5-9fda-577fc5bab48d.png)

Notepad and Wordpad (WinXP)
-
They simply refuse to open a nonexistent file with a popup message
![notepad_xp](https://cloud.githubusercontent.com/assets/901732/8863003/3d78ffa8-3152-11e5-8051-cd6c4463f21a.png)

Editors that do not display any sort of indication that the file does not exist:
-

**Gedit**
![gedit](https://cloud.githubusercontent.com/assets/901732/8863006/3da32e90-3152-11e5-9332-db219bb0cb48.png)

**Leafpad**
![leafpad](https://cloud.githubusercontent.com/assets/901732/8862999/3d6323a4-3152-11e5-91d8-2d0d6b3bdbb8.png)

**Comment by izuzak** [comment]
Amazing, thanks so much for doing the research, @multiwebinc.

**Comment by batjko** [comment]
Yea, nice work @multiwebinc :+1:

**Comment by stereobooster** [comment]
I would like to see marker of "file has unsaved changes", but it is just opened so you can conclude it does not exist on disk.
