### ISSUE TITLE
Error checking for updates immediately after updating Atom

### ISSUE THREAD

**Issue by parasyte** [atom/atom#7854]
![screen shot 2015-07-11 at 11 04 41 pm](https://cloud.githubusercontent.com/assets/456942/8636632/8cab9c50-2821-11e5-9e55-0bbb691a46e2.png)

After Atom updates (and restarts), _immediately_ attempt another update. The error message is displayed.

After waiting a few minutes, the update check succeeds.

**Comment by Stanzilla** [comment]
Could be related? https://github.com/atom/atom/issues/8265

**Comment by rick** [comment]
![](https://cloud.githubusercontent.com/assets/6259/9213456/78cff8be-4047-11e5-82b7-1515f8c6cf05.png)

I also saw this today, was at version 1.0.5, a few minutes later I checked again and it downloaded 1.0.6 successfully.

**Comment by erchen** [comment]
Updated from 1.7.4 to 1.8.0 and attempted to immediately update again. I did not receive the "There was an error checking for updates." message, and instead received an accurate "No update available" message. I believe this issue can be closed.

**Comment by 50Wliu** [comment]
@parasyte @rick Are you still experiencing this?

**Comment by parasyte** [comment]
I have not seen this recently.

**Comment by 50Wliu** [comment]
Ok, in that case I'm going to close this issue until it can be reproduced again.

**Comment by pydolan** [comment]
I got this today after updating last week (either to 1.17.0 or 1.17.1), but mine didn't have the "(null)" at the end of the message.  This only appeared once, then didn't see it again. However, Atom kept telling me there was an update available (blue circle icon), but on the About screen, clicking Check for Updates told me 1.17.0 was the latest.

I then manually downloaded Atom 1.17.2 today, opened it, and got this message again ("There was an error checking for updates...").

A few minutes later (as I'm typing this), I get "Editor is not responding" (from MacOS I assume).  After I clicked, "wait for response" (or whatever the button was), clicking any of my open panels have no response. Menus open, but do no response on any action I click.  I had to request a Quit via Activity Monitor, then got the "not responding" message again and closed it.

After restarting, all my previously open panels/files are cleared, and checking for updates says 1.17.2 is the latest (which it is).  I do wonder though if I'll have the same issue when a new version of Atom comes out.  Unfortunately, reinstalling the application (copying Atom.app into Applications) didn't fix the issue this last time, so there must be something corrupted elsewhere. Thoughts?

**Comment by tjkohli** [comment]
I am having the same experience as @pydolan, except when updating from 1.17.2 to 1.18.0.

**Comment by 50Wliu** [comment]
:wave: @pydolan or @tjkohli would you mind opening a new issue?  It sounds like what you're experiencing is slightly different from what was reported in this one.

**Comment by tjkohli** [comment]
@50Wliu No, it was the same exact error and steps. But I want to note that once you click "Restart to Update" or something similar on 1.17.2, it quits Atom for a long time. If you manually launch Atom again, you get the error described above. But if you wait a minute or so, 1.18.0 launches and updates successfully. That's how I resolved it.

**Comment by 50Wliu** [comment]
@tjkohli sounds like you're running into https://github.com/Squirrel/Squirrel.Mac/issues/124?

**Comment by arrygoo** [comment]
I'm running to the same error now on 18.

**Comment by F1ks3r** [comment]
yep, just downloaded linter and updated all packages and got same thing (el capitan)

**Comment by mdanetzky** [comment]
Apparently Atom has an installer which runs in background without any user feedback. When I tried to start Atom before it was finished - the "Error checking for updates" came up. My solution was to punch the "Restart and Install Update" and wait patiently for a minute or so while watching my empty desktop. Eventually an updated Atom came up automatically. 

In my opinion this is an UX error. Atom should have some sort of an update progress notification.

**Comment by 50Wliu** [comment]
@mdanetzky Yep - this is mostly out of our hands.  See Squirrel/Squirrel.Mac#124.

**Comment by tjkohli** [comment]
@mdanetzky I agree. I think the easiest solution would be to warn the user that it may take up to a minute before the application is restarted. I initially thought the installation failed or the updated application was unable to launch for some reason.

**Comment by ryanlloydfrench** [comment]
I saw this issue pop up today when trying to update.

Atom Version: 1.18.0
MacOS Version: 10.12.6

**Comment by vilaskumkar** [comment]
As Azazw as d xx zezea<<¢a,a,aa
As atssazdzdz

On Aug 9, 2017 10:05, "Ryan French" <notifications@github.com> wrote:

I saw this issue pop up today when trying to update.

Atom Version: 1.18.0
MacOS Version: 10.12.6

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/atom/atom/issues/7854#issuecomment-321150252>, or mute
the thread

**Comment by d3r1v3d** [comment]
I experienced this issue today, as well, when re-opening Atom:
```
Atom: v1.18.0
MacOS: v10.11.6
```

**Comment by tjkohli** [comment]
@d3r1v3d @vilaskumkar @ryanlloydfrench You guys realize there is no "bug" here, right? It's just a usability issue. Atom takes a while to reopen after installing update and there is no way to know what it's doing. If you open it manually during that period, it will fail. Just be patient, and it will load up. Takes about 90 seconds.

**Comment by d3r1v3d** [comment]
@tjkohli I let it run for an hour and it hung. That qualifies as a bug to me... Comes back up every time I reopen Atom.

**Comment by tjkohli** [comment]
@d3r1v3d But did you attempt to launch Atom at any point while it was updating?

**Comment by ikari7789** [comment]
@tjkohli This is a bug as the "update" progress has no kind of visibility to the user. The user has no way of knowing. The application will boot up and work just fine (though it will show that error message in the process). What you call a "usability" issue makes the application function weirdly, so in other words, this becomes a "bug." The error message is unclear. To me, it looks like a permissions issue. I didn't even know an update was in progress.

**Comment by tjkohli** [comment]
@50Wliu Please reopen this. This is a valid issue and can be reproduced every time.

**Comment by parasyte** [comment]
To everyone who has commented on this ticket in regard to *manually* restarting Atom during an update; please file another ticket. This one is related to checking for updates after an *automatic restart* completes successfully.

**Comment by lee-dohm** [comment]
@tjkohli Can you give a set of steps to reproduce the problem here?

**Comment by tjkohli** [comment]
@lee-dohm Although I need an Atom update for it to happen, and I've learned to avoid it, basically the steps are:

1. macOS (happened in 10.12, I haven't triggered it in 10.13 yet)
2. Check for updates on Atom, install them.
3. Atom quits
4. Atom takes a long time to restart
5. In the meantime, it seems as if Atom has crashed
6. Attempt to relaunch Atom (clicking Dock icon, Spotlight, whatever)
7. Receive update error, and you notice the update install also failed

On the contrary, if you don't do anything around steps 4-5, and just wait a solid 30 seconds, Atom comes back up no problem. This is somewhat of a usability issue more than an actual bug. There should be some sort of communication to the user telling them that the update may take a while. You could also disable relaunching of Atom while it is updating.

**Comment by lee-dohm** [comment]
@tjkohli So if I understand correctly, at a high level you have to:

1. Have an update available
1. Check for updates and immediately install and relaunch
1. Launch Atom while it is still updating
1. Check for updates again and get the error?

**Comment by tjkohli** [comment]
@lee-dohm That is what triggered it last time I reported it. I'll report back next time there is an Atom update.
