### ISSUE TITLE
Default styling for form select elements?

### ISSUE THREAD

**Issue by mensinda** [atom/atom#7856]
Is there a class for `<select>...</select>` elements? 
I am currently using a copy of [this section](https://github.com/atom/settings-view/blob/master/styles/settings-view.less#L78-L87) in the settings-view package.

**Comment by mensinda** [comment]
If there aren't classes for those elements, would it be possible to move them from the settings package to the main editor, so that other packages could use them?
It would also be nice if the checkbox classes could be moved.

**Comment by mnquintana** [comment]
There should be default styling for `select`s provided by Bootstrap, but if you specifically want the styles from settings-view than that currently isn't included in core.

@simurai What do you think about moving some of the form styling from settings-view to Atom core? I'm not sure personally - it might be a bit too prescriptive.

**Comment by mensinda** [comment]
Both `select` and `<input type="checkbox";>` elements are currently not effected by a theme (tested one-{dark,light}, atom-{dark,light} (atom 1.0.2)).
Adding the `form-control` class to select elements changes size and border but not the color.

**Comment by simurai** [comment]
Yeah, the `select` and `checkbox` in the settings are custom styled with the theme colors.

> What do you think about moving some of the form styling from settings-view to Atom core?

I think it's a good idea. That way they look more consistent and package authors don't have to bother trying to style them. It just wasn't that high priority pre 1.0, but definitely on the roadmap.

It would be Bootstrap + settings styles = core control/component.

**Comment by simurai** [comment]
@mensinda For now, feel free to grab the styles in the settings till they're available globally.

**Comment by simurai** [comment]
Custom styled `select` elements are available by adding the `input-select` class:

```less
<select class='input-select'>
```

![screen shot 2016-11-04 at 3 31 01 pm](https://cloud.githubusercontent.com/assets/378023/19996551/b7e3081a-a2a3-11e6-9878-1addc6c7ec64.png)
