### ISSUE TITLE
Please tell me where to rename

### ISSUE THREAD

**Issue by chinakids** [atom/atom#7860]
no rename？

**Comment by mark-hahn** [comment]
Rename what?  There is a rename function in the file tree.

**Comment by chinakids** [comment]
I found that I did not find him even in development tools
![screenshot](https://github.com/chinakids/PicturesStore/raw/master/issue/atom-rename.png)

**Comment by chinakids** [comment]
In ContextMenu

**Comment by mark-hahn** [comment]
Look in the repo for find-and-replace.  You can see how it is implemented there.

I would think it is just a call to the npm module fs-plus, not an atom command.

**Comment by chinakids** [comment]
thanks for your's answer~~

**Comment by lee-dohm** [comment]
@chinakids Did @mark-hahn sufficiently answer your question? If so, i'd like to close this.

**Comment by chinakids** [comment]
OK
