### ISSUE TITLE
Updating a disabled package automatically re-enables that package

### ISSUE THREAD

**Issue by rktjmp** [atom/atom#7861]
I'm not sure how to test this again locally, because I'm not sure how to install an older version of a package.

I had the vim-mode package installed but disabled. I manually clicked the "update package" button (not the "update all" button). After the package had been updated, it seemed that it re-enabled itself. I would have expected it to remain disabled.

Not a large issue but might catch some people out if they had a larger number of disabled packages.

**Comment by mnquintana** [comment]
What version of Atom are you using? You can install an old version of a package with `apm install`, e.g.:

```
apm install linter-eslint@1.0.0
```

**Comment by rktjmp** [comment]
```
$ atom --version
1.0.2
```

To reproduce:

1) Confirm vim-mode is disabled, quit atom
2) `apm install vim-mode@0.54.0`
3) Load atom and confirm vim-mode remains disabled.
4) Click "Update to 0.55.0"
5) Observe package is automatically re-enabled after update finishes

**Comment by rktjmp** [comment]
This also happens with `minimap-git-diff`, so i don't think its specific to vim mode.

**Comment by palango** [comment]
Just saw this as well. Works with any package as far as I can tell.

**Comment by mnquintana** [comment]
This issue was moved to atom/settings-view#603
