### ISSUE TITLE
List of projects to be excluded when opening the Atom

### ISSUE THREAD

**Issue by jlamim** [atom/atom#7867]
Several times, when starting the Atom, the list of projects disappears, and I have to add all again.

P.S: I use Mac OS X Yosemite.

**Comment by abe33** [comment]
Can you give us more information about what you mean by *projects list*?

**Comment by jlamim** [comment]
When we go to the menu "File - Add Project to Follder ..." and select a project, they are now displayed fixedly on the left side of the screen, making navigation.

However, some holes in times when the atom is opened, the projects add up, and I have isnerir again. What is very annoying.

Do not I get many projects added at most a 5.

**Comment by benogle** [comment]
How are you restarting atom? From the dock? From the command line? If command line, what command are you typing on the command line?

**Comment by jlamim** [comment]
From the Dock.
