### ISSUE TITLE
Python grammar tokenizeLines inconsistent when using self

### ISSUE THREAD

**Issue by jagill** [atom/atom#7873]
It tokenizes the `foo` in `self.foo` as two tokens, `f` and `oo`, but in `self.foo()` it is correctly tokenized as `foo`.  This does not happen with `a.foo`.

Reproduction:  get a python grammar object `grammar`:
```js
tokens = grammar.tokenizeLines('self.foo')
// length 4 array, tokens[2].value == 'f', tokens[3].value == 'oo'
tokens = grammar.tokenizeLines('self.foo()')
// length 5 array, tokens[2].value == 'foo'
```

This is version 1.0.2 of atom on OS X 10.10.2, running in `--safe` mode.

**Comment by lee-dohm** [comment]
This sounds like an issue with the [language-python package](https://github.com/atom/language-python). Or are you suggesting this is an issue with the grammar engine itself?

**Comment by jagill** [comment]
Good point; opened it there as https://github.com/atom/language-python/issues/77 .
