### ISSUE TITLE
Highlight code folding section on mouse over

### ISSUE THREAD

**Issue by multiwebinc** [atom/atom#7874]
Similar to https://github.com/atom/bracket-matcher/issues/30 but with code folding.

Here's a feature currently present in the Kate text editor that I think would be a great addition to Atom. When you hover your mouse over the code folding icons, it highlights the section that will be folded to give a quick and easy visual indicator.

Here's a screenshot:

![code_folding_highlight_crop](https://cloud.githubusercontent.com/assets/901732/8658870/c3dd9488-2963-11e5-9993-b91b5874cfdc.png)

**Comment by abe33** [comment]
It looks like something that could also be implemented as a package.

**Comment by sdaitzman** [comment]
I think it should be an integrated feature.

**Comment by harryjubb** [comment]
Any news on this?
