### ISSUE TITLE
File failed to save, and editor froze

### ISSUE THREAD

**Issue by mcandre** [atom/atom#7875]
Today, Atom failed to save a file, and later froze. I'll document the steps to reproduce as best I can, though I know they're incredibly general.

# Steps to reproduce

1. Use [these](https://gist.github.com/mcandre/b209c904748b983552ca) Atom settings.
2. Edit a few Python .py files.
3. Attempt to save a few edits.
4. Attempt to continue editing.

# Expected

The file saves, and new characters typed on the keyboard appear in the editor.

# Observed

Atom freezes, eventually raising a prompt to either wait or relaunch.

Upon relaunch, it was discovered that the previous saves had failed to actually save.

If this happens again, I'm ditching Atom.

# Configuration

https://gist.github.com/mcandre/b209c904748b983552ca

# System

* Atom 1.0.1
* Brew Cask 0.54.1
* Homebrew 0.9.5
* Mac OS X 10.10.4 Yosemite

**Comment by skela** [comment]
Same thing happened to me. a few hours work gone :(

**Comment by lee-dohm** [comment]
Since you mention that you have Homebrew installed, is that how you installed Atom? Have you tried the version direct from the website?

**Comment by mcandre** [comment]
Brew Cask gets Atom direct from the website.

I believe symbol-gen may be the problem.

**Comment by kscheunert** [comment]
Same problem here: Atom is not saving changes to files - Crash has not yet happened. I noticed this behaviour when SASS-files were not compiled automatically after changes.

- Atom 1.0.2
- Mac OS X 10.10.4
- symbol-gen is not installed

**Comment by mcandre** [comment]
Confirmed, disabling symbol-gen fixes the crash.

https://github.com/weskinner/symbol-gen/issues/36
