### ISSUE TITLE
Atom memory leak

### ISSUE THREAD

**Issue by Enkouyami** [atom/atom#7883]
**Atom version**: 1.0.0
**OS**: Linux

I started atom and my CPU jumped and memory usage gradually increased without end. After around 2 to 3 minutes,  the memory usage was at 3GiB and the virtual memory was at 10 GiB.

I tried running atom in safe mode with `atom --safe` and got the same result.

**Comment by lee-dohm** [comment]
Which version of Linux? Have you tried updating to the latest version of Atom and seeing if this still reproduces?

**Comment by lee-dohm** [comment]
Can you also include CPU and memory snapshots?

https://atom.io/docs/latest/hacking-atom-debugging#diagnose-performance-problems-with-the-dev-tools-cpu-profiler

**Comment by barttt** [comment]
I have the same issue on a win7 box. Easy to reproduce:
Start Process Explorer
Start atom and load one file for edits
On the Process Explorer main screen scroll down to the atom nodes and watch the memory usage column, it increments every couple of seconds
Hope this helps

**Comment by Enkouyami** [comment]
I'm running Linux Kernel v4.0.5-040005-generic, saving the files for CPU & memory snapshots produced blank 0KB files, and I haven't tried a more updated version of atom yet.

This is the only record I have for it:
![screenshot from 2015-07-16 18 06 35](https://cloud.githubusercontent.com/assets/1947085/8737784/349d631e-2bf4-11e5-869e-886fdb4a8e89.png)

**Comment by 50Wliu** [comment]
> snapshots produced blank 0KB files

This is a known bug on Linux.

**Comment by Enkouyami** [comment]
I don't have this problem on atom v1.0.2.

**Comment by Enkouyami** [comment]
Sorry, this actually happens in v1.0.2, but not as fast.

**Comment by Ghariani-Mohamed** [comment]
Same issue.I'm using linux mint 17.2 and atom v1.0.2.
My CPU is intel i5 480M with 6GB of ram

I was just editing a JSON file when i noticed the problem and the only suggested update was for the minimap plugin.here's a screenshot of the memory usage i got

![screenshot from 2015-09-06 19 47 00](https://cloud.githubusercontent.com/assets/8039627/9706140/65363646-54d4-11e5-979e-d37475444e58.png)

sorry i couldn't use the Chrome’s CPU profiler but i was watching the System monitor and the ram usage was slowly getting higher.

**Comment by fcharlie** [comment]
Ubuntu 15.10 x64, Atom 1.6.0 Memory leak, 
![2016-03-21 14-18-56](https://cloud.githubusercontent.com/assets/6904176/13911789/e95e8fbe-ef6f-11e5-816f-e3edc440a7f5.png)

**Comment by Maevnik** [comment]
Same problem
Same OS - Ubuntu 15.10 x64
![2016-03-21 13-01-41](https://cloud.githubusercontent.com/assets/10526663/13915369/49ca5a50-ef65-11e5-8c95-8bba871f8653.png)

**Comment by contentfree** [comment]
Seeing this with 1.8 on macOS, too. Eventually leads to the kernel shutting down other processes because of memory / swap starvation which eventually requires a system restart. (Had a screenshot in my pasteboard that showed four Atom Helper processes that each said they were using 4-9 gigabytes of memory each but I lost it…)

**Comment by wordyallen** [comment]
@contentfree  What made you think it was a package?

**Comment by mikhailrojo** [comment]
for future visitors: 

please check, may be in the folder there is .gitignorefile and no .git folder(git wasn't initiated). In this case Atoms behaves like a crazy.
