### ISSUE TITLE
Default language syntax (like Ruby on Rails)

### ISSUE THREAD

**Issue by Mihoid** [atom/atom#7889]
please, make ability to set default language (Ruby on Rails for example) for everytime. 
This hardcore method will be helpful.

Thanks

**Comment by esam091** [comment]
What exactly do you want to achieve? Do you want every new tab to use Ruby language?

**Comment by lee-dohm** [comment]
There is [an answer I posted on StackOverflow](http://stackoverflow.com/questions/24661424/set-default-language-for-new-files/24728120#24728120) that shows how to do this in your `init.coffee`.

**Comment by lee-dohm** [comment]
There is also the [default-language package](https://atom.io/packages/default-language).

**Comment by lee-dohm** [comment]
Thanks for the suggestion. Since there are a couple options here, I'm going to close this.
