### ISSUE TITLE
Cannot make text selection on Lubuntu

### ISSUE THREAD

**Issue by mr-lanholmes** [atom/atom#7890]
Hi all, I just install Atom on my Lubuntu. But why cant I make text selection using my mouse? And also, when I right-click on the project files there are no highlight for the menu i chose.
Thanks

**Comment by mnquintana** [comment]
Are you running Lubuntu in VirtualBox?

The latter is a known issue: https://github.com/atom/atom/issues/2991

**Comment by mr-lanholmes** [comment]
Yes... Any particular problem? And how to solve that?
Thanks

**Comment by mnquintana** [comment]
Thanks for the update! I think this is a duplicate of https://github.com/atom/atom/issues/6306 and/or https://github.com/atom/atom/issues/6243. You can check this comment for more information on its status: https://github.com/atom/atom/issues/6306#issuecomment-116265414
