### ISSUE TITLE
Problems on users with spaces on user's folder

### ISSUE THREAD

**Issue by GGG-KILLER** [atom/atom#7892]
I installed atom on my computer and the path to atom is something like this:
C:\Users\User Name\AppData\Local\atom
and when I try to use the "Open with Atom" option on the context menu it says that the file which I'm trying to open is not a valid Win32 application.
The solution that I was able to find is putting quotes around the path to the atom executable on the windows registry.

**Comment by damieng** [comment]
Hi, I just checked the latest 1.6.2 release registry keys and they all have quotes around them now so this was fixed - not sure in which release however.

Please re-open if you see issues in 1.6.2 or later.
