### ISSUE TITLE
Atom Installed Packages Page Doesn't Search Well Before Items Are Loaded

### ISSUE THREAD

**Issue by bobber205** [atom/atom#7895]
An example:

I wanted to uninstall my xml formatter plugin because I'm not using it at all anymore.

I go to installed packages, type xml, press enter, packages keep loading and nothing happens.
Nothing is searched for while packages are loading.

To get it to search again, I gotta clear the field, press enter, type xml again, then press enter again. 

If I just wait for everything to load before typing, it searches successfully the first time.

If all packages have to be loaded, can the search box resubmit the search terms once they're all loaded?
Odd behavior.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/settings-view? Thanks!
