### ISSUE TITLE
HAML comment line leaves subsequent line italic

### ISSUE THREAD

**Issue by Superpencil** [atom/atom#7898]
In HAML with Rails, if I comment out a line with -# or / or // the subsequent line in italics and some text greyed out as well.

<img width="290" alt="screenshot 2015-07-15 12 26 55" src="https://cloud.githubusercontent.com/assets/3094044/8688299/72f0b6f4-2aee-11e5-8015-9b5ead8e55d7.png">
<img width="349" alt="screenshot 2015-07-15 12 40 12" src="https://cloud.githubusercontent.com/assets/3094044/8688317/a9b8406c-2aee-11e5-8c2a-eee0b7cc934a.png">

**Comment by mnquintana** [comment]
Atom doesn't ship with HAML support - are you using https://atom.io/packages/language-haml?

**Comment by Superpencil** [comment]
Moving over there, thanks :bow:
