### ISSUE TITLE
[Bug] Several language fonts (Japanese, Chinese, Hebrew, ...) not displaying in Ubuntu 14.04+ with Atom v1.0.2

### ISSUE THREAD

**Issue by martynbiz** [atom/atom#7899]
Does anyone use Atom with foreign characters (e.g. Japanese)? I found one post on this, but no one had replied (https://discuss.atom.io/t/japanese-encoding/17871)

Is there a package to install or something? I have Japanese Anthy installed, so I can type Japanese characters in other programs (LibreOffice, Chrome, etc), and I'm saving in UTF-8. Just in Atom these characters appear as squares.

**Comment by batjko** [comment]
It works fine for me in UTF8 encoding.
![image](https://cloud.githubusercontent.com/assets/7287076/8691686/f4efec1e-2abd-11e5-9fb0-29a8dee81aad.png)

I'm using Source Code Pro font.
Can you try different fonts and see if that's the issue?

**Comment by martynbiz** [comment]
I tried switching to Source Code Pro and, other than make the squares smaller, still I see squares. I've just recently upgraded to Ubuntu 14.04 if that helps. And I'm running Atom v1.0.2.

**Comment by batjko** [comment]
I did the above on a Windows machine, I'll try it on Linux a little later today.
But I'd be surprised if that made a difference.

**Comment by martynbiz** [comment]
Hm, that's interesting. I'm at home where I have two versions of the .deb package file. One is the current version (v1.0.2) and the other is an older one (v0.136.0). With the current version, I get the same results as I did at work - just squares. With the older version, the bug isn't there. Seems fine. So if you were to try the latest version out in Ubuntu (14.04?) anyway I'd expect it might be the same. How was did you Linux get on?

**Comment by batjko** [comment]
Yea so, on Ubuntu 15.04, with the same font I used on Windows (Source Code Pro) and in UTF-8, I am indeed also getting just boxes:
![image](https://cloud.githubusercontent.com/assets/7287076/8708672/5b6009a8-2b35-11e5-9b14-ec653f7b063a.png)

**Comment by martynbiz** [comment]
Great. Well, great it seems reproducible on other machines. Hopefully easier to fix. Thanks for confirming. Any way to raise this as a bug, or is just leaving the issue open OK?

**Comment by batjko** [comment]
This is raised as a bug, although you could change the name of the issue to reflect that it's a problem, rather than a question.

If the issue was reported before, there are a few capable people traversing this repository and will point it out.

**Comment by hetdegon** [comment]
I am getting this too, it used to work properly before, but can't tell since when it started to show only boxes. Same specs as the issue author.

**Comment by donlencho** [comment]
Same here with Chinese characters in a UTF-8 file, tried different fonts but it's definitely not where the problem is (these fonts can display Chinese characters in other programs).
Ubuntu 14.04 and LinuxMint 17.2

**Comment by martynbiz** [comment]
Changed title

**Comment by donlencho** [comment]
Right, but Arabic seems to work, Hebrew doesn't.

**Comment by martynbiz** [comment]
Sorry, I misread. Thanks for the correction. Can I change the label? I can't see how to do that.

**Comment by donlencho** [comment]
Only registered contributors can, the only thing you can do is (again!) rename the issue with something like "[Bug]" before the title. It's not really the intended way but until github allows users to label the issues, it is the only way.
see https://github.com/isaacs/github/issues/148

**Comment by IvoBartecek** [comment]
Same problem here with Japanese characters in a UTF-8 file in Atom in Ubuntu 14.04 LTS.

**Comment by 50Wliu** [comment]
@martynbiz Sorry for the delay.

**Comment by 50Wliu** [comment]
Can someone please see if this is still present in Atom 1.0.12 and above?  Thanks.

**Comment by martynbiz** [comment]
Hi. Just tried with Japanese and looks good, seems fixed now. It was 1.0.19 I tested with. I don't have any other languages (Chinese, Hebrew) to test though.

**Comment by 50Wliu** [comment]
OK, good to hear.  The other languages should with as well now.

**Comment by donlencho** [comment]
Wonderful! Thank you. Tested just now with Chinese in 1.0.19, working fine.
