### ISSUE TITLE
Special string tokens at end of strings cause another closing quote to be created

### ISSUE THREAD

**Issue by 190n** [atom/atom#7900]
When I'm typing a string (in any language) that ends in a special token (e.g. `"hi\n"`), another closing quote is inserted when I type a closing quote:
![bug](https://cloud.githubusercontent.com/assets/7763597/8689621/06108922-2a5f-11e5-8de8-00212d27e2c7.gif)
(The screencast uses JavaScript, but I've seen the issue in enough languages that I think it's not an issue with any one language package.)

**Comment by lee-dohm** [comment]
This is a duplicate of https://github.com/atom/bracket-matcher/issues/80. Please subscribe there for updates.
