### ISSUE TITLE
Performance drop AFTER startup

### ISSUE THREAD

**Issue by jasenc** [atom/atom#7901]
Hey guys, 

Been having some sort of every since going to 1.0.0, currently I am on 1.0.2. 

After opening Atom, everything is super responsive for about 15 - 30 seconds then it can't keep up with how fast I'm typing (like with markdown). I ran through the debugging document and didn't see anything really on performance, but maybe I missed something?

Any whose, thanks!

**Comment by lee-dohm** [comment]
Could you give the following information?

* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by jasenc** [comment]
Certainly, 

* OS X 10.4.4 (actually that could have been when it started)
* No Emmet
* Yes, I can reproduce it in `atom --safe`, and after a fresh uninstall/reinstall with all downloaded packages turned off.

**Comment by mnquintana** [comment]
> OS X 10.4.4

That might be your problem - Atom only supports OS X 10.8 or later.

**Comment by batjko** [comment]
Atom only supports OS X 10.8 or later.
...with a [slight exception](https://github.com/atom/atom/issues/7811) for OS X El Capitan, but that's not an official release yet, anyway.

**Comment by jasenc** [comment]
Sorry guys I typed that wrong. I meant 10.10.4 and the upgrade might have been when it started.

**Comment by jasenc** [comment]
Well I had to stop using Atom completely because of the performance lags. I tried deleting ~/.atom/ as well and every thing seemed to be going well for a couple of minutes but then the lagging started again. 

Hopefully I can get back to using Atom one day...

**Comment by jasenc** [comment]
@lee-dohm This seems to be the Atom Helper high CPU issue. Please let me know if there has been any solutions to that. I'll close this issue though.

**Comment by maxbrunsfeld** [comment]
@jasenc If you get a chance, it'd be really useful to see a javascript CPU profile of what's going on while you're experiencing this lag.

**Comment by jasenc** [comment]
@maxbrunsfeld here is a screenshot, I have the .cpuprofile saved as well if you'd like to see it. Just let me know what the best way to get it to you would be.

![screen shot 2015-07-24 at 1 08 37 pm](https://cloud.githubusercontent.com/assets/11709645/8883639/35d54d52-3205-11e5-8c8c-cefc59efe1c7.png)

**Comment by maxbrunsfeld** [comment]
@jasenc could you zoom in on one of the spikes so we can see the names of some of the functions?

**Comment by jasenc** [comment]
@maxbrunsfeld Sorry, never saw your comment.

You guys can go ahead and close this. The lag is pretty non existent anymore, in fact I only notice it for about a minute when starting a new project. Furthermore I haven't noticed anymore Atom Helpers becoming outrageous resource hogs.
