### ISSUE TITLE
Sidebar menu: add a "Copy Relative Path" item?

### ISSUE THREAD

**Issue by jpetitcolas** [atom/atom#7903]
When right-clicking on a file in the sidebar, we already have:

* Copy Full Path
* Copy Project Path

What about adding a `Copy Relative Path` item, which would copy a path relative to current open file? For instance, with the following tree:

```
src/
    services/
        foo/
            Bar.js
    controllers/
        QuzController.js
```

If I am in the `QuzController` file, clicking on this item would put in the clipboard the string `../services/foo/Bar.js`. It would be especially useful as I often count the dot-dot-slash, wasting some development time. :)

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tree-view? Thanks!

**Comment by jpetitcolas** [comment]
Done [here](https://github.com/atom/tree-view/issues/523). Thanks. :)
