### ISSUE TITLE
Atom doesn't take focus when file is opened on opened window.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#7911]
On Linux (Ubuntu 14.04 - both Unity and GNOME) Atom does not ask my system for focus when a new file is opened on a previously opened file, this could be related to the fact that we split our dev across multiple desktops across multiple screens but ultimately it never even asks for focus.

**Comment by envygeeks** [comment]
I take that back, it does ask for focus, it just doesn't ask in a forceful way we had to disable focus prevention to get it to focus, I'm moving this upstream because this is a bug in Ubuntu probably.

**Comment by jhasse** [comment]
I think this is a duplicate of #4324

**Comment by envygeeks** [comment]
This ticket isn't even open so it's irrelevant whether it's a duplicate.  This is an upstream issue.

**Comment by jhasse** [comment]
Even if it's closed it might be helpful for other people having the same issue and finding this one ;)

**Comment by envygeeks** [comment]
Stop using bad search queries then.
