### ISSUE TITLE
Chews a lot of Memory on my  Mac Book Pro

### ISSUE THREAD

**Issue by VIF-AndrewRutazamba** [atom/atom#7912]
I think this is a wonderful tool, and it has a great future. Comparing to most common IDE such as Eclipse this tools hogs a lot of memory considering it's just a text editor. When used I can see my memory  go down from 8gb to 2gb once start using it and the response is really slow. I have a Mac Book Pro with 16GB I can run Photoshop, IDE, two browsers with multiple tabs and I don't see any performance issue, but if I open Atom with 2 browser it lags and performance is really bad.

**Comment by pbohun** [comment]
This seems to be related to issue #7883 
I can confirm this happens on my macbook pro as well. Appears to be a memory leak.

Running OS X 10.10.4
Atom v1.0.2

Memory usage increases dramatically as I go through my edit/save cycle. Eventually responsiveness for typing a single character becomes slow and the editor must be closed and restarted. Depending on the amount of RAM installed it may take a while to reach this level of low responsiveness.

**Comment by batjko** [comment]
Can you guys try running Atom in safe mode (`atom --safe`) and confirm whether you see a difference? This will disable community packages, which helps eliminate them as culprits.

A lot will depend on the packages you have installed.
Having said that, performance improvements in Atom's core and bundled packages are also always happening.

**Comment by pbohun** [comment]
I am performing experiments to compare the behavior between safe mode and standard mode and will report back once I have results. I run almost no extra packages, but it's quite possible one is the culprit.

**Comment by pedrosanta** [comment]
:+1: I'm also experiencing issues with very heavy memory load for Atom. Which is unfortunate. Probably going back to ST. :confused:
