### ISSUE TITLE
I can't install atom (windows 7): "Installation has failed: Failed to extract installer"

### ISSUE THREAD

**Issue by jakedemianrosetta** [atom/atom#7915]
I downloaded the installer from the official site and when I run it, I get the error message in the title.  I've been researching this issue and I've found that problem may lie in Update.exe.  When I go to

C:\Users\myname\AppData\Local\SquirrelTemp

I find the Update.exe file.  I can open and edit all other files in this directory, but when I try to open Update.exe, I get the error:

"Windows cannot access the specified device, path, or file.  You may not have the appropriate permissions to access the item."

But when I look at the security tab in the properties dialog of Update.exe, it shows that my account has full access.

I have no idea how to fix this issue.

**Comment by batjko** [comment]
What about the entire AppData folder? Any permission issues on that one?

Also, the access error on update.exe might not be related to the update.exe itself, but rather with what it tries to do (e.g. write to a temporary folder or something).

Do you have any temp folders or other restricted folders on your machine that are not permitted for your account (but usually are for most people)?

**Comment by jakedemianrosetta** [comment]
Yes, I can open and edit any and all files in AppData. I don’t know the answer to the temp folder question, however.  As far as I know, I don't have any directory restriction set up on this PC ,but I could be wrong and I'm not entirely sure how to check for permissions of a folder I don't know the name of.

**Comment by batjko** [comment]
cc @paulcbetts on this one.
Not sure which part of the installer may run into this error.

**Comment by paulcbetts** [comment]
Log file? Should be in that SquirrelTemp directory

**Comment by 50Wliu** [comment]
Also, can you try to disable any antiviruses you have when running the installer?

**Comment by jakedemianrosetta** [comment]
@paulcbetts Not seeing a log file in thar directory.  This is everything in that directory: 
![image](https://cloud.githubusercontent.com/assets/13152997/8723508/3e92f1a2-2b9c-11e5-9879-35007e24a657.png)

**Comment by batjko** [comment]
@jakedemianrosetta Can you check this one:
![image](https://cloud.githubusercontent.com/assets/7287076/8728428/f40a87da-2bdc-11e5-8f5c-097d6df4141c.png)

**Comment by jakedemianrosetta** [comment]
@batjko That's the directory I was in in the image I posted.

**Comment by jakedemian** [comment]
@paulcbetts So I managed to generate the SquirrelSetup.log file, by running the updater as administrator but not the setup.  If I set both to run as administrator, I get caught in an infinite loop of windows asking me for permission to open some file.

The log file only has one line, however:

Program: Starting Squirrel Updater:

**Comment by shawmanz32na** [comment]
I would like to +1 this. Running the latest (1.0.5) installer fails immediately, and the only file in the ~/AppData/Local/SquirrelTemp directory is an empty SquirrelSetup.log file. I'm running Windows 10 x64.

**Comment by lijojacob1982** [comment]
I disabled my antivirus and it worked fine

**Comment by FagnerMartinsBrack** [comment]
Maybe related to https://github.com/atom/atom/issues/9094?

**Comment by pgcm** [comment]
Had the same issue on Windows 7 x64. Disabling antivirus (Mcafee) worked for me.

**Comment by inference2015** [comment]
I also have the same problem.I run installer with administrator rights but still the message "Installation has failed; Failed to extract installer" appears.

**Comment by lisboaxd** [comment]
I disabled my antivirus and it also worked

**Comment by panchalnv** [comment]
1) Download Atom-Windows.zip folder with this link: https://github.com/atom/atom/releases/tag/v1.5.3
2) Unzipped the folder
3) Inside this folder, double click on Atom.exe to open the editor.

**Comment by damieng** [comment]
@lisboaxd and @lijo-jacob can you let me know which antivirus product you were using that interfered?

**Comment by lijo-jacob** [comment]
For me it was McAfee.

**Comment by damieng** [comment]
Appear to be issues with McAfee and Kapersky plain flat-out blocking our installer. Not much we can do here but right now but will continue to monitor reports.

**Comment by dolkee** [comment]
In India its netprotector which is causing the problem I excluded atom exe to start it now its working

**Comment by damieng** [comment]
Thanks @dolkee it's good to know which antivirus programs are getting overprotective!

**Comment by paulcbetts** [comment]
> Appear to be issues with McAfee and Kapersky plain flat-out blocking our installer. Not much we can do here but right now but will continue to monitor reports.

We're enlisting in the whitelist program for Slack to try to resolve this - it should carry over to all Squirrel apps

**Comment by damieng** [comment]
That's awesome news, thanks Paul!

**Comment by xpg94** [comment]
Avast antivirus blocked the installation on my windows 7..

**Comment by smallx** [comment]
**Yeah, yeah. 关掉杀毒软件就行了。**

**Comment by remix2** [comment]
This message error occurs because I have not enough free space on my disk C:\

**Comment by RANDALUZ** [comment]
Good afternoon , I have not heard very well if they said the solution to the problem , but also happens ami me , and I'm desperate means , PLEASE HELP !!!!!!!!

**Comment by damieng** [comment]
1. Turn off anti virus temporarily
2. If that doesn't work either try portable zip version or paste contents of squirrelsetup.log

**Comment by ShivaShinde** [comment]
Same problem, I have uninstalled my macfee, I didnt find any options, So, I kicked off ;) Windows10 should be okay without anti-virus!!

**Comment by FagnerMartinsBrack** [comment]
Guys, this issue is **CLOSED**. If you want to report a new issue, please create a new one with proper stacktrace like https://github.com/atom/atom/issues/9094.

Commenting on closed issues will make no difference since the maintainers will not dedicate any effort to fix this!

**Comment by 50Wliu** [comment]
> Commenting on closed issues will make no difference since there will be no visibility and therefore the maintainers will not dedicate any effort to fix your error!

This is not true.  I read all comments, including ones on closed issues.  In addition, @damieng provided assistance just a bit further up, despite the issue being closed.

**Comment by FagnerMartinsBrack** [comment]
@50Wliu 

> This is not true. I read all comments, including ones on closed issues. In addition, @damieng provided assistance just a bit further up, despite the issue being closed.

Good to know that this project has enough capacity to follow closed issues, but does it really helps if someone just posts that the problem is happening and no evidence that it is the same issue? Wouldn't be better to encourage creating a new issue with log errors so that the maintainers can analyze objectively if the problem is the same or not?

I am saying this because it just seems common sense in OSS and the contributing guidelines shows a lot of suggestions on how to create a bug report that can drive action.

**Comment by 50Wliu** [comment]
> Wouldn't be better to encourage creating a new issue with log errors so that the maintainers can analyze objectively if the problem is the same or not?

Yeah, I didn't include this in my comment, but that's generally what I do on closed issues (see for example my comments in [this issue](https://github.com/atom/atom/issues/1603#issuecomment-214870583)).

**Comment by FagnerMartinsBrack** [comment]
> In this case though there's really only two ways that the Windows installer can fail: paths are too long or an AV is stopping the installation.

Are you sure there are only two ways? Most of the time, trying to create a simple model for complexity can make us reach to conclusions that contain [too many assumptions](https://en.wikipedia.org/wiki/Occam%27s_razor).

**Comment by 50Wliu** [comment]
Ok, >95% of the issues we receive :wink:.  If someone opens up a new issue (or comments on one) about the installer and the log provided doesn't match any of the two symptoms listed above, then of course it's triaged further.  Though this is getting off-topic now; are you a member of the [Atom Slack channel](https://discuss.atom.io/t/join-us-on-slack/16638)?  If so, I'd be happy to continue this conversation with you there!  I'm `@wliu` on Slack.

**Comment by FauziFerdiansyah** [comment]
xx <script> I Cant Install atom ,, Failed Failed -_-</script> xx
