### ISSUE TITLE
Branch undo

### ISSUE THREAD

**Issue by mrthebob** [atom/atom#7917]
One very useful feature that vim has is undo branching. This feature can be a real life saver. Let's say I make some changes, undo them, and then start typing again, only to realize that I needed some of those other changes. Without undo branches, those changes are gone. With them, I am free from worry about losing work!

See: http://vim.wikia.com/wiki/Using_undo_branches

It would be so nice for Atom to have this as well!

**Comment by bronson** [comment]
Yes, gundo.vim saved me from a pile of hurt a year ago.  I'd hit undo a few tens of times to find something I'd missed, then finger-slipped and typed a letter.  Without gundo I'd be tearing my hair out at having to retype the last 1/2 hour of work.  With gundo, I undid the keypress, then redid all my work.  Easy!

So :+1: :+1: for undo branches.  I'm uncomfortable being without them.

**Comment by wolftune** [comment]
Just for clarity, the undo tree exists in vim without gundo. Gundo is just a way to browse the undo tree, and another competing option is [undotree](https://github.com/mbbill/undotree).

Indeed, Atom should add comparable functionality.

**Comment by SlimeQ** [comment]
I'm not in a position to experiment with this at the moment so this is purely a spitball, but might it be practical to implement undos using git? then the tree could be manipulated using some javascript/html git gui

**Comment by wolftune** [comment]
@SlimeQ while spitballing has a place (so not trying to be overly critical here), undo in the editor is every single little action. Git as is tracks only commits and diffs, it doesn't track every step of getting there. It really seems it would be quite a hack and not make sense.

Atom *already* has an undo history! The only thing it doesn't have is keeping branches of undone work and a way to browse those branches.

**Comment by SlimeQ** [comment]
Yeah I know what git does. And obviously I know atom has an existing undo history... but wouldn't implementing branches mean essentially implementing a basic diff versioning system anyways? I'd imagine using git would be far simpler and reliable than any home rolled solution, plus it would allow for some fun integrations with remote repositories in the future. I have no doubt it would be possible to add and commit incremental changes to some hidden branch or something when adding to the undo history, but I'm unsure how drastically this would affect performance. 

of course I'm just talking out of my ass until I actually find where undo is implemented in the source code. can anyone point me in the right direction? I'd love to experiment with this, as I frequently find myself screwing up my undo history and having to redo work.

**Comment by SlimeQ** [comment]
https://atom.io/packages/git-wip
@relevant

**Comment by styx** [comment]
👍 for the feature

**Comment by paradoxxxzero** [comment]
Here's a package (hack) that tries to mimic this behavior https://github.com/paradoxxxzero/atom-undo-tree

**Comment by mpacer** [comment]
I would still be interested in this feature being supported by the core of atom.
