### ISSUE TITLE
config onDidChange does not return keypath in event

### ISSUE THREAD

**Issue by jamesgpearce** [atom/atom#7918]
Per docs (https://github.com/atom/atom/blob/v1.0.2/src/config.coffee#L418) there should be oldValue, newValue, keyPath in the event passed to the callback. In fact only the first two are present

I think https://github.com/atom/atom/blob/v1.0.2/src/config.coffee#L871 is the issue. Correct?

**Comment by abe33** [comment]
Yes, you're right, there's also https://github.com/atom/atom/blob/v1.0.2/src/config.coffee#L1017 that need to be changed as well.

**Comment by jamesgpearce** [comment]
OK, tagged `documentation` but I think the path would be pretty interesting. Or is there a reason why it can't be surfaced?

**Comment by benogle** [comment]
cc @nathansobo I cant remember if we took the keyPath out? I remember having a discussion about it.

**Comment by nathansobo** [comment]
My memory is a bit fuzzy, but I think the reason is that we wanted to encourage people to observe a *specific* key path, which made supplying the key path redundant.

**Comment by maxbrunsfeld** [comment]
Yeah, you are now *always* observing a specific key-path. If you don't pass a key-path, you are observing the empty key-path (the entire object). The `oldValue` and `newValue` always represent the values of the key-path that you're observing. So it doesn't really make sense to pass a key-path any more.
