### ISSUE TITLE
Differing snippet behaviour

### ISSUE THREAD

**Issue by idleberg** [atom/atom#7919]
I have just received an [issue](https://github.com/idleberg/atom-semantic-ui/issues/2#issuecomment-121737883) for one a package of Atom snippets. The package in question was converted from Sublime Text and it used `.text.html -text.html.markdown` as scope. Now, I know that Atom uses `source.gfm` for Markdown, but that's not the point here. The snippets worked perfectly on Mac OS X using that scope, but they did not work at all on Windows. Thought that you might want to look into that.

However, I was wondering if Atom even supports scope in the mentioned format, would `.text.html -source.gfm` be a valid scope (I'm not near my computer, otherwise I'd simply test it)

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/snippets? Thanks!
