### ISSUE TITLE
The program can't start because chromiumcontent.dll is missing from your computer

### ISSUE THREAD

**Issue by Michael-0** [atom/atom#7920]
Just installed Atom 1.0.2 on Windows 8 x64, I get this error on first launch.

![Error screenshot](http://i.imgur.com/kXkM066.png)

It seems that everything is working just fine anyway.

**Comment by jscissr** [comment]
I get the same error when I click "Open with Atom" in the context menu of a folder in Explorer. Atom starts fine when opening it normally.

**Comment by damieng** [comment]
Are you still getting this error on newer builds?

**Comment by jscissr** [comment]
No, for me it didn't happen anymore.
