### ISSUE TITLE
[Feature Request] Additional menu bar with icons as shortcuts

### ISSUE THREAD

**Issue by stebiger** [atom/atom#7926]
Hey,

it would be nice if there would be a possibility to define an additional menu bar that can contain (default or custom) icons with shortcuts to commands like save file, save all etc.

Most editors like Notepad++ offer such menubars - for everyone that doesn't like that it is always possible to disable those bars

![image](https://cloud.githubusercontent.com/assets/8200750/8717406/a12554f0-2b9b-11e5-8682-f738355955c7.png)

**Comment by nguyengiangdev** [comment]
I don't think that is better feature, when coding you use icon to execute actions or you use shortcut key, i like shorts cut key for every task, example in minimal all eviroment: hide side bar, search file i use short cut key command + shift + p, .... You must use short cut key for better coding. Thanks

**Comment by stebiger** [comment]
True story - and I do use lots of shortcuts which boosts my speed and performance to the moon ;-) - anyhow - to distribute and spread the use of atom editor to make it a widely used one you should also have possibilites for junior dev's, newbies and everyone that is not that familiar (yet) to start using an editor that grows with their abilities to code.

Imagine a young boy or girl, hearing about atom and want to give it a try. While not having much background in programming the young dev relies on lots of visual help - but by getting more and more familiar with developing, shortcuts, editor assistance etc. it customizes atom more and more to it's own needs and becoming a huge fan.

Nobody grows up as a professional dev, when I remember my first years in programming around 16 years ago and compare it to my behaviour today everything has changed.

notepad++ is a widely spread editor with lots of users - because it meets the req's of prof dev and young dev in same way. 
Have lot's of assistance or purely shortcut behaviour it's your choice to display or disable a menu bar - but just because there is one has nothing to do with a "bad feature".

**Comment by mnquintana** [comment]
Thanks for the suggestion! I don't think this is something that will ever be added to Atom core by design, but something like this would be a great idea for a community package.

**Comment by abe33** [comment]
You can probably take a look at all these packages: https://atom.io/packages/search?q=toolbar
Many of them are built on top of suda's tool-bar package.

This one in particular looks close to what you're proposing: 
https://atom.io/packages/tool-bar-almighty

**Comment by stebiger** [comment]
As I am not searching for such a toolbar but just proposing idea for features I think this can be closed than as you have stated such a feature will not be part of atom. This is not a problem and the discussion should therefore be ended :)
