### ISSUE TITLE
No way to return to install "Featured Packages" list without restarting editor

### ISSUE THREAD

**Issue by edmorley** [atom/atom#7927]
Using Atom 1.0.2 on Windows 8.1 x64.

1) Open settings
2) Switch to the "Install" section & observe page shown
3) Type "foo" in the search box and press enter
4) (After deciding the search results didn't contain anything useful) Try to return to the original page that listed "Featured Packages" so you can install one of those

Expected:
One or more of the following should reset the install settings page, so that it shows the "featured packages" list:
* Deleting "foo" from the search field and pressing enter
* Switching to another settings page (eg keybindings) and then back to the "install" page
* Closing the settings tab entirely and then reopening it
* Or some kind or breadcrumb navigation, like there is on the themes settings page, when you go deeper into a theme's individual settings

Actual:
None of the above allows for returning to "featured packages". The only solution I found was to exit Atom and reload it. Ideally all/most of the above would work in resetting the install page.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/settings-view? Thanks!

**Comment by edmorley** [comment]
Sure, filed as https://github.com/atom/settings-view/issues/590
