### ISSUE TITLE
Atom does not work over NX

### ISSUE THREAD

**Issue by Weuxel** [atom/atom#7928]
Atom does not start in an NX environment.

App load time: 150ms
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[7643:0716/110551:ERROR:gl_surface_glx.cc(357)] GLX 1.3 or later is required.
[7643:0716/110551:ERROR:gl_surface_x11.cc(56)] GLSurfaceGLX::InitializeOneOff failed.
[7643:0716/110551:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[7643:0716/110551:ERROR:gpu_child_thread.cc(146)] Exiting GPU process due to errors during initialization
atom: Fatal IO error 11 (Ressource is not available) on X server :1000.0.

**Comment by batjko** [comment]
I might just be terribly ignorant, but can you mention what an NX environment is?

**Comment by Weuxel** [comment]
Sure, NX is a remote desktop protocol that enhances the native X display protocol by various compression schemes and tunneling it over SSH. (https://en.wikipedia.org/wiki/NX_technology)

If you work in you homeoffice for example, you log in to you workstation at your company via NX and  have your workstations desktop even on a slower line on a thin client or other less potent computer.

Usually there is no difference in capability, you can even watch videos.
Unfortunately Atom is the first Tool, which does not seems to work properly this way.

**Comment by thomasjo** [comment]
This should be opened on the [Electron repo](https://github.com/atom/electron/issues) since this is a low-level error related to Chromium (and GPU rendering). Please re-open the issue there. Thanks!

**Comment by adamkdean** [comment]
I am also having this issue, 14.04.3 and xrdp. NoMachine doesn't seem to give a valid package for Ubuntu to install. It would be nice if Atom/Electron wasn't so awkward, I have to admit.
