### ISSUE TITLE
XML folding loses scope in multiline text values

### ISSUE THREAD

**Issue by jgeorgeson** [atom/atom#7934]
Looking at an Ant build file with a target that uses an echo task with a CDATA block, the folding loses track of the folding levels when it sees the <?xml> entities. Something like this

```
<?xml version="1.0" encoding="UTF-8"?>
<project name="lgcbuildutils">
<target name="init">
...
</target>
<target name="clean">
...
</target>
<target name="compile">
...
</target>
<target name="special">
        <echo file="${reportFile}"><![CDATA[<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="file:///usr/share/mylib/conversion.xsl"?>
<modules/>]]>
        </echo>
</target>
<target name="deploy">
...
</target>
</project>
```
When I fold all, it leaves the <?xml-stylesheet> unfolded, and everything after that line is folded under it. In the first screenshot you can see that everything between two such echo tasks was folder under the first <?xml-stylesheet>. In the second you can see the <target> and the first <?xml-stylesheet> unfolded.

![folded](https://cloud.githubusercontent.com/assets/10238523/8729013/2155114e-2bae-11e5-9a1b-b2ef08147f35.png)

![unfolded](https://cloud.githubusercontent.com/assets/10238523/8729018/2ec5b75c-2bae-11e5-9088-f34c0af4ad80.png)

**Comment by jgeorgeson** [comment]
Actually it looks like it's whenever there's a multi-line text value, and not because of the <?xml-stylesheet> element specifically. I'm seeing the same behavior with something like this

```
    <echo>
this is a
multiline text value
of an XML node
    </echo>
```

**Comment by abe33** [comment]
Hi @jgeorgeson , it looks like an issue with the [language-xml](https://github.com/atom/language-xml) folding settings. Can you please move this to [atom/language-xml](https://github.com/atom/language-xml/issues) and then close this issue? Thanks!

**Comment by jgeorgeson** [comment]
will do
