### ISSUE TITLE
Line wrap inserts wrap character that is not accounted in buffer

### ISSUE THREAD

**Issue by stanzheng** [atom/atom#7935]
when there is a tab character and the line wraps seems to place a tab character into the buffer.
the next line is offset by one character causing editing to be offset by one.

![atombug](https://cloud.githubusercontent.com/assets/3683993/8729248/132f2dc0-2bb8-11e5-8fe0-9b872121c54c.gif)
Edit:**The line I'm editing is on the same line number and wrapped as in the buffer. apologies for not capping from the line number position**

to note\* it only affects the line where the line 
1) wraps, 
2) adds a tab into the buffer

atom: Version 1.0.2 (1.0.2)
os: OSX 10.9

**Comment by stanzheng** [comment]
heres a link to a gist that demonstrates the above.

https://gist.github.com/stanzheng/a79eb4aab85ee548db5f

**Comment by abe33** [comment]
I could confirm this issue on 1.0.3-92e495d in safe mode.
