### ISSUE TITLE
Find/Replace in Project does not have expected behavior when pattern field is empty

### ISSUE THREAD

**Issue by eliasak** [atom/atom#7936]
It seems to me that in "Find in Project"/"Replace in Project" dialog, it is **not the expected** behavior that an empty pattern field means all files.

 It would be clearer if the pattern field is prefilled with "*" or "*.*", as that is the behavior when the pattern field is empty.

Or make the empty pattern field only replace in the current/active buffer

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace? Thanks!

**Comment by eliasak** [comment]
Thanks,

Opened at https://github.com/atom/find-and-replace/issues/451
