### ISSUE TITLE
Can't find an installed package in "Packages", have to search it in "Install"

### ISSUE THREAD

**Issue by DiThi** [atom/atom#7937]
![installed_package](https://cloud.githubusercontent.com/assets/1127198/8732680/4d56525c-2bff-11e5-9622-5b3919c56a2d.gif)

I forgot to capture the mouse cursor, but I hope it's clear the package is installed.

**Comment by mnquintana** [comment]
What version of Atom are you using?

**Comment by DiThi** [comment]
1.0.2

**Comment by mnquintana** [comment]
This issue was moved to atom/settings-view#591
