### ISSUE TITLE
HTML Tag Enhancements

### ISSUE THREAD

**Issue by tuhinkarmakar** [atom/atom#7938]
#### Drag and drop files to get HTML tags

**`img`**
_An image dragged and dropped into the editor would generate `<img src="{file-name}.{extension}" alt=""/>`_

**`link`**
_A CSS file dragged  and dropped into the editor would generate `<link rel="stylesheet" href="{file-name}.css"/>`_

**`script`**
_A script dragged  and dropped into the editor would generate `<script src="{file-name}.js" type="text/javascript" />`_

**Comment by mnquintana** [comment]
Thanks for the suggestions! For future reference, please search for existing issues first, and please open a separate issue per feature request – it's much harder for us to keep track of them when there are multiple feature requests in the same issue.

I think these all sound like great ideas for community packages.

**Comment by tuhinkarmakar** [comment]
Yes, I did search the existing issues first. But I didn't find anyone asking for these features. Maybe someone did, but they used words different than what I searched for.

Okay, I will keep that in mind from next time. Should I break this issue into two issues?

**Comment by izuzak** [comment]
> Should I break this issue into two issues?

Yes, you should open one issue per feature request or bug report.

**Comment by tuhinkarmakar** [comment]
Alright, I will split this issue into 3 issues. One last question, would it be better to move this issue to the **language-html** repository?

**Comment by izuzak** [comment]
> would it be better to move this issue to the language-html repository?

You can keep them here for now. But I agree with @mnquintana on this one -- these ideas you suggested sound like great candidates for community packages, rather than something that would be implemented in Atom core or core packages. Have you considered creating a package for these features or suggesting them on the forum? https://discuss.atom.io/c/packages

**Comment by tuhinkarmakar** [comment]
> Have you considered creating a package for these features or suggesting them on the forum?

Well, yes, I thought of creating a package. I read the Atom Flight Manual. But the instructions were not intuitive to me. I couldn't follow along. So I thought I'll share my ideas here. And no, I didn't know that I can suggest packages in the forum.

**Comment by tuhinkarmakar** [comment]
I have split the issue into 2 issues.

**Comment by batjko** [comment]
The drag&drop feature and the popups for tag partners, both of which are awesome ideas btw! - should also be separated as they are unrelated.

I could see all of these things being implemented by some of the intrepid and very active package devs in the not too distant future.

**Comment by tuhinkarmakar** [comment]
Alright, I'll do that.
