### ISSUE TITLE
Java programming support

### ISSUE THREAD

**Issue by TekxWolf** [atom/atom#7941]
Already I love Atom for Web Development 
But I am also a strong Java Developer. I would like to see more mutual support for Java Programming such as:
- Exporting Jars
- Adding Libraries/Archives

I currently use Eclipse but I love Atom, I'd even be willing to give up more storage to have this feature part of my Atom Application

Side note: I run on Ubuntu 14.04 and I am using the .deb package version

**Comment by Tribex** [comment]
@TeksWolf This would probably be something for a (large) extension or set of such extensions.

**Comment by TekxWolf** [comment]
I imagine it would be, although I'm sure if they teamed up with the Eclipse team they could produce a "universal" IDE to cover more than just Web Development and Java Development.

With Atom's sleek and new ui thats hackable to the core, and their support for all languages, they could integrate Eclipse's level of knowledge and support to produce an OpenSource IDE while still maintaining the original beliefs behind each project.

Although I imagine it would come default with just Web Development features and have full size add ons much like Atom does with packages available to download Instead of swamping the origin with heaps of data

**Comment by thomasjo** [comment]
This sounds like a great idea for a community package. Check out the [Atom Flight Manual](https://atom.io/docs/latest/hacking-atom-package-word-count) for some tips on getting started with package development.

Perhaps starting a thread on [Discuss](http://discuss.atom.io) would be a good way to get the ball rolling on the community effort.
