### ISSUE TITLE
Save new file creates file open error (automatic filename is set to init-script)

### ISSUE THREAD

**Issue by stebiger** [atom/atom#7943]
Trying to save a new file creates a file open error dialog and the filename is set to init-script.
Windows shows also a error dialog

![image](https://cloud.githubusercontent.com/assets/8200750/8745792/72d50fc6-2c83-11e5-9398-b146470b7d55.png)

Translation is:
You can't use this Path with this application.
Choose another Path

**Comment by stebiger** [comment]
What kind of more information do you need?

**Comment by 50Wliu** [comment]
> What kind of more information do you need?

For starters, what Atom version are you using?  Can you try to completely uninstall (including removing the `.atom` folder in your user directory) and reinstall Atom and see if that solves your problem?

**Comment by stebiger** [comment]
Thank you for giving information.

I am using atom 1.0.2 - Have not tried but pretty sure that removing and reinstall will fix the issue as I am using atom since 1.0 and this just came up some days ago.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/7943#issuecomment-122272964. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
