### ISSUE TITLE
Wrap at end of syntax highlighting carries highlighting to next line

### ISSUE THREAD

**Issue by halleycarleton** [atom/atom#7947]
If a line of code wraps and the break is right after a section of syntax highlighting the rest of that line will have that same syntax highlighting.

Here's a screenshot:
![Screenshot](http://i.imgur.com/B03jFpd.png?1)

System Specs:
Ubuntu 14.04
Atom 1.0.0
language-javascript 0.80.0

*I'm pretty sure this is an issue with Atom and not the language specific syntax highlighter because I've reproduced the issue in multiple languages.*

**Comment by izuzak** [comment]
Thanks for the report, @halleycarleton. This sounds very similar to https://github.com/atom/atom/issues/7068 -- I think it's the same problem, so I'm closing this in favor of that and cc-ing @nathansobo since he assigned himself to that one.
