### ISSUE TITLE
setting to open files as tabs/windows

### ISSUE THREAD

**Issue by ntessore** [atom/atom#7958]
While many voted for the changes in #3355, there should be an option to select the behaviour of Atom when opening individual, unrelated files (e.g. from the Terminal or dropping onto the dock icon in OS X). There could be a simple checkbox in the settings to "open files in new window", which restores the previous behaviour.

**Comment by nhep** [comment]
Please can someone add this setting?  I'd really like to open files in a new window if not in the current window's project tree (which was the old behaviour I believe).
