### ISSUE TITLE
Mouse keys are broken... in some way?

### ISSUE THREAD

**Issue by LynnCo** [atom/atom#7959]
I'm having a bunch of strange issues with atom where like, the mouse keys (particularly left click + scroll scrollbar) feel like they are mapped incorrectly? Or it also seems like ALT is being held down? For example, sometimes `scroll down` would act like `left click`, sometimes `left click` would act like `CONTROL + left click` rarely, but usually it was like `right click`. At least, I assume it was right click because left click and right click did exactly the same thing (which was: bring up a one option menu with an option to paste something)

Also, it was only the mouse keys. The keyboard was just fine.

Extra information:

* Everything else I tried using had no issues whatsoever (ie. sublime text, google chrome, etc)
* I was on an Ubuntu 14.04 virtual machine through virtualbox hosted on Windows 7
* I got atom via this ppa https://launchpad.net/~webupd8team/+archive/ubuntu/atom
* This started immediately upon launching atom, and never went away (related: if your response to seeing this issue is "you should have googled X first" then I just won't bother)

**Comment by 50Wliu** [comment]
Chromium 41 and under detects Virtualbox as touch-friendly, so Atom automatically switches to touch input mode.  This will be addressed in #7877 and you can see the original bug reports at #6306, #6243, and #6219.
