### ISSUE TITLE
editor.bufferRangeForScopeAtCursor('link') returns undefined

### ISSUE THREAD

**Issue by zhuochun** [atom/atom#7961]
How to reproduce, given an empty markdown file:

``` markdown
[link](http://example.com)_
```

Where `_` represents the cursor position (at the end of the link)

And I try to get the buffer range for scope `link`:

``` javascript
editor = atom.workspace.getActiveTextEditor()

// check link scope selector is there
cursor = editor.getLastCursor()
cursor.getScopeDescriptor().getScopesArray()
// => ["source.gfm", "link", "markup.underline.link.gfm", "punctuation.definition.end.gfm"]

// since link scope is there, when i try to get the buffer range
editor.bufferRangeForScopeAtCursor('link')
// => undefined
editor.bufferRangeForScopeAtCursor('markup.underline.link.gfm')
// => undefined
```

**Comment by izuzak** [comment]
Thanks for the report, @zhuochun :bow:.

@nathansobo I'm seeing this as well, but not sure if that's expected or not. I guess I also expected that if a scope is listed in `cursor.getScopeDescriptor().getScopesArray()`, then `editor.bufferRangeForScopeAtCursor` for that scope would return a non-undefined value. Any chance that in this case `cursor.getScopeDescriptor().getScopesArray()` should have returned just `["source.gfm"]`? In other words, should the scopes when the cursor is after the closing `)` in the example above be different than the scopes when the cursor is in front of the closing `)`? (Currently, they are the same.)

**Comment by nathansobo** [comment]
There's probably something going on with the new token representation. I can investigate.
