### ISSUE TITLE
Atom doesn't remember sessions on Windows 10 RTM

### ISSUE THREAD

**Issue by eliasjorgensen** [atom/atom#7964]
I installed Atom in Win10 and everything seems to work fine. But when i reopen Atom i see nothing but an untitled tab. I haven't installed any packages or anything, so it's a vanilla install.

**Comment by mnquintana** [comment]
What version of Atom are you using? How did you install it? How are you quitting and reopening Atom?

**Comment by eliasjorgensen** [comment]
I downloaded the newest version from the website (atom.io).
So i am running version 1.0.2 and i'm opening it from the start menu/ the desktop shortcut. I'm quitting by hitting the close button in the top right corner.
I'm coming from Windows 7 where i had no problems, so this is very strange to me.

**Comment by Exilz** [comment]
Same problem on OSX, latest version aswell. Even on a blank installation of atom without any plugin.

**Comment by eliasjorgensen** [comment]
I have no plugins installed either. Completely clean installation of Atom.
I have tried uninstalling, removing all the folders and files it leaves behind and installing it again to no success.

**Comment by Starsam80** [comment]
i have windows 10 build 10162 and atom 1.0.2 works just fine for me, it loads plugins and previously opened tabs

**Comment by eliasjorgensen** [comment]
My username is "elias", so that shouldn't be the issue.
It actually worked fine on build 10162 with plugins and everything, but then i upgraded to the newest build. I believe it's build 10240, but don't quote me on that. It's the RTM one.
After i upgraded and opened Atom, it would always show the project folder and the file i had open before upgrading to the newest build.
Then, as i said before, i tried uninstalling it, removing all the files and folders it left behind and doing a clean install. Now it's just showing a blank "untitled" tab and nothing else when i open it.

**Comment by eliasjorgensen** [comment]
I just tried using Atom again, and now it remembers my recent files etc.
I've gotten a couple of updates for Windows, so i believe that Windows itself might have been the problem. 
Issue closed, i guess.
