### ISSUE TITLE
Images broken on available updates

### ISSUE THREAD

**Issue by Clemmy** [atom/atom#7969]
<img width="1440" alt="screen shot 2015-07-19 at 2 53 34 pm" src="https://cloud.githubusercontent.com/assets/3696934/8767298/12a85000-2e26-11e5-9e66-8b445d5abf0e.png">

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/settings-view? Thanks!

**Comment by Clemmy** [comment]
Oops, got it!
