### ISSUE TITLE
Atom breaks PATH variable on Windows 7

### ISSUE THREAD

**Issue by pcan** [atom/atom#7970]
When I open the console in Atom, if I evaluate process.env['PATH'], atom appends :/usr/local/bin at the end of my PATH variable, breaking the last path (in windows these are separated by semicolon). Following there is an example:

[more variables here...];C:\Program Files\nodejs\;C:\Users\Piero\AppData\Local\atom\bin;C:\Users\Piero\AppData\Roaming\npm:/usr/local/bin 

In this case, since the broken path is the npm one, i was not able to launch grunt.cmd from atom-build. As a temporary workaround i appended a semicolon at the end of my PATH environment variable, so it now looks as following:

[more variables here...];C:\Program Files\nodejs\;C:\Users\Piero\AppData\Local\atom\bin;C:\Users\Piero\AppData\Roaming\npm;:/usr/local/bin 

And now it works, but I think this could be hard to detect.

**Comment by Stanzilla** [comment]
Related https://github.com/atom/atom/issues/7757

**Comment by damieng** [comment]
I suspect the reworking of the PATH code mentioned in the related issue has also fixed this. Please re-open if you experience this bug beyond 1.7.
