### ISSUE TITLE
Some wierd errors with python and ruby

### ISSUE THREAD

**Issue by huttarichard** [atom/atom#7971]
When I used atom I got error like this one:

```
if self.inHistory(nickname) > 0:
                            ^
SyntaxError: invalid syntax
```

If I rewrote the same exact line in a vim, magically start working, but I didn't change a letter!
And happens for ruby too...

**Comment by mnquintana** [comment]
What file encoding do you have active for the files in question? Can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? (`atom --safe`)

**Comment by huttarichard** [comment]
So far, happens for me like 8 times, so not really sure If I can reproduce it (this kind of errors are worst).
But this maybe helps, if I had header with encoding for python `# -*- coding: utf-8 -*-` the error is the one above, but if I removed the encoding line from py file the error changed to
`SyntaxError: Non-ASCII character '\xc2' in file /Users/richard/Desktop/ripebeast/ish/simnode/job.py on line 136, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

Editor has enabled UTF-8. What I know for sure, that even If I rewrote the same exact line in atom still happens (and I try this 3 times in a row)

**Comment by mnquintana** [comment]
Can you post a list of your installed packages? (`apm list --installed`)

**Comment by huttarichard** [comment]
/Users/richard/.atom/packages (2)
├── angularjs@0.3.0
└── rails-snippets@1.10.0
