### ISSUE TITLE
Keyboard shortcut "ALT GR" + "G" (prints slash "/") doesn't work

### ISSUE THREAD

**Issue by rodrigocprates** [atom/atom#7972]
Simply when I use keyboard shortcut ALT GR + G it doesn't print "/".

**Comment by mnquintana** [comment]
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom-keymap/issues/35 – please subscribe there for updates.

**Comment by rodrigocprates** [comment]
solved by installing keyboard-localzation atom package (https://github.com/andischerer/atom-keyboard-localization)
