### ISSUE TITLE
GitRepository::checkoutReference doesn't work with remote or tag references

### ISSUE THREAD

**Issue by olmokramer** [atom/atom#7973]
The following works just fine
```js
repository.checkoutReference('refs/heads/branch');
```
But when I have a remote branch named `remote-branch` on the `origin` remote and I try
```js
repository.checkoutReference('refs/remotes/origin/remote-branch');
```
It fails to check out the remote branch. The same is true for tags.

**Comment by izuzak** [comment]
Seems like that's [expected behavior](https://github.com/atom/git-utils/blob/5f0b6e70c77aeb5f23e831bb1c591d5a39cc3467/src/git.coffee#L110) and only refs in `refs/heads` are handled:

```coffee
Repository::checkoutReference = (branch, create)->
  if branch.indexOf('refs/heads/') isnt 0
    branch = "refs/heads/#{branch}"

  @checkoutRef(branch, create)
```

If you'd like, please re-open this on the git-utils repository.

**Comment by olmokramer** [comment]
Ah, I get it. Thanks.

New issue here: https://github.com/atom/git-utils/issues/50
