### ISSUE TITLE
**/.* matched all files under dir

### ISSUE THREAD

**Issue by zetay** [atom/atom#7975]
In .gitignore, `**/.*` matched all files under dirs, and can't display in project.

**Comment by mnquintana** [comment]
I'm not sure I follow - if you have `**/.*` in your `.gitignore`, then unless there's a file without an extension, that *would* match every file in your project directory. Were you expecting something else?

**Comment by zetay** [comment]
My project 'sc-rfqnoah' in Explorer
![dir](https://cloud.githubusercontent.com/assets/726159/8799563/8eb51526-2fdd-11e5-9eb1-653059f89233.png)
And settings in .gitignore
![gitignore](https://cloud.githubusercontent.com/assets/726159/8799570/9efd282e-2fdd-11e5-8bea-65e796405ebf.PNG)
Then result in Atom
![nofile](https://cloud.githubusercontent.com/assets/726159/8799575/a802f0e8-2fdd-11e5-924f-b1c49da11eeb.png)
Files are disappeared.

**Comment by izuzak** [comment]
You can tell Tree View to show you gitignored files. Go to the settings for the Tree View package and uncheck the "Hide VCS ignored files" config option. Does that help?
