### ISSUE TITLE
Minimize download size in git clone (build instructions for linux)

### ISSUE THREAD

**Issue by nelson6e65** [atom/atom#7978]
**Theres is another way to download source (via git or linux console) to specific version (instead all)?**

In instructions:
```
Clone the Atom repository:

git clone https://github.com/atom/atom
cd atom

Checkout the latest Atom release:

git fetch -p
git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
```

This works fine, but there is a lot of objects and the size is over 200 Mb (`Receiving objects: 100% (137970/137970), 262.89 MiB `). How can I ignore the download of old files?

Or how can I download a minimal source to build?

I notice in releases sources, files size is <10Mb. Can I use this instead to build full atom?

**Comment by mehcode** [comment]
Specify the version you want when you clone and add `--depth=1`.

```
git clone https://github.com/atom/atom -b v1.0.2 --depth=1
```

**Comment by izuzak** [comment]
> I notice in releases sources, files size is <10Mb. Can I use this instead to build full atom?

Yes, you should be able to do that. You can write a script which fetches the [latest release](https://developer.github.com/v3/repos/releases/#get-the-latest-release), and then fetches the ZIP archive for the latest release (use the `zipball_url`/`tarball_url` attributes in the response). You could also fetch the ZIP archive with the source for the latest master version, by using [this API endpoint](https://developer.github.com/v3/repos/contents/#get-archive-link).

**Comment by nelson6e65** [comment]
Thanks, @izuzak. I'll try that. 

@mehcode That is a good idea, but still need to get latest version dynamically. I'l make some tests.

Thanks for ideas. :+1:
