### ISSUE TITLE
Empty line handling

### ISSUE THREAD

**Issue by SebastianGoendoer** [atom/atom#7981]
There is an issue with empty lines in Atom, in which all whitespace characters are deleted automatically if this line just contains whitespaces. This happens when a file is saved in Atom, but not always: Seems like this happens NOT when there are SOME lines with just whitespace chars, but with many of such lines, this tends to happen always (?). Couldn't figure out a logic behind that yet.

Plus, upon saving a file, an empty line is added automatically after the last line with content (if no such line exists). Very annoying. This happens upon saving a file in Atom.

Proposal: Change that to NOT removing any "unnecessary" whitespaces, or adding empty lines. Maybe add a configuration option to explicitly trigger this.

**Comment by mnquintana** [comment]
This is not a bug - see https://atom.io/docs/v1.0.2/using-atom-editing-and-deleting-text#whitespace for more information (including details on how to disable this feature).

**Comment by shanuk** [comment]
This is not right to have such an important setting enabled by default. Don't touch anything I don't explicitly edit unless I make action to make changes.
