### ISSUE TITLE
Auto-indent `decreaseIndentPattern` for empty string causes unexpected problems

### ISSUE THREAD

**Issue by lierdakil** [atom/atom#7984]
Not sure if it's been reported already, but I'm pressed for time right now. Sorry if it's a duplicate.

`language-haskell` package used `decreaseIndentPattern: '^\\s*$'` to decrease indentation on empty strings (this was taken directly from Haskell TexMate bundle). Recently, it started causing problems on OSX and simply stopped working on other platforms. See https://github.com/atom-haskell/language-haskell/issues/40 for more information.

I think this is a bug, but I'm not sure, given apparent lack of documentation on the matter.

Thanks.

**Comment by mnquintana** [comment]
Possibly related to https://github.com/atom/atom/pull/6808

/cc @svanharmelen @maxbrunsfeld

**Comment by svanharmelen** [comment]
Thanks for the ping @mnquintana!

This is indeed related to #6808, but it's already updated/fixed in #7858 which is already merged. So in the next release `decreaseIndentPattern` will work as expected again.

**Comment by mnquintana** [comment]
Ah excellent! Just wanted to make sure. Gonna close this one out then - @lierdakil feel free to reopen this if you experience this again on Atom 1.0.3 when it's released.
