### ISSUE TITLE
Need some extra options/settings

### ISSUE THREAD

**Issue by Gibbz** [atom/atom#7985]
Id like to see the following options added:
- option to disable the tree view by default
- option to not remember history of opened tabs
- option to have no tabs, opening each document would instead open a new window

**Comment by mnquintana** [comment]
For your first one, it won't be disabled by default, but you can disable it yourself in Settings.

Your last two suggestions have been reported already: https://github.com/atom/atom/issues/6605, https://github.com/atom/atom/issues/7958
