### ISSUE TITLE
Can't load installed packages or themes on Windows 10

### ISSUE THREAD

**Issue by FredrikAugust** [atom/atom#7986]
Hello! I recently installed atom, and started using it today. Everything seems fine except for loading installed packages/themes and installing from the program.

When I click on install I get an error saying: _Fetching featured packages failed_.

And the output is:
```
spawn C:\Windows\system32\cmd.exe;C:\python27 ENOENT
```

And when I open the dev console while looking at the installed packages page I see:

```
Fetching local packages failed. Error: Fetching local packages failed.
  at createProcessError (C:\Users\fredr\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:607:13)
  at C:\Users\fredr\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:618:23
  at Emitter.module.exports.Emitter.emit (C:\Users\fredr\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at BufferedProcess.module.exports.BufferedProcess.handleError (C:\Users\fredr\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:251:20)
  at ChildProcess.<anonymous> (C:\Users\fredr\AppData\Local\atom\app-1.0.2\resources\app.asar\src\buffered-process.js:240:24)
  at emitOne (events.js:77:13)
  at ChildProcess.emit (events.js:166:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1055:12)
  at child_process.js:1127:20
  at process._tickCallback (node.js:357:13)
```

I am running 64-bit Windows 10 Build 10130.

**Comment by maxbrunsfeld** [comment]
Could you open the dev tools (`Window: Toggle Dev Tools` from the command pallette) and report the output of this javascript code?

```js
atom.packages.getApmPath()
```

It looks like Atom is failing to run the `apm` command line tool.

**Comment by FredrikAugust** [comment]
Yes sir! Here's the output:

```
C:\Users\fredr\AppData\Local\atom\app-1.0.2\resources\app\apm\bin\apm.cmd
```

**Comment by maxbrunsfeld** [comment]
Ok, looks like that's not the problem. How about this: could you share the output of running `apm featured` from the command prompt?

**Comment by FredrikAugust** [comment]
Yep.

```
Featured Atom Packages (10)
├── color-picker Right click or press CMD-SHIFT-C/CTRL-ALT-C to open it. (365825
 downloads, 991 stars)
├── merge-conflicts Resolve git conflicts within Atom (132217 downloads, 792 sta
rs)
├── minimap A preview of the full source code. (513734 downloads, 1390 stars)
├── pigments A package to display colors in project and files. (43464 downloads,
 318 stars)
├── travis-ci-status Add Travis CI status of the project to the Atom status bar.
  (29054 downloads, 123 stars)
├── vim-mode Add vim modal control (210080 downloads, 476 stars)
├── atom-material-syntax A dark syntax theme for Atom that uses Google's Materia
l Design color palette (15043 downloads, 40 stars)
├── atom-material-ui A dark UI theme for Atom that follows Google's Material Des
ign Guidelines (26893 downloads, 71 stars)
├── nucleus-dark-ui An adaptable UI with your favorite syntax theme at it's core
! (1152 downloads, 9 stars)
└── unity-ui An Atom theme for a more native experience on OS X. (92411 download
s, 127 stars)

Use `apm install` to install them or visit http://atom.io/packages to read more
about them.

```

**Comment by maxbrunsfeld** [comment]
@kevinsawicki Any idea what could be going on here? It looks like it's reading the `%PATH%` wrong or something: trying to run a child process with a garbled path, but in this case I would think it would just need to run `apm`.

**Comment by kevinsawicki** [comment]
> Any idea what could be going on here?

This is really strange, @FredrikAugust can you check what the value of your `COMSPEC` environment variable is?

Looks like it might contain multiple paths which is causing issues.

https://github.com/atom/atom/blob/1a961d987dd69c1bfd69f13b340ce1796b0ae8b9/src/buffered-process.coffee#L174

**Comment by FredrikAugust** [comment]
Hey, sorry for late response. The value of `COMSPEC` is:

```
C:\Windows\system32\cmd.exe;C:\python27
```

**Comment by kevinsawicki** [comment]
@FredrikAugust is there a reason that python is on your `COMSPEC`?

If you remove it then I would think this would resolve the issue you are seeing.

**Comment by batjko** [comment]
We've seen that in another issue a few weeks back.

Something or someone added a path to the ComSpec variable when it was supposed to add it to the PATH variable.

The Python installer or manual addition by mistake?

**Comment by paulcbetts** [comment]
@kevinsawicki tbh, I would ignore COMSPEC altogether and always spawn `%SystemRoot%\System32\cmd.exe`

**Comment by FredrikAugust** [comment]
Hm.. I can not recall messing with the ComSpec variable, could be the python 2.7 installer as I installed that yesterday. Any tips on how to change it? It seems to be grayed out in windows environment variables settings panel.

**Comment by FredrikAugust** [comment]
Never mind, seems to be two ways to open the settings for the environment variables.

**Comment by FredrikAugust** [comment]
And this resolved the issue. Thanks! :+1:

**Comment by Abdullah8006** [comment]
I had the same issue. I am working with Atom 1.17.1 on a 64 bit windows 7 machine. Restarting Atom did the trick for me.
