### ISSUE TITLE
A bit buggy on Linux Ubuntu Gnome 

### ISSUE THREAD

**Issue by sourceCode17** [atom/atom#7990]
The default mouse pointer changes to text insert pointer once I click on Atom. From there it does not allow me to highlight anything. I have Atom also installed on my OS X and it works fine there, just not on this linux.

**Comment by mnquintana** [comment]
Are you using VirtualBox?

**Comment by sourceCode17** [comment]
Yes.

**Comment by mnquintana** [comment]
Thanks for the update! This is a duplicate of https://github.com/atom/atom/issues/6243 and https://github.com/atom/atom/issues/6306 and will be fixed in https://github.com/atom/atom/pull/7877.
