### ISSUE TITLE
Opening a png image via keyboard shortcuts breaks tab/treeview keyboard navigation

### ISSUE THREAD

**Issue by DanielJoyce** [atom/atom#7991]
1. Use treeview to browse to a png file
2. Hit enter to open and view png file
3. Note that you can no longer user Ctrl-0 to return focus to treeview, and Ctrl-tab to switch tabs until you click on another file in treeview to open it, or another tab. Then it works again.

If the image was opened previously, and you select it again in treeview, it seems navigation doesn't always break. Open the image for the first time via treeview seems to always break it.

Atom 1.0.2

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"

**Comment by izuzak** [comment]
I'm having trouble reproducing this on OSX. Can someone on linux try and reproduce? /cc @atom/feedback 

Also, @DanielJoyce -- do you see the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?
