### ISSUE TITLE
atom requires sudo

### ISSUE THREAD

**Issue by krngrvr09** [atom/atom#7992]
I recently installed atom from source.
I did 
``sudo script/build``
``sudo script/grunt install``

When I type ``atom`` in the terminal, I see this.

![atom](https://cloud.githubusercontent.com/assets/5905966/8783883/4d9b9412-2f3c-11e5-8a3b-20232dc4d2cc.png)

The ownership of the ``.atom`` directory is this:

![ownership](https://cloud.githubusercontent.com/assets/5905966/8783903/749880de-2f3c-11e5-8452-031e191046af.png)

Is this the expected behaviour?

**Comment by krngrvr09** [comment]
#1965 An issue already opened. Apologies for being too quick to jump and open an issue!

**Comment by 50Wliu** [comment]
@krngrvr09 In addition, try doing `script/build` *without* `sudo` (the install command should remain the same, however).  You may have to do a `sudo script/clean` first and also remove `~./atom`.
