### ISSUE TITLE
C++ syntax highlighting does not behave properly in some class inheritance cases

### ISSUE THREAD

**Issue by jaredmpayne** [atom/atom#7994]
The commented screenshot shows expected and observed behavior.
This occurred on OS X. I am running 10.11 Beta, but I'm confident I've experienced this behavior in 10.10 as well.

<img width="530" alt="screen shot 2015-07-20 at 3 45 45 pm" src="https://cloud.githubusercontent.com/assets/7102870/8786885/765f659a-2ef6-11e5-8d82-cb62e5fa7065.png">

**Comment by mehcode** [comment]
You'll want to report this on the appropriate language package: https://github.com/atom/language-c

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/language-c? Thanks!
