### ISSUE TITLE
Auto hide menu bar setting not working properly

### ISSUE THREAD

**Issue by mikeott** [atom/atom#7997]
When initially enabling this option, the menu bar does indeed hide, and hitting the **ALT** key does toggle it showing/hiding.

The problem occurs when you have files open and you want to show the menu bar. Pressing **ALT** doesn't do anything, until you close all your open files and only then does the ALT key show the menu.

If you have the settings tab open, clicking on it will let the **ALT** key show the menu. But then clicking on any other open tab pressing the **ALT** key doesn't make the menu appear.

The attached GIF shows it in action. While I have the .htaccess tab in focus (or any file for that matter) I'm pressing the **ALT** key but nothing is happening.

I'm running Windows 8.1 (64), Atom v1.0.2. This is only a recent phenomena, I think (though could be wrong) it only started happening with the 1.0 release.

## How to reproduce the bug ##

1) Go to **Settings** and enable **Auto hide menu bar**.
2) Close the **Settings** page.
3) Open a file.
4) Click on the tab for the file you just opened.
5) Press the **TAB** key (the menu will **not** show).
6) Close the file you have open.
7) Press the **TAB** key again (the menu **will** show).

## Where I've seen this bug ##

Two different workstations, at home and at the office:

1)  On Windows 8.1 (64) running Atom v1.0.2 (home)
2)  On Windows 8.1 (64) running Atom v1.0.2 (at the office)

![auto-hide-menu](https://cloud.githubusercontent.com/assets/5625353/8791236/d7dec4ac-2f8a-11e5-8792-37e1de1807bf.gif)

**Comment by mnquintana** [comment]
Can you reproduce this in safe mode? (`atom --safe`)

**Comment by mikeott** [comment]
@mnquintana Thanks for the tip (I didn't know Atom was able to be launched in safe mode).

And yes - I can confirm this also happens in safe mode.

**Comment by mnquintana** [comment]
This means that a community package you have installed is interfering with the default <kbd>Alt</kbd> behavior - if you have linter installed it might be https://github.com/atom-community/linter/issues/648

**Comment by mikeott** [comment]
I do have linter installed. So I guess I should delete this bug report?

**Comment by mnquintana** [comment]
Thanks for the update! You can subscribe to https://github.com/atom-community/linter/issues/648 for updates.

**Comment by mikeott** [comment]
No, thank you for the feedback.
