### ISSUE TITLE
Please give us discrete options how to deal with indentation

### ISSUE THREAD

**Issue by weichert** [atom/atom#8001]
As it stands Atom is using "auto-detection" to decide if it should use tabs or spaces to indent and then how many.
That can break in edge cases and if it does it's usually polluting code in unexpected ways.

Please give us an option like you did with character encoding, integrated into the status bar like so many other professional editors do.

That way we can say: This file is using 4 spaces to indent exclusively, period. No matter what happened somewhere else in the file.

**Comment by mnquintana** [comment]
I think this is covered by https://github.com/atom/atom/issues/3719 – let's keep the discussion there. Feel free to comment if I'm misunderstanding, though.
