### ISSUE TITLE
Cant browse file if password is not saved in server config

### ISSUE THREAD

**Issue by vince68** [atom/atom#8003]
If I dont save the password but leave the field blank, it ask me for the password to establish the connection. It say connection ok, but I cant browse the folders. If I store the password on the ftp or sftp connection I get the list of files and all works good. Did I miss something when the password field is blank or it's a bug ?

**Comment by benogle** [comment]
Can you elaborate on which package you're entering a password into? Nothing in atom requires a password

**Comment by vince68** [comment]
Sorry, it's for the remote-edit package. I open a case for this package.
