### ISSUE TITLE
invisible character settings are removed after first open

### ISSUE THREAD

**Issue by chharvey** [atom/atom#8004]
I just installed Atom on my new work computer for the first time and opened the settings. I noticed there were a few options for setting invisible characters, such as **Cr, Eol, Tab,** etc. This was surprising to me since I did not see those settings for Atom installed on my home computer. I checked to make sure both versions were the latest, which they were. I decided not to worry about it for the time being…

Then after quitting and reopening Atom on my new computer, the character settings were gone! I still have "Show Indent Guide" and "Show Invisibles" but no options to choose invisible characters.

Is this a bug?

---
stats:

- Work Computer: MacBook Pro (Retina, 13-inch, Early 2013), 3 GHz Intel Core i7, OS X 10.10.4 (Yosemite) 
- Home Computer: MacBook Pro (Retina, 15-inch, Mid 2014), 2.2 GHz Intel Core i7, Os X 10.10.4 (Yosemite)

**Comment by izuzak** [comment]
Yeah, seems like a bug in Settings View. Thanks for the report -- gonna move this issue over to that package.

Note: you should still be able to change those config values by manually editing your config.cson file.

**Comment by izuzak** [comment]
This issue was moved to atom/settings-view#611
