### ISSUE TITLE
DisplayMarker doesn't dispatch a change event when a line gets wrapped

### ISSUE THREAD

**Issue by abe33** [atom/atom#8007]
Here's a demonstration: 

![marker-change](https://cloud.githubusercontent.com/assets/247140/8806074/2f921bfa-2fd5-11e5-98a6-4a66b857ac5a.gif)

I've attached a listener to the change event of a marker created using `TextEditor::markBufferRange`. As you can see in the console, I do receive the event when adding/removing lines but not when the line I'm editing gets wrapped.

As the range of the underlying buffer marker did not change, it doesn't emit a change event. But the screen range of the display marker did change, so I believe it should emit an event on its own in this case.

**Comment by benogle** [comment]
cc @nathansobo @maxbrunsfeld

**Comment by maxbrunsfeld** [comment]
Yeah, I think we knowingly removed this feature in the process of optimizing Marker events. Specifically, I think it was this PR: https://github.com/atom/atom/pull/7023. It's probably possible to add it back without performance regressions, but I don't know how; it won't be trivial.

@abe33 Is this causing problems in your `atom-pigments` package? Can you help me explain why you need a marker change event when the line wraps?

**Comment by abe33** [comment]
@maxbrunsfeld that's because I use my own decoration elements, so I need to update them as the user types. I didn't noticed this until someone reported me the issue recently (abe33/atom-pigments#55). I guess the same thing happen when folding occurs as it only affect the screen lines and not the buffer.

Maybe I was wrong, but I was thinking that the marker class in `atom` was like an extension of the `text-buffer`'s marker to add the support for screen ranges, so I was thinking it would emit its change event when its screen range changes, not only the buffer range. 

Anyway, I have a fix for the out-of-sync markers issues in pigments, and it's actually quite simple and efficient so I guess it's okay if it won't be fixed on the marker side.

**Comment by benogle** [comment]
Just curious, would overlay decorations work for you? I guess the real fix would be to make highlight decorations allow for text color adjustment.

**Comment by maxbrunsfeld** [comment]
> so I was thinking it would emit its change event when its screen range changes, not only the buffer range.

Yeah, it would make sense for it to emit a change event, but we currently have no way of detecting a change without iterating over every marker and comparing its screen range to its previous value. We used to do that, but it's prohibitively expensive when there are thousands of find-and-replace search results, or underlined spelling errors. I think doing this work on an as-needed basis in packages is the best compromise at the moment.

**Comment by abe33** [comment]
> Just curious, would overlay decorations work for you? I guess the real fix would be to make highlight decorations allow for text color adjustment.

I tried to use overlay decorations, but as I need to render a text range I still have to implement the region rendering routine. And AFAIK overlay decorations aren't affected by the visibility if their marker, so that mean that I still would have to deal with performances issues when working on a big files with lots of colors (like the bootstrap css). 
Having the option to change the color of the text in a highlight decorations would be great, but I also have a render mode where the markers appears at the end of the line, so highlights won't do in this case.
Maybe if there was also a decoration to add some element at the end of a line I could use only native decorations but for the moment using my own custom decorations works pretty well. I use an instances pool to avoid touching the DOM too much and as I only render the colors that are on screen it reduces  the burden when working on really big files.

> We used to do that, but it's prohibitively expensive when there are thousands of find-and-replace search results, or underlined spelling errors.

I was feeling it was due to a perfomance issue. I initially looked at the marker source to see if I could fix that myself and when I realized I would have to loop over each marker on each keystroke (or on specific events dispatched only when the screen lines changes but I didn't find any) I thought of reporting it first.

**Comment by abe33** [comment]
BTW, do you want me to close this issue or do you want to keep it open as a reminder?

**Comment by nathansobo** [comment]
Let's leave it open; this needs to be solved.

**Comment by abe33** [comment]
Seems it's resolved now, I'm closing it then.
