### ISSUE TITLE
Can't take screenshots on Mac?

### ISSUE THREAD

**Issue by DavidAwad** [atom/atom#8008]
Hi! using command shift 4 to take a screenshot of atom creates strange results. Please feel free to look at my screen captures if it's helpful ... 
![screen shot 2015-07-21 at 2 03 17 pm](https://cloud.githubusercontent.com/assets/4019054/8809013/f9a63a24-2fb3-11e5-878d-b7bfc5560b2d.png)
![screen shot 2015-07-21 at 2 02 40 pm](https://cloud.githubusercontent.com/assets/4019054/8809014/f9a7cfb0-2fb3-11e5-8a92-9ef63943b5ac.png)

**Comment by mnquintana** [comment]
What version of OS X are you using?

**Comment by batjko** [comment]
Is it really possible that this is an Atom issue, rather than OSX and whatever is used for screenshots here?
Has anyone seen this before (as in related to Atom)?

**Comment by adambuczynski** [comment]
I'm actually having a similar issue since a little while ago with taking screenshots of Atom using licecap. Used to work fine before, but since an Atom update not too long ago it stopped working. I didn't update my OS or licecap in between, so it's strange to say the least.

This was on OS X 10.10.3.

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8008#issuecomment-123832762. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by adamreisnz** [comment]
@50Wliu 

> What version of OS X are you using?

> This was on OS X 10.10.3.
