### ISSUE TITLE
Typing cursor disappearing on Windows 8/8.1

### ISSUE THREAD

**Issue by candidosales** [atom/atom#8011]
When you're typing and press the Windows key on Windows 8/8.1 and then ESC to get back to Atom, the typing cursor is gone =( It comes back if we change typing focus away from it than back. Annoying as heck =/

**Comment by izuzak** [comment]
@candidosales Sorry for the delay in getting back to you on this. I think you're seeing the same issue which is described in https://github.com/atom/atom/issues/3622. I just had a quick look at the comments there and I don't think I noticed reports from Windows users, so it would be nice if you could add a comment there and list the steps which reproduce the problem for you on Windows. Thanks for reporting this and sorry this is causing problems :(
