### ISSUE TITLE
Auto-indent on newline broken in 1.0.2

### ISSUE THREAD

**Issue by martinpllu** [atom/atom#8013]
Auto-indent on newline works in 1.0.1 but is broken in 1.0.2.

To test, I'm opening a new file (Command-N) and typing a line that starts with a tab. When I press return I expect the next line to have the same indentation. The behaviour is as expected on 1.0.1 but there is no indentation on the next line in 1.0.2.

I tested the behaviour by installing 1.0.1 and 1.0.2 packages from https://github.com/atom/atom/releases. I'm using Mac OSX Yosemite and vanilla installs of Atom with no third party plugins.

Cheers,

Martin

**Comment by feifanzhou** [comment]
:+1:

**Comment by DylanFahey** [comment]
I can confirm the same issue on Windows Server 2008 R2 Standard. When creating a new file, auto-indent works on 1.01, but does not work on 1.02. If I set the language to SQL in 1.02 auto-indent works. The issue persists after I've saved the new file, unless the file triggers the SQL highlighting. 

This issue persists in 1.02 with every package disabled. Auto-indent continues to work in 1.01 with every package disabled.

**Comment by svanharmelen** [comment]
@maxbrunsfeld  @martinpllu I'll have a look... It seems to give this result only when no language is selected (so when using `plain text`). As soon as I select a language (any language that is) it works as expected.

**Comment by DylanFahey** [comment]
@svanharmelen I've tested all of the langauges on my system. It appears the issue occurs when the language grammer doesn't have an increase or decrease indent grammar rule. Auto-indent is broken when using CSS, but works with SQL, HTML, etc.

Here is an example of the grammar rule from Language-SQL

    'increaseIndentPattern': '^\\s*(create|grant|insert|delete|update)\\b|\\((?!.*\\))'
    'decreaseIndentPattern': '^\\s*\\)(?!=.*\\()'

Here is an example from the grammar rule from Language-HTML

```
'increaseIndentPattern': '(?x)
      <(?!\\?|(?:area|base|br|col|frame|hr|html|img|input|link|meta|param)\\b|[^>]*/>)
      ([-_\\.A-Za-z0-9]+)(?=\\s|>)\\b[^>]*>(?!.*</\\1>)
      |<!--(?!.*-->)
      |<\\?php.+?\\b(if|else(?:if)?|for(?:each)?|while)\\b.*:(?!.*end\\1)
      |\\{[^}"\']*$
    '
    'decreaseIndentPattern': '(?x)
      ^\\s*
      (</(?!html)
        [-_\\.A-Za-z0-9]+\\b[^>]*>
        |-->
        |<\\?(php)?\\s+(else(if)?|end(if|for(each)?|while))
        |\\}
      )'
```

Language-text and Language-CSS do not have indent rules in their grammar, and I suspect that is why they are breaking.

**Comment by svanharmelen** [comment]
@DylanFahey yes, I was just looking at the same thing... But those lines (https://github.com/atom/atom/blob/master/src/language-mode.coffee#L254-L255) were already in there before as well: https://github.com/atom/atom/commit/eaf814e5be7e365c4c6cfd0bfdb1bc430e68685d#diff-7d7c3b2f436032f702341d66de00c841R254 Albeit in a slightly different syntax.

**Comment by svanharmelen** [comment]
@DylanFahey that indeed has something to do with it :wink:

PR #8048 fixes (as far as I can tell and have tested) the problem without falling back to the old behaviour.
