### ISSUE TITLE
Tree-view doesn't show some folders without any consistency.

### ISSUE THREAD

**Issue by YoungxHelsinki** [atom/atom#8016]
Hi all,

Before I begin, thank you for the great text editor :)

I'm using Mac OS 10.10.4 and Atom 1.0.2.
In one Django project, I have a path like ..../project/static/lib/bootstrap.....
Atom wouldn't show the lib folder at all. I checked the Atom setting whether I accidentally included that folder but I didn't.
I opened another Django project which also has lib folder. Atom shows that folder in this case.
![screen shot 2015-07-22 at 10 08 44 am](https://cloud.githubusercontent.com/assets/5738363/8815852/0be7088e-305a-11e5-8e11-467aee9e2990.png)

I thought it was weird but I decided to move on until I found another behavior.
I created /static/icon/ and it didn't show that folder either. 
![screen shot 2015-07-22 at 10 08 04 am](https://cloud.githubusercontent.com/assets/5738363/8815853/0be763f6-305a-11e5-918a-eaadb2a69f78.png)

Then I changed the folder name to 'icons' then it showed!!! I changed '/lib/' to '/libs/' then it also showed. I experimented with '/images/' but that folder always appeared in any case.

![screen shot 2015-07-22 at 10 08 26 am](https://cloud.githubusercontent.com/assets/5738363/8815854/0be7bbbc-305a-11e5-9bd5-45a15a45ac4e.png)

I think this is not an intended behavior. Any ideas?

**Comment by mark-hahn** [comment]
There are several ways to hide things in the tree-view.  There is a
specific setting to hide patterns and there is also a setting to hide
things in .gitignore.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tree-view? Thanks!

**Comment by YoungxHelsinki** [comment]
Of course!
