### ISSUE TITLE
Editor image preview does not load with % in its URI

### ISSUE THREAD

**Issue by tqn** [atom/atom#8018]
Let me begin by thanking you for the great editor! It's much better than any alternatives I've found.
I am using Atom 1.0.2 and Windows 8.1 x64.
When opening an image with `%` in its URI, it is not displayed properly, but can still be opened from the tree view. The dev tools report an `ERR_FILE_NOT_FOUND`.
![image](http://i.imgur.com/a4FM6tK.png)

Removing the `%`s seem to fix this issue.
![image](https://cloud.githubusercontent.com/assets/6508913/8817512/ab35bc3a-3066-11e5-87ad-1882c130ecf2.png)

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/image-view? Thanks!
