### ISSUE TITLE
editor:cut-to-end-of-line on empty line above fold deletes the whole fold

### ISSUE THREAD

**Issue by KnutHelland** [atom/atom#8023]
I feel there are a couple of inconsistencies with code folding. At least I can prove this one:

`editor:cut-to-end-of-line` is by default bound to `ctrl-k` on darwin, so I use it a lot for deleting current line.

The default behavoiur when cursor is on an _empty_ line is to delete the current line (delete the newline).

But if the line below is folded, that one is deleted as well (and not even cut. It's deleted). I've tried to make a demonstration in this gif. It first demonstrates normal behaviour, and then what happens when the line below is folded.

![Demo](http://zippy.gfycat.com/ShortWeightyHorseshoebat.gif)

**Comment by KnutHelland** [comment]
One additional and similar bug: `editor:newline-above` on the line below a folded are should add a newline between current line and the folded are, but it is inserted above the folded area (and the fold is expanded).

I wrote that "I feel there are a couple of inconsistencies", but I'm almost sure that these two bugs are the only one I've encountered.

**Comment by renestalder** [comment]
Same problem when pressing backspace just below a folded code block. The whole block will be deleted. Very annoying behaviour.
