### ISSUE TITLE
open new file in an already open window

### ISSUE THREAD

**Issue by haikyuu** [atom/atom#8030]
I'm using atom 1.0.0 in Ubuntu. 
When i run `atom nonExistantFile`, a **new window** is opened for it.
As atom is slow on start-up, that's very inconvenient. Is there an option to open in an already open window?

**Comment by mnquintana** [comment]
That's weird - I can't reproduce this on Atom 1.0.2 on OS X 10.10.3. Can you try updating to the latest version (1.0.2)?

**Comment by haikyuu** [comment]
it happens only when the file in question doesn't exist and for commit messages if you set atom as the core.editor.
I'll update and try again

**Comment by haikyuu** [comment]
I updated (i don't think it has anything to do with the version).
Anyway, here is what happens:
- If you open a new file in a directory that **has an** instance of atom open, it will open the file in the **same window**.
- If you open a file new file in a directory that **has no** instance of atom open, it will open the file in a **new window**. (happens also for git commit message)
I think that it would be great to add it as an **option** `atom --already-open fileName`: and the file will be opened in the **last active** instance of atom.
This way we could fix it for the commit message too.

**Comment by mnquintana** [comment]
Ah, thanks! I can reproduce this now.

**Comment by glajchs** [comment]
I can't believe this is the default behavior, much less the *enforced* behavior.

This is just a text editor!  Open my files in the text editor window, not 1 window per file!

My terrible workaround for now: add "/" as a project folder.

**Comment by ssbarnea** [comment]
I am wondering how many years we will need till we will solve this bug. This one is very well defined and easy to reproduce, clearly against documentation.

**Comment by mattvonrocketstein** [comment]
Yes please, this maddening problem happens with me several times a day, every day.  All you have to do is typo a filename, and my computer is basically unusable for a few seconds while Atom bootstraps the new window.  Yes I need a new computer.. but Atom needs a more efficient and quick bootstrap.. so a solution for this very old and easy-to-reproduce issue makes a great compromise :)

**Comment by mattvonrocketstein** [comment]
@mnquintana can this please be reopened?
