### ISSUE TITLE
Can't write @ character

### ISSUE THREAD

**Issue by MrLinDowsMac** [atom/atom#8031]
I have Windows 8. I was trying to write a single @ character using the ALT GR - Q keys. At beginning I though was a problem of my keyboard configuration, so I tried by using the onscreen keyboard tactile, and typing the @ character directly, but it doesn't render it anyway.

**Comment by mnquintana** [comment]
I think this is a duplicate of https://github.com/atom/atom-keymap/issues/35 and https://github.com/atom/atom-keymap/issues/37 – please subscribe there for updates.
