### ISSUE TITLE
OSX 10.9.5, Atom 1.0.2: Saving file in atom gives random number of changes in git diff

### ISSUE THREAD

**Issue by marcosvanella** [atom/atom#8032]
Hello,
I downloaded today the latest version of Atom, and find that even when I change one line of a file of my repo in GitHub, I get a large amount of changes through git diff (452 in the Screen Shot_change saved below).
![screen shot_change without saving](https://cloud.githubusercontent.com/assets/7450069/8834305/5ff8fbae-3081-11e5-9e80-3febb07d63a6.png)
![screen shot_change saved](https://cloud.githubusercontent.com/assets/7450069/8834322/79cac972-3081-11e5-94d2-2a6ef1fa1138.png)
I tried changing the standard editor from Vim to atom, at no avail. This doesn't seem to be the issue seen previously on Windows, regarding the last line added by atom, as the changes appear randomly. I started atom in safe mode but still see the problem. I don't have the problem when I make a small change using other editors (Vim).
I'm new with git and atom so it might be some configuration problem?
Thank you in advance for your time,
Marcos

**Comment by mnquintana** [comment]
Take a look at https://discuss.atom.io/t/why-is-atom-deleting-trailing-whitespace-why-are-there-all-these-changes-in-the-file-diff/19189?u=mnquintana for more information.

**Comment by marcosvanella** [comment]
Thank you Machisté,
Marcos
