### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cursor' of undefined

### ISSUE THREAD

**Issue by jssln** [atom/atom#8034]
This problem starts to repro on/after https://github.com/atom/atom/commit/5a799578dea41f389e3a23bb7edfd8284aabf303.

This error appears in the console when you try to open the fuzzy finder (cmd+t) -- which is unsuccessful. I'm also unable to open any files via clicking on them in the file tree, though this doesn't result in an error in the console.

Trace:

![screenshot 2015-07-22 14 48 31](https://cloud.githubusercontent.com/assets/1017111/8838366/f73bf9e0-3080-11e5-9283-06980f4e7ccd.png)

Trace text:

module.exports.TextEditor.addCursorAtBufferPositiontext-editor.coffee:101 TextEditortext-editor-element.coffee:100 TextEditorElement.buildModeltext-editor-element.coffee:97 TextEditorElement.getModel/Users/jessicalin/atom/node_modules/atom-space-pen-views/lib/text-editor-view.js:36 TextEditorView/Users/jessicalin/atom/node_modules/atom-space-pen-views/lib/select-list-view.js:26 (anonymous function)/Users/jessicalin/atom/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281 Builder.tag/Users/jessicalin/atom/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83 Tags.forEach.View.(anonymous function)/Users/jessicalin/atom/node_modules/atom-space-pen-views/lib/select-list-view.js:22 module.exports.SelectListView.content/Users/jessicalin/atom/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:156 (anonymous function)/Users/jessicalin/atom/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123 View.buildHtml/Users/jessicalin/atom/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:155 View/Users/jessicalin/atom/node_modules/atom-space-pen-views/lib/select-list-view.js:18 SelectListViewfuzzy-finder-view.coffee:10 FuzzyFinderViewproject-view.coffee:10 ProjectViewmain.coffee:59 module.exports.createProjectViewmain.coffee:19 module.exports.activate.atom.commands.add.fuzzy-finder:toggle-file-findercommand-registry.coffee:236 module.exports.CommandRegistry.handleCommandEventcommand-registry.coffee:1 __bind/Users/jessicalin/atom/node_modules/atom-keymap/lib/keymap-manager.js:520 module.exports.KeymapManager.dispatchCommandEvent/Users/jessicalin/atom/node_modules/atom-keymap/lib/keymap-manager.js:355 module.exports.KeymapManager.handleKeyboardEventwindow-event-handler.coffee:135 module.exports.WindowEventHandler.onKeydown

**Comment by maxbrunsfeld** [comment]
It looks like this is in dev mode. Does this happens if you checkout Atom master, run `script/build`, and run `atom --safe` (without dev mode)?

**Comment by jssln** [comment]
@maxbrunsfeld, it works fine if I do the above (now on 1.0.3)
