### ISSUE TITLE
Linux DPI scaling is not working

### ISSUE THREAD

**Issue by rfkrocktk** [atom/atom#8035]
Atom version is 1.0.2, running on elementary Freya, based on Ubuntu 14.04 LTS. Kernel is 3.19.0. 

Screenshots demonstrating the problem:

![](https://i.imgur.com/rPAKCR0.png)

![](https://i.imgur.com/kwbZ4dZ.png)

Windows on the left scale properly on a HiDPI display (MacBook 13" 2013 edition in this case, native resolution is 2560x1600px), next to Atom, which isn't scaling.

**Comment by mnquintana** [comment]
This is a duplicate of https://github.com/atom/atom/issues/3826 – please subscribe there for updates.

**Comment by rfkrocktk** [comment]
@mnquintana I don't think that we're talking about the same bug as the other one. That one is reporting that fonts are too big on low-DPI displays, mine is reporting the opposite problem: fonts are too small on HiDPI displays.

**Comment by mnquintana** [comment]
@rfkrocktk It's a symptom of the same underlying issue as #3826 though, and I'd rather not have too many issues open for that.

**Comment by rfkrocktk** [comment]
Fair enough :)
