### ISSUE TITLE
Incorrect Symbol Pairing

### ISSUE THREAD

**Issue by crstauf** [atom/atom#8036]
Running Atom v1.0.2 on Yosemite
![screen shot 2015-07-22 at 8 58 25 pm](https://cloud.githubusercontent.com/assets/4573033/8840894/58bd4172-30b5-11e5-94db-c4ed7cc788f9.png)
https://cloudup.com/cDuqPmzypsC

Confirmed incorrect pairing for both brackets and parenthesis.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/bracket-matcher? Thanks!
