### ISSUE TITLE
Add a status when Atom is downloading a new update

### ISSUE THREAD

**Issue by Ivoz** [atom/atom#8038]
When I know there is a new update available for Atom, I can run "Check for Update" in the Help menu. Sometimes it is already running. The problem is lack of feedback: it seems, if it found an update, and is now downloading one, it doesn't tell the user it is doing this. Which would be useful.

Instead, as it is downloading the update, it simply looks like it is stuck checking for one. It would be nice if the Menu item could change to something like "Downloading Update (1.0.2) 43%..." or similar while it is doing this, to give feedback to the user that something is actually going on.

**Comment by 50Wliu** [comment]
Checking Update and Downloading Update should be displayed correctly (but without a version number and %) - what are you seeing instead?

**Comment by Ivoz** [comment]
I am running Windows 7 x64, with atom installed from `atom.io` installer.

I am always only seeing a greyed out `Checking for Update` while I am pretty sure there is the new update being downloaded. After it is completely finished, (takes a while for me with ADSL over in Australia) IIRC it updates to text that a new update is ready to be installed (been a week since it happened, sorry).

I can quite clearly remember never seeing a `Downloading Update` text.

**Comment by Zireael07** [comment]
Seconding @Ivoz's observations. Never seen downloading update...

**Comment by 50Wliu** [comment]
I'm seeing `Downloading Update` right now as I'm updating to 1.0.3...
![downloading-update](https://cloud.githubusercontent.com/assets/2766036/8947568/7aeb4d8e-356a-11e5-87b5-a03f78636591.png)

Does this also happen with auto-updates or only when you click "Check for updates"?  In my case, Atom started auto-updating and displayed "Downloading update".

**Comment by batjko** [comment]
A percentage or other progress indicator would indeed be nice.

I didn't pay attention when I just updated, so not sure which text it displayed actually.

**Comment by Ivoz** [comment]
I can report I see Downloading Update now, on 1.0.2 -> 1.0.3

![Downloading Update](http://i.imgur.com/cjn48dB.png)

I'm guessing this could have been fixed by something in 1.0.2, haven't verified that yet though.

It seemed to take a while to show up, though. I would have thought a 'new version check' would normally be a <1 second network operation after which you'd quickly update the text.

I'd still advocate making the text more detailed, as a cosmetic upgrade. Adding ellipses at the end, for instance, is a common standard for indicating that something is ongoing. So text like `Downloading Update... (<new_version_>)` would be cool.

**Comment by 50Wliu** [comment]
@Ivoz Is there any reason you closed this?

**Comment by Ivoz** [comment]
@50Wliu PR to implement this was closed in #8483 so I thought this wasn't wanted. If I'm wrong I can leave it open, would be nice to see.

**Comment by 50Wliu** [comment]
All that #8483 did was add ellipses to the context menu, not add a download percentage or version.  I haven't had time to look into that yet but I'll try to investigate this week.

**Comment by 50Wliu** [comment]
Unfortunately I'm too busy to realistically take a look at fixing this, so I'm going to unassign myself so that others can take a shot at it.
