### ISSUE TITLE
OSX: ctrl-backspace binding not working

### ISSUE THREAD

**Issue by zyklus** [atom/atom#8040]
I have the following binding:

```cson
'ctrl-backspace'  : 'editor:delete-to-beginning-of-word'
```

It's being blatantly ignored :(

OSX 10.10.4
Atom 1.0.2

**Comment by mnquintana** [comment]
Can you post your entire `keymap.cson`?

**Comment by zyklus** [comment]
```cson
'atom-text-editor':
  'ctrl-left'       : 'editor:move-to-beginning-of-word'
  'ctrl-right'      : 'editor:move-to-end-of-word'
  'ctrl-shift-left' : 'editor:select-to-beginning-of-word'
  'ctrl-shift-right': 'editor:select-to-end-of-word'
  'ctrl-delete'     : 'editor:delete-to-end-of-word'
```

**Comment by mnquintana** [comment]
Can you open up the keybinding resolver (with <kbd>Cmd-.</kbd>), enter <kbd>Ctrl-Backspace</kbd> on your keyboard, and take a screenshot of what you see?

**Comment by zyklus** [comment]
<img width="1143" alt="screen shot 2015-07-23 at 10 31 19 pm" src="https://cloud.githubusercontent.com/assets/320562/8852921/91e56e86-318a-11e5-8993-bc8c641f1d1d.png">

**Comment by mnquintana** [comment]
@zyklus Try this:

```cson
'.platform-darwin atom-text-editor':
  'ctrl-backspace'  : 'editor:delete-to-beginning-of-word'
```

It looks like the keybinding from bracket-matcher was overriding your custom keybinding because its selector was more specific.

**Comment by zyklus** [comment]
Thanks!  Is there documentation on this?  I feel like it should be easier to figure this out :)
