### ISSUE TITLE
Keep files open after close and start

### ISSUE THREAD

**Issue by stebiger** [atom/atom#8042]
Hey,

it would be nice if atom would open the files  when I start atom again.

If I currently have 3 files open and close atom upon restarting atom only the first file is still open in editor.

**Comment by mnquintana** [comment]
Atom should be restoring all of your files. What OS are you on? What version of Atom? Can you reproduce this in safe mode? (`atom --safe`) How are you quitting Atom? Are any of those 3 files unsaved?

**Comment by batjko** [comment]
Is this a preview tabs thing? I.e. if two the three previously opened tabs were unchanged, will it only restore the third one that was actually touched?

**Comment by stebiger** [comment]
It is reproducable for me on windows 7 enterprise x64. Current version 1.0.2

I am quitting by pressing X Close button on window.
All files are saved files on disk (but where not modified) - but also unsaved files should be kept.

It does also not work when starting with --safe mode.

**Comment by mnquintana** [comment]
Can you post the contents of your `config.cson`?

**Comment by benogle** [comment]
Seems like he wants [autosave untitled buffers](https://github.com/atom/atom/issues/942)

**Comment by stebiger** [comment]
> Seems like he wants autosave untitled..
Well, yes this feature is hidden in this case but not the solution for the core problem, but thanks for noticing the issue I can subscribe there.

> config.cson
"*":
  "exception-reporting":
    userId: "35af3146-5ed9-24cc-b1c0-ea9f7b38829c"
  welcome:
    showOnStartup: false
  core:
    excludeVcsIgnoredPaths: false
    themes: [
      "atom-material-ui"
      "apathy-theme"
    ]
    disabledPackages: [
      "auto-encoding"
      "autoflow"
    ]
    fileEncoding: "windows1252"
    autoHideMenuBar: true
  editor:
    invisibles: {}
    tabLength: 4
    fontSize: 15
  minimap: {}
  "one-light-ui": {}
  "apathy-theme":
    enableTreeViewBorder: true
    enableTreeViewStyles: true
  "atom-material-ui":
    accentColor: "Green"
    panelContrast: true
    depth: true
  "keyboard-localization": {}
  "merge-conflicts": {}
  "terminal-status": {}
  "file-icons":
    forceShow: true
    onChanges: true
  "tool-bar":
    position: "Left"

**Comment by mnquintana** [comment]
> Well, yes this feature is hidden in this case but not the solution for the core problem, but thanks for noticing the issue I can subscribe there.

I'm not sure I understand - does https://github.com/atom/atom/issues/942 cover what you're looking for?

**Comment by stebiger** [comment]
No it is not - it is just a part of what I am looking for.

The core problem is: 3 files are open and I close atom. Launch atom again and only first file is still open

**Comment by piteer1** [comment]
I have a similar issue, Atom just does not save all the tabs in most of the cases. When I'm left with one last tab, then this one is saved always and restored during Atom restart. When there's more than one tab open then it is random. I'm using it on OS X and quiting Atom using CMD + q, here's my cson also:

```cson
"*":
  "exception-reporting":
    userId: "ee6d532c-0680-e1e2-dce5-c68a4811d3ed"
  welcome:
    showOnStartup: false
  editor:
    fontSize: 13
    invisibles: {}
    tabLength: 4
  core:
    disabledPackages: []
    themes: [
      "one-dark-ui"
      "monokai"
    ]
  "autocomplete-plus":
    minimumWordLength: 1
  "atom-ternjs": {}
  linter:
    subtleLinterErrors: [
      "jshint"
      "pep8"
    ]
  docblockr:
    auto_add_method_tag: true
  whitespace:
    ignoreWhitespaceOnCurrentLine: false
  minimap: {}
  "atom-beautify":
    _analyticsUserId: "805662f9-40af-480b-8b12-eccf5ff998e2"
  tabs:
    usePreviewTabs: true
  "file-watcher":
    promptWhenFileHasChangedOnDisk: false
  nuclide:
    remoteProjectsConfig: []
  "linter-jshint": {}
  autosave: {}
```

Unsaved tabs are for sure not preview tabs.

**Comment by davidak** [comment]
@mnquintana @lee-dohm i have a similar issue with Atom 1.14.2 on elementary OS 0.4 Loki (based on Ubuntu 16.04 LTS).

I have 2 folders open in Atom. When i close Atom and open it again, only one is opened. Both windows have unsaved files. That is very scary because you think you lost that data!

When i open the folder again, also the unsaved files are there. So, no data loss but it would be really helpful to have all the windows again to just continue working.

**Comment by 50Wliu** [comment]
@davidak when you say "2 folders open in Atom", does that mean you have two Atom windows open, each with its own folder?  If so, when closing Atom you'll need to Quit it (File -> Quit) instead of closing each window.

**Comment by davidak** [comment]
@50Wliu thanks, you are right. I used the "close all" (windows) entry in [Pantheon Dock](https://launchpad.net/pantheon-dock).

**Comment by lee-dohm** [comment]
Does anyone have steps to reproduce this problem? I haven't been able to reproduce it. Given the information we have here, there isn't enough to take action.

**Comment by vinodhl** [comment]
Not sure if this helps but I am able to reproduce this on my Win 7 64Bit Pro
1. Open few files in atom
2. Click the X in Atom to close it
3. Most important: Restart the entire OS (Either Restart or Shutdown and then Power On)
4. Launch Atom again
5. Only one file is open.
