### ISSUE TITLE
At the building stage, Running "download-atom-shell" task ends without errors

### ISSUE THREAD

**Issue by canercandan** [atom/atom#8045]
Atom: v1.0.2
Node: v0.12.6
npm: v2.5.1
Archlinux (4.0.7-2-ARCH, x86_64)

At the building stage (script/build), the script ends at the following task without dumping any errors:

```Running "download-atom-shell" task```

If you are facing on the same issue, it is probably due to a bug with the request module failing with users behind proxy (https://github.com/atom/node-github-releases/issues/2).

You can add the ```--stack``` option to the file ```script/utils/run-grunt.js``` to dump the hidden error to your console (@ the line 14):

```var args = ['--gruntfile', path.resolve('build', 'Gruntfile.coffee'), '--stack'];```

Then rebuild Atom thanks to the same command line ```./script/build``` will probably dump a similar error:

```
TypeError: Request path contains unescaped characters.
…
```

I temporary fixed the issue by removing my *_proxy env variables (bash):

```unset http_proxy https_proxy ftp_proxy HTTP_PROXY HTTPS_PROXY FTP_PROXY no_proxy NO_PROXY```

and then everything goes well:

```
Running "download-atom-shell" task
Running "download-atom-shell-chromedriver" task
Running "build" task
Running "coffee:glob_to_multiple" (coffee) task
>> 333 files created.
Running "prebuild-less:src" (prebuild-less) task
Running "cson:glob_to_multiple" (cson) task
>> 170 files compiled to JSON.
Running "peg:glob_to_multiple" (peg) task
Running "generate-license:save" (generate-license) task
Running "generate-module-cache" task
Running "compile-packages-slug" task
Running "set-version" task
Running "generate-asar" task
Done, without errors.
```

It will be preferable to definitely fix the issue by replacing the version of the ```tunnel-agent``` package (https://github.com/npm/npm/issues/4569#issuecomment-62051308).

Thanks.

**Comment by mnquintana** [comment]
Thanks for the report and link to the comment on npm/npm! It looks like https://github.com/atom/atom/pull/7249 should fix this.
