### ISSUE TITLE
[Performance] Converting a 2k lines JSON file from spaces to tabs takes ~15sec

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#8046]
Converting a ~2k lines (2386) JSON file from spaces to tabs takes around 15 seconds (with the UI completely freezed).

The JSON doesn't have any errors and it has been formatted by an external tool, so this is just a "replace each 4 spaces with 1 tab" operation.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/whitespace? Thanks!

**Comment by alexandernst** [comment]
https://github.com/atom/whitespace/issues/87
