### ISSUE TITLE
"Find" doesn't move the cursor to the match

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#8047]
Not sure if a bug or a feature, but "find"ing stuff doesn't move the cursor to the first match (which I'd say is the expected behavior as all other editors I know do it and because it doesn't make any sense not to move the cursor to the first match as the whole point of searching something is to see it/where it is).

**Comment by benogle** [comment]
There is a new setting in the find and replace settings which should be out in atom 1.0.3 next week:

![screen shot 2015-07-23 at 10 34 05 am](https://cloud.githubusercontent.com/assets/69169/8857413/66b01d2e-3126-11e5-8432-200d749a16df.png)
