### ISSUE TITLE
Save Warning on Tab Move

### ISSUE THREAD

**Issue by DerekTBrown** [atom/atom#8054]
When moving an unsaved file from one window to another (by dragging the tab from window to window), Atom displays a save warning, despite the file not being closed.

**Comment by kevinsawicki** [comment]
Can you include the warning in a screenshot?

**Comment by DerekTBrown** [comment]
If I have a document in one window (left) with unsaved changes, and I try to move it into another window (right), it gives a save prompt, even though the file is not getting closed, only moved.

![screenshot from 2015-07-27 20-56-48](https://cloud.githubusercontent.com/assets/6845676/8921335/11e96316-34a2-11e5-9186-739a6ae7cf1e.png)

**Comment by mnquintana** [comment]
What version of Atom are you using? I can't seem to reproduce this with 1.0.3-62a46f6 and OS X 10.10.4.

**Comment by DerekTBrown** [comment]
For posterity sake I upgraded to the 1.0.2, still the same warning:

![screenshot from 2015-07-27 21-33-06](https://cloud.githubusercontent.com/assets/6845676/8921681/32f20be4-34a7-11e5-9d10-cac652a372b3.png)

I am using the latest release from the AUR: 
https://aur.archlinux.org/packages/atom-editor/

**Comment by 50Wliu** [comment]
Cannot reproduce, assuming fixed.

**Comment by DerekTBrown** [comment]
Confirmed.  Seems to be fixed.
