### ISSUE TITLE
Remember toggle soft wrap option

### ISSUE THREAD

**Issue by lamerman** [atom/atom#8057]
I would be great if the value of this option is saved somehow. How one has to turn it on every time. Maybe it should be saved separately for different file formats, maybe globally.

**Comment by mnquintana** [comment]
There's already a setting for it:

<img width="737" alt="settings_-__users_machistequintana_github_atom_-_atom" src="https://cloud.githubusercontent.com/assets/823545/8874200/97cf9978-31dc-11e5-827e-40ba883665ab.png">

You can also scope this setting to different grammars in your `config.cson`:

<img width="265" alt="config_cson_-__users_machistequintana_github_atom_-_atom" src="https://cloud.githubusercontent.com/assets/823545/8874232/ff96f538-31dc-11e5-89de-015b6938f722.png">
