### ISSUE TITLE
Manual keymaps sometimes being ignored in preference of package defaults

### ISSUE THREAD

**Issue by mauricioszabo** [atom/atom#8064]
I'm an vim-mode user and my keyboard layout is ABNT-2. This means that, when using Atom, I need to remap the "?" keymap to `ex-mode` command, otherwise my keymaps are wrong.

Sometimes, specialy when I upgrade `vim-mode` package, their keymaps are overriding mine. Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/138037/8879530/43a46ff0-3208-11e5-9144-47ce2a221330.png)

As you can see, vim-mode is capturing my keymap, and the manual keymaps defined in Atom are being ignored. This is a recurring issue - most of the time, I don't know if my keymaps are being overriden or not.

**Comment by tmunro** [comment]
@mauricioszabo Could this problem be related to vim-mode renaming `command-mode` to `normal-mode` in the selectors? You might need to change your selector.

**Comment by maxbrunsfeld** [comment]
Yeah, they're ordered by specificity, similar to CSS. When there is a tie though, I believe your custom key-maps should take precedence. For now, you could workaround this by making your selector at least as specific as vim-mode's (`atom-text-editor.vim-mode.normal-mode`).

**Comment by mauricioszabo** [comment]
@tmunro, this corrected the issue, thanks.

@maxbrunsfeld, don't custom keymaps should *always* take precedence over the others, even if it is less specific? I don't know how to test this, but it is kinda hard to overwrite keymaps if we need to keep track if that keymap is being used by some package or some atom internals, and if the selector that matches that keymap is specific or generic, and then trying to map to, at least, the same level os specificity... it's a lot of steps to just add a shortcut to a command...

**Comment by izuzak** [comment]
> don't custom keymaps should always take precedence over the others, even if it is less specific? 

@mauricioszabo No, that's not the case at the moment. Thanks for the feedback on this -- would you mind adding this to an existing issue (which is a bit more general), so that we have everything in one place? https://github.com/atom/atom/issues/6718
