### ISSUE TITLE
Shrink or scroll editor when panels at bottom open up

### ISSUE THREAD

**Issue by adamreisnz** [atom/atom#8068]
If this has been raised before or if this is the wrong repo, please correct me. I couldn't find a previous issue for it. I've raised this issue at the atom linter repository originally, see https://github.com/atom-community/linter/issues/758, but we felt this was a more widespread issue and not the responsibility of the linter package.

Considering that [linter might get integrated into the atom core](https://github.com/atom/atom/issues/7353), it's probably a good idea to handle this issue in atom core anyway.

The problem is with panels that open up at the bottom of the Atom window (e.g. find & replace, linter) while you are working on code which is at the bottom of a file. These panels overlap your code when they open, hiding the code from view and forcing you to scroll up.

Type something erroneous at the bottom:
![ss](https://www.dropbox.com/s/aplhj66dn0mohfv/Screenshot%202015-07-21%2011.57.04.png?dl=1)

Panel shows up and overlaps your code:
![ss](https://www.dropbox.com/s/qqren1bvolmc2l9/Screenshot%202015-07-21%2011.57.35.png?dl=1)

The problem is particularly troublesome with automatically opened windows, like linter. The find & replace panel never bothered me like that, because it's triggered manually with a keyboard command, so you're not focussed on typing code anyway. But with the linter panel, you are, and it's very disturbing to have the panel suddenly show up and block your view of your code.

A proposed work around has been to enable the setting "Scroll Past End", but while this alleviates the issue a little bit, it doesn't solve it and it can still happen when you forgot to scroll further up.

A better solution would probably be for the panels to not overlap the editor window, but rather push it up causing it to shrink. I realize this might cause the opposite problem though, e.g. if you're typing at the top of the file, then that code would be pushed out of view.

Any idea's?

**Comment by v3ss0n** [comment]
Yes that is very annoying . it should just put editor up.

**Comment by abe33** [comment]
I believe this is an issue with the linter, `find-and-replace` insert its pane in the bottom panel, and panels use a flexbox layout, using `one-dark-ui` this is what I get when I open find and replace: 
![_comments_sass_-__users_c_nehemie_gsoi_newho_vendor_gsoi_style-framework_-_atom](https://cloud.githubusercontent.com/assets/247140/8928306/ca0f4746-351d-11e5-9811-7f3772edee8d.png)

Or if you don't have this result with the find-and-replace then it's probably an issue with the theme you use, but as far I can tell you're using `one-dark-ui` too.

**Comment by aaronjensen** [comment]
@abe33 that's not the issue. The issue is that it appearing overlaps where the cursor may be.  

### Repro

1. Turn off "Scroll Past End"
2. Open a file that is taller than the editor.
3. Put your cursor at the bottom of the file.
4. Open find-and-replace w/ cmd-shift-f (on a mac) or however.

### Actual

The find and replace panel overlaps where my cursor was, hiding my cursor and my context.

### Expected

My cursor stays in view, in this case, the editor would need to scroll up. so that the cursor is still visible.

![panel](https://cloud.githubusercontent.com/assets/8588/8934771/2237637e-34fe-11e5-9248-259a4697f8de.gif)

**Comment by aaronjensen** [comment]
One other thing to note, manually scrolling up after the find and replace panel appears only temporarily helps. If you close the panel, then reopen it, the problem repeats. This is why it is such a problem for things like linter which open and close the panel/change its size regularly.

**Comment by adambuczynski** [comment]
Yes, @aaronjensen is right. Linter in particular is annoying if you don't have `scroll past end` enabled, because of the frequent opening and closing of the panel.

**Comment by abe33** [comment]
Ok, sorry guys I was a bit confused, hopefully the screencast made it clear for me. As I see it, it sure should be handled in core. Whenever the text-editor is resized it should make sure the (last) cursor is still visible.

@benogle It looks like something that could fit the quality initiative roadmap, don't you think?

**Comment by gkrawiec** [comment]
This issue pops up as a huge bug in a specific case when the windows is divided into top and bottom panes. Please look at this issue in linter for a video of the problem.
https://github.com/atom-community/linter/issues/779#
THough the bug is serious in the linter situation, the issue is caused by the way atom manages the panels and how panes move up to let a new pane grow.

**Comment by adambuczynski** [comment]
@abe33 Do you still need more information on this issue?

**Comment by Stefan-Code** [comment]
+1

**Comment by adambuczynski** [comment]
Does this still need more information?

**Comment by benogle** [comment]
Nope. Relabeled to bug.

**Comment by steelbrain** [comment]
The bug described here is also addressed in https://github.com/atom/atom/issues/11249

**Comment by joshaber** [comment]
It's related but I'm not sure #11249 solves the whole thing. E.g., when my cursor's at the bottom of the editor and I use Find.

**Comment by steelbrain** [comment]
@joshaber You are right, I meant that they are related :)
