### ISSUE TITLE
Unable to select text by highlighting with mouse

### ISSUE THREAD

**Issue by ajcann** [atom/atom#8069]
Atom 1.0.2 on Ubuntu 14.04.02 in 
Virtualbox 4.3.20  with 3d acceleration enabled on Win 8.1 Pro physical host
Mouse integration is enabled - when disabled, highlighting of text works, however mouse cursor disappears.

Seems related: https://discuss.atom.io/t/mouse-selection-problem/16623
Chromium version issue?

**Comment by 50Wliu** [comment]
> Chromium version issue?

Exactly.  You can follow #6306, #6243, and also #6219 for more information and updates.  Also, #7877 will fix this when it gets merged.

**Comment by ajcann** [comment]
Cheers - thanks, Wliu.
