### ISSUE TITLE
TextEditor::pasteText does not emit did-insert-text

### ISSUE THREAD

**Issue by jacekkopecky** [atom/atom#8070]
`insertText` calls `@emitWillInsertTextEvent(text)` and later `@emitter.emit 'did-insert-text', didInsertEvent`, but `pasteText` only does the former and never the latter.

**Comment by jacekkopecky** [comment]
Thanks, looking forward to 1.0.3 :sunglasses:

**Comment by as-cii** [comment]
:heart:
