### ISSUE TITLE
Find in Project searches performs search in recently removed project folders

### ISSUE THREAD

**Issue by bobbysciacchitano** [atom/atom#8072]
I'm having a reproducible issue in Atom 1.0.2 Mac where when I run Find in Project the search also searches in projects that I've removed from the sidebar and as well as the currently selected / open project.

The only way I've managed to get around it is by quitting and reopening Atom.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace? Thanks!
