### ISSUE TITLE
Issue with multiple cursor history and atom-alignment plugin

### ISSUE THREAD

**Issue by zyklus** [atom/atom#8073]
This is being triggered by a plugin, but I believe it belongs here because plugins _probably_ shouldn't be responsible for micro-managing things like history.

The package `atom-alignment` just aligns cursors.  Unfortunately it adds one history event per cursor, which is quite annoying.

```json
{
  "a"|: 1,
  "ab"|: 1,
  "abc"|: 1
```

align cursors

```json
{
  "a"  |: 1,
  "ab" |: 1,
  "abc"|: 1
```

undo (note nothing happens, it's resetting the 3rd cursor which didn't move):

```json
{
  "a"  |: 1,
  "ab" |: 1,
  "abc"|: 1
```

undo:

```json
{
  "a"  |: 1,
  "ab"|: 1,
  "abc"|: 1
```

undo:

```json
{
  "a"|: 1,
  "ab"|: 1,
  "abc"|: 1
```

**Comment by maxbrunsfeld** [comment]
This means that the `atom-alignment` plugin is performing one change per cursor. It needs to use the `TextEditor::transact` method to group these changes.
