### ISSUE TITLE
Old tabs startup 

### ISSUE THREAD

**Issue by larsenwork** [atom/atom#8076]
When I start Atom it doesn't remember my most recent open windows but instead shows me 3 tabs from a now very old session.
This also happens when running `atom --dev`

Mac 10.10.4 Atom 1.0.2

**Comment by izuzak** [comment]
How _exactly_ are you starting Atom? Do you see the problem when you start Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by larsenwork** [comment]
@izuzak From Spotlight, from Finder, `atom --dev`, `atom --safe`

**Comment by izuzak** [comment]
@larsenwork If you start Atom like that, then it will restore the previous session. If you start Atom like this, then it will use the current directory for the new session: `atom .`

Can you try that and see if the behavior changes?

**Comment by larsenwork** [comment]
No difference. If you read my initial comment you'd see that the issue isn't a previous session being opened but a very old session

**Comment by izuzak** [comment]
> If you read my initial comment you'd see that the issue isn't a previous session being opened but a very old session

Your initial comment doesn't really say how you're running Atom, which is relevant, as I explained. Having all the relevant details is helpful for debugging, as I'm sure you'd agree. So let's continue investigating. Did I understand correctly that the same tabs are opened regardless of which folder you run `atom .` in? Have you tried doing that from several different folders/projects?

**Comment by larsenwork** [comment]
Running atom from `~/` (plus launching from Finder + Spotlight): very old (and outdated - i.e. not previous) session
Running atom from a folder: untitled doc + empty tree

**Comment by izuzak** [comment]
Thanks for clarifying, @larsenwork. 

I'm having trouble reproducing that behavior. @maxbrunsfeld what am I missing here?

**Comment by larsenwork** [comment]
I'm not sure but I think the problem appeared after the computer shut down improperly (empty battery) if that helps.
Anything I can do now to "reset" previous states?

**Comment by maxbrunsfeld** [comment]
So Atom is reopening the correct *folder* when you run it from spotlight, but the editor is in an old state? What happens when you just reload Atom (`Window: Reload` command). Atom attempts to save this state when you exit. How are you quitting Atom?

**Comment by larsenwork** [comment]
Hehe...well now it works. 
I've had this issue for the last month without being able to fix it (launched it in many different ways, incl. `atom --dev`, `atom --safe` `View -> Reload` and from Finder and using Spotlight).
I normally quit atom using cmd+q but as written above I think this problem started after my computer turned off due to battery 0%. 

I've done nothing that can explain why it suddenly works again (no updates, removing packages etc). I simply quit and reopened to be able to answer the folder question by @maxbrunsfeld 

Feel free to close it. I'll reopen if it reappears.

Thanks

**Comment by maxbrunsfeld** [comment]
Ok, if you're interested in diagnosing this if it appears again, you should look at the files in `~/.atom/storage`. There's two main things in there: `application.json` which stores *which* folders are open, and `editor-<some-hash>`, which stores the state for a given editor. The name of the `editor-` file for a given window can be obtained by running this code in the javascript console:

```js
atom.constructor.getStateKey(atom.project.getPaths(), "editor")
```

These editor-specific files should be updated when quitting Atom.

**Comment by larsenwork** [comment]
Ok, then something caused them not to be updated ¯\_(ツ)_/¯ 
I'll look at those files should the problem reappear
