### ISSUE TITLE
Atom crashes on minified js files

### ISSUE THREAD

**Issue by andreasonny83** [atom/atom#8077]
It's quite annoying every time I try to open a big minified Javascript or css file, Atom freeze and sometimes I manage to close the document, some other I need to reload the software.
Thus I'm not sure if this bug is happening just on my machine, I would appreciate a feedback on this topic

**Comment by mnquintana** [comment]
This is a duplicate of https://github.com/atom/atom/issues/979 – please subscribe there for updates.

**Comment by andreasonny83** [comment]
Thanks for your quick comment but I saw that ticket already however that one is dated 2 years ago and I'm not sure someone is still working on that

**Comment by mnquintana** [comment]
@andreasonny83 If it's open then it will be addressed eventually, regardless of its age. Opening duplicate issues definitely won't make a fix happen any faster, though.
