### ISSUE TITLE
[feature request] Display non-breaking space character when showing invisibles. 

### ISSUE THREAD

**Issue by maxcal** [atom/atom#8080]
It would be really nice if the editor displayed an "invisibles" symbol for the character UNICODE NON BREAK SPACE `U+00A0` as it most often is added by mistake and gives pretty perplexing error messages. It is currently visually indistinguishable from the normal space. 

![image](https://cloud.githubusercontent.com/assets/765647/8891079/ba5cf786-3319-11e5-9786-75be7a4b618f.png)

(You can't see it but it's there...)

**Comment by lifeBalance** [comment]
**+1** for this feature.
I've come accross this error when doing Ruby. Sometimes I copy-paste code from books, and the code throw errors because it contains the `U+00A0 ` character, which is invisible to the eye. In Sublime I use a script that shows these characters. It would be great have that in **Atom**.

**Comment by renholm** [comment]
+1

**Comment by askehansen** [comment]
+1

**Comment by wismill** [comment]
+1

There is a special symbol to represent that: "⍽" (Unicode: 237D).

There are also [variants](https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation) of the non-breaking space.

**Comment by askehansen** [comment]
I ended up adding a custom keybinding:
```
# ~/Library/KeyBindings/DefaultKeyBinding.dict

{
  "~ " = ("insertText:", "💩");
}
```

So now every ones in a while a 💩 shows up in my code instead. Its hilarious 😂

**Comment by toukovk** [comment]
Note that there is a package [highlight-bad-chars](https://libraries.io/atom/highlight-bad-chars/) that higlights non-breaking spaces and a couple of other similar potentially problematic characters.
