### ISSUE TITLE
RTL and LTR mixture in a line makes some problems.

### ISSUE THREAD

**Issue by MahdiPOnline** [atom/atom#8081]
There's a bug (more like a problem) with mixing rtl and ltr languages in a line in Atom. The cursor would go crazy and it would be almost impossible to get what you see. Take a look. the third line is the clipboard of the selection in line 1.
https://imgur.com/q1DAEJt

**Comment by 50Wliu** [comment]
Duplicate of #1849, please subscribe there for updates.
