### ISSUE TITLE
Atom treats left click as right click (maybe?) on opensuse Tumbleweed

### ISSUE THREAD

**Issue by yisding** [atom/atom#8084]
![atom tumbleweed](https://cloud.githubusercontent.com/assets/1209314/8892256/22362abe-3304-11e5-8053-afd1291e3e0f.png)

Right clicking on the title of the file doesn't open the context menu like it should. Right clicking on the page doesn't do anything. There's this big blue dot that follows me everywhere I left click (with the weird tablet? context menu)

**Comment by 50Wliu** [comment]
Are you running Atom through Virtualbox?

**Comment by yisding** [comment]
Yes, through VMWare Player (guest OS is opensuse Tumbleweed)

**Comment by mnquintana** [comment]
I think this is the same issue as https://github.com/atom/atom/issues/6306 (looks like VMware Player has the same issue as VirtualBox) – please take a look at that issue for updates on this.

**Comment by yisding** [comment]
For some reason, this only happens on my opensuse tumbleweed install, and not Kubuntu or Fedora. All three are running under VMWare. Could you reopen?
