### ISSUE TITLE
right-click menus are inconsistent

### ISSUE THREAD

**Issue by zyklus** [atom/atom#8085]
Atom 1.0.2

It _seems_ to be a difference between the root folder and sub-folders

<img width="184" alt="screen shot 2015-07-26 at 11 49 37 am" src="https://cloud.githubusercontent.com/assets/320562/8892516/67342646-338d-11e5-887d-1b2928e7b357.png">
<img width="191" alt="screen shot 2015-07-26 at 11 49 57 am" src="https://cloud.githubusercontent.com/assets/320562/8892517/6875ded2-338d-11e5-8e8f-643c02aefaaa.png">

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tree-view? Thanks!

See https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290?u=mnquintana for more information.
