### ISSUE TITLE
"Search in Directory" is unreliable and not searching all files :(

### ISSUE THREAD

**Issue by zyklus** [atom/atom#8086]
Atom 1.0.2

This seems to happen on larger directories, and I've run into it a few times now but don't have a consistent reproduction case --

Search in files often turns up empty or partial results.  The only thing I did between taking the following screenshots was:

- open a few files in the directory
- re-do search

<img width="335" alt="screen shot 2015-07-26 at 11 58 14 am" src="https://cloud.githubusercontent.com/assets/320562/8892520/da6dc310-338d-11e5-9146-0ea58e1a4bd4.png">
<img width="267" alt="screen shot 2015-07-26 at 11 58 34 am" src="https://cloud.githubusercontent.com/assets/320562/8892522/dca07a10-338d-11e5-8a6c-e74bcf833031.png">
<img width="266" alt="screen shot 2015-07-26 at 11 58 44 am" src="https://cloud.githubusercontent.com/assets/320562/8892524/df6edd7c-338d-11e5-8951-f76b404c3c0e.png">
<img width="237" alt="screen shot 2015-07-26 at 11 59 02 am" src="https://cloud.githubusercontent.com/assets/320562/8892525/e0b9bc88-338d-11e5-8fc4-257afae362db.png">

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace? Thanks!

See https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290?u=mnquintana for more information.
