### ISSUE TITLE
Uncommenting block comments not behaving as expected

### ISSUE THREAD

**Issue by kevinschaich** [atom/atom#8087]
If a block of code is commented out, and I place my cursor within the block and press `CMD + /`, I think the desired behavior here is to uncomment it. This is how it works in Sublime and I think it's very intuitive.

This is what happens in Atom:

![block_uncomment_bug](https://cloud.githubusercontent.com/assets/9244728/8892463/63db13cc-330d-11e5-99c5-c8d4f82e2b30.gif)

I can't imagine a situation where this is ever what I needed to do. I think it would be great if the 'toggle comment' command actually uncomments code if your cursor is placed within a commented block.

**Comment by kevinschaich** [comment]
Bump

**Comment by goeddea** [comment]
Second that. I also expect the block comment to be uncommented in its entirety when the cursor is within the block and I press `CMD + /` (or, rather, `CMD + #` on my German keyboard).
