### ISSUE TITLE
Python 

### ISSUE THREAD

**Issue by AHL96** [atom/atom#8088]
```python
import random
import time

anwser = 0
x = 0

while x < 10 :

    num = random.randint(1,9)
    print(num)
    anwser += num
    time.sleep(1)
    x += 1

print("")
print(anwser)
```

instead of printing line by line it waits for the whole program to execute then shows you everything. it should show you line by line

**Comment by 50Wliu** [comment]
Atom does not execute Python files - it's probably one of your installed packages that is doing this.

**Comment by batjko** [comment]
@AHL96 Find whichever package you're using to run the Python script, and re-open the issue on that package's repository, please.
