### ISSUE TITLE
Make disabling DirectWrite an option

### ISSUE THREAD

**Issue by ErmanSayin** [atom/atom#8089]
There should be an option to disable DirectWrite.

**Comment by frabert** [comment]
DirectWrite is soon going to be the only rendering method available in Chromium. It does not seem to be sensible to fallback to something deprecated. Maybe you can elaborate on your issues with rendering?

**Comment by ErmanSayin** [comment]
I use [MacType](https://code.google.com/p/mactype/), which is a font rasteriser for Windows. MacType doesn't work with DirectWrite, so I was looking for a way to disable it

**Comment by frabert** [comment]
Seems quite old... Anyway, just as you have no support for it on Atom you won't have support on Chrome, when the change will be definitive.

**Comment by ErmanSayin** [comment]
Setting this on `styles.less` seems to soften the text a little:
    * {
        -webkit-text-stroke: .02em;
    }

**Comment by frabert** [comment]
What *exactly* is the problem?

**Comment by ErmanSayin** [comment]
The problem is that the text rendering isn't good

![example]
(http://i.imgur.com/ZthW86K.png)

**Comment by frabert** [comment]
Unfortunately, good and bad are personal opinions in this field, so a good way to be able to suggest you new solutions would be to provide an example of what *you* consider good rendering and make a list of the differences you notice

**Comment by photuris** [comment]
ErmanSayin, here's how you do it.

Using a hex editor (like http://mh-nexus.de/en/hxd/), open up the file:
%HOME%\%APPDATA%\Local\atom\app-<version>\resources\app.asar

Search for the string:

    'Direct-write': true,

And replace it with:

    'Direct-write':false,

And save it. Notice I removed the space between the colon [:] and false, so that the saved version will have the exact same amount of characters.

And boom! We now have nice Mac- and Linux-styled fonts, rendered true to shape! Woo!

**Comment by ErmanSayin** [comment]
@photuris I've already figured that out long ago, but thanks anyway

**Comment by photuris** [comment]
@ErmanSayin Cool!

Please post your solution next time, so guys like me can find it!

**Comment by damieng** [comment]
Given that DirectWrite is going to be the only solution in future versions of Chromium this would have a limited lifespan.

Between the various improvements Chromium is making in how it uses DirectWrite and a few things we can so such as ensuring whole-pixel boundaries for lines and the the start of our editor (which also affect other platforms) our rendering will improve but it's going to take a little time.
