### ISSUE TITLE
Usability: Add button beside settings to highlight config.cson

### ISSUE THREAD

**Issue by martinheidegger** [atom/atom#8090]
The Settings dialog at the moment has some user interface to edit the config.cson file. Clicking or changing any value will result in the change of the config.cson file. To explain the use of the config.cson and to understand the relationship easier I propose to add a link next to the config that highlights the property in the config.cson that would be modified on click.

![atomconfig](https://cloud.githubusercontent.com/assets/914122/8894616/158dbb5c-33f8-11e5-9594-958ca02bf0c7.gif)

**Comment by 50Wliu** [comment]
Could you please move this to [atom/settings-view](https://github.com/atom/settings-view)?  Thanks.

**Comment by martinheidegger** [comment]
moved: https://github.com/atom/settings-view/issues/607
