### ISSUE TITLE
Big file saving is too long

### ISSUE THREAD

**Issue by quolpr** [atom/atom#8091]
When I am trying to save big files (5000+lines), atom do it too long, about 10 seconds. As an example, sublime save file very fast - less than 1 second.

My system spec:
1) CPU - AMD A4-5000 APU with Radeon(TM) HD Graphics × 4 
2) ssd 64gb
3) OS - ubuntu 15.04 x64
4) uname -r: 3.19.0-16-generic
5) Atom version - 1.0.2

**Comment by charleswson** [comment]
Do you mean less than 1 second?

**Comment by quolpr** [comment]
Oh, yes, 1 second. I updated my comment.

**Comment by maxbrunsfeld** [comment]
I can't reproduce this. What packages do you have installed (`apm list --installed`)? Can you record and send a screenshot of a Javascript CPU profile while the slow save is occurring?

**Comment by 50Wliu** [comment]
@quolpr do you by any chance have `tabs-to-spaces` installed?  If so, can you try disabling it and see if the problem goes away?

**Comment by benogle** [comment]
Please see https://atom.io/docs/latest/hacking-atom-debugging#diagnose-performance-problems-with-the-dev-tools-cpu-profiler for info on taking and saving a CPU profile.

**Comment by lpommers** [comment]
I've seen this as well when working on large files. This happens to me frequently when writing specs for atom. This profile was taken from saving `text-editor-spec.coffee`. I did have `tabs-to-spaces` installed, but disabling it did not make a difference, the profiles are the same. 
<img width="1053" alt="screen shot 2015-08-17 at 5 38 15 pm" src="https://cloud.githubusercontent.com/assets/5764316/9308894/dd6d3804-4506-11e5-945b-61eb266fac94.png">

**Comment by quolpr** [comment]
Sorry for my long answering. Now atom has ony 2 comunity plugins installed(rails-rspec, set-syants, set-syntax). There are not influence on perfomance, I checked.

So, when I type one symbol in atom editor:
![when_editing](https://cloud.githubusercontent.com/assets/7958527/9309930/4a75a59a-4515-11e5-9ac1-a147912c7b29.png)
And when I am saving it:
![when_saving](https://cloud.githubusercontent.com/assets/7958527/9309946/6cc3a28c-4515-11e5-895a-dfad0f33c2e3.png)
File has about 3400 lines, size - 400kb.

Also I can upload *.cpuprofile file, if needed.

**Comment by maxbrunsfeld** [comment]
@quolpr Can you upgrade Atom and profile the slow save one more time? This looks like a performance regression that we have fixed since 1.0.2.

**Comment by quolpr** [comment]
@maxbrunsfeld ok, I installed version 1.0.7, and it seems that saving is fixed. But typing has some freezes.

When I type 1 symbol (no matter which):
![one_symbol](https://cloud.githubusercontent.com/assets/7958527/9311887/03eb705c-4522-11e5-9728-7961ca12b99e.png)
As I noticed - after I typed one symbol underline is appeared through 1 second.

When I typing many symbols(4 symbols):
![many_symbols](https://cloud.githubusercontent.com/assets/7958527/9312092/42b8ec14-4523-11e5-8ba1-deedcce1557e.png)
![many_symbols_2](https://cloud.githubusercontent.com/assets/7958527/9312095/46db2f82-4523-11e5-8953-01065c201a60.png)
![many_items_3](https://cloud.githubusercontent.com/assets/7958527/9312096/4b8583ac-4523-11e5-8aa7-15038e33a756.png)
![many_item_4](https://cloud.githubusercontent.com/assets/7958527/9312099/5141fb54-4523-11e5-9691-cea2abeb0ab6.png)

**Comment by adambuczynski** [comment]
I am running into this issue with Atom 1.2.4, and trying to save a file with around 50k lines. It freezes up Atom and asks me if I want to quit the editor or keep waiting. After about 2 minutes it finally manages to save the file.

**Comment by lee-dohm** [comment]
@adambuczynski Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
* Can you include a CPU profile?

**Comment by adambuczynski** [comment]
@lee-dohm 

- Mac OS X 10.10.5
- No Emmet
- The problem seems to have reversed, and opening the file now takes about 50 seconds, whereas saving it is faster and now completes after approximately 5 seconds.
- See attached profile for opening the file:

![ss](https://www.dropbox.com/s/bolifttifqboiqt/Screenshot%202015-12-10%2010.47.15.png?dl=1)
