### ISSUE TITLE
Weird Commenting out lines issue

### ISSUE THREAD

**Issue by thebkbuffalo** [atom/atom#8096]
Hi there!  Found an odd bug which may be getting brought on by a package, but am not entirely sure.  When I comment out a line in any langue on any file, the line below also gets commented out.  Or at the very least grey'd out.  Thank you in advance for your help!

**Comment by benogle** [comment]
Can you run atom in safe mode via `atom --safe .`. That will run without packages.

Can you take a screenshot of what you are highlighting, then what is commented after using the command?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8096#issuecomment-125294254. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
