### ISSUE TITLE
Fullscreen refocuses to most recent atom window (El Capitan)

### ISSUE THREAD

**Issue by pzuraq** [atom/atom#8097]
When switch to a fullscreen instance of Atom in El Capitan via either a three-finger-swipe or keyboard shortcut, Atom will switch focus to the most recently focussed window rather than the one in the current space.

I have two fullscreen instances of Atom, A and B. I edit a file in Atom A, then switch my space to B which is one space to the right. Before I can edit or interact in any way, mission control is forced back to Atom A.

Hopefully that's clear enough. I'm pretty sure this is unique to El Capitan.

**Comment by nicholasrq** [comment]
There is same thing with Sublime Text. I guess that this is not a problem of Atom but the bug of OS X.

**Comment by mnquintana** [comment]
@pzuraq Can you also reproduce this with Sublime (or any other app)? If you can, then I'm going to close this out, because this does seem like an El Capitan bug.

**Comment by pzuraq** [comment]
@mnquintana have been able to reproduce with iTerm as well. Closing, sorry about the mixup.
