### ISSUE TITLE
Memory leak (v1.02) on Win7 

### ISSUE THREAD

**Issue by barttt** [atom/atom#8099]
Just installed Atom v.1.02.. I like what I see so far except....
I am experiencing a memory leak on win7
My colleague has the same experience.

You can reproduce it at will:
Start ProcessExplorer.
Start Atom - it should be ok until you load the first file for edit.
With one file open PE will show that Atom is consuming 4k blocks every couple of seconds.
With more than one file open the consumption goes up accordlngly.

**Comment by mnquintana** [comment]
Have you installed any community packages? Can you reproduce this in safe mode? (`atom --safe`)

**Comment by barttt** [comment]
No community packages
Yes it behaves the same in safe mode.
HTH..

**Comment by damieng** [comment]
Let's track this memory leak under #9006
