### ISSUE TITLE
ENFILE: file table overflow

### ISSUE THREAD

**Issue by willwhitney** [atom/atom#8100]
I'm not sure whether Atom is actually the root cause of this or not. I'm running the canary build of Chrome, and it's crashing periodically too. But Atom is certainly having a problem.

<img width="1756" alt="screenshot 2015-07-27 18 09 33" src="https://cloud.githubusercontent.com/assets/597829/8919120/ee744c28-348a-11e5-9851-677f3174b94f.png">

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [language-html](https://github.com/atom/language-html) package, v0.40.0

### Stack Trace

Failed to load a language-html package grammar

```
At ENFILE: file table overflow, open '/Applications/Atom.app/Contents/Resources/app.asar' in /Applications/Atom.app/Contents/Resources/app.asar/node_modules/language-html/grammars/html.json

Error: ENFILE: file table overflow, open '/Applications/Atom.app/Contents/Resources/app.asar'
  at Error (native)

  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/language-html/grammars/html.json:1:1
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/will/code",
    "audioBeep": false,
    "disabledPackages": [
      "autocomplete-snippets",
      "vim-mode",
      "script",
      "spark-monitor-atom",
      "typewriter"
    ]
  }
}
```

### Installed Packages

```coffee
# User
jupyter-notebook-atom, v0.0.0
language-elm, v0.5.0
language-julia, v0.9.0
language-latex, v0.6.1
language-lua, v0.9.4
language-r, v0.2.0
react, v0.12.4

# Dev
No dev packages
```

**Comment by willwhitney** [comment]
I take it back. 90% sure this is because of code I wrote. Sorry for the false alarm!

**Comment by gnestor** [comment]
@willwhitney Can you remember what was causing this? I'm seeing it now coming from my own package. It kinda sounds like an NPM issue?

**Comment by willwhitney** [comment]
I don't remember for sure — this may have been from when I was opening sockets but not closing them. 

Sorry I couldn't be more helpful!

**Comment by gnestor** [comment]
No problem. I think the problem has gone away on its own so it probably was related to NPM.
