### ISSUE TITLE
Text editing performance issue with many markers (persistent: false, maintainHistory: false)

### ISSUE THREAD

**Issue by ArtemGovorov** [atom/atom#8106]
I'm creating a plugin that creates quite a few markers with
``` JavaScript
persistent: false,
maintainHistory: false
```
and I'm hitting editing performance issues when I create many markers.

For example, in a source file with 5000 lines and ~2300 markers, adding a single character results in:
![screen shot 2015-07-28 at 7 44 57 pm](https://cloud.githubusercontent.com/assets/979966/8928463/01de2f2c-3562-11e5-871c-dde8486918e2.png)

Same operation in a source file 10000 lines and ~4500 markers:

![screen shot 2015-07-28 at 7 41 36 pm](https://cloud.githubusercontent.com/assets/979966/8928497/2a86ae68-3562-11e5-96ac-18e4def9cca2.png)

Search markers suffer the same issue, so can it be reproduced by opening a relatively large source file, searching for a single character, such as `a` and trying to type while search markers are rendered. Any code linters suffer the same issue on medium-large files as well.

**Comment by maxbrunsfeld** [comment]
Thanks for the report. Is this on Atom 1.0.2? I'm surprised that marker snapshots are taking so long when all these markers have `maintainHistory: false`. Is the source code of your package public? If so, could you share a link to it?

**Comment by ArtemGovorov** [comment]
Yep, it was 1.0.2. 
Just upgraded to 1.0.3 and the issue has gone. Now editing ~20k lines source file with ~13k markers looks like:

![screen shot 2015-07-29 at 10 13 53 am](https://cloud.githubusercontent.com/assets/979966/8947145/b0707c98-35da-11e5-9578-bb59de63e6f4.png)

and that's just awesome comparing to what it was, great job! Please feel free to close the issue. 

The source code is not public yet, but I have extracted [the gist](https://gist.github.com/ArtemGovorov/8dce6ec67959b6ce97a5#file-atom-markers-performance-js) demonstrating the issue.

**Comment by maxbrunsfeld** [comment]
That's strange, the only related change that I'm aware of from Atom 1.0.2 to 1.0.3 is changing the default of `maintainHistory` from true to false, since it's so expensive to maintain. I'm glad the issue is fixed though.
