### ISSUE TITLE
atom always adds characters when I save a file

### ISSUE THREAD

**Issue by awaemmanuel** [atom/atom#8108]
Hello team, 

I have this very weird issue, whenever I open a file with atom everything is fine, I can make modifications until I save the file, and try to commit in git.

Git shows every line in the file as changed, when there is no visible change. I think atom is appending some hidden characters like eol or something.

auto.crlf is set to false in my global config so I don't see when atom may try to convert/add more characters to each line.

Sublime Text, TextWranger, TextEdit all work fine without any issues.

Please advise.

**Comment by mnquintana** [comment]
See https://discuss.atom.io/t/why-is-atom-deleting-trailing-whitespace-why-are-there-all-these-changes-in-the-file-diff/19189 for more information.
