### ISSUE TITLE
ESLint throws errors.

### ISSUE THREAD

**Issue by akash-bhardwaj** [atom/atom#8113]
Hi,

I'm using Eslint and Linter as a package. I've installed Eslint locally as well as globally. Tried every solution on the internet, but nothing seems to work for me. I keep getting these errors:

![screen shot 2015-07-28 at 7 17 17 pm](https://cloud.githubusercontent.com/assets/7085282/8933205/2ed78d1e-355f-11e5-955f-c5ca543915f6.png)

![screen shot 2015-07-28 at 7 27 56 pm](https://cloud.githubusercontent.com/assets/7085282/8933210/3a03eb88-355f-11e5-87af-524d984d4814.png)

Here is my .eslintrc file:

![screen shot 2015-07-28 at 7 17 47 pm](https://cloud.githubusercontent.com/assets/7085282/8933221/4c3121ea-355f-11e5-8186-b6ea53b0ee0b.png)

and  here is my Eslint package settings:

![screen shot 2015-07-28 at 7 20 41 pm](https://cloud.githubusercontent.com/assets/7085282/8933241/6351efee-355f-11e5-81b8-ba27d57efd75.png)

Please help! Thanks in advance :)

**Comment by mnquintana** [comment]
Please reopen this on https://github.com/AtomLinter/linter-eslint – see https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290?u=mnquintana for more information on what belongs in atom/atom.

**Comment by akash-bhardwaj** [comment]
Sure, sir! My bad :)
