### ISSUE TITLE
Make it easier to find crash reports

### ISSUE THREAD

**Issue by dankcushions** [atom/atom#8117]
Atom crashed a lot for me. Normally I would post the crashes up as issues, but there were no logs, or error messages, just a generic "I've crashed" and options to close, ignore, or restart. This leaves me at a bit of a loss as to how to contribute the issue to the community, rather than just ditch atom.

I understand I can potentially get at the error messages by using the internal debugging tools, but that seems a bit obfuscated. Can't it show more information about crashes when they occur? I realise that this is a more of a hacker-oriented tool, but you're reaching wider audiences with the adverts, etc, I personally don't want to run it in dev mode 24/7 just to get info on the crashes :)

(unless there's another way of getting info on past crashes?)

**Comment by 50Wliu** [comment]
@dankcushions if you're on Mac, opening Console.app should show you the stacktrace for crashes.

**Comment by batjko** [comment]
So what's the OS you're running on, and is there perhaps any pattern you can pinpoint as to what caused the crash?

Does the crash message you mention come from atom or the OS?

**Comment by dankcushions** [comment]
it's windows 7, and the error is within atom (if it was in windows I would get and error message!)

It's not really about the issue itself, more about the lack of useful error feedback.

**Comment by batjko** [comment]
Yea I was hoping you could add a screenshot of the error you do get, just as a reference.

Whether or not more information about a crash can be provided will depend on how that crash happens and what facilities Electron offers for that kind of thing, but I don't see any fundamental barriers from Atom's perspective.

**Comment by budnik** [comment]
I have following crash in few seconds after start caused by some package, it won't happen with `--safe` but I don't know how to debug or prevent this issue. That message should provide some guidelines for poor user
![selection_12 2912 2912 29](https://cloud.githubusercontent.com/assets/1160699/9655158/df627b90-5237-11e5-8805-b8db44004b59.png)
