### ISSUE TITLE
Unable to create unix-compatible shell script

### ISSUE THREAD

**Issue by IgorGanapolsky** [atom/atom#8118]
I am trying to create this shell script for Circle-ci integration:
```bash
#!/bin/bash

# Fix the CircleCI path
function getAndroidSDK(){
  export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$PATH"

  DEPS="$ANDROID_HOME/installed-dependencies"

  if [ ! -e $DEPS ]; then
    cp -r /usr/local/android-sdk-linux $ANDROID_HOME &&
    echo y | android update sdk -u -a -t android-22 &&
    echo y | android update sdk -u -a -t platform-tools &&
    echo y | android update sdk -u -a -t build-tools-22.0.1 &&
    echo y | android update sdk -u -a -t extra-android-m2repository &&
    echo y | android update sdk -u -a -t extra-google-m2repository &&
    echo y | android update sdk -u -a -t sys-img-x86-android-22 &&
    echo y | android update sdk -u -a -t sys-img-armeabi-v7a-addon-google_apis-google-22 &&
    echo y | android update sdk -u -a -t addon-google_apis-google-22 &&
    echo no | android create avd -n testAVD -f -t android-22 --abi default/x86 && touch $DEPS
  fi
}

# Wait for emulator to start
function waitAVD() {
    local bootanim=""
    export PATH=$(dirname $(dirname $(which android)))/platform-tools:$PATH
    until [[ "$bootanim" =~ "stopped" ]]; do
      sleep 5
      bootanim=$(adb -e shell getprop init.svc.bootanim 2>&1)
      echo "emulator status=$bootanim"
    done
}
```

However, Circle-ci keeps complaining of the following
> scripts/environmentSetup.sh: line 2: $'\r': command not found
scripts/environmentSetup.sh: line 4: syntax error near unexpected token `$'{\r''
(source scripts/environmentSetup.sh && getAndroidSDK) returned exit code 1
' Action failed: (source scripts/environmentSetup.sh && getAndroidSDK)
Why isn't your editor capable of creating a normal shell script????

Thanks,
Igor

**Comment by mnquintana** [comment]
Thanks for the report! To help you debug this we're going to need [some more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues). What OS are you using? What version of Atom?

**Comment by maxbrunsfeld** [comment]
I don't get what this has to do with Atom. Did you mean to post this on another repo?

**Comment by IgorGanapolsky** [comment]
@maxbrunsfeld I created this script in Atom!!!

**Comment by IgorGanapolsky** [comment]
@mnquintana I am on Windows 10 64bit.  Atom 1.0.2.

**Comment by maxbrunsfeld** [comment]
Oh, I see. It sounds like you want an option to use unix-style line-endings while on windows. We're actually working on this right now. Please subscribe to this issue: https://github.com/atom/atom/issues/2822.
