### ISSUE TITLE
Not Issue, It's about 'marker-clusterer'.

### ISSUE THREAD

**Issue by JayLim82** [atom/atom#8129]
Your work is great. And I have to say Thank you.
By the way, I can't find detail information about the marker-clusterer tag.

http://bundlr.com/clips/53f43e6975a6d20b2e00005c

I read your post, but I can't find how to use marker-cluster tag. what is 'markersData'?? How can I use it with my ng-repeat markers??

And say again, Thank for your work!

**Comment by batjko** [comment]
Is this actually to do with Atom? Or perhaps with one package that uses marker clusterer?

**Comment by JayLim82** [comment]
Sorry!!!! I clicked wrong area!!
