### ISSUE TITLE
Inserting <text-editor-view> tag doesn't observed by Workspace::observeTextEditors

### ISSUE THREAD

**Issue by MaximSokolov** [atom/atom#8132]
Seems like <text-editor-view> tag should be registered as pane item.

EDIT: Nevermind, `Workspace::observeTextEditors` is not supposed to observe it

**Comment by thomasjo** [comment]
Sorry, but you're going to have to provide more context. What are you trying to do? What was your expectation, and how did the actual outcome deviate from it?

**Comment by MaximSokolov** [comment]
I want to use textEditor in panel with all plugins enabled(vim, linter...). Now i use a hidden pane for containing textEditors items and panel for for displaying them. I understand that it's a special case of using <text-editor-view> tag, but possibility to register tag as pane item directly would be useful.
