### ISSUE TITLE
"Search in Directory" should be in a fixed order in the menu

### ISSUE THREAD

**Issue by gam-phon** [atom/atom#8134]
When clicking on the project "Search in Directory" will be on the bottom above the last one.
![screen shot 2015-07-29 at 12 06 31](https://cloud.githubusercontent.com/assets/1763722/8953879/5899c3ca-35ea-11e5-9855-418afc92a716.png)

When clicking on any folder inside the project "Search in Directory" will be the first one in order.
![screen shot 2015-07-29 at 12 06 45](https://cloud.githubusercontent.com/assets/1763722/8953886/5c72ce88-35ea-11e5-9de2-8e3ce436ce80.png)

This confuse me a lot. I do search a lot and I got confused when I want to search some time it is above and other times is down. I think it would be better to be in a fixed place.

**Comment by mnquintana** [comment]
Would you mind moving this to https://github.com/atom/find-and-replace? Thanks!

(See https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290?u=mnquintana for more information)

**Comment by gam-phon** [comment]
Done. Thanks
