### ISSUE TITLE
Linux Mint freezes when using Atom

### ISSUE THREAD

**Issue by aldelval** [atom/atom#8138]
Somewhat randomly, but annoyingly frequently, my Linux Mint/Cinnamon installation crashes, and I think the issue may well be related to atom. 

**Symptoms**: The whole windows manager freezes and blacks out, except for the mouse, and I may or may not be able to restart with Ctrl+Alt+Backspace or by opening a tty with Ctr+Alt+F1 and killing cinnammon. 

The last line of /var/sys/log always looks like this immediately after the crash:
Jul 29 15:50:40 ulises-ubuntu acpid: client 9595[0:0] has disconnected

but in addition .xsession-errors seems to point out to Atom (see below)

It often, but not always, happens while swtiching apps with Alt+Tab.

**System data:**
Linux Mint 17.1 32 bit
![captura de pantalla de 2015-07-29 16 50 52](https://cloud.githubusercontent.com/assets/4282554/8960849/3b4e39a4-3612-11e5-971f-c0173ac1032f.png)

Atom version (according to Synaptic): 1.0.0-1~webupd8~0
Or from the terminal:

~ $ atom --version
1.0.0 
~ $ cinnamon --version
Cinnamon 2.4.8
~ $ uname -a
Linux ulises-ubuntu 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:30:01 UTC 2014 i686 i686 i686 GNU/Linux

**Why I think it may be caused by atom:**

The last few lines of .xsession-errors right after the crash are always like the last lines in the following log excerpt (where I include the log from the start of the session in case something else may be relevant)

/etc/mdm/Xsession: Beginning session setup...
localuser:alvaro being added to access control list
Script para ibus iniciada en run_im.
Script para auto iniciada en run_im.
Script para default iniciada en run_im.
Failed to connect to the VirtualBox kernel service
Failed to connect to the VirtualBox kernel service
Failed to connect to the VirtualBox kernel service
Failed to connect to the VirtualBox kernel service
Failed to connect to the VirtualBox kernel service
Script para ibus iniciada en run_im.
Script para auto iniciada en run_im.
Script para default iniciada en run_im.
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-WrPb0S
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-WrPb0S
GPG_AGENT_INFO=/run/user/1000/keyring-WrPb0S/gpg:0:1
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-WrPb0S
GPG_AGENT_INFO=/run/user/1000/keyring-WrPb0S/gpg:0:1
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-WrPb0S
GPG_AGENT_INFO=/run/user/1000/keyring-WrPb0S/gpg:0:1
SSH_AUTH_SOCK=/run/user/1000/keyring-WrPb0S/ssh
Initializing nemo-dropbox 2.4.0
Starting Dropbox...Cjs-Message: JS LOG: About to start Cinnamon
nm-applet-Message: using fallback from indicator to GtkStatusIcon

*\* (nemo:2469): WARNING **: Can not determine workarea, guessing at layout
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-in".
Window manager warning: Trying to remove non-existent custom keybinding "magnifier-zoom-out".
Cjs-Message: JS LOG: Cinnamon started at Wed Jul 29 2015 15:54:41 GMT+0200 (CEST)
Dropbox isn't running!
Done!
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
Cjs-Message: JS LOG: network applet: Found connection for active
mintUpdate: proceso no encontrado

(mintUpdate.py:2608): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:2608): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:2608): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(mintUpdate.py:2608): libglade-WARNING **: unknown attribute `swapped' for <signal>.

**Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2c00001 (Nueva pest)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3800001 (Atom)
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x3800001 (Atom)**

(gnome-terminal:4253): GLib-GIO-CRITICAL **: g_settings_get: the format string may not contain '&' (key 'monospace-font-name' from schema 'org.gnome.desktop.interface'). This call will probably stop working with a future version of glib.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1c00003 (Autenticar)
Terminated

**Comment by mnquintana** [comment]
You're using an old version of Atom - can you try updating to the latest version (1.0.3) first and see if you can reproduce this issue?

**Comment by aldelval** [comment]
My version is up to date according to synaptic (i.e. standard repositories do not provide anything more recent), and I don't see any debian packages for 32 bit in https://github.com/atom/atom/releases,

Not sure installling from source is worth the trouble for this... I'd rather not if possible. Is there any alternative?

(Go figure, I just realised my -oldish- computer is 64 bit capable, but the fact is the installed Mint distro is 32bit)

Thanks for any help-

**Comment by 50Wliu** [comment]
The webupd8 repo usually lags behind the 'true' Atom version by around a week, but a month seems a bit drastic.  That being said, it doesn't *look* like any changes in 1.0.0-->1.0.3 would solve this issue, but who knows :).

**Comment by kenden** [comment]
This  ticket: https://github.com/atom/atom/issues/6557
said this solution worked for them: https://github.com/atom/atom/issues/8708#issuecomment-139183263

**Comment by darkmorpher** [comment]
@aldelval Is this still reproducible?

CC @mnquintana to close

**Comment by aldelval** [comment]
It still happens on occasion, but rarely. It was never reproducible, it
just happened some times. But I guess you can close the thread.

2016-05-05 23:34 GMT+02:00 Hei Liebrecht <notifications@github.com>:

> @aldelval <https://github.com/aldelval> Is this still reproducible?
>
> CC @mnquintana <https://github.com/mnquintana> to close
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/8138#issuecomment-217286486>
>



-- 
Alvaro del Val
Profesor de Universidad
Departamento de Ingeniería Informática
Universidad Autónoma de Madrid

**Comment by kenden** [comment]
After updating Atom to the last version, no more freezes with Atom.

**Comment by Siecje** [comment]
I just installed Linux Mint 18 (Cinnamon) using VirtualBox version 5.1.2 with 3D Acceleration enabled.

Fresh install and I downloaded the .deb from http://atom.io 

When I launch atom the window is always on top and black.

If I close it everything locks up.

**Comment by 50Wliu** [comment]
@Siecje there's a bug in VirtualBox right now regarding 3D Acceleration.  Try disabling it and see if that helps.

**Comment by Siecje** [comment]
@50Wliu Yeah atom works without 3D Acceleration.
