### ISSUE TITLE
On screen keyboard opens when hardware keyboard is present

### ISSUE THREAD

**Issue by wlesieutre** [atom/atom#8143]
Tapping a text area to move focus in Atom opens the OSK, even with a hardware keyboard connected.

This looks related to a longstanding issue in Chromium (which now works correctly, tested in Chrome v44): https://code.google.com/p/chromium/issues/detail?id=335735

What has to happen for the fix to make its way to Atom? It's a bit maddening to run on a Surface as-is.

**Comment by wlesieutre** [comment]
Proposed labels bug / windows / UI, only contributors can set them?

**Comment by TimeForAChange** [comment]
This is a "me too" comment. Windows 10, on screen keyboard completely disabled in the settings and it never shows up anywhere else. I even verified the registry key somewhere under HKLM is 0 and not 1.

I installed the touch-event package which took care of removing the on screen keyboard popping up when I merely touch the screen to edit the file. Here are two ways for me to reliably get it to popup again:

1) Cursor in a JS file I'm editing I press CTRL-R (calls package symbols-view), which pops up a search box. When I then touch-click the editor window to close the search box and get back to the file the OSK pops up.

2) I'm in the settings, "Packages". I go to a package's settings. To get back to the packages view I use breadcrumb navigation at the top: I touch-click on "Packages", I get back to the packages page - and the OSK pops up.

**Comment by lee-dohm** [comment]
> What has to happen for the fix to make its way to Atom?

To answer this question, Chrome v44+ has to be integrated into [Electron](https://electron.atom.io) and then that version of Electron has to be integrated into Atom. There is currently a [PR to integrate a relatively recent version of Electron into Atom](https://github.com/atom/atom/pull/7877) but even that is only Chrome v43.

**Comment by damieng** [comment]
Atom is now on Chrome 49 and this fix should have been in Atom for a while. Please open a new issue if you see this problem again. Thanks.
