### ISSUE TITLE
Not sure 1.0.3 correctly upgraded in-place

### ISSUE THREAD

**Issue by ebsen** [atom/atom#8145]
I'm on a Mac. If I open About Atom or run `atom --version`, it says **1.0.3**. If I open the Release Notes section (from the Help menu), it says **1.0.2** with the normal button to "Restart and update."

Trouble is, if I click that, Atom will never relaunch. When I next launch it manually (in regular, dev or safe mode), I'm back to the scenario above.

It seems Atom is confused. How can I help it?

**Comment by kevinsawicki** [comment]
What version does it say in the Atom menu?

**Comment by ebsen** [comment]
Version 1.0.3.

Today when I launched Atom, the About info appears in a window tab like Settings and Release Notes does. When I opened this ticket yesterday, it appeared in the little pop-up box that it always had been until now. 

All these panes report the version numbers as they did yesterday and I get the same behavior (Atom never relaunches) when clicking “Restart and update.” 

– Erik

**Comment by ebsen** [comment]
Perhaps the issue isn't an improperly auto-installed update but with the Release Notes pane. Are the only place that doesn't show the newest version.

**Comment by thomasjo** [comment]
@ebsen It's possible that something might have gone "wrong" with respect to the release notes. The previous version info is persisted in Local Storage. I haven't got a "normal" install of Atom to verify with right now, but I believe you might be able to fix your predicament by executing this
``` js
localStorage.removeItem("release-notes:previousVersion")
```
from the *Developer Console*. Restart Atom afterwards, and hopefully the problem is gone.

**Comment by ebsen** [comment]
You might be on the right track. Local Storage gives me 
	`release-notes: previousVersion: ”1.0.3”`
	`release-notes:version: ”1.0.2”`
Calling `removeItem` on them and restarting doesn’t change the values, however.

– Erik

**Comment by thomasjo** [comment]
Hmm, even if you're unable to remove it maybe you can do this?
```js
localStorage.setItem("release-notes:version", "1.0.3")
```

**Comment by ebsen** [comment]
Calling `setItem` on the two seems to have corrected the Release Notes pane.

Thanks for pointing this out. I haven't messed with Local Storage at all and I had no idea Atom did things like this.

**Comment by thomasjo** [comment]
:+1: Great news! Glad we managed to resolve your problem.
