### ISSUE TITLE
Working on atom internals -> Building

### ISSUE THREAD

**Issue by saschagehlich** [atom/atom#8155]
I started working on a feature in atom's core yesterday and I was wondering what your workflow is. Running `scripts/build` after making a change is very slow - is there some kind of grunt watcher task that automatically recompiles the coffee and lets you reload the editor?

If you tell me how it works, I can make a PR modifying the docs for better understanding of the workflow

**Comment by mnquintana** [comment]
Take a look at https://discuss.atom.io/t/atom-core-development-workflow/15584/4?u=mnquintana

**Comment by lpommers** [comment]
When I'm playing around with things in the core, I run the `build` task. I tend to build it to a separate directory. I have a stable atom window open (the one where I'm actively making changes on a new branch). 

Then I `cd` into the directory where I built atom and start it in `atom --dev` mode. 

I just keep editing the files I'm working on in the stable window I have open and I open the dev tools in the other window and `cmd-r` or refresh the window every time i want to see new changes.

----

When it comes to specs I write my tests and I write them using `fdescribe`  or `fit` so I only run my new tests when developing.  To run the tests I run `apm test` (in the directory where i've made changes- not the directory where I had atom built to).

Before committing I remove the `f` so it's just `describe` or `fit`
