### ISSUE TITLE
Tab inconsistent between Linux and Windows.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#8156]
Today I was on Windows 10 debugging an issue with Jekyll and opened a file (that is not related) and noticed that when I opened that tab delimited file the alignment was off because on Linux Atom editor defaults to 8 space tabs but on Windows Atom editor defaults to 2 space tabs, this results in a massive misalignment of sources that use tabs between the two operating systems.

**Comment by thomasjo** [comment]
There are no platform differences when it comes to indentation settings. Are you sure both environments have *identical* packages installed as well as *identical* configuration? Indentation settings are overridden by both configuration and language packages.

**Comment by envygeeks** [comment]
That takes the assumption that Atom has a setting to adjust both independently but to answer your question: both are set to 2 space tabbing, but when `\t` is in a file one has 8 space tabbing (Linux) the other has 2 space tabbing (Windows,) both do not use any addons that would alter this behavior.  To me this seems like a platform difference that is not normalized.

**Comment by thomasjo** [comment]
As I mentioned, there is no platform-specific handling of indentation. Neither insertion nor rendering.
Are you able to reproduce this with the same file on both platforms when running in safe mode? `atom --safe`

**Comment by envygeeks** [comment]
> As I mentioned, there is no platform-specific handling of indentation

I didn't refute your assertion... so why do you keep repeating it as if I'm ignorant? I asserted an agreement with an assessment that it should be handled and normalized.  I already stated there are no -addons that alter the tabbing so `atom --safe` is just a redundancy, I personally audit every addon we use on our systems because Atom has no control over the things people do (like inserting analytics and tracking our behavior) so I know exactly what every plugin does.

**Comment by thomasjo** [comment]
Let's go back to your original issue;

> [..] because on Linux Atom editor defaults to 8 space tabs but on Windows Atom editor defaults to 2 space tabs [..]

This assumption is **not** correct. Hence my reason for asking you about packages, and configuration, because whatever is causing the difference in indentation in your two environments is not originating from Atom.

**Comment by envygeeks** [comment]
What? That assumption is not correct? I fucking experienced that behavior exactly like that.

**Comment by envygeeks** [comment]
I'm closing this ticket, I don't have time for this bullshit.

**Comment by benogle** [comment]
@envygeeks What do the config.cson files look like on both systems?

**Comment by joefitzgerald** [comment]
@envygeeks I'm sorry you are having a bad experience with tab / indentation behavior. I think @thomasjo was genuinely trying to help. Please remember that there are volunteers here working on many of these issues, expending their free time in service of you. Please review http://todogroup.org/opencodeofconduct/#Atom/opensource@github.com.

Regarding:
> [..] because on Linux Atom editor defaults to 8 space tabs but on Windows Atom editor defaults to 2 space tabs [..]
> *@envygeeks*

And:
> This assumption is not correct.
> *@thomasjo*

@thomasjo is trying to articulate that Atom does not have a default to 8 space tabs on Linux. The default is always 2: https://github.com/atom/atom/blob/1d9ecc1d597983c0ac88b3c7f9df1bde3f798c3e/src/config-schema.coffee#L135-L138

That said, there can be a different default tab length set on a grammar-by-grammar basis. That could explain some variation if you are opening different files on each platform. Another cause of variation could be that your `config.cson` has a value set for editor.tabLength on one of your platforms but not the other:

`config.cson:`
```cson
"*":
  editor:
    tabLength: 8
```

**Comment by envygeeks** [comment]
@benogle @joefitzgerald it could be the latter part, I will get on my main Linux machine tonight and see if there is a dangling configuration option from the past in there that sets it.  I think I remember in the past there being an option to set both independently back in the way-way-back but I think I also remember refreshing my entire configuration for the Atom 1.0 so I honestly don't know but I will compare the two tonight and post the diff and do a fresh install test (since it's high time I clean out my Atom folder anyways, it's got stuff in there from when Atom first went public.)

**Comment by envygeeks** [comment]
I guess dangling was the wrong word, "different" is better.

**Comment by thomasjo** [comment]
In addition it might be worth checking `init.coffee`. Some of us used that in the early days to handle indentation settings based on file types, platform, etc. Easy to forget about that file, at least that's my personal experience.

**Comment by envygeeks** [comment]
@thomasjo good idea, I shall check there too

**Comment by envygeeks** [comment]
It was an old Atom configuration option from the way-way back.

**Comment by thomasjo** [comment]
Glad you solved it :thumbsup:
