### ISSUE TITLE
Atom makes numerous requests on start / offers no way to disable

### ISSUE THREAD

**Issue by bnvk** [atom/atom#8157]
Upon running Atom (on Mac OS 10.9+), I have noticed it wants to connect to the following URLs:

- atom.io on TCP port 443 (https)
- 2001:4860:4860::8888 on UDP port 53 (domain) and (Reverse DNS: google-public-dns-a.google.com)
- s3-1.amazonaws.com on port 443 (https)
- maps.gstatic.com on port 443 (https)
- www-google-analytics.l.google.com on TCP port 443 (https) and (193.229.108.55)

I assumed the first couple were to just check if there were any updates, but the calls to Google have me stumped as to why my local app needs to ping Google. I searched the codebase and didn't find any mention of these URLs.

Perhaps you can explain these requests (or already have somewhere). Additionally, It seems that offering users a way to opt-out / disable these requests would be desirable, especially for the more privacy conscious users.

**Comment by thomasjo** [comment]
First three are related to Atom's auto-update mechanism and package updating. The last two are related to the [metrics package](https://atom.io/packages/metrics). See https://github.com/atom/atom/issues/4966 for more details.
