### ISSUE TITLE
Atom Process does not close after workspace::scan completes

### ISSUE THREAD

**Issue by benjaminRomano** [atom/atom#8166]
On windows 10, when calling the atom.workspace.scan function, a process is created and doesn't terminate even after it is finished finding matches.

This can be tested by running this line: 
atom.workspace.scan(/(a)+/, function(result){})

**Comment by benogle** [comment]
This is actually legit, and was fixed in https://github.com/atom/atom/pull/8126 It should be out in atom 1.0.4

**Comment by benjaminRomano** [comment]
Oh so it was actually a bug... Thanks for fixing it!
