### ISSUE TITLE
`Reload Atom And Recheck Packages` locks up atom

### ISSUE THREAD

**Issue by despairblue** [atom/atom#8176]
Pressing `Reload Atom And Recheck Packages` in `Incompatible Packages View` atom goes so far:

![screenshot from 2015-07-31 22-48-00](https://cloud.githubusercontent.com/assets/927609/9017299/58d989b8-37d6-11e5-8c08-851679c0378a.png)

and then just hogs cpu until the it can only be killed

![screenshot from 2015-07-31 22-48-36](https://cloud.githubusercontent.com/assets/927609/9017300/5f84dab0-37d6-11e5-8293-e72f5563d496.png)

## Command History

```
     -3:52.8 ready (#document)
     -3:40.6 incompatible-packages:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-dark-ui)
     -0:01.8 command-palette:toggle (div.tool-panel.panel-bottom.padded.incompatible-packages.native-key-bindings)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 bug-report:open (div.tool-panel.panel-bottom.padded.incompatible-packages.native-key-bindings)
```

## Versions

* **Atom:**       1.0.3
* **Atom-Shell:** 0.22.3
* **OS:**         linux 3.14.48-1-lts
* **Misc**
    * apm  1.0.1
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.10
    * git 2.4.6

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/incompatible-packages? Thanks!

**Comment by despairblue** [comment]
sure, will do
