### ISSUE TITLE
Option for zero-indexed line numbers

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8180]
I've always wanted zero-indexed line numbers. That's what I'm used to: other than nutty environments like Excel/AppleScript/Matlab/etc, arrays are always zero-indexed. But perplexingly no programmer's editor supports them. Zero-indexed line numbers make counting lines, sets of lines, and newline characters easier, since the line number is literally the index of the line. The correspondence is so well suited that pointer/index arithmetic carries over seamlessly. And this would be exceptionally easy to implement in the core.

**Comment by bronson** [comment]
Well, that's an idea.  If it's so easy, definitely file a PR.  But don't forget about goto-line etc.  I suspect the 1-based indexing ripples through the codebase pretty far... there's only one way to find out!

**Comment by mark-hahn** [comment]
If I remember correctly, everything internally is zero-based and the
increment only happens at the last second when the number is put in the dom
for display.  So one place would fix it.  You would probably have to hook
the internal code, but be brave.  I've done it many times.

**Comment by lee-dohm** [comment]
@mark-hahn is correct. The positions in both buffer and screen coordinates are stored zero-indexed:

<img width="506" alt="screen shot 2015-07-31 at 11 08 12 pm" src="https://cloud.githubusercontent.com/assets/1038121/9020842/1cd08900-37d9-11e5-88fa-72be0a69f167.png">

But yes, there are lots of places where the coordinates are probably translated. There's the line numbers in the gutter, the cursor location widget in the status bar, the goto-line command that @bronson mentioned, etc.

**Comment by mark-hahn** [comment]
I just realized that the chrome dev tools and many other tools like
compiler output will all be wrong.  I think this is a non-starter.

**Comment by alexchandel** [comment]
> the line numbers in the gutter, the cursor location widget in the status bar, the goto-line command

I think I've figured out where to make the changes, except the goto-line command.

@mark-hahn Chrome dev tools are fine. But what do you mean by compiler output? Someone who uses this option this will know that non-Atom programs aren't affected. And for packages that run compilers and modify lines, they're probably already getting/setting the internal 0-indexed line numbers, right? So they wouldn't even notice.

**Comment by lee-dohm** [comment]
This isn't something that we want to maintain, mostly for the reasons that @mark-hahn outlined above. Thanks for the suggestion!
