### ISSUE TITLE
Workaround for #4893

### ISSUE THREAD

**Issue by wmhilton** [atom/atom#8183]
I made a workaround using AutoHotKey.

atom.ahk:
```
Run, %LocalAppData%\atom\bin\atom.cmd %1% %2% %3% %4% %5% %6% %7% %8% %9% %10%,,Hide
```

Then using Ahk2Exe for AutoHotkey:
![screenshot_11](https://cloud.githubusercontent.com/assets/587740/9019989/5b830114-37c5-11e5-8178-1baa4930278b.png)

Now when I set filetypes to "Open With..."
![screenshot_14](https://cloud.githubusercontent.com/assets/587740/9020007/efe9015a-37c5-11e5-99ba-314a2c8d6cbb.png)

They have this nice icon:
![image](https://cloud.githubusercontent.com/assets/587740/9020021/76752ea6-37c6-11e5-9fa9-2d7b2289fc6f.png)

**Comment by mnquintana** [comment]
Would you mind posting this as a comment in #4893? (I just unlocked the issue so you can add this.) Thanks!
