### ISSUE TITLE
Command prompt has bad search results

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8185]
The command prompt has mediocre-to-bad search results. Searching `install` yields `Select All`, `Install Update`, `Uninstall Themes`, etc. The logical choice, `Install Packages And Themes`, is choice #7. But it's worse. Even typing `install packages` still leaves `uninstall packages` two results higher than `Install Packages And Themes`! Even `View Installed Packages` is ranked higher than it. This should not be.

**Comment by izuzak** [comment]
Thanks for the feedback -- this should be reported on the [issue tracker for that package](https://github.com/atom/command-palette/issues). Actually, I think there's already an issue there that's very similar to what you reported here: https://github.com/atom/command-palette/issues/28. I'm going to close this in favor of that one, and please feel free to leave a comment there.
