### ISSUE TITLE
Bracket highlighting incorrect

### ISSUE THREAD

**Issue by JulianLeviston** [atom/atom#8192]
Where there are multiple parens, currently, paren matching at the end-paren (ie close parens) highlights the paren to the right, but it should be the paren to the left.

So, say I have this:
(((:after-clone-fn val)X))

...and my cursor is at the X position, then the paren that *should* be matched is the one to the left. The one that *is* matched, tho, is the one to the right.

This doesn't seem correct behaviour to me. (FWIW, I'm editing clojure code at the moment).

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/bracket-matcher? Thanks!

(Also see https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues)

**Comment by izuzak** [comment]
Note: I think this is a duplicate of https://github.com/atom/bracket-matcher/issues/116, so check that one before opening a new issue, @JulianLeviston.

**Comment by JulianLeviston** [comment]
Apologies all, and thanks.
