### ISSUE TITLE
Atom --safe does not work

### ISSUE THREAD

**Issue by Mrnumbers9** [atom/atom#8194]
I installed a extension that put atom into a infinite reload loop. (But that is not this issue) So I ran atom --safe. It just started atom **with** all extensions, even ones I had disabled.

**Comment by izuzak** [comment]
@Mrnumbers9 I'm having trouble reproducing this. Can you share a link to your plugin and provide the _exact_ steps which reproduce the problem for you, along with [other useful information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8194#issuecomment-132321631. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
