### ISSUE TITLE
The scroll bar doesn't respond sometimes in zip files

### ISSUE THREAD

**Issue by wafflespeanut** [atom/atom#8195]
I'm very happy that Atom actually supports viewing zip files (among many other things). But, there's some trouble while scrolling a pane. Here's a (~7 MB) GIF demonstrating what I did:

![GIF](https://cloud.githubusercontent.com/assets/6691262/9026385/ec12a0aa-394a-11e5-83f4-f8e492736e5b.gif)
- I can click and drag the scroll bar from the start of the zip file (I can also use my mouse wheel).
- But, I can't click & drag the scroll bar when it's somewhere in the middle. When I do that, the scroll bar simply goes upwards! (as you can see)

**Note:** This works only while viewing zip files. Other files work just fine...

**OS**: Ubuntu 14.04 (x64)
**Atom version:** 1.0.0

<sup>**Sidenote:** I use Atom almost everyday and it's really helpful as a text editor. Thanks for making it possible! :)</sup>

**Comment by izuzak** [comment]
Thanks for the report, @Wafflespeanut -- I'm also seeing funky scrollbar behavior. Here's what I did:

1. Downloaded the zip archive for Atom's source from https://github.com/atom/atom
2. Started Atom
3. Open file > atom-master.zip
4. Tried scrolling with the scrollbar up and down by dragging the scrollbar and clicking on it.

The behavior was strange, very similar to what @Wafflespeanut recorded in the GIF. I'm not really sure why that's so. Wondering if @simurai has any ideas?

**Comment by simurai** [comment]
I'm not able to reproduce it on OS X when enabling (permanent scrollbars). From the gif it looks like that after letting go of the scrollbar, somehow the scroll position is wrong and then it jumps into the right position?

Or maybe that once you let go, it adds more rows/content and that makes it jump?

**Comment by izuzak** [comment]
@simurai that's so strange -- I can still reproduce this on latest master of Atom.

> Or maybe that once you let go, it adds more rows/content and that makes it jump?

No new content is added as far as I can tell -- the scrollbar just acts completely strange and moves almost randomly.

![strangeeeee](https://cloud.githubusercontent.com/assets/38924/9686597/091ba608-5325-11e5-80c4-5621adaf6cd4.gif)
