### ISSUE TITLE
Takes all resources - other programs stop working

### ISSUE THREAD

**Issue by jaulz** [atom/atom#8196]
After upgrading to the latest version (1.0.3) I frequently face the issue that Atom takes all the resources (new MacBook Pro; Chrome with a lot of tabs open and XCode) and other programs suddenly stop working:
-Node.js: error with code EAGAIN
-No new terminal: bash: fork: Resource temporarily unavailable
-Chrome: no new tab

As soon as I close Atom everything runs smoothly again. Also I already tried to increase the ```ulimit -n``` but nothing helped so far. Has someone else also experienced these issues? Is it Atom itself or maybe a system setting? 

P.S: just in this second Atom also stopped working and the error report says the following (creating this issue from within Atom is also not possible as Atom does not react to this click):
```
/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120
Hide Stack Trace
TypeError: undefined is not a function
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120:27)
  at Task.module.exports.Task.start (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:111:12)
  at Function.module.exports.Task.once (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:23:18)
  at GitRepository.module.exports.GitRepository.refreshStatus (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:398:37)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:77:26
```

**Comment by izuzak** [comment]
Thanks for the report, @jaulz. Do you see the same behavior in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? If so, do you see the same behavior for every project you open in Atom, or only some projects? Is one of the projects you can reproduce this with a public project you can link to so that we can try and reproduce? Do you see the same problem in Atom 1.0.5?

**Comment by jaulz** [comment]
Thanks for the hint! It seems that git-plus is taking all the resources i.e. file handler. I will look for a solution in their repository. Thanks a lot :-)
