### ISSUE TITLE
Text not rendering in menus on HiDPI displays

### ISSUE THREAD

**Issue by ThomasJClark** [atom/atom#8198]
Fedora 22 + Atom 1.0.3.  When I right click anywhere in the application, the context menu has no text in it.  Nothing relevant is printed in the dev console or ~/.atom/nohup.out.

![atom](https://cloud.githubusercontent.com/assets/3964980/9028075/b84a136c-393a-11e5-9dee-468fa95ba454.png)

**Comment by mnquintana** [comment]
Are you using a HiDPI display by any chance? How do application menus render?

**Comment by ThomasJClark** [comment]
Yes, this is a HiDPI display.  In the screenshot, I have  [mcanders/atom-hidpi](https://github.com/mcanders/atom-hidpi)  enabled, but this issue still occurs with only the default  packages.

The application menus look the same as the context menu.

**Comment by mnquintana** [comment]
Thanks for the update! In that case, this is a duplicate of https://github.com/atom/atom/issues/3826 and will be fixed by https://github.com/atom/atom/pull/7877.

**Comment by ThomasJClark** [comment]
It's nice to see that Atom is improving HiDPI support, but that issue is unrelated to mine.  To test it, I just checked out  #7877 and got the same appearance, with the additional issue that the context menu is in the wrong place.

![atom](https://cloud.githubusercontent.com/assets/3964980/9028365/51d9e940-3944-11e5-87ef-7553b2b4f0b4.png)

**Comment by thomasjo** [comment]
What window manager/desktop environment are you using?

**Comment by ThomasJClark** [comment]
GNOME Shell 3.16.3

**Comment by ThomasJClark** [comment]
Also, my work laptop, which also has Fedora 22 + Atom 1.0.3 + Gnome Shell 3.16.3 but a regular 1080p display does not have this problem.

**Comment by ThomasJClark** [comment]
I just switched my system font from Fira Sans Regular to Roboto Regular and the problem went away.  Does Atom maybe have a problem reading certain fonts?

**Comment by niedzielski** [comment]
This might be related to https://github.com/atom/electron/issues/2523.
