### ISSUE TITLE
Added projects aren't restored unless File -> Exit

### ISSUE THREAD

**Issue by csholmq** [atom/atom#8200]
When _File -> Add Project Folder_ successfully adds a project, closing the window (Via cross or Alt + F4)it  means that the next time Atom is opened, the added project isn't present in Tree View.

However, shutting down Atom via _File -> Exit_ successfully restores all added projects once Atom is reopened.

I thought adding a project folder should be considered a "permanent bookmark" and not be part of the session handling for open windows/tabs.

This is on Windows 7.

**Comment by csholmq** [comment]
I realise now that _atom-project-manager_ does exactly this. I expected the _Add Project Folder_ to behave in the same way. Not sure what the purpose is otherwise.

**Comment by izuzak** [comment]
@csholmq Which version of Atom are you using?

@maxbrunsfeld this issue sounds familiar, I think we've seen it before and that it was fixed. :older_man:

**Comment by csholmq** [comment]
1.0.4 at the time of creating this ticket.

**Comment by axefrog** [comment]
This is an issue for me too. I'm on Atom 1.1.0 on Windows 10. If I exit using File -> Exit, then the session is restored on next open. If I exit using the application's close button, then the session is not restored. Specifically, the project folders are still there, but none of the files or panes are restored. I just get my project tree on the left and an empty environment with no tabs open and only the one default pane.

**Comment by csholmq** [comment]
This seems to be resolved for me on 1.1.0.

**Comment by damieng** [comment]
Confirmed fixed here too.
