### ISSUE TITLE
Opening 20 MB TSV causes Atom to hang and increase memory consumption until it crashes

### ISSUE THREAD

**Issue by wrummler** [atom/atom#8201]
On Windows 7 Pro 64-bit, using Atom 1.0.3 in safe mode to open a 20 MB TSV-formatted file (2.5 MB compressed version [here](https://www.dropbox.com/s/x6ect89470hb86n/gwlevels%20%283%29.gz?dl=0)) causes Atom to hang and its memory usage to grow from about 150 MB to about 1.5 GB in about 20 seconds. Atom offers to close or keep waiting a few seconds or so after that. If I choose to keep waiting, memory usage will grow more slowly for about 3 or 4 more minutes until Atom reports that it has crashed (and that the issue should be reported here).

**Comment by izuzak** [comment]
Thanks for the report, @wrummler. Yeah, I'm also seeing the hang behavior and Keep Waiting popups on OSX and Atom 1.0.6-1c88b2d (it's been more than 10 minutes now). However, I'm not seeing the crash.

cc @nathansobo
