### ISSUE TITLE
Extract `GitRepository` into its own npm package.

### ISSUE THREAD

**Issue by bolinfest** [atom/atom#8207]
This is necessary to fix https://github.com/facebook/nuclide/issues/158.

From a cursory look through https://github.com/atom/atom/blob/master/src/git-repository.coffee, the dependencies appear to be the following "ordinary" npm packages:

```
event-kit
fs-plus
git-utils
grim
underscore-plus
```

and also:

```
repository-status-handler.coffee
task.coffee
```

There are also some Atom-specific calls to `atom.config.get` and `atom.confirm`.

We would probably also want to extract https://github.com/atom/atom/blob/master/src/git-repository-provider.coffee, but that would be trivial.

Would GitHub be open to such a refactoring?

**Comment by thomasjo** [comment]
I don't speak for GitHub, but I'm :ok_hand: with this.
