### ISSUE TITLE
Sidebar folder misalignment

### ISSUE THREAD

**Issue by okonomiyaki3000** [atom/atom#8209]
If a folder in the sidebar is named with a file extension (e.g. :file_folder: less.js) the positioning of the folder icon will be slightly left of other folders that are not named in this way. I thought this must be a problem with the ui theme I was using but it seems to affect all of them.

**Comment by thomasjo** [comment]
Are you able to reproduce this in safe mode? `atom --safe`.

**Comment by okonomiyaki3000** [comment]
@thomasjo No. It seems that it does not happen in safe mode. I suppose then, that this means it's a bug in the ui theme and not Atom itself. It seems to be present in most, if not all, themes though.

**Comment by thomasjo** [comment]
> No. It seems that it does not happen in safe mode. I suppose then, that this means it's a bug in the ui theme and not Atom itself. It seems to be present in most, if not all, themes though.

It could also be a bug in community package that tweaks your tree-view. If you provide the list of installed community packages, we might be able to help you track down the culprit; show us the output of
```
$ apm list --installed
```

**Comment by okonomiyaki3000** [comment]
Ah, you were right. It's the seti-icons package. Thanks for your help.

**Comment by thomasjo** [comment]
> Ah, you were right. It's the seti-icons package. Thanks for your help.

You're welcome :bow:
