### ISSUE TITLE
Browser preview inside Atom?

### ISSUE THREAD

**Issue by santosh** [atom/atom#8216]
Atom is based on Chromium, right? So does it provides the same developer console as in other chromium based. 

What I was looking for was preview of my current HTML file working on. I know there are some [discussions](https://discuss.atom.io/t/browser-live-preview/612/48) already been discussed on this issue, and I know there are packages that issue the same. But when is it coming native in Atom?

**Comment by santosh** [comment]
Plus until then, how can I open current HTML file in my default browser? Without installing packages? Or if not possible any package?

**Comment by mehcode** [comment]
You're looking for https://atom.io/packages/browser-plus and https://atom.io/packages/preview-plus
