### ISSUE TITLE
UTF16 encoded files save aren't really UTF16

### ISSUE THREAD

**Issue by spuder** [atom/atom#8219]
Atom does not properly save UTF16 files, and here are steps to reproduce. 

Create a windows scheduled task, and export it. Windows will gladly create an XML file for you that is encoded as UTF-16 (Little Endian).

![screenshot 2015-08-04 11 57 39](https://cloud.githubusercontent.com/assets/242382/9068402/8762c78c-3aa0-11e5-9341-4279a50b3db3.png)

Open that xml in atom. Tell atom that it is a UTF-16 LE file (if it doesn't automatically recognize it)

![screenshot 2015-08-04 11 58 07](https://cloud.githubusercontent.com/assets/242382/9068436/b00120d0-3aa0-11e5-961d-3052bdadd323.png)

Verify that the XML windows task scheduler created is infact a UTF-16 file

![screenshot 2015-08-04 11 58 17](https://cloud.githubusercontent.com/assets/242382/9068447/c2f39c18-3aa0-11e5-9b7f-50e9c05cee3d.png)

Change 1 letter or word anywhere in the file

Save it as file2.xml

Try and import that back into windows task scheduler. 

You will get an error

```
The format of the task is not valid. The following error was reported: (1,2)::ERROR: one root element
```

![screenshot 2015-08-04 12 03 53](https://cloud.githubusercontent.com/assets/242382/9068465/e3469c4a-3aa0-11e5-84be-82b4c247cf10.png)

If you open the exported file in another editor (Like notepad++) and make a change, it will be formatted properly and windows task scheduler won't freak out. 

Atom : 1.0.3
Windows Server 2012R2

**Comment by spuder** [comment]
Probably related to:

https://github.com/atom/atom/issues/5482 
https://github.com/atom/atom/issues/7553
https://github.com/atom/atom/issues/5482

**Comment by frou** [comment]
I would try taking a look at the files using a hex editor to confirm what encoding they actually are at each stage. It's possible that the lexical value of the XML encoding attribute simply lies.

**Comment by spuder** [comment]
I can not reproduce on 1.27.1 on OSX or windows 2016
