### ISSUE TITLE
Path for atom.workspace.open is case sentive

### ISSUE THREAD

**Issue by hammeron-art** [atom/atom#8221]
Although something like C:\path\Main.ext is the same thing as C:\path\main.ext for the Windows filesystem, Atom opens different windows. One with the title "Main.hx" and other with "main.hx"...
They point to the same file. If I edit and save one the other window is updated.

I'm using a tool that output the path always in lower case and atom.workspace.open to open in a given line and column.

On Windows 8.1, Atom 1.03, Javascript, the follow open two windows for the same file:

``` javascript
atom.workspace.open(path, {
  initialLine: line,
  initialColumn: column,
  searchAllPanes: true
});
```

``` javascript
atom.workspace.open(path.toLowerCase(), {
  initialLine: line,
  initialColumn: column,
  searchAllPanes: true
});
```

**Comment by damieng** [comment]
Given the cross-platform nature of Atom and the case-sensitivity across systems we have decided not to change the behavior on Windows to try and do something different there and will continue to treat paths case-sensitive - this is especially important for other code paths such as opening urls which are still case-sensitive on Windows.

**Comment by Arcanemagus** [comment]
As this is causing issues in some packages it would be nice if this could be fixed here. For now it looks like a workaround like bringing in [true-case-path](https://www.npmjs.com/package/true-case-path) might need to be done in packages where this is a problem.

**Comment by Arcanemagus** [comment]
Note that this is also an issue on OSX (any file system where case isn't sensitive to the file system for resolving a file).
