### ISSUE TITLE
In a spec, when I run "atom.config.set", it returns all of my configs to default

### ISSUE THREAD

**Issue by mauricioszabo** [atom/atom#8224]
I know this is **really** a strange bug: I have a spec with `atom.configuration.set("package.key", "Foo")`. This makes Atom return to defaults in EVERYTHING - packages' settings, themes, font settings... The only things that are not changed are keybindings and stylesheets.

As I know this is kinda strange, I attached a gif to show this happening:

![capture](https://cloud.githubusercontent.com/assets/138037/9075824/11644b0a-3af0-11e5-8459-5e837a64897a.gif)

I click on "Reload Specs" and then, everything goes back to defaults...

**Comment by benogle** [comment]
Can you paste a link to your code? Config stuff is all mocked for specs: https://github.com/atom/atom/blob/26a382d8eb3611ba56c8a167da5d8ac77bfa2a4b/spec/spec-helper.coffee#L130

**Comment by mauricioszabo** [comment]
This is the code that my specs are testing. In my specs, right now, I'm mocking Atom specs but if I don't mock, it happens exactly as it happend on the screenshot.

Here's the code being tested:

```coffee
  registerProvider: (provider) ->
    # Sets a config for provider prefix
    config = atom.config.get('everything') || {}
    key = "#{provider.name}ProviderTrigger"
    if !config[key]
      provider.defaultPrefix ?= ""
      atom.config.set("everything.#{key}", provider.defaultPrefix)
    # Adds into provider list
    @providers[provider.name] = provider
    provider.onStart(this) if @visible && provider.onStart
```

The specs where:

```coffee
  it "registers a prefix to only trigger that provider", ->
    configs = {}
    spyOn(atom.config, 'set') # if I comment this line, then it breaks
    everything.registerProvider(test2Provider)
    expect(atom.config.set)
    .toHaveBeenCalledWith('everything.test2ProviderTrigger', 'tst')
```
