### ISSUE TITLE
EPERM operation not permitted fdatasync if backup before save enabled 1.0.4

### ISSUE THREAD

**Issue by Zireael07** [atom/atom#8235]
As the topic says. The backup gets created but the file itself fails to save. 
Switching off backup before save fixes this issue.

Please fix ASAP!!!

**Comment by jbehan-nexient** [comment]
this is also happening to me

**Comment by nathansobo** [comment]
Glad I made it optional... It would be great to get some more information. What platform? Does this happen always or intermittently? Are there any stack traces available?

**Comment by Zireael07** [comment]
In my case, Win 7 x64.
File creation permissions are on - I can save the same file fine with the option off or using 1.0.3. The backup gets created in the same folder, so it's further proof that permissions are on.
Happens always if I have the option on.

As for stack traces, how do I get them?

**Comment by jbehan-nexient** [comment]
* Windows 7, x64
* If 'backup before save' is enabled, it **always** happens
* Yes, I have file creation/editing permissions
* It gives this error message: "Unable to save file 'C:\Users\me\file.js    EPERM: operation not permitted, fdatasync"
* It creates the backup file in the directory. When I try it three times, it creates three backup files and looks like this:
  * file.js
  * file.js~
  * file.js~~
  * file.js~~~

**Comment by wesruv** [comment]
Was happening to me to, Win 8.1, turned off Backup before save and it's fine.
Was saving to a network drive that goes to my local Ubuntu VM.
Error was unable to save bla bla, then `EPERM: operation not permitted, fdatasync`

**Comment by Zireael07** [comment]
In my case it was my own HDD, NOT a network drive.

**Comment by Dave-Heyborne** [comment]
I just want to add that this affects me as well (Windows 10, x64). If 'Backup Before Save' is enabled, the backup file is created but never overwrites the actual file being saved. It ALWAYS happens, and the file is being saved on a local hard drive by a user account that has full file creation/deletion permissions. The problem does NOT occur for me on OS X (Yosemite), so it seems specific to Windows.

**Comment by nathansobo** [comment]
@bronson Any insight on these errors or suggestions? Time to start researching `fdatasync` on Windows I guess.

**Comment by bronson** [comment]
@nathansobo, no idea if the problem is in Atom, Node's fs binding, the filesystem, or Windows itself.  I'm unhappy to see it's happening with a local HD too.  I was hoping this would be yet-another-network-filesystem oddity.

@Zireael07 what filesystem were you trying to save to?

I googled but can't find much info about the combination of fsync, node, and windows.  I don't have any VMs lying around to try it anymore (stopped keeping up with the upgrade treadmill).

Is it worth extracting this to a small, reproducible test case script and asking the Node community?

**Comment by nathansobo** [comment]
Would still love to see a stack trace from someone that can reproduce this issue? I'm wondering if it's caused by our attempt to call `FlushFileBuffers` with the directory handle.

**Comment by 50Wliu** [comment]
@nathansobo just tell me how to get one :smile:.  I can repro this.

**Comment by nathansobo** [comment]
I think this is because you can't `fdatasync` a directory on Windows, and we're doing that to ensure the backup file's directory entry is flushed to disk. I need to get a build going again in a VM to see if this is true.

**Comment by nathansobo** [comment]
I just did a small test on my Windows VM where I tried to call `fdatasync` with a directory file descriptor and got this exact error. We're just not going to be able to sync the file entry on Windows. @bronson do you have any clever ideas for alternatives?

**Comment by bronson** [comment]
Found someone with the [same experience:](http://blog.httrack.com/blog/2013/11/15/everything-you-always-wanted-to-know-about-fsync/) "On Windows… err, there is no clear answer. You can not call FlushFileBuffers() on a directory handle as far as I can see."

Supporting evidence: Lucene still attempts the fsync on the dir and just eats the error: https://issues.apache.org/jira/browse/LUCENE-5588

That might be the best approach...  It would not surprise me if Linux/OSX can mount some network filesystem that also barfs when fsyncing directories.  Might as well attempt a sync but proceed even if it bombs.

**Comment by ejoso** [comment]
Why was this closed? I'm having the same problem and don't see a fix or patch here...

**Comment by nathansobo** [comment]
@ejoso The fix is on master, it will be available on the next release (1.0.6).

**Comment by johnsonz** [comment]
this is also happening to me. v1.0.4

**Comment by mnquintana** [comment]
@johnsonz You're using an old version of Atom - you need to update to the latest version (1.0.9) for the fix.

**Comment by johnsonz** [comment]
@mnquintana Thanks
