### ISSUE TITLE
Provides APIs to limit Atom autoupdate version in a specific range.

### ISSUE THREAD

**Issue by scv119** [atom/atom#8236]
Hey guys. I am working on [Nuclide](https://github.com/facebook/nuclide) and one thing I am doing right now is improve the quality of Nuclide.  

As it happened to us previously that Atom auto-updated a new version and made a non-backwards-compatible change and caused bugs and regressions, it would nice to have APIs to set the autoupdate version range for Atom programatically so that we can control the version of Atom user is using.

What's your guys thought about this? I am willing to write up PR's if it does make sense to you.

**Comment by bolinfest** [comment]
Which change was that? Was it the one that I fixed via https://github.com/atom/atom/commit/5031284ce58aab3c86a04c1ffe59a76822d0d62b?

**Comment by scv119** [comment]
@bolinfest  yeah, although https://github.com/atom/atom/commit/5031284ce58aab3c86a04c1ffe59a76822d0d62b didn't break Nuclide, but it's really close.

**Comment by scv119** [comment]
Addressed in https://github.com/atom/atom/pull/8721
