### ISSUE TITLE
Atom failing installing/searching packages with the message "The system cannot find the path specified"

### ISSUE THREAD

**Issue by olavobelloc** [atom/atom#8242]
I am running Windows 10 Pro (64-bit) and a fresh install of Atom 1.0.4.

After enabling the Developer Tools, I see the following error message:

> Fetching local packages failed. Error: Fetching local packages failed.
    at C:\Users\Olavo\AppData\Local\atom\app-1.0.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:89:21
    at exit (C:\Users\Olavo\AppData\Local\atom\app-1.0.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:59:16)
    at triggerExitCallback (C:\Users\Olavo\AppData\Local\atom\app-1.0.4\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Olavo\AppData\Local\atom\app-1.0.4\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

In the dev console, entering: "atom.packages.getApmPath()", gives me:
> "C:\Users\Olavo\AppData\Local\atom\app-1.0.4\resources\app\apm\bin\apm.cmd"

On a Command Prompt, running "apm featured" gives me:
> Featured Atom Packages (10)
├── color-picker Right click or press CMD-SHIFT-C/CTRL-ALT-C to open it. (389020 downloads, 1054 stars)
├── merge-conflicts Resolve git conflicts within Atom (159546 downloads, 844 stars)
├── minimap A preview of the full source code. (570904 downloads, 1483 stars)
├── pigments A package to display colors in project and files. (68434 downloads, 400 stars)
├── travis-ci-status Add Travis CI status of the project to the Atom status bar.  (30200 downloads, 128 stars)
├── vim-mode Add vim modal control (224665 downloads, 503 stars)
├── atom-material-syntax A dark syntax theme for Atom that uses Google's Material Design color palette (25348 downloads, 74 stars)
├── atom-material-ui A dark UI theme for Atom that follows Google's Material Design Guidelines (48253 downloads, 121 stars)
├── batman-syntax A color scheme inspired by the World's Greatest Detective (1171 downloads, 3 stars)
└── nucleus-dark-ui An adaptable UI with your favorite syntax theme at it's core! (4731 downloads, 18 stars)
> 
> Use `apm install` to install them or visit http://atom.io/packages to read more about them.

And running "echo %COMSPEC%", gives me:
> C:\WINDOWS\system32\cmd.exe

Also, other screens with package or theme information does not complete loading, ever, keeps showing "Loading packages/themes...".

Please, help! This renders Atom completely useless.

Thank you!

**Comment by olavobelloc** [comment]
Hello! I finally found the error! It was unrelated to Atom. Unfortunatly, I installed ANSICON aiming to colorize my command prompt (using choco). Unsatisfied with the result, I tried to uninstall it, but choco failed doing that properly, and leaved me with a buggy command prompt.

After removing the ANSICON AutoRun value from the registry, everything came back to normal.

**Comment by Shtucer** [comment]
> After removing the ANSICON AutoRun value from the registry, everything came back to normal.

Thanks! Have same problem with [Clink](https://github.com/mridgers/clink) installed.

**Comment by gtimuny** [comment]
I have the message about file path issues and the perpetual loading packages etc but how the hell do I figure out what else is installed and interfering
