### ISSUE TITLE
complie atom?

### ISSUE THREAD

**Issue by HappyGod158** [atom/atom#8244]
I 'm wondering how to compile atom source code, and debug it, just like debug a program in vs2008, but  I could not find a good tool, any suggestions?
Thanks!

**Comment by thomasjo** [comment]
Platform specific build instructions can be found here:
https://github.com/atom/atom/tree/master/docs/build-instructions.

As for debugging, that is detailed in the [debugging chapter](https://atom.io/docs/latest/hacking-atom-debugging) of the [Atom Flight Manual](https://atom.io/docs/latest/).
