### ISSUE TITLE
editor:delete-to-beginning-of-word is too greedy

### ISSUE THREAD

**Issue by zyklus** [atom/atom#8245]
Similar to #3816, but I have the same complaint about whitespace in general -- I believe that the command should act as follows (which is how ST3 acts):

- Delete trailing whitespace if any, up to newline
- Delete newline only if there is no whitespace on the current line
- Otherwise act as it currently does (delete previous characters until word boundary, case change, etc)

If I have the following text (`|` being the cursor):

```json
foobar    |
```

and tap ctrl-backspace, atom deletes the entire line.  ST3 yields:

```json
foobar|
```

I believe ST3's behavior makes more sense and is easier to use.

Atom 1.0.3, OSX 10.10.4

**Comment by benogle** [comment]
Can you try the `editor:delete-to-previous-word-boundary` and `editor:delete-to-next-word-boundary`. Do they do what you want?

**Comment by zyklus** [comment]
Thanks.  This _almost_ works like I want.  Unless I'm going crazy here, there seems to have been a functionality change in both of these between Atom 1.0.3 and 1.0.5

Previously:

```
fooBarBaz|  # ctrl+backspace
fooBar|
```

Now it deletes the entire word with either `editor:delete-to-previous-word-boundary` or `editor:delete-to-beginning-of-word`.  Other than that, this works like I'd expect.

Is there a new option that deletes up until a case change?  Or was that functionality tossed?  Or am I going insane?  ;)

**Comment by benogle** [comment]
There are `editor:delete-to-beginning-of-subword` and `editor:delete-to-end-of-subword`. AFAIK, these were never the default.

**Comment by maxbrunsfeld** [comment]
It seems like the commands @benogle suggested are what you're looking for, so I'm closing this out. Let us know if you have further issues with these commands.
