### ISSUE TITLE
Atom Load Time and applying some package Is Still Slow

### ISSUE THREAD

**Issue by shanalikhan1** [atom/atom#8247]
Im daily user for git hub atom. i found it best , using latest version with latest packages versions.
But im getting problems like.

1. When opening Atom first time it takes around 20 seconds to load. Only atom menu appears and rest of window hangs until all the atom loads.
2. When i apply some package like atom beatify to some page whole window stops responding. Sometimes i get error like editor is not responding. Close or wait more. I have to wait more in order to continue with work.

There should be a bar when the core atom features loads the window should be working properly and when loading the each of the installed packages it should display in status bar like 10 of 20 packages loaded and editor should be working behind in order to continue work and when package loads all features start working in backend of editor etc

**Comment by mnquintana** [comment]
1. See https://github.com/atom/atom/issues/2654. Also please try opening Atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) (`atom --safe`) to see if you still experience the same long load time - it could be that some of your community packages are slowing Atom down.
1. Please open an issue on [Atom Beautify's repo](https://github.com/Glavin001/atom-beautify).
