### ISSUE TITLE
editor crashed 5 times in 5 minutes

### ISSUE THREAD

**Issue by AHL96** [atom/atom#8248]
i was just looking at code not even 50 lines long

**Comment by AHL96** [comment]
and every time i go into the settings menu

**Comment by Zireael07** [comment]
What's your OS? RAM? Did you try atom --safe?

**Comment by AHL96** [comment]
im running os x (10.10.4), 4GBs of ram. I don't know what atom safe is, i just found out about this editor last week

**Comment by batjko** [comment]
@AHL96 You can run atom in safe mode from the command line, which disables all non-bundled packages:
`atom --safe`

If you don't get the crashes then, there's probably a community package you have installed, messing with you.

**Comment by izuzak** [comment]
Also, can you provide the crash reports which OSX recorded for those crashes, e.g. by pasting them in a gist and sharing a link here? You should be able to find those crash reports in Console.app.

**Comment by andya9** [comment]
I don’t know if it’s the same issue, but there’s [this file](https://gist.github.com/andya9/18ab6c6cdd6dfa7bc5cb) that immediately crashes atom on linux (4gb ram), both safe and normal mode

**Comment by benogle** [comment]
@andya9 likley your issue is #979

**Comment by andya9** [comment]
@benogle Yes it is! thank’you very much for pointing it
