### ISSUE TITLE
Unable to add a folder to project if that folder's parent is already in the project

### ISSUE THREAD

**Issue by brainthinks** [atom/atom#8249]
Assume you have the following directory structure:
- MyFolderA
- \- MyFolderA1
- \- MyFolderA2
- \- aFile.txt
- MyFolderB
- \- MyFolderB1
- \- MyFolderB2
- \- anotherFile.txt

Atom will not let me add MyFolderA and MyFolderA1 to the "root" of the project.  Of course if I add MyFolderA, then MyFolderA1 is still in the project, but if I want to add a folder that is more deeply nested than that, I am wasting sometimes a significant amount of horizontal space on the project tree having multiple nested folders open.  Additionally, I would like to have quicker access to some folders, since I work more in certain folders than others for a given project.

**Comment by bobrocke** [comment]
+1
