### ISSUE TITLE
Atom affects other programs' UIs on multiple desktops

### ISSUE THREAD

**Issue by steronydh** [atom/atom#8250]
I use MS Desktops (https://technet.microsoft.com/en-us/library/cc817881.aspx) on 64-bit Windows 7 and find that when Atom is running, when I bring other programs to the front, they don't always refresh completely, and I have to click again in the window or scroll the window to force a full refresh.

This seems to be a particular problem when using a desktop other than the default one, and when the programs are not running full-screen. I've had particular problems with the UI not updating in the Arduino IDE, but VS2010 and others also suffer from this.

The screenshot shows empty files in Atom and the Arduino UI. Atom was on top, then I clicked in the edit area in the Arduino IDE to bring it to the front and it drew as shown. Bringing the Arduino IDE to the front of other programs when Atom is not running never shows this problem.

Using Atom 1.0.4 on 64-but Windows 7.

![screen](https://cloud.githubusercontent.com/assets/4245329/9111729/ad7ff2c6-3c41-11e5-810e-cbaa757bec48.png)

**Comment by benogle** [comment]
cc @zcbenz

**Comment by zcbenz** [comment]
Refs https://github.com/atom/electron/issues/1821.

**Comment by steronydh** [comment]
Using the VirtuaWin virtual desktop manager seems to solve the problem. MS Desktops starts up a new copy of explorer.exe for each desktop, and the programs run isolated within their own desktop environment. With VirtuaWin, all programs run within the same explorer.exe, and the manager handles which programs are displayed within each virtual desktop.

Could the different ways the two multiple desktop managers work be behind this problem?
