### ISSUE TITLE
Settings view color bug

### ISSUE THREAD

**Issue by shanemikel** [atom/atom#8258]
The install packages tab of the settings view has a search box for finding new packages, and the text within this box is hard-coded with colors.  If you highlight the text in the box, it is impossible to read.

**Comment by simurai** [comment]
![screen shot 2015-08-07 at 4 15 27 pm](https://cloud.githubusercontent.com/assets/378023/9130708/17a22c62-3d20-11e5-8c1b-ace5a9555285.png)

Seems to happen with most dark themes. Maybe good to fix it on a Core level.
