### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by EpocSquadron** [atom/atom#8259]
After a fresh build of 1.0.5 I'm suddenly seeing this uncaught error. The error reporter claims it is a reported issue, but [that issue](https://github.com/atom/atom/issues/7987) is unrelated after reading through the comments. I went so far as to disable all of my packages. A noteworthy symptom is that syntax highlghting for php is not available with this error, presumably because of script execution stopping before that language file is loaded. I am able to see sass and js highlighting however.
#### Steps to reproduce
1. Open the editor

**Atom Version**: 1.0.5
**System**: "Arch Linux"
**Thrown From**: Atom Core
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:179

TypeError: undefined is not a function
    at /usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:179:24
    at Object.fs.readFile (ATOM_SHELL_ASAR.js:330:16)
    at Object.module.exports.readFile (/usr/share/atom/resources/app.asar/node_modules/season/lib/cson.js:173:17)
    at GrammarRegistry.module.exports.GrammarRegistry.readGrammar (/usr/share/atom/resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:107:12)
    at /usr/share/atom/resources/app.asar/src/package.js:561:32
    at /usr/share/atom/resources/app.asar/node_modules/async/lib/async.js:99:13
    at Array.forEach (native)
    at _each (/usr/share/atom/resources/app.asar/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/usr/share/atom/resources/app.asar/node_modules/async/lib/async.js:98:9)
    at /usr/share/atom/resources/app.asar/src/package.js:593:24
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-eslint",
      "linter",
      "emmet",
      "linter-scss-lint",
      "linter-phpmd",
      "linter-phpcs",
      "linter-php",
      "linter-pep8",
      "linter-less",
      "linter-jshint",
      "linter-jscs",
      "angularjs-styleguide-snippets",
      "atom-alignment",
      "atom-beautify",
      "docblockr",
      "editorconfig",
      "file-icons",
      "language-docker",
      "language-expressionengine",
      "language-htaccess",
      "language-twig",
      "minimap",
      "php-debug",
      "php-introspector",
      "ssh-config",
      "todo-show"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "showIndentGuide": true,
    "softWrap": true,
    "invisibles": {},
    "zoomFontWhenCtrlScrolling": false,
    "tabLength": 4,
    "showInvisibles": true
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Does it happen if you quit Atom and relaunch it in safe mode by running `atom --safe`?

**Comment by kevinsawicki** [comment]
@zcbenz This looks like `fs.readFile` called with a charset of `utf8` is calling back with something besides a string, probably a Buffer.

Do you think this could be an asar issue or something already fixed in electron?

**Comment by zcbenz** [comment]
> @zcbenz This looks like fs.readFile called with a charset of utf8 is calling back with something besides a string, probably a Buffer.
> Do you think this could be an asar issue or something already fixed in electron?

I remember I fixed a bug like this before, but I'm not sure whether that fix has been included in Atom.
