### ISSUE TITLE
Window decorations corrupted by workspace switching on XFCE

### ISSUE THREAD

**Issue by michaelsproul** [atom/atom#8260]
When I switch workspaces on XFCE 4.10 the Atom window decorations go all glitchy.
### Software
- Linux Mint XFCE 17.1
- XFCE 4.10
- Atom 1.0.3
- Firefox 39 (other GTK apps work too)
### Steps to Reproduce
- Open Atom in one workspace and something else in another (Firefox for example). 
- Switch from the Atom workspace to the other workspace and back.
### Result

Atom's window decorations aren't rendered, rather the contents of the other workspace are shown in their place. It looks like Atom needs to redraw. Switching focus to another application in the same workspace returns Atom to normal. No messages or errors are shown in the terminal used to launch Atom.

Here's a video of this behaviour: http://sproul.xyz/atom-xfce-render-bug.ogg

This doesn't happen on my Arch Linux machine (with XFCE 4.12) so it could well be a bug in this slightly old XFCE version. I'll try to upgrade it and update this thread accordingly.

Related but distinct from #3593 (which I can also reproduce).

**Comment by michaelsproul** [comment]
Unfortunately this is no different on Mint 17.2 with XFCE 4.12 (latest).

**Comment by rsyring** [comment]
Same problem here

**Comment by michaelsproul** [comment]
@rsyring: Are you also on Linux Mint/Ubuntu? I'm trying to work out why my computer running Arch is ok. I suspect the Xorg version is important.

**Comment by rsyring** [comment]
@michaelsproul Sorry, I'm on Xubuntu 14.04 with no customizations made to the desktop environment.  When I do "About XFCE", it shows 4.10.  

FWIW, I also have this problem with the Chrome browser sometimes.  It may not be specific to Atom.

**Comment by michaelsproul** [comment]
@rsyring I think I've discovered a work-around. I only tried it briefly but disabling compositing seems to fix this (Window Manager Tweaks > Compositor).

It's not the full story however, as my laptop running Arch has compositing enabled and no issues...

**Comment by peduxe** [comment]
@michaelsproul i'm running xfce with xubuntu here and I can't reproduce with neither (compositor enabled and disabled).

**Comment by michaelsproul** [comment]
@peduxe Which version? I suspect it's related to something in the 14.04 version of Ubuntu.

**Comment by peduxe** [comment]
@michaelsproul 15.04

**Comment by ZanyMonk** [comment]
This application is based on Chromium, that makes you able to simply run it with `--disable-gpu-compositing` flag, as you'd do with Chrome/Chromium and it will solve the problem. It has solved it here at least !

**Comment by peduxe** [comment]
@peduxe see if your gpu drivers are updated and also your window manager's compositor settings.

**Comment by michaelsproul** [comment]
@ZanyMonk: You're a legend!

I've noticed a few other graphical oddities recently, so I suspect it may be something specific to my graphics set-up (i915 driver with a Core i3 530 CPU).

**Comment by michaelsproul** [comment]
Oop, spoke to soon. I still have some weirdness...

**Comment by stephanfriedrich** [comment]
Same problem with here, with:
- Mint 17.3 & Mate-desktop v1.12.0.1-1+rosa
- Ubuntu 16.04 & Mate
