### ISSUE TITLE
Cannot easily specify variable Tab Length

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8261]
Why does Atom feel the need to choose which tab lengths I'm allowed to use? So many other editors let you specify this value (XCode/ST2/ST3/TW/KE/VisualStudio/even Word). And it's useful for all kinds of random tasks: sometimes I need to view/edit a massive variable-length TSV, so, elsewhere, I just throw my tab length to 40/60/whatever and edit faster than Excel thanks to regexes and [column selection](#2306).

The Tab Length item in the Settings panel should be a field, like Font Size, Line Height, and every other reasonable option: not a dropdown.

**Comment by izuzak** [comment]
Thanks for the feedback, @alexchandel. You can manually set the tab length to a different value by [editing your config.cson file](https://atom.io/docs/latest/using-atom-basic-customization#global-configuration-settings). Does that help?

**Comment by alexchandel** [comment]
@izuzak It does a little, but it's still a huge papercut. Wouldn't it be so much simpler to permit users to type directly into the dropdown, like every other display variable? I mean, I can specify an arbitrary custom *Line Height*, but I specify a 5-length tab (as certain old code often requires)? The restriction doesn't fit with Atom at all. Please reopen.

Moreover, tab lengths longer than 8 flat-out fail, and default to 4. Please reopen.

**Comment by izuzak** [comment]
@alexchandel Thanks for the additional feedback. Before we reopen this, I'd like to hear from @benogle who made this change in https://github.com/atom/atom/commit/7f5428e2a460641700bcff992e62026fe939dd5f. @benogle -- can you share some :thought_balloon: on that change and if we'd consider going back?

**Comment by benogle** [comment]
What if we added a couple higher ticks in there? 16, 32.

**Comment by 50Wliu** [comment]
> What if we added a couple higher ticks in there?

Is there any reason to not let people put in any value they want and bound it at a reasonably high number (like 100)?  I think that allows for a lot more flexibility (because there's going to be someone out there who loves a tab length of 5...).

**Comment by benogle** [comment]
I dont want to be a stick in the mud. PRs welcome.

**Comment by izuzak** [comment]
Thanks, @benogle :smile: -- going to reopen this then.

@alexchandel Since you've been helpful and expressed interest in this so far -- would you perhaps like to open a pull request for this? I'm happy to do it as well, but just wondering if you're interested in helping with that as well.

**Comment by alexchandel** [comment]
@izuzak Sure, I took a shot at #9198
