### ISSUE TITLE
menus disappear after hoovering over

### ISSUE THREAD

**Issue by MARTIMM** [atom/atom#8262]
Hi,
I've just installed the editor now but I see the following problem

After selecting an item in the menu bar or right click in editor panes a menu appears as it should. When hoovering over it on many occasions it will disappear again without being able to make a choice. It helps when selecting from the menubar first going left or right to have other menus out and then going over it.

I am working on a fedora linux system
```
> uname -a
Linux h03-fedora 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mnquintana** [comment]
Can you post a screenshot / screen capture of what you're experiencing?

**Comment by MARTIMM** [comment]
I cannot send you a movie screen capture here. Is there an email address I can use? Pictures will not show what I mean.

**Comment by MARTIMM** [comment]
Hi,
I found out that the settings in KDE for window behaviour(focus tab) were wrong. Now I've set it like so;
```
Policy: Focus follows mouse
Delay focus: 1000ms
focus stealing prevention: low
Raise on hover, delayed by 1000ms
```
Timings are not important but maybe not too short.
The policy is. however. This was before 'Focus strictly under mouse'.

Greetings
Marcel

**Comment by mnquintana** [comment]
@MARTIMM Oh nice! Did that fix your issue then?

**Comment by MARTIMM** [comment]
Yes it did

**Comment by 50Wliu** [comment]
Glad to hear :).
