### ISSUE TITLE
global.Function cannot be replaced on Atom 1.0.5

### ISSUE THREAD

**Issue by Metric** [atom/atom#8267]
Okay, so guys. People have been commenting on less-autocompile about it not being able to compile .less that uses javascript. It seems y'all did something to break the global.Function on 1.0.5. Anything lower than 1.0.5 works just fine.

In less-autocompile I use loophole on the global.Function such as:

```
var oldFunction = global.Function;
global.Function = loophole.Function;
.... //do stuff here while replaced
global.Function = oldFunction; //restore to default global
```

However, this does not appear to work in Atom 1.0.5. At least, it used to affect the less compiler parse Function, but it doesn't appear to anymore. I have proven that it is indeed 1.0.5 causing this issue again. I was on Atom 1.0.4 and lower for awhile and it still worked. The minute I updated to 1.0.5 it no longer works.

**Comment by batjko** [comment]
Since the [https://atom.io/packages/less-autocompile](less-autocompile) isn't a bundled package, there may have been a change that broke an assumption that the package author made.

I would open an issue on that package's repository, so he can adapt.

**Comment by Metric** [comment]
I am the author of it. What did y'all change exactly to cause this issue in 1.0.5?

**Comment by abe33** [comment]
Not sure about why it broke, but why do you actually need to `eval` something? Why not using `vm.runInContext` which is actually what `loophole` does under the hood?

**Comment by Metric** [comment]
Because, the less parser node module uses the 
```
(new Function('blah blah'))() //to parse javascript in a less mixin.
```
And, I have no control over that Function in the less parser node module. I also do not want to maintain a separate branch of the less parser node module just for Atom. The only way to modify and let the less parser work was setting the global.Function to the loophole.Function for a moment and then restore it after completion of parsing.

**Comment by batjko** [comment]
> I am the author of it.

Ah ok. Sorry, that wasn't clear.

**Comment by abe33** [comment]
Thanks for the explanation. BTW have you looked at how Atom was compiling the less stylesheets? because if it's not broken in 1.0.5 (and as far as I can tell it's not) then maybe there's a way for you to fix that by using the same mechanism that Atom.

**Comment by Metric** [comment]
Hmm, no I haven't looked at how Atom itself compiles its less files. I will take a gander through the code to try and find it. Unless, you can point me to which file it is in.

**Comment by Metric** [comment]
From what I can see, Atom uses LessCache, but LessCache uses require 'less'.Parser, which is exactly what I am doing. Looks like the Atom Less files do not have any javascript in them and that is why it is not throwing the javascript unsafe sandbox error when compiling. I bet, if you used the following mixin, in one of the Atom Less files, it would cause the javascript unsafe sandbox error:

```
.box-sizing(...) {
  @process: ~`(function(e){return e=e||"content-box"})((function(){var e="@{arguments}";return e=e.replace(/^\[|\]$/g,"")})())`;
  -webkit-box-sizing: @process;
  -moz-box-sizing: @process;
  box-sizing: @process;
}
```

**Comment by abe33** [comment]
You're right about Atom suffering the same restriction on `eval`: 

```
Error compiling Less stylesheet: /Users/cedric/.atom/styles.less
Line number: 66
JavaScript evaluation error: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
 from `(function(e){return e=e||"content-box"})((function(){var e="border-box";return e=e.replace(/^\[|\]$/g,"")})())`
```

**Comment by kevinsawicki** [comment]
I'm guessing this is due to https://github.com/atom/loophole/pull/4

**Comment by kevinsawicki** [comment]
> However, this does not appear to work in Atom 1.0.5.

What error are you seeing?

**Comment by kevinsawicki** [comment]
And also, do you have issues using `allowUnsafeNewFunction ` like in https://github.com/atom/loophole#eval-loophole- ?

**Comment by Metric** [comment]
Okay, I finally was able to update my windows version of atom to 1.0.5. And
I installed my lesscompile package 0.5.0. It seems to work just fine with
lesshat mixins with JavaScript. Looks like this actually may be a conflict
with the users packages they have installed along with lesscompile.

Users are reporting that lesscompile 0.5.0 is triggering the unsafe eval
error and not allowing files to save. However, upon further testing of my
Mac version and windows version it appears to work just fine. Nonetheless,
my Mac version did trigger the error earlier right after upgrade to 1.0.5.
But restarting atom on the Mac fixed it.

My conclusion, is that the users that are experiencing this, must have
other packages installed that are conflicting with the global.Function
overwrite. The other packages must be doing something on save that
is restoring it to the default global before lesscompile can finish the
parsing.

This can be closed.

**Comment by Metric** [comment]
As to this, yes. I tried using that originally, but the less parser is
asynchronous and it would still fail using that method. Because,
allowunsafenewfunction would restore the global.Function to the default
before the less could finish parsing.
