### ISSUE TITLE
"Replace All" is disabled

### ISSUE THREAD

**Issue by lowerends** [atom/atom#8269]
When doing a find-and-replace in a directory, the "Replace All" button is disabled.

The version of Atom is the latest at the moment of writing (1.0.5), running on Mac OS X. Here's a screenshot showing the disabled button:

![image](https://cloud.githubusercontent.com/assets/6588791/9137379/6bca19a6-3d1d-11e5-8eaa-35206a0934dc.png)

**Comment by mnquintana** [comment]
You need to do actually execute a search first, and that search has to return results. This prevents the user from accidentally replacing all before a successful search. See https://github.com/atom/find-and-replace/pull/473 for more information.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues

**Comment by lowerends** [comment]
Got it, thanks. 
Sorry for posting in the wrong repo, I'll take this into account.
