### ISSUE TITLE
Now ignored filenames showing up in the tree view. (Atom 1.0.5)

### ISSUE THREAD

**Issue by zoltanradics** [atom/atom#8270]
![screen shot 2015-08-07 at 18 08 10](https://cloud.githubusercontent.com/assets/878239/9140149/492a0886-3d2f-11e5-8e2b-df5e5b3ef10a.png)

**Comment by mehcode** [comment]
I believe _Exclude VCS Ignored Paths_ under "Core Settings" is for project search. We should really add some descriptive text there.

You'll want to go to the packages list (menu on the left of the settings tab) and search for "Tree View" and click on its settings. There is a similar checkbox you'll need to disable there.

**Comment by izuzak** [comment]
I believe you're right, @mehcode -- I suspect @zoltanradics didn't modify config options for the tree view package. @zoltanradics -- let us know if that doesn't help.

> I believe Exclude VCS Ignored Paths under "Core Settings" is for project search. We should really add some descriptive text there.

I agree. I wouldn't mind seeing a new issue for this. Would you like to create one, @mehcode?

**Comment by zoltanradics** [comment]
Enabling "Hide VCS Ignored Files" in the Tree View settings helped so now i see only those folders as before the update. Thanks guys to pointing it out!
