### ISSUE TITLE
"Check for Updates" crashes the editor in Atom 1.0 in Win 7

### ISSUE THREAD

**Issue by svaldivia** [atom/atom#8271]
Every time I try to update my packages, the editor crashes and asks me to reload. This behavior also happens when I go to settings>packages; I can't load installed packages. The following is what I use:

Atom 1.0.4
OS:Win 7

**Comment by izuzak** [comment]
@svaldivia Do you see the same problem in Atom 1.0.5, and can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by svaldivia** [comment]
@izuzak: Yes, it happens in Atom 1.0.5. I tried in safe mode and it happens as well; however, not that frequent. In safe mode, I can load packages and see the updates but after some time it crashes, it just takes longer than normal.

**Comment by izuzak** [comment]
@kevinsawicki @zcbenz  Any tips on investigating/debugging this?

**Comment by damieng** [comment]
Hi Svaldivia do you still have this problem?  If so can you provide a screenshot of the crash?

**Comment by svaldivia** [comment]
@damieng It doesn't anymore, I traced it back to a problem with the nuclide plugin. They had reported crashes in their repo; the plugin made atom consume a lot of memory. After removing it, atom has not crashed anymore.

**Comment by svaldivia** [comment]
As a result, I think it is safe to close this issue for now

**Comment by damieng** [comment]
Cool, thanks for the update @svaldivia
