### ISSUE TITLE
Scrollbar can stay active even if mouse button is relesed

### ISSUE THREAD

**Issue by w1res** [atom/atom#8273]
Using Atom 1.0.5 on Windows 7 64-bit.

Steps to reproduce:

1. Click and hold on the dragging thing on the scroll bar with the left mouse button (like when you are scrolling).
2. While continuing to hold the button, move your mouse out towards the center of the screen (away from the scroll bar's area).
3. Click and release the middle mouse button (the scroll wheel button).
4. Let go of the left mouse button.

What happens:

* The icon of the scroll bar stays as a square (rather than the small rounded style) like when you click and hold on it.
* If you move your mouse back to the scroll bar, the scroll bar's position will follow your mouse, even when no buttons are pressed.

Clicking on the scroll bar again fixes the issue.

**Comment by 50Wliu** [comment]
This is also present in Chrome 44, so I don't think this is Atom-specific.
Can you please report this to Chromium's [bug tracker](https://code.google.com/p/chromium/issues/list) instead?  Thanks.
