### ISSUE TITLE
Atom crashes when I drag a picture over it in Virtual Box

### ISSUE THREAD

**Issue by jacobnbrum** [atom/atom#8275]
I haven't seen any other issues noting this, but I am using atom in a virtual box running ubuntu 14.04. When I drag a picture (for example, from a website) over the atom window, Atom immediately closes (instantly). (Note I did not "drop" the picture in the window, just dragged it over.)

**Comment by mnquintana** [comment]
Thanks for the report! What version of Atom are you running? Are you dragging the picture in the guest OS or the host OS? What is your host OS?

**Comment by jacobnbrum** [comment]
I am running version 1.0.0.
It only happens when dragged from guest os (to atom running in guest os).
I am running windows 7 host.

**Comment by damieng** [comment]
Are you still experiencing this on recent versions of VirtualBox?  Their drag and drop support was flakey for a while but seems better now.

**Comment by damieng** [comment]
No response.
