### ISSUE TITLE
Having both "Exclude VCS Ignored Paths" and "Hide VCS Ignored Paths" settings is confusing

### ISSUE THREAD

**Issue by mehcode** [atom/atom#8276]
![image](https://cloud.githubusercontent.com/assets/753919/9144836/8b9fc460-3d04-11e5-8a93-7f1e4a62c348.png)

The _Exclude VCS Ignored Paths_ setting under Core Settings commonly gets confused with the similar setting under the Tree View package, _Hide VCS Ignored Paths_. I believe the first is for excluding files from search and the latter is for the tree view itself. 

For an idealized UI I'd vote for removing both settings and adding a new one that is a Select box where we can select to _exclude_ (from search and tree view), _exclude from search only_, and _show_. It doesn't make sense (to me) to allow not showing in the tree view but showing up in search.

We could also just add some explanation text to both settings if the above is too radical a change.

// ref #8270

**Comment by 50Wliu** [comment]
Another option would be to rename the settings to `Exclude VCS Ignored Paths From Search` and `Hide VCS Ignored Paths from Tree View`, respectively.  Of course, if either of the settings has a broader impact, then this won't work :P.

**Comment by surdu** [comment]
I'm here because I wanted to file a bug that `Exclude VCS Ignored Paths` is not honoured in TreeView, so yeah, it's confusing :smile:

**Comment by tomByrer** [comment]
The check box would be more clear if it was: "Hide `.gitignore` files"

**Comment by surdu** [comment]
@tomByrer In your variant, I would believe that by checking the checkbox it will hide the `.gitignore` file itself from the tree view, which is not the intended function.

**Comment by hypnoboutique** [comment]
I second this. Having both settings is confusing. Especially as you have to dig a bit to get to the tree-view settings.

The fact that I'm still unclear on the difference make me think that this is a UX issue (or I'm an idiot, which is also feasible).

p.s. For future sailors: pressing `i` in the tree view will toggle your ignored files. You might find this useful in diagnosing why they disappeared in the first place.
