### ISSUE TITLE
Too large memory footprint

### ISSUE THREAD

**Issue by neotyobosralsya** [atom/atom#8278]
![atom_memory_consumption](https://cloud.githubusercontent.com/assets/11809316/9145662/197e54fe-3d5f-11e5-879d-5c96edb70bd7.png)

Excuse me for russian on the screenshot. ГБ stands for gigabyte and МБ for megabyte.
It may be seen that Atom with 8 windows and 37 files open consumes about 4.7 Gb of memory. That's way too much for a text editor. My system even asked me to close some programs and I closed Firefox :D
So, I think that memory consumption should be optimized.

**Comment by lewislepton** [comment]
aye. i am having at least 1gb of memory used on a project, for just being open. 2 projects, about 2gb.

so yeah, the memory footprint is way way way too much

**Comment by YuriSolovyov** [comment]
BTW, chrome team is working on a [memory reduction project](https://docs.google.com/document/d/1zlGQkwkWEu5LUg-CrZHHRuhDtZcuvrRv8bjdC8-noaU/edit?pli=1#heading=h.a898thpufhtq). Atom just needs to pick newer versions of chrome more often

**Comment by lewislepton** [comment]
oh cool. good to know. hope it gets sorted soon

**Comment by andyburke** [comment]
This is still an issue. Perhaps this comment could help shed some light?: https://github.com/atom/atom/issues/1827#issuecomment-142954663

I am seeing this, leaving Atom running for long periods:

![screen shot 2015-09-30 at 2 37 35 am](https://cloud.githubusercontent.com/assets/273857/10189641/689fd896-671c-11e5-8dad-a7a3ab16be23.png)

**Comment by benogle** [comment]
Closing in favor of https://github.com/atom/atom/issues/1827

**Comment by nodkz** [comment]
@lee-dohm The problem of huge memory consumption can be related to the **disk size**. 
Electron may see **1Tb disk** and starts to eat memory like abnormal. I have this problem with other Electron apps.

I have 3 same Atom setups on same app:
- iMac 16GB RAM 1TB fusion disk - after one hour Atom eats 2-3GB of memory 
- iMac 8GB RAM 1TB fusion disk - after one hour Atom eats 2-3GB of memory
- MacPro 8GB RAM 256 ssd disk - after one hour just 800MB, and stays almost the same all day

For myself I solved this problem via free version of CleanMyMac 3. Press **Free up** and atom from 3-4GB reduces memory consumption till 600MB without restarting.

<img width="339" alt="screen shot 2017-05-17 at 11 08 55" src="https://cloud.githubusercontent.com/assets/1946920/26139288/48f105d8-3af1-11e7-9ff5-5f297016a6c1.png">

**Comment by nodkz** [comment]
Sorry for the noise.
The problem was with Nuclide plugin. It is very wasted. Remove it and try to find exactly needed functionality in other plugins.

BTW. New Git GUI in 1.18 is amazing! Bye-bye SourceTree, now stage lines/hunks will do only in Atom.

**Comment by 50Wliu** [comment]
Glad you figured out the problem @nodkz!
