### ISSUE TITLE
treeview

### ISSUE THREAD

**Issue by leifeng-hm** [atom/atom#8280]
I want to know,how to move tree view to left...
![bf057693-7e04-49dd-a7ab-5fb6160d8a66](https://cloud.githubusercontent.com/assets/8827549/9148745/f4a563a0-3dba-11e5-835b-5d4fae04b014.png)

**Comment by izuzak** [comment]
Open the [Command Palette](https://atom.io/docs/latest/getting-started-atom-basics#command-palette) and then use the `Tree View: Toggle Side` command. Does that help?

**Comment by leifeng-hm** [comment]
thanks！！！
