### ISSUE TITLE
Building Atom from source on Mageia 5, `sudo script/grunt install` fails

### ISSUE THREAD

**Issue by fusion809** [atom/atom#8283]
Hi, 

A previous issue I raised here, namely, #7534, is similar but this time I have a new virtual machine and I haven't made the mistake of deleting `/usr/bin/env`. Atom appears to run without issue (although I haven't done like rigorous tests to see whether all functionalities are available. I just know the interface of Atom pops up and everything, visually, looks fine) when I run `./atom.sh` from the source code directory (which FYI is at `~/atom`). The only problem is that running `sudo script/grunt install` gives the error:

```sh
/usr/bin/env: node: No such file or directory
```

does anyone know I might overcome this problem? 

**How I got my dependencies for Atom**
I ran `sudo urpmi make gcc gcc-c++ glibc-devel git-core libgnome-keyring-devel rpmdevtools` (and yes I did just copy-paste it from the Fedora/CentOS/RHEL instructions [here](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#fedora--centos--rhel)) and installed Node.js v0.12.7 from source.

**Comment by thomasjo** [comment]
If you read the error message carefully, you'll notice that it's telling you that the `env` executable cannot locate a `node` executable. In other words, `node` is not discoverable given your current `PATH` environment variable.

What does executing `which node` return?

**Comment by fusion809** [comment]
Returns `/usr/local/bin/node` and my PATH variable is: `/usr/local/bin:/usr/bin:/usr/local/games:/usr/games:/usr/lib64/qt4/bin:/usr/lib64/qt5/bin:/home/fusion809/bin` (I'm including as it includes `/usr/local/bin`)

**Comment by thomasjo** [comment]
OK, and what about `sudo which node`?

**Comment by fusion809** [comment]
`which: no node in (/sbin:/bin:/usr/sbin:/usr/bin)`

On 10 August 2015 at 15:04, Thomas Johansen <notifications@github.com>
wrote:

> OK, and what about sudo which node?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/atom/issues/8283#issuecomment-129300251>.
>



-- 
Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Oh and btw may I ask why you haven't added the linux tag to this question? If I can add tags to my question please do tell me as if so I haven't the foggiest how.

**Comment by thomasjo** [comment]
Your problem is caused by Debian-based distros (almost always) using the `secure_path` feature which is part of the `env_reset` functionality. Either alter the `secure_path` as configured in `/etc/sudoers` or negate it. Check out these for more details
 1. https://wiki.debian.org/sudo
 2. http://unix.stackexchange.com/questions/91541/why-is-path-reset-in-a-sudo-command

If it's a one-time thing (or at least infrequent) I commonly work around this by doing e.g.
```bash
$ sudo env "PATH=$PATH" script/grunt install
```
This is the safest approach, and would also allow you to temporarily extend/alter `PATH` if necessary.
