### ISSUE TITLE
New option: Update checking interval

### ISSUE THREAD

**Issue by mat-b-** [atom/atom#8285]
As per [discussion](https://discuss.atom.io/t/questions-about-update-checking/19688), notification in the status line is bugging to install updates every single day (packages are updated often).

It takes focus away from real work to the application ("action is needed").

The option would go great with the motto:

> Atom - (...) a tool you can customize to do anything but also use productively without ever touching a config file

This should also help a little with startup performance.

Default setting could be 24 hours or 1 week.

**Comment by maxbrunsfeld** [comment]
Could you move this issue to the [settings-view](https://github.com/atom/settings-view) package?
