### ISSUE TITLE
Is there a way to inject BrowserWindow options from a user script?

### ISSUE THREAD

**Issue by p-e-w** [atom/atom#8287]
It appears that the options for Atom's `BrowserWindow` instance are compiled [here](https://github.com/atom/atom/blob/a6d9b0506c1fc4aab1eb7a9ec34cb6047729514c/src/browser/atom-window.coffee#L29).

Is there a way for user scripts to add to / manipulate these options? There are many use cases for this, such as setting the initial window position or enabling the GTK+ dark theme.

**Comment by peduxe** [comment]
@p-e-w Would like to as well, there's an [option](https://github.com/atom/atom/blob/a6d9b0506c1fc4aab1eb7a9ec34cb6047729514c/src/browser/atom-window.coffee#L34) that I think may be the culprit for poor font rendering on windows:

**Comment by darkmorpher** [comment]
CC @damieng Tag `Linux`

**Comment by damieng** [comment]
@darkmorpher I appreciate the help but I'm focused on Windows issues.
