### ISSUE TITLE
chinese chars becomes 〄〄〄 in version 0.209.0 on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by 4096void** [atom/atom#8288]
![chinese_does nt display](https://cloud.githubusercontent.com/assets/11892251/9154024/324e4fbe-3eb0-11e5-9f75-7563c7f3d885.png)

**Comment by izuzak** [comment]
Thanks for the report, @4096void -- this sounds like a duplicate of https://github.com/atom/atom/issues/6214. There are some notes in there about how you might work around the problem.

**Comment by 4096void** [comment]
Thx for your help! I just set the font-family to Droid Sans Mono, Droid Sans Fallback
