### ISSUE TITLE
Git LFS confuses Atom's git change detection.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#8291]
When a file is added to Git LFS and pushed Atom still thinks the file has changed and highlights it in orange even though it has already been pushed up to Github.

I am pretty sure this is the wrong repo to post this on but if you point me to the proper one I will move it.

**Comment by thomasjo** [comment]
If this works as expected in a terminal, then I believe this should be reported against [libgit2](https://github.com/libgit2/libgit2).

Not 100% sure though, so maybe someone else can confirm or correct? /cc @atom/feedback

**Comment by izuzak** [comment]
@envygeeks Just to make sure we understand your report -- can you share the exact steps which reproduce the problem for you? Also, as @thomasjo mentioned -- can you confirm that Git reports the correct status?

**Comment by envygeeks** [comment]
@izuzak @izuzak  Git does provide the correct status because it seems Github is using attributes.

```
jordon@envygeeks:~/development/envygeeks/docker/alpine-dev ~> git status --porcelain \
  --verbose repo/x86_64/glibc-2.21-r4.apk; echo $?
0
```

I will check tonight if it's a libgit2 issue since Ruby has bindings.

**Comment by envygeeks** [comment]
Move it to libgit2 since it is their problem!

**Comment by envygeeks** [comment]
I'm back, it seems that libgit2 says this is a problem with Atom: https://github.com/libgit2/libgit2/issues/3373#issuecomment-130349524 but I don't know where the source to all this is so if you can point me to the repo and the source I'd be happy to try and fix that.

**Comment by izuzak** [comment]
@envygeeks I guess the next place to look would be https://github.com/atom/git-utils.

**Comment by envygeeks** [comment]
Closing this in favor of @ruffsl's issue that follows up on this one. Thanks!

**Comment by lee-dohm** [comment]
Thanks @envygeeks :grinning:
