### ISSUE TITLE
Package's `deactivate` callback doesn't seem to be called when Atom window is closed/reloaded

### ISSUE THREAD

**Issue by UltCombo** [atom/atom#8294]
From the [docs](https://atom.io/docs/latest/creating-a-package#source-code):

> - `deactivate()`: This **optional** method is called when the window is shutting down, or when your package is being updated or disabled. If your package is watching any files, holding external resources, providing commands or subscribing to events, release them here.

If I disable the package manually through the Settings interface, the `deactivate` callback is called as expected. However, if I close or reload Atom (ctrl+alt+r / cmd+ctrl+alt+l), the `deactivate` callback is not called at all. I'm testing this by adding a `console.log` to the `deactivate` callback and reloading Atom while having the DevTools console open with the "Preserve log" option enabled.

Use case: I'm developing a package which spawns child processes. I'd like to kill them when Atom closes.

Is this a bug or am I doing something wrong?
Running Atom 1.0.5 on Windows 10.

Here's the package's [source code](https://github.com/UltCombo/ult-terminal/blob/0061f89db5fc37a50f7b17a71e8b1d653f95d61c/lib/ult-terminal.coffee#L16-L17).

**Comment by deprint** [comment]
I tested this in one of my packages (which also has to kill a child process):
* Reloading atom with `console.log` in `deactivate` does not print anything
* Calling `atom.packages.deactivatePackage` manually prints the log message
* Reloading atom with `require('fs-plus').writeFileSync('test','Destroyed')` in `deactive` creates a test file

It appears that the `deactivate` function is fine but `console.log` does not work when reloading atom (even with the "Preserve log" option)

**Comment by UltCombo** [comment]
Interesting diagnostic, @deprint.
Further testing shows that not only the `console.*` API output is not shown when reloading, thrown errors are also not reported.

Anyway, looks like I'm back to square one then. My child process tree is not killed when Atom exits or reloads. Perhaps this is because spawning the child process which kills the child process tree is asynchronous. I guess I'll try to `spawnSync` and dereference a new child process to kill the child process tree.

Perhaps showing a message and preventing Atom from closing (i.e. having the user explicitly press a kill button) would be a better solution?

@deprint does your package reliably kills the entire child process tree when closing Atom?

**Comment by thomasjo** [comment]
I'm closing this issue since the `deactivate` function on packages is invoked correctly.

Perhaps continue the discussion about resource cleanup either in [Slack](https://discuss.atom.io/t/join-us-on-slack/16638) or [Discuss](https://discuss.atom.io)? :bow:

**Comment by UltCombo** [comment]
Oh thanks, but I guess it won't be necessary. I've found a solution which seems to work reliably: https://github.com/UltCombo/ult-terminal/commit/a61f585e52b138c0583e5b9628654b02f0d8545e
