### ISSUE TITLE
Build fails while downloading atom

### ISSUE THREAD

**Issue by agauniyal** [atom/atom#8297]
While installing [atom-editor-bin](https://aur.archlinux.org/packages/atom-editor-bin/) through yaourt on arch-linux, downloading step fails each time with error - `curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104`. Another thing to note is, process of downloading is started everytime successfully but downloading fails only on 5% or 6%.

Here is remaining output from yaourt:

```
==> ERROR: Failure while downloading atom-amd64-v1.0.5.deb
    Aborting...
==> ERROR: Makepkg was unable to build atom-editor-bin.
```

Also are there any other hosts that contain up to date builds of atom so that I could edit PKGBUILD with relevant url.

**Comment by anielk** [comment]
same here, cannot dowload any windows build, keeps on failing

**Comment by izuzak** [comment]
This is likely related to the availability issues with releases, as mentioned on the GitHub status page:

https://status.github.com/messages

Follow that for updates.

**Comment by izuzak** [comment]
Things should be back to normal -- release assets should be downloadable again. Please let us know if you're still seeing problems.
