### ISSUE TITLE
Can't scroll to the very edge of the window

### ISSUE THREAD

**Issue by lodev09** [atom/atom#8298]
I'm having an issue with the scroll bar at the very edge of the window. Most apps will let you just drag your mouse at the very edge of the window and would let you scroll the content. I'm not sure if this is intended feature or something but it would be really nice to just move the scroll bar at the very edge so you don't need to focus your cursor all the time to scroll. :)

![scroll](https://cloud.githubusercontent.com/assets/6686328/9168925/1780392c-3f8c-11e5-82bf-58f6b34e4337.png)

Atom version: `1.0.5`
OS/Platform: **Windows 10 PC**

**Comment by izuzak** [comment]
@lodev09 Thanks for the feedback. I don't have access to my windows vm so I'm wondering if you could record a short GIF which clearly demonstrates the problem (e.g. with http://www.cockos.com/licecap/)? I'm not sure I understood what seems to be the problem, and a GIF would probably be more helpful than a screenshot here. :bow:

**Comment by lodev09** [comment]
nvm, this issue is related to the theme **One Dark**. It has thick window border. I'll submit this issue to their repo page. Thank you.
