### ISSUE TITLE
Latest manual (1.0.5) is blank

### ISSUE THREAD

**Issue by mindrones** [atom/atom#8299]
At the moment, the [latest manual](https://atom.io/docs/latest/) is blank.

![screen shot 2015-08-10 at 12 50 25](https://cloud.githubusercontent.com/assets/1309648/9169875/7322c6ba-3f5e-11e5-9022-270d30fdc841.png)

The [previous version](https://atom.io/docs/v1.0.4/) is ok.

**Comment by izuzak** [comment]
Thanks for the report -- closing in favor of https://github.com/atom/docs/issues/111
