### ISSUE TITLE
pane:move-item-left/right, tab jumps two places

### ISSUE THREAD

**Issue by emiljohansson** [atom/atom#8300]
When I use the key bindings ctrl-shift-left and right, the tab jumps two steps.
It looks like the key binding is defined in two places and is called for each one. The screenshot is open in safe mode and my keymap.cson is empty.

Atom 1.0.5
OSX 10.10.4

<img width="1440" alt="screen shot 2015-08-10 at 2 54 12 pm" src="https://cloud.githubusercontent.com/assets/1788399/9171954/0c9a1076-3f70-11e5-9dc7-0b01a1867458.png">

**Comment by benogle** [comment]
This is legit, I think it's a regression from the last couple of releases.

**Comment by benogle** [comment]
This will be fixed in 1.0.6 tomorrow
