### ISSUE TITLE
allow package developers to create OS global keybindings

### ISSUE THREAD

**Issue by zettler** [atom/atom#8304]
It seems like Electron has API for this (https://github.com/atom/electron/blob/master/docs/api/global-shortcut.md) but you cannot use it for package creation.

Any way to fix that?

**Comment by thedaniel** [comment]
Can you give an example of how you'd like to use this in a package?

**Comment by zettler** [comment]
I'm using https://github.com/deltaidea/notational-windows for taking notes. It would be nice to trigger the atom window with the notes searchfield toggled by a hotkey, so when I'm watching a youtube video, or read an interesting quote, I just have to press e.g. ctrl+shift+P and can directly start the package search to find my "quotes.txt" where I then text.

It would be nice if you could specify whether the atom itself will move into focus or not. An example where it (could but) needn't be focussed is a stopwatch package I'm working on. It locks the time when a certain key is pressed (takes rounds). A very specific (personal) use for this is that I'm sometimes watching youtube videos while recording the audio for creating flashcards afterwards or just to replay from the video position (e.g. if they speak fast and you just want to listen again) and it would be nice if I could do so in full-screen-mode, while atom logs the times where you clicked "Ctrl+T+O+P". So that afterwards you can have another look at the video positions you had difficulties with/you're interested for your language studies, without loosing too much of the movie feeling when you watch the film for the first time. (Other uses would be recording an interview/a lecture and logging important time positions to get back to, but here, putting ATOM in focus wouldn't be a problem).
