### ISSUE TITLE
"quick jump" between indents is buggy

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#8306]
"quick jump" between indents is buggy (and useless IMHO, but that is more of #3174 topic).

Check example here: http://youtu.be/grQyFxLhOd8
This happens with latest Atom, in safe mode, Linux.

**Comment by izuzak** [comment]
@alexandernst I'm having trouble reproducing the behavior in that video. Which version of Atom are you using, which UI and syntax theme, and can you reproduce this in safe mode? Also, can you provide your config.cson file as well?

**Comment by alexandernst** [comment]
@izuzak Turns out it's a bug because of a font with ligatures. Should I close this?

**Comment by izuzak** [comment]
@alexandernst Yeah, I think so. There's a few other issues related to problems with fonts with ligatures -- you might want to find those and add a comment there. Thanks for investigating this! :sparkler:
