### ISSUE TITLE
Arrow Keys don't scroll up/down in package search

### ISSUE THREAD

**Issue by smazo** [atom/atom#8310]
Arrow Keys don't scroll up/down in package search results.  Also can't scroll with mouse or page up/ page down.

**Comment by izuzak** [comment]
Sounds like a duplicate of https://github.com/atom/settings-view/issues/544 which is being worked on in https://github.com/atom/settings-view/pull/468. It's strange that you're not able to scroll with the mouse, though. I'd suggest you open a new issue for that in https://github.com/atom/settings-view and provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues).
