### ISSUE TITLE
Can not disable linebreak at end of file

### ISSUE THREAD

**Issue by DebugMeNow** [atom/atom#8311]
Atom is adding a linebreak at the end of a file.
This behavior can not be disabled (as I know) and is problematic for eg. developing PHP scripts.
Every character in an included PHP file that comes after the closing tag "?>" will prevent me from sending headers.
(I know that I could remove the closing PHP tag, but a editor souldn't tell me how to programm.)

Using Atom 1.0.5 (portable) on Windows 7 x64

**Comment by 50Wliu** [comment]
You can disable it by going to Settings (<kbd>Ctrl+,</kbd>) --> Packages --> Whitespace --> disabling `Ensure Single Trailing Newline`.

**Comment by DebugMeNow** [comment]
Thanks an sorry for the noise ;-)
