### ISSUE TITLE
Update to Octicons 3.0

### ISSUE THREAD

**Issue by simurai** [atom/atom#8314]
The Octicons got [updated to 3.0](https://github.com/github/octicons/pull/58). There are some visual changes, but also some icons got removed and some new ones added.

It's not that straightforward to update them, since some of the community packages might use some of the icons that got removed.. like the `alignment`, `move`, `jump` icons.

A few options:
1. Update to Octicons 3.0. Packages might need to make changes or add their own icons.
2. "Manually" update to Octicons 3.0 and still keep the ones that got removed. There should be no name conflicts.
3. Keep the current Octicons as is.
4. Keep the current Octicons as is (at least until Atom 2.0). And add an additional "Atom icons set". Could be a fork of the Octicons 3.0 and modified to Atom's needs. Class names could be `atom-icon` or so. The find + replace already uses some custom icons. Also having custom icons for autocomplete-plus would be nice.

**Comment by simurai** [comment]
Short term we can just keep as is (3). And then at some point, try 2. And maybe start an additional Atom set for all icons that need to be custom.

**Comment by thomasjo** [comment]
I (or someone else) can grab all community packages and `grep` for usage of the removed octicons. I'm super busy today though due to travel, so I might not have time to do this today.

If there's no usage of the removed icons, I propose we upgrade sooner rather than later.

**Comment by simurai** [comment]
I see. Yeah, if we have some usage insights, that would make it easier. In case, here a list of the class names that got removed:

```
icon-alignment-align
icon-alignment-aligned-to
icon-alignment-unalign
icon-beer
icon-hourglass
icon-jump-down
icon-jump-left
icon-jump-right
icon-jump-up
icon-microscope
icon-move-down
icon-move-left
icon-move-right
icon-move-up
icon-playback-fast-forward
icon-playback-pause
icon-playback-play
icon-playback-rewind
icon-podium
icon-puzzle
icon-split
icon-steps
```

**Comment by benogle** [comment]
> Keep the current Octicons as is (at least until Atom 2.0)

I think we should probably do this. There's no reason to switch them up: no benefit, and opportunity for pain.

**Comment by mnquintana** [comment]
This might be a good time to start an Atom 2.0 milestone or label for breaking changes we won't touch till then.

**Comment by simurai** [comment]
> no benefit, and opportunity for pain.

Well, arguably the new icons look better? :grimacing: But yeah, maybe not enough to cover the potential pain.

**Comment by thedaniel** [comment]
> Keep the current Octicons as is (at least until Atom 2.0)

I feel like the current icon set is basically a public API, so we shouldn't remove them. If you're really invested on getting them in we could add a set of `octicons-3-*` css classes through Atom 2.0 but who knows how many versions of octicons will come out before then?

**Comment by thomasjo** [comment]
Given how much many of the icons have changed, it seems like we cannot add new icons unless we upgrade to 3.0 (the visual discrepancy is a bit jarring). But of course, ad have been pointed out, is not without problems either. And these types of big changes might happen again as well... Tough call.

**Comment by danielbayley** [comment]
+1.

**Comment by jerone** [comment]
Octicons 3.5 has been [released](https://github.com/github/octicons/releases/), it would be nice if this gets updated to the latest version.

**Comment by simurai** [comment]
Ya, the new `3.x` version is nice. But it's not without issues, see above.

Another issue is that now with sub-pixel rendering enabled, font icons can look blurry. So maybe a good way forward would be:

1. Keep the current Octicons as "legacy" icon set. So no packages would break.
2. Introduce a new Atom icon set that uses SVG instead of an icon font. It could start with a fork of the `Octicons 3.5`, but maybe have a few more custom icons added. Find + replace already uses their own icons.

**Comment by jerone** [comment]
> Introduce a new Atom icon set

If this option is chosen, is it possible to install this as dependency package so it can get regular updates?

_FYI, I'm trying to restart this issue, as it's the default iconset for the [Tool Bar](https://github.com/suda/tool-bar) package and besides it's no documented which version Atom is using, people expect the latest version._

**Comment by simurai** [comment]
> is it possible to install this as dependency package so it can get regular updates?

Yes, we would maintain it ourselves as a fork. Manually updating icons or add new ones. And when an icon gets removed from the Octicons, we could still keep it to stay backwards compatible. More work, but more flexible and less breaking changes.

The current Octicons version in Atom is `2.1.2`. Maybe for Tool Bar you could bundle the new `3.5` version. At least for now. Then people can switch to it if they don't need the icons that got removed.

**Comment by Alhadis** [comment]
Having an *"Atomicons"* font for Atom feels like the most sustainable and logical long-term solution.

Icons will be removed or added to GitHub's icon-set over time, but there's absolutely no reason these should be reflected in the icon-set of a related product (Atom). Even if both fonts share very similar icons, keeping their development histories separate enables us to avoid breaking changes, and permits the introduction of new icons for Atom that're otherwise not relevant enough to be used or seen on GitHub.

**Comment by simurai** [comment]
Here another idea from @joefitzgerald:

> couldn't we have octicons (latest) + octicons (deleted bits) to have the best of both worlds?

So instead of replacing or manually merging the new font with the current one, maybe we could [load](https://github.com/atom/atom/blob/master/static/variables/octicon-mixins.less#L37) an `octicons-2-1-2.woff` (old version) **and** `octicons.woff` (new 3.x version). Might be worth a try.

**Comment by joefitzgerald** [comment]
v4.3.0, now 😃

**Comment by joefitzgerald** [comment]
Incidentally, why wouldn't we load the latest patch release of octicons 2.x (https://github.com/primer/octicons/releases/tag/v2.4.1)?

**Comment by simurai** [comment]
Hey, there is an easy way of updating to the new Octicons **AND** still keep the ones that got removed. See PR #13138.

Basically just have two font-face declarations that load the old and new icons, but have the **same** font-family name:

```less
@font-face {
  font-family: 'Octicons Regular';
  src: url("octicons-old.woff") format("woff");
}
@font-face {
  font-family: 'Octicons Regular';
  src: url("octicons-new.woff") format("woff");
}
```

Luckily it doesn't replace the whole `@font-face` but only the icons with the same utf codes. 🎉
