### ISSUE TITLE
Babel: Line numbers when specs fail are from transpiled file.

### ISSUE THREAD

**Issue by noseglid** [atom/atom#8316]
Running tests:
![](https://cdn.discourse.org/business/uploads/github_atom/original/3X/a/4/a46dc79a2e4a783e423f06453b4d332deb342f44.png)

Checking source code file at row 784: 
![](https://cdn.discourse.org/business/uploads/github_atom/original/3X/8/c/8c39d14a261567fbcd5572c64418c81f3e8383c3.png)
That's not it. Neither `warning` nor `error` is part of this...

The actual error is found further down in the file:
![](https://cdn.discourse.org/business/uploads/github_atom/original/3X/a/9/a937c28f777b88e2bd83fe0db5d4b55f09aa357b.png)

I transpiled the file manually using babel, and voila (at row 784):
![](https://cdn.discourse.org/business/uploads/github_atom/original/3X/f/b/fbe069f8745480980320657221b3ebcadcf855e0.png)

**Comment by thomasjo** [comment]
@bolinfest Any idea what might be going wrong here? I've noticed this in the past, but not for a while now. Anyway, is there anything we can do if this is a problem on our end?
