### ISSUE TITLE
Copy project path (keyboard shortcut + command)

### ISSUE THREAD

**Issue by sandstrom** [atom/atom#8319]
The tree view has *Copy full path* and *Copy project path*. In the edit-menu there is *Copy path* (which copies the full path). The latter can also be used via a keyboard shortcut and the command palette [cmd+shift+p].

It would be great if the edit-menu (as well as the command palette) would could be split into a *Copy full path* and *Copy project path* — I find them very useful, but currently they are only available using the mouse. :mouse:

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tree-view? Thanks!

Also see https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Comment by sandstrom** [comment]
@mnquintana I think this is the correct place. *Copy Path* is implemented in this repo: https://github.com/atom/atom/blob/22b1259fdb0c7545aca/menus/darwin.cson#L58

*(happy to be corrected though)*

**Comment by ypresto** [comment]
+1

I'll PR this.

**Comment by acusti** [comment]
This would be very useful. It doesn’t work for me, however. If I assign a custom keyboard shortcut for `editor:copy-project-path`, like:

```cson
'atom-text-editor:not([mini])':
  'alt-ctrl-shift-C': 'editor:copy-project-path'
```

The shortcut doesn’t work (i.e., hitting the keyboard combination does nothing). Tried with a number of different keybindings. It does show up in Keybindings preferences:

![keybindings preferences](https://cloud.githubusercontent.com/assets/517889/12857574/d3ce8688-cbff-11e5-95e7-c9adaa4d6ad3.png)

Also, I would love the described implementation, in which the Copy Project Path command would be added to the Edit submenu, i.e. adding `{ label: 'Copy Project Path', command: 'editor:copy-project-path' }` below https://github.com/atom/atom/blob/master/menus/darwin.cson#L59

-------------

Using Atom 1.4.3

**Comment by NKjoep** [comment]
I confirm, I have the same problem with 1.4.3

**Comment by ypresto** [comment]
It seems not included in 1.4.x. Would be released in 1.5.0.

**Comment by pratyushtewari** [comment]
Even I cannot bind any keyboard shortcut to `editor:copy-project-path`

**Comment by 50Wliu** [comment]
Keybindings are case-sensitive: `C` is equivalent to `shift-c`.  So `ctrl-shift-C` is actually `ctrl-shift-shift-c`, which is impossible.
