### ISSUE TITLE
Page Up and Page Down don't move correctly with the window.

### ISSUE THREAD

**Issue by ehiggs** [atom/atom#8320]
Each page up and page down move the contents of the screen up a full amount but it's offf by one line. For each page down, the cursor also moves down a line relative to the window.

If you open [this file](https://github.com/smparkes/sphinxsearch/blob/upstream-trunk/src/sphinx.cpp) and start at line 1, then hold page down you will see that cursor on the screen creeps down the window until it's off the bottom of the screen instead of holding its position. By line 7968, the cursor is off the screen.

Atom 1.0.0
Fedora 22
Gnome Shell 3.16.3

**Comment by izuzak** [comment]
Thanks for the report, @ehiggs -- I was able to reproduce this:

![](https://cloud.githubusercontent.com/assets/38924/9194798/3b220904-401e-11e5-99c6-4e153a1777f8.gif)

/cc @nathansobo for :eyes:.

**Comment by nathansobo** [comment]
Added it to the list of small interaction issues to fix.
