### ISSUE TITLE
Atom package and install views in settings not showing all installed packages

### ISSUE THREAD

**Issue by gfarrell** [atom/atom#8324]
I was trying to see if linter-pylint was installed on my atom. If I navigate to the packages directory, I can see it. If I run `apm list`, I can see it, but in atom if I search for "linter" in the packages view of the settings panel then nothing shows up, not even the `linter` package, despite them being very obviously installed.

**Comment by izuzak** [comment]
Strange. Can you please reopen this issue [here](https://github.com/atom/settings-view) and provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)? Thanks!

**Comment by mnquintana** [comment]
This might be the same issue as https://github.com/atom/settings-view/issues/591
