### ISSUE TITLE
In handlebars files Atom doesn't color text properly when there is a forward slash in the name

### ISSUE THREAD

**Issue by adam-knights** [atom/atom#8325]
To reproduce:

Create a new test.hbs file with the following two lines:

    {{forms-colors-nicely name="priceManualSwitch" checked=manualPriceChecked}}
    {{forms/colors-nicely name="priceManualSwitch" checked=manualPriceChecked}}

The second line remains all grey (apart from the {{ and }}) whereas 'name' and 'checked' change to orange on line 1 and "priceManualSwitch" to green.

![handlebars-grey](https://cloud.githubusercontent.com/assets/12710362/9199993/819b6e74-403d-11e5-98ba-a2050192ca52.png)

It appears that the / in the component name stops the nice coloring. The / is used in Ember in particular from about version 1.10 to 1.13 to organise components into sub folders.

Version 1.0.5, Windows 7 64bit

**Comment by abe33** [comment]
Hi, the support for handlebars grammar is not provided by a core package, do you mind moving the issue on [alexlafroscia/language-handlebars](https://github.com/alexlafroscia/language-handlebars)?

**Comment by adam-knights** [comment]
This has nothing to do with grammar as far as I can see this is the default behavior of coloring in a fresh install of Atom with no extra packages?

**Comment by mnquintana** [comment]
@adam-knights Can you post the results of `apm list --installed`?

**Comment by adam-knights** [comment]
My mistake - ill post it against https://github.com/Sneagan/atom-handlebars
