### ISSUE TITLE
npm integration

### ISSUE THREAD

**Issue by Daniel15** [atom/atom#8328]
It would be nice to have some npm integration, like [what Visual Studio has now](http://webtooling.visualstudio.com/package-managers/npm/). This is what Visual Studio does:
- Autocompletion of everything in package.json, including npm package names and version numbers.
- Automatically runs "npm install" on save of package.json
- Shows tooltip with info about package when hovering over it in package.json
- Shows installed packages and their dependencies as a tree structure in the IDE

I'm not sure if this is the right place for feature requests, sorry if I'm posting in the wrong area.

**Comment by thomasjo** [comment]
Check out these two community packages:
 1. https://atom.io/packages/npm-install
 2. https://atom.io/packages/npm-autocomplete

The missing pieces would make for great, additional community packages. Hopefully you and/or someone else in the community will step up and implement the missing features.
