### ISSUE TITLE
Atom on Windows Goes to Black Screen on Display Switch

### ISSUE THREAD

**Issue by mbidewell** [atom/atom#8330]
Atom 1.0.5 has developed a bad habit, of when I remove my laptop from my docking station, going to a frame containing only a black screen.  In order to restore operation Atom must be closed and restarted.  I have had this issue with Google Chrome for some time, however Atom had been immune until now.

**Comment by damieng** [comment]
This is most likely a video driver issue given that Chrome also suffers from it.

Atom would likely have been immune until we took a later version of Chroium that enabled DirectWrite hardware-accelerated GPU drawing.
