### ISSUE TITLE
Accidental multiple tab closing --> follow Chrome and Firefox

### ISSUE THREAD

**Issue by mostafaeweda** [atom/atom#8331]
When having many tabs open, one keep accidentally closing some of them because the Xs appear all the time. Atom should mimic what Firefox and Chrome do with many tabs open.

**Comment by izuzak** [comment]
@mostafaeweda I'm not sure I understand the problem you're describing or the change you'd like to see in the behavior. Could you clearly explain, perhaps with step-by-step instructions and a screenshot, what exactly is the problem when you have many tabs open? Also, do you think that a better home for this issue would be the issue tracker for the Tabs package? https://github.com/atom/tabs

**Comment by Ben3eeE** [comment]
Going to close this one out as we have improved the tab close icon recently and no additional information was added.
