### ISSUE TITLE
Open »Project Find Results« in same split pane

### ISSUE THREAD

**Issue by jancborchardt** [atom/atom#8332]
1. Split the editor in two panes, one left one right for example, and focus a document on the right
2. Use Ctrl-Shift-F to find stuff across the project
3. In the results dialog (which will pop up on the right where the focused document was) click on a result

Expected: The file opens up as a tab to the right next of the Project Find Results tab. Instead it opens in the left pane, somewhere completely different.

**Comment by izuzak** [comment]
@jancborchardt Could I trouble you to re-open this on the Find and replace package's repository? Thanks! https://github.com/atom/find-and-replace

**Comment by izuzak** [comment]
Also, just wanted to mention that there's a config option in that package's settings which make project find results always open in the right pane.

**Comment by jancborchardt** [comment]
Thanks, did so in https://github.com/atom/find-and-replace/issues/484
