### ISSUE TITLE
racer.racerBinPath is not set in your config.

### ISSUE THREAD

**Issue by Rodney-Gabriel** [atom/atom#8333]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: Atom Core

### Stack Trace

racer.racerBinPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
     -0:53.9.0 vim-mode:replace (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:53.9.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:51.9.0 vim-mode:find (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:51.9.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:51.5.0 vim-mode:find (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:51.4.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:51 vim-mode:find (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:51 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:50.5.0 vim-mode:find (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:50.5.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:50.2.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:50.2.0 vim-mode:move-to-end-of-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:50.2.0 vim-mode:insert-after (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  8x -0:41.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:19.6.0 blur (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:00.9.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
auto-encoding, v0.4.1
autocomplete-modules, v1.0.0
ios, v0.1.0
language-rust, v0.4.4
racer, v0.16.0
rust-api-docs-helper, v0.5.1
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Seems like a problem with https://github.com/edubkendo/atom-racer -- can you please re-open the issue there? Let me know if I misunderstood.

**Comment by Rodney-Gabriel** [comment]
@izuzak the error that comes up states it likely a bug in Atom thats why i reported it here sir.
![screen shot 2015-08-11 at 2 12 07 pm](https://cloud.githubusercontent.com/assets/13702353/9207862/cf5b1a90-4035-11e5-9ce3-a274c9addefa.png)

**Comment by izuzak** [comment]
> @izuzak the error that comes up states it likely a bug in Atom thats why i reported it here sir.

Yeah, sorry for not explaining, @Rodney-Gabriel -- I think that the fact that Atom core is blamed for the exception is a different bug (see https://github.com/atom/notifications/issues/66), but the exception itself seems related to racer. Can you try defining the config setting mentioned in the exception in you config.cson file and see if that helps? Again, I think opening an issue on racer's repository would be a better idea -- those folks should be able to provide advice.

**Comment by tacone** [comment]
Hello, I had the same issue with Atom 1.0.2. While upgrading to 1.0.9 I suddenly found my rust executable path was wrong. I have no idea if the issue depends on the wrong path or on too old version of Atom, but I'm inclined to think it is the first :-) Fixing the path fixed it for me.
