### ISSUE TITLE
Find in Project caches prior search results

### ISSUE THREAD

**Issue by fungilation** [atom/atom#8338]
For example: ![screenshot 2015-08-11 18 50 00](https://cloud.githubusercontent.com/assets/3803466/9215014/deff6ba8-4059-11e5-9bd1-3dfef03dac26.png)

The search for "rsvpOptions" doesn't search what is intended. It immediately comes up with results of prior search, on "mainGuest". I can force an actual search by changing say, the case sensitivity setting in the Find in Project panel.

I noticed this only today, after updating Atom to 1.0.6. Can't say if this is bug in Atom or some misbehaving package I'm using. (Is there a way on cli to launch Atom with non-core packages temporarily disabled to test?)

**Comment by izuzak** [comment]
This issue was moved to atom/find-and-replace#490
