### ISSUE TITLE
Add Support for Opening .plist Files 

### ISSUE THREAD

**Issue by BigxMac** [atom/atom#8339]
I was working on some object persistence using NSCoder in Swift which produces a .plist file. I can view it using Xcode or quick look on my mac. When I tried opening it in Atom (version 1.05) it recognized it as a "Property List (Old-Style) file, but displayed [this](http://imgur.com/yuDmV7g). It would be nice if Atom supported this for iOS developers.

**Comment by izuzak** [comment]
Thanks for the feedback, @BigxMac. Can you please reopen this over at https://github.com/atom/language-property-list, and explain what you expected Atom to show instead? I think it would be helpful if you could add screenshots from Atom, Xcode, but also some other editor (e.g. what do you see in VIM and SublimeText)?

**Comment by BigxMac** [comment]
Will do! Thanks!

**Comment by nasht00** [comment]
I did not see any issues opened there, so I opened one:
https://github.com/atom/language-property-list/issues/3

However I'm not sure it's related to that package. It's not related to syntax highlighting or snippets, the file simply does not open correctly, you can't see raw text.

In Atom:
![screen shot 2015-08-25 at 10 59 28 am](https://cloud.githubusercontent.com/assets/329834/9461676/d1b04854-4b18-11e5-9013-3b2cee5370db.png)

In TextWrangler:
![screen shot 2015-08-25 at 11 01 10 am](https://cloud.githubusercontent.com/assets/329834/9461679/d83be174-4b18-11e5-9d9a-4777058c36e8.png)

**Comment by izuzak** [comment]
@nasht00 What do you see if you view the file in Vim, for example? What do you see if you run `cat <path_to_plist_file>`?

**Comment by nasht00** [comment]
Added screenshot of each of those in the linked issue.
You are right, looks bad in vim as well.

**Comment by izuzak** [comment]
@nasht00 Yeah, that's because that's the actual content of files (which you can confirm with `cat` or `hexdump`). I'm not familiar with those types of files, but I'm guessing they are interpreted and then displayed in a different way.

**Comment by pudquick** [comment]
Correct.

This is a binary plist, mentioned by Apple in several documentation locations.

Only source code example from Apple I'm aware of is: http://www.gnu-darwin.org/www001/src/DarwinSourceArchive/expanded/CF/CF-299/Parsing.subproj/CFBinaryPList.c

But applications like TextWrangler / BBEdit likely just use native Apple APIs for loading the binary file and then converting it to a XML representation behind the scenes, like:

```objective-c
[NSPropertyListSerialization dataFromPropertyList:plistDict format:NSPropertyListXMLFormat_v1_0 errorDescription:&error]
```
There are several opensource projects out there that implement binary plist parsing functionality in various language (perl, python, etc.)

**Comment by nasht00** [comment]
@izuzak considering the latest comment from @pudquick (Thanks!), would you say this issue should sit at the core `atom` or at the `language-property-list` repository?

**Comment by izuzak** [comment]
@nasht00 I don't think it should be in core atom -- it's not related to core atom, it's rather specific for this type of file, I'd say. Do you think it should be in core atom and can you explain why?

**Comment by nasht00** [comment]
No I don't have any strong opinion, as long as it's fixed somewhere ;)

**Comment by danielbayley** [comment]
You can now download the [plist-converter](https://atom.io/packages/plist-converter) package which handles automatic conversion from binary to XML and back on open/close of `.plist` files.
