### ISSUE TITLE
URGENT: loosing data due to file versions

### ISSUE THREAD

**Issue by gp187** [atom/atom#8341]
This is the 10th time I lost data due to the Atom editor. 
I work with 2 panels open and a lot of file. Each time I restart my activities and re-open the editor, the files are open but most times they are previous version of what I was doing. 

For example now I just lost 12 hours of coding due to Atom!!!!!

It is loading a previous version of the file, which doesn't make any sense because I do not have versions or git. It's on my computer, that's it

Configuration: Ubuntu 15. Atom latest.

**Comment by Zireael07** [comment]
Do you save the files? Do you have the backup before saving on?

**Comment by Davidx7** [comment]
Yes. I save everything all the time. I don't close the editor without saving. 
Even like this it messed up my work, really bad

**Comment by mnquintana** [comment]
Can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Can you post a list of your installed packages? (`apm list --installed`)

**Comment by Davidx7** [comment]
Steps :: 
1) work work work, constantly save everything
2) close the editor knowing everything works properly and is properly saved
3) sleep
4) back to work. Open the editor, surprise! The main file in which I worked is in yesterday morning version and already overwritten on the disk. Can't do anything

**Comment by Davidx7** [comment]
├── angularjs@0.3.0
├── angularjs-helper@0.10.2
├── angularjs-snippets@0.10.18
├── autoclose-html@0.18.0
apm list
├── css-snippets@0.8.0
├── htmlhint@1.1.3
├── language-cuda@0.0.0
├── language-opencl@0.1.1
├── minimap@4.12.2
├── seti-syntax@0.4.0
├── seti-ui@0.7.1
├── travis-ci-status@0.16.0
└── unity-ui@2.1.0

**Comment by Zireael07** [comment]
Davidx7, Windows has something called file versions enabled for some folders. Is there an equivalent on Ubuntu? (It's sorta a rollback to a previous version or two for the folder)

**Comment by Davidx7** [comment]
Unless you install specific software, no. I looked trough the ```~/.atom/storage/``` but no luck. Just older versions

**Comment by alexberry** [comment]
Just to be sure it's not your machine rather than atom, why not test by working in atom, save files etc, then before opening it in atom the next time open it in vim or some other editor. If it's an older version check the date stamp on the file with ls -la to see when it was last saved. If it was before your last save then either a) you didn't save it or b) atom didn't save it. If you suspect the latter then try saving, then while the file is open in atom open it in another editor to double check it's saved.

**Comment by Davidx7** [comment]
If I open them in another editor they are the good version. If I open them in atom, it overwrites and messes things up. 
It's not my machine. It happened on Ubuntu 14, 15 and Windows.

**Comment by mnquintana** [comment]
> If I open them in atom, it overwrites and messes things up. 

Can you be more specific about what you mean by `overwrites`? Do you mean that when you open the files in Atom, old versions are opened? Or do you mean that immediately upon opening files in Atom, those files are overwritten on disk with the old versions of the file?

**Comment by Davidx7** [comment]
If you open the files in another editor, BEFORE opening again Atom you will find the good versions. 
If you open directly Atom it will overwrite them with some other older version, which is random. Not necessary the last save.

What happened today is it replace my current file version with a version from 12hours ago. 
I those 12 hours I saved the file about 50-100 times and it still used an older version

**Comment by mnquintana** [comment]
I'm sorry, maybe I wasn't clear - is Atom saving these old versions to disk (*overwriting* the files on disk) as soon as you open them? Or is it merely opening up and displaying the old versions to you? The distinction here is pretty crucial.

**Comment by Davidx7** [comment]
That I couldn't figure out. It opens the old versions but no indication that it's an older version or original.

Once I managed to reverse it by closing atom and opening again, without touching the files, the reverted to disk versions.

**Comment by Zireael07** [comment]
Can you copy the good versions somewhere so that they don't get lost and check again whether Atom opens the good ones or the old ones? What happens with another editor?

**Comment by mnquintana** [comment]
@Davidx7 It seems to me like Atom isn't correctly serializing the state of this project. Try this:

1. Quit Atom
1. `rm -rf ~/.atom/storage`
1. Reopen Atom

Then see if you can reproduce this issue.

**Comment by nathansobo** [comment]
@Zireael07 do you have `Backup Before Saving` enabled?

![screenshot 2015-08-12 10 11 54](https://cloud.githubusercontent.com/assets/1789/9229483/97b80db4-40da-11e5-8410-b362864cf7da.png)

**Comment by Davidx7** [comment]
That version does not exist in my Atom. I'm running on Ubuntu 15.04, latest version available. 
I have 
>> Auto Indent
>> Auto Indent On Paste
>> Confirm Checkout HEAD Revision

The backup option is totally missing. 
A version thing?

**Comment by mnquintana** [comment]
@Davidx7 Can you try the steps I outlined above and report if they work for you?

> 1. Quit Atom
1. `rm -rf ~/.atom/storage`
1. Reopen Atom

> latest version available. 

What version is that, exactly? If it doesn't have the backup option then it's not the latest version. How did you install Atom?

**Comment by Davidx7** [comment]
You are right. It's not. Wasn't it supposed to give me the update message ?
I'm running 1.0.4.
I install from atom.io downloading the .deb
I'm updating now. 

Will also do what you just said and see if happens again.
It probably will. It was always a random event, but seems to be more often when I'm doing heavy work. I work with big script files, lots of lines, saves etc.

**Comment by Davidx7** [comment]
Updated Atom and managed to replicate the bug. 
Good thing I had saved my file. 
If before closing the editor, you close the file, the error doesn't happen. Only by letting the workspace open

**Comment by mnquintana** [comment]
@Davidx7 Did you try the steps I outlined above? I wouldn't expect updating Atom to fix this.

**Comment by joejeet** [comment]
+1 Similar issue. Lost half of the data in script. Didn't choose the backup data option as well. So, have to write the script again. Try above mention steps, still same. I'm on v1.0.15

**Comment by ansorensen** [comment]
+1 Similar issue, on Mac.  I have been saving as I go, but I lost several days of work after restarting my computer; somehow Atom restored a version of a couple of files that are several days old.  Other files are up to date.  Do not have backup before save option enabled... although I'd be hard pressed to trust that option if Atom is somehow reverting my files old backups even _without_ that option enabled.

**Comment by bastiao** [comment]
This also happened to me.
I've link a folder in a git repository linked to another folder (outside) and it is also a git repository.

**Comment by theyowza** [comment]
I also experienced this on a Mac. I saved at about 6PM yesterday and reopened the script today on Atom, now as an older version. Somehow the saved script reverted to the older version. Luckily I had a file recovery program but this issue is pretty disconcerting. I'm on 1.8.0.

**Comment by joeguinness** [comment]
I think a similar thing happened to me. Yesterday I opened a file I had worked on a few weeks ago. When I opened it in atom, the blue dot next to the filename was active, looking like it was unsaved. So I hit save, and I think that made me lose some work. It seems like it reverted to a cached version of the file. Is there any way to recover the overwritten file?

**Comment by jwyuen** [comment]
This constantly happens to me as well
