### ISSUE TITLE
Idea: make restoring from cache easier

### ISSUE THREAD

**Issue by andreis** [atom/atom#8342]
I have to start by saying that `~/.atom/storage` just saved my ass after I overwrote an untracked file in a project, and I'm very grateful for that! Would it be a worthwhile idea to implement a restore feature for people who do dumb things like me?

Proposal:

``` bash
# Lists projects saved, and last save timestamp
atom-restore --list-all
# Lists files in a project, and last save timestamp for each file
atom-restore list {project_name}
# Restores the project files in the current folder
atom-restore {project_name} [-o dest_dir]
```

**Comment by Davidx7** [comment]
How did you manage to do that? I just lost a file like that. How can I restore?

**Comment by andreis** [comment]
Well, the first step is to not open that project again with Atom. Then, go to `~/.atom/storage` and you'll have  bunch of JSON files that start with `editor-`. If you're lucky one of them will have your file open, albeit all newlines and tabs are escaped, so you might want to write a quick Python script or something.

**Comment by adarshTS** [comment]
I have recovered to my old state by undoing which and that old state file was saved the previous day, so is it possible to go back to the changes that I have made on the present day? redo doesn't respond
