### ISSUE TITLE
Cannot scroll/move cursor to the end of the line when using the "Base16 Tomorrow Dark" syntax theme.

### ISSUE THREAD

**Issue by cosmix** [atom/atom#8343]
### Description:

With soft-wrap disabled and a long line of text that exceeds the available viewport width of the editor pane, erroneous behaviour is observed when attempting to go to the end of the line either via the (bottom) scroll bar or through the doesn't work properly and requires a repeat invocation to work as expected.

### Steps to reproduce:

You can reproduce this either using the scroll bar or using a keyboard command (e.g. `editor:move-to-end-of-screen-line` with whatever key shortcut applies on your platform/configuration).

1. Open Atom with an empty file. Make sure soft wrap is disabled.
2. type a long string on a single line --- your string should exceed the width of the editor viewport.
3. Press <kbd>End</kbd> or try to scroll (using the scrollbar at the bottom of the editor pane) as far right as you can.

### Actual results:

In the case of the end-of-line keyboard shortcut, the cursor does move to the end of the line, but both cursor and end of line content is not visible.

In the case of the scrollbar, you cannot go past a point which is just before the end of the line. The cursor remains hidden, as does the end of the line.

### Expected results:

In the case of the scrollbar event, you should be able to actually read the content at the end of the line, with some appropriate padding.

In the case of the keyboard commands, you should see both end of line content and the cursor blinking there.

### Notes:

* Repeating the `editor:move-to-end-of-screen-line` command one more time does move to the end of the line. I couldn't find a way to achieve this using the scroll bar.
* This issue was consistently reproducible on OS X.

**Comment by izuzak** [comment]
Thanks for the detailed report, @cosmix, but I'm having trouble reproducing that exact behavior. Can you share which version of Atom you're using, which version of OSX, which type of Mac you're using (with retina screen?), and a GIF which clearly demonstrates the problem? (you can record one using [this tool](http://www.cockos.com/licecap/))

The behavior which I observed was this:

1. Opened a new file, soft wrap disabled
2. Triggered the `lorem` snippet to get a really long line
3. Positioned the cursor at the end of the line using `editor:move-to-end-of-screen-line`. 
4. Observed that the cursor was definitely shown, but not completely -- seems like half of it went over the edge and is not visible. The "invisible" character marking the end of the line is not visible.
5. Triggering `editor:move-to-end-of-screen-line` again does not change anything.
6. Using the horizontal scrollbar gives the same behavior.

![](https://cloud.githubusercontent.com/assets/38924/9227434/ce4c7b7e-4113-11e5-9681-5330a6602c10.gif)

Atom 1.0.7-8d68680, OSX 10.10.4, MacBook Pro with a retina screen.

/cc @nathansobo for thoughts

**Comment by cosmix** [comment]
Hello @izuzak. No retina screen here, OS X 10.0.4. Atom 1.0.6-f7a60c0 (release).

Here's a GIF showcasing the issue. In case I wasn't clear enough in my report, you *can* get to the end if you explicitly click with your mouse or move the cursor with the arrow keys. It doesn't work properly using <kbd>End</kbd>/<kbd>Command</kbd>+<kbd>&rarr;</kbd> unless you do it twice. And it doesn't work at all by dragging the scrollbar.

Here's a capture from my box.

![atom-bug](https://cloud.githubusercontent.com/assets/76265/9228793/ba6b06ac-4122-11e5-83c7-30986757c507.gif)

Let me know if there's something more I can help you with.

**Comment by izuzak** [comment]
Thanks @cosmix :bow:

> In case I wasn't clear enough in my report, you *can* get to the end if you explicitly click with your mouse or move the cursor with the arrow keys. It doesn't work properly using <kbd>End</kbd>/<kbd>Command</kbd>+<kbd>&rarr;</kbd> unless you do it twice. And it doesn't work at all by dragging the scrollbar.

Yeah, that was clear. Strangely, I'm unable to reproduce that -- behavior is the same for me regardless of whether I use arrow keys, execute the `editor:move-to-end-of-screen-line` command or use the scrollbar.

Can anyone else reproduce this, just in case I'm missing something? /cc @atom/feedback

**Comment by cosmix** [comment]
Ok, I tried getting rid of .atom, after keeping a backup copy of course and discovered the following: this issue, as shown above, is way more pronounced using 'Base 16 Tomorrow Dark'. It is much less of a problem using other themes, where, although the cursor does remain nearly out of sight (especially when using packages like minimap), the scrolling behaviour is much closer to my expectation. So, if anything, this might be related to the theme and not the core editor per se.

**Comment by cosmix** [comment]
I updated the issue title to better match the comments following the description, that is that the issue is largely confined to the "Base16 Tomorrow Dark" syntax theme, although the underlying cause may be due to a bug in the editor rendering code. I have consistently reproduced this issue on other OS X machines, including a Retina MacBook Pro using the latest Atom release (1.0.7)

**Comment by cosmix** [comment]
Confirmed as caused by Base16 Tomorrow Dark syntax them and fixed in my repo (viz. pull request above). Closing issue.
