### ISSUE TITLE
'Find in Project' returns no results

### ISSUE THREAD

**Issue by SeanJM** [atom/atom#8344]
'Find in Project' returns no results when opened for the first time. Once, opened results appear.
To show results, toggle 'Use RegExp' or any of the other toggles.

**Comment by izuzak** [comment]
Thanks for the report. Yeah, I've seen this too -- it's already mentioned in https://github.com/atom/find-and-replace/issues/373#issuecomment-130194295. If you'd like, please reopen this on the package's issue tracker: https://github.com/atom/find-and-replace/issues/373.
