### ISSUE TITLE
Checkable checkmarks in packages installer

### ISSUE THREAD

**Issue by rugk** [atom/atom#8349]
I really like this but I don't think that's intentional: :smiley: 
![checkablecheckmarks](https://cloud.githubusercontent.com/assets/11966684/9233626/6b85f49a-4134-11e5-8b67-41010fc75712.gif)
Example: https://github.com/Azakur4/autocomplete-php

The issue in text: In the packages install part you can select/deselect the checkboxes.

Windows 7
Atom 1.0.6

**Comment by maxbrunsfeld** [comment]
Ha, good catch. Could you move this issue to https://github.com/atom/settings-view?

**Comment by rugk** [comment]
Done. Sorry didn't know that there was a more specific repo.
Moved to: https://github.com/atom/settings-view/issues/628
