### ISSUE TITLE
Find in Project initially returns no results in 1.0.6

### ISSUE THREAD

**Issue by bradbeck** [atom/atom#8351]
After updating to 1.0.6, I noticed that Find in Project initially returns no results for a search that I expect to return many results. After waiting several minutes and executing the search again, I finally see the results I expect.

If it is indexing or something behind the scenes, then I think the user should be informed that is what is happening and not simply told that the search returned no results.

Or in some cases it will pop up the results from a prior search that did return results. e.g. I search for "component" but I'm presented with the results of a prior search for "immutable".

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace? Thanks!

Also see https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.
