### ISSUE TITLE
Autocomplete-plus removes options upon typing last character

### ISSUE THREAD

**Issue by Anfa-am** [atom/atom#8353]
When typing  something like 'div' the options disappear as soon as you type the 'v'. Same with JS, typing 'log' to autocomplete to console.log(); only works if you type 'lo' and hit enter.

Using Atom 1.0.6 with autocomplete-plus 2.19.0

**Comment by benogle** [comment]
This is intentional https://github.com/atom/autocomplete-plus/pull/547 Though in the case of snippets it might be strange. Closing in favor of https://github.com/atom/autocomplete-snippets/issues/58
