### ISSUE TITLE
Windows 10 - Crashes

### ISSUE THREAD

**Issue by genio** [atom/atom#8355]
## Apologies in advance

I apologize if this has already been reported, but I couldn't find it anywhere.  Please close this issue if that's the case.  It's an oddball case.

## Platform and Version

**Platform** Windows 10
**Version** Atom 1.0.7
**Safe Mode?** Yep, that crashes too.
**Remote FileSystem** SMB Share from Mac machine (Yosemite) (as a mapped drive or as just the share itself).

## Steps to Reproduce

- Create a samba (SMB) share on a Mac machine.
- Navigate to that share on your Windows machine and authenticate.
- Tell Atom.io to open a directory within that share.
- With Windows Explorer, change a file name within the share, or simply re-navigate to the share by going to a directory above the one you opened with Atom.io and then back into the opened directory.  There are many, many things you can do at this point.
- Atom.io crashes.

## Other Tests

My situation might be a bit *unique* so again I will apologize if it makes it hard to debug. I have tested this same setup using a linux samba share as well as a Windows file share and Atom.io behaves very well and ***never crashes*** in those setups.  It might be something to do with how the Mac (Yosemite) samba shares are created.

All shares I used required authentication different from that of my Windows workstation.  All shares were on an AD domain using domain credentials.

**Comment by Kradirhamik** [comment]
Hi,

I'm not sure if this is related but I'm getting this since yesterday: https://goo.gl/9b6N13

I have tried reinstalling, restarting, admin mode... Nothing works!


Best,
Ivo

**Comment by batjko** [comment]
This may be a duplicate of https://github.com/atom/atom/issues/6974
Have a look there and confirm, if you can?

On a side note, "Atom.io" is the website. The editor is just called "Atom". ;)

**Comment by genio** [comment]
#6974 certainly seems similar (if not an exact match) to this issue, but my testing couldn't reproduce the problem from any network share other than from a Mac.  #6974 is unclear as to which platform the share is coming from.

That's the only difference I see and that being said, I'll go ahead and close this issue as having two open issues for seemingly the same thing is surely of no help to you guys.

Sorry about that.  I would have just commented on the other one had I seen it prior to inserting this one.  Oops!
