### ISSUE TITLE
Launching atom on 64-bit Debian 8.1 fails due to erroneous calls to files in /tmp

### ISSUE THREAD

**Issue by fusion809** [atom/atom#8360]
Hi, 

I installed Atom from source initially using source code found [here](https://github.com/atom/atom/archive/v1.0.7.tar.gz) instead of using git to get the code (as it saves an awful lot of HDD space), with absolutely no error messages. I installed Node.js from source code too (using [this tarball](https://github.com/joyent/node/archive/v0.12.7.tar.gz)), also without errors. But whenever I run `atom` I get the error:

`nohup: failed to run command ‘/tmp/user/1000/atom-build/Atom/atom’: No such file or directory`

Then I tried to use the Debian package at [here](https://github.com/atom/atom/releases/download/v1.0.7/atom-amd64.deb) to install Atom (via running `sudo dpkg -i atom-amd64.deb`) but yet again running `atom` gives:

`nohup: failed to run command ‘/tmp/user/1000/atom-build/Atom/atom’: No such file or directory`

Thanks for your time,
Brenton

**Comment by thomasjo** [comment]
Can you provide the exact commands you used to build and install Atom (for both approaches)? Essentially we need a list of reproducible steps to figure out what might be going wrong.

**Comment by fusion809** [comment]
OK, well they're pretty much identical to that found in the official documentation (like [linux.md](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md)), but here we go. 

Source build:
```sh
ver=1.0.7
sudo apt-get install -y build-essential git libgnome-keyring-dev fakeroot
wget -c https://github.com/atom/atom/archive/atom-v$ver.tar.gz
tar -xzf atom-v$ver.tar.gz # extracting tarball contents
mv atom-$ver atom #renaming the atom source code directory
cd atom
script/build
sudo script/grunt install
```

Binary install:
```sh
wget -c https://github.com/atom/atom/releases/download/v1.0.7/atom-amd64.deb
sudo dpkg -i atom-amd64.deb
```
