### ISSUE TITLE
Better detection of git repository inside a symlink dir

### ISSUE THREAD

**Issue by omrihar** [atom/atom#8363]
I tend to have symbolic links to some of my subdirectories in a large repository. When I open atom from the symlink directory it does not detect that the file is part of a project. As a result, packages such as `git-plus` also do not detect that I am actually inside a git repository.

Git provides the command `git rev-parse --show-toplevel` which I think is a more robust way of detecting a git repository than traversing the tree to find the `.git` folder. There is also `git rev-parse --git-dir` to find the path to the `.git` directory if this is needed. Most things `git` I know (bash terminal with git status line and `vim-fugitive` simply detect I'm in a repository irrespective if there is a `.git` subdirectory in the parents of the directory I'm in) and I think it will be a really neat feature if `atom` detected the fact that the files it's editing are being tracked by git no matter where it finds them.

I should mention I'm on a linux (arch linux) using atom version 1.0.3.

I would submit a pull request but I'm not very good with coffee script and I'm afraid it might affect many parts of atom which I'm not aware of.

**Comment by phord** [comment]
Related to (but different from) #2203

**Comment by ayberkozgur** [comment]
I have the same issue on atom 1.9.4 but I don't see how #2203 is related to this; it is not problem that the top project directory doesn't contain `.git/`, it is just symlinked to somewhere else that does contain `.git/`.

**Comment by phord** [comment]
It is related in that the part of Atom that detects the .git repo existence is broken in the same way. Any packages which rely on the same mechanism will need hanle both cases, too.  But it is different, as I said.  So if someone thinks they have this bug or that one, they can read the descriptions and determine which is their problem.

**Comment by FelixBrendel** [comment]
I also have the same issue, is there a workaround?
