### ISSUE TITLE
Better default key bindings on Mac

### ISSUE THREAD

**Issue by andreis** [atom/atom#8364]
This is what I'm used to on Mac, why is it not the default?

```coffeescript
'atom-text-editor':
  'alt-left': 'editor:move-to-previous-subword-boundary'
  'alt-right': 'editor:move-to-next-subword-boundary'
  'alt-delete': 'editor:delete-to-end-of-subword'
  'alt-backspace': 'editor:delete-to-beginning-of-subword'
  'alt-delete': 'editor:delete-to-end-of-subword'
  'alt-shift-left': 'editor:select-to-previous-subword-boundary'
  'alt-shift-right': 'editor:select-to-next-subword-boundary'

```
And this is nice to have:

```coffeescript
  'alt-up': 'editor:move-to-beginning-of-previous-paragraph'
  'alt-down': 'editor:move-to-beginning-of-next-paragraph'
  'alt-shift-up': 'editor:select-to-beginning-of-previous-paragraph'
  'alt-shift-down': 'editor:select-to-beginning-of-next-paragraph'
```

**Comment by cosmix** [comment]
Although you may very well change your keybindings to conform to Apple's standard behaviour and guidelines, I tend to agree with you @andreis. Atom has, what you might call call, unconventional keybindings on OS X; one argument in favour of the current situation is that it is consistent across platforms. Similar issues have been reported before, especially with regard to OS X, see #7349 for example. But this is not about the Mac, it's about policy: observe platform conventions and guidelines or default to your own, independent and cross-platform scheme. Until now Atom is straddling the line between the two and it can sometimes be frustrating.

**Comment by andreis** [comment]
Thank you for your explanation @cosmix. You raise a valid point that leads me to an idea. Why not have multiple\* keybindings that you can easily switch to? This would actually make a good plugin.

\* user-submitted? although that would involve additional infrastructure overhead for voting, etc.

**Comment by cosmix** [comment]
It could certainly work as a plugin. I doubt the the github/atom folks would do this as part of the core package – feature creep and all… =)
