### ISSUE TITLE
Copy-paste doesn't work properly with Unix-style line endings under Windows

### ISSUE THREAD

**Issue by kovbal** [atom/atom#8365]
Copying (Ctrl+C-Ctrl+V) from a file with Unix-style line ending (LF) doesn't work as expected, since line endings are _preserved_ on the clipboard.

This causes a wide range of issues:
- you can't paste text in an application that doesn't handle LF (notepad for example, but if you're using vim over PuTTY that also doesn't work)
- even if the other app handles LF, you have to be consistent, so you can't paste text from an CRLF file into a LF one or vice versa

This issue is briefly discussed in #2822, and it is the reason of #5808.

**All other editors convert line endings in text placed on the clipboard** (Sublime Text, jEdit, etc.), so in this regard Atom behaves rather strangely compared to other editors.

The proposed solution in #2822 (configurable line endings) is insufficient since it's based on the assumption that _all_ files edited by the user are using the same line ending.
For example, if I've got a file with LF line endings and I'd like to use copy-paste, then I **have to convert it to CRLF** and then **copy the text** I want, and **then convert it back to LF** to preserve the original format. I wouldn't call editing LF files on Windows a rare use case, especially among Atom's users.

Atom should convert any text's line ending to the platform's native line ending _before_ it is placed on the clipboard. This conversion should only be done on the content that is placed on the clipboard—the text in the buffer should not be changed.

**Comment by kovbal** [comment]
I just checked, and this still affects the released version (1.0.9).

**Comment by maxbrunsfeld** [comment]
I'm not quite understanding exactly what behavior you're suggesting. What line-ending should we convert to? Always use the platform's default line ending?

**Comment by kovbal** [comment]
Text placed _on the clipboard_ should be converted to the platform's native line-ending.

Currently, what is placed on the clipboard has exactly the same line-ending that the open buffer has. If you substitute "line-ending" with "character encoding" you see how insane this is. The clipboard's contents must be normalized so other applications can use it.

So what I suggest is that any text's line-ending should be converted to the platform's native line-ending _before_ it is placed on the clipboard. The text in the buffer should not be changed, only what is placed on the clipboard.

I hope this clarifies what I meant.

**Comment by kovbal** [comment]
This issue is still present in the latest release version, so I'd like this issue to remain open.

See my example:
 ![atom-line-ending-bug](https://user-images.githubusercontent.com/6624494/30004100-31668694-90c9-11e7-807d-c98f186ed94c.gif)

**Comment by wdscxsj** [comment]
Coming from Microsoft/vscode#22688, I feel this behavior quite unnatural. Rekindles my love for Sublime Text.

Why not give it a configurable option to make everybody happy? `editor.copiedEol`: `asIs`, `osNativeAtYourOwnRisk`, `CRLF`, `CR`, `LF`.

**Comment by AnandLaddha** [comment]
Any updates on this issue?

**Comment by maxbrunsfeld** [comment]
👋 We definitely see this as a legitimate issue, but to be explicit, it's not super high priority for us because of relative amount of feedback that we've heard about it, relative to other issues. We would definitely be open to a good PR that addresses it, but probably won't be working on it ourselves in the near term. Apologies for our lack of resources.

**Comment by ccorcos** [comment]
I'm a little confused about this. Doesn't the windows operating system or the application handle these conversions from LF to CRLF for you? Websites, for example, are built with LR, not CRLF. Is Chrome converting these LF endings to CRLF endings whenever you copy text from a website?
