### ISSUE TITLE
Atom not showing correct folders

### ISSUE THREAD

**Issue by Cuel** [atom/atom#8366]
This happend for me today

![Problem](http://i.imgur.com/BNFCFpi.png)

It's the same folder but I cannot get the correct folders to show up

I can not create already existing folders. I can create new folders and they'll show up

![Problem](http://i.imgur.com/RDyKUaZ.png)

The folders that do not show up are deleted by Gulp/Rimraf after every edits in \client.
```javascript
gulp.task('scripts', function () {
  rem('public/js/**/*', function () {
    gulp.src(['client/js/**/*.js'])
      .pipe(sourcemaps.init())
      .pipe(uglify({mangle: true}))
      .pipe(sourcemaps.write())
      .pipe(gulp.dest('public/js'))
  })
})
```

What I've tried:
- Restarting atom
- Moving the public folder from the project, atom will show that it is moved (not visible anymore). Once I move it back it looks like the above.

**Comment by maxbrunsfeld** [comment]
Do you have a `.gitignore` file?

**Comment by Cuel** [comment]
Oh, yeah. wasn't aware atom removed those from the view. This can be closed.
