### ISSUE TITLE
Settings don't open after automatic updade

### ISSUE THREAD

**Issue by rsvargas** [atom/atom#8367]
I use to leave the editor opened for several days. 

Every time there's a automatic update, the settings view do not open anymore until I restart the software..

The developer view shows un uncaught exception:
I've not copied the exception, but this was the file that was not being found:
`C:\Users\MY_USER_NAME\AppData\Local\atom\app-1.0.5\resources\app.asar`

**Comment by maxbrunsfeld** [comment]
Does restarting Atom fix the issue?

**Comment by rsvargas** [comment]
Yes, it does!

**Comment by rsvargas** [comment]
This issue does not happen in the newest releases.
