### ISSUE TITLE
Syntax highlighting issue for PHP language

### ISSUE THREAD

**Issue by TreyTaylor1997** [atom/atom#8368]
Hi all,

weird issue here, when double-clicking a variable ($var) it will highlight the whole thing, instead of excluding the $.

I raised it on discuss.atom.io (http://discuss.atom.io/t/double-click-highlights-whole-of-variable-in-php/18625/6).

^above link has full details

Thanks,
Trey

**Comment by kevinsawicki** [comment]
This is intentional and was changed in https://github.com/atom/language-php/pull/75

You can modify this behavior by editing the `Non Word Characters` value in the settings page for the `Language Php` package.

This will be available from the Packages section of the Settings view.

**Comment by TreyTaylor1997** [comment]
ahh last time I tried that it didn't seem to save my specified characters! Thanks! :)
