### ISSUE TITLE
Typing the word test causes a black box to paint over content

### ISSUE THREAD

**Issue by oleersoy** [atom/atom#8370]
![image](https://cloud.githubusercontent.com/assets/1163873/9254103/3e2eab7c-41a7-11e5-97b9-e7a3f4f1ab88.png)

The screen shot shows the black box (Right below `src.test.html`).  It also locks up the cursor and does not allow it to move forward.  If I move backwards the black box disappears.

**Comment by izuzak** [comment]
@oleersoy Which version of Atom are you using and can you reproduce this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by oleersoy** [comment]
@izuzak I'm using 1.0.7 and it does not happen in safe mode.

**Comment by izuzak** [comment]
@oleersoy Sounds like a problem related to one of the packages you have installed. Recommendation: try disabling packages one-by-one to figure out which one it is an report the problem on that package's issue tracker.

**Comment by oleersoy** [comment]
OK - Will do.  Thanks.
