### ISSUE TITLE
Margin missing on available update

### ISSUE THREAD

**Issue by coppolaemilio** [atom/atom#8371]
When you have a small screen (or split panes) the buttons stack and there is no margin separating them from the rest, so it looks weird:

This is under Settings > Updates

![screen shot 2015-08-13 at 5 43 39 pm](https://cloud.githubusercontent.com/assets/2206700/9256138/1719a590-41ee-11e5-98b8-5371f156f0dd.png)

Adding this margin to that *.btn-group* fixes the issue
```css
margin: 5px 0 10px;
```
![screen shot 2015-08-13 at 7 10 36 pm](https://cloud.githubusercontent.com/assets/2206700/9256293/0326e4d4-41ef-11e5-8ce9-0175a0ddac76.png)

**Comment by mnquintana** [comment]
Thanks for the report! Would you mind reopening this on https://github.com/atom/settings-view? Thanks!

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues

**Comment by coppolaemilio** [comment]
Thanks! Will do!
