### ISSUE TITLE
Empty split panes suddenly not being destroyed

### ISSUE THREAD

**Issue by tylerFowler** [atom/atom#8372]
I've noticed recently (right around the time of the 1.0.6 release) that when I split a file in a new pane, after I close all windows in that pane the pane will still exist. This leaves no 'x' button to close it and I have to resort to `cmd+w` in order to close it and cause the other panes to fill in that space. Whereas before closing all windows in a pane would cause the pane to be destroyed, this also happens even in safe mode so I assume it's a change in core Atom, though whether it was intentional I'm not quite sure.

**Comment by benogle** [comment]
There is a setting in the core settings: 

![screen shot 2015-08-13 at 2 05 36 pm](https://cloud.githubusercontent.com/assets/69169/9261679/636aea28-41c4-11e5-86b4-f6268b4d2d6f.png)

Is this checked or unchecked for you?

**Comment by tylerFowler** [comment]
Ah, it seems it is unchecked. I'm assuming this was added? If so it might be less confusing to have it checked by default. Thanks!
