### ISSUE TITLE
Add classes for unsaved changes in the editor?

### ISSUE THREAD

**Issue by Yuudaari** [atom/atom#8378]
Currently, Atom supports line classes when a line has git modifications/additions, etc, but doesn't have classes for when it simply has unsaved changes.

When you've deleted lines, it should have a `.removed` class on the line prior to the lines removed.
When you've edited a line, it should have a `.modified` class on it
And finally, when you've added a new line, it should have a `.new` class on it

Knowing git changes is definitely a helpful thing to have, but it's not anywhere near as important (to me, at least) as knowing changes before I commit to a file save. =)

**Comment by Zireael07** [comment]
Great idea.
