### ISSUE TITLE
stack trace in spec window should be hyperlinked

### ISSUE THREAD

**Issue by jacekkopecky** [atom/atom#8383]
It would be great if file pointers in reports of failed specs were hyperlinked so that clicking on them opens the file on the right line. For example, I'd love a hyperlink on this:

```
at operators-spec.coffee:259:32
```

in the screeshot:

<img width="408" alt="screen shot 2015-08-14 at 15 09 43" src="https://cloud.githubusercontent.com/assets/807315/9275682/aca237c8-4296-11e5-86c1-98e3353c1f02.png">

**Comment by abe33** [comment]
:+1: I would like to see this feature in Atom too!
