### ISSUE TITLE
Keyboard shortcut to hide/toggle find/find in project

### ISSUE THREAD

**Issue by joshuaterrill** [atom/atom#8388]
As atom is right now, when you press Ctrl+F to find or Ctrl+Shift+F to find in project, pressing those buttons again does not get rid of the find/find in project area. From what I've seen, in most editors you are able to toggle the visibility of find with the same keyboard shortcut.

**Comment by eshyunsoo** [comment]
It doesn't seem to do it for Chrome, IE, Notepad, WebStorm, Eclipse and Sublime txt editor on OSX. 'ESC' seems to close it for all.

**Comment by benogle** [comment]
Thanks @eshyunsoo. 

You can remap this to toggle if you'd like. 

```coffee
'.platform-win32, .platform-linux':
  'ctrl-F': 'project-find:toggle'
  'ctrl-f': 'find-and-replace:toggle'
```

**Comment by joshuaterrill** [comment]
Thanks!
