### ISSUE TITLE
There are many bugs in the Atom

### ISSUE THREAD

**Issue by oknixus** [atom/atom#8391]
1.Shortcuts is very chaotic, can be covered.
2.Custom shortcuts or shortcut key mapping range can be infinite

**Comment by batjko** [comment]
I assume you're talking about key mappings?
I'm afraid you'll have to be a bit more explicit. What do you mean by "chaotic" and "infinite"?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8391#issuecomment-131313319. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
