### ISSUE TITLE
Update packaged Node.js

### ISSUE THREAD

**Issue by glen-84** [atom/atom#8395]
The packaged version of Node.js (0.10.35.0) is [insecure](http://secunia.com/advisories/65232), please update it to version 0.10.40 (at least).

Question: I see two instances of Node.js installed for Atom – why are previous versions not removed when updating the software?

**Comment by thomasjo** [comment]
The version of Node.js you are referring to originates from [apm](https://github.com/atom/apm). As part of the effort to get Atom running on Electron, we're working on updating apm as well. Part of that work involves updating its Node.js to v0.12.7.

For the relevant PRs see https://github.com/atom/atom/pull/7877 and https://github.com/atom/apm/pull/409.

**Comment by glen-84** [comment]
Thanks, but both versions appear to be from apm:

`C:\Users\Glen\AppData\Local\atom\app-1.0.2\resources\app\apm\bin\node.exe` (previous version)
`C:\Users\Glen\AppData\Local\atom\app-1.0.7\resources\app\apm\bin\node.exe` (current version)

**Comment by batjko** [comment]
@glen-84 Those are two different instances of Atom (v1.0.2 and v1.0.7 respectively). They do not interfere with each other and you are free to remove the old one.

**Comment by glen-84** [comment]
@batjko Ya, my question was "why are previous versions not removed when updating the software?".

**Comment by batjko** [comment]
Which is another question entirely, as you asked about node, and it's Atom does keeps old versions around, not node. 
Squirrel is supposed to clean up previous versions (I think up to the last one or two), but I have noticed as well that this only works sporadically.

**Comment by glen-84** [comment]
Sorry, I phrased the question poorly. By "updating the software", I was referring to updating Atom.
