### ISSUE TITLE
Can atom display like this?

### ISSUE THREAD

**Issue by agileago** [atom/atom#8398]
<img width="882" alt="qq20150816-1 2x" src="https://cloud.githubusercontent.com/assets/11799110/9291428/abddbc0c-43f1-11e5-9b6b-e461319cc500.png">

background is transparent? who can tell me? i think it's fantastic

**Comment by mnquintana** [comment]
Closing in favor of https://github.com/atom/atom/issues/7439

**Comment by 1j01** [comment]
See previous [discussion here](https://discuss.atom.io/t/background-transparency/1005) about background transparency and https://github.com/atom/electron/issues/381

**Comment by agileago** [comment]
thanks
