### ISSUE TITLE
pane.observeFlexScale documentation error

### ISSUE THREAD

**Issue by mrodalgaard** [atom/atom#8401]
[pane.observeFlexScale](https://github.com/atom/atom/blob/master/src/pane.coffee#L95) description seems to be off. The callback is invoked when pane is resized and its argument is a Number representing the panes `flex-grow`; ability for a flex item to grow if necessary.

It looks like a copy-paste error from `pane.observeItems`.

Also it wouldn't hurt to add a comment to [pane.onDidChangeFlexScale](https://github.com/atom/atom/blob/master/src/pane.coffee#L92), that the panes current flex can be extracted using `pane.getFlexScale()`.

I can create a PR if everybody agrees.

**Comment by maxbrunsfeld** [comment]
Yeah, thanks for noticing that. A PR would be much appreciated!
