### ISSUE TITLE
Dragging folder(s) into the search input should add the path(s)

### ISSUE THREAD

**Issue by mrtnbroder** [atom/atom#8402]
It would be a nice feature to allow dragging & dropping of folder(s) into the search input for a better user experience.

![allow-drag-n-drop](https://cloud.githubusercontent.com/assets/1118826/9295128/77034f84-4463-11e5-883d-3b54d4103bf9.gif)

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tree-view? Thanks!

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.
