### ISSUE TITLE
Rendering errors: scoped character widths getting incorrectly assigned to zero

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#8404]
I got into a state where certain scoped character widths were getting set to zero.

I'm not sure how to get back into this state. I was editing [this C file](https://github.com/maxbrunsfeld/tree-sitter/blob/master/src/runtime/parser.c), I had folded some text, and I was using both of the `One Light` themes, with the `Source Code Pro` font.

For one scope, all of the assigned character widths were zero. For another scope, it was just one character.

``` js
b = atom.workspace.getActiveTextEditor().displayBuffer

// this scope had all zero widths
b.charWidthsByScope["source.c"]["meta.function.c"]["meta.block.c"]["storage.type.c"].charWidths
{b: 0, o: 0, l: 0, i: 0, n: 0}

// for this scope, just the 'u' character had zero width
b.charWidthsByScope["source.c"]["meta.function.c"]["entity.name.function.c"].charWidths["t"]
8 
b.charWidthsByScope["source.c"]["meta.function.c"]["entity.name.function.c"].charWidths["u"]
0
```

/cc @as-cii @nathansobo has anything changed with measurement recently?

**Comment by nathansobo** [comment]
Nothing. I can't wait to get onto a new measurement approach. We need it badly.
