### ISSUE TITLE
Persistent Replace All tooltip

### ISSUE THREAD

**Issue by johnnyreilly** [atom/atom#8408]
Hi,

I love using atom - well done!  

I've just noticed a problem which affects me when I'm attempting to find and replace in a single file (using CTRL+F key binding).

After you've hit "Replace All" to replace all instances within a file the button becomes disabled and the tooltip **fails to disappear**.  It hangs around and obscures the buttons above it:

![persistenttooltip](https://cloud.githubusercontent.com/assets/1010525/9303182/3cfe5d9e-44d4-11e5-9bf3-3a96255b7663.jpg)

The only way to get rid of it (it seems) is to change the content of the "find" input so it matches something in the current file. Then the "Replace All" button becomes enabled once more and the tooltip stops persisting.

I'm using Windows 8.1.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace? Thanks!

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Comment by johnnyreilly** [comment]
[Done!](https://github.com/atom/find-and-replace/issues/501) - apologies for raising in the wrong place.
