### ISSUE TITLE
Ability to open file in new tab multiple times

### ISSUE THREAD

**Issue by foxx** [atom/atom#8409]
There is a neat little feature in ST called "New View for File", which basically opens the file a second time in a new tab. Atom Editor has support for this by "splitting" the view, but this isn't always the desired behaviour.

For example, if I have two panes already split and all I want to do is create a new view of a file, then I'd have to split then drag the file back out to destroy the newly created pane.

There should be an option to just open the file in a new tab, in the same pane which it exists in.

**Comment by alexchandel** [comment]
4tr, `New View into File` in ST does not split panes, although ST has that capability. And it is contradistinct to the normal sidebar selection in ST, where some tab is brought forward if it is already open to that file. :+1:

**Comment by rjschu** [comment]
hey i wouldn't mind taking a look at this, mind if i ask a few questions just for some clarity on how you would like it to work?

**Comment by benogle** [comment]
Seems like a great idea for a package.

**Comment by thomasjo** [comment]
> Seems like a great idea for a package.

I agree, so I'm going to close this. If anyone is opposed to that, feel free to reopen.

**Comment by robsonsobral** [comment]
Hi! I don't think this should be a package. To open the same file more than once is something pretty common across several different kinds of programs. I use it even on Photoshop!

Specially when you're editing a long file (and because of Atom bad performance), to have more than one view into file is the best way to move code around. Of course, if we could drag text, which isn't available also.

**Comment by robsonsobral** [comment]
Hey! It looks like you can use `CTRL+K, right` for that, but I can't find it on any menu.

**Comment by alexchandel** [comment]
@benogle This should *NOT* be a package. It is necessary that both views edit the same buffer, and that the same temp file buffer is restored to both views. The functionality already natively exists in Atom, as evidenced by `Cmd+K, right`.

However, there is no way to do the equivalent of `Cmd+K, right` in the same pane, which is often desired. Moreover, atom crashes when you drag the result of `Cmd+K, right` back into the original pane.

**Comment by foxx** [comment]
+1 for not being a package

**Comment by gliviu** [comment]
Since no package seems yet to exist, work around this by opening the file in a separate pane (ctrl-k left) and drag&drop the new tab back to the original pane

**Comment by jaepage** [comment]
Pressing <kbd>command</kbd><kbd>k</kbd>,<kbd>command</kbd><kbd>right-arrow</kbd> does not open a new view into the file, it just moves keyboard focus to the next pane over. 

Atom 1.9.9. Mac OS 10.11.6.

**Comment by jjh42** [comment]
I am also missing this functionality. If I have two panes open, Atom now refuses to open the file again in the second pane.

**Comment by rysport** [comment]
It works for me by just selecting a pane that does not have the file in any of its tabs and then doubleclicking. Opening with cmd+p results in a moved focus to the already opened one.
Atom 1.13.1 MacOS 10.12.2

**Comment by jaepage** [comment]
Exiting convo, returned to Sublime.

**Comment by jjh42** [comment]
@rysport Maybe that's my experience as well. I'm always opening files via cmd+p, not with a mouse. Its odd that the functionality would be different between them.

**Comment by beznosd** [comment]
Seems crash was fixed when you try to do `cmd+k, right` and then dragging the result of this manipulation back to the original pane.
It works in Atom 1.23.3
So the feature `New View into File` seems to be available now.

**Comment by r3dcrosse** [comment]
I did an upgrade from Atom 1.23 to 1.24 and discovered I had lost `New View into File`.

After digging through the config/settings, it turns out you can re-enabled this feature. In config.cson:
```
"tree-view":
    alwaysOpenExisting: true
```
if you change `alwaysOpenExisting` to `false`, then the feature is re-enabled.
