### ISSUE TITLE
Default key bindings not replicated from OS X

### ISSUE THREAD

**Issue by foxx** [atom/atom#8411]
There are a couple of keybindings missing from OS X which you'd expect to exist within the editor.

For example:

`Ctrl + Left/Right` - Jump to start/end of line
`Ctrl + Shift + Left/Right` - Jump+select to start/end of line

**Comment by mnquintana** [comment]
I'm not sure what you mean - <kbd>Cmd-Left/Right</kbd> and <kbd>Cmd-Shift-Left/Right</kbd> are the standard keyboard shortcuts for this behavior on OS X, which should work in Atom. What OS X apps use <kbd>Ctrl</kbd> for this? I just tested with Xcode, and it doesn't use <kbd>Ctrl</kbd> for this behavior.

**Comment by foxx** [comment]
Hmm I'm not sure why you're not able to reproduce this, I've just tried this in Xcode and I was able to use Ctrl for this behaviour. I don't have any keybinding modifications either. I'm using "British - PC" input if that makes any difference

**Comment by lee-dohm** [comment]
By default (as far as I know) <kbd>Ctrl+Left</kbd> and <kbd>Ctrl+Right</kbd> are bound to "Move left a space" and "Move right a space" in Mission Control:

<img width="780" alt="screen shot 2015-08-17 at 12 19 00 pm" src="https://cloud.githubusercontent.com/assets/1038121/9313847/2c9a14d8-44da-11e5-9326-3e368501bd9a.png">

After I disabled that behavior, in XCode the Ctrl versions were *not* jump to the start/end of line, they were move to left/right word boundary.

You can always change the behavior of these keys in your copy of Atom, but I don't feel your suggestions should be defaults.

**Comment by lee-dohm** [comment]
Sorry, in XCode they call it "Move subword backward/forward":

<img width="862" alt="screen shot 2015-08-17 at 12 25 23 pm" src="https://cloud.githubusercontent.com/assets/1038121/9314011/1d95763e-44db-11e5-8667-b46f70d81cfc.png">

**Comment by foxx** [comment]
No worries, thanks for the quick replies!

**Comment by mnquintana** [comment]
You can add these keyboard shortcuts in your `keymap.cson` to get that behavior though:

```cson
'.platform-darwin atom-text-editor':
  'ctrl-left': 'editor:move-to-first-character-of-line'
  'ctrl-right': 'editor:move-to-end-of-screen-line'
  'ctrl-shift-left': 'editor:select-to-first-character-of-line'
  'ctrl-shift-right': 'editor:select-to-end-of-line'
```
