### ISSUE TITLE
Uncaught Error: Can't create a backup file for /Volumes/C/Development/Source/...

### ISSUE THREAD

**Issue by ralfbiedert** [atom/atom#8414]
[Enter steps to reproduce below:]
1. On Mac as a host, mount Parallels 10 / Windows 10 guest C: volume
2. Edit file on that volume, try to save it (from within atom-typescript file window)

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core
### Stack Trace

Uncaught Error: Can't create a backup file for /Volumes/C/Development/Source/[...]/executor.ts because files already exist at every candidate path.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:801

Error: Can't create a backup file for /Volumes/C/Development/Source/[...]/executor.ts because files already exist at every candidate path.
    at TextBuffer.module.exports.TextBuffer.backUpFileContentsBeforeWriting (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1073:17)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1008:31)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:539:18)
    at Pane.module.exports.Pane.promptToSaveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:511:23)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:457:18)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:435:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:617:35)
    at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:656:21)
```
### Commands

```
     -1:14.4.0 typescript:go-to-declaration (atom-text-editor.editor.is-focused)
 16x -1:13.7.0 core:move-down (atom-text-editor.editor.is-focused)
  9x -1:11.7.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -1:10.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:03.3.0 core:cut (atom-text-editor.editor.is-focused)
     -1:02.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:53.2.0 project-find:show (atom-text-editor.editor.is-focused)
     -0:50.6.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -0:37.2.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:34.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:34.2.0 core:cancel (atom-text-editor.editor.is-focused)
  3x -0:33.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:20 window:save-all (atom-text-editor.editor.is-focused)
     -0:11.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.8.0 typescript:build (atom-text-editor.editor.is-focused)
     -0:02.8.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "editor": {
    "invisibles": {},
    "tabLength": 4,
    "preferredLineLength": 120,
    "backUpBeforeSaving": true
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v5.4.0
docblockr, v0.7.3
language-docker, v1.1.3
language-latex, v0.6.1
last-cursor-position, v0.9.0
latex, v0.25.0
latexer, v0.2.4
linter, v1.4.1
minimap, v4.12.3

# Dev
No dev packages
```

**Comment by nathansobo** [comment]
@ralfbiedert Had previous attempts to save the file failed? We leave backup copies in place when writing the original file fails, and it looks like you must have built up multiple copies.

**Comment by ralfbiedert** [comment]
I just tried to reproduce it and I had save it (rather attempt to save it) a few times indeed. Before that I got an:

`Unable to save file: Operation not supported on socket '/Volumes/C/Users/rb/Desktop/test2.txt'`

Here is how the directory looks like:

![screen shot 2015-08-18 at 23 31 04](https://cloud.githubusercontent.com/assets/301288/9343274/3b087f8c-4601-11e5-91fe-0c8cdd38ef2c.png)

**Comment by ralfbiedert** [comment]
Funny thing is, I can't open the backup files from the Windows guest, gives me the following error:

![screen shot 2015-08-18 at 23 37 30](https://cloud.githubusercontent.com/assets/301288/9343425/3445eba2-4602-11e5-9d19-7fdb6ce784e3.png)

**Comment by ralfbiedert** [comment]
All of them are empty though ...

![screen shot 2015-08-18 at 23 39 07](https://cloud.githubusercontent.com/assets/301288/9343450/5da2fa8a-4602-11e5-8e6a-59347322013d.png)

**Comment by kvonmurphy** [comment]
I’ve got a similar problem when saving a file on a Samba share. 

Work-around : in the Config, set   ``backUpBeforeSaving: false``

Error message : ``Unable to save file: Operation not supported on socket ``
Configuration: 
Atom 1.3.2 on Mac OS X 10.8.5, working on a Ubuntu 15.10 server, shared through Samba 4.1.17.

Rights are OK, I can update my files through another editor. No problem updating files on the Mac itself. This is a problem with Atom and Samba share only apparently. The ~ appear but they are not empty.

**Comment by masonfox** [comment]
@kvonmurphy +1

I just replaced `backUpBeforeSaving` to false and I no longer have issues. If you were like me and searched package contents for the config file for mac, you can find it under the main menu by clicking on "Atom" when the app is active.

**Comment by AWTrost** [comment]
@kvonmurphy @masonfox :+1:, same problem and same work around as well.  Atom does not ask for authentication when attempting to save the backup file, but does when backUpBeforeSaving is false.  Would be nice to be able to use both together.

Happens on both 1.5.0-beta1 and 1.4.1 versions of atom, and am on Mac OS X 10.11.2 and this happens both on readonly local files on the mac, as well as on smb shares (error msg is different, local says 'unable to save file: Permission denied' while on the share it gives the 'operation not supported on socket' message).  Thx for the help

**Comment by nathansobo** [comment]
We're investigating an alternative solution that's less error prone. It's difficult to track down all the ways things can go wrong here with different file systems.

**Comment by rupertbg** [comment]
Same here: OS X 10.11.3 and a Samba share on Ubuntu 15.10. Perhaps the backup is doing a rename instead of a mv?..

**Comment by Pysis868** [comment]
Same problem here; Mac OS X 10.11.3; Atom 1.5.3; can consistently reproduce ever since first editing a file over an SMB/Samba share; Sublime Text saves fine; Finder also has (mostly) no problems dealing with the share as well.

I would really like to **not** disable making backups of files upon save.

Curious, how's the progress of this item as a bugfix/enhancement? :)

**Comment by nathansobo** [comment]
@Pysis868 as of 1.7 it's much safer to turn this off because we're periodically saving the entire project state, including the buffers. The buffer state is still tied to the project, which is why we aren't removing this feature yet. When we periodically save buffers independently of project state we're probably going to rip this out entirely because there are way too many edge cases on different file systems.

**Comment by liam-b** [comment]
@ralfbiedert I have the same problem but it was working earlier this week no problem.

**Comment by liam-b** [comment]
Just tried backUpBeforeSaving: false, works perfectly for me
