### ISSUE TITLE
Unable to change installation directory

### ISSUE THREAD

**Issue by abenitesDC** [atom/atom#8417]
Limited drive space considering more packages to be installed. Need to change default windows directory to D drive. I can't find anything on forums or documentation. It is curious how Atom claims to be "hackable" but I can't find a way how to do a very basic functionality :)

**Comment by izuzak** [comment]
Thanks for the feedback, @abenitesDC -- I think this is covered in https://github.com/atom/atom/issues/7504, so I'm closing this in favor of that issue. Please feel free to leave a comment there or just subscribe for updates.
