### ISSUE TITLE
Sporadic X11 error causes Atom to crash

### ISSUE THREAD

**Issue by samis** [atom/atom#8418]
I've never exactly been able to nail down the cause of this issue. It has happened multiple times with the same error results. Restarting my desktop environment  (Enlightenment) cures the issue, suggesting the error is perhaps caused by a specific interaction with it. Once Atom crashes once from it (unpredictable) it will then predictably crash the first time a menu is clicked, always dying from the same error code. This 2nd crash will occur even in safe mode, but I have not used safe mode long enough to see if it can trigger the first one. I'm on Arch Linux and using Atom 1.0.7. Below is the last output of a crashed instance of Atom.
```
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 3680 error_code 3 request_code 3 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by izuzak** [comment]
Thanks for the report, @samis -- can you add this as a comment to https://github.com/atom/atom/issues/6595? That seems like a very similar report, so it would be helpful to keep all the relevant information in one place. I'll close this in favor of that, but let me know if you think this isn't related. :v:

**Comment by samis** [comment]
While the error in #6595 is the same, I'd personally say it's much more closer to #6496 myself. Mainly the issues described by @Yomi0 and @mauricioszabo. However, there are no dbus-related messages in the log unlike most of the issues in that thread. This is evident in the below log, from the same instance as the above error.
```
2791:0817/231747:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[2791:0817/231749:INFO:audio_manager_pulse.cc(258)] Failed to connect to the context.  Error: Connection refused
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[2814:0817/231750:ERROR:sandbox_linux.cc(325)] InitializeSandbox() called with multiple threads in process gpu-process
[2822:0817/231751:INFO:renderer_main.cc(212)] Renderer process started
[2791:0817/231802:INFO:CONSOLE(56)] "Window load time: 9366ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (56)
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 3680 error_code 3 request_code 3 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by izuzak** [comment]
Thanks for investigating further, @samis -- I suggest you add your information to those issues or just subscribe to them so that you receive updates.
