### ISSUE TITLE
Saving a file should not automatically append a newline at the end if it is "missing"

### ISSUE THREAD

**Issue by groue** [atom/atom#8424]
To reproduce: open a file which has no newline at the end, perform no edition whatsoever, and save. Bam! an unwanted newline is appended at the end.

Where things turn not funny: this unwanted newline can not be removed from Atom, since Atom always adds it on saving...

**Comment by groue** [comment]
Atom 1.0.7, MacOS 10.10.5 (14F27).

I don't know any text editor that forces this very intrusive behavior. Intrusive as in "all your data are belong to us". You could at least provide a preference.

**Comment by alexchandel** [comment]
@groue Look in the settings for the `whitespace` package to disable this. Though I agree, per-language and per-project configuration is important.

**Comment by mnquintana** [comment]
Please see https://discuss.atom.io/t/why-is-atom-deleting-trailing-whitespace-why-are-there-all-these-changes-in-the-file-diff/19189 for more information.

**Comment by groue** [comment]
OK, thanks @alexchandel.

@mnquintana, since you took the responsability of closing this issue, here is my conclusion: I don't know how many people complain about this default behavior. I'm certainly not the only one. It would be reasoable to move that "whitespace" package into the core of the app, and expose as set of preferences. Rationale : it's *impossible* to *guess* how this whitespace *storm* can be stopped.

**Comment by mnquintana** [comment]
@groue Did you read through that forum thread? There are preferences for changing this behavior.

![image](https://cloud.githubusercontent.com/assets/823545/9331428/78755666-458d-11e5-8349-599a73375650.png)

**Comment by groue** [comment]
I don't have those settings (OS X 10.10.5, Atom 1.0.7)

![capture d ecran 2015-08-18 a 15 48 51](https://cloud.githubusercontent.com/assets/54219/9331601/a87c058e-45c0-11e5-9627-f5fcbcd0e56b.png)

**Comment by mnquintana** [comment]
@groue Can you post the contents of your `config.cson`? (Atom > Open Your Config)

**Comment by groue** [comment]
Sure @mnquintana, there it is:

    "*":
      "exception-reporting":
        userId: "0e6508f3-4e60-efb6-d9c3-25bcdab1686f"
      welcome:
        showOnStartup: false
      core:
        themes: [
          "one-light-ui"
          "one-light-syntax"
        ]
        disabledPackages: [
          "whitespace"
        ]
      editor:
        invisibles: {}

**Comment by abe33** [comment]
Looks like there's an issue with your settings view, do you happen to see the settings for the other packages?

**Comment by groue** [comment]
Whitespace package was enabled when I took the screenshot.

**Comment by groue** [comment]
I can see it for the autocomplete-plus package.

**Comment by mnquintana** [comment]
@groue Can you try restarting Atom? I suspect something weird happened with serialized state for that package when it was disabled.

**Comment by groue** [comment]
After a restart, the settings were back. Well guessed, @mnquintana. And I could tune it to my needs.
