### ISSUE TITLE
Path in window title bar not correct on Linux

### ISSUE THREAD

**Issue by miishke** [atom/atom#8434]
Path shown in the window title bar is always shown only for the first opened file and doesn't change when switching tabs. It even stays on after all tabs are closed. System is Ubuntu 14.04 LTS.
![atom_path_bug_1 txt - -home-phoebus-documents - atom_101](https://cloud.githubusercontent.com/assets/4196718/9346791/1a381fcc-45ef-11e5-869f-08d4643b2786.png)
![atom_path_bug_2 txt - -home-phoebus-documents - atom_102](https://cloud.githubusercontent.com/assets/4196718/9346794/220f23da-45ef-11e5-814d-96f9d4910300.png)

**Comment by izuzak** [comment]
Thanks for the report @miishke -- I think the core problem here is already covered in https://github.com/atom/atom/issues/5058 and https://github.com/atom/atom/issues/7614, so I'm going to close this in favor of those two issues to keep things focused. If you'd like, please leave a comment on those issues or just subscribe for updates. And please let me know if I've misunderstood your report.
