### ISSUE TITLE
request: awk support

### ISSUE THREAD

**Issue by jungle-boogie** [atom/atom#8435]
Hello,

When pasting in some awk code, the atom editor didn't know what it was so it was left as plain text. I tried looking for awk by clicking in the lower right corner on plain text, but no awk results appeared when I typed in `awk`.

Thanks!

**Comment by izuzak** [comment]
Hey @jungle-boogie :wave:. Support for specific languages, such as syntax highlighting, comes from packages. Atom ships with a default set of packages which don't cover every possible language, but you can install additional packages to add support for more languages. 

You can also see and search through the complete list of packages on the atom.io website:

https://atom.io/packages

As far as I can tell, noone has built a language package for `awk` yet:

https://discuss.atom.io/t/language-awk/19540

This might be a good opportunity to reach out to interested folks and build it together.

I hope this answers your question.
