### ISSUE TITLE
CLI add project folder options (feature request)

### ISSUE THREAD

**Issue by filipesilva** [atom/atom#8438]
Opening several atom windows is still a bit of a performance hit, so I usually try to add project folders onto the existing window using the command palette or menu options.

Having CLI flag (similar to how we have `-n` for a new window) to do that would be pretty useful. It could be `-a` for `--add` or maybe `-e` for `--existing`. It would add the folders to an instance if it exists, and if not just open a new one.

Example usage:
```
atom .
atom ~user/.config/ ../related-project/ -a
```
Result: one window with `.`, `~user/.config/` and `../related-project/` open.

**Comment by izuzak** [comment]
Sounds like the same suggestion which is described over in https://github.com/atom/atom/issues/6097. Let me know if I misunderstood, though.

**Comment by filipesilva** [comment]
Indeed it is. Thanks for the heads up!
