### ISSUE TITLE
Network Proxy Setting is needed

### ISSUE THREAD

**Issue by Loyalsoldier** [atom/atom#8439]
I'm living in China, it's very very slow when searching, installing, updating the packages and themes.
**Hope you guys add a network proxy setting feature.**

**Thanks a lot!**

**Comment by kevinsawicki** [comment]
I believe this is a duplicate of https://github.com/atom/atom/issues/3119

You can configure `apm` to use a proxy from the command line https://github.com/atom/apm#behind-a-firewall

**Comment by Loyalsoldier** [comment]
It seems the solution is  out of date. It doesn't work actually……
