### ISSUE TITLE
Can't exit Find, but can exit Find and Replace (project)

### ISSUE THREAD

**Issue by TreyTaylor1997** [atom/atom#8444]
Hey all,

noticed a rather weird bug, whenever I hit CTRL + F to find something I can't seem to ever exit the find pane, but if I hit CTRL + SHIFT + F and find things like that I can exit the find pane..

Has anyone else experienced this?

Details:

Atom version: 1.0.7
OS: Windows 10 64-bit

(^Windows 10 is probably the cause of the bug)

**Comment by mnquintana** [comment]
Thanks for opening an issue! This isn't a bug though - <kbd>Escape</kbd> closes the find panel, not <kbd>Cmd-F</kbd>. <kbd>Cmd-F</kbd> and <kbd>Cmd-Shift-F</kbd> are intended to re-focus the search input.

![image](https://cloud.githubusercontent.com/assets/823545/9361366/1c1a3cf6-4669-11e5-8a36-a1e207d93ec0.png)

See https://github.com/atom/find-and-replace/issues/419#issuecomment-116274834 for more information.

Hope that helps!

**Comment by TreyTaylor1997** [comment]
I push ESC to try to escape I was just referring the keys for find and project find..

**Comment by mnquintana** [comment]
Ah, so you mean that when you press <kbd>Esc</kbd> when find in buffer is open it doesn't close?

**Comment by TreyTaylor1997** [comment]
Yess :) (although English is my native language - I suck at it haha)
