### ISSUE TITLE
Pane split on windows doesn't work in the left and right directions when using single key combo binding

### ISSUE THREAD

**Issue by NullVoxPopuli** [atom/atom#8447]
my keymap.cson

    'body':
      'alt-down': 'pane:split-down'
      'alt-up': 'pane:split-up'
      'alt-right': 'pane:split-right'
      'alt-left': 'pane:split-left'

splitting up and down work fine, but left and right just don't do anything..

it does work if I do a two stage hotkey, like:

    'ctrl alt-left'

but that's not ideal for me

**Comment by mnquintana** [comment]
Thanks for the report! This looks like it might be the same issue as https://github.com/atom/atom/issues/6037 - would you mind taking a look to see if it is?

**Comment by NullVoxPopuli** [comment]
ah yes, that does look very similar. 

I noticed that the menu on the top of atom (file, edit, etc), as well as other windows apps, is active when `alt` is held. so, alt is probably a default windows binding for navigating menus. (I'm used to linux.. so this just adds to the frustration of windows.)

So, I'm not sure if it's possible to override that default behavior or not.

**Comment by NullVoxPopuli** [comment]
this is now also happening in linux... boo

**Comment by mnquintana** [comment]
Thanks for the update! Since this does look like the same issue as https://github.com/atom/atom/issues/6037, I'm going to close this out in favor of that issue.
