### ISSUE TITLE
Building a fork of Atom to run at the same time.

### ISSUE THREAD

**Issue by zackarychapple** [atom/atom#8448]
I am trying to build a fork of Atom and have it running at the same time.  My goal is similar to what Nuclide did in the sense that I will be bundling configurations and packages with Atom, however I want to run it as it's own application and not affect the user's install of Atom. 

I found how to change the home directory and the app name, however which ever app I launch first (mine or atom) that is the one that new windows will open in when I try to open the second application.

**Comment by kevinsawicki** [comment]
Do you want them as completely separate applications?

In that case you will need to modify the `.plist` on Mac OS X to be a separate application.

**Comment by zackarychapple** [comment]
@kevinsawicki yes I want to run them as separate applications, for multiple reasons.  I modified the `.plist` file and for some reason the two apps are still tied together.   I modified Executable File, Bundle Identifier and Bundle Name, what else needs to be changed?  Also just FYI I changed the name of the executable as well.

**Comment by zackarychapple** [comment]
Thoughts?

**Comment by kevinsawicki** [comment]
You probably need to change the socket path.

https://github.com/atom/atom/blob/cd4726bb27f714e47f7e2e822d9a09ab0535488f/src/browser/atom-application.coffee#L20-L24

This is also tweakable via the `--socket-path` command line option.

**Comment by john-kelly** [comment]
@zackarychapple 

#### These handle the link for the atom.sh -- you'll want to make some changes for your own .sh
- https://github.com/atom/atom/blob/9a431a5c979f9b0b2dbe95119eb66292bb00fbaf/src/workspace.coffee#L126
- https://github.com/atom/atom/blob/master/src/atom.coffee#L624

#### This file in general will just need some work
- https://github.com/atom/atom/blob/master/atom.sh

#### This is where the `.atom` is setup if not already done so. You'll want to have your own `.myapp` dir
- https://github.com/atom/atom/blob/master/src/browser/main.coffee#L60

Changing those files (and the aforementioned socket path) should be enough to get something working.

Let me know if you have any questions :+1:

**Comment by Ben3eeE** [comment]
Looks like this question was answered. Closing.
