### ISSUE TITLE
Selected Text Breaks When Dragging

### ISSUE THREAD

**Issue by blakeembrey** [atom/atom#8449]
I couldn't find this issue previously logged.

It took me a long time to realise this isn't a random bug, but a consistent issue with how I happen to use drag (Mac OS X) + `cmd+d`. I believe other applications using selections suffer similar issues.

![selection buffer issue](https://cloud.githubusercontent.com/assets/1088987/9365952/4ecd166e-4669-11e5-9083-1cc58c37d632.gif)

Notice the first selection is without holding down the selection on Mac OS X (E.g. three finger drag and lifting up before pressing `cmd+d`). The second is pressing `cmd+d` with my fingers still on the trackpad.

**Comment by maxbrunsfeld** [comment]
Are you using a trackpad? I think this is related to https://github.com/atom/atom/pull/8446

**Comment by blakeembrey** [comment]
@maxbrunsfeld Yes, I had updated the description with that. Looks like it is, but it's not text input - rather a shortcut.

**Comment by mnquintana** [comment]
@blakeembrey Thanks for the update! It's good to know that this happens with keyboard shortcuts too. I think this is the same underlying issue as https://github.com/atom/atom/issues/8369 though, so I'm going to close this in favor of that issue.
