### ISSUE TITLE
TextEditor.getCursorBufferPosition and tabs

### ISSUE THREAD

**Issue by torgeirsh** [atom/atom#8454]
For the horizontal position returned by getCursorBufferPosition, a tab counts as 1 step insted of 8 (or other tab width). This is also apparent from the status bar. The behaviour differs from other popular editors like Visual Studio or IntelliJ IDEA, and causes trouble when plugins use the position to e.g. jump to the definition of the function name below the cursor. See this issue for reference: https://github.com/atom-haskell/ide-haskell/issues/92

**Comment by izuzak** [comment]
@torgeirsh I'm not sure I understand what kinds of problems this is causing.

The `getCursorBufferPosition` method returns the position of the cursor when you observe a string of characters as they're written in the buffer, not on the screen. These buffer position are not aware of how tabs get rendered on the screen -- it could be 4 spaces, 8 spaces, or something else. You get the position in the buffer and you can use that to determine what text is at that position in the buffer. Can you clearly explain what's wrong with this approach for fetching the text under the cursor?

/cc @nathansobo just in case you have a different opinion on this

**Comment by torgeirsh** [comment]
As I mentioned it's inconsistent with several other editors and tools. If Atom needs a tab-unaware position in the API, that's not wrong as such, but please consider adding a tab-aware version for convencience. Otherwise a plugin will have to work around it by parsing the line and expanding tabs manually.

**Comment by izuzak** [comment]
> Otherwise a plugin will have to work around it by parsing the line and expanding tabs manually.

Can you explain why that's so exactly? When you read text from a file, that file doesn't know how a tab is represented on the screen. Again, being as clear and as precise as possible here would be helpful.

**Comment by izuzak** [comment]
@torgeirsh Also, there's [`getCursorScreenPosition`](https://github.com/atom/atom/blob/7e197060bc483106f9002526f22349fed6d94959/src/text-editor.coffee#L1607) which you might find helpful.

```javascript
editor = atom.workspace.getActiveTextEditor()

// my tab length is set to 2, and my cursor doesn't change position as I run the commands below

> editor.getCursorBufferPosition()
Point {row: 0, column: 2, copy: function, negate: function, freeze: function…}

> editor.getCursorScreenPosition()
Point {row: 0, column: 4, copy: function, negate: function, freeze: function…}

// at this point, I change the tab length to 4 in settings

> editor.getCursorBufferPosition()
Point {row: 0, column: 2, copy: function, negate: function, freeze: function…}

// notice that the buffer position didn't change, but the screen position will

> editor.getCursorScreenPosition()
Point {row: 0, column: 8, copy: function, negate: function, freeze: function…}
```

**Comment by nathansobo** [comment]
@torgeirsh You should be using screen coordinates instead of buffer coordinates for this kind of behavior. They also account for other spatial transformations such as folds and soft wraps. If that's not working for you for some reason, please re-open.

**Comment by torgeirsh** [comment]
The fact that screen coordinates account for stuff like soft wraps makes them unsuitable for passing to a language analysis tool. It's not a good idea that tab settings affect the result either, as tab stops are always 8 characters apart in the eyes of compilers and tools for languages like Haskell and Python. Maybe that makes the feature too language/plugin specific to belong in core, even if it's consistent with the way tabs were usually interpreted historically.

**Comment by nathansobo** [comment]
It's pretty surprising to me that these tools don't work in absolute buffer coordinates. Can you point me to a more detailed example of an API where non-tab-stop-aware tab expansion is needed? I'm reluctant to add a third coordinate system where tabs are expanded to the screen but no other transformations are applied, because it will complicate the API.

**Comment by torgeirsh** [comment]
One example is the Haskell ghc-mod tool: http://www.mew.org/~kazu/proj/ghc-mod/en/ghc-mod.html As you can see the type command expects a column number, not a character offset. For a line that contains a tab character followed by an expression, the user has to specify column 9 (or greater) to obtain the type of the expression after the tab, column 2 would be inside the indentation. This is not explicitly documented on the page, but easy to verify. I'm not sure if tools for Python (which also assumes 8 characters between tab stops) work in a similar way. If there are no other examples of this behaviour I agree that it would be needless complication of the API.

**Comment by lierdakil** [comment]
For what it's worth, general advice for Haskell is "don't use tabs if you can help it", precisely for this reason: tabs are unreliable in many cases.

That said, being able to transform a point and/or range for a given buffer/editor to/from tab-aware coordinates, while ignoring folds etc, would be a godsend. Best solution I could come up with at the moment is iterating over line containing a point, comparing computed and point column at each iteration, which is... less than elegant. Any advice is appreciated.

**Comment by torgeirsh** [comment]
Tabs aren't unreliable, the problem is when people mix tabs and spaces for indentation, often because they rely on fixed-width fonts for ad-hoc formatting to work. Tabs aren't being unreliable in this particular case either, they're simply not implemented. :) I understand that it would be more convenient to ignore the tab character, but I think it's too widespread to not only deprecate, but remove, especially in the context of a language that explicitly defines its purpose.

**Comment by lierdakil** [comment]
Problem with tabs is most editors on market let you configure display width of tab stop, while Haskell Report defines tab stops as 8 characters apart. This is where "unreliable" bit comes from -- you can't rely on editor settings being correct in every case. Granted, experienced developers know about this and can take measures to deal with it. But at the very least, for open-source projects, tabs are *quite* bad.

Sorry about a bit of off-topic...
