### ISSUE TITLE
Links in package view open twice

### ISSUE THREAD

**Issue by rugk** [atom/atom#8457]
If I view an installed or not installed package and click on on of the links/buttons ('view on Atom.io' or 'Changelog' e.g.) the link will open twice.

That happens with web links ('view on Atom.io') but - as I said - also with links which are opened in Atom itself (like 'Changelog').

Atom 1.0.7
Windows 7

**Comment by mnquintana** [comment]
Does this also happen if you click on links from another package? Try opening the About dialog (Help > About Atom) and clicking some of the links / buttons and see if this still happens.

**Comment by rugk** [comment]
No and I've now tried it again at the package buttons and it worked, so I don't know what has caused this issue.

**Comment by rugk** [comment]
Okay I think this should also be moved to settings-view as it only happens there.
I will move it...

**Comment by rugk** [comment]
Done. (https://github.com/atom/settings-view/issues/639)
