### ISSUE TITLE
Version of packages displayed as 'undefined' in full view

### ISSUE THREAD

**Issue by rugk** [atom/atom#8459]
![noversiondisplayed](https://cloud.githubusercontent.com/assets/11966684/9388820/24e8ed78-4768-11e5-8668-a3b1a2e6ecd7.gif)

This happens with every package I haven't installed.

Atom 1.0.7
Windows 7

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/settings-view? Thanks!

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Comment by rugk** [comment]
Done: https://github.com/atom/settings-view/issues/638

And thanks for the second link. That's indeed a goof to read.
