### ISSUE TITLE
Toggling tree-view displaces screen and hides tabs

### ISSUE THREAD

**Issue by lancelafontaine** [atom/atom#8461]
Hope this is the right place to be submitting this bug.

Using Atom 1.0.5 on Arch Linux with Gnome 3. Linux kernel is linux 4.1.4-1.

This behavior began as soon as I upgraded to 1.0.5. It is also independent of any themes I have applied. It occurs every time without fault.

When toggling the tree view open, and then toggling it closed again, the entire screen with the exception of the tree view moves upwards approximately 100px. This effective hides the tabs. I realize that this is difficult so describe, so I've included a short gif. 

![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/1548285/9231107/585a4b04-40f4-11e5-8f0a-69db7f26e924.gif)

Opening the Command Pallette at any time seems to reset the window placement, but does not fix the original issue when toggling the tree-view.

**Comment by thomasjo** [comment]
Are you able to reproduce this problem in safe mode? `atom --safe`

**Comment by lancelafontaine** [comment]
No, it is not reproducible in safe mode.

**Comment by maxbrunsfeld** [comment]
@lancelafontaine Thanks for the update. Could you narrow down which of your installed packages/themes has caused this, and open an issue on the repo for the offending package or theme? 

I'm going to close this out for now; if you find that there are still issues with Atom, I'll reopen it. We can still help you troubleshoot too.
