### ISSUE TITLE
Strange keyboard

### ISSUE THREAD

**Issue by ezequias** [atom/atom#8464]
Hello everyone

I am in trouble to print the slash key "/" on Atom. It is basically formed by two keys on my notebook keyboard.

Please take a look on my keyboard configuration on that screenshot: https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues

It is basically formed by 
Alt Gr + Q

Could someone tell me how to disable the shortcut that Atom is firing when I press this two keys? 

I tried to find this out on keybindings screen but without any success.

Regards
Ezequias Rocha

**Comment by batjko** [comment]
Hi Zeque... 
There is a known issue with the support of international keyboards, most commonly seen when the Alt-Gr key is involved. 

Please see these existing issues:
https://github.com/atom/atom-keymap/issues/35
https://github.com/atom/atom-keymap/issues/37

As a workaround, there is a package many people are using successfully:
https://atom.io/packages/keyboard-localization

**Comment by izuzak** [comment]
Thanks for adding those links, @batjko -- I believe you're right. 

@ezequias Please check out those issues and subscribe for updates there -- I'm closing this in favor of those issues.

**Comment by ezequias** [comment]
Thank you all @izuzak @batjko ;)
