### ISSUE TITLE
Atom error on first startup

### ISSUE THREAD

**Issue by jvilaplana** [atom/atom#8466]
Atom does not load correctly the first time I try to open it.
It seems to load correctly the second time I open it.

![Atom error](http://i.imgur.com/Oz4Pc3f.png)

I'm using Windows 10 x64 and Atom version 0.146.0.

**Comment by izuzak** [comment]
> Atom version 0.146.0

That's a super old version of Atom. Do you see the same problem in the latest version, 1.0.7?

**Comment by jvilaplana** [comment]
Oh I upgraded to the latest version and seems fixed now, thanks.
