### ISSUE TITLE
"mkdir" Operation Not Permitted

### ISSUE THREAD

**Issue by kingbari** [atom/atom#8472]
Whenever I execute atom.exe (even in safe mode) I get the following error:

> Error: EPERM: operation not permitted, mkdir 
'C:\WINDOWS\system32\config\systemprofile\AppData\Local\atom'

Does anyone know how to resolve this?

**Atom Version: 1.0.7**
**Apm version: 1.0.1**
**Node version: 0.12.7**
**Npm version: 2.5.1**
**System: Microsoft Windows 10 Home**

**Comment by batjko** [comment]
It seems Atom is installed in the wrong place (under the Windows folder, to which by default the application won't have write access).

Normally, it should be installed under your user account's Appdata, for example:
`C:\Users\[yourUsername]\AppData\Local\atom`

It seems to me that some pre-configured path was misconfigured on your machine when you installed Atom.
The "systemprofile" portion of the path is not standard Windows, so my first guess would be that some environment variable that is supposed to point at your current user account's directory (`C:\Users\[Username`)... isn't pointing at that.

**Comment by kingbari** [comment]
There are no pre-configured atom paths. But just to be sure I cleared the ATOM_HOME environment variable created during installation, then uninstalled and re-installed atom. When doing so, I noticed that windows creates a shortcut "Atom.exe" with the following parameters:

**Target:** C:\Users\Ari\AppData\Local\atom\Update.exe --processStart atom.exe

**Start in:** C:\Users\Ari\AppData\Local\atom\app-1.0.7

When I execute this shortcut, it seemingly creates another folder within **C:\Users\Ari\AppData\Local\atom** named **app-1.0.7** -- within this folder it creates a folder literally named %USERPROFILE% whenever I install packages from an atom instance started with this shortcut, packages are installed to the aforementioned %USERPROFILE% literal folder name. 

However, from the search panel if I execute atom.cmd an atom instance is launched that uses **C:\Users\Ari\\.atom** to store packages.

**Comment by damieng** [comment]
That all sounds correct except for creating a folder named '%USERPROFILE%'.

Are you still having this issue with recent versions?

**Comment by damieng** [comment]
No response, closing issue. Please re-open if still experiencing issue.
