### ISSUE TITLE
Desktop App does not pin correctly in Windows 10

### ISSUE THREAD

**Issue by rofeksos** [atom/atom#8474]
When you pin the desktop app it creates a separate instance and puts it at the end in the desktop. Whenever you close and re-launch the app it opens up a separate instance and not where you pinned it originally

**Comment by mnquintana** [comment]
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/7374 – I'm gonna close this out in favor of that issue. Let me know if I'm misunderstanding, though.
