### ISSUE TITLE
open with atom stays when I uninstall atom

### ISSUE THREAD

**Issue by resouer** [atom/atom#8481]
That's annoying!

I can't clear "open with atom" when I right click on the desktop, any help on this?

ENV:

win7 64bit

**Comment by SelenaZelia** [comment]
Open command line (windows + R)
Type in regedit.exe
May have to enter your password 
Left click on computer (at the top of the tree), CTRL+F and type in "Atom"
From here you should get a folder going "Open with atom" or something like that, delete that, and ONLY that
Continue doing CTRL+F to see if something else is here, and try to get it out of here

I'm more concerned by the reason that push you to delete that awesome editor :p 

For the screenshot, note that your tree won't be exactly like mine probably
![atomdeletion](https://cloud.githubusercontent.com/assets/5408322/9519030/af279d74-4cbb-11e5-9a1e-3f6ffd956843.png)

**Comment by damieng** [comment]
Open with Atom should be removed on uninstall but there may have been issues in old versions. If you see this problem in Atom 1.7.0 or beyond please reopen.
