### ISSUE TITLE
Allow us to block popup's from addons.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#8482]
The same way that Android allows us to silence apps it would be nice to silence addons with glaring bugs that keep causing errors but we do not wish to remove.  Such as a recent bug with linter that causes a file with a simple name to popup an error, it would be nice if we could block those messages because as a whole it works but in one part it's broken.

**Comment by lee-dohm** [comment]
If you mean the standard notifications that show in the upper-right:

<img src="https://cloud.githubusercontent.com/assets/69169/5176406/350d0e80-73fd-11e4-8101-1776b9d6d8bf.gif" />

then this should probably be moved to the atom/notifications repository.

If you mean something more global, then could you clarify what your expectation is?

**Comment by mark-hahn** [comment]
I have used several different methods to show dialogs and there is no one
way that would work on all packages, at least all of mine.

The standard one is an ugly "alert" kind of thing.  Is that what you are
talking about?  Maybe show a screen cap?

Now that I think about it I'm not sure if it is possible to tell what
package is causing pop-up code to run.  Code can execute from anywhere.

**Comment by envygeeks** [comment]
@lee-dohm @mark-hahn the screenshot provided was exactly what I was on about so I shall move it there but as you point out it might not be possible without some rewiring.

**Comment by sambuchl** [comment]
Hi all,

I'm new to gh and not sure how to report my issue as an add-on to this one, but if you're working on a half-size screen and get add-on errors, they can prevent you from doing work.

Seconding the request to be able to block/silence popups - especially after you've already closed them once. 
<img width="840" alt="screen shot 2015-12-24 at 9 49 55 am" src="https://cloud.githubusercontent.com/assets/3187916/11996203/21b201a2-aa24-11e5-87b0-d98ffe391229.png">

**Comment by envygeeks** [comment]
@sambuchl you probably want to merge your comment into: https://github.com/atom/notifications/issues/14 as even though it's kind-of like mine, you probably want status-bar notifications so you don't have that mess happen to you

**Comment by sambuchl** [comment]
Thanks, merged into atom/notifications#14

(Let me know if it would be typically for me to remove my comments from this thread :-). Still feeling out gh conventions.)

**Comment by envygeeks** [comment]
@sambuchl nah, normally comments just stay so people can read and follow everything for posterity.

**Comment by sambuchl** [comment]
That makes sense. Thank you.
