### ISSUE TITLE
BBEdit like syntax highlighting color / theme

### ISSUE THREAD

**Issue by scls19fr** [atom/atom#8484]
Hello,

I'm using BBEdit and I'm considering moving to Atom.
But I love syntax highlighting color, font size, page area and out of area color of BBEdit...
is there a theme quite similar ?

![capture d ecran 2015-08-23 a 11 11 02](https://cloud.githubusercontent.com/assets/109167/9427624/d0466238-4987-11e5-89c5-03a365de15c3.png)

Kind regards

**Comment by scls19fr** [comment]
- Settings
  - Font Size: 11
  - Line Height: 1.4

![capture d ecran 2015-08-23 a 11 18 25](https://cloud.githubusercontent.com/assets/109167/9427658/2df04a38-4989-11e5-9c5d-470fe3ba124d.png)

**Comment by batjko** [comment]
I think this question may be better posed on the [forum](https://discuss.atom.io/).
At the same time, you might get lucky browsing the [themes directory](https://atom.io/themes), although there currently is no other way than looking at them one-by-one.

**Comment by scls19fr** [comment]
Ok.

I did myself something which is quite close (not exactly the same).
https://github.com/scls19fr/aa-light-theme

Thanks

**Comment by scls19fr** [comment]
But it still needs to be improved

https://github.com/scls19fr/aa-light-theme/issues/2
