### ISSUE TITLE
IME composition with multiple cursors

### ISSUE THREAD

**Issue by jacekkopecky** [atom/atom#8486]
In `text-editor-component.coffee` L249–251 ([here](https://github.com/atom/atom/blob/4560914273127105eac7ce2d46bcb8903b972dae/src/text-editor-component.coffee#L249)) the `compositionend` event causes the editor to put back in the text that was in the original selection, except it breaks with multiple cursors. 

Steps to reproduce:
 1. have `foobar` in a text editor
 2. put cursor before `f` and add a new cursor before `b`
 3. press `shift-right`, now you have `f` and `b` selected
 4. type a composited text (e.g., on a mac with US keyboard, `alt-e`+`e` to get `é`)
 5. you will now have `éooéar` – so far so good, but now do `undo` (`cmd-z`)
 6. end up with `boobar` instead of `foobar`

Possibly related to #5414.

**Comment by maxbrunsfeld** [comment]
Thanks for tracking this down. Are you interested in submitting a PR for this one? Seems like instead of maintaining our state in a single string (`selectedText`), we'll need to store an array containing each selection's text.

**Comment by jacekkopecky** [comment]
I'm attempting to avoid having to keep the old selections by using `undo` instead: #8526 
Let me know if that wouldn't work.

**Comment by maxbrunsfeld** [comment]
Yeah, I think it sounds like a better idea than what I suggested.
