### ISSUE TITLE
tree-view show folder in green even if new file has been removed

### ISSUE THREAD

**Issue by shawninder** [atom/atom#8487]
Repro:

1. Open the root of a git repo in atom 
2. Create a new file in one of the directories
3. Notice that directory becomes green in the tree-view
4. Remove the new file
5. EXPECT the directory to not be green
6. OBSERVE it is still green

**Comment by mnquintana** [comment]
Thanks for the report! This looks like a duplicate of https://github.com/atom/tree-view/issues/498 – please subscribe there for updates.

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Comment by shawninder** [comment]
Ah, my bad, thanks
