### ISSUE TITLE
Atom sometimes doesn't load the project on window reload in dev mode

### ISSUE THREAD

**Issue by olmokramer** [atom/atom#8488]
I haven't found solid reproduction steps for this, but sometimes when I'm working on an Atom package, Atom doesn't reload the project after a window reload. It makes working on packages a real pain, because I have to open the project folder from Atom again and again.

Here's what I do:

1. `cd` to project dir, e.g. `cd ~/projects/atom/minimap-codeglance`
2. `apm link -d`
3. `atom -d`
4. Make some edits to some files
5. Run `window:reload` command with keybinding <kbd>ctrl-alt-r</kbd> (haven't tested running it from the command palette or the menu)
6. **BUG** (doesn't happen all the time) Atom opens an empty window, no tree view, no open files, nothing. I can open the project I was working on with <kbd>ctrl-shift-o</kbd> and all is fine.<br> **Expected** Atom opens the project folder I was working on, shows it in the tree view and opens files that were open when I hit reload.

This is using Atom 1.0.8-a8e80a2 on Debian 9

I'll let you know if I find 100% reproduction steps.

**Comment by maxbrunsfeld** [comment]
Does this happen if you run Atom in `safe` mode? When it happens, it may mean that an exception was thrown during the window's teardown process. Can you check the `Preserve log` box in the javascript console and report if you see any errors?

**Comment by olmokramer** [comment]
Doesn't happen right now, but I'll keep `Preserve log` on for now (never noticed it, so thanks!) and check if it's something in the window teardown process.

**Comment by maxbrunsfeld** [comment]
Ok, I'm going to close this out for now, but I'll reopen if you find that something's happening in safe mode. Thanks!
