### ISSUE TITLE
Snippet won't load

### ISSUE THREAD

**Issue by jlarget** [atom/atom#8491]
On startup I get this error message.  It comes from having an asterisk in a SQL snippet.  Here is the error message from main scree alert it is followed by the snippet.
Tks
Jerry A

Failed to load snippets from '/home/jerry/.atom/snippets.cson'
/home/jerry/.atom/snippets.cson: unexpected *

SELECT All990s.* INTO BC990s
FROM All990s
INNER JOIN BCOrgs
ON All990s.EIN=BCOrgs.EIN;

**Comment by maxbrunsfeld** [comment]
Can you share your entire `snippets.cson`?

**Comment by jlarget** [comment]
Maxs,
     I've just started using atom so I only had the one snippet in there as
it wasn't making atom happy.  Since I wrote the report I've deleted the
snippet I sent you.  The remainder of the snippet file was the canned stuff
that come with the application.
Cheers
Jerry A

**Comment by maxbrunsfeld** [comment]
@jlarget Ok, thanks. If you're no longer having a problem, I'm going to close this out. If you'd still like help making this snippet work, you can add it back, and post the contents of the file, and I'll help you troubleshoot.
