### ISSUE TITLE
Not changing content type after renaming

### ISSUE THREAD

**Issue by CaledoniaProject** [atom/atom#8492]
Hi I created a xxx.html and i saved it

Now I rename it to xxx.php and the content type remains as `html`, was it supposed to be a bug? 

Close & reopen works fine

**Comment by redaktor** [comment]
It seems Atom [1.0.7] does not check if a file changed in general (this should happen whenever a tab gets focus).
Working on a 'build' tool, writing modules. When they are open and do change I also need to Close & reopen !
cc. @CaledoniaProject fyi

**Comment by izuzak** [comment]
@CaledoniaProject Can you reproduce this only with HTML files, or can you reproduce this will all file types? For example, do you see this when you rename a foo.css file to foo.js?

**Comment by 50Wliu** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8492#issuecomment-136676498. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
