### ISSUE TITLE
Failed to load the todo-manager package

### ISSUE THREAD

**Issue by cassiopaia** [atom/atom#8493]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Failed to load the todo-manager package

```
At undefined

SlickGrid requires jquery module to be loaded
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "bower-install"
    ],
    "themes": [
      "seti-ui",
      "watson"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 12,
    "backUpBeforeSaving": true,
    "showInvisibles": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
bottom-dock, v0.3.2
hyperclick, v0.1.4
minimap, v4.13.1
pigments, v0.11.0
project-manager, v1.15.11
react, v0.12.6
remote-atom, v1.2.6
remote-edit, v1.8.15
seti-icons, v0.4.2
seti-ui, v0.8.0
todo-manager, v0.2.1
watson, v0.2.2

# Dev
No dev packages
```

**Comment by zoidbergwill** [comment]
I'm still having this issue, did you manage to resolve it?

Should I re-file this issue in the [todo-manager](https://github.com/benjaminRomano/todo-manager) repo?

**Comment by cassiopaia** [comment]
not solved yet .. so maybe yes it would make sense to re-open it on todo-manager repo!

**Comment by p-ho** [comment]
Yep I can confirm it, too: Not resolved.
