### ISSUE TITLE
Fuzzy Find not finding

### ISSUE THREAD

**Issue by brec-c** [atom/atom#8495]
sorry if this is a dupe.  too hard to figure that out.

I've opened atom using cmd line like this: > atom .

the cwd has 20-25 js files.

I hit cmd-t (on a mac) to bring up the new tab / fuzzy finder and start typing the name of a file.  and the the spinner in the filelist section starts spinning and never stops.

enjoy this animated gif of the issue:
http://cl.ly/cji3/Screen%20Recording%202015-08-24%20at%2003.21%20PM.gif

**Comment by maxbrunsfeld** [comment]
It looks like you're using some custom fuzzy-finder package. Does this happen if you open that directory in safe mode (`atom --safe`)?

**Comment by brec-c** [comment]
i'll check that out.  noticed that cmd-p launches the UI that I actually want to use.  according to my keymaps though they're both doing the same thing though

**Comment by brec-c** [comment]
--safe does fix it.  now to figure out where / how to eradicate all plugins.

thanks.
