### ISSUE TITLE
activationHooks grammar-used does not activate package when running specs

### ISSUE THREAD

**Issue by melke** [atom/atom#8498]
In Atom 1.0.7, the specs in https://atom.io/packages/markdown-folder can no longer be executed. They all timeout in waitsForPromise, probably due to the fact that the markdown-folder package is never loaded. 

In package.json:
```
"activationHooks": [
    "language-gfm:grammar-used"
  ],
```  

In spec:
```
  beforeEach ->
    workspaceElement = atom.views.getView(atom.workspace)
    activationPromise = atom.packages.activatePackage('markdown-folder')
    waitsForPromise ->
      activationPromise
    waitsForPromise ->
      atom.workspace.open('test.md')
```
The activationPromise never completes, so all spec tests timeout after 5000 ms.

The exact same code and spec used to work fine in the Atom version that was the latest in mid-July 2015. 

Tested in Atom 1.0.7 on Max OSX. 
In normal use situations (when editing a markdown file), the markdown-folder is activated and works fine.

**Comment by melke** [comment]
Any comments, please?

**Comment by benogle** [comment]
Are there any errors in the markdown-folder activation method? Remove all the code from the activation method. Does it still timeout? Are there any issues in the eval of the package's main file?

**Comment by melke** [comment]
Hi @benogle Thanks for commenting. It still times out with all code in the activation method removed. No errors show up anywhere. I believe the problem is that the activationhook for loading the package is never fired for some reason: Here is the activationhook in package.json:
```
"activationHooks": [
    "language-gfm:grammar-used"
  ]
```
So when the spec test does the following, the package is never activated, so the specs timeout:
```
  beforeEach ->
    workspaceElement = atom.views.getView(atom.workspace)
    activationPromise = atom.packages.activatePackage('markdown-folder')
    waitsForPromise ->
      activationPromise
    waitsForPromise ->
      atom.workspace.open('test.md')
```

**Comment by benogle** [comment]
Ah, right. You need to dispatch that hook in your specs.

**Comment by melke** [comment]
Ok, but it used to work, but maybe that was due to an old bug or something? How do I dispatch it myself in the spec?

**Comment by benogle** [comment]
Find and replace uses activationHooks. See this spec: https://github.com/atom/find-and-replace/blob/master/spec/find-view-spec.coffee#L38-L45

**Comment by melke** [comment]
I'm sorry, but it doesn't seem to be the same thing. find-and-replace is a command. language-gfm:grammar-used should be trigged when I open the test.md file? Also in the spec, right? Or how can I explicitely trigger language-gfm:grammar-used in the spec?

**Comment by benogle** [comment]
I dont know how the `language-gfm:grammar-used` commands work. If that's the case, then you will need to open the file before waiting for the activation promise.

**Comment by melke** [comment]
I'm not sure that's possible, isn't `atom.workspace.open` async? So that's why the waitsForPromise is needed in the first place; to wait for the file to open before running the individual spec tests.
Note also, that this used to work in a previous Atom version.

**Comment by benogle** [comment]
Try swapping the waits functions:

```
  beforeEach ->
    workspaceElement = atom.views.getView(atom.workspace)
    activationPromise = atom.packages.activatePackage('markdown-folder')
    waitsForPromise ->
      atom.workspace.open('test.md')
    waitsForPromise ->
      activationPromise
```

**Comment by melke** [comment]
Yes, I tried that. Still timeout.

**Comment by benogle** [comment]
Is that command getting triggered when a file opens? Do you have the gfm grammar activated?

**Comment by melke** [comment]
Yes, at least it's activated when I just open the test.md file. I can see that it's activated and the status area in the bottom right corner says "Github markdown".

**Comment by benogle** [comment]
In your specs, you will need to activate the `language-gfm` package. Is that currently happening?

**Comment by melke** [comment]
I'm assuming that language-gfm should be activated by opening the test.md file. But it seems like it's not activated when opened within the context of the spec. Maybe that is what is differing between the Atom versions?

**Comment by melke** [comment]
@benogle Should this issue still have the tag more-information-needed? Is there any more needed at this point?

**Comment by benogle** [comment]
Yeah, I still think this is an issue with the specs. Try 

```coffee
  beforeEach ->
    workspaceElement = atom.views.getView(atom.workspace)
    waitsForPromise ->
      atom.packages.activatePackage('language-gfm')
    waitsForPromise ->
      atom.workspace.open('test.md')
    waitsForPromise ->
      atom.packages.activatePackage('markdown-folder')
```

**Comment by melke** [comment]
@benogle I tried the above suggestion, but I still get the timeout, along with another error.

<img width="795" alt="screen shot 2015-09-20 at 11 43 42" src="https://cloud.githubusercontent.com/assets/838604/9980141/4e48785e-5f8d-11e5-97ff-7029713c16c2.png">

**Comment by melke** [comment]
@benogle Since this used to work in Atom 1.0.3, I suspect that it might actually be a new bug in Atom. Maybe you could open my package in developer mode and try it out yourself?

**Comment by melke** [comment]
@benogle Should this issue still have the tag more-information-needed? Is there any more information needed at this point?

**Comment by benogle** [comment]
Closing in favor of https://github.com/melke/markdown-folder/pull/8
