### ISSUE TITLE
Package architecture error: amd64 does not match armhf

### ISSUE THREAD

**Issue by henrywright** [atom/atom#8502]
Hey guys,

`sudo dpkg -i /home/henrywright/Downloads/atom-amd64.deb`

Gives me the error:

> package architecture (amd64) does not match system (armhf)

**Comment by 50Wliu** [comment]
That is because you are trying to install a package meant for x64 systems on an ARM system.  Please see #7822 for the current status of running Atom on ARM.

**Comment by henrywright** [comment]
@50Wliu Thanks for the info.

**Comment by cantalupo555** [comment]
Solution
`sudo dpkg --add-architecture i386` [32 bits]
`sudo dpkg --add-architecture amd64` [64 bits]
`sudo apt-get update`
`sudo dpkg -i package.deb`

**Comment by cantalupo555** [comment]
@Arcanemagus It worked well here.
http://www.empirion.co.uk/linux/teamviewer-package-architecture-i386-does-not-match-system-amd64/

**Comment by rsese** [comment]
Thanks @cantalupo555 @Arcanemagus :+1:  Going to go ahead and lock this since the original issue was addressed, Atom doesn't officially support ARM, and the issue was closed years ago.
