### ISSUE TITLE
Add: File Find Results

### ISSUE THREAD

**Issue by jcalfee** [atom/atom#8504]
Just like the "Project Find Results" list, the "File Find Results" list is needed.

**Comment by maxbrunsfeld** [comment]
Could you explain the workflow that you're imagining in a bit more detail?

I would think that when searching a single file, you wouldn't want a separate list, because you're already looking at the file, and the search results are highlighted inline.

**Comment by jcalfee** [comment]
It is incredibly useful, you would be surprised ..
From jEdit
A+.	HyperSearch for word under the caret.


Would you consider trying it?  Open a file, select a word then alt+. .. The first time it shows a popup, but you can immediately tell it to dock right.  This is a very good place.  It stays visible until you close it.  You can click through each match.  Even if you change the matching text it will remain in the match list (many times you will want to revisit that code position).  It is very smart too, you can change the line counts (add or remove lines) and it will remain on target for all the other matches.  This is exactly how I would envision find in projects working.  It is very hard for me to leave jEdit without that working so well, it is a huge productivity gain.  In a similar way, Find in Products should revisit changes even if they matching text does not match anymore, the programmer will need to review or adjust that logic  until it is owrking and the find results can be replaced by the next round of refactorings.

**Comment by maxbrunsfeld** [comment]
OK, that's interesting feedback. Would you mind re-opening this issue on the [find-and-replace](https://github.com/atom/find-and-replace) package? It also be helpful if you included some screenshots or GIFs of UI interactions that you find useful in jEdit.
