### ISSUE TITLE
Docking will greatly simplify window splitting

### ISSUE THREAD

**Issue by jcalfee** [atom/atom#8505]
Atom can remove the need for plugins to split the window.  Splitting is really for user files.  For example, "Project Find Results" should be dockable [left, right, top, bottom] ..

I recommend installing jEdit to explorer this feature set.  IMO, jEdit is carefully planned out and minimally implemented in a simple but highly functional way.  I would consider mimicking the feature as closely as possible.

**Comment by maxbrunsfeld** [comment]
Could you reopen this issue on the [find-and-replace](https://github.com/atom/find-and-replace) package?

Also, note that if you prefer an alternative UI for find-and-replace, you can simply disable our default package, and install your own.

Personally, I think there are a *lot* of advantages to showing project search results in their own pane. We value screen space for code very highly. I think it really kills productivity to have ancillary UI elements (like some kind of 'dock') obscuring the actual code that you're working on. With the current design, when you're browsing search results, you have lots of room to do that, and when you switch to reading code, you have lots of room to do that.

**Comment by jcalfee** [comment]
Ok .. just fyi the docking in jedit is optional and collapses into buttons on the side bar.  So it is the width of 1 character wide button down the side line (text is rotated 90 degrees) If you choose to start docking plugins ..  I think it separates concerns for text editing and plugin interfaces ..
