### ISSUE TITLE
Project find and replace improvements 

### ISSUE THREAD

**Issue by a7madgamal** [atom/atom#8517]
Although I'm really glad I switched from Netbeans to Atom and I love many things about it. I do miss some features in the Project wide Find\Replace functionality so I will try to list them here:

1. I think the results screen shouldn't be a normal tab because sometimes it's harder to find it when many taps are open!
I think It's better to have a results as a panel instead of a normal tab 

2. I should be able to have multiple search\replace instances without having to reuse the same instance! sometimes you want to search for multiple keywords and currently I'm only able to have one search instance at a time

3. When replacing, it's VERY important to be able to select or filter out some results. It really sucks when I want to replace 99 results from 100 and I cancel the whole thing just for one result I want to skip!

That's my basic thoughts and after discussing we can find a more specific features and I can then split them into different features or tickets
Now I really have to go back to work :D

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace? Thanks!

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Comment by a7madgamal** [comment]
sorry for that XD
