### ISSUE TITLE
Please consider restoring multiple cursors on undo

### ISSUE THREAD

**Issue by zyklus** [atom/atom#8518]
Just what the title says :)

**Comment by mnquintana** [comment]
I think this is a duplicate of https://github.com/atom/atom/issues/8178 and was just fixed via https://github.com/atom/atom/issues/8506 for the next release of Atom (1.0.8). Let me know if I'm misunderstanding though.

**Comment by zyklus** [comment]
:+1: sorry for the dupe!

**Comment by maxbrunsfeld** [comment]
@zyklus No problem! Really sorry for this bug hung around for so long.
