### ISSUE TITLE
"Replace all" tooltip covers options

### ISSUE THREAD

**Issue by fulldecent** [atom/atom#8522]
![screen shot 2015-08-26 at 11 59 41 am](https://cloud.githubusercontent.com/assets/382183/9498870/1d64d306-4bea-11e5-9244-7580f2511db4.png)

**Comment by maxbrunsfeld** [comment]
When the `Replace All` button is enabled (after you've run a search), `command-enter` does the same thing as clicking the button.

**Comment by 50Wliu** [comment]
Duplicate of atom/find-and-replace#501, please subscribe there for updates.
