### ISSUE TITLE
All programs stop responding simultaneously after running Atom

### ISSUE THREAD

**Issue by SilentSpike** [atom/atom#8523]
Atom version: 1.0.7
OS: Windows 7 Home Premium x64
Behaviour: Never seen before atom.
Packages: [editorconfig](https://github.com/sindresorhus/atom-editorconfig) and an [Arma language package](https://github.com/acemod/language-arma-atom)

First of all, I apologise that I can't provide any more information right now. All of my evidence is circumstantial.

Since switching to atom I've started experiencing seemingly random "crashes" where all of my programs stop responding (including explorer) and I can't open the task manager or even use ctrl+alt+delete. The only fix I've found for this is a hard reset.

Steps I've taken to find out what's causing this:
- Booted in safe mode and ran a scan with MSE and Malwarebytes. Nothing found.
- Ran a disk check. Reports no issues.
- Ran a memory diagnostic. Reports no issues.
- Checked event viewer for any problems.

I'm not the best at debugging issues on this scale (at this point, I actually experienced another of these crashes while typing this - thankfully chrome remembered this post) but I believe these are in some way related to atom as:
- They only ever seem to happen while or shortly after it has been open.
- They only started happening since I started using it.
- One time I had the task manager open beforehand and saw many instances of the following processes running (which I believe are atom related):
  - cmd.exe *32
  - node.exe *32
  - conhost.exe

![](http://i.imgur.com/A9wZeln.png) Here is a print screen I managed to save from the crash I experienced while typing this (one of my programs remained open and thank god it could upload images).

Does it seem like this is caused by atom or am I looking in the wrong place? Also are there any debugging steps I can make to get more information from atom that might pertain to this issue?

**Comment by Zireael07** [comment]
Do you see atom.exe * 32 in your Task Manager? There might be multiple entries - how much memory do they use up?

**Comment by 50Wliu** [comment]
cmd.exe gets initialized by Atom when checking for package updates.  I believe that then calls node.exe which calls conhost.exe.  I might have the order mixed up somewhere, but all three are definitely used by Atom for package updates.

**Comment by SilentSpike** [comment]
My processes while atom is open and idle (no files or folders open):
![](http://i.imgur.com/s7RgZ8K.jpg)

Immediately after closing the same instance of atom:
![](http://i.imgur.com/KsqPhpn.jpg)

Those cmd, node and conhost processes don't seem to close with time or anything. They just remain open.

I'm running atom as an admin user (though not launching it as admin) and have had no issues with other programs using %APPDATA% in the past.

Now that you mention package updates, the first time this issue occurred was when atom tried to update to the current version of editorconfig (1.1.1) from the previous version and it was a seemingly indefinite process so I closed the program to re-launch and retry. If my memory is correct, everything crashed before I could re-launch though.

**Comment by SilentSpike** [comment]
Well I can confirm that purging and reinstalling atom has fixed the issue, so something somewhere probably became corrupt and atom was handling it extremely badly.

Simple fix, although it does allude to some form of underlying critical issue under the wrong circumstances.

**Comment by damieng** [comment]
Hi SilentSpike.

About the only thing I can think of that might have that kind of effect would be some form of rendering bug - the rendering subsystem is in the kernel and can easily spread to other apps that way.  

Given however the issue has disappeared for you I'm going to close this bug. Feel free of course to reopen it if it happens again.
