### ISSUE TITLE
Markdown Preview and webgl

### ISSUE THREAD

**Issue by ezequias** [atom/atom#8524]
Hello everyone.

I am having trouble to preview, correctly, a project (html/css/js) I checked out from github from https://github.com/dataarts/webgl-globe with Atom.

I know somewhere in the past I could see it using Brackets (i suppose it has an internal web server but I have no intent to download it and keep using Atom.

Is there any way to run an internal web server, as brackets does, on Atom?

Best regards
Ezequias Rocha

**Comment by rugk** [comment]
If you need a webserver using PHP you could try this package: https://atom.io/packages/php-server

For just displaying HTML/JS/CSS you do not need a web server, but just a browser. And as Atom is built on out of Chromium this is easily possible. E.g. by using this package: https://atom.io/packages/atom-html-preview

**Comment by ezequias** [comment]
Thank you @rugk this package is good but for this project I mentioned I suppose It only work on an internal webserver. Thank you.

I think the website uses WebGL and it not load properly without a webserver.

Regards
Ezequias Rocha

**Comment by rugk** [comment]
> I think the website uses WebGL and it not load properly without a webserver.

No:
> WebGL (Web Graphics Library) is a **JavaScript** API for rendering interactive 3D computer graphics and 2D graphics within any compatible **web browser** [...]

https://en.wikipedia.org/wiki/WebGL
(highlighting by me)

:smiley:

**Comment by ezequias** [comment]
Sorry. I didn't know. Unfortunately it is not working even on html preview. I ask you to check out the project and see for yourself. Please see https://github.com/dataarts/webgl-globe

**Comment by mnquintana** [comment]
I think for a question like this you might have better luck browsing / asking on [Discuss](https://discuss.atom.io/), as live previewing HTML projects is a subject that's come up quite frequently there.
