### ISSUE TITLE
thread-sleep not available

### ISSUE THREAD

**Issue by ScriptorNY** [atom/atom#8528]
Hello,

When installing the atom editor, this message is risen:

```
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
```

node version: 0.12.7
npm version: 2.11.13

Both `spawn-sync` and `thread-sleep` are installed.

Thank you very much in advance :)

**Comment by 50Wliu** [comment]
This is caused by [sindresorhus/os-locale](https://github.com/sindresorhus/os-locale).
