### ISSUE TITLE
Untracked and staged files show up with the same color

### ISSUE THREAD

**Issue by javawizard** [atom/atom#8529]
On Atom 1.0.7 and OS X 10.10.1, untracked and staged files both show up green, with no way to differentiate between the two. It ought to be possible to have them be colored differently so that I can tell which files I still need to stage before committing.

<img width="714" alt="screen shot 2015-08-26 at 4 12 18 pm" src="https://cloud.githubusercontent.com/assets/874635/9507745/7bfbe88c-4c0d-11e5-825b-aa7d0b53021e.png">
<img width="714" alt="screen shot 2015-08-26 at 4 12 25 pm" src="https://cloud.githubusercontent.com/assets/874635/9507747/7f009abe-4c0d-11e5-9a42-d55cb42a0fb0.png">
<img width="682" alt="screen shot 2015-08-26 at 4 12 46 pm" src="https://cloud.githubusercontent.com/assets/874635/9507855/3ad18c80-4c0e-11e5-9cf3-9dc5552145eb.png">

**Comment by th-we** [comment]
Doing the following:

    $ git init
    Initialized empty Git repository in /tmp/gittest/.git/
    $ touch untracked
    $ touch committed
    $ git add committed 
    $ git commit -m "initial commit"
    [master (root-commit) c148523] initial commit
     1 file changed, 0 insertions(+), 0 deletions(-)
     create mode 100644 committed
    $ touch added
    $ git add added
    $ git status
    On branch master
    Changes to be committed:
      (use "git reset HEAD <file>..." to unstage)

    	new file:   added

    Untracked files:
      (use "git add <file>..." to include in what will be committed)

    	untracked

    $ atom committed

As can be seen from the screenshot, the tree view adds the class `.status-added` to both the untracked and staged file, but not the committed one (which is visualized as untracked). The inverse might be sensible.

![bildschirmfoto vom 2016-01-24 18 03 36](https://cloud.githubusercontent.com/assets/1147152/12537693/69e8da36-c2c5-11e5-852e-c0ff828c622d.png)
