### ISSUE TITLE
How to disable little blue hovering hint over replace buttons

### ISSUE THREAD

**Issue by iosdev-republicofapps** [atom/atom#8532]
I love Atom, but it's almost unusable for me now since a recent version seems to have added a little hovering blue hint popup over the search and replace buttons.  This little hovering blue hint/affordance is intensely distracting and it covers up some of the important search buttons.  I cannot make it go away.

I am using Atom 1.0.7 on Mac OS X 10.10.5.  Please see attached screenshot.

Please help ... I'm on the verge of abandoning Atom due to this recent change and I can't seem to turn it off.

![atomunusableduetoannoyingbluehint](https://cloud.githubusercontent.com/assets/1666680/9509520/7d211c70-4c15-11e5-8b4a-e451f1b6c737.png)

**Comment by maxbrunsfeld** [comment]
You can always do this in your `styles.less` file:

```css
.tooltip {
  display: none !important;
}
```

Though that hides *all* tooltips in Atom.

Could you file this issue on Atom's [find-and-replace](https://github.com/atom/find-and-replace/issues) package? There's already one issue that seems related: https://github.com/atom/find-and-replace/issues/501, so you might just want to subscribe to that.
