### ISSUE TITLE
Manually change order of Project folders

### ISSUE THREAD

**Issue by fabianschwarzfritz** [atom/atom#8538]
I would love to be able to manually order the project folders in the left project/files sidebar. Currently I am closing and re-opening the project folders to get the order I want. 

It would be cool if there was a drag and drop functionality that would allow me to reorder my projects.

**Comment by izuzak** [comment]
Please re-open this on the package's issue tracker: https://github.com/atom/tree-view, and check out this PR which is working towards this feature: https://github.com/atom/tree-view/pull/525

You might also want to check out the [general issue submission guidelines](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues).
