### ISSUE TITLE
Multi line mouse select breaks in text editor when editor is small enough

### ISSUE THREAD

**Issue by hannes-landeholm** [atom/atom#8539]
Steps to reproduce:

1. Open text file with lots of lines of code.
2. Resize text editor vertically so only 5 lines is visible.
3. Try to select two lines with the mouse.
4. As soon as two lines are selected the text editor begins to scroll rapidly in a state that is only possible to exit by stop selection.

The practical use case for me is when you split the editor vertically it's nothing strange to have just 5 lines in one of the panes.

Suggested solution is to use a relative auto vscroll select area instead of an absolute.

OS: Mac OS X 10.10.5
Atom 1.0.7

**Comment by hannes-landeholm** [comment]
Would be nice to have to possibility to disable the auto vedge select scroll altogether as I'll happily use the scroll wheel to scroll when selecting.

**Comment by 50Wliu** [comment]
Confirmed on Atom 1.0.7, Windows 10 x64.  It's possible to stop, but you have to use very, very subtle movements with the mouse.

**Comment by nathansobo** [comment]
Adding this to the short list.
