### ISSUE TITLE
[Metabug] Find a proper solution for the "z-index problem"

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#8540]
- https://github.com/atom/atom/pull/8537
- https://github.com/atom/atom/pull/8098
- https://github.com/atom/atom/pull/8112
- https://github.com/atom/git-diff/issues/71

Those feel dirty/hacky (@as-cii agrees, I believe), so a better/proper solution should be found.

**Comment by simurai** [comment]
Also #6857

The `position: fixed` solution from @Varanas [comment](https://github.com/atom/atom/issues/6857#issuecomment-128733330) might work. But only for things that keep position and are not part of a scrollview.
