### ISSUE TITLE
Cannot override native keybindings

### ISSUE THREAD

**Issue by rugk** [atom/atom#8541]
If I e.g. want to add this key binding it won't work:
```less
 'atom-text-editor':
   'ctrl-d': 'editor:duplicate-lines'
```

Just because ctrl-d is set as ```native!```. However AFAIK there is no command on Windows which triggers something when pressing ctrl-d (notepad also uses CTRL+D for duplicating lines), so I tried to override it.
But it's not only that this specific override does not work - no. If I try to use this it completely disables my keybindings config and also other keybindings do not work.

**Comment by maxbrunsfeld** [comment]
It's not because `ctrl-d` is mapped to `native!`; it's because [the selector](https://github.com/atom/atom/blob/master/keymaps/base.cson#L28) used for the existing `ctrl-d` mapping is more specific than yours. I'm not sure why `body` is used there, but you could try this for now:

```coffee
'atom-text-editor.native-key-bindings':
   'ctrl-d': 'editor:duplicate-lines'
```

**Comment by maxbrunsfeld** [comment]
I'm going to close this out, as I believe that should solve your issue. Let me know if you'd like me to reopen.

**Comment by rugk** [comment]
No it does not work. But at least I can use my other keybindings.

Just note that even if it would have worked there would still be the issue that this breaks my keymap.cson file:
> But it's not only that this specific override does not work - no. If I try to use this it completely disables my keybindings config and all other keybindings do not work too.
