### ISSUE TITLE
highlighting of soft wrapped line

### ISSUE THREAD

**Issue by cognominal** [atom/atom#8549]
Current line is highlighted, which is nice. 
When a line is soft wrapped, the whole line should be highlighted and
the wrap differently highlighted. This would allow to see what is going on
instead of watching the gutter to realize that the line is wrapped.

**Comment by marcofugaro** [comment]
Yup, this issue of one and a half year ago still bothers me, is there a package which fixes this?

**Comment by jdw1996** [comment]
@marcofugaro There is a highlight-line package, but it has the same issue: https://github.com/richrace/highlight-line/issues/85

**Comment by hg42** [comment]
I think that's because each display line of the soft wrapped line is a `<div class="line">`.
You have no chance to distinguish those.
