### ISSUE TITLE
Atom won't start after upgrade

### ISSUE THREAD

**Issue by MatthewNewland** [atom/atom#8559]
OS: Windows 7 64-bit

This morning, I tried to upgrade to Atom 1.0.8 from 1.0.7. Although the updater didn't say that there were any updates available, after I closed and reopened atom, I got this error message:

![atom-javascript-error](https://cloud.githubusercontent.com/assets/9618670/9555509/56293486-4d82-11e5-8a6e-94560a9325cb.PNG)

The taskbar shortcut had been changed to point to the new atom-1.0.8 directory.

I'm not the only one who's experienced this: see [https://discuss.atom.io/t/a-javascript-error-occured-in-the-browser-process/20306](here).

I can roll back to 1.0.7 for now, but it would be nice to upgrade.

**Comment by StartupDino** [comment]
2nded and bumped! :)

**Comment by kevinsawicki** [comment]
@bcoe do you think this is something to raise against `yargs` or `os-locale`?

**Comment by bcoe** [comment]
@kevinsawicki looks like it, @sindresorhus thoughts?

I'll get a hot fix out in yargs ASAP.

**Comment by bcoe** [comment]
@kevinsawicki for your review, I can have this out the door within 10 minutes.

https://github.com/bcoe/yargs/pull/240

**Comment by bcoe** [comment]
@kevinsawicki `+ yargs@3.21.1` should hot fix this issue on Windows.

See https://github.com/bcoe/yargs/issues/241 for further discussion.

**Comment by kevinsawicki** [comment]
Great, thanks for the speedy response.

**Comment by bcoe** [comment]
@kevinsawicki `yargs@3.22.1` is released with the new option `detectLocale(false)` which can be used to disable the automatic locale detection functionality:

https://github.com/bcoe/yargs/pull/242/files

Sorry about this breakage, I really care about keeping yargs a stable project and hope I can get you back on an up-to-date release -- please don't hesitate to reach out to me immediately if anything like this happens again in the future.

**Comment by kevinsawicki** [comment]
> please don't hesitate to reach out to me immediately if anything like this happens again in the future.

Thanks, sounds good :+1:

**Comment by StartupDino** [comment]
3rd day on Github, so I'll admit I am completely lost here. I've tried re-downloading, re-installing, even uninstalling...and nothing seems to be working.
![image4144](https://cloud.githubusercontent.com/assets/13918282/9559019/c0312f22-4dba-11e5-86d2-1d119283790c.png)

**Comment by 50Wliu** [comment]
@StartupDino for now, you can try either downgrading to 1.0.7 or waiting until the next release.  One final option if you're interested would be to [build Atom](https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md) by yourself.

**Comment by maxbrunsfeld** [comment]
@StartupDino Sorry for this. There will be another release today.

**Comment by kevinsawicki** [comment]
@StartupDino  I just published `1.0.9`which should have this fixed, you can download it as `AtomSetup.exe` from https://github.com/atom/atom/releases/tag/v1.0.9

Apologies for this regression.

**Comment by MatthewNewland** [comment]
Thanks to all involved for the speedy response! I just this morning got back to my Windows box, and 1.09 is working great.
