### ISSUE TITLE
Indent guides draw_active like sublime text

### ISSUE THREAD

**Issue by jorge8168711** [atom/atom#8560]
it will be great if the indent guides they will be displayed as sublime text, draw the guides containing the caret in a different color.
In that way highlights more the active indent guide.

### Sublime text
![image](https://cloud.githubusercontent.com/assets/7266089/9555591/ad71c454-4d93-11e5-8096-b79b3728e1fa.png)

### Atom
![image](https://cloud.githubusercontent.com/assets/7266089/9555627/e4656858-4d93-11e5-8345-4af85ed37ab1.png)

I dont know if that is possible, but is just a suggestion.

**Comment by izuzak** [comment]
@jorge8168711 Have you tried using this package: https://atom.io/packages/indent-guide-improved ? I think it offers exactly what you want.

**Comment by jorge8168711** [comment]
thanks a lot @izuzak this this is exactly what I needed.

**Comment by izuzak** [comment]
Cool, going to close this for now since there's a package which implements this feature.
