### ISSUE TITLE
Random "Error compiling Less stylesheet" errors when switching syntax themes

### ISSUE THREAD

**Issue by izuzak** [atom/atom#8565]
Just noticed this on Atom 1.0.9-020c11d on OSX 10.10.5 after I tried to switch the syntax theme from One Dark to Base16 Tomorrow Dark:

<img width="459" alt="screen shot 2015-08-29 at 07 37 22" src="https://cloud.githubusercontent.com/assets/38924/9560697/cd5bc658-4e23-11e5-9fcb-4731c7fda859.png">

Notice how two errors are thrown first for the Base16 Tomorrow Dark, and then for the One Dark UI (which was already set as the UI theme).

I haven't touched any of those files. After I restarted Atom, Base16 Tomorrow Dark was successfully loaded at startup and I could switch themes just fine (no errors thrown).

I remember this happened once a few weeks/months ago as well, but I couldn't reproduce it back then either. I noticed one other similar issue (https://github.com/atom/atom/issues/6797), but that's related to styles.less.

cc @kevinsawicki in case you have any :thought_balloon: about this

**Comment by kevinsawicki** [comment]
Is this consistently happening or just the one time?

**Comment by izuzak** [comment]
It's not happening consistently -- happened that one time, and I remember it happening once a few weeks ago as well. Tried to reproduce it a dozen times now and couldn't, with the same Atom setup as when it did happen.
