### ISSUE TITLE
Error: Failed to load package 'atom-color-highlight'

### ISSUE THREAD

**Issue by JPomichael** [atom/atom#8567]
Error: Failed to load package 'atom-color-highlight'
![11111111111111111](https://cloud.githubusercontent.com/assets/1901960/9560838/3b5359a8-4e5d-11e5-942e-884f56a19bf0.png)

![22222222222](https://cloud.githubusercontent.com/assets/1901960/9560839/44194af2-4e5d-11e5-9ba4-c33ed8bef8f5.png)

**Comment by 50Wliu** [comment]
Please try installing the [pigments](https://atom.io/packages/pigments) package instead as that is the replacement for atom-color-highlight.

/cc @abe33
