### ISSUE TITLE
Shift + enter keymap

### ISSUE THREAD

**Issue by huovnn** [atom/atom#8572]
In my keymap I've:
```cson
'atom-text-editor':
   'shift-enter': 'editor:select-to-end-of-line'
```

Doesn't work. Should this even work?

**Comment by 50Wliu** [comment]
This is working for me.  Are there any other keybindings in your keymaps file?  If so, can you paste the whole file here?  In addition, does it work in safe mode (`atom --safe`)?  And finally...what Atom version and what OS are you using?  Thanks.

**Comment by huovnn** [comment]
Mac OSX Yosemite and Atom version is 1.0.9. I don't have anything else in my keymap file. Tried safe-mode, did not help.

**Comment by 50Wliu** [comment]
Ok.  Then can you open up the Keybinding Resolver (<kbd>Cmd+.</kbd>), press <kbd>shift+enter</kbd>, and report the result here (preferably in an image)?

**Comment by segevofer** [comment]
it's probably because there is a "stronger" rule by darwin.json. try adding this rule instead:

'atom-workspace atom-text-editor:not([mini])':
  'shift-enter': 'editor:select-to-end-of-line'

**Comment by denzo** [comment]
@segevofer Thanks! Your suggestion worked for me,

**Comment by 50Wliu** [comment]
Closing as resolved.
