### ISSUE TITLE
Fuzzy file finder not finding all files?

### ISSUE THREAD

**Issue by JesseLeite** [atom/atom#8573]
Fuzzy file finder not finding all files?  At least not as I’d expect.  In this screencast example, I'm looking for Model.php deep within /vendor.  You'll see it exists in sidebar, but fuzzy finder doesn't show Model.php within the result set unless I explicitly type 'Model.php' with file extension.  (Note: I have 'Exclude VCS Ignored Paths' unchecked, so Atom is indexing within /vendor.)

[Example Screencast](http://recordit.co/3J13jqCKQ9)

**Comment by 50Wliu** [comment]
Can you please move this to [atom/fuzzy-finder](https://github.com/atom/fuzzy-finder)?

**Comment by JesseLeite** [comment]
@50Wliu No problem, thanks for link.
