### ISSUE TITLE
Ability to disable auto-indent while typing.

### ISSUE THREAD

**Issue by envygeeks** [atom/atom#8576]
More often than not Atom's auto indent feature gets auto-indentation wrong for example:

```sh
for f in $(git show --pretty="format:" --name-only); do
  [[ "$f" ]] {
    file=$(readlink -f "$f")
    if grep -E "^$root/dockerfiles/"
    then

    fi
  }
done
```

Will always lead to anything typed after then being indented backwards all the way into the for statement.  This behavior happens quite often in bash and Ruby when working with complex sets of code where Atom expects one thing but the other is actually valid.

It would be nice to be able to disable this auto-indent in the middle of typing instead of waiting for changes to make it into a specific language, because Atom is a large project, so changes don't happen over night, but this feature would make it so that it can be fixed.

**To clarify:** I do not wish to remove auto-indentation entirely, just disable it when I start typing.  I don't need it to correct my personal indentation for me, where I choose to indent should really be my business, but when I press enter and go to a new line, indent automatically how you see fit all you want, but once I correct it and start typing, the correct behavior (IMO) would be to let me be because it's a personal choice at that point.

**Comment by envygeeks** [comment]
To add, I know there is a syntax error in that script and it's there to highlight the problem, we have a linter to point out those syntax errors.

**Comment by Zireael07** [comment]
I have the indenting backwards while typing thing in Lua, too.

**Comment by alexandernst** [comment]
Maybe instead of monkey patching errors (like disabling autoindent), just fix the damn thing once and for all. https://github.com/atom/atom/issues/6655 has been open for months.

**Comment by envygeeks** [comment]
Closing in favor of that ticket.

**Comment by Radivarig** [comment]
No ability to disable it? ...

**Comment by dan-higgins** [comment]
Why not just a setting that says "only auto indent on Enter" ? There's no point in auto indenting on every keypress anyway. It's doing MORE work than it needs to.
