### ISSUE TITLE
markdown problem

### ISSUE THREAD

**Issue by chovy** [atom/atom#8577]
https://www.dropbox.com/s/8bvox1c3vgmkvdn/Screenshot%202015-08-29%2013.43.06.png?dl=0

If my markdown code block contains `*.log` the rest of the markdown file formatting is messed up.

**Comment by mnquintana** [comment]
Thanks for the report! This looks like the same issue as https://github.com/atom/language-gfm/issues/44 – closing in favor of that issue.

You might also want to take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.
