### ISSUE TITLE
Race condition when opening files leads to data loss

### ISSUE THREAD

**Issue by ChrisJefferson** [atom/atom#8581]
I have had this problem happen in other circumstances (disconnected windows into the same file), but I seem to be able to reproduce it reliably this way.

Open a terminal, type `atom file.txt & ; atom file.txt` (make sure file.txt does not current exist)

Two windows into file.txt will open. In the top one, type some text, save and close.

The text is not reproduced in the second. Closing this window will prompt to save the file even though you have not typed anything. This will save a blank file, overwriting your text.

**Comment by laceres** [comment]
What version of atom were you using?

**Comment by ChrisJefferson** [comment]
1.0.11, on Mac OS X.

However, I did just try running with --safe, and the bug seems to disappear, so it could be a package I'm running (or just with --safe atom starts faster and avoids the problem)

**Comment by ChrisJefferson** [comment]
Is reproducible with --safe, just only seems to happen about 40% of the time on my machine.

**Comment by ChrisJefferson** [comment]
Just a quick poke on this, I'm not sure what more information you want, and a friend of mine can reproduce it (also on Mac)

**Comment by stereobooster** [comment]
Can reproduce. Expected behaviour second window notice that file changed on the disk and loads updated version (assuming you have no unsaved changes for that file in that tab)
