### ISSUE TITLE
Logitech Smooth Scrolling, Strange Behaviour

### ISSUE THREAD

**Issue by NicoM1** [atom/atom#8582]
Atom 1.0.9: Windows 10

Hi, I recently bought the Mx Master mouse, from Logitech. It comes with software that enables smooth scrolling (the wheel spins freely so it doesn't feel great to have things still scroll in chunks). Now, when atom is inactive, and the mouse is hovered over top of the editor, this behaves as expected: the editor scrolls smoothly, without a set increment. However, once the editor is made active (clicked inside) it will only scroll in distinct chunks. 

Hopefully someone finds a simple fix, however it is not critical,

Nico

**Comment by veegee2** [comment]
I also looking for this feature for some time  but dont know how to make it.

**Comment by msiniscalchi** [comment]
Same here ;(
