### ISSUE TITLE
After replacing all items found during search and replace, Find button remains covered by "Replace Next" balloon

### ISSUE THREAD

**Issue by psnider** [atom/atom#8586]
This ballon remains for a long period of time, and I haven't figured out yet when it disappears.

This  prevents me from clicking on the buttons underneath the balloon,
such as the "Whole Word" button.

I'll add a screenshot the next time I see it.

**Comment by 50Wliu** [comment]
Duplicate of atom/find-and-replace#501, please subscribe there for updates.

**Comment by SlimeQ** [comment]
[find and replace bug](http://i.imgur.com/rCpiaTy.png)

this is so bad, i don't understand why this was closed
