### ISSUE TITLE
Need a way to disable auto-updates -- extremely unfriendly with slow internet

### ISSUE THREAD

**Issue by zyklus** [atom/atom#8591]
I just had to block Atom's access to the internet in order to actually get anything done.

- I'm in Indonesia, internet here sucks in most places
- There's an atom update out and whenever atom is open is _always_ tries to download this update
- It's using 100% of my bandwidth to attempt to download a file that will _never_ succeed
- My internet basically goes from slow-as-a-turtle to non-existent because of this
- I can't disable it

Please provide a way to disable auto-updates.

**Comment by izuzak** [comment]
Can you please add a note to this issue: https://github.com/atom/atom/issues/1882 ? I think that covers this problem as well. 

And yeah, I agree -- it would be really helpful if it was possible to turn that off.

**Comment by MinuteBar** [comment]
please @Atom , kill the auto-update ! It keeps turning on and update. While it should NOT, it ruins my set up !

**Comment by shuaibird** [comment]
While the internet is not an issue for me, I still hope there's an option to disable the auto-update feature, which may cause some packages installed previously not work properly. I've encountered such an embarrassment for a few times and really get bothered.

**Comment by liapis** [comment]
Settings > Core > Automatically Update
![atom](https://user-images.githubusercontent.com/1415893/34462406-3051976c-ee11-11e7-8b3a-d19def2b0050.png)
