### ISSUE TITLE
Cant open folder mounted locally with sshfs

### ISSUE THREAD

**Issue by bitswarming** [atom/atom#8592]
Cant open remote folder mounted with "sudo sshfs -o allow_other ....." .
Sublime and others -  can.
Just receive Editor is not responding message.
Linux.

**Comment by mnquintana** [comment]
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/2456 / https://github.com/atom/atom/issues/1766 – please subscribe there for updates.
