### ISSUE TITLE
San Francisco on El Capitan

### ISSUE THREAD

**Issue by williambout** [atom/atom#8594]
3ac69500b0627067db59ea60f02f456fee6791be

`font-family: 'SF UI Text'` is not working on El Capitan Beta 15A263e
`font-family: '.SFNSText-Regular'` does work.

**Comment by simurai** [comment]
I think `SF UI Text` works for the downloaded version of San Francisco. But good point about also adding `.SFNSText-Regular` that comes with El Capitan Beta.

**Comment by trkoch** [comment]
From what I can tell this doesn't match the system's behaviour *exactly*. For smaller fonts, OS X uses the display variant of SF, not regular. Also fonts prefixed prefixed with a dot are considered private. The most stable approach would be to use `-apple-system`, but this doesn't seem to work in Chrome yet.

**Comment by trkoch** [comment]
Apparently the Blink team considers adding a placeholder string `BlinkMacSystemFont`. However, it is currently reverted. See https://codereview.chromium.org/1266403002/.

**Comment by trkoch** [comment]
The OS is not only switching between text and display. Turns out there is even more trickery involved! Compare https://jsbin.com/fumali/1/edit?css,output.

**Comment by simurai** [comment]
> The most stable approach would be to use `-apple-system`, but this doesn't seem to work in Chrome yet.

That would be nice if something like that gets supported. There is another approach to get the system font with `font: menu` https://github.com/atom/atom/pull/8817. Not sure if that also would change between text and display.

**Comment by williambout** [comment]
@trkoch Here are the values for letter spacing adjustments ![iOS and OS X Tracking](https://pbs.twimg.com/media/CPJkPXlUYAEIh8r.png)

**Comment by trkoch** [comment]
BlinkMacSystemFont has been reintroduced and now works in Chrome (confirmed with 46.0.2490.52). When using this symbolic font, Chrome automatically switches between text and display. However Chrome does not seem to apply the letter spacing adjustments mentioned by @williambout.

**Comment by simurai** [comment]
Awesome.. let's keep it in mind for when it lands in Electron/Atom.

**Comment by markesaaremets** [comment]
SF UI tracking adjustment filed here — https://code.google.com/p/chromium/issues/detail?id=578799
