### ISSUE TITLE
customFileTypes not overriding default file types

### ISSUE THREAD

**Issue by mmcbride1007** [atom/atom#8595]
Per #8144 I would expect to be able to set a custom file type association to override the default syntax. Here's my `config.cson`:

![atom_customfiletypes](https://cloud.githubusercontent.com/assets/6248612/9579239/b967be74-4fb6-11e5-9be0-6d59c3d06545.png)

Based on [this block in grammars-spec.coffee](https://github.com/atom/atom/blob/master/spec/grammars-spec.coffee#L141-L152) I would expect that my config above would use the `.scss` syntax on `.css` files, but I am not seeing that behavior. Am I reading this incorrectly or doing something wrong?

I am running Atom v1.0.9 on OS X v 10.10.4

cc: @maxbrunsfeld

**Comment by thomasjo** [comment]
Your file type specification is incorrect; change `"*.css"` to `"css"`.

**Comment by thomasjo** [comment]
@atom/feedback Would it be worth having some type of validation here, given we could implement one without too much complexity?

**Comment by mmcbride1007** [comment]
:+1: that worked, thanks @thomasjo 

cc: @balexand you mentioned you had a similar issue, check this out.

**Comment by lee-dohm** [comment]
I think validation would be good. I think some documentation is necessary too.

**Comment by balexand** [comment]
@mmcbride1007 Thanks for pinging me with this. That worked.

**Comment by mmcbride1007** [comment]
:+1: for documentation on this.
