### ISSUE TITLE
z-index issue for autocomplete suggestions

### ISSUE THREAD

**Issue by edgartheunready** [atom/atom#8596]
To reproduce, just write something to get the autocomplete list to show, then scroll down. This is on OS X 10.9.5. I would expect the autocomplete list to be hidden when the line it belongs to is no longer visible. This happens in atom 1.0.8 
![atom bug](https://cloud.githubusercontent.com/assets/3502769/9582056/21515f08-4fd1-11e5-87c3-0d8918c280ec.gif)

**Comment by simurai** [comment]
That the autocomplete list overlaps the rest of the UI is intended. Because sometimes the list is quite big and it could be annoying having to scroll to see the whole list.

But I agree, in this case it feels wrong.

**Comment by simurai** [comment]
> I don't think you would want it to auto-hide on-scroll, because that would frustrate users when there was a long list and they accidentally scrolled in the window instead of the list. Maybe, like you suggested, there would be a buffer before it hid.

Yeah, I was more thinking when "scrolling out of sight", like when the list would be 100px-200px past the editor's visible area. Not sure if it should behave like `[esc]` or re-appear if you scroll back up again.

> What if the autocomplete list had a max height, and then you could scroll to see the rest of the suggestions? (maybe it already does)

Seems there is a max height of 10 items

![screen shot 2015-09-02 at 12 04 25 am](https://cloud.githubusercontent.com/assets/378023/9607859/5adf6d9c-5106-11e5-91e5-68f319bb4767.png)

**Comment by lee-dohm** [comment]
This is some good discussion. I do think that this belongs on the autocomplete-plus repository, so I'm going to close this in favor of https://github.com/atom/autocomplete-plus/issues/716. Please subscribe there for updates.
