### ISSUE TITLE
Find/Replace duplication via Regex

### ISSUE THREAD

**Issue by pixelchutes** [atom/atom#8597]
I've noticed in the past few versions of Atom that Find/Replace via Regex now has an unwanted side effect where the replacement value gets duplicated.

### Example:
Here I am simply attempting to add 3 trailing periods to the end of each line:
![regex](https://cloud.githubusercontent.com/assets/352182/9582967/d2d1b004-4fc5-11e5-82a6-ca7a8e6e2a9f.gif)

### Expected Result:
> this is a test...
> this is also a test...
> this may or may not be a test...

### Actual Result:
The resulting trailing periods are actually 6, instead of 3:
> this is a test......
> this is also a test......
> this may or may not be a test......

### Versions
Confirmed on latest Atom v1.0.9, and a few releases before this.
OS X 10.10.4

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace? Thanks!

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Comment by pixelchutes** [comment]
Done. Thanks for sharing the discussion link.
