### ISSUE TITLE
ctrl-alt-b conflicts with `build` package

### ISSUE THREAD

**Issue by noseglid** [atom/atom#8602]
Recently, `Atom` takes the key `ctrl-alt-b` for `editor:move-to-previous-subword-boundary` (https://github.com/atom/atom/blob/master/keymaps/emacs.cson#L7). This conflicts with the [`build` package I am maintaining](https://atom.io/packages/build).

Would it make more sense to have an `emacs-mode` package for people who wants this? This would be akin to the `vim-mode` package which adds `vim` functionalitites to `Atom`.

Right now I am getting reports this keymap takes precedence over mine (https://github.com/noseglid/atom-build/issues/168). Doesn't seem to be that way for everyone though.

**Comment by izuzak** [comment]
Thanks for pointing this out, @noseglid. 

@nathansobo: That keybinding was added in https://github.com/atom/atom/pull/7612. Would we consider changing those keybindings or using the approach suggested by @noseglid? If not, is there some advice we can give to package authors in situations like these?

**Comment by nathansobo** [comment]
As long as the specificity of his selector's binding is greater than or equal to the bundled binding, his package should win. @noseglid could you add an additional selector specifically targeting `atom-text-editor` so your binding wins? I don't want to remove the binding or add the complexity of an additional mode at this time.

**Comment by noseglid** [comment]
Adding `atom-text-editor` instead of `atom-workspace` would limit where the build can be triggered from to the text editor.

**Comment by nathansobo** [comment]
@noseglid You can add it to both selectors simultaneously.

**Comment by noseglid** [comment]
@nathansobo I get that. But in Linux (they seem to be the only ones affected) it will only work when the text editor is active, right?

I can do this for a short-term solution, but it definitely needs to be addressed on a wider scale. This situation could arise from any package (or atom core) adding any keybinding at any point.

**Comment by nathansobo** [comment]
@noseglid If you do 2 bindings like this...

```coffee
'atom-workspace':
  'ctrl-alt-b': 'run-build'
'atom-text-editor':
  'ctrl-alt-b': 'run-build'
```

Then `ctrl-alt-b` will run your command in either context. You just need to override `atom-text-editor` specifically, but it doesn't preclude you from matching in the workspace globally.

**Comment by noseglid** [comment]
Ah that makes sense. That's a good solution for now! Thank you
