### ISSUE TITLE
cannot type a closing brace }

### ISSUE THREAD

**Issue by jarnix** [atom/atom#8606]
Hi,

I'm on Windows 10, using a French azerty keyboard and whenever I type this key: "}" (which is AltGr +) it either does nothing or folds a section of the code which obviously is not what I want. I have to use copy/paste for this character :)

I have this issue while typing JS or PHP or CSS...

**Comment by 50Wliu** [comment]
Atom currently has problems handling non-US keyboard layouts - please see atom/atom-keymap#35 and atom/atom-keymap#37 for more information.
