### ISSUE TITLE
Atom clashes with Gulp 

### ISSUE THREAD

**Issue by reneolivo** [atom/atom#8610]
I get the following error when I have Atom open:

```
$ gulp serve
[23:00:42] Using gulpfile gulpfile.js
[23:00:42] Starting 'build'...
[23:00:42] Starting 'clean'...
[23:00:42] Finished 'clean' after 114 ms
[23:00:42] Starting 'build-system'...
[23:00:42] Starting 'build-html'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EPERM, stat 'dist\app.html'
    at Error (native)
```

As soon as I close Atom it works fine. I think this error may interfere with other CLI tools.

I'm developing on windows.

**Comment by mnquintana** [comment]
This is quite strange - I've never had any issues running Atom alongside Gulp. Does the same thing happen if you quit Atom, reopen it in safe mode (`atom --safe`), and then try running Gulp?

> I think this error may interfere with other CLI tools.

Has that actually happened? If so, what other CLI tools?

**Comment by reneolivo** [comment]
Hello, I could produce the error message only when atom was open, even on safe mode as you requested, and on different projects that used gulp and grunt tasks.

I restarted my computer and now everything is working fine, which is a shame because I can't reproduce the error any longer.

Sorry about that :cry:

**Comment by Pleasurazy** [comment]
Hi @mnquintana

I have same problem.

- removed everyfolder that in `~/.atom/packages`
- install `gulp`, [`gulp-watch`](https://github.com/floatdrop/gulp-watch), [`run-sequence`](https://www.npmjs.com/package/run-sequence)
- write task

  ```
    gulp.task('tttt', () => {
      return gulp.src('app/assets/**/*.js')
      .on('data', (file) => {
        console.log(file.path)
      })
    })

    gulp.task('watch', () => {
      gulpWatch('src/**/*.js', () => runSequence('tttt'))
    })
  ```

- open `atom`, find a js file, hold the <kbd>cmd+s</kbd>, then  **crash randomly**

- open `sublime text`, find a js file, hold the <kbd>cmd+s</kbd>, then  **working fine**

error with atom:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, stat '/Users/pleasurazy/projects/cms/src/pages/welcome/index.js~'
    at Error (native)
```

I think the tilde cause the crash...?

---
atom 1.5.4
gulp 3.9.1
mac os x 10.11.3

**Comment by mnquintana** [comment]
@Pleasurazy Would you mind opening a new issue for that? That seems unrelated to Gulp, since the error's being thrown from Atom. Thanks!

**Comment by Petya-Naumova** [comment]
I had the same issue. Running 'gulp serve' with open Atom produced errors like 'Error: EPERM: operation not permitted, unlink.....Error in plugin 'run-sequence' Message: An error occured in task 'cleantmp'.' 
After closing Atom,  'gulp serve' run just fine.

**Comment by jlafica** [comment]
Same issue here.  Only fails when the project on which I'm running tasks is open in Atom. Having Atom open with a project other than the one I'm running tasks on does not cause an issue.

Atom 1.16.0
Node 6.10.0
Gulp Cli 1.2.2
Windows 7 Pro X64

```shell
c:\xx> gulp build
[10:13:20] Using gulpfile c:\xx\gulpfile.js
[10:13:20] Starting 'build'...
[10:13:20] Starting 'clean'...
[10:13:20] Finished 'clean' after 147 ms
[10:13:20] Starting 'scripts:plugins'...
[10:13:20] Finished 'build' after 174 ms
[10:13:21] 'scripts:plugins' errored after 1.39 s
[10:13:21] Error: EPERM: operation not permitted, mkdir 'c:\xx\assets\dist\maps'
    at Error (native)
[10:13:21] Error in plugin 'run-sequence(scripts:plugins)'
Message:
    EPERM: operation not permitted, mkdir 'c:\xx\assets\dist\maps'
Details:
    errno: -4048
    code: EPERM
    syscall: mkdir
    path: c:\xx\assets\dist\maps
Stack:
Error: EPERM: operation not permitted, mkdir 'c:\xx\assets\dist\maps'
    at Error (native)
```
