### ISSUE TITLE
Cursor is hidden by preferred width indicator

### ISSUE THREAD

**Issue by lordjavac** [atom/atom#8625]
The cursor blinks merrily along until it occupies the same column as the preferred line length indicator, then it disappears only to reappear once past it. I'm sure this has something to do with how the cursor and the line wrap indicator are displayed. I'm not sure if it's a layer issue (is the cursor on a different layer?) Or are they both border styles and the wrap indicator is a more specific selector?

**Comment by 50Wliu** [comment]
Hi @lordjavac, what Atom version are you using?

**Comment by lordjavac** [comment]
I'm running Atom 1.0.9. The issue presents itself on both Mac OS X 10.10 (Yosemite) and Windows 10.
Your inquiry got me thinking and I checked. It's actually an issue with the Base 16 Tomorrow Dark syntax theme. I will close this issue and open one there. Thanks.
