### ISSUE TITLE
Add option to have cmd-w close the window when there are no editors open

### ISSUE THREAD

**Issue by matthewmccullough** [atom/atom#863]
When I have multiple buffers open in tabs and a tree view, my past editors (TextMate, Sublime) have conditioned me to expect that a repeated ⌘+w close each buffer's tab, then close the frame and its tree list after the last buffer has been closed.  Atom does not behave this way, and I'm curious if this is by design.

It is worth noting that Brackets does also hold the frame open after repeated ⌘+w presses. Is this similarly by design in Atom? Must I switch fingers to ⌘+⇧+w to close the frame?

**Comment by fulldecent** [comment]
For me, this is intuitive:

**A file is open and you press Cmd-W:** This closes the last file, and focus returns to the file tree so you can up/down/enter to open another file.

**No file is open and you press Cmd-W:** The full MDI window closes.

**Comment by ryanseys** [comment]
Seems strange that Cmd+W doesn't close the window on Mac because this is just regular convention across all applications. This felt very much "broken" when I realized I couldn't close the window with Cmd+W.

**Comment by mcandre** [comment]
+1

**Comment by cthielen** [comment]
+1

**Comment by jacekkopecky** [comment]
would it be easily possible to make background-tips receive keyboard events? Then we could bind `cmd-w` to `window:close` for an easy workaround.

**Comment by jacekkopecky** [comment]
Oh, how is the package `the-closer` not mentioned here? It addresses this very issue.

**Comment by eparejatobes** [comment]
@jacekkopecky it was! https://github.com/atom/atom/issues/863#issuecomment-47467785 works just great and it makes atom usable as your `$EDITOR`

**Comment by jacekkopecky** [comment]
Ah, @izuzak neglected to mention the name of his package when introducing it. 8-)

**Comment by PaulCapestany** [comment]
+1

**Comment by df-sean** [comment]
+1 *** Atom is literally the *only* app on my Mac that doesn't behave this way.

**Comment by smilingpoplar** [comment]
+1

**Comment by Gerald09** [comment]
+1

**Comment by groue** [comment]
@benogle, you have changed the title of the issue, by adding "option". I don't know if it's a good idea. On OSX, such behavior has no meaning being an option, since it is a de facto standard.

**Comment by benogle** [comment]
Yes, an option is important because this behavior has been in since the beginning. There will inevitably be new people who are frustrated by `cmd-w` closing the window. Whenever we change behavior [we see this happen](https://github.com/atom/atom/issues/6605), so we need to minimize frustration.

**Comment by df-sean** [comment]
Just want to mention again that "the-closer" package solves this issue perfectly. (Though I still think it should be default functionality because I'm pedantic like that).

**Comment by groue** [comment]
You know better. Isn't it weird to ship an application which requires a lot of tweaking before if behaves nicely (nice as "just like a regular app")? I've been bitten by those weird default settings already. Now I'm more or less aware that oddities may be fixable by crawling in the (many) options, but it's not quite ideal.

**Comment by benogle** [comment]
For the record, I think this setting should be default to closing the window, but I want to give people an out.

**Comment by izuzak** [comment]
https://github.com/atom/atom/pull/9607 added support for this (thanks, @DouweM!), so it should reach stable and beta releases in the near future. The feature will be enabled by default, but it's possible to opt-out using a config option.

```
"*":
  core:
    closeEmptyWindows: false
```

**Comment by DouweM** [comment]
@izuzak A config option which is also available in the UI: :)

![screenshot](https://cloud.githubusercontent.com/assets/159434/11303872/94600abc-8fa5-11e5-9412-62734caa656a.png)

**Comment by izuzak** [comment]
Thanks, @DouweM. :)

I was just looking at that and it seems that the description of that config option is a bit misleading. It says "When a window with no tabs or panes is given the 'Close Tab' command, close that window."

However, if I trigger that command (`Tabs: Close Tab`) through the command palette -- the windows is not closed. It's closed only when I hit `cmd-w` or trigger the `Core: Close` command through the command palette. Do you see the same behavior? If so, do you think we should clarify that or make some changes?

**Comment by DouweM** [comment]
@izuzak Hmm. The "Close Tab" I'm referring to is the "Close Tab" in the File menu, which is mapped to `Cmd-W` and fires the `core:close` command. It is defined by Atom itself and does indeed also appear as "Core: Close" in the command palette. 

"Tabs: Close Tab", on the other hand, is the `tabs:close-tab` command defined by the `tabs` package, and is not affected. We could patch `tabs` to show the same behavior, but I am not seeing the "Tab: Close Tab" command at all when 0 tabs are open, so I think we don't need to change anything.

**Comment by izuzak** [comment]
> I am not seeing the "Tab: Close Tab" command at all when 0 tabs are open

I definitely see it:

<img width="1280" alt="screen shot 2015-11-23 at 13 26 45" src="https://cloud.githubusercontent.com/assets/38924/11336481/e0cfdb38-91e5-11e5-9523-d992c458e329.png">

Have you made sure that you've focused the pane? (Try clicking on the background tips text after closing the last tab)

**Comment by DouweM** [comment]
@izuzak Ah, you're right, I see it now. I think we should change the behavior of the `tabs:close-tab` command do follow the same logic, would you agree?

**Comment by izuzak** [comment]
> I think we should change the behavior of the tabs:close-tab command do follow the same logic, would you agree?

I'm not sure, to be honest. How do you feel about creating a new issue for this, mentioning some of the possibilities (changing the description, updating tabs:close, ...) and pinging the folks that were involved in your PR? I think that's the best way to discuss this and also reduce the noise on this issue, which I'm pretty sure is followed by lots of folks. :bowtie: 

Thanks for investigating this with me! :bow:
