### ISSUE TITLE
Missing caret on selection

### ISSUE THREAD

**Issue by vjeux** [atom/atom#8630]
When you are selecting something, the flashing caret disappears on Atom. This would be nice to revive it, it is useful to know if the current cursor is at the beginning or the end of the line to know where you are going to select when you do left or right.

https://www.youtube.com/watch?v=UVSFBSKcS0Q
Left is Sublime, Right is Atom

**Comment by brandon-nelson** [comment]
This seems to have been an intentional feature:
https://github.com/atom/atom/blob/4d77c9240975c955fe74a758bc96d25c0cc910ad/src/cursor.coffee#L588

If not this seems rather simple thing to fix, I might try my hand at fixing it tonight.

**Comment by maxbrunsfeld** [comment]
/cc @atom/feedback 

I would support showing cursors for selections, so you can see if they are reversed or not. Thoughts?

**Comment by lee-dohm** [comment]
I agree that this would be useful.

**Comment by as-cii** [comment]
I have no strong feelings about this, but here's something I found a bit odd :thought_balloon::

![selections](https://cloud.githubusercontent.com/assets/482957/9713677/4ef656b6-5553-11e5-9bb9-9d40a33087a3.gif)

Although the behavior is consistent with Sublime Text, now that I see the cursor and I move it down, I'd expect it to maintain the same column. 

Nothing super disruptive, I know, but I'd probably prefer not showing the cursor at all if it gives unclear hints about the position (unless we want to change how `moveDown` works).

**Comment by lee-dohm** [comment]
This was fixed in recent versions of Atom.
