### ISSUE TITLE
Find in Project returns nothing for folder 'front_end'

### ISSUE THREAD

**Issue by yury-s** [atom/atom#8631]

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace and elaborating more on what you mean there? Generally issues opened with no descriptions and no reproduction steps are not terribly helpful for helping you debug - please take a look at https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues for a guide on submitting issues.

**Comment by yury-s** [comment]
@mnquintana sure. Sorry, I pressed enter before entering reproduction steps.

**Comment by yury-s** [comment]
Filed it as https://github.com/atom/find-and-replace/issues/518
