### ISSUE TITLE
CSS3 will-change property incorrectly highlights red in SCSS file

### ISSUE THREAD

**Issue by adam-knights** [atom/atom#8633]
Say I have a buttons.scss file with:

    @mixin btn-gradient($c) {
      background-image: radial-gradient(circle, $c 1%, lighten($c, 15%) 15%, rgba(0,0,0,0) 30%);
      background-color: $c;
    }
        
    .btn-raised {
	  border-radius: $border-radius-small*0.66;
	  box-shadow: $box-shadow-raised;
	  @include btn-gradient($secondary-color);
	  will-change: box-shadow, background-color;
	  color: $secondary-text-color;
	  &:hover {
        color: $secondary-text-color;
	    box-shadow: $box-shadow-raised-hover;
	    background-color: lighten($secondary-color, 5%);
	  }
    }

Will change currently highlights red, when it is valid:

![will-change](https://cloud.githubusercontent.com/assets/12710362/9626088/ed870280-5152-11e5-9138-3c241b9b2c31.png)

I believe this should not be highlighted? Which core addon is providing these checks and colorings of the code?

**Comment by mnquintana** [comment]
This is handled by https://github.com/atom/language-sass - would you mind reopening this there? Thanks!
