### ISSUE TITLE
Atom does not start for non-root users

### ISSUE THREAD

**Issue by n00dl3** [atom/atom#8637]
When I run `atom -f --safe` I get an error :
>[21795:0902/164238:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.

The only way to get it working is to run atom as root, it still complains about  "running without the SUID sandbox", but it starts...

I'm running atom 1.0.10 (installed from .deb)  on Debian testing (stretch)

**Comment by peduxe** [comment]
This is the only way to start atom with the `-f` flag. `atom -f --safe`also works, I get that exact error when I run `atom`or `atom <folder|file>`

**Comment by n00dl3** [comment]
Okay, I didn't do anything, didn't even reboot, just left work and when I came back this morning everythin works fine, maybe the cleaning woman fixed this :smile: ...
