### ISSUE TITLE
Cannot open folders any longer on Linux

### ISSUE THREAD

**Issue by anavarre** [atom/atom#8649]
Using Linux Debian 8 and **Atom 1.0.10** that comes from the [webupd8 packaging](http://www.webupd8.org/2014/05/install-atom-text-editor-in-ubuntu-via-ppa.html). Tried `atom --safe` either but it didn't make any difference.

Basically, using **File > Open folder...** doesn't work anymore. It used to work perfectly until recently, but now it does nothing. I couldn't say if the issue was already happening with a previous version or not, but it feels to me this regression has been introduced within the past 2 weeks or so.

**Comment by MichaelAquilina** [comment]
Works for me on Ubuntu 15.04 (I'm using Atom 1.0.11 from the releases section though).

**Comment by anavarre** [comment]
Oh, I think I can detail this even more. It's only in the context of Debian 'places' (aka, the left sidebar shortcut tree you find in basically every modern Linux distro and OSX) that it won't work. Tried from 'regular' folders instead of shortcuts and it works well.

![atom-issue-places](https://cloud.githubusercontent.com/assets/293478/9710628/f4846152-553c-11e5-8e64-989ddcb5f0ca.png)

**Comment by anavarre** [comment]
Tried on a fresh Debian 8 VM to make sure and...I cannot reproduce. Not sure what's going on but let's not blame atom just now.
