### ISSUE TITLE
Goto folded row -> does not unfold

### ISSUE THREAD

**Issue by lloiser** [atom/atom#8651]
Given a simple JSON (or any other foldable code block):
![image](https://cloud.githubusercontent.com/assets/3003233/9070863/368563e0-3af2-11e5-9a59-aa892d9a08c3.png)

When I fold it and then go to a line in between the folded code block:
![image](https://cloud.githubusercontent.com/assets/3003233/9071017/066d2aa2-3af3-11e5-93ee-d751588e35ed.png)

Then I expect the code block to unfold and jump to the entered line.
Instead it remains folded.
![image](https://cloud.githubusercontent.com/assets/3003233/9070892/66597480-3af2-11e5-8608-6b5f3cb91e82.png)

Works at least in Sublime Text 3.

Atom: 1.0.10
OS: Win 8.1 64Bit

How to fix:
adding the following lines after https://github.com/atom/go-to-line/blob/master/lib/go-to-line-view.coffee#L68 unfolds the row
```js
if (editor.isFoldedAtBufferRow(position)) {
  editor.unfoldBufferRow(position)
}
```

**Comment by lpommers** [comment]
this issue should probably be moved to https://github.com/atom/go-to-line, and why not make a PR there since it looks like you've already looking into a solution?

**Comment by lloiser** [comment]
already opened one there earlier, reopened.
https://github.com/atom/go-to-line/issues/24

**Comment by maxbrunsfeld** [comment]
Ok, closing this out in favor of the `go-to-line` issue. Thanks @lloiser.
