### ISSUE TITLE
Move to new line in object

### ISSUE THREAD

**Issue by dmitruksergey** [atom/atom#8653]
How i can move to next line in object like in Sublime Text? Not to start line.

In Sublime Text:
<img width="496" alt="screenshot 2015-09-03 13 43 46" src="https://cloud.githubusercontent.com/assets/4532683/9656620/2f5b138c-5242-11e5-8477-5225a283dfd3.png">

In Atom:
<img width="546" alt="screenshot 2015-09-03 13 45 44" src="https://cloud.githubusercontent.com/assets/4532683/9656604/1a1c27c2-5242-11e5-97c8-6896c90528ea.png">

**Comment by peduxe** [comment]
Tab key?

**Comment by dmitruksergey** [comment]
No

**Comment by izuzak** [comment]
Do you have this option enabled in settings?

<img width="351" alt="screen shot 2015-09-03 at 13 29 52" src="https://cloud.githubusercontent.com/assets/38924/9657280/ed25c1f8-523f-11e5-8763-96709eb94489.png">

**Comment by dmitruksergey** [comment]
Thanx!
