### ISSUE TITLE
Deleting tabs with the mouse: don't resize until tabbar lose focus

### ISSUE THREAD

**Issue by erwan** [atom/atom#8654]
Just like Chrome does: while deleting tabs, keep the same length. Only resize them to ajust to the new number of tabs when the mouse leaves the tabbar area.

That way we can close multiple tabs without having to move the mouse (just click as many times as needed). Currently, we have to move the mouse around after each tab deletion to accomodate with the length change.

**Comment by maxbrunsfeld** [comment]
This would be pretty cool. Could you reopen this issue on [the tabs package](http://github.com/atom/tabs)?

**Comment by mnquintana** [comment]
I think this is a duplicate of https://github.com/atom/tabs/issues/132 and https://github.com/atom/tabs/issues/129
