### ISSUE TITLE
Atom does not use the system font on Linux (and Mac and Windows)

### ISSUE THREAD

**Issue by p-e-w** [atom/atom#8656]
Atom does not actually use the system font for its UI. [The "font stack" solution currently implemented](https://github.com/atom/atom/pull/8612) hardcodes a bunch of fonts in the hope that the default font for every possible installation is included. This is not a big issue on Mac and Windows where it is ~~impossible~~ almost impossible – and very unusual – to change the system font.

Not so on Linux. As an example, I use Fedora which comes with Cantarell by default. I don't like Cantarell and have changed my system font to Source Sans Pro instead (easily done in GNOME). All of my desktop applications respect the change, except Atom because it has Cantarell hardcoded in its font stack and since Cantarell is still present on my system it is used instead.

The solution is to make Atom use the system fonts like other desktop applications. Instead of guessing which font the user wants, it should query the system for the default font to use. IMO this should also extend to the fixed-width font and themes explicitly setting the font family should be the exception rather than the rule. No matter which theme I choose, there is almost never a good reason for one application to use a different font than the others.

**Comment by mnquintana** [comment]
That's legit - we may have to wait on https://www.webkit.org/blog/3709/using-the-system-font-in-web-content/ to get standardized though. When it is, then using a future version of Electron we should be able to just set the UI font to `-system`.

**Comment by paulcbetts** [comment]
We don't have to wait, we just have to add code to Atom to figure out the system font, It Can Be Done(tm)

**Comment by peduxe** [comment]
Would be great, it's using Ubuntu font on mine and I would like to set SFNS or Noto.

**Comment by benklebe** [comment]
Would it not be simpler to allow the user to change the UI font themselves?

**Comment by thomasjo** [comment]
> Would it not be simpler to allow the user to change the UI font themselves?

Which can easily be done, just not via a GUI. But I think @paulcbetts approach is where the effort should be spent. Working on a GUI solution that would still require manual intervention by the user, is not worth the effort in my opinion. An automated approach is the way to go.

**Comment by jerone** [comment]
To quote @mnquintana on [3 jul. 2015 20:13 CEST](https://github.com/atom/atom/pull/7698#issue-92918401 "2015-07-03T18:13:33Z - Replied by Github Comment Enhancer"):
> This will go a long way, I think, toward making Atom feel less like a "website" running in a semi-headless Chrome, and far more like a native app with a custom UI.

**Comment by johnmuhl** [comment]
I haven't tested it across every platform but:

``` css
body { font: menu }
```

seems to work where I have tested it.

**Comment by mnquintana** [comment]
This one's not quite done yet - there are some pitfalls of using `font: menu`, unfortunately. (You can follow the discussion in https://github.com/atom/atom/pull/8817) Since `menu` isn't actually a font family and can't be used with `font-family`, using it requires messing with the UI variable `@font-family`, which will break packages that import it and use it in their own styles.

**Comment by simurai** [comment]
Just as a reminder, once `BlinkMacSystemFont` will be supported in Atom (already works in Chrome stable), we could give that a try. See [Approach B](http://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/#approach-b).
