### ISSUE TITLE
Highlight git changes on the level of a project

### ISSUE THREAD

**Issue by jagi** [atom/atom#8657]
Hi currently Atom is highlighting files in which there are git changes. However when you collapse project tree, a project name isn't highlighted. Because of that I have to unfold each project's directories tree to check whether I've made some changes. I'm working on several connected projects in the same time so that's why I think such feature would be handy. What do you think? :)

It would also be nice to have, next to the project name, an indicator showing how many commits have been made and are waiting to be pushed and what branch I'm currently on. Such feature is present for instance in Eclipse.

![atom](https://cloud.githubusercontent.com/assets/1051229/9665934/94cee2a8-5273-11e5-8cfb-32267f64d59f.png)

**Comment by mnquintana** [comment]
Sounds good! Would you mind reopening this on https://github.com/atom/tree-view? Thanks!

**Comment by jagi** [comment]
Ok great I will :)
