### ISSUE TITLE
Pointer is nearly invisible when using a dark syntax theme

### ISSUE THREAD

**Issue by ravinggenius** [atom/atom#8659]
When using the Atom Dark syntax theme, the pointer is very difficult to see. I frequently use the pointer to quickly move the cursor to a new location. Note that I had the same result with all the dark themes I have installed; namely Atom Dark, Base16 Tomorrow Dark, One Dark, Solarized Dark. Below are some screenshots which demonstrate the problem.

<img width="273" alt="atom_light" src="https://cloud.githubusercontent.com/assets/21517/9666201/b7bc55d8-5242-11e5-88bd-5f4f4f7fca22.png">

<img width="277" alt="atom_dark" src="https://cloud.githubusercontent.com/assets/21517/9666200/b7bb0746-5242-11e5-8421-02060312fa22.png">

---

Sublime Text seems to invert the I-bar pointer so it shows as mostly white when on a dark background. I tried to take a screenshot to illustrate this, but couldn't capture Sublime Text's pointer.

**Comment by izuzak** [comment]
Can you add a comment to https://github.com/atom/atom/issues/1654, which I think is discussing the same issue? Thanks!
