### ISSUE TITLE
Cannot find module 'fs-plus' when loading rst-preview package

### ISSUE THREAD

**Issue by joshua-ballard** [atom/atom#8662]
I'm behind a ridiculous firewall and unable to use the native package manager to install the 'rst-preview' package.  

I downloaded the latest rst-preview from git (1.3.0), cd into the directory and run `apm link`.  Everything seems OK.  When I force reload Atom with Ctrl + Alt + r, I get an error:

    Failed to load the rst-preview package
    Cannot find module 'fs-plus'

I downloaded the latest 'fs-plus' package (2.8.1), cd in and run `apm link`.  No problem.  

Force reload atom and still get the error.  I removed both packages and tried installing 'fs-plus' first.  Still the same issue.   

Here is the error report:

**Atom Version**: 1.0.11
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Failed to load the rst-preview package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\ballard\AppData\Local\atom\app-1.0.11\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (<anonymous>:2:6)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\ballard\AppData\Local\atom\app-1.0.11\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 15,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
fs-plus, v2.8.1
rst-preview, v1.3.0

# Dev
No dev packages
```

**Comment by maxbrunsfeld** [comment]
I think you just need to run `apm install` from the `rst-preview` directory, to install the dependencies. Let me know if that doesn't fix it for you.

**Comment by joshua-ballard** [comment]
Thanks. 
`apm install` fails:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp WARN download ignoring invalid "proxy" config setting: "^^^^^^^^^^^^^^^^^.org:8082"

gyp WARN install got an error, rolling back install
gyp
```
https://atom.io is not in our corporate whitelist, so, even if the proxy were set correctly, I'm not sure it could get the .tar.gz file it needs.  Can that be installed manually?

**Comment by maxbrunsfeld** [comment]
> https://atom.io is not in our corporate whitelist

Ok, well I think the only reason that `apm install` needs to connect to atom.io is to download the headers for Atom's version of V8. This is only needed when installing modules that contain native code. If none of the modules contain native code, you can install the dependencies with `npm install`. Is npmjs.com on your whitelist?

**Comment by joshua-ballard** [comment]
Unfortunately, no.

**Comment by maxbrunsfeld** [comment]
Ok. So Atom packages can use arbitrary node modules, and node modules aren't all on GitHub. But for some packages it will be possible to manually install each dependency. You'd have to clone the correct version of the module into `node_modules`. Each node module has its *own* dependencies that get installed to its own `node_modules` folder though, so you'd have to repeat that process recursively.

**Comment by joshua-ballard** [comment]
That may be more work than I'm ready to do for this.  Thanks for your help.
