### ISSUE TITLE
Using atom from the command line creates a duplicate instance of the app

### ISSUE THREAD

**Issue by benklebe** [atom/atom#8666]
When I type `atom [file]` at the command line to open a file, or when I use `atom` as my git commit editor, the command line tool briefly opens a separate instance of the Atom app (I see it bouncing in the Dock). This instance then closes, and the desired file or commit is instead opened in an entirely new window in the previous instance. I find this behavior undesirable and would like to know how to change it if it's not a bug.

**Comment by 50Wliu** [comment]
Refs #2964.

**Comment by damieng** [comment]
Tracking on the other bug.
