### ISSUE TITLE
Default theme provides insufficient contrast in bright environments

### ISSUE THREAD

**Issue by benbalter** [atom/atom#867]
Specifically when editing markdown in a bright environment, such as outside, or when the screen brightness isn't super high, it's hard to see markdown link sources (the part in the `()`s) as they're so close to the background color at that light.

Same goes for the cursor... generally find myself moving it around a lot just to find it when it's on a big block of full-column text like markdown.

**Comment by mnquintana** [comment]
This shouldn't be an issue anymore with the new themes - closing
