### ISSUE TITLE
Auto-indent in python syntax highlighting disrespects tab settings

### ISSUE THREAD

**Issue by ian-bertolacci** [atom/atom#8670]
I came across this while trying to write a python script.
With Soft Tabs enabled, Tab Type = soft, Tab Length = 2

Any tab insertion (either by key or auto-indent) inserts 4 space characters.
when auto-indenting because of a newline, from a line with no indentation, 4 spaces are inserted.
However, if auto-indenting because of a newline, from a line with 2 spaces of indentation, a 4 spaces of tab, and 2 additional spaces are inserted.

If the tab key is used on a line with 2 space characters, 2 more are inserted to 'complete' its idea of what the indentation should be.

Changing the language (to anything really) 'corrected' the behavior in that tabs become 2 spaces, regardless of auto-indentint, or tab key-ing, or whatever.

This bad behavior is not seen when writing C code, in the C syntax highlighting mode.

**Comment by lee-dohm** [comment]
The default tab length for Python is 4 characters:

https://github.com/atom/language-python/blob/master/settings/language-python.cson#L5

You can override this to 2 characters by doing the following:

1. Start Atom
1. Open the Settings View with <kbd>Cmd+,</kbd> on OS X or <kbd>Ctrl+,</kbd> on other platforms
1. Click the Packages tab
1. Type `python` in the search box
1. Click the background of the box describing the language-python package
1. Scroll down in the language-python package settings to Tab Length
1. Set it to 2

**Comment by ian-bertolacci** [comment]
:+1:
