### ISSUE TITLE
"Restart and Install Update" doesn't work as a non-administrative user under OSX

### ISSUE THREAD

**Issue by gitsnaf** [atom/atom#8671]
I have an iMac with OSX 10.10.4 and this behaviour is reproducible. I would expect the app to ask for administrative credentials like all other apps are doing.

My MacBook where I work as an administrative user, the update procedure is working.

**Comment by adas172002** [comment]
+1, I am on Atom 1.0.9

**Comment by dstack4273** [comment]
The updater is still broken for me too, also use a non-admin account if that makes any difference.

**Comment by 50Wliu** [comment]
This is a duplicate of #2860 - feel free to subscribe there for updates.
