### ISSUE TITLE
OSX Saving files adds a new empty line at the end of file

### ISSUE THREAD

**Issue by ainstushar** [atom/atom#8677]
Hey guys, tried searching for this issue but I didn't really find anything.

I've got all of my packages disabled. When I save a file, atom adds a new line at the end of the file. Not sure why. Am I missing any setting?

OSX 10.10.5 on rMBP. If you need any logs/config, please let me know.

**Comment by mnquintana** [comment]
Hey there! I linked to this on Slack too, but you'll want to take a look at https://discuss.atom.io/t/why-is-atom-deleting-trailing-whitespace-why-is-there-a-newline-at-the-end-of-the-file-why-are-there-all-these-changes-in-the-file-diff/19189 for what that is and how to disable it.

Hope that helps!

**Comment by ainstushar** [comment]
Yep didn't realize that core atom packages had their own settings options. Would be cool to merge those core package settings in just main settings page...

In any case, thanks for the info :)
