### ISSUE TITLE
Packages page missing lots of my installed packages

### ISSUE THREAD

**Issue by AgentME** [atom/atom#8678]
I think these screenshots should explain the issue. In the first screenshot, I'm on the "Install" page and you can see I have atom-beautify installed. In the second screenshot, I'm on the packages page. It says there are 14 packages in the "Community Packages" section, but it only shows one. In the third screenshot, I've searched for "atom-beautify" on the packages page, and there are no results.

![screen shot 2015-09-04 at 4 12 10 pm](https://cloud.githubusercontent.com/assets/577345/9696147/23ab9c62-5320-11e5-84e3-786fcc52af66.png)

![screen shot 2015-09-04 at 4 12 40 pm](https://cloud.githubusercontent.com/assets/577345/9696166/4ff64998-5320-11e5-88e5-3a71850f73e7.png)

![screen shot 2015-09-04 at 4 12 00 pm](https://cloud.githubusercontent.com/assets/577345/9696172/549e7e98-5320-11e5-8454-9edb1e874c20.png)

**Comment by mnquintana** [comment]
This looks like the same issue as https://github.com/atom/settings-view/issues/591 – closing in favor of that issue. Let me know if I'm mistaken though!
