### ISSUE TITLE
TokenizedBuffer#bufferRangeForScopeAtPosition appears to be using incorrect position

### ISSUE THREAD

**Issue by blakeembrey** [atom/atom#8685]
I run into this with https://github.com/blakeembrey/atom-dash/issues/26 and solved it using https://github.com/blakeembrey/atom-dash/commit/750f84560f62e824b87fbd2012699d50dd3446e2. It seems a method are using the wrong position object. I suspect `TokenizedBuffer#bufferRangeForScopeAtPosition` is not calculating the position correctly.

The issue starts with https://github.com/atom/atom/blob/278e988cca2bba2b0f5f13d1833786ac59cb989e/src/text-editor.coffee#L2565-L2566 and ends up using https://github.com/atom/atom/blob/4ff3b6d5efd213f491b82317316bdbffd39efbdf/src/tokenized-buffer.coffee#L478. As it passes cursor buffer position, if you have tabs enabled it will never get the position back correctly and it ends up being off by however much your tab spacing is.

Edit: Here's an image in action:

![image](https://cloud.githubusercontent.com/assets/1088987/11289914/4a6d38e0-8ee6-11e5-88cd-b67a85b6dd9c.png)

**Comment by KnutHelland** [comment]
`toggle-quotes` also doesn't work for tab indented lines.

Looks like `bufferRangeForScopeAtPosition` returns `row` in _buffer coordinates_, but `col` in _screen coordinates_.

See also my comments on https://github.com/atom/toggle-quotes/issues/27.

**Comment by nathansobo** [comment]
This is a duplicate of #9648 and is now fixed.

**Comment by mnquintana** [comment]
This appears to still be an issue, and is the underlying cause of https://github.com/atom/toggle-quotes/issues/27 (refs https://github.com/atom/toggle-quotes/issues/27#issuecomment-156734463).

It seems that this method still returns screen columns, which totally throws off the returned range.

**Comment by joefitzgerald** [comment]
I have reproduced this issue also. Definitely an issue.

**Comment by ruscur** [comment]
Any updates on this one?
