### ISSUE TITLE
[Idea] Locate the file when click letters on the keyboard on atom tree view

### ISSUE THREAD

**Issue by johnsonz** [atom/atom#8686]
On windows os, I open a directory includes sub-directories and files, when I click the letter "a" on keyboard, the file or directory that begins with the letter "a" will be located in turn. So could you consider this feature whether it can be implemented on atom tree view.
It will be convenience and time saving if there are many directories and files.
![screenshot](https://cloud.githubusercontent.com/assets/2533629/9702405/db1ac15c-548d-11e5-8f74-0bfcc226450e.png)

**Comment by izuzak** [comment]
Please reopen on https://github.com/atom/tree-view. Also, you might want to check the list of existing packages (https://atom.io/packages) -- perhaps there's a package which adds this feature already. And check out https://github.com/atom/tree-view/issues/515 and https://github.com/atom/tree-view/pull/532.
