### ISSUE TITLE
Failed to load the atom-terminal-panel package

### ISSUE THREAD

**Issue by grand-cat-unknown** [atom/atom#8687]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Ubuntu 15.04
**Thrown From**: Atom Core
### Stack Trace

Failed to load the atom-terminal-panel package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at global.include (<anonymous>:25:9)
    at Object.<anonymous> (<anonymous>:9:13)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 12,
    "invisibles": {}
  }
}
```
### Installed Packages

``` coffee
# User
node-on-fire, v0.1.0
seti-icons, v0.4.5

# Dev
No dev packages
```

**Comment by peduxe** [comment]
Go to ~/.atom/packages/atom-terminal-panel and execute `npm install`.

**Comment by thomasjo** [comment]
@The-Doodler How did you install the package? Looks like you probably did not use the package manager in Atom or the `apm install <package>` command? I recommend you install the package using either of those two approaches. If you're trying to develop against the package, you'll need to install its dependencies and in that case follow the general concept in @peduxe's comment with respect to executing `apm install`.

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8687#issuecomment-138058070. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
