### ISSUE TITLE
Can't type opening bracket [

### ISSUE THREAD

**Issue by junkies4** [atom/atom#8694]
My keyboard layout is French (Belgian) and I have to press Alt Gr + ] but when I press the right keys the sign doesn't appear in the editor, nothing happens.

![bracket](https://cloud.githubusercontent.com/assets/13817303/9706208/4865be82-54df-11e5-91c4-88ec3e61dd77.png)

I tried to disable all the installed plugins and even the core plugin associated with the auto completion but I did not succeed to find out which one cause this bug.

Windows 10 64 Bits, Atom 1.0.11 Version

**Comment by 50Wliu** [comment]
Hey @junkies4, Atom currently doesn't work well with foreign keyboard layouts.  Please see atom/atom-keymap#35 and atom/atom-keymap#37 for more information and possible workarounds.
