### ISSUE TITLE
A block of code which is folded and made as comment cannot be unfolded right after

### ISSUE THREAD

**Issue by fabiospampinato** [atom/atom#8695]
The following block of SCSS code cannot be unfolded right after having folded it and made as a comment:

``` scss
.foo {
  display: none;
}
```

Steps to reproduce the issue:
1. Paste the provided snippet in a new SCSS-formatted tab
2. Select all
3. Fold the block
4. Make as comment
5. Try to unfold 😕

IMHO when we click the "unfold block" icon it should be unfolded and every line should be a comment, but it just does nothing.

**Comment by 50Wliu** [comment]
Confirmed on other languages as well, Atom 1.0.11.

**Comment by mertkahyaoglu** [comment]
When we click "tree-dots" at the end, it unfolds but gutter arrow does not.

**Comment by jrial** [comment]
Still present in Atom 1.0 and the issue goes further than that. It's not just that the code can't be unfolded.

There are two issues with trying to comment out a folded code block:
* Only the first line gets folded
* The fold arrow in the gutter doesn't unfold the block

When trying to uncomment a commented out and folded code block, similarly three issues arise:
* Only the first line gets uncommented
* If it's XML (probably anything where you have comment-start and comment-end markers) nothing happens at all.
* The fold arrow doesn't unfold the block.

This is when using the shortcut CTRL+/

See https://www.youtube.com/watch?v=DkQ8RW0SAtc&feature=youtu.be for a demonstration. Whenever I hover over the folding arrow, it means I'm clicking but nothing happens.
