### ISSUE TITLE
[idea] Saving config on the server

### ISSUE THREAD

**Issue by jagi** [atom/atom#8696]
Hi, I have three workstations and on each one I'm using Atom. Sometimes it's hard to keep track of all changes that I made on one computer (installed packages, shortcuts, configs etc.) and redo them on other computers. I would like to have the same configuration on each computer. Of course I could add configuration file to git and store it somewhere or move my config file between computers. And I have and idea for a new package that maybe someone would like to implement or maybe it could be built in feature.

IDEA:
Ability to store config in the cloud. It could be a dedicated server from Atom. It could be a paid service. Or just ability to log in using for example your google account and store config on Google Drive, or log in with Dropbox account and store your data there. Thanks to that, anywhere you log in using your account, you would be able to load all the configuration. It would probably require to implement switching account in Atom like it's done in Chrome browser.

What do you think?

**Comment by Evpok** [comment]
https://atom.io/packages/sync-settings

**Comment by jagi** [comment]
Thanks! Great package :) Should be built in and automated, so that it does not require copying ID's, however it does it's job :)

**Comment by mnquintana** [comment]
Thanks for the suggestion! This essentially looks like the same enhancement request as https://github.com/atom/atom/issues/3572 though – closing in favor of that issue.
