### ISSUE TITLE
Atom 1.0.11 does not syntax highlight PHP code.

### ISSUE THREAD

**Issue by karevn** [atom/atom#8698]
I installed Atom 1.0.11 just recently and was very surprised to see that it does not syntax highlight php files (even though language-php is installed).

**Comment by philipgiuliani** [comment]
It works for me! Have you opened the `<?php` tag?

**Comment by karevn** [comment]
@philipgiuliani LOL. Yes. My file does even have a correct syntax and works! Inspecting the workspace shows me that php code is has some php-related css classes, but tokens are not highlighted. Screenshot: https://gyazo.com/56e575d4e81cf4d3025a5af183762adf

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* What OS and version are you running?
* Do you have [Emmet](https://atom.io/packages/emmet) installed?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by karevn** [comment]
Nailed it. It was by "live grammar reload" package. Closing this one. Thanks for helping!

**Comment by lee-dohm** [comment]
You're welcome!
