### ISSUE TITLE
Suggestion/Issue with autosuggest

### ISSUE THREAD

**Issue by arpecop** [atom/atom#8705]
When there is split panel down the suggestions are not visible
![screen shot 6](https://cloud.githubusercontent.com/assets/168974/9722020/268cf2a6-55ae-11e5-9ed9-801356c9b212.png)

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/autocomplete-plus? Thanks!

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.
