### ISSUE TITLE
Polymer syntax is not supported and generates error

### ISSUE THREAD

**Issue by matthieubosquet** [atom/atom#8709]
When using web-components, the syntax is not the same as HTLM and I couldn't find a way to enable proper error checking.
It is annoying to see errors constantly showing at the bottom of my editor.
The main errors I found are :
- "Doctype must be first" (at line 1 col 1)
- "Special character must be escaped" (this one is triggered when you use the attribute$= form of databinding within html markup).

I have been googling the issue for a long time and apparently, web components are used in atom. Please help!

**Comment by peduxe** [comment]
You must disable those, are you using linter-htmlhint?

**Comment by matthieubosquet** [comment]
Thanks a lot!
It worked like a charm.
To get rid of the doctype error I had to add "doctype-first": false.

My config is now:
```
{
    "attr-lowercase": true,
    "attr-value-double-quotes": true,
    "attr-value-not-empty": true,
    "doctype-first": false,
    "doctype-html5": true,
    "head-script-disabled": false,
    "id-unique": true,
    "img-alt-require": true,
    "style-disabled": true,
    "tag-self-close": false,
    "tagname-lowercase": true
}
```

htmlhint doc for reference:
https://github.com/yaniswang/HTMLHint/wiki/Usage

**Comment by peduxe** [comment]
@matthieubosquet you're welcome mate
