### ISSUE TITLE
Unable to use font by its name

### ISSUE THREAD

**Issue by Whenrow** [atom/atom#8710]
Hi, 
I would like to use the font Source Code Pro in atom (vers. 1.0.11). When I write it in the settings it is not recognize : 
![2015-09-08_16-08-11](https://cloud.githubusercontent.com/assets/12071695/9736835/d675ef48-5643-11e5-8cd6-59e7f5a94b78.png)
It works with a *"* in front of it but not if framed in *" "*
![It works](https://cloud.githubusercontent.com/assets/12071695/9736881/21851fe0-5644-11e5-8439-661895f15fcc.png)
![2015-09-08_16-10-07](https://cloud.githubusercontent.com/assets/12071695/9736882/2186f978-5644-11e5-8dc4-dbb7d516ed50.png)

**Comment by izuzak** [comment]
I was able to set it up with `sourcecodepro-regular` on OSX (see https://github.com/atom/atom/issues/2912#issuecomment-48742625). But I agree, that's not the best experience. There's already an open issue to improve this https://github.com/atom/settings-view/issues/286 so I'm going to close this in favor of that issue. Thanks for the feedback
