### ISSUE TITLE
"Installed On" date is wrong in Windows 7 "Programs and Features"

### ISSUE THREAD

**Issue by w1res** [atom/atom#8711]
I was uninstalling unneeded programs through the Windows 7 "Uninstall or change a program" menu, and I noticed that Atom is said to have been installed on 12/3/2015. I am in the USA, so this date would be December 3, 2015, which hasn't happened yet--today is September 8, 2015 (9/8/2015). Atom is listed as version 1.0.11.

I don't really know how to give any more info except that it is obviously wrong. As far as I know, the system time was never changed, and no other applications seem to share this problem. Also, the editor was probably installed about a month ago, so it is not likely that just the month and day were flipped.

**Comment by mnquintana** [comment]
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/6606 - closing out in favor of that issue.
