### ISSUE TITLE
The "package management" views are placed in the "preferences" menu

### ISSUE THREAD

**Issue by rondonjon** [atom/atom#8713]
Another naming / usability issue, sorry ...

There is a "packages" menu item in atom. What it really contains are the "installed packages" and not things related to "packages".

To reach the "package management" functions however, I have to navigate through "Edit > Preferences" and select "Packages" there.

IMO it would be more intuitive to add a separator at the beginning or the end of the "packages" menu, put "Manage Packages ..." or "Manage Installed Packages ..." and "Install New Packages ..." there, and remove these functions from the "Preferences" menu.

Admittedly, yes, some packages offer customization, and it indeed comfortable to install a package and then customize by simply clicking on the gear icon that is displayed next to the "uninstall" button. But the same button could as well link to a dedicated, plugin-specific section in the "real" settings page.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/settings-view? Thanks!

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.
