### ISSUE TITLE
Need a better way to switch between UI themes. 

### ISSUE THREAD

**Issue by kirklazarus** [atom/atom#8716]
It'd be nice to have a drop down just for this that made changes. I think this would be easy and useful.

**Comment by mnquintana** [comment]
I'm not quite sure what you mean - what kind of UI change are you thinking exactly? There is a dropdown for switching themes:

<img width="382" alt="settings_-__users_machistequintana_code_devdocs_-_atom" src="https://cloud.githubusercontent.com/assets/823545/9744600/d80f1cde-563a-11e5-8616-737bade961c9.png">

**Comment by kirklazarus** [comment]
I am totally wrong. Sorry!
