### ISSUE TITLE
SCSS with brackets causing 

### ISSUE THREAD

**Issue by JimmyMultani** [atom/atom#8717]
I've noticed that using brackets inside a class/id will break the theming of code after.

![screenclip](https://cloud.githubusercontent.com/assets/1281284/9744152/14a6688a-5638-11e5-931a-55ef9b556a4f.png)

I am on Atom 1.0.11 as of this posting. I switched back to the One Dark UI and theme, but that did not fix the issue. Removing all plugins did not fix it either.

I am at a loss as to what to do next. Any idea why this is happening?

Thanks.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/language-sass? Thanks!

Also you might want to take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.

**Comment by JimmyMultani** [comment]
My mistake, @mnquintana. I've opened up my issue on the appropriate repo. Thanks again. :)
