### ISSUE TITLE
Suggestion, if I'm in wrong place let me know I'm firstimer to GitHub

### ISSUE THREAD

**Issue by Seekula** [atom/atom#8718]
So Hi,
I think it may already be asked/suggested, but is there a possibility of adding option to "open with Atom" to the windows thingy that pops when you right click a file :)

Sorry for my English I'm ESL :D 
I'm sorry if I' bothering you with something and just wasting your time but I'd love this feature added ;]
-Jackob

**Comment by aclonegeek** [comment]
![2015-09-08_20-52-42](https://cloud.githubusercontent.com/assets/9111965/9750883/b9da6a4e-566b-11e5-8e08-cbfc75c491bf.png)

It's there for me on Windows 10 (and was there previously on Windows 8.1). According to this guide it should do it all automatically (The windows thingy that pops up when you right click a file is called the context menu):
(https://atom.io/docs/latest/getting-started-installing-atom#atom-on-windows)

Try reinstalling atom and see if that fixes it. If not, you can do it manually by editing the registry (just google a guide for that).

**Comment by 50Wliu** [comment]
Hey @Seekula, how did you install Atom?  Did you use `AtomSetup.exe`?

**Comment by Seekula** [comment]
@50Wliu I did, now I reinstalled it for the 2nd time and it works now, don't know where the issue occurred, I guess between the desktop and the chair :D Well thanks for your replies, next time I have an issue I'll rather reinstall more times than once :D
