### ISSUE TITLE
wrong architecture? running xubuntu 14 on intel i7

### ISSUE THREAD

**Issue by jerry1970** [atom/atom#8728]
Hi,

I would love to install Atom on my machine but the .deb and the .rpm (using alien) both say "wrong architecture".

I have a Lenovo T431s with an Intel i7 vPro with Xubuntu 

This is my ```uname -a``` result:
```
3.16.0-48-generic #64~14.04.1-Ubuntu SMP Thu Aug 20 23:03:49 UTC 2015 i686 i686 i686 GNU/Linux
```

Any idea how to install atom?

Cheers!
Jerry

**Comment by 50Wliu** [comment]
Hi Jerry, both the .deb and .rpm are currently built for x64 systems only.  If you want to run Atom on x32, you'll need to [build it](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md) by yourself, sorry.
