### ISSUE TITLE
Create new language for Informix 4GL

### ISSUE THREAD

**Issue by INGCRENGIFO** [atom/atom#8734]
How could create a new language in Atom?
There is some guidance?
the idea is to create an Informix 4GL language and to seek and found there.

**Comment by mnquintana** [comment]
The easiest way to create a new language grammar for Atom is to convert an existing TextMate bundle: https://atom.io/docs/latest/hacking-atom-converting-from-textmate

Hope that helps!

**Comment by INGCRENGIFO** [comment]
Hello @mnquintana not know you could convert a package textmate, I now comes a doubt that language (Informix 4GL) exists to sublimeText (someone did) that it could convert ??

**Comment by OlegLustenko** [comment]
Hello @INGCRENGIFO, I had published 4GL language packages
If you enjoy it, give me feedback, please

more info here https://atom.io/packages/language-4gl

**Comment by 50Wliu** [comment]
Closing as a package has been provided.

**Comment by INGCRENGIFO** [comment]
Thank You  @OlegLustenko !!!!!!!!!
