### ISSUE TITLE
Bare caret/dollar not found in search and replace

### ISSUE THREAD

**Issue by bmhkim** [atom/atom#8735]
I'm trying to do a regex search and replace for start-of-line in order to prepend text to all of my lines in a file. However, a search for the caret character ('^') returns no results. This seems like a defect to me, I believe other editors such as Sublime and BBEdit/TextWrangler support this behavior. Note that a similar issue exists for the dollar sign character ('$').

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/find-and-replace? Thanks!

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.
