### ISSUE TITLE
Option to disable key binding tips

### ISSUE THREAD

**Issue by rondonjon** [atom/atom#8741]
Could you please add a settings option to disable the "key binding" tips that are displayed in the main area when no files are open? Some may find them helpful. I find them very distracting.

**Comment by peduxe** [comment]
The package name is `atom-background-tips`.

**Comment by mnquintana** [comment]
You can disable this feature by disabling the background-tips package:

<img width="745" alt="settings_-__users_machistequintana_github_settings-view_-_atom" src="https://cloud.githubusercontent.com/assets/823545/9787513/6890332c-5791-11e5-9069-4d570cc7f51d.png">

Hope that helps!

**Comment by rondonjon** [comment]
Great, thanks!
