### ISSUE TITLE
autocomplete occupies `return(enter)` and no way to change it

### ISSUE THREAD

**Issue by mfoman** [atom/atom#8746]
> It annoys me that autocomplete occupies `return(enter)` as a key.
> So when i try to make newline it autocompletes for me instead.
>
> And it is impossible to change!
> It might be a bug.

**Comment by benogle** [comment]
There is a setting in the autocomplete-plus settings that allows you to change it to tab or enter + tab

![tab](https://cloud.githubusercontent.com/assets/69169/9797182/bc9e198a-57ae-11e5-8730-a69f2c23830a.png)

**Comment by mfoman** [comment]
Woops, thanks.
Searched for autocomplete packages in packages, showed ac -atom-api and -css
Scrolled down, there was it. Danke, thanks for the quick reply.
