### ISSUE TITLE
OSX atom fails to save a file

### ISSUE THREAD

**Issue by ainstushar** [atom/atom#8750]
Hi there, searched for open issues with "save".... 8 pages of results so hopefully this is not a duplicate.

OSX 10.10.5, rMBP

I edited a js file and pressed `cmd+s` to save the file. Atom indicated that it saved the file (the little blue ring in the title of the file disappeared). But in reality, the file wasn't saved. Opened it with Sublime to find out that file wasn't being saved. No matter how many times I try to save the file in atom, it wouldn't save...

Not using git/version control.

Kind of a huge issue. If you need any info, please let me know. It happened randomly. If you need any more logs, please let me know.

Also, I opened a minified bootstrap.js file with atom in the same workflow and atom was lagging when editing that file. Maybe opening a large file can make a difference?

**Comment by goproAkan** [comment]
Env:
Atom 1.0.16
OSX 10.10.5, rMBP

I have been experiencing the same issue for the past 3 days.  I noticed when changes made were still reporting errors in my code.  The files are negligible size.  Then I used another application to verify that save itself works.  My hardrive had plenty of space.

**Comment by ainstushar** [comment]
Finally someone having the same issue. In work environment, I can't actually rely on atom with issues like failing to save files... Hopefully more people can reproduce this issue.

**Comment by 50Wliu** [comment]
@ainstushar what Atom version are you on?
And regarding `bootstrap.js`, Atom currently has a very hard time with minified files (#979).

Possibly related to #8888, #8849, #8874.

**Comment by ainstushar** [comment]
@50Wliu At the time of reporting this issue, 1.0.11? It was always updated. 
Could be related to those issues, but honestly it has only happened once or twice. Can I get some info on how to check logs or create a bugreport if this happens again?

**Comment by 50Wliu** [comment]
Atom doesn't create any logs, unfortunately.  Can you paste the output of `apm list --installed` here please?  Thanks.

/cc @maxbrunsfeld for debugging tips

**Comment by ainstushar** [comment]
````
/Users/ainstushar/.atom/packages (8)
├── Sublime-Style-Column-Selection@1.3.0
├── docblockr@0.7.3
├── file-icons@1.6.9
├── linter@1.5.2
├── linter-csslint@1.0.5
├── linter-jshint@1.2.0
├── symbol-gen@1.0.0
└── symbols-tree-view@0.10.0
````
