### ISSUE TITLE
Dragging vertical line selection doesn't include the last line 

### ISSUE THREAD

**Issue by vorg** [atom/atom#8754]
Here I'm trying to remove the whitespace by selecting it vertically (`alt` + drag) and then dragging it to the left the last line is not included.

<img width="526" alt="screen shot 2015-09-11 at 11 59 56" src="https://cloud.githubusercontent.com/assets/171001/9813368/c61dc450-587c-11e5-8b31-b8964bf988f0.png">

What's in the gif:
a) trying to select the white space vertically and deleting it -> the last line jumps
b) placing multiple cursors and deleting the whitespace one by one going backwards (backspace) -> works, all cursors move in parallel

![a3itn5glr3](https://cloud.githubusercontent.com/assets/171001/9813241/e7343a4e-587b-11e5-9d28-2b4fb96d9add.gif)

**Comment by vorg** [comment]
Surprisingly dragging from right to left works, only dragging from right to left is broken

![9jhwv2swbp](https://cloud.githubusercontent.com/assets/171001/9813607/f35e7c6e-587e-11e5-9bfe-004eb53f87aa.gif)

**Comment by izuzak** [comment]
> Here I'm trying to remove the whitespace by selecting it vertically (alt + drag)

I believe that's not a part of Atom core. Sounds like you're using a package to get that alt+drag behavior, perhaps https://github.com/bigfive/atom-sublime-select ?

**Comment by vorg** [comment]
True, actually this one https://atom.io/packages/Sublime-Style-Column-Selection will post there
