### ISSUE TITLE
Feature: Remove white space on enter to the right of the cursor

### ISSUE THREAD

**Issue by jcalfee** [atom/atom#8756]
I believe this is a very safe and hopefully an easy feature!  I don't know if any draw-back scenarios.  I use this feature all the time in another editor and frequently miss it when using Atom now...

It happens every time a line starts to get too long and the editor wants to make it multi-line.  So, given this line with this new feature, the enters can go in immediately after the `{`, `,`s

`this.setState({ wif_to_balances, balance_by_asset, balances_known: true ...`

Then instead of seeing this (the pipe is my cursor):

```
this.setState({
               | wif_to_balances, balance_by_asset, balances_known: true ...
```

One should see this:

```
this.setState({
               |wif_to_balances, balance_by_asset, balances_known: true ...
```

Small change but it cuts the work in 1/2 .. Also, I have yet to see a time when I really wanted to keep the white space after breaking a line with enter.

**Comment by jcalfee** [comment]
Additional restriction, if there is only whitespace on the left of the cursor, don't delete any white space but instead re-position the cursor to the start of the text.  Example:
| == cursor
Before enter:
```
    static getPropsFromStores() {
        var wallet = WalletManagerStore.getState()
   |    var backup = BackupStore.getState()
        return { wallet, backup }
    }
```
After enter:
```
    static getPropsFromStores() {
        var wallet = WalletManagerStore.getState()
     
       |var backup = BackupStore.getState()
        return { wallet, backup }
    }
```

**Comment by JoshStrobl** [comment]
> Also, I have yet to see a time when I really wanted to keep the white space after breaking a line with enter.

If I'm dealing with multi-line strings (yes, can still happen), I personally want to end with a trailing whitespace so I don't have to add a whitespace at the beginning of the new line, it  breaks the aesthetic of indentations / character alignment.

**Comment by jcalfee** [comment]
Example?

**Comment by jcalfee** [comment]
This does not strip spaces from the end of a line ..

**Comment by jcalfee** [comment]
To clarify: If you put the cursor after a space and press enter that space will remain at the end.  If you put it before the space then the indenter will place the cursor and this feature could detect that there is more space to the right of the cursor then some text and remove that space.  It is a very specific behaviour that seems to say out of the way of what people typically do.
