### ISSUE TITLE
Can't add text when I save file as with source file extension

### ISSUE THREAD

**Issue by awaemmanuel** [atom/atom#8757]
Hello Team, 

So I've noticed a weird behavior described below:
1. I open up atom.
2. Create a new file.
3. Save the file as maybe .java or .py
4. Try to add code, but it doesn't accept code.
5. I go to Sublime Text, open the same file, and I can add my code, that also appears on the atom version.

Can you please advise what this issue is?

**Comment by mnquintana** [comment]
Hmm that's quite strange. Is the editor focused after you save the file? (ie. is the cursor in the editor and blinking?) Can you try quitting Atom and reopening it in safe mode (`atom --safe`) and see if you can reproduce this?

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/8757#issuecomment-139608324. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
