### ISSUE TITLE
[feature request] add tiny command-line as a builtin atom package

### ISSUE THREAD

**Issue by Kimura1** [atom/atom#8761]
I want tiny command line in atom.
Certainly, There are many command-line packages, but they not enough.
someone package is heavy, or another one does not accept `sudo`.
I want vim like command line in atom

**Comment by peduxe** [comment]
@Kimura1 there's a package that 'turns atom into vim' - [vim-mode](https://atom.io/packages/vim-mode).

**Comment by mnquintana** [comment]
Since there is a [vim-mode](https://atom.io/packages/vim-mode) package for what you're describing already, I'm gonna close this out. Let me know if I'm misunderstanding though!
