### ISSUE TITLE
After splitting set the scrollbar to match the original

### ISSUE THREAD

**Issue by jcalfee** [atom/atom#8765]
Position the cursor 1 page down in a longer file then split the pane.  The new pain's scrollbar is set to top.  Instead it should scroll down to show the original code and cursor.

In other words, the cursor's position is correctly set after the split it is just not scrolling to make it visible.

EDIT: see acontreras89 below... new pane should match the original view (not the cursor, that may not be visible).   fyi, this is the behaviour I see in JEdit...

**Comment by TheJosh** [comment]
:+1: Please fix this it's very annoying

**Comment by acontreras89** [comment]
However, the cursor position might not be on the screen at the time the split is done. 
@mnquintana should we scroll to the cursor position or just replicate scroll from the original item?

**Comment by jcalfee** [comment]
Probably the original item.  The user can simply move the cursor to jump scroll to that view.  Finding the original view position is a more manual process.

**Comment by acontreras89** [comment]
@jcalfee :+1: 

Then adding a couple of lines to `Pane`'s `copyActiveItem` method should do the trick:
```coffeescript
copyActiveItem: ->
  if @activeItem?
    item = @activeItem.copy?() ? @deserializerManager.deserialize(@activeItem.serialize())
    item.setFirstVisibleScreenRow?(@activeItem.getFirstVisibleScreenRow?())
    item.setFirstVisibleScreenColumn?(@activeItem.getFirstVisibleScreenColumn?())
    item
```

Another option would be to do this within the `split` function:
```coffeescript
split: (orientation, side, params) ->
  if params?.copyActiveItem
    item = @copyActiveItem()
    item.setFirstVisibleScreenRow?(@activeItem.getFirstVisibleScreenRow?())
    item.setFirstVisibleScreenColumn?(@activeItem.getFirstVisibleScreenColumn?())
    params.items ?= []
    params.items.push(item)
```

I personally like the former most, but I'm not sure if there are cases in which the active item has to be copied with scroll position set to the first line.

**Comment by acontreras89** [comment]
@nathansobo should we add this to atom/pull/7953 ? 
This is specially annoying when you have the option to move (instead of copy) the active item in split operations, as scroll position is maintained when moving but not when copying.

**Comment by nathansobo** [comment]
@acontreras89 if you're inclined to address the scrollbar state in your PR, that would be really awesome. It did work at some point, but seems to have regressed. Should probably be pretty simple to ensure the `scrollTop` and `scrollLeft` are copied.

**Comment by acontreras89** [comment]
@nathansobo sure, no problem :ok_hand:
It was indeed as simple as passing `firstVisibleScreenRow`and `firstVisibleScreenColumn` when the `text-editor` constructor [is called](https://github.com/atom/atom/blob/master/src/text-editor.coffee#L497).
