### ISSUE TITLE
Can't type numbers when editing HTML

### ISSUE THREAD

**Issue by konxet** [atom/atom#8769]
Whenever I open an HTML file (in any fashion) for editing, I can't type numbers from the number pad or the number bar. I can work around this by copying the number I want and pasting it into my document.

**Comment by 50Wliu** [comment]
Can you please try to reproduce this in safe mode (`atom --safe`)?  In addition, what Atom version are you using?  Thanks.

**Comment by mrBarney** [comment]
This issue still exists and is persistent even in safe mode.

**Comment by hantuzun** [comment]
I experience this issue as well! On the latests Atom and macOS of today.

**Comment by NDari** [comment]
I am having this issue in HTML(Mustache)

Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

I had disabled my vim mode, and the problem presisted. I then proceeded to disable/uninstall each html/mustache addon I had, and the problem continues.

**Comment by NDari** [comment]
I forgot to mention, I have also tried `--safe` mode, and the same issue continued.

**Comment by Ben3eeE** [comment]
@NDari  What are the contents of your `keymap.cson` file?

**Comment by NDari** [comment]
@Ben3eeE That was the trick! I have the following:

```cson
'atom-text-editor[data-grammar~="html"]':
  'open-html-in-browser:open'
'.tree-view':
  'shift-o': 'open-html-in-browser:selected-entry'
```

Removing the above lines fixed the problem. Putting them back in, cause the problem again.
