### ISSUE TITLE
Upgrade - Search and replace

### ISSUE THREAD

**Issue by paaljoachim** [atom/atom#8771]
Hi

I am doing a search and replace and need a go to next or go to previous. As there will be instances that I do not want to replace. I found this: https://github.com/atom/find-and-replace

As it is better then the default. Do please upgrade the search and replace. It seems I am seeing different then what I should see...

This is what I am seeing:

![skjermbilde 2015-09-13 kl 09 02 33 am](https://cloud.githubusercontent.com/assets/5323259/9835665/3502ac62-59f6-11e5-9f43-5b30384cb536.png)

**Comment by Zireael07** [comment]
Press F3 to go next and Shift+F3 to go to previous.

**Comment by mnquintana** [comment]
I'm not sure what you mean - https://github.com/atom/find-and-replace •is* the find and replace that ships with Atom. You can "go to next" with <kbd>Enter</kbd> and "go to previous" with <kbd>Shift-Enter</kbd> - does that help?

**Comment by LoicGrobol** [comment]
What he means is probably that there should be buttons to do that, as in a lot of GUI text editors.

**Comment by Evpok** [comment]
What he means is probably that there should be buttons to do that, as in a lot of GUI text editors.

**Comment by mnquintana** [comment]
Ah indeed - @paaljoachim since you opened up [another issue](https://github.com/atom/find-and-replace/issues/524) on atom/find-and-replace I'm going to close this out in favor of that one.

**Comment by paaljoachim** [comment]
Thanks guys.... Have a great continued Sunday!
