### ISSUE TITLE
Crash on drag n drop in Arch

### ISSUE THREAD

**Issue by xavier83** [atom/atom#8774]
Atom crashes with the following message when I drag and drop any file/folder into it with the message below.
I am using atom in KDE Plasma - 5.4.0 under Arch.

```
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 955 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by despairblue** [comment]
Does not happen with i3 under arch. Can you reproduce this in other DEs?

**Comment by xavier83** [comment]
I am running kde with sddm.

**Comment by despairblue** [comment]
I meant if you would mind to try this with another DE, just to make sure that this only happens with KDE. :smiley:

**Comment by gandalf3** [comment]
Can reproduce using 1.0.11 on openbox

**Comment by xavier83** [comment]
even I didn't have to drop what I'm draggin as @gandalf3  described, same issue.

**Comment by miselico** [comment]
The same happens using ubuntu 12.04 / awesome window manager, but not for all drag actions: I only get these crashes when dragging a file directly from thunderbird. 

    [14935:0916/111050:INFO:renderer_main.cc(212)] Renderer process started
    [14903:0916/111055:INFO:CONSOLE(46)] "Window load time: 4509ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (46)
    The program 'atom' received an X Window System error.
    This probably reflects a bug in the program.
    The error was 'BadAtom (invalid Atom parameter)'.
      (Details: serial 911 error_code 5 request_code 20 minor_code 0)
      (Note to programmers: normally, X errors are reported asynchronously;
       that is, you will receive the error a while after causing it.
       To debug your program, run it with the --sync command line
       option to change this behavior. You can then get a meaningful
       backtrace from your debugger if you break on the gdk_x_error() function.)

**Comment by xgdgsc** [comment]
When I used GNOME shell, it does not crash when dragging, only crash in KDE for me.

**Comment by r-ku** [comment]
Can confirm KDE crash.

**Comment by vanboom** [comment]
Same issue here when I try to drag a color from gPick on Ubuntu 15.10.  Atom crashes.

**Comment by JoshWillik** [comment]
Also happens on arch with xmonad 0.12.

I don't have to drop the file. It crashes as soon as the dragged file crosses the atom window border.

I get the following logs:

```
[27%] ⚡ atom --safe
[27%] ⚡ [13979:0314/114436:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
App load time: 129ms
[13979:0314/114437:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[13979:0314/114437:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[13979:0314/114437:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[13979:0314/114437:WARNING:accelerator_util.cc(185)] Invalid accelerator token: command
[14022:0314/114437:INFO:renderer_main.cc(200)] Renderer process started
[13979:0314/114438:INFO:CONSOLE(46)] "Window load time: 989ms", source: file:///usr/share/atom/resources/app.asar/static/index.js (46)
[14014:0314/114438:ERROR:gles2_cmd_decoder.cc(11539)] [GroupMarkerNotSet(crbug.com/242999)!:D0A80E633D270000]GL ERROR :GL_INVALID_OPERATION : glTexStorage2DEXT: <- error from previous GL command
The program 'atom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAtom (invalid Atom parameter)'.
  (Details: serial 715 error_code 5 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by xavier83** [comment]
I've upgraded atom to 1.5.4 and it doesn't crash on KDE plasma anymore.It still doesn't open the dragged file though.

**Comment by xavier83** [comment]
Upgraded to 1.16.0 and the dragging and dropping file/folder is working, but dropping a folder to the project list side bar, it doesn't get added to the list. maybe that is another issue. closing this now. Thanks for the fixes 😄
