### ISSUE TITLE
Editor Tab Type "auto" doesn't update after whitespace conversion

### ISSUE THREAD

**Issue by wmertens** [atom/atom#8777]
When setting Tab Type to "auto" and running "Whitespace: spaces to tabs" or vice versa, new tabs will remain the old type.

Workaround: close the tab and re-open.

**Comment by alexandernst** [comment]
Related to https://github.com/atom/atom/issues/4054

**Comment by wmertens** [comment]
Ah indeed a duplicate. The referenced bug is not fixed though although it mentions it will be fixed before 1.0 :-) 

Anyway I'll close.
