### ISSUE TITLE
Make .twig files open with PHP syntax

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#8782]
.twig files are basically PHP files, it would be nice if they could be opened with PHP syntax/highlighting by default.

**Comment by izuzak** [comment]
Thanks for the suggestion. You should consider opening an issue or pull request on the language-php package to update [this list](https://github.com/atom/language-php/blob/befafefa06df28386f33a62bc0ab32bbb289f3b8/grammars/php.cson#L3-L17). This is not related to Atom core, as far as I can tell.
