### ISSUE TITLE
Package search times out in ipv6 only environment (connect ETIMEDOUT)

### ISSUE THREAD

**Issue by GothAck** [atom/atom#8786]
I'm currently testing an ipv6 only network env, with 6to4 NAT. In this environment it seems (at least) package search times out with "connect ETIMEDOUT".

**Comment by lee-dohm** [comment]
Can you reproduce this using the apm tool at the command line?

**Comment by nethad** [comment]
@lee-dohm 

I'm currently on an IPv6 only network, with NAT64 configuration.

```
$ apm update
Request for package information failed: connect ENETUNREACH 54.235.212.238:443 - Local (0.0.0.0:0)
```
```
$ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.9.3
```

This looks to me like there's a hardcoded IPv4 address or something that's not compatible with IPv6-only networks.
