### ISSUE TITLE
squirrel-update-spec not really testing desktop shortcut

### ISSUE THREAD

**Issue by BrainCrumbz** [atom/atom#8789]
It looks like test *keeps the desktop shortcut deleted on updates if it was previously deleted* in [squirrel-update-spec](https://github.com/atom/atom/blob/master/spec/squirrel-update-spec.coffee) is not really doing its job.

We tried removing a meaningful bit of functionality in code under test (see 
[this commit](https://github.com/BrainCrumbz/atom/commit/b34d9c50312158a675017b06600c0c04872c45af)) and the test still passes.

Now having a look at possible cause. Probably that's because ~~the *ChildProcess* is being mocked *too much* [here](https://github.com/atom/atom/blob/fb3cc5554c1913c6002c76bf3d12967bdde72d1f/spec/squirrel-update-spec.coffee#L20). Or, maybe~~ there's no test *really* checking that desktop shortcut is created in the first place? (otherwise expectation on [line #82](https://github.com/atom/atom/blob/fb3cc5554c1913c6002c76bf3d12967bdde72d1f/spec/squirrel-update-spec.coffee#L82) should fail).

Is this test behavior intended?

**Comment by 50Wliu** [comment]
I can confirm that the desktop shortcut is in fact coming back every update, and it is pretty annoying.

**Comment by BrainCrumbz** [comment]
Although I'd prefer to take care of this after PR #8780 gets (?) merged.

**Comment by BrainCrumbz** [comment]
Uhm. Taking my word back, maybe that's a false problem. [In this other commit](https://github.com/BrainCrumbz/atom/commit/8b3a0aed6700fbd8b41edf0f83c3f77d9f036b85) I just skipped the check for existing shortcut, so that it gets always created. Result: the test (correctly) fails.

**Comment by BrainCrumbz** [comment]
Even refactoring spec to make any assertion *explicit* as in [here](https://github.com/BrainCrumbz/atom/commit/3c549dda7d9b49109e1513b23bd3c5791d4c67fb), desktop shortcut tests still pass.

**Comment by BrainCrumbz** [comment]
Just created PR #8793 to make desktop shortcut tests intent more clear (and they all still pass)

**Comment by 50Wliu** [comment]
Closing in favor of #5323.
