### ISSUE TITLE
No way to go from a TextEditor to a File

### ISSUE THREAD

**Issue by bolinfest** [atom/atom#8791]
A `TextEditor` has a `TextBuffer` which likely (but is not guaranteed to) have a `File`. `TextEditor` has a public `getBuffer()` method, but there is no public API on `TextBuffer` to get to the corresponding `File`.

As a result, instead of passing around a `File`, most packages pass around a string `path`, which is assumed to be a local file path. This can lead to bugs like:

https://github.com/gandm/language-babel/issues/66

because it's not safe to assume you can call things like `require('path').dirname()` on the path from the `TextEditor` because it might be a URI rather than a local file path:

https://github.com/bolinfest/language-babel/blob/b3fe5a544b2c707f5094a327788b0eb438cf0f25/lib/transpiler.coffee#L174

If we want to encourage more packages to be agnostic as to whether files are local or remote, we should make it easier to use a `File` rather than a path.

**Comment by nathansobo** [comment]
Want to add a `TextBuffer.prototype.getFile` method and delegate through to it from `TextEditor`? It would return `null` in some circumstances because we don't have a pattern of doing option types or anything.

**Comment by bolinfest** [comment]
@nathansobo Sounds good: will do.

**Comment by nathansobo** [comment]
Ping me on it so I can review promptly.

**Comment by daniel-pittman** [comment]
@bolinfest, are you still working on this?  It's a blocker for a current feature I want to implement, but I don't want to duplicate your work, so...

**Comment by nathansobo** [comment]
Pretty sure @bolinfest got pulled off to other things, so fire away @daniel-pittman.
