### ISSUE TITLE
.cs(C#) file that saved 'CRLF' is always changed state in all lines. 

### ISSUE THREAD

**Issue by dark0084** [atom/atom#8792]
![2015-09-15 2 20 32](https://cloud.githubusercontent.com/assets/4486373/9868538/e4ed39a2-5bb4-11e5-872d-14f4ea84b587.png)

not changed
![2015-09-15 2 28 35](https://cloud.githubusercontent.com/assets/4486373/9868610/00965246-5bb6-11e5-92b6-37a41e9f740d.png)

Atom : 1.0.11
OS : OS X Yosemite 10.10.5

.gitattribute
*.cs text eol=crlf

After git commited, occured same issue in all .cs file(CRLF).

**Comment by lee-dohm** [comment]
This sounds like the same issue that Windows users face when trying to share CRLF terminated files without setting Git's configuration for it. Check #3768 for details, this may well be a duplicate.

**Comment by dark0084** [comment]
Sorry, I read #3768. 
But, It did not create the project on Windows. I work only Mac.
I tried the line ending normalization, it is still an issue occurs.
All .cs files in project don't targeted the line ending normalization.
It is setting 'core.autocrlf=true' in git's configuration.
