### ISSUE TITLE
Warn users when one keybinding's keystroke is a prefix of another

### ISSUE THREAD

**Issue by izuzak** [atom/atom#8795]
See https://github.com/atom/atom/issues/8706 and https://github.com/atom/atom/issues/6233 for context.

When users define two keybindings, and one keybinding's keystroke is a prefix of another -- then [a timeout is used](https://github.com/atom/atom-keymap/blob/411ae894194e6563019498c7a9b60a28f22513b7/src/keymap-manager.coffee#L56-L64) as a way of determining what to do next if the user hits that prefix (execute the command for that prefix or wait for more keys so that the longer keystroke can be matched).

In such situations, some users are confused that it takes so long to execute the command. Perhaps a warning (in the form of a [notification](https://github.com/atom/notifications)) might help reduce this confusion?

/cc @nathansobo

**Comment by nathansobo** [comment]
When would the notification be displayed? Always dreamed of a keybinding editor but that's a ways off.

**Comment by izuzak** [comment]
> When would the notification be displayed?

Great question, @nathansobo. I'm not sure, so here's one idea: show the warning either when 1) the user manually creates a new keybinding (in `keymap.cson`) that is a prefix of another existing keybinding or for which another keybinding is a prefix of, or when 2) the user installs a package which contains a keybinding which matches the same description.

**Comment by nathansobo** [comment]
Another idea... a status bar entry indicating that they're in a pending state when they type the first key. Not sure what we'd show exactly. Maybe `Pending Binding: cmd-k`.
