### ISSUE TITLE
Operation not permitted saving hidden files

### ISSUE THREAD

**Issue by rmp135** [atom/atom#8797]
OS: Windows 10
Atom version: 1.0.11

To recreate:
Create a file and set the hidden flag to true in the file properties.
Open the file in Atom.
Add some text and attempt to save.
An "Operation no permitted, open '<filepath>'" error will apear.

**Comment by damieng** [comment]
Confirmed still repros in master 
![image](https://cloud.githubusercontent.com/assets/118951/15062946/85a01f3e-12fa-11e6-9968-70b854730f96.png)
