### ISSUE TITLE
Need overflow/scroll on text field in filename dialog

### ISSUE THREAD

**Issue by sparkjames** [atom/atom#8799]
Referring to the text field in the "filename dialog", which appears when you right-click in the file tree and do Rename, New File, or New Folder...

It doesn't resize and/or it doesn't scroll to follow the text cursor. It seems to have a set width and if the filename or path is longer than the width of the text field then the overflowing text is hidden.

Usually in these sort of text fields the text will scroll to follow the cursor so that you can still read the text that would normally overflow.

I like to use the New Folder and New File features, but if it's too deep in the project directories it gets really frustrating that I can't use it.

http://i.imgur.com/nFOqz8X.gif

## Repro Steps

1. Right-click a file in the file tree and select "Rename"
2. The filename dialog appears.
3. In a file with a path longer than the width of the text field, attempt to view any text that is overflowing out of the field.

**Expected:** I expect the text field to scroll with the overflowing text.
**Actual:** The text field does not scroll/resize at all. This makes it impossible to see the filename if it has a path that is longer than the width of the text field.

## Command History

```
     -0:52.8 ready (#document)
     -0:50.1 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:46.5 core:confirm (atom-text-editor.editor.mini)
     -0:45.4 core:close (div.image-view)
     -0:29.1 core:backspace (atom-text-editor.editor)
     -0:26.4 editor:select-to-previous-subword-boundary (atom-text-editor.editor)
     -0:24.9 settings-view:open (atom-text-editor.editor)
     -0:00.0 bug-report:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-cool-syntax-for-attractive-people.theme-atom-dark-ui)
```

## Versions

* **Atom:**       1.0.11
* **Atom-Shell:** 0.22.3
* **OS:**         Mac OS X 10.10.5
* **Misc**
    * Could not determine apm version information

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by mnquintana** [comment]
Thanks for the report! This looks like another symptom of https://github.com/atom/tree-view/issues/473 - can you take a look at that issue and see if it looks like what you're experiencing? Thanks!

**Comment by sparkjames** [comment]
That is exactly what I'm experiencing! I tried searching for that issue,
but after several google attempts I couldn't find it.

Thank you for pointing me in the right direction.

__________________________












* James Pfleiderer Senior Front-end Developer (d) 301.358.0310(o)
301.294.3340james@sparkexperience.com <james@sparkexperience.com>
www.sparkexperience.com <http://www.sparkexperience.com> We are a green
certified business — please consider the environment before printing this
email. *

**Comment by 50Wliu** [comment]
In that case, I'm going to close this out :).
