### ISSUE TITLE
Expose monospace font-family as UI variable

### ISSUE THREAD

**Issue by ssorallen** [atom/atom#8800]
There is currently a `@font-family` variable in ui-variables.less for the standard UI font:

```
@font-family: 'SF UI Text', 'Lucida Grande', 'Segoe UI', Ubuntu, Cantarell, sans-serif;
```

Exposing the monospaced font-family as `@font-family-monospaced` or similar and using that in atom-text-editor would enable monospace theming.

```
@font-family-monospaced: Menlo, Consolas, 'DejaVu Sans Mono', monospace;
```

**Comment by jgebhardt** [comment]
+1

**Comment by simurai** [comment]
A problem is that Less variables can't be overridden from the settings.

If a theme would define `@font-family-monospaced`. But then a user wants to change the font in the settings:

![screen shot 2015-09-17 at 10 07 21 pm](https://cloud.githubusercontent.com/assets/378023/9933902/2a6c553c-5d89-11e5-9f8c-ed098a9798c2.png)

`@font-family-monospaced` wouldn't get updated to `Fira Mono`.

**Comment by ssorallen** [comment]
@simurai How does the "Font Family" input work right now? There's a `@font-family` Less variable that themes can override already.

**Comment by simurai** [comment]
They are used in separate places. Currently it works like this:

![fonts](https://cloud.githubusercontent.com/assets/378023/9948554/0571acfe-5ddf-11e5-9b08-cfd500f259f8.png)

- `@font-family` is only applied outside of the editor. Or if a package uses it.
- Inside the editor, some default monospaced fonts are used, unless they get overridden by the user in the settings.

> and using that in atom-text-editor would enable monospace theming.

Are you thinking about creating a Syntax theme that has a custom monospaced font?

**Comment by Stanzilla** [comment]
After the default font changes, I find myself unsure on how the font options work. Previously the UI font was Segoe on Windows, after the change it looks like Times New Roman or Tahoma. Now I'm kinda missing an option to change the font of the whole UI separate from the one the editor window uses...

**Comment by simurai** [comment]
Got reminded of this by @joefitzgerald.

An option would be to inline the font-family config from the editor + a [fallback stack](https://github.com/atom/atom/blob/master/static/text-editor-light.less#L7) (in case it's not set), like: 

```js
atom.config.get('editor.fontFamily') + 'Menlo, Consolas, "DejaVu Sans Mono", monospace'
```

The fallback stack might get changed in core one day, but at least it would match if a user sets a custom font.

We could also look into using CSS variables, now that they're available in Chromium/Electron. Colors would be more tricky in case you want to manipulate them, like darken/lighten. But font-family would be fine. Then it can be updated from the settings and be used in style sheets.

**Comment by simurai** [comment]
🤖 Stale Bot is so timely. https://github.com/atom/atom/pull/16731 got merged yesterday!

From Atom `1.26` you'll be able to use the `--editor-font-family` custom property that matches the editor font family. Use like:

```less
.myClass {
  font-family: var(--editor-font-family);
}
```
