### ISSUE TITLE
Configurable number of lines below cursor-line

### ISSUE THREAD

**Issue by johnmuhl** [atom/atom#8802]
As you navigate downwards in a file Atom always keeps two lines below the current cursor-line. In the screenshot pressing <kbd>ctrl-n</kbd> or <kbd>⬇︎</kbd> once will bring line 55 into view.

![screen shot 2015-09-14 at 16 12 45](https://cloud.githubusercontent.com/assets/7944/9890626/a0168ce0-5bc6-11e5-8d79-de6fd1307c9b.png)

Could this number of lines be made configurable?

**Comment by as-cii** [comment]
I think you might be looking for `TextEditor::setVerticalScrollMargin`. As far as I know, there isn't a configuration parameter for it, but you can put the following in your init script:

```coffee
atom.workspace.observeTextEditors (e) -> e.setVerticalScrollMargin(n)
```

So that, when you go up or down with the cursor, you always have `n` rows as your margin.
