### ISSUE TITLE
Popover when you click on tab lingers when you have two panes and you close the parent pane.

### ISSUE THREAD

**Issue by samtechie** [atom/atom#8805]
![screenshot from 2015-09-15 16 48 02](https://cloud.githubusercontent.com/assets/1004825/9878245/5b066842-5bca-11e5-9232-7affd10b8bee.png)

When you open two panes and you hover over a tab in one of the panes the popover showing the file location appears and then you right click to close the pane the popover lingers  as shown in the screenshot. When you hover over other tabs their popovers will appear as normal but the lingering popover remains unless you minimize and maximize the window again. Am using Atom 1.0.0 and Opensuse 13.2

**Comment by izuzak** [comment]
Thanks for the report -- I'm having trouble reproducing this on OSX and latest version of Atom.

Can you please reopen this in https://github.com/atom/tabs and also make sure you're on the latest version of Atom (1.0.11, not 1.0.0)? Also try reproducing this in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode).

**Comment by samtechie** [comment]
@izuzak I upgraded to 1.0.11 and you are right the issue is resolved. It is not necessary to reopen it as it only affects the older version of atom. Thanks.
