### ISSUE TITLE
Autocomplete CSS class/id in HTML/PHP files (and vice versa optionally)

### ISSUE THREAD

**Issue by PixelT** [atom/atom#8806]
It will be nice, when I write:
```
<div class="">
```
and the cursor is betwteen class="|" the autocomplete will show the class / id which I defined in my sass / scss / less / css files

Optionally: When I start write in sass / scss / less / css files by typing . or # the autocomplete display class / id which I defined in my HTML / PHP files.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/autocomplete-html? Thanks!

Also take a look at https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290 for a guide on where to post issues.
