### ISSUE TITLE
Wrap-guide hides cursor

### ISSUE THREAD

**Issue by Pugio** [atom/atom#8812]
The wrap-guide's z-index is 100, and the cursor's is 4. When the cursor occupies the same column as the wrap guide, the wrap guide covers it. You won't notice this with the default cursor size of 2px, but if you prefer a single pixel cursor (as I do), the cursor disappears at the wrap-guide.

Is there a reason the cursor's z-index can't be moved higher than the wrap-guide's?

**Comment by benogle** [comment]
I am not able to reproduce this with the latest version of the one-dark theme. What theme are you using? 

![screen shot 2015-09-16 at 11 00 08 am](https://cloud.githubusercontent.com/assets/69169/9913539/3624e01a-5c62-11e5-8604-fb99d56cccb2.png)

**Comment by Pugio** [comment]
My apologies. I didn't notice that the wrap-guide was implemented with a 15% opacity (if you change it's color to red, for example, you'll see it occlude the cursor). The theme I was using (Tomorrow Night Eighties) uses a straight background color, and hence covered the cursor.

It would be nice if active elements, like the cursor, were placed above static indicators like wrap-guides, (to make it easier for theme authors, and because it seems to make sense), but I guess this is not really an atom core bug. Thanks for checking it out.

**Comment by simurai** [comment]
This got fixed here https://github.com/atom/wrap-guide/pull/36 and should be in the next Atom update.

The wrap-guide will have a z-index of `3`, so cursors should be on top.
