### ISSUE TITLE
Soft Wrap did not work in Chinese

### ISSUE THREAD

**Issue by Huxpro** [atom/atom#8819]
I dont know why but it just not work...not only `soft warp` but also `soft wrap at preferred line length`
sometimes I need to write README/Post in Chinese, so it didnt work make me sad

**Comment by izuzak** [comment]
Thanks for the report. This is a know issue being tracked here: https://github.com/atom/atom/issues/1783, so I'm going to close this in favor of that issue.

**Comment by Huxpro** [comment]
Thanks
