### ISSUE TITLE
Backslash not working on Swedish keyboard

### ISSUE THREAD

**Issue by patriksvensson** [atom/atom#8820]
For some reason I can't write `\` in Atom. On a Swedish keyboard, this is the combination of `AltGr`+ `+`. Other combinations with `AltGr` works (like `}`).

**Comment by mnquintana** [comment]
Thanks for the report! This looks like the same issue as https://github.com/atom/atom-keymap/issues/35 – closing out in favor of that issue.

**Comment by csvn** [comment]
A workaround for this is by adding the following to your keymap.cson file:
```
'atom-workspace atom-pane':
  'ctrl-alt-=': 'unset!'
```

Seems to work fine for me.

**Comment by ttsirkia** [comment]
Thanks for the tip!

**Comment by jimmysjolund** [comment]
I noticed a workaround on Windows. If I first type the `¨` -key and then `alt-gr` + `\` it works.

**Comment by fredrikaverpil** [comment]
Thanks @csvn  - your suggestion worked for me!

**Comment by mikael1000** [comment]
I have this problem. Why isn't this fixed yet?

**Comment by patriksvensson** [comment]
@mikael1000 Because no one submitted a PR for it?

**Comment by Ben3eeE** [comment]
@mikael1000 You can try installing the keyboard-localization package instead if you don't want some ridiculous workaround.
