### ISSUE TITLE
node v4

### ISSUE THREAD

**Issue by Zverushko** [atom/atom#8823]
hello!
in my arch node version is 4.0
and atom not build

do you plan to support v4? 
thx!

**Comment by Zverushko** [comment]
i download node v10.9 and replace /usr/bin/node 
atom build success and get node v10.40 (save in /usr/share/atom/resource/bin)
a remove v10.9 and back v4 in /usr/bin/node

**Comment by 50Wliu** [comment]
Duplicate of #8508, please subscribe there for updates.
