### ISSUE TITLE
Cannot find module binary

### ISSUE THREAD

**Issue by fusion809** [atom/atom#8831]
Hi,

I'm trying to upgrade from Atom 1.0.11 to 1.0.13 on Sabayon. I originally installed 1.0.11 from source code from the method outlined in `linux.md`. To upgrade to 1.0.13 I ran:

```sh
git fetch -p
git checkout v1.0.13
script/build
sudo script/grunt install
```
from my clone of the Atom git repo. `script/build` gave this output:

```sh
Node: v0.12.7
npm: v2.13.3
Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓
Running "download-electron" task

Fatal error: Cannot find module 'binary'
```

I had never seen this error before, even though I have used this upgrade technique before without error. 

Thanks for your time,
Brenton

**Comment by thomasjo** [comment]
I'm assuming this issue was resolved due to inactivity. If that's not the case, re-open it.
