### ISSUE TITLE
Is there a verbose backup function?

### ISSUE THREAD

**Issue by johnsonz** [atom/atom#8835]
Assume the following scenario, I modified a file with atom, saved it, closed atom. Suddenly I realize I was wrong, I want to restore the file. But there is not a backup file, and undo or ctrl+z does not work. 
So I must modify it manually.
So should add a verbose backup function?  It will backup it automatically when I modify the file. Of course, more disk space will be used.

**Comment by 50Wliu** [comment]
There should be an option in Atom 1.0.4 and above - just check the "Back Up Before Saving" option in Settings.
