### ISSUE TITLE
Auto-update should not be compulsory

### ISSUE THREAD

**Issue by artcommacode** [atom/atom#8838]
##### Expected:
I open Atom, ready for another productive day of work.

##### Reality:
Atom uses all 60KB/s of my bandwidth to download an unneeded update and I can't get anything done for the next hour.

##### Possible Fixes:
Add a checkbox to Settings that allows those of us in low-bandwith situations to turn off auto-updating.

Thanks!

**Comment by 50Wliu** [comment]
Duplicate of #1882, please subscribe there for updates.

**Comment by artcommacode** [comment]
Obviously I didn't search well enough. Thanks
