### ISSUE TITLE
CustomEvent inheritance change breaks vim-mode in 1.12

### ISSUE THREAD

**Issue by bhuga** [atom/atom#8845]
[This commit](https://github.com/atom/atom/commit/e3f9074f4a98f15a4436a79a2209e2fdece85dd4), added in 1.12 released a day ago, removes `originalEvent` from dispatched events. This breaks vim-mode's use of the same event for multiple different keys:

```cson
  '1': 'vim-mode:repeat-prefix'
  '2': 'vim-mode:repeat-prefix'
  '3': 'vim-mode:repeat-prefix'
```

I've poked around at the new events from the vim-mode point of view, and without the `originalEvent`, there's no way to fix it other than to create tons of unique events, like in [this commit](https://github.com/atom/vim-mode/commit/d73e0916c51374c22c36fb4fd9931e7ded0b4c17), which is so bad I can't bring myself to make a PR out of it.

It seems like the breaking commit is attempting to keep the API the same, but the original event keys are part of the event prototype, not the event, so they're not copied. It looks like there's been [some work on that file](https://github.com/atom/atom/commits/master/src/command-registry.coffee) since the breaking commit, but nothing in the last day or two, so I'm hoping this isn't a duplicate.

For reference, the vim-mode code that's referencing the missing `originalEvent` is [here](https://github.com/atom/vim-mode/blob/master/lib/vim-state.coffee#L587-L588) and [here](https://github.com/atom/vim-mode/blob/master/lib/vim-state.coffee#L575-L576). And the break is pretty dramatic, making vim-mode more or less unusable.

**Comment by bhuga** [comment]
The vim-mode bug, with plenty of :+1:'s, is here: https://github.com/atom/vim-mode/issues/863

**Comment by nathansobo** [comment]
Will release a hotfix. Thank you.

**Comment by mnquintana** [comment]
Fixed in https://github.com/atom/atom/pull/8848
