### ISSUE TITLE
.atom/storage corruption messing up blue dot on dirty buffers

### ISSUE THREAD

**Issue by ssfrr** [atom/atom#8846]
I'm having a strange issue where sometimes Atom stops displaying the little blue dot in the tab bar for dirty buffers (unsaved modified files).

This has happened twice now since yesterday, and each time it was resolved by deleting my `.atom/storage` directory.

Any thoughts on first troubleshooting steps?

**Comment by 50Wliu** [comment]
Actually going to close this in favor of #8849 since maxbrunsfeld just assigned himself to that issue.
