### ISSUE TITLE
Interface is blank on 3/4 of screen

### ISSUE THREAD

**Issue by erikanderson** [atom/atom#8847]
Just updated to 1.0.13 on OSX 10.10.5. When I open up atom through the command line(`atom`) or through the dock icon 3/4 of my screen is white: 

![screen shot 2015-09-18 at 10 29 36 am](https://cloud.githubusercontent.com/assets/4634290/9964914/2e1b8d58-5df0-11e5-80df-d68122e063ca.png)

It looks like it is only happening if I have it at a certain size on my external monitor (thunderbolt display running @ 2560-by-1440). The window size in that screen shot is around 2400x1300

This also happens if I run it in safe mode from the command line (`atom --safe`)

It does fix itself if I resize the window

**Comment by mnquintana** [comment]
Before you last quit Atom, was the window size smaller? (ie. the size of your computer's built-in display, for instance)

**Comment by erikanderson** [comment]
If I set the window size smaller (like 1900x900) it opens normally. Its only when I set the window size around 2400x1300 that it happens

**Comment by Yahkob** [comment]
I have this problem as well, if it helps I use slate.js as a window manager. I close Atom with it taking up the whole screen but not full screened

**Comment by bryanrsmith** [comment]
I'm seeing this as well. It only happens when Atom opens at larger window sizes on my thunderbolt display.

> Before you last quit Atom, was the window size smaller? (ie. the size of your computer's built-in display, for instance)

No. The window size was the same as it is now, and the problem can be consistently reproduced by closing and reopening Atom without resizing the window to a smaller size.

**Comment by erikanderson** [comment]
This seems to be fixed on El Capitan fyi

**Comment by zslabs** [comment]
@erikanderson Running into this on El Capitan.

**Comment by Tedko** [comment]
I'm using 10.11, not fixed

**Comment by kangman** [comment]
@bryanrsmith  same with me. running **OSX 10.10.5** and  **Atom 1.0.19**

**Comment by pydolan** [comment]
I'm experiencing this same issue when connecting to a Dell U2415. I'm using OS X 10.11.1 with Atom 1.1.0 on a retina MBP.  *I think* this is a new problem within the last week or so (I could be wrong), and this is around when I got the Atom 1.1.0 update *and* upgraded to El Capitan, so maybe related to one of these upgrades?

**Example of triggering bug:**

1. Have atom on external monitor (in my case, 1900x1200 resolution, and atom roughly at 1500x1100)
2. Disconnect monitor cable (in my case, display port cable plugged into thunderbolt v2 port); this triggers atom to pop over to laptop's display
3. plug monitor cable back in; and Atom returns to external monitor, but with 1/4 of window showing content, the other 3/4's cropped and white.

**Comment by jaisongreen** [comment]
I am having the same issue here. I am using OSX 10.11.1 with Atom 1.1.0 on a 13" MBP over thunderbolt.

Steps to reproduce:
1) Atom open on an Ultrawide 3440x1440 monitor (not fullscreen).
2) Disconnect monitor and use laptop on built in display.
3) Reconnect Ultrawide monitor. Now Atom is shown exactly like the original image.

**Comment by geeeeeeeeek** [comment]
I'm having this issue on El Captain. When I move a fullscreen atom to a second display, it leaves large piece of blank.
![qq20151104-0](https://cloud.githubusercontent.com/assets/7262715/10940678/a9b096b2-8342-11e5-9156-016e80703045.png)

**Comment by pydolan** [comment]
FWIW, Chromium had this same bug last year, so their solution may be useful to whoever tackles this issue with Atom: [Chromium bug](https://code.google.com/p/chromium/issues/detail?id=424713)

**Comment by KapJI** [comment]
I have same issue, but it also works in other direction: when I move window to retina from non-retina window renders blurry like in compatibility mode.

**Comment by erikanderson** [comment]
I'm going to close this since it seems to be resolved in the newer versions of Atom
