### ISSUE TITLE
No more unsaved file indicators

### ISSUE THREAD

**Issue by AgentME** [atom/atom#8849]
It seems that as of 1.0.12 or 1.0.13 there's no longer an indicator (the blue circle) for me in the tab near the filename if the file has unsaved changes. This is still true if I start atom with `--safe`. I'm on OS X.

**Comment by AgentME** [comment]
Huh, some of my tabs still show unsaved indicators, but some of my tabs refuse to. Closing and reopening the specific tab seems to fix the tab. (But weirdly, restarting Atom does not fix a tab.)

Using the developer tools, I can see that saved tabs normally have the "tab" and "sortable" classes, and the tabs with the unsaved indicators have the "modified" class added. The tabs that are missing their unsaved indicator are missing their "modified" class, so I know it's not some theme/styling issue (I'm using the default theme anyway afaik).

**Comment by 50Wliu** [comment]
Can you please try removing `~/.atom/storage` and see if that fixes your issue?

**Comment by AgentME** [comment]
Closing the affected tabs and reopening them already seemed like a way to work around the issue, though that worked too.

**Comment by 190n** [comment]
I'm getting this too. Atom 1.0.15, Debian 8.2.

**Comment by pldrake26** [comment]
I also have no blue unsaved files indicator on tabs after upgrade to version 1.0.15.

**Comment by NTICompass** [comment]
I'm running Atom 1.0.15 on Windows 10 and I realized that the blue "modified" file indicators are missing.

**Comment by FloFra** [comment]
There seems to be any issue with atoms storage being out of sync with the file being edited (#8888). The files in question also have a broken save indicator most of the time. Just wanted to mention that, since it seemed somwhat related to this bug.

**Comment by AndrewSepic** [comment]
I have the same issue. Atom 1.0.16, Windows 10

**Comment by tedyun** [comment]
Same issue Atom 1.0.15-1.0.17, Windows 10 x64 and Windows 7 x64. Error also reported in the Atom discussion forum https://discuss.atom.io/t/atom-does-not-detect-alert-unsaved-changes-v1-0-15-windows-10/20984

**Comment by benogle** [comment]
cc @simurai

**Comment by maxbrunsfeld** [comment]
Ok, I just released Atom 1.0.18. I believe it should fix this issue, if removing the ~/.atom/storage directory did not already fix it. Everyone, please let me know if you're still experiencing this on 1.0.18.

**Comment by tedyun** [comment]
The issue persists in Atom 1.0.18 (Windows 10 x64). I also tried removing ~/.atom/storage, ~/.atom/.apm, ~/.atom/compile-cache directories but it didn't fix the issue.

Steps to reproduce the issue:
1) Open a folder with "Open Folder..." and close all other Atom instances.
2) Open a file
3) Edit the file => At this point the blue indicator DOES work.
4) Close Atom.
5) Open Atom (it re-opens the last edited file)
6) Edit the file => Blue indicator doesn't show up.

Thanks,
Ted

**Comment by maxbrunsfeld** [comment]
@tedyun You're right. Thanks so much for providing these repro steps!

FWIW, the problem was partially fixed, but not completely. Autosave should work correctly now, but after reloading an Atom window, an event is not getting emitted properly the *first* time a buffer changes from unmodified to modified. I'll have a fix shortly.

**Comment by maxbrunsfeld** [comment]
Ok, @tedyun can you try on Atom 1.0.19. I believe this error is fixed.

**Comment by tedyun** [comment]
@maxbrunsfeld Confirmed fixed in 1.0.19. Thank you so much!

**Comment by maxbrunsfeld** [comment]
Great to hear. Everyone, please let me know if you see any other problems with this.

**Comment by pldrake26** [comment]
My Atom is fixed also.  Thank you!
