### ISSUE TITLE
Atom can be pinch and tap zoomed on OS X

### ISSUE THREAD

**Issue by idmean** [atom/atom#8850]
It is possible to zoom in the whole editor on OS X using the pinch zoom gesture on the trackpad. If you do this accidentally I can be really hard to zoom out back. I don’t believe this is an intended feature, is it? 

Occurs in Atom 1.0.13.
![bug](https://cloud.githubusercontent.com/assets/5495918/9968820/0bfcc77c-5e4b-11e5-878d-6fe32a5413d8.gif)

**Comment by mnquintana** [comment]
Confirmed in Atom 1.0.13 and OS X 10.10.5

**Comment by zcbenz** [comment]
There is a `webFrame.setZoomLevelLimits` API to fix this, but it is added after electron v0.31.1, we need to merge #8779 first.

**Comment by johnjelinek** [comment]
:+1:

**Comment by tbillington** [comment]
This still happens when I use atom 1.6.0 on OSX 10.9.5 when pinching over the tree view.

**Comment by mnquintana** [comment]
Confirmed that this is still an issue in 1.8.0-dev-74407fc

cc @atom/feedback

**Comment by davidlukerice** [comment]
Also still happens when two finger tapping ("smart zoom") anywhere in the editor.

**Comment by tonyneel923** [comment]
Would be awesome if you used pinch and zoom as an alternative to cmd + shift + '+'

**Comment by timscott** [comment]
In case if happens to you, **two-finger-double-tap** will unzoom (in 1.5.1)
