### ISSUE TITLE
Multiple theme/syntax switching causes errors

### ISSUE THREAD

**Issue by rugk** [atom/atom#8860]
**Edit:** If you want to skip all my own troubleshooting start reading at this comment: https://github.com/atom/atom/issues/8860#issuecomment-141775143

----

The Light UI theme shows dark parts when I switch from Atom dark theme to Atom light:
![atomlightdesign](https://cloud.githubusercontent.com/assets/11966684/9838056/b0758f60-5a53-11e5-9da6-a65c6bdcdb7d.PNG)

I don't know whether it's caused by the core or by another package, but I'm trying to get this out.
Actually when I run Atom with the -safe-mode option it works.

**Comment by rugk** [comment]
(the following are screenshots from different states of the editor - different packages where enabled/disabled)
Actually I can with some packages disabled (which I can't tie to a specific package) switch the theme to the light one without any problems but when switching back these error messages appear:
![notfound](https://cloud.githubusercontent.com/assets/11966684/9976320/cca0e36a-5ee0-11e5-86ce-9e8ec7ec95d1.PNG)
Sometimes it also already appears when switching to the light theme.

One time it showed me this:
![atom](https://cloud.githubusercontent.com/assets/11966684/9976324/f45a1f7a-5ee0-11e5-9d39-eee7024a7979.PNG)

and the GUI went like this:
![brokentheme](https://cloud.githubusercontent.com/assets/11966684/9976329/2a7cd264-5ee1-11e5-84c1-4e4868cb45c7.PNG)

One time it showed me this:
![errorconsole_switchingbacktodark](https://cloud.githubusercontent.com/assets/11966684/9976333/36f8027a-5ee1-11e5-9069-2b2077f2ca86.PNG)

And it looked like this:
![errorconsole_switchingbacktodark_view](https://cloud.githubusercontent.com/assets/11966684/9976334/3e974946-5ee1-11e5-80a6-b6111d1dd9a4.PNG)

**Comment by rugk** [comment]
Mostly my config (config.js) was retested at the next restart when this error occurred.

Additionally one time it also looked like this:
![errorlist](https://cloud.githubusercontent.com/assets/11966684/9976361/19d2d44e-5ee2-11e5-825b-47cf985245c1.PNG)
(one error it throw was [this](https://gist.github.com/rugk/545aa10e67eb71245509))

**Comment by rugk** [comment]
I also deleted `compile-cache` and `storage`but that did not fixed this problem either.

**Comment by rugk** [comment]
Again these error messages:
![atomthemeswitchingerrormessages](https://cloud.githubusercontent.com/assets/11966684/9979883/87f9bc16-5f83-11e5-8372-f1db3a32a229.PNG)

And while they are shown the config.json is cleaned (0 byte).

**Comment by rugk** [comment]
Okay, so finally trying this on a freshly installed Atom version and it seems this issue is in the core:
![themeissue](https://cloud.githubusercontent.com/assets/11966684/9980348/6fe1abd6-5f95-11e5-9f52-694a8fb1d845.gif)

And here the whole .atom user settings folder before this issue happened:
https://github.com/rugk/assets/blob/master/troubleshooting/atom/8860_themeswitching/atomafter.zip

And afterwards (after the first demonstration in the gif):
https://github.com/rugk/assets/blob/master/troubleshooting/atom/8860_themeswitching/atombefore.zip

**Comment by rugk** [comment]
Now I could also find related issues: https://github.com/atom/atom/issues/8834 and https://github.com/atom/atom/issues/8565

**Comment by 50Wliu** [comment]
Closing in favor of the above issues.
