### ISSUE TITLE
Unable to run Node from Atom in with Script even though it is in PATH

### ISSUE THREAD

**Issue by jasepellerin** [atom/atom#8863]
Hello.

I have installed Script to run code quickly from within Atom. However, it is having trouble running things written with Node. It gives me an error window here:

![capture](https://cloud.githubusercontent.com/assets/9395127/9977808/e9eadea2-5ec8-11e5-92ef-27964977e0e2.PNG)

The path highlighted points to here:

![capture2](https://cloud.githubusercontent.com/assets/9395127/9977811/f4f97934-5ec8-11e5-8e26-21fab64a8dba.PNG)

It seemed to work when I first installed it yesterday, but that quickly became this error. After a lot of pulling my hair out, I bring this issue to you.

Thanks,
Jase

**Comment by peduxe** [comment]
Can you execute this in atom's chrome devtools and paste the output here?

`process.env.PATH`

Did you check if node is present in your system environment variables (PATH)?

**Comment by jasepellerin** [comment]
process.env.PATH
"C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Users\Jase\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Programs\nodejs\;C:\CMake\bin;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5.4 & MySQL Utilities 1.5.4 1.5\Doctrine extensions for PHP\;C:\Programs\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Programs\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Users\Jase\.dnx\bin;C:\Users\Jase\AppData\Local\atom\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Programs\nodejs;C:\Make\bin;C:\Programs\nodejs\node.exe;"

It's in the screenshot above as well.

**Comment by peduxe** [comment]
@jasepellerin Yes but `where node` also important, I don't think there's any error, I tried it in a windows machine and ran about fine. Is there are exception being thrown? Check your console after you get the error.

**Comment by jasepellerin** [comment]
The console doesn't show anything after it happens. There are a few duplicates in the PATH. I'm working on getting that cleaned up.

**Comment by damieng** [comment]
Hi Jase. Did you ever get this working?

**Comment by jasepellerin** [comment]
I still haven't been able to fix it.

**Comment by damieng** [comment]
Can you try opening a command prompt and type 'node --version'

The last part of your path is incorrect - "C:\Programs\nodejs\node.exe" is an executable and not needed but this should be working because the correct c:\Programs\nodejs folder is already specified earlier in your path.

**Comment by damieng** [comment]
No response so closing. Please re-open if you still have this problem.
