### ISSUE TITLE
Packages that add a popup at the bottom of the editor can hide my cursor

### ISSUE THREAD

**Issue by shawninder** [atom/atom#8868]
The simplest way to observe this is to write things near the bottom of a file and trigger `Project Find: Show`. The find form appears at the bottom, hiding the part of the file you're working on. This is not particularly bothersome for `find`, but it's really annoying when the `linter` package, linting on every keystroke, shows errors that hide the part of the file you're working on (making it difficult to fix the linting errors without scrolling down.

Have a look at [this issue](https://github.com/atom-community/linter/issues/895#issuecomment-141793355) for a better description of why this is annoying.

**Comment by mnquintana** [comment]
Thanks for the report! I think this is a duplicate of https://github.com/atom/atom/issues/8068 and https://github.com/atom-community/linter/issues/758 though - please subscribe there for updates.
