### ISSUE TITLE
questions: key shortcut and start

### ISSUE THREAD

**Issue by crperlin** [atom/atom#8869]
1.why key shortcut use webstorm double cilck change…
2.default disable all plugins keyshortcut ，show key exec command at readme，users  control on/off（like checkbox）

3.atom start time very slow （compare for sublime）……next version can reduce start time？

**Comment by 50Wliu** [comment]
Hey there @crperlin!
Your first issue is already being tracked at atom/settings-view#163.
For your second issue, you can now enable/disable all keybindings for a particular package:
![keybindings](https://cloud.githubusercontent.com/assets/2766036/9981892/284de71e-5f98-11e5-841a-40a73a33df0e.png)
And for your third, that's being tracked at #2654 and #3673.

Hopefully that answers your questions!
