### ISSUE TITLE
Atom v1.0.15 keeps freezing/crashing on Windows 10

### ISSUE THREAD

**Issue by SergeUK** [atom/atom#8870]
Hi,

I am new to Atom and I just started to use it with Julia (packages language-julia, julia-client, ink). I have the version 1.0.15 installed on Windows 10. It runs fine a while but it keeps crashing when I run my Julia code always at the same place. I don't know if it is an issue with the packages or with Atom. How can I find out what causes the crash / freeze?

Thanks
Serge

**Comment by Varanas** [comment]
I think it's most likely that the julia packages are at fault here. If you're interested in debugging this, head on over to https://github.com/JunoLab/atom-julia-client/ and open an issue there.

**Comment by 50Wliu** [comment]
Thanks @Varanas.
