### ISSUE TITLE
Running Slow

### ISSUE THREAD

**Issue by felixgeilert** [atom/atom#8872]
Hey,
I am running version 1.0.15 on Windows 10. Currently I have the problem that I have massive performance problems when editing text. I have not installed any new packages and also tried to disable all community packages, however the problem still persists. 
The unresponsiveness occurs very short after starting atom and there is plenty of free memory on my machine if that is any help.
Also this happens especially (but not exclusively) after pasting text. Might be a performance issue with the text rendering (I tried to disable spellcheck, however without any effect)?

**Comment by 50Wliu** [comment]
Hi @felixgeilert, does this still happen in safe mode (`atom --safe`)?  If so, can you please follow the instructions [here](https://atom.io/docs/v1.0.15/hacking-atom-debugging#diagnose-performance-problems-with-the-dev-tools-cpu-profiler)?  Thanks

**Comment by felixgeilert** [comment]
I tried to, however I now have further errors with atom. The settings get reset every time I start the editor and he started to clear the content of tex files from my repository.
As I currently have to finish my thesis and don't have much time, I went with re-installing atom, which works fine for now.

**Comment by 50Wliu** [comment]
Ok, thanks for replying.  If it happens again please comment here!

**Comment by felixgeilert** [comment]
Will do.
