### ISSUE TITLE
Atom not updating some files during rebase

### ISSUE THREAD

**Issue by KingsleyKelly** [atom/atom#8874]
This was a weird one. I was rebasing a series of commits.
Git was telling me there were merge conflicts on the file but I was only seeing them in some files flagged by the rebase.
I continued the rebase several times and saw that merge conflicts were now present in my html on the page when I finished the rebase. I restarted atom and found I had several merges folded on top of each other.

In future I'll have to restart atom if I see that rebased files aren't showing their changes from merges, but it's a really unpleasant bug as I have to restart the rebase now.

After I finished the rebase I went looking for the conflicts by searching for (>>>).
I could find the merge arrows in the search but clicking on them brought me to the file where it wasn't showing the updates. It even said there were merge conflicts on lines that were longer than the length of  the file.

The project is pretty large, so this may be memory based or specific to my machine. If it occurs again I can submit screenshots.

**Comment by FloFra** [comment]
Seems to be related to #8888

**Comment by betesh** [comment]
This happens to me on atom 1.3.2.  #8888 says it's fixed in 1.0.18.
