### ISSUE TITLE
Trouble with acute accent in version 1.09

### ISSUE THREAD

**Issue by ctala** [atom/atom#8877]
Aftter a while of writting in spanish acute accents stop working, so for example if I want to write "ó,á,í" or other characters nothing appears written on the screen.

This issue is being fixed rebooting Atom.

**Comment by mnquintana** [comment]
Can you reproduce this in the latest version of Atom? (1.0.15)

**Comment by chagara** [comment]
helo,

I'm able to write letters with accent as described in this ticket but, when using the search function it does not work. Even with the accent or not the search feature cannot find it. IT should be able to get close to the word at least if put most of the word at least. EX. configuración if I search for configu or the whole word the search does not work.

**Comment by chagara** [comment]
never mind the last comment. It works now :) you can write with accents and search for words that have it.

**Comment by mnquintana** [comment]
Great to hear @chagara!

I'm going to close this out – @ctala feel free to comment if you run into this again!
