### ISSUE TITLE
Atom fails to build with runas version 2 as dependency

### ISSUE THREAD

**Issue by DuckThom** [atom/atom#8878]
When building Atom on Arch Linux, it fails with the following error.
https://gist.github.com/DuckThom/82e71087339f67cf2335

When changing `"runas": "^2",` to `"runas": "^3",` in `build/packages.json:36` the build continues and finishes successfully.

**Comment by vdemin** [comment]
Confirm, an error occured when trying to run `npm install runas@2.0.0`,
node v4.1.0
npm  v3.3.3

**Comment by 50Wliu** [comment]
Atom currently cannot be built on Node 4/io.js 3 - please revert to Node 0.10/0.12 or io.js 1/2 as documented in the [build instructions](https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#requirements).  A tracking issue is located at #8508 and will be fixed by #8779.
