### ISSUE TITLE
Markdown breaks code folding in Literate CoffeeScript

### ISSUE THREAD

**Issue by vijithassar** [atom/atom#8879]
Atom supports [Literate Coffeescript](http://coffeescript.org/#literate), but the code folding breaks when presented with Markdown content, which is the entire point of Literate Coffeescript. A function which contains Markdown text will not fold correctly; the Markdown and anything following is considered immune to the fold.

![code-folding-bug](https://cloud.githubusercontent.com/assets/3488572/9997786/0ff2ee48-605c-11e5-8ff6-c33ffdf6db17.png)

**Comment by benogle** [comment]
Can you outline exactly what you expect? Atom's folding is indentation based.

**Comment by vijithassar** [comment]
Literate CoffeeScript's annotations in Markdown are also indentation based; [per the Markdown syntax](http://daringfireball.net/projects/markdown/syntax#code), code blocks meant for the compiler are demarcated by two tabs, and everything else is a rich annotation. I'd expect Atom to fold according to functions and code and application structure, and treat the Markdown annotations as affiliated with their enclosing functions. Currently, writing any Markdown content breaks all folding capabilities – in other words, in terms of the folding behavior, an annotation or comment is akin to starting a new function at the outermost scope, which prohibits commenting inside functions or deeper scopes.

**Comment by vijithassar** [comment]
Looks like it's possible to [specify folding behavior in the language config files for Sublime Text](https://gist.github.com/pateketrueke/6818164). (Also, it just occurred to me that this seems like a very illogical bug since Atom is itself written in CoffeeScript!)

**Comment by vijithassar** [comment]
Any updates on this bug yet?
