### ISSUE TITLE
atom showing old versions of files

### ISSUE THREAD

**Issue by ChrisJefferson** [atom/atom#8888]
I have atom set up as my editor for git using `atom --wait --safe` (I added the safe today, this bug still appears).

When I make a commit, atom opens an old version of `COMMIT_EDITMSG`, from a week ago. If I go into the .git directory and do `cat COMMIT_EDITMSG`, I see the new copy. I can't figure out where atom is even getting these old file contents from.

**Comment by mnquintana** [comment]
Can you try removing Atom's storage directory and seeing if you can still reproduce this? (`rm -rf ~/.atom/storage`)

**Comment by ChrisJefferson** [comment]
I can't reproduce it any more now.

This was / is still a really terrible bug -- I badly messed up a git rebase -i, as an old rebase file was loaded and I lost some commits (well, I get them back with pain).

**Comment by rasselbock** [comment]
I'm using 1.0.15. Opening a html file to edit, I just got an older version of the file. It had diff marks like it might be diffing against the new file version that I just pulled. Clearing the storage (rm -rf ~/.atom/storage) then restarting Atom set everything back right.

**Comment by FloFra** [comment]
Just had the same problem and lost 3 hours of work by saving before noticing something was off.

Other tabs that I did not "save" would properly display the files content once I closed and reopened them.

I am on the newest version (1.0.15) and on Windows 7.

**Comment by 50Wliu** [comment]
@rasselbock, @ChrisJefferson: What OSes are you on?

**Comment by rasselbock** [comment]
@50Wliu Oops, should have said. OSX 10.10.5 Yosemite; Git 2.2.0

**Comment by ChrisJefferson** [comment]
10.11.0 GM; git 2.5.3

**Comment by ChrisJefferson** [comment]
This could be related to a (for me) repeatable data-loss bug I am having, #8581

**Comment by maxbrunsfeld** [comment]
Hey all, just want to let you know that I think this is really serious, and I'm really sorry this is happening to you, and I'm looking into it. I haven't been able to reproduce this bug yet, but I'm looking into it. It's also possible that it's already been fixed by some dependency upgrades on master, and will be fixed in the next release. Anyway, I'm looking into it and I'll keep you posted.

**Comment by maxbrunsfeld** [comment]
Can everyone check if this still happens after doing this?

1. Close Atom
2. `rm -rf ~/.atom/storage`
3. Open Atom

**Comment by ChrisJefferson** [comment]
I have tried hard to cause this bug to re-occur after clearing storage, and it isn't coming back.

I should have made a copy of the directory before I deleted it! It did have a large number (> 100) files in it.

**Comment by maxbrunsfeld** [comment]
Ok, let me know if you see any more problems, or find out any new information @ChrisJefferson. I was finally able to reproduce a related problem (https://github.com/atom/atom/issues/8849) by going back to an earlier version of Atom and then upgrading. Clearing the `storage` directory seems to have fixed the problem. I'm trying to think now what caused the invalid state to be stored, and if this can be prevented without requiring people to nuke that `storage` directory.

**Comment by rasselbock** [comment]
@maxbrunsfeld Thanks for the updates!
@ChrisJefferson Did Time Machine do a backup for you?

**Comment by maxbrunsfeld** [comment]
Ok, I just released Atom 1.0.18. I believe it should fix this issue, if removing the `~/.atom/storage` directory did not already fix it. Everyone, please let me know if you're still experiencing this on 1.0.18.

**Comment by glebcha** [comment]
Today faced this terrible bug. Did recursive Atom's shit deletion to keep thing s fine.
Hope you'll really fix this bug.

**Comment by ShaunYudin** [comment]
Worst bug of all time! Just lost hours of work :''(

**Comment by lowstz** [comment]
I have same problem on the version 1.8.0

**Comment by glebcha** [comment]
Same shit again.

**Comment by mvdobrinin** [comment]
Running into same issue on version 1.9.2.

**Comment by voylinux** [comment]
Same here in 1.10.2

**Comment by maxbrunsfeld** [comment]
Anyone who is experiencing this on Atom 1.10. Could you open a new issue and provide as detailed of reproduction steps as possible?

**Comment by jacekkowalczyk82** [comment]
All, I experienced it on atom 1.13.1 at windows (I had this also on Ubuntu some time ago). 
Atom editor was showing old content of some file, and I was surprised as I was remember I was editing it with some other editor.   It does not happen every time.

**Comment by BenjaminDalziel** [comment]
Hi all, I encountered what appears to be this issue in Atom 1.19.1, running on OS X El Capitan version 10.11.6.

**Comment by Justin-Mitchell** [comment]
Experiencing same issue...  When launching Atom from my work directory it opens with 10 Tabs of files.  All files being past versions of themselves from what is currently in the repository. Not even recent versions, 3 month old versions.  Accidentally deployed these old files costing me hours of debugging and work.  Unfortunately I don't think I can continue to use this Editor unless a solution is provided.

Fully deleted app and rm -rf ~/.atom, did reinstall and problem still exists.

**Comment by droiddk** [comment]
Experiencing same issue.
The is the absolute WORST thing an editor can do.  
I don't feel safe using this editor any more.

**Comment by abepetrillo** [comment]
@maxbrunsfeld The work around of `rm -rf ~/.atom/storage` seems to fix the problem temporarily.

**Comment by sosey** [comment]
I have the same issue on osx sierra, with:
Atom    : 1.19.7
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

It appeared after I deleted  a local repository and then cloned it back to the same directory. 
Following the fixes above doesn't help

**Comment by BenjaminDalziel** [comment]
The work around of closing atom, then rm -rf ~/.atom/storage seemed to fix the problem for me as well.

**Comment by shevegen** [comment]
Atom probably needs to check more on old files/directories there.

**Comment by ungb** [comment]
I'm currently trying to get a repro for this.  Very sorry for those that ran into this issue.    Is everyone here using Windows?  Would be useful to provide which OS you're using as well.  I tried to repro on Mac and couldn't I'll try on windows.  

Also, when Atom opens the old file, is it dirty(unsaved changes)?  If you close the tab and reopen it does it open a older version still?

**Comment by BenjaminDalziel** [comment]
At least a few of us are on Mac. When the issue occurred for me, I was getting the same old version of the file each time I started Atom. I would use File->Open and select the same-named file to get the correct version. I would work on it, save changes, and close. Next time, same old version as before.

**Comment by ungb** [comment]
thanks @BenjaminDalziel interesting... When the old file opens up is it in dirty(unsaved state)?

![image](https://user-images.githubusercontent.com/5624870/30358423-4efa6afe-97f9-11e7-9f5e-c99d55f34bd3.png)

**Comment by sosey** [comment]
I get dirty files on open. Even after completely uninstalling atom and reinstalling, when I ask to open a specific file in a repo that is clean (using cmdline),  with no changes, it opens multiple tabs with a mix of clean and dirty files. I have the same issue when rebasing, when a file I was working on, and saved, is being rebased and I open in atom to resolve conflicts, the old version shows up.

**Comment by BenjaminDalziel** [comment]
Sorry @ungb, I can't remember if the files were dirty when they appeared in my case.

**Comment by ungb** [comment]
@sosey a few comments above people mentioned that `rm -rf ~/.atom/storage` and restarting atom might fix the issue.  

If you are still seeing the issue.   can you try to do the following:(moving instead of deleting)
```
mv ~/.atom/storage ~/.atom/temp_storage
``` 
Restart atom and see if it fixes the issue for you?  

If this fixes the issue, is it possible for you to share what's inside of `.atom/temp_storage`?  In mine I just see a file `application.json` that has `initialPaths`.   


This can help us narrow down the issue.

**Comment by sosey** [comment]
I did try removing storage before removing atom entirely, after closing atom, and before, and  it had no effect. Even with the issue, there was nothing in  ~/.atom/storage whenever I looked.

**Comment by sosey** [comment]
To remove the atom application from everywhere, I deleted it from `/Applications`, the whole `.atom/` directory,  `/usr/local/bin/atom`, ` /usr/local/bin/apm` and `~/Library/Preferences/com.github.atom.plist `

Is there anywhere else that a buffer might be stored in a local working directory that I missed? After re-installing the app and opening a repo file, I still had the same issues. The new install was started with --safe and I had no extra packages installed. I feel like this might have something to do with the repo tracking, or however atom is using information in `.git/`. I'm not currently getting  this issue when I use my fresh `atom` and look at other repositories elsewhere on disk. I consistently get it in the repo that I first deleted and then cloned again in the same disk location. The fresh clone had quite a few commits squashed, and the files atom displayed were from a really old commit that had been squashed before I re-cloned the repo.

**Comment by p-ugulino** [comment]
It just happened to me. Lost 3 files. :(

**Comment by maxbrunsfeld** [comment]
It seems like a lot of people are reporting a lot of subtly different problems on this issue. When reporting that this happened to you, please report in detail, step by step, exactly what you saw. One very relevant piece of information is whether the file showed up as 'modified' (blue dot on the tab) when you reopened Atom.

**Comment by p-ugulino** [comment]
Hey @maxbrunsfeld sorry. So, I closed atom yesterday and today when I opened, I noticed the blue dots on the tabs and started saving all the files (I thought I forgot to save yesterday). Then, I put my react native project to run and a lot of my functions were not working. After checking the files, I realized they were all old files. Tried to delete the atom "store" folder but still, the old files persist. 
Now I just accepted the fact that I'll have to waste some time recoding stuff

**Comment by ungb** [comment]
Another thing to try is `atom --clear-window-state`.  This will clear all the saved project states, but unsure how someone gets into this state.

**Comment by joeguinness** [comment]
I just had this happen a couple of days ago, using Atom 1.21.0. I opened a file I had been working on a few weeks ago. When I opened it, the pale blue dot appeared at the top (even though I always save), I reflexively hit save, then I noticed that the file was an older version. I don't see any way to get back the work that was lost. I checked the ~/.atom/storage directory last night, and the only file in there was application.json.

**Comment by Ben3eeE** [comment]
@ungb Let's chat about this today I have some ideas

**Comment by ungb** [comment]
@joeguinness Do you know if there's been a few Atom upgrades?  Wondering if something happened between Atom upgrades and not opening the file for a while between upgrades.  

I'm currently trying to find a repro for this issue, but haven't been able to track down the root cause.

**Comment by joeguinness** [comment]
There may have been, but I don't know for sure. I hadn't worked on the file in a few weeks.
By the way, Atom is otherwise great. I plan to keep using it (and commit more often, which I should be doing anyway!).

**Comment by Ben3eeE** [comment]
We have investigated this and found one case where it can happen in https://github.com/atom/atom/issues/16081. I am going to close this issue out as fixed by https://github.com/atom/text-buffer/pull/283.

The fix for this is currently scheduled to be released in Atom 1.25. If you run into this issue in Atom 1.25 or later then please open a new issue and provide as much details as possible.
