### ISSUE TITLE
Editor zooms on tap

### ISSUE THREAD

**Issue by gustavpursche** [atom/atom#8890]
Not sure if this a new issue, or if I'm just uncoordinated today: When tapping in the middle of Apples Magic Mouse, the editor zooms in. After the interface is still scrollable. If you tap again, it zooms out again.

I think the interface should'nt be zoomable that way - only the size of the font.

OSX: 10.11
Atom: 1.0.15

Screenrecording:
![atom-ui-regression-tap](https://cloud.githubusercontent.com/assets/2244375/10017529/7dc87bee-612f-11e5-980e-10db55858077.gif)

**Comment by mnquintana** [comment]
Thanks for the report! I think this is the same underlying issue as https://github.com/atom/atom/issues/8850 - I'm gonna close this out in favor of that issue. Would you mind adding your comments here as a comment on that issue?
