### ISSUE TITLE
Opens way too slow on windows

### ISSUE THREAD

**Issue by AakashRaina** [atom/atom#8902]

**Comment by daftpanda** [comment]
Hi @AakashRaina,
can you give them more informations? HDD or SSD using?

I'm using Win7 Ultimate 64 Bit with the latest atom release (1.0.15) and the starting takes the following:

![image](https://cloud.githubusercontent.com/assets/14540591/10039621/4b78d080-61d4-11e5-974c-736762b7cf3e.png)

And to be honest - for me it's fast enough :)

**Comment by AakashRaina** [comment]
@daftpanda 
I'm using win 8 64-bit,HDD.
Atom version 0.150.0
Here's the Timecope:
![screenshot 114](https://cloud.githubusercontent.com/assets/8619310/10042982/e42c82b2-620c-11e5-9ee6-16a0f0079a3a.png)

**Comment by Zireael07** [comment]
@AakashRaina: Update your Atom. 0.150.0 is... waaaaaaaaay old.

**Comment by daftpanda** [comment]
^ that would've been my first advice @AakashRaina, thank you @Zireael07  :)

**Comment by AakashRaina** [comment]
ok,cool
Thanks @daftpanda @Zireael07

**Comment by daftpanda** [comment]
Please let us know if updating atom to the latest version solved your problem :)

**Comment by mnquintana** [comment]
Since you're using a very old version of Atom, I'm going to close this out - if you still experience slow load times, then feel free to subscribe to https://github.com/atom/atom/issues/2654.
