### ISSUE TITLE
Atom downgrades newer versions than aren't on it's servers

### ISSUE THREAD

**Issue by enilsen16** [atom/atom#8911]
I installed v1.0.16 via Github and once I opened atom, it treated v1.0.15 as the latest. I would expect that if I have a newer version than what's on the atom update servers that it would treat that version as the latest.

![screen shot 2015-09-23 at 10 43 28 am](https://cloud.githubusercontent.com/assets/5035876/10053367/76e06c4a-61e0-11e5-9d14-42c67d27bafd.png)

**Comment by maxbrunsfeld** [comment]
So are you sure it actually downgraded your app, or is it just showing the wrong release notes? Can you click `Restart and Install Update`, reopen Atom, and run this in the console?

```js
atom.getVersion()
```

**Comment by enilsen16** [comment]
It did downgrade atom, however I have already gone through this process and am using the latest version. I guess I could try manually updating my version and then running auto updater...

**Comment by enilsen16** [comment]
@maxbrunsfeld I just updated to the latest beta(using atoms updater) and these are the release notes that I was given -

I haven't been able to reproduce my initial issue. However Atom does still show incorrect release notes for versions and will let you click `Restart and Install Update` if your version does not match the newest on the release notes.

![screen_shot_2015-10-29_at_4_18_32_pm](https://cloud.githubusercontent.com/assets/5035876/10834722/027c14ae-7e59-11e5-9a32-876bddb20be7.png)

**Comment by enilsen16** [comment]
Here's another example -

I upgraded to 1.2.0 beta1 from the website before it was on the servers -
![screen shot 2015-11-04 at 12 52 17 pm](https://cloud.githubusercontent.com/assets/5035876/10951564/11044200-82f3-11e5-9bc6-d5b00754aeb8.png)

After atom prompted me to upgrade, I was downgraded back to 1.2.0.beta0 -
![screen shot 2015-11-04 at 12 52 48 pm](https://cloud.githubusercontent.com/assets/5035876/10951565/11070792-82f3-11e5-8bba-334b6daabedf.png)
```
atom.getVersion()
"1.2.0-beta0"
```

**Comment by enilsen16** [comment]
I haven't seen this happen in awhile. Closing
