### ISSUE TITLE
After Updating to 1.0.15, Won't Update Packages

### ISSUE THREAD

**Issue by ghost** [atom/atom#8912]
Fetching outdated packages and themes failed.Hide output…
Request for package information failed: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>

**Comment by ainstushar** [comment]
Currently on 1.0.16 and this just happened to me.

````
Fetching outdated packages and themes failed.Hide output…
Request for package information failed: <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
````

**Comment by thomasjo** [comment]
These types of errors are caused by service outages in the package infrastructure. Please open such issues on the [atom.io repo](https://github.com/atom/atom.io). Thanks!
