### ISSUE TITLE
Atom Helper uses 100% CPU, stuck in readableAddChunk?

### ISSUE THREAD

**Issue by LegNeato** [atom/atom#8914]
Atom is basically unusable for me because Atom Helper uses 100% CPU and the whole editor is unresponsive. Even exiting Atom tells me the editor is unresponsive and asks if I want to wait or close.

**Reproduces 100% for me and with `atom --safe` as well**. Also tried blowing away `~/.atom` and it didn't fix it. Core i7 iMac, 10.10.5. Latest released Atom.

Here is the .cpuprofile from developer tools:

http://pastebin.com/sPx4y5TM

To my untrained eye it looks like it is trying to download something and is in some tight busy-loop trying to emit status events.

And here is the sample of Atom Helper:

http://pastebin.com/MpWYNd7G

Happy to do anything I can to help debug.

**Comment by mnquintana** [comment]
This looks like a duplicate of https://github.com/atom/atom/issues/3426 - closing this out in favor of that issue. Would you mind posting your comments here as a comment on that issue? Thanks!
