### ISSUE TITLE
Add a parameter for silent / quiet / unattended install for Windows installer

### ISSUE THREAD

**Issue by dogancelik** [atom/atom#8915]
Right now when installing, you can't pass any parameters like these:

`/?`, `/S`, `/Q`, `/silent`, `/quiet`

I don't want to see a GUI that says it's installing or don't want it to open Atom after setup has finished installing.

**Comment by 50Wliu** [comment]
Did you try `--silent`?  That should suppress the GIF, but I think Atom will still start after being installed.

**Comment by dogancelik** [comment]
`--silent` works and Atom didn't start but someone should verify this. And I believe the setup file parameters should follow Windows convention and use `slash + parameter name`.

There is no `--help` or `/?` to tell you what commands or options it supports. When you do `--help`, it starts install as usual.

**Comment by 50Wliu** [comment]
In that case, you'll probably want to move this upstream to [Squirrel/Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) and cc @paulcbetts.
