### ISSUE TITLE
Custom Gutter component does not accept space in class list

### ISSUE THREAD

**Issue by steelbrain** [atom/atom#8920]
In linter, we need to provide a base class `linter-highlight` along with the error type as the class. Not being able to have a space in class pretty much cripples the abilities, furthermore, we are allowed spaces in classes in highlight markers so I believe it's an inconsistency.
I am talking about `custom-gutter-component` on lines https://github.com/atom/atom/blob/master/src/custom-gutter-component.coffee#L84-L88
cc @nathansobo

**Comment by steelbrain** [comment]
Side Question: Until that's fixed in atom and for backward compatibility, is there a way to get a decoration element directly? so we can patch it from our package.

**Comment by steelbrain** [comment]
Some investigation found me this, but it's super-super hacky :(
```
atom.views.getView(this.editor).component.gutterContainerComponent.gutterComponentsByGutterName['linter']
```

**Comment by steelbrain** [comment]
I've taken an alternative route now, I am assigning line numbers to decorations, then searching for elements with that class in the gutter view that I get with `atom.views.getView` and then add the classes there

**Comment by steelbrain** [comment]
so I just found out that the `item` attribute works with the custom gutter decorations as well, which is not mentioned at https://atom.io/docs/api/v1.0.15/Gutter#instance-decorateMarker
and that missing caused me more than an hour of debugging :(

**Comment by ssorallen** [comment]
The options are passed through to [`TextEditor::decorateMarker`](https://atom.io/docs/api/v1.0.15/TextEditor#instance-decorateMarker), which has more complete documentation. Maybe `Gutter::decorateMarker` should just link there and remove its duplicate docs.

**Comment by steelbrain** [comment]
@ssorallen Here's my :+1: on that

**Comment by ssorallen** [comment]
@steelbrain, where did you find `item` could be passed as an option? That doesn't seem to be documented anywhere.

**Comment by steelbrain** [comment]
@ssorallen Well guess what? It isn't even documented clearly!
The closest thing you get is a hint from the [`decorationParams::type->overlay`](https://atom.io/docs/api/v1.0.17/TextEditor#instance-decorateMarker) in the docs where it says

> Positions the view associated with the given __item__ at the head or tail of the given marker, depending on the position property

**Comment by ssorallen** [comment]
Oof. Well this should still be a helpful change to centralize the docs for `decorationParams`: https://github.com/atom/atom/pull/8931

**Comment by nathansobo** [comment]
@steelbrain do you still want to keep this open?

**Comment by steelbrain** [comment]
The bug still remains :)
