### ISSUE TITLE
Settings -> Packages -> Deprecated Packages never loads

### ISSUE THREAD

**Issue by mackelito** [atom/atom#8924]
- When going to this settings page it never loads..
- Number of installed packages is "..." on all packages groups
- Community Packages only shows one packages (todo-manager)
- Core Packages show all

some config file that is wrongly formated?

**Comment by 50Wliu** [comment]
Can you please move this to [atom/settings-view](https://github.com/atom/settings-view)?

For future reference on where to create issues, this guide might help: https://discuss.atom.io/t/id-like-to-report-an-issue-request-an-enhancement-for-atom-where-on-github-do-i-do-that/19290
