### ISSUE TITLE
Backup / Installable setup of atom

### ISSUE THREAD

**Issue by mackelito** [atom/atom#8925]
Would really love to have a single file that when imported/added somehow, atom will install the plugins specified... much like a spm/bower install :)

**Comment by mnquintana** [comment]
You can do that now! To export your current packages (on Mac & Linux):

```
apm list --installed --no-dev --bare > packages.txt
```

To install packages:

```
apm install --packages-file=path/to/packages.txt
```

Does that cover what you're looking for?

**Comment by mackelito** [comment]
Looks very promising! Does that also save my settings?
Or if I install a fresh atom, run the install packages.txt, will I still need to do config? (themes, settings etc)

**Comment by abe33** [comment]
For your setttings you can already copy/paste the `config.cson` file in your `.atom` directory.

**Comment by mackelito** [comment]
It would be great if this was done automatically.. Why? Because I often switch computers and it would be awesome to keep them in sync.

Perhaps if I could just have the packages and config in dropbox or similar and when booting up Atom just use them :) 👍

**Comment by damieng** [comment]
You could set ATOM_HOME to point to a folder within dropbox?

**Comment by mackelito** [comment]
Actually I found the plugin sync-settings that uses git gists to sync.. works like a charm! 👍
