### ISSUE TITLE
Find/Replace drawer doesn't close

### ISSUE THREAD

**Issue by rceee** [atom/atom#8932]
On 1.0.12 (OS X) now after opening the Find/Replace drawer/sub-window, it does not close with the Esc button, nor does right-click and Close Pane work.  

It usually only closes after closing an open tab.

**Comment by 50Wliu** [comment]
I can't reproduce this on Atom 1.0.18, Windows 10.  Can you please try updating to Atom 1.0.18 and see if that fixes it?  If not, does running Atom in safe mode (`atom --safe`) help?

**Comment by 50Wliu** [comment]
This issue was moved to atom/find-and-replace#538
