### ISSUE TITLE
Stop adding project folders to the window

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#8934]
This is my single most painful papercut with Atom. Every time I open Atom with, e.g. `atom ~/.wine/system.reg`, Atom adds the WHOLE FOLDER (e.g. `.wine`) to the window, which blows up my memory and CPU and pollutes my search with millions of files I'm not interested in. I almost never want Atom to add and index the folder of the file I'm editing.

**Comment by dnl** [comment]
the same for when I want to edit e.g. ~/.bash_profile or ~/.gitconfig, hello whole home directory.

What I expect should happen is 
1. when I open a folder/directory, then I see the tree and can search project etc. (as current) 
2. When I open a single file I should just be able to edit that file, and not have to have the overhead of having it's containing folder indexed.

**Comment by fl0at** [comment]
I agree, this is a really weird behavior. Especially coupled with restoring sessions.

I don't want `~/.ssh` or whatever to be a project folder, unless I explicitly add it! It's also a waste of screen real-estate, having to close the Tree View every time I open the app... :/

**Comment by halilim** [comment]
I was actually expecting even a higher number of complaints regarding this, since this is not common among other editors. In my experience, too, opening a file opens just the file. And the difficulty of removing the project folder from the tree (you can't assign a shortcut for it, you have to right-click and select the action!) adds insult to injury for me...

**Comment by midwire** [comment]
I love the idea of Atom, as the hackable editor. However, this single issue has me running back to Sublime Text. I'm subscribing here to hopefully discover when, if ever, it gets fixed.

**Comment by matanui159** [comment]
Has anything changed? This one thing is bugging me a lot.

**Comment by midwire** [comment]
> Has anything changed? This one thing is bugging me a lot.

Not that I know of. I switched back to Sublime about a year ago because of this issue so I'm unaware of any fixes or changes. Hopefully, someday...

**Comment by Ben3eeE** [comment]
Thanks for reaching out!

Improving the launch story of Atom to address problems like this is something that we are tracking in https://github.com/atom/atom/issues/10517. You may want to subscribe there for updates.
