### ISSUE TITLE
private config type

### ISSUE THREAD

**Issue by zephraph** [atom/atom#8935]
There should be a setting in the configuration api to make a config item _private_. With this flag activated when generating an automated bug report it won't print out any _private_ config keys. Specifically if the config api is being used to store api keys a user could accidentally report a bug that reveals their api key.

**Comment by benogle** [comment]
For now, is there a way you can get them to put it in localStorage? You could prompt for the token, then put it in localStorage.

**Comment by zephraph** [comment]
There's an idea. The aforementioned issue actually happen [here](https://github.com/zephraph/atom-github-notifications/issues/1).

Are there still issues with localStorage persisting? I know that was an issue a while back.

**Comment by benogle** [comment]
I don't think there are issues with it persisting (we use it for metrics). Give it a shot, and if you have issues, don't hesitate to open a new one.

**Comment by zephraph** [comment]
Sounds good.
