### ISSUE TITLE
Atom 1.0.18 flashing window on Ubuntu 14.04

### ISSUE THREAD

**Issue by FlyingPumba** [atom/atom#8936]
Hi,

I just updated from Atom 1.0.15 to 1.0.18, and now it's completely unusable.
The atom window "flashes", showing the editor for one sec, and then showing the desktop wallpaper, and again.

FWIW, the same happens if Atom is run with the ```safe``` option.
Any idea ?

**Comment by maxbrunsfeld** [comment]
Oh no! Trying to reproduce on Ubuntu right now...

**Comment by Tribex** [comment]
Testing on 15.04, give me a minute or two.

**Comment by maxbrunsfeld** [comment]
Ok, I just installed the `deb` for 1.0.18 on Ubuntu 14.04, and I'm not seeing any problems yet.

**Comment by maxbrunsfeld** [comment]
@FlyingPumba does the problem persist if you restart Atom, reboot your machine, etc?

**Comment by Tribex** [comment]
@FlyingPumba Not having any trouble here on 15.04 either. Can you run it from the command line?

**Comment by FlyingPumba** [comment]
@maxbrunsfeld restarting Atom did not solve the problem, I will try rebooting my machine now.
@Tribex I always run it from command line.

**Comment by FlyingPumba** [comment]
Glad to inform that problem is gone after reboot. I don't know what could be causing it the first time.
@maxbrunsfeld feel free to close this issue, I'll re-open if happens again.

**Comment by maxbrunsfeld** [comment]
Thanks for the update @FlyingPumba!
