### ISSUE TITLE
Error running LOVE.

### ISSUE THREAD

**Issue by jayce-leathers** [atom/atom#8937]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.18
**System**: Mac OS X 10.10.5
**Thrown From**: Atom Core

### Stack Trace

Error running LOVE.

```
At 

undefined
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "latexer",
      "linter-chktex",
      "latex-completions",
      "vim-mode",
      "ever-notedown"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-glsl, v0.2.3
color-picker, v2.0.9
hyperclick, v0.0.32
language-glsl, v2.0.1
language-latex, v0.6.1
language-lua, v0.9.4
latex, v0.25.1
linter, v1.5.0
love-ide, v0.4.0
merge-conflicts, vundefined
pdf-view, v0.23.0
tool-bar, v0.1.8
travis-ci-status, v0.15.1

# Dev
No dev packages
```

**Comment by benogle** [comment]
> Error running LOVE

I feel like there's a lot of people who might identify with this.

**Comment by benogle** [comment]
Does this happen all the time? One time thing? What were you doing? Might be related to some LOVE package.

**Comment by 50Wliu** [comment]
> Might be related to some LOVE package

Going to take a wild stab at this and guess that `love-ide` is causing it :P.

**Comment by benogle** [comment]
Obv I should have looked at the package list

**Comment by jayce-leathers** [comment]
haha sorry just clicked through and didn't have time to write a real bug
report. The problem that caused that was the I had to explicitly set the
pass to the love file "Applications/love.app/Contents/MacOS/love" once I
did that I no longer get that error. But instead get the love bluescreen
and an error that it can't find any valid code. I'm editing a main.lua file
that runs from sublime and from the cli.

**Comment by 50Wliu** [comment]
In that case, can you please report this to https://github.com/rameshvarun/love-ide/issues?  Thanks.
