### ISSUE TITLE
Accept tags files that use line number, not just complete line search

### ISSUE THREAD

**Issue by wolftune** [atom/atom#8938]
See https://github.com/elaforge/fast-tags/issues/19

Whereas Vim will accept tags files that just have a number in the command (jump to definition means go to the given line number), Atom *only* accepts the text string of the complete line for a search. This means less flexibility in working with various tools that create tags files.

Atom should be updated to accept the line number approach. Incidentally, Atom *does* work with such files to at least search by tag and go to the right file, but it totally fails to jump to definitions under the cursor when the tags file uses just line numbers rather than full text.

**Comment by 50Wliu** [comment]
Is this a duplicate of atom/symbols-view#92?

**Comment by wolftune** [comment]
Yes, this is a duplicate of https://github.com/atom/symbols-view/issues/92
