### ISSUE TITLE
Make it easier to add top/bottom bars

### ISSUE THREAD

**Issue by simurai** [atom/atom#8939]
From this discussion: https://discuss.atom.io/t/placing-element-at-top-of-atom-for-package/21118

#### Problem:

Currently you can't easily add a bar to the top or bottom that spans across the whole width. If you try, it pushes down the status bar. I guess because `atom-workspace-axis` has `height: 100%`.

![screen shot 2015-09-25 at 3 22 20 pm](https://cloud.githubusercontent.com/assets/378023/10094309/40c5935a-6399-11e5-92df-bc56f4986499.png)

An option is to add it above/below the editor, like `tool-bar` currently does, but that might not be desired for all packages.

#### Possible solution:

Add two empty `<atom-panel-container>` as children of `<atom-workspace>`. They're just placeholders and won't take up space if they are empty, but it would allow other packages to fill them.

![atom-panels](https://cloud.githubusercontent.com/assets/378023/10159023/c0848db4-66d0-11e5-9cbe-fadbfa2bd110.png)

**Comment by pradyunsg** [comment]
:eyes:

**Comment by simurai** [comment]
After trying it out I think I'm gonna close this again as `wontfix`. Here the reasoning:

1. If we move the status-bar to take up full-width, like:

![screen shot 2015-10-03 at 10 20 49 am](https://cloud.githubusercontent.com/assets/378023/10260897/799a545e-69bb-11e5-9f63-0c756a11f1e2.png)

It feels weird, because the status-bar changes based on to the active editor and should stay somewhat connected and not something that is global.

2. If we encourage other packages to take up full width, like the tool-bar:

![screen shot 2015-10-03 at 10 17 26 am](https://cloud.githubusercontent.com/assets/378023/10260905/9c0dab9e-69bb-11e5-9e15-705a157c4eaf.png)

It also feels weird because the status-bar should stay as the last thing at the bottom.

**Comment by jerone** [comment]
I disagree about that the status-bar should be connected (same width) to the editor. The status-bar can contain tiles that aren't necessary related to the editor. Besides, if I split the screen it doesn't split the status-bar too. Making the [status-bar to the full width](https://github.com/atom/status-bar/issues/91) has my preference.
I do agree that the status-bar should always stay as last thing at the bottom, but with priorities we can force that.

Personally I have the tool-bar positioned at the top, like any other (Windows) desktop program has placed their (customizable) toolbars. To this day I find it weird that it's beside the tree-view and not above it, while it contains buttons that are related to the tree-view and not the editor only.
I still believe this should be implemented as another API function, so packages can position their bars/panels like they want (as the first post suggests).

**Comment by simurai** [comment]
> Besides, if I split the screen it doesn't split the status-bar too.

True. Ok, we can reopen it and at least make it technically possible.

**Comment by jerone** [comment]
The [panels API](https://atom.io/docs/api/v1.1.0-beta.0/Workspace#section-Panels) could be extended by adding another boolean property (e.g. `fullWidth`) to the existing methods `addBottomPanel`, `addLeftPanel`, `addRightPanel` & `addTopPanel`. Or add new methods, e.g. `addFullBottomPanel`, `addFullLeftPanel`, `addFullRightPanel` & `addFullTopPanel`.

**Comment by Zeioth** [comment]
I'm the author of the theme "atom-visual-studio-code-ui" and I'm running into this issue too trying to modify status bar width.

**Comment by pradyunsg** [comment]
+1 for optional parameter in the same method.

Moreover, other than the bottom, there's the top. I would like to hide the menu bar and use the tool-bar instead as it gives me more control over what's there (and thus quicker access to stuff I use often) and I can use the menu bar with <kbd>alt</kbd> any time I want anyway.

Except that the toolbar should really be over the sidebar as well as it is then an application wide thing...
