### ISSUE TITLE
need a md5sum hash value of release packages

### ISSUE THREAD

**Issue by catscarlet** [atom/atom#8940]
I downloaded AtomSetup.exe(1.0.18) . After a while I forgot I downloaded ,so I downloaded AtomSetup.exe(1.0.18) again .
Now I have to setup_packages in my download_folder, but I find they don't have the same size .I use HashMyFiles to checksum them ,and ,of course , they don't match to each other.
I don't know why they are different .I think there may be some network problems .

But I cann't verify which package is the right package, I think there should be a hash value list of release packages .Just like centos.org  ,they provide a md5sum.txt to tell the md5 of the iso files.

There is already a RELEASES ,but it only about the nupkg files, and is that SHA1 or what ?

Some days ago a malware called 'xcodeghost' cames out .XcodeGhost is a compiler malware in OS X. Its malicious code is located in a Mach-O object file that was repackaged into some versions of Xcode installers. I'm afraid there may be someone do the same to Atom in the future .

So I think there should be a md5sum.txt or something like that in the page of releases page for users to verify the setup_files.

**Comment by catscarlet** [comment]
the file I downloaded:
![snap018](https://cloud.githubusercontent.com/assets/10594035/10094475/e348572c-6392-11e5-949f-583c8ddebce9.png)

sorry about my English

**Comment by 50Wliu** [comment]
There were two releases yesterday within three hours of each other - are you sure you downloaded 1.0.18 both times?

**Comment by catscarlet** [comment]
Yes ,I first time finished downloading at 11:46(GMT+8) , and then downloaded again and finished at 12:44 (GMT+8).
I think no matter what I have downloaded , there should be a method to verify my downloaded file because of the bad networking .
It is better providing a list of hash value about the package on the release page . It seems there is already a SHA1 for nupkg .I think there should be something more about EXE for windows users

**Comment by damieng** [comment]
The version details are embedded in the exe and are easily visible from the details tab.
