### ISSUE TITLE
tree-view package settings should be more accessible

### ISSUE THREAD

**Issue by chav-n** [atom/atom#8941]
Since there are many bytecode languages out there (Java, python, ...) one would naturally want to hide the bytecode files from what Atom has as a "Package Explorer". This is a task that many users would like to perform. Currently, this requires changing the Core settings as well as the tree-view package settings. The problem here is that a) tree-view is not an obvious name and b) one does not expect it to be treated, from the GUI perspective, as one of the 78 non-core standard packages of Atom.

This is a GUI design issue and I think it can cause frustration and waste serious time for the average user. It certainly did for me.

**Comment by 50Wliu** [comment]
The general issue of core and package settings not being unified is being tracked at atom/settings-view#284 - please subscribe there for updates.

**Comment by chav-n** [comment]
It shouldn't be all-or-nothing. Some "popular/critical" settings should be more accessible, for example, being mirrored in sections of a "General Settings" pane, that would begin with a "Core Settings" section.

I think that a complete unification is too much. It still does not address the name issue. How would someone guess the tree-view? If You expose just a few packages, it would at least be easier to locate.

**Comment by mnquintana** [comment]
The approach for solving this isn't set in stone yet, but https://github.com/atom/settings-view/issues/284 is the issue where we'd be discussing the best way to approach this, so I'm going to close this out.
