### ISSUE TITLE
Global gitignore

### ISSUE THREAD

**Issue by iofjuupasli** [atom/atom#8943]
In git there is possibility to use global .gitignore:

`git config --global core.excludesfile '~/.gitignore'`

Atom doesn't show files ignored by that excludefile as ignored. And shows them as new files (green in tree).

**Comment by dorian-marchal** [comment]
Did you find a solution ?

**Comment by iofjuupasli** [comment]
@dorian-marchal it started to work for me after some atom update
However git highlighting in atom is very buggy still, and I need to restart atom to fix that sometimes

**Comment by ssbarnea** [comment]
I don't know what causes this bug but suddenly about one week ago Atom started to display files that I do have added to global `.gitignore`. 

Git works well, ignoring these, but atom no longer respects the file. This is on MacOS 10.13. Maybe someone else managed to spot the issue.

**Comment by LukaHorvat** [comment]
Same issue
