### ISSUE TITLE
Atom running wild on memory

### ISSUE THREAD

**Issue by silentwarrior** [atom/atom#8944]
I rarely use Atom, I have it here for editing some random files, but I normally use a full blown IDE when working on bigger projects or vim when editing on the server.

I opened .vimrc with atom (wtf right? haha), and then this happens : 
![image](https://cloud.githubusercontent.com/assets/83322/10099785/d6146c66-6384-11e5-99a9-6105f7a5a2ee.png)

If you notice, its using 31GB of ram (getting paged to disk because i only have 16).

Closing it again and reopening gives me this:
![image](https://cloud.githubusercontent.com/assets/83322/10099812/20b3ce1a-6385-11e5-804e-e70cc34299f1.png)

I am pretty sure its something related to some plugin. How can I pinpoint what plugin it is so I can bug report to them?

PS: if you notice, PHPStorm has 666 for the port count, maybe he is acting evil and corrupting his brother for me choosing to open Atom :P

**Comment by 50Wliu** [comment]
You can try using @mark-hahn's [package-cop](https://atom.io/packages/package-cop) package, though I'm not sure if it'll work if you have to restart Atom each time.
