### ISSUE TITLE
Atom always shows checking for updates message and is not gonna upgraded

### ISSUE THREAD

**Issue by AryanShadowhunter** [atom/atom#8946]
I have the atom Version 1.0.3 as you see in the screenshot below. I want to update it to latest version that released in http://atom.io (1.0.18 October 2015) but i can't. It is always showing «checking for updates» message and don't download app updates. Is there any way or package to update my atom with User Interface or at least show me what is the problem with updating operations?

![update_issue](https://cloud.githubusercontent.com/assets/9091958/10100259/422b12e8-639d-11e5-96ff-5d3978377789.png)

**Comment by 50Wliu** [comment]
You can download the updated version at https://github.com/atom/atom/releases.  To find out what's wrong with the update checker, can you please paste the contents of `%localappdata%/atom/SquirrelSetup.log` into a Gist and then paste the link here?  Thanks.

**Comment by damieng** [comment]
No response, closing.
