### ISSUE TITLE
Hitting Esc on a dialog box should perform the most conservative option

### ISSUE THREAD

**Issue by artagnon** [atom/atom#8947]
For instance, on Cmd-Q, a dialog box comes up, and I hit Esc because I hit the keybinding by mistake in the first place. No changes are saved and my editor quits!

**Comment by mnquintana** [comment]
@atom/feedback I don't remember this happening before the Electron upgrade - this might be a regression?

**Comment by benogle** [comment]
I can repro. For me esc _does_ press cancel, but cancel doesnt do the right thing. Even pressing cancel on the cmd-q dialog will still quit the app.

**Comment by benogle** [comment]
Definitely seems like a regression.

**Comment by davidlin1980** [comment]
I cannot reproduce the issue, it seems okay on my setup. 

With unsaved document, pressing Esc with Cmd-Q dialog press cancel, and returns to the editor. (Expected behavior)

OS Version: Yosemite 10.10.4
Atom Version: 1.0.19

**Comment by artagnon** [comment]
Sorry, I forgot to mention: you need the git HEAD to reproduce this issue.

**Comment by kevinsawicki** [comment]
Did some git bisecting and this looks like it may have regressed in https://github.com/atom/atom/pull/8680
