### ISSUE TITLE
Windows7 'apm upgrade' problem

### ISSUE THREAD

**Issue by emcek** [atom/atom#8948]
Of course with previous atoms 1.0.11 worked after upgrade to 1.0.18 I have problem with **packages upgrade**

**C:\Users\mipl>apm upgrade**
'Package Updates Available (2)
├── language-haskell 1.4.6 -> 1.4.8
└── minimap 4.13.3 -> 4.13.4

Would you like to install these updates? (yes) yes

Installing language-haskell@1.4.8 to C:\Users\mipl\.atom\packages
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.30.7/node-v0.30.7.tar.gz
gyp WARN install got an error, rolling back install
gyp'

**C:\Users\mipl>apm -v**
'apm  1.0.5
npm  2.13.3
node 0.10.40
python 2.7.7
git 2.5.3.windows.1
visual studio 2010'

**C:\Users\mipl>apm install --check**
'Checking for native build tools failed

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.30.7/node-v0.30.7.tar.gz
gyp WARN install got an error, rolling back install
gyp'

**Comment by catscarlet** [comment]
I updated Atom to 1.0.19 today , and got the same problem today.
![snap021](https://cloud.githubusercontent.com/assets/10594035/10126243/7025f4cc-65c0-11e5-83c8-37e9163595fc.png)

I can download https://atom.io/download/atom-shell/v0.30.7/node-v0.30.7.tar.gz through my proxy .

**Comment by catscarlet** [comment]
I tried updating without my proxy , and it has the same problem too.
![snap022](https://cloud.githubusercontent.com/assets/10594035/10126269/4447dc8e-65c1-11e5-8245-e0fbab9732e5.png)

**Comment by galpin** [comment]
I am also having this problem and I can download the package in my browser.

Any ideas?

**Comment by gbark** [comment]
Same issue here. Works fine to download the tarball outside of apm.

**Comment by rcreasey** [comment]
This is also happening to me on a fresh 1.0.19 install:

```
C:\>apm install autocomplete-python
Installing autocomplete-python to C:\Users\rcreasey\.atom\packages
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | win32 | ia32
gyp http GET https://atom.io/download/atom-shell/v0.30.7/node-v0.30.7.tar.gz
gyp WARN install got an error, rolling back install
gyp

C:\>apm --version
apm  1.0.5
npm  2.13.3
node 0.10.40
python 2.7.9
git 2.6.0.windows.1
visual studio 2013

C:\>atom --version
[672:1014/104002:INFO:CONSOLE(0)] 1.0.19
```

I too, am behind a corporate proxy, but I have `strict-ssl=false` enabled:
```
C:\>apm config list
; cli configs
globalconfig = "C:\\Users\\rcreasey\\.atom\\.apm\\.apmrc"
user-agent = "npm/2.13.3 node/v0.10.40 win32 ia32"
userconfig = "C:\\Users\\rcreasey\\.atom\\.apmrc"

; userconfig C:\Users\rcreasey\.atom\.apmrc
strict-ssl = false

; globalconfig C:\Users\rcreasey\.atom\.apm\.apmrc
cache = "C:\\Users\\rcreasey\\.atom\\.apm"

; node bin location = C:\Users\rcreasey\AppData\Local\atom\app-1.0.19\resources\app\apm\bin\node.exe
; cwd = C:\projects\deployment
; HOME = C:\Users\rcreasey
; 'npm config ls -l' to show all defaults.
```

And can confirm that URL is indeed downloadable:
```
C:\>curl -LIk https://atom.io/download/atom-shell/v0.30.7/node-v0.30.7.tar.gz
HTTP/1.1 200 Connection established

HTTP/1.1 302 Found
Server: Cowboy
Connection: keep-alive
Date: Thu, 15 Oct 2015 01:01:35 GMT
Status: 302 Found
Strict-Transport-Security: max-age=631152000
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self'; connect-src 'self'; font-src 'self'; frame-src 'self' https://www.youtube.com; img-src https://* 'self' data:; media-src 'none'; object-src 'self'; script-src 'self' 'unsafe-inline' https://ssl.google-analytics.com https://www.google-analytics.com https://platform.twitter.com; style-src 'self' 'unsafe-inline';
Location: http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.30.7/node-v0.30.7.tar.gz
Content-Type: text/html; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 1141ebfd-fdc0-4566-b26a-9d79c04f657b
X-Runtime: 0.016041
X-Rack-Cache: miss
Via: 1.1 vegur

HTTP/1.1 200 OK
x-amz-id-2: pwLYG045qUgB42uQRcWPyBv55Z/4TW4RBZKS+K/UAuDHB0L6p5Ubzw51M+JdvyvT
x-amz-request-id: 7E62A77EA5118645
ETag: "e19edcc6ab9b814ae7e471e575166ca7"
Accept-Ranges: bytes
Server: AmazonS3
Content-Length: 438258
Content-Type: application/x-tar
Last-Modified: Thu, 24 Sep 2015 06:16:52 GMT
Date: Thu, 15 Oct 2015 00:58:30 GMT
Age: 187
Via: 1.1 myproxy:80 (Cisco-WSA/8.5.2-027)
Connection: keep-alive
Proxy-Connection: keep-alive
```

This seemed to all start around the 1.0.19 release.
@thedaniel: any thoughts on this?

**Comment by kowareta** [comment]
This worked for me.
https://github.com/atom/apm/issues/322#issuecomment-96430856

**Comment by emcek** [comment]
@kowareta Yes!!!!! It's working :)

**Comment by galpin** [comment]
@kowareta I can also confirm this worked for me. Thanks.

**Comment by damieng** [comment]
I think we should continue to track this directly on the apm issue at https://github.com/atom/apm/issues/322#issuecomment-96430856
