### ISSUE TITLE
[Metabug] Implement first class "Projects" support

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#8962]
It would be very nice if Atom could implement some sort of "projects" support. I couldn't find any open ticket for this, but [this discussion](https://discuss.atom.io/t/how-to-work-with-projects/1043/7) is pretty much what I'd write here if I had to explain what I'm asking for.

**Comment by mehcode** [comment]
@alexandernst Something like that UI presented is completely possible today to make a package for. The one missing feature (which I'll admit is pretty key to making it flow nice) is https://github.com/atom/atom/issues/6984 (switching projects within atom proper).

Each time you open a new atom window and open 1 or more folders, atom saves this as a "project" in its serialized state. A package could be made that reads this list of "projects" and presents a nice UI to switch between them if #6984 was implemented. I know how to do it in a very hack-ish way but I'd love a proper atom API before I dive into making a package for it.

**Comment by mehcode** [comment]
@alexandernst Project support is done enough in atom as of 1.7.0 (not released yet / on master). I'm working on vetting some additional use cases for projects in https://github.com/mehcode/atom-project-plus

**Comment by benogle** [comment]
> Project support is done enough in atom as of 1.7.0

Can you elaborate on this? I dont think we added anything related to projects recently.

**Comment by mehcode** [comment]
> Can you elaborate on this? I dont think we added anything related to projects recently.

By *projects* I mean the serialization system as well as the API. The serialization system has recently been greatly improved (partly by moving to IndexedDB). Furthermore we've moved mostly away from relying on (de)serializing state in a url encoded JSON object on `location.hash`. I've been watching for these features. This is awesome. This enables me to provide a project switching API with a couple lines of code (for the base). To make it _stable_ we'd need to provide an actual API in core ( #6984 ) and provide events for when the project changed so packages can update if needed (there is currently a hack in the project switch for tree-view).

**Comment by benogle** [comment]
Noted, thanks for the detail. The serialization is now being stringified for performance. Not sure if that hurts what you are trying to do: https://github.com/atom/atom/pull/10925

**Comment by mehcode** [comment]
Nope. I caught that change and updated my package this morning. :+1:

**Comment by mehcode** [comment]
I was able to make https://github.com/mehcode/atom-project-plus work without relying on master. I shimmed a handful of functions; it's really quite awful. Heh. Will be happy to remove the shims in the coming month (once 1.7 is released).
