### ISSUE TITLE
Cursor not aligned with text

### ISSUE THREAD

**Issue by GreyFox48** [atom/atom#8964]
Atom Version: 1.0.19
OS: Ubuntu 14.04.4 LTS

Hello,

  I am currently having an issue where the cursor on atom will not keep aligned with the text.  Here is a gif:
![screencapture](https://cloud.githubusercontent.com/assets/14354407/10123592/b717f298-64fa-11e5-9338-a56ceb585eb6.gif)

  This happens even when there are not repeating characters, getting worse the farther right the text is on the screen.  I should mention that I am not running any third party packages.  So far, I have tried closing atom, renaming the .atom file, and then opening again while running only the core packages in order to try to solve the issue.   I have even tried completely uninstalling atom to try to fix it, but the issue still persists.  Any and all help will be appreciated.

**Comment by as-cii** [comment]
Hey @GreyFox48, thank you for reporting this issue!

Could you please post which theme you're using, your custom stylesheet and the font family you're working with as well? Seems like something is screwing up character measurement, which shouldn't happen unless some particular font properties are set either on your stylesheet or in the font itself.

Also, which packages are you using? (hint: running `apm list` in your terminal will show them) 

It'd be great if you could also specify when you started observing this bizarre behavior: spotting a correlation with a specific Atom version could help us identifying the culprit. 

Thank you! :bow:

**Comment by GreyFox48** [comment]
Hello @as-cii and thank you for replying.  

Thanks to you, I found the issue.  The font family for whatever reason was completely blank, like so:

![screenshot from 2015-09-28 13 18 10](https://cloud.githubusercontent.com/assets/14354407/10145953/76390458-65e3-11e5-8ce7-2efe56c2c88f.png)

I set it to Ubuntu Mono, and that seemed to fix the issue.  I also was able to recreate the problem:  If you close atom, rename the .atom folder, and then reopen atom the font family will always be set to blank, and the character measurement will be messed up again.  I don't know if one is intended to manually fill out the the font family during first time setup or not, but it seems to create issues.  

In case you wanted to still know about the other information, here it is:
UI and Syntax Theme: One Dark
Font Family:  was blank, now Ubuntu Mono and fixed
Stylesheet: is whatever the default is:

![screenshot from 2015-09-28 12 50 56](https://cloud.githubusercontent.com/assets/14354407/10145772/609f5f1c-65e2-11e5-8864-efc8285a0a8c.png)

Packages: according to apm list none, aka (empty), disregarding the built in packages.
I noticed the behavior Saturday, which is about when I installed atom for the first time.

Thank you so much for the help!  Really appreciate it.  Atom looks like an excellent text editor, and I'm glad to have it working.

**Comment by mark-adams** [comment]
I'm experiencing the same issue on a Dell XPS 13 with Ubuntu 15.04. I'm running 3200x1800 with a display scale setting of 2x (hidpi).

I did not experience the issue until I upgraded to 1.0.19 a few days ago from 1.0.11.
When I downgraded to 1.0.11, it fixed the issue for me.

I can confirm that "Font Family" is blank in the default configuration and switching to Ubuntu Mono does fix the issue. However, if I switch to my normal editor font [Hack](http://sourcefoundry.org/hack/), I definitely still have the issue even with "Font Family" populated.

No packages installed. No stylesheets. Default theme. If you need more information, please let me know.

**Comment by as-cii** [comment]
> Thank you so much for the help! Really appreciate it. Atom looks like an excellent text editor, and I'm glad to have it working.

Glad you enjoy it! :green_heart: 

>  I don't know if one is intended to manually fill out the the font family during first time setup or not, but it seems to create issues.

I am not sure if the configuration setting will be filled by default (I think it won't), but Atom should set for you a standard font out of the box nevertheless, so this still seems an anomalous behavior to me. Could you tell which font gets automatically picked up when the font-family box is empty?

It should default to a `monospace` character, but something is probably screwing that up. To check which font is being used, you could simply poke around in Chrome Developer Tools:

![screen shot 2015-09-30 at 10 54 29](https://cloud.githubusercontent.com/assets/482957/10188683/a9a9de46-6761-11e5-813d-34ac087ca341.png)

And check the computed styles of any line:

![screen shot 2015-09-30 at 10 55 55](https://cloud.githubusercontent.com/assets/482957/10188708/d889f7e6-6761-11e5-9ff6-2a8c1c967ea5.png)

> I think this potentially points a finger at the Chrome 43 update that went in during 1.0.12 (since 1.0.11 is the first version where I seem to not experience the issue)

That's interesting, @mark-adams. I wonder: are you able to reproduce this issue with a font that's not `Hack`? This should let us further discard/confirm the hypothesis that it's a font-related issue.

@atom/feedback: could anyone with an Ubuntu environment reproduce this problem? 

Thanks everyone! :bow:

**Comment by pacharanero** [comment]
I run Linux Mint 17.3 on a Dell M3800 (HiDPI) and had exactly the same problem, which was fixed when I populated Font-family with Ubuntu Mono. It was blank on my OOTB install 1.0.19. I haven't tried any other fonts though

**Comment by mark-adams** [comment]
![screenshot from 2015-10-01 20 48 54](https://cloud.githubusercontent.com/assets/472350/10237901/ee90de70-687d-11e5-9145-e0b43445e93d.png)

Testing in 1.0.19 (with the issue): `font-family: Menlo, Consolas, 'DejaVu Sans Mono', monospace;`
Testing in 1.0.11 (without the issue): `font-family: Menlo, Consolas, 'DejaVu Sans Mono', monospace;`

**Comment by mark-adams** [comment]
I tried switching to Source Code Pro to eliminate Hack being the issue and I experience the same thing with Source Code Pro (cursor is not aligned with the text)

![screenshot from 2015-10-01 20 58 03](https://cloud.githubusercontent.com/assets/472350/10238012/4c52e5ac-687f-11e5-9f54-9fe1820ca917.png)

I'm thinking this is related to HiDPI. I went ahead and tried changing my display scaling to 1.0 instead of 2.0 (2.0 is the norm for HiDPI) and the issue does not present itself anymore for the default (no font), Hack, or Source Code Pro.

![screenshot from 2015-10-01 21 01 44](https://cloud.githubusercontent.com/assets/472350/10238071/d063ca1e-687f-11e5-97e1-a15747724acf.png)

Is it possible that Atom / Elecftron is not reading the system display scaling setting properly?

**Comment by niedzielski** [comment]
I experience this issue in v1.0.19 on a high DPI Cinnamon 17.2 Mint installation on certain text zoom levels. I can hold the ctrl key and scroll in Atom to find a level that works.

**Comment by niedzielski** [comment]
I take it back. The cursor positioning seems to be completely botched most of the time.

**Comment by as-cii** [comment]
This seems to coincide with our _recent_ electron upgrade. @zcbenz: as far as I remember, this area of the code hasn't changed from `v1.0.11`; do you think this could be an issue with electron/Chrome?

Unfortunately I cannot reproduce it (as it seems platform-dependent and somehow related to the font) but this should probably be solved after we :ship: #8811: our current measurement/positioning technique relies on measuring characters for a certain scope once and then reuse that width to compute coordinates for visual elements; this is probably having an impact on this issue as well, so I'd like to wait until we merge the new measurement mechanism before diving in.

@niedzielski @mark-adams: no pressure on this, but it would be awesome if you could test the aforementioned PR by building it locally: your feedback would be really appreciated! :pray:

**Comment by mark-adams** [comment]
When trying to reproduce, make sure you have display scaling set to "2" (see the screenshot above) as this appears to be important and may explain why the issue is hard to reproduce (usually users don't use display scaling unless  they have a hidpi screen)

I tried #8811 locally and it appears to fix this issue very nicely. :smile:

**Comment by zcbenz** [comment]
@as-cii It is probably because `subpixel-font-scaling: false` is not working on Linux, that option had been removed by Chrome very long ago and I have been patching Chromium to add it back, it possible that recent Chrome versions have added new code paths for rendering font on Linux and our patch didn't cover that.

Refs https://github.com/atom/atom/issues/6055.

**Comment by as-cii** [comment]
> I tried #8811 locally and it appears to fix this issue very nicely.

Awesome, thanks for trying that out! :bow: 

> It is probably because subpixel-font-scaling: false is not working on Linux, that option had been removed by Chrome very long ago and I have been patching Chromium to add it back, it possible that recent Chrome versions have added new code paths for rendering font on Linux and our patch didn't cover that.

Makes sense. We're enabling subpixel font scaling by default in #8811, thus we should be able to drop our patch to support the deprecated option as soon as that PR lands. :+1: Thanks @zcbenz!

**Comment by 50Wliu** [comment]
Closing since #8811 has been merged.
