### ISSUE TITLE
Package commands shouldn't be (mandatorily) added as menu items

### ISSUE THREAD

**Issue by dcarral** [atom/atom#8967]
It seems like nowadays (v1.0.18) package authors are forced to register commands as menu items in order to make them available. I've just figured out what was happening the hard way, after struggling with package activation-related specs. 

Since I didn't dive into core code to check out what's the root of this, so... don't know if this is intended or not. Anyway, as far as I see it, it doesn't make sense. As a package developer I'd like to provide n different commands, listing just a subset of them in the menus.

It would be nice to read your thoughts about this, perhaps I'm missing something out.

**Comment by mnquintana** [comment]
> package authors are forced to register commands as menu items in order to make them available.

Hmm that shouldn't be the case - there are plenty of packages that register commands but don't add them as menu items. What kind of error were you getting?

**Comment by dcarral** [comment]
Sure @mnquintana. I've kept working on (my) issue and it (happily) doesn't have nothing to do with the menu items. This issue can be safely closed, sorry for the lying report.

For what it's worth, It seems like I was running into async issues related to package activation while passing the integration tests (it was being delayed because of activation commands, which by the way makes integration testing in Atom packages a kind of nightmare).

**Comment by dcarral** [comment]
@mnquintana, @thomasjo: For what it's worth, I've been spiked again by this issue. I've just created the [menu_items_issue](https://github.com/dcarral/atom-ruby-test-switcher/tree/menu_items_issue) branch within [atom-ruby-test-switcher](https://github.com/dcarral/atom-ruby-test-switcher/) repo, so you guys (or anyone interested) could take a look at it.

[The package is subscribing to 2 commands](https://github.com/dcarral/atom-ruby-test-switcher/blob/menu_items_issue/lib/ruby-test-switcher.coffee): `switch` and `switch-without-split`. Only one of them is included as menu item (`switch-without-split`) within the [menus/ruby-test-switcher.cson](https://github.com/dcarral/atom-ruby-test-switcher/blob/menu_items_issue/menus/ruby-test-switcher.cson) file, being it the single command which correctly works. Including the other one (`switch`) as a menu item fixes that, forcing both commands to work as expected.

If anyone could bring light to this issue by pointing out what's the cause of this behavior I'd highly appreciate it ;)
