### ISSUE TITLE
ALT+F opens File menu item, but only if no file is open

### ISSUE THREAD

**Issue by awvalenti** [atom/atom#8977]
On main menu, the File item is underlined on the F letter. ALT+F opens it, but only if no file is open. If a file is open, Atom instead advances to the next word, like CTRL+Right.

I understand this may be a terminal/vim-like behavior. However, a shortcut's behavior should be consistent. Either it opens the File menu item, or it doesn't.

ALT+H (for the Help menu item) has this problem, too.

**Comment by 50Wliu** [comment]
Refs #4057.

**Comment by damieng** [comment]
Will track via #4057
