### ISSUE TITLE
Blurry text when scrolling

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#8979]
![blur](https://cloud.githubusercontent.com/assets/2766036/10148101/b620c8e6-65ff-11e5-8d29-450b3450fb47.gif)
It's much easier to see if you open the GIF in a new tab.

Basically what's happening is whenever I select enough text to scoll the editor (ie the scrollbars are moving), the text becomes blurry and stays that way until I scroll a bit out of its range and then back (guessing this has something to do with tiles).  Both horizontal and vertical scrolling are affected.

Also tested in safe mode.  Windows 10 x64, Atom 1.0.19, though this has been happening for a *long* time.

/cc @as-cii

**Comment by as-cii** [comment]
Ugh, tiling strikes again.

@50Wliu: thanks for reporting this, I guess all of these headaches will be over as soon as we switch back to a single layer. This is going to happen in a near future, I think.

**Comment by 50Wliu** [comment]
I can no longer reproduce this on Atom 1.2.0-dev-6495f1a.
