### ISSUE TITLE
Can't install/update packages - High CPU on Evented I/O for V8 JavaScript

### ISSUE THREAD

**Issue by yanlyan** [atom/atom#8980]
I can't install or upgrade any packages, the installing process seems stuck. 

![asdasdadddddd](https://cloud.githubusercontent.com/assets/3099180/10153110/4f312138-6683-11e5-8c7a-79269d67d7fe.PNG)

On my task manager theres Evented I/O for V8 JavaScript with high cpu, when i end those process the package installing process error with no message.

It's running on Win 10 x64
Atom version : 1.0.19

![jkjkjkjk](https://cloud.githubusercontent.com/assets/3099180/10153204/261fe45e-6684-11e5-98c3-0c606d35ecc5.PNG)

![hjhjhhjhj](https://cloud.githubusercontent.com/assets/3099180/10153149/a8d14a9c-6683-11e5-8eaa-122f6b07997c.PNG)

**Comment by polarathene** [comment]
How long did you leave it updating/installing? I just updated all my packages, atom-typescript made my cpu usage max to 100%, Windows anti-malware service was consuming 30%+ of that, once it died down V8 took over like your screenshot. It had been updating that same package for a while but eventually completed.

**Comment by mnquintana** [comment]
What version of Atom are you using?

**Comment by polarathene** [comment]
@mnquintana I'm on 1.0.19

**Comment by yanlyan** [comment]
@polarathene I've been leave it updating for all night long

@mnquintana I'm on 1.0.19

**Comment by EdJr** [comment]
The same happened here. I'm using Atom 1.1.0. There was only TypeScript left to be updated and both the CPU and memory usage were really high (CPU at 99%, memory at 74%).

I think it's worth mentioning that I'm using atom-sync-settings. I installed all my packages on Ubuntu and backed them up. I opened Atom on Windows (with just TypeScript and some other packages installed), then `Sync Settings > Restore` and this happened. After checking that the packages were in fact installed, I closed and reopened Atom and it said all my packages are up-to-date (including TypeScript, which was still showing as being updated when I closed Atom). Now the CPU usage is generally lower, but it sometimes oscillates a lot while idle (I don't know if this is normal behavior).

**Comment by mohessaid** [comment]
This thing happens everywhere, with Atom and when I use ionic serve in one of my projects, it's everywhere, I think windows **won't** support these things very well.

**Comment by darkred** [comment]
I confirm this in Atom 1.5.3 in win 10 x64.
It occurred while trying to install the `atom-beautify` package.

At some time I force closed the `Evented I/O for V8 JavaScript` process via Task Manager,
and then closed Atom.
Now whenever I open Atom's `Settings|Packages`
the Atom.exe process causes ~100% CPU usage 
and the packages are not listed: they are stuck in "Loading Packages..." instead.

**Comment by Basfordxela** [comment]
This issue still seems to be present in version 1.5.4. I am running Windows 10 x64. Anytime I attempt to update the packages my cpu usage jumps to 100% and I have to end the Evented I/O for V8 Javascript process in task manager.

**Comment by abeltensor** [comment]
I've completely stopped using Atom because of this problem.  It happens all the time while updating and just running atom on windows 10 64bit.  Overall the editor is slower than a big IDE like android studio which is a big issue imo.  not to mention that when i run Atom it will spawn like 10-15 evented I/O  for V8 JavaScript processes.

**Comment by polarathene** [comment]
I've been using both Linux and OSX since Jan this year. Haven't encountered the problem, so it's definitely related to something going on with Windows.

 Another similar issue someone found the solution for them was to disable anti-virus software from monitoring area's Atom touched like projects or where it stores it's settings/packages, something like that.

**Comment by abeltensor** [comment]
I don't use an anti-virius and i have windows defender ignoring the problem.  No real change on my end.
