### ISSUE TITLE
Consider adding 'editor:remove-last-selection' (& first)

### ISSUE THREAD

**Issue by zyklus** [atom/atom#8981]
This is a feature request.  This happens to me all the time -- I'm adding cursors on 10 lines and I accidentally go one line too far and there's no keyboard shortcut to remove the last cursor I created.

**Comment by 50Wliu** [comment]
You can actually just ctrl+click/cmd+click that selection to remove it :smile:.

**Comment by zyklus** [comment]
@50Wliu -- Yes, I know, but I want a keyboard shortcut!  :D  I almost never touch my mouse.

**Comment by 75lb** [comment]
i'm migrating from TextMate 2 and i miss this feature too.. in TextMate you tap shift twice to undo the previous selection(s).. i'd love that in Atom too - i frequently CMD+D too far..

**Comment by karlek** [comment]
Also frequently used in sublime text with `Ctrl-u`.
