### ISSUE TITLE
Ubuntu 14.04 atom Chinese garbled

### ISSUE THREAD

**Issue by robinclark007** [atom/atom#8986]
when I open the atom editor .the Chinese garbled 
below is a picture i captured ...
![screenshot from 2015-09-29 01 32 41](https://cloud.githubusercontent.com/assets/8747172/10158959/08be031c-664a-11e5-8460-25eaf29f7a28.png)

How could I fix this problem

My File is UTF8 encoded also without BOM. works fine with atom on windows.
So I think it's a problem associated with liunx system.

**Comment by catscarlet** [comment]
It seems your file may not  be encoded in utf8 
Convent to UTF8 without BOM.
![snap023](https://cloud.githubusercontent.com/assets/10594035/10159286/eecac168-66c9-11e5-82a6-bad69b8a3138.png)

**Comment by 50Wliu** [comment]
In addition, please make sure you're running Atom 1.0.12 or above.
