### ISSUE TITLE
In dwm focusing on window with hotkeys doesn't work

### ISSUE THREAD

**Issue by prog666** [atom/atom#8987]
http://dwm.suckless.org/ - dwm
btw, in sublime everything works fine

**Comment by prog666** [comment]
to reproduct this install DWM and use 'ctrl + j' to switch between windows

**Comment by drewmnoel** [comment]
@prog666 can you post your versions? It works for me right now.

```
$ atom -v
Atom    : 1.9.0-dev-720ad9c
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ apm -v
apm  1.10.0
npm  2.13.3
node 0.10.40
python 3.5.1
git 2.8.2
$ pacman -Qi dwm 
Name            : dwm
Version         : 6.1-3
```

**Comment by prog666** [comment]
I have Mac already, so if it works for you just close the issue

**Comment by lee-dohm** [comment]
Thanks for the quick response @prog666.
