### ISSUE TITLE
Disabled package updates enable package

### ISSUE THREAD

**Issue by polarathene** [atom/atom#8988]
If I have disabled packages installed, and an update is available, triggering the update manually/individually or via update all packages enables any updated disabled package afterwards. I do not believe this is an intended behaviour? I cannot use Update All button unless I take note of my disabled packages to disable again after updating or uninstall them prior.

Win 8.1x64

**Comment by izuzak** [comment]
Thanks for the report -- I think this is a duplicate of https://github.com/atom/settings-view/issues/603.
