### ISSUE TITLE
High Cpu usage by SAMBA process on linux while trying to edit files on SHARED network

### ISSUE THREAD

**Issue by alilg** [atom/atom#8989]
i love atom and i have using it for months without any problem!.
BUT recently i recognized when ever we try to edit a file, which located on our "LAN NETWORK (a centos6 box with samba-server installed)", the samba cpu usage (on the linux client which installed atom) is raising!
ATOM cpu usage is normal, but "gvfsd-smb" and "gvfsd-fuse" is hogging the CPU!.
if i close the "ATOM" the cpu usage of "gvfsd*" will go down immediately!
and if i start atom "(with safe flag or without)" the cpu usage of "gvfsd*" is hogging again immediately and laptop fan speed is raicing and want to blow up!
What i guess is ATOM is looking for something into the shared directory or something in the background maybe? :/ 
THIS THING happening on WINDOWS too!
On windows, when we open ATOM, the "ExpanDrive SFTP" cpu usage is going for 70% immediately!
and when we close the ATOM, the "ExpanDrive SFTP" cpu usage is go zero.
ExpanDrive is a software we use on windows, to access CENTOS folders and edit them easy.
Our files are located on a Centos6.7 box and we try to edit them via ATOM editor on Windows7 box and LinuxMint box.

I really love ATOM but i can not use if for more then 3 days because of this CPU usage...
any idea?

This thing only happening with 'ATOM". with other editors like "Sublime" we can edit files on shared folder without any cpu hog.

top before lunch atom --safe
![screenshot from 2015-09-29 15 44 46](https://cloud.githubusercontent.com/assets/7819173/10163640/30e51156-66c1-11e5-817d-2c154a080f45.png)

top after lunch atom --safe
![screenshot from 2015-09-29 15 45 51](https://cloud.githubusercontent.com/assets/7819173/10163641/31229e0e-66c1-11e5-9eaf-d17cff231697.png)

**Comment by alilg** [comment]
i fount the problem!
the problem was because of "samba share file locking mechanism".
noting wrong with "ATOM". just samba file locking mechanism...

**Comment by alexandreLavenant** [comment]
@alilg Can you please post your solution for samba configuration file, i have the same problem. Thx

**Comment by alilg** [comment]
@alexandreLavenant i had a git folder under the shared directory, which contained some files with huge size! (one of them was 500MB for example. yes a single file with 500mb. id on't remember then name of those files, but it was cache or temp file as i remember).
after deleting that and restart, atom worked smooth.

I thinks ATOM has a mechansim which scans the folders or something like that, and when it detect a huge file, it stopps and cpu goes 100%
