### ISSUE TITLE
shown cursor and real cursor are not synced 

### ISSUE THREAD

**Issue by AlhasanIQ** [atom/atom#8993]
in arabic there are characters that are placed under/above the letter ( we call them حركات or harakat )

in atom if i write a word with one of these characters there will be a problem that the cursor will be shown in a place and if a write it will insert letters in another position 

test with this text
كتابً جميلاً جداً تيست تيست تيست

**Comment by izuzak** [comment]
Thanks for the report -- I think this is a duplicate of https://github.com/atom/atom/issues/1849.
