### ISSUE TITLE
backupBeforeSaving does not work for SharePoint/WebDAV shares

### ISSUE THREAD

**Issue by jeoje** [atom/atom#8994]
Hello,

I've noticed that the backupBeforeSaving option in versions 1.04+ does not work for SharePoint/WebDAV shares.  I love the feature itself, but is it possible to do the backup save in a local temp directory, instead of the folder in which we're attempting to save?

Error shown in the popup notification -- there is no stack trace logged in the console:

```
Unable to save file '\path\file.js~'

UNKNOWN: unknown error, open '\\path\file.js~'
```

Thanks

**Comment by 50Wliu** [comment]
The backupBeforeSaving option has been removed.
