### ISSUE TITLE
error installing modules: scrollbar-style@3.2.0

### ISSUE THREAD

**Issue by xl1000** [atom/atom#8996]
Using RH 6.7, x64, receiving error during script/build process, with a lot of stack trace messages ending with : 

$ script/build
Node: v0.10.40
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✗
... < snip > ...
npm ERR! scrollbar-style@3.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrollbar-style@3.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrollbar-style package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrollbar-style
npm ERR! There is likely additional logging output above.

Additional data from the debug npm-debug.log : 
....<snip>...
45237 verbose about to build /home/xl1000/Downloads/atom/node_modules/git-utils
45238 info build /home/xl1000/Downloads/atom/node_modules/git-utils
45239 info linkStuff git-utils@3.0.1
45240 silly linkStuff git-utils@3.0.1 has /home/xl1000/Downloads/atom/node_modules as its parent node_modules
45241 verbose linkBins git-utils@3.0.1
45242 verbose linkMans git-utils@3.0.1
45243 verbose rebuildBundles git-utils@3.0.1
45244 verbose rebuildBundles [ 'nan' ]
45245 info install git-utils@3.0.1
45246 verbose unsafe-perm in lifecycle true
45247 info git-utils@3.0.1 Failed to exec install script
45248 verbose unlock done using /home/xl1000/.atom/.apm/_locks/git-utils-f55cdfd253a276e2.lock for /home/xl1000/Downloads/atom/node_modules/git-utils
45249 verbose stack Error: scrollbar-style@3.2.0 install: `node-gyp rebuild`
45249 verbose stack Exit status 1
45249 verbose stack     at EventEmitter.<anonymous> (/home/xl1000/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/lib/utils/lifecycle.js:214:16)
45249 verbose stack     at EventEmitter.emit (events.js:98:17)
45249 verbose stack     at ChildProcess.<anonymous> (/home/xl1000/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/lib/utils/spawn.js:24:14)
45249 verbose stack     at ChildProcess.emit (events.js:98:17)
45249 verbose stack     at maybeClose (child_process.js:766:16)
45249 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
45250 verbose pkgid scrollbar-style@3.2.0
45251 verbose cwd /home/xl1000/Downloads/atom
45252 error Linux 2.6.32-573.3.1.el6.x86_64
45253 error argv "/home/xl1000/Downloads/atom/apm/node_modules/atom-package-manager/bin/node" "/home/xl1000/Downloads/atom/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/xl1000/.atom/.apm/.apmrc" "--userconfig" "/home/xl1000/.atom/.apmrc" "install" "--target=0.30.7" "--arch=x64"
45254 error node v0.10.40
45255 error npm  v2.13.3
45256 error code ELIFECYCLE
45257 error scrollbar-style@3.2.0 install: `node-gyp rebuild`

Seeing also an error failing to install git-utils, is causing confusion about what to do...
any ideas ?

**Comment by gauravsaxena26** [comment]
I am also getting this error while trying to build _atom_ on __Rhel 6__. 

Supporting build output is pasted below

$ script/build 
Node: v0.10.40
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✗
> atom@1.1.0-beta1 preinstall /home/adminibm/atom
> node -e 'process.exit(0)'


> scrollbar-style@3.2.0 install /home/adminibm/atom/node_modules/scrollbar-style
> node-gyp rebuild


> oniguruma@5.1.1 install /home/adminibm/atom/node_modules/oniguruma
> node-gyp rebuild


> nslog@3.0.0 install /home/adminibm/atom/node_modules/nslog
> node-gyp rebuild


> runas@3.1.0 install /home/adminibm/atom/node_modules/runas
> node-gyp rebuild


> git-utils@4.0.5 install /home/adminibm/atom/node_modules/git-utils
> node-gyp rebuild


> keyboard-layout@1.0.0 install /home/adminibm/atom/node_modules/atom-keymap/node_modules/keyboard-layout
> node-gyp rebuild


> pathwatcher@6.2.5 install /home/adminibm/atom/node_modules/pathwatcher
> node-gyp rebuild


Traceback (most recent call last):
  File "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 533, in script_main
    return main(sys.argv[1:])
  File "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 526, in main
    return gyp_main(args)
  File "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    params, options.check, options.circular_check)
  File "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 129, in Load
    params['parallel'], params['root_targets'])
  File "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2736, in Load
    variables, includes, depth, check, True)
  File "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 386, in LoadTargetBuildFile
    includes, True, check)
  File "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 258, in LoadOneBuildFile
    aux_data, includes, check)
  File "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 295, in LoadBuildFileIncludesIntoDict
    LoadOneBuildFile(include, data, aux_data, None, False, check),
  File "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 238, in LoadOneBuildFile
    None)
  File "/home/adminibm/.atom/.node-gyp/.node-gyp/0.30.7/common.gypi", line 1
    {
     ^
SyntaxError: invalid syntax
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
gyp ERR! command "node" "/home/adminibm/atom/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/adminibm/atom/node_modules/scrollbar-style
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by jlsalmon** [comment]
I'm also seeing the same issue as @gauravsaxena26 on RHEL6.

**Comment by hamxiaoz** [comment]
It seems like a node-gyp issue. Try to make sure you meet all the prerequisites, see: https://github.com/nodejs/node-gyp

**Comment by Harsesis** [comment]
I had the sime issue and I could solve it by using python 2.7 instead of 2.6 (compiling went without problems)
