### ISSUE TITLE
Consider an `onDidStopChangingActivePaneItem`

### ISSUE THREAD

**Issue by ssorallen** [atom/atom#8997]
Similar to the motivation behind [`TextEditor::onDidStopChanging`](https://atom.io/docs/api/v1.1.0-beta.0/TextEditor#instance-onDidStopChanging),  clients of `onDidChangeActivePaneItem` should nearly always wait for a small time period before acting on the new pane item. If the user is quickly switching through tabs or closing several tabs in quick succession, work done on [`Workspace::onDidChangeActivePaneItem`](https://atom.io/docs/api/v1.1.0-beta.0/Workspace#instance-onDidChangeActivePaneItem) is likely wasted and can become a bottleneck for giving feedback to the user if they are switching/closing tabs quickly.

There's at least one candidate in core that could defer its actions until the active item has stopped changing: [`FileInfoView`](https://github.com/atom/status-bar/blob/master/lib/file-info-view.coffee#L71) in the status bar.

Nuclide wrapped `onDidChangeActivePaneItem` to get this effect: https://github.com/facebook/nuclide/blob/master/pkg/nuclide/atom-helpers/lib/atom-event-debounce.js#L29

I think a `DidStopChangingActivePaneItem` should be recommended similar to the one in `TextEditor` if it's created.

**Comment by ssorallen** [comment]
`GitView` in the status bar is another candidate: https://github.com/atom/status-bar/blob/master/lib/git-view.coffee#L11

**Comment by ssorallen** [comment]
`ImageView`: https://github.com/atom/image-view/blob/master/lib/image-editor-status-view.coffee#L15

All of the synchronous updates can be seen by looking at the chart in a debugger profile.

**Comment by maxbrunsfeld** [comment]
Yeah, I think this would be a good change. I'd be glad to merge a PR adding this feature.

**Comment by ssorallen** [comment]
@maxbrunsfeld Awesome, I'm happy to add this. I'll send a PR in the next couple days.
