### ISSUE TITLE
Suggestion: Select Next (CMD + D) Case Insensitivity Option

### ISSUE THREAD

**Issue by MethodGrab** [atom/atom#9003]
I think `Select Next` (`CMD + D`) should respect the case sensitivity option of find and replace.
I.E. if find and replace search is set to case **insensitive**, all the following should be treated the same and selectable by `CMD + D`:

```
FooBar
FooBar

fooBar
fooBar
```

This is how Sublime Text does it and for me it's more useful to have as an option.

**Comment by jeancroy** [comment]
Basically this ask for what was done here but for case-sensitivity in addition to whole word.
https://github.com/atom/find-and-replace/pull/482

**Comment by benogle** [comment]
Seems reasonable to attach the setting to cmd for case as well. PRs welcome :)

**Comment by benogle** [comment]
Closed via https://github.com/atom/find-and-replace/pull/541

**Comment by benogle** [comment]
In the next release you will be able to use the find and replace case sensitivity option to toggle this behavior.

![screen shot 2015-10-01 at 4 28 07 pm](https://cloud.githubusercontent.com/assets/69169/10236359/6b75d226-6859-11e5-91dd-13eae3216eeb.png)

**Comment by MethodGrab** [comment]
Excellent, thanks! :+1:

**Comment by Ganbin** [comment]
Hello, I come here because this behavior doesn't seems to work for me. I have my `find & replace` set to `Case Insensitive` but when I use `cmd + d` it select only the one that are `Case Sensitive`.

**Comment by elado** [comment]
Doesn't work here either. v1.14.2. Search preferences are ignored on CMD+D (even when search bar is opened)
