### ISSUE TITLE
Disallow moving project folder

### ISSUE THREAD

**Issue by Kroid** [atom/atom#9008]
Drag-ang-drop 'project folder' to another folder - bad feature, because undo is difficult. Maybe do not allow this or use copy instead move?

**Comment by mitchellnemitz** [comment]
I quite literally just did this 3 minutes ago and almost paid dearly for it.

+1 please disable drag and drop for folders or enable undo folder move.

**Comment by arcticicestudio** [comment]
:+1: for avoiding accidentally moved folders or at least adding a setting to disable drag & drop for project folder

**Comment by philipgiuliani** [comment]
A confirm dialog when moving folders would also be nice! It happened so often to me. Good when you have git at least to see where its gone... :laughing:

**Comment by mnquintana** [comment]
This issue was moved to atom/tree-view#590
