### ISSUE TITLE
Ubuntu 64 bit - "The editor has crashed"

### ISSUE THREAD

**Issue by jsonschema** [atom/atom#9009]
OS:
- Ubuntu 14.04 (64 bit)

Atom packages:
- atom-material-syntax
- color-picker
- jsformat
- atom-material-syntax-light
- dracula-theme
- linter
- seti-ui
- atom-material-ui
- file-icons
- minimap
- trailing-spaces

I consistently receive the alert "The editor has crashed".  I started receiving this exception a few weeks ago and had _not_ installed any new packages or modified Atom. I don't know what precipitated this exception.
- I have reinstalled Atom using the Ubuntu Software Center and still receive the exception.
- The Developer Tools console is empty and remains empty after reloading the window.

![screenshot from 2015-09-30 15 52 41](https://cloud.githubusercontent.com/assets/1623996/10196551/541db3f6-678b-11e5-9152-cf1a0a230a41.png)

**Comment by strandoe** [comment]
Same here. It also caused an internal ubuntu error regarding something like whitelist certificates.
