### ISSUE TITLE
Atom 1.0.7 wont update after restart and it wont restart

### ISSUE THREAD

**Issue by AdamKyle** [atom/atom#9010]
I have Mac OSX 10.10 and Atom 1.0.7 and it states there is an update. Ok, so i say download. Mac requests password. Great lets enter that. It downloads then states "restart and install update" Awesome.

Nothing ever happens ..... Waits ..... 15 ..... 30.....45.....50....minutes later. I open Atom, "download update" ... Um ok? "restart and install update" .... um Ok - same loop.

So I cleared out `~/.atom/storage` Same issue.

Help?

**Comment by 50Wliu** [comment]
@AdamKyle does #2860 cover what you're seeing?

**Comment by damieng** [comment]
No response, presumably fixed. Please re-open if it is not.
