### ISSUE TITLE
Syntax highlighting problem in python multiline string containing "CREATE"

### ISSUE THREAD

**Issue by JoarLeth** [atom/atom#9013]
Steps to reproduce:
1. Create a python file, e.g. asdf.py
2. Define a function, with a multinine string containing "CREATE" (within quotes)
```
def asdf()
    '''
    "CREATE"
    ''''
    print "Hi!"
```
"UPDATE" and "DELETE" give the same result, except those words get highlighted in a different color than the rest of the multiline string.

Expected result:
The code after the multiline string should be syntax highlighted as python code.

Actual result:
Everything after the multiline string is highlighted as if it were a string.

I'm on Atom 1.0.19 and I have disabled my Community Packages.

**Comment by 50Wliu** [comment]
@JoarLeth can you please move this to the [atom/language-python](https://github.com/atom/language-python) repo?  Thanks.

**Comment by JoarLeth** [comment]
Sorry about that, I'll post it there. No, I just made a typo when I added the issue.
