### ISSUE TITLE
Consume two services in single package

### ISSUE THREAD

**Issue by fojtCz** [atom/atom#9016]
I'm creating two simple packages which should interact between each other, but function ```consumePackage2``` never ran. I have this in JSON files:

package.json of first package:
```
{
  "name": "package-1",
  "main": "./lib/package-1",
  "version": "0.0.0",
  "description": "A short description of your package",
  "keywords": [
  ],
  "repository": "https://github.com/atom/package-1",
  "license": "MIT",
  "engines": {
    "atom": ">=1.0.0 <2.0.0"
  },
  "dependencies": {
  },
  "consumedServices": {
    "status-bar": {
      "versions": {
        "^1.0.0": "consumeStatusBar"
      }
    },
    "package-2": {
      "versions": {
        "^0.0.0": "consumePackage2"
      }
    }
  }
}
```
package.json of second package:
```
{
  "name": "package-2",
  "main": "./lib/package-2",
  "version": "0.0.0",
  "description": "A short description of your package",
  "keywords": [
  ],
  "repository": "https://github.com/atom/package-2",
  "license": "MIT",
  "engines": {
    "atom": ">=1.0.0 <2.0.0"
  },
  "dependencies": {
  },
  "providedServices": {
    "package-2": {
      "description": "Does a useful thing",
      "versions": {
        "1.0.0": "providePackage2"
      }
    }
  }
}
```
I have this in main Coffe file of first package:
```
  consumeStatusBar: (statusBar) ->
    console.log 'consumeStatusBar'

  consumePackage2: (service) ->
    console.log 'consumePackage2'
```

**Comment by maxbrunsfeld** [comment]
Can you share the content of `lib/package-2`? Does it export a `providePackage2` method?

**Comment by fojtCz** [comment]
Both packages are generated in Package Generator and i changed just those four files

i have this in lib/package-2
```
  providePackage2: ->
    console.log 'providePackage2'
```

**Comment by maxbrunsfeld** [comment]
You provide an incompatible version of the `package-2` service in your package. In your `consumedServices` of `package-1`, you specify the version range `^0.0.0`, but in the `providedServices` section of `package-2`, you provide version `1.0.0`.

**Comment by fojtCz** [comment]
Thanks. I changed version number, but still having same problem.

**Comment by thomasjo** [comment]
> Thanks. I changed version number, but still having same problem.

Just to be sure, you changed the service specification under the `versions` key right? In other words, it should look like this:

``` javascript
"consumedServices": {
    // ...
    "package-2": {
      "versions": {
        "^1.0.0": "consumePackage2"
      }
    }
  }
}
```

In addition, to rule out other issues, `console.log 'consumeStatusBar'` is executed right?

**Comment by fojtCz** [comment]
- yes, i have this ```"^1.0.0": "consumePackage2"``` under the ```versions```
- ```console.log 'providePackage2'``` and ```console.log 'consumeStatusBar'``` are executed, but ```console.log 'consumePackage2'``` is not

**Comment by maxbrunsfeld** [comment]
I believe it's because `providePackage2` doesn't return anything. Try returning an object from that function.

**Comment by fojtCz** [comment]
thanks guys, finally it's working

solution is this:
```
  providePackage2: ->
    something: @returnThis()

  returnThis: ->
    console.log 'providePackage2'
```
