### ISSUE TITLE
Dialog for read-only files does not go away on Esc

### ISSUE THREAD

**Issue by artagnon** [atom/atom#9017]
<img width="497" alt="screen shot 2015-10-01 at 3 29 20 pm" src="https://cloud.githubusercontent.com/assets/37226/10231529/4ca32270-6851-11e5-9c8c-d851d34b93d3.png">

There seems to be some focus issue -- RET or Esc doesn't act on the dialog.

**Comment by benogle** [comment]
cc @zcbenz
