### ISSUE TITLE
Can't catch unhandled promise rejection

### ISSUE THREAD

**Issue by scv119** [atom/atom#9019]
Since Atom 1.0.18, we can't use

``` js
process.on('unhandledRejection', ...)
```

to catch unhandled rejections.

How to reproduce: in console of latest Atom build, type in 

``` js
setTimeout(function(){Promise.reject(1)}, 100)
```

And verified we get following errors:
![screen shot 2015-10-01 at 1 34 45 pm](https://cloud.githubusercontent.com/assets/837180/10233100/61e53f20-6841-11e5-8942-840cb4a3c90a.png)
whereas It is supposed be something like 
`'Unhandled promise rejection %o with error: %o', promise, error)``
according to https://github.com/atom/atom/blob/0a67cb97298eadd16a1d2fae91f9c40566cb879b/static/index.js#L13

**Comment by 50Wliu** [comment]
Reproduced on Atom 1.0.19, Windows 10 x64.

**Comment by scv119** [comment]
cc @maxbrunsfeld as we are losing track of unhandled promises.
