### ISSUE TITLE
Windows Installer icon broken in Win 7

### ISSUE THREAD

**Issue by giyyapan** [atom/atom#9021]
I downloaded and run the latest atom installer (v1.0.19) from official site, and the task bar icon is broken.
![image](https://cloud.githubusercontent.com/assets/3479453/10239517/5fc9aed6-6901-11e5-9fe1-3b6be8d89be2.png)

Let't me know if there's more information I can provide.

**Comment by damieng** [comment]
This was likely caused by the auto-update process. Atom 1.7.0 includes fixes to address that.
