### ISSUE TITLE
racer.rustSrcPath is not set in your config.

### ISSUE THREAD

**Issue by zosob** [atom/atom#9036]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: Atom Core

### Stack Trace

racer.rustSrcPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
     -1:47.2.0 application:new-file (atom-pane.pane.active)
     -1:45.3.0 grammar-selector:show (atom-text-editor.editor)
  5x -1:39.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:37.6.0 grammar-selector:show (atom-text-editor.editor)
     -1:13.4.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:08.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:03.8.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-csharp"
    ]
  },
  "editor": {
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
language-rust, v0.4.5
racer, v0.17.2
scheme-syntax, v0.4.0

# Dev
No dev packages
```

**Comment by wldcordeiro** [comment]
This looks pretty self-explanatory, you didn't set your rustSrcPath for racer to find.

**Comment by izuzak** [comment]
Yeah, I agree with @wldcordeiro. If you did set that config, then this seems like a problem with https://github.com/edubkendo/atom-racer -- can you please re-open the issue there in that case? 

I think that the fact that Atom core is blamed for the exception is a different bug (see https://github.com/atom/notifications/issues/66), but the exception itself seems related to racer.
