### ISSUE TITLE
Updates consume disk space

### ISSUE THREAD

**Issue by lucastan** [atom/atom#9039]
A large number of updates are stored in ~/Library/Application Support/com.github.atom.ShipIt until you restart Atom.

The autoupdater keeps downloading updates without deleting the older ones, thereby consumin disk space up to 4 GB, as long as the updates keep coming in.  The updates are only deleted until the app is restarted. 

I suggest just keep the latest update. there is not a setting to disable autoupdate

**Comment by thomasjo** [comment]
Duplicate of #7061. Will be fixed once #8779 ships.

**Comment by adamkdean** [comment]
I am getting this and I'm on v1.1.0, is this still an issue, @thomasjo?
