### ISSUE TITLE
Atom serializes DisplayBuffer scroll position correctly but overwrites it when re-opening workspaces

### ISSUE THREAD

**Issue by tmunro** [atom/atom#9044]
Atom serializes the scroll position (`scrollTop` and `scrollLeft`) of each DisplayBuffer, but when you close a project / workspace and re-open it, it fails to restore the scroll position. This happens because the bounds check on `setScrollTop` doesn't have the correct data yet, and clamps every `scrollTop` value to 0:
https://github.com/atom/atom/blob/stable/src/display-buffer.coffee#L255

I'm not sure exactly what the fix should be:

* Delay applying scroll position until after the editor is attached and bounds are accurate.
* Apply the deserialized scroll position without a bounds check if the bounds are invalid.
* Do a third, better thing.

**Comment by as-cii** [comment]
@maxbrunsfeld: after switching to a logical `DisplayBuffer` we no longer serialize the absolute coordinates but we rather save a reference to a row and column. You can see the [relevant lines of code here](https://github.com/atom/atom/blob/master/src/text-editor-presenter.coffee#L776-L782).

When a window gets restored (and we have all the required information), we try to restore such logical scroll position: https://github.com/atom/atom/blob/master/src/text-editor-presenter.coffee#L1611-L1617.

Therefore, I'd say this should be working fine already in **master**. Are you observing a different behavior, @maxbrunsfeld?

**Comment by maxbrunsfeld** [comment]
No, I haven't actually observed this issue; I just thought it sounded like it might be affected by the logical coordinates PR.

@tmunro This should be fixed in the next release of Atom thanks to [a recent PR](https://github.com/atom/atom/pull/8905) by @as-cii.

**Comment by tmunro** [comment]
Sounds good. I'll prepare a release of my package that targets that version.
