### ISSUE TITLE
 Pasting with a newline in front adds last lines indentation to pasted one

### ISSUE THREAD

**Issue by hitodama** [atom/atom#9045]
Example ("-" are indentations, "\n" is a leading newline from the previous line):

```
\n
---copy me
```

```
---indented line <-- copied here, to an indented line
------copy me <-- will end up indented as such
---------copy me <-- when done again on above line
```

I expect:

```
\n
---copy me
```

```
---indented line <-- copied here, to an indented line
---copy me <-- should end up as such, not further indented
---copy me <-- when done again on above line
```

To reproduce, open a new (language independent) file and copy-paste as shown. I am not sure this works in all other languages (it does in C), because I don't know the extend of their potential interference. (But I guess so basic rule (regex?) is broken.)

I typically turn of all indentation management but in this case **it seems to happen regardless of the options** (Auto Indent, Indent on Paste, Normalize Indent on Paste) set. In my opinion, **it should (almost) never happen**, because we don't want to indent most expressions in programming, unless they are scoped. Likewise, for texts it makes no sense (to me).

So:
1) For auto indentation this seems wrong, the indentation should not increase.
2) For "Indent On Paste" (or any other indent options) set to false, it is a **bug**, because the indentation should never be touched at all.

Infos: Linux, atom 1.0.0, also tested with git repo version 1.2.0-dev (commit 4b507be99769a38e0b8e9b26a950fc408951f986)

**Comment by hitodama** [comment]
I may have spoken to soon, the issue still exist in C as well. Just try pasting around with newlines in front and different (lower levels of) indentations as seen above. The indentation will change in an unwanted manner, regardless of options (but potentially differently).

**Comment by oseiskar** [comment]
+1 for "bug" because this happens when all auto-indenting options are turned off.
Tested on Linux (Debian) with v. 1.3.1.

**Comment by brentshermana** [comment]
hitodama, I've solved this issue [here](https://github.com/atom/atom/pull/11267). Please help me test my code on Windows so we can get this pull request accepted!

**Comment by pauloschilling** [comment]
Same problem here, and that's really annoying. =/

**Comment by Kzone272** [comment]
How has something as simple as copying and pasting code in an editor as popular as Atom been broken for over a year?

I'm starting to regret the switch from Sublime.

**Comment by patstew** [comment]
I've had another go at fixing this - see this package: https://atom.io/packages/fix-indent-on-paste
It would be useful to get feedback on whether that package works as people expect - if so I'll update PR #12793 with the same code
