### ISSUE TITLE
Close tab: save changes dialog: accept keypress "Y"/"N"

### ISSUE THREAD

**Issue by stijnsanders** [atom/atom#9046]
When closing and not needing to store the changes made, I've trained muscle memory to do <kbd>Ctrl+F4</kbd> and then <kbd>N</kbd>, since this will close the (sub-)window and select the 'don't save' option from any 'Save changes first?' dialog with most editors. Except Atom. I've noticed the dialogs were modified to default Windows styling in a recent version, but still don't accept my pressing <kbd>N</kbd>. (On Windows it's typically done by writing `&` in the button labels, e.g. `Do&n't save changes`.
I'm on version 1.0.19 on Windows.

**Comment by oh-ren** [comment]
The same issue is discussed here: #2928.
@stijnsanders <kbd>Ctrl</kbd> + <kbd>W</kbd> is more convenient btw (when applicable).. ;)

**Comment by mnquintana** [comment]
Thanks @oh-ren! Closing this out in favor of #2928.
