### ISSUE TITLE
Dependency without permissive license: spdx-exceptions

### ISSUE THREAD

**Issue by smashwilson** [atom/atom#9050]
I'm currently seeing a check-licenses failure on master, for (ironically) spdx-exceptions:

```
Running "check-licenses" task
Found dependencies without permissive licenses:
spdx-exceptions@1.0.3
  License: CC-BY-3.0
  Repository: git+https://github.com/kemitchell/spdx-exceptions.json
```

At first glance, I suspect that this is related to kemitchell/spdx-exceptions.json#1.

**Comment by mnquintana** [comment]
@kevinsawicki @nathansobo Can we add CC-BY as a permissive license [here](https://github.com/atom/legal-eagle/blob/master/src/legal-eagle.coffee#L206)? [The license](https://creativecommons.org/licenses/by/2.0/) only requires attribution, and is otherwise completely permissive.

**Comment by nathansobo** [comment]
Gonna defer to @kevinsawicki on this one, but probably.

**Comment by kevinsawicki** [comment]
Yup, fixing now...

**Comment by smashwilson** [comment]
:sparkles: :bow:
