### ISSUE TITLE
Rename dialog for a long path does not show the file

### ISSUE THREAD

**Issue by oxo42** [atom/atom#9057]
When trying to rename a file `environments\production\modules\ltuk\files\users\oxle019\oxle019.bash_profile` the rename dialog shows up to the end of the first `oxle019`.

![image](https://cloud.githubusercontent.com/assets/572079/10305889/07266982-6c1b-11e5-91ff-57a4664b224a.png)

It would make more sense to have the text box scrolled to the end, so you can see the file that has been highlighted.

**Comment by izuzak** [comment]
This issue was moved to atom/tree-view#592
