### ISSUE TITLE
setTimeout behavior in specs

### ISSUE THREAD

**Issue by mcolyer** [atom/atom#906]
We should document what it is, because I didn't know we changed how things work.

**Comment by mauricioszabo** [comment]
Why, by default, setTimeout is spied on Atom? Isn't it counter-intuitive? I have wasted three hours of work to find out that Atom was spying setTimeout in the specs of my package. Even more, it only spies setTimeout, not setInterval, so for a **lot** of time I was searching for a bug in my code...
