### ISSUE TITLE
PHP isn't syntax highlighted when mixed with HTML in a .php

### ISSUE THREAD

**Issue by ircer** [atom/atom#9061]
![capture](https://cloud.githubusercontent.com/assets/8420596/10310152/62860e6e-6c38-11e5-856e-60defa764420.PNG)

Is this intended behavior as it looks odd?

**Comment by izuzak** [comment]
Thanks for the report. I think this problem is covered by some existing issues, for example https://github.com/atom/atom/issues/2734 and https://github.com/atom/language-php/issues/48 so I'm going to close this. Let me know if I misunderstood your report, though.
