### ISSUE TITLE
Reordering tabs is VERY laggy

### ISSUE THREAD

**Issue by gsklee** [atom/atom#9066]
Reordering tabs with drag-n-drop has become VERY laggy since Atom hits v1.x... I recall it used to work smoothly in v0.x.

**Comment by izuzak** [comment]
Can you share [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) and try following the [debugging guide](https://atom.io/docs/latest/hacking-atom-debugging) and see if that helps?

**Comment by izuzak** [comment]
Also, please re-open this on the issue tracker for the Tabs package with more information:

https://github.com/atom/tabs

Thanks!
