### ISSUE TITLE
Can't open big XML file with size ~2gb

### ISSUE THREAD

**Issue by Hronom** [atom/atom#9068]
Hello everyone!

I start to use Atom and looks like in discussions in another issues the problem with big files was solved?

Now I try to open big XML file that has size ~2gb.
Then I open this file Atom show me popup window that he can hang for a while, I accept this, and after that - Atom crashed. 

Here is the Ctrl+C of crash window:
```
[Window Title]
Atom

[Main Instruction]
The editor has crashed

[Content]
Please report this issue to https://github.com/atom/atom

[Close Window] [Reload] [Keep It Open]
```

 Here u can download this big file: [ruwiktionary-latest-pages-articles.xml](http://dumps.wikimedia.org/ruwiktionary/latest/ruwiktionary-latest-pages-articles.xml.bz2) 

I use stock version of Atom 1.0.19 without any additional extensions.
My OS: win10 x64, 16gb RAM

**Comment by wldcordeiro** [comment]
I'm pretty sure Atom has a max file size of 4-5 MB, not sure the specific number but it's a lot lower than 2 GB.

**Comment by Announcement** [comment]
use vim op

**Comment by Hronom** [comment]
It's will be good if Atom can read end edit file "partially", without this I can't use Atom as main editor. This feature helps me use Atom for all my work.

So after fast search/reading issues looks like problem not solved after alot of discussions... so what is the current status of this?

**Comment by mehcode** [comment]
I hope that this is a joke/troll/something. You can't seriously be asking about editing a 2 GiB _anything_ file _by hand_. I feel for you.

@Hronom If you do need to modify this XML file manually (and it isn't the database for a misguided application) then you should use a XML focused editor such as [Oxygen](http://www.oxygenxml.com/xml_editor/tree_editor.html). Technically a package could be written for atom that would do something similar (and still work at huge sizes) but there just isn't the demand for this kind of editing at the moment for someone to try to write a package for it.

**Comment by Hronom** [comment]
@mehcode So looks like on this [issue](https://github.com/atom/atom/issues/307) "demand for this kind of editing" is available. Of course, I can use for editing pay editors like [EmEditor](https://www.emeditor.com/).

So I try ask about this feature after I found [issue](https://github.com/atom/atom/issues/307) that looks like solved, so I try to open big file and nothing happens...

**Comment by mnquintana** [comment]
Thanks for the report! This looks similar to https://github.com/atom/atom/issues/7583 - closing in favor of that issue.
