### ISSUE TITLE
style method calls (generated method names not wrapped in span)

### ISSUE THREAD

**Issue by arabsight** [atom/atom#9074]
Hi, I'm trying to style method calls in a syntax theme, but method names are not wrapped in any elements.

``` js
Object.keys().filter();
```

the line above gives me the following html (in dev tools):

``` html
<span class="source js">
    <span class="support class js">Object</span>
    <span class="meta delimiter method period js">.</span>keys
    <span class="meta brace round js">(</span>
    <span class="meta brace round js">)</span>
    <span class="meta delimiter method period js">.</span>filter
    <span class="meta brace round js">(</span>
    <span class="meta brace round js">)</span>
    <span class="punctuation terminator statement js">;</span>
</span>
```

but when I tried the atom/highlights package it gave me this (I thought atom uses that package), everything is wrapped in span, at least I can style it this way.:

``` html
<span class="source js">
    <span class="support class js">
        <span>Object</span>
    </span>
    <span class="meta delimiter method period js">
        <span>.</span>
    </span>
    <span>keys</span>
    <span class="meta brace round js">
        <span>(</span>
        <span>)</span>
    </span>
    <span class="punctuation terminator statement js">
        <span>;</span>
    </span>
...
</span>
```

sorry if this wasn't the appropriate place to put this.

**Comment by nisanth074** [comment]
@arabsight I faced the same issue when I tried to style method calls while creating a syntax theme. Could you find a solution?

**Comment by arabsight** [comment]
@nisanth074 unfortunately I couldn't. But I'm overriding the grammar in init.coffe:
```js
atom.workspace.observeTextEditors (editor) ->
    atom.grammars.loadGrammar('/path/to/grammar/javascript.cson', (err, grammar) ->
        editor.setGrammar(grammar)
    )
```
for javascript I'm using a modified copy of the grammar from atom/language-javascript package, I added this to the array of patterns:
```cson
{
        'captures':
            '1':
                'name': 'meta.delimiter.method.period.js'
            '2':
                'name': 'support.method.js'
            '3':
                'name': 'meta.brace.round.js'
        'comment': 'match method calls like: Sound.filter()'
        'match': '(\\.)\\s*([a-zA-Z_$][\\w$]*)\\s*(\\()\\s*'
    }
```

**Comment by samcv** [comment]
This is really a problem with how atom creates the html right? There is another repository for reporting bugs with the language-javascript package. I'm not totally sure but I think I ran into this problem with the grammar I am maintaining right now for Perl 6. Regardless, would like to see some response from people who know more about Atom what the reason for this is.

I just converted the documentation site for Perl 6 to use highlights and the same grammar I have been working on for Atom: https://github.com/perl6/atom-language-perl6

Would like to know why they format them differently, since this could also cause possible weirdness in how things might display on the site vs in Atom.

**Comment by 50Wliu** [comment]
language-javascript now tokenizes method calls, so this issue has been fixed.

@samcv No, this is not a problem with how Atom creates the HTML.  Language packages need to tokenize everything correctly in order for the generated HTML to be correct.  In the above example, language-javascript wasn't tokenizing method calls at all, so it wasn't assigned any classes in the HTML.

**Comment by samcv** [comment]
Okay thanks for the clarification.
