### ISSUE TITLE
Toggle a modal panel won't work if use command palette

### ISSUE THREAD

**Issue by cheunghy** [atom/atom#9077]
To reproduce this bug:
1. Generate a new package with `package-generator:generate-package` named anything
2. use command palette to run `new-package-name:toggle`, the modal panel shows
3. use command palette to run the toggle command again, the same modal panel shows again
4. use `ctrl-alt-o`, the two modal panel hide.

Toggle a modal panel is working when using shortcut key, but not work when using command palette.

**Comment by cheunghy** [comment]
If it's not bound to any command, open command palette and press ESC will dismiss the modal panel, too.

**Comment by izuzak** [comment]
@cheunghy I think you're describing the behavior reported in https://github.com/atom/package-generator/issues/22. Seem my comment here for an explanation: https://github.com/atom/package-generator/issues/22#issuecomment-118376647. Let me know if I misunderstood your question.
