### ISSUE TITLE
Bad cursor positioning when mixing RTL and LTR characters

### ISSUE THREAD

**Issue by as-cii** [atom/atom#9078]
Using RTL characters only works just fine as of the latest Atom version:

![arabic](https://cloud.githubusercontent.com/assets/482957/10359927/1b30b5a8-6d9d-11e5-8b81-7c195c18c69e.gif)

However, as soon as we add LTR characters _before_ the RTL ones, Atom won't position the cursor _inside_ the RTL text. The following does in fact work just fine:

```
اثر کارآزمودگی test test
```

Whereas the snippet below does not:

```
test test اثر کارآزمودگی 
```

With the new character measurement mechanism we now degrade gracefully, but the cursor can only be placed before and after the arabic text. This _seems_ like a limitation in the `Range` API which gets confused when mixing the two: I think this kinda makes sense 'cause I believe that, in order to provide a full RTL editing experience, we should need to go beyond character measurement.

/cc: @nathansobo @izuzak

**Comment by Eschon** [comment]
:+1: 

I have similar problems with code that translates arabic number symbols:
![rtlltr](https://cloud.githubusercontent.com/assets/11647830/10487272/69f4305c-7293-11e5-9ecd-cbd2f04f5e76.gif)

**Comment by ihabovich** [comment]
That is completely annoying for any developer. Hope it get fixed soon. :(

**Comment by elshahat** [comment]
Any updates regarding this issue???

**Comment by bentalgad** [comment]
Please fix it :)

**Comment by salehmosleh** [comment]
I have same problem
Please fix this problem
