### ISSUE TITLE
Retina & Non-retina redraw issue

### ISSUE THREAD

**Issue by zslabs** [atom/atom#9084]
When waking up my Mac (Retina) that is hooked up to a non-retina external display, the Atom editor only shows about 25% of itself with the rest of the app blank/white. What I normally have to do is drag the editor from my non-retina to the retina, which fixes the issue and then back over to the non-retina display.

**Comment by mnquintana** [comment]
Thanks for the report! This looks like a duplicate of https://github.com/atom/atom/issues/8847 – please subscribe there for updates.

**Comment by zslabs** [comment]
Thanks for pointing that out @mnquintana !
