### ISSUE TITLE
Atom hangs on Mac OS el capitan

### ISSUE THREAD

**Issue by harrybabu** [atom/atom#9086]
Running Mac OS el capitan. Initial boot is very slow (i5 processor with 8GB RAM) and when i navigate to Settings-->Themes view the whole app crashes and the app prompts me to force quit. Restarting app/Force quitting not solving issue.

P.S. I have installed latest version of atom + nuclide plugin.

<img width="798" alt="screen shot 2015-10-08 at 8 30 31 pm" src="https://cloud.githubusercontent.com/assets/2870584/10370242/92494fac-6dfb-11e5-97dd-bbec6703fe8d.png">

**Comment by mnquintana** [comment]
Can you try quitting Atom completely and opening it in safe mode (`atom --safe`), and see if you can reproduce this?

**Comment by dawidxt** [comment]
@harrybabu I am using Atom also on El Capitan, and it works just perfectly. It's fast and 0 problematic. Perhaps there is something wrong with plugin(s) You're using.

**Comment by darkn3rd** [comment]
I have it crashing consistently on Yosemite.

**Comment by mgoffin** [comment]
I had to nuke my `~/.atom` directory in order for it to open normally again. Trying to install Nuclide is causing my fans to freak out and the entire UI to slow to a crawl.

**Comment by hkboy** [comment]
I have just downloaded Atom on my Mac mini 2011 with the newest Capitan. It crashes literally when I boot the program.

**Comment by Shashaness** [comment]
Atom is crashing my entire system since upgrade to El Capitan. It took me while to figure out what is going on as the crashes seemed completely random. But than I realized they are only happening when I am working in Atom. 

While I am working, Atom first becomes completely unresponsive, and keeps the keyboard focus. Then, the mouse locks up, and eventually either the system reboots, or I have use the power button to hard boot.

I deleted the .atom folder form my home directory in hopes that it would help.

This morning as soon as I launched Atom... kaboom! the entire system rebooted. 

Like I said at first I though I was having a memory or disk issue, but this is ONLY happening when I launch/work in Atom.

**Comment by Shashaness** [comment]
I just downloaded the latest Beta Version... Same thing. I've been working with my computer all morning no issues, as soon as I open Atom, I all but scrolled the file, and same thing.. first keyboard locked up, then mouse froze and eventually the system rebooted.

Let me know if there is anything specific I can do or logs you would like to see.

**Comment by bowersjc** [comment]
Same thing here. Atom was working fine a week ago. Installed nuclide package. Now hangs so badly I can't even get into an editor.

**Comment by jeffeoff** [comment]
The issue described happens for me in El Capitan, but only when I'm editing via sudo from command line, example: `sudo atom /etc/hosts`

**Comment by alvarogois** [comment]
I'm having the same problem with Yosemite. Not hanging but full of lags (that seem to extend to Chrome), it renders it unusable. 

It's the first time I have this issues with Atom, started a few days ago.

**Comment by jeffeoff** [comment]
The issue I was experiencing with Atom locking after sudo in El Capitan is no longer occurring in the latest updated version of Atom.

**Comment by dwehrmann** [comment]
I am having the same issue with El Capitan and Atom v. 1.2.4: After a while the complete system becomes unresponsive, getting worse until locking up completely after half an hour or so. This goes on until I have to do a hard reboot.

**Comment by benogle** [comment]
Everyone who still has hanging problems, please start atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode). It runs the app with no 3rd party packages. Let us know if it is still an issue, and let us know exactly in which circumstances there is hanging (is it slow in typing? Slow when autocomplete shows up? tab switching? Something else? What kind of file are you in? is it huge? etc).

If you are going to add a 'me too' comment, please use safe mode, and add information about what you are doing when it happens, and exactly where it happens.

**Comment by bigxiang** [comment]
:+1: to nuke `~/.atom` folder.

**Comment by McCloudA** [comment]
I deleted my ~/.atom directory, and it worked fine (I'm using El Capitan). I then began installing my 3rd party plugins one at a time. When I installed the 'minimap-pigments' package, the freezing symptoms returned.

**Comment by andrefreitas** [comment]
Same symptom here. I remove my ~/.atom folder and is still hanging in El Capitan.

**Comment by Adriano72** [comment]
It freezes every now and then on my Mac too..  :(

**Comment by bowersjc** [comment]
Final Update from me: I ended up having to completely uninstall and reinstall the most current Atom with no packages. Nuclide seems to have been the problem and I've been running for several weeks now with no issues on a vanilla Atom installation.

**Comment by esetnik** [comment]
Me too

**Comment by godspeedelbow** [comment]
I have the same issue. It would be great if there would be some error log we could check somewhere so we could see *post mortem* why Atom died.

Turning off (and on) packages is a one-off fix which is only going to fix your current combination of package versions. As soon as there's a package update that crashes Atom, you're required to go through the whole process again.

**Comment by andrefreitas** [comment]
This issue is actually very subjective. I had Atom hanging from a lot of reasons that are not necessarily the same as the one from the OP. Issues that made my Atom hanging:

- Big files;
- There was a bug with having multiple files with the same name;
- Entropy of installing Packages and configuring them;
- Misconfigured linters.

The more frustrating part is trying to make the scenario reproducible to others. Therefore, I believe atom team cannot do much more about this issue than just wait for more information.

**Comment by godspeedelbow** [comment]
@andrefreitas how are we to provide more information when there is no means to provide it? Or am I missing some hidden reporting feature?

**Comment by andrefreitas** [comment]
@godspeedelbow yes, I pointed the frustration of not having means to give more information. That's also why this issue is subjective :)

**Comment by godspeedelbow** [comment]
@andrefreitas Ah yes, what I was replying to is "Therefore, I believe atom team cannot do much more about this issue than just wait for more information." I think a starting point would be is to give us the tools to get information out of Atom, so as community we can help improve the product. Now, we're collectively stuck in a chicken and egg problem.

**Comment by Geoide** [comment]
Same problem with El Capitan. Very slow each 5-10 min. and intesive disk E/S

**Comment by iwazaru** [comment]
I also have this problem since today. Atom 1.6.0 suddenly hangs out for a dozens seconds. I have updated OSX from Yosemite to El Capitan a week ago. Launching atom with --safe did not help. Removing my .atom folder did not help either.

**Comment by danpalmer** [comment]
Ping on this. Atom is hanging every ~5-10 mins for ~5-30 seconds. It's definitely not my system being slow, everything is working fine, then suddenly Atom completely stops for a bit. El Capitan, latest release. Atom 1.6.2.

**Comment by iwazaru** [comment]
Completely uninstalling Atom ([as described here](https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084)) seems to have fixed the problem for me.

**Comment by ankur2002** [comment]
It looks like the Atom Helper process is hogging the CPU I see it spiking to 103.6% and I am running it on Sierra 10.12.5. And I have not even started working on Atom yet. Why is the Atom Helper process hogging so much of the CPU even when it is idle?

**Comment by ankur2002** [comment]
So I noticed that atom was starting up a git process owned by atom helper. I disabled the two git system packages git-diff and github. So far so good let's see if that was the main issue here.

**Comment by Bsangston** [comment]
@ankur2002 I'm having the exact same issue on El Capitan 10.11.6, disabling the git-diff and github packages seems to have resolved the issue.

**Comment by ankur2002** [comment]
Great now if we could only get someone to please fix the issue with these two packages.

**Comment by huntersgordon** [comment]
@Bsangston 
```
System.out.println("thank you so much");
```
