### ISSUE TITLE
cursor blocked

### ISSUE THREAD

**Issue by unluisco** [atom/atom#9092]
This days, when I open any files, I have a different cursor at the beginning, and does not allow me to write until I press certain specific keys:

![untitled - users unluisco dropbox unluisco pruebas diseno sensible - atom 2015-10-08 17-51-21](https://cloud.githubusercontent.com/assets/6332263/10382338/943d70c6-6de8-11e5-82ec-99bb9bf374ea.png)

**Comment by benogle** [comment]
Do you have vim-mode package installed and enabled?

**Comment by unluisco** [comment]
Oh!
Yes, just today I installed it, I forgot it. I checked the settings that package and you're all in order

Thanks, very thanks.
