### ISSUE TITLE
Not-quite-clicking on the path generates “copied” feedback; doesn't follow through

### ISSUE THREAD

**Issue by steveluscher** [atom/atom#9100]
# Repro

1. Hover your mouse just outside the pathname at bottom left
2. Click; note that a tooltip appears saying the path has been copied to the clipboard
3. Paste.

# Expected

The path is pasted.

# Actual

The path was never actually copied.

*Note: Hovering over the path such that the underline appears yields the desired behavior.*

**Comment by izuzak** [comment]
This issue was moved to atom/status-bar#106
