### ISSUE TITLE
Please add option to not use VCS

### ISSUE THREAD

**Issue by haibison** [atom/atom#9102]
Please add option to not use VCS, such as Git.

For instance, I have an old machine, I work on some medium projects. `git status` often takes up to 3 seconds to finish. So It would be great to add option to not use VCS, not at all.

Thank you.

**Comment by izuzak** [comment]
@haibison I don't understand your feedback/request. Can you explain more clearly what exactly seems to be the problem (in a step-by-step way) and where exactly in Atom you'd like to disable Git integration?

**Comment by haibison** [comment]
@izuzak Thanks for your reply.

I'm sorry that I'm not sure about VCS integration.

It was because of package `git-diff`. When it was enabled, Atom was very slow, due to it checking for differences and marking them in the editor.

I just disabled that package and it seems Atom is working normally.

But just in case if Atom has features with VCS integration, it would be great if you can have options to disable those features. For example, Android Studio is an IDE for Android projects, I disable its Git integration to gain performance.

Thanks,

**Comment by izuzak** [comment]
Thanks for explaining, @haibison. As you already figured out -- you can disable features by disabling packages. If you run into any other specific features causing (performance) problems -- let us know.
