### ISSUE TITLE
Visible .DS_Store in tree-menu of project files

### ISSUE THREAD

**Issue by dawidxt** [atom/atom#9105]
Like in the title. I can't hide the Mac OS X default config file in every location of my project - I see the .DS_Store. It would be nice, if the Atom was not showing them at all.

![zrzut ekranu 2015-10-10 o 20 33 38](https://cloud.githubusercontent.com/assets/13783466/10412703/40f1e454-6f8e-11e5-9b96-5c2e48c8d763.png)

**Comment by arcticicestudio** [comment]
Atom should normally ignore them by default 
![github-atom-atom-issue-9105-defaults](https://cloud.githubusercontent.com/assets/7836623/10412730/76804e3e-6f8f-11e5-9f46-ddae891a8fb2.png)

Does it work if you add it manually?
![github-atom-atom-issue-9105-customs](https://cloud.githubusercontent.com/assets/7836623/10412734/a104239c-6f8f-11e5-9024-5e8c48ab3e0c.png)

**Comment by dawidxt** [comment]
Nope, it does not work either. 
I made the changes, and restarted the app. .DS_Store still remains visible.
![zrzut ekranu 2015-10-10 o 23 29 21](https://cloud.githubusercontent.com/assets/13783466/10413366/e4e08cba-6fa6-11e5-8fd0-5d26dce34d26.png)

**Comment by mnquintana** [comment]
What version of Atom are you using? Can you try quitting Atom completely and restarting it in safe mode (`atom --safe`) and see if you can reproduce this? Those files should definitely at least be grayed out.

**Comment by izuzak** [comment]
@dawidxt Have you enabled the "Hide Ignored Names" config setting under Packages > Tree View? The tree view has config setting of its own:

<img width="428" alt="screen shot 2015-10-11 at 10 05 07" src="https://cloud.githubusercontent.com/assets/38924/10415930/b9b9842a-6fff-11e5-8ce1-3bfb352c76f9.png">

**Comment by dawidxt** [comment]
@izuzak yup, that was the case. It was not checked by default (why?). After checking it everything is great. Thank You a lot :)
