### ISSUE TITLE
Settings → Packages sometimes doesn't load

### ISSUE THREAD

**Issue by ircer** [atom/atom#9119]
This has happened a couple of times but I've passed it off.

I want to install the `remote-edit` package now, which I am looking at on the Atom website but when I put that package name in to Atom it comes up with 0 results.

I have Internet etc.

Edit: Err, does that mean that I'm searching installed packages, since the text box is under that heading? Where are the other text boxes to search for something that I want to install now? *Confused*

![capture](https://cloud.githubusercontent.com/assets/8420596/10428498/c46c2996-70e9-11e5-9c20-d229b0c32d7c.PNG)

**Comment by peduxe** [comment]
Control + Shift + I will open the chromium devtools, do you see any exception in the console?

**Comment by izuzak** [comment]
Packages should be installed from the "Install" panel, not the "Packages" panel (which is what you're doing). The "Packages" panel lists only packages which are already installed.

Let me know if this doesn't resolve the problem for you.
