### ISSUE TITLE
Allow a new Decoration type to represent ticks on the vertical scroll bar

### ISSUE THREAD

**Issue by patrys** [atom/atom#9120]
PyCharm does this by default for linter warnings and errors, Chrome uses it to show search results. It makes it easy to look at the scroll bar and see whether certain parts of the file may be of interest.

**Comment by 50Wliu** [comment]
Refs atom/find-and-replace#529.

**Comment by Aakash1312** [comment]
For this issue, I have been working on this package
https://atom.io/packages/scroll-searcher
