### ISSUE TITLE
Folding html tags not working if there the indent is not proper

### ISSUE THREAD

**Issue by ranji2612** [atom/atom#9124]
If the indent is proper, the folding of div/ any other tag works fine. However if there is any indent issue its folding the contents until the point of error.
It detects the starting and ending of the tag properly, but not the folding. I have attached the images which shows the behaviour.
1. Detecting the ends of tag  - *works fine
<img width="1053" alt="screen shot 2015-10-12 at 2 10 15 pm" src="https://cloud.githubusercontent.com/assets/5123183/10435114/ffa0e842-70eb-11e5-9cc3-905a5fd871fa.png">
2. Proper indent - Folding works
<img width="710" alt="screen shot 2015-10-12 at 2 10 34 pm" src="https://cloud.githubusercontent.com/assets/5123183/10435115/ffa4f1a8-70eb-11e5-89ff-59437fe2ada4.png">
3. Intentional Indent change at Canvas tag
<img width="1003" alt="screen shot 2015-10-12 at 2 10 52 pm" src="https://cloud.githubusercontent.com/assets/5123183/10435117/ffa945fa-70eb-11e5-8c7b-5714a42b8ab8.png">
4.Folding is done only until the point of error which is the canvas tag
<img width="781" alt="screen shot 2015-10-12 at 2 11 03 pm" src="https://cloud.githubusercontent.com/assets/5123183/10435116/ffa5ef18-70eb-11e5-8210-09dc5172b781.png">

**Comment by 50Wliu** [comment]
Folding in Atom is currently indentation-based: please see #3442 for more details.
