### ISSUE TITLE
"Preferred Line Length" line doesn't get redrawn when changing the Font Size from a Preferences tab in the current window

### ISSUE THREAD

**Issue by technicalpickles** [atom/atom#9125]
It seems that if you change the font size in a window, either using Settings -> Preferences -> Font Size or zoom in / zoom out, the 'line' drawn for the Preferred Line Length is not updated to take the new size into account. Consider this gif, where I have the text "the position of this question mark? it's column 35" and I set the preferred line length to 35:

![](http://f.cl.ly/items/1E2z1x3y2g1n3z3s0l3k/Screen%20Recording%202015-10-12%20at%2002.13%20PM.gif)

If I open up a new tab, the font size and preferred line length are correctly drawn. Interestingly, it seems that changing the Font Size from a *different window* redraws the Preferred Line Length window as expected:

![](http://f.cl.ly/items/2R3K0D3X1o180Q1w0n41/Screen%20Recording%202015-10-12%20at%2002.14%20PM.gif)

This was from Atom 1.0.19 running on Mac OS X 10.10.5. I didn't see any errors in the dev tools.

cc @mjstahl who was asking if anyone else had seen this behavior

**Comment by benogle** [comment]
cc @atom/feedback I feel like there was an issue for this somewhere else, but cant find it.

**Comment by technicalpickles** [comment]
I did search for "Preferred Line Length" and "Font Size", but wasn't able to find anything... so possible it was just described in another way.

**Comment by izuzak** [comment]
Possibly https://github.com/atom/wrap-guide/issues/25 ?

**Comment by benogle** [comment]
Closing as dupe. Sorry for the trouble
