### ISSUE TITLE
how to publish a styntax theme

### ISSUE THREAD

**Issue by Huaraz2** [atom/atom#9126]
Hi,

I have created my own syntax and I am almost done writing it all up/gettting it ready to publish but I do not know how to actually publish it.  Does anyone know how to do this please.

thanks

**Comment by thomasjo** [comment]
Follow the documentation for the "Word Count" package tutorial, specifically the "Publishing" section:
https://atom.io/docs/v1.0.19/hacking-atom-package-word-count#publishing

Have fun :smiley:

**Comment by Huaraz2** [comment]
Thanks for this @thomasjo
