### ISSUE TITLE
Loading bar with Progress

### ISSUE THREAD

**Issue by neOnSHiFT** [atom/atom#9128]
This is a serius problem for me
Really most of the time I download a small package and I always cancell it.
Because I feel it take a years to download that
The problem is We don't know the progress until the instalation process done, it just we have to wait and wait without knowing what's happening in the background.
I download a  package that under 100KB (vim-mode in my case), but I noticed why I'm downloading more than 10MB?
Is it downloading another package ,updating atom or something?
Or Maybe you can show/hide console while downloading to see what's happening in the background

**Comment by maxbrunsfeld** [comment]
:+1: This is a very good point. Could you re-open this issue on the [settings-view](https://github.com/atom/settings-view/issues) package? That is the package that provides this UI.
