### ISSUE TITLE
Clicking on "CRLF" does not change line endings

### ISSUE THREAD

**Issue by rovf** [atom/atom#9129]
Atom 1.0.19 for Windows:

When I click on "CRLF" in the status bar, a small pop-up opens, which lets me choose between LF and CRLF, but even when I click on LF, the line ending style sticks to LF.

In this way, the editor is unusable, because many Unix-programs can not process textfiles with CRLF endings.

**Comment by maxbrunsfeld** [comment]
> but even when I click on LF, the line ending style sticks to LF.

So when you click `LF` in the pop-up menu, the line-endings should change to `LF`. Is this not what you are seeing?

**Comment by rovf** [comment]
On Tue, Oct 13, 2015, at 18:35, Max Brunsfeld wrote:
> > but even when I click on LF, the line ending style sticks to LF.
> 
> So when you click `LF` in the pop-up menu, the line-endings should change
> to `LF`. Is this not what you are seeing?

Exactly. However, I have narrowed down the bug a bit: This erroneous
behaviour occurs only, when the document is still "untitled". If I open
an existing document, the line ending style can be changed.

Aside from this, I find it pretty inconvenient to explicitly set the
line ending style for every document. By far the majority of our files
have LF endings, and it would make sense to have the possibility to
define this as a default value.

Ronald

**Comment by maxbrunsfeld** [comment]
@rovf I believe this has *just* been addressed, via https://github.com/atom/line-ending-selector/pull/7!

In the next release of Atom, there will be a new setting `line-ending-selector.defaultLineEnding` that you can set to either `LF`, `CRLF`, or `OS Default`.

**Comment by maxbrunsfeld** [comment]
@rovf After the next release, please let me know if this feature does not solve your problem, and we can reopen this issue.

**Comment by rovf** [comment]
On Wed, Oct 14, 2015, at 18:22, Max Brunsfeld wrote:
> @rovf I believe this has *just* been addressed, via
> https://github.com/atom/line-ending-selector/pull/7!
> 
> In the next release of Atom, there will be a new setting
> `line-ending-selector.defaultLineEnding` that you can set to either `LF`,
> `CRLF`, or `OS Default`.

I think we have two unrelated issues here:

- One is the (important) feature, that we want to control the default
line ending for new documents; this is addressed by pull request 7

- The other one is the bug, that we can not change the default line
ending of a "untitled" document. This is the one which was addressed by
my issue.

This means that even with pull request 7 implemented, I would still face
a problem when I want to create a new document with line endings which
are *different* from the default. I would have to save it first with the
default line ending, and only then I could change the endings.

Ronald
