### ISSUE TITLE
Project Find Results: matched strings are not jumped to correct lines

### ISSUE THREAD

**Issue by sparanoid** [atom/atom#9138]
How to reproduced:

- Search something in a project
- Click on one result which the file is not opened in Atom
- Always jumped to the end of the file

But if the file is already opened, everything works.

Demo:

![atom search bug](https://cloud.githubusercontent.com/assets/96356/10477792/b1f53386-728b-11e5-9e97-6c0343ce6310.gif)

**Comment by benogle** [comment]
cc @maxbrunsfeld @as-cii

**Comment by 50Wliu** [comment]
Duplicate of sindresorhus/atom-editorconfig#51, please subscribe there for updates.
