### ISSUE TITLE
Support \A regex anchor for matching beginning of string

### ISSUE THREAD

**Issue by alexchandel** [atom/atom#9146]
This is often useful in Find & Replace, and worked in ST. But it's also useful in grammar packages where special behavior is desired for the 1st line

**Comment by alexchandel** [comment]
This would also require correctly supporting `\Z`. At the moment `\A` and `\Z` just match `a` and `z`.

**Comment by 50Wliu** [comment]
@alexchandel Is this just for find-and-replace or also for grammar packages?  The two use different regex engines (the former uses the native JS regex, while grammars use Oniguruma, which is much more comprehensive).

**Comment by alexchandel** [comment]
`\A` matches the beginning of the document, `^` matches the beginning of the line, `$` matches the end of the line, `\Z` matches the end of the document (before an optional newline), and `\z` matches the absolute end of the document. When I last tried (admittedly a few months ago), `\A` didn't work in a grammar.

**Comment by 50Wliu** [comment]
If you can still reproduce it, would you mind reporting this to Oniguruma instead?  I don't think this is something that Atom can (reasonably) patch in.

**Comment by alexchandel** [comment]
Sure
