### ISSUE TITLE
ECMAScript 2015 "constant" chaining

### ISSUE THREAD

**Issue by jamen** [atom/atom#9149]
Hey, when using the`const` ECMAScript 2015 feature in a chain on a JavaScript document, the chained variable names aren't classified as "constant"s...

Take this code piece:

```javascript
const path = require('path'),
      fs = require('fs');
```
(Notice how GitHub does it too...  Lol)

Here is what it looks like in the editor:

![image](https://cloud.githubusercontent.com/assets/6251703/10494185/1eb045ca-7272-11e5-97bf-67ff87a6a8d3.png)

Despite this being valid way to define constants in JavaScript, Atom doesn't signify that as such...

When peaking in the HTML structure you see that the first keyword is classified as a constant:

![image](https://cloud.githubusercontent.com/assets/6251703/10494213/50e5ab34-7272-11e5-9a42-ba814c47c76e.png)

But the second keyword in the chain is not, and is simply loose, not classed as anything:

![image](https://cloud.githubusercontent.com/assets/6251703/10494255/7fa5ea9c-7272-11e5-85d3-a320b43a17d9.png)

Note that this also happens if you use more than two in the chains...  Only the first keyword is classified as a `"constant"`.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/language-javascript? Thanks!

**Comment by jamen** [comment]
https://github.com/atom/language-javascript/issues/240
