### ISSUE TITLE
tab closing order

### ISSUE THREAD

**Issue by jacobhamblin** [atom/atom#9151]
With three tabs open and the middle one active, closing the tab makes the tab on the left active, whereas in Chrome or Safari, closing the the current tab makes the tab to its right active.

Maybe it's an intentional decision and there's no issue, but it isn't expected behavior to me.

Atom 1.0.19
OS X Yosemite 10.10.5

**Comment by mnquintana** [comment]
This issue was moved to atom/tabs#217
