### ISSUE TITLE
Javascript Syntax highlighting emoji + url string issue

### ISSUE THREAD

**Issue by reggi** [atom/atom#9153]
String with any emoji and `http://` followed a character breaks syntax highliging. 

```js
var problemString = '💻 http://a'
```

I found this in the wild here 

https://github.com/erikras/react-redux-universal-hot-example/blob/master/api/api.js#L80

I have no clue what's happening here.

![screen shot 2015-10-15 at 3 17 30 am](https://cloud.githubusercontent.com/assets/296798/10507095/1a9c2e3e-72ec-11e5-8dff-6421a38bd262.png)
![screen shot 2015-10-15 at 3 13 06 am](https://cloud.githubusercontent.com/assets/296798/10507097/1ef30390-72ec-11e5-829e-093f4d69caea.png)

**Comment by reggi** [comment]
It doesn't seem specific to javacript. Because no matter what set the file to It still doesn't close this string.

**Comment by MethodGrab** [comment]
I have this problem as well (OSX 10.10.4 / Atom 1.0.19).
It seems like a weird edge case with certain emoji/string combinations. With the example string if you put a space before the final quote, the highlighting is fixed:

![image](https://cloud.githubusercontent.com/assets/2421069/10542624/762b8d0a-7411-11e5-8ca8-761f5edc4614.png)

```
// with space
var problemString = '💻 http://a '
function (  ) {}

// without space
var problemString = '💻 http://a'
function (  ) {}
```

**Comment by MethodGrab** [comment]
I think it's related to the JavaScript `length` of the emoji. I did some quick testing and 2 character emoji like `💻` (`'💻'.length === 2`) cause issues but single character emoji like `✅` (`'✅'.length === 1`) don't break the highlighting.

![image](https://cloud.githubusercontent.com/assets/2421069/10542802/a9363d0c-7412-11e5-88d5-c45da81830fc.png)

**Comment by 50Wliu** [comment]
Interesting how this doesn't break on Github, even though it uses the same language package.

**Comment by MethodGrab** [comment]
It also doesn't seem to affect Windows. I just tried it on Win 7 / Atom 1.0.19 and it's fine:

![image](https://cloud.githubusercontent.com/assets/2421069/10552926/1b6f4576-744f-11e5-8516-e86d8b4e70cc.png)

**Comment by methodbox** [comment]
I'm sorry but why the hell are you using emoji in JS? Is this part of ES6 I missed?

**Comment by reggi** [comment]
@methodbox Don't quote me on this but I think it's valid utf-8. 
@erikras is using it to log emojis to the teriminal and not as javascript variables.

**Comment by methodbox** [comment]
It may be valid utf-8 but it's being used in a string, so it should be Unicode.

If the JS engine/interpreter supports it in console, it will still display in console.

Note that Atom is based on Chromium. If Chromium won't display it in console, likely neither will Atom.

AFAIK, Unicode isn't interpreted in console in Chrome, so I wouldn't expect this to work.

**Comment by methodbox** [comment]
Actually on that note check it in the dev tools in Atom; it's the same as the Chrome/Chromium console. If it displays correctly there, it's your syntax highlighting rules, which you can just hack to identify emoji... Or use Unicode :) .

**Comment by nathansobo** [comment]
@50Wliu Seems very possible that we're relying on length somewhere in first-mate. It would be great if someone could open a PR with a failing test on that library if they can reproduce.

**Comment by MethodGrab** [comment]
PR added.

**Comment by 1st1** [comment]
We have a similar bug in MagicPython -- https://github.com/MagicStack/MagicPython/issues/15#issuecomment-149950804

Looks like this is a bug in the `oniguruma` library that `first-mate` uses.

**Comment by MethodGrab** [comment]
Thanks for fixing this, Atom 1.1.0 highlights correctly!

**Comment by nathansobo** [comment]
:+1: Thanks for getting it started.
