### ISSUE TITLE
Atom always opens keymap.cson on startup

### ISSUE THREAD

**Issue by rovf** [atom/atom#9155]
Atom 1.0.19 running on Windows 7

Steps to reproduce:

- Make sure all tabs are closed
- Terminate Atom (File/Exit)
- Start Atom

I would expect that no tab is open, but the tab keymap.cson is always opened.

**Comment by 1b8** [comment]
It's not happening for me. For me, it doesn't open any files. I'm also running Atom 1.0.19 on Windows 7.

**Comment by rovf** [comment]
On Fri, Oct 16, 2015, at 05:48, 1b8 wrote:
> It's not happening for me. For me, it doesn't open any files. I'm also
> running Atom 1.0.19 on Windows 7.

Maybe it depends on the history. At the first usage of Atom, I opened
the keymap file deliberately and closed Atom, without closing Atom
first. After this, this file kind of "sticks", i.e. even if I close the
keymap file explicitly, it's open again on the next start of Atom.

Is it possible to start Atom with "debug traces" switched on, so we can
see what is going on during startup?

Ronald

**Comment by benogle** [comment]
My assumption is that some package is failing to deserialize, causing the deserialization to fail and not overwrite an old state. Can you try starting atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by rovf** [comment]
On Thu, Oct 22, 2015, at 02:50, Ben Ogle wrote:
> My assumption is that some package is failing to deserialize, causing the
> deserialization to fail and not overwrite an old state. Can you try
> starting atom in [safe
> mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

No change.

BTW, if I do NOT close the keymap.cson file before exiting Atom, and
then start Atom again, I get TWO tabs with keymap.cson open.

Atom tries to reopen the files, which were open the last time it was
run, and it seems to reopen keymap.cson in addition. I wonder: Where
does Atom store the list of files to be opened on the next start? Maybe
it gets them from two different locations (INI-File,
Registry-Entry,....), and one of them is "broken" somehow.. 

In case you need it, here is the console output when starting and
shutting down Atom:

C:\Users\fisrona\AppData\Local\atom\app-1.0.19>atom.exe --safe

C:\Users\fisrona\AppData\Local\atom\app-1.0.19>App load time: 236ms
[8440:1022/132828:WARNING:accelerator_util.cc(185)] Invalid accelerator
token: command
[8440:1022/132828:WARNING:accelerator_util.cc(185)] Invalid accelerator
token: command
[8440:1022/132828:WARNING:accelerator_util.cc(185)] Invalid accelerator
token: command
[8440:1022/132828:WARNING:accelerator_util.cc(185)] Invalid accelerator
token: command
[8728:1022/132828:INFO:renderer_main.cc(200)] Renderer process started
[8440:1022/132828:WARNING:browser_accessibility_manager_win.cc(193)] Not
firing AX event because of no root_delegate or hwnd
[8440:1022/132828:WARNING:browser_accessibility_manager_win.cc(94)] Not
firing AX event because of no
hwnd
[8440:1022/132829:INFO:CONSOLE(46)] "Window load time: 1455ms", source:
file:///C:/Users/fisrona/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js
(46)
[8440:1022/132832:WARNING:browser_accessibility_manager_win.cc(193)] Not
firing AX event because of no root_delegate or hwnd
[5812:1022/133006:WARNING:raw_channel_win.cc(473)] WriteFile: Die Pipe
wird gerade geschlossen. (0xE8)
[5812:1022/133006:WARNING:channel.cc(549)] Failed to send message to ack
remove remote endpoint (local ID 1, remote ID 1)
[5812:1022/133006:WARNING:channel.cc(315)] RawChannel write error

**Comment by lorddevi** [comment]
Actually I am having this issue too. Although I can say my steps to produce the error were a bit different.

Namely, I tried to add an entry to my keymap.cson file that had a formatting issue. This gave me the error on Atom launch about not being able to load keymap.cson.

I then repaired the issue. After Re-Launching Atom after fixing this formatting issue the automatic opening of keymap.cson began.

I also have Atom launching a new tab for the same file on open if I do not close the tab for keymap.cson before quitting Atom.

Not sure how to repair this!

**Comment by derelk** [comment]
This is happening for me with Atom 1.3.2 on OS X 10.11.1.

**Comment by derelk** [comment]
Happened in safe mode as well. I was only able to fix it by manually deleting it from `initialPaths` in `~/.atom/storage/application.json`.

**Comment by lee-dohm** [comment]
For people encountering this:

1. Close all instances of Atom
1. Delete the `~/.atom/storage` directory
1. Launch Atom again

If that does not fix it, please open a new Issue with the following information:

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

Thanks!
