### ISSUE TITLE
The editor crashed when attempting to Install Packages

### ISSUE THREAD

**Issue by galpin** [atom/atom#9158]
I get the following error whenever I cilck on "Install" in the Settings pane.

I am on Windows 7 with v1.0.19.

Any ideas?

![image](https://cloud.githubusercontent.com/assets/485240/10518059/981cb8d6-7357-11e5-8610-2d0bf7577a42.png)

**Comment by Zireael07** [comment]
Are you behind a proxy?

**Comment by galpin** [comment]
Yes, I am on a corporate network.

**Comment by Zireael07** [comment]
Duplicate of #8465, then.

**Comment by 50Wliu** [comment]
Thanks, @Zireael07!
