### ISSUE TITLE
Clicking on Search results does not scroll to line

### ISSUE THREAD

**Issue by zslabs** [atom/atom#9159]
Hi all,
This used to work in previous versions, but searching in Atom and ultimately selecting the line within a file used to open the file and scroll you to that specific point in the file. It currently is shooting me to the end of the editor each time.

**Comment by 50Wliu** [comment]
Duplicate of sindresorhus/atom-editorconfig#51, please subscribe there for updates.

If you don't in fact have editor config installed, please comment here!

**Comment by zslabs** [comment]
Indeed I do, thanks for linking to that!
