### ISSUE TITLE
Snippets not working

### ISSUE THREAD

**Issue by Somebi** [atom/atom#9160]
v. 1.0.19 on Windows 7

```coffee
'.source.js':
  'console.log':
    'prefix': 'loggg'
    'body': 'console.dir($1)'
```

**Comment by Somebi** [comment]
btw atom starts very slowly, eating almost all my cpu O_o wtf

**Comment by 50Wliu** [comment]
@Somebi Is that the entirety of your `snippets.cson` file?  If not, can you paste the entire contents of it into a Gist and then link it here?  Thanks.

**Comment by Somebi** [comment]
https://gist.github.com/Somebi/830b05a2a06397d36d38

**Comment by 50Wliu** [comment]
Closing this since the comments on the Gist appear that the issue has been resolved.

@Somebi if you manage to reproduce this again please comment here :).
