### ISSUE TITLE
File content erased upon save when system ran out of disk space

### ISSUE THREAD

**Issue by tmaila** [atom/atom#9166]
# Description

If a disk containing a file being edited with Atom runs out of disk space, atom erases existing file content as well as edit buffer in memory upon attempt to save the file.
# Steps To Reproduce
1. Create a file with atom, add some content to it and save it to disk
2. Fill the disk with something so that you run out of disk space
3. Now in atom, modify the file you created in step 1.
4. Save the file again to store the modifications. As disk is full, atom fails to save the file but erases the existing file content upon save attempt. Atom then automatically refreshes the file content from disk, effectively erasing the file from both memory and disk upon save attempt. There is not way to recover the file content.
# Expected behavior

If there is no space on disk, the save operation should fail, the original file on disk should stay intact and most importantly the edit buffer in memory should stay intact so that the user can save the file to another disk with space
# System and Version Information

Atom 1.0.1.19
Windows 7 x64

**Comment by 50Wliu** [comment]
There is now an option to make a temporary backup before saving: #8140.

That being said, the save should probably be prevented in the first place like @tmaila said if there's not enough space.  /cc @nathansobo

**Comment by nathansobo** [comment]
> That being said, the save should probably be prevented in the first place like @tmaila said if there's not enough space.

We could cover 80% by just performing a check that there was sufficient space, though this would be subject to race conditions... we could find that there was enough space and then proceed to write, only to have the space consumed by another process in the meantime. Even so, it may be worth avoiding this when we can.

**Comment by iainhallam** [comment]
Is it possible to have Back Up Before Saving turned on by default? Have just had a user lose hours of work due to a crash in Atom while saving and we were astonished to find that it doesn't do atomic saves, but first discards the safe copy of the user's data.

**Comment by strarsis** [comment]
+1
Windows 10 x64.
File was emptied when trying to save.

**Comment by jeancroy** [comment]
How about a copy of the file that get saved every few editor changes ?
That copy would guard against atom crash or full os crash.

But relevant here,  that copy could also guard against file truncation trouble.
This would allow to overwrite the original file and thus avoid [atomic change issues](https://github.com/atom/atom/issues/3158#issuecomment-124225148).

Not being able to write that copy could trigger low disk space warning.
Having at least a copy on disk help mitigate race condition described above.

Auto background save could be triggered only for smaller file, while the two file save is somewhat always needed to avoid loosing data.

**Comment by hugollm** [comment]
This just happened to me on Atom 1.20 (Linux x64).
Shouldn't this issue be open?

**Comment by iainhallam** [comment]
Astonished that this was allowed to close. It's a data loss situation caused by the editor, so it's a bug that can radically affect a user's work.

**Comment by nathansobo** [comment]
We have a recovery system in place that is constantly saving the contents of open buffers.

**Comment by iainhallam** [comment]
How does that work when the disk is full?
