### ISSUE TITLE
Incorrect links in online Flight Manual section 1 sidebar

### ISSUE THREAD

**Issue by apjanke** [atom/atom#9167]
On the main Flight Manual table of contents at https://atom.io/docs/v1.0.19/, it lists the following subsections in chapter 1.

Chapter 1: Getting Started
    1.1 Why Atom
    1.2 Installing Atom
    1.3 Atom Basics
    1.4 Summary

<img width="522" alt="screen shot 2015-10-16 at 12 40 06 am" src="https://cloud.githubusercontent.com/assets/2618447/10533989/95ea6ada-739e-11e5-8e73-33119115b06f.png">

But once I click on one of those to get [in to Chapter 1](https://atom.io/docs/v1.0.19/getting-started-why-atom), the navigation sidebar on the left shows a different set of sections.

1 : Getting Started
    1.1 Upgrading Your Package
    1.2 Upgrading Your UI Theme Or Package Selectors
    1.3 Upgrading Your Syntax Theme
    1.4 Summary

<img width="669" alt="screen shot 2015-10-16 at 12 41 57 am" src="https://cloud.githubusercontent.com/assets/2618447/10533995/b8a5e18a-739e-11e5-9627-aa100ddf4f9a.png">

If I click on one of those, it seems to pull up old documentation. For example, the 1.1 "Upgrading Your Package" section starts out like this:

> Atom is rapidly approaching 1.0. Much of the effort leading up to the 1.0 has been cleaning up APIs in an attempt to future proof,

The prev / next links at the bottom of the pages still seem to work and get to the current docs, though.

**Comment by izuzak** [comment]
Thanks for the report, @apjanke -- I think this is already reported in https://github.com/atom/docs/issues/121 and we're still looking into why this is happening. Can you add your comment there? I think that would be helpful since the screenshots demonstrate the problem clearly.

Also /cc @thedaniel because :fire: :book: :fire:

**Comment by apjanke** [comment]
Yep, that's it. Closing in favor of atom/docs#121 and moving comments over there.
