### ISSUE TITLE
Windows installation creates non-hidden .atom folder under user's home dir

### ISSUE THREAD

**Issue by apjanke** [atom/atom#9168]
I just installed Atom on Windows 7 today using the download link from https://atom.io/. After installing and running it, a non-hidden folder named `.atom` appeared in my user profile directory (`C:\Users\janke`). Windows doesn't have the convention that an initial `.` in a file name causes the folder to be hidden, so the folder needs to have its Hidden attribute set to keep it from showing up in Windows Explorer by default.

It might make more sense to store this folder under the user's AppData folder(s) instead, if you want this to seem like a native Windows application. That's the standard Windows location for application-managed data and settings, and it would let users take advantage of roaming profiles to share their settings between machines.

**Comment by 50Wliu** [comment]
Closing in favor of #8281 - please subscribe there for updates.

**Comment by apjanke** [comment]
Thanks. Chimed in over there.
