### ISSUE TITLE
What Unix-on-Windows platforms are supported?

### ISSUE THREAD

**Issue by apjanke** [atom/atom#9169]
I installed Atom on Windows 7 today, and its installation came with `atom` and `atom.sh` Unix shell scripts. I assume these are intended to be usable on Windows, since they reference `.exe` files.

When I try to run `atom` under Cygwin, it produces a syntax error, because the sh script files are installed with DOS mode CRLF line endings.

```
$ atom foo.txt
/cygdrive/c/Users/janke/AppData/Local/atom/bin/../app-1.0.19/resources/cli/atom.sh: line 2: $'\r': command not found
/cygdrive/c/Users/janke/AppData/Local/atom/bin/../app-1.0.19/resources/cli/atom.sh: line 4: syntax error near unexpected token `$'in\r''
/cygdrive/c/Users/janke/AppData/Local/atom/bin/../app-1.0.19/resources/cli/atom.'h: line 4: `  case "$opt" in
```

But it seems to run okay under MinGW. Is this intentional? Is only MinGW supported, and not Cygwin?

The current `atom.sh` script is confusing on this point. It [tests for MinGW, but then calls it Cygwin](https://github.com/atom/atom/blob/21aee18911ea33f0e4ff416f8f3b14c6ac51385e/atom.sh#L7-L8). And there is no branch for Cygwin or MinGW in [the following platform-specific `if` logic that actually launches the program](https://github.com/atom/atom/blob/21aee18911ea33f0e4ff416f8f3b14c6ac51385e/atom.sh#L53-L113).

```bash
elif [ "$(expr substr $(uname -s) 1 10)" == 'MINGW32_NT' ]; then
  OS='Cygwin'
```

It would be nice to have the requirements/compatibility for the Unix-on-Windows environments mentioned in the documentation. I couldn't find it in the Flight Manual or through some brief searches of the documentation site. It would be nice to have Cygwin supported out of the box, too.

**Comment by mosbth** [comment]
I tried the same. I usually want to start atom directly from the prompt, just as i do on a Linux or Mac terminal. My preferred terminal is Cygwin.

I opened the file `atom.sh` and changed the lineendings to LF and the startupscript works. Instead I get this error.

```
mikae@DESKTOP-C3SVUSV ~
$ atom

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\cygdrive\c\Users\mikae\AppData\Local\atom\app-1.0.19\resources\cli\atom                 .js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

Looking at the path it seems like its using, understandable, the windows path with C:.

It would indeed be nice to be able to start atom directly from Cygwin.

**Comment by mosbth** [comment]
I partly stand corrected. Doing like this works excellent to start Atom from Cygwin terminal.

```
$ atom.cmd 
```

Its this that does not work.

```
$ atom
```

Since it *points at* `atom.sh` which does not work on Cygwin.

```
$ which atom
/cygdrive/c/Users/mikae/AppData/Local/atom/bin/atom
```

**Comment by apjanke** [comment]
Yeah. `atom.cmd` is known to be a native Windows program, based on file extension (I think), so automagic Cygwin->Windows path translation happens when you invoke it from a shell running under Cygwin. Plain `atom` is a shell script, which runs in the Cygwin Unix space, so automagic path translation doesn't happen.

MinGW is a different Unix-on-Windows layer with different filesystem mount point conventions and different automagic path translation conventions.

I don't know the particulars of exactly when the automagic path translation happens (and suspect I never will, b/c it's an interoperability issue between three platforms that don't like each other). But the `atom` script could learn enough about them to detect which layer it's running under, and do appropriate path translations. It's the only thing in the right position to do it well, and it wouldn't take a huge amount of code to do so. (And there's only the two Unix-on-Windows layers to worry about, so they wouldn't be opening themselves up to an explosion of supported platforms like per-distro Linux support might entail.)

**Comment by idivait** [comment]
Came across this, and added these lines to ~/.bashrc in Cygwin:

```
alias atom="atom.cmd"
alias apm="apm.cmd"
```

Worked like a charm! Thanks to the above posts for the idea.

**Comment by damieng** [comment]
Thanks for this information.

The next release (1,7) has atom.sh exactly calling atom.cmd passing along the command-line args. It has been tested on Cygwin (supported) and MSYS2 (not officially supported).
