### ISSUE TITLE
Search inside node_modules/lib but not node_modules

### ISSUE THREAD

**Issue by maligree** [atom/atom#9173]
This is part of my `.gitignore`:

```
node_modules/*
!node_modules/lib
!node_modules/lib/*
```

File search won't find files inside `lib/` since it is set to omit VCS ignored directories. Is there any way to make it understand that `node_modules/lib/` is searchable?

**Comment by lee-dohm** [comment]
Are you talking about the Project Find functionality from the [find-and-replace package](https://github.com/atom/find-and-replace)? Or something else?

If you're talking about Project Find, I can't reproduce the behavior you seem to be describing.

**Comment by maligree** [comment]
Yes, that and Fuzzy Finder. None of the directories under `node_modules/lib` are searched. This is what the directories show up like in tree view:

<img width="272" alt="screen shot 2015-10-17 at 9 47 43 am" src="https://cloud.githubusercontent.com/assets/902616/10557618/45ece7b2-74b4-11e5-9241-799fa02d15ca.png">

Changes do get picked up, though:

<img width="310" alt="screen shot 2015-10-17 at 9 49 44 am" src="https://cloud.githubusercontent.com/assets/902616/10557630/6f7cbbf2-74b4-11e5-8ebd-459ffc99c5d6.png">

**Comment by izuzak** [comment]
This sounds similar to https://github.com/atom/fuzzy-finder/issues/65 and https://github.com/atom/tree-view/issues/196.
