### ISSUE TITLE
VCS ignores not respected when searching inside of a particular project folder

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/atom#9175]
It seems like the 'included' paths for a search are overriding the VCS ignores in an unexpected way.
#### Repro
1. Enable the `core.excludeVcsIgnoredPaths` config setting.
2. Add two project folders: `atom` and `scandal`
3. Perform a project search for `dependencies` with the `File/Directory Pattern` field set to `scandal`.

The search results will include files in `scandal/node_modules`, even though `node_modules/` is set as ignored in `scandal/.gitignore`. I would expect `scandal/node_modules` to still be skipped, even though I've scoped my search to `scandal`.

**Comment by maxbrunsfeld** [comment]
It looks like [this scandal change](https://github.com/atom/scandal/commit/a07e14e9004d0b3a2448bbc73bd687a148a69cc9) might be related?

**Comment by benogle** [comment]
Yeah, it's a scandal bug. I remember this being really tough to get right with some exclusions, and some inclusions, and one group has higher precedence depending on the situation.

**Comment by mguida22** [comment]
Is there any progress on this?

**Comment by benogle** [comment]
Unfortunately, no. But you can [dig in](https://github.com/atom/scandal/blob/ad0113448f042697a031b732ea88701f6a3e776f/src/path-filter.coffee#L49-L72) if you'd like. [This](https://github.com/atom/scandal/blob/ad0113448f042697a031b732ea88701f6a3e776f/src/path-filter.coffee#L61-L63) is the bit that is accepting those files.

**Comment by mguida22** [comment]
Thanks for the pointers, I'll take a look and see what I can do!

**Comment by artgillespie** [comment]
I just submitted [PR 40](https://github.com/atom/scandal/pull/40) to scandal with a fix for this issue.

**Comment by 50Wliu** [comment]
Fixed by atom/scandal#40.
