### ISSUE TITLE
Atom fails silently trying to delete files that can't be sent to trash (Linux)

### ISSUE THREAD

**Issue by danShumway** [atom/atom#9182]
To reproduce:
Create a project on a drive that is not able to send deleted files to the trash, either because it does not have permissions or is not the owner.
Open project in Atom.
Attempt to delete file from tree view. No error will be thrown, file will remain.
Atom is however able to delete from projects located on drives that can access the trash.

Running version 1.0.4
Ubuntu 15.04

Would it be possible for Atom to give the option to permanently delete the file? If not, would it be possible for Atom to throw some kind of even generic error, so it doesn't appear that deletion itself is broken in the app?

**Comment by jrmedd** [comment]
+1 on this, it's bugged me for a while.

**Comment by fenque** [comment]
Temporary solution
```apm install permanent-delete```

**Comment by the-destro** [comment]
This is also the case on OS X. I am unable to delete on NFS mounted shares

**Comment by skybrian** [comment]
There should be a way to disable the trashcan functionality for a particular filesystem.  When the filesystem automatically takes snapshots, there is no need to have a trashcan - you can restore from a snapshot. Just removing the file is fine and expected.

**Comment by lee-dohm** [comment]
> Would it be possible for Atom to give the option to permanently delete the file?

No, we used to have various levels of permanent delete and people kept finding ways to accidentally permanently delete things they didn't want permanently deleted. It isn't worth the headache for us to even have the option available. If you want the ability to permanently delete things, you can install the [permanent-delete package](https://atom.io/packages/permanent-delete).

Atom does now report an error if it can't move something to the trash. If you have steps to reproduce a problem where it silently fails, please let us know and I'll be happy to reopen the Issue.
