### ISSUE TITLE
Atom doesn't follow system's fonconfig.

### ISSUE THREAD

**Issue by Wuxiangdong** [atom/atom#9188]
Hi!I am a chinese and my English is poor....:)
atom doesn't follow system's fonconfig,such as:
![screenshot_20151017_171002](https://cloud.githubusercontent.com/assets/7942339/10557966/1b7d9c54-74f2-11e5-906d-0bdf1f281d85.png)
I set hintslight but atom may follow hintfull
but if I set fonts:
![screenshot_20151017_171234](https://cloud.githubusercontent.com/assets/7942339/10557971/5544af18-74f2-11e5-8cee-92adee5ddce3.png)
Atom will follow system's fontconfig(hintslight)
![screenshot_20151017_171317](https://cloud.githubusercontent.com/assets/7942339/10557977/945d1866-74f2-11e5-9f34-12c0ff066351.png)

**Comment by thomasjo** [comment]
What operating system are you using?

**Comment by Wuxiangdong** [comment]
Archlinux Kde5

**Comment by Wuxiangdong** [comment]
My fontconfig is:
    <match target="font">
      <edit mode="assign" name="hinting"><bool>true</bool></edit>
      
      <edit mode="assign" name="hintstyle"><const>hintslight</const></edit>
      <edit mode="assign" name="rgba"><const>rgb</const></edit>
      <edit mode="assign" name="antialias"><bool>true</bool></edit>
      <edit mode="assign" name="lcdfilter"><const>lcddefault</const></edit>
      <edit mode="assign" name="embeddedbitmap"><bool>false</bool></edit>
    </match>

looks like:
![screenshot_20151019_205327](https://cloud.githubusercontent.com/assets/7942339/10578268/afa9a802-76a3-11e5-992e-3bcd8d2ceec4.png)


but if I set 'hintfull',
looks like:
![screenshot_20151019_205547](https://cloud.githubusercontent.com/assets/7942339/10578291/d0f1f8f2-76a3-11e5-9557-76a125c61592.png)

**Comment by Wuxiangdong** [comment]
It's seems that the bug was fixed up in atom 1.1...

**Comment by 50Wliu** [comment]
> It seems that the bug was fixed up in atom 1.1...

Glad to hear it! :smile:
