### ISSUE TITLE
Enable regular expressions in core.customFileTypes

### ISSUE THREAD

**Issue by danielbayley** [atom/atom#9197]
Since the functionality of [atom-file-types](https://github.com/execjosh/atom-file-types) is being [absorbed into core](https://github.com/atom/atom/releases/tag/v1.0.8) (related to #1718), can we have the ability to specify regular expressions in `config.cson` in the same way also?

For a basic example, with `atom-file-types`, putting `"jsx(inc)?$": "source.js"` will work on both `.jsx` and `.jsxinc` files.

**Comment by danielbayley** [comment]
@50Wliu This one should definitely stay open. I want to do a PR actually for this one…

**Comment by mdesantis** [comment]
I can still reproduce this on Atom 1.33.0
