### ISSUE TITLE
Fails to open folder

### ISSUE THREAD

**Issue by SamuelMarks** [atom/atom#9199]
![The editor has crashed](http://i.imgur.com/XMlsFQT.png)

It's a new folder, which I made a copy `cp -r` of another, then ran `sed` on its files. The folder I copied is openable in Atom. It's an NTFS mount.

## Versions

* **Atom:**       1.0.19
* **Atom-Shell:** 
* **OS:**         linux 3.19.0-30-generic
* **Misc**
    * apm  1.0.5
    * npm  2.13.3
    * node 0.10.40
    * python 2.7.9
    * git 2.1.4

---

Not sure where the log file is, as this message isn't very useful to show.

EDIT: I can open it from a directory above, but when I right-click open in new window same crash occurs.

**Comment by tiagocpontesp** [comment]
+1 , can't open folder on an NTFS mount: 
fuseblk (rw,nosuid,nodev,noexec,relatime,user_id=0,group_id=0,allow_other,blksize=4096,user)
