### ISSUE TITLE
Is there some other place to download Atom for Windows that doesn't expire? 

### ISSUE THREAD

**Issue by disuem** [atom/atom#9201]
Is there any mirrors to download Atom that doesn't expire? I am on a slow internet connection, and well, I have tried twice and both times almost at the end the download expired. I do not understand why people put expiry dates on download to begin with - making it inaccessible especially for people who do not live on high-tech places and high internet speed, and no option to resume.

**Comment by nathansobo** [comment]
@thedaniel would you know who to ping on the releases API about the expiry timeout on release downloads? Not sure there's anything we can do about this immediately.
