### ISSUE TITLE
Opening IMDb Actors Data File Causes Crash

### ISSUE THREAD

**Issue by schackbrian2012** [atom/atom#9202]
Dear Atom,

When I open the IMDb actors data file, then Atom crashes.

Steps to Replicate:
1. Download the IMDb actors data file at ftp://ftp.fu-berlin.de/pub/misc/movies/database/actors.list.gz.
2. Open the file in Atom.
3. Atom says, "Atom will be unresponsive during the loading of very large files. Do you still want to load this file?"
4. Click the Proceed button.

Expected Result:
Atom opens the file.

Actual Result:
Atom says, "The editor has crashed. Please report this issue to https://github.com/atom/atom."

**Comment by Zireael07** [comment]
How big is the file exactly?

**Comment by schackbrian2012** [comment]
1.03 GB

**Comment by nathansobo** [comment]
Thanks for the report. This is pretty similar to #7583, so I'm going to close it as a duplicate.
