### ISSUE TITLE
cmd-d (find-and-replace:select-next) doesn't "select" starting with multi selection

### ISSUE THREAD

**Issue by Gurpartap** [atom/atom#9203]
```proto
service UserService {
	rpc GetUser(GetUserRequest) returns (GetUserResponse) {}
	rpc PostUser(PostUserRequest) returns (PostUserResponse) {}
}

message GetUserRequest { string id = 1; }
message GetUserResponse { User user = 1; }

message PostUserRequest { *User* user = 1; }
message PostUserResponse { *User* user = 1; }
```
Imagine something like this with the code in asterisks having been selected by double clicking its first instance and then holding cmd and double clicking the second one.

Now press cmd-d (`find-and-replace:select-next`) repeatedly. It'll select all instances of `User` except the one in the beginning of the last line (from `PostUserResponse`). I expected it to select all instances of `User`.

**Comment by nathansobo** [comment]
![select-bug](https://cloud.githubusercontent.com/assets/1789/10589902/24445e66-766b-11e5-973c-64dbc2ea07a2.gif)

I can confirm what @Gurpartap is reporting on master. For some reason following his steps prevents a couple of the items from being selected.

/cc @benogle just so you're aware of this.

**Comment by nathansobo** [comment]
This issue was moved to atom/find-and-replace#563
