### ISSUE TITLE
racer.rustSrcPath is not set in your config.

### ISSUE THREAD

**Issue by Fimasik** [atom/atom#9204]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: Atom Core

### Stack Trace

racer.rustSrcPath is not set in your config.

```
At undefined

undefined
```

### Commands

```
  4x -0:20.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "useReactEditor": true,
    "disabledPackages": [
      "linter-pep8",
      "linter-python-pep8",
      "python-autopep8",
      "linter-rust",
      "rust-api-docs-helper"
    ]
  },
  "editor": {
    "tabLength": 4,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
atom-python-debugger, v0.3.4
autocomplete-python, vundefined
language-rust, v0.4.5
linter, v1.8.1
python-isort, v0.0.7
racer, v0.17.2

# Dev
No dev packages
```

**Comment by mnquintana** [comment]
This looks like an issue with [racer](https://github.com/edubkendo/atom-racer), not with Atom core - feel free to reopen an issue there.

**Comment by derekdreery** [comment]
The error message says "This is likely a bug in Atom.", is there a way for atom to tell that the bug is in the package?

**Comment by pyfisch** [comment]
The bug is that atom claims it is a bug with itself.

**Comment by 50Wliu** [comment]
> The bug is that atom claims it is a bug with itself.

There is no context in this error message, so there is absolutely no way for Atom to determine which package is causing the issue.  It defaults to atom/atom for safety.

**Comment by derekdreery** [comment]
Maybe the error message could be like `This may be a bug in Atom`, - the `likely` misled me a little.

**Comment by derekdreery** [comment]
Or maybe `probably`, because that allows the chance that it is not, whereas `likely` can be taken to mean `almost certainly`

**Comment by htory327** [comment]
still get this error
