### ISSUE TITLE
"Reveal in Finder" on OS X not working on a German / Norwegian / Swedish / Danish keyboard

### ISSUE THREAD

**Issue by sveinfid** [atom/atom#9205]
"Reveal in Finder" on OS X not working on a German / Norwegian / Swedish / Danish keyboard

"Reveal in Finder" is ⇧⌘\ while Tree View's "Toggle" is ⌘\

This is a problem since \ (backslash) is ⇧-Ctrl-7 on a German / Norwegian / Swedish / Danish keyboard

So "Reveal in Finder" simply does a "Toggle" instead.

Could the default key mapping for one of these be mapped to another key combination in order for them not to conflict?

Thanks.

**Comment by 50Wliu** [comment]
Atom currently cannot handle foreign keyboard layouts correctly - see atom/atom-keymap#35 for more information.

As a workaround, you can try installing the [keyboard-localization](https://atom.io/packages/keyboard-localization) package.
