### ISSUE TITLE
Put "Finding with Options: Case (Ins/S)ensitive" status inside "Find in current buffer" field

### ISSUE THREAD

**Issue by willnwhite** [atom/atom#9211]
Not knowing if the search is case sensitive or insensitive without remembering to look outside the search field for that meant I lost time because I didn't remember I'd (for a previous search) set the search to be case sensitive.

![screen shot 2015-10-19 at 13 50 06](https://cloud.githubusercontent.com/assets/8081877/10578170/5e5fd6e6-7668-11e5-921d-6da21d21c69d.png)

When I couldn't find what I was looking for, I remembered to make the search case insensitive, and of course more results showed up.

**Comment by izuzak** [comment]
This issue was moved to atom/find-and-replace#562
