### ISSUE TITLE
two folder exist after renaming existing folder

### ISSUE THREAD

**Issue by liyakun** [atom/atom#9212]
![rename](https://cloud.githubusercontent.com/assets/7370334/10579010/efeabce0-7675-11e5-97fb-6c2c6d6b50e7.PNG)
If I rename this folder to 08_functions_03_return, the both 08_functions_03_return and 08_functions_03_operators will exist.

**Comment by izuzak** [comment]
Thanks for the report, but I'm unable to reproduce this problem, @liyakun. Can you please reopen this issue on the https://github.com/atom/tree-view issue tracker, but only with [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues)? Which version of Atom are you using? Which OS and version? Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)? Can you provide a GIF which clearly demonstrates what you're doing and the problem you're seeing?

**Comment by liyakun** [comment]
@izuzak Sorry for the misleading. This is an operation error, so I did not make a new issue. However I still think it is very easy to make this error, so I made a gif to show it. My OS is windows 10, and atom version is 1.0.19. 
![ezgif com-gif-maker 1](https://cloud.githubusercontent.com/assets/7370334/10617939/7af29ad6-776d-11e5-9069-0fa231533aa2.gif)
As you can see, the file in the path before rename still exist in the editor after rename, if I save it again, then the original folder is created again. So, if the path in the editor after rename is also changed, then there will be less chance to make this error. Thank you!

**Comment by izuzak** [comment]
@liyakun Thanks for the feedback. I _think_ what you're trying to point out is already being tracked in this issue: https://github.com/atom/tree-view/issues/559, so you might want to follow that for updates or add a comment there. Also, let me know if I misunderstood your note. :v:
