### ISSUE TITLE
Atom settings behind Bluecoat crashes in Windows

### ISSUE THREAD

**Issue by kkdoitall** [atom/atom#9215]
Using Atom behind Bluecoat proxy crashes as below when trying to change theme. 
![atom crash report](https://cloud.githubusercontent.com/assets/3229241/10586219/c7c25364-7660-11e5-80c6-514ea65096b8.png)

I have setup the below property in ~/.atom/.apmrc 
strict-ssl = false

I am new to atom and would need help to resolve this issue

Additional Information : 
Here is what I see from the atom Crash report  operation_log.txt

*[121964:122184:1019/125651:VERBOSE1:crash_service_main.cc(68)] Session start. cmdline is [--reporter-url=http://54.249.141.255:1127/post --application-name=Atom --v=1]
[121964:122184:1019/125651:VERBOSE1:crash_service.cc(142)] window handle is 000C0E72
[121964:122184:1019/125651:VERBOSE1:crash_service.cc(290)] pipe name is \\.\pipe\Atom Crash Service
dumps at C:\Users\myuser\AppData\Local\Temp\Atom Crashes
[121964:122184:1019/125651:VERBOSE1:crash_service.cc(294)] checkpoint is C:\Users\myuser\AppData\Local\Temp\Atom Crashes\crash_checkpoint.txt
server is http://54.249.141.255:1127/post
maximum 128 reports/day
reporter is electron-crash-service
[121964:122184:1019/125651:ERROR:crash_service.cc(301)] could not start dumper
[118300:122608:1019/125651:VERBOSE1:crash_service.cc(331)] client end. pid = 120464*

**Comment by nathansobo** [comment]
@raelyard do you know how we can capture a crash report for this so we could get more insight on what's going wrong?

**Comment by nicklevett** [comment]
Related #9176?

**Comment by raelyard** [comment]
@nathansobo something like a dump generated by the operating system?  Haven't tried to do that before, but pretty sure there is an API for that.

**Comment by nathansobo** [comment]
@zcbenz are we getting any crash reports from breakpad that could shed light on this?

**Comment by karthikeyan-kesavaraj** [comment]
@nathnsobo is that something I can get. I am able to see the .dmp and .txt files under Temp/Atom Crashes. I am unable to attach the files here.

**Comment by nathansobo** [comment]
@karthikeyan-kesavaraj Want to just send them to me at nathan@github.com?

**Comment by damieng** [comment]
Did we get any more debug information on this?

**Comment by damieng** [comment]
Still no information on this so closing the bug. If you have more info please re-open.
