### ISSUE TITLE
OS X 'Smart Zoom' is enabled on OS X

### ISSUE THREAD

**Issue by nathansobo** [atom/atom#9216]
_From @ashgti on October 19, 2015 17:35_

This might be intentional, but I just noticed that 'Smart Zoom' on OS X is enabled. I haven't seen anywhere that says this should be supported. I'm mostly filing this because I couldn't find confirmation one way or another that this should work. 

If this is the intended behavior, the please ignore. 

![atom-smart-zoom](https://cloud.githubusercontent.com/assets/22535/10585609/ea25d5fc-764c-11e5-8b66-35fdd7f7e93e.gif)

_Copied from original issue: atom/electron#3143_

**Comment by nathansobo** [comment]
No, this isn't intentional. We've disabled pinch to zoom on the latest beta release, and we should disable this as well. Thanks for the report.

**Comment by ashgti** [comment]
The operation I performed is a 'Smart Zoom' which is a double tap (not double click though) on a Magic Mouse/Trackpad. You need the 'Smart Zoom' gesture enabled in the OS X Mouse / Trackpad system settings for the gesture to work.

**Comment by alexchandel** [comment]
@nathansobo Wait, I thought this was intentional. Being an OS X user, I had assumed this and pinch would work and was pleased when it did. I could see the need for an option in the Settings to disable it, but can it please be reenabled?

**Comment by nathansobo** [comment]
@alexchandel Not really keen to add an option, but in your init script you could do the following:

```js
webFrame = require('web-frame')
webFrame.setZoomLevelLimits(1, 10) // or some limits you like better
```

That will re-enable pinch to zoom for you.
