### ISSUE TITLE
Make default-state of flags for find/replace configurable

### ISSUE THREAD

**Issue by goldsborough** [atom/atom#9232]
As of now, at least for me, every time I start Atom and hit cmd+f to do find/replace I have to manually set the regex + case-sensitivity flag. Can you please make the default-state of these flags configurable in the settings, or just store them from the last session? In Sublime the flags are remembered even after closing/restarting the application (i.e. really quitting, not just hiding). I find this really inconvenient in Atom right now. Sorry if there already is some mechanism of doing this, I just couldn't find anything for it.

**Comment by mnquintana** [comment]
This issue was moved to atom/find-and-replace#565
