### ISSUE TITLE
--profile-startup flag doesn't record a profile when launching Atom for the first time with no path

### ISSUE THREAD

**Issue by izuzak** [atom/atom#9233]
More context here: https://github.com/atom/docs/pull/136#issuecomment-149606128

@kevinsawicki mentioned:

> Hmm, I wonder if the timeout needs to be bumped in https://github.com/atom/atom/blob/806b46bb6c981f110a34ed20f566de50288900d0/static/index.js#L143-L145

> There seemed to be issues in past Electron versions where you needed to wait a bit to start profiling after the devtools opened event fired.

I tried bumping the timeout to 500ms and that did fix the problem for me. But I'm not sure what a good timeout would be so opening this to track the issue.

cc @kevinsawicki @nathansobo

**Comment by kevinsawicki** [comment]
> I tried bumping the timeout to 500ms and that did fix the problem for me.

Maybe going a full second just to be on the safe side?

Profile creation take time anyway so an extra second shouldn't be too bad to sit through.

**Comment by nathansobo** [comment]
Ugh. Accidentally left this on master when upgrading a dependency and force-pushed it back.

**Comment by izuzak** [comment]
Gonna reopen this since the issue isn't fixed for me by https://github.com/atom/atom/issues/9235, more info in https://github.com/atom/atom/pull/9235#issuecomment-149843864.
