### ISSUE TITLE
Add an option on atom-text-editor to make it read-only

### ISSUE THREAD

**Issue by bolinfest** [atom/atom#9237]
Currently in Nuclide, we create a subclass of `TextEditor` named `ReadOnlyTextEditor` to try to make a read-only version:

https://github.com/facebook/nuclide/blob/1fdf2b98/pkg/nuclide/ui/atom-text-editor/lib/ReadOnlyTextEditor.js
1. This is pretty hacky and tough to maintain because it's hard to be sure that we have blocked off all reasonable entry points that could mutate things.
2. Currently on master, the new refactoring of `TextEditor` that frowns on using the constructor directly and strongly pushes for the use of `atom.workspace.buildTextEditor()` breaks our existing use of `extends TextEditor` in implementing `ReadOnlyTextEditor`.

We can work around this using a new hack (will link once the diff is up), but it would be nice to have proper support for this in Atom. We use `TextEditor` in a number of places as a UI element to show things like console logs.

I'll try to put up my own fix for this when I get a chance, but I'm filing this to have a placeholder for now.

/cc @nathansobo @maxbrunsfeld

**Comment by bolinfest** [comment]
For reference, this is how we made a quick fix for this in Nuclide: https://github.com/facebook/nuclide/commit/c7dabd840e415973f23218fbf45d89a992dcb730

**Comment by mnquintana** [comment]
@bolinfest Were you thinking this would be instead of, or in addition to https://github.com/atom/atom/issues/6880?

**Comment by nathansobo** [comment]
Thanks @bolinfest. This is definitely something we've needed as well in a couple cases and have resorted to hacks to achieve. It would be good to do a solid, supported implementation.

**Comment by gamaralf** [comment]
+1

It is something I find useful in Emacs, the "read-only-mode".
