### ISSUE TITLE
Atom crashes when pasting clipboard image into editor

### ISSUE THREAD

**Issue by winterflags** [atom/atom#9246]
I am using Mac OS X 10.11 with Atom 1.0.19.

When opening a bitmap image with OS X's "Preview", copying it and <kbd>CMD</kbd> + <kbd>V</kbd> into the Atom editor, Atom crashes.

It usually crashes, but it has succeeded a few times. It seems like it wants to paste this:
`![Alt text](/Users/xxx/.atom/evnd/tmp/clipboard_20151021_214154.png "Optional title")`

The clipboard image I wish to paste is 2804 × 1544 px.

<img width="509" alt="screen shot 2015-10-21 at 21 47 41" src="https://cloud.githubusercontent.com/assets/14942350/10648215/694c3fa0-783d-11e5-9713-932da21aca73.png">

**Comment by 50Wliu** [comment]
Does this still happen in safe mode (`atom --safe`)?  Is it possible to share the image you want to paste here?  Thanks.

**Comment by winterflags** [comment]
Starting Atom in safe mode seems to disallow pasting clipboard data into the editor.
So no, it does not happen.

Link to the image:
https://dl.dropboxusercontent.com/u/4750338/Screen%20Shot%202015-10-21%20at%2021.36.12.png

**Comment by 50Wliu** [comment]
> Starting Atom in safe mode seems to disallow pasting clipboard data into the editor.

Hmm, that shouldn't be the case.  Can you please post the output of `apm list --installed` here?

**Comment by winterflags** [comment]
This is the output of `apm list --installed`:

`/Users/xxx/.atom/packages (2)`
`├── ever-notedown@0.2.11`
`└── sublime-block-comment@0.2.1`
