### ISSUE TITLE
Page CSS style Affects Atom's IDE

### ISSUE THREAD

**Issue by udoyen** [atom/atom#9252]
I am following a tutorial on styling with css on the page header and i discovered that when i use the **"div"** tags in my header in this fashion **(div{background-color:blue;})** this color and any other style is applied to the IDE as well as to the html target docs.

**Comment by simurai** [comment]
Not quite sure what you mean with

>  when i use the __"div"__ tags in my header in this fashion __(div{background-color:blue;})__

There is an [issue](https://github.com/atom/markdown-preview/issues/276) if you use CSS with a `<style>` element inside a markdown file? Like:

```html
<style> div { background-color:blue; } </style>
```

**Comment by udoyen** [comment]
Hi Simurai, If I get you right, not adding the "type" attribute to my css style opening tag will cause this issue? Please note that this is all in the page header section.

Thanks in advance

**Comment by simurai** [comment]
"type" attribute shouldn't matter, just that when adding it to a markdown file and then opening the markdown preview, then it can affect Atom's UI.

Do you have screenshot showing the problem?
