### ISSUE TITLE
CSS syntax highlighting is strange

### ISSUE THREAD

**Issue by ghost** [atom/atom#9253]
![capture](https://cloud.githubusercontent.com/assets/8420596/10666412/5dcdea8e-78c9-11e5-8fba-8eff769a5bdf.PNG)

What is happening here?

Sometimes the first word is highlighted, sometimes just a single letter etc.

**Comment by mnquintana** [comment]
What language is this? This doesn't look like CSS at all. (Some of those aren't valid CSS properties, and CSS properties are kebab-cased, not camel-cased.) What language grammar do you have active? (Check the lower right-hand corner in the status bar.)

**Comment by Ben3eeE** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/atom/issues/9253#issuecomment-150227369. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
