### ISSUE TITLE
Search and duplicate results with symbolic links

### ISSUE THREAD

**Issue by MichaelJCole** [atom/atom#9256]
Hi, I have a project split into microservices.  So, some of the code is in an 'all' folder and gets symbolicly linked into the individual service folders.

When I do a search, I get duplicate results from the symbolic links.

It would be awesome if I could not see these duplicate results in search results.  They are all from the same file, with the same text, on the same line.

If there was one last filter the results passed through, that checked if they'd already been added to the list, that would be awesome.

Is this possible with a package?  Is there an existing package to hack?   

Thanks!

Mike

**Comment by thedaniel** [comment]
This issue was moved to atom/find-and-replace#574
