### ISSUE TITLE
`apm rm .` (or uninstall) will uninstall all packages

### ISSUE THREAD

**Issue by forivall** [atom/atom#9261]
I've accidentally done this a couple times when trying to remove linked packages for the official versions. Luckily, I have a list of all of my installed packages saved and a script to install all of them (for new computers).

**Comment by thomasjo** [comment]
Thanks for the report! However, please report this on the [apm repo](https://github.com/atom/apm) :bow:

**Comment by forivall** [comment]
Ah, my bad. I thought it was bundled in core atom. apm#460
