### ISSUE TITLE
Display 2-space indentation as if it's 4-space wide

### ISSUE THREAD

**Issue by gsklee** [atom/atom#9263]
Is there any way to display 2-space indentations as if it's 4-space wide?

My team is interested in adapting [Semistandard](https://github.com/Flet/semistandard) but the enforcement on pure personal preference (ie. indentation) is holding them off. We're looking for a way to introduce Semistandard into our workflow but allowing different indentation depth. Tweaking the width of indentation space character seems to be a way of doing it.

**Comment by thedaniel** [comment]
You could always style `.source.js .leading-whitespace` to be wider in in your styles.less, would that help solve this problem?

**Comment by alexandernst** [comment]
This is still a problem/requested feature
