### ISSUE TITLE
Exclude VCS Ignored Paths don't work

### ISSUE THREAD

**Issue by arusakov** [atom/atom#9264]
Atom version 1.0.19
My .gitignore:
```
.DS_Store
.idea
node_modules
compiled
```
node_modules and compiled folder not displayed:
![atom](https://habrastorage.org/files/43c/3c9/f80/43c3c9f804c14da596acaa3d6e5c3729.png)

**Comment by izuzak** [comment]
There are additional settings for the Tree View under Packages > Tree View > Settings. Can you check those as well?

**Comment by arusakov** [comment]
@izuzak
In config folder? I don't have tree view folder in packages folder...

**Comment by izuzak** [comment]
In the Packages section of the Settings. Tree view is a bundle package, it is installed by default.

<img width="718" alt="screen shot 2015-10-23 at 12 21 36" src="https://cloud.githubusercontent.com/assets/38924/10690228/aa330082-7980-11e5-9a2f-b1c9b8f32526.png">

**Comment by arusakov** [comment]
@izuzak Thank you very much, I don't know about this settings. Sorry for stupid issue (

**Comment by k98kurz** [comment]
What the hell is the point of having that option in the main settings anyway if it doesn't affect anything? Isn't that as disingenuous as it is pointless?
