### ISSUE TITLE
First creation of styles.less requires restarting Atom

### ISSUE THREAD

**Issue by chris-martin** [atom/atom#9266]
1. Opened Atom for the first time
2. Created `~/.atom/styles.less` (using a different editor)
3. Spent a frustrated while trying to figure out why none of my styles were being applied.
4. Restarted Atom
5. Now changes to `styles.less` update automatically as documented.

Seems like maybe it's watches the filesystem for changes when the file already exists, but it doesn't watch for file _creation_?

**Comment by thedaniel** [comment]
Thanks for the bug report. I think the more concerning thing is that `styles.less` wasn't created already. Had you created the `~/.atom` directory yourself before installing atom by any chance?

**Comment by chris-martin** [comment]
No, I hadn't.

**Comment by samschmidt** [comment]
Issue looks difficult to reproduce. Doesn't seem like it's still a problem. Consider closing.

**Comment by 50Wliu** [comment]
Atom should automatically create the `~/.atom` folder as well as subfiles such as `~/.atom/styles.less`.  If that is not happening then please create a new issue.
