### ISSUE TITLE
Editor:move-to-end-of-word does not move beyond end of line if CRLF line ends in file

### ISSUE THREAD

**Issue by rluiten** [atom/atom#9270]
I am on windows 7 64bit, running atom version v1.0.19, I have reset my atom config to make sure it is not related to my config and it still exhibits this behaviour.

For keystroke ctrl-right which maps to editor:move-to-end-of-word, it will not move the cursor beyond the end of any line it is on if the file ending is CRLF terminated. If I convert the file to LF termination it then works as I would expect and will move to end of the next word on the next line appropriately.

I checked ctrl-left mapped to editor:move-to-beggining-of-word and it works and moves off start of the current line to previous line without a problem.

**Comment by jerone** [comment]
Confirmed both issue and work-around on Windows 7, Atom 1.1.0-beta1.
Same goes for selections.

**Comment by thedaniel** [comment]
Confirmed on Mac as well. Thanks for the bug report.

**Comment by rluiten** [comment]
Crossed fingers this fixes it https://github.com/atom/atom/pull/9937

**Comment by rluiten** [comment]
The beta does appear to fix this thankyou.
