### ISSUE TITLE
Compilation errors when installing in sl-release-6.6-1.x86_64

### ISSUE THREAD

**Issue by acampove** [atom/atom#9275]
Hi,

When following https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md for fedora/centos/Rhel I get a lot of error messages when running script/build. I am told at the end of the message that:

npm ERR! Please include the following file with any support request:
npm ERR!     /home/acampove/Downloads/atom/npm-debug.log

I cant attach the file for some reason, but the lines at the end say:

10864 error node v0.10.40
10865 error npm  v2.13.3
10866 error code ELIFECYCLE
10867 error scrollbar-style@3.2.0 install: `node-gyp rebuild`
10867 error Exit status 1
10868 error Failed at the scrollbar-style@3.2.0 install script 'node-gyp rebuild'.
10868 error This is most likely a problem with the scrollbar-style package,
10868 error not with npm itself.
10868 error Tell the author that this fails on your system:
10868 error     node-gyp rebuild
10868 error You can get their info via:
10868 error     npm owner ls scrollbar-style
10868 error There is likely additional logging output above.
10869 verbose exit [ 1, true ]

Any idea what might be the problem?

Thanks.

**Comment by thedaniel** [comment]
This issue was moved to atom/scrollbar-style#10
