### ISSUE TITLE
When a new file opened cannot be saved

### ISSUE THREAD

**Issue by NikosEfthias** [atom/atom#9281]
if a file doesnt exists atom cannot create file and save it im using atom 1.0.19 and ubuntu 14.4 lts

**Comment by pitops** [comment]
can you elaborate on that?

**Comment by NikosEfthias** [comment]
what do you mean ?

**Comment by izuzak** [comment]
@NikosEfthias It seems that you're saying that Atom can not create new files, is that right? Can you share the exact steps which reproduce this problem for you in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode) and a GIF which clearly demonstrates the problem? Just to make sure we understand what you're doing.

**Comment by jeancroy** [comment]
Is it possible to be a permission problem ?
Ie existing files are read/write but parent folder is read only (impossible to create new files)


https://help.ubuntu.com/community/FilePermissions

**Comment by NikosEfthias** [comment]
no the folder is owned by me and has 0777 permissions
