### ISSUE TITLE
Weird C++ syntax highlighting 

### ISSUE THREAD

**Issue by laituan245** [atom/atom#9282]
Why is the variable name 'fIndex' colored red while 'eIndex' and 'dIndex' are colored white ?

![selection_031](https://cloud.githubusercontent.com/assets/3805149/10716308/2b738b64-7b78-11e5-972a-625298cb49bd.png)

**Comment by thomasjo** [comment]
Please re-open this on the [language-c](https://github.com/atom/language-c) repo.
