### ISSUE TITLE
Windows freezing on gulp compile

### ISSUE THREAD

**Issue by harangue** [atom/atom#9284]
I have a 10/10 reproduction rate with this issue - when I'm watching a directory for changes with gulp and save a file, atom will freeze for an indeterminate amount of time. After a little while, the editor unlocks enough to toggle tabs which unfreezes things completely.

I can set up a git repo of my current project, if that would be helpful. Note that in the gif, the first time I select save from the menu while the second time I used Ctrl-S. It makes no difference for the purpose of reproducing this.

![Image of problem](http://g.recordit.co/RsX9DNxEq2.gif)

**Comment by thomasjo** [comment]
Are you able to reproduce this in safe mode? `atom --safe`

**Comment by harangue** [comment]
No, I'm not, but I'm no longer able to reproduce the issue in my regular editor either. I'll keep looking to get it to lock up again.

**Comment by izuzak** [comment]
Thanks for letting us know, @harangue -- I'm going to close this until you can reproduce this again. Once you can do that, a link to a Git repository and the exact list of commands which you ran would be helpful. Also, please include your OS+version and Atom version. :memo:
