### ISSUE TITLE
When disconnecting a non-retina external monitor, Atom doesn't switch state while full screen

### ISSUE THREAD

**Issue by will-in-wi** [atom/atom#9288]
I have a retina MacBook Pro running El Capitan with two non-retina external monitors. If I have an Atom window full screen on a non-retina display and then disconnect my laptop, Atom will continue to be in low-resolution mode on the Retina display. Sizing is correct, but text is blurry.

**Comment by izuzak** [comment]
Thanks for the report, @will-in-wi. This sounds similar to https://github.com/atom/atom/issues/9226 so I'm going to close this in favor of that. Could you add a comment there so that everything is in one place? And please let me know if I misunderstood your report. :v:

**Comment by will-in-wi** [comment]
This is indeed a duplicate of the listed bug. Thanks!
