### ISSUE TITLE
displayBuffer.getVisibleRowRange in beta

### ISSUE THREAD

**Issue by camel-chased** [atom/atom#9289]
where did go getVisibleRowRange function from displayBuffer in beta version of atom?
there is some place that developer could track the changes in core functionality of atom?
if you are making a lot of changes in each release of atom a lot of plugins will stop working correctly but you know that already
maybe try to use adapters or something for compability reasons, or getters/setters for properties that in newer versions become functions, i don't know 
it is painfull to struggle with errors each time bigger update is released
of course beta is not released yet as stable but i don't know how i can repair my plugin to work with beta and whether reapair it or this is a atom bug or change
awww :]

**Comment by mnquintana** [comment]
Sorry for the frustration here, but that method (and the `DisplayBuffer` class as a whole) is [undocumented](https://atom.io/docs/api/v1.0.19/Atom) and unsupported, which makes it subject to change at any time without notice. Packages technically can still use these methods anyway, but they do so at their own risk. Sorry about that!

**Comment by nathansobo** [comment]
You can access this method in a deprecated form on `TextEditor` and in an officially-supported form on `TextEditorElement`. We have to draw some sort of line on public vs private APIs or we'll never be able to improve anything. If you're using private methods, the beta period is a good time to check if anything has changed.

**Comment by camel-chased** [comment]
thanks for help, everything works now with textEditor instead of buffer :+1:
