### ISSUE TITLE
Resizing the window leaves a white trail 

### ISSUE THREAD

**Issue by izuzak** [atom/atom#929]
I started noticing a white trail when resizing the Atom window if a medium-sized file is loaded (or larger). This GIF was made with a file that has 1000 lines and `This is a test` text in every other line:

![out](https://f.cloud.github.com/assets/38924/1275351/516ad54e-2df4-11e3-8240-53702ad391e8.gif)

(sorry for the quality! still learning how to create GIFs)

The trail is shown only when the resizing increases the size of the window, not when the size is decreased. 

Atom version 31.0. OSX 10.8.5

**Comment by jordwalke** [comment]
Is there really no way to solve this? Sublime and other modern IDEs don't have this ugly window resize issue. It's just one more reminder that "this is a web view" - a glitch in the matrix.
Last time I checked, Safari/Webkit doesn't have this issue.

**Comment by jordwalke** [comment]
Visual Studio Code Insiders version has solved this now. What do they do to solve it?

**Comment by faustinoaq** [comment]
Ping, Atom 1.19 still has this issue :sweat_smile:

**Comment by Redsleeve** [comment]
Ping, Atom 1.25.0 still has this issue :(

**Comment by codeblooded** [comment]
@jordwalke is right about VSCode not doing it? What are they doing differently?
