### ISSUE TITLE
Syntax coloring error for C++ filter

### ISSUE THREAD

**Issue by krice42** [atom/atom#9290]
![screen shot 2015-10-26 at 9 49 47 am](https://cloud.githubusercontent.com/assets/15328301/10735875/5b45865e-7bc7-11e5-9f3b-480474decd5d.png)

While creating a function template I noticed that the syntax coloring for "T" didn't match up with what I was seeing when I type the same thing into visual studio. The color for "T" should continue to be orange throughout the function, parameters and block.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/language-c? Thanks!

**Comment by krice42** [comment]
will do!
