### ISSUE TITLE
I/O blocking when editing in mounted network directories 

### ISSUE THREAD

**Issue by hiyou102** [atom/atom#9291]
When I mount an ssh directory on my file system on Ubuntu 15.04 and open a file the editor freezes until the file is loaded. This also happens when saving files. This can be problematic if my network is slow or experiences interruptions since it can completely lock up the editor and cause it to crash.

**Comment by izuzak** [comment]
Thanks for the report, @hiyou102. There's already a few issues related to slowness/problems when working with network drives, e.g. https://github.com/atom/atom/issues/2456 and https://github.com/atom/atom/issues/1766. I think those two cover your report as well, so I'm going to close this in favor of those issues, but please let me know if I misunderstood anything.
