### ISSUE TITLE
Get random edits on js file

### ISSUE THREAD

**Issue by matteo-ronchetti** [atom/atom#9292]
I'm using atom version 1.0.19 on linux elementary os luna, the only package I installed is https://atom.io/packages/jshint.
While I'm editing a js file, in particolar after using  the multiple  cursors with CTRL+D and then deselecting by clicking on the editor I get after some time a random modification of the file. If I notice it I can CTRL+Z the change, but this is making atom unusable.
I love this editor please help me with this bug :)

**Comment by 50Wliu** [comment]
Since it only happens on Javascript files, and you happen to have a JS package installed...can you try to reproduce this in safe mode (`atom --safe`) and see if the bug still occurs?  Thanks!

**Comment by matteo-ronchetti** [comment]
I've noticed it happens in JS file but I'm not sure it happens only in JS files
In safe mode I don't get this bug, should I try disabling the package?

**Comment by 50Wliu** [comment]
Sorry for the late response.  If it's still happening - yes, you should definitely report it to the jshint package.
