### ISSUE TITLE
Initial window load UI can be improved

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#9294]
![initial load](https://cloud.githubusercontent.com/assets/2766036/10740328/0df89310-7bf8-11e5-8c91-9f01974ef968.png)
There are a couple of issues here:
1. The only menu that appears is `Atom`.  If you click on that the commands that normally go in the `Atom` menu on Mac appear, but with the `Cmd-` part of the keyboard shortcut stripped off (eg `Cmd-R` --> `R`).
2. A large portion of the screen is white, which seems related to #8847.
3. As briefly mentioned in #8293, the window is showing up in an unmaximized state, but with dimensions that correspond to a maximized state.

Please note that I could only reproduce the first two issues on Windows 10 x64 using Atom 1.0.19, and not Atom 1.2.0-dev-9b46f7c.

**Comment by mnquintana** [comment]
> 1. The only menu that appears is Atom. If you click on that the commands that normally go in the Atom menu on Mac appear, but with the Cmd- part of the keyboard shortcut stripped off (eg Cmd-R --> R).

Definitely :+1: on this - I've seen a lot of coworkers attempt to click that Atom menu before Atom actually finishes loading, only to be confused about the result (on both Mac and Windows).

**Comment by Zireael07** [comment]
Win 7 x64 here, seen 1 & 3 but not 2.

**Comment by hiddewie** [comment]
3. When the window was maximized before it was closed last session, a new window will show up with  maximized dimensions (but not maximized) and become maximized on load of the content of the window.
(Windows 10 x64)

**Comment by 50Wliu** [comment]
Some updates since 1.0.19.  Note that all of the images below were taken on Atom 1.5.0-dev-dbf7bed (the Electron 0.36 branch).
![initial-screen](https://cloud.githubusercontent.com/assets/2766036/12060809/82395626-af45-11e5-9286-d8290d29525c.png)
This is now the initial (unmaximized) screen that appears when starting Atom.  The shortcut keys in the `Atom` menu no longer appear though.

Wait a bit more for Atom to load, and this (maximized) screen appears:
![still-loading](https://cloud.githubusercontent.com/assets/2766036/12060791/09a297d6-af45-11e5-8732-d8deec9bd500.png)
Notice how everything is scaled down appropriately to match the available area.  Not sure why the rest of that whitespace is there.  Also note how no syntax highlighting has been applied yet.  This image in particular seems to be new behavior from Electron 0.35 and up, and isn't present on master yet.

Wait a few more seconds and Atom finally finishes loading.  I also tested this in safe mode just to confirm.

**Comment by damieng** [comment]
Is this still an issue in current versions of Atom?  I've not seen this behavior.

**Comment by 50Wliu** [comment]
Can no longer reproduce either, but it might also be because I'm on a much newer/faster laptop now.  The `untitled - Atom` part in the title bar does flash for a second though before it gets replaced with the correct filepath.

**Comment by 50Wliu** [comment]
Looks like these issues have been solved.
