### ISSUE TITLE
find and replace covers selected word

### ISSUE THREAD

**Issue by Huaraz2** [atom/atom#9295]
Hi,

I have created my own syntax theme but now when I use the find/replace tool it covers the word with the same colour as I us for selecting lines of code but I can't see what it has written.  Is this normal? have attached a picture as help if this is confusing.
![find and replace opac colour](https://cloud.githubusercontent.com/assets/8998661/10742290/4c842686-7c24-11e5-9d03-54a3dd68a357.png)

**Comment by thedaniel** [comment]
Can you link to your syntax theme? It's not normal to cover up the results, but you might just have some overly aggressive css selectors or something.

**Comment by Huaraz2** [comment]
ok here it is https://atom.io/themes/the-matrix-syntax

**Comment by Huaraz2** [comment]
FIxed with commit bdbd11a2bb688dfba3713b7a769bc256faa74b65 :smiling_imp:
