### ISSUE TITLE
can't install any package 

### ISSUE THREAD

**Issue by MohamedTita** [atom/atom#9298]
Unable to download https://www.atom.io/api/packages/color-picker/versions/2.0.13/tarball: DEPTH_ZERO_SELF_SIGNED_CERT

O.S Fedora 22

**Comment by izuzak** [comment]
Are you still seeing this problem? Are you behind a proxy of some kind? This works fine for me:

```
$ apm install color-picker
Installing color-picker to /Users/izuzak/.atom/packages ✓
```

Also cc @thedaniel

**Comment by izuzak** [comment]
This issue was moved to atom/atom.io#36
