### ISSUE TITLE
Graphical glitch when waking up OS X from retina-MBP to non-retina monitor

### ISSUE THREAD

**Issue by Gurpartap** [atom/atom#9300]
Steps I took:

1. Have a few windows open in Retina MacBook Pro.
2. Close the lid (OS X sleeps).
3. Connect MacBook Pro to monitor (Apple Cinema Display via Thunderbolt in my case).
4. Without ever opening the mbp's lid, wake up OS X to the connected monitor by pressing keyboard keys.
5. All atom windows will only attempt to render 1/4th of their frame (2nd quadrant — top left one). The rest are rendered white. See attached screenshot.
6. Resizing a window fixes its rendered frame.

![screen shot 2015-10-27 at 10 25 52 am](https://cloud.githubusercontent.com/assets/39792/10749935/fa5e8d16-7c95-11e5-826c-e99bb8ae570c.png)

Looks like it couldn't figure that the screen has switched to non-retina one.

**Comment by 50Wliu** [comment]
This looks like a duplicate of #9226 - please subscribe there for updates.

**Comment by Gurpartap** [comment]
Thanks!
