### ISSUE TITLE
Files still highlighted even after pushed

### ISSUE THREAD

**Issue by trd-leoalexander** [atom/atom#9301]
I'm really having problem lately recognizing which files I recently modifying after pushing a certain branch on github.com. Atom was not like this before, After each pushed it automatically clean my file explorer by removing all highlighted files but now it's not. 

![untitled](https://cloud.githubusercontent.com/assets/11266104/10751244/824f5016-7cb9-11e5-9578-787a4e0c1310.png)

Thanks.

**Comment by thedaniel** [comment]
This issue was moved to atom/tree-view#628
