### ISSUE TITLE
Centos7.1(1503) has gone wrong ,and  can't recover(atom 1.0.19.01.fc21 installed)

### ISSUE THREAD

**Issue by thermalogic** [atom/atom#9303]
After atom 1.0.19.01.fc21 installed in Centos7.1(1503), Centos  has gone wrong and  can't recover

**Comment by thedaniel** [comment]
Can you provide a little more information? How did you install Atom, and what kind of problems did it cause?

**Comment by thermalogic** [comment]
I downloaded  atom.x86_64.rpm(1.0.19.01.fc21 ) form github,then install it :

#sudo yum localinstall atom.x86_64.rpm
 
on Centos7.1(1503), then,

# atom

atom run,then I do some operation in atom , about 3-5 operations（any type of operations),Centos7.1(1503) always gone wrong and can't recover.

**Comment by 1dot75cm** [comment]
@thermalogic  Please try https://copr.fedoraproject.org/coprs/mosquito/atom/ . It applies to the Centos7.1.

**Comment by thermalogic** [comment]
ThankS
