### ISSUE TITLE
[ can't be typed on azerty

### ISSUE THREAD

**Issue by TomVeuskens** [atom/atom#9304]
] is fine but [ doesn't work on an AZERTY keyboard

**Comment by izuzak** [comment]
Thanks for the report, @TomVeuskens -- I think this is a duplicate of https://github.com/atom/atom-keymap/issues/35. Can you check that for advice and subscribe for updates? If I misunderstood your report, please let me know. (There's also https://github.com/atom/atom-keymap/issues/37 which is related.)
