### ISSUE TITLE
Atom vertical line between curly brace

### ISSUE THREAD

**Issue by tsouhaieb** [atom/atom#9312]
Hello, sorry for the bothering, but i installed atom 1.0.19 and i can't get the vertical line between two curly brackets when i'm inside a function, the line in the red ellipse in the image(the photo is not of my version), is absent from my installed version and i can't get, i searched for a package but i didn't find, please if some one help me with a name of a package to added it or a configuration, and sorry for my bad english
![atom-editor copy 1](https://cloud.githubusercontent.com/assets/15350774/10773446/aa060036-7cfb-11e5-8a77-cad8e7140165.png)

**Comment by mnquintana** [comment]
Go to Settings and make sure Show Indent Guide is enabled. If it is, and you still don't see an indent guide, then try using a different syntax theme (like One Dark) - it could be that the syntax theme you're using is hiding them. Does that help?

<img width="533" alt="settings_-__users_machistequintana_code_campus-map_-_atom" src="https://cloud.githubusercontent.com/assets/823545/10774603/82e57324-7cd8-11e5-8514-d79b894cc011.png">

**Comment by tsouhaieb** [comment]
thanks it works.

**Comment by sagespidy** [comment]
thanks
