### ISSUE TITLE
CTRL+R freezes Atom

### ISSUE THREAD

**Issue by greencopper** [atom/atom#9315]
Pressing CTRL+R in order to jump to a method in a PHP file freezes Atom version 1.0.19.

No extra plugins installed, only core.

**Comment by Zireael07** [comment]
How big is the file?

**Comment by thedaniel** [comment]
Even better if you can provide us the actual file. Also, what platform?

**Comment by greencopper** [comment]
I have tried using several different files. A minor PHP file that requires a class with a single method is enough to make it freeze. However, only if c-tags are used. If no c-tags exists Atom displays "The project has no tags file or it is empty."

The platform is Linux Debian 8.
