### ISSUE TITLE
Atom freezes momentarily when deleting a variable

### ISSUE THREAD

**Issue by tekina** [atom/atom#9316]
![oct 28 14 52](https://cloud.githubusercontent.com/assets/5358503/10784369/b22b946e-7d83-11e5-940e-f85d733fc7d0.gif)

Editor freezes for a few seconds when deleting a variable(or symbol?). 

Atom v1.0.19
OSX El Capitan 10.11

**Comment by thedaniel** [comment]
Can you reproduce this in atom's safe mode?

**Comment by tekina** [comment]
Does not occur in safe mode. I'm suspecting it has got something to do with the tags it generates for searching method names etc.

**Comment by thedaniel** [comment]
If it doesn't happen in safe mode, it probably has to do with a community
package you've installed. You might want to take a look at what you have
installed and try disabling (or perhaps) updating the likely suspects and
see if it helps.

**Comment by jeancroy** [comment]
Is that python ?
You probably have a community package along the line of `autocomplete-python` that recompute the symbols you haves. That would be the proper place to open the issue.

**Comment by tekina** [comment]
@jeancroy yes, that's ruby. I'll look into packages related to that and open an issue there if needed.
