### ISSUE TITLE
Atom background transparency

### ISSUE THREAD

**Issue by crper** [atom/atom#9321]
atom can achieve transparency effects similar background terminal it;
If you can, write for the front, it is very unwieldy;
Configuring a gulp file synchronization monitor changes to the browser; translucent effect while watching the side terminal can write, can save a lot of time
![image](https://cloud.githubusercontent.com/assets/8272877/10792022/ee509664-7dc5-11e5-8fde-59411b8d69bf.png)

Thank you!!!!

**Comment by alexandernst** [comment]
This is indeed something interesting. It can be easily done in KDE (setting the opacity of the window), but it would be nice if Atom could do that natively. On the other hand, for this to work, properly working hardware acceleration would be required.

**Comment by FezVrasta** [comment]
Is there any chance to see this feature implemented? it shouldn't be much different from the option we now have to switch to frameless window style.
