### ISSUE TITLE
Close tab when splitting it into a new pane

### ISSUE THREAD

**Issue by htor** [atom/atom#9322]
Is it possible when I right-click a tab and select split-{up,down,right,left} to have that tab close, since I now have two tabs open with the same file (the original and the new split pane)?

Don't know if this is possible today - haven't found any package for it.

**Comment by mlms13** [comment]
I'd also love to see this behavior. Perhaps this issue is duplicate of #4738, which might be getting fixed in #7953?

**Comment by htor** [comment]
@mlms13 Looks like you're right. I hope #7953 will fix this soon, because I'm running out of tab space!

**Comment by 50Wliu** [comment]
Ok, closing this in favor of #4738 then!  Thanks @mlms13.
