### ISSUE TITLE
Can't fetch packages when backspace character in username, Windows

### ISSUE THREAD

**Issue by vladdeSV** [atom/atom#9323]
I made my username the backspace character `` (`Ctrl`+`Backspace`, on Windows 7), which I think is the reason to why Atom can't fetch packages.

Here are some screenshots: http://imgur.com/a/Wk0ik

The install path in the last image does contain a backspace character, only it's not visible; ...`are installed to C:\Users\\.atom\packages`

This is on Windows 7 :checkered_flag: , Atom v1.0.19

**Comment by 50Wliu** [comment]
That's a...rather interesting choice of username :P.

**Comment by vladdeSV** [comment]
This is fixed as of Atom v1.1.0, Windows 7 :checkered_flag:
