### ISSUE TITLE
Atom hangs on large directories/files and when window switching

### ISSUE THREAD

**Issue by MatthewHerbst** [atom/atom#9325]
I used the command `atom .` to open the root level of a large SVN-controlled project. Atom takes a fairly long time to open this, and is laggy while trying to scroll through/open directories using the file explorer. In addition, opening a large file (say, an 1800 line shell script) takes longer than it should. Further, if I open the large file, then switch to Chrome, then switch back, the editor often freezes forcing me to wait several seconds before giving me the ability to scroll/edit again; often it simply crashes the editor.

Is this a known bug/being addressed at all? I feel like I can't be the only one this is happening to.

OSX 10.10.5
MBP 2012 (2.5GHz Intel Core i5, 8 GB RAM)
Atom 1.0.19

**Comment by benogle** [comment]
Closing in favor of #1596, #1847, #8851, and https://github.com/atom/atom/issues/6692

> Is this a known bug/being addressed at all?

Yes, performance things like this are being worked on from a couple different angles.
