### ISSUE TITLE
Crashing when opening a file and minimizing a folder

### ISSUE THREAD

**Issue by drbloxy** [atom/atom#9327]
When I open a file called ball.dts, leave the window open, and then close the folder named items that is 2 folders away, the editor crashes. That is the only one that I can close and it crashes, other files don't do anything. When I change tabs, or close the folders except for items, it also doesn't crash. 

(I can't check the file size right now)

**Comment by Zireael07** [comment]
What happens if you don't close the folder? Or if you open another file? How big is the file? The project?

**Comment by 50Wliu** [comment]
In addition, can you reproduce this in safe mode (`atom --safe`)?

**Comment by drbloxy** [comment]
sure, when I get home

**Comment by pablobb** [comment]
same here, even when running atom -- safe. No error, just this window:
![5874fff2e619628856c36253d9c2765cf7145ca083 1](https://cloud.githubusercontent.com/assets/217570/10845991/839001aa-7f0c-11e5-9fe4-e6e08d460deb.png)

**Comment by hitch90** [comment]
I have this problem too, after update. I tried reinstal lastest stable version but it didnt resolve issue

**Comment by pablobb** [comment]
Well all started working when I deleted all atom folders on hard drive.
Unfortunately windows Uninstaller leaves a lot of files.

pon., 2 lis 2015, 10:57 Tomasz użytkownik <notifications@github.com>
napisał:

**Comment by pablobb** [comment]
And there is also another catch, at least on windows. Atoms create its shortcut not to atom.exe, but it's starting update.exe and then atom editor. So if u install 1.0.19 without bug, at the second start u will have again 1.1 with libhit2 error.

**Comment by damieng** [comment]
It appears that the issue went away with clearing of the atom folder?

With regards to the other issues about shortcuts and not updating - those are addressed in the next 1.7.0 release.
