### ISSUE TITLE
Tree View bug when opening multiple files from command line.

### ISSUE THREAD

**Issue by bkboggy** [atom/atom#9328]
If I open a single file with Atom from a command line (atom some_file.cpp), it opens Atom, displays the current directory and its contents in the Tree View and displays the file which was passed as the argument.  So, everything works properly.

![bug1](https://cloud.githubusercontent.com/assets/5036152/10810884/facd443a-7dc2-11e5-8d81-806998dfc207.JPG)

However, if I open multiple files (atom some_file1.cpp some_file2.cpp some_file3.cpp), it opens Atom, display the files which were passed as the arguments, but does something strange in the Tree View:

![bug](https://cloud.githubusercontent.com/assets/5036152/10810846/5c05040a-7dc2-11e5-8e33-52c907fed9ef.JPG)

As you can see, instead of the current directory and its contents, it displays each file from the argument list as a directory.  However, they're all empty.  If I close the displayed files, there is no way to re-open them by clicking those empty directories.... they're just empty artifacts.  If I right click and show each of those directories in the explorer, it opens the proper current directory in the explorer.  If I right click and choose to open in the new window, it'll open a new instance of Atom with the selected file displaying and proper Tree View on the left.

Note that this only occurs if you are doing this with existing files.  If any of the arguments is a non-existing file, then you get a mixture of the two cases:

![bug2](https://cloud.githubusercontent.com/assets/5036152/10810930/a06015ee-7dc3-11e5-9a09-00e09f4c3127.JPG)

If all of the arguments are non-existing files, then proper Tree View is displayed, as none of the files actually exist, so they're just displayed and need to be saved.

I've tried this on two different machines and its the same result.  So, sounds like a bug.

Windows 7 SP1 & Windows 10
Atom 1.0.19

**Comment by izuzak** [comment]
Thanks for the detailed report. I noticed you also opened https://github.com/atom/tree-view/issues/632 -- I don't think there's a need to have two issues track the same problem, so I'm closing this in favor of that issue.

**Comment by bkboggy** [comment]
Yeah, sorry.  I wasn't sure if both trackers are monitored or merged somehow, so I kind of did a shotgun effect there.
