### ISSUE TITLE
No way to turn off Line Wrapping

### ISSUE THREAD

**Issue by lifeiscontent** [atom/atom#9329]
I'd like to turn off the soft line wrapping in Atom, there seems to be a few options that have to do with soft wrapping whitespace, but none seem to make it so an entire line of code will not wrap.

![issue](https://cloud.githubusercontent.com/assets/180963/10811920/488a8eca-7dce-11e5-8e6b-a7adc65b70f7.png)

**Comment by izuzak** [comment]
Hi @lifeiscontent -- does running the "Editor: Toggle Soft Wrap" command from the Command Palette help? Also, please provide a bit more information, as suggested [here](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues).

**Comment by lifeiscontent** [comment]
@izuzak that totally worked, thanks for the quick intermediary fix!

OS: Windows 10
Atom Version: 1.0.19

seems not all of the keybindings aren't working either, I noticed the markdown preview toggle doesn't work either from the keybinding.

**Comment by izuzak** [comment]
Also, have you checked the "Soft Wrap" config option for the language-gfm package? (Settings > Packages > langauge-gfm > Soft Wrap)

**Comment by izuzak** [comment]
> seems not all of the keybindings aren't working either, I noticed the markdown preview toggle doesn't work either from the keybinding.

Happy to hear that.

> seems not all of the keybindings aren't working either, I noticed the markdown preview toggle doesn't work either from the keybinding.

I suggest you open new issues for those problems and provide more details. For example, if you suspect that keybindings are not working, sharing a screenshot of the keybinding resolver is helpful:

https://atom.io/docs/latest/hacking-atom-debugging#check-the-keybindings

Thanks!

**Comment by lifeiscontent** [comment]
@izuzak there is no way for me to goto **Settings > Packages > langauge-gfm > Soft Wrap**

**Comment by izuzak** [comment]
@lifeiscontent Why not? At which step of that process are you stuck? It would really help if you could start sharing a bit more information :)

**Comment by lifeiscontent** [comment]
@izuzak good idea.

![image](https://cloud.githubusercontent.com/assets/180963/10812513/208d2d3c-7dd4-11e5-95f2-fa100c0daea5.png)


as you can see in the image, there is no settings gear to click on

**Comment by izuzak** [comment]
@lifeiscontent And what happens if you just click the package card?

**Comment by lifeiscontent** [comment]
@izuzak ohoho! Tricky. its a UX Bug. that didn't make sense to me at all.

**Comment by lifeiscontent** [comment]
@izuzak thanks for your speedy efforts :+1:

**Comment by izuzak** [comment]
You'll be interested in https://github.com/atom/settings-view/pull/676, which should be included in the next release.

**Comment by lifeiscontent** [comment]
@izuzak awesome, I love how progressive the team is at Github. Keep up the awesome work :+1:

**Comment by tempusrname** [comment]
This no longer works. Disabling soft-wrap or running 'Editor: Toggle Soft Wrap' command does not disable line breaks. There is no way for me to disable line breaks.

**Comment by bennypowers** [comment]
for very long strings like datauris, I always get soft wrap, regardless of settings

**Comment by xh3b4sd** [comment]
So there are people still having issues with this, including me, but the issue is closed. Feels wrong. How can I make Atom not wrap long lines at all?

**Comment by jonathan-ciandt** [comment]
The bug persists, have a new issue?

**Comment by haggen** [comment]
Still having this, soft wrap is effectively disabled (both in Editor settings and in package settings) and it still wraps long lines (at column 499).

**Comment by prometheanbob** [comment]
Same. no matter settings, very long lines still break. Around column 520 for me

**Comment by gerbsen** [comment]
Same here :(

**Comment by chrishough** [comment]
Same problem for me too.

**Comment by rsese** [comment]
Soft-wrapping at 500 characters was added to prevent Atom hanging in some cases in 1.15 /cc https://github.com/atom/atom/pull/13820.  In Atom 1.22 (available now in beta), there's a new setting `Settings > Editor > Max Screen Line Length` that let's you adjust this value.  The setting was added in https://github.com/atom/atom/pull/14495.
