### ISSUE TITLE
Add option to toogle the wrap guide

### ISSUE THREAD

**Issue by arcticicestudio** [atom/atom#9330]
I don't know if this belongs here or into the [specific repositiory](https://github.com/atom/wrap-guide).
It would be nice if the [wrap-guide](https://atom.io/packages/wrap-guide) package could be toggled via Command Palette or menu (*Edit* -> *Toggle Wrap Guide*).
I've disabled the package because it bothers me, but sometimes I need it.
Actually you have to navigate to the settings view, search for the wrap-guide package and enable/disable it all the time.

**Comment by thedaniel** [comment]
This issue was moved to atom/wrap-guide#50
