### ISSUE TITLE
(ctrl + backspace) or (ctrl + del) unexpected behaviour

### ISSUE THREAD

**Issue by prog666** [atom/atom#9331]
in this case
```javascript
container.hover(func, /*cursor here*/                              func2);
```
when I hit (ctrl + del) I expect it to delete all spaces before 'func2', but I get 'func2' deleted too. It's really annoying. Other text editors like sublime behave correctly in this case.

**Comment by thedaniel** [comment]
This is working as I would expect - ctrl-del is bound to "delete to end of word", and whitespace characters aren't recognized as a word. alt-del is bound to "delete to end of subword" which will give you the behavior that you want. Switching those keybindings in your `keymap.cson` might give you the behavior you're familiar with.

**Comment by prog666** [comment]
alt+delete works the same way as ctrl+delete, can you help me with keymap? or any link to the docs?
