### ISSUE TITLE
[FR][Meta] Split UI and "core"

### ISSUE THREAD

**Issue by alexandernst** [atom/atom#9334]
The idea is very simple (but doing it would probably cost a lot). What this feature request is is a proposal for splitting the UI from the "core" part of the editor in such a way that the UI and the core would communicate via an abstracted communication channel (be it some sort of signals/events when on a local machine, be it via network when on a remote machine, etc)

Let me define the terms that I'm using:

UI: the visual part that we use too interact with Atom. Panes, tabs, editor, tree view, etc...
core: the *thing* that does file management (open/close/save files), holds unsaved buffers, performs searching in the FS, etc.

In other words, The UI would be the `V` and the `C` and the core would be the `M` if I had to describe that thing with a `MVC` example.

Such a split would allow Atom to:

* edit files remotely (like vim/emacs over ssh)
* connect to another Atom core and interact with it (collaborative editing between 2+ people)
* speed up Atom (tricky, First launch won't have any speed boost, but multiple instances won't need to do the entire startup process, but only search for an already available core and bind to it)
* make Atom's UI bullet proof (an UI crash, which is still a thing, won't close opened files nor lose unsaved buffers, as those would be living in the core instead of the UI)
* probably more

**Comment by alexandernst** [comment]
This hasn't received comments or tags. Is this feasible?

**Comment by lee-dohm** [comment]
I don't feel that doing this is feasible in the 1.0 timeframe, personally. I'll mention it to the rest of the team.

**Comment by nathansobo** [comment]
I don't think going full RPC between the model and the view is really feasible given APIs that we are committed to supporting going forward. Even if we didn't have this API contract, I don't think the trade-offs of creating this kind of process barrier are worth the costs. Keeping everything in the same context makes Atom really easy to modify, which is a primary goal of the project.

We are considering something *similar* to this idea, however, which is starting to drop the core editor implementation to native code.
