### ISSUE TITLE
Size for pointer

### ISSUE THREAD

**Issue by pustovalov** [atom/atom#9336]
Hey guys, updated atom to 1.1, and size for pointer changed:

![screencast 2015-10-29 17-10-43](https://cloud.githubusercontent.com/assets/1568885/10835550/dfcf4e00-7e60-11e5-8b8f-ae2689263f39.gif)

Is it bug in atom or in some plugin?

**Comment by mnquintana** [comment]
Have you tried checking this in safe mode? (`atom --safe`) If you don't experience this in safe mode, then it's likely a package you have installed.

**Comment by 50Wliu** [comment]
Is this using seti-syntax?

**Comment by raphaelcuba** [comment]
I have the same trouble. And yes, i'm using seti-syntax.

**Comment by pustovalov** [comment]
found the solustion:
https://github.com/jesseweed/seti-syntax/issues/106

@raphaelcuba

**Comment by raphaelcuba** [comment]
Thanks @pustovalov!
