### ISSUE TITLE
Native application

### ISSUE THREAD

**Issue by TuomLarsen** [atom/atom#9337]
(I apologize in advance if this is not the right place to ask. Please feel free to close immediately if not appropriate here.)

Please, are there any plans in very distant future to move away from web-based application stack (Node, JS, Chromium, ...) to the more native technologies like Skia, Cairo, Scintilla, Cocoa, ..?

I'm mostly asking about the editing component, whether it wouldn't make sense to implement it with native drawing library, instead of DOM.

My only motivation to ask such question is the belief that such move would make Atom editing more responsive and performant.

Thanks!

**Comment by alexandernst** [comment]
I'd say 'No' as you're just asking for something that is not Atom. You're basically asking the devs to rewrite every simple piece of the editor (as it's based on Node and uses the DOM to draw everything).

**Comment by izuzak** [comment]
It's hard to make "very distant future" predictions and plans, as I'm sure you understand, so we can't really promise anything. But the answer for now is "no". Thanks for the question!
