### ISSUE TITLE
Always opens previous project. Even with settings changed. 

### ISSUE THREAD

**Issue by VectorLightning** [atom/atom#9338]
I discussed it with someone here: 
https://discuss.atom.io/t/open-empty-editor-on-start-does-nothing/22127/6

...and I was told that this PR might have something to do with it. 
https://github.com/atom/atom/pull/8397

**Comment by thedaniel** [comment]
This PR implements the setting you describe, but hasn't been merged yet: #9042

**Comment by VectorLightning** [comment]
I find it odd, myself, but all I did was go to the site and hit download. I'm not a beta tester or anything, I thought I got the main build.

**Comment by Ben3eeE** [comment]
This is a duplicate of https://github.com/atom/atom/issues/6605 and the setting has been around since Atom 1.8.
