### ISSUE TITLE
Cursor goes missing, when admin password prompt is triggered for a write protected file during editing

### ISSUE THREAD

**Issue by Anubhav410** [atom/atom#9340]
1. Using the editor on mac.
2. If a file has write permission restrictions, mac OS prompts for the admin password(sudo) , for editing. But after that the cursor stops showing. I have to switch to some other file and come back to re focus the cursor. Or also switch to some other application and come back. (CMD+TAB)*2.

**Comment by thedaniel** [comment]
Thanks for the bug report!

**Comment by michaeljdennis** [comment]
+1

**Comment by fuzzy76** [comment]
And if I force-quit Atom, the file is only partially written. I just lost half my /etc/hosts because of this. :(

**Comment by adamgoose** [comment]
+1

**Comment by maxbrunsfeld** [comment]
> And if I force-quit Atom, the file is only partially written. I just lost half my /etc/hosts because of this.

@fuzzy76 I think this is a separate bug than the issue with the missing cursor. Could you describe some exact steps to reproduce this behavior and open another issue for it? Thanks!

**Comment by fuzzy76** [comment]
@maxbrunsfeld The steps are the _exact_ same. Though my experience more closely matches #9360 (the entire app freezes, I cannot switch documents).
