### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by nwinger** [atom/atom#9341]
I'm working on a project, both from my mac and my windows (10) pc. 
When pulling the latest code from my repo this morning, and trying to open the folder (or any single file from within the folder for that matter), I get a dialog saying "The editor has crashed". I can either close the window, reload or keep it open - none of them are viable options and the editor keeps crashing. I've tried uninstalling, removing all plugins and themes, installed the beta version, but nothing appears to be working.

**Comment by kkHAIKE** [comment]
same issue #9339

**Comment by 50Wliu** [comment]
Thanks @kkHAIKE!
