### ISSUE TITLE
Swedish letters sorted wrong in the folder/file-sidebar

### ISSUE THREAD

**Issue by emil-nasso** [atom/atom#9342]
The swedish letters `Å`, `Ä` and `Ö` are placed last in the alphabet. The sorting in atom treats them as `a` and `o`, i think.

![https://dl.dropboxusercontent.com/s/hze1a285agokxrc/2015-10-30%20at%2008.46.png?dl=0](https://dl.dropboxusercontent.com/s/hze1a285agokxrc/2015-10-30%20at%2008.46.png?dl=0)

![https://dl.dropboxusercontent.com/s/s0p502ynvqr9dna/2015-10-30%20at%2008.49.png?dl=0](https://dl.dropboxusercontent.com/s/s0p502ynvqr9dna/2015-10-30%20at%2008.49.png?dl=0)

That last one is a bit wierd. If it the second letter, `ä` was treated as an `a` it should have been on top of the list.

The swedish alphabet: https://en.wikipedia.org/wiki/Swedish_orthography (We are not the only nation using these letters though.)

**Comment by thedaniel** [comment]
I think this could be fixed similarly to https://github.com/atom/sort-lines/pull/8 - thanks for the report.

**Comment by thedaniel** [comment]
This issue was moved to atom/tree-view#634
