### ISSUE TITLE
no plugin preview - maybe proxy reason?

### ISSUE THREAD

**Issue by stebiger** [atom/atom#9346]
Hey,

I am using atom on Windows 7 and am sitting behind a corporate proxy.

I already configured my %USERHOME%/.atom/.apmrc to have
http_proxy = foo
https_proxy = foo

and if I want to install plugins that is working pretty fine.

But what is not working is that I can't have a look on the preview/information of a plugin.
After some time of loading I get:

![image](https://cloud.githubusercontent.com/assets/8200750/10844969/59c10f0c-7f04-11e5-9404-4c81887c644c.png)

And I also have broken icon images on Install setttings:

![image](https://cloud.githubusercontent.com/assets/8200750/10844978/677b05ee-7f04-11e5-8f98-c77057a30dd9.png)

Am I missing anything?

Regards,
Stefan

**Comment by brendanfalkowski** [comment]
Plugin thumbnails have been broken for like a year for me. Doesn't matter what network I'm connected to. No special firewalls or proxies here. Rarely (like once every 2 months) they do load.

**Comment by alexjurkiewicz** [comment]
You can fix this by running Atom with either the `--proxy-server` commandline option, or with `http_proxy` and `https_proxy` environment variables set. See my OP in #5725 for more info.
