### ISSUE TITLE
Wrong type of comments when using toggle-line-comments in .sce files

### ISSUE THREAD

**Issue by mammothb** [atom/atom#9349]
On Windows, when I use the ctrl-/ shortcut for toggle-line-comments in .sce files, the line / block is commented using `/*...*/` which is not recognized by scilab. It used to work fine and used `//` instead.

**Comment by vection** [comment]
+1 Same problem in julia.
Instead of toggling `#` comments, it's toggling `*\` \ `\*` comments

**Comment by acontreras89** [comment]
Shouldn't be this addressed by the language package?

**Comment by 50Wliu** [comment]
@acontreras89 Problem being that Julia has the correct comment type in its settings :confused:.  For some reason it's falling back to the default `/* */` instead.
https://github.com/JuliaLang/atom-language-julia/blob/a4953fe57f57a800a544b8c832501cde480022a1/settings/language-julia.cson#L3

@mammothb's issue should be redirected to the [language-scilab](https://github.com/JeremyHeleine/language-scilab/) package.

**Comment by mammothb** [comment]
Package settings was stored in `scoped-properties/` instead of `settings/`. Owner of the Scilab language package, which I was using, deleted his account before problem was fixed. I've fixed it in [language-scilab-atom](https://github.com/mammothb/language-scilab-atom) package.

@vection may want to open a new issue for his problem with julia.
