### ISSUE TITLE
copying rebuild errors to the clipboard is not possible

### ISSUE THREAD

**Issue by despairblue** [atom/atom#9351]
That makes it hard to report them.

![screen shot 2015-10-30 at 14 13 04](https://cloud.githubusercontent.com/assets/927609/10846503/7679bad4-7f10-11e5-8b2c-86b75f3da470.png)

Copying them from the chrome dev tools works.

**Comment by benogle** [comment]
What UI is this? Is that an `atom-text-editor`? Maybe this is in https://github.com/atom/incompatible-packages ?

**Comment by despairblue** [comment]
@benogle sorry, haven't thought about this being confusing without context. Yes it is the 
https://github.com/atom/incompatible-packages view. I'll reopen it there.
