### ISSUE TITLE
[MAC] Project Folders lost after crashes and force quits

### ISSUE THREAD

**Issue by EvHaus** [atom/atom#9352]
If Atom 1.1.0 crashes, or is force quitted on a Mac, all project folders will be lost for me. I've been able to reproduce this since 1.0.0.

This is related to the issue described in #9643

Is this a known issue?

**Comment by mnquintana** [comment]
@globexdesigns Does https://github.com/atom/atom/issues/4161 cover this issue?

**Comment by globexdesigns** [comment]
Hmm, #4161 doesn't mention anything about Project Folders specifically. I guess it depends on what the fix for #4161 will cover.

**Comment by cakecatz** [comment]
I lose Project Folders when I use `window:reload` from 1.1.0.
@globexdesigns Did you only lose when crashed?

**Comment by globexdesigns** [comment]
I lose Project Folders even when I use "File > Open New Window".

Is done by design in Atom? Hiding project folders for any new window or session, or after a crash seems like a bug to me. I recommend changing this behavior. I have to manually re-add all my projects every time and it's incredibly frustrating.

**Comment by globexdesigns** [comment]
A very simple repro step:

- Launch Atom (Window 1)
- Added a Project Folder
- Go to File > New Window (Window 2)
- Window 2 will launch without any project folders (weird, but ok.. not a huge deal)
- Close Window 1
- Close Atom
- Re-launch Atom
- Project folders are gone with no way to recover

**Comment by mkendall07** [comment]
I'm having this issue as well. Is there a way to save projects and restore after this happens?

**Comment by liuderchi** [comment]
I found a workaround to save project folders without additional packages.
(version: Atom `1.10.2`, Ubuntu 14)

__BACKUP Project Folders__
when you wanna save current project folders
(maybe right after step 3 from @EvNaverniouk 's example ), backup this file:

```
cp ~/.atom/storage/application.json ~/.atom/storage/application.json.bkp
```

__RESTORE Project Folders__
before you Re-launch Atom to expect seeing saved project folders, restore back:

```
cp ~/.atom/storage/application.json.bkp ~/.atom/storage/application.json
```

__NOTE__

`~/.atom/storage/application.json` is updated each time when you:

- add a project folder
- remove a project folder
- create a new window
- close a window
    - so some project folders will lost if the window you closed is _not the last one_.

**Comment by gabfl** [comment]
This bug is still happening in version `1.12.9`, exactly as described by @EvNaverniouk

**Comment by gabfl** [comment]
IMO this issue has been resolved for ~6 month. I did not encounter the bug with newer versions of Atom

**Comment by 50Wliu** [comment]
Thanks for the update @gabfl. If anyone else is still experiencing this issue on Atom 1.23.3 or later, please let me know and I'll reopen this!
