### ISSUE TITLE
AST-based language support (syntax highlighting, linting, etc)

### ISSUE THREAD

**Issue by phlogisticfugu** [atom/atom#9353]
One of the new things out with [Babel 6](https://babeljs.io/blog/2015/10/29/6.0.0/) is a vision of it's use in tools like Atom for syntax highlighting, linting, code completion, and other language-dependent features.

Atom, as I understand it, leverages TextMate grammars.  While this has been a great way to get instant support for a wide ecosystem of languages, it depends on regular expressions, which can have bad performance edge cases.  For example, any time I happen to load a large minified JavaScript file in Atom, it effectively freezes.

Perhaps if there was support for some mechanism within Atom that would take an AST generated by something like Babel 6, transform or parse that into a language-agnostic form, and use that for language-specific interactions within Atom (e.g. markers for syntax highlighting), we could get much better performance, and be able to leverage a growing ecosystem of AST parsers.

**Comment by ngryman** [comment]
:+1: Please, yes, totally.

This is 2015, we need smart autocomplete, highlighting and everything else :)
I was messing around with Chrome DevTools source code and I think they are using [acorn](https://github.com/ternjs/acorn) for this. Do you guys intend to support this?

Thanks!

**Comment by thedaniel** [comment]
@maxbrunsfeld has been doing some experimenting with tokenizing buffers using a scanner - you can read more about it in this comment and some of the follow-ups https://github.com/atom/atom/issues/979#issuecomment-77778162

**Comment by ngryman** [comment]
@thedaniel Thanks, but the discussion has been closed :(
This would definitely be a new feature, but it could be complementary to the existing parser.
In fact Eclipse uses both lexical and syntaxic parsing: http://stackoverflow.com/a/7243859.

**Comment by alexandernst** [comment]
Any news on that? Or any other issue/branch that we can track?

**Comment by 50Wliu** [comment]
https://github.com/tree-sitter/tree-sitter

**Comment by danielbayley** [comment]
https://github.com/wooorm/lowlight#lowlight--

**Comment by maxbrunsfeld** [comment]
This has shipped for many languages. Enable the “use tree-sitter parsers” setting in the settings view. It will be on by default in a couple releases.
