### ISSUE TITLE
Wrong command names shown after installing shell commands in Atom Beta

### ISSUE THREAD

**Issue by jasonrudolph** [atom/atom#9361]
When you install the shell commands in Atom Beta, the confirmation message says, "The shell commands `atom` and `apm` are installed." It should instead say, "The shell commands `atom-beta` and `apm-beta` are installed."

To reproduce this issue, choose "Atom" in the menu bar, and then choose "Install Shell Commands".
#### Screenshot

![screenshot](https://cloud.githubusercontent.com/assets/2988/10857572/7924d454-7f14-11e5-8263-6376a7bc7088.png)
#### Version info

Atom version: 1.2.0-beta0
OS version: OS X 10.11.1

**Comment by nathany** [comment]
Thanks. I was trying to figure out what the shell commands are and found this.

**Comment by svanegas** [comment]
:+1: Thank you, I was also trying to figure out why the commands weren't getting installed, it was just that **Atom Beta** commands are different.

Meanwhile, I'm using an alias, like this:

`alias atom='atom-beta''`

**Comment by nathany** [comment]
Yah, I have the same alias in my .zshrc:

```
alias atom="atom-beta"
alias apm="apm-beta"
```

But I've found that the alias isn't used for the EDITOR variable when git wants a commit message or interactive rebase. So now I'm explicitly setting: 

```
export EDITOR="atom-beta -w"
```

**Comment by vlsd** [comment]
Oh man this drove me insane! Thank you!

**Comment by jasonrudolph** [comment]
This issue still exists in the current Atom Beta (1.20.0-beta5).

Note: We have an open PR (https://github.com/atom/atom/pull/14254) that aims to resolve this issue.

**Comment by jasonrudolph** [comment]
This issue has been resolved. Here's the current behavior in Atom 1.31.0-beta0:

![image](https://user-images.githubusercontent.com/2988/44851843-97802c00-ac2f-11e8-8741-bbafa6e5f8c0.png)
