### ISSUE TITLE
Malformed indent guides

### ISSUE THREAD

**Issue by 50Wliu** [atom/atom#9369]
![indent-guides](https://cloud.githubusercontent.com/assets/2766036/10861319/82b8c54c-7f51-11e5-8954-91af714a00d9.png)
Notice how the final indent guide on each blank line is ever so slightly misaligned with the rest.  Re-opening the file or reloading Atom does not fix the issue.

Atom 1.3.0-dev-69dfdd0, Windows 10 x64, safe mode.

/cc @nathansobo @as-cii

**Comment by thomasjo** [comment]
I've seen this as well. Seems like a combination of font and font size seems to trigger it. @50Wliu Try increasing the font size and see if that "resolves" it. 

I'm hypothesizing that this is caused by issues with subpixel character width calculations; i.e. floating point round-off error.

**Comment by 50Wliu** [comment]
> Try increasing the font size and see if that "resolves" it.

Just tried this with the following results (the picture above is using 13px Consolas):
Setting the font to 12px messes up the third indent line, while setting it to 14 seems to fix it.

**Comment by thomasjo** [comment]
Yeah, there are definitely a few serious regressions I'm experienced on master now at least. I'm using the One syntax themes, and I'm getting incorrectly placed cursors on some lines; the cursor ends up being placed on top of a character for instance. Using a large font size (14px or higher) does seem to (mostly) resolve the problem, but using 12px or smaller does exhibit FP round-off errors :disappointed:

**Comment by jeancroy** [comment]
Maybe related to https://github.com/atom/atom/issues/9382 ?

>  FP round-off errors 
This looks like one pixel out of 100...  that's way less than the normal float/double range. Is Atom summing up rounded numbers ? I have a hard time understanding how this relate to being off on blank line only.

**Comment by 50Wliu** [comment]
Yup, but I can still repro this.

**Comment by poswald** [comment]
I'm trying out 1.4.0 and I'm seeing it with Monaco font at size 10 and then at 11 it went away.

**Comment by cjduncana** [comment]
![Maligned Tab Guides](https://cloud.githubusercontent.com/assets/1977082/14335528/8c8fe562-fc21-11e5-9ea4-b24d41e381f6.png)

I did what was suggested here regarding changing font-size, and the maligned tab guides just scaled with the changing size. Refer #11389

**Comment by SnoringFrog** [comment]
In Atom 1.8.0 on Windows 10, the misaligned indent guides happen fairly often (fonts: FiraCode, Hack, and the default font, all at size 12). 

Increasing the font size to 14 corrected the issue Changing the font size from 12 to 14 corrected them. Changing the font back to 12 left them corrected, but they quickly misalign themselves again once I resume editing.

**Comment by cjduncana** [comment]
I do not see this problem anymore.
