### ISSUE TITLE
Upgraded to the latest version of Atom and now it crashes on launch

### ISSUE THREAD

**Issue by scotthathaway** [atom/atom#9370]
I now get The Editor has Crashed error.  When I run atom --safe it works.  I have the latest MacOS and the latest Atom.  

Please help.

Scott

**Comment by jimmyye** [comment]
This works for me:
1.Menu - File - New Window
2.Intall all available updates (by click bottom right of the window)
3.Quit Atom and open it again, and it restored all the windows and files

**Comment by scotthathaway** [comment]
This did not work for me.  Still have the same issue.

**Comment by 50Wliu** [comment]
@scotthathaway can you please include the following information:
* `apm list --installed`
* The contents of your `init.coffee` file

Usually if safe mode works then one of your installed packages is causing the issue.

**Comment by elaberge** [comment]
Hello, I have the same issue with Atom 1.1
init.coffee has everything commented
Installed packages:
```
/Users/myself/.atom/packages (22)
├── Zen@0.16.3
├── atom-beautify@0.28.16
├── atom-terminal@0.8.0
├── coffee-compile@0.19.2
├── dash@1.3.2
├── file-icons@1.6.11
├── git-control@0.4.0
├── js2coffee@0.15.0
├── language-csharp@0.11.0
├── language-d@3.2.1
├── language-protobuf@0.5.0
├── line-ending-converter@1.3.2
├── linter@1.10.0
├── minimap@4.16.0
├── minimap-color-highlight@4.1.4
├── minimap-find-and-replace@4.3.2
├── minimap-git-diff@4.1.8
├── minimap-highlight-selected@4.3.1
├── open-terminal-here@2.1.0
├── pigments@0.18.1
├── refactor@0.6.0
└── term2@0.9.21
```

**Comment by 50Wliu** [comment]
Ok, nice to hear.  You might want to create an issue on the js2coffee repo if there isn't one already.

**Comment by scotthathaway** [comment]
Removing js2coffee fixed my issue too!  Thx!
