### ISSUE TITLE
Crash after selection of 'Application Install Update'

### ISSUE THREAD

**Issue by pantuts** [atom/atom#9374]
* Please delete this issue if it is a duplicate.

Atom: Installed from source and currently using 1.2.0-beta0-2ec1b18
OS: Manjaro Linux x86_64

Editor crashes always when I do CTRL+SHIFT+P then choose Application Install Update.
I do not know where is the log file. Please tell me what to do for how to get more information for this issue. Thanks.

**Comment by 50Wliu** [comment]
Interesting.  This might be happening because Linux doesn't have an auto-updater.

**Comment by ghigt** [comment]
I also have this issue on my ubuntu VM and on my Windows host machine. (not sure, but I think I also have the issue on my Mac)

**Comment by NiotoMOto** [comment]
:+1

**Comment by pantuts** [comment]
Current: 1.4.0-beta3-385721a

It is not crashing anymore but when Application Install Update is selected, it does nothing.

**Comment by lee-dohm** [comment]
@pantuts Sounds like you built from source at the v1.4.0-beta3 tag?

**Comment by pantuts** [comment]
@lee-dohm correct.

**Comment by lee-dohm** [comment]
When you build from source, the only way to update is to build from source again or install a released version.

**Comment by lee-dohm** [comment]
To be clear, perhaps this menu item should have a notification that comes up that informs people of this.

**Comment by pantuts** [comment]
Is Application install update specific to atom update only? how about its installed packages?

**Comment by lee-dohm** [comment]
Yes, it is only to update the application. Packages are updated in the Settings View.

**Comment by gnanadeeptu** [comment]
@pantuts May I know why this bug was closed? Today I encountered this issue on my MAC machine. This was labeled as `**needs-reproduction**`, not sure if that is still the case.

**Comment by pantuts** [comment]
@gnanadeeptu I did close this because when I updated and had latest builds, it disappeared. Let me reopen this one.

**Comment by 50Wliu** [comment]
I'm going to keep this closed as this bug applied only to Linux and not Mac.

@gnanadeeptu Please open a new issue.
