### ISSUE TITLE
Bad cursor positioning

### ISSUE THREAD

**Issue by xurde** [atom/atom#9376]
Since I updated to `1.1.0` on `OS X 10.10.5` I'm getting this weird cursor positioning issue.

<img width="390" alt="atom_1_1_cursor_position_deviated" src="https://cloud.githubusercontent.com/assets/27406/10865800/c0ac9032-8018-11e5-9039-727445008977.png">
(Cursor is supposed to be at the beginning of the line in the snapshot)

Anyone else having this issues?
Could this be somehow related to any linter plugin?

**Comment by aspin** [comment]
I also literally just updated and have this issue now too.

**Comment by pedroolguin** [comment]
im having the same problem in win 10, for a couple of days now

**Comment by benogle** [comment]
It is likely the syntax theme you are using. Any of you have seti-syntax installed? See https://github.com/atom/atom/issues/9343 for more info

**Comment by xurde** [comment]
@benogle Yes, that was my case.
Thanks!
