### ISSUE TITLE
Atom writes an space back from selected

### ISSUE THREAD

**Issue by pedroolguin** [atom/atom#9378]
I dont know how to solve this or explain it so i upload two screenshots.
The letter A is just for example.
Im using atom 1.1.0 on windows 10.
 Thanks for your time,
![atom3](https://cloud.githubusercontent.com/assets/15434529/10866705/7a369b9a-801b-11e5-9c9b-f84b77199039.png)

**Comment by pedroolguin** [comment]
The plroblem was with the seti-syntax, solved here https://github.com/jesseweed/seti-syntax/issues/106

**Comment by izuzak** [comment]
Thanks for opening an issue, @pedroolguin. Yeah, this seems like a duplicate of  https://github.com/atom/atom/issues/9343 for more information -- see that for more information, I'm going to close this in favor of that. :v:
