### ISSUE TITLE
Atom 1.2.0 Type error 

### ISSUE THREAD

**Issue by oxygen16** [atom/atom#9379]
when i upgrade Atom to 1.2.0-beta , something happen ,found that Atom display a black grid, I use Enter and delete and type something，It does'nt work!

**Comment by Arcanemagus** [comment]
Are you using one of the default themes, or a custom one?

**Comment by Arcanemagus** [comment]
@oxygen16 Would you mind reporting what the solution was in case somebody comes across this in the future?

**Comment by oxygen16** [comment]
@Arcanemagus  Sorry , I use github not a long time so some rule I don't know, yep , just like you say ,When I change my Syntax Theme to another, It's solve . and then you can replace Syntax Theme you used before
