### ISSUE TITLE
How can i set a specify font ?

### ISSUE THREAD

**Issue by agileago** [atom/atom#9387]
i want to use `Source Code Pro` fonts. so i set a font in settings. it worked.
![image](https://cloud.githubusercontent.com/assets/11799110/10872293/b9bcad76-8139-11e5-8bef-08282f76e92c.png)

but i want to use `Source Code Pro Italic` . when i set it . it is nothing.  who can tell me how to solve this ?

![image](https://cloud.githubusercontent.com/assets/11799110/10872305/e46c3e9c-8139-11e5-90c9-4bfd511fe84e.png)

it worked on sublime.  maybe atom don't support this?

![image](https://cloud.githubusercontent.com/assets/11799110/10872310/0fedda58-813a-11e5-84f7-1ed5470b2127.png)

**Comment by izuzak** [comment]
Hey @agileago -- I think this is supported. Using `SourceCodePro-It` worked for me, that's the name of the Font in OSX for me. I agree, that's not the most obvious solution. There's already an issue to improve font selection, so I'm going to close this in favor of that: https://github.com/atom/settings-view/issues/286

**Comment by agileago** [comment]
thanks @izuzak . it also worked for me .
