### ISSUE TITLE
Request for markdown scroll sync in core

### ISSUE THREAD

**Issue by banool** [atom/atom#9388]
This is a formal request for a functioning markdown scroll sync to be included in the atom core.

The lack of scroll sync and decent markdown editing, like you have Macdown for example, is a real killer for me being able to tolerate atom and I'm sure I'm not alone. This is especially concerning considering that Github itself has made such a push to have markdown become a standard, and is quite incredible that it has had to fall to members of the community, such as @mark-hahn with **markdown-scroll-sync**,  to implement features such as this themselves instead of being created by the core dev team.

The existing package is no longer supported by the original author and it doesn't appear anyone has stepped up to try and improve on the current state of things. Furthermore this package, at least in my experience (tried on multiple machines and over many version of atom), works tentatively at best, with a jerky and at times inaccurate sync, and at the worst just doesn't work at all or repeatedly crashes.

Any input on this suggestion would be welcome because I want to get the ball rolling again on making atom a great editor for markdown.

Any input on this suggestion would be welcome because I want to get the ball rolling again on making atom a great editor.

**Comment by mnquintana** [comment]
Thanks for the suggestion! It would be awesome to have this, but there is already an existing issue at https://github.com/atom/markdown-preview/issues/24, so I'm going to close this out as a duplicate. The issue's currently locked, but a PR implementing this would be absolutely welcome.
