### ISSUE TITLE
No keybinding for window:save-all on Windows and Linux

### ISSUE THREAD

**Issue by sveinfid** [atom/atom#9390]
I use Atom on both a Mac and a Windows machine, and I tend to use the "Save All" function quite often on my Mac. Also, on Windows I am quite used to the shortcut Ctrl-Shift-S for "Save All" from Visual Studio, Notepad++, etc.

Any particular reason why there is no binding for window:save-all on Windows and Linux?

**Comment by williamhallatt** [comment]
Adding the following to keymap.cson works for me (Windows 10, Atom 1.7.3):

'body':
  'ctrl-shift-S':'window:save-all'

**Comment by gdufford** [comment]
@williamhallatt, how did you know what selector to use? Also, how did you know that the save-all is scoped at the window? I've seen key bindings that reference body, window, core, and others, but no reference that spells out the current commands and the syntax needed to modify them.

**Comment by williamhallatt** [comment]
@gdufford I wish I could tell you that I had applied some logical process to determine the scope and selection, but unfortunately it was purely an insane amount of Google searching coupled with a lot of trial and error (hence the "works for me" comment).  If there is any documentation out there that addresses all available selectors, I am unaware of it.

**Comment by n0f3** [comment]
why is the save-all keybinding automatically assigned and available only in os x?

**Comment by xucaen** [comment]
I don't understand why the save all command is 'window:save-all' when the save as is 'core:save-as' and save is 'core:save'. This is not intuitive and most programmers are going to try 'core:save-all' and fail. Take a queue from Brackets and VSCode and make the Atom configuration intuitive.

**Comment by damieng** [comment]
<kbd>ctrl</kbd><kbd>shift</kbd><kbd>S</kbd> is already `save-as` on Windows and Linux and we'd need to unbind that to make it this.

Unfortunately there is no standard shortcuts on Windows for save-as or save-all hence why there is no default binding.

We do have a future plan to review all of our keyboard bindings and will reconsider save-as vs save-all at that point. Closing until then.

**Comment by jestersoftware** [comment]
Damien. Dude. This is a deal breaker for many of us. The use case for editing a bunch of files and then saving them all at once (to trigger a Node rebuild or whatever) has got to be at least 80% (80/20 rule) over "Save As" which no one ever uses. And I don't know about Linux but CTRL+SHIFT+S is almost always the default in Windows for Save All. It just makes sense in relation to Save, CTRL+S.

**Comment by damieng** [comment]
@jestersoftware  You can give yourself that functionality in 10 seconds.

File > Keymap...

then paste in the code williamhallat described above

```cson
'body':
  'ctrl-shift-s': 'window:save-all'
```

**Comment by jestersoftware** [comment]
Thank you @damieng ... I'll try it.  

I guess I was also seconding the point that @xucaen was making and/or voting for this out-of-the-box ... :) Any combo OOB would be better than no combo OOB (thereby also eliminating 'figuring out the proper config name'), imo, as I have to believe that "saving all on demand" is common to many developers.

I would use "auto-save" but that triggers things like Angular or Meteor builds too often.

To be sure, Atom is pretty nice outside of a couple details, so thanks for the work and the reply.

**Comment by damieng** [comment]
I did try a few apps and there didn't seem to be much consensus on what the shortcut should be.  Visual Studio, TextPad and Notepad++ did use ctrl-shift-s for Save All but VS Code and Sublime used ctrl-shift-s for Save As.

I'd be up for changing save all to ctrl-shift-s and moving save-as to F12 for consistency with the former apps although I suspect we'll get complaints from people who are used to ctrl-shift-s for save as.

I wish we had telemetry at the shortcut level to help make decisions like this one.

**Comment by jestersoftware** [comment]
Agree with your points ... there is inconsistency, and I'm sure if you change someone will complain. 

I would still say that ... I've been a developer for 20 years and I don't think I've ever used Save As for anything. Once in a while I'll use it with a Word doc or Paint program.

What "save as" really means functionally is "make a copy" ... Google Docs, for instance, gets this right, and calls it "make a copy", not "save as".

If one is making lots of copies of code, what kind of developer is one? Ha.

Anyway, I do use Save All _all_ the time.

**Comment by damieng** [comment]
What I'm thinking here is we could unbind Save As in one release and then rebind it to Save All a major release later so that it doesn't suddenly change behavior out from under people.

**Comment by happycollision** [comment]
Is there a way to scope that only to Windows? I've tried both of the following and they do not work:
```cson
'body .platform-win32':
  'ctrl-alt-s': 'window:save-all'

'.platform-win32 body':
  'ctrl-alt-s': 'window:save-all'
```
(I like mine to be `alt` instead of `shift`)

**Comment by damieng** [comment]
ctrl-alt with an alpha key will unfortunately not work as they are used by international keyboards to generate alpha characters.  e.g. á in this case.

**Comment by happycollision** [comment]
Sorry. I was unclear. It actually works just fine like this:
```cson
'.body':
  'ctrl-alt-s': 'window:save-all'
```
I was just trying to *additionally* scope it only to Windows, so it won't blow away any defaults on the Mac, since I have to run both (like an animal) and I sync my settings.

**Comment by damieng** [comment]
Hmm, not sure why then the .platform-win32 specifier wouldn't work.

**Comment by davidtaubmann** [comment]
This one worked great for me:
https://gist.github.com/olegantonyan/f11d6de002347365418b

**Comment by Coliwob** [comment]
and then restart atom.

**Comment by christianbueno1** [comment]
hello pals, what kind of key-bind is Ctrl+k,s and how adding this in the keymap.cson file.
this keymap
`'body'
    'ctrl+k,s':'window:save-all'
`
Show me the following error.

`[stdin]:21:1: error: unexpected indentation
    'ctrl+k,s':'window:save-all'
^^^^`

**Comment by happycollision** [comment]
The error you are seeing is in the format of your file. A “cson” file has strict rules when it comes to leading white space in each line. Follow the format of other lines in the file carefully.

See https://github.com/bevry/cson#what-is-cson for more

**Comment by christianbueno1** [comment]
thanks pal, I do it in this way, changing the plus sign by minus sign ctrl-alt-s.
`'body':`
`    'crtl-alt-s' : 'window:save-all'`
without problems.
But keyboard shortcuts called "key chords" are very useful , e.g. type ctrl+k drip the keys then type "S" key,  as in visual code.  Will Atom support this kind of shortcuts?

**Comment by 50Wliu** [comment]
> But keyboard shortcuts called "key chords" are very useful , e.g. pressing ctrl+k release those keys then press "S" key, as in visual code. Will Atom support this kind of shortcuts?

```cson
'body':
  'ctrl-k shift-s': 'window:save-all'
```
Notice the space.
