### ISSUE TITLE
atom 1.10 on Mac

### ISSUE THREAD

**Issue by LeFnord** [atom/atom#9395]
the cursor is invisible

**Comment by benogle** [comment]
This is likely an issue with the one of the themes you have installed. Can you try starting atom in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by LeFnord** [comment]
thanks for the hint, and yes in safe mode is all fine … ;)
