### ISSUE TITLE
Instacrash on load - Mac OS X

### ISSUE THREAD

**Issue by Daniel15** [atom/atom#9398]
Atom is crashing as soon as I open it, and I get a dialog like this:

![Instafail](https://cloud.githubusercontent.com/assets/91933/10891996/f8af3be0-8155-11e5-868b-01bb886a3121.png)

Full contents of the crash message: https://gist.github.com/Daniel15/bdcfd57b9915bade7d2a

**Comment by mnquintana** [comment]
cc @zcbenz

**Comment by Daniel15** [comment]
It seems to have stopped crashing after restarting my computer. I'll keep an eye on it. Still, I have no idea if restarting "fixed" it or if it'll just start happening again after some period of time.

**Comment by benogle** [comment]
Can you go into Console.app and paste the crash report in here?

**Comment by Daniel15** [comment]
@benogle  - Is that not what I linked to above? I copied that from the text in the crash dialog. Sorry, I'm not very familiar with Mac OS.

**Comment by benogle** [comment]
I'm sorry, I didnt read it thoroughly

**Comment by Daniel15** [comment]
No problem, I was just wondering if OS X has multiple different types of crash reports :smile:

**Comment by zcbenz** [comment]
It is probably because OS X was doing something crazy at the time, from the report the crash seems to be happened randomly.

**Comment by Daniel15** [comment]
Interesting... I tried opening Atom several times, and it crashed every single time.

Oh well, it seems to be working now. I haven't seen it crash again since this morning.

**Comment by nwehner** [comment]
Mine is also crashing each time I load the program on Yosemite with the message "The editor has crashed." Was fine before the latest update. Though, I can only attach the crash report as a PNG, GIF, or JPG here.

**Comment by joshaber** [comment]
This looks like https://github.com/libgit2/libgit2/issues/3414, which will be fixed by https://github.com/atom/git-utils/pull/60.

**Comment by Daniel15** [comment]
Haven't seen my issue for a while so I'm going to close this out.
