### ISSUE TITLE
Windows "Open in Atom" context menu shortcut opens new window

### ISSUE THREAD

**Issue by mjohnsonengr** [atom/atom#9399]
This seems semi-related to https://github.com/atom/atom/issues/1722 but different, still (that issue is quite old)

In Windows, when I click "Open in Atom" from the context menu, a new Atom window is open.  That's fairly annoying, but it's even worse if I select 3 or 4 files and open in Atom, when 3 or 4 windows open. You can imagine the scalability.

If an Atom window is already open, is it technically possible to open these files in the most recently active window or something?

**Comment by mjohnsonengr** [comment]
And today this works.  Ladies and gentlemen, I present to you, Microsoft Windows.

**Comment by gregplaysguitar** [comment]
I'm seeing this behaviour in Atom on Mac, so it might be something to do with Atom itself?

**Comment by mikejolley** [comment]
Same here - new instance of the app opens and crashes.

**Comment by anirudhn18** [comment]
> And today this works.

Is this feature implemented now or am I missing something? The "Open in Atom" from any context menu still opens the file(s) up in a new window.
