### ISSUE TITLE
Alt + Mouse Selection to select multiple lines

### ISSUE THREAD

**Issue by martinheidegger** [atom/atom#9407]
One of the features I miss most in Atom is column selection usually done using the ALT Key + Left mouse on mac:

https://www.sublimetext.com/docs/2/column_selection.html

Would love to see that in Atom.

**Comment by izuzak** [comment]
Thanks for the feedback, @martinheidegger -- yeah, that would be neat. There's already an issue tracking that request https://github.com/atom/atom/issues/2306, so I'm going to close this in favor of that one. Also, I think the comments in that issue mention a few packages you might try to get the same behavior in Atom today.
