### ISSUE TITLE
Window menu doesn't list open windows

### ISSUE THREAD

**Issue by jonrimmer** [atom/atom#9408]
In Atom 1.2.0-beta0, OS X 10.11.1.

The “Window” menu is no longer listing the open Atom windows, making it difficult to switch between them. The problem still occurs in safe mode.

**Comment by benogle** [comment]
True. 

![screen shot 2015-11-03 at 5 49 18 pm](https://cloud.githubusercontent.com/assets/69169/10927271/3f2d820e-8253-11e5-985b-a989ec6d6887.png)

Regression? cc @maxbrunsfeld

**Comment by Scotchester** [comment]
:+1: It seems to occur when restarting Atom, e.g., after installing an update. Windows are restored, but no longer listed in the Window menu. Only newly-opened windows will populate it.

**Comment by jonrimmer** [comment]
@Scotchester I am seeing the problem with both restored and newly-opened windows.

**Comment by Scotchester** [comment]
Interesting. On 1.1.0 (OS X) new windows do get added to the list for me.

**Comment by pookah-net** [comment]
I'm still getting this problem.
![screen shot 2015-11-16 at 10 17 42 am](https://cloud.githubusercontent.com/assets/4722050/11185570/61f3dd18-8c4b-11e5-9002-319ca0bf6a39.jpg)

Running Atom 1.2.0, OS X El Capitan 10.11.2 Beta Beta (15C40a). 

Did I miss some update? I can't find anything saying so, but it wouldn't be the first time!

Thanks.
/Ian

**Comment by mnquintana** [comment]
@pookah-net This fix didn't make it to 1.2.0 - it's in the 1.3.0 beta.

**Comment by pookah-net** [comment]
Ah! Thanks! :-)

**Comment by jipiboily** [comment]
Can we get a backport in 1.2.X? Or when is 1.3.0 due? If it's a few days it's fine, if it's weeks that would be greatly appreciated.

**Comment by jglovier** [comment]
>Or when is 1.3.0 due?

Yeah, I arrived at this thread with the same issue today, and just downloaded the Atom Beta as a fix. But curious to know if there is a public timetable for releases anywhere?

**Comment by benogle** [comment]
> Or when is 1.3.0 due?

Likely first week of dec. cc @nathansobo on the backport question

**Comment by skeet** [comment]
CTRL+down to "Show all Windows" is my workaround for now.

**Comment by dancinglightning** [comment]
thanks @skeet
