### ISSUE TITLE
How do I configure TAB behavior in Atom?

### ISSUE THREAD

**Issue by ircer** [atom/atom#9409]
Hi

I've been using Atom for a while, just opened up some code that I created in Atom using `vi` and the spacing etc. is crazy, nothing lines up etc.!

I have always used Notepad++ for years before switching to Atom, and had that set to `Use spaces instead of TABs` and `Tab size is 2 spaces`.

How do I emulate this behaviour in Atom? Never use tabs, and when the tab key is hit just insert 2 spaces.

**Comment by rawrmonstar** [comment]
In your settings use a tab type of soft for spaces.
![image](https://cloud.githubusercontent.com/assets/13814048/10916097/b4a23768-820e-11e5-81ae-d9580ee6b437.png)

**Comment by mnquintana** [comment]
Thanks @rawrmonstar! @ircer Feel free to leave a comment if that wasn't what you were looking for.
