### ISSUE TITLE
Package precedence

### ISSUE THREAD

**Issue by svlentink** [atom/atom#9411]
I'm very new to this all, I got here because my latex syntax high lighting makes my [red-wavy-underline](https://atom.io/packages/red-wavy-underline) disappear.
As a web developer I'm aware of the z-index and also that the order you load your css files can make a huge difference.

Is Atom using any kind of [precedence](https://en.wikipedia.org/wiki/Order_of_operations) for its packages, and if, where can I change it / which categories are there?

For me (non native EN), my spell-check is essential and number one priority for latex (and code), of course followed by the code [standard](http://standardjs.com) of your team.

**Comment by benogle** [comment]
Can you open an issue on the package?

cc @lee-dohm
