### ISSUE TITLE
Multiple crashes on Windows 10

### ISSUE THREAD

**Issue by dborsatto** [atom/atom#9412]
Atom crashes on startup on Windows. It happens about once per week, and the only solution is to delete the whole ~/.atom directory.
I can't understand what triggers the problem, sometimes it happens after installing a new package, but removing it and clearing everything inside compile-cache won't solve the problem. Sometimes it just happens out of nowhere, one day it works, and the next it won't open. I'm sorry I can't be more helpful in describing the issue, but I can't narrow it down to a specific event. The last 3 crashes were today (11/03), October 28th and October 15th.
I'm running Atom 1.1.0 on Windows 10. The editor loads and it shows and empty pane, and the menu bar on top only shows the "Atom" tab, but then it stays idle for a few seconds and then Windows notifies that the program froze.

**Comment by benogle** [comment]
cc @raelyard

**Comment by dborsatto** [comment]
If it is of any help, I kept the .atom directories instead of deleting them -- I just renamed them so the editor would create a new one.

If there are no personal info stored (I use it at work, so the data I work with is rather confidential) I'd be happy to provide a zip file of it for reproduction purposes.

**Comment by raelyard** [comment]
@dborsatto Yes please.  If there's something corrupted in there, it would be helpful to see what is happening.  There shouldn't be personal information, it's settings and packages and such.

**Comment by dborsatto** [comment]
Here it is:
https://drive.google.com/file/d/0B6uLnP-htMHnRXhXM2xDSTJhZ2s/view?usp=sharing

**Comment by raelyard** [comment]
I don't crash with that .atom on Win 10.  I see an error message on start coming out of the atom-autocomplete-php package.  There are some long paths in that package directory.  I suspect in your user home directory, those might be causing you to hit the dreaded path too long problem on Windows.  Is your username long in Windows?  Could it be it works until you install that package?

**Comment by dborsatto** [comment]
Today it happened again, but deleting the .atom directory didn't fix the problem. However, removing the cache data inside ~\AppData\Roaming\Atom did the trick.
Next time this happens, I'll check the content of those files to see if there's anything unusual.
