### ISSUE TITLE
Settings lost when launching atom by opening an associated file

### ISSUE THREAD

**Issue by florianwalter** [atom/atom#9413]
When atom is not running and i am opening an associated file (e.g. test.php), this will launch atom, but all settings are reset to default (theme, core settings and package settings).

When atom is launched as described, the console shows that almost all packages failed to load:
```javascript
Failed to load package named 'project-manager' c:\Users\myuser\.atom\packages\project-manager\lib\project-manager.js:3
```
And i get the following error:
```javascript
TypeError: Expecting a function in instanceof check, but got undefined
  at c:\Program Files (x86)\Atom\resources\app\src\view-registry.js:70:34
  at Array.find (native)
```

When atom is already running the file is just opened in the last focused editor window and the settings are untouched.

This happens on `Windows 7` and `Windows 10` running `Atom 1.0.19` and `1.1.0`.

**Comment by florianwalter** [comment]
I think i found the cause of the error.

Since i am using atom for a while now i still had an installation in `C:\Programs\atom\` which didn't get replace/removed by the updater. (The version was `0.1.149`)
The version i was starting normally from the taskbar is located in `C:\Users\myUser\AppData\Local\atom` (version `1.1.0`), but the file association still pointed to the old version of atom.exe in the programs folder.

So opening an associated file was starting the old version, which would corrupt the config and atom started with the default settings.

After removing all atom instances, reinstalling it and setting the file associations to `C:\Users\myUser\AppData\Local\atom\bin\atom.cmd` the problem is gone.

**Comment by damieng** [comment]
The next version - 1.7.0 - adds atom.exe to the list of programs that can be associated with files and will take the necessary steps to ensure the path is updated correctly with each update.
