### ISSUE TITLE
Atom weird bug with space character

### ISSUE THREAD

**Issue by esiao** [atom/atom#9414]
Hello I open this issue as it happens more and more often on my Atom editor.
Sometimes when I hit space I have the following character
` `
Which looks like a normal space character but isn't, it results in PHP fatals errors and Javascript errors
`Parse error: syntax error, unexpected ' ' (T_STRING), expecting '{'`
For something like
`function my_function() {`
If I replace the space part by a new space it works again.

This is really weird and I don't know what the difference is between ` ` and ` `but it happens occasionally on my files resulting in mind blowing errors. Looks like the first one is`&nbsp;`
If you need something more I will be happy to share it since it's really annoying.

**Comment by glangford** [comment]
See also #9027
