### ISSUE TITLE
Hitting escape on multiple selection lands cursor at point of origin...

### ISSUE THREAD

**Issue by arxpoetica** [atom/atom#9417]
See gif:

![Wonkish multiple selection behavior.](http://g.recordit.co/OMKFOkmlQT.gif)

I would expect hitting escape would leave the cursor (and jump the page) to the final selection. In this case (in the gif) that would be the first line, not the second line. For reference, Sublime Text behaves this way—forgetting the point of origin.

Perhaps there are some programmers who prefer this behavior, and its actually a feature? If so, is there a way that I can change the behavior on just my instance? It's (sorry) driving me batty.

**Comment by alexandernst** [comment]
It's actually a feature IIRC, this was implemented some weeks ago. The expented behavior (in all major editors) is the one Atom has implemented.

**Comment by arxpoetica** [comment]
> "in all major editors"

This is *not* true of SublimeText, which focuses at the last point of selection, not the origin.

In any case, I won't quibble. But if somebody could show me a method to change this behavior programmatically on my own, I would be very appreciative.

**Comment by benogle** [comment]
The PR: https://github.com/atom/atom/pull/8604
The original issue: https://github.com/atom/atom/issues/7738

**Comment by arxpoetica** [comment]
Thank you for the PR and the commit. :+1: Hopefully this helps me figure out a technique to optimize my environment according to my own idiosyncratic needs. :wink:
