### ISSUE TITLE
Auto-save untitled buffers

### ISSUE THREAD

**Issue by matthewmccullough** [atom/atom#942]
One feature I love of an increasing number of Mac OSX Lion and above apps is the auto-saving of untitled buffers.  If I quit an app that supports this behavior and re-open it, even untitled buffers (never explicitly named and saved) are restored. This lets me have greater confidence about using these apps as "clipboards," knowing that even if I crash or accidentally close the app, I'll have some reasonably up-to-date copy of the file restored.

Sublime is the front-of-mind example for this in my daily workflow.

**Comment by kice** [comment]
+1 I will love this feature

**Comment by NamPNQ** [comment]
+1

**Comment by Zireael07** [comment]
I agree that it'd be great!

**Comment by JoshCoady** [comment]
FYI ... I've been using the community package save-session by mpeterson2
which has the ability to restore unsaved changes, even changes to untitled
buffers.

-Josh

**Comment by phsilva** [comment]
I am so used to this on other editors that I don't even bother to save some stuff, just use as scratchpad and know that it will be there all the time.

+1

**Comment by Pholey** [comment]
+1

**Comment by mehcode** [comment]
Re-posting opening comment from #6455 

-----

I think this is critical. It's not about atom crashing or not crashing. It's about a myriad of other things crashing on a computer. It's about being able to not kill a junior because he or she accidentally hit the reset button on your computer. Sublime gives you the "don't worry about it" guarantee. It's a state of mind and affects your workflow. I was used to having many unnamed buffers open with random scratch data. I didn't need to save it anywhere but sublime kept them around.

**Comment by Leonick** [comment]
This is a feature I'd really like to see, especially now that Atom remembers windows without any addons. If Atom is going to remember anything from the last session it needs to remember pretty much everything.
  * Open windows
  * Open tabs
  * Order of the tabs
  * Content of all tabs, doesn't matter if it's a named and previously saved file or a new unsaved one
  * For a previously saved tab, changes should not be saved to that file on exit. It needs to me saved like untitled files until I choose to save it.

I'm rather new to Atom. Previously been a user of Notepad++ which handles this perfectly, however I'm moving to Atom as a I need good text-editor available across platforms.

**Comment by BretFisher** [comment]
+1

I use both atom and sublime, but only use sublime for scratch/temp stuff because of autosave.

**Comment by ggamel** [comment]
Please implement. Now that remembering tabs/open windows is implemented (in 0.193.0), this feels like the logical next step. Being able to do this across all other apps on my system means Atom feels out of touch not allowing me to scratchpad ideas/code.

:pray: :pray: :pray:

**Comment by lukehefson** [comment]
This is very standard behaviour for Mac apps now. So much so that some folks are quite used to **not** saving and therefore it could prove worrisome if their system crashes and they haven't saved recently/ever.

**Comment by 7ynk3r** [comment]
I still can understand this is not yet implemented... So painful to work without this. 
Please, just use https://github.com/mpeterson2/save-session. I read that it was deprecated because it was already implemented in core but is not true at all.

**Comment by yissachar** [comment]
The lack of this feature is surprising and has bitten me a few times already. I've installed save-session now which fixes this oversight, but it should really be part of core.

**Comment by viartemev** [comment]
+1

**Comment by fabb** [comment]
+1

**Comment by Waltton** [comment]
+1

**Comment by dansoton** [comment]
+1 Must have

I mistakenly thought that this was part of 1.0 (#1603) but appears that is only to do with remembering which tabs were open and not saving state.

IMHO it's crazy this wasn't part of 1.0. I thought it was finally the time I was going to switch over from ST3 as my default text editor, but again nope, back I go :(

**Comment by lukehefson** [comment]
@dansoton You might want to check out [save session](https://github.com/atom/atom/issues/942#issuecomment-102191673) as an interim solution. It's pretty awesome.

**Comment by dwelle** [comment]
I agree, this should have been part of 1.0, but we can always make up for it.

**Comment by sanbor** [comment]
Yes, this was one of the "amazing" and disrupting features from Sublime that I was missing. So far [save-session](https://github.com/mpeterson2/save-session) is doing a good job.

**Comment by SigmaDraconis** [comment]
+1

**Comment by santosh** [comment]
:+1:

**Comment by hseitz** [comment]
+1

**Comment by bitbonk** [comment]
+1

I really second what @mehcode said!

**Comment by hemangajmera** [comment]
Definitely +1.
I just started using atom and never thought that this feature would not be part of the core. It is default behavior in notepad++, ST2, ST3.

**Comment by mnquintana** [comment]
Thanks for the feedback everyone! However, all these +1s and :+1:s are just adding noise, so to minimize that I'm going to lock this issue for now – we may unlock it once someone starts working on this enhancement to get further feedback.

**Comment by 50Wliu** [comment]
This will be fixed in Atom 1.4.0 and 1.4.0-beta0 (or you can get the new behavior right now by building master).

Thanks for the patience everyone!  If you notice bugs, please open a new issue for that.

**Comment by 50Wliu** [comment]
This feature is now available in [1.4.0-beta0](https://github.com/atom/atom/releases/tag/v1.4.0-beta0).  If everyone can try it out and report any bugs they experience, that would be great! :smile:
