### ISSUE TITLE
Dragging over tabs should switch tabs

### ISSUE THREAD

**Issue by francoislaberge** [atom/atom#9421]
It would be great if when you are drag and dropping something onto atom pages if you drag over the editor tabs it would switch tabs to the editor who's tab you are hovering over. Some delay would likely be ideal.

**Comment by mnquintana** [comment]
Would you mind reopening this on https://github.com/atom/tabs? Thanks! :smile:

**Comment by francoislaberge** [comment]
[Done](https://github.com/atom/tabs/issues/232)
