### ISSUE TITLE
The application /Applications/Atom.app cannot be opened because its executable is missing.

### ISSUE THREAD

**Issue by jasonlagaac** [atom/atom#9423]
Hi I'm getting the error when running atom from the command line in OSX 

ProductName:    Mac OS X
ProductVersion: 10.11.1
BuildVersion:   15B42

Atom Version: 1.1.0

**Comment by benogle** [comment]
cc @zcbenz @joshaber

**Comment by alvinsj** [comment]
did you try Atom Menu > Install Shell Commands?

**Comment by jasonlagaac** [comment]
@alvinsj This is a fresh install with shell commands installed.

**Comment by joshaber** [comment]
Only when running from the command line? Does it launch fine from Finder?

**Comment by jasonlagaac** [comment]
@joshaber It launches fine in Finder and Spotlight.

**Comment by joshaber** [comment]
What's the output of running:

```
$ ls -la $(which atom)
```

**Comment by joshaber** [comment]
Is it possible tmux is doing something with `PATH`?

**Comment by lee-dohm** [comment]
@timothysu would you mind opening a new Issue? I want to make sure that your Issue gets handled and if @jasonlagaac isn't using tmux, it sounds like a different problem.

@jasonlagaac are you no longer running into this problem?

**Comment by robertwahler** [comment]
A common method for starting CLI apps on OSX is to use `open -a`

`open -a Atom README.txt`

This works for me 9 times out of 10 and then will fail with the same error message from the OP.  Restarting iTerm/Fish/Tmux fixes the issue for me.

This isn't just an Atom issue. I have the same issue intermittently with `open -a Firefox 'http://example.com'`

**Comment by bnmnetp** [comment]
I'm getting the same problem under 10.11.4 beta with atom 1.5.3.   Also using fish and tmux.   However the old `reattach-to-user-namespace` trick works fine so I've created an alias to run

If you don't know about the `reattach-to-user-namespace` it is installable with brew.  And you can google it for more details.

```
function e
    echo "using fish alias to open atom"
		reattach-to-user-namespace atom -n $argv
end
```

**Comment by hovancik** [comment]
Have the same problem here. os x 10.11.3.

Atom was  installed via brew. Happening now on version 1.5.4, not happening before (I was using atom update feature to get updates).

```
ls -la $(which atom)
lrwxr-xr-x  1 501  admin  79 Jul  8  2015 /usr/local/bin/atom -> /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/atom.sh
```

**Comment by dd1994** [comment]
meet the same, fixed after iTerm restart

**Comment by dd1994** [comment]
opppps can't use it in tmux

**Comment by craigiswayne** [comment]
I'm having the same issue:
`ls -la $(which atom)`
`lrwxr-xr-x  1 myusername  admin  78 Apr 28 23:59 /usr/local/bin/atom -> /opt/homebrew-cask/Caskroom/atom/1.7.2/Atom.app/Contents/Resources/app/atom.sh`

I installed with homebrew as well....

however if i open atom via command line, it works using either of these methods
`atom`
`open -a Atom`

I will glady provide ANY information.

**Comment by lee-dohm** [comment]
It sounds like this is a problem restricted to Homebrew installations? Is anyone still running into this that is not installing via Homebrew?

Homebrew Casks are installed to `/User/[username]/Applications` not `/Applications`, so if you have a copy of `Atom.app` in `/Applications`, it is probably broken and should be deleted.

**Comment by craigiswayne** [comment]
I can verify that Homebrew has been installing into 
`~/Applications`

so this is not the problem.

**Comment by lee-dohm** [comment]
The title of this Issue specifically mentions a problem with `/Applications/Atom.app`, so if you are having a problem with an `Atom.app` installed in another location, please open a new Issue.

**Comment by lee-dohm** [comment]
@jasonlagaac are you running into this problem anymore?

**Comment by lee-dohm** [comment]
Closing due to lack of response. If you start running into this Issue again, please feel free to reopen it and give us the new information. Thanks!

**Comment by paanvaannd** [comment]
@lee-dohm I've just started running into this same issue.

This only happens with `tmux` but the `atom {fileName}` and 'open {filenNme} -a {applicationName}` work fine in `zsh`.

This isn't localized to just Atom; this same error is output whenever I try to open a file using `tmux` in an application outside iTerm. I'll write to the `tmux` Git page and open up an issue there since it seems like this is a `tmux` issue.

Just wanted to let you know in case others contact you with this same issue! I will provide another update once I have (hopefully) resolved the issue after contacting the `tmux` devs so you can direct them to that issue.

**Comment by Pipeliner** [comment]
@paanvaannd has this been fixed with newer tmux?
The haven't (yet) occured for me with tmux 2.3

**Comment by mshaaban0** [comment]
that happens when you __force quit__  atom for some reason, try to restart atom, and iterm/terminal then it should work fine.

**Comment by paanvaannd** [comment]
@Pipeliner I tried to replicate the issue with the newer version of `tmux` and running `atom {fileName}` will now work just fine, but `open {fileName} -a {applicationName}` works yet results in the following message on occasion:
`The window server could not be contacted.  open must be run with a user logged in at the console, either as that user or as root.`

I'm not sure what causes this message to pop up. Using the `open {fileName} -a {applicationName}` method with Atom on an HTML file, I get the error and no file or application opening. Using the same method on the same file but with Microsoft Word, I get no error and the application opens the file. Using TextEdit, the application opens the file but I get the error message as well... strange stuff.

**Comment by matthewdowns-eb** [comment]
I was able to fix this by clicking "Install Shell Commands" in Atom, then restarting iTerm.
