### ISSUE TITLE
Atom incorrectly detecting changes to files with changed line endings when git has core.autocrlf set

### ISSUE THREAD

**Issue by Ajedi32** [atom/atom#9424]
I'm having an issue where git on the command line doesn't report a file as changed, but Atom is showing the file as changed in the tree view.

Opening the file shows +22, -22 in the stats indicator in Atom, but doesn't show any individual line in the file as changed. (There are no bars indicating changed lines on the left.) If I change the file, the changed lines are shown as changed in the bars on the left, but no other lines in the file are shown as changed (as the stats indicator would have you believe).

Showing hidden characters lets me see that the line endings in the file are indeed different, but these changes are ignored by git, as per my settings.

Now here's something weird I discovered in the process of debugging this issue. This might actually be a bug in git...

``` text
$ git config core.autocrlf
input
$ git config --global core.autocrlf
$ git config --local core.autocrlf
$ git config --system core.autocrlf
```

git seems to think my `core.autocrlf` setting is set to "input", but I don't have it set to that anywhere in my settings. Why? I have no idea. Anyone know if this is a bug in git? And if so, where do I report it?

Setting `core.autocrlf` explicitly seems to resolve the inconsistency, causing Atom to once again ignore changes to line endings:

``` text
$ git config --global core.autocrlf input
```

This difference of behavior is confusing though. Is this a bug in Atom? Or perhaps a bug in git, git-utils, or maybe libgit2?

Note I'm running `git version 2.6.2.windows.1` on Windows 10, and Atom v1.1.0.

Note: _Issue migrated from akonwi/git-plus#302._

**Comment by 50Wliu** [comment]
It's about time someone created a dedicate issue for this.  Something else to note is that resetting the file to HEAD will cause the line endings to go back to LF.

See also #3768, atom/tree-view#628, among others.

**Comment by Slumber86** [comment]
I think is the option in installation. I have set autoclrlf to true and the issue disappeared with an hard reset

**Comment by Ajedi32** [comment]
Maybe that's the problem. I always just assumed that setting that option on installation just set `core.autocrlf` to an appropriate value in the global config, but that's apparently not the case?

**Comment by Slumber86** [comment]
I don't know, maybe is a bug in git 2.6.2 installer. With 1.9 all went fine, I noticed the problem after the upgrade.
