### ISSUE TITLE
Can Atom have a custom right-click context menu?

### ISSUE THREAD

**Issue by jamen** [atom/atom#9429]
When right clicking in Atom, I can't help to notice that the popup is my system's sad attempt at a context menu.

I think it would be interesting if we used a custom right-click context menu in the document, or even a frameless `BrowserWindow`.  This way its more accessible as a piece of the software.  For things like themes and packages to customize and use.

**Comment by programmatical** [comment]
+1

**Comment by ricardovsilva** [comment]
+1 . If someone point me where to start, I can try develop this feature.

**Comment by 50Wliu** [comment]
> If someone point me where to start, I can try develop this feature.

First you'll probably need to see whether or not Electron supports custom context menus.  If it does, then it's just a matter of using those APIs within Atom.
