### ISSUE TITLE
Atom trying to upload something and blocked by network

### ISSUE THREAD

**Issue by celiosilva** [atom/atom#9432]
Atom version: 1.1.0
OS: Windows 7
Behaviour: Crashes when OS detects file upload.
Packages: default.

Just suddenly atom started crashing after copying files from Atom instance to another. It crashes not because I'm copying files but somehow my OS detects it sa a file upload and blocks the action immediately. If there's a usage data upload back to Atom how can we turn this off ? In blocked environments I'm not allowed to report usage neither do uploads.

Thanks.
![upload_not_permitted](https://cloud.githubusercontent.com/assets/5233805/10937905/5ccddcd4-82dd-11e5-80f9-01d3e5017bb9.png)
![atom_crashing](https://cloud.githubusercontent.com/assets/5233805/10937906/5ce5a026-82dd-11e5-93bf-445820535192.png)

**Comment by jeancroy** [comment]
Have you tried to disable metric package ?

**Comment by celiosilva** [comment]
I see in this thread they will include it in the future (https://github.com/atom/atom/issues/4966). Is there another way to do that ?

Thanks.

**Comment by jeancroy** [comment]
Setting &gt; Packages &gt; [search for metric] &gt; [disable]

**Comment by celiosilva** [comment]
Just changed now and it's working again!!

Thankyou!!
