### ISSUE TITLE
Pressing Ctrl while the page is being inertially scrolled decreases the font size

### ISSUE THREAD

**Issue by Valve** [atom/atom#9434]
I think it maybe only reproducible on a Mac. I'm using two-finger scroll on MBP, which has this 'inertia' effect, causing the page to slowly decelerate scrolling after two fingers were already lifted from the touch pad surface. So if I press Ctrl during the inertia scrolling (after I physically stopped dragging fingers onto the touch pad surface), - the font becomes tiny as if I pressed Ctrl + <minus> multiple times.

I'm using Atom 1.1.0 on OSX 10.10.5.

**Comment by 50Wliu** [comment]
Also happens on Windows 10.

**Comment by sylistine** [comment]
Isn't this sort of a 'if it hurts when you hit yourself, then don't hit yourself' problem? This happens on mice that have analog scroll wheels with momentum scrolling, too. If the inertia is OS level, there's probably no way for atom to deal with it.
If so, suggest closing due to intended-behaviour.

**Comment by sylistine** [comment]
I take it back, as per this stackoverflow post, it might be able to detect simulated inertial scroll on mac: https://stackoverflow.com/questions/4339196/how-to-detect-disable-inertial-scrolling-in-mac-safari

**Comment by YemSalat** [comment]
I am not sure how scrolling is implemented in Atom, but the way you can deal with it in a browser - is continuously check the window Y offset (e.g. on a timer) and in the onScroll event make sure that it has not changed before increasing the font size.
