### ISSUE TITLE
Caret position completely broken after updating to 1.1 

### ISSUE THREAD

**Issue by louisremi** [atom/atom#9435]
I'm on Ubuntu Linux, I just read the release blog post for 1.1 and then proceeded to update atom. The new caret positioning mechanism is completely broken for me, as demonstrated in the following screencast: https://www.youtube.com/watch?v=CPgFNo4OlHg
Sometimes hitting the left-arrow key even moves the caret to the right :-/

I tried updating to the beta version but that didn't help. I'll have to downgrade to an earlier version, if I find one!

**Comment by MaximSokolov** [comment]
Duplicate of #9343

**Comment by louisremi** [comment]
Oops, sorry.
