### ISSUE TITLE
atom/Whitespace package eat random characters on save !

### ISSUE THREAD

**Issue by jeancroy** [atom/atom#9438]
Step 1: atom --safe
Step 2: Open http://gundvang.dk/atom/fonts.js
Step 3: Save As `font2.js`
Step 4: Notice the missing `i`of `if` at line 22 and various missing character ( for example `$('.expanded')` at line 217 miss the `x`)
Step 5: Undo (file is ok)
Step 6: Disable package whitespace
Step 7: Save As `font3.js` (file is ok)
Step 8: Enable package whitespace
Step 9: Save As `font4.js`
Step 10: See the file mangled again (but in my case different mangle !)

[issue on discuss](https://discuss.atom.io/t/saving-js-and-scss-deletes-random-letters/20431/18)

![img1](https://i.gyazo.com/e676b79b43c92cf3944723ef40d7651f.png)

![img2](https://i.gyazo.com/888980d8af99ce4e75b07d47fd30c444.png)

**Comment by benogle** [comment]
This issue was moved to atom/whitespace#99
