### ISSUE TITLE
file reformatting on open

### ISSUE THREAD

**Issue by chrisdrackett** [atom/atom#9442]
I have files with a `.examples` extension that recently started to reformat on open. They look normal for a split second before many spaces and page breaks are added to the file. If I hit undo at this point I can get the file back into its normal format. I'm sure that this is probably a 3rd party package, but I have a lot of them. What is the preferred method of tracking down what is causing this?

**Comment by 50Wliu** [comment]
You can try using the [package-cop](https://atom.io/packages/package-cop) package by @mark-hahn.  Hope that helps!

**Comment by chrisdrackett** [comment]
That is *very* helpful, thanks!
