### ISSUE TITLE
BUG: class name usage!!

### ISSUE THREAD

**Issue by crperlin** [atom/atom#9446]
I found left sidebar have treeview class name error , such as:
![image](https://cloud.githubusercontent.com/assets/8272877/10958540/29dc042c-83aa-11e5-9dc6-9c9f16b3f70b.png)

**`label` and `label-*` is relative, but `label` and `bg-green` no relative although same effect!!!**

**Comment by lee-dohm** [comment]
Is this for the [Atom editor](https://atom.io)? The screenshot doesn't look like it is for Atom.

**Comment by crperlin** [comment]
@lee-dohm  oh no !! sorry ,,  my feedback error place ....sorry

**Comment by lee-dohm** [comment]
@crperlin It's alright, I'm glad we got it figured out :grinning:
