### ISSUE TITLE
atom can't high-light C language code correctly.

### ISSUE THREAD

**Issue by snaix** [atom/atom#9450]
OS:Windows 10 64bit
Atom: 1.1.0
color style: default

I found atom can't high-light correctly in C code.
When a macro define with another macro, like this:

#define ABC XYZ(1)
struct MY_STRUCT {
/* code */
};

The keyword "struct" is expected with colored, but the result is white without any color.
But the next keyword will be right. As follows:

![image](https://cloud.githubusercontent.com/assets/6660768/10961009/f8b95c6c-83c4-11e5-8a34-e86b2bf3102a.png)

**Comment by thomasjo** [comment]
Please re-open this on the [language-c](https://github.com/atom/language-c) repo. Thanks!
