### ISSUE TITLE
Documentation: groupChangesSinceCheckpoint takes no parameters

### ISSUE THREAD

**Issue by FPtje** [atom/atom#9457]
According to the documentation, `editor.groupChangesSinceCheckpoint` takes no parameters, but it does take one parameter: the checkpoint. 

This confused me.

https://github.com/atom/atom/blob/v1.1.0/src/text-editor.coffee#L1149

**Comment by maxbrunsfeld** [comment]
@FPtje Thanks for catching that. Are you interested in submitting a PR fixing that?

**Comment by FPtje** [comment]
Sorry, I can't be forked. It's probably three seconds work for someone who has the repo readily cloned in some folder.
