### ISSUE TITLE
Weird behavior in Windows Server 2012 multi-user environment

### ISSUE THREAD

**Issue by somecoder43242** [atom/atom#9459]
When using Atom in a multi-user environment, like when remoting into Windows Server 2012, only one person can use Atom at a time. If I have Atom open first, and then some else from another session tries to open Atom their window opens on my session.

**Comment by 50Wliu** [comment]
Looks like the Windows socket path needs the same treatment as https://github.com/atom/atom/blob/master/src/browser/main.coffee#L42.

**Comment by paulcbetts** [comment]
The new single-instance feature of Electron handles this case as well if you move to it
