### ISSUE TITLE
List of activationCommands and activationHooks?

### ISSUE THREAD

**Issue by oakmac** [atom/atom#9465]
In the "Hacking Atom" documentation, the [section on package.json](https://atom.io/docs/v1.1.0/hacking-atom-package-word-count#package-json) references `activationCommands` and `activationHooks`.

Is there a list of valid `activationCommands` and `activationHooks` that can be listened to in Atom?

For example, what should I listen to for my package's `activate` method to run when Atom first loads? How do I listen for when a user opens a file with extension `.txt` or `.text`? etc

**Comment by thomasjo** [comment]
The referenced activation commands are commands that Atom listens to in *your* packages, and when one of them is triggered, Atom will activate your package. Essentially if you specify commands provided by your package in your package's `activationCommands`, then your package will have deferred activation. Hopefully that makes sense.

**Comment by oakmac** [comment]
Could you provide examples to the questions in my first post? re: when atom first opens, when a text file is opened

My understanding is that `activationCommands` in package.json is an object and you provide custom "package events" as the values in that object. But what are the keys and where would a possible list of all of those keys be? I understand that they are CSS selectors, but how are they triggered?

I do not understand the difference between `activationCommands` and `activationHooks`. Are the only events usable in `activationHooks` something related to which language is being used in the editor?

The 30,000 ft view here is that I am trying to plug into some relatively simple events in Atom and having difficulty understanding how that works. I'm looking for a list of events my package can listen to and optionally examples of how to listen to those events.

**Comment by thomasjo** [comment]
For a concrete example in the documentation see
https://atom.io/docs/v1.1.0/hacking-atom-package-modifying-text#trigger-the-command

You might also want to read the rest of that, at least the earlier subsection on command creation. `activationHooks` is described in the documentation you referenced. It allows your package's activation to be deferred until the user interacts with a document with a specific grammar (aka language).

If you need further details, look at existing packages both core and community, and/or continue this in Slack or on Discuss.

**Comment by walles** [comment]
There's a new activation hook `core:loaded-shell-environment ` added in https://github.com/atom/atom/commit/9176a6429f1a1306d8a20609a5382ffb40d7fd40 which isn't mentioned in the tutorials.

I second the request for a list!
