### ISSUE TITLE
Option to disable autocomplete for snippet parameters

### ISSUE THREAD

**Issue by tj** [atom/atom#9472]
I can only speak for myself but for me having to press escape 3+ times for a simple snippet as you're stepping through params makes it pretty unusable. It would be awesome to have an option to disable auto-complete when you're stepping through a snippet.

cheers

**Comment by tj** [comment]
If this would get accepted I can dig around and come up with a pull-request, it's slowly driving me mad :D

**Comment by benogle** [comment]
Can you elaborate on the case where you don't want it? e.g. I type `cla` in a js file and get:

```js
class | {
  constructor(|) {
    |
  }
}
```

Where the pipes are snippet params. In each of these cases I find autocomplete useful. 

Also, what are you using for autocomplete confirmation? `enter`? `tab`? both? I can see if you had `tab` as confirm that it would be a pain because it hinders movement between params.

We're not super into adding more options, and I'd love to avoid it if possible. Maybe there's another way.

**Comment by tj** [comment]
ended up just remapping:

```coffee
'atom-text-editor':
  ']': 'snippets:next-tab-stop'
  '[': 'snippets:previous-tab-stop'
```

It would be useful to have a setting but this is a decent compromise for me. Between the languages that I use actively (Go, C, JS, CSS, etc) I've never really wanted auto-complete in snippet params, but if it's not bothering anyone else I might just be a weird edge-case haha.

Feel free to close, I'm happy enough with remapping.

**Comment by benogle** [comment]
Do you never type `[]` chars? :p Maybe try using `enter` to confirm autocomplete (it's a setting in autocomplete-plus)? 

I think there is a bit of a conflict generally with snippets and autocomplete (and emmet!) using the `tab` key. Other people are having issues as well: https://github.com/atom/autocomplete-plus/issues/522, https://github.com/atom/autocomplete-plus/issues/391

I admittedly dont know what the best solution is at this time. If one were to come up with a nice idea for interaction between snippets and ac+ when using tab key, we'd be way more into merging that than an option.

One thing proposed in the other thread was favoring snippets on a tab key press when autocomplete is open. But then, it makes showing autocomplete kind of useless when there is another snippet tab stop. A workaround to try could be to make the snippet movement commands more specific than those from autocomplete:

```coffee 
'atom-workspace atom-text-editor.autocomplete-active':
  'tab': 'snippets:next-tab-stop'
  'shift-tab': 'snippets:previous-tab-stop'
```

**Comment by tj** [comment]
Not often in snippet, pretty much all of my snippet params are typically just identifiers. I'll check out the stuff you mentioned!
