### ISSUE TITLE
atom crashes if you try to open any files in webkit.js repo

### ISSUE THREAD

**Issue by AgentME** [atom/atom#9473]
If you clone https://github.com/trevorlinton/webkit.js, start atom in it (with or without the `--safe` flag), it appears to start up fine and lists files in the left file list, but as soon as you open any of them, Atom freezes for a few seconds, and then a dialog appears "The editor has crashed. Please report this issue to https://github.com/atom/atom. [Keep It Open] [Reload] [Close]".

**Comment by frewsxcv** [comment]
Same thing happens for me with http://github.com/servo/servo/

**Comment by jeancroy** [comment]
There's an issue with libgit and large repo.
https://github.com/atom/atom/issues/9339

it's on the process of being fixed.

**Comment by 50Wliu** [comment]
Thanks @jeancroy!
