### ISSUE TITLE
Creates new line when saving

### ISSUE THREAD

**Issue by greencopper** [atom/atom#9487]
I have just installed Atom 1.1.0 and I have noticed that whenever I am using CTRL-S and saves the file I am on, Atom creates a newline at the bottom before saving.

It doesn't matter what file type it is.

It should not create newlines when saving.

**Comment by 50Wliu** [comment]
This functionality is part of the Whitespace package.  To disable, go to Settings -> Packages -> Whitespace -> uncheck the "Ensure Single Trailing Newline" option.

**Comment by mnquintana** [comment]
You may also find https://discuss.atom.io/t/why-is-atom-deleting-trailing-whitespace-why-is-there-a-newline-at-the-end-of-the-file-why-are-there-all-these-changes-in-the-file-diff/19189 helpful for further background.
