### ISSUE TITLE
Random bubble pops up on text.

### ISSUE THREAD

**Issue by ddaza** [atom/atom#9488]
I am not sure if this is the right place to post this. But  this issue has become extremely annoying. 

<img width="812" alt="screen shot 2015-11-07 at 10 36 28 pm" src="https://cloud.githubusercontent.com/assets/290254/11018821/e36f6666-85a0-11e5-88c3-792284fc6cc2.png">

What is that pop up?? and how do I stop it? 

thanks!

**Comment by vramana** [comment]
@ddaza For starters have you tried running in safe mode i.e, disabling all custom packages that you have installed? If it is caused by package  you should the inform issue on that package repo. 

Also it is better to mention which version of Atom you are using and list of packages you have installed (`apm ls`).

**Comment by ddaza** [comment]
This is my atom version : 
```
Built-in Atom packages (90)
├── about@1.1.0
```
I installed all the packages at once since I changed computers recently.
Here are my packages: 
```
.atom/packages (10)
├── atom-monokai@0.9.6
├── ex-mode@0.7.0
├── file-icons@1.6.11
├── isotope-ui@2.7.0
├── language-babel@2.2.0
├── linter@1.10.0
├── linter-eslint@4.0.0
├── monokai@0.18.0
├── vim-mode@0.63.0
└── vim-surround@0.8.1
```
How do I pinpoint which package it might be?

**Comment by vramana** [comment]
First try turning off everything and see if the problem persists. Then enable packages one by one until you hit the issue. I don't know a better way.

**Comment by AluisioASG** [comment]
There's [package-cop](https://atom.io/packages/package-cop) though I never used it myself.

Also of interest is when does that pop-up appears.

**Comment by ddaza** [comment]
There lies the problem. I cannot consistently reproduce this issue. 
It just randomly happens as I am reading and scrolling through files.

**Comment by mnquintana** [comment]
[This is an OS X feature](https://support.apple.com/kb/PH18436?locale=en_US), not anything to do with Atom - the character accent menu will popup if you press and hold on a character with accent options for long enough. If you really dislike this feature though, you can always disable it OS-wide with:

```
defaults write -g ApplePressAndHoldEnabled -bool false
```

But this is not provided by Atom.

**Comment by ddaza** [comment]
thanks! that worked.  (No!, bad :apple:, bad :apple: )
