### ISSUE TITLE
Horizontal Scolling From Trackpad Treated Like Arrow Keys

### ISSUE THREAD

**Issue by josephbergevin** [atom/atom#9497]
When I use Horizontal Scrolling from my touchpad, Atom treats it like I am just pushing my left/right arrow keys, moving the cursor one character at a time left or right. Vertical Scrolling works great for me from my touchpad.

Behavior does not change with toggling the following settings:
- Scroll Past End
- Soft Wrap
- Soft Wrap At Preferred Line Length

OS: Windows 10 (this was happening on Windows 8.1 as well)
Atom Version: 1.1.0
Computer: Samsung ATIV Book 8
Touchpad: Elan Touchpad (ETDWare X64 15.7.0.1_WHQL)

**Comment by raelyard** [comment]
@josephbergevin That's an unexpected one - is this with a two-finger gesture to scroll.  Please forgive me if this is common knowledge and should be obvious, but are we talking about a dedicated part of the touchpad used for scrolling or is it sonething like a two-finger gesture?  Not sure what's specific to certain types of hardware.  I'm running Windows 10 on a MacBook and the two-finger scrolls as expected.  Will try on another machine I have as well and see if I see something different.

**Comment by josephbergevin** [comment]
@raelyard Yeah it's with 2-finger scrolling. It's really strange that my 2-finger horizontal scrolling works everywhere else, except Atom. Let me know if there is more info I can give you.

**Comment by raelyard** [comment]
@josephbergevin Have you tried Chrome?  https://productforums.google.com/forum/#!topic/chrome/60XWWkfFv0M I'm running same version of Atom, so should be using same chromium, but might narrow down a bit if Chrome has a problem for you too.

**Comment by josephbergevin** [comment]
Yes Chrome is my default browser. Horizontal Scrolling works as expected in the browser. It also works in my Microsoft Office programs, Slack, Sublime Text, Edge, etc.
I haven't been able to reproduce the same behavior in any other program on my computer. Is there a way to see what command is being heard by Atom when I initiate horizontal scrolling from the touchpad?

**Comment by 50Wliu** [comment]
Confirmed on Atom 1.3.0-dev-7bcdc9a, Windows 10 x64.  HOWEVER, this also affects me on Chrome 46:
![horizontal-scroll](https://cloud.githubusercontent.com/assets/2766036/11048392/a2ed7e3c-8705-11e5-8a71-cbdacad3578d.gif)
^This is in Github's online editor.

**Comment by giacomocerquone** [comment]
I have the exact same problem... actually I've always had it and it's so much annoying.

Machine: Dell Inspiron 15 7000
OS: Windows 10 Pro Insider Preview - Build 14352
Atom -v: 
```
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```
Touchpad: Dell Touchpad, SGS 15.2 -synaptic driver (it's not much, but it's all I can get)

# "Bug" reproduced
As I said in the slack channel, I use this computer for 2 year and I never noticed that I can reproduce the exact same behavior on textareas and input fields on web pages opened with Chrome. On those elements has some sort of meaning to reproduce the arrow keys, but in atom it's just frustrating.

**Comment by damieng** [comment]
Just tried to repro this in Atom 1.10.2 using a Surface Book trackpad and it scrolls horizontally as expected without moving the cursor.  Let me know if it is still a problem on your system with Atom 1.10.2

**Comment by giacomocerquone** [comment]
Actually I still have the problem with the 1.10.2

**Comment by damieng** [comment]
There must be some difference between how the Dell (Synaptics?) and Microsoft trackpads are interacting with the OS. Have you tried updating the trackpad driver? It often doesn't auto-update but the latest should be available from Dell or Synpatics.

If that doesn't solve it we're going to be dependent on more information/help from somebody who actually has one of these.

**Comment by giacomocerquone** [comment]
I check regularly for driver updates (I don't personally like the update utility that DELL gives) and mine are the last ones.
Couple of people at the university and my father has a DELL, I didn't think to try it on one of those and actually I think it wouldn't be so helpful considering that if it's a driver problem only DELL can fix it and there... well we know that they do whatever they want.

**Comment by yuanliwei** [comment]
There is a problem with horizontal scrolling and vertical scrolling on my computer.
When I use two fingers in the touch panel on the level of sliding, like a continuous press the left and right cursor keys;
When I use two fingers on the touchpad vertical slide, like a continuous press the upper and lower cursor keys;
In VSCode also have this problem;
But I am in other programs, the use of touchpad scroll is no problem.
![rec-atom](https://cloud.githubusercontent.com/assets/15871845/24584868/8fd7ec20-17ae-11e7-9cb2-25c520e586ce.gif)

PC : `LENOVO™ XIAOXIN 310`
System : `Win10 1607`
Touchpad : `ELAN Touchpad 11.4.96.1_X64_WHQL`
ATOM : `1.16.0-beta0 x64`

Hope that someone can quickly solve this problem

**Comment by damieng** [comment]
@yuanliwei This looks to be an issue in Chrome itself which is the basis of Electron which is what Atom is developed in. https://bugs.chromium.org/p/chromium/issues/detail?id=617096&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

It looks like they don't have enough detail to analyze why this is happening - if you have Spy++ on your system you might be able to provide them with more detail as to why this happens.

Unfortunately this would not be a quick solution as it would have to be fixed in Chrome, then upstreamed by Electron and then eventually into Atom. This process takes many months.

**Comment by ThrashJazzAssassin** [comment]
I'm getting the same problem with my Lenovo Yoga 510 with an ELAN touchpad. It's also present in Visual Studio Code.

There is a hacky solution for VS Code here: https://github.com/Microsoft/vscode/issues/1200 
Renaming code.exe to Chrome.exe enables normal scrolling. But atom doesn't load if atom.exe is renamed to Chrome.exe.

**Comment by SurgeArrester** [comment]
Just commenting to say same problem occurs on Lenovo ideapad 710s in VS Code, atom and spotify that I've found so far, very irritating!

**Comment by ThrashJazzAssassin** [comment]
The problem is the ELAN driver. Here is the fix:
https://www.youtube.com/watch?v=f2rfwR-IV-c

**Comment by SurgeArrester** [comment]
THANK YOU SO MUCH!! This has been driving me crazy for months, thought this would be the straw that drove me to Linux as my full time driver, not today Tux, not today...

**Comment by peekcell** [comment]
as @ThrashJazzAssassin suggested, changing atom.exe to Chrome.exe inside "C:\Users\Username\AppData\Local\atom\app-1.27.1" worked for me

**Comment by ncmoud** [comment]
I personally use Visual Studio Code, the problem occurs there too.
It's a driver problem, the defaults cause that issue and you'll have to dive into the registry to change it.

**Comment by ellocke** [comment]
For Lenevo / ElanTech people, here's the **solution**. _Please spread the word and post this solution to other "scrolling-moves-cursor" issues, so that developers aren't bothered with unrelated crappy touchpad driver problems:_

> 1.open regedit.exe using run
> 2.go to HKEY_CURRENT_USER -> SOFTWARE -> Elantech -> Smartpad
> 3.change ScrollControl_Mode from 0 to 1
> 4.open the elan software and apply just to make sure the settings gt applied
> change the number of lines to scroll in the Devices Settings to 3 then it works better.

OP: https://www.reddit.com/r/techsupport/comments/3lhmhq/win10_elan_touchpad_scrolling_issues/cvn9t28?utm_source=share&utm_medium=web2x
