### ISSUE TITLE
Change version number scheme for built versions

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom#9499]
So that version numbers sort in a more expected way, we should change the version numbers of built versions from `vX.Y.Z-dev-SHA` to `vX.Y.Z-alpha-SHA`.

**Comment by benogle** [comment]
@maxbrunsfeld @nathansobo are we officially calling it dev or alpha? Alpha does make sense given beta. Though it does have connotations of the product as a whole being unreleased.

**Comment by nathansobo** [comment]
Yeah, but I think that's similar with `beta`. I think having versions that sort correctly is a pretty good idea.

**Comment by maxbrunsfeld** [comment]
Yeah, `alpha` would be better.

**Comment by lee-dohm** [comment]
Good idea, not a lot of traction.
