### ISSUE TITLE
Atom autoupdate keeping gigabytes of redundant copies of Atom

### ISSUE THREAD

**Issue by Alazoral** [atom/atom#9503]
This keeps happening after I leave Atom running for a while:
![screen shot 2015-11-10 at 11 22 25 am](https://cloud.githubusercontent.com/assets/682772/11050798/5e86af64-879d-11e5-8ffa-6492eafe08fb.png)
Every single one of those folders contains an *identical* v1.10 Atom.app. This is using a significant amount of download quota and totally filling my small SSD - that listing represents almost 9 GB! At startup, Atom deletes all the folders and the cycle continues.

**Comment by benogle** [comment]
cc @joshaber, was the issue fixed recently? Is it on 1.2.0 beta?

**Comment by joshaber** [comment]
This should have been fixed in 1.1 :disappointed:

@Alazoral what version are you on?

**Comment by Alazoral** [comment]
@joshaber 1.1.0, sorry bro.

**Comment by joshaber** [comment]
I reopened #7061 so I'll close this one.
