### ISSUE TITLE
getBeginningOf(Next|Previous)ParagraphBufferPosition doesn't work with CRLF line endings

### ISSUE THREAD

**Issue by cheniel** [atom/atom#9504]
`getBeginningOfNextParagraphBufferPosition` and `getBeginningOfPreviousParagraphBufferPosition` in [cursor.coffee](https://github.com/atom/atom/blob/master/src/cursor.coffee) do not work if the line endings are CRLF. For example, when using vim-mode, paragraph jumping does not work (see atom/vim-mode#911).

I spent a good deal of time trying to fix this problem, but I don't have a good solution. The current regex, `/^\n*$/g`, does not work as Javascript regex counts CRLF as two line breaks ([source](http://www.regular-expressions.info/anchors.html)), so the regex matches to the second half of a CRLF pair. I experimented with some other regex patterns but have been unable to find one that works.

I also considered getting CRLF/LF information from elsewhere and using that to pick a regex pattern to use. I tried `@editor.buffer.prefferedLineEnding`, but that is unreliable, as it needs to be set explicitly or it is undefined. 

Another option, which I haven't tried implementing, is to simply use the line ending of the current line to pick the regex, however I am not sure if this would be considered acceptable behavior. If this seems reasonable I'd be happy to implement it and PR. If there are other ideas, I'd also be happy to implement them.

**Comment by rluiten** [comment]
I bet this is the same core problem behind this issue https://github.com/atom/atom/issues/9270 "Editor:move-to-end-of-word does not move beyond end of line if CRLF line ends in file"

**Comment by cheniel** [comment]
Yep, although I don't think that issue has to do with these paragraph movement methods, I'm thinking it's likely a similar regex problem.

**Comment by maxbrunsfeld** [comment]
I think this is fixed via atom/atom#9937. It will be out in Atom versions 1.4.0 and 1.4.0-beta0.
