### ISSUE TITLE
Add 'Install Packages' To Packages Drop Down

### ISSUE THREAD

**Issue by francoislaberge** [atom/atom#9512]
For me at least, I expected the top level **Packages** menu to have entry for jumping to installing/managing packages. Hell Straight up having an Install Packages button somewhere always visiable would lead to way more activity, albeit be more crude. But let's stick to my former feature request. 

Just my opinion,
Francois

**Comment by mnquintana** [comment]
Thanks for the suggestion! This seems similar to https://github.com/atom/settings-view/issues/651 - would you mind taking a look at that one and seeing if it's what you're looking for?

**Comment by francoislaberge** [comment]
That sounds pretty close. I'm cool with this being marked as duplicate and/or just referenced in that discussion if there are subtle differences.
