### ISSUE TITLE
Editor has crashed

### ISSUE THREAD

**Issue by philcruz** [atom/atom#9516]
I'm using Windows 10. Atom is crashing when I click on files to edit

http://screencast.com/t/QHnRKNDMHxE

What could be the issue? Are there log files that would give a clue?

**Comment by philcruz** [comment]
I launched in --safe mode and it still crashes

http://screencast.com/t/XLSzhbzmJI

**Comment by philcruz** [comment]
Using version 1.1.0.

**Comment by benogle** [comment]
Could it be #9339? Can you try 1.2.0-beta2?

**Comment by philcruz** [comment]
I would love to try 1.2.0-beta2. Unfortunately I'm hitting #9515 So I can't install. I guess I can try the zipped release. I'll try that and let you know....

**Comment by philcruz** [comment]
Using the zipped release of 1.2.0-beta2 I haven't crashed yet. Thanks!

**Comment by edwin-itrs** [comment]
Windows 7, version 1.1.0 frequent crashes on opening files.
