### ISSUE TITLE
Add more file extensions on OS X

### ISSUE THREAD

**Issue by simurai** [atom/atom#9518]
Carried over from #9449. Currently Atom's `file` icon gets used for these file extensions: https://github.com/atom/atom/blob/master/resources/mac/atom-Info.plist

Would be good to add at least all the languages that come bundled with Atom: https://github.com/atom/language-examples/tree/master/languages

I think these are missing:

- `clojure`
- `COMMIT_EDITMSG`
- `less`
- `mk`
- `mustache`
- `erb`
- `scss` + `sass`
- `toml`

![screen shot 2015-11-11 at 11 07 26 am](https://cloud.githubusercontent.com/assets/378023/11081983/b9f5052c-8864-11e5-83b4-cce677e3779c.png)

**Comment by maxbrunsfeld** [comment]
:+1:

Also, I think the usual file extensions for clojure are `.clj` (for regular clojure) and `.cljs` (for clojurescript).
