### ISSUE TITLE
Unexpected folding behavior

### ISSUE THREAD

**Issue by DiogoDoreto** [atom/atom#9530]
If I follow these steps:
1. Fold Level 2
2. Open a single fold in code
3. Fold Level 3

I would expect that only the visible code to be folded at level 3. Currently Atom opens all folds and folds all code at level 3. This annoys me when I need to go through big files.

_Note: Sublime Text behaves as I'd expect_

**Comment by maxbrunsfeld** [comment]
So you're saying that `Fold Level 3` should mean something like `Fold Level <= 3`, so that code folded at a lower level would stay folded?

**Comment by DiogoDoreto** [comment]
Yes, exactly like that. Because changing the fold level of entire file again loses the current context.

**Comment by boylett** [comment]
+1 - This is incredibly frustrating when dealing with large libraries
