### ISSUE TITLE
Cursor disappears and unable to select text on Mac after using arrow keys.

### ISSUE THREAD

**Issue by jagalbraith** [atom/atom#9531]
The cursor disappears and causes you to have to do a CMD-ALT-Control-L to reset the editor to get it back when you are at the start of a line and use the left arrow on your keyboard to jump to the end of the previous line. 

I have a Macbook Pro - Late 2011 with El Capitan installed. 
Atom version 1.1.0

**Comment by maxbrunsfeld** [comment]
Does this happen if you run Atom with `--safe`?

**Comment by jagalbraith** [comment]
I couldn't replicate it with the --safe option with the little testing I did. I have been disabling add ons and themes trying to pin it down but haven't found what the culprit is.
 
John Galbraith
Information Security Analyst

**Comment by maxbrunsfeld** [comment]
Ok thanks @jagalbraith. I'm going to close this for now. I'll reopen if you are able to repro in safe mode.

**Comment by daniel-a-melo** [comment]
I have the same symptom with Atom 1.2.0 and the package `atom-innerspace` on Windows 10
