### ISSUE TITLE
weird horizontal scroll bar

### ISSUE THREAD

**Issue by Jheysoon** [atom/atom#9537]
Steps to reproduce..

1. center the horizontal scroll bar
2. close atom and open again

![bug1](https://cloud.githubusercontent.com/assets/8098903/11110205/082d2e0c-8934-11e5-9c64-a8379f891313.gif)
atom version 1.2.0-beta 3
windows (x86)

Also exists in atom --safe mode

**Comment by 50Wliu** [comment]
Duplicate of #9189, please subscribe there for updates.
