### ISSUE TITLE
copy/paste in native inputs no longer works

### ISSUE THREAD

**Issue by yinghuitan** [atom/atom#9548]
Hi,

Nuclide debugger uses chrome debugger UI as it front end UI. Atom seems to hijack the copy/paste operations which caused these operations to be disabled in Nuclide watch/console window. 

I think it is regressed in recent Atom releases per user reporting. 

Any idea how to fix this?

Jeffrey

**Comment by yinghuitan** [comment]
Btw: I just synced my Atom back to 1.0.18, copy/paste works fine so it is regressed between 1.0.18 and 1.1.0.

**Comment by noseglid** [comment]
I have the same issue in the package I am maintaining: https://github.com/noseglid/atom-build/issues/221

I've verified that I have `tabIndex=-1` and `native-key-bindings` set. I'm sure this worked at some point.

**Comment by lee-dohm** [comment]
I'm not sure if @noseglid's and @yinghuitan issues are actually the same issue, but here is some context:

https://discuss.atom.io/t/copy-from-panels-stopped-working-even-with-tabindex-1-and-native-key-bindings-class/22891

I can confirm @noseglid's bug on Stable v1.2.3, Beta v1.3.0-beta0 and a recent Alpha.

**Comment by noseglid** [comment]
This still doesn't work for me, OS X with Atom 1.3.0.

I can't copy from the build panel (from [noseglid/atom-build](https://github.com/noseglid/atom-build)), nor from notifications or other panels (such as the one produces by [AtomLinter/linter](https://github.com/AtomLinter/linter))

**Comment by lee-dohm** [comment]
According to the PR, the first tag it showed up in is `v1.4.0-beta0`. Please test it on the Beta channel and let us know.

**Comment by noseglid** [comment]
Yes it's working on the Beta channel. Why wasn't this included in `v1.3.0` which was just released?
This is quite a big issue in my package where build errors often need to be copied for googling and stuff.

Can we make a minor release with this?

**Comment by lee-dohm** [comment]
We're taking a look at it for a patch release to Stable. I don't have a timeline for when the patch release will be.

**Comment by lee-dohm** [comment]
@noseglid Check out v1.3.1 and let us know :grinning:

**Comment by noseglid** [comment]
@lee-dohm `v1.3.1` works well. Thank you for releasing this in a patch release!
