### ISSUE TITLE
Scrolling through document is sluggish

### ISSUE THREAD

**Issue by danielbonnell** [atom/atom#9549]
Hi, I just upgraded to Atom v1.1.0 and have noticed an issue with scrolling. When I have a large file open (at least a few hundred lines) and scroll with the trackpad, the scroll is sluggish depending on how slowly I scroll. If I scroll slowly, it's very sluggish, however if I scroll at a faster rate, the speed increases exponentially. This makes it very difficult to navigate a large document by scrolling through it. I'm running on OS X 10.11.

**Comment by nathansobo** [comment]
@danielbonnell And this got worse for you in the transition from 1.1.0 to 1.2.0?

**Comment by danielbonnell** [comment]
I'm not sure which version I was on previously, but when I restarted it updated to 1.1.0, which is when I first noticed the problem. I've since updated to 1.2.0 but the problem is still present. I would describe it more accurately as non-linear scrolling. Before, scrolling was linear in the sense that the speed was proportionate the how fast I moved my fingers on the trackpad. Now if I move slowly, the scrolling is very slow, but as I speed up, the scroll speed increases much faster than I would expect.

**Comment by danielbonnell** [comment]
Was this issue ever resolved? I just updated to 1.2.4 and I'm still having problems with this. It's a major annoyance when scrolling through a large file with 4000+ lines.

**Comment by splodingsocks** [comment]
I've begun to see jerky scrolling, also, on the later Atom versions. It's been problematic enough that I've taken to using other editors in the mean-time. I tried launching Atom in "safe" mode just to be sure it wasn't a customization of mine that was causing performance issues, but sadly the jerkiness was still present.

Thanks for all the work you do, Atom team!

**Comment by danielbonnell** [comment]
Just updated to 1.3.2 and the issue seems to have been resolved.

**Comment by anselmobattisti** [comment]
Im using 1.14.3 ia32 and the bug starts again! 

Impossible to work!

**Comment by levani** [comment]
I'm also having this problem on 1.15.0 on osx. Also had it in 1.14.

**Comment by danielbonnell** [comment]
I just updated to 1.15.0 on OS X and everything seems in order for me.

**Comment by andrew-dixon** [comment]
I've just started looking at Atom again for the first time in a while and this scrolling issue is the only issue I'm having at the moment, using 1.14.4 on OS X. 😞

**Comment by levani** [comment]
I tried this in safe mode as well and scroll start much much slower than in vs code for example. This is a really bad experience for me...

**Comment by jfischoff** [comment]
I also have had to stop using Atom on OSx with 1.15. I disabled must packages too.

**Comment by 50Wliu** [comment]
For anyone experiencing these scroll issues, it would be very helpful if you could open a new issue.  That way, we can more effectively triage the root cause.

**Comment by nathansobo** [comment]
I'm in the process of completely rewriting editor rendering, which will include a different approach to scrolling that may alleviate peoples issues with the current design. Right now scrolling is implemented completely in JavaScript, dating back to a time when Chrome scroll events were delivered asynchronously. Now that Chrome sends scroll events synchronously, we can use a simpler design which I'm hoping will provide a more native feel across platforms.

**Comment by andrew-dixon** [comment]
For me, updating to 1.15 fixes the issue 👍

**Comment by finnrayment** [comment]
I seem to be getting some sort of lag on any file that requires scrolling... 1.16 and its terrible on OSX.

**Comment by lordozb** [comment]
On ubuntu 16.04 I am getting terrible lagging after updating it 1.18

**Comment by fulldecent** [comment]
macOS with 1.19.4 is also slow

**Comment by levani** [comment]
macOS with 1.20.1 is also slow. I made a quick comparison with vs code and sublime. I full swipe on trackpad scrolls at least 60 lines on both editors. In atom the same action scrolls only 20-25 lines.

**Comment by sogen** [comment]
as @levani and @fulldecent describe the issue, I'm also affected by this issue, the use of scroll is very slow.
Using minimap seems to help a little bit.
Tried uninstalling almost all plugins but that didn't solve it.

**Comment by sogen** [comment]
Realized the scrolling feels unnatural after I compared it to other platforms. 
Sublime (and iOS and other platforms) have a momentum scrolling, where the faster the initial scroll the further down it scrolls. 
In Atom on the other hand, scroll has no momentum, it doesn't take the force of the scroll into account, so it's not translating the impulse into the speed and final position of the scroll.

**Comment by j127** [comment]
I'm also having problems with scrolling after completely deleting Atom (including config directories) and reinstalling today. It's also a problem with the Slack desktop app, so I wonder if it's a problem with Electron.

Scrolling isn't fast any more, but seems to have some kind of slowing down effect ("smooth scrolling"?) when trying to scroll quickly through large files. Scrolling rapidly with the touchpad is now very unpleasant.

Ubuntu 16.04. Atom 1.21.1 x64.

**Comment by sogen** [comment]
Hi, noticed that you need to CLICK the text area to enable scroll :(

________________________________

**Comment by skaraman** [comment]
Scrolling is faked. Lines in the editor are swapped out based on a translate/x/y position and don't actually exist in the DOM until you scroll to them. Then the lines you scrolled away from are deleted from the DOM. It's rather counterintuitive and the amount of cpu power needed when quickly scrolling back and forth is pretty large.

**Comment by 50Wliu** [comment]
> It's rather counterintuitive and the amount of cpu power needed when quickly scrolling back and forth is pretty large.

@skaraman do you have any suggestions to how to improve this situation?  That would help rather than just saying that the current behavior is counterintuitive :).  In addition, the GPU is used when scrolling, not the CPU.

**Comment by nathansobo** [comment]
Well to be fair we do quite a bit of work on the CPU to create new tiles as they are paged in and send them to the GPU. The DOM is a real bottleneck... manipulating it, style recalc, and layout consume the majority of the frame.

**Comment by skaraman** [comment]
> do you have any suggestions to how to improve this situation?
I don't know a lot yet about how the parsing of files happens, but I imagine if currently Atom has to parse files to understand which lines to display on the screen then instead it would preload the entire file into the DOM. Understandably this could have a big problem with very large files but these can be broken up into DocumentFragments probably, and as a fallback use the current method.
