### ISSUE TITLE
Installing packages failed.

### ISSUE THREAD

**Issue by Bantes** [atom/atom#9552]
`Linux Bantes 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

install any packages will be show the err output like this:

gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.30.7/node-v0.30.7.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at createHangUpError (http.js:1473:15)
gyp ERR! stack     at Socket.socketOnEnd (http.js:1569:23)
gyp ERR! stack     at Socket.g (events.js:180:16)
gyp ERR! stack     at Socket.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:944:16
gyp ERR! stack     at process._tickCallback (node.js:448:13)
gyp ERR! System Linux 3.13.0-68-generic
gyp ERR! command “/usr/share/atom/resources/app/apm/bin/node” “/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js” “install” “–target=0.30.7” “–dist-url=https://atom.io/download/atom-shell” “–arch=x64” “–ensure”
gyp ERR! cwd /home/bantes/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by sabertazimi** [comment]
```shell
$ touch ~/.atom/.apmrc && echo 'strict-ssl = false' > ~/.atom/.apmrc
```

It works for me.I hole that would be useful for you,too.
