### ISSUE TITLE
Uninstall button of plugins should ask for confirmation

### ISSUE THREAD

**Issue by keul** [atom/atom#9557]
The "Uninstall" button of community plugins just remove, without asking for any confirmation.

![schermata 2015-11-13 alle 09 23 51](https://cloud.githubusercontent.com/assets/284924/11141722/4c2ad3fc-89e8-11e5-88ea-2b60aee54c05.png)

This can lead to errors when the users click it by mistake (for example: his intention was to click "Settings" or "Disable")

**Comment by abe33** [comment]
Hi @keul, I moved your issue on the proper repository: atom/settings-view#699

I'm closing this one then.
