### ISSUE TITLE
Services menu in OS X doesn't work

### ISSUE THREAD

**Issue by sunabozu** [atom/atom#9558]
I just installed Atom 1.2 on OS X 10.10 and noticed that the `Services` menu doesn't work. I use Automator script to control my music player, so without that menu I have no access to global OS X hotkeys when I'm in Atom. The `Services` menu item itself is present, but it has no submenu.

I'm not sure if this issue emerged after updating to Atom 1.2 or it existed before.

**Comment by 50Wliu** [comment]
This has been fixed in the 1.3.0 betas I believe.
