### ISSUE TITLE
Atom 1.2.0 (1.3.0-beta) color schema changes.

### ISSUE THREAD

**Issue by alexbeletsky** [atom/atom#9562]
Again as #9561 I appologize for not having good details, but after an upgrage I've noticed that JS color schema changed. Currenly I have 1.1.0 and 1.3.0-beta installed side by side.

With having identitical plugins, JS file in 1.1.0

<img width="517" alt="screenshot 2015-11-13 10 26 59" src="https://cloud.githubusercontent.com/assets/304929/11142925/3b335084-89f1-11e5-9df6-c9d31fcc717a.png">

In 1.3.0-beta

<img width="520" alt="screenshot 2015-11-13 10 27 15" src="https://cloud.githubusercontent.com/assets/304929/11142929/458db470-89f1-11e5-986c-8200e96d2048.png">

All variables become red with Javascript (JSX) language selected. 

It might seems as minor thing, but color schema changes (especially to that red color) is quite significant experience change, that I would like to avoid.

**Comment by jsjain007** [comment]
### in my opinion it looks better

**Comment by 50Wliu** [comment]
@alexbeletsky there were multiple import/export improvements in language-javascript to properly tokenize those things.

/cc @MaximSokolov.

**Comment by MaximSokolov** [comment]
Ref: atom/language-javascript#237
I suppose your syntax theme color all variables like that. Most of them just are not tokenized.
You can change variables on the second screenshot by adding this to your stylesheet:
```less
@import "syntax-variables";

atom-text-editor::shadow {
  .module.js, .module-alias.js {
    color: @syntax-text-color;
  }
}
```

**Comment by peduxe** [comment]
@alexbeletsky [language-babel](https://atom.io/packages/language-babel) grammar tokenizing is much better and supports more ES6/7 cases, Flow and JSX.
