### ISSUE TITLE
Atom 1.2.0 (1.3.0-beta) JS and JSX syntax

### ISSUE THREAD

**Issue by alexbeletsky** [atom/atom#9563]
After upgrade to 1.2.0 all my `.js` files that were treated as `Javascript (JSX)` syntax are treated as `Javascript` and I need to manually switch every time I start to render.

I haven't found and toggles to make the change persitant. In the same time, it works totally fine in 1.1.0.

**Comment by nathansobo** [comment]
@alexbeletsky I assume you're using the [language-jsx](https://github.com/Icehunter/language-jsx) extension. Do your files have a `.jsx` extension? If not, you can override the grammar used for the `.js` extension by adding this to your `config.cson`:

```coffee
"*":
    core: 
      customFileTypes: {
        "source.jsx": ["js"]
      }
```

**Comment by 50Wliu** [comment]
language-javascript definitely shouldn't be overriding language-jsx in this case; it doesn't even list `.jsx` as a valid filetype for JS.  Something else seems to be happening here.

**Comment by nathansobo** [comment]
@50Wliu It seems like for some reason we were previously choosing the JSX grammar for `.js` files, and now we're not. Without a link to the actual grammar being used, it's hard to say.

**Comment by 50Wliu** [comment]
Ah, I misread the initial issue (I thought it was `.jsx` files getting tokenized as JS).  Sorry.

**Comment by alexbeletsky** [comment]
Previosly JSX grammar has been used for `.js` files, now it's not. My question is how to tweak to treat all `.js` files as JSX?

I don't use `language-jsx` package.

**Comment by abe33** [comment]
@alexbeletsky Have you tried the snippet provided by @nathansobo? Given you have `language-jsx` installed it will use the JSX gramar for every `.js` file.

@50Wliu Was JSX ever supported by language-javascript in the first place?

**Comment by 50Wliu** [comment]
I don't believe so.  It was inadvertently supported by Linguist though, and was fixed one to two months ago.
