### ISSUE TITLE
::shadow warnings in the console

### ISSUE THREAD

**Issue by albertosantini** [atom/atom#9564]
With Atom `1.2.0`.

In the console log, when Atom starts without any open file:
```
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

In the console log, after opening a file:
```
[cut]\AppData\Local\atom\app-1.2.0\resources\app.asar\src\text-editor-component.…:919 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

**Comment by simurai** [comment]
From this [Chromium issue](https://code.google.com/p/chromium/issues/detail?id=489954#c17):

> There is no timeline to remove `/deep/` (or `::shadow`) from chromium, as of now. We can't remove `/deep/` in the near future because the usage [1] is too high.

> We are likely to continue to support it for a while, maybe for a couple of quarters, or years. :(

And..

> As for the static profile,  I'll __un-deprecate__ `/deep/` in the static profile if other browser vendors agree that we should support /deep/ in the static profile [2]. However, I think that __won't happen soon__.

So that deprecation warning might go away again.
