### ISSUE TITLE
Possible Startup Improvements

### ISSUE THREAD

**Issue by as-cii** [atom/atom#9572]
This issue is aimed at listing and evaluating some speedups we could potentially employ on startup. The reported savings are somewhat suppositional, in that they may or may not represent the actual time we will end up saving.
### Breaking Startup Down

![breakdown](https://cloud.githubusercontent.com/assets/482957/11148370/b18ae820-8a1c-11e5-9456-edb230584f38.png)
### What could we attack?

| Operation | Cost | Potential Savings | Notes |
| :-: | :-: | :-: | :-: |
| JSON Parsing | 50ms | 30ms |  |
| Reading Less Cache | 40ms | 30ms |  |
| Resolving Modules | 56ms (?) | 50ms (?) | We suspect the require path takes much more than this, but it's hard to tell from the profiler. |
| Loading Grammars | 150ms | 100-120ms |  |
| Slow Reflows | 150ms | 100ms (?) | It's not clear whether Chrome needs to spend a fixed amount of time when it reflows stuff the first time. |
| Sync GitRepository | 45ms | 45ms |  |
| Electron Startup | 180ms | 100-120ms (?) | We may probably use the NativeCompileCache here as well, and speeding up the require path may help too. |
| - | - | - | - |
| **Total:** |  | 450-480ms |  |

Please, note that the speedups herein highlighted wouldn't _revolutionize_ the way Atom handles the above operations. This means that there are probably other ways in which we could make things faster by, for example, introducing breaking changes: this is outside the scope of this issue, though, as we're currently looking for optimizations that are safe and compatible with how things work as of today.

Also, there may be other chances to make startup faster by employing some hack to simply show an hidden window instead of reloading the whole environment: this, however, should probably be the subject of another issue, as it is a completely distinct approach.

/cc: @atom/feedback @nathansobo

**Comment by benogle** [comment]
Love the breakdown :+1:

**Comment by etiktin** [comment]
Does the JSON parsing operation counts CSON parsing as well?

**Comment by nixpulvis** [comment]
Been a while, I'd be curious to see the graph again now.

**Comment by nathansobo** [comment]
@as-cii Does your new issue supplant this one?

**Comment by as-cii** [comment]
Yes, this is superseded by #13253 and we will post updates on that issue as we make progress on reducing startup time.
