### ISSUE TITLE
atom 1.2.0 release cannot start as root

### ISSUE THREAD

**Issue by SlimeQ** [atom/atom#9573]
just upgraded to 1.2.0 release and suddenly can't run as root.

this is on an Ubuntu 14.04 fresh install

1.1.0 does not have this issue

**Comment by kevinsawicki** [comment]
What error are you seeing at startup? Or does the window not appear at all?

Also is there any console output? If you start `atom` with the `-f` option it should log there.

**Comment by kevinsawicki** [comment]
This looks similar to #9569 are you seeing the same error in the screenshots there?

**Comment by lee-dohm** [comment]
Since there hasn't been a response to the request for more information, I'm going to close this. Please let us know if there is more information you can give us to help us understand :grinning:
