### ISSUE TITLE
Editor crashes when I try to save a new file

### ISSUE THREAD

**Issue by ifriedman08** [atom/atom#9576]
I've been using Atom for several weeks (on windows 7) with no issue but now, when I try to add a folder or file to my project directory, a window appears saying the editor has crashed offering three options:
close, reload, leave open
If I choose the option to leave it open, the window goes white. Any thoughts?

**Comment by nathansobo** [comment]
What version of Atom are you running?

**Comment by ifriedman08** [comment]
1.2.0

**Comment by nathansobo** [comment]
Did it happen in previous versions?

**Comment by nathansobo** [comment]
@raelyard could you give @ifriedman08 guidance on how we might get a crash dump from this problem?

**Comment by ifriedman08** [comment]
No to previous versions.

**Comment by raelyard** [comment]
Should be able to find a crash dump with a .dmp extension and a .txt file with meta info about the app in C:\Users\David\AppData\Local\Temp\Atom Crashes
such a pair for each crash

**Comment by ifriedman08** [comment]
Local/ appears empy

**Comment by raelyard** [comment]
I'm sorry - I completely glossed over that you are on Windows 7.  I think it should be here on Win 7:
C:\Windows\Minidump

Can't verify now, but will in a bit.  If I get to it before you do, I'll confirm on a Windows 7 machine where to find the dumps.

**Comment by raelyard** [comment]
@ifriedman08 It appears I lied to you - it should be in the same location on Windows 7.
C:\Users\YOUR_USER_NAME\AppData\Local\Temp\Atom Crashes

I'm wondering if you see Local empty because you are looking in Windows Explorer and have settings such that it's hiding the contents.  If you Windows+R for a run prompt and just enter the full path to the Atom Crashes directory, does that path exist?

**Comment by ifriedman08** [comment]
Hi all,

The issue seems to have resolved itself suddenly.... not sure what I did (if anything). Thanks guys! I will bring it back up if anything changes.

**Comment by reinvantveer** [comment]
I can confirm the crash on Ubuntu with LXDE gui. Running Atom 1.2.1, using context menu (right click) on a folder, choosing "New File". Happened once, I can't seem to reproduce it :(.

**Comment by damieng** [comment]
Don't have a solid repro for this. If you have one please re-open this issue and provide details!
