### ISSUE TITLE
Atom wants to downgrade itself from the latest version

### ISSUE THREAD

**Issue by AgentME** [atom/atom#9577]
The blue squirrel icon at the bottom right lit up today, so I clicked it.
![screen shot 2015-11-13 at 10 26 45 am](https://cloud.githubusercontent.com/assets/577345/11153973/32000a20-89f1-11e5-9574-976fedfe36b1.png)
It shows an update to 1.1.0 being available as of the October 29. But I was pretty sure I updated Atom more recently than that. The Atom menu says that I'm on 1.2.0! If I click the "Check for Update" button, I get this:
![screen shot 2015-11-13 at 10 26 53 am](https://cloud.githubusercontent.com/assets/577345/11154001/660851ec-89f1-11e5-861a-787eb1d06396.png)
Was the latest version of Atom rolled back for some reason? I think I'm just going to avoid "updating" for now.

**Comment by benogle** [comment]
You are on the latest version. This is a crappy bug. It is a bug in the release notes package. We plan to do some UX work to the update process soonish. Please subscribe to https://github.com/atom/atom/issues/9164 for more info
