### ISSUE TITLE
If atom is launched on non-primary monitor, dropdowns appear in wrong place

### ISSUE THREAD

**Issue by DanielJoyce** [atom/atom#9579]
1. Open atom on non-primary screen ( You do this by moving terminal to non primary screen, and typing "atom ." to launch)
2. go to preferences -> Settings, go to "Tab length", click dropwdon
3. Notice that drop down appears in wrong place, or doesn't appear ( likely due to rendering off screen)
4. Drag atom to primary screen
5. Click dropdown, notice it is positioned properly
6. Drag atom back to non-primary monitor
7. Click tab length dropdown
8. Notice it works properly now.

Atom 1.1.0

uname -a: 
Linux lnx-daniel 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

/etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"

**Comment by fsievers** [comment]
I have the same problem even with single screen setup on two devices, both running Ubuntu Gnome 15.10. The problem appears with with Atom 1.2.1 and 1.3.0-beta1 (both build from source). See a

ttached image.
![atom-dropdown-offset](https://cloud.githubusercontent.com/assets/2866107/11168142/b14b7b82-8b83-11e5-8c92-4bdc19643b99.png)

**Comment by tinchoz49** [comment]
same error in 1.2.1

**Comment by Preovaleo** [comment]
Error still there in atom 1.5.4

`Linux _REDACTED_ 4.4.4-301.fc23.x86_64 #1 SMP Fri Mar 4 17:42:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by v3ss0n** [comment]
still effect in latest commit.
