### ISSUE TITLE
atom 1.2, 1.3-beta does not respect themes scrollbar styling on load

### ISSUE THREAD

**Issue by hatched** [atom/atom#9582]
When starting Atom in a directory where you currently had files open the scrollbars are loaded in each pane without any theme styling. If you then open a new file in that pane the scrollbars styles will be properly applied.

1.1 is OK.
OS: Ubuntu 14.04

**Comment by 50Wliu** [comment]
I believe this has been fixed by #9575 and will be available in 1.3.0-beta1.
