### ISSUE TITLE
Cannot drag file to atom window to display it on linux

### ISSUE THREAD

**Issue by xgdgsc** [atom/atom#9588]
I' m using KDE 5 and atom 1.2.0 on archlinux. If I drag a text file from dolphin to atom window, there is no effect, while usually other text editors would display the text file when dragged into the window. Atom on OSX also supports this function. Is this not available on linux because of https://github.com/atom/atom/issues/3593 ?

**Comment by fiws** [comment]
[This happens](https://photos.google.com/share/AF1QipPLfFYoyAlsPRjrl1pXGFpe1l92t8cl3QkXw6n4XOTGZjJnFvkoEsNOU0Rp9QlAPg/photo/AF1QipMf24HdKkyXdmcZUkGGIOM-rRW6iaSUSAic6Fri?key=T0hRT0VQci1weUJZbzhWM01HdUVoZFdrSV9JanFR) when I try that. (Nautlius + atom 1.2)

**Comment by ricardograca** [comment]
It seems to work fine in Ubuntu with Nautilus, so probably not a widespread issue. The fix for issue #3593 is present in the 1.2.0 release.

**Comment by Kais-DkM** [comment]
Same issue here for Kubuntu 15.10. I've also tried other types of files, but nothing was opened on atom.

**Comment by xgdgsc** [comment]
Seems working now with kde and atom 1.7.3, closing this.
