### ISSUE TITLE
Wrong restart message and release notes not up to date

### ISSUE THREAD

**Issue by rugk** [atom/atom#9590]
After updating to Atom v1.2.0:
![wrongrestartmessage](https://cloud.githubusercontent.com/assets/11966684/11163391/9504dccc-8acd-11e5-8ac6-dfd838f223d2.png)

**Comment by lee-dohm** [comment]
It sounds like this is a bug in the [release-notes package](https://github.com/atom/release-notes). Would you mind filing the bug there?

**Comment by rugk** [comment]
Done.
