### ISSUE TITLE
Problem with opening file in OS X and shortcut Go to directory

### ISSUE THREAD

**Issue by pom421** [atom/atom#9593]
I can't use my favorite shortchut in OS X (10.11 El Capitan). The Atom's version is 1.2.0. 
I have a french keyboard (AZERTY one)

I copy a file path with the finder. Let's say /Users/john
- i want to open a file in Atom : Cmd-O
- a finder-like windows appears. i want to go through a directory with the shortcut Cmd-Shift-G
- i can't paste the path /Users/john what is not the expected behavior

!**Installed packages:**
I have no addtionnal package installed. 
- Problem can be reliably reproduced, doesn't happen randomly: Yes on 2 devices
- Problem happens with all files and projects, not only some files or projects: Yes

**Comment by 50Wliu** [comment]
Duplicate of atom/atom-keymap#35 and atom/atom-keymap#37, please subscribe there for updates.  You can try installing the [keyboard-localization](https://atom.io/packages/keyboard-localization) packages as a workaround.

**Comment by pom421** [comment]
Sorry but i don't think this is a duplicate problem of issue #35. In my opinion, it's not a keybinding issue (i don't have Alt-Gr key, i am with an Apple keyboard).

To sum up, the only problem is i can't paste the path in the modal window. 

When i do "Open file", atom shows me the window to navigate across my hard disk. Then i use the shortcut Cmd-Shift-G, wich is ok, and shows me the modal window to put a file path. 
But i can't paste the path in this window. 

I hope this is clearer.

**Comment by 50Wliu** [comment]
Ok, it might not be a duplicate of atom/atom-keymap#35, but it still seems to be a duplicate of atom/atom-keymap#37.  As you can see in the initial example, an AltGr is not needed to trigger the bug in the case of atom/atom-keymap#37.

**Comment by pom421** [comment]
It's not either a duplicate of #37. 

There is no problem with copy/paste (Cmd-C/Cmd-V) in the real windows of Atom (the editor tabs).
But the paste is not enable when you pass by the "open file" window and the "Shift-Cmd-G" shortcut. 

I have made one more test with a Mac book air with OS X 10.10.5 and Atom 1.0.11. 

I can reproduce the bug with 3 different devices so i think it's a bug ;)

**Comment by 50Wliu** [comment]
Oh, ok.  I don't use the Mac so that's probably why I didn't understand at first.  Sorry!

**Comment by sclarkso** [comment]
I am having this same issue.  Very frustrating when I have the path of a file I want to open on my clipboard, but can't do anything with it.
