### ISSUE TITLE
What happened to the downloads for 1.3.0-beta1?

### ISSUE THREAD

**Issue by forivall** [atom/atom#9595]
I downloaded the deb package for 1.3.0-beta1, updated [my aur package](https://aur.archlinux.org/packages/atom-editor-beta-bin/), and now that it's been removed, the version of my aur package is in a limbo state.

What happened?

Also, why are there no binary downloads for 1.2.1?

**Comment by 50Wliu** [comment]
There were missing assets for the Mac platform due to a build issue.

1.3.0-beta2 should be out soon, but no guarantees (especially since I'm not a Github employee).

Also, where are you seeing the 1.2.1 release?

**Comment by forivall** [comment]
A [tag was made](https://github.com/atom/atom/releases/tag/v1.2.1). I have notifications for the atom/rss feed for releases (that's atom, the feed format :wink:), since I'm maintaining the beta aur package, and a co-maintainer for the mainline. Unfortunately, it pings me when the tag is made, not when the files are uploaded.

**Comment by 50Wliu** [comment]
Ah.  Watch for the release itself, not the tag :).  Tags may come before the actual release.

**Comment by forivall** [comment]
Unfortunately, the [atom feed](https://github.com/atom/atom/releases.atom) for releases includes tags :(. I've closed this, it's now become a bug for github itself :).
