### ISSUE TITLE
Package-defined deserialization is broken (Atom-1.2.0)

### ISSUE THREAD

**Issue by mojodna** [atom/atom#9600]
I was running into this with my own package, but it can be reproduced with the `release-notes` package by:

1. open a directory as a project (`atom .`)
2. open the developer console
3. show the release notes (⌘⇧P Release Notes: Show)
4. reload (View → Reload)
5. observe the following error:

```
No deserializer found for Object {deserializer: "ReleaseNotesView", uri: "atom://release-notes", releaseNotes: Array[23], releaseVersion: "1.1.0"}
```

(Note: when first loaded, it's displaying the release notes from 1.1.0, which is presumably unrelated.)

Possibly related to #9598

**Comment by mojodna** [comment]
(Wrong release notes is #9590)

**Comment by jamesgpearce** [comment]
Seeing this in Nuclide too.

**Comment by benogle** [comment]
cc @nathansobo
