### ISSUE TITLE
Privacy policy must disclose the use of Google Analytics

### ISSUE THREAD

**Issue by tombrossman** [atom/atom#9602]
As stated in the [FAQ](https://atom.io/faq) page, Atom uses Google Analytics to provide useful feedback to the development team. I see from issue #4966 that work has started on providing a way for users to give informed consent, which is great.

Google Analytics' [Terms and Conditions](https://www.google.com/analytics/terms/us.html) under section 7 "Privacy" read: _"You must post a Privacy Policy and that Privacy Policy must provide notice of Your use of cookies that are used to collect data. You must disclose the use of Google Analytics, and how it collects and processes data."_

This is currently missing from your privacy policy and must be added to be compliant with Google's T&Cs, whether a method to opt-in (or out) is later added.

It's acceptable to use Google Analytics, you just have to disclose that you use it in a Privacy Policy.

**Comment by 50Wliu** [comment]
@tombrossman Can you please move this over to the [atom/metrics](https://github.com/atom/metrics) repo?  Thanks.
(Also, the README in the metrics repo both discloses the use of GA and what data Atom collects.  There's also a notice present on the initial Welcome screen to Atom.)
