### ISSUE TITLE
Atom won't start after 1.2.0 update on Win 8.1, even in safe mode

### ISSUE THREAD

**Issue by clemorphy** [atom/atom#9604]
Window 8.1
When I launch Atom, the window shows up, and then nothing. The menu bar is here but I can't open a file or go to the settings. When I try to close the window, the following error appears :
`Editor is not responding`

Even in safe mode.

I tried to reinstall Atom with the Windows installer.
Same problem.

**Comment by clemorphy** [comment]
After many tries, it turned out that Atom started correctly after I deleted all files inside the "/storage" directory.

**Comment by benjaminRomano** [comment]
I had the same problem. Deleting the storage folder worked for me too.

**Comment by hughlomas** [comment]
I'm having this issue on 1.2.1, but I'm unable to locate the /storage folder mentioned above in `AppData\Local\atom` or its subdirectories.

**Comment by nathansobo** [comment]
@raelyard Can you try to reproduce this on Window 8.1?

**Comment by raelyard** [comment]
Haven't successfully reproduced yet.  Would be helpful to see a sample of a storage directory exhibiting the problem.  Anybody have that still sitting on disk that can be shared?

**Comment by clemorphy** [comment]
@raelyard I did a backup copy of my storage directory before deleting it, but the files inside contain confidential / private data that I don't really want to share.

There a `application.json` file that contains only this:
`[{"initialPaths":["C:\\wamp\\www\\XXXXXX\\GIT"]}]`
The path matches with my last working directory.

The storage directory also contain 20 files with names like :
`editor-242d1406f469e3cf2365542443408122bfa17519`
`editor-25ce0f00481437bd66431f9886cc7e31608ba4e4`
`editor-29f3fae9a98ffe17f98d195607189f050ac77014`

And their size vary between 1KB and 2780KB

**Comment by damieng** [comment]
@clemorphy did you ever get back into this state or has it been fine since you cleared that folder?

**Comment by clemorphy** [comment]
All has been fine since I cleared that folder :)
