### ISSUE TITLE
[visual bug] scroll bar lost style

### ISSUE THREAD

**Issue by dogis** [atom/atom#9605]
scroll bar on left side pane lost it's style when reopen atom with 2 panes activated. i am using atom 1.3.0-beta-1 on windows 10.
![image](https://cloud.githubusercontent.com/assets/14012643/11169644/11e9086e-8bf8-11e5-8b44-7eae056cc152.png)

**Comment by 50Wliu** [comment]
This has been fixed and will be available in 1.3.0-beta2 when it is released.
