### ISSUE TITLE
Portable 1.3b0 on Windows uses sibling folder for config

### ISSUE THREAD

**Issue by Kalthorn** [atom/atom#9608]
When using the new --portable command line param, my .atom folder is moved to be a sibling of my Atom folder.  I was expecting to see .atom appear within that folder (as a sibling to the executable) and it took me a while to figure out why I didn't see it there.

Would it be possible to make that change?  I think a lot of folks take 'portable' to mean that they can drag a single folder to a new destination and a hidden sibling folder complicates that.

**Comment by benogle** [comment]
cc @kevinsawicki @raelyard

**Comment by paulcbetts** [comment]
What @raelyard said, if you put `.atom` in the same folder as atom.exe, updates will pave it

**Comment by julmot** [comment]
I've just searched about 2h in all related issues and PRs to learn how to make ATOM portable. That's a very annoying startpoint. The [documentation](https://atom.io/docs/latest/search?utf8=%E2%9C%93&q=portable) doesn't show any information about the `--portable` command. Are you expecting from users gather up this information themselfs?

However, I have several questions:
- When using ATOM in portable mode, is it necessary to always run it with the `--portable` parameter or just initially?
- How does this behave with the update mechanism? If ATOM portable does't load updates, what is the prefered way of updating?

Please see this comment not only as a question, but also as a request for documentation improvement about this issue.

**Comment by damieng** [comment]
Instructions on how to make Atom portable are being tracked at https://github.com/atom/atom/issues/10072

Unfortunately having the .atom folder live within the atom folder itself is not possible because of the way updates are processed.

**Comment by julmot** [comment]
Hi @damieng,
Thanks for your reply. Unfortunately this does not answer my second question nor does this respond to my wish to add that to the documentation.

**Comment by damieng** [comment]
Hi Julmot.

Issue #10072 is going to track getting the documentation on using Atom in portable mode.

The portable mode should auto-update just fine however the .atom folder will continue to exist alongside the folder that contains atom.exe rather than within it.
