### ISSUE TITLE
The editor has crashed

### ISSUE THREAD

**Issue by pangyanjin** [atom/atom#9611]
the editor is not responding

**Comment by kkHAIKE** [comment]
add more-information please

**Comment by pangyanjin** [comment]
一直加载不出来，弹出编辑器未反应。
提示：
deprecationSite.getFileName is not a function
The error was thrown from the nuclide-debugger-atom package.
Create issue on the nuclide-debugger-atom package

**Comment by 50Wliu** [comment]
Duplicate of #9350, please subscribe there for updates.
