### ISSUE TITLE
Release Notes for v1.2.0 are not displayed

### ISSUE THREAD

**Issue by kjusupov** [atom/atom#9612]
OS: MacOSX 10.11.1
Atom: 1.2.0

1. Go to Help / Release Notes --> the last release notes are for v 1.1.0
2. Go to Help / Release Notes --> does not display release notes for v 1.2.0
3. Go to Help / Release Notes --> buttons [Restart and update] & [View on atom.io] are active

**Comment by albertosantini** [comment]
Duplicate https://github.com/atom/atom/issues/9590
