### ISSUE TITLE
DirectorySearch is marked as `essential` in docs, but no docs on how to create one

### ISSUE THREAD

**Issue by devoncarew** [atom/atom#9613]
`DirectorySearch` is marked as `essential` in the documentation (https://atom.io/docs/api/v1.2.0/DirectorySearch), but no mention is made about how to create one. Either through a constructor or via some other API call.

**Comment by abe33** [comment]
Not really a detailled documentation, but there was a discussion about that on discuss: https://discuss.atom.io/t/how-to-import-and-use-directorysearch-in-atom/19205/2

**Comment by benogle** [comment]
Why is this essential? @nathansobo?

**Comment by nathansobo** [comment]
I'm not sure. I didn't merge it. We can definitely mark it extended, though I think we should add some docs.

**Comment by nathansobo** [comment]
@maxbrunsfeld You were involved in this API getting introduced... should this class even be public?
