### ISSUE TITLE
Atom hangs when docked to left or right side of screen - Windows

### ISSUE THREAD

**Issue by benjaminRomano** [atom/atom#9616]
After moving Atom to the left side of my screen using windows shortcut (Win+left arrow key) or (Win+right arrow key), Atom hangs. However, when I move it around or make it full screen. Atom starts to work again.

I've tried this in safe mode and I experience the same problem.
![image](https://cloud.githubusercontent.com/assets/9221137/11175853/7b838156-8bfc-11e5-84c9-36f6b10f5e63.png)

Edit: I've found an easy way to reproduce it somewhat consistently. If you open one atom instance and move it to the right or left side and then open a second atom instance and move it to the other side. The second atom instance will hang. As shown in the picture below.
![image](https://cloud.githubusercontent.com/assets/9221137/11176488/31238848-8c03-11e5-8ba9-e817b9729b75.png)

**Comment by LondonAppDev** [comment]
I get the same issue. I am running Windows 10 with latest updates and Atom 1.1.0. 

I have two projects in separate folders containing numerous JS files. I open the first project (right click folder > open with Atom) and snap to left of screen. All works fine. 

I open second project (right click folder > open with Atom) and snap to right of screen and this (the right) Atom instance becomes unresponsive. I can click the menu items at the top (file, edit, view etc...) and it shows the list, however if I select anything in the list nothing happens. I cannot toggle the tree view with the shortcut (Ctrl + \), and I cannot use search (Ctrl + t, or Ctrl + f). If the tree view is already visible then I can expand the folders but clicking a file doesn't do anything.

If I unsnap right window from the right size and resize it slightly, it starts to work again. If I snap it back to right after doing this is continues to work. If I close the right window, re-open, snap to right side of screen it works, but if I close all instances of Atom and repeat again I get the same issue. It looks like it's something to do with the second instance loading exactly the same as the first instance (snapped to left) and then snapping it to the right.

Step by step to re-produce:

 * Close all instances of Atom.
 * Open `Project A` by right clicking folder and choosing "Open with Atom".
 * Snap `Project A` to left of screen.
 * Open Windows Explorer, right click `Project B` and click "Open with Atom". 
 * Wait for it to fully open, then drag and snap to right side of screen.
 * Try to navigate around the right screen and you will see the issue.

**Comment by benjaminRomano** [comment]
Update: This is a problem with chromium and has been fixed in a newer version.

Check out https://github.com/atom/electron/issues/3501 for more info.

**Comment by 50Wliu** [comment]
Since this fix isn't in Atom yet I'm going to reopen until it is (because sometimes it takes a long time to get upstream Electron fixes into Atom).

**Comment by LondonAppDev** [comment]
Once this is fixed, will Chromium auto update or does it need to be manually updated?

**Comment by 50Wliu** [comment]
@LondonAppDev I'm working on updating Atom to Electron 0.36 right now (#9627).  After that you'll need to wait until an Atom version that uses 0.36 comes out.

**Comment by lukeapage** [comment]
This is confirmed fixed in 1.7.0
